### DISCUSSION TITLE
Can I make Istio custom metrics via Telemetry resource

### DISCUSSION THREAD

**Discussion by ElkRom** [istio/istio#44269] [Q&A]
I am looking into customizing Istio's metrics.
This [guide ](https://sirishagopigiri-692.medium.com/istio-customizing-metrics-3c58b57b45a) provides steps how to do it properly via EnvoyFilters.

Question is, can I achieve the same result via [Telemetry](https://istio.io/latest/docs/reference/config/telemetry/), without of using filters for each of my workload?

Any related examples will be appreciated.
Thanks

**Comment by zirain** [comment]
please checkout https://preliminary.istio.io/latest/docs/tasks/observability/metrics/telemetry-api/

**Reply by ElkRom** [reply]
Hi thanks, 
but I did not manage to find any insights about how to make it work via Telemetry API.

**Reply by ElkRom** [reply]
Hi @zirain,
Did you have a chance to find any working example which matches to my case?

**Reply by zirain** [reply]
I think that page has enough example.

**Reply by ElkRom** [reply]
Hi, sorry for disturbing with such stupid questions.

I would like to eleborate on what I have in my configuration file.
This block is presented in my helmValues file for Istio:
```
telemetry:
  enabled: true
  v2:
    # For Null VM case now.
    # This also enables metadata exchange.
    enabled: true
    metadataExchange:
      # Indicates whether to enable WebAssembly runtime for metadata exchange filter.
      wasmEnabled: false
    # Indicate if prometheus stats filter is enabled or not
    prometheus:
      enabled: true
      # Indicates whether to enable WebAssembly runtime for stats filter.
      wasmEnabled: false
      # overrides stats EnvoyFilter configuration.
      configOverride:
        inboundSidecar:
          metrics:
            - name: requests_total
              dimensions:
                request_url_path: request.url_path
                request_method: request.method
            - name: request_duration_milliseconds
              dimensions:
                request_url_path: request.url_path
                request_method: request.method
        outboundSidecar:
          metrics:
            - name: requests_total
              dimensions:
                request_url_path: request.url_path
                request_method: request.method
            - name: request_duration_milliseconds
              dimensions:
                request_url_path: request.url_path
                request_method: request.method
        gateway:
          metrics:
            - name: requests_total
              dimensions:
                request_url_path: request.url_path
                request_method: request.method
            - name: request_duration_milliseconds
              dimensions:
                request_url_path: request.url_path
                request_method: request.method
```

In addition to that i have added **extraStatTags**:
```
      - request_url_path
      - request_method
```

Such configuration works for me and I have _request_url_path_ property in a **requests_total**  metric, but I have an . 

Let me explain it:
I have log in API service,  the main endpoint for this service is accessible via _/account/<user_id>_
As we have multiple users, request can have different _user_id_, hence we have metric per  _/account/<user_id>_.

What I want to achieve is to make segregation based on **/account/*** and have single metric _requests_total_, for which only _count_ will change during a time based on amount of requests.

That is why, I did not manage to find any answers in a doc which you shared above, but managed to find working setup with[ EnvoyFilters](https://sirishagopigiri-692.medium.com/istio-customizing-metrics-3c58b57b45a)
