### DISCUSSION TITLE
configuration is invalid: HTTP route, redirect or direct_response is required

### DISCUSSION THREAD

**Discussion by patsevanton** [istio/istio#44304] [Q&A] [answered]
Hello! Thanks for Istio!
Istio Version - 1.17.1

I have config:
```
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: company-api-gitops
  namespace: istio-ingress
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - company-api.dev.ya.company.org
      port:
        name: http
        number: 80
        protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: company-api-gitops
  namespace: istio-ingress
spec:
  gateways:
    - company-api-gitops
  hosts:
    - company-api.dev.ya.company.org
  http:
    - corsPolicy:
        allowHeaders:
          - Origin
          - Content-Type
          - Accept
          - x-app-version
          - Authorization
          - Client-Authentication
          - x-app-version
          - x-device-platform
          - x-device-id
        allowOrigin:
          - '*'
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: gateway.dev.svc.cluster.local
            port:
              number: 80
```

When apply i get error:
```
admission webhook "validation.istio.io" denied the request: configuration is invalid: HTTP route, redirect or direct_response is required
```
How fix it ?
```
