### DISCUSSION TITLE
Outlier detection interval not working as expected in Istio traffic policy configuration

### DISCUSSION THREAD

**Discussion by BharathKumarRavichandran** [istio/istio#44437] [Q&A]
Hi folks!

We are planning to use outlier detection in traffic policy, but the interval field does not seem to be working as expected. The definition of the interval is the time interval between ejection sweep analysis, which means unhealthy hosts are ejected if the number of 5xx errors is greater than the configured consecutive 5xxErrors value consecutively when the sweep analysis is performed after the current interval. This is what we expected.

Our configuration:
```
  trafficPolicy:
    outlierDetection:
      baseEjectionTime: 60s
      consecutive5xxErrors: 2
      interval: 60m
      maxEjectionPercent: 100
```

Expected:
We've set the interval to 60 minutes, which we believe means that as long as the 5xx errors occur within that interval, the host won't be ejected. Technically, ten or more consecutive 500 can be made definitely within the 60m if the calls are made with an interval of 1 second. 

Observations:
However, when we tested the policy by sending four consecutive 5xx errors with a one-second gap between them, the host was ejected. We expected that the interval would allow for more than four consecutive 5xx errors to occur before the host would be ejected.

Can you clarify the definition of the interval field and whether our understanding is correct?
