### DISCUSSION TITLE
Question about Istio and MCS

### DISCUSSION THREAD

**Discussion by yboaron** [istio/istio#44661] [Q&A]
Hi folks, 

I have a question about Istio and MCS services, I'm doing my first steps with Istio, 
trying to check Istio service discovery with Multi Cluster Services (MCS).

What did I do? 

A. I first deployed Istio on 2 K8S KIND clusters,   using [1] commands.

B. Created a service on cluster1 

C. Exported the service from step B (by creating serviceexport resource)

Steps A,B and C are detailed [here](https://github.com/jewertow/istio-playground/tree/mcs-submariner/mcs-submariner)

D. The relevant serviceimport with VIP address resource created on cluster2  by MCS controller (I used Submariner Lighthouse as MCS controller)

E. Checking the logs of Istiod pod on cluster2 , I can see that istiod failed to process ServiceImport  with [3] error. 

it seems that istiod is looking also for local service in cluster2,  I think this is the relevant code : https://github.com/istio/istio/blob/0feeb55227e77d26283ca3b34649a81609e3b8db/pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go#L164-#L176

Did I miss something with Istio configuration? 
Could you please explain above error?
Is there any doc/link that describes how to configure/test Istio and MCS ?

Thanks in advance 

[1] 

# deploy Istio on Cluster1
istioctl install -y -n istio-system -f cp-1.yaml
# deploy Istio on Cluster2
istioctl install -y -n istio-system -f cp-2.yaml

cp-1.yaml content:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: control-plane
spec:
  values:
    global:
      meshID: mesh
      multiCluster:
        clusterName: cluster1
      network: network
    pilot:
      env:
        PILOT_USE_ENDPOINT_SLICE: "true"
        ENABLE_MCS_SERVICE_DISCOVERY: "true"
        ENABLE_MCS_HOST: "true"

```

cp-2.yaml content:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: control-plane
spec:
  values:
    global:
      meshID: mesh
      multiCluster:
        clusterName: cluster2
      network: network
    pilot:
      env:
        PILOT_USE_ENDPOINT_SLICE: "true"
        ENABLE_MCS_SERVICE_DISCOVERY: "true"
        ENABLE_MCS_HOST: "true"

```
[2] 

kubectl config use-context cluster1
kubectl create namespace foo
kubectl label namespace foo istio-injection=enabled
kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.17/samples/httpbin/httpbin.yaml -n foo

[3] 

2023-05-01T14:30:47.314504Z     warn    kube    failed processing add event for ServiceImport foo/httpbin in cluster cluster2. No matching service found in cluster
