### DISCUSSION TITLE
How to make istio supports http1.1 only?

### DISCUSSION THREAD

**Discussion by ningyougang** [istio/istio#44925] [General]
## use curl to access istio's gateway with specific protocol: http1.1

![image](https://github.com/istio/istio/assets/11749867/0a6554b1-1919-4e47-9b30-fce2e492fbc7)

## use curl to access without any protocol

![image](https://github.com/istio/istio/assets/11749867/20d25a00-e0da-4d32-8f31-f440115c5968)

We can see, if don't specify any protocol, it will use `http2`, 

My question is:
how to make istio to allow http1.1 only (disable http2)?
which mean, if don't specify protocol, the curl will use `http1.1` by default and the http status code should be `200` too.

Can add some envofyfilter to solve it?
(Btw, i also refered to: https://github.com/istio/istio/issues/14708, but did not solve it)

Another silimiar article: https://discuss.istio.io/t/restrict-istio-to-offer-http1-1-for-https/8444

**Comment by ningyougang** [comment]
Btw, i added below envoyfilter
```
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: HTTP1
```
When i use curl to access without protocol
![image](https://github.com/istio/istio/assets/11749867/97d8a0de-7240-49d8-aada-627958f2a233)
It still uses http1.1 to access. but a good message, it said `Perhaps, peer does not support HTTP/2 properly`

**Comment by ningyougang** [comment]
I found the key configuration in envoy
```
static_resources:
  listeners:
  - name: https_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - transport_socket:                                     
        name: envoy.transport_sockets.tls                   
        typed_config:                                       
          '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            alpn_protocols:
            - http/1.1   # this is the key point
            tls_certificates:                               
              - certificate_chain:                          
                  filename: "/etc/envoy/server.crt"    
                private_key:                                
                  filename: "/etc/envoy/server.key" 
```

But for istio, i wrote a envoyfilter, but does not work as expected.
envoyfilter as below
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  ...
  name: testfilter
  namespace: yournamespace
spec:
  configPatches:
  - applyTo: FILTER_CHAIN
    match:
      listener:
        portNumber: 8443
    patch:
      operation: MERGE
      value:
        transport_socket:
          name: envoy.transport_sockets.tls
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
            common_tls_context:
              alpn_protocols:
              - http/1.1
 ```
The reason is, for `applyTo: FILTER_CHAIN`, does not support `REPLACE` just support `MERGE`: https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-Patch-Operation. 
So we have no choice, must use `MERGE` operation for `applyTo: FILTER_CHAIN`

After merged above configuration, the `alpn_protocols` part configuration as below(Btw, i got again from like `curl http://localhost:15000/config_dump`) 
![image](https://github.com/istio/istio/assets/11749867/b755340d-bd72-4489-9dd7-c6ff33cd8983)
