### DISCUSSION TITLE
Verb * for clusterroles in RBAC in operator chart

### DISCUSSION THREAD

**Discussion by kpu32167** [istio/istio#45299] [Q&A] [answered]
Hi. Can anyone explain why istio operator needs such wide RBAC rights ? Operator really needs rights to create clusterroles ? 
```yaml
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - roles
  - rolebindings
  verbs:
  - '*'
```
