### DISCUSSION TITLE
Internal traffic management using HTTPRoute

### DISCUSSION THREAD

**Discussion by v-sag** [istio/istio#45543] [Q&A] [answered]
Hello,

I have 2 deployments with 2 respective services, and 1 service (let's refer to it as the common service) that targets both deployment pods. Then, as I am trying to use Gateway API only, I have created an HTTPRoute that has as parent ref the common service and applies percentage traffic 100% on the first service only. However, when I am inside a pod in my cluster and I try to hit the common service, I see responses from both deployments. I have been following [this guide](https://istio.io/latest/docs/tasks/traffic-management/traffic-shifting/). What am I missing? I am adding the common service and the HTTPRoute below for reference:

```
apiVersion: v1
kind: Service
metadata:
  name: nginx-global
  labels:
    deployment: nginx
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 80
      targetPort: 80
  selector:
    type: nginx
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: nginx-global
spec:
  parentRefs:
  - kind: Service
    name: nginx-global
  rules:
  - backendRefs:
    - name: nginx-v1
      port: 80
      weight: 100
```

Thanks in advance.
