### DISCUSSION TITLE
Skip tracing for Prometheus requests

### DISCUSSION THREAD

**Discussion by andreivaloshyn** [istio/istio#45680] [Q&A]
Hello,
I need to skip traces for Prometheus call to `/metrics` endpoint.
I tried to change `X-B3-Sampled` request header to "0" with `VirtualService` and with `EnvoyFilter`, but each time in response I see X-B3-Sampled: 1 and unwanted traces are in place :(
I can delete/add/update custom tags in the same EnvoyFilter or VirtualSerive but I can't change `X-B3-Sampled`
Is it possible to rewrite `X-B3-Sampled` to "0"  based on `/metrics` path and(or) `user-agent` HTTP header to avoid unnecessary traces

**Comment by howardjohn** [comment]
If you use https://istio.io/latest/docs/ops/integrations/prometheus/#option-1-metrics-merging, the prometheus metrics requests will bypass envoy and thus the tracing. I am not sure about other options though

**Comment by husnialhamdani** [comment]
I'm using this way to remove unwanted Traces, like Prometheus requests.

Istio traces -> Telemetry API -> Istio Extension Provider -> OTELCollector -> Jaeger.

```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: default
  namespace: some-namespace
spec:
  tracing:
  - providers:
    - name: otel-provider
```

Istiod Config:
```
 meshConfig:
    extensionProviders:
    - name: otel-provider
      opencensus:
        context:
        - B3
        port: 55678
        service: opentelemetry-collector.some-namespace.svc.cluster.local
```     

OTELCollector config:
```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry-collector
spec:
  mode: deployment
  replicas: 1
  config: |
    receivers:
      opencensus:
        endpoint: 0.0.0.0:55678
      zipkin:
        endpoint: 0.0.0.0:9411
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      tail_sampling:
        policies:
          - name: drop_noisy_traces_url_user_agent
            type: string_attribute
            string_attribute:
              key: user_agent
              values:
                - Prometheus.*
              enabled_regex_matching: true
              invert_match: true
          - name: drop_noisy_traces_url_http_url
            type: string_attribute
            string_attribute:
              key: http.url
              values:
                - http:\/\/zipkin.*
                - http:\/\/.*\/metrics
                - http:\/\/.*\/actuator\/prometheus
                - http:\/\/opentelemetry.*
                - \/actuator.*
              enabled_regex_matching: true
              invert_match: true
          - name: drop_noisy_traces_url_http_url_internal
            type: string_attribute
            string_attribute:
              key: http.path
              values:
                - http:\/\/.*\/actuator\/prometheus
              enabled_regex_matching: true
              invert_match: true
    exporters:
      logging:
        loglevel: info
      jaeger:
        endpoint: <JAEGER-ENDPOINT>
        tls:
          insecure: true
    extensions:
      zpages:
        endpoint: 0.0.0.0:55679
    service:
      extensions:
        - zpages
      pipelines:
        traces:
          receivers:
            - zipkin
            - opencensus
            - otlp
          processors:
            - tail_sampling
          exporters:
            - logging
            - jaeger
```
