### DISCUSSION TITLE
Transform Replies from Istio Ingress Gateway to JSON

### DISCUSSION THREAD

**Discussion by markusobsil** [istio/istio#45697] [Q&A] [answered]
Hi, 
I face the problem, that I need the Istio Ingress Gateway to reply in case of errors (e.g. no healthy upstream, ...) in JSON format, instead of plain html. This is needed, because external clients (which I do not control) are accessing APIs in the cluster, and they expect JSON format. For sure, this does not solve, if there is an actual error on my systems, but at least their application will not crash, when trying to parse the HTML reply as JSON. So I wrote a envoy filter, which takes care about that, and I would like to get some feedback, if this is a appropriate solution, or if there is a better way to do it?

This envoy filter transforms every local reply from a specific gateway in a specific namespace into JSON with a status and message. 

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: create-json-output
  namespace: <my-ingress-gateway-namespace>
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          local_reply_config:
            body_format:
              json_format:
                status:  "%RESPONSE_CODE%"
                message: "%LOCAL_REPLY_BODY%"
              content_type: "application/json"
  workloadSelector:
    labels:
      app: <my-ingress-gateway-label>
```

Thank you very much!
