### DISCUSSION TITLE
Egress Gateway not working for HTTPS Requests

### DISCUSSION THREAD

**Discussion by ChrisJBurns** [istio/istio#45824] [Q&A]
Am running the following code and when I try to exec onto a pod (with a sidecar) within the infra namespace and run `curl -sSL -o /dev/null -D - https://edition.cnn.com/politics`, I get `curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to edition.cnn.com:443` . Am following https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/#egress-gateway-for-https-traffic

The http traffic worked fine. But the https does not.
Here's my yamls
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cnn
  namespace: istio-system
spec:
  hosts:
  - edition.cnn.com
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: egress-gateway
  namespace: istio-system
spec:
  selector:
    istio: egress-gateway
  servers:
  - port:
      number: 443
      name: tls
      protocol: TLS
    hosts:
    - edition.cnn.com
    tls:
      mode: PASSTHROUGH
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-cnn
  namespace: infra
spec:
  host: istio-egress-gateway.istio-system
  subsets:
  - name: cnn
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-cnn-through-egress-gateway
  namespace: infra
spec:
  hosts:
  - edition.cnn.com
  gateways:
  - mesh
  - istio-system/egress-gateway
  tls:
  - match:
    - gateways:
      - mesh
      port: 443
      sniHosts:
      - edition.cnn.com
    route:
    - destination:
        host: istio-egress-gateway.istio-system
        subset: cnn
        port:
          number: 443
  - match:
    - gateways:
      - istio-system/egress-gateway
      port: 443
      sniHosts:
      - edition.cnn.com
    route:
    - destination:
        host: edition.cnn.com
        port:
          number: 443
      weight: 100
```

Istio version: 1.18

Is worth mentioning, it works when I add the `ServiceEntry` on it's own. But I get the curl error above when adding the `Gateway`, `DestinationRule` and `VirtualService`. Also the result of `istioctl pc routes $(kubectl get pods -l istio=egress-gateway -o jsonpath='{.items[0].metadata.name}' -n istio-system).istio-system -o json` is just

```json
[
    {
        "virtualHosts": [
            {
                "name": "backend",
                "domains": [
                    "*"
                ],
                "routes": [
                    {
                        "match": {
                            "prefix": "/stats/prometheus"
                        },
                        "route": {
                            "cluster": "prometheus_stats"
                        }
                    }
                ]
            }
        ]
    },
    {
        "virtualHosts": [
            {
                "name": "backend",
                "domains": [
                    "*"
                ],
                "routes": [
                    {
                        "match": {
                            "prefix": "/healthz/ready"
                        },
                        "route": {
                            "cluster": "agent"
                        }
                    }
                ]
            }
        ]
    }
]
```

**Comment by ChrisJBurns** [comment]
## HTTP
The following are the http YAML's that work perfectly fine, it's just the https that doesn't work.
```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cnn
  namespace: istio-system
spec:
  hosts:
  - edition.cnn.com
  ports:
  - number: 80
    name: http-port
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: egress-gateway
  namespace: istio-system
spec:
  selector:
    istio: egress-gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - edition.cnn.com
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-cnn
  namespace: infra
spec:
  host: istio-egress-gateway.istio-system.svc.cluster.local
  subsets:
  - name: cnn
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-cnn-through-egress-gateway
  namespace: infra
spec:
  hosts:
  - edition.cnn.com
  gateways:
  - istio-system/egress-gateway
  - mesh
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: istio-egress-gateway.istio-system.svc.cluster.local
        subset: cnn
        port:
          number: 80
      weight: 100
  - match:
    - gateways:
      - istio-system/egress-gateway
      port: 80
    route:
    - destination:
        host: edition.cnn.com
        port:
          number: 80
      weight: 100
```

Although I still can't see anything in the routes config when I run `istioctl pc routes $(kubectl get pods -l istio=egress-gateway -o jsonpath='{.items[0].metadata.name}' -n istio-system).istio-system`


```json
[
    {
        "virtualHosts": [
            {
                "name": "backend",
                "domains": [
                    "*"
                ],
                "routes": [
                    {
                        "match": {
                            "prefix": "/stats/prometheus"
                        },
                        "route": {
                            "cluster": "prometheus_stats"
                        }
                    }
                ]
            }
        ]
    },
    {
        "virtualHosts": [
            {
                "name": "backend",
                "domains": [
                    "*"
                ],
                "routes": [
                    {
                        "match": {
                            "prefix": "/healthz/ready"
                        },
                        "route": {
                            "cluster": "agent"
                        }
                    }
                ]
            }
        ]
    }
]
```

**Reply by howardjohn** [reply]
The HTTPs example works for me if you replace `istio-egress-gateway.istio-system` -> `istio-ingressgateway.istio-system.svc.cluster.local` which is what you have in the HTTP example.

**Reply by howardjohn** [reply]
BTW, Envoy routes are an HTTP concept. HTTPS is not HTTP and uses tcp proxy, which is a part of the `istioctl proxy-config listener`, not routes.

**Reply by laiminhtrung1997** [reply]
>The HTTPs example works for me if you replace istio-egress-gateway.istio-system -> istio-ingressgateway.istio-system.svc.cluster.local which is what you have in the HTTP example.

@howardjohn He wants to configure the egress gateway. Please let me know why you advised him to replace the ingress gateway. Was this a typo? Or did I not understand the configurations?

**Reply by howardjohn** [reply]
sorry typo. I meant to just add the svc.cluster.local suffix

**Comment by ashrith06** [comment]
I'm seeing similar failures for my mTLS setup:
HTTP client->Egress Gateway ->mTLS Server this flow is working
HTTPS Client->Egress Gateway ->mTLS Server this is not working.

**Comment by laiminhtrung1997** [comment]
Any news on this?

**Comment by laiminhtrung1997** [comment]
```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio.io/use-waypoint: waypoint
    istio.io/dataplane-mode: ambient
  name: istio-egress
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  labels:
    istio.io/waypoint-for: all
  name: waypoint
  namespace: istio-egress
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - allowedRoutes:
      namespaces:
        from: Same
    name: mesh
    port: 15008
    protocol: HBONE
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: istio-egress
  namespace: istio-egress
  labels:
    istio.io/use-waypoint: waypoint
spec:
  hosts:
  - httpbin.org
  ports:
  - name: https
    number: 443
    protocol: HTTPS
  location: MESH_EXTERNAL
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: istio-egressgateway
  namespace: istio-egress
spec:
  host: waypoint.istio-egress.svc.cluster.local
  subsets:
  - name: istio-egress
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-egress
  namespace: istio-egress
spec:
  hosts:
  - httpbin.org
  gateways:
  - mesh
  - common-gateway/herculesdev9-egressgateway
  tls:
  - match:
    - gateways:
      - mesh
      port: 80
      sniHosts:
      - httpbin.org
    route:
    - destination:
        host: istio-egressgateway.common-gateway.svc.cluster.local
        subset: istio-egress
        port:
          number: 80
  - match:
    - gateways:
      - common-gateway/herculesdev9-egressgateway
      port: 80
      sniHosts:
      - httpbin.org
    route:
    - destination:
        host: httpbin.org
        port:
          number: 80
      weight: 100
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: istio-egress
  namespace: istio-egress
spec:
  podSelector: {}
  ingress:
  - {}
  egress:
  - ports:
    - protocol: TCP
      port: 15008
  - ports:
    - protocol: TCP
      port: 15012
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: common-gateway
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: direct-httpbin-to-egress-gateway
  namespace: istio-egress
spec:
  parentRefs:
  - kind: ServiceEntry
    group: networking.istio.io
    name: istio-egress
  rules:
  - backendRefs:
    - name: waypoint
      port: 15008
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: forward-httpbin-from-egress-gateway
  namespace: istio-egress
spec:
  parentRefs:
  - name: waypoint
  hostnames:
  - httpbin.org
  rules:
  - backendRefs:
    - kind: Hostname
      group: networking.istio.io
      name: httpbin.org
      port: 443
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: originate-tls-for-httpbin-org
  namespace: istio-egress
spec:
  host: httpbin.org
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE
```

My YAML files don't work too.
