### DISCUSSION TITLE
Help configuring Istio with with an Artemis multi node cluster and statefulset/headless services.

### DISCUSSION THREAD

**Discussion by lordigon** [istio/istio#46077] [Q&A]
Hi all, as I'm pretty new to Istio I need some help on how to configure it for my use case.
I'm using Artemis broker on kubernetes with this CRD

```yaml
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: exoo
spec:
  deploymentPlan:
    size: 2
    image: placeholder
    persistenceEnabled: true
    messageMigration: true
    labels:
      app: artemis-cluster
  acceptors:
    - name: tcp-mqtt
      protocols: MQTT
      port: 61616
      expose: false
      sslEnabled: false
    - name: tcp-mqtt-tls
      protocols: MQTT
      port: 61617
      expose: false
      sslEnabled: true
      needClientAuth: true
      verifyHost: false
  console:
    expose: false
```

that creates two statefulsets

```bash
NAME                                                   READY   STATUS    RESTARTS       AGE
exoo-ss-0                                              2/2     Running   0              163m
exoo-ss-1                                              2/2     Running   0              163m
```

and some services

```bash
NAME                      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)              AGE
exoo-hdls-svc             ClusterIP   None             <none>        8161/TCP,61616/TCP   164m
exoo-ping-svc             ClusterIP   None             <none>        8888/TCP             164m
exoo-tcp-mqtt-0-svc       ClusterIP   10.98.65.47      <none>        61616/TCP            164m
exoo-tcp-mqtt-1-svc       ClusterIP   10.101.203.69    <none>        61616/TCP            164m
exoo-tcp-mqtt-tls-0-svc   ClusterIP   10.110.174.162   <none>        61617/TCP            164m
exoo-tcp-mqtt-tls-1-svc   ClusterIP   10.102.132.166   <none>        61617/TCP            164m
```

I would like to configure an Ingress Gateway that exposes the service on TCP port 61617 (MQTT+TLS protocol with SSL Passthrough) pointing to both nodes of the Artemis cluster (namely exoo-ss-0 and exoo-ss-1).
Do I have to use Istio ServiceEntry?
I read something about configuring Istio with headless services and Statefulsets and tryed something without success.
Is it possible to have a solution that automatically manages creation/deletion of Artemis nodes depending on the traffic?
