### DISCUSSION TITLE
Combine JWT claim based routing and External Authorization

### DISCUSSION THREAD

**Discussion by JulianSchmidgall** [istio/istio#46638] [Q&A]
Hi, I want to combine the two features [JWT claim based routing](https://istio.io/latest/docs/tasks/security/authentication/jwt-route/) and [External Authorization](https://istio.io/latest/docs/tasks/security/authorization/authz-custom/). Are there any example or hints on how to get that running? 🚀 

I started with setting up the External Authorization, which works fine. The oauth2-proxy adds an JWT to the request.
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: istio-ingressgateway-oauth2-proxy
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  action: CUSTOM
  provider:
    name: oauth2-proxy
  rules:
  - {}
---
extensionProviders:
- name: oauth2-proxy
  envoyExtAuthzHttp:
    service: oauth2-proxy.oauth2-proxy.svc.cluster.local
    port: 80
    includeRequestHeadersInCheck:
      - authorization
      - cookie
    includeAdditionalHeadersInCheck:
      "X-Auth-Request-Redirect": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
    headersToUpstreamOnAllow:
      - authorization
      - path
      - x-auth-request-user
      - x-auth-request-email
      - x-auth-request-access-token
    headersToDownstreamOnDeny:
      - content-type
      - set-cookie
```

I further added a RequestAuthentication and a VirtualService:
```
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  jwtRules:
  - issuer: "testing@secure.istio.io"
    jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.18/security/tools/jwt/samples/jwks.json"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
  namespace: foo
spec:
  hosts:
    - "*"
  gateways:
    - istio-ingress/ingress-gateway
  http:
    - match:
        - uri:
            prefix: /headers
          headers:
            "@request.auth.claims.groups":
              exact: group1
        - uri:
            prefix: /no-headers
      route:
        - destination:
            port:
              number: 8000
            host: httpbin
```
When I send a request to the `/headers` endpoint I directly receive a HTTP 404 back. There is no redirect to the configured OAuth provider. Therefor I assume that once the request is routed, the validated JWT claims are not yet in the request.

The endpoint `/no-headers` works as expected. The request got redirected to the OAuth provider.

I would be happy about any hints on how to combine those two features. Thanks a lot!

**Comment by agreedSkiing** [comment]
You could add a second AuthorizationPolicy that uses the `action: ALLOW` which in OpenShift Service Mesh version 2.4.2, that is Istio 1.16, uses the custom and then the normal. 
```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: custom-authorization
spec:
  selector:
    matchLabels:
      app: backend
  action: CUSTOM
  provider:
    name: external-authz-http
  rules:
    - to:
        - operation:
            methods:
              - "GET"
            paths:
              - "/foos"
```
```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: backend-authorization
spec:
  selector:
    matchLabels:
      app: backend
  action: ALLOW
  rules:
    - to:
        - operation:
            methods:
              - "GET"
            paths:
              - "/foos"
      from:
        - source:
            requestPrincipals:
              - https://keycloak-test.svc.cluster.local/auth/realms/foo-test/*
      when:
        - key: request.auth.claims[roles]
          values:
            [
              "admin",
            ]
```
