### DISCUSSION TITLE
Mirroring to the multi-destination from 1.19.0-rc.0

### DISCUSSION THREAD

**Discussion by cychoi1z** [istio/istio#46836] [Q&A]
Hello, folks.

The Istio 1.19.0-rc.0 version incorporates the mentioned [PR,](https://github.com/istio/istio/pull/45944/files) and I made an attempt to leverage the mirroring feature for multi-destinations. Nevertheless, I encountered an issue where the traffic wasn't being properly mirrored to the specified destinations. In my case, I utilized httpbin with subset v1/v2 and v3 for testing purposes.

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: httpbin
spec:
  host: httpbin
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
    - name: v3
      labels:
        version: v3
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
    - httpbin
  http:
    - route:
        - destination:
            host: httpbin
            subset: v1
          weight: 100
      mirrors:
        - destination:
            host: httpbin
            subset: v2
        - destination:
            host: httpbin
            subset: v3
```

Is there anyone who can guide me where I can start digging into more for troubleshooting?
