### DISCUSSION TITLE
Intercept request headers

### DISCUSSION THREAD

**Discussion by marksugar** [istio/istio#46967] [Q&A]
How do I get the headers of requests coming from upstream for routing	？

```
# apiVersion: networking.istio.io/v1beta3
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello
  namespace: test1
spec:
  hosts:
  - "hello"
  gateways:
  - istio-system/cookie-gateway
  - mesh
  http:
  - name: canary
    match:
    - headers:
        regex:  { ".*test:true.*"}
    route:
    - destination:
        host: go-test-2
  - name: default
    route:
    - destination:
        host: hello2
```
If test:true is carried is routed to go-test-2
I should have done this

thanks
