### DISCUSSION TITLE
How to achieve routing by url and then split traffic by header?

### DISCUSSION THREAD

**Discussion by caibirdme** [istio/istio#47134] [Q&A]
I have an istio-gateway to handle sourth-north trafic, and I created a virtualservice for that gateway to make requests with different urls can be routed to different SVCs, something like:
```yaml
host:
  - example.com # domain for my website
http:
  - match:
      - url:
          prefix: /a/
      - url:
          prefix: /b/c
    route:
      - destination:
          host: foo.ns.svc.cluster.local
          port: 8082
  - match:
      - url:
          prefix: /x
    route:
      - destination:
          host: bar.ns.svc.cluster.local
          port: 9952
  # and many other rules, just like nginx location directives
```

And then, I want to achieve that all the traffic that will be routed to foo.ns.svc.cluster.local can be split by header and then routed to different subsets. Just like doing grayscale publish.
```yaml
kind: DestinationRule
spec:
  host: 
    - foo.ns.svc.cluster.local 
  subsets:
    - labels:
        version: v1
      name: v1
    - labels:
        version: v1
      name: v2
```
```yaml
kind: VirtualService
spec:
  host: foo.ns.svc.cluster.local 
  http:
    - match:
        - headers:
            my-env:
              exact: v1
      route:
        - destination:
            host: foo.ns.svc.cluster.local
            subset: v1
    - match:
        - headers:
            my-env:
              exact: v2
      route:
        - destination:
            host: foo.ns.svc.cluster.local
            subset: v2
```
But this didn't work. Traffic in the mesh can go to desired subset, but traffic from outside of the cluster(which go through the gateway) go to random subset.
The reason why I created an individual vs for foo.ns.svc.cluster.local is that I want all the traffic can apply this routing rule no matter where it comes from(outside mesh or inside mesh).
Am I missing something, or how to achieve this?
