### DISCUSSION TITLE
What's the *strict subset* means for delegate?

### DISCUSSION THREAD

**Discussion by caibirdme** [istio/istio#47146] [Q&A]
from virtualservice doc:
> NOTE:
>
> - Only one level delegation is supported.
> - The delegate’s HTTPMatchRequest must be a **strict subset** of the root’s, otherwise there is a conflict and the HTTPRoute will not take effect.

I want to know what the strict subset mean or what the HTTPMatchRequest config merge process look like?

For example, Can I specify the uri match rules in root vs and specify headers match rules in delegate vs, something like:
```yaml
hosts:
  - mysite.com
http:
  - match:
    - uri:
        prefix: /a
    - uri:
        prefix: /b
    - uri:
        exact: /hello/friend
    delegate:
      name: a-vs
      namespace: test
---
# a-vs
http:
  - match:
    - headers:
        x-env:
          exact: v1
    route:
      - destionation:
          host: xxx
          subset: v1
  - match:
    - headers:
        x-env:
          exact: v2
    route:
      - destionation:
          host: xxx
          subset: v2
```
