### DISCUSSION TITLE
What's the order if add multi filters in one EnvoyFilter

### DISCUSSION THREAD

**Discussion by caibirdme** [istio/istio#47248] [Q&A]
say:
```yaml
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        filterClass: AUTHN
        operation: ADD
        value: {}   # my rate limiter
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        filterClass: AUTHN
        operation: ADD
        value: {} #  my fraud detection
```
The doc just tell the order between different EnvoyFilters, but what about within one EnvoyFIlter?
