### DISCUSSION TITLE
Who's modifying the istio-sidecar-injector MutatingWebhookConfiguration?

### DISCUSSION THREAD

**Discussion by benjaminxie** [istio/istio#47919] [Q&A] [answered]
I've installed Istio using the helm charts and noticed that after installing the gateway chart, the manifest for the istio-sidecar-injector MutatingWebhookConfiguration is different from what I see in the chart itself. Namely, entries are being added to .webhooks[].namespaceSelector.matchExpressions:
```
- key: control-plane
  operator: NotIn
  values:
  - "true"
- key: kubernetes.azure.com/managedby
  operator: NotIn
  values:
  - aks
```
After using kubectl explain to get some background on what each part of that path does, it seems sensible and intentional that these are added. Nonetheless, can someone tell me how they're being added? I see it isn't templated in via helm templating.

Thanks in advance!

P.S. I originally needed to know because I'm installing Istio via ArgoCD and it complains that the MutatingWebhookConfiguration is "out of sync" due to this difference between the "live" manifest in the cluster and the "desired" manifest of what it saw at the time of kubectl apply. Although ArgoCD has [custom diffing](https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/) for ignoring this, I was hesitant to ignore something I didn't understand.
