### DISCUSSION TITLE
Circuit breaker not working

### DISCUSSION THREAD

**Discussion by noor-muradi** [istio/istio#48204] [General]
I have deployed a sample app (helloword) with two versions (v1 and v2), I have defined circuit breaker to stop sending traffic to unhealthy deployment, after I delete manually the v2 deployment, and observing the kiali graph, it does not seem to stop the traffic to unhealthy deployment (v2).

Deployment.yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    version: v1
  name: hello-v1
  namespace: practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
        version: v1
    spec:
      containers:
      - image: noormuradi/v1
        name: hello-v1

---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: helloworld

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    version: v2
  name: hello-v2
  namespace: practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
        version: v2
    spec:
      containers:
      - image: noormuradi/v2
        name: hello-v2
```
Gateway-vs-dr.yaml:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: hello-gateway
  namespace: practice
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - "hello.example.com"

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
 name: hello
 namespace: practice
spec:
 hosts:
 - "hello.example.com"
 gateways:
 - hello-gateway
 http:
 - route:
   - destination:
       host: helloworld
       subset: v1
     weight: 80
   - destination:
       host: helloworld
       subset: v2
     weight: 20
---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: hello
  namespace: practice
spec:
  host: helloworld
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 1
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
    outlierDetection:
      consecutive5xxErrors: 1
      interval: 1s
      baseEjectionTime: 3m
      maxEjectionPercent: 100

```

![image](https://github.com/istio/istio/assets/24589033/95037d54-6c7e-4c8e-b841-1c2b37398aaa)

![image](https://github.com/istio/istio/assets/24589033/29fe3949-0640-49aa-af59-fbacefa72737)

```
while true; do curl hello.example.com; sleep 1; done
<h1>V1</h1>
<h1>V1</h1>
<h1>V1</h1>
<h1>V1</h1>
<h1>V1</h1>
no healthy upstream
<h1>V1</h1>
<h1>V1</h1>
<h1>V1</h1>
<h1>V1</h1>
<h1>V1</h1>
no healthy upstream
<h1>V1</h1>
<h1>V1</h1>
<h1>V1</h1>
<h1>V1</h1>
no healthy upstream
<h1>V1</h1>
<h1>V1</h1>
```

**Comment by howardjohn** [comment]
The circuit breaker is about evicting endpoints _within_ a group (service+subset+port). 

So you have a group (helloworldv2), with 0 endpoints. You explicitly send to this (via the VS), and there is no endpoints so it fails. The circuit breaker is irrelevant here.

You can kind of work around this in a way using "locality lb". This was originally intended for other purposes but works here:

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: echo-versions
spec:
  host: echo-versions.default.svc.cluster.local
  trafficPolicy:
    connectionPool:
      http:
        maxRequestsPerConnection: 1
    loadBalancer:
      simple: ROUND_ROBIN
      localityLbSetting:
        enabled: true
        failoverPriority:
        - version=v1
        - version=v2
    outlierDetection:
      consecutive5xxErrors: 1
      interval: 1s
      baseEjectionTime: 1m
```

And then do not use subsets at all. This will send requests first to things matching version=v1, then to version=v2 if those are failing.
