### DISCUSSION TITLE
Istio gateway returning 200 instead of 503 when the upstream is not avaialble

### DISCUSSION THREAD

**Discussion by prrs** [istio/istio#48293] [Q&A] [answered]
Sample log

```
{"trace_id":null,"method":"POST","upstream_transport_failure_reason":null,"downstream_tls_version":"TLSv1.3","duration":0,"c │
│ onnection_termination_details":null,"response_code_details":"no_healthy_upstream","request_id":"9648-a968-ac7004fefc61","downstream_remote_addre │
│ ss":"10.30.124.246:5722","x_forwarded_for":"forwarded_ip","upstream_service_time":null,"bytes_sent":0,"downstream_local_address":"downstream_ip:8443","start_ti │
│ me":"2023-12-12T07:25:25.033Z","downstream_tls_cipher":"TLS_AES_128_GCM_SHA256","connection_id":15900,"protocol":"HTTP/2","upstream_cluster":"outbound|19530|| │
│ milvusdb.milvus.svc.cluster.local","upstream_local_address":null,"requested_server_name":"destination-domain.cl","response_flags":"UH","route_name":null,"path":"/milvus.proto.milvus.MilvusService/LoadCollection","authority":"destination:443","upstream_host":null,"upstream_request_attempt_count":0,"response_code":200,"user_agent":"grpc-java-netty/1.46.0","bytes_received" │
│ :0} 
```

I have an istio gateway -> virtual service -> destination rule -> deployment.

Dropping the virtual service 

```
spec:
  gateways:
  - istio-system/internal-gateway
  hosts:
  - domain
  http:
  - match:
    - headers:
        dbname:
          exact: <dbname_placeholder>
    retries:
      attempts: 0
      perTryTimeout: 5s
      retryOn: 5xx,connect-failure,refused-stream,unavailable,cancelled,resource-exhausted,internal,retriable-status-codes
    route:
    - destination:
        host: <service_endpoint>
        port:
          number: <port_number>
    timeout: 15s
```

destination rule
```
spec:
  host: service_endpoint
  trafficPolicy:
    connectionPool:
      http:
        useClientProtocol: true
      tcp:
        connectTimeout: 1s
    outlierDetection:
      consecutive5xxErrors: 5
      consecutiveGatewayErrors: 5
    tls:
      caCertificates: /etc/identity/ca/cacerts.pem
      clientCertificate: /etc/identity/client/certificates/client.pem
      mode: MUTUAL
      privateKey: /etc/identity/client/keys/client-key.pem
```

I do have two setup, when client is REST, I get 503 in response code but for gRPC it says 200 with details in "response_code_details".

I have downsclaed all the deploymenst and statefulset to 0 to ensure that there is no place to route. But, the behaviour remain same. I want to configure retry based on response code at gateway level, otherwise I need to force handle in client. Please suggest, thanks in advance.

P.S- I see an old thread pointing similiar issue, for telemetry. https://discuss.istio.io/t/grpc-status-codes-in-telemetry/354
