### DISCUSSION TITLE
Got Empty content with integrating skywalking

### DISCUSSION THREAD

**Discussion by sky92zwq** [istio/istio#48325] [Q&A] [answered]
I used **kind** to create a k8s cluster, then installed **istio**. and followed this [blog](https://skywalking.apache.org/blog/how-to-use-skywalking-for-distributed-tracing-in-istio/) to integrate **skywalking**.
But I got empty web content.

**env**:
Kubernetes 1.27.3
Istio 1.20
SkyWalking 9.1.0

 Then, I followed [this handbook](url) to do istio installation with operator,
_BTW,  I want to know if it is right that we just need add a command `istioctl operator init` after installation with istioctl,
then operator controller will watch namespace _istio-system_.
Then we add `kubectl apply -f xxx` to configure skywalking, it should work._
But in fact whenever I installed istio by istioctl or by operator, It all does not work. I got no data of services.

May someone give me some ideas?(I am learning troubleshooting istio k8s and skywalking, they are really complex. )

**Comment by rootsongjc** [comment]
[This blog](https://skywalking.apache.org/blog/how-to-use-skywalking-for-distributed-tracing-in-istio/) was written by me in December last year, and it has been a year since then. Many software versions have undergone significant changes. This week, I will reinstall and test it again, so please stay tuned for my updates.
P.S
1. [Here is](https://jimmysong.io/blog/distributed-tracing-with-skywalking-in-istio/) the Chinese version of this blog.
2. The handbook link you mentioned is not correct.

**Comment by rootsongjc** [comment]
I just started installing Istio and SkyWalking in Kind, and the blog still applies. Just make some adjustments to the SkyWalking and Istio versions. I'm using Kubernetes 1.27.3 and Istio 1.20.1, and everything works fine. 

You should run `istioctl operator init` first, and after that, install Istio.

My blog has an error: You should execute the following command to install Istio.

```bash
kubectl apply -f https://raw.githubusercontent.com/istio/istio/master/samples/addons/extras/skywalking.yaml
```

PS. I've fixed the error in my blog.

**Comment by hanxiaop** [comment]
It's not recommended to use `istioctl operator init` - which will initiate a in-cluster operator controller. I think you can just use `istioctl install -f file.yaml` to install Istio components with a custom IstioOperator overlay file.

**Comment by rootsongjc** [comment]
@sky92zwq It's indeed not necessary to execute `istioctl operator init`. This command is used to plan to use IstioOperator custom resources (CRs) to install and manage Istio as it deploys the required Istio Operator controllers. (Note: The IstioOperator installation method is no longer maintained, so it's not recommended to use this approach for installation).

Suppose you choose not to use Istio Operator and instead install Istio directly using the `istioctl install` command or manually applying YAML files. In that case, you don't need to run `istioctl operator init`. Just save the configuration to a file first:

```bash
cat<<EOF>istio-install.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-with-skywalking
spec:
  meshConfig:
    defaultProviders:
      tracing:
      - "skywalking"
    enableTracing: true
    extensionProviders:
    - name: "skywalking"
      skywalking:
        service: tracing.istio-system.svc.cluster.local
        port: 11800
EOF
```

Then, you can install Istio with the following command:

```bash
istioctl apply -f istio-install.yaml
```

**Reply by sky92zwq** [reply]
@rootsongjc  It's great to receive so detailed responses.
But I still not success.
Here are my installation steps,  can you give me some advices:

1. create a k8s cluster
`kind create cluster --config=cluster-config1.yml --name=istiosky`
2. cluster consists of a control-plane and two worker nodes
    ```
     cat cluster-config1.yml
    # cluster-config.yml
    kind: Cluster
    apiVersion: kind.x-k8s.io/v1alpha4
    nodes:
    - role: control-plane
    - role: worker
    - role: worker
    ```
3. install istio 
`istioctl install --set profile=demo -y`
4. configure skywalking  
 istioctl apply -f istio-install.yaml would  print error:   
>     Error: generate config: failed to parse YAML to a k8s object: error converting YAML to JSON: yaml: line 2: mapping values are not allowed in this context 
  so I changed the command as below:  
```  
  kubectl apply -f - <<EOF
  apiVersion: install.istio.io/v1alpha1
  kind: IstioOperator
  metadata:
    namespace: istio-system
    name: istio-with-skywalking
  spec:
    meshConfig:
      defaultProviders:
        tracing:
        - "skywalking"
      enableTracing: true
      extensionProviders:
      - name: "skywalking"
        skywalking:
          service: tracing.istio-system.svc.cluster.local
          port: 11800
  EOF
```
5. install skywalking, the yaml file is located in istio-1.20.0 package
`kubectl apply -f samples/addons/extras/skywalking.yaml`
6. create a namespace for installing applications
`kubectl create ns istioinaction`
7. switch namespace
`kubectl config set-context $(kubectl config current-context) --namespace=istioinaction`
8. add label for envoy injection
`kubectl label namespace istioinaction istio-injection=enabled`
9. install sample applications 
    ```  
   kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml
   kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml
    ```
10. finally, start dashboard
`istioctl  dashboard skywalking`

Then, I still got no data.

**Reply by zirain** [reply]
by default, sample rate is 1%, you can verify it by running istioctl pc l <pod_name> -oyaml

**Reply by sky92zwq** [reply]
@zirain , the result is huge. Should I verify which keyword? And I attached the result.
[productpage_pod.log](https://github.com/istio/istio/files/13669839/productpage_pod.log)

**Reply by hanxiaop** [reply]
I assume you have not installed Istio correctly. In step 4, you have applied a IstioOperator file without any controller processing it. I think you can just combine step 3 and 4 into one step:
```
istioctl install -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-with-skywalking
spec:
  meshConfig:
    defaultProviders:
      tracing:
      - "skywalking"
    enableTracing: true
    extensionProviders:
    - name: "skywalking"
      skywalking:
        service: tracing.istio-system.svc.cluster.local
        port: 11800
EOF
```
