### DISCUSSION TITLE
[Kubernetes DNS] Non istio namespace to istio namespace

### DISCUSSION THREAD

**Discussion by agreedSkiing** [istio/istio#48322] [Q&A] [answered]
Do i need to set up a ServiceEntry or something else to make this communication possible? Currently our pod responeds with a 
```
curl -v http://keycloak-http.keycloak-staging.svc.cluster.local:8080/auth
*   Trying <cluserIP>...
* TCP_NODELAY set
* connect to <cluserIP> port 8080 failed: Connection timed out
* Failed to connect to keycloak-http.keycloak-staging.svc.cluster.local port 8080: Connection timed out
* Closing connection 0
```
The same curl command works in another namespace that has istio applied to it.

P.S. Using istio 1.16.7

**Comment by zirain** [comment]
what's your OutboundTrafficPolicy? if it's allow any, this's more like a network issue.

**Reply by agreedSkiing** [reply]
Just found it :)
```
outboundTrafficPolicy:
  mode: REGISTRY_ONLY
```
is it possible to change it to cluster?

**Reply by zirain** [reply]
Sorry, I made a mistake, it's a cluster.local service, should not related to `outboundTrafficPolicy`.

Did you enable STRICT mTLS?

**Reply by agreedSkiing** [reply]
No it is set to PERMISSIVE by default and the namespace I'm trying to reach has no override

**Reply by zirain** [reply]
If so, I don't think it's due to istio.
Maybe you should the network across nodes, if there's not on same node.

**Reply by agreedSkiing** [reply]
Well they are running on the same node 😆, currently

**Comment by agreedSkiing** [comment, marked as answer]
We found a solution to our problem and that was by adding a NetworkPolicy
```yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: test
  namespace: keycloak-staging
spec:
  podSelector: {}
  ingress:
    - from:
        - podSelector: {}
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: non-istio-namespace-name
  policyTypes:
    - Ingress
```

We also found out that all our communication from our namespaces in istio returned a 503 when trying to curl a non istio namespace
