### DISCUSSION TITLE
How to set multiple domain for `Access-Control-Allow-Origin` response header?

### DISCUSSION THREAD

**Discussion by veerendra2** [istio/istio#48381] [Q&A]
We have a virtual service with 2 hosts like 
```
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vault
  namespace: vault
  labels:
    app: vault
spec:
  hosts:
    - vault-de1.example.com
    - vault.example.com
  gateways:
    - istio-system/istio-default-gateway
  http:
    - match:
        - uri:
            exact: /metrics
      redirect:
        uri: /
    - route:
        - destination:
            host: vault.vault.svc.cluster.local
            port:
              number: 8200
      headers:
        response:
          set:
            Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
            X-Content-Type-Options: nosniff
            X-Frame-Options: DENY
            Referrer-Policy: no-referrer
            Access-Control-Allow-Origin: vault.example.com # <---------
```
How to add 2 domain for `Access-Control-Allow-Origin` response header?

I found [stackoverflow question](https://stackoverflow.com/questions/1653308/access-control-allow-origin-multiple-origin-domains), response header is set based on request coming in. Is there something we can do in istio? or any regex trick can do here?

**Comment by howardjohn** [comment]
I think you just want `Access-Control-Allow-Origin: vault.example.com,vault2.example.com`

**Comment by rootsongjc** [comment]
You can try this EnvoyFilter:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: dynamic-ac-allow-origin
  namespace: vault
spec:
  workloadSelector:
    labels:
      app: vault
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_OUTBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.lua
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
            inlineCode: |
              function envoy_on_response(response_handle)
                local allowed_domains = {
                  ["vault-de1.example.com"] = true,
                  ["vault.example.com"] = true
                }
                local origin_header = response_handle:headers():get("origin")
                if allowed_domains[origin_header] then
                  response_handle:headers():replace("Access-Control-Allow-Origin", origin_header)
                end
              end
```

- This EnvoyFilter is applied to the vault app's sidecar proxy.
- The Lua script checks if the Origin header of the incoming request matches one of the specified domains in the allowed_domains table.
- If there's a match, the script sets the Access-Control-Allow-Origin header to the value of the request's Origin header.
