### DISCUSSION TITLE
need help with VirtualService Request Routing by value of header with regex

### DISCUSSION THREAD

**Discussion by DSNYCYANG** [istio/istio#48405] [Q&A] [answered]
I try to route to different service version base on browser. It's working when I use prefix or exact match, but I can't make it work with regex. can anyone help me check if my regex format is wrong? I tested regex format on "https://regex101.com/r/BgMkwf/2" and it match.

the following route by **regex match doesn't work**:

```yaml
  - match:
    - headers:
        Sec-Ch-Ua:
          regex: Google
      uri:
        prefix: /busybox/
    rewrite:
      uri: /
    route:
    - destination:
        host: busybox
        port:
          number: 80
        subset: v1
  - match:
    - headers:
        Sec-Ch-Ua:
          regex: Microsoft
      uri:
        prefix: /busybox/
    rewrite:
      uri: /
    route:
    - destination:
        host: busybox
        port:
          number: 80
        subset: v2

```

the following route by **prefix match working**:

```yaml
  - match:
    - headers:
        Sec-Ch-Ua:
          prefix: '"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";'
      uri:
        prefix: /busybox/
    rewrite:
      uri: /
    route:
    - destination:
        host: busybox
        port:
          number: 80
        subset: v1
  - match:
    - headers:
        Sec-Ch-Ua:
          prefix: '"Not_A Brand";v="8", "Chromium";v="120", "Microsoft Edge";'
      uri:
        prefix: /busybox/
    rewrite:
      uri: /
    route:
    - destination:
        host: busybox
        port:
          number: 80
        subset: v2
```

the following route by **exact match working** too:
```yaml
  - match:
    - headers:
        Sec-Ch-Ua:
          exact: '"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"'
      uri:
        prefix: /busybox/
    rewrite:
      uri: /
    route:
    - destination:
        host: busybox
        port:
          number: 80
        subset: v1
  - match:
    - headers:
        Sec-Ch-Ua:
          exact: '"Not_A Brand";v="8", "Chromium";v="120", "Microsoft Edge";v="120"'
      uri:
        prefix: /busybox/
    rewrite:
      uri: /
    route:
    - destination:
        host: busybox
        port:
          number: 80
        subset: v2
```

**Comment by hanxiaop** [comment]
Maybe you can try something like `.*google.*`?

**Reply by DSNYCYANG** [reply]
Hi Xiaopeng, Thank you for looking into this. But I tried the following still doesn't work. It doesn't route to v1 subset. any other suggestion? 

 - match:
    - headers:
        Sec-Ch-Ua:
          regex: .\*google.\*
      uri:
        prefix: /busybox/
    rewrite:
      uri: /
    route:
    - destination:
        host: busybox
        port:
          number: 80
        subset: v1

**Reply by DSNYCYANG** [reply]
Hi Xiaopeng, Actually it working! The reason of that is the first letter must be capital letter G, so the following working. Thank you so much for your help!

` 
- match:
    - headers:
        Sec-Ch-Ua:
          regex: .\*Google.\*
      uri:
        prefix: /busybox/
    rewrite:
      uri: /
    route:
    - destination:
        host: busybox
        port:
          number: 80
        subset: v1
`

**Comment by rootsongjc** [comment, marked as answer]
When using regular expressions (regex) for routing in Istio's `VirtualService` configuration, ensure the regex is in the format used by Envoy because Istio uses Envoy proxy at its core for routing. Envoy uses regular expressions in RE2 style, which differs from Perl-compatible regular expressions (PCRE) used by some regex testing websites like regex101.

### Check the Regular Expression

Could you make sure that your regular expression is in the RE2 format supported by Envoy? For example, if you want to match the `Sec-Ch-Ua` header that contains either "Google" or "Microsoft," you can use the following regular expressions:

- For a string containing "Google": `.*Google.*`
- For a string containing "Microsoft": `.*Microsoft.*`

These expressions will match any header value containing these strings.

### Update the `VirtualService` Configuration

Based on the above recommendations, your `VirtualService` configuration should be modified as follows:

```yaml
- match:
  - headers:
      Sec-Ch-Ua:
        regex: ".*Google.*"
    uri:
      prefix: /busybox/
  rewrite:
    uri: /
  route:
  - destination:
      host: busybox
      port:
        number: 80
      subset: v1
- match:
  - headers:
      Sec-Ch-Ua:
        regex: ".*Microsoft.*"
    uri:
      prefix: /busybox/
  rewrite:
    uri: /
  route:
  - destination:
      host: busybox
      port:
        number: 80
      subset: v2
```

Ensure your `regex` fields in the `match` section of the `VirtualService` use the Envoy-compatible RE2 regular expression format for accurate routing.
