### DISCUSSION TITLE
Istio Protocol Selection if name of the port and appProtocol both are defined

### DISCUSSION THREAD

**Discussion by husnialhamdani** [istio/istio#48459] [Q&A] [answered]
Referencing to this doc: 
https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#explicit-protocol-selection

How Istio will evaluate below Service if port name and appProtocol both are defined?
```
kind: Service
metadata:
  name: myservice
spec:
  ports:
  - port: 3306
    name: tcp
    appProtocol: https
``` 
A name with TCP but the appProtocol with HTTPS, will be treated as TCP/HTTP workload?
