### DISCUSSION TITLE
Troubleshooting Istio with ALB SSL Termination

### DISCUSSION THREAD

**Discussion by adam-aph2** [istio/istio#48626] [Q&A] [answered]
Hi All. This is another case which is somehow problematic to me. As explained in https://github.com/istio/istio/discussions/48608, I'm doing all my tests in AWS with EKS 1.27 and Istio 1.15.2 (cannot really upgrade to higher versions because of other dependencies).

For ALB I wanted to build that scenario:
<img src="https://github.com/istio/istio/assets/97974298/d0481435-8415-4b97-a686-5fd657d40b3a" width="500">

I started additional `istio-ingressgateway-alb` instance with `service.type=NodePort` for this test, listening to 15021, 80, 443, 8080 and 8443. Then ALB has been instantiated that way:
```
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: common-external-alb-class
  namespace: istio-system
spec:
  controller: ingress.k8s.aws/alb
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: common-external-alb-ingress
  namespace: istio-system
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/load-balancer-name: common-external-alb-ingress
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:xyz
    alb.ingress.kubernetes.io/subnets: subnet-x, subnet-y, subnet-z  
#    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:us-east-2:xyz
    alb.ingress.kubernetes.io/actions.ssl-redirect: '443'
  labels:
    app: common-external-alb-ingress
spec:
  ingressClassName: common-external-alb-class
  defaultBackend:
    service:
      name: istio-ingressgateway-alb
      port:
        number: 443
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: istio-ingressgateway-alb
                port:
                  number: 8443
```
This is the setup for Istio and the App:
```
---
apiVersion: v1
kind: Service
metadata:
  name: game-alb-api-srv
  namespace: game-alb
  labels:
    app.kubernetes.io/name: game-alb-api
    app.kubernetes.io/instance: game-alb-api
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    app: game-alb-api
  type: ClusterIP
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: game-alb-api-gateway
  namespace: game-alb
spec:
  selector:
    istio: ingressgateway-alb
  servers:
  - port:
      number: 8443
      name: https
      protocol: HTTPS
    hosts:
      - game.xyz.com
    tls:
      mode: SIMPLE
      credentialName: "game-alb-tls-secret"   # make sure it is created in istio-system namespace
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: game-alb-api-vsrv
  namespace: game-alb
spec:
  exportTo:
    - "*"
  hosts:
  - game.xyz.com
  gateways:
  - game-alb-api-gateway
  http:
    - match:
        - port: 8443
        - uri:
            prefix: /game
      route:
        - destination:
            subset: game-alb-api-srv
            port:
              number: 8080
            host: game-alb-api-srv
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: game-nginx-dr
  namespace: game-alb
spec:
  exportTo:
    - "*"
  host: game-alb-api-srv
  subsets:
    - name: game-alb-api-srv
      labels:
        app: game-alb-api
```
The self-signed certificate was added with this:
```
kubectl create -n istio-system secret generic game-alb-tls-secret --from-file=key=certs/key.pem --from-file=cert=certs/cert.pem
```
Istio is not complaining:
```
kubectl istio analyze -n game-alb
✔ No validation issues found when analyzing namespace: game-alb.
```
But the test is failing:
```
curl -v -H "Host: game.xyz.com" -H "Content-Type: application/json"  https://game.xyz.com/game
*   Trying a.b.c.d:443...
* Connected to game.xyz.com (a.b.c.d) port 443 (#0)
* schannel: disabled automatic use of client certificate
* ALPN: offers http/1.1
* ALPN: server accepted http/1.1
* using HTTP/1.1
> GET /game HTTP/1.1
> Host: game.xyz.com
> User-Agent: curl/8.0.1
> Accept: */*
> Content-Type: application/json
>
< HTTP/1.1 502 Bad Gateway
< Server: awselb/2.0
< Date: Wed, 03 Jan 2024 09:52:58 GMT
< Content-Type: text/html
< Content-Length: 122
< Connection: keep-alive
<
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>
* Connection #0 to host game.xyz.com left intact
```
I enabled debug logs at the `istio-ingressgateway-alb` Pod and can see this:
```
2024-01-03T10:08:04.478418Z     debug   envoy filter    tls inspector: new connection accepted
2024-01-03T10:08:04.478521Z     debug   envoy conn_handler      closing connection from 10.100.14.232:62885: no matching filter chain found
[2024-01-03T10:08:04.478Z] Host:- Method:- OrPath:- Proto:- RespC:0 RespFl:NR BytesRcv:0 BytesSent:0 Dur:0 RespTime:- ReqForw:- ReqUser:- ReqId:- ReqAuth:- UpstHost:- RoutName:- UpsClust:- UpsLocAddr:- DownLocAddr:10.100.80.72:8443 DownRemAddr:10.100.14.232:62885 ReqServName:- IstioPolicyStatus:- UpsTranFailReason:-

10.100.14.232 = primary IP on worker node
10.100.80.72 = istio-ingressgateway-alb Pod
```
'Host' in access log is Host:%REQ(HOST)%, does it mean that ALB is not forwarding Host to envoy proxy and this is the reason for missing routing?

Here is also list of listeners on `istio-ingressgateway-alb` :
```
ADDRESS PORT  MATCH                        DESTINATION
0.0.0.0 8443  SNI: game.xyz.com Route: https.8443.https.game-alb-api-gateway.game-alb
0.0.0.0 15021 ALL                          Inline Route: /healthz/ready*
0.0.0.0 15090 ALL                          Inline Route: /stats/prometheus*
```
And list of clusters:
```
SERVICE FQDN                                                        PORT      SUBSET               DIRECTION     TYPE           DESTINATION RULE
BlackHoleCluster                                                    -         -                    -             STATIC
agent                                                               -         -                    -             STATIC
aws-load-balancer-webhook-service.kube-system.svc.cluster.local     443       -                    outbound      EDS
calico-api.calico-apiserver.svc.cluster.local                       443       -                    outbound      EDS
calico-kube-controllers-metrics.calico-system.svc.cluster.local     9094      -                    outbound      EDS
calico-typha.calico-system.svc.cluster.local                        5473      -                    outbound      EDS
cc-api.cc.svc.cluster.local                                         8080      -                    outbound      EDS
cert-manager-webhook.istio-system.svc.cluster.local                 443       -                    outbound      EDS
cert-manager.istio-system.svc.cluster.local                         9402      -                    outbound      EDS
clients-api.clients.svc.cluster.local                               8080      -                    outbound      EDS
dikastes.calico.cluster.local                                       1         -                    outbound      EDS            dikastes-mtls.istio-system
game-alb-api-srv.game-alb.svc.cluster.local                         8080      -                    outbound      EDS            game-nginx-dr.game-alb
game-alb-api-srv.game-alb.svc.cluster.local                         8080      game-alb-api-srv     outbound      EDS            game-nginx-dr.game-alb
game-nginx-api-srv.game-nginx.svc.cluster.local                     8080      -                    outbound      EDS
istio-egressgateway.istio-system.svc.cluster.local                  80        -                    outbound      EDS
istio-egressgateway.istio-system.svc.cluster.local                  443       -                    outbound      EDS
istio-egressgateway.istio-system.svc.cluster.local                  8080      -                    outbound      EDS
istio-egressgateway.istio-system.svc.cluster.local                  8180      -                    outbound      EDS
istio-egressgateway.istio-system.svc.cluster.local                  15021     -                    outbound      EDS
istio-ingressgateway-alb.istio-system.svc.cluster.local             80        -                    outbound      EDS
istio-ingressgateway-alb.istio-system.svc.cluster.local             443       -                    outbound      EDS
istio-ingressgateway-alb.istio-system.svc.cluster.local             8080      -                    outbound      EDS
istio-ingressgateway-alb.istio-system.svc.cluster.local             8443      -                    outbound      EDS
istio-ingressgateway-alb.istio-system.svc.cluster.local             15021     -                    outbound      EDS
istio-ingressgateway.istio-system.svc.cluster.local                 80        -                    outbound      EDS
istio-ingressgateway.istio-system.svc.cluster.local                 443       -                    outbound      EDS
istio-ingressgateway.istio-system.svc.cluster.local                 8080      -                    outbound      EDS
istio-ingressgateway.istio-system.svc.cluster.local                 8180      -                    outbound      EDS
istio-ingressgateway.istio-system.svc.cluster.local                 8443      -                    outbound      EDS
istio-ingressgateway.istio-system.svc.cluster.local                 15021     -                    outbound      EDS
istiod.istio-system.svc.cluster.local                               443       -                    outbound      EDS
istiod.istio-system.svc.cluster.local                               15010     -                    outbound      EDS
istiod.istio-system.svc.cluster.local                               15012     -                    outbound      EDS
istiod.istio-system.svc.cluster.local                               15014     -                    outbound      EDS
jaeger-agent.istio-system.svc.cluster.local                         5778      -                    outbound      EDS
jaeger-agent.istio-system.svc.cluster.local                         14271     -                    outbound      EDS
jaeger-collector-headless.istio-system.svc.cluster.local            4317      -                    outbound      EDS
jaeger-collector-headless.istio-system.svc.cluster.local            4318      -                    outbound      EDS
jaeger-collector-headless.istio-system.svc.cluster.local            9411      -                    outbound      EDS
jaeger-collector-headless.istio-system.svc.cluster.local            14250     -                    outbound      EDS
jaeger-collector-headless.istio-system.svc.cluster.local            14267     -                    outbound      EDS
jaeger-collector-headless.istio-system.svc.cluster.local            14268     -                    outbound      EDS
jaeger-collector-headless.istio-system.svc.cluster.local            14269     -                    outbound      EDS
jaeger-collector.istio-system.svc.cluster.local                     4317      -                    outbound      EDS
jaeger-collector.istio-system.svc.cluster.local                     4318      -                    outbound      EDS
jaeger-collector.istio-system.svc.cluster.local                     9411      -                    outbound      EDS
jaeger-collector.istio-system.svc.cluster.local                     14250     -                    outbound      EDS
jaeger-collector.istio-system.svc.cluster.local                     14267     -                    outbound      EDS
jaeger-collector.istio-system.svc.cluster.local                     14268     -                    outbound      EDS
jaeger-collector.istio-system.svc.cluster.local                     14269     -                    outbound      EDS
jaeger-operator-metrics.istio-system.svc.cluster.local              8383      -                    outbound      EDS
jaeger-operator-webhook-service.istio-system.svc.cluster.local      443       -                    outbound      EDS
jaeger-query.istio-system.svc.cluster.local                         16685     -                    outbound      EDS
jaeger-query.istio-system.svc.cluster.local                         16686     -                    outbound      EDS
jaeger-query.istio-system.svc.cluster.local                         16687     -                    outbound      EDS
kiali.istio-system.svc.cluster.local                                9090      -                    outbound      EDS
kiali.istio-system.svc.cluster.local                                20001     -                    outbound      EDS
kube-dns.kube-system.svc.cluster.local                              53        -                    outbound      EDS
kube-dns.kube-system.svc.cluster.local                              9153      -                    outbound      EDS
kubernetes.default.svc.cluster.local                                443       -                    outbound      EDS
nginx-ingress-ext-controller.nginx-system.svc.cluster.local         80        -                    outbound      EDS
nginx-ingress-ext-controller.nginx-system.svc.cluster.local         443       -                    outbound      EDS
orders-api.orders.svc.cluster.local                                 8080      -                    outbound      EDS
payment-api.payment.svc.cluster.local                               8080      -                    outbound      EDS
prometheus.istio-system.svc.cluster.local                           9090      -                    outbound      EDS
prometheus_stats                                                    -         -                    -             STATIC
sds-grpc                                                            -         -                    -             STATIC
xds-grpc                                                            -         -                    -             STATIC
zipkin                                                              -         -                    -             STRICT_DNS
```
Is there anything else should I check? Any obvious errors in my configuration? Any pointers are appreciated.

**Comment by adam-aph2** [comment]
I did one more attempt - fresh cluster with EKS 1.28 and Istio 1.20.1, this time nothing else in the system (in previous tests I had also integrated Calico with it). Still the same error.

**Comment by adam-aph2** [comment]
Here is the ingress status:
```
istio-ingressgateway-alb-cc6b4f8c-st2zf.istio-system           Kubernetes     SYNCED     SYNCED     SYNCED     SYNCED     NOT SENT     istiod-6c7b79d8cc-dhw8d     1.20.1
```
The test App Pod:
```
game-alb          game-alb-api-8656d7cdb8-dhd4w                   2/2     Running   0             23h   10.100.65.50    ip-10-100-75-16.internal    <none>           <none>
```
Endpoints at the istio-ingressgateway-alb related to the test App Pod:
```
10.100.65.50:80                                         HEALTHY     OK                outbound|8080|game-alb-api-srv|game-alb-api-srv.game-alb.svc.cluster.local
10.100.65.50:80                                         HEALTHY     OK                outbound|8080||game-alb-api-srv.game-alb.svc.cluster.local
```
And routings at istio-ingressgateway-alb:
```
    {
        "name": "https.8443.https.game-alb-api-gateway.game-alb",
        "virtualHosts": [
            {
                "name": "game.xyz.com:8443",
                "domains": [
                    "game.xyz.com"
                ],
                "routes": [
                    {
                        "match": {
                            "prefix": "/",
                            "caseSensitive": true
                        },
                        "route": {
                            "cluster": "outbound|8080|game-alb-api-srv|game-alb-api-srv.game-alb.svc.cluster.local",
                            "timeout": "0s",
                            "retryPolicy": {
                                "retryOn": "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes",
                                "numRetries": 2,
                                "retryHostPredicate": [
                                    {
                                        "name": "envoy.retry_host_predicates.previous_hosts",
                                        "typedConfig": {
                                            "@type": "type.googleapis.com/envoy.extensions.retry.host.previous_hosts.v3.PreviousHostsPredicate"
                                        }
                                    }
                                ],
                                "hostSelectionRetryMaxAttempts": "5",
                                "retriableStatusCodes": [
                                    503
                                ]
                            },
                            "maxGrpcTimeout": "0s"
                        },
                        "metadata": {
                            "filterMetadata": {
                                "istio": {
                                    "config": "/apis/networking.istio.io/v1alpha3/namespaces/game-alb/virtual-service/game-alb-api-vsrv"
                                }
                            }
                        },
                        "decorator": {
                            "operation": "game-alb-api-srv.game-alb.svc.cluster.local:8080/*"
                        }
                    }
                ],
                "includeRequestAttemptCount": true
            }
        ],
        "validateClusters": false,
        "maxDirectResponseBodySizeBytes": 1048576,
        "ignorePortInHostMatching": true
    },
```

**Comment by adam-aph2** [comment, marked as answer]
So finally I figured it out with some help of AWS support and community notes. It malfunctioned because of combination of two issues:

- ALB is not passing SNI to downstream services - see [here](https://istio.io/latest/docs/ops/common-problems/network-issues/#configuring-sni-routing-when-not-sending-sni) for suggested solutions.
- My initial ALB Ingress setup didn't consider that Istio Ingress Gateway accepts only TLS, so ALB target groups should use HTTPS.

For the reference here is corrected setup for ALB Ingress and Istio resources:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: common-external-alb-ingress
  namespace: istio-system
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/load-balancer-name: common-external-alb-ingress
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:xyz
    alb.ingress.kubernetes.io/subnets: subnet-x, subnet-y, subnet-z  # public cluster subnets
    alb.ingress.kubernetes.io/backend-protocol: HTTPS  # to make sure it can use TLS to backend, as we re-encrypt
    alb.ingress.kubernetes.io/healthcheck-path: /healthz/ready
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
#    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:xyz
    alb.ingress.kubernetes.io/actions.ssl-redirect: '443'
  labels:
    app: common-external-alb-ingress
spec:
  defaultBackend:
    service:
      name: istio-ingressgateway-alb
      port:
        number: 8443   
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: istio-ingressgateway-alb   
                port:
                  number: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: game-alb2-api-srv
  namespace: game-alb
  labels:
    app.kubernetes.io/name: game-alb2-api
    app.kubernetes.io/instance: game-alb2-api
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
  selector:
    app: game-alb2-api
  type: ClusterIP
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: game-alb2-api-gateway
  namespace: game-alb
spec:
  selector:
    istio: ingressgateway-alb
  servers:
  - hosts:
     # https://istio.io/latest/docs/ops/common-problems/network-issues/#configuring-sni-routing-when-not-sending-sni
#     - game.xyz.com
    - "*"
    port:
      name: https
      number: 8443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: "game-alb-tls-secret"   # make sure it is created in istio-system namespace
  - hosts:
      - game.xyz.com
    port:
      name: http
      number: 80
      protocol: HTTP
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: game-alb2-api-vsrv
  namespace: game-alb
spec:
  exportTo:
    - "*"
  hosts:
    - game.xyz.com
  gateways:
  - game-alb2-api-gateway
  http:
    - match:
        - port: 80
        - uri:
            prefix: /alb
      route:
        - destination:
            port:
              number: 80
            host: game-alb2-api-srv
```
