### DISCUSSION TITLE
How to preserve X-Forwarded-Client-Cert header between pods

### DISCUSSION THREAD

**Discussion by SmithJosh** [istio/istio#48635] [Q&A]
I have a reverse proxy running behind an Istio Gateway. The gateway is configured for mTLS and forwards the client cert in the X-Forwarded-Client-Cert header. I want the proxy to forward this XFCC header to upstream services, but Istio replaces it with it's own. Something like `By=spiffe://platform.cluster.local/ns/default/sa/default;Hash=0da5c3f919141378825d04730c5ac876370ace2ca9bd8bf6fd8e3b48a85eb785;Subject="";URI=spiffe://platform.cluster.local/ns/ingress/sa/istio-ingressgateway-service-account`. Istio is configured with mTLS between all workloads, which I think is the problem.

I tried changing the `forwardClientCertDetails` configuration at the pod-level to change how the XFCC header gets forwarded, but that made no difference. I then found this related issue describing a very similar use case https://github.com/istio/istio/issues/48506. The response was that is expected, the config only applies to the gateway.

Is there any way to prevent Istio from overwriting the XFCC header when making requests between pods?

**Comment by husnialhamdani** [comment]
Hi @SmithJosh, 
Have you check this one https://istio.io/latest/docs/ops/configuration/traffic-management/network-topologies/?
That might help.

**Reply by SmithJosh** [reply]
I did read through that and that's what gave me the idea to try changing the `forwardClientCertDetails`. The problem is that it only applies to the gateway. It doesn't control how the XFCC header is forwarded between my own proxy and my upstream application. Here's a diagram to help visualize

![IstioXfccOverwritten](https://github.com/istio/istio/assets/3878142/ea1fba7a-7bf2-436b-a65a-12f3bb5f635f)

`forwardClientCertDetails` will affect the Istio <-> Proxy traffic, not the Proxy <-> App traffic. I need to figure out how to preserve the XFCC header for that request as well.

**Reply by rootsongjc** [reply]
Is your Reverse Proxy deployed standalone? Not inside an Istio Mesh?

**Reply by SmithJosh** [reply]
No it's part of the Istio Mesh as well

**Comment by SmithJosh** [comment]
In the end I did not find a way to preserve the header between pods in the mesh when strict mtls is configured. I was able to modify the proxy to send the client cert in a separate header though and then add an Envoy filter to the app pod to translate that custom header back into the `X-Forwarded-Client-Cert` header.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: handle-custom-xfcc-header
spec:
  workloadSelector:
    labels:
      app: myapp
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_FIRST
        value:
          name: envoy.lua
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
            inlineCode: |
              function envoy_on_request(request_handle)
                local header = request_handle:headers():get("Custom-X-Forwarded-Client-Cert")
                if header then
                  request_handle:logWarn("Copying Custom-X-Forwarded-Client-Cert header to X-Forwarded-Client-Cert: " .. header)
                  request_handle:headers():add("X-Forwarded-Client-Cert", header)
                  request_handle:headers():remove("Custom-X-Forwarded-Client-Cert")
                end
              end
```

**Comment by bltavares** [comment]
I was able to achieve something similar to the Lua script by configuring the OUTBOUND listener of the sidecar to use `ALWAYS_FORWARD_ONLY`, as the default bevaviour of `HttpConnectionManager` is to `SANITIZE` if not configured.

So the HTTP header leaves the `Service -> Outbound Listener -> Network -> Inbound Listener -> Service` properly. 


```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: forward-outbound-client-cert
  namespace: istio-system
spec:
  configPatches:
    - applyTo: NETWORK_FILTER
      match:      
        context: SIDECAR_OUTBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
            forward_client_cert_details: "ALWAYS_FORWARD_ONLY"
```
