### DISCUSSION TITLE
Proxy Protocol over MTLS is not working as expected

### DISCUSSION THREAD

**Discussion by skiran-a** [istio/istio#48642] [Q&A]
Hi There,

Here is the data flow (TLS Traffic) in my use case. And using istio version 1.16.7

Public LB <----> Istio IGW <-----> Service Pod. ANd Strict MTLS is enabled.

Configured passthrough in the Ingress Gateway. And also enabled proxy protocol in down and upstream like below.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: proxy-protocol
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: LISTENER
    match:
       listener:
          name: "0.0.0.0_5696"
    patch:
      operation: MERGE
      value:
        listener_filters:
        - name: envoy.listener.proxy_protocol
        - name: envoy.listener.tls_inspector
```

and 

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: proxy-protocol-upstream
  namespace: istio-system
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      cluster:
        service: "kmip.default.svc.cluster.local"
    patch:
      operation: MERGE
      value:
        transport_socket:
          name: envoy.transport_sockets.upstream_proxy_protocol
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.proxy_protocol.v3.ProxyProtocolUpstreamTransport
            config:
              version: V2
            transport_socket:
              name: "envoy.transport_sockets.raw_buffer"
  workloadSelector:
    labels:
      istio: ingressgateway
```

And in the service pod also enabled proxy protocol for downstream

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: proxy-protocol-kmip-sc
  namespace: default
spec:
  workloadSelector:
    labels:
      app: kmip-app
  configPatches:
  - applyTo: LISTENER
    patch:
      operation: MERGE
      value:
        listener_filters:
        - name: envoy.listener.proxy_protocol
        - name: envoy.listener.tls_inspector
```

With this configuration the data flow is not working, it looks like the sidecar envoy proxy is not able to route the traffic due to ```requested_server_name``` is not matching. 

With upstream proxy protocol configuration the ```requested_server_name``` is changing to the host name used in curl request from the local service name.

Note: 

Without upstream proxy protocol configuration i see the following in the sidecar proxy log

```
{"requested_server_name":"outbound_.5696_._.kmip.default.svc.cluster.local",
"request_id":null,
"downstream_remote_address":"xxx.xxx.xxx.xxx:43018",
"upstream_host":"xxx.xxx.xxx.xxx:5696",
"response_flags":"-",
"start_time":"2024-01-04T03:10:35.222Z",
"user_agent":null,
"upstream_local_address":"127.0.0.6:52039",
"upstream_transport_failure_reason":null,
"path":null,"connection_termination_details":null,"duration":670,"upstream_service_time":null,"response_code":0,"response_code_details":null,"protocol":null,"bytes_received":2657,"x_forwarded_for":null,"authority":null,"downstream_local_address":"xxx.xxx.xxx.xxx:5696","upstream_cluster":"inbound|5696||","method":null,"route_name":null,"bytes_sent":6383}
```

With upstream proxy protocol configuration:

```
{**"requested_server_name":"kmip.xxx.xxx.xxx"**,
"x_forwarded_for":null,
"upstream_local_address":null,"bytes_sent":0,
"downstream_local_address":"xxx.xxx.xxx.xxx:5696",
"response_code_details":null,"bytes_received":0,"upstream_host":null,"user_agent":null,"upstream_service_time":null,"duration":349,"authority":null,"upstream_cluster":"inbound|5696||","response_flags":"-","connection_termination_details":null,"route_name":null,"path":null,"method":null,"upstream_transport_failure_reason":null,"protocol":null,"start_time":"2024-01-04T03:13:40.358Z","response_code":0,"request_id":null,"downstream_remote_address":"xxx.xxx.xxx.xxx:12595"}
```
