### DISCUSSION TITLE
Envoyfilter cannot add request headers correctly

### DISCUSSION THREAD

**Discussion by ZachariahHu** [istio/istio#48666] [Q&A]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hello, I would like to ask why my envoyfilter's OUTBOUND can add request headers to port 9234, but not to port 9235?

```shell
bash-5.0# curl 10.58.97.4:9234/example/headers
{"x-envoy-attempt-count":"1","x-request-id":"19413283-7e8c-9d7e-8dde-d6fe50b61bf7","x-b3-spanid":"fe9410420c80f363","x-b3-traceid":"4b724186c8f02db1fe9410420c80f363","x-forwarded-proto":"http","x-b3-sampled":"1","x-envoy-peer-metadata":"CiAKDkFQUF9DT05UQUlORVJTEg4aDGV4YW1wbGUtdGVzdAoaCgpDTFVTVEVSX0lEEgwaCkt1YmVybmV0ZXMKIAoMSU5TVEFOQ0VfSVBTEhAaDjEwMC4xMDEuMTcwLjc0ChkKDUlTVElPX1ZFUlNJT04SCBoGMS4yMC4wCq8BCgZMQUJFTFMSpAEqoQEKFQoDYXBwEg4aDGV4YW1wbGUtdGVzdAokChlzZWN1cml0eS5pc3Rpby5pby90bHNNb2RlEgcaBWlzdGlvCjEKH3NlcnZpY2UuaXN0aW8uaW8vY2Fub25pY2FsLW5hbWUSDhoMZXhhbXBsZS10ZXN0Ci8KI3NlcnZpY2UuaXN0aW8uaW8vY2Fub25pY2FsLXJldmlzaW9uEggaBmxhdGVzdAoaCgdNRVNIX0lEEg8aDWNsdXN0ZXIubG9jYWwKJwoETkFNRRIfGh1leGFtcGxlLXRlc3QtNjhkYmZiZmNiOS1rY2Z6NgoXCglOQU1FU1BBQ0USChoIaWJwLXRlc3QKUQoFT1dORVISSBpGa3ViZXJuZXRlczovL2FwaXMvYXBwcy92MS9uYW1lc3BhY2VzL2licC10ZXN0L2RlcGxveW1lbnRzL2V4YW1wbGUtdGVzdAofCg1XT1JLTE9BRF9OQU1FEg4aDGV4YW1wbGUtdGVzdA==","host":"10.58.97.4:9234","x-envoy-peer-metadata-id":"sidecar~100.101.170.74~example-test-68dbfbfcb9-kcfz6.ibp-test~ibp-test.svc.cluster.local","pod_name":"example-test-68dbfbfcb9-kcfz6","accept":"*/*","user-agent":"curl/7.79.1"}bash-5.0# ^C
bash-5.0# curl 10.58.97.4:9235/example/headers
{"host":"10.58.97.4:9235","accept":"*/*","user-agent":"curl/7.79.1"}bash-5.0# ^C
```

And envoyfilter.yaml configuration

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: my-envoy-filter
  namespace: ibp-test
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_OUTBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: add-pod-header
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
            inlineCode: |
              function envoy_on_request(request_handle)
                local pod_name = os.getenv("POD_NAME") or "unknown_pod"
                request_handle:headers():add("POD_NAME", pod_name)
              end
```
How can i solve this problem?

### Version

```Text
root@master01:/opt/temp# istioctl version
2024-01-05T07:37:42.496438Z     error   klog    an error occurred forwarding 38441 -> 15014: error forwarding port 15014 to pod 553db327eb4a1b594369ae1d4ea08d8d27f5695be8e131975176b1698b3b2a9a, uid : unable to do port forwarding: socat not found
2024-01-05T07:37:42.497032Z     error   port forward failed: lost connection to pod
2 errors occurred:
        * error port-forwarding into istio-system.istiod-b9f857555-xqtfc: failure running port forward process: Get "http://localhost:38441//version": EOF
        * failure running port forward process: Get "http://localhost:38441//version": EOF


2024-01-05T07:37:44.963648Z     error   klog    an error occurred forwarding 46389 -> 15014: error forwarding port 15014 to pod 553db327eb4a1b594369ae1d4ea08d8d27f5695be8e131975176b1698b3b2a9a, uid : unable to do port forwarding: socat not found
1.20.0
root@master01:/opt/temp# kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.4-1
Kustomize Version: v4.5.7
Server Version: v1.25.4-1
root@master01:/opt/temp#
```

**Comment by ZachariahHu** [comment]
My kubernetes service is nodePort type

service a
```yaml
 ports:
  - name: http-port
    nodePort: 30000
    port: 9234
    protocol: TCP
    targetPort: 9234
```
It seems to have something to do with this place?

I try to add the new service b.

service b
```yaml
 ports:
  - name: http-port
    nodePort: 30001
    port: 9235
    protocol: TCP
    targetPort: 9235
```

After adding, the request header can be added normally to port 9235. But I don’t understand why it is related to kubernetes service?

```shell
root@platform-test-85c5d9fbdd-v9xtx:/app# curl 10.58.97.4:9235/example/headers
{"x-envoy-attempt-count":"1","x-request-id":"9380c016-5385-9dfa-979b-f218f2d88ab9","x-b3-spanid":"ef202b50bed1ed31","x-b3-traceid":"fa1e928494db306cef202b50bed1ed31","x-forwarded-proto":"http","x-b3-sampled":"1","x-envoy-peer-metadata":"CiEKDkFQUF9DT05UQUlORVJTEg8aDXBsYXRmb3JtLXRlc3QKGgoKQ0xVU1RFUl9JRBIMGgpLdWJlcm5ldGVzCiAKDElOU1RBTkNFX0lQUxIQGg4xMDAuMTAxLjE3MC4xMAoZCg1JU1RJT19WRVJTSU9OEggaBjEuMjAuMAqxAQoGTEFCRUxTEqYBKqMBChYKA2FwcBIPGg1wbGF0Zm9ybS10ZXN0CiQKGXNlY3VyaXR5LmlzdGlvLmlvL3Rsc01vZGUSBxoFaXN0aW8KMgofc2VydmljZS5pc3Rpby5pby9jYW5vbmljYWwtbmFtZRIPGg1wbGF0Zm9ybS10ZXN0Ci8KI3NlcnZpY2UuaXN0aW8uaW8vY2Fub25pY2FsLXJldmlzaW9uEggaBmxhdGVzdAoaCgdNRVNIX0lEEg8aDWNsdXN0ZXIubG9jYWwKKAoETkFNRRIgGh5wbGF0Zm9ybS10ZXN0LTg1YzVkOWZiZGQtdjl4dHgKFwoJTkFNRVNQQUNFEgoaCGlicC10ZXN0ClIKBU9XTkVSEkkaR2t1YmVybmV0ZXM6Ly9hcGlzL2FwcHMvdjEvbmFtZXNwYWNlcy9pYnAtdGVzdC9kZXBsb3ltZW50cy9wbGF0Zm9ybS10ZXN0CiAKDVdPUktMT0FEX05BTUUSDxoNcGxhdGZvcm0tdGVzdA==","host":"10.58.97.4:9235","x-envoy-peer-metadata-id":"sidecar~100.101.170.10~platform-test-85c5d9fbdd-v9xtx.ibp-test~ibp-test.svc.cluster.local","pod_name":"platform-test-85c5d9fbdd-v9xtx","accept":"*/*","user-agent":"curl/7.88.1"}root@platform-test-85c5d9fbdd-v9xtx:/app# 
```
