### DISCUSSION TITLE
Is it possible to configure EnvoyFilter listener  to allow both proxy_protocol and non proxy_protocol at the same time?

### DISCUSSION THREAD

**Discussion by whitehatbuds** [istio/istio#48750] [Q&A]
I have a envoyfilter K8s configuration that looks like this. However, once this is applied, I have to ensure my load balancer has enabled proxy_protocol else all incoming request will fail.

Is there any way I can allow both proxy_protocol and non proxy_protocol requests to go through?
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: proxy-protocol
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: LISTENER
    patch:
      operation: MERGE
      value:
        listener_filters:
        - name: envoy.filters.listener.proxy_protocol
        - name: envoy.filters.listener.tls_inspector
```
