### DISCUSSION TITLE
Help, about configuring HTTPS certificates for Istio

### DISCUSSION THREAD

**Discussion by saowu** [istio/istio#48789] [Q&A]
[Configure a TLS ingress gateway for a single host](https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/)
I have referred to these contents and after completing the following two configurations, the HTTP protocol can work properly. Only the HTTPS protocol for one domain name is valid, and the HTTPS response for another domain name is 404. Is this a problem?

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kiali
  namespace: istio-system
spec:
  selector:
    app: istio-ingressgateway
  servers:
    - hosts:
        - wh-member1-kiali.jiajiayue.com
      port:
        name: http
        number: 80
        protocol: HTTP
    - hosts:
        - wh-member1-kiali.jiajiayue.com
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        credentialName: istio-ingressgateway-certs
        mode: SIMPLE
```
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: grafana
  namespace: istio-system
spec:
  selector:
    app: istio-ingressgateway
  servers:
    - hosts:
        - wh-member1-grafana.jiajiayue.com
      port:
        name: http
        number: 80
        protocol: HTTP
    - hosts:
        - wh-member1-grafana.jiajiayue.com
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        credentialName: istio-ingressgateway-certs
        mode: SIMPLE
```
We use istio-ingressgateway-certs here！

**Comment by husnialhamdani** [comment]
Can you please share the VirtualService for both domain?

**Reply by saowu** [reply]
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kiali
  namespace: istio-system
spec:
  gateways:
  - kiali
  - mesh
  hosts:
  - wh-member1-kiali.jiajiayue.com
  http:
  - route:
    - destination:
        host: kiali.istio-system.svc.cluster.local
        port:
          number: 20001
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
  name: grafana
  namespace: istio-system
spec:
  gateways:
  - grafana
  - mesh
  hosts:
  - wh-member1-grafana.jiajiayue.com
  http:
  - route:
    - destination:
        host: grafana.istio-system.svc.cluster.local
        port:
          number: 3000
```

**Comment by saowu** [comment]
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kiali
  namespace: istio-system
spec:
  gateways:
  - kiali
  - mesh
  hosts:
  - wh-member1-kiali.jiajiayue.com
  http:
  - route:
    - destination:
        host: kiali.istio-system.svc.cluster.local
        port:
          number: 20001
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
  name: grafana
  namespace: istio-system
spec:
  gateways:
  - grafana
  - mesh
  hosts:
  - wh-member1-grafana.jiajiayue.com
  http:
  - route:
    - destination:
        host: grafana.istio-system.svc.cluster.local
        port:
          number: 3000
```
