### DISCUSSION TITLE
Are TLSRoute and TCPRoute implemented and active?

### DISCUSSION THREAD

**Discussion by gernoteger** [istio/istio#48807] [Q&A] [answered]
Hi,
I wonder if TCPRoute and TLSRoute are properly implemented, and active by default. I used an HTTPRoute, a TLSRoute and a TCPRoute: The HTTPRoute got a status and was reachable, the TCPRoute and TLSRoutes weren't. A quick code review shows that they seem to be implemented, but somehow they don't seem to be recognised by the istiod controller.

What did I miss?

To reproduce:

1. I Added CRD's with `kubectl kustomize "github.com/kubernetes-sigs/gateway-api/config/crd/experimental?ref=v1.0.0" | kubectl apply -f -` 
2.  I created a kind cluster version 1.20.2 with `istioctl install -y --set profile=minimal`
3. I Installed the resoures:
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: echogateway
  namespace: echo

  annotations:
    networking.istio.io/service-type: ClusterIP

spec: 
  gatewayClassName: istio

  listeners: 
  - name: http-proxy
    port: 80
    protocol: HTTP
    allowedRoutes: 
      namespaces:
        from: "Same"

  - name: passthrough
    port: 443 
    protocol: TLS
    tls: 
      mode: Passthrough

    allowedRoutes: 
      namespaces:
        from: "Same"

  - name: http-tcp
    port: 8080 
    protocol: TCP

    allowedRoutes: 
      namespaces:
        from: "Same"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo-http
  namespace:  echo
spec:
  parentRefs:
  - name: echogateway
    namespace: echo
    sectionName: http-proxy

  hostnames:
  - echo-http.example.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs: 
    - name: echo 
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute

metadata:
  name: echo-istio-local
  namespace: echo
spec:
  parentRefs:
  - name: echogateway
    namespace:  echo
    sectionName: http-tcp

  hostnames:
  - echo1-tcproute.example.con
  rules:
  - backendRefs: 
    - name: echo 
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute

metadata:
  name: echo-tls-istio
  namespace: echo

spec:
  parentRefs:
  - name: echogateway
    namespace: echo
    sectionName: passthrough # was http-proxy when posting

  hostnames:
  - echo-tlsroute.example.com
  rules:
  - backendRefs: 
    - name: echo 
      port: 443
```
Did I miss something?
Thanks for any hints!

**Comment by howardjohn** [comment, marked as answer]
These are disabled by default and need to opt in
with PILOT_ENABLE_ALPHA_GATEWAY_API

**Reply by gernoteger** [reply]
Thanks a lot, this made it work:
```
istioctl install -y --set profile=minimal -f istioconfig.yaml
```
```
# file istioconfig.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    pilot:
      env:
        # see: https://istio.io/latest/docs/reference/commands/pilot-discovery/
        PILOT_ENABLE_ALPHA_GATEWAY_API: true # enable TLSRoute
```

The TLSRoute still has issues when connecting (even after fixing sectionName), but that's another story. The TCPRoute is working fine.

**Reply by lucagervasi** [reply]
Hi,
how do i activate that after I installed base, istiod and gateway using helm ?
I need it for TCPRoute.
Thanks.

**Reply by gernoteger** [reply]
tested with istio 1.22.3:
```
helm upgrade --install istiod istio/istiod -n istio-system --values istio-values.yaml --wait
```
and:
```
# file: istio-values.yaml 
pilot:
  env:
    PILOT_ENABLE_ALPHA_GATEWAY_API: true
```
this should work. Nevertheless, istio docs are quite sketchy here.
