### DISCUSSION TITLE
Istio Ingress Gateway External IP for a cluster running on Azure VM

### DISCUSSION THREAD

**Discussion by whizyrel** [istio/istio#48800] [Q&A]
Hello Istio Community,
I have just setup Kubernetes, pod network using flannel and Istio. I also installed Istio with the `default` profile. This was done in an Azure VM that was not attached to a LoadBalancer.

**_Kubernetes version:_** 
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0

**_Istio version:_**
client version: 1.20.1
control plane version: 1.20.1
data plane version: 1.20.1 (2 proxies)

Behavior
![Screenshot from 2024-01-14 15-57-56](https://github.com/istio/istio/assets/38155356/624c26b3-edbd-4e04-a90c-70cc521149b3)

I appreciate any help I can get. I would also appreciate questions to clarify.
Thank you for your help

**Comment by keithmattix** [comment]
Are you using https://capz.sigs.k8s.io/? If you're manually building Kubernetes, you'll need to install/configure the cloud controller manager yourself

**Comment by whizyrel** [comment]
Interesting, thank you for your reply.
I have just seen this for the first time.
What I did was to install k8s with the guide here [https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/).

I will look into the link you shared, what should be my outlook, install kubernetes as directed on that link?

**Reply by rootsongjc** [reply]
Could you tell me if you are trying to install Kubernetes using tools? Since you're already using a cloud platform, why not try using a Kubernetes service provided by a cloud vendor, such as Azure's AKS, or Google's GKE, which will save you the hassle of managing a Kubernetes cluster yourself?

**Reply by whizyrel** [reply]
I am not sure how you mean tools but I installed kubeadm, kubelet, kubectl via apt according to the docs.

Well, it is the requirement of the business: setup a kubernetes cluster on an azure VM that we provide. This is beyond me.

**Comment by whizyrel** [comment]
Hello,
I am not be able to go the CAPZ route because I can not be provided with the credentials I see so.
On that note, I googled a little bit more and I installed istio with the  externalIPs modified thus:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  hub: docker.io/istio
  tag: 1.20.2

  # You may override parts of meshconfig by uncommenting the following lines.
  ...

  # Traffic management feature
  components:
    ...
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        service:
          externalIPs: ["xxx.xxx.xxx.xxx"]
     ...
```

I modified and applied the httpbin sample, the ingress controller did get the ip specified and I could curl using the domain I specified from inside the server and I get the httpbin page printed to standard output but from my browser on my laptop, I see the connection refused page.
It can not be the firewall settings on Azure dashboard (I can not have access to it) because I already tried the nginx ingress controller and it works just fine.

Help is very much appreciated!
