### DISCUSSION TITLE
Unbalanced load when using consistentHash in a DistinationRule

### DISCUSSION THREAD

**Discussion by cybrhwk** [istio/istio#48802] [Q&A]
We have an application which is stateful and requires session affinity / sticky sessions to be applied.

We have a DestinationRule setup within our service mesh that has a `trafficPolicy` of:

```yaml
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: "myTenant_INGRESSCOOKIE"
          ttl: "172800s"
          path: "/my-app/"
```

When running a load test with this in place we are seeing quite a noticeable imbalance of the load between pods that use this rule

Does anyone know:

1) How new sessions are allocated to a pod when using consistentHash, is it round-robin for example?
2) Can it be configured to use a different allocation algorithm?
3) Is the imbalance an inherent trait of using consistentHash?
4) Is there another way to implement session affinity / sticky sessions that would allow us to use a different load balancing algorithm?

I appreciate any help you can provide

Thanks
