### DISCUSSION TITLE
Wheter needs to configure DNS on public network  for Remotely Accessing Telemetry Addons

### DISCUSSION THREAD

**Discussion by REMREMLX** [istio/istio#48813] [Q&A]
Hi team, one question over here.

I followed [this tutorial](https://istio.io/latest/docs/tasks/observability/gateways/) try to expose my prometheus service to service outside of cluster on public network.  

![image](https://github.com/istio/community/assets/38306844/4674dc36-f8f0-4303-a3a1-96d8fb1013db)

I used this domain name for testing which is called "momo.online".  

I also using  `export INGRESS_DOMAIN="momo.online"` and below manifest.

```
cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: prometheus-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https-prom
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: telemetry-gw-cert
    hosts:
    - "prometheus.${INGRESS_DOMAIN}"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus-vs
  namespace: istio-system
spec:
  hosts:
  - "prometheus.${INGRESS_DOMAIN}"
  gateways:
  - prometheus-gateway
  http:
  - route:
    - destination:
        host: prometheus
        port:
          number: 9090
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: prometheus
  namespace: istio-system
spec:
  host: prometheus
  trafficPolicy:
    tls:
      mode: DISABLE
---
EOF
```
Also below is my promethus service. Please ignore MetaILB service which is just used for testing before. I got load balancer service from cloud provider later.

![112630](https://github.com/istio/community/assets/38306844/43279446-816b-44d5-93a2-18e3218b213e)

![112927](https://github.com/istio/community/assets/38306844/517bd06d-b93d-47ea-99ae-89658c80dc04)

When I try to access  `prometheus.momo.online` from my browser, it told me that browser is unable to get service.

In that case , I should configure  `prometheus.momo.online`  on public network DNS server before I configure it on istio part. Is it right?

Last please forgive me for my poor expression. My english is very poor. 

Any suggestion or help is appreciated!
