### DISCUSSION TITLE
I want to replace proxyv2 with a new proxy image.

### DISCUSSION THREAD

**Discussion by Ruanjq98** [istio/istio#48916] [Q&A] [answered]
I want to replace proxyv2 with a new proxy image.
What do I need to do.
Thank you.

**Comment by hanxiaop** [comment]
set `global.proxy.image`

**Reply by zirain** [reply]
you can also try with annotation `sidecar.istio.io/proxyImage`

**Reply by Ruanjq98** [reply]
Can you give me an example?

For example, this
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
```

**Reply by zirain** [reply, marked as answer]
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      annotations:
        sidecar.istio.io/proxyImage: "istio/proxyv2:1.20.1"
      labels:
        app: sleep
    spec:
      terminationGracePeriodSeconds: 0
      serviceAccountName: sleep
      containers:
      - name: sleep
        image: curlimages/curl
        command: ["/bin/sleep", "infinity"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /etc/sleep/tls
          name: secret-volume
      volumes:
      - name: secret-volume
        secret:
          secretName: sleep-secret
          optional: true
```

**Reply by Ruanjq98** [reply]
thank you

**Reply by Ruanjq98** [reply]
set global.proxy.image 

 Can you elaborate on that? Thank you.

**Reply by hanxiaop** [reply]
How did you install istio?

**Reply by Ruanjq98** [reply]
Is that what it looks like?
```
istioctl install --set global.proxy.image：xxxx 
```

Is there any solution that supports hot deployment?

**Reply by hanxiaop** [reply]
```
istioctl install --set values.global.proxy.image：xxxx
```
No hot deployment, you need to do re-injection.

**Comment by rootsongjc** [comment]
You can refer to this configuration:

```yaml
pilot:
  image: "our.registry.com/proxy-docker-hub/istio/pilot:1.19.1"
global:
  hub: "our.registry.com/proxy-docker-hub/istio"
  tag: "1.19.1"
  proxy:
    image: "proxyv2"
  proxy_init:
    image: "our.registry.com/proxy-docker-hub/istio/proxyv2:1.19.1"
```

Here is the doc: https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig
