### DISCUSSION TITLE
VirtualService configruation for uriRegexRewrite

### DISCUSSION THREAD

**Discussion by safrrhmn** [istio/istio#48969] [Q&A]
I have been trying many things to get `uriRegexRewrite `working however failed. Here is the virtual service

```yaml 
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: abc-vservice
spec:
  hosts:
    - abc.xyz.com
    - abc-service.xyz.svc.cluster.local
  gateways:
    - istio-ingress/default-gateway
    - mesh
  http:
  - match:
    - uri:
        regex: "abc/(.*[$WS]{2}([?]{1}wsdl)?)"
    rewrite:
      uriRegexRewrite:
        match: "abc/(.*[$WS]{2}([?]{1}wsdl)?)"
        rewrite: "abc/Services/$1"
      route:
      - destination:
          host: abc-service.xyz.svc.cluster.local
          port:
            number: 8080
        headers:
          response:
            set:
              Strict-Transport-Security: max-age=31536000; includeSubDomains
```

Is it syntactically correct? The document does not have a clear example of `uriRegexRewrite`. Thanks in advance
