### DISCUSSION TITLE
Help configuring VirtualService and DestinationRule for a legacy TLS application

### DISCUSSION THREAD

**Discussion by russellrc-keebo** [istio/istio#48975] [Q&A]
Hi,

I am new to Istio and I am having difficulties configuring the Istio resources for an application.  I've tried different things already, but I just keep getting 503 errors.

Some context about the application
* The application is a legacy Java web server that handles it's own TLS communication.
* The receives only internal traffic
* We generate the client certificate and private key for the service, and pass them to the K8s Deployment through a mount volume.  * The K8s Service exposes the port `443`. The `spec.type` is `LoadBalancer`, and the LB type is Internal (`networking.gke.io/load-balancer-type: "Internal"`).
* The Service port config is this:
```
    - name: https-myapp
      protocol: TCP
      appProtocol: https
      port: 443
      targetPort: {{ .Values.snowflake.port }}
```
* The IP address of the Service is associated with the DNS record used to generate the certificate and private key.
* The client applications that send requests to this application use the DNS record

Here is my Istio cofiguration so far:

```
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: myapp
spec:
  exportTo:
    - "." # Export only to this namespace
  hosts:
    - myapp.mycompany.com
    - myapp.mynamespace.svc.cluster.local
  http:
    - name: "http-default-route"
      route:
        - destination:
            host: myapp.mynamespace.svc.cluster.local
  tls:
    - match:
        - port: 443
          sniHosts:
            - myapp.mycompany.com
      route:
        - destination:
            host: myapp.mynamespace.svc.cluster.local
          weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: myapp
  exportTo:
    - "." # Export only to this namespace
  host: myapp.mynamespace.svc.cluster.local
  workloadSelector:
    matchLabels:
      app: myapp
  trafficPolicy:
    tls:
      mode: SIMPLE
      clientCertificate: /opt/myapp/tls/tls.crt
      privateKey: /opt/myapp/tls/tls.key
    loadBalancer:
      simple: LEAST_REQUEST
    connectionPool:
      tcp:
        connectTimeout: 180s
        maxConnectionDuration: 300s
      http:
        idleTimeout: 180s
        maxRequestsPerConnection: 1
        h2UpgradePolicy: DO_NOT_UPGRADE
        useClientProtocol: true
```

I also tried changing the traffic policy to `tls.mode`: NONE

Any help would be greatly appreciated, as I have hit a road block.
