### DISCUSSION TITLE
How to regenerate metric labels removed by Telemetry API in a new Telemetry API?

### DISCUSSION THREAD

**Discussion by xjtupdy** [istio/istio#49040] [Q&A]
If I removed a set of labels in Namespace-specific Telemtry API with Namespace-scoped overrides, then I want to resume them in Workload-specific Telemetry API with Workload-scoped overrides. How can I configure the new Telemtry?

In Telemtry API doc, there are some expressions about this below, I am wondering whether my requirement can be implemented:

Specified overrides will be applied in order. They will be applied on top of inherited overrides from other resources in the hierarchy in the following order:
  Mesh-scoped overrides
  Namespace-scoped overrides
  Workload-scoped overrides
Because overrides are applied in order, users are advised to order their overrides from least specific to most specific matches. That is, it is a best practice to list any universal overrides first, with tailored overrides following them.

In EnvoyFilter, I can achieve it which "REPLACE" the "istio.stats" Filter totally. 
However, in Telemetry API, the field MetricsOverrides.TagOverride.Operation can be set as "UPSERT" or "REMOVE", maybe both of Operations can't regenerate the labels removed previously?

**Comment by xjtupdy** [comment]
I regenerate a label by using expressions of [Envoy attributes](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/attributes) and Peer metadata.
https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/#use-expressions-for-values
```
        - tagOverrides:
            source_app:
              operation: UPSERT
              value: "downstream_peer.labels['app'].value"
```
Then I find "dimensions" field in Envoy config_dump. 
`
\"dimensions\":{\"source_app\":\"downstream_peer.labels['app'].value\"}
`

Is it meaning that label "source_app" is considered as a customized label currently? 
Will it be slower?

**Reply by xjtupdy** [reply]
if setting the value of source_app as "downstream_peer.labels['app'].value", server inbound metrics have right values, but the source_app of client outbound metrics is "unknown".
Now I need to find a solution to distinguish between client and server in expressions.

**Reply by zirain** [reply]
will https://istio.io/latest/docs/reference/config/telemetry/#MetricSelector help?

**Reply by xjtupdy** [reply]
Thanks for your reply.
Yes, it helps. By overriding "source_app" of CLIENT and SERVER seperately, I correctly get the label "source_app" removed previously.
```
        - tagOverrides:
            source_app:
              operation: UPSERT
              value: "node.metadata['LABELS']['app']"
          match:
            mode: CLIENT
            metric: ALL_METRICS
        - tagOverrides:
            source_app:
              operation: UPSERT
              value: "downstream_peer.labels['app'].value"
          match:
            mode: SERVER
            metric: ALL_METRICS
```
But this solution is a little strange because "source_app" is a default tag.
