### DISCUSSION TITLE
issues with destination rule load balncer and outlierDetection

### DISCUSSION THREAD

**Discussion by ogolan-ig** [istio/istio#49041] [Q&A]
hi,

im having some strange behaviour with http request ot a service with replicates. 

when i add to destination rule 
 outlierDetection:
      baseEjectionTime: 3m
      consecutive5xxErrors: 1
      interval: 1s
      maxEjectionPercent: 100  
      
  all the trafic goes to the same instace regardless of how many instances are running and the load balancing strategy. 
only if there is an 5xx error wil lthe traffic reach another node ( until   baseEjectionTime: is over). 

there is also some strange bevahiour regarding http2MaxRequests: 1. if i use outlierDetection and make an http request thats a while to complete, new http request will wait until the first done is finished. even though there are other idle instances. 

if i do not use outlierDetection i get istio upstream connect error or disconnect/reset before headers. reset reason: overflow for the second request if the first one did not complete yet.

thi is the destination rule 

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: billing-api-service-rule
  namespace: stage
spec:
  host: billing-api-service.stage.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    loadBalancer:
      simple: LEAST_REQUEST
    connectionPool:
      http:
        maxRequestsPerConnection: 1
        http1MaxPendingRequests: 1
        http2MaxRequests: 1
      tcp:
        maxConnections: 1
    outlierDetection:
      baseEjectionTime: 3m
      consecutive5xxErrors: 1
      interval: 1s
      maxEjectionPercent: 100  
      
```
      
      
      
      
 and this is the virtual service 
      
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
spec:
  gateways:
  - istio-system/ingressgateway-private
  hosts:
  - billingapi.stage.com
  http:
  - match:
    - gateways:
      - istio-system/ingressgateway-private
      uri:
        prefix: /
    route:
    - destination:
        host: billing-api-service.stage.svc.cluster.local
        port:
          number: 80

```
