### DISCUSSION TITLE
Some problem with additional TCP port in ingress-gateway.

### DISCUSSION THREAD

**Discussion by vsfomin** [istio/istio#49084] [Q&A] [answered]
I want to expose postgresql outward through an internal gateway. 
To do this, I added one more port in helm template _gateways/istio-ingress/values.yaml_ to the other ports:
```
- name: postgresql
      port: 5432
      protocol: TCP
      targetPort: 5432
```
By doing a helm upgrade istio-ingress .\manifests\charts\gateways\gateways\\istio-ingress\ -n istio-ingress I can see that the service istio-ingressgateway and port 5432 is now available in it
```
spec:
  ports:
    - name: status-port
      protocol: TCP
      port: 15021
      targetPort: 15021
      nodePort: 31476
    - name: http2
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32488
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
      nodePort: 30976
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 31265
```

But if I look at the ports that are listening inside the istio-ingressgateway container, I see ports 8080, 8443 15021 but I don't see the new port 5432.  You can see it below.
```
[root@dev-cnv-new-nodepool-46354-mia4o ~]# ip netns exec istio ss -lpn | grep 8443
tcp    LISTEN     0      128       *:8443                  *:*                   users:(("envoy",pid=109119,fd=37))
tcp    LISTEN     0      128       *:8443                  *:*                   users:(("envoy",pid=109119,fd=36))
[root@dev-cnv-new-nodepool-46354-mia4o ~]# ip netns exec istio ss -lpn | grep 8080
tcp    LISTEN     0      128       *:8080                  *:*                   users:(("envoy",pid=109119,fd=35))
tcp    LISTEN     0      128       *:8080                  *:*                   users:(("envoy",pid=109119,fd=34))
[root@dev-cnv-new-nodepool-46354-mia4o ~]# ip netns exec istio ss -lpn | grep 15021
tcp    LISTEN     0      128       *:15021                 *:*                   users:(("envoy",pid=109119,fd=25))
tcp    LISTEN     0      128       *:15021                 *:*                   users:(("envoy",pid=109119,fd=24))
[root@dev-cnv-new-nodepool-46354-mia4o ~]# ip netns exec istio ss -lpn | grep 5432
```

Accordingly, Elastic Load balancer does not see it either. But see 80, 443 and 15021
I've added Gateway and VirtualService too:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cnv-postgresql-gateway
  namespace: istio-ingress
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - dev-cnv-srv.example.com
      port:
        name: postgresql
        number: 5432
        protocol: TCP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: postgres-vs
  namespace: cnv-dev
spec:
  hosts:
  - dev-cnv-srv.example.com
  gateways:
  - cnv-postgresql-gateway
  tcp:
  - match:
    - port: 5432
    route:
    - destination:
        host: postgresql
        port:
          number: 5432
```
What could be the problem?

**Comment by abasitt** [comment, marked as answer]
TCP route is not created when the VS is either missing or not correctly applied. In your case VS is not applied correctly because you are referring to a gateway from istio-ingress ns. Below will work.

```
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cnv-postgresql-gateway
  namespace: istio-ingress
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - dev-cnv-srv.example.com
      port:
        name: tcp-postgresql
        number: 5432
        protocol: TCP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: postgres-vs
  namespace: cnv-dev
spec:
  hosts:
  - dev-cnv-srv.example.com
  gateways:
  - istio-ingress/cnv-postgresql-gateway
  tcp:
  - match:
    - port: 5432
    route:
    - destination:
        host: postgresql
        port:
          number: 5432
```
