### DISCUSSION TITLE
Problems with Istio first-level virtualService delegate to specific namespace with many second-level virtualService

### DISCUSSION THREAD

**Discussion by zhizhencai** [istio/istio#49096] [Q&A]
## Background: 
We have a blue/green deployment for our applications. We are going to deploy the first-level virtualService at control-plane, then leverage the [delegate feature](https://istio.io/latest/docs/reference/config/networking/virtual-service/#Delegate) to delegate the traffic to blue/green environments. The second-level virtualServices are supposed to deploy in the blue/green environments. And they are configured with each application. The goal is to delegate the traffic to the application in the blue/green environment we needs.

We found when we specify the delegate rules in the first-level virtualService, we must define the both namespace and delegate name. 
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
  namespace: control-plane
spec:
  hosts:
  - "*"
  gateways:
  - bookinfo-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    delegate:
      namespace: blue
      name: application1
  - match:
    - uri:
        prefix: "/"
    delegate:
      namespace: blue
      name: application2
...
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: application1
  namespace: blue
spec:
  http:
  - match:
    - uri:
        prefix: /api/v1/application1
    route:
    - destination:
        host: application2
        port:
          number: 9080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: application2
  namespace: blue
spec:
  http:
  - match:
    - uri:
        prefix: /api/v1/application2
    route:
    - destination:
        host: application2
        port:
          number: 9080
---
...
```
## Issue:
Due to there are many applications, there will be many second-level virtualServices. We see the delagate.namespace and delegate.name are both not required in [delegate documentation](https://istio.io/latest/docs/reference/config/networking/virtual-service/#Delegate). We want to only specify the delegate.namespace and not delagate.name. Then let first-level virtualService to scan all the second-level virtualServices in the delegated namespace and feed to istio ingress. But the istio ingress seems will not work like this. Also we tried to use Regex under the delegate.name. This didn't work either. 
```bash
istioctl proxy-config route central-istio-ingress-5cbd47c76b-hgg5t                                     
NAME         VHOST NAME        DOMAINS     MATCH                  VIRTUAL SERVICE
http.80      blackhole:80      *           /*                     404
http.443     blackhole:443     *           /*                     404
```
## Question:
Is there a way to let one entry of delegate to match many virtualService in delegate namespace?

Thank you in advance.
