### DISCUSSION TITLE
Multi-datacenter traffic is working, but cannot access pods and services between clusters

### DISCUSSION THREAD

**Discussion by ku9nov** [istio/istio#49109] [Q&A] [answered]
I have 2 development clusters located in different regions and different VPCs, of course. Multi-datacenter traffic is working fine, but I cannot reach pods and services in the other cluster. I need to configure ScyllaDB to interact between clusters using PodIP, but pods and services do not have access to each other across clusters. What is the best way to set up connectivity between pods?

I have a lot of configurations, so I'm not sure which ones will be useful here. I will provide all upon request. 

<img width="995" alt="Знімок екрана 2024-01-31 о 11 42 22" src="https://github.com/istio/istio/assets/69673517/591868ee-89b4-492b-8339-a89d136cfaeb">
<img width="908" alt="Знімок екрана 2024-01-31 о 11 42 41" src="https://github.com/istio/istio/assets/69673517/c5cc95a6-91a2-4613-b395-53b25f2a06b2">
Screenshots proving that inter-regional deployment is indeed working are available.

**Comment by ku9nov** [comment]
Despite the fact that multi-regional traffic is functioning,
if following this guide: https://istio.io/latest/docs/ops/diagnostic-tools/multicluster/

at this step using REMOTE_POD_IP,
<img width="950" alt="Знімок екрана 2024-01-31 о 14 51 56" src="https://github.com/istio/istio/assets/69673517/ecffcc1c-4ed3-420a-a8e5-85f752bfd623">

I encounter this error.
<img width="1492" alt="Знімок екрана 2024-01-31 о 14 50 04" src="https://github.com/istio/istio/assets/69673517/a55cf3c7-40e8-4fd9-8d29-f99c31497af1">

**Comment by abasitt** [comment]
I believe you are trying to achieve multi-cluster using Istio multi cluster modes?.

1. Which multicluster-controlplan mode are you using ? Multi-primary? Primary-remote ? ...
2. Which multicluster-network mode are you using ? For pod level access AFAIK you can only do it with a flat-network.

**Reply by ku9nov** [reply]
1. I believe you are trying to achieve multi-cluster using Istio multi cluster modes? Of course.
2. Multi-primary
3. What do you mean by "flat-network"? As I mentioned earlier, I am using two clusters in different regions and different VPCs, meaning I have two separate networks.
Update. I found your presentation on YouTube, and now I can answer that the discussion is about different networks. So the question is, if in my situation it's not possible to connect via IP, how can it be done?

In both clusters (DOKS `sfo3` and `fra1` regions), I have two namespaces `scylla`. I need to make it so that they can communicate and have a direct connection. Both have services named `scylla-cluster-client`. If in the `sfo3` cluster I can access this service as `scylla-cluster-client.scylla.cluster.local`, how can I access the `fra1` `cluster-client.scylla` from `sfo3`?

If this is not possible, do I need to open a port on the ingress for this database, create a DNS record in the Digital Ocean console, and connect them in that way? Or can I somehow achieve this without exposing the database to the outside world using tools like Istio?

Thank you very much for your responses.

**Reply by abasitt** [reply]
if the requirements is to make services based access, then you can workaround with it with East-West gateways. Did you follow this guide ?
https://istio.io/latest/docs/setup/install/multicluster/multi-primary_multi-network/

In summary you need to have. 

- Common CA between clusters.https://istio.io/latest/docs/setup/install/multicluster/before-you-begin/#configure-trust
- expose the east-west gateway using digitaloceans LBs. I have a limited knowledge of DOKS but I believe there will be an option to expose a service with Private LB IP instead of public. Even if its public, it's pretty safe because the communication happens over mTLS.

If the direct PODIP is mandatory e.g. headless service. You have to find an alternative, I will suggest to do peering between two different VPC or try cilium clustermesh if that's possible which is the default CNI of DOKS and then run Istio multicluster on top and for that you don't have to worry about east-west gateways.

**Reply by ku9nov** [reply]
1. [multi-primary](https://istio.io/latest/docs/setup/install/multicluster/multi-primary_multi-network/), yeah, it's done and verified
2. Common CA between clusters. Also done and verified. You can find how i can automated it [here](https://github.com/cert-manager/cert-manager/discussions/6568).
3. Yep, it seems that I don't fully understand the role of the East-West gateway here. I know that communication between clusters goes through it, but I don't comprehend how it needs to be reconfigured for this task. I need to more investigate this case, and if there are any updates, I will get back to you. Thank you. For now, the question remains open.

**Reply by ku9nov** [reply]
Hold on, it seems we've gotten a bit tangled.

I understand that in the third point, you meant simply configuring the East-West gateway, which, as you can see from my screenshots in Kiali, is already set up, and the clusters have access to each other.

So, according to your opinion, it seems that there is nothing more to be done in Istio, and the focus should be on configuring Cilium ClusterMesh. However, bringing up this question
```
In both clusters (DOKS sfo3 and fra1 regions), I have two namespaces scylla. I need to make it so that they can communicate and have a direct connection. Both have services named scylla-cluster-client. If in the sfo3 cluster I can access this service as scylla-cluster-client.scylla.cluster.local, how can I access the fra1 cluster-client.scylla from sfo3?
```
 without an answer implies that connecting to a service from another cluster is impossible—no endpoint exists. Is that correct?

**Reply by abasitt** [reply]
Seems like you are well set-up. My suggestion regarding clustermesh was only if you want need direct pod access, if the service level access is enough, then you don't need it.

`In both clusters (DOKS sfo3 and fra1 regions), I have two namespaces scylla. I need to make it so that they can communicate and have a direct connection. Both have services named scylla-cluster-client. If in the sfo3 cluster I can access this service as scylla-cluster-client.scylla.cluster.local, how can I access the fra1 cluster-client.scylla from sfo3?`

Sorry i missed above. Istio will harmonize the service-names with endpoints under common service names. If you have a service-name scylla-cluster-client in both cluster in the same namespace, istio will auto load-balance between the endpoints in both clusters. https://istio.io/latest/docs/ops/deployment/deployment-models/#namespace-tenancy

you can check with istioctl pc ep podname.ns to see the endpoints of service scylla-cluster-client.scylla.cluster.local and it should be localpod IP and east-west gatewayIP with port 15443.

**Reply by ku9nov** [reply]
Yeah, and it's working as expected:
```
xx.xx.xx.xx:15443                                      HEALTHY     OK                outbound|9042||scylla-cluster-client.scylla.svc.cluster.local
10.244.0.121:9042                                       HEALTHY     OK                outbound|9042||scylla-cluster-client.scylla.svc.cluster.local
```
For the Scylla database, the node in Europe should connect to the node in the USA (nodes' addresses configured in Scylla manifests). I can't do it with PodIP, I understand. However, service names are also identical. When I try to connect from Europe to the USA like this:
```
root@scylla-cluster-fra1-a-0:/# cqlsh scylla-cluster-client.scylla
Connected to Scylla at scylla-cluster-client.scylla:9042
[cqlsh 6.2.0 | Scylla 5.4.0-0.20231205.58a89e7a4231 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh> describe keyspaces;

system_auth    system_distributed  system_traces
system_schema  system              system_distributed_everywhere

```
Of course, I connect to the EU cluster, e.g., the local cluster. It means services aren't a good solution for this task? Maybe it would be better if I configure some redirection with Istio? For example, some Istio resource will be assigned for the EU cluster, redirecting scylla-cluster-client.scylla.usa to the USA Scylla, and for the USA cluster, redirecting scylla-cluster-client.scylla.eu to the EU Scylla. I'm sorry; I'm not very familiar with Istio and K8s. I just think Istio has something like this because it logically allows services between clusters.

**Reply by ku9nov** [reply]
Also, for a clearer example:

I have Elasticsearch in the USA, and I can make requests to it:
```
curl --user elastic:xxxx -k "https://elasticsearch-es-http.default:9200"
{
  "name" : "elasticsearch-es-default-0",
  ...
}

```
But I can't do it from the EU cluster:
```
curl --user elastic:xxxx -k "https://elasticsearch-es-http.default:9200"
curl: (6) Could not resolve host: elasticsearch-es-http.default

```

**Reply by abasitt** [reply]
Apologies if i missed something, but based on what I understood so far, I suggest to look in to below.

- Multicluster locality aware routing or subset based routing. You can control to target specific endpoints in a specific cluster using the same svc name. e.g. calling scylla-cluster-client.scylla and you indent to hit ep in a specific region and failover to another region during outage, you can do that with locality routing.
- service names are not auto resove, this is a limitation of coredns. So you either need to create similar names in every cluster using the same namespace or use istio dns-proxy. https://istio.io/latest/docs/ops/deployment/deployment-models/#dns-with-multiple-clusters.

if you can add some flow drawings, it could be easier to answer.

**Reply by ku9nov** [reply]
I'm really sorry, but I don't understand what I need to do. I follow your [documentation](https://istio.io/latest/docs/ops/configuration/traffic-management/dns-proxy/), and everything works which remained in this docs, but my pods can't communicate directly with the service in another cluster. I tried to illustrate what's happening now:
<img width="503" alt="Знімок екрана 2024-02-02 о 16 37 23" src="https://github.com/istio/istio/assets/69673517/c193a0f7-e512-4d72-8067-a7901f8790e9">

 and I'll repeat it using a curl request as an example:
I have Elasticsearch in the East cluster, and I can make requests to it from any pods in east cluster:
```
curl --user elastic:xxxx -k "https://elasticsearch-es-http.default:9200"
{
  "name" : "elasticsearch-es-default-0",
  ...
}
```
But if I'm trying make request from pod in west cluster, to elasticsearch, which in east cluster, it isn't successfull:
```
curl --user elastic:xxxx -k "https://elasticsearch-es-http.default:9200"
curl: (6) Could not resolve host: elasticsearch-es-http.default
```

**Reply by abasitt** [reply]
the problem i see from west cluster is that no resolution. first the dns part has to be fixed. As an alternative to dns-proxying:
in the west cluster can you create the service name e.g. elasticsearch-es-http.default. just the service name will do so that coredns can respond with something, the routing part will be taking care by Istio.

**Reply by ku9nov** [reply]
Yes, this is a very simple and effective hack, but in this case, if I expand the elasticsearch pod in this cluster, I will be addressing both clusters simultaneously using this service name. The question is how can I ensure that from the Western pod I consistently access only the Eastern service without load balancing. This will allow configuring interaction and synchronization between databases when one database knows that another database is located at this address and does not refer to itself.

**Reply by ku9nov** [reply]
And I hope we both understand that initially we were discussing Scylla, but now Elasticsearch is being used only for the sake of example and better visualization, as well as for easy verification of the feasibility of the idea.

**Reply by abasitt** [reply, marked as answer]
`Yes, this is a very simple and effective hack, but in this case, if I expand the elasticsearch pod in this cluster, I will be addressing both clusters simultaneously using this service name`
You don't need to expand elastic pod to the west cluster, only need to create the service-name for dns and the istio-proxy will do the load-balancing in the dataplane to correct endpoint to east cluster.
`The question is how can I ensure that from the Western pod I consistently access only the Eastern service without load balancing.`
if you want to enforce this, I suggest to look in to the locality based routing or subset base routing https://istio.io/latest/docs/ops/configuration/traffic-management/multicluster/#partitioning-services

**Reply by ku9nov** [reply]
Okay, we have a working multi-datacenter cluster and deployed the HelloWorld Istio sample on them.
This is 100% working:
```
kubectl exec -n sample -c sleep \
          $(kubectl get pod -n sample -l \
          app=sleep -o jsonpath='{.items[0].metadata.name}') \
          -- curl -sS helloworld.sample:5000/hello
Hello version: v2, instance: helloworld-v2-7f46498c69-q2hcb
kubectl exec -n sample -c sleep \
          $(kubectl get pod -n sample -l \
          app=sleep -o jsonpath='{.items[0].metadata.name}') \
          -- curl -sS helloworld.sample:5000/hello
Hello version: v1, instance: helloworld-v1-77b446d6f4-ffl79
```
Now we want to configure ALL traffic from the `helloworld service` in `cluster-1` to only go to the `helloworld service` in `cluster-2`. If we use code from the docs like this:
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: mysvc-per-cluster-dr
  namespace: sample
spec:
  host: mysvc.myns.svc.cluster.local
  subsets:
  - name: cluster-1
    labels:
      topology.istio.io/cluster: cluster-1
  - name: cluster-2
    labels:
      topology.istio.io/cluster: cluster-2
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: mysvc-cluster-local-vs
  namespace: sample
spec:
  hosts:
  - mysvc.myns.svc.cluster.local
  http:
  - name: "cluster-1-local"
    match:
    - sourceLabels:
        topology.istio.io/cluster: "cluster-1"
    route:
    - destination:
        host: mysvc.myns.svc.cluster.local
        subset: cluster-1
  - name: "cluster-2-local"
    match:
    - sourceLabels:
        topology.istio.io/cluster: "cluster-2"
    route:
    - destination:
        host: mysvc.myns.svc.cluster.local
        subset: cluster-2
```
This code will only keep local traffic, similar to this configuration in `IstioOperator`:
```
serviceSettings:
- settings:
    clusterLocal: true
  hosts:
  - "*.myns.svc.cluster.local"
```
So, it's not okay for our case.
When I try to switch cluster names in `sourceLabels` like this:
```
 http:
  - name: "cluster-1-local"
    match:
    - sourceLabels:
        topology.istio.io/cluster: "cluster-2"
    route:
    - destination:
        host: mysvc.myns.svc.cluster.local
        subset: cluster-1
  - name: "cluster-2-local"
    match:
    - sourceLabels:
        topology.istio.io/cluster: "cluster-1"
    route:
    - destination:
        host: mysvc.myns.svc.cluster.local
        subset: cluster-2
```
which looks like if your request from `cluster-1` goes to `mysvc.myns.svc.cluster.local` in `cluster-2`, then I have these errors:
```
upstream connect error or disconnect/reset before headers. retried and the latest reset reason: remote connection failure%   
```
If I use `mysvc.myns` instead of `mysvc.myns.svc.cluster.local`, I have the same behavior. In some configgurations i have empty responce, in other load balancing v1 v2 just working.

**Reply by ku9nov** [reply]
We need something like this:
<img width="806" alt="Знімок екрана 2024-02-05 о 19 50 22" src="https://github.com/istio/istio/assets/69673517/a9a92372-5571-4385-a658-47af7e65d6fa">
But we can't use PodIP, so I want to use service names for VPC peering. Alternatively, I aim to set DNS for the Pods in the Istio cluster, but after that, the DNS name isn't reachable from the second cluster. So, I can't connect to them.

**Reply by ku9nov** [reply]
Was re-created deployment helloworld in cluster-1:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-region1.zone1
  labels:
    app: helloworld
    version: region1.zone1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      version: region1.zone1
  template:
    metadata:
      labels:
        app: helloworld
        version: region1.zone1
    spec:
      containers:
      - name: helloworld
        env:
        - name: SERVICE_VERSION
          value: region1.zone1
        image: docker.io/istio/examples-helloworld-v1
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
```
in cluster-2
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-region1.zone2
  labels:
    app: helloworld
    version: region1.zone2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      version: region1.zone2
  template:
    metadata:
      labels:
        app: helloworld
        version: region1.zone2
    spec:
      containers:
      - name: helloworld
        env:
        - name: SERVICE_VERSION
          value: region1.zone2
        image: docker.io/istio/examples-helloworld-v1
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
```
Created Weighted load balancer rule in cluster-1:
```
kubectl apply -n sample -f - <<EOF
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: helloworld
spec:
  host: helloworld.sample.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      localityLbSetting:
        enabled: true
        distribute:
        - from: region1/zone1/*
          to:
            "region1/zone2/*": 100
    outlierDetection:
      consecutive5xxErrors: 100
      interval: 1s
      baseEjectionTime: 1m
EOF
```
Destination Rule is fully ignored:
```
kubectl exec -n sample -c sleep \
          $(kubectl get pod -n sample -l \
          app=sleep -o jsonpath='{.items[0].metadata.name}') \
          -- curl -sS helloworld.sample:5000/hello
Hello version: region1.zone1, instance: helloworld-region1.zone1-ccb79757d-lcgbs
kubectl exec -n sample -c sleep \
          $(kubectl get pod -n sample -l \
          app=sleep -o jsonpath='{.items[0].metadata.name}') \
          -- curl -sS helloworld.sample:5000/hello
Hello version: region1.zone2, instance: helloworld-region1.zone2-5f554ddc56-7bcg8
```
<img width="872" alt="Знімок екрана 2024-02-05 о 20 37 41" src="https://github.com/istio/istio/assets/69673517/f9c530ad-2dc5-4b55-ad3e-9095da24668e">
