### DISCUSSION TITLE
About problems with image pulling of envoyfilter in docker.io

### DISCUSSION THREAD

**Discussion by ZachariahHu** [istio/istio#49135] [General]
![image](https://github.com/istio/istio/assets/140360349/4c0c8b35-643c-4d2e-8a71-b504fa57c0bc)

Hi, I have a question: 
I do not want to go to docker.io to pull the image, how to specify the image repository?

**Comment by zirain** [comment]
https://istio.io/latest/docs/reference/config/annotations/#SidecarProxyImage

**Reply by ZachariahHu** [reply]
Can it be specified in deployment? For me, I will only write the deployment yaml file.

**Reply by zirain** [reply]
sure

**Reply by ZachariahHu** [reply]
I don’t know how to write the configuration file. Can you teach me how to specify it? How should I configure the image of the specified initContainer?

**Reply by ZachariahHu** [reply]
Can you give me a configuration example?

**Reply by zirain** [reply]
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      annotations:
        "sidecar.istio.io/proxyImage": docker.io/istio/proxyv2:1.20.0
      labels:
        app: httpbin
        version: v1
    spec:
      serviceAccountName: httpbin
      containers:
      - image: docker.io/kong/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80
```
