### DISCUSSION TITLE
Istio Multi cluster setup | Using istio smart DNS proxying | TCP traffic routed to BlackholeCluster

### DISCUSSION THREAD

**Discussion by Muthumj123** [istio/istio#49144] [General]
```
meshConfig:
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
```
Issue : After setting this up, Existing ServiceEntries (like aws dbs) for TCP traffic with `resolution: DNS`  getting routed to `BlackHoleCluster `. If we change the `resolution to NONE`  it works correctly.
Checked enpoints, listerners and even envoy config dump, could not track down why the behaviour is different. 
Every issues or post that I read realted to this, says to set DNS VIP allocation for ServiceEntry but does not work for my case.
FYI. `Outbout traffic is registry only`

Is this a shorting coming for istio DNS?  Any insight would help to understand this behaviour better.

Attaching access logs from proxy side car.

If resolution of serviceEntry is set to DNS, then access logs :
```
{
	"protocol": null,
	"upstream_local_address": null,
	"upstream_host": null,
	"authority": null,
	"start_time": "2024-01-18T21:42:47.347Z",
	"user_agent": null,
	"bytes_received": 0,
	"upstream_transport_failure_reason": null,
	"route_name": null,
	"request_id": null,
	"upstream_service_time": null,
	"response_code_details": null,
	"downstream_local_address": "172.xx.xx.xx:9142", #vpc private endpoint for db
	"x_forwarded_for": null,
	"method": null,
	"downstream_remote_address": "100.xx.xx.xx:36140", #podip
	"response_flags": "UH",
	"requested_server_name": null,
	"response_code": 0,
	"upstream_cluster": "BlackHoleCluster",
	"bytes_sent": 0,
	"duration": 11,
	"client_ip": null,
	"path": null
}
```

Istio pc listeners 
`ADDRESS=240.240.0.58, DESTINATION=Cluster: outbound|9142||cassandra.eu-west-1.amazonaws.com`

If resolution of serviceEntry is set to NONE, then access logs looks like this and connects to the db.
```
{
	"method": null,
	"response_code": 0,
	"requested_server_name": null,
	"upstream_local_address": "100.1xx.xx.xx:60900", #podip
	"path": null,
	"protocol": null,
	"duration": 202,
	"upstream_host": "172.xx.xx.xx:9142", #vpc private endpoint for db
	"x_forwarded_for": null,
	"route_name": null,
	"bytes_received": 669,
	"upstream_cluster": "outbound|9142||cassandra.eu-west-1.amazonaws.com",
	"upstream_transport_failure_reason": null,
	"client_ip": null,
	"bytes_sent": 5698,
	"request_id": null,
	"user_agent": null,
	"response_code_details": null,
	"start_time": "2024-01-18T21:42:46.051Z",
	"upstream_service_time": null,
	"response_flags": "-",
	"downstream_remote_address": "100.xx.xx.xx:50350", #podip
	"downstream_local_address": "240.240.0.5:9142", # autoallocated VIP for the service entry
	"authority": null
}
```

**Comment by howardjohn** [comment]
I cannot fathom how NONE would work with auto_allocation. Basically that means the DNS response is going to return a bogus IP addrss (240.240.0.5), and envoy is going to pass the request through to that IP address. Since 240.240.0.5 is not as real IP its going to be broken.

DNS vs NONE mode should not impact traffic matching at all.

I feel there is maybe some information missing that explains this. Can you give more config like the Service entry, etc

See also https://istio.io/latest/docs/ops/configuration/traffic-management/traffic-routing/

**Comment by Muthumj123** [comment]
Our service entry looks like this. Many namspaces have same serviceentry but all of them are namespaced scope ( `exportTo: - .`)

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
spec:
  exportTo:
    - .
  hosts:
    - cassandra.eu-west-1.amazonaws.com
  location: MESH_EXTERNAL
  ports:
    - name: tcp
      number: 9142
      protocol: TCP
  resolution: DNS
```

And destination rule, like this : 
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
spec:
  host: cassandra.eu-west-1.amazonaws.com
  trafficPolicy:
    tls:
      mode: DISABLE
```
