### DISCUSSION TITLE
Issue with Deploying Istio Configuration on AKS in EUS2

### DISCUSSION THREAD

**Discussion by Manoj-Kothapalli-Microsoft** [istio/istio#49214] [Q&A]
We're encountering an unusual problem with our AKS deployment in two regions. Specifically, we maintain the same Istio configuration file for both regions. When we deploy in CUS, we're not facing any issues. However, when deploying in the EUS2 AKS cluster, it fails with the following error:

```
Received an error from AKS.Error output from Helm: Error: UPGRADE FAILED: cannot patch "xfcc-forward" with kind EnvoyFilter: admission webhook "validation.istio.io" denied the request: configuration is invalid: referenced type unknown (hint: try using the v3 XDS API): Envoy filter: could not resolve Any message type: type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
```

We've already updated to V3 configuration. Below is the common configuration that we're using. It's worth noting that a previous deployment with the same bits succeeded in both EUS2 and CUS. However, if we attempt to deploy the same bits again, it fails with this error only in EUS2, which is very strange.

**Envoy Filter File:**

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: xfcc-forward
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          forward_client_cert_details: ALWAYS_FORWARD_ONLY
          set_current_client_cert_details:
            subject: true
            cert: true
            chain: true
```

We appreciate any assistance in resolving this issue. Thank you.
