### DISCUSSION TITLE
Authorization based on the content of the query string parameter

### DISCUSSION THREAD

**Discussion by lorenzobassi96** [istio/istio#49212] [Q&A]
Good morning.

I am working on Istio 1.16.

In my environment, I have:

* A Kubernetes cluster
* Keycloak IDP (external to the cluster)
* oauth2proxy installed in the Kubernetes cluster.

Currently, I can authenticate using Authorization Bearer. If I try the following command:

```
curl -k https://x.x.x.x/somepath/ -H "Authorization: Bearer $TOKEN"
```

it works.

Of course, If I do not add the Authorization Bearer in the request, I'm redirected to Keycloak.

This is my starting point....

What I want to achieve is as follows: 
I want to base my Authorization on the content of the `query parameter`.

By using this curl command:

```
curl -k https://x.x.x.x/somepath/?access_token=$TOKEN
```

I want to either ALLOW or DENY the request based on the content of the query string parameter (JWT payload passed as `$TOKEN`).

How can I achieve this? I've seen that at the `RequestAuthentication` level, it's possible to configure the token as a query string parameter, but I can't find anything on the `AuthorizationPolicy` side.

Reading the documentation https://istio.io/v1.16/docs/reference/config/security/jwt/, I see that I need to add the `fromParam` field in `RequestAuthentication`. This is how I have set it in my case.
```
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: xran-idp-authn
  namespace: xran-idp
spec:
  jwtRules:
  - forwardOriginalToken: true
    fromParams:
    - access_token
    issuer: https://registry.local/auth/realms/jma
    jwksUri: https://registry.local/auth/realms/jma/protocol/openid-connect/certs
  selector: {}
```

I am having trouble understanding how to set the AuthorizationPolicy. Currently, I have it set like this:
```
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: xran-idp-authz-instance-ingress-second
  namespace: istio-system
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        hosts:
        - '*'
    when:
    - key: request.auth.claims[roles]
      values:
      - SomeSecificValues
```

But it seems not to be working.

Any suggestion or working examples to take reference from is welcome.

Thanks in advance!
