### DISCUSSION TITLE
TLS origination while keeping non-TLS option available (on same or different port not too important)

### DISCUSSION THREAD

**Discussion by Dines97** [istio/istio#49224] [Q&A] [answered]
Hi, 

In our cluster we have some legacy applications with not so legacy. Both application set sends logs to same elastic search. For non-legacy application we just disabled tls verification right on them. But for legacy application we want to create tls origination while keeping other way also. So, after reading documentation I came up with this:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: elastic1
  namespace: armageddon
spec:
  hosts:
  - elastic1 # Used to match with destination rule. Service not used by hostname
  addresses:
  - 10.113.202.88 # Actual address of service
  ports:
  - name: http # We want to create tls origination 
    number: 9201
    protocol: HTTP
    targetPort: 9200
  - name: https # Https works
    number: 9200
    protocol: HTTPS
  resolution: NONE # App uses IP in own configuration (http:// 10.113.202.88:9201/) so there is no need for dns resolution?

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: elastic1
  namespace: armageddon
spec:
  host: elastic1 # Used to match with service entry
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 9201 # I am not sure about this port. Should it be destination https port or http port specified in service entry
      tls:
        insecureSkipVerify: true # Skip tls verification for self signed certificate 
        mode: SIMPLE
```

When I try to curl https://10.113.202.88:9200 (the way non-legacy application did) it works (but I am not sure if there service entry involved because just by removing all of this it continues to work because we don’t have any restriction for egress traffic).  But when I try curl https://10.113.202.88:9201 it doesn’t return anything I just forced to ctrl+c. Can anybody tell me what I am doing wrong here? Also I left a bunch of comment string inside yaml if they are wrong can somebody explain to me why?

Thanks.

**Comment by rootsongjc** [comment]
You should not use the IP address directly when testing with curl as this bypasses Istio, instead, you should test with http://elastic1.armageddon.svc.cluster.local:9201 in the pod in the Istio mesh, making sure to test using the HTTP protocol.

**Reply by Dines97** [reply]
Okey this time I came up with this:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: elastic1
  namespace: armageddon
spec:
  hosts:
  - elastic1 # Used to match with destination rule. Service not used by hostname
  ports:
  - name: http-port
    number: 9201
    protocol: HTTP
    targetPort: 9200
  - name: https-port
    number: 9200
    protocol: HTTPS
  resolution: STATIC
  endpoints:
  - address: 10.113.202.88
---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: elastic1
  namespace: armageddon
spec:
  host: elastic1 # Used to match with service entry
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 9201 # I am not sure about this port. Should it be destination https port or http port specified in service entry
      tls:
        insecureSkipVerify: true # Skip tls verification for self signed certificate 
        mode: SIMPLE
```

It works with curl -k https://elastic1:9200 but this time when trying with curl http://elastic1:9201 prints out `error upstream connect error or disconnect/reset before headers. reset reason: connection termination`. Istio proxy logs are containing this information (first string successful with curl -k https://elastic1:9200 second unsuccessful with curl curl http://elastic1:9201):

```
"- - -" 0 - - - "-" 720 5002 19 - "-"  "-"  "-" "-" "-" "10.113.202.88:9200" outbound|9200||elastic1 10.116.6.36:47488 240.240.158.51:9200 10.116.6.36:41550 - -
"GET / HTTP/1.1" 503 UC upstream_reset_before_response_started{connection_termination} - "-" 0 95 1 - "-"  "http"  "curl/7.81.0" "e23e8ce4-f292-4c0b-8a34-fe5c5ff3c583" "elastic1:9201" "10.113.202.88:9200" outbound|9201||elastic1 10.116.6.36:41472 240.240.158.51:9201 10.116.6.36:38180 - default
```
