### DISCUSSION TITLE
TLS with Kubernetes Gatyeway API

### DISCUSSION THREAD

**Discussion by marquesj2-ppb** [istio/istio#49253] [Q&A] [answered]
Hi everyone 👋 

I'm trying to configure Istio Ingress using K8S Gateway API 
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: private
  labels:
    istio: private-istio
    app: private-istio
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: 'nlb'
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: 'ip'
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      hostname: '*.example.com'
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      hostname: '*.example.com'
      port: 443
      protocol: HTTPS
      tls:
        mode: MUTUAL
        certificateRefs:
          - name: tls-cert
      allowedRoutes:
        namespaces:
          from: All
```
Created an HTTPRoute that uses this gateway and I can connect to it, only problem is HTTPs does not have a valid certificate.
Using openssl I can see that the certificate is well passed from the k8s secret, but the root CA is not read at all.
```
CONNECTED(00000006)
depth=<private>, CN=example.com
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=<private>, CN=example.com
verify error:num=21:unable to verify the first certificate
... actual cert...
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 1703 bytes and written 425 bytes
Verification error: unable to verify the first certificate
```

this is my secret
```
apiVersion: v1
data:
  cacert: ++++++++
  cert: ++++++++
  key: ++++++++
kind: Secret
metadata:
  name: tls-cert
  namespace: istio-ingress
type: Opaque
```
