### DISCUSSION TITLE
Multiple manipulations to HTTP_FILTER using EnvoyFilter

### DISCUSSION THREAD

**Discussion by bregtaca** [istio/istio#49267] [Q&A]
Hello,

I am trying to do multiple manipulations to the same request in a fixed order for a specific application.
I want to unzip the body, change some urls in the body and zip the body again.
I wrote an EnvoyFilter to achieve the first 2 parts.

Both of these code blocks work when I deploy them separately.
However, when I deploy them as described below, only the first manipulation is done.

I also tried splitting them up in 2 EnvoyFilters with different priority, but it has the same result.

I am looking for guidance how I can combine 2 HTTP_FILTER manipulations after each other.
Is this even possible?
Or is there a way to do gzip decompression and compression in the lua rule?

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: data.ddt.geoserver-http-filter-all-in-one
  namespace: istio-system
spec:
  priority: 10
  workloadSelector:
    labels:
      app: myapp
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.decompressor
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.http.decompressor.v3.Decompressor
            decompressor_library:
              name: small
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.compression.gzip.decompressor.v3.Gzip
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.lua
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
            inlineCode: |
              function envoy_on_response(response_handle)
                response_handle:headers():add("Parsed", "true")
    
                body = response_handle:body()
                xmlString = tostring(body:getBytes(0, body:length()))
    
                #url manipulation code here
    
                response_handle:logErr("XMLString: "..xmlConvString)
                response_handle:body():setBytes(xmlConvString)
              end
```

Thanks in advance
Bregt
