### DISCUSSION TITLE
Call a virtualservice from Lua

### DISCUSSION THREAD

**Discussion by vladfr** [istio/istio#49297] [Q&A] [answered]
I have a `httpbin` deployed, with a VirtualService that defines a basic match route to the pod, and another route that matches on a header and gives a `directResponse`.

```
http:
    - match:
        - uri:
            prefix: "/"
          headers:
            x-flex-env:
              exact: "bad"
      directResponse:
        status: 500
        body:
          string: "this header is bad"
```

This works as expected, i.e. `curl httpbin -H 'x-flex-env: bad'` throws a 500 with the correct string "this header is bad".

I would like to call this cluster from a lua script in `EnvoyFilter`, essentially proxying in lua. The call works fine, the `httpbin` replies with its stuff.

Except for when I add the `bad` header in lua, I don't get the result from `directResponse`. The call makes it through to the `httpbin` container. Why is that?

```
k exec sleep-9454cc476-trzvl -- curl -vvv httpbin.flex:8000/headers -H 'X-Flex-Env: bad'
# Throws 500 this header is bad

k exec sleep-9454cc476-trzvl -- curl -vvv helloflex:5000/headers -H 'X-Flex-Env: bad'
# goes through to the httpbin container
# helloflex has the lua filter applied
```

[Here's a repo with a fully reproducible example.](https://github.com/vladfr/demo-istio-lua/blob/main/README.md) I'm using Istio 1.20 and Kind on K8s 1.27.
