### DISCUSSION TITLE
Enable MetadataExchangeHeaders for IN_MESH traffic

### DISCUSSION THREAD

**Discussion by nikhilbarar** [istio/istio#49318] [Q&A]
Hi,

I'm trying to identify a way to get the context of the calling service as a request header. I came across [MetadataExchangeHeaders](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig-ProxyHeaders-MetadataExchangeHeaders) which adds some base64 encoded metadata headers. However, the default behavior is unspecified.

To try this out, I tried changing this configuration locally to IN_MESH by installing istio using the below command.

`istioctl install --set meshConfig.defaultConfig.proxyHeaders.metadataExchangeHeaders.mode=IN_MESH --set profile=demo`

However, when I checked the incoming headers using the httpbin service, I couldn't see any metadata exchange headers (just the default X-Envoy-Attempt-Count was there).

I also tried installing istio by specifying a custom configuration using the below command. But, I still saw the same results.

```
cat <<EOF > ./my-config.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    defaultConfig:
      proxyHeaders:
        metadataExchangeHeaders:
          mode: IN_MESH
EOF

istioctl install --set profile=demo -f my-config.yaml
```

I'm using Istio 1.20.3. Is there anything else I'm missing to generate the metadata exchange headers?
