### DISCUSSION TITLE
Can not apply EnvoyFilter to specific domain

### DISCUSSION THREAD

**Discussion by volkorny** [istio/istio#49324] [General]
Hello Istio Community,
I am seeking assistance in configuring Istio to apply a 'max_request_bytes' limit to a specific domain. Currently, I have successfully implemented this configuration for all Mesh without limiting it to a specific domain using the following YAML:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: max-request-bytes-gateway
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingress-private-gateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.buffer
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.buffer.v3.Buffer
          max_request_bytes: 67108901
```
However, when attempting to limit the scope to a specific domain using the following match configuration:
```    
    match:
      context: GATEWAY
      listener:
        filterChain:
          sni: app.example.com
          filter:
            name: "envoy.filters.network.http_connection_manager"
```
Istio does not apply this filter as expected. Surprisingly, there are no error messages in the Istiod log to indicate what might be wrong.

Could someone please assist me in understanding what might be incorrect with this match configuration? Your insights would be greatly appreciated.

Thank you in advance for your help.

Istio version: 1.20.2

Sincerely,
Volodymyr
