### DISCUSSION TITLE
TLS setup for Istio Ingress Gateway

### DISCUSSION THREAD

**Discussion by rameshrepo** [istio/istio#49341] [Q&A]
Want to enable TLS for Istio Ingress Gateway. The Services (RabbitMq and Redis) behind the gateway will run in Non-TLS
Only the connection from outside to Istio Ingress Gateway to be TLS

Created the Self Signed Certificates using the below OpenSSL Commands
```
openssl req -x509 -sha256 -nodes -days 30 -newkey rsa:2048 -subj '/O=rootca Inc./CN=MYCA' -keyout rootca.key -out rootca.crt
openssl req -out redis.csr -newkey rsa:2048 -nodes -keyout redis.key -subj "/CN=redis.com/O=redis app"
openssl x509 -req -days 30 -CA rootca.crt -CAkey rootca.key -set_serial 0 -in redis.csr -out redis.crt
openssl req -out rabbitmq.csr -newkey rsa:2048 -nodes -keyout rabbitmq.key -subj "/CN=rabbitmq.com/O=rabbitmq app"
openssl x509 -req -days 30 -CA rootca.crt -CAkey rootca.key -set_serial 0 -in rabbitmq.csr -out rabbitmq.crt
```
Created the below secrets
```
kubectl create -n istio-system secret tls redis-secret --key=redis.key --cert=redis.crt
kubectl create -n istio-system secret tls rabbitmq-secret --key=rabbitmq.key --cert=rabbitmq.crt_
```

Not sure why TLS is not working.  I get error when trying to connect to RabbitMQ using Java
org.springframework.amqp.AmqpIOException: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake

Note: Non-TLS Gateway is working fine. In the below manifest, if I change TLS to TCP and remove the TLS credential. Then, able to reach the Service (RabbitMQ and Redis) via the Istio Ingress Gateway.

Kindly help. 

Used the below Manifest to create the Gateway and Virtual Services 
```
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      number: 80
      name: tls-amqp
      protocol: TLS
    tls:
      credentialName: rabbitmq-secret
    hosts:
      - rabbitmq.com
  - port:
      number: 443
      name: tls
      protocol: TLS
    tls:
      credentialName: redis-secret
    hosts:
      - redis.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: redis-virtual-service
spec:
  hosts:
  - redis.com
  gateways:
  - my-gateway
  tcp:
  - match:
    - port: 443
    route:
    - destination:
        host: my-redis.appns.svc.cluster.local
        port:
          number: 6379
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rabbitmq-virtual-service
spec:
  hosts:
  - rabbitmq.com
  gateways:
  - my-gateway
  tcp:
  - match:
    - port: 80
    route:
    - destination:
        host: my-rabbitmq.appns.svc.cluster.local
        port:
          number: 5672
```

**Comment by husnialhamdani** [comment]
Try to set the TLS mode to SIMPLE, like in this example https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/#configure-a-tls-ingress-gateway-for-a-single-host

**Reply by rameshrepo** [reply]
Thanks for your suggestion. I tried with the TLS mode as SIMPLE. Still, the same issue

```
    tls:
      mode: SIMPLE
      credentialName: redis-secret
```

**Comment by xyphanajay** [comment]
You can try to directly parse the certificate in gateway
```
tls:
  mode: SIMPLE
  serverCertificate: |
  privateKey: |
```
