### DISCUSSION TITLE
Istio sidecar-to-sidecar communication

### DISCUSSION THREAD

**Discussion by wmashal** [istio/istio#49358] [Q&A] [answered]
Hi

In our specific scenario, the setup is somewhat unique. we have a server pod and several client pods that connect to it. When a client pod makes a call to the upstream server pod, we need to verify the certificate subject within the server pod to enforce additional security policies. My goal is to append the client certificate to the outbound request header or if i can  , specifically the x-forwarded-client-cert header.

What I have attempted so far involves deploying the ‘sleep’ sample from the Istio samples into the ‘sleep’ namespace. Following that, I deployed an echo server in the ‘echo’ namespace. To incorporate the certificate into the request header, I applied an Envoy filter to the ‘sleep’ pod.

When I View the root certificate mounted by the Envoy proxy then decrypt it I note that the issuer is cluster.local ?? is that right ?

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            48:cb:97:10:e1:c5:46:cb:79:5b:d2:23:17:a8:15:a7
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: O = cluster.local
        Validity
            Not Before: Feb 12 09:40:17 2024 GMT
            Not After : Feb  9 09:40:17 2034 GMT
        Subject: O = cluster.local
        Subject Public Key Info:
```

Please Advice ??

**My Envoy Filter** 
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: xfcc-forward
  namespace: sleep
spec:
  workloadSelector:
    labels:
      app: sleep
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_OUTBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.lua
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
            inlineCode: |
              function envoy_on_request(request_handle)
                  request_handle:logInfo("Lua filter invoked")
                  local connection = request_handle:streamInfo():downstreamSslConnection()
                  if connection then
                    local xfcc_header_value = connection:subjectPeerCertificate()
                    if xfcc_header_value then
                      request_handle:headers():add("x-forwarded-client-cert", xfcc_header_value)
                      request_handle:logInfo("XFCC header added")
                    else
                      request_handle:logInfo("No peer certificate found")
                    end
                  else
                    request_handle:logInfo("No TLS connection")
                  end
                end
```
**Echo Server**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - image: ealen/echo-server:latest
        imagePullPolicy: IfNotPresent
        name: echoserver
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: echo
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app: echoserver
```
**Sleep Pod** 

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sleep
---
apiVersion: v1
kind: Service
metadata:
  name: sleep
  labels:
    app: sleep
    service: sleep
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: sleep
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      terminationGracePeriodSeconds: 0
      serviceAccountName: sleep
      containers:
      - name: sleep
        image: curlimages/curl
        command: ["/bin/sleep", "infinity"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /etc/sleep/tls
          name: secret-volume
      volumes:
      - name: secret-volume
        secret:
          secretName: sleep-secret
          optional: true
```

I test the communication using the following 
```

kubectl exec "$(kubectl get pod -l app=sleep -n sleep -o jsonpath={.items..metadata.name})" -c sleep -n sleep -- curl http://echoserver.echo/ -v | jq .
```

**The echo response** 

```

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Host echoserver.echo:80 was resolved.
* IPv6: (none)
* IPv4: 10.147.95.254
*   Trying 10.147.95.254:80...
* Connected to echoserver.echo (10.147.95.254) port 80
> GET / HTTP/1.1
> Host: echoserver.echo
> User-Agent: curl/8.6.0
> Accept: */*
>
< HTTP/1.1 200 OK
< content-type: application/json; charset=utf-8
< content-length: 1669
< etag: W/"685-Vi2/cxk8Zuq1RrkP0IDFhRQ5y5A"
< date: Wed, 14 Feb 2024 14:30:23 GMT
< x-envoy-upstream-service-time: 3
< server: sap-atom-unified-services
<
{ [1669 bytes data]
100  1669  100  1669    0     0   232k      0 --:--:-- --:--:-- --:--:--  271k
* Connection #0 to host echoserver.echo left intact
{
  "host": {
    "hostname": "echoserver.echo",
    "ip": "::ffff:127.0.0.6",
    "ips": []
  },
  "http": {
    "method": "GET",
    "baseUrl": "",
    "originalUrl": "/",
    "protocol": "http"
  },
  "request": {
    "params": {
      "0": "/"
    },
    "query": {},
    "cookies": {},
    "body": {},
    "headers": {
      "host": "echoserver.echo",
      "user-agent": "curl/8.6.0",
      "accept": "*/*",
      "x-forwarded-for": "10.96.0.45,10.96.0.45",
      "x-forwarded-proto": "http",
      "x-request-id": "e6309f96-d8c3-9ca3-9a87-2cd453253e36",
      "x-envoy-attempt-count": "1",
      "x-envoy-external-address": "10.96.0.45",
      "x-forwarded-client-cert": "By=spiffe://cluster.local/ns/echo/sa/default;Hash=118988b4d10d558c25a1dc7974b82dc4d543ee33873c37d6bf580da0577cee2a;Subject=\"\";URI=spiffe://cluster.local/ns/sleep/sa/sleep",
      "x-b3-traceid": "17bfa83aa43b86d76e40b354e7c2bb5f",
      "x-b3-spanid": "75701d57a4f5d317",
      "x-b3-parentspanid": "6e40b354e7c2bb5f",
      "x-b3-sampled": "1"
    }
  },
  "environment": {
    "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
    "HOSTNAME": "echoserver-6d874b9bc-h6wch",
    "NODE_VERSION": "20.11.0",
    "YARN_VERSION": "1.22.19",
    "PORT": "80",
    "KUBERNETES_SERVICE_HOST": "api.i334513.atom-dev.internal.canary.k8s.ondemand.com",
    "ECHOSERVER_PORT_80_TCP_ADDR": "10.147.95.254",
    "KUBERNETES_PORT_443_TCP_PORT": "443",
    "KUBERNETES_PORT_443_TCP_ADDR": "10.147.0.1",
    "ECHOSERVER_PORT": "tcp://10.147.95.254:80",
    "ECHOSERVER_PORT_80_TCP_PROTO": "tcp",
    "KUBERNETES_SERVICE_PORT": "443",
    "KUBERNETES_PORT_443_TCP": "tcp://10.147.0.1:443",
    "ECHOSERVER_SERVICE_PORT": "80",
    "KUBERNETES_SERVICE_PORT_HTTPS": "443",
    "ECHOSERVER_PORT_80_TCP_PORT": "80",
    "ECHOSERVER_SERVICE_HOST": "10.147.95.254",
    "ECHOSERVER_PORT_80_TCP": "tcp://10.147.95.254:80",
    "KUBERNETES_PORT": "tcp://10.147.0.1:443",
    "KUBERNETES_PORT_443_TCP_PROTO": "tcp",
    "HOME": "/root"
  }
}
```
Thanks
