### DISCUSSION TITLE
Efficient or clean yaml for different method response headers

### DISCUSSION THREAD

**Discussion by timm088** [istio/istio#49369] [Q&A]
Hi All,

Given the below VirtualService, where i want to, for OPTIONS methods, attach a header to my response (for caching purposes), is there a cleaner or more efficient version of doing the below, where we dont have to have so much duplicaton? 

Have checked the docs, and I dont think so , but could be misunderstanding?

The outcome in mind is
* For request of OPTIONS method, to specific URIs, set a header
* For ALL other methods, just route the same URIs to the same destination

```
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: just-a-name
spec:
  gateways:
    - my-gateway
  hosts:
    - myapi-host
  http:
    - match:
        - uri:
            exact: /v1/route1
          method:
            exact: OPTIONS
        - uri:
            regex: \/v1\/route1\/.+$
          method:
            exact: OPTIONS
        - uri:
            exact: /v1/route2
          method:
            exact: OPTIONS
        - uri:
            exact: /v1/route3
          method:
            exact: OPTIONS
        - uri:
            regex: \/v[0-9]+\/route4\/.+$
          method:
            exact: OPTIONS
      route:
        - destination:
            host: destination.svc.cluster.local
          headers:
            response:
              set:
                Cache-Control: "public, max-age=86400"
    - match:
        - uri:
            exact: /v1/route1
        - uri:
            regex: \/v1\/route1\/.+$
        - uri:
            exact: /v1/route2
        - uri:
            exact: /v1/route3
        - uri:
            regex: \/v[0-9]+\/route4\/.+$
      route:
        - destination:
            host: destination.svc.cluster.local
```
