### DISCUSSION TITLE
telemetry logging provider has no envoy config generated

### DISCUSSION THREAD

**Discussion by 13567436138** [istio/istio#49420] [Q&A]
![image](https://github.com/istio/istio/assets/31508490/247f1222-2ff4-4f1c-8092-8481627ca10e)
```
root@istio-01-a:~# kubectl edit cm -n istio-system istio

    extensionProviders:
    - envoyOtelAls:
        port: 4317
        service: opentelemetry-collector.istio-system.svc.cluster.local
      name: otel
    - name: skywalking
      skywalking:
        port: 11800
        service: tracing.istio-system.svc.cluster.local
    - name: otel-tracing
      opentelemetry:
        port: 4317
        service: opentelemetry-collector.otel-collector.svc.cluster.local
    - name: my-fluentd-provider
      fluentd:
        port: 24231
        service: fluentd.istio.svc.cluster.local
```

```
kubectl apply -n istio -f - <<EOF
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: telemetry-productpage
spec:
  selector:
    matchLabels:
      app: productpage
  accessLogging:
  - providers:
    - name: my-fluentd-provider
    disabled: false
EOF
```
