### DISCUSSION TITLE
How implement EnvoyFilter with extensions.transport_sockets.tls.v3.CertificateValidationContext

### DISCUSSION THREAD

**Discussion by wmashal** [istio/istio#49422] [Q&A] [answered]
Hi 

Any one can give example how I can implement this envoy filter configurations in Istio sidecar  ? What I am trying to do when a pod in my cluster send a request to another pod with a client certificate I want to validate it with a trusted_ca using this envoy extension (extensions.transport_sockets.tls.v3.CertificateValidationContext)

[extensions.transport_sockets.tls.v3.CertificateValidationContext Docs](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto#extensions-transport-sockets-tls-v3-certificatevalidationcontext)

I tried with this but not working 

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: client-cert-validation
  namespace: sleep
spec:
  workloadSelector:
    labels:
      app: sleep
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_OUTBOUND
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
            common_tls_context:
             validation_context:
                trusted_ca:
                  filename: /etc/my-shared-secret/ca.crt
```

Thanks

**Comment by wmashal** [comment, marked as answer]
My working Envoy , I just a add the listener for the target VirtualService host and port then add the TLS termination part under tls_certificates

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: verify-add-client-cert-header
  namespace: sleep
spec:
  configPatches:
  - applyTo: FILTER_CHAIN
    match:
      context: SIDECAR_OUTBOUND
      listener:
        portNumber: 80
        filterChain:
          sni: "echoserver.echo"
    patch:
      operation: MERGE
      value:
       transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
            require_client_certificate: true
            common_tls_context:
              tls_certificates:
                - certificate_chain:
                    filename: /etc/client-cert/tls.crt
                  private_key:
                    filename: /etc/client-cert/tls.key
              validation_context:
                trusted_ca:
                  filename: /etc/ca-cert/ca.crt
  workloadSelector:
    labels:
      app: sleep
```
