### DISCUSSION TITLE
clientsidecar mode doesn't work in Istio performance benchmark tools

### DISCUSSION THREAD

**Discussion by xjtupdy** [istio/istio#49479] [Q&A] [answered]
I am using performance benchmark tools https://github.com/istio/tools.
I choose to test the performance in the clientsidecar mode in which traffic should pass through the sidecar of the fortio client, but not through the sidecar of the fortio server. But in fact traffic doesn't pass through both sidecars. I can't find any logs in istio-proxy of both pods. But other three modes(baseline, bothsidecar and serversidecar) work well, and I can find istio-proxy logs correctly. I'm confused, but can't find the cause of the problem.

the clientsidecar test command:
**python runner/runner.py --conn 1 --qps 1 --protocol_mode grpc --duration 93 --clientsidecar --load_gen_type=fortio --telemetry_mode=v2**

the url fortio client will request is as follows:
serversidecar mode:          10.53.158.144:8079
baseline mode:                 10.53.148.252:8076
bothsidecar mode:            fortioserver:8079
**clientsidecar mode:           fortioserver:8076**

The Deployment of fortio client and server is as follows:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fortioserver
  name: fortioserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortioserver
  template:
    metadata:
      annotations:
        sidecar.istio.io/interceptionMode: REDIRECT
        sidecar.istio.io/inject: "true"
        linkerd.io/inject: "disabled"
        # exclude inbound ports of the uncaptured container
        traffic.sidecar.istio.io/excludeInboundPorts: "8076,8077,8078,8081,9999"
        traffic.sidecar.istio.io/excludeOutboundPorts: "80,8076,8077,8078, 8081"
        sidecar.istio.io/proxyCPU: 100m
        sidecar.istio.io/proxyMemory: 128Mi
      labels:
        app: fortioserver
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - "fortioclient"
            topologyKey: "kubernetes.io/hostname"
      volumes:
      - name: shared-data
        emptyDir: {}
      containers:
      - name: captured
        securityContext:
          runAsUser: 1
        volumeMounts:
        - name: shared-data
          mountPath: /var/lib/fortio
        image:  fortio/fortio:latest_release
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8079
          protocol: TCP
        - containerPort: 8078
          protocol: TCP
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi
      - name: uncaptured
        securityContext:
          runAsUser: 1
        image: fortio/fortio:latest_release
        imagePullPolicy: IfNotPresent
        args:
        - server
        - -http-port
        - "8077"
        - -grpc-port
        - "8076"
        - -tcp-port
        - "8078"
        - -redirect-port
        - "8081"
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fortioclient
  name: fortioclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortioclient
  template:
    metadata:
      annotations:
        sidecar.istio.io/interceptionMode: REDIRECT
        sidecar.istio.io/inject: "true"
        linkerd.io/inject: "disabled"
        # exclude inbound ports of the uncaptured container
        traffic.sidecar.istio.io/excludeInboundPorts: "8076,8077,8078,8081,9999"
        traffic.sidecar.istio.io/excludeOutboundPorts: "80,8076,8077,8078, 8081"
        sidecar.istio.io/proxyCPU: 100m
        sidecar.istio.io/proxyMemory: 128Mi
      labels:
        app: fortioclient
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - "fortioserver"
            topologyKey: "kubernetes.io/hostname"
      volumes:
      - name: shared-data
        emptyDir: {}
      containers:
      - name: captured
        securityContext:
          runAsUser: 1
        volumeMounts:
        - name: shared-data
          mountPath: /var/lib/fortio
        image:  fortio/fortio:latest_release
        imagePullPolicy: IfNotPresent
        args:
        - report
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi
      - name: uncaptured
        securityContext:
          runAsUser: 1
        image: fortio/fortio:latest_release
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: shared-data
          mountPath: /var/lib/fortio
        args:
        - report
        - -http-port
        - "8077"
        - -grpc-port
        - "8076"
        - -redirect-port
        - "8081"
        - -tcp-port
        - "8078"
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi
---

```
