### DISCUSSION TITLE
Istio Gateways Pods use too much memory, how can i fine tune them for memory usage?

### DISCUSSION THREAD

**Discussion by samuel-esp** [istio/istio#49630] [Q&A]
Hi everyone,

I have a big cluster (500-1000 pods range) with the Istio control plane installed. Each namespace of this Cluster can choose to adopt Istio or not, if Istio is adopted inside a namespace the CI/CD automation takes care of deploying a dedicated Gateway bounded to an Ingress Gateway Pod and a Sidecar (with all the necessary RBACs)

This is the sidecar resource

```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: default
  namespace: mynamespace
spec:
  egress:
  - hosts:
    - "./*"
```

The Ingress Gateway template that is deployed is the same that can be generated with `Istioctl install` against the IstioOperator yaml containing only the Ingress Gateway set to true

Unfortunately the Sidecar resource doesn't apply to the proxy inside the Ingress Gateway as stated in the "Note" list of this doc (https://istio.io/latest/docs/reference/config/networking/sidecar/),. So, while the usage of memory for sidecar is low, I can't say the same thing for the Ingress Gateway pod. What I'm noticing is that each ingress gateway pod uses too much memory (More than 500Mi in most cases) even if the namespace contains 3/4 pods.

Can someone give me some advices to optimize the memory performance of the Ingress Gateway?
