### DISCUSSION TITLE
How to configure external access from NGINX proxy?

### DISCUSSION THREAD

**Discussion by vsfomin** [istio/istio#49658] [Q&A]
There is a kuber with istio that allows access to services via url https://k8s.example.com/<service_name>. This works, you can see config below.
One of the services is accessed via a third-party external nginx https://nginx.example.com, where the proxy_pass for this service is https://k8s.example.com. (or IP of k8s.example.com)
Do I need to tweak something on the istio side? Should the host nginx.example.com be specified somewhere? Because so far it doesn't work. The service should be available as curl -v https://nginx.example.com/my-service/rest/api/v1/calculation. At the moment the service is available and responds to https://k8s.example.com/my-service.
Traffic reaches ingress-gateway, 502 error is generated now. Any ideas?
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: my-service
  namespace: cnv-test
spec:
  host: my-service
  trafficPolicy:
    tls:
      credentialName: tls-certs-opaque-test-cnv-srv
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-service
  namespace: cnv-test
spec:
  gateways:
    - istio-ingress/cnv-ingress-gateway-https
  hosts:
    - k8s.example.com
  http:
    - match:
        - uri:
            prefix: /my-service
      name: my-service
      rewrite:
        uri: /
      route:
        - destination:
            host: my-service
            port:
              number: 8090
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cnv-ingress-gateway-https
  namespace: istio-ingress
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - k8s.example.com
      port:
        name: https-test
        number: 443
        protocol: HTTPS
      tls:
        credentialName: tls-certs-opaque-test-cnv-srv
        mode: SIMPLE```
        
 ```
 NGIXN configuration:
```
location  /my-service/ {
        proxy_set_header Host 'k8s.example.com';
        proxy_pass https://CnvKubernetesHttps;
    }
   upstream CnvKubernetesHttps {
    server 172.16.123.123:443;
}
 ```
