### DISCUSSION TITLE
Possible to override the source_workload label for a bare pod

### DISCUSSION THREAD

**Discussion by mikebell90** [istio/istio#49666] [Q&A]
This is a followup to https://github.com/istio/istio/discussions/49649

- We have a bare pod launched by teamcity
- it works pretty well
- in telemetry it had high cardinality as @howardjohn states in source_workload dimension. This equaled the pod name which is autoincremented by TC.
- I tried applying both the canonicalName (didn't matter, fine the service was "correct" anyway, but I hoped for a hidden override of source_workload being undocumented )
- I tried Telemetry API, both CLIENT_AND_SERVER and just CLIENT against ALL_METRICS
- I upserted the spec below, basically overriding to a constant

```
spec:
  selector:
    matchLabels:
      app: tc-mesh-agent
  metrics:
  - overrides:
    - disabled: false
      match:
        metric: ALL_METRICS
        # tried to use CLIENT_AND_SERVER but it didn't work any better, so narrow scope
        mode: CLIENT
      tagOverrides:
        source_workload:
          operation: UPSERT
          value: string('tc-mesh-agent')
    providers:
    - name: prometheus
```

This worked great except only for reporter="source". For the destination metadata it didn't seem possible to override what envoy thinks?
