### DISCUSSION TITLE
Can I do rewrite based on regex in VirtualService?

### DISCUSSION THREAD

**Discussion by vsfomin** [istio/istio#49720] [Q&A]
I need the following behavior:
k8s.example.com/some-random-name from the string takes the path and substitutes it into http.rewrite.authority as follows some-random-name.default.k8s.example.com. Obviously, **some-random-name** may be any name  :-)

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: entry-route
  namespace: default
spec:
  gateways:
  - istio-ingress/cnv-ingress-gateway-http
  hosts:
  - k8s.example.com
  http:
  - match:
    - uri:
        prefix: "/some-random-name"   (Take "some-random-name" there)
    rewrite:
      authority: some-random-name.default.k8s.example.com   (Put"some-random-name" before the  _.default.k8s.example.com_) 
    route:
      - destination:
          host: knative-local-gateway.istio-ingress.svc.cluster.local
          port:
            number: 80
        weight: 100
```
