### DISCUSSION TITLE
Help with setting external auth on ingress and namespace

### DISCUSSION THREAD

**Discussion by kozomonster** [istio/istio#49828] [Q&A]
Help with setting external auth on ingress and namespace

We have an issue with setting up AuthorizationPolicy.
Our case requires forwarding each request (from outside the cluster and inside the cluster) to an "authorizer" service.
Authorizer is a service deployed on the cluster, that communicates with grpc on port 9000.
All services reside in the same namespace - `apps-namespace`.

We were able to set the AuthorizationPolicy for the requests that come from outside, and it works very well:

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: authorizer
  namespace: istio-system
spec:
  action: CUSTOM
  provider:
    name: authorizer-grpc
  rules:
    - to:
        - operation:
            notHosts:
              - some-load-balancer.address.com
            notPaths:
              - /different_path/api/v*
              - /x-service*
              - /y-tracker-service*
              - /z-service*
              - /g-service*
              - /h-service*
              - /t-ms*
              - /jersey*
              - /api/v1/edge*
              - /api/v2/edge*
              - /api/v1/translations*
              - /api/v2/translations*
  selector:
    matchLabels:
      app: istio-ingressgateway
```

Issue has started when we started to use the internal DNS for some communication between services. 
When the request from service A goes to service B inside the cluster (using the http://b.namespace.svc.cluster etc), the policy is not applied, so it misses the token that authorizer app needs to add to it. 

We tried to apply a new policy to the services namespace, as in documentation:

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: authorizer-namespace
  namespace: apps-namespace
spec:
  action: CUSTOM
  provider:
    name: authorizer-grpc
  rules:
    - to:
        - operation:
            notHosts:
              - some-load-balancer.address.com
            notPaths:
              - /different_path/api/v*
              - /x-service*
              - /y-tracker-service*
              - /z-service*
              - /g-service*
              - /h-service*
              - /t-ms*
              - /jersey*
              - /api/v1/edge*
              - /api/v2/edge*
              - /api/v1/translations*
              - /api/v2/translations*
```

But it breaks Istio proxy. The requests are multiplied when send to authorizer, the notPaths do not work in this case. This happens for the services that are requesed first from outside and go through Ingres.
The internal calls between services seem to work.

The services use port 80m target 8080, http, the mTLS is strice on cluster. 

Can someone please advise us how we can achieve this authorizer setup to work properly?

We thought that the easiest solution would be to filter the requests with `from PA` condition in `authorizer-namespace` policy, but it is not possible in the CUSTOM version.
