### DISCUSSION TITLE
Help with Istio Internal Routing Configuration from external ingress controller

### DISCUSSION THREAD

**Discussion by assafsauer** [istio/istio#49860] [Q&A]
I'm working on setting up an environment where Kong manages the external ingress for my applications, while Istio handles internal service-to-service communication. My understanding is that in this setup, Istio's Ingress Gateway might not be needed. Please correct me if this assumption is incorrect.

For testing purposes, I've attempted to create a routing rule that redirects traffic from an external domain (managed by Kong and pointing to python1) to python2 internally within the cluster. However, I've encountered an issue where the routing rule only works when using service names directly, but not with the external domain.

```
Here's the configuration I've used:
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: python1-to-python2-routing
  namespace: python1
spec:
  hosts:
    - "python1.apps.source-lab.io"
  http:
    - match:
        - uri:
            prefix: "/"  # This matches all paths
      route:
        - destination:
            host: python2.python2.svc.cluster.local
            port:
              number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: python2-destination
  namespace: python2
spec:
  host: python2.python2.svc.cluster.local
  subsets:
  - name: v1
    labels:
      stacktic.io/app: python2
```

so this one being routed:
 kubectl run curlpod --image=curlimages/curl --restart=Never --rm -it -- curl http://python1.python1.svc.cluster.local/greeting
 
 this one failed:
 curl -ks https://python1.apps.source-lab.io/greeting  
 
 many thanks!
