### DISCUSSION TITLE
Shifting traffic with multi cluster on different network

### DISCUSSION THREAD

**Discussion by Byunk** [istio/istio#49904] [Q&A]
Hi I'm trying to shift traffic within single mesh with multi cluster on different network. So, I created a destination rule to define a set of subsets and a virtual service to grant 100 weight on cluster1.

But it doesn't work. A curl request from cluster2 to cluster1 cause 503 service unavailable error. Would you please give me help? 

```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: helloworld-per-cluster
spec:
  host: helloworld.sample.svc.cluster.local
  subsets:
  - name: cluster1
    labels:
      topology.istio.io/cluster: cluster1
  - name: cluster2
    labels:
      topology.istio.io/cluster: cluster2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helloworld
spec:
  hosts:
    - helloworld.sample.svc.cluster.local
  http:
  - route:
    - destination:
        host: helloworld.sample.svc.cluster.local
        subset: cluster1
      weight: 100
    - destination:
        host: helloworld.sample.svc.cluster.local
        subset: cluster2
      weight: 0
```
