### DISCUSSION TITLE
Using virtualservice for routes, need it to work inside and outside the mesh

### DISCUSSION THREAD

**Discussion by devonjones** [istio/istio#49920] [Q&A]
I have a frontend service that is served on /, and a backend api that handles every other path.  I have it working fine externally via the ingressgateway, but for the life of me I can't figure out how to expose the virtualservice internally.  For reasons, our testing infra *must* access the application from inside kube and does not have access to the external host.  How would I go about making it accessible via coredns on an address say like someservice.somenamespace?

I really don't want to have to run something like nginx internally to achieve the routing.

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  annotations:
    meta.helm.sh/release-name: somenamespace
    meta.helm.sh/release-namespace: somenamespace
  labels:
    app: someapp
    app.kubernetes.io/component: someservicename
  name: someservicename
  namespace: somenamespace
spec:
  exportTo:
  - .
  - istio-system
  gateways:
  - istio-system/public
  - mesh
  hosts:
  - external.somedomain.com
  http:
  - match:
    - uri:
        exact: /
    name: Frontend
    route:
    - destination:
        host: frontend.somenamespace
        port:
          number: 3000
  - name: Backend
    route:
    - destination:
        host: backend.somenamespace
        port:
          number: 3000
```

**Comment by devonjones** [comment]
My best guess fwiw is that I need a ServiceEntry, but I don't see any way to direct the ServiceEntry to the VirtualService.

**Reply by devonjones** [reply]
ok, more info on this, even with a ServiceEntry and 

```
  template:
    metadata:
      annotations:
        proxy.istio.io/config: |
          proxyMetadata:
            ISTIO_META_DNS_CAPTURE: "true"
            ISTIO_META_DNS_AUTO_ALLOCATE: "true"
```

added to the deployment, it still won't resolve the address I've added to the ServiceEntry

**Reply by abasitt** [reply]
the only reason you would need a serviceentry if you want to resolve the service within mesh as well, else you could rely on coredns/externaldns and it VS should still work. 
Still no luck ? this could be the exportto if the calling service is in a different ns.

**Reply by devonjones** [reply]
Yeah, I expressly need to be able to call this virtual service from inside the mesh.  This service is hit by a test framework that runs inside the cluster that simply put can't call the external address (It would take months of effort due to the implementation, and I would rather just run an nginx proxy as a sidecar to replace what the istio virtualservice is doing than fight with the product team to prioritize fixing the test framework if I can't get istio to work for me on this).  It needs mesh access to the service via the virtual service because of the routing that's done in the http match section.

So far the main problem is that I don't appear to be able to create a dns entry even via a serviceentry that containers in the mesh resolve.  The mesh is in general not using the istio dns overlay, but I added the appropriate annotations to make sure the pod does and still no luck.

**Reply by abasitt** [reply]
I installed default istio profile and trying just example helloworld. without having SE i am seeing below from sleep pod.

```
k exec deploy/sleep -it sh
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
~ $ 
~ $ curl helloworld.abasitt.tech
curl: (6) Could not resolve host: helloworld.abasitt.tech
```

After add the annotations you shared to the sleep pod and installing serviceentry. I can hit something at-least.
```
k exec deploy/sleep -it sh
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
~ $ curl helloworld.abasitt.tech
no healthy upstream~ $ 

{"request_id":"ec8cb68a-1062-9869-9972-aa156bde7795","user_agent":"curl/8.6.0","upstream_metadata":null,"duration":0,"upstream_local_adress":null,"upstream_cluster":"outbound|80||helloworld.abasitt.tech","start_time":"[2024-03-19T10:15:37.041Z]","repons_code_details":"no_healthy_upstream","cluster_metadata":{"services":[{"namespace":"default","host":"helloworld.abasitt.tech","name":"helloworld.abasitt.tech"}]},"route_name":"default","reponse_flags":"UH","failure_reason":null,"forwarded_for":null,"reponse_code":503,"requested_server_name":null,"method":"GET","bytes_received":"0 19","authority":"helloworld.abasitt.tech","host":null,"envoy_upstream_service_time":null,"downstream_remote_address":"10.244.2.4:33826","protocol":"HTTP/1.1","downstream_local_address":"240.240.80.191:80","path":"/"}
```
the example SE
```

apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: helloworld-service-entry
spec:
  hosts:
  - "helloworld.abasitt.tech"
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
  location: MESH_INTERNAL
```
and to make sure it's pushed correctly.
```
stioctl pc c sleep-7dbdd9b7c8-v4frl.default | grep abasitt
helloworld.abasitt.tech                                 80        -          outbound      STRICT_DNS   
```

****************************
I created a below example VS that will use SE host.
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: helloworld-virtual-service
spec:
  hosts:
  - "helloworld.abasitt.tech"
  gateways:
  - mesh
  http:
  - match:
    - uri:
        exact: /hello
    route:
    - destination:
        host: "helloworld.default.svc.cluster.local"
        port:
          number: 5000
```
and it works.
```
~ $ curl -v helloworld.abasitt.tech/hello
* Host helloworld.abasitt.tech:80 was resolved.
* IPv6: (none)
* IPv4: 240.240.80.191
*   Trying 240.240.80.191:80...
* Connected to helloworld.abasitt.tech (240.240.80.191) port 80
> GET /hello HTTP/1.1
> Host: helloworld.abasitt.tech
> User-Agent: curl/8.6.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< server: envoy
< date: Tue, 19 Mar 2024 10:25:52 GMT
< content-type: text/html; charset=utf-8
< content-length: 60
< x-envoy-upstream-service-time: 281
< 
Hello version: v2, instance: helloworld-v2-7dd7df5884-fblsn
* Connection #0 to host helloworld.abasitt.tech left intact
```

by looking at the address 240.x.x.x, you can tell its resolved by the istio-dns-proxy.

hope this helps.
