### DISCUSSION TITLE
How does the istio create a inbound listener in the case of multiple services

### DISCUSSION THREAD

**Discussion by ZPerling** [istio/istio#50017] [General]
I have a workload that has two associated services, the same port is in different services, and one portName starts with http and the other starts with tcp. I found that sidecar was finally built using tcp proxy inbound listener, I want to ask how istiod chooses service and how to decide which service to use to create inbound listener, thanks.

```yaml
# service1
spec:
  ports:
  - name: http-8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    service: a

# service2
spec:
  ports:
  - name: tcp-8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    service: a

# sidecar inbound listener
"name": "envoy.filters.network.tcp_proxy",
"typedConfig": {
    "@type": "type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy",
    "statPrefix": "inbound|8080||",
    "cluster": "inbound|8080||",
```
