### DISCUSSION TITLE
DestinationRule trafficPolicy loadBalancer question

### DISCUSSION THREAD

**Discussion by Dr-wgy** [istio/istio#50016] [Q&A]
if I don't  set DestinationRule trafficPolicy loadBalancer ,Does it have default loadBalancer config?

etc 

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
spec:
  host: xxxxxxxx
  subsets:
  - labels:
      version: v1
    name: v1
  trafficPolicy:
    connectionPool:
      http:
        idleTimeout: 50s
```
