### DISCUSSION TITLE
How to configure cache in Envoy Proxy SideCar

### DISCUSSION THREAD

**Discussion by Dharam7777** [istio/istio#50024] [General]
I tried implementing but its giving error Error : can't unmarshal Any nested proto [type.googleapis.com/envoy.extensions.filters.http.cache.v3.CacheConfig](http://type.googleapis.com/envoy.extensions.filters.http.cache.v3.CacheConfig)

``` yaml 
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: envoy-cache-filter
spec:
  workloadSelector:
    labels:
      app: productpage
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.cache
        typed_config:
              "@type": "type.googleapis.com/envoy.extensions.filters.http.cache.v3.CacheConfig"
              typed_config:
                "@type": "type.googleapis.com/envoy.extensions.http.cache.simple_http_cache.v3.SimpleHttpCacheConfig"
```
