### DISCUSSION TITLE
TCP 443 Gateway "response_code_details":"filter_chain_not_found"

### DISCUSSION THREAD

**Discussion by teimyBr** [istio/istio#50099] [Q&A]
Hi i want to get a 443 TCP Gateway over DNS. 

Reason is because the traffic comes from outside Kubernetes and there the Security guys prefere to have a 443 port. 

And this must be raw tcp traffic.

My Config: 

```
apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  ports:
  - name: helloworld
    port: 8080
    appProtocol: TCP
  selector:
    app: helloworld-service
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: helloworld-gateway
spec:
  selector:
    istio: ingress
  servers:
  - hosts:
    - "helloworld.service.clustername.corp"
    port:
      name: helloworld
      number: 443
      protocol: TCP
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: helloworld
spec:
  gateways:
  - helloworld-gateway
  hosts:
  - "helloworld.service.clustername.corp"
  tcp:
  - match:
    - port: 443
    route:
    - destination:
        host: helloworld
        port:
          number: 8080
```

When i then connect over helloworld.service.clustername.corp my istio ingress gives me 

"response_code_details":"filter_chain_not_found" 

Istio Version: 1.20.2

How i can get this to work ?
