### DISCUSSION TITLE
Admission webhook "validation.istio.io" does not allow underscore in FQDN, what's the workaround?

### DISCUSSION THREAD

**Discussion by edwardccg** [istio/istio#50106] [Q&A] [answered]
We have legacy SQL server which has underscore (_) in the FQDN, this is causing the Admission webhook "validation.istio.io" complaining about the configuration. I have tried to remove the underscore to test and its happy without underscore, so I believe the problem is on the underscore in FQDN in the ServiceEntry.

Is there anyway to bypass the validation and have istio accepting the FQDN for the ServiceEntry?

## Istio version

> client version: 1.20.3
> control plane version: 1.20.3
> data plane version: 1.20.3 (7 proxies)

## Error
> ServiceEntry/sample/sqlserver-db dry-run failed: admission webhook "validation.istio.io" denied the request: configuration is invalid: domain name "glb_d000.mydomain.net" invalid (label "glb_d000" invalid)

## Yaml

```yaml
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: sqlserver-db
  namespace: sample
spec:
  hosts:
    - "glb_d000.mydomain.net"
  addresses:
    - 10.0.0.0
  location: MESH_EXTERNAL
  exportTo:
    - "."
  ports:
    - name: tcp
      number: 23603
      protocol: TCP

```

### validateFQDN
https://github.com/istio/istio/blob/2f54c6a52a5c6661d5eb9bd2277aab77304fee45/pkg/config/validation/validation.go#L265-L270

### validateDNS1123Labels
https://github.com/istio/istio/blob/2f54c6a52a5c6661d5eb9bd2277aab77304fee45/pkg/config/validation/validation.go#L298-L314

### IsDNS1123Label
https://github.com/istio/istio/blob/2f54c6a52a5c6661d5eb9bd2277aab77304fee45/pkg/config/labels/instance.go#L111-L113

### dns1123LabelFmt does not contain _ here
https://github.com/istio/istio/blob/2f54c6a52a5c6661d5eb9bd2277aab77304fee45/pkg/config/labels/instance.go#L28-L49
