### DISCUSSION TITLE
How to configure Istio for gRPC over Websockets?

### DISCUSSION THREAD

**Discussion by dleeha** [istio/istio#50115] [Q&A]
We would like to direct traffic from the Browser to the Signal component of Ion Pion (webRTC).
From our limited understanding, a websocket is established between the Browser and the Signal, and subsequent interactions take place via gRPC over this websocket.

The setup is verified ok with Traefik ingress. ie. a Browser is able to reach the Signal service with HTTP code 101.

For this Istio setup, the Gateway is set for:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ucs-gateway
  namespace: ucs
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "ucs.external"
 ```
and the Virtual Service:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: signal-vs
  namespace: ucs
spec:
  hosts:
  - "signal.external"
  gateways:
  - ucs-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 5551
        host: signal.ucs
```
When accessing `signal.external`, HTTP error 503 is observed. The endpoint Signal service does not seem to be receiving the traffic as there's no logging registered at the service, nor at its Istio Proxy.
What is the recommended setup for gRPC over websocket connections?
How else can we debug?
