### DISCUSSION TITLE
Restrict Istio-proxy access logs to only capture errors (non-200 status codes) to reduce costs in Datadog

### DISCUSSION THREAD

**Discussion by yasithab** [istio/istio#50122] [Q&A] [answered]
Hello

I am running **Istio version 1.20.4** and need your support with the following use case.

I want to restrict **istio-proxy** access logs to only capture errors (non-200 status codes) to reduce costs in Datadog. I tried using EnvoyFilters without success. Can you provide guidance or suggestions based on your experience with this scenario?

Here's my IstioOperator configurations.

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    accessLogFile: "/dev/stdout"
    accessLogEncoding: JSON
  values:
    global:
      logging:
        level: "default:warn"
      proxy:
        logLevel: warning
        componentLogLevel: "misc:error"
```

Thank you very much in advance :)

Regards,
Yasitha
