### DISCUSSION TITLE
Loadbalancing to external VM

### DISCUSSION THREAD

**Discussion by vsfomin** [istio/istio#50348] [Q&A]
![image](https://github.com/istio/istio/assets/7394246/090e94e8-5df1-4422-bb49-5537a53c5069)

Could you please advise me how do I implement the tacub traffic balancing that is shown in the network diagram?
I need preprod-cnv-ui.example.com/axilink to balance two nodes that are outside the kubernetes cluster.
I currently have it configured as shown below, but I am catching a 503 error when trying to open preprod-cnv-ui.example.com/axilink 
I have http://cpre-cnv-app03.example.com/ and http://cpre-cnv-app03.example.com/ open correctly, uri /axilink on this servers open correctly too.

```
apiVersion: networking.istio.io/v1alpha3 
kind: ServiceEntry 
metadata: 
  name: cpre-cnv-server
  namespace: cnv-preprod
  hosts: 
  - axilink
  location: MESH_EXTERNAL 
  ports: 
  - number: 80 
    name: http
    protocol: HTTP
  resolution: DNS 
  endpoints: 
  - address: cpre-cnv-app03.example.com
    ports: 
      http: 80 
  - address: cpre-cnv-app04.example.com
    ports: 
      http: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: axilink-dr
  namespace: cnv-preprod
spec:
  host: axilink
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: conv-web
  namespace: cnv-preprod
spec:
  gateways:
    - istio-ingress/cnv-ingress-gateway-https-ui
  hosts:
    - preprod-cnv-ui.example.com
  http:
    - match:
        - uri:
            prefix: /axilink
      route:
        - destination:
            host: axilink
```
