### DISCUSSION TITLE
Read header in EnvoyFilter which was added in virtual service

### DISCUSSION THREAD

**Discussion by vjerci** [istio/istio#50386] [Q&A]
Bug Description
I have virtual service in which i add X-Custom-Header
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  generation: 1
  labels:
    app: grafana
  name: grafana-vsvc
spec:
  gateways:
  - mygateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /prefix/grafana
    rewrite:
      uri: /prefix/grafana
    route:
    - destination:
        host: grafana.prefix.svc.cluster.local
        port:
          number: 80
      headers:
        request:
          add:
            X-Custom-Header: customHeaderValue
```

However when i try to access that header in EnvoyFilter it doesn't appear to be there

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: jwt-to-teknoir-header-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      teknoir.org/activity-logs-enabled: "true"
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          portNumber: 8080
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_AFTER
        value:
          name: envoy.lua
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
            inlineCode: |
              function envoy_on_request(request_handle)
                request_handle:logDebug("Header is: " .. request_handle:headers():get("X-Custom-Header")
              end
```
Debug doesn't show header.

I am not sure if i am doing something wrong or if it is a bug?
