### DISCUSSION TITLE
istio - keep source ip (tcp service)

### DISCUSSION THREAD

**Discussion by mvrk69** [istio/istio#50457] [Q&A]
Hi,

I have a pod with rsyslog running as a central logging system, and i need that the logs that arrive at my rsyslog pod from external network arrive with the original source ip address, but i have not been able to make it work with istio.

I've set the ingressgateway service externalTrafficPolicy="Local" as explained all over the internet and in the istio docs.

rsyslog pod is running without sidecar injection, though i also tried with sidecar injection and still no correct source ip.

Example
I have a VM with ip 192.168.0.6 which is sending logs to my rsyslog pod service (syslog.apps.k8s.mydomain.com - 192.168.0.115) but the logs arrive with ip 10.32.80.13 which is the ip of the istio-ingressgateway

Relevant configs:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: istio-ingressgateway
    meta.helm.sh/release-namespace: istio-ingress
  labels:
    app: istio-ingressgateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istio-ingressgateway
    app.kubernetes.io/version: 1.21.1
    helm.sh/chart: gateway-1.21.1
    istio: ingressgateway
  name: istio-ingressgateway
  namespace: istio-ingress
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 172.16.18.88
  clusterIPs:
  - 172.16.18.88
  externalIPs:
  - 192.168.0.115
  externalTrafficPolicy: Local
  healthCheckNodePort: 31197
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: status-port
    nodePort: 32261
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: http2
    nodePort: 31036
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 30761
    port: 443
    protocol: TCP
    targetPort: 443
  - name: syslog
    nodePort: 30514
    port: 514
    protocol: TCP
    targetPort: 514
  - name: syslog-tls
    nodePort: 31514
    port: 6514
    protocol: TCP
    targetPort: 6514
  - name: mysql
    nodePort: 30306
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
```

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: services-gateway
  namespace: istio-ingress
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
    hosts:
    - "*"
  - port:
      number: 514
      name: syslog
      protocol: TCP
    hosts:
    - "*"
  - port:
      number: 6514
      name: syslog-tls
      protocol: TCP
    hosts:
    - "*"
  - port:
      number: 3306
      name: mysql
      protocol: TCP
    hosts:
    - "*"
```

```
apiVersion: v1
kind: Service
metadata:
  name: syslog
  namespace: syslog
spec:
  type: ClusterIP
  selector:
    app: syslog
  ports:
  - name: syslog
    port: 514
    protocol: TCP
    targetPort: 514
  - name: syslog-tls
    port: 6514
    protocol: TCP
    targetPort: 6514
```

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: syslog
  namespace: syslog
spec:
  hosts:
  - "syslog.apps.k8s.mydomain.com"
  gateways:
  - istio-ingress/services-gateway
  tcp:
  - match:
    - port: 514
    route:
    - destination:
        host: syslog
        port:
          number: 514
  - match:
    - port: 6514
    route:
    - destination:
        host: syslog
        port:
          number: 6514
```

Anyone as any idea what might be wrong?
