### DISCUSSION TITLE
How to set Envoy `--drain-time-s` more than 1h

### DISCUSSION THREAD

**Discussion by s-dwinter** [istio/istio#50477] [Q&A] [answered]
Istio sets the maximum duration to 1 hour, but I want to set it to 100 hours.
https://github.com/istio/istio/blob/c5463a0b9e381842049a2f2081f361affc2dd0a2/pkg/config/validation/validation.go#L71

I would like to know how to bypass the validation and set the duration to `100h`.

**Comment by ramaraochavali** [comment]
What is the use case you are trying to solve?

**Reply by s-dwinter** [reply]
Thank you reply! I'm testing a Blue/Green deployment for TCP Proxy using the manifests as follows.

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: tcp-bg-test
spec:
  gateways:
    - istio-ingressgateway
  hosts:
    - example.com
  tcp:
    - match:
        - port: 21935
      route:
        - destination:
            host: example.default.svc.cluster.local
            port:
              number: 11935
            subset: blue
          weight: 100
        - destination:
            host: example.default.svc.cluster.local
            port:
              number: 11935
            subset: green
          weight: 0
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: example
spec:
  host: example.default.svc.cluster.local
  subsets:
    - labels:
        version: blue
      name: blue
    - labels:
        version: green
      name: green
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
```

When I change the `weight` to switch between Blue and Green, The existing TCP connections, currently linked to Blue, are terminated. This behavior was unexpected as I hoped that updating the `weight` would not affect existing connections.
Upon further investigation, I found out that the `--drain-time-s` command line option in Envoy allows for setting the duration before existing connections are terminated. However, Istio has set the maximum limit to `1h`.
