### DISCUSSION TITLE
How to get istio to pull a JwksUri from an in-mesh source using an authorizationpolicy principle

### DISCUSSION THREAD

**Discussion by tculp** [istio/istio#50578] [Q&A]
I have a keycloak instance inside the mesh with an authorizationPolicy:
```
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: keycloak
  namespace: foo
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/istio-system/sa/istiod
```

and a requestAuthentication which pulls from this server internally:
```
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: request-authentication
  namespace: foo
spec:
  jwtRules:
  - issuer: foo-keycloak
    jwksUri: http://keycloak.foo:80/realms/bar/protocol/openid-connect/certs
  selector:
    matchLabels:
      app.kubernetes.io/name: bar
```

However, istiod fails to pull the public cert because it's blocked by the AuthorizationPolicy:
```
Failed to refresh JWT public key from "http://keycloak.foo:80/realms/bar/pr
otocol/openid-connect/certs": status 403, message "RBAC: access denied"
```

In the logs for the keycloak's envoy I can see that the istiod call trying to pull the cert doesn't have a principal populated, and so isn't using a cert.

If I switch the AuthenticationPolicy to allow internal traffic, it works:
```
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: keycloak
  namespace: foo
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        ipBlocks:
          - 10.0.0.0/8
```

However, this feels wrong. I feel like I should be able to use a principal, or in general that istiod should act like it's part of its own mesh. I've seen other issues about not being able to use STRICT MTLs mode for the JWKS source which seems related. Does anyone know of a smarter way of allowing istiod to pull the cert without overly exposing the keycloak instance?
