### DISCUSSION TITLE
mTLS Enable Issue

### DISCUSSION THREAD

**Discussion by RamazanBiyik77** [istio/istio#50764] [Q&A]
I installed istio with zero-config. So as i understand mTLS is enabled by default. So i though can reach from a service to another with https. I can see mTLS on kiali. But couldnt do it with simple curl command. Also my applications cant reach another with https://blabla

At below example i have my-first-app, my-first-app-isito-proxy and my-second-app and my-second-app-isito-proxy. 

When i try https call from my-first-app to my-second-app i got wrong version number error. (Cut on second hello (server hello))

When i try https call from my-first-app-isito-proxy  to my-second-app i got self-signed certificate error.

What am i doing or understand wrong?

FYI:  Istio envoy sidecar started successfully

My First App:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: test-purpose
  labels:
    app: my-first-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-first-app
  template:
    metadata:
      labels:
        app: my-first-app
        role: my-first-role
    spec:
      containers:
      - name: nginx
        image: public.ecr.aws/nginx/nginx:1.23
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-first-app
  namespace: test-purpose
  labels:
    app: my-first-app
spec:
  selector:
    app: my-first-app
  ports:
    - protocol: TCP
      name: app
      port: 443
      targetPort: 80
```

My Second App:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-second-deployment
  namespace: test-purpose
  labels:
    app: my-second-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-second-app
  template:
    metadata:
      labels:
        app: my-second-app
        role: my-second-role 
    spec:
      containers:
      - name: nginx
        image: public.ecr.aws/nginx/nginx:1.23
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-second-app
  namespace: test-purpose
  labels:
    app: my-second-app
spec:
  selector:
    app: my-second-app
  ports:
    - protocol: TCP
      name: app
      port: 443
      targetPort: 80

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-second-app
  namespace: test-purpose
  labels:
    environment: my-second-app
spec:
  hosts:
  - "my-second-app"
  - "my-second-app.test-purpose.svc.cluster.local"
  http:
  - route:
    - destination:
        host: "my-second-app"
        port:
          number: 443

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: my-second-app-destination-rule
  namespace: test-purpose
  labels:
    environment: my-second-app
spec:
  host: "my-second-app"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```

> k exec -it deployment/my-deployment -c istio-proxy -- /bin/bash
> curl https://my-second-app

Returns:

```
curl: (60) SSL certificate problem: self-signed certificate in certificate chain
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above
```
