### DISCUSSION TITLE
Ingress gateway istio mutual TLS from other pod

### DISCUSSION THREAD

**Discussion by hanstf** [istio/istio#50868] [Q&A]
Hello all, we are trying to create an ingress gateway that will be called by other pod in mesh with this flow:

cloudflared/cli pod -> istio mutual TLS to ingress gateway -> istio mutual TLS to other pods based on our routing

Our ingress gateway, cloudflared and other upstream pods are in the same namespace (non istio system).
We try to set up cloudflared/cli pod to call to port 8082 of ingress gateway and add virtual service + destination rule to redirect to port 443 with istio mutual.

our gateway service:
```
labels:
  app: ingressgateway
  istio: ingressgateway
service:
  type: ClusterIP
  ports:
    - name: https
      port: 443
    - name: http
      port: 8082
```

gateway CRD:
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: ingressgateway
  namespace: somenamespace
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: tls-ingress
        protocol: TLS
      hosts:
        - "portal2.example.com"
      tls:
        mode: ISTIO_MUTUAL
    - port:
        number: 8082
        name: http-ingress
        protocol: HTTP
      hosts:
        - "portal2.example.com"
```

ingress gw destination rule:
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: ingressgateway
  namespace: somenamespace
spec:
  host: ingressgateway.somenamespace.svc.cluster.local
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 443
        tls:
          mode: ISTIO_MUTUAL
          sni: portal2.example.com
```
virtual service from port 8082 from another pod:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: internal-ingressgateway
  namespace: somenamespace
spec:
  hosts:
    - "portal2.example.com"
  exportTo:
    - "."
  http:
    - match:
        - port: 8082
      route:
        - destination:
            host: ingressgateway.somenamespace.svc.cluster.local
            port:
              number: 443
```
virtual service from gateway to other pods:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: external-ingressgateway
  namespace: somenamespace
spec:
  exportTo:
    - "."
  hosts:
    - "portal2.example.com"
  gateways:
    - ingressgateway
  http:
    - route:
        - destination:
            host: main-service.somenamespace.svc.cluster.local
            port:
              number: 80
```
I also noticed that our ingress gateway only have 1 listener which is the HTTP 8082 but not the port 443.

when I try to call from cli pod and check from kiali it still go through the passThroughCluster instead istio mtls via port 443
```
curl  http://ingressgateway. somenamespace.svc.cluster.local:8082/api  -H 'Host: portal2.example.com'
```

our istio version is:
client version: 1.19.0
control plane version: 1.18.7
data plane version: 1.18.7 (62 proxies)

**Comment by zufardhiyaulhaq** [comment]
can you try using this object instead?

1. for gateway
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: portal2-example-com-gw
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: tls-ingress
        protocol: TLS
      hosts:
        - "portal2.example.com"
      tls:
        mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: portal2-example-com-vs
  namespace: istio-system
spec:
  hosts:
    - "portal2.example.com"
  gateways:
    - istio-system/portal2-example-com-gw
  http:
    - route:
        - destination:
            host: main-service.somenamespace.svc.cluster.local
            port:
              number: 80
```

2. create DNS portal2.example.com that pointing to ingress gateway

3. for mesh to force forwarding to gateway
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: portal2-example-com-se
  namespace: istio-system
spec:
  hosts:
  - portal2.example.com
  ports:
  - name: https
    number: 443
    protocol: HTTPS
  - name: http
    number: 8082
    protocol: HTTP
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: portal2-example-com-mesh-vs
  namespace: istio-system
spec:
  hosts:
    - "portal2.example.com"
  gateways:
    - mesh
  http:
  - name: mtls-route
    match:
    - gateways:
      - mesh
      port: 8082
    route:
    - destination:
        host: portal2.example.com
        subset: upgrade-mtls
        port:
          number: 443
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: portal2-example-com-mesh-dr
  namespace: istio-system
spec:
  host: portal2.example.com
  subsets:
  - name: upgrade-mtls
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
        sni: portal2.example.com
```
