### DISCUSSION TITLE
istiod can't automaticly push new generated route config to proxy

### DISCUSSION THREAD

**Discussion by kangmingfa** [istio/istio#50914] [Q&A]
When i apply a virtualservie config, which can generate Cluster and RouteConfig of envoy.
My question is that above new added routeConfig could automaticly push update to a proxy ? Or, should I actively send a discoveryRequest to fetch routeConfig for my proxy?  
```
apiVersion: v1
kind: Service
metadata:
  name: helloworld-d
  labels:
    app: helloworld-d
    version: v4
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: helloworld-d
    version: v4
```
Before I apply the above vs resource, I got 3 RDS resources , after I apply this file, I also got same 3 RDS resourecs.
![image](https://github.com/istio/istio/assets/39798612/27577978-0207-4476-a142-208cecd8f49b)

installed isito version is v1.21.1.

Thanks the help of everyone.
