### DISCUSSION TITLE
overlapping port is ignored without any error or warn log

### DISCUSSION THREAD

**Discussion by qazz92** [istio/istio#50949] [Q&A]
I don't know if this is a bug or intended behavior in istio.

For example, with a total of 2 workloads set up as shown below, a curl request to a.example.com results in the error **"error:0A00010B:SSL routines::wrong version number"**.

My prediction is that based on the host header of "init.example.com / a.example.com", init.example.com should output an error and a.example.com should output the normal value. Or at least output the error when trying to register the second gateway server.

However, if I request any host and the port is 443, I get the same error.

I realize this is my mistake. It was a typo.

However, I don't see any logs of this issue.

I was wondering if this is the intended behavior, or if istio doesn't leave any logs. 

```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: test-gateway
  namespace: default
spec:
  selector:
    app: example-gateway
    istio: ingressgateway
  servers:
    - hosts: ["init.example.com"]
      port:
        name: http-example
        number: 80
        protocol: HTTP
    - hosts: ["init.example.com"]
      port:
        name: https-example
        number: 443
        protocol: HTTP
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: test-gateway
  namespace: default
spec:
  selector:
    app: example-gateway
    istio: ingressgateway
  servers:
    - hosts: ["a.example.com"]
      port:
        name: http-a
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts: ["a.example.com"]
      port:
        name: https-a
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: "example-tls"
```
