### DISCUSSION TITLE
how to call ingress gateway from mesh

### DISCUSSION THREAD

**Discussion by hanstf** [istio/istio#50950] [Q&A] [answered]
Hi all is there any way for ingress gateway to be accessed via another pod in the mesh through istio mutual tls ? It seems that currently the traffic from another pod to ingress gateway always go through passthroughclusterh

**Comment by abasitt** [comment]
Hi Hans, Yes possible.
You can use the same example of egress-gateway [here ](https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/#perform-tls-origination-with-an-egress-gateway) and then route the traffic back to in-cluster service using VS.

**Reply by abasitt** [reply]
I saw your another post as well, let me know if you are still stuck and will try to create for you the working example of it.

**Reply by hanstf** [reply]
Hi thanks for the reference, I have tried to follow the "Perform TLS origination with an egress gateway" example, but it seems after it arrived to egress gateway, we getting "filter_chain_not_found" error and response_flags: "NR". This is my config:

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: cf-ingress
  namespace: ns
spec:
  exportTo:
    - "."
  hosts:
    - "portal2.example.com"
  gateways:
    - ingressgateway
    - mesh
  http:
    - name: main-3
      match:
        - port: 8082
          gateways:
            - mesh
      route:
        - destination:
            host: ingressgateway.ns.svc.cluster.local
            subset: upgrade-mtls
            port:
              number: 8082
    - name: portal-0
      match:
        - gateways:
            - ingressgateway
      route:
        - destination:
            host: main-service.ns.svc.cluster.local
            port:
              number: 80
```
gateway chart values:
```
    labels:
      app: ingressgateway
      istio: ingressgateway
    service:
      type: ClusterIP
      ports:
        - name: https
          port: 8082
```
gateway:
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: ingressgateway
  namespace: ns
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 8082
        name: tls-ingress
        protocol: HTTPS
      hosts:
        - "portal2.example.com"
      tls:
        mode: ISTIO_MUTUAL
```
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: ingressgateway
  namespace: ns
spec:
  host: ingressgateway.ns.svc.cluster.local
  subsets:
  - name: upgrade-mtls
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
        - port:
            number: 8082
          tls:
            mode: ISTIO_MUTUAL
            sni: "portal2.example.com"
```
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: ingressgateway
  namespace: ns
spec:
  exportTo:
    - '.'
  hosts:
    - "portal2.example.com"
  ports:
    - name: http
      number: 8082
      protocol: HTTP
  resolution: DNS
```
