### DISCUSSION TITLE
Istio Ambient Mesh enabled for ArgoCD HA

### DISCUSSION THREAD

**Discussion by Skoucail** [istio/istio#51033] [Q&A]
I'm trying to activate Istio Ambient mesh on the argocd namespace (containing a ArgoCD HA deployment).
Multiple functions of argocd stop working after activating ambient mesh.
Some functions start working again after deleting a few of the default installed network policies (argocd-redis-ha-proxy-network-policy, argocd-redis-ha-server-network-policy, argocd-repo-server-network-policy).

But even then the ztunnel pods are spamming errors
```
2024-05-14T12:38:46.654258Z     error   access  connection complete     src.addr=172.20.185.145:38726 src.workload=argocd-redis-ha-haproxy-6b4d989bc9-lrdpz src.namespace=argocd src.identity="spiffe://cluster.local/ns/argocd/sa/argocd-redis-ha-haproxy" dst.addr=172.20.131.223:15008 dst.hbone_addr=172.20.131.223:6379 dst.service=argocd-redis-ha-announce-0.argocd.svc.cluster.local dst.workload=argocd-redis-ha-server-0 dst.namespace=argocd dst.identity="spiffe://cluster.local/ns/argocd/sa/argocd-redis-ha" direction="outbound" bytes_sent=24 bytes_recv=644 duration="2001ms" error="io error: Connection reset by peer (os error 104)"
2024-05-14T12:38:47.015345Z     error   access  connection complete     src.addr=172.20.131.224:54455 src.workload=argocd-redis-ha-haproxy-6b4d989bc9-47p5w src.namespace=argocd src.identity="spiffe://cluster.local/ns/argocd/sa/argocd-redis-ha-haproxy" dst.addr=172.20.185.143:26379 dst.hbone_addr=172.20.185.143:26379 dst.service=argocd-redis-ha-announce-2.argocd.svc.cluster.local dst.workload=argocd-redis-ha-server-2 dst.namespace=argocd dst.identity="spiffe://cluster.local/ns/argocd/sa/argocd-redis-ha" direction="inbound" bytes_sent=97 bytes_recv=53 duration="1ms" error="io error: broken pipe"
```

Anyone has an experience / insight on how to run ArgoCD HA on Istio Ambient Mesh?

Edit 1:
The network policies:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: argocd-application-controller-network-policy
spec:
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - port: 8082
  podSelector:
    matchLabels:
      app.kubernetes.io/name: argocd-application-controller
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: argocd-applicationset-controller-network-policy
spec:
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - port: 7000
      protocol: TCP
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: argocd-applicationset-controller
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: argocd-dex-server-network-policy
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: argocd-server
    ports:
    - port: 5556
      protocol: TCP
    - port: 5557
      protocol: TCP
  - from:
    - namespaceSelector: {}
    ports:
    - port: 5558
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: argocd-dex-server
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/component: notifications-controller
    app.kubernetes.io/name: argocd-notifications-controller
    app.kubernetes.io/part-of: argocd
  name: argocd-notifications-controller-network-policy
spec:
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - port: 9001
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: argocd-notifications-controller
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: argocd-redis-ha-proxy-network-policy
spec:
  egress:
  - ports:
    - port: 6379
      protocol: TCP
    - port: 26379
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: argocd-redis-ha
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: argocd-server
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: argocd-repo-server
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: argocd-application-controller
    ports:
    - port: 6379
      protocol: TCP
    - port: 26379
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: argocd-redis-ha-haproxy
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: argocd-redis-ha-server-network-policy
spec:
  egress:
  - ports:
    - port: 6379
      protocol: TCP
    - port: 26379
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: argocd-redis-ha
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: argocd-redis-ha-haproxy
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: argocd-redis-ha
    ports:
    - port: 6379
      protocol: TCP
    - port: 26379
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: argocd-redis-ha
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: argocd-repo-server-network-policy
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: argocd-server
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: argocd-application-controller
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: argocd-notifications-controller
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: argocd-applicationset-controller
    ports:
    - port: 8081
      protocol: TCP
  - from:
    - namespaceSelector: {}
    ports:
    - port: 8084
  podSelector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: argocd-server-network-policy
spec:
  ingress:
  - {}
  podSelector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
  policyTypes:
  - Ingress
```

(Running Istio 1.22 on K3S v1.28.8+k3s1 with Calico CNI)
