### DISCUSSION TITLE
Adding label to an existing Istio metric

### DISCUSSION THREAD

**Discussion by mcancarevic** [istio/istio#51137] [Q&A]
I have the 'x-user-email' header and I want to add it to the existing istio_request_bytes_sum metric as a label (dimension) to be discovered by Prometheus.

Istio version is 1.21.1.

How should I make it?

**Comment by zirain** [comment]
https://istio.io/latest/docs/tasks/observability/metrics/telemetry-api/

**Comment by mcancarevic** [comment]
Thanks for your answer @zirain.

I already tried the following telemetry configuration
```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: custom-tags
  namespace: istio-system
spec:
  metrics:
    - overrides:
        - match:
            metric: REQUEST_SIZE
            mode: CLIENT
          tagOverrides:
            x_user_email:
              value: request.headers["x-user-email"] | "unknown"
        - match:
            metric: REQUEST_SIZE
            mode: SERVER
          tagOverrides:
            x_user_email:
              value: request.headers["x-user-email"] | "unknown"
      providers:
        - name: prometheus
```
but, I still cannot see the desired label x-user-email for the istio_request_bytes_sum metric.

My Prometheus scrape configuration looks like the following:
```
     - job_name: 'istiod'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - istio-system
        relabel_configs:
          - source_labels: [ __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name ]
            action: keep
            regex: istiod;http-monitoring

      - job_name: 'envoy-stats'
        metrics_path: /stats/prometheus
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [ __meta_kubernetes_pod_container_port_name ]
            action: keep
            regex: '.*-envoy-prom'
```

**Reply by zirain** [reply]
can you check out config_dump by `istioctl pc l <pod_name>.<pod_namespace> -o yaml`, and then check stats output with `istioctl x es <pod_name>.<pod_namespace> -o prom`

**Comment by mcancarevic** [comment]
I don't have Istio sidecars injected into pods. I only have Istio ingress gateway to point to my API pod and Istio virtualService to route the traffic.

Should I have enabled the injection?

I installed Istio using Helm. There's an istiod pod in the istio-system namespace, and istio-ingress controller in the istio-ingress namespace. Envoy filter and telemetry resources are residing in the istio-system namespace.

**Reply by zirain** [reply]
it does matter, If it contains sensitive information, you can share it to me on slack.

**Reply by zirain** [reply]
please change your configuration as following:
```yaml
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: custom-tags
  namespace: istio-system
spec:
  metrics:
    - overrides:
        - match:
            metric: REQUEST_COUNT
            mode: CLIENT
          tagOverrides:
            x_user_email:
              value: request.headers['x-user-email'] 
        - match:
            metric: REQUEST_COUNT
            mode: SERVER
          tagOverrides:
            x_user_email:
              value: request.headers['x-user-email'] 
      providers:
        - name: prometheus

```

**Reply by mcancarevic** [reply]
I've tried applying this telemetry, but I still cannot see a custom label.

This is my Istio Ingress Gateway:

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: [NAME]
  namespace: default
spec:
  selector:
    istio: ingress
  servers:
  - hosts:
    - [HOST]
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - [HOST]
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: [SECRET]
      mode: SIMPLE
```

The virtual service is like this:

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: [NAME]
  namespace: default
spec:
  gateways:
  - [GATEWAY_NAME]
  hosts:
  -[HOST]
  http:
  - match:
    - port: 80
    - port: 443
    - uri:
        prefix: /
      - uri:
        exact: /api/users
    . . .
    uris
    . . .
    route:
    - destination:
        host:[API]
        port:
          number: 4200
```

and this is the envoy filter to extract the email from the jwt and to add it as a x-user-email header.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: extract-email
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingress
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.lua
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
            inlineCode: |
              -- Load the JSON library
              package.path = package.path .. ";/var/lib/lua/?.lua"
              local json = require("json")
              -- Custom base64 decoding function
              local function base64_decode(input)
                  local b = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'

                  input = input:gsub('[^'..b..'=]', '')
                  return (input:gsub('.', function(x)
                      if (x == '=') then return '' end
                      local r, f = '', (b:find(x) - 1)
                      for i = 6, 1, -1 do r = r .. (f % 2 ^ i - f % 2 ^ (i - 1) > 0 and '1' or '0') end
                      return r;
                  end):gsub('%d%d%d?%d?%d?%d?%d?%d?', function(x)
                      if (#x ~= 8) then return '' end
                      local c = 0
                      for i = 1, 8 do c = c + (x:sub(i, i) == '1' and 2 ^ (8 - i) or 0) end
                      return string.char(c)
                  end))
              end

              -- Function to parse JWT payload as JSON
              local function parse_jwt_payload(payload)
                  local claims, err = json:decode(payload)
                  if not claims then
                      return nil, "Failed to parse JWT payload as JSON: " .. err
                  end
                  return claims
              end

              -- Function to extract email from JWT token payload
              local function extract_email_from_jwt(jwt_token)
                  -- Split the JWT token into its parts (header, payload, signature)
                  local parts = {}
                  for part in jwt_token:gmatch("[^.]+") do
                      table.insert(parts, part)
                  end

                  -- Check if the token has the expected format (three parts separated by dots)
                  if #parts ~= 3 then
                      return nil, "Invalid JWT token format"
                  end

                  -- Get the payload part (second part) and decode it from base64
                  local payload_base64 = parts[2]
                  local payload = base64_decode(payload_base64)

                  -- Print the decoded payload for inspection
                  -- print("Decoded JWT payload:", payload)

                  -- Parse the payload as a JSON-like object
                  local claims, err = parse_jwt_payload(payload)
                  if not claims then
                      return nil, err
                  end

                  -- Extract the email claim from the JWT claims object
                  local email = claims.email

                  -- Check if the email claim exists
                  if email then
                      return email
                  else
                      return nil, "Email address not found in JWT token"
                  end
              end

              -- Entry point for Envoy Lua filter
              function envoy_on_request(request_handle)
                  local authorization_header = request_handle:headers():get("Authorization")
                  if authorization_header then
                      local token = authorization_header:match("Bearer%s+(.+)")
                      if token then
                          local email, err = extract_email_from_jwt(token)
                          if email then
                              -- Add email address as a header
                              request_handle:headers():add("X-User-Email", email)
                              request_handle:headers():add("x-envoy-metadata-email", email)
                          else
                              request_handle:logWarn("Failed to extract email address from JWT token: " .. err)
                          end
                      end
                  end
              end
```

**Reply by zirain** [reply]
can you check the filter order? I guess the lua filter behind the `istio.stats` filter?

**Reply by mcancarevic** [reply]
```
istioctl pc l istio-ingress-bcdbf497b-wq26d -n istio-ingress -o yaml --port 80 | grep "istio.stats" -A 30
        - name: istio.stats
          typedConfig:
            '@type': type.googleapis.com/stats.PluginConfig
            disableHostHeaderFallback: true
        - name: envoy.filters.http.lua
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
            inlineCode: "-- Load the JSON library\npackage.path = package.path ..
              \";/var/lib/lua/?.lua\"\nlocal json = require(\"json\")\n-- Custom base64
              decoding function\nlocal function base64_decode(input)\n    local b
              = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'\n\n
              \   input = input:gsub('[^'..b..'=]', '')\n    return (input:gsub('.',
              function(x)\n        if (x == '=') then return '' end\n        local
              r, f = '', (b:find(x) - 1)\n        for i = 6, 1, -1 do r = r .. (f
              % 2 ^ i - f % 2 ^ (i - 1) > 0 and '1' or '0') end\n        return r;\n
              \   end):gsub('%d%d%d?%d?%d?%d?%d?%d?', function(x)\n        if (#x
              ~= 8) then return '' end\n        local c = 0\n        for i = 1, 8
              do c = c + (x:sub(i, i) == '1' and 2 ^ (8 - i) or 0) end\n        return
              string.char(c)\n    end))\nend\n\n-- Function to parse JWT payload as
              JSON\nlocal function parse_jwt_payload(payload)\n    local claims, err
              = json:decode(payload)\n    if not claims then\n        return nil,
              \"Failed to parse JWT payload as JSON: \" .. err\n    end\n    return
              claims\nend\n\n-- Function to extract email from JWT token payload\nlocal
              function extract_email_from_jwt(jwt_token)\n    -- Split the JWT token
              into its parts (header, payload, signature)\n    local parts = {}\n
              \   for part in jwt_token:gmatch(\"[^.]+\") do\n        table.insert(parts,
              part)\n    end\n\n    -- Check if the token has the expected format
              (three parts separated by dots)\n    if #parts ~= 3 then\n        return
              nil, \"Invalid JWT token format\"\n    end\n\n    -- Get the payload
              part (second part) and decode it from base64\n    local payload_base64
              = parts[2]\n    local payload = base64_decode(payload_base64)\n\n    --
```

**Reply by mcancarevic** [reply]
I've moved the lua script to put it before the istio.stats and it now looks like this:

```
istioctl pc l istio-ingress-f676985cf-rmmbq -n istio-ingress -o yaml --port 80 | grep "istio.stats" -A 30 -B 44
        - name: envoy.filters.http.lua
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
            inlineCode: "-- Load the JSON library\npackage.path = package.path ..
              \";/var/lib/lua/?.lua\"\nlocal json = require(\"json\")\n-- Custom base64
              decoding function\nlocal function base64_decode(input)\n    local b
              = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'\n\n
              \   input = input:gsub('[^'..b..'=]', '')\n    return (input:gsub('.',
              function(x)\n        if (x == '=') then return '' end\n        local
              r, f = '', (b:find(x) - 1)\n        for i = 6, 1, -1 do r = r .. (f
              % 2 ^ i - f % 2 ^ (i - 1) > 0 and '1' or '0') end\n        return r;\n
              \   end):gsub('%d%d%d?%d?%d?%d?%d?%d?', function(x)\n        if (#x
              ~= 8) then return '' end\n        local c = 0\n        for i = 1, 8
              do c = c + (x:sub(i, i) == '1' and 2 ^ (8 - i) or 0) end\n        return
              string.char(c)\n    end))\nend\n\n-- Function to parse JWT payload as
              JSON\nlocal function parse_jwt_payload(payload)\n    local claims, err
              = json:decode(payload)\n    if not claims then\n        return nil,
              \"Failed to parse JWT payload as JSON: \" .. err\n    end\n    return
              claims\nend\n\n-- Function to extract email from JWT token payload\nlocal
              function extract_email_from_jwt(jwt_token)\n    -- Split the JWT token
              into its parts (header, payload, signature)\n    local parts = {}\n
              \   for part in jwt_token:gmatch(\"[^.]+\") do\n        table.insert(parts,
              part)\n    end\n\n    -- Check if the token has the expected format
              (three parts separated by dots)\n    if #parts ~= 3 then\n        return
              nil, \"Invalid JWT token format\"\n    end\n\n    -- Get the payload
              part (second part) and decode it from base64\n    local payload_base64
              = parts[2]\n    local payload = base64_decode(payload_base64)\n\n    --
              Print the decoded payload for inspection\n    -- print(\"Decoded JWT
              payload:\", payload)\n\n    -- Parse the payload as a JSON-like object\n
              \   local claims, err = parse_jwt_payload(payload)\n    if not claims
              then\n        return nil, err\n    end\n  \n    -- Extract the email
              claim from the JWT claims object\n    local email = claims.email\n\n
              \   -- Check if the email claim exists\n    if email then\n        return
              email\n    else\n        return nil, \"Email address not found in JWT
              token\"\n    end\nend\n\n-- Entry point for Envoy Lua filter\nfunction
              envoy_on_request(request_handle)\n    local authorization_header = request_handle:headers():get(\"Authorization\")\n
              \   if authorization_header then\n        local token = authorization_header:match(\"Bearer%s+(.+)\")\n
              \       if token then\n            local email, err = extract_email_from_jwt(token)\n
              \           if email then\n                -- Add email address as a
              header\n                request_handle:headers():add(\"X-User-Email\",
              email)\n                request_handle:headers():add(\"x-envoy-metadata-email\",
              email)\n            else\n                request_handle:logWarn(\"Failed
              to extract email address from JWT token: \" .. err)\n            end\n
              \       end\n    end\nend\n"
        - name: istio.stats
          typedConfig:
            '@type': type.googleapis.com/stats.PluginConfig
            disableHostHeaderFallback: true
        - name: envoy.filters.http.router
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
        httpProtocolOptions: {}
        normalizePath: true
        pathWithEscapedSlashesAction: KEEP_UNCHANGED
        rds:
          configSource:
            ads: {}
            initialFetchTimeout: 0s
            resourceApiVersion: V3
          routeConfigName: http.80
        requestIdExtension:
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.request_id.uuid.v3.UuidRequestIdConfig
            useRequestIdForTraceSampling: true
        serverName: istio-envoy
        setCurrentClientCertDetails:
          cert: true
          dns: true
          subject: true
          uri: true
        statPrefix: outbound_0.0.0.0_80
        streamIdleTimeout: 0s
        tracing:
          clientSampling:
            value: 100
```

**Comment by mcancarevic** [comment]
I've managed to make it work by adding the label to all metrics with the following telemetry resource:

```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: custom-tags
  namespace: istio-system
spec:
  metrics:
  - providers:
    - name: prometheus
    overrides:
    - tagOverrides:
        x_user_email:
          value: request.headers['x-user-email']
```

Now, the x_user_email is shown in istio_request_bytes_sum and all other metrics!
