### DISCUSSION TITLE
Enable  authentication and authorization on traffic coming from  istio  external gateway  for a particular app.

### DISCUSSION THREAD

**Discussion by amitborole88** [istio/istio#51169] [Q&A]
Hi ,

In my cluster, I have public and private istio ingress gateway.  I want to set up authentication and authorization on traffic coming from  istio  external gateway  for a particular app. Other apps and traffic coming from internal gateway shopuld not be impacted.

I tried  setting up requestauthentication and authorization policy in root namespace istio-system and used selectors as istio: externalgateway and app: appname-XYZ.

However it does not work.

Please help me how to set it up.

ReqauthPolicy

```yaml
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  labels:
    app: deploy-test-sandbox-amit
    app_language: java
    appname: deploy-test-sandbox-amit
  name: deploy-test-sandbox-amit
  namespace: istio-system
spec:
  jwtRules:
  - forwardOriginalToken: true
    issuer: << issuer URL >>
    jwksUri: << jwksUri URL >>
  selector:
    matchLabels:
      appname: deploy-test-sandbox-amit
      istio: istio-ingressgateway-external


AuthorizationPolicy

apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  labels:
    app: deploy-test-sandbox-amit
    app_language: java
    appname: deploy-test-sandbox-amit
  name: deploy-test-sandbox-amit
  namespace: istio-system 
spec:
  action: ALLOW
  rules:
  - when:
    - key: request.auth.claims[iss]
      values:
      - << issuer URL >>
  - from:
    - source:
        namespaces:
        - istio-system
        - prometheus
        - kube-system
    to:
    - operation:
        paths:
        - /health
  - from:
    - source:
        requestPrincipals:
        - '*'
  selector:
    matchLabels:
      appname: deploy-test-sandbox-amit
      istio: istio-ingressgateway-external
```
