### DISCUSSION TITLE
rate limit with retry not working

### DISCUSSION THREAD

**Discussion by ogolan-ig** [istio/istio#51197] [Q&A]
hi, 

im trying to use an envoy filter and virtual service for local rate limiting and retry when rate limit is reached. 

rate limit works fine and returns status code 429 and headers x-local-rate-limit=true, x-envoy-ratelimited=true. 

but retry does not work.  i have a single pod that can handle 100 http requests in 15s or else the rate limit is reached. i try do retry 3 times with time out of 20s. i send the pod 200 requests at the same time. 100 of those failed with status 429. 

i was expecting retry to kick in and after 20s all requests to be succesful. but that does not happen

virtuervice code :
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: word2vec-api-v2-sentiment-model-2023-ingress
  namespace: stage
spec:
  gateways:
  - istio-system/ingressgateway
  - istio-system/ingressgateway-private
  hosts:
  - word2vecapiv2-sentiment-model-2023.stage.com
  http:
  - match:
    - uri:
        prefix: /
    retries:
      attempts: 3
      perTryTimeout: '20s'
      retryOn: 'connect-failure,refused-stream,unavailable,cancelled,resource-exhausted,retriable-status-codes,envoy-ratelimited,retriable-4xx,gateway-error,500,429'
    route:
    - destination:
        host: word2vec-api-v2-sentiment-model-2023-service.stage.svc.cluster.local
        port:
          number: 80

```

envvoy filter file: 

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-ratelimit
  namespace: stage
spec:
  workloadSelector:
    labels:
      app: word2vec-api-v2-sentiment-model-2023
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter
              token_bucket:
                max_tokens: 100
                tokens_per_fill: 100
                fill_interval: 15s
              filter_enabled:
                runtime_key: local_rate_limit_enabled
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              filter_enforced:
                runtime_key: local_rate_limit_enforced
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              response_headers_to_add:
                - append: false
                  header:
                    key: x-local-rate-limit
                    value: 'true'
                - append: false
                  header:
                    key: x-envoy-ratelimited
                    value: 'true'

```
