### DISCUSSION TITLE
Routing to a multi-tenant application with TCP service on same port

### DISCUSSION THREAD

**Discussion by chandanpjain** [istio/istio#51247] [General]
Hi everyone,

I'm seeking some assistance with configuring Istio for proper TCP traffic routing in a multi-tenant environment.

### Scenario:

- We have an ingress gateway (`default-gw` in `istio-ingress` namespace) receiving all external traffic.
- A single `Gateway` resource is configured to handle both `HTTP` and `TCP` traffic, routing them to corresponding `VirtualServices` based on hostname.
- Our cluster hosts multiple customer environments, each with a dedicated namespace (e.g., `cust-abc`, `cust-xyz`). Within each namespace resides a separate instance of the same application.
- `HTTP` traffic routes as expected to the desired service on the appropriate namespace based on the hostname.
- **The issue**: `TCP` traffic consistently routes to the first configured `VirtualService`, regardless of the target namespace hostname.

### Desired Behavior:

We aim to ensure `TCP` traffic gets routed to the intended pod within the selected namespace based on the hostname.

#### Gateway
```yaml
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: default-gw
  namespace: istio-ingress
spec:
  selector:
    istio:  ingressgateway
  servers:
  - hosts:
    - '*.ourcompany.com'
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - '*.ourcompany.com'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: le-ingress-crt-secret
      mode: SIMPLE
  - hosts:
    - '*.ourcompany.com'
    port:
      name: tcp-10000
      number: 10000
      protocol: TCP
```

#### VirtualServices in different namespaces
```yaml
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: cust-abc-vs
  namespace: cust-abc
spec:
  gateways:
  - istio-ingress/default-gw
  hosts:
  - cust-abc.ourcompany.com
  http:
  - name: web-route
    route:
    - destination:
        host: cust-abc-svc
        port:
          number: 8081
  tcp:
  - match:
    - port: 10100
    route:
    - destination:
        host: cust-abc-svc
        port:
          number: 4050

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: cust-xyz-vs
  namespace: cust-xyz
spec:
  gateways:
  - istio-ingress/default-gw
  hosts:
  - cust-xyz.ourcompany.com
  http:
  - name: web-route
    route:
    - destination:
        host: cust-xyz-svc
        port:
          number: 8081
  tcp:
  - match:
    - port: 10100
    route:
    - destination:
        host: cust-xyz-svc
        port:
          number: 4050
````

### Question:

What adjustments are necessary to achieve proper `TCP` traffic routing based on the target namespace hostname? Any insights or suggestions on the correct setup would be greatly appreciated.

Thanks,
