### DISCUSSION TITLE
How to properly publish a gRPC port.

### DISCUSSION THREAD

**Discussion by vsfomin** [istio/istio#51274] [Show and tell]
Am I correctly publishing gRPC port 10091, which will be further converted to a port that listens to applications (10901)?
In VirtualService, do I need to use http or tcp to describe the match and subsequent route? 
And how do I properly configure TLS in case of gRPC, if it should be there?

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: cnv-thanos-gateway
  namespace: istio-ingress
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - '*'
      port:
        name: thanos-grpc
        number: 10091
        protocol: GRPC
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: thanos-grpc
  namespace: monitoring
spec:
  gateways:
    - istio-ingress/cnv-thanos-gateway
  hosts:
    - prd-cnv-pmts.example.com
  http:
    - match:
        - port: 10091
      route:
        - destination:
            host: thanos
            port:
              number: 10091
---
apiVersion: v1
kind: Service
metadata:
  name: thanos
  namespace: monitoring
spec:
  ports:
    - name: sidecar-http
      protocol: TCP
      port: 10902
      targetPort: 10902
    - name: grpc
      protocol: TCP
      port: 10091
      targetPort: 10901
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: prometheus-thanos-sidecar
    app.kubernetes.io/name: prometheus
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: thanos
  namespace: monitoring
spec:
  host: thanos
  trafficPolicy:
    tls:
      credentialName: tls-certs-opaque-prd-cnv-pmts
      insecureSkipVerify: true
      mode: MUTUAL
```

If I try to check it the error has occured 
.\grpcurl.exe -insecure  prd-cnv-pmts.example.com:10091 grpc.health.v1.Health.Check
Failed to dial target host "prd-cnv-pmts.example.com:10091": tls: first record does not look like a TLS handshake
