### DISCUSSION TITLE
Single Network Multi Primary Ambient installation

### DISCUSSION THREAD

**Discussion by moore-nathan** [istio/istio#51463] [Q&A]
Currently trying to test out creating a single network Multi-Primary setup with Istio Ambient mode. Using version Istio version `1.22.0` and trying to do as much as possible in Helm. This is deployed into AWS EKS on kubernetes version `1.29`.
I currently got it working so that the ztunnel picks up the workloads from each cluster, but there is no balancing between the two clusters. When going through [verify-installation](https://istio.io/latest/docs/setup/install/multicluster/verify/) only the deployment inside the cluster is getting hit (e.g. in cluster1 only hitting helloworldv1). Was hoping someone could provide assistance as I've gone through all the troubleshooting guides with no luck.

Followed the [plugin-ca-cert](https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/) guide before installing so both clusters have a `cacerts` secret.  
After installing via Helm followed the commands in [enbale-endpoint-discovery](https://istio.io/latest/docs/setup/install/multicluster/multi-primary/#enable-endpoint-discovery) for adding in the cluster contexts.

`istioctl experimental ztunnel-config workloads` command
```
NAMESPACE    POD NAME               IP  NODE    WAYPOINT PROTOCOL
default      metrics-server-xyz     xx  xx      None     TCP
istio-system istiod-xyz             xx  xx      None     TCP
istio-system istiod-xyz             xx  xx      None     TCP
istio-system ztunnel-xyz            xx  xx      None     TCP
istio-system ztunnel-xyz            xx  xx      None     TCP
istio-system ztunnel-xyz            xx  xx      None     TCP
istio-system ztunnel-xyz            xx  xx      None     TCP
istio-system ztunnel-xyz            xx  xx      None     TCP
istio-system ztunnel-xyz            xx  xx      None     TCP
kube-system  coredns-xyz            xx  xx      None     TCP
kube-system  coredns-xyz            xx  xx      None     TCP
kube-system  coredns-xyz            xx  xx      None     TCP
kube-system  coredns-xyz            xx  xx      None     TCP
sample       helloworld-v1-xyz      xx  xx      None     HBONE
sample       helloworld-v2-xyz      xx  xx      None     HBONE
sample       sleep-xyz              xx  xx      None     HBONE
sample       sleep-xyz              xx  xx      None     HBONE
```

`Chart.yaml`
```yaml
---
apiVersion: v2
name: istio-ambient
version: 1.0.0
appVersion: 1.22.0
dependencies:
  - name: base
    alias: istio-base
    version: 1.22.0
    repository: https://istio-release.storage.googleapis.com/charts
  - name: istiod
    version: 1.22.0
    repository: https://istio-release.storage.googleapis.com/charts
  - name: cni
    version: 1.22.0
    repository: https://istio-release.storage.googleapis.com/charts
  - name: ztunnel
    version: 1.22.0
    repository: https://istio-release.storage.googleapis.com/charts

```

`values.yaml`
```yaml
global:
  variant: distroless

enable:
  istiod: true

# Overrides for the `istiod-remote` dep
istiod:
  profile: ambient
  global:
    externalIstiod: true
    meshid: nmoore-test-mesh
    network: network1

# Overrides for the `ztunnel` dep
ztunnel:
  profile: ambient

# Overrides for the `cni` dep
cni:
  profile: ambient

```

`values.cluster1.yaml`
```yaml
istiod:
  global:
    multiCluster:
      clusterName: test-multi-cluster-1

ztunnel:
  multiCluster:
    clusterName: test-multi-cluster-1
```

`values.cluster2.yaml`
```yaml
istiod:
  global:
    multiCluster:
      clusterName: test-multi-cluster-2

ztunnel:
  multiCluster:
    clusterName: test-multi-cluster-2
```
