### DISCUSSION TITLE
How to disable overload manager or global connection limit for health checks and prometheus listeners

### DISCUSSION THREAD

**Discussion by AleksanderBrzozowski** [istio/istio#51631] [General]
I am trying to use Envoy's [Overload manager](https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/overload_manager/overload_manager) feature and `overload.global_downstream_max_connections` (which is deprecated in 1.30 and moved to overload_manager), but I fail to disable it for prometheus and health check listeners.

What I found it that I can use [custom bootstrap config](https://github.com/istio/istio/blob/master/samples/custom-bootstrap/README.md) to set up overload manager and `global_downstream_max_connections`. Then, I would like to disable these features for prometheus and health check listeners, so that even when connections / requests are rejected, these doesn't happen to prometheus metrics and health check - meaning that metrics are still queryable, and health check returns "OK".

What I tried to do is using such EnvoyFilter:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: connection-limit
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: istio-ingressgateway
  priority: 50
  configPatches: 
    - applyTo: LISTENER # enable to all listeners
      match:
        context: GATEWAY
      patch:
        operation: MERGE
        value:
          ignore_global_conn_limit: true
```

However, this config is only applied to the "user" listeners, for example, when applied to Gateway, it is only applied to `8080` and `8443` listeners. My idea was to enable set `ignore_global_conn_limit` for all listeners, and then disable it for `8080` and `8443`.

Is there any other option to set it, so that `overload_manager` will ignore prometheus and health check ports?
