### DISCUSSION TITLE
How to bypass JWT authentication for internal services call in ISTIO

### DISCUSSION THREAD

**Discussion by miragir** [istio/istio#51700] [General]
We recently started using ISTIO and we use requestauthentication feature with JWT to verify all api calls for all external traffic. 
Below is the file: 
```
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: jwt-token
  namespace: <app namespace>
spec:
  jwtRules:
  - forwardOriginalToken: true
    fromHeaders:
    - name: Authorization
      prefix: 'Bearer '
    issuer: < issuer name >
    jwksUri: < address >
```
```
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-all
  namespace: <namespace>
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        requestPrincipals:
        - '*'
    to:
    - operation:
        methods:
        - POST
        - GET
        - DELETE
        - PUT
        - PATCH
        - OPTIONS
        paths:
        - '*'
    when:
    - key: request.auth.claims[iss]
      values:
      - < iss >
```
      
  This works perfectly for external traffic. However, we observed that our internal service calls fail with error: RBAC access denied. 
```
curl --location --request DELETE 'http://sample-service-service.<namespace>.svc.cluster.local:5000/bat/0da8fg0ahfj07ec0d33842a'
RBAC: access denied
```
We want to bypass this authentication for our internal services call. Any suggestions?
