### DISCUSSION TITLE
Trouble setting up Envoy IP Geolocation Filter

### DISCUSSION THREAD

**Discussion by skarasev** [istio/istio#51789] [Q&A] [answered]
As we are migrating from Nginx Ingress to Istio Gateway I stumbled on an issue with this filter: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/geoip_filter

I try to enable it this this EnvoyFilter:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: geoip
  namespace: istio-ingress
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.geoip
          typed_config:
            '@type': >-
               type.googleapis.com/envoy.extensions.filters.http.geoip.v3.Geoip
            provider:
              name: "envoy.geoip_providers.maxmind"
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.geoip_providers.maxmind.v3.MaxMindConfig
                common_provider_config:
                  geo_headers_to_add:
                    city: "x-geo-city"
                city_db_path: "/tmp/GeoLite2-City.mmdb"
  workloadSelector:
    labels:
      istio: ingress
```

The error I get in istio-proxy container in istio-ingress pod:

> warning	envoy config external/envoy/source/extensions/config_subscription/grpc/grpc_subscription_impl.cc:138	gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_443: Didn't find a registered implementation for 'envoy.filters.http.geoip' with type URL: 'envoy.extensions.filters.http.geoip.v3.Geoip'
> 0.0.0.0_80: Didn't find a registered implementation for 'envoy.filters.http.geoip' with type URL: 'envoy.extensions.filters.http.geoip.v3.Geoip'

I tried running envoy locally with this config and it works. So I assume the issue is somewhere in EnvoyFilter, maybe I am putting the config in the wrong section. But then I try to debug the envoy config with `curl localhost:15000/config_dump` I get this error:

> Failed to convert protobuf message to JSON string: INVALID_ARGUMENT: could not find @type 'type.googleapis.com/envoy.extensions.filters.http.geoip.v3.Geoip'

So I ask for suggestions on how to debug it further or just to point out some silly typo in my config
