### DISCUSSION TITLE
Need help understanding Waypoint proxy in ambient mode

### DISCUSSION THREAD

**Discussion by llTimKramer** [istio/istio#51827] [Q&A]
Hello,

I'm currently in the process of setting up Istio in ambient mode, and I'm encountering an issue with controlling outbound traffic that I don't quite understand.

Following the documentation, I've created a Waypoint proxy, a ServiceEntry, and a VirtualService:
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  labels:
    istio.io/waypoint-for: all
  name: outbound
  namespace: <NAMESPACE>
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - name: mesh
    port: 15008
    protocol: HBONE
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: google
  namespace: <NAMESPACE>
spec:
  hosts:
  - "www.google.de"
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: route-google
  namespace: <NAMESPACE>
spec:
  hosts:
  - "www.google.de"
  tls:
  - match:
    - port: 443
      sniHosts:
      - "www.google.de"
    route:
    - destination:
        host: "www.google.de"
        port:
          number: 443
```

Additionally, I've labeled the namespace using `kubectl label namespace <NAMESPACE> istio.io/use-waypoint=outbound` . However, when I attempt to curl from a test pod to https://www.google.de, I'm not seeing this traffic visualized in Kiali.

I suspect I may be overlooking something and would greatly appreciate your advice on this matter.

Thank you!

**Comment by howardjohn** [comment]
The ztunnel handles traffic at L4. So it can only see IP addresses. Google doesn't have a defined IP in the service, so it cannot match. 

What you can do is define one by putting an arbitrary IP under service entry spec.addresses. It doesn't have to be the real Google IP - can be anything since it's just used for matching. You will need the DNS proxy features as well though. 

In 1.23 we will have the above automated which is why we haven't really documented this egress use case much

**Reply by llTimKramer** [reply]
Thank you for your prompt response!

If I understand correctly, I deployed this Waypoint to handle Layer 7 matching without requiring specific IPs?

For context, I'm attempting to restrict all outbound traffic except for whitelisted URLs (mainly databases, employing TCP with DNS resolution and HTTPS to specific domains).

**Reply by howardjohn** [reply]
The problem is ztunnel needs to know which traffic to send to the waypoint. It cannot (currently - it's plausible we will in the future) send all traffic to the waypoint

**Reply by llTimKramer** [reply]
Thank you for the clarification!

Regarding the DNS proxy feature you mentioned, I have a question about activating it. I deployed Istio using Helm, and I'm unsure whether to configure the DNS proxy settings under `meshConfig` or `global.meshConfig` in the Helm values. Could you please advise on this?

**Reply by howardjohn** [reply]
Yopull want to set on ztunnel chart:

```
meshConfig:
  defaultConfig:
    proxyMetadata:
      ISTIO_META_DNS_CAPTURE: "true"
```

On cni:

```
cni:
  ambient:
    dnsCapture: true
```

**Reply by llTimKramer** [reply]
Hi,

Thank you for the provided values. I've implemented them and also updated the ServiceEntry configuration as follows:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: google
  namespace: <NAMESPACE>
spec:
  hosts:
  - "www.google.de"
  addresses:
  - 172.16.20.1
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: route-google
  namespace: <NAMESPACE>
spec:
  hosts:
  - "www.google.de"
  tls:
  - match:
    - port: 443
      sniHosts:
      - "www.google.de"
    route:
    - destination:
        host: "www.google.de"
        port:
          number: 443
```

Despite these changes, I observe the following entry in the ztunnel logs:
```
2024-07-03T14:32:56.304069Z    info    access    connection complete    src.addr=10.96.7.6:56994 src.workload="wordpress-sts-0" src.namespace="<NAMESPACE>" dst.addr=142.250.186.99:443 direction="outbound" bytes_sent=814 bytes_recv=26733 duration="147ms"
```

It seems that the entry is still not being matched, and I am unable to view it in Kiali.

Could you please assist me in resolving it?

Thank you!

**Reply by howardjohn** [reply]
That looks like you don't have the DNS proxy enabled. Else you would not see `142.250.186.99` as the dst.addr.

I tested this myself and it worked for me once I had the dns proxy enabled

**Reply by llTimKramer** [reply]
Ah understood thanks.

This are the helm values which are currently deployed: (Output generated with helm -n istio-sytem get all)
Istio-cni:
```yaml
NAME: istio-cni
LAST DEPLOYED: Wed Jul  3 19:13:16 2024
NAMESPACE: istio-system
STATUS: deployed
REVISION: 3
CHART: cni
VERSION: 1.22.2
APP_VERSION: 1.22.2
TEST SUITE: None
USER-SUPPLIED VALUES:
defaults:
  cni:
    affinity: {}
    ambient:
      configDir: ""
      dnsCapture: true
      enabled: true
    chained: true
    cniBinDir: ""
    cniConfDir: /etc/cni/net.d
    cniConfFileName: ""
    cniNetnsDir: null
    excludeNamespaces:
    - kube-system
    hub: ""
    image: install-cni
    logLevel: debug
    podAnnotations: {}
    provider: default
    pullPolicy: ""
    repair:
      brokenPodLabelKey: cni.istio.io/uninitialized
      brokenPodLabelValue: "true"
      deletePods: false
      enabled: true
      hub: ""
      initContainerName: istio-validation
      labelPods: false
      repairPods: true
      tag: ""
    resourceQuotas:
      enabled: false
      pods: 5000
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
    rollingMaxUnavailable: 1
    seccompProfile: {}
    tag: ""
    variant: ""
  global:
    defaultResources:
      requests:
        cpu: 100m
        memory: 100Mi
    hub: docker.io/istio
    imagePullPolicy: ""
    imagePullSecrets: []
    logAsJson: false
    logging:
      level: default:info,cni:info
    tag: 1.22.2
    variant: ""
  ownerName: ""
  revision: ""
profile: ambient

COMPUTED VALUES:
defaults:
  cni:
    affinity: {}
    ambient:
      configDir: ""
      dnsCapture: true
      enabled: true
```

Ztunnel:
```yaml
NAME: ztunnel
LAST DEPLOYED: Wed Jul  3 13:37:38 2024
NAMESPACE: istio-system
STATUS: deployed
REVISION: 2
CHART: ztunnel
VERSION: 1.22.2
APP_VERSION: 1.22.2
TEST SUITE: None
USER-SUPPLIED VALUES:
defaults:
  annotations: {}
  caAddress: ""
  env: {}
  hub: docker.io/istio
  image: ztunnel
  imagePullPolicy: ""
  imagePullSecrets: []
  istioNamespace: istio-system
  labels: {}
  logLevel: info
  meshConfig:
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
```

I'm able to see both deployments have the DNS Capture enabled? I guess I'm missing something?

**Reply by howardjohn** [reply]
hmm, one note is you will need to restart your application after changing the DNS config to take effect I think

**Reply by llTimKramer** [reply]
Edit:

After restarting the application I get a new error but the traffic is recognized and routed.

But now I see this error when I try to curl to google:
`curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.google.de:443`

Edit2:
Also if I create a service entry for a tcp connection to a external database, it also fails:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: postgres
  namespace: <NAMESPACE>
spec:
  hosts:
  - "<HOST>"
  addresses:
  - 240.0.0.2
  ports:
  - number: 5432
    name: tcp-postgres
    protocol: TCP
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: route-postgres
  namespace: <NAMESPACE>
spec:
  hosts:
  - "<HOST>"
  tcp:
  - match:
    - port: 5432
    route:
    - destination:
        host: "<HOST>"
        port:
          number: 5432
```

**Reply by llTimKramer** [reply]
Hi @howardjohn , sorry to bother you again, but could you help me identify where I might be going wrong?

**Reply by howardjohn** [reply]
Sorry was out for a few days. Hard to say without logs from ztunnel and the waypoint. 

I do note you change from TLS route to TCP. it worked fine for me with the original TLS config.

**Reply by llTimKramer** [reply]
Hi,

no issue, I appreciate your help!

To clarify, these are 2 different service entries and both fail.

For the service entry https-google, I see following log entry when I try to curl google.de:
```2024-07-05T15:50:16.880579Z    info    access    connection complete    src.addr=10.96.7.24:47600 src.workload="wordpress-sts-0" src.namespace="<NAMESPACE>" src.identity="spiffe://cluster.local/ns/<NAMESPACE>/sa/default" dst.addr=10.96.0.21:15008 dst.hbone_addr=240.0.0.1:443 dst.service="www.google.de" dst.workload="outbound-6c5d54b8dc-zjqh8" dst.namespace="<NAMESPACE> ││ " dst.identity="spiffe://cluster.local/ns/<NAMESPACE>/sa/outbound" direction="outbound" bytes_sent=517 bytes_recv=0 duration="34ms"```

But in the shell of the test Application I get from curl an TLS error:
`curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.google.de:443`

Then I also tried to make the service entry of the postgres database and this tcp service entry gets also routed by ztunnel but fails with a connection timeout.

How do I get the logs of the waypoint?

Thanks again for your help!

**Reply by howardjohn** [reply]
So zrtunnel is not failing, its sending to the waypoint and then failing there. So need to see the waypoint logs. `kubectl logs waypoint-....` (the waypoint pod name). Waypoint is just a normal pod

**Reply by llTimKramer** [reply]
Oh that is maybe my issue:

I don't see any pod for the waypoint, I deployed the waypoint with this:
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  labels:
    istio.io/waypoint-for: all
  name: outbound
  namespace: <NAMESPACE>
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - name: mesh
    port: 15008
    protocol: HBONE
```

**Reply by howardjohn** [reply]
Hmm, can you check thestatus on the Gateway? and see if there is a deployment maybe but no pod?

**Reply by llTimKramer** [reply]
Sure:

k get gateway outbound:
`outbound   istio-waypoint   10.65.106.34   True         3d21h`

k describe gateway outbound:
```yaml
Name:         outbound
Namespace:    <NAMESPACE>
Labels:       istio.io/waypoint-for=all
Annotations:  gateway.istio.io/controller-version: 5
API Version:  gateway.networking.k8s.io/v1
Kind:         Gateway
Metadata:
  Creation Timestamp:  2024-07-01T18:45:18Z
  Generation:          1
  Resource Version:    108865139
  UID:                 f5b95fc3-2956-4b55-b2a0-48efa12c44b8
Spec:
  Gateway Class Name:  istio-waypoint
  Listeners:
    Allowed Routes:
      Namespaces:
        From:  Same
    Name:      mesh
    Port:      15008
    Protocol:  HBONE
Status:
  Addresses:
    Type:   IPAddress
    Value:  10.65.106.34
  Conditions:
    Last Transition Time:  2024-07-01T18:45:18Z
    Message:               Resource accepted
    Observed Generation:   1
    Reason:                Accepted
    Status:                True
    Type:                  Accepted
    Last Transition Time:  2024-07-03T19:19:06Z
    Message:               Resource programmed, assigned to service(s) outbound.<NAMESPACE>.svc.cluster.local:15008
    Observed Generation:   1
    Reason:                Programmed
    Status:                True
    Type:                  Programmed
  Listeners:
    Attached Routes:  0
    Conditions:
      Last Transition Time:  2024-07-01T18:45:18Z
      Message:               No errors found
      Observed Generation:   1
      Reason:                Accepted
      Status:                True
      Type:                  Accepted
      Last Transition Time:  2024-07-01T18:45:18Z
      Message:               No errors found
      Observed Generation:   1
      Reason:                NoConflicts
      Status:                False
      Type:                  Conflicted
      Last Transition Time:  2024-07-01T18:45:18Z
      Message:               No errors found
      Observed Generation:   1
      Reason:                Programmed
      Status:                True
      Type:                  Programmed
      Last Transition Time:  2024-07-01T18:45:18Z
      Message:               No errors found
      Observed Generation:   1
      Reason:                ResolvedRefs
      Status:                True
      Type:                  ResolvedRefs
    Name:                    mesh
    Supported Kinds:
Events:  <none>
```

Also there is no deployment for a waypoint.
