### DISCUSSION TITLE
gRPC request how to get request body in envoyfilter

### DISCUSSION THREAD

**Discussion by emilyyujieli** [istio/istio#51933] [Q&A]
l try to create an envoyfilter to get request body. It works well when my request content-type is application/json.
```
request_handle:logErr(" --------Get request body ------------- ")
local body = request_handle:body()
local myBody = tostring(body:getBytes(0, body:length())) 
request_handle:logErr("request body:"..myBody)
```
However when l send a gRPC request to the service and the request content-type is application/grpc, l am not able to use the code above to get gRPC request body.

If there got any idea how can l get gRPC request body via request_handle:body() in envoyfilter?

Regards & thanks

**Comment by j2gg0s** [comment]
grpc based on http2, I think you should use [bodyChunk](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter#bodychunks) replace body

I add header&body to metadata, so i can access it in access_log, like this `request_body: "%DYNAMIC_METADATA(envoy.lua.log:request_body)%"` 


```lua
function envoy_on_request(handle)
  local headers = {}
  for k, v in pairs(handle:headers()) do
    headers[k] = v
  end
  handle:streamInfo():dynamicMetadata():set(
    "envoy.lua.log", "request_headers", headers)

  local md = handle:headers():get(":method")
  if md ~= "POST" and md ~= "PUT" then return end

  local n = 0
  local body = ""
  for chunk in handle:bodyChunks() do
    body = body..chunk:getBytes(0, chunk:length())
    n = n + chunk:length()
    if n > 10240 then break end
  end

  if n > 0 then
    if handle:headers():get("content-type") == "application/grpc" then
      handle:streamInfo():dynamicMetadata():set(
        "envoy.lua.log", "request_body", handle:base64Escape(body))
    else
      handle:streamInfo():dynamicMetadata():set(
        "envoy.lua.log", "request_body", body)
    end
  end

end

```

**Comment by emilyyujieli** [comment]
Hi @j2gg0s ，

Thank you for your reply.
As your suggestion. l modified my code below
```
              function envoy_on_request(request_handle)

              local n = 0
              local body = ""
              for chunk in request_handle:bodyChunks() do
                body = body..chunk:getBytes(0, chunk:length())
                n = n + chunk:length()
                if n > 10240 then break end
              end

              if n > 0 then
                if request_handle:headers():get("content-type") == "application/grpc" then
                  request_handle:streamInfo():dynamicMetadata():set(
                    "envoy.lua.log", "request_body", request_handle:base64Escape(body))
                    request_handle:logErr("--------test 2-------------")
                else
                  request_handle:streamInfo():dynamicMetadata():set(
                    "envoy.lua.log", "request_body", body)
                end
              end 
               request_handle:logErr(body)
               request_handle:logErr(request_body)
              end
```
Here is the log l can see
```
=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=���=��	thread=77
error	envoy lua external/envoy/source/extensions/filters/http/lua/lua_filter.cc:924	script log: [string "function envoy_on_request(request_handle)..."]:22: bad argument #1 to 'logErr' (string expected, got nil)	thread=77
requestBody: -
```

it seems the boy has been encoded and even l used bodychunk still not able to decode. And l also tried to see the request_body in access_log, but nothing return, it seems "request_body" is a nil value. Do you have idea how to decode this grpc request body?

**Comment by j2gg0s** [comment]
@emilyyujieli 

Try this, it's ok in my test cluster.
If you want to use it in a production environment, pay attention to the impact on latency and memory.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: log
  namespace: istio-system
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value:
        name: "envoy.lua.log-request-response"
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
          inlineCode: |
            
            function envoy_on_request(handle)
              local headers = {}
              for k, v in pairs(handle:headers()) do
                headers[k] = v
              end
              handle:streamInfo():dynamicMetadata():set(
                "envoy.lua.log", "request_headers", headers)
            
              local md = handle:headers():get(":method")
              if md ~= "POST" and md ~= "PUT" then return end
            
              local n = 0
              local body = ""
              for chunk in handle:bodyChunks() do
                body = body..chunk:getBytes(0, chunk:length())
                n = n + chunk:length()
                if n > 10240 then break end
              end
            
              if n > 0 then
                if handle:headers():get("content-type") == "application/grpc" then
                  handle:streamInfo():dynamicMetadata():set(
                    "envoy.lua.log", "request_body", handle:base64Escape(body))
                else
                  handle:streamInfo():dynamicMetadata():set(
                    "envoy.lua.log", "request_body", body)
                end
              end
            
            end
            
            function envoy_on_response(handle)
              local headers = {}
              for k, v in pairs(handle:headers()) do
                headers[k] = v
              end
              handle:streamInfo():dynamicMetadata():set(
                "envoy.lua.log", "response_headers", headers)
            
              local n = 0
              local body = ""
              for chunk in handle:bodyChunks() do
                body = body..chunk:getBytes(0, chunk:length())
                n = n + chunk:length()
                if n > 10240 then break end
              end
            
              if n > 0 then
                if handle:headers():get("content-type") == "application/grpc" then
                  handle:streamInfo():dynamicMetadata():set(
                    "envoy.lua.log", "response_body", handle:base64Escape(body))
                else
                  handle:streamInfo():dynamicMetadata():set(
                    "envoy.lua.log", "response_body", body)
                end
              end
            end
  - applyTo: NETWORK_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          accessLog:
          - name: envoy.access_loggers.debug
            filter:
              headerFilter:
                header:
                  name: ":path"
                  exact_match: "/healthz"
                  invert_match: true
            typedConfig:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: /dev/stdout
              logFormat:
                omit_empty_values: true
                jsonFormat:
                  start_time: "%START_TIME%"
                  bytes_received: "%BYTES_RECEIVED%"
                  bytes_sent: "%BYTES_SENT%"
                  protocol: "%PROTOCOL%"
                  response_code: "%RESPONSE_CODE%"
                  response_code_details: "%RESPONSE_CODE_DETAILS%"
                  connection_termination_details: "%CONNECTION_TERMINATION_DETAILS%"
                  duration: "%DURATION%"
                  response_flags: "%RESPONSE_FLAGS%"
                  route_name: "%ROUTE_NAME%"
                  grpc_status: "%GRPC_STATUS%"
                  path: "%REQ(:PATH)%"
                  method: "%REQ(:METHOD)%"
                  authority: "%REQ(:AUTHORITY)%"
                  downstream_host: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
                  upstream_host: "%UPSTREAM_HOST%"
                  upstream_cluster: "%UPSTREAM_CLUSTER%"
                  upstream_service_time: "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%"
                  upstream_transport_failure_reason: "%UPSTREAM_TRANSPORT_FAILURE_REASON%"
                  forwarded_for: "%REQ(X-Forwarded-For)%"
                  traceid: "%REQ(X-Request-Id)%"
                  version: "%REQ(Y-Ohai-Version)%"
                  request_headers: "%DYNAMIC_METADATA(envoy.lua.log:request_headers)%"
                  request_body: "%DYNAMIC_METADATA(envoy.lua.log:request_body)%"
                  response_headers: "%DYNAMIC_METADATA(envoy.lua.log:response_headers)%"
                  response_body: "%DYNAMIC_METADATA(envoy.lua.log:response_body)%"
                  level: info
                  mark: AccessLog
---

```
