### DISCUSSION TITLE
How to set serviceEntry for AWS Redis cluster by AWS endpoints

### DISCUSSION THREAD

**Discussion by zhihuizhang17** [istio/istio#51938] [Q&A]
I have an AWS Redis cluster which doesn't run over TLS and is outside of my Istio mesh. And I want to monitor metrics between my application and the Redis cluster, and set a circuit breaker for it later. My Redis cluster has 3 shards with 2 nodes each, with a cluster endpoint `my-redis.abc.clustercfg.use2.cache.amazonaws.com:6379`, and each node has its own endpoint, such as `my-redis-0001-001.abc.0001.use2.cache.amazonaws.com:6379`, `my-redis-0001-002.abc.0001.use2.cache.amazonaws.com:6379`.

To set a `ServiceEntry` for the AWS Redis cluster, I initially used the following method to retrieve IPs:
```bash
host my-redis.abc.clustercfg.use2.cache.amazonaws.com | grep " has address " | cut -d" " -f4
```
This yielded six IPs (`ip_1`, `ip_2`, ...).

First attempt follows as [Consuming External MongoDB Services](https://preliminary.istio.io/latest/blog/2018/egress-mongo/#egress-control-for-tls):
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: ccs-redis-cluster
spec:
  hosts:
  - my-redis.abc.clustercfg.use2.cache.amazonaws.com
  addresses:
  - "<ip_a>/20"
  - "<ip_b>/20"
  ports:
  - name: redis
    protocol: TCP
    number: 6379
  endpoints:
  - address: "<ip_1>"
  - address: "<ip_2>"
  - address: "<ip_3>"
  - address: "<ip_4>"
  - address: "<ip_5>"
  - address: "<ip_6>"
  exportTo:
  - "."
  resolution: STATIC
  location: MESH_EXTERNAL
```
This resulted in `MOVED <port> <ip>` errors with the Redis client.

Second attempt:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: ccs-redis-cluster
spec:
  hosts:
  - my-redis.abc.clustercfg.use2.cache.amazonaws.com
  addresses:
  - "<ip_1>"
  - "<ip_2>"
  - "<ip_3>"
  - "<ip_4>"
  - "<ip_5>"
  - "<ip_6>"
  ports:
  - name: redis
    protocol: TCP
    number: 6379
  exportTo:
  - "."
  resolution: NONE
  location: MESH_EXTERNAL
```
This worked, but I'm unsure if it's correct. Since using the second method, the metric `envoy.cluster.out_my_redis.abc.clustercfg.use2.cache.amazonaws.com_redis_6379.upstream_rq_total` stopped updating and remains at 0.

It seems my Redis client's requests are redirected in my first attempt? I tried to set a virtual service for every node of shards to avoid redirect requests, it failed too. I have to set `resolution` to `None`. Is that right? 

Additionally, is there a way to use AWS endpoints instead of IPs for the `ServiceEntry`? What about IPs change? I searched some issues, found some like this one: https://github.com/istio/istio/issues/34585, but it didn't help. Could anyone take a look at this issue?
