### DISCUSSION TITLE
Routing L4 Traffic Based on Host in Istio Gateway

### DISCUSSION THREAD

**Discussion by Demmyart** [istio/istio#51942] [Q&A]
Hi Istio Community,

I have set up my AWS Network Load Balancer (NLB) with two listeners: TLS and TCP. Additionally, I have configured two Istio gateways, one using the HTTP protocol and the other using the TCP protocol. I have L4 traffic coming to one of the gateway, and several Virtual Services route this traffic to Kubernetes services. However, I’ve encountered an issue where the hosts field in these Virtual Services is ignored because of L4 limitations.

Here’s my example setup for the Virtual Services:

```
hosts:
  - example-1.domain.com
gateways:
  - general-gateway
tcp:
  - match:
      - port: 80
    route:
      - destination:
          port: 10591
          host: example.svc.cluster.local"
-----
hosts:
  - example-2.domain.com
gateways:
  - general-gateway
tcp:
  - match:
      - port: 80
    route:
      - destination:
          port: 10592
          host: example.svc.cluster.local"
```

So, on the gateway, there is no route for my listener, and it just uses one of the Virtual Services. 
```
istioctl proxy-config listeners -n istio-ingress deploy/gateway            
ADDRESSES PORT  MATCH DESTINATION
0.0.0.0   80    ALL   Cluster: outbound|10591||example.example.svc.cluster.local
```
I want to use a single gateway and route traffic based on something. I came across the DNS proxy feature but am unsure if it’s suitable for my case. At least, it does not work with the same configuration of virtual services by simply enabling it. In the documentation, it says about ServiceEntries, how exactly should it work?

Is there a way to achieve my goal without creating separate ports?
