### DISCUSSION TITLE
EnvoyFilter for Preserve Header Case Istio, VirtualService  TLS, Causes "upstream connect error or disconnect/reset before headers. reset reason: protocol error"

### DISCUSSION THREAD

**Discussion by lfelicetti-softatnet** [istio/istio#51969] [Q&A]
Hello, 
 can anyone help me with a potential issue? I'm not an expert of Istio and Envoy, but i cannot find a solution for this scenario: 
We need to preserve header case in response, using a istio ingress gateway with SSL. 

**NO ERRORS when using HTTP without SSL using an Istio Gateway in plain HTTP**

Our sample application use:
- Istio
- IngressGateway with TLS
- VirtualService
- A Service linked to the deployment

Here details of istio version used:
- client version: 1.20.0
- control plane version: 1.21.1
- data plane version: 1.18.2 (21 proxies), 1.21.1 (2 proxies)

Installed with helm chart into a rancher RKE2. Version Detail:
kubectl version --short
Client Version: v1.27.3
Kustomize Version: v5.0.1
Server Version: v1.27.7+rke2r2

The istio was installed using the UX/UI of rancher to install istio system, without any customization. The Istio IngressGateway service was modified just for use a LoadBalancer instead of a ClusterIP

Everything works like a charm, but the issue start when i apply the EnvoyFilter Configuration to Preserve Header Casing

Here the configuations

```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-default-gateway
  namespace: istio-cfg
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*.mydomain.it'
    port:
      name: https-fivenet
      number: 443
      protocol: HTTPS
    tls:
      cipherSuites:
      - ECDHE-ECDSA-AES128-GCM-SHA256
      - ECDHE-RSA-AES128-GCM-SHA256
      - ECDHE-ECDSA-AES128-SHA
      - ECDHE-ECDSA-AES256-GCM-SHA384
      - ECDHE-RSA-AES256-GCM-SHA384
      - ECDHE-ECDSA-AES256-SHA
      - ECDHE-RSA-CHACHA20-POLY1305
      - ECDHE-ECDSA-CHACHA20-POLY1305
      credentialName: star-mydomain-crt
      maxProtocolVersion: TLSV1_3
      minProtocolVersion: TLSV1_2
      mode: SIMPLE
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
    service: httpbin
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8080
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      serviceAccountName: httpbin
      containers:
      - image: docker.io/kong/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        # Same as found in Dockerfile's CMD but using an unprivileged port
        command:
        - gunicorn
        - -b
        - 0.0.0.0:8080
        - httpbin:app
        - -k
        - gevent
        env:
        # Tells pipenv to use a writable directory instead of $HOME
        - name: WORKON_HOME
          value: /tmp
        ports:
        - containerPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - "httpbin.mydomain.it"
  gateways:
  - istio-cfg/istio-default-gateway
  http:
  - route:
    - destination:
        host: httpbin
        port:
          number: 8000        
``` 

Using these configuration i can use a curl and a web browser to put to URL https://httpbin.mydomain.it/anything and it works like a charm, but the response headers are all lowercase. 

Googling i've found a EnvoyFilter to apply for get the header unchanged. It works using a client like CURL or POSTMAN, but when i try to browse the site with a web browser i got the error:
***upstream connect error or disconnect/reset before headers. reset reason: protocol error***

Here is the filter i've applied into ***istio-system*** namespace:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: preserve-case-filter
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      context: ANY
    patch:
      operation: MERGE
      value:
        typed_extension_protocol_options:
          envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
            '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
            use_downstream_protocol_config:
              http_protocol_options:
                header_key_format:
                  stateful_formatter:
                    name: preserve_case
                    typed_config:
                      '@type': type.googleapis.com/envoy.extensions.http.header_formatters.preserve_case.v3.PreserveCaseFormatterConfig
  - applyTo: NETWORK_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          http_protocol_options:
            header_key_format:
              stateful_formatter:
                name: preserve_case
                typed_config:
                  '@type': type.googleapis.com/envoy.extensions.http.header_formatters.preserve_case.v3.PreserveCaseFormatterConfig          
``` 

Applying filters on SIDECAR_INBOUND / SIDECAR_OUTBOUND doesn't change anything.

Any help is appreciated.

Thanks in advance.
