### DISCUSSION TITLE
Problems with communication between two namespaces when mtls is activated

### DISCUSSION THREAD

**Discussion by avisaradir** [istio/istio#51992] [Q&A]
I have two services in different namespaces let's say team-a and team-b so how can I restrict that only services in team-a can access to services in team-b.

I have been following more than a few documentation files trying to figure out what is the problem but without any success.
I applied this authorization policy but I think the issue is on the side of namespace-a.

when Im running curl -v service.namespace.svc.cluster.local Im getting the following errors

```
without service entry:
* Request completely sent off
* Recv failure: Connection reset by peer
* Closing connection
curl: (56) Recv failure: Connection reset by peer
```

with this log in istio-proxy container
```
{
    "protocol": null,
    "duration": 0,
    "upstream_transport_failure_reason": null,
    "request_id": null,
    "response_code_details": null,
    "downstream_remote_address": "xx.xx.xx.xx:54000", #  this is the curl pods ip.
    "requested_server_name": null,
    "client_ip": null,
    "authority": null,
    "x_forwarded_for": null,
    "downstream_local_address": "172.20.123.123:3000", # this is the service ip
    "route_name": null,
    "upstream_cluster": "BlackHoleCluster",
    "start_time": "2024-07-10T13:24:25.147Z",
    "upstream_service_time": null,
    "method": null,
    "bytes_sent": 0,
    "response_flags": "UH",
    "user_agent": null,
    "response_code": 0,
    "upstream_host": null,
    "bytes_received": 0,
    "upstream_local_address": null,
    "path": null,
 }
```

with service entries applied on both namespaces I get the following error and not the first one above:
```
with service entry:
* Request completely sent off
< HTTP/1.1 403 Forbidden
< content-length: 19
< content-type: text/plain
< date: Wed, 10 Jul 2024 13:24:49 GMT
< server: istio-envoy
< x-envoy-decorator-operation: service.team-b.svc.cluster.local:3000/*
< 
* Connection #0 to host service.team-b.svc.cluster.local left intact

```

these are all the configurations I have:
```
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-namespace-communication-from-base-to-istio-system-ip
  namespace: istio-system
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            ipBlocks:
              - xx.xx.xx.xx/24
------------------------------------------------------------------------------------------------------------------------
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-namespace-communication-from-base-to-istio-system
  namespace: istio-system
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces:
              - fluent-bit
              - gatekeeper-system
              - istio-system
              - k8s-event-logger
              - keda
              - kube-node-lease
              - kube-public
              - kube-system
              - logstash
              - monitoring
              - velero
              - xray
------------------------------------------------------------------------------------------------------------------------
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: istio-system-sidecar
  namespace: istio-system
spec:
  egress:
    - hosts:
        - ./*
        - istio-system/*
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY
------------------------------------------------------------------------------------------------------------------------
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: istio-system-peer-namespace-communication
  namespace: istio-system
spec:
  mtls:
    mode: PERMISSIVE
------------------------------------------------------------------------------------------------------------------------
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-namespace-communication-from-b-to-a
  namespace: team-a
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces:
              - team-b
------------------------------------------------------------------------------------------------------------------------
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-namespace-communication-from-a-to-b
  namespace: team-b
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces:
              - team-a
------------------------------------------------------------------------------------------------------------------------
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-namespace-communication-from-b-to-b
  namespace: team-b
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces:
              - team-b
------------------------------------------------------------------------------------------------------------------------
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-namespace-communication-from-a-to-a
  namespace: team-a
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces:
              - team-a
------------------------------------------------------------------------------------------------------------------------
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: allow-service-entry-from-team-a-to-b
  namespace: team-a
spec:
  addresses: []
  hosts:
    - "*.team-b.svc.cluster.local"
  location: MESH_EXTERNAL
  ports:
    - name: http
      number: 3000
      protocol: TCP
  resolution: NONE
------------------------------------------------------------------------------------------------------------------------
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: allow-service-entry-from-team-b-to-a
  namespace: team-b
spec:
  addresses: []
  hosts:
    - "*.team-a.svc.cluster.local"
  location: MESH_EXTERNAL
  ports:
    - name: http
      number: 3000
      protocol: TCP
  resolution: NONE
```

**Comment by avisaradir** [comment]
with the authorization policy below internal communication in the namespace works fine

```
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-namespace-communication-from-a-to-a
  namespace: team-a
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces:
              - team-a
```
