### DISCUSSION TITLE
Problem with setting up the end-to-end security on EKS

### DISCUSSION THREAD

**Discussion by IS-lczyr** [istio/istio#52128] [Q&A]
Hello community

Istio version: 1.22

For one of my client I'm trying to setting up the end-to-end security setup. Here are the requirements:
- we don't want to use sidecars
- we should have one central Gateway and attach VirtualServices to it
- we should use AWS EKS with ALB on the front
- the ALB should have a certificate (currently: *.somedomain.com)
- the pods also should have a valid certificate and only expose ports with TLS

Having those requirements in mind I've created 1 pod with nginx listening on port 443 (TCP) with proper TLS configuration - it's confirmed that this nginx alone works. The service part of that container looks like this:

```yaml apiVersion: v1
kind: Service
metadata:
  namespace: nginx-https
  name: nginx-https
  labels:
    app: nginx-https
    service: nginx-https
spec:
  type: NodePort
  ports:
    - port: 20443
      name: tcp
      protocol: TCP
      targetPort: 443
  selector:
    app: nginx-https
```

and the VirtualService loooks like this:

```yaml apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nginx-https
  namespace: nginx-https
spec:
  hosts:
    - istio.somedomain.com
    - istio-tls.somedomain.com
  gateways:
    - istio-system/external-gateway
  http:
  - match:
     - uri:
        prefix: "/"
    route:
    - destination:
        host: nginx-https
  tls:
  - match:
    - port: 443
      sniHosts:
      - istio-tls.somedomain.com
    route:
    - destination:
        host: nginx-https.nginx-https.svc.cluster.local
        port:
          number: 20443
```

the gateway config looks like this:

```yaml apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: external-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - 'istio.somedomain.com'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: istio-ingressgateway-certs
  - hosts:
      - "istio-tls.somedomain.com"
    port:
      number: 10443
      name: tls-passthrough
      protocol: TLS
    tls:
      mode: PASSTHROUGH
```

and following change was applied by IstioOperator:

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  components:
    ingressGateways:
      - enabled: true
        name: istio-ingressgateway
        k8s:
          serviceType: NodePort
          hpaSpec:
            minReplicas: 2
          overlays:
            - apiVersion: v1
              kind: Service
              name: istio-ingressgateway
              patches:
                - path: spec.ports
                  value:
                    - name: status-port
                      port: 15021
                      targetPort: 15021
                      protocol: TCP
                    - name: http2
                      port: 80
                      targetPort: 8080
                      protocol: TCP
                    - name: https
                      port: 443
                      targetPort: 8443
                      protocol: TCP
                    - name: tls-passthrough
                      port: 10443
                      targetPort: 8443
                      protocol: TCP
```
For using ALB with istio I've followed this guide: https://aws.amazon.com/blogs/containers/secure-end-to-end-traffic-on-amazon-eks-using-tls-certificate-in-acm-alb-and-istio/

Right now best I can do is to run workload with SSL offload on the ALB without the SSL certificate on a pod. The only response that I have is a "Bad gateway" message. Can you support me during this journey?
