### DISCUSSION TITLE
regex is not working with header block

### DISCUSSION THREAD

**Discussion by hridyeshpant** [istio/istio#52137] [General]
I have virtual service with delegate rule but delegate rule not working (getting 503) when using ```regex``` thing as part of headers but working fine when using ```exact```  
my delegate virtual service looks like 
```
spec:
  http:
  - match:
    - headers:
        my-header:
          exact: test-app-pr-10
      uri:
        prefix: /
    route:
    - destination:
        host: test-app-pr-10
        port:
          number: 80
```

and below is the my main virtual service examples, which have delegate rule to redirct request to above delegate virtual service.

**Using regex, it is  not working :**  passing when header value "my-header: test-app-pr-10" 
```
- delegate:
      name: test-app
      namespace: default
    match:
    - headers:
        my-header:
          regex: .+-pr-\d{2,}$                        #even putting ".-pr-." in regex rule not working, it should match test-app-pr-10 string
      uri:
        prefix: /
 ```
  
**Using exact, it is working**   passing same header value "my-header: test-app-pr-10" 
```
- delegate:
      name: test-app
      namespace: default
    match:
    - headers:
        my-header:
          exact: test-app-pr-10
      uri:
        prefix: /
 ```      
**Using prefix, it is working**  passing same header value "my-header: test-app-pr-10" 
```
spec:
  http:
  - match:
    - headers:
        my-header:
          prefix: test-app-pr-
      uri:
        prefix: /
 ```

Any help what i am missing for regex things ? following the regex format https://github.com/google/re2/wiki/Syntax 
even putting ".*-pr-.*" in regex rule not working when passing header like   "my-header: test-app-pr-10"
