### DISCUSSION TITLE
tcp.maxConnections in destination rule apparently doesn't work

### DISCUSSION THREAD

**Discussion by pablofilgueira91** [istio/istio#52332] [Q&A]
Hello, I am trying to configure tcp.maxConnections in my destination rule and from the tests I am doing it seems that it does not work.

this is my configuration
Gateway:
```
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: http-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*.dev.testing.ad'
    port:
      name: http
      number: 80
      protocol: HTTP
```
   
VitualService:
```
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: delayweb-hub
  namespace: default
spec:
  gateways:
  - istio-system/http-gateway
  hosts:
  - delayweb-default.dev.testing.ad
  http:
  - match:
    - uri:
        prefix: /metrics
    route:
    - destination:
        host: delayweb.default.svc.cluster.local
        subset: stable
  - name: canary-deployment
    retries:
      attempts: 0
    route:
    - destination:
        host: delayweb.default.svc.cluster.local
        port:
          number: 8080
        subset: canary
      weight: 0
    - destination:
        host: delayweb.default.svc.cluster.local
        port:
          number: 8080
        subset: stable
      weight: 100
```

and my DestinationRule:
```
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: delayweb
  namespace: default
spec:
  host: delayweb.default.svc.cluster.local
  subsets:
  - labels:
      app: delayweb
      rollouts-pod-template-hash: 6449cd5bf9
    name: stable
  - labels:
      app: delayweb
      rollouts-pod-template-hash: 6449cd5bf9
    name: canary
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 1
    tls:
      mode: DISABLE
```
      
      
 this is my testing 
 my delayweb service gives an http_code 200 after 10 seconds
 and my test consists of sending 5 curls in parallel, with which only one should respond 200 and the rest fail, but all 5 respond 200
```
seq 5 | xargs -n1 -P5 -I{} curl -s -o /dev/null -w "Conexión {}: %{http_code}\n" http://delayweb-default.dev.testing.ad/pabli/10

Conexión 4: 200
Conexión 3: 200
Conexión 5: 200
Conexión 1: 200
Conexión 2: 200
```

my istio version is 1.22.1
Am I missing some extra configuration? Or is something I did wrong?

On the other hand, I did the same test setting the maxconn in a haproxy and this test did give the expected result, only 1 responded 200
I leave my haproxy configuration in case it helps
```
frontend firstbalance
    bind *:8441
    default_backend binhub
 
backend binhub
        default-server inter 15s fall 3 rise 2
        server bbjumper2.testing.ad bbjumper2.testing.ad:8234 maxconn 1 check resolvers mydns
```
```
seq 5 | xargs -n1 -P5 -I{} curl -s -o /dev/null -w "Conexión {}: %{http_code}\n" http://hubprod1.testing.ad:8441/pabli/10

Conexión 4: 503
Conexión 1: 503
Conexión 2: 503
Conexión 3: 503
Conexión 5: 200
 ```
