### DISCUSSION TITLE
Passing un-terminated TLS traffic to pod

### DISCUSSION THREAD

**Discussion by esn89** [istio/istio#52338] [Q&A]
I have a GCP Internal Network LoadBalancer (passthrough), with the hopes of getting the TLS termination onto the pod:

Currently I have things set up like so:

```yaml
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: myapp-gateway
  namespace: myapp
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 3978
      name: tcp
      protocol: TLS
    tls:
      mode: PASSTHROUGH
    hosts:
    - myapp.com
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: myapp-virtualservice
  namespace: myapp
spec:
  hosts:
  - myapp.com
  gateways:
  - myapp-gateway
  tls:
  - match:
    - port: 3978
      sniHosts:
      - myapp.com
    route:
    - destination:
        host: myapp-service.myapp.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: myapp
spec:
  selector:
    app: myapp-noistio
    podlabel: myapp
  ports:
    - protocol: TCP
      port: 3978
      targetPort: 3978
```

When I telnet to my LoadBalancers IP and the 3987 port, it just hangs and I can't connect to it.

From within the cluster (I exec into pods), I am able to see that it is connect-able, both the pod and the service:

```
/app/src #  nc -zv 172.20.0.2 3978
172.20.0.2 (172.20.0.2:3978) open
/app/src #  nc -zv 172.18.27.70 3978
172.18.27.70 (172.18.27.70:3978) open
```

On the same LoadBalancer, I have an HTTPS service on 443 which seems to work fine, however.
