### DISCUSSION TITLE
Istio Virtual Service Skip Rule processing for unhealthy backend

### DISCUSSION THREAD

**Discussion by pvmraghunandan** [istio/istio#52411] [General]
Hi Team,
Looking for some guidance on below scenario from Istio. In the virtual service, there are two rules based on RegEx `/test1/t1/*` & `/test1/*` configured to the Kubernetes service `svc1` & `svc2` respectively. Is there anyway for Virtual Service to skip the first rule if all backends for the first rule (backend of svc1) is unhealthy so that down the line Rule 2 will handle the request (Generic Fallback Rule)? Health checks and Outlier Detection is added for Backend & Destination Rule so that upstream unhealthy can be detected.

```yml

- match:
    - uri:
        regex: /test/t1$ 
    route:
    - destination:
        host: svc1.example.svc.cluster.local 
        port:
          number: 80
  - match:
    - uri:
        regex: /test/.*$ 
    route:
    - destination:
        host: svc2.example.svc.cluster.local 
        port:
          number: 80
```
