### DISCUSSION TITLE
What's the best way get source ip in NLB with istio-ingressgateway

### DISCUSSION THREAD

**Discussion by HanCheo** [istio/istio#52653] [Q&A]
What is the best way to get source ip while using istio and NLB together?

From what I've tried, only way is to set `externalTrafficPolicy: Local`

But I don't want to adopt that because of the disadvantage that traffic can be concentrated on some node. Is there any other way?

my Config
```yaml
# ingress gateway config
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          service:
            externalTrafficPolicy: Local
          hpaSpec:
            minReplicas: 2
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 1024Mi
          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb" 
```

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: proxy-protocol
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: LISTENER
    patch:
      operation: MERGE
      value:
        listener_filters:
        - name: envoy.filters.listener.proxy_protocol
        - name: envoy.filters.listener.tls_inspector
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ingressgateway-settings
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          skip_xff_append: false
          use_remote_address: true
          xff_num_trusted_hops: 2
```
