### DISCUSSION TITLE
Can't seem to ever reach application of Argo Workflows (upstream_reset_before_response_started{connection_failure})

### DISCUSSION THREAD

**Discussion by esn89** [istio/istio#52682] [Q&A]
I currently have my Gateway and Virtualservice set up like so:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
  name: wf-gateway
  namespace: istio-system
spec:
  selector:
    app: istio-ingressgateway
    istio: dev-ingressgateway
  servers:
  - hosts:
    - argo.workflows.local
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: workflow-tls
      mode: SIMPLE
```

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: workflows-vs
  namespace: default
spec:
  gateways:
  - istio-system/wf-gateway
  hosts:
  - argo.workflows.local
  http:
  - match:
    - uri:
        prefix: /
    rewrite:
      uri: /
    route:
    - destination:
        host: my-argo-workflows-server.default.svc.cluster.local
        port:
          number: 2746
```

And the service:

```
my-argo-workflows-server   ClusterIP   172.16.141.72   <none>        2746/TCP                       31h
```

What happens:

Whenever I visit it on the browser, I get:

`upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure`

Whenever I do cURL, I get:

```
* using HTTP/1.x
> GET /workflows/default?&limit=50 HTTP/1.1
> Host: argo.workflows.local
> User-Agent: curl/8.9.1
> Accept: */*
> 
* Request completely sent off
** starts hanging here **
```

On the dev-ingressgateway pod, I enabled `trace` for logs and here is what I see:

```
[2024-08-14T22:25:30.902Z] "GET / HTTP/1.1" 503 UF,URX upstream_reset_before_response_started{connection_failure} - "-" 0 114 30028 - "172.16.148.1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0" "77e082b2-22a1-4cf4-a8a6-1ecbfe00a459" "argo.workflows.local" "172.16.148.229:2746" outbound|2746||my-argo-workflows-server.default.svc.cluster.local - 172.16.148.251:8443 172.16.148.1:32750 argo.workflows.local -


[2024-08-14T22:33:22.879Z] "GET / HTTP/1.1" 503 UF,URX upstream_reset_before_response_started{connection_failure} - "-" 0 114 30028 - "172.16.148.1" "curl/8.9.1" "91616d7c-8de6-4ad7-b34b-8e9ec7600ea8" "argo.workflows.local" "172.16.148.229:2746" outbound|2746||my-argo-workflows-server.default.svc.cluster.local - 172.16.148.251:8443 172.16.148.1:54438 argo.workflows.local -

```

The big kicker is that, when I'm inside a pod in my cluster, I am able to curl the local cluster DNS and it works:

```
$  curl http://my-argo-workflows-server.default.svc.cluster.local:2746
<!doctype html><html lang="en"><head><meta charset="UTF-8"><title>Argo</title><base href="/"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><link rel="icon" type="image/png" href="assets/favicon/favicon-32x32.png" sizes="32x32"><link rel="icon" type="image/png" href="assets/favicon/favicon-16x16.png" sizes="16x16"><script defer="defer" src="main.7a44505c3847a49bec49.js"></script></head><body><div id="app"></div></body></html>
```

So I believe that that the application itself starts up just fine and is able to listen and serve, but beyond that I haven't been having luck.
