### DISCUSSION TITLE
Isitio ambient mesh with service entry

### DISCUSSION THREAD

**Discussion by waynewong-ascenda** [istio/istio#52727] [General]
Hi sirs, I tested istio ambient mesh 1.23.0 with service entry but it seems doesnt work. I see it supported here https://istio.io/latest/news/releases/1.23.x/announcing-1.23/. Could you help to check? Thanks!

**Comment by ilrudie** [comment]
Hi @waynewong-ascenda, can you be more specific about your setup and what isn't working?

**Reply by waynewong-ascenda** [reply]
Hi @ilrudie, my setup is:
- Added service entry via yaml
- Try to remove a domain and test it from inside pod
I expected it blocked by istio ambient but it still worked
```
~ $ nc -vz us.app.unleash-hosted.com 443
us.app.unleash-hosted.com (34.237.45.63:443) open
```
Currently, it works well with sidecar mode. Thanks for your reply!

**Reply by ilrudie** [reply]
I'm not sure I am clear on what you are trying to do. It seems like maybe you are trying to use `REGISTRY_ONLY` to prevent egress.

**Reply by waynewong-ascenda** [reply]
@ilrudie yes, I set `meshConfig.outboundTrafficPolicy.mode = REGISTRY_ONLY` for accessing external services

**Reply by ilrudie** [reply]
`REGISTRY_ONLY` does not impact ambient. This is a feature that seems unlikely to be implemented for ambient in part because the project considers it to be of limited practical use while also being easy to misuse.

https://istio.io/latest/docs/ops/best-practices/security/#securing-egress-traffic has some good details. There is also a good blog post on a vendor's website about how ambient mesh enables easier egress gateways. The author is John Howard and it is easy to google if you are interested but I don't think I should link to vendor's page from the Istio discussions.

**Reply by ilrudie** [reply]
@waynewong-ascenda, can this be marked closed/resolved or is there another bit which is still unresolved?

**Reply by waynewong-ascenda** [reply]
Hi @ilrudie, I assumed that [this service entry](https://istio.io/latest/news/releases/1.23.x/announcing-1.23/#:~:text=Support%20for%20DNS%20ServiceEntries%20in%20waypoints%20and%20ztunnel. ) supported for ambient, could I know what exactly this feature?

**Reply by ilrudie** [reply]
This enables ambient supporting ServiceEntry with DNS backend. Previously if the backend address was not parsable as an IP we logged a warning in istiod and ignored that address.

**Reply by waynewong-ascenda** [reply]
Thanks @ilrudie, do you know when ambient mesh will support `REGISTRY_ONLY` feature with service entry? Since I used it with sidecar to whitelist outgoing domains 🙇

**Reply by howardjohn** [reply]
Ambient is unlikely to ever support `REGISTRY_ONLY`. This is not an appropriate way to restrict outbound traffic, and **does not provide any security guarantees**. See https://istio.io/latest/docs/ops/best-practices/security/#understand-traffic-capture-limitations.

What you want is an egress gateway + network policies, which already works today. See https://www.solo.io/blog/egress-gateways-made-easy/ for example

**Reply by waynewong-ascenda** [reply]
Hi @howardjohn, I followed [this guide](https://www.solo.io/blog/egress-gateways-made-easy/) to test outbound whitelist domain with service entry + waypoint proxy but I can call domain which is not in service entry though I enabled ambient mode for namespace. I dont see any traffic logs in waypoint too. What should I check more? My eks version is 1.30 and istio version is 1.23.0

**Reply by howardjohn** [reply]
One thing you'll need to make sure you do is enabled `--set values.cni.ambient.dnsCapture=true` and `PILOT_ENABLE_IP_AUTOALLOCATE=true` env var on the Istiod deployment. You can verify this is working by doing `curl -v <domain>` and should see it connecting to a `240.x.x.x` IP

**Reply by rezaebrahimi1** [reply]
I am on baremetal, also my k8s version is 1.30 and my istio version is 1.23.0, everything seems OK (values.cni.ambient.dnsCapture=true and PILOT_ENABLE_IP_AUTOALLOCATE=true), but no still dns is not resolved to VIP.
I have jus one waypoint gateway and my NS is labeled to use it. There is no networkPolicy in my setup

**Reply by rezaebrahimi1** [reply]
I decided to restart my CNI, istiod and ztunnel pods but it has no effect. Then a restart my sleep pod and all of a sudden i saw dns is getting resolved by the VIP!.
Also yesterday i restarted my istiod and ztunnel and also sleep pod, but it has no effect,
Maybe something related to CNI component?!

**Reply by rezaebrahimi1** [reply]
I try to reproduce the issue. I did my setup without configuring
values.cni.ambient.dnsCapture=true and PILOT_ENABLE_IP_AUTOALLOCATE=true
At first. Then after applying them i had issue until i restart all components and my client

**Reply by howardjohn** [reply]
When changing the dnsCapture, existing pods wil not be updated so that may be why it did not resolve until sleep is restarted

**Reply by waynewong-ascenda** [reply]
Hi @howardjohn, I enabled both values.cni.ambient.dnsCapture=true and PILOT_ENABLE_IP_AUTOALLOCATE=true for istiod, I restarted all istio-cni, ztunnel, waypoint proxy but I cant see any logs in waypoint pod as [this guide](https://www.solo.io/blog/egress-gateways-made-easy/). However, I can see this ip `240.x.x.x` in service entry, what should I check more? Thanks
```
status:
  addresses:
  - host: push.appsignal.com
    value: 240.240.0.1

```

**Reply by waynewong-ascenda** [reply]
Anyway, I can see logs in ztunnel but not waypoint proxy pod
```
Found 4 pods, using pod/ztunnel-tzv96
2024-09-03T10:30:07.366349Z	debug	xds:xds{id=3}	handling insert Kubernetes/networking.istio.io/ServiceEntry/istio-egress/httpbin.org/httpbin.org	
2024-09-03T10:32:17.261323Z	debug	xds:xds{id=3}	handling insert Kubernetes/networking.istio.io/ServiceEntry/istio-egress/httpbin.org/httpbin.or	
2024-09-03T10:32:17.261386Z	debug	xds:xds{id=3}	handling delete Kubernetes/networking.istio.io/ServiceEntry/istio-egress/httpbin.org/httpbin.org	
2024-09-03T10:32:17.261408Z	debug	xds:xds{id=3}	handling delete istio-egress/httpbin.org	
2024-09-03T10:32:17.261414Z	debug	xds::client:xds{id=3}	received delete resource type.googleapis.com/istio.workload.Address/Kubernetes/networking.istio.io/ServiceEntry/istio-egress/httpbin.org/httpbin.org	
2024-09-03T10:32:17.261419Z	debug	xds::client:xds{id=3}	received delete resource type.googleapis.com/istio.workload.Address/istio-egress/httpbin.org	
2024-09-03T10:32:40.071541Z	debug	xds:xds{id=3}	handling insert Kubernetes/networking.istio.io/ServiceEntry/istio-egress/httpbin.org/httpbin.org	
2024-09-03T10:32:40.071565Z	debug	xds:xds{id=3}	handling delete istio-egress/httpbin.or	
2024-09-03T10:32:40.071575Z	debug	xds:xds{id=3}	handling delete Kubernetes/networking.istio.io/ServiceEntry/istio-egress/httpbin.org/httpbin.or	
2024-09-03T10:32:40.071587Z	debug	xds::client:xds{id=3}	received delete resource type.googleapis.com/istio.workload.Address/istio-egress/httpbin.or	
2024-09-03T10:32:40.071593Z	debug	xds::client:xds{id=3}	received delete resource type.googleapis.com/istio.workload.Address/Kubernetes/networking.istio.io/ServiceEntry/istio-egress/httpbin.org/httpbin.or	
2024-09-03T10:34:22.987179Z	debug	xds:xds{id=4}	handling insert Kubernetes/networking.istio.io/ServiceEntry/istio-egress/httpbin.org/httpbin.org	
2024-09-03T10:35:41.161055Z	debug	xds:xds{id=4}	handling insert Kubernetes/networking.istio.io/ServiceEntry/istio-egress/httpbin.org/httpbin.org	
2024-09-03T10:47:08.147797Z	debug	xds:xds{id=4}	handling insert Kubernetes/networking.istio.io/ServiceEntry/istio-egress/httpbin.org/httpbin.org	
2024-09-03T10:49:56.267330Z	debug	xds:xds{id=4}	handling insert Kubernetes/networking.istio.io/ServiceEntry/istio-egress/httpbin.org/httpbin.org
```

**Reply by ilrudie** [reply]
if you run `istioctl zc service` you should be able to see all the services configured and whether or not they have a waypoint proxy. If no waypoint proxy is shown then you have a config issue with setting up the waypoint

**Reply by waynewong-ascenda** [reply]
Hi @ilrudie, I applied waypoint proxy via yaml, not use istioctl. Do I need to add netpol for waypoint proxy?

**Reply by waynewong-ascenda** [reply]
Hi @howardjohn @ilrudie, thanks for your help! I can restrict outbound with service entry + waypoint proxy in istio-egress namespace as [this guide](https://www.solo.io/blog/egress-gateways-made-easy/). However, I tested to opt-in on a per-service basis with service entry in another namespace, it didnt work. Is it possible to do that?
```
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: httpbin.org
  namespace: test # Not in istio-egress namespace where waypoint proxy resides
  labels:
    istio.io/use-waypoint: waypoint-proxy
spec:
  hosts:
  - httpbin.org
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  location: MESH_EXTERNAL
  resolution: DNS
```

**Reply by ilrudie** [reply]
I have a documentation update to clarify how to attach serviceentry (or other resources) to a waypoint in another namespace. Please be aware that the link below is just a preview, eventually some form of this will land on the main istio.io though once we agree on the exact wording.

https://deploy-preview-15649--preliminary-istio.netlify.app/latest/docs/ambient/usage/waypoint/#usewaypointnamespace

**Reply by ilrudie** [reply]
> Hi @ilrudie, I applied waypoint proxy via yaml, not use istioctl. Do I need to add netpol for waypoint proxy?

Istio doesn't create or mutate network policy when you create a waypoint. If you are using netpol it may need to be updated.

**Reply by waynewong-ascenda** [reply]
Thanks @ilrudie, it worked with cross namespace, so I close this discussion

**Reply by rezaebrahimi1** [reply]
> Ambient is unlikely to ever support `REGISTRY_ONLY`. This is not an appropriate way to restrict outbound traffic, and **does not provide any security guarantees**. See https://istio.io/latest/docs/ops/best-practices/security/#understand-traffic-capture-limitations.
> 
> What you want is an egress gateway + network policies, which already works today. See https://www.solo.io/blog/egress-gateways-made-easy/ for example

Dear @howardjohn
I tested "authorizationpolicy" in the link  you provide and i get following error:
**The AuthorizationPolicy "hb" is invalid: spec.targetRefs[0]: Invalid value: "object": Support kinds are core/Service and gateway.networking.k8s.io/Gateway**

**Reply by ilrudie** [reply]
@rezaebrahimi1, I think its a validation bug in 1.23.0 which was already corrected. ~Are you able to update to 1.23.1, it has correct validation.~ Actually, it looks like we may not have cherry-picked that fix to 1.23 yet. Need to take a seconds look to understand why.

**Reply by ilrudie** [reply]
OK. I created a [PR](https://github.com/istio/api/pull/3314) to get this fix into 1.23

**Reply by ilrudie** [reply]
@rezaebrahimi1, I was mistaken actually. Supporting policy attachment to SE sadly did not make the 1.23 branch cut and was not cherry-picked. I was pretty sure we made it but I was wrong and support will not be introduced until 1.24 most likely.

**Reply by waynewong-ascenda** [reply]
Hi @howardjohn @bleggett, I followed [this guide](https://www.solo.io/blog/egress-gateways-made-easy/) to restrict outbound with service entry + waypoint proxy in istio-egress namespace but there is no ztunnel logs, only waypoint proxy logs though I set debug ztunnel loglevel. Could i know why? My istio version is `1.23.2`, I installed ztunnel via helm chart
```
USER-SUPPLIED VALUES:
defaults:
  logLevel: debug
  meshConfig:
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: true

COMPUTED VALUES:
defaults:
  annotations: {}
  caAddress: ""
  env: {}
  hub: docker.io/istio
  image: ztunnel
  imagePullPolicy: ""
  imagePullSecrets: []
  istioNamespace: istio-system
  labels: {}
  logLevel: debug
  meshConfig:
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: true
  multiCluster:
    clusterName: ""
  podAnnotations:
    prometheus.io/port: "15020"
    prometheus.io/scrape: "true"
  podLabels: {}
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
  revision: ""
  seLinuxOptions: {}
  tag: 1.23.2
  terminationGracePeriodSeconds: 30
  variant: ""
  volumeMounts: []
  volumes: []
```
