### DISCUSSION TITLE
Routing Behavior for Requests Missing the specified HTTP Header

### DISCUSSION THREAD

**Discussion by paopa** [istio/istio#52762] [Q&A]
Hey there, I'm working on session affinity with Istio and setting up the destination rule as shown below:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: nginx-destination
  namespace: sample
spec:
  host: nginx-service.sample.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: "user-session" 
```

I'm curious about the routing behavior when a request is sent without the specified HTTP header. In my observations, with three pods available, the requests seem to be routed to different pods either randomly or based on some mechanism. However, this behavior doesn't seem to be documented for cases where the header is missing. 

Any insights on how requests without the header are handled? 
Thank you!
