### DISCUSSION TITLE
HttpHeaderName based consistent hash not work

### DISCUSSION THREAD

**Discussion by csh2022** [istio/istio#52790] [Q&A]
I made a simple case as follows:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: istio-test1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: hashicorp/http-echo:latest
        args:
        - "-text=Hello from $(MY_POD_NAME) at $(MY_POD_IP)"
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 5678

---

apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: istio-test1
spec:
  ports:
  - port: 80
    targetPort: 5678
  selector:
    app: myapp

---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: myapp
  namespace: istio-test1
spec:
  hosts:
  - "myapp.istio-test1.svc.cluster.local"
  http:
  - route:
    - destination:
        host: myapp.istio-test1.svc.cluster.local
      weight: 100

---

apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: myapp
  namespace: istio-test1
spec:
  host: myapp.istio-test1.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: test-header
````

However, when I send requests with the same `test-header`, the responses are coming from different pods instead of a single pod.

requests:
`for i in {1..10}; do curl -H "test-header: 1234" http://myapp.istio-test1.svc.cluster.local; done`

responses:
```
Hello from myapp-7b7559db4f-lhghz at 192.168.0.59
Hello from myapp-7b7559db4f-xkzgc at 192.168.0.40
Hello from myapp-7b7559db4f-lhghz at 192.168.0.59
Hello from myapp-7b7559db4f-xkzgc at 192.168.0.40
Hello from myapp-7b7559db4f-xkzgc at 192.168.0.40
Hello from myapp-7b7559db4f-xkzgc at 192.168.0.40
Hello from myapp-7b7559db4f-lhghz at 192.168.0.59
Hello from myapp-7b7559db4f-lhghz at 192.168.0.59
Hello from myapp-7b7559db4f-lhghz at 192.168.0.59
Hello from myapp-7b7559db4f-xkzgc at 192.168.0.40
```
