### DISCUSSION TITLE
How to point RequestAuthentication and AuthorizationPolicy to VirtualService without Service

### DISCUSSION THREAD

**Discussion by volkorny** [istio/istio#52810] [Q&A]
Hi Team,

I’m attempting to use JWT authentication for the solution described in this [GitHub discussion](https://github.com/istio/istio/discussions/52493). I followed the example provided in the [Istio documentation on JWT routing](https://istio.io/latest/docs/tasks/security/authentication/jwt-route/), which uses a Service as the destination in the `VirtualService` configuration:

```yaml
route:
- destination:
    port:
      number: 8000
    host: httpbin
```

In this example, the Service is labeled with `app: httpbin`, so the `RequestAuthentication` and `AuthorizationPolicy` configurations use the `selector: matchLabels: app: httpbin` to target the Service.

In my use case, however, I need to route traffic to an external URL in the `VirtualService`:

```yaml
route:
- destination:
    host: project2.example.com
    port:
      number: 443
```

Because of this, I cannot use `selector: matchLabels: app: httpbin` in my `RequestAuthentication` and `AuthorizationPolicy` configurations. 

I attempted the following configuration, but the URL `project1.example.com` remains accessible without authentication:

```yaml
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: httpbin-auth-policy
  namespace: staging-mesh
spec:
  selector:
    matchLabels:
      app: httpbin
  rules:
  - from:
    - source:
        requestPrincipals: ["*"]
    to:
    - operation:
        hosts: ["project2.example.com"]
```

It seems that Istio does not recognize that I want to apply the `RequestAuthentication` and `AuthorizationPolicy` to `project1.example.com`. Could you please assist me in configuring this properly?

Thank you!

**Comment by volkorny** [comment]
Full example config:

```
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: project1-example-com
  namespace: istio-ingress
spec:
  dnsNames:
  - project1.example.com
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-webhook-dnsimple-production
  secretName: project1-example-com-tls
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/controller: ignored-resource
  name: project1-gateway
  namespace: test-mesh
spec:
  selector:
    istio: ingress-public-gateway
  servers:
  - hosts:
    - project1.example.com
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - project1.example.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: istio-ingress/project1-example-com-tls
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: project1-virtualservice
  namespace: test-mesh
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "project1.example.com"
    external-dns.alpha.kubernetes.io/ttl: "60"
spec:
  hosts:
  - "*"
  gateways:
  - test-mesh/project1-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: project2.example.com
        port:
          number: 443
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: egress-project2-example-com
  namespace: test-mesh
spec:
  hosts:
    - project2.example.com
  ports:
    - name: https
      number: 443
      protocol: TLS
  location: MESH_EXTERNAL
  resolution: DNS
---
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: httpbin-ingress-jwt
  namespace: staging-mesh
spec:
  selector:
    matchLabels:
      app: httpbin
  jwtRules:
  - issuer: "https://jwt.example.com"
    jwks: |
      {
        "keys": [
          {
            "kty": "RSA",
            "alg": "RS256",
            "use": "sig",
            "kid": "my-key-id",
            "n": "...CUT...",
            "e": "...CUT..."
          }
        ]
      }
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: httpbin-auth-policy
  namespace: staging-mesh
spec:
  selector:
    matchLabels:
      app: httpbin
  rules:
  - from:
    - source:
        requestPrincipals: ["*"]
    to:
    - operation:
        hosts: ["project2.example.com"]
```
