### DISCUSSION TITLE
filter_chain_not_found error on https

### DISCUSSION THREAD

**Discussion by KOCEAN33** [istio/istio#52848] [Q&A] [answered]
http communication works smoothly, but https is completely impossible.
I use istio 1.23 & 1.22.3 (I upgraded during debug)
I use EKS to run Kubernetes, I followed aws blueprint(https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/patterns/istio/main.tf) 

when I tried to access https, i got "PR_END_OF_FILE_ERROR" on browser and
`[2024-08-26T07:45:40.173Z] "- - -" 0 NR filter_chain_not_found - "-" 0 0 247 - "-" "-" "-" "-" "-" - - 10.3.33.224:443 10.3.49.72:11479 - -` on istio-gateway

How can I get https connect?

This is my setup

# istio setup
## istio-base
```YAML
defaults:
  global:
    istioNamespace: istio-system
```
## istio-gateway
```YAML
# Helm Chart Values
defaults:
  name: istio-gateway
  labels:
    istio: ingressgateway

  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
      effect: "NoSchedule"

  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: external
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
      service.beta.kubernetes.io/aws-load-balancer-internal: "false"
      service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: deregistration_delay.timeout_seconds=200,deregistration_delay.connection_termination.enabled=true,preserve_client_ip.enabled=false
    ports:
      - name: status-port
        port: 15021
        protocol: TCP
        targetPort: 15021
      - name: http2
        port: 80
        protocol: TCP
        targetPort: 80
      - name: https
        port: 443
        protocol: TCP
        targetPort: 443
      - name: amqp
        port: 5672
        protocol: TCP
        targetPort: 5672

  podDisruptionBudget:
    minAvailable: 1

  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      # cpu: 2000m
      memory: 1024Mi

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: karpenter.sh/provisioner-name
                operator: DoesNotExist
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - istio-gateway
            topologyKey: kubernetes.io/hostname

```
## istiod
```YAML
# Helm Chart Values
pilot:
  env:
    K8S_INGRESS_NS: istio-system

  autoscaleEnabled: true
  autoscaleMin: 1
  autoscaleMax: 5
  replicaCount: 3

  resources:
    requests:
      cpu: 1000m
      memory: 2048Mi
    limits:
      # cpu: 2000m
      memory: 4096Mi

  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
      effect: "NoSchedule"

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - istiod
            topologyKey: topology.kubernetes.io/zone

meshConfig:
  accessLogFile: /dev/stdout
  ingressService: istio-system
  ingressSelector: istio-system

global:
  proxy:
    resources:
      requests:
        cpu: 250m
        memory: 64Mi
      limits:
        # cpu: 1m
        memory: 128Mi

  priorityClassName: "system-cluster-critical"
```

# Gateway - VS
## Gateway
```YAML
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: argo-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - argocd.example.com
      port:
        number: 80
        name: http
        protocol: HTTP
    - hosts:
        - argocd.example.com
      port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        credentialName: example-tls
        mode: SIMPLE
```

## virtual service
```YAML 
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: argocd-server
  namespace: argocd
spec:
  hosts:
    - argocd.example.com
  gateways:
    - istio-system/argo-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: argo-cd-argocd-server
            port:
              number: 80
```

## Certificate 
```YAML
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-tls
  namespace: istio-system
spec:
  secretName: example-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - argocd.example.com
```

I don't know Certificate is working or not

Thank you for helping me
