### DISCUSSION TITLE
Cross namespace communication is allowed even after implementing mesh-wide sidecar resource

### DISCUSSION THREAD

**Discussion by praseed44** [istio/istio#52861] [Q&A] [answered]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi Team,

I have implemented the mesh-side default sidecar in istio-system namespace. Purpose is to limit the config pushes from istiod and also to limit the inter-namespace communication excluding istio-system.

The istioctl proxy-config also shows the routes as per the following config - services in own namespace + istio-system namespace. However, I am able to access services in another namespace by exec into any pod and performing curl, which doesn't have any routes to those namespaces. Ideally this should be blocked by proxy as per the following configuration.

Can you please correct me I am wrong in my understanding? How is the proxy able to access services from other namespaces which is not allowed by Sidecar config.

```
apiVersion: networking.istio.io/v1
kind: Sidecar
metadata:
  name: default
  namespace: istio-system
spec:
  egress:
  - hosts:
    - "./*"
    - "istio-system/*"
```

### Version

```Text
$ istioctl-1-18-2 version
client version: 1.18.2
control plane version: 1.20.3
data plane version: 1.20.3 (1874 proxies)
$ kubectl version
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.9
```
