### DISCUSSION TITLE
istio 1.22 envoyfilter add headers invalid

### DISCUSSION THREAD

**Discussion by nicole-lihui** [istio/istio#52920] [Q&A]
I’m asking for help from friends. I want to add a custom header to my request, but it’s not working in Istio version 1.22

my configurations :
```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: test-gw
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - '*'
      port:
        name: test
        number: 8080
        protocol: HTTP
 ---
 apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: test
  namespace: istio-system
spec:
  gateways:
    - istio-system/test-gw
  hosts:
    - '*'
  http:
    - name: test-login
      route:
        - destination:
            host: helloworld.default.svc.cluster.local
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: test-token-to-cookie
  namespace: istio-system
spec:
  configPatches:
    - applyTo: HTTP_ROUTE
      match:
        context: GATEWAY
        routeConfiguration:
          vhost:
            route:
              name: test-login
      patch:
        operation: MERGE
        value:
          name: envoy.lua
          typed_per_filter_config:
            envoy.filters.http.lua:
              '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute
              source_code:
                inline_string: |-
                  function envoy_on_response(response_handle)
                      response_handle:logInfo("------test")
                      response_handle:headers():add("cus_response_body_size", response_handle:body():length())
                      response_handle:logInfo("-------------------------test-nicole")
                  end
  workloadSelector:
    labels:
      istio: ingressgateway
```

istioctl output:
```bash
$ istioctl version                                                           
client version: 1.23.0
control plane version: 1.22.2
data plane version: 1.22.2 (14 proxies)


$ istioctl pc routes istio-ingressgateway-79644456c-g65xg.istio-system -ojson
[
    {
        "name": "http.8080",
        "virtualHosts": [
            {
                "name": "*:8080",
                "domains": [
                    "*"
                ],
                "routes": [
                    {
                        "name": "envoy.lua",
                        "match": {
                            "prefix": "/"
                        },
                        "route": {
                            "cluster": "outbound|5000||helloworld.default.svc.cluster.local",
                            "timeout": "0s",
                            "retryPolicy": {
                                "retryOn": "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes",
                                "numRetries": 2,
                                "retryHostPredicate": [
                                    {
                                        "name": "envoy.retry_host_predicates.previous_hosts",
                                        "typedConfig": {
                                            "@type": "type.googleapis.com/envoy.extensions.retry.host.previous_hosts.v3.PreviousHostsPredicate"
                                        }
                                    }
                                ],
                                "hostSelectionRetryMaxAttempts": "5",
                                "retriableStatusCodes": [
                                    503
                                ]
                            },
                            "maxGrpcTimeout": "0s"
                        },
                        "metadata": {
                            "filterMetadata": {
                                "istio": {
                                    "config": "/apis/networking.istio.io/v1alpha3/namespaces/istio-system/virtual-service/test"
                                }
                            }
                        },
                        "decorator": {
                            "operation": "helloworld.default.svc.cluster.local:5000/*"
                        },
                        "typedPerFilterConfig": {
                            "envoy.filters.http.lua": {
                                "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute",
                                "sourceCode": {
                                    "inlineString": "function envoy_on_response(response_handle)\n    response_handle:logInfo(\"------test\")\n    response_handle:headers():add(\"response_body_size\", response_handle:body():length())\n    response_handle:logInfo(\"-------------------------test-nicole\")\nend"
                                }
                            }
                        }
                    }
                ],
                "includeRequestAttemptCount": true
            }
        ],
        "validateClusters": false,
        "maxDirectResponseBodySizeBytes": 1048576,
        "ignorePortInHostMatching": true
    },
    {
        "virtualHosts": [
            {
                "name": "backend",
                "domains": [
                    "*"
                ],
                "routes": [
                    {
                        "match": {
                            "prefix": "/healthz/ready"
                        },
                        "route": {
                            "cluster": "agent"
                        }
                    }
                ]
            }
        ]
    },
    {
        "virtualHosts": [
            {
                "name": "backend",
                "domains": [
                    "*"
                ],
                "routes": [
                    {
                        "match": {
                            "prefix": "/stats/prometheus"
                        },
                        "route": {
                            "cluster": "prometheus_stats"
                        }
                    }
                ]
            }
        ]
    }
]
```
