### DISCUSSION TITLE
custom ext authz followed by allow authorization policy with header check cond not working

### DISCUSSION THREAD

**Discussion by 11mhg** [istio/istio#52945] [General]
I was under the impression that based on the ordering of the authorization policies and the request injections possible from the custom authz endpoints, that it would be possible to set something up like the following:
```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: gateway-testing
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      istio: gateway-testing
  action: CUSTOM
  provider:
    name: "oauth2-proxy"
  rules:
    - to:
      - operation:
          hosts: ["*"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: gateway-testing-group-allow
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      istio: gateway-testing
  action: ALLOW
  rules:
    - to:
      - operation:
          hosts: ["*"]
      when:
      - key: request.auth.claims[groups]
        values: ['O_Some_Group_That_Exists']
---
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: gateway-testing-authn
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      istio: gateway-testing
  jwtRules:
  - issuer: "https://MY_DOMAIN.com/dex"
    jwksUri: https://MY_DOMAIN.com/dex/keys
```

This seems to fail 100% of the time on the `gateway-testing-group-allow`. This is confusing as I've check the claims on the jwt that's set to the authorization bearer token in the request after the custom ext_authz and know that the `O_Some_Group_That_Exists` exists and is present. I added the request authentication cause it's my understanding that this is needed to be able to check the auth claim specified. Is there something I'm missing? Is this not a supported workflow? 

Thanks!
