### DISCUSSION TITLE
Is outboundTrafficPolicy mode: REGISTRY_ONLY supported in Ambient mode with Istio 1.22?

### DISCUSSION THREAD

**Discussion by courcelm** [istio/istio#53021] [Q&A] [answered]
Hello,
I am not successful at blocking external traffic with this configuration in Ambient mode:

kind: IstioOperator
spec:
  meshConfig:
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY

This configuration used to work in the sidecar mode.

Is this supported in ambient mode with Istio 1.22?

Thanks for your assistance.

**Comment by howardjohn** [comment, marked as answer]
Ambient mode does not implement `REGISTRY_ONLY`.

Please be aware that even in sidecars, `REGISTRY_ONLY` does not really _block_ traffic. It simply doesn't configure to handle the traffic. This is an important distinction, because it does **not** provide security guarantees. See https://istio.io/latest/docs/ops/best-practices/security/#understand-traffic-capture-limitations or https://blog.howardjohn.info/posts/bypass-egress/.

To provide security guarantees you need egress gateways. Note that ambient makes this **way** easier. We haven't yet built up proper istio.io docs since its brand new, but https://www.solo.io/blog/egress-gateways-made-easy/ gives an overview

**Reply by courcelm** [reply]
Thanks for your quick reply and clear answer @howardjohn. Good references. I learned important stuff today.

**Reply by ssheisy** [reply]
Hi, @howardjohn Thanks for your answer. After reading the [this](https://www.solo.io/blog/egress-gateways-made-easy/ ), I still I have a question on how to achieve the similar functionality of what sidecar REGISTRY_ONLY mode does in ambient mode. I understand that the REGISTRY_ONLY is not the best security practice, but at least it provides a feature of egress traffic control - blocks any egress IP/Host that can't be recognized as in mesh or in serviceEntries. In ambient mode, I am having a hard time to block all egress traffic that can't be captured by serviceEntries. ServiceEntry needs explicit Host/Port, so it's not a catch all. How can I block all the other egress traffic that's not defined in ServiceEntries, like in sidecar REGISTRY_ONLY mode? Am I missing something here? Thanks.

**Reply by visit1985** [reply]
@ssheisy, I solved this in my cluster using a combination of network policies and waypoint proxy (on ISTIO 1.26).

<details><summary>example manifests</summary>

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-egress
  namespace: default
spec:
  # select all pods in this namespace
  podSelector: {}
  # deny all egress by default
  policyTypes:
  - Egress
  egress:
  # dns resolution
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
  # configuration distribution to ztunnel and waypoint proxies via gRPC
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: istio-system
      podSelector:
        matchLabels:
          istio: pilot
  # telemetry collection
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: istio-system
      podSelector:
        matchLabels:
          istio: telemetry
  # intra-namespace traffic to all pods in this namespace
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: default
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-gateway-allow-egress
  namespace: default
spec:
  podSelector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: egress-gateway
  policyTypes:
  - Egress
  egress:
  - {}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: egress-gateway
  namespace: default
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - name: mesh
    port: 15008
    protocol: HBONE
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: google
  namespace: default
  labels:
    istio.io/use-waypoint: egress-gateway
spec:
  hosts:
  - www.google.com
  ports:
  - name: http
    number: 80
    protocol: HTTPS
  - name: tls
    number: 443
    protocol: HTTPS
  resolution: DNS
```

</details>
