### DISCUSSION TITLE
Headless Service Auto-discovery over Multi-cluster Multi-network: DNS fails to proxy

### DISCUSSION THREAD

**Discussion by Budgiebrain994** [istio/istio#53022] [Q&A]
Good morning

I have two clusters, Cluster A and Cluster B. Cluster A is running a normal service (prometheus) and also a headless service (thanos sidecar) pointing to two pod IPs. Cluster B has a workload attempting to resolve the DNS of this headless service on Cluster A, but is unable to do so - Istio is not auto-discovering the headless service across the cluster boundary. I have verified that communication between the clusters is successful, as automatic service discovery is finding all other services correctly.
I expect that Cluster B's pod is able to successfully resolve the headless service on Cluster A. Is my understanding correct, and if not, how so?

Cluster A's headless service:
```
% kubectl describe service --namespace monitoring tooling-02-prometheus-thanos
Name:              tooling-02-prometheus-thanos
Namespace:         monitoring
<...>
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                None
IPs:               None
Port:              grpc  10901/TCP
TargetPort:        grpc/TCP
Endpoints:         10.a.b.c:10901,10.d.e.f:10901
Session Affinity:  None
Events:            <none>
```

Performing a `dig` on this headless service from within the cluster using a debug pod successfully resolves the IP addresses:
```
% dig tooling-02-prometheus-thanos.monitoring.svc.cluster.local

; <<>> DiG 9.18.24-1-Debian <<>> tooling-02-prometheus-thanos.monitoring.svc.cluster.local
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1328
;; flags: qr aa rd; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;tooling-02-prometheus-thanos.monitoring.svc.cluster.local. IN A

;; ANSWER SECTION:
tooling-02-prometheus-thanos.monitoring.svc.cluster.local. 30 IN A 10.a.b.c
tooling-02-prometheus-thanos.monitoring.svc.cluster.local. 30 IN A 10.d.e.f

;; Query time: 4 msec
;; SERVER: 172.20.0.10#53(172.20.0.10) (UDP)
;; WHEN: Fri Sep 06 11:23:25 ACST 2024
;; MSG SIZE  rcvd: 221
```

Checking `dns:debug` logs from Istio's proxy sidecar shows the request successfully intercepted and served by Istio:
```
2024-09-06T01:53:25.079225Z	debug	dns	request ;; opcode: QUERY, status: NOERROR, id: 1328
<as in dig above>
2024-09-06T01:53:25.079304Z	debug	dns	response for hostname "tooling-02-prometheus-thanos.monitoring.svc.cluster.local." (found=true): ;; opcode: QUERY, status: NOERROR, id: 1328
<as in dig above>
```

From Cluster B's perspective, performing a `dig` on Cluster A's headless service:
```
% dig tooling-02-prometheus-thanos.monitoring.svc.cluster.local

; <<>> DiG 9.18.24-1-Debian <<>> tooling-02-prometheus-thanos.monitoring.svc.cluster.local
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 31971
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; COOKIE: 91f8d43bf65f59ca (echoed)
;; QUESTION SECTION:
;tooling-02-prometheus-thanos.monitoring.svc.cluster.local. IN A

;; AUTHORITY SECTION:
cluster.local.		30	IN	SOA	ns.dns.cluster.local. hostmaster.cluster.local. 1725436567 7200 1800 86400 30

;; Query time: 0 msec
;; SERVER: 172.20.0.10#53(172.20.0.10) (UDP)
;; WHEN: Fri Sep 06 11:44:38 ACST 2024
;; MSG SIZE  rcvd: 191
```

Checking `dns:debug` logs from Istio's proxy sidecar:
```
2024-09-06T02:14:08.084313Z	debug	dns	updated lookup table with 451 hosts
2024-09-06T02:14:38.721358Z	debug	dns	request ;; opcode: QUERY, status: NOERROR, id: 31971
<as in dig above>
2024-09-06T02:14:38.722911Z	debug	dns	response for hostname "tooling-02-prometheus-thanos.monitoring.svc.cluster.local." not found in dns proxy, querying upstream
2024-09-06T02:14:38.724379Z	debug	dns	upstream response for hostname "tooling-02-prometheus-thanos.monitoring.svc.cluster.local." : ;; opcode: QUERY, status: NXDOMAIN, id: 31971
<as in dig above>
```

We can see that the hostname is not found in the cache, and Istio passes it up to CoreDNS, which is not aware of the hostname.

`/ndsz` from Cluster A's perspective:
```
{
  "resource": {
    "@type": "type.googleapis.com/istio.networking.nds.v1.NameTable",
    "table": {
      <.....>
      "tooling-02-prometheus-thanos.monitoring.svc.cluster.local": {
        "ips": [
          "10.a.b.c",
          "10.d.e.f"
        ],
        "registry": "Kubernetes",
        "shortname": "tooling-02-prometheus-thanos",
        "namespace": "monitoring"
      },
      "tooling-02-prometheus.monitoring.svc.cluster.local": {
        "ips": [
          "172.x.y.z"
        ],
        "registry": "Kubernetes",
        "shortname": "tooling-02-prometheus",
        "namespace": "monitoring"
      }
    }
  }
}
```
`/ndsz` from Cluster B's perspective:
```
{
  "resource": {
    "@type": "type.googleapis.com/istio.networking.nds.v1.NameTable",
    "table": {
      <.....>
      "tooling-02-prometheus.monitoring.svc.cluster.local": {
        "ips": [
          "172.x.y.z"
        ],
        "registry": "Kubernetes",
        "shortname": "tooling-02-prometheus",
        "namespace": "monitoring"
      }
    }
  }
}
```
As we can see, the automatic service discovery protocol isn't detecting headless services on the different cluster, but it does show normal services.

Istio configuration on Cluster A:
```
values:
  global:
    meshID: staging
    multiCluster:
      clusterName: staging-aps2-tooling-02
    network: staging-aps2-tooling-02
  meshConfig:
    defaultConfig:
      gatewayTopology:
        numTrustedProxies: 1
      holdApplicationUntilProxyStarts: true
      proxyMetadata:
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
        ISTIO_META_DNS_CAPTURE: "true"
```

Istio configuration on Cluster B:
```
values:
  global:
    meshID: staging
    multiCluster:
      clusterName: staging-aps2-edge-02
    network: staging-aps2-edge-02
  meshConfig:
    defaultConfig:
      gatewayTopology:
        numTrustedProxies: 1
      holdApplicationUntilProxyStarts: true
      proxyMetadata:
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
        ISTIO_META_DNS_CAPTURE: "true"
```

How is my understanding of headless service forwarding misguided? Thanks in advance.
