### DISCUSSION TITLE
In Ambient mode, how do I access the bookinfo demo app via external IP/hostname?

### DISCUSSION THREAD

**Discussion by benjaminxie** [istio/istio#53020] [Q&A]
I'm testing out the new Istio ambient mode on an AKS cluster with Kubernetes version 1.28.3. I've deployed the bookinfo demo app and can access it using `kubectl port-foward`. However, I'd like to access the app using the gateway's original external IP. I thought simply pasting <external ip>/productpage would allow me to access the demo app just like localhost:8080/productpage but that has not been the case. What additional steps would I need to take.

Similarly, what additional steps do I need to take if I'd like to use a hostname instead of an IP address? I know that the [httpbin demo app](https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-control/) in the Ingress Gateway traffic management task seems to cover this seeing as its gateway and http route includes a hostname. However, after using the same installation instructions and following the steps in that task using the Gateway APIs, I'm not able to use the hostname to access (and to be clear, I do add the proper entry to my hosts file).

Thanks for the help!

**Comment by benjaminxie** [comment]
Here's how it's done. In short, you make your gateway use the istio-ingress service's IP address.

I basically followed the [tutorial from the AKS Engineering blog ](https://azure.github.io/AKS/2024/08/06/istio-with-gateway-api). Instead of using the AKS mesh add-on, I followed the [Istio Ambient Mode instructions](https://istio.io/latest/docs/ambient/install/helm/#install-the-control-plane) and installed Istio using Helm, making sure to also install the gateway chart.

Moving onto deploying the bookinfo application, I made the following deviations from Istio's instructions. The first is the gateway I deployed
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: istio-ingress
spec:
  addresses:
  - type: Hostname
    value: istio-ingress
  gatewayClassName: istio
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    hostname: bookin.fo
    name: default
    port: 80
    protocol: HTTP
```
The differences to note is that I deployed my gateway in the istio-ingress namespace, I use the optional spec.addresses field, as well as the spec.listeners.hostname field.

Then, for my HTTPRoute, I used
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: bookinfo
  namespace: bookinfo
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: gateway
    namespace: istio-ingress
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: productpage
      port: 9080
      weight: 1
    matches:
    - path:
        type: Exact
        value: /productpage
    - path:
        type: PathPrefix
        value: /static
    - path:
        type: Exact
        value: /login
    - path:
        type: Exact
        value: /logout
    - path:
        type: PathPrefix
        value: /api/v1/products
```
The one difference to note is in spec.parentRefs. Make sure you correctly set the name and namespace. Another difference you may notice is the namespace. This isn't important because the gateway is allowing routes from all namespaces.

For completeness, make sure the address for your gateway matches the external-IP for the istio-ingress service. Use that IP to properly set your hostfile. Based on what I used, I'd have to add a line like
```
<gateway address> bookin.fo
```
Go to your browser, type bookin.fo/productpage and you should see the page.

I'm not sure why I can't just the service that's automatically created when I create a gateway. Maybe it has something to do with using the Istio gateway class?
