### DISCUSSION TITLE
how to record source_workload and destination_workload on istio-proxy accesslog just like that in metrics: istio_reuqests_total

### DISCUSSION THREAD

**Discussion by shuxnhs** [istio/istio#53052] [General]
how to record source_workload and destination_workload on istio-proxy accesslog just like that in metrics: istio_reuqests_total

**Comment by zirain** [comment]
`[%CEL(filter_state['wasm.upstream_peer'].workload_name)%] [%CEL(filter_state['wasm.downstream_peer'].workload_name)%]`

**Reply by shuxnhs** [reply]
Please can you provide a complete example? Thank you.

**Comment by zirain** [comment]
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      meshID: mesh1
  meshConfig:
    accessLogFormat: "[%START_TIME%] [%CEL(filter_state['wasm.upstream_peer'].workload_name)%] [%CEL(filter_state['wasm.downstream_peer'].workload_name)%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% \"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %REQUEST_TX_DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%\n"
    accessLogFile: /dev/stdout
```
