### DISCUSSION TITLE
[Ambient] AuthorizationPolicy for egress-waypoint: workload to external host HTTPS

### DISCUSSION THREAD

**Discussion by kapistka** [istio/istio#53051] [Q&A] [answered]
Hi team!
Is there any way to allow certain external hosts for certain workloads (HTTPS)?
I tried the following ways and they don't seem to work (v1.23.0).

1. @howardjohn https://www.solo.io/blog/egress-gateways-made-easy/ AuthorizationPolicy for ServiceEntry: `is invalid: spec.targetRefs[0]: Invalid value: "object": Support kinds are core/Service and gateway.networking.k8s.io/Gateway`

<details>
  <summary>2. AuthorizationPolicy for ztunnel does not block anything, everything is allowed to everyone:</summary>

```yaml
kind: AuthorizationPolicy
apiVersion: security.istio.io/v1
metadata:
  name: zt-app-httpbin.org
  namespace: egr
spec:
  selector:
    matchLabels:
      app: wp
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/app/sa/app1
    to:
    - operation:
        hosts:
        - httpbin.org
```
</details>

<details>
  <summary>3. AuthorizationPolicy for egress-waypoint blocks everything with an error: curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to httpbin.org:443</summary>

```yaml
  kind: AuthorizationPolicy
  apiVersion: security.istio.io/v1
  metadata:
    name: wp-app-httpbin.org
    namespace: egr
  spec:
    targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: wp
    rules:
    - from:
      - source:
          principals:
          - cluster.local/ns/app/sa/app1
      to:
      - operation:
          hosts:
          - httpbin.org
```
</details>

<details>
  <summary>My egress config</summary>

```yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio.io/use-waypoint: wp
    istio.io/dataplane-mode: ambient
  name: egr
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: default
  namespace: egr
spec:
  host: "*"
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE
---        
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  labels:
    istio.io/waypoint-for: all
    app: wp
  name: wp
  namespace: egr
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - allowedRoutes:
      namespaces:
        from: Same
    name: mesh
    port: 15008
    protocol: HBONE
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: default
  namespace: egr
  labels:
    istio.io/use-waypoint: wp
spec:
  hosts:
  - httpbin.org
  - github.com
  ports:
  - name: https
    number: 443
    protocol: HTTPS
  location: MESH_EXTERNAL
  resolution: DNS

# To block outbound external trafic in app ns:
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default
  namespace: app
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels: {}
  egress:
  - to:
    - podSelector:
       matchLabels: {}
      namespaceSelector:
       matchLabels: {} 
  ```
</details>
