### DISCUSSION TITLE
raw TCP request with TLS termination at gateway level

### DISCUSSION THREAD

**Discussion by ramandas** [istio/istio#53110] [Q&A]
i have one scenario. I have 2 application which is listening on same port lets say 7777 and on raw TCP protocol only no http/https.
i configured gateway with PROTOCOL TLS and tls mode set to SIMPLE and listen on port 9999. then i created 2 virtual service pointed to each app service. but request is only served by app1 no request will go to app2. is there some thing where we can filter request with sniHost and then forward that request to dedicated application. i want tcp connection to be secure so i use tls mode with SIMPLE as my application dont have mechanism to terminate TLS.

**Comment by ramandas** [comment]
this is my gateway file
=============================
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: tcp-tls-gateway

spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 9999
      name: tls-new
      protocol: TLS
    tls:
      mode: SIMPLE
      credentialName: "my-tls"
    hosts:
    - "*.example.in"
    - app1.example.in
    - app2.example.in
```
    
  ==============================
  
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: tcp-app1
spec:
  hosts:
  - "app1.example.in"  
  gateways:
  - istio-system/tcp-tls-gateway  # Reference the Gateway
  tcp:
  - match:
    - port: 9999  # Match traffic coming in on port 9443 (TLS)
    route:
    - destination:
        host: app1.test.svc.cluster.local  # Route to the app1 service
        port:
          number: 7777  # The backend service port (raw TCP)

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: tcp-app2
spec:
  hosts:
  - "app2.example.in"  
  gateways:
  - istio-system/tcp-tls-gateway  # Reference the Gateway
  tcp:
  - match:
    - port: 9999  # Match traffic coming in on port 9443 (TLS)
    route:
    - destination:
        host: app2.test.svc.cluster.local  # Route to the app1 service
        port:
          number: 7777  # The backend service port (raw TCP)

```
