### DISCUSSION TITLE
How to mix L4 and L7 `Authorizationpolicies` using ambient

### DISCUSSION THREAD

**Discussion by ca-scribner** [istio/istio#53134] [General]
I'm hitting issues with mixing L4 and L7 `AuthorizationPolicies` using istio 1.23.1 and wondering if I'm doing something wrong.  

I've followed [this ambient getting started page](https://istio.io/latest/docs/ambient/getting-started/) to deploy bookinfo, and create an[L4 AuthorizationPolicy](https://istio.io/latest/docs/ambient/getting-started/enforce-auth-policies/#enforce-layer-4-authorization-policy/) allowing the deployed ingress gateway to talk to `productpage`:

<details>

```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: gateway-to-productpage-viewer-l4
  namespace: bookinfo-1
spec:
  selector:
    matchLabels:
      app: productpage
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/bookinfo-1/sa/bookinfo-gateway-istio
```

</details>

That works as expected:
* `curl -v http://productpage:9080/productpage` from pod with`sa=bookinfo-gateway-istio` succeeds
* `curl -v http://productpage:9080/productpage` from pod with `sa=sleep` fails with "connection reset by peer".  I see traffic rejected by policy in ztunnel logs

If I then delete that AuthorizationPolicy and deploy a waypoint (`istioctl waypoint apply --enroll-namespace --wait --overwrite`), I can create [this L7 policy](https://istio.io/latest/docs/ambient/getting-started/enforce-auth-policies/#enforce-layer-7-authorization-policy):
<details>

```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: productpage-viewer
  namespace: default
spec:
  targetRefs:
  - kind: Service
    group: ""
    name: productpage
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/default/sa/sleep
    to:
    - operation:
        methods: ["GET"]
```

</details>

and I get policy enforcement as expected:
* `curl -v http://productpage:9080/productpage` from pod with`sa=bookinfo-gateway-istio` fails (403)
  * ztunnel logs show traffic is ok
  * waypoint logs show: <details>
[2024-09-13T20:45:18.159Z] "GET /productpage HTTP/1.1" 403 - rbac_access_denied_matched_policy[none] - "-" 0 19 0 - "-" "curl/7.35.0" "491ffc1e-5722-4474-97a1-5f99e5f808e2" "productpage:9080" "-" inbound-vip|9080|http|productpage.bookinfo-1.svc.cluster.local - 10.96.172.202:9080 10.244.0.27:43046 - default

</details>

* `curl -v http://productpage:9080/productpage` from pod with `sa=sleep` succeeds (200)

My expectation was that, if I combined both `AuthorizationPolicies`, I should then allow both cases to work.  But what I get is:
* `curl -v http://productpage:9080/productpage` from pod with`sa=bookinfo-gateway-istio` fails (403)
  * ztunnel logs show traffic is ok
  * waypoint logs show (same as above): <details>
[2024-09-13T20:51:27.119Z] "GET /productpage HTTP/1.1" 403 - rbac_access_denied_matched_policy[none] - "-" 0 19 0 - "-" "curl/7.35.0" "93117d98-e962-406b-9dbe-9fc73f9b076b" "productpage:9080" "-" inbound-vip|9080|http|productpage.bookinfo-1.svc.cluster.local - 10.96.172.202:9080 10.244.0.27:43046 - default
</details>

* `curl -v http://productpage:9080/productpage` from pod with `sa=sleep` fails with "upstream connect error or disconnect/reset before headers. reset reason: connection termination" (503)
  * ztunnel logs show two entries, with inbound traffic to dst.workload=productpage blocked due to policy rejection <details>
2024-09-13T20:52:20.021409Z	info	access	connection complete	src.addr=10.244.0.33:38728 src.workload="curl-othersa3" src.namespace="bookinfo-1" src.identity="spiffe://cluster.local/ns/bookinfo-1/sa/sleep" dst.addr=10.244.0.32:15008 dst.hbone_addr=10.96.172.202:9080 dst.service="productpage.bookinfo-1.svc.cluster.local" dst.workload="waypoint-7d5759cb9b-nxbfj" dst.namespace="bookinfo-1" dst.identity="spiffe://cluster.local/ns/bookinfo-1/sa/waypoint" direction="outbound" bytes_sent=91 bytes_recv=313 duration="3ms"
2024-09-13T20:52:20.196182Z	error	access	connection complete	src.addr=10.244.0.23:47366 src.workload="prometheus-84676b8788-2z49p" src.namespace="istio-system" dst.addr=10.244.0.17:9080 dst.service="productpage.bookinfo-1.svc.cluster.local" dst.workload="productpage-v1-7c4b6b857-t4p5s" dst.namespace="bookinfo-1" direction="inbound" bytes_sent=0 bytes_recv=0 duration="0ms" error="connection closed due to policy rejection"
</details>

  * waypoint logs showing (I think) that the ztunnel at the destination closed the connection: <details>
[2024-09-13T20:52:20.019Z] "GET /productpage HTTP/1.1" 503 UC upstream_reset_before_response_started{connection_termination} - "-" 0 95 1 - "-" "curl/7.35.0" "67c3aa7d-a557-4fd2-9615-82efeda84944" "productpage:9080" "envoy://connect_originate/10.244.0.17:9080" inbound-vip|9080|http|productpage.bookinfo-1.svc.cluster.local envoy://internal_client_address/ 10.96.172.202:9080 10.244.0.33:39974 - default
</details>

So from what I can tell, the L4 and L7 policies both block each other.  Is this expected?

Where this really feels like an odd behaviour is if I use a global `allow-nothing` policy on my cluster to prevent unauthorized traffic:

```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-nothing
  namespace: istio-system
spec:
  action: ALLOW
```

This too breaks the L7 AuthorizationPolicy (503 errors).  

Is this documented somewhere?

**Comment by ilrudie** [comment]
By default there is no "automatically allow traffic from a waypoint" functionality. There is a feature for this `PILOT_AUTO_ALLOW_WAYPOINT_POLICY` though. You could also apply your own policy to allow the waypoint to reach your WL.

Side note, running a curl from the ingress gateway pod is not the same as using the ingress gateway. When using the ingress gateway, it sends traffic to a workload directly and bypasses the waypoint. This was done to prevent double-policy applies at the ingress and the waypoint.

**Reply by ca-scribner** [reply]
ty, I'll check out `PILOT_AUTO_ALLOW_WAYPOINT_POLICY`!  

So if I understand correctly then, what was happening above was that there was no AP allowing `waypoint->productpage` on L4, so ztunnel was blocking the second hop of the `pod with sa:gateway -> waypoint -> productpage`?  And what I could have done was add a second L4 policy to allow `waypoint -> productpage`?

What I'm worried about with adding the second policy is, as far as I can tell, it allows traffic from everyone.  For example, if I have the following:
* productpage (target for my traffic)
* a waypoint with `sa:waypoint`
* `pod:curl1` with `sa:curl1`
* `pod:curl2` with `sa:curl2`

and I apply the following `AuthorizationPolicies`

* a default `allow-nothing` policy
* a policy allowing `sa:curl1` to talk to `productpage`
* a policy allowing `sa:waypoint` to talk to `productpage`

<details>

```yaml
# Allow nothing by default, just to be really explicit about how default communication is disabled
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-nothing
spec:

---

# Allow from `curl` SA to the productpage
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-curl-to-productpage-l4
spec:
  action: ALLOW
  selector:
    matchLabels:
      app: productpage
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/bookinfo-1/sa/curl

---

# Allow from `waypoint` SA to the productpage
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-waypoint-to-productpage-l4
spec:
  action: ALLOW
  selector:
    matchLabels:
      app: productpage
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/bookinfo-1/sa/waypoint
```

</details>

what happens is that, because all traffic will flow through `waypoint`, both `curl1` **and** `curl2` even though I only want `curl1`'s traffic.  This is because all traffic to `productpage` is forced through `waypoint`, and all `waypoint` traffic is allowed to `productpage`

Is there something else I'm missing here?  ty!
