### DISCUSSION TITLE
Unable to filter OpenTelemetry access logs stored in Grafana Loki

### DISCUSSION THREAD

**Discussion by phmcder** [istio/istio#53146] [Q&A]
Hi All

After a hard battle configuring all the aspects of OpenTelemrtry logs collection, I am successfully getting Istio Access Logs to show in my Grafana Loki server.  

However, when I look at the logs in Grafana, Loki reports only `service_name` as a label, and the only selectable value for that is  `unknown_service`. Using this filter, I can see all the access logs Istio produces. I'm going to be unable to filter these logs if can't get Loki to index on some of the log labels. I haven't made any configuration changes in Loki, so It is using the default mappings listed here https://grafana.com/docs/loki/latest/send-data/otel/#format-considerations 

As far as I can understand, all I need to do is add the attributes from the above list to the list of labels for `envoyOtelAls` like this
```
extensionProviders:
    - name: otel
      envoyOtelAls:
        service: ${OTEL_COLLECTOR_URL}
        port: 4317
        logFormat:
          labels:
            k8.pod.name: "%ENVIRONMENT(POD_NAME)%"
            service.namespace: "%ENVIRONMENT(POD_NAMESPACE)%"
            k8s.cluster,name: "%ENVIRONMENT(ISTIO_META_CLUSTER_ID)%"
            mesh: "%ENVIRONMENT(ISTIO_META_MESH_ID)%"
            service.name: "%ENVIRONMENT(ISTIO_META_WORKLOAD_NAME)%.%ENVIRONMENT(POD_NAMESPACE)%"
```

When I do this, I see the following in Grafana
![image](https://github.com/user-attachments/assets/72cb814a-41f0-4a9a-af0f-65d800ad3cec)

Digging deeper, I can't influence Loki's labels using OpenTelemetry attributes. Those values I want to use as labels need to be passed in the resource section of the OpenTelemetry message. However, after spending days digging though Istio and Envoy code I can't see a way of doing this.

Can anyone point me to what I am missing or verify this is a potential missing feature in Istio?

I'm thinking it might have something to do with configuring the `resource_attributes` of this object 
https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/access_loggers/open_telemetry/v3/logs_service.proto#extensions-access-loggers-open-telemetry-v3-opentelemetryaccesslogconfig

**Comment by zirain** [comment]
did you try our loki sample https://github.com/istio/istio/tree/06cb3abeea2eee6466323d466e547ddb0d643244/samples/open-telemetry/loki?

**Reply by phmcder** [reply]
Hi @zirain 

Thanks for getting back. In that example, you are using the Loki Opentelemetry exports, which Loki is trying to move away from [link](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/lokiexporter/README.md). They prefer data is sent from the OpenTelemetry collector using the otlp exporter.

I have just managed to find a work around that has confirmed my investigation.  The following OpenTelemetry configuration uses the `transfrom` processor to modify the resources of a log. If the resource attribute is missing it will be added via the filter. This has confirmed that Istio is not sending any OpenTelemetry logs with these Resource Attributes. With the configuration, Loki is now showing labels and I can filter with them.

```
    processors:
      transform/loki:
        error_mode: ignore
        log_statements:
          - context: log
            statements:
              - set(resource.attributes["service.name"], attributes["service"]) where resource.attributes["service.name"] == "nil"
              - set(resource.attributes["k8s.cluster.name"], attributes["cluster"]) where resource.attributes["k8s.cluster.name"] == "nil"
              - set(resource.attributes["k8s.pod.name"], attributes["pod"]) where resource.attributes["k8s.pod.name"] == "nil"
              - set(resource.attributes["k8s.namespace.name"], attributes["namespace"]) where resource.attributes["k8s.cluster.name"] == "nil"

    exporters:
      otlphttp/loki:
        endpoint: http://loki.loki.svc.cluster.local:3100/otlp
        tls:
          insecure: true


    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [transform/loki]
          exporters: [otlphttp/loki]
```

**Reply by phmcder** [reply]
Here is my Istio configuration for reference

```
extensionProviders:
    - name: otel
      envoyOtelAls:
        service: ${OTEL_COLLECTOR_URL}
        port: 4317
        logFormat:
          labels:
            pod: "%ENVIRONMENT(POD_NAME)%"
            namespace: "%ENVIRONMENT(POD_NAMESPACE)%"
            cluster: "%ENVIRONMENT(ISTIO_META_CLUSTER_ID)%"
            mesh: "%ENVIRONMENT(ISTIO_META_MESH_ID)%"
            service: "%ENVIRONMENT(ISTIO_META_WORKLOAD_NAME)%.%ENVIRONMENT(POD_NAMESPACE)%"
```
