### DISCUSSION TITLE
issues with lenvoy filter  local rate limit for routes

### DISCUSSION THREAD

**Discussion by ogolan-ig** [istio/istio#53166] [Q&A]
hi, 

im trying to create a local rate limit. i want my route to have different rate limit than the other routes. the rate limits of 10 seems to work for all the routes even for the route i set rate limit of 3.

what am i missing?
 
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: billing-api-envoy-filter-rate-limit
  namespace: stage  
spec:
  workloadSelector:
    labels:
      app: billing-api 
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            stat_prefix: http_local_rate_limit
            token_bucket:
              max_tokens: 10 
              tokens_per_fill: 10
              fill_interval: 30s  
            filter_enabled:
              runtime_key: local_rate_limit_enabled
              default_value:
                numerator: 100
                denominator: HUNDRED
            filter_enforced:
              runtime_key: local_rate_limit_enforced
              default_value:
                numerator: 100
                denominator: HUNDRED
            descriptors:
              - entries:
                  - key: path
                    value: /customer/allCustomers
                token_bucket:
                  max_tokens: 3  
                  tokens_per_fill: 3
                  fill_interval: 1m 

```

**Comment by zirain** [comment]
did you set up ratelimit action on route? a full configuration will help to debug.

**Reply by ogolan-ig** [reply]
im not sure what you mean so im guessing the config i shard is not enought for the rate limit? it is the full envoy filter config used right now.  i thought this part is the rate limit action :

```
 descriptors:
              - entries:
                  - key: path
                    value: /customer/allCustomers
                token_bucket:
                  max_tokens: 3  
                  tokens_per_fill: 3
                  fill_interval: 1m 
```

im also adding the virtual service config in case it will help 

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: billing-api-ingress
  namespace: stage
  annotations:
    external-dns.alpha.kubernetes.io/target: alb.stage.com
spec:
  gateways:
    - istio-system/ingressgateway
    - istio-system/ingressgateway-private
  hosts:
    - billingapi.stage.com
  http:
    - match:
        - gateways:
            - istio-system/ingressgateway
        - uri:
            prefix: /
        - headers:
            host:
              exact: billingapi.stage.com
      retries:
        attempts: 0
      route:
        - destination:
            host: billing-api-service.stage.svc.cluster.local
            port:
              number: 80
          weight: 100
```
