### DISCUSSION TITLE
Visualizing service-to-service traffic

### DISCUSSION THREAD

**Discussion by CC007** [istio/istio#53179] [Q&A]
Hardware: Raspberry Pi 4B (8x) 
Arch: arm64
OS version: Ubuntu 22.04.4 LTS 
K8S version: k3s v1.30.3+k3s1 
Istio version: rancher-istio 104.4.0+up1.22.1 
Kiali version: v1.86.0

I was trying out the bookinfo demo, but I ran into some issues.

Here is my config
[bookinfo.zip](https://github.com/user-attachments/files/17035582/bookinfo.zip)

I also have this configured:
```yaml
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: istio-system
spec:
  mtls:
    mode: STRICT
```

When this is configured, the website is available and it correctly routes traffic to reviews v1, as configured in the virtual service.
When I look in Kiali though, I see this: 
![afbeelding](https://github.com/user-attachments/assets/f855f428-f456-47c5-af77-2c92fe59f4fd)

I only see the traffic from the ingress to the productpage, not any traffic between the productpage and reviews or details.

Also, I don't see the mTLS icon ![afbeelding](https://github.com/user-attachments/assets/e83d8083-6ae0-4c5c-bfe1-6afa4ee7d16b) on the traffic that I used to see on my routes when I used Istio 2 years ago. (Yes I did enable to show security)

Is there anything that I'm missing?
