### DISCUSSION TITLE
LoadBalancer, consistentHash, subsets

### DISCUSSION THREAD

**Discussion by rblesk-hms** [istio/istio#53248] [Q&A]
I'm trying to implement such a thing as using **(loadBalancer: consistentHash: httpCookie) + (Routes+weights)**. This means that besides the basic ability to bind a client to a specific pod, it would be possible to use weights as well. For example, we have a version of the application **v1**, to which we direct **90 %** of the schedule and there is a version **v2** to which we direct **10 %** of the schedule. And if the client has already got to a specific version of the application and a specific pod, then in the future all requests of this client should get to the same pod, despite the weight. If you don't use **“match”** then the **route+weight+subset+consistentHash** bundle doesn't work as expected and only the **route+weight** mechanism works and **consistentHash** doesn't work.
The following logic is used in the example below: if the client does not have a cookie header containing the application version X-App-Version=v1/X-App-Version=v2, we set the cookie according to the weight distribution and then follow the subset chosen by the algorithm. In DestinationRule I have specified some loadBalancer to understand how the algorithm works.
Different httpCookie names are written intentionally to understand which rule is triggered. It turns out that two rules are triggered at once
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: my-app
  namespace: default
spec:
  host: my-app.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: "sticky-M-session"
          ttl: "0s"
  subsets:
    - name: v1
      labels:
        version: v1
      trafficPolicy:
        loadBalancer:
          consistentHash:
            httpCookie:
              name: "sticky1-session"
              ttl: "0s"
    - name: v2
      labels:
        version: v2
      trafficPolicy:
        loadBalancer:
          consistentHash:
            httpCookie:
              name: "sticky2-session"
              ttl: "0s"
```

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: myapp-virtualservice
  namespace: default
spec:
  hosts:
    - "*"
  gateways:
    - default/myapp-gateway
  http:
    - name: "route-cookie-v1"
      match:
      - headers:
          cookie:
            regex: ".*X-App-Version=v1.*"
      route:
      - destination:
          host: my-app
          subset: v1
        weight: 100
    - name: "route-cookie-v2"
      match:
      - headers:
          cookie:
            regex: ".*X-App-Version=v2.*"
      route:
      - destination:
          host: my-app
          subset: v2
        weight: 100

    - route:
      - destination:
          host: my-app
          subset: v1
        weight: 90
        headers:
          response:
            add:
              set-cookie: "X-App-Version=v1"
      - destination:
          host: my-app
          subset: v2
        weight: 10
        headers:
          response:
            add:
              set-cookie: "X-App-Version=v2"
```

 If we run curl -v http://localhost:8080 we get two set-cookie responses, although logically we should get only one. 

> * Host localhost:8080 was resolved.
> * IPv6: ::1
> * IPv4: 127.0.0.1
> *   Trying [::1]:8080...
> * Connected to localhost (::1) port 8080
> > GET / HTTP/1.1
> > Host: localhost:8080
> > User-Agent: curl/8.7.1
> > Accept: */*
> > 
> * Request completely sent off
> < HTTP/1.1 200 OK
> < set-cookie: user-session=user-1727099602013725012; Path=/
> < date: Mon, 23 Sep 2024 13:53:22 GMT
> < content-length: 82
> < content-type: text/plain; charset=utf-8
> < x-envoy-upstream-service-time: 0
> < server: istio-envoy
> < **set-cookie: sticky1**-session="bfd00c2b19cd509c"; HttpOnly
> < **set-cookie: sticky2**-session="bfd00c2b19cd509c"; HttpOnly
> < set-cookie: X-App-Version=v1
> < 
> Hello, user-1727099602013725012! You are served by pod my-app-v1-7558656b5c-mz6qb

This entails that if the first request comes to one subset, then the second and subsequent ones go to another (i.e. glue), but it is received from the second request, and is expected that from the first as the mechanism works consistentHash if you do not use weights.
Example of run script with 
```
#!/usr/bin/env bash

URL="http://localhost:8080/"
rm store-here.txt  # clean cookie
for i in {1..9}
do
  curl -s -c store-here.txt -b store-here.txt $URL
done
```

Hello, user-1727098642633092878! You are served by pod my-app-v1-7558656b5c-mz6qb
Hello, user-1727098642633092878! You are served by pod my-app-v1-7558656b5c-9nrq9
Hello, user-1727098642633092878! You are served by pod my-app-v1-7558656b5c-9nrq9
Hello, user-1727098642633092878! You are served by pod my-app-v1-7558656b5c-9nrq9
Hello, user-1727098642633092878! You are served by pod my-app-v1-7558656b5c-9nrq9
Hello, user-1727098642633092878! You are served by pod my-app-v1-7558656b5c-9nrq9
Hello, user-1727098642633092878! You are served by pod my-app-v1-7558656b5c-9nrq9
Hello, user-1727098642633092878! You are served by pod my-app-v1-7558656b5c-9nrq9
Hello, user-1727098642633092878! You are served by pod my-app-v1-7558656b5c-9nrq9

If weights are redistributed to 100/0 for example, then only one subset works and it can be seen from the response.

> * Request completely sent off
> < HTTP/1.1 200 OK
> < set-cookie: user-session=user-1727099856343234902; Path=/
> < date: Mon, 23 Sep 2024 13:57:36 GMT
> < content-length: 82
> < content-type: text/plain; charset=utf-8
> < x-envoy-upstream-service-time: 0
> < server: istio-envoy
> < set-cookie: sticky1-session="51b9284c680fc81a"; HttpOnly
> < set-cookie: X-App-Version=v1
> < 

Anticipating the question what happens if you remove loadBalancer in each subset. There will be the following, two answers to the cookie setting.

> * Request completely sent off
> < HTTP/1.1 200 OK
> < set-cookie: user-session=user-1727101986557327953; Path=/
> < date: Mon, 23 Sep 2024 14:33:06 GMT
> < content-length: 82
> < content-type: text/plain; charset=utf-8
> < x-envoy-upstream-service-time: 0
> < server: istio-envoy
> < set-cookie: sticky-M-session="ea7229f89b9c0c5e"; HttpOnly
> < set-cookie: sticky-M-session="ea7229f89b9c0c5e"; HttpOnly
> < set-cookie: X-App-Version=v1
