### DISCUSSION TITLE
EnvoyFilter with lua script on ountbound traffic does not apply to HTTPS requests

### DISCUSSION THREAD

**Discussion by zclyne** [istio/istio#53253] [Q&A]
Hi Istio community,

I am writing an `EnvoyFilter` which runs a lua script to patch a custom HTTP header to all outbound traffic. The same code works well with outbound HTTP requests but it seems for HTTPS requests the lua script is not executed at all.

Here's my `EnvoyFilter` definition:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: patch-created-by-header
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      test-label: "true"
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_OUTBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.lua
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
          inlineCode: |
            function envoy_on_request(request_handle)
              request_handle:logInfo("outbound envoyfilter executing...")
              -- local created_by = os.getenv("CREATED_BY")
              if created_by ~= nil then
                request_handle:logInfo("created_by: "..created_by)
                request_handle:headers():add("notebook_user", created_by)
              end
            end
```

The reason I doubt the lua script is not executed is because for outbound HTTPS traffic, the `"outbound envoyfilter executing..."` log line is even not printed out in the istio sidecar container's log.

I have done extensive searching online but still cannot figure out the reason why it works well with HTTP but not HTTPS. Can anybody please take a look? Thanks!
