### DISCUSSION TITLE
AuthorizationPolicy CUSTOM action/provider issue with OpenTelemetry Collector

### DISCUSSION THREAD

**Discussion by wmashal** [istio/istio#53280] [Q&A]
Hi,

I have an OpenTelemetry collector sending traces to Jaeger. However, when I disable the Istio sidecar injection in these pods, the traces are successfully reported in the Jaeger UI. But when I enable the sidecars, the trace reporting stops working.

Additionally, I have implemented the following authorization policy to connect the Jaeger UI with our IDP through the OAuth-proxy. Despite this, I am still facing the error: "RBAC: Access denied" in the Jaeger UI.

**The Flows:**

With the below yamls together > I am still facing the error: "RBAC: Access denied" in the Jaeger UI > opentelemetry tarces exporting to jaeger **not working**

Sidecras Inject Enabled > delete jaeger-allow-opentelemetry AuthorizationPolicy > Add jaeger-auth-policy and  jaeger-request-auth  >The integration with the IDP through oauth2-proxy provider **working** > opentelemetry tarces exporting to jaeger **not working**

Sidecras Inject Disabled > delete jaeger-allow-opentelemetry AuthorizationPolicy > Add jaeger-auth-policy and  jaeger-request-auth  >The integration with the IDP through oauth2-proxy provider **not working** > opentelemetry tarces exporting to jaeger **working**

**Note : the jaeger pod deployed in the same namespace with opentelmetry collector**

Whats wrong with my configurations ? Is there any conflict ?

My configurations:

```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: jaeger-auth-policy
  namespace: monitoring-prometheus
spec:
  action: CUSTOM
  provider:
    name: oauth2-proxy
  rules:
  - {}
  selector:
    matchLabels:
      app: jaeger

```

```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: jaeger-allow-opentelemetry
  namespace: monitoring-prometheus
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces:
        - monitoring-prometheus
  - to:
    - operation:
        ports:
        - "14250"
        - "14268"
        - "4317"
        - "4318"
  selector:
    matchLabels:
      app: jaeger

```

```yaml
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: jaeger-request-auth
  namespace: monitoring-prometheus
spec:
  selector:
    matchLabels:
      app: jaeger
  jwtRules:
    - issuer: <my jwt issuer>
      jwksUri: <my jwt issuer url>

```
