### DISCUSSION TITLE
[OAuth2] Failure to get token from login.microsoftonline.com (Azure AD), returns 503

### DISCUSSION THREAD

**Discussion by ygenie418** [istio/istio#53430] [General]
I'm trying to use the OAuth2 filter to authenticate with Azure AD. The initial redirect to the authorization endpoint works as expected, as well as the callback redirect. But when the callback is being processed by the filter, the request to the token endpoint gets a 503 response, and the filter then fails with a 401 response. 
```
httpbin-c6b85f985-zslgh istio-proxy 'location', 'https://login.microsoftonline.com/TENANT_ID/oauth2/v2.0/authorize?client_id=CLIENT_ID&redirect_uri=https%3A%2F%2FMYDOMAIN%2Foauth2%2Fcallback&response_type=code&scope=openid%20profile%20email&state=https%3A%2F%2FMYDOMAIN%2F'
httpbin-c6b85f985-zslgh istio-proxy [2024-10-04T13:37:04.248Z] "GET / HTTP/1.1" 302 - oauth.missing_credentials - "-" 0 0 0 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36" "56b28059-6984-932f-988b-eaaa80e155e0" "MYDOMAIN" "-" inbound|80|| - 10.31.210.77:80 10.31.201.185:49514 outbound_.8000_._.httpbin.devops.svc.cluster.local -
httpbin-c6b85f985-zslgh istio-proxy ':path', '/oauth2/callback?code=<CODE>'
httpbin-c6b85f985-zslgh istio-proxy 2024-10-04T13:37:05.540894Z debug   envoy oauth2 external/envoy/source/extensions/filters/http/oauth2/oauth_client.cc:58    Dispatching OAuth request for access token.        thread=28
httpbin-c6b85f985-zslgh istio-proxy 2024-10-04T13:37:05.541213Z debug   envoy oauth2 external/envoy/source/extensions/filters/http/oauth2/oauth_client.cc:87    Oauth response code: 503   thread=28
httpbin-c6b85f985-zslgh istio-proxy 2024-10-04T13:37:05.541215Z debug   envoy oauth2 external/envoy/source/extensions/filters/http/oauth2/oauth_client.cc:88    Oauth response body: upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: immediate connect error: Network is unreachable        thread=28
httpbin-c6b85f985-zslgh istio-proxy 'referer', 'https://MYDOMAIN/oauth2/callback?code=<CODE>'
httpbin-c6b85f985-zslgh istio-proxy 'location', 'https://login.microsoftonline.com/TENANT_ID/oauth2/v2.0/authorize?client_id=CLIENT_ID&redirect_uri=https%3A%2F%2FMYDOMAIN%2Foauth2%2Fcallback&response_type=code&scope=openid%20profile%20email&state=https%3A%2F%2FMYDOMAIN%2Ffavicon.ico'
httpbin-c6b85f985-zslgh istio-proxy [2024-10-04T13:37:05.540Z] "GET /oauth2/callback?code=<CODE> HTTP/1.1" 401 -  - "-" 0 18 0 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36" "b16bcfd5-0616-9183-ad27-271de24665d6" "MYDOMAIN" "-" inbound|80|| - 10.31.210.77:80 10.31.201.185:49514 outbound_.8000_._.httpbin.devops.svc.cluster.local -
httpbin-c6b85f985-zslgh istio-proxy [2024-10-04T13:37:05.717Z] "GET /favicon.ico HTTP/1.1" 302 - oauth.missing_credentials - "-" 0 0 0 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36" "0b8e360c-a942-9c0c-877e-77a792a21f21" "MYDOMAIN" "-" inbound|80|| - 10.31.210.77:80 10.31.201.185:49514 outbound_.8000_._.httpbin.devops.svc.cluster.local -
```

Seems it can't connect to Azure to fetch the token:
```
upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: immediate connect error: Network is unreachable 
```

And thus it fails with a `OAuth flow failed.`

filter config
```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: httpbin-auth
spec:
  workloadSelector:
    labels:
      app: httpbin
  configPatches:
  - applyTo: CLUSTER
    match:
      cluster:
        service: oauth
    patch:
      operation: ADD
      value:
        name: oauth
        connect_timeout: 10s
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: oauth
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: login.microsoftonline.com
                    port_value: 443
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
            sni: login.microsoftonline.com
        type: LOGICAL_DNS
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.jwt_authn
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.oauth2
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.oauth2.v3.OAuth2
          config:
            token_endpoint:
              cluster: oauth
              uri: https://login.microsoftonline.com/TENANT_ID/oauth2/v2.0/token/
              timeout: 10s
            authorization_endpoint: https://login.microsoftonline.com/TENANT_ID/oauth2/v2.0/authorize
            redirect_uri: https://%REQ(:authority)%/oauth2/callback
            redirect_path_matcher:
              path:
                exact: /oauth2/callback
            signout_path:
              path:
                exact: /signout
            credentials:
              client_id: CLIENT_ID
              token_secret:
                name: token
                sds_config:
                  path: "/etc/istio/config/token-secret.yaml"
              hmac_secret:
                name: hmac
                sds_config:
                  path: "/etc/istio/config/hmac-secret.yaml"
            auth_scopes:
            - openid
            - profile
            - email
            forward_bearer_token: true
            # Bypass auth proxy for health check
            pass_through_matcher:
            - name: :path
              exact_match: /healthz/ready
            - name: authorization
              prefix_match: Bearer
```

where
```yaml
# /etc/istio/config/hmac-secret.yaml
resources:
- "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
  name: hmac
  generic_secret:
    secret:
      # generated using `head -c 32 /dev/urandom | base64`
      inline_bytes: QBrUNBG/eB9hQJR4tZbcel7IzUImKgrTwWn3ZyqJZk8=
```

```yaml
# /etc/istio/config/token-secret.yaml
resources:
  - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
    name: token
    generic_secret:
      secret:
        inline_string: CLIENT_SECRET>
```

I understand this version of Envoy is archived, but wondering if something obvious stands out before we go the upgrade route and test again.

[optional *Referenced Links*:]
1. https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/oauth2_filter
2. https://github.com/envoyproxy/envoy/issues/20179
3. https://github.com/istio/istio/issues/43251

```
$ istioctl version
client version: 1.17.5
control plane version: 1.17.5
data plane version: 1.17.5 (11 proxies)
$ kubectl version
Client Version: v1.26.15
Kustomize Version: v4.5.7
Server Version: v1.25.16-eks-a18cd3a
```
