### DISCUSSION TITLE
Authorization Default Deny Pattern

### DISCUSSION THREAD

**Discussion by mtcolman** [istio/istio#53455] [General]
Hi, I'm a little confused by a couple of Istio pages, plus my own experience using Istio and wondered if someone could provide some clarity (which may in turn result in the need to modify docs).

The [Safer Authorization Policy Patterns page](https://istio.io/latest/docs/ops/best-practices/security/#use-default-deny-patterns) says:

>Use default-deny patterns
>
>We recommend you define your Istio authorization policies following the default-deny pattern to enhance your cluster’s security posture. The default-deny authorization pattern means your system denies all requests by default, and you define the conditions in which the requests are allowed. In case you miss some conditions, traffic will be unexpectedly denied, instead of traffic being unexpectedly allowed. The latter typically being a security incident while the former may result in a poor user experience, a service outage or will not match your SLO/SLA.
>
>For example, in the [authorization for HTTP traffic task](https://istio.io/latest/docs/tasks/security/authorization/authz-http/), the authorization policy named allow-nothing makes sure all traffic is denied by default. From there, other authorization policies allow traffic based on specific conditions.

and the link through to the authorization of HTTP traffic task shows:

>Run the following command to create a allow-nothing policy in the default namespace. The policy doesn’t have a selector field, which applies the policy to every workload in the default namespace. The spec: field of the policy has the empty value {}. That value means that no traffic is permitted, effectively denying all requests.
>```
>$ kubectl apply -f - <<EOF
>apiVersion: security.istio.io/v1
>kind: AuthorizationPolicy
>metadata:
>  name: allow-nothing
>  namespace: default
>spec:
>  {}
>EOF
>```

Alongside this, the [Authorization Policy page](https://istio.io/latest/docs/reference/config/security/authorization-policy/) says:

>Istio Authorization Policy enables access control on workloads in the mesh.
>
>Authorization policy supports CUSTOM, DENY and ALLOW actions for access control. When CUSTOM, DENY and ALLOW actions are used for a workload at the same time, the CUSTOM action is evaluated first, then the DENY action, and finally the ALLOW action. The evaluation is determined by the following rules:
>
>    1. If there are any CUSTOM policies that match the request, evaluate and deny the request if the evaluation result is deny.
>    2. If there are any DENY policies that match the request, deny the request.
>    3. If there are no ALLOW policies for the workload, allow the request.
>    4. If any of the ALLOW policies match the request, allow the request.
>    5. Deny the request.

====

Following the default deny pattern guidance, I created a DENY all policy in a namespace and then created a scoped ALLOW policy to permitted a workload to receive from another namespace, with a certain principal, specific method, path and port. The traffic was denied. I then removed the deny all and the traffic flow was permitted. When I reapplied the deny all, I once again get failed/blocked comms.

The events I experienced align with the **Authorization Policy** page description that any DENY policies matching the request will cause it to be denied and this is evaluated prior to any ALLOW policies. However, the **Safer Authorization Policy Patterns** page appears to completely contradict this.

Am I misreading something, and what is the expected behaviour?

Thanks,

Matt

**Comment by husnialhamdani** [comment]
Maybe you could also include your policies here

**Comment by mtcolman** [comment]
Hi @husnialhamdani the policies are:
```
# deny all
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
 name: allow-nothing
 namespace: destination-b
spec:
  action: DENY
  rules:
  - {}
```

and
```
# permit specific flow
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: source-a-to-destination-b
  namespace: destination-b
spec:
  selector:
    matchLabels:
      app: destination-app-b
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
          - "cluster.local/ns/source-a/sa/source-app-a"
    to:
    - operation:
        methods: ["GET"]
        paths: ["/resources/*"]
        ports: ["8080"]
```

**Reply by m8-t** [reply]
Afaik (I am also pretty new at istio :)) your `allow-nothing` policy is wrong. [This](https://istio.io/latest/docs/reference/config/security/authorization-policy/) page states this:

> For example, the following authorization policy applies to all workloads in namespace foo. It allows nothing and effectively denies all requests to workloads in namespace foo.

```
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
 name: allow-nothing
 namespace: foo
spec:
  {}
```

and furthermore:

> The following authorization policy allows all requests to workloads in namespace foo.

```
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
 name: allow-all
 namespace: foo
spec:
 rules:
 - {}
 ```

You also use `DENY` in your default deny and use `- {}` under `rules` while the documentation says just use:

```
spec:
  {}
```
and ommit any `action`.

This works like a charm at my setup and the bookinfo demo.

Here are my AuthorizationPolicies as an example:

```
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: default-deny-istio
  namespace: bookinfo
spec: {}
```

and as an example for the bookinfo demo I tried this and it worked:

```
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-productpage-to-details
  namespace: bookinfo
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/bookinfo/sa/bookinfo-productpage
    to:
    - operation:
        ports:
        - "9080"
  selector:
    matchLabels:
      app: details
```

Hope this helps and someone could explain the default deny policy more detailed.

cheers

**Comment by mtcolman** [comment]
@dan-m8t - I finally managed to get this working last night after a bit of head-scratching. I had misread the [authorization for HTTP traffic task](https://istio.io/latest/docs/tasks/security/authorization/authz-http/) page, and added in a deny when I didn't need to.

Rereading it, I can see that the purpose is to create an ALLOW rule; either via `spec.action` = ALLOW, or by omitting `spec.action` altogether as it defaults to ALLOW if not present (as per [here](https://istio.io/latest/docs/reference/config/security/authorization-policy/#AuthorizationPolicy)):

>Optional. The action to take if the request is matched with the rules. Default is ALLOW if not specified.

Which means that I needed to use:
```
# deny all
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
 name: allow-nothing
 namespace: destination-b
spec:
  action: ALLOW
  rules:
  - {}
```

and likewise, the same outcome but without specifying the action:
```
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
 name: allow-nothing
 namespace: destination-b
spec:
 {}
```

And likewise, `spec.rules` is optional, as per [here](https://istio.io/latest/docs/reference/config/security/authorization-policy/#AuthorizationPolicy):

>Optional. A list of rules to match the request. A match occurs when at least one rule matches the request.
>
> If not set, the match will never occur. This is equivalent to setting a default of deny for the target workloads if the action is ALLOW.

The concept I had struggled with was the fact it's "ALLOW nothing" instead of "DENY everything".
