### DISCUSSION TITLE
Rate limiting with EnvoyFilter not working when using JWT claim extraction in Istio

### DISCUSSION THREAD

**Discussion by stanyzra** [istio/istio#53527] [Q&A]
I have the following manifest that extracts the "userId" claim from my JWT request and put it in a header called "x-jwt-userid".

```yaml
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: "jwt-extractor"
  namespace: collection-api-dev
spec:
  selector:
    matchLabels:
      app: node-api
  jwtRules:
    - issuer: <ISSUER>
      jwks: |
        {
          "keys": [
            {
              "kty": "oct",
              "k": <JWT_SECRET>
              "alg": "HS256"            
            }
          ]
        }
      forwardOriginalToken: true
      fromHeaders:
        - name: "authorization"
          prefix: "Bearer "
      outputClaimToHeaders:
        - header: "x-jwt-userid"
          claim: "userId"

---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: require-jwt
  namespace: collection-api-dev
spec:
  selector:
    matchLabels:
      app: node-api
  action: ALLOW
  rules:
    - {}
```

So, when I check into my API logs, I see that the "x-jwt-userid" header is present with correct value. That header can't been seen when I use something like browser DevTools or curl with "-v" flag. Now, here's another manifest that apply the rate limiting using EnvoyFilters, [Rate Limit](https://github.com/envoyproxy/ratelimit) by Envoy and Redis.

The configuration file for rate limiting:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
  namespace: collection-api-dev
data:
  ratelimit.yaml: |
    domain: node-api
    descriptors:
      - key: x-jwt-userid
        rate_limit:
          unit: minute
          requests_per_unit: 5
```

And the EnvoyFilters:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ratelimit-filter
  namespace: collection-api-dev
spec:
  workloadSelector:
    labels:
      app: node-api
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.ratelimit
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
            domain: node-api
            failure_mode_deny: true
            timeout: 10s
            rate_limit_service:
              grpc_service:
                envoy_grpc:
                  cluster_name: outbound|8081||rate-limit-service.collection-api-dev.svc.cluster.local
                  authority: rate-limit-service.collection-api-dev.svc.cluster.local
              transport_api_version: V3
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ratelimit-filter-svc
  namespace: collection-api-dev
spec:
  workloadSelector:
    labels:
      app: node-api
  configPatches:
    - applyTo: VIRTUAL_HOST
      match:
        context: SIDECAR_INBOUND
        routeConfiguration:
          vhost:
            name: ""
            route:
              action: ANY
      patch:
        operation: MERGE
        value:
          rate_limits:
            - actions:
                - request_headers:

                    header_name: "x-jwt-userid" 
                    descriptor_key: "x-jwt-userid" 
```

That didn't worked and when I check the rate limiting pod logs, nothing happens. I've tested with another header that is always present in our requests and it worked well, so my guess is that the "jwt-extractor" put the "x-jwt-userid" after the rate limit filter. In that way, the filter can't get the header and nothing happens because the "x-jwt-userid" isn't present by the time that the filters do it's work. Is there any way to make the filter work after the "x-jwt-userid" header is available?

**Comment by zirain** [comment]
can you share the config dump, make sure the ratelimit placed after the JWT filter.

**Reply by stanyzra** [reply]
Hi, sorry for the late response. What config dump are you talking about? And how do I make sure the ratelimit is placed after the JWT filter?

**Reply by zirain** [reply]
istioctl pc l -n <pod_namepace> <pod_name> -o json/yaml

**Reply by stanyzra** [reply]
I've runned this command in my ratelimit pod and the output file has 21140 lines in it, should I send you the entire config file?

**Reply by zirain** [reply]
you can add `--port int         Filter listeners by Port field` to shorten it

**Reply by stanyzra** [reply]
Well, I've runned `istioctl pc l --port 8081 -n collection-api-dev rate-limit-service-7fdddb6744-dq7n6 -o yaml` and got the following config file:

```yaml
- address:
    socketAddress:
      address: 0.0.0.0
      portValue: 8081
  bindToPort: false
  continueOnListenerFiltersTimeout: true
  defaultFilterChain:
    filterChainMatch: {}
    filters:
    - name: istio.stats
      typedConfig:
        '@type': type.googleapis.com/stats.PluginConfig
    - name: envoy.filters.network.tcp_proxy
      typedConfig:
        '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
        accessLog:
        - name: envoy.access_loggers.file
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
            logFormat:
              jsonFormat:
                authority: '%REQ(:AUTHORITY)%'
                bytes_received: '%BYTES_RECEIVED%'
                bytes_sent: '%BYTES_SENT%'
                connection_termination_details: '%CONNECTION_TERMINATION_DETAILS%'
                downstream_local_address: '%DOWNSTREAM_LOCAL_ADDRESS%'
                downstream_remote_address: '%DOWNSTREAM_REMOTE_ADDRESS%'
                duration: '%DURATION%'
                method: '%REQ(:METHOD)%'
                path: '%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%'
                protocol: '%PROTOCOL%'
                request_id: '%REQ(X-REQUEST-ID)%'
                requested_server_name: '%REQUESTED_SERVER_NAME%'
                response_code: '%RESPONSE_CODE%'
                response_code_details: '%RESPONSE_CODE_DETAILS%'
                response_flags: '%RESPONSE_FLAGS%'
                route_name: '%ROUTE_NAME%'
                start_time: '%START_TIME%'
                upstream_cluster: '%UPSTREAM_CLUSTER%'
                upstream_host: '%UPSTREAM_HOST%'
                upstream_local_address: '%UPSTREAM_LOCAL_ADDRESS%'
                upstream_service_time: '%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%'
                upstream_transport_failure_reason: '%UPSTREAM_TRANSPORT_FAILURE_REASON%'
                user_agent: '%REQ(USER-AGENT)%'
                x_forwarded_for: '%REQ(X-FORWARDED-FOR)%'
              jsonFormatOptions:
                sortProperties: true
            path: /dev/stdout
        cluster: PassthroughCluster
        statPrefix: PassthroughCluster
    name: PassthroughFilterChain
  filterChains:
  - filterChainMatch:
      applicationProtocols:
      - http/1.1
      - h2c
      transportProtocol: raw_buffer
    filters:
    - name: envoy.filters.network.http_connection_manager
      typedConfig:
        '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
        accessLog:
        - name: envoy.access_loggers.file
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
            logFormat:
              jsonFormat:
                authority: '%REQ(:AUTHORITY)%'
                bytes_received: '%BYTES_RECEIVED%'
                bytes_sent: '%BYTES_SENT%'
                connection_termination_details: '%CONNECTION_TERMINATION_DETAILS%'
                downstream_local_address: '%DOWNSTREAM_LOCAL_ADDRESS%'
                downstream_remote_address: '%DOWNSTREAM_REMOTE_ADDRESS%'
                duration: '%DURATION%'
                method: '%REQ(:METHOD)%'
                path: '%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%'
                protocol: '%PROTOCOL%'
                request_id: '%REQ(X-REQUEST-ID)%'
                requested_server_name: '%REQUESTED_SERVER_NAME%'
                response_code: '%RESPONSE_CODE%'
                response_code_details: '%RESPONSE_CODE_DETAILS%'
                response_flags: '%RESPONSE_FLAGS%'
                route_name: '%ROUTE_NAME%'
                start_time: '%START_TIME%'
                upstream_cluster: '%UPSTREAM_CLUSTER%'
                upstream_host: '%UPSTREAM_HOST%'
                upstream_local_address: '%UPSTREAM_LOCAL_ADDRESS%'
                upstream_service_time: '%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%'
                upstream_transport_failure_reason: '%UPSTREAM_TRANSPORT_FAILURE_REASON%'
                user_agent: '%REQ(USER-AGENT)%'
                x_forwarded_for: '%REQ(X-FORWARDED-FOR)%'
              jsonFormatOptions:
                sortProperties: true
            path: /dev/stdout
        httpFilters:
        - name: istio.metadata_exchange
          typedConfig:
            '@type': type.googleapis.com/udpa.type.v1.TypedStruct
            typeUrl: type.googleapis.com/io.istio.http.peer_metadata.Config
            value:
              upstream_discovery:
              - istio_headers: {}
              - workload_discovery: {}
              upstream_propagation:
              - istio_headers: {}
        - name: envoy.filters.http.grpc_stats
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.http.grpc_stats.v3.FilterConfig
            emitFilterState: true
            statsForAllMethods: false
        - name: istio.alpn
          typedConfig:
            '@type': type.googleapis.com/istio.envoy.config.filter.http.alpn.v2alpha1.FilterConfig
            alpnOverride:
            - alpnOverride:
              - istio-http/1.0
              - istio
              - http/1.0
            - alpnOverride:
              - istio-http/1.1
              - istio
              - http/1.1
              upstreamProtocol: HTTP11
            - alpnOverride:
              - istio-h2
              - istio
              - h2
              upstreamProtocol: HTTP2
        - name: envoy.filters.http.fault
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.http.fault.v3.HTTPFault
        - name: envoy.filters.http.cors
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
        - name: istio.stats
          typedConfig:
            '@type': type.googleapis.com/stats.PluginConfig
        - name: envoy.filters.http.router
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
        normalizePath: true
        pathWithEscapedSlashesAction: KEEP_UNCHANGED
        rds:
          configSource:
            ads: {}
            initialFetchTimeout: 0s
            resourceApiVersion: V3
          routeConfigName: "8081"
        requestIdExtension:
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.request_id.uuid.v3.UuidRequestIdConfig
            useRequestIdForTraceSampling: true
        statPrefix: outbound_0.0.0.0_8081
        streamIdleTimeout: 0s
        tracing:
          clientSampling:
            value: 100
          customTags:
          - metadata:
              kind:
                request: {}
              metadataKey:
                key: envoy.filters.http.rbac
                path:
                - key: istio_dry_run_allow_shadow_effective_policy_id
            tag: istio.authorization.dry_run.allow_policy.name
          - metadata:
              kind:
                request: {}
              metadataKey:
                key: envoy.filters.http.rbac
                path:
                - key: istio_dry_run_allow_shadow_engine_result
            tag: istio.authorization.dry_run.allow_policy.result
          - metadata:
              kind:
                request: {}
              metadataKey:
                key: envoy.filters.http.rbac
                path:
                - key: istio_dry_run_deny_shadow_effective_policy_id
            tag: istio.authorization.dry_run.deny_policy.name
          - metadata:
              kind:
                request: {}
              metadataKey:
                key: envoy.filters.http.rbac
                path:
                - key: istio_dry_run_deny_shadow_engine_result
            tag: istio.authorization.dry_run.deny_policy.result
          - literal:
              value: latest
            tag: istio.canonical_revision
          - literal:
              value: rate-limit-service
            tag: istio.canonical_service
          - literal:
              value: Kubernetes
            tag: istio.cluster_id
          - literal:
              value: cluster.local
            tag: istio.mesh_id
          - literal:
              value: collection-api-dev
            tag: istio.namespace
          overallSampling:
            value: 100
          randomSampling:
            value: 1
        upgradeConfigs:
        - upgradeType: websocket
        useRemoteAddress: true
        xffNumTrustedHops: 2
  listenerFilters:
  - name: envoy.filters.listener.tls_inspector
    typedConfig:
      '@type': type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
  - name: envoy.filters.listener.http_inspector
    typedConfig:
      '@type': type.googleapis.com/envoy.extensions.filters.listener.http_inspector.v3.HttpInspector
  listenerFiltersTimeout: 0s
  name: 0.0.0.0_8081
  trafficDirection: OUTBOUND
```
