### DISCUSSION TITLE
How to use Ingress Gateway with OpenShift Routes?

### DISCUSSION THREAD

**Discussion by m8-t** [istio/istio#53562] [Q&A]
Hello,

I deployed Istio in ambient mode on OpenShift and it works so far. When it comes to Ingress I am struggling to set ingress gateway up.

The documentation states (but this is for sidecar mode):

> After installation is complete, expose an OpenShift route for the ingress gateway.

>$ oc -n istio-system expose svc/istio-ingressgateway --port=http2

This is what I did and I got a route.

Then I deployed my gateway and virtualservice (using istio API, not Gateway API) to access the bookinfo demo via Ingress Gateway:

```
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: bookinfo-gateway
  namespace: demo
spec:
  selector:
    istio: ingress
  servers:
  - hosts:
    - bookinfo.example.com
    port:
      name: http
      number: 8080
      protocol: HTTP
```
and VirtualService:

```
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: bookinfo
  namespace: demo
spec:
  gateways:
  - bookinfo-gateway
  hosts:
  - bookinfo.example.com
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: 9080
```

The ingress gateway is running in istio-system.

There is a route as mentioned above. When I try to access the route I just get an 503 and not sure where to look, not sure if I am even did it setup correctly.

Traffic should flow like this:

NGINX Loadbalancer in front of OpenShift --> 2 Ingress Controllers OpenShift Ingress --> Istio Gateway --> Virtual Service --> Workload

Not sure if this the intended way, any hints? I looked up OpenShift ServiceMesh docs which is clearly not pure istio, thus outdated  but they recommended to create routes inside istio-system namespace like this:

```
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: example-gateway
  namespace: istio-system 
spec:
  host: www.example.com
  to:
    kind: Service
    name: istio-ingressgateway 
    weight: 100
  port:
    targetPort: http2
  wildcardPolicy: None
```

I also tried this with no luck, no NetworkPolicies between these namespaces. The bookinfo namespace has AuthorizationPolicies set but I can't see any logs for rejection or something.

Thanks
