### DISCUSSION TITLE
Patching Envoy config

### DISCUSSION THREAD

**Discussion by ymetelkin-ias** [istio/istio#53580] [Q&A]
If I need my Envoy config to look like this (reduced to important parts)
```
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/prefix/"
                          route:
                            host_rewrite_literal: external_host
                            cluster: my_cluster
```
How do I add a route to Envoy if it is managed by Istio?
