### DISCUSSION TITLE
Proxy for External Services failed after upgrade from 1.20.3 to 1.23.3

### DISCUSSION THREAD

**Discussion by volkorny** [istio/istio#53604] [Q&A]
Hello,
I have a configuration that works fine on Istio 1.20.3 but fails on 1.23.3. Could you please assist me in identifying the issue and finding a fix?
Thank you.

Configuration:
```
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: project1-example-com
  namespace: istio-ingress
spec:
  dnsNames:
  - project1.example.com
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-webhook-dnsimple-production
  secretName: project1-example-com-tls
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/controller: ignored-resource
  name: project1-gateway
  namespace: test-mesh
spec:
  selector:
    istio: ingress-public-gateway
  servers:
  - hosts:
    - project1.example.com
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - project1.example.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: istio-ingress/project1-example-com-tls
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: project1-virtualservice
  namespace: test-mesh
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "project1.example.com"
    external-dns.alpha.kubernetes.io/ttl: "60"
spec:
  hosts:
  - "project1.example.com"
  gateways:
  - test-mesh/project1-gateway
  http:
  - match:
    - uri:
        prefix: /
    rewrite:
      authority: project2.example.com
    route:
    - destination:
        host: project2.example.com
        port:
          number: 443
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: egress-project2-example-com
  namespace: test-mesh
spec:
  hosts:
    - project2.example.com
  ports:
    - name: https
      number: 443
      protocol: TLS
  location: MESH_EXTERNAL
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: proxy-project2-example-com
  namespace: staging-mesh
spec:
  host: project2.example.com
  trafficPolicy:
    tls:
      mode: SIMPLE
```

Request Error:
```
< HTTP/2 503
< content-length: 239
< content-type: text/plain
< date: Mon, 21 Oct 2024 13:17:14 GMT
< server: istio-envoy
<
* Connection #0 to host project1.example.com left intact
upstream connect error or disconnect/reset before headers. retried and the latest reset reason: remote connection failure, transport failure reason: TLS_error:|268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED:TLS_error_end%
```

Log:
```
[2024-10-21T13:17:14.023Z] "GET / HTTP/2" 503 URX,UF 
upstream_reset_before_response_started{remote_connection_failure|TLS_error:|268435581:SSL_routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED:TLS_error_end} - 
"TLS_error:|268435581:SSL_routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED:TLS_error_end" 0 239 994 - "10.7.26.220" "curl/8.4.0" 
"c5ee6725-0b4e-9bd8-9a60-6589e3a56769" "project2.example.com" "55.79.6.74:443" outbound|443||project2.example.com - 
10.7.36.57:443 10.7.26.220:49222 project1.example.com -
```
