### DISCUSSION TITLE
Issue with Datadog Env Variables and Native Sidecars

### DISCUSSION THREAD

**Discussion by volkorny** [istio/istio#53649] [Q&A] [answered]
Hello Team,

I am currently injecting Datadog environment variables into the Istio proxy container in my Deployment using the following annotation:

```yaml
inject.istio.io/templates: sidecar,datadog-ust
```

In my `values-istiod.yaml`, I have configured the `sidecarInjectorWebhook` like this:

```yaml
sidecarInjectorWebhook:
  neverInjectSelector: []
  alwaysInjectSelector: []
  enableNamespacesByDefault: false
  templates:
    # Template to add Datadog Universal Service Tag variables for naming envoy proxy traces
    datadog-ust: |
      spec:
        containers:
          - name: istio-proxy
            env:
              - name: DD_ENV
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['tags.datadoghq.com/env']
              - name: DD_SERVICE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['tags.datadoghq.com/service']
              - name: DD_VERSION
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['tags.datadoghq.com/version']
```

However, after enabling `ENABLE_NATIVE_SIDECARS`, I encounter the following error:

```
Required value, spec.initContainers[1].name: Duplicate value: "istio-proxy"
```

When I remove the annotation `inject.istio.io/templates: sidecar,datadog-ust`, everything works fine, but I lose the necessary environment variables (DD_ENV, DD_SERVICE, DD_VERSION).

I also tried using just:

```yaml
inject.istio.io/templates: datadog-ust
```

In this case, I received the following error:

```
Error creating: Pod "podname" is invalid: spec.containers[1].image: Required value
```

I would appreciate any guidance on how to resolve this issue. Thank you!

**Comment by howardjohn** [comment]
As native sidecars makes the istio-proxy actually an initContainer you will need to make the template have it listed as such

**Reply by volkorny** [reply]
I don’t fully understand your answer. Could you provide more hints or some examples on "make the template have it listed"? Thanks

**Reply by volkorny** [reply]
I use https://artifacthub.io/packages/helm/istio-official/istiod/1.23.3 to deploy istio

**Reply by keithmattix** [reply, marked as answer]
He's referring to your template. You need something like this for native sidecars:
```yaml
spec:
        initContainers:
          - name: istio-proxy
            env:
              - name: DD_ENV
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['tags.datadoghq.com/env']
              - name: DD_SERVICE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['tags.datadoghq.com/service']
              - name: DD_VERSION
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['tags.datadoghq.com/version']
```
