### DISCUSSION TITLE
Global rate limit grouped by authority

### DISCUSSION THREAD

**Discussion by yuzhouliu9** [istio/istio#53660] [Q&A] [answered]
The [example](https://istio.io/latest/docs/tasks/policy-enforcement/rate-limit/#global-rate-limit) global rate limit implies that the ingressgateway serves a single hostname/authority.

Is there an easy way to divide up the ratelimit EnvoyFilter per `:authority`?
With that I can configure multiple rules such as blanket rate limit on `:authority` and more `:path` specific rate limits.

This is what I've come up with and works, but is very tedious and error prone.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ratelimit
  namespace: routing
spec:
  workloadSelector:
    labels:
      istio: istio-ingressgateway-public
  configPatches:
    - applyTo: VIRTUAL_HOST
      match:
        context: GATEWAY
        routeConfiguration:
          vhost:
            name: ""
            route:
              action: ANY
      patch:
        operation: MERGE
        # Applies the rate limit rules.
        value:
          rate_limits:
            - actions:
              - header_value_match:
                  descriptor_key: "authority_path"
                  descriptor_value: "auth.example.com/metrics"
                  headers:
                  - name: ":authority"
                    string_match:
                      exact: "auth.example.com"
              - header_value_match:
                  descriptor_key: "path"
                  descriptor_value: "/metrics"
                  headers:
                  - name: ":authority"
                    string_match:
                      exact: "auth.example.com"
                  - name: ":path"
                    string_match:
                      prefix: "/metrics"
            - actions:
              - header_value_match:
                  descriptor_key: "authority"
                  descriptor_value: "auth.example.com"
                  headers:
                  - name: ":authority"
                    string_match:
                      exact: "auth.example.com"
```
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
  namespace: routing
data:
  config.yaml: |
    domain: ratelimit
    descriptors:
      - key: authority_path
        value: "auth.example.com/metrics"
        descriptors:
          - key: path
            value: "/metrics"
            rate_limit:
              unit: minute
              requests_per_unit: 5
      - key: authority
        value: "auth.example.com"
        rate_limit:
          unit: minute
          requests_per_unit: 50
```

**Comment by yuzhouliu9** [comment, marked as answer]
Found the solution. The EnvoyFilter can be limited for a hostname like this
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
...
spec:
...
  configPatches:
    - applyTo: VIRTUAL_HOST
      match:
        context: GATEWAY
        routeConfiguration:
          vhost:
            name: "myapp.example.com:443"
            route:
              action: ANY
```

This EnvoyFilter will only be applied to the filter chain matching that hostname. Whereas before it was applying to all hostnames.
Also you now guarantee the rate limit actions you define below only apply to that hostname, which may simplify some `:authority` checks.
