### DISCUSSION TITLE
Custom Header for Outgoing Upstream Requests

### DISCUSSION THREAD

**Discussion by aakp10** [istio/istio#53663] [Q&A] [answered]
Hi,
I want to add a custom header to upstream requests going out of a service. I tried to implement this using a custom lua filter hooked to SIDECAR_OUTBOUND. However, the upstream requests don't seem to have be filter by this. Here's the config file:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: service-c-filter-outbound
  namespace: default
spec:
  workloadSelector:
    labels:
      app: app-c
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_OUTBOUND # inbound request; outbound response
      listener:
        portNumber: 5200
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.lua
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
          default_source_code:
            inline_string: |
              -- response from other service
              -- Request to other service 
              function envoy_on_request(request_handle)
                request_handle:headers():add("State", "foo")
              end
```
Has anyone encountered this problem?

**Comment by zirain** [comment]
please check the configuration is there after you apply an EnvoyFilter.
`istioctl pc l <pod_name> -n <pod_namepace> --port 5200 -o yaml`

**Reply by aakp10** [reply]
Strangely, it has a stale entry of some past lua filter. I tried deleting the application and re-deployed it, yet this stale entry persists in the result of the above command.  Do you know why this might be happening and how can I force delete the filters?

**Reply by aakp10** [reply]
Further investigation shows that despite a filter being successfully applied in some other example, the output of ` istioctl pc l <pod_name> -n <pod_namepace> --port 5200 -o yaml` doesn't show the filter code. Is this normal?

**Reply by zirain** [reply]
so there's no 5200 filter, can you check access log, I think you request may may the PassThrough cluster, which explain why the EnvoyFilter didn't work as expected.

**Reply by aakp10** [reply]
I checked the access log, and it just says "upstream requests/ responses" and also downstream "request/ responses".

However, I deleted the entire cluster and now SIDECAR_OUTBOUND filter works. 

But for some reason, the command you suggested doesn't show any inbound filter code despite being actively filtering the inbound traffic. Is this normal?

**Reply by zirain** [reply]
you can remove `--port 5200`

**Reply by aakp10** [reply]
I did remove the port parameter, it doesn't work and inbound filter doesn't show up. Btw if it helps, my cluster is indeed set to PassThrough. I'm new to Istio, so I'm wondering if you've any pointers here?

**Reply by zirain** [reply]
Inbound listen on 15006, you maybe not see it on a gateway(ingress/egress).

**Reply by zirain** [reply, marked as answer]
```
istioctl pc l -n sidecar httpbin-857b9b7d99-6xk28  --port 15006
ADDRESSES PORT  MATCH                                                                                           DESTINATION
0.0.0.0   15006 Addr: *:15006                                                                                   Non-HTTP/Non-TCP
0.0.0.0   15006 Trans: tls; App: istio-http/1.0,istio-http/1.1,istio-h2                                         InboundPassthroughCluster
0.0.0.0   15006 Trans: raw_buffer; App: http/1.1,h2c                                                            InboundPassthroughCluster
0.0.0.0   15006 Trans: tls; App: TCP TLS                                                                        InboundPassthroughCluster
0.0.0.0   15006 Trans: raw_buffer                                                                               InboundPassthroughCluster
0.0.0.0   15006 Trans: tls                                                                                      InboundPassthroughCluster
0.0.0.0   15006 Trans: tls; App: istio,istio-peer-exchange,istio-http/1.0,istio-http/1.1,istio-h2; Addr: *:8080 Cluster: inbound|8080||
0.0.0.0   15006 Trans: raw_buffer; Addr: *:8080                                                                 Cluster: inbound|8080||
```

**Reply by aakp10** [reply]
Thank you very much! This was immensely helpful!

**Reply by aakp10** [reply]
@zirain on a related note, I found myself exploring the C++ Wasm SDK for envoy filters. When I run `istioctl pc l -n namespace podname  --port 15006` I do not see the name of the wasm filter that I'd applied. Is it an expected behavior or is there something wrong in my istio coniguration that I have detailed below.

The detailed setup is: 
1. compile the wasm filter "http_wasm_example.wasm" from this example project https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/tree/main/example
2. apply the following istio filter configuration file:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: headers-extension
spec:
  workloadSelector:
      labels:
        app: app-b
  configPatches:
  - applyTo: EXTENSION_CONFIG
    patch:
      operation: ADD
      value:
        name: headers-extension
        typed_config:
          "@type": type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          value:
            config:
              vm_config:
                vm_id: headers-extension-vm
                runtime: envoy.wasm.runtime.v8
                code:
                  remote:
                    http_uri:
                      uri: https:/<somedomain>/http_wasm_example.wasm
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: INSERT_BEFORE
      value:
        name: headers-extension
        config_discovery:
          config_source:
            ads: {}
            initial_fetch_timeout: 0s # wait indefinitely to prevent bad Wasm fetch
          type_urls: [ "type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm"]
```
