### DISCUSSION TITLE
Static lua tables in envoy filters

### DISCUSSION THREAD

**Discussion by aakp10** [istio/istio#53678] [Q&A]
Hi, 
I'm implementing an inline lua filter where the `on_envoy_request` and `on_envoy_response` methods use a static lua table. 
For example,
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: service-a-filter
  namespace: default
spec:
  workloadSelector:
    labels:
      app: app-a
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND # inbound request; outbound response
      listener:
        portNumber: 5000
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.lua
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
          default_source_code:
            inline_string: |
              tbl = {}
              tbl["foo"] = "bar"
              -- Inbound Requests
              function envoy_on_request(request_handle)
                request_handle:logCritical(tbl["foo"])
              end
``` 
Based on this discussion: https://github.com/envoyproxy/envoy/issues/27117
it seems like lua filters will be instantiated per HTTP request, which means this `tbl` will be instantiated for each request. 

Is there a way to create this static table once which gets used across all the requests and responses?
