### DISCUSSION TITLE
How to change subset which pod belongs by change pod's label or others?

### DISCUSSION THREAD

**Discussion by MinH-09** [istio/istio#53768] [Q&A]
Hello,
I have a simple case from bookinfo case, can I change pod label to change its subset？Such as：In same deployMent, change pod label version: v1 -> version: v2 to change its subset v1->v2, or other way I can try to achieve the goal. 

Below is case yaml:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews
  labels:
    app: reviews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
  template:
    metadata:
      labels:
        app: reviews
    spec:
      serviceAccountName: bookinfo-reviews
      containers:
      - name: reviews
        image: docker.io/istio/examples-bookinfo-reviews-v2:1.20.1
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        ports:
        - containerPort: 9080

kind: DestinationRule
apiVersion: networking.istio.io/v1beta1
metadata:
  name: reviews
spec:
  host: 
  subsets:
    - name: v1
      labels:
         version: v1
    - name: v2
      labels:
        version: v2
    - name: v3
       labels:
        version: v3
```
