### DISCUSSION TITLE
How do I get MySQL service traffic to work correctly with Istio Ambient + Waypoint?

### DISCUSSION THREAD

**Discussion by jessebye** [istio/istio#53823] [Q&A] [answered]
I have Istio ambient mode enabled for my cluster and namespace, and created a Waypoint for the namespace:
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  labels:
    istio.io/waypoint-for: service
  name: waypoint
  namespace: foo-bar
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - allowedRoutes:
      namespaces:
        from: Same
    name: mesh
    port: 15008
    protocol: HBONE
```

Traffic to http services works fine (and shows up in the waypoint's logs), but traffic to mysql containers in the namespace doesn't work correctly (no waypoint logs for this traffic). I tried creating a ServiceEntry for the mysql service:

```
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: api-mysql
  namespace: foo-bar
spec:
  hosts:
  - api-mysql
  location: MESH_INTERNAL
  ports:
  - name: mysql-port
    number: 3306
    protocol: mysql
  resolution: DNS
```

But it still fails with a "MySQL server has gone away" type of error in the client. Also, I didn't have to create ServiceEntries for my http services and they worked, so this seems like the wrong approach.

If I remove the `istio.io/use-waypoint: waypoint` label from the mysql kubernetes `Service`, then it works fine. But as soon as I add that label it stops working.
