### DISCUSSION TITLE
[Sidecar] Default deny AuthorizationPolicy and metrics

### DISCUSSION THREAD

**Discussion by kapistka** [istio/istio#53853] [Q&A]
When we use sidecars and [default deny patterns](https://istio.io/latest/docs/ops/best-practices/security/#use-default-deny-patterns)
<details>
  <summary>like this :</summary>

```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: default
  namespace: bookinfo
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces:
        - bookinfo
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: prometheus
  namespace: bookinfo
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces:
        - prometheus
```
</details>
is there a way to get metrics on the same port as the application? When accessing the pod directly, prometheus receives 403.
In the ambient mode it works fine.
