### DISCUSSION TITLE
[Sidecar] Can I use Sidecar CRD to exclude some hosts?

### DISCUSSION THREAD

**Discussion by xjtupdy** [istio/istio#53890] [Q&A] [answered]
IstioEgressListener can only allow some hosts by [hosts]?  Is it possible to allow all hosts except some services in config? 
a hypothetical example may be:  
```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: exclude-nginx
  namespace: sample
spec:
  egress:
  - hosts:
    - "*/*"
    - "-sample/nginx.sample.svc.cluster.local"
```
