### DISCUSSION TITLE
How to bind a localhost port to a service via a Gateway without Host header

### DISCUSSION THREAD

**Discussion by abhishekmukherg** [istio/istio#53901] [Q&A]
Hope it's okay to cross post this [from Stack Overflow](https://stackoverflow.com/questions/79190109/how-to-bind-a-localhost-port-to-a-service-via-a-gateway-without-host-header), since there doesn't seem to be much engagement over there.

in our organization, we have a lot of services that hardcode sending requests to something like `localhost:12345` from our previous service mesh solution. This pattern is in broad enough codebases that I'm trying to find a way to replicate this using Istio. The goal is to make it so that requests on a Kubernetes pod for `localhost:12345` make its way through to a upstream configured via Istio.

This is documented in the [docs for Sidecar](https://istio.io/latest/docs/reference/config/networking/sidecar/) however, there's one other complexity in our setup that seems insurmountable -- we need to have our traffic support going across an Istio Gateway. This seems to make the entire house fall down.

Before getting into details of what has been tried, thinking about it broadly, I can't see how this could work. The client pod is set up with a Sidecar to bind localhost and point to `VirtualService` routed to a `ServiceEntry` with the Gateway's hostname. There are two results to this:

1. The client envoy leverages the default route-discovery-service route config to route the request to the gateway -- this leverages the `Host` / `:authority` header.
2. That request has to include the `Host` / `:authority` so that the Gateway instance can route to the appropriate `Gateway` CR.

There doesn't seem to be something on the [`Sidecar`](https://istio.io/latest/docs/reference/config/networking/sidecar/) I can configure to say "requests on _this_ port should adopt _this_ `Host`".

## What worked

I was broadly able to make it work via a `Sidecar` like:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: default
spec:
  egress:
    - hosts:
        - "default/foo.example.com"
      captureMode: NONE
      port:
        number: 8000
        name: frontend-httpbin
        protocol: HTTP2
      bind: 127.0.0.1
```

with the big caveat that requests _must_ include the `Host header, such as:

```sh
curl -H "Host: foo.example.com" localhost:8000
```

Without the `Host` header, I think two things happen

1. The Envoy sidecar running on the client pod is listening on port 8000, but does not know that it should route to the Gateway, because it [does that routing based on the Host](https://istio.io/latest/docs/ops/configuration/traffic-management/traffic-routing/#http). Because of that, the curl returns with a no upstream error (sorry forgot to capture the exact line)
2. Assumption: If we were able to route the request appropriately, without the client Envoy injecting the `Host` header, the request would get a similar issue once it got to the gateway. The gateway wouldn't have any of the information on the port or otherwise to route the service otherwise

## Overall question

Is there a way to make this happen? So that requests to localhost which currently route to a specific service will do the same in Istio via a gateway, without any application code changes?

**Comment by abhishekmukherg** [comment]
It's a complete workaround, but we implemented this by just running an(other) Envoy sidecar in "user" space of the pod that just proxies to the appropriate host in the mesh. For example

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: localhost-envoy-proxy
data:
  envoy.yaml: |
    admin:
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 19901
    static_resources:
      listeners:
        - name: listener_18123
          address:
            socket_address:
              address: 127.0.0.1
              port_value: 18123
          filter_chains:
            - filters:
                - name: "envoy.http_connection_manager"
                  typed_config:
                    "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
                    stat_prefix: ingress_http
                    codec_type: AUTO
                    stream_error_on_invalid_http_message: true
                    route_config:
                      name: "local_route"
                      virtual_hosts:
                        - name: local_service
                          domains: ["*"]
                          routes:
                            - match:
                                prefix: "/"
                              route:
                                host_rewrite_literal: testservice.example.com
                                cluster: "testservice.example.com"
                    http_filters:
                      - name: envoy.filters.http.router
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      clusters:
        - name: testservice.example.com
          type: STRICT_DNS
          load_assignment:
            cluster_name: testservice.example.com
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: testservice.example.com
                          port_value: 80
---
containers:
- name: localhost-proxy
  image: envoyproxy/envoy:v1.30.1
  volumeMounts:
    - name: localhost-envoy-proxy
      mountPath: /etc/envoy
      readOnly: true
# ...
volumes:
    - name: localhost-envoy-proxy
      configMap:
        name: localhost-envoy-proxy
        items:
          - key: envoy.yaml
            path: envoy.yaml
```

It ain't pretty, but works. Would still be really interested if someone has a better way to implement this.
