### DISCUSSION TITLE
Unexpected Behavior with Session Affinity during Pod Restart

### DISCUSSION THREAD

**Discussion by fgksteinman** [istio/istio#53905] [General]
My team has cookie-based session affinity via a destinationrule with the following configuration:
```yaml
  host: serviceName.namespace.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: sessionName
          path: "/"
          ttl: 0s
```
where `serviceName` corresponds to a deployment with several pods and a HorizontalPodAutoscaler. 

We have observed the following:
Say I have podA, podB, etc... actively running for this deployment. If podA restarts, traffic moves to podB. 
However, when podA is running and healthy again (within a couple minutes), then traffic moves back from podB to podA.

The movement of traffic from podA -> podB makes sense and is expected. But why isn't the traffic staying on podB? Why is the traffic going from podA -> podB -> podA when podA finishes restarting?

Going from podA -> podB -> podA is introducing more latency than is acceptable. Session data gets loaded on podB, which is necessary, but then session data has to get loaded a second time on podA when the traffic switches back. 

My hypothesis, based on documentation stating "The affinity to a particular destination host may be lost when one or more hosts are added/removed from the destination service", is that the podA restart removes the podA host from the service and then adds the podA host back to the service, and therefore there is no guarantee for session affinity to any pod when a restart happens.

Is there any way to configure destinationrules so that traffic stays on podB even after podA finishes restarting?
Are there any other workarounds that the community is aware of for dealing with an issue like this?

Any thoughts and input are much appreciated, thanks!
