### DISCUSSION TITLE
Istio Proxy Exiting pods after completion

### DISCUSSION THREAD

**Discussion by lgruendh** [istio/istio#54009] [Q&A] [answered]
I have a few K8s jobs which are deployed in Istio enabled namespaces.

After the main container finishes and terminates the istio-proxy container keeps running.

I know about the /quitquitquit but this is hard to implement for every job.
Especially if you can not use lifecycle preStop for successful containers.

There are already a few open issues about this, but in 2023 this should be fixed.
https://istio.io/latest/blog/2023/native-sidecars/#exiting-pods
"Here we can see the application container exited, and shortly after Istio’s sidecar container exits as well."
Did I miss a config somewhere?

Did I miss a config somewhere?
I looked into these, but I didn't find the right one.
https://istio.io/latest/docs/reference/config/

old issues:
https://stackoverflow.com/questions/72645650/terminate-istio-proxy-after-cronjob-completion
https://github.com/istio/istio/issues/11659
https://github.com/istio/istio/issues/11045
https://github.com/istio/istio/issues/6324
...

Thank you!

**Comment by howardjohn** [comment, marked as answer]
Native sidecar mode is still not enabledf by default since it is "beta" in Kubernetes. You will need to install Istiod with ENABLE_NATIVE_SIDECARS=true set

**Reply by lgruendh** [reply]
Thank you!
We are currently running K8s Version 1.28.
After upgrading we will enable this feature and see if it is working.
Maybe we also wait for Istio 1.25 and see if ENABLE_NATIVE_SIDECARS is still needed, or a default setting.

Similar discussion:  https://github.com/istio/istio/issues/48794#issuecomment-2429419152

**Reply by howardjohn** [reply]
Istio will not enable by default while its "beta" in Kubernetes for reliability reasons. You can always enable it  yourself though.

Note the feature has some serious bugs in k8s 1.28, strongly recommend 1.29.

**Comment by lgruendh** [comment]
In meanwhile we will just disable the Autoinjection for jobs with a Kyverno mutate rule.
```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: 'istio-job-disabled'
spec:
  background: true
  generateExistingOnPolicyUpdate: true
  rules:
    - match:
        any:
          - resources:
              kinds:
                - Job
      mutate:
        patchStrategicMerge:
          spec:
            template:
              metadata:
                labels:
                  sidecar.istio.io/inject: "false"
      name: istio-job-disabled
      skipBackgroundRequests: true
  validationFailureAction: enforce
```
