### DISCUSSION TITLE
Use case : internal curl without svc.local but with test.example.com, is it possible ?

### DISCUSSION THREAD

**Discussion by vbx** [istio/istio#54068] [Q&A]
Hello, 
I am testing istio for the first time with ambient mode and some resources like serviceEntry / virtualService / gateway and api integration. 
I would like to reach a pod A to another pod B in same namespace (and ambient mode) but not from internal (cluster.local) address, only from test.example.com. 
From Pod A : curl test.example.com ( -> POD B ): The result must be the same as internal (cluster.local) = curl test.default.svc.cluster.local

How to do it ? 
Thanks

**Comment by howardjohn** [comment]
I would recommend a setup like so:

```yaml
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: test-app
spec:
  hosts:
  - test.example.com
  location: MESH_INTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: STATIC
  workloadSelector:
    labels:
      app: test
```

This will essentially make a new service for 'test.example.com' that selects all pods with `app: test` label. Align the label selector with the `Service`s selector
