### DISCUSSION TITLE
Managing and Removing High-Cardinality Metrics in Istio

### DISCUSSION THREAD

**Discussion by tomerguttman** [istio/istio#54084] [Q&A]
Hi there! We're currently using Istio `1.20.8` and have identified some high-cardinality metrics that we don't really need.

We've successfully removed some of them using the Telemetry resource, as shown below:

```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: disable-istio-metrics
  namespace: istio-system
spec:
  metrics:
    - providers:
        - name: prometheus
      overrides:
        - disabled: true
          match:
            mode: CLIENT_AND_SERVER
            metric: REQUEST_SIZE # istio_request_bytes
        - disabled: true
          match:
            mode: CLIENT_AND_SERVER
            metric: RESPONSE_SIZE # istio_response_bytes
        - disabled: true
          match:
            mode: CLIENT_AND_SERVER
            metric: REQUEST_DURATION # istio_request_duration_milliseconds
```

We have some unused metrics that we want to remove, but we're unclear on how to achieve this based on the documentation. While we could handle it on the Prometheus side through configurations, we believe the cleaner approach is to address it directly within Istio.

Specifically, i'm referring to the `envoy_*` metrics exposed by the Istio sidecar

![Screenshot 2024-11-27 at 11 51 48](https://github.com/user-attachments/assets/7a96557a-2d05-4075-a559-a1ac7fcb6a0b)

Appreciate the help 🙏🏻

**Comment by zirain** [comment]
Telemetry API won't affact metrics with prefix `envoy-*`.

I think you can use custom bootstrap to enable stats exclusion_list.

**Reply by tomerguttman** [reply]
@zirain Can you please elaborate a bit about the bootstrap process?

**Reply by zirain** [reply]
the examples is [here](https://github.com/istio/istio/blob/master/samples/custom-bootstrap), you can try change the configmap like following:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-custom-bootstrap-config
data:
  custom_bootstrap.json: |
    "statsConfig": {
      "statsMatcher": {
        "exclusionList": {
          "patterns": [
            { "prefix": "tcp"}
          ]
        }
      }
    }
```
