### DISCUSSION TITLE
Route external traffic to Egress Gateway

### DISCUSSION THREAD

**Discussion by jbaarssen** [istio/istio#54104] [Q&A]
I'm trying to route external traffic through the waypoint deployed in my namespace. Right now I only see the traffic from the pods within the namespace. For example I'm trying to route the traffic for https://graph.microsoft.com through the egress-gateway. I get an  response but none of the traffic is logged within in ztunnel or the waypoint.

In Kiali I see the traffic for https://graph.microsoft.com coming directly from the source pod. 

This is my ServiceEntry:

```yaml 
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  namespace: egress-gateway
  # Name is shown in Kiali when traffic goes to this service entry
  name: ms-graph-test
spec:
  exportTo:
  - .
  hosts:
  - 'graph.microsoft.com'
  ports:
  - number: 443
    name: https
    protocol: TLS
  location: MESH_EXTERNAL
  resolution: DNS
```
On the namespace I've set the label for the gateway: istio.io/use-waypoint: waypoint. The waypoint pod is running and logging traffic between pods in the namespace. The namespace is also labeled to use ambient mode.
