### DISCUSSION TITLE
Fetching JWKs from Envoy

### DISCUSSION THREAD

**Discussion by RomekCDPR** [istio/istio#54126] [Q&A] [answered]
Hello, I use ISTIO 1.19.10 with `PILOT_JWT_ENABLE_REMOTE_JWKS=envoy` (as Managed Cloud Service Mesh) and struggle to configure proper authorization policies.

 In the cluster I have 2 namespaces:

1. one with JWT authorization configured via `RequestAuthentication`
2. one with authorization handled by an application (it has to handle both JWT and non-JWT tokens)

The JWKs are fetched from an external service (via HTTPS). In order to fetch JWKs in Envoy I had to crate `ServiceEntry` + `DestinationRule` (for TLS in Envoy).

1. I created `ServiceEntry` objects in each namespace (with `exportTo: .`), but the policy applier [was throwing errors about service being found in multiple namespace](https://github.com/istio/istio/blob/1b34cb9c7a77a0d48d20bc99a31f2eba1fbe0dbb/pilot/pkg/security/authn/policy_applier.go#L228).
2. I replaced it with one shared `ServiceEntry` (with `exportTo: *`), but run into problem with [double TLS encryption](https://istio.io/latest/docs/ops/common-problems/network-issues/#double-tls) in the 2nd namespace.
3. I ended up fetching JWKs via HTTP (both from Envoy and the application) and setting up TLS origination in `DestinationRule`.
4. I also stumbled onto solution with `VirtualService` and destination subsets (https://github.com/istio/istio/issues/51398#issuecomment-2150453971 - I assume that `VirtualService` is applied only to traffic from the application).

What is recommended configuration for the setup?

**Comment by howardjohn** [comment]
It might be useful to show the config you actually applied. But I would think you could do something like so:

```yaml
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: external-svc-dns
spec:
  hosts:
  - fake.reqauth.example.com # Not used for endpoint selection, see below
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  endpoints:
  - address: real.example.com # the actual hostname of the server
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: bookinfo-ratings
spec:
  host: fake.reqauth.example.com
  trafficPolicy:
    tls:
      mode: SIMPLE
```

Then the app calling `real.example.com` is not impacted by our customizations. Point the ReqAuth to `fake.reqauth.example.com`

**Reply by RomekCDPR** [reply]
Thanks - here is my current config:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: accounts
  namespace: istio-shared
spec:
  hosts:
  - accounts.test.cdpred.services
  location: MESH_EXTERNAL
  ports:
  - name: http
    number: 80
    protocol: HTTP
    targetPort: 443
  resolution: DNS

---

apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: accounts
  namespace: istio-shared
spec:
  host: accounts.test.cdpred.services
  trafficPolicy:
    tls:
      mode: SIMPLE

---

apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: default
  namespace: game-library
spec:
  jwtRules:
  - forwardOriginalToken: true
    issuer: https://accounts.test.cdpred.services/realms/cdp
    jwksUri: http://accounts.test.cdpred.services/realms/cdp/protocol/openid-connect/certs # ISTIO performs TLS origination
```

**Reply by RomekCDPR** [reply]
@howardjohn You recommended using `VirtualService` in similar use case: https://github.com/istio/istio/issues/51398#issuecomment-2150453971. Is fake host preferred?

**Reply by howardjohn** [reply]
Ultimately you need to change ReqAuth codepath, or the non-ReqAuth codepath.

Solution above makes it so you don't need to change anything in the normal flow but need to change your ReqAuth.

https://github.com/istio/istio/issues/51398#issuecomment-2150453971 does the opposite.

**Reply by RomekCDPR** [reply]
OK, changing ReqAuth path sounds better for me.

**Reply by RomekCDPR** [reply]
OK, I tested the solution and it does not work out of the box. The requests to `fake.reqauth.example.com` from envoy are successfully resolved to IP address of `real.example.com` but the host header seems to stay `fake.reqauth.example.com`, messing routing on downstream service. Is there any workaround?

**Reply by RomekCDPR** [reply, marked as answer]
OK - here is the configuration that turned out to be working:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: accounts
spec:
  host: accounts.test.cdpred.services
  subsets:
  - name: direct
    trafficPolicy:
      tls:
        mode: DISABLE
  trafficPolicy:
    tls:
      mode: SIMPLE
---

apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: accounts
spec:
  hosts:
  - accounts.test.cdpred.services
  location: MESH_EXTERNAL
  ports:
  - name: https
    number: 443
    protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: accounts
spec:
  hosts:
  - accounts.test.cdpred.services
  tls:
  - match:
    - port: 443
      sniHosts:
      - accounts.test.cdpred.services
    route:
    - destination:
        host: accounts.test.cdpred.services
        subset: direct
```
