### DISCUSSION TITLE
Istio VM Services

### DISCUSSION THREAD

**Discussion by worlddrknss** [istio/istio#54139] [Q&A]
What I am trying to accomplish is have Kubernetes/EKS talk to the VM which sits in a private network in order to talk with services that live on that network. The flow I am looking for is `EKS -> VM -> Private Service`. 

Network 1:
EKS with Istio Control Plane
 - I installed the east-west gateway with HELM.
 - `helm install istio-eastwestgateway istio/gateway -n istio-system --set name=istio-eastwestgateway --set networkGateway=network1`
 - Configured a Network-LB that forwards ports 15017, 15021, 15012, 15443 that their respected ports on the Nodes.
 - Can't reach services from Kubernetes to VM

Network 2:
Ubuntu EC2 with Istio Runtime Proxy
 - Istio Runtime is connected to EKS
 - Private subnet
 - Can reach Kubernetes services via `curl service.namespace.svc`

```
ubuntu@ip-172-23-1-144:~$ curl nginx-server.default.svc
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
ubuntu@ip-172-23-1-144:~$
```

Ubuntu EC2 running Nginx Server
 - Private subnet
 - Created Service, ServiceEntry and VirtualService configs in EKS 

If I run `curl nginx-external.default.svc.cluster.local` from either the EC2 running Istio or POD I get the following response `no healthy upstream`

`workloadgroup.yaml`
```
apiVersion: networking.istio.io/v1
kind: WorkloadGroup
metadata:
  name: "proxy"
  namespace: "istio-vms"
spec:
  metadata:
    labels:
      app: "proxy"
  template:
    serviceAccount: "istio-account"
    network: "network2"
```

`service.yaml`
```
apiVersion: v1
kind: Service
metadata:
  name: nginx-external
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: proxy
```
`service-entry.yaml`
```
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: external-nginx
  namespace: istio-vms
spec:
  hosts:
  - nginx.external.com
  addresses:
  - 172.23.1.140
  ports:
  - number: 80
    name: http
    protocol: HTTP
  location: MESH_EXTERNAL
  resolution: STATIC
```
`virtual-service.yaml`
```
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: nginx-external-route
  namespace: istio-system
spec:
  hosts:
  - nginx.external.com
  gateways:
  - mesh
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: nginx-external.default.svc.cluster.local 
        port:
          number: 80
```
