### DISCUSSION TITLE
[Ambient] egress routing with TLS origination not working

### DISCUSSION THREAD

**Discussion by anumalasri** [istio/istio#54166] [Q&A] [answered]
We are trying to secure service mesh as much as possibile using auth policies and network policies. 

In this effort, we are trying to connect to few external service and required to setup custom TLS configuration.   We are started with `SIMPLE` tls from egress waypoint to external service. 

When we originate TLS from application pod, its working fine.  However, when we use HTTP from POD and trying to originate TLS from egress waypoint, we are getting unexpected results.   From the logs, we could see that traffic is directly going to external working with HTTP. 

Here is configuration we have: 

1. Enabled MTLS at mesh level. 
```
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: "default"
spec:
  mtls:
    mode: STRICT
```

2. Created application having following auth and network policies. 
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-to-istio-egress 
  namespace: app-backend
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: istio-egress
    ports:
    - protocol: TCP
      port: 15008           
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: istio-system
    ports:
    - protocol: TCP
      port: 15008        
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: app-backend        
    ports:
    - protocol: TCP
      port: 15008      
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-egress
  namespace: app-backend
spec:
  podSelector: {}
  policyTypes:
  - Egress
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: app-api
  namespace: app-backend
spec:
  selector:
    matchLabels:
      app: app-api
      app.kubernetes.io/name: api
      app.kubernetes.io/instance: app
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/istio-ingress/sa/ingress-gateway-istio        

---  
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-nothing
  namespace: app-backend
spec:
  {}
---       

```

3. Created egress waypoint and service entries 

```
apiVersion: v1
kind: Namespace
metadata:
  name: istio-egress
  labels:
    istio.io/dataplane-mode: ambient    
    istio.io/use-waypoint: egress-waypoint
---    
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    fluentbit.io/exclude: "true"
  labels:
    istio.io/waypoint-for: all
  name: egress-waypoint
  namespace: istio-egress
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - name: mesh
    port: 15008
    protocol: HBONE
    allowedRoutes:
      namespaces:
        from: Same 
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-nothing
  namespace: istio-egress
spec:
  {}    
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: external-services-common-auth-policy
  namespace: istio-egress
spec:
  targetRefs:
  - kind: ServiceEntry
    group: networking.istio.io
    name: external-services-common
  action: ALLOW
  rules:
  - from:
    - source:
         principals:
         - cluster.local/ns/app-backend/sa/api-sa
---      
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: originate-tls
  namespace: istio-egress
spec:
  host: kyve1dv0101.vault.net
  exportTo:
  - "istio-egress"  
  trafficPolicy:
    tls:
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-services-common
  namespace: istio-egress
  labels:
    istio.io/use-waypoint: egress-waypoint
spec:
  exportTo: 
  - "istio-egress"
  hosts:
    - "kyve1dv0101.vault.net"
  ports:
  - number: 80
    name: https-80
    protocol: https
    targetPort: 443
  resolution: DNS
  location: MESH_EXTERNAL
``` 

We verified the following: 

1.  Waypoint gateway programmed successfully.
2.  Service Entry has assigned IP Address and attached to waypoint
3.  Tried to debug from Source POD and able to get same IP Address. 
4.  Verified ztunnel logs - logs available from troubleshoot, but not when application tries to connect to external services.
5.  `istioctl zc services` - showing all service entries assigned to egress-waypoint.
6.  'istioctl zc workloads' - showing none of pod assigned to egress-waypoint. 
7.   `istioctl analyze -A` - showing no errors , but warning on Destination rule that SIMPLE TLS mode should have CA certificates . 

Some gray areas for us: 
1. `allowedRoutes` in waypoint - is it correct way when PODs from other namespace trying to utilize egress routing. 
2.  'allow-nothing' policies 
3.  anything incorrect in 'network polices`.

We are unable to troubleshoot this issue further. 

Appreciate any help to establish TLS origination successfully in this configuration.
