### DISCUSSION TITLE
Pod was rejected: init container "istio-proxy" may not have a non-default restartPolicy

### DISCUSSION THREAD

**Discussion by kryptonite303** [istio/istio#54216] [Q&A] [answered]
I'm trying to use Native Sidecars with Istio as described in this article: https://istio.io/latest/blog/2023/native-sidecars/
I'm using AWS EKS with cluster version 1.29 and Istio version 1.21.6:
```
client version: 1.21.6
control plane version: 1.21.6
```

This AWS document https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-kubernetes-version-1-29/ also mentions that "SidecarContainers feature gate is enabled by default". I also confirmed this by running this command in my cluster:
```
kubectl get --raw /metrics | grep kubernetes_feature_enabled
```
with a result of
```
kubernetes_feature_enabled{name="SidecarContainers",stage="BETA"} 1
```
so Native Sidecars should also be enabled within my cluster.

The issue I'm running into is when a CronJob I have tries to create a Job, which creates a Pod, I get the following error:
```
InitContainerRestartPolicyForbidden
Pod was rejected: Init container "istio-proxy" may not have a non-default restartPolicy
```
I also have the `ENABLE_NATIVE_SIDECARS` environment variable also specified in my IstioOperator like so:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    pilot:
      k8s:
        env:
          - name: ENABLE_NATIVE_SIDECARS
            value: "true"
```
Is there some configuration that I may be missing here? Thanks for your help!
