### DISCUSSION TITLE
Communication between namespaces

### DISCUSSION THREAD

**Discussion by hagay3** [istio/istio#54257] [Q&A] [answered]
Hey team,
We are exploring a scenario where we need to enable communication between two services located in different namespaces, without requiring the full DNS name <service.name>.<namespace name>.svc.cluster.local

While researching solutions, I came across a [method](https://stackoverflow.com/a/44329470) that involves using an ExternalName service to create an alias for a service in another namespace:
```
kind: Service
apiVersion: v1
metadata:
  name: service-y
  namespace: namespace-a
spec:
  type: ExternalName
  externalName: service-y.namespace-b.svc.cluster.local
```

I have tested this approach, and it works as expected.
We are able to reach a service in different namespace only using its name without the full kubernetes DNS name.

However, I’d like to understand the implications when Istio is involved.

Lets say we have 2 services with istio-proxy sidecar that communicate with each other using dedicated externalName service.
Will Istio continue to function normally, applying network-related policies such as Least Request load-balancing?

I reviewed the Istio related [documentation](https://istio.io/latest/docs/tasks/traffic-management/egress/egress-kubernetes-services/) but didn’t find a discussion on this specific use case.
