### DISCUSSION TITLE
[Sidecar] Is it necessary to add 'istio-system' namespace to Sidecar's egress hosts？

### DISCUSSION THREAD

**Discussion by xjtupdy** [istio/istio#54274] [Q&A]
If I use Sidecar to reduce istio-proxy's memory, is it necessary to add 'istio-system' namespace to Sidecar's hosts？
Is there any impact if 'istio-system' namespace is missed?
```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: default
  namespace: sample
spec:
  egress:
    - hosts:
        - ./*
        # necessary?
        - istio-system/*
```
