### DISCUSSION TITLE
Why istio-ingressgateway does not have any log output?

### DISCUSSION THREAD

**Discussion by cn-hew** [istio/istio#54308] [Q&A]
When I use curl to request 10 times in a row, there are always one or two times when it is always waiting and there is no info request log. When I change to debug, there is log output, but the corresponding pod of the backend does not receive the request. I have tried to access it using the fully qualified name in other pods, and there is no exception. What is the problem? The version of istio is 1.21.6
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: xxx-gateway
  namespace: istio-ingress
spec:
  selector:
    istio: ingressgateway # Use Istio's ingress gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "uat-xxx.xx.xx"
      tls:
        httpsRedirect: true # sends 301 redirect for http requests
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "*"
      tls:
        mode: SIMPLE
        credentialName: xxxx.xx
```

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: open-platform-gateway
  namespace: istio-ingress
spec:
  hosts:
    - "uat-xxx.xxxx.xxx"
  gateways:
    - xxx-gateway
  http:
    - match:
        - uri:
            prefix: "/"  # 匹配 /a 开头的请求
      route:
        - destination:
            host: xxx-open-platform-gateway.uat.svc.cluster.local
            port:
              number: 8080
      timeout: 30s

   

```
debug log 
```
':path', '/platform/authorization/getToken'
2024-12-13T05:00:17.321533Z	debug	envoy router external/envoy/source/common/router/router.cc:514	[Tags: "ConnectionId":"20792239","StreamId":"14654885778441423058"] cluster 'outbound|8080||lsym-open-platform-gateway.uat.svc.cluster.local' match for URL '/platform/authorization/getToken'	thread=65
':path', '/platform/authorization/getToken'

```
