### DISCUSSION TITLE
Ambient Waypoint Egress - Secret_is_not_supplied_by_SDS error

### DISCUSSION THREAD

**Discussion by anumalasri** [istio/istio#54326] [Q&A] [answered]
Followed the approach described in https://www.solo.io/blog/egress-gateways-made-easy and able to setup ambient waypoint for egress. 

The configuration works fine except custom certificates to establish HTTPS connection between waypoint proxy and external url. 

We have the following destination rule and secrets available in `istio-egress` namespace.  With this,  waypoint throws error `TLS_error:_Secret_is_not_supplied_by_SDS` when connecting to external url. 

1.  Is there any order of resources to be created , so that SDS will be able to identify secret and push it to waypoint ? 
2.  Is any below configuration need to corrected ? 
3.  I could find some previous issues related to `credentialName` in DestinationRule.   Is there other options to inject Certs/CACerts into waypoint proxy  and use `caCertificates` in DestinationRule ? 

Appreciate your help in this. 

**Waypoint Proxy Error:** 
`[2024-12-14T18:42:33.756Z] "GET /channel/api/chat HTTP/1.1" 503 URX,UF upstream_reset_before_response_started{remote_connection_failure|TLS_error:_Secret_is_not_supplied_by_SDS} - "TLS_error:_Secret_is_not_supplied_by_SDS" 0 189 31 - "-" "curl/8.10.1" "e1450ae2-ee9a-411b-bad1-7fc62ba4279c" "dev.apis.xxxxx.com" "10.xxx.xxx.xxx:443" inbound-vip|80|http|dev.apis.xxxxx.com - 240.240.0.19:80 172.17.3.235:60334 - default`

**Configuration:**
```
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: originate-tls-for-dev
  namespace: istio-egress
spec:
  exportTo:
  - istio-egress
  host: dev.apis.xxxxx.com
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      credentialName: istio-egressgateway-certs
      mode: SIMPLE
```

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  labels:
    istio.io/waypoint-for: all
  name: egress-waypoint
  namespace: istio-egress
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - name: mesh
    port: 15008
    protocol: HBONE
    allowedRoutes:
      namespaces:
        from: Same 
```        
```
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  labels:
    istio.io/use-waypoint: egress-waypoint
  name: external-services-apim
  namespace: istio-egress
spec:
  exportTo:
  - istio-egress
  hosts:
  - dev.internal.apis.metlife.com
  location: MESH_EXTERNAL
  ports:
  - name: http-80
    number: 80
    protocol: http
    targetPort: 443
  resolution: DNS        
```
```
% k get secrets -n istio-egress
NAME                               TYPE     DATA   AGE
istio-egressgateway-certs          Opaque   3      15m
istio-egressgateway-certs-cacert   Opaque   1      15m

% k get secrets -n istio-egress istio-egressgateway-certs -o yaml
apiVersion: v1
data:
  cacert: "xxxx"
  cert: "xxxx"
  key: "xxxx"
kind: Secret
metadata:
  name: istio-egressgateway-certs
  namespace: istio-egress
type: Opaque

% k get secrets -n istio-egress istio-egressgateway-certs-cacert -o yaml
apiVersion: v1
data:
  cacert: "xxxx"
kind: Secret
metadata:
  name: istio-egressgateway-certs-cacert
  namespace: istio-egress
type: Opaque

% istioctl pc s egress-waypoint-5d545cbdb9-f259q.istio-egress                      
RESOURCE NAME                                     TYPE           STATUS      VALID CERT     SERIAL NUMBER                        NOT AFTER                NOT BEFORE
kubernetes://istio-egressgateway-certs-cacert                    WARMING     false                                                                        
default                                           Cert Chain     ACTIVE      true           9ad2722b790cd9451ce38f6ddc620e00     2024-12-15T18:41:47Z     2024-12-14T18:39:47Z
ROOTCA                                            CA             ACTIVE      true           f9c72bb2f2573cb32f8b760f4aae13f9     2034-11-13T22:21:39Z     2024-11-15T22:21:39Z
file-root:system                                  CA             ACTIVE      true           5ec3b7a6437fa4e0                     2030-12-31T09:37:37Z     2011-05-05T09:37:37Z
```

**Comment by anumalasri** [comment]
Istiod has this warning: 

`2024-12-15T19:46:47.509911Z	warn	ads	proxy egress-waypoint-5d545cbdb9-84t92.istio-egress attempted to access unauthorized certificates istio-egressgateway-certs-cacert: egress-waypoint/istio-egress is not authorized to read secrets: Azure does not have opinion for this user.
`
Are there any additional permissions required from 'istio-egress' to access secrets ?

**Reply by anumalasri** [reply]
We are running out of options .. Appreciate if any help here from anyone ?

**Reply by keithmattix** [reply]
It looks like this is an rbac error for the waypoint service acccount. When I get to my desk, I'll double check the permissions we give the waypoint

**Reply by keithmattix** [reply]
~@anumalasri do you have Azure RBAC configured on this cluster?~ Nevermind, I think I found the answer

**Comment by keithmattix** [comment]
Ok so I think this is a feature gap; waypoints currently don't have a role + rolebinding deployed with them so they can't list secrets in their namespace.

**Reply by anumalasri** [reply]
Thanks @keithmattix ..  Please let us know required additional role + rolebinding to be added to read secrets. 

Is there any other way to inject certs into waypoint and use them as file based certificates ?

We can give a try and test it out.

**Reply by keithmattix** [reply, marked as answer]
You can create it yourself with something like:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: egress-waypoint
  namespace: istio-egress
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: egress-waypoint
  namespace: istio-egress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: egress-waypoint
subjects:
- kind: ServiceAccount
  name: egress-waypoint
```
Applying that should get you where you want to go. We're discussing the tradeoffs of doing this automatically in Slack; please join if you'd like to participate: https://istio.slack.com/archives/C049TCZMPCP/p1734459320294559
