### DISCUSSION TITLE
Relative ordering of extensionProviders causing listener draining

### DISCUSSION THREAD

**Discussion by yasaswyk** [istio/istio#54354] [Q&A]
Hi!

I've configured istio's meshConfig to look like this:
```
meshConfig:
  defaultProviders:
    accessLogging:
      - envoy
      - otel
  extensionProviders:
    - envoyOtelAls:
         logFormat:
           labels:
             authority: '%REQ(:AUTHORITY)%'
             content_type: '%REQ(CONTENT-TYPE)%'
             duration: '%DURATION%'
             <snip>
           text: envoy access log
        port: 4317
        service: <snip>
        name: otel
    - envoyFileAccessLog:
        logFormat:
          labels:
            authority: '%REQ(:AUTHORITY)%'
            bytes_received: '%BYTES_RECEIVED%'
            bytes_sent: '%BYTES_SENT%'
            <snip>
        path: /dev/stdout
      name: envoy
```

But I noticed that I have frequent updates to the `listener_modified` metric, which causes pods to drop connections which I can see using the `downstream_cx_active` metric. After looking at the listener proxy-config dump, I noticed that the order of `extensionProviders` is not stable. Sometimes `envoyOtelAls` is first in the list and sometimes `envoyFileAccessLog` is first.

Is there a way to order the list to make it stable and not drop my connections periodically? I'm using Istio 1.20.2
