### DISCUSSION TITLE
Istio TCP L4 Matching not working ?

### DISCUSSION THREAD

**Discussion by lmq1999** [istio/istio#54407] [Q&A]
I have a Gateway like this:

```
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: tcp-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: tcp
      number: 8999
      protocol: TCP
```

And Virtual Service:

```
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: tcp-routing-1
  namespace: istio-system
spec:
  gateways:
  - tcp-gateway
  hosts:
  - '*'
  tcp:
  - match:
    - destinationSubnets:
      - 10.93.23.83
    route:
    - destination:
        host: nginx-service.nginx1.svc.cluster.local
        port:
          number: 80
  - match:
    - destinationSubnets:
      - 10.93.136.40
    route:
    - destination:
        host: nginx-service.nginx2.svc.cluster.local
        port:
          number: 80
```

But when I request into istio, all the request route to nginx1 service

I want the request into IP 10.93.23.83 -> nginx-service.nginx1.svc.cluster.local:80 and request IP 10.93.136.40 -> nginx-service.nginx2.svc.cluster.local:80

I dont know where i was wrong 

```
│ [2024-12-19T02:51:00.510Z] "- - -" 0 - - - "-" 74 203 4 - "-" "-" "-" "-" "10.200.0.155:80" outbound|80||nginx-service.nginx1.svc.cluster.local 10.200.1.78:45894 10.93.136.40:16443 123.30.48.139:58418 - -                                                                                                                                                                      │
│ [2024-12-19T02:51:00.662Z] "- - -" 0 - - - "-" 74 203 6 - "-" "-" "-" "-" "10.200.0.155:80" outbound|80||nginx-service.nginx1.svc.cluster.local 10.200.1.78:45898 10.93.23.83:16443 123.30.48.139:34022 - -   
```  

Version:

```
quanlm@quanlm-desktop:~$ istioctl version
client version: 1.24.1
control plane version: 1.24.1
data plane version: 1.24.1 (6 proxies)
```

```
(base) quanlm@quanlm-desktop:~$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.31.1
Kustomize Version: v4.5.7
Server Version: v1.31.1
```

Install:

I install using the command: `istioctl install --set profile=demo`
