### DISCUSSION TITLE
AuthorizationPolicy for Ingress gateway in ambient mode

### DISCUSSION THREAD

**Discussion by plstryagain** [istio/istio#54440] [Q&A] [answered]
With Istio 1.20 I had:

Ingress

```yaml
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: tools-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway-internet
  servers:
  - hosts:
    - kibana.example.com
    port:
      name: https-kibana
      number: 443
      protocol: HTTPS
    tls:
      credentialName: kibana-cert
      minProtocolVersion: TLSV1_2
      mode: SIMPLE
```

VirtualService
```yaml
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: kibana
  namespace: logging
spec:
  gateways:
  - istio-system/tools-gateway
  - mesh
  hosts:
  - kibana.example.com
  http:
  - match:
    - scheme:
        exact: http
    redirect:
      scheme: https
  - route:
    - destination:
        host: kibana.logging.svc.cluster.local
        port:
          number: 5601
````

and AuthorizationPolicy
```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-nothing
  namespace: istio-system
spec:
  action: ALLOW
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-tools
  namespace: istio-system
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        ipBlocks:
        - 192.168.0.10
    to:
    - operation:
        hosts:
        - kibana.example.com
  selector:
    matchLabels:
      app: istio-ingressgateway
```

After upgrading to Istio 1.24.1 with enabled ambient mode, "allow-nothing" policy seems to have started blocking all traffic in the cluster, not just for ingress.

Also policy "allow-tools" has status:
```yaml
status:
  conditions:
  - lastTransitionTime: "2024-12-21T08:29:03.209791240Z"
    message: ztunnel does not support HTTP rules (hosts require HTTP parsing), in
      ambient mode you must use waypoint proxy to enforce HTTP rules. Allow rules
      with HTTP attributes will be empty and never match. This is more restrictive
      than requested.
    reason: UnsupportedValue
    status: "True"
    type: ZtunnelAccepted
```
despite this, looks like the policy still allows access to this specific host _kibana.example.com_ from my IP only.

So the question is: Is this approach for accessing a specific host from a specific IP still valid? And I can safely ignore the message?

I also tried Waypoint approach (if I've got it right):
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    ...
    istio.io/ingress-use-waypoint: "true"
  name: kibana
  namespace: logging
...
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-tools
  namespace: logging
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        ipBlocks:
        - 192.168.0.10
    to:
    - operation:
        hosts:
        - kibana.example.com
  targetRefs:
  - name: waypoint
    kind: Gateway
    group: gateway.networking.k8s.io
```
But in this case it looks like the Waypoint doesn't know about the host "kibana.example.com".
In addition, this policy becomes too restrictive and you need to explicitly allow all other interactions in namespace (e.g. kibana -> elasticsearch).
