### DISCUSSION TITLE
Isitio ambient with service entry

### DISCUSSION THREAD

**Discussion by Rory-Z** [istio/istio#54480] [Q&A] [answered]
Hi Team, I tested istio ambient follow this blog: https://www.solo.io/blog/egress-gateways-made-easy, I deploy istio by argocd like this:
```YAML
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    app: istio
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: base
      targetRevision: 1.24.2
      helm:
        releaseName: "istio-base"
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: istiod
      targetRevision: 1.24.2
      helm:
        releaseName: "istiod"
        parameters:
          - name: profile
            value: ambient
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: cni
      targetRevision: 1.24.2
      helm:
        releaseName: "istio-cni"
        parameters:
          - name: profile
            value: ambient
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: ztunnel
      targetRevision: 1.24.2
      helm:
        releaseName: "ztunnel"
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
```

And I create waypoint and other resources like this
```YAML
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: istio-egress
  namespace: istio-system
  annotations:
    networking.istio.io/service-type: ClusterIP
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - name: mesh
    port: 15008
    protocol: HBONE
    allowedRoutes:
      namespaces:
        from: All

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: istio-egress
    istio.io/use-waypoint-namespace: istio-system
  name: istio-demo
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: httpbin-ext
  namespace: istio-demo
  labels:
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: istio-egress
    istio.io/use-waypoint-namespace: istio-system
spec:
  hosts:
  - httpbin.org
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL

---
apiVersion: v1
kind: Pod
metadata:
  name: curl
  namespace: istio-demo
  labels:
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: istio-egress
    istio.io/use-waypoint-namespace: istio-system
spec:
  containers:
  - name: curl
    image: curlimages/curl
    command:
    - tail
    - -f
    - /dev/null

```

But when I doing curl in curl pod, I got this:
```
~ $ curl httpbin.org/get -v
* Host httpbin.org:80 was resolved.
* IPv6: (none)
* IPv4: 3.218.7.103, 34.226.108.155
*   Trying 3.218.7.103:80...
* Connected to httpbin.org (3.218.7.103) port 80
* using HTTP/1.x
> GET /get HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/8.11.1
> Accept: */*
>
* Request completely sent off
< HTTP/1.1 200 OK
< Date: Fri, 27 Dec 2024 02:49:26 GMT
< Content-Type: application/json
< Content-Length: 252
< Connection: keep-alive
< Server: gunicorn/19.9.0
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
<
{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Host": "httpbin.org",
    "User-Agent": "curl/8.11.1",
    "X-Amzn-Trace-Id": "Root=1-676e15b6-085b87c10ba7e8ad31b77a34"
  },
  "origin": "35.90.9.222",
  "url": "http://httpbin.org/get"
}
* Connection #0 to host httpbin.org left intact
```

Looks it didn't use istio-envoy, Did I do anything wrong? 
I have already check logs of `ztunnel / cni / istiod`, and didn't found anything about this case.
