### DISCUSSION TITLE
Support multiple GW in ambient mode

### DISCUSSION THREAD

**Discussion by OteemoSanjay** [istio/istio#54487] [Q&A]
hi

We have istio 1.22.x in the old method.   We have multiple GW.  Public/ Private and Server GW.
How do we support these GW in the new ambient mode?

Operator yaml.  Installed via istioctl.  
CMD :  istioctl install -f <<YAML FILE>>

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
    accessLogEncoding: JSON
    defaultConfig:
      holdApplicationUntilProxyStarts: true

  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          service:
            type: NodePort
            ports:
              - port: 80
                targetPort: 8080
                name: http2
                nodePort: 31380
              - port: 443
                nodePort: 32001
                name: https
      - name: istio-private-ingressgateway
        label:
          istio: istio-private-ingressgateway
        enabled: true
        k8s:
          service:
            type: NodePort
            ports:
              - port: 80
                targetPort: 8080
                name: http2
                nodePort: 31381
              - port: 443
                nodePort: 32002
                name: https
      - name: istio-server-ingressgateway
        label:
          istio: istio-server-ingressgateway
        enabled: true
        k8s:
          service:
            type: NodePort
            ports:
              - port: 80
                targetPort: 8080
                name: http2
                nodePort: 31382
              - port: 443
                nodePort: 32003
                name: https
      - name: istio-apiprivate-ingressgateway
        label:
          istio: istio-apiprivate-ingressgateway
        enabled: true
        k8s:
          service:
            type: NodePort
            ports:
              - port: 80
                targetPort: 8080
                name: http2
                nodePort: 31383
              - port: 443
                nodePort: 32004
                name: https
  values:
    gateways:
      istio-ingressgateway:
        runAsRoot: true
        type: NodePort
      # istio-private-ingressgateway:
      #   runAsRoot: true
      #   type: NodePort
      # istio-server-ingressgateway:
      #   runAsRoot: true
      #   type: NodePort

```
