### DISCUSSION TITLE
Traffic split using is not happening using virtual service outside the mesh but within the cluster.

### DISCUSSION THREAD

**Discussion by ajaydevtron** [istio/istio#54538] [Q&A]
We have deployed the latest version of Istio (1.24.2) using a Helm chart.

I have deployed an application using a Kubernetes Deployment and Service(name backend) in the backend namespace, where Istio auto-injection is enabled. A VirtualService has been created for this application to split traffic equally (50% to version v1 and 50% to version v2).
1. When accessing the application from a pod with Istio sidecar injection enabled, the traffic splits correctly and works as expected.
2. When accessing the application externally via the hostname (e.g., [backend.xyz.com](http://backend.xyz.com/)) using the ingress gateway, traffic splitting also works, as the ingress gateway pod enforces the routing rules.
However, when accessing the backend service from another pod within the same cluster (in the frontend namespace) without Istio sidecar injection, the traffic splitting does not occur , my frontend service is exposed through ALB and don’t want to put that inside the mesh.

I would like to achieve traffic splitting for requests originating from this **non-sidecar-injected** pod as well.
Could you suggest any possible workarounds to address this issue?

**Comment by howardjohn** [comment]
You will need to go through the ingress to accomplish this. or add a sidecar to the client

**Reply by ajaydevtron** [reply]
Hello  @howardjohn 

You mean using the ingress gateway? If yes the traffic flow works like this:

backend.xyz.com -> ingress gateway load balancer -> split traffic to backend service
The backend service should not be exposed outside the cluster through a load balancer because it is intended to operate only within the cluster.
What is the best approaches you would recommend to address this, apart from adding sidecar to client ?

Thanks in advance :pray:

**Reply by howardjohn** [reply]
You can make another gateway that is not exposed externally and only has a ClusterIP assigned

**Reply by ajaydevtron** [reply]
I have just install the ingress gateway with service type **ClusterIP** deployed using helm chart (https://istio-release.storage.googleapis.com/charts)

I am looking for documentation or guidance on how to use a ClusterIP ingress gateway to create a gateway for my application and configure it in **virtualservice** for internal cluster use.

The following two documents mainly show examples of using a LoadBalancer type ingress gateway to expose services outside the cluster:

[Istio Ingress Gateway Control Documentation](https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-control/)
[StackOverflow: How to Create an Internal Gateway Using Istio](https://stackoverflow.com/questions/59604397/how-do-i-create-an-internal-gateway-using-istio)


Could you please provide documentation or steps on using a **ClusterIP ingress gateway** to access applications within the cluster?

Thanks 🙏

**Reply by howardjohn** [reply]
https://artifacthub.io/packages/helm/istio-official/gateway#examples has an example

**Comment by ajaydevtron** [comment]
Hello @howardjohn 

To achieve this use case, I implemented the following configuration:

I created another Service for my application using the **ExternalName** type, as shown below:

```
apiVersion: v1
kind: Service
metadata:
  name: myapp-proxy-service
  namespace: test-canary
spec:
  externalName: gateway-controller-istio-system.istio-system.svc.cluster.local
  sessionAffinity: None
  type: ExternalName
status:
  loadBalancer: {}
```
**Gateway Configuration**
This is the Gateway object I configured for my application:

```
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: app-internal-gateway
  namespace: test-canary
spec:
  selector:
    app: gateway-controller-istio-system
    istio: gateway-controller-istio-system
  servers:
    - hosts:
        - myapp-proxy-service.test-canary.svc.cluster.local
      port:
        name: http
        number: 80
        protocol: HTTP
```

**VirtualService Configuration**
Below is the VirtualService configuration:
```
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: rollout-4-test-canary
  namespace: test-canary
spec:
  gateways:
    - app-internal-gateway
  hosts:
    - myapp-proxy-service
    - rollout-4-test-canary ##This is my original svc of application
  http:
    - match:
        - uri:
            prefix: /
      retries:
        attempts: 3
        perTryTimeout: 1s
        retryOn: gateway-error,connect-failure,refused-stream
      rewrite:
        uri: /
      route:
        - destination:
            host: rollout-4-test-canary-primary
          weight: 50
        - destination:
            host: rollout-4-test-canary-canary
          weight: 50

```

With this setup, traffic splitting is happening outside the mesh when accessing my application via the FQDN:
**myapp-proxy-service.test-canary.svc.cluster.local** within the cluster.
