### DISCUSSION TITLE
Not able to enable OTEL Tracing in istio

### DISCUSSION THREAD

**Discussion by bazingarj** [istio/istio#54576] [General]
**values.yaml**
```
meshConfig:
  enableTracing: true
  extensionProviders:
    - name: otel-tracing
      opentelemetry:
        port: 4317
        service: otel-collector.logging.svc.cluster.local
        resource_detectors:
          environment: {}
```
**Telemetry Config:**
```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
   name: otel-demo
   namespace: istio-system
spec:
  tracing:
  - providers:
    - name: otel-tracing
    randomSamplingPercentage: 100
```
**EKS version:** 1.29
**Istio Version:** 1.19.1
**Expected Outcome:** Istio Envoy Proxy Traces must be visible in observability Tool e.g. Elasticsearch or grafana,
Would anybody be able to help ?
