### DISCUSSION TITLE
How to Receive External Traffic Using Gateway API on Amazon EKS

### DISCUSSION THREAD

**Discussion by YusukeSugiyamaTG** [istio/istio#54598] [Q&A]
Hi Team,

I am trying to implement Istio's Gateway API on an externally exposed application running on Amazon EKS.
Currently, I use the Istio ingress gateway, designating the Istio ingress gateway Pod as a target for AWS ALB, and manage traffic using Gateway and Virtual Service. (I’m not entirely confident whether this approach is appropriate, though…)

To adopt the Gateway API, I built the following configuration:

![EKS-Ingress-design-Jan-2025-Gateway-API-pettern](https://github.com/user-attachments/assets/1a5dfe95-d18d-491a-94ec-c85a74bfab1d)

While communication works as intended, I’m unsure whether this setup—where the Gateway-provisioned service (or more specifically, the Pod, according to AWS Load Balancer Controller specifications) uses its IP address as the target for ALB—is the right approach.

When using AWS Load Balancer Controller, an internal NLB is created whenever a `type: LoadBalancer` service is provisioned. Since this setup cannot accept external traffic directly, I had previously used `type: NodePort` when working with the Istio ingress gateway. However, in this case, the service provisioned by the Gateway (as of now) does not allow changing its `type`, so I’ve resorted to this configuration. (I hope this will be addressed in the following issue.)
https://github.com/istio/istio/issues/46594

I would greatly appreciate any advice regarding potential issues or concerns with this setup.

**Comment by dudicoco** [comment]
You can use the `service.beta.kubernetes.io/aws-load-balancer-*` annotations to configure the load balancer.
Any annotations you set on the gateway will be passed to the service object.
By default the in-tree cloud provider is used to provision the LB, which is more limited.
In order to use the AWS LB controller to provision an external NLB use these annotations:
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cool
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
```

See the docs for more info: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.11/guide/service/annotations/#annotations
