### DISCUSSION TITLE
Help with Ambient and Kubernetes NetworkPolicy

### DISCUSSION THREAD

**Discussion by plstryagain** [istio/istio#54650] [Q&A] [answered]
I need help understanding how NetworkPolicy work with Istio in ambient mode

My setup:
Kubernetes v1.29.2 bare metal
Calico v3.29.1
Istio v1.24.1

What I'm trying to achieve:
* restrict access to service *ppa-api* in namespace *ppa* only from Ingress Gateway, Prometheus and other services in namespace *ppa*
* restrict access from *ppa-api* only to service *code-system-api* in namespace term, to service *proxy* in namespace *iehr* and any service in namespace ppa

So I ended up with this NetworkPolicy (without ambient mode):
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ppa-api
  namespace: ppa
spec:
  egress:
  # everything in namespace ppa
  - to:
    - podSelector: {}
  # access to kube-dns
  - ports:
    - port: 53
      protocol: UDP
    to:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          k8s-app: kube-dns
  # access to service code-system-api in namespace term
  - ports:
    - port: 8080
      protocol: TCP
    to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: term
      podSelector:
        matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values:
          - code-system-api
  # access to service proxy in namespace iehr
  - ports:
    - port: 8080
      protocol: TCP
    to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: iehr
      podSelector:
        matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values:
          - proxy
  ingress:
  # from everything in namespace ppa
  - from:
    - podSelector: {}
    ports:
    - port: 8080
      protocol: TCP
  # from ingress gateway
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: istio-system
      podSelector:
        matchLabels:
          istio: ingressgateway-internet
    ports:
    - port: 8080
      protocol: TCP
  # from prometheus
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: monitoring
      podSelector:
        matchLabels:
          app.kubernetes.io/name: prometheus-node-exporter
  podSelector:
    matchLabels:
      app.kubernetes.io/name: ppa-api
  policyTypes:
  - Ingress
  - Egress
```
I tested this policy with debug container attached to *ppa-api* and it worked as expected:
```sh
curl http://code-system-api.term.svc.cluster.local - 200
curl http://proxy.iehr.svc.cluster.local - 200
curl http://code-system-ui.term.svc.cluster.local - Operation timed out
```

After enabling ambient mode (with waypoints) I tried to modify NetworkPolicy as follows:
```yml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ppa-api
  namespace: ppa
spec:
  egress:
  # everything in namespace ppa
  - to:
    - podSelector: {}
  # access to kube-dns
  - ports:
    - port: 53
      protocol: UDP
    to:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          k8s-app: kube-dns
  # access to service code-system-api in namespace term
  - ports:
    - port: 8080
      protocol: TCP
    - port: 15008
      protocol: TCP
    to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: term
      podSelector:
        matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values:
          - code-system-api
  # access to service code-system-api in namespace term
  - ports:
    - port: 8080
      protocol: TCP
    - port: 15008
      protocol: TCP
    to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: iehr
      podSelector:
        matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values:
          - proxy
  ingress:
  # from everything in namespace ppa
  - from:
    - podSelector: {}
    ports:
    - port: 8080
      protocol: TCP
    - port: 15008
      protocol: TCP
  # from ingress gateway
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: istio-system
      podSelector:
        matchLabels:
          istio: ingressgateway-internet
    ports:
    - port: 8080
      protocol: TCP
    - port: 15008
      protocol: TCP
  # from prometheus
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: monitoring
      podSelector:
        matchLabels:
          app.kubernetes.io/name: prometheus-node-exporter
  podSelector:
    matchLabels:
      app.kubernetes.io/name: ppa-api
  policyTypes:
  - Ingress
  - Egress
```
All requests from debug container failed with error Connection reset by peer
ztunnel log:
```sh
error   access  connection complete     src.addr=10.244.127.11:37042 src.workload="ppa-api-6dfc54b775-mw25v" src.namespace="ppa" src.identity="spiffe://cluster.local/ns/ppa/sa/ppa-api" dst.addr=10.244.127.3:15008 dst.hbone_addr=10.102.74.12:80 dst.service="code-system-api.term.svc.cluster.local" dst.workload="waypoint-8c47449c4-l66w8" dst.namespace="term" dst.identity="spiffe://cluster.local/ns/term/sa/waypoint" direction="outbound" bytes_sent=0 bytes_recv=0 duration="10002ms" error="connection timed out, maybe a NetworkPolicy is blocking HBONE port 15008: deadline has elapsed"
```

Also I tried to add this:
```yml
...
  egress:
  - ports:
    - port: 15008
      protocol: TCP
...
```
but in this case I can curl any service in cluster from ppa-api container and any service in cluster can access ppa-api.

Does it mean that NetworkPolicy with Istio in ambient mode can work only with ports and not with podSelector\namespaceSelector? Or am I missing something?

**Comment by ilrudie** [comment]
Based on your logs it looks like you are sending traffic to a waypoint in the `term` namespace and the net policy for term namespace has a pod selector which would not include the waypoint:
```      podSelector:
        matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values:
          - code-system-api
 ```

**Reply by plstryagain** [reply]
Do you mean something like this?
```yml
  egress:
  - ports:
    - port: 8080
      protocol: TCP
    to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: term
      podSelector:
        matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values:
          - code-system-api
  - ports:
    - port: 15008
      protocol: TCP
    to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: term
      podSelector:
        matchLabels:
          gateway.networking.k8s.io/gateway-name: waypoint
```

In that case I can access any service in ``term``, not only ``code-system-api`` :(

For request *ppa-api.ppa -> waypoint.term -> code-system-api.term* from the CNI point of view, the request destination waypoint.term and it doesn't know anything about code-system-api.term?
