### DISCUSSION TITLE
istio.io/rev label Behaviour on Configuration Resources

### DISCUSSION THREAD

**Discussion by adyang-tw** [istio/istio#54684] [Q&A]
Hello, is there a documentation for which resources the `istio.io/rev` applies to and what the behaviour would be like?

For more specific context, I'm trying to find out the behaviour of having this label on the sidecar configuration:
```
kind: Sidecar
metadata:
  name: namespaced-sidecar
  namespace: my-namespace
  labels:
    istio.io/rev: 1-22-5
spec:
  egress:
    - hosts:
        - '*/*'
```

1. Does this mean that it only applies to proxies/pods connected to the 1-22-5 istiod control plane?
2. If we create another `Sidecar` resource with `istio.io/rev: 1-23-3`, is this supported istio behaviour? Meaning each of the 1-22-5 and 1-23-3 istiod control plane will have the respective namespaced sidecar configuration? Reason for asking is because in the [document for sidecar](https://istio.io/latest/docs/reference/config/networking/sidecar/), it specifically points out not to have 2 namespace-wide sidecar config with no workload selector as behaviour will be undefined. But doesn't cover the case for canaries using `istio.io/rev`. Example 2nd sidecar to create:
```
kind: Sidecar
metadata:
  name: namespaced-sidecar-1-23-3
  namespace: my-namespace
  labels:
    istio.io/rev: 1-23-3
spec:
  egress:
    - hosts:
        - '*/*'
```

Not directly relevant, but background context for need of this Sidecar workaround: https://github.com/istio/istio/issues/51747#issuecomment-2330236041
