### DISCUSSION TITLE
White screen ingress configuration.

### DISCUSSION THREAD

**Discussion by AleksFirsta** [istio/istio#54694] [Q&A] [answered]
I have very simple app which works via nodePort   
nodejs app run this page  

```plaintext
`<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite + React</title>
    <script type="module" crossorigin src="/assets/index-BOmzKVaV.js"></script>
    <link rel="stylesheet" crossorigin href="/assets/index-Ca74PG3G.css">
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>
```

deployment:  
 

```plaintext
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: mfe
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-world
  namespace: mfe
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world
    APP_ID: dda3835b-2c99-44cc-bdce-77ff5c401ae7
    version: latest
  name: hello-world
  namespace: mfe
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hello-world
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: hello-world
        app: hello-world
        version: v0.0.56
        spireSpiffeid: default
    spec:
      serviceAccountName: hello-world
      containers:
        - name: hello-world
          image: onprem-poc-app
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 1Gi
              cpu: 0.5
            requests:
              memory: 512Mi
              cpu: 0.25
          # volumeMounts:
          #   - name: config-volume
          #     mountPath: /config/data
          ports:
            - containerPort: 80
              protocol: TCP
              name: app-port
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-registry
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app: hello-world
  namespace: mfe
spec:
  ports:
    - port: 3000
      targetPort: 80
  selector:
    name: hello-world
```

Istio resources:  
  
 

```plaintext
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: hello-world-app
  namespace: mfe
spec:
  hosts:
  - "*"
  gateways:
  - hello-world-gw
  http:
  - match:
    - uri:
        prefix: "/hello"
    rewrite:
      uri: "/"
    route:
    - destination:
        host: hello-world
        port:
          number: 3000
      headers:
        response:
           add:
             x-test: "true"
             Content-Type: "text/html"
  - route:
    - destination:
        host: hello-world
        port:
          number: 3000
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: hello-world-gw
  namespace: mfe
spec:
  selector:
    istio: ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
```

The problem is next: If I'm removing default route in VirtualService its give me blank page  
In devtool → network I see that  GET to `localhost:30010/assets/index-BOmzKVaV.js` - 404 

at the same time with default route it works good.   
  
What I need to check again?

**Comment by howardjohn** [comment]
If you don't have the default route, you are only matching `/hello` so `/assert/index-BOmzKVaV.js` would not match?

**Reply by AleksFirsta** [reply]
@howardjohn  Thanks for quick response 

with default route + /hello I see correct page and both pages return custom header Version: default and version: 1
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: hello-world-app
  namespace: mfe
spec:
  hosts:
  - "*"
  gateways:
  - hello-world-gw
  http:
  - match:
    - uri:
        prefix: "/hello"
    route:
    - destination:
        host: hello-world
        port:
          number: 3000
      headers:
        response:
          add:
            version: "1"
  - route:
    - destination:
        host: hello-world
        port:
          number: 3000
      headers:
        response:
          add:
            version: "default"
```

It means that we need to have default route mandatory ?
