### DISCUSSION TITLE
Support for AuthorizationPolicy with contains esque rule

### DISCUSSION THREAD

**Discussion by lyngekpdxc** [istio/istio#54736] [Ideas]
Authorization policy when condition with contains match

Is it possible to make a rule that functions like a "contains" match in istio authorization policies?
We have a custom ext-auth policy already that verifies a SAML Assertion, extracts user information, groups and translates said groups into a set of roles. This is all returned as headers in upstream.

I have tested that I can make another authorization policy and create rules for these headers.
However I am having trouble with list type headers, i.e. roles.
I would like to create a rule that allows access to a resource based on the presence of a role in the list. However, the documentation states that only exact, prefix, suffix and presence match is supported.

I would have expected something simple as the below would work. However it does not.
```
spec:
  selector:
    matchLabels:
      app: appname
  action: ALLOW
  rules:
  - to:
      - operation:
          paths: ["*"]
    when:
      - key: request.headers[x-user-roles]
        values: ["*trustedrole*"]
```

If I only include 2 roles I am able to match using either prefix or suffix match, but this is not viable as most use cases feature many roles at once.

Is something like this attainable in some way with Istio? Perhaps using some other mechanism?
I feel like this would be a very common use case and that this would be fairly easy to support. Perhaps the istio team can clarify or add support for this in the future?

**Comment by lyngekpdxc** [comment]
Current workaround is to add separate role/group headers for each individual role and make matchers based on this.
```
spec:
  selector:
    matchLabels:
      app: appname
  action: ALLOW
  rules:
  - to:
      - operation:
          paths: ["*"]
    when:
      - key: request.headers[role_trustedrole]
        values: ["*"]
```

This works. However incur some limitations compared to using values, e.g. stricter content requirements for country specific characters.
