### DISCUSSION TITLE
How to implement sidecar egress configuration in ambient mode?

### DISCUSSION THREAD

**Discussion by angelosanramon** [istio/istio#54734] [General]
I am trying to restrict outgoing traffic in a pod to a specific service. I have the following sidecar configuration in Istio sidecar mode. How do I implement a similar configuration in ambient mode?
```
apiVersion: networking.istio.io/v1
kind: Sidecar
metadata:
  name: bookinfo-reviews-istio-sidecar
  namespace: bookinfo
spec:
  workloadSelector:
    labels:
      app: bookinfo-reviews
  ingress:
    - port:
        name: http
        number: 9080
        protocol: HTTP
  egress:
    - hosts:
      - ./bookinfo-ratings.bookinfo.svc.cluster.local
      port:
        name: http
        number: 9080
        protocol: HTTP
```

In ambient mode, I created this network policy. But the egress part is not working.
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: bookinfo-reviews-network-policy
  namespace: bookinfo
spec:
  podSelector:
    matchLabels:
      app: bookinfo-reviews
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: bookinfo-productpage
      ports:
      - port: 9080
        protocol: TCP
      - port: 15008
        protocol: TCP
  egress:
    - ports:
      - port: 9080
        protocol: TCP
      to:
      - podSelector:
          matchLabels:
            app: bookinfo-ratings
```
