### DISCUSSION TITLE
Equivalents to Envoy retry policies in the Kubernetes Gateway API

### DISCUSSION THREAD

**Discussion by uB4nshee** [istio/istio#54766] [Q&A]
Hello to everyone!

We are migrating our manifests from the Istio API (networking.istio.io) to the API Gateway API (gateway.networking.k8s.io) and we are faced with the following situation:

In the `spec.http.retries.retryOn` field of the **Istio VirtualService** we have the following values coming from the Envoy retry policies: `gateway-error, connect-failure, refused-stream`.

Here's an example below:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nginx
  namespace: apps
spec:
  hosts:
    - nginx.apps.svc.cluster.local
  http:
    - retries:
        attempts: 4
        perTryTimeout: 500ms
        retryOn: gateway-error,connect-failure,refused-stream
      route:
        - destination:
            host: nginx.apps.svc.cluster.local
            port:
              number: 80
```

We would like to know what the equivalent values would be in the `spec.rules.retry.codes` field in the **Gateway API**? 
Reading the official documentation I saw that the field only accepts **int values**, so I couldn't pass the same values from the Istio API.

Below is an example of the migration of this Virtual Service to HTTPRoute:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nginx
  namespace: apps
spec:
  parentRefs:
    - kind: Service
      name: nginx
      namespace: apps
  hostnames:
    - nginx.apps.svc.cluster.local
  rules:
    - retry:
        codes: [] # What do I fill in here to maintain equivalence?
        attempts: 4
        backoff: 500ms
      backendRefs:
        - name: nginx
          namespace: apps
          port: 80
```

Does anyone know what values we can use to maintain equivalence or **how we can use experimental features of the api gateway**?
