### DISCUSSION TITLE
Is it possible to create a "deny all by default" authorization policy per namespace with explicit policies per workloads?

### DISCUSSION THREAD

**Discussion by gregory-hive** [istio/istio#54763] [Q&A] [answered]
### What I'm trying to achieve:

- Implement a catch-all deny-all authorization policy at the namespace level to block all traffic by default.

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-all
  namespace: my-namespace
spec:
  action: DENY
  rules:
  - {}
```

- Allow specific workloads within the namespace to receive traffic explicitly by defining workload-specific ALLOW policies.

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: app-name
  namespace: my-namespace
spec:
  action: ALLOW
  selector:
    matchLabels:
      app: app-name
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/my-namespace-2/sa/allowed-app
```

### Results:

- With the namespace-level DENY policy, all traffic to the namespace is blocked
- The workload-specific ALLOW policy does not override the DENY policy, so even explicitly allowed traffic to the workload is denied.
- Alternatively, with an ALLOW policy at the namespace level - it opens traffic for all workloads, even the one which is supposed to be denied by the individual workload's policies 

### Question
Could someone confirm that it is impossible to achieve a true "deny-by-default" at the namespace level while having granular workload-specific ALLOW policies without compromising the namespace-wide block? Or is there a mistake in my configuration?
