### DISCUSSION TITLE
Visibility for retries on 5xx with some logs or metrics on istio

### DISCUSSION THREAD

**Discussion by AbhishekKandoi314e** [istio/istio#54838] [Q&A]
Hi everyone,
I'm currently using Istio 1.23.1 with istio-ingressgateway as my primary entry point. Most of my deployments don't have sidecar injection. I've implemented retry policies within my VirtualServices, and I've confirmed that the retry logic is functioning as expected.
However, I'm struggling to gain visibility into when retries actually occur. I'm not seeing any obvious logs or metrics indicating that a retry has been initiated. This lack of visibility makes it difficult to troubleshoot or optimize my retry configurations. I have tried my istio-ingressgateway logs as well there is no entry in that. I tried with some metrics as well still those are not reflecting the retries.

Specifically, I'm wondering:

- Are there specific logs I should be looking for (at the gateway level perhaps) to identify retries?
- Are there any metrics that expose retry counts or other retry-related information that I can monitor?
- Is there any specific configuration I might be missing to enable this kind of logging or metrics?

This is a test VirtualService I am using:-
```
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: nginx-vs
  namespace: nginx-test
spec:
  gateways:
  - istio-system/istiogateway
  hosts:
  - nginx-test.domain.tech
  http:
  - match:
    - uri:
        prefix: /
    retries:
      attempts: 10
      perTryTimeout: 2s
      retryOn: 5xx,connect-failure,refused-stream
    route:
    - destination:
        host: nginx-service.nginx-test.svc.cluster.local
        port:
          number: 80
```
