### DISCUSSION TITLE
deploy mariadb error

### DISCUSSION THREAD

**Discussion by codeMonkey-shin** [istio/istio#54929] [Q&A] [answered]
Hello,

I am experiencing an issue where I cannot establish a connection to my MariaDB service using the Istio Gateway and VirtualService configurations as defined below.

### **Deployment and Service Configuration:**

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  type: ClusterIP
  selector:
    app: mariadb
  ports:
  - port: 3306
    targetPort: 3306
```

### **Istio Gateway Configuration:**

```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: cm-db-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 3306
      name: tcp-mariadb
      protocol: TCP
    hosts:
    - "db.mydomain.com"
```

### **Istio VirtualService Configuration:**

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: cm-db-virtualservice
  namespace: istio-system
spec:
  hosts:
  - "db.mydomain.com"
  gateways:
  - cm-db-gateway
  tcp:
  - match:
    - port: 3306
    route:
    - destination:
        host: mariadb-service.default.svc.cluster.local
        port:
          number: 3306
```

### **Issue Details:**

- **Problem:** Despite deploying the above configurations, I am unable to connect to the MariaDB service from outside the cluster. The connection attempts either time out or are refused.
- **What I've Checked:**
  - The MariaDB pod is running, and the service is active within the cluster.
  - The Istio ingress gateway is deployed and seems to be functioning correctly.
  - There are no apparent typos or misconfigurations in the hostnames, ports, or selectors.
- **Expected Behavior:** I should be able to connect to the MariaDB instance using `db.mydomain.com` on port `3306` through the Istio ingress gateway.

### **Environment:**

- **MariaDB Image:** `mariadb:latest`

### **Request for Assistance:**

I would appreciate any help in identifying the cause of this connectivity issue. Is there something missing or incorrectly configured in my setup? Any suggestions or guidance would be greatly appreciated.

Thank you!
