### DISCUSSION TITLE
multicluster multi-primary route traffic to a subset using VS & DR from remote cluster.

### DISCUSSION THREAD

**Discussion by kshitijmjoshi** [istio/istio#54932] [Q&A]
I have a 3 cluster istio multicluster set up in multi-primary mode and all of them are reachable/routable from each other. Using pod labels, VirtualService & DestinationRule subsets, I'm able to route traffic to a particular cluster as required. Here's my simplified situation.

Cluster A has some applications deployed on it. Clusters B and C are identical but some applications are active in cluster B but standby in C and vice versa.

The VirtualService & DestinationRules for the applications in B and C are present in both the B & C clusters and traffic flow is controlled using subsets (requirement is 100% of traffic flowing to 1 cluster).

Consider this example, helloworld deployment and it's VS & DR are deployed to cluster B & C
```
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: helloworld-route
spec:
  hosts:
  - helloworld.sample.svc.cluster.local
  http:
  - name: "helloworld-route"
    route:
    - destination:
        host: helloworld.sample.svc.cluster.local
        # routes traffic to cluster b 
        subset: kind-cluster-b 
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: helloworld-destination
spec:
  host: helloworld.sample.svc.cluster.local
  subsets:
    - name: kind-cluster-b
      labels:
        cluster: kind-cluster-b
    - name: kind-cluster-c
      labels:
        cluster: kind-cluster-c
```
This works fine for traffic originating from clusters B or C.
Traffic originating from Cluster A is loadbalanced because the helloworld's VS & DR are not deployed in cluster A.

Without going over ingressgateway, deploying the helloworld VS & DR in cluster A or defining a ServiceEntry for helloworld in cluster A, is is possible for the traffic originating from cluster A to be routed as per the rules from VS & DR in cluster B/C? Or have istio import VS & DR from the connected cluster?
