### DISCUSSION TITLE
Reducing Istio proxy resource consumption：“Headless Service + Endpoint” or ServiceEntry

### DISCUSSION THREAD

**Discussion by tjccwccwcc** [istio/istio#54978] [General]
### Description:
Currently, I'm managing external databases in my Kubernetes cluster using “**Headless Service (without selector) + Endpoint**", with **both monitoring and business ports** set in the service and endpoints. However, when the number of databases increases, the memory usage of the Istio proxy becomes very high. To reduce memory usage, I am considering the following two solutions:

- **Solution 1**: Remove the monitoring port from the service, keeping both monitoring and business ports in the endpoints.
- **Solution 2**: Use ServiceEntry to manage the databases, keeping only the business port. Retain only the monitoring port in the service and endpoints, and add the annotation 【networking.istio.io/exportTo: '~'】 to the service.

### Example:
**Current**
```
apiVersion: v1
kind: Service
metadata:
  name: cassandra-service
  namespace: example
spec:
  clusterIP: None
  ports:
    - name: tcp-cassandra
      port: 9042
      protocol: TCP
      targetPort: 9042
    - name: tcp-prometheus
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: node-exporter
      port: 8082
      protocol: TCP
      targetPort: 8082
  type: ClusterIP
```
```
apiVersion: v1
kind: Endpoints
metadata:
  name: cassandra-service
  namespace: example
subsets:
  - addresses:
      - ip: #my cassandra EC2 ip
    ports:
      - name: tcp-cassandra
        port: 9042
        protocol: TCP
      - name: tcp-prometheus
        port: 8080
        protocol: TCP
      - name: node-exporter
        port: 8082
        protocol: TCP
```
**Solution 1**
```
apiVersion: v1
kind: Service
metadata:
  name: cassandra-service
  namespace: example
spec:
  clusterIP: None
  ports:
    - name: tcp-cassandra
      port: 9042
      protocol: TCP
      targetPort: 9042
  type: ClusterIP
```
```
apiVersion: v1
kind: Endpoints
metadata:
  name: cassandra-service
  namespace: example
subsets:
  - addresses:
      - ip: #my cassandra EC2 ip
    ports:
      - name: tcp-cassandra
        port: 9042
        protocol: TCP
      - name: tcp-prometheus
        port: 8080
        protocol: TCP
      - name: node-exporter
        port: 8082
        protocol: TCP
```
**Solution 2**
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: cassandra-serviceentry
  namespace: example
spec:
  endpoints:
    - address: #my cassandra EC2 ip
  hosts:
    - cassandra-service.example
  location: MESH_EXTERNAL
  ports:
    - name: tcp-cassandra
      number: 9042
      protocol: TCP
  resolution: STATIC
```
```
apiVersion: v1
kind: Service
metadata:
  name: cassandra-service
  namespace: example
spec:
  clusterIP: None
  ports:
    - name: tcp-prometheus
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: node-exporter
      port: 8082
      protocol: TCP
      targetPort: 8082
  type: ClusterIP
```
```
apiVersion: v1
kind: Endpoints
metadata:
  name: cassandra-service
  namespace: example
subsets:
  - addresses:
      - ip: #my cassandra EC2 ip
    ports:
      - name: tcp-prometheus
        port: 8080
        protocol: TCP
      - name: node-exporter
        port: 8082
        protocol: TCP
```
### Current Findings:
Both solutions can access the database normally and achieve the following functionalities:
- **Monitoring Metrics**: Obtain the source of workloads accessing the database, data transfer rate, and number of connections.
- **Traffic Control**: Implement TCP routing based on weights, enabling canary upgrades for the database.
- **Circuit Breaking and Rate Limiting**: Achieve TCP connection circuit breaking and rate limiting through DestinationRule and EnvoyFilter.
- **Reduced Istio Proxy Configuration**: Both solutions reduce Istio proxy configurations (lowering Istio proxy memory usage) and allow Prometheus metrics for external databases to be obtained through ServiceMonitor.
### Question
- In Solution 1, the ports in the Service and Endpoint are different. **Does this comply with Kubernetes or Istio specifications**?
- The main difference between Solution 2 and Solution 1 is that the business traffic uses ServiceEntry to access the external databases. **Does ServiceEntry provide more advanced features** compared to "Service + Endpoint"?

Since Solution 1 involves fewer modifications and Solution 2 requires more significant changes, I hope to determine if **Solution 1 is feasible** based on the above questions, or if **Solution 2 is more compliant with standards and offers additional features** to replace Solution 1.
