### DISCUSSION TITLE
Istio Ambient - AuthorizationPolicy not working

### DISCUSSION THREAD

**Discussion by shreyansmaloo** [istio/istio#54987] [Q&A]
Hello everyone,

I have set up a Kubernetes cluster using with Istio in Ambient Mode, using GatewayAPI and HTTPRoute to route requests. I have also installed the required CRDs for GatewayAPI and created a test namespace

I have also configured RequestAuthentication and AuthorizationPolicy to validate JWT tokens and enforce authorization.

However, when sending an invalid JWT token, there is no validation error or rejection. In contrast, the same configuration works as expected with sidecar proxy mode. I'm wondering if I might have missed something in my setup for Ambient Mode.

Below is my manifest file:

# RequestAuthentication configuration for JWT validation
```
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: auth0-jwt-auth
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: my-app
  jwtRules:
    - issuer: "https://dev-powerverse-tenant-1.us.auth0.com/"
      jwksUri: "https://dev-powerverse-tenant-1.us.auth0.com/.well-known/jwks.json"
      outputClaimToHeaders:
        - header: "x-org-id"
          claim: "http://testapp.com/orgId123"
```

# AuthorizationPolicy configuration
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: require-jwt
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: my-app
  action: ALLOW
  rules:
    - from:
        - source:
            requestPrincipals: ["*"]
      to:
        - operation:
            methods: ["GET", "POST"]
```
# Gateway configuration
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: my-gateway
  namespace: istio-system
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
        kinds:
          - kind: HTTPRoute
```
# HTTPRoute configuration
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: my-app-route
  namespace: test
spec:
  parentRefs:
    - name: my-gateway
      namespace: istio-system
      sectionName: http 
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: read-header-service
          namespace: test
          port: 8080
```
# Deployment and Service
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          resources:
            limits:
              memory: 256Mi
              cpu: "0.2"
          image: read-header-app:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: read-header-service
  namespace: test
  labels:
    app: my-app
    istio.io/ingress-use-waypoint: "true"
spec:
  selector:
    app: my-app
  ports:
    - port: 8080
      targetPort: 8080
```
What I've observed:

When sending an invalid JWT token, the request isn't rejected, and no error is thrown.
This works as expected with Istio's sidecar mode, where invalid tokens are properly validated.
Can anyone help me figure out what might be missing in the Ambient Mode setup? Any pointers or suggestions would be greatly appreciated.

Thanks in advance!
