### DISCUSSION TITLE
local rate limiting in ambient mode with separate limits for different service URL prefixes

### DISCUSSION THREAD

**Discussion by porobd-avaya** [istio/istio#55011] [Q&A]
Local rate limiting in ambient mode seems to work by pointing the workload selector in the EnvoyFilter to the corresponding waypoint gateway PODs:
```
workloadSelector:
    labels:
      gateway.networking.k8s.io/gateway-name: test1-waypoint
```
And it is also possible to have different rate limits per service in the waypoint enabled namespace by using a routeConfiguration match like below in the EnvoyFilter:
```
        routeConfiguration:
          vhost:
           name: "inbound|http|8080"
           route:
             name: "default"
             action: ANY
          name: "inbound-vip|8080|http|web-server1.test1.svc.cluster.local"
```
Next, I was trying to see whether it is possible to have different rate limits for different routes in one of the services. I was hoping to create multiple named routes for a service and associate them with the waypoint gateway using a virtualservice like below:
```
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
 name: web-server1-mesh-virtualservice
 namespace: test1
spec:
  hosts:
  - "web-server1.test1.svc.cluster.local"
  gateways:
  - test/test1-waypoint
  http:
  - match:
    - uri:
        prefix: /web-server1/ui/
    name: web-server1-ui
    route:
    - destination:
        host: web-server1.test1.svc.cluster.local
        port:
          number: 8080
  - match:
    - uri:
        prefix: /web-server1/api/
    name: web-server1-api
    route:
    - destination:
        host: web-server1.test1.svc.cluster.local
        port:
          number: 8080
```
But, when I take a dump of the routes in the waypoint gateway (using 'istioctl proxy-config routes'), I see that these routes do get associated but the 'default' route which uses '/' still exists and all the traffic gets routed using that default route and these new routes do not get used at all.

Is it possible to get rid of that default route in the waypoint proxy ?
Is there a way to achieve such kind of local rate limiting in the ambient mode ?
Or would I have to configure global rate limiting on the waypoint gateway to achieve such URL level rate limiting per service ?

Thank you.
