### DISCUSSION TITLE
How can I change the listen ip of envoy and pilot-agent, for example, 0.0.0.0:15001 to $(POD_IP):15001?

### DISCUSSION THREAD

**Discussion by JetFixer** [istio/istio#55108] [Q&A]
Similar modifications in istiod can be made by modifying the deployment of istiod, using like --secureGRPCAddr=$(POD_IP):15012
```
      containers:
      - args:
        - discovery
        - --monitoringAddr=$(POD_IP):15014
        - --grpcAddr=$(POD_IP):15010
        - --secureGRPCAddr=$(POD_IP):15012
        - --httpsAddr=$(POD_IP):15017
        - --httpAddr=$(POD_IP):8080
        - --log_output_level=default:info
        - --domain
        - cluster.local
        - --keepaliveMaxServerConnectionAge
        - 30m
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
```
But I can't find similar way in the documentation for envoy and pilot-agent.
I would appreciate it if you could answer this.
