### DISCUSSION TITLE
Multiple Gateways in separate namespaces watching the same host

### DISCUSSION THREAD

**Discussion by b1zley** [istio/istio#55122] [Q&A]
Can multiple gateways watch the same host?

In this case, requests made with only one of the prefix matches specified in the two virtual services is routed correctly (specifically, the virtual service/gateway pair that was created later).

Is this expected behavior or a configuration mistake on my part (or both)?
Thanks!

```
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: gateway1
  namespace: namespace1
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - example.com
    port:
      name: http
      number: 80
      protocol: HTTP
```
```
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: gateway2
  namespace: namespace2
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - example.com
    port:
      name: http
      number: 80
      protocol: HTTP
```

```
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: virtualservice1
  namespace: namespace1
spec:
  gateways:
  - gateway1
  hosts:
  - example.com
  http:
  - match:
    - uri:
        prefix: /service1
    route:
    - destination:
        host: service1.namespace1.svc.cluster.local
        port:
          number: 4000

```
```
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: virtualservice2
  namespace: namespace2
spec:
  gateways:
  - gateway2
  hosts:
  - example.com
  http:
  - match:
    - uri:
        prefix: /service2
    route:
    - destination:
        host: service2.namespace2.svc.cluster.local
        port:
          number: 4000

```
