### DISCUSSION TITLE
Gateway k8s API with Istio controller and Listeners with different certificates

### DISCUSSION THREAD

**Discussion by Harish-R-TCS** [istio/istio#55147] [Q&A]
Hello All

I'm using Istio version 1.20.3 and Kubernetes version AKS 1.30.  I am trying to use Kubernetes Gateway API with Istio (automated deployment not manual one ).  I followed the instructions at [https://istio.io/v1.20/docs/tasks/traffic-management/ingress/gateway-api/] to configure the Gateway.  I'm also attempting to use a TLS certificate.  The issue is that the certificate is not being mounted correctly.  I've tried using the documentation at [https://gateway-api.sigs.k8s.io/guides/tls/?h=tls#listeners-with-different-certificates] as a starting point. When I deploy the Gateway, it's looking for the certificate at a default location, but that location(error	cache	resource:file-cert:/etc/istio/ingressgateway-certs/tls.crt~/etc/istio/ingressgateway-certs/tls.key failed to generate secret for proxy from file: context deadline exceeded with last error: open /etc/istio/ingressgateway-certs/tls.crt: no such file or directory) doesn't exist error, causing an error.  I'm not sure if the problem is with IstioOperator or the Istio Gateway controller, but I suspect it is the Istio Gateway Controller.   Could you please advise me on whether I'm making an error, or if the current version supports this configuration ?

YAML FILE:

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  name: k8sgatewayapi
  namespace: k8s-gateway-api
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      hostname: "dev.gatewayapi.com"
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      hostname: "dev.gatewayapi.com"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: gatewayapisecret
            namespace: k8s-gateway-api
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: frontend-gatewayapi
  namespace: k8s-gateway-api
spec:
  parentRefs:
    - name: k8sgatewayapi
      namespace: k8s-gateway-api
  hostnames: ["dev.gatewayapi.com"]
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: gatewayapi-gateway-app2
          port: 80
```
