### DISCUSSION TITLE
Is there a way to get request metrics for a specific subset?

### DISCUSSION THREAD

**Discussion by jackmtpt** [istio/istio#55158] [Q&A]
Imagine I have the following VirtualService spec:

```
http:
    - name: primary
      route:
        - destination:
            host: my-app
            port:
              number: 80
            subset: stable
          weight: 100
        - destination:
            host: my-app
            port:
              number: 80
            subset: canary
          weight: 0
```

and this DestinationRule:

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: my-app
spec:
  host: my-app
  subsets:
  - name: canary
    labels:
      {{ include "app.labels" . | nindent 6 }}
  - name: stable
    labels:
      {{ include "app.labels" . | nindent 6 }}
```

I'm using Argo Rollouts to do canary deployments here, so the `canary` subset will get patched automatically to select the pods from the canary replicaset. So far, so good.

What I'd like to do is to be able to query the HTTP request metrics _just for the canary subset_ as part of the rollout. Looking at the `istio_requests_total` metric in prometheus though, it doesn't seem to have any labels that allow me to differentiate the two subsets explicitly. The `destination_canonical_revision` label _might_ be different if the change being deployed is actually a new image tag, but it might just be a configuration update with the same tag as before, so that won't work.

It's worth mentioning that we're not running in Ambient mode and we aren't using Sidecar containers either - we're only using Istio as an ingress controller with gateway pods.

Is there anything out of the box that can do this, or do I need to look at the Telemetry API stuff (which I'd like to avoid if possible to keep complexity down, as this is our first attempt at canary deployments).
