### DISCUSSION TITLE
Issue with Implementing Local Rate Limiter with Header Wildcard Value

### DISCUSSION THREAD

**Discussion by adityahilman** [istio/istio#55188] [Q&A]
I am facing an issue while implementing a local rate limiter in my pod. Specifically, I am unable to use the wildcard (*) value in request headers to set rate limits. The intended behavior is to allow requests based on header values that can vary, but the rate limiter is not functioning as expected when using wildcards.

Any suggestions on how to approach this issue would be appreciated, or if there’s a known bug/limitation.

Here my full configuration:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: dummy-repo-staging-rate-limiter
  namespace:staging
spec:
  workloadSelector:
    labels:
      app: dummy-repo-staging
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.local_ratelimit
        typed_config:
          "@type": type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
          value:
            stat_prefix: http_local_rate_limiter
  - applyTo: HTTP_ROUTE
    match:
      context: SIDECAR_INBOUND
      routeConfiguration:
        vhost:
          name: "inbound|http|80"
          route:
            action: ANY
    patch:
      operation: MERGE
      value:
        route:
          rate_limits:
            - actions:
              - header_value_match:
                  descriptor_key: x-header
                  descriptor_value: ".*"
                  headers:
                    - name: "x-secret"
                      safe_regex_match:
                        google_re2: {}
                        regex: ".*"
        typed_per_filter_config:
          envoy.filters.http.local_ratelimit:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter
              enable_x_ratelimit_headers: "DRAFT_VERSION_03"
              token_bucket:
                max_tokens: 1000
                tokens_per_fill: 1000
                fill_interval: 60s
              filter_enabled:
                runtime_key: local_rate_limit_enabled
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              filter_enforced:
                runtime_key: local_rate_limit_enforced
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              response_headers_to_add:
                - append: false
                  header:
                    key: x-local-rate-limit
                    value: "true"
              descriptors:
                - entries:
                  - key: x-header
                    value: ".*"
                  token_bucket:
                    max_tokens: 3
                    tokens_per_fill: 3
                    fill_interval: 60s 
```

**Comment by zirain** [comment]
any logs from proxy?

**Reply by adityahilman** [reply]
> any logs from proxy?

No logs from istio-proxy

In my current configuration, all requests with the X-Secret header are rejected, even when the value is unique per request. My expectation is to reject only requests with the same value for 1 minute to prevent spammers from targeting my pod.

**Reply by zirain** [reply]
you can enabled debug log by running `istioctl pc log <pod_name> --level filter:debug`

**Reply by adityahilman** [reply]
> you can enabled debug log by running `istioctl pc log <pod_name> --level filter:debug`

here the proxy logs
```
2025-02-20T06:54:32.519578Z	debug	envoy filter external/envoy/source/extensions/filters/http/local_ratelimit/local_ratelimit.cc:126	populate descriptors: key=x-header value=.*	thread=23
2025-02-20T06:54:32.639401Z	debug	envoy filter external/envoy/source/extensions/filters/http/local_ratelimit/local_ratelimit.cc:126	populate descriptors: key=x-header value=.*	thread=23
2025-02-20T06:54:32.755050Z	debug	envoy filter external/envoy/source/extensions/filters/http/local_ratelimit/local_ratelimit.cc:126	populate descriptors: key=x-header value=.*	thread=23
2025-02-20T06:54:32.865033Z	debug	envoy filter external/envoy/source/extensions/filters/http/local_ratelimit/local_ratelimit.cc:126	populate descriptors: key=x-header value=.*	thread=23
```

**Reply by zirain** [reply]
that means descriptors generated correctly.

**Reply by adityahilman** [reply]
> that means descriptors generated correctly.

However, my expectation is different. I expect the following behavior:

```
curl -H "x-secret: test123" http://myservice/auth  -> allowed (1st request)  
curl -H "x-secret: test123" http://myservice/auth  -> rejected (2nd request)  
 
curl -H "x-secret: test1234" http://myservice/auth -> allowed (1st request)  
curl -H "x-secret: test1235" http://myservice/auth -> allowed (1st request)  
```
In other words, I want to reject requests only if the same X-Secret value is used within 1 minute, but allow requests with different values.

how to achieve that?

**Reply by zirain** [reply]
I failed to reproduce with following configuration on m1 mac with envoy 1.33
```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901

static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 8000
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                http_filters:
                  - name: envoy.filters.http.local_ratelimit
                    typed_config:
                      "@type": type.googleapis.com/udpa.type.v1.TypedStruct
                      type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
                      value:
                        stat_prefix: http_local_rate_limiter
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          name: "rl-test"
                          route:
                            cluster: service_protected_by_rate_limit
                            rate_limits:
                              - actions:
                                  - header_value_match:
                                      descriptor_key: x-header
                                      descriptor_value: ".*"
                                      headers:
                                        - name: "x-secret"
                                          safe_regex_match:
                                            google_re2: {}
                                            regex: ".*"
                          typed_per_filter_config:
                            envoy.filters.http.local_ratelimit:
                              "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
                              stat_prefix: test
                              enable_x_ratelimit_headers: "DRAFT_VERSION_03"
                              token_bucket:
                                max_tokens: 1000
                                tokens_per_fill: 1000
                                fill_interval: 60s
                              filter_enabled:
                                runtime_key: local_rate_limit_enabled
                                default_value:
                                  numerator: 100
                                  denominator: HUNDRED
                              filter_enforced:
                                runtime_key: local_rate_limit_enforced
                                default_value:
                                  numerator: 100
                                  denominator: HUNDRED
                              response_headers_to_add:
                                - append: false
                                  header:
                                    key: x-local-rate-limit
                                    value: "true"
                              descriptors:
                                - entries:
                                    - key: x-header
                                      value: ".*"
                                  token_bucket:
                                    max_tokens: 3
                                    tokens_per_fill: 3
                                    fill_interval: 60s
                        - match: { prefix: "/foo2" }
                          route: { cluster: default_service }

    - name: staticreply-8080
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 8080
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: auto
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          direct_response:
                            status: 200
                            body:
                              inline_string: "example body\n"
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

    - name: staticreply-8081
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 8081
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: auto
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          direct_response:
                            status: 200
                            body:
                              inline_string: "example body\n"
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
    - name: default_service
      load_assignment:
        cluster_name: default_service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 8080
    - name: service_protected_by_rate_limit
      load_assignment:
        cluster_name: service_protected_by_rate_limit
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 8081

```

```yaml
~/Codes/servicemesh/istio on master                                                                                                               Ruby 9.2.6.0 at 16:35:33
╰─❯ envoy -c envoy/ratelimit/local/regex.yaml --component-log-level filter:debug,router:debug

╭─ ~/Codes/servicemesh/istio on master                                                                                                         ✘ INT Ruby 9.2.6.0 at 16:35:37
╰─❯ curl -o /dev/null -s -w "%{http_code}\n" localhost:8000 -H "x-secret: test1234"
200

╭─ ~/Codes/servicemesh/istio on master                                                                                                               Ruby 9.2.6.0 at 16:35:39
╰─❯ curl -o /dev/null -s -w "%{http_code}\n" localhost:8000 -H "x-secret: test1234"
200

╭─ ~/Codes/servicemesh/istio on master                                                                                                               Ruby 9.2.6.0 at 16:35:40
╰─❯ curl -o /dev/null -s -w "%{http_code}\n" localhost:8000 -H "x-secret: test1234"
200

╭─ ~/Codes/servicemesh/istio on master                                                                                                               Ruby 9.2.6.0 at 16:35:40
╰─❯ curl -o /dev/null -s -w "%{http_code}\n" localhost:8000 -H "x-secret: test1234"
429

╭─ ~/Codes/servicemesh/istio on master                                                                                                               Ruby 9.2.6.0 at 16:35:42
╰─❯ curl -o /dev/null -s -w "%{http_code}\n" localhost:8000 -H "x-secret: test1234"
429

╭─ ~/Codes/servicemesh/istio on master                                                                                                               Ruby 9.2.6.0 at 16:35:45
╰─❯ curl -o /dev/null -s -w "%{http_code}\n" localhost:8000 -H "x-secret: test123"
429

╭─ ~/Codes/servicemesh/istio on master                                                                                                               Ruby 9.2.6.0 at 16:35:51
╰─❯ curl -o /dev/null -s -w "%{http_code}\n" localhost:8000 -H "x-secret: test123"
429
```
