### DISCUSSION TITLE
Are JWT audiences getting validated in Istio?

### DISCUSSION THREAD

**Discussion by rvillane** [istio/istio#55193] [Q&A] [answered]
Hi,  I have been using Istio for several years and I was under the assumption that when a app that is member of the mesh receives a JWT token, the audience is validated, just like expiration and issuer are validated, however, during a test today, I was able to successfully make calls to multiple JWT-enforced apps, all members of the mesh using the exact same JWT token and each has a different DNS (audience) name.   Is that an expected behavior?

Something all apps accepting the token regardless of the audience is the fact they all have `token-signer@my-project.iam.gserviceaccount.com` configured as an issuer and the token was issued by that user.

Here are the configuration details of the 

App A
DNS name: app-a@my-domain.com
```
apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: "jwt-authentication"
  namespace: my-namespace
spec:
  selector:
    matchLabels:
      app: my-app-a
  jwtRules:
    - issuer: "https://accounts.google.com"
      jwksUri: "https://www.googleapis.com/oauth2/v3/certs"
    - issuer: "token-signer@my-project.iam.gserviceaccount.com"
      jwksUri: "https://www.googleapis.com/service_accounts/v1/jwk/token-signer@my-project.iam.gserviceaccount.com"
---
apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
  name: "token-signer-authpolicy"
  namespace: my-namespace
spec:
  selector:
    matchLabels:
      app: my-app-a
  action: ALLOW
  rules:
    - when:
        - key: request.auth.claims[iss]
          values:
            - "token-signer@my-project.iam.gserviceaccount.com"
---
apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
  name: "google-authpolicy"
  namespace: my-namespace
spec:
  selector:
    matchLabels:
      app: my-app-a
  action: ALLOW
  rules:
    - when:
        - key: request.auth.claims[email]
          values:
            - "my-identity-b@my-project.iam.gserviceaccount.com"
            - "my-identity-c@my-project.iam.gserviceaccount.com"
---
apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
  name: "force-jwt-token"
  namespace: my-namespace
spec:
  selector:
    matchLabels:
      app: my-app-a
  action: DENY
  rules:
    - from:
        - source:
            notRequestPrincipals: ["*"]
```

App B
DNS name: app-b@my-domain.com
```
apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: "jwt-authentication"
  namespace: my-namespace
spec:
  selector:
    matchLabels:
      app: my-app-b
  jwtRules:
    - issuer: "https://accounts.google.com"
      jwksUri: "https://www.googleapis.com/oauth2/v3/certs"
    - issuer: "token-signer@my-project.iam.gserviceaccount.com"
      jwksUri: "https://www.googleapis.com/service_accounts/v1/jwk/token-signer@my-project.iam.gserviceaccount.com"
---
apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
  name: "token-signer-authpolicy"
  namespace: my-namespace
spec:
  selector:
    matchLabels:
      app: my-app-b
  action: ALLOW
  rules:
    - when:
        - key: request.auth.claims[iss]
          values:
            - "token-signer@my-project.iam.gserviceaccount.com"
---
apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
  name: "google-authpolicy"
  namespace: my-namespace
spec:
  selector:
    matchLabels:
      app: my-app-b
  action: ALLOW
  rules:
    - when:
        - key: request.auth.claims[email]
          values:
            - "my-identity-a@my-project.iam.gserviceaccount.com"
            - "my-identity-c@my-project.iam.gserviceaccount.com"
---
apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
  name: "force-jwt-token"
  namespace: my-namespace
spec:
  selector:
    matchLabels:
      app: my-app-b
  action: DENY
  rules:
    - from:
        - source:
            notRequestPrincipals: ["*"]
```

Here is the payload of the JWT token that was created with the intention to send a request to app B, however, I was able to send it also to app B and the request was accepted successfully.

```
{
  "iss": "token-signer@my-project.iam.gserviceaccount.com",
  "sub": "token-signer@my-project.iam.gserviceaccount.com",
  "iat": 1740060206,
  "exp": 1740063806,
  "aud": "app-b@my-domain.com"
}
```
