### DISCUSSION TITLE
Istio[1.5.9] Locality Load Balancing not working as expected with Mesh external ServiceEntry

### DISCUSSION THREAD

**Discussion by akarunad07** [istio/istio#55275] [Q&A]
Hello, Greetings!!
We are trying to implement Locality load balancing to route requests between application and external service endpoints in the same zone using K8's External Service, istio ServiceEntry and DestinationRule. After creating both ServiceEntry and DestinationRule in the same namespace where application is attached, we are able to see external endpoints are added in the istio proxy config with correct locality and priority for the POD. Even though locality and priority are set properly, requests from the application is distributed across external endpoints in different zones. But the expectation is request should be routed to the endpoint in the same zone considering the priority based on locality.

**Istio version**
client version: 1.5.9
control plane version: 1.5.9
data plane version: 1.5.9 (20 proxies)

**K8's External Service:**
```  
NAME                   TYPE           CLUSTER-IP      EXTERNAL-IP  PORT(S)    AGE
rds                       ExternalName   <none>          rds1.com      <none>     2d12h
rds-reader           ExternalName   <none>          rds1-ro.com      <none>     2d12h
```  
**Istio Mesh config:**
```   
      accessLogFile: "/dev/stdout"
      ....
      outboundTrafficPolicy:
        mode: ALLOW_ANY
      localityLbSetting:
          enabled: true
      ....
```
**Istio ServiceEntry**
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
 name: external-svc-rds
 namespace: app
spec:
 hosts:
 - "*.app.svc.cluster.local"
 location: MESH_EXTERNAL
 ports:
 - number: 3306
   name: tcp
   protocol: tcp
 resolution: DNS
 endpoints:
 - address: rds1.com
   locality: ap-south-1/ap-south-1c
   ports:
     tcp: 3306
 - address: rds1-ro.com
   locality: ap-south-1/ap-south-1b
   ports:
     tcp: 3306
``` 
**Istio DestinationRule**
``` 
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
 name: external-svc-rds-dr
 namespace: app
spec:
 host: "*.app.svc.cluster.local"
 trafficPolicy:
    loadBalancer:
      localityLbSetting:
        enabled: true
    outlierDetection:
      consecutiveErrors: 7
      interval: 30s
      baseEjectionTime: 30s
``` 

**Istio Proxy config endpoint details**
``` 
[
    {
        "name": "outbound|3306||*.app.svc.cluster.local",
        "addedViaApi": true,
        "hostStatuses": [
            {
                "address": {
                    "socketAddress": {
                        "address": "10.17.1.66",
                        "portValue": 3306
                    }
                },
                "stats": [
                    {
                        "name": "cx_connect_fail"
                    },
                    {
                        "name": "cx_total"
                    },
                    {
                        "name": "rq_error"
                    },
                    {
                        "name": "rq_success"
                    },
                    {
                        "name": "rq_timeout"
                    },
                    {
                        "name": "rq_total"
                    },
                    {
                        "type": "GAUGE",
                        "name": "cx_active"
                    },
                    {
                        "type": "GAUGE",
                        "name": "rq_active"
                    }
                ],
                "healthStatus": {
                    "edsHealthStatus": "HEALTHY"
                },
                "weight": 1,
                "hostname": "rds1-ro.com"
            },
            {
                "address": {
                    "socketAddress": {
                        "address": "10.17.1.86",
                        "portValue": 3306
                    }
                },
                "stats": [
                    {
                        "name": "cx_connect_fail"
                    },
                    {
                        "name": "cx_total"
                    },
                    {
                        "name": "rq_error"
                    },
                    {
                        "name": "rq_success"
                    },
                    {
                        "name": "rq_timeout"
                    },
                    {
                        "name": "rq_total"
                    },
                    {
                        "type": "GAUGE",
                        "name": "cx_active"
                    },
                    {
                        "type": "GAUGE",
                        "name": "rq_active"
                    }
                ],
                "healthStatus": {
                    "edsHealthStatus": "HEALTHY"
                },
                "weight": 1,
                "hostname": "rds1.com",
                "priority": 1
            }
        ]
    }
]
``` 

**Test Outcome:**

- curl request to `rds.app.svc.cluster.local:3306` are directed to `rds1.com`
- curl request to `rds-reader.app.svc.cluster.local:3306` are directed to `rds1-ro.com`

**Expectation**

- Both the requests should be routed to `rds1-ro.com` based on priority set by locality load balancing.

**Questions** 

1. Envoy access logs are showing only inbound traffic and not showing outbound traffic. Is there any specific config to enable outbound traffic access logs? Envoy version: 1.13.4
2. Does Locality Load Balancing with ServiceEntry & DestinationRule is supported in Istio 1.5.9 ?
3. If Supported, any other config needs to be added to get Locality Load Balancing work as expected?

Any help is appreciated!!!
