### DISCUSSION TITLE
Multiple gateways with wildcards subdomains

### DISCUSSION THREAD

**Discussion by lawrence-c** [istio/istio#55374] [Q&A]
Hi,

Recently went from one gateway for everything, to split Gateways for better traffic routing and resource management, however at a subdomain lower.

Eg:

```
*.platform.eu-west-1.qa.test.com
```
to
```
*.app.platform.eu-west-1.qa.test.com
*.inference.platform.eu-west-1.qa.test.com
```

This worked:
```
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-gateway
  namespace: istio-ingress
spec:
  selector:
    istio: istio-ingress  # must match istio-ingress pod label
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*.platform.eu-west-1.qa.test.com"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: tls-cert
    hosts:
    - "*.platform.eu-west-1.qa.test.com"
```

With a VirtualService:
```
Spec:                                                                                                                                                                                                                                                                                            
  Gateways:                                                                                                                                                                                                                                                                                      
     - istio-ingress/istio-gateway                                                                                                                                                                                                                                                        
  Hosts:                                                                                                                                                                                                                                                                                         
     - test-1.platform.eu-west-1.qa.test.com
```

and within the istio-ingress pod, could see the Telemetry logs of the requests coming in.

---

Now moving to the split Gateway, I removed the Gateway above, create two new Certificates for each Gateway and installed the new Gateways, but I'm not seeing any logs appear in the app-ingress or inference-ingress, and I'm not sure what I'm missing. See below:

```
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-inference-gateway
  namespace: istio-ingress
spec:
  selector:
    istio: inference-ingress  # must match istio-ingress pod label
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*.inference.platform.eu-west-1.qa.test.com"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: inference-tls-cert
    hosts:
    - "*.inference.platform.eu-west-1.qa.test.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-app-gateway
  namespace: istio-ingress
spec:
  selector:
    istio: app-ingress  # must match istio-ingress pod label
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*.app.platform.eu-west-1.qa.test.com"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: app-tls-cert
    hosts:
    - "*.app.platform.eu-west-1.qa.test.com"
```

With a VirtualService:
```
Spec:                                                                                                                                                                                                                                                                                            
  Gateways:                                                                                                                                                                                                                                                                                      
     - istio-ingress/istio-inference-gateway                                                                                                                                                                                                                                                        
  Hosts:                                                                                                                                                                                                                                                                                         
     - test-1.inference.platform.eu-west-1.qa.test.com
```

If I add the previous Gateway back in, and update the VirtualService to use the previous setting it works again.

Any ideas what I could be missing?

TIA!

**Comment by ilrudie** [comment]
Have you taken a look at how traffic is meant to reach your gateways? It seems like you should have 3 load balancer services right now. One for the old shared gateway you are trying to move away from and the two newer ones. It's probably worth verifying that clients resolve a name like `test-1.inference.platform.eu-west-1.qa.test.com` to the correct address for your new inference gateway.

**Reply by lawrence-c** [reply]
Yeah, we have 3 load balancers now, with the DNS setup accordingly in Route53 with CNAME's pointing to the load balancers:

```
istio-ingress: 
 - LB: k8s-istioing-istioing-<>elb.eu-west-1.amazonaws.com
 - CNAME: *.platform.eu-west-1.qa.test.com

istio-app-ingress: 
- LB: k8s-istioing-istioapp-<>.elb.eu-west-1.amazonaws.com
- CNAME: *.app.platform.eu-west-1.qa.test.com

istio-inference-ingress: 
- LB: k8s-istioing-istioinf-<>.elb.eu-west-1.amazonaws.com
- CNAME:  *.inference.platform.eu-west-1.qa.test.com

```

I did originally have the shared Cert and hit the issue mentioned [here](https://istio.io/latest/docs/ops/common-problems/network-issues/#404-errors-occur-when-multiple-gateways-configured-with-same-tls-certificate), but since adding certs for each gateway, no luck still

Doing an `nslookup -debug inference.platform.eu-west-1.qa.test.com` points to the original `istio-ingress` rather than the `istio-inference-gateway`.

Doing the `nslookup -debug test-1.inference.platform.eu-west-1.qa.test.com` however, points to something I can't find within Route53 🤔
