### DISCUSSION TITLE
Trying to get client cert whitelisting on ingressgateway for Virtualservice re-route

### DISCUSSION THREAD

**Discussion by esn89** [istio/istio#55435] [Q&A]
I terminate TLS on gateway:

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: api-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - myhost.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: istio-ingressgateway-tls
      mode: MUTUAL
 ```
 
 Then I have a VirtualService that re-routes it to my GCP cloud run function:
 
 ```
 apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  generation: 1
  name: my-virtual-service
  namespace: istio-system
spec:
  gateways:
  - api-gateway
  hosts:
  - myhost.com
  http:
  - match:
    - uri:
        exact: /goToCloudRun
    rewrite:
      authority: cloudrun.us-central1.run.app
      uri: /
    route:
    - destination:
        host: cloudrun.us-central1.run.app
        port:
          number: 443
```

I also have an EnvoyFilter that takes a look at the client cert used at the request and adds an extra header:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: client-cert-info
  namespace: istio-system
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.lua
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
          default_source_code:
            inline_string: |
              function envoy_on_request(request_handle)
                  local xfcc_header = request_handle:headers():get('x-forwarded-client-cert')
                  if xfcc_header ~= nil then
                      local client_cert_subject = string.gsub(string.gsub(xfcc_header, '";URI=.*', ''), '.*;Subject="', '')
                      if client_cert_subject ~= nil then
                          _, _, ou = string.find(client_cert_subject, 'OU=([^,]+)')
                          _, _, cn = string.find(client_cert_subject, 'CN=([^,]+)')
                          request_handle:headers():replace('x-forwarded-client-cert-subject', client_cert_subject)
                          request_handle:logInfo('request with client cert subject: ' .. client_cert_subject)
                          _, _, ou = string.find(client_cert_subject, 'OU=([^,]+)')
                          _, _, cn = string.find(client_cert_subject, 'CN=([^,]+)')
                          _, _, o = string.find(client_cert_subject, 'O=([^,]+)')
                      end
                  else
                      request_handle:headers():remove('x-forwarded-client-cert-subject')
                  end
                  if cn ~= nil then
                      request_handle:headers():replace('x-forwarded-client-cert-cn', cn)
                  else
                      request_handle:headers():remove('x-forwarded-client-cert-cn')
                  end
                  if ou ~= nil then
                      request_handle:headers():replace('x-forwarded-client-cert-ou', ou)
                  else
                      request_handle:headers():remove('x-forwarded-client-cert-ou')
                  end
   
              end
  workloadSelector:
    labels:
      istio: ingressgateway
```

In my logs on the ingressgateway I am able to see this header by logging: ` x-forwarded-client-cert-cn: '%REQ(x-forwarded-client-cert-cn)%'`

One thing I cannot get working is that on the AuthorizationPolicy level, I wish to only let CNAME of 'foobar' be able to call this route.  But no matter what I try it always gives `RBAC: access denied` 

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-rewrite
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  action: ALLOW
  rules:
    - to:
        - operation:
            hosts:
              - myhost.com
            paths: ["/goToCloudRun"]
      when:
        - key: 'request.headers[x-forwarded-client-cert-cn]'
          values:
            - 'foobar'
```

Here are the logs:

```[2025-03-09T23:26:45.555Z] "GET /goToCloudRun HTTP/2" 403 - rbac_access_denied_matched_policy[none] - "-" 0 19 0 - "172.16.48.27" "curl/8.12.0" "0b007a78-9912-4139-9b66-a3b1f134671b" "myhost.com" "-" outbound|443||cloudrun.us-central1.run.app - 172.20.4.207:443 172.16.48.27:54914 myhost.com -
{"request":{"authority":"myhost.com","method":"GET","reponseCode":"403","path":"/goToCloudRun","protocol":"HTTP/2","x-forwarded-client-cert-cn":"-","client_cert_subj":"OU=nonprod-client,O=MyCompany,L=Santa Clara,ST=CA,C=US,CN=foobar"}}
```

You can see that "x-forwarded-client-cert-cn" is empty value. 

However, if I remove the AuthorizationPolicy it works and I get a 200 response and the `x-forwarded-client-cert-cn` has the value of the client cert.
