### DISCUSSION TITLE
AuthorizationPolicy with AUDIT Action: Audit Logs Not Showing in Istio-Proxy or Datadog

### DISCUSSION THREAD

**Discussion by abhiverma001** [istio/istio#55446] [Q&A]
I’ve set up Istio in my Kubernetes cluster using Helm and enabled the sidecar proxy. My goal is to utilize AuthorizationPolicy with the ```AUDIT``` action to generate audit-specific logs and forward them to Datadog, which is already integrated as a telemetry provider. However, I’m encountering an issue where only standard access logs are recorded, both in the istio-proxy sidecar container and in Datadog.

**Current Configuration:**
1. Istio Installation:
- Installed using Helm.
- Enabled ```meshConfig.accessLogFile: "/dev/stdout"```.
- Sidecar proxy injection is enabled.
2. AuthorizationPolicy:
- Created an ```AuthorizationPolicy``` with the following configuration:
```
yaml
Copy
Edit
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: audit-policy
  namespace: default
spec:
  action: AUDIT
  rules:
    - to:
        - operation:
            methods: ["GET", "POST"]
 ```           
            
3. Telemetry Provider:
- Datadog is integrated as the telemetry provider and successfully captures standard access logs.

4. Expectations:
- Logs related to the AUDIT action in the AuthorizationPolicy should appear in the istio-proxy logs or be forwarded to Datadog.
- The logs should indicate that requests matching the policy were marked for audit.

**Observations:**
- istio-proxy Logs: Only standard access logs are visible, containing general request information like method, response code, duration, source/destination.
- Datadog: Similar to the sidecar logs, only standard access logs are visible, and there are no logs related to the AUDIT action.

**Questions:**
1. Configuration Missing?
- Is there any additional configuration required to enable or capture logs specifically related to the AUDIT action in the AuthorizationPolicy?

2. Telemetry Provider Support?
- Does Datadog support forwarding or displaying logs generated by the AUDIT action? If so, is there any Istio-specific setting required to enable this?

3. Envoy Filter Required?
- Do I need to create a custom EnvoyFilter to explicitly capture and log the AUDIT action? If yes, what should the configuration look like?

4. Direction Check:
- Am I heading in the right direction by expecting the AUDIT action to produce distinct logs visible in the sidecar or Datadog, or is there a different recommended approach?

Any insights, recommendations, or examples of working configurations would be greatly appreciated. If there are known limitations or caveats with using the AUDIT action, I’d love to understand those as well.

**Comment by howardjohn** [comment]
My details are a bit fuzzy here but my understanding is the AUDIT support was pretty much partially implemented; I think it emits some dynamic metadata which was only implemented by one specific vendor's (Stackdriver) logging extension.

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/rbac/v3/rbac.proto#config-rbac-v3-rbac specifically the `access_log_hint`

**Comment by abhiverma001** [comment]
Documentation says a separate plugin must be configured and enabled to actually fulfill the audit decision and complete the audit behavior. The request will not be audited if there are no such supporting plugins enabled. 

https://istio.io/latest/docs/reference/config/security/authorization-policy/

Any one knows what is this separate plugin?

**Reply by howardjohn** [reply]
As mentioned in https://github.com/istio/istio/discussions/55446#discussioncomment-12451907 - it was a single vendor (Stackdriver) which is not even part of Istio anymore

**Reply by abhiverma001** [reply]
Thank you @howardjohn for clarifying the details about audit logging and the reference to StackDriver as the separate plugin in Istio documentation. Your insights saved me a lot of time and effort—thanks again!

**Comment by Ferdudas97** [comment]
Hey, It can be configured using Istio resources - Telemetry API and MeshConfig. With that there is no need for separated plugin.
```
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: global-telemetry
  namespace: istio-system
spec:
  accessLogging:
  - match:
      mode: SERVER
    providers:
    - name: envoy.access_log.rbac.audit
    filter:
      expression: "metadata.filter_metadata['envoy.common']['access_log_hint']"
```
https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-ExtensionProvider-EnvoyFileAccessLogProvider
```
...
    extensionProviders:
    - envoyFileAccessLog:
        logFormat: ... 
      name: envoy.access_log.rbac.audit
```
Maybe documentation should be changed?
