### DISCUSSION TITLE
Removing metrics labels in 1.9.9 via EnvoyFilter

### DISCUSSION THREAD

**Discussion by Kritnich** [istio/istio#55441] [Q&A] [answered]
Hello, we are using Istio 1.9.9 via the Openshift Service Mesh operator. Due to some quirks in our application architecture, I want to remove the labels "source_workload" and "destination_workload" from TCP metrics of all envoy proxies to reduce memory load. I have built the following EnvoyFilter for this according to the documentation and examples I could find:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: prune-workload-tcp-metrics
  namespace: istio
spec:
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.tcp_proxy
      patch:
        operation: INSERT_BEFORE
        value:
          name: istio.stats
          typed_config:
            '@type': type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.network.wasm.v3.Wasm
            value:
              config:
                configuration:
                  '@type': type.googleapis.com/google.protobuf.StringValue
                  value: |
                    {
                      "metrics": [
                        {
                          "name": "tcp_received_bytes_total",
                          "tags_to_remove": [
                            "source_workload",
                            "destination_workload"
                          ]
                        },
                        {
                          "name": "tcp_sent_bytes_total",
                          "tags_to_remove": [
                            "source_workload",
                            "destination_workload"
                          ]
                        },
                        {
                          "name": "tcp_connections_opened_total",
                          "tags_to_remove": [
                            "source_workload",
                            "destination_workload"
                          ]
                        },
                        {
                          "name": "tcp_connections_closed_total",
                          "tags_to_remove": [
                            "source_workload",
                            "destination_workload"
                          ]
                        }
                      ]
                    }
                root_id: stats_inbound
                vm_config:
                  code:
                    local:
                      inline_string: envoy.wasm.stats
                  runtime: envoy.wasm.runtime.null
                  vm_id: tcp_stats_inbound
    - applyTo: NETWORK_FILTER
      match:
        context: SIDECAR_OUTBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.tcp_proxy
      patch:
        operation: INSERT_BEFORE
        value:
          name: istio.stats
          typed_config:
            '@type': type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.network.wasm.v3.Wasm
            value:
              config:
                configuration:
                  '@type': type.googleapis.com/google.protobuf.StringValue
                  value: |
                    {
                      "metrics": [
                        {
                          "name": "tcp_received_bytes_total",
                          "tags_to_remove": [
                            "source_workload",
                            "destination_workload"
                          ]
                        },
                        {
                          "name": "tcp_sent_bytes_total",
                          "tags_to_remove": [
                            "source_workload",
                            "destination_workload"
                          ]
                        },
                        {
                          "name": "tcp_connections_opened_total",
                          "tags_to_remove": [
                            "source_workload",
                            "destination_workload"
                          ]
                        },
                        {
                          "name": "tcp_connections_closed_total",
                          "tags_to_remove": [
                            "source_workload",
                            "destination_workload"
                          ]
                        }
                      ]
                    }
                root_id: stats_outbound
                vm_config:
                  code:
                    local:
                      inline_string: envoy.wasm.stats
                  runtime: envoy.wasm.runtime.null
                  vm_id: tcp_stats_outbound
    - applyTo: NETWORK_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.tcp_proxy
      patch:
        operation: INSERT_BEFORE
        value:
          name: istio.stats
          typed_config:
            '@type': type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.network.wasm.v3.Wasm
            value:
              config:
                configuration:
                  '@type': type.googleapis.com/google.protobuf.StringValue
                  value: |
                    {
                      "metrics": [
                        {
                          "name": "tcp_received_bytes_total",
                          "tags_to_remove": [
                            "source_workload",
                            "destination_workload"
                          ]
                        },
                        {
                          "name": "tcp_sent_bytes_total",
                          "tags_to_remove": [
                            "source_workload",
                            "destination_workload"
                          ]
                        },
                        {
                          "name": "tcp_connections_opened_total",
                          "tags_to_remove": [
                            "source_workload",
                            "destination_workload"
                          ]
                        },
                        {
                          "name": "tcp_connections_closed_total",
                          "tags_to_remove": [
                            "source_workload",
                            "destination_workload"
                          ]
                        }
                      ]
                    }
                root_id: stats_outbound
                vm_config:
                  code:
                    local:
                      inline_string: envoy.wasm.stats
                  runtime: envoy.wasm.runtime.null
                  vm_id: tcp_stats_outbound

```

The EnvoyFilter is accepted by the control plane and I can see within Kiali that it is also applied to the proxy config after restarting them, but I still see the labels on those metrics. Is there a syntactic error or is it possible that other default EnvoyFilters interfere with this filter? I would appreciate any ideas, further documentation or pointers on how I can troubleshoot/debug this.
