### DISCUSSION TITLE
[Ambient] Add kubeapi as Service Entry to Mesh with Deny Egress Networkpolicy

### DISCUSSION THREAD

**Discussion by shel-tall** [istio/istio#55467] [Q&A]
Hello,

we started using Istio Ambient in our project that is hosted in aws. Therefor we have only a headless service in the default namespace that references the kube-api endpoints. 

We want to deny all egress with plain kubernetes network policies and only allow gateways to communicate to the internet via serviceentries. This works with a gateway that listens on 15008 and serviceentries doing 443 TLS or grpc and a networkpolcy that allows only gateway pods egress to 0.0.0.0.

But I'm just not getting the kubeapi service to work. Maybe I'm missing something but what would I need? Different listeneres? Serviceentry  and gateways in the default namespace or just a serviceentry in the namespace i want to connect from ? Or is there a flaw in the attempt? We want to prohibit every unnecessary traffic in our cluster and I do not know about other option to controll egress with istio ambient.

the kubernetes service has the ip 10.100.0.1
In my workload i get:
` Get \"https://10.100.0.1:443/apis/apiextensions.k8s.io/v1\": net/http: TLS handshake timeout"`
and in the corresponding ztunnel log i see:
```
dst.addr=172.100.5.66:443 dst.service="kubernetes.default.svc.cluster.local" dst.workload="kubernetes" dst.namespace="default" direction="outbound"
bytes_sent=0 bytes_recv=0 duration="10001ms" error="io error: deadline has elapsed"
```
the current serviceentry in the default namespace that is part of the ambient mesh(issue?):

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: kube-apiserver
  labels:
    istio.io/use-waypoint: waypoint
  namespace: default
spec:
  hosts:
  - kubernetes.default.svc.cluster.local
  location: MESH_INTERNAL
  addresses: ["100.10.0.1"]
  ports:
  - name: https
    number: 443
    protocol: TLS
  resolution: DNS
```

Thank you for your help!

**Comment by howardjohn** [comment]
It seems like you have a NetworkPolicy blocking it. What are your network policies?

If your application needs to call the api-server, networkpolicy will need to allow it. Note that this traffic is over port 443, NOT 15008, since the api-server is not in the mesh.

**Reply by howardjohn** [reply]
I don't thikn its related but there were fixes in 1.24 around the API server BTW, so if you are on pre-1.24 I would also upgrade.

**Reply by shel-tall** [reply]
Thank you for your reply. I'm already on 1.25. I think I managed to achieve what i planned to do. I removed the serviceentry. The default namespace was labeled anyway and i added a label to the kubernetes service: istio.io/use-waypoint: waypoint. 

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  labels:
    istio.io/waypoint-for: all
  name: waypoint
  namespace: default
spec:
  gatewayClassName: istio-waypoint
  listeners:
    - name: mesh
      port: 15008
      protocol: HBONE
      allowedRoutes:
        namespaces:
          from: All
```
In my application namespace i have the following network policies:
```
spec:
  podSelector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: waypoint
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
```
and:
```
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - ports:
        - port: 15008
          protocol: TCP
    - to: 
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
```

@howardjohn This shows logs in the ztunnel:
```
dst.hbone_addr=10.100.0.1:443
dst.service="kubernetes.default.svc.cluster.local" dst.workload="waypoint-cd656b9d6-d2n75" dst.namespace="default" dst.identity="spiffe://cluster.local/ns/default/sa/waypoint"
```
Is this working correct? i wanted to add the kubeapi as a service to the mesh to better control the access because the endpoints behind the service are not part of the cluster and are hard to block/allow dynamicly.
