### DISCUSSION TITLE
Header Information Not Properly Inherited in VirtualService Delegation

### DISCUSSION THREAD

**Discussion by mk2taiga** [istio/istio#55487] [Q&A]
# Question
When delegating from a parent VirtualService (user) to a child VirtualService (user-delegate), is it possible that header information is not passed correctly?
Even with the `user-test` header, requests do not go to `user-test.default.svc.cluster.local`.

## Parent VirtualService (user)
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: user
  namespace: default
spec:
  hosts:
    - user.default.svc.cluster.local
  http:
    - name: user-delegate
      match:
        - headers:
            x-test-request:
              regex: ".*-test$"
      delegate:
        name: user-delegate
        namespace: default
    - name: default
      route:
        - destination:
            host: user.default.svc.cluster.local

```

## Child VirtualService (user-delegate)
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: user-delegate
  namespace: default
spec:
  http:
    - name: test-request
      match:
        - headers:
            x-test-request:
              exact: user-test
      route:
        - destination:
            host: user-test.default.svc.cluster.local

```
