### DISCUSSION TITLE
How to I set podAntiAffinity rules to a Kubernetes Gateway pods?

### DISCUSSION THREAD

**Discussion by zchenyu** [istio/istio#55484] [Q&A] [answered]
I've installed Istio using https://istio.io/v1.16/docs/tasks/traffic-management/ingress/gateway-api/
and am using a Kubernetes Gateway CRD:

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: gateway
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    port: 80
    protocol: HTTP
```

However the `gateway-istio` pods that it spins up don't have the desired podAntiAffinity rules that I want. How can I add them?
