### DISCUSSION TITLE
[Ambient] kubeapi / mTLS Strict

### DISCUSSION THREAD

**Discussion by shel-tall** [istio/istio#55512] [Q&A] [answered]
Hey I run a Kubernetes Cluster in AWS.

how do i manage kubeapi access (kubernetes service in default namespace with 2 ips) ? We have multiple workloads that have the following issue: 
E.g. ExternalSecrets webhook wants ingress from the kubeapi on port 10250. But if i set the mTLS to Strict in the namespace of externalsecrets is get
```
error="connection closed due to policy rejection:
explicitly denied by:
istio-system/istio_converted_static_strict"
```
If i set mtls to permissive I'm able to call the pod at 10250 from outside the mesh(just a random namespace). I have this policy enabled:

```
  action: ALLOW
  rules:
    - from: 
        - source:
            notNamespaces: ["*"]
      to:
        - operation:
            ports:
              - "10250" # kubeapi access
```

Because we have different environments and want IaC, we dont want to hard code the ips of this service, because they are different with every deployment.

**Comment by howardjohn** [comment]
Generally you will need to not require mTLS from the api-server in these cases. You can PeerAuthentication allows per-port overrides (so you can have STRICT everywhere except port 10250 for example) or AuthorizationPolicy can do things more complex.

**Reply by shel-tall** [reply]
Do you mean something like that :
```
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: test
  namespace: externalsecrets
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: external-secrets
  mtls:
    mode: STRICT
  portLevelMtls:
    10250:
      mode: DISABLE
```
But the missing point is here: how can i now allow only kubeapi and not any pod to connect to 10250. Using kubernetes Networkpolicies I also cant select the headless kubernetes.default.svc.cluster.local server. 
I tried DestinationRule but i dont now if it is supported in ambient or if I used it correctly because the following did not work:

```
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: mtls-strict
  namespace: externalsecrets
spec:
  mtls:
    mode: STRICT
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: api-server
  namespace: externalsecrets
spec:
  host: kubernetes.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE

```
