### DISCUSSION TITLE
IstioOperator are lost after upgrade from 1.20.0 to 1.21.0

### DISCUSSION THREAD

**Discussion by gokhankocak** [istio/istio#55532] [Q&A]
Hello,

We did an in-place upgrade from 1.20.0 to 1.21.0.
istioctl x precheck
istioctl upgrade #for default profile
istioctl upgrade --filename project1.istiooperator.yaml

After the upgrades finished we get an empty list from the following command:
kubectl get istiooperator -n istio-system
-> empty output

What should we do now?
istio is working properly but there are no istiooperator objects in the istio-system namespace.

We have several istiooperator definitions like the following (project1.istiooperator.yaml):
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: project1-istio-ingressgateway
spec:
  profile: empty # Do not install CRDs or the control plane
  components:
    ingressGateways:
    - name: project1-istio-ingressgateway
      namespace: project1
      enabled: true
      label:
        # Set a unique label for the gateway. This is required to ensure Gateways
        # can select this workload
        istio: project1-istio-ingressgateway
  values:
    gateways:
      istio-ingressgateway:
        # Enable gateway injection
        injectionTemplate: gateway
        type: NodePort
```

Before the upgrade we had the following output
```
kubectl get istiooperator -n istio-system
NAME                                                         REVISION   STATUS   AGE
installed-state                                                                  421d
installed-state-project1-istio-ingressgateway                         414d
...
```
