### DISCUSSION TITLE
Issues with VirtualService not matching requests

### DISCUSSION THREAD

**Discussion by vikramchhibber** [istio/istio#55582] [General]
Hi All,

I have load-balancer service with external IPv6. External gRPC clients are sending requests to this IP. I have a deployment attached with this service and have injected Envoy sidecar.
I have created a virtual service for this load balancer where I have some traffic routing rules.
In these rules, I want to redirect gRPC traffic to internal services based on the received port. The issue I have is that the traffic is not matching any of these rules. The clients don’t send “Host” header in the gRPC request. Please let me know what options I have.

```
kind: VirtualService
apiVersion: networking.istio.io/v1
metadata:
  name: ingress_virtual_service
  namespace: default
spec:
  hosts:
  - ingress-service.default.svc
  - fd00:30:1:13::108
  http:
  - match:
    - port: 17000
    route:
    - destination:
        host: ingress-service.default.svc
        port:
          number: 17000
  - match:
    - port: 18000
    route:
    - destination:
        host: foo-bar.default.svc # Requests recieved on 18000 needs to be redirected to foo-bar
        port:
          number: 18000


kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-ipv6: fd00:30:1:13::108
  name: ingress-service
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv6
  ipFamilyPolicy: SingleStack
  ports:
  - name: http2-ingress-service
    port: 17000
    targetPort: 17000
  - name: http2-foo-bar
    port: 18000
    targetPort: 18000
  type: LoadBalancer
```

Requests on 17000 are reaching my application container via Envoy sidecar.
Requests on 18000 are reaching envoy and since my container is not listening on 18000, it gets rejected with this error.
"RpcFailure: 14-UNAVAILABLE upstream connect error or disconnect/reset before headers. retried and the latest reset reason: remote connection failure, transport failure reason: delayed connect error: Connection refused"

I was expecting that the traffic routing rule should have redirected it to foo-bar service.

Any pointers will be appreciated.
Thank you
