### DISCUSSION TITLE
ISTIO_META_DNS_AUTO_ALLOCATE deprecated

### DISCUSSION THREAD

**Discussion by josemrs** [istio/istio#55586] [Q&A]
Hi,

According to [Istio 1.25 release notes](https://istio.io/latest/news/releases/1.25.x/announcing-1.25/change-notes/), this option has been deprecated:

> Deprecated use of ISTIO_META_DNS_AUTO_ALLOCATE in proxyMetadata in favor of a newer version of [DNS auto-allocation](https://istio.io/latest/docs/ops/configuration/traffic-management/dns-proxy/#address-auto-allocation). New users of Istio IP auto-allocation should adopt the new status based controller. Existing users may continue to use the older implementation. ([Issue #53596](https://github.com/istio/istio/issues/53596))

We do have Istio deployed with this option:

```
istiod:
  global:

    proxyMetadata:
      # Enable Istio agent to handle DNS requests for known hosts
      # Unknown hosts will automatically be resolved using upstream dns servers in resolv.conf
      ISTIO_META_DNS_CAPTURE: "true"
      ISTIO_META_DNS_AUTO_ALLOCATE: "true"
```

However, TBH, I have no idea about how to replace the deprecated option. The notes say:

> New users of Istio IP auto-allocation should adopt the new status based controller

Is this enabled by default? Is any other option we have to enable? 

We use sidecars, and we don't really have any ServiceEntry.

Also, the doc still points to use the option, https://istio.io/latest/docs/ops/configuration/traffic-management/dns-proxy/#address-auto-allocation

Thanks in advance,
Jose
