### DISCUSSION TITLE
How to use Authorization policy with destination rule mTls?

### DISCUSSION THREAD

**Discussion by agreedSkiing** [istio/istio#55597] [Q&A] [answered]
So... I don't really understand when the authorization policy is applied when using mTLS when i also have a virtual service in between and a destination rule.

The current behaviour is that the authorization policy can't see a thing and blocks all requets even though i'm only trying to block `POST`

Example of the destination rule
```
spec:
  host: <revoked-3>
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: <revoked-2>
          ttl: 10s
    tls:
      mode: MUTUAL
      credentialName: <revoked>
```
