### DISCUSSION TITLE
Implement istio in argocd rollout with Bluegreen stratgey

### DISCUSSION THREAD

**Discussion by ratnakumarchukkapalli** [istio/istio#55602] [Q&A]
We are implementing argocd rollouts with blue green strategy where we are creating two services which has active and preview. Now I would like add virtual service and destination rule. In virtual service, under destination host what is the svc name we have to give? Is it active service host or preview host? Can you please look into below files and let me know if it looks good?
 Service.yaml:

```
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-rollout-active-{{ .Values.environment }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  labels:
    {{- toYaml .Values.service.labels | nindent 4 }}
    app.kubernetes.io/instance: "{{ .Values.environment }}"
spec:
  selector:
    app: {{ include "app.fullname" . }}-{{ .Values.environment }}-rollout
    environment: "{{ .Values.environment }}"
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-rollout-preview-{{ .Values.environment }}
  annotations:    {{- toYaml .Values.service.annotations | nindent 4 }}
  labels:
    {{- toYaml .Values.service.labels | nindent 4 }}
    app.kubernetes.io/instance: "{{ .Values.environment }}"
spec:
  selector:
    app: {{ include "app.fullname" . }}-{{ .Values.environment }}-rollout
    environment: "{{ .Values.environment }}"
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
```
      
    I have found this document of argocd where istio is implemented but it was supporting only canary. Can it be extended to bluegreen too?https://argoproj.github.io/argo-rollouts/features/traffic-management/istio/#host-level-traffic-splitting
    
    ```
 strategy:
    blueGreen:
      activeService: {{ include "app.fullname" . }}-rollout-active-{{ .Values.environment }}
      previewService: {{ include "app.fullname" . }}-rollout-preview-{{ .Values.environment }}
      autoPromotionEnabled: {{ .Values.autoPromotionEnabled }}
      autoPromotionSeconds: {{ .Values.autoPromotionSeconds }}
      trafficRouting:
      istio:
        virtualService:
          name: "{{ include "app.fullname" . }}-{{ .Values.environment }}-virtualservice"
          routes:
          - app-route  # This must match your route name
        destinationRule:
          name: "{{ include "app.fullname" . }}-{{ .Values.environment }}-destination-rule"
          stableSubsetName: blue
          canarySubsetName: green
```
          
          This is the rollout.yaml which i am trying using istio. Will this work?
```
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ include "app.fullname" . }}-{{ .Values.environment }}-virtualservice"
  annotations:
    {{- with .Values.virtual_service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  {{- range $.Values.hosts }}
  - {{ . }}
  {{- end }}
  http:
  - name: app-route
    match:
    {{- range $.Values.url_path }}
    - uri:
        prefix: {{ . }}
    {{- end }}
    route:
    - destination:
    host: {{ include "app.fullname" . }}-rollout-active-{{ .Values.environment }}.{{ .Values.namespace }}.svc.cluster.local
    port:
      number: {{ .Values.application_port }}
    subset: blue  
  weight: 100
    - destination:
    host: {{ include "app.fullname" . }}-rollout-active-{{ .Values.environment }}.{{ .Values.namespace }}.svc.cluster.local
    port:
      number: {{ .Values.application_port }}
    subset: green
  weight: 0`

```
```
`# Define the available subsets of a service.
# Optionally set properties of those subsets.

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: "{{ include "app.fullname" . }}-{{ .Values.environment }}-v{{ .Values.image.tag }}-destination-rule"
  annotations:
    {{- with .Values.destination_rule.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  host: {{ include "app.fullname" . }}-rollout-active-{{ .Values.environment }}  # The k8 service
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:  # Break down the service into subsets based on the labels below.
  - name: blue  # This must match stableSubsetName in rollout.yaml
    labels:
      app: {{ include "app.fullname" . }}-{{ .Values.environment }}-rollout
  - name: green  # This must match canarySubsetName in rollout.yaml
    labels:
      app: {{ include "app.fullname" . }}-{{ .Values.environment }}-rollout
    trafficPolicy:
      loadBalancer:
        simple: RANDOM`
```
