### DISCUSSION TITLE
Trying to see why allow-all policy is not matching grpc request

### DISCUSSION THREAD

**Discussion by mmerrill3** [istio/istio#55633] [General]
Hi all, I'm running istio 1.24.3.  I setup a dummy grpc service in a namespace, without TLS for testing.   The service is running with the istio sidecar injected.  Also, traffic is coming inbound through the istio gateway that is running in the same namespace as my service.  This is just the default deployment and service that is setup for gateway api.

I test the service by running grpcurl.  When I do not have any authorization policy set, traffic is allowed... easy enough, there's no policies so rbac isn't applied.

However, if I add policies that match the request, and for this example I just use an allow-all policy, the request is still rejected by the istio sidecar running next to my grpc service.

Here's my general allow-all policy, looks good, and I verified that its applied to my pod below as well

policy:

```
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  annotations:
  name: allow-all
  namespace: mike
spec:
  selector:
    matchLabels:
      app: randrpc-server
  action: ALLOW
```

Here is my verification that the policy is applied to my pod:

```
istioctl x authz check randrpc-server-deployment-64bbc9fd8d-rp4ng.mike
ACTION   AuthorizationPolicy   RULES
ALLOW    allow-all.mike        1
```

When I now test out the service, from the logs of istio-proxy running next to my pod, we see the payload passed to rbac, and we see the payload doesn't match any policies.   We can see the traffic is handled by the gateway-istio pod and forwarded on ok.  We also see the spiffe cert for the gateway-istio pod:

```
2025-03-22T22:34:31.880523Z     debug   envoy rbac external/envoy/source/extensions/filters/http/rbac/rbac_filter.cc:161        checking request: requestedServerName: outbound_.80_._.randrpc-server-svc.mike.svc.cluster.local, sourceIP: 100.71.31.75:57234, directRemoteIP: 100.71.31.75:57234, remoteIP: 10.27.72.31:0,localAddress: 100.71.31.74:7070, ssl: uriSanPeerCertificate: spiffe://cluster.local/ns/mike/sa/gateway-istio, dnsSanPeerCertificate: , subjectPeerCertificate: , headers: ':method', 'POST'
':scheme', 'http'
':path', '/grpc.reflection.v1.ServerReflection/ServerReflectionInfo'
':authority', 'grpc.red24s.dev-sandbox-use1.k8s.dev.mike.net:80'
'content-type', 'application/grpc'
'user-agent', 'grpcurl/dev-build (no version set) grpc-go/1.61.0'
'te', 'trailers'
'grpc-accept-encoding', 'gzip'
'x-forwarded-for', '10.27.72.31'
'x-forwarded-proto', 'http'
'x-request-id', '72e801c0-0870-48db-b3f5-aada348d9fa4'
'x-envoy-attempt-count', '1'
'x-envoy-internal', 'true'
'x-forwarded-client-cert', 'By=spiffe://cluster.local/ns/mike/sa/default;Hash=3877bf3b8c8b76125ef46140f777686d972555632f420ac6beb5e28f231fc105;Subject="";URI=spiffe://cluster.local/ns/mike/sa/gateway-istio'
, dynamicMetadata:      thread=21
2025-03-22T22:34:31.880564Z     debug   envoy rbac external/envoy/source/extensions/filters/http/rbac/rbac_filter.cc:224        enforced denied, matched policy none    thread=21
```

I'm not sure if there's something special about this traffic from the gateway-istio pod to the target pod.  I do see the header for x-envoy-internal being true.  I'm not sure if that's a problem.

Basically, the traffic from the gateway-istio pod should be trusted, and its not.  The allow-all is really a sledgehammer policy, I wouldn't use this in real life.

**Comment by mmerrill3** [comment]
Answering my own question, for allow-all, the authorizationPolicy needs to have rules defined in the spec with an empty rule, like below:

```
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  annotations:
  name: allow-all
  namespace: mike
spec:
  selector:
    matchLabels:
      app: randrpc-server
  action: ALLOW
  rules:
    - {}
```
