### DISCUSSION TITLE
Istio DNS Gateway Hairpining Issues

### DISCUSSION THREAD

**Discussion by biscflowers** [istio/istio#55664] [Q&A]
**Problem:**
Currently we are running an EKS cluster in AWS. We have a k8s gateway in the cluster with Istio installed. We have a public hostname of example.com that forwards to the K8s gateway and two HTTPRoutes that map to two services off of path /a and /b.

We would like service A to be able to talk to service B over the public hostname without the traffic leaving the cluster. 

From doing research we should be able to use a service entry that targets the gateway service but in testing the DNS rewrite is not occurring when curl'ing from a pod. I have made sure that `ISTIO_META_DNS_CAPTURE` was enabled in Istiod and confirmed that the values were set to true in the injection configmap. 

**Istio install:**
We are installing Istiod and Istio-base via helm file with the following versions and values:
```yaml
repositories:
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts
releases:
- name: istio-base
  namespace: istio-system
  chart: istio/base
  version: 1.23
- name: istio-istiod
  namespace: istio-system
  chart: istio/istiod
  version: 1.23
  values:
  - global:
      meshConfig:
        defaultConfig:
          proxyMetadata:
            ISTIO_META_DNS_CAPTURE: "true"
            ISTIO_META_DNS_AUTO_ALLOCATE: "true"
```

**Gateway Config:**
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    proxy.istio.io/config: '{"gatewayTopology" : { "proxyProtocol": {} }}'
spec:
  gatewayClassName: istio
  listeners:
  - name: https-proxy  
    hostname: $publicHostname
    port: 443  
    protocol: HTTPS
    tls:  
      mode: Terminate  
      certificateRefs:
      - kind: Secret  
        name: $secretName  
```

**Service Entry Config**

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: svc-redirect
spec:
  endpoints:
    - address: $gatewayService.$gatewayNamespace.svc.cluster.local
  hosts:
    - $publicDomain
  location: MESH_INTERNAL
  ports:
    - name: https
      number: 443
      protocol: TLS
  resolution: DNS
```

**References:**
https://discuss.istio.io/t/best-way-to-to-route-public-service-dns-internally/9390/4
