### DISCUSSION TITLE
Applying authorization policy to passthrough ingress-egress traffic

### DISCUSSION THREAD

**Discussion by lyngekpdxc** [istio/istio#55717] [General]
We are working on implementing a service gateway using istio. We have some services that are hosted outside of our Kubernetes environment and would like to expose these using istio as a gateway or proxy while applying custom authorization policies to accessing these services as well as our cluster-internal resources.

I have installed Istio in Ambient mode and I am able to apply policies using a waypoint gateway to applications/pods within the cluster when calling through an ingress gateway exposing our cluster on a specified hostname.
I can't make this work however when applying policies directly on an external service exposed via a ServiceEntry resource. Reading the documentation it seems like this should be possible, and it seems like the ServiceEntry is part of the mesh?
Policies are applied when calling from a curl pod inside the namespace. But not when calling in from outside of the cluster from my local machine, i.e. on `egress-test.our.domain.com/httpbin/status/200`

My test configuration is as follows. Am I missing something?
I have tried applying the authorization policy to the ServiceEntry itself and the waypoint gateway both.

We are running Istio version 1.25.

```
apiVersion: v1
kind: Namespace
metadata:
  name: egress-test
  labels:
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: waypoint
    istio.io/ingress-use-waypoint: "true"
    istio.io/egress-use-waypoint: "true" # Is there, or should there be an egress variant of ingress-use-waypoint?
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ingress-gateway
  namespace: egress-test
spec:
  gatewayClassName: istio
  addresses:
    - value: 123.123.123.123
      type: IPAddress
  listeners:
  - name: http
    hostname: "*.our.domain.com"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: waypoint
  namespace: egress-test
  labels:
    istio.io/waypoint-for: all
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - name: mesh
    port: 15008
    protocol: HBONE
  - name: http
    port: 80
    protocol: HTTP
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: httpbin.org
  namespace: egress-test
  labels:
    istio.io/use-waypoint: waypoint
spec:
  hosts:
  - httpbin.org
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: httpbin
  namespace: egress-test
spec:
  targetRefs:
  - kind: ServiceEntry
    group: networking.istio.io
    name: httpbin.org
  # - kind: Gateway
  #   group: gateway.networking.k8s.io
  #   name: waypoint
  action: ALLOW
  rules:
    - to:
      - operation: 
          paths:
            - /*
      when:
        - key: request.headers[iam]
          values: [ "vip" ]
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httpbin
  namespace: egress-test
spec:
  parentRefs:
  - name: ingress-gateway
    namespace: egress-test
  hostnames: ["egress-test.our.domain.com"]
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /httpbin
    filters:
      - type: URLRewrite
        urlRewrite:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: /
    backendRefs:
      - kind: Hostname
        group: networking.istio.io
        name: httpbin.org
        port: 80
```

**Comment by ilrudie** [comment]
Can you explain the traffic flow you are looking for when you say "But not when calling in from outside of the cluster from my local machine"? Would you be looking for `ingress-gw -> egress-gw -> external dst`?

**Reply by lyngekpdxc** [reply]
That sounds about it yes. I haven't explicitly defined an egress gateway in this case. I have tried doing so, but without much success either.

From my local machine I would think the flow would be like so
`Local machine -> ingress-gw -> serviceentry/waypoint proxy -> external dst`
I am expecting that adding the ServiceEntry for the external destination would allow me to attach authorization policies for traffic flowing to the external destination for traffic directly from ingress as well.

**Reply by howardjohn** [reply]
https://ambientmesh.io/docs/traffic/gateways/#gateways-and-waypoints should make this work

**Reply by lyngekpdxc** [reply]
I had actually already tried adding this to the service as well. I had a bit of trouble finding the documentation for the `istio.io/ingress-use-waypoint: "true"` label, but it made no difference to me adding it to the service entry or the namespace in this case unfortunately.

When getting the service entry and authorization policy in the deployed mesh it seems like the policy should be applied and the service entry should be registered in my waypoint proxy. But the authorization policy is not enforced?

kubectl get serviceentry httpbin.org -n egress-test -oyaml
```yaml
status:
  addresses:
  - host: httpbin.org
    value: 240.240.0.51
  - host: httpbin.org
    value: 2001:2::33
  conditions:
  - lastTransitionTime: "2025-03-31T07:15:49.666257214Z"
    message: Successfully attached to waypoint egress-test/waypoint. Ingress traffic
      will traverse the waypoint
    reason: WaypointAccepted
    status: "True"
    type: istio.io/WaypointBound
```

kubectl get authorizationpolicy httpbin -n egress-test -oyaml
```yaml
status:
  conditions:
  - lastTransitionTime: "2025-03-31T07:15:49.676331287Z"
    message: bound to egress-test/waypoint
    observedGeneration: "1"
    reason: Accepted
    status: "True"
    type: WaypointAccepted
```

**Comment by ilrudie** [comment]
@howardjohn, Would we expect this kind of setup to work after https://github.com/istio/istio/pull/54765? I don't really see why the ingress should not honor the waypoint for this SE. On local repro I see traffic skip the waypoint. My SE has:
```yaml
  conditions:
  - lastTransitionTime: "2025-03-28T15:25:10.650154801Z"
    message: Successfully attached to waypoint egress-test/waypoint. Ingress traffic
      will traverse the waypoint
    reason: WaypointAccepted
    status: "True"
    type: istio.io/WaypointBound
```
