### DISCUSSION TITLE
Issues with `consistentHash` load balancing when header set in VirtualService

### DISCUSSION THREAD

**Discussion by aiguofer** [istio/istio#55723] [Q&A]
Hey all, we currently have working sticky sessions based on a header with something like:

```
kind: DestinationRule
...
spec:
  host: app.namespace.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: "header"
-------------------
kind: VirtualService
...
spec:
  hosts:
  - app.namespace.svc.cluster.local
  gateways:
  - istio-ingress/default-gateway

  http:
  - route:
    - destination:
        host: app.namespace.svc.cluster.local
        port:
          number: 8000
```

We want to change our sticky session behavior to take into account 3 headers instead, so I figured I'd create a header in the `VirtualService` then use that in my `DestinationRule` to get session affinity. Something like:

```
kind: DestinationRule
...
spec:
  host: app.namespace.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      consistentHash:
        # This is created in the VirtualService
        httpHeaderName: "sticky-session"
-------------------
kind: VirtualService
...
spec:
  hosts:
  - app.namespace.svc.cluster.local
  gateways:
  - istio-ingress/default-gateway

  http:
  - route:
    - destination:
        host: app.namespace.svc.cluster.local
        port:
          number: 8000
    headers:
      request:
        set:
          # This is used in the DestinationRule
          sticky-session: "%REQ(header)%-%REQ(header-two)%-%REQ(header-three)%"
```

Unfortunately, this seems to break our sticky sessions, even though the `sticky-session` header is properly created and sent to each pod as part of the request. Any help would be greatly appreciated!!
