### DISCUSSION TITLE
IngressGateway act as reverse proxy

### DISCUSSION THREAD

**Discussion by yuzhouliu9** [istio/istio#55755] [Q&A] [answered]
Hello,

I'm trying to configure an Ingress Gateway to act as a reverse-proxy.
Requests from external clients to externalhttpbin.example.com should go to the istio public ingress gateway, then forwarded to httpbin.org.

I saw a similar configuration https://github.com/istio/istio/discussions/52493. The accepted answer was to configure a DestinationRule but I cannot get it to work.

```
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: externalhttpbin
  namespace: routing-rules
spec:
  selector:
    istio: istio-ingressgateway-public
  servers:
  - hosts:
    - externalhttpbin.example.com
    name: externalhttpbin
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: externalhttpbin
  namespace: routing-rules
spec:
  gateways:
  - externalhttpbin
  hosts:
  - externalhttpbin.example.com
  http:
  - match:
    - uri:
        prefix: "/external"
    rewrite:
      uri: "/"
      # authority: "httpbin.org" # This does not work?
    route:
    - destination:
        host: httpbin.org
        port:
          number: 443
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-services
  namespace: routing
spec:
  hosts:
  - httpbin.org
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
  location: MESH_EXTERNAL
```

DestinationRule
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: httpbin-org
  namespace: routing
spec:
  host: httpbin.org
  trafficPolicy:
    tls:
      mode: SIMPLE
      # insecureSkipVerify: true # uncomment to see forwarding request plaintext works
```

Results in 
```
upstream connect error or disconnect/reset before headers. retried and the latest reset reason: remote connection failure, transport failure reason: TLS_error:|268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED:TLS_error_end:TLS_error_end
```

```
> istioctl analyze
...
Error [IST0128] (DestinationRule routing/httpbin-org) DestinationRule routing/httpbin-org in namespace routing has TLS mode set to SIMPLE but no caCertificates are set to validate server identity for host: httpbin.org
```

Does the DestinationRule need a `tls.caCertificate`?
Is it the caCertificate loaded on the ingressgateway?

**Comment by yuzhouliu9** [comment, marked as answer]
Found the fix: https://github.com/istio/istio/issues/50997#issuecomment-2128153161
On DestinationRule setting `sni: httpbin.org` fixed it

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: httpbin-org
  namespace: routing
spec:
  host: httpbin.org
  trafficPolicy:
    tls:
      mode: SIMPLE
      sni: httpbin.org
```
