### DISCUSSION TITLE
https egress traffic through gateway causes SSL_ERROR_SYSCALL while http works fine

### DISCUSSION THREAD

**Discussion by ssichynskyi** [istio/istio#55773] [Q&A] [answered]
Hello. I have an istio ambient mesh successfully running in my k8s cluster (in most of user namespaces).
I've came through a multiple tutorials trying to compile them and get a working solution as well as came across the reported bugs and questions here on GitHub.
Although similar questions and issues exist, they are usually ~6 month old and has no resolution, or a resolution that is not applicable in my case.
Yet, I'm not able to configure a proper egress gateway that works for https connection. Maybe I'm just missing something. Please explain where I'm doing things in the wrong way.

### Setup
```
$ kubectl version
Client Version: v1.32.2
Kustomize Version: v5.5.0
Server Version: v1.32.2-gke.1182001
```
```
helm version --short
v3.17.2+gcc0bbbd
```
There's also ingress-nginx setup.

Istio installed using this set of helm charts:
https://artifacthub.io/packages/helm/istio-official/base     v1.25.1
https://artifacthub.io/packages/helm/istio-official/istiod    v1.25.1
https://artifacthub.io/packages/helm/istio-official/cni        v1.25.1
https://artifacthub.io/packages/helm/istio-official/ztunnel v1.25.1

Through studying the documentation, I've applied these additional values:
istio-cni:
```yaml
    dnsCapture: true
```

istiod:
```yaml
    env:
      PILOT_ENABLE_ALPHA_GATEWAY_API: true
      PILOT_ENABLE_IP_AUTOALLOCATE: true
```
`PILOT_ENABLE_ALPHA_GATEWAY_API` seems like not needed, but I've tried both values with the same end result.

ztunnel:
```yaml
    meshConfig:
      defaultConfig:
        proxyMetadata:
          ISTIO_META_DNS_CAPTURE: "true"
```

### Deployment
```yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio.io/use-waypoint: egress-waypoint
    istio.io/dataplane-mode: ambient
  name: istio-egress
---
apiVersion: v1
kind: Pod
metadata:
  namespace: istio-egress
  name: debugger
spec:
  containers:
    - name: debug-container
      image: jonlabelle/network-tools
      command: ["sleep", "36000"]
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: egress-waypoint
  namespace: istio-egress
  labels:
    istio.io/waypoint-for: all
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - name: mesh
    port: 15008
    protocol: HBONE
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  annotations:
  # labels:
  #   istio.io/use-waypoint: egress-waypoint
  name: httpbin.org
  namespace: istio-egress
spec:
  hosts:
  - httpbin.org
  ports:
  - name: http
    number: 80
    protocol: HTTP
  - name: https
    number: 443
    protocol: HTTPS
  location: MESH_EXTERNAL
  resolution: DNS
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: httpbin.org
  namespace: istio-egress
spec:
  host: httpbin.org
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 80
      tls:
        mode: ISTIO_MUTUAL
    - port:
        number: 443
      tls:
        # Also tried SIMPLE with the same end result
        mode: ISTIO_MUTUAL
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: httpbin
  namespace: istio-egress
spec:
  targetRefs:
    # Also tried attaching to gateway with the same end result
  - kind: ServiceEntry
    group: networking.istio.io
    name: httpbin.org
  action: ALLOW
  rules:
  - to:
    - operation:
        hosts: ["httpbin.org"]
        methods: ["GET"]
        # paths: ["/get"]
```

### Actions and results
I ssh into `debugger` pod and call:

1. Restricted method via HTTP (works as expected, OK)
```
debugger:/# curl -vX POST "http://httpbin.org/status/202"
* Host httpbin.org:80 was resolved.
* IPv6: 2001:2::9
* IPv4: 240.240.0.9
*   Trying [2001:2::9]:80...
* Immediate connect fail for 2001:2::9: Address not available
*   Trying 240.240.0.9:80...
* Connected to httpbin.org (240.240.0.9) port 80
* using HTTP/1.x
> POST /status/202 HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/8.12.1
> Accept: */*
> 
* Request completely sent off
< HTTP/1.1 403 Forbidden
< content-length: 19
< content-type: text/plain
< date: Tue, 01 Apr 2025 23:53:05 GMT
< server: istio-envoy
< x-envoy-decorator-operation: httpbin.org:80/*
< 
* Connection #0 to host httpbin.org left intact
RBAC: access denied
```
2. Non-restricted method via HTTP (works as expected, OK)
```
debugger:/# curl -vX GET http://httpbin.org/status/200
Note: Unnecessary use of -X or --request, GET is already inferred.
* Host httpbin.org:80 was resolved.
* IPv6: 2001:2::9
* IPv4: 240.240.0.9
*   Trying [2001:2::9]:80...
* Immediate connect fail for 2001:2::9: Address not available
*   Trying 240.240.0.9:80...
* Connected to httpbin.org (240.240.0.9) port 80
* using HTTP/1.x
> GET /status/200 HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/8.12.1
> Accept: */*
> 
* Request completely sent off
< HTTP/1.1 200 OK
< date: Tue, 01 Apr 2025 23:54:58 GMT
< content-type: text/html; charset=utf-8
< content-length: 0
< server: istio-envoy
< access-control-allow-origin: *
< access-control-allow-credentials: true
< x-envoy-upstream-service-time: 190
< x-envoy-decorator-operation: httpbin.org:80/*
< 
* Connection #0 to host httpbin.org left intact
```
3. Any call using https to a controlled resource `httpbin.org` leads to the same error (not as expected, NOK!)
```
debugger:/# curl -vX GET https://httpbin.org/status/200
Note: Unnecessary use of -X or --request, GET is already inferred.
* Host httpbin.org:443 was resolved.
* IPv6: 2001:2::9
* IPv4: 240.240.0.9
*   Trying [2001:2::9]:443...
* Immediate connect fail for 2001:2::9: Address not available
*   Trying 240.240.0.9:443...
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: /etc/ssl/certs
* TLS connect error: error:00000000:lib(0)::reason(0)
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to httpbin.org:443 
* closing connection #0
curl: (35) TLS connect error: error:00000000:lib(0)::reason(0)
```
4. Any call to a non-controlled external resource also succeed, because it bypasses the `ServiceEntry` and proxy for example (works as expected, OK) :
```
# curl -vX GET https://blockstream.info/api/blocks/tip/height
```

ztunnel logs  looks OK IMO:
HTTP:
```json
{
  "level": "info",
  "time": "2025-04-01T23:57:34.225027Z",
  "scope": "access",
  "message": "connection complete",
  "src.addr": "10.112.3.125:47930",
  "src.workload": "debugger",
  "src.namespace": "istio-egress",
  "src.identity": "spiffe://cluster.local/ns/istio-egress/sa/default",
  "dst.addr": "10.112.2.16:15008",
  "dst.hbone_addr": "240.240.0.9:80",
  "dst.service": "httpbin.org",
  "dst.workload": "egress-waypoint-7b9f9f6649-zfxxc",
  "dst.namespace": "istio-egress",
  "dst.identity": "spiffe://cluster.local/ns/istio-egress/sa/egress-waypoint",
  "direction": "outbound",
  "bytes_sent": 85,
  "bytes_recv": 291,
  "duration": "192ms"
}
```
HTTPS:
```json
{
  "level": "info",
  "time": "2025-04-01T23:57:40.967121Z",
  "scope": "access",
  "message": "connection complete",
  "src.addr": "10.112.3.125:37486",
  "src.workload": "debugger",
  "src.namespace": "istio-egress",
  "src.identity": "spiffe://cluster.local/ns/istio-egress/sa/default",
  "dst.addr": "10.112.2.16:15008",
  "dst.hbone_addr": "240.240.0.9:443",
  "dst.service": "httpbin.org",
  "dst.workload": "egress-waypoint-7b9f9f6649-zfxxc",
  "dst.namespace": "istio-egress",
  "dst.identity": "spiffe://cluster.local/ns/istio-egress/sa/egress-waypoint",
  "direction": "outbound",
  "bytes_sent": 517,
  "bytes_recv": 0,
  "duration": "98ms"
}
```
* - There's one difference, if `AutorizationPolicy` is attached to a Gateway instead of ServiceEntry, ztunnel logs for HTTP traffic are not available

I don't see any logs from the waypoint (gateway) pod for any of those cases.

### What I want to achieve at the end
To have an istio-controlled, L7 proxy for the egress traffic coming from pods. Both http and https. Egress traffic shall leave through a NAT gateway.

### Short catalog of used documentation and similar issues:
https://istio.io/latest/docs/ambient/usage/waypoint/#useawaypoint
https://docs.solo.io/gloo-mesh/main/istio/ambient/egress/
https://www.solo.io/blog/egress-gateways-made-easy
https://ambientmesh.io/docs/traffic/mesh-egress/
https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/
https://github.com/istio/istio/discussions/51827
https://github.com/istio/istio/discussions/45824
https://github.com/istio/istio/issues/27067
https://github.com/istio/istio/issues/51482
https://github.com/istio/istio/issues/45854
https://github.com/istio/istio/issues/52532
