### DISCUSSION TITLE
AuthorizationPolicy only works in the istio-system namespace

### DISCUSSION THREAD

**Discussion by davidshen84** [istio/istio#55841] [Q&A]
Hi,

According to the documents AuthorizationPolicy should work in all namespaces.

I have a simple AuthorizationPolicy that denies all requests:

```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: deny-all
spec:
  {}
```

If I apply it to the `istio-system` namespace, where my other istio related resources are deployed, the policy works and my requests are denied.

If I put it into any other namespace, like the `default` namespace where my app is deployed, it has no effect.

I don't have PeerAuthentication or RequestAuthenticate resources in my cluster.
