### DISCUSSION TITLE
Gateway API share IP for multiple gateways

### DISCUSSION THREAD

**Discussion by finomen** [istio/istio#55866] [Q&A] [answered]
Is there an option to create multiple gateways (gateway.networking.k8s.io/v1, nost istio) using the same ip/port but diffrent hostnames? (like mergeGateways in envoy)

Cluster is runnign on bare metal (talos) with Cilium CNI.

**Comment by howardjohn** [comment, marked as answer]
@finomen there is - basically you can use https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/#manual-deployment to attach a Gateway to an existing deployment/service. So you would make 1 with "automated mode" then the rest as 'manual'.

Note https://gateway-api.sigs.k8s.io/geps/gep-1713 is really the proper way forward (https://github.com/istio/istio/pull/55595)

**Comment by finomen** [comment]
Is there complete example for manual deployment? I got error "hostname not found" when I try to do that. Tried names of both gateway and service (line default-gw.istio-ingress.svc.k8s.cluster and default-gw-istio.istio-ingress.svc.k8s.cluster)

GEP-1713 is not supported by borh cert-manager and kserve

**Comment by GDXbsv** [comment]
I constantly have an error
```
skipping server on gateway gateway-public-review-all-istio-autogenerated-k8s-gateway-https-r port default.443.HTTPS: conflict with existing server 443.HTTPS 
```

I can not use 2 listeners with the same port/protocol but with different names and hosts

```
    - name: https
      hostname: "*.domain.example.com"
      protocol: HTTP
      port: 443
      allowedRoutes:
        namespaces:
          from: All
-------------------------------------------------------
    - name: https-r
      hostname: "*.domain2.example2.net"
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              review-app-name: {{ .Values.name }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: gateway-https-ca-cert
```

**Reply by howardjohn** [reply]
that's not the same protocol ... one is HTTP and the other is HTTPS. the "name" field is not relevant but rather the "protocol"

**Reply by GDXbsv** [reply]
With this one it does not work with the same reason

It just not allow creating listeners on the same protocol. Maybe I am doing something wrong, of course.
```
    - name: https
      hostname: "*.domain.example.com"
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
```
