### DISCUSSION TITLE
mTLS over http port

### DISCUSSION THREAD

**Discussion by KeyurB** [istio/istio#55873] [Q&A]
I would like to understand how mTLS works for http port. 

I have one ES service which has ports mentioned 9200, 9300.

```
ports:
  - appProtocol: http
    name: http
    port: 9200
    protocol: TCP
    targetPort: http
  - appProtocol: TCP
    name: peer
    port: 9300
    protocol: TCP
    targetPort: peer
 ```
 
 And i have sidecar configuration for this service
 
 ```
 Spec:
  Egress:
    Hosts:
      es7-service.es7.svc.cluster.local
```
 
 
 Listeners generated for this service
 
 ```
 0.0.0.0        9200  Trans: raw_buffer; App: http/1.1,h2c                                                            Route: 9200
0.0.0.0        9200  ALL                                                                                             PassthroughCluster
10.4.110.35    9300  ALL                                                                                             Cluster: outbound|9300||es7-service.es7.svc.cluster.local
10.4.79.179    9300  ALL                                                                                             Cluster: outbound|9300||es7-service.es7.svc.cluster.local
```

My expectation is that for 9200 port the traffic will be routed through Cluster named as " outbound|9200||es7-service.es7.svc.cluster.local". But instead it was routed through PassthroughCluster.

In service definition when port changed to tcp, listeners are generated for 9200 port also, 

```
10.4.110.35    9200  ALL                                                                                             Cluster: outbound|9200||es7-service.es7.svc.cluster.local
10.4.79.179    9200  ALL                                                                                             Cluster: outbound|9200||es7-service.es7.svc.cluster.local
10.4.110.35    9300  ALL                                                                                             Cluster: outbound|9300||es7-service.es7.svc.cluster.local
10.4.79.179    9300  ALL                                                                                             Cluster: outbound|9300||es7-service.es7.svc.cluster.local
```

Is this expected behaivour while using http port ? What will happen if STRICT mTLS is enabled, how the traffic will be encrypted ?
