### DISCUSSION TITLE
How to configure SSL termination on gateway (using gateway api)? Got connection refused

### DISCUSSION THREAD

**Discussion by finomen** [istio/istio#55891] [Q&A] [answered]
Cluste is on bare metal (talos) with cilium CNI
Isio is installed in istio-system, ambient mode from helm

```
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
spec:
  interval: 5m0s
  upgrade:
    force: true
  chart: 
    spec:
      chart: base
      sourceRef:
        kind: HelmRepository
        name: istio
  releaseName: istio-base
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
spec:
  interval: 5m0s
  upgrade:
    force: true
  chart:
    spec:
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
  releaseName: istiod
  values:
    profile: ambient
    global:
      proxy:
        clusterDomain: k8s.finomen.net
    pilot:
      cni:
        enabled: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
spec:
  interval: 10m0s
  upgrade:
    force: true
  chart:
    spec:
      chart: cni
      sourceRef:
        kind: HelmRepository
        name: istio
  releaseName: cni
  values:
    profile: ambient
    global:
      proxy:
        clusterDomain: k8s.finomen.net
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ztunnel
spec:
  interval: 5m0s
  upgrade:
    force: true
  chart:
    spec:
      chart: ztunnel
      sourceRef:
        kind: HelmRepository
        name: istio
  releaseName: ztunnel
  values:
    global:
      proxy:
        clusterDomain: k8s.finomen.net
```

In istio-ingress following resources created:

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: default-gateway
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    hostname: finomen.net
    allowedRoutes:
      namespaces:
        from: All
  - name: https
    port: 443
    protocol: HTTPS
    hostname: finomen.net
    tls:
      mode: Terminate
      certificateRefs:
      - name: default-gw-cert
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-filter-redirect
spec:
  parentRefs:
  - name: default-gateway
    sectionName: http
  hostnames:
  - finomen.net
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
```

and
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
spec:
  replicas: 5
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - image: ealen/echo-server:latest
        imagePullPolicy: IfNotPresent
        name: echoserver
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app: echoserver
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: echo-gw
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: istio
  addresses:
  - value: default-gateway-istio.istio-ingress.svc.k8s.finomen.net
    type: Hostname
  listeners:
  - name: https
    hostname: echo.finomen.net
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - name: echo-gw-cert
    allowedRoutes:
      namespaces:
        from: All
  - name: http
    hostname: echo.finomen.net
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo-route
spec:
  parentRefs:
  - name: echo-gw
    sectionName: http
  - name: echo-gw
    sectionName: https
  hostnames:
  - echo.finomen.net
  rules:
  - backendRefs:
    - name: echoserver
      port: 80
```

Gateway status looks ok
```
Name:         echo-gw
Namespace:    istio-ingress
Labels:       <none>
Annotations:  cert-manager.io/cluster-issuer: letsencrypt-prod
API Version:  gateway.networking.k8s.io/v1
Kind:         Gateway
Metadata:
  Creation Timestamp:  2025-04-11T11:02:27Z
  Generation:          6
  Resource Version:    39634390
  UID:                 e3be8b38-acbb-4f22-9049-73f1edd2c3f2
Spec:
  Addresses:
    Type:              Hostname
    Value:             default-gateway-istio.istio-ingress.svc.k8s.finomen.net
  Gateway Class Name:  istio
  Listeners:
    Allowed Routes:
      Namespaces:
        From:  All
    Hostname:  echo.finomen.net
    Name:      https
    Port:      443
    Protocol:  HTTPS
    Tls:
      Certificate Refs:
        Group:  
        Kind:   Secret
        Name:   echo-gw-cert
      Mode:     Terminate
    Allowed Routes:
      Namespaces:
        From:  All
    Hostname:  echo.finomen.net
    Name:      http
    Port:      80
    Protocol:  HTTP
Status:
  Addresses:
    Type:   IPAddress
    Value:  95.217.228.183
    Type:   IPAddress
    Value:  a01:4f8:221:300b::
  Conditions:
    Last Transition Time:  2025-04-11T11:02:27Z
    Message:               Resource accepted
    Observed Generation:   6
    Reason:                Accepted
    Status:                True
    Type:                  Accepted
    Last Transition Time:  2025-04-11T11:03:51Z
    Message:               Resource programmed, assigned to service(s) default-gateway-istio.istio-ingress.svc.k8s.finomen.net:443 and default-gateway-istio.istio-ingress.svc.k8s.finomen.net:80
    Observed Generation:   6
    Reason:                Programmed
    Status:                True
    Type:                  Programmed
  Listeners:
    Attached Routes:  1
    Conditions:
      Last Transition Time:  2025-04-11T11:02:27Z
      Message:               No errors found
      Observed Generation:   6
      Reason:                Accepted
      Status:                True
      Type:                  Accepted
      Last Transition Time:  2025-04-11T11:02:27Z
      Message:               No errors found
      Observed Generation:   6
      Reason:                NoConflicts
      Status:                False
      Type:                  Conflicted
      Last Transition Time:  2025-04-11T11:10:57Z
      Message:               No errors found
      Observed Generation:   6
      Reason:                Programmed
      Status:                True
      Type:                  Programmed
      Last Transition Time:  2025-04-11T11:10:57Z
      Message:               No errors found
      Observed Generation:   6
      Reason:                ResolvedRefs
      Status:                True
      Type:                  ResolvedRefs
    Name:                    https
    Supported Kinds:
      Group:          gateway.networking.k8s.io
      Kind:           HTTPRoute
      Group:          gateway.networking.k8s.io
      Kind:           GRPCRoute
    Attached Routes:  1
    Conditions:
      Last Transition Time:  2025-04-11T11:02:27Z
      Message:               No errors found
      Observed Generation:   6
      Reason:                Accepted
      Status:                True
      Type:                  Accepted
      Last Transition Time:  2025-04-11T11:02:27Z
      Message:               No errors found
      Observed Generation:   6
      Reason:                NoConflicts
      Status:                False
      Type:                  Conflicted
      Last Transition Time:  2025-04-11T11:02:27Z
      Message:               No errors found
      Observed Generation:   6
      Reason:                Programmed
      Status:                True
      Type:                  Programmed
      Last Transition Time:  2025-04-11T11:02:27Z
      Message:               No errors found
      Observed Generation:   6
      Reason:                ResolvedRefs
      Status:                True
      Type:                  ResolvedRefs
    Name:                    http
    Supported Kinds:
      Group:  gateway.networking.k8s.io
      Kind:   HTTPRoute
      Group:  gateway.networking.k8s.io
      Kind:   GRPCRoute
Events:
  Type    Reason             Age   From                       Message
  ----    ------             ----  ----                       -------
  Normal  CreateCertificate  12m   cert-manager-gateway-shim  Successfully created Certificate "echo-gw-cert"
  Normal  UpdateCertificate  10m   cert-manager-gateway-shim  Successfully updated Certificate "echo-gw-cert"
```

`curl -H"Host: echo.finomen.net" -vv http://95.217.228.183` works as expected
`curl -H"Host: echo.finomen.net" -vv https://95.217.228.183` does not with error:

```
*   Trying 95.217.228.183:443...
* Connected to 95.217.228.183 (95.217.228.183) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* Recv failure: Connection reset by peer
* OpenSSL SSL_connect: Connection reset by peer in connection to 95.217.228.183:443 
* closing connection #0
curl: (35) Recv failure: Connection reset by peer
```

Looking into hubble-ui, I see accepted packets on port 443 to ztunnel and istiod when I preform this request but could not found what's wrong
