### DISCUSSION TITLE
Upgrade/migration issue: Istio From 1.23.4 (installed using istioctl) to 1.24.4 (using helm charts)

### DISCUSSION THREAD

**Discussion by anoopne** [istio/istio#55928] [Q&A]
Hi,
We recently wanted to migrate from istioctl approach of istio deployment(doing since last few years) to Helm chart approach.
Did the following uninstall actions:
1. istioctl purge ran to remove all control plane and cni
2. kubectl delete <yaml > to delete both ingress and egress gateways
3. CRDs were removed manually.  So all virtual services, destination rules. service entries and gateway got removed alongwith..
Post this we did install using Helm install command and using the helm chars are per the istio documentation. We  did not use legacy gateway charts. But the gateway chart common for both ingress and egress .
The installation went fine. But the service discovery seems broken as the communication between the microservices(application) and to external is not working,. Can see logs in ingress gateway istio-proxy but no logs seen in egress gateway istio-proxy.
We are running istio in a dedicated GKE cluster.
The CRD are recreated from base chart using helm install and we have yaml files for virtual services, gateway,service entries and destination rule. Which are applied using kubectl commands. 
When we rollback to istioctl based install it works but when install done using helm it breaks. Thanks for any inputs in advance.

**Comment by howardjohn** [comment]
I'd assume the change in the gateway chart is mismatching your config. Maybe your labels on your Gateway (or even port) is no longer matching. Impossible to tell without the config but I bet it's mismatched Gateway

**Reply by anoopne** [reply]
Thanks @howardjohn  for the quick response..
Adding some more information to support the advice.

We have custom gateways(one sample below) which has only Istio: ab-egressgateway in selector but the gateway deployment has two selectors ie->  app: and Istio: Will this be a problem?

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
   name: forock
   namespace: egress
spec:
   selector:
     Istio: ab-egressgateway

--------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ab-egressgateway
  namespace: egress
  labels:
    app.kubernetes.io/name: ab-egressgateway
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "egress"
    app.kubernetes.io/part-of: "Istio"
    app.kubernetes.io/version: "1.24.4"
    helm.sh/chart: gateway-1.24.2
    app: ab-egressgateway
    Istio: ab-egressgateway
```
-------------------------

COMING TO PORTS THE NEW GATEWAY CHART HAS DIFFERENCE FROM PAST PORTs for gateway CONTAINERS and SERVICES:

In the ab-egressgateway deployment, below is the ONLY container port which is coming from the default values.yaml file in charts folder.
```
ports:
- containerPort: 15090
  protocol: TCP
  name: http-envoy-prom
```
since the template has fixed port values, even if additional ports are added to values.yaml it is not taken

-----------------------------
Service port values are below  which is again coming from default values.yaml file from charts folder
```
service:
  type: ClusterIP
  ports:
  - name: status-port
    port: 15021
    protocol: TCP
    targetport: 15021
  - name: http2
    port: 80
    protocol: TCP
    targetport: 80
  - name: https
    port: 443
    protocol: TCP
    targetport: 443
```

---------------------------------------
we have custom gateways like below example and some other custom gateways  listening on 15443 . Virtual services on port: 80 

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
   name:forock
   namespace: egress
spec:
   selector:
     Istio: ab-egressgateway
   servers:
   - hosts:
     - sit3.sec.gcp
     port:
       name: https-forock-sit3
       protocol: HTTPS
       number: 443  
```
