### DISCUSSION TITLE
Question regarding Destination rule behaviour with v1.22+

### DISCUSSION THREAD

**Discussion by preethakvrtk** [istio/istio#55971] [Q&A]
Hey all, 

I am seeing weird behaviour where  my gateway is not able to route request to the upstream service if do not set SNI explicitly 

From the doc, i understand that this would be set to host 
` SNI string to present to the server during TLS handshake. If unspecified, SNI will be automatically set based on downstream HTTP host/authority header for SIMPLE and MUTUAL TLS modes.`
https://istio.io/v1.24/docs/reference/config/networking/destination-rule/

this was the behaviour until v1.20.7.
Below is an snippet from DR 

```
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
::::
  host: piglet.test.io
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 10
        tcpKeepalive:
          interval: 20s
          time: 120s
    tls:
      mode: SIMPLE
```

the below is the error seen when SNI is not explicitly set 

```
URX,UF upstream_reset_before_response_started{remote_connection_failure|TLS_error:|268435581:SSL_routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED:TLS_error_end} - "TLS_error:|268435581:SSL_routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED:TLS_error_end
```
Appreciate any help understand the change in the behaviour 🙏

**Comment by emreberber** [comment]
@preethakvrtk Hello. Did you find any fix in here? I've same problem for update my Istio version.

**Comment by sushmanthc** [comment]
@preethakvrtk  Hi , did you get any Solution for above issue? i am seeing same in version 1.26.2

**Comment by ramaraochavali** [comment]
This is related to this change https://github.com/istio/istio/blob/69b44d6100a14bf195ce509d7bdf8778aec82944/releasenotes/notes/enable-auto-sni.yaml#L6

**Reply by sushmanthc** [reply]
I have tried with both options true and false for this ENABLE_AUTO_SNI but no luck.

my destination rule looks like below

````
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRulespec:
  host: microapi-worker-operations
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 5000
        maxRequestsPerConnection: 500
      tcp:
        maxConnections: 50000
    outlierDetection:
      baseEjectionTime: 30s
      consecutive5xxErrors: 20
      consecutiveGatewayErrors: 0
      interval: 10s
      maxEjectionPercent: 100
    tls:
      mode: ISTIO_MUTUAL
```
