### DISCUSSION TITLE
[Ambient] Migration from Sidecar to Ambient mode - Trafic to External Service with mTLS fails

### DISCUSSION THREAD

**Discussion by smilingbullet** [istio/istio#56003] [Q&A] [answered]
Hello, I have an application deployed in sidecar mode and I want to switch to ambient mode. This application calls external service using mTLS.

Kube version: 1.31
Istio version: 1.24.2

Here is the configuration which makes it work in sidecar mode.

```yaml
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: my-ns-egress-gw
  namespace: my-ns
spec:
  selector:
    istio: egressgateway
  servers:
  - hosts:
    - service.external.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: ISTIO_MUTUAL

---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: vs-through-egress-for-service.external.com
  namespace: my-ns
spec:
  gateways:
  - mesh
  - my-ns-egress-gw
  hosts:
  - service.external.com
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        port:
          number: 443
  - match:
    - gateways:
      - my-ns-egress-gw
      port: 443
    route:
    - destination:
        host: service.external.com
        port:
          number: 443

---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  labels:
    mtls-through-egress: "true"
  name: my-ns-service.external.com-mutualtls
  namespace: my-ns
spec:
  exportTo:
  - .
  host: istio-egressgateway.istio-system.svc.cluster.local
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: ISTIO_MUTUAL
        sni: service.external.com

apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  labels:
    mtls-from-egress: "true"
  name: my-ns-service.external.com-originate-mtls
  namespace: my-ns
spec:
  exportTo:
  - istio-system
  host: service.external.com
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 443
      tls:
        credentialName: mtls-client-creds
        mode: MUTUAL
        sni: service.external.com

---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: my-app-service.external.com
  namespace: my-ns
spec:
  hosts:
  - service.external.com
  ports:
  - name: tls
    number: 443
    protocol: TLS
  resolution: DNS
```

When I try to call the external service from my pod, it works fine:

```shell
root@my-app-8477997ff5-fbbk9:/opt/jar# curl -I -v http://service.external.com
* Host service.external.com:80 was resolved.
* IPv6: (none)
* IPv4: 80.X.X.171
*   Trying 80.X.X.171:80...
* Connected to service.external.com (80.X.X.171) port 80
> HEAD / HTTP/1.1
> Host: service.external.com
> User-Agent: curl/8.5.0
> Accept: */*
>
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< server: nginx
server: nginx
< date: Fri, 18 Apr 2025 09:19:53 GMT
date: Fri, 18 Apr 2025 09:19:53 GMT
< content-type: text/html
content-type: text/html
< content-length: 200
content-length: 200
< last-modified: Thu, 28 Nov 2024 13:08:44 GMT
last-modified: Thu, 28 Nov 2024 13:08:44 GMT
< etag: "67486b5c-c8"
etag: "67486b5c-c8"
< strict-transport-security: max-age=31536000; includeSubDomains
strict-transport-security: max-age=31536000; includeSubDomains
< x-content-type-options: nosniff
x-content-type-options: nosniff
< x-xss-protection: 1; mode=block
x-xss-protection: 1; mode=block
< accept-ranges: bytes
accept-ranges: bytes
< x-envoy-upstream-service-time: 51
x-envoy-upstream-service-time: 51

<
* Connection #0 to host service.external.com left intact
```

I redeployed Istio in ambient (profile=ambient) with AMBIENT_DNS_CAPTURE=true for the CNI and PILOT_ENABLE_IP_AUTOALLOCATE=true for the pilot.

I switched the namespace in ambient mode and add a waypoint to it

```shell
kubectl label ns my-ns istio-injection-
kubectl label ns my-ns istio.io/dataplane-mode=ambient
istioctl waypoint apply --enroll-namespace --namespace my-ns --wait --name my-waypoint --overwrite --for all
```

I restarted my application and now the call to the external service does not work anymore.

```shell
root@my-app-646c479c66-qbsgr:/opt/jar# curl -I -v http://service.external.com
* Host service.external.com:80 was resolved.
* IPv6: 2001:2::14
* IPv4: 240.240.0.20
*   Trying 240.240.0.20:80...
* Connected to service.external.com (240.240.0.20) port 80
> HEAD / HTTP/1.1
> Host: service.external.com
> User-Agent: curl/8.5.0
> Accept: */*
>
* Empty reply from server
* Closing connection
curl: (52) Empty reply from server
```

In istio waypoint logs, I got this:

```json
{"duration":0,"response_code_details":"filter_chain_not_found","bytes_sent":0,"x_sigsci_request_id":null,"x_sigsci_waf_response":null,"user_agent":null,"route_name":null,"upstream_host":null,"upstream_local_address":null,"x_forwarded_for":null,"downstream_local_address":"240.240.0.20:80","upstream_service_time":null,"response_flags":"NR","requested_server_name":null,"upstream_transport_failure_reason":null,"response_code":0,"request_id":null,"downstream_remote_address":"10.98.143.148:52506","start_time":"2025-04-18T13:57:15.566Z","method":null,"path":null,"connection_termination_details":null,"protocol":null,"upstream_cluster":null,"bytes_received":0,"authority":null}
```

I cannot find what is missing or what must be changed to make it work. Any help would be appreciated.

**Comment by howardjohn** [comment, marked as answer]
@smilingbullet the problem here is your traffic flow is dependant on the client side reading the DestinationRule and sending Istio mTLS. Ztunnel does not implement destination rule.

However, ambient mode comes with a much simpler way to achieve this goal: https://www.solo.io/blog/egress-gateways-made-easy

**Comment by smilingbullet** [comment]
@howardjohn Thank you for your quick reply.

I managed to fix the problem by doing the following:

* delete the previously mentionned gateway, virtualservice and destinationRules.
* updated the serviceEntry by adding the port 80 with targetPort to 443
```yaml
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: my-app-service.external.com
  namespace: my-ns
spec:
  hosts:
  - service.external.com
  location: MESH_EXTERNAL
  ports:
  - name: http
    number: 80
    protocol: HTTP
    targetPort: 443
  - name: tls
    number: 443
    protocol: TLS
  resolution: DNS
status:
  addresses:
  - host: service.external.com
    value: 240.240.0.20
  - host: service.external.com
    value: 2001:2::14
  conditions:
  - lastTransitionTime: "2025-04-18T15:04:23.367177787Z"
    message: Successfully attached to waypoint my-ns/my-app-waypoint
    reason: WaypointAccepted
    status: "True"
    type: istio.io/WaypointBound
```
* created a new DestinationRule
```yaml
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  labels:
    mtls-from-egress: "true"
  name: service.external.com-originate-mtls
  namespace: my-ns
spec:
  host: service.external.com
  trafficPolicy:
    tls:
      credentialName: mtls-client-creds
      mode: MUTUAL
      sni: service.external.com
```
and now the response is OK:
```shell
root@my-app-7cc57568dd-lfqz8:/opt/cbp/jar# curl -I -vvv http://service.external.com
* Host service.external.com:80 was resolved.
* IPv6: 2001:2::14
* IPv4: 240.240.0.20
*   Trying 240.240.0.20:80...
* Connected to service.external.com (240.240.0.20) port 80
> HEAD / HTTP/1.1
> Host: service.external.com
> User-Agent: curl/8.5.0
> Accept: */*
>
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< server: nginx
server: nginx
< date: Fri, 18 Apr 2025 15:04:42 GMT
date: Fri, 18 Apr 2025 15:04:42 GMT
< content-type: text/html
content-type: text/html
< content-length: 200
content-length: 200
< last-modified: Thu, 28 Nov 2024 13:08:44 GMT
last-modified: Thu, 28 Nov 2024 13:08:44 GMT
< etag: "67486b5c-c8"
etag: "67486b5c-c8"
< strict-transport-security: max-age=31536000; includeSubDomains
strict-transport-security: max-age=31536000; includeSubDomains
< x-content-type-options: nosniff
x-content-type-options: nosniff
< x-xss-protection: 1; mode=block
x-xss-protection: 1; mode=block
< accept-ranges: bytes
accept-ranges: bytes
< x-envoy-upstream-service-time: 51
x-envoy-upstream-service-time: 51
< x-envoy-decorator-operation: service.external.com:80/*
x-envoy-decorator-operation: service.external.com:80/*

<
* Connection #0 to host service.external.com left intact
```
