### DISCUSSION TITLE
Does HttpRoute (gateway API) in Istio support path regex match and URL rewrite ?

### DISCUSSION THREAD

**Discussion by porobd** [istio/istio#56045] [General]
We are using istio 1.24.0 (and can upgrade to 1.25.2 if required) in 'ambient' mode. 
One of our requirements is to set up Authorization Policies at the ingress gateway to use token verification (with corresponding RequestAuthentication resource) and a CUSTOM policy to forward certain frontend requests to oauth2-proxy.
But in the ambient mode, it does not allow setting up such policies in the Istio API ingress gateway (networking.istio.io) so we thought we could use the gateway API and setup such policies and it seems to work fine but then we have another requirement where we need to do path regex match and URL rewriting in the HttpRoute (cannot use VirtualService anymore with the gateway API).

But a match like below doesn't seem to work:
```
- matches:
    - path:
        type: RegularExpression
        value: /test/[[:alnum:]]{7,}/path1
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplaceFullPath 
          replaceFullPath: /test/fixed/path1
```

Does HttpRoute not support regex ? Is there a plan to support it in an upcoming release ?

I tried using the idea mentioned in https://github.com/istio/istio/issues/46662 to attach a virtualservice to gateway API but that did not work for me. Any idea how I can get the auto-generated name of the gateway and whether this is supposed to work and is supported while Istio is working on supporting all VirtualService features in HttpRoute ?
