### DISCUSSION TITLE
How configure logging

### DISCUSSION THREAD

**Discussion by BeyondEvil** [istio/istio#56062] [Q&A]
Our log ingestor is getting flooded with logs from Istio, so we're looking to configure all logging to the equivalent of a "warning" and above level.

We're running the following Helm charts:

- istio-istiod
- istio-base
- istio-cni

And we've (tried) to configure logging as follows:

cni values file:
```yaml
global:
  logAsJson: true
  logging:
    level: warn
```

istiod values file:
```yaml
global:
  logAsJson: true
  logging:
    level: 'all:warn'
```

But we're still seeing info-logs from:

- proxyv2
- install-cni
- agent

What are we missing?
