### DISCUSSION TITLE
How to use x-b3-traceid as x-request-id

### DISCUSSION THREAD

**Discussion by kytool** [istio/istio#56098] [General]
How to use x-b3-traceid as x-request-id（response header）
 I want the traceid to be returned to the caller, who can then look up the trace

**Comment by zirain** [comment]
you can use accesslog fromatter in headers: 
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
    - httpbin
  http:
    - route:
        - destination:
            host: httpbin
            port:
              number: 8000
          headers:
            response:
              add:
                test: "%REQ(:authority)%"
```

**Comment by kytool** [comment]
global config
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: add-response-header-traceid
  namespace: istio-system
spec:
  configPatches:
    - applyTo: HTTP_ROUTE
      match:
        context: GATEWAY
        routeConfiguration:
          vhost:
            route:
              action: ANY
      patch:
        operation: MERGE
        value:
          response_headers_to_add:
            - header:
                key: "x-request-id"
                value: "%REQ(x-b3-traceid)%"
              append: false
```
