### DISCUSSION TITLE
Is it possible to use both istio gateway and k8s gateway at the same time?

### DISCUSSION THREAD

**Discussion by gojanpaolo** [istio/istio#56129] [Q&A] [answered]
I'm trying to install both istio gateway and k8s gateway in minikube but can't seem to have both working simultaneously.

I have these resources
```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: default-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      name: http
      number: 80
      protocol: HTTP
    hosts:
      - "product2.com"
```
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-k8s
  namespace: istio-system
spec:
  gatewayClassName: istio
  listeners:
  - name: http-k8s
    hostname: "product1.com"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            product: product1
```

If I only use one of them, it works fine.
I expose using `minikube tunnel` and then have product1.com and product2.com map to 127.0.0.1 in my /etc/hosts
