### DISCUSSION TITLE
multiple destinations in VS - same http/route - fallback mechanism possibility

### DISCUSSION THREAD

**Discussion by feduniakdaniel** [istio/istio#56146] [Q&A]
Dears,

Currently wanting to achieve proper fallback mechanism using my mesh ;

In short ; for the same http/route, a collection of destinations is configured. The first destination item should always be targeted in nominal situation (linked DestinationRule - no outlined external host), while the second destination should be used iff the first has been outlined. 

I'm not sure this is the correct way to implement active fallback mechanism, (see resource below), but I'm told envoy would used the first healthy destination while weight is not set.

Proposed VS resource;

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: myservice
spec:
  hosts:
  - myservice.default.svc.cluster.local
  http:
  - route:
    - destination:
        host: myservice-primary
        subset: primary
    - destination:
        host: myservice-secondary
        subset: backup
```

Per se, I need different destination items - aka separate DR item - one per host to reach (these are external to my mesh, DNS resolved, must be provided with specific headers, have different TLS terminations,...)

Thanks for your advices, 

Kind regards, 

Daniel
