### DISCUSSION TITLE
Gateway resources when using Gateway API

### DISCUSSION THREAD

**Discussion by josemrs** [istio/istio#56150] [Q&A]
Hi,

We are deploying Istio as our ingress and Mesh solution and now we are adjusting resources for the pods.

We deploy istio using our own Helm chart wrapping the original charts, no istioctl or istio operator involved.

Sidecar resources are easy:
```
    proxy:
      # These are the resources for the istio-proxy container,
      # the sidecar proxy injected in the pods in namespaces with istio-injection enabled
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
```

We deploy Internal/Extarnal gateways using the recommended, "future-proof", Gateway resources from Gateway API:

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    proxy.istio.io/config: '{"gatewayTopology" : { "proxyProtocol": {} }}'
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: external
    sidecar.istio.io/proxyCPU: 100m
    sidecar.istio.io/proxyCPULimit: 200m
    sidecar.istio.io/proxyMemory: 128Mi
    sidecar.istio.io/proxyMemoryLimit: 256Mi
  labels:
    app.kubernetes.io/name: external-gateway
    app.kubernetes.io/version: default
    istio: ingressgateway
  name: external-gateway
  namespace: istio-system
spec:
  gatewayClassName: istio
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: http
    port: 80
    protocol: HTTP
  - allowedRoutes:
      namespaces:
        from: All
    name: https
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: istio-wildcard-tls
      mode: Terminate
```

As we understand the sidecar may be "tiny" while the gateway pods need to be bigger.

At first I thought `sidecar.istio.io/proxy*`annotations would do the trick but I understand now, it's the other way around, those are to fine tune proxy sidecar in an individual deployment. The pods deployed for the gateway follow the values:

```
    Limits:
      cpu:     500m
      memory:  512Mi
    Requests:
      cpu:      100m
      memory:   128Mi
```

Is there a way for selecting the gateway memory/CPU resources using Gateway API gateway?

Thanks a lot.
