### DISCUSSION TITLE
dowstream HTTP Connection metric

### DISCUSSION THREAD

**Discussion by stromnet** [istio/istio#56163] [Q&A] [answered]
Hi,
I'm trying to determine how many incoming connections our ingress pods have relative to the number of requests made (i.e. how well are downstream connections re-used) in order to design some suitable load-tests. But, I cannot really find a good prometheus metric for it? For number of requests, we have in `istio_requests_total` but I would like to know number of accepted  downstream TCP connections as well.
If it be accomplished with some envoy filter, I'd appreciate any hints in the right direction.

Thanks!

**Comment by rsalmond** [comment]
Can you subtract `istio_tcp_connections_closed_total` from `istio_tcp_connections_opened_total` for that?

**Reply by stromnet** [reply]
I believe those are for upstream TCP connections only (they are 0 for upstream HTTP connections iirc, dont have numbers at hand atm).

While number of upstream HTTP connections (`connect()`) would also be interesting to know as well, I'm interested in downstream connections (i.e. `acccep()`ed incoming to my istio ingress).

**Reply by rsalmond** [reply, marked as answer]
Ahh I see in that case I believe what you want is the envoy `downstream_cx_active` metric which is disabled by default. See [this doc](https://istio.io/latest/docs/ops/configuration/telemetry/envoy-stats/) to enable it.

**Reply by stromnet** [reply]
Thank you very much!
Ended up annotating our ingress pods like this, and I can now see newly accepted connections and also connections kept (and a bunch of other interesting stuff), hopefully without choking our prometheus too much
```
    proxy.istio.io/config: |
      proxyStatsMatcher:
        inclusionRegexps:
          - ".*outbound.*downstream_cx.*total"
          - ".*outbound.*downstream_cx.*active"
          - ".*outbound.*downstream_cx_destroy_remote"
          - ".*outbound.*downstream_cx_destroy_local"
          - ".*outbound.*downstream_cx_http1_soft_drain"
          - ".*outbound.*downstream_cx_drain_close"
          - ".*outbound.*downstream_cx_.*_bytes_buffered"
          - ".*outbound.*downstream_cx_idle_timeout"
          - ".*outbound.*downstream_cx_max_duration_reached"
          - ".*outbound.*downstream_cx_max_requests_reached"
          - ".*outbound.*downstream_cx_overload_disable_keepalive"
          - ".*outbound.*downstream_rq.*total"
          - ".*outbound.*downstream_rq_.*_reset"
          - ".*outbound.*downstream_rq_too_large"
          - ".*outbound.*downstream_rq_.*timeout"
          - ".*outbound.*downstream_rq_overload_close"
```
based on [this list of metrics](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/stats)
