### DISCUSSION TITLE
Traffic to an external cluster with certificate signed by company PKI

### DISCUSSION THREAD

**Discussion by Max-LAB** [istio/istio#56196] [Q&A] [answered]
I have one problem trying to solve, and with my limited Istio knowledge I need someone to point me into right direction.

Inside a company we have multiple clusters K8S setup. Communication between the clusters is possible only through an internal DNS server.

Istio is deployed on all clusters, and TLS termination is handled at the gateway level using internally signed certificates (I do not have access to the private key). Configuration below.

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ingressgateway
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    hostname: "*.keycloak.xyz.com"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  - name: https
    hostname: "*.keycloak.xyz.com"
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - name: keycloak.xyz.com-tls # internaly signed certificate
    allowedRoutes:
      namespaces:
        from: All
```

**Problem:**

On `Cluster-A`, we have Keycloak deployed, and it is accessed by applications in `Cluster-B` via the domain `*.keycloak.xyz.com`. 

To enable communication from`Cluster-B` to Keycloaks`Cluster-A`, I manually add the `keycloak.xyz.com.crt` (signed by internal PKI) into the /etc/ssl/certs folder inside the application’s Docker image. After doing so, I can successfully use curl to reach the Keycloak service from within the application pod.

Problem is that this setup is not scalable. There will be multiple applications across different clusters, all needing access to Keycloak via  `*.keycloak.xyz.com`.

I need a way to automatically distribute the`keycloak.xyz.com.crt` certificate to all pods in the clusters that are communicating via Istio, without having to manually import the certificate into each application’s container. The ideal solution would allow Istio (via the Envoy proxy) to manage and distribute this certificate to all relevant pods across clusters.

I am aware that Istio manages certificates for mutual TLS (mTLS) but am unsure of how to integrate and distribute custom certificates like `keycloak.xyz.com.crt` to all the application pods using Envoy proxies in a multi-cluster setup.

Any insights or guidance on how to solve this would be greatly appreciated!

**Comment by rsalmond** [comment]
I believe you can achieve this by creating a ServiceEntry for `*.keycloak.xyz.com`, putting your CA cert into a K8s secret, and then cerating a DestinationRule with a `credentialName` field which references the secret.

https://istio.io/latest/docs/reference/config/networking/destination-rule/#ClientTLSSettings-credential_name

**Reply by Max-LAB** [reply]
Hi all. @rsalmond thanks for the tip! Ok, I still cannot get a desired result, after I apply `ServiceEntry` and after that `DestinationRue` I still cannot do a curl request in my pod.

Here are my `ServiceEntry` and `DestinationRule` definitions which are deployed to `istio-system` namespace 

```yml
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: external-keycloak-https
spec:
  hosts:
  - "keycloak.xyz.com"
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
```

```yml
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: keycloak-mtls
spec:
  host: keycloak.xyz.com
  # workloadSelector:
  #   matchLabels:
  #     app: testapp
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 443
      tls:
        #clientCertificate: /etc/ssl/certs/kc-cert.pem
        #privateKey: /etc/ssl/certs/client-key.pem
        #caCertificates: /etc/certs/ca-cert.pem
        credentialName: keycloak-certs  # Refers to the Kubernetes Secret
        mode: MUTUAL
````

Here is how my `keycloak-certs` secret looks like, and it is deployed to `istio-ingress` namespace.

```yml
kubectl create secret generic keycloak-certs \
  --namespace=istio-ingress \
  --from-file=ca.crt=keycloak_cert/keycloak.xyz.com.crt
```


After I deplyoy secret I receive this warning inside `istiod` logs

``` 
proxy ingressgateway-istio-966d5b8ff-rd2qz.istio-ingress attempted to access unauthorized certificates keycloak-certs: ingressgateway-istio/istio-ingress is not authorized to read secrets
``` 

After I apply all of this, I exec pod which has an envoy-proxy atached and I try to do curl request but still I get sam error

```sh
k exec -it testapp-584fcc8888-2t525 -- sh
```

```
curl -sSiv "https://keycloak.xyz.com"

*   Trying 100.10.4.52:443...
* Connected to keycloak.xyz.com (100.10.4.52) port 443 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

On which step I am making mistake? How can I debug this to see what is the problem? Can this warning in istiod can be the case?

**Reply by rsalmond** [reply]
> ingressgateway-istio/istio-ingress is not authorized to read secrets

You've debugged it. That's the problem. The service account that the ingress gateway operates under needs access to read secrets.

**Reply by Max-LAB** [reply]
@rsalmond thanks again, this was a problem!! :) Now I have another question. To see "something" that is working I moved the `ServiceEntry` and `DestinationRule` to the namespace where application is deployed. After that I added a Role and RoleBinding so that secret can be accessed.

```yml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-secrets
  namespace: app-test
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    #resourceNames: ["keycloak-certs-tls"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-test-read-secrets
  namespace: app-test
subjects:
  - kind: ServiceAccount
    name: default
    namespace: app-test
roleRef:
  kind: Role
  name: read-secrets
  apiGroup: rbac.authorization.k8s.io
```
I checked it if secret can be accessed and I received `yes`

```sh
kubectl auth can-i get secrets/keycloak-certs-tls --as=system:serviceaccount:app-test:default --namespace=app-test
```

Now when I do a curl request I receive a different error

```sh
*   Trying 100.10.4.52:443...
* Connected to keycloak.xyz.com (100.10.4.52) port 443 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* Recv failure: Connection reset by peer
* OpenSSL SSL_connect: Connection reset by peer in connection to keycloak.xyz.com:443 
* Closing connection 0
curl: (35) Recv failure: Connection reset by peer
```

At least some progress. Now I think I have a problem with certificates. Qustion is where can I see inside envoy-proxy or pod itself certificates from secret I provided inside `DestinationRule`?

Also I am a littel bit confused by `credentialName` definition https://istio.io/latest/docs/reference/config/networking/destination-rule/#ClientTLSSettings-credential_name inside `DestinationRule`. What in my case will bi `key`, `cert` and `cacert` it I want to access from Cluster-B (where application is and where I am testing everything) to Cluster-A where Keycloak is deployed.

**Reply by rsalmond** [reply]
> Recv failure: Connection reset by peer

This looks like what happens when you have mTLS set to STRICT mode and you make a non-mTLS connection to a pod in the mesh.

To see the secrets in use by a proxy run `istioctl pc secret <name of pod goes here> -n <namespace of pod>`.

`credentialName` supports several use cases which is why you can put a key and a cert in there as well as a cacert, but for your use case you should only need the cacert. Try adjusting the key in your secret from `ca.crt` to `cacert`.

**Reply by Max-LAB** [reply]
Hi @rsalmond thank you again for reaching out. I am still on this problem and it is driving me crazy. I create da new secret as you said.

```sh
kubectl create secret generic robs-secret-2 \
  --namespace=app-test \
  --from-file=cacert=keycloak_cert/keycloak.xyz.com.crt
```

and when I do 
```sh
istioctl pc secret app-test-77b884ccf8-tpzzn -n app-test

RESOURCE NAME                         TYPE           STATUS     VALID CERT     SERIAL NUMBER                              NOT AFTER                NOT BEFORE
kubernetes://robs-secret-2-cacert     Cert Chain     ACTIVE     true           120002b13825027f5e0efdbc7b00000005a193     2027-03-17T09:10:11Z     2025-03-17T09:10:11Z
``` 
I also disabled mTls by using PeerAuthentication

```yml
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
  namespace: "istio-system"
spec:
  mtls:
    mode: DISABLE
```

but still I am receiving same error :(

```sh
...
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: Connection reset by peer in connection to keycloak.xyz.com:443 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to keycloak.xyz.com:443
```

**Reply by rsalmond** [reply]
Just to clarify, if you do `curl --cacert <your ca file here> https://keycloak.xyz.com` from outside the mesh this works?

Can you add `-vvv` to your curl command and share the whole command as well as the output? Also can you double check that the hostname in the service entry and destination rule matches? If they don't match the rule won't be applied.

**Reply by Max-LAB** [reply]
When I test curl from my PC

```sh
curl -sSiv --cacert keycloak_cert/keycloak.xyz.com.crt https://keycloak.xyz.com 

```

<details><summary>Curl output</summary>
<p>

```sh

* Uses proxy env variable no_proxy == 'localhost,xyz.com'
* Host keycloak.xyz.com:443 was resolved.
* IPv6: (none)
* IPv4: 100.10.4.52
*   Trying 100.10.4.52:443...
* Connected to keycloak.xyz.com (100.10.4.52) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: keycloak_cert/keycloak.xyz.com.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / X25519 / RSASSA-PSS
* ALPN: server accepted h2
* Server certificate:
*  subject: O=XYZ; OU=NY; OU=Cloud; CN=*.keycloak.xyz.com; emailAddress=Cloud@xyz.com
*  start date: Mar 17 09:10:11 2025 GMT
*  expire date: Mar 17 09:10:11 2027 GMT
*  subjectAltName: host "keycloak.xyz.com" matched cert's "*.keycloak.xyz.com"
*  issuer: C=US; O=IT XYZ; CN=XYZ-SubCA03-2025
*  SSL certificate verify ok.
*   Certificate level 0: Public key type RSA (4096/152 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 1: Public key type RSA (4096/152 Bits/secBits), signed using sha256WithRSAEncryption
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://keycloak.xyz.com/
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: keycloak.xyz.com]
* [HTTP/2] [1] [:path: /]
* [HTTP/2] [1] [user-agent: curl/8.5.0]
* [HTTP/2] [1] [accept: */*]
> GET / HTTP/2
> Host: keycloak.xyz.com
> User-Agent: curl/8.5.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 302 
HTTP/2 302 
< location: https://keycloak.xyz.com/admin/
location: https://keycloak.xyz.com/admin/
< referrer-policy: no-referrer
referrer-policy: no-referrer
< strict-transport-security: max-age=31536000; includeSubDomains
strict-transport-security: max-age=31536000; includeSubDomains
< x-content-type-options: nosniff
x-content-type-options: nosniff
< x-xss-protection: 1; mode=block
x-xss-protection: 1; mode=block
< content-length: 0
content-length: 0
< x-envoy-upstream-service-time: 4
x-envoy-upstream-service-time: 4
< date: Mon, 12 May 2025 19:26:41 GMT
date: Mon, 12 May 2025 19:26:41 GMT
< server: istio-envoy
server: istio-envoy

< 
* Connection #0 to host keycloak.xyz.com left intact
```

</p>
</details> 

After that I did a copy of my `keycloak_cert/keycloak.xyz.com.crt` into my `test-app`  pod and did a two tests. 

```sh
k cp keycloak_cert/keycloak.xyz.com.crt $POD_NAME:/usr/local/share/ca-certificates/keycloak.xyz.com.crt
```

1. Test inside `test-app`  pod - With `ServiceEntry` and `DestiantionRule` applied in namespace where `test-app` is deployed

```sh
# test with certificate
bash-5.1# curl -sSiv --cacert /usr/local/share/ca-certificates/keycloak.xyz.com.crt https://keycloak.xyz.com

#test withhout certificate (desired way)
bash-5.1# curl -sSiv https://keycloak.xyz.com

# same results down in Curl output
```

<details><summary>Curl output</summary>
<p>

```sh
*   Trying 100.10.4.52:443...
* Connected to keycloak.xyz.com (100.10.4.52) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /usr/local/share/ca-certificates/keycloak.xyz.com.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: Connection reset by peer in connection to keycloak.xyz.com:443 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to keycloak.xyz.com:443
```

</p>
</details> 

2. Test inside `test-app`  pod - Without `ServiceEntry` and `DestiantionRule` applied in namespace where `test-app` is deployed

```sh
bash-5.1# curl -sSiv --cacert /usr/local/share/ca-certificates/keycloak.xyz.com.crt https://keycloak.xyz.com
```

<details><summary>Curl output</summary>
<p>

```sh
   Trying 100.10.4.52:443...
* Connected to keycloak.xyz.com (100.10.4.52) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /usr/local/share/ca-certificates/keycloak.xyz.com.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: O=XYZ; OU=NY; OU=Cloud; CN=*.keycloak.xyz.com; emailAddress=Cloud@xyz.com
*  start date: Mar 17 09:10:11 2025 GMT
*  expire date: Mar 17 09:10:11 2027 GMT
*  subjectAltName: host "keycloak.xyz.com" matched cert's "*.keycloak.xyz.com"
*  issuer: C=US; O=IT XYZ; CN=XYZ-SubCA03-2025
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f82031e7a90)
> GET / HTTP/2
> Host: keycloak.xyz.com
> user-agent: curl/7.79.1
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 2147483647)!
< HTTP/2 302 
HTTP/2 302 
< location: https://keycloak.xyz.com/admin/
location: https://keycloak.xyz.com/admin/
< referrer-policy: no-referrer
referrer-policy: no-referrer
< strict-transport-security: max-age=31536000; includeSubDomains
strict-transport-security: max-age=31536000; includeSubDomains
< x-content-type-options: nosniff
x-content-type-options: nosniff
< x-xss-protection: 1; mode=block
x-xss-protection: 1; mode=block
< content-length: 0
content-length: 0
< x-envoy-upstream-service-time: 6
x-envoy-upstream-service-time: 6
< date: Mon, 12 May 2025 19:44:17 GMT
date: Mon, 12 May 2025 19:44:17 GMT
< server: istio-envoy
server: istio-envoy

< 
* Connection #0 to host keycloak.xyz.com left intact
```

</p>
</details>

**Reply by Max-LAB** [reply]
Hi @rsalmond , here is another progress. When I add `-vvv` to my curl command then in `istio-proxy` I can see meaningful error

```sh
bash-5.1# curl -vvv "https://keycloak.xyz.com"

# Error
# [2025-05-12T20:30:37.005Z] "- - -" 0 UF,URX - - "TLS_error:|268435581:SSL_routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED:TLS_error_end" 0 0 51 - "-" "-" "-" "-" "100.10.4.52:443" outbound|443||keycloak.xyz.com - 100.10.4.52:443 100.64.1.66:42390 keycloak.xyz.com -
``` 

This happens when I apply `DestinationRule` with tls mode `ISTIO_MUTUAL`

```yml
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: keycloak-mtls
spec:
  host: "keycloak.xyz.com"
  workloadSelector:
     matchLabels:
       app: testapp
  trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
        - port:
            number: 443
          tls:
            credentialName: robs-secret-2 # Refers to the Kubernetes Secret
            mode: ISTIO_MUTUAL
```

When mode is just `MUTUAL`, then I receive this error

```sh

# Error
#  [2025-05-12T20:37:46.123Z] "- - -" 0 UF,URX - - "TLS_error:_Secret_is_not_supplied_by_SDS" 0 0 22 - "-" "-" "-" "-" "100.10.4.52:443" outbound|443||keycloak.xyz.com - 100.10.4.52:443 100.64.1.66:45780 keycloak.xyz.com - 
```

**Reply by rsalmond** [reply]
Why is the mode any kind of mutual? You're not using client certificates right? It should be SIMPLE I think.

**Reply by Max-LAB** [reply]
Point is just to get a connection with external server without explicitly providing --cacert, cert should be there. When I do SIMPLE and -vvv in curl request I get only this inside `istio-proxy`

```sh
# [2025-05-13T07:24:54.699Z] "- - -" 0 UF,URX - - "-" 0 0 27 - "-" "-" "-" "-" "100.10.4.52:443" outbound|443||keycloak.xyz.com - 100.10.4.52:443 100.64.1.66:37364 keycloak.xyz.com -
```

**Reply by Max-LAB** [reply]
Ok here is the latest status. I cleaned up `ServiceEntry` and also `DestinationRule` definition.

```yml
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: external-keycloak-https
spec:
  hosts:
  - keycloak.xyz.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
```

```yml
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: keycloak-tls
spec:
  host: keycloak.xyz.com
  exportTo: ["."]
  workloadSelector:
     matchLabels:
       app: testapp
  # trafficPolicy:
  #     loadBalancer:
  #       simple: ROUND_ROBIN
  #     portLevelSettings:
  #       - port:
  #           number: 443
  #         tls:
  #           #clientCertificate: /etc/ssl/certs/kc-cert.pem
  #           #privateKey: /etc/ssl/certs/client-key.pem
  #           #caCertificates: /etc/certs/ca-cert.pem
  #           #credentialName: robs-secret 
  #           credentialName: monc-certs-all-in-one
  #           mode: SIMPLE
  trafficPolicy:
    tls:
      mode: SIMPLE
      caCertificates: subca-cacert
```

then when I do `istioctl pc s <pod-name> -n <namespace>` I receive for my certificate `Status: WARMING`  and `CERT: false`

```
istioctl pc secret testapp-deployment-77b884ccf8-z4fvh -n tooling

RESOURCE NAME                  TYPE           STATUS      VALID CERT     SERIAL NUMBER                        NOT AFTER                NOT BEFORE
file-root:subca-cacert                    WARMING     false                                                                        
default                        Cert Chain     ACTIVE      true           db9c0269cb2809d92e39e91eddeb2809     2025-05-14T11:14:06Z     2025-05-13T11:12:06Z
ROOTCA                         CA             ACTIVE      true           bde0a7308f9cc31c32fc7fcde9d0a730     2035-04-13T09:07:18Z     2025-04-15T09:07:18Z
```
In `istio-proxy` I receive this

```sh
# [2025-05-13T11:32:02.707Z] "- - -" 0 UF,URX - - "TLS_error:_Secret_is_not_supplied_by_SDS" 0 0 22 - "-" "-" "-" "-" "100.10.4.52:443" outbound|443||keycloak.xyz.com - 100.10.4.52:443 100.64.0.54:39838 keycloak.xyz.com -

# error    cache    resource:file-root:subca-cacert failed to generate secret for proxy from file: context deadline exceeded with last error: open subca-cacert: no such file or directory    
```

Secret used inside `DestinationRule` is created like this

```sh
kubectl create -n tooling secret generic subca-cacert \
  --from-file=ca.crt=keycloak_cert/keycloak.xyz.com.crt
```

Do I need to change `tls-terminate-mode` inside istio gateway to `SIMPLE`? I have deployed my gateway with tls mode Terminate but I did not specify any option, like so

```yml
    tls:
      mode: Terminate
      certificateRefs:
      - name: test.cluster-tls
      #options:
        #gateway.istio.io/tls-terminate-mode: MUTUAL
```

**Reply by rsalmond** [reply]
As far as I can tell you are not doing mutual TLS. You want SIMPLE, not MUTUAL or ISTIO_MUTUAL. And I believe the cert is stuck in warming status because the secret is created with the key `ca.crt` instead of `cacert`.

**Reply by Max-LAB** [reply]
> As far as I can tell you are not doing mutual TLS. You want SIMPLE, not MUTUAL or ISTIO_MUTUAL.

You are right, just SIMPLE, and with `curl -v --cacert ...` I confirmed that my server also requres only cacert. 

I am losing it slowly :( , I made a mistake up there in my `DestinationRule` file, instead of using `caCertificates` as a path I should be using `credentialName` 

```yml
  trafficPolicy:
    tls:
      mode: SIMPLE
      credentialName: subca-cacert # NOT caCertificates: subca-cacert
```
With this change and `istioctl pc secret ... ` I am getting `STATUS: ACTIVE`  and `VALID CERT: true`. Now I am on the beggining and becomming desparate. Dont know where to look next. In istio-proxy I only get

```yml
# [2025-05-13T12:29:25.948Z] "- - -" 0 UF,URX - - "-" 0 0 27 - "-" "-" "-" "-" "100.10.4.52:443" outbound|443||keycloak.xyz.com - 100.10.4.52:443 100.64.1.66:37364 keycloak.xyz.com -
```

and after curl request

```yml
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: Connection reset by peer in connection to keycloak.xyz.com:443 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to keycloak.xyz.com:443 
```

I also have access to a second cluster where keycloak is deployed, can I change/look/do something in there that could help?

**Reply by Max-LAB** [reply]
Hi @rsalmond I "think" I had some progress in here. It seams that my Load Balancer is filtering SNI's. So when I made this change in `DestinationRule` I receive another error message. 

DestinationRule

```yml
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: keycloak-tls
spec:
  host: keycloak.xyz.com
  workloadSelector:
     matchLabels:
       app: testapp
  trafficPolicy:
      tls:
        credentialName: subca-cacert
        mode: SIMPLE
        sni: keycloak.xyz.com
```

ServiceEntry

```yml
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: external-keycloak-https
spec:
  hosts:
  - keycloak.xyz.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: kc-https
    protocol: TLS
  - number: 80
    name: kc-http
    protocol: HTTP
  resolution: DNS
```

Now when I do a curl request, i get this error:

```sh
# Cluster B - test-app pod
# curl -vL https://keycloak.xyz.com

* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number
* Closing connection 0
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number

# istio-proxy log

[2025-05-14T13:04:49.887Z] "- - -" 0 - - - "-" 517 162 36 - "-" "-" "-" "-" "100.10.4.52:443" outbound|443||keycloak.xyz.com 100.64.0.79:53110 100.10.4.52:443 100.64.0.79:53098keycloak.xyz.com - 
```

I also enabled a debug inside keyckloak cluster istio instannce and there in istio-ingress pod I receive:

```yml
# Cluster A - ingress

[2025-05-14T12:34:35.415Z] "- - HTTP/1.1" 400 DPE http1.codec_error - "-" 0 11 0 - "-" "-" "-" "-" "-" - - 100.64.0.39:443 100.64.2.1:17821 keycloak.xyz.com - 
```

Here are some additional infos:

```sh
istioctl proxy-config cluster -n istio-ingress ingressgateway-istio-855845668f-sg4h9.istio-ingress

SERVICE FQDN                                              PORT      SUBSET     DIRECTION     TYPE           DESTINATION RULE
BlackHoleCluster                                          -         -          -             STATIC         
agent                                                     -         -          -             STATIC         
          
keycloak.xyz.com                                         80        -          outbound      STRICT_DNS     
keycloak.xyz.com                                         443       -          outbound      STRICT_DNS     
          
prometheus_stats                                          -         -          -             STATIC         
sds-grpc                                                  -         -          -             STATIC         
xds-grpc                                                  -         -          -             STATIC
```

```sh
istioctl pc listeners deploy/testapp-deployment

ADDRESSES      PORT  MATCH                                                               DESTINATION

0.0.0.0        80    Trans: raw_buffer; App: http/1.1,h2c                                Route: 80
0.0.0.0        80    ALL                                                                 PassthroughCluster

0.0.0.0        443   ALL                                                                 PassthroughCluster
0.0.0.0        443   SNI: keycloak.xyz.com                                              Cluster: outbound|443||keycloak.xyz.com
````

```sh
stioctl pc secret testapp-deployment-77b884ccf8-km7qs -n tooling
RESOURCE NAME                            TYPE           STATUS     VALID CERT     SERIAL NUMBER                              NOT AFTER                NOT BEFORE
default                                  Cert Chain     ACTIVE     true           a77969cbb7a13568fee45461336fa135           2025-05-15T11:40:11Z     2025-05-14T11:38:11Z
kubernetes://subca-cacert     CA             ACTIVE     true           7c00000002f0486563486dd250000000000002     2031-03-28T09:23:08Z     2023-07-19T09:30:12Z
ROOTCA                                   CA             ACTIVE     true           b6664f536ba8759f3a7819d0a2ce64f5           2035-05-11T21:36:48Z     2025-05-13T21:36:48Z

```

Additionaly, now when I try to do `curl -vL --cacert ...`  with valide cert inside pod after `DestinationRule` and `ServiceEntry` apply, it wont work.
