### DISCUSSION TITLE
Helm chart value in istio-cni to enable ambient mode

### DISCUSSION THREAD

**Discussion by danielrive** [istio/istio#56205] [Q&A]
Hello, 

I am installing Istio-CNI using the helm chart, I saw the following:

```YAML
 # Configure ambient settings
  ambient:
    # If enabled, ambient redirection will be enabled
    enabled: false
    # If ambient is enabled, this selector will be used to identify the ambient-enabled pods
    enablementSelectors: 
    - podSelector:
        matchLabels: {istio.io/dataplane-mode: ambient}
```

I added the label **istio.io/dataplane-mode: ambient** to my pod, which added to the mesh. Is it also necessary to enable ambient mode in the Istio-CNI values?

Thanks
