### DISCUSSION TITLE
How can I rate limit traffic to external resource?

### DISCUSSION THREAD

**Discussion by vsfomin** [istio/istio#56202] [Q&A]
I  need to limit rps to some resource external to the K8S cluster. For instance, google.com
Is it necessary to use egress gateway for this or not? 

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google.com
  namespace: my-ns
spec:
  hosts:
    - google.com
  ports:
    - name: tls
      number: 443
      protocol: TLS
  resolution: DNS
```

What additional manifests need I create for this task?

I tried doing this, but it didn't work:
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: google-com-test
  namespace: my-ns
spec:
  host: google.com
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 10
      http:
        maxRequestsPerConnection: 1
```
