### DISCUSSION TITLE
X-Forwarded-Client-Cert does not have peer client certificate

### DISCUSSION THREAD

**Discussion by kaedwen** [istio/istio#56231] [Q&A]
Hi,

we did have ext_authz working with http with an EnvoyFilter. Now I try to migrate to the `AuthorizationPolicy` but for some reason the client cert is not injected correctly anymore.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio
  namespace: istio-system
data:
  mesh: |-
    extensionProviders:
    - name: "cbc-auth-proxy-ext-authz-grpc"
      envoyExtAuthzGrpc:
        service: "cbc-auth-proxy.cbc-system.svc.cluster.local"
        port: "3001"
    - name: "cbc-auth-proxy-ext-authz-http"
      envoyExtAuthzHttp:
        service: "cbc-auth-proxy.cbc-system.svc.cluster.local"
        port: "3000"
        pathPrefix: /check
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      gatewayTopology:
        forwardClientCertDetails: SANITIZE_SET
      proxyHeaders:
        forwardedClientCert: SANITIZE_SET
...
```

```
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: cbc-auth-proxy
  namespace: istio-system
spec:
  action: CUSTOM
  provider:
    name: cbc-auth-proxy-ext-authz-http
  rules:
  - to:
    - operation:
        hosts:
        - '*.<redacted>'
  selector:
    matchLabels:
      app: istio-ingress
      istio: ingress
```

For some reason the client cert is not injected in `X-Forwarded-Client-Cert` anymore.
```
X-Forwarded-Client-Cert: By=spiffe://cluster.local/ns/cbc-system/sa/cbc-auth-proxy;Hash=e234ae8ad37533192912bf2d9738743d4d3bcdbfe3f60f600db2f6bbc63ac8f5;Subject=\"\";URI=spiffe://cluster.local/ns/istio-system/sa/istio-ingress
```

This breaks our mtls ext_authz check and I have no idea what to configure. I have read that XFCC is only injected on Gateway level, not sure what this means. It was working before were we have written the EnvoyFilter directly.

And the weird thing is, when using GRPC the correct client cert is in `X-Forwarded-Client-Cert` ... so it behaves differently for http and grpc

With grpc we do have another issue where multi header values are not handled correctly to the upstream.

Changing to `SANITIZE` does prevent the header to be in grpc too, so this seems to work.
```
      gatewayTopology:
        forwardClientCertDetails: SANITIZE
```

If I do use an `EnvoyFilter` directly like before, the http ext-authz call does have the cert in
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: cbc-auth-proxy-ext-authz
  namespace: istio-system
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
          sni: '*.<redacted>'
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.ext_authz
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
          http_service:
...
            path_prefix: /check
            server_uri:
              cluster: outbound|3000||cbc-auth-proxy.cbc-system.svc.cluster.local
              timeout: 1.5s
              uri: http://cbc-auth-proxy.cbc-system.svc.cluster.local:3000
  workloadSelector:
    labels:
      app: istio-ingress
      istio: ingress
```

If I do understand this correct the XFCC should be controlled directly by this settings
https://istio.io/latest/docs/ops/configuration/traffic-management/network-topologies/#configuring-x-forwarded-client-cert-headers

Any ideas?
