### DISCUSSION TITLE
Virtual services with failover and retry/timeout policies not working as expected

### DISCUSSION THREAD

**Discussion by TanYuzhen** [istio/istio#56262] [Q&A]
The official doc said that Virtual services with failover and retry/timeout policies not working as expected
(https://istio.io/latest/docs/ops/common-problems/network-issues/#virtual-service-with-fault-injection-and-retrytimeout-policies-not-working-as-expected)
So, according to the doc, I use the envoy filter to inject abort fault.
The envoy filter is shown below:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ef-abort-inject-filter
spec:
  workloadSelector:
    labels:
      app: cartservice
      version: v1
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.fault
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.fault.v3.HTTPFault"
          abort:
            http_status: 500
            percentage:
              numerator: 100
              denominator: HUNDRED
          headers:
            - name: tracestate
              exact_match: "fault=1"
```
And I use the MicroService Demo: Online Boutique(https://github.com/GoogleCloudPlatform/microservices-demo)
And I send a request to the frontend 
``` bash
curl -v -H "traceparent: 00-4bf92f3577b34da6a3ce929d0e0e4749-00f067aa0ba902b7-01" -H "tracestate: fault=1" http://192.168.31.169:32448/
```
![image](https://github.com/user-attachments/assets/833e56c6-ecb5-4919-9d5a-d2c59c880a6a)

It shows that the envoy filter injects the abort fault successfully.

And next, I want to use the Virtual Service of Retry in Istio to make the fault don't occur, and this is my retry-virtualservice.yaml
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: cartservice
  namespace: online-trace
spec:
  hosts:
    - cartservice
  http:
    - retries:
        attempts: 3
        perTryTimeout: 2s
        retryOn: 5xx
      route:
        - destination:
            host: cartservice
            subset: v1
```
And I see the logs of cartservice-v1's istio-proxy, it seems that retry doesn't happen!
```bash
kubectl logs cartservice-v1-7d5fd85bcb-rdpbd -n online-trace -c istio-proxy -f
```
![image](https://github.com/user-attachments/assets/2dd90c3a-cf8d-4f2c-aeb3-656af588bf88)
Is there anyone have the same problem?

**Comment by zirain** [comment]
grpc always return 200, maybe you should try with http.

**Reply by TanYuzhen** [reply]
However, I inject abort on frontend service which can return the 5xx error code when inject abort fault as below:
```bash
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: abort-inject
spec:
  workloadSelector:
    labels:
      app: frontend
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.fault
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.fault.v3.HTTPFault"
          abort:
            http_status: 500
            percentage:
              numerator: 100
              denominator: HUNDRED
          headers:
            - name: tracestate
              exact_match: "fault=1"
```
And the retry VirtualService Yaml file is below:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend
spec:
  hosts:
    - "*"
  gateways:
  - frontend-gateway
  http:
  - retries:
      attempts: 5
      retryOn: 5xx
    route:
    - destination:
        host: frontend
```
And the frontend can return the HTTP error status code 500. Anyway, it doesn't still retry on the error.
This is the injected abort error on frontend service:
![image](https://github.com/user-attachments/assets/38176493-9481-4610-8cd7-638f57a629cf)
This is the logs of frontend pod's istio proxy:
![image](https://github.com/user-attachments/assets/fb1d36ed-e9f8-4754-9802-43a75cf275e0)

Why it still hasn't worked?

**Reply by rsalmond** [reply]
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend
spec:
  hosts:
    - "*"
  gateways:
  - frontend-gateway
  http:
  - retries:
      attempts: 5
      retryOn: 5xx
    route:
    - destination:
        host: frontend
```

This virtualservice is enabling the retry on the ingress-gateway but the curl commands appear be going through a proxy. Are you connecting directly to the ingress-gateway service? If not, you will not see retries happening.
