### DISCUSSION TITLE
Prometheus metrics not working in Ambient mode

### DISCUSSION THREAD

**Discussion by anumalasri** [istio/istio#56274] [General]
We are trying to deploy Kiali and Prometheus in Istio Ambient Mode, where Kiali is not showing any graphs. When analyzed, it looks like prometheus does not updated with Metrics. 

Istio `v1.25.2` installed with `STRICT` peer authentication.  Kiali-server and minimal prometheus deployed into `istio-system` namespace.

Has following Istio config:
```
    defaultProviders:
      metrics:
      - prometheus
    enableAutoMtls: true
    enablePrometheusMerge: true
```

```
kubectl get svc -n istio-system
NAME         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                  
istiod       ClusterIP   172.17.212.248   <none>        15010/TCP,15012/TCP,443/TCP,15014/TCP    
kiali        ClusterIP   172.17.239.173   <none>        20001/TCP,9090/TCP                      
prometheus   ClusterIP   172.17.237.143   <none>        9090/TCP                               
```
Also disbaled `TLS` for Kiali and prometheus

```
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: kiali
  namespace: istio-system
spec:
  host: kiali
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: prometheus
  namespace: istio-system
spec:
  host: prometheus
  trafficPolicy:
    tls:
      mode: DISABLE
```

Everything works fine, expect graphs in Kiali.  Unable to find any error logs for prometheus scraping. 

Kiali has following annotations for prometheus scraping
```
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
```
where are other istio components has different port#
```
        prometheus.io/port: "15014"
        prometheus.io/scrape: "true"
```

Appreciate any help to troubleshoot this issue in above mentioned configuration.

**Comment by anumalasri** [comment]
@howardjohn  @keithmattix  Appreciate any help to troubleshoot prometheus metrics issue.

I could verify that metrics are available from Pod.

```
% k exec -it -n istio-system kiali-7f4f9d4dfd-l8jvg  -- curl http://localhost:9090/metrics
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 2.8154e-05
go_gc_duration_seconds{quantile="0.25"} 3.6042e-05
go_gc_duration_seconds{quantile="0.5"} 4.7621e-05
go_gc_duration_seconds{quantile="0.75"} 7.1068e-05
go_gc_duration_seconds{quantile="1"} 0.005090019
go_gc_duration_seconds_sum 0.339044216
go_gc_duration_seconds_count 4042
....
```

I could see these policies in ztunnel .  Are they causing any failure for scraping ? 
```
% istioctl zc policy -o yaml
- action: Deny
  name: istio_converted_static_strict
  namespace: istio-system
  rules:
  - - - notPrincipals:
        - Presence: []
  scope: WorkloadSelector
- action: Allow
  name: kiali-auth-policy
  namespace: istio-system
  rules:
  - - - principals:
        - Exact: cluster.local/ns/istio-ingress/sa/ingress-gateway-istio
  scope: WorkloadSelector
```
