### DISCUSSION TITLE
How to route to individual StatefulSet pods (TCP)?

### DISCUSSION THREAD

**Discussion by mvrk69** [istio/istio#56287] [General]
Hi,

Does anyone know how to route traffic via ingressgateway based on host and tcp port to a specific pod of a stateful set ?

Lets say i have a statefulset with 3 pods

mariadb-0
mariadb-1
mariadb-2

and clusterip service:
service/mariadb     ClusterIP   172.16.19.103   <none>        3306/TCP   29h   app=mariadb

if i send traffic to 
- mariadb-0.mydomain.com it should be routed to pod mariadb-0
- mariadb-1.mydomain.com it should be routed to pod mariadb-1
- mariadb-2.mydomain.com it should be routed to pod mariadb-2

With http uri match and subsets would be easy, but with tcp i don't see how to match host/port with a subset, does anyone know?

I tried one VirtualService per pod, but doesn't work, sends always to pod0, seems it matches the 1st one with that port and ignores the hosts:

```
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: mariadb-0-tcp
  namespace: mariadb
spec:
  gateways:
  - mariadb
  hosts:
  - mariadb-0.mydomain.com
  tcp:
  - match:
    - port: 3306
    route:
    - destination:
        host: mariadb
        port:
          number: 3306
        subset: pod-0
```

```
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: mariadb-1-tcp
  namespace: mariadb
spec:
  gateways:
  - mariadb
  hosts:
  - mariadb-1.mydomain.com
  tcp:
  - match:
    - port: 3306
    route:
    - destination:
        host: mariadb
        port:
          number: 3306
        subset: pod-1
```

```
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: mariadb-2-tcp
  namespace: mariadb
spec:
  gateways:
  - mariadb
  hosts:
  - mariadb-2.mydomain.com
  tcp:
  - match:
    - port: 3306
    route:
    - destination:
        host: mariadb
        port:
          number: 3306
        subset: pod-2
```

```
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: mariadb
  namespace: mariadb
spec:
  host: mariadb
  subsets:
  - labels:
      apps.kubernetes.io/pod-index: "0"
    name: pod-0
  - labels:
      apps.kubernetes.io/pod-index: "1"
    name: pod-1
  - labels:
      apps.kubernetes.io/pod-index: "2"
    name: pod-2
```

```
nmap -sT -Pn -p 3306 mariadb-0.mydomain.com
nmap -sT -Pn -p 3306 mariadb-1.mydomain.com
```

```
[pod/istio-ingressgateway-58b685fcfb-wdwwd/istio-proxy] [2025-05-13T20:47:24.396Z] "- - -" 0 - - - "-" 0 0 0 - "-" "-" "-" "-" "10.244.57.36:3306" outbound|3306|pod-0|mariadb.mariadb.svc.cluster.local 10.244.57.52:57116 10.244.57.52:3306 192.168.10.3:39726 - -

[pod/istio-ingressgateway-58b685fcfb-wdwwd/istio-proxy] [2025-05-13T20:47:26.728Z] "- - -" 0 - - - "-" 0 0 0 - "-" "-" "-" "-" "10.244.57.36:3306" outbound|3306|pod-0|mariadb.mariadb.svc.cluster.local 10.244.57.52:57128 10.244.57.52:3306 192.168.10.3:39738 - -
```
