### DISCUSSION TITLE
Is it possible to setup failover using virtual services?

### DISCUSSION THREAD

**Discussion by darahask** [istio/istio#56329] [Q&A]
### Is it possible to go to minio-cluster2 only if minio-cluster1 fails?

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: minio-cluster
  namespace: sample
spec:
  hosts:
  - minio.minio.svc.cluster.local
  http:
  - route:
    - destination:
        host: minio-cluster1.minio.svc.cluster.local
        port:
          number: 80
      weight: 100
    - destination:
        host: minio-cluster2.minio.svc.cluster.local
        port:
          number: 80 
      weight: 0
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: minio-cluster1
  namespace: sample
spec:
  host: minio-cluster1.minio.svc.cluster.local
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 2
      interval: 5s
      baseEjectionTime: 30s
      maxEjectionPercent: 100
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: minio-cluster2
  namespace: sample
spec:
  host: minio-cluster2.minio.svc.cluster.local
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 2
      interval: 5s
      baseEjectionTime: 30s
      maxEjectionPercent: 100
EOF
```
