### DISCUSSION TITLE
Filtering traffic to different versions of backend based on a field in the request body

### DISCUSSION THREAD

**Discussion by venkatraopasupuleti-stashfin** [istio/istio#56325] [General]
I am currently working on following use case where I have to route the traffic of same api endpoint to different backends based on a field in the request body. For this we tried following approaches which are unsuccessful. Please give me some idea on how we can approach this use case. Thanks

**Approach 1: Decoding the request body in lua http filter in envoy and setting a header x-route-id based on which routing logic will be implemented** 
This approach however was unsuccessful as we are not able to set the header after reading the request body.

**Approach 2: Decoding the request body in lua http filter in envoy and setting a value in dynamicMetadata**
By this approach we are able to set the value in dynamicMetadata but the route filtering is not happening

**Comment by ramaraochavali** [comment]
You have to call [clearRouteCache](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter.html#clearroutecache)() at the end of Lua filter

**Reply by venkatraopasupuleti-stashfin** [reply]
```
static_resources:
  clusters:
  - name: flask_app_mode_1
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: flask_app_mode_1
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: flask_app_mode_1
                port_value: 5000

  - name: flask_app_mode_2
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: flask_app_mode_2
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: flask_app_mode_2
                port_value: 6000


  listeners:
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
      - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              codec_type: AUTO
              http_filters:
                - name: envoy.filters.http.lua
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
                    inline_code: |
                        function envoy_on_request(request_handle)
                          request_handle:logInfo("inside on requestBody")
                          request_handle:headers():add("my-header", "my-header-value")
                          local requestBody = ""
                          for chunk in request_handle:bodyChunks() do
                            if (chunk:length() > 0) then
                              requestBody = requestBody .. chunk:getBytes(0, chunk:length())
                            end
                          end
                          request_handle:logInfo(requestBody)
                          local mode = requestBody and string.match(requestBody, "mode=([^&]+)")
                          request_handle:streamInfo():dynamicMetadata():set("envoy.filters.http.lua","mode",mode)
                          request_handle:clearRouteCache()
                          return
                        end
                        function envoy_on_response(response_handle)
                          local metadata = response_handle:streamInfo():dynamicMetadata():get("envoy.filters.http.lua")
                          if metadata then
                            for k, v in pairs(metadata) do
                              response_handle:logInfo("Metadata key: " .. k .. " = " .. tostring(v))
                            end
                          else
                            response_handle:logInfo("No dynamic metadata found")
                          end
                        end
                - name: envoy.filters.http.router
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              route_config:
                name: local_routes
                virtual_hosts:
                  - name: local_service
                    domains:
                      - "*"
                    routes:
                      - match:
                          prefix: "/"  # Required field
                        route:
                          cluster: flask_app_mode_1
                        metadata:
                             filter_metadata:
                               "envoy.filters.http.lua":
                                 mode: "v1"
                      - match:
                          prefix: "/"  # Same prefix
                        route:
                          cluster: flask_app_mode_2
                        metadata:
                             filter_metadata:
                               "envoy.filters.http.lua":
                                 mode: "v2"


```
