### DISCUSSION TITLE
How do I make Istio + Kind + Gateway on Localhost work?

### DISCUSSION THREAD

**Discussion by agardnerIT** [istio/istio#56364] [Q&A]
I will first explain what I have working, to provide the context of what I'm trying to achieve. Scroll further for the setup I'm trying (the gateway setup).

# Currently Working (NGINX Ingress Controller)

![image](https://github.com/user-attachments/assets/8b96638c-3b49-4053-b477-a80fbadd02ce)

I have an nginx-ingress-controller working on kind on localhost (windows + podman if it makes a difference):

```
kind create cluster --config=cluster1.yml
kubectl apply -f https://kind.sigs.k8s.io/examples/ingress/deploy-ingress-nginx.yaml
kubectl wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=90s
kubectl apply -f https://kind.sigs.k8s.io/examples/ingress/usage.yaml
kubectl wait --namespace default pod --all --for=condition=ready --timeout=90s
```

### File Definitions
`cluster1.yml`
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.30.0
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
```

## Istio Setup
As I understand the docs, I can entirely replace nginx-ingress-controller with gateway and the `gatewayClassName: istio` should create the infrastructure.

### Istio File Definitions

`cluster.yaml`
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.30.0
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
```

`gateway.yaml`

Note: I've also tried this without the annotations but the gateway remains as `Programmed: False`

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: httpbin-gateway
  namespace: default
  annotations:
   networking.istio.io/service-type: ClusterIP
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
```

`httproute.yaml`
```
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httpbin-foo-route
  namespace: default
spec:
  parentRefs:
  - name: httpbin-gateway
  rules:
  - matches:
    - path:
        type: Exact
        value: /foo
    backendRefs:
    - name: foo-service
      port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httpbin-bar-route
  namespace: default
spec:
  parentRefs:
  - name: httpbin-gateway
  rules:
  - matches:
    - path:
        type: Exact
        value: /bar
    backendRefs:
    - name: bar-service
      port: 8080
```

### Istio Gateway Creation Script

```
kind create cluster --config=cluster1.yml
helm repo add istio https://istio-release.storage.googleapis.com/charts
helm repo update
# Install the Istio base chart which contains cluster-wide Custom Resource Definitions (CRDs)
# which must be installed prior to the deployment of the Istio control plane
helm install istio-base istio/base -n istio-system --set defaultRevision=default --create-namespace
helm ls -n istio-system     # make sure status is deployed
# Now deploy Istio proper
helm install istiod istio/istiod -n istio-system --wait

# Make sure it's all running
kubectl get deployments -n istio-system --output wide

# Create an ingress gateway
kubectl create namespace istio-ingress
helm install istio-ingress istio/gateway -n istio-ingress --create-namespace --wait
kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0/standard-install.yaml
# Deploy the foo and bar service again
# But this time from a local copy (without the kind: Ingress because a kind: Gateway will be created instead in the next step)
kubectl apply -f usage.yaml
kubectl wait --namespace default pod --all --for=condition=ready --timeout=90s

# Now create the gateway
# Notice that we've had to add an annotation for ClusterIP to the gateway so that it becomes programmed
# Otherwise it sits forever it "Programmed: False"
kubectl apply -f gateway.yaml
kubectl apply -f httproute.yaml
```
