### DISCUSSION TITLE
Local Rate Limit `token_bucket_settings` not recognized in Istio 1.26 Envoy proxy despite Envoy 1.34.1-dev label

### DISCUSSION THREAD

**Discussion by ifishchuk** [istio/istio#56386] [Q&A]
Hello Istio team,

We’re trying to implement Istio local rate limiting using the dynamic token bucket support recently added in Envoy via the `token_bucket_settings` field ([PR #36623](https://github.com/envoyproxy/envoy/pull/36623)).

Our environment:

1. Istio version: 1.26
2. Envoy version (as reported by istio-proxy container): 
The Envoy sidecar binary reports version:
`envoy version: 71a753428f4479887db4b686ca9d01cfc6e11068/1.34.1-dev/Clean/RELEASE/BoringSSL`

The problem I am facing is:

The newer local rate limit filter feature **token_bucket_settings** ([introduced in Envoy 1.34.0](https://github.com/envoyproxy/envoy/pull/36623)) is not recognized when applied via EnvoyFilter in Istio.

Attempts to use `token_bucket_settings` in EnvoyFilter result in:

`Warning: Envoy filter: can't unmarshal Any nested proto type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit: unknown field "token_bucket_settings" in envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit`

Here is a minimal EnvoyFilter YAML example that I used to test `token_bucket_settings`:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: test-local-ratelimit-token-bucket-settings
  namespace: backbase
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/instance: backbase-identity
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            stat_prefix: http_local_rate_limiter
            token_bucket_settings:
              token_bucket:
                max_tokens: 10
                tokens_per_fill: 1
                fill_interval: 1s
              runtime_enabled:
                default_value: true
                runtime_key: local_rate_limit_enabled
              tokens_per_fill_runtime:
                default_value: 1
                runtime_key: tokens_per_fill_override
              max_tokens_runtime:
                default_value: 10
                runtime_key: max_tokens_override
            filter_enabled:
              runtime_key: local_rate_limit_enabled
              default_value:
                numerator: 100
                denominator: HUNDRED
            filter_enforced:
              runtime_key: local_rate_limit_enforced
              default_value:
                numerator: 100
                denominator: HUNDRED
```

`token_bucket_settings` does not show up in the test pod Envoy config dump.

Could you confirm whether the Envoy proxy binary included in Istio 1.26 fully supports token_bucket_settings?
