### DISCUSSION TITLE
Unexpected Match Order with Multiple HTTPRoutes on Same Hostname (Istio Ambient / Gateway API)

### DISCUSSION THREAD

**Discussion by share-me** [istio/istio#56392] [General]
Hello,

I'm currently facing an issue with multiple HTTPRoute resources applied to the same hostname in an Istio Ambient environment. My understanding, based on the [Gateway API specification](https://gateway-api.sigs.k8s.io/reference/spec/#httprouterule), is that HTTPRoute rules are to be evaluated in a flattened list and the most specific path match should take precedence.

Here’s the scenario: I have two HTTPRoute objects configured as follows:

    One route matches paths prefixed with /service/v2/ and routes to svc-service-v2.

    Another route matches /service/ and routes to svc-service.

Both are bound to the same Gateway and the same hostname (a.b.c.d.e).

However, when I send a request to /service/v2/, it is unexpectedly routed through the /service/ rule, leading to svc-service instead of svc-service-v2.

This behavior seems to contradict the expected order of evaluation where a more specific match (/service/v2/) should take precedence over a more generic one (/service/).

Am I misunderstanding the intended behavior of HTTPRoute precedence? Or could this be due to a different implementation or limitation in Istio Ambient?

Any insight would be greatly appreciated.

Best regards,

keywords: istio ambient httproute precedence routing path order gateway-api evaluation same hostname

**Comment by rsalmond** [comment]
Your understanding sounds correct to me. This behaviour sounds incorrect. If you can provide steps to reproduce this I believe you should file an issue.

**Comment by ilrudie** [comment]
What version of Istio? In 1.26 I modified gtw api conformance so that `conformance/tests/httproute-path-match-order.yaml` looks like this and conformance still passes:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: path-matching-order-2
  namespace: gateway-conformance-infra
spec:
  parentRefs:
  - name: same-namespace
  rules:
  - matches:
    - path:
        type: Exact
        value: /match
    backendRefs:
    - name: infra-backend-v1
      port: 8080
  - matches:
    - path:
        type: Exact
        value: /match/exact
    backendRefs:
    - name: infra-backend-v2
      port: 8080
  - matches:
    - path:
        type: Exact
        value: /match/exact/one
    backendRefs:
    - name: infra-backend-v3
      port: 8080
  - matches:
    - path:
        type: PathPrefix
        value: /match/
    backendRefs:
    - name: infra-backend-v3
      port: 8080
  - matches:
    - path:
        type: PathPrefix
        value: /match/prefix/
    backendRefs:
    - name: infra-backend-v1
      port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: path-matching-order
  namespace: gateway-conformance-infra
spec:
  parentRefs:
  - name: same-namespace
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /match/prefix/one
    backendRefs:
    - name: infra-backend-v2
      port: 8080
```

It seems like this small change would cover your use, although the original test doesn't try to test any semantics around multiple HTTPRoutes. Did I miss something?
