### DISCUSSION TITLE
Controlling TCP egress traffic targeting TLS endpoints with DNS

### DISCUSSION THREAD

**Discussion by torbendury** [istio/istio#56402] [Q&A]
Hello all,

I'm currently facing a challenge that I couldn't wrap my head around the last few days. I'm pretty fed up with it because I couldn't get anything to work, so here I am.

## Scenario

I want application `a` in namespace `a` to be able to access `db.com` on port `5432`. It is a PostgreSQL endpoint outside my Kubernetes cluster to which `a` will connect to via TLS connection on port `5432`.

To better control traffic, I want to route it through my egress gateway.

**Only** `a` should be able to reach `db.com:5432`.

For TCP endpoints reachable via IP address, for example MySQL instances, I used to solve this by creating a Kubernetes `Service` that points to my egress gateway on port `3306` and then only allow the principal `cluster.local/ns/a/sa/a` to access `mysql-endpoint.istio-egress.svc.cluster.local` on port `3306`, however I can not get this to work in any way.

## What did I try out so far

Various things. For debugging purposes, I chose `google.com:443` instead of hosting a real DB with TLS certificates and ended up with a config similar to this:

```yaml
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-google-com
  namespace: istio-egress
spec:
  hosts:
    - google.com
  ports:
    - number: 443
      name: postgres
      protocol: TLS
  resolution: DNS
  location: MESH_EXTERNAL
```

```yaml
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: egress-gateway-google
  namespace: istio-egress
spec:
  selector:
    istio: egressgateway
  servers:
    - port:
        number: 443
        name: tls-db-com
        protocol: TLS
      hosts:
        - google.com
      tls:
        mode: AUTO_PASSTHROUGH
```

```yaml
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: egress-google
  namespace: istio-egress
spec:
  hosts:
    - google.com
  gateways:
    - mesh
    - egress-gateway-google
  tls:
    - match:
        - port: 443
          sniHosts:
            - google.com
      route:
        - destination:
            host: egress-gateway.istio-egress.svc.cluster.local
            port:
              number: 443
```

```yaml
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: egress-google-com
  namespace: istio-egress
spec:
  host: google.com
```

I tried several variations of this but this is where I stopped at.

I've been banging my head at this wall for way too long, so I became pretty blind for things that might be obvious to a fresh pair of eyes.

Very glad for any kind of hint into the right direction!
