### DISCUSSION TITLE
Istio EnvoyFilter to reduce initial_read_buffer_size in tls_inspector not working

### DISCUSSION THREAD

**Discussion by madhunzv** [istio/istio#56446] [Q&A]
Hi Team, We seem to be hitting this [issue](https://github.com/envoyproxy/envoy/issues/34706), and trying to reduce  initial_read_buffer_size to 8K as suggested in one of the [comments](https://github.com/envoyproxy/envoy/issues/34706#issuecomment-2165596873). Our current istio version is 1.20.6

Created envoyfilter to do the same, but could not see buffer size change in envoy listener config after applying this.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: tls-inspector-buffer-config
spec:
  configPatches:
  - applyTo: LISTENER_FILTER
    match:
      context: GATEWAY
      listener:
        listenerFilter: envoy.filters.listener.tls_inspector
        portNumber: 8443
    patch:
      operation: MERGE
      value:
        name: envoy.filters.listener.tls_inspector
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
          initial_read_buffer_size: 8192
```

      
Could you please help checking if there's any issue with this envoyfilter or guide on how initial_read_buffer_size value can be lowered on our current version?

**Comment by zirain** [comment]
you'd better to check the diff of the config dump before and after, make sure the merge worked as expected.

**Reply by madhunzv** [reply]
This tls_inspector filter config is same before and after envoyfilter applied. checked the diff of entire config_dump, but initial_read_buffer_size was not found. 
```

"listener_filters": [
        {
         "name": "envoy.filters.listener.tls_inspector",
         "typed_config": {
          "@type": "type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector"
         }
        }
      ],
```
MERGE operation seems to be not applying, How do I make sure MERGE works as expected?

**Reply by zirain** [reply]
can you change MERGE with REPLACE

@ramaraochavali why Istio didn't support MERGE here?

**Reply by madhunzv** [reply]
Tried with REPLACE operation, that doesn't have any effect as well

**Reply by ramaraochavali** [reply]
spec:
  workloadSelector:
    labels:
      app: istio-ingressgateway
  configPatches:
  - applyTo: LISTENER_FILTER
    match:
      context: GATEWAY
      listener:
        listenerFilter: "envoy.filters.listener.tls_inspector"
    patch:
      operation: REPLACE
      value:
        name: "envoy.filters.listener.tls_inspector"
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector"
          initial_read_buffer_size: 512

This works for us. Can you try this?

**Reply by madhunzv** [reply]
@ramaraochavali I've tried this config, both MERGE and REPLACE operations, but no luck. still not able to get buffer size updated in tls_filter.

However, tried below to add and remove the filter as below

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: tls-inspector-buffer-config-ingress
  namespace: istio-ingress
spec:
  configPatches:
  - applyTo: LISTENER_FILTER
    match:
      context: GATEWAY
      listener:
        listenerFilter: "envoy.filters.listener.tls_inspector"
    patch:
      operation: REMOVE
  - applyTo: LISTENER_FILTER
    match:
      context: GATEWAY
      listener:
        listenerFilter: envoy.filters.listener.tls_inspector
    patch:
      operation: ADD
      value:
        name: envoy.filters.listener.tls_inspector
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
          initial_read_buffer_size: 8196
  workloadSelector:
    labels:
      app: istio-ingressgateway
```
which added "initialReadBufferSize": 8196 to the tls_inspector filter, but traffic to the pod went completely zero, without any warn/error logs on both ingress, istiod pods. Anything am I missing?
```
"listenerFilters": [
            {
                "name": "envoy.filters.listener.tls_inspector",
                "typedConfig": {
                    "@type": "type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector",
                    "initialReadBufferSize": 8196
                }
            }
        ],
```
