### DISCUSSION TITLE
Unable to Apply Large EnvoyFilter with >5000 Descriptors Without Conflicts – Need Strategy to Split and Avoid Patch Overlap

### DISCUSSION THREAD

**Discussion by mks27** [istio/istio#56496] [Q&A]
### Is this the right place to submit this?

- [x] This is not a security vulnerability or a crashing bug
- [x] This is not a question about how to use Istio

### Bug Description

I'm applying an EnvoyFilter for local rate limiting in Istio. The filter uses descriptors based on different URLs.
A single file with ~5000 URL entries (about 1.88MB in size) is applied successfully using:
`kubectl apply --server-side --force-conflicts -f envoyfilter.yaml`

However, applying more than that fails due to Kubernetes resource size constraints (etcd 1.5MB object limit or server-side validation).

Issue
If I try to split the large EnvoyFilter into multiple ones (dividing the URL entries), I encounter conflicts because:
All filters attempt to patch the same filter chain: envoy.filters.network.http_connection_manager
This causes overlapping patches and conflict errors when applying multiple EnvoyFilters targeting the same filter.

Ask
Is there a recommended way to:
Split large EnvoyFilter descriptors into multiple EnvoyFilter resources?
Avoid conflicts while patching the same HTTP_FILTER and HTTP_ROUTE for local rate limiting?

Below is the sample envoyfilter yaml containing two URLs, actual envoyfilter will have more than 5000 URL entries.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: url-ratelimit-test
  namespace: test-ns
spec:
  workloadSelector:
    labels:
      app: test-pod
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter

    - applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_INBOUND
        routeConfiguration:
          vhost:
            name: "inbound|http|8080"
            route:
              action: ANY
      patch:
        operation: MERGE
        value:
          route:
              rate_limits:
              - actions:
                - request_headers:
                    header_name: "TEST-URL"
                    descriptor_key: path 
          typed_per_filter_config:
            envoy.filters.http.local_ratelimit:
              "@type": type.googleapis.com/udpa.type.v1.TypedStruct
              type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
              value:
                stat_prefix: http_local_rate_limiter
                token_bucket:
                  max_tokens: 10
                  tokens_per_fill: 10
                  fill_interval: 30s
                filter_enabled:
                  runtime_key: local_rate_limit_enabled
                  default_value:
                    numerator: 100
                    denominator: HUNDRED
                filter_enforced:
                  runtime_key: local_rate_limit_enforced
                  default_value:
                    numerator: 100
                    denominator: HUNDRED
                response_headers_to_add:
                  - append: false
                    header:
                      key: x-local-rate-limit
                      value: "true" 
                descriptors:
                  - entries:
                    - key: path
                      value: /testservice/1
                    token_bucket:
                      max_tokens: 2
                      tokens_per_fill: 2
                      fill_interval: 30s
                  - entries:
                    - key: path
                      value: /testservice/2
                    token_bucket:
                      max_tokens: 2
                      tokens_per_fill: 2
                      fill_interval: 30s
```

### Version

```Text
Istio version: 1.15.7
Kubernetes version: 1.29.3
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Dual Stack
- [ ] Installation
- [ ] Networking
- [x] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
