### DISCUSSION TITLE
Ingressgateway starts before istiod – better solution ?

### DISCUSSION THREAD

**Discussion by emreberber** [istio/istio#56527] [Q&A]
I'm deploying the Istio via Helm umbrella chart like below:

```
dependencies:
  - name: base
    version: "1.26.1"
  - name: istiod
    version: "1.26.1"
  - name: gateway
    version: "1.26.1"
```

The **ingressgateway** pod starts before istiod, so it try pulling the `auto` image and fails with `ImagePullBackOff`.

I currently fix this with a post-install Helm Job that waits for istiod and then restarts the gateway pods. It works, but feels hacky.

Is there a better or official way to handle this ?

Thanks!
