### DISCUSSION TITLE
Request from a namespace not in mesh to a namespace/ service in mesh

### DISCUSSION THREAD

**Discussion by deepak7946** [istio/istio#56523] [Q&A]
The test setup has microservice demo app deployed https://github.com/GoogleCloudPlatform/microservices-demo
The app is deployed in a namesapce boutique which is ambient enabled
Was testing curl requests to the frontend/ productcatalog service from notinmesh namespace that is not under ambient mesh (kubectl run --image curlimages/curl curl-frontend -n notinmesh -- curl -v frontend.boutique.svc.cluster.local/product/OLJCESPC7Z),

We do see accesslogs for the above connection in ztunnel logs
`connection complete src.addr=10.244.1.58:49616 src.workload="curl-frontend" src.namespace="notinmesh" dst.addr=10.244.1.246:8080 dst.service="frontend-external.boutique.svc.cluster.local" dst.workload="frontend-6b88d4dcd7-zrnbd" dst.namespace="boutique" direction="inbound" bytes_sent=8230 bytes_recv=117 duration="32ms" `

However, there is no logs captured in waypoint. 
1) Is this expected behavior? Was expecting it to be captured in waypoint access logs since it is a L7 request. 

2) We want to export access logs to an external collector, we were able to explore all the in cluster communications using the below configuration. Is there a way to export ztunnel access logs as well in a similar way to an external collector?

telemetry resource

<code>
spec:
  accessLogging:
  - providers:
    - name: ct-http-als
    - name: ct-tcp-als
</code>

istio config

<code>
mesh: |-
    accessLogEncoding: JSON
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      extraStatTags:
      - request_method
      - request_path
      tracing:
          zipkin:
            address: zipkin.istio-system:9411
      image:
        imageType: distroless
      proxyMetadata:
        ISTIO_META_ENABLE_HBONE: "true"
    defaultProviders:
      metrics:
      - prometheus
    enableEnvoyAccessLogService: true
    extensionProviders:
    - envoyHttpAls:
        port: 9999
        service: collector.test-ns.svc.cluster.local
      name: ct-http-als
    - envoyTcpAls:
        port: 9999
        service: collector.test-ns.svc.cluster.local
      name: ct-tcp-als
    enablePrometheusMerge: true
    rootNamespace: istio-system
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
</code>

**Comment by zirain** [comment]
did you add annotation on that svc or namespace?

**Comment by deepak7946** [comment]
Labels are added to the namespace
`
Labels:       istio.io/dataplane-mode=ambient                                                    │
│               istio.io/use-waypoint=waypoint
`

gateway is deployed as well
kubectl get gateway -n boutique
NAME       CLASS            ADDRESS       PROGRAMMED   AGE
waypoint   istio-waypoint   10.0.171.58   True         36m

**Reply by zirain** [reply]
IIUC, you request from a not-in-mesh namespace, which means there's no traffic capture by ztunnel.

**Reply by deepak7946** [reply]
Yes correct connection initiated from a namesapce that is not in service mesh (not labelled). I could see the access log with source ip as the curl pod and destination as the frontend in the ztunnel logs, show below. However in waypoint access logs there is no reference of it. Is this expected?

curl pod (notinmesh namespace) >>> ztunnel  >>> frontend service (boutique namespace)

`
connection complete src.addr=10.244.1.58:49616 src.workload="curl-frontend" src.namespace="notinmesh" dst.addr=10.244.1.246:8080 dst.service="frontend-external.boutique.svc.cluster.local" dst.workload="frontend-6b88d4dcd7-zrnbd" dst.namespace="boutique" direction="inbound" bytes_sent=8230 bytes_recv=117 duration="32ms" 
`

**Reply by ilrudie** [reply]
The client-side ztunnel would be the proxy which knows the waypoint needs to be used. No client ztunnel means would mean the waypoint is skipped

**Reply by deepak7946** [reply]
Thank you @ilrudie That explains why we did not see the access log on the destination waypoint proxy.

As part of test we enabled otel extentionProvider and in telemery configured to forward the telemetry (Access) logs to open telemetry collector. We see only the traffic that is hitting waypoint in the collector (be it the custom collector or otel). We do not see access logs from the ztunnel on the collector. Is this expected?

The follow up question now is, since we can see an access log in the destination ztunnel, as in the above snippet, is it possible to export the access logs in ztunnel to and external collector as we do with envoy access logs?

Telemetry config:
```
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: access-logs
  namespace: istio-system
spec:
  accessLogging:
  - providers:
    - name: otel
```

istio config map:

```
data:
  mesh: |-
    accessLogFile: /dev/stdout
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      proxyMetadata: {}
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
    enablePrometheusMerge: true
    extensionProviders:
    - name: otel
      envoyOtelAls:
        service: opentelemetry-collector.observability.svc.cluster.local
        port: 4317
    rootNamespace: istio-system
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
```
