### DISCUSSION TITLE
Istio Cross-Zone traffic metrics based on topology.kubernetes.io/zone

### DISCUSSION THREAD

**Discussion by seilerre** [istio/istio#56680] [Q&A] [answered]
We would like to see in Prometheus if Traffic is going cross zone, based on the Kubernetes Node label "topology.kubernetes.io/zone". For example it would be great to have this in metrics like istio_tcp_sent_bytes_total. I tried something like this

```yaml
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: add-zone-tags-global
  namespace: istio-system
spec:
  selector:
    matchLabels: {}  # Applies to everything
  metrics:
  - overrides:
    - match:
        metric: ALL_METRICS
      tagOverrides:
        source_zone:
          operation: UPSERT
          value: 'node.metadata["topology.kubernetes.io/zone"] ?: "unknown"'
        destination_zone:
          operation: UPSERT
          value: 'upstream_peer.node.metadata["topology.kubernetes.io/zone"] ?: "unknown"'
```

It doesnt seem that the new labels are populated though.
