### DISCUSSION TITLE
How to Apply a Global Path Rewrite for Inter-Service Calls in Istio Ambient?

### DISCUSSION THREAD

**Discussion by share-me** [istio/istio#56733] [Q&A] [answered]
Hello,

I'm using Istio Ambient and I want to apply a rewrite rule to all inter-service calls.
Specifically, I need to remove any '/v1', '/v2', '/v3', or '/v4' prefix from the request path.
What is the recommended way to achieve this?

**Comment by zirain** [comment]
you need a waypoint to do L7 policy.

**Comment by share-me** [comment]
I've created my L7 waypoint and my services are correctly pointing to it, but creating an HTTPRoute has no effect.



```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-waypoint
  namespace: tst10
  labels:
    istio.io/waypoint-for: service
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - name: mesh
    port: 15008
    protocol: HBONE
  infrastructure:  
    parametersRef:
      group: ""
      kind: ConfigMap
      name: gateway-waypoint-options
```


```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: custom-route
spec:
  parentRefs:
  - name: gateway-waypoint
    kind: Gateway
    namespace: tst10
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /myalarms/api/v1/
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /myalarms/api/
```


```yaml
apiVersion: v1
kind: Service
metadata:
  name: svc-myalarms
  namespace: tst10
  labels:
    istio.io/use-waypoint: gateway-waypoint
    # istio.io/ingress-use-waypoint: "true"
spec:
  selector:
    app: myalarms
    channel: v1
  type: ClusterIP
  ports:
  - name: svc-app-port
    port: 10443
    targetPort: app-port
    appProtocol: http
```

**Reply by zirain** [reply]
did the traffic actually go through the waypoint? you can double check the access log to confirm that.

**Comment by share-me** [comment, marked as answer]
To apply the "custom-gateway" HTTPRoute to traffic originating from the Gateway API, the parentRefs field must reference the Gateway resource.

To apply the "custom-route" HTTPRoute to traffic between pods, the parentRefs field must reference the corresponding Service.

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: custom-route
spec:
  parentRefs:
  - group: ""
    kind: Service
    name: svc-myalarms
    port: 10443
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /myalarms/api/v1/
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /myalarms/api/
```


If traffic entering through the Gateway API must be processed by both httproute objects, the Service must include the following label:
`istio.io/ingress-use-waypoint: "true"`

This configuration ensures that ingress traffic routed via the Gateway is forwarded to the Service waypoint, allowing both HTTPRoute resources to be applied sequentially.
