### DISCUSSION TITLE
VirtualService timeout explanation

### DISCUSSION THREAD

**Discussion by ffppmm** [istio/istio#56756] [Q&A]
Hi,

it may sound trivial but I don't undestand the behavior of the timeout property in a VirtualService. I have the following yaml:
```yaml
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: my-webserver
spec:
  gateways:
    - somegateway
  hosts:
    - somehost.fqdn
  http:
    - match:
        - headers:
            x-stateid:
              exact: something
          uri:
            prefix: /web
      route:
        - destination:
            host: webserver-1
            port:
              number: 8081
            subset: something
      timeout: 3m
```
If I download a "big" file that takes longer than 3m, the request is stopped:
```
curl: (18) transfer closed with 3762486853 bytes remaining to read
```
I thought that as long as data is flowing the timeout doesn't hit. Instead it looks like if this is a hard timeout for the whole request ([request_timeout](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-request-timeout)).

Is this correct? So if I specify the timeout property in a VirtualService, thats the time a request as a whole may last?

Regards Philipp
