### ISSUE TITLE
can not access the external service registered on external Consul inside K8s service but is accessible via ingressgateway

### ISSUE THREAD

**Issue by jeffcai** [istio/istio#10030]
**Describe the bug**
I have a service-b registered on Consul, and service-b and Consul both are running outside of Kubernetes, and modified the pilot discovery to add the Consul registry, and meanwhile I deployed a service-a on Kubernetes which is to call service-b with the http url: http://service-b.service.consul:8071, and also created gateway, virtualservice and destinationrule as shows below:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: consul-demo-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: demo-services
spec:
  hosts:
  - "*"
  gateways:
  - consul-demo-gateway
  http:
  - match:
    - uri:
        prefix: /serviceb
    rewrite:
      uri: "/"
    route:
    - destination:
        host: service-b.service.consul
        port:
          number: 8071
  - match:
    - uri:
        prefix: /servicea
    rewrite:
      uri: "/"
    route:
    - destination:
        host: servicea
        subset: v1
        port:
          number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: servicea
spec:
  host: servicea
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: service-b
spec:
  host: service-b.service.consul
      
```

the problem I had is: I can access the service-b through the istio ingressgateway like: http://localhost/serviceb, but fail to access it in the service-a with url: http://service-b.service.consul:8071 (the host can not be resolved), and it works to run the script 
```
curl -v http://${hostname}:8071 -H "host: service-b.service.consul" 
```

**Expected behavior**
- can access the http://service-b.service.consul:8071 in the service-a on K8s

**Steps to reproduce the bug**
described on the bug above

**Version**
Kubernetes v1.10: the cluster provided by the Docker for Mac 
Istio v1.0.3

**Installation**
use the Helm chart

**Environment**
Local MacOS machine

**Comment by GregHanson** [comment]
@jeffcai had some time to dig into this one some more.  You need to expose consul dns to kubernetes.  In order to hook up consul dns to kubernetes, your k8s installation must use coredns instead of kube-dns.  Coredns is the default is latest versions of k8s:
```
kubectl get po -n kube-system | grep coredns
coredns-576cbf47c7-kf7lr                1/1     Running   0          20h
```
If coredns is enabled in k8s, you will need:
```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {"consul": ["$(kubectl get svc consul-dns -o jsonpath='{.spec.clusterIP}')"]}
EOF
```
 `kubectl get svc consul-dns -o jsonpath='{.spec.clusterIP}'` assumes the instance of consul is running in k8s, if not you will need to extract the IP through other means.  You also need to append a `serivce.consul` section to the coredns configmap:
```
kubectl edit cm -n kube-system coredns

# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
Corefile: |
  .:53 {
      errors
      health
      kubernetes cluster.local in-addr.arpa ip6.arpa {
         pods insecure
         upstream
         fallthrough in-addr.arpa ip6.arpa
      }
      prometheus :9153
      proxy . /etc/resolv.conf
      cache 30
      loop
      reload
      loadbalance
  }
  service.consul:53 {
      errors
      cache 30
      proxy . <consul_dns_ip> #if consul is running in k8s: kubectl get svc consul-dns -o jsonpath='{.spec.clusterIP}'
  }
kind: ConfigMap
metadata:
creationTimestamp: 2019-01-08T17:56:31Z
name: coredns
namespace: kube-system
resourceVersion: "10911"
selfLink: /api/v1/namespaces/kube-system/configmaps/coredns
uid: baf419fa-136e-11e9-8af9-08002762374b
```
I was able to get dns working with the above setup in k8s version 1.12.1

Helpful links I found to get the config working:
https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#coredns
https://www.consul.io/docs/platform/k8s/dns.html
