### ISSUE TITLE
Istio doesn't work with Cassandra

### ISSUE THREAD

**Issue by diemtvu** [istio/istio#10053]
**Describe the bug**
Cassandra node cannot communicate with each other (handshaking / gossip), with or without mTLS.

Note: this is different from issue https://github.com/istio/istio/issues/1277 which partly due to incorrect containerPort. That issue get this same problem once the containerPort was fixed.

**Expected behavior**
[istio-dump.tar.gz](https://github.com/istio/istio/files/2596502/istio-dump.tar.gz)

**Steps to reproduce the bug**

1. Install Istio 1.0.3 withouth mTLS

1. Deploy cassandra (e.g following this [tutorial](https://kubernetes.io/docs/tutorials/stateful-application/cassandra/)). Make sure to declare containerPort for the pod in the statefulset.

1. Notice handshaking requests keep failing. Log on cassandra-0 shows issue connect to local backend

```
[2018-11-19T17:39:51.936Z] UF 0 0 0 "127.0.0.1:7000" inbound|7000||cassandra.default.svc.cluster.local 127.0.0.1:35262 10.44.4.11:7000 10.44.5.5:36344
```

**Version**
Istio 1.0.3
Kube: 1.9

**Installation**
{{ Please describe how Istio was installed }}

**Environment**
GKE

**Cluster state**

**Comment by sauldhernandez** [comment]
Running into the same issue here with istio 1.0.4 running on minikube.

```

**Comment by mabushey** [comment]
I believe Rook supports Cassandra. Rook is amazing, it's the only k8s "framework" that has just worked effortlessly, and their docs are correct (huge contrast to Istio docs). Rook, at least with Ceph, plays nice with Istio.

**Comment by costinm** [comment]
Did you set DestinationRule / LoadBalancer / PASSTHROUGH ?

**Comment by diemtvu** [comment]
I've just added this, but still doesn't work (also try to change host to cassandra-0.cassandra.default.svc.cluster.local, 1, 2 etc, but non works)

```
kind: DestinationRule
metadata:
  name:  cassandra
spec:
  host: cassandra.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: PASSTHROUGH
```

**Comment by diemtvu** [comment]
For the reference, here are the cds and lds dump of cassandra-1.

[cds.txt](https://github.com/istio/istio/files/2658321/cds.txt)
[lds.txt](https://github.com/istio/istio/files/2658322/lds.txt)

**Comment by diemtvu** [comment]
@costinm, I assign this issue to you. Please help to reassign to someone in networking team. Thanks.

**Comment by costinm** [comment]
I don't think anyone in Google networking side has bandwidth for this at
the moment - any Istio engineer should be able to pick this up,
the work is mostly related to installing and getting tcpdumps.

Any volunteers ?

**Comment by diemtvu** [comment]
Costin, can you give the instruction of what tcpdumps commands and what should be looked at? Thanks.

**Comment by costinm** [comment]
First need to find the ports that Casandra is using, and run
'tcpdump -s0 -xX port ... ' with and without istio, on client and server

We need to see what is different between the 2.

**Comment by gephcott** [comment]
any hope of this being fix in the near future? If not are there any Istio consultants out there that could pick this up?

**Comment by yaman** [comment]
@diemtvu & @costinm Istio is great for a lot of things but is not ready for production use if we can not run Cassandra/Kafka/Zookeeper/NameYourDistributedDataStuff. We have been struggling with istio transition for a while, and could not be able to deploy Cassandra in any way. I will try taking cassandra out of mesh and see if I can access it within mesh, while diminishing the benefits of istio and adding the complexity of it.

Should we back away for now?

**Comment by yaman** [comment]
@mabushey

Thanks for the info. I am already running multiple namespaces for multiple environments, and istio already brings tons of complexity anyway, the last thing I would like to add more *pseudo*-namespaces just for istio-cassandra sake. I am seriously thinking to move back to good old days of nginx ingress world.

I am using incubator/cassandra helm chart. By default *clusterIP: None* and *service.type* is ClusterIP is set within the service.yaml. Removed *clusterIP* and cassandra nodes started to successfully handshake. Though still cannot reach to cassandra nodes in istio-mesh from my golang service.

I have another service couple with haskell+mongodb in istio-mesh. I works fine though.

**Comment by diemtvu** [comment]
Sorry, I was unable to get back to this until lately. Good news is, I think I found the issue.

The problem is [`listen_address`](https://docs.datastax.com/en/cassandra/3.0/cassandra/configuration/configCassandra_yaml.html) was set to `POD_IP` (at least for the setup in the [kubernetes tutorial](https://kubernetes.io/docs/tutorials/stateful-application/cassandra/). Because of that, sidecar proxy cannot forward traffic to localhost. 

You can check and modify `/etc/cassandra/cassandra.yaml` in your system. If you use google-sample cassandra image, there is no simple way to set this value yet (I've just file a feature request), but you can build and use your own image. For example, here is the sample Dockerfile to do so.

```
FROM gcr.io/google-samples/cassandra:v13
RUN sed -i 's/^CASSANDRA_LISTEN_ADDRESS=.*/CASSANDRA_LISTEN_ADDRESS="127.0.0.1"/' /run.sh
```

Also, in case you miss other note in previous thread, make sure the cassandra service contain the ports information.

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
spec:
  clusterIP: None
  ports:
  - name: tcp-client
    port: 9042
  - port: 7000
    name: tcp-intra-node
  - port: 7001
    name: tcp-tls-intra-node
  - port: 7199
    name: tcp-jmx
  selector:
    app: cassandra
```

**Comment by diemtvu** [comment]
Can you send me the authentication policies and destination rules in your system. Also, the Cassandra deployment yaml. Thanks.

**Comment by ahadrana** [comment]
Istio doesn't seem to handle Headless Services associated with a Statefulset properly. It is not clear to me yet whether this is a bug or by design. In the meantime, this is what we had to do to make Statefulsets work properly in Istio (as of 1.1.2): 

1. As mentioned above, for the envoy sidecar proxy to route traffic to your pod properly, your container has to bind to localhost, NOT $POD_IP. 

2. Pods in a Statefulset are  identified by a combination of hostname and ordinal position. So, the fully qualified DNS name for a pod 0 in a statefulset called zk using a Headless Service named zk-service would be _zk-0.zk-service.{namespace}_. All _outbound_ traffic associated with an Istio-enabled pod is redirected to its sidecar proxy. Since, as of now, istio maps the above mentioned unique Headless Service name (per ordinal) improperly, istio-enabled pods cannot talk to the instances in your Stateful set. To fix this, you need to create a ServiceEntry config that tells the istio sidecar proxy how to handle your unique Statefulset service names. An example for a hypothetical Zookeeper Statefulset consisting of 3 ZK nodes would be as follows: 

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: zk-stateful-set-mapping
  namespace: zk
spec:
  hosts:
  - zk-0.zk-service.zk
  - zk-1.zk-service.zk
  - zk-2.zk-service.zk
  location: MESH_INTERNAL
  ports:
  - number: 2181
    name: tcp
    protocol: TCP
  resolution: DNS
``` 
The above sample config will tell the Istio-enabled pod's sidecar proxy to resolve your Zookeeper Statefulset pod names using kube-dns and then route the traffic as appropriate.

Docs explaining Egress can be found here: [https://istio.io/docs/tasks/traffic-management/egress/](https://istio.io/docs/tasks/traffic-management/egress/)
Docs explaining ServiceEntry can be found here: [https://istio.io/docs/reference/config/networking/v1alpha3/service-entry/](https://istio.io/docs/reference/config/networking/v1alpha3/service-entry/)
