### ISSUE TITLE
gRPC mirroring does not work

### ISSUE THREAD

**Issue by sergio-fleetsmith** [istio/istio#10057]
**See second comment for easy to reproduce setup.**

**Describe the bug**
gRPC calls are not mirrored properly. Only server reflection calls are mirrored.
Other gRPC calls are only mirrored once client pod is restarted/deleted.

**Expected behavior**
All gRPC calls to be mirrored properly, not just server reflection calls.

**Steps to reproduce the issue**
**See second comment for easy to reproduce setup.**
Have three gRPC services (client, serverA, and serverB).
Each service has their own kubernetes deployment and kubernetes service.
Client has label `version=v1`, serverA has label `version=legacy-v1`, and serverB has label `version=newest-v1`.
Have the client make a gRPC call to serverA while having a mirrored route for serverB (per VirtualService).

Client DestinationRule
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: clientService
spec:
  host: clientService
  subsets:
  - name: v1
    labels:
      version: v1
```

Client VirtualService
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: clientService
spec:
  hosts:
  - clientService
  http:
  - route:
    - destination:
        host: clientService
        subset: v1
      weight: 100
```

ServerA VirtualService (with ServiceB mirroring)
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: serverA
spec:
  hosts:
  - serverA
  http:
  - route:
    - destination:
        host: serverA
        subset: legacy
      weight: 100
    mirror:
      host: serverB
      subset: newest
```

ServerA DestinationRule
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: serverA
spec:
  host: serverA
  subsets:
  - name: legacy
    labels:
      version: legacy-v1
```

serverB DestinationRule
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: serverB
spec:
  host: serverB
  subsets:
  - name: newest
    labels:
      version: newest-v1
```

**Version**
```
$ ./istioctl version
Version: 1.0.2
GitRevision: d639408fded355fb906ef2a1f9e8ffddc24c3d64
User: root@66ce69d4a51e
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.8", GitCommit:"7eab6a49736cc7b01869a15f9f05dc5b49efb9fc", GitTreeState:"clean", BuildDate:"2018-09-14T16:06:30Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.8", GitCommit:"7eab6a49736cc7b01869a15f9f05dc5b49efb9fc", GitTreeState:"clean", BuildDate:"2018-09-14T15:54:20Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
```curl -L https://git.io/getLatestIstio | sh -
kubectl apply -f install/kubernetes/helm/istio/templates/crds.yaml
kubectl apply -f install/kubernetes/istio-demo.yaml
```

**Environment**
GKE

**Comment by sergio-fleetsmith** [comment]
Was able to replicate this using a contrived gRPC example which makes it easy to reproduce.
Here I use [YAGES](https://github.com/mhausenblas/yages) as the base image for the two servers.
I then use a [dockerized grpcurl](quay.io/datawire/grpcurl) to continuously send grpc requests to the YAGES service.

### To reproduce
Create the resources below (create the client last so it does not error out when making the requests). Then inject 3 services (client and two servers) into istio service mesh as such:

##### Original Server/service
```
./istioctl kube-inject -f <(kubectl get deployment -o yaml  yages) | kubectl apply -f -
```

##### Mirrored server/service
```
./istioctl kube-inject -f <(kubectl get deployment -o yaml  yages-mirror) | kubectl apply -f -
```

##### Client
```
./istioctl kube-inject -f <(kubectl get deployment -o yaml  grpcurl) | kubectl apply -f -
```
#### Observations
if you monitor the logs of `istio-proxy` container inside the `yages` pod, you will see two grpc calls are being made (logs of 2 grpc calls being made):
```
[2018-11-26T22:42:39.387Z] "POST /yages.Echo/Ping HTTP/2" 200 - 5 11 14 13 "-" "grpc-go/1.17.0-dev" "d17c0157-8ba6-9e82-932c-e831ffbb1182" "yages:9000" "127.0.0.1:9000"
[2018-11-26T22:42:39.379Z] "POST /grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo HTTP/2" 200 - 72 2013 98 - "-" "grpc-go/1.17.0-dev" "fa97ac7f-8c5c-94dd-b373-08a9b83ea5f0" "yages:9000" "127.0.0.1:9000"
[2018-11-26T22:42:49.604Z] "POST /yages.Echo/Ping HTTP/2" 200 - 5 11 1 0 "-" "grpc-go/1.17.0-dev" "2549297a-9d30-9982-9357-c8febd8d31df" "yages:9000" "127.0.0.1:9000"
[2018-11-26T22:42:49.585Z] "POST /grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo HTTP/2" 200 - 72 2013 23 - "-" "grpc-go/1.17.0-dev" "401888a0-7d3d-91ac-a08b-0e6b999fd13e" "yages:9000" "127.0.0.1:9000"
```
The second one **by timestamp**, ```POST /yages.Echo/Ping HTTP/2```, being the explicit grpc call being made by the client grpcurl pod (```while true; do grpcurl --plaintext yages:9000 yages.Echo.Ping; sleep 10; done```). The first one  **by timestamp** being a grpc call from the client grpcurl pod to the yages server to figure out the sever's API.

Now if you look at the logs of `istio-proxy` container inside the `yages-mirror` pod, you will see that only the reflection call is being mirrored (logs of 2 grpc calls being made)
```
[2018-11-26T22:42:39.476Z] "POST /grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo HTTP/2" 200 - 72 2013 7 4 "10.10.12.86" "grpc-go/1.17.0-dev" "fa97ac7f-8c5c-94dd-b373-08a9b83ea5f0" "yages-shadow:9000" "127.0.0.1:9000"
[2018-11-26T22:42:49.608Z] "POST /grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo HTTP/2" 200 - 72 2013 3 0 "10.10.12.86" "grpc-go/1.17.0-dev" "401888a0-7d3d-91ac-a08b-0e6b999fd13e" "yages-shadow:9000" "127.0.0.1:9000"
```
However once you delete the grpcurl pod (or deployment), it flushes the direct `Ping` grpc call:
```
[2018-11-26T22:42:39.476Z] "POST /grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo HTTP/2" 200 - 72 2013 7 4 "10.10.12.86" "grpc-go/1.17.0-dev" "fa97ac7f-8c5c-94dd-b373-08a9b83ea5f0" "yages-shadow:9000" "127.0.0.1:9000"
[2018-11-26T22:42:49.608Z] "POST /grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo HTTP/2" 200 - 72 2013 3 0 "10.10.12.86" "grpc-go/1.17.0-dev" "401888a0-7d3d-91ac-a08b-0e6b999fd13e" "yages-shadow:9000" "127.0.0.1:9000"
[2018-11-26T22:42:49.606Z] "POST /yages.Echo/Ping HTTP/2" 0 - 0 0 3506 - "10.10.12.86" "grpc-go/1.17.0-dev" "2549297a-9d30-9982-9357-c8febd8d31df" "yages-shadow:9000" "127.0.0.1:9000"
[2018-11-26T22:42:39.475Z] "POST /yages.Echo/Ping HTTP/2" 0 - 0 0 13639 - "10.10.12.86" "grpc-go/1.17.0-dev" "d17c0157-8ba6-9e82-932c-e831ffbb1182" "yages-shadow:9000" "127.0.0.1:9000"
```

Note that the timestamps of the flushed `Ping` calls closely follows the the `ServerReflectionInfo` call in `yages-mirror`, as seen in `yages` pod.

# Resources
## Client
**Deployment and Service**
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: grpcurl
  name: grpcurl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grpcurl
        version: v1
    spec:
      containers:
      - name: grpcurl
        image: quay.io/datawire/grpcurl:latest
        command: ["/bin/sh"]
        args: ["-c", "while true; do grpcurl --plaintext yages:9000 yages.Echo.Ping; sleep 10; done"]
        ports:
        - containerPort: 9000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpcurl
  name: grpcurl
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: grpcurl
```
**DestinationRule and VirtualService**
No destinationrule or virtualservice for the client since it is not receiving any requests.

## Servers
**Deployment and Service for original service**
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: yages
  name: yages
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: yages
        version: v1
    spec:
      containers:
      - name: grpcsrv
        image: quay.io/mhausenblas/yages:0.1.0
        ports:
        - containerPort: 9000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: yages
  name: yages
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: yages
```

**Deployment and Service for mirrored service**
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: yages-mirror
  name: yages-mirror
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: yages-mirror
        version: v1-mirror
    spec:
      containers:
      - name: grpcsrv
        image: quay.io/mhausenblas/yages:0.1.0
        ports:
        - containerPort: 9000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: yages-mirror
  name: yages-mirror
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: yages-mirror
```

**VirtualService (which specifies mirroring)**
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: yages
spec:
  hosts:
  - yages
  http:
  - route:
    - destination:
        host: yages
        subset: original
      weight: 100
    mirror:
      host: yages-mirror
      subset: mirror
```

**DestinationRule for both services**
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: yages
spec:
  host: yages
  subsets:
  - name: original
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: yages-mirror
spec:
  host: yages-mirror
  subsets:
  - name: mirror
    labels:
      version: v1-mirror
```
