### ISSUE TITLE
Can not use hostname on virtualService

### ISSUE THREAD

**Issue by darkrasid** [istio/istio#10069]
Hello, I use 1.0.3 istio.

I use a Nodeport ingressgateway and want to access pod with hostname.

my gateway
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  clusterName: ""
  generation: 0
  name: test-api-ingress-gateway
  namespace: pilsner
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - test-bookinfo.pilsner.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
```

and my virtual service.
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  clusterName: ""
  creationTimestamp: 2018-11-20T10:37:21Z
  generation: 0
  name: test-api-virtualservice
  namespace: pilsner
spec:
  gateways:
  - test-api-ingress-gateway
  hosts:
  - '*'
  http:
  - route:
    - destination:
        host: test.pilsner.svc.cluster.local
        port:
          number: 8080
```

And I regist `test-bookinfo.pilsner.com` url on my dns server.

```
Server:         10.20.xx.xx
Address:        10.20.xx.xx#53

Non-authoritative answer:
Name:   test-bookinfo.pilsner.com
Address: 10.113.xxx.xxx
```

With these config, it works well.

However when I try to add specific hostname on virtual service, it occurs error.

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  clusterName: ""
  creationTimestamp: 2018-11-20T10:37:21Z
  generation: 0
  name: test-api-virtualservice
  namespace: pilsner
spec:
  gateways:
  - test-api-ingress-gateway
  hosts:
  - 'test-bookinfo.pilsner.com'
# or - '*.pilsner.com'
  http:
  - route:
    - destination:
        host: test.pilsner.svc.cluster.local
        port:
          number: 8080
```

I already read [docs](https://istio.io/docs/tasks/traffic-management/ingress/#accessing-istio-service-mesh-by-a-browser). 
```
this is not a problem because because you configure the requested host properly and DNS resolvable.
```
I don't understand this words. Even I registed dns, browser does not inject HOST header.

If I want to specify hostname not '*',  there is any extra works to do?
