### ISSUE TITLE
Get 503 Error Code when accessing service on remote cluster from local pod with ingress gateway

### ISSUE THREAD

**Issue by morvencao** [istio/istio#10083]
**Describe the bug**
Have followed the doc here: https://preliminary.istio.io/docs/setup/kubernetes/multicluster-install/gateways/
to setup `Istio multi-cluster` deployment with daily build: https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/

I found that if I use the daily build on [20181112](https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/release-1.1-20181112-21-12/), then everything seems OK, I can access service on remote cluster from local pod with the help of `serviceentry` and `ingressgateway`.
However, If I use the  daily build after that day, when I access service on remote cluster from local pod, I get `503` error code:
```
root@xaubt1:~/istio-release-1.1-20181118-09-15# kubectl exec -it sleep-6748c7b795-99gqg -c sleep sh
/ #
/ #
/ #
/ # curl -v http://httpbin.default.global:8000/
*   Trying 127.255.0.3...
* TCP_NODELAY set
* Connected to httpbin.default.global (127.255.0.3) port 8000 (#0)
> GET / HTTP/1.1
> Host: httpbin.default.global:8000
> User-Agent: curl/7.60.0
> Accept: */*
>
< HTTP/1.1 503 Service Unavailable
< content-length: 57
< content-type: text/plain
< date: Mon, 19 Nov 2018 14:31:54 GMT
< server: envoy
<
* Connection #0 to host httpbin.default.global left intact
upstream connect error or disconnect/reset before headers/ #
```
Then I check the code commit log, the Istio multi-cluster deployment with gateway should be broken by this PR: https://github.com/istio/istio/pull/9905

Also I check that `maser` branch also works fine while `release_1.1` branch is broken.
@rshriram Would you help to have a look at this?

**Expected behavior**
Istio multi-cluster deployment with ingress gateways should be working for latest daily build.

**Steps to reproduce the bug**
Get the latest Istio v1.1 daily build from https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/
Set up Istio multi-cluster deployment with ingress gateways following: https://preliminary.istio.io/docs/setup/kubernetes/multicluster-install/gateways/

Deploy the `sleep` application n cluster1 and `httpbin` on cluster2, create `serviceentry` on cluster1:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin-default
spec:
  hosts:
  # must be of form name.namespace.global
  - httpbin.default.global
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 8000
    protocol: http
  resolution: DNS
  addresses:
  - 127.255.0.2
  endpoints:
  - address: 9.111.254.158
    network: external
    ports:
      http: 15443 # Do not change this port value
  - address: istio-egressgateway.istio-system.svc.cluster.local
    ports:
      http: 15443
```

Then access the `httpbin` service on cluster2 from `sleep` pod on cluster1 by 
```
curl -v http://httpbin.default.global:8000
```

**Version**
```
root@xaubt1:~/istio-release-1.1-20181120-09-15# ./bin/istioctl version
version.BuildInfo{Version:"release-1.1-20181120-09-15", GitRevision:"e8bccd2e9bfe18d86becb795a8b8278275010336", User:"root", Host:"713a38b1c4f8", GolangVersion:"go1.10.4", DockerHub:"gcr.io/istio-release", BuildStatus:"Clean"}
root@xaubt1:~/istio-release-1.1-20181120-09-15# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3+icp-ee", GitCommit:"5f4327948913b3c0bd330cae0e5bf7cf09d1f0ae", GitTreeState:"clean", BuildDate:"2018-09-21T05:53:39Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3+icp-ee", GitCommit:"5f4327948913b3c0bd330cae0e5bf7cf09d1f0ae", GitTreeState:"clean", BuildDate:"2018-09-21T05:53:39Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
https://preliminary.istio.io/docs/setup/kubernetes/multicluster-install/gateways/

/cc @gyliu513 @clyang82
