### ISSUE TITLE
Read error on TCP connections causing Postgres to drop connections

### ISSUE THREAD

**Issue by ckousik** [istio/istio#10101]
**Describe the bug**
Connections to Postgres (TCP) are failing with `handshake error: 5` with mTLS enabled and `read error: 11` without mTLS. However any modification to Istio configuration (eg. Changing max number of connections to 200 from 201 in the DestinationRule) seems to fix the problem many times (sometimes this fails too). 

**Expected behavior**
All connections to the Postgres service work.

**Steps to reproduce the bug**
Apply the following YAML to an Istio enabled cluster
```yaml
# Client
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-ping
  labels:
    app: pg-ping
spec:
  replicas: 5
  selector:
    matchLabels:
      app: pg-ping
  template:
    metadata:
      name: pg-ping
      labels:
        app: pg-ping
    spec:
      containers:
      - name: pg-ping
        image: postgres:9.6.2
        command: ["bin/sh", "-c", "set -e; while true; do pg_isready -h postgres -p 5432; sleep 2; done;"]
      initContainers:
      - name: wait
        image: groundnuty/k8s-wait-for:0.1
        args:
        - "pod"
        - "-lapp=postgres"
---
# Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: "postgres:9.6.2"
        ports:
        - containerPort: 5432
          name: tcp-postgres
        readinessProbe:
          exec:
            command:
            - pg_isready
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - port: 5432
    name: tcp-postgres
    targetPort: tcp-postgres
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: postgres-rule
spec:
  host: postgres.ckousik.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 201
        connectTimeout: 300ms
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wait-rbac
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ckousik
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
```
The problem persists in the following conditions too:
1. DestinationRule is removed
2. Postgres is external to the Istio mesh
3. Number of `pg_ping` pods is increased or decreased
4. Postgres service is headless

**Version**
Istio: 1.0.4 and 1.0.3
Kubernetes: 1.10 EKS

**Installation**
Helm chart
```
helm install install/kubernetes/helm/istio --name istio --namespace istio-system \
--set grafana.enabled=true \
--set servicegraph.enabled=true \
--set kiali.enabled=true \
--set tracing.enabled=true
```
**Environment**
EKS, GKE

**Cluster state**
[istio-dump.tar.gz](https://github.com/istio/istio/files/2608333/istio-dump.tar.gz)
