### ISSUE TITLE
Websocket HTTP error 400

### ISSUE THREAD

**Issue by Paic** [istio/istio#10114]
I have a NodeJS application serving non-TLS websocket but I cannot get it to work since injection of the sidecar. mTLS is disabled in the whole cluster but enabled for specific services using `DestinationRule` and a `Policy` (the websocket service has mTLS enabled).

I'm getting an HTTP error 400 on the `Upgrade: websocket` request.

Gateway:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - '*'
```

VirtualService:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-endpoint
spec:
  hosts:
  - my-endpoint.com
  gateways:
  - my-gateway
  http:
  - match:
    - uri:
        prefix: /socket.io
    route:
      - destination:
          host: svc-websocket.default.svc.cluster.local
  - route:
    - destination:
        host: svc-endpoint.default.svc.cluster.local
```

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-websocket
spec:
  hosts:
  - svc-websocket.default.svc.cluster.local
  http:
  - route:
    - destination:
        host: svc-websocket.default.svc.cluster.local
    websocketUpgrade: true
```

I can provide logs of proxies if needed.

**Comment by ymesika** [comment]
Can you see if https://github.com/istio/istio/issues/9152 helps?

**Comment by Paic** [comment]
I'm not quite sure how to adapt this to my case. Does this looks ok ?

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: ws-serviceentry
spec:
  hosts:
  - my-endpoint.com
  ports:
  - name: http
    number: 80
    protocol: HTTP
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ws-gateway
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      name: http
      number: 80
      protocol: HTTP
    hosts:
    - my-endpoint.com
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ws-destination-rule
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: ws
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 80
        tls:
          mode: ISTIO_MUTUAL
          sni: my-endpoint.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ws-virtual-service
spec:
  hosts:
  - my-endpoint.com
  gateways:
  - ws-gateway
  - mesh
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: ws
        port:
          number: 80
      weight: 100
  - match:
    - gateways:
      - ws-gateway
      port: 80
    route:
    - destination:
        host: my-endpoint.com
        port:
          number: 80
      weight: 100
    websocketUpgrade: true
```
