### ISSUE TITLE
Validation for HTTPRoute header name is validating header value

### ISSUE THREAD

**Issue by itaysk** [istio/istio#10118]
**Describe the bug**
Validation for HTTPRoute's `AppendRequestHeaders` and `AppendResponseHeaders` is wrong. It validates the header value instead of the name.
I'll send a PR soon to fix this.

**Expected behavior**
Validating a Header map will make sure the header name is not empty.

**Steps to reproduce the bug**
`istioctl validate` fails this model:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews-route
spec:
  hosts:
  - reviews.prod.svc.cluster.local
  http:
  - route:
    - destination:
        host: reviews.prod.svc.cluster.local
        subset: v1
    appendRequestHeaders:
      "name": ""
```

While this one succeed:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews-route
spec:
  hosts:
  - reviews.prod.svc.cluster.local
  http:
  - route:
    - destination:
        host: reviews.prod.svc.cluster.local
        subset: v1
    appendRequestHeaders:
      "": "value"
```

**Version**
on master, commit: dce455456d77ca5af34ba5848f9704577349c6bd
