### ISSUE TITLE
Prometheus Operator Installation with Istio

### ISSUE THREAD

**Issue by RaymondArias** [istio/istio#10134]
**Describe the feature request**
Have the ability to install Prometheus Operator Helm Chart with Istio Helm installation.
Prometheus Operator has many features that are easier to work with than the vanilla Prometheus that gets installed with Istio and it would be nice to leverage these features. Service monitors for integrating custom works

**Describe alternatives you've considered**
Integrating Istio and Mixer metrics into Prometheus Operator. While this solution does work it would beneficial with having Istio and Prometheus Operator in one installation/helm chart.

**Additional context**
N/A

**Comment by hd-deman** [comment]
Absolutely agree. This is a huge problem for me too. Currently I have two kubernetes setup because merging istio provided prometheus and prometheus operator is really painful.

**Comment by nixgadget** [comment]
This is the very reason why I have a custom Helm setup for Istio so I can remove all the bloat like grafana and prometheus and instead manage all of that in the operator. Doing so comes with its own problems such as having to manage the config and versions but it seems to be working well for me so far.

**Comment by hd-deman** [comment]
@nixgadget can you share your approach?

**Comment by nixgadget** [comment]
@hd-deman 
- I simply stripped prometheus, grafana and zipkin charts and moved them to external charts. 
- Promtheus and grafana are all part of prometheus-operator.
- And I've defined `ServiceMonitor` config like below,
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "exporter-istio.fullname" . }}-pilot
spec:
  jobLabel: component
  selector:
    matchLabels:
      istio: pilot
  namespaceSelector:
    matchNames:
      - istio-system
  endpoints:
  - port: http-monitoring
    interval: 5s
```
- Unfortunately envoy prometheus could not converted to a `ServiceMonitor` as it doesnt have a concept of scraping metrics from every pod. So I used external scraping config in prometheus-operator instead.
