### ISSUE TITLE
Recently added scrape of envoy generates quite a lot of network traffic

### ISSUE THREAD

**Issue by Stono** [istio/istio#10193]
The switch from the statsd exporter, to prometheus scraping envoy for metrics directly creates quite a jump in network traffic for us:

<img width="894" alt="screen shot 2018-11-29 at 11 29 47" src="https://user-images.githubusercontent.com/1486729/49224034-47ed0000-f3d8-11e8-85e7-880591668068.png">

We're actually only interested in a handful of metrics from envoy, but a typical envoy returns a whole load of data.

The problem with the current setup of dropping metrics in prometheus:

```
      metric_relabel_configs:
      # Exclude some of the envoy metrics that have massive cardinality
      # This list may need to be pruned further moving forward, as informed
      # by performance and scalability testing.
      - source_labels: [ cluster_name ]
        regex: '(outbound|inbound|prometheus_stats).*'
        action: drop
      - source_labels: [ tcp_prefix ]
        regex: '(outbound|inbound|prometheus_stats).*'
        action: drop
      - source_labels: [ listener_address ]
        regex: '(.+)'
        action: drop
      - source_labels: [ http_conn_manager_listener_prefix ]
        regex: '(.+)'
        action: drop
      - source_labels: [ http_conn_manager_prefix ]
        regex: '(.+)'
        action: drop
      - source_labels: [ __name__ ]
        regex: 'envoy_tls.*'
        action: drop
      - source_labels: [ __name__ ]
        regex: 'envoy_tcp_downstream.*'
        action: drop
      - source_labels: [ __name__ ]
        regex: 'envoy_http_(stats|admin).*'
        action: drop
      - source_labels: [ __name__ ]
        regex: 'envoy_cluster_(lb|retry|bind|internal|max|original).*'
        action: drop
```

Is that you still scrape the entire envoy metric set before it is dropped (hence the large amount of network traffic).

Thinking about scale, the cluster in question has around 210 envoys but we'll eventually get to circa 800 so we're 200mbps for what is actually a small amount of metrics.  As we run in multiple availability zones so that will equate to quite a bit of cross zone egress charges for us too (another example for https://github.com/istio/istio/issues/4481).

Digging into envoy a little, it doesn't look as if they support any sort of filter query on their `/metrics` endpoint.  I suppose this could be added to envoy, but perhaps this could be resolved sooner by doing something in istio-proxy? 

For the time being, we're going to disable the envoy scraping (thus losing some visibility).

Thoughts?
