### ISSUE TITLE
Istio ingress static IP support for GCP

### ISSUE THREAD

**Issue by charlesverdad** [istio/istio#1024]
After applying this ingress resource in a GKE cluster,
```yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: static-ip
  # Assumes a global static ip with the same name exists.
  # You can acquire a static IP by running
  # gcloud compute addresses create test-ip --global
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "test-ip"
    kubernetes.io/ingress.class: "istio"
spec:
  tls:
  # This assumes istio-ingress-certs exist with tls.key and tls.crt
  - secretName: istio-ingress-certs 
  backend:
    # This assumes http-svc exists and routes to healthy endpoints.
    serviceName: http-svc
    servicePort: 80
```
The address returned by `kubectl get ing static-ip` seem to depend on the ephemeral external ip of the `istio-ingress` service but is different from the gcloud provisioned `test-ip`. My expected behavior is for the ingress controller to use the global-static-ip-name test-ip.

**Comment by linsun** [comment]
@ayj this is a GCP issue, can you comment?

**Comment by ayj** [comment]
`kubernetes.io/ingress.global-static-ip-name` is not supported by Istio ingress controller.

**Comment by ldemailly** [comment]
do we plan on addressing this ? how do people expose GKE services ?

**Comment by vaikas-google** [comment]
Are there workarounds for this? Seems pretty limiting to not be able to use static IP with Istio ingress.

**Comment by ldemailly** [comment]
@vaikas-google the work around is to go in the cloud management UI and switch the ip from `ephemeral` to `static` after the ingress is up

for instance:
![screen shot 2018-02-22 at 6 09 21 pm](https://user-images.githubusercontent.com/3664595/36574666-a9693d4e-17fb-11e8-8a79-af87d8a8a19c.png)

**Comment by vaikas-google** [comment]
Aha, ok, thanks!

**Comment by costinm** [comment]
Can we also add the kubernetes.io/ingress.global-static-ip-name ? ( in the
helm templates, where
it can be set in values.yaml ). Probably P2 since we have a workaround -
which should be documented.

**Comment by ldemailly** [comment]
We need to support it before we add it, no?

**Comment by denseidel** [comment]
Am I correct that this workaround only allows to make the ip static but there is no way to attach this static ip address to an existing cluster (e.g. starting a new cluster, attaching the the static ip of the ingress of the old cluster to the ingress of the new cluster, then deleting the old cluster)? Or does the workaround allow for this too?

**Comment by ilyasotkov** [comment]
@denseidel Not sure if that what you're asking, but if you just want to attach an existing (regional) static IP address to your istio-ingress, you can add `spec.loadBalancerIP` to your `istio-ingress` service. More info in Kubernetes docs: https://kubernetes.io/docs/concepts/services-networking/service/#type-loadbalancer

If you use the Helm chart to deploy Istio, these are the changes that are needed to be made (link to  a commit in my fork of the Istio Helm chart): https://github.com/exekube/charts/commit/5fc335371bf799b795cf0547b3504fb4626d24b3

@ldemailly should I submit a PR with the changes to the Helm chart? The feature is very useful for having an ephemeral cluster with a permanent static IP address (and permanent DNS records for it).

**Comment by ldemailly** [comment]
Yes please!

**Comment by ilyasotkov** [comment]
https://github.com/istio/istio/pull/4955 has been merged ✅

You can now reserve a *regional* static IP address (https://cloud.google.com/compute/docs/ip-addresses/reserve-static-external-ip-address), then bind it to Istio ingress service like this:

```yaml
# values.yaml
ingress:
  enabled: true
  ...
  service:
    loadBalancerIP: 130.211.160.207 # (your static IP address)
```
