### ISSUE TITLE
Packets between ingressgateway and backend service can not be decoded as http packets

### ISSUE THREAD

**Issue by lubinson** [istio/istio#10246]
Could you please open another issue with your full configuration? Additional question - do you experience the problem for the traffic from the gateway to your service, or also for the traffic from some pod to your service?

_Originally posted by @vadimeisenbergibm in https://github.com/_render_node/MDU6SXNzdWUzNTE2MjI2NTQ=/issues/unread_timeline#issuecomment-443783351_

**Comment by lubinson** [comment]
**Describe the bug**
The tcp packets between ingressgateway and backend service can not be decoded as http or http2 (clear text) packet after change the backend service port name to http, http2 or prefix with http- or http2-. My originate test is using http2(clear text), but failed to decode, then I switch to http 1.1 still the same.

**Expected behavior**
should be decoded successfully.

**Steps to reproduce the bug**
1, deploy my backend service successfully and can be accessed ok with directly call. Dump the packets using wiresharek to make sure http or http2 message are decoded successfully in wireshark. All content are clear text inside.

2, Then setup sidecar, etc.
3, add gateway as below
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: myservice-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http-api
      protocol: http
    hosts:
    - "*"
```
4, add virtual service 
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: myservice
spec:
  hosts:
  - "*"
  gateways:
  - myservice-gateway
  http:
  - match:
    - uri:
        exact: /account
    route:
    - destination:
        host: myservice
        port:
          number: 8080
```
5, backend service yaml snippet
```
spec:
  type: NodePort
  ports:
  - name: https
    port: 8443
    nodePort: 8443
    targetPort: 8443
  - name: http-api
    port: 8080
    nodePort: 8080
    targetPort: 8080  
```
6, send message and dump the port 8080

The request message is successfully processed and responed. But the packets can not be decoded as http or http2. As the page https://istio.io/docs/setup/kubernetes/spec-requirements/ describes the plain tcp will be used if no specific port name are defined. But I followed this page to define the name. The packets still looks like plain tcp. 

Just failed to upload the packets snapshot. ~~

**Version**
_What version of istio and Kubernetes are you using? Use `istioctl version` and `kubectl version`_
istioctl version
```
Version: 1.0.0
GitRevision: 3a136c90ec5e308f236e0d7ebb5c4c5e405217f4
User: root@71a9470ea93c
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

```
kubectl version
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Thanks.
