### ISSUE TITLE
"unknow attribute destination.port " when creating a grpc adaptor

### ISSUE THREAD

**Issue by wansuiye** [istio/istio#10267]
**Describe the bug**
{{ Succinctly describe the bug }}
when creating a grpc adaptor, it reports error "destination.port" attribute unknow, however i can find it from the wiki and the helm/mix/template/config.yaml, so if the attribute is available？
the config as below and other attributes are available.

```
apiVersion: "config.istio.io/v1alpha2"
kind: tracespan
metadata:
  name: default
  namespace: istio-system
spec:
  traceId: request.headers["x-b3-traceid"] | ""
  spanId: request.headers["x-b3-spanid"] | ""
  parentSpanId: request.headers["x-b3-parentspanid"] | ""
  spanName: request.path | "/"
  startTime: request.time
  endTime: response.time
  httpStatusCode: response.code | 0
  spanTags:
    http.host: request.host | ""
    http.method: request.method | ""
    http.path: request.path | ""
    http.user_agent: request.useragent | ""
    protocol: api.protocol | "unknown"
    principal: request.auth.principal | "unknown"
    request.size: request.size | 0
    response.size: response.size | 0
    source.ip: source.ip | ip("0.0.0.0")
    source.service: source.service | "unknown"
    source.version: source.labels["version"] | "unknown"
    destination.ip: destination.ip | ip("0.0.0.0")
    destination.service: destination.service | "unknow"
    destination.port: destination.port | 0
```
**Expected behavior**
{{ What did you expect to happen? }}
no error

**Steps to reproduce the bug**
{{ Minimal steps to reproduce the behavior }}

**Version**
{{ What version of Istio and Kubernetes are you using? Use `istioctl version` and `kubectl version` }}
istio : 1.0.4

**Installation**
{{ Please describe how Istio was installed }}

**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}
