### ISSUE TITLE
Intelligent Routing through ingress gateway

### ISSUE THREAD

**Issue by ChenLingPeng** [istio/istio#10264]
**Describe the feature request**
requests from outside through ingressgateway should have the ability to configure the service backend version

**Describe alternatives you've considered**
In the bookinfo example, I want to expose the `reviews` service and configure destinations based on some rule. But it seems not support.

## first try: 

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bookinfo-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - "*"
  gateways:
  - bookinfo-gateway
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: 9080
  - match:
    - uri:
        exact: /reviews/1
    route:
    - destination:
        host: reviews
        port:
          number: 9080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
  - reviews
  http:
  - route:
    - destination:
        host: reviews
        subset: v3
```

when I visit reviews through `${INGRESS_GATEWAY}/reviews/1`, response from v1/v2 also comes

## second try

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - "*"
  gateways:
  - bookinfo-gateway
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: 9080
  - match:
    - uri:
        exact: /reviews/1
    route:
    - destination:
        host: reviews
        subnet: v3
        port:
          number: 9080
```
`kubectl apply` fails with `unknown field "subnet" in v1alpha3.Destination`

So, what should I do if I want route my reviews request to just v3 version through ingress gateway?

**Additional context**
{{ Add any other context about the feature request here }}
