### ISSUE TITLE
Routing TCP traffic to egress gateway with DNS resolution

### ISSUE THREAD

**Issue by jcetkov** [istio/istio#10277]
Consider a scenario: 
An application needs to access external service via TCP, where the hostname configured in the application is difficult to change and routing via egress gateway is desired.

There are multiple services accessed from within the cluster using the same port, so the `addresses` field of the `ServiceEntry` needs to be populated.

Following the guide https://preliminary.istio.io/blog/2018/egress-mongo/

Since the client uses hostname in the configuration, but the service entry has the `addresses` hardcoded, if the DNS resolution (outside of k8s) changes, the record becomes invalid.

Possible workaround:
spoof dns record in the pod, to resolve in virtual Ip address, which is then used in the service entry to match the rule so the traffic can be intercepted by a VirtualService rule.

It would be nice to have more systematic control of the DNS in cluster vs. on the edge (egress-gateway), so that the configuration explicitly defines a hostname is resolved to a virtual IP address for the istio-proxy/mesh while uses external DNS for the egress-gateway.

**Comment by vadimeisenbergibm** [comment]
@jcetkov Just to be sure - you are using TCP without TLS and SNI? My guess is that most calls to external services have to be over TLS anyway, so the section https://preliminary.istio.io/blog/2018/egress-mongo/#egress-control-for-tls would be more relevant than just TCP control.

**Comment by jcetkov** [comment]
@vadimeisenbergibm the usecase was indeed TCP from the node (mysql protocol) tunneled via the TLS to the egress gateway. I think this applies to any non HTTP/HTTPS traffic to the egress gateway, since there is no field to preserve the original routing.

**Comment by jcetkov** [comment]
@vadimeisenbergibm that's what I did, between the mesh and the egress-gateway, however if I have 22 distinct mysql instances that I need to distinguish, the original rewrite rule before the TLS SNI gets in the picture needs to be IP address based, as nothing else is available

**Comment by vadimeisenbergibm** [comment]
@jcetkov I do not understand why you need IP-address-based routing. Consider https://preliminary.istio.io/blog/2018/egress-mongo/#direct-tls-egress-traffic-through-an-egress-gateway. Instead of `$MONGODB_HOST`, you just specify multiple mysql instances; you will have to specify multiple matches in the following section:
```
- match:
    - gateways:
      - istio-egressgateway
      port: 443
      sni_hosts:
      - mysql_host1
    route:
    - destination:
        host: mysql_host1
        port:
          number: mysql_port
      weight: 100
    - gateways:
      - istio-egressgateway
      port: 443
      sni_hosts:
      - mysql_host2
    route:
    - destination:
        host: mysql_host2
        port:
          number: mysql_port
      weight: 100
```
