### ISSUE TITLE
Unexpected caching behaviour for OOP adapter

### ISSUE THREAD

**Issue by PhilipGough** [istio/istio#10294]
**Describe the bug**

This may not be a bug but the behaviour is not as I would expect. We are working on an OOP adapter which supports the default [Authorization template](https://istio.io/docs/reference/config/policy-and-telemetry/templates/authorization/).

Within the adapter, to return a successful  `CheckResult`, the user must provide an `api_key` as query param or header. If auth against the backend is approved and the `CheckResult` returned with a status code of 0 and some values set for caching, then the proceeding x amount of calls over some period will not hit the handler as expected.

What is not expected however is that the caching does not take into account the source ip, so essentially the window is open for any client to make a successful request within this time period.

**Expected behaviour**
Expected cached calls to be filtered per source ip at least and perhaps based on query params and/or headers

**Version**
1.0.2

**Installation**
Via https://github.com/Maistra/openshift-ansible

**Environment**
OpenShift 3.11

**Comment by douglas-reid** [comment]
Do the instance configs in your test use `source.ip` as an expression?

Can you post your instance config here?

**Comment by PhilipGough** [comment]
Hey @douglas-reid, I have tried with both the following:

```yaml
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
  name: threescale-authorization
  namespace: istio-system
spec:
  template: authorization
  params:
    subject:
      user: request.api_key | request.headers["api-key"] | ""
    action:
      path: request.path | "/"
      method: request.method | "get"
```
This hits the handler as expected but doesn't reference the source ip so it is not going to produce the desired behaviour right?

Now adding an arbitrary reference in the properties causes the handler not to be reached:
```yaml
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
  name: threescale-authorization
  namespace: istio-system
spec:
  template: authorization
  params:
    subject:
      user: request.api_key | request.headers["api-key"] | ""
      properties:
        client_ip: source.ip | ip("0.0.0.0")
    action:
      path: request.path | "/"
      method: request.method | "get"
```

Any suggestions as to what I'm doing wrong? Also I am wondering if this is an external request that comes through the ingress gateway, will the `source.ip` be set to the gateway pod ip for each request regardless?
