### ISSUE TITLE
used TCP connect DNS, when I ping a service, reture "unknown host"

### ISSUE THREAD

**Issue by jinjie2088** [istio/istio#10310]
**Describe the bug**
 add dnsConfig in deployment:
dnsConfig:
        options:
          - name: use-vc
the resolv.conf in pod
[root@status-monitor-587995bb44-d4rlp /]# cat /etc/resolv.conf
nameserver 10.96.0.10
search star.svc.cluster.local svc.cluster.local cluster.local
options ndots:5 use-vc

**used istio inject, can not resolve service name**
eg:
[root@status-monitor-587995bb44-d4rlp /]# ping partner-service
ping: unknown host partner-service

**partner-service**: a service in k8s cluster

**Steps to reproduce the bug**
1.  add dnsConfig in deployment yaml:
dnsConfig:
        options:
          - name: use-vc
2. kubectl apply -f <(istioctl kube-inject -f $yaml_file)

**Version**
1.0.4

**Installation**
kubectl apply -f istio-demo.yaml

**Environment**
k8s 1.10.10 + istio1.0.4

**Comment by Waret** [comment]
Do you have enabled IPv6 in your k8s cluster?

**Comment by jinjie2088** [comment]
> Do you have enabled IPv6 in your k8s cluster?

no

**Comment by Stono** [comment]
Hey
I had this when my DNS queries were too large for udp.

Do you have mTLS enabled?  If so you need a destinstionrule which disabled mTLS for the DNS service.

**Comment by jinjie2088** [comment]
> Hey
> I had this when my DNS queries were too large for udp.
> 
> Do you have mTLS enabled? If so you need a destinstionrule which disabled mTLS for the DNS service.
thank you for your reply.

I donn't enable mTLS, i add a ServiceEntry. And it  is strange for under phenomenons。
 begin, not work -> apply the ServiceEntry ->work ->hold a few minutes->not work->delete 
 the ServiceEntry ->work->hold a few minutes->not work ........

**the ServiceEntry:**

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: dns-over-tcp
  namespace: stariboss
spec:
  hosts:
  - '*.svc.cluster.local'
  addresses:
  - 10.96.0.10
  ports:
  - number: 53
    name: tcp
    protocol: TCP
  resolution: STATIC
  endpoints:
  - address: 10.96.0.10
```
