### ISSUE TITLE
 How to filter liveness request form kiali

### ISSUE THREAD

**Issue by Liv1020** [istio/istio#10336]
**Describe the bug**
![image](https://user-images.githubusercontent.com/5382358/49637940-b7e73000-fa41-11e8-972f-1786c9569b5c.png)
This unknow service is liveness, how to filter it?

**Expected behavior**
undisplay it from kiali

**Steps to reproduce the bug**
add http liveness

**Version**
```
Version: 1.0.4
GitRevision: d5cb99f479ad9da88eebb8bb3637b17c323bc50b
User: root@8c2feba0b568
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean
```
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:18:13Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
helm

**Environment**
Centos

**Cluster state**

**Comment by ChristofferNicklassonLenswayGroup** [comment]
As far as i know  that is stored by istio and Kiali only displays what Istio have saved. 
I pinged the developers of Kiali about this.

**Comment by Liv1020** [comment]
> As far as i know that is stored by istio and Kiali only displays what Istio have saved.
> I pinged the developers of Kiali about this.

How to fix it?

**Comment by flunderveiko** [comment]
don't use `port -> containerPort` directive in k8s deployment/Pod

**Comment by Liv1020** [comment]
> don't use `port -> containerPort` directive in k8s deployment/Pod

If you don't use `port -> containerPort`, it will cause jaeger don't trace inbound problems.

**Comment by flunderveiko** [comment]
i changed the match spec `rule` resource named `promhttp` in namespace `istio-system`
`context.protocol == "http" || context.protocol == "grpc"`
`(context.protocol == "http" || context.protocol == "grpc") && ( request.path != "/healthz")`

cause i use /healthz for my livenessProbe

**Comment by Liv1020** [comment]
> i changed the match spec `rule` resource named `promhttp` in namespace `istio-system`
> `context.protocol == "http" || context.protocol == "grpc"`
> `(context.protocol == "http" || context.protocol == "grpc") && ( request.path != "/healthz")`
> 
> cause i use /healthz for my livenessProbe

I use this yaml to fix it, it's more general
```
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: promhttp
  namespace: istio-system
spec:
  match: (context.protocol == "http" || context.protocol == "grpc") && ( match(request.useragent, "kube-probe*") == false )
  actions:
  - handler: handler.prometheus
    instances:
    - requestcount.metric
    - requestduration.metric
    - requestsize.metric
    - responsesize.metric
```

**Comment by jotak** [comment]
So if having `match: (context.protocol == "http" || context.protocol == "grpc") && match(request.useragent | "", "kube-probe*") == false` in promhttp sounds good, maybe it could come as a default in istio templates for kubernetes? What do you think?

**Comment by douglas-reid** [comment]
@jotak +1 to your suggestion. If you feel up to it, please send a PR my way. Otherwise, I'll get to it when I next am at a computer.

**Comment by Liv1020** [comment]
@jotak +1

**Comment by anthonyhaussman** [comment]
Seems that the patch does not work on GKE.
The probe does not return kube-probe as user-agent:
```
test-health-5c97cfdfbb-lwbg6 istio-proxy [2019-03-27T13:18:25.386Z] "- - -" 0 - "-" 119 181 0 - "-" "-" "-" "-" "127.0.0.1:8080" inbound|8080||test-health.default.svc.cluster.local 127.0.0.1:57026 10.0.16.45:8080 10.0.16.1:37926 -
```
It still show the `http liveness` unknown icon.
My promhttp configuration:
```
```

**Comment by Liv1020** [comment]
you can set test-health

**Comment by Liv1020** [comment]
@anthonyhaussman you use tcp liveness?

**Comment by anthonyhaussman** [comment]
@Liv1020 I use HTTP liveness:
```
...
    spec:
      containers:
      - image: infrastructureascode/hello-world
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: test-health
        ports:
        - containerPort: 8080
          protocol: TCP 
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
...
```

**Comment by dbarentine** [comment]
This still doesn't seem to be fixed. I'm running Istio 1.1.5 and I have a service with a liveness check on the same port that still shows up as unknown in Kiali.

I checked the user-agent of the request and it's: kube-probe/1.12

The promhttp match rule looks like:
match: (context.protocol == "http" || context.protocol == "grpc") && (match((request.useragent
    | "-"), "kube-probe*") == false)

It doesn't seem to matter what I put in the match for promhttp. But when I remove the liveness check from my service the unknown traffic goes away.

**Comment by Liv1020** [comment]
> This still doesn't seem to be fixed. I'm running Istio 1.1.5 and I have a service with a liveness check on the same port that still shows up as unknown in Kiali.
> 
> I checked the user-agent of the request and it's: kube-probe/1.12
> 
> The promhttp match rule looks like:
> match: (context.protocol == "http" || context.protocol == "grpc") && (match((request.useragent
> | "-"), "kube-probe*") == false)
> 
> It doesn't seem to matter what I put in the match for promhttp. But when I remove the liveness check from my service the unknown traffic goes away.

Your liveness is http?

**Comment by Liv1020** [comment]
> @Liv1020 I use HTTP liveness:
> 
> ```
> ...
>     spec:
>       containers:
>       - image: infrastructureascode/hello-world
>         imagePullPolicy: Always
>         livenessProbe:
>           failureThreshold: 3
>           httpGet:
>             path: /health
>             port: 8080
>             scheme: HTTP
>           periodSeconds: 10
>           successThreshold: 1
>           timeoutSeconds: 1
>         name: test-health
>         ports:
>         - containerPort: 8080
>           protocol: TCP 
>         readinessProbe:
>           failureThreshold: 3
>           httpGet:
>             path: /health
>             port: 8080
>             scheme: HTTP
>           periodSeconds: 10
>           successThreshold: 1
>           timeoutSeconds: 1
> ...
> ```

What version about istio and k8s?

**Comment by Liv1020** [comment]
> kube-probe/1.12

I use istio 1.1.5 too, k8s is 1.13.5. I hasn't this problem, you can modify promhttp file to test

**Comment by dbarentine** [comment]
@Liv1020 I updated k8s to 1.13.5 and still have the problem. promhttp is correct as well and excludes kube-probe. But unknown traffic still appears in Kiali for liveness checks.

![UnknownIstio](https://user-images.githubusercontent.com/939865/57719052-b1ce2e80-7633-11e9-9c75-21e9354d19df.png)

**Comment by Liv1020** [comment]
@dbarentine Can you show connect-dev service 's istio-proxy log?

**Comment by dbarentine** [comment]
@Liv1020 This dump is from three days ago. I can pull a more recent version in the morning if you need.

[istio-dump.tar.gz](https://github.com/istio/istio/files/3189760/istio-dump.tar.gz)

**Comment by Liv1020** [comment]
@dbarentine istio-dump/logs/dev/connect-dev-699f55479f-qjgwz/istio-proxy.log not accesslog, please look https://istio.io/docs/tasks/telemetry/logs/access-log/#enable-envoy-s-access-logging enable

**Comment by dbarentine** [comment]
@Liv1020 I apologize for the delay but here are the access logs for a connect-dev instance.

[connect-dev.log](https://github.com/istio/istio/files/3203988/connect-dev.log)

**Comment by Liv1020** [comment]
mybe you use tcp health check 
![image](https://user-images.githubusercontent.com/5382358/58243862-13a13d80-7d84-11e9-80ff-97a25d990b72.png)

**Comment by dbarentine** [comment]
It's definitely an httpGet. I've tried it with and without the readinessProbe:
```
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        livenessProbe:
          httpGet:
            path: /heartbeat
            port: {{ .Values.resources.port }}
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /heartbeat
            port: {{ .Values.resources.port }}
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 60
```
