### ISSUE TITLE
only one rule take effect when two traffic rules on one request

### ISSUE THREAD

**Issue by aimuke** [istio/istio#10359]
**Describe the bug**
there are two traffic rules on one request, but only one takes effect

**Expected behavior**
I hope both of the two rules should take effect

**Steps to reproduce the bug**
I'm using bookinfo for test. below is my steps:

1. add forward route to details service 
 ````
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: details
spec:
  hosts:
  - details.default.svc.cluster.local
  http:
  - route:
    - destination:
        host: reviews.default.svc.cluster.local
````
2. add fault abort rule to reviews
````
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fault-abort-reviews
spec:
  hosts:
  - reviews.default.svc.cluster.local
  http:
  - fault:
      abort:
        httpStatus: 500
    route:
    - destination:
        host: reviews.default.svc.cluster.local
````
3. send a request from productpage service
  3.1 curl  http://reviews:9080/reviews/0    //  return 500 as expected
  3.2 curl http://details:9080/reviews/0      // return bookreviews info, not expected 500
 
 I hope 3.2 will return 500 error too. Or how should I set to achieve the purpose? thx.

**Version**
istio 1.0.0 
k8s 
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.2-rancher1", GitCommit:"386fc0481824878c3dacf830ec605776f112467e", GitTreeState:"clean", BuildDate:"2018-08-20T18:29:45Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Installation**
I used rancher to install a k8s environment, and installed istio and bookinfo follow offical documents.

**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}
