### ISSUE TITLE
gRPC retryOn is not working 

### ISSUE THREAD

**Issue by sakthishanmugam02** [istio/istio#10391]
**Describe the bug**
I am trying to configure retryOn policy with service unavailable; it is not retrying

I have 2 app; 
1st one exposes REST endpoint; on receiving request, it dials to gRPC server(2nd app) and post some request

my yaml configuration files for app and istio rules as below:
SERVICE 1:
```

// apiVersion: apps/v1
// kind: Deployment
// metadata:
  // name: app-one
  // namespace: default
// spec:
  // replicas: 1
  // minReadySeconds: 15
  // strategy:
    // type: RollingUpdate
    // rollingUpdate:
      // maxUnavailable: 1
      // maxSurge: 1
  // selector:
    // matchLabels:
      // app: app-one
  // template:
    // metadata:
      // labels:
        // app: app-one
    // spec:
      // containers:
        // - image: localhost:5000/app-one:1.1
          // imagePullPolicy: IfNotPresent
          // name: app-one
          // ports:
            // - containerPort: 8082
      // imagePullSecrets:
        // - name: regcred

// ---

// apiVersion: v1
// kind: Service
// metadata:
  // name: app-one-service
  // namespace: default
// spec:
  // type: LoadBalancer
  // ports:
  // - port: 8082
    // protocol: TCP
    // targetPort: 8082
    // name: http
  // selector:
    // app: app-one

```
SERVICE 2:
```

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-two
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: app-two
  template:
    metadata:
      labels:
        app: app-two
    spec:
      containers:
        - image: localhost:5000/app-two:1.1
          imagePullPolicy: IfNotPresent
          name: app-two
          ports:
            - containerPort: 50051
      imagePullSecrets:
        - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: app-two-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 50051
    name: grpc
  selector:
    app: app-two
```

ISTIO rules

```

// apiVersion: networking.istio.io/v1alpha3
// kind: Gateway
// metadata:
  // name: app-gateway
// spec:
  // selector:
    // istio: ingressgateway # use istio default controller
  // servers:
  // - port:
      // number: 80
      // name: http
      // protocol: HTTP
    // hosts:
    // - "*"
  // - port:
      // number: 9090
      // name: grpc
      // protocol: GRPC
    // hosts:
    // - "*"
// ---

// apiVersion: networking.istio.io/v1alpha3
// kind: VirtualService
// metadata:
  // name: apps-vs
// spec:
  // hosts:
  // - "*"
  // gateways:
  // - app-gateway
  // http:
  // - match:
    // - uri:
        // prefix: /rest-app
    // route:
    // - destination:
        // host: app-one-service
        // port:
          // number: 8082
  // - match:
    // - uri:
        // prefix: /helloworld.Greeter
    // route:
    // - destination:
        // host: app-two-service
        // port:
          // number: 50051
    // retries:
      // attempts: 3
      // perTryTimeout: 20s
      // retryOn: unavailable


```

**Expected behavior**
It should retry if the 2nd app (gRPC server is unavailable)

**Steps to reproduce the bug**
configure retryOn policy for gRPC server; and kill the pod; it will not retry for further request

**Version**
istioctl version
version.BuildInfo{Version:"1.1.0-snapshot.3", GitRevision:"e3653d5a8244c2f30e2e0600cb5af956a575bae1", User:"root", Host:"e34a3c8d4731", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

**Installation**
https://preliminary.istio.io/docs/setup/kubernetes/helm-install.html#option-2-install-with-helm-and-tiller-via-helm-install

**Environment**
ubuntu 16.04 on VM

**Cluster state**
-

**Comment by hzxuzhonghu** [comment]
This makes sure retry on will not happen to previously failed host.  @sakthishanmugam02 Would you help verify this?

https://github.com/istio/istio/blob/e3653d5a8244c2f30e2e0600cb5af956a575bae1/pilot/pkg/networking/core/v1alpha3/route/route.go#L547-L552

**Comment by sakthishanmugam02** [comment]
@hzxuzhonghu 
Could you please elaborate?  
> "This makes sure retry on will not happen to previously failed host."
My issue was it is not retrying, you mean to say. because of this check. it is not retrying?

**Comment by hzxuzhonghu** [comment]
Yeah

**Comment by sakthishanmugam02** [comment]
@hzxuzhonghu how to configure retry on grpc codes then?

**Comment by hzxuzhonghu** [comment]
Don't you have multi service instances ? Then configure as above seems work well. 
  
The reason why we set `envoy.retry_host_predicates.previous_hosts` is not to retry previous attempted host.
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http_connection_management.html?highlight=envoy%20retry_host_predicates%20previous_hosts

**Comment by sakthishanmugam02** [comment]
@hzxuzhonghu Is there any ways to unset this value. My use case is to retry irrespective of the previous failure attempt; 

**also one important thing here: it never retries in my case though it is freshly brought up.** (not even once).

**Comment by hzxuzhonghu** [comment]
There is no way to unset this.

**Comment by sakthishanmugam02** [comment]
@hzxuzhonghu as I mentioned, it is not even retried once? what could be the reason; as per this check, only for already failed host it will not retry right? in my case it never retries

**Comment by hzxuzhonghu** [comment]
Your virtualservice rule is not correct. You configure it for gateway.

**Comment by sakthishanmugam02** [comment]
@hzxuzhonghu Could you please help me to configure it properly?

**Comment by sakthishanmugam02** [comment]
@hzxuzhonghu now I have changed my vs configuration as below: still not working

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: apps-vs
spec:
  hosts:
  - "*"
  gateways:
  - app-gateway
  http:
  - match:
    - uri:
        prefix: /rest-app
    route:
    - destination:
        host: app-one-service
        port:
          number: 8082
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app-two-vs
spec:
  hosts:
  - app-two-service
  http:
  - match:
    - uri:
        prefix: /helloworld.Greeter
    route:
    - destination:
        host: app-two-service
        port:
          number: 50051
    retries:
      attempts: 3
      perTryTimeout: 20s
      retryOn: unavailable

```

**Comment by hzxuzhonghu** [comment]
I want to know how you simulate unavailable?

**Comment by hzxuzhonghu** [comment]
This is not right. If you do this, pilot will not generate outbound cluster for Service2.  Unless you can make sure the outbound configuration for Service 2 exist, and you are shutting down grpc server.

**Comment by sakthishanmugam02** [comment]
@hzxuzhonghu this situation can happen in real time also right?
app is getting crashed. how to handle the retry in this scenario

**Comment by hzxuzhonghu** [comment]
They are not same thing.  Keep in mind, pilot generate and dispatch configurations for only running pod. 
If a request shipped to a crashing pod, then envoy makes a retry on other healthy endpoints automatically .                                    
But firstly you have to simulate this scenario.

**Comment by elvizlai** [comment]
Friendly ping.

Is this issue solved? I also have same issue. Or should I open a new issue?

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: experimental-hack
  namespace: xxx-dev
spec:
  hosts:
    - "*"
  gateways:
    - istio-system/api-gateway
  http:
    - match:
        - uri:
            prefix: "/hack.ExperimentalService"
      route:
        - destination:
            host: experimental-hack
            port:
              number: 6443
      retries:
        attempts: 3
        perTryTimeout: 60s
        retryOn: unavailable
      corsPolicy:
        allowOrigin:
          - "*"
        allowMethods:
          - POST
          - GET
          - OPTIONS
          - PUT
          - DELETE
        allowHeaders:
          - grpc-timeout
          - content-type
          - keep-alive
          - user-agent
          - cache-control
          - content-type
          - content-transfer-encoding
          - custom-header-1
          - x-accept-content-transfer-encoding
          - x-accept-response-streaming
          - x-user-agent
          - x-grpc-web
          - x-auth-token
          - x-org
        maxAge: 24h
        exposeHeaders:
          - "*"
        allowCredentials: true
```

My hack server random generate code 14 Unavailable.

With this config, retry works for grpc-json-transcoder http, but NOT worked for grpc.

Here is service istio-proxy log for failed gRPC(x-request-id: c00cacfd-69bd-bde3-abf5-28645b51045b is failed)
```
[2019-10-29T02:38:49.614Z] "POST /hack.ExperimentalService/Ping HTTP/2" 200 - "-" "-" 5 43 1 0 "HIDDEN_IP" "grpc-go/1.24.0" "3113f87f-d719-b4d8-9b9a-51df0744b4ab" "t.xxx.com:443" "127.0.0.1:9999" inbound|6443|grpc-web|experimental-hack.xxx-dev.svc.cluster.local - 10.244.58.194:9999 HIDDEN_IP:0 -
[2019-10-29T02:38:54.628Z] "POST /hack.ExperimentalService/Ping HTTP/2" 200 - "-" "-" 5 0 1 0 "HIDDEN_IP" "grpc-go/1.24.0" "c00cacfd-69bd-bde3-abf5-28645b51045b" "t.xxx.com:443" "127.0.0.1:9999" inbound|6443|grpc-web|experimental-hack.xxx-dev.svc.cluster.local - 10.244.58.194:9999 HIDDEN_IP:0 -
[2019-10-29T02:38:59.690Z] "POST /hack.ExperimentalService/Ping HTTP/2" 200 - "-" "-" 5 43 1 0 "HIDDEN_IP" "grpc-go/1.24.0" "5bb77f90-f3f3-bdc3-9561-e0b873d5fb07" "t.xxx.com:443" "127.0.0.1:9999" inbound|6443|grpc-web|experimental-hack.xxx-dev.svc.cluster.local - 10.244.58.194:9999 HIDDEN_IP:0 -
```

And the log for curl request, retry works(x-request-id:46974df5-760f-4b86-8868-35df7bd52b45 is failed)
```
[2019-10-29T02:42:21.732Z] "POST /hack.ExperimentalService/Ping HTTP/2" 200 - "-" "-" 2 64 2 0 "HIDDEN_IP" "curl/7.64.1" "108bd38d-dbf1-4264-a966-58a41f1f07ce" "t.xxx.com" "127.0.0.1:9999" inbound|6443|grpc-web|experimental-hack.xxx-dev.svc.cluster.local - 10.244.58.194:9999 HIDDEN_IP:0 -
[2019-10-29T02:42:22.532Z] "POST /hack.ExperimentalService/Ping HTTP/2" 503 - "-" "-" 2 0 2 0 "HIDDEN_IP" "curl/7.64.1" "46974df5-760f-4b86-8868-35df7bd52b45" "t.xxx.com" "127.0.0.1:9999" inbound|6443|grpc-web|experimental-hack.xxx-dev.svc.cluster.local - 10.244.58.194:9999 HIDDEN_IP:0 -
[2019-10-29T02:42:22.553Z] "POST /hack.ExperimentalService/Ping HTTP/2" 200 - "-" "-" 2 64 1 0 "HIDDEN_IP" "curl/7.64.1" "46974df5-760f-4b86-8868-35df7bd52b45" "t.xxx.com" "127.0.0.1:9999" inbound|6443|grpc-web|experimental-hack.xxx-dev.svc.cluster.local - 10.244.58.194:9999 HIDDEN_IP:0 -
```
