### ISSUE TITLE
Routing to a wrong endpoint with multiple virtualservices for the same host, when the virtualservices have header rules.

### ISSUE THREAD

**Issue by dreadbird** [istio/istio#10485]
**Describe the bug**
I see a new feature：https://istio.io/help/ops/traffic-management/deploy-guidelines/#multiple-virtual-services-and-destination-rules-for-the-same-host
but when I match the header rules,the root path"/" will override the other rules.

**Expected behavior**
the virtualservices like these:
```apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: trident-web
  namespace: iop
spec:
  gateways:
  - default.istio-system.svc.cluster.local
  hosts:
  - multi-example.iop.com
  http:
  - match:
    - headers:
        cookie:
          regex: ^(.*\s*)?(canary)(.*)?$
      uri:
        prefix: /
    route:
    - destination:
        host: trident-web.iop.svc.cluster.local
        subset: canary
    timeout: 60s
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: trident-web.iop.svc.cluster.local
        subset: stable
    timeout: 60s
--------------------------
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cicd-api
  namespace: iop
spec:
  gateways:
  - default.istio-system.svc.cluster.local
  hosts:
  - multi-example.iop.com
  http:
  - match:
    - headers:
        cookie:
          regex: ^(.*\s*)?(canary)(.*)?$
      uri:
        prefix: /cicd
    route:
    - destination:
        host: cicd-api.iop.svc.cluster.local
        subset: canary
    timeout: 60s
  - match:
    - uri:
        prefix: /cicd
    route:
    - destination:
        host: cicd-api.iop.svc.cluster.local
        subset: stable
    timeout: 60s
```
and the svc:

```
apiVersion: v1
kind: Service
metadata:
  name: cicd-api
  namespace: iop
spec:
  ports:
  - name: http-cicd-apis
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    k8s-app: cicd-api
  type: ClusterIP
-----------------
apiVersion: v1
kind: Service
metadata:
  name: trident-web
  namespace: iop
spec:
  ports:
  - name: http-trident-web-pro
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    appinstance: trident-web
    application: trident-web
    user: cks
  type: ClusterIP
```

**Steps to reproduce the bug**
When I call the  url "http://multi-example.iop.com/cicd/core/v1/jenkins-env" from chrom with cookie witch has "roles=cannary", it should routing to the *cicd-api* service,
but I get 404 because the request was routed to the *trident-web* service,I find this at ingressgateway logs:
```
[2018-12-14T07:43:51.933Z] "GET /cicd/core/v1/jenkins-envHTTP/2" 404 - 0 571 8 0 "10.1.211.192" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36" "a0c33090-489c-9b1f-a2ac-730cd68895e2" "multi-example.iop.com" "10.1.101.6:80" outbound|8080|canary|trident-web.iop.svc.cluster.local - 10.1.75.6:443 10.1.211.192:55836

```

**Version**
istio version: v1.0.4
k8s version: v1.11.1+icp-ee

**Installation**
install istio with helm

**Environment**
ICP from IBM

**Comment by linsun** [comment]
@frankbu can you help check this out?

**Comment by frankbu** [comment]
This is working as designed. In the documentation it says `Although the order of evaluation for rules in any given source VirtualService will be retained, the cross-resource order is UNDEFINED. In other words, there is no guaranteed order of evaluation for rules across the fragment configurations, so it will only have predictable behavior if there are no conflicting rules or order dependency between rules across fragments.`.

The rules in this example do have order dependency. This rule:
```
  - match:
    - headers:
        cookie:
          regex: ^(.*\s*)?(canary)(.*)?$
      uri:
        prefix: /
    route:
    - destination:
        host: trident-web.iop.svc.cluster.local
        subset: canary
```
needs to be ordered after (i.e., lower priority) than these ones:
```
  http:
  - match:
    - headers:
        cookie:
          regex: ^(.*\s*)?(canary)(.*)?$
      uri:
        prefix: /cicd
    route:
    - destination:
        host: cicd-api.iop.svc.cluster.local
        subset: canary
    timeout: 60s
  - match:
    - uri:
        prefix: /cicd
    route:
    - destination:
        host: cicd-api.iop.svc.cluster.local
        subset: stable
    timeout: 60s
```
because any request to a uri starting with `/cicd` will also match rules for `prefix: /`.

To use this feature, there must be no overlapping conditions in the rules, or you will get UNDEFINED behavior, so even if you were lucky and it did work, there is no guarantee it will work in the future.

Btw, your second `/` rule:
```
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: trident-web.iop.svc.cluster.local
        subset: stable
    timeout: 60s
```
should work fine, because it is a "catch-all" rule which will automatically get moved to the end of the list in the merged configuration.
