### ISSUE TITLE
Istio with statefulsets

### ISSUE THREAD

**Issue by anargund1979** [istio/istio#10490]
I am trying deploy zookeeper/kafka/cassandra/ES, statefulsets (3 node cluster) with istio 
I am getting Handshake failure messages.
Can someone tell me whether its supported with or not ?
I have gone through number of issues but did not find solid answer.
https://github.com/istio/old_issues_repo/issues/28 says its supported.

**Comment by harryge00** [comment]
@anargund1979 Based on my understanding, whether the app is statefulset or deployment has little bussiness with Istio. Istio build xDS based on k8s service and Pod IP. So statefulset should also be supported. Maybe you used headless service or subdomain?

**Comment by anargund1979** [comment]
@harryge00 , thanks for the reply.
Yes, all these cluster have headless service for inter communication, this is e.g. for Zookeeper. 
```
apiVersion: v1
kind: Service
metadata:
  name: zk-hs
  labels:
    app: zk
spec:
  ports:
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: zk
```
