### ISSUE TITLE
Customized Error response in case of origin authentication failure 

### ISSUE THREAD

**Issue by ahmadsayed** [istio/istio#10543]
**Describe the feature request**
Using istio rbac, when the token is not valid, Istio proxy returns HTTP status 401 Unauthorized, in the body it returns **Origin authentication failed** in plain/text, but in some cases we need a customized message that is aligned with the API specification we provide to the our API client, ideally http status 401 and body in JSON format, similar to other response we generate from application side

**Describe alternatives you've considered**
I thought about capture this request in kubernetes ingress and replace the body but still not sure if this is even doable

**Comment by kyessenov** [comment]
You might want to reuse https://github.com/istio/api/blob/master/policy/v1beta1/http_response.proto#L23
This proto is meant to be packed into RPC status error details, and is picked up by Mixer from external adapters.

**Comment by cagataygurturk** [comment]
Have the same request. This is not only for this message but we'd like to have a way of customising all error messages Istio is sending to client.

**Comment by gabel** [comment]
@ahmadsayed @cagataygurturk Did you solve this? I'd like to have a custom response (json custom format) as well.

**Comment by ahmadsayed** [comment]
@gabel  Not really, we lived with it, not optimum unfortunately

**Comment by joebertj** [comment]
My use case is when the user tries to directly access a URI protected by a Policy. I would like it redirected to the login page.

**Comment by x4d3** [comment]
We have the same request.

**Comment by gabel** [comment]
To fully customize the errors one might need a custom error backend that handles the response?

**Comment by bogiva** [comment]
Why was this issue closed without a solution?
We have to now stop using Istio because we cannot customize the response and we have a hard requirement to return application/json for example...

**Comment by despondency** [comment]
Shamelessly reopening the issue, it would be great if you can manipulate the error response when an authentication failure happens. It could be as easy as having a callback url configured which creates a json/or any response and returns it to the proxy which in turn returns it to the client. 

What do you guys think?

**Comment by bogiva** [comment]
@despondency 
> having a callback

Sounds fine for greater flexibility, but I would also love to have the chance to define a static (customized) response as callback might be an overhead in some situations.

**Comment by felipegirotti** [comment]
Maybe this could be useful, you need to implement one service more to validate the jwt  and write the `EnvoyFilter`, that way you can have flexibility to respond json/html and redirect.
Sounds like workaround than the definitivity solution, but works.
https://medium.com/@csaba.ujvari/custom-request-authorization-with-istio-1-5-envoyfilter-b43c728ecfa4

**Comment by polavishnu4444** [comment]
Hi,
We are awaiting for this feature as well.

**Comment by msonnleitner** [comment]
This is certainly a must-have feature in many settings, if the response is exposed to API consumers. Please reopen.

**Comment by shadiramadan** [comment]
I just switched JWT auth from my app to Istio and was confused when my app broke- it was expecting a json response and thus failed to parse.  Would definitely be useful if we could just pass in the error message via configuration.

**Comment by daniellmorris** [comment]
Can we reopen this? This would be a super valuable piece. I can't quite figure out why it isn't implemented already.

**Comment by bburky** [comment]
Would Envoy's local reply modification allow customizing these error messages?

https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/local_reply

I'm not sure where I would configure it in istio though. (It's not a filter, I'm not sure if EnvoyFilters work. Maybe though.)

**Comment by yangminzhu** [comment]
Reopening the issue for more discussions.

**Comment by lenalebt** [comment]
Hey, I'm also very interested in this feature - or about current possible workarounds. @bburky did you get it to work with istio local reply? I'm also unsure how to configure this in istio, and would be interested in a workaround that would currently work.

**Comment by yangminzhu** [comment]
> Hey, I'm also very interested in this feature - or about current possible workarounds. @bburky did you get it to work with istio local reply? I'm also unsure how to configure this in istio, and would be interested in a workaround that would currently work.

For now you can use the following workaround, you can change `403` to `401` to make it work for JWT authentication fail response:

```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: customize-authz-response
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          local_reply_config:
            mappers:
            - filter:
                # Better to use the metadata_filter to only match the 403 returned by RBAC filter instead of upstream backend.
                status_code_filter:
                  comparison:
                    op: EQ
                    value:
                      default_value: 403
                      runtime_key: placeholder
              status_code: 403
              body:
                inline_string: customized_authz_deny_response
              body_format_override:
                text_format: "<h1>%LOCAL_REPLY_BODY% %RESPONSE_CODE% %REQ(:path)%</h1>"
                content_type: "text/html; charset=UTF-8"
EOF
```
