### ISSUE TITLE
Apply custom SpanTags in Tracespan

### ISSUE THREAD

**Issue by garyxuehong** [istio/istio#10625]
**Describe the feature request**
Apply custom spantags for tracing purpose

**Describe alternatives you've considered**
noop

**Additional context**

I want to apply custom span.tags in Tracespan as follow:

```
apiVersion: "config.istio.io/v1alpha2"
kind: tracespan
metadata:
  name: default
  namespace: istio-system
spec:
  traceId: request.headers["x-b3-traceid"]
  spanId: request.headers["x-b3-spanid"] | ""
  parentSpanId: request.headers["x-b3-parentspanid"] | ""
  spanName: request.path | "/"
  startTime: request.time
  endTime: response.time
  clientSpan: (context.reporter.local | true) == false
  rewriteClientSpanId: false
  spanTags:
    http.method: request.method | ""
    http.status_code: response.code | 200
    http.url: request.path | ""
    request.size: request.size | 0
    response.size: response.size | 0
    source.ip: source.ip | ip("0.0.0.0")
    source.service: source.service | ""
    source.user: source.user | ""
    source.version: source.labels["version"] | ""
    my.value: "value1" <-------- I want this one
```

After I `kubectl apply -f`, I get following in the logs:

`error   failed to evaluate expression for field 'SpanTags[my.value]'; unknown attribute value1`

**Comment by douglas-reid** [comment]
Do you want the literal value of `value1`?  Or the value of a new attribute that you trying to add?

**Comment by garyxuehong** [comment]
New attribute

Douglas Reid <notifications@github.com>于2019年1月8日 周二上午10:11写道：

**Comment by douglas-reid** [comment]
If you are adding a new attribute, have you made sure to add it to one of the existing attribute manifests (or create new attribute manifest for this attribute)?

See: https://github.com/istio/istio/blob/master/install/kubernetes/helm/subcharts/mixer/templates/config.yaml#L3

**Comment by garyxuehong** [comment]
Thanks I will look into that. I must missed that part

Douglas Reid <notifications@github.com>于2019年1月8日 周二上午11:03写道：

**Comment by douglas-reid** [comment]
@garyxuehong I assume your issue has been addressed. Closing. Please reopen if needed.

**Comment by bedla** [comment]
Hi,
I am unable to find any detail information in documentation how to add custom tag to `spanTags`. I also tried to extract current configuration using `kubectl get instance -n istio-system` but without luck (I am unable to locate the one with `metadata.name=default` as mentioned in configuration example here https://archive.istio.io/v1.3/docs/reference/config/policy-and-telemetry/templates/tracespan/). 
Thank you,
Ivos

**Comment by douglas-reid** [comment]
@bedla which version of Istio are you using?

**Comment by bedla** [comment]
v1.3.8, but I was not able to find info about `tracespan`s in 1.5 docs too.

**Comment by bedla** [comment]
It seems that from version 1.6 (https://github.com/istio/api/pull/1369) it is possible to configure custom span tags in `istio`-`ConfigMap`. 

```
    defaultConfig:
      tracing:
        zipkin:
          # Address of the Zipkin collector
          address: zipkin.istio-system:9411
        custom_tags:
          new_tag_name:
            header:
              name: custom-http-header-name
              default_value: defaulted-value-from-custom-header
```
