### ISSUE TITLE
Istio rewrite to a different prefix does not work

### ISSUE THREAD

**Issue by shahaf600** [istio/istio#10647]
**Describe the bug**
{{ Succinctly describe the bug }}
trying to use one port for GRPC in the ingress gateway, as well as 1 gateway .
I want to create a virtualservice for each service i deploy to K8S and to route to those services with 1 load balancer and one port but different api calls(prefix or virtual host like in nginx)

**Expected behavior**
{{ What did you expect to happen? }}
i want the end route to be to the one i rewrite
this is the route created, and you can see in the decorator that it does not get rid of the "trs-tulip" prefix:
and this way it does not get the traffic also.
```
"name": "http.24051",
        "virtualHosts": [
            {
                "name": "*:24051",
                "domains": [
                    "*",
                    "*:24051"
                ],
                "routes": [
                    {
                        "match": {
                            "prefix": "/trs-tulip"
                        },
                        "route": {
                            "cluster": "outbound|50051||trs-tulip.ud.svc.kube.am.taboolasyndication.com",
                            "prefixRewrite": "/",
                            "hostRewrite": "",
                            "timeout": "0.000s",
                            "maxGrpcTimeout": "0.000s"
                        },
                        "decorator": {
                            "operation": "trs-tulip.ud.svc.kube.am.taboolasyndication.com:50051/trs-tulip*"
                        },
                        "perFilterConfig": {
```

**Steps to reproduce the bug**
{{ Minimal steps to reproduce the behavior }}
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: trs-tulip-gateway
spec:
  selector:
    istio: ud-ingressgateway
  servers:
  - port:
      number: 24051
      name: grpc
      protocol: HTTP2
    hosts:
    - "*"
```
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: trs-tulip-vsvc
spec:
  hosts:
  - "*"
  gateways:
  - trs-tulip-gateway
  http:
  - match:
    - uri:
        prefix: "/trs-tulip"
    rewrite:
      uri: /
    route:
    - destination:
        host: trs-tulip
        port:
          number: 50051
```

**Version**
{{ What version of Istio and Kubernetes are you using? Use `istioctl version` and `kubectl version` }}
istio: 1.0.1
k8s: v1.11.3

**Installation**
{{ Please describe how Istio was installed }}
helm charts
**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}
vanilla kubernetes
**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}
