### ISSUE TITLE
can't set egress with serviceentry to allow all egress traffic without a specific host or address

### ISSUE THREAD

**Issue by shahaf600** [istio/istio#10662]
**Describe the bug**
I have a pod which runs a kafka writter service along with an istio sidecar.
this pod is trying to reach kafka with port 6667 to the exact DNS name of the kafka servers.
kafka is using TCP protocol for communication.
I have configured a serviceentry for the port 6667 so the app will be able to reach kafka outside with port 6667:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  annotations:
  name: taboola-service-entry
  namespace: ud
spec:
  hosts:
  - kafka-metrics401.example.com
  - kafka-metrics402.example.com
  - kafka-metrics403.example.com
  - kafka401.example.com
  - kafka402.example.com
  - kafka403.example.com
  location: MESH_EXTERNAL
  ports:
  - name: kafka-port
    number: 6667
    protocol: TCP
  resolution: DNS
```
when I configured it like this it works and the app can reach the kafka service in port 6667.
BUT, I don't want to explicitly specify each server in the DC I want to reach to in the serviceEntry.
I want to specify a port and a protocol and I want it to work for every host no matter what it's dns name. 
so it is possible in the docs, it is said there to use TCP protocol with resolution set to NONE and it should work but it doesn't. the docs says that if I configure it this way to should ignore hosts and addresses and allow all traffic to this port. but it does not work.
any ideas how to do it in a more generic way ?

**Version**
istio - 1.0.1
k8s - 1.11.3

**Installation**
helm charts

**Environment**
bare-metal vanilla clusters
