### ISSUE TITLE
Rate limiting does not work for external services

### ISSUE THREAD

**Issue by neillee95** [istio/istio#10676]
Following this [task](https://istio.io/docs/tasks/traffic-management/egress/) I can access to external services by defining ServiceEntry configurations. And in another [task](https://istio.io/docs/tasks/policy-enforcement/rate-limiting/) I can limit the traffic to a service, it works in cluster. But I failed to limit the traffic from service in cluster to external urls like www.google.com.

I try to [configure an Egress gateway](https://preliminary.istio.io/docs/examples/advanced-gateways/egress-gateway/), and then apply the rate limiting. Depressingly, it still does not work.

Configuration:
```
apiVersion: "config.istio.io/v1alpha2"
kind: memquota
metadata:
  name: handler
  namespace: istio-system
spec:
  quotas:
  - name: requestcount.quota.istio-system
    maxAmount: 2
    validDuration: 60s
---
apiVersion: "config.istio.io/v1alpha2"
kind: quota
metadata:
  name: requestcount
  namespace: istio-system
spec:
  dimensions:
    source: request.headers["x-forwarded-for"] | "unknown"
    destination: destination.labels["app"] | destination.service | "unknown"
    destinationVersion: destination.labels["version"] | "unknown"
---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpec
metadata:
  name: request-count
  namespace: istio-system
spec:
  rules:
  - quotas:
    - charge: 1
      quota: requestcount
---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpecBinding
metadata:
  name: request-count
  namespace: istio-system
spec:
  quotaSpecs:
  - name: request-count
    namespace: istio-system
  services:
  - name: sleep
    namespace: default
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: quota
  namespace: istio-system
spec:
  actions:
  - handler: handler.memquota
    instances:
    - requestcount.quota
```

I don't know if my configuration is correct. Rate limiting is not working for external services?

Istio version: 1.0.5
