### ISSUE TITLE
Webhook "pilot.validation.istio.io" reports invalid configuration error for valid config 

### ISSUE THREAD

**Issue by kbhattac** [istio/istio#10694]
ServiceEntry fails to create egress rule with host "metadata": https://raw.githubusercontent.com/kbhattac/CoolRetailer/master/setup/istio-manifests/whitelist-egress.yaml

kubectl apply -f setup/istio-manifests/whitelist-egress.yaml
Error from server: error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"networking.istio.io/v1alpha3\",\"kind\":\"ServiceEntry\",\"metadata\":{\"annotations\":{},\"name\":\"whitelist-egress\",\"namespace\":\"default\"},\"spec\":{\"hosts\":[\"169.254.169.254\",\"metadata.google\",\"metadata.google.internal\",\"accounts.google.com\",\"metadata\",\"*.googleapis.com\"],\"ports\":[{\"name\":\"http\",\"number\":80,\"protocol\":\"HTTP\"},{\"name\":\"https\",\"number\":443,\"protocol\":\"HTTPS\"}]}}\n"}},"spec":{"hosts":["169.254.169.254","metadata.google","metadata.google.internal","accounts.google.com","metadata","*.googleapis.com"]}}
to:
&{0xc42007f800 0xc42007b180 default whitelist-egress setup/istio-manifests/whitelist-egress.yaml 0xc422206df0 1656642 false}
for: "setup/istio-manifests/whitelist-egress.yaml": admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: invalid host metadata

Hostname "metadata" should be allowed. If not what is the workaround?

**Comment by sbezverk** [comment]
I tried to locate which part of the webhook code generates this error and even though I could clearly see the code validating `ServiceEntry` crd, it does not have any error related to `host metadata`.  I am using `master` branch of Istio. I think Steve's request is right about version. It looks to me there is a mismatch between webhook version and ServiceEntry config you try to push.

**Comment by tsiq-oliver** [comment]
FWIW, I just ran into this (with a different hostname).  It appears the cause is https://github.com/istio/istio/blob/master/pilot/pkg/model/validation.go#L1818:

```
// Full wildcard or short names are not allowed in the service entry.
if host == "*" || !strings.Contains(host, ".") {
	errs = appendErrors(errs, fmt.Errorf("invalid host %s", host))
} else {
	errs = appendErrors(errs, ValidateWildcardDomain(host))
}
```

**Comment by sbezverk** [comment]
@tsiq-oliver what was the host name? this code catches is the host name is "*" or not fqdn.

**Comment by tsiq-oliver** [comment]
@sbezverk In my case, it was my Travis VM's hostname (something like `travis-job-0cc65e30-9e6e-4e18-a2d4-deadbeef`).  So indeed not an FQDN, which is also the case for the OP here (`metadata`).

**Comment by sdake** [comment]
@kbhattac note that SEs must be FQDNs.  Your yaml that is failing parsing does not contain a FQDN hostname:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: whitelist-egress
spec:
  hosts:
  - "169.254.169.254" # GCE metadata servers
  - "metadata"
  - "metadata.google"
  - "metadata.google.internal"
  - "accounts.google.com" # Used to get token
  - "*.googleapis.com"
  ports:
  - number: 80
    protocol: HTTP
    name: http
  - number: 443
    protocol: HTTPS
    name: https
```

in this case, metadata is not a fully qualified host.  It is possible a protection check was added in a z stream of Istio to prevent operators from configuring their systems in this way.

Cheers
-steve
