### ISSUE TITLE
Weird SNI Behavior

### ISSUE THREAD

**Issue by motek80** [istio/istio#10702]
**Describe the bug**
I have two domains:
"a.acme.com" and "b.acme.com" (both are A records pointing to the same AWS ELB)

I want to accept TLS traffic for "a.acme.com" but not for "b.acme.com". I want to use SNI feature to route incoming traffic based on destination host.

 I configured Gateway like this:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mygateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    - "a.acme.com"
```

If I trying right away to send request to "b.acme.com" - it fails (as expected).

However, if I trying to send to "a.acme.com" - it success (as expected) and then trying to send to "b.acme.com" - it success as well (which is not expected). After several minutes "b.acme.com" not accepting requests again, until any call to "a.acme.com".

**Expected behavior**
Requests to "a.acme.com" will always succeed, requests to "b.acme.com" will always fail

**Steps to reproduce the bug**
Make sure you have both domains in your DNS zone, configure Gateway to accept only one of them. Then first call to "listed" domain and right after that call to "not listed" URL. Second call will return response despite it not configured in Gateway "hosts".

**Version**
EKS 1.11.5
Istio 1.0.5

**Installation**
I used "Helm Template" method as described [here](https://istio.io/docs/setup/kubernetes/helm-install/) (option 1)

**Environment**
AWS EKS. VPC network plugin.

**Cluster state**
[istio-dump.tar.gz](https://github.com/istio/istio/files/2720714/istio-dump.tar.gz)
