### ISSUE TITLE
Write EPIPE Error or read ECONNRESET error when using istio with cloudsql proxy sidecar

### ISSUE THREAD

**Issue by mkinoshi** [istio/istio#10716]
**Describe the bug**
I'm using GCK, and I have a pod that runs an application along with both istio and cloudsql proxy sidecar. The application can successfully access database but always gets the following errors in the application logs. Any ideas how to solve this error ?
```
Debug: internal, implementation, error
  Error: read ECONNRESET
  at TCP.onread (net.js:602:25)
```
```
Debug: internal, implementation, error
  Error: Uncaught error: write EPIPE
   at WriteWrap.afterWrite [as oncomplete] (net.js:844:14)
```
Cloudsql proxy runs with the following setup.
```
 containers:
      - image: b.gcr.io/cloudsql-docker/gce-proxy:latest
        imagePullPolicy: Always
        name: cloudsqlproxy
        command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                "-instances=project-name:zone:db_name=tcp:0.0.0.0:5432",
                "-credential_file=$SECRET_FILE_PATH"]
        ports:
        - name: db_name
          containerPort: 5432
```

I also wrote the following `ServiceEntry` and `VirtualService` rules
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: https-network-rule
spec:
  hosts:
    - www.googleapis.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
```
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cloud-sql-instance
spec:
  hosts:
    - $INSTANCE_IP_ADDRESS
  addresses:
    - $INSTANCE_IP_ADDRESS/32
  ports:
    - name: tcp
      number: 3307
      protocol: tcp
  location: MESH_EXTERNAL
```
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: google
spec:
  hosts:
    - www.googleapis.com
  tls:
  - match:
    - port: 443
      sniHosts:
      - www.googleapis.com
    route:
    - destination:
        host: www.googleapis.com
```

**Version**
k8s version - 1.11.2

**Installation**
Through the following gcloud command. 
gcloud beta container clusters update istio-demo --project=$PROJECT_ID \
    --update-addons=Istio=ENABLED --istio-config=auth=MTLS_PERMISSIVE

**Environment**
Google cloud Kubernes
