### ISSUE TITLE
Gateway and VirtualService ordering should not matter

### ISSUE THREAD

**Issue by arun-gupta** [istio/istio#10748]
**Describe the bug**
{{ Succinctly describe the bug }}

Gateway needs to be created VirtualService in order for the service to respond back. Otherwise the service endpoint gives `curl: (52) Empty reply from server`.

**Expected behavior**
Expected the service to return a valid response

**Steps to reproduce the bug**

Use the following config file for the service to return an error:

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: greeting
spec:
  host: greeting
  subsets:
  - name: greeting-hello
    labels:
      greeting: hello
  - name: greeting-howdy
    labels:
      greeting: howdy
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: greeting
spec:
  gateways:
    - greeting # namespace of the Gateway
  hosts:
    - greeting.com
  http:
  - route:
    - destination:
        host: greeting
        subset: greeting-hello
        port:
          number: 80
      weight: 50
    - destination:
        host: greeting
        subset: greeting-howdy
        port:
          number: 80
      weight: 50
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: greeting
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
```

If Gateway is ordered as the first item in this file then the service returns expected response.

**Version**

```
istioctl version
Version: 1.0.5
GitRevision: c1707e45e71c75d74bf3a5dec8c7086f32f32fad
User: root@6f6ea1061f2b
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:10Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**

https://aws.amazon.com/blogs/opensource/getting-started-istio-eks/

**Environment**

AWS

**Cluster state**

{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

Script did not work

Thanks @ZackButcher for helping debug and encouraging to submit the issue.
