### ISSUE TITLE
VirtualService HTTPMatchRequest.regex breaks when using pipes

### ISSUE THREAD

**Issue by mehemken** [istio/istio#10766]
**Describe the bug**

## As seen on [StackOverflow](https://stackoverflow.com/questions/54066089/how-to-achieve-logical-or-in-an-istio-virtualservice-regex).

The pipe character does not seem to work in Istio's VirtualService.

The example below is intended to route requests based on the user-agent header. Requests from a mobile device should go to myapp and requests from a desktop user should go to deskt-app, handled by next match block. The \<REGEX\> field works when I use this regex:

    ^.*\bMobile\b.*$

But the powers that be require a more sophisticated regex to identify mobile users. My routing breaks entirely when I use these:

    ^.*\b(iPhone|Pixel)\b.*$
    ^.*\b(iPhone|Pixel)+\b.*$
    ^.*\biPhone|Pixel\b.*$

**Expected behavior**

Using a regex with a pipe (logical OR) I expect to be routed to myapp when I have a user-agent header that contains the word "iPhone" or "Pixel".

**Actual behavior**

I get routed to deskt-app.

**Steps to reproduce the bug**

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
  ...
  ...
  http:
  - match:
    - headers:
        user-agent:
          regex: "<REGEX>"    <------
      uri:
        prefix: /foo/bar
    route:
    - destination:
        host: myapp
        port:
          number: 80
  - match:
    - uri:
        prefix: /foo/bar
    route:
    - destination:
        host: deskt-app
        port:
          number: 80
```

**Version**

**K8s**
kubectl Client: 1.9.9
kubectl Server: 1.10.9-gke.5

**Istio**
Version: 1.0.5
GitRevision: c1707e45e71c75d74bf3a5dec8c7086f32f32fad
User: root@6f6ea1061f2b
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean

**Installation**
With the Helm chart.

**Environment**
GKE
