### ISSUE TITLE
Process run as root

### ISSUE THREAD

**Issue by clyang82** [istio/istio#10768]
I see the process is running as root in `galley` `pilot` `citadel` and `mixer` pod while the process is running as user `istio-proxy` for `envoy`.
is it must running as root for `galley` `pilot` `citadel` and `mixer`? why? Thanks.

**Comment by linsun** [comment]
so we don't use root for data plane, but uses root process for control plane components.  Any issue with this?

**Comment by clyang82** [comment]
I am filling in the Threat Model for ICP. it requires to provide justification as to why it needs to run as root. so I wonder to know some details.

**Comment by esnible** [comment]
Envoy MUST run as istio-proxy (uid 1337).

I don't know of any particular reason the galley, pilot, citadel and mixer as running as root.  They should be able to run as any user *except* they must not run as istio-proxy.

**Comment by clyang82** [comment]
Thanks @esnible for your information. 

> Well designed systems adhere to the [principle of least privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege). This simply states that an application should only have access to the resources it needs in order to perform its required function. This is critical when designing a secure system.

If `pilot`/`mixer`/`galley`/`citadel` can be able to run as any user except from istio-proxy, we may consider to create a user for them to run the process.

**Comment by ayj** [comment]
Galley doesn't need root privileges. I think the same is true for Mixer and Pilot. Their `istio-proxy` sidecars are a bit different than the app sidecars in that traffic is not automatically captured (via iptables) and the proxy configuration itself is hardcoded (vs. configured by Pilot) such that the root privileges and special uid is not needed.

**Comment by clyang82** [comment]
Thanks @ayj for your information. How about create a user `istio` to run the process?

**Comment by linsun** [comment]
@clyang82 probably worth exploring if this can work, if it works, it will folks who don't like to use root to run processes.

**Comment by luksa** [comment]
Ideally, the image should allow running the container with _any_ uid, so that it can be run with a new (random) uid every time. This improves security in cases where an attacker is able to escape from the container. Using a static uid may help the attacker do things outside of the container, if that same uid is used on the host (e.g. if the uid is allowed to access sensitive files). 

Allowing the container to run with any uid requires file permissions to be set at group level.

**Comment by MarkDeckert** [comment]
Is there any movement on this?  It's such low hanging fruit and just basic old school security. Everything needs to run as least privilege.

**Comment by clyang82** [comment]
/assign

I will do it next week.

**Comment by clyang82** [comment]
[this pr](https://github.com/istio/istio/pull/16014) was merged. we can close this one.

**Comment by segfault16** [comment]
@clyang82 I think its unclear what's the current state of running istio with non-root privileges (except CNI of course):
- This issue is tagged for milestone 1.3
- [PR 16014](https://github.com/istio/istio/pull/16014) is merged into master
- Commits of the PR have been reverted afterwards?
- Istio core components can be run as non-root in 1.4.2 when patching the deployment, e.g. with:

````
  configManagement:
    components:
      galley:
        k8s:
          overlays:
          - apiVersion: apps/v1
            kind: Deployment
            name: istio-galley
            patches:
            - path: spec.template.spec.containers.[name:galley].securityContext
              value: 
                runAsUser: 1337
            - path: spec.template.spec.containers.[name:istio-proxy].securityContext
              value: 
                runAsUser: 1337
            - path: spec.template.spec.containers.[name:istio-proxy].args
              value:
              - proxy
              - --serviceCluster
              - istio-galley
              - --templateFile
              - /var/lib/istio/galley/envoy/envoy.yaml.tmpl
              - --controlPlaneAuthPolicy
              - MUTUAL_TLS
              - --trust-domain=cluster.local
              - --configPath # Added
              - /tmp # Added
````
