### ISSUE TITLE
Authentication policy configuration does not work for some service in one namespace

### ISSUE THREAD

**Issue by chenzhenyang** [istio/istio#10762]
I have two service in one namespace , I create a authentication policy file as below:

```
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "default"
spec:
  peers:
  - mtls: {}
  origins:
  - jwt:
      issuer: "https://uaa-stage.sdmkny.com/uaa/oauth/token"
      jwksUri: "https://uaa-stage.sdmkny.com/uaa/token_keys"
  principalBinding: USE_ORIGIN
```

but , two service in one namespace ,one is work and another is not work;

maybe what's reason?
