### ISSUE TITLE
istio does not support gzip

### ISSUE THREAD

**Issue by wjwinner** [istio/istio#10770]
Envoy already supports [gzip](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/gzip_filter),but I haven't found any instructions for istio to support gzip. Is istio planning to support gzip?

**Comment by kuzaxak** [comment]
@wjwinner 

You can add gzip filter to the gateway.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: gateway-gzip
spec:
  filters:
  - listenerMatch:
      listenerType: GATEWAY
      listenerProtocol: HTTP
    filterName: envoy.gzip
    filterType: HTTP
    filterConfig:
      inlineCode: |
        compression_level: BEST
```
