### ISSUE TITLE
Mixer emits warning if value for responseHeaderOperation of a Rule is not defined

### ISSUE THREAD

**Issue by robertpanzer** [istio/istio#10801]
**Describe the bug**
I am testing route directives with a current 1.1 snapshot according to https://github.com/istio/istio/wiki/Route-directive-adapter-development-guide.
I created a Rule that should set a response header.
When my custom external adapter sets this header everything is fine and I see the header in the response to the client.
But when the adapter does not set this value, because it decides that this is not necessary, Mixer emits a warning in the logs:

```
2019-01-08T14:03:01.905945Z     warn    Failed to evaluate header value: lookup failed: 'a1.output.refreshToken'                              
```

Setting an empty string instead of not passing a value sets the header on the response what I also don't want.

The output template looks like this:

```proto
message OutputTemplate {
  string refreshToken = 1;
}
```

The adapter returns this response:
```go
	output := &OutputMsg{}
	return &MyResponse{
		Result:&v1beta1.CheckResult{Status: status.OK, ValidUseCount: 1, ValidDuration: 0},
		Output: output,
	}, nil
```

**Expected behavior**
I expect that it should be possible to set response headers conditionally.
Mixer should not emit a warning in such cases.

**Steps to reproduce the bug**
Create an external adapter according to https://github.com/istio/istio/wiki/Route-directive-adapter-development-guide
Add one property `refreshToken` to the response template and make the adapter not set it.
Configure a rule that invokes the adapter and applies the output field on the response template:
```yaml
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: myrule
  namespace: istio-system
spec:
  actions:
  - handler: myadapter
    instances:
    - myinstance
    name: a1
  match: destination.workload.uid == "istio://test/workloads/testserver"
  responseHeaderOperations:
  - name: refreshtoken
    values:
    - a1.output.refreshToken
```

(Setting the value to `a1.output.refreshToken | ""` results in an empty header in the response which I also don't want.

**Version**
More or less current Istio 1.1 head built from https://github.com/istio/istio/commits/ee30c791a99acef108be825e70010b5f47da5254
Running on Kubernetes 1.10.3 on Docker for Mac

**Installation**
```
helm template ~/go/src/istio.io/istio/install/kubernetes/helm/istio \
  --name istio --namespace istio-system \
  -f ~/istio/istio-1.0.4/install/kubernetes/helm/istio/values-istio-auth.yaml \
  --set global.mtls.enabled=true \
  --set global.tracing.enabled=true \
  --set pilot.traceSampling=100.0 \
  --set global.hub=istio \
  --set global.tag=ee30c791a99acef108be825e70010b5f47da5254 \
  --set tracing.enabled=true|ubectl apply -f -
```

**Environment**
See above, Docker for Mac, K8s 1.10.3
