### ISSUE TITLE
EDS code correctness issue with config scopes and the Sidecar API

### ISSUE THREAD

**Issue by rshriram** [istio/istio#10817]
**Describe the bug**
The new sidecar API for subsetting allows a namespace to import specific sets of destination rules from limited namespaces. This means, I could have a private destination rule in local namespace, or import a public destination rule from one namespace (but not import the public destination rule from another namespace).

Consequently, a cluster of the form `outbound|8000|v1|foo.ns1.svc.cluster.local` could be formed from a namespace local private destination rule or a destination rule that is imported from a different namespace. i.e., two proxies in different namespaces could have a cluster with the same name but completely different set of endpoints [a v1 in one dest rule may not be the same as the v1 in another dest rule for the same host]

The existing EDS code uses calls like model.SubsetToLabels(subsetName, ..) that disregards the proxy completely, leading to the correctness issue described above. 

A proper fix is to compute the EDS per Sidecar API object and not have a single shared EDS for all sidecars in the mesh.

cc @duderino / @munrodg or whoever happens to be tracking 1.1 milestones.

assigning to @costinm as he wrote all the EDS code
FYI @louiscryan

**Comment by rshriram** [comment]
namespace will not help. The problem is that you can have a public dest rule for a cluster and a private dest rule for the same cluster, in same namespace. 
Simple example:

```
DestRule:
  name: foo
  namespace: ns1
spec:
  host: myservice.ns2.svc.cluster.local
  subsets:
  - name: v1
     labels:
        version: v1
        state: prod-test-fix
 configScope: PRIVATE
---
DestRule:
  name: foo
  namespace: ns2
spec:
  host: myservice.ns2.svc.cluster.local
  subsets:
  - name: v1
     labels:
        version: v1
 configScope: PUBLIC
```

For a cluster `Outbound|80|v1|myservice.ns2.svc.cluster.local`, for sidecars in ns1 namespace, it would get endpoints with labels `version:v1, state: prod-test-fix`, whereas sidecars in ns2 namespace and any other namespace will get endpoints with labels `version: v1`.

Adding the destination rule in the cluster name will cause a lot more trouble and break LDS/RDS code, in addition to creating correctness issues caused by destination rule inheritance model, etc. 

The proper fix, IMO, is to have an EDS cache per sidecarScope object, which in turn can be applied to all proxies that map to this sidecar scope object.
