### ISSUE TITLE
[question] Pilot headless service in multi-cluster setup

### ISSUE THREAD

**Issue by hasusuf** [istio/istio#10824]
At KubeCon 2018, Rohit from Cisco demoed istio multi-cluster setup. At the minute [19:45](https://youtu.be/bLJL53UIcqI?t=1186) he deployed `istio-pilot` service as headless service on his `secondary` cluster, and it was able to discover the remote pilot pod's IP running on his `primary` cluster.

I have two GKE clusters with VPC-native enabled, and I'm not able to reproduce the same behavior. The `istio-pilot` endpoint is always `<none>`. May I ask what I'm missing?

**Comment by ymesika** [comment]
I believe the deployment there is similar to what we called Multi-cluster in v1.0.x (things changed in v1.1).

There is actually [a detailed deployment example](https://istio.io/docs/setup/kubernetes/multicluster-install/#example-deployment) that shows how to install such a local/remote setup on two clusters. See if it helps.

**Comment by hasusuf** [comment]
Thanks, @ymesika 👍

**Comment by Nielsoux** [comment]
Hello, 

I'm working on a multi-cluster, shared control-plane, multi-network Istio deployment on EKS

The only way I had it working at the moment is with the istio-ingressgateway in both cluster populating TCP ELB's

```
cat override.yaml 
gateways:
  istio-ingressgateway:
    serviceAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "elb"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
```
Problem could come from the lack of support stated here: 
https://istio.io/docs/setup/kubernetes/install/multicluster/shared-gateways/#setup-cluster-2

`The command fails if the load balancer configuration doesn’t include an IP address. The implementation of DNS name support is pending.`

Could this issue be resolved if, instead of populating **endpoints**:
```
---
# Source: istio/templates/endpoints.yaml

apiVersion: v1
kind: Endpoints
metadata:
  name: istio-pilot
  namespace: istio-system
subsets:
- addresses:
  - ip: <LOCAL_GW_ADDR>
  ports:
  - port: 15003
    name: http-old-discovery # mTLS or non-mTLS depending on auth setting
  - port: 15005
    name: https-discovery # always mTLS
  - port: 15007
    name: http-discovery # always plain-text
  - port: 15010
    name: grpc-xds # direct
  - port: 15011
    name: https-xds # mTLS or non-mTLS depending on auth setting
  - port: 8080
    name: http-legacy-discovery # direct
  - port: 15014
    name: http-monitoring
---
apiVersion: v1
kind: Endpoints
metadata:
  name: istio-policy
  namespace: istio-system
subsets:
- addresses:
  - ip: <LOCAL_GW_ADDR>
  ports:
  - name: grpc-mixer
    port: 9091
  - name: grpc-mixer-mtls
    port: 15004
  - name: http-monitoring
    port: 15014
---
apiVersion: v1
kind: Endpoints
metadata:
  name: istio-telemetry
  namespace: istio-system
subsets:
- addresses:
  - ip: <LOCAL_GW_ADDR>
  ports:
  - name: grpc-mixer
    port: 9091
  - name: grpc-mixer-mtls
    port: 15004
  - name: http-monitoring
    port: 15014
  - name: prometheus
    port: 42422

---
```
Where we are obliged to use IP addresses

We could use [Headless Service](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services) where we reference the DNS name of the LoadBalancer exposing the istio-ingressgateway service from the primary cluster?

```
...
apiVersion: v1
kind: Service
metadata:
  name: istio-pilot
  namespace: istio-system
spec:
  type: ExternalName
  externalName: <ELB-DNS-NAME>
  clusterIP: None
  ports:
    - port: 15003
      name: http-old-discovery # mTLS or non-mTLS depending on auth setting
    - port: 15005
      name: https-discovery # always mTLS
    - port: 15007
      name: http-discovery # always plain-text
    - port: 15010
      name: grpc-xds # direct
    - port: 15011
      name: https-xds # mTLS or non-mTLS depending on auth setting
    - port: 8080
      name: http-legacy-discovery # direct
    - port: 15014
      name: http-monitoring
...
---
apiVersion: v1
kind: Service
metadata:
  name: istio-pilot
  namespace: istio-system
spec:
  type: ExternalName
  externalName: <ELB-DNS-NAME>
  clusterIP: None
  ports:
    - name: grpc-mixer
      port: 9091
    - name: grpc-mixer-mtls
      port: 15004
    - name: http-monitoring
      port: 15014
...
---
apiVersion: v1
kind: Service
metadata:
  name: istio-pilot
  namespace: istio-system
spec:
  type: ExternalName
  externalName: <ELB-DNS-NAME>
  clusterIP: None
  ports:
    - name: grpc-mixer
      port: 9091
    - name: grpc-mixer-mtls
      port: 15004
    - name: http-monitoring
      port: 15014
    - name: prometheus
      port: 42422
...
```
