### ISSUE TITLE
Route based on user identity

### ISSUE THREAD

**Issue by clyang82** [istio/istio#10829]
Here is an example about [Route based on user identity](https://istio.io/docs/tasks/traffic-management/request-routing/#route-based-on-user-identity). I want to have 2 end users to access the same service. so I create 2 virtualservices. for instance:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews-jason
spec:
  hosts:
    - reviews
  http:
  - match:
    - headers:
        end-user:
          exact: jason
    route:
    - destination:
        host: reviews
        subset: v2
  - route:
    - destination:
        host: reviews
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews-kevin
spec:
  hosts:
    - reviews
  http:
  - match:
    - headers:
        end-user:
          exact: kevin
    route:
    - destination:
        host: reviews
        subset: v2
  - route:
    - destination:
        host: reviews
        subset: v1
```

it is not working as my expected.
When I create 1 virtualservice with multiple match, it works well. for instance:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews-jason
spec:
  hosts:
    - reviews
  http:
  - match:
    - headers:
        end-user:
          exact: jason
    route:
    - destination:
        host: reviews
        subset: v2
  - match:
    - headers:
        end-user:
          exact: kevin
    route:
    - destination:
        host: reviews
        subset: v2
  - route:
    - destination:
        host: reviews
        subset: v1
```

I know we have a feature to merge virtualservices. is this designed behaviour or just a bug?
