### ISSUE TITLE
pip does not work inside container with Envoy proxy.

### ISSUE THREAD

**Issue by mabushey** [istio/istio#10847]
**Describe the bug**
Cannot retrieve data from pipy.python.org - `pip install boto3` from inside container with Envoy sidecar proxy.
```
/app # pip install boto3
Collecting boto3
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(104, 'Connection reset by peer'))': /simple/boto3/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(104, 'Connection reset by peer'))': /simple/boto3/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(104, 'Connection reset by peer'))': /simple/boto3/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(104, 'Connection reset by peer'))': /simple/boto3/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(104, 'Connection reset by peer'))': /simple/boto3/
  Could not find a version that satisfies the requirement boto3 (from versions: )
No matching distribution found for boto3
```

**Expected behavior**
`Pip install` installs 

**Steps to reproduce the bug**
Add egress rule:
```
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: pypi
spec:
  hosts:
  - "pypi.python.org"
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: pypi
spec:
  hosts:
  - "*.python.org"
  tls:
  - match:
    - port: 443
      sni_hosts:
      - "*.python.org"
    route:
    - destination:
        host: "*.python.org"
        port:
          number: 443
      weight: 100
---
```
Exec into container and run `pip install boto3`.

**Version**
```
Istio version 1.0.5

istioctl version
version.BuildInfo{Version:"1.1.0-snapshot.2", GitRevision:"bd24a62648c07e24ca655c39727aeb0e4761919a", User:"root", Host:"6408abaf1dac", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean"}
```
This is a mostly an obsolete tool, the only thing it's good for is checking the mTLS settings.

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
Client and server within 1 minor version of each other

**Installation**
`kubectl apply -f istio.yaml`. istio.yaml was created with the garbage tool Helm:
`helm template istio-1.0.5/install/kubernetes/helm/istio --name istio --namespace istio-system  --set grafana.enabled=true  --set grafana.security.enabled=true  --set grafana.security.adminUser=admin --set grafana.security.adminPassword=[redacted] --set tracing.enabled=true > istio.yaml`

**Environment**
AWS brought up via Kops. Nodes are CoreOS.

**Cluster state**
Happy, mTLS (default defective setting of Istio) disabled.

**Comment by esnible** [comment]
I attempted to look into this.

I got a lot further with

```
cat <<EOF | kubectl create -f -
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: make-pypi-work
spec:
  hosts:
  - "pypi.python.org"
  ports:
  - number: 443
    name: tcp
    protocol: TCP
  resolution: DNS
  location: MESH_EXTERNAL
EOF
```

By saying the connection is TCP, Istio doesn't look into it.

When I tried it your way I got 

```
[2019-02-01 18:43:14.433][32][debug][filter] [external/envoy/source/extensions/filters/listener/tls_inspector/tls_inspector.cc:119] tls:onServerName(), requestedServerName: pypi.org
[2019-02-01 18:43:14.433][32][debug][main] [external/envoy/source/server/connection_handler_impl.cc:231] closing connection: no matching filter chain found
```

from the Envoy logs when I raised them to DEBUG level.  @vadimeisenbergibm can you shed light on why @mabushey 's rule does not work?
