### ISSUE TITLE
Websocket connection dies on refresh

### ISSUE THREAD

**Issue by wooderz** [istio/istio#10898]
**Describe the bug**
VirtualService with DestinationRule running including websocketUpgrade: true - all works on first load of page, but refreshes cause the Websocket connections to throw 404 errors. I'm not 100% sure but I think this could be caused by using multiple replicas?

**Expected behavior**
Websocket Connection to be stable throughout lifetime of request and browser refreshes

**Steps to reproduce the bug**
Host a websocket service with multiple replicas (I normally use 3). 
Gateway
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: websocket-gateway
  namespace: websocket
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
      - "*"
```

VirtualService
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: websocket-virtual-service
  namespace: websocket
spec:
  hosts:
    - "*"
  gateways:
    -websocket-gateway
  http:
    - match:
      route:
      - destination:
          host: "*"
          port:
            number: 443
        weight: 100
      websocketUpgrade: true
```

Destination Rule
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: websocket-destinationrule
  namespace: websocket
spec:
  host: websocket-service
  subsets:
    - name: stable
      labels:
        version: websocket-v1
```

**Version**
Istio: 1.0.4
Kubectl: Client: 1.10.7 . Server 1.11.5-gke.5

**Installation**
Via GKE when creating the Cluster

**Environment**
Google Compute

**Cluster state**
See attached
[istio-dump.tar.gz](https://github.com/istio/istio/files/2749233/istio-dump.tar.gz)
