### ISSUE TITLE
requestHeaderOperations in rule inoperative without an action

### ISSUE THREAD

**Issue by theganyo** [istio/istio#10902]
I'm not sure if this is a "bug" or just needs to be documented as a quirk, but I wanted to raise it for discussion at least:

If I declare a rule that has requestHeaderOperations, it will not fire unless it has an associate "action". I feel that this is not intuitive to the operator (at least it wasn't to me) as `actions:` and `requestHeaderOperations:` are peers in the spec.

For example, a rule like this will do nothing:
```
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: my-rule
  namespace: istio-system
spec:
  match: true
  actions: []
  requestHeaderOperations:
  - name: :authority
    values:
    - '"wherever.example.com"'
```

In order to make this work as expected, I need to also add in some kind of dummy action like this:

```
apiVersion: config.istio.io/v1alpha2
kind: listchecker
metadata:
  name: dummylist
  namespace: istio-system
spec:
  overrides: ["X"]  # static list
  blacklist: true
  cachingUseCount: 1
  cachingInterval: "1s"
---
apiVersion: config.istio.io/v1alpha2
kind: listentry
metadata:
  namespace: istio-system
  name: dummylist
spec:
  value: '"Y"'
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: my-rule
  namespace: istio-system
spec:
  match: true
  actions:
  - handler: dummylist.listchecker
    instances:
    - dummylist.listentry
  requestHeaderOperations:
  - name: :authority
    values:
    - '"wherever.example.com"'
```
