### ISSUE TITLE
Istio ingressgateway routing broken with two different gateways using same port and different protocol(HTTP, GRPC)

### ISSUE THREAD

**Issue by karthikt-yahoo** [istio/istio#10999]
Istio ingress gateway routing is broken when same port is used by two different gateways with different protocol(HTTP and GRPC). 

Example:
if port 80 is shared by two gateways, 1. HTTP, 2. GRPC, routing is broken for the application associated with gateway, virtual service created latter.  individual application with different gateway with same protocol and same port works fine. 
**Expected behavior**
- Routing decision happens based on host header through virtual service configuration. 
- Istio should generate envoy routing configs properly when two gateways uses same port with different protocols. 
- Routing should work for same port with different protocols. 

**Steps to reproduce the bug**
1. Create HTTP application and corresponding K8s service(nginx would be faster)
2. Create GRPC application and corresponding K8s service(helloworld go app)
3. Create Gateway with Port 80, protocol HTTP,
sample gateway yaml.. names are changed for security purpose. 
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: grpc-app
  namespace: test-k8s
spec:
  servers:
  - port:
      number: 80
      name: grpc
      protocol: grpc
    hosts:
     - hello-world-grpc.test.com
```
4. Create Virtual service routing to application created from step 1.
5. Create second gateway with Port 80 and Protocol GRPC,
sample yaml,
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: http-app
  namespace: test-k8s
spec:
  servers:
  - port:
      number: 80
      name: http80
      protocol: HTTP
    hosts:
     - hello-world-grpc.test1.com
```
6.  create virtualservice for the GRPC applicaiton routing.
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grpc-app
  namespace: test-k8s
spec:
  hosts:
  - hello-world-grpc.test.com
  gateways:
  - grpc-app
  - mesh
  http:
  - route:
    - destination:
        port:
          number: 7777
        host: hello-md.test-k8s.svc.cluster.local 
```
7.  Verify HTTP application by hitting ingressgateway pod ip directly.
8. Verify GRPC application by hitting ingressgateway pod ip direclty.
you could reproduce the routing broken for grpc application where ingress gateways could not able to find the outbound cluster and the request failes.

GRPC and HTTP application works fine when created with different ports with no port conflicts

**Version**
Istio 1.0.4
Kubernetes v1.11.5

No logs in istio-pilot component.
