### ISSUE TITLE
DNS based issues

### ISSUE THREAD

**Issue by motek80** [istio/istio#11008]
**Describe the bug**
Declaring DNS name inside "hosts" of VirtualService does not working (routing fails).

**Expected behavior**
Routing will work

**Steps to reproduce the bug**
I have a Windows machine running Linux VM (Ubuntu 18.04). Inside Windows "hosts" file I have an entry pointing to IP of my VM (e.g. "micro.service xxx.xxx.xxx.xxx").

On my Ubuntu VM, I have installed Microk8s with Istio enabled (by the way, tried the same with KubeAdm - same results. This is **not** Microk8s issue). 

Define VirtualService with same host as defined in Windows "hosts" file:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: connectors
spec:
  hosts:
  - "micro.service"
  gateways:
  - thegateway
  http:
  - match:
    - uri:
        prefix: /v1
    rewrite:
        uri: "/"
    route:
     - destination:
        port:
          number: 80
        host: my-service.default.svc.cluster.local
```

I expecting that navigating to "http://micro.service/v1/dosomething" will work. However, it returns 404 error. If I replacing "micro.service" inside VirtualService by "*", then it works.

However, if I trying to do the same on real environment (EKS) with real domain - it works as expected (e.g. Istio able to use host name specified in "hosts" entry).

My Gateway definition looks like this:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: thegateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
```

**Version**
Kubernetes 1.13
Istio 1.0.5

**Installation**
Using "Helm Option 1" (creating Istio.yaml and then applying it) for KubeADM or by calling "microk8s.enable istio" for Microk8s

**Environment**
Windows 10 running Ubuntu VM
