### ISSUE TITLE
Not able to access the ingress URL from pod

### ISSUE THREAD

**Issue by santhosh-git** [istio/istio#11056]
We have to connect istio ingress load balancer from the pod. For that, We have created the service entry. Earlier It worked fine, Suddenly it's started giving 404 from the pod for HTTP but HTTPS is working. 

**Service Entry**
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: abc
  namespace: default
resolution: DNS
spec:
  hosts:
  - groot-abc.com
  location: MESH_EXTERNAL
  ports:
  - name: https
    number: 443
    protocol: HTTPS
  - name: http
    number: 80
    protocol: HTTP
```

**Version**

Istioctl :  1.0.2
Kubernetes & CLI : 1.10.8

**Installation**
Helm

**Environment**
AWS - Kubernetes ( Installed through KOPS)
