### ISSUE TITLE
Istio is Incompatible with Google's Metadata FQDN

### ISSUE THREAD

**Issue by ellis-bigelow** [istio/istio#11072]
**Describe the bug**
Istio's ServiceEntry "hostnames" field is overly restrictive on FQDNs. 

Tensorflow hardcodes the GCS metadata uri to "http://metadata/..." when downloading from GCS. Istio's admission controller rejects FQDNs of this format which prevents downloading from GCS when using Tensorflow, Istio, and GKE Auth scopes.

https://github.com/tensorflow/tensorflow/blob/7817237d5852c7778d3ba03c40f139e6f2c37a76/tensorflow/core/platform/cloud/compute_engine_metadata_client.cc#L27

**Expected behavior**
The following ServiceEntry should succeed. 
```
 apiVersion: networking.istio.io/v1alpha3
 kind: ServiceEntry
 metadata:
   name: google-metadata-api
 spec:
   hosts:
   - "metadata"
   location: MESH_EXTERNAL
   ports:
   - number: 80
     name: http
     protocol: HTTP
   resolution: DNS
```

**Steps to reproduce the bug**
kubectl apply the above yaml.

**Version**
Istio: 1.0.2,  GKE: 1.11

**Installation**
GKE Addon

**Environment**
GKE
