### ISSUE TITLE
elasticsearch tcp disconnecting

### ISSUE THREAD

**Issue by erikparienty** [istio/istio#11120]
Im trying to install elasticsearch from Helm on namespace with istio auto inject sidecar when installing it with no sidecar all is working well but with sidecar i see the servers disconnect from each other (the masters) and i dont know how to debug it (no virtual service and no gateway only internal communication from elastic-0 to elastic-1)

**the service is **
```
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-master
  labels:
    service: elasticsearch-master
    namespace: elk
spec:
  clusterIP: None
  ports:
  - port: 9200
    name: http-elasticsearch
  - port: 9300
    name: tcp-master
  selector:
    service: elasticsearch-master
```
**and the pod**
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-master
  labels:
    service: elasticsearch-master
    version: 6.5.4
    track: stable
    namespace: elk
spec:
  serviceName: elasticsearch-master
  replicas: 3
  template:
    metadata:
      labels:
        service: elasticsearch-master
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: tcp
        # NOTE: you can increase this resources
        resources:
          requests:
            cpu: 2
            memory: 1Gi
          limits:
            cpu: 2
            memory: 2Gi
        env:
          # NOTE: the cluster name; update this
          - name: cluster.name
            value: elasticsearch-cluster
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          # NOTE: This will tell the elasticsearch node where to connect to other nodes to form a cluster
          - name: discovery.zen.ping.unicast.hosts
            value: "elasticsearch-master-0.elasticsearch-master.elk.svc.cluster.local,elasticsearch-master-1.elasticsearch-master.elk.svc.cluster.local,elasticsearch-master-2.elasticsearch-master.elk.svc.cluster.local"
          - name: ES_JAVA_OPTS
            value: -Xms1g -Xmx1g
          - name: node.master
            value: "true"
          - name: node.data
            value: "false"
          - name: node.ingest
            value: "false"
```
