### ISSUE TITLE
App container unable to connect to network before sidecar is fully running

### ISSUE THREAD

**Issue by linsun** [istio/istio#11130]
**Describe the feature request**
We had users who spend very long time to debug why their app container stops working initially when sidecar is used in istio.  They have found out the app container could not reach out to network for simple things like clone a file from GitHub before the envoy proxy is ready and running.  It is hard to debug this because when they exec into the container after the deployment is running, everything works fine.

**Describe alternatives you've considered**
the current work group used by folks is to put a big sleep like 20 or 30 seconds in their app container to give enough time for envoy to start up.

This is fine once they discover the issue and understand how istio works better, but it can take days for them to discover the issue.

How can we make the experience better?
can we provide some startup hook so app container won't start till envoy sidecar is ready, if the app container starts very fast and requires network connectivity.

**Comment by linsun** [comment]
@esnible pls feel free to add things I missed.  cc @GregHanson

**Comment by esnible** [comment]
This may be a duplicate of https://github.com/istio/istio/issues/9454

**Comment by esnible** [comment]
This may be a duplicate of https://github.com/istio/istio/issues/4341

**Comment by jackkleeman** [comment]
Hey, we here at Monzo have open sourced our solution to this sequencing problem:
https://github.com/monzo/envoy-preflight
The idea is, it's a wrapper around your main application, which ensures it starts after envoy is live, and shuts down envoy when its done. You'll still need to prevent sigterms from reaching envoy.

**Comment by esnible** [comment]
Removing myself because I am not a sidecar networking guru.  That is what we need for this item.

**Comment by howardjohn** [comment]
Long term fix is https://github.com/istio/istio/issues/11366 or maybe https://github.com/kubernetes/kubernetes/issues/65502

**Comment by hzxuzhonghu** [comment]
As we have `ALLOW_ANY`, is this still a big problem?

**Comment by idouba** [comment]
Consider config postStart for app container to check envoy status.
`
 httpGet:
      path: /healthz/ready
`

**Comment by hzxuzhonghu** [comment]
I think this makes sense.
```
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: xxx
    command: 
    lifecycle:
      postStart:           # same as istio-proxy readiness probe, when this hook exec failed, the app container will be restarted
        httpGet:
          path: /healthz/ready
          port: 15020
```
