### ISSUE TITLE
bookinfo demo: istio-proxy doesn't connect to istio-pilot.istio-system

### ISSUE THREAD

**Issue by procyclinsur** [istio/istio#11144]
**Describe the bug**
I have installed bookinfo on EKS according to the instructions [here][1] and [here][2].  

While verifying that the application was installed correctly, i received `000` when trying to bring up the product page.  After checking my network connections VPC/Subnets/Routing/SecurityGroups, I have narrorwed the issue down to being an istio networking issue.

Upon further investigation, I logged into the istio-sidecar container for productpage and have noticed the following error.

```
2019-01-21T09:04:58.949152Z	info	Version root@6f6ea1061f2b-docker.io/istio-1.0.5-c1707e45e71c75d74bf3a5dec8c7086f32f32fad-Clean
2019-01-21T09:04:58.949283Z	info	Proxy role: model.Proxy{ClusterID:"", Type:"sidecar", IPAddress:"10.20.228.89", ID:"productpage-v1-54b8b9f55-jpz8g.default", Domain:"default.svc.cluster.local", Metadata:map[string]string(nil)}
2019-01-21T09:04:58.949971Z	info	Effective config: binaryPath: /usr/local/bin/envoy
configPath: /etc/istio/proxy
connectTimeout: 10s
discoveryAddress: istio-pilot.istio-system:15007
discoveryRefreshDelay: 1s
drainDuration: 45s
parentShutdownDuration: 60s
proxyAdminPort: 15000
serviceCluster: productpage
zipkinAddress: zipkin.istio-system:9411
...
[2019-01-21 09:06:01.039][10][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:41] Unable to establish new stream
[2019-01-21 09:06:28.150][10][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:240] gRPC config stream closed: 14, no healthy upstream
```

This led me to to notice that the istio-proxy is pointing to the `istio-pilot.istio-system:15007` address for discovery.  Only the strange thing was, the kubernetes `istio-pilot.istio-system` service does not seem to be exposing port `15007` as shown below.

```
[procyclinsur@localhost Downloads]$ kubectl get svc istio-pilot --namespace=istio-system
NAME          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                                 AGE
istio-pilot   ClusterIP   172.20.185.72   <none>        15010/TCP,15011/TCP,8080/TCP,9093/TCP   1d
```

Infact none of the services from the `istio-system` namespace seem to expose that port.
I am assuming that this `istio-pilot.istio-system` address is the one used for gRPC and would like to know how to fix this as it seems to be pointing to the wrong address; please correct me if I am wrong.

  [1]: https://istio.io/docs/setup/kubernetes/helm-install/#option-2-install-with-helm-and-tiller-via-helm-install
  [2]: https://istio.io/docs/examples/bookinfo/
**Expected behavior**
{{ What did you expect to happen? }}

**Steps to reproduce the bug**
1. Install cluster via eksctl

```
apiVersion: eksctl.io/v1alpha3
kind: ClusterConfig

metadata:
  name: kube-cluster
  region: us-east-1
  tags: {environment: staging, creator: scott}

vpc:
  id: vpc-088d4632821fe0f52
  subnets:
    Private:
      us-east-1a:
          id: subnet-0b73f4183e00d028c
      us-east-1b:
          id: subnet-0c92168f3faeed699
    Public:
      us-east-1a:
          id: subnet-0f960edf42d22b955
      us-east-1b:
          id: subnet-011a8697711f41dd6

availabilityZones: ["us-east-1a", "us-east-1b"]

nodeGroups:
  - name: kube-cluster-ng-1
    instanceType: m5.large
    desiredCapacity: 2
    minSize: 1
    maxSize: 5
    availabilityZones: ["us-east-1a", "us-east-1b"]
    ami: auto
    volumeSize: 50
    allowSSH: true
    sshPublicKeyPath: my-key-name
```

2. I have installed bookinfo on EKS according to the instructions [here][1] and [here][2]. 

3. During the verificaation step 

**Version**

```
[procyclinsur@localhost Downloads]$ istioctl version
Version: 1.0.5
GitRevision: c1707e45e71c75d74bf3a5dec8c7086f32f32fad
User: root@6f6ea1061f2b
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean

[procyclinsur@localhost Downloads]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"archive", BuildDate:"2018-04-26T09:29:05Z", GoVersion:"go1.10.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
Using the instructions at the link [here][1] 

**Environment**
OS: Fedora28
Cloud: EKS

**Cluster state**
[istio-dump.zip](https://github.com/istio/istio/files/2782815/istio-dump.zip)
