### ISSUE TITLE
new service entries or editing the existing one does not get propagated to istio proxies 

### ISSUE THREAD

**Issue by mbanikazemi** [istio/istio#11145]
**Describe the bug**
Changes from adding new service entries or editing the existing one does not get propagated to istio proxies running as side cars.

**Expected behavior**
Changes will get propagated to istio proxy containers.

**Steps to reproduce the bug**
Create a simple deployment by applying the following:
```
apiVersion: v1
kind: Service
metadata:
  name: myclient
  labels:
    app: myclient
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: myclient
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: myclient
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: myclient
    spec:
      containers:
      - command:
        - /bin/sleep
        - infinity
        image: tutum/curl
        imagePullPolicy: IfNotPresent
        name: myclient
        resources: {}
```
create s service entry by applying the following:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
   name: banix
spec:
   hosts:
   - banix.default.global
   location: MESH_INTERNAL
   ports:
   - name: http1
     number: 8080
     protocol: http
   resolution: DNS
   addresses:
   - 127.255.0.14
   endpoints:
   - address: 169.22.214.227
     ports:
       http1: 15443 
```
if you run the istioctl command below
```
istioctl proxy-status
```
the output will contain something like the following:
```
myclient-5768b9778d-n2hr8.default                      SYNCED     SYNCED       SYNCED (50%)      SYNCED       istio-pilot-7c6cc5b69-6npmh     1.1.0
```
wait a few minutes until you see the output change to:
```
myclient-5768b9778d-n2hr8.default                      SYNCED     SYNCED       SYNCED (50%)      NOT SENT     istio-pilot-7c6cc5b69-6npmh     1.1.0
```
from now on changes to the service entry that affect the route entry will not get sync'ed to the proxy in my client pod.
Simply edit the service entry and change the address from  127.255.0.14 to something else. Notice that from my client it still thinks the address is 127.255.0.14.

**Version**
with daily builds, including release-1.1-20190114-09-15 and release-1.1-20190120-09-16

**Installation**
Using helm templates.

**Environment**
Linux

**Cluster state**
