### ISSUE TITLE
Istio sidecar injection not working with pod annotation set to true and namespace label set to disabled

### ISSUE THREAD

**Issue by nitishm** [istio/istio#11205]
**Describe the bug**
The automatic sidecar injection fails to inject the istio-proxy sidecar in to the sleep pod with the `default` namespaces labeled with `istio-injection=disabled` and the pod template spec annotated with `sidecar.istio.io/inject: "true"`. 

**Expected behavior**
According to the truth table in https://istio.io/help/ops/setup/injection/#the-result-of-sidecar-injection-was-not-what-i-expected the sidecar should be injected in to the sleep pod.

**Steps to reproduce the bug**
- Label Namespace
`kubectl label namespace default istio-injection=disabled`

```
kubectl get namespace -L istio-injection                         130 ↵
NAME                   STATUS    AGE       ISTIO-INJECTION
default                Active    13d       disabled
```

- Add annotation to sleep.yaml
```
kubectl get deployment sleep -o yaml | grep "sidecar.istio.io/inject:" -C3
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      creationTimestamp: null
      labels:
        app: sleep
```

**Version**
istioctl version                                           
```
Version: 1.0.3
GitRevision: a44d4c8bcb427db16ca4a439adfbd8d9361b8ed3
User: root@0ead81bba27d
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean
```

kubectl version
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
Istio was deployed using the istio helm chart, using `helm template` and `kubectl apply`

**Environment**
AWS (self-managed)

**Cluster state**
_Can provide if needed._

**Comment by hzxuzhonghu** [comment]
This is the expected behavior,.

Three stuff influence the sidecar inject.  You should look at the chart carefully.

https://preliminary.istio.io/help/ops/setup/injection/

**Comment by nitishm** [comment]
In that case I am little confused. How can I get this working on a per pod basis ? What knobs do I need to turn ? 

I'd appreciate it if you could help me with this.

**Comment by nitishm** [comment]
@hzxuzhonghu I did figure it out but I had to modify the `istio-sidecar-injector` **configmap** by setting the `default` policy to `disabled` and also modify the `istio-sidecar-injector` **mutatingwebhookconfiguration** to the right _namespaceSelector_. 

In my case, I set it to, _(depends on how you want the namespaceSelector to return true. In my case I want it to return true if it the label is set on the namespace irrespective of whether it is enabled or disabled.)_
```
 namespaceSelector:
    matchExpressions:
    - key: istio-injection
      operator: In
      values:
      - disabled
      - enabled
```

In retrospect I think I misunderstood what components each of the columns referred to in the truth table.
