### ISSUE TITLE
Incorrect/misleading documentation of gateways field of VirtualService CRD

### ISSUE THREAD

**Issue by johngmyers** [istio/istio#11203]
**Describe the bug**
The sentence "To apply the rules to both gateways and sidecars, specify `mesh` as one of the gateway names." in the documentation of the gateways field of VirtualService is incorrect. Specifying `mesh` as one of the gateway names does not in fact apply the rules to both gateways and sidecars; it only applies them to sidecars.

**Expected behavior**
Parsing the sentence with standard English semantic rules, I expected that specifying a gateways field with the single value `mesh` would apply the rules to both gateways and sidecars.

**Steps to reproduce the bug**
Install bookinfo application. Edit the bookinfo VirtualService as follows:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - "*"
  gateways:
  - mesh
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: 9080
```

Attempt to access the productpage through the gateway URL.

**Version**
istio 1.0.5 on Kubernetes 1.10.12

**Installation**
Helm

**Environment**
AWS
