### ISSUE TITLE
tcp ingress port not listening

### ISSUE THREAD

**Issue by zhqworld** [istio/istio#11240]
**Describe the bug**
Creating a gateway for ingress to accept TCP has no result, ingress not listening on new ports.
(If I switch the protocol from TCP to HTTP then ingress will take it and listening on those ports)

**Expected behavior**
ingress should listen on new TCP ports

**Steps to reproduce the bug**
1. create a gateway with tcp ports:
```
cat <<EOF | kubectl create -f -
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  generation: 1
  name: httpbin-gateway
  namespace: httpbin
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - a.com
    port:
      name: tcp
      number: 30201
      protocol: TCP
  - hosts:
    - b.com
    port:
      name: tcp-2
      number: 30202
      protocol: TCP
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
EOF
```

2. check ingress port:
istioctl -n istio-system proxy-config listener $(kubectl get po -l istio=ingressgateway -n istio-system -o jsonpath='{.items[0]..metadata.name}')
```
ADDRESS     PORT      TYPE
0.0.0.0     80        HTTP
0.0.0.0     443       HTTP
```
None of TCP port 30201 or 30202 listening.

NOTE: If swith the protocol to HTTP for 30201 and 30202, then check the ingress port it is listening.

**Version**
istioctl version: 1.1.0-snapshot.3
kubectl version: 1.10.3

**Installation**
Istio was installed by helm

**Comment by liminw** [comment]
@duderino @costinm Is this a known issue?

**Comment by zhqworld** [comment]
It didn't listen for tcp even though I had virtualservice there:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test
  namespace: httpbin
spec:
  gateways:
  - httpbin-gateway.httpbin.svc.cluster.local
  hosts:
  - a.com
  tcp:
  - match:
    - port: 30201
    route:
    - destination:
        host: tcpservice.tcp-ns.svc.cluster.local
        port:
          number: 30201

**Comment by zhqworld** [comment]
yes, I added both in ingress svc as well.

```
istio-ingressgateway     NodePort    10.50.131.196   <none>        80:30000/TCP,443:30443/TCP,30200:30200/TCP,30201:30201/TCP,30202:30202/TCP,31400:31400/TCP,15011:32460/TCP,8060:32027/TCP,853:31550/TCP,15030:31926/TCP,15031:31336/TCP   26d```

**Comment by costinm** [comment]
The exposed Service part is not critical for this, listener should still show up in envoy.

I applied the 2 configs from this bug - and in pilot logs I get:

* gateway omitting listener "0.0.0.0_30201" due to: must have more than 0 chains in listener: &v2.Listener{Name:"0.0.0.0_30201", Address:core.Address{Address:(*core.Address_SocketAddress)(0xc003901ae8), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}, FilterChains:[]listener.FilterChain{}, UseOriginalDst:nil, PerConnectionBufferLimitBytes:nil, Metadata:(*core.Metadata)(nil), DeprecatedV1:(*v2.Listener_DeprecatedV1)(nil), DrainType:0, ListenerFilters:[]listener.ListenerFilter(nil), ListenerFiltersTimeout:(*time.Duration)(nil), Transparent:nil, Freebind:nil, SocketOptions:[]*core.SocketOption(nil), TcpFastOpenQueueLength:nil, BugfixReverseWriteFilterOrder:nil, XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}
* gateway omitting listener "0.0.0.0_30202" due to: must have more than 0 chains in listener: &v2.Listener{Name:"0.0.0.0_30202", Address:core.Address{Address:(*core.Address_SocketAddress)(0xc003901c10), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}, FilterChains:[]listener.FilterChain{}, UseOriginalDst:nil, PerConnectionBufferLimitBytes:nil, Metadata:(*core.Metadata)(nil), DeprecatedV1:(*v2.Listener_DeprecatedV1)(nil), DrainType:0, ListenerFilters:[]listener.ListenerFilter(nil), ListenerFiltersTimeout:(*time.Duration)(nil), Transparent:nil, Freebind:nil, SocketOptions:[]*core.SocketOption(nil), TcpFastOpenQueueLength:nil, BugfixReverseWriteFilterOrder:nil, XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}

I'll debug further...

In general - it really helps to include pilot logs in the bugs :-)

**Comment by costinm** [comment]
2 changes needed:
- on the gateway host, use '*' ( port matchers don't know about hostnames )
- the important one: the gateway name in VirtualService is just the simple name, not fully qualified.

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - "*"
      port:
        name: tcp
        number: 30201
        protocol: TCP
    - hosts:
        - b.com
      port:
        name: tcp-2
        number: 30202
        protocol: TCP
    - hosts:
        - '*'
      port:
        name: http
        number: 80
        protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test
spec:
  gateways:
  - httpbin-gateway
  hosts:
  - a.com
  tcp:
  - match:
    - port: 30201
    route:
    - destination:
        host: fortiotls.fortio-control.svc.cluster.local
        port:
          number: 8080
```
