### ISSUE TITLE
Authn policy without port selector not configure TCP port

### ISSUE THREAD

**Issue by incfly** [istio/istio#11246]
**Expected behavior**
All ports declared in the container 

**Steps to reproduce the bug**
Configure a service with authn policy as 

```
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "mtls-strict-for-a"
spec:
  targets:
  - name: "a"
  peers:
    - mtls:
        mode: STRICT
```

**Version**
1.1 head version.

**Environment**
GKE
