### ISSUE TITLE
k8s: Istio Proxy and control plane pods should have request cpu/memory sizes by default

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#11280]
**Describe the bug**
In order to allow the k8s scheduler and HPA to work properly for both control plane AND customer pods with side-cars and HPA, IStio should provide default requests sizes for BOTH cpu and memory
for proxy and all control plane pods.

**Expected behavior**
A customer pod with HPA enabled for memory utilization, needs to scale properly, but needs to have all containers with request size for memory.  By default proxy does not.  

To make this easier for folks, we should define request cpu and memory sizes for proxy and all control plane pods. 

Currently commented out:
https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/values.yaml#L133-L140
```
# Resources for the sidecar.
    resources:
      requests:
        cpu: 10m
      #  memory: 128Mi
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
```
This should change to at least have memory also defined.  I'm think 50m cpu and 128mi memory is a good place to start.
```
defaultResources:
    requests:
      cpu: 10m
    #   memory: 128Mi
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
```
Having no memory size and very low cpu will lead the k8s kubelet to hit OutOfCPU/Memory issues and possible crash nodes.  This should change to something more reasonable and closer to reality.

Pilot has some defined, the rest of the pods should as well. 
```
# Resources for a small pilot install
resources:
  requests:
    cpu: 500m
    memory: 2048Mi
```
     
   

**Steps to reproduce the bug**

**Version**

**Installation**

**Environment**

**Cluster state**
