### ISSUE TITLE
Enable istio monitoring using external prometheus

### ISSUE THREAD

**Issue by 1hanymhajna** [istio/istio#11304]
**Describe the feature request**
we are looking to have one monitoring dashboard for whole kuberenets ( logging, istio, services that not running with istio proxy).
We deployed pormetheus and grafana using stable helm versions:
`helm install -f ./monitoring/prometheus-values.yaml stable/prometheus --name prometheus --namespace monitoring`
And
`helm install -f ./monitoring/grafana-values.yaml stable/grafana --name grafana --namespace monitoring`

Our prometheus values file: (yaml)
[prometheus-values.txt](https://github.com/istio/istio/files/2799921/prometheus-values.txt)

Is there any way that we can configure our promethues to get data from istio?

**Describe alternatives you've considered**
An alternative option that we tried is to connect our grafana to two promethues sources ( one external, and one from istio) it succeeds to connect but we don't see any data coming when we install an istio mesh dashboard

**Comment by douglas-reid** [comment]
Yes. You should be able to copy the relevant jobs from the prometheus config that Istio provides: https://github.com/istio/istio/blob/master/install/kubernetes/helm/subcharts/prometheus/templates/configmap.yaml

**Comment by dileep-p** [comment]
@douglas-reid this url throwing 404.

**Comment by isaacmorci** [comment]
This is now the URL: https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/prometheus/templates/configmap.yaml

**Comment by douglas-reid** [comment]
I'll also add that the new istio/installer comes with prom operator configuration as well, which should provide a mechanism for this as well.

Closing for now.

**Comment by chenrulongmaster** [comment]
I think we should use Prometheus Federation to resolve your question. We are tring this..

**Comment by yiyan-wish** [comment]
We have  already deployed prometheus on k8s cluster , and the how the istio using the existed prometheus?

**Comment by iVampireSP** [comment]
These yaml works for me

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-oper-istio-controlplane
  namespace: istio-system
  labels:
    release: prometheus
spec:
  jobLabel: istio
  selector:
    matchExpressions:
      - {key: istio, operator: In, values: [mixer,pilot,galley,citadel,sidecar-injector]}
  namespaceSelector:
    any: true
  endpoints:
  - port: http-monitoring
    interval: 15s
  - port: http-policy-monitoring
    interval: 15s
```

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-oper-istio-dataplane
  namespace: istio-system
  labels:
    monitoring: istio-dataplane
    release: prometheus
spec:
  selector:
    matchExpressions:
      - {key: istio-prometheus-ignore, operator: DoesNotExist}
  namespaceSelector:
    any: true
  jobLabel: envoy-stats
  endpoints:
  - path: /stats/prometheus
    targetPort: http-envoy-prom
    interval: 15s
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_container_port_name]
      action: keep
      regex: '.*-envoy-prom'
    - action: labelmap
      regex: "__meta_kubernetes_pod_label_(.+)"
    - sourceLabels: [__meta_kubernetes_namespace]
      action: replace
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_pod_name]
      action: replace
      targetLabel: pod_name
```

original post: https://zhuanlan.zhihu.com/p/281747776
