### ISSUE TITLE
istioctl authn tls-check incorrect client status

### ISSUE THREAD

**Issue by castlemilk** [istio/istio#11315]
**Describe the bug**
when running `istioctl authn tls-check` incorrect client status is reported as follows:

```bash
./istio-1.0.5/bin/istioctl authn tls-check
Stderr when execute [/usr/local/bin/pilot-discovery request GET /debug/authenticationz ]: gc 1 @0.018s 21%: 0.59+1.4+4.8 ms clock, 2.9+0.25/0.70/1.5+24 ms cpu, 4->4->1 MB, 5 MB goal, 5 P
gc 2 @0.043s 17%: 0.015+1.2+2.3 ms clock, 0.079+1.2/1.1/1.0+11 ms cpu, 4->4->2 MB, 5 MB goal, 5 P

HOST:PORT           STATUS       SERVER     CLIENT   AUTHN POLICY     DESTINATION RULE
...
example.com:443     CONFLICT     mTLS       HTTP     default/         example-external/mesh
...
```
**_Note that the client status is **HTTP**_, should be _mTLS_**

this is with the following `DestinationRule` defined:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: example
spec:
  host: example.com
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      mode: MUTUAL
      caCertificates: /etc/certs/example-ca/ca.crt
      clientCertificate: /etc/certs/example-client-cert/tls.crt
      privateKey: /etc/certs/example-client-cert/tls.key
    portLevelSettings:
    - port:
        number: 443
       tls:
         mode: MUTUAL
         sni: example.com
         caCertificates: /etc/certs/example-ca/ca.crt
         clientCertificate: /etc/certs/example-client-cert/tls.crt
         privateKey: /etc/certs/example-client-cert/tls.key
```

**Expected behavior**
With `mode: MUTUAL` specified in the `TLSSettings`, I would expect this to be correctly classified at mTLS client connection.
**It operates as expected with `mode: ISTIO_MUTUAL` set.**

**Steps to reproduce the bug**
set up the described `DestinationRule` above and run `./istio-1.0.5/bin/istioctl`

**Version**
istio 1.0.5

**Installation**
kubectl apply

**Environment**
local machine (docker for mac)
