### ISSUE TITLE
Anti-Affinity for control plane for node and zones

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#11333]
**Describe the feature request**
Configure a high level of availability for control plane deployments
Apply this to: pilot, sidecar-injector, policy, telemetry

requiredDuringSchedulingIgnoredDuringExecution node level anti affinity
preferredDuringSchedulingIgnoredDuringExecution zone level anti affinity

**Describe alternatives you've considered**

**Additional context**

**Comment by kramvan1** [comment]
@linsun  cc

**Comment by thomschke** [comment]
Please apply this to **(ingress/egress)-gateways** too.

These days it's very easy to create k8s-multi-zone-clusters (like [gke regional cluster](https://cloud.google.com/kubernetes-engine/docs/concepts/regional-clusters)), but anti-affinity is needed for that.

**Comment by thomschke** [comment]
Hi @linsun, any good news?

The official istio charts (1.1.0-rc.2) provide deployments with:
- dynamic autoscaling for: 
  - gateways (Ingress/Egress/ILB)
  - mixer (Policy, Telemetry)
  - pilot
- configurable replica count for:
  - galley
  - citadel

That's very good. But **without anti-affinity rules** these charts are **not suitable for HA clusters in production**. 

So I have to merge the anti-affinity rules manually in the above deployments like:

```
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                ...
                topologyKey: failure-domain.beta.kubernetes.io/zone
            - weight: 100
              podAffinityTerm:
                ...
                topologyKey: kubernetes.io/hostname
```

**Comment by linsun** [comment]
@kramvan1 @thomschke sorry for the slow reply.  Checking on istio 1.1 rc2, I saw affinity is already specified in gateways, galley, sidecar-injector and many other components.  Not configurable but it is configured as below.   Would this satisfy your needs?

```
affinity:      
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - ppc64le
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - s390x
```

**Comment by kramvan1** [comment]
@linsun that is for the node arch types, does not really help with pod anti-affinity.

**Comment by linsun** [comment]
@kramvan1 can you suggest an example yaml blob that are needed for pod?  wonder if it's generic enough.   or should we leave this as configurable for operators?

**Comment by thomschke** [comment]
@linsun please make it configurable (like `.values.podAnnotations` or `.values.nodeSelector` etc.)

**Comment by thomschke** [comment]
BTW: `galley` and `citadel` have no PDB and HPA yet, so it's possible to scale up this components n > 1 for HA setups? Sorry, but I can't find detail HA documentations yet (only [this](https://preliminary.istio.io/docs/concepts/performance-and-scalability/#scalability-and-sizing-guide)).

**Comment by kramvan1** [comment]
@linsun something like this should do the trick, just replace the app-name.
```
      podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values: ["app-name"]
            topologyKey: "kubernetes.io/hostname"
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values: ["app-name"]
            topologyKey: "failure-domain.beta.kubernetes.io/zone"
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values: ["app-name"]
              topologyKey: failure-domain.beta.kubernetes.io/region
```
