### ISSUE TITLE
Mixer uses mTLS?

### ISSUE THREAD

**Issue by joberdick** [istio/istio#11390]
**Describe the bug**
Enabling mTLS cluster wide causes telemetry and policy failures

**Expected behavior**
telemetry and policy function as they did before mTLS policy was enabled.

**Steps to reproduce the bug**
Apply the following mesh policy:
```
apiVersion: "authentication.istio.io/v1alpha1"
kind: "MeshPolicy"
metadata:
  name: "default"
spec:
  peers:
  - mtls: {}
```
Things work until a destination rule is applied to enable the client side of mTLS:

```
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "default"
  namespace: "default"
spec:
  host: "*.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```
Then services in the default namespace fail to call mixer:
```
[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:73] Mixer Report failed with: UNAVAILABLE:upstream connect error or disconnect/reset before headers
```
**Version**
1.1.0-snapshot.5

**Installation**
`helm upgrade istio install/kubernetes/helm/istio --namespace istio-system --set global.k8sIngressSelector=ingressgateway --set ingress.enable=false --set gateways.enabled=true --set gateways.istio-ingressgateway.type=NodePort --set  global.mtls.enabled=false --set tracing.enabled=true --set grafana.enabled=true --set prometheus.enabled=true --set kiali.enabled=true --set kiali.tag=v0.13
`
**Environment**
EKS

Should mixer be apart of mTLS or not? The policy I used comes directly from documentation. So either the documentation needs to be updated or my mixer is not correctly enforcing mTLS. It does not look like pilot controls envoy for either istio-telemtry or istio-policy pods.

```
istioctl proxy-status istio-telemetry-5966b85884-7dzcq.istio-system
Warning! error execing into istio-pilot-5bcbc558c-x29c9/istio-system discovery container: gc 1 @0.018s 8%: 0.065+2.0+1.6 ms clock, 0.13+0.40/0.091/1.9+3.3 ms cpu, 4->4->2 MB, 5 MB goal, 2 P
gc 2 @0.032s 12%: 0.011+3.0+2.3 ms clock, 0.022+0.25/0.41/2.5+4.7 ms cpu, 4->4->3 MB, 5 MB goal, 2 P

Error: unable to find config dump in Pilot responses
```
