### ISSUE TITLE
Web-sockets upgrade not working in alphav3

### ISSUE THREAD

**Issue by shashankn91** [istio/istio#11498]
**Describe the bug**
Prefix matching rules to upgrade the connection to web sockets are applied(kubctl apply) . When a request is made to WebSocket URL 404 occurs . It was observed that the rules are not seen in the envoy routes(istioctl proxy-config routes).

**Expected behavior**
For URI's filtered Web sockets must be working.

**Steps to reproduce the bug**
apply the Virtual Service rules and you see envoy routes not being updated. 

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fashtagbackend-virtual-service
  namespace: fashtagbackend
spec:
  gateways:
  - fashtagbackend-gateway
  hosts:
  - 'fashtagbackend.fashtag.info'
  - fashtagbackend-service.backend.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: "/replenishment/"
    route:
    - destination:
        host: fashtagbackend-service
      weight: 100
    websocketUpgrade: true
  - match:
    - uri:
        prefix: "/inventoryCount/"
    route:
    - destination:
        host: fashtagbackend-service
      weight: 100
    websocketUpgrade: true
  - match:
    - uri:
        prefix: "/transfer"
    route:
    - destination:
        host: fashtagbackend-service
      weight: 100
    websocketUpgrade: true
  - match:
    - uri:
        prefix: "/api/"
    route:
    - destination:
        host: fashtagbackend-service
      weight: 100
```

**Version**
kubectl version - Major:"1", Minor:"13"
istioctl version - 1.0.5
**Installation**
Istio is installed using helm
**Environment**
AWS

**Comment by ymesika** [comment]
Websocket upgrade should be enabled by default.
Can you try the same configuration after removing the `websocketUpgrade: true` entries from the routes?

**Comment by shashankn91** [comment]
I did remove the websocketUpgrade:true . I am still having the same issue.
Below is the configuration for route.
```
  http:
  - route:
    - destination:
        host: fashtagbackend-service


```

Registration of web sockets URL

```
INFO  [2019-02-04 09:08:43,144] io.dropwizard.websockets.WebsocketBundle: Registering websocket endpoints: 

    WS      /replenishment/{replnishmentRequestId} (com.fashtag.sockets.inventory.replenishment.ReplenishmentServer)

```

Log which says 404 when open socket connetion request is sent.
`27.59.80.71 - - [04/Feb/2019:09:15:56 +0000] "GET /replenishment/33b4a605-c72d-4837-8df4-ab2d5f5c807e HTTP/1.1" 404 282 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36" 3
`
