### ISSUE TITLE
Provide examples of external services

### ISSUE THREAD

**Issue by esnible** [istio/istio#11504]
This Issue for creating a few examples of ServiceEntries for accessing external services.

I found work items https://github.com/istio/istio/issues/10847 and https://github.com/istio/istio/issues/7664 which seem to show users have difficulty writing ServiceEntries.  I propose we supply some service entries examples in _samples/external_

I tried to create sample service entries for Github and Pypi.  My first version Service Entries work, but not together!

*FIRST VERSIONS*

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: make-git-work
spec:
  hosts:
  - github.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  - number: 22
    name: ssh
    protocol: tcp
```
and
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: make-pypi-work
spec:
  hosts:
  - "pypi.python.org"
  ports:
  - number: 443
    name: tcp
    protocol: TCP
  resolution: DNS
  location: MESH_EXTERNAL
```

Although these work individually, there is a port conflict when they are applied together.

```
git clone https://github.com/istio/istio.io.git
Cloning into 'istio.io'...
fatal: unable to access 'https://github.com/istio/istio.io.git/': SSL: certificate subject name (www.python.org) does not match target host name 'github.com'
```

I next attempted to do this properly using ServiceEntries with HTTPS and SNI and failed.  The connections were getting dropped.

**Comment by esnible** [comment]
*INCORRECT SECOND VERSIONS*

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: make-pypi-work
spec:
  hosts:
  - "*.python.org"
  endpoints:
  - address: pypi.python.org
  location: MESH_EXTERNAL
  resolution: DNS
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: make-pypi-work
spec:
  hosts:
  - pypi.python.org
  tls:
  - match:
    - port: 443
      sniHosts:
      - pypi.python.org
    route:
    - destination:
        host: '*.python.org'
        port:
          number: 443
```

and

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: make-git-work
spec:
  hosts:
  - github.com
  endpoints:
  - address: github.org
  location: MESH_EXTERNAL
  resolution: DNS
  ports:
  - number: 443
    name: https
    protocol: TLS
  - number: 22
    name: ssh
    protocol: tcp
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: make-git-work
spec:
  hosts:
  - github.com
  tls:
  - match:
    - port: 443
      sniHosts:
      - github.com
    route:
    - destination:
        host: github.com
        port:
          number: 443
  ```

**Comment by vadimeisenbergibm** [comment]
There are three kinds of configuration for external services: HTTP, TLS and TCP. For HTTP and TLS, the host must be specified, for TCP the IP ranges must be specified.

Documentation: 
* for HTTP and TLS https://preliminary.istio.io/docs/tasks/traffic-management/egress/
* for TCP https://preliminary.istio.io/blog/2018/egress-tcp/#mesh-external-service-entry-for-an-external-mysql-instance 

So, the configuration items are: 

1.  www.github.com, port 443, TLS

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: git-https
spec:
  hosts:
  - github.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: git-https
spec:
  hosts:
  - github.com
  tls:
  - match:
    - port: 443
      sniHosts:
      - github.com
    route:
    - destination:
        host: github.com
        port:
          number: 443
```

1.  www.github.com, port 22, TCP

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: github-tcp
spec:
  hosts:
  - dummy.github.com # not used
  addresses: # from https://help.github.com/articles/about-github-s-ip-addresses/
  -  "192.30.252.0/22"
  - "185.199.108.0/22"
  -  "140.82.112.0/20"
  -  "192.30.252.0/22"
  - "185.199.108.0/22"
  -  "140.82.112.0/20"
  - "13.229.188.59/32"
  - "13.250.177.223/32"
  - "18.194.104.89/32"
  - "18.195.85.27/32"
  - "35.159.8.160/32"
  - "52.74.223.119/32"
  - "192.30.252.153/32"
  - "192.30.252.154/32"
  - "185.199.108.153/32"
  - "185.199.109.153/32"
  - "185.199.110.153/32"
  - "185.199.111.153/32"
  - "54.87.5.173/32"
  - "54.166.52.62/32"
  - "23.20.92.3/32"
  ports:
  - name: tcp
    number: 22
    protocol: tcp
  location: MESH_EXTERNAL
```

**Comment by absc6** [comment]
Not sure if I need to create a new thread. But how does DNS resolution takes place for external service. If service is present in Istio/Kubernetes cluster, does it take routes from the server?
Also, say the network is behind a proxy, how do we distinguish external network calls from internal network.

**Comment by esnible** [comment]
@absc6 The ServiceEntry example above includes
```
  resolution: DNS
  location: MESH_EXTERNAL
```
The Location distinguishes internal from external.  The resolution `DNS` causes Envoy to use its configured DNS on the hostname.

**Comment by absc6** [comment]
@esnible  I tried to configure an external service, I am getting **UNAVAILABLE:upstream connect error or disconnect/reset before headers**. Can you please have a look.

The service is accessible from the server. There are no restricting in iptables, the service is present outside of istio mesh.
```
curl http://test.abc.com:18080/testing/1
{"user","1}
```

Below is my configurations, I have removed any other service entries to void conflicts:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: generic-gateway
spec:
  selector:
    istio: ingressgateway # we are using default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*" #all inbound hosts
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gateway-routing 
spec:
  hosts:
  - "*"
  gateways:
  - generic-gateway
  http:
  - match:
    - uri:
        prefix: /testing
    route:
    - destination:
        host: test.abc.com 
        port:
          number: 18080
  - route:
    - destination:
        host: test.abc.com
        port:
          number: 18080
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
spec:
  selector:
    istio: egressgateway #Research other values for this field and significance.
  servers:
  - port:
      number: 80
      name: http  
      protocol: HTTP
    hosts:
    - "*" 
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: testconnect-http 
spec:
  hosts:
  - test.abc.com 
  ports:
  - number: 18080 
    name: httpext 
    protocol: HTTP
  location: MESH_EXTERNAL 
  resolution: DNS
```
