### ISSUE TITLE
Using both Exact and Prefix URI matches results in unexpected behavior

### ISSUE THREAD

**Issue by bradenwright** [istio/istio#11535]
**Describe the bug**
I need to route 1 path `/aggregator` to a different backed than all other paths.  To do so I tried using:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: aggregator
spec:
  hosts:
  - "*.example.com"
  gateways:
  - istio-system/istio-public
  http:
  - match:
    - authority:
        exact: myapp.example.com
      uri:
        exact: /aggregator
    route:
    - destination:
        port:
          number: 80
        host: aggregator.{{ .Release.Namespace }}.svc.cluster.local
```
and

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend
spec:
  hosts:
  - "*.example.com"
  gateways:
  - istio-system/istio-public
  http:
  - match:
    - authority:
        exact: myapp.example.com
      uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: frontend.{{ .Release.Namespace }}.svc.cluster.local
```

All paths get sent to backend: `frontend.{{ .Release.Namespace }}.svc.cluster.local` including `myapp.example.com/aggregator`

**Expected behavior**
`myapp.example.com/aggregator` to route to `aggregator.{{ .Release.Namespace }}.svc.cluster.local` instead of `frontend.{{ .Release.Namespace }}.svc.cluster.local`

**Steps to reproduce the bug**
Deploy to 2x virtual services with path based routing

**Version**
k8s: `v1.10.12-gke.1`
istio `1.10`

**Installation**
helm

**Environment**
GKE

**Cluster state**
n/a

Note I was able to use a workaround which is to not match the path /aggregator via regex:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend
spec:
  hosts:
  - "*.example.com"
  gateways:
  - istio-system/istio-public
  http:
  - match:
    - authority:
        exact: myapp.example.com
      uri:
        regex: ^/(?!aggregator).*$
    route:
    - destination:
        port:
          number: 80
        host: frontend.{{ .Release.Namespace }}.svc.cluster.local
```
but this is pretty ugly, especially for other services where I have more than 1 path which needs to be routed to a different service (and I haven't even tested if multiple nots will work)

Thanks for the help, Istio's been great so far!
