### ISSUE TITLE
ConsistentHashLB: Hash based on request path/url

### ISSUE THREAD

**Issue by berstend** [istio/istio#11554]
I have a use-case where it'd be amazing to use the consistent hash-based [load balancer](https://preliminary.istio.io/docs/reference/config/istio.networking.v1alpha3.html#LoadBalancerSettings-ConsistentHashLB) based on the path (or URL) of the request.

Unfortunately it seems like I cannot use `httpHeaderName` to extract the path or request url.

Or is there a way to do this currently that I missed? 

Thanks!

**Comment by murarisumit** [comment]
@berstend  can you pls guide me in explaining more in it. What I found out in envoy documentation here "https://www.envoyproxy.io/docs/envoy/v1.9.0/intro/arch_overview/load_balancing/load_balancers" that it doesn't provide such load-balancing functionality.

Do we need something like this : https://www.haproxy.com/blog/haproxys-load-balancing-algorithm-for-static-content-delivery-with-varnish/

hashing the whole url, including the query string
```
    backend bk_static
      balance uri whole
      hash-type consistent
```

Query string parameter hash
```
    backend bk_static
      balance uri whole
      hash-type consistent
```

Do we need need to implement such load-balancing at envoy's end ?

**Comment by berstend** [comment]
@murarisumit thanks for your followup questions.

Unfortunately I'm not too familiar with the envoy proxy internals (yet), to know with certainty wether or not envoy supports url based load balancing currently. 

Let me instead lay out my use-case in more detail:
```
https://app.com/projectid1/
https://app.com/projectid2/
https://app.com/projectid3/
```
As a developer using istio I wish to use the URL (or path) as the ring key for load balancing/sticky sessions. Currently that doesn't seem possible.

In my scenario it's not too relevant if query strings are part of the hash or not.

My current workaround:

**Add a Cloudflare Worker which will add the URL to the request headers:**
```js
addEventListener('fetch', event => {
  event.respondWith(handleRequest(event.request))
})

/**
 * Add `x-url` header to fetch request
 * @param {Request} request
 */
async function handleRequest(request) {
  const headers = new Headers(request.headers)
  headers.set('x-url', request.url)
  return fetch(request, { headers })
}
```

**Use the `x-url` request header as loadBalancer key:**

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ $.Release.Name }}-dest-{{ $versionId }}
spec:
  host: {{ $.Release.Name }}
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: x-url
  subsets:
    - name: version-{{ $versionId }}
      labels:
        app: {{ $.Release.Name }}
        version: {{ $versionId }}
```

This works as expected (sticky sessions based on request URL) but has a dependency on having Cloudflare in front of the cluster. Would love to simplify this and have istio allow me to use the request url directly.

Thanks!

**Comment by berstend** [comment]
This envoy issue might be related: https://github.com/envoyproxy/envoy/issues/2436

**Comment by epa095** [comment]
Is it possible to get this re-opened @rlenglet ?

**Comment by kaiburjack** [comment]
In case you want to have consistent hash-based load balancing (i.e. for "sharding" purposes) that is only dependent on the request's *path* (and query string), you can use a `DestinationRule` like the following:
```yaml
spec:
  host: {{ $.Release.Name }}
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: ':path'
```
This uses the pseudo-header `:path` (written _with_ the colon) that Envoy understands (also works for HTTP/1.1 requests).
Earlier, I actually added an intermediate proxy (nginx) between the clients/callers and the load-balanced/sharded destination service (in our case Varnish) where that nginx proxy would add a custom header based on the URL of the request, but that was too complicated in the end.
Then I found that for our case, at least, sharding/load-balancing on the `:path` pseudo-header was sufficient (no need to also make the destination 'host' part of the hash).
This *does* work and we use it in production right now.

**Comment by junoriosity** [comment]
@kaiburjack Many thanks for your input, could you provide some examples, such that I can see whether this would be well-suited for our use case?

Specifically, I do not quite understand how I would have to understand `:path`.

**Comment by kaiburjack** [comment]
@junoriosity `:path` is a so-called "pseudo-header" in Envoy.
See for example: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#path
That's because it is not _actually_ a header in a HTTP request, but is the "request URI" (in terms of the HTTP 1.1 specification) in the "request line" of a HTTP request, such as the `/some/path?query=123&abc=xyz` in `GET /some/path?query=123&abc=xyz HTTP/1.1`.
So, it will effectively include the path _as well as_ the query string of the request URI.
You can treat it like a header name everywhere where Envoy expects a header name, such as in the `hash_policy` of a virtual host's `routes` configuration (expressed in Istio via the `DestinationRule`'s `trafficPolicy.loadBalancer.consistentHash.httpHeaderName` field).
So, like I said, you can use `:path` as described in the `DestinationRule` spec above for hash-based load balancing when you want to hash based on the HTTP's request URI (path + query string).
Our use-case here was to have horizontal load balancing for HTTP caches, where same requests (with same HTTP request line) will not go to different HTTP cache instances and thusly not fetched by each of these caches from the backend servers individually, so effectively implementing "sharding" (based on the request URI). This had a nice effect of reducing the time-to-first-byte (and effectively the "Largest Contentful Paint") metric.

**Comment by musabshak** [comment]
This is super neat. 

I wonder if there's another similar pseudo-header that only takes into account the path and not the query parameters. I have requests of form `/<bucketName>/<gitLFSObjecthash>?awsSigV4QueryParams...`. I would like requests for the same git object to go to the same pod consistently. `:path` doesn't work because the AWS SigV4 pre-signed URL query params will be different everytime (different signature, different timestamp, etc). 

As mentioned above, I could always set up a reverse proxy to add a custom header (ignoring the query params). But wondering if there is an Envoy hack to accomplish the same.

**Comment by kaiburjack** [comment]
@musabshak yes, _only_ using a DestinationRule is not sufficient when you want load balancing based on the _path_ part of the URL but _without_ the query string. For this, you _need_ something that generates an additional HTTP request header that Envoy then can use to perform the load balancing on.

*However* you _don't need_ a full additional HTTP _server_ in front of the load balanced target service to do this.
You can make use of a Lua Filter to extract on the path part of the request URL and write this to an additional artificial HTTP request header before Envoy makes the load balancing decision:

This should work
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: add-request-header-with-path
spec:
  workloadSelector:
    labels:
      app: istio-ingressgateway
      istio: ingressgateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.lua
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
            defaultSourceCode:
              inlineString: |
                function envoy_on_request(request_handle)
                  local path = request_handle:headers():get(":path")
                  local pathWithoutQuery = string.match(path, "([^?]+)")
                  request_handle:headers():add("x-request-hash", pathWithoutQuery)
                end
```

When you install this on the ingress gateway (or whatever service you want as the *client*/source for requests that ultimately should load balance towards another service based on the path of the URL) it will generate a new HTTP request header called "x-request-hash" and fill it with only the path-part of the URL.

You would then define a DestinationRule like this for the target service that should be load-balanced:
```yaml
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: target-service
spec:
  host: target-service
  trafficPolicy:
    loadBalancer:
      consistentHash:
        # This request header is computed by a Lua filter installed
        # in the HTTP Connection Manager right before the router filter,
        # such that, when the load balancing decision is computed,
        # this header is present in the HTTP request.
        httpHeaderName: 'x-reques-thash'
```
