### ISSUE TITLE
Enable --server-dry-run with kubectl on k8s >= 1.12

### ISSUE THREAD

**Issue by ayj** [istio/istio#11560]
kubectl supports the `--dry-run` for CRD in Kubernetes versions >= 1.12. This allows users to pre-validate their configuration with `kubectl apply` without it being persisted. To enable this feature for Istio CRD we need to set `sideEffects=None` in the validatingwebhookconfiguration (see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#webhook-v1beta1-admissionregistration-k8s-io). We also need to verify that this can be safely set for k8s <= 1.12.

xref: https://github.com/istio/istio/issues/10429

**Comment by esnible** [comment]
I tried this interactively using K8s 1.13 client and server.  I set `sideEffects=None` with `kubectl edit validatingwebhookconfigurations istio-galley` and sent bogus DestinationRules.  I was not able to get the desired experience.

```
cat <<EOF | kubectl apply --dry-run=true -f -
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: destination-rule-httpbin
spec:
  host: httpbin
  subsets:
  - name: '*'
    labels:
      version: v1
EOF
```

was accepted, even though without `--dry-run=` it was rejected because of the subset name.

If I run without `--dry-run` and use `-v 999` to check the traffic between the CLI and API server, the CLI attempts a PATCH and gets a 500 error

```
... curl -k -v -XPATCH  -H "Content-Type: application/merge-patch+json" -H "Accept: application/json" -H "User-Agent: kubectl/v1.13.4 (darwin/amd64) kubernetes/c27b913" 'https://c2.us-south.containers.cloud.ibm.com:25968/apis/networking.istio.io/v1alpha3/namespaces/default/destinationrules/destination-rule-httpbin'
... PATCH https://c2.us-south.containers.cloud.ibm.com:25968/apis/networking.istio.io/v1alpha3/namespaces/default/destinationrules/destination-rule-httpbin 500 Internal Server Error in 115 milliseconds
```

The XPATCH is not sent when `--dry-run=true`.

I am looking into why the 500 was returned instead of a normal code.
