### ISSUE TITLE
RbacConfig not working

### ISSUE THREAD

**Issue by andreipetrescu95** [istio/istio#11567]
**Describe the bug**
Pilot does not create filter configs for services, other than the httpbin service.

**Expected behavior**
I expect Istio to create filter configs for all my services, not just one, but I have no idea why it only works with this one.

**Steps to reproduce the bug**
I have the following RbacConfig applied in my cluster:

```apiVersion: "rbac.istio.io/v1alpha1"
kind: RbacConfig
metadata:
  name: default
spec:
  mode: 'ON_WITH_INCLUSION'
  inclusion:
    namespaces: ["app"]
```

In the `app` namespace, there are 3 services, with the following YAMLs:

```
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: app
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend
  namespace: app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
        version: v1
    spec:
      #serviceAccountName: backend-sa
      containers:
      - name: backend
        image: docker.io/citizenstig/httpbin
        ports:
        - containerPort: 8000
```

```
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: app
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
  namespace: app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      #serviceAccountName: frontend-sa
      containers:
      - name: frontend
        image: docker.io/citizenstig/httpbin
        ports:
        - containerPort: 8000
```

```
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: app
  labels:
    app: httpbin
spec:
  ports:
  - name: http
    port: 8000
  selector:
    app: httpbin
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpbin
  namespace: app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      containers:
      - image: docker.io/citizenstig/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 8000
```

The logs from istio-pilot are the following:

```
2019-02-06T19:41:17.709419Z     info    registering for apiVersion rbac.istio.io/v1alpha1
2019-02-06T19:42:05.513697Z     info    rbac    no service role in namespace app
2019-02-06T19:42:05.513711Z     info    rbac    no service role binding in namespace app
2019-02-06T19:42:05.513884Z     info    rbac    built filter config for httpbin.app.svc.cluster.local
2019-02-06T19:49:42.521865Z     info    rbac    no service role in namespace app
2019-02-06T19:49:42.521908Z     info    rbac    no service role binding in namespace app
2019-02-06T19:49:42.525097Z     info    rbac    built filter config for httpbin.app.svc.cluster.local
```

As you can see, it is only creating filter configs for httpbin.

Also, ran `curl localhost:15000/config_dump -s` in each istio-proxy of the pods, only the httpbin pod show something when grep-ing for `rbac`

**Version**
Istio 1.0.5
Kubernetes 1.12.5

**Installation**
via `helm template`, and the with `kubectl apply -f istio.yaml`

**Environment**
VMs running in vSphere and deployed using Kubespray
