### ISSUE TITLE
Issue with ELB annotations when using websockets

### ISSUE THREAD

**Issue by mabushey** [istio/istio#11579]
This works fine for plain https, but breaks on websockets:
```
apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-west-2:xxx:certificate/xxx-xxxx-xxxx-xxxx-xxx"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
```

We have to manually change https -> http to ssl -> tcp on 31390 with our cert in the AWS console.
Is there anyway to configure this to come up correctly?
