### ISSUE TITLE
Multiple services for the same workload in Mixer (telemetry and policy)

### ISSUE THREAD

**Issue by dicarlo2** [istio/istio#11578]
**Describe the bug**
In order to workaround issues with referring and connecting to statefulset pods directly (see https://github.com/istio/istio/issues/10659), we create a service per pod in the statefulset. For example:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: thanos-store
  namespace: monitoring-potato-beetle
  labels:
    app: thanos-store
spec:
  selector:
    app: thanos-store
  ports:
  - name: http-prom
    port: 10902
  - name: grpc
    port: 10901
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-store-0
  namespace: monitoring-potato-beetle
  labels:
    app: thanos-store
spec:
  selector:
    app: thanos-store
    statefulset.kubernetes.io/pod-name: thanos-store-0
  ports:
  - name: http-prom
    port: 10902
  - name: grpc
    port: 10901
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-store-1
  namespace: monitoring-potato-beetle
  labels:
    app: thanos-store
spec:
  selector:
    app: thanos-store
    statefulset.kubernetes.io/pod-name: thanos-store-1
  ports:
  - name: http-prom
    port: 10902
  - name: grpc
    port: 10901
```

One minor issue this causes is that when using authz every service name must be included in the `ServiceRole`:

```yaml
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRole
metadata:
  name: thanos-query.monitoring-potato-beetle-thanos-store.monitoring-potato-beetle
  namespace: monitoring-potato-beetle
  labels:
    app: thanos-query
spec:
  rules:
  - services:
    - thanos-store.monitoring-potato-beetle.svc.cluster.local
    - thanos-store-0.monitoring-potato-beetle.svc.cluster.local
    - thanos-store-1.monitoring-potato-beetle.svc.cluster.local 
    constraints:
    - key: destination.port
      values:
      - "10901"
    methods:
    - POST
```

The much worse issue, however, is that the service name used in telemetry appears to change over time:

<img width="1078" alt="screenshot 2019-02-06 16 04 47" src="https://user-images.githubusercontent.com/1311014/52382172-0f495280-2a29-11e9-84ab-f04ada4936aa.png">

This screenshot shows a similarly setup service `grafana` with one additional service for the single workload (pod) `grafana-0`:

<img width="1073" alt="screenshot 2019-02-06 15 57 54" src="https://user-images.githubusercontent.com/1311014/52382128-f3de4780-2a28-11e9-8292-6eab3c444fd3.png">

**Expected behavior**

One service name is used so that telemetry is consistent. Perhaps there could be an annotation that marks a service as the canonical service to use in policy and telemetry.

**Steps to reproduce the bug**
See description of setup.

**Version**
release-1.1-20190130-09-16

**Installation**
Mostly equivalent to helm with flat multicluster and cni.

**Environment**
GKE

**Related**
https://github.com/istio/istio/issues/1459
https://github.com/istio/istio/issues/10659
