### ISSUE TITLE
Unknown attributes error in Mixer logs - Istio 1.1

### ISSUE THREAD

**Issue by PhilipGough** [istio/istio#11589]
**Describe the bug**

According to the [preliminary doc](https://preliminary.istio.io/docs/reference/config/policy-and-telemetry/attribute-vocabulary/). Some additional attributes (request.query_params, request.url_path) have been added as of 1.1. 

However when an instance is created that references these new attributes, error such as follows are being produced in mixer logs and the instance never registers.

```
2019-02-07T12:14:16.227957Z error config does not conform to schema of template 'authorization':
unable to build message field: action, unable to encode fieldEncoder path: request.url_path | "/".
unable to build primitve encoder for:path request.url_path | "/". unknown attribute request.url_path
```

**Expected behavior**
Expect to be able to use attributes in 1.1 namely request.query_params and request.url_path as specified in the docs

**Steps to reproduce the bug**
Deploy 1.1 and attempt to create an instance that uses these attributes, for example:

```
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
  name: example-auth
  namespace: istio-system
spec:
  template: authorization
  params:
    subject:
      user: request.query_params["user_key"] | request.headers["x-user-key"] | request.api_key | ""
    action:
      path: request.url_path | "/"
      method: request.method | "get"
```

**Version**
1.1 snapshot 4
