### ISSUE TITLE
VirtualService rules change when active namespace is changed

### ISSUE THREAD

**Issue by mabushey** [istio/istio#11606]
Istio 1.0.5, k8s 1.11.6

Changing the active namespace changes the namespace in the Virtualservice. Notice the `host:` line change from `httpbin.httpbin.svc.cluster.local` to `httpbin.microservice-stg.svc.cluster.local` 
```
➜  kops  git:(master) ✗ kubectl get virtualservices -o yaml | grep httpbin
        {"apiVersion":"networking.istio.io/v1alpha3","kind":"VirtualService","metadata":{"annotations":{},"name":"microservice-stg","namespace":"microservice-stg"},"spec":{"gateways":["elb-gateway"],"hosts":["microservice-stg.example.com","microservice-stg.green.example.com","microservice-stg.blue.example.com"],"http":[{"match":[{"uri":{"exact":"/info-xxx"}}],"rewrite":{"uri":"/info"},"route":[{"destination":{"host":"microservice-xxx.microservice-stg.svc.cluster.local","port":{"number":8080}}}]},{"match":[{"uri":{"prefix":"/xxx"}}],"route":[{"destination":{"host":"microservice-xxx.microservice-stg.svc.cluster.local","port":{"number":8080}}}]},{"match":[{"uri":{"exact":"/info-yyy"}}],"rewrite":{"uri":"/info"},"route":[{"destination":{"host":"microservice-yyy.microservice-stg.svc.cluster.local","port":{"number":8080}}}]},{"match":[{"uri":{"prefix":"/yyy"}}],"route":[{"destination":{"host":"microservice-yyy.microservice-stg.svc.cluster.local","port":{"number":8080}}}],"timeout":"360s"},{"match":[{"uri":{"exact":"/info-zzz"}}],"rewrite":{"uri":"/info"},"route":[{"destination":{"host":"microservice-zzz.microservice-stg.svc.cluster.local","port":{"number":8080}}}]},{"match":[{"uri":{"prefix":"/zzz"}}],"route":[{"destination":{"host":"microservice-zzz.microservice-stg.svc.cluster.local","port":{"number":8080}}}],"timeout":"360s"},{"match":[{"uri":{"prefix":"/"}}],"route":[{"destination":{"host":"httpbin.httpbin.svc.cluster.local","port":{"number":8000}}}]}]}}
          host: httpbin.httpbin.svc.cluster.local
➜  kops  git:(master) ✗ kubens default
Context "k8s-blue.example2.com" modified.
Active namespace is "default".
➜  kops  git:(master) ✗
➜  kops  git:(master) ✗ kubectl get virtualservices -o yaml | grep httpbin
        {"apiVersion":"networking.istio.io/v1alpha3","kind":"VirtualService","metadata":{"annotations":{},"name":"microservice-stg","namespace":"default"},"spec":{"gateways":["elb-gateway"],"hosts":["microservice-stg.example.com","microservice-stg.blue.example.com","microservice-stg.green.example.com"],"http":[{"match":[{"uri":{"exact":"/info-xxx"}}],"rewrite":{"uri":"/info"},"route":[{"destination":{"host":"microservice-xxx.microservice-stg.svc.cluster.local","port":{"number":8080}}}]},{"match":[{"uri":{"prefix":"/xxx"}}],"route":[{"destination":{"host":"microservice-xxx.microservice-stg.svc.cluster.local","port":{"number":8080}}}]},{"match":[{"uri":{"exact":"/info-yyy"}}],"rewrite":{"uri":"/info"},"route":[{"destination":{"host":"microservice-yyy.microservice-stg.svc.cluster.local","port":{"number":8080}}}]},{"match":[{"uri":{"prefix":"/yyy"}}],"route":[{"destination":{"host":"microservice-yyy.microservice-stg.svc.cluster.local","port":{"number":8080}}}],"timeout":"360s"},{"match":[{"uri":{"exact":"/info-zzz"}}],"rewrite":{"uri":"/info"},"route":[{"destination":{"host":"microservice-zzz.microservice-stg.svc.cluster.local","port":{"number":8080}}}]},{"match":[{"uri":{"prefix":"/zzz"}}],"route":[{"destination":{"host":"microservice-zzz.microservice-stg.svc.cluster.local","port":{"number":8080}}}],"timeout":"360s"},{"match":[{"uri":{"prefix":"/"}}],"route":[{"destination":{"host":"httpbin.microservice-stg.svc.cluster.local","port":{"number":8000}}}]}]}}
          host: httpbin.microservice-stg.svc.cluster.local
```

**Comment by mabushey** [comment]
Somehow the rules got applied against multiple namespaces (depending on active namespace), which makes no sense as the route file specifies the `microservice-stg` namespace. I moved httpbin from `httpbin.microservice-stg` to `httpbin.httpbin`. The VirtualService stayed in `microservice-stg`.

**Comment by mabushey** [comment]
It looks like the same VirtualService can be applied to multiple namespaces, and as they're "global", one will randomly take priority.

**Comment by esnible** [comment]
Most of the Istio samples do not specify a namespace.  For example _samples/httpbin/httpbin.yaml_ has no namespace.  It can be applied to whatever namespace you wish using `-n <namespace>`.

This allows users to deploy the service in whichever namespace they want without modifying the .yaml.

**Comment by mabushey** [comment]
@esnible I gave up on any of the Istio examples, and highly recommend everyone to do the same. Saying they're a wild goose chance is an understatement. Even the spec pages for Istio are almost always wrong. Love the project, but have never seen more inaccurate docs in my life. Even the httpbin you're mentioning is an out of date fork. I'm using the real one.

My bug report is that if you do not specify a namespace in the VirtualService. you can set up a VirtualService for routing, update the VirtualService, and if you changed the default namespace, you will have both the new and the old routing rules in different namespaces and have no idea which one Istio is going to pick.

There's some other issues with this going on too, I can apply a VirtualService in default and xxxx-stg and they work, but if I apply them in xxxx-prd they do not take effect.

**Comment by esnible** [comment]
I am trying to make the samples better.

The httpbin.yaml example is the latest version and can be seen at https://github.com/istio/istio/blob/release-1.1/samples/httpbin/httpbin.yaml

How do you change the namespace of a virtual service?  I tried with `kubectl edit` and `kubectl patch` and always received ```Error from server (BadRequest): the namespace of the object (istio-system) does not match the namespace on the request (default)``` from Kubernetes.

**Comment by mabushey** [comment]
@esnible
> I am trying to make the samples better.
That's awesome! You have your work cut out for you! Thank you. :)

I figured out a little more. I have services in `xxxx-stg` and `xxxx-prd`. I tried putting the VirtualServices in each namespace, but only one worked. This was on a fresh setup of K8s 1.11 with kops and Istio 1.0.5. Once I set them to both use a namespace of `default`, both sets of rules worked.

To change the namespace you have to do a `kubectl delete -f virtualservice-stg`, edit the file, then ``kubectl apply -f virtualservice-stg`

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: xxxx-prd
  namespace: default
```

**Comment by esnible** [comment]
@mabushey II reproduced a problem, I am not sure if it is yours because I don't know what you are using for `hosts`.  Are you using two VirtualServices for the *same host*, in two different namespaces?  I don't think it is allowed, because the VirtualService is not bound to the namespace it is created in.

I created two VirtualServices `default` and `ns`, both for ns1-httpbin.ns1.svc.cluster.local:80, in different Namespaces, and Istio created an Envoy configuration with two Routes both with the same name.


```
kubectl create ns ns1
cat <<EOF | kubectl -n ns1 apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - ns1-httpbin
  http:
  - match:
     - uri:
        prefix: /
    route:
    - destination:
        host: httpbin
        port:
          number: 8000
EOF

kubectl create ns ns1
cat <<EOF | kubectl -n default apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - ns1-httpbin.ns1.svc.cluster.local
  http:
  - match:
     - uri:
        prefix: /
    route:
    - destination:
        host: httpbin
        port:
          number: 8000
EOF
```

Then I checked a pod in default (it could be any pod, I used a ratings instance from bookinfo) for the Envoy route configuration.  I found Envoy was misconfigured with two entries for the same route.  (I have the `jq` JSON query language tool installed).

`kubectl exec ratings-v1-65dd9d89dd-ww7jm -c istio-proxy -- curl --silent localhost:15000/config_dump | jq '.configs[]?.dynamic_route_configs[]?.route_config?.virtual_hosts[]?.name' /tmp/config_dump.json  | uniq -c`

The output showed one entry for every Envoy route but two identical route entries:

```
...
   1 "istio-ingressgateway.istio-system.svc.cluster.local:80"
   2 "ns1-httpbin.ns1.svc.cluster.local:80"
   1 "productpage.default.svc.cluster.local:80"
...
```

@andraxylia @rshriram What should Istio do in this situation?

**Comment by rshriram** [comment]
if you use shortnames in the hosts, they will be expanded based on the namespace of the virtualService. It is possible that k8s triggers a CRD change update causing Pilot to reevaluate the virtualServices, expanding short names like httpbin to httpbin.Namespace.default.svc.cluster.local ..

**Comment by mabushey** [comment]
@esnible - no my host for `stg` is `xxx-stg.example.com`. and `prd` is `xxx-prd.example.com`
Putting them in `xxx-stg` and `xxx-prd` namespaces resulted in one set of rules that worked, and one that did not. Putting them both in `default` results in both rules working.

**Comment by mabushey** [comment]
@rshriram I've used both full names and also short names within the namespace, that does not seem to change the behavior.

**Comment by linsun** [comment]
@mabushey would it be possible for you to provide some examples?  Virtual Service in 1.0 is global scoped so I would expect only 1 is effective (probably the newer one).  

I am having a bit trouble to understand this ```Putting them both in default results in both rules working.```.   Do you mean you have a virtual service for stage host, and the same named VS for prod host where stage and prod are the 2 services with 2 deployments?

**Comment by linsun** [comment]
@mabushey I would like to make sure we have an automated tests for your scenario to demonstrate the expected behavior for this in 1.1 or 1.1.x.

In 1.1, I'm expecting you to use the new export_To support to mark if you want a given VS to be exported.  Further, you can also use the sidecar API to indicate the ingress and egress scope of the sidecar for your service.

**Comment by mabushey** [comment]
@linsun 

Gateway:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: elb-gateway
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-west-2:{act#}:certificate/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http-elb
      protocol: HTTP
    hosts:
    - "example.com"
    - "*.example.com"
    tls:
      httpsRedirect: true # sends 301 redirect for http requests
  - port:
      number: 443
      name: https-elb
      protocol: HTTP
    hosts:
    - "example.com"
    - "*.example.com"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all
spec:
  podSelector: {}
  ingress:
  - {}

```

Prd:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: xxx-prd
  namespace: default
spec:
  hosts:
  - "xxx-prd.example.com"
  - "xxx-prd.green.example.com"
  - "xxx-prd.blue.example.com"
  gateways:
  - elb-gateway
  http:
  - match:
...
```
Stg:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: xxx-stg
  namespace: default
spec:
  hosts:
  - "xxx-stg.example.com"
  - "xxx-stg.green.example.com"
  - "xxx-stg.blue.example.com"
  gateways:
  - elb-gateway
  http:
  - match:
...
```

When they are both in the default namespace they work. When stg is in xxx-stg and prd is in www-prd, Only stg works, which I assume is because it was applied first.
