### ISSUE TITLE
Neither webhook nor istioctl validation detects extra fields in CRDs

### ISSUE THREAD

**Issue by esnible** [istio/istio#11634]
To reproduce:

```
cat <<EOF | kubectl -v 9 apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: productpage
unexpected_junk:
   still_more_junk:
spec:
  host: productpage
EOF
kubectl -v 9 get destinationrule productpage
```

Although there is a section `unexpected_junk` the admission controller happily accepts it.  `istioctl validate` does as well.

The `kubectl get` with `-v 9` option shows that Kubernetes is still holding the unexpected junk and transmitting it over the networking.

This is not a problem if the extra data is just comments, but as a user shows in https://discuss.istio.io/t/configuration-validation/738 there is a problem if the extra data was intended to go under `spec` but because of YaML tabs it didn't.
