### ISSUE TITLE
virtual service not calling service entry for external service

### ISSUE THREAD

**Issue by absc6** [istio/istio#11671]
We have the following configuration. The object is to call external service via istio-ingressgateway.
When the curl request is triggered we are getting 
```
< HTTP/1.1 503 Service Unavailable
< content-length: 69
< content-type: text/plain
< date: Mon, 11 Feb 2019 17:16:50 GMT
< server: envoy
<
UNAVAILABLE:upstream connect error or disconnect/reset before headers
```
Istio server does have access to external service, present on different server.
Jaeger trace shows virtual service getting called and destination (test1.abc.com) is getting populated, but then it is showing error **async outbound|9091||istio-policy.istio-system.svc.cluster.local egress**. It seems service entry is not getting called.
```
$curl http://test.abc.com:18070/testing/1
{"user":"1"}
```
Below are the configuration:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: generic-gateway
spec:
  selector:
    istio: ingressgateway # we are using default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*" #all inbound hosts
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gateway-routing 
spec:
  hosts:
  - "*"
  gateways:
  - generic-gateway
  http:
  - match:
    - uri:
        prefix: /testing
    route:
    - destination:
        host: 1test.abc.com 
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
spec:
  selector:
    istio: egressgateway #Research other values for this field and significance.
  servers:
  - port:
      number: 80
      name: http  
      protocol: HTTP
    hosts:
    - "*" 
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: testconnect-http 
spec:
  hosts:
  - test1.abc.com 
  ports:
  - number: 80 
    name: http
    protocol: HTTP
  location: MESH_EXTERNAL 
  resolution: DNS
  endpoints:
  - address: test.abc.com
      ports:
	    http: 18070
```
