### ISSUE TITLE
Host Header service require between pod

### ISSUE THREAD

**Issue by anthonyhaussman** [istio/istio#11670]
Kuberntes: **v1.13.2**
Istio: **1.0.5**

Hi,

I have a simple configuration with an Nginx  who proxy_pass to a service like this:

```
      upstream oauth {
        server oauth;
    
        keepalive 2;
      }   

        location /oauth/token {
          proxy_set_header Host $host;
          proxy_pass http://oauth/oauth/token;
}
```

Without an ISTIO running, the service work great.

Here my problem is when I push istio with sidecar, the service returns a 404 Not Found.
I know this is a known bug and if I set the ` proxy_set_header Host` with the service name `oauth` it worked.

The problem is in my workflow, I need to have the default header Host for some verification.
I have tried to follow the solution found on https://github.com/istio/istio/issues/9107 but without success.
I have set the `nginx.ingress.kubernetes.io/service-upstream: "true"` on my ingress:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/client-max-body-size: 5m
    nginx.ingress.kubernetes.io/proxy-body-size: 5m
    nginx.ingress.kubernetes.io/service-upstream: "true"
  name: dev-gateway
  namespace: istio-system
spec:
  rules:
  - host: graphql-istio.kube.test.gg
    http:
      paths:
      - backend:
          serviceName: istio-ingressgateway
          servicePort: 80
  tls:
  - hosts:
    - graphql-istio.kube.test.gg
    secretName: wildcard-kube-test-gg-tls
status:
  loadBalancer:
    ingress:
    - {}
```

Add the host into my virtualservices:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: oauth
  namespace: test
spec:
  hosts:
  - oauth
  - graphql-istio.kube.test.gg
  http:
  - route:
    - destination:
        host: oauth
        subset: v1


apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gateway
  namespace: test
  hosts:
  - gateway
  - graphql-istio.kube.test.gg
  http:
  - route:
    - destination:
        host: gateway
        subset: v1
```

My istio gateway:
```
apiVersion: v1
items:
- apiVersion: networking.istio.io/v1alpha3
  kind: Gateway
  metadata:
    name: test-gateway
    namespace: test
  spec:
    selector:
      istio: ingressgateway
    servers:
    - hosts:
      - graphql-istio.kube.test.gg
      port:
        name: http
        number: 80
        protocol: HTTP
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

But with this config I still have a 404.
Does it exists a configuration where the Host header can be bypass easily?
Am I missing something?

Thanks for your help.
