### ISSUE TITLE
ECONNRESET with Redis

### ISSUE THREAD

**Issue by cptaffe** [istio/istio#11689]
**Describe the bug**

Redis connections fail with `ECONNRESET` when using Istio Proxy and a `ServiceEntry`

**Expected behavior**

Redis connections should not fail

**Steps to reproduce the bug**
1. Have a Redis server running outside the mesh
2. Add a `ServiceEntry` like the following
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: redis
spec:
  hosts:
    - redis.example.com
  ports:
    - number: 6379
      name: redis
      protocol: TCP
  location: MESH_EXTERNAL
```
3. Try to connect to redis using `redis-cli` from the cluster in a namespace with `istio-injection=enabled`
```sh
kubectl run -it --rm redis-test --image=redis -- /bin/sh
# redis-cli -h redis.example.com
redis.example.com:6379> flushall
Error: Connection reset by peer
```

I confirmed the above does work on namespaces without `istio-injection=enabled`, and the same `ServiceEntry` approach works with postgresql.

**Version**

Istio 1.0.5
Kubernetes 1.11+ (v1.11.5-eks-6bad6d)

**Installation**

From the Helm chart as follows:
```
curl -sSL https://git.io/getLatestIstio | sh -
helm template \
  --name istio \
  --namespace istio-system \
  --set 'global.mtls.enabled=true' \
  --set 'global.controlPlaneSecurityEnabled=true' \
  --set 'gateways.istio-ingressgateway.type=NodePort' \
  ./istio-1.0.5/install/kubernetes/helm/istio \
  > istio.yaml
kubectl apply -f istio.yaml
```

I also change `istio-ingressgateway` to `kind: DaemonSet`, add `externalTrafficPolicy: Local`, and remove the HPA.

**Environment**

EKS on AWS using the EKS-optimized AMI (based on Amazon Linux 2)
Redis is an Elasticache instance (non-cluster), Redis 5.0
