### ISSUE TITLE
galley validation still expects older gateway resource format

### ISSUE THREAD

**Issue by zhqworld** [istio/istio#11686]
**Describe the bug**
With sds node agent on ingress gateway, there is no more need to provide certificate path in gateway resources, but it failed with following yaml:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: https-gateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https-name1
      protocol: HTTPS
    tls:
      mode: SIMPLE
    hosts:
    - "httpbin1.example.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - "httpbin1.example.com"
  gateways:
  - https-gateway
  http:
  - match:
    - uri:
        prefix: /status
    - uri:
        prefix: /delay
    route:
    - destination:
        port:
          number: 8000
        host: httpbin
```

The failure message:

```
virtualservice.networking.istio.io "httpbin" created
Error from server: error when creating "STDIN": admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: 2 errors occurred:
```

**Expected behavior**
Gateway resource that does not specify a certificate path should be accepted by Galley given that the SDS agent loads the certificates dynamically from the API server.

**Steps to reproduce the bug**
After the Istio installation, the SDS agent for ingress gateway needs to be enabled in the configuration. Then use above yaml to reproduce the bug.

**Version**
kubernetes version: 1.12.5
Istio version:
image: gcr.io/istio-release/galley:release-1.1-20190211-09-16
imageID: docker-pullable://gcr.io/istio-release/galley@sha256:7154d0dedc05a432186cde9c6b258398eb733dbd17c3dfef217fa945db67e97b

**Installation**
Installed using helm.

**Environment**
private environment

**Cluster state**
n/a
