### ISSUE TITLE
/debug/authenticationz reports confusing "mTLS" for non-inject namespaces (affects istioctl authn tls-check)

### ISSUE THREAD

**Issue by esnible** [istio/istio#11697]
Istio only performs mTLS for pods with sidecar injected.  Even if the mesh default policy is to inject, if a namespace is created and the user doesn't label it `istio-injection=enabled` the sidecar will not be injected.

If a Service is created in a namespace that is not labeled `istio-injection=enabled` the `istioctl authn tls-check` will report the server uses mTLS.  However there is no sidecar to enforce it, and attempts to contact that pod from any pod with a sidecar will fail.

To reproduce,

```
kubectl create ns no-inj-pol
cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Service
metadata:
  labels:
    app: no-inj-pol
  name: no-inj-pol
  namespace: no-inj-pol
spec:
  ports:
  - name: "4999"
    port: 4999
    targetPort: 80
  selector:
    app: no-inj-pol
  type: LoadBalancer
EOF
istioctl authn tls-check | grep no-inj-pol
```

The `tls-check` will show

```
no-inj-pol.no-inj-pol.svc.cluster.local:4999                  OK           mTLS       mTLS       default/         default/istio-system
```

I believe the first "mTLS" is incorrect, and it should read "non-Istio", "no sidecar", or "HTTP".

_istioctl_ just asks Pilot.  To reproduce w/o istioctl do 

```
kubectl -n istio-system exec $(kubectl -n istio-system get pod --selector istio=pilot --output jsonpath='{.items[0].metadata.name}') -- curl localhost:8080/debug/authenticationz
```

I encountered this because I deployed a pod in a namespace without the label to diagnose a user issue and received `UNAVAILABLE:upstream connect error or disconnect/reset before headers/tmp/IstioTest/` messages.
