### ISSUE TITLE
Mixer tracing does not work with 1.1.0-snapshot.6

### ISSUE THREAD

**Issue by robertpanzer** [istio/istio#11755]
**Describe the bug**
After enabling tracing the proxies start sending their traces to jaeger.
I created rules that make Mixer reject the request with a validUseCount of 1.
However the mixer-policy pod does not sample the trace, even though I installed with `--set pilot.traceSampling=100.0 --set tracing.enabled=true`.

Debugging a bit through mixer it seems like the Istio-proxies are sending x-b3-traceids with a length of 128 bits.
When the traceId is extracted from the incoming request it fails because it tries to parse it as a 64 bit int:
https://github.com/istio/istio/blob/727e719b56362060924cd75bef6ed731cc41b272/vendor/github.com/uber/jaeger-client-go/zipkin/propagation.go#L72-L94
Therefore the new SpanContext is not created with the `sampled` flag that is coming with the request, but as an empty SpanContext.

Looking at the bootstrap config of the istio-proxy I can also see that 128 bit traceIds are explicitly enabled:
```json
  "tracing": {
    "http": {
      "name": "envoy.zipkin",
      "config": {
        "collector_cluster": "zipkin",
        "collector_endpoint": "/api/v1/spans",
        "trace_id_128bit": "true",
        "shared_span_context": "false"
      }
    }
  }
```
(I checked that the proxy is running docker.io/istio/proxyv2:1.1.0-snapshot.6)

**Expected behavior**
If sampling is enabled, the Mixer adapter check results should also appear in the logs.

**Steps to reproduce the bug**
Install Istio with tracing enabled.
Then apply a configuration that requires call of the istio-policy mixer:
```yaml
apiVersion: "config.istio.io/v1alpha2"
kind: checknothing
metadata:
  name: checknothing
  namespace: istio-system
spec:
---
apiVersion: "config.istio.io/v1alpha2"
kind: denier
metadata:
  name: deny-all
  namespace: istio-system
spec:
  validUseCount: 1
  status:
    code: 7
    message: "Go away"
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: deny-all
  namespace: istio-system
spec:
  match: request.headers["foo"] == "bar"
  actions:
  - handler: deny-all.denier
    instances:
    - checknothing.checknothing
```
Execute a request and check that it is rejected by the policy.
Check jaeger for the trace.
It should not contain any hint about the mixer call.

**Version**
Istio 1.1.0-snapshot.6
Kubernetes 1.10.11 running on Docker for Mac

**Installation**
```
helm install . --name istio --namespace istio-system -f values-istio-auth-mcp.yaml  --set global.mtls.enabled=true --set global.tracing.enabled=true --set pilot.traceSampling=100.0 --set tracing.enabled=true --set grafana.enabled=true --set global.useMCP=false
```

**Environment**
Local Docker for Mac

**Cluster state**
