### ISSUE TITLE
Sidecar resource not updated properly

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#11762]
**Describe the bug**
When a Sidecar resource is modified, it does not seem to update correctly.

**Expected behavior**
Applying a new config should have the same effect as deleting the config, then applying the new config, but it does not.

**Steps to reproduce the bug**
Turned on `global.outboundTrafficPolicy.mode=ALLOW_ANY` (not sure if related)

1. No Sidecar - all external traffic is blocked (`curl google.com` 404s)
2. Apply Sidecar resource
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
spec:
  egress:
    - hosts:
      - ./*
```
After this external traffic works

3. `kubectl apply` same config, changed to `hosts: []` - external traffic still works
4. `kubectl remove` the Sidecar - traffic blocked
5. `kubectl apply` the config with  `hosts: []` - traffic blocked

Step 3 and 5 should have the same result.

**Version**
Istio 1.1 Snapshot 6

**Installation**
Helm

**Environment**
GKE

@rshriram
