### ISSUE TITLE
Custom Ingress Gateway doesnt work in a different namespace

### ISSUE THREAD

**Issue by 4c74356b41** [istio/istio#11763]
**Describe the bug**
no rules get populated in envoy proxy getting a bunch of `gRPC config stream closed: 14, no healthy upstream` in the gateway pod logs

**Expected behavior**
custom gateway working

**Steps to reproduce the bug**
follow this article: https://preliminary.istio.io/blog/2019/custom-ingress-gateway/#configuring-the-custom-ingress-gateway

**Version**
k8s: 1.12.4
istio: 1.0.6 and 1.1.0.beta5

**Installation**
helm install and helm template. followed both paths: https://preliminary.istio.io/docs/setup/kubernetes/helm-install/

**Environment**
Azure, AKS 1.12.4

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

I'm really lost. tried on 2 different clusters, different ways\version of setting up istio, nothing seems to work. gateway doesnt throw errors only when in the istio-system namespace, but I'm unable to reference it using name.namespace for some reason (again, no routes in the envoy proxy).

**Comment by mabushey** [comment]
It's the same with VirtualServices. They need to all go in `default` if you want them to work right.

**Comment by 4c74356b41** [comment]
I'm not sure, they seem to work with the istio-system namespace, but not with custom gateway. At least I'm unable to make them work.

**Comment by 4c74356b41** [comment]
ok, I made a bit more progress, it appears, I can see the listener with the proper domain configured, I can see curl returning proper certificate when I curl the endpoint, but it gives me 404. I can access the service endpoint internally from the gateway and\or using port-forward.

I can see the dynamic_active_cluster pointing to my service, but in the dynamic_route_configs I only see blackhole for https.443.https

**Comment by 4c74356b41** [comment]
```
apiVersion: v1
kind: Service
metadata:
  name: omg
  namespace: testota
  labels:
    app: service1
    version: v1
spec:
  ports:
  - port: 8080
    targetPort: 80
    name: http-service
  selector:
    app: service1
    version: v1

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: team1
spec:
  hosts:
  - sub.domain.com
  gateways:
  - custom-gateway.istio-system.svc.cluster.local
  http:
  - route:
     - destination:
        host: omg.testota.svc.cluster.local
        port:
          number: 8080
```
