### ISSUE TITLE
Custom gateway detects wrong port for the service

### ISSUE THREAD

**Issue by 4c74356b41** [istio/istio#11785]
**Describe the bug**
different port appears in the gateway route
```
[
    {
        "cluster":  "outbound|443||A.dev.svc.cluster.local", <<<< should be 8088 as well
        "timeout":  "0.000s",
        "maxGrpcTimeout":  "0.000s"
    },
    {
        "cluster":  "outbound|8088||B.dev.svc.cluster.local",
        "timeout":  "0.000s",
        "maxGrpcTimeout":  "0.000s"
    }
]
```

virtual services:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: a
  namespace: istio-system
spec:
  gateways:
  - custom-gateway.istio-system.svc.cluster.local
  hosts:
  - istio.xxx.com
  http:
  - match:
    - uri:
        prefix: /path_a
    route:
    - destination:
        host: a.dev.svc.cluster.local
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: b
  namespace: istio-system
spec:
  gateways:
  - custom-gateway.istio-system.svc.cluster.local
  hosts:
  - istio.xxx.com
  http:
  - match:
    - uri:
        prefix: /path_b
    route:
    - destination:
        host: b.dev.svc.cluster.local
```

services:
```
apiVersion: v1
kind: Service
metadata:
  name: a
  namespace: dev
spec:
  clusterIP: 10.64.3.112
  ports:
  - name: http
    port: 8088
    protocol: TCP
    targetPort: http
  - name: metrics
    port: 8090
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/instance: a
    app.kubernetes.io/name: a
  sessionAffinity: None
  type: ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: b
  namespace: dev
spec:
  clusterIP: 10.64.10.252
  ports:
  - name: http
    port: 8088
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: b
    app.kubernetes.io/name: b
  sessionAffinity: None
  type: ClusterIP
```

**Expected behavior**
proper port :)

**Steps to reproduce the bug**
create a custom gateway in istio-system namespace, create a custom wildcard certificate, map 2 virtual services to the same gateway\dns name, create 2 services in a different namespace, create egress entry for service A to talk to the database (not sure last bit is relevant).

**Version**
AKS : 1.12.5
Istio 1.0.6

**Installation**
Helm upgrade --install like in the docs

**Environment**
Azure AKS

Sometimes I also get a weird case when second pod of the gateway is being created on its own. if I remap service to listen on 443 service A starts working, service B just works fine.
