### ISSUE TITLE
TLS modes PASSTHROUGH and SIMPLE do not work in same cluster

### ISSUE THREAD

**Issue by adenis-sv** [istio/istio#11786]
**Describe the bug**
I am trying to implement TLS termination on Gateway for one application and on backend side for another.
Following tasks from the documentation.

    https://istio.io/docs/tasks/traffic-management/secure-ingress/ 1
    For TLS mode SIMPLE
    https://preliminary.istio.io/docs/examples/advanced-gateways/ingress-sni-passthrough/ 1
    For TLS mode PASSTHROUGH

Each of them separately works fine.

But if I an trying to deploy them both the second one reports error on attempt to connect.
The first one looks the winner.
Tried to use the unique port names in Gateway and Server but it did not help as well.

Error for the second application looks like

curl -vvv https://myapp.mydomain.com
*   Trying 34.123.123.123…
* TCP_NODELAY set
* Connected to myapp.mydomain.com (34.123.123.123) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /usr/local/etc/openssl/cert.pem
  CApath: /usr/local/etc/openssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to myapp.mydomain.com:443 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to myapp.mydomain.com

**Expected behavior**
Applications with TLS mode SIMPLE and PASSTHROUGH should work in the same cluster

**Steps to reproduce the bug**
    Install application with TLS mode SIMPLE
    https://istio.io/docs/tasks/traffic-management/secure-ingress/ 1
    and with PASSTHROUGH
    https://preliminary.istio.io/docs/examples/advanced-gateways/ingress-sni-passthrough/ 1
    
Tried to adjust Gateways to make port name unique like the following

Gateway for tls mode SIMPLE

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
  namespace: httpbin
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 80
      name: http-httpbin
      protocol: HTTP
#    tls:
#      httpsRedirect: true
    hosts:
    - "httpbin.mydomain.com"
  - port:
      number: 443
      name: https-httpbin
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    - "httpbin.mydomain.com"
```

And for PASSTROUGH

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: nginx-gateway
  namespace: nginx-passthrough
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 80
      name: http-nginx
      protocol: HTTP
    tls:
      httpsRedirect: true
    hosts:
    - nginx.mydomain.com
  - port:
      number: 443
      name: https-nginx
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
    hosts:
    - nginx.mydomain.com
```
Tried to discuss it on https://discuss.istio.io/t/tls-modes-passthrough-and-simple/852
Any advises how to address the issue would be appreciated

**Version**
Kubernetes 1.11(AWS EKS), Istio 1.0.5

**Installation**
istio:
	helm install --wait \
	--name istio \
	--namespace istio-system \
	--set global.mtls.enabled=true \
	install/kubernetes/helm/istio

**Environment**
Kubernetes 1.11(AWS EKS)

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by rshriram** [comment]
If you mark the passthrough port's protocol as TLS, it should work as intended.. HTTPS implies you are doing TLS termination of HTTP requests. TLS implies (in istio), you are either terminating TLS connection or forwarding it based on SNI.

**Comment by adenis-sv** [comment]
Tried these changes, still same error
```    port:
      name: https-nginx
      number: 443
      protocol: TLS
    tls:
      mode: PASSTHROUGH
```
and just in case tried with 'tls-" port name as well
```    port:
      name: tls-nginx
      number: 443
      protocol: TLS
    tls:
      mode: PASSTHROUGH
```

**Comment by kbruner** [comment]
I hate a similar issue, this time with both gateway ports being intended for TLS passthrough.  (Istio 1.0.5)

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: https-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: tls-mysvc
      protocol: TLS
    tls:
      mode: PASSTHROUGH
    hosts:
    - "mysvc.example.com"
  - port:
      number: 443
      name: tls-nginx
      protocol: TLS
    tls:
      mode: PASSTHROUGH
    hosts:
    - "nginx.example.com"
```

The API accepts the policy, but the `istio-ingressgateway` pod log has the following: `[2019-02-26 00:31:37.514][27][warning][config] bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:70] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener 0.0.0.0_443: error adding listener '0.0.0.0:443': multiple filter chains with the same matching rules are defined`

Same issue if I replace TLS/tls with HTTPS/https.

(This may be a different issue because of the port re-use.  If so, let me know and I'll file a separate issue.)
