### ISSUE TITLE
Sidecar resource with workloadSelector only match Services

### ISSUE THREAD

**Issue by robertpanzer** [istio/istio#11818]
**Describe the bug**
When registering a Sidecar resource to restrict what a certain Pod can see, the restrictions are not applied if the spec contains a `workloadSelector`.

**Expected behavior**
When a Sidecar resource has a `workloadSelector`, it should be used to select pods for which the restrictions should be applied.

**Steps to reproduce the bug**
Take an empty Kubernetes cluster with Istio 1.1.0-snapshot.6.
Then apply this minimal configuration of one consumer – testcurl – and 2 provider services – testserver and testserver2 – in the namespaces `consumer` and `provider`, respectively:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: consumer

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: provider

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testcurl
  namespace: consumer
  labels:
    app: testcurl
spec:
  selector:
    matchLabels:
      app: testcurl
  replicas: 1
  template:
    metadata:
      labels:
        app: testcurl
    spec:
      containers:
        - name: testcurl
          image: tutum/curl
          command:
            - sleep
            - "1000000"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testserver
  namespace: provider
spec:
  selector:
    matchLabels:
      app: testserver
  replicas: 1
  template:
    metadata:
      labels:
        app: testserver
    spec:
      containers:
        - name: testserver
          image: kennethreitz/httpbin
          ports:
            - containerPort: 80
              name: http

---
apiVersion: v1
kind: Service
metadata:
  name: testserver
  namespace: provider
  labels:
    app: testserver
spec:
  selector:
    app: testserver
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testserver2
  namespace: provider
spec:
  selector:
    matchLabels:
      app: testserver2
  replicas: 1
  template:
    metadata:
      labels:
        app: testserver2
    spec:
      containers:
        - name: testserver
          image: kennethreitz/httpbin
          ports:
            - containerPort: 80
              name: http

---
apiVersion: v1
kind: Service
metadata:
  name: testserver2
  namespace: provider
  labels:
    app: testserver2

spec:
  selector:
    app: testserver2
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
```

Open a shell in the testcurl container and test that a curl command to both providers return HTTP 200:
```
$ k exec -ti -n consumer testcurl-... -- curl -v testserver.provider:8080/get
$ k exec -ti -n consumer testcurl-... -- curl -v testserver2.provider:8080/get
```

Now create this sidecar resource:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: testcurl
  namespace: consumer
spec:
  egress:
    - hosts:
        - "provider/testserver2.provider.svc.cluster.local"
```

After that testcurl is able to only connect to testserver2:
```
# This returns HTTP 404
$ k exec -ti -n consumer testcurl-... -- curl -v testserver.provider:8080/get 
# This returns HTTP 200
$ k exec -ti -n consumer testcurl-... -- curl -v testserver2.provider:8080/get
```

Now update the same sidecar resource so that it explicitly selects the consumer workload:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: testcurl
  namespace: consumer
spec:
  workloadSelector:
    labels:
      app: testcurl
  egress:
    - hosts:
        - "provider/testserver2.provider.svc.cluster.local"
```
(I added the label `app=testcurl` to the Pod and Deployment just to make sure I didn't miss anything, I would expect though that the label on the Pod would be sufficient.)

Now try the same commands again:
```
# This should still return HTTP 404, but now it returns HTTP 200
$ k exec -ti -n consumer testcurl-... -- curl -v testserver.provider:8080/get 
# This returns HTTP 200
$ k exec -ti -n consumer testcurl-... -- curl -v testserver2.provider:8080/get
```

I expected the workloadSelector to still apply the restriction on egress traffic for the testcurl Pod, but as the result of the curl shows, it looks like traffic is not restricted anymore.

**Version**
Istio 1.1.0-snapshot.6 on Kubernetes 1.10.11 on Docker for Mac

**Installation**
```
helm install . --name istio --namespace istio-system \
  -f values-istio-auth-mcp.yaml  \
  --set global.mtls.enabled=true \
  --set global.tracing.enabled=true \
  --set pilot.traceSampling=100.0 \
  --set tracing.enabled=true \
  --set grafana.enabled=true
```

**Environment**
Local, Docker for Mac

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}
