### ISSUE TITLE
Remove no-longer-needed VirtualService from external samples

### ISSUE THREAD

**Issue by esnible** [istio/istio#11891]
The external service samples at https://github.com/istio/istio/tree/release-1.1/samples/external included VirtualServices.  At the time this was important, as it was needed and users were forgetting it.

The VirtualService is no longer needed and should be removed to avoid confusion.

VirtualService was needed before https://github.com/istio/istio/pull/11735

**Comment by mabushey** [comment]
Thanks for cleaning this mess of documentation up @esnible .

**Comment by mabushey** [comment]
Also, I know you looked at #11606 , but if that is not fixed by 1.1 you might want to add `namespace: default` to these examples. Even if that gets fixed, the possibly still exists for the ServiceEntry (I'm assuming this is similar in behavior to VirtualService) to be applied to multiple namespaces if the Active namespace changes and the file is applied again.

**Comment by mabushey** [comment]
Are you sure about Pypi? It uses port 3128.

My current pypi egress config:
```
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: pypi
spec:
  hosts:
  - "pypi.python.org"
  ports:
  - number: 3128
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: pypi
spec:
  hosts:
  - "*.python.org"
  tls:
  - match:
    - port: 3128
      sni_hosts:
      - "*.python.org"
    route:
    - destination:
        host: "*.python.org"
        port:
          number: 3128
      weight: 100
---
```
