### ISSUE TITLE
Use downward API with volume mount to monitor pod labels/annotations

### ISSUE THREAD

**Issue by rshriram** [istio/istio#11893]
The labels and annotations in a pod are currently detected statically during injection or via helm spec and encoded into  ISTIO_META_INSTANCE_LABELS/ANNOTATIONS. These metadata are currently not the authoritative source since pod labels and annotations could change dynamically. So we are forced to monitor k8s api server for label updates as well.

K8S allows mounting all the pod labels/annotations as a "file" using the downward API. I verified that this works for deployments as well. For example,

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80
        volumeMounts:
        - name: podinfo
          mountPath: /tmp/etc
          readOnly: true
      volumes:
      - name: podinfo
        downwardAPI:
          defaultMode: 444
          items:
          - fieldRef:
              fieldPath: metadata.labels
            path: pod_labels
          - fieldRef:
              fieldPath: metadata.annotations
            path: pod_annotations
```

Rather than detecting the labels at injection time, we could monitor the file path /tmp/etc/pod_labels, obtain the list of labels and add them to the metadata before starting up Envoy. The mounted files change when you add/remove labels to a pod (verified). Curiously, when you add/remove labels from a deployment, the entire deployment is restarted [which is good for us].

Bottom line is that we now have a reliable way of obtaining pod labels from the pod/proxy metadata while being able to monitor for changes. When the labels change, the proxy needs to be restarted with the new set of labels encoded in the metadata. 

It is not clear where this will be useful as we still rely on the API server to get list of all service instances with their labels, to form the subsets for destination rules.
