### ISSUE TITLE
Istio-Proxy leaks memory on ServiceEntry updates

### ISSUE THREAD

**Issue by robertpanzer** [istio/istio#11937]
**Describe the bug**
I have a minimal setup of Istio 1.1.0-snapshot.6 with a single Deployment.
When I repeatedly create and delete the same ServiceEntry the memory consumption of the Istio-proxy next to my service only goes up to > 200MB. 

**Expected behavior**
When ServiceEntries are deleted the memory that was claimed before should be freed again.

**Steps to reproduce the bug**
Install Istio 1.1.0-snapshot.6 and install the following deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testcurl
  namespace: sr-test
spec:
  selector:
    matchLabels:
      app: testcurl
  replicas: 1
  template:
    metadata:
      labels:
        app: testcurl
    spec:
      containers:
      - name: testcurl
        image: hub.docker.prod.walmart.com/library/openjdk:8-jdk
        command:
          - sleep
          - "100000"
---
apiVersion: v1
kind: Service
metadata:
  name: testcurl
  namespace: sr-test
  labels:
    app: testserver
spec:
  selector:
    app: testcurl
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
```

Now the memory consumption of the Istio-proxy shows this:
```
CMD                           RSS
/usr/local/bin/pilot-agent  16376
/usr/local/bin/envoy -c /et 31876
```

Now create a file with this ServiceEntry:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: wmt-subnets
  namespace: default
spec:
  hosts:
  - "*.example.com"
  addresses:
  - 4.100.64.0/19
  - 4.226.0.0/16
  - 4.227.0.0/16
  - 4.228.0.0/16
  - 4.229.0.0/16
  - 4.22.0.0/16
  - 4.230.0.0/16
  - 4.25.0.0/16
  - 4.26.0.0/16
  - 4.27.0.0/16
  - 4.42.0.0/16
  - 4.47.0.0/16
  - 4.15.0.0/16
  - 4.26.0.0/16
  - 4.27.0.0/16
  - 4.28.0.0/16
  - 4.29.0.0/16
  - 4.36.0.0/16
  - 4.38.0.0/16
  - 4.39.0.0/16
  - 4.40.0.0/16
  - 4.47.0.0/16
  - 4.43.0.0/16
  - 4.45.0.0/16
  - 4.54.0.0/16
  - 4.55.0.0/16
  - 4.64.0.0/18
  - 4.64.128.0/18
  - 4.64.192.0/18
  - 4.64.64.0/18
  - 4.9.0.0/16
  - 4.93.0.0/16
  - 5.74.0.0/16
  - 5.75.0.0/16
  - 6.80.0.0/16
  - 7.16.0.0/16
  - 7.21.0.0/16
  - 7.30.0.0/16
  ports:
  - number: 3306
    name: crdbms
    protocol: TCP
  - number: 7000
    name: csdr1
    protocol: TCP
  - number: 7199
    name: csdr2
    protocol: TCP
  - number: 9042
    name: csdr3
    protocol: TCP
  - number: 9160
    name: csdr4
    protocol: TCP
  - number: 9142
    name: csdr5
    protocol: TCP
  - number: 60000
    name: csdr6
    protocol: TCP
  - number: 9000
    name: kafka1
    protocol: TCP
  - number: 9091
    name: kafka2
    protocol: TCP
  - number: 9092
    name: kafka3
    protocol: TCP
  - number: 9093
    name: kafka4
    protocol: TCP
  - number: 8983
    name: solr
    protocol: TCP
  - number: 8000
    name: splunk
    protocol: HTTP
  resolution: NONE
  location: MESH_EXTERNAL
```
(I admit that this might not be the smallest ServiceEntry, but I experience the same behavior at a smaller scale with smaller, more conventional, ServiceEntries.)

Now repeatedly install and remove this ServiceEntry.
After some installs the memory consumption of the Istio-Proxy jumps by ~25MB and this is not returned anymore.
I don't send any requests, so the proxy basically has nothing to do from my perspective.

While removing and adding the ServiceEntry I see these memory consumptions:
```
CMD                           RSS
/usr/local/bin/pilot-agent  16376
/usr/local/bin/envoy -c /et 59712

CMD                           RSS
/usr/local/bin/pilot-agent  16880
/usr/local/bin/envoy -c /et 84848

CMD                           RSS
/usr/local/bin/pilot-agent  16880
/usr/local/bin/envoy -c /et 111248

CMD                           RSS
/usr/local/bin/pilot-agent  16880
/usr/local/bin/envoy -c /et 137912

CMD                           RSS
/usr/local/bin/pilot-agent  16880
/usr/local/bin/envoy -c /et 164312
```

Even after ~20 minutes the memory consumption is the same.

**Version**
Kubernetes version 1.10.11 on Docker for Mac.
Istio 1.1.0-snapshot.6

**Installation**
helm install ~/istio/istio-1.1.0-snapshot.6/install/kubernetes/helm/istio-init --name istio-init --namespace istio-system -f ~/istio/istio-1.1.0-snapshot.6/install/kubernetes/helm/istio/values-istio-auth-mcp.yaml  --set global.mtls.enabled=true --set global.tracing.enabled=true --set pilot.traceSampling=100.0 --set tracing.enabled=true --set grafana.enabled=true --set global.useMCP=false

helm install ~/istio/istio-1.1.0-snapshot.6/install/kubernetes/helm/istio --name istio --namespace istio-system -f ~/istio/istio-1.1.0-snapshot.6/install/kubernetes/helm/istio/values-istio-auth-mcp.yaml  --set global.mtls.enabled=true --set global.tracing.enabled=true --set pilot.traceSampling=100.0 --set tracing.enabled=true --set grafana.enabled=true --set global.useMCP=false

**Environment**
Running locally on Docker for Mac

**Cluster state**
The script for the cluster state fails on the docker-compose container, so I can't create whatever is expected.
However here is what I could get manually:

[clusterinfo.zip](https://github.com/istio/istio/files/2888260/clusterinfo.zip)

Also the logs of galley, pilot and the proxy:

[logs.zip](https://github.com/istio/istio/files/2888272/logs.zip)
