### ISSUE TITLE
LoadBalancer trafficPolicy returns 503 errors / Mixer Unavailable cluster

### ISSUE THREAD

**Issue by anthonyhaussman** [istio/istio#11945]
Istio version: **1.0.6**
Kubernetes server version: **v1.13.2**

Hi,
I have installed istio without mutual TLS authentication and modified the DiscoveryRefreshDelay to have by default 30s configured.

I have followed instructions to install the bookinfo application in a namespace *bookinfo* using : 
 - samples/bookinfo/platform/kube/bookinfo.yaml
 - samples/bookinfo/networking/virtual-service-all-v1.yaml
 - samples/bookinfo/networking/destination-rule-all.yaml

And modified the gateway configuration (samples/bookinfo/networking/bookinfo-gateway.yaml) to respond on the host **bookinfo.kube.test.gg**.

In this situation, Everything work like a charm.
Now I want to test the trafficPolicy loadBalancer configuration to use another simpleLB.
So I have modified the destination-rule-all.yaml file to configure a ROUND_ROBIN lb (default for test):
```
egrep -B1 -A2 "trafficPolicy:" destination-rule-all.yaml
  host: productpage
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
--
  host: reviews
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
--
  host: ratings
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
--
  host: details
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
```

Unfortunately, when I connect to the productpage via a web browser with the trafficPolicy, the page returns `Error fetching product details!` / `Error fetching product reviews!`.

The istio-proxy container of the productpage logs return a 503 error when it tries to get the details and reviews:
```
productpage-v1-54d799c966-ckckp istio-proxy [2019-02-21T15:47:12.601Z] "GET /details/0HTTP/1.1" 503 NR 0 0 0 - "-" "python-requests/2.18.4" "8828e207-d7b0-9250-8907-fa3e323352dc" "details:9080" "-" - - 10.175.98.40:9080 10.174.54.187:55442
productpage-v1-54d799c966-ckckp istio-proxy [2019-02-21T15:47:12.604Z] "GET /reviews/0HTTP/1.1" 503 NR 0 0 0 - "-" "python-requests/2.18.4" "8828e207-d7b0-9250-8907-fa3e323352dc" "reviews:9080" "-" - - 10.175.98.127:9080 10.174.54.187:52670
productpage-v1-54d799c966-ckckp istio-proxy [2019-02-21T15:47:12.606Z] "GET /reviews/0HTTP/1.1" 503 NR 0 0 0 - "-" "python-requests/2.18.4" "8828e207-d7b0-9250-8907-fa3e323352dc" "reviews:9080" "-" - - 10.175.98.127:9080 10.174.54.187:52672
productpage-v1-54d799c966-ckckp istio-proxy [2019-02-21T15:47:12.595Z] "GET /productpageHTTP/1.1" 200 - 0 3955 12 10 "192.168.51.99, 10.189.20.80" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.46 Safari/537.36" "8828e207-d7b0-9250-8907-fa3e323352dc" "bookinfo.kube.dm.gg" "127.0.0.1:9080" inbound|9080||productpage.bookinfo.svc.cluster.local - 10.174.54.187:9080 10.189.20.80:0
```

On an other namespace with some home application with liveness and readiness probe, when i try to activate a loadBalancer trafficPolicy, it returned:
```
gateway-795d45f5dc-6fkvk istio-proxy [2019-02-21T16:00:38.529Z] "GET /health/liveHTTP/1.1" 404 NR 0 0 0 - "-" "kube-probe/1.13" "dd94f9ac-0d73-9d6e-8c9e-aebc9aeef75e" "10.174.46.20:80" "-" - - 10.174.46.20:80 10.189.20.150:30132
gateway-795d45f5dc-6fkvk istio-proxy [libprotobuf ERROR src/istio/mixerclient/report_batch.cc:83] Mixer Report failed with: UNAVAILABLE:Cluster not available
```

Without any trafficPolicy configured in the DestinationRule, it works well.
Did I miss something?

If some more logs are needed don't hesitate to ask for it.

Thanks for your help.
