### ISSUE TITLE
mixs crd adapter produces different CRDs from helm

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#11955]
Auto-generated CRD by mixs crd:
```yaml
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: zipkins.config.istio.io
  labels:
    package: zipkin
    istio: mixer-adapter
spec:
  group: config.istio.io
  names:
    kind: zipkin
    plural: zipkins
    singular: zipkin
    categories:
    - istio-io
    - policy-istio-io
  scope: Namespaced
  version: v1alpha2
```

Helm version:
```yaml
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: zipkins.config.istio.io
  annotations:
    "helm.sh/hook": crd-install
  labels:
    app: mixer
    package: zipkin
    istio: mixer-adapter
spec:
  group: config.istio.io
  names:
    kind: zipkin
    plural: zipkins
    singular: zipkin
    categories:
    - istio-io
    - policy-istio-io
  scope: Namespaced
  version: v1alpha2
```
