### ISSUE TITLE
Pilot using wrong Destination Rule when there is no Sidecar resource

### ISSUE THREAD

**Issue by yangminzhu** [istio/istio#12000]
**Describe the bug**
1. Follow the tutorial here: https://preliminary.istio.io/docs/tasks/traffic-management/request-routing/

1. Refresh the page, the reviews part displays black and red stars (unexpected behavior).

**Expected behavior**
The reviews part of the page displays with no rating stars, no matter how many times you refresh.

**Steps to reproduce the bug**
Follow the tutorial here: https://preliminary.istio.io/docs/tasks/traffic-management/traffic-shifting/#apply-weight-based-routing

**Version**
Istio 1.1.0-rc.0

**Installation**
$ kubectl apply -f install/kubernetes/helm/istio-init/files/crd-*
$ kubectl apply -f install/kubernetes/istio-demo-auth.yaml

**Environment**
GKE

**Root cause**
The direct cause is the endpoints for the reviews v1 cluster is computed incorrectly that doesn't honor the subset field in virtual service. That's why the productpage is still seeing all the 3 versions of reviews but not the v1 version only.

The root cause is a little complicated and is caused by multiple reasons:
1. In 1.1, I'm under the impressions that the isolated namespace is enabled by default in Pilot even if there are no sidecar resources because a default Sidecar resource is generated in this case. However, the default Sidecar resource doesn't have the actual config (i.e. `sidecarScope.Config == nil`), this results [pushEds()](https://github.com/istio/istio/blob/aa498982104b22d999ce0c68842e84d4dc02d515/pilot/pkg/proxy/envoy/v2/eds.go#L766) calls into `loadAssignmentsForClusterLegacy()` instead of `loadAssignmentsForClusterIsolated()`.

2. When `loadAssignmentsForClusterLegacy()` is called, it gets the default destination rule:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
  name: default
  namespace: istio-system
spec:
  exportTo:
  - '*'
  host: '*.local'
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```

This default destination rule doesn't have subsets field which results the [SubsetToLabels()](https://github.com/istio/istio/blob/c4c2baddf61c3f72a0cbeb088c991c8899d8ddc2/pilot/pkg/model/push_context.go#L557) to return a nil LabelsCollection in this case.

3. Last, when [updateCluster()](https://github.com/istio/istio/blob/aa498982104b22d999ce0c68842e84d4dc02d515/pilot/pkg/proxy/envoy/v2/eds.go#L388) is trying to compute the service instances for the cluster, it gets all the service instances due to a nil LabelsCollection is considered subset to any labels.

**Workaround**
I tried to apply the following Sidecar resource and the issue is solved:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
  namespace: default
spec:
  workloadSelector:
    labels:
      app: productpage
  egress:
  - hosts:
    - "default/*"
    - "istio-system/*"
```

**Potential fix**
- To solve this when isolated namespace is enabled, we may just relax the check in https://github.com/istio/istio/blob/aa498982104b22d999ce0c68842e84d4dc02d515/pilot/pkg/proxy/envoy/v2/eds.go#L766 (don't check `sidecarScope.Config == nil`)

- To solve this when isolated namespace is disabled, it's a little bit tricky, the [DestinationRule()](https://github.com/istio/istio/blob/c4c2baddf61c3f72a0cbeb088c991c8899d8ddc2/pilot/pkg/model/push_context.go#L486) seems problematic when the proxy is nil, it says `look for dest rules across all namespaces public/private` which seems meaning a random namespace is going to be used. And in this issue, the default destination rule in the istio-system is used and caused problems.

I think we need fix this for 1.1, any thoughts? @costinm @rshriram  @ymesika  @duderino @louiscryan
