### ISSUE TITLE
Support of multiple JWT origins with same issuer in Policy for different triggers

### ISSUE THREAD

**Issue by brommer** [istio/istio#12016]
**Describe the feature request**
Assume you want to use a Policy for a composite VirtualService (e.g. on the edge bound to a Gateway) and define multiple JWT configuration, e.g. like here https://github.com/istio/istio/blob/49c978439ddde62f4d5e0cf672976294797cf2fa/tests/e2e/tests/pilot/testdata/authn/v1alpha1/authn-policy-jwt.yaml.tmpl

If the issuer is the same for two config entries, I will not be able to create the Policy. However, I might want to have two different entries for the same issuer e.g. by allowing two different audiences for two different paths defined in trigger_rules.

Thus, it would be nice, if you would support this setting.

**Describe alternatives you've considered**
Alternatives are Virtual Services per service (which is part of the composition) with own Policy. 

**Additional context*
/

**Comment by yangminzhu** [comment]
@brommer Would you mind to give an example Policy in your mind? So we can get some sense about how would like the Policy format should be. Thanks.

**Comment by brommer** [comment]
Sure:
```
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: istio-ingressgateway-service-plain
  namespace: istio-system
spec:
  targets:
  - name: istio-ingressgateway
  origins:
  - jwt:
      audiences:
      - service-plain
      issuer: http://traefik.minikube:32269/auth/realms/istio-demo
      jwksUri: http://keycloak-http.default.svc.cluster.local:80/auth/realms/istio-demo/protocol/openid-connect/certs
      trigger_rules:
      - included_paths:
        - prefix: /service-plain
  # doesn't work due to same issuer
  # - jwt:
  #     audiences:
  #     - service-admin
  #     issuer: http://traefik.minikube:32269/auth/realms/istio-demo
  #     jwksUri: http://keycloak-http.default.svc.cluster.local:80/auth/realms/istio-demo/protocol/openid-connect/certs
  #     trigger_rules:
  #     - included_paths:
  #       - prefix: /service-admin
  principalBinding: USE_ORIGIN
```

I understand, it would be possible to apply these policies also to the services itself (if I split it up to dedicated policies). However, in my local setup I was running into issues with that. The traffic from the ingress controller/Gateway seems to be not going through the envoy sidecar of the service pod itself (e.g. for service-plain) so that policies are not applied even if the envoy config of the service-plain pod seems to be correct. I tried to circumvent this issue, by using this merged policy on the ingress level itself. 

Does it help you?
