### ISSUE TITLE
Pilot needs restart to apply Virtual Service changes for internal calls

### ISSUE THREAD

**Issue by velumaniduraisamy** [istio/istio#12012]
Istio Version - 1.1.0.snapshot.1

I am trying to inject http delay for my service. Ingress calls (via Ingress Gateway) are working as expected where as internal calls (service to service) not reflecting unless  I restart Istio pilot pod.

Below is the virtual service resource
```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: paysafe-psm-asset
  namespace: psm-devint
 
spec:
  gateways:
  - paysafe-psm-asset
  - mesh
  hosts:
  - api.stress.ps.money
  - paysafe-psm-asset
  http:
  - fault:
      delay:
        fixedDelay: 5s
        percentage:
          value: 100
    match:
    - uri:
        prefix: /asset
    route:
    - destination:
        host: paysafe-psm-asset
        port:
          number: 7001
  - route:
    - destination:
        host: paysafe-psm-asset
        port:
          number: 7001
EOF
```
I have 2 services say A and B. I am calling B directly via Ingress Gateway and also from A.
First time when put delay it worked as expected, After that I changed the delay value and re applied, the changes reflected only for Ingress request whereas Service to Service still follows the older rule. If I restart pilot pod, then it is working as expected. 

When I dumped the config data (`kubectl exec -it <podname>  -c istio-proxy  -- sh -c 'curl localhost:15000/config_dump' `) of istio-proxy, Service B's side-car has latest value whereas service A's sidecar has both older and new value.   

Thanks in advance
