### ISSUE TITLE
Metrics are not written to stdio

### ISSUE THREAD

**Issue by kramerul** [istio/istio#12022]
**Describe the bug**
Logging metrics to stdio is not working with release 1.1

**Expected behavior**

Logging of metrics to stdio is possible

**Steps to reproduce the bug**

```
kubectl apply -f - <<EOF
---
# Configuration for metric instances
apiVersion: "config.istio.io/v1alpha2"
kind: metric
metadata:
  name: requestcount
  namespace: istio-system
spec:
  value: "1" # count each request twice
  dimensions:
    reporter: "test"
    source: source.workload.name | "unknown"
    destination: destination.workload.name | "unknown"
    message: '"twice the fun!"'
  monitored_resource_type: '"UNSPECIFIED"'
---
# Rule to send metric instances to a stdio handler
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: prom
  namespace: istio-system
spec:
  actions:
  - handler: handler.stdio
    instances:
    - requestcount.metric
---
# Configuration for a stdio handler
apiVersion: "config.istio.io/v1alpha2"
kind: stdio
metadata:
  name: handler
  namespace: istio-system
spec:
  logStream: FILE
  metricLevel: "ERROR"
  outputPath: "/tmp/metrics"
EOF
```
* Collect some traffic e.g using [httpbin example](https://istio.io/docs/tasks/traffic-management/ingress/)

```
kubectl -n istio-system -c mixer cp  istio-telemetry-???????:/tmp/metrics .
```

```
error: unexpected EOF
```

**Version**

istio-1.1.0-rc.0

**Installation**

```
wget https://github.com/istio/istio/releases/download/1.1.0-rc.0/istio-1.1.0-rc.0-linux.tar.gz
tar xzfv istio-1.1.0-rc.0-linux.tar.gz 
cd istio-1.1.0-rc.0/
for i in install/kubernetes/helm/istio-init/files/crd*yaml; do kubectl apply -f $i; done
kubectl apply -f install/kubernetes/istio-demo.yaml
```

**Environment**

Kubernetes on Google

**Cluster state**

Running the installation on MacOS fails with

```
curl https://raw.githubusercontent.com/istio/istio/release-1.0/tools/dump_kubernetes.sh | sh -s -- -z
...
Retrieving kubernetes resource configurations
Retrieving istio resource configurations
No resources found.
Retrieving logs for copy_core_dumps_if_istio_proxy//
error: You must provide one or more resources by argument or filename.
Example resource specifications include:
   '-f rsrc.yaml'
   '--filename=rsrc.json'
   '<resource> <name>'
   '<resource>'
error: resource name may not be empty
sh: line 108: [: : integer expression expected
Wrote ./istio-dump.tar.gz
Wrote to istio-dump
sh: line 283: return: tap_containers: numeric argument required
```

**Comment by douglas-reid** [comment]
I'm confused a bit by this report. The  `stdio` adapter only provides handling for the `logentry` template, meaning that it handles logs, not metrics.

You would need instances of `kind: logentry` and a rule that sends the information to `stdio` to see logs.

**Comment by kramerul** [comment]
In this case, it's a bug in the [documentation](https://preliminary.istio.io/docs/reference/config/policy-and-telemetry/adapters/stdio/):

The stdio adapter enables Istio to output logs and metrics to the local machine. Logs and **metrics** can be directed to Mixer’s standard output stream, standard error stream, or to any locally reachable file. When outputting to files, you can enable file rotation such that the adapter will automatically manage a set of file backups as data is generated.

**Comment by kramerul** [comment]
My first intention was to test the statsd adapter. But this was no working. Therefore, I switched to stdio to get my scenario running.

**Comment by kramerul** [comment]
Perhaps this is also related to #12059

**Comment by douglas-reid** [comment]
@kramerul my apologies. I spoke too quickly. `stdio` does indeed log metrics -- much to my surprise.

I've tested with adding `'` around the `"` in the reporter dimension (`reporter: '"test"'`) and configuring `stdio` without logging to a file. It works.

**Comment by douglas-reid** [comment]
@kramerul I believe if you want to write to a file, you'll need to edit the istio-telemetry deployment to mount a volume and proceed from there (i don't believe the scratch image exposes a `/tmp` dir).  Otherwise, simply use the following config and observe it working:

```yaml
apiVersion: "config.istio.io/v1alpha2"
kind: metric
metadata:
  name: altrequest
  namespace: istio-system
spec:
  value: "1" 
  dimensions:
    reporter: '"test"'
    source: source.workload.name | "unknown"
    destination: destination.workload.name | "unknown"
    message: '"twice the fun!"'
  monitored_resource_type: '"UNSPECIFIED"'
---
# Rule to send metric instances to a stdio handler
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: altrule
  namespace: istio-system
spec:
  actions:
  - handler: handler.stdio
    instances:
    - altrequest.metric
---
# Configuration for a stdio handler
apiVersion: "config.istio.io/v1alpha2"
kind: stdio
metadata:
  name: handler
  namespace: istio-system
spec:
  metricLevel: "ERROR"
```
