### ISSUE TITLE
install option for grafana endpoint

### ISSUE THREAD

**Issue by drishticode** [istio/istio#12039]
**Describe the feature request**
Provide install option to set grafana endpoint. For example, --set grafana.url.endpoint=/grafana

**Describe alternatives you've considered**
At the moment I am either forced to use NodePort if I want to use ingress gateway. I tried creating a Virtual service with /grafana prefix and rewrite rule but throws 404 on css and other network calls

**Additional context**
Providing endpoint configuration for grafana is useful for exposing grafana dashboard via ingress gateway

**Comment by denniseffing** [comment]
The Helm chart provides the key `grafana.contextPath` to configure the context path of Grafana. The documentation says that it defaults to `/grafana`. However, this doesn't seem to be working. 

I checked the Grafana Helm chart for the context path configuration and it turns out that the template doesn't even use the configured value.

As a workaround you can configure a virtual service and match URIs with prefix `/` and route it to the grafana service, i.e.

```yaml
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: grafana.istio-system.svc.cluster.local
            port:
              number: 3000
```
