### ISSUE TITLE
1.1.0-rc0 "Configuring multiplie TLS hosts in a gateway" does not raise error message

### ISSUE THREAD

**Issue by jsPlachetka** [istio/istio#12058]
**Describe the bug**
We tested the scenario described in [Configuring multipleTLS hosts in a gateway](https://preliminary.istio.io/help/ops/traffic-management/deploy-guidelines/#configuring-multiple-tls-hosts-in-a-gateway). The error message described in the documentation for such a scenario ("non unique port") does not appear in the pilot's log. Furthermore the scenario simply works and seems to have no issues at all.

**Expected behavior**
As described in the documentation we expected to have some error message when we use the same port name in two different gateways. If the original reason for the error message is no longer relevant the section should be removed from the operations guide. 

**Version**
istio 1.1.0-rc

**Comment by frankbu** [comment]
Are you sure the example you tried was as described in the doc. I just tried the documented example with rc0 and the log message appears exactly as documented:
```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mygateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    - "myhost.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mygateway2
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    - "myhost2.com"
EOF
```

```
kubectl logs -n istio-system -l istio=pilot -c discovery | grep "non unique port"
2019-02-26T17:08:34.364179Z	info	model	skipping server on gateway mygateway2 port https.443.HTTPS: non unique port name for HTTPS port
```
