### ISSUE TITLE
Retries not working as expected. 

### ISSUE THREAD

**Issue by velumaniduraisamy** [istio/istio#12067]
Istio Version - 1.1.0.snapshot.1

I am trying to understand retries in Istio using sample bookinfo app. When I killed review pod, I expected productpage service should retry 3 times (as default maxRetries is 3), but in istio-proxy logs I am seeing only 2 calls to review service

> [2019-02-26T16:25:22.299Z] "GET /reviews/0HTTP/1.1" 503 UH 0 19 0 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36" "74652f75-48cf-9b0d-bde7-cda94446957e" "reviews:9080" "-" - - 100.65.14.39:9080 100.124.0.49:38800 -
[2019-02-26T16:25:22.303Z] "GET /reviews/0HTTP/1.1" 503 UH 0 19 0 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36" "74652f75-48cf-9b0d-bde7-cda94446957e" "reviews:9080" "-" - - 100.65.14.39:9080 100.124.0.49:38802 -

Even after applying VirtualService with retry attempts 3, it didn't work. I am seeing only 2 calls to review service from productpage. 

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
  name: reviews
  namespace: default
spec:
  hosts:
  - reviews
  http:
  - match:
    - headers:
        end-user:
          exact: jason
    route:
    - destination:
        host: reviews
        subset: v2
  - route:
    - destination:
        host: reviews
        subset: v1
    retries:
      attempts: 3
      perTryTimeout: 1s
``` 

Help me to understand what I am missing?
