### ISSUE TITLE
Support HTTP direct responses

### ISSUE THREAD

**Issue by julianvmodesto** [istio/istio#12096]
Currently, there isn't a way to fulfill arbitrary http responses in the traffic management nor policy config APIs. Directives are available in [Envoy](https://github.com/istio/envoy/blob/master/api/envoy/api/v2/route/route.proto#L161-L162), HAProxy, and Nginx to write direct response codes with simple message bodies without routing to a backend.

Instead, users need to write, deploy, and route to a custom backend to serve arbitrary short response codes + messages (e.g. run an httpbin-like image w/ Deployment, Service, VirtualService). Or users could write and deploy a custom mixer adapter, similar to the denier mixer adapter, and write a route rule.

Fulfilling HTTP direct responses on route matches would be useful for use cases including:
* returning 200s that match requests from chained L7 cloud load balancer health checks e.g. in GCP, return 200s for requests with user-agents prefixed w/ `GoogleHC` for the GCP L7 load balancer health checks
* returning simple, useful direct responses for basic application routes like 200s or 204s

**Comment by esnible** [comment]
I agree that this would be powerful.  I have some ideas for how to use it.

Here is a hack I have played with.  I wanted to create something like a custom 404 page for a cluster with bookinfo.  So I deployed bookinfo, bookinfo-gateway, and httpbin samples (but not httpbin gateway).

Then I did this:

```
cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - "*"
  gateways:
  - bookinfo-gateway
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: 9080
  - match:
    - uri:
        prefix: /base64/
    route:
    - destination:
        host: httpbin
        port:
          number: 8000
  - match:
    - uri:
        prefix: /
    redirect:
      uri: /base64/Qm9va2luZm8gaXMgPGEgaHJlZj0nL3Byb2R1Y3RwYWdlJz5oZXJlPC9hPgo=
EOF
```

It would be so much nicer to be able to specify this directly in plaintext without httpbin or the base64 encoding.
