### ISSUE TITLE
Pilot crash under performance test resulting in abnormal behavior of Istio applications

### ISSUE THREAD

**Issue by morvencao** [istio/istio#12117]
**Describe the bug**

### Static configuration:

Pilot discovery resource requests: `2CPU 13G`
Each sidecar resource requests: `1CPU 2G`

### Dynamic configuration:

1. During the initial test period, we deployed:

    - 500 services and corresponding 500 pods inside the Istio mesh(with Istio sidecar injected) 
    - 160 services and 900 pods outside the Istio mesh 

Pilot memory usage gets a steady increase during the initial deployment process.
Finally pilot works normally after some times. 

Check the below pilot metrics from Grafana(the part before `17:08`):

![image](https://user-images.githubusercontent.com/5468682/53483341-380ab800-3abc-11e9-9801-e9f7400950b2.png)

2. During the pressure test period, we do:

    - Firstly create 50 namespaces
    - Create 20 services(2 ports for each service), corresponding 20 pods, 20 serviceaccounts into each namespace.

> Note: All applications deployed during this step are outside Istio mesh. This is reasonable in production environment, because applications size in the cluster can be very huge while the mesh is small.

Then we found that Pilot crashes due to `OM killed` and try to restart, but no good, please check the above pilot metrics from Grafana(the part after `17:08`).

**What's weird is that after pilot crashed, we found that all envoy endpoints with type `EDS` are missing from `istioctl proxy-config cluster` and the Istio application can't be accessed.**
Check the below diagram:

![image](https://user-images.githubusercontent.com/5468682/53484167-20343380-3abe-11e9-91d9-c16a37d45300.png)

Istio data plane(applications and sidecar) is supposed to be working, even the pilot is down, isn't it?

We then dump the envoy configuration from 15000 admin port of sidecar:
![image](https://user-images.githubusercontent.com/5468682/53484352-9d5fa880-3abe-11e9-85ae-d0ddd1774811.png)

As you can see, we only get endpoints of type 'ORIGINAL_DST' and `STATIC`, all others are gone.

**Expected behavior**
Even pilot crashes, all istio applications should also work without traffic drops.

**Steps to reproduce the bug**
{{ Minimal steps to reproduce the behavior }}

**Version**
istio-1.1.0-snapshot.6
```
[root@master istio-1.1.0-snapshot.6]# istioctl version
version.BuildInfo{Version:"1.1.0-snapshot.6", GitRevision:"14777199b85ba56ebca2a4516afff33c97199eb4", User:"root", Host:"f0f1db73-2fb5-11e9-86e9-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-snapshot.5-156-g1477719"}
```

**Installation**
Istio installed with `kubectl apply -f istio-demo-auth.yaml`

**Comment by morvencao** [comment]
Any thought? @louiscryan @ayj @rshriram 

/cc @gyliu513 @clyang82

**Comment by ayj** [comment]
cc @costinm

**Comment by rshriram** [comment]
With regard to endpoints disappearing:
 1. are you sure that the new pilot didn't come  up and that the envoys contacted the new pilot and received an empty set of endpoints, or haven't received any endpoints?
2. With regard to crashing from OOM, cc @mandarjog who has been doing similar perf tests but using the sidecar config instead..

IF all your applications only talk to other apps in the same namespace, then can you repeat the test with the following:
 use thie PR https://github.com/istio/istio/pull/11576
  set the meshConfig. configRootNamespace to istio-config in the helm charts. 

 apply this config:
```
apiVersion: v1
kind: Namespace
metadata:
  name: istio-config
---
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default-sidecar-scope
  namespace: istio-config
spec:
  egress:
    # If this config is applied, sidecars will only be able to talk to
    # other services in the same namespace, in addition to istio-telemetry
    # and istio-policy
  - hosts:
    - "./*"
    - "istio-system/istio-telemetry.istio-system.svc.cluster.local"
    - "istio-system/istio-policy.istio-system.svc.cluster.local"
---
````

This will confine every sidecar to talk only to its local namespace.
