### ISSUE TITLE
Non-deterministic route configuration for ingressgateway

### ISSUE THREAD

**Issue by BenPope** [istio/istio#12153]
**Describe the bug**
I have a basic ingress configuration with a `Gateway`, `VirtualService` and `DestinationRule`.

There are no sidecars, just an AWS ELB pointing at `istio-ingressgateway` configured as `NodePort` with `externalTrafficPolicy: Local`, pointing to a Service accepting TLS connections.

It works. Sometimes. However, if I remove and re-add the `VirtualService`, or if I restart `Galley`, more often than not, it will end up routing to `BlackHoleCluster`. I've been unable to determine what makes it work, it feels random.

**Expected behavior**
A given `VirtualService` configuration to result in a given routing configuration, regardless of what's restarted or when a configuration is applied.

**Steps to reproduce the bug**
Restart `Galley`, or delete and re-add the `VirtualService`.

**Version**
release-1.1-20190213-09-16
1.1.0-rc.0
release-1.1-20190227-09-16

**Installation**
helm template, kubectl apply.

**Environment**
Kubernetes 1.11.5 on recent CoreOs.

**Cluster state**
Unfortunately, I'm unable to provide a dump but should be able to answer any specific questions.

Gateway:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: service-core
  namespace: platform
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: http2
      protocol: HTTPS
    hosts:
    - "*"
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
```
VirtualService:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service-core
  namespace: platform
spec:
  hosts:
  - "*"
  gateways:
  - service-core
  http:
  - match:
    - port: 443
    - uri: 
        prefix: /
    route:
    - destination:
        port:
          number: 10443
          name: https
        host: service-core.platform.svc.cluster.local
```
and DestinationRule:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: service-core
  namespace: platform
spec:
  host: service-core.platform.svc.cluster.local
  trafficPolicy:
    tls:
      mode: SIMPLE
    connectionPool:
      http:
        http2MaxRequests: 2147483646
        maxRequestsPerConnection: 2147483646
      tcp:
        maxConnections: 100
        connectTimeout: 200ms
    loadBalancer:
      simple: LEAST_CONN
```
Service:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: service-core
  namespace: platform
spec:
  selector:
    app: service
    component: core
  ports:
    - name: https
      port: 10443
```
Routes when not working:
```json
istio-ingressgateway-74df7575bc-vch2p.istio-system -o json
[
    {
        "name": "https.443.http2",
        "virtualHosts": [
            {
                "name": "*:443",
                "domains": [
                    "*",
                    "*:443"
                ],
                "routes": [
                    {
                        "match": {
                            "prefix": "/"
                        },
                        "route": {
                            "cluster": "BlackHoleCluster",
                            "timeout": "0s",
                            "retryPolicy": {
                                "retryOn": "connect-failure,refused-stream,unavailable,cancelled,resource-exhausted",
                                "numRetries": 10,
                                "retryHostPredicate": [
                                    {
                                        "name": "envoy.retry_host_predicates.previous_hosts"
                                    }
                                ],
                                "hostSelectionRetryMaxAttempts": "3",
                                "retriableStatusCodes": [
                                    503
                                ]
                            },
                            "maxGrpcTimeout": "0s"
                        },
                        "metadata": {
                            "filterMetadata": {
                                "istio": {
                                    "config": "/apis/networking/v1alpha3/namespaces/platform/virtual-service/service-core"
                                }
                            }
                        },
                        "decorator": {
                            "operation": "service-core:443/*"
                        },
                        "typedPerFilterConfig": {
                            "mixer": {
                                "@type": "type.googleapis.com/istio.mixer.v1.config.client.ServiceConfig",
                                "disableCheckCalls": true,
                                "mixerAttributes": {},
                                "forwardAttributes": {}
                            }
                        }
                    }
                ]
            }
        ],
        "validateClusters": false
    }
]
```
Routes when working:
```json
istio-ingressgateway-74df7575bc-vch2p.istio-system -o json
[
    {
        "name": "https.443.http2",
        "virtualHosts": [
            {
                "name": "*:443",
                "domains": [
                    "*",
                    "*:443"
                ],
                "routes": [
                    {
                        "match": {
                            "prefix": "/"
                        },
                        "route": {
                            "cluster": "outbound|10443||service-core.platform.svc.cluster.local",
                            "timeout": "0s",
                            "retryPolicy": {
                                "retryOn": "connect-failure,refused-stream,unavailable,cancelled,resource-exhausted",
                                "numRetries": 10,
                                "retryHostPredicate": [
                                    {
                                        "name": "envoy.retry_host_predicates.previous_hosts"
                                    }
                                ],
                                "hostSelectionRetryMaxAttempts": "3",
                                "retriableStatusCodes": [
                                    503
                                ]
                            },
                            "maxGrpcTimeout": "0s"
                        },
                        "metadata": {
                            "filterMetadata": {
                                "istio": {
                                    "config": "/apis/networking/v1alpha3/namespaces/platform/virtual-service/service-core"
                                }
                            }
                        },
                        "decorator": {
                            "operation": "service-core.platform.svc.cluster.local:10443/*"
                        },
                        "typedPerFilterConfig": {
                            "mixer": {
                                "@type": "type.googleapis.com/istio.mixer.v1.config.client.ServiceConfig",
                                "disableCheckCalls": true,
                                "mixerAttributes": {
                                    "attributes": {
                                        "destination.service.host": {
                                            "stringValue": "service-core.platform.svc.cluster.local"
                                        },
                                        "destination.service.name": {
                                            "stringValue": "service-core"
                                        },
                                        "destination.service.namespace": {
                                            "stringValue": "platform"
                                        },
                                        "destination.service.uid": {
                                            "stringValue": "istio://platform/services/service-core"
                                        }
                                    }
                                },
                                "forwardAttributes": {
                                    "attributes": {
                                        "destination.service.host": {
                                            "stringValue": "service-core.platform.svc.cluster.local"
                                        },
                                        "destination.service.name": {
                                            "stringValue": "service-core"
                                        },
                                        "destination.service.namespace": {
                                            "stringValue": "platform"
                                        },
                                        "destination.service.uid": {
                                            "stringValue": "istio://platform/services/service-core"
                                        }
                                    }
                                }
                            }
                        }
                    }
                ]
            }
        ],
        "validateClusters": false
    }
]
```
