### ISSUE TITLE
TCP Ingress doesn't work when used with mTLS and weighted routes in VirtualService

### ISSUE THREAD

**Issue by uk000** [istio/istio#12170]
**Describe the bug**
Given:
1. a service that defines subsets using a DestinationRule
2. ingress gateway is configured via a VirtualService to perform weighted routing among the two subsets
3. mTLS is enabled in the cluster
The above setup doesn't work when mTLS is enabled in the cluster
The same setup works once mTLS is disabled. Alternately, the setup works with mTLS enabled if the VirtualService is changed to not perform weighted routing.
I've confirmed the above issue with TCP protocol. I haven't confirmed at present whether the issue also exists with HTTP protocol.

**Expected behavior**
Ingress gateway should route traffic based on weighted configuration defined in a VirtualService with mTLS enabled for TCP protocol.

**Steps to reproduce the bug**
1. Enable mTLS in the cluster
2. Create a namespace with a TCP service deployed in it.
3. Create a DestinationRule to configure subsets and client mTLS 

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: tcp-dr
  namespace: ns
spec:
  host: tcp-service.ns.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  trafficPolicy:
    tls:
      mode: "ISTIO_MUTUAL"
```

4. Create a gateway configuration:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tcp-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 9000
      name: tcp-9000
      protocol: TCP
    hosts:
    - "*"
```

5. Create a VirtualService

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tcp-vs
  namespace: ns
spec:
  hosts:
  - "*"
  gateways:
  - tcp-gateway
  tcp:
  - match:
    - port: 9000
    route:
    - destination:
        host: tcp-service.ns.svc.cluster.local
        port:
          number: 9000
        subset: v1
      weight: 80
    - destination:
        host: tcp-service.ns.svc.cluster.local
        port:
          number: 9000
        subset: v2
      weight: 20
```

6. With the above config, the ingress gateway doesn't route the TCP traffic.

7. Now replace the VirtualService with this one

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tcp-vs
  namespace: ns
spec:
  hosts:
  - "*"
  gateways:
  - tcp-gateway
  tcp:
  - match:
    - port: 9000
    route:
    - destination:
        host: tcp-service.ns.svc.cluster.local
        port:
          number: 9000
```

8. With the above setup, TCP ingress starts working.

9. Alternately, disable mTLS in Step 7 instead of changing the VirtualService, and ingress starts working too.

**Version**
Istio version: 1.1.0-rc.1
Kubernetes version: 1.13.0

**Installation**
Using "helm template" to generate istio-init.yaml and istio.yaml files, and applied them to kubernetes.

**Environment**
Tested on docker-for-mac on MacOS

**Cluster state**
As reported in issue #12156 , the bug in tools/dump_kubernetes.sh prevents creation of state dump

**Comment by rshriram** [comment]
I assume you have modified the gateway k8s service to open up port 9000?

**Comment by uk000** [comment]
@rshriram yes indeed

**Comment by costinm** [comment]
I'll try to repro, thanks for the details.

**Comment by hzxuzhonghu** [comment]
I found the root cause, @rshriram I think this is related to the destinationrule match policy fix.  

And the gateway proxy selected destinationrule  `default` in namespace `istio-system` 

```
root@bz-ubuntu:~# kubectl get destinationrule -n istio-system default -oyaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1alpha3","kind":"DestinationRule","metadata":{"annotations":{},"labels":{"app":"security","chart":"security","heritage":"Tiller","release":"istio"},"name":"default","namespace":"istio-system"},"spec":{"exportTo":["*"],"host":"*.local","trafficPolicy":{"tls":{"mode":"ISTIO_MUTUAL"}}}}
  creationTimestamp: "2019-02-26T02:48:30Z"
  generation: 1
  labels:
    app: security
    chart: security
    heritage: Tiller
    release: istio
  name: default
  namespace: istio-system
  resourceVersion: "3369881"
  selfLink: /apis/networking.istio.io/v1alpha3/namespaces/istio-system/destinationrules/default
  uid: 00403257-3971-11e9-b464-fa163ed0737f
spec:
  exportTo:
  - '*'
  host: '*.local'
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

```

**Comment by hzxuzhonghu** [comment]
host: '*.local'   so it is matched.

**Comment by hzxuzhonghu** [comment]
```
// search through the DestinationRules in proxy's namespace first
	if ps.namespaceLocalDestRules[proxy.ConfigNamespace] != nil {
		if host, ok := MostSpecificHostMatch(service.Hostname,
			ps.namespaceLocalDestRules[proxy.ConfigNamespace].hosts); ok {
			return ps.namespaceLocalDestRules[proxy.ConfigNamespace].destRule[host].config
		}
	}

	// if no private/public rule matched in the calling proxy's namespace,
	// check the target service's namespace for public rules
	if service.Attributes.Namespace != "" && ps.namespaceExportedDestRules[service.Attributes.Namespace] != nil {
		if host, ok := MostSpecificHostMatch(service.Hostname,
			ps.namespaceExportedDestRules[service.Attributes.Namespace].hosts); ok {
			return ps.namespaceExportedDestRules[service.Attributes.Namespace].destRule[host].config
		}
	}

	// if no public/private rule in calling proxy's namespace matched, and no public rule in the
	// target service's namespace matched, search for any public destination rule across all namespaces
	if host, ok := MostSpecificHostMatch(service.Hostname, ps.allExportedDestRules.hosts); ok {
		return ps.allExportedDestRules.destRule[host].config
	}
```

Destinationrule in istio-system namespace is matched in first order. So destinationrule created for the tcp service is not used.

**Comment by rshriram** [comment]
I just noticed @uk000 that your virtual service is incorrect. You are specifying the gateway without a namesapce
```
hosts:
  - "*"
  gateways:
  - tcp-gateway
```

this will default to the namespace of the VS but your gateway is in a different namespace (istio-system)

**Comment by uk000** [comment]
@rshriram I guess I wrote up those sample virtualservice yaml in the bug description in a hurry, but indeed I see the issue when using the full fqdn for gateway. 
Ingress starts routing as soon as one of the two changes are made: either disable mTLS in the cluster, or change VirtualsService to not use weighted routing. 
Interestingly, the ingress routing doesn't work if you just switch to PERMISSIVE mTLS mode for the service, but disabling mTLS altogether makes it start working.

**Comment by costinm** [comment]
Ok, I tried it first on my 'separate gateway' and it seems it works there.
```
Listener:
 {
                        "name": "envoy.tcp_proxy",
                        "typedConfig": {
                            "@type": "type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy",
                            "statPrefix": "tcp-vs.iperf3s",
                            "weightedClusters": {
                                "clusters": [
                                    {
                                        "name": "outbound|5201|v1|iperf3.iperf3s.svc.cluster.local",
                                        "weight": 50
                                    },
                                    {
                                        "name": "outbound|5201|v2|iperf3.iperf3s.svc.cluster.local",
                                        "weight": 50
                                    }
                                ]
                            },

... 

clusters:
   {
        "name": "outbound|5201|v1|iperf3.iperf3s.svc.cluster.local",
        "type": "EDS",
        "edsClusterConfig": {
            "edsConfig": {
                "ads": {}
            },
            "serviceName": "outbound|5201|v1|iperf3.iperf3s.svc.cluster.local"
        },
        "connectTimeout": "1s",
        "circuitBreakers": {
            "thresholds": [
                {
                    "maxRetries": 1024
                }
            ]
        },
        "tlsContext": {
            "commonTlsContext": {
                "tlsCertificates": [
                    {
                        "certificateChain": {
                            "filename": "/etc/certs/cert-chain.pem"
...

Logs: 
[2019-03-04T22:40:53.574Z] "- - -" 0 - "-" 611125785 0 10072 - "-" "-" "-" "-" "10.52.6.188:5201" outbound|5201|v1|iperf3.iperf3s.svc.cluster.local 10.52.7.241:55248 10.52.7.241:5201 10.52.7.1:38870 -

[2019-03-04T22:37:35.331Z] "- - -" 0 - "-" 614327379 0 10503 - "-" "-" "-" "-" "10.52.7.243:5201" outbound|5201|v2|iperf3.iperf3s.svc.cluster.local 10.52.7.241:47246 10.52.7.241:5201 10.128.15.233:55065 -

```

I'll try next with gateway in istio-system ( the test was with gateway in istio-gateway )

**Comment by costinm** [comment]
And the config I tried:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iperf3-srv
  labels:
    release: iperf3s
  namespace: iperf3s
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: iperf3
        version: v2
    spec:
      containers:
        - image: docker.io/networkstatic/iperf3
          imagePullPolicy: IfNotPresent
          name: iperf3
          ports:
            - containerPort: 5201
          args:
            - '-s'
            - '-p'
            - '5201'
          resources:
            requests:
              cpu: 1000m
              memory: "1G"
            limits:
              cpu: 1000m
              memory: "2G"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iperf3-srv-a
  labels:
    release: iperf3s
  namespace: iperf3s
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: iperf3
        version: v1
    spec:
      containers:
        - image: docker.io/networkstatic/iperf3
          imagePullPolicy: IfNotPresent
          name: iperf3
          ports:
            - containerPort: 5201
          args:
            - '-s'
            - '-p'
            - '5201'
          resources:
            requests:
              cpu: 1000m
              memory: "1G"
            limits:
              cpu: 1000m
              memory: "2G"
---
apiVersion: v1
kind: Service
metadata:
  name: iperf3
  labels:
    release: iperf3s
  namespace: iperf3s
spec:
  ports:
    - name: tcp
      port: 5201
      targetPort: 5201
  selector:
    app: iperf3
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: tcp-dr
  namespace: iperf3s
spec:
  host: iperf3.iperf3s.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  trafficPolicy:
    tls:
      mode: "ISTIO_MUTUAL"
---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tcp-gateway
  namespace: istio-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 5201
      name: tcp-5201
      protocol: TCP
    hosts:
    - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tcp-vs
  namespace: iperf3s
spec:
  hosts:
  - "*"
  gateways:
  - istio-gateway/tcp-gateway
  tcp:
  - match:
    - port: 5201
    route:
    - destination:
        host: iperf3.iperf3s.svc.cluster.local
        port:
          number: 5201
        subset: v1
      weight: 50
    - destination:
        host: iperf3.iperf3s.svc.cluster.local
        port:
          number: 5201
        subset: v2
      weight: 50


```

**Comment by costinm** [comment]
And I can repro in istio-system - seems to be the same problem with DestionationRules that should be fixed by Shriram change. 

I would strongly recommend installing the gateway out of istio-system, it is already supported with the old installer (even in 1.0), plan for 1.2 is to move everything except certs out of istio-system.

**Comment by costinm** [comment]
@rshriram 
@howardjohn 

Well - it doesn't seem the DR fix solves problem. I did a build with the last PR, same behavior.

Deleting the 'default' destinationrule from istio-system is fixing the problem, both v1/v2 show up.
Adding an explicit destinationrule in istio-system is also fixing the problem.

We do have 2 workarounds - moving the gateway to different namespace is best,  adding the destination-rule in istio-system is the second, so not blocking for 1.1 but we should fix for 1.1.1.

**Comment by duderino** [comment]
@costinm @howardjohn @rshriram what is the final state for this bug for 1.1?  wont fix + release note?

**Comment by rshriram** [comment]
It works properly. I verified. we can close this issue..

CDS output in gateway
```
{
     "version_info": "2019-03-05T20:13:26Z/7",
     "cluster": {
      "name": "outbound|3306||mysql-server.default.svc.cluster.local",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       },
       "service_name": "outbound|3306||mysql-server.default.svc.cluster.local"
      },
      "connect_timeout": "1s",
      "circuit_breakers": {
       "thresholds": [
        {
         "max_retries": 1024
        }
       ]
      },
      "tls_context": {
       "common_tls_context": {
        "tls_certificates": [
         {
          "certificate_chain": {
           "filename": "/etc/certs/cert-chain.pem"
          },
          "private_key": {
           "filename": "/etc/certs/key.pem"
          }
         }
        ],
        "validation_context": {
         "trusted_ca": {
          "filename": "/etc/certs/root-cert.pem"
         },
         "verify_subject_alt_name": [
          "spiffe://cluster.local/ns/default/sa/default"
         ]
        },
        "alpn_protocols": [
         "istio"
        ]
       },
       "sni": "outbound_.3306_._.mysql-server.default.svc.cluster.local"
      },
      "metadata": {
       "filter_metadata": {
        "istio": {
         "config": "/apis/networking/v1alpha3/namespaces/default/destination-rule/tcp-dr"
        }
       }
      }
     },
     "last_updated": "2019-03-05T20:13:26.247Z"
    },
```

LDS output:
```{
     "version_info": "2019-03-05T20:13:26Z/7",
     "listener": {
      "name": "0.0.0.0_31400",
      "address": {
       "socket_address": {
        "address": "0.0.0.0",
        "port_value": 31400
       }
      },
      "filter_chains": [
       {
        "filters": [
         {
          "name": "envoy.tcp_proxy",
          "typed_config": {
           "@type": "type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy",
           "stat_prefix": "tcp-vs.default",
           "weighted_clusters": {
            "clusters": [
             {
              "name": "outbound|3306|v1|mysql-server.default.svc.cluster.local",
              "weight": 80
             },
             {
              "name": "outbound|3306|v2|mysql-server.default.svc.cluster.local",
              "weight": 20
             }
            ]
           }
          }
         }
        ]
       }
      ]
     },
     "last_updated": "2019-03-05T20:13:26.253Z"
    }
```

for the following config (similar to @uk000 's config)

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: tcp-dr
  namespace: default
spec:
  host: mysql-server.default.svc.cluster.local
  subsets:
  - name: v1
  - name: v2
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tcp-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 31400
      name: tcp
      protocol: TCP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tcp-vs
  namespace: default
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/tcp-gateway
  tcp:
  - match:
    - port: 31400
    route:
    - destination:
        host: mysql-server.default.svc.cluster.local
        port:
          number: 3306
        subset: v1
      weight: 80
    - destination:
        host: mysql-server.default.svc.cluster.local
        port:
          number: 3306
        subset: v2
      weight: 20
---
```
