### ISSUE TITLE
Consistent hashing based on httpHeader works through ingress-gateway but not through service

### ISSUE THREAD

**Issue by nizamsp** [istio/istio#12178]
**Describe the bug**
Configurations like rewrite rules, timeout, consistent hashing doesn't work on service-to-service api calls. But it works when we go via the istio ingress gateway

**Steps to reproduce the bug**

We took the helloworld.yml from the samples folder of 1.0.6 version and just added the following rewrite rule and ran few curl commands to test this.

**Newly added rewrite rule part of yaml**
```
 - match:
    - uri:
        exact: /dummy
    rewrite:
        uri: /hello
    route:
    - destination:
        host: helloworld
        port:
          number: 5000
```

**Full yaml is below:**
```
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: helloworld
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
        version: v1
    spec:
      containers:
      - name: helloworld
        image: istio/examples-helloworld-v1
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
        version: v2
    spec:
      containers:
      - name: helloworld
        image: istio/examples-helloworld-v2
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: helloworld-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helloworld
spec:
  hosts:
  - "*"
  gateways:
  - helloworld-gateway
  http:
  - match:
    - uri:
        exact: /hello
    route:
    - destination:
        host: helloworld
        port:
          number: 5000
  - match:
    - uri:
        exact: /dummy
    rewrite:
        uri: /hello
    route:
    - destination:
        host: helloworld
        port:
          number: 5000

```

**Behaviour outside the cluster:**
```
curl -o - "http://$GATEWAY_URL/dummy"
200 OK - works fine
curl -o - "http://$GATEWAY_URL/hello"
200 OK - works fine
```

**Behaviour inside a pod:**
```
curl -I -o - "http://helloworld.default.svc.cluster.local:5000/dummy"
404 not found - doesn't work
curl -I -o - "http://helloworld.default.svc.cluster.local:5000/hello"
200 OK - works fine
```

**Version**
Istio version: 1.0.6

**Installation**
Installed with mTLS enabled by using demo-auth.yml

**Environment**
GCP

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by esnible** [comment]
Because you have specified

```
  gateways:
  - helloworld-gateway
```

Your VirtualService will only apply to things going through _helloworld-gateway_.

If you leave off the gateway, Istio validation will complain "wildcard host * is not allowed for virtual services bound to the mesh gateway".

What you want is 

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helloworld-in-cluster
spec:
  hosts:
  - helloworld.default.svc.cluster.local
  http:
  - match:
    - uri:
        exact: /hello
    route:
    - destination:
        host: helloworld
        port:
          number: 5000
  - match:
    - uri:
        exact: /dummy
    rewrite:
        uri: /hello
    route:
    - destination:
        host: helloworld
        port:
          number: 5000
```

**Comment by rsbala** [comment]
Thanks esnible for the quick response, the above configuration works !! Now we are facing the similar issue with Destination rule based on Consistent hash. Consistent hashing based on httpHeader works through ingress-gateway but not working through service.

**Newly added consistent hash destination rule:**
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: helloworld-consistent-hash
spec:
  host: helloworld.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: user
```

**Full yaml:**
```
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: helloworld
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
        version: v1
    spec:
      containers:
      - name: helloworld
        image: istio/examples-helloworld-v1
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
        version: v2
    spec:
      containers:
      - name: helloworld
        image: istio/examples-helloworld-v2
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: helloworld-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helloworld
spec:
  hosts:
  - "*"
  gateways:
  - helloworld-gateway
  http:
  - match:
    - uri:
        exact: /hello
    route:
    - destination:
        host: helloworld
        port:
          number: 5000
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: helloworld-consistent-hash
spec:
  host: helloworld.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: user
```

**Behavior through ingress-gateway, outside the cluster:**
```
for i in {1..5}; do curl -H "user: abc" "http://$GATEWAY_URL/hello"; done
Hello version: **v1**, instance: helloworld-v1-c64bc46f5-6jns5
Hello version: **v1**, instance: helloworld-v1-c64bc46f5-6jns5
Hello version: **v1**, instance: helloworld-v1-c64bc46f5-6jns5
Hello version: **v1**, instance: helloworld-v1-c64bc46f5-6jns5
Hello version: **v1**, instance: helloworld-v1-c64bc46f5-6jns5
```

All requests with http header "user: abc" goes to v1 version, consistent hash works.

**Behavior through service, inside the pod:**

```
for i in {1..5}; do curl -H "user: abc" "http://helloworld.default.svc.cluster.local:5000/hello"; done
Hello version: **v2**, instance: helloworld-v2-6489d9fb5-5zs4g
Hello version: **v1**, instance: helloworld-v1-c64bc46f5-6jns5
Hello version: **v2**, instance: helloworld-v2-6489d9fb5-5zs4g
Hello version: **v1**, instance: helloworld-v1-c64bc46f5-6jns5
Hello version: **v1**, instance: helloworld-v1-c64bc46f5-6jns5
```

Requests go to both v1 and v2, consistent hash is not working.
