### ISSUE TITLE
Bookinfo example status 000

### ISSUE THREAD

**Issue by abhyuditjain** [istio/istio#12176]
**Describe the bug**
I have a Cluster with CoreDNS and Calico. I installed istio following the quickstart guide (without mutual TLS, `kubectl apply -f istio-demo.yml`) and then followed bookinfo installation.

When I verify the installation using curl, I get `000`.

The following is the cluster config:
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-02-06T05:04:34Z
  name: cluster.k8s.local
spec:
  api:
    loadBalancer:
      sslCertificate: arn:aws:acm:ap-south-1:ACCOUNT:certificate/CERTIFICATE
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://cluster-state-store/cluster.k8s.local
  etcdClusters:
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-ap-south-1b
      name: b
    name: main
    enableEtcdTLS: true
    version: 3.2.26
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-ap-south-1b
      name: b
    name: events
    enableEtcdTLS: true
    version: 3.2.26
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.11.7
  kubeAPIServer:
    admissionControl:
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - PersistentVolumeLabel
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - ResourceQuota
    - NodeRestriction
    - Priority
  masterPublicName: api.cluster.k8s.local
  networkCIDR: 172.20.0.0/16
  kubeDNS:
    provider: CoreDNS
  networking:
    calico:
      majorVersion: v3
      crossSubnet: true
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: ap-south-1a
    type: Private
    zone: ap-south-1a
  - cidr: 172.20.64.0/19
    name: ap-south-1b
    type: Private
    zone: ap-south-1b
  - cidr: 172.20.0.0/22
    name: utility-ap-south-1a
    type: Utility
    zone: ap-south-1a
  - cidr: 172.20.4.0/22
    name: utility-ap-south-1b
    type: Utility
    zone: ap-south-1b
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-02-06T05:04:34Z
  labels:
    kops.k8s.io/cluster: cluster.k8s.local
  name: master-ap-south-1b
spec:
  additionalUserData:
  - name: etcResolv.sh
    type: text/x-shellscript
    content: |
      #!/bin/sh
      systemctl stop systemd-resolved
      systemctl disable systemd-resolved
      rm -f /etc/resolv.conf
      cat /run/systemd/resolve/resolv.conf > /etc/resolv.conf
  image: ami-092e1fd695ed0e93c
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-south-1b
  role: Master
  rootVolumeSize: 30
  subnets:
  - ap-south-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-02-06T05:04:34Z
  labels:
    kops.k8s.io/cluster: cluster.k8s.local
  name: nodes
spec:
  additionalUserData:
  - name: etcResolv.sh
    type: text/x-shellscript
    content: |
      #!/bin/sh
      systemctl stop systemd-resolved
      systemctl disable systemd-resolved
      rm -f /etc/resolv.conf
      cat /run/systemd/resolve/resolv.conf > /etc/resolv.conf
  image: ami-092e1fd695ed0e93c
  machineType: t3.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 30
  subnets:
  - ap-south-1a
  - ap-south-1b
```

The following are the pods:
```
➜ kubectl get po -n kube-system
NAME                                                                   READY   STATUS      RESTARTS   AGE
calico-complete-upgrade-v331-928mj                                     0/1     Completed   0          39m
calico-kube-controllers-6f875f599b-lhqhk                               1/1     Running     0          39m
calico-node-8748c                                                      2/2     Running     0          38m
calico-node-rcr8m                                                      2/2     Running     0          39m
calico-node-wpfq6                                                      2/2     Running     0          38m
coredns-784bfc9fbd-lstkr                                               1/1     Running     0          39m
coredns-784bfc9fbd-wnhqc                                               1/1     Running     0          39m
dns-controller-547884bc7f-lpjqq                                        1/1     Running     0          39m
etcd-server-events-ip-172-20-66-125.ap-south-1.compute.internal        1/1     Running     0          39m
etcd-server-ip-172-20-66-125.ap-south-1.compute.internal               1/1     Running     0          39m
k8s-ec2-srcdst-85c59d5857-9tt2d                                        1/1     Running     0          39m
kube-apiserver-ip-172-20-66-125.ap-south-1.compute.internal            1/1     Running     0          38m
kube-controller-manager-ip-172-20-66-125.ap-south-1.compute.internal   1/1     Running     0          39m
kube-proxy-ip-172-20-38-243.ap-south-1.compute.internal                1/1     Running     0          38m
kube-proxy-ip-172-20-64-54.ap-south-1.compute.internal                 1/1     Running     0          38m
kube-proxy-ip-172-20-66-125.ap-south-1.compute.internal                1/1     Running     0          39m
kube-scheduler-ip-172-20-66-125.ap-south-1.compute.internal            1/1     Running     0          39m
```

```
➜ kubectl get po -n istio-system
NAME                                      READY   STATUS      RESTARTS   AGE
grafana-7f6cd4bf56-hvmpb                  1/1     Running     0          20m
istio-citadel-796c94878b-lfgw9            1/1     Running     0          20m
istio-cleanup-secrets-b5tnd               0/1     Completed   0          20m
istio-egressgateway-864444d6ff-l5vcs      1/1     Running     0          20m
istio-galley-6c68c5dbcf-4df5n             1/1     Running     0          20m
istio-grafana-post-install-mk8qm          0/1     Completed   3          20m
istio-ingressgateway-694576c7bb-c6bv7     1/1     Running     0          20m
istio-pilot-6c87bfbf-wn2xh                2/2     Running     0          20m
istio-policy-5bd5578b94-8xgkl             2/2     Running     0          20m
istio-security-post-install-r4sdx         0/1     Completed   2          20m
istio-sidecar-injector-6d8f88c98f-9tndq   1/1     Running     0          20m
istio-telemetry-5598f86cd8-fkgl7          2/2     Running     0          20m
istio-tracing-7596597bd7-ch4t8            1/1     Running     0          20m
prometheus-76db5fddd5-tm9hm               1/1     Running     0          20m
servicegraph-df4d5f678-r9k68              1/1     Running     0          20m
```

```
➜ kubectl get po
NAME                             READY   STATUS    RESTARTS   AGE
details-v1-6764bbc7f7-lsvw8      2/2     Running   0          17m
productpage-v1-54b8b9f55-xpjf8   2/2     Running   0          17m
ratings-v1-7bc85949-9sttr        2/2     Running   0          17m
reviews-v1-fdbf674bb-dltzm       2/2     Running   0          17m
reviews-v2-5bdc5877d6-7766v      2/2     Running   0          17m
reviews-v3-dd846cc78-9rc7h       2/2     Running   0          17m
```

```
➜ kubectl get svc -n istio-system
NAME                     TYPE           CLUSTER-IP       EXTERNAL-IP                                                                PORT(S)                                                                                                                   AGE
grafana                  ClusterIP      100.70.38.3      <none>                                                                     3000/TCP                                                                                                                  21m
istio-citadel            ClusterIP      100.66.18.224    <none>                                                                     8060/TCP,9093/TCP                                                                                                         21m
istio-egressgateway      ClusterIP      100.64.136.162   <none>                                                                     80/TCP,443/TCP                                                                                                            21m
istio-galley             ClusterIP      100.67.234.38    <none>                                                                     443/TCP,9093/TCP                                                                                                          21m
istio-ingressgateway     LoadBalancer   100.64.6.139     <PUBLIC CNAME>   80:31380/TCP,443:31390/TCP,31400:31400/TCP,15011:32633/TCP,8060:32379/TCP,853:32196/TCP,15030:31468/TCP,15031:31272/TCP   21m
istio-pilot              ClusterIP      100.71.132.32    <none>                                                                     15010/TCP,15011/TCP,8080/TCP,9093/TCP                                                                                     21m
istio-policy             ClusterIP      100.67.78.77     <none>                                                                     9091/TCP,15004/TCP,9093/TCP                                                                                               21m
istio-sidecar-injector   ClusterIP      100.70.206.4     <none>                                                                     443/TCP                                                                                                                   21m
istio-telemetry          ClusterIP      100.67.9.227     <none>                                                                     9091/TCP,15004/TCP,9093/TCP,42422/TCP                                                                                     21m
jaeger-agent             ClusterIP      None             <none>                                                                     5775/UDP,6831/UDP,6832/UDP                                                                                                21m
jaeger-collector         ClusterIP      100.71.96.103    <none>                                                                     14267/TCP,14268/TCP                                                                                                       21m
jaeger-query             ClusterIP      100.69.245.27    <none>                                                                     16686/TCP                                                                                                                 21m
prometheus               ClusterIP      100.67.137.55    <none>                                                                     9090/TCP                                                                                                                  21m
servicegraph             ClusterIP      100.66.208.128   <none>                                                                     8088/TCP                                                                                                                  21m
tracing                  ClusterIP      100.69.210.187   <none>                                                                     80/TCP                                                                                                                    21m
zipkin                   ClusterIP      100.67.112.217   <none>                                                                     9411/TCP                                                                                                                  21m
```

**Expected behavior**
200

**Steps to reproduce the bug**
Follow the quickstart

**Version**
Istio: 1.0.6
K8S: 1.11.7
Calico: v3
Etcd: 3.2.26

**Installation**
```
kubectl apply -f install/kubernetes/istio-demo.yaml
kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml
kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml
kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml
```

**Environment**
Cloud: AWS
OS: Ubuntu 18.04.1 LTS
