### ISSUE TITLE
Istio proxy sidecar interferes with Kubernetes API calls for the first seconds.

### ISSUE THREAD

**Issue by vcanaa** [istio/istio#12187]
**Describe the bug**
I am facing the same problem as this #8696.

The command `kubectl get all` fails, when run by a container that has istio-proxy sidecar in the same pod. I got the message from the logs:
```
The connection to the server 10.3.240.1:443 was refused - did you specify the right host or port?
```
However, running the same command after getting a terminal to the container works:
```
$ kubectl exec -it test2 -c=tester -- /bin/bash
root@test2:/# kubectl get all
NAME                                 READY   STATUS             RESTARTS   AGE
pod/details-v1-795bb75447-7rxnt      2/2     Running            0          3d
...
```

Why would istio-proxy block kubectl API in a normal context and let it through when we run a command using exec?

**Expected behavior**
It should either block or allow in both contexts, instead of blocking in one of them and allowing in the other.

**Version**
```
$ istioctl version
Version: 1.0.6
```
`istioctl proxy-status` shows proxy version 1.0.2 in the clusters.

```
root@test2:/# kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2"
```
Cluster runs k8s version **1.11.7**

**Installation**
It was installed automatically by GCP. The auto injection is enabled in the default namespace.

**Environment**
GCP

**UPDATE**

I found out what is happening. Istio is not blocking the call, it is instead not prepared to proxy it just yet.
Here is a manifest that makes it easy to reproduce.

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8sapitest  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8sapitest
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: k8sapitest
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: test1
spec:
  serviceAccountName: k8sapitest
  containers:
  - name: tester
    image: "cosmintitei/bash-curl"
    imagePullPolicy: Always
    # Calling k8s api right away fails:
    #   Failed to connect to 10.3.240.1 port 443: Connection refused
    command: ['bash', '-c', 'curl -v --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT || sleep 300']
    # But if we wait 5 seconds it works.
    command: ['bash', '-c', 'sleep 5; curl -v --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT || sleep 300']
  restartPolicy: Never
```
