### ISSUE TITLE
Sidecar resources silently failing on invalid config

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#12193]
**Describe the bug**
Create a Sidecar:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: scope
  namespace: withsidecar
spec:
  egress:
  - hosts:
    - "withsidecar/*"
    - "istio-system/*"
    - "other/productpage" # <--- THIS ONE
```

And the Sidecar resource is silently rejected... or something happens to it. Either way it is not used. https://github.com/istio/istio/blob/da8d99904b80853b8b4757ba8096ac2f262da8a3/pilot/pkg/model/push_context.go#L792 shows an empty list. Removing the "other/productpage" line causes it to be accepted.

**Expected behavior**
If "other/productpage" is valid, then accept the Sidecar resource and use it. If it isn't, explicitly reject it.

**Version**
1.1 rc1

@rshriram
