### ISSUE TITLE
Migrate manifests from {extensions/v1beta1,apps/v1beta1,apps/v1beta2} to apps/v1

### ISSUE THREAD

**Issue by liggitt** [istio/istio#12211]
**Describe the feature request**

There are ~165 manifests in the repo using deprecated versions of DaemonSets, Deployments, ReplicaSets, and StatefulSets (in extensions/v1beta1, apps/v1beta1, or apps/v1beta2).

These resources have been deprecated since k8s v1.9 and are planned to no longer be served starting in k8s v1.16 (c.f. https://github.com/kubernetes/kubernetes/issues/43214).

All supported versions of k8s have the apps/v1 versions of these resources available. Switching manifests to use the GA versions of these resources ensures broader compatibility and longer-term support.

Migration involves:
* changing apiVersion to `apps/v1`
* populating `spec.selector.matchLabels` with the contents of `spec.template.metadata.labels` if `spec.selector` does not already exist
* populating `metadata.labels` with the contents of `spec.template.metadata.labels` if `metadata.labels` does not already exist

**Comment by hzxuzhonghu** [comment]
Thanks @liggitt , should upgrade to apps/v1 in 1.2

/assign

**Comment by hzxuzhonghu** [comment]
@asifdxtreme

**Comment by ozevren** [comment]
@irisdingbj

**Comment by irisdingbj** [comment]
@hzxuzhonghu Have you working on this already? If not I can work on this as I am working on https://github.com/istio/istio/issues/2119 and this issue is related.

**Comment by hzxuzhonghu** [comment]
no

**Comment by linsun** [comment]
@liggitt is there any doc that indicated the top level deployment  labels are required in the newer version we are moving to (e.g. apps/v1)?

A bit concerned with the redundant of labels below we have for product page as a golden sample:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: productpage-v1
  labels:
    app: productpage
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: productpage
        version: v1
```
