### ISSUE TITLE
Why can't a VirtualService route based on prefix in case of HTTPS?

### ISSUE THREAD

**Issue by Kajvdh** [istio/istio#12222]
I am trying to route a request using an Istio Ingress Gateway.
In case of HTTP, this was easy since I could use the `http.match.uri.prefix` property in my `VirtualService`:
```yml
http:
    - match:
        - uri:
            prefix: /eureka
      route:
        - destination:
            host: discovery-server-service
            port:
              number: 8080
```
This works perfectly, however, the upstream service that the ingress has to route the request to is using HTTPS, so instead of using a `http` block, I now need to use `tls` block:

```yml
tls:
  - match:
      - uri:
            prefix: /eureka
      - port: 443
        sni_hosts:
          - 'k8s.example.com'
    route:
      - destination:
          host: discovery-server-service
          port:
            number: 443
```

But, apparantly it is not possible to use a `uri.prefix` property to match the URL of the request with when using a `tls` block instead of a `http` block. How can I achieve the desired request routing based on the path in the URI with istio when using HTTPS for the upstream services?

Kind regards,

Kaj
