### ISSUE TITLE
Add allowPrivilegeEscalation default to PodSecurityPolicy

### ISSUE THREAD

**Issue by ostromart** [istio/istio#12231]
See https://github.com/istio/istio/issues/11571#issuecomment-469081061 for context. 
k8s admission controller requires this.

**Comment by mattmi88** [comment]
@ostromart - I've been rooting around in the PSP admission plugin code to sort out how it works so I'm hoping my discussion below can give you a leg up on this work item. I'm struggling to get a PSP and a container securityContext config that works reliably. It's been a real pain in the neck!

First, I recommend getting familiar with the Kubernetes [podsecuritypolicy provider code](https://github.com/kubernetes/kubernetes/blob/master/pkg/security/podsecuritypolicy/provider.go). From there, you can get the gist of how it works. For more details, grok the various support data structure objects (especially strategies and capabilities).

In the admission process, mutating admission plugins are run first and then the validating plugins. And the PSP mutating plugin runs before the webhook mutating plugin.

The PSP plugin goes through all the PSPs and mutates the pod based on the PSP definition (oddly, it doesn't discard the PSP because of disallowed RBAC access until after it does the mutating work). The first one that mutates successfully is picked; however, if it finds one that doesn't mutate at all, then that PSP is chosen. The pod is tagged with an annotation naming the chose. PSP name. This annotation is the only piece of information you have to know which PSP won the lottery.

When the sidecar injection webhook plugin fires, it now adds a couple more containers that the PSP plugin didn't get a chance to mutate.

Then the validation phase occurs, so the PSP plugin fires. That's when things go wonky. In the mutating phase, the pod can be mutated, but in the validation phase, it can't. The plugin uses the same logic of applying the PSP to the pod, but this time, if a mutation occurs, the PSP is discarded. The first PSP that doesn't cause a mutation wins. Usually the last PSP in the list (alphabetically) is a restricted PSP that doesn't mutate but also doesn't satisfy the validation. (In my case, the restricted PSP doesn't have any `allowedCapabilities`, so it fails on trying to add NET_ADMIN.) The validation errors displayed are for that last PSP and not the one that was used in the mutating phase. The general idea is that the PSP in the mutating phase is going to be the one that also succeeds in the validation phase.

What this means is that if you mutate the pod after the PSP plugin, you better make absolutely certain that it matches exactly to the PSP in the validate phase. And it's impossible to get any logs of what mutation caused a PSP to be discarded in the validation phase. So it becomes a trial-and-error test loop until you finally hit on one that works.

For now, I've managed to get a PSP to work with `allowedCapabilities: ["NET_ADMIN", "NET_RAW"]`. But I can't add `requiredDropCapabilities: ["ALL"]` even though I've update the sidecar injection configmap with `capabilities.drop: ["ALL"]` for the init container. Note: NET_RAW was necessary for iptables to save the updates since I also included a drop ALL. BTW, using drop ALL is a strategy that increases the chance of a custom PSP being picked over a system-wide one since they're processed alphabetically.

From the linked issue, the definition for `allowPrivilegeEscalation: false` should be a non-issue. It's good to have since most PSPs will want to set `defaultAllowPrivilegeEscalation: false` and that will trigger a mutation if the container doesn't have it already defined.

Below is a copy of my desired PSP (I still want to get requiredDrop ALL to work) that you might find useful. You're welcome to use it for testing and include any variation of it for customer documentation - that's going to be necessary as more people adopt PSPs in their clusters.

This PSP works well with the manual injection, but currently fails with the auto-injection, probably for some mutation in the validation phase I can't figure out yet.

```yaml
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: istio-poc.poc-services.pod-security
spec:
  privileged: false
  allowPrivilegeEscalation: false
  defaultAllowPrivilegeEscalation: false
  allowedCapabilities:
  - NET_ADMIN
  - NET_RAW
  defaultAddCapabilities: []
  requiredDropCapabilities:
  - ALL
  allowedUnsafeSysctls: []
  forbiddenSysctls: []
  allowedHostPaths: []
  hostIPC: false
  hostNetwork: false
  hostPID: false
  hostPorts: []
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: MustRunAs
    ranges:
    - min: 0
      max: 0
    - min: 1337
      max: 1337
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  readOnlyRootFilesystem: false
  allowedFlexVolumes: []
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
```

Below is the fragment of the injected initContainer securityContext (I disabled requireDrop in the PSP so it will pass validation) so you can see the tweak I made to the sidecare injection configmap.

```yaml
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        drop:
        - ALL
      procMount: Default
      readOnlyRootFilesystem: false
      runAsUser: 0
```

I hope this information is helpful to you and also hope you can improve the PSP-securityContext config definitions for the init and proxy containers.

**Comment by mattmi88** [comment]
A follow-up. Although I set the `initContainer.securityContext.capabilities.drop: ["ALL"]`, I failed to double-check the proxy container, which apparently did *not* have that setting. That caused it to mutate in the validation phase and fail. This is a case where the PSP  validation error message misled me to think the init container was wrong.

My recommendation is that the injector configmap define the bare minimum security it needs to run and then give guidance to the community on how to construct a PSP that will take this into account.
- The starting point for any container should be `capabilities.drop: ["ALL"]` and then add only what is necessary, such as NET_BIND_SERVICE for any container that needs to bind to a port below 1024.
- I found NET_ADMIN and NET_RAW are required for iptables when drop ALL is defined.
- Neither container needs privilege escalation (normally).
- The init container needs `readOnlyRootFilesystem: false` so it can save the iptables updates. The proxy container does not. This might be a sore point with some people who really want to lock down their file system.
- Neither container needs any of the PSP `host*` settings enabled (yay!).
- You'll see in my PSP that I specifically set two single-range entries for `runAsUser` with `rule: MustRunAs`. A bit ugly, but it describes exactly what's necessary for the init (root, UID: 0) and proxy (UID: 1337) containers. Any user will need to know these are required in any PSP they construct.
- By setting `rule: RunAsAny` for `fsGroup`, `supplementalGroups` and `seLinux`, I avoided requiring them declared in my pod and/or container `securityContext`. This is often ok for most people. Securing the file system with these PSP settings will require a user to also update the sidecar injector configmap or it will fail PSP validation.

In my updated `istio-sidecar-injector` configmap, below are the updated `securityContext` fragments for the init and proxy sidecar containers that work with the PSP I provided earlier.

```yaml
      initContainers:
      {{ "[[ if ne (annotation .ObjectMeta `sidecar.istio.io/interceptionMode` .ProxyConfig.InterceptionMode) \"NONE\" ]]" }}
{{- if not .Values.istio_cni.enabled }}
      - name: istio-init
...
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            drop:
            - ALL
          {{- if .Values.global.proxy.privileged }}
          allowPrivilegeEscalation: true
          privileged: true
          {{- else }}
          allowPrivilegeEscalation: false
          {{- end }}
          readOnlyRootFilesystem: false
          runAsUser: 0
...
```

```yaml
...
      containers:
      - name: istio-proxy
...
        securityContext:
          {{- if .Values.global.proxy.privileged }}
          allowPrivilegeEscalation: true
          privileged: true
          {{- else }}
          allowPrivilegeEscalation: false
          {{- end }}
          {{- if ne .Values.global.proxy.enableCoreDump true }}
          readOnlyRootFilesystem: true
          {{- end }}
          capabilities:
            drop:
            - ALL
          {{ "[[ if eq (annotation .ObjectMeta `sidecar.istio.io/interceptionMode` .ProxyConfig.InterceptionMode) \"TPROXY\" -]]" }}
            add:
            - NET_ADMIN
          runAsGroup: 1337
          {{ "[[ else -]]" }}
          {{ if and .Values.global.sds.enabled .Values.global.sds.useTrustworthyJwt }}
          runAsGroup: 1337
          {{- end }}
          runAsUser: 1337
          {{ "[[- end ]]" }}
...
```

Hope this helps...

**Comment by k-f** [comment]
An additional point on this one.  Things also go wrong if you specify any seccomp or apparmour annotations in your pod security policy.  Eg here is a restricted PSP that does work with the istio sidecar if you deploy it manually, but you cannot use this PSP in partnership with the sidecar injector:

```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted-psp
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'docker/default'
    apparmor.security.beta.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: true 
```

The apparmour annotation is a particular issue, the PSP mutating plugin adds apparmour policy in the form of `apparmor.security.beta.kubernetes.io/[container name]: runtime/default`.  The istio injector runs following this and so you have one container with an apparmour policy and then the istio one without.  You can't manually add an apparmour annotation of `apparmor.security.beta.kubernetes.io/istio-proxy: runtime/default` to your deployment in advance as k8s validates that the istio-proxy container exists when the deployment is submitted and validation fails as the injector hasnt run yet.

I've successfully worked around all the other issues by customising the injector configmap in the helm chart to add in required configuration eg requiredDropCapabilities, privileged, allowPrivilegeEscalation, etc but I suspect solving for this apparmour point will to require larger changes to the injector.

For now to work around this we are manually templating the sidecar in advance so that we can have it functioning with a tight pod security policy which is not ideal.

**Comment by mattmi88** [comment]
@k-f - Oh man, that's a whole 'nother level of security pain. 😸 

Thanks for confirming my approach. I too am tweaking the injector configmap so the pod succeeds during the validation phase.

It might be a bit of work, but I think the sidecar injector webhook can get the chosen PSP from the annotation. It can then perform it's own mutation on the injected containers. The logic "should" be "includable" in go so the webhook could call the exact same code to do the work.

**Comment by neeleshkorade** [comment]
@ostromart @mattmi88 I am running into something similar. I followed the pointers given in this issue and the #11571 , however, it still doesn't work for me. Here're the sidecar-innjector configmap, the psp I am using.

```
# SecurityContext for the istio-init container
securityContext:
          runAsUser: 0
          #runAsNonRoot: false
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_ADMIN
        restartPolicy: Always
```

```

**Comment by neeleshkorade** [comment]
@ostromart @mattmi88 I am running into something similar. I followed the pointers given in this issue and the #11571 , however, it still doesn't work for me. Here're the sidecar-innjector configmap, the psp I am using.

```
# SecurityContext for the istio-init container
securityContext:
          runAsUser: 0
          #runAsNonRoot: false
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_ADMIN
        restartPolicy: Always
```

```

**Comment by neeleshkorade** [comment]
@ostromart @mattmi88 I am running into something similar. I followed the pointers given in this issue and the #11571 , however, it still doesn't work for me. Here're the sidecar-innjector configmap, the psp I am using.

```
# SecurityContext for the istio-init container from the injector configmap
securityContext:
          runAsUser: 0
          #runAsNonRoot: false
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_ADMIN
        restartPolicy: Always
```

```
# SecurityContext for the istio-proxy container from the injector configmap
securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_ADMIN
          runAsGroup: 1337
```

```

**Comment by neeleshkorade** [comment]
@ostromart @mattmi88 I am running into something similar. I followed the pointers given in this issue and the #11571 , however, it still doesn't work for me. Here're the sidecar-innjector configmap, the psp I am using.

```
# SecurityContext for the istio-init container from the injector configmap
securityContext:
          runAsUser: 0
          #runAsNonRoot: false
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_ADMIN
        restartPolicy: Always
```

```
# SecurityContext for the istio-proxy container from the injector configmap
securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_ADMIN
          runAsGroup: 1337
```

```
`psp for the service`

apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: sidecar-injector-psp
spec:
  privileged: false
  allowPrivilegeEscalation: false
  allowedCapabilities:
  - NET_ADMIN
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
  - flexVolume
```

My app is deployed in the namespace `app-namespace`. I am binding the service account of my app deployment to the psp given above as follows.
```
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: sidecar-injector-psp-role-binding
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:serviceaccounts:app-namespace
roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
   name: sidecar-injector-psp-role
```

The error I see in the deployment yaml is shown below-
```
kubectl -n app-namespace get deploy sample-generic-app1 -o yaml

```
log-
```
- lastTransitionTime: 2019-06-02T19:54:08Z
    lastUpdateTime: 2019-06-02T19:54:08Z
    message: 'pods "sample-generic-app1-s9rsms"
      is forbidden: unable to validate against any pod security policy: [spec.volumes[7]:
      Invalid value: "flexVolume": flexVolume volumes are not allowed to be used capabilities.add:
      Invalid value: "NET_ADMIN": capability may not be added spec.initContainers[3].securityContext.allowPrivilegeEscalation:
      Invalid value: true: Allowing privilege escalation for containers is not allowed
      capabilities.add: Invalid value: "NET_ADMIN": capability may not be added capabilities.add:
      Invalid value: "NET_ADMIN": capability may not be added spec.initContainers[3].securityContext.allowPrivilegeEscalation:
      Invalid value: true: Allowing privilege escalation for containers is not allowed]'
    reason: FailedCreate
    status: "True"
    type: ReplicaFailure
```

I am clueless as to what might be wrong here. Would appreciate your help on this.
