### ISSUE TITLE
Virtualservice 404 and ECONNREFUSED after 15 minutes

### ISSUE THREAD

**Issue by primehaxor** [istio/istio#12269]
**Describe the bug**
Currently, we have an ISTIO setup with the following options below, everything works fine for 15 to 30 minutes then we start to receive every 3 or 4 requests one 404 or even worse one ECONNREFUSED in the ingress-gateway, all pods are healthy everything is up and running. During the issue, I've run the tests locally in the pods itself. After re-apply the virtualservice rule this behavior goes away.  

Also, I've tried to change the HPA for the ingress-gateway to decrease the threshold and increase the replicas but still with the same issue.

**Expected behavior**
I should be able to do many requests as I want to and receive a 200 in all of them since my pods are healthy

**Steps to reproduce the bug**
Virtualservice:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - my-endpoint-gw
  http:
  - match:
    - uri:
        exact: /package/_health
    - uri:
        prefix: /app/package/prices/
    - uri:
        prefix: /app/package/filters/
    - uri:
    route:
    - destination:
        host: my-endpoint.com
        port:
          number: 3000
    retries:
      attempts: 3
      perTryTimeout: 2s
```

```
siege -c 10 -H "Host: my-endpoint.com" http://1.1.1.1
```

**Version**
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-gke.5", GitCommit:"9aba9c1237d9d2347bef28652b93b1cba3aca6d8", GitTreeState:"clean", BuildDate:"2018-12-11T02:36:50Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}

**Installation**
```
helm template istio-${ISTIO_RELEASE}/install/kubernetes/helm/istio \
        --name istio \
        --namespace istio-system \
        --set gateways.istio-ingressgateway.loadBalancerIP=${CLUSTER_IP} \
        --set global.mtls.enabled=false \
        --set global.proxy.autoInject=disabled \
        --set tracing.enabled=true \
        --set servicegraph.enabled=true \
        --set telemetry-gateway.grafanaEnabled=true \
        --set grafana.enabled=true > istio.yaml
```

**Environment**
Google GKE

**Cluster state**
