### ISSUE TITLE
install/kubernetes/helm/istio/values.yaml correctness for mixer values

### ISSUE THREAD

**Issue by ericvn** [istio/istio#12261]
**Describe the bug**
Top of file has:
```
# chart sections: Every subdirectory inside the charts/ directory has a top level
#       configuration key in this file. This file overrides the values specified
#       by the charts/${chartname}/values.yaml.
#       Check the chart level values file for exhaustive list of configuration options.
```

mixer section:
```
#
# mixer configuration
#
# @see charts/mixer/values.yaml, it takes precedence
mixer:
  enabled: true
  policy:
    # if policy is enabled the global.disablePolicyChecks has affect.
    enabled: false

  telemetry:
    enabled: true
```

Which is correct? Top or mixer section?

**Expected behavior**
Correct above

**Steps to reproduce the bug**
{{ Minimal steps to reproduce the behavior }}

**Version**
1.1.0-rc2

**Installation**
tar file

**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}
