### ISSUE TITLE
Being able to use sniHosts directive with ingress gateway and TLS termination

### ISSUE THREAD

**Issue by yannlambret** [istio/istio#12290]
**Describe the feature request**

Hi,

I would like to be able to route multiple TCP services while exposing a single port on the ingress gateway. The goal is to achieve something similar to the feature described [here](https://www.haproxy.com/fr/blog/enhanced-ssl-load-balancing-with-server-name-indication-sni-tls-extension/) (HAProxy project documentation), but it looks like this use case is not currently supported by Istio. It would be very useful in an hybrid infrastructure context.

**Describe alternatives you've considered**

Exposing each TCP service on a dedicated port of the ingress gateway.

**Additional context**

I've been using Istio 1.0.6 on GKE (kubernetes 1.11.5) to make my tests, and here is the helm command used for the deployment:

```bash
$ kubectl create namespace istio-system

$ ILB_GATEWAY_IP="10.251.92.251"

$ helm install install/kubernetes/helm/istio --name istio --namespace istio-system \
    --set global.mtls.enabled=false \
    --set global.proxy.autoInject=enabled \
    --set gateways.istio-ingressgateway.enabled=false \
    --set gateways.istio-ilbgateway.enabled=true \
    --set gateways.istio-ilbgateway.loadBalancerIP=$ILB_GATEWAY_IP \
    --set gateways.istio-ilbgateway.ports[0].name=http2 \
    --set gateways.istio-ilbgateway.ports[0].port=80 \
    --set gateways.istio-ilbgateway.ports[0].targetPort=80 \
    --set gateways.istio-ilbgateway.ports[0].nodePort=31380 \
    --set gateways.istio-ilbgateway.ports[1].name=tls \
    --set gateways.istio-ilbgateway.ports[1].port=443 \
    --set gateways.istio-ilbgateway.ports[1].targetPort=443 \
    --set gateways.istio-ilbgateway.ports[1].nodePort=31390 \
    --set sidecarInjectorWebhook.enabled=true \
    --set prometheus.enabled=true \
    --set grafana.enabled=true \
    --set tracing.enabled=true \
    --set kiali.enabled=true \
    --set servicegraph.enabled=false \
    --set certmanager.enabled=false
```

Certificates for the ilbgateway are generated by our own cert-manager setup, and are correctly mounted.

Below is an example of configuration that I would like to use, but which does not work.

Istio internal ingress gateway:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-ilbgateway
  namespace: istio-system
spec:
  selector:
    istio: ilbgateway
  servers:
  - hosts:
    - '*.l4.sandbox.gke'
    port:
      name: http
      number: 80
      protocol: HTTP
  - hosts:
    - '*.l4.sandbox.gke'
    port:
      name: tls
      number: 443
      protocol: TLS
    tls:
      mode: SIMPLE
      privateKey: /etc/istio/istio-ilbgateway-certs/tls.key
      serverCertificate: /etc/istio/istio-ilbgateway-certs/tls.crt
```

And the associated virtual services:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tcp-server-1
  namespace: istio-system
spec:
  gateways:
  - istio-ilbgateway
  hosts:
  - tcp-server-1.l4.sandbox.gke
  tls:
  - match:
    - port: 443
      sniHosts:
      - tcp-server-1.l4.sandbox.gke
    route:
    - destination:
        host: tcp-server-1.default
        port:
          number: 3333
```

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tcp-server-2
  namespace: istio-system
spec:
  gateways:
  - istio-ilbgateway
  hosts:
  - tcp-server-2.l4.sandbox.gke
  tls:
  - match:
    - port: 443
      sniHosts:
      - tcp-server-2.l4.sandbox.gke
    route:
    - destination:
        host: tcp-server-2.default
        port:
          number: 3333
```

When applying this configuration, the following error occurs:

```text
2019-03-06T09:10:23.935344Z     info    1 error occurred:

* gateway omitting listener "0.0.0.0_443" due to: must have more than 0 chains in listener: &v2.Listener{Name:"0.0.0.0_443", Address:core.Address{Address:(*core.Address_SocketAddress)(0xc4201f3b68)}, FilterChains:[]listener.FilterChain{}, UseOriginalDst:nil, PerConnectionBufferLimitBytes:nil, Metadata:(*core.Metadata)(nil), DeprecatedV1:(*v2.Listener_DeprecatedV1)(nil), DrainType:0, ListenerFilters:[]listener.ListenerFilter(nil), Transparent:nil, Freebind:nil, SocketOptions:[]*core.SocketOption(nil), TcpFastOpenQueueLength:nil}                                                                                                   
2019-03-06T09:10:23.935549Z     info    ads     LDS: PUSH for node:istio-ilbgateway-58c794fb4b-nxzn6.istio-system addr:"10.251.133.10:48194" listeners:1 2290                                                     
2019-03-06T09:10:23.935594Z     info    ads     Push finished: 10.275332ms {
    "ProxyStatus": {},
    "Start": "2019-03-06T09:10:23.92531494Z",
    "End": "2019-03-06T09:10:23.935567394Z"
}
```
The HTTP listener is created as expected though:

```text
$ istioctl proxy-config listeners -n istio-system istio-ilbgateway-58c794fb4b-nxzn6
ADDRESS     PORT     TYPE
0.0.0.0     80       HTTP
```

I believe the relevant code is in the file `pilot/pkg/networking/core/v1alpha3/gateway.go`. The way I see it, the problem is related to the fact that the function invoked to build listeners when TLS mode is SIMPLE is `buildGatewayNetworkFiltersFromTCPRoutes`, whereas we would need `buildGatewayNetworkFiltersFromTLSRoutes`, which is only invoked when TLS mode is PASSTHROUGH.

But I might have missed something obviously.

Do you think this feature could be implemented in the future?

Kind regards,

Yann
