### ISSUE TITLE
EnvoyFilter isn't applied in 1.1-rc.2

### ISSUE THREAD

**Issue by theganyo** [istio/istio#12313]
**Describe the bug**
Creating an EnvoyFilter in Istio 1.1-rc.2 does nothing.

**Steps to reproduce the bug**
I created and applied the simplest possible Lua filter I could:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: lua-test
spec:
  filters:
  - filterName: envoy.lua
    filterType: HTTP
    filterConfig:
      inlineCode: |
        function envoy_on_request(request_handle)
          request_handle:logCritical("log test")
        end
```

There is no effect in 1.1. I've verified that this works in 1.0 and that /config_dump includes the filter in 1.0 and not in 1.1.

**Version**
➜  temp istioctl version
version.BuildInfo{Version:"1.1.0-rc.2", GitRevision:"a5e38d2cbedbb1eeb8f60b24176656d1813dea44", User:"root", Host:"d994e95d-3e07-11e9-8dad-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-rc.1-25-ga5e38d2"}
➜  temp kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Installation**
kubectl apply -f $ISTIO/install/kubernetes/istio-demo.yaml

**Environment**
Docker for Desktop Mac

**Comment by mandarjog** [comment]
@theganyo did you test it with a prior release?

@robertpanzer are you injecting lua filters in 1.1  or 1.0 ?

**Comment by theganyo** [comment]
No, I haven’t tested against the various pre-releases of 1.1. When it didn’t work, I tested against 1.0 as a baseline.

**Comment by robertpanzer** [comment]
I got it working on rc2 by adding workloadLabels and a listenerMatch:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: lua-test
spec:
  workloadLabels:
  filters:
    - listenerMatch:
        listenerProtocol: HTTP
        listenerType: SIDECAR_INBOUND
      filterName: envoy.lua
      filterType: HTTP
      filterConfig:
        inlineCode: |
          function envoy_on_request(request_handle)
            request_handle:logCritical("log test")
          end
```

The workloadLabels can even be empty, but have to be there.
Without the listenerMatch it also seems that the filter is not applied.
Both make sense, but it is not documented like this, I think this could be enhanced.

I am always using the listenerMatch and the workloadLabels, so I cannot quickly test if this worked on 1.0.

**Comment by theganyo** [comment]
Interesting. My first attempts had both listenerMatch and workloadLabels, but I removed all optional fields and whittled it down to the minimum to see if I could get it working at all. It never did, but I’ll give it another try.

**Comment by mandarjog** [comment]
Without listener match pilot will attempt to place an http filter outside http connection manager.

**Comment by theganyo** [comment]
Aha! So the real key to all this is `listenerProtocol: HTTP`. Indeed, I just verified that this must be present to win. All other fields are optional.

**Comment by theganyo** [comment]
I'll be happy to make a doc change for this, but I want to be sure I'm specific and correct. Perhaps just a warning on the EnvoyFilter doc page that if it uses an Envoy HTTP filter, it will not work unless `listenerProtocol: HTTP` is set. Does that sound correct?

**Comment by mandarjog** [comment]
Yes that sounds right.

**Comment by esnible** [comment]
I'd like to fix validation for workload labels.

The documentation https://preliminary.istio.io/docs/reference/config/networking/v1alpha3/envoy-filter/#EnvoyFilter says there should be "one or more" workload labels but this isn't checked.  I saw the same language for the Sidecar CRD and it is checked there.

The documentation for listenerProtocol https://preliminary.istio.io/docs/reference/config/networking/v1alpha3/envoy-filter/#EnvoyFilter-ListenerMatch says "If not specified, applies to listeners on all protocols."  That seems unimplemented.  Do we need a defect to fix it?

**Comment by theganyo** [comment]
There's seemingly another doc issue as well: The following are from two different spots on the page and (I believe) contradictory. Which is correct?

```
NOTE 2: When multiple EnvoyFilters are bound to the same workload, all filter configurations will be processed sequentially in order of creation time. The behavior is undefined if multiple EnvoyFilter configurations conflict with each other.
```

```
NOTE: There can be only one EnvoyFilter bound to a specific workload. The behavior is undefined if multiple EnvoyFilter configurations are specified for the same workload.
```

**Comment by theganyo** [comment]
As far as I can tell from the code, the first note (NOTE 2) is the correct one.

@esnible Is there a good reason to force workload labels?

**Comment by esnible** [comment]
@theganyo You are correct, we should not force workload labels.  I made a mistake when testing.

I did find a delay.

First I recreated your no-workload-label example adding a listenerMatch
```
    listenerMatch:
        listenerProtocol: HTTP
        listenerType: SIDECAR_INBOUND
```

I confirmed it was attached to the pod using `kubectl exec httpbin-54f5bb4957-l9nds -c istio-proxy -- curl --silent localhost:15000/config_dump | grep lua`

I then deleted it and repeated the command above to see if the filter was removed from the config.  It was, but it took about 40 seconds to go away.

**Comment by theganyo** [comment]
I'll just update the docs to say "zero or more" workload labels as well.

**Comment by theganyo** [comment]
Re:

> The documentation for listenerProtocol https://preliminary.istio.io/docs/reference/config/networking/v1alpha3/envoy-filter/#EnvoyFilter-ListenerMatch says "If not specified, applies to listeners on all protocols." That seems unimplemented. Do we need a defect to fix it?

I'm not sure. This is what confused me and why I was going to add the warning that `listenerProtocol: HTTP` must be specified. It feels like these two statements are contrary... but wasn't sure if I'm just missing some nuance?

**Comment by theganyo** [comment]
Alternatively, it is a documentation issue and validation omission. The specific case of "tcp listener, http filter" is called out as invalid [in the code](https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/envoyfilter.go#L61), but there's no error when you submit an EnvoyFilter with `filterType: HTTP` and either no `listenerProtocol` or `listenerProtocol: TCP`.

**Comment by rshriram** [comment]
sorry for the confusion.. the envoy filter code can insert a network filter to both tcp based services/listeners, and http based services.. that said, order of insertion matters.. in the end, we run a validate() function on each listener.. if any of them are found to be invalid we skip it (or all?)

Envoy for its part does same..

**Comment by theganyo** [comment]
Unfortunately, I'm still confused. The issue is clear: if you have a EnvoyFilter of `filterType: HTTP` and you don't also explicitly include a `listenerMatch.listenerProtocol: HTTP` it just silently fails. But it still isn't clear to me what the appropriate resolution is.

**Comment by theganyo** [comment]
The PR referenced above just updates the docs to match the behavior.

**Comment by howardjohn** [comment]
@theganyo is this still an issue? In master builds which have had many changes to them, I applied the config:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: lua-test
spec:
  filters:
  - filterName: envoy.lua
    filterType: HTTP
    filterConfig:
      inlineCode: |
        function envoy_on_request(request_handle)
          request_handle:logCritical("log test")
        end
```

And I see it show up correctly
