### ISSUE TITLE
In the gateway connectivity setting with egress gateway, the egress gateway ignores the external endpoint

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#12326]
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin-bar
  namespace: foo
spec:
  addresses:
  - 127.255.0.2
  endpoints:
  - address: <cluster2 ingress gateway IP (node port)>
    network: external
    ports:
      http1: 31390
  - address: istio-egressgateway.istio-system.svc.cluster.local
    ports:
      http1: 443
  hosts:
  - httpbin.bar.global
  location: MESH_INTERNAL
  ports:
  - name: http1
    number: 8000
    protocol: http
  resolution: DNS
```

Egress gateway's endpoints:
```
    {
        "name": "outbound|8000||httpbin.bar.global",
        "addedViaApi": true,
        "hostStatuses": [
            {
                "address": {
                    "socketAddress": {
                        "address": "172.21.149.253",
                        "portValue": 443
                    }
                },
```

Egress gateway clusters
```
 {
        "name": "outbound|8000||httpbin.bar.global",
        "type": "STRICT_DNS",
        "connectTimeout": "1s",
        "loadAssignment": {
            "clusterName": "outbound|8000||httpbin.bar.global",
            "endpoints": [
                {},
                {
                    "lbEndpoints": [
                        {
                            "endpoint": {
                                "address": {
                                    "socketAddress": {
                                        "address": "istio-egressgateway.istio-system.svc.cluster.local",
                                        "portValue": 443
                                    }
                                }
                            },
                            "loadBalancingWeight": 1
                        }
                    ]
                }
            ]
        },
```
