### ISSUE TITLE
TLS termination in istio-ingressgateway for routing based on HTTP match

### ISSUE THREAD

**Issue by absc6** [istio/istio#12332]
I would like to know if anyone has implemented **uri.prefix** based routing at ingress gateway.
I am getting 503 Service Unavailable when I am trying to route the request based on URI
```
curl -v -k -H 'Host: test.secure.internal.com' https://$EXTERNAL-IP:$EXTERNAL-PORT/users
> Host: test.secure.internal.com 
>
< HTTP/1.1 503 Service Unavailable
< content-length: 57
< content-type: text/plain
< date: Thu, 07 Mar 2019 18:57:30 GMT
< server: envoy
<

```
Serviceentry is working correctly within the istio cluster

```
kubectl exec -it $SLEEP-POD -- curl -k https://test.external.com:10443/users
[{"firstName":"John","lastName":"Doe"}]
```

Below are the istio config of Gateway, VirtualService and ServiceEntry
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: secure-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*"
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: secure-gateway-routing 
spec:
  hosts:
  - test.secure.internal.com 
  gateways:
  - secure-gateway 
  http:
  - match:
    - uri:
        prefix: /users
    route:
    - destination:
        host: test.external.com #should this match service entry or be external???
        port:
          number: 10443
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: test-http
spec:
  hosts:
  - test.external.com
  ports:
   - number: 10443 
    name: httpsexternal 
    protocol: HTTPS
  location: MESH_EXTERNAL 
  resolution: DNS 
---
```

**Comment by absc6** [comment]
This worked by adding destinationrule with following config
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: test-http-dr
spec:
  host: test.external.com
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 10443
      tls:
        mode: SIMPLE
```
