### ISSUE TITLE
ServiceEntry validation is too agressive

### ISSUE THREAD

**Issue by silentdai** [istio/istio#12338]
**Describe the feature request**
The below service entry yaml file pass the validation but is not accepted by pilot.
```
2019-03-07T23:14:57.198462Z     info    parseHostname(foo) => error missing service name and namespace from the service hostname "foo"
```
Several issues:
- namespace is not required field. `default` is the default
- in my yaml, my ports of service entry has the prototype TCP.  From the description of `hosts` here, I don't see why we need a `DNS` name or a hostname.
- The service entry doesn't translate to a valid listener config for envoy. 

**Describe alternatives you've considered**
Either document or the implementation. Hopefully the implementation because semantically it is a valid service entry IMHO.

**Additional context**
The example serviceentry yaml
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: serviceentrytest
spec:
  hosts:
  - foo  # foo.make.it.dnsname.com works
  addresses:
  - 192.192.192.0/24  
  ports:
  - number:  7000
    name: fooportname
    protocol: TCP
  location: MESH_INTERNAL
  resolution: STATIC
  endpoints:
  - address: 10.39.241.138  # my helloword
    ports:
      fooportname: 5000
```
