### ISSUE TITLE
Outlier detection not working for Consecutive 5XX Errors

### ISSUE THREAD

**Issue by velumaniduraisamy** [istio/istio#12349]
Istio Version -  Istio-1.1.0-rc2

I trying to apply outlier detection for my service in case of consecutive errors but circuit break didn't happen. 

In service B I injected delay and abort fault. In service A, I put outlier detection traffic policy for 3 consecutive errors within 30 seconds. 

Fault Injection in Service B
```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service_b
 
spec:
  gateways:
  - service_b
  - mesh
  hosts:
  - api.test.com
  - service_b
  http:
  - fault:
      delay:
        fixedDelay: 2s
        percentage:
          value: 100
      abort:
        httpStatus: 503
        percentage:
          value: 100
    match:
    - uri:
        prefix: /svcb
    route:
    - destination:
        host: service_b
        port:
          number: 7001
    retries:
      attempts: 3
  - route:
    - destination:
        host: service_b
        port:
          number: 7001
    retries:
      attempts: 3
EOF
``` 

Destination Rule for Service A
```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: service_a
spec:
  host: service_a
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 1
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
        maxRetries: 3
    outlierDetection:
      consecutiveErrors: 3
      interval: 30s
      baseEjectionTime: 3m
      maxEjectionPercent: 100
EOF
```
Config Dump 
```
     "outlier_detection": {
       "interval": "30s",
       "base_ejection_time": "180s",
       "max_ejection_percent": 100,
       "enforcing_consecutive_5xx": 0,
       "consecutive_gateway_failure": 3,
       "enforcing_consecutive_gateway_failure": 100
      }
```
