### ISSUE TITLE
Istio Serviceentry with Oracle clustered DB

### ISSUE THREAD

**Issue by Joerg-L** [istio/istio#12350]
**Describe the bug**
We want to connect from an deployed application to a Oracle Database which is clustered.

We have deployed following serviceentry
````
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: oracle-cluster02
spec:
  hosts:
  - something-scan.domainname.local
  location: MESH_EXTERNAL
  ports:
  - name: tcp
    number: 1521
    protocol: tcp
  resolution: DNS
````

Where something-scan.domainname.local is resolving to three IP Addresses as the cluster is a 3-Node-Cluster.
But connection fails with 
> ORA-12520: TNS:listener could not find available handler for requested

When changing host from 
> something-scan.domainname.local

to a node name from the cluster
> cluster-node-01.domainname.local

the connection works, without any change to application configuration.

Also it works from outside of the Kubernetes Cluster to access the Database with the SCAN-Name

**Expected behavior**
Connection should be successfull

**Steps to reproduce the bug**
- Clustered Oracle Db with SCAN (single client access name)
- application to try to connect through SCAN-Name to DB

**Version**
Istio 1.0.4
Kubernetes 1.12.2

**Installation**
by Helm

**Environment**
On-Prem Kubernetes on virtual machines
