### ISSUE TITLE
Istio ingressgateway TLS port does not create listener for PASSTHROUGH

### ISSUE THREAD

**Issue by absc6** [istio/istio#12359]
When trying to expose istio service mesh to external IP/Port using NodePort on k8 cluster. Istio ingressgateway does not create a listener unless TLS mode mentioned is SIMPLE.
Secure-gateway.yaml
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: secure-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*"
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
```
Listeners: 
```
# istioctl -n istio-system proxy-config listener $(kubectl get po -l istio=ingressgateway -n istio-system -o jsonpath='{.items[0]..metadata.name}')
ADDRESS     PORT     TYPE
0.0.0.0     80       HTTP
0.0.0.0     443      HTTP
```
When the gateway TLS mode is changed to PASSTHROUGH, the listener no longer exists
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: secure-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*"
    tls:
      mode: PASSTHROUGH
```
Listeners:
```
# istioctl -n istio-system proxy-config listener $(kubectl get po -l istio=ingressgateway -n istio-system -o jsonpath='{.items[0]..metadata.name}')
ADDRESS     PORT     TYPE
0.0.0.0     80       HTTP
```

**Istio version: 1.0.5**
**K8 Version: 1.13.1**
