### ISSUE TITLE
ISTIO 1.0.6 istio-galley endpoint not ready 

### ISSUE THREAD

**Issue by HamzaK8s** [istio/istio#12389]
**Describe the bug**

I installed the latest version of Istio provided by  the command ``` curl -L https://git.io/getLatestIstio | sh - ```
And when I want to create a destinationRule I got the following errors 

```
kubectl create -f routing.yaml
gateway.networking.istio.io/my-gw created
virtualservice.networking.istio.io/hello-vs created
Error from server (InternalError): error when creating "routing.yaml": Internal error occurred:failed calling webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: stream error: stream ID 5; INTERNAL_ERROR
```
Galley pod is up and running, I got this, while checking istio-galley logs
```
2019-03-10T18:08:12.100576Z     warn    istio-galley validatingwebhookconfiguration update deferred: istio-system/istio-galley endpoint not ready: no ready addresses
2019-03-10T18:08:17.107951Z     info    istio-galley validatingwebhookconfiguration updated
2019-03-10T18:13:19.483853Z     info    http2: panic serving 172.16.0.1:37530: runtime error: invalid memory address or nil pointer dereference
goroutine 426 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc4200ba018, 0xc42056ffaf, 0xc42018f880)
        /usr/local/go/src/net/http/h2_bundle.go:5753 +0x190
panic(0x194b8c0, 0x29ca8e0)
        /usr/local/go/src/runtime/panic.go:502 +0x229
istio.io/istio/pilot/pkg/model.validateSubset(0x0, 0x0, 0xc42056f8f0)
        /workspace/go/src/istio.io/istio/pilot/pkg/model/validation.go:629 +0x2c
istio.io/istio/pilot/pkg/model.ValidateDestinationRule(0xc4200590e0, 0x15, 0xc420938cd9, 0x7, 0x1dc2080, 0xc4205e4a20, 0xa, 0x1be8346)
        /workspace/go/src/istio.io/istio/pilot/pkg/model/validation.go:490 +0x13f
istio.io/istio/galley/pkg/crd/validation.(*Webhook).admitPilot(0xc4201143c0, 0xc420384140, 0xc4201b4930)
        /workspace/go/src/istio.io/istio/galley/pkg/crd/validation/webhook.go:398 +0x45e
istio.io/istio/galley/pkg/crd/validation.(*Webhook).(istio.io/istio/galley/pkg/crd/validation.admitPilot)-fm(0xc420384140, 0xc4205a4000)
        /workspace/go/src/istio.io/istio/galley/pkg/crd/validation/webhook.go:364 +0x34
istio.io/istio/galley/pkg/crd/validation.serve(0x1dccb80, 0xc4200ba018, 0xc42087a100, 0xc4208d1cc0)
        /workspace/go/src/istio.io/istio/galley/pkg/crd/validation/webhook.go:340 +0x4ee
istio.io/istio/galley/pkg/crd/validation.(*Webhook).serveAdmitPilot(0xc4201143c0, 0x1dccb80, 0xc4200ba018, 0xc42087a100)
        /workspace/go/src/istio.io/istio/galley/pkg/crd/validation/webhook.go:364 +0x5f
istio.io/istio/galley/pkg/crd/validation.(*Webhook).(istio.io/istio/galley/pkg/crd/validation.serveAdmitPilot)-fm(0x1dccb80, 0xc4200ba018, 0xc42087a100)
        /workspace/go/src/istio.io/istio/galley/pkg/crd/validation/webhook.go:224 +0x48
net/http.HandlerFunc.ServeHTTP(0xc4205ee440, 0x1dccb80, 0xc4200ba018, 0xc42087a100)
        /usr/local/go/src/net/http/server.go:1947 +0x44
net/http.(*ServeMux).ServeHTTP(0xc4205f0360, 0x1dccb80, 0xc4200ba018, 0xc42087a100)
        /usr/local/go/src/net/http/server.go:2340 +0x130
net/http.serverHandler.ServeHTTP(0xc420027ad0, 0x1dccb80, 0xc4200ba018, 0xc42087a100)
        /usr/local/go/src/net/http/server.go:2697 +0xbc
net/http.initNPNRequest.ServeHTTP(0xc42039a380, 0xc420027ad0, 0x1dccb80, 0xc4200ba018, 0xc42087a100)
        /usr/local/go/src/net/http/server.go:3263 +0x9a
net/http.(Handler).ServeHTTP-fm(0x1dccb80, 0xc4200ba018, 0xc42087a100)
        /usr/local/go/src/net/http/h2_bundle.go:5475 +0x4d
net/http.(*http2serverConn).runHandler(0xc42018f880, 0xc4200ba018, 0xc42087a100, 0xc4205d02a0)
        /usr/local/go/src/net/http/h2_bundle.go:5760 +0x89
created by net/http.(*http2serverConn).processHeaders
        /usr/local/go/src/net/http/h2_bundle.go:5494 +0x46b
```
**Expected behavior**

**Steps to reproduce the bug**

**Version**
istio version : 1.0.6
kubectl version: 
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
**Installation**
Following the instruction of Option 1: Install with Helm via helm template
**Environment**
kubeadm 

```
kubeadm version: &version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:35:32Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

```

Thank you for you help

**Comment by HamzaK8s** [comment]
@hzxuzhonghu do you have any idea or tips to help ?

**Comment by ymesika** [comment]
@HamzaK8s can you please share your `routing.yaml`?

**Comment by hzxuzhonghu** [comment]
I think its because a invalid desctinationrule with subset nil

**Comment by hzxuzhonghu** [comment]
Like this 
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews
spec:
  host: reviews
  subsets:
  - 
  - name: v2
    labels:
      version: v2
  - name: v3
    labels:
      version: v3

```

**Comment by HamzaK8s** [comment]
@ymesika Here's the yaml file of routing.yaml 
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gw
spec:
 selector:
    istio: ingressgateway
 servers:
 - port:
     number: 80
     name: http
     protocol: HTTP
   hosts:
   - '*'

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-vs
spec:
 hosts:
 - '*'
 gateways:
 - my-gw
 http:
 - match:
   - uri:
      exact: /hello
   route:
   - destination:
       host: helloworld
       port:
         number: 5000
       subset: v1
     weight: 25
   - destination:
       host: helloworld
       port:
         number: 5000
       subset: v2
     weight: 75
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
   name: hello-policy-versions
spec:
 host: helloworld.default.svc.cluster.local
 subsets:
 - name: v1
   labels:
     version: v1
 - name: v2
   labels:
     version: v2
```
