### ISSUE TITLE
Configuring an external TCP endpoint (Microsoft SQL Server, TCP: 1433)

### ISSUE THREAD

**Issue by HXK123** [istio/istio#12390]
**Description of issue**
Hi,

I am having a little trouble adapting the examples for configuring external TCP endpoints in Istio.  I wish to create a consistent service name that points to varying external IP address endpoints (e.g., external database server on port 1433) so that applications in Kubernetes do not have to update the hostname between environments (e.g., Test vs. Staging vs. Production).

These are the two examples I have tried (with and without a `VirtualService`):

* https://preliminary.istio.io/blog/2018/egress-mongo/#control-tcp-egress-traffic-without-a-gateway
* https://preliminary.istio.io/blog/2018/egress-mongo/#control-tls-egress-traffic-without-a-gateway

Here is the latest attempt:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: mssql
spec:
  hosts:
  - mssql.testdomain
  ports:
  - number: 1433
    name: tcp-mssql
    protocol: TCP
  resolution: NONE
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mssql
spec:
  hosts:
  - mssql.testdomain
  tls:
  - match:
    - port: 1433
      sni_hosts:
      - mssql.testdomain
    route:
    - destination:
        host: 10.10.5.5
        port:
          number: 1433
```

However, when I try to ping `mssql.testdomain` from within the application container or use `sqlcmd` to connect via port 1433, I get a connection timeout.  If I use `sqlcmd` to connect to the IP address directly, I am able to query the schema.

Am I doing something wrong?  I also tried with `resolution: STATIC` with similar results:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: mssql
spec:
  hosts:
  - mssql.testdomain
  addresses:
  - 10.10.5.5/32
  ports:
  - number: 1433
    name: tcp-mssql
    protocol: TCP
  resolution: STATIC
  location: MESH_EXTERNAL
  endpoints:
  - address: 10.10.5.5
    ports:
      tcp-mssql: 1433
```

If I use native Kubernetes `Service` and `Endpoint` objects, I am able to connect without any issues:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: {{ include "app.name" . }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: tcp-{{ include "app.name" . }}
---
kind: Endpoints
apiVersion: v1
metadata:
  name: {{ include "app.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: {{ include "app.name" . }}
subsets:
  - addresses:
      - ip: 10.10.5.5
    ports:
      - port: {{ .Values.service.port }}
```

Any help is greatly appreciated.

Thanks!

**Version**
```
$ istioctl version
Version: 1.0.5
GitRevision: c1707e45e71c75d74bf3a5dec8c7086f32f32fad
User: root@6f6ea1061f2b
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean
```

**Installation**
Installed via Helm Chart.

**Environment**
IBM Cloud Kubernetes Service:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.8+IKS", GitCommit:"105f9aeb766a38f33dcd5f632bff307be45722ab", GitTreeState:"clean", BuildDate:"2019-03-01T14:51:51Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
