### ISSUE TITLE
Connection Issue to simple Hello World App / 404

### ISSUE THREAD

**Issue by Joerg-L** [istio/istio#12404]
**Describe the bug**
I'm trying to connect to a simple http hello world (https://hub.docker.com/r/nginxdemos/hello/) application by using istio gateway and virtual service.

I have created a simple istio gateway with
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: http-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - hosts:
    - '*'
    port:
      number: 80
      name: http
      protocol: HTTP
```
after that I have create a virtual service

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-nginx-demo
  namespace: default
spec:
  gateways:
  - http-gateway
  hosts:
  - 'servername.somedomain.net'
  http:
  - route:
    - destination:
        port:
          number: 80
        host: nginx-demo.default.svc.cluster.local
```
From testing, I receive everytime a 404 from envoy.

Isito Servcie istiop-ingressgateway shows

> istio-ingressgateway   LoadBalancer   10.102.5.182   <pending>     80:31380/TCP,443:31390/TCP,31400:31400/TCP,15011:31470/TCP,8060:30282/TCP,853:30131/TCP,15030:31363/TCP,15031:32652/TCP   4d3h

The Service nginx-demo.default.svc.cluster.local was created by 

```
apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx-demo-nodeport-svc
  name: nginx-demo
  namespace: default
spec:
  clusterIP: 10.110.223.41
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30180
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-demo
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
```
When accessing the Service directly by the nodePort, connection works as expected.

**Expected behavior**
connection should be possible by using gateway and virtual service from istio.

**Steps to reproduce the bug**
- deploy https://hub.docker.com/r/nginxdemos/hello/
- create nodePort service for the deployment
- create istio gateway
- create  istio virtual service pointing to application service
- trying to connect to application

**Version**
Istio v1.0.4

**Installation**
Helm Chart

**Environment**
On-Prem on CentOs 7.x
