### ISSUE TITLE
inconsistent validation messages between istioctl and webhook

### ISSUE THREAD

**Issue by esnible** [istio/istio#12407]
Using Istio 1.1 RC 3

Testing the example from https://preliminary.istio.io/docs/reference/config/istio.authentication.v1alpha1/

```
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: productpage_mTLS_disable
  namespace: frod
spec:
  targets:
  - name: productpage
```

`istioctl validate -f` reports 
```
* cluster-scoped authentication policy name must be "default", found "productpage_mTLS_disable"
* cluster-scoped authentication policy must not have targets
```

`kubectl apply` reports 
```
The Policy "productpage_mTLS_disable" is invalid: metadata.name: Invalid value: "productpage_mTLS_disable": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

The two commands should produce similar messages.  Figure out why they don't and see if they can be brought closer together.

A separate defect for the incorrect example itself has been created at https://github.com/istio/api/issues/851

**Comment by esnible** [comment]
Here is an example that is allowed by the webhook but not `istioctl validate`:

```
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: productpage
  namespace: frod
spec:
  targets:
  - name: productpage
```

The problem is that `istioctl` strips the namespace from the .yaml before passing to ValidateAuthenticationPolicy().  The namespace is being stripped by FilterNamespace() in _vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/visitor.go_ because it believes the `info` is not Namespaced.
