### ISSUE TITLE
ingressgateway can't listen a port

### ISSUE THREAD

**Issue by yiqinguo** [istio/istio#12422]
**Describe the bug**
When I created a gateway, it contained a port of 20433. I entered the ingressgateway container and did not find the 20433 port listener.

gateway.yaml
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: sm-test
  namespace: public
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 20433
      name: http
      protocol: HTTP
    hosts:
    - "*"
```

**Expected behavior**
Can get 20433 port listener

**Steps to reproduce the bug**
Create this gateway and delete it and create it again

**Version**
1.0.5 and 1.0.6

**Installation**
helm install

**Environment**
k8s 1.11.0
