### ISSUE TITLE
Sidecar port name required by MCP but not validated

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#12435]
**Describe the bug**

I created a Sidecar config, with egress:

```yaml
    - hosts:
        - "ns/relname.ns.svc.cluster.local
```
and no port set. Traffic works. Then, I applied various different port settings to the egress, in order, and tested traffic.

Example of the full one:
```yaml
    - hosts:
        - "ns/relname.ns.svc.cluster.local"
      port:
        number: 5757
        name: something
        protocol: TCP
```

| Setup | Works? |
| -- | -- |
| No port                                 | works  |
| Port number, protocol                   | works  |
| Port number, protocol, name=""          | works  |
| Port number, protocol, name="something" | fails  |
| Port number, protocol, name=""          | fails  |
| Port number, protocol                   | fails  |
| No port                                 | works  |

I am not sure at all why the name/port is impacting the traffic at all, but that is another issue.

It is a clear bug that applying `Port number, protocol, name=""` works, but then applying the same config later fails? Could be somehow when we set name="" it sees this is empty so it keeps the name="something"

Running 1.1rc3
