### ISSUE TITLE
custom bootstrap not working 

### ISSUE THREAD

**Issue by jcetkov** [istio/istio#12436]
**Describe the bug**
The sidecart fails to start after providing custom bootstrap
```
2019-03-12T21:24:38.079070Z	info	Envoy command: [-c /etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster productpage.default --service-node sidecar~10.1.2.113~productpage-v1-7cfb78f9d4-9k5ml.default~default.svc.cluster.local --max-obj-name-len 189 --allow-unknown-fields -l warning --config-yaml '{"stats_config":{"stats_matcher":{"inclusion_list":{"patterns":["prefix":"cluster"]}}}}'
 --concurrency 2]
[2019-03-12 21:24:38.130][25][critical][main] [external/envoy/source/server/server.cc:86] error initializing configuration '/etc/istio/proxy/envoy-rev0.json': Unable to convert YAML as JSON: '{"stats_config":{"stats_matcher":{"inclusion_list":{"patterns":["prefix":"cluster"]}}}}'

Unable to convert YAML as JSON: '{"stats_config":{"stats_matcher":{"inclusion_list":{"patterns":["prefix":"cluster"]}}}}'
```

**Expected behavior**
The sidecart should start and expose the data-plane metrics in the stats
```
./envoy -c ~/opt/envoy-rev1.json --restart-epoch 0 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster productpage.default --service-node sidecar~10.1.2.113~productpage-v1-7cfb78f9d4-9k5ml.default~default.svc.cluster.local --max-obj-name-len 189 --allow-unknown-fields -l warning --config-yaml '{"stats_config":{"stats_matcher":{"inclusion_list":{"patterns":["prefix":"cluster"]}}}}'
```
runs successfully on local envoy 1.9.0 (with the `envoy-rev1.json` copied from the istio-sidecart pod prior to the bootstrap override application)

**Steps to reproduce the bug**
Following readme at https://github.com/istio/istio/tree/master/samples/custom-bootstrap 
Use the following ConfigMap
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-custom-bootstrap-config
  namespace: default
data:
  custom_bootstrap.json: >
    '{"stats_config":{"stats_matcher":{"inclusion_list":{"patterns":["prefix":"cluster"]}}}}'
```
and amend the bookinfo sample with the bootstrap annotation
```
apiVersion: v1
kind: Service
metadata:
  name: productpage
  labels:
    app: productpage
    service: productpage
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: productpage
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: productpage-v1
  labels:
    app: productpage
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: productpage
        version: v1
      annotations:
        sidecar.istio.io/bootstrapOverride: "istio-custom-bootstrap-config"
    spec:
      containers:
      - name: productpage
        image: istio/examples-bookinfo-productpage-v1:1.10.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
---
```
apply
```
kubectl apply -f <(bin/istioctl kube-inject -f samples/bookinfo/platform/kube/bookinfo.yaml)
```

**Version**
```
bin/istioctl version --remote
client version: version.BuildInfo{Version:"1.1.0-rc.3", GitRevision:"653f0050f57c7bfbc238e8a92cce1f0eb6896863", User:"root", Host:"d6e7fc1a-41c9-11e9-8dad-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-rc.2-27-g653f005"}
citadel version: version.BuildInfo{Version:"1.1.0-rc.3", GitRevision:"653f0050f57c7bfbc238e8a92cce1f0eb6896863-dirty", User:"root", Host:"d6e7fc1a-41c9-11e9-8dad-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-rc.2-27-g653f005"}
galley version: version.BuildInfo{Version:"1.1.0-rc.3", GitRevision:"653f0050f57c7bfbc238e8a92cce1f0eb6896863-dirty", User:"root", Host:"d6e7fc1a-41c9-11e9-8dad-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-rc.2-27-g653f005"}
ingressgateway version: version.BuildInfo{Version:"1.1.0-rc.3", GitRevision:"653f0050f57c7bfbc238e8a92cce1f0eb6896863", User:"root", Host:"d6e7fc1a-41c9-11e9-8dad-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-rc.2-27-g653f005"}
pilot version: version.BuildInfo{Version:"1.1.0-rc.3", GitRevision:"653f0050f57c7bfbc238e8a92cce1f0eb6896863-dirty", User:"root", Host:"d6e7fc1a-41c9-11e9-8dad-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-rc.2-27-g653f005"}
policy version: version.BuildInfo{Version:"1.1.0-rc.3", GitRevision:"653f0050f57c7bfbc238e8a92cce1f0eb6896863-dirty", User:"root", Host:"d6e7fc1a-41c9-11e9-8dad-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-rc.2-27-g653f005"}
sidecar-injector version: version.BuildInfo{Version:"1.1.0-rc.3", GitRevision:"653f0050f57c7bfbc238e8a92cce1f0eb6896863-dirty", User:"root", Host:"d6e7fc1a-41c9-11e9-8dad-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-rc.2-27-g653f005"}
telemetry version: version.BuildInfo{Version:"1.1.0-rc.3", GitRevision:"653f0050f57c7bfbc238e8a92cce1f0eb6896863-dirty", User:"root", Host:"d6e7fc1a-41c9-11e9-8dad-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-rc.2-27-g653f005"}
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
```
helm template install/kubernetes/helm/istio-init  --namespace istio-system > ./istio-init.yaml
helm template install/kubernetes/helm/istio --set global.mtls.enabled=true --name istio --namespace istio-system > ./istio.yaml
k apply -f istio-init.yaml
k apply -f istio.yaml
```

**Environment**
docker edge for mac, 2.0.3.0

**Cluster state**
empty local cluster which had earlier versions of istio installed and purged via helm

**Comment by howardjohn** [comment]
`{"stats_config":{"stats_matcher":{"inclusion_list":{"patterns":["prefix":"cluster"]}}}}` Doesn't look like valid JSON. 
`["prefix":"cluster"]` should be `[{"prefix":"cluster"}]`?

**Comment by jcetkov** [comment]
@howardjohn looks like it doesn't matter to envoy and in istio it fails with the braces too
```
2019-03-19T21:39:20.284258Z	info	Envoy command: [-c /etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster productpage.default --service-node sidecar~10.1.2.143~productpage-v1-7cfb78f9d4-2qhph.default~default.svc.cluster.local --max-obj-name-len 189 --allow-unknown-fields -l warning --config-yaml '{"stats_config":{"stats_matcher":{"inclusion_list":{"patterns":[{"prefix":"cluster"}]}}}}'
 --concurrency 2]
[2019-03-19 21:39:20.348][28][critical][main] [external/envoy/source/server/server.cc:86] error initializing configuration '/etc/istio/proxy/envoy-rev0.json': Unable to convert YAML as JSON: '{"stats_config":{"stats_matcher":{"inclusion_list":{"patterns":[{"prefix":"cluster"}]}}}}'

Unable to convert YAML as JSON: '{"stats_config":{"stats_matcher":{"inclusion_list":{"patterns":[{"prefix":"cluster"}]}}}}'
```

**Comment by howardjohn** [comment]
Sorry I didn't notice before, I thought Envoy was adding the `'`, but that is your issue.

Try:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-custom-bootstrap-config
  namespace: default
data:
  custom_bootstrap.json: >
    {"stats_config":{"stats_matcher":{"inclusion_list":{"patterns":[{"prefix":"cluster"}]}}}}

```

Notice there are no `'` around the json
