### ISSUE TITLE
Limits on istio-proxy in istio-policy

### ISSUE THREAD

**Issue by Stono** [istio/istio#12453]
Hey, 
I'm starting to look through what 1.1.x looks like for us and I noticed that istio-proxy on istio-policy now has a memory limit set to the same value as the request.

```
          resources:
+           limits:
+             cpu: 2000m
+             memory: 128Mi
            requests:
              cpu: 75m
              memory: 128Mi
```

This worries me as each istio-proxy memory usage on our cluster currently sits around 150-160meg, so this would just be getting OOM'd repeatedly if i was to roll it out.

**Comment by wailua** [comment]
Same issue here. By default pilot now uses cpu: 500m and memory 2048Mi. For most users that just costs a lot of money without any need. Or they even fail to install Istio.

You can set your own values with helm like this running from install/kubernetes/helm folder:
`helm template istio --name istio --namespace istio-system --values istio/values-istio-demo-auth.yaml --set pilot.resources.requests.cpu=200m,pilot.resources.requests.memory=256Mi | kubectl apply -f -`

I would really like to see lower default values. New users most likely won't understand how to reduce it by themself. Using "demo-auth.yaml" only reduces resource requests for mixer, not for pilot.  :(

**Comment by Stono** [comment]
I think that's a different issue.  This is about the limits for the istio-proxy sidecar which have crept into 1.1

**Comment by francoran** [comment]
Duplicate of #8553

**Comment by Stono** [comment]
*bump* feels risky rolling out with this low limit

**Comment by PiotrKlimczak** [comment]
I am new to Istio, but we are apparently affected by the problem mentioned in this issue- oom due to the too low initial limit using istio 1.1.1.
We have increased the limit to 256 for sidecar and it seems to be stable.
What I do not understand however is why memory footprint it so high, while elsewhere I can find that it should be taking like 30mb in a "normal" scenario.
To clarify we are getting almost 200mb used by sidecar right after a sidecar start.
On another issue, I have found that changes might be causing spikes in memory usage, while our case is happening without any changes.

**Comment by PiotrKlimczak** [comment]
I have managed to drop memory footprint by namespace isolation to approx 70mb.
What was surprising for me, is that the sidecar page: https://istio.io/docs/reference/config/networking/v1alpha3/sidecar/ does not mention memory impact.
I found that information here instead https://istio.io/docs/concepts/traffic-management/ on the very bottom of the page. I suppose it would be easier for people who are evaluating istio like me to provide some more info on sidecar page itself as this is the 1st place where I was looking for such details.

Besides namespace isolation, is there any other way to reduce memory further?
As per performance testing page: 

> The Istio load tests mesh consists of 1000 services and 2000 sidecars with 70,000 mesh-wide requests per second.

They have achieved above with 50mb used by sidecar.
We have ~20 services and sidecars in a namespace with no load we are still on 70mb right after start.
We have like 10 Virtual Services, 5 Destination rules, 7 Service Entries and single gateway.
Therefore I would expect the sidecar to be rather in the lower end of 30mb instead of 70mb.

Any guidance, please?

**Comment by Stono** [comment]
I find that interesting, I have 300+ services, 600 or so pods, a *lot* of configuration and our proxies sit at around 40mb.

A typical sidecar config for me looks like this:
```
  spec:
    egress:
    - hosts:
      - carzone-mmv/*
      - istio-system/zipkin.istio-system.svc.cluster.local
      - istio-system/jaeger-agent.istio-system.svc.cluster.local
      - istio-system/istio-telemetry.istio-system.svc.cluster.local
      - istio-system/istio-policy.istio-system.svc.cluster.local
      - kube-system/kube-dns.kube-system.svc.cluster.local
      - core-system/logstash.core-system.svc.cluster.local
```

We've also annotated some services with `networking.istio.io/exportTo: '.'`
