### ISSUE TITLE
Using httpHeaders in Route Rules results in an unknown field error

### ISSUE THREAD

**Issue by retroryan** [istio/istio#1246]
Using the httpHeader examples from this doc page:

https://istio.io/v-0.1/docs/concepts/traffic-management/rules-configuration.html

Gives an error  -  unknown field "httpHeaders" in istio_proxy_v1_config.MatchCondition

For an example modifying the book sample route rule `route-rule-reviews-v3.yaml` to use httpHeader like this:

```
spec:
  destination:
    name: reviews
  precedence: 2
  match:
    httpHeaders:
      Foo:
        exact: bar
  route:
  - tags:
      version: v2
````

**Comment by ijsnellf** [comment]
Which version of Istio are you using? In the current version of Istio the definition is somewhat different:
https://istio.io/docs/concepts/traffic-management/rules-configuration.html#qualify-rules-by-sourceheaders

```apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: ratings-jason
spec:
  destination:
    name: reviews
  match:
    request:
      headers:
        cookie:
          regex: "^(.*?;)?(user=jason)(;.*)?$"
```

**Comment by retroryan** [comment]
I am using the latest version of Istio.  I tried the new format - which I think should be something like:

    request:
       headers:
         user-agent:
           exact: mobile

Istio added the rule but I don't see it getting applied when I test from curl:

For example something like:

curl http://104.198.198.111/echo/universe -A mobile

And the rule is not applied.  This same type of rule used to work with Istio 0.1

**Comment by thesandlord** [comment]
@retroryan I changed my config to the new format for 0.2 and it seems to work for me. If I send the header, it goes on this route, otherwise it goes on the other route. Did you set the precedence correctly?
 https://istio.io/docs/concepts/traffic-management/rules-configuration.html#rules-have-precedence

```yaml
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: middleware-canary-route
  namespace: default
spec:
  precedence: 1
  match:
    request:
      headers:
        x-dev-user:
          exact: super-secret
  destination:
    name: middleware
  route:
  - labels:
      version: canary
```
