### ISSUE TITLE
Istio Multicluster: Liveness/Readiness Probes Fail in Remote Cluster

### ISSUE THREAD

**Issue by catherinetcai** [istio/istio#12479]
**Describe the bug**
Deployed Istio multicluster on two K8 clusters with m-TLS disabled. Liveness/readiness probes for pod workloads work fine on the control plane cluster after proxy sidecar is injected. Liveness/readiness probes for the same pod workload fail on the remote cluster after sidecar is injected.

**Expected behavior**
Liveness/readiness probes should exhibit the same behavior in both local cluster and remote cluster.

**Steps to reproduce the bug**
1. Install Istio multicluster on a cluster with m-TLS disabled
2. Deploy an app with liveness and readiness probes on the control plane cluster
3. Deploy same app with liveness and readiness probes on the remote plane and watch it fail healthchecks

Example deployment below. The container that the liveness/readiness probes check against is verified to work fine when the proxy sidecar is not injected.
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: "/"
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 6
            successThreshold: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: "/"
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 6
            failureThreshold: 3
```

**Version**
Istio Version: 1.0.2
Kubectl Version: 1.10.1

**Installation**
Deployed Istio multicluster in accordance with setup docs [here](https://istio.io/docs/setup/kubernetes/multicluster-install/).

**Environment**
Two Kubernetes clusters running AWS, spun up using Kops.

**Root Cause**
In a mutual TLS-disabled multicluster Kubernetes setup, liveness and readiness probes don't work in remote clusters. However, this behavior could not be replicated on the Kubernetes cluster running the Istio control plane.

My coworker [@marshallbrekka](https://github.com/marshallbrekka) and I verified that the remote proxy sidecar containers had connectivity to Pilot Discovery. However, we noticed when comparing the logs in the sidecar containers on a remote cluster vs the local cluster that the local cluster sidecars were properly registering liveness and readiness probes, and the remote clusters weren't.

```bash
# GOOD - On the "local" control plane - we expect to see a listener registered for 8080
[2019-03-06 21:44:39.033][15][info][upstream] external/envoy/source/server/lds_api.cc:80] lds: add/update listener '10.21.3.242_8080'

# BAD - On the "remote" cluster - where are 3333 and 9999 coming from???
[2019-03-06 22:00:16.701][10][info][upstream] external/envoy/source/common/upstream/cluster_manager_impl.cc:494] add/update cluster inbound|3333||mgmtCluster during init
[2019-03-06 22:00:16.702][10][info][upstream] external/envoy/source/common/upstream/cluster_manager_impl.cc:494] add/update cluster inbound|9999||mgmtCluster during init
```

After diving into the Istio source, we only found that 3333 and 9999 were ports returned from the [Envoy debug registry](https://github.com/istio/istio/blob/1.0.2/pilot/pkg/proxy/envoy/v2/debug.go#L324-L337).

In the Istio logs, we could see that a remote cluster registry was being picked up. However, based off of the [server bootup order](https://github.com/istio/istio/blob/1.0.2/pilot/pkg/bootstrap/server.go#L211-L219) (note that Discovery service is always init'd before Multicluster), it looks like Discovery has various registry providers that an [aggregate controller iterates through](https://github.com/istio/istio/blob/1.0.2/pilot/pkg/serviceregistry/aggregate/controller.go#L172-L192) to identify management and health check information from. Since the debug registry is always loaded before the multicluster K8 registries, and given that the debug registry will always return entries, it meant that the aggregate controller would get a hit on the debug ports and exit the loop. This means that remote cluster ports will never be returned properly, and liveness and readiness probes for the remote cluster will never work.

We added a lot more logs into [this fork](https://github.com/wearefair/istio/pull/1) and deployed it in a test cluster to confirm our suspicious.

We then added a feature flag to disable registering the debug registry to see if it would fix our liveness probes. Sure enough, it did.

It looks like this still may be an issue on [master](https://github.com/istio/istio/blob/faad288297e569342c81726b4189d52baec8747e/pilot/pkg/bootstrap/server.go#L252-L260). I'm wondering if we can get some guidance on how to proceed, as we're currently running on a fork. Is this the root cause of the problem or is there a misconfiguration on our end?
