### ISSUE TITLE
Single Invalid resource (sidecar) drops the entire collection 

### ISSUE THREAD

**Issue by costinm** [istio/istio#12474]
I noticed during testing that all Whitebox Sidecar stopped working. 
Looking further, pilot /debug/configz shows there is no Sidecar defined. 
I have quite a few Sidecar in different namespaces - and they do work fine if useMCP=false.

Only logs I've seen are:
```
2019-03-13T21:16:33.817749Z     warn    mcp     MCP: connection {addr=127.0.0.1:55020 id=3}: NACK collection=istio/networking/v1alpha3/sidecars version="4" with nonce="14" error=&rpc.Status{Code: 3,
Message: "sidecar: the egress listener with empty port should be the last listener in the list",
} inc=false
```

Pilot logs at that time seem to be gone - restarting pilot to get more info.

**Comment by costinm** [comment]
Pilot side logs, after restart:
```
2019-03-13T21:46:42.773190Z     info    mcp     New MCP sink stream created
2019-03-13T21:46:42.790263Z     error   mcp     MCP: sending NACK for nonce=6: error="rpc error: code = InvalidArgument desc = sidecar: the egress listener with empty port should be the last listener in the list"
```

**Comment by costinm** [comment]
As a secondary issue - there is no way to know which resource is bad. 

For reference, the bad config was:

```
    egress:
    - hosts:
      - ./*
      - istio-policy/*
    - hosts:
      - istio-telemetry/istio-telemetry.istio-telemetry.svc.cluster.local
      port:
        name: grpc-mixer
        number: 9091
        protocol: GRPC
    - hosts:
      - fortio110/*
      port:
        name: http-echo
        number: 8080
        protocol: HTTP
    ingress:
    - default_endpoint: 127.0.0.1:17071
      port:
        name: httplocal
        number: 7071
        protocol: HTTP
    - default_endpoint: 127.0.0.1:17070
      port:
        name: tcplocal
        number: 7070
        protocol: TCP
```
