### ISSUE TITLE
When only address is changed, mixer handler isn't refreshed

### ISSUE THREAD

**Issue by zhranklin** [istio/istio#12488]
**Describe the bug**
change the address of out-process-adapter when mixer is running doesn't work.

**Expected behavior**
mixer server change the handler address to a new one that config yaml specifies.

**Steps to reproduce the bug**
Define an out-of-process adapter like this:
```yaml
# handler for adapter mygrpcadapter
apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
  name: h1
  namespace: istio-system
spec:
  adapter: java-adapter
  connection:
    address: "java-adapter:8888"
  params:
    file_path: "out.txt"
```

start mixer server.

change `spec.connection.address` to another one. For example, from a wrong address to a right address.

the handler still doesn't works.

**Version**
mixer build from master branch

**Environment**
MacOS

**Cluster state**
run from command.

PR: #12512
