### ISSUE TITLE
Authorization template config does not recognize fields supplied in config such as "request.auth"

### ISSUE THREAD

**Issue by vinayvenkat** [istio/istio#12494]
**Describe the bug**

I'm using the authorization template to build a custom mixer adapter. When I specify the request.auth fields in the instance configuration I get the following error while running mixs:

```
019-03-14T15:49:26.486248Z     info    Awaiting for config store sync...
2019-03-14T15:49:26.486710Z     info    Starting runtime config watch...
2019-03-14T15:49:26.487050Z     info    Built new config.Snapshot: id='0'
2019-03-14T15:49:26.487363Z     info    Cleaning up handler table, with config ID:-1

2019-03-14T15:49:26.507663Z     error   config does not conform to schema of template 'authorization': unable to build message field: subject, unable to encode fieldEncoder user: source.user | request.auth.token[user] | "". unable to build primitve encoder for:user source.user | request.auth.token[user] | "". unknown attribute request.auth.token
2019-03-14T15:49:26.507702Z     error   Instance not found: instance='icheck'

2019-03-14T15:49:26.507710Z     error   No valid instances found
2019-03-14T15:49:26.507716Z     error   No valid actions found in rule
```

**Expected behavior**

I expected the fields to all be recognized and appropriately passed to my gRPC adapter which will perform the appropriate adjudication. 

**Steps to reproduce the bug**

1. Check out the latest istio code base. 
2. Build and compile mixs
3. Run mixs: 
    $GOPATH/out/linux_amd64/release/mixs server --configStoreURL=fs://$(pwd)/mixer/adapter/panpolicyenforcer/testdata/
**Version**
{{ What version of Istio and Kubernetes are you using? Use `istioctl version --remote` and `kubectl version` }}

**Installation**

Istio is checked out from the latest branch as of March 13, 2019. Its a local environment. 

**Environment**

Local environment on an Ubuntu VM. 

Sample configuration file:
```
# handler for adapter mygrpcadapter
apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
 name: h1
 namespace: istio-system
spec:
 adapter: panpolicyenforcer
 connection:
   address: "[::]:44845"
   #address: "mygrpcadapterservice:44225"
   #address: "35.184.34.117:44225"
---
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
 name: icheck
 namespace: istio-system
spec:
 template: authorization
 params:
   subject:
     user: source.user | request.auth.token[user] | ""
     properties:
       custom_token_header:  request.headers["x-custom-token"]
---

# rule to dispatch to handler h1
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
 name: r1
 namespace: istio-system
spec:
 actions:
 - handler: h1.istio-system
   instances:
   - icheck
---
```

The testdata directory has the following files:
```
attributes.yaml from $MIXER_REPO/testdata/config/attributes.yaml
template.yaml from $MIXER_REPO/template/authorization/template.yaml
panpolicyenforcer.yaml which is template for my custom grpc adapter
sample_config.yaml shown above
```

**Comment by bianpengyuan** [comment]
I don't believe request.auth.token is a valid attribute. See https://preliminary.istio.io/docs/reference/config/policy-and-telemetry/attribute-vocabulary/ for an full list of supported attributes in 1.1 release. "source.user" is also going to be deprecated with 1.1. I think what you might want are source.principal.

Also when operating with map attributes, the key value needs to be quoted, like request.auth.token["user"].

**Comment by vinayvenkat** [comment]
@bianpengyuan Thats a great point and thank you for the link. 
However, I literally pulled the config out of the authorization template's ```template_handler_service.pb.go``` file. 
I've shown the excerpt from it below:

```
Example config:

    yaml
    apiVersion: "config.istio.io/v1alpha2"
    kind: authorization
    metadata:
      name: authinfo
      namespace: istio-system
    spec:
     subject:
       user: source.user | request.auth.token[user] | ""
       groups: request.auth.token[groups]
       properties:
        iss: request.auth.token["iss"]
     action:
       namespace: destination.namespace | "default"
       service: destination.service | ""
       path: request.path | "/"
       method: request.method | "post"
       properties:
         version: destination.labels[version] | ""
   
```
Can you help me understand the discrepency and also generically speaking, where in the code is the authoritative attributes vocabulary that can be referenced and used within a specific branch. 
Thanks!
