### ISSUE TITLE
Make "hosts" in ServiceEntry optional

### ISSUE THREAD

**Issue by nrjpoddar** [istio/istio#12493]
**Describe the feature request**
The `hosts` field in ServiceEntry is a required field as stated here: https://istio.io/docs/reference/config/istio.networking.v1alpha3/#ServiceEntry

This is a possible security issue when you want to talk to external services via known stable IPs but need to add bogus hosts which can lead to maintenance/security issues long term.

**Describe alternatives you've considered**
Currently user has to write the IP in "address" field & add a bogus DNS name in host field to get around this issue.

**Additional context**
Concrete example use case is when any service in AWS wants to reach out to AWS metadata server. Currently, our ServiceEntry looks like this:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  annotations:
  name: aws-metadata
  namespace: istio-system
spec:
  addresses:
  - 169.254.169.254
  hosts:
  - xyz.local
  location: MESH_EXTERNAL
  ports:
  - name: http-metadata
    number: 80
    protocol: http
  resolution: NONE
```
As you can see the `hosts` section is not required for this configuration to work but the Galley/Pilot validation won't allow you to create ServiceEntry without the `hosts` field populated.
