### ISSUE TITLE
Use all envoy http redirect capabilities

### ISSUE THREAD

**Issue by mseravalli** [istio/istio#12518]
Currently istio redirects only on the same domain by updating the path:
https://istio.io/docs/reference/config/istio.networking.v1alpha3/#HTTPRedirect

It would be interesting to be able to use all redirect attributes provided by envoy:
https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#route-redirectaction
so that they are configurable like:
```
spec:
  hosts:
  - example.com
  http:
  - match:
    - uri:
        exact: /v1/getProductRatings
  redirect:
    host: example.org
    path: /index.html
    ...   
```
