### ISSUE TITLE
Need ability to set use_remote_address to false in ingressgateway envoy config

### ISSUE THREAD

**Issue by gdhagger** [istio/istio#12549]
**Describe the feature request**
Need to be able to tell an ingressgateway that it's not the absolute edge proxy.  Currently the value for it's envoy http connection filter 'use_remote_address' configuration is hardcoded to true.  This causes it to ignore values set for x-forwarded-for, x-forwarded-proto etc.  In turn, this breaks the behavior of the httpsRedirect flag in a gateway configuration when TLS is terminated prior to the ingressgateway.

**Describe alternatives you've considered**
I've experimented with using Lua EnvoyFilters to inspect headers and provide a workaround http->https redirect, however the filter sees the headers after they've already been mangled.  Potentially I could run yet another proxy between the loadbalancer and the ingressgateway, but this is something I really want to avoid.
As far as I can tell it's not possible to patch an automatically generated envoy filter.

**Additional context**
My exact scenario is this:
* Running in GKE
* Tried with both GKE provided Istio and Istio 1.0.6
* Want to put a Google Global HTTP(S) Load Balancer in front of my ingressgateway, rather than using the default regional TCP loadbalancer.
* Want to terminate TLS on the Google LB (whether or not I end up using TLS from the Google LB back to ingressgateway)

Related to:
* https://github.com/istio/istio/issues/7964
* https://github.com/istio/istio/issues/7607

**Comment by sangwa** [comment]
@gdhagger For the particular case of using a Google HTTPS balancer over GKE, we've been able to make it work with a bunch of workarounds:
- istio ingressgateway is deployed with Service `type: NodePort` and `externalTrafficPolicy: Local`, port 15020 (healthcheck) is also exposed to (an arbitrary) `nodePort` 31320 (similar to the default 31380 for HTTP and 31390 for HTTPS)
- a custom GCE Health Check is created for port 31320, HTTP URL `/healthz/ready`
- ports 31380 (HTTP) and 31390 (HTTPS) of ingressgateway Service are manually added to the port mapping for the GCE Instance Group of GKE's node pool where ingressgateway pods are deployed
- two Load Balancers are deployed, one for HTTP and one for HTTPS, with backends pointing to HTTP and HTTPS ports respectively of the GKE's node pool Instance Group, using the health check defined beforehand

(The drawback here is that if a node pool is recreated then the ports should be mapped again for the new instance group, but we have the whole sequence scripted in Terraform so it helps a bit.)

With this configuration a common Gateway resource with httpsRedirect for port 80 and TLS `mode: SIMPLE` termination on port 443 is working as expected.
Hope it helps.

**Comment by gdhagger** [comment]
@sangwa These workarounds shouldn't be necessary, and even with them I don't believe it actually solves the problem.
* Two loadbalancers = two IPs, which means having multiple DNS records and knowing ahead of time which one you want to request.   The whole point of the HTTP->HTTPS redirect is to be able to hit one endpoint and get redirected appropriately.

Also, from the testing I've done, even with `externalTrafficPolicy: Local` I don't believe the correct IP will be used by envoy as the 'real' IP of the client unless we are able to tune the `use_remote_address` parameter. (Also, for the record I'm using Network Endpoint Groups rather than Instance Groups to hit my pods)

For now I've solved the redirect portion by putting AWS CloudFront in front of my LB for any subdomains that need to be redirected from HTTP->HTTPS.

**Comment by sangwa** [comment]
> Two loadbalancers = two IPs

Not necessarily, we have both balancers on the same global IP, just different ports (80 vs 443).

**Comment by gdhagger** [comment]
My apologies, you're absolutely right!  For some reason I was completely
convinced I could only attach a global IP to one LB at a time.

**Comment by gdhagger** [comment]
Note for anyone who comes across this issue:

When trying to create an ingress assigned to a global IP already attached to another loadbalancer NOT managed by GKE ingress, I received the following error:
```
Error during sync: Error running load balancer syncing routine: googleapi: Error 400: Invalid value for field 'resource.IPAddress': 'IP.RED.ACT.ED'. Specified IP address is in-use and would result in a conflict., invalid
```
However, using another IP address I was able to create two GKE ingresses using the same global IP.

**Comment by MartinLG** [comment]
I have the exact same problem...
I think Istio should trust headers comming from known upper LB and avoidi to strip them.
I understand the security issues related to these headers, but this is a blocking point for us to adopt Istio.

**Comment by cagataygurturk** [comment]
Same issue here.

**Comment by nicktrav** [comment]
Can someone that works on Istio help triage this?

Maybe @rshriram? I've seen some comments of yours on some related PRs / issues, such as #13157.

**Comment by nicktrav** [comment]
@howardjohn - are there any updates on this? cc: @PiotrSikora, who was also active in the conversation over on #7679, which is related.

**Comment by howardjohn** [comment]
Yes. Someone added this and we found later it broke existing users so we set it behind a feature flag. For now it can be enabled with `--set pilot.env.PILOT_SIDECAR_USE_REMOTE_ADDRESS=true`. I think someone is working on adding a proper api for this

**Comment by rshriram** [comment]
Also, with the newer EnvoyFilter API, you can tweak a whole lot of envoy settings like this without clumsy workarounds like env vars. https://github.com/istio/api/blob/master/networking/v1alpha3/envoy_filter.proto

**Comment by nicktrav** [comment]
@rshriram - that api looks like exactly what we want. Nice. Is going to be in 1.3.x, or later?

@howardjohn - thanks! I'll check that out in the meantime.

**Comment by rshriram** [comment]
1.3.x .. its almost done

**Comment by fcantournet** [comment]
> Yes. Someone added this and we found later it broke existing users so we set it behind a feature flag. For now it can be enabled with `--set pilot.env.PILOT_SIDECAR_USE_REMOTE_ADDRESS=true`. I think someone is working on adding a proper api for this

I might be missing something but I don't see how this is applied to the ingress-gateway ?
this seems hardcoded here :
https://github.com/istio/istio/blob/f772ceea87ae58896e1eabe2cf83ebfd8c54bf6d/pilot/pkg/networking/core/v1alpha3/gateway.go#L358

**Comment by fcantournet** [comment]
@howardjohn I think we should re-open this issue : 
The issues specifically is about setting `use_remote_address` to `false` on the ingress-gateway.
Currently I have not been able to do that, except by forking pilot.

- the flag you mention does allow setting `use_remote_address` to `true` for sidecars (defaults to false) but it doesn't change anything on the ingress-gateway. On my ingress-gateway the `use_remote_address`is `true`which is the default on 1.3.x as far as I can make from the code.

- Using the EnvoyFilter below I'm able to modify the http_connection_manager but my value for `use_remote_address` is over-ridden during the `MERGE`.
I know my envoy filter is applied because the `xffNumTrustedHops` is set to `2`
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ingressgateway-settings
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
    patch:
      operation: MERGE
      value:
        typed_config:
          '@type': type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          use_remote_address: false
          xff_num_trusted_hops: 2
  workloadSelector:
    labels:
      istio: ingressgateway
```

```istioctl pc listener istio-ingressgateway-fdd56884f-52brx -o json --port 80
[
    {
        "name": "0.0.0.0_80",
        "address": {
            "socketAddress": {
                "address": "0.0.0.0",
                "portValue": 80
            }
        },
        "filterChains": [
            {
                "filters": [
                    {
                        "name": "envoy.http_connection_manager",
                        "typedConfig": {
                            "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager",
                            "statPrefix": "0.0.0.0_80",
                            "rds": {
  ...
                            },
                            "httpFilters": [
...
],
                            "useRemoteAddress": true,
                            "xffNumTrustedHops": 2,
                            "generateRequestId": true,
...
    }
]
```

**Comment by hzxuzhonghu** [comment]
Maybe related `use_remote_address` is not a bool type. it is a struct
```
type BoolValue struct {
	// The bool value.
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}
```

**Comment by cdmurph32** [comment]
You can preserve the external request id with the following EnvoyFilter.  I'm running Istio 1.3.0.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ingressgateway-settings
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
    patch:
      operation: MERGE
      value:
        typed_config:
          '@type': type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          preserve_external_request_id: true
```
Thanks to https://github.com/envoyproxy/envoy/pull/7140

**Comment by jh-sz** [comment]
@fcantournet have you got a solution for your issue for 1.3.x version, i have created a `EnvoyFilter` similar to yours, and confirmed that it works on 1.4.0, but there're intermittent 503 issues. Changing it to 1.3.5 doesn't seem to work

**Comment by bbenlazreg** [comment]
@jh-sz I am facing the same issue on 1.3.5, setting xff_num_trusted_hops works on 1.4.0 but not in 1.3.5, did you managed to make it work ?

**Comment by jh-sz** [comment]
@bbenlazreg don't think it works for 1.3.5

**Comment by ngtuna** [comment]
don't think it's solved in 1.10. I can not set `use_remote_address: false` via EnvoyFilter

**Comment by ashleywang1** [comment]
This is still true as of Istio 1.17.2. I've tried using this EnvoyFilter:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ingressgateway-settings
  namespace: istio-ingressgateway
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          use_remote_address: false
          xff_num_trusted_hops: 2
  workloadSelector:
    labels:
      istio: ingressgateway-ns
```
And saw the same thing:
```
use_remote_address: true,
...
xff_num_trusted_hops: 2,
```

Is there an existing ticket for the fact that Istio EnvoyFilters cannot set boolean values? This may end up being a proto issue as well.

**Comment by achetronic** [comment]
**This is still an issue in Istio 1.26.2**

/reopen ?

**Comment by chen-anders** [comment]
We were migrating from emissary-ingress to Istio and got hit by this unexpectedly. This is also an issue in 1.27.x and it seems like there's no great way to resolve the underlying issue.

**Comment by ramaraochavali** [comment]
@chen-anders Can you explain your dependency on that parameter - what features are you impacted by? Also do you need this for one particular gateway or all gateways?

**Comment by chen-anders** [comment]
We have our web applications behind CloudFront and an ALB. Emissary allowed us to turn use_remote_address to false since we had Cloudfront effectively being a trusted proxy. Our apps effectively trusted the XFF header written by Cloudfront. When envoy in Istio appended its own address into the XFF header, this caused our applications to interpret the envoy proxy address as the correct one. Emissary was configured to not append its address at the end. The end result on our end was some irreversible data loss due to incorrect attribution of customer data. This situation is regrettable as we've should've done more careful verification on our front instead of spot-checking the headers. 

While there is a way to work around the issue, it does require us to modify all our apps to properly parse the X-Forwarded-For header and dynamically get a list of trusted proxies in front or read the non-standard X-Envoy-External-Address header. 

Both nginx-ingress and Emissary expose options (or the equivalent) to turn use_remote_address off but I think there's no way to use the EnvoyFilter to do so because of issues with merging / parsing the boolean value. 

Given that this has been an issue for a long time, I'm convinced that most people have found ways to workaround it already.

**Comment by chen-anders** [comment]
A possible workaround is to use `skip_xff_append: true` but we're finding that envoyfilters are not consistently applied (e.g. sometimes it just disappears). 

This is our config excerpt:
```
configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          skip_xff_append: true
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.lua
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
          inlineCode: |
            function envoy_on_request(handle)
              local hdr = handle:headers()
              local orig = hdr:get("x-forwarded-proto")
              if orig then
                -- re-set it before Envoy overwrites it
                hdr:replace("x-forwarded-proto", orig)
              end
            end
```

**Comment by ramaraochavali** [comment]
Envoy filters should work consistently though

**Comment by chen-anders** [comment]
> Envoy filters should work consistently though

From my own observations:
1) Envoyfilter gets applied
2) I restart the istio deployment and the modifications I've made from envoyfilter show up consistently (as I would expect)
3) Some other app gets deployed onto the cluster (e.g. updated deployment)
4) Envoyfilter changes are no longer present until I restart the istio deployment again

We deploy our apps many times a day so it's generally not feasible to have to constantly restart the istio deployment. 

I'm running EKS 1.33 with Istio 1.27.1 on an IPv6 only cluster

**Comment by ramaraochavali** [comment]
> We deploy our apps many times a day so it's generally not feasible to have to constantly restart the istio deployment.

I do not expect Istio restart. There must be some thing else going on here. Can you share the envoy filter that is being applied to gateway?

**Comment by chen-anders** [comment]
this is the full envoyfilter being applied

```
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: preserve-xfp
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      gateway.networking.k8s.io/gateway-name: external-gateway
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: ANY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          skip_xff_append: true
  - applyTo: HTTP_FILTER
    match:
      context: ANY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.lua
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
          inlineCode: |
            function envoy_on_request(handle)
              local hdr = handle:headers()
              local orig = hdr:get("x-forwarded-proto")
              if orig then
                -- re-set it before Envoy overwrites it
                hdr:replace("x-forwarded-proto", orig)
              end
            end
```

From a quick investigation I just did on our current set of pods, we have one pod that is missing `skip_xff_append`. 

```
> kubectl exec -n istio-ingress-external external-gateway-istio-746585fdfb-5v7hm  -c istio-proxy -- \
  curl -s localhost:15000/config_dump | grep -A5 skip_xff_append
            "skip_xff_append": true,
            "upgrade_configs": [
             {
              "upgrade_type": "websocket"
             }
            ],
>  kubectl exec -n istio-ingress-external external-gateway-istio-746585fdfb-95lwz  -c istio-proxy -- \
  curl -s localhost:15000/config_dump | grep -A5 skip_xff_append
            "skip_xff_append": true,
            "upgrade_configs": [
             {
              "upgrade_type": "websocket"
             }
            ],
> kubectl exec -n istio-ingress-external external-gateway-istio-746585fdfb-k8fjb  -c istio-proxy -- \
  curl -s localhost:15000/config_dump | grep -A5 skip_xff_append
  <nothing>
```
