### ISSUE TITLE
HTTPRewrite not triggering before routing to destination

### ISSUE THREAD

**Issue by giedroyc** [istio/istio#12553]
**Describe the bug**
HTTPRewrite doesn't trigger. Request gets routed to destination correctly but without rewrite.  

**Expected behavior**
Request should have prefix replaced according to rewrite uri.

**Steps to reproduce the bug**
 
 ```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: webapp-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: webapp-virtualservice
spec:
  hosts:
    - "*"
  gateways:
    - webapp-gateway
  http:
    - match:
        - uri:
            prefix: /webapp/
      rewrite:
        uri: /
      route:
        - destination:
            host: webapp
            port:
              number: 3000
```

**Version**
istio 1.0.6
kubectl 1.13.0

**Installation**
Istio without mutual TLS authentication between sidecars
kubectl apply -f install/kubernetes/istio-demo.yaml

**Environment**
OS X, Docker Desktop 

** Logs **
istio-ingressgateway
```
[2019-03-17T17:06:04.656Z] "GET /webapp/HTTP/1.1" 304 - 0 0 19 8 "192.168.65.3" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "d938b6ec-020b-9427-82bc-44d07bedfab8" "localhost" "10.1.2.32:3000" outbound|3000||webapp.default.svc.cluster.local - 10.1.2.7:80 192.168.65.3:55414
```

webapp istio-proxy 
```
[2019-03-17T17:06:04.667Z] "GET /webapp/HTTP/1.1" 304 - 0 0 8 2 "192.168.65.3" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "d938b6ec-020b-9427-82bc-44d07bedfab8" "localhost" "127.0.0.1:3000" inbound|3000||webapp.default.svc.cluster.local - 10.1.2.32:3000 192.168.65.3:0
```
