### ISSUE TITLE
Frequent "Client.Timeout exceeded while awaiting headers" in kubectl events (1.1.0-rc.6)

### ISSUE THREAD

**Issue by jaygorrell** [istio/istio#12550]
**Describe the bug**
I deployed a very simple deployment (3 pods) with liveness/readiness probes and the `kubectl events` log had regular (every 30-60s) probe failures. I'm not positive if this happens with regular requests but I doubt that would be any different.

The default retries in 1.1 seem to take care of this, so it isn't end-user impacting but I would expect to rely on the retry for the _occasional_ timeout... not something happening every minute or so for every pod.

**Expected behavior**
Liveness probe requests should not regularly get failures. I definitely did not have this problem on an environment of this small size in ~1.0.3.

**Steps to reproduce the bug**
Deploy the following modified productpage deployment (just a simple well-known starting point):
```
apiVersion: v1
kind: Service
metadata:
  name: productpage
  labels:
    app: productpage
    service: productpage
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: productpage
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: productpage-v1
  labels:
    app: productpage
    version: v1
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: productpage
        version: v1
    spec:
      containers:
      - name: productpage
        image: istio/examples-bookinfo-productpage-v1:1.10.1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "0"
            memory: "0"
        ports:
        - containerPort: 9080
        livenessProbe: &probe
          httpGet:
            path: /productpage
            port: 9080
          initialDelaySeconds: 15
        readinessProbe:
          <<: *probe
```

Then monitor `kubectl events` and see that each of the 3 pods regularly has `net/http: request canceled (Client.Timeout exceeded while awaiting headers)` messages.

**Version**
Istio: 1.1.0-rc.6
Kubernetes: 1.11.7

**Installation**
`helm template` with only these custom values:
```
grafana:
  enabled: true
pilot:
  autoscaleMin: 3
  autoscaleMax: 5
```

**Environment**
AWS Kops

Here's an example from the deployment that was started while I typed this issue:
![image](https://user-images.githubusercontent.com/12174604/54484428-f3617980-483c-11e9-84e9-9bd5bb25c5b7.png)
