### ISSUE TITLE
RDS is stale only for a specific deployment blocking it from outbound traffic

### ISSUE THREAD

**Issue by iftachsc** [istio/istio#12599]
**Describe the bug**
we have 60 microservice.
after a recent update (not sure its related) only for this service we get stale (istioctl proxy-status) on its RDS column.
if we delete the pods of this service the new pods still gets staled over RDS which means its not an issue with pilot connectivity.
we currently have 224 injected pods in the mesh (including istio-system)

![image](https://user-images.githubusercontent.com/28829551/54611485-b4f7d480-4a5f-11e9-852e-a8078f3372e1.png)

**Expected behavior**
it would be synced just as the others and itself as untill now.

**Steps to reproduce the bug**
no idea

**Version**
istio 1.0.6
kubernetes 1.11.7gke3

**Installation**
via helm chart

**Environment**
gcp

**Comment by iftachsc** [comment]
update: more pods start to have this now. i guess its related to the fact our environments grows today - i.e. we have more injected pods coming up. 

only restarting pilots help but this is really bothering. 

i cant see antyhing special in pilots logs.
pilots (3 replicas) are not even close to their resource requests (no limits set). 
it seems to me that manually triggering pilot rolling update so its pod would restart every few days is the only solution. 
any ideas how can i mitigate that?

**Comment by iftachsc** [comment]
update: after restarting the pilots and problem is fixed - synced pods that i delete are replaced by new pods that are again stale on RDS (even pilots are fresh now)

**Comment by iftachsc** [comment]
update: i see in logs of sidecars of these pods the following: 
config for type.googleapis.com/envoy.api.v2.RouteConfiguration rejected: Only unique values for domains are permitted. Duplicate entry of domain 10.190.24.204

does it mean that they cannot update their routes for some reason?

**Comment by iftachsc** [comment]
update: ok this wasthe reason for this stale porxies. we had a service entry that had both hosts and addresses that resolve to the same ips. i would just like to get a confirmation my behaviour is expected when this situation is set. because for me its odd that one mistake in a service entry can shutdown all traffic in the mesh (assuming stale porxy cannot access anything, as we experienced)

**Comment by esnible** [comment]
@iftachsc Can you attach the SE that caused trouble?  It would help with writing accurate test cases for the problem.

**Comment by iftachsc** [comment]
I won’t reveal hosts and ips so it doesn’t make sense to. It’s really simple. A minimal SE with ips and hosts  that resolve to these very ips , with resolution:dns . I think without resolution it also removes the error.

**Comment by esnible** [comment]
The symptoms you describe are very similar to https://github.com/istio/istio/issues/9504 .  That problem is Listeners going Stale when there are duplicates.  This problem is Routes going stale.

I tried to recreate your problem with Istio 1.1 using variations of the SEs below and couldn't make STALE appear.  It is possible that the problem is fixed.  It is also possible that I misunderstood your description of the SE.

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: issue12599
spec:
  hosts:
  - example.com
  addresses:
  - "93.184.216.34"
  - "93.184.216.34"
  ports:
  - name: tcp
    number: 22
    protocol: tcp
  - name: http
    number: 80
    protocol: tcp
  location: MESH_EXTERNAL
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: issue12599b
spec:
  hosts:
  - www.example.com
  addresses:
  - "93.184.216.34"
  - "93.184.216.34"
  ports:
  - name: tcp
    number: 22
    protocol: tcp
  - name: http
    number: 80
    protocol: tcp
  location: MESH_EXTERNAL
  resolution: DNS
```
