### ISSUE TITLE
Virtual service  binding to wrong gateways

### ISSUE THREAD

**Issue by mbanikazemi** [istio/istio#12603]
**Describe the bug**
For a given gateway that does not have any VS associated with it, it gets routes from a VS defined for a different gateway.

**Expected behavior**
No such binding of VS to a gateway for which the VS was not defined

**Steps to reproduce the bug**
1- create two gateways:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: sm-test
  namespace: default
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 99
      name: http-99
      protocol: HTTP
    hosts:
    - "*"
```

and

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http-80
      number: 80
      protocol: HTTP
```

2- define a VS:

```
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: vs-test
  namespace: default
kind: VirtualService
spec:
  gateways:
  - httpbin-gateway
  hosts:
  - '*'
  http:
  - match: null
    route:
    - destination:
        host: httpbin
        port:
          number: 8000
```

Check the envoy config on Ingress gateway and notice routes http.80 and http.99.

**Version**
Release-1.1 RC6
