### ISSUE TITLE
STRICT_DNS Empty endpoints for each locality

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#12610]
**Describe the bug**
From config_dump:
```json
      "load_assignment": {
       "cluster_name": "outbound|80||google.com",
       "endpoints": [
        {},
        {},
        {
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "172.217.6.78",
              "port_value": 80
             }
            }
           },
           "load_balancing_weight": 1
          },
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "identity-b",
              "port_value": 80
             }
            }
           },
           "load_balancing_weight": 1
          },
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "identity-c",
              "port_value": 80
             }
            }
           },
           "load_balancing_weight": 1
          }
         ]
        },
        {
         "locality": {
          "region": "us-central1",
          "zone": "us-central1-a"
         },
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "identity-a",
              "port_value": 80
             }
            }
           },
           "load_balancing_weight": 1
          }
         ]
        }
       ]
      }
     },
```

There are two empty `{}` endpoints. With each locality endpoint I add, another one is created.

This seems to have no impact so is low priority.

Occurs on 1.1

Config to generate:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google-ext
spec:
  hosts:
  - "google.com"
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL
  endpoints:
  - address: identity-a
    locality: us-central1/us-central1-a
  - address: identity-b
  - address: identity-c
```
