### ISSUE TITLE
Egress: VirtualService with domain name not working.

### ISSUE THREAD

**Issue by nagapavan** [istio/istio#12618]
**Describe the bug**
I have NodeJS client which uploads files to AWS S3. If I enable Istio on the K8S cluster, service is not able to reach `sts.amazonaws.com` or `*.s3.amazonaws.com`

Config used is as follows:
```yaml
# Service Entry for HTTPS
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: amazonaws
spec:
  hosts:
  - "sts.amazonaws.com"
  - "s3.amazonaws.com"
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
---
# Virtual Service Entry for HTTPS
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: amazonaws
spec:
  hosts:
  - "sts.amazonaws.com"
  - "amazonaws.com"
  gateways:
  - egressgateway
  - mesh
  tls:
  - match:
    - port: 443
      sniHosts:
      - "sts.amazonaws.com"
    route:
    - destination:
        host: "sts.amazonaws.com"
      weight: 100
  - match:
    - port: 443
      sniHosts:
      - "amazonaws.com"
    route:
    - destination:
        host: "amazonaws.com"
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: amazonaws
spec:
  host: "*.amazonaws.com"
  trafficPolicy:
    tls:
      mode: DISABLE
---
```
I am getting ECONNRESET whenever the connection request is sent. If I specifically add my AWS Bucket URL `<bucker_name_here>.s3.amazonaws.com`, then only the connection is established,

**Expected behavior**
Istio Egress to allow traffic without any error.

**Steps to reproduce the bug**
Config shared above

**Version**
{{ What version of Istio and Kubernetes are you using? Use `istioctl version --remote` and `kubectl version` }}
Kubectl : 1.9.3
Istioctl : 1.0.6

**Installation**
{{ Please describe how Istio was installed }}
Istio installation done through `curl` request on setup page, followed by CRDs and scaffolding config

**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}
Baremetal K8S cluster with CentOS nodes

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by prima101112** [comment]
if you just want to all traffict to amazon go to amazon i think you dont need virtualservice and destinationrule. and the resolution is none

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-redirect
spec:
  hosts:
  - "amazonaws.com"
  - "*.amazonaws.com"
  location: MESH_EXTERNAL
  ports:
  - number: 443
     name: https
     protocol: TLS
  - number: 80
     name: http
     protocol: HTTP
  resolution: NONE
```
