### ISSUE TITLE
Split-Horizon EDS multicluster does not send the ingress gateway of the local cluster to the remote cluster as an endpoint

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#12623]
The pilot does not send the ingress gateway of the local cluster to a remote cluster as an endpoint, so connectivity from the remote cluster into the local one is currently not possible.

**Comment by vadimeisenbergibm** [comment]
cc @costinm

**Comment by vadimeisenbergibm** [comment]
The code of [EndpointsByNetworkFilter](https://github.com/istio/istio/blob/116a6a6ed2a1dfbb7444e4fa8f13052f7bb00a0e/pilot/pkg/proxy/envoy/v2/ep_filters.go#L34) does not send the local gateway to the remote sidecars.

Proposed solution: define the local network as "default". If the sidecar does not specify its network, treat it as "default". If the endpoint doesn't have network metadata, treat it as "default". Allow defining "default" network in the MeshNetworks with its gateways to send to remote sidecars.

**Comment by mikebryant** [comment]
We were able to solve this without any code changes - though a docs update would be good.

This is our config:
```
  meshNetworks:
    "":
      gateways:
      - address: 10.1.1.1
        port: 443
    network2:
      endpoints:
      - fromRegistry: n2
      gateways:
      - address: 10.2.2.2
        port: 443
```

It turned out to be sufficient to add a gateway config for `""` - as that's already the hardcoded default

**Comment by dwradcliffe** [comment]
Did you set the meta network name on the remote cluster?

**Comment by mikebryant** [comment]
Yes, we have. Though since we're also explicitly setting fromRegistry I think it might be redundant? Eh, followed the guide and it worked :)

**Comment by vadimeisenbergibm** [comment]
@mikebryant I see, but it is a hack. I propose to use some dedicated name instead of `""`, e.g. `default`.

**Comment by mikebryant** [comment]
Yeah, I'm not opposed to some special name. Thought it would be helpful to share how to make it work right now though. (as we actually need this to work, so we're ploughing ahead)

**Comment by vadimeisenbergibm** [comment]
@mikebryant yes, it helps, thank you for sharing!

**Comment by romo8D** [comment]
> We were able to solve this without any code changes - though a docs update would be good.
> 
> This is our config:
> 
> ```
>   meshNetworks:
>     "":
>       gateways:
>       - address: 10.1.1.1
>         port: 443
>     network2:
>       endpoints:
>       - fromRegistry: n2
>       gateways:
>       - address: 10.2.2.2
>         port: 443
> ```
> It turned out to be sufficient to add a gateway config for `""` - as that's already the hardcoded default

Thanks. So if we create a service end point in cluster1, it will never show up in cluster2, whether is a cluster  having control plane installed or not, right?

I checked the endpoints of 2 clusters, they only have end points in their local service endpoints.

**Comment by romo8D** [comment]
> We were able to solve this without any code changes - though a docs update would be good.
> 
> This is our config:
> 
> ```
>   meshNetworks:
>     "":
>       gateways:
>       - address: 10.1.1.1
>         port: 443
>     network2:
>       endpoints:
>       - fromRegistry: n2
>       gateways:
>       - address: 10.2.2.2
>         port: 443
> ```
> It turned out to be sufficient to add a gateway config for `""` - as that's already the hardcoded default

So the - address: 10.1.1.1 is the local cluster  gateway ip addr and - address: 10.2.2.2 is the remote  cluster gateway ip addr, right?

**Comment by mikebryant** [comment]
Yes, that's right on the ip addresses.

With this config we have the `istioctl proxy-config endpoints` command showing both local endpoints and the other cluster gateway endpoint (if the same services has endpoints in the other cluster)

**Comment by romo8D** [comment]
> Yes, that's right on the ip addresses.
> 
> With this config we have the `istioctl proxy-config endpoints` command showing both local endpoints and the other cluster gateway endpoint (if the same services has endpoints in the other cluster)

I'm using istioctl 1.1.3 the latest version and run "istioctl proxy-config endpoints sleep-88ddbcfdd-bhstf.sample --context=$CTX_CLUSTER1 | grep helloworld" following the instruction@https://istio.io/docs/examples/multicluster/split-horizon-eds/#split-horizon-eds-in-action

And I got
<local cluster ip>:5000       HEALTHY     outbound|5000||helloworld.sample.svc.cluster.local
<remote cluster gateway ip>:443          HEALTHY     outbound|5000||helloworld.sample.svc.cluster.local

Then I ran $ kubectl exec --context=$CTX_CLUSTER1 -it -n sample -c sleep $(kubectl get pod --context=$CTX_CLUSTER1 -n sample -l app=sleep -o jsonpath='{.items[0].metadata.name}') -- curl helloworld.sample:5000/hello

And it always returned the service deployed in the local cluster services.  Any idea?

**Comment by hzxuzhonghu** [comment]
```

  meshNetworks:
    network1:  #This name can be specified，when installing primary cluster  --set global.network="network1" 
      endpoints:
      - fromRegistry: kubernetes  #This is fixed cluster registry for primary cluster
      gateways:                    
      - address: 10.1.1.1
        port: 443
    network2:
      endpoints:
      - fromRegistry: n2
      gateways:
      - address: 10.2.2.2
        port: 443

```

Can use the above config. Btw , the official doc for cluster-aware ,multicluster install guide is not complete.
