### ISSUE TITLE
IP addresses in mixer logs are not readable

### ISSUE THREAD

**Issue by dwradcliffe** [istio/istio#12634]
**Describe the bug**
IP addresses in mixer logs are not readable. (Not Envoy logs)

Examples:
`sourceIp:	 CjQpPQ==`
`destinationIp:	 AAAAAAAAAAAAAP//CjRD8w==`

Istio config resources are defaults as provided by helm charts.
For example this is still present:

```
apiVersion: config.istio.io/v1alpha2
kind: logentry
metadata:
  name: accesslog
  namespace: istio-system
spec:
  variables:
    sourceIp: source.ip | ip("0.0.0.0")
    destinationIp: destination.ip | ip("0.0.0.0")
    <...>
```

**Expected behavior**
I expected to see the string representation of the IP Address.

**Steps to reproduce the bug**
Run any workloads on the mesh. View the mixer access logs.

**Version**
Istio `1.1.0`
Kubernetes `v1.11.6-gke.2`

**Installation**
helm template + (some processing of yaml) + kubectl apply

**Environment**
GKE
