### ISSUE TITLE
gRPC service call in istio behave inconsistent

### ISSUE THREAD

**Issue by pandey-adarsh147** [istio/istio#12648]
**Describe the bug**
Sometime happening
Service to service call in istio mesh giving Unimplemented, at the same time ingress call is working fine. After sometime, (may be due to restart target service) its working fine. This happening vice-versa as well (service to service call working fine but ingress giving Unimplemented exception).

**Expected behavior**
It should work at all cases all time
**Steps to reproduce the bug**
Inconsistent

**Version**
istio 1.04
Kubernetes v1.12 & v1.13

**Installation**
Helm

**Environment**
GKE and Baremetal(RKE)

**Comment by nmnellis** [comment]
Im seeing a similar result, i can call my application service directly via grpc and it works but through the ingressgateway im getting Unimplemented and i do not see the request making it to the service. I do not see any logs in my applications istio-proxy logs when calling through the ingressgateway

Ingress gateway log
```
[2019-03-22T14:02:48.079Z] "POST /summaft.infrastructure.v1.SFTService/GetClientHTTP/2" 200 - 0 0 0 - "10.60.70.1" "grpc-node/1.17.0 grpc-c/7.0.0 (osx; chttp2; gizmo)" "ace2ff26-b6dc-4d0d-a5d0-fcdbd2f6b9ea" "10.60.0.30:81" "-" - - 10.60.70.54:80 10.60.70.1:54169
```

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sft
  namespace: sft
spec:
  hosts:
  - '*'
  gateways:
  - istio-autogenerated-k8s-ingress
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8064
        host: sft
```
