### ISSUE TITLE
Galley valid virtualservice(and other crds) error when the host contain port

### ISSUE THREAD

**Issue by wansuiye** [istio/istio#12654]
**Describe the bug**
{{ Succinctly describe the bug }}
As mentioned in [#7242](https://github.com/istio/istio/issues/7242) and #6469, the galley return error when create a virtualservice that has a host  with port.

**Expected behavior**
{{ What did you expect to happen? }}

When port 80 is not opened, the ingressgateway is mapped to node port such as 3xx80, in HTTP 1.0, the host header of client request contained port as default. 
If the virtualservice's host can not contain port 3xx80, the request can not be matched, which results in a 404 error.
before close the galley can solve the problem, which can create the virtualservice successfully, but the galley is much more important now such as mcp. so i think we should support it

**Steps to reproduce the bug**
{{ Minimal steps to reproduce the behavior }}

**Version**
{{ What version of Istio and Kubernetes are you using? Use `istioctl version --remote` and `kubectl version` }}

**Installation**
{{ Please describe how Istio was installed }}
1.1/1.0.x/0.x
**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by linsun** [comment]
could you kindly produce sample yaml file(s) that can produce this?

**Comment by wansuiye** [comment]
@linsun 
the ingressgateway service use nodeport which is 3xx80, yaml such as:
```
apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  annotations:
  labels:
    chart: gateways
    heritage: Tiller
    release: istio
    app: istio-ingressgateway
    istio: ingressgateway
spec:
  type: NodePort
  selector:
    release: istio
    app: istio-ingressgateway
    istio: ingressgateway
  ports:
    -
      name: http2
      nodePort: 31180
      port: 80
      targetPort: 80
```
and the internal service is foo, the serviceport is 8080:
```
apiVersion: v1
kind: Service
metadata:
  name: foo
  namespace: demo
  annotations:
  labels:
    app: foo
spec:
  type: ClusterIP
  selector:
    app: foo
  ports:
    -
      name: http
      port: 8080
      targetPort: 8080
```
the vs yaml:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: foo.xxx.io
spec:
  hosts:
  - "foo.xxx.io:31180"
  - foo.xxx.io
  gateways:
  - istio-gateway
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: foo.demo.svc.cluster.local
        subset: data
        port:
          number: 8080
```
if request the foo.xxx.io:30080/health, have to set the host of the vs to "foo.xxx.io:30080", however the galley return error.

**Comment by linsun** [comment]
sorry for the delay on this.   i don't think port number is allowed in the hosts field, see https://github.com/istio/api/blob/master/networking/v1alpha3/virtual_service.proto#L137

You don't need to specify port number in your hosts in your VS.  Can you remove that line `- "foo.xxx.io:31180"` and retry?

**Comment by linsun** [comment]
BTW, I don't see your gateway resource, you need to create a gateway resource which should include the port 31180 in there.

**Comment by linsun** [comment]
Closing this because I believe it is a config error trying to do things we don't allow and we already gave an error msg.

**Comment by klusht** [comment]
Although this topic is closed I believe this is still an issue of ingressgateway host matching 
Have a local testing cluster and configured hosts file with 
> grafana.cluster 192.168.0.100

Doing the simple curl will generate the following ( browsers will add the same Host value )
```
curl -I http://grafana.cluster:30473 -vvv

*   Trying 192.168.0.100:30473...
* TCP_NODELAY set
* Connected to grafana.cluster (192.168.0.100) port 30473 (#0)
 HEAD / HTTP/1.1
 >Host: grafana.cluster:30473     <<<<------- host header has the port
 >User-Agent: curl/7.65.3
 >Accept: */


ingressgateway logs shows 
"HEAD / HTTP/1.1" 404 NR "-" "-" 0 0 0 - "192.168.0.100" "curl/7.65.3" "1ac63d81-4898-9eea-bb06-5df4d75de44d" "grafana.cluster:30473" "-" - - 10.200.105.78:80 192.168.0.100:38536 -
```

Overriding the Host header will propagate just fine 
```
curl -I -HHost:grafana.cluster http://grafana.cluster:30473 -vvv

*   Trying 192.168.0.100:30473...
* TCP_NODELAY set
* Connected to grafana.cluster (192.168.0.100) port 30473 (#0)
> HEAD / HTTP/1.1
> Host:grafana.cluster          <<<<----- correct host header as defined in VirtualService
> User-Agent: curl/7.65.3
> Accept: */*

ingressgateway logs
"HEAD / HTTP/1.1" 200 - "-" "-" 0 0 4 3 "192.168.0.100" "curl/7.65.3" "13ffcfb2-f381-9719-ad61-1f94cb3d593e" "grafana.cluster" "10.200.102.193:3000" outbound|3000||grafana.monitoring.svc.cluster.local - 10.200.105.78:80 192.168.0.100:30237 - -
```

Adding matching rule did NOT work either
```
  hosts:
    - "grafana.cluster"
  http:
    - match:
      - port: 30473
        uri:
          prefix: /
```

As expected if hosts is set to "*"  the host pattern matching is not executed and it works as expected/ but you will need to use prefix path, which requires changing the configuration of the Root path in your app. 

The only viable solution for this is to have a reverse proxy server that will proxy pass the request and provide the right "Host" header with no port number ( ingress ? )
