### ISSUE TITLE
TestIngressGateway503DuringRuleChange is flaky

### ISSUE THREAD

**Issue by ozevren** [istio/istio#12678]
https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/12676/istio_auth_sds_e2e/3283

**Comment by ozevren** [comment]
@andraxylia can you triage and redirect?

**Comment by esnible** [comment]
I looked into this on https://github.com/istio/istio/issues/11929 and even created https://github.com/istio/istio/pull/12207 to look into it.  See also https://github.com/istio/istio/issues/11700

What I discovered is that the test got 451 200s, then a 503, then 48 200s.

I discuss my findings at https://github.com/istio/istio/issues/11700#issuecomment-468976840 https://github.com/istio/istio/issues/11700#issuecomment-469311940 https://github.com/istio/istio/issues/11700#issuecomment-469375832

I suspect the 503s happen because of a gap between Envoy receiving “gRPC config for type.googleapis.com/envoy.api.v2.Cluster accepted with 82 resources” and receiving “gRPC config for type.googleapis.com/envoy.api.v2.ClusterLoadAssignment” with the IP and weight of the clusters.  I lack the Envoy knowledge to tell if this theory is correct or to fix it.

**Comment by kyessenov** [comment]
Flakes consistently for me: https://circleci.com/gh/istio/istio/361809?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link, as an example.

**Comment by esnible** [comment]
A few weeks ago I ran `while time go test -run TestIngressGateway503DuringRuleChange -namespace=istio-system -skip_setup=true -pilot_hub=istio -pilot_tag=1.1.0-rc.0 -auth_enable=true; do date; done` for four hours against IBM Kubernetes Service and was not able to reproduce this problem even once.

I have been testing today with similar rules against Bookinfo with `/usr/bin/fortio -- load -qps 100 -t 60s -loglevel Warning http://reviews:9080/reviews/0` which has 20 times the traffic.  I could not reproduce the problem if I used a different kubectl apply to change the DR and VS.

I was able to get a lot of 503s if I applied the rule change in a single `kubectl apply`.  To recreate:

SETUP

```
cat <<EOF > /tmp/12-12.yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: destination-rule-reviews
spec:
  host: reviews
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
    - reviews
  http:
  - route:
    - destination:
        host: reviews
        subset: v1
      weight: 50
    - destination:
        host: reviews
        subset: v2
      weight: 50
EOF

cat <<EOF > /tmp/1234-34-34.yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: destination-rule-reviews
spec:
  host: reviews
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
    - name: v3
      labels:
        version: v1
    - name: v4
      labels:
        version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
    - reviews
  http:
  - route:
    - destination:
        host: reviews
        subset: v3
      weight: 50
    - destination:
        host: reviews
        subset: v4
      weight: 50
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: destination-rule-reviews
spec:
  host: reviews
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
    - name: v3
      labels:
        version: v1
    - name: v4
      labels:
        version: v2
EOF

kubectl apply -f samples/httpbin/sample-client/fortio-deploy.yaml
```

TEST

```
kubectl apply -f /tmp/12-12.yaml
kubectl exec $(kubectl get pod --selector app=fortio --output jsonpath='{.items[0].metadata.name}') -c fortio -- /usr/bin/fortio load -qps 2000 -t 6s -loglevel Error http://reviews:9080/reviews/0 &
sleep 5
kubectl apply -f /tmp/1234-34-34.yaml
```
