### ISSUE TITLE
Node agent does not refresh certificates before expiry if expiry is less than requested TTL

### ISSUE THREAD

**Issue by maxlambrecht** [istio/istio#12674]
Istio uses always a static configuration parameter to determine if the secret cache should be refreshed and doesn't take into account the expiration time (NotAfter) of the cached certificate: 

https://github.com/istio/istio/blob/2d951d1bd6efcf881ca5692c5c5b7dfd28089a0e/security/pkg/nodeagent/cache/secretcache.go#L547

If the node requests certificates from an external CA server and this server signs certs with a shorter validity period than the period configured in Istio, there will problems with expired certs.

**Comment by myidpt** [comment]
@quanjielin Please take a look, thanks!

**Comment by quanjielin** [comment]
@maxlambrecht 

Today we don't parse certificate but rely on operator to config ```SecretTTL``` (and other params) to control cert rotation. For example, you could put below params in nodeagent yaml if your cert has a short time in 10m (not recommend in production). 


```
-env:
...
- name: SECRET_GRACE_DURATION
  value: "2m"
- name: SECRET_JOB_RUN_INTERVAL
  value: "3m" 
- name: SECRET_TTL
  value: "10m"
```
