### ISSUE TITLE
Circuit Breaking does not take effect for grpc service

### ISSUE THREAD

**Issue by yiqinguo** [istio/istio#12695]
**Describe the bug**
I start a grpc server and client and set up a circuit breaker,the circuit breaker did not take effect.
Client sends one hundred requests per second.
**Version**
1.0.6

**Installation**
helm install

**Cluster state**
On kubernetes 1.11.0

**client.yaml**
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: helloworld-client
  namespace: yqguo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: helloworld-client
    spec:
      containers:
      - name: helloworld-client
        image: myrepo/library/helloworld-client
        env:
        - name: ADDRESS
          value: "hellworld-server:50051"
```
**server.yaml**
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: helloworld-server
  namespace: yqguo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld-server
    spec:
      containers:
      - name: helloworld-server
        image: myrepo/library/helloworld-server
        ports:
        - containerPort: 50051
---
kind: Service
apiVersion: v1
metadata:
  name: hellworld-server
  namespace: yqguo
spec:
  selector:
    app: helloworld-server
  ports:
    - protocol: TCP
      name: grpc
      port: 50051
      targetPort: 50051
```
**destinationrule.yaml**
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: helloworld-server
  namespace: yqguo
spec:
  host: hellworld-server
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 1
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
        http2MaxRequests: 1
    outlierDetection:
      consecutiveErrors: 1
      interval: 1s
      baseEjectionTime: 3m
      maxEjectionPercent: 100
```
