### ISSUE TITLE
Galley Error: unknown flag: --meshConfigFile also please change istio.io helm repo to stable

### ISSUE THREAD

**Issue by kylebevans** [istio/istio#12697]
**Describe the bug**
Galley is stuck in CrashLoopBackoff due to this error:
```
Error: unknown flag: --meshConfigFile
```

**Expected behavior**
galley to run without error

**Steps to reproduce the bug**
Install istio from the helm repo at istio.io/istio

**Version**
The Istio version is 1.1.0, but the Deployments are set to load containers from master-latest-daily.  Here is the snippet from the galley Deployment:

```
      containers:
      - command:
        - /usr/local/bin/galley
        - --meshConfigFile=/etc/mesh-config/mesh
        - --livenessProbeInterval=1s
        - --livenessProbePath=/healthliveness
        - --readinessProbePath=/healthready
        - --readinessProbeInterval=1s
        - --insecure=true
        - --validation-webhook-config-file
        - /etc/config/validatingwebhookconfiguration.yaml
        - --monitoringPort=15014
        image: gcr.io/istio-release/galley:master-latest-daily
```

**Installation**
From the helm repo at istio.io/istio

**Environment**
AWS EKS

**Notes**
This is a bug, but I would also like to morph it into a feature request.  Could the helm repo at istio.io be switched to a stable version of Istio instead of loading containers from master-latest-daily?
