### ISSUE TITLE
Does workloadSelector for Sidecar only work with `app`

### ISSUE THREAD

**Issue by Stono** [istio/istio#12759]
Hey, 
The docs say:
```
> | REQUIRED: One or more labels that indicate a specific set of pods/VMs on which this sidecar configuration should be applied. The scope of label search is restricted to the configuration namespace in which the the resource is present.
-- | --
```

However, it doesn't seem to be working for me, when I use `sidecar: cron`?

Pod:
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    checksum/configmap: 64a8c5b9d68f2c515e7d4acbcd51698d6b2b55c4046f7a985b1e4595ea6fed2a
    checksum/secret: 0df211bcaeda617fe7ab3a72e6975c14033f426f8a3099cc884eb6caf819aa57
    cni.projectcalico.org/podIP: 10.198.5.4/32
    prometheus.io/port-jmx: "9090"
    prometheus.io/scrape-jmx: "true"
    seccomp.security.alpha.kubernetes.io/pod: docker/default
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/status: '{"version":"48e5ed746cc1a64e9550ed985adfaf4fdb3fe5ff16a9c8ff0c6c8993918cda76","initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["istio-envoy","istio-certs"],"imagePullSecrets":null}'
  creationTimestamp: "2019-03-25T18:06:30Z"
  generateName: cache-warm-
  labels:
    controller-uid: b74fe048-4f28-11e9-89a9-42010aa40208
    cron: cache-warm
    job-name: cache-warm
    sidecar: cron
```

And my sidecar resource:
```
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  creationTimestamp: "2019-03-25T17:45:58Z"
  generation: 1
  labels:
    app: forecourt-service
    group: delivery-platform
    heritage: Tiller
    release: forecourt-service
  name: forecourt-service-cron
  namespace: forecourt-service
  resourceVersion: "133400340"
  selfLink: /apis/networking.istio.io/v1alpha3/namespaces/forecourt-service/sidecars/forecourt-service-cron
  uid: d93b968e-4f25-11e9-89a9-42010aa40208
spec:
  egress:
  - hosts:
    - forecourt-service/*
    - kafka/*
    - location-service/*
    - portal-advert-text/*
    - vehicle-metric-service/*
    - istio-system/*
    - kube-system/kube-dns
    - core-system/logstash
  workloadSelector:
    labels:
      sidecar: cron
```

But the sidecar gets populated with clusters that are not in those selectors:
```
❯ istioctl proxy-config endpoint cache-warm-z8fs6
ENDPOINT                STATUS      CLUSTER
10.192.37.210:9411      HEALTHY     zipkin
10.192.46.151:15011     HEALTHY     xds-grpc
10.193.32.7:5473        HEALTHY     outbound|5473||calico-typha.kube-system.svc.cluster.local
10.193.32.75:5473       HEALTHY     outbound|5473||calico-typha.kube-system.svc.cluster.local
10.198.0.30:80          HEALTHY     outbound|80||solr-1.vds-solr.svc.cluster.local
10.198.0.30:80          HEALTHY     outbound|80||solr.vds-solr.svc.cluster.local
10.198.1.18:80          HEALTHY     outbound|80||solr-2.search-solr.svc.cluster.local
10.198.1.18:80          HEALTHY     outbound|80||solr.search-solr.svc.cluster.local
10.198.10.100:8080      HEALTHY     outbound|80||app.rate-of-sale-model-service.svc.cluster.local
10.198.10.100:9080      HEALTHY     outbound|9080||admin.rate-of-sale-model-service.svc.cluster.local
10.198.10.104:8080      HEALTHY     outbound|80||app.sauron-web-mobile.svc.cluster.local
10.198.10.104:8081      HEALTHY     outbound|9080||admin.sauron-web-mobile.svc.cluster.local
10.198.10.105:8080      HEALTHY     outbound|80||app.private-online-ads-ws.svc.cluster.local
10.198.10.105:9080      HEALTHY     outbound|9080||admin.private-online-ads-ws.svc.cluster.local
10.198.10.106:8080      HEALTHY     outbound|80||app.retailer-tools-portal.svc.cluster.local
10.198.10.71:3838       HEALTHY     outbound|80||app.business-partner-report.svc.cluster.local
10.198.10.72:8088       HEALTHY     outbound|80||app.autotrader-api-docs.svc.cluster.local
10.198.10.72:9080       HEALTHY     outbound|9080||admin.autotrader-api-docs.svc.cluster.local
...
```

So it doesn't appear to be applying.
