### ISSUE TITLE
What is the recommended way to define an Instance and handler?

### ISSUE THREAD

**Issue by idouba** [istio/istio#12780]
[Instance](https://istio.io/docs/reference/config/policy-and-telemetry/istio.policy.v1beta1/#Instance)  introduce a way to define  instance used in mixer. like this
```
apiVersion: config.istio.io/v1alpha2
kind: instance
metadata:
  name: keyval
  namespace: istio-system
spec:
  template: keyval
  params:
    key: request.headers["user"] | ""
```

But we used to define a instance by CRD like this way:
```
apiVersion: "config.istio.io/v1alpha2"
kind: metric
metadata:
  name: requestsize
  namespace: istio-system
spec:
  value: request.size | 0
  dimensions:
    source_version: source.labels["version"] | "unknown"
    destination_service: destination.service.host | "unknown"
    destination_version: destination.labels["version"] | "unknown"
    response_code: response.code | 200
  monitored_resource_type: '"UNSPECIFIED"'
```
which is also used in current [helm config.yaml](https://github.com/istio/istio/blob/1.1.0/install/kubernetes/helm/istio/charts/mixer/templates/config.yaml) , and the examples in  the [tasks](https://istio.io/docs/tasks/telemetry/) and [concepts](https://istio.io/docs/concepts/policies-and-telemetry/#instances).

And the same case for [Handler](https://istio.io/docs/reference/config/policy-and-telemetry/istio.policy.v1beta1/#Handler) a definition of handler is introduced. but the example above the definition, which really confused me a lot,  is still the old CRD way like this:
```
apiVersion: "config.istio.io/v1alpha2"
kind: prometheus
metadata:
  name: handler
  namespace: istio-system
spec:
  metrics:
  - name: request_count
    instance_name: requestcount.metric.istio-system
    kind: COUNTER
    label_names:
    - source_service
    - source_version
    - destination_service
    - destination_version
```
and in current [helm config.yaml](https://github.com/istio/istio/blob/1.1.0/install/kubernetes/helm/istio/charts/mixer/templates/config.yaml) , the CRD handler is replaced with the Handler way. But the concepts doc and task examples is still described by CRD.

My question what is recommended way to define a handler and instance in current mixer config.
