### ISSUE TITLE
Unable to authenticate JWT Token + CORS

### ISSUE THREAD

**Issue by procyclinsur** [istio/istio#12796]
I can't seem to wrap my head around how and where Istio is performing what type of authentication...

The reason we are not defining JWT authentication at the backend service level is because we do not want to authenticate our internal services just to send traffic to this particular service.  Only external communication should be authenticated.

**TL;DR:**

1. Can and should I create a Virtual Service for my istio-ingressgateway for CORS processing when my frontend `localhost` or `app.example.com` doesnt match the host designator on the  Gateway `api.example.com`?

2. I am placing my backend Gateway in the same namespace as the application I am serving, should it be in the istio-system namespace instead?

3. Is CORS processing performed before the JWT Check?

4. Is it possible to define a service level JWT authentication policy to only authenticate external communications, and still allow internal services access to said backend service?

**Versions first:**

```
#KUBERNETES
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-eks-7c34c0", GitCommit:"7c34c0d2f2d0f11f397d55a46945193a0e22d8f3", GitTreeState:"clean", BuildDate:"2019-03-01T22:49:39Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

#ISTIO 
Server Version: 1.0.6
```
NOTE: I could not get ouput from `istioctl` as I deleted the folder by mistake and had to reinstall the tool (newer version), server side has not changed. 

**INGRESS-GATEWAY:**

* namespace: istio-system

istio-ingressgateway is default aside from being an AWS NLB as opposed to an AWS CLB.

**POLICY (for JWT):**

* namespace: istio-system

```yaml
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: core-api-jwt-auth
  namespace: istio-system
spec:
  targets:
  - name: istio-ingressgateway
    ports:
    - number: 443
  origins:
  - jwt:
      audiences:
      - 4i00tescmmXXXXXX6c1chlvhpq
      issuer: https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_XXXXXXX
      jwksUri: https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_XXXXXXX/.well-known/jwks.json
  principalBinding: USE_ORIGIN
```

**GATEWAY:**

* namespace: custom

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: core-api-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "api.example.net"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "api.example.net"
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
```

**VIRTUAL SERVICE:** 

* namespace: custom

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: core-api-virtual-service
spec:
  hosts:
  - "api.example.net"
  gateways:
  - core-api-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: core-api-service
        port:
          number: 80
    corsPolicy:
      allowOrigin:
        - "*"
      allowMethods:
        - POST
        - GET
        - OPTIONS
      allowHeaders:
        - content-type
      maxAge: 300s
      allowCredentials: true
```

**JWT: **

```json
{
  "sub": "xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "aud": "4i00tescmmXXXXXX6c1chlvhpq",
  "email_verified": true,
  "token_use": "id",
  "auth_time": 1553610006,
  "iss": "https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_XXXXXXX",
  "cognito:username": "xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "exp": 1553613606,
  "custom:initial_device_id": "123",
  "iat": 1553610006,
  "email": "procyclinsur@xxxxx.jp"
}
```

**REQUEST HEADERS:**

```
Host: api.example.net
User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Access-Control-Request-Method: POST
Access-Control-Request-Headers: authorization,content-type
Referer: http://localhost:8080/
Origin: http://localhost:8080
Connection: keep-alive
TE: Trailers
```

NOTE: I manually entered `Authorization: apollo-token` in subsequent runs with only change being to the response body shown below.

**ERROR:**

* Web Console:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.example.net/graphql. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.example.net/graphql. (Reason: CORS request did not succeed)
```

* Response Body (when Authorization header is manually entered): 

When token is not manually entered the body is empty.

```
Origin authentication failed.
```

* Response Headers

```
HTTP/2.0 401 Unauthorized
content-length: 29
content-type: text/plain
date: Tue, 26 Mar 2019 14:49:46 GMT
server: envoy
X-Firefox-Spdy: h2
```
