### ISSUE TITLE
Tracing Sample rate on a per-service basis

### ISSUE THREAD

**Issue by Stono** [istio/istio#12818]
**Describe the feature request**
The ability to control the sample rate (or even disable sampling) on a per-service basis, rather than globally in pilot.

**Describe alternatives you've considered**
Not using istio tracing and instrumenting apps instead (sad times)

**Additional context**
We have one or two apps that are incredibly batch like, and the data they process I largely do not care about sampling.  However because during that window they provide such a disproportionate amount of traffic, we really strain jaeger: 

<img width="811" alt="Screenshot 2019-03-26 at 23 16 49" src="https://user-images.githubusercontent.com/1486729/55039754-59a88200-501d-11e9-9748-9462b4287108.png">

You can see outside of the load, jaeger is nice and happy.  

A global sample rate doesn't help me deal with this problem unfortunately.

**Comment by douglas-reid** [comment]
@Stono right now, this is supported, in a fashion, via Mixer-based tracing.  This would be a change from your default setup, but it would provide precise tracing controls.

Moving forward, I think we want to expose a more full-featured tracing API that isn't mixer-specific for providing that level of control.

/cc @objectiser

**Comment by Stono** [comment]
@douglas-reid thanks - could you point me through some documentation that i can read around that implementation?

**Comment by Stono** [comment]
This is becoming more of a requirement for us now as we have more and more services on the mesh, many we don't care about tracing for but some we want very high sample levelling for as they're SLI/SLO constrained services.

We can't possible enable it at the level we want for that subset of services, for all services as we're generate far far too much data.

So we're approaching the scale we can't actually make use of tracing without having the ability to control the same rate per service/workload.

**Comment by douglas-reid** [comment]
@Stono still working on building consensus on the best approach. I've fleshed out the two alternate approaches, as requested during the initial review and am hopeful that I can drive us towards a path forward sooner rather than later.

**Comment by Stono** [comment]
Great stuff @douglas-reid thank you.  More than happy to test out any alpha/beta/feature flagged implementations.

**Comment by Stono** [comment]
Hey @douglas-reid - i'm having to investigate work arounds to this as it's stopping us scaling.
Do you think it'd be suitable for me to modify the `Sidecar` of an application to remove the reference to `zipkin`?

eg at the moment the app looks like this:
```
  spec:
    egress:
    - hosts:
      - .*
      - istio-system/zipkin.istio-system.svc.cluster.local
      - istio-system/jaeger-agent.istio-system.svc.cluster.local
      - istio-system/istio-telemetry.istio-system.svc.cluster.local
      - istio-system/istio-policy.istio-system.svc.cluster.local
      - kube-system/kube-dns.kube-system.svc.cluster.local
      - core-system/logstash.core-system.svc.cluster.local
```

and remove?
```
      - istio-system/zipkin.istio-system.svc.cluster.local
```

I'm not sure on the knock on impact (eg what does envoy do when it doesn't get a route for zipkin)?

**Comment by Stono** [comment]
Linking associated issues: https://github.com/istio/istio/issues/11582 https://github.com/istio/istio/issues/14433

**Comment by objectiser** [comment]
HI @Stono , the proposal @douglas-reid has been working on is [here](https://docs.google.com/document/d/1s7ScttcAfKL7g4ch5goWQYymUEghtTFiMvGPcdbTnpk/edit?ts=5d5454e5).

At the end of the document in the section entitled "[7/2019] - Updated Sidecar Proposal" the proposed definition includes the ability to configure whether spans should be reported.

The benefit of this approach is that it completely disables creation of spans within the proxy (as well as reporting). If you just prevent the spans being reported, the proxy would still create new span context and propagate - thus resulting in the trace instance at your tracing backend being fragmented due to missing the intermediate spans.

Would be good to get your comments on the proposal.

**Comment by douglas-reid** [comment]
@Stono I've never tested what would happen in this scenario. I imagine that there might be some small overhead in Envoy, but I don't know that to be the case.

Re: the proposal. I believe we have general consensus on the API. I look forward to bringing up for formal API review in a few weeks (once vacations, etc., have finished).

**Comment by Stono** [comment]
Hey @objectiser,
If we simply have `[service a] -> [service-b]` and we effectively block (via sidecar or networkpolicy) on both; the trace would never be created correct?

I do wonder if anyone can confirm how long envoy would keep retrying and what sort of buffer it would hold?

I appreciate that it's not an ideal solution but being realistic i'm going to need to find a way to do this before the end of september :-(

**Comment by Stono** [comment]
Annnnddd it's the end of September :D Did you have the API review?

**Comment by Stono** [comment]
Just stumbled across https://github.com/istio/istio/wiki/EnvoyFilter-Samples#tracing-and-access-logging which seems to imply controlling tracing?

**Comment by objectiser** [comment]
@Stono Was just about to reply about that. On the last P&T call, @douglas-reid indicated that the proposed sidecar API changes may need to be reconsidered to take into account some future changes - I'll let him elaborate.

However he did also point to the EnvoyFilter which I have been playing with - and I believe it could meet your requirements. The example I have tried is having route specific sampling in the ingress:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: bookinfo-gateway-sampling
  namespace: istio-system
spec:
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: GATEWAY
      routeConfiguration:
        portNumber: 80
        vhost:
          name: "*:80"
          route:
            name: "productpage.mainpage"
    patch:
      operation: MERGE
      value:
        tracing:
          random_sampling:
            numerator: 1000
            denominator: TEN_THOUSAND
```
this was based on using a route name, to achieve this I had to update the `bookinfo-gateway.yaml` with:
```
  http:
  - match:
    - uri:
        exact: /productpage
      name: mainpage
...
    route:
    - destination:
        host: productpage
        port:
          number: 9080
    name: productpage
```
but seemed to work.

One thing though - this will only work if the entry point where the sampling decision is being made. So you can't adjust the sampling rate mid trace. So if the services you are interested in are all invoked from particular ingress routes, then this approach can be used to enable sampling - while globally the sampling rate could be set very low (or off).

**Comment by Stono** [comment]
Thanks for that example @objectiser !  I'll have a play and see how I get on.

**Comment by Stono** [comment]
@howardjohn i notice you added a 1.5 milestone tag here; is there so commitment to making this a feature?  Playing around with envoy filters feels quite fragile to me

**Comment by howardjohn** [comment]
I was just bumping it from 1.4 since that has already shipped. I am not familiar with exactly what telemetry team is doing to give a better estimate than just bumping it up to 1.5

**Comment by douglas-reid** [comment]
@Stono we might need to reevaluate, but work on a separate API for tracing (and related) was deprioritized because the feature could be achieved with EnvoyFilters. There had been pushback on intro'ing new APIs for this purpose.

I'm happy to help troubleshoot, based on your needs. Perhaps that can drive work to pick back up on our API proposal.

**Comment by Stono** [comment]
It's really fiddly with `EnvoyFiliter`, and configuring envoy itself doesn't feel right - that's why we have istio as a control plane, right?  Also envoy filters are applied at the destination, whereas what I would like to achieve is defining the rule in the destination, but have it apply to all the source systems (like a `DestiniationRule`).

Take this simplistic example (keep in mind we might have 300+ services going through nginx):

![tracing](https://user-images.githubusercontent.com/1486729/72090789-a1776c00-3306-11ea-87c2-6e208ef5991f.png)

If i only wanted traces from `nginx` to `service-b` and `service-d`, then i'd have to create complex envoy filters on `nginx` to select those hosts.  

From a permissions perspective, the people deploying service b, and d, do not have access to nginx so couldn't create `EnvoyFiliters` there anyway.

What I really want to do is in the `DestinationRule` for `b` and `d` is having an api that allows you to control the tracing level for that service which then configures the calling service envoy (nginx in this example) accordingly.

The problem is even more difficult, imagine if there were 20 services that all call `service-b`, would i be expected to go and create envoy filters for all of those calling services, and keep them up to date whenever we change the policy for `service-b`?

So really, EnvoyFilters don't work

**Comment by douglas-reid** [comment]
Not stale. Reopening.

**Comment by Stono** [comment]
We actually "disable" sampling for a service now by using the `http request headers` on the `virtualservice`:

```
  headers:
    request:
      set:
        x-b3-sampled: "0"
```
