### ISSUE TITLE
'lookup failed: 'request.host'' in istio-telemetry with Istio 1.1.1

### ISSUE THREAD

**Issue by Yisaer** [istio/istio#12866]
**Describe the bug**
I upgrade istio from 1.1.0 into 1.1.1. After I installed istio 1.1.1 and refresh all the pods with sidecar proxy. I apply follwoing **Metric** which works well in istio 1.1.0 and 1.0.6. And I found that the following **Metric** didn't work well and there are lots of logs in **istio-telemetry** showed 
> 2019-03-28T05:11:08.973358Z	warn	input set condition evaluation error: id='4', error='lookup failed: 'request.host''

```yaml
#  instance 
apiVersion: "config.istio.io/v1alpha2"
kind: metric
metadata:
  name: qunherequest
spec:
  value: "1" 
  dimensions:
    host: request.host | "unknown"
    qunheCode: response.headers["x-qunhe-code"] | "unknown"
    requestPath: request.url_path | "unknown"
    requestMethod: request.method | "unknown"
    responseCode: response.code | 0
    destinationName: destination.service.name | "unknown"
    destinationType: destination.labels["type"] | "unknown"
    # destinationNamespace: destination.service.namespace | "unknown"
  monitored_resource_type: '"UNSPECIFIED"'
---
# prometheus handler 
apiVersion: "config.istio.io/v1alpha2"
kind: prometheus
metadata:
  name: qunherequesthandler
spec:
  metrics:
  - name: qunhe_request_total # Prometheus 
    instance_name: qunherequest.metric.istio-system # Mixer Instance 
    kind: COUNTER
    label_names:
    - host
    - qunheCode
    - requestPath
    - requestMethod
    - responseCode
    - destinationName
    - destinationType
---
# 
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: qunherequestrule
spec:
  match: match(request.host,"*.coohom.com") == true && match(request.url_path,"/gateway/*") == false
  actions:
  - handler: qunherequesthandler.prometheus.istio-system
    instances:
    - qunherequest.metric.istio-system

```

**Steps to reproduce the bug**
Install Istio 1.1.1 , and apply the **Metric** 

**Version**
Kubernetes 1.13.1 , Istio 1.1.1

**Installation**
Istio installed by  **helm install**

**Comment by foshantiger** [comment]
similar error with Istio 1.1.1:
2019-03-29T03:23:08.488849Z     error   error creating instance: destination='tracespan:handler.zipkin.istio-system(zipkin)', error='evaluation failed at [default.tracespan.istio-system]'StartTime': 'lookup failed: 'request.time'''

**Version**
Kubernetes v1.10.10 , Istio 1.1.1

**Installation**
Istio installed by helm install

```yaml
apiVersion: "config.istio.io/v1alpha2"
kind: tracespan
metadata:
  name: default
  namespace: istio-system
spec:
  traceId: request.headers["x-b3-traceid"] | ""
  spanId: request.headers["x-b3-spanid"] | ""
  parentSpanId: request.headers["x-b3-parentspanid"] | ""
  spanName: request.path | "/"
  startTime: request.time
  endTime: response.time
  httpStatusCode: response.code | 0
  sourceName: source.workload.name | ""
  sourceIp: source.ip | ip("0.0.0.0")
  destinationName: destination.workload.name | ""
  destinationIp: destination.ip | ip("0.0.0.0")
  requestSize: request.size | 0
  requestTotalSize: request.total_size | 0
  responseSize: response.size | 0
  responseTotalSize: response.total_size | 0
  apiProtocol: api.protocol | ""
  rewriteClientSpanId: "false"
  spanTags:
    http.host: request.host | ""
    http.method: request.method | ""
    http.path: request.path | ""
    http.user_agent: request.useragent | ""
    principal: request.auth.principal | "unknown"
    source.version: source.labels["version"] | "unknown"
    destination.version: destination.labels["version"] | "unknown"
---
apiVersion: "config.istio.io/v1alpha2"
kind: zipkin
metadata:
  name: handler
  namespace: istio-system
spec:
  url: "http://zipkin.istio-system:9411/api/v1/spans"
  sampleProbability: 1.0
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: zipkin
  namespace: istio-system
spec:
  match: "true" # If omitted match is true.
  actions:
  - handler: handler.zipkin
    instances:
    - default.tracespan.istio-system
---
```
