### ISSUE TITLE
Fail to set gateway to service's differernt version with weight ( Route rules have no effect on ingress gateway requests )

### ISSUE THREAD

**Issue by Tao526** [istio/istio#12868]
With samples/helloword, I want to set routing to version v1 with weight 20 ( version v2 with weight 80).
I write 2 yaml files as following:

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helloworld
spec:
  hosts:
    - helloworld
  http:
  - route:
    - destination:
        host: hello
        subset: v1
      weight: 20
    - destination:
        host: helloworld
        subset: v2
      weight: 80

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: helloworld
spec:
  host: helloworld
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2

After applying them,  the configs do not report an error. However , it seemed not to work when I curl the site. The same configs works at the sample bookinfo.

I wonder if the gateway ignoreed the new added virtualservice hello ,or something else resons

**Comment by AshishThakur** [comment]
Istio Version: 1.1.0
I observe a similar behaviour. I created a new virtualservice for helloworld which is shipped in samples
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helloworld-vs
spec:
  hosts:
  - helloworld
  http:
  - route:
    - destination:
        host: helloworld
        subset: v1
```
And created a destionationrule
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: helloworld
spec:
  host: helloworld
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
```

I have another sleep service running and in case i send the request the virtualservice i just applied seems to be working fine and all requests are routed to v1 but in case i access it via gateway the virtualservice does not seem to be working.
