### ISSUE TITLE
OutboundTrafficPolicy should be configurable per Workload

### ISSUE THREAD

**Issue by robertpanzer** [istio/istio#12873]
**Describe the feature request**
Currently the Outbound Traffic Policy can only be configured cluster wide.
Additionally the default is `ALLOW_ANY` which is also preferred by many (even though I have a completely different opinion on this for various reasons).

In larger clusters dedicated applications might not want this behavior, for example to make sure that a staging environment cannot access any production systems.

Therefore it would be nice if the policy could be configured with the Sidecar resource, e.g.:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: foo
spec:
  outboundTrafficPolicy: 
    mode: REGISTRY_ONLY | ALLOW_ANY
  egress:
    - hosts:
        - "foo/*"
        - "bar/*"
```

Setting this in a Sidecar resource would override the default in the mesh config.

**Describe alternatives you've considered**
The alternative to support the requirement of maybe only a single tenant would be to change the default to `REGISTRY_ONLY` and ask everybody else to register their external dependencies.

**Additional context**
If the general approach is accepted I would be fine with helping out on this and providing a PR.
