### ISSUE TITLE
Setting up a ServiceEntry for HTTPS/TLS with SNI fails with Istio on GKE

### ISSUE THREAD

**Issue by MrMage** [istio/istio#12882]
**Describe the bug**
Using the example config

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-https
spec:
  hosts:
  - api.dropboxapi.com
  - www.googleapis.com
  - api.facebook.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
```

from https://istio.io/docs/reference/config/networking/v1alpha3/service-entry/, running `curl https://www.googleapis.com` fails with `curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number` on Ubuntu 18.04 and with `curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol` on Ubuntu 14.04. The same command works when adding

```
  - number: 80
    name: http
    protocol: HTTP
```

to the `ServiceEntry` and using `http://` instead of `https://`. Using `protocol: HTTPS` does not make a difference.

I understand that Istio won't be able to inspect the HTTP traffic; however, the documentation indicates that the above setup _should_ allow detecting the remote host via SNI and then proxying the encrypted connection through the egress.

**Expected behavior**
`curl` to the `https://` url should work as well.

**Steps to reproduce the bug**
1. Launch an Ubuntu 18.04 image on Kubernetes:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: xxx
  namespace: xxx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: xxx
    spec:
      containers:
      - name: xxx
        image: ubuntu:18.04
        imagePullPolicy: Always
        command: ["/bin/sleep"]
        args: ["36000"]e
```

**Version**
```
version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-17-g2b13318"}
Error: error execing into istio-citadel-76f674f64-wskvg citadel container: command terminated with exit code 255
```

No idea why that command fails — according to the GKE dashboard, I am running Istio `1.0.6-gke.1`. The error also occurred with Istio 1.0.3, though.

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.7", GitCommit:"65ecaf0671341311ce6aea0edab46ee69f65d59e", GitTreeState:"clean", BuildDate:"2019-01-24T19:32:00Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-gke.7", GitCommit:"aeaa96020ec0614a8773799058c3b8d58c19b9ff", GitTreeState:"clean", BuildDate:"2019-03-13T11:22:57Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
Installed via [Istio on GKE](https://cloud.google.com/istio/docs/istio-on-gke/installing#adding_istio_on_gke_to_an_existing_cluster), with permissive mTLS. (I did have strict TLS enabled before, but have since disabled that again.)

**Environment**
Vanilla GKE with Container-Optimized OS, see above for the Kubernetes version.

**Cluster state**
(Partial dump attached.)
[istio-dump.zip](https://github.com/istio/istio/files/3019115/istio-dump.zip)

**Comment by hzxuzhonghu** [comment]
I've tested your config, and only replace add one more host with `www.github.com`, and I can access by `curl https://www.github.com -ivk`. But I can not access  `api.dropboxapi.com`. I know this is expected, because in my vm, I can not access `api.dropboxapi.com`
```
/ # curl https://api.dropboxapi.com/  -ivk
*   Trying 162.125.82.7...
* TCP_NODELAY set
* Connected to api.dropboxapi.com (162.125.82.7) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.dropboxapi.com:443 
* stopped the pause stream!
* Closing connection 0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.dropboxapi.com:443 

```

**Comment by MrMage** [comment]
@hzxuzhonghu thank you for looking into this!

I've tried with a completely new cluster now, with the following config:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: xxx
  namespace: xxx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: xxx
    spec:
      containers:
      - name: xxx
        image: ubuntu:18.04
        command: ["/bin/sleep"]
        args: ["36000"]
        imagePullPolicy: IfNotPresent
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-https
spec:
  hosts:
  - fcm.googleapis.com
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS

---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-https2
spec:
  hosts:
  - heise.de
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
```

Now, `curl https://fcm.googleapis.com` works. However, `curl -vv https://heise.de` indicates that this connection is _also_ routed to `fcm.googleapis.com`. Is it possible that I am simply affected by https://github.com/istio/istio/issues/9744? If so, what are my options to work around the issue, given that Istio on GKE does not yet support Istio 1.1? I can hardly believe that it should be impossible to connect to two different services via HTTPS.

(Listener config will follow in a minute.)

**Comment by MrMage** [comment]
Unfortunately, I'm unable to extract the listener config:

```
$ istioctl pc listener xxx-89985d997-m2f8b.xxx --port=443 --address="0.0.0.0" -o json
Error: error unmarshalling config dump response from Envoy: json: cannot unmarshal object into Go value of type []json.RawMessage
```

**Comment by MrMage** [comment]
Okay, that was due to an `istioctl` version mismatch. The full config is attached; looks like only the service entry for `fcm.googleapis.com` is applied.

[istio-config.json.zip](https://github.com/istio/istio/files/3021603/istio-config.json.zip)

**Comment by hzxuzhonghu** [comment]
Yeah, the two serviceEntry has duplicated port, so the first one take effect.

**Comment by MrMage** [comment]
But even when I add both hosts to the first ServiceEntry, heise.de never gets added to the config. How am I supposed to connect to more than one HTTPS service outside my cluster?

**Comment by hzxuzhonghu** [comment]
make protocol `TLS` in this case,  for other tcp protocol, one of the solution i can think of is to provide addresses in serviceentry.

![image](https://user-images.githubusercontent.com/13374016/55221522-a02bf580-5244-11e9-95d4-8de7d9fdff11.png)

**Comment by hzxuzhonghu** [comment]
![image](https://user-images.githubusercontent.com/13374016/55221569-b5088900-5244-11e9-90df-d35091834808.png)

**Comment by MrMage** [comment]
@hzxuzhonghu I have created the following ServiceEntries now:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-https
spec:
  hosts:
  - fcm.googleapis.com
  - bing.com
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-https2
spec:
  hosts:
  - heise.de
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-arstechnica
spec:
  hosts:
  - arstechnica.com
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
```

**All four domains work via HTTP.** So clearly I can have more than one `ServiceEntry` on the same port, provided the hosts are different.

However, **all four domains point to `fcm.googleapis.com` when using HTTPS or TLS (see the entry for `arstechnica.com`).** Also, [the config](https://github.com/istio/istio/files/3021900/istio-config.json.zip) _only_ mentions `fcm.googleapis.com`, even though all four hosts work via HTTP.

**[The docs](https://istio.io/docs/reference/config/networking/v1alpha3/service-entry/) specifically state that at least `fcm.googleapis.com` and `bing.com` should work in this case.** Also, looking up the IP addresses of each service I use (and which may change in the future) can't be the solution?

**Comment by hzxuzhonghu** [comment]
Note: if should be 
```
  ports:
  - number: 443
    name: https
    protocol: TLS
```

https works as tcp

**Comment by MrMage** [comment]
@hzxuzhonghu I have tried using both `TLS` and `HTTPS` in that field. Neither has worked.

**Comment by MrMage** [comment]
Update:

I have now been able to connect to remote services with the following configuration:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-https
spec:
  hosts:
  - api.appfigures.com
  location: MESH_EXTERNAL
  resolution: NONE
  ports:
  - number: 443
    name: https
    protocol: TLS
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tls-routing-https
spec:
  hosts:
  - api.appfigures.com
  tls:
  - match:
    - sniHosts:
      - api.appfigures.com
    route:
    - destination:
        host: api.appfigures.com
```

Initially, this did not work because I had exposed a `Service` based on GCP LoadBalancer on port 443 whose port name was `grpc`. Changing that port name to `https` changed the Envoy proxies to listen on that port with the `TCP` protocol instead of the `HTTP` protocol (as evidenced by `istioctl proxy-config listeners istio-test-7f478f476c-qzrlf -n istio-test`).

However, [the docs](https://istio.io/docs/reference/config/networking/v1alpha3/service-entry/) still make it sound like a single config of type

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-https
spec:
  hosts:
  - api.dropboxapi.com
  - www.googleapis.com
  - api.facebook.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
```

should be sufficient to access external services. **That only works for the first service declared in that list**; all others would also be routed to `api.dropboxapi.com` in this case even if the host `www.googleapis.com` is specified.

Am I missing something?
