### ISSUE TITLE
Gateway definition created in control cluster causes failure in remotes for cluster-aware installation.

### ISSUE THREAD

**Issue by dkushner** [istio/istio#12938]
**Describe the bug**
With two clusters configured according to the multicluster installation instructions with cluster-aware routing, an ingress gateway in cluster-1 (the control plane) forwarding requests to a service in the remote via an endpoint `outbound|4433||birdcage.production.svc.cluster.local` results in a 503 and shows the upstream as a pod IP of the remote service.

This determination was made by observing the access logs on the configured ingress gateway in cluster-1 and seeing the following message associated with a failed 503 response:

```
"GET /login HTTP/2" 503 UF,URX "-" 0 57 4140 - "$NODE_IP_GW" "$USER_AGENT" "$REQ_ID" "birdcage.mydomain.io" "$POD_IP:4433" outbound|4433||birdcage.production.svc.cluster.local - $POD_IP_GW $NODE_IP_GW:39170 birdcage.mydomain.io
```

I've replaced the true values with variable names for clarity and for privacy but of note is the facth that $POD_IP in the above string is the actual IP address of a pod serving the `birdcage` service in the `production` namespace of the remote. From the documentation, this was not the behaviour I was expecting. 

**Expected behavior**
The ingress gateway in cluster-1 would forward requests to the remote service at endpoint `outbound|4433||birdcage.production.svc.cluster.local` to the remote (cluster-2) ingress gateway which would then use SNI to properly route the request within cluster-2. 

**Steps to reproduce the bug**
Assuming a standard installation according to the [cluster-aware guide](https://preliminary.istio.io/docs/examples/multicluster/split-horizon-eds). Create a `Gateway` definition with the following spec properties:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: production-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers
  - hosts:
  - '*.mydomain.io'
  - 'mydomain.io'
  port:
    name: https
    number: 443
    protocol: HTTPS
  tls:
    mode: SIMPLE
    privateKey: /etc/istio/ingressgateway-certs/tls.key
    serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
```

And a `VirtualService` definition with the following spec, to configure this gateway to forward traffic to the remote:

```yaml
apiVersion: newtorking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: birdcage
  namespace: istio-system
spec:
  gateways:
  - production-gateway.istio-system.svc.cluster.local
  - mesh
  hosts:
  - birdcage.mydomain.io
  - birdcage.production.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: /login
    route:
    - destination:
        host: birdcage.production.svc.cluster.local
```

With these two resources in place, attempt to send traffic through the ingress gateway indicating a hostname consistent with whatever domain is
indicated in the gateway configuration. Observe that the logs of the ingress gateway for the issued request show the upstream as an IP associated
with a pod in the remote cluster, rather than the remote cluster ingress.

**Version**
Istio 1.1.0-rc.5
Kubernetes 1.11.7-gke.12

**Installation**
Installed via Helm chart according to the [cluster-aware guide](https://preliminary.istio.io/docs/examples/multicluster/split-horizon-eds).

**Environment**
GKE
