### ISSUE TITLE
Unable to compile match condition expression "unknown function GEQ"

### ISSUE THREAD

**Issue by flunderveiko** [istio/istio#12956]
**Describe the bug**
I just want to log log entries with a response code greater than or equal to 400.
Rule stdio in namespace istio-system:

```
match: response.code >= 400
```
Then I get the following error message and istio-telemetry no longer logs.

error	unknown function: GEQ
warn	Unable to compile match condition expression: 'unknown function: GEQ', rule='stdio.rule.istio-system', expression='response.code >= 400'
 

**Expected behavior**
no looging messages with response.code <400

**Steps to reproduce the bug**
Edit rule in namespace istio-system
```
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: stdio
  namespace: istio-system
spec:
  actions:
  - handler: handler.stdio
    instances:
    - accesslog.logentry
  match: response.code >= 400
```

**Version**
Version: 1.0.6
GitRevision: 98598f88f6ee9c1e6b3f03b652d8e0e3cd114fa2
User: root@464fc845-2bf8-11e9-b805-0a580a2c0506
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean

**Installation**
helm templates

**Environment**
GKE 1.12

**Cluster state**
