### ISSUE TITLE
istio-galley service calling failed in Istio 1.1.1

### ISSUE THREAD

**Issue by bjethwan** [istio/istio#12951]
**Describe the bug**
I was trying to follow https://istio.io/docs/examples/multicluster/split-horizon-eds/
When I got struck in below step
```
kubectl create --request-timeout=1m --context=$CTX_CLUSTER1 -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cluster-aware-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: tls
      protocol: TLS
    tls:
      mode: AUTO_PASSTHROUGH
    hosts:
    - "*.local"
EOF
```
```
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling admission webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
I had created the cluster using kops with t2.xlarge instances for master and workers.

Istio seemed to be running perfectly fine
```
kubectl get pods --context=$CTX_CLUSTER1 -n istio-system
NAME                                      READY   STATUS      RESTARTS   AGE
istio-citadel-68c8d6cff8-gdrzf            1/1     Running     0          38m
istio-cleanup-secrets-1.1.1-hfwlb         0/1     Completed   0          38m
istio-galley-6db4964df6-pz8zk             1/1     Running     0          38m
istio-ingressgateway-cd5df7bc6-6kjgb      1/1     Running     0          38m
istio-pilot-597dd58685-bxgb6              2/2     Running     0          38m
istio-policy-67f66c8b5c-dvk5g             2/2     Running     3          38m
istio-security-post-install-1.1.1-7ph6r   0/1     Completed   0          38m
istio-sidecar-injector-59fc9d6f7d-7z2xs   1/1     Running     0          38m
istio-telemetry-c5bfc457f-wzhnj           2/2     Running     3          38m
prometheus-89bc5668c-d6v5l                1/1     Running     0          38m
```

**Expected behavior**
cluster-aware-gateway should have come up fine.

**Steps to reproduce the bug**
Use KOPS to create k8s clusters with kubernetes version set as 1.11.8.
kops version
Version 1.11.0 (git-2c2042465)

istioctl version
version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-17-g2b13318"}

**Version**
Talked above

**Installation**
https://istio.io/docs/examples/multicluster/split-horizon-eds/

**Environment**
AWS

**Cluster state**
$ tools/dump_kubernetes.sh -z
Fetching debug/configz from pilot
Fetching debug/endpointz from pilot
Fetching debug/adsz from pilot
Fetching debug/authenticationz from pilot
Fetching metrics from pilot
Retrieving kubernetes resource configurations
Retrieving istio resource configurations
Retrieving logs for istio-system/istio-citadel-68c8d6cff8-gdrzf/citadel
tools/dump_kubernetes.sh: line 118: "0" + "15382": syntax error: operand expected (error token is ""0" + "15382"")
