### ISSUE TITLE
need Egress rule to git clone using SSH

### ISSUE THREAD

**Issue by prune998** [istio/istio#1296]
One of my microservice is cloning an external GIT private repo. As we are using SSH keys for auth, I have to create an Egress rule of type SSH (or GIT) like : 

```
apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: gitlab-egress-rule
spec:
  destination:
    service: git.myserver.com
  ports:
    - port: 22
      protocol: ssh
```

Any idea how to support this ? 

```
Version: 0.2.10
GitRevision: f27f2803f59994367c1cca47467c362b1702d605
GitBranch: release-0.2
User: sebastienvas@ee792364cfc2
GolangVersion: go1.8
```
Kubernetes on GKE, version 1.7.8
