### ISSUE TITLE
Routing not working as expected

### ISSUE THREAD

**Issue by walkerline** [istio/istio#12960]
Istio version 1.1.0

We finished the installation of Istio 1.1.0
And we found that we are not able to apply the routing rule to the service mesh.

For example, we use the simplest helloworld service. and we applied below virtual service to route the request to only v2 helloworld, but it did not work as expected.

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helloworld
spec:
  hosts:
  - helloworld
  http:
  - route:
    - destination:
        host: helloworld
        subset: v2
```
After I applied above rule, i got nothing or no response from my curl command any more.

Thanks

**Comment by esnible** [comment]
First, do `kubectl get destinationrule` to verify you have a DestinationRule that defines `name: v2`.

The next thing to check is the sidecar status.  Do `kubectl get pods -l version=v2` and verify that you have pods labeled `version: v2`.  (Assuming the DestinationRule defined `v2` as `version: v2`.

The tool https://github.com/aspenmesh/istio-vet can be good for finding problems in Istio configuration.

**Comment by walkerline** [comment]
I think everything looks fine. But still when I curl the helloworld, i got no response at all.

```
kubectl get destinationrule

NAME         HOST         AGE
helloworld   helloworld   10d

```


```
kubectl describe destinationrule helloworld

Name:         helloworld
Namespace:    default
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"networking.istio.io/v1alpha3","kind":"DestinationRule","metadata":{"annotations":{},"name":"helloworld","namespace":"defaul...
API Version:  networking.istio.io/v1alpha3
Kind:         DestinationRule
Metadata:
  Creation Timestamp:  2019-03-22T13:50:31Z
  Generation:          1
  Resource Version:    14102556
  Self Link:           /apis/networking.istio.io/v1alpha3/namespaces/default/destinationrules/helloworld
  UID:                 75bc2434-4ca9-11e9-8530-0050569bf5da
Spec:
  Host:  helloworld
  Subsets:
    Labels:
      Version:  v1
    Name:       v1
    Labels:
      Version:  v2
    Name:       v2
Events:         <none>
```

```
kubectl -n istio-system logs -l "app=istio-vet"
Vetter "AppLabel" ran successfully and generated no notes

Vetter "serviceportprefix" ran successfully and generated no notes

Vetter "serviceassociation" ran successfully and generated no notes

Vetter "DanglingRouteDestinationHost" ran successfully and generated no notes

Vetter "ConflictingVirtualServiceHost" ran successfully and generated no notes
```

**Comment by esnible** [comment]
When you say "no response" do you mean a timeout?  If there is an HTTP error like 404 or 503 use `curl -v` to see it.

Do `istioctl proxy-status` and see if the _curl_ pod or _helloworld_ pod is `STALE`.  Do `istioctl authn tls-check <curl-pod>` and look for `CONFLICT`.

When I get really stuck I `kubectl exec` into the sidecar and attempt to simulate what the sidecar is doing.  I use the following commands.  These are not version label aware, so these might not detect your problem.  You may want to replace the endpoint section with the IP address of a v2 pod to troubleshoot that subset.

```
MYCLIENT=productpage  # Replace with your client, e.g. curl, pod svc
MYSERVER=details      # Replace with your server, e.g. helloworld, svc
HPATH=details/0       # Replace with your path
PORT=9080             # Replace with pod (not svc) port
// NON-mTLS
kubectl exec $(kubectl get pod --selector app=$MYCLIENT --output jsonpath='{.items[0].metadata.name}') -c istio-proxy -- curl -v http://$(kubectl get endpoints $MYSERVER -o jsonpath='{.subsets[0].addresses[0].ip}'):$PORT/$HPATH 
// mTLS
kubectl exec $(kubectl get pod --selector app=$MYCLIENT --output jsonpath='{.items[0].metadata.name}') -c istio-proxy -- curl -v https://$MYSERVER.default.svc.cluster.local:$PORT/$HPATH --resolve "$MYSERVER.default.svc.cluster.local:$PORT:$(kubectl get endpoints $MYSERVER -o jsonpath='{.subsets[0].addresses[0].ip}')" --key /etc/certs/key.pem --cert /etc/certs/cert-chain.pem --cacert /etc/certs/root-cert.pem --insecure
```

**Comment by walkerline** [comment]
Thanks
1. I actually get 404 not found error 
2. output for istioctl proxy-status
```
NAME                                                   CDS        LDS        EDS               RDS        PILOT                            VERSION
helloworld-v1-7b984f4489-7ncj2.default                 SYNCED     SYNCED     SYNCED (50%)      SYNCED     istio-pilot-55c7b5b879-zn42m     1.1.0
helloworld-v2-9948f5495-54g9k.default                  SYNCED     SYNCED     SYNCED (50%)      SYNCED     istio-pilot-55c7b5b879-zn42m     1.1.0
```

nothing shows conflict for below
```
istioctl authn tls-check helloworld-v2-9948f5495-54g9k

HOST:PORT                                                                                STATUS     SERVER        CLIENT     AUTHN POLICY                                 DESTINATION RULE

helloworld.default.svc.cluster.local:5000                                                OK         HTTP/mTLS     HTTP       default/                                     helloworld/default
```

```
kubectl exec helloworld-v2-9948f5495-54g9k -c istio-proxy -- curl -v http://xx.xx.xx.xx:31380/hello

*   Trying xx.xx.xx.xx...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to xx.xx.xx.xx (xx.xx.xx.xx) port 31380 (#0)
> GET /hello HTTP/1.1
> Host: xx.xx.xx.xx:31380
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< location: http://xx.xx.xx.xx:31380/hello
< date: Mon, 01 Apr 2019 18:30:42 GMT
< server: istio-envoy
< content-length: 0
< 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to host xx.xx.xx.xx left intact

```

**Comment by walkerline** [comment]
So initially, if we apply below gateway yaml, it will work fine
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: helloworld-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helloworld
spec:
  hosts:
  - "*"
  gateways:
  - helloworld-gateway
  http:
  - match:
    - uri:
        exact: /hello
    route:
    - destination:
        host: helloworld
        port:
          number: 5000
```

Then we will get 200:
```
curl -v http://xx.xx.xx.xx:31380/hello
*   Trying xx.xx.xx.xx...
* TCP_NODELAY set
* Connected to xx.xx.xx.xx (xx.xx.xx.xx) port 31380 (#0)
> GET /hello HTTP/1.1
> Host: xx.xx.xx.xx:31380
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< content-type: text/html; charset=utf-8
< content-length: 59
< server: istio-envoy
< date: Mon, 01 Apr 2019 18:33:48 GMT
< x-envoy-upstream-service-time: 175
< 
Hello version: v2, instance: helloworld-v2-9948f5495-54g9k
```

Then if we apply below virtual service rule:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helloworld
spec:
  hosts:
  - helloworld
  http:
  - route:
    - destination:
        host: helloworld
        subset: v2
```

We will get 404

**Comment by esnible** [comment]
Something that jumps out at me is `31380` for a port.  That is the Nodeport used by the Istio ingressgateway.  I do not have any test cases where a server was listening on 31380.

What happens when you curl localhost:31380/hello ?

**Comment by walkerline** [comment]
So does that mean we need to use a load balancer?
Sorry im new to this area.

And where to curl that localhost:31380/hello? in the pod or on the cluster?
I tried both, either one returns 404.

**Comment by esnible** [comment]
In Kubernetes a *Service* has up to three port numbers.  You will see a `port`, sometimes a `targetPort`, and sometimes a `nodePort`.

Your container is listening on a port, for example `8000`.  You can verify this by `kubectl exec` into the `istio-proxy` sidecar and doing `curl localhost:8000/hello`.  There will be no Kubernetes or Istio involved, just containerization.  This kind of port is called the `targetPort`.

Under Kubernetes we often want to use a different port than what the container author did.  So within the cluster, without Istio, another pod might want to use `curl helloworld:80/hello` or `curl helloworld:8080/hello`.  The number here is the Service `port`.  (If it is the same as the `targetPort` the targetPort can be skipped.)

From outside the cluster, meaning on your laptop if you use minikube or a public cloud, you can talk to the `nodePort` on some IP address that the cloud makes available to you.

With just Kubernetes, if you talk to `helloworld:8000/hello` from within the cluster the traffic will go to the VirtualIP of the HelloWorld service, and from there to the targetPort of a HelloWorld Service *Endpoint*.  With Istio, if you talk to `helloworld:8000/hello` from within the app container it will go to the sidecar, then directly to the sidecar on on endpoint, then to the server app container.  The virtual IP of the service will be bypassed.

Because Istio uses 31380 as the nodePort you would use that as the port only from your laptop, and for the IP address you would use the address reported by `minikube ip` or by `kubectl -n istio-system get service istio-ingressgateway`.

**Comment by walkerline** [comment]
Thanks @esnible for your detail explanation
So couple of things:

1. the targetPort in our case is 5000 and its the same as Service port
2. I was able to `curl localhost:5000/hello` and got 200 in the istio side car
3. I was also able to use `curl helloworld:5000/hello` and got 200 in another pod
4. **If I applied a routing rule(e.g. in my question) to helloworld serivce to route request only to v2, and  If I run `curl helloworld:5000/hello` from another pod, I do not see my rule got applied, i will get response from either v1 or v2 every time when i make the call**

It does not seem like my rule got applied. But why?

Thanks

**Comment by walkerline** [comment]
So just make things clear, now we have 2 issues:
1. If we curl the helloworld service from ingress, we got 404 error
2. If we curl the helloworld service from another pod on the same cluster, we can get response, but the Routing rule is not working at all. Seems like the rule was not able to pushed to the sidecar.

**Comment by walkerline** [comment]
So an update:

if we apply the routing rule on gateway level, it works fine.

For example, if we apply below virtual service on Gateway, the routing will be just working fine.
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helloworld
spec:
  hosts:
  - "*"
  gateways:
  - helloworld-gateway
  http:
  - route:
    - destination:
        host: helloworld
        subset: v1

```

However if we apply below rule to service to service routing, it won't work

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helloworld-internal
spec:
  hosts:
  - helloworld
  http:
  - route:
    - destination:
        host: helloworld
        subset: v1
```

And i test this one by loggin on to another pod other than Helloworld, and when i send the request, the routing rule don't work, i can still see response coming from either v1 or v2 on a round robin way.

**Comment by walkerline** [comment]
any one can help?

**Comment by esnible** [comment]
To recreate your scenario I did

```
kubectl apply -f samples/helloworld/helloworld.yaml

cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: helloworld
  namespace: default
spec:
  host: helloworld
  subsets:
  - labels:
      version: v1
    name: v1
  - labels:
      version: v2
    name: v2
EOF

cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helloworld-internal
spec:
  hosts:
  - helloworld
  http:
  - route:
    - destination:
        host: helloworld
        subset: v1
EOF
```

I then did the following and always saw V1:

```
kubectl run cli1 --image tutum/curl --command -- bash -c 'sleep 9999999'
// Repeat, I always get v1
kubectl exec -it $(kubectl get pod --selector run=cli1 --output jsonpath='{.items[0].metadata.name}') -- curl helloworld:5000/hello
```

I also applied _helloworld-gateway_ which is bound to the outside world.  It did not affect these internal calls.

If you are not seeing V1 consistently routed by your in-mesh client this means the sidecar of the in-mesh client isn't configured.  Verify the pod status is `2/2`.
