### ISSUE TITLE
Documentation bug - Authorization for TCP services - missing DR for Mongo

### ISSUE THREAD

**Issue by arielb135** [istio/istio#12989]
**Describe the bug**
When following the tutorial here: https://istio.io/docs/tasks/security/authz-tcp/
after deploying mongo (and switching to it) - the rating services did not work.

As part of the requirement, global MTLS needed to be created, when deploying mongo, there was **no** DestinationRule that was created to mongo, thus - it rejected all traffic to it.

Referenced issue: #12964 

After applying this:
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mongodb
spec:
  host: mongodb
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
---
```

The product page started to show the ratings

**Expected behavior**
missing the destination rule from documentation

**Steps to reproduce the bug**
Enable MTLS using MeshPolicy (As requested in pre conditions), and follow until this:
![image](https://user-images.githubusercontent.com/33662254/55399139-f786da00-5552-11e9-802a-b5f5391081b6.png)

Rating will be unavailable.
