### ISSUE TITLE
metadata.resourceVersion: Invalid value

### ISSUE THREAD

**Issue by Kyslik** [istio/istio#12985]
**Describe the bug**
I was upgrading to the Istio 1.1.1 using the official [guide](https://istio.io/docs/setup/kubernetes/upgrade/steps/) and when I applied the helm chart I get this error:

```
The Service "istio-ingressgateway" is invalid: metadata.resourceVersion: Invalid value: "": must be specified for an update
```
> **Note**: I am using this in istio-values.yaml

```
gateways:
  istio-ingressgateway:
    autoscaleMin: 3
    serviceAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    externalTrafficPolicy: Local
```

**Expected behavior**
No error.

**Steps to reproduce the bug**
Have Istio 1.0.6 installed and try to upgrade to 1.1.1.

**Version**
Istio: 1.1.1
k8s: 1.11.7

**Installation**
I used helm chart (no Tiller). Relevant `gateway` is noted above.

**Environment**
AWS
