### ISSUE TITLE
Support end user authentication policy with multiple JWT issuers

### ISSUE THREAD

**Issue by codependent** [istio/istio#12992]
**Describe the feature request**
At the moment the end user validation Policy for a JWT can be configured like this:
```
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: productpage-mTLS-with-JWT
  namespace: frod
spec:
  target:
  - name: productpage
    ports:
    - number: 9000
  peers:
  - mtls:
  origins:
  - jwt:
      issuer: "https://securetoken.google.com"
      audiences:
      - "productpage"
      jwksUri: "https://www.googleapis.com/oauth2/v1/certs"
      jwt_headers:
      - "x-goog-iap-jwt-assertion"
      trigger_rules:
      - excluded_paths:
        - exact: /health_check
  principalBinding: USE_ORIGIN
```

We have come across a scenario where a microservice could get valid a JWT from two different issuers.

I am not sure if configuring multiple JWT validations is possible right now. Apparently it could be since the origin field expects a list. Is something like this valid?:
```
origins:
  - jwt:
      issuer: "https://someissuer.com"
      ...
  - jwt:
      issuer: "https://anotherissuer.com"
      ...
```
If it isn't supported I'd appreciate that it were added to the backlog since I think it's an important feature.

Otherwise, is it documented? I haven't found it explicitly: https://istio.io/docs/reference/config/istio.authentication.v1alpha1/

**Comment by esnible** [comment]
I tried to recreate your Policy and it wasn't accepted until I made `targets` plural and made the `name` lower case.

I tried to recreate your request with

```
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: productpage-mtls-with-jwt
spec:
  targets:
  - name: productpage
    ports:
    - number: 9080
  peers:
  - mtls:
  origins:
  - jwt:
      issuer: "https://securetoken.google.com"
      audiences:
      - "productpage"
      jwksUri: "https://www.googleapis.com/oauth2/v1/certs"
      jwt_headers:
      - "x-goog-iap-jwt-assertion"
      trigger_rules:
      - excluded_paths:
        - exact: /health_check
  - jwt:
      issuer: https://www.example.com
      jwksUri: "https://www.example.com/oauth2/v1/certs"
  principalBinding: USE_ORIGIN
```

Both www.example.com and securetoken.google.com were present in the Envoy configuration dump.  I did not test with actual traffic.
