### ISSUE TITLE
IP no longer allowed in ServiceEntry host field

### ISSUE THREAD

**Issue by ryan-dyer** [istio/istio#13009]
**Describe the bug**
With the 1.1 release, the host field of a service entry can no longer be an IP address.  Perhaps this is intended, but if so, additional documentation needs to be added on how to allow an IP address for a service entry. 

**Expected behavior**
An IP address is allowed for a service entry.  Our mesh is configured with REGISTRY_ONLY and our application needs to access the AWS ec2 metadata endpoint at 169.254.169.254.  Have tried
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: aws-metadata
spec:
  hosts:
  - ec2-metadata.local
  endpoints:
  - address: 169.254.169.254
  ports:
  - number: 80
    name: http-aws-metadata
    protocol: HTTP
  resolution: STATIC
  location: MESH_EXTERNAL
```
as a hopeful workaround, but this doesnt work either.

**Steps to reproduce the bug**
Unable to create the following service entry which worked in istio 1.0.6
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: aws-metadata
spec:
  hosts:
  -169.254.169.254
  ports:
  - number: 80
    name: http-aws-metadata
    protocol: HTTP
```

**Version**
```
client version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-17-g2b13318"}
citadel version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
galley version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
galley version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
ilbgateway version: version.BuildInfo{Version:"", GitRevision:"", User:"", Host:"", GolangVersion:"", DockerHub:"", BuildStatus:"", GitTag:""}
ilbgateway version: version.BuildInfo{Version:"", GitRevision:"", User:"", Host:"", GolangVersion:"", DockerHub:"", BuildStatus:"", GitTag:""}
ingressgateway version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-17-g2b13318"}
ingressgateway version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-17-g2b13318"}
nodeagent version: version.BuildInfo{Version:"", GitRevision:"", User:"", Host:"", GolangVersion:"", DockerHub:"", BuildStatus:"", GitTag:""}
nodeagent version: version.BuildInfo{Version:"", GitRevision:"", User:"", Host:"", GolangVersion:"", DockerHub:"", BuildStatus:"", GitTag:""}
nodeagent version: version.BuildInfo{Version:"", GitRevision:"", User:"", Host:"", GolangVersion:"", DockerHub:"", BuildStatus:"", GitTag:""}
nodeagent version: version.BuildInfo{Version:"", GitRevision:"", User:"", Host:"", GolangVersion:"", DockerHub:"", BuildStatus:"", GitTag:""}
pilot version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
pilot version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
policy version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
policy version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
sidecar-injector version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
telemetry version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
telemetry version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.7", GitCommit:"65ecaf0671341311ce6aea0edab46ee69f65d59e", GitTreeState:"clean", BuildDate:"2019-01-24T19:22:45Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
via helm template 

**Environment**
AWS

**Cluster state**
Will provide if necessary, but dump script doesnt work with multiple pilot pods.

**Comment by carvercj** [comment]
We're seeing this too. Any workarounds?

**Comment by neiltoshten** [comment]
If you specify the meta data IP using CIDR notation, that should fix it for you. See the documentation here: https://istio.io/docs/reference/config/networking/v1alpha3/service-entry/#ServiceEntry.

**Comment by Jonathan34** [comment]
@neiltoshten i have the same issue upgrading from 1.0.6 to 1.1.6. I did not see any mention about this breaking change and i ran the google tool to ensure the cluster is ready for upgrade but it s apparently not checking service entries.

for google metadata server, i did the following:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: whitelist-egress-googleapis
spec:
  hosts:
    - "metadata.google" # GCE metadata server
    - "metadata.google.internal" # GCE metadata server
    - "accounts.google.com" # Used to get token
    - "*.googleapis.com"
  addresses:
    - 169.254.169.254 # GCE metadata server
  ports:
    - number: 80
      protocol: HTTP
      name: http
    - number: 443
      protocol: HTTPS
      name: https
```
but for single ip service entries, i am not sure what it needs in the hosts since it is required:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: whitelist-cloudsql-egress
spec:
  hosts:
    - w.x.y.z
  addresses:
    - w.x.y.z/32
```

**Comment by htsili** [comment]
@Jonathan34 
I think something like that will work
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: kube2iam
spec:
  hosts:
  - example.com
  addresses:
  - 169.254.169.254/32
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: NONE
  location: MESH_EXTERNAL
```

**Comment by Jonathan34** [comment]
> @Jonathan34
> I think something like that will work
> 
> ```yaml
> apiVersion: networking.istio.io/v1alpha3
> kind: ServiceEntry
> metadata:
>   name: kube2iam
> spec:
>   hosts:
>   - example.com
>   addresses:
>   - 169.254.169.254/32
>   ports:
>   - number: 80
>     name: http
>     protocol: HTTP
>   resolution: NONE
>   location: MESH_EXTERNAL
> ```

What if i dont have a example.com domain for it? i m trying to connect to a public cloudsql instance.
It seems it will be ignored when connection is TCP. I am deploying and will test soon.

**Comment by linsun** [comment]
In this case, would a `hosts: *` work when you just have IP but don't have a domain ?

@frankbu @hzxuzhonghu - I think we tightened up checking for hosts in 1.1. Thoughts?

cc @mbanikazemi @howardjohn

**Comment by Jonathan34** [comment]
@linsun `admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: invalid host *`
if i put 'foobar' as host, it creates the entry (have yet to try if it works)

**Comment by frankbu** [comment]
You should use the `addresses` field to set the IP. When `addresses` is set, `hosts` is ignored, so it can be any hostname you like. I wonder why we don't just make hosts optional, and generate some name in this case?

^^^ @rshriram

**Comment by howardjohn** [comment]
@frankbu the host name is not fully ignored, our docs are not entirely correct. I think it is used to match VS at the very least. See https://github.com/istio/api/pull/932.

**Comment by Jonathan34** [comment]
i can confirm what @howardjohn says:
```
2019-05-31T21:40:29.005021Z    info    parseHostname(unused) => error missing service name and namespace from the service hostname "unused"
```
I set `unused` but it still does something with it. It seems the serviceentry works though with such host. So it's parsed but not used.

There is still some other breaking changes related to ServiceEntry that I have not identified yet.
The following service entry works in istio 1.0.6 but generates ECONNRESET with istio 1.1.3.
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: whitelist-egress-cosmosdb
spec:
  hosts:
    - <xyz>.documents.azure.com
  ports:
    - number: 443
      protocol: HTTPS
      name: https
```
I updated it to the below and at least it does not complain anymore about the connection but any query to my service returns 503, no healthy upstream.
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: whitelist-egress-cosmosdb
spec:
  hosts:
    - <xyz>.documents.azure.com
  ports:
    - number: 443
      protocol: TLS
      name: https
  resolution: NONE
  location: MESH_EXTERNAL
```
This is a Azure CosmosDB instance using Gremlin Graph API... may be some can share some lights here?

**Comment by Jonathan34** [comment]
@mbanikazemi @howardjohn @frankbu @linsun would you please provide some guidance on how to debug that on istio 1.1.3?

**Comment by frankbu** [comment]
@Jonathan34 Have you tried using Istio 1.1.7? On Istio 1.1.4+ you should be able to access the db even without a ServiceEntry. See: https://istio.io/docs/tasks/traffic-management/egress/#envoy-passthrough-to-external-services

**Comment by Jonathan34** [comment]
@frankbu i'm using the GKE-managed istio addon. So I cannot really control the version... I am fine in providing a serviceentry and i think it s aogod practice to exaustively whitelist the egress traffic, but i can't understand what changed between istio 1.06 and 1.1.3 that either break the service entry i had or make it incomplete.

**Comment by frankbu** [comment]
I don't think this is supposed to have changed, but maybe there's a bug in 1.1.3???
Does this example work in your env: https://istio.io/docs/tasks/traffic-management/egress/#access-an-external-https-service?
If it does, can you do the same thing using your db URL and see what it has in the logs?

**Comment by kunickiaj** [comment]
Using a dummy hostname as suggested in the thread is working for me on GKE
with managed Istio 1.1.3.

**Comment by Jonathan34** [comment]
@frankbu 
it does not behave the same way as the documentation.... I scripted the commands run in the documentation and the behavior is different. see below the commands and output.
the namespace default is empty.

```
--> Applying resources...
serviceaccount/sleep unchanged
service/sleep unchanged
deployment.extensions/sleep configured

--> Waiting...

-->SOURCE_POD=sleep-654d99c54c-snc98
kubectl get configmap istio -n istio-system -o yaml | grep -o "mode: ALLOW_ANY"
mode: ALLOW_ANY
mode: ALLOW_ANY

-->Make a couple of requests to external HTTPS services from the SOURCE_POD to confirm successful 200 responses
command terminated with exit code 51
command terminated with exit code 51

-->Make a couple of requests to external HTTPS services from SOURCE_POD to verify that they are now blocked
command terminated with exit code 51
command terminated with exit code 51

-->Accessing an external HTTP service - creating service entry on port 80
serviceentry.networking.istio.io/httpbin-ext created

--> Waiting...

-->kubectl exec -it sleep-654d99c54c-snc98 -c sleep -- curl http://httpbin.org/headers

-->kubectl logs sleep-654d99c54c-snc98 -c istio-proxy | tail
[2019-06-04 18:09:53.922][11][warning][config] [external/envoy/source/server/listener_manager_impl.cc:307] adding listener '0.0.0.0:443': filter chain match rules require TLS Inspector listener filter, but it isn't configured, trying to inject it (this might fail if Envoy is compiled without it)
2019-06-04T18:09:55.379488Z	info	Envoy proxy is ready
[2019-06-04 18:39:02.258][11][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:86] gRPC config stream closed: 13,
[2019-06-04 18:39:02.591][11][warning][misc] [external/envoy/source/common/protobuf/utility.cc:174] Using deprecated option 'envoy.api.v2.Listener.use_original_dst' from file lds.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details.
[2019-06-04 19:09:49.921][11][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:86] gRPC config stream closed: 13,
[2019-06-04 19:09:50.204][11][warning][misc] [external/envoy/source/common/protobuf/utility.cc:174] Using deprecated option 'envoy.api.v2.Listener.use_original_dst' from file lds.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details.
[2019-06-04 19:39:26.529][11][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:86] gRPC config stream closed: 13,
[2019-06-04 19:39:27.064][11][warning][misc] [external/envoy/source/common/protobuf/utility.cc:174] Using deprecated option 'envoy.api.v2.Listener.use_original_dst' from file lds.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details.
[2019-06-04 20:08:24.005][11][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:86] gRPC config stream closed: 13,
[2019-06-04 20:08:24.345][11][warning][misc] [external/envoy/source/common/protobuf/utility.cc:174] Using deprecated option 'envoy.api.v2.Listener.use_original_dst' from file lds.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details.

-->kubectl -n istio-system logs -l istio-mixer-type=telemetry -c mixer | grep 'httpbin.org'

-->Access an external HTTPS service - creating service entry om port 443
serviceentry.networking.istio.io/google created

--> Waiting...

-->kubectl exec -it $SOURCE_POD -c sleep -- curl -I https://www.google.com | grep  "HTTP/"
command terminated with exit code 51

-->kubectl logs $SOURCE_POD -c istio-proxy | tail
[2019-06-04 18:09:53.922][11][warning][config] [external/envoy/source/server/listener_manager_impl.cc:307] adding listener '0.0.0.0:443': filter chain match rules require TLS Inspector listener filter, but it isn't configured, trying to inject it (this might fail if Envoy is compiled without it)
2019-06-04T18:09:55.379488Z	info	Envoy proxy is ready
[2019-06-04 18:39:02.258][11][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:86] gRPC config stream closed: 13,
[2019-06-04 18:39:02.591][11][warning][misc] [external/envoy/source/common/protobuf/utility.cc:174] Using deprecated option 'envoy.api.v2.Listener.use_original_dst' from file lds.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details.
[2019-06-04 19:09:49.921][11][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:86] gRPC config stream closed: 13,
[2019-06-04 19:09:50.204][11][warning][misc] [external/envoy/source/common/protobuf/utility.cc:174] Using deprecated option 'envoy.api.v2.Listener.use_original_dst' from file lds.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details.
[2019-06-04 19:39:26.529][11][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:86] gRPC config stream closed: 13,
[2019-06-04 19:39:27.064][11][warning][misc] [external/envoy/source/common/protobuf/utility.cc:174] Using deprecated option 'envoy.api.v2.Listener.use_original_dst' from file lds.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details.
[2019-06-04 20:08:24.005][11][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:86] gRPC config stream closed: 13,
[2019-06-04 20:08:24.345][11][warning][misc] [external/envoy/source/common/protobuf/utility.cc:174] Using deprecated option 'envoy.api.v2.Listener.use_original_dst' from file lds.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details.

-->kubectl -n istio-system logs -l istio-mixer-type=telemetry -c mixer | grep 'www.google.com'

-->cleanup
serviceentry.networking.istio.io "httpbin-ext" deleted
serviceentry.networking.istio.io "google" deleted
```

**Comment by frankbu** [comment]
In that case, I think you must have some kind of bad configuration in your cluster that is interfering with outgoing calls. Do you have any other ServiceEntry or DestinationRules defined? Are you running Istio with PERMISSIVE or STRICT auth?

I would suggest trying again using a clean cluster.

**Comment by Jonathan34** [comment]
> . Do you have any other ServiceEntry or DestinationRules defined

I have other service entries for CloudSQL, one for some internal appspot urls, and one for google metadata server. I am using Permissive.  
I just tried to disable/uninstall istio and reinstall using GKE commands but that does not really fix anything.

It seems what fixes it is to have the Gateway resource in the same namespace as the service entries (i am not using default). That used to work fine in 1.0.6.
[Documentation](https://istio.io/docs/reference/config/networking/v1alpha3/gateway/) says it `It is recommended that the Gateway resource reside in the same namespace as the gateway workload. This may become a requirement in the future.`

**Comment by chrisob** [comment]
Seeing this issue in 1.2 also: 

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: aws-metadata
spec:
  endpoints:
    - address: 169.254.169.254
  hosts:
    - 169.254.169.254
  location: MESH_EXTERNAL
  ports:
    - name: http
      number: 80
      protocol: HTTP
  resolution: STATIC
```

**Comment by howardjohn** [comment]
You need to set a hostname, but what it is doesn't really matter for these cases which is a bit confusing. https://github.com/istio/api/pull/932 just landed which improves the docs. Basically, the hostname is used to match the serviceentry to DestinationRules and VirtualServices, but otherwise isn't needed.

This change is expected and documented (well, it should be now at least :slightly_smiling_face: ).

Is there anything else we need to do here? In retrospect this should have been in the release notes probably, as some other users ran into this as well

**Comment by kbruner** [comment]
I still haven't found a permutation that works in 1.2.0.  Previously, was using this in GKE on Istio up to 1.1.8:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: gce-metadata
spec:
  hosts:
  - metadata.google.internal # not used with addresses
  addresses:
  - 169.254.169.254
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: STATIC
  location: MESH_EXTERNAL
  endpoints:
  - address: 169.254.169.254
```

That still passes the validation, but doesn't work.  I've tried appending a `/32` to the `addresses:` line, but that apparently gets evaluated in a way that the validator thinks there's no change and discards te edit.  I added a suffix to the port name to force a change, but I still get 403 in the application container.  Dropping the `endpoints` attribute and changing `resolution` to `NONE` also doesn't work.  Putting the `endpoints` back and changing `resolution` to `DNS` also didn't work.  I'm sure that the endpoint is available because if I exec into the `istio-proxy` container instead, I can curl it just fine.

(Note that this is for a freshly-deployed cluster, not upgraded from 1.1.x.) 

Does anyone have something that actually works with Istio 1.2.0?  And could we get that added as an example to the `ServiceEntry` page since that's going to be a very popular use case and would work in both GKE and AWS EC2?

**Comment by kbruner** [comment]
I did spend a little more time looking here.  `istioctl authn tls-check` for the service that needs to connect to the metadata endpoint does return the following:

```metadata.google.internal:80                                   CONFLICT     mTLS          HTTP       default/                                     gce-metadata/stackrox```

Note there was no change in mTLS auth (required by default), outbound traffic policy (REGISTRY_ONLY) from the 1.1.8 installation to 1.2.0.    Already for Istio 1.1.x, we also had a DestinationRule:

```apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: gce-metadata
spec:
  host: metadata.google.internal
  trafficPolicy:
    tls:
      mode: DISABLE
```

**Comment by Jonathan34** [comment]
These are the types of error i get using 1.2.0:
```html
2019/06/26 08:37:05 rpc error: code = Unauthenticated desc = transport: compute: Received 403 `<!DOCTYPE html>
<html lang=en>
<meta charset=utf-8>
<meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
<title>Error 403 (Forbidden)!!1</title>
<style>
*{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7%!a(MISSING)uto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100%!p(MISSING)x no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0%/100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100%}}#logo{display:inline-block;height:54px;width:150px}
</style>
<a href=//www.google.com/><span id=logo aria-label=Google></span></a>
```

and if I put my destination rule in the namespace i get this:
```html
2019/06/26 08:41:32 rpc error: code = Unauthenticated desc = transport: compute: Received 403 `<!DOCTYPE html>
<html lang=en>
<meta charset=utf-8>
<meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
<title>Error 403 (Forbidden)!!1</title>
<style>
*{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7%!a(MISSING)uto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100%!p(MISSING)x no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0%/100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100%}}#logo{display:inline-block;height:54px;width:150px}
</style>
<a href=//www.google.com/><span id=logo aria-label=Google></span></a>
```

below are my definition (namespace for service entry do not seem to have any effect n the behavior):
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: whitelist-egress-googleapis
  # namespace: development
spec:
  hosts:
    - "*.googleapis.com"
    - "accounts.google.com"
  ports:
    - number: 443
      name: https
      protocol: HTTPS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: whitelist-egress-google-metadata-server
  # namespace: development
spec:
  hosts:
    - metadata.google.internal
  addresses:
    - 169.254.169.254
  ports:
    - number: 80
      name: http
      protocol: HTTP
    - number: 443
      name: https
      protocol: HTTPS
  resolution: DNS
  endpoints:
    - address: 169.254.169.254
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: gce-metadata-internal
  namespace: development
spec:
  host: metadata.google.internal
  trafficPolicy:
    tls:
      mode: DISABLE
```

**Comment by frankbu** [comment]
@kbruner The TLS conflict seems to imply that your DestinationRule isn't being found. Note that the scope of visibility has been tightened up recently. It won't be found in just any namespace. The search path is: 1. client namespace, 2. service namespace, 3. istio-system. If it's in any other namespace it won't be used.

**Comment by kbruner** [comment]
@frankbu In my case, the ServiceEntry, DestinationRule and Deployment are all in the same namespace.

**Comment by Jonathan34** [comment]
i managed to get it working using the below and I don't get 403 anymore:
PS: i am not using workload identity
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: metadata-google-internal
spec:
  hosts:
    - metadata.google.internal
  http:
    - route:
        - destination:
            host: metadata.google.internal
          headers:
            request:
             remove:
                - x-forwarded-for
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: metadata-google-internal
spec:
  hosts:
    - metadata.google.internal
  addresses:
    - 169.254.169.254
  ports:
    - name: http
      number: 80
      protocol: HTTP
    - name: https
      number: 443
      protocol: HTTPS
  location: MESH_INTERNAL
  resolution: DNS
```

**Comment by frankbu** [comment]
Are you sure the `x-forwarded-for` header is the problem? I'm wondering if the problem is visibility of the `DestinationRule` when there's no `VirtualService`. If you just add a NOOP `VirtualService` that simply forwards to the same host (i.e., take out the `headers` part, does that work too?

**Comment by Jonathan34** [comment]
> Are you sure the `x-forwarded-for` header is the problem? I'm wondering if the problem is visibility of the `DestinationRule` when there's no `VirtualService`. If you just add a NOOP `VirtualService` that simply forwards to the same host (i.e., take out the `headers` part, does that work too?

I do not have any `DestinationRule` anymore; I opened 80 and 443 to make the access happy although metadata only access 80.

**Comment by howardjohn** [comment]
@frankbu the x forwarded for header was changed in 1.2.0 which causes this issue, Here is the PR with merge resolved. https://github.com/istio/istio/pull/15167 reverts it which fixes the issue. I tested this by manual curling with x forwarded for (not through envoy) and it fails

**Comment by Jonathan34** [comment]
> @frankbu the x forwarded for header was changed in 1.2.0 which causes this issue, Here is the PR with merge resolved. #15167 reverts it which fixes the issue. I tested this by manual curling with x forwarded for (not through envoy) and it fails

Google support mentioned a fix is in preparation for 1.2.2 and being tested. Now i don't know if the fix means revert. Just FYI
Having an example from istio team is required now, we are all losing time deploying istio on GKE and using GCP services because of the lack of examples and guidance from the Google/Istio team. So it will be highly appreciated to have a recommended approach for that metadata access

**Comment by cagataygurturk** [comment]
As of 1.4.5, the ServiceEntry below allows access for **both** http://169.254.169.254 and http://metadata.google.internal

`````yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: gke-metadata-server
spec:
  hosts:
    - metadata.google.internal
  addresses:
    - 169.254.169.254
  ports:
    - name: http
      number: 80
      protocol: http
  resolution: STATIC
  location: MESH_EXTERNAL
  endpoints:
    - address: 169.254.169.254
`````
