### ISSUE TITLE
A ServiceEntry from one namespace can interfere with the traffic of another namespace

### ISSUE THREAD

**Issue by uk000** [istio/istio#13008]
**Describe the bug**
As of Istio 1.1.1, anybody can create a ServiceEntry in one's own namespace to interfere with or hijack traffic of all other namespaces for a certain host.
The hijacked traffic can be routed to another external destination, or to some internal kubernetes service. Even if we ignore the possibility of a malicious intent, this leaves the door open for a simple mistake to disrupt production traffic for crucial applications.

In some ways, this issue is in the same league as #12144 which was in the context of DestinationRule interfering with unrelated namespaces.

**Expected behavior**
A ServiceEntry should only take effect in the namespace where it is defined, and not apply to all namespaces in the cluster. That way, whether by malicious intent or honest mistake, a user can only disrupt traffic of one's own namespace and not for the whole cluster.

**Steps to reproduce the bug**
1. Given two namespaces client-ns-1 and client-ns-2, both running some client deployment that provides curl (e.g. sleep or testcurl).
Also given there's an external application accessible at some fqdn or IP address

Initially neither clients can access kubeman.com.

2. Create a ServiceEntry in client-ns-1 to enable access to the external service

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: kubeman-ext
spec:
  exportTo:
    - "."
  hosts:
  - kubeman.com
  ports:
  - number: 80
    name: http-kubeman-80
    protocol: HTTP
  location: MESH_EXTERNAL
  resolution: DNS
  endpoints:
  - address: kubeman.com
  ```

Now verify that client-ns-1 can access the external service. Note that this client-1 created this ServiceEntry for its own local namespace. Other possible variations in this step: 
- Use STATIC resolution with IP address instead of DNS
- export ServiceEntry to all namespaces instead of client-ns-1 only  

3. Now client-2 creates a ServiceEntry to route domain kubeman.com to somewhere else, basically hijacking the domain

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: kubeman-to-google
spec:
  hosts:
  - kubeman.com
  ports:
  - number: 80
    name: http-kubeman-80
    protocol: HTTP
  location: MESH_EXTERNAL
  resolution: DNS
  endpoints:
  - address: google.com
  ```

Now the requests from any namespace to kubeman.com are randomly routed to either kubeman.com or google.com

4. Alternately, traffic can be hijacked to route to an internal kubernetes service

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: kubeman-int
spec:
  hosts:
  - kubeman.com
  ports:
  - number: 80
    name: http-kubeman-80
    protocol: HTTP
  location: MESH_INTERNAL
  resolution: DNS
  endpoints:
  - address: nginx.svc-sc-nomtls-1.svc.cluster.local
```

5. Additionally, traffic can be disrupted for an internal service if a rogue ServiceEntry gets created hijacking the internal service FQDN. In this case the traffic doesn't get routed to the new destination, but seems to be simply disrupted with envoy returning 503 "UH".
To achieve this, create a ServiceEntry using the internal service fqdn as "host" and attempt to send the traffic elsewhere:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: good-to-bad
spec:
  hosts:
  - good-service.good-namespace.svc.cluster.local
  ports:
  - number: 80
    name: http-80
    protocol: HTTP
  location: MESH_INTERNAL
  resolution: DNS
  endpoints:
  - address: bad-service.bad-namespace.svc.cluster.local
    weight: 100
```

Overall, what I found strange in my testing is that the behavior is not consistent. It seems like a case of eventual consistency or last-write-wins, or some other logic is in play. Sometimes the creation of conflicting ServiceEntry hijacks traffic completely, whereas other times it only hijacks it randomly (e.g. 50-50 split if no weights are specified in the ServiceEntry). And then at times the behavior is that it doesn't hijack traffic for the existing pods, but does hijack it if either a pod is rescheduled or if the original (first) ServiceEntry is redeployed for some reason (e.g. some changes in the first ServiceEntry). Upon redeployment, suddenly the 2nd ServiceEntry takes over and hijacks traffic.

**Version**

```
client version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-17-g2b13318"}
citadel version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
galley version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
ingressgateway version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-17-g2b13318"}
nodeagent version: version.BuildInfo{Version:"", GitRevision:"", User:"", Host:"", GolangVersion:"", DockerHub:"", BuildStatus:"", GitTag:""}
pilot version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
policy version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
sidecar-injector version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
telemetry version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
```

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
Using helm template

**Environment**
kubernetes on docker-for-mac

**Cluster state**

**Comment by uk000** [comment]
Updated the bug description to add another scenario (step #5), where a ServiceEntry can disrupt traffic going to an internal service.

**Comment by costinm** [comment]
Sidecar is required to enable isolation - for backward compat we didn't enable isolation if Sidecar is not used ( since we don't know which namespace to use )

**Comment by uk000** [comment]
The behavior was the same with or without using Sidecar resource. TBH, I don't fully understand why would a sidecar resource make a difference with this issue. Isn't the sidecar resource primarily meant to restrict/allow egress routes to specific hosts? Sidecar doesn't really affect the destinations of routes.

**Comment by howardjohn** [comment]
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin-a
  namespace: a
spec:
  hosts:
  - httpbin.org
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: wikipedia-b
  namespace: b
spec:
  hosts:
  - wikipedia.org
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL---
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: sidecar
spec:
  egress:
    - hosts:
      - ./*
      - istio-system/*
---
```

`istioctl pc clusters` shows no wikipedia entry.


But, we change it to the interfering with traffic like in description

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: wikipedia-b
  namespace: b
spec:
  hosts:
  - httpbin.org
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL
  endpoints:
  - address: wikipedia.org
```

And now I see routing to wikipedia and httpbin.

`istioctl pc clusters` shows:
```json
[
    {
        "name": "outbound|80||httpbin.org",
        "type": "STRICT_DNS",
        "connectTimeout": "1s",
        "loadAssignment": {
            "clusterName": "outbound|80||httpbin.org",
            "endpoints": [
                {
                    "lbEndpoints": [
                        {
                            "endpoint": {
                                "address": {
                                    "socketAddress": {
                                        "address": "wikipedia.org",
                                        "portValue": 80
                                    }
                                }
                            },
                            "loadBalancingWeight": 1
                        },
                        {
                            "endpoint": {
                                "address": {
                                    "socketAddress": {
                                        "address": "httpbin.org",
                                        "portValue": 80
                                    }
                                }
                            },
                            "loadBalancingWeight": 1
                        }
                    ]
                }
            ]
        },
        "circuitBreakers": {
            "thresholds": [
                {
                    "maxRetries": 1024
                }
            ]
        },
        "dnsRefreshRate": "5s",
        "dnsLookupFamily": "V4_ONLY"
    }
]
```

Seems to be a clear bug. @costinm

**Comment by hzxuzhonghu** [comment]
Isn't this expected, pilot merges the two service entries?

**Comment by howardjohn** [comment]
No we should not get services from other namespaces if we have Sidecar, for all the reasons mentioned in the issue.

**Comment by howardjohn** [comment]
Think I know what is happening. First we get all of the services exposed to the sidecar. Then, for each service, we look up instances by hostname. At this point, we can pull in entries from other namespaces. 
 See: https://github.com/istio/istio/blob/fdd6444d166e1c12e6ab48cffae8110b64ea26e6/pilot/pkg/networking/core/v1alpha3/cluster.go#L313

Seems like we would need pretty substantial changes in order to fix this. @rshriram any ideas?

**Comment by rshriram** [comment]
Few things:
 1. you can restrict the visibility of a service entry by declaring the service entry's `exportTo: '.'` . This will ensure that the service entry is visible only in the declaring namespace and not in others.
 2. Even when you do this exportTo stuff, you cannot have two service entries in the system with the same host. This is equivalent to having two google.coms in the service registry where each google.com points to something completely different. Such a thing is not possible in Istio today because the service registry is a map[hostnameFQDN->service]. Bad things will happen when you do this. 
 If you think about this, almost every service registry out there today (consul, zookeeper, eureka, etc.) all enforce uniqueness on the name lookup. Even inside kubernetes, you cannot have foo.ns1.svc.cluster.local inside ns1 and ns2 namespaces. k8s simply wont allow that by virtue of appending the unique namespace to the FQDN.

Perhaps what can be done is to add an additional check in the aggregate service registry and in external service registry (one processing service entries) to check for duplicates, and emit warnings.

**Comment by howardjohn** [comment]
Me and Shriram discussed this a bit offline. Adding the conversation here for others to comment.

Key points:
* My thoughts are that Sidecar should provide config isolation. In this case, we are pulling in config from other namespaces, which breaks this isolation. I think this is important because it limits our multi tenancy support.
* Shriram thinks this is expected because it breaks a fundamental concept that services can only be in one namespace. Violating this will break telemetry (not just mixer, but other systems as well like Datadog). We should only support multi-tenancy within the confines of basic concepts. Adding new abstractions for service registry will lead to too much complexity. Service entries should not be allowed to be created by teams, they are not routing related.
* Possible workaround is to add a validation rule to reject duplicate hosts.

cc @costinm @louiscryan

**Comment by costinm** [comment]
'exportTo' is not an option for security reasons. No namespace that is not explicitly imported should be able to affect the config of another namespace - clear security reasons. 

ServiceEntry is used for egress - so needs to be per-namespace

**Comment by howardjohn** [comment]
@costinm exportTo does not fix this either anyways, they will still be imported from other namespaces even if they have `exportTo: '.'`

**Comment by costinm** [comment]
Even if it fixes it (and it could be used) - it is still a security problem, because a namespace can interfere with a different one and inject an egress.

We can restrict the ServiceEntry for "foo.bar.cluster.local" to only be accepted in "bar" namespace - 
i.e. service can only be defined in its own namespace, like in K8S. 
But the egress ( www.example.com ) should not be picked from a random namespace that is not 
imported.

**Comment by costinm** [comment]
Also: validation rule doesn't work either - it is legitimate for 2 namespaces to define their own view of an egress.

**Comment by louiscryan** [comment]
@rshriram I disagree a bit with your points above.

We introduced namespace scoping of service references to avoid collisions like this. That feature also explicitly allows for split horizons across namespaces so service resolution can't simply be

map[hostnameFQDN->service]

its really map[hosnameFQDN, namespace-> service]

otherwise we'd have to treat services in the same namespace equivalently with services in other namespace when consuming them.  The old behavior is because we by default treat service references as 

*/host-name

but that isn't safe for large deployments. We need to respect scoped references otherwise they won't meet user expectations

**Comment by rshriram** [comment]
what happens if I declare a serviceEntry in my local namespace like this:
```
ServiceEntry:
 name: hack
 namespace: mybroken-namespace
host: someBigService.namespaceIdontHaveaccess.svc.cluster.local
address: 127.255.1.3 or my pod IP
ports:
  same ports as someBigService
```

such that I can hijack all traffic bound for this someBigService by declaring a namespace local service entry, and start discovering what traffic is being sent to that service?

Today, this wont work (mostly) in our system because this service is always keyed by the hostname and the hostname will already exist in k8s service registry, such that the service specs from another namespace will be ignored.
