### ISSUE TITLE
Unvalid endpoint error when creating the Service Entry for Gateway-Connected Clusters

### ISSUE THREAD

**Issue by yuchen9459** [istio/istio#13021]
**Describe the bug**
I am following the Gateway-Connected Clusters tutorial in the example. Everything goes well until I create the Service Entry, I received an error which states that 

> error when creating "STDIN": admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: endpoint address "172.17.0.4:31380" is not a valid FQDN or an IP address

**Steps to reproduce the bug**
1. Create two kind(Kubernetes in the docker) using the script from [Kubernetes Federation V2](
        https://github.com/kubernetes-sigs/federation-v2/blob/master/scripts/create-clusters.sh#L117
      ) 
2. Deploy the Istio Control Plane in each cluster. Since the kind cluster does not support external Load Balancer, I have changed the type of ingress-gateway to NodePort.
3. Deploy the sleep and httpbin service in two clusters. 
4. Export the cluster gateway address following the steps in [Determining the ingress IP and ports when using a node port](https://istio.io/docs/tasks/traffic-management/ingress/#determining-the-ingress-ip-and-ports-when-using-a-node-port). The command I used are:

`export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].nodePort}')`
`export INGRESS_HOST=$(kubectl get po -l istio=ingressgateway -n istio-system -o jsonpath='{.items[0].status.hostIP}')`
`export CLUSTER2_GW_ADDR=$INGRESS_HOST:$INGRESS_PORT`

5. Run command to create the Service Entry
 ```
kubectl apply --context=$CTX_CLUSTER1 -n foo -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin-bar
spec:
  hosts:
  # must be of form name.namespace.global
  - httpbin.bar.global
  # Treat remote cluster services as part of the service mesh
  # as all clusters in the service mesh share the same root of trust.
  location: MESH_INTERNAL
  ports:
  - name: http1
    number: 8000
    protocol: http
  resolution: DNS
  addresses:
  # the IP address to which httpbin.bar.global will resolve to
  # must be unique for each remote service, within a given cluster.
  # This address need not be routable. Traffic for this IP will be captured
  # by the sidecar and routed appropriately.
  - 127.255.0.2
  endpoints:
  # This is the routable address of the ingress gateway in cluster2 that
  # sits in front of sleep.foo service. Traffic from the sidecar will be
  # routed to this address.
  - address: ${CLUSTER2_GW_ADDR}
    ports:
      http1: 15443 # Do not change this port value
EOF
```
Then I got the error:

`Error from server: error when creating "STDIN": admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: endpoint address "172.17.0.4:31380" is not a valid FQDN or an IP address`

I have checked with command `kubectl get po -l istio=ingressgateway -n istio-system -o wide` that the ingressway is running.

```
NAME                                    READY   STATUS    RESTARTS   AGE   IP          NODE                     NOMINATED NODE   READINESS GATES
istio-ingressgateway-7b8686cbc5-kcqqq   1/1     Running   0          52m   10.32.0.7   cluster2-control-plane   <none>           <none>

```

May I ask what could be the reason for causing the error?

**Version**

Kubernetes Version:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-20T16:54:39Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**
Running on CentOS Server
