### ISSUE TITLE
istio-1.1.1 broke NONE service resolution entries

### ISSUE THREAD

**Issue by valarauca** [istio/istio#13039]
**Describe the bug**

Valid service configurations from `1.0.3` and `1.0.6` do not work in `1.1.1` 

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cassandra
  namespace: default
spec:
  hosts:
  - cassandra.default.svc.cluster.local
  addresses:
  - 10.126.0.109/32
  - 10.126.15.210/32
  - 10.126.15.211/32
  ports:
  - number: 7000
    name: tcp-7000
    protocol: TCP
  - number: 9042
    name: tcp-9042
    protocol: TCP
  - number: 9160
    name: tcp-9160
    protocol: TCP
  resolution: NONE
  location: MESH_INTERNAL
  endpoints:
  - address: 10.126.0.109
    ports:
      tcp-7000: 7000
      tcp-9042: 9042
      tcp-9160: 9160
  - address: 10.126.15.210
    ports:
      tcp-7000: 7000
      tcp-9042: 9042
      tcp-9160: 9160
  - address: 10.126.15.211
    ports:
      tcp-7000: 7000
      tcp-9042: 9042
      tcp-9160: 9160
```

This is to support a cassandra cluster which would be added to the `istio` service mesh via `envoy` and sidecar expansion. IP addresses need to be used instead of domain names as this is a legacy applications, and some management scripts prefer IP-Addresses. 

We are attempting to conform to the guidelines from the [NONE](https://istio.io/docs/reference/config/networking/v1alpha3/sidecar/#CaptureMode) documentation. Also the [ServiceEntry Address section](https://istio.io/docs/reference/config/networking/v1alpha3/sidecar/#CaptureMode) doesn't mention the incompatibility. 

Is `NONE` still supported in `1.1.1`?

**Expected behavior**

I expected I could still apply `YAML` that was used before. 

**Steps to reproduce the bug**

Have a `resolution: NONE` with a non-empty `addresses:` section. 

**Version**

```bash
kubectl --version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.7-gke.12", GitCommit:"06f08e60069231bd21bdf673cf0595aac80b99f6", GitTreeState:"clean", BuildDate:"2019-02-25T20:37:10Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

```bash
helm version
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
```

I have not completed my `istio` installation. 

**Installation**

```bash
kubectl apply -f istio-1.1.1/install/kubernetes/helm/helm-service-account.yaml`
helm init --service-account tiller
helm install istio-1.1.1/install/kubernetes/helm/istio-init --name istio-init --namespace istio-system
helm install istio-1.1.1/install/kubernetes/helm/istio --name istio --namespace istio-system ---set global.meshExpansion.enabled=true --set global.controlPlaneSecurityEnabled=true --set global.mtls.enabled=true 
```

**Environment**

* Debian Linux
* GCP
* GKE

**Cluster state**

This is a change to the validator not the cluster state?
