### ISSUE TITLE
ServiceRoleBinding subject user: allUsers no longer working

### ISSUE THREAD

**Issue by wp0pw** [istio/istio#13058]
**Describe the bug**
When configuring authorization with ServiceRole and ServiceRoleBinding I have following binding:

```
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: bind-echo-poster
  namespace: default
spec:
  subjects:
  - user: "*"
  roleRef:
    kind: ServiceRole
    name: "echo-poster"
---
```

which I expected to allow all users - authenticated and otherwise to post to my echo service, but I get `Origin authentication failed.` with HTTP code 401 instead.

I'm set up with authentication policy against the sample jwks:

```
origins:
  - jwt:
      issuer: "testing@secure.istio.io"
      jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.1/security/tools/jwt/samples/jwks.json"
  principalBinding: USE_ORIGIN
```

as soon as I add the token to the request I do get 200 response.

**Expected behavior**
I expected to get 200 response without providing the jwt token

**Steps to reproduce the bug**
Configure 'ServiceRole' targeting a service and bind with 'ServiceRoleBinding' as above - setting subject user to `*` and add authentication policy with origin as above. Then try to access the service without a valid jwt token.

**Version**
istio 1.1.0 and and kubernetes 1.10.11

**Installation**
istio installed with helm template and kubectl with following flags:

```
--set tracing.enabled=true 
--set grafana.enabled=true 
--set sidecarInjectorWebhook.rewriteAppHTTPProbe=true 
--set global.controlPlaneSecurityEnabled=true
```

**Environment**
k8s on docker (ce 2.0.0.3) for windows

**Cluster state**
