### ISSUE TITLE
Configure Mixer adapter instance and rules to deny requests on configuration failure

### ISSUE THREAD

**Issue by Daniel-Houston** [istio/istio#13068]
**Describe the feature request**
I have a custom authorization adapter configured which uses the authorization template. 

If I accidentally deploy the mixer instance with a bad configuration, mixer will log an error, but will ignore the mixer adapter on any requests matched by the rule.

I would like a way to configure istio to deny any requests if an adapter instance or rule is configured incorrectly. Essentially, if an adapter can't be reached, requests should be denied.

Here is a configuration with a bad template instance (see instance.spec.params.action.properties.headers):

```
# handler for bouncer adapter 
apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
 name: h1
 namespace: istio-system
spec:
 adapter: bouncer
 connection:
   address: "bouncer:8000" #replaces at runtime by the test
---
# instance for template authorization
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
  name: bouncer
  namespace: istio-system
spec:
  template: authorization
  params: 
    subject:
      user: request.auth.claims["sub"] | ""
      groups: request.auth.claims["groups"] | ""
      properties:
        iss: request.auth.claims["iss"] | ""
        cid: request.auth.claims["cid"] | ""
    action:
      namespace: destination.service.namespace | ""
      service: destination.service.name
      path:  request.path | ""
      method: request.method | ""
      properties:
        headers: request.headers

---
# rule to dispatch to handler h1
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
 name: r1
 namespace: istio-system
spec:
 match: "true"
 actions:
 - handler: h1.istio-system
   instances:
   - bouncer.istio-system
---
```
When I make a request with that bad config, the rule and instance are effectively ignored.

This is obviously dangerous if using the mixer check request to check for authorization
