### ISSUE TITLE
Impossible to establish external connection even by following the documentation

### ISSUE THREAD

**Issue by sneko** [istio/istio#13087]
Hi everyone,

I migrated to Istio 1.1 a few days ago and I noticed today that one of my microservice was no longer able to reach Google APIs.

I checked it really comes from Istio by creating the same deployment without Istio injection and the microservice is able to reach Google APIs.

My previous configuration about egress was:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: googleapis
spec:
  hosts:
  - "*.googleapis.com"
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
```

but since it's no longer working I checked a new time the documentation and it seems it's more appropriate to do the following (https://istio.io/docs/examples/advanced-gateways/wildcard-egress-hosts/):
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: googleapis
spec:
  hosts:
  - "*.googleapis.com"
  ports:
  - number: 443
    name: tls
    protocol: TLS
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: googleapis
spec:
  hosts:
  - "*.googleapis.com"
  tls:
  - match:
    - port: 443
      sniHosts:
        - "*.googleapis.com"
    route:
    - destination:
        host: "*.googleapis.com"
        port:
          number: 443
```

So do I, but I'm still unable to make my script working to communicate with Google APIs, I directly get this error from the Google library:
```
{ Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at TLSWrap.onread (net.js:618:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
```

Note that by connecting through SSH to my pod, I'm able to run the following and get content of the page:
`curl https://www.googleapis.com`

Do you have any idea what's missing to make it working please?

By looking at Istio 1.1 changelog I don't see what could have broken my Istio settings 🤔 

Thank you,

**Comment by esnible** [comment]
I tried to recreate your situation using Istio 1.1.1.  Before applying any Istio rules I did `curl -v https://www.googleapis.com` and got a "curl: (35) Unknown SSL protocol error".

I then applied this rule:

```
cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: googleapis
spec:
  hosts:
  - "*.googleapis.com"
  ports:
  - number: 443
    name: tls
    protocol: TLS
EOF
```

After application, the same _curl_ gave a 404 as expected.

**Comment by sneko** [comment]
Thanks @esnible for testing :) . But as I mentioned, after applying this ServiceEntry I'm indeed able to use the `curl` command from my Node.js pod. But the official Google APIs library that is run inside my JavaScript is not able to do is job while having the Envoy sidecar.

I don't understand why I'm having this kind of error (`ECONNRESET`) since I'm allowed all communcation with `*.googleapis.com`. Maybe some communications are still blocked by Istio?

How could I see each pod attempts that are catched by my sidecar? Like that I would be able to know which remaining domain is blocked to use Google APIs.

Thank you,

Note: it's working great without the sidecar

**Comment by esnible** [comment]
A great deal of logic is involved when pods communicate on port 443.  The application manages HTTP/TLS.  Envoy must peer into the encrypted traffic a little bit using SNI and make sure the traffic is passed unmodified to the correct destination.  This is tricky because there might be multiple destinations, and if any destination on port 443 doesn't have SNI in it's Istio rule it might capture some of the traffic.

First, verify everything works by testing that the Istio sidecar itself can reach the external service:

```
MYPOD=…
EXTERNAL_HOST=www.googleapis.com # or whatever
EXTERNAL_IP=$(nslookup $EXTERNAL_HOST | awk '/^Address: / { print $2 ; exit }')
HPATH=
PORT=443
kubectl exec $MYPOD -c istio-proxy -- curl -v https://$EXTERNAL_HOST/$HPATH --resolve "$EXTERNAL_HOST:$PORT:$EXTERNAL_IP" --insecure
```

Next, see what Envoy is logging about the failed connection following the example at https://istio.io/docs/tasks/telemetry/logs/access-log/ .  If Envoy is reporting that the certificates don't match it means that some other ServiceEntry or VirtualService on port 443 is getting the traffic.  Try adding `SNI` entries to the other rules to restrict what kinds of communication they manage.

**Comment by sneko** [comment]
Hi @esnible , 

After upgrading to 1.1.4 the work disappeared. I'm sorry I'm not able to explain why, I didn't modified the settings.

So now I'm able to reach Google APIs endpoints even without specifying any VirtualService with `outboundTrafficPolicy.mode: "REGISTRY_ONLY"`. But it means there is no restriction because all my microservices can reach Google APIs.

How could could I restrict that?

I tried to "scope" a VirtualService with `sourceLabels` but it doesn't seem to cancel the authorization for all:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: googleapis-sheet-api
  namespace: XXXXXXXX
spec:
  hosts:
  - "*.googleapis.com"
  tls:
  - match:
    - sourceLabels:
        app: app
      port: 443
      sni_hosts:
      - "*.googleapis.com"
    route:
    - destination:
        host: "*.googleapis.com"
        port:
          number: 443
```

Any idea please?

Thank you,
