### ISSUE TITLE
istio 1.0.6 virtual service can't match uri query section with regex

### ISSUE THREAD

**Issue by Frozen-Shadow** [istio/istio#13121]
**Describe the bug**
I want to control the traffic by [query parameters](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Examples). I have an URI like this `http://foo.bar/path?param=something`. My yaml file

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: foo-gateway
spec:
  gateways:
    - foo-gateway
  http:
    - match: 
        - uri:
              regex: something # I tried  `param=something`, `.*something.*`, `something` ...
      route:
        - destination:
            host: ahost
            subset: target-subset # I want this subset
            port:
              number: 80
   - route:
        - destination:
            host: ahost
            subset: default-subset
            port:
              number: 80
```
Through the [HTTPMatchRequest doc](https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#HTTPMatchRequest), I had tried `param=something`, `.*something.*`, `something` to get the  **target-subset**,  all of these had verified in [RegExr](https://regexr.com/). But none of these could get to the  **target-subset**.

By the way, I had tested `.*`,`.*path.*`, they all works. Is istio ignore the query section in URI ? If yes, can you write it in the documection.

Thanks.

**Expected behavior**
Get to the **target-subset** when I using regex to match query string.

**Version**
istio: 1.0.6
k8s: v1.9.10-r0-CCE2.0.12.B002-1-g30ab32284a000f

**Environment**
It is a service in HUAWEI cloud.
