### ISSUE TITLE
VirtualService timeout parameter doesn't work in Istio 1.1.2

### ISSUE THREAD

**Issue by codependent** [istio/istio#13144]
**Describe the bug**
I have installed Istio 1.1.2 on OpenShift 3.11.0. Things like balanced traffic work fine in VirtualServices. However timeouts are not enforced.

At first I was trying with my own application, and seeing it didn't work I tested with the BookInfo sample. I can confirm it doesn't work in these case either.

I have followed this task: https://istio.io/docs/tasks/traffic-management/request-timeouts/

My ratings VirtualService is:

```
spec:
  hosts:
  - ratings
  http:
  - fault:
      delay:
        fixedDelay: 2s
        percent: 100
    route:
    - destination:
        host: ratings
        subset: v1
```

As expected the request to /productpage takes around 2 seconds.

I modified the reviews VirtualService to:
```
spec:
  hosts:
  - reviews
  http:
  - route:
    - destination:
        host: reviews
        subset: v2
      timeout: 0.5s
```
**Expected behavior**
The request should stop in about 1 second, instead of 2, and the reviews should be unavailable

**Steps to reproduce the bug**
Follow the Bookinfo tutorial and the task https://istio.io/docs/tasks/traffic-management/request-timeouts/

**Version**
Istio: 1.1.2
Kubernetes: 1.11.0

**Installation**
Installed on Openshift following the documentation

**Environment**
AWS EC2 machines
Centos7
Okd (3.11)

**Comment by codependent** [comment]
My bad, the indentation wasn't correct:
```
spec:
  hosts:
  - reviews
  http:
  - route:
    - destination:
        host: reviews
        subset: v2
    timeout: 0.5s
```
