### ISSUE TITLE
mirrored requests doesn't apply consistent hashing (destination rules not applied)

### ISSUE THREAD

**Issue by nizamsp** [istio/istio#13179]
**Describe the bug**
consistent hash in destinationrule is not working in mirrored request but works in original request

**Expected behavior**
Both original and mirrored requests should have landed on the same pod applying the consistent hash

**Steps to reproduce the bug**
This issue was reproduced by slightly modifying the example giving in istio mirror.
https://istio.io/docs/tasks/traffic-management/mirroring/

```
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: user
```
Above lines in the httpbin-virtualservice.yml is the only new addition from the istio mirror example.

Bring up the following 5 yml files
```
 kubectl apply -f <(istioctl kube-inject -f httpbin-v1.yml)
 kubectl apply -f <(istioctl kube-inject -f httpbin-v2.yml)
 kubectl apply -f <(istioctl kube-inject -f httpbin-service.yml)
 kubectl apply -f <(istioctl kube-inject -f httpbin-virtualservice.yml)
 kubectl apply -f <(istioctl kube-inject -f sleep-pod.yml)
```
**httpbin-v1.yml**
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpbin-v1
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        command: ["gunicorn", "--access-logfile", "-", "-b", "0.0.0.0:80", "httpbin:app"]
        ports:
        - containerPort: 80

```
**httpbin-v2.yml**
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpbin-v2
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: httpbin
        version: v2
    spec:
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        command: ["gunicorn", "--access-logfile", "-", "-b", "0.0.0.0:80", "httpbin:app"] 
        ports:
        - containerPort: 80

```
**httpbin-service.yml**
```
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: httpbin
```
**httpbin-virtualservice.yml**
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
    - httpbin
  http:
  - route:
    - destination:
        host: httpbin
        subset: v1
      weight: 100 
    mirror:
      host: httpbin
      subset: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: httpbin
spec:
  host: httpbin
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: user
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
```
**sleep-pod.yml**
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sleep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
      - name: sleep
        image: tutum/curl
        command: ["/bin/sleep","infinity"]
        imagePullPolicy: IfNotPresent
```

**open logs in v1 and v2 pods**
```
kubectl logs -f <v1 pod-replica1> -c httpbin
kubectl logs -f <v1 pod-replica2> -c httpbin

kubectl logs -f <v2 pod-replica1> -c httpbin
kubectl logs -f <v2 pod-replica2> -c httpbin
```
**Fire the following curl**
```
export SLEEP_POD=$(kubectl get pod -l app=sleep -o jsonpath={.items..metadata.name})
kubectl exec -it $SLEEP_POD -c sleep -- sh -c 'curl -H "user: testing123"  http://httpbin:8000/headers' | python -m json.tool
```
Execute the above curl command for 3 or 4 times.. It will land in the same pod consistently using consistent hash in v1 but it will land on different pods in v2.

This shows that the consistent hash is not working on mirrored request. Not sure what we are doing wrong.

**Version**
```
$ istioctl version --remote
version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.1"}
Error: error execing into istio-citadel-7c4864c9d5-bgwhb citadel container: command terminated with exit code 255
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.7-gke.12", GitCommit:"06f08e60069231bd21bdf673cf0595aac80b99f6", GitTreeState:"clean", BuildDate:"2019-02-25T20:37:10Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}

```

**Installation**
GKE cluster with PERMISSIVE mode

**Environment**
GKE

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by philrud** [comment]
Confirming, I can reproduce the issue.

From what I tell right now, both mirroring and hash-based load balancing is handled by Envoy and is configured via the same RouteAction config: Envoy respects the "route.RouteAction.HashPolicy" for the destination cluster, but not for a cluster specified in the "route.RouteAction.RequestMirrorPolicy".

I'll keep investigating this further, looks like this will require a fix on Envoy side.

**Comment by GregHanson** [comment]
I wonder if this could be related to https://github.com/istio/istio/issues/13261
we are currently setting a bad (0) minimum ring size by default instead of the documented 1024.  PR's are open in master and release to resolve.  Can you verify the `0` value in your config_dump's?
```
        "ringHashLbConfig": {
            "minimumRingSize": "0"
        },
```

**Comment by philrud** [comment]
@GregHanson yes, I've got the following block in the configs:
```
"ring_hash_lb_config": {
  "minimum_ring_size": "0"
},
```
But I see this block on both clusters, yet LB works for the destination cluster, but not for the mirrored one. That issue wouldn't explain that, would it?

**Comment by philrud** [comment]
Tried flipping "minimumRingSize" to 1024 just in case. That didn't help unfortunately – the traffic on the mirror cluster still doesn't seem to respect the hashPolicy.

**Comment by jwendell** [comment]
Have you guys tried adding a destination rule for the mirror host? Something like:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: httpbin-shadow
spec:
  host: httpbin-shadow
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: user
```
