### ISSUE TITLE
Clarification for istio authentication policy with origin and peer mtls authentication

### ISSUE THREAD

**Issue by Daniel-Houston** [istio/istio#13188]
I am using istio deployed in a minikube cluster. I have created and deployed two services in the default namespace, an 'entitlements' service and an 'organizations' service. The 'organizations' service exposes and endpoint meant to be hit publicly. When that endpoint is called, organizations calls into the 'entitlements' service to get some information.

I want to have an authentication policy that requires origin authentication for requests coming from outside the cluster, and mtls for all requests machine-to-machine (peer authentication: orgs -> entitlemlents). 

This is the policy I have:

```
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "default"
  namespace: "default"
spec:
  origins:
  - jwt:
      issuer: "https://login-dev.solutionreach.com/oauth2/aushjaeb7yvgghqOU0h7"
      jwksUri: "https://solutionreach-test.oktapreview.com/oauth2/aushjaeb7yvgghqOU0h7/v1/keys"
      audiences:
      - "https://api.dev.srconnect.io"
  peers:
  - mtls: {}
  principalBinding: USE_ORIGIN
```
Before I added the 'peers' section of the config, I was able to make a request to the public endpoint fine using curl. However, once I added 'peers' into the Policy config, I started getting 503 responses with `upstream connect error or disconnect/reset before headers` in the body.

I expected that with that configuration, I would be able to make origin-authenticated calls, and that service-to-service calls would be authenticated via mtls, but what I think is happening is that now my origin-calls from outside the cluster are required to use mtls as well, is that correct?

How would I go about configuring origin authentication for requests coming from outside the cluster, and mtls for maching-to-machine authentication inside the cluster?

**Comment by Daniel-Houston** [comment]
What I want to do is have certain services that are publicly accessible, which use origin jwt authentication only, and then I want to have certain internal services which only communicate using mtls. The publicly accessible services will communicate with other internal services using only mtls. Is this possible?

**Comment by Daniel-Houston** [comment]
Any insight here? This seems like it should be a pretty common use case, I'm wondering what I've been missing

**Comment by yangminzhu** [comment]
> How would I go about configuring origin authentication for requests coming from outside the cluster, and mtls for maching-to-machine authentication inside the cluster?

In this case I think you can have 2 separate authentication policy, One enables mTLS for machine-to-machine inside the mesh, the other one enables the JWT policy on the Istio ingress gateway, assuming your publicly accessible services are exposed via the Istio ingress gateway.

/cc @diemtvu

**Comment by yangminzhu** [comment]
Assume you have configured the ingress gateway to expose your `svc-organizations` to public:
```
                     +-----------------------+         +-------------------+
  Request with JWT   |                       |         |                   |
+--------------------> Istio Ingress Gateway +--mTLS---> svc-organizations |
                     |                       |         |                   |
                     +-----------------------+         +------^------------+
                                                              |
                                                             mTLS
                                                              |
                                                              |
                                                       +------v------------+
                                                       |                   |
                                                       | svc-entitlements  |
                                                       |                   |
                                                       +-------------------+

```

You can have the following two authentication policy for your purpose:
```
# This enables the JWT authentication on istio ingress gateway 
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "default"
  namespace: "istio-system"
spec:
  targets:
  - name: istio-ingressgateway
  origins:
  - jwt:
      issuer: "https://login-dev.solutionreach.com/oauth2/aushjaeb7yvgghqOU0h7"
      jwksUri: "https://solutionreach-test.oktapreview.com/oauth2/aushjaeb7yvgghqOU0h7/v1/keys"
      audiences:
      - "https://api.dev.srconnect.io"
  principalBinding: USE_ORIGIN
```

```
# This enables mTLS for the default namespace
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "default"
  namespace: "default"
spec:
  peers:
  - mtls: {}
```

If you don't want to use istio ingress gateway and want to expose your service directly to public, one possible way it to make the mTLS permissive which means to allow mTLS and plaintext traffic at the same time. So that the request sent from outside won't need to use mTLS. And to only enable the JWT requirements on external requests, you may need to use the Istio authorization policy to enforce access control on requests from outside of the cluster.
Overall this makes things quite complicated and reduce the security (as you will need to use the permissive mTLS)
