### ISSUE TITLE
Redis Protocol Support

### ISSUE THREAD

**Issue by ramaraochavali** [istio/istio#13200]
**Describe the feature request**
Currently when we deploy redis service with the following service object,
```
kind: Service
apiVersion: v1
metadata:
  name: redis
  labels:
    app: redis
    visualize: "true"
spec:
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  selector:
    app: redis
```
Istio, generates clusters and listeners for `TCP` - While it may allow redis protocol to flow through Mesh from source -> destination, it does not do any sharding (using `RING_HASH` or `MAGLEV` as Load balancing options for the upstream cluster) and does not take advantage of `envoy.redis_proxy` network filter as well.

This feature request is for Istio to natively support redis protocol on Mesh by creating 

- Upstream Clusters with `RING_HASH` or `MAGLEV ` - We can make it configurable via some API or mesh wide config
- Create Egress/Ingress Listeners using `envoy.redis_proxy`.
when the service entry specifies `redis` as the protocol name.

If this breaks any existing assumptions/use cases, we can make this behaviour configurable.

**Describe alternatives you've considered**
There are no alternatives.
