### ISSUE TITLE
Virtual Service updates are not propagating via `kubectl` 

### ISSUE THREAD

**Issue by zparnold** [istio/istio#13218]
**Background**
We upgraded over the weekend from Istio 1.0.2 to 1.1.2 due to the CVE. So we believe the issue is either with our configuration...or possibly with values that are now out of date WRT to the new Istio version

**Describe the bug**
Using the following DR + VS Combo we are expecting that the Istio ingressgateway will shift traffic from one deployment (defined via a subset) to another in Kubernetes:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: manager-blue-green
  namespace: acceptance
spec:
  host: ygrene-manager-service
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
  subsets:
    - name: blue
      labels:
        deployment: blue
    - name: green
      labels:
        deployment: green
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: manager-service-acceptance
spec:
  hosts:
    - "ops.acceptance.ygreneworks.com"
  gateways:
    - istio-system/kube-gateway
  http:
    - route:
        - destination:
            port:
              number: 80
            host: ygrene-manager-service.acceptance.svc.cluster.local
            subset: blue
      retries:
        attempts: 3
        perTryTimeout: 2s
```
We expect that to propagate in less than 1 minute to all sidecars (we have a smaller deployment < 100 nodes) or at least have similar behavior to Istio 1.0.2. What we observe is that the update never fully propagates...and for some reason restarting the Pilot pods will occasionally fix this issue.

**Expected behavior**
It to work as designed (begin switching traffic from one subset to another.) 

**Steps to reproduce the bug**
Add the two manifests above and two separate deployments and use `kubectl` to change the `subset` of the VirtualService from Blue to Green or vice versa.

**Version**
Istio 1.1.2

**Installation**
1.0.2 was installed with Helm
1.1.2 was installed following the exact steps here: https://istio.io/docs/setup/kubernetes/upgrade/steps/

**Environment**
Kubernetes 1.11.8 (EKS), Amazon Linux 2, AWS, Amazon CNI

But this same behavior occurs in 1.11.8 (Kops with Calico CNI), AWS, Debian

**Cluster state**
I am happy to perform a dump, however the script wants all namespaces and we have secrets we'd prefer to stay secret rather than attach here. May we find a more secure method of delivery or possible just get `istio-system` namespace pod resources

**Comment by zparnold** [comment]
Please feel free to suggest a better title

**Comment by howardjohn** [comment]
Looking into this now. Could you provide logs of Pilot (discovery container)?

**Comment by howardjohn** [comment]
Tried to reproduce this. Here is my exact setup:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: identity
spec:
  host: identity
  subsets:
  - name: blue
    labels:
      deployment: blue
  - name: green
    labels:
      deployment: green
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs
spec:
  hosts:
  - "*"
  gateways:
  - gateway
  http:
  - route:
    - destination:
        port:
          number: 80
        host: identity
        # subset: green
        subset: blue
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-a
spec:
  selector:
    matchLabels:
      app: identity
      version: a
  template:
    metadata:
      labels:
        app: identity
        version: a
        deployment: blue
    spec:
      containers:
      - image: howardjohn/identity
        name: identity-a
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
        env:
        - name: SERVICE_NAME
          value: a
        ports:
        - containerPort: 8080
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-b
spec:
  selector:
    matchLabels:
      app: identity
      version: b
  template:
    metadata:
      labels:
        app: identity
        version: b
        deployment: blue
    spec:
      containers:
      - image: howardjohn/identity
        name: identity-b
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
        env:
        - name: SERVICE_NAME
          value: b
        ports:
        - containerPort: 8080
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-c
spec:
  selector:
    matchLabels:
      app: identity
      version: c
  template:
    metadata:
      labels:
        app: identity
        version: c
        deployment: green
    spec:
      containers:
      - image: howardjohn/identity
        name: identity-c
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
        env:
        - name: SERVICE_NAME
          value: c
        ports:
        - containerPort: 8080
---

kind: Service
apiVersion: v1
metadata:
  name: identity
spec:
  selector:
    app: identity
  ports:
  - name: http
    port: 80
    targetPort: 8080
---

```

I flipped blue to green a few times and saw the change immediately, so I wasn't able to reproduce this.

A few questions:

* Any custom install options used, or just the defaults? 
* What namespace is the VS, DR, and application in? Are they the same or different?

**Comment by zparnold** [comment]
First off, thanks for the quick reply! For custom install we have (passed as args to helm chart):
```yaml
global:
  proxy:
    includeIPRanges: "172.20.0.0/16"
```
But ☝️ was only to deal with the default deny egress. 
To give you some context: https://www.lucidchart.com/publicSegments/view/336b90f0-123f-47c7-85d5-80a2453def87/image.png

That roughly outlines how we used (in 1.0.2) to use Kubernetes Service label selectors to steer traffic, and since that didn't seem to work in 1.1.2 we moved towards using DR Subsets...but well it had the same result.

Let me paste all of the rules here for you to compare:
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ygrene-manager
  name: ygrene-manager-service
  namespace: acceptance
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: ygrene-manager
    deployment: green
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    readiness.status.sidecar.istio.io/applicationPorts: "3000"
  labels:
    app: ygrene-manager
    deployment: green
    environment: acceptance
    version: green
  name: ygrene-manager-deployment
  namespace: acceptance
spec:
  selector:
    matchLabels:
      app: ygrene-manager
      deployment: green
      environment: acceptance
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ygrene-manager
        deployment: green
        environment: acceptance
    spec:
      containers:
      - env:
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        envFrom:
        - configMapRef:
            name: ygrene-manager-config
        image: quay.io/ygrene/ruby-manager:sha-0f3fda990db240ecd35fde9b34769e0e1de7044b
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /usr/bin/curl
            - -X
            - GET
            - http://localhost:3000/users/sign_in
          failureThreshold: 3
          initialDelaySeconds: 120
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 30
        name: ygrene-manager
        ports:
        - containerPort: 3000
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /usr/bin/curl
            - -X
            - GET
            - http://localhost:3000/users/sign_in
          failureThreshold: 3
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
        - mountPath: /opt/certs/
          name: fds-certs
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kube-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
    - port: # This section must remain in ANY YGRENE GATEWAY. There should be zero plaintext traffic sent to the cluster.
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
        privateKey: /etc/istio/ingressgateway-certs/tls.key
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: manager-blue-green
  namespace: acceptance
spec:
  host: ygrene-manager-service
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
  subsets:
    - name: blue
      labels:
        deployment: blue
    - name: green
      labels:
        deployment: green
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: manager-service-acceptance
spec:
  hosts:
    - "ops.acceptance.ygreneworks.com"
  gateways:
    - istio-system/kube-gateway
  http:
    - route:
        - destination:
            port:
              number: 80
            host: ygrene-manager-service.acceptance.svc.cluster.local
            subset: blue
      retries:
        attempts: 3
        perTryTimeout: 2s
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mtls-acceptance
  namespace: acceptance
spec:
  host: "*.acceptance.svc.cluster.local"
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: default
  namespace: acceptance
spec:
  peers:
    - mtls:
        mode: STRICT
```

**Comment by zparnold** [comment]
@howardjohn The VS and DR that I think are affected are in the same ns `acceptance` I hope this is enough. There are other ServiceEntries, but I omitted them since they aren't affected. Please let me know if there is any more detail needed to debug

**Comment by howardjohn** [comment]
Thanks, I'll see if I can reproduce it with those settings. The only other thing would be logs from pilot - if the probably occasionally fixes itself when you restart pilot then the logs may provide some insight

**Comment by zparnold** [comment]
😂 That's actually how we ended up proceeding. It seems to work when we restart pilot...but we deploy often enough that it feels more like a hack than a fix. Let me upload the pilot logs here...I'm thinking of possibly a forced hard refresh or cache purge would be a way forward (maybe) 
[logs-from-istio-proxy-in-istio-pilot-6cb5f8f44d-5ck7b.txt](https://github.com/istio/istio/files/3066176/logs-from-istio-proxy-in-istio-pilot-6cb5f8f44d-5ck7b.txt)
[logs-from-discovery-in-istio-pilot-6cb5f8f44d-5ck7b.txt](https://github.com/istio/istio/files/3066177/logs-from-discovery-in-istio-pilot-6cb5f8f44d-5ck7b.txt)

**Comment by howardjohn** [comment]
Ok logs don't seem to indicate any problems. I think the problem here is with the Gateway. Using your configs (with minor changes), I am able to access the service directly fine, and virtual service rules apply if I comment out the gateways part of the VS. But when going through the gateway, the VS is not applied.

@philrud any insight here?

**Comment by zparnold** [comment]
Yea, I was seeing similar behavior, basically inside the cluster everything seemed peachy keen when accessing services. (though, since this particular service is most often accessed via the public internet...I admit I didn't look deeply into internal functionality.) The only place we really noticed is through the ingress gateway. Is there an alternate config I can try as a workaround?

**Comment by philrud** [comment]
@howardjohn I'm not aware of anything gateway-special related to this. I'll try this setup when I get a chance.

**Comment by zparnold** [comment]
Over the weekend we downgraded to Istio 1.0.7 @howardjohn @philrud and were able to observe the same behavior unfortunately. I know you guys are busy, so if you have a sense of where I should look I can keep digging myself. The issue is, I'm not even quite sure where to look.

**Comment by zparnold** [comment]
@nrjpoddar helped me confirm that the issue can be found when looking at the endpoints listed on the envoy management port for the istio ingressgateway. It seems that it's not updating to reflect the correct pod IP addresses.

**Comment by zparnold** [comment]
We have determined the RCA, this offending `ServiceEntry` caused Pilot to choke on the hostname `localhost`:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: datadog-agent
spec:
  hosts:
    - "localhost"
  addresses:
    - "172.20.0.0/16"
  ports:
    - name: tcp
      number: 8126
      protocol: TCP
  location: MESH_EXTERNAL
  resolution: NONE
```
