### ISSUE TITLE
Pod with istio sidecard can't connect to external service with TCP + TLS

### ISSUE THREAD

**Issue by guitmz** [istio/istio#13240]
**Describe the bug**
Whenever a pod that has istio-proxy injected tries to connect to an external TCP + TLS service, we get `Connection reset by peer`.

- The external service is whitelisted in service entry (shouldn't matter because of ALLOW_ANY policy in v1.1 of istio anyway)
- If I try the same connection from the `istio-proxy` sidecar, I get the same error
- I dont see any outbound connection in the sidecar logs
- As soon as I remove the sidecard from the pod, it is able to connect to the service just fine

This was working before the 1.1 upgrade we did.

Am I being super stupid here and missing something obvious? 

**Expected behavior**
Connection to work fine.

**Steps to reproduce the bug**
In our case, Istio was upgraded from 1.0.6 to 1.1.1 (no config changes basically) and it started to happen.

**Version**
Kubernetes: v1.12.6
Istio: release-1.1-20190402-09-16

**Installation**
Official Helm chart

**Environment**
Azure AKS

**Comment by guitmz** [comment]
Update: with the following service entry I was able to connect properly to the external endpoint
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: endpoint-external
spec:
  hosts:
  - thehostname.com
  addresses:
  - CIDR/32
  ports:
  - name: tcp
    number: thePortHere
    protocol: tls
  location: MESH_EXTERNAL
```
But the problem still persists if I deploy a TCP + TLS service inside of the cluster.

From outside of the cluster I can connect to the service just fine but from inside of the cluster (this is valid for pods who are not in istio network too) I still get the same error. My ServiceEntry for my service looks the same as the one above too.
