### ISSUE TITLE
1.1.2 - Cannot use wildcard in prefix hosts in ServiceEntry

### ISSUE THREAD

**Issue by 1hanymhajna** [istio/istio#13241]
**Describe the bug**
Cannot use wildcard in prefix hosts in ServiceEntry

**Expected behavior**
In the documentation, you mention that the wildcard prefix is accepted, but it throws this error:
`* hosts must be FQDN if no endpoints are provided for resolution mode DNS`

In your code: 
https://github.com/istio/istio/blob/master/pilot/pkg/model/validation.go#L250
i see that you call **`validateDNS1123Labels `** function directly instead of calling **`ValidateWildcardDomain `** function

**Steps to reproduce the bug**
1. Create new serviceEntry:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: egress-network
spec:
  hosts:
  - '*.hooks.slack.com'
  ports:
  - number: 80
    name: http-port
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
```
2. Run `kubectl apply -f ../egress-network.yaml`
3. You will get this error: 
`* hosts must be FQDN if no endpoints are provided for resolution mode DNS`

**Version**
istio version: 1.1.2
kubectl client version: v1.12.0
kubectl server version: v1.12.6-eks-d69f1b

**Installation**
- `kubectl apply -f install/kubernetes/helm/helm-service-account.yaml ;`
- `helm install --tls install/kubernetes/helm/istio-init --name istio-init --namespace istio-system ;`
`-helm install --tls install/kubernetes/helm/istio --name istio --namespace istio-system  --values install/kubernetes/helm/istio/values.yaml`

**Environment**
EKS
