### ISSUE TITLE
Grafana and Prometheus UIs do not work with non-root contextpath

### ISSUE THREAD

**Issue by msiraj7** [istio/istio#13279]
**Describe the bug**
[istio installation options](https://istio.io/docs/reference/config/installation-options) include  [grafana.contextPath](https://istio.io/docs/reference/config/installation-options/#grafana-options), [prometheus.contextPath](https://istio.io/docs/reference/config/installation-options/#prometheus-options) and [kiali.contextPath](https://istio.io/docs/reference/config/installation-options/#kiali-options)

grafana and prometheus UIs do not work on context path other than '/'. kiali UI works with context path "/kiali" 

**Expected behavior**
grafana and prometheus UI should work on non-root contextpath

**Steps to reproduce the bug**
Expose grafana and prometheus services to an external IP. One way to do that would be to use nodeport:

``` 
kubectl expose deployment grafana --type=Nodeport --name=grafana-test-service  --namespace istio-system
kubectl expose deployment prometheus --type=NodePort --name=prometheus-test-service --namespace istio-system
```

Access grafana and prometheus UI like this : 
<$IP-FOR-EXPOSED-SERVICE>/grafana
<$IP-FOR-EXPOSED-SERVICE>/prometheus
The above URLs will not display the UI properly. However these would work on the context root "/" 

The default contextPath values for [grafana](https://istio.io/docs/reference/config/installation-options/#grafana-options) and [prometheus](https://istio.io/docs/reference/config/installation-options/#prometheus-options) are /grafana and /prometheus respectively.

The kiali UI works on the contextPath '/kiali' properly.

**Version**
istio version: 1.1.0
kubectl version: 1.10.11

**Installation**
Install istio1.1.0 using either option at https://istio.io/docs/setup/kubernetes/install/helm
with
 `--set istio-ingressgateway=true 
--set grafana.enabled=true 
--set grafana.ingress.enabled=true 
--set kiali.enabled=true 
--set kiali.ingress.enabled=true 
--set prometheus.enabled=true 
--set prometheus.ingress.enabled=true`
  

**Environment**

**Cluster state**

**Comment by esnible** [comment]
@clyang82 the PR https://github.com/istio/istio/pull/10699 added contextpath support for Grafana for Ingress, but not for IngressGateway.  @msiraj7 are you accessing via Ingress or IngressGateway?

**Comment by esnible** [comment]
@sdake Can you triage Istio Helm issues and/or assign them to likely implementors?

**Comment by msiraj7** [comment]
I am accessing it via the ingress gateway. Is support for ingressgateway going to be available?

**Comment by esnible** [comment]
I have been accessing it through `kubectl port-forward`.  This would be a good use of a VirtualService matching /grafana and routing to the grafana service, but I haven't tried that.

**Comment by msiraj7** [comment]
Gateway: 
```apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: default-http-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP```

VirtualService:

```apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana
  namespace: default
spec:
  hosts:
  - "*"
  gateways:
  - default-http-gateway
  http:
  - match:
    - uri:
        prefix: /grafana
    route:
    - destination:
        port:
          number: 3000
        host:  grafana.istio-system.svc.cluster.local```

Then access grafana like this : http://$INGRESS_GATEWAY_IP/grafana. You will see the same issue. The same recipe works for kiali.

**Comment by mklettner** [comment]
I had the same issue and was able to solve it by creating a virtualservice with prefix and by setting two env vars in the grafana deployment template:
```
          - name: GF_SERVER_ROOT_URL
            value: %(protocol)s://%(domain)s/grafana
          - name: GF_SERVER_DOMAIN
            value: example.org
```

I suggest adding something like this to the Grafana deployment template:
```
{{- range $key, $value := .Values.env }}
          - name: "{{ $key }}"
            value: "{{ $value }}"
{{- end }} 
```   
and in the Grafana values.yaml:
`env: {}`

Grafana is highly customizable via env vars and this allows adding any desired amount of them.
I can open PR if necessary.

**Comment by rafik8** [comment]
@esnible, could you assigned to me?

**Comment by xelfe** [comment]
Same here. I had to use {} for --set grafana.ingress.hosts . ex: --set grafana.ingress.hosts={theoneiwant.com}
If I dont, I got this message;

`Error: render error in "istio/charts/grafana/templates/ingress.yaml": template: istio/charts/grafana/templates/ingress.yaml:19:30: executing "istio/charts/grafana/templates/ingress.yaml" at <.Values.ingress.host...>: range can't iterate over thehostiwant.com`

It's the same for any ingress.host that I tried.

**Comment by esnible** [comment]
@rafik8 I can't assign you.  You aren't a choice -- this happens with new people.  I assigned myself but you can do the work and submit the PR, which I will mark as ok-to-test.

**Comment by kish3007** [comment]
any update on this issue?

**Comment by esnible** [comment]
@rafik8 Are you working on this?

**Comment by rafik8** [comment]
@esnible , need to perform a couple of tests before pushing the PR.

**Comment by esnible** [comment]
@rafik8 is there a PR?

**Comment by rafik8** [comment]
@esnible, just back from my vacation. I ll pushed tonight.

**Comment by esnible** [comment]
@rafik8 Can you link to the PR?

**Comment by esnible** [comment]
@msiraj7 is this still a problem for you?

**Comment by arjav-desai** [comment]
@esnible its still an issue. Using nodeport ip:port/grafana results in error page 
![grafana](https://user-images.githubusercontent.com/19695134/62493195-237eca00-b796-11e9-8a50-ea052e5e4c28.png). The home page link results in "http://<nodeport ip:port>/?orgId=1" which works.

**Comment by arjav-desai** [comment]
I have been trying to narrow this down and wanted to provide an update. I think there are 3 ways discussed here so far to access grafana/prometheus which uses "contextPath" option on istio install.

1. NodePort Service
This was tried as ingress didn't work. However, NodePort will not work/honor contextPath as the way NodePort service is created 
`kubectl expose deployment grafana --type=Nodeport --name=grafana-test-service  --namespace istio-system` 
doesn't rely on (use) contextPath param. 
So the error page on above comment is expected, I think.

2. Ingress (deployed NGINC as ingress controller)
3. Ingress Gateway

For both of the above, we are getting same error

```
If you're seeing this Grafana has failed to load its application files 

1. This could be caused by your reverse proxy settings.
2. If you host grafana under subpath make sure your grafana.ini root_path setting includes subpath
3. If you have a local dev build make sure you build frontend using: npm run dev, npm run watch, or npm run build
4. Sometimes restarting grafana-server can help
```

I think, @mklettner have provided work-around for this issue which I will try out. 

FYI, I see that the same work around has made its way to istio:master i.e. https://github.com/istio/istio/pull/14796

**Comment by arjav-desai** [comment]
@mklettner Can you please share your VS created for grafana as well as the way you access it (browser or curl url)? 

I tried adding those to variables by editing grafana deployment in istio-system as well as create VS for grafana, but I always get 404. It seems I am running into https://github.com/grafana/grafana/issues/16135 and this issue is not fixed until grafana 6.2.x.

**Comment by mklettner** [comment]
@arjav-desai I've added the virtualservice to my previous comment. The trailing slash was necessary. Please let me know if it works, I am not sure about the rewrite and can't test it now.

**Comment by esnible** [comment]
@arjav-desai @mklettner any update on how this should be fixed?

**Comment by arjav-desai** [comment]
@esnible Haven't had a chance to try out this yet. I just started using istio 1.2.4 so will update as soon as I can.

**Comment by 0ht** [comment]
@arjav-desai @mklettner 
try this virtualservice match rule:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "istio-dashboard-app"
spec:
  hosts:
    - "mydomain.com"
  gateways:
    - default-gateway
  http:
    - match:
      - uri:
        prefix: /grafana/
      - uri:
        prefix: /grafana
      rewrite:
        uri: /
      route:
        - destination:
            host: grafana.istio-system.svc.cluster.local
            port:
              number: 3000
```
adding two uri match rule with and without trailing slash works fine on my env.

**Comment by maffeis** [comment]
I'm installing grafana through stable/helm and make it accessible under the context /grafana. Attached find the grafana.yaml which I specify to helm --values. Also find my nginx ingress config. Maybe this can help.

grafana.yaml:

<pre>
imageTag: 6.5.1

persistence:
  enabled: true
  size: 100Mi

grafana.ini:
  server:
    root_url: https://admin.somewhere.com/grafana
</pre>

ingress.yaml:

<pre>
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: admin-ingress
  namespace: admin-foundation
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/grafana/(.*)$ /$1 break;
spec:
  tls:
  - hosts:
    - admin.somewhere.com
    secretName: tls-secret
  rules:
  - host:  admin.somewhere.com
    http:
      paths:
      - path: /kibana
        backend:
          serviceName: kibana-kibana
          servicePort: 5601
      - path: /grafana
        backend:
          serviceName: grafana
          servicePort: 3000
</pre>

**Comment by wanghao923** [comment]
This install options resloved this issue:

istioctl manifest apply  --set values.gateways.istio-ingressgateway.type=NodePort --set values.grafana.enabled=true  --set values.kiali.enabled=true  --set values.tracing.enabled=true  --set values.tracing.enabled=true --set values.grafana.env.GF_SERVER_ROOT_URL=/grafana, --set values.grafana.env.GF_SERVER_SERVE_FROM_SUB_PATH=true

Istio version: 1.6.0

**Comment by Shashankft9** [comment]
@0ht I applied the same config, but mine goes to /login and gives 404 error. It works fine without any rewrites and directly giving `/` as prefix. Any clue why? 
this works for me:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana
  namespace: monitoring
spec:
  hosts:
  - "grafana.com"
  gateways:
  - grafana-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 3000
        host: grafana.monitoring.svc.cluster.local
```
but your config does not work, I do want to make it work with prefix `/grafana' though. so that I can give this prefix in the browser instead of `/`

**Comment by sk185771** [comment]
I am also facing the same issue for grafana and Prometheus. 
for grafana I tried using the HTTP rewrite. initially, it did not work. but when I added the following line in the deployment template(based on this https://stackoverflow.com/questions/63054402/istio-grafana-with-subpath-if-youre-seeing-this-grafana-has-failed-to-load-i ).
- name: GF_SERVER_ROOT_URL
  value: %(protocol)s://%(domain)s/grafana/
- name: GF_SERVER_DOMAIN
  value: example.com
- name: GF_SERVER_DOMAIN_SERVE_FROM_SUB_PATH:
  value: "false"
 it has given the error saying invalid template.
 so I modifies thwm into following
 - name: GF_SERVER_ROOT_URL
  value: http://example.com/grafana/
- name: GF_SERVER_DOMAIN
  value: example.com
- name: GF_SERVER_DOMAIN_SERVE_FROM_SUB_PATH:
  value: "false"
  
  along with this in virtual service, I added the HTTP rewrite to root uri as following
  apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-vs
  namespace: istio-system
spec:
  hosts:
  - "*"
  gateways:
  - example-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /grafana/
    name: metrics-route
    rewrite:
      uri: /
    route:
    - destination:
        host: grafana.istio-system.svc.cluster.local
        port:
          number: 3000
		  
  with this configuration grafana is working on http://<public IP of ingress>/grafana. But it is not working on http://example.com/grafana/.
  I am not sure what I did wrong here.
  
  for Prometheus,
  the HTTP rewrite does not give any results to me. it is giving 404 not found error.

**Comment by sk185771** [comment]
I am also facing the same issue for grafana and prometheus. 
for grafana I tried using the HTTP rewrite. initially it did not work. but when I added the following line in deployment template(based on this https://stackoverflow.com/questions/63054402/istio-grafana-with-subpath-if-youre-seeing-this-grafana-has-failed-to-load-i ).
```
- name: GF_SERVER_ROOT_URL
  value: %(protocol)s://%(domain)s/grafana/
- name: GF_SERVER_DOMAIN
  value: example.com
- name: GF_SERVER_DOMAIN_SERVE_FROM_SUB_PATH:
  value: "false"
```

  
  along with this in virtual service I added the HTTP rewrite to root uri as following
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-vs
  namespace: istio-system
spec:
  hosts:
  - "*"
  gateways:
  - example-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /grafana/
    name: metrics-route
    rewrite:
      uri: /
    route:
    - destination:
        host: grafana.istio-system.svc.cluster.local
        port:
          number: 3000
```

with this configuration grafana is working on http://<public IP of ingress>/grafana. But it is not working on http://example.com/grafana/.
  I am not sure what I did wrong here.
  
  for prometheus,
  the HTTP rewrite does not give any results to me. it is giving 404 not found error.

**Comment by howardjohn** [comment]
This is not an Istio bug, we provide the routing to support either rewriting, passing that url through, etc. For help setting up Grafana please refer to grafana docs/github/support.

That being said, this config should work:
```
        GF_SERVER_ROOT_URL: "http://localhost:3000/grafana/"
        GF_SERVER_DOMAIN: "localhost"
        GF_SERVER_SERVE_FROM_SUB_PATH: "true"
```

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: grafana-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-vts
  namespace: istio-system
spec:
  hosts:
  - "*"
  gateways:
  - grafana-gateway
  http:
  - match:
    - uri:
        prefix: /grafana
    route:
    - destination:
        host: grafana.istio-system.svc.cluster.local
        port:
          number: 3000

```
