### ISSUE TITLE
Sidecar resources do not filter external service entries

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#13319]
Tested in Istio 1.1.2.

Steps to reproduce:

1. Create a sidecar resource:

```
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
spec:
  egress:
  - hosts:
    - "./*"
    - "istio-system/*"
```

2. Create a service entry for httpbin.org, according to https://istio.io/docs/tasks/traffic-management/egress/#access-an-external-http-service

3. Check the clusters for a pod:

```
$ istioctl proxy-config clusters <some pod> | grep httpbin.org
httpbin.org                                                                                    80        -               outbound      &{STRICT_DNS}
```
