### ISSUE TITLE
Timeout defined for requests coming to external service does not work

### ISSUE THREAD

**Issue by DariuszBl** [istio/istio#13313]
**Describe the bug**
I have created ServiceEntry for haproxy. After that, I have created VirtualService which defines timeout and fault injection for requests coming to it but it does not work. Here is part of my configuration:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: haproxy
spec:
  hosts:
  - "some-haproxy.com"
  addresses:
  - {{ .Values.haproxyLbPrivateIp }}/32
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: NONE
  location: MESH_INTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: haproxy-timeout
spec:
  hosts:
    - "some-haproxy.com"
  http:
    - fault:
        delay:
          fixedDelay: 10s
      route:
        - destination:
            host: "some-haproxy.com"
      timeout: 5s
```
Mybe the issue is that the host defined in ServiceEntry is virtual and requests are coming through ip defined in address field?

**Expected behavior**
Every request to haproxy gets delayed by 10s and ends with timeout (after 5s). 

**Steps to reproduce the bug**
Create similar configuration for istio and check example request.

**Version**
istio 1.06
kubernetes 1.14.1

**Comment by howardjohn** [comment]
See https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#HTTPFaultInjection-Delay, you need to set the percentage. By default this is 0%.

I just verified on Istio 1.3 with:

```
cat <<EOF | kaf -
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: haproxy
spec:
  hosts:
  - "google.com"
  addresses:
  - 1.2.3.4/32
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: NONE
  location: MESH_INTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: haproxy-timeout
spec:
  hosts:
    - "google.com"
  http:
    - fault:
        delay:
          percentage:
            value: 50
          fixedDelay: 12s
      route:
        - destination:
            host: "google.com"
      timeout: 5s
EOF
```
