### ISSUE TITLE
I created a simple demo.But get 404 Not Found.

### ISSUE THREAD

**Issue by sun-wenming** [istio/istio#13315]
**Describe the bug**
{{ Succinctly describe the bug }}

When I access normally, 404 appears.
![image](https://user-images.githubusercontent.com/22268505/56087579-9a6b1c80-5ea0-11e9-89a5-8791ae7e5c55.png)

**Expected behavior**
{{ What did you expect to happen? }}

Return 200 status code

**Steps to reproduce the bug**
{{ Minimal steps to reproduce the behavior }}
I turned on an 8888 port monitor via Gin, and the pod worked.
```
FROM alpine
COPY user-client /usr/local/bin/user-client
EXPOSE 8888
CMD [ "user-client" ]
```
![image](https://user-images.githubusercontent.com/22268505/56087745-aa383000-5ea3-11e9-81d6-71347bedb664.png)

**Gateway And VirtualService user httpbin demo config.Only changed my project name and port**

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: newh
spec:
  hosts:
    - "*"
  gateways:
    - httpbin-gateway
  http:
    - match:
      route:
        - destination:
            host: newh.default.svc.cluster.local
            port:
              number: 8888
```

**This is my k8s service and deployment.**

```
apiVersion: v1
kind: Service
metadata:
  name: newh
  labels:
    app: newh
spec:
  type: NodePort
  ports:
    - name: http
      port: 8888
      targetPort: 8888
  selector:
    app: newh

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: newh
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: newh
        version: v1
    spec:
      containers:
        - image: newh
          imagePullPolicy: IfNotPresent
          name: newh
          ports:
            - containerPort: 8888
  selector:
    matchLabels:
      app: newh
```
I'm a beginner. I hope you can help me. It's been bothering me for two days.

**Version**
{{ What version of Istio and Kubernetes are you using? Use `istioctl version --remote` and `kubectl version` }}
`istioctl version --remote`
```
root@ubuntu:/home/mecm/Desktop/Link to sun-wenming# istioctl version --remote
client version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-17-g2b13318"}
citadel version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
galley version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
ingressgateway version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-17-g2b13318"}
pilot version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
policy version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
sidecar-injector version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
telemetry version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
```
`kubectl version` 
```
root@ubuntu:/home/mecm/Desktop/Link to sun-wenming# kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

```
**Installation**
{{ Please describe how Istio was installed }}
```
helm install install/kubernetes/helm/istio --name istio --namespace istio-system
```
**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}
vmware's ubuntu 16.04

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

[k8s_resources.txt](https://github.com/istio/istio/files/3076959/k8s_resources.txt)

Thank you very much.
