### ISSUE TITLE
Deploy the same version service in multiple clusters

### ISSUE THREAD

**Issue by yuchen9459** [istio/istio#13327]
**Describe the feature request**
Deploy the same version service in multiple clusters using gateway connected feature and make sure they can be accessed

**Describe alternatives you've considered**
In the [Version Routing in a Multicluster Service Mesh tutorial ](https://istio.io/blog/2019/multicluster-version-routing/), it deploys two version of review services in the second cluster. I created three Kubernetes clusters and deploy review-v1 in cluster1, review-v2 and review-v3 in cluster2 and cluster 3.
![autodraw 4_15_2019](https://user-images.githubusercontent.com/8820341/56124135-4468a880-5f76-11e9-89bd-04f9ac2b6c4b.png)

I wonder how can I deploy the same version service like review-v2 in two clusters and make sure both of them can be accessed.
Currently, I have tried to add some lines to the deployment files:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: reviews-default
spec:
  hosts:
  - reviews.default.global
  location: MESH_INTERNAL
  ports:
  - name: http1
    number: 9080
    protocol: http
  resolution: DNS
  addresses:
  - 127.255.0.3
  endpoints:
  - address: 172.17.0.3
    labels:
      cluster: cluster2
    ports:
      http1: 30417  # Do not change this port value
  - address: 172.17.0.4
    labels:
      cluster: cluster3
    ports:
      http1: 31940
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews-global
spec:
  host: reviews.default.global
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v2
    labels:
      cluster: cluster3
      cluster: cluster2
   - name: v3
    labels:
      cluster: cluster2
      cluster: cluster3
```
                                                                                                                                                                                       
As you can see from the yaml file, I added two endpoints for the ServiceEntry review-default. Since one subsets cannot have two labels, the second label in the configuration file will overwrite the first one. After deployment, v2 subset's corresponding label is cluster2, and v3 subset's corresponding label is cluster3. Therefore, after the deployment, all requests for a certain service will be directed to a cluster instead of two-clusters in a certain order (such as round-robin).
