### ISSUE TITLE
TCP Gateway only works when i open http port.

### ISSUE THREAD

**Issue by r3kzi** [istio/istio#13359]
**Describe the bug**
TCP `Gateway` only works when i open `http` port.

**Expected behavior**
TCP `Gateway` works without `http` port.

**Steps to reproduce the bug**

Deployment of:

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: tcp-echo-destination
spec:
  host: tcp-echo
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tcp-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 31400
        name: tcp
        protocol: TCP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tcp-echo
spec:
  hosts:
    - "*"
  gateways:
    - tcp-gateway
  tcp:
    - match:
        - port: 31400
      route:
        - destination:
            host: tcp-echo
            port:
              number: 9000
            subset: v1
          weight: 90
        - destination:
            host: tcp-echo
            port:
              number: 9000
            subset: v2
          weight: 10
```

Test (**no** response of tcp echo `Pod`):

```
$ echo "" | nc -vv <AWS-URL> 31400
Connection to <AWS-URL> 31400 port [tcp/*] succeeded!
```

Add `http` port in `Gateway` and redeploy:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tcp-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 31400
        name: tcp
        protocol: TCP
      hosts:
        - "*"
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
```

Test (got response of tcp echo `Pod`): 

```
$ echo "" | nc -vv <AWS-URL> 31400
Connection to <AWS-URL> 31400 port [tcp/*] succeeded!
v1
```

**Version**

```
$ istioctl version --short --remote
client version: 1.1.1
citadel version: release-1.1-20190415-09-16
galley version: release-1.1-20190415-09-16
ingressgateway version: release-1.1-20190415-09-16
pilot version: release-1.1-20190415-09-16
policy version: release-1.1-20190415-09-16
sidecar-injector version: release-1.1-20190415-09-16
telemetry version: release-1.1-20190415-09-16
```

```
$ kubectl version --short
Client Version: v1.14.1
Server Version: v1.12.6-eks-d69f1b
```

**Installation**

```
$ helm install install/kubernetes/helm/istio-init --name istio-init --namespace istio-system
$ kubectl get crd | grep istio.io | wc -l
53
$ helm install install/kubernetes/helm/istio --set prometheus.enabled=false \
	--set gateways.istio-ingressgateway.sds.enabled=true \
	--set gateways.istio-egressgateway.enabled=false \
	--set sidecarInjectorWebhook.rewriteAppHTTPProbe=true \
	--name istio \
	--namespace istio-system
```

**Environment**
AWS EKS
