### ISSUE TITLE
[Install] Support of Kiali deployment in a separate namespace

### ISSUE THREAD

**Issue by rafik8** [istio/istio#13360]
**Describe the feature request**
I want to handle the deployment of Kiali in a separate namespace then istio-system without having to update the config map after the installation. For example:
![image](https://user-images.githubusercontent.com/13514337/56201439-ca4d2800-6038-11e9-9ee1-b5adecff4bc1.png)

**Describe alternatives you've considered**
Kiali configmap needs to be updated to point the right:

- Istio namespace (default is istio-system)

- Pilot service (default is http://istio-pilot:8080/version)

- Grafana namespace (default is istio-system)

**Additional context**
The required variables will be handled using values yaml:

```
istio:
  # The namespace where Istio is installed. (Default: istio-system)
  istio_namespace: istio-system-11
  # The Service of Istio to check version. (default is http://istio-pilot:8080/version)
  url_service_version: http://istio-pilot.istio-system-11.svc:8080/version

# The Kubernetes namespace that holds the Grafana service. (default is istio-system)
grafana:
  service_namespace: istio-dashbord-11
```
