### ISSUE TITLE
Failed to configure a TLS ingress gateway using SDS

### ISSUE THREAD

**Issue by x15zhang** [istio/istio#13364]
**Describe the bug**
When I configure a TLS ingress gateway using SDS wither Istio1.1.2.
Ingressgateway pod report warning:
**Warning FailedMount 16s (x6 over 31s) kubelet, 192.168.0.19 MountVolume.SetUp failed for volume “sdsudspath” : hostPath type check failed: /var/run/sds/uds_path is not a socket file**

**Version**
kubernetes v1.11.7

**Comment by x15zhang** [comment]
@YangminZhu @Quanjie_Lin

**Comment by JimmyCYJ** [comment]
This seems to be a UDS path config issue rather than ingress gateway SDS behavior issue. @quanjielin might has more context about UDS path setup.

**Comment by quanjielin** [comment]
@x15zhang do you have the global sds flag turn on ? like https://github.com/istio/istio/blob/f523998fd8a3b070a91d34690d5e5f72910b4d47/install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml#L262;

**Comment by x15zhang** [comment]
@quanjielin Yes.I upgrade istio with this:
helm upgrade istio install/kubernetes/helm/istio --namespace istio-system --set gateways.istio-ingressgateway.sds.enabled=true

with the same config, Istio 1.1.0 is OK.

**Comment by yangminzhu** [comment]
I suspect this might be due to the sds path left over from 1.1.0 not cleaned correctly when upgrading to 1.1.2. Would you mind to try this in a complete new cluster with fresh install of Istio 1.1.3?

**Comment by quanjielin** [comment]
@x15zhang , to double check, did you turn on ```global.sds.enabled``` (it's a different flag from ```gateways.istio-ingressgateway.sds.enabled```) ? if yes, could you try - 
1. kubectl get pods -n istio-system
to see if there is nodeagent pod running in your env
2. if yes for 1, could you pls restart each nodeagent pod(by delete old pod so that k8s will start a new one)

**Comment by JimmyCYJ** [comment]
Found some discussion on a issue that looks quite similar to this one.
https://github.com/argoproj/argo/issues/826
https://github.com/kubernetes/kubernetes/issues/61801
This is a known issue in Kubernetes, and the fix is in v1.9.7.

**Comment by wxdao** [comment]
I reproduced this with a new cluster(GKE, v1.12.7-gke.10) with fresh install of **Istio 1.1.5**.

The event of istio-ingressgateway pod:
```
Warning  FailedMount  59s (x15 over 15m)  kubelet, gke-toy-cluster-1-default-pool-f9dc41fc-4fkg  MountVolume.SetUp failed for volume "sdsudspath" : hostPath type check failed: /var/run/sds/uds_path is not a socket file
```

I installed istio with this values file:
```
global:
  proxy:
    accessLogFile: "/dev/stdout"
    resources:
      requests:
        cpu: 10m
        memory: 40Mi

  disablePolicyChecks: false

  sidecarInjectorWebhook:
    enabled: true
    rewriteAppHTTPProbe: false

pilot:
  traceSampling: 100.0
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 200Mi

mixer:
  policy:
    enabled: true
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 100Mi

  telemetry:
    enabled: false
 
  adapters:
    stdio:
      enabled: true
 
grafana:
  enabled: false

tracing:
  enabled: false

kiali:
  enabled: false

prometheus:
  enabled: false

gateways:
  istio-ingressgateway:
    type: NodePort
    autoscaleEnabled: false
    sds:
      enabled: true
    resources:
      requests:
        cpu: 10m
        memory: 40Mi
      limits:
        cpu: 100m
        memory: 128Mi

  istio-egressgateway:
    enabled: false

global:
  controlPlaneSecurityEnabled: false

  mtls:
    enabled: false

  # copied from values-istio-sds-auth.yaml
  sds:
    enabled: true
    udsPath: "unix:/var/run/sds/uds_path"
    useNormalJwt: true

certmanager:
  enabled: true
```
