### ISSUE TITLE
TCP connectivity is not working correctly through a service unless the port name is `tcp` or is prefixed with `tcp-`

### ISSUE THREAD

**Issue by 2ZZ** [istio/istio#13371]
**Describe the bug**
TCP connectivity is not working correctly through a service unless the port name is `tcp` or is prefixed with `tcp-`. The documentation states that a port name without a prefix will be treated as plain TCP but that doesn't seem to be the case.

> If the port name does not begin with a recognized prefix or if the port is unnamed, traffic on the port will be treated as plain TCP traffic (unless the port explicitly uses Protocol: UDP to signify a UDP port).
https://istio.io/help/faq/traffic-management/#naming-port-convention

**Expected behavior**
Services with unknown port names to be behave as TCP if the protocol is set to TCP.

**Steps to reproduce the bug**
Create 2 pods (client and server) with Netcat installed
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: client
  name: client
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: amouat/network-utils
    name: client
    ports:
    - containerPort: 3306
      name: mysql
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: server
  name: server
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: amouat/network-utils
    name: server
    ports:
    - containerPort: 3306
      name: mysql
      protocol: TCP
```
Create 2 services pointing to the server pod but name the port differently.
```
apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: server
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
spec:
  ports:
  - name: tcp
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: server
 ```

Exec into the server pod and start a Netcat listener
```kubectl exec -it server nc -l 3306```

Exec into the client pod and send data to `service-a` observing the output on `server` pod tty
```
# client console
$ kubectl exec -it client /bin/bash
$ nc -v service-a 3306
> 1
> 2
> 3
> 4
# server console
$ nc -l 3306
> 1
```
Exec into the client pod and send data to `service-b` observing the output on `server` pod tty
```
# client console
$ nc -v service-a 3306
> 1
> 2
> 3
> 4
# server console
$ nc -l 3306
> 1
> 2
> 3
> 4
```

**Version**
```
client version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"brew", Host:"Mojave.local", GolangVersion:"go1.12.2", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.2"}
citadel version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.1"}
egressgateway version: version.BuildInfo{Version:"bdda7cfcf5ba1397e6e0e2629d53114c9ea8fc14", GitRevision:"bdda7cfcf5ba1397e6e0e2629d53114c9ea8fc14", User:"mjog", Host:"devinstance.c.mixologist-142215.internal", GolangVersion:"go1.10.1", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-snapshot.4-592-gbdda7cf"}
galley version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.1"}
ingressgateway version: version.BuildInfo{Version:"bdda7cfcf5ba1397e6e0e2629d53114c9ea8fc14", GitRevision:"bdda7cfcf5ba1397e6e0e2629d53114c9ea8fc14", User:"mjog", Host:"devinstance.c.mixologist-142215.internal", GolangVersion:"go1.10.1", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-snapshot.4-592-gbdda7cf"}
pilot version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.1"}
policy version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.1"}
sidecar-injector version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.1"}
telemetry version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.1"}
```
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-04T04:49:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
```
helm install --wait --name istio-init --namespace istio-system install/kubernetes/helm/istio-init
helm upgrade --install --wait istio --namespace istio-system install/kubernetes/helm/istio --values install/kubernetes/helm/istio/values-istio-demo.yaml --timeout 100000 --set gateways.istio-ingressgateway.serviceAnnotations.'service\.beta\.kubernetes\.io/aws-load-balancer-internal'=0.0.0.0/0 --set global.proxy.accessLogFile="/dev/stdout"
```

**Environment**
AWS EKS 1.12

**Comment by howardjohn** [comment]
I was able to reproduce this issue with Istio 1.1.3

**Comment by yangminzhu** [comment]
@2ZZ I tried to reproduce this with the following yaml in Istio 1.1.3:
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: client
  name: client
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: amouat/network-utils
    name: client
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: server
  name: server
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: amouat/network-utils
    name: server
    ports:
    - containerPort: 3306
      name: mysql
      protocol: TCP
    - containerPort: 3307
      name: custom
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: server
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
spec:
  ports:
  - name: custom
    port: 3307
    protocol: TCP
    targetPort: 3307
  selector:
    run: server
```

And tested with the following command:
```
# On client side
$ k exec -it client -c client -- bash
root@client:/# nc -v service-a 3306
Connection to service-a 3306 port [tcp/mysql] succeeded!
1
2
3
4
^C
root@client:/# nc -v service-b 3307
Connection to service-b 3307 port [tcp/*] succeeded!
1
2
3
4
```

```
# On server side
$ kubectl exec -it server -- bash
Defaulting container name to server.
Use 'kubectl describe pod/server -n default' to see all of the containers in this pod.
root@server:/# nc -l 3306
1
root@server:/# nc -l 3307
1
2
3
4
```

It seems it's working as expected, see the response on port 3307. Note the prefix `mysql` is a reserved for ports serving MySQL protocol, so I guess it doesn't work on port 3306 because you're not speaking the MySQL protocol.

Probably we should add the `mysql` to the https://istio.io/docs/setup/kubernetes/prepare/requirements/ as well.

@rshriram @venilnoronha It seems the MySQL filter is not passing through the traffic when there is a decode error, is this expected? (From the code it seems it should continue pass through the traffic in this case)
