### ISSUE TITLE
PILOT_ENABLE_FALLTHROUGH_ROUTE doesn't work for https

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#13386]
The problem seems to be external traffic over https when you have mtls enabled. If you have mtls not enabled http and https work. With mtls enabled only http works.

```
 $ curl https://www.google.com
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.google.com:443
```

**Comment by howardjohn** [comment]
Actually my assesment was wrong. Cause is a VS like:
```yaml
spec:
  hosts:
  - host
  tls:
  - match:
    - port: 443
      sni_hosts:
      - host
    route:
    - destination:
        host: host
        port:
          number: 443
      weight: 100
```

creates a listener on 443 which does send to the `route_config_name` which is where we add the fallthrough route
