### ISSUE TITLE
Retry policies not supported

### ISSUE THREAD

**Issue by viktorpeacock** [istio/istio#13419]
**Bug description**
ISTIO documentation suggests that multiple retry policies are supported (https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#HTTPRetry) and points to this article (https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/router_filter#x-envoy-retry-on) for supported policies. Specifying 5xx, retriable-4xx and retriable-status-codes do not work. Error is returned when deploying a virtual service with these policies.

**Expected behavior**
Retry policies outlined https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/router_filter#x-envoy-retry-on should be supported.

**Steps to reproduce the bug**
```
---        
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ratings-route
spec:
  hosts:
  - customer-api.demo.svc.cluster.local
  http:
  - route:
    - destination:
        host: customer-api.demo.svc.cluster.local        
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: gateway-error,connect-failure,refused-stream, 5xx
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-17-g2b13318"}

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
Via Helm charts by following default installation instructions.

**Environment where bug was observed (cloud vendor, OS, etc)**

docker-for-desktop local cluster

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
