### ISSUE TITLE
DestinationRule getting used for an external client for SNI and MTLS enabled application

### ISSUE THREAD

**Issue by nirvanagit** [istio/istio#13422]
**Bug description**
Presence of a DestinationRule with MUTUAL mode breaks routing for external clients when SNI Passthrough for Ingress is enabled for a given MTLS application

**Expected behavior**
DestinationRule should only be applied to  in mesh clients and exclude istio-ingressgateway when SNI passthrough is enabled for Ingress

**Steps to reproduce the bug**
Configure an SNI Passthrough-MTLS enabled application.

Gateway
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: foo
  namespace: bar
spec:
  servers:
  - hosts:
    - foo.bar
    port:
      name: https-443-sni
      number: 443
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
```

DestinationRule
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: foo
  namespace: bar
spec:
  host: foo.bar.svc.cluster.local
  trafficPolicy:
    tls:
      mode: MUTUAL
      caCertificates: /etc/certs/root-cert.pem
      clientCertificate: /etc/certs/cert-chain.pem
      privateKey: /etc/certs/key.pem
```

Policy
```
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: foo
  namespace: bar
spec:
  targets:
  - name: foo
  peers:
  - mtls:
      mode: STRICT
```

Config dump shows a **tcp_proxy** filter chain for the service
![Screen Shot 2019-04-18 at 9 51 04 AM](https://user-images.githubusercontent.com/5599566/56386861-b68bf800-61d7-11e9-85a5-94ac8715ca5a.png)

and a DestinationRule corresponding to the service with **tls_context** settings
![Screen Shot 2019-04-18 at 12 37 54 PM](https://user-images.githubusercontent.com/5599566/56386834-aa079f80-61d7-11e9-9646-03160e3f165f.png)

Output when I try to access the service by curling via istio-ingressgateway
```
...
...
* Connected to foo.bar (X.X.X.X) port 443 (#0)
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /opt/ca_bundle.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to foo.bar:443
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to foo.bar:443
```

**Current workaround**
1. If I delete the DR or use mode: DISABLE, the call starts working - This does not work when we want MTLS both for internal and external clients.

2. If I create a DR with exportTo: `"."`, the call starts working - We do not want to use this as we are creating a single DR for the service in the same namespace as the mTLS enabled application. This will not work if there are clients in other namespaces.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
kubectl - 1.11.8
istio - 1.1.2

**How was Istio installed?**
Using helm templates with kubectl

**Environment where bug was observed (cloud vendor, OS, etc)**
On-Prem
