### ISSUE TITLE
ServiceEntry allows short names in hosts, but pilot does not

### ISSUE THREAD

**Issue by GregHanson** [istio/istio#13436]
**Bug description**
Validation logic in ServiceEntry.Hosts allows shortnames, but pilot is silently ignoring ServiceEntries defined with a non-FQDN name

sample rules:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: rabbitmq
spec:
  hosts:
  - rabbitmq.com
  addresses:
  - XX.XXX.XX.XX
  ports:
  - number: 5673
    name: tcp-5673
    protocol: TCP
  resolution: NONE
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: rabbitmq
spec:
  hosts:
  - rabbitmq
  ports:
  - number: 5673
    name: tcp-5673
    protocol: TCP
  endpoints:
  - address: "rabbit1.com"
    ports:
      tcp-5673: 5677
  resolution: DNS
  location: MESH_EXTERNAL
```
Both rules are accepted by the validation plugin but pilot silently complaining about the non-FQDN names with only a message logged at the `Info` level.
```
$ kubectl logs -n istio-system istio-pilot-5b7d5696f-htn9c discovery | grep rabbit
2019-04-18T21:16:42.298081Z	info	parseHostname(rabbitmq) => error missing service name and namespace from the service hostname "rabbitmq"
```
checking the config_dumps of sidecars show non of the corresponding configs get pushed for rabbit:
```
$ kubectl exec httpbin-54f5bb4957-7nkbh -c istio-proxy -- curl -is localhost:15000/config_dump | grep rabbit
Gregorys-MBP:istio gihanson$
```

**Expected behavior**
Invalid rules should notify user at the creation step

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.1.3
