### ISSUE TITLE
ingress service nodeport problem (Prober does not exists url /)

### ISSUE THREAD

**Issue by marcin-kasinski** [istio/istio#13474]
Istio objects:
```

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: itzone-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
#curl -H "Host: springbootweb.apps.svc.cluster.local:30999" localhost:30999/
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: springbootweb
spec:
  hosts:
#  - "springbootweb.apps.svc.cluster.local:30999"
#  - "springbootweb:30999"
#  - "springbootweb.com:30999"
  - "springbootweb.apps.svc.cluster.local"
  - "springbootweb"
  - "springbootweb.com"
  gateways:
  - itzone-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: springbootweb # interpreted as springbootweb.apps.svc.cluster.local
        #host: ambassador.default.svc.cluster.local # interpreted as springbootweb.apps.svc.cluster.local
        port:
          number: 7070
          #number: 80
---          
```

Istio version 1.1.3
```

root@k8smaster:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
root@k8smaster:~#

```
Hello.
I have istio and ingres gateway with service nodeport type.

nodeport points to port 30999 on my woring node.

I can access my service using ingress pod IP .
I can not access my service using kubernetes work node ip and service nodeport 
```


export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.clusterIP}')
export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].port}')
export INGRESS_NODEPORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].nodePort}')
export SECURE_INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="https")].port}')
export GATEWAY_URL=$INGRESS_HOST:$INGRESS_PORT

echo INGRESS_HOST $INGRESS_HOST
echo INGRESS_PORT $INGRESS_PORT
echo INGRESS_NODEPORT $INGRESS_NODEPORT
echo GATEWAY_URL $GATEWAY_URL
log "checking internal"
curl -I -H Host:springbootweb.apps.svc.cluster.local http://$INGRESS_HOST:$INGRESS_PORT/
log "checking external"
curl -I -H Host:springbootweb.apps.svc.cluster.local http://192.168.1.11:30999/

```
curl -I -H Host:springbootweb.apps.svc.cluster.local http://$INGRESS_HOST:$INGRESS_PORT/ returns service content

In ingress gateway I can see logs:
`
[2019-04-19T19:27:59.146Z] "HEAD / HTTP/1.1" 500 - "-" 0 0 635 634 "10.38.0.0" "curl/7.58.0" "3507bde3-0452-9c11-b217-b7704bc235d7" "springbootweb.apps.svc.cluster.local" "10.40.0.7:7070" outbound|7070||springbootweb.apps.svc.cluster.local - 10.44.0.3:80 10.38.0.0:56122 -`

curl -I -H Host:springbootweb.apps.svc.cluster.local http://192.168.1.11:30999/ (k8s node) returns HTTP/1.1 400 Bad Request

In ingress gateway I can see error logs:
`
2019-04-19T19:28:20.922966Z     error   Prober does not exists url /
`
