### ISSUE TITLE
ExternalName Service results in incorrect Envoy configs (for both IngressGateway and sidecars)

### ISSUE THREAD

**Issue by uk000** [istio/istio#13479]
**Bug description**
If you create an service of type="ExternalName" with the intention of routing a certain fqdn to a certain destination (internal or external), the envoy cluster config that gets created in both IngressGateway as well as sidecars contains additional endpoint mappings than what the service definition contains. For each port in the ExternalName service, the corresponding envoy cluster config has destination endpoints to all ports of the service, so each port ends up forwarding to all ports of the service (I'm sure there's a better way to explain this, but see example below)
This results in calls that routed through the envoy proxy (either ingress requests on gateway or egress requests from a pod) to fail randomly, because the requests are sent to any of the 3 destination endpoints in a round-robin fashion.
The behavior for this issue is the same regardless of whether the ExternalName service routes to an external or an internal service.

**Expected behavior**
Envoy cluster config for ExternalName service should have single destination to the correct port for which the cluster config was generated

**Steps to reproduce the bug**
1. Use an istio setup that's running IngressGateway as well as a pod using istio-proxy sidecar.
2. Create an ExternalName service:

```
---
kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: demo
spec:
  type: ExternalName
  externalName: nginx.test.svc.cluster.local
  ports:
  - name: http-demo
    port: 80
    targetPort: 80
  - name: https-demo
    port: 443
    targetPort: 443
  - name: http-demo-proxy
    port: 7070
    targetPort: 14000
```
3. Check envoy cluster configs on IngressGateway as well as sidecar istio-proxy containers.
There will be one cluster for each port (80, 443, and 7070). Each cluster has 3 endpoints as shown below:

```
cluster:
  name: "outbound|80||nginx.demo.svc.cluster.local"
  type: "STRICT_DNS"
  connect_timeout: "1s"
  circuit_breakers:
    thresholds:
      - max_retries: 1024
  dns_refresh_rate: "5s"
  dns_lookup_family: "V4_ONLY"
  load_assignment:
    cluster_name: "outbound|80||nginx.demo.svc.cluster.local"
    endpoints:
      - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: "nginx.test.svc.cluster.local"
                  port_value: 80
            load_balancing_weight: 1
          - endpoint:
              address:
                socket_address:
                  address: "nginx.test.svc.cluster.local"
                  port_value: 443
            load_balancing_weight: 1
          - endpoint:
              address:
                socket_address:
                  address: "nginx.test.svc.cluster.local"
                  port_value: 7070
            load_balancing_weight: 1
```
So each service port is getting mapped to all 3 service ports. A request for port 80, based on above config, will be sent in round-robin manner to all 3 ports alternately. Envoy cluster configs for other ports are similar.
This results in calls to port 80 being sent to either 80, 443 or 7070 randomly (or round-robin) and hence 2 in 3 calls will fail in this setup (assuming port 80, 443 and 7070 expect different requests).

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
client version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-17-g2b13318"}
citadel version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
galley version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
ingressgateway version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-17-g2b13318"}
nodeagent version: version.BuildInfo{Version:"", GitRevision:"", User:"", Host:"", GolangVersion:"", DockerHub:"", BuildStatus:"", GitTag:""}
pilot version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
policy version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
sidecar-injector version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
telemetry version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
```

**How was Istio installed?**
Using helm template

**Environment where bug was observed (cloud vendor, OS, etc)**
kubernetes on docker-for-mac
