### ISSUE TITLE
ExportTo doesn't work in DestinationRule

### ISSUE THREAD

**Issue by castlemilk** [istio/istio#13504]
Trying to use the new `ExportTo` filtering capability to control how `DestinationRule` policy gets pushed to sidecars/gateways. The configuration is as follows:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: stock-to-external
  namespace: istio-system
spec:
  host: stock.training.local
  exportTo: ["."]
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      mode: MUTUAL
      sni: stock.training.local
      caCertificates: /etc/certs/stock-ca/ca.crt
      clientCertificate: /etc/certs/stock-client-cert/tls.crt
      privateKey: /etc/certs/stock-client-cert/tls.key
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: MUTUAL
        sni: stock.training.local
        caCertificates: /etc/certs/stock-ca/ca.crt
        clientCertificate: /etc/certs/stock-client-cert/tls.crt
        privateKey: /etc/certs/stock-client-cert/tls.key
```

I'm then trying to confirm the policy gets pushed to my gateway `istio-egressgateway` in the `istio-system` namespace via `curl localhost:15000/config_dump | grep 'stock-client-cert' -C 20`. The policy does not seem to update the reference to certificates, where the cluster has been populated by a `ServiceEntry` defined as follows:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: stock
  namespace: istio-system
spec:
  hosts:
  - stock.training.local
  location: MESH_INTERNAL
  endpoints:
  - address: istio-ingressgateway.istio-system.svc.cluster.local
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS 
```
creating the following cluster:

```json
  {
     "version_info": "2019-04-22T05:30:43Z/125",
     "cluster": {
      "name": "outbound|443||stock.training.local",
      "type": "STRICT_DNS",
      "connect_timeout": "10s",
      "circuit_breakers": {
       "thresholds": [
        {
         "max_retries": 1024
        }
       ]
      },
      "tls_context": {
       "common_tls_context": {
        "tls_certificates": [
         {
          "certificate_chain": {
           "filename": "/etc/certs/cert-chain.pem"
          },
          "private_key": {
           "filename": "/etc/certs/key.pem"
          }
         }
        ],
        "validation_context": {
         "trusted_ca": {
          "filename": "/etc/certs/root-cert.pem"
         }
        },
        "alpn_protocols": [
         "istio"
        ]
       },
       "sni": "outbound_.443_._.stock.training.local"
      }
```

As seen above, the default mTLS certs are set in the `tls_context`, instead of the desired certs specified in the `DestinationRule`.

Changing the export to `ExportTo: ["*"]` gets the policy pushed as expected as follows:

```json
{
     "version_info": "2019-04-22T05:38:23Z/126",
     "cluster": {
      "name": "outbound|443||stock.training.local",
      "type": "STRICT_DNS",
      "connect_timeout": "10s",
      "circuit_breakers": {
       "thresholds": [
        {
         "max_retries": 1024
        }
       ]
      },
      "tls_context": {
       "common_tls_context": {
        "tls_certificates": [
         {
          "certificate_chain": {
           "filename": "/etc/certs/stock-client-cert/tls.crt"
          },
          "private_key": {
           "filename": "/etc/certs/stock-client-cert/tls.key"
          }
         }
        ],
        "validation_context": {
         "trusted_ca": {
          "filename": "/etc/certs/stock-ca/ca.crt"
         }
        }
       },
       "sni": "stock.training.local"
      }
```

Suggesting an issue with how `ExportTo` is working, my understanding was by specifying `ExportTo: ["."]` policy should get pushed to all mesh components that reside in the same namespace? 

**Expected behavior**
egressgateway gets the full policy pushed out, including any references to custom mTLS certs, when using `ExportTo: ["."]`

**Steps to reproduce the bug**

Apply the above `DestinationRule` and check to see if it gets pushed to an egressgateway defined in the same namespace

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

istio 1.1.3

**How was Istio installed?**

helm template

**Environment where bug was observed (cloud vendor, OS, etc)**

docker-for-mac

@rshriram

**Comment by rshriram** [comment]
Is there a gateway definition and virtual service that binds the service to the egress gateway?

**Comment by castlemilk** [comment]
`Gateway`: 

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: stock-egressgateway
  namespace: istio-system
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 80
      name: https-stock
      protocol: HTTPS
    hosts:
    - "stock.training.local"
    tls:
      mode: MUTUAL
      caCertificates: /etc/certs/root-cert.pem
      privateKey: /etc/certs/key.pem
      serverCertificate: /etc/certs/cert-chain.pem
```
`Virtualservice`:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: egressgateway-to-ingressgateway
  namespace: istio-system
spec:
  gateways:
  - stock-egressgateway 
  hosts:
  - stock.training.local
  http:
  - match:
    - gateways:
      - stock-egressgateway 
      port: 80
    rewrite:
      authority: stock.training.local
    route:
    - destination:
        host: stock.training.local
        port:
          number: 443
      weight: 100
```
