### ISSUE TITLE
Destination rule affecting control plane communications (Envoy -> Mixer)

### ISSUE THREAD

**Issue by adityats2020** [istio/istio#13524]
**Bug description**

Envoy sidecar is not able to communicate with Mixer when the following global Destination Rule is used with Mesh Policy set to PERMISSIVE and ControlPlaneAuthPolicy set to NONE.
```
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "default"
spec:
  host: "*.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```
Destination Rule for Istio-Telemetry is default
```
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: istio-telemetry
  namespace: istio-system
  labels:
    app: mixer
    chart: mixer
    heritage: Tiller
    release: istio
spec:
  host: istio-telemetry.istio-system.svc.cluster.local
  trafficPolicy:
    connectionPool:
      http:
        http2MaxRequests: 10000
        maxRequestsPerConnection: 10000
---
```

**Expected behavior**
The same configuration was working in Istio 1.0. It is not working in Istio 1.1.

As a workaround I am using the following configuration
```
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "default"
spec:
  host: "*.default.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```

**Steps to reproduce the bug**
* Install Istio 1.1 in a Kubernetes cluster. 
* Setup the DestinationRule shared above. 
* Create a deployment with sidecar in default namespace. Sidecar will not be able to communicate with Istio-Telemetry. 

**istioctl version --remote**
client version: version.BuildInfo{Version:"1.1.3", GitRevision:"d19179769183541c5db473ae8d062ca899abb3be-dirty", User:"brew", Host:"HighSierra-2.local", GolangVersion:"go1.12.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.3"}

**kubectl version**
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:05:06Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
Using Helm template.

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS - EKS

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

Earlier discussion in forum regarding this: https://discuss.istio.io/t/is-envoy-metrics-not-pushed-via-statsd-after-1-1/1883/12
