### ISSUE TITLE
Istio sidecar init-proxy-container requires to run as `root`

### ISSUE THREAD

**Issue by mrshengzyzy** [istio/istio#13577]
**Describe the feature request**
In the [#10358](https://github.com/istio/istio/issues/10358) we can specify it explicitly in the ConfigMap like this:
```
securityContext:
  capabilities:
     add:
       - NET_ADMIN
   privileged: true
   runAsNonRoot: false
   runAsUser: 0
```
How can I perform as a `root` in container istio-proxy cause I need exec ‘iptables’
```
root@productpage-v1-7ddd4fb9f4-tct7q:~# iptables -L -v
iptables v1.6.0: can't initialize iptables table `filter': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
```

**Comment by howardjohn** [comment]
The init container will run as root, but the proxy will not - major security reasons for this. 

If you are 100% sure you want root in the istio-proxy container, you could modify the injector template - it is an option to pass to `istioctl kube-inject`.

However, I strongly recommend not doing this. If you want to set up some custom iptables, you could add an init container to your pod that does this. 

Does that work for you, or did I misunderstand what you want to do?

**Comment by mrshengzyzy** [comment]
@howardjohn thanks a lot you are right
Just append the configuration 
```
securityContext:
capabilities:
   add:
     - NET_ADMIN
 privileged: true
 runAsNonRoot: false
```
to istio-proxy container Node `securityContext`.
And you shoule  execute `sudo -i` to switch `root`  in istio-proxy container.
