### ISSUE TITLE
can't connect to GCE's redis with istio sidecar by creating serviceentry

### ISSUE THREAD

**Issue by maonaoda** [istio/istio#13607]
**Bug description**
     Application which is created on GKE can't connect to GCE's redis with istio sidecar by creating serviceentry.but works well without  istio sidecar.
    At first, application internal log was "redis.clients.jedis.exceptions.JedisConnectionException: All sentinels down, cannot determine where is mymaster master is running..."
    After create Serviceentry ,log was chagned as  "Cannot get Jedis connection,nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool"

 Created Serviceentry ：    
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: redis-instance1
  namespace: backend-api
spec:
  addresses:
  - addresses/32
  hosts:
  - host
  ports:
  - number: 26379
    name: redis
    protocol: TCP
  resolution: NONE
  location: MESH_EXTERNAL
```

**Expected behavior**
 connect to redis successfully by using serviceentry

**Steps to reproduce the bug**
after pod created by statefulset

error：Readiness probe failed read: connection reset by peer

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio 1.0.6
Client Version: v1.11.7-dispatcher
Server Version: v1.12.6-gke.10

**How was Istio installed?**
 Without auth 

**Environment where bug was observed (cloud vendor, OS, etc)**
  Google Kubernetes Engine , and Google Computer Engine

**Ways of trying**
changed the includeOutboundIPRanges on CongfigMap named isito,but reback after change automatically.
[https://istio.io/docs/tasks/traffic-management/egress/](https://istio.io/docs/tasks/traffic-management/egress/)
