### ISSUE TITLE
setting sdsUdsPath when sds is disabled breaks functionality of gateways when deployed

### ISSUE THREAD

**Issue by castlemilk** [istio/istio#13604]
**Bug description**
with `global.sds.enabled=false` and a `sdsUdsPath` set as non-empty such as `global.sds.sdsUdsPath="/some/path"`, causes gateway configuration to have a non-empty sdsUdsPath, which in turn causes issues in the deployment as there are a number of conditional checks (in pilot) which use the sdsUdsPath to check if SDS functionality should be used or not.

**Expected behavior**
when `global.sds.enabled=false` it should not matter what the values of the following values are:

```yaml
  sds:
    # SDS enabled. IF set to true, mTLS certificates for the sidecars will be
    # distributed through the SecretDiscoveryService instead of using K8S secrets to mount the certificates.
    enabled: false
    udsPath: "unix:/var/run/sds/uds_path"
    useTrustworthyJwt: false
    useNormalJwt: false
```

**Steps to reproduce the bug**
set the following:
```yaml
  sds:
    # SDS enabled. IF set to true, mTLS certificates for the sidecars will be
    # distributed through the SecretDiscoveryService instead of using K8S secrets to mount the certificates.
    enabled: false
    udsPath: "unix:/var/run/sds/uds_path"
    useTrustworthyJwt: false
    useNormalJwt: false
```
 in the istio deployment `values.yaml` and deploy the control plane and ingress gateway. Then attempt to achieve ingress to an example backend and the ingressgateway will fail.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istio 1.1.3
**How was Istio installed?**
helm template
**Environment where bug was observed (cloud vendor, OS, etc)**
docker-for-mac, gke
