### ISSUE TITLE
Istio circuit breaker not opening the circuit when downstream service throws 500 error

### ISSUE THREAD

**Issue by codependent** [istio/istio#13612]
**Bug description**
The full description is on this StackOverflow question: https://stackoverflow.com/questions/55707778/istio-circuit-breaker-not-opening-the-circuit-when-downstream-service-throws-500

Summing up, given this configuration:

**customer-rating-service - Istio Virtual Service**
```
...
spec:
  hosts:
    - customer-rating-service
  gateways: ~
  http:
    - route:
        - destination:
            host: customer-rating-service
            subset: v1
```
**customer-rating-service - Istio Destination Rule**
```
...
spec:
  host: customer-rating-service
  trafficPolicy:
    outlierDetection:
      baseEjectionTime: 30s
      consecutiveErrors: 1
      maxEjectionPercent: 100%
      minHealthPercent: 0%
    tls:
      mode: ISTIO_MUTUAL
  subsets:
    - labels:
        version: v1
      name: v1
```

When customer-rating-service returns an error (500 HTTP response code), since it has defined `consecutiveErrors: 1`, the circuit breaker should be open. However, every call to the customer-rating-service reaches the service.

**Expected behavior**
The circuit breaker should be open.

**Steps to reproduce the bug**
Configure a Circuit Breaker as shown above

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio 1.1.2
Kubernetes 1.10
OKD 3.10

**How was Istio installed?**
Following the official documentation (OpenShift setup + normal installation)

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EC2 instances.
