### ISSUE TITLE
Outlier detection with maxEjectionPercent 100 minHealthPercent 0 not allowing to evict all replicas

### ISSUE THREAD

**Issue by codependent** [istio/istio#13682]
**Bug description**
Given this outlier detection config:

```
spec:
  host: customer-rating-service
  trafficPolicy:
    outlierDetection:
      baseEjectionTime: 1m
      consecutiveErrors: 1
      maxEjectionPercent: 100
      minHealthPercent: 0
    tls:
      mode: ISTIO_MUTUAL
  subsets:
    - labels:
        version: v1
      name: v1
```
Let' suppose I have 2 replicas of an application and both always fail with a 502 error. I want that all replicas failing more than once are evicted from the pool. What I was expecting was that the circuit breaker would be open and a 503 response (open circuit breaker) is returned for every request at this service. However what I see is the failing replicas are always called.

**maxEjectionPercent 100 should let me evict 100% of the failing replicas** 

**minHealthPercent 0 shoud prevent outlier detection from being disabled**

**Expected behavior**
All two replicas of the application should be evicted from the pool and the 503 response should be returned

**Steps to reproduce the bug**
Setup a DestinationRule as shown above and configure it service to have two replicas that always answer with a 502 status.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

Istio 1.1.2

Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-10-15T09:45:30Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-04-04T19:38:01Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
Istio on OKD following the OpenShift setup guide and the usual install process.

**Environment where bug was observed (cloud vendor, OS, etc)**
centos
