### ISSUE TITLE
Apply a retry policy and a fault injection on the same virtual service

### ISSUE THREAD

**Issue by viktorpeacock** [istio/istio#13705]
**Describe the feature request**
I would like to be able to use fault injection and retry policies for testing purposes. 

I have a service A that calls a service B. Service B has been configured with a retry policy, i.e. any incoming route into service B should be retried if that service returns a 503. 

I now want to validate this configuration via a CI pipeline by getting service A to call service B. Now I would like to inject a fault into service B via fault injection, but from my understanding this is not possible, i.e. I cannot use both fault injection and retry policies at the same time. 

**Describe alternatives you've considered**
Adding manual configuration into service B that would enable fault injection. I consider this to be very risky as it has a potential of getting into production. 

**Additional context**

**Comment by howardjohn** [comment]
Why is it not possible? Does something like this not work
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ratings
spec:
  hosts:
  - ratings
  http:
  - fault:
      delay:
        percent: 10
        fixedDelay: 5s
    route:
    - destination:
        host: ratings
        subset: v1
    retries:
      attempts: 3
      perTryTimeout: 2s
```
