### ISSUE TITLE
Add x-request-start header header for new relic

### ISSUE THREAD

**Issue by trevorlinton** [istio/istio#13708]
**Describe the feature request**

Some diagnostic services used by our engineering staff rely on a x-request-start header that contains the unix epoch time when a request first arrived.  I've tried adding this with virtual service / rules but with no luck.  It would appear envoy added this support to the proxy itself (https://github.com/envoyproxy/envoy/issues/1966) is this something that can be added to an istio ingress gateway config or virtual service / gateway config?

**Describe alternatives you've considered**

Manually inserting the current time via rules, but unsuccessful.

**Additional context**

Here's the new relic docs: https://docs.newrelic.com/docs/apm/applications-menu/features/request-queue-server-configuration-examples

**Comment by howardjohn** [comment]
Can you just add 

```yaml
      headers:
        response:
          add:
            "x-request-start": "%START_TIME(%s.%3f)%"
```

To your virtual service?
