### ISSUE TITLE
Overlapping Gateway HTTPS hosts causes ACK ERROR, rejecting full listener

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#13717]
Pilot gives 
```
ADS:LDS: ACK ERROR 10.60.53.62:48764 istio-ingressgateway-9c5dfc8c6-h6fbg.istio-system node:<id:"router~10.60.53.62~istio-ingressgateway-9c5dfc8c6-h6fbg.istio-system~istio-system.svc.cluster.local" cluster:"istio-ingressgateway" metadata:<fields:<key:"CONFIG_NAMESPACE" value:<string_value:"istio-system" > > fields:<key:"ISTIO_META_INSTANCE_IPS" value:<string_value:"10.60.53.62,10.60.53.62,fe80::40fa:beff:fe06:8582" > > fields:<key:"ISTIO_PROXY_SHA" value:<string_value:"istio-proxy:a169a0c0cd86b51538c240e2d037fa8f7f5860ae" > > fields:<key:"ISTIO_PROXY_VERSION" value:<string_value:"1.1.3" > > fields:<key:"ISTIO_VERSION" value:<string_value:"1.1.3" > > fields:<key:"POD_NAME" value:<string_value:"istio-ingressgateway-9c5dfc8c6-h6fbg" > > fields:<key:"ROUTER_MODE" value:<string_value:"sni-dnat" > > fields:<key:"USER_SDS" value:<string_value:"true" > > fields:<key:"istio" value:<string_value:"sidecar" > > > locality:<> build_version:"a169a0c0cd86b51538c240e2d037fa8f7f5860ae/1.11.0-dev/Clean/RELEASE/BoringSSL" > type_url:"type.googleapis.com/envoy.api.v2.Listener" response_nonce:"c0ee59dc-db9c-497d-91b0-e859ad5462d9" error_detail:<code:13 message:"Error adding/updating listener(s) 0.0.0.0_443: error adding listener '0.0.0.0:443': multiple filter chains with effectively equivalent matching rules are defined" >
```

Relevant part is `multiple filter chains with effectively equivalent matching rules are defined`.

This causes the full 0.0.0.0_443 listener to be rejected, effectively breaking all ingress traffic.

Reproduce with:
Follow steps in https://istio.io/docs/tasks/traffic-management/secure-ingress/mount/ to create secret

Make Gateway config:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - httpbin.example.com
  gateways:
  - mygateway
  tls:
  - match:
    - port: 443
      sni_hosts:
      - httpbin.example.com
    route:
    - destination:
        host: my-httpbin
        port:
          number: 443
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mygateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    - httpbin.example.com

  - port:
      number: 443
      name: https-other
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    - "google.com"
    - "httpbin.example.com"
```

`--set global.proxy.image=istio/proxyv2:1.1.2` does NOT have this issues (using 1.1.4 for all other components)
`--set global.proxy.image=istio/proxyv2:1.1.3` DOES have this issue
`--set global.proxy.image=istio/proxyv2:1.1.4` DOES have this issue

Root cause seems to be this PR: https://github.com/envoyproxy/envoy/pull/6022. This effect seems to be an unintended consequence of that PR.

@costinm @silentdai @duderino

**Comment by PiotrSikora** [comment]
@howardjohn could you paste config that's pushed to Envoy? I believe it should show up in k8s logs when Envoy is logging at the `trace` level.

**Comment by silentdai** [comment]
I am wonder if a proper fix is to reshape the generated config at pilot.
I don't have the log to confirm but I highly suspect that there will be two filterchains of which
Port-DesitationPort-DestinationIP are the same, while beneath that tree node,
the first filter chain add "httpbin.example.com" node first, and then the second filter chain try to add 2 nodes with "google.com" and "httpbin.example.com". The later "httpbin.example.com" hit this throw

https://github.com/envoyproxy/envoy/blob/master/source/server/listener_manager_impl.cc#L428

**Comment by silentdai** [comment]
@howardjohn @costinm 
Let's suppose the envoy did not throw exceptions somehow,
If a connection is hitting httpbin.example.com, what would envoy choose to reach access httpbin? 
Another way to ask is what if secret is different(although the comment says it must be same)?

**Comment by howardjohn** [comment]
Filter chains are matched in order, which is the same order specified in the Gateway config

**Comment by howardjohn** [comment]
Tried to reproduce this with simpler set up1.1.4, default install
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - httpbin.example.com
  gateways:
  - mygateway
  tls:
  - match:
    - port: 443
      sni_hosts:
      - httpbin.example.com
    route:
    - destination:
        host: my-httpbin
        port:
          number: 443
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mygateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
    hosts:
    - httpbin.example.com

  - port:
      number: 443
      name: https-other
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
    hosts:
    - "google.com"
    - "httpbin.example.com"
```
Now I get `Error adding/updating listener(s) 0.0.0.0_443: error adding listener '0.0.0.0:443': multiple filter chains with the same matching rules are defined`
