### ISSUE TITLE
EnvoyFilter request/response hooks called twice

### ISSUE THREAD

**Issue by gokhansengun** [istio/istio#13728]
Setting up a simple EnvoyFilter and adding request/response hooks result in them being called twice instead of once.

Issue exists starting with 1.1.0 onwards including latest 1.1.4, did not test it before 1.1.0. Same setup with bare Envoy (using the same Docker image as Istio) does not exhibit the behaviour.

Reproduction is pretty straightforward:

- Install Istio 1.1.4
- Install BookInfo sample app
- Apply a very simple EnvoyFilter given below.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-details-lua
  namespace: default
spec:
  workloadLabels:
    app: details
  filters:
  - filterConfig:
      inlineCode: |
        function envoy_on_request(request_handle)
          request_handle:logErr("Request hook called")
        end

        function envoy_on_response(response_handle)
          response_handle:logErr("Response hook called")
        end
    filterName: envoy.lua
    filterType: HTTP
    listenerMatch:
      listenerType: SIDECAR_INBOUND
      portNumber: 9080
```
- Make a request to http://<INGRESS_IP>:9800
- Look at the `istio-proxy` logs of `details` pod.
- Notice double calls to both `envoy_on_request` and `envoy_on_response` like in below log.

```
details-v1-68868454f5-kp7tw istio-proxy [2019-04-30 17:32:51.966][22][error][lua] [external/envoy/source/extensions/filters/http/lua/lua_filter.cc:541] script log: Request hook called
details-v1-68868454f5-kp7tw istio-proxy [2019-04-30 17:32:51.966][22][error][lua] [external/envoy/source/extensions/filters/http/lua/lua_filter.cc:541] script log: Request hook called
details-v1-68868454f5-kp7tw istio-proxy [2019-04-30 17:32:51.970][22][error][lua] [external/envoy/source/extensions/filters/http/lua/lua_filter.cc:541] script log: Response hook called
details-v1-68868454f5-kp7tw istio-proxy [2019-04-30 17:32:51.970][22][error][lua] [external/envoy/source/extensions/filters/http/lua/lua_filter.cc:541] script log: Response hook called
details-v1-68868454f5-kp7tw details 127.0.0.1 - - [30/Apr/2019:17:32:51 UTC] "GET /details/0 HTTP/1.1" 200 178
details-v1-68868454f5-kp7tw details - -> /details/0
```

[Config Dump](https://gist.githubusercontent.com/gokhansengun/6f332e4a35ee490baa1da82b0ac549e7/raw/cb30bf03622180b510305aef04c149d60f7106f4/Config%2520Dump) shows that the filter is somehow duplicated therefore probably causing the issue.

```
"http_filters": [
	{
	 "name": "envoy.lua",
	 "config": {
	  "inlineCode": "function envoy_on_request(request_handle)\n  request_handle:logErr(\"Request hook called\")\nend\n\nfunction envoy_on_response(response_handle)\n  response_handle:logErr(\"Response hook called\")\nend\n"
	 }
	},
	{
	 "config": {
	  "inlineCode": "function envoy_on_request(request_handle)\n  request_handle:logErr(\"Request hook called\")\nend\n\nfunction envoy_on_response(response_handle)\n  response_handle:logErr(\"Response hook called\")\nend\n"
	 },
	 "name": "envoy.lua"
	},
```

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
