### ISSUE TITLE
 unknown field "trigger_rules" in v1alpha1.Jwt

### ISSUE THREAD

**Issue by Jonathan34** [istio/istio#13751]
**Bug description**
```
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
spec:
  origins:
  - jwt:
      issuer: https://accounts.google.com
      jwksUri: https://www.googleapis.com/oauth2/v3/certs
      trigger_rules:
      - excluded_paths:
        - exact: /
```
`unknown field “trigger_rules” in v1alpha1.Jwt`
Also tried with `triggerRules` as camelCase seems odd but no go.

**Expected behavior**
trigger_rules is applied.
Even better, i d like to exclude a service using targets.

**Steps to reproduce the bug**
deploy he policy above.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
`Error: unknown flag: --remote`
```
Version: 1.0.3
GitRevision: a44d4c8bcb427db16ca4a439adfbd8d9361b8ed3
User: root@0ead81bba27d
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean
```

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:12:47Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-gke.10", GitCommit:"aaf0906400b5fc1d858ce0566a571e4f3ed06b9f", GitTreeState:"clean", BuildDate:"2019-03-30T19:30:48Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
GKE add-on

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X ] Policies and Telemetry
[X ] Security
[ ] Test and Release
[ ] User Experience
