### ISSUE TITLE
RBAC not working with Namespace isolation

### ISSUE THREAD

**Issue by anoopl** [istio/istio#13803]
[istio-dump.tar.gz](https://github.com/istio/istio/files/3141537/istio-dump.tar.gz)
I am using Istio 1.1.4. 
I am trying to allow traffic to a service only from default namespace.
mTLS is enabled with:
```
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "default"
  namespace: "test-ns"
spec:
  peers:
  - mtls: {}
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "default"
  namespace: "test-ns"
spec:
  host: "*.test-ns.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```
RBAC enabled with:
```
apiVersion: "rbac.istio.io/v1alpha1"
kind: ClusterRbacConfig
metadata:
  name: default
spec:
  mode: 'ON_WITH_INCLUSION'
  inclusion:
    namespaces: ["test-ns"]
```
I have the following ServiceRole & binding:

```
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: testapp
  namespace: test-ns
spec:
  rules:
  - services: ["testapp.test-ns.svc.cluster.local"]
    methods: ["GET", "POST"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: testapp
  namespace: test-ns
spec:
  subjects:
  - properties:
      source.namespace: "default"
  roleRef:
    kind: ServiceRole
    name: "testapp"
```
But I am able to access the service using curl from namespaces other than default as well.
To test whether the service role binding is working I deleted the service role and role binding then I got “RBAC access denied” as expected.
What could be wrong? Could this be a bug?

**Comment by yangminzhu** [comment]
> But I am able to access the service using curl from namespaces other than default as well.

do you have logs of the envoy (with RBAC debugging enabled, see https://istio.io/help/ops/security/debugging-authorization/#ensure-proxies-enforce-policies-correctly) when this is happening?

Is this happening constantly? (sometime there might be some delay from the policy taking effect)

**Comment by yangminzhu** [comment]
I just tried this with Istio 1.1.6 but couldn't reproduce this problem. I cannot access the testapp service from namespace other than `default`.

**Comment by anoopl** [comment]
Thanks @yangminzhu , let me upgrade Istio and try on 1.1.6.
Can you please share the yamls you have used or it's same as the one I posted.

**Comment by yangminzhu** [comment]
@anoopl I think this should work for both 1.1.4 and 1.1.6.

The following is my rbac config, almost the exactly same as yours:
```
apiVersion: "rbac.istio.io/v1alpha1"
kind: ClusterRbacConfig
metadata:
  name: default
spec:
  mode: 'ON_WITH_INCLUSION'
  inclusion:
    namespaces: ["test-ns"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: testapp
  namespace: test-ns
spec:
  rules:
  - services: ["httpbin.test-ns.svc.cluster.local"]
    methods: ["GET", "POST"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: testapp
  namespace: test-ns
spec:
  subjects:
  - properties:
      source.namespace: "default"
  roleRef:
    kind: ServiceRole
    name: "testapp"
```

Note I deployed a httpbin in the test-ns namespace and use it as the test-app. I also deployed a sleep app in both default and test-ns namespace. The one in default could access the httpbin while the one in test-ns couldn't.

**Comment by sushicw** [comment]
I was running into this issue in Istio 1.1.7, following the ["Authorization for HTTP Services"](https://istio.io/docs/tasks/security/authz-http) task. 

Starting with the sample bookinfo app, and following the steps as given, after applying the serviceRoleBinding I continue to get “RBAC access denied” as an error.

If I modify the ServiceRoleBinding to use 

```
kind: ServiceRoleBinding
metadata:
  name: bind-service-viewer
  namespace: default
spec:
  subjects:
  - user: "*"
  roleRef:
    kind: ServiceRole
    name: "service-viewer"

```

instead of 

```
kind: ServiceRoleBinding
metadata:
  name: bind-service-viewer
  namespace: default
spec:
  subjects:
  - properties:
      source.namespace: "istio-system"
  - properties:
      source.namespace: "default"
  roleRef:
    kind: ServiceRole
    name: "service-viewer"
```

then it works as expected.
