### ISSUE TITLE
Envoy filter not allowing headers in Istio?

### ISSUE THREAD

**Issue by kumarsparkz** [istio/istio#13819]
I am using Istio 1.0.3 as GKE managed. I am adding an envoy filter to do external authorization as per documentation mentioned in https://istio.io/docs/reference/config/networking/v1alpha3/envoy-filter/
and https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/ext_authz/v2/ext_authz.proto#external-authorization

Based on logs, I see that the filter is being applied and the HTTP call is happening to the external authorization service I created. But, it's not passing the headers I mentioned in the envoyfilter. Maybe I am setting it right? Can someone look into it and help by correcting the envoyfilter syntax?  

Here's my filter config:

```apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: test-auth-service-filter
spec:
  workloadLabels:
    app: test-service
  filters:
  - insertPosition:
      index: FIRST
    listenerMatch:
      listenerType: ANY
      listenerProtocol: ALL
    filterType: HTTP
    filterName: "envoy.ext_authz"
    filterConfig:
      http_service:
        server_uri:
          uri: http://test-auth-service.default.svc.cluster.local:80
          cluster: outbound|80||test-auth-service.default.svc.cluster.local
          timeout: 5s
        path_prefix: /api/testAuthService/jwt/authenticate
        authorization_request:
          allowed_headers: [ x-goog-authenticated-user-email, X-TST-AUTH-TOKEN, set-cookie, cookie ]
      failure_mode_allow: false
```

**Comment by rphillipsz** [comment]
I'm struggling with the same thing.  I was able to get the lua filter working, but I'm not seeing any request headers with ext_authz.  I do get a request, I just can't get any of the request headers in the auth call.

**Comment by kumarsparkz** [comment]
Based on the envoy docs, I have corrected the syntax issue of allowed_headers, however, it's still not working. Here's the updated filter config
```
kind: EnvoyFilter
metadata:
  name: test-auth-service-filter
spec:
  workloadLabels:
    app: test-service
  filters:
  - insertPosition:
      index: FIRST
    listenerMatch:
      listenerType: ANY
      listenerProtocol: ALL
    filterType: HTTP
    filterName: "envoy.ext_authz"
    filterConfig:
      http_service:
        server_uri:
          uri: http://test-auth-service.default.svc.cluster.local:80
          cluster: outbound|80||test-auth-service.default.svc.cluster.local
          timeout: 5s
        path_prefix: /api/testAuthService/jwt/authenticate
        authorization_request:
          allowed_headers:
            patterns: [ exact: x-goog-authenticated-user-email, exact: X-TST-AUTH-TOKEN, exact: set-cookie, exact: cookie ]
      failure_mode_allow: false
```
The config in JSON for reference:
```
{
    "apiVersion": "networking.istio.io/v1alpha3",
    "kind": "EnvoyFilter",
    "metadata": {
        "name": "test-service-envoy-filter",
        "namespace": "istio-system"
    },
    "spec": {
        "filters": [
            {
                "filterConfig": {
                    "clear_route_cache": true,
                    "failure_mode_allow": false,
                    "http_service": {
                        "authorization_request": {
                            "allowed_headers": {
                                "patterns": [
                                    {
                                        "exact": "x-goog-authenticated-user-email"
                                    },
                                    {
                                        "exact": "X-TST-AUTH-TOKEN"
                                    },
                                    {
                                        "exact": "set-cookie"
                                    },
                                    {
                                        "exact": "cookie"
                                    }
                                ]
                            }
                        },
                        "path_prefix": "/api/testAuthService/jwt/authenticate",
                        "server_uri": {
                            "cluster": "outbound|80||test-auth-service.default.svc.cluster.local",
                            "timeout": "5s",
                            "uri": "http://test-auth-service.default.svc.cluster.local:80"
                        }
                    }
                },
                "filterName": "envoy.ext_authz",
                "filterType": "HTTP",
                "insertPosition": {
                    "index": "FIRST"
                },
                "listenerMatch": {
                    "listenerProtocol": "HTTP",
                    "listenerType": "SIDECAR_INBOUND"
                }
            }
        ],
        "workloadLabels": {
            "app": "test-service"
        }
    }
}
```


This is blocking our progress and the plan to use Istio in production. Can someone please review and let's know what can be the correct solution here?
