### ISSUE TITLE
Pilot doesn't update ingress-gateway configuration in some cornercase

### ISSUE THREAD

**Issue by Demonsthere** [istio/istio#13863]
**Bug description**

The problem seems to be similar as https://github.com/istio/istio/issues/11039, when the creation of a new `gateway` resource doesn't propagate to `istio-ingressgateway`, which can be verified by the following command:
```
kubectl exec -t -n istio-system $(kubectl get pod -l app=istio-ingressgateway -n istio-system | grep "istio-ingressgateway" | awk '{print $1}') -- netstat -lptnu
```

**Expected behavior**

Assuming the following gateway configuration:
```
apiVersion: networking.istio.io/v1alpha3
  kind: Gateway
  metadata:
    name: kyma-gateway
    namespace: kyma-system
  spec:
    selector:
      istio: ingressgateway
    servers:
    - hosts:
      - '*.kyma.local'
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        privateKey: /etc/istio/ingressgateway-certs/tls.key
        serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
    - hosts:
      - '*.kyma.local'
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
```

Netstat should return:
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      20/envoy
tcp        0      0 0.0.0.0:15090           0.0.0.0:*               LISTEN      20/envoy
tcp        0      0 127.0.0.1:15000         0.0.0.0:*               LISTEN      20/envoy
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      20/envoy
tcp6       0      0 :::15020                :::*                    LISTEN      1/pilot-agent
```

However, in some corner case, the entries for 80 and 443 are missing causing connection refused errors (example: https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-minikube-verification/1125520861810397186)

**Steps to reproduce the bug**

Install istio, install some gateway, observe the istio-ingressgateway pod

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

Istio 1.1.0

**How was Istio installed?**

Helm chart in Kyma, with reduced resources and autoscaling disabled

**Environment where bug was observed (cloud vendor, OS, etc)**

Google VM, minikube with driver none

**Related issues**
Observed in Kyma: https://github.com/kyma-project/kyma/issues/3622
Related istio error: https://github.com/istio/istio/issues/11039
