### ISSUE TITLE
Unable to remove server header

### ISSUE THREAD

**Issue by aaronmell** [istio/istio#13861]
**Bug description**
I should be able to remove/disable the server: istio-envoy when using istio  

**Expected behavior**

using the following configuration on a virtual service, I should be able to 

Headers:
      Response:
        Remove:
          server

**Steps to reproduce the bug**
Add a gateway that routes to a virtual service

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.1.4
1.13

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
Local kubernetes cluster on macos docker

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Comment by nisan270390** [comment]
I'm facing with the same issue, I've upgraded istio from 1.0.6 to 1.1.5 and trying to manipulate the response server header.

> headers:
     response:
       remove:
         server

OR 
> headers:
     response:
       set:
         server: xxxxxx

but the server header haven't changed

**Comment by prestonvanloon** [comment]
I tried to remove this in a rule as well, but the server field persists. 

```yaml
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: remove-server
  namespace: istio-system
spec:
  match: source.workload.name == "istio-ingressgateway"
  responseHeaderOperations:
    - name: server
      operation: REMOVE
```

**Comment by kyessenov** [comment]
Envoy treats some headers as special, including this server header and content-length, and it overrides any plugin (e.g. istio) actions when HTTP specification suggests it. For example, empty bodies are going to have content length 0 because that's what clients expect.

Do you have an issue with the server header itself, or the value that the header is set to?

**Comment by nisan270390** [comment]
@kyessenov I prefer to cover the proxy backend we're using. I'm wondering if there is an option to overwrite the server header value

**Comment by aaronmell** [comment]
@kyessenov Our security/compliance team has an issue with it.

**Comment by xring** [comment]
got same problem with 1.1.6, for security reasons we should be able to override this header.

**Comment by elvizlai** [comment]
same issue.

**Comment by rtmie** [comment]
similar experience on 1.1.4. Tried both set and remove on server header. Set would be sufficient for my use case.

**Comment by slabber** [comment]
Is it possible that this PR will help:
https://github.com/istio/api/pull/897

Perhaps it will allow the override of the server header like so:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingress
spec:
  selector:
    istio: ingressgateway
  httpOptions:
    server_name: Apache
```

**Comment by mitchellmaler** [comment]
What is the status of this? Our secops team wants us to override this for all responses.

**Comment by seanmcelroy** [comment]
> Envoy treats some headers as special, including this server header and content-length, and it overrides any plugin (e.g. istio) actions when HTTP specification suggests it. For example, empty bodies are going to have content length 0 because that's what clients expect.
> 
> Do you have an issue with the server header itself, or the value that the header is set to?

It is a form of CWE-200: Information Exposure (ref: https://cwe.mitre.org/data/definitions/200.html)

This type of leaking of technology choices in HTTP responses allows threat actors to enumerate target environments using certain tools and versions and target them when vulnerabilities are identified.  This is why both internal SecOps teams and external pen testers will routinely flag Server banners that include tech choices and version numbers as low to medium issues for engineering teams to address.

**Comment by kyessenov** [comment]
Regarding server header, this should be doable given this option exists https://github.com/envoyproxy/data-plane-api/blob/master/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto#L166

**Comment by pingz** [comment]
I'm testing something like:

`apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: server-name-tweaks
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER # http connection manager is a filter in Envoy
    match:
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
    patch:
      operation: MERGE
      value:
        config:
          server_name: "custom server name"
`

notice that the example codes on current `EnvoyFilter` documents does not work on istio 1.3.0 , current MEGER operation only accept `config` as input.

**Comment by angulito** [comment]
First of all, the `server` header cannot be deleted using the `response_headers_to_delete` from envoy because this header is manipulated by the connection manager.
In the [envoy-proxy connection manager](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/http_connection_manager/v2/http_connection_manager.proto), there are two parameters which allow you to manipulate the `server` header:
- server_name
- server_header_transformation

`server_header_transformation` is an option to decide what transformation we want to do to the server header. By default, it overwrites any server header with the contents of `server_name`. It means that if you leave it as it is and fill out the `server_name` with a static value, `server_name` will be always overridden with that value

note: I don't have any experience with Istio so I cannot test this behaviour in Istio - I'm not sure if they already support this option (because it depends on the envoy-proxy version they are using)

**Comment by yacut** [comment]
@pingz Thank you for the solution. It does work on Istio 1.3.4.
P.S. Please add the `apiVersion` field to your yaml example.

**Comment by donbowman** [comment]
is the above EnvoyFilter JSON patch the best option?
many people have the same issue (a pentest is performed, this shows up on the fail list), it seems like a simpler option would be better.

**Comment by seanmcelroy** [comment]
While changing the server name to a static value resolves the information leakage security issue, is there a way to simply remove the server header completely?  (This was the original poster's question.)

**Comment by prestonvanloon** [comment]
How can we reopen this issue?

**Comment by tnm** [comment]
This really needs a much simpler solution for anyone working at scale; probably a single configuration variable. 

Most good security/audit teams — and the compliance checks that come along with them — will grade down any servers exposing `server` as information exposure. As it stands, most users expose implementation data via `curl` to public clients.

`nginx` does it with `server_tokens off;`, apache with `ServerSignature Off`, etc etc.

**Comment by softcane** [comment]
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: remove-server-header-filter
  namespace: sonic-test
spec:
  workloadSelector:
    labels:
      service.istio.io/canonical-name: 
istio-ingressgateway
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
      patch:
        operation: MERGE
        value:
          config:
            server_header_transformation: PASS_THROUGH
```

This enjoy filter will remove the server header.

**Comment by angelovopsan** [comment]
@softcane, how can I adapt this for 1.2.10, I get:
Error from server: error when creating "envoyfilter.yaml": admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: envoy filter: missing filters when I apply in istio-namespace.

**Comment by frank-carnovale** [comment]
Just to clarify patch by @softcane above.. this does not actually guarantee removal of the server header; what it does do is it stops envoy from overwriting the server header that came back from upstream, hence the phrase PASS_THROUGH.  

Also note that from Envoy 1.7.0 it looks like these headers can be suppressed after all.. https://www.envoyproxy.io/docs/envoy/v1.7.0/api-v2/config/filter/http/router/v2/router.proto

**Comment by xring** [comment]
just wondering does this feature available in Istio 1.6.7?

**Comment by joostfarla** [comment]
In Istio 1.7.2, the following filter configuration worked for me:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  namespace: istio-system
  name: replace-server-name
spec:
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.http_connection_manager
      patch:
        operation: MERGE
        value:
          typed_config:
            '@type': type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
            server_name: 'undefined'
```

**Comment by natanaelfonseca** [comment]
> In Istio 1.7.2, the following filter configuration worked for me:
> 
> ```yaml
> apiVersion: networking.istio.io/v1alpha3
> kind: EnvoyFilter
> metadata:
>   namespace: istio-system
>   name: replace-server-name
> spec:
>   workloadSelector:
>     labels:
>       istio: ingressgateway
>   configPatches:
>     - applyTo: NETWORK_FILTER
>       match:
>         context: GATEWAY
>         listener:
>           filterChain:
>             filter:
>               name: envoy.http_connection_manager
>       patch:
>         operation: MERGE
>         value:
>           typed_config:
>             '@type': type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
>             server_name: 'undefined'
> ```

It worked for me, tks.

**Comment by nrjpoddar** [comment]
@howardjohn any suggestions/concerns in elevating this configuration option to a first class API so users don't need to rely on EnvoyFilter? Happy to discuss it during Networking WG but let's do the first round of back and forth on this issue.

**Comment by howardjohn** [comment]
Sure, I am not against that. But also not clear what the API should be exactly, so we should discuss. There are probably a bunch of envoy headers that are relevant

**Comment by jsolv** [comment]
I managed to remove Server header. Example:
`apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  namespace: istio-system
  name: remove-server-header
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.http_connection_manager
      patch:
        operation: MERGE
        value:
          typed_config:
            '@type': type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
            server_header_transformation: PASS_THROUGH
---            
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ecosystem
spec:
  hosts:
  - example.com
  gateways:
  - example
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: example
        port:
          number: 8080
      headers:
        response:
          remove:
          - Server`

**Comment by nrjpoddar** [comment]
Thanks @jsolv Why is the VS needed? Isn't the passthrough settings alone sufficient?

**Comment by jsolv** [comment]
@nrjpoddar it's depends. If `Server` header not added before `VirtualService` by any service then we can use only `server_header_transformation: PASS_THROUGH`.
From envoy docs:
```
OVERWRITE
(DEFAULT) ⁣Overwrite any Server header with the contents of server_name.

APPEND_IF_ABSENT
⁣If no Server header is present, append Server server_name If a Server header is present, pass it through.

PASS_THROUGH
⁣Pass through the value of the server header, and do not append a header if none is present.
```
`PASS_THROUGH` just keeping `Server` header untouched.

**Comment by jsolv** [comment]
@nrjpoddar I think it will be enough for **istio** to setting `server_header_transformation` to **`PASS_THROUGH`** by _default_. Then we will can **add**, **remove**, or **override** any headers with `VirtualService` if needed or passing headers through from applications.

**Comment by PeterClaes** [comment]
@jsolv, It doesn't seem to work on Istio 1.8.2 :-(

**Comment by nrjpoddar** [comment]
We discussed this during Feb 11 2021 Networking WG meeting and agreed on configuring Envoy to always set Server header value as `PASS_THROUGH` instead of the currently configured override value.

**Comment by howardjohn** [comment]
@nrjpoddar sorry I missed the meeting. Do we expect that anyone *depends* on the `server: istio-envoy` header? I am certain our docs tests do at the very least

**Comment by nrjpoddar** [comment]
> @nrjpoddar sorry I missed the meeting. Do we expect that anyone _depends_ on the `server: istio-envoy` header? I am certain our docs tests do at the very least

I doubt it. We did the discuss the option of making this configurable to enable migration but this behaviour is not documented (afaik) and no one on the call knew of any legitimate use cases.

**Comment by jsolv** [comment]
> @jsolv, It doesn't seem to work on Istio 1.8.2 :-(
this is strange, because I have updated my istio to 1.8.2 and this solution still work

**Comment by jsolv** [comment]
> @jsolv, It doesn't seem to work on Istio 1.8.2 :-(

 this is strange, because I have updated my istio to 1.8.2 and this solution still work

**Comment by jsolv** [comment]
@nrjpoddar good news! thx guys!

**Comment by PeterClaes** [comment]
> > @jsolv, It doesn't seem to work on Istio 1.8.2 :-(
> 
> this is strange, because I have updated my istio to 1.8.2 and this solution still work

@jsolv :  Sorry, my mistake. it works. I was using  envoy API and had a typo in it. Working typed_config with envoy api v3 : 
`
      value:
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          server_header_transformation: PASS_THROUGH
  `

**Comment by httran13** [comment]
Hello, i have istio 1.8.3 and can't seem to remove the header we a few of the solns above. I tried restarting my deployments as well.

my envoy filter is below, am i missing anything else?

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  namespace: istio-system
  name: replace-server-name
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.http_connection_manager
      patch:
        operation: MERGE
        value:
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            server_header_transformation: PASS_THROUGH
            ```

huysmacbookibm:dev-env huytran$ istioctl version --remote
client version: 1.8.1
control plane version: 1.8.3
data plane version: 1.8.3 (8 proxies)
huysmacbookibm:dev-env huytran$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-13T13:22:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15+IKS", GitCommit:"6aaff2c2e616933799bce6aea81abb00454376de", GitTreeState:"clean", BuildDate:"2021-01-15T04:16:00Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
huysmacbookibm:dev-env huytran$

**Comment by rvennam** [comment]
@httran13 I just tried your envoyfilter on 1.8.3 and it's working for me:
```
$ curl -I 169.62.142.131
HTTP/1.1 404 Not Found
content-type: text/plain; charset=utf-8
x-content-type-options: nosniff
date: Tue, 02 Mar 2021 00:42:05 GMT
content-length: 19
x-envoy-upstream-service-time: 4
server: istio-envoy

$ k apply -f ./remove-header.yaml
envoyfilter.networking.istio.io/replace-server-name created

$ curl -I 169.62.142.131
HTTP/1.1 404 Not Found
content-type: text/plain; charset=utf-8
x-content-type-options: nosniff
date: Tue, 02 Mar 2021 00:42:31 GMT
content-length: 19
x-envoy-upstream-service-time: 5
```

**Comment by anton-v-ivanov** [comment]
In case if anyone still needs this, I used these filters to remove the `server` and the `x-envoy-upstream-service-time` headers (istio 1.9.0)

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: response-server-passthrough-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
            server_header_transformation: PASS_THROUGH
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: response-remove-headers-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.lua
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
          inlineCode: |
            function envoy_on_response(response_handle)
              response_handle:headers():remove("x-envoy-upstream-service-time")
              response_handle:headers():remove("server")
            end
```

**Comment by alx13** [comment]
Without lua:
```
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: gateway-response-server-passthrough
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
            server_header_transformation: PASS_THROUGH
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: gateway-response-remove-headers
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: ROUTE_CONFIGURATION
    match:
      context: GATEWAY
    patch:
      operation: MERGE
      value:
        response_headers_to_remove:
        - "x-envoy-upstream-service-time"
        - "server"
```

**Comment by vvatlin** [comment]
Still have issues with the server header. 
How is it possible to remove it ? or Set to "Unknown" for example.

**Comment by johnzheng1975** [comment]
How to change server in latest envoy version:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ef-removeserver
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER 
    match:
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          server_name: "My Server"
```

**Comment by johnzheng1975** [comment]
How to remove header in latest envoy version, works for me, FYI  (istio1.15.5)
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ef-removeserver
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER 
    match:
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          server_header_transformation: PASS_THROUGH
  - applyTo: ROUTE_CONFIGURATION
    patch:
      operation: MERGE
      value:
        response_headers_to_remove:
        - "x-envoy-upstream-service-time"
        - "server"
```

**Comment by lkreimann** [comment]
Hi @johnzheng1975, both of your most recent examples don't work for me on Istio 1.21.x.

Can you confirm that your examples work on this version of Istio?

**Comment by zirain** [comment]
> Hi @johnzheng1975, both of your most recent examples don't work for me on Istio 1.21.x.
> 
> Can you confirm that your examples work on this version of Istio?

the latest version of istio is 1.17.2

**Comment by lkreimann** [comment]
Whoopsie, I probably mixed some things up. I'm gonna check my versions

**Comment by SebTardif** [comment]
@johnzheng1975 It's working well. However, I cannot make sense of the first applyTo block. I asked ChatGPT, but that didn't help!

**Comment by SMRehanRizvi** [comment]
> How to remove header in latest envoy version, works for me, FYI (istio1.15.5)
> 
> ```
> apiVersion: networking.istio.io/v1alpha3
> kind: EnvoyFilter
> metadata:
>   name: ef-removeserver
>   namespace: istio-system
> spec:
>   configPatches:
>   - applyTo: NETWORK_FILTER 
>     match:
>       listener:
>         filterChain:
>           filter:
>             name: "envoy.filters.network.http_connection_manager"
>     patch:
>       operation: MERGE
>       value:
>         typed_config:
>           "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
>           server_header_transformation: PASS_THROUGH
>   - applyTo: ROUTE_CONFIGURATION
>     patch:
>       operation: MERGE
>       value:
>         response_headers_to_remove:
>         - "x-envoy-upstream-service-time"
>         - "server"
> ```

@johnzheng1975 it works

**Comment by pbr0ck3r** [comment]
This filter works for anything coming in on ports 80/443 (removes `server: istio-envoy`, but when I hit the port health/ready port `15021`, `server: envoy` is being returned. Tried adding a `HTTP_FILTER` but may be going down the wrong path. Here is my HTTP_FILTER (which is not valid). 

```
- applyTo: HTTP_FILTER
      match:
        listener:
          filterChain:
            filter:
              name: envoy.filters.http.header_mutation
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.header_mutation.v3.HeaderMutation
            mutations:
              response_mutations:
                remove:
                  - "server"
```
