### ISSUE TITLE
VirutalService traffic management for persistent connection service

### ISSUE THREAD

**Issue by zhiqli** [istio/istio#13908]
I want to use VirtualService traffic management for persistent connection service.like this 
![image](https://user-images.githubusercontent.com/3350002/57357833-7a303400-71a6-11e9-84f8-5a0808c388a9.png)
my VirtualService and DestinationRule like this
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: phub-ipv6-reporter
  namespace: istio-phub-ipv6
spec:
  host: phub-ipv6-reporter
  #trafficPolicy:
  #  loadBalancer:
  #    simple: RANDOM
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: phub-ipv6-reporter-vs
  namespace: istio-phub-ipv6
spec:
  hosts:
    - phub-ipv6-reporter
  http:
  - route:
    - destination:
        host: phub-ipv6-reporter
        subset: v1
      weight: 90
    - destination:
        host: phub-ipv6-reporter
        subset: v2
      weight: 10
```

Now,I change the weight 20% to v1 80% to v2。After a while, there is no work，still 90% to v1,10% to v2。
And after i delete pod serverA , new serverA pod build it‘s work。I think the reason it doesn't work is that the serverA and reporter is persistent connection 

**I want to know how to take effect without restarting.**

> btw，my istio version is 1.1.5

**Comment by linsun** [comment]
what do you mean by persistent connection service?  any sample out that is using it?

**Comment by howardjohn** [comment]
> I want to know how to take effect without restarting.

What do you mean by this? Restarting the pod?

As far as I know, Envoy won't intentionally close the connections just to get the load balancing even, it will only apply to new connections. We face a similar issue with the connection between Envoy and Pilot, which is long lasting. 

Maybe there is a better solution, but one possible answer is to reconnect every X minutes, so that a new connection will be made and it will be load balanced

**Comment by zhiqli** [comment]
@howardjohn i am delete pod after modify VirtualService.

**Comment by zhiqli** [comment]
@howardjohn Now i am delete pod after modify VirtualService.
It seems that it can reconnect every X minutes to solve this problem。
Thank you very much.

**Comment by zhiqli** [comment]
@linsun it's mean two service keep connected.

**Comment by anticpp** [comment]
Istio uses [envoy traffic shifiting/splitting](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/traffic_splitting#id2) to do traffic management. Which envoy makes use of multiple upstream/cluster to route requests, each upstream/cluster handle unique connection management internal envoy.

Thus, I don't think there is any `long-connection` issue for request loadbalance, because you can route request to any connections regardless of whether this is a new connection or not?

So, I think there are more internal situations why this test won't work.

**Comment by zhiqli** [comment]
hey @howardjohn

**Comment by zhiqli** [comment]
hi @howardjohn @anticpp  I did some testing on envoy's Traffic splitting, reference the envoy doc [https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/traffic_splitting#traffic-splitting-across-multiple-upstreams](url)

my demo like this 
![image](https://user-images.githubusercontent.com/3350002/57513507-01b1aa80-7341-11e9-86a2-950e0ad3a9a5.png)
Between services is grpc long connection。
```
the envoy config like this
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
                - match: 
                    prefix: "/"
                    grpc: {}
                  route:
                    weighted_clusters:
                      runtime_key_prefix: routing.traffic_split
                      clusters:
                        - name: service1
                          weight: 90
                        - name: service2
                          weight: 10
          http_filters:
          - name: envoy.router
            typed_config: {}
  clusters:
  - name: service1
    connect_timeout: 2s
    type: strict_dns
    lb_policy: round_robin
    http2_protocol_options: {}
    load_assignment:
      cluster_name: service1
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 192.168.65.2 
                port_value: 9090
  - name: service2
    connect_timeout: 2s
    type: strict_dns
    lb_policy: round_robin
    http2_protocol_options: {}
    load_assignment:
      cluster_name: service2
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 192.168.65.2 
                port_value: 9091 
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```
At first,90% traffic to server1 and 10% traffic to server2, then i use runtime_modify api modify weight traffic 10% to server1 and 90% to server2。I saw that this modification is valid。
So I think if istio should also support this kind of traffic splitting？

**Comment by howardjohn** [comment]
VirtualServices should be generating a similar config. If this is not the case, can your add the output of `curl localhost:15000/config_dump` from the sidecar

**Comment by zhiqli** [comment]
![image](https://user-images.githubusercontent.com/3350002/57592676-82072400-756a-11e9-8033-b172db9f6797.png)
hi @howardjohn  In `reporter v1` and `report v2` sidecar, the output of curl localhost:15000/config_dump like this.
```
curl localhost:15000/config_dump | grep weight
         "weighted_clusters": {
              "weight": 10,
              "weight": 90,
           "weighted_clusters": {
              "weight": 10,
              "weight": 90,
           "weighted_clusters": {
              "weight": 10,
              "weight": 90,
```
then i change `VirtualService`
```
  - route:
    - destination:
        host: phub-ipv6-reporter
        subset: v1
      weight: 60
    - destination:
        host: phub-ipv6-reporter
        subset: v2
      weight: 40
```
after a few seconds， In `reporter v1` and `report v2` sidecar, Can see that it has taken effect.
```
curl localhost:15000/config_dump | grep weight
         "weighted_clusters": {
              "weight": 60,
              "weight": 40,
           "weighted_clusters": {
              "weight": 60,
              "weight": 40,
           "weighted_clusters": {
              "weight": 60,
              "weight": 40,
```
but，when i request from client，the request is still 10% to v1， 90% to v2。Until I delete pod serverA pull up a new pod。
