### ISSUE TITLE
pod & node affinity, unify configuration options & add samples to documentation

### ISSUE THREAD

**Issue by peter-fe** [istio/istio#13912]
Currently node and pod affinity configuration is way different in style and options available. Also the documentation is lacking samples, so it's quite hard to figure out the syntax needed (especially when using Helm and --set)  

The pod affinity settings are way more flexible currently, so it's possible to set the operator as well as defining multiple values (by using comma separation).
So extending the current node affinity configuration options by the ones pod affinity already supports would be a great benefit and a more uniform way of setting these options.

Also extending the documentation would greatly improve the usability.
I can volunteer if it's just unifying the two approaches, but would have to leave it to more capable hands if a more sophisticated approach is preferred .

**Comment by linsun** [comment]
@peter-fe please elaborate what you are thinking with some examples perhaps?
I agree with making it consistent and easier to configure in general.

cc @morvencao

**Comment by peter-fe** [comment]
@linsun sorry for the late reply, was quite busy.
Currently if you compare the nod affinity option you can set via Helm with the option for anti affinity, they are quite different.

```
{{- define "nodeAffinityRequiredDuringScheduling" }}
      nodeSelectorTerms:
      - matchExpressions:
        - key: beta.kubernetes.io/arch
          operator: In
          values:
        {{- range $key, $val := .Values.global.arch }}
          {{- if gt ($val | int) 0 }}
          - {{ $key }}
          {{- end }}
        {{- end }}
        {{- $nodeSelector := default .Values.global.defaultNodeSelector .Values.nodeSelector -}}
        {{- range $key, $val := $nodeSelector }}
        - key: {{ $key }}
          operator: In
          values:
          - {{ $val }}
        {{- end }}
{{- end }}
``` 

As you can see the operator is fixed and it is only possible to set one $val, so in case you like to enable multiple pools where Istio is allowed to spin up that's not possible.
The anti affinity part is more flexible in that regard.

```
{{- define "podAntiAffinityPreferredDuringScheduling" }}
    {{- range $index, $item := .Values.podAntiAffinityTermLabelSelector }}
    - podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: {{ $item.key }}
            operator: {{ $item.operator }}
            {{- if $item.values }}
            values:
            {{- $vals := split "," $item.values }}
            {{- range $i, $v := $vals }}
            - {{ $v }}
            {{- end }}
            {{- end }}
        topologyKey: {{ $item.topologyKey }}
    {{- end }}
{{- end }}
``` 

Here all options can be set via configuration, though I'm not 100% convinced that delimiter splitting is appropriate for that, maybe going into list would better conform Helm, so providing values as {val1, val2, val3} (at least for Helm --set) would make more sense.

Regarding the [documentation](https://istio.io/docs/reference/config/installation-options-changes/#new-global-key-value-pairs), it's quite limited there is only {} as a sample value, here a more explicit sample would make more sense.
When thinking of unifying and making more config options available a more explicit value.yaml config would be possible, maybe with all options set, just without the value, so it is ignored during execution as long as no value property is set.

**current values.yaml**
```
# Common settings used among istio subcharts.
global:

  # Default node selector to be applied to all deployments so that all pods can be
  # constrained to run a particular nodes. Each component can overwrite these default
  # values by adding its node selector block in the relevant section below and setting
  # the desired values.
  defaultNodeSelector: {}
```

**could maybe better expressed like this (dummy config)**
```
# Common settings used among istio subcharts.
global:

  # Default node selector to be applied to all deployments so that all pods can be
  # constrained to run a particular nodes. Each component can overwrite these default
  # values by adding its node selector block in the relevant section below and setting
  # the desired values.
  defaultNodeSelector:
  - key: sampleKey
    operator: In
    values:
      node-pool1
      node-pool2
```

**or as sample without value, so it doesn't get processed but can stay as reference in the values**
```
# Common settings used among istio subcharts.
global:

  # Default node selector to be applied to all deployments so that all pods can be
  # constrained to run a particular nodes. Each component can overwrite these default
  # values by adding its node selector block in the relevant section below and setting
  # the desired values.
  defaultNodeSelector:
  - key: sampleKey
    operator: In
    values:
```
