### ISSUE TITLE
"istioctl kube-inject -f -" JSON support has inconsistent behavior than kubectl

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1394]
@kilianc commented on [Sat Aug 26 2017](https://github.com/istio/old_pilot_repo/issues/1108)

given:

```json
{
  "apiVersion": "v1",
  "kind": "Secret",
  "metadata": {
    "name": "service-name"
  },
  "data": {
  }
}
{
  "apiVersion": "extensions/v1beta1",
  "kind": "Deployment",
  "metadata": {
    "name": "service-name"
  }
}
```

I get : `Error: error converting YAML to JSON: yaml: line 9: did not find expected <document start>`
while it works in `kubectl`.

Strange enough, if I add `---` in between documents it will work for `istioctl` and fail for `kubectl`.

---

@gyliu513 commented on [Mon Aug 28 2017](https://github.com/istio/old_pilot_repo/issues/1108#issuecomment-325289098)

@kilianc the file is not right, it should be as following:
```
{
  "apiVersion": "v1",
  "kind": "Secret",
  "metadata": {
    "name": "service-name"
  },
  "data": {
  }
}
---
{
  "apiVersion": "extensions/v1beta1",
  "kind": "Deployment",
  "metadata": {
    "name": "service-name"
  }
}
```

Added `---` as separation for two different templates.

My test steps:

1) Get the template file.
```
root@pc002:~/test# cat a.yaml
{
  "apiVersion": "v1",
  "kind": "Secret",
  "metadata": {
    "name": "service-name"
  },
  "data": {
  }
}
---
{
  "apiVersion": "extensions/v1beta1",
  "kind": "Deployment",
  "metadata": {
    "name": "service-name"
  }
}
```

2) Inject data.
```
root@pc002:~/test# istioctl kube-inject -f ./a.yaml
{
  "apiVersion": "v1",
  "kind": "Secret",
  "metadata": {
    "name": "service-name"
  },
  "data": {
  }
}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    alpha.istio.io/sidecar: injected(deprecated)
    status.sidecar.istio.io: injected-version-@--
  creationTimestamp: null
  name: service-name
spec:
  strategy: {}
  template:
    metadata:
      annotations:
        alpha.istio.io/sidecar: injected(deprecated)
        status.sidecar.istio.io: injected-version-@--
      creationTimestamp: null
    spec:
      containers:
      - args:
        - proxy
        - -v
        - "2"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: 'docker.io/istio/proxy_debug:'
        imagePullPolicy: IfNotPresent
        name: istio-proxy
        resources: {}
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 1337
        volumeMounts:
        - mountPath: /etc/istio/config
          name: istio-config
          readOnly: true
        - mountPath: /etc/istio/proxy
          name: istio-envoy
        - mountPath: /etc/certs
          name: istio-certs
          readOnly: true
      initContainers:
      - args:
        - -p
        - "15001"
        - -u
        - "1337"
        image: 'docker.io/istio/proxy_init:'
        imagePullPolicy: IfNotPresent
        name: istio-init
        resources: {}
        securityContext:
          capabilities:
            add:
            - CAP_NET_ADMIN
          privileged: true
      - args:
        - -c
        - sysctl -w kernel.core_pattern=/etc/istio/proxy/core.%e.%p.%t && ulimit -c
          unlimited
        command:
        - /bin/sh
        image: alpine
        imagePullPolicy: IfNotPresent
        name: enable-core-dump
        resources: {}
        securityContext:
          privileged: true
      volumes:
      - configMap:
          name: istio
        name: istio-config
      - emptyDir:
          medium: Memory
          sizeLimit: "0"
        name: istio-envoy
      - name: istio-certs
        secret:
          secretName: istio.default
status: {}
---
```

---

@gyliu513 commented on [Mon Aug 28 2017](https://github.com/istio/old_pilot_repo/issues/1108#issuecomment-325290775)

@kilianc seems your template for deployment is not valid.

```
root@pc002:~/test# cat b.yaml
{
  "apiVersion": "extensions/v1beta1",
  "kind": "Deployment",
  "metadata": {
    "name": "service-name"
  }
}
```

```
root@pc002:~/test# kubectl create -f ./b.yaml
The Deployment "service-name" is invalid:
* spec.selector: Required value
* spec.template.metadata.labels: Invalid value: map[string]string(nil): `selector` does not match template `labels`
* spec.template.spec.containers: Required value
```

---

@kilianc commented on [Mon Aug 28 2017](https://github.com/istio/old_pilot_repo/issues/1108#issuecomment-325360349)

@gyliu513  I just made the example up so it is very likely. But I tried with a valid configuration and I get the error.

While `kubectl` accepts the `\n` separated list and `istioctl` doesn't, `istioctl` accepts `\n---` and kubectl `doesn't`.

I am not sure which one is valid, it was just a odd inconsistency.

---

@ayj commented on [Mon Aug 28 2017](https://github.com/istio/old_pilot_repo/issues/1108#issuecomment-325430769)

kube-inject uses `k8s.io/apimachinery/pkg/util/yaml::yaml.NewYAMLReader()` which doesn't handle multi-doc JSON files. We may need something similar to [YAMLOrJSONDecoder](https://github.com/kubernetes/apimachinery/blob/master/pkg/util/yaml/decoder.go#L216) to handle multi-doc files for JSON *and* YAML.

---

@gyliu513 commented on [Tue Aug 29 2017](https://github.com/istio/old_pilot_repo/issues/1108#issuecomment-325678156)

@ayj so why does following json file works with `istioctl kube-inject`?

```
root@pc002:~/test# cat a.yaml
{
  "apiVersion": "v1",
  "kind": "Secret",
  "metadata": {
    "name": "service-name"
  },
  "data": {
  }
}
---
{
  "apiVersion": "extensions/v1beta1",
  "kind": "Deployment",
  "metadata": {
    "name": "service-name"
  }
}
```

---

@ayj commented on [Tue Aug 29 2017](https://github.com/istio/old_pilot_repo/issues/1108#issuecomment-325711094)

Two reasons: (1) `NewYAMLReader` uses `---` as deliminator for parsing out multiple documents from a single file and (2) github.com/ghodss/yaml is used for (un)marshaling individual documents. This results in a weird combination of using YAML document markers with JSON objects.
