### ISSUE TITLE
Unable to route/proxy to external site

### ISSUE THREAD

**Issue by mabushey** [istio/istio#13968]
**Bug description**
I would like google.example.com to serve up google.com. I can serve up internal sites just fine, and in a pod I can curl external sites.

I have Istio 1.1.2 installed via the awesome Bonzai operator.

I can curl external sites, so I don't think I actually need a ServiceEntry
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google
spec:
  hosts:
  - www.google.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: google
spec:
  hosts:
  - google.example.com
  gateways:
  - elb-gateway.istio-system.svc.cluster.local
  http:
  - match:
    route:
    - destination:
#       host: httpbin.httpbin.svc.cluster.local  # This works for Internal
       host: www.google.com
```

I've tried with other http sites (google is https only). I'm doing SSL termination on the ELB, so Istio would need to create a new SSL connection, which works fine in a pod via curl. All I get at google.example.com are 503's.

**Comment by mbanikazemi** [comment]
can you use the -v option with curl and see what is going wrong and report back please.

**Comment by mabushey** [comment]
```
✗ curl -v https://google.example.com
* Rebuilt URL to: https://google.example.com/
*   Trying 52.41.xxx.xxx...
* TCP_NODELAY set
* Connected to google.example.com (52.41.xxx.xxx) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=example.com
*  start date: Mar 26 00:00:00 2019 GMT
*  expire date: Apr 26 12:00:00 2020 GMT
*  subjectAltName: host "google.example.com" matched cert's "*.example.com"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: google.example.com
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 503 Service Unavailable
< content-length: 57
< content-type: text/plain
< date: Tue, 14 May 2019 20:12:42 GMT
< server: envoy
<
* Connection #0 to host google.example.com left intact
upstream connect error or disconnect/reset before headers%
```

**Comment by mbanikazemi** [comment]
is this above correct?
``` gateways:
  - elb-gateway.istio-system.svc.cluster.local```

**Comment by mabushey** [comment]
@mbanikazemi yes, If I change the destination host from `host: www.google.com` to `host: httpbin.httpbin.svc.cluster.local` I then get the httpbin app going to google.example.com. I have Grafana, Jaeger, Ceph dashboard, and several custom services listening on that gateway.

**Comment by mabushey** [comment]
Is there a reason Istio can't proxy external sites?

**Comment by mbanikazemi** [comment]
Sorry for late response. I think you need to direct traffic to your egress gateway. What you have in your virtual service says what to do with the requests that get there but to get requests from pods in your mesh to the gateway you need a virtual service. Something like the following:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-cnn-through-egress-gateway
spec:
  hosts:
  - edition.cnn.com
  gateways:
  - istio-egressgateway
  - mesh
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: cnn
        port:
          number: 80
      weight: 100
  - match:
    - gateways:
      - istio-egressgateway
      port: 80
    route:
    - destination:
        host: edition.cnn.com
        port:
          number: 80
      weight: 100
```
frpm `https://istio.io/docs/examples/advanced-gateways/egress-gateway/`. 
But the fact that this works for local services as you have mentioned, suggests requests get to the gateway? In that case I am not sure, how and the above perhaps won't be helpful.
