### ISSUE TITLE
Rule not matching with match: true; no actions

### ISSUE THREAD

**Issue by prestonvanloon** [istio/istio#14029]
**Bug description**

I'm trying to add additional HTTP headers to understand the backend that is being load balanced. The follow rule seems to have no effect.

```yaml
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: example
  namespace: istio-system
spec:
  match: "true" # match for all requests
  actions: []
  responseHeaderOperations:
  - name: x-backend
    values: [ destination.name || "unknown" ]
  - name: x-service
    values: [ destination.service.host || "unknown" ]
```

**Expected behavior**

I expected to see `x-backend: something` header

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.4-10-g9b6d31b"}

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-gke.6", GitCommit:"394ee507d00f15a63cef577a14026096c310698e", GitTreeState:"clean", BuildDate:"2019-03-30T19:31:43Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by prestonvanloon** [comment]
I finally looked at mixer logs and it complained about the OR statement, which was unnecessary and that destination.service.host does not exist.

This is a working config:
```yaml
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: example
  namespace: istio-system
spec:
  match: "true" # match for all requests
  responseHeaderOperations:
  - name: x-backend
    values: [ destination.name ]
```
