### ISSUE TITLE
Wildcard virtual host not created for non-port 80 service

### ISSUE THREAD

**Issue by arnecls** [istio/istio#14033]
**Bug description**

We've got a service entry targeting two ports, using a wildcard name.  
First port is 80, second is 6565. We resolve the name statically, as we have multiple ingress-IPs being used as an entrypoint and want to force-route it to the one supposed to be used for the cluster.
* When using `host: *.foo.bar` in the service entry, routing to port 80 works, but not to 6565.
* When using `host: foo.bar` in combination with a virtual host, port 6565 works, but port 80 does not.

Using `istioctl routes`, we saw that in the first scenario (see below) the virtualhosts entries for port 6565 are missing the `*.foo.bar` entry and only have `foo.bar`. In the second scenario (see below) we see this for port 80.

Our current solution to this:
* Create two different service entries for the same host (one with wildcard, one without) and let a virtual service route to the corresponding one based on port.

Scenario 1: Not working for 6565 but for port 80:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: '{{ $target }}.foo.bar'
spec:
  resolution: 'STATIC'
  location: 'MESH_EXTERNAL'
  hosts:
  - '{{ $target }}.foo.bar'
  addresses: {{ $ips | toYaml | nindent 2 -}}
  endpoints:
    - address: {{ $ips  | first }}
  ports:
  - name: 'http2'
    number: 80
    protocol: 'http2'
  - name: 'grpc'
    number: 6565
    protocol: 'grpc'
```

Scenario 2: Not working for port 80 but works for 6565:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: '*.{{ $target }}.foo.bar'
spec:
  resolution: 'STATIC'
  location: 'MESH_EXTERNAL'
  hosts:
  - '{{ $target }}.foo.bar'
  addresses: {{ $ips | toYaml | nindent 2 -}}
  endpoints:
    - address: {{ $ips  | first }}
  ports:
  - name: 'http2'
    number: 80
    protocol: 'http2'
  - name: 'grpc'
    number: 6565
    protocol: 'grpc'
```

What works:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: 'http.{{ $target }}.foo.bar'
spec:
  resolution: 'STATIC'
  location: 'MESH_EXTERNAL'
  hosts:
  - '{{ $target }}.foo.bar'
  addresses: {{ $ips | toYaml | nindent 2 -}}
  endpoints:
    - address: {{ $ips  | first }}
  ports:
  - name: 'http2'
    number: 80
    protocol: 'http2'
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: 'grpc.{{ $target }}.foo.bar'
spec:
  resolution: 'STATIC'
  location: 'MESH_EXTERNAL'
  hosts:
  - '*.{{ $target }}.foo.bar'
  addresses: {{ $ips | toYaml | nindent 2 -}}
  endpoints:
    - address: {{ $ips  | first }}
  ports:
  - name: 'grpc'
    number: 6565
    protocol: 'grpc'
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: '{{ $target }}.foo.bar'
spec:
  hosts:
  - '*.{{ $target }}.foo.bar'
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: '{{ $target }}.foo.bar'
        port: 
          number: 80
  - match:
    - port: 6565
    route:
    - destination:
        host: '*.{{ $target }}.foo.bar'
        port: 
          number: 6565
```

**Expected behavior**

Virtual hosts entry behavior should be the same for all ports.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

Istio 1.1.5
Kubernetes 1.11.8-gke.6

```bash
istioctl version --remote
client version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.4-10-g9b6d31b"}
citadel version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
galley version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
ingressgateway version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.4-10-g9b6d31b"}
ingressgateway version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.4-10-g9b6d31b"}
ingressgateway version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.4-10-g9b6d31b"}
pilot version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
pilot version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
pilot version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
policy version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
sidecar-injector version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
telemetry version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
telemetry version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
telemetry version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
telemetry version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
telemetry version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
```

```bash
kubectl version
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.9-dispatcher", GitCommit:"e3f5193e8f1091a162af7e17a781e6a3129bcfd0", GitTreeState:"clean", BuildDate:"2019-03-28T18:15:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-gke.6", GitCommit:"394ee507d00f15a63cef577a14026096c310698e", GitTreeState:"clean", BuildDate:"2019-03-30T19:31:43Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**

Via rendering of the official helm chart + kubectl apply.
Config:

```yaml
global:
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY

sidecarInjectorWebhook:
  enableNamespacesByDefault: true
```

**Environment where bug was observed (cloud vendor, OS, etc)**

Google Kubernetes (see version)

**Affected product area (please put an X in all that apply)**

[x] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by mbanikazemi** [comment]
Not sure if you have a typo here but scenario 2 is not valid. Can't have a * in the name of the resource.
It seems to me you can have one service entry for both ports:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: '{{ $target }}.foo.bar'
spec:
  resolution: 'STATIC'
  location: 'MESH_EXTERNAL'
  hosts:
  - '*.{{ $target }}.foo.bar'
  addresses: {{ $ips | toYaml | nindent 2 -}}
  endpoints:
    - address: {{ $ips  | first }}
  ports:
  - name: 'http2'
    number: 80
    protocol: 'http2'
  - name: 'grpc'
    number: 6565
    protocol: 'grpc'
```
and the virtual service as you have defined above. Doesn't that solve the problem?

**Comment by arnecls** [comment]
No, that‘s not a typo. In istio 1.0.x this definitely was not possible but in 1.1 it is. It‘s even mentioned in the [docs](https://istio.io/docs/reference/config/networking/v1alpha3/service-entry/) - see the wikipedia example - although it‘s used for TLS services, which is not the case in my scenarios.
Also I deployed the manifests above to our cluster (with other host names, but the same wildcard usage), and galley did not complain.

**Comment by mbanikazemi** [comment]
For the resource defined under Scenario 2, you have:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: '*.{{ $target }}.foo.bar'
...
```
I am referring to the use of '*' in the name of the object as defined here.  

Have a look at: 
https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names

**Comment by rshriram** [comment]
Lets assume that he has named the resources correctly. This seems to indicate that the virtual host generation code is not picking up the ports for wildcard hosts..

**Comment by mbanikazemi** [comment]
@arnecls I cannot reproduce this. Can you describe two cases: 1- where things do not work; specify exactly what resources you create, and how you test it showing it does not work. 2- where things work;  specify what resources you create, and how you test it showing it does work

**Comment by arnecls** [comment]
Ok, here are the resources that are currently deployed on our cluster.
The critical one is `grpc.stage.europe-west4.nsp.trv.cloud` if I remove the `*` from the hosts there, no wildcard virtual host for 6565 is created, even though there is a virtual service that should do this.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: 'http.stage.europe-west4.nsp.trv.cloud'
  namespace: shared
spec:
  resolution: 'STATIC'
  location: 'MESH_EXTERNAL'
  hosts:
  - 'stage.europe-west4.nsp.trv.cloud'
  addresses: 
  - 10.246.41.242
  - 10.246.41.241
  - 10.246.41.240
  endpoints:
    - address: 10.246.41.242
  ports:
  - name: 'http2'
    number: 80
    protocol: 'http2'
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: 'grpc.stage.europe-west4.nsp.trv.cloud'
  namespace: shared
spec:
  resolution: 'STATIC'
  location: 'MESH_EXTERNAL'
  hosts:
  - '*.stage.europe-west4.nsp.trv.cloud'
  addresses: 
  - 10.246.41.242
  - 10.246.41.241
  - 10.246.41.240
  endpoints:
    - address: 10.246.41.242
  ports:
  - name: 'grpc'
    number: 6565
    protocol: 'grpc'
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: 'stage.europe-west4.nsp.trv.cloud'
  namespace: shared
spec:
  hosts:
  - '*.stage.europe-west4.nsp.trv.cloud'
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: 'stage.europe-west4.nsp.trv.cloud'
        port: 
          number: 80
  - match:
    - port: 6565
    route:
    - destination:
        host: '*.stage.europe-west4.nsp.trv.cloud'
        port: 
          number: 6565
```

Now, if I leave out the `*` in the 6565 service entry and I use `istioctl proxy-config routes dummy-15553 --name 6565 -o json` (replace dummy with any pod with a istio-proxy) I only get:

```json
                "name": "stage.europe-west4.nsp.trv.cloud:6565",
                "domains": [
                    "stage.europe-west4.nsp.trv.cloud",
                    "stage.europe-west4.nsp.trv.cloud:6565",
                    "10.246.41.240",
                    "10.246.41.240:6565"
                ],
                "routes": [
```

Doing the same for route "80" yields:

```json
                "name": "stage.europe-west4.nsp.trv.cloud:80",
                "domains": [
                    "stage.europe-west4.nsp.trv.cloud",
                    "stage.europe-west4.nsp.trv.cloud:80",
                    "10.246.41.240",
                    "10.246.41.240:80"
                ],
                "routes": [
```

too, but also

```json
                "name": "*.stage.europe-west4.nsp.trv.cloud:80",
                "domains": [
                    "*.stage.europe-west4.nsp.trv.cloud",
                    "*.stage.europe-west4.nsp.trv.cloud:80"
                ],
                "routes": [
```

So the expected `"name": "*.stage.europe-west4.nsp.trv.cloud:6565"` is missing.
It does appear as soon as I add the `*` again to the service entry

**Comment by mbanikazemi** [comment]
Thanks @arnecls for the above description. I see the problem. It is indeed because port 80 is treated differently from all other ports. I am going to submit a patch and work on a fix shortly. @rshriram please see the patch (you will recognize the issue immediately) and see if the proposed change makes sense. I have not done a lot of testing so I am going to mark the PR as WIP for now.

 @arnecls with the following, I get the desired setup after the application of the upcoming patch:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: 'http.stage.europe-west4.nsp.trv.cloud'
  namespace: default
spec:
  resolution: 'STATIC'
  location: 'MESH_EXTERNAL'
  hosts:
  - 'stage.europe-west4.nsp.trv.cloud'
  addresses:
  - 10.246.41.242
  - 10.246.41.241
  - 10.246.41.240
  endpoints:
    - address: 10.246.41.242
  ports:
  - name: 'http2'
    number: 80
    protocol: 'http2'
  - name: 'grpc'
    number: 6565
    protocol: 'grpc'
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: 'stage.europe-west4.nsp.trv.cloud'
  namespace: default
spec:
  hosts:
  - '*.stage.europe-west4.nsp.trv.cloud'
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: 'stage.europe-west4.nsp.trv.cloud'
        port:
          number: 80
  - match:
    - port: 6565
    route:
    - destination:
        host: 'stage.europe-west4.nsp.trv.cloud'
        port:
          number: 6565
```
Is this what you want to have? (Please note that in the above example I use the default namespace but others work as well.)
