### ISSUE TITLE
Kiali is showing erroneous traffic

### ISSUE THREAD

**Issue by dbarentine** [istio/istio#14065]
I have two services running and neither interact with each other. I then have a third external service that I've created a service entry for that one of the services talks to over TLS. In Kiali I was expecting it to look like this:
connect-dev -> connectors-example-dev.azurewebsites.net
sts-dev (no traffic either of the above services)

But what Kiali shows is traffic going to the external service which I know is not the case.
![IstioIssue](https://user-images.githubusercontent.com/939865/57662055-5f90fd00-75a2-11e9-97a6-170f69ae8e18.png)

**Expected behavior**
Traffic betwe
[istio-dump.tar.gz](https://github.com/istio/istio/files/3175317/istio-dump.tar.gz)
en sts-dev and connectors-example-dev.azurewebsites.net should not be there.

**Steps to reproduce the bug**
Deploy two services one that calls an external service that is defined as a service entry.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
**istioctl**
client version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.4-10-g9b6d31b"}
citadel version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
egressgateway version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.4-10-g9b6d31b"}
galley version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
ingressgateway version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.4-10-g9b6d31b"}
pilot version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
policy version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
sidecar-injector version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
telemetry version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}

**kubectl**
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:41:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
Helm charts

**Environment where bug was observed (cloud vendor, OS, etc)**
Azure Kubernetes Service

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ X] User Experience

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

[istio-dump.tar.gz](https://github.com/istio/istio/files/3175318/istio-dump.tar.gz)

**Comment by dbarentine** [comment]
It looks like this only happens with external hosts using https. If it's just http then I don't see the problem.

I've tested it using httpbin as the external service with the following configuration:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin-ext
spec:
  hosts:
    - httpbin.org
  ports:
    - number: 443
      name: https
      protocol: TLS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-virtualservice
spec:
  hosts:
    - httpbin.org
  tls:
    - match:
        - port: 443
          sni_hosts:
            - httpbin.org
      route:
        - destination:
            host: httpbin.org
            port:
              number: 443
          weight: 100
```

**Comment by douglas-reid** [comment]
@jmazzitelli any ideas here?

**Comment by josejulio** [comment]
Kiali builds the graph from the telemetry data, from the image it looks like Kiali found more than one time-series for `istio_tcp_sent_bytes_total` that have `destination_service="connectors-example-dev.azurewebsites.net"`

Could you query prometheus to check what time-series are being stored there? 
`istio_tcp_sent_bytes_total{destination_service="connectors-example-dev.azurewebsites.net"}`

**Comment by dbarentine** [comment]
Sorry I had my cluster in a slightly different state so I'm working from a setup that is slightly changed.

This is what I currently see:
![Screenshot from 2019-06-19 09-27-54](https://user-images.githubusercontent.com/939865/59783454-05f0b200-9275-11e9-9300-fe2ce6e1a40b.png)

What is interesting is connect-connectors-example-dev... now only shows traffic from connect-dev as expected. But as you can see I have httpbin.org as another external service which was added first. Neither connect-dev or sts-dev call httpbin.org for anything yet Prometheus and therefore Kiali show traffic.

From Prometheus for httpbin.org:
![Screenshot from 2019-06-19 09-34-02](https://user-images.githubusercontent.com/939865/59783753-b8287980-9275-11e9-8004-164bf2360385.png)

From Prometheus for connect-connectors-example-dev...:
![Screenshot from 2019-06-19 09-24-59](https://user-images.githubusercontent.com/939865/59783767-cb3b4980-9275-11e9-8737-1cf94ebb601c.png)

If I remove httpbin.org as an external service I then see all traffic going to connect-connectors-example-dev again even though I haven't changed anything else:
![Screenshot from 2019-06-19 09-48-07](https://user-images.githubusercontent.com/939865/59784529-80bacc80-9277-11e9-88ca-f19b56c1ad03.png)

![Screenshot from 2019-06-19 09-48-28](https://user-images.githubusercontent.com/939865/59784533-844e5380-9277-11e9-8790-dae39558af6a.png)

**Comment by josejulio** [comment]
How do you have your ServiceEntry, Gateway and VirtualService configured?

For example, with this configuration, every external request points to my `external-svc` (`en.wikipedia.com`)

travels.v1 is running:
```watch "curl https://www.google.com | grep -o '<title>.*</title>'"```

hotels.v1 is running:
```watch "curl https://en.wikipedia.org/wiki/Main_Page | grep -o '<title>.*</title>'"```

discount.v1 is running:
```watch "curl https://www.apple.com | grep -o '<title>.*</title>'"```

But as you can see in the screenshot below, all is going to en.wikipedia.com.

![virtual-service](https://user-images.githubusercontent.com/3845764/59788360-262e6a00-9291-11e9-952d-ecd736adc041.png)

![virtual-servince-p8s](https://user-images.githubusercontent.com/3845764/59788802-254a0800-9292-11e9-91f1-37960cdc44f1.png)


```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc
  namespace : travel-agency
spec:
  hosts:
    - en.wikipedia.com
  exportTo:
    - "."
  location: MESH_EXTERNAL
  ports:
    - number: 443
      name: https
      protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
  namespace: travel-agency
spec:
  selector:
    istio: egressgateway
  servers:
    - port:
        number: 443
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gateway-routing
  namespace: travel-agency
spec:
  hosts:
    - en.wikipedia.com
  exportTo:
    - "*"
  gateways:
    - mesh
    - istio-egressgateway
  http:
    - match:
        - port: 443
          gateways:
            - mesh
      route:
        - destination:
            host: istio-egressgateway.istio-system.svc.cluster.local
    - match:
        - port: 443
          gateways:
            - istio-egressgateway
      route:
        - destination:
            host: en.wikipedia.com
            port:
              number: 443
```

Is your case similar? I'm going to play with the VirtualService/Gateway to see if i can find anything. Maybe @douglas-reid would know.

**Comment by dbarentine** [comment]
The configuration I was using is below. I originally just tried it using a ServiceEntry and no virtual service as well.

I haven't tried configuring it to use an egress gateway although I do have one running.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin-ext
spec:
  hosts:
    - httpbin.org
  ports:
    - number: 443
      name: https
      protocol: TLS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-virtualservice
spec:
  hosts:
    - httpbin.org
  tls:
    - match:
        - port: 443
          sni_hosts:
            - httpbin.org
      route:
        - destination:
            host: httpbin.org
            port:
              number: 443
          weight: 100
```

**Comment by josejulio** [comment]
I repeated the test with only one unrelated ServiceEntry [1], and they all still generate metrics to that ServiceEntry. My workloads are still doing requests on google, apple and wikipedia.

[1]
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-netflix
  namespace : travel-agency
spec:
  hosts:
    - "www.netflix.com"
  exportTo:
    - "."
  location: MESH_EXTERNAL
  ports:
    - number: 443
      name: https
      protocol: HTTPS
  resolution: NONE
```
[2] 
![se-netflix](https://user-images.githubusercontent.com/3845764/59798587-1a01d700-92a8-11e9-894b-105c78b064bc.png)
