### ISSUE TITLE
redis is inaccessible

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1407]
@kyessenov commented on [Thu Aug 17 2017](https://github.com/istio/old_pilot_repo/issues/1055)

A basic redis service appears to be inaccessible:
```
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - port: 6379
    name: tcp
    protocol: TCP
    targetPort: 6379
  selector:
    service: redis
```

---

@sakshigoel12 commented on [Fri Aug 18 2017](https://github.com/istio/old_pilot_repo/issues/1055#issuecomment-323488254)

Please add assignees

---

@ijsnellf commented on [Mon Aug 21 2017](https://github.com/istio/old_pilot_repo/issues/1055#issuecomment-323846806)

Probably related to https://github.com/istio/pilot/issues/964?

---

@linsun commented on [Wed Aug 23 2017](https://github.com/istio/old_pilot_repo/issues/1055#issuecomment-324453526)

Note this is not a headless service.  issue reported:  https://groups.google.com/forum/#!topic/istio-users/7AhQOq9ligg

---

@kyessenov commented on [Mon Sep 11 2017](https://github.com/istio/old_pilot_repo/issues/1055#issuecomment-328626682)

headless TCP PR merged: https://github.com/istio/pilot/pull/1197

---

@kyessenov commented on [Mon Sep 11 2017](https://github.com/istio/old_pilot_repo/issues/1055#issuecomment-328626733)

@ijsnellf can you confirm that this issue can be closed?
