### ISSUE TITLE
how to get application traces without modifying its code

### ISSUE THREAD

**Issue by aliartiza75** [istio/istio#14094]
Hello everyone,

I have deployed istio using Helm Release with the following configurations:

```yaml
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: istio
  namespace: istio-system
spec:
  releaseName: istio
  chart:
    repository: https://raw.githubusercontent.com/IBM/charts/master/repo/stable
    name: ibm-istio
    version: 1.0.5
  values:
    global:
      enableTracing: true
    tracing:
      enabled: true
    jaeger:
      ingress:
        enabled: true
```

The issue that I am facing right now is that I just getting traces for these:

- jaeger query
- jaeger mixer
- jaeger telemetry
- jaeger policy

but no for the other applications

**Comment by objectiser** [comment]
Have you looked at: https://istio.io/help/faq/distributed-tracing/#no-tracing ?

**Comment by aliartiza75** [comment]
@objectiser @douglas-reid  @howardjohn, I am able to get the sample `book-info` application traces but why we need to add [code](https://github.com/istio/istio/blob/3a243984020e891deb3c694af896a315ff26405f/samples/bookinfo/src/productpage/productpage.py#L130) to get information from headers why can't it can't be done by `side-car-container`

**Comment by objectiser** [comment]
@aliartiza75 The code you referenced is just demonstrating how an application can create its own internal spans to enhance the tracing information describing a business transaction.

If your question is about why an application needs to propagate headers, please see https://istio.io/help/faq/distributed-tracing/#istio-copy-headers

**Comment by aliartiza75** [comment]
@objectiser why we need to add code for tracing in our application, why sidecar container can't do it or is there a way to do this. 

If I have to add the code then what purpose does istio serve for enabling tracing?

for instance, if I have 50 microservice developed in different technologies, do I have to add tracing code in each microservices?

**Comment by aliartiza75** [comment]
@objectiser thank you.

**Comment by aliartiza75** [comment]
@objectiser I have another question, which is that when I get traces for the `bookinfo applicaiton` just 1 or 2 times other traces are not being caught by the jaeger. Can can kindly give me some guidelines what it is behaving like that.

**Comment by objectiser** [comment]
@aliartiza75 This is due to the sampling rate, see https://istio.io/docs/tasks/telemetry/distributed-tracing/overview/#trace-sampling

**Comment by aliartiza75** [comment]
@objectiser this is my istio helm release configuration:

```yaml
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: istio
  namespace: istio-system
spec:
  releaseName: istio
  chart:
    repository: https://raw.githubusercontent.com/IBM/charts/master/repo/stable
    name: ibm-istio
    version: 1.0.5
  values:
    global:
      enableTracing: true
    tracing:
      enabled: true
    jaeger:
      ingress:
        enabled: true
    
    pilot:
      traceSampling: 1

```
