### ISSUE TITLE
Prometheus operator doesn't get CPU/memory metrics

### ISSUE THREAD

**Issue by fpesce** [istio/istio#14119]
@howardjohn commented on [Sat May 11 2019](https://github.com/istio/installer/issues/158)

Installed prom operator, and see that dashboards show some stuff, but missing others -- specifically CPU is missing.

Grafana queries for `irate(process_cpu_seconds_total{job="pilot"}[1m])`

But prometheus gets metrics like:

`process_cpu_seconds_total{endpoint="http-monitoring",instance="10.60.36.5:15014",job="istio-pilot",namespace="istio-control",pod="istio-pilot-5f477dfd7b-csffx",service="istio-pilot"}`

The fix isn't that hard but we need to make sure it works for operator and not operator. Probably we update the job name for not operator + grafana dashboard?

---

@howardjohn commented on [Mon May 13 2019](https://github.com/istio/installer/issues/158#issuecomment-491855704)

Doug if you are busy one of us can make the change, just want your insight on best solution

---

@douglas-reid commented on [Mon May 13 2019](https://github.com/istio/installer/issues/158#issuecomment-491910861)

What's missing is the servicemonitors for k8s resources. not clear if Istio should own that or not.

---

@howardjohn commented on [Mon May 13 2019](https://github.com/istio/installer/issues/158#issuecomment-491911591)

It seems we do have these? Or is `kubernetes-pods-monitor` something different? My opinion is anything in the dashboards should work out of the box (even if its a values option) with the operator 

---

@douglas-reid commented on [Mon May 13 2019](https://github.com/istio/installer/issues/158#issuecomment-491913819)

That is distinct.  For CPU, etc., you need the service monitors that mirror the cAdvisor stuff: https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/prometheus/templates/configmap.yaml#L180-L209.

See also: https://github.com/coreos/prometheus-operator/issues/1686#issuecomment-407676698

I think this is the missing piece: https://github.com/coreos/kube-prometheus/blob/master/manifests/prometheus-serviceMonitorKubelet.yaml

---

@howardjohn commented on [Wed May 15 2019](https://github.com/istio/installer/issues/158#issuecomment-492720425)

Endpoint | State | Labels | Last Scrape | Scrape Duration | Error
-- | -- | -- | -- | -- | --
https://10.128.0.25:10250/metrics/cadvisor | DOWN | endpoint="https-metrics" instance="10.128.0.25:10250" namespace="kube-system"node="gke-howardjohn-istio-default-pool-d71c7ad1-z8m7" service="istio-kubelet" | 26.427s ago | 10s | Get https://10.128.0.25:10250/metrics/cadvisor: context deadline exceeded
https://10.128.0.26:10250/metrics/cadvisor | DOWN | endpoint="https-metrics" instance="10.128.0.26:10250" namespace="kube-system"node="gke-howardjohn-istio-default-pool-d71c7ad1-pw77" service="istio-kubelet" | 37.636s ago | 10s | Get https://10.128.0.26:10250/metrics/cadvisor: context deadline exceeded
https://10.128.0.46:10250/metrics/cadvisor | DOWN | endpoint="https-metrics" instance="10.128.0.46:10250" namespace="kube-system"node="gke-howardjohn-istio-default-pool-d71c7ad1-fflb" service="kubelet" | 28.412s ago | 5.398ms | server returned HTTP status 403 Forbidden
https://10.128.0.48:10250/metrics/cadvisor | DOWN | endpoint="https-metrics" instance="10.128.0.48:10250" namespace="kube-system"node="gke-howardjohn-istio-default-pool-d71c7ad1-z8m7" service="kubelet" | 26.629s ago | 3.62ms | server returned HTTP status 403 Forbidden

```yaml
{{- if .Values.prometheus.createKubeletMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubelet-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    monitoring: kubelet
    release: {{ .Release.Name }}
spec:
  endpoints:
  - 
    honorLabels: true
    interval: 30s
    metricRelabelings:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - targetLabel: __address__
      replacement: kubernetes.default.svc:443
    - sourceLabels: [__meta_kubernetes_node_name]
      regex: (.+)
      targetLabel: __metrics_path__
      replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
    path: /metrics/cadvisor
    port: https-metrics
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  jobLabel: kubernetes-cadvisor
  namespaceSelector:
    any: true
  selector:
    matchExpressions:
      - {key: istio-prometheus-ignore, operator: DoesNotExist}
{{- end }}
```

@douglas-reid trying to get it set up to match https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/prometheus/templates/configmap.yaml#L180-L209 but having some difficulties. Seems like we don't have permission?

Any ideas?

---

@douglas-reid commented on [Wed May 15 2019](https://github.com/istio/installer/issues/158#issuecomment-492744446)

Probably something to do with the token stuff (for instance, I bet that secret doesn't exist in your Prom instance). I can help troubleshoot after I finish some other stuff.

---

@howardjohn commented on [Wed May 15 2019](https://github.com/istio/installer/issues/158#issuecomment-492763172)

@douglas-reid the bearerTokenFile does seem to exist in prometheus. Maybe it is invalid, but looks good to me (base64 decoded):

```
{"alg":"RS256","kid":""}{"iss":"kubernetes/serviceaccount","kubernetes.io/serviceaccount/namespace":"istio-prometheus","kubernetes.io/serviceaccount/secret.name":"prometheus-token-5729x","kubernetes.io/serviceaccount/service-account.name":"prometheus","kubernetes.io/serviceaccount/service-account.uid":"6a0299cf-7697-11e9-b9f2-42010a800026","sub":"system:serviceaccount:istio-prometheus:prometheus"}SOMEBINARYDATA
```

I have the prometheus service account too

---

@douglas-reid commented on [Wed May 15 2019](https://github.com/istio/installer/issues/158#issuecomment-492797789)

Well, that's surprising. Needs more investigation, I suppose.

---

@howardjohn commented on [Wed May 15 2019](https://github.com/istio/installer/issues/158#issuecomment-492798961)

@douglas-reid I added a wip PR with what I have now https://github.com/istio/installer/pull/174

If you want my exact setup, https://github.com/istio/tools/pull/122 then run 
`SMALL_INSTALL=1 DNS_DOMAIN=howardjohn.qualistio.org ./setup_istio_new_installer.sh gcr.io/istio-release master-latest-daily` from perf/istio-install folder.

---

@howardjohn commented on [Wed May 15 2019](https://github.com/istio/installer/issues/158#issuecomment-492812187)

@douglas-reid I got a little closer maybe. I manually curled with the bear token I pasted above and get

```
"message": "forbidden: User \"system:serviceaccount:istio-prometheus:prometheus\" cannot get path \"/metrics/cadvisor\": no RBAC policy matched",

```

Then i updated the role to allow /metrics/cadvisor URl, and it works, but I was querying metrics-server not kubelet so it doesn't actually have the metrics.

From what I ahve seen I need to hit the node IP address instead, but when I do that I get 
```
*   Trying 10.128.0.46...
* TCP_NODELAY set
* Connected to 10.128.0.46 (10.128.0.46) port 10250 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 10.128.0.46:10250
* stopped the pause stream!
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 10.128.0.46:10250
```

---

@douglas-reid commented on [Wed May 15 2019](https://github.com/istio/installer/issues/158#issuecomment-492813004)

What if we stop trying to use any tokens whatsoever?  Would that be easier?

Otherwise, we probably need to figure out what the kube-prom setup is doing differently.

---

@howardjohn commented on [Wed May 15 2019](https://github.com/istio/installer/issues/158#issuecomment-492824309)

I get the same problem without passing the token

---

@howardjohn commented on [Wed May 15 2019](https://github.com/istio/installer/issues/158#issuecomment-492827983)

Adding `- nodes/metrics` seems to fix (at least partially)

---

@howardjohn commented on [Wed May 15 2019](https://github.com/istio/installer/issues/158#issuecomment-492829275)

More issues -- `go_goroutines{job="pilot"}` fails because prometheus reports `go_goroutines{job="istio-pilot"}`

`pilot_xds_write_timeout`, etc stats are also using the wrong job.

Its not clear to me what the job means and why its wrong in all of these metrics @douglas-reid 

---

@douglas-reid commented on [Wed May 15 2019](https://github.com/istio/installer/issues/158#issuecomment-492830506)

IIUC, the job stuff is taken from the name of the service when using ServiceMonitors, so yes, this would likely be different than the previous job names (which were taken directly from prom config).
