### ISSUE TITLE
Request routing in 1.1.5 doesn't work for requests coming to a service with an external LB

### ISSUE THREAD

**Issue by aaronjwood** [istio/istio#14221]
**Bug description**
When applying this virtual service:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: 'my-svc-v0.4.53'
  namespace: "myns"
spec:
  hosts:
  - "my-host"
  http:
  - match:
    - headers:
        x-my-service-version:
          exact: "v0.4.53"
    route:
    - destination:
        host: "my-host"
        subset: "v0453"
  - match:
    - headers:
        x-my-service-version:
          exact: "v0.4.58"
    route:
    - destination:
        host: "my-svc"
        subset: "v0458"
```
and these destination rules:
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: my-svc-v0.4.53
  namespace: myns
spec:
  host: my-host
  subsets:
  - name: "v0453"
    labels:
      version: "v0.4.53"
```
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: my-svc-v0.4.58
  namespace: myns
spec:
  host: my-host
  subsets:
  - name: "v0458"
    labels:
      version: "v0.4.58"
```
I see that request routing works as expected for traffic inside the cluster when the headers are used:
`curl -H "x-my-service-version: v0.4.53" -i my-svc/path/to/version`
`curl -H "x-my-service-version: v0.4.58" -i my-svc/path/to/version`

When headers are not used with traffic coming from inside the cluster Envoy correctly throws me back a 404.

When I follow this same flow but instead use the service's LB to hit the service from outside the cluster I see that traffic is round-robin'ed. Even if I make requests from outside the cluster omitting the header the traffic is round-robin'ed. Example of a request coming from the WAN:
`curl -H "x-my-service-version: v0.4.53" my-lb-address/path/to/version`

**Expected behavior**
Request routing for traffic coming from outside the cluster to work in the same way as traffic coming from inside the cluster.

**Steps to reproduce the bug**
Apply a similar virtual service + destination rule config to the ones I posted above and try to hit the service from the WAN using an LB address.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
istioctl version --remote
client version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"brew", Host:"Sierra-2.local", GolangVersion:"go1.12.5", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6"}
citadel version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
galley version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
ingressgateway version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.4-10-g9b6d31b"}
pilot version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
policy version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
sidecar-injector version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
telemetry version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:15:46Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.8", GitCommit:"4e209c9383fa00631d124c8adcc011d617339b3c", GitTreeState:"clean", BuildDate:"2019-02-28T18:40:05Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Installation files generated for a full installation from instructions [here](https://istio.io/docs/setup/kubernetes/install/helm/#option-1-install-with-helm-via-helm-template) and then a `kubectl apply -f istio-crds.yaml && kubectl apply -f istio.yaml`

**Environment where bug was observed (cloud vendor, OS, etc)**
Kubernetes cluster deployed to AWS using kops.

**Affected product area (please put an X in all that apply)**

[x ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
