### ISSUE TITLE
Envoy heapprofiler cannot write to directory

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#14245]
```
istio-proxy@svc02-0v1-55f67fbbf6-wgfg4:/$ curl -X POST localhost:15000/heapprofiler?enable=y
Starting heap profiler
istio-proxy@svc02-0v1-55f67fbbf6-wgfg4:/$ curl -X POST localhost:15000/heapprofiler?enable=n
Heap profiler stopped and data written to /var/log/envoy/envoy.prof. See http://goog-perftools.sourceforge.net/doc/heap_profiler.html for details.
istio-proxy@svc02-0v1-55f67fbbf6-wgfg4:/$ cat /var/log/envoy/envoy.prof
cat: /var/log/envoy/envoy.prof: No such file or directory
```

I think we just need to either give write access to this folder, or update the bootstrap to configure it to write somewhere else.

cc @silentdai

**Comment by silentdai** [comment]
What do you think if the bootstrap set the envoy.prof path to the directory where the bootstrap is?

**Comment by howardjohn** [comment]
> What do you think if the bootstrap set the envoy.prof path to the directory where the bootstrap is?

Seems reasonable to me, especially if it outputs where it goes to. Running the heap profiler is not a day to day thing, so if the location it sends it to isn't intuitive or the best location I don't think its that big of a deal, as long as it goes somewhere.

**Comment by howardjohn** [comment]
@silentdai I made a custom bootstrap with:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-custom-bootstrap-config
  namespace: default
data:
  custom_bootstrap.json: |
    {
      "admin": {
        "profilePath": "/var/lib/istio/envoy/envoy.prof",
        "accessLogPath": "/dev/null",
        "address": {
          "socketAddress": {
            "address": "127.0.0.1",
            "portValue": 15000
          }
        }
      }
    }


```

Still is readonly.. I don't get how we write the bootstrap templates though if it is readonly

Error I get:
```
Dumping heap profile to /var/lib/istio/envoy/envoy.prof.0001.heap (stop and dump)
Failed dumping heap profile to /var/lib/istio/envoy/envoy.prof.0001.heap
```
