### ISSUE TITLE
Virtual Service StringMatch case sensitivity

### ISSUE THREAD

**Issue by JoshKeegan** [istio/istio#14266]
**Describe the feature request**
Looking at [the Istio docs](https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#StringMatch), a Virtual Service StringMatch (exact or prefix) is case sensitive. Envoy appears to expose a `case_sensitive` option for this (see [their docs](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto.html)). Could this be made available within Istio?

e.g:
An app has a health check endpoint on `/health` and I want to add a retry policy on it. I can use:
```yaml
- match:
  - uri:
    exact: /health
  route:
  - destination:
    host: api.app-name.svc.cluster.local
  timeout: 9s 
  retries:
    attempts: 3
    perTryTimeout: 3s      
    retryOn: retriable-4xx,5xx
```

If my app now accepts case insensitive `/health`, (so `/Health`, `/HEALTH` etc... are valid) then I currently need to use regex to match this.

**Describe alternatives you've considered**
Using regex to match with the `/i` flag.

**Additional context**
