### ISSUE TITLE
Does idleTimeout even work?

### ISSUE THREAD

**Issue by Stono** [istio/istio#14310]
Given the following DestinationRule:

```
spec:
  host: solr
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 1024
        http2MaxRequests: 10240
        idleTimeout: 6h
      tcp:
        maxConnections: 10240
        tcpKeepalive:
          interval: 30s
          time: 30s
```

I would expect to see connections only rise for the first six hours, on these two test apps you can see that just isn't the case.  This is 30m following deployments of the two apps.

<img width="1668" alt="Screenshot 2019-05-22 at 20 25 38" src="https://user-images.githubusercontent.com/1486729/58202568-d0859280-7ccf-11e9-817e-f2738d31f134.png">
<img width="1678" alt="Screenshot 2019-05-22 at 20 25 45" src="https://user-images.githubusercontent.com/1486729/58202570-d0859280-7ccf-11e9-8f09-51ac785b9442.png">

These apps have fluctuating request patterns.

Connection fluctuations cause me 503 errors (see https://github.com/istio/istio/issues/13848#issuecomment-494933896)
