### ISSUE TITLE
nginx-ingress controller complete traces are not visible

### ISSUE THREAD

**Issue by aliartiza75** [istio/istio#14328]
Hello everyone,

**Problem description**

I am trying to use [nginx-ingress](https://github.com/helm/charts/tree/master/stable/nginx-ingress) controller with [istio](https://github.com/IBM/charts/tree/master/stable/ibm-istio). The reason for using `nginx-ingress` is that our other services are already using it to create ingress ( a load balancer is attached with `nginx-ingress`) but `istio` creates a new service of type `LoadBalancer` to expose its services. I don't want to use `istio` LoadBalancer instead of it I want to use the `nginx-ingress`  to expose istio services (like jaeger.) 

The flow that I want to implement is given below
```bash
Public Internet -> [nginx-ingress -> envoy] -> [envoy -> upstream-service -> envoy] ... (more services)
```

** Environment and Installation**

* I am working on kubernetes cluster deployed on aws.
 
* I have deployed istio using the manifest given below:

```yaml
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: istio
  namespace: istio-system
spec:
  releaseName: istio
  chart:
    repository: https://raw.githubusercontent.com/IBM/charts/master/repo/stable
    name: ibm-istio
    version: 1.0.5
  values:
    global:
      enableTracing: true
    tracing:
      enabled: true
    jaeger:
      ingress:
        enabled: true
    pilot:
      traceSampling: 100
```

It creates a service of LoadBalancer type it can be seen below:

```bash
details                    ClusterIP      XXX.XX.XXX.XXX   <none>                                                                    9080/TCP                                                                                                                  1h
istio-citadel              ClusterIP      XXX.XX.XX.XXX    <none>                                                                    8060/TCP,9093/TCP                                                                                                         1h
istio-egressgateway        ClusterIP      XXX.XX.X.XX      <none>                                                                    80/TCP,443/TCP                                                                                                            1h
istio-galley               ClusterIP      XXX.XX.XXX.XXX   <none>                                                                    443/TCP,9093/TCP                                                                                                          1h
istio-ingressgateway       LoadBalancer   XXX.XX.XXX.XX    XXXXXe7d1b11e9974802ab685c4f1-XXXXX.XX-west-2.elb.amazonaws.com   80:31380/TCP,443:31390/TCP,31400:31400/TCP,15011:30704/TCP,8060:30755/TCP,853:32658/TCP,15030:31650/TCP,15031:30197/TCP   1h
```

* I have deployed nginx-ingress-controller with these configuration:
```yaml
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: istio-system
spec:
  releaseName: nginx-ingress
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: nginx-ingress
    version: 1.1.5
  values:
    controller:
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "app"
        effect: "NoSchedule"
      publishService:
        enabled: true
        pathOverride: istio-system/nginx-ingress-controller
      ingressClass: test-ingress
      config:
        enable-opentracing: "true"
        jaeger-collector-host: "jaeger-agent.istio-system"
      service:
        labels:
          dns: "route53"
        annotations:
          helm.sh/resource-policy: keep
          external-dns.alpha.kubernetes.io/hostname: testing.com
          domainName: "testing.com"
          service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: XXXXX
      podAnnotations:
        traffic.sidecar.istio.io/includeInboundPorts: ""
        scheduler.alpha.kubernetes.io/critical-pod: "true"
        sidecar.istio.io/inject: "false"
    defaultBackend:
      enabled: false
```
It creates the ingress.

* I have deployed the istio sample application using these [guidelines](https://istio.io/docs/examples/bookinfo/)

* I have created an ingress for one of the services of above application:
```bash
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:    
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: test-ingress
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/upstream-vhost: productpage.istio-system.svc.cluster.local
  name: product-page
spec:
  rules:
  - host: productpage.XXXX.com
    http:
      paths:
      - backend:
          serviceName: productpage
          servicePort: 9080
```

When I try to access the application on this link `productpage.XXXX.com` it is accessible but its `complete` traces are not visible on `jaeger`. I am just getting `nginx-ingress` controller service traces not its subsequent service traces.

When I use istio's LoadBalancer service's `external host`. I get all the traces of all services.

**Expected behaviour**
I should receive all the traces for the services when my request passes through ingress created for the productpage service using the  `nginx-ingress` controller.

Thank you
