### ISSUE TITLE
multiple filter chains with the same matching rules are defined

### ISSUE THREAD

**Issue by stevegszabo** [istio/istio#14334]
(This is used to report product bugs, please visit <https://discuss.istio.io> for questions on using Istio)

**Bug description**

Following this document:

https://preliminary.istio.io/blog/2018/egress-mongo/

We would like to force all egress through the gateway

The istio-egressgateway service has been configured to use tcp/9999:

```
$ kubectl -n istio-system get svc istio-egressgateway
NAME                  TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                             AGE
istio-egressgateway   ClusterIP   xxxxxxxxxxxx   <none>        80/TCP,443/TCP,15443/TCP,9999/TCP   16h
```

When we create the virtual service we get a warning in the istio-proxy pod:

[2019-05-23 13:30:16.428][17][warning][config]
gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected:
Error adding/updating listener(s) 0.0.0.0_8888: error adding listener '0.0.0.0:8888':
multiple filter chains with the same matching rules are defined

**Expected behavior**

**Steps to reproduce the bug**

```
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: infra-sl
  namespace: opsdemo
spec:
  hosts:
  - myhost.tcp.svc
  gateways:
  - mesh
  - istio-egressgateway
  tcp:
  - match:
    - gateways:
      - mesh
      destinationSubnets:
      - 192.168.0.123/24
      port: 8888
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: infra-sl
        port:
          number: 9999
  - match:
    - gateways:
      - istio-egressgateway
      port: 9999
    route:
    - destination:
        host: myhost.tcp.svc
        port:
          number: 8888
      weight: 100
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.5-11-g04850e1"}

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.6+IKS", GitCommit:"ac5f7341d5d0ce8ea8f206ba5b030dc9e9d4cc97", GitTreeState:"clean", BuildDate:"2019-05-09T13:26:51Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

helm

**Environment where bug was observed (cloud vendor, OS, etc)**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
Can you post your all of your Gateways? that is the one likely causing the issue, not the virtual service.

What version of Istio are you running? You said 1.1.6 in the post but that is istioctl, can you get the version for pilot from `kubectl describe deployment istio-pilot -n istio-system` or `istioctl version --remote`?

More context here: https://github.com/istio/istio/issues/13717 was the same bug for https, maybe we missed the tcp case

**Comment by stevegszabo** [comment]
pilot version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.5-11-g04850e1"}

**Comment by stevegszabo** [comment]
```
$ kc get -o json gw infra-sl | jq -r .spec
{
  "selector": {
    "istio": "egressgateway"
  },
  "servers": [
    {
      "hosts": [
        "myhost.tcp.svc"
      ],
      "port": {
        "name": "tcp",
        "number": 9999,
        "protocol": "TCP"
      }
    }
  ]
}

```

**Comment by stevegszabo** [comment]
```
$ kc get -o json gw webapp-ingress | jq -r .spec
{
  "selector": {
    "istio": "ingressgateway"
  },
  "servers": [
    {
      "hosts": [
        "igate.whatever.com"
      ],
      "port": {
        "name": "webapp",
        "number": 443,
        "protocol": "HTTPS"
      },
      "tls": {
        "mode": "SIMPLE",
        "privateKey": "/etc/istio/ingressgateway-certs/tls.key",
        "serverCertificate": "/etc/istio/ingressgateway-certs/tls.crt"
      }
    }
  ]
}

```

**Comment by stevegszabo** [comment]
I have only the above two gateways

**Comment by stevegszabo** [comment]
If I remove the mesh sections I don't get the error:

```
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: infra-sl
  namespace: opsdemo
spec:
  hosts:
  - myhost.tcp.svc
  gateways:
#  - mesh
  - istio-egressgateway
  tcp:
#  - match:
#    - gateways:
#      - mesh
#      destinationSubnets:
#      - 192.168.0.123/24
#      port: 8888
#    route:
#    - destination:
#        host: istio-egressgateway.istio-system.svc.cluster.local
#        subset: infra-sl
#        port:
#          number: 9999
  - match:
    - gateways:
      - istio-egressgateway
      port: 9999
    route:
    - destination:
        host: myhost.tcp.svc
        port:
          number: 8888
      weight: 100

```

**Comment by stevegszabo** [comment]
There seems to be a conflict with the service entry:

```
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: infra-sl
  namespace: opsdemo
spec:
  hosts:
  - myhost.tcp.svc
  addresses:
  - 192.168.0.123/24
  ports:
  - name: tcp
    number: 8888
    protocol: TCP
  location: MESH_EXTERNAL
  resolution: STATIC
  endpoints:
  - address: 192.168.0.123

```

**Comment by howardjohn** [comment]
Thanks for all the extra info. I tried reproducing this and wasn't able too but k think my config isn't identical to yours. If you have time to create a representative yaml that I can just kubectl apply on my cluster that would help, if not I'll keep playing around with it

**Comment by stevegszabo** [comment]
```
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: infra-sl
  namespace: opsdemo
spec:
  hosts:
  - myhost.tcp.svc
  addresses:
  - 192.168.0.123/24
  ports:
  - name: tcp
    number: 8888
    protocol: TCP
  location: MESH_EXTERNAL
  resolution: STATIC
  endpoints:
  - address: 192.168.0.123

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: infra-sl
  namespace: opsdemo
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      name: tcp
      number: 9999
      protocol: TCP
    hosts:
    - myhost.tcp.svc

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: infra-sl-gateway
  namespace: opsdemo
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: infra-sl

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: infra-sl
  namespace: opsdemo
spec:
  host: myhost.tcp.svc

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: infra-sl
  namespace: opsdemo
spec:
  hosts:
  - myhost.tcp.svc
  gateways:
  - mesh
  - istio-egressgateway
  tcp:
  - match:
    - gateways:
      - mesh
      destinationSubnets:
      - 192.168.0.123/24
      port: 8888
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: infra-sl
        port:
          number: 9999
  - match:
    - gateways:
      - istio-egressgateway
      port: 9999
    route:
    - destination:
        host: myhost.tcp.svc
        port:
          number: 8888
      weight: 100

```

**Comment by mbanikazemi** [comment]
yes, this can be reproduced. The error comes from Envoy. I removed the destination rules you have mentioned above as they don't really select a subset or anything. Then, if I remove ``` destinationSubnets:
      - 192.168.0.123/24``` in both places in your yams, things work. I think this should solve your problem. You can rely on port number to identify what you want to route where and have essentially a TCP proxy. This of course means you cannot share these ports. Would that solve your problem? 
I will have to look more to see why specifying destinationSubnets do not work or that is the intended behavior.

**Comment by howardjohn** [comment]
Thank you for providing those configs, saved me a lot of time. Like @mbanikazemi said, this is reproducible. I simplified the config down to 
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: infra-sl
spec:
  hosts:
  - myhost.tcp.svc
  addresses:
  - 192.168.0.123/24
  ports:
  - name: tcp
    number: 8888
    protocol: TCP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: infra-sl
spec:
  hosts:
  - myhost.tcp.svc
  tcp:
  - match:
    - 
      destinationSubnets:
      - 192.168.0.123/24
      port: 8888
    route:
    - destination:
        host: google.com
        port:
          number: 80
```

if it helps anyone reading this.

Basically the problem is at https://github.com/istio/istio/blob/3ef69ae767362993901e7d22c72987706e8366ac/pilot/pkg/networking/core/v1alpha3/listener.go#L1574 we add filter chains for both the VS and for the ServiceEntry. These both have the same matching rules, which makes envoy reject them.

What is the expected behavior here? It is a clear issue from Pilot, as it shouldn't send Envoy invalid config, but I am curious what behavior you wanted here
