### ISSUE TITLE
[Kiali] Setting grafana url takes no effect

### ISSUE THREAD

**Issue by Demonian** [istio/istio#14335]
(This is used to report product bugs, please visit <https://discuss.istio.io> for questions on using Istio)

**Bug description**
There is ability to set Grafana service url for the situations when kiali should be integrated with grafana deployed separately from istio. [Link to chart](https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/kiali/templates/configmap.yaml)
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "kiali.name" . }}
    chart: {{ template "kiali.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  config.yaml: |
    istio_namespace: {{ .Release.Namespace }}
    server:
      port: 20001
    external_services:
      istio:
        url_service_version: http://istio-pilot:8080/version
      jaeger:
        url: {{ .Values.dashboard.jaegerURL }}
      grafana:
        url: {{ .Values.dashboard.grafanaURL }}
```
This url will be used only if `service` and `service_namespace` values are empty, but the problem is that default value for `service` is hardcoded on *Kiali* side. In result this url will not be used by kiali and there will be errors during requests to Grafana api. 

[Link to Kiali sources](https://github.com/kiali/kiali/blob/v0.16.0/config/config.go#L233).
[Grafana settings description from Kiali operator](https://github.com/kiali/kiali/blob/master/operator/deploy/kiali/kiali_cr.yaml#L140-L154). This link is here just for understanding all properties that could be configured.
```
# **Grafana-specific settings:

# service: The Kubernetes service name for Grafana. Kiali uses this to connect within the cluster to Grafana.
#          If "service" and "service_namespace" are empty then "url" is used for communication..
# service_namespace: The Kubernetes namespace that holds the Grafana service (if empty, assumes the same value as deployment.namespace)
# url: The URL that Kiali uses when integrating with Grafana. This URL must be accessible to clients external to
#    grafana:
#      api_key: ""
#      display_link: "true"
#      password: ""
#      service: "grafana"
#      service_dashboard_pattern: "Istio%20Service%20Dashboard"
#      service_namespace: ""
#      url: ""
#      username: ""
#      var_namespace: "var-namespace"
#      var_service: "var-service"
#      var_workload: "var-workload"
#      workload_dashboard_pattern: "Istio%20Workload%20Dashboard"
```
**Expected behavior**
If we give ability to configure url for grafana it should work.
I am ready to crerate PR with fix, but we should agree on the way how we want to fix this (E.g. just add this additional property, allow user to override full configmap (gives ability for user to make all available configurations for kiali))

**Steps to reproduce the bug**
* Use [this instruction](https://istio.io/docs/tasks/telemetry/kiali/) to install istio with Kiali. Additional property should be set " --set "kiali.dashboard.grafanaURL=http://custom-grafana-url.io"`
* Login to Kiali console.
* Error will be there in this format: `Error fetching Grafana Info., Error: [ services "grafana" not found ]`

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio version: 1.1.6
Kubernetes version: v1.11.7

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X ] User Experience

**Comment by jmazzitelli** [comment]
Just to be clear, the links to the kiali code and that kiali_cr.yaml are to master branch - which is NOT the current version in Istio 1.1.6 (which is kiali v0.16). That kiali_cr.yaml is used for the Kiali Operator (not used by Istio helm today) and those settings may not be the same as what they were in Kiali v0.16.

**Comment by Demonian** [comment]
@jmazzitelli Good points. I have changed the link to source code of Kiali for version 0.16. Link to kiali_cr.yaml from `kiali operator` is here just to give visibility of all the properties that can be configured.
BTW Situation was the same at the point (v 0.16).

**Comment by jotak** [comment]
@Demonian , have you tried to set `service` and `service_namespace` for grafana in Kiali config? I don't understand why you say the default is hardcoded... well yes it is, but you're not forced to use the default. 

So if you do so, then Kiali should be able to generate the links to Grafana (note that it is _only_ for links generation).

**Comment by Demonian** [comment]
@jotak You are absolutely right about setting those configs, but the problem here is that istio helm charts do not provide ability to set them, so this is the main point of this issue.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "kiali.name" . }}
    chart: {{ template "kiali.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  config.yaml: |
    istio_namespace: {{ .Release.Namespace }}
    server:
      port: 20001
    external_services:
      istio:
        url_service_version: http://istio-pilot:8080/version
      jaeger:
        url: {{ .Values.dashboard.jaegerURL }}
      grafana:
        url: {{ .Values.dashboard.grafanaURL }}

```
