### ISSUE TITLE
ServiceEntry objects allow `localhost` as a hostname, but shouldn't

### ISSUE THREAD

**Issue by zparnold** [istio/istio#14356]
Using this example manifest:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: datadog-agent
spec:
  hosts:
    - "localhost"
  addresses:
    - "172.20.0.0/16"
  ports:
    - name: tcp
      number: 8126
      protocol: TCP
  location: MESH_EXTERNAL
  resolution: NONE
```

**Bug description**
When a ServiceEntry object (like above) is applied, there are no errors, but pilot begins to choke and is unable to distribute config properly to the sidecars. Here are the logs from the discovery process:
```
istio-pilot-ff9fcff77-xn7w2 istio-pilot-ff9fcff77-4j2vn discovery 2019-05-23T12:53:25.700297Z	info	parseHostname(localhost) => error missing service name and namespace from the service hostname "localhost"
discovery 2019-05-23T12:53:25.700325Z	info	parseHostname(localhost) => error missing service name and namespace from the service hostname "localhost"
istio-pilot-ff9fcff77-xn7w2 discovery istio-pilot-ff9fcff77-4j2vn discovery 2019-05-23T12:53:25.702083Z	info	parseHostname(localhost) => error missing service name and namespace from the service hostname "localhost"
istio-pilot-ff9fcff77-4j2vn discovery 2019-05-23T12:53:25.702105Z	info	parseHostname(localhost) => error missing service name and namespace from the service hostname "localhost"
```

**Expected behavior**
The validating admission controller should prevent this manifest from being applied.

**Steps to reproduce the bug**
Apply the manifest above and then apply literally any other change. Nothing will happen.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio version 1.0.7
Kubernetes version 1.11.13

**How was Istio installed?**
Helm template to Kubernetes manifests

**Environment where bug was observed (cloud vendor, OS, etc)**
EKS/AWS

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
