### ISSUE TITLE
Pods that are not exposed via a Service are not sent some config, including fault injection and locality lb configuration

### ISSUE THREAD

**Issue by nicktrav** [istio/istio#14367]
**Bug description**

When configuring fault injection on a VirtualService with a match on `sourceLabels`, Pods in a Deployment that _do not_ have a Service are not sent the fault injection configuration.

NOTE: I'm scoping this ticket to fault injection configuration. Other configuration may not be sent, but I have not confirmed this.

**Expected behavior**

Using a VirtualService with a `sourceLabels` selector should select pods in a Deployment, even if the pods are not exposed by a K8s Service resource.

In our case, it doesn't make sense to have the Pods exposed by a Service as they are purely load generators (i.e. nothing is sending them traffic).

**Steps to reproduce the bug**

Set up any Deployment that is _not_ exposed by a K8s Service. Include an arbitrary label, e.g.:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
spec:
...
  template:
    metadata:
      labels:
        app: example-app
        foo: bar
```

Set up a VirtualService that matches traffic originating from these Pods.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: example
  namespace: example
spec:
  hosts:
  - some-service.some-namespace
  http:

  # Fault injection route
  - match:
    - sourceLabels:
        foo: bar
    fault:
      abort:
        percentage:
          value: 100.0
        httpStatus: 500
    route:
    - destination:
        host: some-service.some-namespace.svc.cluster.local
```

Dump the Envoy configuration on a `foo` Pod:

```bash
curl http://localhost:15000/config_dump
```

 and observe that there is no `envoy.fault` settings applied for the virtual service for `some-service.some-namespace`.

Creating a "dummy Service" for `foo` fixes the problem. The ports are arbitrary (the `foo` Deployment doesn't expose any ports, but a Service needs them):

```yaml
apiVersion: v1
kind: Service
metadata:
  name: foo
spec:
  ports:
    - name: dummy-port
      port: 1234
      targetPort: 1234
      protocol: TCP
  selector:
    app: example-app
```

Create this Service and dump out the envoy config again, and observe the presence of the `envoy.fault` now:

```json
"envoy.fault": {
  "abort": {
    "percentage": {
      "denominator": "MILLION",
      "numerator": 1000000
    },
    "http_status": 500
  }
}
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```
$ istioctl version --remote
client version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.1"}
citadel version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.1"}
galley version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.1"}
pilot version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.1"}
policy version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.1"}
sidecar-injector version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.1"}
telemetry version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.1"}
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:04:52Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-gke.11", GitCommit:"035e49d66342c7c6ac569c68721f0a821d2df6f5", GitTreeState:"clean", BuildDate:"2019-04-03T01:27:32Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

Helm charts from `install/kubernetes/helm/`.

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
