### ISSUE TITLE
export overload manager options at envoy

### ISSUE THREAD

**Issue by lambdai** [istio/istio#14366]
Among the overload actions this particular `envoy.overload_actions.shrink_heap` is helping proxy to reclaim the heap memory. It's extremely helpful when there is burst of config changes.

Ref:
https://www.envoyproxy.io/docs/envoy/latest/configuration/overload_manager/overload_manager#overload-actions

**Comment by howardjohn** [comment]
Nice, should be a pretty simple change to the bootstrap. Ill try it out

**Comment by ckcd** [comment]
@howardjohn 
Is this issue still valid ?  Can I take it ?

**Comment by howardjohn** [comment]
Sure, that would be great!

**Comment by lambdai** [comment]
Thank you for taking it @ckcd

**Comment by howardjohn** [comment]
If you want to apply this today:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-custom-bootstrap-config
data:
  custom_bootstrap.json: |
    {
      "stats_config": {
        "stats_matcher": {
          "inclusion_list": {
            "patterns": [
              {
              "prefix": "overload"
              },
            ]
          }
        }
      },
      "overload_manager": {
        "refresh_interval": {
          "seconds": 1,
        },
        "actions": [
          {
            "name": "envoy.overload_actions.shrink_heap",
            "triggers": [
            {
              "threshold": {
                "value": 0.90
              },
              "name": "envoy.resource_monitors.fixed_heap"
            }
            ]
          },
          {
            "name": "envoy.overload_actions.stop_accepting_requests",
            "triggers": [
            {
              "threshold": {
                "value": 0.99
              },
              "name": "envoy.resource_monitors.fixed_heap"
            }
            ]
          }
        ],
        "resource_monitors": [
          {
            "config": {
              "max_heap_size_bytes": 2147483648
            },
            "name": "envoy.resource_monitors.fixed_heap"
          }
        ]
      }
    }

```

Then follow other directions in `samples/custom-bootstrap/`

**Comment by zirain** [comment]
resource_monitors[0]) config: Cannot find field.) has unknown fields

please check you istio version and verify the configuration.

**Comment by style95** [comment]
I could apply the configuration with the following configs.

```yaml
$ cat custom-bootstrap-runtime.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-custom-bootstrap-config
data:
  custom_bootstrap.json: |
    {
      "stats_config": {
        "stats_matcher": {
          "inclusion_list": {
            "patterns": [
              {
              "prefix": "overload"
              },
            ]
          }
        }
      },
      "overload_manager": {
        "refresh_interval": {
          "seconds": 1,
        },
        "actions": [
          {
            "name": "envoy.overload_actions.shrink_heap",
            "triggers": [
            {
              "threshold": {
                "value": 0.10
              },
              "name": "envoy.resource_monitors.fixed_heap"
            }
            ]
          },
          {
            "name": "envoy.overload_actions.stop_accepting_requests",
            "triggers": [
            {
              "threshold": {
                "value": 0.99
              },
              "name": "envoy.resource_monitors.fixed_heap"
            }
            ]
          }
        ],
        "resource_monitors": [
          {
            "typed_config": {
              "@type": "type.googleapis.com/envoy.extensions.resource_monitors.fixed_heap.v3.FixedHeapConfig",
              "max_heap_size_bytes": 2147483648
            },
            "name": "envoy.resource_monitors.fixed_heap"
          }
        ]
      }
    }
```

This part is updated.

```
"resource_monitors": [
          {
            "typed_config": {
              "@type": "type.googleapis.com/envoy.extensions.resource_monitors.fixed_heap.v3.FixedHeapConfig",
              "max_heap_size_bytes": 2147483648
            },
            "name": "envoy.resource_monitors.fixed_heap"
          }
```
