### ISSUE TITLE
LDS ACK ERROR: sent weighted cluster with empty list 

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#14414]
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: infra-sl
  namespace: opsdemo
spec:
  hosts:
  - myhost.tcp.svc
  addresses:
  - 192.168.0.123/24
  ports:
  - name: tcp
    number: 8888
    protocol: TCP
  location: MESH_EXTERNAL
  resolution: STATIC
  endpoints:
  - address: 192.168.0.123
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: infra-sl
  namespace: opsdemo
spec:
  hosts:
  - myhost.tcp.svc
  gateways:
  - mesh
  - istio-egressgateway
  tcp:
  - match:
    - gateways:
      - mesh
      destinationSubnets:
      - 192.168.0.123/24
      port: 8888
    # route:
    # - destination:
    #     host: istio-egressgateway.istio-system.svc.cluster.local
    #     subset: infra-sl
    #     port:
    #       number: 9999
  - match:
    - gateways:
      - istio-egressgateway
      port: 9999
    route:
    - destination:
        host: myhost.tcp.svc
        port:
          number: 8888
      weight: 100
```

Gives

```
ADS:LDS: ACK ERROR 10.60.4.30:59316 sidecar~10.60.4.30~shell-6f85b78468-gjxfz.opsdemo~opsdemo.svc.cluster.local-22 (shell-6f85b78468-gjxfz.opsdemo) version_info:"2019-05-29T01:10:27Z/11" node:<id:"sidecar~10.60.4.30~shell-6f85b78468-gjxfz.opsdemo~opsdemo.svc.cluster.local" cluster:"shell.opsdemo" metadata:<fields:<key:"CONFIG_NAMESPACE" value:<string_value:"opsdemo" > > fields:<key:"INCLUDE_INBOUND_PORTS" value:<string_value:"" > > fields:<key:"INTERCEPTION_MODE" value:<string_value:"REDIRECT" > > fields:<key:"ISTIO_META_INSTANCE_IPS" value:<string_value:"10.60.4.30,10.60.4.30,fe80::50d3:32ff:fe9d:3783" > > fields:<key:"ISTIO_PROXY_SHA" value:<string_value:"istio-proxy:542b4fda35046fc9dad5014dbe81f3d5969e63f7" > > fields:<key:"ISTIO_PROXY_VERSION" value:<string_value:"1.1.3" > > fields:<key:"ISTIO_VERSION" value:<string_value:"master-20190522-09-15" > > fields:<key:"POD_NAME" value:<string_value:"shell-6f85b78468-gjxfz" > > fields:<key:"app" value:<string_value:"shell" > > fields:<key:"istio" value:<string_value:"sidecar" > > fields:<key:"pod-template-hash" value:<string_value:"6f85b78468" > > > locality:<region:"us-central1" zone:"us-central1-a" > build_version:"542b4fda35046fc9dad5014dbe81f3d5969e63f7/1.11.0-dev/Clean/RELEASE/BoringSSL" > type_url:"type.googleapis.com/envoy.api.v2.Listener" response_nonce:"5b9bd6f9-e0da-41f4-9093-660e540beccf" error_detail:<code:13 message:"Error adding/updating listener(s) 0.0.0.0_8888: Proto constraint validation failed (TcpProxyValidationError.WeightedClusters: [\"embedded message failed validation\"] | caused by WeightedClusterValidationError.Clusters: [\"value must contain at least \" '\\x01' \" item(s)\"]): stat_prefix: \"infra-sl.opsdemo\"\nweighted_clusters {\n}\n" >
```

One thing to note is this is failing the proto constraint. Maybe we can check the constraints pilot side.

Got this error from some modifications to https://github.com/istio/istio/issues/14334, so likely related
