### ISSUE TITLE
STATIC ServiceEntry do not take endpoint weight into account

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#14466]
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin
spec:
  hosts:
  - httpbin.locality.svc.cluster.local
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: STATIC
  endpoints:
  - address: 172.217.0.46
    locality: external
    weight: 5
  - address: 1.1.1.1
    locality: external
    weight: 1
```

Current output of /clusters:
```
outbound|80||httpbin.locality.svc.cluster.local::172.217.0.46:80::weight::1
outbound|80||httpbin.locality.svc.cluster.local::1.1.1.1:80::weight::1
```

Expected:
```
outbound|80||httpbin.locality.svc.cluster.local::172.217.0.46:80::weight::5
outbound|80||httpbin.locality.svc.cluster.local::1.1.1.1:80::weight::1
```

Probably we need to update https://github.com/istio/istio/blob/master/pilot/pkg/proxy/envoy/v2/eds.go#L116-L122
