### ISSUE TITLE
Istio proxy sidecar need to skip mTLS when routing request an external endpoint based on ServiceEntry locality

### ISSUE THREAD

**Issue by uk000** [istio/istio#14495]
**Bug description**
As of Istio 1.1.7, given the following scenario:
- there is a cluster service configured to use mTLS and is consumed by in-cluster clients over mTLS
- the service is also deployed outside of kubernetes cluster (on cloud VMs), and the service wants to provide a "fallback/failover" feature to its in-cluster clients such that when there are no healthy pods available for the service in the cluster, the client requests should be routed to the external VM instances of the service
- to achieve the fallback routing, the service uses the ServiceEntry's locality feature to configure additional external endpoints, and setup outlier detection via a DestinationRule, so that calls can be sent to the external endpoints after certain # of consecutive errors detected by envoy.

Given the above setup, when the outlier detection is triggered and the client's sidecar sends the request to the external endpoint, the sidecar still applies the mTLS setting as configured in the DestinationRule even though the call is going to an external endpoint outside the cluster.

The root of the issue is that currently there's no way for a service to configure mTLS selectively only for its in-cluster endpoints, but skip mTLS for the external endpoints.

**Expected behavior**
- Either sidecar needs to have the smarts to automatically detect that a request is headed to an external endpoint and hence mTLS should not be applied,
- Or, there needs to be an explicit configuration exposed somewhere (say on ServiceEntry) so that the service owner can mark its external endpoints explicitly as "non-mTLS".

**Steps to reproduce the bug**
1. Deploy a cluster service and backing deployment (with sidecar injected)

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: outlier
spec:
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - name: httpbin
        image: docker.io/kennethreitz/httpbin
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: outlier
spec:
  selector:
    app: httpbin
  ports:
  - name: http
    port: 80
    targetPort: 80
```

2. Configure the service to use mTLS

```
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: default
  namespace: outlier
spec:
  peers:
  - mtls:
      mode: STRICT
```

3. Configure the client mTLS requirement and outlier detection via a DestinationRule 

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: outlier
  namespace: outlier
spec:
  host: "httpbin.outlier.svc.cluster.local"
  trafficPolicy:
    outlierDetection:
      consecutiveErrors: 1
    tls:
      mode: "ISTIO_MUTUAL"
```

4. Add an external endpoint via a ServiceEntry (change 1.2.3.4 in the sample below to a valid IP address) 

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin-external
  namespace: outlier
spec:
  hosts:
  - httpbin.outlier.svc.cluster.local
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: STATIC
  endpoints:
  - address: 1.2.3.4
    locality: external
```
5. Deploy a client pod with sidecar injected (use any of the sample client pod images)

6. Make curl calls to httpbin service and request status 503 to trigger outlier detection.
curl httpbin.outlier/status/503
Given the DestinationRule is configured to trigger circuit breaker upon a single failure, the sidecar will attempt to route the call to external endpoint. However, since mTLS is enabled for the service, the call will fail.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.6-6-geec7a74"}
```
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Helm template

**Environment where bug was observed (cloud vendor, OS, etc)**
Docker for mac

**Affected product area (please put an X in all that apply)**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
