### ISSUE TITLE
Cannot see any error logs in pilot but getting errors in prometheus metrics

### ISSUE THREAD

**Issue by rajusharma** [istio/istio#14522]
(This is used to report product bugs, please visit <https://discuss.istio.io> for questions on using Istio)

**Bug description**
Getting `pilot_total_xds_internal_errors` & `pilot_rds_expired_nonce` metric errors in prometheus but cannot find any error logs in pilot pods. So not sure how to resolve this error and avoid `pilot_total_xds_internal_errors` & `pilot_rds_expired_nonce` 
 

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[x] Test and Release
[x] User Experience

**Expected behavior**
If there are `pilot_total_xds_internal_errors` & `pilot_rds_expired_nonce` then we should see some error or warning logs in pilot pods

**Steps to reproduce the bug**
Installed Istio with following values.yaml
```
global:
  tag: 1.1.4
  logging:
    level: "default:warn"

  proxy:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

    accessLogFile: ""
    accessLogEncoding: JSON
    enableTracing: false

    # this means that auto-injection will be opt-in.
    # For autoinjection both namespace label & pod annotation will be required
    # https://istio.io/help/ops/setup/injection/
    autoInject: disabled

  # TODO: Change this to true when start supporting Istio CRDs
  useMCP: false

pilot:
  enabled: true
  autoscaleMin: 3
  env:
    GODEBUG: gctrace=0
    PILOT_ENABLE_FALLTHROUGH_ROUTE: 1

mixer:
  enabled: false
  env:
    GODEBUG: gctrace=0
  policy:
    enabled: false
  telemetry:
    enabled: false
    loadshedding:
      mode: logonly
      latencyThreshold: 200ms

sidecarInjectorWebhook:
  enabled: true
  replicaCount: 3

galley:
  enabled: false

# Used as secondary monitoring tool for istio components
prometheus:
  enabled: false

# Used as secondary monitoring tool for istio components
grafana:
  enabled: false

gateways:
  enabled: false

security:
  enabled: true

nodeagent:
  enabled: false

servicegraph:
  enabled: false

tracing:
  enabled: false

kiali:
  enabled: false

istio_cni:
  enabled: false

istiocoredns:
  enabled: false

```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
client version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2-dirty", User:"brew", Host:"Mojave.local", GolangVersion:"go1.12.5", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.7"}
citadel version: version.BuildInfo{Version:"1.1.4", GitRevision:"bc7465793cbff4c4189639b3f404e21c517cbdc6-dirty", User:"root", Host:"471e568b-66d7-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.3-20-gbc74657"}
pilot version: version.BuildInfo{Version:"1.1.4", GitRevision:"bc7465793cbff4c4189639b3f404e21c517cbdc6-dirty", User:"root", Host:"471e568b-66d7-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.3-20-gbc74657"}
pilot version: version.BuildInfo{Version:"1.1.4", GitRevision:"bc7465793cbff4c4189639b3f404e21c517cbdc6-dirty", User:"root", Host:"471e568b-66d7-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.3-20-gbc74657"}
pilot version: version.BuildInfo{Version:"1.1.4", GitRevision:"bc7465793cbff4c4189639b3f404e21c517cbdc6-dirty", User:"root", Host:"471e568b-66d7-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.3-20-gbc74657"}
sidecar-injector version: version.BuildInfo{Version:"1.1.4", GitRevision:"bc7465793cbff4c4189639b3f404e21c517cbdc6-dirty", User:"root", Host:"471e568b-66d7-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.3-20-gbc74657"}
sidecar-injector version: version.BuildInfo{Version:"1.1.4", GitRevision:"bc7465793cbff4c4189639b3f404e21c517cbdc6-dirty", User:"root", Host:"471e568b-66d7-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.3-20-gbc74657"}
sidecar-injector version: version.BuildInfo{Version:"1.1.4", GitRevision:"bc7465793cbff4c4189639b3f404e21c517cbdc6-dirty", User:"root", Host:"471e568b-66d7-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.3-20-gbc74657"}
```
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T18:55:03Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.7-gke.17", GitCommit:"b1adfec15b29a53b3dcf4af600952861b5819ede", GitTreeState:"clean", BuildDate:"2019-05-01T18:59:13Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Using helm template

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
