### ISSUE TITLE
VirtualService HTTPRoute match header scheme not working

### ISSUE THREAD

**Issue by dzdx** [istio/istio#14554]
(This is used to report product bugs, please visit <https://discuss.istio.io> for questions on using Istio)

**Bug description**

I defined a virtualservice 
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: asm-test-http
spec:
  hosts:
  - asm-test-http
  http:
  - match:
    - scheme:
        prefix: http
    route:
    - destination:
        host: asm-test-http
```
which match http scheme request to route to the host asm-test-http， but the response status code is 404 not Found

asm-test-http virtualhost route config is
```
 "routes": [
                    {
                        "match": {
                            "prefix": "/",
                            "headers": [
                                {
                                    "name": ":scheme",
                                    "prefixMatch": "http"
                                }
                            ]
                        },

```

then I turn on Envoy's debug log
```
[2019-06-04 17:55:16.987][15333][debug][http] [source/common/http/conn_manager_impl.cc:580] [C4][S15658494270569588834] request headers complete (end_stream=true):
':authority', 'asm-test-http.default'
':path', '/'
':method', 'GET'
'user-agent', 'curl/7.61.0'
'accept', '*/*'
```
there is not header key named ":scheme" , so the request header cannot match config header

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

istio1.1
kubernetes1.14

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
