### ISSUE TITLE
Istio URI routing is not working with tls

### ISSUE THREAD

**Issue by ronakpandya7** [istio/istio#14586]
**Bug description**

Hello,

We are using istio 1.1.7 and kubernetes 1.14.2 and we deploy one application with HTTPs enable and certificates are inside the pods itself and it is working fine, we are using tls "PASSTHROUGH" concept to process our https requests.

But issues come when we are applying "uri" based routing on tls in virtualservice.

Below are the things that we want our application will do:
```
test.example.com/check1 -> call svc-infra-nodehealthcheck-1 service
test.example.com/check2 -> call svc-infra-nodehealthcheck-2 service
```

Ingress Gateway:

```
kubectl create -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: dynamic-gateway-1
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:  
  - hosts:
    - test.example.com
    port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
EOF
```
Virtual Service:

```
kubectl create -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-test-web
  namespace: istio-system
spec:
  hosts:
  - test.example.com
  gateways:
  - dynamic-gateway-1
  tls:
  - match:
    - uri:
        prefix: /check1
    - port: 443
      sni_hosts:
      - test.example.com
    route:
    - destination:
        host: svc-infra-nodehealthcheck-1-http.ns-beta.svc.cluster.local
        port:
          number: 9101
  - match:
    - uri:
        prefix: /check2
    - port: 443
      sni_hosts:
      - test.example.com
    route:
    - destination:
        host: svc-infra-nodehealthcheck-2-http.ns-beta.svc.cluster.local
        port:
          number: 9101
EOF
```
So uri section is not working in the virtual service.
but when we try `http` instead of `tls` with normal http request these uri matches works.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
istio version 1.1.7

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
`Istio  is installed with mtls disabled, we manually enabled mtls.`

**Environment where bug was observed (cloud vendor, OS, etc)**
```
ID=coreos
VERSION=2079.4.0
VERSION_ID=2079.4.0
BUILD_ID=2019-05-15-0808
PRETTY_NAME="Container Linux by CoreOS 2079.4.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

So what we are missing here?
Is URI based routing won't work in TLS ?

Thanks in advance,
Ronak Pandya
