### ISSUE TITLE
Add Grafana Loki as a telemetry provider

### ISSUE THREAD

**Issue by Lysholm** [istio/istio#14580]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Installers and necessary config for grafana loki as a telemetry provider, in the same vein as is currently done for prometheus. Loki on github: https://github.com/grafana/loki

**Describe alternatives you've considered**
Ideally i'd like to see an ecosystem where it was simple to install istio standalone and add prometheus, and other similar third parties, on top. Given the amount of istio specific configuration required for telemetry applications and the current state of installers in the k8s ecosystem i can't come up with a feasible alternative that achieves that.

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience

**Additional context**
In today's istio installs you can get 2 out of 3 telemetry "pillars", metrics and traces, out of the box for your mesh. If you want log collection you have to add that on your own, and there's good documentation provided for how to get started with fluentd, elasticsearch and kibana. This works but is still tedious to set up and is not easy to use together with metrics collected in grafana.

Grafana loki wants to be "Prometheus for logs" and provide logs easily accessible in your grafana dashboards. Given that the other components in this stack is already present in the istio charts / installer i think it makes sense to look at it as a candidate for mesh log collection.

There are some challenges here and i haven't taken that hard a look at it. For starters promtail (the agent used to scrape / tail logs) is probably going to need the same kind of setup as is done for Prometheus with regards to mTLS. Also loki is still young, the first beta was released only two days ago, so this might be a bit premature.

Even so there already seem to be interest from the community:
  - https://discuss.istio.io/t/loki-and-istio-anyone/2121
  - https://github.com/grafana/loki/issues/475

**Comment by douglas-reid** [comment]
Thanks for sending this FR!  I was not aware of the loki effort.

The idea behind the new installer is that it should be simple to install standalone components. That's part of the reason behind the transition to the support for the prom operator, etc. If loki has similar support, I don't see why it can't be supported in a similar fashion.

Let's talk about this in a future P&T WG meeting.  I'll try to get smarter about Loki in the meantime.

**Comment by sdake** [comment]
@douglas-reid hi I set the priority to 2 such that this issue wouldn't show up in the new issues column of zenhub.  If you disagree with the prioritization please feel free to change it.

Cheers
-steve

**Comment by aemaem** [comment]
As it is possible to gather logs with Fluentd and storing them in Elasticsearch, one should be able to change ES with Loki. Guess the Fluentd Loki Plugin (https://github.com/grafana/loki/blob/master/fluentd/fluent-plugin-grafana-loki) will be exactly what we need to send logs to Loki. Promtail won't be needed in that case.

**Comment by aemaem** [comment]
Did you set it up with fluentd? How do you know the logs are not coming from promtail because the Loki-stack is used where promtail is installed as well?

**Comment by aemaem** [comment]
Ah OK, thought Mixer needs to send the logs in order to enhance them with additional meta data. But as you get the logs from sidecars as well this is probably not needed. Thanks for clearing things up!

**Comment by r3kzi** [comment]
@howardjohn have you installed Loki in a istio-labeled namespace? It doesn't work for me when Promtail and Loki have envoy sidecards....

**Comment by howardjohn** [comment]
That I didn't try... but I am not sure why you would want promtail to have a sidecar? I think general prometheus is installed without a sidecar so I would expect promtail to be the same?

**Comment by r3kzi** [comment]
My cluster have to meet very high demands regarding data protection (GDPR). So i have to encrypt all network traffic. Especially log file entries.

**Comment by howardjohn** [comment]
I see, thanks for the info. Just wondering, do you have prometheus with sidecar as well?

Seems like we should be able to get it to work, I didn't try though so I am not sure where/why it breaks

**Comment by r3kzi** [comment]
I run Prometheus without a sidecar but with mounted istio secrets and additional scrape config to be able to scrape all other pods that have sidecars.

```
additionalScrapeConfigs:
      # scrape config for Istio secured Pods
      - job_name: 'kubernetes-pods-istio-secure'
        scheme: https
        tls_config:
          ca_file: /etc/prometheus/secrets/istio.default/root-cert.pem
          cert_file: /etc/prometheus/secrets/istio.default/cert-chain.pem
          key_file: /etc/prometheus/secrets/istio.default/key.pem
          insecure_skip_verify: true  # prometheus does not support secure naming.
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_prometheus_io_scrape]
            action: keep
            regex: true
...
```
