### ISSUE TITLE
Adding multiple gateways on istio ingressgateway

### ISSUE THREAD

**Issue by Sanjanare** [istio/istio#14625]
I am trying to add multiple gateways on istio-ingressgateway with a type : LoadBalancer.
One Load balancer works fine but the second one goes to pending state. I am using helm charts

```
istio:
  gateways:
    istio-ingressgateway:
      enabled: true
      serviceAnnotations: 
        dns.alpha.kubernetes.io/internal: '*.dev.k8s.*******'
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "********"
        service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "******"
        service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-prefix: "*******"
      labels:
        app: istio-ingressgateway
        istio: ingressgateway
      ports:
      - port: 15020
        name: status-port
      - port: 80
        name: http
      - port: 443
        name: https
    istio-ingressgateway-external:
      enabled: true
      serviceAnnotations: 
        dns.alpha.kubernetes.io/internal: '*.internal.dev.********'
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "****************"
        service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "******"
        service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-prefix: "********"
      labels:
        app: istio-ingressgateway-external
        istio: ingressgateway
      type: LoadBalancer
      ports:
      - port: 15020
        name: status-port
      - port: 80
        name: http
      - port: 443
        name: https
   ```
Can some one please help me ! thanks

**Comment by howardjohn** [comment]
Why is it pending? You can see by `kubectl describe`ing the pod.

**Comment by Sanjanare** [comment]
@howardjohn if i describe the gateway it shows Running 

```
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
```
it builds Load balancer in AWS as well , but the load balancer is not connected to instances, i checked the certs they are okay.

**Comment by howardjohn** [comment]
It doesn't seem like an istio issue to me. Can you create other Services of type LoadBalancer? if not then its an issue with your Kubernetes.

Sorry I mispoke, you should look at the status on the service not the pod. Mine shows
```
  Type    Reason                Age   From                Message
  ----    ------                ----  ----                -------
  Normal  EnsuringLoadBalancer  3m5s  service-controller  Ensuring load balancer
  Normal  EnsuredLoadBalancer   48s   service-controller  Ensured load balancer

```

**Comment by Sanjanare** [comment]
@howardjohn yes i did check on service only it didnot create any events.
```
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  istio-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio.istio-ingressgateway-external-service-account
    Optional:    true
  istio-ingressgateway-external-service-account-token-s7r7q:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio-ingressgateway-external-service-account-token-s7r7q
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          

```

**Comment by howardjohn** [comment]
Weird there are no events? Can you try creating another Service of type LoadBalancer? Just simple like

```
apiVersion: v1
kind: Service
metadata:
  name: httpbin
spec:
  type: LoadBalancer
  selector:
    app: httpbin
  ports:
  - name: http
    port: 80
    targetPort: 80
```

If that one is stuck pending, then it may be an issue with your K8S setup. Are you using EKS?
