### ISSUE TITLE
rate limit requested quota is not configured

### ISSUE THREAD

**Issue by rookiefiend** [istio/istio#14658]
**Bug description**
  when I perform [enabling rate limits  task](https://istio.io/docs/tasks/policy-enforcement/rate-limiting/#conditional-rate-limits). Wether I use memory quota or redis quota, the rate limits is not work, and I can find warn in mixer --- `warn	Requested quota 'requestcountquota' is not configured`
**Affected product area (please put an X in all that apply)**
  istio 1.1.6
[ ] Configuration Infrastructure
  I use istio in kubernetes.
[ ] Docs
  
[ ] Installation
  I install istio by helm, use configuation that disable prometheus base on default configuration.
[ ] Networking
  calico
[ ] Performance and Scalability
  request: cpu: 500m, memory: 500M
[ ] Policies and Telemetry
[ ] Security
   not use
[ ] Test and Release
   release istio 1.1.6
[ ] User Experience
  
**Expected behavior**
  I want the rate limit can work.
**Steps to reproduce the bug**
  I don't sure other will meet this problem, I Install istio 1.1.6 with helm that default configuartion, note I disabel the prometheus. then  follow [enabling rate limits task](https://istio.io/docs/tasks/policy-enforcement/rate-limiting/#conditional-rate-limits) step by step.
**Version (include the output of `istioctl version --remote` and `kubectl version`)**
  - istioctl version --remote
 ```
client version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.5-11-g04850e1"}
citadel version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.5-11-g04850e1"}
galley version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.5-11-g04850e1"}
ingressgateway version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.5-11-g04850e1"}
pilot version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.5-11-g04850e1"}
policy version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.5-11-g04850e1"}
sidecar-injector version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.5-11-g04850e1"}
telemetry version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.5-11-g04850e1"}
 ```
- kubectl version
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"archive", BuildDate:"2019-01-25T08:57:03Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"archive", BuildDate:"2019-01-25T08:57:03Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**
  use helm that disable prometheus base on default configuration.
**Environment where bug was observed (cloud vendor, OS, etc)**
   private cloud
Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by gargnupur** [comment]
Can you share your mixer logs along with the config you are using?

**Comment by rookiefiend** [comment]
- policy mixer log
```
[root@master1 ~]# kubectl -n istio-system logs -f istio-policy-5bcf878994-k5grw -c mixer --tail=0
scvg461: 0 MB released
scvg461: inuse: 32, idle: 10, sys: 43, released: 8, consumed: 35 (MB)
2019-06-11T01:22:11.055667Z	warn	Requested quota 'requestcountquota' is not configured
2019-06-11T01:22:11.831993Z	warn	Requested quota 'requestcountquota' is not configured
2019-06-11T01:22:12.400319Z	warn	Requested quota 'requestcountquota' is not configured
```
the log print when I access the productpage service
- redis quota configuration
```
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: redishandler
  namespace: istio-system
spec:
  compiledAdapter: redisquota
  params:
    redisServerUrl: shen-space-redis-master.shen-space:6379
    connectionPoolSize: 10
    quotas:
    - name: requestcountquota.instance.istio-system
      maxAmount: 500
      validDuration: 1s
      bucketDuration: 500ms
      rateLimitAlgorithm: ROLLING_WINDOW
      # The first matching override is applied.
      # A requestcount instance is checked against override dimensions.
      overrides:
      # The following override applies to 'reviews' regardless
      # of the source.
      - dimensions:
          destination: reviews
        maxAmount: 1
      # The following override applies to 'productpage' when
      # the source is a specific ip address.
      - dimensions:
          destination: productpage
          source: "10.28.11.20"
        maxAmount: 500
      # The following override applies to 'productpage' regardless
      # of the source.
      - dimensions:
          destination: productpage
        maxAmount: 2
---
apiVersion: config.istio.io/v1alpha2
kind: instance
metadata:
  name: requestcountquota
  namespace: istio-system
spec:
  compiledTemplate: quota
  params:
    dimensions:
      source: request.headers["x-forwarded-for"] | "unknown"
      destination: destination.labels["app"] | destination.workload.name | "unknown"
      destinationVersion: destination.labels["version"] | "unknown"
---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpec
metadata:
  name: request-count
  namespace: istio-system
spec:
  rules:
  - quotas:
    - charge: 1
      quota: requestcountquota
---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpecBinding
metadata:
  name: request-count
  namespace: istio-system
spec:
  quotaSpecs:
  - name: request-count
    namespace: istio-system
  services:
  - name: productpage
    namespace: default
    #  - service: '*'  # Uncomment this to bind *all* services to request-count
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: quota
  namespace: istio-system
spec:
  # quota only applies if you are not logged in.
  # match: match(request.headers["cookie"], "session=*") == false
  actions:
  - handler: redishandler
    instances:
    - requestcountquota
---
```
