### ISSUE TITLE
After applying a policy, Galley crashes

### ISSUE THREAD

**Issue by daleangus** [istio/istio#14788]
Working with Istio 1.1.7

Studying how to use JWTs, I applied the following YAML file
```
apiVersion: "authentication.istio.io/v1alpha1"
kind: Policy
metadata:
  name: front-end-policy
spec:
  targets:
  - name: front-end
  origins:
  - jwt:
    issuer: "testing@secure.istio.io"
    jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.1/security/tools/jwt/samples/jwks.json"
  principalBinding: USE_ORIGIN
```
I get this erro
Error from server (InternalError): error when creating "policy.yaml": Internal error occurred: failed calling admission webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:7443/admitpilot?timeout=30s: stream error: stream ID 1; INTERNAL_ERROR

The Galley logs show

2019-06-13T11:22:49.757037Z     info    http2: panic serving 172.16.0.49:35736: runtime error: invalid memory address or nil pointer dereference
goroutine 1442 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc4203daae0, 0xc420be9faf, 0xc42050c1c0)
        /usr/local/go/src/net/http/h2_bundle.go:5753 +0x190
panic(0x1ca6dc0, 0x2fd1910)
        /usr/local/go/src/runtime/panic.go:502 +0x229
istio.io/istio/pilot/pkg/model.ValidateAuthenticationPolicy(0xc420c818b0, 0x10, 0xc420c818a7, 0x7, 0x21be3c0, 0xc420474100, 0xe, 0x1fab594)
        /workspace/go/src/istio.io/istio/pilot/pkg/model/validation.go:1457 +0x58d
istio.io/istio/galley/pkg/crd/validation.(*Webhook).admitPilot(0xc420692b40, 0xc420e96000, 0xc4201bef00)
        /workspace/go/src/istio.io/istio/galley/pkg/crd/validation/webhook.go:472 +0x509
istio.io/istio/galley/pkg/crd/validation.(*Webhook).(istio.io/istio/galley/pkg/crd/validation.admitPilot)-fm(0xc420e96000, 0xc420d9b000)
        /workspace/go/src/istio.io/istio/galley/pkg/crd/validation/webhook.go:435 +0x34
istio.io/istio/galley/pkg/crd/validation.serve(0x21cb6c0, 0xc4203daae0, 0xc420d4a200, 0xc420be9cc0)
        /workspace/go/src/istio.io/istio/galley/pkg/crd/validation/webhook.go:407 +0x4ee
istio.io/istio/galley/pkg/crd/validation.(*Webhook).serveAdmitPilot(0xc420692b40, 0x21cb6c0, 0xc4203daae0, 0xc420d4a200)
        /workspace/go/src/istio.io/istio/galley/pkg/crd/validation/webhook.go:435 +0x5f
istio.io/istio/galley/pkg/crd/validation.(*Webhook).(istio.io/istio/galley/pkg/crd/validation.serveAdmitPilot)-fm(0x21cb6c0, 0xc4203daae0, 0xc420d4a200)
        /workspace/go/src/istio.io/istio/galley/pkg/crd/validation/webhook.go:287 +0x48
net/http.HandlerFunc.ServeHTTP(0xc4200b7c10, 0x21cb6c0, 0xc4203daae0, 0xc420d4a200)
        /usr/local/go/src/net/http/server.go:1947 +0x44
net/http.(*ServeMux).ServeHTTP(0xc4206919b0, 0x21cb6c0, 0xc4203daae0, 0xc420d4a200)
        /usr/local/go/src/net/http/server.go:2340 +0x130
net/http.serverHandler.ServeHTTP(0xc42061fe10, 0x21cb6c0, 0xc4203daae0, 0xc420d4a200)
        /usr/local/go/src/net/http/server.go:2697 +0xbc
net/http.initNPNRequest.ServeHTTP(0xc4204bf500, 0xc42061fe10, 0x21cb6c0, 0xc4203daae0, 0xc420d4a200)
        /usr/local/go/src/net/http/server.go:3263 +0x9a
net/http.(Handler).ServeHTTP-fm(0x21cb6c0, 0xc4203daae0, 0xc420d4a200)
        /usr/local/go/src/net/http/h2_bundle.go:5475 +0x4d
net/http.(*http2serverConn).runHandler(0xc42050c1c0, 0xc4203daae0, 0xc420d4a200, 0xc420c4d600)
        /usr/local/go/src/net/http/h2_bundle.go:5760 +0x89
created by net/http.(*http2serverConn).processHeaders
        /usr/local/go/src/net/http/h2_bundle.go:5494 +0x46b

Any ideas, please?

**Comment by daleangus** [comment]
If I remove all the lines about Jwt, there is no error (but meaningless in my case)

**Comment by irisdingbj** [comment]
```apiVersion: "authentication.istio.io/v1alpha1"
kind: Policy
metadata:
  name: front-end-policy
spec:
  targets:
  - name: front-end
  origins:
  - jwt:
      issuer: "testing@secure.istio.io"
      jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.1/security/tools/jwt/samples/jwks.json"
  principalBinding: USE_ORIGIN``` this config works.

**Comment by ozevren** [comment]
@wattli Is this something that you can take a look? The crash is coming from the validation code within Pilot.

```

istio.io/istio/pilot/pkg/model.ValidateAuthenticationPolicy(0xc420c818b0, 0x10, 0xc420c818a7, 0x7, 0x21be3c0, 0xc420474100, 0xe, 0x1fab594)```

**Comment by pitlv2109** [comment]
@daleangus Could you share the steps to reproduce this error? How did you install Istio?, etc.

**Comment by daleangus** [comment]
I installed Istio 1.1.8 with mTLS enabled. I have grafana and kiali enabled. I installed my application. Everything is working until I apply this policy with jwt.

**Comment by ozevren** [comment]
@wattli @diemtvu @lei-tang 
Folks, can one of you route this appropriately and get it fixed?

**Comment by yangminzhu** [comment]
This should already be fixed by https://github.com/istio/istio/pull/14910 in 1.2.

@daleangus you missed a few whitespaces before the `issuer` and `jwksUri` field, the correct yaml should be like the following:
```
apiVersion: "authentication.istio.io/v1alpha1"
kind: Policy
metadata:
  name: front-end-policy
spec:
  targets:
  - name: front-end
  origins:
  - jwt:
      issuer: "testing@secure.istio.io"
      jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.1/security/tools/jwt/samples/jwks.json"
  principalBinding: USE_ORIGIN
```
