### ISSUE TITLE
DestinationRule subsets don't allow slashes in label selectors

### ISSUE THREAD

**Issue by dokipen** [istio/istio#14797]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

DestinationRule doesn't accept subset labels with slashes. 

**Affected product area (please put an X in all that apply)**

[ x] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Expected behavior**

Using labels with slashes for subsets should be allowed.

**Steps to reproduce the bug**

Create a destination rule with a subet label that contains a slash in the key name.

```admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: 1 error occurred:
    * invalid tag key: "mydomain.com/tag"```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

1.1.8

**How was Istio installed?**

helm chart

**Environment where bug was observed (cloud vendor, OS, etc)**

EKS

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by elevran** [comment]
Shouldn't k8s.io/apimachinery/pkg/apis/meta/v1/validation be used?
This has a `ValidateLabels()` function...

**Comment by rmichela** [comment]
A heavy handed workaround for this bug is to disable the Galley validating webhook altogether.

If installing Istio with Helm, install with `--set global.configValidation=false`.

**Comment by rmichela** [comment]
Here's a specific example of where this bug causes problems:

*Deployment*
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-service-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: my-service
      app.kubernetes.io/version: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: my-service
        app.kubernetes.io/version: 1
    spec:
      ...
```

*DestinationRule*
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: my-service-destinationrule
  namespace: default
spec:
  host: my-service.default.svc.cluster.local
  subsets:
    - name: v1
      labels:
        app.kubernetes.io/version: 1
```

*VirtualService*
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-service-virtualservice
  namespace: default
spec:
  gateways:
    - mesh
    - http-gateway
  hosts:
    - my-service.default.svc.cluster.local
    - http-gateway.foo.com
  http:
    - route:
      - destination:
          host: my-service.default.svc.cluster.local
          subset: v1
```

* The `DestinationRule` referring to the `app.kubernetes.io/version: 1` label doesn't work and routes aren't published.
* If I replace `app.kubernetes.io/version: 1` with `version: 1` in the `Deployment` and `DestinationRule`, routing correctly resumes.
