### ISSUE TITLE
IP addresses should be rejected when resolution: DNS is based

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#14811]
```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin-bar
spec:
  hosts:
  # must be of form name.namespace.global
  - httpbin.bar.global
  location: MESH_INTERNAL
  ports:
  - name: http1
    number: 8000
    protocol: http
  resolution: DNS
  endpoints:
  - address: 5.6.7.8
    network: external
    ports:
      http1: 15443 # Do not change this port value
  - address: istio-ingressgateway.istio-system.svc.cluster.local
    ports:
      http1: 15443
EOF
```

This generates the config:

```json
   {
     "version_info": "2019-06-13T18:29:07Z/28",
     "cluster": {
      "name": "outbound|8000||httpbin.bar.global",
      "type": "STRICT_DNS",
      "connect_timeout": "10s",
      "circuit_breakers": {
       "thresholds": [
        {
         "max_retries": 1024
        }
       ]
      },
      "dns_refresh_rate": "300s",
      "dns_lookup_family": "V4_ONLY",
      "load_assignment": {
       "cluster_name": "outbound|8000||httpbin.bar.global",
       "endpoints": [
        {
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "istio-ingressgateway.istio-system.svc.cluster.local",
              "port_value": 15443
             }
            }
           },
           "load_balancing_weight": 1
          }
         ],
         "load_balancing_weight": 1
        }
       ]
      }
     },
     "last_updated": "2019-06-13T18:29:07.170Z"
    },
```

The `5.6.7.8` address is never sent to Envoy (I think, unless it rejects it silently). Neither Envoy or Pilot have any logging about it

This can be rejected by Galley.

cc @sdake @linsun
