### ISSUE TITLE
Wildcard destination rules are silently ignored when Spec.Host specifies a different namespace from its definition

### ISSUE THREAD

**Issue by jacob-delgado** [istio/istio#14817]
**Bug description**
Wildcard destination rules defined in a namespace for services in a different
namespace with exportTo=* are not globally exported, but are silently ignored.
This does not pertain to istio-system namespace.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience

**Expected behavior**
Globally exported destination rules that match a host based on wildcards would
have their configuration propagated to envoy sidecars based on the most specific wildcard matching (e.g. *.namespace.svc.cluster.local has precedence over *.local).

**Steps to reproduce the bug**
1. Install bookinfo in the default namespace
2. Create a new namespace, 'foo'
3. Apply the following destination rule:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: foo-destinationrule
  namespace: foo
spec:
  exportTo:
  - '*'
  host: "*.default.svc.cluster.local"
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
        connectTimeout: 30ms
    loadBalancer:
      simple: LEAST_CONN
```

4. Using istioctl examine the proxy config of a pod in the default namespace;
in this case productpage (e.g. istioctl proxy-config clusters productpage-v1-6597cb5df9-bnxlz -o json).

Here is a snippet of the config when using istio-auth.yaml at the top level (istio-system has a rule for using mTLS globally for *.local).

The left side shows when the same destination rule is applied in the same namespace whereas the right shows when it is defined in a different namespace.

![Screen Shot 2019-06-13 at 4 30 37 PM](https://user-images.githubusercontent.com/38300436/59471557-9dc74980-8df8-11e9-97a1-7fae1200920c.png)

5. Change the above destination rule to be in namespace 'default' and re-apply.
6. When inspecting the proxy config of a pod in the namespace the above destination rule is
propagated to the envoy sidecar.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.1.3

**How was Istio installed?**
Install with Helm via helm template.

**Environment where bug was observed (cloud vendor, OS, etc)**
Kops installed kubernetes cluster on AWS; kubernetes 1.12.7 server.

**Comment by nrjpoddar** [comment]
What's the expected behavior when destination rules are defined using wildcards in a namespace other than the service (destination) or istio-global namespace? If we don't want to allow it, we should reject it in galley instead of silently ignoring it.

**Comment by nrjpoddar** [comment]
@rshriram can you clarify on the expected behavior?

**Comment by howardjohn** [comment]
The behavior is pretty well commented here https://github.com/istio/istio/blob/7dd93b3f70ee1305dc7f258375fb0097a1781600/pilot/pkg/model/push_context.go#L479

If I am understanding right, this is expected. `foo` should not be able to set rules for default. The DR will either come from the caller namespace, destination namespace, or istio-system

**Comment by nrjpoddar** [comment]
Thanks @howardjohn. Why is foo namespace not consider the calling namespace in this example? Is it because of wildcard hostname?

If you think the expected behavior is to ignore then we should reject the config via Galley.

**Comment by howardjohn** [comment]
It wouldn't always be ignored. If you are calling from the foo namespace, then those settings would apply. My understand is in this case those config dumps are from pods in the default namespace? Maybe I am mistaken though

**Comment by nrjpoddar** [comment]
If the exportTo is set to "*" and we have no Sidecar resources defined for config pruning, I would expect the cluster output to be the same in this case irrespective of whether I look in the pod of default or foo namespace. Isn't that correct?

**Comment by howardjohn** [comment]
I don't believe so. If you want to create global rules you should create them in `istio-system` (really the config RootNamespace but that is istio-system by default). Someone in the `foo` namespace should not be able to configure settings from `bar`->`default` traffic

**Comment by nrjpoddar** [comment]
I see. We verified (thanks @jacob-delgado) the behavior and it aligns with your explanation. Here's what we saw:

1. Any DestinationRules defined in the client namespace (i.e. not in target namespace) with exportTo set to "*" is equivalent to setting exportTo to "." as only sidecars in client namespace get that configuration. Inspecting the Envoy config in the client namespace did show the correct settings.

2. For global DestinationRules you either need to create them in config RootNamespace as you mentioned or in the target namespace with exportTo set to "*".

We should document the bullet 1 clearly as it was quite confusing to understand the semantics. I can file a bug in the [docs site](https://github.com/istio/istio.io) to explain it better. Do you agree?

**Comment by howardjohn** [comment]
> Any DestinationRules defined in the client namespace (i.e. not in target namespace) with exportTo set to "*" is equivalent to setting exportTo to "." as only sidecars in client namespace get that configuration. Inspecting the Envoy config in the client namespace did show the correct settings.



If you defined a DR with exportTo * in namespace `a`, and namespace `b` calls `a` it will should get that config. But if you set it to `.` it will not, as far as I know. So it seems like those are not equivalent, or am I misunderstanding?

**Comment by nrjpoddar** [comment]
I should clarify:

Any DestinationRules defined in the client namespace (i.e. not in target namespace) **for the hostname set to the target namespace service or wildcard for the target namespace** with exportTo set to "*" is equivalent to setting exportTo to "." as only sidecars in client namespace get that configuration. Inspecting the Envoy config in the client namespace did show the correct settings.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: foo-destinationrule
  namespace: foo
spec:
  exportTo:
  - '*'
  host: "*.default.svc.cluster.local"
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
        connectTimeout: 30ms
    loadBalancer:
      simple: LEAST_CONN
```

In the DR above exportTo "*"  has no meaning.

**Comment by nrjpoddar** [comment]
From the current docs https://istio.io/docs/reference/config/networking/v1alpha3/destination-rule/:

exportTo | string[] | A list of namespaces to which this destination rule is exported. The resolution of a destination rule to apply to a service occurs in the context of a hierarchy of namespaces. Exporting a destination rule allows it to be included in the resolution hierarchy for services in other namespaces. This feature provides a mechanism for service owners and mesh administrators to control the visibility of destination rules across namespace boundaries.

**If no namespaces are specified then the destination rule is exported to all namespaces by default.**

**Comment by hzxuzhonghu** [comment]
DestinationRule should not reside in a different ns rather than Client and service ns or root config ns, which is meaningless .

**Comment by nrjpoddar** [comment]
I agree, but I’m suggesting that we shouldn’t allow DRs in client namespaces which have exportTo set to “*” and hostnames set to the target service in a different namespace.

**Comment by rshriram** [comment]
exportTo is independent of Sidecar. if you set exportTo, then its as @howardjohn says.. local namespace of the caller, owning namespace of the destination, and finally the config root namespace.

**Comment by rshriram** [comment]
> I agree, but I’m suggesting that we shouldn’t allow DRs in client namespaces which have exportTo set to “*” and hostnames set to a target service in a different namespace.

you can build admission controllers for this. But this is not doable in the validation as there is no client/server in validation context.

**Comment by nrjpoddar** [comment]
@rshriram it won't be relying on client/server semantics. It will only rely on inspecting a single DestionationRule resource.  For example we can reject this config:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: foo-destinationrule
  namespace: foo
spec:
  exportTo:
  - '*'
  host: "*.default.svc.cluster.local"
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
        connectTimeout: 30ms
    loadBalancer:
      simple: LEAST_CONN
```

as the DR lives in namespace `foo`, has `host` set to `*.default.svc.cluster.local` and exportTo set to `*`. The exportTo setting of `*` is what is misleading and incorrect in my opinion.
