### ISSUE TITLE
Pilot should internally perform validation when using Kube controller (no Galley)

### ISSUE THREAD

**Issue by Stono** [istio/istio#14836]
Hi, 
Someone on my team deployed an invalid Sidecar configuration today and it sent pilot into a panic crash loop:

```
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  labels:
    app: vds-acceptor
    group: delivery-platform
    heritage: Tiller
    release: vds-acceptor
  name: vds-acceptor-policy
  namespace: vds-acceptor
spec:
  ingress:
  - port:
      number: 8138
      protocol: TCP
      defaultEndpoint: 127.0.0.1:8138
  egress:
  - hosts:
    - vds-acceptor/*
    - istio-system/zipkin.istio-system.svc.cluster.local
    - istio-system/jaeger-agent.istio-system.svc.cluster.local
    - istio-system/istio-telemetry.istio-system.svc.cluster.local
    - istio-system/istio-policy.istio-system.svc.cluster.local
    - kube-system/kube-dns.kube-system.svc.cluster.local
    - core-system/logstash.core-system.svc.cluster.local
  workloadSelector:
    labels:
      app: vds-acceptor
```

Notice how `defaultEndpoint` is at the wrong level (that's the only thing i could spot wrong).

It results in:

```
panic: runtime error: index out of range                                                                                                                                                                                                                                                                                                                                                                                                                                                    goroutine 459 [running]:
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).buildInboundClusters(0xc420756880, 0xc4202d4410, 0xc420504000, 0xc420f76000, 0xc42000c248, 0x1, 0x1, 0xc42000c718, 0x1, 0x1, ...)
        /workspace/go/src/istio.io/istio/pilot/pkg/networking/core/v1alpha3/cluster.go:455 +0xd61
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).BuildClusters(0xc420756880, 0xc4202d4410, 0xc420504000, 0xc420f76000, 0x0, 0x6b6, 0x73, 0x40d17d, 0xc420038000)
        /workspace/go/src/istio.io/istio/pilot/pkg/networking/core/v1alpha3/cluster.go:112 +0x345                                                                                                                                             istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).generateRawClusters(0xc42068e420, 0xc420504000, 0xc420f76000, 0x0, 0xbf38f435a3e38b90, 0x15986fcdf, 0x2a349e0, 0x3)                                                                        /workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/cds.go:74 +0x6e                                                                                                                                                             istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).pushCds(0xc42068e420, 0xc4212f8000, 0xc420f76000, 0xc420fd32c0, 0x16, 0x4, 0x0)                                                                                                            /workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/cds.go:51 +0x5e                                                                                                                                                             istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).StreamAggregatedResources(0xc42068e420, 0x1deb780, 0xc4211a0370, 0x0, 0x0)                                                                                                                 /workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/ads.go:441 +0x1221                                                                                                                                                          istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2._AggregatedDiscoveryService_StreamAggregatedResources_Handler(0x1c11c60, 0xc42068e420, 0x1de5120, 0xc4210de000, 0x2a534c0, 0xc4215faab0)                      /workspace/go/src/istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2/ads.pb.go:197 +0xb2                                                                                                         istio.io/istio/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc4200b4780, 0x1ded8e0, 0xc420c2e900, 0xc420cd0000, 0xc420535800, 0x2a1b500, 0xc4215faa80, 0x0, 0x0)
        /workspace/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:1124 +0x911
istio.io/istio/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4200b4780, 0x1ded8e0, 0xc420c2e900, 0xc420cd0000, 0xc4215faa80)
        /workspace/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:1212 +0x12b1
istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420f6e170, 0xc4200b4780, 0x1ded8e0, 0xc420c2e900, 0xc420cd0000)
        /workspace/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:686 +0x9f                                                                                                                                                    created by istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams.func1                                                                                                                                                                  /workspace/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:684 +0xa1
```
