### ISSUE TITLE
istio sidecar injector limit too big

### ISSUE THREAD

**Issue by suridaddy** [istio/istio#14835]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
CPU limit(cpu 2000m) of istio sidecar is too big(much bigger than the CPU request value) which conflicts with namespace level quota limit design. 

 Currently, we set quota limit(both request and limit) in namespace level. And we met following error:
```
status:
  conditions:
  - lastTransitionTime: 2019-06-14T06:31:40Z
    lastUpdateTime: 2019-06-14T06:31:40Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2019-06-14T06:31:40Z
    lastUpdateTime: 2019-06-14T06:31:40Z
    message: 'pods "asdfa-7s0kp-test-details-f757c8f9d-jdfqj" is forbidden: exceeded
      quota: t111111-test-quota, requested: limits.cpu=3, used: limits.cpu=3, limited:
      limits.cpu=4'
    reason: FailedCreate
    status: "True"
    type: ReplicaFailure
  observedGeneration: 1
  unavailableReplicas: 1
```
In fact, the limit of the application pod is 1000m, and now, the quota check found that 3000m cpu limits reaches, and no enough resources left for other pod, so the later pods failed to start.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[X] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Expected behavior**
Why the CPU limit is set so big, 2000m? Can we modify it smaller?If yes, what's the rules to follow to deduce the size?

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.1.5

**How was Istio installed?**
helm chart from GitHub.

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
