### ISSUE TITLE
Mixer: Add password for Redis Handler for rate limiting

### ISSUE THREAD

**Issue by SuperMohit** [istio/istio#14830]
```
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: redishandler
  namespace: istio-system
spec:
  compiledAdapter: redisquota
  params:
    **redisServerUrl: redis-release-master:6379**
    connectionPoolSize: 10
    quotas:
```

  Redishandler only has redis URL. But no way to provide password and dbname.
