### ISSUE TITLE
Cluster ports config is not scoped by the Sidecar resource

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#14870]
Steps to reproduce the bug:
create a sidecar resource to limit egress traffic to the `default` and `istio-system` namespaces, and to `httpbin.org` port 80:

```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
  namespace: default
spec:
  egress:
  - port:
      number: 80
      protocol: HTTP
    hosts:
    - "*/httpbin.org"
  - hosts:
    - "default/*"
    - "istio-system/*"  
EOF
```

Define a service entry for port 80 and 443:

```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin-ext
spec:
  hosts:
  - httpbin.org
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
EOF
```

Define a destination rule for port 443, for httpbin.org:

```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mlts-httpbin
spec:
  host: httpbin.org
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: ISTIO_MUTUAL
        sni: my.httpbin.org
EOF
```

Dump cluster info. The following cluster appears for a pod in the default namespace:

```
   {
        "name": "outbound|443||httpbin.org",
        "type": "STRICT_DNS",
        "connectTimeout": "10s",
        "loadAssignment": {
            "clusterName": "outbound|443||httpbin.org",
            "endpoints": [
                {
                    "lbEndpoints": [
                        {
                            "endpoint": {
                                "address": {
                                    "socketAddress": {
                                        "address": "httpbin.org",
                                        "portValue": 443
                                    }
                                }
                            },
                            "loadBalancingWeight": 1
                        }
                    ],       
         },
        "circuitBreakers": {
            "thresholds": [
                {
                    "maxRetries": 1024
                }
            ]
        },
        "tlsContext": {
            "commonTlsContext": {
                "tlsCertificates": [
                    {
                        "certificateChain": {
                            "filename": "/etc/certs/cert-chain.pem"
                        },
                        "privateKey": {
                            "filename": "/etc/certs/key.pem"
                        }
                    }
                ],
                "validationContext": {
                    "trustedCa": {
                        "filename": "/etc/certs/root-cert.pem"
                    }
                },                
               "alpnProtocols": [
                    "istio"
                ]
            },
            "sni": "my.httpbin.org"
        },
        "dnsRefreshRate": "5s",
        "dnsLookupFamily": "V4_ONLY",
        "metadata": {
            "filterMetadata": {
                "istio": {
                    "config": "/apis/networking/v1alpha3/namespaces/default/destination-rule/mlts-httpbin"
                }
            }
        }
    },
```

The expectation is that the cluster configuration will be filtered by the Sidecar resources, and the clusters for httpbin.org, port 443 will not appear in the configuration. This feature is critical when a destination rule uses client certificates. We want to create destination rules for some hosts that will use client certificates mounted for some pods and not mounted for other pods. Currently, it is not possible, DestinationRules are applied for all the pods.
