### ISSUE TITLE
Pilot resource limit in 1.1.8 is less than the request

### ISSUE THREAD

**Issue by pc-rshetty** [istio/istio#14903]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
Pilot resource limit in 1.1.8 is less than the request
```
  Namespace                  Name                                           CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ---------                  ----                                           ------------  ----------  ---------------  -------------
  istio-system               istio-pilot-cbb879d6-f6mwj                     600m (30%)    2 (100%)    2176Mi (27%)     1Gi (13%)
```
**Affected product area (please put an X in all that apply)**

[Y ] Configuration Infrastructure
[ ] Docs
[ Y] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastrcture

**Expected behavior**
Limits should be less than requests
**Steps to reproduce the bug**
install using helm
**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.1.8
**How was Istio installed?**
helm
**Environment where bug was observed (cloud vendor, OS, etc)**
EKS
Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
The command you used is misleading, if the limit was actually less than the request kubernetes would reject the config.

Pilot has two containers.
discovery:
```
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
```

istio-proxy:
```
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi
```
