### ISSUE TITLE
Meshed workloads can't talk to K8s services with ports named "grpc"

### ISSUE THREAD

**Issue by esnible** [istio/istio#14909]
Re: https://discuss.istio.io/t/port-named-grpc-lacks-listener-breaks-connection/2705

Meshed pods cannot not talk to CockroachDB because of port naming.  This is because the CockroachDB K8s Service uses a port named "grpc".  Changing the port name to "plain" fixes the problem.

I discovered the non-meshed clients could talk to this instance, but meshed pods cannot.

I installed CockroachDB outside the mesh, in a namespace that Istio does not inject, using `helm install --namespace non-istio --name my-release stable/cockroachdb`.  I traced the problem to the Service created by the helm chart:

```
apiVersion: v1
kind: Service
metadata:
  name: my-release-cockroachdb-public
  namespace: non-istio
spec:
  ports:
  - name: grpc
    port: 26257
    protocol: TCP
    targetPort: 26257
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    component: my-release-cockroachdb
  type: ClusterIP
```

If I changed “grpc” to “plain” it worked.

What does it mean when a Service port is named “grpc”? The Istio docs at https://istio.io/docs/setup/kubernetes/prepare/requirements/ just say the name is needed to take advantage of routing features. What I noticed was that the CockroachDB helm chart author’s choice to name the port “grpc” caused Envoy to lack a listener.  Even if we fix this problem we should modify the list of meaningful port names to explain what the names do.  For example, the name "http" allows Istio traffic management.  Do any of the others affect behavior in a way that is observable to the user?

Anyone wishing to experiment can test the same way I did. I did `kubectl -n <ns> run -it cockroach-client --image=cockroachdb/cockroach --restart=Never --command bash` and ran the command `./cockroach sql --insecure --host my-release-cockroachdb-public.test --execute "SHOW DATABASES"`. This works from non-injected namespaces, and from injected namespaces if the K8s Service Port is not named “grpc”.

**Comment by howardjohn** [comment]
I used to have cockroachDB running but just ran it now and get the same issue. We have tests for grpc though, this may be a headless service + grpc issue

**Comment by esnible** [comment]
@howardjohn The service isn't headless.  CockroachDB comes with two Services: *-cockroachdb which listens on 26257 and 8080, and *-cockroachdb-public which listens on exactly the same ports.  Both Services select the same workload.

(I have not yet been able to get the CockroachDB cluster itself up and running in an injected namespace, perhaps for the same reason.  Experiments ongoing.)

I know we have issues related to incorrect telemetry when multiple K8s services select the same pod ( https://github.com/istio/istio/issues/11578 ).  That issue should not affect correctness.

**Comment by howardjohn** [comment]
Maybe I'll have to look into it more, but I thought cockroach was using a statefulset which requires a headless service. Then there is a non headless service for clients

Maybe it has changed since I tested it out a while ago

**Comment by esnible** [comment]
The Service *-cockroachdb is Headless (Type is `None`).  It has a selector and three Endpoints coming from the three pods in the StatefulSet.

The Service *-cockroachdb-public is `ClusterIP`.  It has a selector and three Endpoints.

As I said, the port name keeps meshed clients from talking to the non-meshed CockroachDB.

I attempted to run CockroachDB in the mesh.  In addition to the StatefulSet there is a Job which completes outside the mesh but when run under the mesh just logs the same messages over and over.

```
+ /cockroach/cockroach init --insecure --host=abc-cockroachdb-0.abc-cockroachdb --port 26257
E190616 17:20:20.282692 1 cli/error.go:230  initial connection heartbeat failed: rpc error: code = Internal desc = server closed the stream without sending trailers
Error: initial connection heartbeat failed: rpc error: code = Internal desc = server closed the stream without sending trailers
Failed running "init"
```

**Comment by mike-holberger** [comment]
did you try creating the necessary service entry (location: MESH_INTERNAL, hosts: *.cockroachdb) required for statefulsets, as described in issue:  https://github.com/istio/istio/issues/10659 ?

**Comment by esnible** [comment]
@mike-holberger I attempted to create the ServiceEntry.  I was unsuccessful with variants of

```
cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: istio-cockroachdb-stateful-service-entry
  namespace: default
spec:
  hosts:
  - abc-cockroachdb-0.default.svc.cluster.local
  - abc-cockroachdb-1.default.svc.cluster.local
  - abc-cockroachdb-2.default.svc.cluster.local
  - abc-cockroachdb.default.svc.cluster.local
  - abc-cockroachdb-public.default.svc.cluster.local
  location: MESH_INTERNAL
  ports:
  - number: 26257
    name: grpc
    protocol: HTTP
  resolution: NONE
EOF
```

I could consistently get CockroachDB working by doing

```
kubectl patch svc abc-cockroachdb-public --type=json --patch='[{"op": "add", "path": "/spec/ports/0/name", "value": "nonistio-grpc"}]'
kubectl patch svc abc-cockroachdb --type=json --patch='[{"op": "add", "path": "/spec/ports/0/name", "value": "nonistio-grpc"}]'
```

This suggests the problem is related to port naming, not to StatefulSets.  I did NOT need a ServiceEntry to get CockroachDB working.
