### ISSUE TITLE
Path based basic auth

### ISSUE THREAD

**Issue by dweidenfeld** [istio/istio#14901]
**Describe the feature request**
I would expect that istio supports basic authentication for routing.

E.g. like this:

```yaml
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "jwt-example"
spec:
  targets:
  - name: httpbin
  origins:
  - basic:
      secret: "k8s-basic-auth-secret"
      trigger_rules:
      - included_paths:
        - exact: /documentation
  principalBinding: USE_ORIGIN
```
or
```yaml
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "jwt-example"
spec:
  targets:
  - name: httpbin
  origins:
  - basic:
      users: 
      - "myuser:mypassword"
      trigger_rules:
      - included_paths:
        - exact: /documentation
  principalBinding: USE_ORIGIN
```

**Describe alternatives you've considered**
I thought about adding another NGINX proxy in front of the the service, but I do not really want to decrease the performance of each HTTP request by adding another layer.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
