### ISSUE TITLE
External ServiceEntry with HTTPS protocol appears as TCP

### ISSUE THREAD

**Issue by josejulio** [istio/istio#14933]
**Bug description**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastrcture

**Expected behavior**

Data is expected in `istio_requests_total` when using a ServiceEntry with protocol = HTTPS, instead i only see data in `istio_tcp_sent_bytes_total`

This seems true for protocol=HTTP

**Steps to reproduce the bug**

1. Create a ServiceEntry using a protocol=HTTPS
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google
spec:
  location: MESH_EXTERNAL
  hosts:
    - "www.google.com"
  ports:
    - number: 443
      name: https
      protocol: HTTPS
  resolution: DNS
```

2. Connect to a pod in the mesh and start sending data to the host
```bash
istiooc exec -it $POD  -c $CONTAINER -- sh
watch 'curl -v   https://www.google.com'
```

3. Verify that no data regarding this ServiceEntry is added to `istio_requests_total`

Using HTTP does seem to add the data to `istio_requests_total`
```
yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: www-httpvshttps
spec:
  location: MESH_EXTERNAL
  hosts:
    - "www.httpvshttps.com"
  ports:
    - number: 80
      name: http
      protocol: HTTP
  resolution: DNS
``` 

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
$ istioctl version --remote
client version: version.BuildInfo{Version:"1.1.3", GitRevision:"d19179769183541c5db473ae8d062ca899abb3be", User:"root", Host:"fbd493e1-5d72-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.2-56-gd191797"}
citadel version: version.BuildInfo{Version:"0.11.0-6", GitRevision:"74878c5d0f82e501871ab6302fd69e323e47f116", User:"redhat", Host:"redhat", GolangVersion:"go1.10.3", DockerHub:"docker.io/maistra", BuildStatus:"Clean", GitTag:"unknown"}
egressgateway version: version.BuildInfo{Version:"0.11.0-6", GitRevision:"74878c5d0f82e501871ab6302fd69e323e47f116", User:"redhat", Host:"redhat", GolangVersion:"go1.10.3", DockerHub:"docker.io/maistra", BuildStatus:"Clean", GitTag:"unknown"}
galley version: version.BuildInfo{Version:"0.11.0-6", GitRevision:"74878c5d0f82e501871ab6302fd69e323e47f116", User:"redhat", Host:"redhat", GolangVersion:"go1.10.3", DockerHub:"docker.io/maistra", BuildStatus:"Clean", GitTag:"unknown"}
ingressgateway version: version.BuildInfo{Version:"0.11.0-6", GitRevision:"74878c5d0f82e501871ab6302fd69e323e47f116", User:"redhat", Host:"redhat", GolangVersion:"go1.10.3", DockerHub:"docker.io/maistra", BuildStatus:"Clean", GitTag:"unknown"}
pilot version: version.BuildInfo{Version:"0.11.0-6", GitRevision:"74878c5d0f82e501871ab6302fd69e323e47f116", User:"redhat", Host:"redhat", GolangVersion:"go1.10.3", DockerHub:"docker.io/maistra", BuildStatus:"Clean", GitTag:"unknown"}
policy version: version.BuildInfo{Version:"0.11.0-6", GitRevision:"74878c5d0f82e501871ab6302fd69e323e47f116", User:"redhat", Host:"redhat", GolangVersion:"go1.10.3", DockerHub:"docker.io/maistra", BuildStatus:"Clean", GitTag:"unknown"}
sidecar-injector version: version.BuildInfo{Version:"0.11.0-6", GitRevision:"74878c5d0f82e501871ab6302fd69e323e47f116", User:"redhat", Host:"redhat", GolangVersion:"go1.10.3", DockerHub:"docker.io/maistra", BuildStatus:"Clean", GitTag:"unknown"}
telemetry version: version.BuildInfo{Version:"0.11.0-6", GitRevision:"74878c5d0f82e501871ab6302fd69e323e47f116", User:"redhat", Host:"redhat", GolangVersion:"go1.10.3", DockerHub:"docker.io/maistra", BuildStatus:"Clean", GitTag:"unknown"}
```

```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-06-14T18:41:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
istiooc version
oc v3.11.0+maistra-0.11.0+f2e7517
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
kubernetes v1.11.0+d4cacc0
```

**How was Istio installed?**

Using istiooc

**Environment where bug was observed (cloud vendor, OS, etc)**

Fedora 29

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
