### ISSUE TITLE
Telemetry information not found 

### ISSUE THREAD

**Issue by varungbt** [istio/istio#14930]
**Bug description**
Cannot find telemetry information for destination service vbergbauer-speedtest

![image](https://user-images.githubusercontent.com/4632477/59533602-a29c0400-8eb1-11e9-8d04-55cb25a52e9b.png)

I have the above setup functional where the traffic flows from the istio ingress gateway to nginx contoller and finally to the speedtest service, however I do not see the required telemetry information captured for traffic between the nginx ingress controller pod and the speedtest service.

Both the nginx controller and the speedtest are part of the service mesh. Pods of both these services have sidecar injected in them.

nginx ingress controller svc ---> nginx-ingress pod ---> speedtest-svc ---> speedtestpod

The traffic flows perfectly fine from the ingress contoller svc to the speedtest pod.

However no telemetry data is getting collected for the link between nginx ingress pod --> speedtest-svc

Here are the manifests used

### virtual-service 

```

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-virtual-service
  namespace: default
spec:
  gateways:
  - nginx-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: nginx-ingress-controller
        port:
          number: 80
    timeout: 86400s

```

### nginx ingress

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
  labels:
    app: vbergbauer-speedtest
  name: speedtest-ingress
  namespace: default
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: speedtest-vbergbauer-speedtest
          servicePort: 8903
        path: /(speedtest)/?(.*)

```

Any hints on why the telemetry information is not being captured for the hop between the nginx ingress controller pod and the speedtest-svc

 
Istio version: 1.1.7
