### ISSUE TITLE
AWS EKS nginx-ingress helm deployment

### ISSUE THREAD

**Issue by MilanDasek** [istio/istio#14979]
Hi,

I am using AWS EKS cluster with nginx-ingress (classic ELB with SSL termination). I would like to use istio mainly for egress control. In other works, ingress will be still on nginx-ingress, but each POD inside won't be able to communicate to other pods or external service without explicit approval.

I thought this configuration can make it:

`helm install --wait --name istio-init --namespace istio-system install/kubernetes/helm/istio-init
`
```
helm install install/kubernetes/helm/istio --name istio --namespace istio-system \
--set gateways.enabled=false \
--set kiali.createDemoSecret=true \
--set kiali.dashboard.grafanaURL="https://grafana.domain/" \
--set kiali.dashboard.jaegerURL="https://jaeger.domain/" \
--set servicegraph.enabled=true \
--set tracing.enabled=true \
--set kiali.enabled=true \
--set prometheus.enabled=false
```

```
kubectl create ns test-istio
kubectl label namespace test-istio istio-injection=enabled
```

annotation to nginx-ingress POD
`    traffic.sidecar.istio.io/includeInboundPorts: ""`

annotation to ingress resource inside test-istio namespace
```
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/upstream-vhost: <svc name>.<namespace>.svc.cluster.local
```

`kubectl get configmap istio -n istio-system -o yaml | sed 's/mode: ALLOW_ANY/mode: REGISTRY_ONLY/g' | kubectl replace -n istio-system -f -`

and testing ServiceEntry for POD inside test-istio namespace
```
kubectl -n test-istio apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cnn
spec:
  hosts:
  - edition.cnn.com
  ports:
  - number: 80
    name: http-port
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
EOF
```

But when I connect to pod inside test-istio namespace, I can still access all other pods as well as other external web services (not only edition.cnn.com).

Can you please ping me what is right direction?
