### ISSUE TITLE
Issues with regex-based http URI matching in Virtual Service

### ISSUE THREAD

**Issue by bogdansucila** [istio/istio#14983]
**Bug description**

We are currently trying to route http requests based on URI matching, using a regular expression. Basically, any URI that matches '/\\/foo\\/bar/gi' should get routed to our API service, while all other requests for the respective host that don't fit the pattern should be directed to an Azure WebApp. The match shouldn't be case sensitive, hence the '/i' switch at the end.

This doesn't work as expected however, as virtually any request gets redirected to the webapp in question, despite the fact that the regex matches the test URLs in virtually any major regex tester you can find online. I tried a few different iterations, omitting the quotation marks, adding single or double quotes, double escaping characters (\\), using (?i) as a switch for case insensitivity, but to no avail so far.

It's worth mentioning that requests get redirected to the API service when using prefix based matching, however this method implies case sensitive URIs, which is not what we need here.

I added my virtual service config below - any ideas what I might have gotten wrong?

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: partnerapi
spec:
  hosts:
  - "host1.com"
  - "host2.com"
  gateways:
  - partnerapi-app-gateway
  http:
  - match:
    - uri:
        regex: /\/foo\/bar/gi
    rewrite:
      uri: "/partnerapi"
    route:
    - destination:
        host: api1.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: "webapp1.azurewebsites.net"
    retries:
      attempts: 5
      perTryTimeout: 3s
      retryOn: gateway-error,connect-failure,refused-stream
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastrcture

**Expected behavior**

HTTP requests should get routed to the API service if they match the regex pattern.

**Steps to reproduce the bug**

Try creating a virtual service and setting up a regex based HTTP match condition for a destination, where the regex matches a case insensitive URI path.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

Istio - 1.1.0
Kubernetes - 1.12.6

**How was Istio installed?**

Using helm

**Environment where bug was observed (cloud vendor, OS, etc)**

Azure Kubernetes Service (AKS)

**Comment by sushicw** [comment]
Does ECMAscript-style regex support (?i)? Do you have an example that passes a regex tester for this case?

**Comment by sushicw** [comment]
Did some digging. Unfortunately it appears the current regex implementation doesn't support flags. I did find https://github.com/istio/istio/issues/14266, which adds an `ignoreUriCase` option at the match rule level. So you can do e.g.

```yaml
- apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  spec:
    gateways:
    - bookinfo-gateway
    hosts:
    - '*'
    http:
    - match:
      - uri:
          regex: /foo/bar
      ignoreUriCase: true
      rewrite:
        uri: /productpage
      route:
      - destination:
          host: productpage
          port:
            number: 9080
          subset: v2
```

This feature is pretty new (thanks @venilnoronha !), and although it's present in master (and nightly builds) it isn't yet in a release. You can probably expect it in 1.3.

I don't believe there is official documentation for it yet.

**Comment by ramaraochavali** [comment]
`ignoreUriCase` does not work for regex type of URIs

**Comment by sushicw** [comment]
> `ignoreUriCase` does not work for regex type of URIs

@ramaraochavali I found this surprising since I'd tested this yesterday and gotten the OP's use case to work using the snippet posted...I could hit `<my ip>/foo/bar` or `<my ip>Foo/BAR` and both would successfully route. 

I've played with it a bit more and noticed that it does *not* work if the regex itself isn't all lowercase. e.g. the above example works for regex `/foo/bar` but not `/FOO/BAR`.

**Comment by bogdansucila** [comment]
@sushicw Thanks for the suggestion, I did try one of the nightly builds with the sample bookinfo app, and the test case does indeed work. 

Unfortunately I couldn't get it to work with my real-life app URI, and deploying an unstable build into production isn't something I'm particularly keen on. I see the feature was moved into 'Nebulous future' so I'm don't think I should be holding my breath for case insensitive URI matching in any 1.2.x release :)

In the meanwhile, I got the regex to watch, albeit in the least elegant manner imaginable:

```
http:
  - match:
    - uri:
        regex:  .*\/[fF][oO][oO]\/[bB][aA][rR]\/.*?         
    rewrite:
      uri: "/partnerapi"
```

The problem I now have is that although the URI matches the regex, its entire relative path gets selected and then rewritten to /partnerapi, which is not the desired outcome. The URIs contain API calls in the form of _https://example.com/foo/bar/Search?q=category_ which then get rewritten into _https://example.com/partnerapi_ which yields a 404.

One possible solution I thought of was using regex substituion and grouping only the /foo/bar part of the relative path using parantheses, then referencing it for substitution with ${1}, however that doesn't seem to be supported by the rewrite function, which only takes strings as values - see [here](url).

Does anyone know how I could trim only the middle section of the URI here? According to every online regex tester he expression I used should only select the portion until the last "/", the rest being optional (?). Without the trailing wildcards it won't match the regex altogether, simply routing traffic to the Azure WebApp.

**Comment by sushicw** [comment]
Looked into how the rewrite rules work, it looks like we're more or less forwarding this configuration on to the Envoy proxy and letting Envoy handle it. Unfortunately, Envoy doesn't seem to have support for partial rewrite on regex. (See "prefix_rewrite" [here](https://www.envoyproxy.io/docs/envoy/v1.5.0/api-v1/route_config/route)).

There's some support for partial rewrites if you use prefix matching instead of regex, but even that might not quite work how you want. (See [here](https://github.com/envoyproxy/envoy/issues/2857)) If you can reframe your problem in terms of prefix rewrite rules (which will probably be ugly), it might be worth giving it a shot anyway.

**Comment by bogdansucila** [comment]
As an update, I managed to get it working in the end, although it implied way more manual configuration than I would have hoped.

The issue with URL rewrites messing up the API queries turned out to be milder than initially expected - a tcpdump run on the Ingress GW's proxy sidecar revealed that the HTTP requests were trimmed only until the (?), and that the API query that followed was preserved.

Thus, https://example.com/foo/bar/Search?q=category became https://example.com/partnerapi?q=category

What actually messed up my queries was the trimming of the API endpoint, in this case 'Search'. My workaround was writing up a separate regex match case followed by a custom rewrite for each API endpoint:

```
http:
  - match:
    - uri:
        regex:  .*\/[fF][oO][oO]\/[bB][aA][rR]\/Search.*?         
    rewrite:
      uri: "/partnerapi/Search

http:
  - match:
    - uri:
        regex:  .*\/[fF][oO][oO]\/[bB][aA][rR]\/Popular.*?         
    rewrite:
      uri: "/partnerapi/Popular"
```

Luckily, there weren't that many endpoints, so the Virtual Service config didn't end up too bloated, however this is not definitely not a practical approach going long term, as it involves way too much administrative overhead and hard-coded data (I basically have to keep track of any new API endpoints that might appear and remove deprecated ones).

Also, this is a lot of configuration work to do for a rather common scenario - case-insensitive URL matching. As per @sushicw's find, I managed to test out the **ignoreUriCase** feature mentioned in https://github.com/istio/istio/issues/14266 (thanks, btw 🥇 ), however it hasn't been included in any stable releases that I've seen until now, and I am relucatant to push a nightly build into production. @venilnoronha - any idea whether this will be included in a subsequent release?

**Comment by venilnoronha** [comment]
@bogdansucila thanks for bringing that up. This feature was supposed to be available in 1.2.0; however, it seems that the commit was accidentally missed in the release. Let me confirm with the release team.

**Comment by venilnoronha** [comment]
@bogdansucila I've created PR #15562 to port the patch to the release (1.2) branch, so it should be available in the release after the merge.

**Comment by bitgandtter** [comment]
any support for envoy prefix_rewrite?

im trying to perform a regex uri match and then rewrite it but use capturing group. Example using previous configuration:

```
http:
  - match:
    - uri:
        regex:  .*\/[fF][oO][oO]\/([bB][aA][rR])\/Search.*?         
    rewrite:
      uri: "/partnerapi/Search/$1
```
