### ISSUE TITLE
Fixed nodePort for gateway service status-port

### ISSUE THREAD

**Issue by peter-fe** [istio/istio#14987]
**Describe the feature request**

Currently in the Helm install for Istio on k8s, some service ports have fixed node ports assigned
([install/kubernetes/helm/istio/charts/gateways/values.yaml](https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/gateways/values.yaml)).

``` 
ports:
  ...
  - port: 80
    targetPort: 80
    name: http2
    nodePort: 31380
  - port: 443
    name: https
    nodePort: 31390
  # Example of a port to add. Remove if not needed
  - port: 31400
    name: tcp
    nodePort: 31400
```

It would be beneficial if this is also true for the status-port of the gateway service, as right now it gets assigned randomly during installation.
This is somewhat troublesome if you like to operate the Istio gateway in node port mode and use an external load balancer that needs some node port for health checks. (in our case on GCP the L7 HTTPS load balancer).

In our opinion it would bring more consistency as well as flexibility in utilizing node level health checking by making that a fixed node port too, e.g.: 31370 to keep up the pattern.

**Describe alternatives you've considered**

Sure we can try to read out the dynamically assigned node port, but then every automated deployment looks different and we are not sure if it can happen that this node port changes some how after the initial Helm install and our health checks start failing.

Also using --set gateways.istio-ingressgateway.ports[0].nodePort=31370 during the install may help to fix the assignment of the status-port node port, but relies on the assumption, that the status-port will always stay first in the values.yaml. 

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

GCP L7 load balancer as first level load balancer in front of Istio gateway on GKE to get a tighter integration with IAP, managed TLS, ...
