### ISSUE TITLE
Galley validation allows unknown fields, but rejects them internally

### ISSUE THREAD

**Issue by sushicw** [istio/istio#15012]
**Bug description**

Adding invalid entries to match rules, or simply misspelling a valid one, fails silently instead of triggering the webhook validation. The impact is that although you think your config was successfully applied, it was not, and you don't know something's wrong until your stuff doesn't work and/or you dig in the logs. 

e.g. if your match YAML uses "sourcelabels" instead of "sourceLabels", you may not realize why the config isn't working when it appeared to apply successfully.

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastrcture

**Expected behavior**

The expected behavior is that bogus "match" entries should trigger a webhook validation failure, like bogus entries elsewhere in the YAML do. (See below). 

**Steps to reproduce the bug**

**temp3a.yaml** (all valid):
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
  namespace: default
spec:
  hosts:
  - reviews
  http:
  - match:
    - sourceLabels:
        app: productpage
        version: v2
    route:
    - destination:
        host: reviews
        subset: v3
  - route:
    - destination:
        host: reviews
        subset: v2
```
Works as expected:
```console
crwilson@crwilson:~/go/src/istio.io/istio$ kubectl apply -f /tmp/temp3a.yaml 
virtualservice.networking.istio.io/reviews configured
```

**temp3b.yaml** (bogus entry under http):
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
  namespace: default
spec:
  hosts:
  - reviews
  http:
  - BOGUS: true
  - match:
    - sourceLabels:
        app: productpage
        version: v2
    route:
    - destination:
        host: reviews
        subset: v3
  - route:
    - destination:
        host: reviews
        subset: v2
```
Fails on apply, as expected, thanks to webhook:
```console
crwilson@crwilson:~/go/src/istio.io/istio$ kubectl apply -f /tmp/temp3b.yaml 
Error from server: error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"networking.istio.io/v1alpha3\",\"kind\":\"VirtualService\",\"metadata\":{\"annotations\":{},\"name\":\"reviews\",\"namespace\":\"default\"},\"spec\":{\"hosts\":[\"reviews\"],\"http\":[{\"BOGUS\":true},{\"match\":[{\"sourceLabels\":{\"app\":\"productpage\",\"version\":\"v2\"}}],\"route\":[{\"destination\":{\"host\":\"reviews\",\"subset\":\"v3\"}}]},{\"route\":[{\"destination\":{\"host\":\"reviews\",\"subset\":\"v2\"}}]}]}}\n"}},"spec":{"http":[{"BOGUS":true},{"match":[{"sourceLabels":{"app":"productpage","version":"v2"}}],"route":[{"destination":{"host":"reviews","subset":"v3"}}]},{"route":[{"destination":{"host":"reviews","subset":"v2"}}]}]}}
to:
Resource: "networking.istio.io/v1alpha3, Resource=virtualservices", GroupVersionKind: "networking.istio.io/v1alpha3, Kind=VirtualService"
Name: "reviews", Namespace: "default"
Object: &{map["apiVersion":"networking.istio.io/v1alpha3" "kind":"VirtualService" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"networking.istio.io/v1alpha3\",\"kind\":\"VirtualService\",\"metadata\":{\"annotations\":{},\"name\":\"reviews\",\"namespace\":\"default\"},\"spec\":{\"hosts\":[\"reviews\"],\"http\":[{\"match\":[{\"sourceLabels\":{\"app\":\"productpage\",\"version\":\"v2\"}}],\"route\":[{\"destination\":{\"host\":\"reviews\",\"subset\":\"v3\"}}]},{\"route\":[{\"destination\":{\"host\":\"reviews\",\"subset\":\"v2\"}}]}]}}\n"] "creationTimestamp":"2019-06-19T18:20:36Z" "generation":'\x1f' "name":"reviews" "namespace":"default" "resourceVersion":"73032" "selfLink":"/apis/networking.istio.io/v1alpha3/namespaces/default/virtualservices/reviews" "uid":"eeddc3b7-92be-11e9-ad0c-42010a8a0151"] "spec":map["hosts":["reviews"] "http":[map["match":[map["sourceLabels":map["app":"productpage" "version":"v2"]]] "route":[map["destination":map["host":"reviews" "subset":"v3"]]]] map["route":[map["destination":map["host":"reviews" "subset":"v2"]]]]]]]}
for: "/tmp/temp3b.yaml": admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: HTTP route or redirect is required

```

**temp3c.yaml** (Bogus entry under match):
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
  namespace: default
spec:
  hosts:
  - reviews
  http:
  - match:
    - sourceLabels:
        app: productpage
        version: v2
    BOGUS: true
    route:
    - destination:
        host: reviews
        subset: v3
  - route:
    - destination:
        host: reviews
        subset: v2
```
Does NOT fail as expected in kubectl:
```console
crwilson@crwilson:~/go/src/istio.io/istio$ kubectl apply -f /tmp/temp3c.yaml 
virtualservice.networking.istio.io/reviews configured
```
Although it does fail silently, as reflected in the galley logs:
```
{
 insertId:  "963fktg161paig"  
 labels: {…}  
 logName:  "projects/google.com:crwilson-gcp-experimental/logs/galley"  
 receiveTimestamp:  "2019-06-19T23:51:56.482640880Z"  
 resource: {…}  
 severity:  "INFO"  
 textPayload:  "2019-06-19T23:51:50.904031Z	error	kube	Unable to convert unstructured to proto: default/reviews/74364: unknown field "BOGUS" in v1alpha3.HTTPRoute
"  
 timestamp:  "2019-06-19T23:51:50.904243694Z"  
}
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Built on tip of master (0d210f251ece736b2d97747e2244c27517257355)

```console
crwilson@crwilson:~/go/src/istio.io/istio$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.6-gke.6", GitCommit:"fcbc1d20b6bca1936c0317743055ac75aef608ce", GitTreeState:"clean", BuildDate:"2019-05-23T11:42:40Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
crwilson@crwilson:~/go/src/istio.io/istio$ istioctl version --remote
client version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.6-6-geec7a74"}
citadel version: version.BuildInfo{Version:"0d210f251ece736b2d97747e2244c27517257355-dirty", GitRevision:"0d210f251ece736b2d97747e2244c27517257355-dirty", User:"crwilson", Host:"crwilson.c.googlers.com", GolangVersion:"go1.12.5", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.0-rc.3-15-g0d210f251"}
egressgateway version: version.BuildInfo{Version:"0d210f251ece736b2d97747e2244c27517257355-dirty", GitRevision:"0d210f251ece736b2d97747e2244c27517257355-dirty", User:"crwilson", Host:"crwilson.c.googlers.com", GolangVersion:"go1.12.5", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.0-rc.3-15-g0d210f251"}
galley version: version.BuildInfo{Version:"0d210f251ece736b2d97747e2244c27517257355-dirty", GitRevision:"0d210f251ece736b2d97747e2244c27517257355-dirty", User:"crwilson", Host:"crwilson.c.googlers.com", GolangVersion:"go1.12.5", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.0-rc.3-15-g0d210f251"}
ingressgateway version: version.BuildInfo{Version:"0d210f251ece736b2d97747e2244c27517257355-dirty", GitRevision:"0d210f251ece736b2d97747e2244c27517257355-dirty", User:"crwilson", Host:"crwilson.c.googlers.com", GolangVersion:"go1.12.5", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.0-rc.3-15-g0d210f251"}
pilot version: version.BuildInfo{Version:"0d210f251ece736b2d97747e2244c27517257355-dirty", GitRevision:"0d210f251ece736b2d97747e2244c27517257355-dirty", User:"crwilson", Host:"crwilson.c.googlers.com", GolangVersion:"go1.12.5", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.0-rc.3-15-g0d210f251"}
pilot version: version.BuildInfo{Version:"0d210f251ece736b2d97747e2244c27517257355-dirty", GitRevision:"0d210f251ece736b2d97747e2244c27517257355-dirty", User:"crwilson", Host:"crwilson.c.googlers.com", GolangVersion:"go1.12.5", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.0-rc.3-15-g0d210f251"}
pilot version: version.BuildInfo{Version:"0d210f251ece736b2d97747e2244c27517257355-dirty", GitRevision:"0d210f251ece736b2d97747e2244c27517257355-dirty", User:"crwilson", Host:"crwilson.c.googlers.com", GolangVersion:"go1.12.5", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.0-rc.3-15-g0d210f251"}
policy version: version.BuildInfo{Version:"0d210f251ece736b2d97747e2244c27517257355-dirty", GitRevision:"0d210f251ece736b2d97747e2244c27517257355-dirty", User:"crwilson", Host:"crwilson.c.googlers.com", GolangVersion:"go1.12.5", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.0-rc.3-15-g0d210f251"}
sidecar-injector version: version.BuildInfo{Version:"0d210f251ece736b2d97747e2244c27517257355-dirty", GitRevision:"0d210f251ece736b2d97747e2244c27517257355-dirty", User:"crwilson", Host:"crwilson.c.googlers.com", GolangVersion:"go1.12.5", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.0-rc.3-15-g0d210f251"}
telemetry version: version.BuildInfo{Version:"0d210f251ece736b2d97747e2244c27517257355-dirty", GitRevision:"0d210f251ece736b2d97747e2244c27517257355-dirty", User:"crwilson", Host:"crwilson.c.googlers.com", GolangVersion:"go1.12.5", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.0-rc.3-15-g0d210f251"}
```

**How was Istio installed?**
Built locally & installed to test env

**Environment where bug was observed (cloud vendor, OS, etc)**
BookInfo demo app on GKE

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
