### ISSUE TITLE
Upgrade from 1.1.8 to 1.2.0 breaks SDS

### ISSUE THREAD

**Issue by MrBlaise** [istio/istio#15020]
**Bug description**
After upgrading to 1.2.0 using helm template installation I've got:
`TLS error: Secret is not supplied by SDS` messages all over the ingress gateway instance. I have recreated the certificates restarted the ingress instance, the logs said it found the secret, but it still wouldn't work.

Downgrading back to 1.1.8 github tag worked.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Steps to reproduce the bug**
Upgrade to 1.2.0 from 1.1.8 using helm template with SDS set up in your gateway.

**How was Istio installed?**
Helm template (github tag)

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by MrBlaise** [comment]
Relevant part of the logs with istio 1.2.0 in the ingressgateway:

```
[2019-06-20 08:14:03.329][18][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:86] gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: connection failure
[2019-06-20 08:14:05.116][18][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:86] gRPC config stream closed: 2, no credential token is found
[2019-06-20T08:14:04.282Z] "GET / HTTP/2" 503 UF,URX "-" "TLS error: Secret is not supplied by SDS" 0 91 63 - "10.0.96.20" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" "29ff51bb-e6f2-44ca-8457-1bc61521f43f" "REDACTED" "10.0.93.98:80" outbound|80|v1|REDACTED.svc.cluster.local - 10.0.92.103:443 10.0.96.20:49298 REDACTED
```

During the downgrade this happened int the logs:

```
2019-06-20T08:14:15.925698Z     info    watchFileEvents: "/etc/certs/cert-chain.pem": MODIFY|ATTRIB
2019-06-20T08:14:15.925768Z     info    watchFileEvents: "/etc/certs/cert-chain.pem": DELETE
2019-06-20T08:14:15.925975Z     info    watchFileEvents: "/etc/certs/root-cert.pem": MODIFY|ATTRIB
2019-06-20T08:14:15.925990Z     info    watchFileEvents: "/etc/certs/root-cert.pem": DELETE
2019-06-20T08:14:15.926205Z     info    watchFileEvents: "/etc/certs/key.pem": MODIFY|ATTRIB
2019-06-20T08:14:15.926218Z     info    watchFileEvents: "/etc/certs/key.pem": DELETE
2019-06-20T08:14:25.925902Z     info    watchFileEvents: notifying
2019-06-20T08:14:25.926130Z     info    Received new config, resetting budget
2019-06-20T08:14:25.926140Z     info    Reconciling retry (budget 10)
2019-06-20T08:14:25.926164Z     info    Epoch 1 starting
2019-06-20T08:14:25.927145Z     info    Envoy command: [-c /etc/istio/proxy/envoy-rev1.json --restart-epoch 1 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster auth-proxy-ingressgateway --service-node router~10.0.92.103~auth-proxy-ingressgateway-5cf658ddb6-7zx7c.istio-system~istio-system.svc.cluster.local --max-obj-name-len 189 --allow-unknown-fields -l warning]
```

And it started working again.

**Comment by linsun** [comment]
@myidpt can you check it out?  I can't find out where "Secret not supplied by SDS" is produced and this seems SDS specific.

**Comment by howardjohn** [comment]
@linsun its in envoy https://github.com/envoyproxy/envoy/blob/master/source/extensions/transport_sockets/tls/ssl_socket.cc#L25

**Comment by sdake** [comment]
This is the most relevant part of the log `[2019-06-20 08:14:05.116][18][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:86] gRPC config stream closed: 2, no credential token is found
`

**Comment by sdake** [comment]
@MrBlaise can you comment about how you intalled 1.1.8 (which options) and how you upgraded (with which options)?

`helm template` or `helm upgrade` mode
paste `helm version`, please

**Comment by wattli** [comment]
Thanks @sdake , this will be very helpful for the debugging.

**Comment by JimmyCYJ** [comment]
@MrBlaise Could you show us the config dump of ingres gateway? The 503 sounds like ingress gateway fail to talk to internal backend sidecar. It would help if we can verify whether the dynamic cluster config has SDS config or file mount path for certs.

**Comment by JimmyCYJ** [comment]
If dynamic cluster config has SDS config, could you also show us whether citadel agent is running per node?

**Comment by MrBlaise** [comment]
I will provide a more details once I am in the office, but I used helm template to install istio. I have two ingressgateways one acts as the edge (it allows internal employees only) and it forwards requests to the other one internally.

**Comment by JimmyCYJ** [comment]
From the log
""GET / HTTP/2" 503 UF,URX "-" "TLS error: Secret is not supplied by SDS" 0 91 63 - "10.0.96.20" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" "29ff51bb-e6f2-44ca-8457-1bc61521f43f" "REDACTED" "10.0.93.98:80" outbound|80|v1|REDACTED.svc.cluster.local - 10.0.92.103:443 10.0.96.20:49298 REDACTED"
It is the failure between ingress gateway and the workload side car.
According to https://www.envoyproxy.io/docs/envoy/latest/configuration/access_log,
UF: Upstream connection failure in addition to 503 response code.

**Comment by JimmyCYJ** [comment]
> I will provide a more details once I am in the office, but I used helm template to install istio. I have two ingressgateways one acts as the edge (it allows internal employees only) and it forwards requests to the other one internally.

Thanks for the response. Is this 503 from the edge ingressgateway? If yes, then the edge ingress gateway tries to forward request to the core ingress gateway via mTLS. Then you need to use the file mount approach to provide key/cert for the edge ingress gateway's Cluster config and the core ingress gateway's Listener config. Maybe the upgrade enables SDS for edge ingress gateway's Cluster config.

**Comment by MrBlaise** [comment]
The edge first forwards normally to an apache instance that does oauth authentication and that service forwards it to the other ingress. But after upgrading the whole process stops at the edge the apache server is never called. With 1.1.8 it works perfectly fine using sds on the edge :/

**Comment by JimmyCYJ** [comment]
So the failure is between edge and apache server. A config dump via $ curl 127.0.0.1:15000/config_dump would help. Looks like the edge tries to talk to apache through a Cluster "outbound|80|v1|REDACTED.svc.cluster.local"

**Comment by MrBlaise** [comment]
@JimmyCYJ here is the dump: https://gist.github.com/MrBlaise/443e93c0c74a374ecc3f77446f68f96d

**Comment by MrBlaise** [comment]
My helm values are the following:

```
global:
  # This needs to be turned off when using sds.
  # It might be fixed in istio 1.2
  # The reason it fails is because it needs the mounted secret to work and sds disables that
  controlPlaneSecurityEnabled: false

  mtls:
    # Default setting for service-to-service mtls. Can be set explicitly using
    # destination rules or service annotations.
    enabled: true

  sds:
    enabled: true
    udsPath: "unix:/var/run/sds/uds_path"
    useNormalJwt: true

  disablePolicyChecks: false

  proxy:
    accessLogFile: "/dev/stdout"

sidecarInjectorWebhook:
  enabled: true
  # If true, webhook or istioctl injector will rewrite PodSpec for liveness
  # health check to redirect request to sidecar. This makes liveness check work
  # even when mTLS is enabled.
  rewriteAppHTTPProbe: true

mixer:
  policy:
    enabled: true
    autoscaleMax: 2
  telemetry:
    enabled: true
    autoscaleMax: 2

pilot:
  autoscaleMax: 2

# Nodeagent will utilise the Secret Discovery Service (SDS) to enable mutual TLS without kubernetes secrets
nodeagent:
  enabled: true
  image: node-agent-k8s
  env:
    CA_PROVIDER: "Citadel"
    CA_ADDR: "istio-citadel:8060"
    VALID_TOKEN: true

# Enabling sds will allow us to utilize cert-manager with let's encrypt certs
gateways:
  istio-ingressgateway:
    enabled: true
    sds:
      enabled: true
    type: ClusterIP
    autoscaleMax: 3
    ports:
    - name: status-port
      port: 15020
      protocol: TCP
      targetPort: 15020
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    - name: tcp
      port: 31400
      protocol: TCP
      targetPort: 31400
    - name: https-kiali
      port: 15029
      protocol: TCP
      targetPort: 15029
    - name: https-prometheus
      port: 15030
      protocol: TCP
      targetPort: 15030
    - name: https-grafana
      port: 15031
      protocol: TCP
      targetPort: 15031
    - name: https-tracing
      port: 15032
      protocol: TCP
      targetPort: 15032
    - name: tls
      port: 15443
      protocol: TCP
      targetPort: 15443
  auth-proxy-ingressgateway:
    enabled: true
    sds:
      image: node-agent-k8s
      enabled: true
    labels:
      app: auth-proxy-ingressgateway
      istio: auth-proxy-ingressgateway
    autoscaleEnabled: true
    replicaCount: 1
    autoscaleMin: 1
    autoscaleMax: 3
    cpu:
      targetAverageUtilization: 80
    type: LoadBalancer #change to NodePort, ClusterIP or LoadBalancer if need be
    loadBalancerIP: REDACTED
    ports:
    - name: status-port
      port: 15020
      protocol: TCP
      targetPort: 15020
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    - name: tcp
      port: 31400
      protocol: TCP
      targetPort: 31400
    - name: https-kiali
      port: 15029
      protocol: TCP
      targetPort: 15029
    - name: https-prometheus
      port: 15030
      protocol: TCP
      targetPort: 15030
    - name: https-grafana
      port: 15031
      protocol: TCP
      targetPort: 15031
    - name: https-tracing
      port: 15032
      protocol: TCP
      targetPort: 15032
    - name: tls
      port: 15443
      protocol: TCP
      targetPort: 15443

certmanager:
  enabled: true

# Enables tracing using jaeger
tracing:
  enabled: true
  ingress:
    enabled: false

grafana:
  enabled: true

# A service to visualize the service mesh
kiali:
  enabled: true
  tag: v0.20
  dashboard:
    jaegerURL: "http://localhost:16686/jaeger"
    grafanaURL: "http://localhost:3000"
```

I just realized this part I had commented:

```
  # This needs to be turned off when using sds.
  # It might be fixed in istio 1.2
  # The reason it fails is because it needs the mounted secret to work and sds disables that
  controlPlaneSecurityEnabled: false
```

Might be something interesting or not connected at all.
