### ISSUE TITLE
External HTTPS traffic always fill telemetry for a existing ServiceEntry

### ISSUE THREAD

**Issue by josejulio** [istio/istio#15038]
**Bug description**

External HTTPS traffic always fill telemetry for a existing ServiceEntry (even if it doesn't match)

For example, If i have a ExternalService to `www.apple.com` and i do requests to `en.wikipedia.org`, data is filled from the pod that called wikipedia, but the de `destination_service_name` points to `www.apple.com`.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastrcture

**Expected behavior**

I would expect not to see any data for `istio_tcp_sent_bytes_total{destination_service_name="www.apple.com"}`, perhaps data to `istio_tcp_sent_bytes_total{destination_service_name="en.wikipedia.org"}` or no data at all (because en.wikipedia.org is not a ServiceEntry)

**Steps to reproduce the bug**

1. Add ServiceEntry  `www.apple.com`
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-apple
  namespace : travel-agency
spec:
  hosts:
    - "www.apple.com"
  exportTo:
    - "."
  location: MESH_EXTERNAL
  ports:
    - number: 443
      name: https
      protocol: HTTPS
  resolution: NONE
```

2. Connect to a pod in the mesh and start sending requests to `en.wikipedia.org`
```bash
istiooc exec -it $POD  -c $CONTAINER -- sh
watch "curl https://en.wikipedia.org/wiki/Main_Page | grep -o '<title>.*</title>'"
```
3. Confirm that the curl request is going directly to wikipedia:
`<title>Wikipedia, the free encyclopedia</title>`

4. Inspect the telemetry by checking `istio_tcp_sent_bytes_total{destination_service_name="www.apple.com"}` in prometheus.

Even when we aren't doing any request to www.apple.com, the external traffic points here.

Note: It doesn't appear in `istio_requests_total`, see this other [issue](https://github.com/istio/istio/issues/14933).

![istio-service-entry-telemetry](https://user-images.githubusercontent.com/3845764/59879314-0752d500-9370-11e9-88b5-bb0ad255f104.png)

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

I tried with maistra installer and installing istio with helm

**Environment where bug was observed (cloud vendor, OS, etc)**

Fedora 29

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
