### ISSUE TITLE
Virtual service HTTPMatchRequest with queryParams or headers doesn't work.

### ISSUE THREAD

**Issue by diemtvu** [istio/istio#15114]
**Bug description**

I set up a virtual service and destination rule like below. I expect the first `httproute` will be triggered only when request contains params `version=bar` (or header `x-version: bar`), and route to `bar`. Any other request should match the second route rule and go to foo (per [API](https://github.com/istio/api/blob/master/networking/v1alpha3/virtual_service.proto#L164): _The first rule matching an incoming request is used_.

However, looks like `queryParams` (or `headers`) was ignored, and the first route match all requests hence the `bar` server is always hit.

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx
  namespace: demo
spec:
  hosts:
  - "*"
  gateways:
  - istio-autogenerated-k8s-ingress.istio-system.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: /
      queryParams:
        version:
          exact: bar
    route:
    - destination:
        port:
          number: 80
        host: nginx.demo.svc.cluster.local
        subset: bar
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: nginx.demo.svc.cluster.local
        subset: foo
```
And destination rule:
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: nginx
  namespace: demo
spec:
  host: nginx
  subsets:
  - name: foo
    labels:
      version: foo
  - name: bar
    labels:
      version: bar
```

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[X] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastrcture

**Expected behavior**

**Steps to reproduce the bug**

Deploy demo nginx servers

```
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: demo
  labels:
    app: nginx
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: nginx
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-foo
  namespace: demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        version: foo
    spec:
      containers:
      - image: waip/demo-nginx:foo
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-bar
  namespace: demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        version: bar
    spec:
      containers:
      - image: waip/demo-nginx:bar
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
```
Then set gateway, virtual service and destination rule (see above)

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP2
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```
istioctl version --remote
client version: c1c8eeea41177137bffe7f7a4ed81d906a4cd0a7
citadel version: 1.2.0
galley version: 1.2.0
ingressgateway version: 1.2.0
pilot version: 1.2.0
policy version: 1.2.0
sidecar-injector version: 1.2.0
telemetry version: 1.2.0
```
```
k version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-gke.10", GitCommit:"f53039cc1e5295eed20969a4f10fb6ad99461e37", GitTreeState:"clean", BuildDate:"2019-06-19T20:48:40Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

Kube apply on helm template. With mTLS enabled.

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by GregHanson** [comment]
Can you provide the VirtualService for the header match case?

I can not reproduce this behavior.  Following the example from the ingress doc [here](https://istio.io/docs/tasks/traffic-management/ingress/ingress-control/#configuring-ingress-using-an-istio-gateway), and the modified VirtualService and ServiceEntry below

```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - "httpbin.example.com"
  gateways:
  - httpbin-gateway
  http:
  - match:
    - uri:
        prefix: /
      queryParams:
        version:
          exact: bar
    route:
    - destination:
        port:
          number: 8000
        host: httpbin
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: httpbin.org
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-httpbin
spec:
  hosts:
  - httpbin.org
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
EOF
```

I am able to see the desired routing behavior, with the matching query going to my local instance of httpbin and the other to the public httpbin.org service:

```
$ curl -I -HHost:httpbin.example.com http://$INGRESS_HOST:$INGRESS_PORT/status/200
HTTP/1.1 200 OK
access-control-allow-credentials: true
access-control-allow-origin: *
content-length: 0
content-type: text/html; charset=utf-8
date: Tue, 25 Jun 2019 13:09:13 GMT
referrer-policy: no-referrer-when-downgrade
server: istio-envoy
x-content-type-options: nosniff
x-frame-options: DENY
x-xss-protection: 1; mode=block
x-envoy-upstream-service-time: 61

$ curl -I -HHost:httpbin.example.com http://$INGRESS_HOST:$INGRESS_PORT/status/200?version=bar
HTTP/1.1 200 OK
server: istio-envoy
date: Tue, 25 Jun 2019 13:09:31 GMT
content-type: text/html; charset=utf-8
access-control-allow-origin: *
access-control-allow-credentials: true
content-length: 0
x-envoy-upstream-service-time: 4
```

You can also check the route configuration of your ingress gateway using istioctl.  Verify that you have two `routes` each with a `prefix` match for `/` but different `cluster` depending on whether the query params are present:
```
$ istioctl proxy-config route istio-ingressgateway-5f9b9d6c44-kwmx9.istio-system -o json
[
    {
        "name": "http.80",
        "virtualHosts": [
            {
                "name": "httpbin.example.com:80",
                "domains": [
                    "httpbin.example.com",
                    "httpbin.example.com:80"
                ],
                "routes": [
                    {
                        "match": {
                            "prefix": "/",
                            "caseSensitive": true,
                            "queryParameters": [
                                {
                                    "name": "version",
                                    "value": "bar"
                                }
                            ]
                        },
                        "route": {
                            "cluster": "outbound|8000||httpbin.default.svc.cluster.local",
                    ....
                    ....
                    },
                    {
                        "match": {
                            "prefix": "/",
                            "caseSensitive": true
                        },
                        "route": {
                            "cluster": "outbound|80||httpbin.org",

```
