### ISSUE TITLE
Fault Injection on External Https Service Not Working

### ISSUE THREAD

**Issue by mrtalley** [istio/istio#15145]
**Bug description**
I'm trying to apply fault injection rules to external services that my cluster is accessing. I'm able to successfully apply rules internally and to http routes, but it isn't working for https.

Looking at envoy logs, it looks like the mesh is recognizing requests to the https route, but I haven't been able to apply any fault injection rules to it.

I'm running istio version 1.2 and have my `outboundTrafficPolicy.mode` set to `ALLOW_ANY`.

I've been testing with https://www.google.com. Here are the yaml files that I'm trying to use.
Service Entry
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google
spec:
  hosts:
  - www.google.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL

```
Fault Injection Rule
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: google-fi
  namespace: default
spec:
  hosts:
  - www.google.com
  http:
  - route:
    - destination:
        host: www.google.com
    fault:
      abort:
        percent: 100
        httpStatus: 500
```

I wasn't able to get this to work with the "Accessing External Services" example (https://istio.io/docs/tasks/traffic-management/egress/egress-control/) or with my own project.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Apply service entry to external service (say, https://www.google.com). Then apply a fault injection virtual service. After that is done, when curling from inside a sidecar-injected pod, expect to see the specified fault, say a 500 response.

**Steps to reproduce the bug**
1. Set `outboundTrafficPolicy.mode` to `ALLOW_ALL`
2. Apply a service entry to some https host, say https://www.google.com
3. Apply a fault injection virtual service to the same host
4. From within a sidecar-injected pod, curl the host you set up the service entry for

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Output of `istioctl version --remote`
```
client version: 1.2.0
citadel version: 1.2.0
galley version: 1.2.0
galley version: 1.2.0
ingressgateway version: 1.2.0
ingressgateway version: 1.2.0
pilot version: 1.2.0
pilot version: 1.2.0
policy version: 1.2.0
policy version: 1.2.0
telemetry version: 1.2.0
telemetry version: 1.2.0
```

Output of `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:14:49Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
Cloud: Azure Kubernetes Service
OS: Windows 10 Enterprise

**Comment by hzxuzhonghu** [comment]
This is expected, as https is treated as raw tcp in envoy.

**Comment by rcaballeromx** [comment]
@mrtalley IMO the problem can also be in the value you used for `hosts` in the routing rule:
```
  - route:
    - destination:
        host: www.google.com
```
Have you tried using the name of the service entry instead?
```
  - route:
    - destination:
        host: google
```

**Comment by howardjohn** [comment]
It looks like this was resolved with no follow up

**Comment by bernardoVale** [comment]
@rcaballeromx I'm trying to do the same thing. It doesn't work. I've tried to set the name of the service entry as the destination as you suggested. Any thoughts?

**Comment by nfw-legion** [comment]
I have a similar problem here as well, ISTIO 1.4.3, I'm trying to blacklist an HTTPS-accessible URI prefix with a NOT-FOUND/404.  Using "fault.abort.httpStatus:404" for the uri-prefix-match in ISTIO VirtualServer leads from external request perspective to too-many-redirects.

**Comment by piyush0609** [comment]
@howardjohn Was there any resolution to this issue?

**Comment by howardjohn** [comment]
Yes, the user is trying to apply config for http routing but they are sending https traffic. You cannot do http level operations on tls traffic

**Comment by piyush0609** [comment]
@howardjohn Any existing tools which you recommend for injecting faults to tls traffic?

**Comment by jainbhavya65** [comment]
@howardjohn is there any way i can perform fault injection on https traffic.  i am able to perform fault inject for http traffic. i am using istio 1.6.5.

**Comment by mkurde** [comment]
We are running in the same issue as we want to test our application circuit breaking settings by returning just 500  (as example above) from google API instead of the real response. No luck so far with the Istio failure injection so far.

**Comment by khaeghar** [comment]
@howardjohn Hi, we've encountered the same problem here.

Trying to inject faults to an external service with ServiceEntry and a VirtualService via HTTPS but no way of doing it. Not with TLS nor HTTPS as protocol label in the ServiceEntry:

```
kind: ServiceEntry
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: external-svc-https
  namespace: default
spec:
  hosts:
    - google
  ports:
    - name: https
      number: 443
      protocol: TLS #or HTTPS, its the same
  location: MESH_EXTERNAL
  resolution: NONE
---------------
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: external-fi
  namespace: default
spec:
  hosts:
    - google
  http:
    - fault:
        abort:
          httpStatus: 500
      route:
        - destination:
            host: google
```

**Comment by abdollahpour** [comment]
You can do this:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: google-tls
spec:
  host: www.google.com
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
      - port:
          number: 443
        tls:
          mode: SIMPLE # initiates HTTPS when accessing httpbin.org
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google
spec:
  hosts:
    - www.google.com
  ports:
    - number: 443
      name: https
      protocol: TLS
    - number: 80
      name: http
      protocol: HTTP
  location: MESH_EXTERNAL
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: google
spec:
  hosts:
    - www.google.com
  http:
    - match:
        - port: 80
      route:
        - destination:
            host: www.google.com
            port:
              number: 443
      timeout: 100s
      retries:
        attempts: 3
        perTryTimeout: 31s
        retryOn: connect-failure,refused-stream,unavailable,cancelled,resource-exhausted,retriable-status-codes,gateway-error,500
```
