### ISSUE TITLE
Not able to deploy my custom "Gateway" and "VirtualService" chart

### ISSUE THREAD

**Issue by pramodrj07** [istio/istio#15173]
```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ubuntu-test
spec:
  selector:
    app: ubuntu-test
  servers:
    ports:
    - port: 10080
	  name: tcp 
	  protocol: TCP
    hosts:
  - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ubuntu-test-gatewayvs
spec:
  hosts:
  - "*"
  gateways:
  - ubuntu-test-gateway
  tcp:
  - match:
    - port: 10001
    route:
    - destination:
        selector: ubuntu-test
        port: 12221
EOF
```
OUTPUT : error: error parsing STDIN: error converting YAML to JSON: yaml: line 12: mapping values are not allowed in this context

**Comment by pramodrj07** [comment]
Please do let me know how to resolve this. I just followed a few of existing charts on bookinfo application to create my own chart.
Details:
1.  Service name = ubuntu-test
2. deployment name = ubuntu-test

**Comment by howardjohn** [comment]
```yaml

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ubuntu-test
spec:
  selector:
    app: ubuntu-test
  servers:
  - port:
      number: 10080
      name: tcp 
      protocol: TCP
    hosts:
    - "*"
```
