### ISSUE TITLE
istio should support tcp liveness and readiness probes  of applications

### ISSUE THREAD

**Issue by kuaikuai** [istio/istio#15178]
the part of  the yaml file as following:
```
    spec:
      containers:
      - image: hello-node:v1
        imagePullPolicy: IfNotPresent
        name: hello-node
        ports:
        - containerPort: 8080
        resources: {}
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
```
I enter into the  envoy pod,  and use an iptables rule to disable 8080 ports so that analog apps are not available. 
`iptables -A INPUT -p tcp -d 127.0.0.1 --dport 8080 -j DROP`
k8s doesn't detect the app are no longer serviceable.

**Comment by hzxuzhonghu** [comment]
For tcp probe, kubelet will try to establish a connection with podip:port by default.

With sidecar injected, the kubelet can still establish a connection with envoy , so the probe still thinks it is healthy. Tcp connection  with app will be established until there is real data transport.

**Comment by kuaikuai** [comment]
@hzxuzhonghu,
I have two ideas：
1. change proxy_init, and a iptables rule, let kubelet connect the app directly.
or
2. change istioctl kube-inject & proxy_agent & pod spec, use proxy_agent detect the app.
    add annotations like: sidecar.istio.io/rewriteAppHTTPProbers: "true"

**Comment by hzxuzhonghu** [comment]
I think 2 is feasible.  
If you would openup a pr i would be glad to review, though personally i think k8s tcp probe does not make much sense.

**Comment by bappr** [comment]
@hzxuzhonghu  
> though personally i think k8s tcp probe does not make much sense.

Can u explain more about that plz?
I am fully using tcp probes cause my apps are not customisable. And it's a nice generic way to test the readiness and liveness of your servers.
Therefore, I am getting hit by this issue.

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - image: nginx
        livenessProbe:
          tcpSocket:
            port: 8080
        name: main
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          tcpSocket:
            port: 8080
```

Very easy to reproduce.
We should reopen.
