### ISSUE TITLE
Sending requests to Ingress Gateway immediately after creation can cause long-term problems

### ISSUE THREAD

**Issue by jaygorrell** [istio/istio#15235]
*** **Update**: Replacing the original issue with the latest info. There was some irrelevant data that added confusion before this was more understood ***

**Bug description**
If I curl an ingress gateway with `-v`, I can see that it responds on one of the three ELB IPs... the other two just hang.

I'm pretty certain I've narrowed this down to happening when sending traffic to a `Gateway`/`VirtualService` immediately upon being created, from an otherwise unused Ingress Gateway.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Ingress Gateway responds consistently and does not get _hung up_ in certain scenarios.

**Steps to reproduce the bug**
I don't fully understand what's happening here, but to the best of my knowledge, these steps work nearly every time.
1. Have an environment where Ingress Gateway is set up but not used.
2. Make sure the ELB is up and healthy for the Ingress Gateway.
3. Create a simple Gateway/VirtualService manifest (These must be applied at the same time -- I cannot reproduce the issue otherwise.)
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: demo-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
      - "*"
      port:
        number: 80
        name: http
        protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: demo-chat-service
spec:
  hosts:
    - "*"
  gateways:
    - demo-gateway
  http:
    - match:
      - uri:
          prefix: /my-service
      rewrite:
        uri: /
      route:
        - destination:
            port:
              number: 80
            host: my-service
```
4. Apply the manifests and immediately start hitting the ingress-gateway ELB with `curl -v <ELB>/my-service`
5. You should see that at least one of the IPs reported back from the ELB is likely failing consistently while the other two work.
6. If this doesn't work, `kubectl delete` the manifests and try again from step 4.

Once it happens, it may take 10-15 minutes (or more) before that IP begins to work. It's also worth noting that it seems the ELB shows a very large number of surge queue items and oftentimes a large number of backend service errors.

To see how this normally behaves, wait about 30 seconds between applying the manifests and sending a `curl` ... you should never hit the hanging issue in that situation.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio: 1.0.2 originally; currently 1.1.9
k8s: 1.11.8

**How was Istio installed?**
Helm default + mTLS

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS / Kops
