### ISSUE TITLE
Customize the image and tag of Istio components

### ISSUE THREAD

**Issue by costinm** [istio/istio#15264]
We need a documented and tested mechanism to customize the image and tag for
all Istio components. 

Kustomize should use the https://github.com/kubernetes-sigs/kustomize/blob/master/docs/fields.md#images

For Helm we should try to use a similar syntax in values.yaml. 
This will deprecate or extend the current use, which is (example):
```
pilot:
  image: istio-pilot - combined with global.hub and global.tag to create the full image
or 
  image: repo/pilot:TAG 
```

The kustomize style is:
```
images:
- name: istio-pilot
  newName: my-registry/my-pilot
  newTag: v1
```

In particular, it means that use can easily specify the TAG for each individual component,
while also allowing the repo+image to be customized while leaving the TAG in place. 

Some discussion in:
https://github.com/istio/istio/pull/14815
