### ISSUE TITLE
Make Envoy's per connection buffer limit configurable

### ISSUE THREAD

**Issue by gokhansengun** [istio/istio#15260]
This is a followup from #13719. As @robertpanzer shown there, Envoy allows to set `per_connection_buffer_limit_bytes` per listener as given in below example:

```
static_resources:
  listeners:
  - name: main
    per_connection_buffer_limit_bytes: 2097152
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 8888
    filter_chains:
    - filters:
```

This limit appears to be 1MB and it cause Envoy to generate an HTTP 500 when an EnvoyFilter is added to the chain and the Filter has to make a buffered read due to its business requirements. When the HTTP response is bigger than 1MB, Envoy emits HTTP 500.

It would be great if this limit is made configurable over Istio.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Comment by vergnes** [comment]
We have a use case where we'd like to control the HTTP2 window size as the default 256 MB are way too big. Envoy offers several knobs to control the buffers: https://www.envoyproxy.io/docs/envoy/latest/faq/configure_flow_control. It'd be nice to expose them in istio.

**Comment by hzxuzhonghu** [comment]
The current resolution is to use `envoyfilter`, reopen if you feel this is a must feature

**Comment by ethicalaakash** [comment]
@hzxuzhonghu how can I achieve this with `envoyfilter`, can you please share an example.

**Comment by vergnes** [comment]
@ethicalaakash 
You can find examples here: https://github.com/istio/istio/wiki/EnvoyFilter-Samples
The full reference documentation is here: https://istio.io/docs/reference/config/networking/envoy-filter/

**Comment by ethicalaakash** [comment]
Thanks @vergnes 
following `envoyfilter` can be used to update the `per_connection_buffer_limit_bytes` in Istio.
The listeners generated by Pilot are typically named as IP_PORT, for me port was 8080, change this accordingly.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: connection
spec:
  configPatches:
  - applyTo: LISTENER
    ListenerMatch: 0.0.0.0_8080
    patch:
      operation: MERGE
      value:
        per_connection_buffer_limit_bytes: 100000000 #100MB
```
