### ISSUE TITLE
httpsRedirect option for 308

### ISSUE THREAD

**Issue by dwalton76** [istio/istio#15292]
**Bug description**
httpsRedirect always sends a 301.  If you are doing a POST the 301 will force most clients to change from POST to GET per https://tools.ietf.org/html/rfc7231#section-6.4.2
```
      Note: For historical reasons, a user agent MAY change the request
      method from POST to GET for the subsequent request.  If this
      behavior is undesired, the 307 (Temporary Redirect) status code
      can be used instead.
```
curl, python's request library, many browsers, etc all follow this behavior.

We need a way for istio to send a 308 redirect instead of a 301. The 308 tells the client to not change the request method (if you start with POST, stay with POST).

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Expected behavior**
For istio to send a 308 redirect

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
dwalton@laptop:kube-config$ istioctl version --remote
version.BuildInfo{Version:"1.1.3", GitRevision:"d19179769183541c5db473ae8d062ca899abb3be", User:"root", Host:"fbd493e1-5d72-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.2-56-gd191797"}
Error: error execing into istio-citadel-5bbbc98c6d-vwpxt citadel container: command terminated with exit code 255
dwalton@laptop:kube-config$ 

dwalton@laptop:kube-config$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:41:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
dwalton@laptop:kube-config$ 
```
**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
azure

**Comment by ckcd** [comment]
I'm working on this issue and I have some idea: I think add a params in `virtualservice` may be a good method, for example:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ratings-route
spec:
  hosts:
  - ratings.prod.svc.cluster.local
  http:
  - match:
    - uri:
        exact: /v1/getProductRatings
    redirect:
      uri: /v1/bookRatings
      authority: newratings.default.svc.cluster.local
      usePermanentRedirect: true
  ...
```
use `usePermanentRedirect: true` to indicate that using `308` rather `301`.

@dwalton76 @howardjohn ideas welcome ~
