### ISSUE TITLE
How to make domain redirection

### ISSUE THREAD

**Issue by xiaozhongliu** [istio/istio#15313]
I need to make a 301 redirection from http(s)://fake.com to http(s)://www.fake.com.
I don't see relevant doc on this, also redirection in virtual service does not work.

**Comment by jsPlachetka** [comment]
Have you used [virtual service wtih destination rule](https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/)? Though it seems to be more common for a 301 redirect.
And what about a simple [routing rule](https://istio-releases.github.io/v0.1/docs/reference/config/traffic-rules/routing-rules.html)

**Comment by xiaozhongliu** [comment]
@jsPlachetka Yes I need a 301, I fixed my original post.
Is it ok to create a dedicated virtual service for 301 redirection, which only handles domain without www?
Also I do not see any sample on domain redirection, could you help to share a quick and dirty sample?

**Comment by jsPlachetka** [comment]
A 301 redirect is one of the things virtual service is for as far as I understood it.
Is [this](https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#HTTPRedirect) already helping you? (unfortunatelly don't have the time right now even for a quick example)

**Comment by xiaozhongliu** [comment]
> A 301 redirect is one of the things virtual service is for as far as I understood it.
> Is [this](https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#HTTPRedirect) already helping you? (unfortunatelly don't have the time right now even for a quick example)

No no no, I think what I describe is quite clear. I need a ***domain redirection***, not a path redirection, the paths won't change.

**Comment by esnible** [comment]
Do this:

```
cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: www-redir
spec:
  hosts:
  - httpbin.org
  http:
  - match:
    - uri:
        prefix: /
    redirect:
      authority: www.httpbin.org
EOF
```

To test, start an interactive container and do `curl --location httpbin.org/headers`.  Without that rule you will see the Host set to httpbin.org, with that rule you will see the Host set to www.httpbin.org.
