### ISSUE TITLE
Pods injected with istio_cni.enabled=true cannot validate against any PSPs on GKE

### ISSUE THREAD

**Issue by samcgardner** [istio/istio#15326]
**Bug description**

If the CNI plugin is installed and istio is configured with `istio_cni.enabled: true` then injected pods cannot validate against any PSP on GKE, giving an error as follows:

```
  - lastTransitionTime: "2019-07-02T17:22:10Z"
    lastUpdateTime: "2019-07-02T17:22:10Z"
    message: 'pods "end-react-deployment-7b8cb675fd-99szm" is forbidden: unable to
      validate against any pod security policy: []'
    reason: FailedCreate
    status: "True"
    type: ReplicaFailure
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Expected behaviour**

Injected pods should either validate against a PSP or fail with a meaningful error message.

**Steps to reproduce the bug**

1. Install istio and istio-cni on GKE version 1.13.7-gke.8
1a. Configure istio with `istio_cni.enabled: true`
2. Enable auto injection on a namespace
3. Install the following PSP and ClusterroleBinding

```
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
    apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: docker/default
    seccomp.security.alpha.kubernetes.io/defaultProfileName: docker/default
  name: restricted
spec:
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  fsGroup:
    ranges:
    - max: 65535
      min: 0
    rule: MustRunAs
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65535
      min: 0
    rule: MustRunAs
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  - persistentVolumeClaim
```

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
  name: psp:restricted
rules:
- apiGroups:
  - extensions
  resourceNames:
  - restricted
  resources:
  - podsecuritypolicies
  verbs:
  - use
```

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: psp:restricted
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:restricted
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

istio: 1.2.2
kubectl:
```Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:12:47Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.8", GitCommit:"7d3d6f113e933ed1b44b78dff4baf649258415e5", GitTreeState:"clean", BuildDate:"2019-06-19T16:37:16Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

Helm 

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE, cOS

**Dump**
[istio-dump.tar.gz](https://github.com/istio/istio/files/3354607/istio-dump.tar.gz)
