### ISSUE TITLE
The range of FaultAbort.http_status in envoy is different from that of istio

### ISSUE THREAD

**Issue by dzdx** [istio/istio#15355]
**Bug description**
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ratings-route
spec:
  hosts:
  - ratings.prod.svc.cluster.local
  http:
  - route:
    - destination:
        host: ratings.prod.svc.cluster.local
        subset: v1
    fault:
      abort:
        percentage:
          value: 0.1
        httpStatus: 100
```
this virtualservice will cause envoy route config update failed:
```
[2019-07-04 08:28:48.868][16][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:77] gRPC config for type.googleapis.com/envoy.
api.v2.RouteConfiguration rejected: Proto constraint validation failed (HTTPFaultValidationError.Abort: ["embedded message failed validation"] | caused by FaultAbortValidationError.HttpStatus: ["value must be inside range [" 'È' ", " 'ɘ'
")"]): abort {
  http_status: 100
  percentage {
    numerator: 110000
    denominator: MILLION
  }
}

```

**Affected product area (please put an X in all that apply)**

[ x ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

The range of FaultAbort.http_status in envoy is `200~600`, but istio is `0~600`
https://github.com/envoyproxy/envoy/blob/805683f835bd63e4b7b9d89059aa0d3783924a93/api/envoy/config/filter/http/fault/v2/fault.proto#L28

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
