### ISSUE TITLE
Sidecar graceful shutdown support

### ISSUE THREAD

**Issue by dozer47528** [istio/istio#15364]
We have a `DaemonSet ` and exposed to AWS load balancer with `hostPort`.

Before shutdown our Pods, we will call AWS API to deregister it from the load balancer.

We made a container for that: [aws-elb-hook-docker](https://github.com/AminoApps/aws-elb-hook-docker)

It works well when we deploy it without an istio sidecar.

But after using istio sidecar, the sidecar shutdown before our container, and our container cannot contact with other services without the sidecar.

How about adding the preStop support for istio sidecar?

**Describe alternatives you've considered**

I added this part to the `injection-template.yaml` and works for me.

```yaml
{{- if (ne (annotation .ObjectMeta `sidecar.istio.io/preStopGracePeriod` "") "") }}
  lifecycle:
    preStop:
      exec:
        command: ["sleep","{{ annotation .ObjectMeta `sidecar.istio.io/preStopGracePeriod` "0"}}"]
{{- end }}
```

**Affected product area (please put an X in all that apply)**

[x] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
