### ISSUE TITLE
Policy not respecting excluded_paths and included_paths

### ISSUE THREAD

**Issue by jnsvd** [istio/istio#15360]
**Bug description**

I've created a policy as follows:

```
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  creationTimestamp: 2019-07-04T12:51:31Z
  generation: 1
  name: <REDACTED>
  namespace: <REDACTED>
  resourceVersion: "14781396"
  selfLink: <REDACTED>
  uid: <REDACTED>
spec:
  origins:
  - jwt:
      audiences:
      - <REDACTED>
      issuer: <REDACTED>
      jwksUri: <REDACTED>
      trigger_rules:
      - excluded_paths:
        - exact: /health
        - exact: /credit/simulate
        - exact: /credit/category
      - included_paths:
        - prefix: /credit/
  principalBinding: USE_ORIGIN
  targets:
  - name: <REDACTED>
```

With this policy in place, I'm getting a 401 Unauthorized when calling `/credit/category`. Making a call to `/health` results in a HTTP 200 response. It seems that paths in `excluded_paths` are not treated correctly if it also occurs in `included_paths`.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ X] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ X] Policies and Telemetry
[ X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

No 401 Unauthorized on endpoint `/credit/category`.

**Steps to reproduce the bug**

Install a similar policy as above for some endpoint, and verify that `included_paths` and `excluded_paths` don't seem to work as documented.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

Istio v1.1.0
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:30:48Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

Using the Helm chart

**Environment where bug was observed (cloud vendor, OS, etc)**

Azure Kubernetes Service

**Comment by jnsvd** [comment]
This issue was caused by an incorrect `-`.

```
trigger_rules:
      - excluded_paths:
        - exact: /health
        - exact: /credit/simulate
        - exact: /credit/category
      - included_paths:
        - prefix: /credit/
```

needs to be 

```
trigger_rules:
      - excluded_paths:
        - exact: /health
        - exact: /credit/simulate
        - exact: /credit/category
        included_paths:
        - prefix: /credit/
```
