### ISSUE TITLE
inter pod communication using ip How to achieve this  in istio?

### ISSUE THREAD

**Issue by anannaya** [istio/istio#15367]
I have multiple replicas of pod which is running in deployment. There is requirement where pods need to communicate each other using ip address, How can this achieved ? I have followed below thread which didnt work for me.

https://discuss.istio.io/t/question-enable-in-mesh-pod-to-communicate-with-another-in-mesh-pod-using-podip-mtls-enabled/1077

**Comment by howardjohn** [comment]
/assign @philrud 

I think he is working on this/similar issue

**Comment by anannaya** [comment]
@philrud  Do you any way to make it work?

**Comment by hzxuzhonghu** [comment]
>There is requirement where pods need to communicate each other using ip address,

How do you get the podip? As pod ip will may change, it is not suggested to use directly.  Please try to use headless service.

**Comment by anannaya** [comment]
@hzxuzhonghu  We  can get the PODIP from the some service discovery or some kafka catalog.
I just need a way to make it work. Is it possible currently in istio?

**Comment by hzxuzhonghu** [comment]
This is something like statefulset support, currently, you need to create ServiceEntry i think.

**Comment by anannaya** [comment]
> This is something like statefulset support, currently, you need to create ServiceEntry i think.
@hzxuzhonghu  Do you have any example?

**Comment by hzxuzhonghu** [comment]
FYI https://github.com/istio/istio/issues/10659

**Comment by anannaya** [comment]
I have tried these But didn't work for me.
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: ccbu-example-chart-comm
spec:
  hosts:
  - 10.6.177.243
  - 10.6.159.123
  addresses:
  - 10.6.0.0/11
  ports:
  - number: 8080
    name: nodejs-port
    protocol: HTTP
  - number: 8080
    name: nodejs-port-tls
    protocol: TLS
  location: MESH_INTERNAL
  resolution: STATIC
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: pod1
spec:
  host: "10.6.177.243"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: pod2
spec:
  host: "10.6.159.123"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```
