### ISSUE TITLE
gateways from meshNetworks are not picked up when using ServiceEntries

### ISSUE THREAD

**Issue by chaudyg** [istio/istio#15379]
**Bug description**
Gateways from meshNetworks are not picked up when using ServiceEntries.

I would like to route every request from a specific CIDR block via a remote gateway. For example, route every request to *.mycompany.local (cidr 10.123.0.0/24) to a remote gateway 1.2.3.4:443 inside the mesh.

Note than not everything undert *.mycompany.local will be routed via the gateway, only whatever resolves within the cird 10.123.0.0/24. For example foo.mycompany.local (10.123.0.1) should be routed via the gateway but bar.mycompany.local (10.456.0.1) should not.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Requests to *.mycompany.io should be routed via the gateway specified  in the meshNetworks settings when the resolved IP matches the given CIDR block.

**Steps to reproduce the bug**

1. I created the following entries:

```yaml
---
# values.yaml
global:
  meshNetworks:
    remote:
      endpoints:
      - fromCidr: "10.123.0.0/24"
      gateways:
      - address: 1.2.3.4
        port: 443
---
# se.yaml
# Here i am creating a foo.mycomany.local with hardcoded endpoints. In real life I am creating
# *.mycompany.local without specifying any endpoints (DNS resolution). The result is the same.
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: internal
  namespace: default
spec:
  addresses: []
  hosts:
  - foo.mycompany.local
  location: MESH_INTERNAL
  endpoints:
  - address: 10.123.0.1
     ports:
       http: 443
  resolution: DNS
  ports:
  - number: 80
    name: http
    protocol: HTTP
```

2. Create a curl pod

`kubectl run -ti --image tutum/curl --generator=run-pod/v1 curl --rm`

3. Check the proxy endpoints

```
  istioctl pc endpoints curl | grep mycompany
  > 10.123.0.1:443         HEALTHY     outbound|80||*.mycompany.local
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

* Istio 1.2.2 

```
client version: 1.2.2
citadel version: 1.2.2
galley version: 1.2.2
ingressgateway version: 1.2.2
pilot version: 1.2.2
policy version: 1.2.2
sidecar-injector version: 1.2.2
telemetry version: 1.2.2
```

* kops cluster with kubernetes 1.12.9

**How was Istio installed?**

* Using helm

**Environment where bug was observed (cloud vendor, OS, etc)**

* kops cluster
Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
