### ISSUE TITLE
Periodic hangs when calling external HTTP services

### ISSUE THREAD

**Issue by toothbrush** [istio/istio#15378]
Hello!  I've been struggling with this for quite a bit, and would like to ask for some input, please.  My apologies if it's PEBKAC.

### Context

Installed Istio 1.2.2 on Amazon EKS cluster (2 x t3.large nodes) in ap-southeast-2.

### Bug description

When deploying a Debian pod to the cluster in default namespace (sidecar injection enabled in default namespace), then running `apt update && apt install dnsutils curl -y` i observe that a few packages download, then apt hangs on `Waiting for headers` for exactly 2 minutes, then continues downloading.  It doesn't happen every time, but frequently enough that i wanted to dig into it.

Interestingly, a similar thing happens when running these steps in an Ubuntu container, but the hang is 30 seconds...

**Affected product area (please put an X in all that apply)**

[x] Networking

**Expected behavior**

Network connections to external services are fast and stable, without periodic hanging.  I brought up a fresh EKS cluster without Istio, and the issue does not occur.

**Steps to reproduce the bug**

1. Bring up EKS cluster.  Here's my configuration:

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: non-production
  region: ap-southeast-2
  version: "1.13"
  tags:
    Environment: non-production

vpc:
  id: "vpc-041beffbcf01d431d"
  subnets:
    private:
      ap-southeast-2a:
        id: "subnet-0f663a10ec7e96d99"
      ap-southeast-2b:
        id: "subnet-03a31cc07e2fc5b6f"
      ap-southeast-2c:
        id: "subnet-04a6efab35bff2aee"
    public:
      ap-southeast-2a:
        id: "subnet-09c33f6e28646b3ea"
      ap-southeast-2b:
        id: "subnet-03a547ad2ab26a93a"
      ap-southeast-2c:
        id: "subnet-0faca9aba4137aca1"

nodeGroups:
  - name: blue
    instanceType: t3.large
    desiredCapacity: 2
    minSize: 2
    maxSize: 2
    ami: auto
```

Install Istio.  Here is my Helm override file:

```yaml
gateways:
  istio-ingressgateway:
    sds:
      enabled: true
    serviceAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    type: LoadBalancer
    ports:
      - name: https
        nodePort: 31390
        port: 443

certmanager:
  # This value only ends up in the ClusterIssuer objects, which we
  # won't use anyway.
  email: mailbox@donotuseexample.com
  enabled: true
  tag: v0.8.1

global:
  controlPlaneSecurityEnabled: false
  proxy:
    accessLogFile: "/dev/stdout"

  mtls:
    # Default setting for service-to-service mtls. Can be set explicitly using
    # destination rules or service annotations.
    enabled: true

  sds:
    enabled: true
    udsPath: "unix:/var/run/sds/uds_path"
    useNormalJwt: true

nodeagent:
  enabled: true
  image: node-agent-k8s
  env:
    CA_PROVIDER: "Citadel"
    CA_ADDR: "istio-citadel:8060"
    VALID_TOKEN: true

sidecarInjectorWebhook:
  # If true, webhook or istioctl injector will rewrite PodSpec for liveness
  # health check to redirect request to sidecar. This makes liveness check work
  # even when mTLS is enabled.
  rewriteAppHTTPProbe: true

kiali:
  enabled: true
  createDemoSecret: true
  dashboard:
    grafanaURL: http://localhost:3000

grafana:
  enabled: true

tracing:
  enabled: true

pilot:
  traceSampling: 100.0
```

Now start a Debian container and install some packages.

```ShellSession
$ kubectl run  -it debian2 --image=debian  /bin/bash
root@debian2-56c6bbbf4d-wqhwt:/# apt update && apt install dnsutils curl -y
Get:1 http://security-cdn.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Get:2 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 Packages [499 kB]
Ign:3 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Get:4 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:6 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages [27.2 kB]
Get:5 http://cdn-fastly.deb.debian.org/debian stretch Release [118 kB]
Get:7 http://cdn-fastly.deb.debian.org/debian stretch Release.gpg [2434 B]
Get:8 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 Packages [7082 kB]
Fetched 7914 kB in 2s (3739 kB/s)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  bind9-host ca-certificates geoip-database krb5-locales libbind9-140 libcurl3 libdns162 libffi6 libgeoip1 libgmp10
  libgnutls30 libgssapi-krb5-2 libhogweed4 libicu57 libidn2-0 libisc160 libisccc140 libisccfg140 libk5crypto3 libkeyutils1
  libkrb5-3 libkrb5support0 libldap-2.4-2 libldap-common liblwres141 libnghttp2-14 libp11-kit0 libpsl5 librtmp1 libsasl2-2
  libsasl2-modules libsasl2-modules-db libssh2-1 libssl1.0.2 libssl1.1 libtasn1-6 libunistring0 libxml2 openssl publicsuffix
  sgml-base xml-core
Suggested packages:
  rblcheck geoip-bin gnutls-bin krb5-doc krb5-user libsasl2-modules-gssapi-mit | libsasl2-modules-gssapi-heimdal
  libsasl2-modules-ldap libsasl2-modules-otp libsasl2-modules-sql sgml-base-doc debhelper
The following NEW packages will be installed:
  bind9-host ca-certificates curl dnsutils geoip-database krb5-locales libbind9-140 libcurl3 libdns162 libffi6 libgeoip1
  libgmp10 libgnutls30 libgssapi-krb5-2 libhogweed4 libicu57 libidn2-0 libisc160 libisccc140 libisccfg140 libk5crypto3
  libkeyutils1 libkrb5-3 libkrb5support0 libldap-2.4-2 libldap-common liblwres141 libnghttp2-14 libp11-kit0 libpsl5 librtmp1
  libsasl2-2 libsasl2-modules libsasl2-modules-db libssh2-1 libssl1.0.2 libssl1.1 libtasn1-6 libunistring0 libxml2 openssl
  publicsuffix sgml-base xml-core
0 upgraded, 44 newly installed, 0 to remove and 0 not upgraded.
Need to get 21.4 MB of archives.
After this operation, 67.7 MB of additional disk space will be used.
.....elided many similar lines........
Get:26 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libidn2-0 amd64 0.16-1+deb9u1 [60.7 kB]
Get:27 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libnghttp2-14 amd64 1.18.1-1 [79.1 kB]
Get:28 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libpsl5 amd64 0.17.0-3 [41.8 kB]
69% [Waiting for headers] [Waiting for headers]                                                                               
```

It hangs like that for almost exactly 2 minutes (always the same when i reproduce the issue), and then manages to continue and install fine.  See the attached `istio-proxy` log and note the timestamps: there's a gap precisely between 05:11:55.275Z and 05:13:51.266Z.

```
[2019-07-08T05:11:55.275Z] "GET /debian/pool/main/libp/libpsl/libpsl5_0.17.0-3_amd64.deb HTTP/1.1" 200 - "-" "-" 0 41778 1 1 "-" "Debian APT-HTTP/1.3 (1.4.9)" "3ea9aed6-f670-9ead-b57d-c992fd4a0215" "cdn-fastly.deb.debian.org" "151.101.28.204:80" PassthroughCluster - 151.101.28.204:80 192.168.6.36:60806 -
[2019-07-08T05:13:51.266Z] "GET /debian-security/pool/updates/main/b/bind9/libdns162_9.10.3.dfsg.P4-12.3%2bdeb9u5_amd64.deb HTTP/1.1" 302 - "-" "-" 0 372 437 437 "-" "Debian APT-HTTP/1.3 (1.4.9)" "b4a2c2e4-5cc0-900e-aa34-53fcb5f6a974" "security.debian.org" "149.20.4.14:80" PassthroughCluster - 149.20.4.14:80 192.168.6.36:59140 -
```

[problem-log.txt](https://github.com/istio/istio/files/3366760/problem-log.txt)

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```ShellSession
$ ~/istio-1.2.2/bin/istioctl version --remote
client version: 1.2.2
citadel version: 1.2.2
galley version: 1.2.2
ingressgateway version: 1.2.2
nodeagent version: 
nodeagent version: 
pilot version: 1.2.2
policy version: 1.2.2
sidecar-injector version: 1.2.2
telemetry version: 1.2.2
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:52:26Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-eks-c57ff8", GitCommit:"c57ff8e35590932c652433fab07988da79265d5b", GitTreeState:"clean", BuildDate:"2019-06-07T20:43:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

Using `helm template`.  I'd be keen to get pointers on how to dig in further — i'm not sure where to look, now...

**Environment where bug was observed (cloud vendor, OS, etc)**

On EKS, Kubernetes 1.13.
