### ISSUE TITLE
Missing yaml separator for yaml manifests generated by istio-operator

### ISSUE THREAD

**Issue by morvencao** [istio/istio#15370]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

Currently if you generate the yaml manifests with default profile:

```
root@mcdev1:~/go/src/istio.io/operator/cmd# pwd
/root/go/src/istio.io/operator/cmd
root@mcdev1:~/go/src/istio.io/operator/cmd# go build -o istio-operator
root@mcdev1:~/go/src/istio.io/operator/cmd# ./istio-operator manifest > istio.yaml
```

You will find the yaml is invalid because there are some missing yaml separator:

```
# kubectl apply -f istio.yaml.old
error: error validating "istio.yaml.old": error validating data: [ValidationError(ClusterRole): unknown field "roleRef" in io.k8s.api.rbac.v1.ClusterRole, ValidationError(ClusterRole): unknown field "spec" in io.k8s.api.rbac.v1.ClusterRole, ValidationError(ClusterRole): unknown field "subjects" in io.k8s.api.rbac.v1.ClusterRole]; if you choose to ignore these errors, turn validation off with --validate=false
```

Check the generated yaml manifests:
```
...
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - s390x
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istio-nodeagent-istio-system
  labels:
    app: istio-nodeagent
    release: istio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-nodeagent-istio-system
subjects:
  - kind: ServiceAccount
    name: istio-nodeagent-service-account
    namespace: istio-system
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-nodeagent-istio-system
  labels:
    app: istio-nodeagent
    release: istio
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
...
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
