### ISSUE TITLE
Kiali doesn't report GRPC errors

### ISSUE THREAD

**Issue by toothbrush** [istio/istio#15400]
# Bug description

As with my other reports, this might be PEBKAC.  However, there is at the very least a gap in my understanding.  Thank you for indulging me!

## Context

I'd like to deploy a set of my services (which use GRPC to communicate) to an Istio-enabled Kubernetes cluster (i'm currently trialling EKS with 1.13) and subsequently have a way to be alerted of connectivity issues between the services.

I created a minimal example of the problem.  Let's say i deploy [grpc-hello-world](https://github.com/enm10k/grpc-hello-world) as follows:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-service
  namespace: default
  labels:
    app: hello-world-service
    env: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-service
      env: development
  template:
    metadata:
      labels:
        app: hello-world-service
        version: latest
        env: development
    spec:
      containers:
      - name: hello-world-service
        image: "enm10k/grpc-hello-world"
        command: ["greeter_server"]
        env:
          - name: PORT
            value: "50051"
        ports:
        - containerPort: 50051
        readinessProbe:
          exec:
            command:
            - "true"
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - "true"
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: default
spec:
  ports:
    - name: grpc-hello-world
      port: 50051
      targetPort: 50051
  selector:
    app: hello-world-service
    env: development
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway-hello-world
  namespace: default
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - hosts:
    - "hello-world.mydomain.com"
    port:
      name: grpc-50051-hello-world-service-platform-dev # this must be unique
      number: 50051
      protocol: grpc # https://github.com/istio/istio/issues/7843#issuecomment-413622721
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-world-service-dev
  namespace: default
spec:
  hosts:
  - "hello-world.mydomain.com"
  gateways:
  - my-gateway-hello-world
  http:
  - route:
    - destination:
        host: hello-world-service
        port:
          number: 50051
```

This works great and i can exercise the service from my dev laptop (again, this is running in AWS) by something like this:

```ShellSession
$ docker run --env ADDRESS=hello-world.scratchpro.link:50051 enm10k/grpc-hello-world sh -c "while true ; do greeter_client; done"
2019/07/09 06:22:39 Greeting: Hello world
....
```
Great!  I can also see the traffic coming in on Kiali.

My problem arises when i introduce an error in my deployment.  Let's say i change `.spec.http.route.destination.host` to `hello-world-service-faux-nonexistent`.  This causes my GRPC test client to start spewing errors:

```
2019/07/09 06:22:45 could not greet: rpc error: code = 14 desc = 
```

However, in Kiali, there's no sign of the error!  It just looks like traffic dropped off, harmlessly.

![Screen Shot 2019-07-09 at 16 24 10](https://user-images.githubusercontent.com/423357/60864513-23f37600-a267-11e9-999b-942ae3ee16cb.png)

Note where i've marked in red, the drop off in traffic.  This is where i deployed a pointer to a nonexistent service.  The behaviour is same if i cause the pod to be unhealthy, e.g., if i make a mistake in the pod's `.spec.containers.command` attribute.

Is this a deep misunderstanding on my part?  Because if this is right, there's no way to detect my app is (for example) in a crash loop and not serving traffic.  It'd have to be up and healthy and serving an error response to show up in Kiali.

**Affected product area (please put an X in all that apply)**

[x] Policies and Telemetry
[x] User Experience

**Expected behavior**

The error percentage should go up for this VirtualService.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

Istio 1.2.2 from `helm template` on EKS v1.13 in `ap-southeast-2`.

**Comment by toothbrush** [comment]
For anybody else that is struggling with this: a thing i just learned is that `response_flags` that Envoy throws are significant.  For example using GRPC, you won't get HTTP codes other than 200, if it's failing at the TCP connection level.  What you _do_ get, is flags like `URX` or `UF`.  The docs are hard to find, but they're there: https://www.envoyproxy.io/docs/envoy/latest/configuration/access_log.  Hope that this helps somebody else have a better day!  I still think this issue is real though, and probably the docs for Kiali could be updated to reflect how to visualise these sorts of errors better.  If i find docs which already tell you how to do this, i'll report back and close the issue. 🎉

**Comment by jmazzitelli** [comment]
The Kiali side summary panel should be showing these gRPC response codes... IIRC it was part of this PR: https://github.com/kiali/kiali-ui/pull/1062

The animated gif only shows HTTP response flags, but I believe when you look at a gRPC edge, it should be showing you the gRPC response codes in there.

**Comment by jmazzitelli** [comment]
If you look at the corresponding server-side PR https://github.com/kiali/kiali/pull/913/files it added the ability to get the response_flags from prometheus, which in turn should be displayed in the UI (again, that happens in the side summary panel IIRC).

**Comment by toothbrush** [comment]
Thanks for the reply!  Unfortunately, in the situation i sketch (pointing at spurious service), no errors are shown, just a plummeting of traffic.

**Comment by toothbrush** [comment]
I've just tried something different — deploying an app that doesn't listen on the correct port.  My thinking was that perhaps i couldn't see my non-existent service on the Kiali graph.  However, when the service is correctly defined but the pod is misbehaving, i still see a green GRPC edge.  As an example i've deployed this pod.  The sidebar does show response flags, which signify an error, but they look very benign in the Kiali console.  Maybe i should file a report there...

![image](https://user-images.githubusercontent.com/423357/61019076-3f33c200-a3dc-11e9-89ae-f0bac3c7fc13.png)

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-service
  namespace: default
  labels:
    app: hello-world-service
    env: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-service
      env: development
  template:
    metadata:
      labels:
        app: hello-world-service
        version: latest
        env: development
    spec:
      containers:
      - name: hello-world-service
        image: debian
        command: ["bash", "-c", "while true; do echo hullo; sleep 30; done"]
        env:
          - name: PORT
            value: "50051"
        ports:
        - containerPort: 50051
        readinessProbe:
          exec:
            command:
            - "true"
        livenessProbe:
          exec:
            command:
            - "true"
```
