### ISSUE TITLE
Redis Connectivity Issues in 1.2.2

### ISSUE THREAD

**Issue by crhuber** [istio/istio#15429]
**Bug description**

After upgrading the control plane from Istio v.1.2.0 to 1.2.2 we started getting the following error message on pods that have Istio sidecar running and connect to a redis instance outside the mesh

```
 [RedisException]
 read error on connection to redis.mydomain.io:6379
```

After checking the sidecar logs on affected pods, we found the following entries

```
[2019-07-10 10:10:09.297][20][warning][config] [external/envoy/source/common/config/grpc_mux_subscription_impl.cc:73] gRPC config for type.googleapis.com/envoy.api.v2.Cluster rejected: Error adding/updating cluster(s) outbound|6379||serviceA.ns.svc.cluster.local: cluster: cluster type 'original_dst' may only be used with LB type 'original_dst_lb'

```

ServiceA has the following kube config:
 
```
apiVersion: v1
kind: Service
metadata:
  name: serviceA
  namespace: ns
spec:
  clusterIP: None
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: redis
  selector:
    app: redis
    release: serviceA
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
_Note: the port name is: `redis` and there is no `ClusterIP` since its a headless service._

At this point all pods inside the mesh that made outbound calls to our external Redis instance, could not communicate until we rolled back to Istio 1.2.0 

As a side note, I noticed other people having similar issues with redis headless services in Dicuss
https://discuss.istio.io/t/istio-ingress-gateway-always-stale/3018/2

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Redis communication happens properly

**Steps to reproduce the bug**

Upgrade the control plane from Istio v.1.2.0 to 1.2.2 

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

client version: 1.2.2
citadel version: 1.2.2
galley version: 1.2.2
ingressgateway version: 1.2.2
pilot version: 1.2.2
policy version: 1.2.2
sidecar-injector version: 1.2.2
telemetry version: 1.2.2

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-eks-c57ff8", GitCommit:"c57ff8e35590932c652433fab07988da79265d5b", GitTreeState:"clean", BuildDate:"2019-06-07T20:43:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Helm Chart

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS EKS

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by tadeucruz** [comment]
Hi, 

I have the similar problem using 1.2.2 in 1.20 everything works fine 

**The error:**

`org.springframework.data.redis.RedisSystemException: Redis exception; nested exception is io.lettuce.core.RedisException: java.io.IOException: Connection reset by peer`

**kube config:**

```
apiVersion: v1
kind: Service
metadata:
  name: redis-sso
spec:
  ports:
  - port: 6379
    name: redis
  selector:
    app: redis-sso
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-sso
spec:
  selector:
    matchLabels:
      app: redis-sso
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis-sso
    spec:
      containers:
      - image: redis:5
        name: redis-sso
        ports:
        - containerPort: 6379
          name: redis-sso

```
**Version (include the output of istioctl version --remote and kubectl version)**

```
client version: 1.2.2
citadel version: 1.2.2
galley version: 1.2.2
ingressgateway version: 1.2.2
pilot version: 1.2.2
policy version: 1.2.2
sidecar-injector version: 1.2.2
```

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-gke.10", GitCommit:"f53039cc1e5295eed20969a4f10fb6ad99461e37", GitTreeState:"clean", BuildDate:"2019-06-19T20:48:40Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Helm Chart and Quick Start Evaluation Install

**Environment where bug was observed (cloud vendor, OS, etc)**

Google Cloud

**Comment by tadeucruz** [comment]
A simple workaround is remove the **name: redis** from ports. I think this new  filter/feature #14582 change the filter. I don't know how to change the PILOT_ENABLE_REDIS_FILTER to make a real test.  

New kube config without problem 

```
apiVersion: v1
kind: Service
metadata:
  name: redis-sso
spec:
  ports:
  - port: 6379
  selector:
    app: redis-sso
  clusterIP: None
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: redis-sso
spec:
  selector:
    matchLabels:
      app: redis-sso
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis-sso
    spec:
      containers:
      - image: redis:5-alpine
        name: redis-sso
        ports:
        - containerPort: 6379
          name: redis-sso

```
