### ISSUE TITLE
Bug in destination rule's "host" interpretation even if FQDN of service is provided

### ISSUE THREAD

**Issue by ajit555db** [istio/istio#15425]
**Bug description**

My destination rule resides in "default" namespace where my service resides in "ns1" namespace. In the destination rule definition, even if I use "FQDN" of the service, it is interpreted to reside in "default" namespace of destination rule and the call to service via istio fails (HTTP/1.1 503 Service Unavailable).

If I change the namespace of destination rule to "ns1" (same as service), then the call to service succeeds.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
It is in contravention to the documentation as below:
https://istio.io/docs/reference/config/networking/v1alpha3/destination-rule/

Note for Kubernetes users: When short names are used (e.g. “reviews” instead of “reviews.default.svc.cluster.local”), Istio will interpret the short name based on the namespace of the rule, not the service. A rule in the “default” namespace containing a host “reviews will be interpreted as “reviews.default.svc.cluster.local”, irrespective of the actual namespace associated with the reviews service. To avoid potential misconfigurations, it is recommended to always use fully qualified domain names over short names.

**Steps to reproduce the bug**  

This does not work (HTTP/1.1 503 Service Unavailable even though FQDN of service is provided)
```
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: helloworld-tls
  namespace: default
spec:
  host: hello.ns1.svc.cluster.local
  subsets:
  - name: v1-tls
    labels:
      version: v1-tls
```
This does works (HTTP/1.1 200 OK after I deploy the rule to ns1, same as service )

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: helloworld-tls
  namespace: ns1
spec:
  host: hello.ns1.svc.cluster.local
  subsets:
  - name: v1-tls
    labels:
      version: v1-tls
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

$ istioctl version --remote
client version: 1.2.0
citadel version: 1.2.0
egressgateway version: 1.2.0
galley version: 1.2.0
ingressgateway version: 1.2.0
pilot version: 1.2.0
policy version: 1.2.0
sidecar-injector version: 1.2.0
telemetry version: 1.2.0

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
as per https://istio.io/docs/setup/kubernetes/install/kubernetes/
with "permissive mutual TLS" mode.

**Environment where bug was observed (cloud vendor, OS, etc)**
Ubuntu OS version : 
$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
