### ISSUE TITLE
Traffic shifting does not work with private destination rules

### ISSUE THREAD

**Issue by robertpanzer** [istio/istio#15454]
**Bug description**
When configuring subsets with label matches in private destination rules, traffic policy rules are applied for CDS, but not for EDS.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Label selectors in private destination rules should apply for traffic policies as well as for endpoints.

**Steps to reproduce the bug**

Install Istio with `global.mtls.enable=false`.
Then apply this configuration that creates two provider Deployments under one Service with different `version` labels. 
The configuration also has a consumer deployment and a VirtualService and DestinationRule that should direct all traffic to the v1 deployment:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: provider
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testserverv1
  namespace: provider
spec:
  selector:
    matchLabels:
      app: testserver
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: testserver
        version: v1
    spec:
      containers:
        - name: testserver
          image: kennethreitz/httpbin
          ports:
            - containerPort: 80
              name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testserverv2
  namespace: provider
spec:
  selector:
    matchLabels:
      app: testserver
      version: v2
  replicas: 1
  template:
    metadata:
      labels:
        app: testserver
        version: v2
    spec:
      containers:
        - name: testserver
          image: kennethreitz/httpbin
          ports:
            - containerPort: 80
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: testserver
  namespace: provider
  labels:
    app: testserver
spec:
  selector:
    app: testserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: consumer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testcurl
  namespace: consumer
spec:
  selector:
    matchLabels:
      app: testcurl
  replicas: 1
  template:
    metadata:
      labels:
        app: testcurl
    spec:
      containers:
        - name: testcurl
          image: tutum/curl
          command:
            - sleep
            - "100000"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: testserver
  namespace: consumer
spec:
  export_to:
    - "."
  hosts:
    - testserver.provider.svc.cluster.local
  http:
    - route:
        - destination:
            host: testserver.provider.svc.cluster.local
            subset: v1
            port:
              number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: testserver
  namespace: consumer
spec:
  export_to:
    - "."
  host: testserver.provider.svc.cluster.local
  subsets:
    - name: v1
      labels:
        version: v1
      trafficPolicy:
        tls:
          mode: ISTIO_MUTUAL
```

Now get the clusters that were pushed to the consumer (after starting a port-forward with `kubectl port-forward -n consumer testcurl-57f77bc7c7-zll9k 15000`):
```
curl -s localhost:15000/clusters|grep "outbound|80|v1|testserver.provider.svc.cluster.local"|cut -d ':' -f 3|grep -e '[0-9.][0-9.]*'|uniq
10.1.26.60
10.1.26.61
```
Apparently the addresses of both pods were pushed for this cluster which means that the label selector was not applied even though they are set on the pods:
```
kgp -n provider --show-labels -o wide
NAME                            READY   STATUS    RESTARTS   AGE   IP           NODE             NOMINATED NODE   READINESS GATES   LABELS
testserverv1-7bb5d99789-wjb7f   2/2     Running   0          19m   10.1.26.61   docker-desktop   <none>           <none>            app=testserver,pod-template-hash=7bb5d99789,version=v1
testserverv2-554b96b9f4-r9m9m   2/2     Running   0          19m   10.1.26.60   docker-desktop   <none>           <none>            app=testserver,pod-template-hash=554b96b9f4,version=v2
```

However the cluster has the ISTIO_MUTUAL traffic policy if I look at the config dump while the default cluster uses plain text communication, this means that the DestinationRule was applied for CDS:
```json
    {
     "version_info": "2019-07-11T09:29:16Z/7",
     "cluster": {
      "name": "outbound|80|v1|testserver.provider.svc.cluster.local",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {},
        "initial_fetch_timeout": "0s"
       },
       "service_name": "outbound|80|v1|testserver.provider.svc.cluster.local"
      },
      "connect_timeout": "10s",
      "circuit_breakers": {
       "thresholds": [
        {
         "max_retries": 1024
        }
       ]
      },
      "tls_context": {
       "common_tls_context": {
        "tls_certificates": [
         {
          "certificate_chain": {
           "filename": "/etc/certs/cert-chain.pem"
          },
          "private_key": {
           "filename": "/etc/certs/key.pem"
          }
         }
        ],
        "validation_context": {
         "trusted_ca": {
          "filename": "/etc/certs/root-cert.pem"
         },
         "verify_subject_alt_name": [
          "spiffe://cluster.local/ns/provider/sa/default"
         ]
        },
        "alpn_protocols": [
         "istio"
        ]
       },
       "sni": "outbound_.80_.v1_.testserver.provider.svc.cluster.local"
      },
      "metadata": {
       "filter_metadata": {
        "istio": {
         "config": "/apis/networking/v1alpha3/namespaces/consumer/destination-rule/testserver"
        }
       }
      }
     },
     "last_updated": "2019-07-11T09:29:22.576Z"
    },
...
    {
     "version_info": "2019-07-11T09:29:16Z/7",
     "cluster": {
      "name": "outbound|80||testserver.provider.svc.cluster.local",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {},
        "initial_fetch_timeout": "0s"
       },
       "service_name": "outbound|80||testserver.provider.svc.cluster.local"
      },
      "connect_timeout": "10s",
      "circuit_breakers": {
       "thresholds": [
        {
         "max_retries": 1024
        }
       ]
      },
      "metadata": {
       "filter_metadata": {
        "istio": {
         "config": "/apis/networking/v1alpha3/namespaces/consumer/destination-rule/testserver"
        }
       }
      }
     },
     "last_updated": "2019-07-11T09:29:22.575Z"
    },
```

Now if I add a Sidecar resource to the consumer namespace that label selector is suddenly applied:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
  namespace: consumer
spec:
  egress:
    - hosts:
        - "*/*"
```
And getting the clusters shows the success:
```
curl -s localhost:15000/clusters|grep "outbound|80|v1|testserver.provider.svc.cluster.local"|cut -d ':' -f 3|grep -e '[0-9.][0-9.]*'|uniq
10.1.26.61
```

This seems to come from the different behavior here:
For EDS the current node and hence its namespace are not passed:
https://github.com/istio/istio/blob/c3a9218ffb80383dfbfbdbcccbde0d8fb5def6b7/pilot/pkg/proxy/envoy/v2/eds.go#L692-L696
But for building the clusters it is:
https://github.com/istio/istio/blob/c3a9218ffb80383dfbfbdbcccbde0d8fb5def6b7/pilot/pkg/networking/core/v1alpha3/cluster.go#L141

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```
$ ~/istio/istio-1.2.2/bin/istioctl version --remote
client version: 1.2.2
citadel version: 1.2.2
egressgateway version: 1.2.2
galley version: 1.2.2
ingressgateway version: 1.2.2
pilot version: 1.2.2
sidecar-injector version: 1.2.2
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"
```

**How was Istio installed?**

Installed with helm install.
Most important values were:
```yaml
global:
  tracing:
    enabled: true 
  useMCP: true
  mtls:
    enabled: false
  disablePolicyChecks: true
  controlPlaneSecurityEnabled: true
```

**Environment where bug was observed (cloud vendor, OS, etc)**

Local environment on Docker for Mac
