### ISSUE TITLE
Single Gateway with multiple Virtual Service

### ISSUE THREAD

**Issue by athertahir** [istio/istio#15458]
**Bug description**

I have single gateway and two virtual services. I am sending requests to ingress-gateway but with different hostnames But traffic is routed to same services for both.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[X ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
I have single gateway and two virtual services. Two services are sending to ingress-gateway but with different hostname But traffic is routed to same service for both.

**Steps to reproduce the bug**
Gateway
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: sip-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*.example.com'
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: false
  - hosts:
      - '*.example.com'
    port:
      name: tcp
      number: 50051
      protocol: TCP
  - hosts:
    - '*.example.com'
    port:
      name: tcp-search
      number: 50052
      protocol: TCP
  - hosts:
    - '*.example.com'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
```

VirtualService
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: serviceb-svc
spec:
  hosts:
  - "serviceB.sip.onl"
  gateways:
  - sip-gateway.istio-system.svc.cluster.local
  tcp:
  - match:
    - port: 50051
    route:
    - destination:
        host: serviceb-svc.default.svc.cluster.local
        port:
          number: 50051
		  
		  
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: servicea-svc
spec:
  hosts:
  - "serviceA.example.com"
  gateways:
  - sip-gateway.istio-system.svc.cluster.local
  tcp:
  - match:
    - port: 50051
    route:
    - destination:
        host: servicea-svc.default.svc.cluster.local
        port:
          number: 50051

```

Services

```
# SERVICES
apiVersion: v1
kind: Service
metadata:
  name: searchclientservice-svc
spec:
  selector:
    app: searchclientservice
  ports:
    - name: grpc-web-port
      port: 50051
      targetPort: 50051

apiVersion: v1
kind: Service
metadata:
  name: translatorservice-svc
spec:
  selector:
    app: translatorservice
  ports:
    - name: grpc-web-port
      port: 50051
      targetPort: 50051

```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istioctl version --remote
client version: 1.2.2
citadel version: 1.2.2
galley version: 1.2.2
ingressgateway version: 1.2.2
pilot version: 1.2.2
policy version: 1.2.2
sidecar-injector version: 1.2.2
telemetry version: 1.2.2

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.9-eks-f1dbc0", GitCommit:"f1dbc0230ef279fc153185a97b8fca4e40f675fe", GitTreeState:"clean", BuildDate:"2019-06-21T23:34:23Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

```
**How was Istio installed?**
using helm charts

**Environment where bug was observed (cloud vendor, OS, etc)**
EKS

**Comment by GregHanson** [comment]
@athertahir unfortunately for plain TCP traffic, Envoy does not look at hostnames - only port number.

**Comment by athertahir** [comment]
> @athertahir unfortunately for plain TCP traffic, Envoy does not look at hostnames - only port number.

Thanks for the reply.
Should I use http then? I have to support both grpc and web-grpc for multiple services (I wanted to distinguish multiple services using hostname). I have using different ingress-gateway ports 55051 and 443 respectively for the traffic. is it possible? or two unique ports for each service

I am also sharing full VirtualService yaml

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: searchclientservice-vs
spec:
  hosts:
  - "serviceA.example.com"
  gateways:
  - sip-gateway.istio-system.svc.cluster.local
  tcp:
  - match:
      port: 50051
    route:
    - destination:
        host: searchclientservice-svc.default.svc.cluster.local
        port:
          number: 50051
  http:
  - match:
      port: 50051
    route:
    - destination:
        host: searchclientservice-svc.default.svc.cluster.local
        port:
          number: 50051
    corsPolicy:
      allowOrigin:
        - "*"
      allowMethods:
        - POST
        - GET
        - OPTIONS
        - PUT
        - DELETE
      allowHeaders:
        - grpc-timeout
        - content-type
        - keep-alive
        - user-agent
        - cache-control
        - content-type
        - content-transfer-encoding
        - custom-header-1
        - x-accept-content-transfer-encoding
        - x-accept-response-streaming
        - x-user-agent
        - x-grpc-web
      maxAge: 1728s
      exposeHeaders:
        - custom-header-1
        - grpc-status
        - grpc-message
      allowCredentials: true
```
