### ISSUE TITLE
Support wildcard/regexp in VirtualService host

### ISSUE THREAD

**Issue by yarivlifchuk** [istio/istio#15456]
**Describe the feature request**
Hi,
 Host in virtual service does not support regexp or wildcard in the left most field (unqualified host)
 e.g.   aaa*.dev.general.com  
There are scenarios which uses different host with the same fqdn that have the same destinations .
Currently I have to define several hosts in the same virtual service.I would like to use only one host with wildcard/regexp and by this decrease the total number of rules.

additional info
-	Any virtual Service in Istio is installed per Namespace.
-	Access to Virtual Service (VS) is done with a matching host which is the address used by a client.

 Describe the solution you'd like:
Uses different host with the same fqdn that have the same destinations 
using one url in vs host  with wildcard/regexp.

e.g.
instead of the following vs:

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: wing-virtualservice
  namespace: exotic-falcon
spec:
  hosts:
  - aaa1.dev.general.com
  - aaa2.dev.general.com
  - aaa3.dev.general.com
  - aaa4.dev.general.com
  - aaa5.dev.general.com
  - aaa6.dev.general.com
  gateways:
  - ws-gateway-dev.istio-system.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: ws-2rdmq-service.exotic-falcon.svc.cluster.local
        port:
          number: 8000
        trafficPolicy:
          tls:
            mode: ISTIO_MUTUAL

Use the following vs:

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: wing-virtualservice
  namespace: exotic-falcon
spec:
  hosts:
  - aaa*.dev.general.com
  gateways:
  - ws-gateway-dev.istio-system.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: ws-2rdmq-service.exotic-falcon.svc.cluster.local
        port:
          number: 8000
        trafficPolicy:
          tls:
            mode: ISTIO_MUTUAL

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[X] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by rshriram** [comment]
> aaa*.dev.general.com
problem is envoy supports only prefix * or suffix *, and not general purpose regex in virtual host.

**Comment by yarivlifchuk** [comment]
I know that Ambassador that is based on Envoy as well support this.

**Comment by yarivlifchuk** [comment]
please see the following link in envoy regarding header matcher which support suffix_match and regex_match
https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#envoy-api-msg-route-headermatcher

**Comment by howardjohn** [comment]
Can you use https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#StringMatch

**Comment by howardjohn** [comment]
Please try using what I posted above with host header. If it doesn't work we can revist this

**Comment by nsainaney** [comment]
I've tried the host header method with istio 1.3.x and 1.4.7. Here's the virtual service:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: example-vs
  namespace: testing
spec:
  gateways:
  - traxitt-system/system-gateway
  hosts:
  - '*'
  http:
  - match:
    - headers:
        host:
          exact: foo.bar.example.com
    route:
    - destination:
        host: example-service
        port:
          number: 80
```

and it does not work but the following does:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: example-vs
  namespace: testing
spec:
  gateways:
  - traxitt-system/system-gateway
  hosts:
  - 'foo.bar.example.com'
  http:
  - match:
    - headers: {}
    route:
    - destination:
        host: example-service
        port:
          number: 80
```

I've verified that headers are coming through using (https://hub.docker.com/r/mendhak/http-https-echo)

Even matching `regex: .*`

Matching other headers like `user-agent: regex: Moz*` does work. It seems it's only broken for the host header value.
