### ISSUE TITLE
Secure GRPC calls not reaching ingress gateway.

### ISSUE THREAD

**Issue by focks** [istio/istio#15461]
I have installed istio 1.22.2 inside kubernetes (1.12.x) with sds enabled. I have been following this https://istio.io/docs/tasks/traffic-management/ingress/secure-ingress-sds/ and I am able to do ssl termination at the ingress gateway for normal services (on HTTP/1.1).  And I could see it in the access logs of the gateway.

gateway
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mygateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 31400
      name: tcp
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: "review-this-co" # must be the same as secret
    hosts:
    - "xyz.example.com"
```

However when GRPC is used over secure channel I could not see any access logs. (Grpc client fails).

**NOTE**: same grpc client works(call reaches the ingress gateway, visible in the access logs) with plaintext if the gateway is configured like following

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mygateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 31400
      name: tcp
      protocol: GRPC
    hosts:
    - "xyz.example.com"
```
