### ISSUE TITLE
redisquota is not consistent with memquota counting.

### ISSUE THREAD

**Issue by juniorz** [istio/istio#15543]
**Bug description**

Istio documentation on Rate-Limiting states:

> Every named quota instance like requestcount represents a set of counters. The set is defined by a Cartesian product of all quota dimensions.

However, the way `memquota` and `redisquota` implement this definition of "set of counter" is not consistent (as mentioned in https://github.com/istio/istio/issues/8526#issuecomment-457291737). As both support the `quota template`, the documentation even suggests that `redisquota` is a drop-in replacement for `memquota` - and encourages its use for convenience unless in production.

Consider the following named instance and handlers:

```
---
apiVersion: config.istio.io/v1alpha2
kind: instance
metadata:
  name: my-instance
  namespace: istio-system
spec:
  compiledTemplate: quota
  params:
    dimensions:
      source: request.headers["x-forwarded-for"] | "unknown"
      destination: destination.labels["app"] | destination.service.name | "unknown"
---
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: quotahandler-redis
  namespace: istio-system
spec:
  compiledAdapter: redisquota
  params:
    redisServerUrl: "redis.default.svc.cluster.local:6379"
    connectionPoolSize: 1
    quotas:
    - name: requestcountquota-redis.instance.istio-system
      maxAmount: 1000
      validDuration: 10s
---
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: quotahandler-memory
  namespace: istio-system
spec:
  compiledAdapter: memquota
  params:
    quotas:
    - name: requestcountquota-memory.instance.istio-system
      maxAmount: 1000
      validDuration: 10s
```

For `memquota`, each unique tuple `(source, destination)` gets its own counter. For `redisquota` the same counter is used for all unique tuple `(source, destination)`.

With this setup in place:

- `memquota` will allow a rate of 80 req/s on each of the two requests types `(source=10.0.0.1,  destination=reviews)` and `(source=10.0.10.1,  destination=reviews)`. No `429`s.
- `redisquota` will NOT allow a rate of 80 req/s on each of the two requests types `(source=10.0.0.1,  destination=reviews)` and `(source=10.0.10.1,  destination=reviews)`. It will limit 60 req/s (from both request types).

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

For the same named instance, `memquota` and `redisquota` should rate-limit similarly given they are configured similarly (`maxAmount` and `validDuration`).

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```
$ istioctl version --remote
client version: 1.2.2
citadel version: release-1.2-20190713-09-16
galley version: release-1.2-20190702-09-15
galley version: release-1.2-20190713-09-16
pilot version: release-1.2-20190702-09-15
pilot version: release-1.2-20190702-09-15
policy version: release-1.2-20190702-09-15
sidecar-injector version: release-1.2-20190702-09-15
sidecar-injector version: release-1.2-20190713-09-16
telemetry version: release-1.2-20190703-09-16
telemetry version: release-1.2-20190702-09-15

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.10", GitCommit:"7a578febe155a7366767abce40d8a16795a96371", GitTreeState:"clean", BuildDate:"2019-05-01T04:14:38Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.10", GitCommit:"7a578febe155a7366767abce40d8a16795a96371", GitTreeState:"clean", BuildDate:"2019-05-01T04:05:01Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

From the helm chart.
