### ISSUE TITLE
service call service through virtualservice with match uri

### ISSUE THREAD

**Issue by phuthinh2202** [istio/istio#15583]
[x ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Kubernetes: 1.12
Istio version: 1.1.3

How i can route the Service A in Namespace AA to multi service in Namespace BB through virualservice with match uri, my example config below:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: b-vs
  namespace: BB
spec:
  hosts:
  - b.BB.svc.cluster.local
  gateways:
  - mesh
  http:
  - match:
    - uri:
        prefix: "/svc-b/"
   rewrite:
        uri: "/"
    route:
    - destination:
        host: b.BB.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: "/svc-bb/"
    rewrite:
        uri: "/"
    route:
      - destination:
          host: bb.BB.svc.cluster.local
          port:
            number: 80
    timeout: 10s
    retries:
      attempts: 3
      perTryTimeout: 2s
```

**Expected behavior**

from service A call "b.BB.svc.cluster.local/svc-b/[url]" will route traffic to "b.BB.svc.cluster.local" and "b.BB.svc.cluster.local/svc-bb/[url]" to "bb.BB.svc.cluster.local"

can anybody help me :D
