### ISSUE TITLE
with sidecar annotation injection enabled, but namespace injection disabled, sidecar is not injected

### ISSUE THREAD

**Issue by sdake** [istio/istio#15619]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
A slack conversation below:
<img width="866" alt="Screen Shot 2019-07-18 at 6 49 17 AM" src="https://user-images.githubusercontent.com/755849/61462958-603e6a80-a928-11e9-9edb-3ce675e72e44.png">

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
injection always honors the annotation, regardless of whether the namesapce is marked for injection or not.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.2.z

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
This is not possible afaik without https://github.com/istio/istio/issues/16538, so closing as a dupe of that

**Comment by sb1975** [comment]
/open

Since the objectSelector is added - this should be now taken be up to ensure consistent behaviour.

**Comment by jonmoter** [comment]
Here is the (slightly edited) default configuration of the `MutatingWebhookConfiguration`:

```
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: istio-sidecar-injector
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: "--REDACTED--"
    service:
      name: istiod
      namespace: istio-system
      path: /inject
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: sidecar-injector.istio.io
  namespaceSelector:
    matchLabels:
      istio-injection: enabled
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 30
```

You could change it so that it works on all namespaces except those where istio-injection is explicitly disabled:

```
  namespaceSelector:
    matchExpressions:
    - key: enabled
      operator: NotIn
      values:
      - "disabled"
```
