### ISSUE TITLE
Cannot find redis master EOF - Istio 1.2.2 1.1.11

### ISSUE THREAD

**Issue by kubesure** [istio/istio#15624]
**Bug description**
Redis sentinel cannot find master with Istio 1.2.2 or 1.1.11.  Have tried renaming service name redis to redis-sso as suggested in a different issue, but it just wont work. I would like to work with Istio and not move to linkerd. Pls help solve. 

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

sentinel get-master-addr-by-name should return with master instead of error. This works well without isito side cars 

**Steps to reproduce the bug**
apply 

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-sso
    role: master
    tier: backend
  name: redissvc
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
	name: rtcp 
  selector:
    app: redis-sso
    role: master
    tier: backend
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  labels:
    app: redis-sso
    role: master
    tier: backend
data:
  master.conf: |- 
    bind 0.0.0.0
    port 6379
    save 900 1
    dir /redis-data
  slave.conf: |-
    bind 0.0.0.0
    port 6379
    dir .
    slaveof redis-premium-master-0.redissvc.default.svc.cluster.local 6379
  sentinel.conf: |- 
    bind 0.0.0.0
    port 26379
    sentinel monitor redis-premium-master redis-premium-master-0.redissvc.default.svc.cluster.local 6379 2
    sentinel parallel-syncs redis-premium-master 1
    sentinel down-after-milliseconds redis-premium-master 10000
    sentinel failover-timeout redis-premium-master 20000
  sentinel.sh: |- 
    #!/bin/bash
    cp /redis-config/sentinel.conf /sentinel.conf
    while ! ping -c 1 redis-premium-master-0.redissvc.default.svc.cluster.local; do
      echo 'Waiting for server'
      sleep 1
    done
    redis-sentinel /sentinel.conf
  init.sh: |-
    #!/bin/bash
    if [[ ${HOSTNAME} == 'redis-premium-master-0' ]]; then
      redis-server /redis-config/master.conf
    else
      redis-server /redis-config/slave.conf
    fi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-premium-master
  labels:
    app: redis-sso
    role: master
    tier: backend
spec:
  replicas: 3
  serviceName: redissvc
  selector:
    matchLabels:
      app: redis-sso
      role: master
      tier: backend 
  template:
    metadata:
      labels:
        app: redis-sso
        role: master
        tier: backend
    spec:
      containers:
      - command: [sh, -c, source /redis-config/init.sh]
        image: redis:{{.Values.imageredis.tag}}
        name: redis
        ports: 
        - containerPort: 6379
        volumeMounts: 
        - mountPath: /redis-data
          name: data
        - mountPath: /redis-config
          name: config
        livenessProbe:
          tcpSocket: 
            port: 6379
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
      - command: [sh, -c, source /redis-config/sentinel.sh]
        image: redis:3.2.7-alpine
        name: sentinel
        ports:
        - containerPort: 26379
        volumeMounts: 
        - mountPath: /redis-data
          name: data
        - mountPath: /redis-config
          name: config          
      volumes: 
      - configMap: 
          defaultMode: 420
          name: redis-config
        name: config
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.alpha.kubernetes.io/storage-class: default
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---           
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: premium
    role: business
    type: backend
  name: premiumcalc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: premium
      role: business
      type: backend
  template:
    metadata:
      labels:
        app: premium
        role: business
        type: backend
    spec:
      containers:
      - image: bikertales/premiumcalc:v0.2
        name: premiumcalc
        ports:
        - containerPort: 8000
        env: 
        - name: redissvc
          value: redissvc  
        readinessProbe:
          httpGet:
            path: /api/v1/healths/premiums/loads
            port: 8000
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 10  
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: premium
    role: business
    type: backend
  name: premiumcalc-svc
  annotations:
    getambassador.io/config: |
      apiVersion: ambassador/v1
      kind: Mapping
      name: premium-mapping
      prefix: /api/v1/healths/premiums
      service: premiumcalc-svc:8000
      rewrite: ""
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
	name: ptcp
  selector:
    app: premium
    role: business
    type: backend  
  type: NodePort
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Version: 1.0.5
GitRevision: c1707e45e71c75d74bf3a5dec8c7086f32f32fad
User: root@6f6ea1061f2b
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
helm 

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EC2

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
