### ISSUE TITLE
Istio mTLS ignored without containerPort declaration

### ISSUE THREAD

**Issue by esnible** [istio/istio#15633]
I am not sure if this is a documentation problem, a security problem, or user error.

I deployed Fortio using _tools/perf_k8svcs.yaml_.  I wasn't trying to do a performance test, I just wanted to grab an example Deployment descriptor for Fortio.

Fortio listens on 8080 and 8079.  I created a DestinationRule to use mTLS:
```
cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: use-least-connected-fortio
spec:
  host: fortio-echo
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
    tls:
      mode: ISTIO_MUTUAL
EOF
```

After applying the rule, traffic on 8080 used mTLS but traffic on 8079, the gRPC port, from non-Istio applications was not blocked.

It took me a few hours to notice that _perf_k8svcs.yaml_ defines two ports in the K8s Service, but only

```
        ports:
        - containerPort: 8080
```

on the K8s Deployment.  Changing to 

```
        ports:
        - containerPort: 8080
        - containerPort: 8079
```

allowed gRPC to work with mTLS.

Is it documented behavior that mTLS settings only work with explicit `containerPort` on the pod?  (It would be easy for a user to believe mTLS is happening when it isn't.)

_istioctl_ claims the client and server are doing mTLS.  (I set up a Policy that is STRICT here, without it the server would be `HTTP/mTLS`.

```
fortio-echo.default.svc.cluster.local:8079                                           OK         mTLS          mTLS       fortio-echo/default                          use-least-connected-fortio/default
fortio-echo.default.svc.cluster.local:8080                                           OK         mTLS          mTLS       fortio-echo/default                          use-least-connected-fortio/default
```

Although I specified mTLS in my DR, and my Policy, and istioctl shows mTLS, traffic to the server isn't even going through Envoy and none of the Envoy rules are respected.

I figured this out is with help from @GregHanson who helped me to understand that 8080 was appearing in Envoy access logs but 8079 wasn't.
