### ISSUE TITLE
Service entry not behaving the same for sidecar and istio-ingressgateway

### ISSUE THREAD

**Issue by aattuluri** [istio/istio#15782]
**Bug description**
When we define the following service entry (where `.mesh` hostnames are resolved with istiocoredns) and virtual service, it seems to work via istio-ingressgateway but not from a sidecar istio-proxy in a workload.

```
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: meshapp02-se
  namespace: meshapp02
spec:
  hosts:
  - meshapp02.mesh
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 80
    protocol: http
  resolution: DNS
  addresses:
  - 127.0.10.20
  endpoints:
  - address: meshapp02-appd-service.meshapp02.svc.cluster.local
    ports:
      http: 8090
```

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: meshapp02-vs
  namespace: meshapp02
spec:
  exportTo:
  - "*"
  gateways:
  - mesh
  - istio-multicluster-ingressgateway
  hosts:
    - meshapp02.mesh
  http:
  - route:
    - destination:
        host: meshapp02-appd-service.meshapp02.svc.cluster.local
```

Here is the output for _istioctl proxy-config endpoints_ command :

istio-ingressgateway (looks right as it points to meshapp02-appd-service.meshapp02.svc.cluster.local's cluster IP):
```
100.69.87.103:8080        HEALTHY     outbound|80||meshapp02.mesh
```

meshapp01 (doesn't look right, some random public IPs):
```
46.19.209.188:8080        HEALTHY     outbound|80||meshapp02.mesh
46.19.209.189:8080        HEALTHY     outbound|80||meshapp02.mesh
```

I think this is causing the calls from meshapp02.mesh from meshapp01 to fail with 503 while the same works via istio-ingressgateway.

**Affected product area (please put an X in all that apply)**

[x] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
The DNS resolution/EDS should be consistent between istio-ingressgateway and other sidecar proxies and should resolve to the cluster local services.

**Steps to reproduce the bug**
See the bug description

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio version: 1.1.7

**How was Istio installed?**
Using helm generation

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by aattuluri** [comment]
Does https://github.com/istio/istio/issues/13008 impact the above scenario?, I do not see how, but would be great to get that information.

@rshriram @uk000

**Comment by aattuluri** [comment]
This started working after:
i) upgrading to istio 1.2 and 
ii) Adding port under destination of the virtual service:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: meshapp02-vs
  namespace: meshapp02
spec:
  exportTo:
  - "*"
  gateways:
  - mesh
  - istio-multicluster-ingressgateway
  hosts:
    - meshapp02.mesh
  http:
  - route:
    - destination:
        host: meshapp02-appd-service.meshapp02.svc.cluster.local
        port:
          number: 8090
```
