### ISSUE TITLE
Consistent Hash load balancer creates cookies for all subsets

### ISSUE THREAD

**Issue by treedy** [istio/istio#15826]
**Bug description**
When a DestinationRule specifies a trafficPolicy that uses cookies for a consistentHash loadBalancer for more than one subset, each subset's cookie is applied instead of just the appropriate subset's cookie.

Was attempting this as a workaround for https://github.com/istio/istio/issues/9764

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Only the subset's cookie should be set instead of multiple cookies.

**Steps to reproduce the bug**
Create a service that is served with a Virtual Service. See YAML
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: webinfo-destinations
spec:
  host: webinfo-svc
  subsets:
  - name: production
    labels:
      version: production
    trafficPolicy:
      loadBalancer:
        consistentHash:
          httpCookie:
            name: production
            ttl: 3600s
          minimumRingSize: 42
  - name: canary
    labels:
      version: canary
    trafficPolicy:
      loadBalancer:
        consistentHash:
          httpCookie:
            name: canary
            ttl: 3600s
          minimumRingSize: 42
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: webinfo-virt-svc
spec:
  hosts:
  - "*"
  gateways:
  - webinfo-gateway
  http:
  - match:
    - headers:
        cookie:
          prefix: "canary="
    route:
    - destination:
        host: webinfo-svc
        subset: canary
  - match:
    - headers:
        cookie:
          prefix: "production="
    route:
    - destination:
        host: webinfo-svc
        subset: production
  - route:
    - destination:
        host: webinfo-svc
        port:
          number: 8080
        subset: production
      weight: 80
    - destination:
        host: webinfo-svc
        port:
          number: 8080
        subset: canary 
      weight: 20
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: webinfo-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*" # For simple setup
```
Output ($HOST replacing hostname)
```
curl -v  $HOST
* Rebuilt URL to: $HOST/
*   Trying $HOST...
* TCP_NODELAY set
* Connected to $HOST ($HOST_IP) port 80 (#0)
> GET / HTTP/1.1
> Host: $HOST
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< date: Wed, 24 Jul 2019 19:51:16 GMT
< content-length: 36
< content-type: text/plain; charset=utf-8
< x-envoy-upstream-service-time: 2
< server: istio-envoy
< set-cookie: production="dc787462e719b437"; Max-Age=3600; HttpOnly
< set-cookie: canary="dc787462e719b437"; Max-Age=3600; HttpOnly
< 
Hello from webinfo-89df5c8fb-4xxp9!
* Connection #0 to host $HOST left intact
```
Notice that both the "production" and "canary" cookies are set. Only one of the 2 should be set.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
$ istioctl version --remote
client version: 1.2.2
citadel version: 1.2.2
galley version: 1.2.2
ingressgateway version: 1.2.2
pilot version: 1.2.2
policy version: 1.2.2
sidecar-injector version: 1.2.2
telemetry version: 1.2.2
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:46:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.8", GitCommit:"7d3d6f113e933ed1b44b78dff4baf649258415e5", GitTreeState:"clean", BuildDate:"2019-06-19T16:37:16Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
From Helm template method

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
*[istio-dump.tar.gz](https://github.com/istio/istio/files/3428595/istio-dump.tar.gz)*
