### ISSUE TITLE
installation - helm chart - tolerations

### ISSUE THREAD

**Issue by QuRa** [istio/istio#15839]
Referring to the documentation [Installation Options](https://istio.io/docs/reference/config/installation-options/#mixer-options)

I should be able to set tolerations ex. for mixer component, by setting mixer.tolerations,

**Steps to reproduce the bug**

Creating configs by:
```
helm template ${ISTIO_ROOT}/install/kubernetes/helm/istio \
    --name istio \
    --namespace istio-system \
    -f values.yaml 
```

```
# values.yaml
mixer:
  tolerations:
    - key: mgt-host
      operator: Equal
      value: "true"
      effect: NoSchedule
```
this has no effect in generated files,

**Expected behavior**

---
# Source: istio/charts/mixer/templates/deployment.yaml

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata: [...]
spec:
  replicas: 1
  strategy: [...]
  selector: [...]
  template:
    metadata:
      labels:[...]
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      # Ensure pods run on mgt-host
      tolerations:
      - key: mgt-host
        operator: Equal
        value: "true"
        effect: NoSchedule
```
**Version**
istio-1.1.7
