### ISSUE TITLE
Galley rejects Authentication Policies with multiple JWT sections with same issuer

### ISSUE THREAD

**Issue by nrjpoddar** [istio/istio#15868]
**Describe the feature request**
Galley has configuration validation which rejects AuthenticationPolicies with multiple JWT sections and if the same issuer is used in more than once JWT block. This is the relevant [code](https://github.com/istio/istio/blob/76f15793c4f9b259c075c2c9a99d13f64f09599f/pkg/config/validation.go#L1441).

This is a legitimate use case where you might have two kinds of JWT token issued by the issuer that have different audiences and trigger rules. Example:

```yaml
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: my-jwt
  namespace: istio-system
spec:
  targets:
  - name: istio-ingressgateway
  peers:
  - mtls:
  origins:
  - jwt:
      issuer: "https://securetoken.google.com"
      audiences:
      - "productpage"
      jwksUri: "https://www.googleapis.com/oauth2/v1/certs"
      trigger_rules:
      - included_paths:
        - exact: /productpage
  - jwt:
      issuer: "https://securetoken.google.com"
      audiences:
      - "reviews"
      jwksUri: "https://www.googleapis.com/oauth2/v1/certs"
      trigger_rules:
      - includded_paths:
        - exact: /reviews
  principalBinding: USE_ORIGIN
```

**Describe alternatives you've considered**
Adding multiple audiences in the same block doesn't work in this scenario as the trigger rules are different.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
Conversation from [slack](https://istio.slack.com/archives/C3TEGNZ7W/p1564092638036800)

From a preliminary code inspection this appears to be an implementation restriction and not an architectural/Envoy one.

**Comment by nrjpoddar** [comment]
cc @yangminzhu

**Comment by liminw** [comment]
@nrjpoddar As discussed in today's security WG meeting, alternatively, you can use authorization policy to express the condition in your use case. With the current authorization policy, you can write the following:

```
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: example
  namespace: istio-system
spec:
  rules:
  - services: ["istio-ingressgateway.istio-system.svc.cluster.local"]
     paths: ["/productpage”]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: example
  namespace: istio-system
spec:
  subjects:
  - properties:
      request.auth.claims[aud]: productpage
  roleRef:
    kind: ServiceRole
    name: example1
```
You can write the same RBAC policy for "/review" path. 

When we move to [new AuthorizationPolicy design](https://docs.google.com/document/d/1diwa9oYVwmLtarXb-kfWPq-Ul3O2Ic3b8Y21Z3R8DzQ), the syntax will be simpler:

```
apiVersion: security.istio.io/v1beta
kind: AuthorizationPolicy
metadata:
   name: example
   namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  rules:
  - to:
     - operation:
          paths: ["/productpage"]
     when:
     - key: request.auth.claims[aud]
        values: ["/productpage"]
  - to:
     - operation:
          paths: ["/review"]
    when:
    - key: request.auth.claims[aud]
       values: ["/review"]
```
Authentication policy will be very simple, which only includes one issuer.
```
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: my-jwt
  namespace: istio-system
spec:
  targets:
  - name: istio-ingressgateway
  peers:
  - mtls:
  origins:
  - jwt:
      issuer: "https://securetoken.google.com"
      audiences:
      - "productpage"
      - "review"
      jwksUri: "https://www.googleapis.com/oauth2/v1/certs"
     principalBinding: USE_ORIGIN
```
