### ISSUE TITLE
Connection to headless service doesn't recover

### ISSUE THREAD

**Issue by kubaj** [istio/istio#15863]
**Bug description**
Service X which is gRPC client connecting to service Y which is stateful gRPC server doesn't recover when server's pod is recreated.

Service Y is gRPC server configured as a statefulset with headless service. Service also have ServiceEntry: 

```
kind: ServiceEntry
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: y-server
  labels:
    app: y-server
spec:
  hosts:
  - "y-server-0.y-server"
  - "y-server-1.y-server"
  ports:
  - name: grpc
    protocol: grpc
    number: 50051
```

Service X is connecting to service Y using address `y-server-0.y-server:50051`. When service X is started before starting service Y, then everything works fine. When I delete pod of service X, connection to service X fails with message: 
```
rpc error: code = Unavailable desc = upstream connect error or disconnect/reset before headers. reset reason: connection failure
```
When service Y starts then message changes to: 
```
rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

To reconnect to service Y, I need to restart service X.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
After the pod of service Y starts, service X should automatically reconnect to new pod and should be able to call gRPC methods without errors.

**Steps to reproduce the bug**
Mentioned above

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio: 1.1.11
Kubernetes: 1.13.7-gke.8

**How was Istio installed?**
Istio installed on the GKE with helm with default options provided in the docs.

**Environment where bug was observed (cloud vendor, OS, etc)**
Google Kubernetes Engine

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
