### ISSUE TITLE
Operator doesn't honor the component namespace

### ISSUE THREAD

**Issue by morvencao** [istio/istio#15862]
**Description**

Take `default` profile as an example, piece of the `default` profile:
```
hub: docker.io/istio
tag: 1.1.4
defaultNamespacePrefix: istio-system

# Traffic management feature
trafficManagement:
  enabled: true
  components:
    namespace: istio-control

    pilot:
      common:
         ...
```

As we can see, we actually want all our `trafficManagement` components are deployed into `istio-control` namespace, but the manifests generated by the `iop manifest . ...` are not:
```
# cat istio-manifest/crds/Pilot/Pilot.yaml
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: pilot
    release: istio
  name: istio-pilot
  namespace: istio-system
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istio-pilot

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-pilot-service-account
  namespace: istio-system
  labels:
    app: pilot
    release: istio
...
```

**Expected behavior**z

Operator is supposed to honor the component namespace specified in profile.

/cc @ostromart
