### ISSUE TITLE
Secure Ingress Gateway does not work with global SDS enabled

### ISSUE THREAD

**Issue by Monkeyanator** [istio/istio#15866]
**Bug description**
Note: have been having troubles with dev env, so it's possible that the following is simply misconfigured

Following the task for setting up a [secure ingress gateway with SDS](https://istio.io/docs/tasks/traffic-management/ingress/secure-ingress-sds/) works on its own, but when [SDS is enabled globally in the mesh](https://istio.io/docs/tasks/security/auth-sds/) in conjunction with the secure ingress task, requests to the ingressgateway fail.

/cc @JimmyCYJ @incfly 

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
As I understand it, when using a Secure Ingress with SDS enabled globally, traffic through the secure ingress gateway should be terminated  w/ the help of the ingressgateway-embedded node agent, and then use `mTLS` inside the cluster to communicate with other internal services (with certs from the _actual_ node agent running on the node rather than the one in the container with the secure gateway).

More concretely, in these examples, the request to the `httpbin` service through the ingressgateway should succeed.

**Steps to reproduce the bug**

Following the steps from the [SDS task](https://istio.io/docs/tasks/security/auth-sds/) we install Istio with the following configuration:

```yaml
global:
  controlPlaneSecurityEnabled: false
  hub: gcr.io/samnaser-gke-dev-217421
  tag: samnaser-dev
  imagePullPolicy: Always
  
  mtls:
    # Default setting for service-to-service mtls. Can be set explicitly using
    # destination rules or service annotations.
    enabled: true

  sds:
    enabled: true
    udsPath: "unix:/var/run/sds/uds_path"
    useNormalJwt: true

nodeagent:
  enabled: true
  image: node-agent-k8s
  env:
    CA_PROVIDER: "Citadel"
    CA_ADDR: "istio-citadel:8060"
    VALID_TOKEN: true
```

Next, follow the steps starting from [here](https://istio.io/docs/tasks/traffic-management/ingress/secure-ingress-sds/#before-you-begin). Rather than a little teapot at the end of the first tutorial step, we receive:

```
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=Denial; L=Springfield; O=Dis; CN=httpbin.example.com
*  start date: Jul 26 18:45:36 2019 GMT
*  expire date: Aug  4 18:45:36 2020 GMT
*  common name: httpbin.example.com (matched)
*  issuer: C=US; ST=Denial; O=Dis; CN=httpbin.example.com
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x562ad9a60dd0)
> GET /status/418 HTTP/2
> Host:httpbin.example.com
> User-Agent: curl/7.64.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 4294967295)!
< HTTP/2 503 
< content-length: 91
< content-type: text/plain
< date: Fri, 26 Jul 2019 19:05:55 GMT
< server: istio-envoy
< 
* Connection #0 to host httpbin.example.com left intact
upstream connect error or disconnect/reset before headers. reset reason: connection failure
```

And here is a [link the the config_dump endpoint of the ingressgatway proxy](https://gist.github.com/Monkeyanator/5d69dfa7910e211c191489fa902a0711).

Perhaps there's another step here that I'm missing to make this work? Please let me know if there's other information that might be useful for debugging.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-gke.10", GitCommit:"f53039cc1e5295eed20969a4f10fb6ad99461e37", GitTreeState:"clean", BuildDate:"2019-06-19T20:48:40Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

```
istioctl version --remote
client version: 1.2.0
citadel version: f3f9a430fb7de56b40ae38dc665b1b2cae145b08
egressgateway version: f3f9a430fb7de56b40ae38dc665b1b2cae145b08
galley version: f3f9a430fb7de56b40ae38dc665b1b2cae145b08
ingressgateway version: master-20190711-09-16
nodeagent version: 
nodeagent version: 
nodeagent version: 
nodeagent version: 
pilot version: f3f9a430fb7de56b40ae38dc665b1b2cae145b08
policy version: f3f9a430fb7de56b40ae38dc665b1b2cae145b08
sidecar-injector version: f3f9a430fb7de56b40ae38dc665b1b2cae145b08
telemetry version: f3f9a430fb7de56b40ae38dc665b1b2cae145b08
```

**How was Istio installed?**
Through sample yaml

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by incfly** [comment]
@myidpt  @linsun To me this definitely seems to be a beta promotion blocker for SDS.

I suspect the root cause is as same as what we see when trying to get `ISTIO_MUTUAL` work for egress gateway... see https://github.com/istio/istio/issues/15485#issuecomment-515620536

**Comment by JimmyCYJ** [comment]
The ingress sds is enabled by a helm flag gateways.istio-ingressgateway.sds.enabled, and global SDS flag is for workload SDS. I had discussion with @costinm, the global SDS flag will be deprecated in 1.3 and we are going to use installer to enable SDS. The new approach that enables SDS has some common steps as we enable ingress SDS.
https://docs.google.com/document/d/13bEpAeSKV8ADMK37ANkQV4FXli5bTQGAqZvhV50yn0M/edit#heading=h.qex63c29z2to

**Comment by incfly** [comment]
@Monkeyanator I think we can closing this now.

Might worth adding an e2e test to exercise both. @JimmyCYJ btw

**Comment by incfly** [comment]
@Monkeyanator I just realized someone else also run into this issue very often...(see linked issue above) do you mind sharing some tips here and istio.io troubleshooting sections (would be better)?

We can add an E2E test as a separate bug.

**Comment by Monkeyanator** [comment]
Update: this bug was due to the same mistake [ I made here](https://github.com/istio/istio/issues/15485#issuecomment-516179868). Specifically, I was generating the configuration for the `Ingress Gateway` separately from the rest of the mesh config, which resulted in the SDS UDS path never getting mounted.

When I put all the mesh configuration values, including the ingress gateway, in the same config, the example works fine with global SDS enabled. We can see observe the correct `listener` configuration on the ingressgateway envoy instance:

```json
    {
     "version_info": "2019-08-02T00:03:24Z/19",
     "listener": {
      "name": "0.0.0.0_443",
      "address": {
       "socket_address": {
        "address": "0.0.0.0",
        "port_value": 443
       }
      },
      "filter_chains": [
       {
        "filter_chain_match": {
         "server_names": [
          "httpbin.example.com"
         ]
        },
        "tls_context": {
         "common_tls_context": {
          "alpn_protocols": [
           "h2",
           "http/1.1"
          ],
          "tls_certificate_sds_secret_configs": [
           {
            "name": "httpbin-credential",
            "sds_config": {
             "api_config_source": {
              "api_type": "GRPC",
              "grpc_services": [
               {
                "google_grpc": {
                 "target_uri": "unix:/var/run/ingress_gateway/sds",
                 "stat_prefix": "sdsstat"
                }
               }
              ]
             },
             "initial_fetch_timeout": "0s"
            }
           }
          ]
         },
         "require_client_certificate": false
        },
```

From what I can tell, the outbound `cluster` traffic is also secured with the workload `SDS` identities (supplied by actual nodeagent, rather than pod nodeagent):

```json
{
          "version_info": "2019-08-02T00:00:02Z/17",
          "cluster": {
            "name": "outbound|8000||httpbin.bar.svc.cluster.local",
            "type": "EDS",
            "eds_cluster_config": {
              "eds_config": {
                "ads": {},
                "initial_fetch_timeout": "0s"
              },
              "service_name": "outbound|8000||httpbin.bar.svc.cluster.local"
            },
            "connect_timeout": "10s",
            "circuit_breakers": {
              "thresholds": [
                {
                  "max_retries": 1024
                }
              ]
            },
            "tls_context": {
              "common_tls_context": {
                "alpn_protocols": [
                  "istio"
                ],
                "tls_certificate_sds_secret_configs": [
                  {
                    "name": "default",
                    "sds_config": {
                      "api_config_source": {
                        "api_type": "GRPC",
                        "grpc_services": [
                          {
                            "google_grpc": {
                              "target_uri": "unix:/var/run/sds/uds_path",
                              "channel_credentials": {
                                "local_credentials": {}
                              },
                              "call_credentials": [
                                {
                                  "from_plugin": {
                                    "name": "envoy.grpc_credentials.file_based_metadata",
                                    "typed_config": {
                                      "@type": "type.googleapis.com/envoy.config.grpc_credential.v2alpha.FileBasedMetadataConfig",
                                      "secret_data": {
                                        "filename": "/var/run/secrets/kubernetes.io/serviceaccount/token"
                                      },
                                      "header_key": "istio_sds_credentials_header-bin"
                                    }
                                  }
                                }
                              ],
                              "stat_prefix": "sdsstat",
                              "credentials_factory_name": "envoy.grpc_credentials.file_based_metadata"
                            }
                          }
                        ]
                      },
                      "initial_fetch_timeout": "0s"
                    }
                  }
                ],
                "combined_validation_context": {
                  "default_validation_context": {
                    "verify_subject_alt_name": [
                      "spiffe://cluster.local/ns/bar/sa/default"
                    ]
                  },
                  "validation_context_sds_secret_config": {
                    "name": "ROOTCA",
                    "sds_config": {
                      "api_config_source": {
                        "api_type": "GRPC",
                        "grpc_services": [
                          {
                            "google_grpc": {
                              "target_uri": "unix:/var/run/sds/uds_path",
                              "channel_credentials": {
                                "local_credentials": {}
                              },
                              "call_credentials": [
                                {
                                  "from_plugin": {
                                    "name": "envoy.grpc_credentials.file_based_metadata",
                                    "typed_config": {
                                      "@type": "type.googleapis.com/envoy.config.grpc_credential.v2alpha.FileBasedMetadataConfig",
                                      "secret_data": {
                                        "filename": "/var/run/secrets/kubernetes.io/serviceaccount/token"
                                      },
                                      "header_key": "istio_sds_credentials_header-bin"
                                    }
                                  }
                                }
                              ],
                              "stat_prefix": "sdsstat",
                              "credentials_factory_name": "envoy.grpc_credentials.file_based_metadata"
                            }
                          }
                        ]
                      },
                      "initial_fetch_timeout": "0s"
                    }
                  }
                }
              },
              "sni": "outbound_.8000_._.httpbin.bar.svc.cluster.local"
            },
            "metadata": {
              "filter_metadata": {
                "istio": {
                  "config": "/apis/networking/v1alpha3/namespaces/istio-system/destination-rule/default"
                }
              }
            }
          },
          "last_updated": "2019-08-02T00:00:09.034Z"
        },
```
I believe this is the intended behavior, so it should be safe to close this issue if nobody has any other objections.

**Comment by vikramkhatri** [comment]
Hi - I am facing exact same issue and when I run my tea pot, it runs fine with mTLS MUTUAL. 

```
$ istioctl authn tls-check httpbin-v1-b9985cc7d-z8wvq.istio-lab httpbin.istio-lab.svc.cluster.local
HOST:PORT                                    STATUS     SERVER     CLIENT     AUTHN POLICY          DESTINATION RULE
httpbin.istio-lab.svc.cluster.local:8000     OK         mTLS       mTLS       default/istio-lab     httpbin/istio-lab
```

But, when I enable SDS ingress gateway for an external name to point to bookinfo `productpage` and try to access mTLS using SIMPLE, the browser shows same error:  `upstream connect error or disconnect/reset before headers. reset reason: connection failure`

My destination rule for the productpage is : `ISTIO_MUTUAL` and the gateway `tls` mode is `SIMPLE` for the external host connecting to the virtual service through Ingress gateway. This worked perfect fine in 1.1.6 and I then tested this in 1.2.2 where it does not seem to work.

The `istio-proxy` for `productpage` shows this line many times.
```
[2019-08-02 21:05:43.663][20][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:86] gRPC config stream closed: 13,
```

```
$ istioctl authn tls-check productpage-v1-8554d58bff-6j5qv.istio-lab productpage.istio-lab.svc.cluster.local
HOST:PORT                                        STATUS     SERVER     CLIENT     AUTHN POLICY          DESTINATION RULE
productpage.istio-lab.svc.cluster.local:9080     OK         mTLS       mTLS       default/istio-lab     productpage/istio-lab
```

`istio-proxy` log from ingress gateway.
```
[2019-08-02 20:48:04.864][21][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:86] gRPC config stream closed: 13,
```

```
$ istioctl authn tls-check istio-ingressgateway-7d74684457-rxqnz.istio-system productpage.istio-lab.svc.cluster.local
HOST:PORT                                        STATUS     SERVER     CLIENT     AUTHN POLICY          DESTINATION RULE
productpage.istio-lab.svc.cluster.local:9080     OK         mTLS       mTLS       default/istio-lab     productpage/istio-lab
```


Any tips - how to get this fixed?

**Comment by Monkeyanator** [comment]
At what point / with what specific configuration are you deploying your `Ingress Gateway`? Could you run `kubectl describe pod -n istio-system -l app=istio-egressgateway` and post the result?

**Comment by vikramkhatri** [comment]
Some more details are here:

## Gateway

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mygateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 443
      name: bookinfo
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: bookinfo-keys
    hosts:
    - bookinfo.istio.io
  - port:
      number: 443
      name: httpbin
      protocol: HTTPS
    tls:
      mode: MUTUAL
      credentialName: httpbin-keys
    hosts:
    - httpbin.istio.io
```

## Virtual Service

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - httpbin.istio.io
  gateways:
  - mygateway
  http:
  - match:
    - uri:
        prefix: /
    - uri:
        prefix: /status
    - uri:
        prefix: /delay
    route:
    - destination:
        host: httpbin.istio-lab.svc.cluster.local
        port:
          number: 8000
---
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - bookinfo.istio.io
  gateways:
  - mygateway
  http:
  - match:
    - uri:
        exact: /
    - uri:
        exact: /productpage
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage.istio-lab.svc.cluster.local
        port:
          number: 9080
```

## Destination rules
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: productpage
spec:
  host: productpage
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews
spec:
  host: reviews
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  - name: v3
    labels:
      version: v3
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ratings
spec:
  host: ratings
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  - name: v2-mysql
    labels:
      version: v2-mysql
  - name: v2-mysql-vm
    labels:
      version: v2-mysql-vm
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: details
spec:
  host: details
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
---
```

The mTLS for httpbin works from curl and browser after I add the client certificate to the Chrome.

The mTLS for bookinfo does not work at curl and in browser.

Everything is in a single VM for the test purpose and the names are defined in the `/etc/hosts`
```
192.168.142.249 bookinfo.istio.io
192.168.142.249 httpbin.istio.io
```

The curl for teapot works fine.

```
$ curl -HHost:httpbin.istio.io --resolve httpbin.istio.io:$INGRESS_PORT:$INGRESS_HOST --cacert $HOME/step/ca-chain.crt --cert $HOME/step/client.crt --key $HOME/step/client.key https://httpbin.istio.io/status/418

    -=[ teapot ]=-

       _...._
     .'  _ _ `.
    | ."` ^ `". _,
    \_;`"---"`|//
      |       ;/
      \_     _/
        `"""`
```

Also, I do not see conflict in mTLS using `istioctl authn tls-check` - the output is shown in previous step.
