### ISSUE TITLE
Job ttlSecondsAfterFinished is not working with Istio

### ISSUE THREAD

**Issue by aalmazanarbs** [istio/istio#15873]
Hi,
We are using Istio in our k8s cluster where we launch deployments and jobs. For jobs we need to use the k8s TTL Mechanism **ttlSecondsAfterFinished**. When we run jobs with Istio sidecar, the jobs are never clean up (Job and the pod associated are not unregistred automatically). If we run the same job without Istio sidecar the Job is unregistred successfully. We have communication between pods and jobs so

**Affected product area**

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Jobs must be unregistered automatically

**Steps to reproduce the bug**
Launch job with Istio and ttlSecondsAfterFinished

`kubectl apply -f job_with_istio_and_ttlSecondsAfterFinished.yml`

```
# job_with_istio_and_ttlSecondsAfterFinished.yml
apiVersion: batch/v1
kind: Job
metadata:
  name: pi-with-ttl
spec:
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
```
Job and pod are **not** unregistered

If launch the same job without Istio the job and pod **are** unregistered
```
# job_without_istio_and_ttlSecondsAfterFinished.yml
apiVersion: batch/v1
kind: Job
metadata:
  name: pi-with-ttl
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
```

**How was Istio installed?**
Strict mutual TLS

**Environment where bug was observed (cloud vendor, OS, etc)**
KOPS AWS
