### ISSUE TITLE
Service stops receive readiness prob requests from Kubernetes

### ISSUE THREAD

**Issue by illidan80** [istio/istio#15881]
**Bug description**

I have about 20 pods running on Kubernetes cluster. After about 3 days, they begin to refuse Readiness prob HTTP requests.

This is an example of "kubectl describe pod" output:

` Warning  Unhealthy  4m41s (x104971 over 4d21h)  kubelet, digi  (combined from similar events): Readiness probe failed: Get http://10.1.1.139:8080/v1/readiness: read tcp 10.1.1.1:35178->10.1.1.139:8080: read: connection reset by peer`

Output of same pod after few minutes:

`Warning  Unhealthy  2m32s (x105570 over 4d21h)  kubelet, digi  (combined from similar events): Readiness probe failed: Get http://10.1.1.139:8080/v1/readiness: read tcp 10.1.1.1:35028->10.1.1.139:8080: read: connection reset by peer`

Seems like process itself inside container is not aware about any issues. Logs look just normally. If I opening ssh into container (e.g. "kubectl exec -it") - **I do able to perform http call to the readiness URL (curl on localhost)** - so the issue is only when making requests from the outside, which makes me thinks it somehow related to networking --> Istio.

Trying to make readiness request from another pod fails as well with the following output:

` curl 10.1.1.139:8080/v1/readiness -v
Trying 10.1.1.139...
TCP_NODELAY set
Connected to 10.1.1.139 (10.1.1.139) port 8080 (#0)
GET /v1/readiness HTTP/1.1
Host: 10.1.1.139:8080
User-Agent: curl/7.58.0
Accept: */*
HTTP/1.1 503 Service Unavailable
content-length: 95
content-type: text/plain
date: Sun, 28 Jul 2019 10:48:37 GMT
server: envoy
Connection #0 to host 10.1.1.139 left intact
upstream connect error or disconnect/reset before headers. reset reason: connection termination`

There is no restarts nor on my pods nor on Istio pods.

Deleting pod (which causing Kubernetes to recreate it) will solve the issue, for about next 3 days. After that, the issue starts over again.

Mutual TLS is **not** enabled.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Readiness probs will work as intended

**Steps to reproduce the bug**
I not doing anything special... Running pod on Kubernetes with http readiness prob enabled.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
I was able to reproduce this issue in the following platforms / versions:
Istio: 1.1.1 / 1.1.8/ 1.2.2
Kubernetes: 1.12 / 1.13 / 1.15
Platform: AWS EKS / local Microk8s

**How was Istio installed?**
Using "Helm template" option

**Environment where bug was observed (cloud vendor, OS, etc)**
on cloud: AWS EKS \ on local: Ubuntu 18.04.02

**Comment by hzxuzhonghu** [comment]
Did you set `sidecarInjectorWebhook.rewriteAppHTTPProbe` ? I just noticed it is still disabled by default.

**Comment by hzxuzhonghu** [comment]
@incfly I think it's time to enable it by default

**Comment by illidan80** [comment]
@hzxuzhonghu: I start to experience issues with readiness checks only after running a while (about 3 days). Could you please elaborate how disabled "sidecarInjectorWebhook.rewriteAppHTTPProbe" can cause such behavior?

**Comment by hzxuzhonghu** [comment]
>BTW, I want to point your attention that I not using mutual TLS

OK, then it is not this cause.  


Check your inbound xds configuration then.

**Comment by illidan80** [comment]
@hzxuzhonghu Appreciate your help, but could you please explain how whatsoever configuration may lead to such inconsistent behavior, as described above (e.g. everything works during few days, after that begin to reject requests from time to time)?

**Comment by hzxuzhonghu** [comment]
Inbound listener、 cluster with the probe port

**Comment by illidan80** [comment]
Update: I disabled sidecar injection on one of the environments (which was previously having the issue). All pods are running already for 5.5 days - without any problem.

Looks like indeed there is some issue related to the Istio sidecar...

Anyone has ideas?

**Comment by crhuber** [comment]
We are also experiencing similar issue

**Comment by illidan80** [comment]
@crhuber: do you have any progress on this?

**Comment by duderino** [comment]
@incfly any ideas?

**Comment by incfly** [comment]
Without taking a look of the Envoy configuration dump and the Pod/Deployment YAML, I have a very random guess.

1. The application port is declared as TCP, even though the prober is a HTTP request.
2. Kubelet ---(http) ---> Envoy --(TCP_PROXY) --> App.
3. Every HTTP prober request establishes a new TCP connection.
4. The app itself does not close the socket correspondingly.
5. App runs out of the socket available.

From a past incident, a customer reports many `CLOSE_WAIT` socket is hanging on the app pod. I think if we ensure the inbound cluster is configured as `http_connection_manager`, that might solve the issue.

Can you check your corresponding service port is named as `http.*` per [istio port name convention](https://istio.io/docs/setup/kubernetes/additional-setup/requirements/)?

**Comment by illidan80** [comment]
@incfly Hi, first - thank you for your effort helping on this.

Here is a deployment yaml ("obfuscated") of one of the trouble makers:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-xxx
  namespace: product  
spec:
  selector:
    matchLabels:
      app: xxx
  replicas: {{.Values.replicas}}
  template:
    metadata:
      labels:
        app: xxx
        kind: deployment
        version: "{{.Values.service.docker.image.version}}"
        context: "{{.Values.context}}"
    spec:
      serviceAccountName: xxx
      volumes:
        - name: volume1
          secret:
            secretName: secret1
        - name: volume2
          secret:
            secretName: secret2
      containers:
        - name: container-xxx
          image: {{.Values.service.docker.imageRegistry}}/xxx:{{.Values.service.docker.image.version}}
          ports:
            - containerPort: 8080
            - containerPort: 5005
          volumeMounts:
            - name: volume1
              mountPath: "/secrets/secret1"
              subPath: secret1
              readOnly: true
            - name: volume2
              mountPath: "/secrets/secret2"
              subPath: secret2
              readOnly: true
          readinessProbe:
            httpGet:
              path: /v1/readiness
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 1
```

...and a corresponding service yaml:

```
kind: Service
apiVersion: v1
metadata:
  name: xxx
  namespace: product
spec:
  selector:
    app: xxx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
```


Yes, you are right. Indeed, we declaring TCP. But I would expect it will either work always or work never . How it can work for about 3 days, and then stop working?
