### ISSUE TITLE
Conversion ip_address into string by CEXL

### ISSUE THREAD

**Issue by odg0318** [istio/istio#15890]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Conversion ip_address to string by CEXL in log entry template.

**Describe alternatives you've considered**
CEXL supports string() function 

The following configuration includes `source.ip` and `destination.ip` for logentry template.
`ip_address` type is internally implemented using `[]byte` in golang.
When some logs are sent to fluentd adapter, `ip_address` type is shown using not `string` but byte code.

I could not find a way to convert `ip_address` to `string` using CEXL.

In case of `stdio` mixer adapter, `.String()` function is used in code level as below.
https://github.com/istio/istio/blob/master/mixer/adapter/stdio/stdio.go#L131

```
apiVersion: config.istio.io/v1alpha2
kind: instance
metadata:
  name: stdio-instance
  namespace: istio-system
spec:
  compiledTemplate: logentry
  params:
    severity: '"warning"'
    timestamp: request.time
    variables:
      source_ip: source.ip
      destination_ip: destination.ip
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ X ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
