### ISSUE TITLE
Intermediate issues reaching the k8s api from an mtls pod.

### ISSUE THREAD

**Issue by JoelDamata-pcc** [istio/istio#15898]
**Bug description**
In one of our applications we use leader-election. Seemingly randomly the leader-election side-car started receiving TLS connection issues to https://kubernetes.default.svc.cluster.local. I have mtls enabled and a destinationrule for the k8s service allowing non-mtls connections which works except for this situation.

```yaml
    apiVersion: networking.istio.io/v1alpha3
    kind: DestinationRule
    metadata:
      name: "api-server"
      namespace: istio-system
      labels:
        app: security
        chart: security
        heritage: Tiller
        release: istio
    spec:
      host: "kubernetes.default.svc.cluster.local"
      trafficPolicy:
        tls:
          mode: DISABLE
```

Log from leader election 
```
E0611 07:14:19.289107       7 leaderelection.go:253] error retrieving endpoint: Get https://172.20.0.1:443/api/v1/namespaces/default/endpoints/bleh.bleh: read tcp 10.159.96.111:42412->172.20.0.1:443: read: connection reset by peer
E0611 07:14:34.508161       7 leaderelection.go:253] error retrieving endpoint: Get https://172.20.0.1:443/api/v1/namespaces/default/endpoints/bleh.bleh: net/http: TLS handshake timeout
```

This has happened twice. The first time I resolved this by removing and readding the api-server destinationrule. The second time I resolved this by just restarting the pods.

When this happens, it affects all pods in the istio-mesh. 

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

telemetry version: version.BuildInfo{Version:"1.1.8", GitRevision:"145b18a441045d6fad33d7916380d8642c7bf21d-dirty", User:"root", Host:"11387264-87af-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.7-14-g145b18a"}

Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
helm

**Environment where bug was observed (cloud vendor, OS, etc)**
EKS
