### ISSUE TITLE
Operator: incorrect hpa scale target ref 

### ISSUE THREAD

**Issue by morvencao** [istio/istio#15918]
Currently incorrect hpa scale target ref is generated for `default` `minimal` and `sds` profiles:

```
# make mesh
# mesh manifest generate
```
then you will find the hpa for policy and telemetry have incorrect scale target ref:

```
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: istio-policy
    release: istio
  name: istio-policy
  namespace: istio-policy
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istio-pilot
```
