### ISSUE TITLE
Error fetching Grafana Info., Error: [ grafana URL is not set in Kiali configuration ]

### ISSUE THREAD

**Issue by winds6206** [istio/istio#15977]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
I installed istio as below step, I use port-forward let my host can connect kiali.
After I login kiali, the screen pop up `Error fetching Grafana Info., Error: [ grafana URL is not set in Kiali configuration ]`

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Kiali can fetch grafana in order

**Steps to reproduce the bug**
```
curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.2.2 sh -

cd istio-1.2.2

export PATH=$PWD/bin:$PATH

for i in install/kubernetes/helm/istio-init/files/crd*yaml; do kubectl apply -f $i; done

kubectl apply -f install/kubernetes/istio-demo.yaml

kubectl -n istio-system port-forward $(kubectl -n istio-system get pod -l app=kiali -o jsonpath='{.items[0].metadata.name}') 20001:20001 --address 0.0.0.0
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istioctl version
```
client version: 1.2.2
citadel version: 1.2.2
egressgateway version: 1.2.2
galley version: 1.2.2
ingressgateway version: 1.2.2
pilot version: 1.2.2
policy version: 1.2.2
sidecar-injector version: 1.2.2
telemetry version: 1.2.2
```

kubectl version
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

My step
```
curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.2.2 sh -

cd istio-1.2.2

export PATH=$PWD/bin:$PATH

for i in install/kubernetes/helm/istio-init/files/crd*yaml; do kubectl apply -f $i; done

kubectl apply -f install/kubernetes/istio-demo.yaml
```

**Environment where bug was observed (cloud vendor, OS, etc)**
Kubernetes install on CentOS

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
I can reproduce this. @clyang82 I think you update kiali recently, is this in 1.2?

@jmazzitelli

**Comment by jmazzitelli** [comment]
What does the kiali configmap look like? Should have something like this:

```
external_services:
  grafana:
    in_cluster_url: "http://grafana.istio-system:3000"
    url: "<the URL here>"
```

This URL is set in the kiali values.yaml:

https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/kiali/values.yaml#L53

**Comment by howardjohn** [comment]
Its not set though. The configmap just looks like

```
      grafana:
        url: {{ .Values.dashboard.grafanaURL }}
```

We don't set in_cluster_url it seems. Does it default to `http://grafana.istio-system:3000`?

**Comment by winds6206** [comment]
I try to these ways as below, but it is still pop up the same message

### First method

**use helm to install**
```
helm template \
    --set kiali.enabled=true \
    install/kubernetes/helm/istio \
    --name istio --namespace istio-system > $HOME/istio.yaml
```

or

```
helm template \
    --set kiali.enabled=true \
    --set "kiali.dashboard.grafanaURL=http://grafana:3000" \
    install/kubernetes/helm/istio \
    --name istio --namespace istio-system > $HOME/istio.yaml
```

or


```
helm template \
    --set kiali.enabled=true \
    --set "kiali.dashboard.grafanaURL=http://grafana.istio-system:3000" \
    install/kubernetes/helm/istio \
    --name istio --namespace istio-system > $HOME/istio.yaml
```

### Second method
**modify configmap.yaml**
```
external_services:
  grafana:
    in_cluster_url: "http://grafana.istio-system:3000"
    url: {{ .Values.dashboard.grafanaURL }}
```
and
```
external_services:
  grafana:
    in_cluster_url: "http://grafana:3000"
    url: {{ .Values.dashboard.grafanaURL }}
```

then use `kubectl apply -f install/kubernetes/istio-demo.yaml` to apply separately

### Third method

**modify value.yaml**

```
dashboard:
  secretName: kiali 
  viewOnlyMode: false # Bind the service account to a role with only read access
  grafanaURL: http://grafana.istio-system:3000
```

and

```
dashboard:
  secretName: kiali 
  viewOnlyMode: false # Bind the service account to a role with only read access
  grafanaURL: http://grafana:3000
```

then use `kubectl apply -f install/kubernetes/istio-demo.yaml` to apply separately
