### ISSUE TITLE
istio-sidecar-injector Injection error. version 1.2.3

### ISSUE THREAD

**Issue by yangpeng14** [istio/istio#16072]
1.  helm  version
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}

2. kubectl  version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

3. Injection reported the following error

```yaml
2019-08-06T09:03:45.576056Z	warn	Failed to unmarshall template error converting YAML to JSON: yaml: line 14: found unknown escape character rewriteAppHTTPProbe: true
initContainers:

- name: istio-init
  image: "docker.io/istio/proxy_init:1.2.3"
  args:
  - "-p"
  - "15001"
  - "-u"
  - 1337
  - "-m"
  - "REDIRECT"
  - "-i"
  - "192.168.16.0/20\,192.168.32.0/20"
  - "-x"
  - ""
  - "-b"
  - "80"
  - "-d"
  - "15020"
  imagePullPolicy: "IfNotPresent"
  resources:
    requests:
      cpu: 10m
      memory: 10Mi
    limits:
      cpu: 100m
      memory: 50Mi
  securityContext:
    runAsUser: 0
    runAsNonRoot: false
    capabilities:
      add:
      - NET_ADMIN
  restartPolicy: Always
  env:

containers:
- name: istio-proxy
  image: "docker.io/istio/proxyv2:1.2.3"
  ports:
  - containerPort: 15090
    protocol: TCP
    name: http-envoy-prom
  args:
  - proxy
  - sidecar
  - --domain
  - $(POD_NAMESPACE).svc.cluster.local
  - --configPath
  - "/etc/istio/proxy"
  - --binaryPath
  - "/usr/local/bin/envoy"
  - --serviceCluster
  - "demo1.$(POD_NAMESPACE)"
  - --drainDuration
  - "45s"
  - --parentShutdownDuration
  - "1m0s"
  - --discoveryAddress
  - "istio-pilot.istio-system:15010"
  - --zipkinAddress
  - "zipkin.istio-system:9411"
  - --dnsRefreshRate
  - 300s
  - --connectTimeout
  - "10s"
  - --proxyAdminPort
  - "15000"
  - --concurrency
  - "2"
  - --controlPlaneAuthPolicy
  - "NONE"
  - --statusPort
  - "15020"
  - --applicationPorts
  - "80"
  env:
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: POD_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  - name: INSTANCE_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP

  - name: ISTIO_META_POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: ISTIO_META_CONFIG_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  - name: ISTIO_META_INTERCEPTION_MODE
    value: "REDIRECT"
  - name: ISTIO_META_INCLUDE_INBOUND_PORTS
    value: "80"

  - name: ISTIO_METAJSON_ANNOTATIONS
    value: |
           {"sidecar.istio.io/inject":"true"}


  - name: ISTIO_METAJSON_LABELS
    value: |
           {"app":"demo1"}

  imagePullPolicy: IfNotPresent

  readinessProbe:
    httpGet:
      path: /healthz/ready
      port: 15020
    initialDelaySeconds: 1
    periodSeconds: 2
    failureThreshold: 30
  securityContext:
    readOnlyRootFilesystem: true

    runAsUser: 1337
  resources:

    limits:
      cpu: 400m
      memory: 500Mi
    requests:
      cpu: 30m
      memory: 50Mi

  volumeMounts:

  - mountPath: /etc/istio/proxy
    name: istio-envoy
  - mountPath: /etc/certs/
    name: istio-certs
    readOnly: true
volumes:
- emptyDir:
    medium: Memory
  name: istio-envoy
- name: istio-certs
  secret:
    optional: true

    secretName: istio.default

Error: error converting YAML to JSON: yaml: line 14: found unknown escape character
```
