### ISSUE TITLE
Trigger Rules not working as expected

### ISSUE THREAD

**Issue by paulfrench** [istio/istio#16099]
Istio 1.2.2
Kubernetes 1.14.3
Docker for windows (windows 10)

I'm applying a policy to a service. I want jwt authentication to only apply to certain paths

The below works fine, any path starting with  /base/jclient/remoting gives me "Origin authentication failed" as expected

```
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: jm-cc-service
spec:
  targets:
  - name: jm-cc-service
  peers:
  - mtls: {}
  origins:
  - jwt:
      issuer: "https://oneadvanced-jm.eu.auth0.com/"
      jwksUri: "https://oneadvanced-jm.eu.auth0.com/.well-known/jwks.json"
      trigger_rules:
      - included_paths:
        - prefix: /base/jclient/remoting
  principalBinding: USE_ORIGIN
```

However I want to exclude the path /base/jclient/remoting/validateInstall so I simply amend to...

```
  ...
  origins:
  - jwt:
      issuer: "https://oneadvanced-jm.eu.auth0.com/"
      jwksUri: "https://oneadvanced-jm.eu.auth0.com/.well-known/jwks.json"
      trigger_rules:
      - excluded_paths: 
        - prefix: /base/jclient/remoting/validateInstall
      - included_paths:
        - prefix: /base/jclient/remoting/
  principalBinding: USE_ORIGIN
```

Now all paths are being authenticated e.g. /base/jclient also gives "Origin authentication failed". I have waited several minutes and more to ensure the policy has been applied. I want the same behaviour as given in the documentation at..

https://istio.io/docs/reference/config/istio.authentication.v1alpha1/#Jwt

"A JWT only for requests at path of prefix /status/ but except the path of /status/version. This means for any request path with prefix /status/ except /status/version will require a valid JWT to proceed."

```
issuer: https://example.com
jwks_uri: https://example.com/.well-known/jwks.json
trigger_rules:
- excluded_paths:
  - exact: /status/version
  included_paths:
  - prefix: /status/
```

I do not get this behaviour??

**Comment by paulfrench** [comment]
This works as expected, I can call /base/jclient/remoting/validateInstall
```
...
  origins:
  - jwt:
      issuer: "https://oneadvanced-jm.eu.auth0.com/"
      jwksUri: "https://oneadvanced-jm.eu.auth0.com/.well-known/jwks.json"
      trigger_rules:
      - excluded_paths: 
        - exact: /base/jclient/remoting/validateInstall
      - included_paths:
        - exact: /base/jclient/remoting/
  principalBinding: USE_ORIGIN
```
...but is not what I want. If I now put to what I require...
```
...
  origins:
  - jwt:
      issuer: "https://oneadvanced-jm.eu.auth0.com/"
      jwksUri: "https://oneadvanced-jm.eu.auth0.com/.well-known/jwks.json"
      trigger_rules:
      - excluded_paths: 
        - exact: /base/jclient/remoting/validateInstall
      - included_paths:
        - prefix: /base/jclient/remoting/
  principalBinding: USE_ORIGIN
```
...I can no longer call /base/jclient/remoting/validateInstall, I get a 401

**Comment by paulfrench** [comment]
More strange behavior the following 2 paths are treated differently

/base/jclient/remoting
/base/jclient/remoting/

If I use one of these paths as an included_path then the other path is accessible

**Comment by tx19980520** [comment]
The same strange behavior
jwt-boostrap.yaml
```yaml
- jwt:
      issuer: "ccc"
      jwksUri: "ccc"
      jwt_headers:
      - "key"
      trigger_rules:
      - excluded_paths:
        - exact: /api/base_register
        - exact: /actuator/health
        - exact: /api/search_case
        - exact: /api/passive_register
  principalBinding: USE_ORIGIN
```
the `/api/base_register` is work but other not work(always get 401)
@paulfrench Have you solved the problem?
