### ISSUE TITLE
Gateway does not register port 443 if another gateway does with the same hosts

### ISSUE THREAD

**Issue by nesl247** [istio/istio#16107]
**Bug description**

I have 2 `Gateway` objects, one for external and one for internal traffic. Both of these are set to `*` for the hosts on both port 80 and 443. With this configuration, only a port 80 is listened on for the `external` `IngressGateway`. On the internal one, 443 is also listened to.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  labels:
    app.kubernetes.io/managed-by: pulumi
  name: gateway-external
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - '*'
    port:
      name: https-external
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
```

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  labels:
    app.kubernetes.io/managed-by: pulumi
  name: gateway-internal
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway-internal
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - '*'
    port:
      name: https-internal
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
```

```
# external
❯ istioctl proxy-config listeners istio-ingressgateway-6c77f9bfb4-87zp2.istio-system
ADDRESS     PORT      TYPE
0.0.0.0     80        HTTP
0.0.0.0     15090     HTTP

# internal
❯ istioctl proxy-config listeners istio-ingressgateway-internal-64cb95ddf9-6rpcv.istio-system
ADDRESS     PORT      TYPE
0.0.0.0     443       HTTP
0.0.0.0     80        HTTP
0.0.0.0     15090     HTTP
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Port 443 should be listened on in both gateways.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```
client version: 1.2.3
cluster-local-gateway version:
cluster-local-gateway version:
citadel version: cba9054abf594acf792a985393ade7f2304a9e17
galley version: cba9054abf594acf792a985393ade7f2304a9e17
ingressgateway version: cba9054abf594acf792a985393ade7f2304a9e17
ingressgateway-internal version:
pilot version: cba9054abf594acf792a985393ade7f2304a9e17
policy version: cba9054abf594acf792a985393ade7f2304a9e17
sidecar-injector version: cba9054abf594acf792a985393ade7f2304a9e17
telemetry version: cba9054abf594acf792a985393ade7f2304a9e17
```

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T16:54:35Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.8", GitCommit:"7d3d6f113e933ed1b44b78dff4baf649258415e5", GitTreeState:"clean", BuildDate:"2019-06-19T16:37:16Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
GKE Istio Addon

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE
