### ISSUE TITLE
rewriteAppHTTPProbers Annotation Does Not Seem to Work

### ISSUE THREAD

**Issue by kbruner** [istio/istio#16110]
**Bug description**

Adding the `sidecar.istio.io/rewriteAppHTTPProbers: "true"` does not actually make health checks on services with mTLS enforcement on work.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Adding the annotation and bouncing pods should make HTTP-based liveness and readiness probes work.

**Steps to reproduce the bug**

```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
        version: v1
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
      - name: helloworld
        image: istio/examples-helloworld-v1
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 6
          successThreshold: 1
```

Resulting pod:

```
Name:           helloworld-v1-74d55cf7-zb746
Namespace:      default
Priority:       0
Node:           gke-gimme-pool-1-c01949a6-h7kr/10.0.0.5
Start Time:     Wed, 07 Aug 2019 13:48:35 -0700
Labels:         app=helloworld
                pod-template-hash=74d55cf7
                version=v1
Annotations:    cni.projectcalico.org/podIP: 10.8.3.48/32
                sidecar.istio.io/rewriteAppHTTPProbers: true
                sidecar.istio.io/status:
                  {"version":"761ebc5a63976754715f22fcf548f05270fb4b8db07324894aebdb31fa81d960","initContainers":["istio-init"],"containers":["istio-proxy"]...
Status:         Running
IP:             10.8.3.48
Controlled By:  ReplicaSet/helloworld-v1-74d55cf7
Init Containers:
  istio-init:
    Container ID:  docker://84675652e0a90f612155686588477010eae9f6b44455d55268557effc6bbb829
    Image:         docker.io/istio/proxy_init:1.2.2
    Image ID:      docker-pullable://istio/proxy_init@sha256:d291e6d584c86ed8a62d0936943082790b71dcb4fcc18dd4a6e2d31ca908b522
    Port:          <none>
    Host Port:     <none>
    Args:
      -p
      15001
      -u
      1337
      -m
      REDIRECT
      -i
      *
      -x
      
      -b
      5000
      -d
      
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 07 Aug 2019 13:48:36 -0700
      Finished:     Wed, 07 Aug 2019 13:48:38 -0700
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  50Mi
    Requests:
      cpu:        10m
      memory:     10Mi
    Environment:  <none>
    Mounts:       <none>
Containers:
  helloworld:
    Container ID:   docker://485404b652c41738f8504124848edf16ad4bc54fb9357571896b6b91a60de618
    Image:          istio/examples-helloworld-v1
    Image ID:       docker-pullable://istio/examples-helloworld-v1@sha256:c671702b11cbcda103720c2bd3e81a4211012bfef085b7326bb7fbfd8cea4a94
    Port:           5000/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Wed, 07 Aug 2019 13:48:38 -0700
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:        100m
    Liveness:     http-get http://:5000/ delay=6s timeout=2s period=5s #success=1 #failure=6
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-q8tm7 (ro)
  istio-proxy:
    Container ID:  docker://8826edf656f23341e82af6a311a0b2406f38897cc7f5b3069581ac6e3a4c2248
    Image:         docker.io/istio/proxyv2:1.2.2
    Image ID:      docker-pullable://istio/proxyv2@sha256:236527816ff67f8492d7286775e09c28e207aee2f6f3c3d9258cd2248af4afa5
    Port:          15090/TCP
    Host Port:     0/TCP
    Args:
      proxy
      sidecar
      --domain
      $(POD_NAMESPACE).svc.cluster.local
      --configPath
      /etc/istio/proxy
      --binaryPath
      /usr/local/bin/envoy
      --serviceCluster
      helloworld.$(POD_NAMESPACE)
      --drainDuration
      45s
      --parentShutdownDuration
      1m0s
      --discoveryAddress
      istio-pilot.istio-system:15010
      --zipkinAddress
      zipkin.istio-system:9411
      --dnsRefreshRate
      300s
      --connectTimeout
      10s
      --proxyAdminPort
      15000
      --concurrency
      2
      --controlPlaneAuthPolicy
      NONE
    State:          Running
      Started:      Wed, 07 Aug 2019 13:48:39 -0700
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:     100m
      memory:  128Mi
    Environment:
      POD_NAME:                          helloworld-v1-74d55cf7-zb746 (v1:metadata.name)
      POD_NAMESPACE:                     default (v1:metadata.namespace)
      INSTANCE_IP:                        (v1:status.podIP)
      ISTIO_META_POD_NAME:               helloworld-v1-74d55cf7-zb746 (v1:metadata.name)
      ISTIO_META_CONFIG_NAMESPACE:       default (v1:metadata.namespace)
      ISTIO_META_INTERCEPTION_MODE:      REDIRECT
      ISTIO_META_INCLUDE_INBOUND_PORTS:  5000
      ISTIO_METAJSON_ANNOTATIONS:        {"sidecar.istio.io/rewriteAppHTTPProbers":"true"}
                                         
      ISTIO_METAJSON_LABELS:             {"app":"helloworld","pod-template-hash":"74d55cf7","version":"v1"}
                                         
      ISTIO_KUBE_APP_PROBERS:            {"/app-health/helloworld/livez":{"path":"/","port":5000,"scheme":"HTTP"}}
    Mounts:
      /etc/istio/proxy from istio-envoy (rw)
      /var/run/sds from sds-uds-path (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-q8tm7 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  default-token-q8tm7:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-q8tm7
    Optional:    false
  istio-envoy:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  sds-uds-path:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/sds
    HostPathType:  
QoS Class:         Burstable
Node-Selectors:    <none>
Tolerations:       node.kubernetes.io/not-ready:NoExecute for 300s
                   node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age   From                                     Message
  ----     ------     ----  ----                                     -------
  Normal   Scheduled  37s   default-scheduler                        Successfully assigned default/helloworld-v1-74d55cf7-zb746 to gke-gimme-pool-1-c01949a6-h7kr
  Normal   Pulled     36s   kubelet, gke-gimme-pool-1-c01949a6-h7kr  Container image "docker.io/istio/proxy_init:1.2.2" already present on machine
  Normal   Created    36s   kubelet, gke-gimme-pool-1-c01949a6-h7kr  Created container
  Normal   Started    36s   kubelet, gke-gimme-pool-1-c01949a6-h7kr  Started container
  Normal   Pulled     34s   kubelet, gke-gimme-pool-1-c01949a6-h7kr  Container image "istio/examples-helloworld-v1" already present on machine
  Normal   Created    34s   kubelet, gke-gimme-pool-1-c01949a6-h7kr  Created container
  Normal   Started    34s   kubelet, gke-gimme-pool-1-c01949a6-h7kr  Started container
  Normal   Pulled     34s   kubelet, gke-gimme-pool-1-c01949a6-h7kr  Container image "docker.io/istio/proxyv2:1.2.2" already present on machine
  Normal   Created    34s   kubelet, gke-gimme-pool-1-c01949a6-h7kr  Created container
  Normal   Started    33s   kubelet, gke-gimme-pool-1-c01949a6-h7kr  Started container
  Warning  Unhealthy  28s   kubelet, gke-gimme-pool-1-c01949a6-h7kr  Liveness probe failed: Get http://10.8.3.48:5000/: read tcp 10.0.0.5:35452->10.8.3.48:5000: read: connection reset by peer
  Warning  Unhealthy  23s   kubelet, gke-gimme-pool-1-c01949a6-h7kr  Liveness probe failed: Get http://10.8.3.48:5000/: read tcp 10.0.0.5:35480->10.8.3.48:5000: read: connection reset by peer
  Warning  Unhealthy  18s   kubelet, gke-gimme-pool-1-c01949a6-h7kr  Liveness probe failed: Get http://10.8.3.48:5000/: read tcp 10.0.0.5:35498->10.8.3.48:5000: read: connection reset by peer
  Warning  Unhealthy  13s   kubelet, gke-gimme-pool-1-c01949a6-h7kr  Liveness probe failed: Get http://10.8.3.48:5000/: read tcp 10.0.0.5:35526->10.8.3.48:5000: read: connection reset by peer
  Warning  Unhealthy  8s    kubelet, gke-gimme-pool-1-c01949a6-h7kr  Liveness probe failed: Get http://10.8.3.48:5000/: read tcp 10.0.0.5:35548->10.8.3.48:5000: read: connection reset by peer
  Warning  Unhealthy  3s    kubelet, gke-gimme-pool-1-c01949a6-h7kr  Liveness probe failed: Get http://10.8.3.48:5000/: read tcp 10.0.0.5:35576->10.8.3.48:5000: read: connection reset by peer
```

The container will fail the health check and bounce repeatedly.  The deployment will function normally if the probe is removed from the spec, or if a `DestinationRule` downgrading mTLS enforcement is added.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```
$ istioctl version --remote
client version: 1.2.0
citadel version: 1.2.2
egressgateway version: 1.2.2
galley version: 1.2.2
ingressgateway version: 1.2.2
nodeagent version:
nodeagent version:
nodeagent version:
pilot version: 1.2.2
pilot version: 1.2.2
policy version: 1.2.2
policy version: 1.2.2
sidecar-injector version: 1.2.2
sidecar-injector version: 1.2.2
telemetry version: 1.2.2
telemetry version: 1.2.2
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-gke.10", GitCommit:"f53039cc1e5295eed20969a4f10fb6ad99461e37", GitTreeState:"clean", BuildDate:"2019-06-19T20:48:40Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

```
helm template install/kubernetes/helm/istio --name istio
        --namespace istio-system \
        --set gateways.istio-egressgateway.enabled=true \
        --set global.disablePolicyChecks=false \
        --set global.mtls.enabled=true \
        --set global.outboundTrafficPolicy.mode=REGISTRY_ONLY \
        --set global.proxy.accessLogFile=/dev/stdout \
        --set global.proxy.statusPort=0 \
        --set grafana.enabled=true \
        --set kiali.createDemoSecret=true \
        --set kiali.dashboard.grafanaURL=http://grafana.istio-system.svc.cluster.local:3000 \
        --set kiali.dashboard.jaegerURL=http://jaeger.istio-system.svc.cluster.local:80 \
        --set kiali.enabled=true \
        --set mixer.adapters.stdio.enabled=true \
        --set mixer.policy.autoscaleMin=2 \
        --set mixer.telemetry.autoscaleMin=2 \
        --set pilot.autoscaleMin=2 \
        --set sidecarInjectorWebhook.enableNamespacesByDefault=true \
        --set sidecarInjectorWebhook.replicaCount=2 \
        --set sidecarInjectorWebhook.rewriteAppHTTPProbe=false \
        --set tracing.enabled=true \
        --set gateways.istio-ingressgateway.autoscaleMin=2 \
        --set gateways.istio-ingressgateway.enabled=true \
        --values install/kubernetes/helm/istio/values-istio-sds-auth.yaml \
        --set gateways.istio-ingressgateway.sds.enabled=true
```

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE, Ubuntu node image

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by incfly** [comment]
Are you using auto injection or istioctl kube-inject?

**Comment by kbruner** [comment]
Auto injection @incfly

**Comment by incfly** [comment]
I can't reproduce it. I'm using 1.2.2 and default `istio-demo.yaml` installation. I'm using the same deployment YAML you're using.

I see the injected pod having the expected podSpec liveness probes rewritten, as

```yaml
spec:                                           
  containers:                          
  - image: istio/examples-helloworld-v1 
    imagePullPolicy: IfNotPresent                             
    livenessProbe:                          
      failureThreshold: 6                           
      httpGet:                         
        path: /app-health/helloworld/livez                                                                                                    
        port: 15020                                           
        scheme: HTTP                                                                                                                          
      initialDelaySeconds: 5            
      periodSeconds: 5                                                      
      successThreshold: 1                                                                 
      timeoutSeconds: 2                                                                 
    name: helloworld                                                                                                               
    ports:                           
    - containerPort: 5000              
      protocol: TCP                                                                           
    resources:                         
      requests:                                                                                                                               
        cpu: 100m                
    terminationMessagePath: /dev/termination-log                                                                                              
    terminationMessagePolicy: File     
    volumeMounts:                       
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-cqlhk             
      readOnly: true    
```
