### ISSUE TITLE
Gateway definition has warning "more than one gateway for the same host port combination"

### ISSUE THREAD

**Issue by selcukusta** [istio/istio#16158]
Helm Version:

```
Client: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
```

Kubectl version:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T14:25:20Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:41:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

I have a domain like `example.com` and has multiple subdomains such as `api.example.com`, `sysmon.example.com`, `logs.example.com` etc.

When I define the Gateway and VirtualServices as below, I'm getting this warning: `more than one gateway for the same host port combination`

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-own-gw
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "example.com"
    - "*.example.com"
    port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - "example.com"
    - "*.example.com"
    port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
```
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-own-vs
spec:
  hosts:
  - "example.com"
  gateways:
  - my-own-gw
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: ui
        port:
          number: 80
```
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-another-vs
spec:
  hosts:
  - "api.example.com"
  gateways:
  - my-own-gw
  http:
  - match:
    - uri:
        prefix: /user/
    rewrite:
      uri: /
    route:
    - destination:
        host: user-api
        port:
          number: 80
  - match:
    - uri:
        prefix: /address/
    rewrite:
      uri: /
    route:
    - destination:
        host: address-api
        port:
          number: 80
```
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-another-2-vs
spec:
  hosts:
  - "sysmon.example.com"
  gateways:
  - my-own-gw
  http:
  - match:
    - uri:
        prefix: /kibana/
    rewrite:
      uri: /
    route:
    - destination:
        host: kibana
        port:
          number: 80
```

I'm following [these](https://istio.io/docs/tasks/traffic-management/ingress/ingress-control/#troubleshooting) steps but I couldn't find anything.

`kubectl get ingress --all-namespaces` 

```
No resources found.
```

`kubectl get gateway --all-namespaces`

```
NAMESPACE   NAME             AGE
default     my-own-gw   1d
```

Traffic management doesn't have any issue and routing is completed successfully but I'm wondering what's the problem on the definition.
