### ISSUE TITLE
HTTPRoute queryParams seem to always return true

### ISSUE THREAD

**Issue by nfons** [istio/istio#16165]
**Bug description**

I have a simple routing in a virtual service that does the following:

if queryparam `?apikey` AND route = "/" go do service A,

if just route "/" go to service B.

**Steps to reproduce the bug**
This is done via:

```
 - match:
        - queryParams:
            apikey:
              exact: version2
          uri:
            prefix: /
      route:
        - destination:
            host: dash-svc
            port:
              number: 80
  ....

-    match:
        - uri:
            prefix: /
      route:
        - destination:
            host: oauth2-proxy-ui
            port:
              number: 80
```

(please disregard spacing, might be a C+P issue).

EXPECTED:
 navigating to "http://myhost.com" => oauth2-proxy

"http://myhost.com?apikey=version2" => dash-svc

HOWEVER, currently navigating to `myhost.com` will ALWAYS result in dash-svc.

modifying JUST the `queryParams` to `headers` will have the correct outcome. so it seems queryParams is always validating

**Affected product area (please put an X in all that apply)**

[x ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.22 k8s: 1.13
**How was Istio installed?**
helm
**Environment where bug was observed (cloud vendor, OS, etc)**
GKE
Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by nfons** [comment]
```
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: bookinfo
spec:
  hosts:
    - '*'
  gateways:
    - bookinfo-gateway
  http:
    - match:
        - queryParams:
            apiKey:
              exact: test
      rewrite:
        uri: /productpage
      route:
        - destination:
            host: productpage
            port:
              number: 9080
  tcp: ~
  tls: ~
```

```
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: bookinfo
spec:
  hosts:
    - '*'
  gateways:
    - bookinfo-gateway
  http:
    - match:
        - headers:
            apiKey:
              exact: test
      rewrite:
        uri: /productpage
      route:
        - destination:
            host: productpage
            port:
              number: 9080
  tcp: ~
  tls: ~

```
