### ISSUE TITLE
istio-pilot crashes with port in capital P

### ISSUE THREAD

**Issue by samos123** [istio/istio#16168]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
When a gateway gets added which used Port instead of port the istio-pilot will crash.

Here is the istio-pilot log:
```
2019-08-08T20:36:21.413953Z     info    ads     CDS: PUSH for node:istio-ingress-76b67fd58d-464vt.gke-system clusters:20 services:14 version:2019-08-08T20:36:03Z/2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x14dd227]
 
goroutine 427 [running]:
istio.io/istio/pilot/pkg/model.MergeGateways(0xc0000cafd0, 0x1, 0x1, 0x2)
        /workspace/go/src/istio.io/istio/pilot/pkg/model/gateway.go:86 +0x477
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).buildGatewayListeners(0xc0000307c0, 0xc0001c4550, 0xc000cf02a0, 0xc000507c00, 0x0, 0xc00069d330, 0x43d28d, 0xc000512478, 0x0)
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Expected behavior**
istio-pilot to not crash and some kind of user input validation

**Steps to reproduce the bug**
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-autogenerated-k8s-ingress
  namespace: gke-system
spec:
  selector:
    istio: ingress-gke-system
  servers:
  - port:
      number: 80
      protocol: HTTP2
      name: http
    hosts:
    - "*"
  - hosts:
    - "*.example.com"
    Port:
      name: https-wildcard
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: ingressgateway-wildcard-cacerts
```
kubectly apply -f istio-gateway.yaml

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.7-gke.19", GitCommit:"a23b6496cc1fdc6bbb888fcb09374c70a848a0f5", GitTreeState:"clean", BuildDate:"2019-05-10T04:06:49Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}

istio version: 1.2.2
```

**How was Istio installed?**
Unsure

**Environment where bug was observed (cloud vendor, OS, etc)**
Anthos GKE on prem 1.0.1-gke.5
