### ISSUE TITLE
Helm upgrade not updating meshpolicy for mtls

### ISSUE THREAD

**Issue by popopanda** [istio/istio#16170]
**Bug description**
Isito 1.2.2 - Helm upgrade does not update meshpolicy.  

few examples:
1) Manually delete the default created meshpolicy, running helm upgrade does not recreate it.  
2) Setting mtls in values.yaml from false to true or vice versa, the meshpolicy and destination rules are not updated/created

However, In istio-security-custom-resources configmap, I do see the custom-resources.yaml key being updated.  

```
apiVersion: v1
data:
  custom-resources.yaml: |-
    # Authentication policy to enable permissive mode for all services (that have sidecar) in the mesh.
    apiVersion: "authentication.istio.io/v1alpha1"
    kind: "MeshPolicy"
    metadata:
      name: "default"
      labels:
        app: security
        chart: security
        heritage: Tiller
        release: istio
    spec:
      peers:
      - mtls:
          mode: PERMISSIVE
```

I did some research, and tried rerunning the following jobs as well thinking it creates it from a job:

```
NAME                COMPLETIONS   DURATION   AGE
istio-init-crd-10   1/1           7s         15d
istio-init-crd-11   1/1           10s        15d
istio-init-crd-12   1/1           9s         15d
```

However, that has no impact as well

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Running helm upgrade should also update the meshpolicy and correct destinationrules when mtls is set from false to true and vice versa.

**Steps to reproduce the bug**
1) Set mtls enabled from false to true
```
  mtls:
    enabled: true
```
Run helm upgrade
` helm upgrade --install --force istio install/kubernetes/helm/istio --namespace istio-system -f install/kubernetes/helm/istio/values.yaml`

2) Delete the default meshpolicy from original installation
`kubectl delete meshpolicy default`

Upgrade istio via helm
` helm upgrade --install --force istio install/kubernetes/helm/istio --namespace istio-system -f install/kubernetes/helm/istio/values.yaml`

For both scenarios, deleted jobs istio-init-crd-10 to 12, reran helm upgrade to recreate jobs. Confirmed jobs ran, and meshpolicy still doesnt exist/updated

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
client version: 1.2.2
devcourseherocom-ingressgateway version:
citadel version: 1.2.2
galley version: 1.2.2
ingressgateway version: 1.2.2
pilot version: 1.2.2
policy version: 1.2.2
sidecar-injector version: 1.2.2
telemetry version: 1.2.2
```
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:04:52Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.8-eks-a977ba", GitCommit:"a977bab148535ec195f12edc8720913c7b943f9c", GitTreeState:"clean", BuildDate:"2019-07-29T20:47:04Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS 1.13
