### ISSUE TITLE
virtual-service header based routing with "_" in header-name does not work

### ISSUE THREAD

**Issue by cfreemoser** [istio/istio#16193]
**Bug description**

Hey, we noticed some problems when implementing header-based routing with istio: 
When creating a virtual-service to enable header-based routing it works fine as long as the header-name does not contain a "_". However, one a "_" is added to the header-name istio seems to ignore the virtual-service.  

Following definition works:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: master-service
spec:
  hosts:
  - master-service.master.svc.cluster.local
  http:
  - match:
    - headers:
        test-test:
          exact: some
    route:
    - destination:
        host: service-a.ns-a.svc.cluster.local
```
The following definition **does no** work: 
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: master-service
spec:
  hosts:
  - master-service.master.svc.cluster.local
  http:
  - match:
    - headers:
        test_test:
          exact: some
    route:
    - destination:
        host: service-a.ns-a.svc.cluster.local
```
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
header-based routing rules allow "_" (underline) in the header-name or Kali is showing a validation error/warning. 

**Steps to reproduce the bug**

1. Deploy a virtual-service as shown above

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio 1.1.8

**How was Istio installed?**

- via helm chart
- we do not use istio gateways but Nginx ingress with sidecars

**Environment where bug was observed (cloud vendor, OS, etc)**
- aks
