### ISSUE TITLE
Pilot crash when envoy ( xds client ) use invaild node Id

### ISSUE THREAD

**Issue by yangdihangN** [istio/istio#16228]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Pilot run normally

**Steps to reproduce the bug**
1.  install istio
2.  use envoy ( xds client ) with below settings to connect to pilot 
```yaml
apiVersion: v1
data:
  envoy.yaml: |
    node:
      cluster: ingress~external~test-debug~test.domain
      id: "ingress~external~test-debug~{{.PodName}}.{{.PodNamespace}}"
      metadata:
        # this line must match !
        role: "{{.PodNamespace}}~gateway-proxy"
    static_resources:
      clusters:
      - name: xds_cluster
        connect_timeout: 5.000s
        load_assignment:
          cluster_name: xds_cluster
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: istio-pilot
                    port_value: 15010
        http2_protocol_options: {}
        type: STRICT_DNS
      - name: rate_limit_service
        type: STRICT_DNS
        connect_timeout: 0.25s
        lb_policy: ROUND_ROBIN
        http2_protocol_options: {}
        load_assignment:
          cluster_name: rate_limit_service
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: rate-limit
                    port_value: 18081
    dynamic_resources:
      ads_config:
        api_type: GRPC
        grpc_services:
        - envoy_grpc: {cluster_name: xds_cluster}
      cds_config:
        ads: {}
      lds_config:
        ads: {}
    admin:
      access_log_path: /dev/null
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 19000
```
3. Pilot crashes immediately
```
2019-08-13T05:58:12.432104Z	info	ads	LDS: PUSH for node:test-debug addr:"10.177.1.70:56552" listeners:1 1221
2019-08-13T05:58:12.435173Z	info	ads	ADS: RDS: PUSH for node: test-debug addr:10.177.1.70:56552 routes:1
panic: runtime error: index out of range

goroutine 483 [running]:
istio.io/istio/pilot/pkg/serviceregistry/kube.(*Controller).GetProxyServiceInstances(0xc000123600, 0xc000736840, 0x3, 0x4, 0xc000736840, 0xc0, 0xc0009fa7e8)
	/root/go/src/istio.io/istio/pilot/pkg/serviceregistry/kube/controller.go:502 +0xb41
istio.io/istio/pilot/pkg/serviceregistry/aggregate.(*Controller).GetProxyServiceInstances(0xc000751c80, 0xc000736840, 0xc00005366a, 0xe, 0x1e1a325, 0x1, 0x0)
	/root/go/src/istio.io/istio/pilot/pkg/serviceregistry/aggregate/controller.go:230 +0x14d
istio.io/istio/pilot/pkg/model.(*Proxy).SetServiceInstances(0xc000736840, 0xc00043c5a0, 0x1e, 0xc000736840)
	/root/go/src/istio.io/istio/pilot/pkg/model/context.go:204 +0x41
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).initConnectionNode(0xc000736300, 0xc000c36700, 0xc000f6e380, 0x0, 0xc000cf5a01)
	/root/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/ads.go:646 +0x18c
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).StreamAggregatedResources(0xc000736300, 0x216cae0, 0xc000b41490, 0x0, 0x0)
	/root/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/ads.go:432 +0x5c9
istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2._AggregatedDiscoveryService_StreamAggregatedResources_Handler(0x1e0ade0, 0xc000736300, 0x215b380, 0xc000411130, 0x348a8b8, 0xc000cc6a00)
	/root/go/src/istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2/ads.pb.go:195 +0xad
istio.io/istio/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc000479980, 0x2174460, 0xc000fff980, 0xc000cc6a00, 0xc000798cf0, 0x3450d20, 0xc000535350, 0x0, 0x0)
	/root/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:1124 +0x85e
istio.io/istio/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000479980, 0x2174460, 0xc000fff980, 0xc000cc6a00, 0xc000535350)
	/root/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:1212 +0x124e
istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000bb1e50, 0xc000479980, 0x2174460, 0xc000fff980, 0xc000cc6a00)
	/root/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:686 +0x9f
created by istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/root/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:684 +0xa1

```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istio version 1.1.11 
kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:40:24Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:30:48Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
