### ISSUE TITLE
Extend Istio RBAC to non-Istio mutual TLS

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#16238]
**Describe the feature request**
Extend Istio RBAC to non-Istio mutual TLS.

Currently, the Istio RBAC filter only works for Istio mutual TLS. The RBAC filter expects the `istio_authn` to extract the source principle for it. The `istio_authn` filter is not applied when mutual TLS other than the Istio mutual TLS is used and the source principle is not extracted.

Proposed solution: in case non-Istio mutual TLS is applied, use Envoy's `authenticated principle` as the source principle. See the next section for Envoy's `http.rbac` filter configuration.

This use case is relevant in case of a gateway that accepts non-Istio mutual TLS connections.

**Describe alternatives you've considered**
The alternative is to use Envoy's `http.rbac` filter:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: private-ingress-rbac
spec:
  workloadLabels:
    istio: private-ingressgateway
  filters:
  - filterName: envoy.filters.http.rbac
    filterType: HTTP
    listenerMatch:
      portNumber: 15443
      listenerType: GATEWAY
      listenerProtocol: HTTP
    filterConfig:
      rules:
        action: ALLOW
        policies:
          reviews_v3:
            permissions:
              and_rules:
                rules:
                - header:
                    name: ":path"
                    prefix_match: "/bookinfo/myreviews/v3/"
                - header:
                    name: ":method"
                    exact_match: "GET"
            principals:
            - authenticated:
                principal_name:
                  exact: "spiffe://c1.example.com/istio-private-egressgateway"
          ratings_v1:
            permissions:
              and_rules:
                rules:
                - header:
                    name: ":path"
                    prefix_match: "/bookinfo/ratings/v1/"
                - header:
                    name: ":method"
                    exact_match: "GET"
            principals:
            - authenticated:
                principal_name:
                  exact: "spiffe://c1.example.com/istio-private-egressgateway"
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
