### ISSUE TITLE
HTTPS access to external service on none 443 port

### ISSUE THREAD

**Issue by tkatrichenko** [istio/istio#16266]
**Bug description**
Looks like Istio doesn't allow applications to access external services through https and use none standard ports (not 443, 8443).
I have a pod with istio-proxy injected
```
kubectl get pod
NAME                                              READY   STATUS             RESTARTS   AGE
busybox-alpine-565ddd7d94-q5grq      2/2     Running            0          6d3h
```
When I try to curl ext service using https on port 443, it works fine and returns code 200. 
But if I try to use another port (7054 in my case), the request fails
```
kubectl exec -it busybox-alpine-565ddd7d94-q5grq -- curl -Isvk https://istio-test.example.com:7054
Defaulting container name to busybox-alpine.
Use 'kubectl describe pod/busybox-alpine-565ddd7d94-q5grq -n default' to see all of the containers in this pod.
*   Trying xx.xx.xx.xx:7054...
* TCP_NODELAY set
* Connected to istio-test.example.com (xx.xx.xx.xx) port 7054 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number
* Closing connection 0
command terminated with exit code 35
```
I saw such errors in bug tickets before, and I believe it was fixed in latest versions of istio, but all of them connect through standard 443 port. 

To fix this I tried to create a VirtualService and ServiceEntry but it didn't help
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: ibm-blockchain
spec:
  hosts:
  - istio-test.example.com
  ports:
  - number: 7054
    name: tls
    protocol: TLS
  location: MESH_EXTERNAL
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ibm-blockchain
spec:
  hosts:
  - istio-test.example.com
  tls:
  - match:
    - port: 7054
      sni_hosts:
      - istio-test.example.com
    route:
    - destination:
        host: istio-test.example.com
        port:
          number: 7054
      weight: 100
```
Also, I was playing with creating Egress Gateway and DestinationRule for this external service and port. Didn't work as well.

So I wonder if Istio supports HTTPS connections to none standard ports?

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
# istioctl version --remote
client version: 1.2.2
citadel version: 1.2.2
egressgateway version: 1.2.2
egressgateway version: 1.2.2
galley version: 1.2.2
ingressgateway version: 1.2.2
ingressgateway version: 1.2.2
pilot version: 1.2.2
policy version: 1.2.2
sidecar-injector version: 1.2.2
telemetry version: 1.2.2
# kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.8+IKS", GitCommit:"fe3e332c2b0f47d4572433c3b0a1687a27fb88c6", GitTreeState:"clean", BuildDate:"2019-07-11T13:45:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Through IBM IKS Addons installer

**Environment where bug was observed (cloud vendor, OS, etc)**
IBM IKS
