### ISSUE TITLE
EnvoyFilter can't work

### ISSUE THREAD

**Issue by icenewman** [istio/istio#16261]
Hi, I want use istio envoyFilter "envoy.grpc_json_transcoder" to translate http-grpc. But it doesn't work.
Here is my config:

EnvoyFilter
```# Created by github.com/tetratelabs/istio-tools/grpc-transcoder
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: weather
  namespace: smartlife-istio
spec:
  workloadLabels:
    app: weather
  filters:
  - listenerMatch:
      portNumber: 7272
      listenerType: SIDECAR_INBOUND
    insertPosition:
      index: BEFORE
      relativeTo: envoy.router
    filterName: envoy.grpc_json_transcoder
    filterType: HTTP
    filterConfig:
      services:  
      - pb.Weather
      protoDescriptorBin: <base64 bin>
      printOptions:
        alwaysPrintPrimitiveFields: True
```

Service
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: weather
  name: weather
  namespace: smartlife-istio
spec:
  selector:
    app: weather
  ports:
    - name: grpc
      port: 7272
      protocol: TCP
      targetPort: 37272
      # nodePort: 30006
  sessionAffinity: None
  type: ClusterIP 
```

Deployment
```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '3'
  labels:
    app: weather  
    version: v1  
  name: weather-server    #deployment名
  namespace: smartlife-istio
spec:
  progressDeadlineSeconds: 600
  replicas: 1      
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: weather
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: weather
        version: v1
    spec:
        containers:
          - name: weather
            ports:
              - containerPort: 37272
            image: 'registry-vpc.cn-shenzhen.aliyuncs.com/zp-repository/weather_api:1.0.0'
            imagePullPolicy: Always    
            livenessProbe:
              failureThreshold: 3
              initialDelaySeconds: 15
              periodSeconds: 10
              successThreshold: 1
              tcpSocket:
                port: 7272
              timeoutSeconds: 1
            resources:
              requests:
                cpu: 100m
                memory: 16Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            tty: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
```

VirtualService
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: weather
  namespace: smartlife-istio
spec:
  gateways:
    - grpc-gateway
  hosts:
    - '*'
  http:
    - route:
        - destination:
            host: weather
            subset: v1
            port:
              number: 7272
```

Gateway
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata: 
  name: grpc-gateway
  namespace: smartlife-istio
spec: 
  selector: 
    istio: ingressgateway # use Istio default gateway implementation
  servers: 
  - port: 
      number: 80
      name: http
      protocol: HTTP
    hosts: 
    - "*"
```
Proto
```
syntax = "proto3";

package pb;
option go_package = "pb";

import "google/api/annotations.proto";

service MyService {
    rpc GrpcServiceA(ReqData) returns (Resp) {
        option (google.api.http) = {
            post : "/service/a"
            body : "reservation"
        };
    };
    rpc GrpcServiceB(ReqData) returns (Resp){
        option (google.api.http) = {
            post : "/service/b"
            body : "reservation"
        };
    };
}
```
request url http://my-gateway-ip:80/package to proto service/function

server return 500 error
