### ISSUE TITLE
Mixer Rule's requestHeaderOperation not run on check adapter rejection

### ISSUE THREAD

**Issue by nbrasz** [istio/istio#16359]
Bug description
In our Mixer check adapter, we have various steps that generate data we pass to output, and then using `requestHeaderOperations` and `responseHeaderOperations` in the `Rule` pass on to upstream services and eventually our logentry adapter.

The problem is that when one of these checks fail, even though we still send the output, the request/response header operations do not seem to trigger.

Is this by design?

Affected product area (please put an X in all that apply)

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastrcture

Expected behavior
requestHeaderOperations and responseHeaderOperations run even if check adapter returns non-zero

Steps to reproduce the bug

Create an out of process check adapter with a Rule that specifies setting a header via requestHeaderOperations as follows:

```
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: my-rule
  namespace: istio-system
spec:
  actions:
  - handler: my-handler
    instances:
    - my-instance
    name: my-oop-adapter
  match: source.labels["istio"] == "myhost"
  requestHeaderOperations:
  - name: my-req-header-foo
    values:
    - my-oop-adapter.output.foo
  responseHeaderOperations:
  - name: my-resp-header-bar
    values:
    - my-oop-adapter.output.bar
```

Make a request where the check fails and neither header will be set and upstream services / requesting client will not be able to see these values.

$ kubectl version                                           
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:13:37Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.10", GitCommit:"e3c134023df5dea457638b614ee17ef234dc34a6", GitTreeState:"clean", BuildDate:"2019-07-08T03:40:54Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Istio Version: 1.1.8 

How was Istio installed?

Helm Charts

Environment where bug was observed (cloud vendor, OS, etc)

Kops + AWS. OS is CoreOS/Container Linux
