### ISSUE TITLE
Small TCP packages are blocked by sidecar

### ISSUE THREAD

**Issue by alexmsu** [istio/istio#16386]
**Bug description**
Small TCP packages with data length less or equal to 4 bytes are blocked, or being saved in receiving buffer. This small TCP data will be read only after another package is sent and the total buffer size is greater than 4 bytes. All the following packages even if data size is less than 4 bytes can be forwarded correctly.
Another weird finding is, if the 2nd byte of data is `/x03`, the 4th and 5th bytes cannot be anything except `\x00`.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Small TCP packages can be forwarded to upper layer container.

**Steps to reproduce the bug**
1. With sidecar auto injection enabled, create 2 k8s pods with any Linux container installed netcat and one public port, say `12345`. Pod 1 will served as netcat server and pod 2 will be client. Then create corresponding k8s service for pod 1.
2. Start a nc server in pod 1 with command `nc -l -s 0.0.0.0 -p 12345 -o /dev/stdout`
3. Try to establish TCP connection from pod 2 to pod 1 with command `echo -ne "\x05\x01\x00" | nc <pod1 service> 12345 -o /dev/stdout`. Server side do not see any data printed.
4. Restart nc server on pod 1 and try to establish another TCP connection with longer data sent from pod 2 to pod 1 with command `echo -ne "\x05\x01\x00\x0a\x0a" | nc <pod1 service> 12345 -o /dev/stdout`. Server side will see the data printed.
5. Remove sidecar from pod 1 then redo the test. #3 will be passed.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Tested with Istio 1.1.7 and 1.2.4
```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5", GitCommit:"0e9fcb426b100a2aea5ed5c25b3d8cfbb01a8acf", GitTreeState:"clean", BuildDate:"2019-08-05T09:13:08Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

> istio-1.2.4/bin/istioctl version --remote
client version: 1.2.4
citadel version: 1.2.4
galley version: 1.2.4
ingressgateway version: 94746ccd404a8e056483dd02e4e478097b950da6-dirty
pilot version: 1.2.4
policy version: 1.2.4
sidecar-injector version: 1.2.4
telemetry version: 1.2.4
```

**How was Istio installed?**
Istio is installed using helm with values file
```
# file: values.yaml
global:
  proxy:
    resources:
      requests:
        cpu: 10m
        memory: 40Mi

pilot:
  traceSampling: 100.0
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 200Mi

mixer:
  telemetry:
    enabled: true
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 100Mi

grafana:
  enabled: true
  security:
    enabled: true

prometheus:
  enabled: true

tracing:
  enabled: true

gateways:
  istio-ingressgateway:
    enabled: true
```
```
helm install istio-1.2.4/install/kubernetes/helm/istio-init -n istio-init
helm install istio-1.2.4/install/kubernetes/helm/istio -n istio -f values.yaml
```

**Environment where bug was observed (cloud vendor, OS, etc)**
k8s cluster is hosted on ubuntu 16.04 VMs

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
