### ISSUE TITLE
Need a mechanism to automatically update cross-repo

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#16381]
As we are moving to multi-repo, we have a lot of changes that require changes to other repos. For example, if we update the builder image in istio/tools, we need to trigger an update in test-infra to use the image. If we update istio/proxy, we need to update the version we use in istio/istio.

Currently this is almost entirely manual, which is pretty painful.

I believe we had some process that would do daily updates to proxy, but it has been broken/disable for months. We may be able to reuse some functionality there.

These can be triggered daily or in postsubmit, not sure which is better.

cc @geeknoid

**Comment by howardjohn** [comment]
Right now there are three ways dependencies are defined:

* `go.mod` - can be updated with `go get repo@sha`
* `istio.deps` - our homegrown dependency management. Could update with jq probably
* Nothing, just `git clone` at master - we should never do this

One possible design:

We have some autoupdate.yaml file like
```yaml
- repo: istio/istio
  deps:
    - repo: istio/cni
      type: istio.deps # go.mod or  istio.deps
      source: master # branch
      freq: every # every commit, daily, weekly, etc
    - repo: istio/pkg
      type: go.mod
      source: master
      freq: daily
```

And then some periodic job that goes through and triggers a bunch of PRs to relevant repos updating different components. Note -- it should not batch multiple updates into one PR, so we can merge independantly. Prow takes care of testing PRs merged together.

I think this would work, my only concern is reinventing the wheel... If there is a better way to do this that would be prefered. 

For the go.mod updates there are certainly existing solutions. I've tried https://dependabot.com/, but its not viable for a couple reasons: you cannot whitelist what modules to update, and it does not do `go mod tidy`.
