### ISSUE TITLE
Istio 1.3 EnvoyFilter not working correctly testing istio 1.3

### ISSUE THREAD

**Issue by brectanus-sigsci** [istio/istio#16393]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

I am trying to inject a simple lua filter into the envoy config to test EnvoyFilter in istio 1.3 using httpbin as a test app. I am following the basic examples and docs from https://preliminary.istio.io/docs/reference/config/networking/v1alpha3/envoy-filter/ but I am running into multiple issues:

1. If I specify a `portNumber: 8080` as in the examples (also tried `name: 0.0.0.0_8080`) in the `match`, then nothing is injected. This match criteria seems broken.
2. If I comment out `portNumber` and `name`, then it applies to all listeners *EXCEPT* port 8080 and the lua filter is injected *TWICE* in each listener.
3. The `INSERT_BEFORE` appears to be working as `INSERT_AFTER` when a `subFilter` is used. Without a `subFilter`, it correctly adds it to the beginning of the list, however.

Simple test EnvoyFilter that should add a lua HTTP filter *BEFORE* the "mixer" filter, but actually adds it *AFTER* and adds the lua filter to all listeners except the port 8080 filter (NOTE using `portNumber: 8080` is what I want to use as in the example, but this causes nothing to be inserted):
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: httpbin-lua-test
spec:
  workloadSelector:
    labels:
      app: httpbin
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
#        portNumber: 8080
#        name: "0.0.0.0_8080"
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "mixer"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.lua
        config:
          inline_code: |
            function envoy_on_request(handle)
              handle:logWarn("DEBUG REQUEST")
            end
            function envoy_on_response(handle)
              handle:logWarn("DEBUG RESPONSE")
            end
```

Example snippet of HTTP filters after running (two lua filters after mixer instead of one filter before mixer):
```
                            "httpFilters": [
                                {
                                    "name": "istio_authn",
                                    "typedConfig": {
                                        "@type": "type.googleapis.com/istio.envoy.config.filter.http.authn.v2alpha1.FilterConfig",
                                        "policy": {
                                            "peers": [
                                                {
                                                    "mtls": {
                                                        "mode": "PERMISSIVE"
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                },
                                {
                                    "name": "mixer",
                                    "typedConfig": {
                                        "@type": "type.googleapis.com/istio.mixer.v1.config.client.HttpClientConfig",
                                        "transport": {
                                            "networkFailPolicy": {
                                                "policy": "FAIL_CLOSE",
                                                "baseRetryWait": "0.080s",
                                                "maxRetryWait": "1s"
                                            },
                                            "checkCluster": "outbound|9091||istio-policy.istio-system.svc.cluster.local",
                                            "reportCluster": "outbound|9091||istio-telemetry.istio-system.svc.cluster.local",
                                            "reportBatchMaxEntries": 100,
                                            "reportBatchMaxTime": "1s"
                                        },
                                        "serviceConfigs": {
                                            "default": {}
                                        },
                                        "defaultDestinationService": "default",
                                        "mixerAttributes": {
                                            "attributes": {
                                                "context.proxy_version": {
                                                    "stringValue": "1.3.0"
                                                },
                                                "context.reporter.kind": {
                                                    "stringValue": "inbound"
                                                },
                                                "context.reporter.uid": {
                                                    "stringValue": "kubernetes://httpbin-d967c6d88-lcnbj.default"
                                                },
                                                "destination.ip": {
                                                    "bytesValue": "AAAAAAAAAAAAAP//CgEA2A=="
                                                },
                                                "destination.namespace": {
                                                    "stringValue": "default"
                                                },
                                                "destination.port": {
                                                    "int64Value": "80"
                                                },
                                                "destination.uid": {
                                                    "stringValue": "kubernetes://httpbin-d967c6d88-lcnbj.default"
                                                }
                                            }
                                        }
                                    }
                                },
                                {
                                    "name": "envoy.lua",
                                    "config": {
                                        "inline_code": "function envoy_on_request(handle)\n  handle:logWarn(\"DEBUG REQUEST\")\nend\nfunction envoy_on_response(handle)\n  handle:logWarn(\"DEBUG RESPONSE\")\nend\n"
                                    }
                                },
                                {
                                    "name": "envoy.lua",
                                    "config": {
                                        "inline_code": "function envoy_on_request(handle)\n  handle:logWarn(\"DEBUG REQUEST\")\nend\nfunction envoy_on_response(handle)\n  handle:logWarn(\"DEBUG RESPONSE\")\nend\n"
                                    }
                                },
                                {
                                    "name": "envoy.cors"
                                },
                                {
                                    "name": "envoy.fault"
                                },
                                {
                                    "name": "envoy.router"
                                }
                            ],
```

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

This should add *ONE* lua HTTP filter to the matching listeners *BEFORE* the "mixer" HTTP filter, not *AFTER*.

**Steps to reproduce the bug**

* Install istio 1.3 (I used istio-release-1.3-20190819-09-16/) using the quick start eval install for k8s
* Install the httpbin sample (or probably any sample)
* Apply the EnvoyFilter as above
* Look at the `istioctl  proxy-config listeners <pod> -o json` output

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```
$ istioctl version --remote
client version: release-1.3-20190819-09-16
control plane version: release-1.3-20190819-09-16
```

**How was Istio installed?**

istio 1.3 (I used istio-release-1.3-20190819-09-16/) using the quick start eval install for k8s

**Environment where bug was observed (cloud vendor, OS, etc)**

This is MacOS w/docker desktop + k8s

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by rshriram** [comment]
can you try out https://github.com/istio/istio/pull/16395 and let me know if it fixes the issue? I am not sure why you are seeing two lua filters. or why the port match is not working. Can you show the full inbound configuration if possible, including the listeners?

**Comment by brectanus-sigsci** [comment]
@rshriram #16395 resolves the INSERT_BEFORE ordering issue.

I have more on the `portNumber` matching:
* I had the wrong port in my EnvoyFilter (app was 8080, but I switched to 80 and forgot to change the EnvoyFilter and the 8080 that was in the config was OUTBOUND, so no match). Using the corrected `portNumber: 80`, then this seems to work correctly. I get one lua filter in the port 80 listener only. So this seems my mistake - apologies.
[lua-filter-1.3_80.yaml.txt](https://github.com/istio/istio/files/3521787/lua-filter-1.3_80.yaml.txt)
[httpbin-listeners-1.3_80.json.txt](https://github.com/istio/istio/files/3521774/httpbin-listeners-1.3_80.json.txt)

* However, using *NO* `portNumber` in the match still seems to have the bug with two filters being added to all matching inbound listeners (but now correctly before the "mixer" filter instead of after)
[lua-filter-1.3_noport.yaml.txt](https://github.com/istio/istio/files/3521789/lua-filter-1.3_noport.yaml.txt)
[httpbin-listeners-1.3_noport.json.txt](https://github.com/istio/istio/files/3521777/httpbin-listeners-1.3_noport.json.txt)

**Comment by rshriram** [comment]
Hmm. thanks for that update.. 
Also for posterity, this config is not working:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: httpbin-test-filter
spec:
  workloadSelector:
    labels:
      app: httpbin
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        portNumber: 80
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager"
          access_log:
          - name: envoy.http_grpc_access_log
            config: 
              common_config:
                log_name: "grpc-als-example"
                grpc_service:
                  envoy_grpc:
                    cluster_name: grpc-als-cluster
  - applyTo: CLUSTER
    match:
      context: SIDECAR_INBOUND
    patch:
      operation: ADD
      value:
        name: grpc-als-cluster
        type: STRICT_DNS
        connect_timeout: 0.25s
        http2_protocol_options: {}
        load_assignment:
          cluster_name: grpc-als-cluster
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 9999
```

Envoy seems to get the literal HCM supplied by the end user without all the required fields.

```
[2019-08-21 16:28:50.347][18][warning][config] [external/envoy/source/common/config/grpc_mux_subscription_impl.cc:81] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) 10.1.1.137_80: Proto constraint validation failed (HttpConnectionManagerValidationError.StatPrefix: ["value length must be at least " '\x01' " bytes"]): access_log {
  name: "envoy.http_grpc_access_log"
  config {
    fields {
      key: "common_config"
      value {
        struct_value {
          fields {
            key: "grpc_service"
            value {
              struct_value {
                fields {
                  key: "envoy_grpc"
                  value {
                    struct_value {
                      fields {
                        key: "cluster_name"
                        value {
                          string_value: "grpc-als-cluster"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
          fields {
            key: "log_name"
            value {
              string_value: "grpc-als-example"
            }
          }
        }
      }
    }
  }
}
, virtualInbound: Proto constraint validation failed (HttpConnectionManagerValidationError.StatPrefix: ["value length must be at least " '\x01' " bytes"]): access_log {
  name: "envoy.http_grpc_access_log"
  config {
    fields {
      key: "common_config"
      value {
        struct_value {
          fields {
            key: "grpc_service"
            value {
              struct_value {
                fields {
                  key: "envoy_grpc"
                  value {
                    struct_value {
                      fields {
                        key: "cluster_name"
                        value {
                          string_value: "grpc-als-cluster"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
          fields {
            key: "log_name"
            value {
              string_value: "grpc-als-example"
            }
          }
        }
      }
    }
  }
}
```

**Comment by brectanus-sigsci** [comment]
Additionally on that config above, it seems ALS cannot use a cluster defined via EnvoyFilter because that cluster is dynamic and ALS requires a static cluster. It seems ext_authz was excluded from this, but ALS was not: https://github.com/envoyproxy/envoy/issues/3660

So, this seems to work instead (use google_grpc client):
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: httpbin-grpc-als-filter
spec:
  workloadSelector:
    labels:
      app: httpbin
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        portNumber: 80
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager"
          access_log:
          - name: envoy.http_grpc_access_log
            config:
              common_config:
                log_name: "grpc-als-example"
                grpc_service:
                   # ALS cannot yet use dynamic grpc clusters - must use google_grpc for ALS
                  google_grpc:
                    target_uri: 127.0.0.1:9999
                    stat_prefix: "grpc-als-example"
```
