### ISSUE TITLE
https gateway with credentialName causes pilot tls error.

### ISSUE THREAD

**Issue by JoelDamata-pcc** [istio/istio#16487]
**Bug description**
Created this gateway and k8s secret 

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: core-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "*"
    port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: test-cert
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
```

Pilot spits out this error
```
	* gateway listener 0.0.0.0_443 validation failed: invalid Listener.FilterChains[0]: embedded message failed validation | caused by: invalid FilterChain.TlsContext: embedded message failed validation | caused by: invalid DownstreamTlsContext.CommonTlsContext: embedded message failed validation | caused by: invalid CommonTlsContext.TlsCertificates[0]: embedded message failed validation | caused by: invalid TlsCertificate.CertificateChain: embedded message failed validation | caused by: invalid DataSource.Filename: value length must be at least 1 bytes
```
If i choose to use privateKey and serverCertificate instead of credentialName this works. 

I use the same secret and gateway in a istio 1.1.8 cluster and it works great.

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istio = 1.2.4
kubernetes = v1.13.7

**How was Istio installed?**
helm template helm/istio --name istio --namespace istio-system  --set global.mtls.enabled=true --set global.controlPlaneSecurityEnabled=true --set global.outboundTrafficPolicy.mode=ALLOW_ANY --set gateways.istio-ingressgateway.enabled=true --set gateways.istio-egressgateway.enabled=false --set tracing.enabled=true --set grafana.enabled=true --set mixer.enabled=true --set prometheus.enabled=true --set kiali.enabled=true  --set global.k8sIngress.enableHttps=true > istio.yaml

**Environment where bug was observed (cloud vendor, OS, etc)**
AKS
