### ISSUE TITLE
PostgreSQL connection not working when using Istio mTLS

### ISSUE THREAD

**Issue by denniseffing** [istio/istio#16506]
Applications running inside pods with an injected sidecar proxy can not establish a connection to a PostgreSQL database running in a different pod with an injected sidecar proxy when mTLS is enabled.

**Affected product area**

[x] Networking
[x] Security

**Expected behavior**
Connections from pods with an injected sidecar to a PostgreSQL database running inside a different pod with an injected sidecar work fine with activated mTLS.

**Actual behavior**
Connections to PostgreSQL database from another pod fail

Logs of PostgreSQL database server:
```
2019-08-23 12:04:55.935 GMT [360] LOG:  connection received: host=127.0.0.1 port=39800
2019-08-23 12:04:55.935 GMT [360] LOG:  incomplete startup packet
```

Logs of psql client:
```
psql: received invalid response to SSL negotiation:
```

Local connections (from inside the PostgreSQL database pod to the database) work fine.

**Steps to reproduce the bug**
1. Install Istio on Kubernetes cluster with activated mTLS
2. Deploy PostgreSQL with an injected sidecar proxy
3. Deploy a PostgreSQL client in another pod with an injected sidecar proxy (the CLI psql is sufficient)
4. Try to connect to the database

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
client version: 1.2.4
citadel version: 1.2.4
egressgateway version: 94746ccd404a8e056483dd02e4e478097b950da6-dirty
galley version: 1.2.4
ingressgateway version: 94746ccd404a8e056483dd02e4e478097b950da6-dirty
pilot version: 1.2.4
policy version: 1.2.4
sidecar-injector version: 1.2.4
telemetry version: 1.2.4
```

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T16:54:35Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Installed with Helm via helm template using the Istio demo values (including mTLS)

**Environment where bug was observed (cloud vendor, OS, etc)**
Minikube

**Cluster dump**
[istio-dump.tar.gz](https://github.com/istio/istio/files/3534315/istio-dump.tar.gz)

**Comment by esnible** [comment]
Possibly related: https://github.com/istio/istio/issues/11987 .  That issue was closed as Stale, but I don't believe a fix was produced for it.

**Comment by denniseffing** [comment]
This can be closed. Turns out that I was experiencing these issues because I changed the deployment configuration to use multiple namespaces without creating new destination rules for those namespaces. mTLS with Postgres is working fine now. Sorry for the confusion.

**Comment by joestty** [comment]
@denniseffing could you please share more information on what changes you made to make postgres work? Im currently experiencing similar issue with postgres 12.2. Oddly, go application that im deploying to the same namespace works without issues and does not require creation of destination rules (by works I mean GET request from different pod to applications endpoint is executed successfully while both application and tester have sidecar injected).

**Comment by joestty** [comment]
For anyone experiencing similar issues, take a look at the document: https://istio.io/docs/ops/configuration/traffic-management/protocol-selection/
This caused a problem in our case. Port in deployment and service definition for Postgres was called "http" (Kubernetes itself does not care what the name is, so it was sitting in our helm chart for a long time). After renaming it to "tcp" Postgres started to accept connections. This was tested with Postgres 12.3 and Istio 1.6.

**Comment by allanhung** [comment]
@joestty I am facing the similar issue.  I was tested with with Postgres 12.3 and Istio 1.6.1. Here is my config.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - image: postgres:12.3
        name: postgresql
        env:
        - name: POSTGRES_PASSWORD
          value: pgsql@123
        ports:
        - containerPort: 5432
          name: postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: default
spec:
  ports:
  - name: tcp
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgresql
  type: ClusterIP
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: pgsql-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 5432
      name: tcp
      protocol: TCP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: pgsql-vs
  namespace: default
spec:
  hosts:
  - "*"
  gateways:
  - pgsql-gateway
  http:
  - match:
    - port: 5432
    route:
    - destination:
        host: postgresql-service
        port:
          number: 5432
        subset: postgres
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: pgsql-dr
  namespace: default
spec:
  host: postgresql-service
  subsets:
  - labels:
      app: postgresql
    name: postgres
```
istio-ingressgateway
```
[root@debug /] kubectl get svc -n istio-system
NAME                        TYPE           CLUSTER-IP     EXTERNAL-IP    PORT(S)                                                                                                                                  AGE
istio-ingressgateway        LoadBalancer   10.1.199.109   172.25.20.11   15021:30529/TCP,80:30822/TCP,443:31709/TCP,5432:30091/TCP,15443:30967/TCP,15011:31410/TCP,15012:30598/TCP,8060:31666/TCP,853:31201/TCP
```
When I try to connect, it shows Connection refused.
```
[root@debug /]# psql -h 172.25.20.11 -U postgres
psql: could not connect to server: Connection refused
        Is the server running on host "172.25.20.11" and accepting
        TCP/IP connections on port 5432?
```
Would you kindly advise me where the problem is?  Thanks.
