### ISSUE TITLE
Quota responses not consistent

### ISSUE THREAD

**Issue by theganyo** [istio/istio#16515]
**Bug description**
Even after hitting rate limit, quota occasionally allows requests.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Results should be consistent. Once the limit has been hit, it should always respond with RESOURCE_EXHAUSTED until the limit is reset based on time.

**Steps to reproduce the bug**
After installing the Istio `helloworld` sample, create a simple quota based on a single header dimension (`memquota` or `redisquota`, it doesn't matter - both fail similarly):
```
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: appquota
  namespace: istio-system
spec:
  compiledAdapter: memquota
  # compiledAdapter: redisquota
  params:
    redisServerUrl: docker.for.mac.host.internal:6379
    connectionPoolSize: 10
    quotas:
    - name: appquota.instance.istio-system
      maxAmount: 2
      validDuration: 1m
---
apiVersion: config.istio.io/v1alpha2
kind: instance
metadata:
  name: appquota
  namespace: istio-system
spec:
  compiledTemplate: quota
  params:
    dimensions:
      application: request.headers["application_name"] | "unknown"
---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpec
metadata:
  name: appquota
  namespace: istio-system
spec:
  rules:
  - quotas:
    - charge: 1
      quota: appquota
---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpecBinding
metadata:
  name: appquota
  namespace: istio-system
spec:
  quotaSpecs:
  - name: appquota
    namespace: istio-system
  services:
  - name: helloworld
    namespace: default
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: appquota
  namespace: istio-system
spec:
  match: request.headers["application_name"] | "unknown" != "unknown"
  actions:
  - handler: appquotas
    instances:
    - appquota
```

Then, make some requests against it:
```
$ for ((n=0;n<30;n++)); do curl localhost/hello -Happlication_name:test1; echo ""; done
Hello version: v1, instance: helloworld-v1-7bb88866c4-wmkt5

Hello version: v2, instance: helloworld-v2-6cd449dff4-lqfg5

RESOURCE_EXHAUSTED:Quota is exhausted for: appquota
RESOURCE_EXHAUSTED:Quota is exhausted for: appquota
RESOURCE_EXHAUSTED:Quota is exhausted for: appquota
RESOURCE_EXHAUSTED:Quota is exhausted for: appquota
RESOURCE_EXHAUSTED:Quota is exhausted for: appquota
RESOURCE_EXHAUSTED:Quota is exhausted for: appquota
RESOURCE_EXHAUSTED:Quota is exhausted for: appquota
RESOURCE_EXHAUSTED:Quota is exhausted for: appquota
RESOURCE_EXHAUSTED:Quota is exhausted for: appquota
RESOURCE_EXHAUSTED:Quota is exhausted for: appquota
RESOURCE_EXHAUSTED:Quota is exhausted for: appquota
Hello version: v1, instance: helloworld-v1-7bb88866c4-wmkt5

RESOURCE_EXHAUSTED:Quota is exhausted for: appquota
RESOURCE_EXHAUSTED:Quota is exhausted for: appquota
Hello version: v2, instance: helloworld-v2-6cd449dff4-lqfg5

RESOURCE_EXHAUSTED:Quota is exhausted for: appquota
Hello version: v1, instance: helloworld-v1-7bb88866c4-wmkt5

RESOURCE_EXHAUSTED:Quota is exhausted for: appquota
Hello version: v2, instance: helloworld-v2-6cd449dff4-lqfg5

RESOURCE_EXHAUSTED:Quota is exhausted for: appquota
RESOURCE_EXHAUSTED:Quota is exhausted for: appquota
RESOURCE_EXHAUSTED:Quota is exhausted for: appquota
RESOURCE_EXHAUSTED:Quota is exhausted for: appquota
RESOURCE_EXHAUSTED:Quota is exhausted for: appquota
RESOURCE_EXHAUSTED:Quota is exhausted for: appquota
RESOURCE_EXHAUSTED:Quota is exhausted for: appquota
RESOURCE_EXHAUSTED:Quota is exhausted for: appquota
RESOURCE_EXHAUSTED:Quota is exhausted for: appquota
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
$istioctl version --remote
client version: 1.2.4
citadel version: 1.2.4
egressgateway version: 94746ccd404a8e056483dd02e4e478097b950da6-dirty
galley version: 1.2.4
ingressgateway version: 94746ccd404a8e056483dd02e4e478097b950da6-dirty
pilot version: 1.2.4
policy version: 1.2.4
sidecar-injector version: 1.2.4
telemetry version: 1.2.4

$kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
```
kubectl apply -f install/kubernetes/istio-demo.yaml
```

**Environment where bug was observed (cloud vendor, OS, etc)**
Docker for Mac

**Comment by theganyo** [comment]
BTW: The configuration used above has the default 1 policy mixer pod and 2 helloworld pods.

**Comment by argeualcantara** [comment]
I'm also having issues with redis quota. I'm running Istio 2.3.6.
The first time, I can make the 2 requests, but then it takes about 10min. to make the other requests, but my window is just 10s. I'm only charging 1 on the quota spec. I don't know why this is happening. The documentation also does not help. I want to limit X reqs / day and I have no idea  the values that I need to put in the handler.
```
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: redishandler
  namespace: istio-system
spec:
  compiledAdapter: redisquota
  params:
    redisServerUrl: redis-cluster.redis.svc.cluster.local:6379
    connectionPoolSize: 10
    quotas:
    - name: requestcountquota.instance.istio-system
      maxAmount: 1
      validDuration: 10s
      bucketDuration: 9s
      rateLimitAlgorithm: ROLLING_WINDOW
      overrides:
      - dimensions:
          destination: my-app
          requestPath: /myapp/ping
          clientId: abc
        maxAmount: 2
```

**Comment by argeualcantara** [comment]
Hi @douglas-reid 
I'm still having issues after updating to istio 1.3.5
Heres the handler spec
```yaml
spec:
  compiledAdapter: redisquota
  params:
    connectionPoolSize: 10
    quotas:
    - bucketDuration: 1s
      maxAmount: 100
      name: requestcountquota.instance.istio-system
      rateLimitAlgorithm: ROLLING_WINDOW
      validDuration: 10m
    redisServerUrl: redis-cluster-svc.redis.svc.cluster.local:6379

```
this was almost working, but I got some inconsistencies, like having 50 requests with 200 response and then the 51st request would respond with 429, but then I got 5 more requests with 200 before getting 429 for all the requests that exceeded the limit.
Do you have a recommendation of the time window, maybe a minimal value that we can use? Or maybe a recommendation on the maxAmmount / validDuration ratio

Thanks
