### ISSUE TITLE
Improve documentation on use of restrictive pod security policy  

### ISSUE THREAD

**Issue by rajholla** [istio/istio#16535]
**Describe the feature request**
This is a request to update documentation on how Istio can be run on a cluster with restrictive pod security polices.  Istio doesn't appear to be working with the restrictive policy even with `--set istio_cni.enabled=true` 

Policy :
```
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
  - ALL
  volumes:
  - 'configMap'
  - 'emptyDir'
  - 'projected'
  - 'secret'
  - 'downwardAPI'
  - 'persistentVolumeClaim'
  - 'csi'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
  runAsGroup:
    rule: 'MustRunAsNonRoot'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  seLinux:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: false
```

**Describe alternatives you've considered**
We are using privileged policy for all service accounts within the istio-system namespace as a workaround but it is not preferred for our production setup.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[x] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
There are several issues talks about this requirement but none of them conclude with the working PSP. I understand we may still have few requirements before we use fully restricted policy, but it would be nice to document the least privileged PSP that works for Istio.  

Related issues: 
https://github.com/istio/istio/issues/6806
https://github.com/istio/istio/issues/11839
https://github.com/istio/istio/issues/11571
