### ISSUE TITLE
https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: no endpoints available for service "istio-sidecar-injector"

### ISSUE THREAD

**Issue by mgenov** [istio/istio#16536]
**Bug description**
VirtualService stops working after an hour of work.  

Error creating: Internal error occurred: failed calling webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: no endpoints available for service "istio-sidecar-injector"

**Affected product area (please put an X in all that apply)**

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [x] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Expected behavior**
The traffic to 
**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

kubectl version
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.8", GitCommit:"7d3d6f113e933ed1b44b78dff4baf649258415e5", GitTreeState:"clean", BuildDate:"2019-06-19T16:37:16Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```

istioctl version --remote
```
client version: 1.2.3
citadel version: 1.2.3
galley version: 1.2.3
ingressgateway version: 1.2.3
pilot version: 1.2.3
sidecar-injector version: 1.2.3
☁  bin
```

**How was Istio installed?**
HelmRelease of fluxcd:

```yaml
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: istio
  namespace: istio-system
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: istio
  chart:
    repository: https://storage.googleapis.com/istio-release/releases/1.2.3/charts
    name: istio
    version: 1.2.3
  values:
    # pilot configuration
    pilot:
      enabled: true
      autoscaleEnabled: true
      sidecar: true
      resources:
        requests:
          cpu: 10m
          memory: 128Mi

    # ingress configuration
    gateways:
      enabled: true
      istio-ingressgateway:
        type: LoadBalancer
        loadBalancerIP: "xxx.xxx.xxx.xxx"
        autoscaleEnabled: true
        autoscaleMax: 2
        secretVolumes:
        - name: ingressgateway-certs
          secretName: istio-ingressgateway-certs
          mountPath: /etc/istio/ingressgateway-certs
        - name: ingressgateway-ca-certs
          secretName: istio-ingressgateway-ca-certs
          mountPath: /etc/istio/ingressgateway-ca-certs
        - name: ingressgateway-dev-certs
          secretName: istio-ingressgateway-dev-certs
          mountPath: /etc/istio/ingressgateway-dev-certs

    # sidecar-injector webhook configuration
    sidecarInjectorWebhook:
      enabled: true

    # security configuration
    security:
      enabled: true

    # galley configuration
    galley:
      enabled: true

    # mixer configuration
    mixer:
      policy:
        enabled: false
        replicaCount: 1
        autoscaleEnabled: false
      telemetry:
        enabled: true
        replicaCount: 1
        autoscaleEnabled: false
      resources:
        requests:
          cpu: 10m
          memory: 128Mi

    # addon prometheus configuration
    prometheus:
      enabled: true
      scrapeInterval: 5s

    # addon jaeger tracing configuration
    tracing:
      enabled: true

    # common settings
    global:
      # sidecar settings
      proxy:
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 2000m
            memory: 256Mi
      controlPlaneSecurityEnabled: false
      mtls:
        enabled: false
      useMCP: true
```

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE
