### ISSUE TITLE
port 8080 in services leads to unknown source

### ISSUE THREAD

**Issue by KuroObi** [istio/istio#16614]
**Bug description**
If a Service is deployed with port 8080 Kiali reports the source as unknown.
This only affects the port and only port 8080, as soon as it is changed to something else Kiali reports source correctly and is able to build the graph.

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test
    service: test-service
  name: test-service
spec:
  ports:
  - name: http
    port: 8080
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
the source field gets reported even on port 8080.

**Steps to reproduce the bug**
Deploy a Service with port 8080, targetPort may be different.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istio: 1.2.0
kubernetes: v1.15.0

**How was Istio installed?**
Rancher Helm Chart

**Environment where bug was observed (cloud vendor, OS, etc)**
bare-metal rancher v2 cluster

**Comment by KuroObi** [comment]
```
$ kubectl get svc --all-namespaces | grep 8080
istio-system        istio-pilot                                       ClusterIP      10.43.178.172   <none>        15010/TCP,15011/TCP,8080/TCP,15014/TCP         2d2h
cattle-prometheus   expose-kubernetes-metrics                         ClusterIP      None            <none>        8080/TCP,8081/TCP                              43d
cattle-prometheus   expose-operator-metrics                           ClusterIP      None            <none>        8080/TCP                                       43d
istio-test          tester-1-v1                                       ClusterIP      10.43.18.107    <none>        8080/TCP                                       20h
istio-test          tester-2-v1                                       ClusterIP      10.43.174.170   <none>        8080/TCP                                       20h
istio-test          tester-3-v1                                       ClusterIP      10.43.187.27    <none>        8080/TCP                                       20h
istio-test          tester-4-v1                                       ClusterIP      10.43.191.167   <none>        8080/TCP                                       20h
istio-test          tester-5-v1                                       ClusterIP      10.43.161.245   <none>        8080/TCP                                       20h
istio-test          tester-6-v1                                       ClusterIP      10.43.13.215    <none>        8080/TCP                                       20h
istio-test          tester-7-v1                                       ClusterIP      10.43.70.60     <none>        8080/TCP                                       20h
istio-test          tester-8-v1                                       ClusterIP      10.43.224.66    <none>        8080/TCP                                       20h
```

**Comment by larstonne** [comment]
We just verified that version 1.2.5 shows same behaviour

**Comment by larstonne** [comment]
We found this in our logs:
warn	Omitting listener for management address 10.42.5.62_8080 due to collision with service listener 10.42.5.62_8080

**Comment by esnible** [comment]
Adding `area/networking` tag because the collision message suggests a problem that is not related to telemetry.

**Comment by douglas-reid** [comment]
Can you post the podspec in use and an example metric?

**Comment by KuroObi** [comment]
Here are the Pod-Specs:
```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: test-service
    type: test
    version: v1
  name: test-service-v1
  namespace: istio-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-service
      version: v1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-service
        type: test
        version: v1
      name: test-service-v1
    spec:
      containers:
      - image: test-service-v1:1.0.0
        imagePullPolicy: Always
        name: test-service-v1
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: "3"
            memory: 8Gi
          requests:
            cpu: 1500m
            memory: 5Gi
      restartPolicy: Always
```
Here are the metrics out of prometheus:
```
istio_requests_total{
  connection_security_policy="none",
  destination_app="test-service",
  destination_principal="unknown",
  destination_service="test-service.istio-test.svc.cluster.local",
  destination_service_name="test-service",
  destination_service_namespace="istio-test",
  destination_version="v1",
  destination_workload="test-service-v1",
  destination_workload_namespace="istio-test",
  instance="10.42.9.65:42422",
  job="istio-mesh",
  permissive_response_code="none",
  permissive_response_policyid="none",
  reporter="destination",
  request_protocol="http",
  response_code="200",
  response_flags="-",
  source_app="unknown",
  source_principal="unknown",
  source_version="unknown",
  source_workload="unknown",
  source_workload_namespace="unknown"
}
```
