### ISSUE TITLE
External Auth not functional when auth service inside mesh

### ISSUE THREAD

**Issue by castlemilk** [istio/istio#16676]
**Bug description**
When  running an authentication service inside the service mesh - for usage in the [ext_auth](https://www.envoyproxy.io/docs/envoy/v1.11.1/configuration/http_filters/ext_authz_filter#configuration-examples) filter in envoy - the `cluster_name` created will not be usable over gRPC due to the previously reported issue #5331, where the `|` is an invalid character for the authority header in gRPC.

The example envoy filter that would be utilising the invalid `cluster_name` is as follows:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: external-auth-my-app
  namespace: default
spec:          
  workloadLabels:
    app: my-app
  filters:                          
  - insertPosition:
      index: FIRST
    listenerMatch: 
      listenerType: SIDECAR_INBOUND
      listenerProtocol: HTTP
    filterType: HTTP
    filterName: "envoy.ext_authz"
    filterConfig:      
      grpc_service:
        timeout: 5s
        envoy_grpc:
          cluster_name: outbound|8083||auth.default.svc.cluster.local
```

In this case, what would be a potential solution to reference a `cluster_name` which is valid? This described scenario works fine if the authentication service runs outside the *Service Mesh* and I reference the in-cluster DNS name instead.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

External Authentication should work over gRPC when the authentication service runs inside the *Service Mesh*

**Steps to reproduce the bug**

Try and set up an authentication service which runs over gRPC and attempt to setup the previously described `EnvoyFilter` with ext_auth

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

any version

**How was Istio installed?**
helm
**Environment where bug was observed (cloud vendor, OS, etc)**
gke
Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
