### ISSUE TITLE
SDS Helm default values are invalid in profiles other than SDS profile

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#16705]
Currently to install SDS a user needs to provide many many values:
```yaml
global:
  controlPlaneSecurityEnabled: true

  mtls:
    # Default setting for service-to-service mtls. Can be set explicitly using
    # destination rules or service annotations.
    enabled: true

  sds:
    enabled: true
    udsPath: "unix:/var/run/sds/uds_path"

nodeagent:
  enabled: true
  image: node-agent-k8s
  env:
    CA_PROVIDER: "Citadel"
    CA_ADDR: "istio-citadel:8060"
    VALID_TOKEN: true

```

This is not standard practice for Istio or Helm in general. A feature should be simple to enable, like `--set pilot.enabled=true` and get sane defaults. Then, if a user needs to customize the setup they can pass complex configs.

At the very least it seems

```yaml
sds:
    udsPath: "unix:/var/run/sds/uds_path"

nodeagent:
  image: node-agent-k8s
  env:
    CA_PROVIDER: "Citadel"
    CA_ADDR: "istio-citadel:8060"
    VALID_TOKEN: true
```

can be removed.
