### ISSUE TITLE
filter chain match rules require TLS Inspector listener filter, but it isn't configured

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#16755]
My envoy logs are filled with

```
[262][warning][config] [external/envoy/source/server/listener_manager_impl.cc:313] adding listener '0.0.0.0:9090': filter chain match rules require TLS Inspector listener filter, but it isn't configured, trying to inject it (this might fail if Envoy is compiled without it)
```

Seems like we are not configuring something correctly?

This may be a regression on https://github.com/istio/istio/issues/7601

**Comment by howardjohn** [comment]
Config Dump:
```yaml
- address:
    socketAddress:
      address: 0.0.0.0
      portValue: 9090
  continueOnListenerFiltersTimeout: true
  deprecatedV1:
    bindToPort: false
  filterChains:
  - filterChainMatch:
      prefixRanges:
      - addressPrefix: 10.52.12.102
        prefixLen: 32
      - addressPrefix: fe80::c072:8ff:fe23:9387
        prefixLen: 128
    filters:
    - name: mixer
      typedConfig:
        '@type': type.googleapis.com/istio.mixer.v1.config.client.TcpClientConfig
        disableCheckCalls: true
        mixerAttributes:
          attributes:
            context.proxy_version:
              stringValue: 1.3.0
            context.reporter.kind:
              stringValue: outbound
            context.reporter.uid:
              stringValue: kubernetes://server-7677bd45c5-r7scx.istio-stability-looper
            destination.service.host:
              stringValue: prometheus-operated.istio-prometheus.svc.cluster.local
            destination.service.name:
              stringValue: prometheus-operated
            destination.service.namespace:
              stringValue: istio-prometheus
            destination.service.uid:
              stringValue: istio://istio-prometheus/services/prometheus-operated
            source.namespace:
              stringValue: istio-stability-looper
            source.uid:
              stringValue: kubernetes://server-7677bd45c5-r7scx.istio-stability-looper
        transport:
          checkCluster: outbound|9091||istio-policy.istio-system.svc.cluster.local
          networkFailPolicy:
            baseRetryWait: 0.080s
            maxRetryWait: 1s
            policy: FAIL_CLOSE
          reportBatchMaxEntries: 100
          reportBatchMaxTime: 1s
          reportCluster: outbound|9091||istio-telemetry.istio-system.svc.cluster.local
    - name: envoy.tcp_proxy
      typedConfig:
        '@type': type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy
        cluster: BlackHoleCluster
        statPrefix: BlackHoleCluster
  - filters:
    - name: mixer
      typedConfig:
        '@type': type.googleapis.com/istio.mixer.v1.config.client.TcpClientConfig
        disableCheckCalls: true
        mixerAttributes:
          attributes:
            context.proxy_version:
              stringValue: 1.3.0
            context.reporter.kind:
              stringValue: outbound
            context.reporter.uid:
              stringValue: kubernetes://server-7677bd45c5-r7scx.istio-stability-looper
            destination.service.host:
              stringValue: prometheus-operated.istio-prometheus.svc.cluster.local
            destination.service.name:
              stringValue: prometheus-operated
            destination.service.namespace:
              stringValue: istio-prometheus
            destination.service.uid:
              stringValue: istio://istio-prometheus/services/prometheus-operated
            source.namespace:
              stringValue: istio-stability-looper
            source.uid:
              stringValue: kubernetes://server-7677bd45c5-r7scx.istio-stability-looper
        transport:
          checkCluster: outbound|9091||istio-policy.istio-system.svc.cluster.local
          networkFailPolicy:
            baseRetryWait: 0.080s
            maxRetryWait: 1s
            policy: FAIL_CLOSE
          reportBatchMaxEntries: 100
          reportBatchMaxTime: 1s
          reportCluster: outbound|9091||istio-telemetry.istio-system.svc.cluster.local
    - name: envoy.tcp_proxy
      typedConfig:
        '@type': type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy
        cluster: outbound|9090||prometheus-operated.istio-prometheus.svc.cluster.local
        statPrefix: outbound|9090||prometheus-operated.istio-prometheus.svc.cluster.local
  - filterChainMatch:
      applicationProtocols:
      - http/1.1
      - http/1.0
    filters:
    - name: envoy.http_connection_manager
      typedConfig:
        '@type': type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
        generateRequestId: true
        httpFilters:
        - name: mixer
          typedConfig:
            '@type': type.googleapis.com/istio.mixer.v1.config.client.HttpClientConfig
            defaultDestinationService: default
            forwardAttributes:
              attributes:
                source.uid:
                  stringValue: kubernetes://server-7677bd45c5-r7scx.istio-stability-looper
            mixerAttributes:
              attributes:
                context.proxy_version:
                  stringValue: 1.3.0
                context.reporter.kind:
                  stringValue: outbound
                context.reporter.uid:
                  stringValue: kubernetes://server-7677bd45c5-r7scx.istio-stability-looper
                source.namespace:
                  stringValue: istio-stability-looper
                source.uid:
                  stringValue: kubernetes://server-7677bd45c5-r7scx.istio-stability-looper
            serviceConfigs:
              default:
                disableCheckCalls: true
            transport:
              checkCluster: outbound|9091||istio-policy.istio-system.svc.cluster.local
              networkFailPolicy:
                baseRetryWait: 0.080s
                maxRetryWait: 1s
                policy: FAIL_CLOSE
              reportBatchMaxEntries: 100
              reportBatchMaxTime: 1s
              reportCluster: outbound|9091||istio-telemetry.istio-system.svc.cluster.local
        - name: envoy.cors
        - name: envoy.fault
        - name: envoy.router
        normalizePath: true
        rds:
          configSource:
            ads: {}
            initialFetchTimeout: 0s
          routeConfigName: '9090'
        statPrefix: 0.0.0.0_9090
        streamIdleTimeout: 0s
        tracing:
          clientSampling:
            value: 100
          operationName: EGRESS
          overallSampling:
            value: 100
          randomSampling:
            value: 1
        upgradeConfigs:
        - upgradeType: websocket
        useRemoteAddress: false
  listenerFilters:
  - name: envoy.listener.http_inspector
  listenerFiltersTimeout: 0.010s
  name: 0.0.0.0_9090
  trafficDirection: OUTBOUND
```
