### ISSUE TITLE
Helm file values-istio-demo.yaml is wrong

### ISSUE THREAD

**Issue by israel-hdez** [istio/istio#16774]
**Bug description**

The `install/kubernetes/helm/istio/values-istio-demo.yaml` available in the released package defines the "global" key twice. There is one definition at the top:

```yaml
global:
  proxy:
    accessLogFile: "/dev/stdout"
    resources:
      requests:
        cpu: 10m
        memory: 40Mi

  disablePolicyChecks: false
```

and one at the bottom:

```yaml
# @include <values-istio-demo-common.yaml>
#
global:
  controlPlaneSecurityEnabled: false

  mtls:
    # Default setting for service-to-service mtls. Can be set explicitly using
    # destination rules or service annotations.
    enabled: false
```

When rendering with:

`helm template install/kubernetes/helm/istio --name istio --namespace istio-system -f install/kubernetes/helm/istio/values-istio-demo.yaml`

definitions are not merged, but the second one completely overwrites the first one. So, the rendered template is not suitable for small envs.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Perhaps, the `values-istio-demo.yaml` file provided in the released package should define `global` only once, with merged values.

**Steps to reproduce the bug**
It's all in the bug description :)

FYI: I discovered this because I was trying to setup a multi-cluster env using instructions in https://istio.io/docs/setup/kubernetes/install/multicluster/gateways/. But I wanted a _demo_ profile _plus_ multi-cluster. So, I was trying:

```bash
helm template install/kubernetes/helm/istio --name istio --namespace istio-system \
    -f install/kubernetes/helm/istio/values-istio-demo.yaml \
    -f install/kubernetes/helm/istio/example-values/values-istio-multicluster-gateways.yaml
```

which was generating a yaml not suitable for small envs (thus pods not starting because insufficient cpu).

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio: 1.2.4
Helm: 2.14.3

**How was Istio installed?**
N/A

**Environment where bug was observed (cloud vendor, OS, etc)**
minikube
