### ISSUE TITLE
httpsRedirect at Gateway causes redirect loop when used in AWS EKS with ACM cert

### ISSUE THREAD

**Issue by mariusmitrofan** [istio/istio#16778]
**Bug description**
When used in AWS EKS, the release version 1.2.5 of istio (installed using helm), causes a continuous HTTPS redirect loop if the value of `tls.httpsRedirect` is set to `true` at the Gateway level.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Should not cause HTTPS redirect loop

**Steps to reproduce the bug**
Start an AWS EKS cluster and deploy istio 1.2.5

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.8-eks-a977ba", GitCommit:"a977bab148535ec195f12edc8720913c7b943f9c", GitTreeState:"clean", BuildDate:"2019-07-29T20:47:04Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
$ istioctl version --remote
client version: 1.2.5
citadel version: 1.2.5
egressgateway version: 1.2.5
galley version: 1.2.5
ingressgateway version: 1.2.5
pilot version: 1.2.5
policy version: 1.2.5
sidecar-injector version: 1.2.5
telemetry version: 1.2.5
```

**How was Istio installed?**
Using helm

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS

**Relevant information**

This is the export of the gateway:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - '*'
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - '*.staging.some.domain'
      port:
        name: https
        number: 443
        protocol: HTTP
```
And this is the export of the virtualservice:
```
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: image-service
  namespace: sip
spec:
  gateways:
  - my-gateway.istio-system.svc.cluster.local
  hosts:
  - img.staging.some.domain
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: image-service.sip.svc.cluster.local
        port:
          number: 80
```

I have checked all logs within the custom service and the requests do *not* reach the container, meaning that the redirect loop happens somewhere within the istio system.

Sample ->
```
$ curl -iL https://img.staging.some.domain/
HTTP/1.1 301 Moved Permanently
location: https://img.staging.some.domain/
date: Tue, 03 Sep 2019 18:27:30 GMT
server: istio-envoy
content-length: 0

HTTP/1.1 301 Moved Permanently
location: https://img.staging.some.domain/
date: Tue, 03 Sep 2019 18:27:30 GMT
server: istio-envoy
content-length: 0

HTTP/1.1 301 Moved Permanently
location: https://img.staging.some.domain/
date: Tue, 03 Sep 2019 18:27:30 GMT
server: istio-envoy
content-length: 0

HTTP/1.1 301 Moved Permanently
location: https://img.staging.some.domain/
date: Tue, 03 Sep 2019 18:27:31 GMT
server: istio-envoy
content-length: 0

HTTP/1.1 301 Moved Permanently
location: https://img.staging.some.domain/
date: Tue, 03 Sep 2019 18:27:31 GMT
server: istio-envoy
content-length: 0
```

Furthermore, if the definition of `tls.httpsRedirect: true` is removed from the Gateway, the service acts and behaves normally (there's just no redirect from HTTP to HTTPS), meaning that both http://img.staging.some.domain/ and ttps://img.staging.some.domain/ simply reply to the request.

Any thoughts on this ?

**Comment by howardjohn** [comment]
do you know if this happened on older releases? specifically like 1.2.2? we had a similar issue fixed since then, but I suspect the root cause is different

I'll try to reproduce this

**Comment by mariusmitrofan** [comment]
The istio install was done from scratch, so I wouldn't know...

**Comment by mariusmitrofan** [comment]
@howardjohn  any luck ... ?

**Comment by mariusmitrofan** [comment]
@howardjohn I've deployed an nginx container with istio and disabled the `tls.httpsRedirect: true` option at the gateway level.

What I noticed through "x" amount of logs is that the istio-proxy sidecar is the "culprit" for this redirect loop, I just don't know how/where the bug happens within the code...

**Comment by mariusmitrofan** [comment]
@howardjohn I think I found out the reason why.

When you are using an AWS ELB with AWS Certificate Manager support that is set up at ELB level, COMBINED with `protocol: HTTP` for the istio gateway, it *ALWAYS* pushes the header `x-forwarded-proto` as `http`, causing a redirect loop because it's continuously trying to update it to `https`, while keeping it as `http` after the request comes in :)

IN SHORT, if the following conditions apply:
1) `Gateway` is set up as following for `https`:
```
    - hosts:
        - '*.staging.sip.onl'
      port:
        name: https
        number: 443
        protocol: HTTP
```
<AND>
2) Istio was deployed using this config for the `gateway` resource in helm:
```
gateways:
  istio-ingressgateway:
    serviceAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "SOME_CERTIFI_CATE_HERE"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: 443
```

THEN THE FOLLOWING HAPPENS:
The header `x-forwarded-proto` is always applied for each request, even if `tls. httpsRedirect` is set to `true`.

POSSIBLE SOLUTION:

IF config for `tls.httpsRedirect` is set to `true`, THEN first make sure that the `x-forwarded-proto` header is not already `https` :)

PS: My logic may be stupid, but you get the idea...

**Comment by rshriram** [comment]
This seems like a data plane addition doesn't it? as Pilot will not know the value of x-forward-proto in advance

**Comment by rshriram** [comment]
cc @istio/wg-networking-maintainers-data-plane PTAL

**Comment by rshriram** [comment]
cc @PiotrSikora / @lizan / @lambdai

**Comment by PiotrSikora** [comment]
@mariusmitrofan If I'm reading this correctly, your setup looks as follows:
```
[client] --> [ELB] --> [istio-ingressgateway] --> [istio-proxy] --> [service]
```
ELB is presumably terminating TLS, so the request flow looks like this:
```
[client] --https--> [ELB terminating TLS] --http--> [istio-ingressgateway redirecting to https]
```
i.e. since ELB is terminating TLS, IngressGateway always receives HTTP traffic, which triggers the redirect to HTTPS.

What's missing is the ability to let IngressGateway know that the proxy in front of it is a trusted hop and that it should respect `x-forwarded-proto` it receives from it (see: #7679). I thought that we have the ability to configure this, but looking at the code and the linked issue, it doesn't look that's the case.

**Comment by mariusmitrofan** [comment]
@PiotrSikora Yup. Sounds right to me.

**Comment by mariusmitrofan** [comment]
@PiotrSikora do you think it's possible to implement this? Can I help somehow?

**Comment by PiotrSikora** [comment]
@mariusmitrofan yes, it should be relatively easy to support, you just need to:
- set `externalTrafficPolicy` to `Local` (this is already exposed in Istio),
- configure `XffNumTrustedHops` to 1 or more (this doesn't seem to be exposed in Istio yet).

Since this is a Pilot change, @istio/wg-networking-maintainers-pilot should be able to help.

**Comment by rshriram** [comment]
For XFF num trusted hops, please look at the EnvoyFilter example.. 
https://github.com/istio/api/blob/master/networking/v1alpha3/envoy_filter.proto#L99 [make sure to use typed config]

**Comment by mariusmitrofan** [comment]
@rshriram / @PiotrSikora 

I've done the following:
1) set the `externalTrafficPolicy` to `Local` on the istio-ingressgateway (and double-checked it by describing the service)
2) added back the option `tls.httpsRedirect: true` on the gateway
3) configured my VirtualServices to match the logic described in https://github.com/istio/istio/issues/7964 by @GregoireW:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: xxxxx
  namespace: yyyyy
spec:
  hosts:
    - "zzzzzz"
  gateways:
    - istio-system/http-gateway
  http:
  - route:
    - destination:
        host: aaaaaaaa
        port:
          number: 8080
    headers:
      request:
        set:
          x-forwarded-proto: https
          x-forwarded-port: "443"
```

What happens now is that:
1) I don't suffer from https redirect loop (yeeey ... ?!)
2) The https redirect doesn't work :))...

Sample ->
```
$ curl -iL http://${HOSTNAME}
HTTP/1.1 200 OK
server: istio-envoy
date: Wed, 25 Sep 2019 09:39:14 GMT
content-type: text/html
content-length: 1580
last-modified: Fri, 20 Sep 2019 11:20:46 GMT
vary: Accept-Encoding
etag: "5d84b60e-62c"
expires: Wed, 25 Sep 2019 09:44:14 GMT
cache-control: max-age=300
accept-ranges: bytes
x-envoy-upstream-service-time: 1

<!DOCTYPE html><html>MY_WEBPAGE_HTML_HERE</html>
```


Am I doing something stupid ... ?

PS: Same thing happens with bot `tls.httpRedirect: true` and without it...

**Comment by crhuber** [comment]
We are also having the same issue: Adding this to the virtual service worked

```
  http:
  - route:
    - destination:
        host: aaaaaaaa
        port:
          number: 8080
    headers:
      request:
        set:
          x-forwarded-proto: https
          x-forwarded-port: "443"
```
