### ISSUE TITLE
Route traffic for multiple hosts through egress gateway doesn't work

### ISSUE THREAD

**Issue by jfeddern** [istio/istio#16806]
**Bug description**

Hi there,
we are trying to route our whole external traffic through the egress gateway. I started with a simple example (configuring external traffic to google and cnn) but unfortunately this doesn't work and I receive the following error, when trying to access https://edition.cnn.com

```
curl -sL -o /dev/null -D - https://edition.cnn.com -v
* Rebuilt URL to: https://edition.cnn.com/
*   Trying 151.101.193.67...
* Connected to edition.cnn.com (151.101.193.67) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 692 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* SSL: certificate subject name (www.google.com) does not match target host name 'edition.cnn.com'
* Closing connection 0
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Traffic should be routed to google and cnn.

**Steps to reproduce the bug**

1. Configure egress traffic through egress gateway for www.google.com
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google
  namespace: istio-system
spec:
  hosts:
  - www.google.com
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dr-for-google
  namespace: istio-system
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: google
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: ISTIO_MUTUAL
          sni: www.google.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-google-through-egress-gateway
  namespace: istio-system
spec:
  hosts:
  - www.google.com
  gateways:
  - mesh
  - istio-egressgateway
  tls:
  - match:
    - gateways:
      - mesh
      port: 443
      sni_hosts:
      - www.google.com
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: google
        port:
          number: 443
  tcp:
  - match:
    - gateways:
      - istio-egressgateway
      port: 443
    route:
    - destination:
        host: www.google.com
        port:
          number: 443
      weight: 100
```

2. Configure egress gateway
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
  namespace: istio-system
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: tls
      protocol: TLS
    hosts:
    - '*'
    tls:
      mode: MUTUAL
      serverCertificate: /etc/certs/cert-chain.pem
      privateKey: /etc/certs/key.pem
      caCertificates: /etc/certs/root-cert.pem
```

Accessing www.google.com works as expected and traffic is routed through the egress gateway:
```
curl -sL -o /dev/null -D - https://www.google.com    
HTTP/1.1 200 OK
```

3. Configure egress traffic through egress gateway for edition.cnn.com
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cnn
  namespace: istio-system
spec:
  hosts:
    - edition.cnn.com
  ports:
    - number: 443
      name: tls
      protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dr-for-cnn
  namespace: istio-system
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
    - name: cnn
      trafficPolicy:
        loadBalancer:
          simple: ROUND_ROBIN
        portLevelSettings:
          - port:
              number: 443
            tls:
              mode: ISTIO_MUTUAL
              sni: edition.cnn.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-cnn-through-egress-gateway
  namespace: istio-system
spec:
  hosts:
    - edition.cnn.com
  gateways:
    - mesh
    - istio-egressgateway
  tls:
    - match:
        - gateways:
            - mesh
          port: 443
          sni_hosts:
            - edition.cnn.com
      route:
        - destination:
            host: istio-egressgateway.istio-system.svc.cluster.local
            subset: cnn
            port:
              number: 443
  tcp:
    - match:
        - gateways:
            - istio-egressgateway
          port: 443
      route:
        - destination:
            host: edition.cnn.com
            port:
              number: 443
          weight: 100
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istio version
```
client version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.4-10-g9b6d31b"}
citadel version: version.BuildInfo{Version:"1.1.7", GitRevision:"26db5587902e21903832b184d6d971f338591ce9-dirty", User:"travis", Host:"travis-job-istio-istio-17578871.travisci.net", GolangVersion:"go1.11.10", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:""}
egressgateway version: version.BuildInfo{Version:"1.1.7", GitRevision:"26db5587902e21903832b184d6d971f338591ce9-dirty", User:"travis", Host:"travis-job-istio-istio-17578871.travisci.net", GolangVersion:"go1.11.10", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:""}
galley version: version.BuildInfo{Version:"1.1.7", GitRevision:"26db5587902e21903832b184d6d971f338591ce9-dirty", User:"travis", Host:"travis-job-istio-istio-17578871.travisci.net", GolangVersion:"go1.11.10", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:""}
ingressgateway version: version.BuildInfo{Version:"1.1.7", GitRevision:"26db5587902e21903832b184d6d971f338591ce9-dirty", User:"travis", Host:"travis-job-istio-istio-17578871.travisci.net", GolangVersion:"go1.11.10", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:""}
pilot version: version.BuildInfo{Version:"1.1.7", GitRevision:"26db5587902e21903832b184d6d971f338591ce9-dirty", User:"travis", Host:"travis-job-istio-istio-17578871.travisci.net", GolangVersion:"go1.11.10", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:""}
policy version: version.BuildInfo{Version:"1.1.7", GitRevision:"26db5587902e21903832b184d6d971f338591ce9-dirty", User:"travis", Host:"travis-job-istio-istio-17578871.travisci.net", GolangVersion:"go1.11.10", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:""}
sidecar-injector version: version.BuildInfo{Version:"1.1.7", GitRevision:"26db5587902e21903832b184d6d971f338591ce9-dirty", User:"travis", Host:"travis-job-istio-istio-17578871.travisci.net", GolangVersion:"go1.11.10", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:""}
telemetry version: version.BuildInfo{Version:"1.1.7", GitRevision:"26db5587902e21903832b184d6d971f338591ce9-dirty", User:"travis", Host:"travis-job-istio-istio-17578871.travisci.net", GolangVersion:"go1.11.10", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:""}
```
kubectl version
```
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10+IKS", GitCommit:"03a1dfa2328c01886a41cdd08e9b91bfff3a4b4d", GitTreeState:"clean", BuildDate:"2019-08-21T11:54:44Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Helm

**Additional informations**
I already tried different ways to configure this (one ServiceEntry, VirtualService, DestinationRule for both hosts and also single ServiceEntry, VirtualService, DestinationRule for each host).

If I configure cnn first than the request to cnn is working but after configuring google this request is not working anymore. Am I doing something wrong?

Saw this issue already https://github.com/istio/istio/issues/9897 but the provided solution within this issue didn't solve my problem.

Kind regards,
Jan

**Comment by jfeddern** [comment]
Here is another sample configuration:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: https-se
  namespace: istio-system
spec:
  hosts:
    - www.google.com
    - edition.cnn.com
  ports:
    - number: 443
      name: tls
      protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dr-for-https
  namespace: istio-system
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: google
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: ISTIO_MUTUAL
          sni: www.google.com
  - name: cnn
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
        - port:
            number: 443
          tls:
            mode: ISTIO_MUTUAL
            sni: edition.cnn.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: google-cnn
  namespace: istio-system
spec:
  hosts:
    - www.google.com
    - edition.cnn.com
  gateways:
    - mesh
    - istio-egressgateway
  tls:
    - match:
        - gateways:
            - mesh
          port: 443
          sni_hosts:
            - www.google.com
      route:
        - destination:
            host: istio-egressgateway.istio-system.svc.cluster.local
            subset: google
            port:
              number: 443
    - match:
        - gateways:
            - mesh
          port: 443
          sni_hosts:
            - edition.cnn.com
      route:
        - destination:
            host: istio-egressgateway.istio-system.svc.cluster.local
            subset: cnn
            port:
              number: 443
  tcp:
    - match:
        - gateways:
            - istio-egressgateway
          port: 443
      route:
        - destination:
            host: www.google.com
            port:
              number: 443
          weight: 100
    - match:
        - gateways:
            - istio-egressgateway
          port: 443
      route:
        - destination:
            host: edition.cnn.com
            port:
              number: 443
          weight: 100
```

Which lead to the same error. Within the pilot logs I can see the following message:
```
"ProxyStatus": {
        "pilot_conflict_outbound_listener_tcp_over_current_tcp": {
            "0.0.0.0:443": {
                "proxy": "utils-6b75cb7cd9-46vjn.core-app-xsp",
                "message": "Listener=0.0.0.0:443 AcceptedTCP=edition.cnn.com RejectedTCP=www.google.com TCPServices=1"
            }
        },
```

**Comment by rshriram** [comment]
cc @vadimeisenbergibm

**Comment by vadimeisenbergibm** [comment]
@jfeddern 

The solution is to use your initial configuration, but with two different `Gateway` resources, for example `istio-egressgateway-google` and `istio-egressgateway-cnn`, and reference these gateways in the VirtualServices.

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway-google
  namespace: istio-system
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: tls
      protocol: TLS
    hosts:
    - 'www.google.com'
    tls:
      mode: MUTUAL
      serverCertificate: /etc/certs/cert-chain.pem
      privateKey: /etc/certs/key.pem
      caCertificates: /etc/certs/root-cert.pem
```

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway-cnn
  namespace: istio-system
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: tls
      protocol: TLS
    hosts:
    - 'edition.cnn.com'
    tls:
      mode: MUTUAL
      serverCertificate: /etc/certs/cert-chain.pem
      privateKey: /etc/certs/key.pem
      caCertificates: /etc/certs/root-cert.pem
```

**Comment by vadimeisenbergibm** [comment]
@jfeddern closing the issue, please let me know if it does not work for you.

**Comment by IsharaPannila** [comment]
> `Gateway`

This means having multiple gateways is an acceptable solution?
I have multiple on-prem services hosted in different servers which requires mutual TLS. So is it recommended to have multiple egress gateways configured with mTLS origination to access those?

**Comment by SohamJ** [comment]
Does anyone (or @vadimeisenbergibm) know if this is this documented anywhere in the Istio docs? Trying to understand why one Gateway cannot route the traffic for multiple hosts? Does Istio do a 1-1 mapping between the port and the host? 

It works, but trying to understand why

When traffic is routed to the gateway based on the VirtualService destination route, I would assume it passes the SNI header as well which the gateway might be able to use to narrow down the host? I may have misunderstood the flow, so wondering if this is documented somewhere to understand it better.

For example:
```yaml
# virtual service
  - match:
    - gateways:
      - my-egress-gateway
      port: 443
     # use this to distinguish other host my-host2.com when the traffic is to be routed from the gateway
      sniHosts:
      - my-host.com
    route:
    - destination:
        host: my-host.com
        port:
          number: 443
      weight: 100
```

I refered to this page but that only talks about splitting the VirtualService: https://preliminary.istio.io/latest/docs/ops/best-practices/traffic-management/#configuring-multiple-tls-hosts-in-a-gateway
