### ISSUE TITLE
Resource rename flag for manifest diff command

### ISSUE THREAD

**Issue by ostromart** [istio/istio#16826]
Sometimes, resources in manifests are renamed, which causes them to appear as deleted/added. In this case it also becomes difficult to diff the two resources as they need to be renamed back manually. 
The request is to have a flag like --renamed which simply takes a list of values like
kind1:namespace1:name1->newkind1:newnamespace1:newname1, kind2:namespace2...
This says that kind1:namespace1:name1 is now called newkind1:newnamespace1:newname1 in the second manifest and they are the same resource. 
Ideally wildcards would also be supported e.g. 
Service:*:istio-pilot->Service:*:istio-control, *:*:istio-citadel->*:*:istio-ca

**Comment by elfinhe** [comment]
An example:

``` yaml
apiVersion: v1
kind: Service
metadata:
  # Must match the certificate, this is used in the node agent in same namespace.
  name: istio-citadel
  namespace: istio-system
  labels:
    app: citadel
    istio: citadel
    release: istio

spec:
  ports:
    - name: grpc-citadel
      port: 8060
      targetPort: 8060
      protocol: TCP
    - name: http-monitoring
      port: 15014
  selector:
    app: citadel
```
``` yaml
apiVersion: v1
kind: Service
metadata:
  # Must match the certificate, this is used in the node agent in same namespace.
  name: istio-ca
  namespace: istio-system
  labels:
    app: citadel
    istio: citadel
    release: istio

spec:
  ports:
    - name: grpc-citadel
      port: 8060
      targetPort: 8060
      protocol: TCP
    - name: http-monitoring
      port: 15014
  selector:
    app: citadel
```
