### ISSUE TITLE
Ability to diff ConfigMaps in istio manifest

### ISSUE THREAD

**Issue by ostromart** [istio/istio#16828]
ConfigMaps are typically text blocks of YAML and are unmarshaled as a single string, making YAML diffing impossible. Try making a small change in ConfigMap:istio-system:istio data.mesh and diffing the result with manifest diff to see the problem.
Some possible solutions:
1. Automatically try to unmarshal ConfigMap data string into YAML and if that succeeds, do a YAML diff of the result.
2. Add a flag like --is-yaml which is a list of paths that are known to be YAML strings

**Comment by elfinhe** [comment]
An example of ConfigMaps:
```yaml
kind: ConfigMap
data:
  validatingwebhookconfiguration.yaml: |-    
    apiVersion: admissionregistration.k8s.io/v1beta1
    kind: ValidatingWebhookConfiguration
    metadata:
      name: istio-galley
```
