### ISSUE TITLE
Unable to access the Kubernetes apiserver when injecting the istio_proxy sidecar

### ISSUE THREAD

**Issue by secat** [istio/istio#1685]
When I inject the `istio_proxy` sidecar, my pod's main container which needs to access the Kubernetes apiserver can't reach it and receives socket errors:
```
fleet/svc/index/service/service.go:49: Failed to list *v1beta1.Ingress: Get https://10.0.0.1:443/apis/extensions/v1beta1/namespaces/fleet/ingresses?resourceVersion=0: dial tcp 10.0.0.1:443: getsockopt: connection refused
```

Here are some error logs from the `istio_proxy` sidecar:
```
[2017-11-08 13:06:45.064][15][warning][config] external/envoy/source/server/listener_manager_impl.cc:248] error adding listener: 'tcp_172.17.0.13_9999' has duplicate address '172.17.0.13:9999' as existing listener
[2017-11-08 13:06:45.064][15][warning][upstream] external/envoy/source/server/lds_subscription.cc:65] lds: fetch failure: error adding listener: 'tcp_172.17.0.13_9999' has duplicate address '172.17.0.13:9999' as existing listener
```

The istio version used are:
- 0.2.10
- 0.2.12

The Kubernetes version is 1.7.5

**Comment by sbezverk** [comment]
@secat I tried to access api server from the main container by using this command:
curl -k -X GET \
  -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
  https://$KUBERNETES_PORT_443_TCP_ADDR:$KUBERNETES_SERVICE_PORT_HTTPS

And I do not see any issue. The difference here is istio version, I am using master version. Is there any chance you could try your application with the lates istio bits?

**Comment by GregHanson** [comment]
@secat are you still seeing this problem on istio version 0.5.1 or later?

**Comment by secat** [comment]
@GregHanson I am currently updating my system in order to evaluate istio version 0.5.1. As soon as I am done, I will let you know.

Thank you.

**Comment by secat** [comment]
@GregHanson I am still receiving errors of type:
```
Failed to list *v1.ConfigMap: Get https://10.96.0.1:443/api/v1/namespaces/fleet/configmaps?resourceVersion=0: dial tcp 10.96.0.1:443: getsockopt: connection refused
```

with istio version 0.5.1.

Here is an example of the sidecar that was injected with `istioctl kube-inject`:
```
  - args:
    - proxy
    - sidecar
    - --configPath
    - /etc/istio/proxy
    - --binaryPath
    - /usr/local/bin/envoy
    - --serviceCluster
    - istio-proxy
    - --drainDuration
    - 2s
    - --parentShutdownDuration
    - 3s
    - --discoveryAddress
    - servicemesh-pilot.istio-system:15003
    - --discoveryRefreshDelay
    - 1s
    - --zipkinAddress
    - zipkin.fleet:9411
    - --connectTimeout
    - 1s
    - --statsdUdpAddress
    - servicemesh-mixer.istio-system:9125
    - --proxyAdminPort
    - "15000"
    - --controlPlaneAuthPolicy
    - NONE
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: INSTANCE_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    image: docker.io/istio/proxy:0.5.1
    imagePullPolicy: IfNotPresent
    name: istio-proxy
    resources: {}
    securityContext:
      privileged: false
      readOnlyRootFilesystem: true
      runAsUser: 1337
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/istio/proxy
      name: istio-envoy
    - mountPath: /etc/certs/
      name: istio-certs
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-bkzwc
      readOnly: true
```
