### ISSUE TITLE
Add NetworkPolicy to allow Istio to run on a secure Kubernetes Platform

### ISSUE THREAD

**Issue by tobiasgiese** [istio/istio#16877]
**Describe the feature request**
On a secure Kubernetes Platform all ingress connections are dropped by default.
To guarantee istio to run properly in this case we need one "allow all" `NetworkPolicy` or several 
fine-grained policies.

~~**Describe alternatives you've considered**~~
**Workaround we applied**
To allow all traffic we added the following `NetworkPolicy`.

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: istio-allow-all
  namespace: istio-system
spec:
  podSelector: {}
  ingress:
    - {}
  policyTypes:
    - Ingress
```

**Affected product area (please put an X in all that apply)**

[x] Configuration Infrastructure
[ ] Docs
[x] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
