### ISSUE TITLE
VirtualService is ignored if Gateway does not exist

### ISSUE THREAD

**Issue by linjmeyer** [istio/istio#16883]
**Bug description**
A VirtualService with a non-existent gateway is accepted by Istio when applied to a Kubernetes cluster, but is then ignored and not used in routing decisions including in local cluster traffic.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Either:
1. The VirtualService would work correctly for local cluster traffic where the non-existent gateway is not needed for routing.  
2. The VirtualService should be rejected as invalid when applied to the cluster until the gateway is removed or created

**Steps to reproduce the bug**

You will need a REST API that returns a value like "canary" or "prod" or some other value that allows you to determine if routing is working correctly.  Deploy the API behind a VirtualService and DestinationRule like:

```yaml
---
# Source: web-istio-simple/templates/destinationrule.yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
# Include all subsets (prod, canary)
# The VirtualService will decide when to route to the correct subset
# So for simplicity we can leave them all here all the time
metadata:  
  name: myapp 
  namespace: mynamespace
spec:
  host: myapp.mynamespace.svc.cluster.local
  subsets:
  - name: "prod"
    labels:
      app: myapp
      environment: "prod"
  - name: "canary"
    labels:
      app: myapp
      environment: "canary"
---
# Source: web-istio-simple/templates/virtualservice.yaml

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:  
  name: myapp 
  namespace: mynamespace
spec:
  gateways:
   - "my-missing-gateway" # This gateway does not exist
  hosts:
  - myapp.mynamespace.svc.cluster.local
    
  http:
   ### Canary routing
    - match:  
      - headers:
          x-my-version: 
            exact: "canary"
      route:
      - destination:
          host: myapp.mynamespace.svc.cluster.local
          subset: "canary"
    ### Prod routing
    - route:
      - destination:
          host: myapp.mynamespace.svc.cluster.local
          subset: "prod"
```

This setup should check for a header "X-MY-Version: canary" and route traffic to the canary deployment, otherwise traffic should go to prod.

To test this shell into a container in the same cluster with curl or wget and hit the endpoint several times.  You will see responses from canary without setting the canary header:

`curl http://myapp.mynamespace.svc.cluster.local/api/values`

Response: `{"CLOUD_ENVIRONMENT":"CANARY"}`

Remove the missing gateway from the above VirtualService, re-apply and test curl again.  You will be routed to prod without the canary, or to canary with the header set.  This shows the VirtualService is now working as expected:

`curl http://myapp.mynamespace.svc.cluster.local/api/values`

Response: `{"CLOUD_ENVIRONMENT":"PRODUCTION"}`

`curl --header "X-MY-VERSION: canary" http://myapp.mynamespace.svc.cluster.local/api/values`

Response: `{"CLOUD_ENVIRONMENT":"CANARY"}`

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

kubectl server: 

```bash
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.8", GitCommit:"7d3d6f113e933ed1b44b78dff4baf649258415e5", GitTreeState:"clean", BuildDate:"2019-06-19T16:37:16Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```

istioctl: 

```bash
client version: version.BuildInfo{Version:"1.1.8", GitRevision:"145b18a441045d6fad33d7916380d8642c7bf21d-dirty", User:"brew", Host:"Mojave.local", GolangVersion:"go1.12.5", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.8"}
citadel version: version.BuildInfo{Version:"1.2.2", GitRevision:"cd4a148f37dc386986d6a6d899778849e686beea-dirty", User:"root", Host:"1a067c3a-98fa-11e9-95c6-bef141052020", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.1-3-gcd4a148"}
galley version: version.BuildInfo{Version:"1.2.2", GitRevision:"cd4a148f37dc386986d6a6d899778849e686beea-dirty", User:"root", Host:"1a067c3a-98fa-11e9-95c6-bef141052020", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.1-3-gcd4a148"}
ingressgateway version: version.BuildInfo{Version:"1.2.2", GitRevision:"cd4a148f37dc386986d6a6d899778849e686beea", User:"root", Host:"1a067c3a-98fa-11e9-95c6-bef141052020", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.2.1-3-gcd4a148"}
pilot version: version.BuildInfo{Version:"1.2.2", GitRevision:"cd4a148f37dc386986d6a6d899778849e686beea-dirty", User:"root", Host:"1a067c3a-98fa-11e9-95c6-bef141052020", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.1-3-gcd4a148"}
policy version: version.BuildInfo{Version:"1.2.2", GitRevision:"cd4a148f37dc386986d6a6d899778849e686beea-dirty", User:"root", Host:"1a067c3a-98fa-11e9-95c6-bef141052020", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.1-3-gcd4a148"}
sidecar-injector version: version.BuildInfo{Version:"1.2.2", GitRevision:"cd4a148f37dc386986d6a6d899778849e686beea-dirty", User:"root", Host:"1a067c3a-98fa-11e9-95c6-bef141052020", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.1-3-gcd4a148"}
telemetry version: version.BuildInfo{Version:"1.2.2", GitRevision:"cd4a148f37dc386986d6a6d899778849e686beea-dirty", User:"root", Host:"1a067c3a-98fa-11e9-95c6-bef141052020", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.1-3-gcd4a148"}
```

**How was Istio installed?**

`Helm Template version 1.2.2`

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
