### ISSUE TITLE
Sidecar config doesn't work when using port in egress

### ISSUE THREAD

**Issue by linsun** [istio/istio#16885]
**Bug description**
Using a simple sidecar config for a given namespace (namespace-a), mostly following the sidecar reference doc example, resulted with service A in namespace-a communicates to service B in namespace-b in 502 error.

```
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
spec:
  ingress:
  - port:
      number: 9080
      protocol: HTTP
      name: somename
    defaultEndpoint: 127.0.0.1:9080
  egress:
  - port:
      number: 9080
      protocol: HTTP
      name: egresshttp
    hosts:
    - "namespace-b/*"  
  - hosts:
    - "./*"
    - "istio-system/*"
```

Below does work.

```
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
spec:
  ingress:
  - port:
      number: 9080
      protocol: HTTP
      name: somename
    defaultEndpoint: 127.0.0.1:9080
  egress:
  - hosts:
    - "./*"
    - "istio-system/*"
    - "namespace-b/*" 
```

After digging through, I found out in the dynamic route config section, there is no matching route for the  external name service I built to allow service A namespace-a to access service B namespace-b.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**
1. Deploy service A in namespace-a
2. Deploy service B in namespace-b.
3. Create service B's external name service in namespace-a so that A can reach B (in namespace-b) the same way as A reach B as if B runs in namespace-a.

```
kind: Service
apiVersion: v1
metadata:  
  name: b-service
spec:  
  type: ExternalName
  externalName: b.namespace-b.svc.cluster.local
  ports:
  - name: http
    protocol: TCP
    port: 9080
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
$ istioctl version
client version: 1.3.0-rc.1
control plane version: 1.2.0

I can reproduce this in newer version.

**How was Istio installed?**
default profile

**Environment where bug was observed (cloud vendor, OS, etc)**
IBM Cloud K8s Service

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by linsun** [comment]
In talking with Frank, I tried 2other possible solutions but none worked.

1. create a SE and VS and deploy in namespace-a.

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: b-service-entry
spec:
  hosts:
  - "b"
  ports:
  - number: 9080
    name: http
    protocol: http
  resolution: DNS
```
2. create a dummy service and VS and deploy in namespace-a.

```
apiVersion: v1
kind: Service
metadata:
  name: b
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9080
      targetPort: 9080
```
Same VS is used in either 1 or 2.

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtual-service-b
spec:
  hosts:
    - b 
  http:
  - route:
    - destination:
        host: b.ns-b
        port:
          number: 9080
```

**Comment by vadimeisenbergibm** [comment]
Recreating the issue:

1. Create namespaces:

```
kubectl create namespace a
kubectl label namespace a istio-injection=enabled
kubectl create namespace b
kubectl label namespace b istio-injection=enabled
```

2. Deploy `sleep` in `a`:

```
kubectl apply -f samples/sleep/sleep.yaml -n a
```

3. Deploy `httpbin` in `b`:

```
kubectl apply -f samples/httpbin/httpbin.yaml -n b
```

**Comment by vadimeisenbergibm** [comment]
@linsun With istio-1.4.0-beta.0, it works as expected for me, see https://github.com/istio/istio/issues/16885#issuecomment-547896625

**Comment by linsun** [comment]
Thank you @vadimeisenbergibm - it does looks working for you.

I have one q - did you use external service in your example? That is the only difference i noticed.

```Create service B's external name service in namespace-a so that A can reach B (in namespace-b) the same way as A reach B as if B runs in namespace-a.```

**Comment by vadimeisenbergibm** [comment]
@linsun I did not use external services. So is the issue about ExternalName services and Sidecar? Or ExternalServices are used as a workaround? I would like to focus the problem.

**Comment by vadimeisenbergibm** [comment]
Recreated the issue. ExternalName to in-mesh services seems not to work in Istio.

1. Create namespaces:

```
kubectl create namespace a
kubectl label namespace a istio-injection=enabled
kubectl create namespace b
kubectl label namespace b istio-injection=enabled
kubectl create namespace c
kubectl label namespace c istio-injection=enabled
```

2. Deploy `sleep` in `a`, `httpbin` in `b`:

```
kubectl apply -f samples/sleep/sleep.yaml -n a
kubectl apply -f samples/httpbin/httpbin.yaml -n b
```

3. Create external name service in namespace `a`:

```
kubectl apply -n a -f - <<EOF
kind: Service
apiVersion: v1
metadata:  
  name: httpbin
spec:  
  type: ExternalName
  externalName: httpbin.b.svc.cluster.local
  ports:
  - name: http
    protocol: TCP
    port: 8000
EOF
```

4. Define a destination rule to set mTLS for the traffic to `httpbin` in `a`:

```
kubectl apply -n a -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: httpbin
spec:
  host: httpbin
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
EOF
```

5. Define a destination rule to set mTLS for the traffic to `httpbin` in `b`:

```
kubectl apply -n b -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: httpbin
spec:
  host: httpbin
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
EOF
```

6. Call `httpbin.b` from `sleep.a`:

```
kubectl exec -it $(kubectl get pod -l app=sleep -o jsonpath='{.items..metadata.name}' -n a) -c sleep -n a -- curl httpbin.b.svc.cluster.local:8000/status/418

    -=[ teapot ]=-

       _...._
     .'  _ _ `.
    | ."` ^ `". _,
    \_;`"---"`|//
      |       ;/
      \_     _/
        `"""`
```

7. Call `httpbin.a` from `sleep.a`:

```
kubectl exec -it $(kubectl get pod -l app=sleep -o jsonpath='{.items..metadata.name}' -n a) -c sleep -n a -- curl httpbin:8000/status/418
```
