### ISSUE TITLE
Istio envoy 504 gateway timeouts after 15 seconds for outbound connections

### ISSUE THREAD

**Issue by vaibhavjain882** [istio/istio#16915]
**Bug description**
istio-envoy-504-gateway-timeouts-after-15-seconds-for-outbound-connections
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
For all outbound without egress gateway and allow all policy it should not timeout.

**Steps to reproduce the bug**

Deploy istio 1.2.5 with default helm profile. Then form any pod with istio-proxy, try to make a CURL request that took more the 15 seconds to respond. You will see istio timeout in 15 seconds before getting back the response.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Version: 1.0.3
GitRevision: a44d4c8bcb427db16ca4a439adfbd8d9361b8ed3
User: root@0ead81bba27d
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean
Though I am using auto side car injection.

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-07-26T20:40:11Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-eks-5ac0f1", GitCommit:"5ac0f1d9ab2c254ea2b0ce3534fd72932094c6e1", GitTreeState:"clean", BuildDate:"2019-08-20T22:39:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
helm:

helm template install/kubernetes/helm/istio  --name istio --namespace istio-system | kubectl apply   -f -

**Environment where bug was observed (cloud vendor, OS, etc)**
cloud AWS EKS

**related Issue**
https://github.com/istio/istio/issues/6860

** StackOverflow Question with details**
https://stackoverflow.com/questions/57840104/istio-envoy-504-gateway-timeouts-after-15-seconds-for-outbound-connections

** What I tried to solve **
Created a destination rule with 30seconds timeout
Created a Virtual service with 30s timeout.

Note: Just to add the delay and I tried "curl http://slowwly.robertomurray.co.uk/delay/17000/url/http://www.google.com" (17000 = 17 seconds )from any of the microservice pod that have istio-proxy sidecar and always getting timeouts at 15 seconds. I am not sure where to change this setting.

**Comment by howardjohn** [comment]
I believe the default timeout is 15s and you cannot apply a virtualservice without a service entry so that's why setting to 30s did not work. I would suggest creating a service entry

**Comment by dileep-p** [comment]
Thanks @howardjohn . We got it working from this.  
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-se-test
spec:
  hosts:
  - slowwly.robertomurray.co.uk
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: example-http
    protocol: HTTP
  resolution: DNS
```
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: slow-ext
spec:
  hosts:
    - slowwly.robertomurray.co.uk
  http:
  - timeout: 30s
    route:
      - destination:
          host: slowwly.robertomurray.co.uk
        weight: 100
```

**Comment by howardjohn** [comment]
Great!

**Comment by p4ali** [comment]
We have some usecases need to extend the default timeout (15s), rather than per each case creating vs+se as above, wondering if there is a global setting can be configured. 
In other words, is the 15s from istion or envoy? Can it be configured? Thank you!

**Comment by jahantech** [comment]
A workaround that did the trick for me was adding an envoy filter for traffic from originating workload e.g.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: nginx-lua-filter
  namespace: nginx-ingress
spec:
  filters:
  - filterConfig:
      inlineCode: |
        function envoy_on_request(request_handle)
            request_handle:headers():add("x-envoy-upstream-rq-timeout-ms", "120000")
        end
    filterName: envoy.lua
    filterType: HTTP
    listenerMatch:
      listenerType: SIDECAR_OUTBOUND
  workloadLabels:
    app: nginx-ingress
```
