### ISSUE TITLE
Not seeing gateway info during istioctl describe

### ISSUE THREAD

**Issue by linsun** [istio/istio#16936]
**Bug description**
when gateway resource and virtual service/pod are deployed different namespaces.

I have deployed my gateway resource in Istio-systems and my VS (that refers to the gateway resource) and pod in another namespace.  When running istioctl x describe, I'm not able to see any reference to the gateway resource.  Is this expected?

examples:

```
$ istioctl x describe pod traderv2-5685c46745-zhmbw -n stock-trader
Pod: traderv2-5685c46745-zhmbw
   Pod Ports: 9080 (trader), 9443 (trader), 15090 (istio-proxy)
--------------------
Service: trader-service
   Port: http 9080/HTTP
   Port: https 9443/HTTPS
9080 DestinationRule: destination-rule-trader for "trader-service"
   Matching subsets: v2
      (Non-matching subsets v1)
   load balancer
9080 Pilot reports that pod is PERMISSIVE (enforces HTTP/mTLS) and clients speak HTTP
9443 DestinationRule: destination-rule-trader for "trader-service"
   Matching subsets: v2
      (Non-matching subsets v1)
   load balancer
9443 Pilot reports that pod is PERMISSIVE (enforces HTTP/mTLS) and clients speak HTTP
```

```
$ k get vs -n stock-trader
NAME                     GATEWAYS                        HOSTS   AGE
virtual-service-trader   [istio-system/trader-gateway]   [*]     23d
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
I would expect to be able to see the gateway resource as well.

**Steps to reproduce the bug**

- Deploy httpbin in its own namespace.
- Deploy VS for httpbin in that namespace.
- Deploy gateway resource in istio-systems
- Run istioctl describe on the httpbin pod.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
$ istioctl version
client version: 1.3.0-rc.2
control plane version: 1.2.0

**How was Istio installed?**
manually

**Environment where bug was observed (cloud vendor, OS, etc)**
IBM Cloud K8s Cluster

**Comment by esnible** [comment]
It is expected.

The version of 1.3 gets configuration from the inspected pod itself.  It only sees the virtual services on the mesh gateway.

It would be a good idea to show the virtual services and gateways attached to the Ingress-gateway.  I will look into querying an ingress-gateway Envoy and using that information to display the requested information.

**Comment by esnible** [comment]
I have an initial implementation.  I need to write tests before creating a PR.

The new additional output is
```
Looking for ingress exposure

Ingress Gateway http://169.62.244.205

VirtualService: bookinfo
   /productpage, /static*, /login, /logout, /api/v1/products*
```

Additional work is needed to verify it works correctly for NodePort clusters.
The new output isn't much but the user didn't need to run any extra commands.  Checking the ingress Envoy configuration will be the default for the command.

**Comment by esnible** [comment]
Idea: @frankbu suggests being able to look for problems similar to

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 8004
      name: http2
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - "*"
  gateways:
  - httpbin-gateway
  http:
  - route:
    - destination:
        host: httpbin
        port:
          number: 8000
```
