### ISSUE TITLE
Sticky session using consistentHash isn't working as expected in Istio 1.2.2

### ISSUE THREAD

**Issue by kish3007** [istio/istio#16937]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
i am trying to handle stickysession for my web-app using istio's destination rule like below, 3 replicas of web-app in a deployment exposed with a single service:
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: web-service.test.svc.cluster.local
  namespace: test
spec:
  host: web-service.test.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: JSESSIONID
          ttl: 40s
```
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ X] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Session persistence should be maintained instead of expring quick, and service should route to the same pod as long the cookie is alive.

**Steps to reproduce the bug**
Hit the url of web-app in multiple windows, session keeps expiring

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.2.2
**How was Istio installed?**
Using helm with default install

**Environment where bug was observed (cloud vendor, OS, etc)**
Istio-1.2.2 , kubernetes 1.13.7 in GKE.

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
