### ISSUE TITLE
Using headless service instead of endpoint in multicluster, single control-plane, multi-network configuration on EKS

### ISSUE THREAD

**Issue by Nielsoux** [istio/istio#16944]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

In a Shared control plane (multi-network) Istio installlation on EKS.
I would like to be able to reference a DNS name for my **LOCAL_GW_ADDR** instead of an IP address since ELB resolved IP addresses can vary 

**Describe alternatives you've considered**

- Reference one of the resolved IP addresses of my principal cluster's ELB hostname => it works but the IP address could change and break the setup

- Using an NLB => IP addresses are fixed but the gRPC trafic between components of the secondary cluster and the pilot (as an example) is'nt working. 

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

I'm working on a multi-cluster, shared control-plane, multi-network Istio deployment on EKS

The only way I had it working at the moment is with the istio-ingressgateway in both cluster populating TCP ELB's

cat override.yaml 
gateways:
  istio-ingressgateway:
    serviceAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "elb"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      service.beta.kubernetes.io/aws-load-balancer-internal: "true" 

Problem could come from the lack of support stated here:
https://istio.io/docs/setup/kubernetes/install/multicluster/shared-gateways/#setup-cluster-2

The command fails if the load balancer configuration doesn’t include an IP address. The implementation of DNS name support is pending.

Could this issue be resolved if, instead of populating endpoints:

```
---
# Source: istio/templates/endpoints.yaml

apiVersion: v1
kind: Endpoints
metadata:
  name: istio-pilot
  namespace: istio-system
subsets:
- addresses:
  - ip: <LOCAL_GW_ADDR>
  ports:
  - port: 15003
    name: http-old-discovery # mTLS or non-mTLS depending on auth setting
  - port: 15005
    name: https-discovery # always mTLS
  - port: 15007
    name: http-discovery # always plain-text
  - port: 15010
    name: grpc-xds # direct
  - port: 15011
    name: https-xds # mTLS or non-mTLS depending on auth setting
  - port: 8080
    name: http-legacy-discovery # direct
  - port: 15014
    name: http-monitoring
...
---
apiVersion: v1
kind: Endpoints
metadata:
  name: istio-policy
  namespace: istio-system
subsets:
- addresses:
  - ip: <LOCAL_GW_ADDR>
  ports:
  - name: grpc-mixer
    port: 9091
  - name: grpc-mixer-mtls
    port: 15004
  - name: http-monitoring
    port: 15014
...
---
apiVersion: v1
kind: Endpoints
metadata:
  name: istio-telemetry
  namespace: istio-system
subsets:
- addresses:
  - ip: <LOCAL_GW_ADDR>
  ports:
  - name: grpc-mixer
    port: 9091
  - name: grpc-mixer-mtls
    port: 15004
  - name: http-monitoring
    port: 15014
  - name: prometheus
    port: 42422
...
```

Where we are obliged to use IP addresses

We could use Headless Service where we reference the DNS name of the LoadBalancer exposing the istio-ingressgateway service from the primary cluster?

```
---
apiVersion: v1
kind: Service
metadata:
  name: istio-pilot
  namespace: istio-system
spec:
  type: ExternalName
  externalName: <ELB-DNS-NAME>
  clusterIP: None
  ports:
    - port: 15003
      name: http-old-discovery # mTLS or non-mTLS depending on auth setting
    - port: 15005
      name: https-discovery # always mTLS
    - port: 15007
      name: http-discovery # always plain-text
    - port: 15010
      name: grpc-xds # direct
    - port: 15011
      name: https-xds # mTLS or non-mTLS depending on auth setting
    - port: 8080
      name: http-legacy-discovery # direct
    - port: 15014
      name: http-monitoring
...
---
apiVersion: v1
kind: Service
metadata:
  name: istio-pilot
  namespace: istio-system
spec:
  type: ExternalName
  externalName: <ELB-DNS-NAME>
  clusterIP: None
  ports:
    - name: grpc-mixer
      port: 9091
    - name: grpc-mixer-mtls
      port: 15004
    - name: http-monitoring
      port: 15014
...
---
apiVersion: v1
kind: Service
metadata:
  name: istio-pilot
  namespace: istio-system
spec:
  type: ExternalName
  externalName: <ELB-DNS-NAME>
  clusterIP: None
  ports:
    - name: grpc-mixer
      port: 9091
    - name: grpc-mixer-mtls
      port: 15004
    - name: http-monitoring
      port: 15014
    - name: prometheus
      port: 42422
...
```

thanks in advance!
Niels

**Comment by Nielsoux** [comment]
It looks to be working,

We have now 3 EKS clusters,

For the principal cluster, We followed the doc as is, using the DNS Hostname of the loadBalancer exposing the istio-ingressgateway for the "network1" address in the istio configMap

For the secondary clusters:

We changed the helm templates to:

- [endpoints](https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/templates/endpoints.yaml): Not use them

-  [services](https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/templates/service.yaml): 
Use : 
  type: ExternalName
  externalName: < DNS Hostname >

- [configMap](https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/templates/configmap.yaml):
Always use the {{ .Values.global.remotePilotAddress }}, {{ .Values.global.remotePolicyAddress }} and {{ .Values.global.remoteTelemetryAddress }}

you can find [here](https://www.diffchecker.com/aYKRDfRa) a diff between the official configMap template and the one I used **for the secondary clusters** 

And used the DNS Hostname of the loadBalancer exposing the istio-ingressgateway of the principal cluster as LOCAL_GW_ADDR

`export LOCAL_GW_ADDR=< DNS Hostname >`

**Comment by mazzy89** [comment]
So you then have used `LOCAL_GW_ADDR` in `remotePilotAddress`, `remotePolicyAddress` and `remoteTelemetryAddress` right?

**Comment by Nielsoux** [comment]
@mazzy89 Yes, once I edited the helm templates I use the same command as stated in the documentation :)

```
helm template --name istio-remote --namespace=istio-system \
  --values install/kubernetes/helm/istio/values-istio-remote.yaml \
  --set global.mtls.enabled=true \
  --set gateways.enabled=true \
  --set security.selfSigned=false \
  --set global.controlPlaneSecurityEnabled=true \
  --set global.remoteUseDnsHostname=true \
  --set global.remotePilotAddress=${LOCAL_GW_ADDR} \
  --set global.remotePolicyAddress=${LOCAL_GW_ADDR} \
  --set global.remoteTelemetryAddress=${LOCAL_GW_ADDR} \
  --set gateways.istio-ingressgateway.env.ISTIO_META_NETWORK="network2" \
  --set global.network="network2" \
  -f override.yaml \
  install/kubernetes/helm/istio > istio-cluster-2.yaml
```

The override.yaml file being
```
gateways:
  istio-ingressgateway:
    serviceAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "elb"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
```
