### ISSUE TITLE
Improve documentation for multiple match with AND behavior

### ISSUE THREAD

**Issue by pc-rshetty** [istio/istio#16959]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
Documentation doesnt mention how to configure multiple matches for uri and header with AND behavior. 

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[Y ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
I have a regular service mock and a canary service.  I have a simple routing rule. For both regular production and canary the traffic comes to my container using ingress gateway. So i would like to match /mock to my service.  only when header has isTestUser i would like the traffic to go to the canary.     My virtual service looks like this

```apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mock-router
  labels:
    app.kubernetes.io/name: {{ include "mock-router.name" . }}
    helm.sh/chart: {{ include "mock-router.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}    
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.istio.gateways.name }}
  http:
  - match:
    - uri:
        prefix: /mock
    - headers:
        isTestUser:
          exact: "true"
    route:
    - destination:
        host: mock-canary-service
        port:
          number: {{ .Values.service.port }}
    
  - match:
    - uri:
        prefix: /mock
    timeout: 120s
    route:
    - destination:
        host: mock-service
        port:
          number: {{ .Values.service.port }}


```

**Steps to reproduce the bug**
When i want the traffic to go to regular when header doesnt have isTestUser it doesnt work. The traffic always goes to canary. This is because the match criteria is for OR condition. 
The documentation for this states "In a YAML file, the difference between AND behavior and OR behavior in a routing rule is a single dash. The dash indicates two separate matches as opposed to one match with multiple conditions."

I have no idea what this means. Would like to understand how to configure AND condition. 
Also it would be nice if i have a match for that virtual service which says /mock should gte processed by these 2 further header based matches . 
 
**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.1.12
**How was Istio installed?**
helm
**Environment where bug was observed (cloud vendor, OS, etc)**
EKS
Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by esnible** [comment]
The documentation at https://preliminary.istio.io/docs/concepts/traffic-management/#multi-match gives examples of AND vs OR.  The sentence you quote reflects the two examples above it.

For AND:
```
  - match:
    - sourceLabels:
        app: reviews
        version: v2
      headers:
        end-user:
          exact: jason
```

Anyway, in the AND case the example becomes a single "match", 
```
{
   "sourceLabels": { "app": "reviews", "version": "v2" },
   "headers": { "end-user": { "exact": "jason" }}
}
```

The OR example in YAML, which is identical to the AND example except for an extra `-`, becomes two matches:

```
{
   "sourceLabels": { "app": "reviews", "version": "v2" },
}, {
   "headers": { "end-user": { "exact": "jason" }}
}
```

(Most humans have a hard time parsing YAML for arrays of sparsely used structs.)

Because you are interested in AND you probably want a single HTTPMatchRequest following https://preliminary.istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#HTTPMatchRequest 

@frankbu , when I was researching this I noticed that the documentation for https://preliminary.istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#HTTPMatchRequest does not include `sourceLabels`, `source_labels` because they are now marked `$hide_from_docs` in _api/networking/v1alpha3/virtual_service.proto_ because of https://github.com/istio/api/commit/0e77ec00236554f76109f0e917c6a11de3fa97f7 two weeks ago.  We should probably remove any fields from the examples that are no longer documented.

**Comment by pc-rshetty** [comment]
Thanks @esnible it works now !!

**Comment by pc-rshetty** [comment]
i will keep it open in case you want to update the documentation to be more clearer.

**Comment by jonaseicher** [comment]
So glad I found this article. Have been trying for hours to get the matcher to work!

Unfortunately the documentation of virtual service doesn't make this beviour clear:

https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRoute

`match | HTTPMatchRequest[] | Match conditions to be satisfied for the rule to be activated. All conditions inside a single match block have AND semantics, while the list of match blocks have OR semantics. The rule is matched if any one of the match blocks succeed.`

**Comment by jonaseicher** [comment]
Ok, I get it now. The 'match' blocks refer to the different elements under the 'match' attribute and not to the different HTTPRoute blocks.

Still, an easy mistake to make when your HTTPRoute blocks look like this:

```
- match:
    prefix: /abc
  route:
    uri: xyz
- match:
    prefix: /abc
  route:
    uri: xyz
```

**Comment by CGavrila** [comment]
For those ending up here after struggling to get this working for 2h.

In the example below, the `AND` rule applies. A client needs to match BOTH `Host: example.com` AND an URI with the prefix `/api` for the rule to apply. 
```
      - match:
          - authority:
              exact: example.com
            uri:
              prefix: /api
        route:
          - destination:
              host: example.test.svc.cluster.local
              port:
                number: 80
```

In the example below, the `OR` rule applies. A client needs to match EITHER `Host: example.com` OR an URI with the prefix `/api` for the rule to apply. 
```
      - match:
          - authority:
              exact: example.com
           - uri:
              prefix: /api
        route:
          - destination:
              host: example.test.svc.cluster.local
              port:
                number: 80
```
