### ISSUE TITLE
Istio fluentd adapter sends IP addresses as bytes

### ISSUE THREAD

**Issue by maxdebayser** [istio/istio#17012]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

When trying to send all fields defined here  https://github.com/istio/istio/blob/84f3b8ff576125a6c3cab667bb213c65768f68a3/install/kubernetes/helm/istio/charts/mixer/templates/config.yaml#L242  to fluentd, the fields that are of type IPAddress are sent as 4-byte binary array, that is interpreted by fluentd as a string, thus causing ElasticSearch to complain about invalid UTF-8

```
2019-09-10 00:31:18 +0000 [warn]: fluent/log.rb:342:warn: dump an error event: error_class=Fluent::Plugin::ElasticsearchErrorHandler::ElasticsearchError error="400 - Rejected by Elasticsearch [error type]: mapper_parsing_exception [reason]: 'failed to parse field [sourceIp] of type [text]'" location=nil tag="accesslog.instance.istio-system" time=1568075465 record={"requestId"=>"50349b1f-bbee-4549-92e9-5251d73ce949", "sourceIp"=>"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xFF\xFF\n\x01\x017", "permissiveResponsePolicyID"=>"none", "destinationServiceHost"=>"kiali.istio-system.svc.cluster.local", "sourceNamespace"=>"istio-system", "requestSize"=>0, "apiKey"=>"", "grpcMessage"=>"", "destinationPrincipal"=>"", "responseFlags"=>"-", "permissiveResponseCode"=>"none", "sourceApp"=>"istio-ingressgateway", "responseSize"=>8857, "destinationApp"=>"kiali", "receivedBytes"=>3940, "severity"=>"Info", "sourcePrincipal"=>"", "responseCode"=>200, "referer"=>"https://natural-r1.br.ibm.com:42444/kiali/console/graph/namespaces/?edges=noEdgeLabels&graphType=versionedApp&namespaces=default&unusedNodes=false&injectServiceNodes=true&duration=60&pi=15000&layout=dagre", "destinationName"=>"kiali-857658674b-ggf4q", "xForwardedFor"=>"9.80.205.227,10.1.3.0", "destinationOwner"=>"kubernetes://apis/apps/v1/namespaces/istio-system/deployments/kiali", "connection_security_policy"=>"unknown", "method"=>"GET", "latency"=>"33.217169ms", "destinationWorkload"=>"kiali", "url"=>"/kiali/api/namespaces/graph?duration=60s&graphType=versionedApp&injectServiceNodes=true&groupBy=app&appenders=deadNode,sidecarsCheck,serviceEntry,istio&namespaces=default", "destinationNamespace"=>"istio-system", "destinationIp"=>"\n\x01\x01<", "grpcStatus"=>"", "requestedServerName"=>"", "sourceName"=>"istio-ingressgateway-84b668cbf4-w7fl6", "apiClaims"=>"", "sourceOwner"=>"kubernetes://apis/apps/v1/namespaces/istio-system/deployments/istio-ingressgateway", "userAgent"=>"Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0", "reporter"=>"source", "httpAuthority"=>"natural-r1.br.ibm.com:42444", "sentBytes"=>8991, "sourceWorkload"=>"istio-ingressgateway", "protocol"=>"http", "clientTraceId"=>""}
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[X ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Expected behavior**

This behavior, if by design, should be documented. The documented example https://istio.io/docs/tasks/telemetry/logs/fluentd/ omits these problematic fields, perhaps knowingly.

The correct behavior IMHO is for the fluentd adapter to re-code fields in non-native formats to strings, so as to generate valid JSON or MsgPack messages.

**Steps to reproduce the bug**

Applying the configuration below in an environment with a fluentd service at fluentd-es.logging.svc.cluster.local:24224 configured to forward output to elasticsearch will result in error messages appearing in fluentd's stdout and no messages reaching ES.

```
# Configuration for a Fluentd handler
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: fluentd-handler
  namespace: istio-system
spec:
  compiledAdapter: fluentd
  params:
    address: "fluentd-es.logging.svc.cluster.local:24224"
    integerDuration: false
---
# Rule to send logentry instances to the Fluentd handler
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: http-to-fluentd
  namespace: istio-system
spec:
  match: context.protocol == "http" || context.protocol == "grpc"
  actions:
    - handler: fluentd-handler
      instances:
        - accesslog
---
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
  name: accesslog
  namespace: istio-system
spec:
  compiledTemplate: logentry
  params:
    severity: '"Info"'
    timestamp: request.time
    variables:
      sourceIp: source.ip | ip("0.0.0.0")
      destinationIp: destination.ip | ip("0.0.0.0")
    monitored_resource_type: '"global"'
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

$ istioctl version --remote
client version: 1.2.4
citadel version: 1.2.4
galley version: 1.2.4
ingressgateway version: 1.2.4
pilot version: 1.2.4
policy version: 1.2.4
sidecar-injector version: 1.2.4
telemetry version: 1.2.4

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

Helm

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

I've managed to get this setup working by adding a custom filter plugin for fluentd, but I consider this a hack.

```
require 'fluent/plugin/filter'

module Fluent::Plugin
  class IstioCorrector < Filter
    Fluent::Plugin.register_filter('istiocorrect', self)

    def configure(conf)
      super
    end

    def filter(tag, time, record)
      if (record["destinationIp"] != nil)
        record["destinationIp"] = record["destinationIp"].unpack('CCCC').join('.')
      end
      if (record["sourceIp"] != nil)
        record["sourceIp"] = record["sourceIp"].unpack('CCCC').join('.')
      end
      record
    end
  end
end
```
