### ISSUE TITLE
Support sticky sessions for weight based routing

### ISSUE THREAD

**Issue by zhaohuabing** [istio/istio#1703]
The requests from the same IP are distributed to different destination services based on the weight if weight-based routing rule is applied. Let's say if I set a rule like this

```
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: reviews-default
spec:
  destination:
    name: reviews
  precedence: 1
  route:
  - labels:
      version: v1
    weight: 50
  - labels:
      version: v2
    weight: 50
```

The requests from the same IP are dispatched to V1 and V2 of reviews services randomly, of course,
 each version gets roughly 50% of the requests.

I'm wondering should we keep the requests from the same user/client get a consistent result?  The user will be confused if the system behaves like this if we use Istio in a canary deployment.

I posted [a topic on the Istio Developers Google group to discuss 'Session sticky for weight based routing'](https://groups.google.com/forum/#!msg/istio-dev/L8ULIFS2QTY/dX6jIXaNCAAJ).  @ZackButcher mentioned that Envoy already support this feature and we need to reflect it in the Istio config.
