### ISSUE TITLE
Rate limit requested quota not working

### ISSUE THREAD

**Issue by SaumyaGurtu** [istio/istio#17048]
* Bug description
When I perform enabling rate limits task memory quota, the rate limits do not work.

* Configuration Infrastructure
Istio in kubernetes.

* Test and Release
Release istio 1.2.5

* Expected behavior
The rate limit should work.

* Kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10", GitCommit:"37d169313237cb4ceb2cc4bef300f2ae3053c1a2", GitTreeState:"clean", BuildDate:"2019-08-19T10:44:49Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

* How was Istio installed?
downloaded from  https://github.com/istio/istio/releases/download/1.2.5/istio-1.2.5-linux.tar.gz 
helm template install/kubernetes/helm/istio-init --name istio-init --namespace istio-system > istio-init.yaml
kubectl apply -f istio-init.yaml -n istio-system 
helm template install/kubernetes/helm/istio --set gateways.istio-ingressgateway.type=NodePort --set gateways.istio-egressgateway.type=NodePort --set sidecarInjectorWebhook.enabled=true --set grafana.enabled=true --set mixer.templates.useTemplateCRDs=true --set mixer.adapters.useAdapterCRDs=true --set mixer.policy.enabled=true --set mixer.adapters.stdio.enabled=true --set grafana.service.type=NodePort --set global.disablePolicyChecks=false --name istio --namespace istio-system > istio.yaml
kubectl apply -f istio.yaml -n istio-system

* Environment where bug was observed (cloud vendor, OS, etc)
private cloud

* Steps to reproduce the bug
I installed istio 1.2.5 with helm. Then follow enabling rate limits task step by step.

* Rate Limit config applied:
```
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: quotahandler
  namespace: istio-system
spec:
  compiledAdapter: memquota
  params:
    quotas:
    - name: requestcountquota.instance.istio-system
      maxAmount: 2
      validDuration: 1s
      # The first matching override is applied.
      # A requestcount instance is checked against override dimensions.
---
apiVersion: config.istio.io/v1alpha2
kind: instance
metadata:
  name: requestcountquota
  namespace: istio-system
spec:
  compiledTemplate: quota
  params:
    dimensions:
      source: request.headers["x-forwarded-for"] | "unknown"
---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpec
metadata:
  name: request-count
  namespace: istio-system
spec:
  rules:
  - quotas:
    - charge: 1
      quota: requestcountquota
---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpecBinding
metadata:
  name: request-count
  namespace: istio-system
spec:
  quotaSpecs:
  - name: request-count
    namespace: istio-system
  services:
  - name: my-service
    namespace: default
  #- service: '*'  # Uncomment this to bind *all* services to request-count

---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: quota
  namespace: istio-system
spec:
  # quota only applies if you are not logged in.
  # match: match(request.headers["cookie"], "user=*") == false
  actions:
  - handler: quotahandler
    instances:
    - requestcountquota
```

Also tried restarting pilot and mixer and found no errors in mixer and pilot logs. But still memquota limit not working correctly in this case.
