### ISSUE TITLE
Multiple serviceentries with same port causing connections to be closed.

### ISSUE THREAD

**Issue by corey-aloia** [istio/istio#17075]
Two service entries with different CIDRs, but the same port cause connections to close.
Here is an example (note: the CIDRs are made up for the example):
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cassandra-example1
  namespace: examplens1
spec:
  hosts:
    - cassandraex1.ports # used for metrics
  addresses:
    - 192.192.192.0/24
  ports:
    - name: cassandraex1-client-port
      number: 9042
      protocol: TCP
```
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cassandra-example2
  namespace: examplens2
spec:
  hosts:
    - cassandraex2.ports # used for metrics
  addresses:
    - 192.192.27.0/24
  ports:
    - name: cassandraex2-client-port
      number: 9042
      protocol: TCP
```

This will cause intermittent closed connections. Most of the time it will work, but sometimes it will fail. 

If I combine these two serviceentries into one, then everything works. 
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cassandra-example
  namespace: examplens
spec:
  hosts:
    - cassandra.ports # used for metrics
  addresses:
    - 192.192.192.0/24
    - 192.192.27.0/24
  ports:
    - name: cassandra-client-port
      number: 9042
      protocol: TCP
```

**Affected product area (please put an X in all that apply)**

[x] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
That one can have the same port in multiple service entries as long as the CIDR is different

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio-Version: 1.2.2
Kubernetes-version: v1.12.3

**How was Istio installed?**
Helm template and then Kubectl apply -f -

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS
