### ISSUE TITLE
Multiple filter chains with overlapping matching rules are defined

### ISSUE THREAD

**Issue by jarvisuser90** [istio/istio#17079]
**Bug description**

I'm using Ansible to provision my bare metal Kubernetes cluster ( 1 master, 3 workers). Istio installs fine without errors. If I apply a simple https gateway with one virtual service, path-based routing works as expected. I run into problems when my gateway gets a little more complex and I deploy more virtual services.

Istio routing completely stops working. Path-based routes that were working before are no longer reachable. I get the following errors in the service/istio-ingressgateway istio-proxy container:

```
2019-09-12T21:03:17.626894Z	info	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 0 rejected; lds updates: 0 successful, 0 rejected

[2019-09-12 21:03:18.241][27][warning][config] [external/envoy/source/common/config/grpc_mux_subscription_impl.cc:73] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) 0.0.0.0_443: error adding listener '0.0.0.0:443': multiple filter chains with overlapping matching rules are defined

2019-09-12T21:03:19.629273Z	info	Envoy proxy is ready

[2019-09-12 21:03:19.766][27][warning][config] [external/envoy/source/common/config/grpc_mux_subscription_impl.cc:73] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) 0.0.0.0_443: error adding listener '0.0.0.0:443': multiple filter chains with overlapping matching rules are defined
```

**Affected product area (please put an X in all that apply)**

[ X ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

I’m trying to expose several web apps via Istio’s path-based routing. 
ex: example.com/service1 example.com/service2 example.com/service3

**Steps to reproduce the bug**

Here’s the setup used that produces the error:

Gateway:
```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: default-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: core-apps-cert-dev
      hosts:
        - “istio-system/kube.dev”
        - “rook-ceph/kube.dev”
        - “default/kube.dev”
    - port:
          number: 31400 
          name: tcp-s3
          protocol: TCP
      hosts:
        - “rook-ceph/kube.dev”
```

Virtual Services:
``` yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-world-one
  namespace: default
spec:
  hosts:
    - kube.dev
  gateways:
    - default-gateway.istio-system.svc.cluster.local
  http:
    - match:
        - uri:
            prefix: /hello-one/
        - uri:
            prefix: /hello-one
      rewrite:
        uri: /
      route:
        - destination:
            port:
              number: 80
            host: hello-world-one.default.svc.cluster.local

```

``` yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-world-two
  namespace: default
spec:
  hosts:
    - kube.dev
  gateways:
    - default-gateway.istio-system.svc.cluster.local
  http:
    - match:
        - uri:
            prefix: /hello-two/
        - uri:
            prefix: /hello-two
      rewrite:
        uri: /
      route:
        - destination:
            port:
              number: 80
            host: hello-world-two.default.svc.cluster.local

```

``` yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jaeger
  namespace: istio-system
spec:
  hosts:
    - kube.dev
  gateways:
    - default-gateway.istio-system.svc.cluster.local
  http:
    - match:
        - uri:
            prefix: /tracing/
        - uri:
            prefix: /tracing
      route:
        - destination:
            port:
              number: 16686
            host: jaeger-query.istio-system.svc.cluster.local

```

``` yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali
  namespace: istio-system
spec:
  hosts:
    - kube.dev
  gateways:
    - default-gateway.istio-system.svc.cluster.local
  http:
    - match:
        - uri:
            prefix: /kiali/
        - uri:
            prefix: /kiali
      route:
        - destination:
            port:
              number: 20001
            host: kiali.istio-system.svc.cluster.local

```

``` yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ceph
  namespace: rook-ceph
spec:
  hosts:
    - "kube.dev"
  gateways:
    - default-gateway.istio-system.svc.cluster.local
  http:
    - match:
        - uri:
            prefix: /ceph/
        - uri:
            prefix: /ceph
      route:
        - destination:
            port:
              number: 8443
            host: rook-ceph-mgr-dashboard.rook-ceph.svc.cluster.local
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ceph-s3-api
  namespace: rook-ceph
spec:
  hosts:
    - "kube.dev"
  gateways:
    - default-gateway.istio-system.svc.cluster.local
  tcp:
    - match:
      - port: 31400
      route:
        - destination:
            host: rook-ceph-rgw-meps-objectstore.rook-ceph.svc.cluster.local
            port:
              number: 80


```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

Istio versions:
> client version: unknown
> control plane version: 1.2.5

Kubectl:
> Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
> Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

Istio was installed following these steps:
[Istio / Customizable Install with Helm](https://istio.io/docs/setup/install/helm/#option-1-install-with-helm-via-helm-template)

**Environment where bug was observed (cloud vendor, OS, etc)**

Bare metal Kubernetes installation on Ubuntu 18.0.4
Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

Cluster state dump file:
[public-files/istio-dump.tar.gz](https://github.com/jarvisuser90/public-files/blob/master/istio-dump.tar.gz)

**Comment by jarvisuser90** [comment]
@howardjohn Thanks for taking a look!

**Comment by rshriram** [comment]
this is expected. You are declaring the same hostname in multiple namespaces under the same SNI match (kube.dev). If you modify the hostnames in the virtual services (and in the gateway), the error should go away

**Comment by jarvisuser90** [comment]
@rshriram Thanks for the reply. Could you please explain what you mean? I’m not sure I follow. I thought declaring namespace/host in the gateway would only allow virtual services in that declared namespace and host name to bind to it.

**Comment by howardjohn** [comment]
you have 2 virtual services in the same namespace for the same host that are doing different things. What is the desired outcome? When a request comes in for host kind.dev does it route to hello world 1 or 2?

**Comment by athurner** [comment]
I'm not sure if I agree that the configuration of @jarvisuser90  is wrong. I applied the virtual services and then the gateway yaml and I'm seeing the same errors. BUT if I apply the gateway.yaml so that only one new host is added each time, it works fine. Let me explain:  

## Test 1 (one host at a time)
###  First Step: 

I only have one host for port 443
        - “istio-system/kube.dev”

run kubectl apply -f gateway.yml
``` 
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: default-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: core-apps-cert-dev
      hosts:
        - “istio-system/kube.dev”
    - port:
          number: 31400 
          name: tcp-s3
          protocol: TCP
      hosts:
        - “rook-ceph/kube.dev”
```
this created the gateway and I was able to access the following virtual services successfully
- kube.dev:31400
- kube.dev/kiali
- kube.dev/tracing

### NEXT STEP:

add an additional host for port 443
        - “rook-ceph/kube.dev” 

run kubectl apply -f gateway.yml
```
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: default-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: core-apps-cert-dev
      hosts:
        - “istio-system/kube.dev”
        - “rook-ceph/kube.dev”
    - port:
          number: 31400 
          name: tcp-s3
          protocol: TCP
      hosts:
        - “rook-ceph/kube.dev”
```
this updates the gateway configuration and I was able to access also the virtual service: 
- kube.dev/ceph

### Final Step
add third additional host for port 443
       - “default/kube.dev”

run kubectl apply -f gateway.yml
```
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: default-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: core-apps-cert-dev
      hosts:
        - “istio-system/kube.dev”
        - “rook-ceph/kube.dev”
        - “default/kube.dev”
    - port:
          number: 31400 
          name: tcp-s3
          protocol: TCP
      hosts:
        - “rook-ceph/kube.dev”
```
this updates the gateway configuration again and I was able to access also the virtual service: 
- kube.dev/hello-one
- kube.dev/hello-two

## Test 2 (host "*")

When changing the host to "*" all routing is working fine

```
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: default-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: core-apps-cert-dev
      hosts:
        - “*”
    - port:
          number: 31400 
          name: tcp-s3
          protocol: TCP
      hosts:
        - “rook-ceph/kube.dev”
```

## Conclusion

Could it be that there is a bug when there are more than one new hosts defined? 

Thank you very much for checking into this.

**Comment by jarvisuser90** [comment]
@howardjohn 

What I understand from the documentation is that having two virtual services in the same namespace with the same host is perfectly fine. Istio will merge these two virtual services. Are my assumptions correct?

>When a second and subsequent VirtualService for an existing host is applied, istio-pilot will merge the additional route rules into the existing configuration of the host.

[Multiple virtual services and destination rules for the same host](https://istio.io/docs/ops/traffic-management/deploy-guidelines/#multiple-virtual-services-and-destination-rules-for-the-same-host)

**Comment by rshriram** [comment]
@jarvisuser90 yes you are correct. Let us go through the code to see where the example breaks

**Comment by rshriram** [comment]
@lambdai can you investigate this bug please? The fix should be some simple adjustments in the gateway code mostly.

**Comment by duderino** [comment]
@lambdai can you take a look at this?  Not a crisis, but would be good to resolve it in 2019 ;)

**Comment by pixystone** [comment]
Thank you @athurner !
Your information help me a lot.

I met the same error message when I applied this gateway config before I enable the sds support at ingressgateway ( followed [](https://istio.io/docs/tasks/traffic-management/ingress/secure-ingress-sds/) :

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "./*"
    tls:
      httpsRedirect: true # sends 301 redirect for http requests
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "./*"
    tls:
      mode: SIMPLE
      credentialName: "https-certs"
```


All I have done to resolve it are only change the order of my operations.
I must restart `istio-ingressgateway` before I applies the gateway config.
