### ISSUE TITLE
helm template - mtls with custom cluster domain

### ISSUE THREAD

**Issue by charlierudolph-sx** [istio/istio#17089]
**Bug description**

Currently when using a custom cluster domain and generating the template using helm, the mtls does not respect the custom domain:

https://github.com/istio/istio/blob/0cc46f0243145a4bb0d0d4868d411f0fd522a3a6/install/kubernetes/helm/istio/charts/security/templates/enable-mesh-mtls.yaml#L33

It is hardcoded as `"*.local"` but I would think it would be `"*.svc.{{ .Values.global.proxy.clusterDomain }}"`

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Generated destination rule for mtls respects custom cluster domain

**Steps to reproduce the bug**

* Checkout this repo, have helm 2.14.3 installed
* Update https://github.com/istio/istio/blob/0cc46f0243145a4bb0d0d4868d411f0fd522a3a6/install/kubernetes/helm/istio/values.yaml#L150 to your custom domain (ex `my.custom.domain`)
* Run `helm template install/kubernetes/helm/istio --name istio --namespace istio-system --values install/kubernetes/helm/istio/values.yaml > output.yaml`
* output.yaml's destination rule for istio-system is 
```yaml
    apiVersion: networking.istio.io/v1alpha3
    kind: DestinationRule
    metadata:
      name: "default"
      namespace: istio-system
      labels:
        app: security
        chart: security
        heritage: Tiller
        release: istio
    spec:
      host: "*.local"
      trafficPolicy:
        tls:
          mode: ISTIO_MUTUAL
```

when I want it to be 

```yaml
    apiVersion: networking.istio.io/v1alpha3
    kind: DestinationRule
    metadata:
      name: "default"
      namespace: istio-system
      labels:
        app: security
        chart: security
        heritage: Tiller
        release: istio
    spec:
      host: "*.svc.my.custom.domain"
      trafficPolicy:
        tls:
          mode: ISTIO_MUTUAL
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

N/A

**How was Istio installed?**

Checked out the repo

**Environment where bug was observed (cloud vendor, OS, etc)**

Ubuntu

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
