### ISSUE TITLE
Routing dynamically learnt services

### ISSUE THREAD

**Issue by MaheshGPai** [istio/istio#17097]
**Bug description**
We have a service architecture where services come in and go out on a regular basis. These services register to a service registry, which is used by consumers to "discover" and consume. We want all external service traffic to flow via the egress gateway, since only those nodes (where the egress pods are scheduled) have external connectivity. So this creates a problem when the service that we are trying to dynamically discover and consume is outside the cluster, since each external service needs a ServiceEntry to be created. 

One way out of this is for the service registry to create the required istio resources when new service registers to it. This would mean that we would perform infrastructure layer operations from application. May not be an ideal solution. Apart from this, there is no guarantee that the service registry itself will be within the cluster. So in such cases, the only way out is to manually configure the routing rules. And this breaks the dynamic nature of the service architecture.
 
Is there any "default" routing that can be applied so that all services that are not part of the istio service registry flow through the egress gateway? Some form of http2 proxy. Can this be introduced if its not already available?

**Affected product area (please put an X in all that apply)**

[ X] Configuration Infrastructure
[ X] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio 1.2.5

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
in theory I think you could write an EnvoyFilter that replaces the passthrough cluster with a cluster that points to egress gateway.. I think I'll try it out if you don't have the chance/envoy experience since this sounds useful

**Comment by howardjohn** [comment]
Something like this maybe
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: passthrough-egress
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: shell
  configPatches:
  - applyTo: CLUSTER
    clusterMatch:
      name: PassthroughCluster
    patch:
      operation: REMOVE
  - applyTo: CLUSTER
    clusterMatch:
      name: PassthroughCluster
    patch:
      operation: ADD
      value: 
        connectTimeout: 1s
        dnsLookupFamily: V4_ONLY
        hosts:
        - socketAddress:
            address: istio-egressgateway.istio-system
            portValue: 80
        name: PassthroughCluster
        type: STRICT_DNS
```
