### ISSUE TITLE
Problems with routing with multiple ingresses

### ISSUE THREAD

**Issue by olofwalker** [istio/istio#1710]
istio 0.2.12 running on GCE (v1.8.2-gke.0)

**Expected behaviour**
Below is a simple ingress example where we want to setup ingresses per project and route the traffic hitting these to respective service. The ingresses will share the same IP in this example.

**Result**
Requests sent to both the url's are always routed to service nginx-0-service, the second service is unreachable from the outside.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config0
data:
  nginx.conf: |
    events {}
    http {
    server {
      listen       80;
      server_name  localhost;
      root /etc/nginx;
      add_header X-Whom nginx-0;
    }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config1
data:
  nginx.conf: |
    events {}
    http {
    server {
      listen       81;
      server_name  localhost;
      root /etc/nginx;
      add_header X-Whom nginx-1;
      }
      }
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-0
  template:
    metadata:
      labels:
        app: nginx-0
    spec:
      volumes:
      - name: nginx-config0
        configMap:
          name: nginx-config0
      containers:
      - image: nginx
        name: nginx-0
        volumeMounts:
        - name: nginx-config0
          mountPath: /etc/nginx
          readOnly: true
        ports:
        - containerPort: 80
          hostPort: 80
          name: nginx-0-port
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-1
  template:
    metadata:
      labels:
        app: nginx-1
    spec:
      volumes:
      - name: nginx-config1
        configMap:
          name: nginx-config1
      containers:
      - image: nginx
        name: nginx-1
        volumeMounts:
        - name: nginx-config1
          mountPath: /etc/nginx
          readOnly: true
        ports:
        - containerPort: 81
          hostPort: 81
          name: nginx-1-port
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-0-service
spec:
  selector:
    app: nginx-0
  ports:
  - name: http
    port: 80
    targetPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-1-service
spec:
  selector:
    app: nginx-1
  ports:
  - name: http
    port: 80
    targetPort: 81
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-0-ingress
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - host: ingress.project1.example.com
    http:
      paths:
      - path: /.*
        backend:
          serviceName: nginx-0-service
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-1-ingress
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - host: ingress.project2.example.com
    http:
      paths:
      - path: /.*
        backend:
          serviceName: nginx-1-service
          servicePort: 80

```
