### ISSUE TITLE
Missing Istio Endpoints for Kubernetes Service with Endpoints

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#17112]
**Bug description**

When you create a service with endpoints, ***and you have some other service without pods and endpoints***,  a listener and a cluster are built for the service, but no Istio endpoints. 

1. Create a Kubernetes service without endpoints:

```
kubectl apply -f - <<EOF
apiVersion: v1
kind: Service
metadata:
  name: my-service-no-endpoints
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9375
EOF
```

2. Follow the Kubernetes example for a Service with Endpoints  https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors:

```
kubectl apply -f - <<EOF
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
---
apiVersion: v1
kind: Endpoints
metadata:
  name: my-service
subsets:
  - addresses:
      - ip: 192.0.2.42
    ports:
      - port: 9376
EOF
```

```
istioctl proxy-config listeners $(kubectl get pod -l app=sleep -o jsonpath='{.items..metadata.name}') -o json | grep my-service
         "stringValue": "my-service.default.svc.cluster.local"
         "stringValue": "my-service"
         "stringValue": "istio://default/services/my-service"
         "statPrefix": "outbound|80||my-service.default.svc.cluster.local",
          "cluster": "outbound|80||my-service.default.svc.cluster.local",
istioctl proxy-config clusters $(kubectl get pod -l app=sleep -o jsonpath='{.items..metadata.name}'  ) -o json | grep my-service
        "name": "outbound|80||my-service.default.svc.cluster.local",
            "serviceName": "outbound|80||my-service.default.svc.cluster.local"
            "sni": "outbound_.80_._.myservice.default.svc.cluster.local"
istioctl proxy-config endpoints $(kubectl get pod -l app=sleep -o jsonpath='{.items..metadata.name}') -o json | grep my-service
```

The pilot log shows:
```
kubectl logs -l istio=pilot -c discovery -n istio-system --tail=100
...
    "ProxyStatus": {
        "endpoint_no_pod": {
            "my-service.default.svc.cluster.local": {
                "message": "192.0.2.42"
            }
        },
        "pilot_eds_no_instances": {
            "outbound_.8080_._.my-service-no-endpoints.default.svc.cluster.local": {},
            "outbound_.80_._.my-service.default.svc.cluster.local": {},
            "outbound|8080||my-service-no-endpoints.default.svc.cluster.local": {},
            "outbound|80||my-service.default.svc.cluster.local": {}
        }
    },
}
```

It appears that `my-service-no-ednponts` causes the EDS error for `my-service`.

3. Delete `my-service-no-ednponts`:

```
kubectl delete service my-service-no-endpoints
```

Now the endpoint appears:

```
istioctl proxy-config endpoints $(kubectl get pod -l app=sleep -o jsonpath='{.items..metadata.name}') -o json | grep my-service
"name": "outbound|80||my-service.default.svc.cluster.local",
```

**Affected product area (please put an X in all that apply)**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
There should be Istio endpoints for the Kubernetes service with endpoints

**Steps to reproduce the bug**
Perform the commands above.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.3.0 release
**How was Istio installed?**
install/kubernetes/istio-demo-auth.yaml

**Environment where bug was observed (cloud vendor, OS, etc)**
Kubernetes 1.14

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
