### ISSUE TITLE
Ingress-gateway is not updating the certs without deleting/restarting the POD

### ISSUE THREAD

**Issue by venomwaqar** [istio/istio#17123]
**Bug description**
Ingress-gateway is presenting the old certificates even after updating the secrets with the new certs.
My problem is that I want to replace the old certificates with the new certificates without deleting or restarting or patching the gateway deployment, I cant bear any down-time.

**Steps to reproduce the bug**
1. Install the ingress-gateway with the following values
```
istio-ingressgateway:
      autoscaleMin: 1
      autoscaleMax: 1
      replicaCount: 2
      autoscaleEnabled: false
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 2000m
          memory: 1024Mi
      type: NodePort
      secretVolumes:
        - name: "{{ cert_secrets.domain_secret_name }}"
          secretName: "{{ cert_secrets.domain_secret_name }}"
          mountPath: "/etc/istio/{{ custom.networking.dnsDomain | replace('.', '-') }}-certs"
      ports:
        - port: 80
          targetPort: 80
          name: http2
          nodePort: 80
        - port: 443
          name: https
          nodePort: 443
        # This is the port where sni routing happens
        - port: 15443
          targetPort: 15443
          name: tls
```

2. Update the secret with the new certs and check if the application is being provided with the new certs.

**Expected**
Application is presenting the new certificates without deleting or restarting or patching the gateway deployment.

**Behavior**
Application is still presenting the old certificates.
When I delete the ingress-gateway POD, or patch the deployment. Application is presenting the new certificates.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Kubernetes: 1.13.6
Istio: 1.1.10

**How was Istio installed?**
I have installed the istio using HELM chart [here](https://github.com/istio/istio/tree/master/install/kubernetes/helm/istio)
