### ISSUE TITLE
/etc/certs/cert-chain.pem not found in sidecar

### ISSUE THREAD

**Issue by rjshrjndrn** [istio/istio#17143]
**Bug description**

**Shortform**
- ssl certificte in namespace istio-system where ingress-gateway is
- Gateway in `dev` namespace, where all application pods are running
- Side car is not starting

**Detailed Error log**
Created ssl certificate with certmanager(Bundled with istio v1.2.2) 
secret in `namespace: istio-system` and gateway in `namespace: dev`
But when I'm creating a deployment, getting error noting
```
➜ stern -n istio-system pilot -c discovery --tail 100

istio-pilot-65dff6fbbf-9xr5r discovery 2019-09-17T15:52:03.318486Z      info    Handling event update for pod telemetry-service-85db4cf548-n67kx in namespace dev -> 11.2.0.87
istio-pilot-65dff6fbbf-9xr5r discovery 2019-09-17T15:52:03.494708Z      info    ads     ADS:CDS: REQ 11.2.0.87:58658 sidecar~11.2.0.87~telemetry-service-85db4cf548-n67kx.dev~dev.svc.cluster.local-240 150.8µs version:
istio-pilot-65dff6fbbf-9xr5r discovery 2019-09-17T15:52:03.499004Z      info    ads     CDS: PUSH for node:telemetry-service-85db4cf548-n67kx.dev clusters:73 services:47 version:2019-09-17T15:45:05Z/168
istio-pilot-65dff6fbbf-9xr5r discovery 2019-09-17T15:52:03.536376Z      info    ads     EDS: PUSH for node:telemetry-service-85db4cf548-n67kx.dev clusters:69 endpoints:63 empty:[outbound|8082||heapster.jx.svc.cluster.local outbound|80||tide.jx.svc.cluster.local outbound|80||hook.jx.svc.cluster.local outbound|42422||istio-telemetry.istio-system.svc.cluster.local outbound|15014||istio-telemetry.istio-system.svc.cluster.local outbound|15004||istio-telemetry.istio-system.svc.cluster.local outbound|9091||istio-telemetry.istio-system.svc.cluster.local outbound|80||nginx.test.svc.cluster.local]
istio-pilot-65dff6fbbf-9xr5r discovery gc 1876 @21287.597s 0%: 0.011+12+3.9 ms clock, 0.022+3.8/2.3/9.9+7.9 ms cpu, 24->25->13 MB, 25 MB goal, 2 P
istio-pilot-65dff6fbbf-9xr5r discovery 2019-09-17T15:52:03.629861Z      info    ads     LDS: PUSH for node:telemetry-service-85db4cf548-n67kx.dev listeners:57
istio-pilot-65dff6fbbf-9xr5r discovery 2019-09-17T15:52:03.741623Z      info    ads     RDS: PUSH for node:telemetry-service-85db4cf548-n67kx.dev routes:13
istio-pilot-65dff6fbbf-9xr5r discovery 2019-09-17T15:52:03.742049Z      warn    ads     ADS:LDS: ACK ERROR 11.2.0.87:58658 sidecar~11.2.0.87~telemetry-service-85db4cf548-n67kx.dev~dev.svc.cluster.local-240 (telemetry-service-85db4cf548-n67kx.dev) node:<id:"sidecar~11.2.0.87~telemetry-service-85db4cf548-n67kx.dev~dev.svc.cluster.local" cluster:"telemetry-service.dev" metadata:<fields:<key:"CONFIG_NAMESPACE" value:<string_value:"dev" > > fields:<key:"INCLUDE_INBOUND_PORTS" value:<string_value:"9001" > > fields:<key:"INTERCEPTION_MODE" value:<string_value:"REDIRECT" > > fields:<key:"ISTIO_META_INSTANCE_IPS" value:<string_value:"11.2.0.87,11.2.0.87" > > fields:<key:"ISTIO_PROXY_SHA" value:<string_value:"istio-proxy:a975561b980463f08689d3debe33bb9eefc80c3d" > > fields:<key:"ISTIO_PROXY_VERSION" value:<string_value:"1.1.3" > > fields:<key:"ISTIO_VERSION" value:<string_value:"1.2.2" > > fields:<key:"POD_NAME" value:<string_value:"telemetry-service-85db4cf548-n67kx" > > fields:<key:"app" value:<string_value:"telemetry-service" > > fields:<key:"istio" value:<string_value:"sidecar" > > fields:<key:"pod-template-hash" value:<string_value:"85db4cf548" > > > locality:<> build_version:"a975561b980463f08689d3debe33bb9eefc80c3d/1.11.0-dev/Clean/RELEASE/BoringSSL" > type_url:"type.googleapis.com/envoy.api.v2.Listener" response_nonce:"c2f9f07e-5e78-4ffa-a6db-8c0ddf6812f9" error_detail:<code:13 message:"Error adding/updating listener(s) 11.2.0.87_9001: Invalid path: /etc/certs/cert-chain.pem" >
```
```
➜ stern telemetry-service-85db4cf548-n67kx -c istio-proxy --tail 2
+ telemetry-service-85db4cf548-n67kx › istio-proxy
telemetry-service-85db4cf548-n67kx istio-proxy
telemetry-service-85db4cf548-n67kx istio-proxy
telemetry-service-85db4cf548-n67kx istio-proxy 2019-09-17T16:07:12.195104Z      info    Envoy proxy is NOT ready: 2 errors occurred:
telemetry-service-85db4cf548-n67kx istio-proxy  * failed checking application ports. listeners="0.0.0.0:15090","172.16.160.232:9001","172.16.86.7:443","172.16.235.156:42422","172.16.17.88:443","172.16.40.53:9011","172.16.194.38:443","172.16.230.217:8000","172.16.37.70:15020","172.16.145.209:14267","172.16.255.10:9010","172.16.191.92:9090","172.16.90.55:9012","172.16.37.70:15029","172.16.205.3:443","172.16.37.70:15443","172.16.115.126:80","172.16.29.2:9008","172.16.194.83:443","172.16.202.249:8082","172.16.152.205:9000","172.16.241.178:443","172.16.37.70:15032","172.16.37.70:443","172.16.37.70:15030","172.16.37.70:31400","172.16.154.54:80","172.16.193.143:9005","172.16.38.86:3000","172.16.230.217:8001","172.16.98.36:15011","172.16.25.177:9090","172.16.0.1:443","172.16.155.52:16686","172.16.190.29:80","172.16.0.10:53","172.16.37.70:15031","172.16.228.227:44134","172.16.75.114:443","172.16.145.209:14268","172.16.217.78:9300","0.0.0.0:15010","0.0.0.0:9411","0.0.0.0:15004","0.0.0.0:3000","0.0.0.0:8080","0.0.0.0:9090","0.0.0.0:9200","0.0.0.0:15014","0.0.0.0:9091","0.0.0.0:8060","0.0.0.0:9901","0.0.0.0:20001","0.0.0.0:80","11.2.0.87:15020","0.0.0.0:15001"
telemetry-service-85db4cf548-n67kx istio-proxy  * envoy missing listener for inbound application port: 9001
telemetry-service-85db4cf548-n67kx istio-proxy
```

**Certificate.yml**
```
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-system
spec:
  secretName: ingress-cert
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: dev.centralindia.cloudapp.azure.com
  dnsNames:
  - dev.centralindia.cloudapp.azure.com
  acme:
    config:
    - http01:
        ingressClass: istio
      domains:
      - dev.centralindia.cloudapp.azure.com
```
**Gateway.yml**
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-gateway
  namespace: dev
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: "ingress-cert" # must be the same as secret
    hosts:
    - "dev.centralindia.cloudapp.azure.com"
```
**Sample Deployment.yml**

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-service
  namespace: dev
spec:
  replicas:
  selector:
    matchLabels:
      app: telemetry-service
  template:
    metadata:
      labels:
        app: telemetry-service
    spec:
      containers:
      - name: telemetry-service
        image: "telemetry-service"
        envFrom:
        - configMapRef:
            name: telemetry-config
        resources:
          requests:
            cpu: "50m"
            memory: "100Mi"
        ports:
        - containerPort: 9001

---
apiVersion: v1
kind: Service
metadata:
  name: telemetry-service
  namespace: dev
  labels:
    app: telemetry-service
spec:
  ports:
  - port: 9001
  selector:
    app: telemetry-service
```
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Deployment complete with `2/2` pod status

**Steps to reproduce the bug**
Deploy the above the yamls

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
➜ k version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5", GitCommit:"0e9fcb426b100a2aea5ed5c25b3d8cfbb01a8acf", GitTreeState:"clean", BuildDate:"2019-08-05T09:13:08Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

➜ istioctl version
client version: 1.2.4
citadel version: 1.2.2
galley version: 1.2.2
ingressgateway version: 1.2.2
nodeagent version:
nodeagent version:
nodeagent version:
nodeagent version:
pilot version: 1.2.2
policy version: 1.2.2
sidecar-injector version: 1.2.2
```
**How was Istio installed?**
Helm 
**Environment where bug was observed (cloud vendor, OS, etc)**
Azure AKS

**Comment by howardjohn** [comment]
Does it happen just at startup or does it never recover?

**Comment by rjshrjndrn** [comment]
It never recovered. To validate that, I deleted running pods prior to SSL enabling, And the new pods have the same Issue.

**Comment by howardjohn** [comment]
Do you have a secret named `ingress-cert`? `kubectl get secrets -n istio-system`

**Comment by rjshrjndrn** [comment]
Yeah I've. Only after that my https port opened.

**Comment by rjshrjndrn** [comment]
Okay I've found the issue. 
While trying to create ssl with certmanager, in the documentation, it was mentioned to enable sds.
Which I enabled in values.yml file of istio chart. But we've to change the sds in `gateway` chart. That was quite confusing. And after a toil of trial and error fixed the issue.

**For Whoever try to create SSL certificate with certmanager and istio, this is what worked for me**
1. Before installing anything, first apply `kubectl apply -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.6/deploy/manifests/00-crds.yaml` : CRDs for certmanager
2. enable certmanager in values.yml inside istio chart
3. Install istio with `helm install istio ./istio --set gateways.istio-ingressgateway.sds.enabled=true`
4. Create a certtificate using
```
 ---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-system
spec:
  secretName: ingress-cert
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: domain.centralindia.cloudapp.azure.com
  dnsNames:
  - domain.centralindia.cloudapp.azure.com
  acme:
    config:
    - http01:
        ingressClass: istio
      domains:
      - domain.centralindia.cloudapp.azure.com
```
> Secret should be in istio-system, where the istio-ingress-gateway pod runs
5. Create a gateway and virtual service( / -> certmanager pod)
6. `kubectl get certtificate`  should show you `true`
7. Create ssl endpoint like
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "domain.centralindia.cloudapp.azure.com"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: "ingress-cert" # must be the same as secret
    hosts:
    - "domain.centralindia.cloudapp.azure.com"
```
> You can have gateway and certificate create in any namespace. The point is, the secret, in this case `ingress-cert` should be available in istio-system
