### ISSUE TITLE
Selective retries (on Idempotent methods)  not working right

### ISSUE THREAD

**Issue by balamuru** [istio/istio#17145]
**Bug description**
I would like to be able to configure RETRIES only for IDEMPOTENT methods . I have applied this in the virtual service but it appears that ALL methods (eg IDEMPOTENT GETS and NON-IDEMPOTENT POSTS) are retried

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Retries should be executed for Idempotent method calls (GET) and timeout in about 5-6 seconds for the test call.
As per the configured virtual service, calls to non-idempotent methods should not be retried

Could this be related to https://github.com/istio/istio/issues/13851 ?

**Steps to reproduce the bug**
* Deploy httpbin (https://hub.docker.com/r/kennethreitz/httpbin/) in K8s/istio cluster
* Install a virtual Service (see below) pointing to the httpbin deploy
* Execute a GET curl or siege command that waits for a time . It will retry 5 times (waiting 1 seconds), timeout and return in about 5-6 seconds
* Execute a POST curl or siege command that waits for a time . It should just wait and timeout eventually (in 10 -20) seconds, depending on the max delay in httpbin
* I observe a timeout in 5-6 seconds, that indicates that the retry is in fact working when it should not.

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "httpbin-virtual-service"
spec:
  hosts:
  - "*"
  gateways:
  - my-istio-gateway
  http:
  - match:
    - uri:
        prefix: /status
      method:
        exact: GET
    - uri:
        prefix: /delay

    retries:
      attempts: 5      
      perTryTimeout: 1s
      retryOn: 5xx,gateway-error,connect-failure,refused-stream
    route:
    - destination:
        host: "httpbin"
        port:
          number: 80
  - match:
    - uri:
        prefix: /status
      method:
        exact: POST
    - uri:
        prefix: /delay
    retries:
      attempts: 0
    route:
    - destination:
        host: "httpbin"
        port:
          number: 80


```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-21T15:34:43Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
[ocadmin@cmsplavm211 config]$ 

$ ./istioctl version
client version: 1.3.0
control plane version: 1.3.0



```

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
Bare metal K8s cluster

**Cluster Dump**
[istio-dump.tar.gz](https://github.com/istio/istio/files/3622387/istio-dump.tar.gz)

**Comment by howardjohn** [comment]
I thought we could disable retries now since #14925.. Can you output the routes config? `istioctl pc routes POD -ojson`

**Comment by balamuru** [comment]
Ok, I got this working, had to tweak the config a bit

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "httpbin-virtual-service"
spec:
  hosts:
  - "*"
  gateways:
  - my-istio-gateway
  http:
  - match:
    - uri:
        prefix: /status
      method:
        exact: GET
    - uri:
        prefix: /delay
      method:
        exact: GET
    timeout: 20s
    retries: 
      attempts: 5      
      perTryTimeout: 3s
      retryOn: gateway-error
#      retryOn: 5xx,gateway-error,connect-failure,refused-stream
    route:
    - destination:
        host: "httpbin"
        port:
          number: 80
  - match:
    - uri:
        prefix: /status
      method:
        exact: POST
    - uri:
        prefix: /delay
      method:
        exact: POST
    route:
    - destination:
        host: "httpbin"
        port:
          number: 80

```

Results
```
 
$ siege -c1 -d1 http://127.0.0.1:31380/delay/10
** SIEGE 4.0.4
** Preparing 1 concurrent users for battle.
The server is now under siege...
HTTP/1.1 504    18.59 secs:      24 bytes ==> GET  /delay/10

PASS - Istio retries (1+5) x 3 = 18 s and times out on GET (as per expectation)

 
$ siege -c1 -d1 --content-type "application/json" '127.0.0.1:31380/delay/10 POST {"ids": ["1","2","3"]}'
** SIEGE 4.0.4
** Preparing 1 concurrent users for battle.
The server is now under siege...
HTTP/1.1 200    10.01 secs:    1078 bytes ==> POST http://127.0.0.1:31380/delay/10
 
PASS - Istio does not retry and returns after waiting 10 s on POST (above the threshold of a single retry)
 
 
$ siege -c1 -d1 --content-type "application/json" '127.0.0.1:31380/delay/2 POST {"ids": ["1","2","3"]}'
** SIEGE 4.0.4
** Preparing 1 concurrent users for battle.
The server is now under siege...
HTTP/1.1 200     2.01 secs:    1077 bytes ==> POST http://127.0.0.1:31380/delay/2

PASS - Istio does not retry and returns after waiting 2 s on POST (below the threshold of a single retry)
```
