### ISSUE TITLE
Support new kubernetes resource EndpointsSlice

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17158]
https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20190603-EndpointSlice-API.md adds a new API to Kubernetes. It has a lot of overlap with our ServiceEntry. It seems plausible that we could completely remove ServiceEntry in favor of the new API.

At the very least, we will need to update Pilot/Galley to understand EndpointSlices

Actions:

* [x] Initial support: https://github.com/istio/istio/pull/18394
* [x] Improve unit test coverage - run all tests with endpoints and slices: https://github.com/istio/istio/pull/19645
* [ ] Improve e2e coverage
* [ ] Add a mode where both endpoints and slices are read
* [ ] Do not read nodes if just using slice
* [ ] Do not require pod reading if just using slice? Needs more stuff put into the slices like SA
* [ ] Documentation
* [ ] Replace/add Endpoint Slice in place of STATIC service entry in tests/docs/users usage
* [ ] Investigate backporting endpoint slice as a CRD to old clusters

**Comment by howardjohn** [comment]
Test using kind:

```
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      "feature-gates": "EndpointSlice=true"
      "runtime-config": "discovery.k8s.io/v1alpha1=true"
  controllerManager:
    extraArgs:
      "controllers": "endpointslice"
```

`kind create cluster --image aojea/kindnode:latest --config config.yaml` (there is not official 1.16 node image yet, config.yaml refers to above)
