### ISSUE TITLE
helm install istio bookinfo-gateway error

### ISSUE THREAD

**Issue by xxlaila** [istio/istio#17168]
``` 
kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml
```
The prompt information is as follows:
```
Error when creating "samples/bookinfo/networking/bookinfo-gateway.yaml": Post https://{ip}:8443/apis/networking.istio.io/v1alpha3/namespaces/default/gateways: unexpected EOF
Error when creating "samples/bookinfo/networking/bookinfo-gateway.yaml": Post https://{ip}:8443/apis/networking.istio.io/v1alpha3/namespaces/default/virtualservices: unexpected EOF
```
Bookinfo-gateway.yaml content is
``` 
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bookinfo-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - "*"
  gateways:
  - bookinfo-gateway
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: 9080
```
istioctl version
```
client version: 1.2.5
citadel version: 1.2.5
galley version: 1.2.5
ingressgateway version: 1.2.5
pilot version: 1.2.5
policy version: 1.2.5
sidecar-injector version: 1.2.5
telemetry version: 1.2.5
```
helm version
``` 
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

Can you help me, thank you! ! !
