### ISSUE TITLE
Intermittent http failures to 169.254.169.254 on EKS for AWS instance metadata

### ISSUE THREAD

**Issue by kylebevans** [istio/istio#17171]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

After upgrading to istio 1.3.0 (previously 1.1.7), http connections to 169.254.169.254 in all namespaces would intermittently fail. The envoy access log shows "UH" which means the upstream host is unavailable. Istio is set to ALLOW_ALL but there is a serviceentry in the default namespace for this ip address.  However, pods in other namespaces also connect to that IP address without a serviceentry defined.

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: spot-interrupt-handler-external
spec:
  hosts:
  - not.used
  addresses:
  - 169.254.169.254
  ports:
  - number: 80
    name: tcp
    protocol: tcp
  location: MESH_EXTERNAL
  resolution: STATIC
  endpoints:
  - address: 169.254.169.254
---
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

-Use Istio 1.3.0 and EKS 1.14 on AWS
-Have pods which need to communicate with the worker nodes instance metadata endpoint at 169.254.169.254.  An example would be if it needs to connect to S3 using the instance profile for authentication.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-21T22:32:40Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

Istio version was 1.3.0, I don't have the output because I downgraded back to 1.1.7.

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
Did you see this one only namespace with the ServiceEntry, without, or both?

Can you expand on "intermittent"? Is this 1/10 requests or .001%? Does it occur in groups (eg, 1 minute of outage) or randomly?

Do you never see this issue on 1.1.7?

**Comment by kylebevans** [comment]
We saw this issue in both the namespace with the ServiceEntry and namespaces without the ServiceEntry.

I don't have a hard percentage, but it occurs in groups.  Maybe 5 minutes of outage at a time.  I'm guessing it follows the timing for Envoy checking upstream, marking unavailable, then checking again and marking available again.

We never saw the issue on 1.1.7, thanks.

**Comment by kylebevans** [comment]
I have 1.4.2 installed now and still see the issue.  Additionally, istioctl proxy-status shows a bunch of STALE entries.  It's like there is something intermittently dropping traffic, but I can't figure out what.

**Comment by kylebevans** [comment]
Here is a dump, thanks.

[istio-dump.tar.gz](https://github.com/istio/istio/files/3957875/istio-dump.tar.gz)

**Comment by kylebevans** [comment]
Ok I think I have this figured out.  I finally noticed messages like this in the pilot log:

```
    "ProxyStatus": {
        "pilot_conflict_outbound_listener_tcp_over_current_tcp": {
            "0.0.0.0:1433": {
                "proxy": "proxy-uat-7c76d65667-k52vr.uat",
                "message": "Listener=0.0.0.0:1433 AcceptedTCP=not.used,not.used RejectedTCP=not.used TCPServices=2"
            },
            "0.0.0.0:3306": {
                "proxy": "proxy-uat-7c76d65667-k52vr.uat",
                "message": "Listener=0.0.0.0:3306 AcceptedTCP=not.used,not.used RejectedTCP=not.used TCPServices=2"
            },
            "0.0.0.0:5432": {
                "proxy": "proxy-uat-7c76d65667-k52vr.uat",
                "message": "Listener=0.0.0.0:5432 AcceptedTCP=not.used,not.used RejectedTCP=not.used TCPServices=2"
            },
            "172.20.0.1:443": {
                "proxy": "proxy-uat-7c76d65667-k52vr.uat",
                "message": "Listener=172.20.0.1:443 AcceptedTCP=kubernetes.default.svc.cluster.local RejectedTCP=kubernetes.default.svc.cluster.local TCPServices=1"
            }
        },
        "pilot_duplicate_envoy_clusters": {
            "outbound|1433||not.used": {
                "proxy": "proxy-uat-7c76d65667-k52vr.uat",
                "message": "Duplicate cluster outbound|1433||not.used found while pushing CDS"
            },
            "outbound|3306||not.used": {
                "proxy": "proxy-uat-7c76d65667-k52vr.uat",
                "message": "Duplicate cluster outbound|3306||not.used found while pushing CDS"
            },
            "outbound|443||kubernetes.default.svc.cluster.local": {
                "proxy": "proxy-uat-7c76d65667-k52vr.uat",
                "message": "Duplicate cluster outbound|443||kubernetes.default.svc.cluster.local found while pushing CDS"
            },
            "outbound|5432||not.used": {
                "proxy": "proxy-uat-7c76d65667-k52vr.uat",
                "message": "Duplicate cluster outbound|5432||not.used found while pushing CDS"
            }
        },
        "pilot_eds_no_instances": {
            "outbound|443||kubernetes.default.svc.cluster.local": {}
        }
    },
```

So, back in 1.0, you had to define a ServiceEntry for anything that was outside the cluster, so I made the following ServiceEntries for the kubernetes api, AWS instance metadata address, postgresql, mysql, and sqlserver:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: spot-interrupt-handler-external
spec:
  hosts:
  - not.used
  addresses:
  - 169.254.169.254
  ports:
  - number: 80
    name: tcp
    protocol: tcp
  location: MESH_EXTERNAL
  resolution: STATIC
  endpoints:
  - address: 169.254.169.254
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: kubernetes-api-internal
spec:
  hosts:
  - "kubernetes.default.svc.cluster.local"
  addresses:
  - 172.20.0.1
  ports:
  - number: 443
    name: https
    protocol: tcp
  location: MESH_INTERNAL
  resolution: NONE
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: rds-mysql-external
  namespace: istio-system
spec:
  hosts:
  - not.used
  addresses:
  - 10.0.8.0/24
  - 10.0.9.0/24
  - 10.0.10.0/24
  ports:
  - name: tcp
    number: 3306
    protocol: tcp
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: rds-sqlserver-external
  namespace: istio-system
spec:
  hosts:
  - not.used
  addresses:
  - 10.0.8.0/24
  - 10.0.9.0/24
  - 10.0.10.0/24
  ports:
  - name: tcp
    number: 1433
    protocol: tcp
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: rds-postgresql-external
  namespace: istio-system
spec:
  hosts:
  - not.used
  addresses:
  - 10.0.8.0/24
  - 10.0.9.0/24
  - 10.0.10.0/24
  ports:
  - name: tcp
    number: 5432
    protocol: tcp
  location: MESH_EXTERNAL
```

These all worked perfectly in 1.1.7.  The docs at the time specified that if you fill in the addresses list, then the hosts list is ignored, so I reused "not.used" in all cases.  However it seems like at some point the hosts list became at least some kind of unique identifier that can't be duplicated.  Doing so results in pilot not being able to program the proxies.

Since Istio by default now allows all traffic instread of requiring ServiceEntries, I just deleted all these ServiceEntries and everything started working as if by magic.  The Pilot errors are gone, the STALE proxy-status entries are gone, and the UH upstream host unavailable errors are gone from Envoy logs.

I can go ahead and close this issue, but I do think there is probably a better way of failing gracefully in a situation like this, but I'm not sure if that's a bug or a feature request.  Let me know what you think.
