### ISSUE TITLE
consistentHashLB doesn't work

### ISSUE THREAD

**Issue by linsun** [istio/istio#17181]
**Bug description**
I have 2 versions of my trade services and I'm trying to apply soft sticky session via consistentHashLB so that after a user logs on, it will stick to a given version of the trade service.  Currently, I don't see it sticky and it changes to v1 or v2 based on what I configured as part of canary test.

I also checked cookie is added to the header, something like this:

``` Cookie: user=\"1d3bff24aaafca2c\"; JWT=....; user=\"1d3bff24aaafca2c\""\```

Here is my DR:

```
$ cat manifests/trader-dr-lb.yaml 
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: destination-rule-trader
spec:
  host: trader-service
  subsets:
  - name: v1
    labels:
      version: "v1"
  - name: v2
    labels:
      version: "v2"
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: user
          ttl: 300s
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Expect that I can use consistentHashLB to have sticky sessions among versions.

**Steps to reproduce the bug**
Deploy a service with multiple versions and use logins to see if the session is sticky.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.3

**How was Istio installed?**
demo profile

**Environment where bug was observed (cloud vendor, OS, etc)**
IBM Cloud KS.

**Comment by linsun** [comment]
my VS for canary 80-20 test.

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtual-service-trader
spec:
  hosts:
    - '*'
  gateways:
    - trader-gateway
  http:
    - route:
        - destination:
            host: trader-service
            subset: "v1"
            port:
              number: 9080
          weight: 80
        - destination:
            host: trader-service
            subset: "v2"
            port:
              number: 9080
          weight: 20
```

If I use firefox as the user-agent for testing v2 and everything else default to v1, that works great.
