### ISSUE TITLE
IP whitelist does not work for a specific IP

### ISSUE THREAD

**Issue by xiaozhongliu** [istio/istio#17202]
**Bug description**
IP whitelist does not work for a specific IP

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
IP whitelist works for a specific IP

**Steps to reproduce the bug**
Whitelist works normally for the following configs:
```yaml
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: whitelistip
spec:
  compiledAdapter: listchecker
  params:
    overrides: ['10.57.0.0/16']
    blacklist: false
    entryType: IP_ADDRESSES

---
apiVersion: config.istio.io/v1alpha2
kind: instance
metadata:
  name: sourceip
spec:
  compiledTemplate: listentry
  params:
    value: request.headers["remoteip"]

---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: checkip
spec:
  match: source.labels["istio"] == "ingressgateway"
  actions:
    - handler: whitelistip
      instances: [sourceip]
```
But not when I change the ip range to a specific one:
```yaml
...
spec:
  compiledAdapter: listchecker
  params:
    overrides: ['123.321.123.321']
    blacklist: false
    entryType: IP_ADDRESSES
...
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
~ istioctl version --remote
client version: 1.2.5
grafana version:
grafana version:
citadel version: 1.2.5
galley version: 1.2.5
ingressgateway version: 1.2.5
pilot version: 1.2.5
pilot-gateway version:
policy version: 1.2.5
policy-gateway version:
sidecar-injector version: 1.2.5
telemetry version: 1.2.5
telemetry-gateway version:
kiali version:
prometheus version:
```
```
~ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:19Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-aliyun.1", GitCommit:"8cb561c", GitTreeState:"", BuildDate:"2019-05-23T11:28:17Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Aliyun ACK, Operator

**Environment where bug was observed (cloud vendor, OS, etc)**
Aliyun ACK, CentOS 7
