### ISSUE TITLE
httpprob doesn't work per deployment

### ISSUE THREAD

**Issue by linsun** [istio/istio#17215]
**Bug description**

I have health check on my service, all running fine before I added mTLS auth policy for the namespace.

After the auth policy is added, i started to see health check fail for my service.

Following instruction - https://istio.io/docs/ops/app-health-check/#use-annotations-on-pod, i added

```
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
```
for my deployment and redeployed, but the pod still fails at health check.  

```
  Warning  Unhealthy  7m19s (x81 over 25m)  kubelet, 10.188.142.236  (combined from similar events): Liveness probe failed: Get http://172.30.244.102:9080/health/live: read tcp 10.188.142.236:53927->172.30.244.102:9080: read: connection reset by peer
```
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
health check of the service should turn green after the annotation and redeployment.

**Steps to reproduce the bug**
Deploy a service that has health check in the mesh, then enable auth policy and destination rule for the namespace the service is deployed.

```
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "default"
spec:
  peers:
  - mtls: {}
```

```
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "default"
spec:
  host: "*"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```
**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.3

**How was Istio installed?**
demo profile

**Environment where bug was observed (cloud vendor, OS, etc)**
IBM KS
