### ISSUE TITLE
Access Service with Domain Name + Custom Port

### ISSUE THREAD

**Issue by Rettpa** [istio/istio#17210]
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: nginx-gateway
  namespace: test
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http2
      protocol: HTTP2
    hosts:
    - "istio01.test.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-virtualservice
  namespace: test
spec:
  hosts:
  - "istio01.test.com"
  - "mesh"
  gateways:
  - nginx-gateway
  http:
  - match:
    - port: 31380
      uri:
        prefix: /
    route:
    - destination:
        host: nginx-service
        port:
          number: 10101
```

Yaml's configuration file is as follows. I want to access the service by using domain name + port, but
Services cannot be accessed through this domain name in the browser: http://istio01.test.com:31380
If hosts use "*", they can be accessed normally.
istio version 1.2.2 
k8s version 1.14.0
