### ISSUE TITLE
VirtualService uri rewrite is ignored when routing between internal services

### ISSUE THREAD

**Issue by Janesee3** [istio/istio#17251]
**Bug description**
Uri rewrite for a VirtualService resource where the host is an internal service and the destination is also an internal service does not work. (See steps to reproduce for an example of the VirtualService)

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Uri should be rewritten as expected.

**Steps to reproduce the bug**

When a VirtualService like the following is created:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: first-hop
spec:
  gateways:
    - default
  hosts:
    - my-load-balancer-host
  http:
    - match:
        - uri:
            exact: /app.js
      # working
      rewrite:
        uri: /first-rewrite-uri
      route:
        - destination:
            host: foo-service.default.svc.cluster.local
            port:
              number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
 name: second-hop
spec:
  hosts:
    - foo-service.default.svc.cluster.local
  http:
    - match:
        - uri:
            exact: /first-rewrite-uri
          port: 8080
      # Not working
      rewrite:
        uri: /second-rewrite-uri
      route:
        - destination:
            host: my-app.default.svc.cluster.local
            port:
              number: 8080
```

When we curl `my-load-balancer-host/app.js`, the uri is correctly re-written to `/first-rewrite-uri` as seen in the `first-hop` VirtualService. However, even though the request is correctly routed to `my-app.default.svc.cluster.local` at the end, the uri is not re-written to `/second-rewrite-uri` .  (I can see the request path of incoming requests from the logs of my-app)

When I run the `istioctl proxy-config routes <my-app-pod-name> -o json` command, I can see that the rewrite configuration is correct reflected, but just not taking effect:

```json
{
  ...
  ...
  "name": "foo-service.default.svc.cluster.local:8080",
  "domains": [
      "foo-service.default.svc.cluster.local",
      "foo-service.default.svc.cluster.local:8080",
  ],
  "routes": [
      {
          "match": {
              "exact": "/first-rewrite-uri",
              "caseSensitive": true
          },
          "route": {
              "cluster": "outbound|8080||my-app.default.svc.cluster.local",
              "prefixRewrite": "/second-rewrite-uri",
              "hostRewrite": "",
              "timeout": "0s",
              "retryPolicy": {
                  "retryOn": "connect-failure,refused-stream,unavailable,cancelled,resource-exhausted,retriable-status-codes",
                  "numRetries": 2,
                  "retryHostPredicate": [
                      {
                          "name": "envoy.retry_host_predicates.previous_hosts"
                      }
                  ]
...
...
}                  
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
citadel version: 1.3.0
egressgateway version: 1.3.0
galley version: 1.3.0
ingressgateway version: 1.3.0
pilot version: 1.3.0
policy version: 1.3.0
sidecar-injector version: 1.3.0
telemetry version: 1.3.0

Using EKS with Kubernetes v1.13

**Comment by howardjohn** [comment]
I see that it doesn't work, but I don't think this is or should be a valid config in the first place. Logically you are trying to make a virtual service with "two hops" -- but in reality there will only be one hop.

Is there any reason you cannot just make a single VirtualService here? If it wasn't clear, VS only apply on the client side, so you are never actually getting two hops -- it is all done by the gateway

**Comment by Janesee3** [comment]
I tried this out with a single virtual service that is not attached to any gateway, and the uri rewrite is not happening too. Below is an example of the virtualservice i used:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-route
spec:
  hosts:
  - service-one.default.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: /
    rewrite:
      uri: /written-uri
    route:
    - destination:
        host: service-two.default.svc.cluster.local
```

To give more context, we are trying to use Istio VirtualService uri rewrites and weighted routes to load balance traffic between 2 endpoints served by a single Kubernetes service. 
Example:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: first-hop
spec:
  gateways:
    - default
  hosts:
    - my-load-balancer-host
  http:
    - match:
        - uri:
            exact: /app.js
      route:
        - destination:
              host: dummy-service-for-new-script.default.svc.cluster.local
            weight: 90
        - destination:
              host: dummy-service-for-old-script.default.svc.cluster.local
            weight: 10
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
 name: new-script-route
spec:
  hosts:
    - dummy-service-for-new-script.default.svc.cluster.local
  http:
    - match:
        - uri:
            exact: /app.js
      rewrite:
        uri: /static/new-app.js
      route:
        - destination:
            host: my-app.default.svc.cluster.local
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
 name: old-script-route
spec:
  hosts:
    - dummy-service-for-old-script.default.svc.cluster.local
  http:
    - match:
        - uri:
            exact: /app.js
      rewrite:
        uri: /static/old-app.js
      route:
        - destination:
            host: my-app.default.svc.cluster.local
``` 

While trying out the configuration above, we realised that even though traffic was still routed to `my-app` correctly, the uri was not re-written. 

Sorry could you also explain further what you mean by VS routing never actually getting two hops?  Thank you!

**Comment by howardjohn** [comment]
It seem to me in your original config you expected the request to go from `Ingress ---- rewrite1 ---> foo ----- rewrite2 ---> my-app` but that doesn't actually happen. It will just go directly from ingress to my-app

@Janesee3 I tried out the example you gave, slightly modified to my services:

```yaml
cat <<EOF | kaf -
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-route
spec:
  hosts:
  - productpage.default.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: /
    rewrite:
      uri: /get
    route:
    - destination:
        host: httpbin.default.svc.cluster.local
EOF
```

and it worked as expected.

I am not sure if the first case of multiple hops should work (I suspect not), but the above definitely should

**Comment by Janesee3** [comment]
Oh I see, so as long as we have a VirtualService entry from `Ingress --- my-app`, all other VS applied to `host: my-app` would not apply? 

Also, can I clarify that uri rewrite wouldn't work for "self-routing" VS? Like for example:
```yaml
# Assuming that my-app is not routed from another VS via the Ingress
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: self-route
  namespace: services
spec:
  hosts:
  - my-app.default.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: /
    rewrite:
      uri: /written-uri
    route:
    - destination:
        host: my-app.default.svc.cluster.local
```
