### ISSUE TITLE
tcp  ingressgateway   

### ISSUE THREAD

**Issue by 1032231418** [istio/istio#17293]
hi:

After the creation of 31400 ports can not telnet, but HTTP 80 can pass

istio: v1.3.0

kubernetes:  v1.11.5

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: dev-api
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 31400
      name: tcp
      protocol: TCP
    hosts:
    - "*"
```
