### ISSUE TITLE
Locality LB does not work after upgrading istio

### ISSUE THREAD

**Issue by xiaozhongliu** [istio/istio#17308]
**Bug description**
Locality LB does not work after upgrading istio from 1.1.8 to 1.2.6.

**Affected product area (please put an X in all that apply)**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Locality LB works normally.

**Steps to reproduce the bug**
Config is like this:
```yaml
  localityLbSetting:
    enabled: true
    distribute:
      - from: cn-hangzhou/cn-hangzhou-g/*
        to:
          'cn-hangzhou/cn-hangzhou-b/*': 100
      - from: cn-beijing/cn-beijing-g/*
        to:
          'cn-beijing/cn-beijing-g/*': 100
    failover:
      - from: cn-beijing
        to: cn-hangzhou
      - from: us-east-1
        to: cn-hangzhou
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
istioctl version
client version: 1.2.6
grafana version:
grafana version:
citadel version: 1.2.6
galley version: 1.2.6
ingressgateway version: 1.2.6
pilot version: 1.2.6
pilot-gateway version:
policy version: 1.2.6
policy-gateway version:
sidecar-injector version: 1.2.6
telemetry version: 1.2.6
telemetry-gateway version:
kiali version:
prometheus version:
```

**How was Istio installed?**
Aliyun ACK, Operator

**Environment where bug was observed (cloud vendor, OS, etc)**
Aliyun ACK, CentOS 7
