### ISSUE TITLE
istioctl does not work for Kubernetes kind `List`

### ISSUE THREAD

**Issue by kameshsampath** [istio/istio#1733]
```
Version: 0.2.12
GitRevision: 998e0e00d375688bcb2af042fc81a60ce5264009
GitBranch: release-0.2
User: releng@0d29a2c0d15f
GolangVersion: go1.8
```
when there is a Kubernetes manifest that is if of kind `List`, then  istioctl does not work injecting sidecars 

e.g. maninfest
```
---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/git-commit: 184fff19f1e17d55c9d323ddeb244d8f6e6e2b60
      fabric8.io/iconUrl: img/icons/vertx.svg
      fabric8.io/git-branch: master
      prometheus.io/scrape: "true"
      prometheus.io/port: "9779"
    labels:
      expose: "true"
      app: aloha
      provider: fabric8
      version: 0.0.3-SNAPSHOT
      group: com.redhat.developers.msa.aloha
    name: aloha
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: aloha
      provider: fabric8
      group: com.redhat.developers.msa.aloha
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      fabric8.io/git-commit: 184fff19f1e17d55c9d323ddeb244d8f6e6e2b60
      fabric8.io/iconUrl: img/icons/vertx.svg
      fabric8.io/git-branch: master
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=aloha&var-version=0.0.3-SNAPSHOT
    labels:
      app: aloha
      provider: fabric8
      version: 0.0.3-SNAPSHOT
      group: com.redhat.developers.msa.aloha
    name: aloha
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: aloha
        provider: fabric8
        group: com.redhat.developers.msa.aloha
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: 184fff19f1e17d55c9d323ddeb244d8f6e6e2b60
          fabric8.io/iconUrl: img/icons/vertx.svg
          fabric8.io/git-branch: master
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=aloha&var-version=0.0.3-SNAPSHOT
        labels:
          app: aloha
          provider: fabric8
          version: 0.0.3-SNAPSHOT
          group: com.redhat.developers.msa.aloha
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: kameshsampath/aloha:0.0.3-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: vertx
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          securityContext:
            privileged: false

```
