### ISSUE TITLE
Analyzer validation messages should support source pathing

### ISSUE THREAD

**Issue by sushicw** [istio/istio#17349]
The structured validation messages used by Analyzers should support pathing, so that validation errors can be back-mapped to specific lines of yaml input. Kiali does something like this already, and it's very useful.

Previous conversations on this topic:
* https://github.com/istio/istio/pull/15824#discussion_r313638133
* https://github.com/istio/istio/pull/17327#issuecomment-534609337

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by burmanm** [comment]
Was this source pathing intended to be as a parameter for certain messages? So for example:

```yaml
  - name: "ReferencedResourceNotFound"
    code: IST0101
    level: Error
    description: "A resource being referenced does not exist."
    template: "Referenced %s not found: %q"
    args:
      - name: reftype
        type: string
      - name: refval
        type: string
      - name: path
        type: string
```
