### ISSUE TITLE
Host Header rewrite is not working

### ISSUE THREAD

**Issue by rjshrjndrn** [istio/istio#17344]
Hi,

```
  - match:
    - uri:
        prefix: /apps
    rewrite:
      uri: /apps/v3/preview/
    route:
    - destination:
        host: apps-service
      host_rewrite: apps.local.lab
```
As per envoy [documentation](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#route-routeaction) `Host: ` header should get rewritten.

But when I apply this `virtualservice` nothing is happening.
1. No logs in pilot
2. Same goes for ingress gateway

But Host is still the old one.

Couldn't find any specific resource for istio of Host header manipulation.

Am I missing anything ..

**Comment by rjshrjndrn** [comment]
Couldn't figure it out. Can you kindly note an example ? @esnible

**Comment by rjshrjndrn** [comment]
Got it. Thanks @esnible 

This is the solution to `Host` header rewrite in istio
```
  - match:
    - uri:
        prefix: /sunbird
    rewrite:
      uri: /
      authority: sunbirddev.blob.core.windows.net
    route:
    - destination:
        host: headercho
```
authority section will rewrite the `Host` header to the value which you're providing
