### ISSUE TITLE
EnvoyFilter with use_remote_address and xff_num_trusted_hops set is not being applied

### ISSUE THREAD

**Issue by lorenzoqricambi** [istio/istio#17351]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
use_remote_address and xff_num_trusted_hops applied using envoyfilter do not apply

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
as described here
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-envoy-internal
when I set use_remote_address=true and xff_num_trusted_hops=0 using the new EnvoyFilter api I should see the xff header rewritten by envoy but the gateway ip does not get added to xff and I cannot add the header  x-envoy-force-trace to the next request.

**Steps to reproduce the bug**
Apply the following following yaml:

```
kind: EnvoyFilter
metadata:
  name: hcm-tweaks
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: ingress-gateway
  configPatches:
  - applyTo: NETWORK_FILTER # http connection manager is a filter in Envoy
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
    patch:
      operation: MERGE
      value:
        config:
          use_remote_address: true
          xff_num_trusted_hops: 0

```
**Version (include the output of `istioctl version --remote` and `kubectl version`)**
client version: 1.3.0
control plane version: 1.3.0

Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.9-2+4a03651a7e7e04", GitCommit:"4a03651a7e7e04a0021b2ef087963dfb7bd0a17e", GitTreeState:"clean", BuildDate:"2019-08-16T18:57:20Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.8", GitCommit:"7d3d6f113e933ed1b44b78dff4baf649258415e5", GitTreeState:"clean", BuildDate:"2019-06-19T16:37:16Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
GCP

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
I found out very recently the docs were a bit wrong, I don't know if the PRs have made it live into istio.io yet. I have an example of a very similar config here: https://github.com/istio/istio/wiki/EnvoyFilter-Samples#http2-flow-control

Basically adding the 
```

        typed_config:
          "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager"
```

Can you try that?

**Comment by lorenzoqricambi** [comment]
This is the complete configuration I have applied to my ingress-gateway:
```

apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1alpha3","kind":"EnvoyFilter","metadata":{"annotations":{},"name":"qricambi-redirectto443","namespace":"istio-system"},"spec":{"configPatches":[{"applyTo":"HTTP_FILTER","match":{"context":"GATEWAY","listener":{"filterChain":{"filter":{"name":"envoy.http_connection_manager","subFilter":{"name":"envoy.router"}}}}},"patch":{"operation":"INSERT_BEFORE","value":{"config":{"inlineCode":"function envoy_on_request(request_handle)\n    tlsv =  request_handle:headers():get(\"x-tls-version\")\n    if tlsv == nil or tlsv == ''  then\n        request_handle:respond(\n            {[\":status\"] = \"301\", [\"location\"] = \"https://\" .. request_handle:headers():get(\":authority\") .. request_handle:headers():get(\":path\")},\n            \"\")\n    end\nend\n"},"name":"envoy.lua"}}}],"workloadSelector":{"labels":{"app":"istio-ingressgateway"}}}}
  creationTimestamp: "2019-09-23T13:41:02Z"
  generation: 36
  name: qricambi-redirectto443
  namespace: istio-system
  resourceVersion: "1835265"
  selfLink: /apis/networking.istio.io/v1alpha3/namespaces/istio-system/envoyfilters/qricambi-redirectto443
  uid: c896eb5c-de07-11e9-bdac-4201ac101e04
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
    patch:
      operation: MERGE
      value:
        typed_config:
          '@type': type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          use_remote_address: true
          xff_num_trusted_hops: 0
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              name: envoy.router
    patch:
      operation: INSERT_BEFORE
      value:
        config:
          inlineCode: |
            function envoy_on_request(request_handle)
                request_handle:headers():replace("x-envoy-force-trace", "true")
                request_handle:logErr("Added forced trace")
                tlsv = request_handle:headers():get("x-tls-version")
                if tlsv == nil or tlsv == ''  then
                    request_handle:respond(
                        {[":status"] = "301", ["location"] = "https://" .. request_handle:headers():get(":authority") .. request_handle:headers():get(":path")},
                        "")
                end
            end
        name: envoy.lua
  workloadSelector:
    labels:
      app: istio-ingressgateway
```

Then in my destination service I apply this lua filter: 
 

```
 function envoy_on_response(response_handle)
  for key, value in pairs(response_handle:headers()) do
    response_handle:logErr("RESP " .. key .. " " .. value)
   end
 
function envoy_on_request(request_handle)
  for key, value in pairs(request_handle:headers()) do
     request_handle:logErr("REQ " .. key .. " " .. value)
  end
end

```

so I can clearly see that the request the service receives has these headers:
- x-forwarded-for (myip), (externalgcp ip),10.28.0.1 <- google internal lb
- x-envoy-external-address 10.28.0.1 <- still google internal lb
I expected that the last ip in xff would be the gateway ip, and also in ext-addr header.
I also think that this is the reason I do not receive the header x-envoy-force-trace as true in my services.

My need is to be able to trace every single transaction (request/response) with its headers and bodies. Before istio I was using packetbeat for this.
Now I planned to send an http request with a lua filter to fluentd with all these information plus the x-request-id that must be present in the response's headers for me to be able to reconstruct request/response transaction later.

English isn’t my first language, so please excuse any mistakes.

Thanks in advance, Lorenzo.

**Comment by lorenzoqricambi** [comment]
Any suggestions?

Thanks

**Comment by howardjohn** [comment]
I just tried this out with config here: https://github.com/istio/istio/wiki/EnvoyFilter-Samples#use-remote-address-and-xff-num-trust-hops

Can you try that?

Getting a config dump and making sure it applies correctly is useful to. I suggest you look to make sure config is applied correctly, then try to make sure it behaves as you expect.

**Comment by achetronic** [comment]
/open The bug still persist @howardjohn 

Let me throw some data:

**Istio version: 1.26.2
Gateway API version 1.3.0**

the manifest 

```yaml

apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: configure-trusted-cidrs
  namespace: istio
spec:
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: ANY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: MERGE
        value:
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            xff_num_trusted_hops: 13 # this is only here to test if the filter is placed wherever we want it after that

            use_remote_address: false # doesn't change ...
            skip_xff_append: false # doesn't change ...

            xff_trusted_cidrs: # doesn't change ...
              - address: "10.0.0.0"
                prefix_len: 8
              - address: "35.xxx.xxx.0"
                prefix_len: 16
              - address: "130.xxx.0.0"
                prefix_len: 22
              - address: "34.xxx.xxx.26"
                prefix_len: 32
              - address: "34.xxx.xxx.140"
                prefix_len: 32
              - address: "35.xxx.xxx.165"
                prefix_len: 32

  workloadSelector:
    labels:
      is-gateway: "true"
```

The result is that the num_trusted_hops is the only field changing, and the rest are not even added:

```json
 "http_protocol_options": {},
            "server_name": "istio-envoy",
            "access_log": [
             {
              "name": "envoy.access_loggers.file",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog",
               "path": "/dev/stdout",
               "log_format": {
                "json_format": {
                 "upstream_service_time": "%REQ(X-ENVOY-UPSTREAM-SERVICE-TIME)%",
                 "requested_server_name": "%REQUESTED_SERVER_NAME%",
                 "request_id": "%REQ(X-REQUEST-ID)%",
                 "response_code": "%RESPONSE_CODE%",
                 "protocol": "%PROTOCOL%",
                 "user_agent": "%REQ(USER-AGENT)%",
                 "request_duration": "%REQUEST_DURATION%",
                 "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
                 "duration": "%DURATION%",
                 "bytes_received": "%BYTES_RECEIVED%",
                 "downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%",
                 "upstream_transport_failure_reason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%",
                 "response_duration": "%RESPONSE_DURATION%",
                 "start_time": "%START_TIME%",
                 "upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%",
                 "authority": "%REQ(:AUTHORITY)%",
                 "x_forwarded_for": "%REQ(X-FORWARDED-FOR)%",
                 "upstream_host": "%UPSTREAM_HOST%",
                 "method": "%REQ(:METHOD)%",
                 "route_name": "%ROUTE_NAME%",
                 "response_code_details": "%RESPONSE_CODE_DETAILS%",
                 "client_ip": "%REQ(TRUE-Client-IP)%",
                 "request_attempt": "%REQ(X-ENVOY-ATTEMPT-COUNT)%",
                 "response_flags": "%RESPONSE_FLAGS%",
                 "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%",
                 "upstream_cluster": "%UPSTREAM_CLUSTER%",
                 "bytes_sent": "%BYTES_SENT%"
                },
                "json_format_options": {}
               }
              }
             }
            ],
            "use_remote_address": true,
            "generate_request_id": false,
            "forward_client_cert_details": "SANITIZE_SET",
            "set_current_client_cert_details": {
             "subject": true,
             "cert": true,
             "dns": true,
             "uri": true
            },
            "proxy_100_continue": true,
            "xff_num_trusted_hops": 13,
            "upgrade_configs": [
             {
              "upgrade_type": "websocket"
             }
            ],
            "stream_idle_timeout": "0s",
            "normalize_path": true,
            "request_id_extension": {
             "typed_config": {
              "@type": "type.googleapis.com/envoy.extensions.request_id.uuid.v3.UuidRequestIdConfig",
              "use_request_id_for_trace_sampling": true
             }
```


As you can see, the `use_remote_address` and the other fields not being num_trusted_hops are being modified

**Comment by zirain** [comment]
please make sure that the namespace and workloadselector match the pod you're targeting.

**Comment by achetronic** [comment]
> please make sure that the namespace and workloadselector match the pod you're targeting.

Hello there :)

They match, if you see, the num-trusted-hops is properly applied, but the rest of the fields are not. The json is extracted using istioctl to get that envoy config from the gateway

**Comment by zirain** [comment]
> > please make sure that the namespace and workloadselector match the pod you're targeting.
> 
> Hello there :)
> 
> They match, if you see, the num-trusted-hops is properly applied, but the rest of the fields are not. The json is extracted using istioctl to get that envoy config from the gateway

1. use_remote_address use  `false` as default value.

2. the rest is not a valid fields on HCM, but part of XffConfig, so that worked as expected.
```
            skip_xff_append: false # doesn't change ...

            xff_trusted_cidrs: # doesn't change ...
              - address: "10.0.0.0"
                prefix_len: 8
              - address: "35.xxx.xxx.0"
                prefix_len: 16
              - address: "130.xxx.0.0"
                prefix_len: 22
              - address: "34.xxx.xxx.26"
                prefix_len: 32
              - address: "34.xxx.xxx.140"
                prefix_len: 32
              - address: "35.xxx.xxx.165"
                prefix_len: 32

```

**Comment by achetronic** [comment]
> > > please make sure that the namespace and workloadselector match the pod you're targeting.
> > 
> > 
> > Hello there :)
> > They match, if you see, the num-trusted-hops is properly applied, but the rest of the fields are not. The json is extracted using istioctl to get that envoy config from the gateway
> 
> 1. use_remote_address use  `false` as default value.
> 2. the rest is not a valid fields on HCM, but part of XffConfig, so that worked as expected.
> 
> ```
>             skip_xff_append: false
>
>             xff_trusted_cidrs:
>               - address: "10.0.0.0"
>                 prefix_len: 8
>               - address: "35.xxx.xxx.0"
>                 prefix_len: 16
>               - address: "130.xxx.0.0"
>                 prefix_len: 22
>               - address: "34.xxx.xxx.26"
>                 prefix_len: 32
>               - address: "34.xxx.xxx.140"
>                 prefix_len: 32
>               - address: "35.xxx.xxx.165"
>                 prefix_len: 32
> ```

So the proper EnvoyFilter would be:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: configure-trusted-cidrs
  namespace: istio
spec:
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: ANY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: MERGE
        value:
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            # Ref: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/http/original_ip_detection/xff/v3/xff.proto#extensions-http-original-ip-detection-xff-v3-xffconfig
            xff_num_trusted_hops: 0
            use_remote_address: false # doesn't change ...

            # Ref: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/http/original_ip_detection/xff/v3/xff.proto
            original_ip_detection_extensions:
              - name: "envoy.extensions.http.original_ip_detection.xff"
                typed_config:
                  "@type": "type.googleapis.com/envoy.extensions.http.original_ip_detection.xff.v3.XffConfig"
                  xff_num_trusted_hops: 0
                  skip_xff_append: false
                  xff_trusted_cidrs: 
                    cidrs:
                      - address_prefix: "10.0.0.0"
                        prefix_len: 8
                      - address_prefix: "35.xxx.0.0"
                        prefix_len: 16
                      - address_prefix: "130.xxx.0.0"
                        prefix_len: 22
                      - address_prefix: "34.xxx.xxx.26"
                        prefix_len: 32
                      - address_prefix: "34.xxx.xxx.140"
                        prefix_len: 32
                      - address_prefix: "35.xxx.xxx.165"
                        prefix_len: 32
```

This create a piece of config like


```json
            "http_protocol_options": {},
            "server_name": "istio-envoy",
            "access_log": [
             {
              "name": "envoy.access_loggers.file",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog",
               "path": "/dev/stdout",
               "log_format": {
                "json_format": {
                 "upstream_service_time": "%REQ(X-ENVOY-UPSTREAM-SERVICE-TIME)%",
                 "requested_server_name": "%REQUESTED_SERVER_NAME%",
                 "request_id": "%REQ(X-REQUEST-ID)%",
                 "response_code": "%RESPONSE_CODE%",
                 "protocol": "%PROTOCOL%",
                 "user_agent": "%REQ(USER-AGENT)%",
                 "request_duration": "%REQUEST_DURATION%",
                 "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
                 "duration": "%DURATION%",
                 "bytes_received": "%BYTES_RECEIVED%",
                 "downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%",
                 "upstream_transport_failure_reason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%",
                 "response_duration": "%RESPONSE_DURATION%",
                 "start_time": "%START_TIME%",
                 "upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%",
                 "authority": "%REQ(:AUTHORITY)%",
                 "x_forwarded_for": "%REQ(X-FORWARDED-FOR)%",
                 "upstream_host": "%UPSTREAM_HOST%",
                 "method": "%REQ(:METHOD)%",
                 "route_name": "%ROUTE_NAME%",
                 "response_code_details": "%RESPONSE_CODE_DETAILS%",
                 "client_ip": "%REQ(TRUE-Client-IP)%",
                 "request_attempt": "%REQ(X-ENVOY-ATTEMPT-COUNT)%",
                 "response_flags": "%RESPONSE_FLAGS%",
                 "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%",
                 "upstream_cluster": "%UPSTREAM_CLUSTER%",
                 "bytes_sent": "%BYTES_SENT%"
                },
                "json_format_options": {}
               }
              }
             }
            ],
            "use_remote_address": true,
            "generate_request_id": false,
            "forward_client_cert_details": "SANITIZE_SET",
            "set_current_client_cert_details": {
             "subject": true,
             "cert": true,
             "dns": true,
             "uri": true
            },
            "proxy_100_continue": true,
            "xff_num_trusted_hops": 12, # THE DEFAULT VALUE I HAVE
            "upgrade_configs": [
             {
              "upgrade_type": "websocket"
             }
            ],
            "stream_idle_timeout": "0s",
            "normalize_path": true,
            "request_id_extension": {
             "typed_config": {
              "@type": "type.googleapis.com/envoy.extensions.request_id.uuid.v3.UuidRequestIdConfig",
              "use_request_id_for_trace_sampling": true
             }
            },
            "path_with_escaped_slashes_action": "KEEP_UNCHANGED",
            "original_ip_detection_extensions": [
             {
              "name": "envoy.extensions.http.original_ip_detection.xff",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.http.original_ip_detection.xff.v3.XffConfig",
               "xff_trusted_cidrs": {
                "cidrs": [
                 {
                  "address_prefix": "10.0.0.0",
                  "prefix_len": 8
                 }, ... THE OTHERS
```

The problem I see is with use_remote_address, as there is not any option in Istio docs to change the default value:
https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig

Are you talking about setting it by setting feature flags? https://istio.io/latest/docs/reference/commands/pilot-agent/

I mean this env variable `PILOT_SIDECAR_USE_REMOTE_ADDRESS`, Is this variable affecting gateways too? (asking because of the specific sidecar-related name)
