### ISSUE TITLE
traffic shifting not working for https service behind nginx

### ISSUE THREAD

**Issue by qi-min** [istio/istio#17377]
**Bug description**
Our application use nginx to redirect request to different service. nginx is also running in a pod. 
When I add Destination Rule and VirtualService for service A, I send request to nginx and request will be routed service A. But the traffic is not correctly shifted as definition in VirtualService. There is no outbound log in the log of istio-proxy for nginx pod.

But the traffic is correct if I run curl to service A directly inside nginx container and I can see outbound in log.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
https traffic for service redirected by nginx also works

**Steps to reproduce the bug**
1. deploy a nginx pod 
2. deploy a https app ( two deployment, v1 and v2), create a Service( `appservice` ) for this app
3. config nginx to route to this app
```
location ^~ /api/v1/test {
                proxy_pass https://appservice:8443;
                proxy_http_version 1.1;
                proxy_set_header Connection "";
        }
```
4. Create DestinationRule and VirtualService for service `appservice`, route all traffic to v1
5. Access nginx by `curl -k https://<host>/api/v1/test`, only app v1 is expected to be accessed, but app v1 and v2 are accessed randomly.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
client version: 1.2.5
citadel version: 1.2.5
galley version: 1.2.5
ingressgateway version: 1.2.5
pilot version: 1.2.5
policy version: 1.2.5
sidecar-injector version: 1.2.5
telemetry version: 1.2.5

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.7", GitCommit:"65ecaf0671341311ce6aea0edab46ee69f65d59e", GitTreeState:"clean", BuildDate:"2019-01-24T19:22:45Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
helm install

**Environment where bug was observed (cloud vendor, OS, etc)**
linux

**Comment by howardjohn** [comment]
Please include your config you applied, as well as a config dump (see https://github.com/istio/istio/wiki/Troubleshooting-Istio#collecting-information-2)

**Comment by qi-min** [comment]
hi @howardjohn  here is the trace followed by the guide:
[trace.zip](https://github.com/istio/istio/files/3666333/trace.zip)

And this is nginx config rule I used for test, nginx will call service `web-a`
```
resolver 10.96.0.10;
server {
        listen 443 ssl;
        listen 9080;

        root /usr/share/nginx/html;
        index index.html;

        server_name localhost;
        ssl_certificate /etc/nginx/ssl/tls.crt;
        ssl_certificate_key /etc/nginx/ssl/tls.key;

        access_log           /var/log/nginx/access.test.log main;
        error_log            /var/log/nginx/error.test.log;

        location ^~ /api/v1 {
          rewrite /api/v1/(.*)$ /$1 break;
          proxy_pass https://web-a.default.svc.cluster.local:8443;
          proxy_http_version 1.1;
          proxy_set_header Connection "";
        }   
}
```

VirtualService
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: weba
spec:
  hosts:
  - web-a
  http:
  - route:
    - destination:
        host: web-a
        subset: production
      weight: 0
    - destination:
        host: web-a
        subset: canary
      weight: 100
  tls:
  - match:
    - port: 8443
      sni_hosts:
      - web-a
    route:
    - destination:
        host: web-a
        subset: production
        port:
          number: 8443
      weight: 100
    - destination:
        host: web-a
        subset: canary
        port:
          number: 8443
      weight: 0
```
