### ISSUE TITLE
Azure AKS istio with load balancer persistent/sticky session

### ISSUE THREAD

**Issue by markjayniel** [istio/istio#17384]
**Describe the feature request**
We are testing a web app in AKS with istio front end as traffic management. The app requires a **persistent session** configured on the load balancer and **sticky session** in pods to be configured. I understand that DestinationRule would solve the pods and istio session but I cannot find any documentation how to setup Azure load balancer with persistent session under istio.

I do not see anyone online using this feature so I am hoping this ticket will help. If istio has sticky session (on pods) and persistent session (on azure lb) available, can you give me directions, how can I set this up correctly?

Here is the link for azure load balancer sticky session:
https://social.technet.microsoft.com/wiki/contents/articles/51997.azure-configure-load-balancer-for-sticky-sessions.aspx

Here is the link I followed for istio sticky session:
https://dev.to/peterj/what-are-sticky-sessions-and-how-to-configure-them-with-istio-1e1a

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: system-gw
  namespace: qa
spec:
  selector:
    istio: istio-public-ingressgateway-qa
  servers:
    - port:
        number: 80
        name: http-system
        protocol: HTTP
      hosts:
       - "webapp.cluster.xyz"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: system-app
  namespace: qa
spec:
  hosts:
    - "webapp.cluster.xyz"
  gateways:
    - system-gw
  http:
    - route:
      - destination:
          port:
            number: 8080
          host: system-web.app-qa.svc.cluster.local

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
    name: system-qa-sticky
    namespace: qa
spec:
    host: system-web.app-qa.svc.cluster.local
    trafficPolicy:
      loadBalancer:
        consistentHash:
          httpCookie:
            name: system-qa-user
            ttl: 0s
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[X] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
