### ISSUE TITLE
VirtualService not work for k8s external service

### ISSUE THREAD

**Issue by liuliqiang** [istio/istio#17405]
**Bug description**

I want to add a external service (which only with ip and port，also it's tls) to our istio service mesh. My idea to do this is following:

1. Add a k8s external service to add this service into k8s
2. Add a Istio VirtualService and Destionaltion Rule to convert inner tcp to outer TLS

The config is following

<details><summary> A sleep pod for test </summary>

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sleep
---
apiVersion: v1
kind: Service
metadata:
  name: sleep
  labels:
    app: sleep
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: sleep
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sleep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sleep
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: sleep
      containers:
        - name: sleep
          image: pstauffer/curl
          command: ["/bin/sleep", "3650d"]
          imagePullPolicy: IfNotPresent
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
---
```

</details>

 <details><summary>K8S External Service</summary>

```
---
kind: Service
apiVersion: v1
metadata:
  name: sz-df-http
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
---
kind: Endpoints
apiVersion: v1
metadata:
  name: sz-df-http
subsets:
  - addresses:
      - ip: 192.168.57.24
    ports:
      - port: 443
---
kind: Service
apiVersion: v1
metadata:
  name: sz-df-http-2
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
---
kind: Endpoints
apiVersion: v1
metadata:
  name: sz-df-http-2
subsets:
  - addresses:
      - ip: 192.168.57.24
    ports:
      - port: 443
```

</details>

 <details><summary> Virtual Service</summary>

```
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sz-df-http
spec:
  hosts:
  - sz-df-http.default.svc.cluster.local
  gateways:
  - mesh
  tcp:
    - match:
        - port: 80
      route:
        - destination:
            host: sz-df-http-2.default.svc.cluster.local
            port:
              number: 443
          weight: 100

```
</details>

 <details><summary> Destionation Rule</summary>

```
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: sz-df-https
spec:
  host: sz-df-http-2.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
      - port:
          number: 443
        tls:
          mode: DISABLE
```
</details>

**Affected product area (please put an X in all that apply)**

- [x] Configuration Infrastructure

**Expected behavior**

Tls Service out of the istio service mesh can be used by tcp inner istio service mesh.

**Steps to reproduce the bug**

1. Run a injected sleep pod in k8s
2. Apply the configs upper 
3. Run `curl -I http://sz-df-http.default.svc.cluster.local` in sleep pod to test the service mesh.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```
# istioctl version --remote
client version: 1.2.2
citadel version: 1.2.2
egressgateway version: 1.2.2
galley version: 1.2.2
ingressgateway version: 1.2.2
pilot version: 1.2.2
pilot version: 1.2.2
policy version: 1.2.2
sidecar-injector version: 1.2.2
telemetry version: 1.2.2
# kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

```
# cd istio-1.2.2
# for i in install/kubernetes/helm/istio-init/files/crd*yaml; do kubectl apply -f $i; done
# kubectl apply -f install/kubernetes/istio-demo.yaml
```
