### ISSUE TITLE
EnvoyFilter applies only to Sidecar even though context is Any

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17414]
Apply this EnvoyFilter:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: h2-control
spec:
  configPatches:
  - applyTo: CLUSTER
    patch:
      operation: MERGE
      value:
        http2_protocol_options:
          initial_stream_window_size: 65536
          initial_connection_window_size: 65536
  - applyTo: NETWORK_FILTER
    match:
      context: ANY
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager"
          http2_protocol_options:
            initial_stream_window_size: 65536
            initial_connection_window_size: 65536
```

Config dump for ingressgateway shows nothing, sidecar shows applied correctly
