### ISSUE TITLE
SIGSEGV in ServiceRoleBindingAnalyzer

### ISSUE THREAD

**Issue by esnible** [istio/istio#17449]
To reproduce use Istio 1.3.1 release

```
cat <<EOF > backtrace.yaml
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: bind-mongodb-viewer
  namespace: default
spec:
  subjects:
  - user: "cluster.local/ns/default/sa/bookinfo-ratings-v2"
EOF
istioctl x analyze backtrace.yaml
```

The backtrace:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x24e8333]

goroutine 35 [running]:
istio.io/istio/galley/pkg/config/analysis/analyzers/auth.(*ServiceRoleBindingAnalyzer).analyzeRoleBinding(0x52b55a8, 0xc00002cbd0, 0x37423c0, 0xc00064c090)
	/workspace/go/src/istio.io/istio/galley/pkg/config/analysis/analyzers/auth/servicerolebindings.go:55 +0x83
istio.io/istio/galley/pkg/config/analysis/analyzers/auth.(*ServiceRoleBindingAnalyzer).Analyze.func1(0xc00002cbd0, 0xc000503110)
	/workspace/go/src/istio.io/istio/galley/pkg/config/analysis/analyzers/auth/servicerolebindings.go:46 +0x46
istio.io/istio/galley/pkg/config/collection.(*Instance).ForEach(0xc000644600, 0xc000290fa0)
	/workspace/go/src/istio.io/istio/galley/pkg/config/collection/instance.go:69 +0xe1
istio.io/istio/galley/pkg/config/processing/snapshotter.(*Snapshot).ForEach(0xc00058c048, 0x32ef4ed, 0x27, 0xc000290fa0)
	/workspace/go/src/istio.io/istio/galley/pkg/config/processing/snapshotter/snapshot.go:87 +0x72
...
```
