### ISSUE TITLE
Can't connect to MYSQL when mtls is enabled

### ISSUE THREAD

**Issue by venomwaqar** [istio/istio#17457]
**Bug description**

I am not being able to connect with MYSQL using MTLS enabled from another application (which is a simple CRUD application). When I disable the MTLS for MYSQL I can successfully connect with it.
Following are the configuration I am using.

```
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: mysql-mtls-authni
  namespace: ns-restriction-demo-2
spec:
  targets:
  - name: db-demo-2   # The name iof *your* K8s Service
  peers:
  - mtls:
      mode: PERMISSIVE
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mysql-mtls-dr
  namespace: ns-restriction-demo-2
spec:
  host: db-demo-2    # The name of *your* K8s Service
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```

```
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: enable-mtls
  namespace: ns-restriction-demo-1
spec:
  host: node-demo-1
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```

**Expected behavior**
When MTLS is enabled on both the application, it should be able to connect easily.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio: 1.1.10
Kubernetes: 1.13.6

Kindly help me understand what I am doing wrong or where should I look for the logs?
P.S
The reason I need to enable MTLS is because I have to enable authorization on MYSQL service and authenticate the request using serviceAccount. and the problem you can use serviceAccount in authorization only when the request is MTLS.

**Comment by howardjohn** [comment]
See https://istio.io/faq/security/#mysql-with-mtls

This should be fixed in 1.3, I would encourage you to try that out

**Comment by venomwaqar** [comment]
> See https://istio.io/faq/security/#mysql-with-mtls
> 
> This should be fixed in 1.3, I would encourage you to try that out

@howardjohn I have tried that. If you see my description, you will know that I have used the same configurations

**Comment by howardjohn** [comment]
It looks like you only have part of it, you will need to apply this as well:
```
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: mysql-mtls-authn
spec:
  targets:
  - name: YOUR-MYSQL-SERVICE     # The name of *your* K8s Service
  peers:
  - mtls:
      mode: STRICT
```
?

**Comment by venomwaqar** [comment]
> It looks like you only have part of it, you will need to apply this as well:
> 
> ```
> apiVersion: "authentication.istio.io/v1alpha1"
> kind: "Policy"
> metadata:
>   name: mysql-mtls-authn
> spec:
>   targets:
>   - name: YOUR-MYSQL-SERVICE     # The name of *your* K8s Service
>   peers:
>   - mtls:
>       mode: STRICT
> ```
> 
> ?

@howardjohn  Its right there in the description

```
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: mysql-mtls-authni
  namespace: ns-restriction-demo-2
spec:
  targets:
  - name: db-demo-2   # The name iof *your* K8s Service
  peers:
  - mtls:
      mode: PERMISSIVE
```
The only change is mode = PERMISSIVE and I think permissive will allow both mtls and plain text connection. Doesn't it?

**Comment by howardjohn** [comment]
> This is because of PERMISSIVE mode which is enabled in istio-demo.yaml by default, does not work with MySQL

You cannot use permissive with MySql. I think you need to use strict for mysql or upgrade to 1.3

**Comment by venomwaqar** [comment]
@howardjohn Okay I'll try it. Thanks

**Comment by venomwaqar** [comment]
@howardjohn I have used istio version 1.3.0 and the following configurations and still the I am not being able to connect to the SQL

```
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: mysql-mtls-authn
  namespace: ns-restriction-demo-2
spec:
  targets:
  - name: db-demo-2     # The name of *your* K8s Service
  peers:
  - mtls:
      mode: STRICT
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mysql-mtls-dr
  namespace: ns-restriction-demo-2
spec:
  host: db-demo-2     # The name of *your* K8s Service
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: mysql-mtls-authn
  namespace: ns-restriction-demo-1
spec:
  targets:
  - name: node-demo-1     # The name of *your* K8s Service
  peers:
  - mtls:
      mode: STRICT
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mysql-mtls-dr
  namespace: ns-restriction-demo-1
spec:
  host: node-demo-1     # The name of *your* K8s Service
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

```

```
[root@ip-172-31-63-184 centos]# istioctl authn tls-check node-demo-1-65b9477c9-n9mqf.ns-restriction-demo-1 db-demo-2.ns-restriction-demo-2.svc.cluster.local
HOST:PORT                                                  STATUS     SERVER     CLIENT     AUTHN POLICY                               DESTINATION RULE
db-demo-2.ns-restriction-demo-2.svc.cluster.local:3306     OK         mTLS       mTLS       mysql-mtls-authn/ns-restriction-demo-2     mysql-mtls-dr/ns-restriction-demo-2
```
