### ISSUE TITLE
SSL with certmanager is not working

### ISSUE THREAD

**Issue by rjshrjndrn** [istio/istio#17482]
**Bug description**
1. Created certificate with certmanager
2. Created gateway to point to port 443
2. but pilot log, gives this error, although I can see the secret has certificate.
```
istio-pilot-5485b8448b-8c7bb discovery  * gateway listener 0.0.0.0_443 validation failed: invalid Listener.FilterChains[0]: embedded message failed validation | caused by: invalid FilterChain.TlsContext: embedded message failed validation | caused by: invalid DownstreamTlsContext.CommonTlsContext: embedded message failed validation | caused by: invalid CommonTlsContext.TlsCertificates[0]: embedded message failed validation | caused by: invalid TlsCertificate.CertificateChain: embedded message failed validation | caused by: invalid DataSource.Filename: value length must be at least 1 bytes
istio-pilot-5485b8448b-8c7bb discovery
istio-pilot-5485b8448b-8c7bb discovery
istio-pilot-5485b8448b-8c7bb discovery gc 116 @8511.341s 0%: 0.050+10+3.1 ms clock, 0.20+13/10/0+12 ms cpu, 17->19->12 MB, 18 MB goal, 4 P
istio-pilot-5485b8448b-8c7bb discovery gc 117 @8511.381s 0%: 5.6+26+0.005 ms clock, 22+2.9/15/0+0.021 ms cpu, 22->27->15 MB, 25 MB goal, 4 P
istio-pilot-5485b8448b-8c7bb discovery 2019-09-30T04:19:49.130654Z      warn    buildGatewayListeners: found 0 services on port 443: []
istio-pilot-5485b8448b-8c7bb discovery 2019-09-30T04:19:49.130663Z      error   rbac    nil service instance
istio-pilot-5485b8448b-8c7bb discovery 2019-09-30T04:19:49.131317Z      warn    Gateway missing for route https.443.httpss.public-gateway.dev. This is normal if gateway was recently deleted. Have map[http.80:[port:<number:80 protocol:"HTTP" name:"http" > hosts:"dev.centralindia.cloudapp.azure.com" ] https.443.https.public-gateway.dev:[port:<number:443 protocol:"HTTPS" name:"https" > hosts:"dev.centralindia.cloudapp.azure.com" tls:<mode:SIMPLE credential_name:"ingress-cert-new" > ]]
istio-pilot-5485b8448b-8c7bb discovery 2019-09-30T04:19:49.152020Z      warn    Gateway missing for route https.443.httpss.public-gateway.dev. This is normal if gateway was recently deleted. Have map[http.80:[port:<number:80 protocol:"HTTP" name:"http" > hosts:"dev.centralindia.cloudapp.azure.com" ] https.443.https.public-gateway.dev:[port:<number:443 protocol:"HTTPS" name:"https" > hosts:"dev.centralindia.cloudapp.azure.com" tls:<mode:SIMPLE credential_name:"ingress-cert-new" > ]]
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ x ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
website should be up with https.

**Steps to reproduce the bug**
https://istio.io/docs/tasks/traffic-management/ingress/ingress-certmgr/

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```
❮ istioctl version
client version: 1.2.4
citadel version: 1.3.0
galley version: 1.3.0
ingressgateway version: 1.3.0
nodeagent version:
nodeagent version:
nodeagent version:
pilot version: 1.3.0
policy version: 1.3.0
sidecar-injector version: 1.3.0
telemetry version: 1.3.0
```
```
➜ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5", GitCommit:"0e9fcb426b100a2aea5ed5c25b3d8cfbb01a8acf", GitTreeState:"clean", BuildDate:"2019-08-05T09:13:08Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**
`❮ helm install --name istio -f ./istio/values1-3.yaml istio.io/istio --set gateways.istio-ingressgateway.sds.enabled=true --namespace istio-system
`
```
gateways:
  enabled: true
sidecarInjectorWebhook:
  enabled: true
galley:
  enabled: true
mixer:
  policy:
    enabled: true
  telemetry:
    enabled: true
pilot:
  enabled: true
security:
  enabled: true
nodeagent:
  enabled: true
  image: node-agent-k8s
  env:
    CA_PROVIDER: "Citadel"
    CA_ADDR: "istio-citadel:8060"
    VALID_TOKEN: true
grafana:
  enabled: true
prometheus:
  enabled: true
tracing:
  enabled: true
kiali:
  enabled: true
certmanager:
  enabled: true
  email: test@test.com
istio_cni:
  enabled: false
istiocoredns:
  enabled: false
global:
  hub: docker.io/istio
  tag: 1.3.0
  logging:
    level: "default:info"
  monitoringPort: 15014
  k8sIngress:
    enabled: false
    gatewayName: ingressgateway
    enableHttps: false
  proxy:
    init:
      resources:
        limits:
          cpu: 100m
          memory: 50Mi
        requests:
          cpu: 10m
          memory: 10Mi
    image: proxyv2
    clusterDomain: "cluster.local"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 1024Mi
    concurrency: 2
    accessLogFile: "/dev/stdout"
    accessLogFormat: ""
    accessLogEncoding: TEXT
    envoyAccessLogService:
      enabled: false
      host: # example: accesslog-service.istio-system
      port: # example: 15000
      tlsSettings:
        mode: DISABLE # DISABLE, SIMPLE, MUTUAL, ISTIO_MUTUAL
        clientCertificate: # example: /etc/istio/als/cert-chain.pem
        privateKey: # example: /etc/istio/als/key.pem
        caCertificates: # example: /etc/istio/als/root-cert.pem
        sni: # example: als.somedomain
        subjectAltNames: []
      tcpKeepalive:
        probes: 3
        time: 10s
        interval: 10s
    logLevel: ""
    componentLogLevel: ""
    dnsRefreshRate: 300s
    protocolDetectionTimeout: 100ms
    privileged: false
    enableCoreDump: false
    enableCoreDumpImage: ubuntu:xenial
    statusPort: 15020
    readinessInitialDelaySeconds: 1
    readinessPeriodSeconds: 2
    readinessFailureThreshold: 30
    includeIPRanges: "*"
    excludeIPRanges: ""
    excludeOutboundPorts: ""
    kubevirtInterfaces: ""
    includeInboundPorts: "*"
    excludeInboundPorts: ""
    autoInject: enabled
    envoyStatsd:
      enabled: false
      host: # example: statsd-svc.istio-system
      port: # example: 9125
    envoyMetricsService:
      enabled: false
      host: # example: metrics-service.istio-system
      port: # example: 15000
    tracer: "zipkin"
  proxy_init:
    image: proxy_init
  imagePullPolicy: IfNotPresent
  controlPlaneSecurityEnabled: false
  disablePolicyChecks: true
  policyCheckFailOpen: false
  enableTracing: true
  tracer:
    lightstep:
      address: ""                # example: lightstep-satellite:443
      accessToken: ""            # example: abcdefg1234567
      secure: true               # example: true|false
      cacertPath: ""             # example: /etc/lightstep/cacert.pem
    zipkin:
      address: ""
    datadog:
      address: "$(HOST_IP):8126"
  mtls:
    enabled: false
  imagePullSecrets: []
  arch:
    amd64: 2
    s390x: 2
    ppc64le: 2
  oneNamespace: false
  defaultNodeSelector: {}
  defaultTolerations: []
  configValidation: true
  meshExpansion:
    enabled: false
    useILB: false

  multiCluster:
    enabled: false
    clusterName: ""
  defaultResources:
    requests:
      cpu: 10m
  defaultPodDisruptionBudget:
    enabled: true
  priorityClassName: ""
  useMCP: true
  trustDomain: ""
  meshID: ""
  outboundTrafficPolicy:
    mode: ALLOW_ANY
  sds:
    enabled: false
    udsPath: ""
    token:
      aud: istio-ca
  meshNetworks: {}
  localityLbSetting:
    enabled: true
  enableHelmTest: false
```

**Environment where bug was observed (cloud vendor, OS, etc)**
Azure AKS
Ubuntu 16.04 VM
Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
