### ISSUE TITLE
ServiceAssociation Analyzer

### ISSUE THREAD

**Issue by sushicw** [istio/istio#17503]
Based on istio-vet implementation: https://github.com/aspenmesh/istio-vet/blob/master/pkg/vetter/serviceassociation/README.md

This should probably be a WARN level message.

**Comment by xeviknal** [comment]
hey @sushicw ! Id like to take this one :) I can't do assignments, could you please do it for me?

**Comment by sushicw** [comment]
@xeviknal Done.

Are you planning to have this look at pods, or deployments? The trouble with looking at pods is that pods generally only exist at runtime. This is fine for analyzing a live cluster, but means we can't do effective analysis on static files. Users probably have YAMLs defining their deployments, but not pods. 

Looking at deployments instead of pods ends up being a bit more complex, but hopefully that shared complexity can be abstracted out if it hasn't already (there are other analyzers that need to do the same kind of thing).

**Comment by xeviknal** [comment]
Then is the idea here to detect if there is one deployment belonging to two different services?
Belonging: Services selector labels match with 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-v1
  labels:
    app: details
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details
      version: v1
  template:
    metadata:
      labels:
        app: details
        version: v1
    spec:
      serviceAccountName: bookinfo-details
      containers:
        - name: details
          image: docker.io/istio/examples-bookinfo-details-v1:1.15.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: details
  labels:
    app: details
    service: details
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: details
---
apiVersion: v1
kind: Service
metadata:
  name: details-copy
  labels:
    app: details
    service: details
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: details
```

The example below should raise a message saying that there are two services pointing to same deployment.

Perhaps I am missing something. That could be more than possible, haha.
