### ISSUE TITLE
gateway omitting listener "0.0.0.0_443" due to: must have more than 0 chains in listener

### ISSUE THREAD

**Issue by nixgadget** [istio/istio#17517]
**Bug description**
I keep seeing the following error on pilot for egress endpoints. I have given the configuration below for Service Entry, Destination Rules, Gateway and Virtual Service.

```
info	1 error occurred:
	* gateway omitting listener "0.0.0.0_443" due to: must have more than 0 chains in listener: &v2.Listener{Name:"0.0.0.0_443", Address:(*core.Address)(0xc003487ad0), FilterChains:[]*listener.FilterChain{}, UseOriginalDst:nil, PerConnectionBufferLimitBytes:nil, Metadata:(*core.Metadata)(nil), DeprecatedV1:(*v2.Listener_DeprecatedV1)(nil), DrainType:0, ListenerFilters:[]*listener.ListenerFilter(nil), ListenerFiltersTimeout:(*time.Duration)(0xc003a74100), ContinueOnListenerFiltersTimeout:true, Transparent:nil, Freebind:nil, SocketOptions:[]*core.SocketOption(nil), TcpFastOpenQueueLength:nil, TrafficDirection:2, XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}
error	buildGatewayListeners: Have zero listeners
...
2019-09-30T20:56:12.043165Z	info	ads	Push Status: {
    "ProxyStatus": {
        "pilot_conflict_outbound_listener_tcp_over_current_tcp": {
            "0.0.0.0:443": {
                "proxy": "sleep-5bbf6b4f77-6b2xq.apps",
                "message": "Listener=0.0.0.0:443 AcceptedTCP=edition.cnn.com RejectedTCP=fcm.googleapis.com TCPServices=1"
            }
        },
        "pilot_destrule_subsets": {
            "istio-egressgateway.control.svc.cluster.local": {
                "message": "Duplicate subset cnn found while merging destination rules for istio-egressgateway.control.svc.cluster.local"
            }
        },
        "pilot_duplicate_envoy_clusters": {
            "outbound|15443|cnn|istio-egressgateway.control.svc.cluster.local": {
                "proxy": "sleep-5bbf6b4f77-6b2xq.apps",
                "message": "Duplicate cluster outbound|15443|cnn|istio-egressgateway.control.svc.cluster.local found while pushing CDS"
            },
            "outbound|443|cnn|istio-egressgateway.control.svc.cluster.local": {
                "proxy": "sleep-5bbf6b4f77-6b2xq.apps",
                "message": "Duplicate cluster outbound|443|cnn|istio-egressgateway.control.svc.cluster.local found while pushing CDS"
            },
            "outbound|80|cnn|istio-egressgateway.control.svc.cluster.local": {
                "proxy": "sleep-5bbf6b4f77-6b2xq.apps",
                "message": "Duplicate cluster outbound|80|cnn|istio-egressgateway.control.svc.cluster.local found while pushing CDS"
            }
        },
        "pilot_eds_no_instances": {
            "outbound_.26379_._.rc-redis-sentinel.storage.svc.cluster.local": {},
            "outbound|26379||rc-redis-sentinel.storage.svc.cluster.local": {}
        }
    }
}
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
To have no issues with Egress and have 0 conflicts with 443 listener.
And this is what I'm observing despite of this error above but would like to understand why this is being thrown.

**Steps to reproduce the bug**
Use the following configuration,
```
kubectl apply -n apps -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cnn
spec:
  hosts:
  - edition.cnn.com
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: fcm
spec:
  hosts:
  - fcm.googleapis.com
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
EOF
```

```
kubectl apply -n apps -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway-cnn
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: TLS
    hosts:
    - edition.cnn.com
    tls:
      mode: MUTUAL
      serverCertificate: /etc/certs/cert-chain.pem
      privateKey: /etc/certs/key.pem
      caCertificates: /etc/certs/root-cert.pem
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-cnn
spec:
  host: istio-egressgateway.control.svc.cluster.local
  subsets:
  - name: cnn
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: ISTIO_MUTUAL
          sni: edition.cnn.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-cnn-through-egress-gateway
spec:
  hosts:
  - edition.cnn.com
  gateways:
  - mesh
  - istio-egressgateway-cnn
  tls:
  - match:
    - gateways:
      - mesh
      port: 443
      sni_hosts:
      - edition.cnn.com
    route:
    - destination:
        host: istio-egressgateway.control.svc.cluster.local
        subset: cnn
        port:
          number: 443
  tcp:
  - match:
    - gateways:
      - istio-egressgateway-cnn
      port: 443
    route:
    - destination:
        host: edition.cnn.com
        port:
          number: 443
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway-fcm
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: TLS
    hosts:
    - fcm.googleapis.com
    tls:
      mode: MUTUAL
      serverCertificate: /etc/certs/cert-chain.pem
      privateKey: /etc/certs/key.pem
      caCertificates: /etc/certs/root-cert.pem
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-fcm
spec:
  host: istio-egressgateway.control.svc.cluster.local
  subsets:
  - name: fcm
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: ISTIO_MUTUAL
          sni: fcm.googleapis.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-fcm-through-egress-gateway
spec:
  hosts:
  - fcm.googleapis.com
  gateways:
  - mesh
  - istio-egressgateway-fcm
  tls:
  - match:
    - gateways:
      - mesh
      port: 443
      sni_hosts:
      - fcm.googleapis.com
    route:
    - destination:
        host: istio-egressgateway.control.svc.cluster.local
        subset: fcm
        port:
          number: 443
  tcp:
  - match:
    - gateways:
      - istio-egressgateway-fcm
      port: 443
    route:
    - destination:
        host: fcm.googleapis.com
        port:
          number: 443
      weight: 100
---
EOF
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio: `1.3.1`
K8:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-19T14:00:14Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-21T22:32:40Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Using Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS
