### ISSUE TITLE
outlierDetection not working correctly for external services 

### ISSUE THREAD

**Issue by Janesee3** [istio/istio#17521]
**Bug description**
`outlierDetection` is not working correctly for mesh external services. Specifically, when a pod makes a `https` call to an external service, the outlierDetection never kicks in.

**Affected product area (please put an X in all that apply)**
[X] Networking

**Expected behavior**

**Steps to reproduce the bug**

**Note:** We are using a service that returns us customised http codes called `httpstat.us` so that we can avoid setting up `faultInjection`

1) First, create a ServiceEntry and DestinationRule config as follow:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpstat
  namespace: istio-system
spec:
  hosts:
  - httpstat.us
  ports:
  - name: https
    number: 443
    protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: httpstat
  namespace: istio-system
spec:
  host: httpstat.us
  trafficPolicy:
    outlierDetection:
      baseEjectionTime: 10s
      consecutiveErrors: 3
      interval: 5s
      maxEjectionPercent: 100
```

2) Spin up a pod that has curl 
```
kubectl run curl -it --rm --generator=run-pod/v1 --image=radial/busyboxplus:curl
``` 
3) Make curl commands to attempt to trigger the outlierDetection behaviour:
```
curl https://httpstat.us/502
```
4) Even after many calls, we still receive `502`
5) Proxy status also show that outlierDetection is not kicking in:

```bash
$ k exec -it curl -- curl -s http://localhost:15000/clusters | grep "httpstat"

outbound|80||httpstat.us::outlier::success_rate_average::-1
outbound|80||httpstat.us::outlier::success_rate_ejection_threshold::-1
outbound|80||httpstat.us::outlier::local_origin_success_rate_average::-1
outbound|80||httpstat.us::outlier::local_origin_success_rate_ejection_threshold::-1
outbound|80||httpstat.us::default_priority::max_connections::1024
outbound|80||httpstat.us::default_priority::max_pending_requests::1024
outbound|80||httpstat.us::default_priority::max_requests::1024
outbound|80||httpstat.us::default_priority::max_retries::1024
outbound|80||httpstat.us::high_priority::max_connections::1024
outbound|80||httpstat.us::high_priority::max_pending_requests::1024
outbound|80||httpstat.us::high_priority::max_requests::1024
outbound|80||httpstat.us::high_priority::max_retries::3
...
outbound|80||httpstat.us::23.99.0.12:80::hostname::httpstat.us
outbound|80||httpstat.us::23.99.0.12:80::health_flags::healthy
outbound|80||httpstat.us::23.99.0.12:80::weight::1
...
outbound|80||httpstat.us::23.99.0.12:80::success_rate::-1
outbound|80||httpstat.us::23.99.0.12:80::local_origin_success_rate::-1
```

Same goes for this command:
```
$ istioctl proxy-config endpoints curl | grep httpstat

ENDPOINT                STATUS      OUTLIER CHECK     CLUSTER
23.99.0.12:443         HEALTHY      OK              outbound|443||httpstat.us
```

However, the proxy-config dump shows that outlierDetection config is present:
```
$ istioctl proxy-config cluster curl --fqdn "httpstat.us" -ojson

[
    {
        "name": "outbound|443||httpstat.us",
        "type": "STRICT_DNS",
        "connectTimeout": "10s",
        "loadAssignment": {
            "clusterName": "outbound|443||httpstat.us",
            "endpoints": [
                {
                    "lbEndpoints": [
                        {
                            "endpoint": {
                                "address": {
                                    "socketAddress": {
                                        "address": "httpstat.us",
                                        "portValue": 443
                                    }
                                }
                            },
                            "loadBalancingWeight": 1
                        }
                    ],
                    "loadBalancingWeight": 1
                }
            ]
        },
        "circuitBreakers": {
            "thresholds": [
                {
                    "maxRetries": 1024
                }
            ]
        },
        "dnsRefreshRate": "300s",
        "respectDnsTtl": true,
        "dnsLookupFamily": "V4_ONLY",
        "outlierDetection": {
            "interval": "5s",
            "baseEjectionTime": "10s",
            "maxEjectionPercent": 100,
            "enforcingConsecutive5xx": 0,
            "consecutiveGatewayFailure": 3,
            "enforcingConsecutiveGatewayFailure": 100
        },
        "commonLbConfig": {
            "healthyPanicThreshold": {},
            "localityWeightedLbConfig": {}
        },
        "metadata": {
            "filterMetadata": {
                "istio": {
                    "config": "/apis/networking/v1alpha3/namespaces/default/destination-rule/httpstat"
                }
            }
        }
    }
]
```

**Version**
Running on Istio 1.3
EKS, Kubernetes Version: v1.13.10-eks-5ac0f1
