### ISSUE TITLE
consistentHash is not working if traffic to pod is tls

### ISSUE THREAD

**Issue by jaesquivel** [istio/istio#17557]
consistentHash is not working if traffic to pod is tls, same configuration works OK using http

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

This request should always hit the same pod, but it only does if I use http and not htts to connect from envoy to the pod.
curl -vk -H 'X-User: Peter' -H 'X-Workload-Selector: sticky' https://172.16.3.205:31390/ 

[sticky.zip](https://github.com/istio/istio/files/3681813/sticky.zip)

Use attached configuration to reproduce, one uses tls and the other one does not.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

istioctl version --remote
client version: 1.3.0
control plane version: 1.3.0

kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
helm template install/kubernetes/helm/istio --name istio --namespace istio-system | kubectl apply -f -

**Environment where bug was observed (cloud vendor, OS, etc)**
Local virtual machines running CentOS 7

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by argeualcantara** [comment]
I'm experiencing the same issue. Is there any update on this???

**Comment by argeualcantara** [comment]
@jaesquivel  I have some updates.
I applied the following yaml:
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  labels:
    name: https-example
  name: originate-tls-and-stickiness
spec:
  host: https-svc
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 8443
      tls:
        mode: SIMPLE
      loadBalancer:
        consistentHash:
          httpHeaderName: client-id
```

applying the consistentHash in portLevelSettings the configuration worked.
I'm terminating the TLS on the gateway, but I'm adding this tls origination rule, which also is applying the stickiness now.
