### ISSUE TITLE
istioctl authn shows conflict when there isn't

### ISSUE THREAD

**Issue by cacedo** [istio/istio#17554]
**Bug description**
I have two deployments with labels `version: v1` and `version: v2` under the same kubernetes service. When creating a `virtualService` and `destinationRule` to weight traffic, if I specify TLS settings per subset (using the same settings), `istioctl authn tls-check` will show a conflict, but it works.  

**Affected product area (please put an X in all that apply)**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
`istioctl` should show `OK` instead

**Steps to reproduce the bug**
Assuming you have two deployments with pod labels `version: v1` and `version: v2` and a service selecting by those two labels. Create a virtualService with this spec:
```
spec:
  hosts:
  - api-api.loadtesting.svc.cluster.local
  http:
  - route:
    - destination:
        host: api-api.loadtesting.svc.cluster.local
        subset: v1
      weight: 1
    - destination:
        host: api-api.loadtesting.svc.cluster.local
        subset: v2
      weight: 99
```
And a `destinationRule` like:
```
spec:
  host: api-api
  subsets:
  - labels:
      version: v1
    name: v1
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
  - labels:
      version: v2
    name: v2
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
```
`istioctl authn tls-check` shows `CONFLICT` (`mTLS HTTP`) but connection works
Instead, setting `trafficPolicy` globally (at spec level) will show `OK`
Is just confusing to see a conflict when it works. 

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istioctl:
```
client version: 1.3.0-rc.1
control plane version: 1.2.2
```
kubectl:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.7", GitCommit:"65ecaf0671341311ce6aea0edab46ee69f65d59e", GitTreeState:"clean", BuildDate:"2019-01-24T19:32:00Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Using Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
cloud: AWS
OS: Linux (Debian)
