### ISSUE TITLE
Analyzer for more than one gateway with the same host+port combination

### ISSUE THREAD

**Issue by sushicw** [istio/istio#17560]
Kiali implementation: https://www.kiali.io/documentation/validations/#_more_than_one_gateway_for_the_same_host_port_combination

**Comment by selmanj** [comment]
Ok, so I think the analyzer as implemented by Kiali might be overly restrictive. The example given shows two gateways bound to the same host `"*"`. Something like:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: webserver
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bookinfo
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
```
While this looks like it might be an error, it's not problematic in practice. I can define virtual services and bind them to each gateway, and they continue to work. I believe this is because pilot merges gateways into a single representation before emitting routes (some hint of this is described here: https://istio.io/docs/ops/traffic-management/deploy-guidelines/#multiple-virtual-services-and-destination-rules-for-the-same-host).

I'm not an expert in pilot but I believe this code shows how the merging is done, and redundant or overlapping gateways shouldn't be a problem: https://github.com/istio/istio/blob/36314f4231d1dd69c6374e44be55b49916cf0b80/pilot/pkg/model/gateway.go#L70
