### ISSUE TITLE
Strip internal mesh-machinery headers when sending requests/responses out of mesh

### ISSUE THREAD

**Issue by chadlwilson** [istio/istio#17635]
**Describe the feature request**

In a couple of situations Istio's default configuration exposes internal mesh-machinery headers outside of the mesh; either to callers or callees.

_Ingress Gateway_
* **Response** header `x-envoy-upstream-service-time`

_Egress Gateway_
* **Request** headers such as `x-forwarded-client-cert`, `x-forwarded-proto`, other `x-forwarded-*` headers, `x-envoy-decorator-operation` (!!)

There may be others.

Since these may expose internal detail of one's mesh, and requests may be made outside the mesh even to a third party organization, it would be preferable for Istio to ship with a "secure-by-default" or "private-by-default" configuration of the gateways, where such internal headers are stripped; or not sent out.

**Describe alternatives you've considered**

It is possible to configure `VirtualService`s to manually strip with [HeaderOperations](https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#Headers-HeaderOperations); but I'm not aware of a convenient way to apply this universally; and we've found it leads to a lot of configuration cruft - and inevitable mistakes/forgetting to do it.

_Ingress_
```yaml
kind: VirtualService
# ...
spec:
  # blah
  http:
  - match:
    # uri, route etc
    headers:
      response:
        remove:
        - x-envoy-upstream-service-time
```

_Egress_
```yaml
kind: VirtualService
# ...
spec:
  # blah
  http:
  - match:
    # uri, route etc
    headers:
      request:
        remove:
        - x-forwarded-client-cert
        # etc
```

It may also be possibly to use an `EnvoyFilter` on the egress gateway to change the config to `useRemoteAddress: false` (suggested by @rshriram ) however I have not yet attempted this.

**Affected product area (please put an X in all that apply)**

[X] Docs
[X] Networking
[X] Policies and Telemetry
[X] Security

**Additional context**

If stripping headers; there may be some considerations to ensure that Istio/Envoy doesn't blindly strip headers that have actually been set by application code or customer-supplied (especially things like `x-forwarded-*` - I can see this being legitimate use from a customer environment in some cases). Alternatively, would there be a need to provide a way to disable the stripping of certain headers? I'm not sure if Istio/Envoy has ability to somehow track which headers it specifically added.

**Comment by chadlwilson** [comment]
I just noticed that in our `ServiceEntry` configurations for egress we have neglected to designate them as `location: MESH_EXTERNAL`. If this affects the way headers are set/propagated (which seems plausible) this may be the reason the request headers are there. We will re-test to verify.

**Comment by dontreboot** [comment]
I have the same concern. I'd like to how to hide `server`, `x-envoy-upstream-service-time` and other internal info from response headers.

**Comment by sneko** [comment]
@chadlwilson by setting MESH_EXTERNAL, did it removes `x-forwarded-client-cert` and so on?

**Comment by chadlwilson** [comment]
@sneko unfortunately I can't recall now. Oops. Will need to check traffic dumps again as our logging doesn't capture all headers sent.

**Comment by chadlwilson** [comment]
I had an occasion to look at this again with Istio `1.4.8` in the last couple of days when looking at why some traffic was being dropped by an external service's Firewall/WAF. I was theorising max header sizes were an issue and noted that even with a `MESH_EXTERNAL` `ServiceEntry` doing direct TLS origination from sidecar (no `egressgateway`) it was still including
```
x-envoy-decorator-operation
x-istio-attributes
x-forwarded-proto
x-request-id
b3 tracing headers
```

That is flow like

```
App -> (HTTP) sidecar -> (HTTPS) external service
```

When I originally raised this ticket, we were using `egressgateway` to do TLS origination, and MTLS between sidecar -> egressgateway which is probably why `x-forwarded-client-cert` etc were included; but I don't seem them now.

```
App -> (HTTP) sidecar -> (HTTPS mTLS) egressgateway -> (HTTPS) external service
```

I can see a possible use case for the request ID and tracing headers to be able to be retained to support distributed tracing/debugging with external services, however the internal headers such as `x-istio-attributes`, client certs etc can leak information internal to your environment. 

In the meantime I applied the `VirtualService` header stripping workaround suggested above.

**Comment by nrjpoddar** [comment]
I think this is a reasonable and useful feature to add.

**Comment by Jeiwan** [comment]
Here's how `EnvoyFilter` can be used to remove response headers:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: response-headers-filter
  namespace: istio-system
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.router"
    patch:
      operation: ADD
      value:
        name: envoy.lua
        config:
          inlineCode: |
            function envoy_on_response(response_handle)
              response_handle:headers():remove("x-envoy-upstream-service-time")
              response_handle:headers():remove("x-envoy-overloaded")
              response_handle:headers():remove("x-powered-by")
            end
```

**Comment by stewartbutler** [comment]
@howardjohn You set this as a P0 before stale bot killed it, and I don't think it's been resolved. Should we revive it?

**Comment by howardjohn** [comment]
Yes, thanks

**Comment by bianpengyuan** [comment]
I believe we no longer set `x-istio-attributes` in 1.8 since mixer filter has been removed. However we might still be leaking some metadata exchange header. cc @kyessenov

Moved this to 1.9 as there is unlikely going to be action in 1.8. Mark this as P1.

**Comment by chadlwilson** [comment]
As far as I can see as of `1.9` (or quite likely earlier, as haven't re-checked this for a long time), `x-envoy-decorator-operation`, `x-forwarded-proto` and `x-istio-attributes` no longer go out on sidecar egress for `MESH_EXTERNAL` services, so appears these have been cleaned up at some point or another?

`x-envoy-upstream-service-time` is still going out the ingress though, so `VirtualService` as a workaround seems still valid there.

**Comment by rocketspacer** [comment]
We need to remove the response header `x-envoy-decorator-operation` as well
From https://github.com/envoyproxy/envoy/issues/9778 I think this can be done with

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: remove-bad-response-headers
spec:
  configPatches:
  - applyTo: ROUTE_CONFIGURATION
    match:
      context: GATEWAY
    patch:
      operation: MERGE
      value:
        decorator:
          propagate: false
```
 
I just want to confirm if we have this feature merged onto the Istio Proxy
I tested on Istio 1.9.4 and `decorator.propagate` seems to be an invalid attribute.

**Comment by chadlwilson** [comment]
I'm confused - isn't `x-envoy-decorator-operation` a request header going to an upstream, not a response header? That header was specifically mentioned in the original post.

Are you sure you see`x-envoy-decorator-operation` in traffic going **out** of the mesh? I empirically checked against outbound sidecar traffic and don't see it in requests any longer. Never saw it in responses.

**Comment by mathieu-benoit** [comment]
I'm currently using Istio `1.10.2` (via GCP ASM) and I'm still seeing those 3 entries in the response header:
```
server: istio-envoy
x-envoy-decorator-operation: mycontainer.mynamespace.svc.cluster.local:8080/*
x-envoy-upstream-service-time: 0
```
Not sure I got exactly what to do to get rid off of them, but I guess I need to go through that thread again to see what I should do.

**Comment by chadlwilson** [comment]
@mathieu-benoit Assuming you are concerned about them going back out of your ingress, adding `response` directives with `headers` manipulation to the `VirtualService`s attached to your `Gateway`s is the least brittle way (IMO `EnvoyFilter`s should be used sparingly and they generally concern me as I never feel I know how stable many APIs are). 

i.e the approach in my OP still works: https://github.com/istio/istio/issues/17635#issue-502981828

However you do need to do it for every route, which has a lot of rinse+and+repeat so is possibly why some would prefer to apply a rule to all traffic going out of any gateway via `EnvoyFilter`s as in https://github.com/istio/istio/issues/17635#issuecomment-648543396

**Comment by mathieu-benoit** [comment]
Thanks for clarifying @chadlwilson, that helps. And yes I'm worrying about the `x-envoy-decorator-operation` field because it's giving internal in-cluster info for potential hackers.

My scenario is a simple web app (`nginx`) exposed via https load balancer via `Ingress`. But I don't have any `IngressGateway` in there. I just have the envoy/Istio side-car injected.

**Comment by chadlwilson** [comment]
Are you using Istio as a Kubernetes `Ingress` controller vis it's ingress class? Or using some other controller?

I have never used Istio like that (Ingress is far too limited for the needs I have had) and have no idea how it works so probably can't really help much. I'd have thought that some magic still happens to route traffic vis the istio-ingressgateway Deployment though, in which case some kind of EnvoyFilter might work - albeit crossing through a lot of abstraction layers to do so.

**Comment by mathieu-benoit** [comment]
My `Ingress` is not Istio based (yet), simple GCLB/NEG, here are my [Kubernetes manifests](https://github.com/mathieu-benoit/my-kubernetes-deployments/tree/main/namespaces/myblog) for this specific application, JFYI.

**Comment by chadlwilson** [comment]
I see. Then that's presumably an L7 LB configured via Ingress. If that doesn't have the ability to strip or allow-list response headers, you'd need to apply something inside the sidecar proxy itself. All of the examples above deal with stripping at the istio ingress gateway so wouldn't work for your use case where the last Istio component to touch the traffic is a sidecar proxy. Would need a different kind of `EnvoyFilter`, assuming it's technically possible.

**Comment by mathieu-benoit** [comment]
Oh ok, gotcha, thanks!

**Comment by rockc2020** [comment]
I also want to add a scenario similar with @mathieu-benoit. In our k8s clusters, `kong` is used as ingress controller and Istio Proxy is running as a sidecar proxy. There are several headers we want to strip from the response:

- x-envoy-decorator-operation
- x-envoy-upstream-service-time
- x-kong-response-latency

Here are two `EnvoyFilter` (listed below) I tried and they both work for `x-envoy-upstream-service-time` and `x-kong-response-latency` but don't work for `x-envoy-decorator-operation`. I don't know if it is because `x-envoy-decorator-operation` is appended after all filters are done?

EnvoyFilter 1:
`
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: response-remove-headers
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          server_header_transformation: PASS_THROUGH
  - applyTo: ROUTE_CONFIGURATION
    patch:
      operation: MERGE
      value:
        response_headers_to_remove:
        - "x-envoy-decorator-operation"
        - "x-envoy-upstream-service-time"
        - "x-kong-response-latency"
`

EnvoyFilter 2:
`
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: response-remove-headers-filter
  namespace: istio-system
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.lua
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
          inlineCode: |
            function envoy_on_response(response_handle)
              response_handle:headers():remove("x-envoy-decorator-operation")
              response_handle:headers():remove("x-kong-response-latency")
              response_handle:headers():remove("x-envoy-upstream-service-time")
            end
`

**Comment by FreeZhang61** [comment]
> Here's how `EnvoyFilter` can be used to remove response headers:
> 
> ```yaml
> apiVersion: networking.istio.io/v1alpha3
> kind: EnvoyFilter
> metadata:
>   name: response-headers-filter
>   namespace: istio-system
> spec:
>   configPatches:
>   - applyTo: HTTP_FILTER
>     match:
>       context: GATEWAY
>       listener:
>         filterChain:
>           filter:
>             name: "envoy.http_connection_manager"
>             subFilter:
>               name: "envoy.router"
>     patch:
>       operation: ADD
>       value:
>         name: envoy.lua
>         config:
>           inlineCode: |
>             function envoy_on_response(response_handle)
>               response_handle:headers():remove("x-envoy-upstream-service-time")
>               response_handle:headers():remove("x-envoy-overloaded")
>               response_handle:headers():remove("x-powered-by")
>             end
> ```

It just delete header "x-envoy-upstream-service-time"

**Comment by FreeZhang61** [comment]
> I also want to add a scenario similar with @mathieu-benoit. In our k8s clusters, `kong` is used as ingress controller and Istio Proxy is running as a sidecar proxy. There are several headers we want to strip from the response:
> 
>     * x-envoy-decorator-operation
> 
>     * x-envoy-upstream-service-time
> 
>     * x-kong-response-latency
> 
> 
> Here are two `EnvoyFilter` (listed below) I tried and they both work for `x-envoy-upstream-service-time` and `x-kong-response-latency` but don't work for `x-envoy-decorator-operation`. I don't know if it is because `x-envoy-decorator-operation` is appended after all filters are done?
> 
> EnvoyFilter 1:
> 
> ```
> apiVersion: networking.istio.io/v1alpha3
> kind: EnvoyFilter
> metadata:
>   name: response-remove-headers
>   namespace: istio-system
> spec:
>   configPatches:
>   - applyTo: NETWORK_FILTER
>     match:
>       listener:
>         filterChain:
>           filter:
>             name: "envoy.filters.network.http_connection_manager"
>     patch:
>       operation: MERGE
>       value:
>         typed_config:
>           "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
>           server_header_transformation: PASS_THROUGH
>   - applyTo: ROUTE_CONFIGURATION
>     patch:
>       operation: MERGE
>       value:
>         response_headers_to_remove:
>         - "x-envoy-decorator-operation"
>         - "x-envoy-upstream-service-time"
>         - "x-kong-response-latency"
> ```
> 
> EnvoyFilter 2:
> 
> ```
> apiVersion: networking.istio.io/v1alpha3
> kind: EnvoyFilter
> metadata:
>   name: response-remove-headers-filter
>   namespace: istio-system
> spec:
>   configPatches:
>   - applyTo: HTTP_FILTER
>     match:
>       listener:
>         filterChain:
>           filter:
>             name: "envoy.filters.network.http_connection_manager"
>             subFilter:
>               name: "envoy.filters.http.router"
>     patch:
>       operation: INSERT_BEFORE
>       value:
>         name: envoy.lua
>         typed_config:
>           "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
>           inlineCode: |
>             function envoy_on_response(response_handle)
>               response_handle:headers():remove("x-envoy-decorator-operation")
>               response_handle:headers():remove("x-kong-response-latency")
>               response_handle:headers():remove("x-envoy-upstream-service-time")
>             end
> ```

I have same problem 😭

**Comment by lei-tang** [comment]
https://github.com/istio/istio/issues/35283 describes a concern over leaking sensitive information in headers X-Envoy-Peer-Metadata and X-Envoy-Peer-Metadata-Id. Based on the comment from @bianpengyuan, consolidate https://github.com/istio/istio/issues/35283 at this issue.

**Comment by felpasl** [comment]
same here, remain `x-envoy-decorator-operation` header in response, Iuse istio and a kong as ingress, all responses from kong has istio headers, I'm using aws ELB, https trafic ELB and http trafic to kong.

**Comment by Himenon** [comment]
I have done exactly the same procedure as [this](https://github.com/istio/istio/issues/17635#issuecomment-898626926) and am facing the same problem. Do you have a solution?

**Comment by RolandMa1986** [comment]
I can successfully remove  `x-envoy-decorator-operation` by adding the following EnvoyFilter. I think this should also work for  Kong or ApiSix.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: remove-bad-response-headers
  namespace: ingress-nginx
spec:
  configPatches:
  - applyTo: HTTP_ROUTE
    patch:
      operation: MERGE
      value:
        decorator:
          propagate: false
```

**Comment by felpasl** [comment]
> I can successfully remove `x-envoy-decorator-operation` by adding the following EnvoyFilter. I think this should also work for Kong or ApiSix.
> 
> ```
> apiVersion: networking.istio.io/v1alpha3
> kind: EnvoyFilter
> metadata:
>   name: remove-bad-response-headers
>   namespace: ingress-nginx
> spec:
>   configPatches:
>   - applyTo: HTTP_ROUTE
>     patch:
>       operation: MERGE
>       value:
>         decorator:
>           propagate: false
> ```

Thx @RolandMa1986  👍

**Comment by felpasl** [comment]
> I can successfully remove `x-envoy-decorator-operation` by adding the following EnvoyFilter. I think this should also work for Kong or ApiSix.
> 
> ```
> apiVersion: networking.istio.io/v1alpha3
> kind: EnvoyFilter
> metadata:
>   name: remove-bad-response-headers
>   namespace: ingress-nginx
> spec:
>   configPatches:
>   - applyTo: HTTP_ROUTE
>     patch:
>       operation: MERGE
>       value:
>         decorator:
>           propagate: false
> ```

Be careful @RolandMa1986  this change works during the runtime, after some restart off kong the envoy are not able to handle services HTTP calls, causing 404 response from all services. works like a charm until pod restart.

**Comment by felpasl** [comment]
after some research, I'm apply for the role only for inbound requests, in some way removing headers from sidecar outbound requests causes the error outbound traffic, but only occurs after envoy restart.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: remove-bad-response-headers
  namespace: kong
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/name: kong
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: SIDECAR_INBOUND # this annotation fixes the envoy outbound
    patch:
      operation: MERGE
      value:
        decorator:
          propagate: false
```
