### ISSUE TITLE
With Istio-1.3 the envoyFilter for external-Auth (INBOUND) doesn't work. 

### ISSUE THREAD

**Issue by abhijitherekar** [istio/istio#17667]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
In Istio 1.3.1 when we create the EnvoyFilter external auth, the Istio-pilot fails to push the config to the Envoy SideCar. 

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ x] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
The EnvoyFilter configuration should be passed down to the Envoy SIdeCar. 

**Steps to reproduce the bug**
I applied the following EnvoyFilter
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: 1-3-ext-auth
  namespace: istio-dev
spec:
  workloadSelector:
    labels:
      app: istio-hello
  configPatches:
    # The first patch adds the lua filter to the listener/http connection manager
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        portNumber: 80
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.router"
    patch:
      operation: INSERT_BEFORE
      value: # lua filter specification
        name: envoy.ext_authz
        config:
          grpc_service:
            google_grpc:
              target_uri: 127.0.0.1:1999
              stat_prefix: aporeto-authz-ingress

```

Once I apply the above configuration I should see the Envoy sideCar to have the EnvoyFilter config pushed. But, I don't see it. 
**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.24", GitCommit:"2ce02ef1754a457ba464ab87dba9090d90cf0468", GitTreeState:"clean", BuildDate:"2019-08-12T22:05:28Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}```

**How was Istio installed?**
Installed it through the helm template. 
**Environment where bug was observed (cloud vendor, OS, etc)**
GKE



Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

I have attached the config_dump of the envoy sideCar. 
[istio-21.txt](https://github.com/istio/istio/files/3699935/istio-21.txt)

**Comment by abhijitherekar** [comment]
@rshriram  @howardjohn I see the following commits in 1.3.1 that went in the envoyFilter package:   https://github.com/istio/istio/pull/15561
https://github.com/istio/istio/pull/15639

Please, can you guys help me narrow down what could be wrong? or if its really broken?

**Comment by abhijitherekar** [comment]
here is my Istio-1.2.5 envoyFilter

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: 1-2-5-istio
  namespace: istio-dev
spec:
  filters:
  - listenerMatch:
      listenerType: SIDECAR_INBOUND
      listenerProtocol: HTTP
    filterName: envoy.ext_authz
    filterType: HTTP
    filterConfig:
      grpc_service:
        google_grpc:
          target_uri: 127.0.0.1:1999
          stat_prefix: apo-ingress-auth
```
