### ISSUE TITLE
Istio 1.2.4: Response bytes size changes between istio ingress and upstream service

### ISSUE THREAD

**Issue by mkinoshi** [istio/istio#17663]
**Bug description**
Hey all, I'm stuck with one issue, and I hope you guys can help me with figuring out this issue. We have an API endpoint that returns PDF as steam response, and we have observed that response byte size occasionally gets smaller between istio ingress and upstream service. This is corrupting PDF. It only happens sometime for the same API endpoint. Here is the diagram that summarizes the issue.

<img width="948" alt="Screen Shot 2019-10-08 at 11 56 45 AM" src="https://user-images.githubusercontent.com/10353744/66424625-d223ce80-e9c2-11e9-8e08-df4d5e5192ee.png">

You can also confirm this from these logs.

Logs from istio-proxy in istio ingress
![istio ingress](https://user-images.githubusercontent.com/10353744/66350168-78160100-e90f-11e9-921a-efd94cae390d.png)

Logs from istio-proxy in upstream service pod
![upstream service](https://user-images.githubusercontent.com/10353744/66350188-86641d00-e90f-11e9-8077-6917b368a05c.png)

As you can see, istio proxy ingress receives the different response size even though upstream service receives the same response size from the further upstream service.

Here is my gateway configuration and service virtual service and destination rule configuration.

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mygateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 80
      name: http2
      protocol: HTTP2
    hosts:
    - app.test.com
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    - app.test.com
```

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test
spec:
  hosts:
  - app.test.com
  gateways:
  - mygateway
  http:
  - route:
    - destination:
        port:
          number: 80
        host: test.default.svc.cluster.local
    websocketUpgrade: true
```

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
 name: test
spec:
 host: test.default.svc.cluster.local
 trafficPolicy:
   loadBalancer:
     consistentHash:
       useSourceIp: true
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.2.4
**How was Istio installed?**
Using helm chart
**Environment where bug was observed (cloud vendor, OS, etc)**
Google Cloud Kubernetes Engine 1.13.7-gke.8
