### ISSUE TITLE
ServiceRole spec.rules.paths not working as expected

### ISSUE THREAD

**Issue by jpatters** [istio/istio#17681]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
I have rbac enabled for my-service and I have a JWT policy in place. I have an application that allows anyone to POST to `/apps` (create an app). This creates a service role that then allows that user access to `/apps/my-app`. So actions on `/apps/my-app` should be restricted to the users in the ServiceRoleBinding.

Given the following ServiceRole and Binding
```yaml
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRole
metadata:
  name: my-servicerole
spec:
  rules:
  - services:
    - my-service
  - methods:
    - POST
  - paths:
    - /apps
---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: my-servicerolebinding
spec:
  roleRef:
    kind: ServiceRole
    name: my-servicerole
  subjects:
  - properties:
      request.auth.claims[iss]: <ISSUER>
```

Any user that matches the subject properties can access `POST /apps` (this is correct). But they can also access `POST /apps/my-app` (which is incorrect).
I have noticed that other http methods are rejected correctly (ie I can't `DELETE` `/apps/my-app`) but the paths seem to be ignored.
I also noticed in the documentation for paths it says
> This field should not be set for TCP services. The policy will be ignored.

However I am unsure what that means. Kubernetes services only support `TCP`, `UDP`, and `SCTP` as protocol options. Is it referring to service protocols? Or is it referring to the port naming conventions (`http-`, `grpc-`, etc)? I find it hard to believe it is referring to kubernetes service protocols but that is how it reads and how it seems to behave.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Access to sub paths should be restricted

**Steps to reproduce the bug**
Create the above service roles

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
$ istioctl version --remote
client version: unknown
control plane version: 1.3.0

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T14:25:20Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-eks-5ac0f1", GitCommit:"5ac0f1d9ab2c254ea2b0ce3534fd72932094c6e1", GitTreeState:"clean", BuildDate:"2019-08-20T22:39:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
helm template

**Environment where bug was observed (cloud vendor, OS, etc)**
EKS

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
