### ISSUE TITLE
trace sampling decision is not forwared when using mixer's Zipkin adapter

### ISSUE THREAD

**Issue by maxbischoff** [istio/istio#17751]
**Bug description**

When using mixer-based tracing with the zipkin adapter, traces are successfully sampled as defined by my `rules`, `handlers` and `instances`, but envoy always sets the `x-b3-sampled` Header to `0`. This means that proxied applications cannot re-use the sampling decision to forward application-level spans for sampled traces. 

I am aware, that this is probably by design (AFAIK requests to istio-telemetry are non-blocking, so envoy cannot know what sampling decision mixer made). I would like to find either a solution that changes this implementation or a workaround.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

The `x-b3-sampled` header should be set to `1` when a trace is sampled.

**Steps to reproduce the bug**

Set `global.tracer` to `zipkin`, `pilot.traceSampling` to `"0.0"` and deploy a handler, instance and rule (make sure to set your zipkin url in the handler). Then deploy an application that generates traces and observe that header `x-b3-sampled`  is always set to `0`.

<details><summary>Manifest</summary>
<p>

```yaml
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
  name: default-tracespan
  namespace: istio-system
spec:
  compiledTemplate: tracespan
  params:
    traceId: request.headers["x-b3-traceid"]
    spanId: request.headers["x-b3-spanid"] | ""
    parentSpanId: request.headers["x-b3-parentspanid"] | ""
    spanName: request.path | "/"
    startTime: request.time
    endTime: response.time
    clientSpan: (context.reporter.kind | "inbound") == "outbound"
    rewriteClientSpanId: "false"
    httpStatusCode: response.code | 0
    sourceName: (source.workload.name | "") + "." + (source.workload.namespace | "")
    sourceIp: source.ip | ip("0.0.0.0")
    destinationName: |
      (destination.workload.name | "") + "." + (destination.workload.namespace | "")
    destinationIp: destination.ip | ip("0.0.0.0")
    requestSize: request.size | 0
    requestTotalSize: request.total_size | 0
    responseSize: response.size | 0
    responseTotalSize: response.total_size | 0
    apiProtocol: api.protocol | ""
    spanTags:
      http.method: request.method | ""
      http.status_code: response.code | 200
      http.url: |
        (request.scheme | "") + "://" + (request.host | "") + (request.path | "")
      request.size: request.size | 0
      response.size: response.size | 0
      user_agent: request.headers["user-agent"] | ""
      source.principal: source.principal | ""
      source.version: source.labels["version"] | ""
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: collect-traces
  namespace: istio-system
spec:
  actions:
  - handler: jaeger-collector
    instances:
    - default-tracespan
---
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: jaeger-collector
  namespace: istio-system
spec:
  compiledAdapter: zipkin
  params:
    url: "zipkin:9411" # Replace with your URL
    sampleProbability: 1.0
```

</p>
</details>

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```bash
istioctl version --remote
client version: 1.2.6
citadel version: 1.2.6
galley version: 1.2.6
galley version: 1.2.6
pilot version: 1.2.6
pilot version: 1.2.6
policy version: 1.2.6
policy version: 1.2.6
sidecar-injector version: 1.2.6
sidecar-injector version: 1.2.6
telemetry version: 1.2.6
telemetry version: 1.2.6

kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

Using the helm-chart

**Environment where bug was observed (cloud vendor, OS, etc)**

Bare-metal kubernetes cluster
