### ISSUE TITLE
Multiple Concurrent Egress requests are very slow w/ istio-proxy sidecar

### ISSUE THREAD

**Issue by rkr-kununu** [istio/istio#17792]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

Disclaimer:  I'm still very green with istio so this could be documented somewhere, but I haven't been able to find it.

I've noticed an alarming discrepancy between the time need to run simple commands like `apt update` with an ubuntu:18.04 container
I've noticed a significant performance impact in running very simple commands like `apt update` on a ubuntu:18.04 container.  If I launch an ubuntu-18.04 pod within a non-istio enabled namespace an `apt update` takes ~2.5 seconds.  If I run the same pod in an istio aware namespace (so it gets an istio-proxy sidecar) it takes between 30-45 seconds.

I've tried isio version v1.3.2 and v1.2.6.  I've set the `outboundTrafficPolicy: ALLOW_ANY`.  I've also experimented with the egress-gateway.  I've tried on different hardware configurations (up to 32 vCPUs).  I've also tried the istio-demo and also the istio/perf benchmarks (which don't seem to test egress traffic).  I've also tested this on different version of k8s (v1.13, v1.14, v1.15).  Also using microk8s, AWS EKS, and through kops.  The all suffered similar performance degradation.

At the moment, I'm running out of ideas.  However, I have a suspicion that the envoy process running in the istio-proxy sidecar is performing some egress rate limiting.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[X] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

I expect an istio aware pods should have a similar performance compared to their non-istio aware pods.

**Steps to reproduce the bug**

The test.yaml file
```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: demo
---
apiVersion: v1
kind: Pod
metadata:
  labels:
  name: debug-node
  namespace: demo
spec:
  containers:
  - args:
    - 365d
    command:
    - sleep
    image: ubuntu:18.04
    name: test-container
---
apiVersion: v1
kind: Pod
metadata:
  labels:
  name: debug-node
  namespace: default
spec:
  containers:
  - args:
    - 365d
    command:
    - sleep
    image: ubuntu:18.04
    name: test-container
```
```bash
kubectl apply -f istio-demo.yaml
kubectl apply -f test.yaml
kubectl exec -t -n default debug-node -- bash -c 'time apt update > /dev/null'
kubectl exec -t -n demo debug-node -- bash -c 'time apt update > /dev/null'
```

My results
```bash
$ kubectl exec -t debug-node -n default -- bash -c 'time apt update > /dev/null'

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.


real	0m3.393s
user	0m2.292s
sys	0m0.196s

$ kubectl exec -t debug-node -n demo -- bash -c 'time apt update > /dev/null'
Defaulting container name to test-container.
Use 'kubectl describe pod/debug-node -n demo' to see all of the containers in this pod.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.


real	0m32.044s
user	0m2.324s
sys	0m0.120s
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```bash
$ ./bin/istioctl version --remote
client version: 1.3.2
citadel version: 1.3.2
egressgateway version: 1.3.2
galley version: 1.3.2
ingressgateway version: 1.3.2
pilot version: 1.3.2
policy version: 1.3.2
sidecar-injector version: 1.3.2
telemetry version: 1.3.2
```
```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

`kubectl apply -f istio-demo.yaml`

**Environment where bug was observed (cloud vendor, OS, etc)**

* AWS EKS (k8s v1.13)
* microk8s (v1.14, v1.15)
* Kops AWS+calico (v1.13, v1.14)
