### ISSUE TITLE
Istio generates duplicate tracing entries on Jaeger (same ID)

### ISSUE THREAD

**Issue by carlosedp** [istio/istio#17827]
**Bug description**

I've deployed a fresh minikube (based on 1.16) cluster on my computer with the following params:

```bash
minikube start \
    --vm-driver=hyperkit \
    --network-plugin=cni \
    --enable-default-cni \
    --container-runtime=cri-o \
    --bootstrapper=kubeadm \
    --cpus=4 \
    --memory=8192 \
    --cache-images=true

minikube addons enable dashboard
minikube addons enable ingress
minikube addons enable metrics-server
```

After this, I've deployed Istio following the Quickstart instructions:

```
curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.3.2 sh -

cd istio-1.3.2

for i in install/kubernetes/helm/istio-init/files/crd*yaml; do kubectl apply -f $i; done

kubectl apply -f install/kubernetes/istio-demo.yaml

kubectl label namespace default istio-injection=enabled

# Create namespace for demo apps
kubectl create namespace istio-demo
kns istio-demo
kubectl label namespace istio-demo istio-injection=enabled
```

And then deployed the HTTPbin and Bookinfo sample applications. Whenever I look in Jaeger dashboard, the trace entries are duplicated even with same ID:

```
kubectl apply -f samples/httpbin/httpbin.yaml

IP=$(minikube ip)
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "httpbin.${IP}.nip.io"
EOF

kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - "httpbin.${IP}.nip.io"
  gateways:
  - httpbin-gateway
  http:
  - match:
    - uri:
        prefix: /status
    - uri:
        prefix: /delay
    route:
    - destination:
        port:
          number: 8000
        host: httpbin
EOF

export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].nodePort}')
export SECURE_INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="https")].nodePort}')
export INGRESS_HOST=$(minikube ip)

curl -I -H Host:httpbin.${IP}.nip.io http://$INGRESS_HOST:$INGRESS_PORT/status/200
```

<img width="1598" alt="image" src="https://user-images.githubusercontent.com/20382/66703369-496da100-ece8-11e9-98b3-cd7932aec285.png">

This also happens to the Bookinfo sample.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Expected behavior**

See each trace only once.

**Steps to reproduce the bug**

I've reproduced my steps above.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```
❯ istioctl version --remote
client version: unknown
citadel version: 1.3.2
egressgateway version: 1.3.2
galley version: 1.3.2
ingressgateway version: 1.3.2
pilot version: 1.3.2
policy version: 1.3.2
sidecar-injector version: 1.3.2
telemetry version: 1.3.2

❯ kubectl version
Found existing alias for "kubectl". You should use: "k"
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T23:49:20Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

Quickstart, as describe above.

**Environment where bug was observed (cloud vendor, OS, etc)**

Minikube cluster

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
