### ISSUE TITLE
controller has odd sematnics when dealing with conflicts

### ISSUE THREAD

**Issue by sdake** [istio/istio#17868]
Specifying a cr manifest such as
```
spec:
  gateways:
    enabled: true
    components:
      egressGateway:
        enabled: true
      ingressGateway:
        enabled: true
```
fails.  I see no reason why this custom resource should fail.

**Bug description**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**
install istio
insttall cr
operator implodes

**How was Istio installed?**
following procedure here:
https://deploy-preview-5142--preliminary-istio.netlify.com/docs/setup/install/kubernetes/

**Environment where bug was observed (cloud vendor, OS, etc)**
all

**Comment by elfinhe** [comment]
I installed istio with operator as a controller. Then I applied the CR below:
```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  namespace: istio-operator
  name: example-istiocontrolplane
spec:
  gateways:
    enabled: true
    components:
      egressGateway:
        enabled: true
      ingressGateway:
        enabled: true
```

And everything looks good.

@sdake can you elaborate what error did you see when the "operator implodes"?
