### ISSUE TITLE
Cant Connect to Azure SQL using SideCar Injection

### ISSUE THREAD

**Issue by kahootali** [istio/istio#1789]
I am using Minikube 0.23, Kubernetes 1.8.0 and Istio 0.2.7 on Windows 10.
I have also used Istio 0.2.12 and it also had the same issue. 

I have deployed the bookinfo sample and its working fine but when I am deploying my own application which calls Azure SQL for data or other external services, it gives exception.

`A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)`

I then added the Egress as well 
```
apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: sql
spec:
  destination:
    service: dbName.database.windows.net
  ports:
    - port: 443
      protocol: https

```
And now I am getting

 `A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 0 - Success)`

**Comment by rshriram** [comment]
this is related to the tcp egress rule that @vadimeisenbergibm is doing.. see PR #1651 
until then use the includeIPranges or try accessing 443 over http (sidecar will do tls upgrade)

**Comment by vadimeisenbergibm** [comment]
Fixed by PR https://github.com/istio/istio/pull/1651. Please specify protocol tcp in the egress rule.

**Comment by kahootali** [comment]
I have upgrade to Istio 0.3.0 and have made the following EgressRule 

```
apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: azure-sql
spec:
  destination:
    service: <server-name>.database.windows.net
  ports: 
    - port: 1433
      protocol: tcp
---
```

but it is still not working and giving the same error.
