### ISSUE TITLE
Sidecar did not send check request correctly under load

### ISSUE THREAD

**Issue by LSChyi** [istio/istio#17967]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
While using istio-1.3.2, I encountered a bug that sometimes sidecar send check request, but sometimes not. This causes the rate-limiting incorrect. I also did some [code change](https://github.com/istio/proxy/pull/2467) as an experiment in istio/proxy to check the behavior, turns out that after I disable some condition check, the sidecar is sending check request even under high traffic load.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[x ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Sidecar should follow the mechanism of sending check request even under high load.

**Steps to reproduce the bug**
Deploy a rate limiting definitions:

```
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: quotahandler
  namespace: istio-system
spec:
  compiledAdapter: memquota
  params:
    quotas:
    - name: mycountquota.instance.istio-system
      maxAmount: 9223372036854775807 # int64 max
      validDuration: 10s
---
apiVersion: config.istio.io/v1alpha2
kind: instance
metadata:
  name: mycountquota
  namespace: istio-system
spec:
  compiledTemplate: quota
  params:
    dimensions:
      source: source.uid | "unknown"
      destination: destination.uid | "unknown"
---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpec
metadata:
  name: request-count
  namespace: istio-system
spec:
  rules:
  - quotas:
    - charge: 1
      quota: mycountquota
---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpecBinding
metadata:
  name: request-count
  namespace: istio-system
spec:
  quotaSpecs:
  - name: request-count
    namespace: istio-system
  services:
  - service: '*'
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: quota
  namespace: istio-system
spec:
  actions:
  - handler: quotahandler
    instances:
    - mycountquota
```
, and then deploy high request traffic load deployments.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istio-1.3.2

**How was Istio installed?**
Manually installed with command in instruction:
```
kubectl apply -f install/kubernetes/istio-demo.yaml
```

**Environment where bug was observed (cloud vendor, OS, etc)**
jelastic with Kubernetes 1.15.3

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
