### ISSUE TITLE
DestinationHost analyzer does not handle wildcards

### ISSUE THREAD

**Issue by burmanm** [istio/istio#17976]
**Bug description**

ServiceEntries with wildcards are only matched as exact matches instead of trying to use the wildcard information at all. This means SE with "*.bookinfo.com" would not match "eu.bookinfo.com" but the VS would be marked invalid.

**Affected product area (please put an X in all that apply)**

[x ] User Experience

**Expected behavior**

Wildcards are matched.

**Steps to reproduce the bug**

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: service-entry-bookinfo
  namespace: default
spec:
  hosts:
  - "*.eu.bookinfo.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews-bookinfo-eu-wildcard
  namespace: default
spec:
  http:
  - route:
    - destination:
        host: reviews.eu.bookinfo.com
        subset: v1
```

@sushicw
