### ISSUE TITLE
Behind GCP L7 LoadBalancer istio redirection stuck in infinite loop 

### ISSUE THREAD

**Issue by shudhanshh** [istio/istio#17980]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
normal http to https redirection
**Steps to reproduce the bug**
connect 31380 port at the backend of http(s) load balancer but at TCP load balancer its work fine 
**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istio version 1.3.3
**How was Istio installed?**
istio installed using helm chart
**Environment where bug was observed (cloud vendor, OS, etc)**
On Google Cloud Platform.
Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
I already try envoyfilter as well as istio handler 
Please help me with this

**Comment by howardjohn** [comment]
@shudhanshh I don't think we have enough info here to help. I don't understand what the issue is, and what steps would be needed to reproduce, can you expand on this?

**Comment by shudhanshh** [comment]
@howardjohn we are trying to run istio behind gcp layer 7 Load balancer we connected istio ingress gateway at the backend of gcp load balancer with 31380 port when we set tls.httpsredirect: true in istio gateway our every request we get response code = 301 permanently moved even we requested is already on https.

**Comment by lambdai** [comment]
Will be fix by https://github.com/istio/api/pull/1148 (along with the pilot change)

**Comment by bbenlazreg** [comment]
Hello
I am facing the same issue using istio self installed and GCP HTTPS LB , 
httpsRedirect: true in the istio gateway and got infinite loop is there a workaround ?

**Comment by howardjohn** [comment]
@lambdai the linked PR was closed, do we have another fix?

**Comment by bbenlazreg** [comment]
Worked for me on Istio 1.4.0 by using EnvoyFilter and setting xff_num_trusted_hops=1
But still does not work in 1.3.x

**Comment by jainbhavya65** [comment]
@bbenlazreg we are still facing same issue can you please guide us how you connect it

**Comment by bbenlazreg** [comment]
> @bbenlazreg we are still facing same issue can you please guide us how you connect it

I applied this envoy filter on Istio 1.4.0

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  annotations:
  name: ingressgateway-settings
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
    patch:
      operation: MERGE
      value:
        typed_config:
          '@type': type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          xff_num_trusted_hops: 1
  workloadSelector:
    labels:
      istio: ingressgateway
```
