### ISSUE TITLE
Overriding resources does not lead to correct merging

### ISSUE THREAD

**Issue by ostromart** [istio/istio#18036]
To reproduce, install using operator controller, then edit the ICP CR to modify trafficManagement.components.pilot.k8s.hpaSpec.minReplicas to 2. 
The value is modified, but some other HPA settings are deleted in the process. This is likely due to incorrect merging when the final output manifest is generated in the controller.

**Comment by sdake** [comment]
@irisdingbj can you take a look at this defect?  This is very important to get right for Istio for 1.4.

**Comment by kramvan1** [comment]
An example CR where it fails to apply the hpaSpec:
```
gateways:
    components:
      egressGateway:
        enabled: true
        k8s:
          hpaSpec:
            minReplicas: 2
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: istio-egressgateway
```

The HPA is created, but the minReplicas is still default of 1.

Also interesting that doing this with the ingress gateway works!?
