### ISSUE TITLE
deleting ICP cr left a few resources

### ISSUE THREAD

**Issue by linsun** [istio/istio#18031]
**Bug description**

After I delete my ICP (istio control plane) cr, all pods/deployments/services in Istio-system are removed.  However, the istio-security ConfigMap remains.  Also, all secrets remain, plus the default service account for istio-system namespace.   All other configmaps and service accounts do get removed.

I noticed what is left don't have the proper labels needed for operator to remove them.

For example, I'm not seeing these labels on the resources that remain which I believe caused the operator to not prune them.

```
 labels:
    install.operator.istio.io/owner-group: install.istio.io
    install.operator.istio.io/owner-kind: IstioControlPlane
    install.operator.istio.io/owner-name: example-istiocontrolplane

```

@morvencao could you take a look at this prob if you have time?  

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
