### ISSUE TITLE
EDS built should consider svc port other than name

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#18038]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

As can be seen https://github.com/istio/istio/blob/156d828d379be772f8d04cac342210e2f04b97b2/pilot/pkg/proxy/envoy/v2/eds.go#L270-L278

If we have a service httpbin with port 8000 and target port 80,  and a service entry with hosts equals httpbin

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpbin
  name: httpbin
  namespace: default
spec:
  clusterIP: 10.107.220.17
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 80
  selector:
    app: httpbin
  sessionAffinity: None
  type: ClusterIP

```

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin
  namespace: default
spec:
  endpoints:
  - address: 1.2.3.4
  hosts:
  - httpbin.default.svc.cluster.local
  ports:
  - name: http
    number: 80
    protocol: HTTP
  resolution: STATIC

```

The eds is
```
# istioctl pc endpoint redis-2|grep httpbin
1.2.3.4:80              HEALTHY     OK                outbound|8000||httpbin.default.svc.cluster.local
1.2.3.4:80              HEALTHY     OK                outbound|80||httpbin.default.svc.cluster.local
10.32.0.13:80           HEALTHY     OK                outbound|8000||httpbin.default.svc.cluster.local

```

But the expected output should be:

```
1.2.3.4:80              HEALTHY     OK                outbound|80||httpbin.default.svc.cluster.local
10.32.0.13:80           HEALTHY     OK                outbound|8000||httpbin.default.svc.cluster.local
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

pilot version: 1.3.3

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
