### ISSUE TITLE
Websocket connections fail when passing through istio-ingressgateway

### ISSUE THREAD

**Issue by 2ZZ** [istio/istio#18045]
**Bug description**
Websocket connections fail when passing through istio-ingressgateway as the `Connection` and `Upgrade` headers are not passed through to the backend application.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Connection and Upgrade headers are passed through intact to the the backend application.

**Steps to reproduce the bug**
Create required resources
```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: httpbin
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: httpbin
    spec:
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80
          name: http
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpbin
  name: httpbin
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: httpbin
  type: ClusterIP

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  gateways:
  - httpbin
  hosts:
  - httpbin.example.org
  http:
  - route:
    - destination:
        host: httpbin
        port:
          number: 80
    websocketUpgrade: true

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - httpbin.example.org
    port:
      name: http
      number: 80
      protocol: HTTP
```

Make a request against the istio-ingressgateway and see that the Upgrade and  Connection headers do not arrive at the application
```
$ curl \
    -H "Host: httpbin.example.org"\
    -H "Connection: upgrade"\
    -H "Upgrade: websocket"\
    httpbin.redacted.com/headers

{
  "headers": {
    "Accept": "*/*",
    "Content-Length": "0",
    "Host": "httpbin.example.org",
    "User-Agent": "curl/7.54.0",
    "X-B3-Sampled": "0",
    "X-B3-Spanid": "<>",
    "X-B3-Traceid": "<>",
    "X-Envoy-Decorator-Operation": "httpbin.<>.svc.cluster.local:80/*",
    "X-Envoy-External-Address": "<>",
    "X-Istio-Attributes": "<>"
  }
}
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```
client version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"brew", Host:"Mojave.local", GolangVersion:"go1.12.2", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.2"}
citadel version: version.BuildInfo{Version:"release-1.3-20191017-10-15", GitRevision:"d929f625306d844225a56c862c7545b0e2c53d46-dirty", User:"root", Host:"3da39106-f0c7-11e9-9560-0a43958f334c", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.3.3-3-gd929f62"}
galley version: version.BuildInfo{Version:"release-1.3-20191017-10-15", GitRevision:"d929f625306d844225a56c862c7545b0e2c53d46-dirty", User:"root", Host:"3da39106-f0c7-11e9-9560-0a43958f334c", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.3.3-3-gd929f62"}
ingressgateway version: version.BuildInfo{Version:"release-1.3-20191017-10-15", GitRevision:"d929f625306d844225a56c862c7545b0e2c53d46", User:"root", Host:"3da39106-f0c7-11e9-9560-0a43958f334c", GolangVersion:"go1.12.9", DockerHub:"gcr.io/istio-release", BuildStatus:"Clean", GitTag:"1.3.3-3-gd929f62"}
pilot version: version.BuildInfo{Version:"release-1.3-20191017-10-15", GitRevision:"d929f625306d844225a56c862c7545b0e2c53d46-dirty", User:"root", Host:"3da39106-f0c7-11e9-9560-0a43958f334c", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.3.3-3-gd929f62"}
policy version: version.BuildInfo{Version:"release-1.3-20191017-10-15", GitRevision:"d929f625306d844225a56c862c7545b0e2c53d46-dirty", User:"root", Host:"3da39106-f0c7-11e9-9560-0a43958f334c", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.3.3-3-gd929f62"}
sidecar-injector version: version.BuildInfo{Version:"release-1.3-20191017-10-15", GitRevision:"d929f625306d844225a56c862c7545b0e2c53d46-dirty", User:"root", Host:"3da39106-f0c7-11e9-9560-0a43958f334c", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.3.3-3-gd929f62"}
telemetry version: version.BuildInfo{Version:"release-1.3-20191017-10-15", GitRevision:"d929f625306d844225a56c862c7545b0e2c53d46-dirty", User:"root", Host:"3da39106-f0c7-11e9-9560-0a43958f334c", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.3.3-3-gd929f62"}
```

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-04T04:49:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-eks-5876d6", GitCommit:"5876d6b7429820450950ade17fe7b4bf5ccada7f", GitTreeState:"clean", BuildDate:"2019-09-24T20:54:25Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
From the offical Helm chart. Also tested on 1.2.6 and 1.2.7.

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS 1.13
