### ISSUE TITLE
IstioCoreDNS is not resolving any domain other than *.global

### ISSUE THREAD

**Issue by rjshrjndrn** [istio/istio#18092]
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
service entry domain should resolve to an ip.
**Steps to reproduce the bug**
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: keycloak-dns
spec:
  hosts:
  - 'keycloak.sunbird.dev'
  addresses:
  - 11.2.0.129
  ports:
  - number: 8080
    name: keycloak
    protocol: HTTP
  location: MESH_INTERNAL
  resolution: DNS
  endpoints:
  - address: 11.2.0.129
```
**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
❮ istioctl version
client version: 1.2.4
citadel version: 1.3.2
galley version: 1.3.2
ingressgateway version: 1.3.2
nodeagent version:
pilot version: 1.3.2
policy version: 1.3.2
sidecar-injector version: 1.3.2
telemetry version: 1.3.2
```
**How was Istio installed?**
helm
**Environment where bug was observed (cloud vendor, OS, etc)**
auzre, local(with k3d)
Note:
I figured there is a hardcoded `global` entry in core file. 
Is it by design not to allow custom domain resolution? Can you kindly tell me why is that?
```
  Corefile: |
    .:53 {
          errors
          health
          {{ if eq -1 (semver  .Values.coreDNSTag  | (semver "1.4.0").Compare) }}
          # Removed support for the proxy plugin: https://coredns.io/2019/03/03/coredns-1.4.0-release/
          grpc global 127.0.0.1:8053
          forward . /etc/resolv.conf {
            except global
          }
          {{ else }}
          proxy global 127.0.0.1:8053 {
            protocol grpc insecure
          }
          proxy . /etc/resolv.conf
          {{ end }}
          prometheus :9153
          cache 30
          reload
        }
```

**Comment by rahulrai-in** [comment]
Facing a similar problem but even *.global doesn't work for me. I followed the steps documented here: https://istio.io/docs/setup/install/multicluster/gateways/#setup-dns

CoreDNS is behaving in a very strange way for me. If the hostname is DNS resolvable for HTTP e.g. google.com, then it works for me even without making any changes to the corefile. However, if the hostname is not DNS resolvable e.g. myservice.internal, nothing works and on lookup I get an error with message: getaddrinfo ENOTFOUND myservice.internal.

**Comment by rjshrjndrn** [comment]
for a simple example.
1. create config map like this
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
  name: coredns-custom
  namespace: kube-system
data:
  Sunbird.server: |-
    global:53 {
       errors
       cache 30
       forward . 172.16.136.83 # istio core dns service ip
    }
```
I am using azure, and azure kube-system coredns will take this cornfig map as an additional serice entry. you might have to append this to your `kube-system` coredns config map if necessary.

2. Create serviceEntry
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: keycloak-dns
spec:
  hosts:
  - 'keycloak.sunbird.global'
  addresses:
  - 11.2.0.129
  ports:
  - number: 8080
    name: keycloak
    protocol: HTTP
  location: MESH_INTERNAL
  resolution: DNS
  endpoints:
  - address: 11.2.0.129
```
now `kubectl exec` to any other pod and try to resolve keycloak.sunbird.global` will resolve the ip address.

@rahulrai-in this will help you out
