### ISSUE TITLE
istio operator fails to reconcile for some cr changes

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#18113]
Isti-operator will fail to reconcile if we apply below crs:

```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  name: example-istiocontrolplane
spec:
  profile: demo
  trafficManagement:
    components:
      pilot:
       enabled: true
        k8s:
          hpa_spec:
            maxReplicas: 4
            metrics:
              - resource:
                  name: cpu
                  targetAverageUtilization: 80
                type: Resource
            minReplicas: 1
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: istio-pilot
```

2019-10-21T08:33:47.619842Z	error	Cannot unmarshal: json: cannot unmarshal object into Go value of type bool

The reason is we will change the spec as below: 
```
spec:
  profile: demo
  trafficManagement:
    components:
      pilot:
        enabled:
          value: true
        k8s:
          hpa_spec:
            maxReplicas: 4
            metrics:
              - resource:
                  name: cpu
                  targetAverageUtilization: 80
                type: Resource
            minReplicas: 1
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: istio-pilot
```
