### ISSUE TITLE
Operator: deployment spec need resource limits

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#18134]
**Bug description**

Operator deployment spec needs resource limits.  Some baseline is needed to start with:
```
resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 50m
        memory: 100Mi
```

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
