### ISSUE TITLE
Istio control plane supports the envoy function (tcp listener connection balancing)

### ISSUE THREAD

**Issue by zengyuxing007** [istio/istio#18152]
**Describe the feature request**
The envoy community has released about tcp listener connection balancing(https://github.com/envoyproxy/envoy/pull/8422), which need pilot-discovery to support its configure
``` yaml
connection_balance_config:
  exact_balance: {}
```

This feature will improve the istio performance, and we verify that the fluctuation is reduced under the fortio scenario test.

hope istio  can add this feature to the istio 1.4 version. thanks 

**Describe alternatives you've considered**

**Additional context**

**Comment by hobbytp** [comment]
Hi,
    When will this feature be developed or merged? Will istio 1.4 support this? Thanks,

**Comment by zengyuxing007** [comment]
@ericvn
@jwendell
@howardjohn

**Comment by howardjohn** [comment]
No, this would not be in 1.4. We only add bug fixes to patch releases. The cut off for 1.5 is January 20th or somewhere around there

**Comment by howardjohn** [comment]
when rebalance happens will it close the connection and reopen?

do we have a way to detect when connection are not balanced?

**Comment by zengyuxing007** [comment]
@howardjohn  no,  reblancer will not  close the connection, it happened in the connection accept stage,  we can using envoy stats admin api to see if the connection is balanced or not ;

see more https://github.com/envoyproxy/envoy/pull/8263

**Comment by hobbytp** [comment]
I try envoy proxy 1.14.1 (istio 1.6.1), and configure the outbound listener 0.0.0.0_9080 in productpage in bookinfo demo, the envoyfilter yaml file is as below,

```yaml
kubectl -n hobby apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: productpage-listener-balance
  namespace: hobby
spec:
  workloadSelector:
    labels:
      app: productpage
  configPatches:
    - applyTo: LISTENER
      match:
        context: SIDECAR_OUTBOUND
        listener:
          address: 0.0.0.0
          portNumber: 9080
      patch:
        operation: MERGE
        value:
          connection_balance_config:
            exact_balance: {}
EOF
```

The istioctl to check the listener configuration is as below:
```yaml
istioctl pc listener productpage-v1-7f59696447-dxx8p.hobby --port 9080 -ojson
    {
        "name": "0.0.0.0_9080",
        "address": {
            "socketAddress": {
                "address": "0.0.0.0",
                "portValue": 9080
            }
        },
        "filterChains": 
        ...
        "listenerFiltersTimeout": "0.100s",
        "continueOnListenerFiltersTimeout": true,
        "trafficDirection": "OUTBOUND",
        "connectionBalanceConfig": {
            "exactBalance": {}                   #==>here
        }
```

And the admin stats for 0.0.0.0_9080 output is as below, I reset the counters every testing, and try more than 3 times, each time, the worker_0 downstream_cx_total is about 3 times of worker_1 downstream_cx_total, so seems the balance is not good. 
```bash
/$ curl localhost:15000/stats | grep listener.0.0.0.0_9080
listener.0.0.0.0_9080.downstream_cx_active: 0
listener.0.0.0.0_9080.downstream_cx_destroy: 220
listener.0.0.0.0_9080.downstream_cx_total: 220
listener.0.0.0.0_9080.downstream_pre_cx_active: 0
listener.0.0.0.0_9080.downstream_pre_cx_timeout: 0
listener.0.0.0.0_9080.http.outbound_0.0.0.0_9080.downstream_rq_1xx: 0
listener.0.0.0.0_9080.http.outbound_0.0.0.0_9080.downstream_rq_2xx: 220
listener.0.0.0.0_9080.http.outbound_0.0.0.0_9080.downstream_rq_3xx: 0
listener.0.0.0.0_9080.http.outbound_0.0.0.0_9080.downstream_rq_4xx: 0
listener.0.0.0.0_9080.http.outbound_0.0.0.0_9080.downstream_rq_5xx: 0
listener.0.0.0.0_9080.http.outbound_0.0.0.0_9080.downstream_rq_completed: 220
listener.0.0.0.0_9080.no_filter_chain_match: 0
listener.0.0.0.0_9080.worker_0.downstream_cx_active: 0
listener.0.0.0.0_9080.worker_0.downstream_cx_total: 170
listener.0.0.0.0_9080.worker_1.downstream_cx_active: 0
listener.0.0.0.0_9080.worker_1.downstream_cx_total: 50
```
And then I try to enable "reuse_port: true" for the same listener, it does not help.

Please correct me if there is any configuration error.

Thanks,
