### ISSUE TITLE
Envoy Filter doesn't merge properly BoolValues

### ISSUE THREAD

**Issue by fcantournet** [istio/istio#18169]
**Bug description**

`use_remote_address` cannot be set to `false` on `http_connection_manager` filter via the new envoy filter API.

This seems to be the case for `BoolType` values (as opposed to `bool`) :
 I see the same problem for `use_remote_address` & `generate_request_id`, whereas I can set `preserve_external_request_id` to `true`. 

cf : https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/http_connection_manager/v2/http_connection_manager.proto

Given the following Gateway :
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*.staging-1.blbl.cr'
    port:
      name: http
      number: 80
      protocol: HTTP
```

The `use_remote_address` filed is set by default to `true`.

When applying the following `EnvoyFilter` : 
```apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  annotations:
  name: ingressgateway-settings
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
    patch:
      operation: MERGE
      value:
        typed_config:
          '@type': type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          use_remote_address: false
          xff_num_trusted_hops: 2
  workloadSelector:
    labels:
      istio: ingressgateway
```

The `MERGE` behavior doesn't take into account `use_remote_address: false`.

You get the following listener :
`istioctl pc listener istio-ingressgateway-fdd56884f-hl2gg --port 80 -o json`
```
[
    {
        "name": "0.0.0.0_80",
        "address": {
            "socketAddress": {
                "address": "0.0.0.0",
                "portValue": 80
            }
        },
        "filterChains": [
            {
                "filters": [
                    {
                        "name": "envoy.http_connection_manager",
                        "typedConfig": {
                            "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager",
                            "statPrefix": "0.0.0.0_80",
                            "rds": {
                                "configSource": {
                                    "ads": {},
                                    "initialFetchTimeout": "0s"
                                },
                                "routeConfigName": "http.80"
                            },
                            "httpFilters": [
                                {
                                    "name": "mixer",
                                    "typedConfig": {
                                        "@type": "type.googleapis.com/istio.mixer.v1.config.client.HttpClientConfig",
                                        "transport": {
                                            "networkFailPolicy": {
                                                "policy": "FAIL_CLOSE",
                                                "baseRetryWait": "0.080s",
                                                "maxRetryWait": "1s"
                                            },
                                            "checkCluster": "outbound|9091||istio-policy.istio-system.svc.cluster.local",
                                            "reportCluster": "outbound|9091||istio-telemetry.istio-system.svc.cluster.local",
                                            "reportBatchMaxEntries": 100,
                                            "reportBatchMaxTime": "1s"
                                        },
                                        "serviceConfigs": {
                                            "default": {
                                                "disableCheckCalls": true
                                            }
                                        },
                                        "defaultDestinationService": "default",
                                        "mixerAttributes": {
                                            "attributes": {
                                                "context.proxy_version": {
                                                    "stringValue": "1.3.2"
                                                },
                                                "context.reporter.kind": {
                                                    "stringValue": "outbound"
                                                },
                                                "context.reporter.uid": {
                                                    "stringValue": "kubernetes://istio-ingressgateway-fdd56884f-hl2gg.istio-system"
                                                },
                                                "source.namespace": {
                                                    "stringValue": "istio-system"
                                                },
                                                "source.uid": {
                                                    "stringValue": "kubernetes://istio-ingressgateway-fdd56884f-hl2gg.istio-system"
                                                }
                                            }
                                        },
                                        "forwardAttributes": {
                                            "attributes": {
                                                "source.uid": {
                                                    "stringValue": "kubernetes://istio-ingressgateway-fdd56884f-hl2gg.istio-system"
                                                }
                                            }
                                        }
                                    }
                                },
                                {
                                    "name": "envoy.cors"
                                },
                                {
                                    "name": "envoy.fault"
                                },
                                {
                                    "name": "envoy.router"
                                }
                            ],
                            "tracing": {
                                "operationName": "EGRESS",
                                "clientSampling": {
                                    "value": 100
                                },
                                "randomSampling": {
                                    "value": 1
                                },
                                "overallSampling": {
                                    "value": 100
                                }
                            },
                            "httpProtocolOptions": {},
                            "serverName": "istio-envoy",
                            "streamIdleTimeout": "0s",
                            "useRemoteAddress": true,
                            "xffNumTrustedHops": 2,
                            "generateRequestId": true,
                            "forwardClientCertDetails": "SANITIZE_SET",
                            "setCurrentClientCertDetails": {
                                "subject": true,
                                "cert": true,
                                "dns": true,
                                "uri": true
                            },
                            "upgradeConfigs": [
                                {
                                    "upgradeType": "websocket"
                                }
                            ],
                            "normalizePath": true
                        }
                    }
                ]
            }
        ],
        "listenerFiltersTimeout": "0.100s",
        "continueOnListenerFiltersTimeout": true,
        "trafficDirection": "OUTBOUND"
    }
]
```
**Expected behavior**

Being able to set `use_remote_address` to `false` on the ingress gateway.

**Steps to reproduce the bug**

create a Gateway. 
Add a filter link above.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

istio : 1.3.2 (all)
kubernetes: v1.14.6-gke.13

**How was Istio installed?**

Helm chart from the istio/istio repo

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by rshriram** [comment]
Have you tried
```
patch:
      operation: MERGE
      value:
        typed_config:
          '@type': type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          use_remote_address: 
               value: false
          xff_num_trusted_hops: 2
```

**Comment by fcantournet** [comment]
This error is weird because it means that in `gogo/protobuf/jsonpb/jsonpb.go` it goes in the case `"Any"` at line 821 and not in the case `BoolValue`.

There is an inconsistency here between the type as defined in the proto of envoy (`BoolValue`) and this.

**Comment by rshriram** [comment]
Yeah.. oh this is tricky. @kyessenov did envoy go control plane move to golang/protobuf ? There is an XDS serialization here https://github.com/istio/istio/blob/master/pkg/config/xds/xds.go that might need a fix possibly?

**Comment by kyessenov** [comment]
@rshriram Yes, it's been awhile already. All xDS protos should use the standard protobuf, not gogo.
@fcantournet This is probably a BoolValue wrapper, which Envoy uses for fields with presence checks. Proto3 does not allow presence checks for regular `bool` fields.

**Comment by fcantournet** [comment]
@kyessenov Yes I agree, I think I understand the idea behind the BoolValue type. My understanding of the spec is that the json representation of a BoolValue is the same as that of a bool, i.e : a json bool.

Therefore the current merge should work, barring a bug in istio or golang.org/protobuf/pbjson. I've not been able to reproduce this problem in the golang.org/protobuf/pbjson unit tests.
I'm a bit lost in terms of what could be done.
I'm not sure I understand why we convert from struct to protobuf via json to begin with to be honest, and I'm not sure how I can advance this topic.
Is someone working on this ?

**Comment by infa-rbliznet** [comment]
We have the same bug but related to set_current_client_cert_details:
Envoy filter:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: xffc-details
  namespace: {{ .Release.Namespace }} 
spec:
  workloadSelector:
    labels:
{{ .Values.iicsgateway.labels | toYaml | indent 6 }}
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager"
          set_current_client_cert_details: 
            subject: true
            cert: false
            chain: false
            dns: false
            uri: true
```
from istio-ingressgateway envoy:
curl -X GET http://127.0.0.1:15000/config_dump
```
        "set_current_client_cert_details": {
            "subject": true,
            "cert": true,
            "dns": true,
            "uri": true
           }
```

For us it's even bigger issue since we don't want our certificates to be leaked to logs.
