### ISSUE TITLE
istioctl analyze works with restricted role

### ISSUE THREAD

**Issue by selmanj** [istio/istio#18177]
We should test situations where `istioctl analyze` is running under a role with restricted permissions (e.g. if unable to view the `istio-system` namespace, what does the injection analyzer do? What should it do?)

**Comment by dgn** [comment]
I ran into this today. `istioctl analyze -k` seems to require `list` permissions on CustomResourceDefinitions, which are cluster-scoped:

```
Failed to list *v1beta1.CustomResourceDefinition: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "developer" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
```

Will look into this and see if we can skip the CRD check.

**Comment by dgn** [comment]
Hmm. I can skip the CRD check by changing a few lines, but the Galley code will try to watch all Istio resources at the cluster-scope.

**Comment by sushicw** [comment]
We should determine exactly what permissions are needed make sure they get documented.

**Comment by sushicw** [comment]
Permissions needed:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istioctl-analyze-role
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - namespaces
  - nodes
  - pods
  - secrets
  - services
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resourceNames:
  - istio
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - list
  - watch
- apiGroups:
  - authentication.istio.io
  - config.istio.io
  - networking.istio.io
  - rbac.istio.io
  - security.istio.io
  resources:
  - '*'
  verbs:
  - list
  - watch
```
