### ISSUE TITLE
Custom Grafana dashboards not showing data when mTLS enabled

### ISSUE THREAD

**Issue by tkatrichenko** [istio/istio#18174]
**Bug description**
After enabling mTLS, Grafana doesn't show data from custom dashboards 

**Expected behavior**
Grafana shows data from the dashboards

**Steps to reproduce the bug**
Istio was installed using Helm template (some options were omitted to make it shorter)
```
helm template install/kubernetes/helm/istio \
  --namespace istio-system \
  --set kiali.enabled=true \
  --set grafana.enabled=true \
  --set tracing.enabled=true \
  --set sidecarInjectorWebhook.rewriteAppHTTPProbe=true \
  --set global.controlPlaneSecurityEnabled=true > istio.yaml
```
After I enabled mTLS (applied policy/dest rule), I can't see any incoming data in my custom dashboards for Spring Boot applications. I'm using these 2 dashboards 

- Spring Boot 2.x Statistics https://grafana.com/grafana/dashboards/10280
- JVM (Micrometer) https://grafana.com/grafana/dashboards/4701

 Default Istio dashboards, Kiali, Jaeger are working fine

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
# istioctl version
client version: 1.3.3
control plane version: 1.3.3
# kubectl version 
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7+IKS", GitCommit:"44d102fa84ebb514e817942f5b1090cf54844445", GitTreeState:"clean", BuildDate:"2019-09-24T06:08:41Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment where bug was observed (cloud vendor, OS, etc)**
IBM Cloud, IKS 1.14.7

My mtls.yaml
```yaml
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "default"
  namespace: "default"
spec:
  peers:
  - mtls: {}
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "default"
  namespace: "default"
spec:
  host: "*.default.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```

What else to check?

**Comment by howardjohn** [comment]
So the application is reporting these metrics but they aren't on the dashboard? Sounds like maybe prometheus scraping is failing.

I would run through https://istio.io/docs/ops/troubleshooting/missing-metrics/ and see if that helps first

**Comment by tkatrichenko** [comment]
Thanks for your reply. I checked with https://istio.io/docs/ops/troubleshooting/missing-metrics/  and looks like everything is okay in terms of istio-mesh. 

However, I discovered that Prometheus fails to receive metrics from "spring-actuator" endpoints once mTLS enabled. Looks like it can't receive it because Prometheus is outside of the Service Mesh 
```
Get http://my-service.default.svc.cluster.local:8061/prometheus: read tcp 172.30.182.181:53620->172.21.84.238:8061: read: connection reset by peer
```

**Comment by tkatrichenko** [comment]
The problem is that Prometheus can't get metrics from Spring Boot applications which are inside the Service Mesh. It gets `connection reset by peer` error for spring-actuator targets 

If Prometheus and Grafana are inside Service Mesh all is working

Is there some way to make it work with Prometheus which provided by Istio? Maybe some tls options for prometheus job? I tried to use options like this but didn't help
```
- job_name: spring-actuator
  tls_config:
    ca_file: /etc/istio-certs/root-cert.pem
    cert_file: /etc/istio-certs/cert-chain.pem
    key_file: /etc/istio-certs/key.pem
    insecure_skip_verify: true
```

**Comment by douglas-reid** [comment]
There is a way to make Prometheus work with the mesh.

Related discussions:
- https://github.com/istio/istio/issues/7352
- https://discuss.istio.io/t/byo-prometheus-with-mtls/2393

Closing for now. Please re-open if you feel that you were not able to get the directions in those issues working.

**Comment by tkatrichenko** [comment]
Indeed, adding https scheme did the trick. Thank you @douglas-reid 

Just in case, leave the final config here
```
- job_name: spring-actuator
  scheme: https
  tls_config:
    ca_file: /etc/istio-certs/root-cert.pem
    cert_file: /etc/istio-certs/cert-chain.pem
    key_file: /etc/istio-certs/key.pem
    insecure_skip_verify: true
```
