### ISSUE TITLE
More documents for beginners 

### ISSUE THREAD

**Issue by dumindu** [istio/istio#18216]
**Bug description**

1. How to use [minimal option](https://istio.io/docs/setup/install/helm/#option-1-install-with-helm-via-helm-template) with ingress gateway and sidecar-injectors?

2. With **[default setup](https://istio.io/docs/setup/install/helm/#option-1-install-with-helm-via-helm-template)** I followed following tasks

- `kubectl create namespace apiapp`

- `kubectl label ns apiapp istio-injection=enabled`

- Deployed the golang app under apiapp namespace(no issues; can access api via 8000 by port forwarding and can see side containers)
- [x] ConfigMap
- [x] Deployment
- [x] Service (custerIP/default)

- `kubectl apply -f gateway.yaml`
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: apiapp-gateway
  namespace: istio-system
  labels:
    app: apiapp-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
```

- `kubectl apply -f app-virtualservice.yaml`
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: apiapp-app
  namespace: istio-system
  labels:
    app: apiapp-app
spec:
  hosts:
  - "*"
  gateways:
  - apiapp-gateway
  http:
  - match:
    - uri:
      exact: /healthz
    - uri:
      exact: /swagger/doc.json
    route:
    - destination:
        host: apiapp-app
        port:
          number: 8000
```
 
> `kubectl get svc -n istio-system istio-ingressgateway` shows
```
NAME                   TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                                                                                                                                      AGE
istio-ingressgateway   LoadBalancer   10.99.214.146   10.99.214.146   15020:32009/TCP,80:31380/TCP,443:31390/TCP,31400:31400/TCP,15029:30884/TCP,15030:31353/TCP,15031:32500/TCP,15032:30676/TCP,15443:30115/TCP
```
and 
```
export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].port}')
echo $INGRESS_HOST:$INGRESS_PORT
```
shows `10.99.214.146:80`

[x] Docs
[x] Networking
[x] User Experience

**Expected behavior**
- I think while access 10.99.214.146:80/healthz should see valid response.

**Current behavior**
`curl -I http://$INGRESS_HOST:$INGRESS_PORT/healthz`
```
HTTP/1.1 503 Service Unavailable
date: Wed, 23 Oct 2019 08:39:14 GMT
server: istio-envoy
transfer-encoding: chunked

```
And can not see routes in prometheus (`istioctl dashboard prometheus`) -> Status -> Configuration

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
- kubectl version: v1.16.0
- helm version: v2.14.3
- minikube env

**How was Istio installed?**
```
minikube start --memory=16384 --cpus=4

helm init --service-account tiller --output yaml | sed 's@apiVersion: extensions/v1beta1@apiVersion: apps/v1@' | sed 's@  replicas: 1@  replicas: 1\n  selector: {"matchLabels": {"app": "helm", "name": "tiller"}}@' | kubectl apply -f -

kubectl create namespace istio-system

helm template istio-1.3.3/install/kubernetes/helm/istio-init --name istio-init --namespace istio-system | kubectl apply -f - 
```

**Environment where bug was observed (cloud vendor, OS, etc)**
- Fedora Linux
- Minikube

Did I missed any step in the second question? Also like to use minimal setup with gateways. 
Please help me to get solve these issues, due to I'm stuck on this for few days.

Thanks
