### ISSUE TITLE
update ICP CR status field to string

### ISSUE THREAD

**Issue by linsun** [istio/istio#18222]
**Bug description**
Currently it is a few numbers which is not meaningful to users without looking up our docs.

Best to change it to string to be meaningful.

from discussion https://github.com/istio/operator/pull/447

**Comment by howardjohn** [comment]
Would be really useful. Is there a way in proto to have the enum rendered as a string?

**Comment by linsun** [comment]
Haven't found a simple way :-(

@morven kindly pointed me to this change https://github.com/istio/operator/pull/357/files

**Comment by sdake** [comment]
Closing as this appears solved:

```
status:
  status:
    Citadel:
      status: 2
      statusString: HEALTHY
    EgressGateway:
      status: 2
      statusString: HEALTHY
    Galley:
      status: 2
      statusString: HEALTHY
    Grafana:
      status: 2
      statusString: HEALTHY
    IngressGateway:
      status: 2
      statusString: HEALTHY
    Injector:
      status: 2
      statusString: HEALTHY
    Kiali:
      status: 2
      statusString: HEALTHY
    Pilot:
      status: 2
      statusString: HEALTHY
    Policy:
      status: 2
      statusString: HEALTHY
    Prometheus:
      status: 2
      statusString: HEALTHY
    Telemetry:
      status: 2
      statusString: HEALTHY
    Tracing:
      status: 2
      statusString: HEALTHY
    crds:
      status: 2
      statusString: HEALTHY
sdake@beast-01:~$ 
```
