### ISSUE TITLE
Is it possible use of egress rule within Istio to realize a forward proxy?

### ISSUE THREAD

**Issue by Templum** [istio/istio#1824]
Hello,
first of all, I hope that this is the correct place to open this issue (/question).
I currently have a scenario in which I have a couple of services (faas-function) deployed in a specific namespace.  Additional all of them have a special label that indicates them as a lambda function. I want for each of the function using rules to restrict the domains they can reach. Based on my understanding this can be accomplished using Egress Rules.

 For my testing, I created two functions similar implementation only differents beeing the URL they call (http://www.google.com:443 / http://youtube.com:443). And also the EgressRule below.

```yaml
apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: google-egress-rule
spec:
  destination:
    service: www.google.com
  ports:
    - port: 443
      protocol: https
```

Regarding the environment, I have Istio installed on my minikube (0.23.0) running kubernetes (Server: 1.8.0 Client: 1.8.2). I followed the setup instruction for istio provided [here](https://istio.io/docs/setup/kubernetes/quick-start.html#installation-steps) and installed it without auth enabled and with automatic sidecar injection (based on [this](https://istio.io/docs/setup/kubernetes/sidecar-injection.html) instructions). 

Do I have to explicitly block all traffic first and the whitelist domains? Because the youtube caller was also able to communicate correctly. Further is Istio usable as a forwarding proxy? 

Best regards,
Simon
