### ISSUE TITLE
ServiceRole AccessRule Service only works with FQDN

### ISSUE THREAD

**Issue by xeviknal** [istio/istio#18327]
**Bug description**
RBAC not working when defining ServiceRole AccessRule services different than FQDN.
The 
**Expected behavior**
```yaml
kind: ServiceRole
apiVersion: rbac.istio.io/v1alpha1
metadata:
  name: details-reviews-viewer
  namespace: bookinfo
spec:
  rules:
    - methods:
        - GET
      services:
        - details
        - reviews
```

```yaml
kind: ServiceRole
apiVersion: rbac.istio.io/v1alpha1
metadata:
  name: details-reviews-viewer
  namespace: bookinfo
spec:
  rules:
    - methods:
        - GET
      services:
        - ".bookinfo.svc.cluster.local"
```
Both ServiceRoles above should not make service mesh return 403 errors.

Or I expect that the documentation for this end updated. I am fine with only supporting exact service name match.

**Steps to reproduce the bug**
![Screen-recording-_12_](https://user-images.githubusercontent.com/613814/67563468-07e5e880-f721-11e9-93cf-4e0501359b86.gif)

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

> client version: 1.3.3
> control plane version: 1.3.3

> $ oc version
> oc v3.11.0+0cbc58b
> kubernetes v1.11.0+d4cacc0
> features: Basic-Auth GSSAPI Kerberos SPNEGO
> 
> Server https://192.168.42.228:8443
> kubernetes v1.11.0+d4cacc0

**How was Istio installed?**
```
for i in install/kubernetes/helm/istio-init/files/crd*yaml; do oc apply -f $i; done
oc apply -f install/kubernetes/istio-demo.yaml
```
