### ISSUE TITLE
Blacklist select egress traffic

### ISSUE THREAD

**Issue by schmidtp0740** [istio/istio#18336]
**Bug description**
Instead of denying all egress traffic. I would like to allow all egress traffic but blacklist certain endpoints.

Sample config:
```
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: blacklistip
spec:
  compiledAdapter: listchecker
  params:
    # providerUrl: ordinarily black and white lists are maintained
    # externally and fetched asynchronously using the providerUrl.
    overrides: ["8.8.8.8/32"]  # overrides provide a static list
    blacklist: true
    entryType: IP_ADDRESSES
---
apiVersion: config.istio.io/v1alpha2
kind: instance
metadata:
  name: sourceip
spec:
  compiledTemplate: listentry
  params:
    value: source.labels["app"]
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: checkip
spec:
  match: source.labels["app"] == "appName"
  actions:
  - handler: blacklistip
    instances: [ sourceip ]
---
```
**Expected behavior**
Would expect to deny egress traffic to 8.8.8.8 from the pod with the following label

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
kubectl version: 
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7+IKS", GitCommit:"44d102fa84ebb514e817942f5b1090cf54844445", GitTreeState:"clean", BuildDate:"2019-09-24T06:08:41Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

istio version: 1.1.14

**How was Istio installed?**
git clone the repository with branch 1.1.14 and use helm tiller to install
manually did the following to check if policy checks are disabled:
```
$ kubectl -n istio-system get cm istio -o jsonpath="{@.data.mesh}" | grep disablePolicyChecks
disablePolicyChecks: false
```
**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by gargnupur** [comment]
@schmidtp0740 : rather than using white/black listing mechanism, why not use https://istio.io/docs/tasks/traffic-management/egress/wildcard-egress-hosts/ for controlling egress traffic?

**Comment by schmidtp0740** [comment]
@gargnupur WIth that though, it seems as if you can only allow white list traffic by host. Is there a feature in istio to do the opposite. Kind of like the following with network policy but would be nice with dns names:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: test-1
spec:
  podSelector:
    matchLabels:
      app: app-1
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except: 
        - 1.1.1.1/32
```
