### ISSUE TITLE
istioctl analyze false positive for cross namespace Gateway/Virtual Service

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#18366]
File:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: helloworld-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helloworld
  namespace: default
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/helloworld-gateway
  http:
  - match:
    - uri:
        exact: /hello
    route:
    - destination:
        host: helloworld
        port:
          number: 5000
```

Command: `istioctl x analyze file.yaml`
Output:
```
Error [IST0101](VirtualService helloworld.default) Referenced gateway not found: "istio-system/helloworld-gateway"
```

Expected: No errors; this config is valid
