### ISSUE TITLE
EnvoyFilter config size limit

### ISSUE THREAD

**Issue by elvizlai** [istio/istio#18371]
**Describe the feature request**
For k8s annotation, size limit is 256KB.
For large project, proto descriptor is much bigger than the limit, and can not apply for k8s (using replace works).

```

apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: grpc-json-transcoder
  namespace: istio-system
spec:
  filters:
  - listenerMatch:
      portNamePrefix: grpc-web
      listenerType: SIDECAR_INBOUND
    insertPosition:
      index: BEFORE
      relativeTo: envoy.router
    filterName: envoy.grpc_json_transcoder
    filterType: HTTP
    filterConfig:
      autoMapping: true
      services:  
        - xxx.XXXService 
      protoDescriptorBin: 
        LARGE BASE64 DATA
```

**Describe alternatives you've considered**
Is there any other way to config EnvoyFilter? For example pvc?

**Additional context**
