### ISSUE TITLE
Unable to call external service from istio enabled pod

### ISSUE THREAD

**Issue by dheerajjoshim** [istio/istio#18380]
**Bug description**
We have enabled Istio and injected side car. As part of container start up. We try to install some extra packages using `npm install` command. 

`npm install `command fails with following error when istio is injected. `npm` can be reached using a corporate proxy

Error
```
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! network request to https://registry.npmjs.org/upath failed, reason: read ECONNRESET
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /usr/src/node-red/.npm/_logs/2019-10-28T13_59_43_636Z-debug.log
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! network request to https://registry.npmjs.org/js-cache failed, reason: read ECONNRESET
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /usr/src/node-red/.npm/_logs/2019-10-28T14_01_00_072Z-debug.log
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! network request to https://registry.npmjs.org/jsrender failed, reason: read ECONNRESET
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /usr/src/node-red/.npm/_logs/2019-10-28T14_02_16_569Z-debug.log
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN smputil@19.0.0 No repository field.
npm WARN smputil@19.0.0 No license field.

up to date in 1.514s
```

In order to connect to external service, I have created a `ServiceEntry` and `DestinationRule`
But unable to get `npm` install command to work.

ServiceEntry
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: registry-npmjs-servicenetry
  namespace: zd
spec:
  hosts:
  - registry.npmjs.org
  location: MESH_EXTERNAL
  ports:
  - name: https
    number: 443
    protocol: TLS
  resolution: DNS
```
DestinationRule
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: registry-npmjs-destinationrule
  namespace: zd
spec:
  host: registry.npmjs.org
  trafficPolicy:
    tls:
      mode: DISABLE
```

Istio config map 
```
# Set the following variable to true to disable policy checks by the Mixer.
# Note that metrics will still be reported to the Mixer.
disablePolicyChecks: false

# Set enableTracing to false to disable request tracing.
enableTracing: false

# Set accessLogFile to empty string to disable access log.
accessLogFile: "/dev/stdout"
#
# Deprecated: mixer is using EDS
mixerCheckServer: istio-policy.istio-system.svc.cluster.local:9091
mixerReportServer: istio-telemetry.istio-system.svc.cluster.local:9091

# policyCheckFailOpen allows traffic in cases when the mixer policy service cannot be reached.
# Default is false which means the traffic is denied when the client is unable to connect to Mixer.
policyCheckFailOpen: false

# Unix Domain Socket through which envoy communicates with NodeAgent SDS to get
# key/cert for mTLS. Use secret-mount files instead of SDS if set to empty.
sdsUdsPath: ""

# How frequently should Envoy fetch key/cert from NodeAgent.
sdsRefreshDelay: 15s

#
defaultConfig:
  #
  # TCP connection timeout between Envoy & the application, and between Envoys.
  connectTimeout: 10s
  #
  ### ADVANCED SETTINGS #############
  # Where should envoy's configuration be stored in the istio-proxy container
  configPath: "/etc/istio/proxy"
  binaryPath: "/usr/local/bin/envoy"
  # The pseudo service name used for Envoy.
  serviceCluster: istio-proxy
  # These settings that determine how long an old Envoy
  # process should be kept alive after an occasional reload.
  drainDuration: 45s
  parentShutdownDuration: 1m0s
  #
  # The mode used to redirect inbound connections to Envoy. This setting
  # has no effect on outbound traffic: iptables REDIRECT is always used for
  # outbound connections.
  # If "REDIRECT", use iptables REDIRECT to NAT and redirect to Envoy.
  # The "REDIRECT" mode loses source addresses during redirection.
  # If "TPROXY", use iptables TPROXY to redirect to Envoy.
  # The "TPROXY" mode preserves both the source and destination IP
  # addresses and ports, so that they can be used for advanced filtering
  # and manipulation.
  # The "TPROXY" mode also configures the sidecar to run with the
  # CAP_NET_ADMIN capability, which is required to use TPROXY.
  #interceptionMode: REDIRECT
  #
  # Port where Envoy listens (on local host) for admin commands
  # You can exec into the istio-proxy container in a pod and
  # curl the admin port (curl http://localhost:15000/) to obtain
  # diagnostic information from Envoy. See
  # https://lyft.github.io/envoy/docs/operations/admin.html
  # for more details
  proxyAdminPort: 15000
  #
  # Set concurrency to a specific number to control the number of Proxy worker threads.
  # If set to 0 (default), then start worker thread for each CPU thread/core.
  concurrency: 0
  #
  # Zipkin trace collector
  #
  # Mutual TLS authentication between sidecars and istio control plane.
  controlPlaneAuthPolicy: NONE
  #
  # Address where istio Pilot service is running
  discoveryAddress: istio-pilot.istio-system:15007
```

**Expected behavior**
External service should be able to call from istio enabled pod when `ServiceEntry` and `DestinationRules` are created.

**Steps to reproduce the bug**
Create simple pod with npm command and try to do npm install in it.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istioctl version
```
Version: 1.0.6
GitRevision: 98598f88f6ee9c1e6b3f03b652d8e0e3cd114fa2
User: root@5b4ec1b11448
Hub: docker.io/istio
GolangVersion: go1.11
BuildStatus: Clean
```
kubectl version
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**
Through Helm charts

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by dheerajjoshim** [comment]
Since cluster is behind a proxy. Should a `ServiceEntry` and `DestinationRule` be created for proxy server as well?

**Comment by howardjohn** [comment]
Istio 1.0 is not supported, please try on a new version of Istio. How we handle external services has changed. See https://istio.io/blog/2019/announcing-1.1-eol/

**Comment by dheerajjoshim** [comment]
I was able to solve it by creating a service entry for TCP with end point. Nothing else really solved my issue.

Adding sample code here if some one else is stuck

Example Code:
```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: proxy-servicenentry
  namespace: <namespace>
spec:
  addresses:
  - <PROXY_IP>32
  endpoints:
  - address: <PROXY_IP>
  hosts:
  - <PROXY_IP>
  location: MESH_EXTERNAL
  ports:
  - name: tcp
    number: <PROXY_PORT>
    protocol: tcp
  resolution: STATIC
EOF
```
