### ISSUE TITLE
Envoy filter API - per_filter_config support

### ISSUE THREAD

**Issue by mgwizdz-jamf** [istio/istio#18425]
**Describe the feature request**

**Describe alternatives you've considered**

**Additional context**

HI,

I struggle with envoy filters in istio 1.3 version and I've got few issues. Can I add per_filter_config in istio 1.3? If not is there a chance this possibility will be available soon? I mean a configuration like this: [Per-Route Configuration](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/ext_authz_filter#per-route-configuration)

**Comment by rshriram** [comment]
you can add this by matching on specific route and doing a merge operation with a route config that has per filter config

**Comment by mgwizdz-jamf** [comment]
@rshriram thanks for your response. I do it in this way but probably I missed something or I just don't understand it correctly. I did something like this but it doesn't work I mean it deploys correctly but looks like properties weren't added to config.
````apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: by-pass
spec:
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: GATEWAY
      routeConfiguration:
        portNumber: 443
        vhost:
          name: "*:443"
    patch:
      operation: MERGE
      value:
          per_filter_config:
            envoy.ext_authz:
              disabled: true
````

**Comment by wesleyfantinel** [comment]
Try with:
```

kind: EnvoyFilter
metadata:
  name: by-pass
spec:
  configPatches:
  - applyTo: VIRTUAL_HOST
    match:
      context: GATEWAY
      routeConfiguration:
        portNumber: 443
    patch:
      operation: MERGE
      value:
          per_filter_config:
            envoy.ext_authz:
              disabled: true
```

**Comment by hanjunlee** [comment]
@mgwizdz-jamf Hi. I'm also struggle to apply the per-route config `EnvoyFilter`.  In your case, you should specify the route to merge it like below. Basically, the name of route is "[default](https://archive.istio.io/v1.3/docs/reference/config/networking/v1alpha3/envoy-filter/#EnvoyFilter-RouteConfigurationMatch-RouteMatch)". 
```yaml
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: GATEWAY
      routeConfiguration:
        portNumber: 443
        vhost:
          name: "*:443"
          route:
            name: default 
```
And also you should set `match`, `route` field in your route. I hope it would be helpful. If you want to reference my case, please check [this repository](https://github.com/hanjunlee/do-731/blob/master/README.md).
