### ISSUE TITLE
Missing endpoint for a Kubernetes Service with Endpoints and a subset in a DestinationRule

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#18424]
**Bug description**

When you define a subset in a DestinationRule for a Kubernetes Service with Endpoints, the Envoy endpoint is missing for that subset.

**Expected behavior**
There should be an Envoy endpoint for the service with a subset.

**Steps to reproduce the bug**

1. Follow the Kubernetes example for a Service with Endpoints  https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors:

```
kubectl apply -f - <<EOF
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
---
apiVersion: v1
kind: Endpoints
metadata:
  name: my-service
subsets:
  - addresses:
      - ip: 192.0.2.42
    ports:
      - port: 9376
EOF
```

2.  Define a destination rule with a subset:

```
kubectl apply -f  - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: my-service
spec:
  host: my-service
  subsets:
  - name: my-subset
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 80
        tls:
          mode: DISABLE
EOF
```

3.  Define a virtual service to use the subset:

```
kubectl apply -f  - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-service
spec:
  hosts: 
  - my-service
  http:
  - name: my-service-my-subset-route
    route:
    - destination:
        host: my-service
        subset: my-subset
EOF
```

4. Check the pilot logs:
```
kubectl logs -l istio=pilot -n istio-system -c discovery --tail 1000
```

There appears:
```
"ProxyStatus": {
        "pilot_eds_no_instances": {
            "outbound_.80_.my-subset_.my-service.default.svc.cluster.local": {},
            "outbound|80|my-subset|my-service.default.svc.cluster.local": {}
        }
    }
```

Note that the endpoint for the service without the subset appears in the dump of endpoints as expected.

```
 {
        "name": "outbound|80||my-service.default.svc.cluster.local",
        "addedViaApi": true,
        "hostStatuses": [
            {
                "address": {
                    "socketAddress": {
                        "address": "192.0.2.42",
                        "portValue": 9376
                    }
                },
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istio-1.4.0-beta.0

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
