### ISSUE TITLE
Control what mixer attributes Envoy uses to cache its Mixer responses

### ISSUE THREAD

**Issue by josephpeacock** [istio/istio#18445]
**Describe the feature request**

We would like a way to control what mixer attributes Envoy uses to cache its Mixer responses. 

**Describe alternatives you've considered**

We've already implemented a cache in our MixerAdapter, that has a very high cache hit rate. However, even on cache hits we're seeing 4-5ms of latency added purely on the Mixer grpc call. This seems to be in line with Istio's publisher performance numbers, found here: https://istio.io/docs/concepts/performance-and-scalability/. Seemingly the only way to cut that out is by improving the cache hit ratio in Envoy itself.

**Affected product area (please put an X in all that apply)**

[ X ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ X ] Performance and Scalability
[ X ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

We use an internal service to manage/store authorization data controlling which services can talk to each other. To enforce that, we added a MixerAdapter that calls out to our service for this authZ check. That works, but is not performant enough for our use case. So, we'd like to bypass the Mixer grpc call as often as possible.

Looking at Envoy debug logs from istio-proxy, we see the cache key being made up of ```context.protocol, context.reporter.kind, destination.namespace, destination.port, destination.principal, destination.uid, request.method, source.uid```

As the authZ is static within environments, our ideal cache would be limited to exclusively the destination.principal and destination.namespace.

As per the Mixer docs (https://github.com/istio/proxy/blob/master/src/envoy/http/mixer/README.md) ```Mixer server controls which attributes to use for cache keys. It also controls the cache expiration.```
So mixer appears to be the proper place for this enhancement.

**Comment by josephpeacock** [comment]
CC @aattuluri @jwebb49

**Comment by bianpengyuan** [comment]
Does your mixer rule or instance reference those attributes? Mixer should already construct cache key from attributes that are actually being looked up. Also by principal namespace do you mean namespace from source.principal? It so it is weird why that attribute does not show up in your cache key.

**Comment by josephpeacock** [comment]
I edited my description to be a little more specific. It's not that the attributes we care about are missing from the cache key, it's that we would like to exclude the rest. Both the principal and namespace are being incorporated into the existing cache key. But additional cache misses are being triggered by (for example) requests with different methods, although we know a different method will never impact the authorization decision.

**Comment by bianpengyuan** [comment]
Yes, mixer should not include attributes into cache key if it is not used by rule/instance. So you are saying other attributes like `destination.port`, `request.method` are not used anywhere in your config but show up in cache key? That sounds like a bug to me...

**Comment by josephpeacock** [comment]
The short answer is that we do have rules/instances that use these attributes. 

But I think this is where my understanding breaks down. I think my core question is how does the Proxy determine which mixer calls to make synchronously, and which to make asynchronously? I read this in the docs: ```The Envoy sidecar logically calls Mixer before each request to perform precondition checks, and after each request to report telemetry.``` I don't understand how Envoy knows which adapters to call before and after. My understanding from a big picture suggests that Authorization should be a precondition, and metrics a telemetry. But yet I see the `context.reporter.kind ` attribute (which seems to be only in the ```accesslog``` instance, used by the ```stdio``` rule) in the cache key for the precondition call, although that strikes me as something that would be a metric. Are you able to shed any light on that?

My expectation would be the cache keys for precondition checks would consist only of attributes included in the params object of the required instances. Instead, it seems as if all of the attributes used for all of the rules are being combined in the cache key. Perhaps the issue would have been better worded to request an explicit way to exclude attributes from the cache key, or to override the dynamically created cache key in some static way.

**Comment by josephpeacock** [comment]
Thanks for that pointer. I'm doing a little digging on my end as well based on that.

Here's our config: https://gist.github.com/josephpeacock/6490d6f78f50499c514f6fb36a4400c6 

Based on our conversation and looking more closely, my original example of method was a poor one, as ```request.method``` is used for the registry-auth instance. But I'm still concerned that we see the ```context.protocol``` and ```context.reporter.kind``` attributes for the precondition mixer call. 

Also, if the cache key is generated based on all of the referenced attributes, I'm confused as to how ```request.path``` is not included in the cache key, as it is referenced by the registry instance.

**Comment by josephpeacock** [comment]
After some testing on my end, I suspect there may be a bug somewhere in the cache key creation logic. I set up two test services within the mesh, let's call them inbound and backend. I SSH'd into the inbound pod, and curled the backend, measuring the time taken (round-trip) per call. For each new path attempted, the first call would take 11ms, and subsequent calls would take 8-9ms. In addition, I'd see logs on the Policy pod showing a precondition call for the 11ms ones but not the 8-9ms ones.

```
curl backend.global/d -w %{time_total} &&  echo \n
0.011n
curl backend.global/e -w %{time_total} &&  echo \n
0.011n
curl backend.global/e -w %{time_total} &&  echo \n
0.009n
curl backend.global/e -w %{time_total} &&  echo \n
0.011n
curl backend.global/f -w %{time_total} &&  echo \n
0.011n
curl backend.global/f -w %{time_total} &&  echo \n
0.009n
curl backend.global/f -w %{time_total} &&  echo \n
0.009n
```

The 11ms calls corresponded with logs looking like this on Policy:

```adapters	Registry Handler Invoked	{"adapter": "registry-auth-handler.istio-system"}```

During this time, here was my list of rules:
```
kubeattrgenrulerule      66m
registry-rule            66m
tcpkubeattrgenrulerule   66m
```

To try to isolate the impact, I deleted the Registry rule (our custom authorization check), and discovered that the pattern was no longer present, all requests took 8-9ms and no logging was showing up in Mixer.

I then restored the Registry rule, but deleted the two attrgenrulerules (So our authorization rule is the only one present), and once again saw that all requests took 8-9ms and no logging was showing up in Mixer.

In other words, a combination of the attribute generation rules and the authorization rule combines to trigger cache misses on a path change. Both of the attribute generation rules point to the following instance (note compiledType kubernetes):
```
apiVersion: config.istio.io/v1alpha2
kind: instance
metadata:
  annotations:
  creationTimestamp: "2019-11-01T21:46:49Z"
  generation: 1
  labels:
    app: mixer
    chart: mixer
    heritage: Tiller
    release: istio
  name: attributes
  namespace: istio-system
spec:
  attributeBindings:
    destination.container.name: $out.destination_container_name | "unknown"
    destination.ip: $out.destination_pod_ip | ip("0.0.0.0")
    destination.labels: $out.destination_labels | emptyStringMap()
    destination.name: $out.destination_pod_name | "unknown"
    destination.namespace: $out.destination_namespace | "default"
    destination.owner: $out.destination_owner | "unknown"
    destination.serviceAccount: $out.destination_service_account_name | "unknown"
    destination.uid: $out.destination_pod_uid | "unknown"
    destination.workload.name: $out.destination_workload_name | "unknown"
    destination.workload.namespace: $out.destination_workload_namespace | "unknown"
    destination.workload.uid: $out.destination_workload_uid | "unknown"
    source.ip: $out.source_pod_ip | ip("0.0.0.0")
    source.labels: $out.source_labels | emptyStringMap()
    source.name: $out.source_pod_name | "unknown"
    source.namespace: $out.source_namespace | "default"
    source.owner: $out.source_owner | "unknown"
    source.serviceAccount: $out.source_service_account_name | "unknown"
    source.uid: $out.source_pod_uid | "unknown"
    source.workload.name: $out.source_workload_name | "unknown"
    source.workload.namespace: $out.source_workload_namespace | "unknown"
    source.workload.uid: $out.source_workload_uid | "unknown"
  compiledTemplate: kubernetes
  params:
    destination_port: destination.port | 0
    destination_uid: destination.uid | ""
    source_ip: source.ip | ip("0.0.0.0")
    source_uid: source.uid | ""

```

I plan to dive a little deeper to try to figure out why we may be paying this performance penalty. In the meantime, I have two main questions:
1. What's the downside to removing these attribute generation rules? Are they crucial for metrics or authorization rules to work? 
2. Is this expected behavior? If not could we change this issue into a bug?
