### ISSUE TITLE
Support gzip compression

### ISSUE THREAD

**Issue by flatmap13** [istio/istio#18443]
Envoy has support for [gzip compression](https://www.envoyproxy.io/docs/envoy/v1.8.0/configuration/http_filters/gzip_filter), would it be possible for Istio to expose the configuration of this feature for the ingress/egress gateways and the sidecars? Ideally, the gzip compression config should be selectively applicable to specific internal or external services.

**Comment by rshriram** [comment]
Example ?

**Comment by flatmap13** [comment]
For example, if I have service A and B running in a k8s/istio cluster and C running somewhere externally. I would like to be able to specify that payloads to/from A and C can be compressed but not to/from B. Not sure if this is the example you're looking for though.

**Comment by Stono** [comment]
My example from the other post:
`[service-a] --plain --> [envoy-a] ---- gzip ----> [envoy-b] --plain--> [envoy-a]`

**Comment by hendrikmaus** [comment]
Here is how I think one can activate gzip compression on the ingress-gateway:

```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ingressgateway-gzip
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
              subFilter:
                name: 'envoy.router'
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.gzip
          config:
            remove_accept_encoding_header: true
            compression_level: DEFAULT
```

I used:
- istio 1.3.4
- config root namespace is `istio-system` (default)
- pods are labeled `istio: ingressgateway` (default)

Once the resource is submitted, pilot starts pushing out new configs.

To verify, dump the config of one of the ingress gateway pods and `grep` for `gzip`.

```sh
kubectl -n istio-system exec -it $(kubectl -n istio-system get pod -l istio=ingressgateway -o jsonpath='{.items[0].metadata.name}') -- curl -s localhost:15000/config_dump | grep gzip
```

Next, request a service through the ingress gateway and set the `accept-encoding` header with `gzip,deflate`:

```sh
curl -H "accept-encoding: gzip,deflate" ...
```

Omit the `accept-encoding` header to get a plain text response.

---

I did not yet test this filter in production, I am very curious to the impact of activating the  filter.

**Comment by howardjohn** [comment]
@Stono @flatmap13 can either of you test the EnvoyFilter approach and make sure it meets your needs, then we can probably add first class support in an Istio API if so?

**Comment by hendrikmaus** [comment]
I put the above config live before christmas; has been working fine so far.

I changed the `compression_level` to `BEST` to achieve a higher compression rate. Unfortunately I do not have metrics on the CPU consumption change handy right now, but the effect was insignificant.

**Comment by aaron-trout** [comment]
That `EnvoyFilter` config works a treat, thanks!

**Comment by howardjohn** [comment]
Not stale

**Comment by blackbaud-brandonstirnaman** [comment]
It would be great to have this without requiring an EnvoyFilter as that introduces a lot of potential complexity for teams when they go to upgrade istio/envoy. We'd really prefer not to 'break the glass' by configuring envoy directly so right now we don't have GZIP compression enabled. Long term I'm not sure that is sustainable for us.

**Comment by kyessenov** [comment]
Ref #26627

**Comment by pisto** [comment]
What about compression for other kinds of stream within the mesh (bare TCP)?

**Comment by baraeb92** [comment]
Not stale

**Comment by howardjohn** [comment]
not stale

**Comment by mstrYoda** [comment]
How about supporting gzip compression in VirtualService definition? So let's say I want to enabled gzip only for one endpoint, I would define a VirtualService rule and configure gzip compression for that endpoint. Also users would be free of maintaining EnvoyFilter.

**Comment by fatedier** [comment]
not stale

**Comment by tomasopye** [comment]
what is the status of this? do we still need to add our own envoy filters or is this supported by an istio api now?

**Comment by kyessenov** [comment]
It's not supported by native API.
cc @costinm

**Comment by tomasopye** [comment]
not the response I want, but thank you. envoy filter it is

**Comment by mstrYoda** [comment]
@kyessenov WDYT about development to add gzip option to VirtualService Custom Resource Definition?

**Comment by sayjeyhi** [comment]
Isn't there any `brotli` implementation?

**Comment by hanjunlee** [comment]
@sayjeyhi Did you implement `brotli` compression? Unfortunately, I've tried it with EnvoyFilter, but it doesn't work.

**Comment by Kuzbekov** [comment]
@sayjeyhi Here is working example for brotli:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: brotli
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: istio-ingressgateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
              subFilter:
                name: 'envoy.router'
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.compressor
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor
            compressor_library:
              name: text_optimized
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.compression.brotli.compressor.v3.Brotli
                quality: 5
                encoder_mode: DEFAULT
                window_bits: 18
                input_block_bits: 24
                chunk_size: 4096
            response_direction_config:
              remove_accept_encoding_header: true
              common_config:
                enabled:
                  default_value: true
                  runtime_key: response_direction_config_enabled
                content_type:
                  - application/json
                  - text/css
                  - text/html
                  - text/plain
                  - text/xml
                min_content_length: 800
            request_direction_config:
              common_config:
                enabled:
                  default_value: false
                  runtime_key: request_direction_config_enabled```

**Comment by pgangwani** [comment]
> @sayjeyhi Here is working example for brotli:
> 
> ```
> apiVersion: networking.istio.io/v1alpha3
> kind: EnvoyFilter
> metadata:
>   name: brotli
>   namespace: istio-system
> spec:
>   workloadSelector:
>     labels:
>       istio: istio-ingressgateway
>   configPatches:
>     - applyTo: HTTP_FILTER
>       match:
>         context: GATEWAY
>         listener:
>           filterChain:
>             filter:
>               name: "envoy.http_connection_manager"
>               subFilter:
>                 name: 'envoy.router'
>       patch:
>         operation: INSERT_BEFORE
>         value:
>           name: envoy.filters.http.compressor
>           typed_config:
>             '@type': type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor
>             compressor_library:
>               name: text_optimized
>               typed_config:
>                 '@type': type.googleapis.com/envoy.extensions.compression.brotli.compressor.v3.Brotli
>                 quality: 5
>                 encoder_mode: DEFAULT
>                 window_bits: 18
>                 input_block_bits: 24
>                 chunk_size: 4096
>             response_direction_config:
>               remove_accept_encoding_header: true
>               common_config:
>                 enabled:
>                   default_value: true
>                   runtime_key: response_direction_config_enabled
>                 content_type:
>                   - application/json
>                   - text/css
>                   - text/html
>                   - text/plain
>                   - text/xml
>                 min_content_length: 800
>             request_direction_config:
>               common_config:
>                 enabled:
>                   default_value: false
>                   runtime_key: request_direction_config_enabled```
> ```

Thanks buddy

**Comment by zirain** [comment]
FYI: compression for stats endpoint is supported in https://github.com/istio/istio/pull/47997.
For common usage, still need a API.

**Comment by sintasy** [comment]
Has anyone figured out how to enable compression for a specific host on istio gateway? For example, if gateway handles multiple virtual services and hostnames, how can you enable compression for just one of the virtual services?

**Comment by gaurav517** [comment]
This would be very useful for us too. GZIP at virtual service level gives lots of flexibility. Any idea when this might be coming?  Thanks.

**Comment by shaoxt** [comment]
Would like to find any solution for this feature.
A (asking for request compression)     --> C
B (doesn't need request compression)--> C

How can I configure this case ?

try  both "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua" and "type.googleapis.com/envoy.extensions.filters.http.header_to_metadata.v3.Config".  Seems neither works

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: compression-filter
  namespace: services-gateway-apigw-usw2-prf-shao
spec:
  workloadSelector:
    labels:
      app: intuit-gateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_OUTBOUND
        listener:
          portNumber: 80
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.lua
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
            inlineCode: |
              function envoy_on_request(request_handle)
                -- Check if the 'X-No-Compression' header is present and set to 'true'
                -- local compression_header = request_handle:headers():get("X-Request-Compression")
                -- if compression_header == "true" then
                -- Disable compression dynamically for this request
                request_handle:streamInfo():setDynamicMetadata("envoy.filters.http.compressor", "request_compressor_enabled", "true")
                -- end
              end
#          name: envoy.filters.http.header_to_metadata
#          typed_config:
#            "@type": type.googleapis.com/envoy.extensions.filters.http.header_to_metadata.v3.Config
#            request_rules:
#              - header: X-Request-Compression
#                on_header_present:
#                  metadata_namespace: envoy.filters.http.compressor
#                  key: request_compressor_enabled
#                  type: STRING
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_OUTBOUND
        listener:
          portNumber: 80
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.compressor
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor
            response_direction_config:
              common_config:
                enabled:
                  default_value: false
                  runtime_key: response_compressor_enabled
                min_content_length: 2048
                content_type:
                  - application/hal+json
                  - application/atom+xml
                  - application/javascript
                  - application/x-javascript
                  - application/json
                  - application/rss+xml
                  - application/vnd.ms-fontobject
                  - application/x-font-ttf
                  - application/x-web-app-manifest+json
                  - application/xhtml+xml
                  - application/xml
                  - font/opentype
                  - image/svg+xml
                  - image/x-icon
                  - text/css
                  - text/html
                  - text/plain
                  - text/xml
                  - text/x-component
              disable_on_etag_header: true
            request_direction_config:
              common_config:
                enabled:
                  default_value: false
                  runtime_key: request_compressor_enabled
            compressor_library:
              name: text_optimized
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.compression.gzip.compressor.v3.Gzip
                compression_level: COMPRESSION_LEVEL_4
                compression_strategy: DEFAULT_STRATEGY
```
