### ISSUE TITLE
HTTPS readyness-liveness probe rewrite

### ISSUE THREAD

**Issue by haf-afa** [istio/istio#18467]
Related: https://github.com/istio/istio/pull/17941

```
      containers:
      - image: docker.elastic.co/kibana/kibana:7.4.0
        imagePullPolicy: IfNotPresent
        name: kibana
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /login
            port: 5601
            scheme: HTTPS
```

with 

```
		--set sidecarInjectorWebhook.rewriteAppHTTPProbe=true \
```

causes

```
monitoring       1s          Warning   Unhealthy                      pod/apm-kb-7dff4cb579-5b2dz                                Readiness probe failed: Get https://10.1.1.61:5601/login: remote error: tls: handshake failure
```

**Bug description**

**Expected behavior**

That rewriting of probes work for HTTPS

**Steps to reproduce the bug**

```
	helm template ./helm/istio \
		--name istio --namespace istio-system \
		--values ./helm/istio/values.yaml \
		--set sidecarInjectorWebhook.enabled=true \
		--set sidecarInjectorWebhook.rewriteAppHTTPProbe=true \
		--set global.mtls.enabled=true \
		--set global.tracer.zipkin.address=jaeger-collector.monitoring:9411 \
		--set global.gateways.enabled=false \
		--set global.k8sIngress.enabled=false \
		--set gateways.istio-ingressgateway.enabled=false \
		--set pilot.traceSampling=100.0 \
		--set kiali.enabled=true \
		--set kiali.createDemoSecret=true \
		--set kiali.dashboard.jaegerURL=jaeger.fou.test \
		--set grafana.enabled=true \
		> ./istio/k8s/base/template.yaml
```

then 

```
$ kubectl apply -f ./istio/k8s/base/template.yaml
```

And for Elastic:

```
$ kubectl apply -f https://download.elastic.co/downloads/eck/1.0.0-beta1/all-in-one.yaml
$ cat <<EOF >apm.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    istio-injection: enabled
---
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: apm
  namespace: monitoring
spec:
  version: 7.4.0
  http:
    tls:
      # TODO: either https://stackoverflow.com/questions/58417177/generate-certificate-for-http-service-from-istio
      # OR TODO: enable istio sidecar injection in the monitoring namespace
      # Relates to: https://github.com/jaegertracing/jaeger-operator/pull/114
      selfSignedCertificate:
        disabled: true

  nodeSets:
  - name: violet
    count: 1
    volumeClaimTemplates:
    - metadata:
        name: apm-es-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
---
apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: apm
  namespace: monitoring
spec:
  version: 7.4.0
  count: 1
  elasticsearchRef:
    name: apm
EOF
$ kubectl apply -f apm.yaml
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

1.2.8 since it starts

**How was Istio installed?**

See repro

**Environment where bug was observed (cloud vendor, OS, etc)**

Docker Desktop, Windows

**Comment by incfly** [comment]
```
monitoring       1s          Warning   Unhealthy                      pod/apm-kb-7dff4cb579-5b2dz                                Readiness probe failed: Get https://10.1.1.61:5601/login: remote error: tls: handshake failure
```

where this log is coming from? kubelet or pilot-agent?

**Comment by incfly** [comment]
Can you attach the full deployment YAML for the workload? You only have the container section. I deployed as 

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      containers:
      - image: docker.elastic.co/kibana/kibana:7.4.0
        imagePullPolicy: IfNotPresent
        name: kibana
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /login
            port: 5601
            scheme: HTTPS
```

The app container fails to get up, I saw log from the container 

```yaml
{"type":"log","@timestamp":"2019-10-30T21:27:15Z","tags":["warning","elasticsearch","admin"],"pid":7,"message":"No living connections"}
{"type":"log","@timestamp":"2019-10-30T21:27:15Z","tags":["warning","elasticsearch","admin"],"pid":7,"message":"Unable to revive connection: http://elasticsearch:9200/"}
{"type":"log","@timestamp":"2019-10-30T21:27:15Z","tags":["warning","elasticsearch","admin"],"pid":7,"message":"No living connections"}
{"type":"log","@timestamp":"2019-10-30T21:27:17Z","tags":["warning","elasticsearch","admin"],"pid":7,"message":"Unable to revive connection: http://elasticsearch:9200/"}
{"type":"log","@timestamp":"2019-10-30T21:27:17Z","tags":["warning","elasticsearch","admin"],"pid":7,"message":"No living connections"}
{"type":"log","@timestamp":"2019-10-30T21:27:20Z","tags":["warning","elasticsearch","admin"],"pid":7,"message":"Unable to revive connection: http://elasticsearch:9200/"}
{"type":"log","@timestamp":"2019-10-30T21:27:20Z","tags":["warning","elasticsearch","admin"],"pid":7,"message":"No living connections"}
{"type":"log","@timestamp":"2019-10-30T21:27:22Z","tags":["warning","elasticsearch","admin"],"pid":7,"message":"Unable to revive connection: http://elasticsearch:9200/"}
{"type":"log","@timestamp":"2019-10-30T21:27:22Z","tags":["warning","elasticsearch","admin"],"pid":7,"message":"No living connections"}
{"type":"log","@timestamp":"2019-10-30T21:27:25Z","tags":["warning","elasticsearch","admin"],"pid":7,"message":"Unable to revive connection: http://elasticsearch:9200/"}
{"type":"log","@timestamp":"2019-10-30T21:27:25Z","tags":["warning","elasticsearch","admin"],"pid":7,"message":"No living connections"}
{"type":"log","@timestamp":"2019-10-30T21:27:27Z","tags":["warning","elasticsearch","admin"],"pid":7,"message":"Unable to revive connection: http://elasticsearch:9200/"}
{"type":"log","@timestamp":"2019-10-30T21:27:27Z","tags":["warning","elasticsearch","admin"],"pid":7,"message":"No living connections"}
{"type":"log","@timestamp":"2019-10-30T21:27:30Z","tags":["warning","elasticsearch","admin"],"pid":7,"message":"Unable to revive connection: http://elasticsearch:9200/"}
{"type":"log","@timestamp":"2019-10-30T21:27:30Z","tags":["warning","elasticsearch","admin"],"pid":7,"message":"No living connections"}
{"type":"log","@timestamp":"2019-10-30T21:27:32Z","tags":["warning","elasticsearch","admin"],"pid":7,"message":"Unable to revive connection: http://elasticsearch:9200/"}
{"type":"log","@timestamp":"2019-10-30T21:27:32Z","tags":["warning","elasticsearch","admin"],"pid":7,"message":"No living connections"}
{"type":"log","@timestamp":"2019-10-30T21:27:35Z","tags":["warning","elasticsearch","admin"],"pid":7,"message":"Unable to revive connection: http://elasticsearch:9200/"}
{"type":"log","@timestamp":"2019-10-30T21:27:35Z","tags":["warning","elasticsearch","admin"],"pid":7,"message":"No living connections"}
{"type":"log","@timestamp":"2019-10-30T21:27:37Z","tags":["warning","elasticsearch","admin"],"pid":7,"message":"Unable to revive connection: http://elasticsearch:9200/"}
{"type":"log","@timestamp":"2019-10-30T21:27:37Z","tags":["warning","elasticsearch","admin"],"pid":7,"message":"No living connections"}
{"type":"log","@timestamp":"2019-10-30T21:27:39Z","tags":["warning","elasticsearch","data"],"pid":7,"message":"Unable to revive connection: http://elasticsearch:9200/"}
{"type":"log","@timestamp":"2019-10-30T21:27:39Z","tags":["warning","elasticsearch","data"],"pid":7,"message":"No living connections"}
{"type":"log","@timestamp":"2019-10-30T21:27:39Z","tags":["license","warning","xpack"],"pid":7,"message":"License information from the X-Pack plugin could not be obtained from Elasticsearch for the [data] cluster. Error: No Living connections"}
{"type":"log","@timestamp":"2019-10-30T21:27:40Z","tags":["warning","elasticsearch","admin"],"pid":7,"message":"Unable to revive connection: http://elasticsearch:9200/"}
{"type":"log","@timestamp":"2019-10-30T21:27:40Z","tags":["warning","elasticsearch","admin"],"pid":7,"message":"No living connections"}
{"type":"log","@timestamp":"2019-10-30T21:27:43Z","tags":["warning","elasticsearch","admin"],"pid":7,"message":"Unable to revive connection: http://elasticsearch:9200/"}
{"type":"log","@timestamp":"2019-10-30T21:27:43Z","tags":["warning","elasticsearch","admin"],"pid":7,"message":"No living connections"}

```
