### ISSUE TITLE
Abort specific URI endpoints

### ISSUE THREAD

**Issue by njfix6** [istio/istio#18477]
**Describe the feature request**
In a virtual service, I would like to abort on an endpoint for a specific URI. For example, if I want to abort the uri `/endpoint`, I could be able to add the following config, and block the endpoint `/endpoint`and return a status code 400:
```
http:
- fault:
    abort:
      httpStatus: 400
      percentage:
        value: 1
  match:
  - uri:
      prefix: /endpoint
  route:
  - destination:
      host: servicethatexists.default.svc.cluster.local
      port:
        number: 80
```
So this would return a 400 whenever the `/endpoint` is hit for that service. This is very useful to shutdown endpoints that are causing issues to our database. 

**Describe alternatives you've considered**
Right now I have a workaround by matching that uri to a service that doesn't exist. I have to add the following config:
```
http:
- match:
    - uri:
        prefix: /sandboxes
    route:
    - destination:
        host: doesnotexist.default.svc.cluster.local
        port:
          number: 80
```
so it returns a 503 without hitting our servers but I really want to be able to control the status code. 

**Additional context**

**Comment by njfix6** [comment]
Nevermind this works but not very clear in the documentation: 
```
- fault:
    abort:
      httpStatus: 400
      percentage:
        value: 1
  match:
  - uri:
      prefix: /endpoint
  route:
  - destination:
      host: thisserviceexists.default.svc.cluster.local
      port:
        number: 80
```

**Comment by howardjohn** [comment]
Does this not work today? It seems like it should based on docs at https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#HTTPFaultInjection-Delay

**Comment by njfix6** [comment]
@howardjohn I tried this and I can't get it to work. Maybe you have better luck?

**Comment by njfix6** [comment]
```
http:
- match:
    - uri:
        prefix: "/endpoint"
    route:
    - destination:
        host: {{ .Values.name }}.{{ .Values.environment }}.svc.cluster.local
        port:
          number: 80
    fault:
      abort:
        percentage:
          value: 1.0
        httpStatus: 400
  - route:
    - destination:
        host: {{ .Values.name }}.{{ .Values.environment }}.svc.cluster.local
        port:
          number: 80
    retries:
      attempts: 3
      perTryTimeout: 250ms
      retryOn: gateway-error,connect-failure,refused-stream
    headers:
      request:
        set:
          x-forwarded-proto: https
          x-forwarded-port: "443"
```
for context this is my exact config http config.

**Comment by njfix6** [comment]
I am also running istio 1.3.0

**Comment by njfix6** [comment]
Oh gosh, I found my issue. I assumed the percentage was on a sliding scale, 1.0 being 100%. I updated it to the following at it worked:
```
fault:
  abort:
    percentage:
      value: 100.0
    httpStatus: 400
```
