### ISSUE TITLE
operator patch fails on new leaf

### ISSUE THREAD

**Issue by tangiel** [istio/istio#18495]
**Bug description**

**Expected behavior**
Running mesh manifest generate with a patch that creates a new map entry should work.

**Steps to reproduce the bug**
Run mesh manifest generate with the following ICP:

```yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  profile: default
  telemetry:
    enabled: true
    components:
      telemetry:
        k8s:
          overlays:
            - kind: ServiceAccount
              name: istio-mixer-service-account
              patches:
                - path: metadata.annotations
                  value:
                    foo: bar
```

The output is `patch error: path not found at element annotations in path metadata.annotations`.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.3.3, 1.4-release

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
