### ISSUE TITLE
VirtualService match: same uri, differ methods

### ISSUE THREAD

**Issue by tkatrichenko** [istio/istio#18506]
Is it possible to map VirtualService to different services using same uri but different methods?

I'm trying to do something like this
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-vs
spec:
  hosts:
  - "example.com"
  gateways:
  - my-gateway
  http:
  - match:
    - method:
        exact: GET
    - uri:
        regex: \/api\/test
    route:
    - destination:
        host: service1
        port:
          number: 8080
  - match:
    - uri:
        regex: \/api\/test
    - method:
        exact: POST
    route:
    - destination:
        host: service2
        port:
          number: 8070
```
For the GET method it works, but for POST says `method not allowed`. 
If I comment out the first match and leave only POST, then POST works

So Istio takes only first entry with same uri and ignores the second

** Istio version: 1.3.3 **

**Comment by tkatrichenko** [comment]
It looks like my typo. Should be like this (without - before method)
```
  - match:
    - uri:
        regex: \/api\/test
      method:
        exact: POST
```
