### ISSUE TITLE
Prometheus metric duplication possible

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#1853]
@douglas-reid commented on [Tue Sep 19 2017](https://github.com/istio/old_mixer_repo/issues/1322)

More investigation/thought needed:

It is possible to configure multiple prometheus handlers that use the same Registry.  If each of these handlers use the same names for metrics, then the data recorded in the metrics will be a union of each of the values sent to the handlers.

This can lead to duplication in the following scenario:
1. handlerA is sent `requestcount.metric.istio-config-default` for a Report() for destination service `foo.bar.svc.cluster.local`
2. handlerB is sent `requestcount.metric.bar` for the *same* Report() for destination service `foo.bar.svc.cluster.local`

The end result would be:
- `request_count{"destination_service":"foo.bar.svc.cluster.local",...} 2`

We should figure out what we want the story to be for this sort of global/local collision.

---

@geeknoid commented on [Fri Sep 22 2017](https://github.com/istio/old_mixer_repo/issues/1322#issuecomment-331580136)

The issue is that the namespace of the metric isn't being respected, right? Seems like if we maintain the name consistently with its namespace, then no collision would take place. Or I'm missing something...

---

@douglas-reid commented on [Fri Sep 22 2017](https://github.com/istio/old_mixer_repo/issues/1322#issuecomment-331585162)

@geeknoid my thoughts: it isn't respected by... operators? prometheus? validation? I'm not clear where the responsibility lies.

If you write config that uses the same name for prometheus metrics connected to two different, fully qualifed instances, you will see this issue.  Example:

```
# config provided by operator A
kind: prometheus
metadata:
   name: handlerA
   namespace: istio-config-default
spec:
  metrics:
  - name: request_count
    instance_name: requestcount.metric.istio-config-default
...
---
# config provided by operator B
...
kind: prometheus
metadata:
   name: handlerB
   namespace: other
spec:
  metrics:
  - name: request_count
    instance_name: requestcount.metric.other
```

In that case, is the duplication intentional?  And how would Mixer or an adapter be able to distinguish?  It isn't an error, currently at least, because the metric shapes are precisely the same for the same name (and iirc we use a `RegisterOrGet` call).

We *could* put namespaces into the generated prometheus metric names when not in the `configDefaultNamespace` or something (to enable easy writing of dashboards, etc.). We could also just say "make sure your name is scoped appropriately".

Anyway, I'm not sure how immediate the concern is... just something I noticed in testing.

---

@mandarjog commented on [Fri Sep 22 2017](https://github.com/istio/old_mixer_repo/issues/1322#issuecomment-331587622)

We added a way for the operator to provide an `outbound` name to the metric. This name appears inside prometheus and is a prometheus friendly name. The name obtained by post processing `requestcount.metric.istio-config-default` is ugly and not prometheus like.

In the above examples, even though instance names are different, the operators chose to assign the same prometheus metric name to those two metrics, and that is the problem.

At present prometheus is a singleton, and the outbound names must be unique.

We could address that by not making prometheus adapter a singleton. It has additional challenges because the external prometheus needs to be told where to scrape from.
