### ISSUE TITLE
Zero request Rate-Limiting is leaking 0.3% requests under load

### ISSUE THREAD

**Issue by marcusschiesser** [istio/istio#18551]
**Bug description**

Adding a `maxAmount: 0` rate-limiting policy to all services, about 0.3% of all requests are still served under load

**Expected behavior**

All requests would return with HTTP code 429, none would return with HTTP code 200.

**Steps to reproduce the bug**

1. Deploy a `maxAmount: 0` policy affecting all services 

```yaml
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: quotahandler
  namespace: istio-system
spec:
  compiledAdapter: memquota
  params:
    quotas:
    - name: requestcountquota.instance.istio-system
      maxAmount: 0
      validDuration: 1s
---
apiVersion: config.istio.io/v1alpha2
kind: instance
metadata:
  name: requestcountquota
  namespace: istio-system
spec:
  compiledTemplate: quota
  params:
    dimensions:
      source: request.headers["x-forwarded-for"] | "unknown"
      destination: destination.labels["app"] | destination.service.name | "unknown"
      destinationVersion: destination.labels["version"] | "unknown"
---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpec
metadata:
  name: request-count
  namespace: istio-system
spec:
  rules:
  - quotas:
    - charge: 1
      quota: requestcountquota
---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpecBinding
metadata:
  name: request-count
  namespace: istio-system
spec:
  quotaSpecs:
  - name: request-count
    namespace: istio-system
  services:
  - service: '*'
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: quota
  namespace: istio-system
spec:
  actions:
  - handler: quotahandler
    instances:
    - requestcountquota
```

2. Create a namespace with sidecar injection enabled
`kubectl create ns 3-tier && kubectl label ns 3-tier istio-injection=enabled`

3. Deploy our local load test 
> Note: I tried to reproduce this problem with the Istio Bookinfo application running a simple load test, but it is not reproducible. In case you can provide a cluster, I can install the test load used

4. Query requests with response code 200 using Prometheus
Query: `istio_requests_total{response_code="200",destination_service_name!~"istio.*"}` (The `destination_service_name` attribute is filtering out the requests sent to `istio-system`)
![image](https://user-images.githubusercontent.com/17126/68014565-e6f63800-fcca-11e9-9ebe-592b907e8467.png)

5. Query requests with response code 429 using Prometheus
Query: `istio_requests_total{response_code="429",destination_service_name!~"istio.*"}`
![image](https://user-images.githubusercontent.com/17126/68014743-5704be00-fccb-11e9-9dcd-0104ead764e7.png)

6. Compare the two results
![image](https://user-images.githubusercontent.com/17126/68014817-7c91c780-fccb-11e9-9144-aa7fadf1cdbf.png)
![image](https://user-images.githubusercontent.com/17126/68015097-5587c580-fccc-11e9-9cab-dd00de6e1b8a.png)
For this example route, the ratio of requests with code 200 to requests with code 429 is about 0.3%

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
# istioctl version --remote
client version: 1.3.2
citadel version: 1.3.2
egressgateway version: 1.3.2
galley version: 1.3.2
ingressgateway version: 1.3.2
pilot version: 1.3.2
policy version: 1.3.2
sidecar-injector version: 1.3.2
telemetry version: 1.3.2
# kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
`kubectl apply -f install/kubernetes/istio-demo.yaml`

**Environment where bug was observed (cloud vendor, OS, etc)**
Loca two-node cluster running CentOS 7.6 and installed via kubeadm
