### ISSUE TITLE
If there is a container that doesn't expose any port, istio-proxy won't start

### ISSUE THREAD

**Issue by jaesquivel** [istio/istio#18594]
If there is a container that doesn't export any port, istio-proxy won't start, 

2019-11-04T14:32:36.150148Z	error	Failed to generate bootstrap config: invalid character ',' looking for beginning of value

**Expected behavior**
Ignore the container with no network connectivity

**Steps to reproduce the bug**
Create a POD with two containers, one of them with no ports, istio-proxy won't start and will show an error:
2019-11-04T14:32:36.150148Z	error	Failed to generate bootstrap config: invalid character ',' looking for beginning of value

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istioctl version --remote
client version: 1.4.0-beta.0
control plane version: 1.4.0-beta.0
data plane version: 1.4.0-beta.0 (9 proxies)

kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-21T22:32:40Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
helm

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS

**Comment by howardjohn** [comment]
Can you provide a reproduction? I applied this yaml:
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: alpine
  name: alpine
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine
  strategy:
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - args:
        - sleep
        - "100000"
        image: alpine
        imagePullPolicy: Always
        name: alpine2
      - args:
        - sleep
        - "10000000000000000"
        image: alpine
        name: alpine
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 16Mi
```
