### ISSUE TITLE
TrafficPolicy ISTIO_MUTUAL not honored when using SDS ingressgateway

### ISSUE THREAD

**Issue by k0ffee** [istio/istio#18596]
**Bug description**

Istio ingressgateway responds with Error 503 to request to working service when SDS secrets are enabled for the gateway.

**Expected behavior**

mTLS TLS handshake succeeds and ingressgateway responds with HTTP status-code "200 OK".

**Steps to reproduce the bug**

Setup Istio via helm chart with option
```
  set {
    name  = "gateways.istio-ingressgateway.sds.enabled"
    value = "true"
  }
```
Setup chart-manager to supply a public TLS certificate in kubernets secret named "ingressgateway-certs" and reference that in the gateway resource:

```
---
apiVersion: v1
kind: Namespace
metadata:
  name: frontend
  labels:
    istio-injection: enabled
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-v1
  labels:
    app: frontend
    version: v1
  namespace: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      containers:
        - name: frontend
          image: docker.io/tinocode/frontend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    service: frontend
  namespace: frontend
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: frontend
    version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: frontend
  namespace: frontend
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "*"
      tls:
        mode: SIMPLE
        credentialName: ingressgateway-certs
        minProtocolVersion: TLSV1_2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend
  namespace: frontend
spec:
  hosts:
    - "*"
  gateways:
    #
    # Use the istio ingress gateway resource in this namespace:
    #
    - frontend
  http:
    - headers:
        response:
          set:
            Strict-Transport-Security: max-age=31536000
      route:
        - destination:
            host: frontend
            port:
              number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: frontend
  namespace: frontend
spec:
  host: frontend
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    loadBalancer:
      consistentHash:
        httpCookie:
          name: route
          ttl: 172800s
```

Now an incoming request to the ingressgateway is sent via mTLS to frontend service, which responds in plain HTTP (Error 400 bad request), resulting in an obvious SSL version number mismatch:

```
root@istio-ingressgateway-84df7b96f9-znjsw:/# tcpdump -pieth0 -vvxX port 8080

16:38:43.578065 IP (tos 0x0, ttl 64, id 25765, offset 0, flags [DF], proto TCP (6), length 60)
    istio-ingressgateway-84df7b96f9-znjsw.43284 > 10.56.0.6.8080: Flags [S], cksum 0x14ac (incorrect -> 0xea5f), seq 507683413, win 28400, options [mss 1420,sackOK,TS val 2054739621 ecr 0,nop,wscale 7], length 0
	0x0000:  4500 003c 64a5 4000 4006 c199 0a38 0008  E..<d.@.@....8..
	0x0010:  0a38 0006 a914 1f90 1e42 a255 0000 0000  .8.......B.U....
	0x0020:  a002 6ef0 14ac 0000 0204 058c 0402 080a  ..n.............
	0x0030:  7a78 d6a5 0000 0000 0103 0307            zx..........
16:38:43.578152 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 60)
    10.56.0.6.8080 > istio-ingressgateway-84df7b96f9-znjsw.43284: Flags [S.], cksum 0x14ac (incorrect -> 0x38b1), seq 1155023901, ack 507683414, win 28160, options [mss 1420,sackOK,TS val 3920707558 ecr 2054739621,nop,wscale 7], length 0
	0x0000:  4500 003c 0000 4000 4006 263f 0a38 0006  E..<..@.@.&?.8..
	0x0010:  0a38 0008 1f90 a914 44d8 441d 1e42 a256  .8......D.D..B.V
	0x0020:  a012 6e00 14ac 0000 0204 058c 0402 080a  ..n.............
	0x0030:  e9b1 3fe6 7a78 d6a5 0103 0307            ..?.zx......
16:38:43.578160 IP (tos 0x0, ttl 64, id 25766, offset 0, flags [DF], proto TCP (6), length 52)
    istio-ingressgateway-84df7b96f9-znjsw.43284 > 10.56.0.6.8080: Flags [.], cksum 0x14a4 (incorrect -> 0xd477), seq 1, ack 1, win 222, options [nop,nop,TS val 2054739621 ecr 3920707558], length 0
	0x0000:  4500 0034 64a6 4000 4006 c1a0 0a38 0008  E..4d.@.@....8..
	0x0010:  0a38 0006 a914 1f90 1e42 a256 44d8 441e  .8.......B.VD.D.
	0x0020:  8010 00de 14a4 0000 0101 080a 7a78 d6a5  ............zx..
	0x0030:  e9b1 3fe6                                ..?.
16:38:43.578261 IP (tos 0x0, ttl 64, id 25767, offset 0, flags [DF], proto TCP (6), length 257)
    istio-ingressgateway-84df7b96f9-znjsw.43284 > 10.56.0.6.8080: Flags [P.], cksum 0x1571 (incorrect -> 0xec8c), seq 1:206, ack 1, win 222, options [nop,nop,TS val 2054739621 ecr 3920707558], length 205: HTTP
	0x0000:  4500 0101 64a7 4000 4006 c0d2 0a38 0008  E...d.@.@....8..
	0x0010:  0a38 0006 a914 1f90 1e42 a256 44d8 441e  .8.......B.VD.D.
	0x0020:  8018 00de 1571 0000 0101 080a 7a78 d6a5  .....q......zx..
	0x0030:  e9b1 3fe6 1603 0100 c801 0000 c403 03ca  ..?.............
	0x0040:  d580 eba5 bdac 86cc d8eb 18d2 aaf3 3c26  ..............<&
	0x0050:  dbdf de22 da93 2d88 bb20 70d8 40dd 1900  ..."..-...p.@...
	0x0060:  001c c02b cca9 c02f cca8 c009 c013 009c  ...+.../........
	0x0070:  002f c02c c030 c00a c014 009d 0035 0100  ./.,.0.......5..
	0x0080:  007f 0000 003a 0038 0000 356f 7574 626f  .....:.8..5outbo
	0x0090:  756e 645f 2e38 3038 305f 2e5f 2e66 726f  und_.8080_._.fro
	0x00a0:  6e74 656e 642e 6672 6f6e 7465 6e64 2e73  ntend.frontend.s
	0x00b0:  7663 2e63 6c75 7374 6572 2e6c 6f63 616c  vc.cluster.local
	0x00c0:  0017 0000 ff01 0001 0000 0a00 0600 0400  ................
	0x00d0:  1d00 1700 0b00 0201 0000 2300 0000 1000  ..........#.....
	0x00e0:  0800 0605 6973 7469 6f00 0d00 1400 1204  ....istio.......
	0x00f0:  0308 0404 0105 0308 0505 0108 0606 0102  ................
	0x0100:  01                                       .
16:38:43.578278 IP (tos 0x0, ttl 64, id 33518, offset 0, flags [DF], proto TCP (6), length 52)
    10.56.0.6.8080 > istio-ingressgateway-84df7b96f9-znjsw.43284: Flags [.], cksum 0x14a4 (incorrect -> 0xd3a3), seq 1, ack 206, win 229, options [nop,nop,TS val 3920707558 ecr 2054739621], length 0
	0x0000:  4500 0034 82ee 4000 4006 a358 0a38 0006  E..4..@.@..X.8..
	0x0010:  0a38 0008 1f90 a914 44d8 441e 1e42 a323  .8......D.D..B.#
	0x0020:  8010 00e5 14a4 0000 0101 080a e9b1 3fe6  ..............?.
	0x0030:  7a78 d6a5                                zx..
16:38:43.578457 IP (tos 0x0, ttl 64, id 33519, offset 0, flags [DF], proto TCP (6), length 118)
    10.56.0.6.8080 > istio-ingressgateway-84df7b96f9-znjsw.43284: Flags [P.], cksum 0x14e6 (incorrect -> 0xe91b), seq 1:67, ack 206, win 229, options [nop,nop,TS val 3920707559 ecr 2054739621], length 66: HTTP, length: 66
	HTTP/1.1 400 Bad Request
	content-length: 0
	connection: close
	
	0x0000:  4500 0076 82ef 4000 4006 a315 0a38 0006  E..v..@.@....8..
	0x0010:  0a38 0008 1f90 a914 44d8 441e 1e42 a323  .8......D.D..B.#
	0x0020:  8018 00e5 14e6 0000 0101 080a e9b1 3fe7  ..............?.
	0x0030:  7a78 d6a5 4854 5450 2f31 2e31 2034 3030  zx..HTTP/1.1.400
	0x0040:  2042 6164 2052 6571 7565 7374 0d0a 636f  .Bad.Request..co
	0x0050:  6e74 656e 742d 6c65 6e67 7468 3a20 300d  ntent-length:.0.
	0x0060:  0a63 6f6e 6e65 6374 696f 6e3a 2063 6c6f  .connection:.clo
	0x0070:  7365 0d0a 0d0a                           se....

```

```
unix% kubectl logs -n istio-system istio-ingressgateway-84df7b96f9-znjsw -c istio-proxy

[2019-11-04 16:41:33.780][24][debug][connection] [external/envoy/source/common/network/connection_impl.cc:704] [C30] connecting to 10.56.0.6:8080
[2019-11-04 16:41:33.781][24][debug][connection] [external/envoy/source/common/network/connection_impl.cc:713] [C30] connection in progress
[2019-11-04 16:41:33.781][24][debug][connection] [external/envoy/source/common/network/connection_impl.cc:552] [C30] connected
[2019-11-04 16:41:33.781][24][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:167] [C30] handshake error: 2
[2019-11-04 16:41:33.781][24][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:167] [C30] handshake error: 1
[2019-11-04 16:41:33.781][24][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:200] [C30] TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
[2019-11-04 16:41:33.781][24][debug][connection] [external/envoy/source/common/network/connection_impl.cc:190] [C30] closing socket: 0
```

```
unix% istioctl experimental auth check -n frontend frontend-v1-846cc67bf-j7tzz

Checked 2/31 listeners with node IP 10.56.0.6.
LISTENER            CERTIFICATE     mTLS (MODE)     JWT (ISSUERS)     RBAC (RULES)
10.56.0.6_8080      none            no (none)       no (none)         no (none)
10.56.0.6_15020     none            no (none)       no (none)         no (none)

Checked 36/41 outbound clusters.
HOST:PORT                                     CERTIFICATE                   VALIDATE PEER CERTIFICATE
kubernetes.default:443                        none                          none
frontend.frontend:8080                        /etc/certs/cert-chain.pem     spiffe://cluster.local/ns/frontend/sa/default
istio-citadel.istio-system:8060               none                          none
istio-citadel.istio-system:15014              none                          none
istio-galley.istio-system:443                 none                          none
istio-galley.istio-system:9901                none                          none
istio-galley.istio-system:15014               none                          none
istio-ingressgateway.istio-system:80          none                          none
istio-ingressgateway.istio-system:443         none                          none
istio-ingressgateway.istio-system:15020       none                          none
istio-ingressgateway.istio-system:15029       none                          none
istio-ingressgateway.istio-system:15030       none                          none
istio-ingressgateway.istio-system:15031       none                          none
istio-ingressgateway.istio-system:15032       none                          none
istio-ingressgateway.istio-system:15443       none                          none
istio-ingressgateway.istio-system:31400       none                          none
istio-pilot.istio-system:8080                 none                          none
istio-pilot.istio-system:15010                none                          none
istio-pilot.istio-system:15011                none                          none
istio-pilot.istio-system:15014                none                          none
istio-policy.istio-system:9091                none                          none
istio-policy.istio-system:15004               /etc/certs/cert-chain.pem     spiffe://cluster.local/ns/istio-system/sa/istio-mixer-service-account
istio-policy.istio-system:15014               none                          none
istio-sidecar-injector.istio-system:443       none                          none
istio-sidecar-injector.istio-system:15014     none                          none
istio-telemetry.istio-system:9091             none                          none
istio-telemetry.istio-system:15004            /etc/certs/cert-chain.pem     spiffe://cluster.local/ns/istio-system/sa/istio-mixer-service-account
istio-telemetry.istio-system:15014            none                          none
istio-telemetry.istio-system:42422            none                          none
istiocoredns.istio-system:53                  none                          none
default-http-backend.kube-system:80           none                          none
heapster.kube-system:80                       none                          none
kube-dns.kube-system:53                       none                          none
metrics-server.kube-system:443                none                          none
sealed-secrets.kube-system:8080               none                          none
tiller-deploy.kube-system:44134               none                          none
```

Connections to frontend service succeed if DestinationRule has "trafficPolicy.tls.mode: DISABLED" set, which is not the desired setting though.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
unix% istioctl version --remote
client version: unknown
control plane version: 1.3.4
unix% kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:43:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.9", GitCommit:"6c1e92d07f5717440f751666d4aad6943015d3cb", GitTreeState:"clean", BuildDate:"2019-10-11T23:14:17Z", GoVersion:"go1.11.13b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

Terraform via helm-provider (terraform-provider-helm_v0.10.4).

```
variable "istio_version" {
  description = "See https://gcsweb.istio.io/gcs/istio-release/releases"
  type        = string
  default     = "1.3.4"
}

variable "istio_url" {
  description = "Current storage location of Istio releases."
  type        = string
  default     = "https://storage.googleapis.com/istio-release/releases"
}

locals {
  base_url   = "${var.istio_url}/${var.istio_version}/charts"
  istio_init = "${local.base_url}/istio-init-${var.istio_version}.tgz"
  istio      = "${local.base_url}/istio-${var.istio_version}.tgz"
}

resource helm_release "istio-init" {
  count = var.use_istio == "helm" ? 1 : 0

  name      = "istio-init"
  namespace = "istio-system"
  chart     = local.istio_init

  depends_on = [
    kubernetes_cluster_role_binding.tiller,
    kubernetes_namespace.istio-system,
  ]
}

resource helm_release "istio" {
  count = var.use_istio == "helm" ? 1 : 0

  name      = "istio"
  namespace = "istio-system"
  chart     = local.istio

  set {
    name  = "global.podDNSSearchNamespaces[0]"
    value = "global"
  }

  set {
    name  = "global.multiCluster.enabled"
    value = "true"
  }

  set {
    name  = "global.controlPlaneSecurityEnabled"
    value = "true"
  }

  set {
    name  = "security.selfSigned"
    value = "false"
  }

  set {
    name  = "prometheus.enabled"
    value = "false"
  }

  set {
    name  = "istiocoredns.enabled"
    value = "true"
  }

  set {
    name  = "gateways.istio-ingressgateway.sds.enabled"
    value = "true"
  }

  set {
    name  = "global.mtls.enabled"
    value = "true"
  }

  set {
    name  = "global.outboundTrafficPolicy.mode"
    value = "REGISTRY_ONLY"
  }

  set {
    name  = "sidecarInjectorWebhook.rewriteAppHTTPProbe"
    value = "true"
  }

  depends_on = [
    kubernetes_namespace.istio-system,
    kubernetes_cluster_role_binding.tiller,
    helm_release.istio-init,
  ]
}
```

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE
