### ISSUE TITLE
Telemetry v2: 1.4 stackdriver protobuf assert

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#18614]
```
2019-11-04T21:46:12.755368Z	info	Envoy proxy is ready
[libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/map.h:1060] CHECK failed: it != end(): key not found: gcp_location
[Envoy (Epoch 0)] [2019-11-04 21:46:15.073][92][critical][main] [external/envoy/source/exe/terminate_handler.cc:13] std::terminate called! (possible uncaught exception, see trace)
[Envoy (Epoch 0)] [2019-11-04 21:46:15.073][92][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:70] Backtrace (use tools/stack_decode.py to get line numbers):
[Envoy (Epoch 0)] [2019-11-04 21:46:15.073][92][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:71] Envoy version: e16fdd1ac73cfccdebc1502c50c678110c56db37/1.12.0-dev/Modified/RELEASE/BoringSSL
[Envoy (Epoch 0)] [2019-11-04 21:46:15.080][92][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #0: Envoy::TerminateHandler::logOnTerminate()::$_0::operator()() [0x192c468]
[Envoy (Epoch 0)] [2019-11-04 21:46:15.086][92][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #1: [0x192c379]
[Envoy (Epoch 0)] [2019-11-04 21:46:15.092][92][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #2: __cxxabiv1::__terminate() [0x1c1edd6]
[Envoy (Epoch 0)] [2019-11-04 21:46:15.092][92][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:83] Caught Aborted, suspect faulting address 0x53900000011
[Envoy (Epoch 0)] [2019-11-04 21:46:15.092][92][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:70] Backtrace (use tools/stack_decode.py to get line numbers):
[Envoy (Epoch 0)] [2019-11-04 21:46:15.092][92][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:71] Envoy version: e16fdd1ac73cfccdebc1502c50c678110c56db37/1.12.0-dev/Modified/RELEASE/BoringSSL
[Envoy (Epoch 0)] [2019-11-04 21:46:15.092][92][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #0: __restore_rt [0x7f192e76d890]
[Envoy (Epoch 0)] [2019-11-04 21:46:15.099][92][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #1: [0x192c379]
[Envoy (Epoch 0)] [2019-11-04 21:46:15.099][92][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #2: __cxxabiv1::__terminate() [0x1c1edd6]
2019-11-04T21:46:15.280474Z	error	Epoch 0 exited with error: signal: aborted (core dumped)
2019-11-04T21:46:15.280512Z	info	No more active epochs, terminating
```

**Comment by jplevyak** [comment]
The backtrace is not particularly useful.  Do you have a core?

**Comment by bianpengyuan** [comment]
Mandar mentioned this happens when he turns on edge, which leads to this line:
https://github.com/istio/proxy/blob/787a566773980c28bb3cffd54af3fb6256031c5a/extensions/stackdriver/edges/edge_reporter.cc#L74

**Comment by kyessenov** [comment]
at() crashes on missing key. I think it needs `find()` first.

**Comment by mandarjog** [comment]
I do not think the value is missing from node metadata.
Can you check ?
```yaml
   node:
      build_version: e16fdd1ac73cfccdebc1502c50c678110c56db37/1.12.0-dev/Modified/RELEASE/BoringSSL
      cluster: svc00-0.service-graph00
      id: sidecar~10.44.12.238~svc00-0v1-f9f68896d-x6fgp.service-graph00~service-graph00.svc.cluster.local
      locality:
        region: us-central1
        zone: us-central1-f
      metadata:
        CLUSTER_ID: Kubernetes
        CONFIG_NAMESPACE: service-graph00
        EXCHANGE_KEYS: NAME,NAMESPACE,INSTANCE_IPS,LABELS,OWNER,PLATFORM_METADATA,WORKLOAD_NAME,CANONICAL_TELEMETRY_SERVICE,MESH_ID,SERVICE_ACCOUNT
        INCLUDE_INBOUND_PORTS: '8080'
        INSTANCE_IPS: 10.44.12.238
        INTERCEPTION_MODE: REDIRECT
        ISTIO_PROXY_SHA: istio-proxy:d065af8de7024757825ee6ebd7552025f962a6ae
        ISTIO_VERSION: 1.5-alpha.533892bde31c3a9a622d22885d3577be1de07a8b
        LABELS:
          app: svc00-0
          pod-template-hash: f9f68896d
          role: service
          version: v1
        MESH_ID: mixologist-142215/us-central1/cls1407
        NAME: svc00-0v1-f9f68896d-x6fgp
        NAMESPACE: service-graph00
        OWNER: kubernetes://api/apps/v1/namespaces/service-graph00/deployments/svc00-0v1
        PLATFORM_METADATA:
          gcp_gce_instance_id: '2818901967593627868'
          gcp_gke_cluster_name: cls1407
          gcp_location: us-central1
          gcp_project: mixologist-142215
        POD_NAME: svc00-0v1-f9f68896d-x6fgp
        POD_PORTS: '[{"containerPort":8080,"protocol":"TCP"}]'
        SERVICE_ACCOUNT: default
        WORKLOAD_NAME: svc00-0v1
        app: svc00-0
        pod-template-hash: f9f68896d
        role: service
        version: v1
```
