### ISSUE TITLE
Multiple ports in service causes Envoy's high CPU load when deploying

### ISSUE THREAD

**Issue by nak3** [istio/istio#18632]
**Bug description**

- When creating services that have multiple ports in `spec.port`, __all__ envoy process in the cluster causes high load at the same time.
- The CPU load increase approximately linearly by the number of ports in the svc.
- Knative Serving deploys `100 svc * (4 ports svc + 2 ports svc + 1 ports svc)` on e2e test. It  produces `Envoy proxy is NOT ready` error after more than 20 svc are deployed. 

**Expected behavior**

- envoy's CPU should not be increased so high even if service with multiple ports are deployed.

**Steps to reproduce the bug**

1. Create a testing ns `bug`

```
$ kubectl create ns bug
```

<details>
<summary>2. Deploy a service to watch CPU stats</summary>

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: bug
  labels:
    app: httpbin
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: bug
  labels:
    app: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80
EOF
```

</details>

3. Run top command in `istio-proxy` of httpbin pod deployed at step-2.

```
$ kubectl exec  -n bug -it httpbin-XXXX-XXXX -c istio-proxy top
```

<details>
<summary>4. Deploy services with multiple ports to see envoy's CPU stats</summary>

e.g. Create 50 svc with 5 ports. (You don't need pods/deplyments, but only svc can produce the issue.)

```
for i in {1..50}; do
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: cpu-load-$i
  namespace: bug
  labels:
    app: bug
spec:
  clusterIP: 172.20.30.$i   ### PLEASE REPLACE YOUR SVC'S IP RANGE
  ports:
  - name: h0
    port: 80
    protocol: TCP
    targetPort: 80
  - name: h1
    port: 81
    protocol: TCP
    targetPort: 80
  - name: h2
    port: 82
    protocol: TCP
    targetPort: 81
  - name: h3
    port: 83
    protocol: TCP
    targetPort: 82
  - name: h4
    port: 84
    protocol: TCP
    targetPort: 84
  selector:
    serving.knative.dev/revisionUID: 59e06fe8-ffa4-11e9-a938-02431cc3d6d0
  sessionAffinity: None
  type: ClusterIP
EOF
done
```

</details>

5. Envoy causes high CPU load during deploying svc.

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
   14 istio-p+  20   0  489276 374120  18888 R  83.0  4.6   5:27.70 envoy
```

6. Also a lot of `Envoy proxy is NOT ready error` below are found:

```
$ kubectl  -n bug logs httpbin-69b458bb76-jk4w5 -c istio-proxy 
...
2019-11-05T10:04:42.270637Z	info	Envoy proxy is NOT ready: failed to get server info: failed retrieving Envoy stats: Get http://127.0.0.1:15000/server_info: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2019-11-05T10:04:44.270096Z	info	Envoy proxy is NOT ready: failed to get server info: failed retrieving Envoy stats: Get http://127.0.0.1:15000/server_info: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2019-11-05T10:04:46.270233Z	info	Envoy proxy is NOT ready: failed to get server info: failed retrieving Envoy stats: Get http://127.0.0.1:15000/server_info: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

Istio 1.3.3 / k8s 1.14

<details>
<summary>command output</summary>

```
$ istioctl version --remote
client version: 1.3.2
cluster-local-gateway version:
cluster-local-gateway version:
citadel version: 1.3.3
galley version: 1.3.3
ingressgateway version: 1.3.3
ingressgateway version: 1.3.3
pilot version: 1.3.3
pilot version: 1.3.3
policy version: 1.3.3
sidecar-injector version: 1.3.3
telemetry version: 1.3.3

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.0-alpha.0.1451+896c901684e774", GitCommit:"896c901684e774169dbd477aecd880df1be6bdd0", GitTreeState:"clean", BuildDate:"2019-06-25T04:30:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

**How was Istio installed?**

Here is the [template](https://github.com/knative/serving/blob/cc391e43969a91f642becba86645c531cddd32e9/third_party/istio-1.3.3/istio.yaml)

**Environment where bug was observed (cloud vendor, OS, etc)**

- Kubernetes on AWS, but I'm sure it does not matter.
