### ISSUE TITLE
Unable to access external services/URLs

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [istio/istio#18634]
**Bug description**
Can't access any external website over HTTPs from my service container. I am getting this error 
`curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol`

**Steps to reproduce the bug**
I have created a service that uses port 8080. I created a gateway and virtual service like:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: test-gateway
  namespace: tools
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
        privateKey: /etc/istio/ingressgateway-certs/tls.key
      hosts:
        - "testurl.com"
    - port:
        number: 8080
        name: jenkins-http
        protocol: HTTP
      tls:
        httpsRedirect: true
      hosts:
        - "testurl.com"
```

```yaml

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-virtualservice
  namespace: tools
spec:
  hosts:
    - "testurl.com"
  gateways:
    - test-gateway
  http:
    - route:
        - destination:
            host: test

```
Now i want to allow the service `test` to be able to access any external URL (google, github anything) I don't want to restrict it.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Kubectl:  Client v1.15.3, Server v1.15.5

**How was Istio installed?**
Deployed via helm chart (v1.1.0). 
With the following values 
```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: istio
  namespace: istio-system
spec:
  releaseName: istio
  chart:
    repository: https://gcsweb.istio.io/gcs/istio-prerelease/prerelease/1.1.0/1.1.0/charts/
    name: istio
    version: 1.1.0
  values:
    global:
      enableTracing: true
    mixer:
      telemetry:
        resources:
          requests:
            cpu: 100m
            memory: 500m
    pilot:
      traceSampling: 100
    prometheus:
      enabled: false
    tracing:
      enabled: true
```

![test](https://user-images.githubusercontent.com/18264334/68206591-ea513280-ffee-11e9-8dc1-676de7f0784a.png)
