### ISSUE TITLE
Feature Request - quota handlers read `maxAmount` from instance value

### ISSUE THREAD

**Issue by feisuzhu** [istio/istio#18631]
**Describe the feature request**
`maxAmount` in quota handlers can only be assigned statically, and we want to lift this limitation.
We plan to put rate limiting info in JWT claims,  and found no way to use that info.

**Describe alternatives you've considered**
Custom out-of-process adapter, not acceptable since it will impact performance.

**Additional context**

**Comment by feisuzhu** [comment]
I have time budget for implementing this so if this seems acceptable pls let me know

**Comment by feisuzhu** [comment]
Example

```yaml
---
apiVersion: config.istio.io/v1alpha2
kind: instance
metadata:
  name: quota-rps
  namespace: serving
spec:
  compiledTemplate: quota
  params:
    dimensions:
      user: destination.labels["serving.openbayes.com/user"] | "unknown"
      project: destination.labels["serving.openbayes.com/project"] | "unknown"
      subject: request.auth.claims["sub"] | "unknown"
      x-quota-max-amount: request.auth.claims["rps_limit"] | 0
---
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: quota-redis
  namespace: serving
spec:
  compiledAdapter: redisquota
  params:
    redisServerUrl: openbayes-serving-controller-quota-redis:6379
    connectionPoolSize: 10
    quotas:
    - name: quota-rps.instance.serving
      maxAmountFromInstance: x-quota-max-amount  # HERE
      validDuration: 30s
      bucketDuration: 9s
      rateLimitAlgorithm: ROLLING_WINDOW
      overrides:
      - dimensions:
          user: ratings
          project: ratings

        maxAmount: 50
      - dimensions:
          destination: ratings
        maxAmountFromInstance: x-quota-max-amount  # HERE TOO
```
