### ISSUE TITLE
Grafana/prometheus really hard to configure with operator

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#18648]
Here is my config to get grafana and prometheus working:

```yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  name: istio
  namespace: istio-operator
spec:
  unvalidatedValues:
    prometheus:
      resources:
        limits:
          cpu: 6000m
          memory: 32G
        requests:
          cpu: 1000m
          memory: 4G

  values:
    grafana:
      enabled: true
```

These should be first class components

**Comment by mabushey** [comment]
I just want the damn yaml for Grafana and Prometheus!

**Comment by ostromart** [comment]
@howardjohn is this still an issue? we've updated the values schema i believe.

**Comment by howardjohn** [comment]
I think this is fixed

**Comment by linsun** [comment]
Just for the record - since someone else is also asking... the resources for prometheus can be configured via a resource blob under Prometheus thus the value can be read from here:  https://github.com/istio/operator/blob/master/data/profiles/default.yaml

Examples:

```
    prometheus:
      enabled: true
      replicaCount: 1
      hub: docker.io/prom
      tag: v2.12.0
      retention: 6h
      resources:
        limits:
          cpu: 6000m
          memory: 32G
        requests:
          cpu: 1000m
          memory: 4G
```

if none is specified, global resource will be used.

@howardjohn @ostromart pls correct me if I'm wrong here.    cc @kramvan1
