### ISSUE TITLE
Allow configuring header_key_format for envoy-proxy

### ISSUE THREAD

**Issue by igcherkaev** [istio/istio#18672]
**Describe the feature request**

Allow configuring HeaderKeyFormat in envoy-proxy. See https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/protocol.proto#envoy-api-msg-core-http1protocoloptions and https://github.com/envoyproxy/envoy/pull/8499 for details

**Describe alternatives you've considered**

Forcing third party libs to expect lower-cased headers is, unfortunately, impossible at this time.

**Additional context**

Istio is using envoy-proxy to intercept http calls. When it does that it also brings all headers to lower-case. Some [legacy and not only] apps/libs don't expect that. The only workaround for now, seems like, is turn off istio side car proxy container.

**Comment by bobvanderlinden** [comment]
What is the status of this issue? Is it possible to set `header_key_format` for instance through LUA?

**Comment by greenu** [comment]
You can compile custom version of **galley** image or wait until patch above is released to update Envoy API. 

To compile just clone this repo, checkout release tag, apply patch merged above and do `GOOS=linux make docker`.  You have to have `make` and `docker` installed. Doing this on MacOS outside of container works well. Update your istio installation with custom istio/galley image.

After that use manifest below:
```
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: normalize-headers
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: NETWORK_FILTER # http connection manager is a filter in Envoy
    match:
      # if context omitted then this applies to both sidecars and gateways
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager"
          http_protocol_options: 
            header_key_format:
              proper_case_words: {}
```

**Comment by kylebevans** [comment]
I'm using 1.5.1, have applied an EnvoyFilter to a CLUSTER in the SIDECAR_INBOUND context, but when i watch the network traffic inside the actual service container (jira), it still has all lowercase headers.

**EnvoyFilter:**
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: fisher-jira-proper-case-headers-prod
  labels:
      app.kubernetes.io/instance: fisher-jira-prod
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: fisher-jira-proper-case-headers-prod
      helm.sh/chart: fisher-jira-1.3.25
spec:
  workloadSelector:
    labels:
      app: fisher-jira-prod
  configPatches:
  - applyTo: CLUSTER
    match:
      context: SIDECAR_INBOUND
      cluster:
        name: "inbound|8080|http|fisher-jira-prod.prod.svc.cluster.local"
    patch:
      operation: MERGE
      value:
        http_protocol_options:
          header_key_format:
            proper_case_words: {}
```

**istioctl output:**

```
{
        "name": "inbound|8080|http|fisher-jira-prod.prod.svc.cluster.local",
        "type": "STATIC",
        "connectTimeout": "10s",
        "loadAssignment": {
            "clusterName": "inbound|8080|http|fisher-jira-prod.prod.svc.cluster.local",
            "endpoints": [
                {
                    "lbEndpoints": [
                        {
                            "endpoint": {
                                "address": {
                                    "socketAddress": {
                                        "address": "127.0.0.1",
                                        "portValue": 8080
                                    }
                                }
                            }
                        }
                    ]
                }
            ]
        },
        "circuitBreakers": {
            "thresholds": [
                {
                    "maxConnections": 4294967295,
                    "maxPendingRequests": 4294967295,
                    "maxRequests": 4294967295,
                    "maxRetries": 4294967295
                }
            ]
        },
        "httpProtocolOptions": {
            "headerKeyFormat": {
                "properCaseWords": {}
            }
        }
    }
```

Am I doing something wrong?
Thanks
