### ISSUE TITLE
traffic shifting when fault

### ISSUE THREAD

**Issue by elvizlai** [istio/istio#18736]
**Describe the feature request**

Is there any guide to configure traffic shifting when fault?

For destination experimental, when subset canary offline, traffic should go to release

For example:
```
      route:
        - destination:
            host: experimental
            subset: canary
            port:
              number: 6443
          falut:
             to another destination release
```

**Comment by howardjohn** [comment]
Please search the docs for locality load balancing - on mobile so I cannot link it

**Comment by elvizlai** [comment]
@hanahmily thanks, canary and release are in the same namespace and same region/zone.(maybe same node) Not all pod/service need shifting, but some of it

**Comment by howardjohn** [comment]
I don't think this is supported today

**Comment by elvizlai** [comment]
@hanahmily  maybe something like dynamic priority?

**Comment by howardjohn** [comment]
Subsets form different envoy clusters. Right now you cannot load balancer between two clusters in Envoy. This is tracked in https://github.com/envoyproxy/envoy/issues/7454. Once that is supported this could be feasible, until then nothing we can do.

**Comment by elvizlai** [comment]
@hanahmily  opps, maybe some misunderstanding, subsets are in same cluster,same istio and same namespace, but deployment are NOT same version.

what i want to do is  

header match x=v1 try deployment v1 first, if not aviable, using v2  

no such header using v2 directly.

**Comment by howardjohn** [comment]
By cluster here I mean Envoy cluster not Kubernetes cluster. Each subset (version) forms it's own cluster. So you can't load balancer across two subsets

**Comment by elvizlai** [comment]
```
      route:
        - destination:
            host: experimental-hack
            subset: canary
            port:
              number: 6443
          weight: 100
        - destination:
            host: experimental-hack
            subset: release
            port:
              number: 6443
          weight: 0
```

@howardjohn OK, so right now, no plan or strategy to configure weight dynamic?
