### ISSUE TITLE
istio.io/client-go: Issue with repeated elements when performing DeepCopyObject

### ISSUE THREAD

**Issue by mhofstetter** [istio/istio#18737]
**Bug description**

Performing a `DeepCopyObject` on generated types in the library `istio.io/client-go`results in duplication of all repeated elements (e.g. slices).

**Expected behavior**

The deepCopy of the object is an actual deepCopy without duplication of repeated elements.

**Steps to reproduce the bug**

1. Create an istio resource with repeated elements e.g. `ClusterRbacConfig` with multiple included namespaces.

```
kubectl apply -f - << EOF
apiVersion: rbac.istio.io/v1alpha1
kind: ClusterRbacConfig
metadata:
  name: default
spec:
  inclusion:
    namespaces:
    - ns1
    - ns2
  mode: ON_WITH_INCLUSION
EOF
```

2. Perform a `DeepCopyObject()` on a istio.io/client-go resource.

```
func main() {
	kubeconfig := os.Getenv("KUBECONFIG")
	restConfig, _ := clientcmd.BuildConfigFromFlags("", kubeconfig)
	ic, _ := versionedclient.NewForConfig(restConfig)

	crc, _ := ic.RbacV1alpha1().ClusterRbacConfigs().Get("default", metav1.GetOptions{})
	fmt.Printf("%v \n", crc.Spec.GetInclusion().Namespaces)

	crcCopy := crc.DeepCopyObject().(*v1alpha1.ClusterRbacConfig)
	fmt.Printf("%v \n", crcCopy.Spec.GetInclusion().Namespaces)
}
```

--> OUTPUT 

```
Original: [ns1 ns2] 
Copy: [ns1 ns2 ns1 ns2] 
```

**Analysis**

It seems that the combination of the assignment of in and out in the generated deepcopy file of the kubernetes type (e.g. https://github.com/istio/client-go/blob/master/pkg/apis/rbac/v1alpha1/zz_generated.deepcopy.gen.go#L13) and the usage of the proto.merge function in the deepcopy file of the generated api type (e.g. https://github.com/istio/api/blob/master/rbac/v1alpha1/rbac_deepcopy.gen.go#L98) is the problem. 

The doc from the proto.merge function says that `Elements of repeated fields will be appended.`

**Related issues**

* https://github.com/istio/istio/issues/8772
* https://github.com/istio/istio/issues/17600
