### ISSUE TITLE
Headless Service + GRPC connection failure

### ISSUE THREAD

**Issue by cmanzi** [istio/istio#18758]
**Bug description**

When using a headless Service with a StatefulSet, gRPC connections to the SS pods fail with the following error message: `rpc error: code = Internal desc = server closed the stream without sending trailers`. 

I have tried adding ServiceEntries for the headless services to no avail. I have also tried replacing `grpc` with both `tcp` and `https` in the port names. Below is an example of the resources being used:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: thanos-receive
  name: thanos-receive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-receive
  serviceName: thanos-receive
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      labels:
        app: thanos-receive
    spec:
      containers:
      - args:
        - receive
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:10902
        - --remote-write.address=0.0.0.0:19291
        - --objstore.config=$(OBJSTORE_CONFIG)
        - --tsdb.path=/var/thanos/receive
        - --label=replica="$(NAME)"
        - --label=receive="true"
        env:
        - name: NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OBJSTORE_CONFIG
          valueFrom:
            secretKeyRef:
              key: thanos.yaml
              name: thanos-objstore-config
        image: quay.io/thanos/thanos:v0.8.1
        name: thanos-receive
        ports:
        - containerPort: 10901
          name: grpc
        - containerPort: 10902
          name: http
        - containerPort: 19291
          name: http-rw
        readinessProbe:
          httpGet:
            path: /-/ready
            port: 10902
            scheme: HTTP
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 75m
            memory: 128Mi
        volumeMounts:
        - mountPath: /var/thanos/receive
          name: thanos-receive-data
          readOnly: false
      volumes:
      - emptyDir: {}
        name: thanos-receive-data
```

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: thanos-receive
  name: thanos-receive
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 10901
    targetPort: 10901
  - name: http
    port: 10902
    targetPort: 10902
  - name: http-rw
    port: 19291
    targetPort: 19291
  selector:
    app: thanos-receive
```

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: thanos-receive
spec:
  gateways:
  - mesh
  hosts:
  - thanos-receive
  http:
  - name: http
    match:
      - port: 10902
    route:
    - destination:
        host: thanos-receive.monitoring.svc.cluster.local
        port:
          number: 10902
  - name: grpc
    match:
      - port: 10901
    route:
    - destination:
        host: thanos-receive.monitoring.svc.cluster.local
        port:
          number: 10901
  - name: http-remote-write
    match:
      - port: 19291
    route:
    - destination:
        host: thanos-receive.monitoring.svc.cluster.local
        port:
          number: 19291
```

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: thanos-receive
spec:
  hosts:
  - "*.thanos-receive.monitoring.svc.cluster.local"
  - thanos-receive.monitoring.svc.cluster.local
  - "*.thanos-receive"
  - thanos-receive
  location: MESH_INTERNAL
  ports:
  - name: grpc
    number: 10901
    protocol: GRPC
  - name: http
    number: 10902
    protocol: HTTP
  - name: http-rw
    number: 19291
    protocol: HTTP
  resolution: NONE
```

Additionally, I can see the connections in the Envoy logs, but they seem like they should be succeeding:
```
kubectl -n monitoring logs thanos-receive-0 istio-proxy | grep '100.108.0.22' | tail
{"bytes_sent":"111","upstream_cluster":"inbound|10901|grpc|thanos-receive.monitoring.svc.cluster.local","downstream_remote_address":"100.108.0.22:57972","authority":"100.108.0.10:10901","path":"/thanos.Store/Info","protocol":"HTTP/1.1","upstream_service_time":"0","upstream_local_address":"-","duration":"0","downstream_local_address":"100.108.0.10:10901","upstream_transport_failure_reason":"-","response_code":"200","user_agent":"grpc-go/1.22.1","response_flags":"-","start_time":"2019-11-07T19:22:58.406Z","method":"POST","request_id":"e0aa7960-5da9-4970-a9de-1c858e08de8d","upstream_host":"127.0.0.1:10901","x_forwarded_for":"-","requested_server_name":"-","bytes_received":"5","istio_policy_status":"-"}
{"duration":"0","downstream_local_address":"100.108.0.10:10901","upstream_transport_failure_reason":"-","response_code":"200","user_agent":"grpc-go/1.22.1","response_flags":"-","start_time":"2019-11-07T19:23:03.405Z","method":"POST","request_id":"d4606fd8-1b61-4851-b0a4-90ef90a8c24e","upstream_host":"127.0.0.1:10901","x_forwarded_for":"-","requested_server_name":"-","bytes_received":"5","istio_policy_status":"-","bytes_sent":"111","upstream_cluster":"inbound|10901|grpc|thanos-receive.monitoring.svc.cluster.local","downstream_remote_address":"100.108.0.22:57600","authority":"100.108.0.10:10901","path":"/thanos.Store/Info","protocol":"HTTP/1.1","upstream_service_time":"0","upstream_local_address":"-"}
{"upstream_host":"127.0.0.1:10901","x_forwarded_for":"-","requested_server_name":"-","bytes_received":"5","istio_policy_status":"-","bytes_sent":"111","upstream_cluster":"inbound|10901|grpc|thanos-receive.monitoring.svc.cluster.local","downstream_remote_address":"100.108.0.22:57600","authority":"100.108.0.10:10901","path":"/thanos.Store/Info","protocol":"HTTP/1.1","upstream_service_time":"0","upstream_local_address":"-","duration":"0","downstream_local_address":"100.108.0.10:10901","upstream_transport_failure_reason":"-","response_code":"200","user_agent":"grpc-go/1.22.1","response_flags":"-","start_time":"2019-11-07T19:23:08.404Z","method":"POST","request_id":"406c955a-75aa-41a8-9957-5c1d6b0c2c0b"}
{"upstream_cluster":"inbound|10901|grpc|thanos-receive.monitoring.svc.cluster.local","downstream_remote_address":"100.108.0.22:57972","authority":"100.108.0.10:10901","path":"/thanos.Store/Info","protocol":"HTTP/1.1","upstream_service_time":"1","upstream_local_address":"-","duration":"1","downstream_local_address":"100.108.0.10:10901","upstream_transport_failure_reason":"-","response_code":"200","user_agent":"grpc-go/1.22.1","response_flags":"-","start_time":"2019-11-07T19:23:13.405Z","method":"POST","request_id":"6231f588-3861-4e87-9607-0584f0709b80","upstream_host":"127.0.0.1:10901","x_forwarded_for":"-","requested_server_name":"-","bytes_received":"5","istio_policy_status":"-","bytes_sent":"111"}
{"requested_server_name":"-","bytes_received":"5","istio_policy_status":"-","bytes_sent":"111","upstream_cluster":"inbound|10901|grpc|thanos-receive.monitoring.svc.cluster.local","downstream_remote_address":"100.108.0.22:57600","authority":"100.108.0.10:10901","path":"/thanos.Store/Info","protocol":"HTTP/1.1","upstream_service_time":"0","upstream_local_address":"-","duration":"0","downstream_local_address":"100.108.0.10:10901","upstream_transport_failure_reason":"-","response_code":"200","user_agent":"grpc-go/1.22.1","response_flags":"-","start_time":"2019-11-07T19:23:18.406Z","method":"POST","request_id":"6055cbad-12c0-45a0-b81c-2d298a7a7e6d","upstream_host":"127.0.0.1:10901","x_forwarded_for":"-"}
{"upstream_cluster":"inbound|10901|grpc|thanos-receive.monitoring.svc.cluster.local","downstream_remote_address":"100.108.0.22:57600","authority":"100.108.0.10:10901","path":"/thanos.Store/Info","protocol":"HTTP/1.1","upstream_service_time":"0","upstream_local_address":"-","duration":"0","downstream_local_address":"100.108.0.10:10901","upstream_transport_failure_reason":"-","response_code":"200","user_agent":"grpc-go/1.22.1","response_flags":"-","start_time":"2019-11-07T19:23:23.411Z","method":"POST","request_id":"6bbc8a8f-c258-4d05-aed1-e56c03c19b5a","upstream_host":"127.0.0.1:10901","x_forwarded_for":"-","requested_server_name":"-","bytes_received":"5","istio_policy_status":"-","bytes_sent":"111"}
{"upstream_local_address":"-","duration":"0","downstream_local_address":"100.108.0.10:10901","upstream_transport_failure_reason":"-","response_code":"200","user_agent":"grpc-go/1.22.1","response_flags":"-","start_time":"2019-11-07T19:23:28.406Z","method":"POST","request_id":"a785ce31-33db-4336-a129-34a64e455ded","upstream_host":"127.0.0.1:10901","x_forwarded_for":"-","requested_server_name":"-","bytes_received":"5","istio_policy_status":"-","bytes_sent":"111","upstream_cluster":"inbound|10901|grpc|thanos-receive.monitoring.svc.cluster.local","downstream_remote_address":"100.108.0.22:57972","authority":"100.108.0.10:10901","path":"/thanos.Store/Info","protocol":"HTTP/1.1","upstream_service_time":"0"}
{"protocol":"HTTP/1.1","upstream_service_time":"0","upstream_local_address":"-","duration":"0","downstream_local_address":"100.108.0.10:10901","upstream_transport_failure_reason":"-","response_code":"200","user_agent":"grpc-go/1.22.1","response_flags":"-","start_time":"2019-11-07T19:23:33.407Z","method":"POST","request_id":"10a2f737-2065-4966-9f7d-cf74d43fb609","upstream_host":"127.0.0.1:10901","x_forwarded_for":"-","requested_server_name":"-","bytes_received":"5","istio_policy_status":"-","bytes_sent":"111","upstream_cluster":"inbound|10901|grpc|thanos-receive.monitoring.svc.cluster.local","downstream_remote_address":"100.108.0.22:57600","authority":"100.108.0.10:10901","path":"/thanos.Store/Info"}
{"duration":"0","downstream_local_address":"100.108.0.10:10901","upstream_transport_failure_reason":"-","response_code":"200","user_agent":"grpc-go/1.22.1","response_flags":"-","start_time":"2019-11-07T19:23:38.406Z","method":"POST","request_id":"df207200-bc54-4f06-b871-6a6497ef6593","upstream_host":"127.0.0.1:10901","x_forwarded_for":"-","requested_server_name":"-","bytes_received":"5","istio_policy_status":"-","bytes_sent":"111","upstream_cluster":"inbound|10901|grpc|thanos-receive.monitoring.svc.cluster.local","downstream_remote_address":"100.108.0.22:57600","authority":"100.108.0.10:10901","path":"/thanos.Store/Info","protocol":"HTTP/1.1","upstream_service_time":"0","upstream_local_address":"-"}
{"bytes_sent":"111","upstream_cluster":"inbound|10901|grpc|thanos-receive.monitoring.svc.cluster.local","downstream_remote_address":"100.108.0.22:57600","authority":"100.108.0.10:10901","path":"/thanos.Store/Info","protocol":"HTTP/1.1","upstream_service_time":"0","upstream_local_address":"-","duration":"0","downstream_local_address":"100.108.0.10:10901","upstream_transport_failure_reason":"-","response_code":"200","user_agent":"grpc-go/1.22.1","response_flags":"-","start_time":"2019-11-07T19:23:43.405Z","method":"POST","request_id":"e5b51e92-7328-44e7-b312-0890890f7e79","upstream_host":"127.0.0.1:10901","x_forwarded_for":"-","requested_server_name":"-","bytes_received":"5","istio_policy_status":"-"}
```

If I change the Service back to a non-headless service, the problem immediately goes away. The only difference I could see in the logs was that when it was working, it was using HTTP2 (non-headless), but when a headless service was used - HTTP1.1 showed up in the requests.

**Expected behavior**

gRPC connection succeeds.

**Steps to reproduce the bug**
Create StatefulSet with Headless service running GRPC.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.2.5

**How was Istio installed?**
Helm template

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS
