### ISSUE TITLE
istio envoy throws 404 response HTTP/2 

### ISSUE THREAD

**Issue by andrijaperovic** [istio/istio#18762]
**Bug description**

Getting a 404 HTTP response when calling service endpoint and resolving to istio-ingressgateway External IP (port forwarding to a jumpbox 30005 to 443 pointing to istio-ingressgateway External IP and below scenario):

```
  curl -XGET -HHost:hostname --resolve hostname:30005:127.0.0.1 https://hostname:30005/gateway_services/ok -v -tls1_2
        Note: Unnecessary use of -X or --request, GET is already inferred.
    * Added hostname:30005:127.0.0.1 to DNS cache
    * Hostname hostname was found in DNS cache
    *   Trying 127.0.0.1...
    * TCP_NODELAY set
    * Connected to hostname (127.0.0.1) port 30005 (#0)
    * ALPN, offering h2
    * ALPN, offering http/1.1
    * Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
    * successfully set certificate verify locations:
    *   CAfile: /etc/ssl/cert.pem
          CApath: none
    * TLSv1.2 (OUT), TLS handshake, Client hello (1):
    * TLSv1.2 (IN), TLS handshake, Server hello (2):
    * TLSv1.2 (IN), TLS handshake, Certificate (11):
    * TLSv1.2 (IN), TLS handshake, Server key exchange (12):
    * TLSv1.2 (IN), TLS handshake, Server finished (14):
    * TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
    * TLSv1.2 (OUT), TLS change cipher, Client hello (1):
    * TLSv1.2 (OUT), TLS handshake, Finished (20):
    * TLSv1.2 (IN), TLS change cipher, Client hello (1):
    * TLSv1.2 (IN), TLS handshake, Finished (20):
    * SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
    * ALPN, server accepted to use h2
    * Server certificate:
    *  subject: (redacted)
    *  start date: Jun  6 00:00:00 2019 GMT
    *  expire date: Aug 27 12:00:00 2021 GMT
    *  subjectAltName: host "hostname" matched cert's "*.domain.com"
    *  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 High Assurance Server CA
    *  SSL certificate verify ok.
    * Using HTTP2, server supports multi-use
    * Connection state changed (HTTP/2 confirmed)
    * Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
    * Using Stream ID: 1 (easy handle 0x7fbe4200e800)
    > GET /gateway_services/ok HTTP/2
    > Host:hostname
    > User-Agent: curl/7.54.0
    > Accept: */*
    >
    * Connection state changed (MAX_CONCURRENT_STREAMS updated)!
    < HTTP/2 404
        < location: https://hostname/gateway_services/ok
        < date: Thu, 07 Nov 2019 21:54:46 GMT
        < server: istio-envoy
    <
    * Connection #0 to host hostname left intact
```

Similarly, after enabling logging with helm: 
```
../helm/linux-amd64/helm template install/kubernetes/helm/istio --namespace=istio-system -x templates/configmap.yaml --set global.proxy.accessLogFile="/dev/stdout" | kubectl replace -f -
```
Seeing the following output in the istio-ingressgateway pod: 
```
[2019-11-07T20:53:47.604Z] "GET /gateway_services/ok HTTP/2" 404 - "-" "-" 0 0 0 - "10.28.164.55" "curl/7.54.0" "0675a0b0-4c3a-4606-b9fa-b3d2227f6b5b" "host" "-" - - 192.168.2.16:443 10.28.164.55:12688 host default
```
where 10.28.164.55 is one of the usercluster nodes where the application is running, and 12688 is the node port. Curling the application service external IP directly gives a valid response. 

There is a kubernetes secret which has been volume mounted on the istio-ingressgateway which contains the valid tls.key and tls.crt for the domain: 

```
        volumeMounts:
        - mountPath: /etc/certs
          name: istio-certs
          readOnly: true
        - mountPath: /etc/istio/ingressgateway-certs
          name: ingressgateway-certs
          readOnly: true
        - mountPath: /etc/istio/ingressgateway-ca-certs
          name: ingressgateway-ca-certs
          readOnly: true
```

The filepath is similarly references in the Gateway resource inside the application namespace: 
```
  - hosts:
    - 'hostname'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
```

**Expected behavior**

Should get a valid API response, similarly to curling the service external IP directly. 

**Steps to reproduce the bug**

Follow the steps provided in the description.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
istioctl version --remote
client version: 1.3.3
control plane version: 1.3.3
```

**How was Istio installed?**
Standard installation, Helm template

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE On-Prem (Anthos), RHEL 6.5
