### ISSUE TITLE
Forwarding ingress traffic to external resources (Azure storage / CDN)

### ISSUE THREAD

**Issue by bogdansucila** [istio/istio#18850]
**Bug description**
Currently, we are using istio's ingress gateway as the public endpoint for many of our microservices. Furthermore, we are using its reverse proxy capabilities to redirect traffic based on URI format to our web frontend or various AKS-hosted backends.

What I am trying to achieve at the moment is splitting 'regular' web requests (i.e. traffic destined for dynamic web pages) from static content requests (CSS, images, etc.). My current setup uses prefix-based URI matching to identify requests containing the subpath '/static', rewrite the subpath to the name of the CDN endpoint that the static content is hosted on, then finally forward the traffic to the Azure CDN where the said static content is hosted. For example:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cdn-ch
spec:
  hosts:
  - "ch-portal-test.example.com"  
  gateways:
  - example-ch-app-gateway
  http:
  - match:
    - uri:
        prefix: /static
    rewrite:
      uri: "/test"
    route:
    - destination:
        host: cdn-ch.azureedge.net
    timeout: 40s    
    retries:
      attempts: 5
      perTryTimeout: 3s
      retryOn: gateway-error,connect-failure,refused-stream
```
Furthermore, I added a Service Entry and Destination Rule for the Azure CDN, since it is an external resource:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: rwe-cdn-test
spec:
  hosts:
  - "cdn-ch.azureedge.net"
  ports:
  - number: 80
    name: http-port
    protocol: HTTP
  - number: 443
    name: http-port-for-tls-origination
    protocol: HTTP
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: rwe-cdn-test
spec:
  host: cdn-ch.azureedge.net
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE 
```
Now, while Istio does perform the basic operations described in the VS config (i.e. rewrites the request URI from _/static/whatever.css_ to _/test/whatever.css_ and forwards the traffic to the CDN), every test that I have ran so far yields a 404 not found despite the requested file being present in the said path (accessing the CDN URL directly downloads the test style sheet)

My first instinct was raising a support ticket with Microsoft, suspecting a possible limitation their Azure CDN / Storage Blob product. However, after a week of back-and-forth emails and log analysis, their conclusion has been that it is possible that Istio could strip away some of the request headers, resulting in the said 404. 

And since I couldn't find any solid reference to header manipulation in the documentation, I thought I might move my inquiry here - did anyone attept something similar until now? does any sort of header manipulation / stripping occur when a request gets processed by Istio? I am happy to provide logs / packet captures of the forwarded requests if it helps with the troubleshooting process.

**Expected behavior**
Requests should be forwarded successfully, since the rewrite is correct and the requested file exists in the specified path.

**Steps to reproduce the bug**
Apply the manifests specified above, replacing the URLs with a different CDN / online storage service (I reckon you could use anything with a static URL)

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Client: 1.2.4
Server: 1.2.4

**How was Istio installed?**
Via a helm chart

**Environment where bug was observed (cloud vendor, OS, etc)**
Azure - AKS

**Comment by bogdansucila** [comment]
Weirdly enough, running a tcpdump on the ingress gw's proxy container shows a 200 response for the same request that yielded a 404 in the browser:

```
HTTP/1.1 200 OK
date: Thu, 14 Nov 2019 09:07:37 GMT
content-type: text/plain; charset=utf-8
server: istio-envoy
x-envoy-upstream-service-time: 11
x-envoy-upstream-healthchecked-cluster: singleadpage-ch.freki
transfer-encoding: chunked
Host: ch-portal-test.example.com
Connection: keep-alive
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Cookie: rub_NewAdsFirstVisit=09/26/2019 11:11:50; tsa=58fe1431f9d
host: ch-portal-test.example.com
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
accept-encoding: gzip, deflate
accept-language: en-US,en;q=0.9
cookie: rub_NewAdsFirstVisit=09/26/2019 11:11:50; tsa=58fe1431f9d
x-forwarded-for: 82.77.129.195
x-forwarded-proto: http
x-envoy-external-address: 82.77.129.195
x-request-id: 5251bd26-2b1b-4398-b8ca-4573f1fe5774
x-envoy-decorator-operation: cdn-ch.azureedge.net:80/static*
x-istio-attributes: CkIKGGRlc3RpbmF0aW9uLnNlcnZpY2UubmFtZRImEiRhdXRvY29tcGxldGUtd2lkZ2V0LWRlLmF6dXJlZWRnZS5uZXQKKAodZGVzdGluYXRpb24uc2VydmljZS5uYW1lc3BhY2USBxIFZnJla2kKTwoKc291cmNlLnVpZBJBEj9rdWJlcm5ldGVzOi8vaXN0aW8taW5ncmVzc2dhdGV3YXktNmZmN2ZjYzVmNC1qcjZsdy5pc3Rpby1zeXN0ZW0KQgoYZGVzdGluYXRpb24uc2VydmljZS5ob3N0EiYSJGF1dG9jb21wbGV0ZS13aWRnZXQtZGUuYXp1cmVlZGdlLm5ldA==
x-envoy-expected-rq-timeout-ms: 3000
x-b3-traceid: 0c152fe59272a76ddbf7cecf30e59f4c
x-b3-spanid: dbf7cecf30e59f4c
x-b3-sampled: 0
x-envoy-original-path: /static/header-footer/Test/generated/FooterResultPage.html
content-length: 0
Content-Type: text/html
Date: Thu, 14 Nov 2019 09:07:47 GMT
Server: ECAcc (ama/8B2F)
Content-Length: 345
content-type: text/html
date: Thu, 14 Nov 2019 09:07:47 GMT
server: istio-envoy
content-length: 345
x-envoy-upstream-service-time: 7
Host: ch-portal-test.example.com
Connection: keep-alive
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
Accept: image/webp,image/apng,image/*,*/*;q=0.8
Referer: http://ch-portal-test.example.com/static/header-footer/Test/generated/FooterResultPage.html
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Cookie: rub_NewAdsFirstVisit=09/26/2019 11:11:50; tsa=58fe1431f9d
```

**Comment by bogdansucila** [comment]
Turns out the issue was the 'Authority' request header, apparently the CDN rejected calls with any other value than its hostname. As illustrated in the packet capture above, the request header was set to the original hostname accessed through the browser ('ch-portal-test.example.com'), while the CDN expected its own hostname ('cdn-ch.azureedge.net').

As a test, I set the gateway and virtual service to listen for the CDN hostname, and modified the DNS records to point the CDN's hostname to the ingress gateway's IP address. The routing worked perfectly, including the URI rewrites, so the problem lies solely with the authority header of the request. 

However, the only workaround I have found so far is re-setting the header from the virtual service config, which results in a hard redirect to the CDN's URL:

```
  http:
  - match:
    - uri:
        prefix: /static
    rewrite:
      authority: cdn-ch.azureedge.net
      uri: "/test"
    route:
    - destination:
        host: cdn-ch.azureedge.net
```

This doesn't really help my case however, since a) the purpose of the setup is to seamlessly integrate the CDN-served static files into the web app, not to have the session redirected to a different URL, b) this kinda messes up the SEO setup, since a good portion of the requests (basically anything associated with css or images) will be registered with a different URL than the main web app.

I also tried employing an Envoy filter with some LUA code, however the result was the same, i.e. a hard redirect:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: edge-lua-filter
spec:
  workloadLabels:
    app: example-ch-app-gateway
  filters:
  - listenerMatch:
      listenerType: GATEWAY
    filterName: envoy.lua
    filterType: HTTP
    filterConfig:
      inlineCode: |
        function envoy_on_request(request_handle)

          local authority = request_handle:headers():get(":authority")

          if authority == "ch-portal-test.example.com" then 
            request_handle:headers():replace(":authority", "cdn-ch.azureedge.net") 
          end
        end
```

It is possible that my config could be a bit off though, this is my second ever attempt at LUA code :)

Any input on the matter would be greatly appreciated. This has been a bit of a blocker for the past week, and it would be useful to know whether this approach is worth pursuing or whether I should scrap it and employ a different method.

**Comment by fcantournet** [comment]
You can rewrite the authority in your virtualservice :
https://istio.io/docs/reference/config/networking/virtual-service/#HTTPRewrite

I should at least save you the trouble of envoyfilters + lua (which is good because envoyfilters are changing a lot in 1.3)

**Comment by fcantournet** [comment]
> However, the only workaround I have found so far is re-setting the header from the virtual service config, which results in a hard redirect to the CDN's URL

I don't understand why the rewrite in the virtualservice would trigger a "hard redirect".
Are you sayin you get a 301 from the istio ingress-gateway ?

**Comment by bogdansucila** [comment]
> > However, the only workaround I have found so far is re-setting the header from the virtual service config, which results in a hard redirect to the CDN's URL
> 
> I don't understand why the rewrite in the virtualservice would trigger a "hard redirect".
> Are you sayin you get a 301 from the istio ingress-gateway ?

Yep, that's what happened initially at least, I would get a 301 and had my CDN-served content opened in a separate tab / window.

However, I managed to find a working version of the config with a few tweaks here and there, including rewriting the content type response header from octet-stream to text/html. Just in case someone attempts to replicate this admittedly fringe case in the future, this is the config that worked for me:

 ```
http:
  - match:
    - uri:
        prefix: /static
    rewrite:
      authority: cdn-ch.azureedge.net
      uri: "/test"
    route:
    - destination:
        host: cdn-ch.azureedge.net
      headers:
        response:
          set:
            content-type: "text/html"
```

Closing this issue as it is now resolved.
