### ISSUE TITLE
NetworkPolicy ignored by running proxy

### ISSUE THREAD

**Issue by Phlak106** [istio/istio#18859]
If you apply a network policy after deploying an Istio side-car injected workload (i.e. Envy sidecar is already running) it has no effect. Restarting the proxy (kill pod and let it restart) picks up the network policy appropriately.  

**Expected behavior**
Network policy is effective without restarting proxy.

**Steps to reproduce the bug**
1) Deploy Istio sidecar-injected workload (I used the Azure voting sample: https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough with a custom virtual service and gateway)
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-back
  namespace: voting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-back
  template:
    metadata:
      labels:
        app: azure-vote-back
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: azure-vote-back
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-back
  namespace: voting
spec:
  ports:
  - port: 6379
  selector:
    app: azure-vote-back
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-front
  namespace: voting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-front
  template:
    metadata:
      labels:
        app: azure-vote-front
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: azure-vote-front
        image: microsoft/azure-vote-front:v1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
        env:
        - name: REDIS
          value: "azure-vote-back"
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front
  namespace: voting
spec:
  ports:
  - port: 9080
    name: http
    targetPort: 80
  selector:
    app: azure-vote-front
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: voting-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: voting
  namespace: voting
spec:
  hosts:
    - "*"
  gateways:
    - istio-system/voting-gateway
  http:
    - match:
      - uri:
          prefix: /
      route:
      - destination:
          port:
            number: 9080
          host: azure-vote-front
```
2) Verify app is working, then apply a deny-all network policy.  This should deny traffic coming from istio-system (ingress gateway) to the voting namespace:
```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: deny-all
  namespace: voting
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
```
3) Observe application is still able to receive traffic.
4) Restart voting pod(s).
5) Observer application is no longer able to receive traffic.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
kubernetes version 1.15.5
kubectl version 1.14.7
istio version 1.3.4
**How was Istio installed?**
Apply istio-demo.yaml (after applying CRDs) per the quickstart: https://istio.io/docs/setup/install/kubernetes/

**Environment where bug was observed (cloud vendor, OS, etc)**
Azure Kubernetes Service created with network policy enabled per https://docs.microsoft.com/en-us/azure/aks/use-network-policies
