### ISSUE TITLE
Request Timeout time does not increase than 15s

### ISSUE THREAD

**Issue by kahootali** [istio/istio#1888]
I am using Istio 0.2.12 and Kubernetes 1.8.1.
I have a service which returns quite a big response and when I load test it by calling a lot of calls in few seconds it takes more time than 15 seconds but the default timeout is 15s . So I have tried to make my own routerule 
```
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: mysvc-routerule
spec:
  destination:
    name: mysvc
    namespace: istio-try
  httpReqTimeout:
    simpleTimeout:
      timeout: 25s
```
But it doesn't work, it still timeouts at 15s, where as if I decrease the timeout period to 5s, it works and timeouts at 5s rather than 15s. Any way I can configure it?
