### ISSUE TITLE
Istio doesn't return 401 error when i add policies with jwt.

### ISSUE THREAD

**Issue by aberistov** [istio/istio#18887]
**Bug description**
When i deploy policies with jwks, istio doesn't work with this policies and doesn't want authenticate an end-user.
I use example policies from istio docs.

```yaml
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "jwt-example"
spec:
  targets:
  - name: myservice
  origins:
  - jwt:
      issuer: "testing@secure.istio.io"
      jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.3/security/tools/jwt/samples/jwks.json"
  principalBinding: USE_ORIGIN
```

```yaml
apiVersion: v1
kind: Service
metadata:
  name: myservice
  namespace: myns
spec:
  clusterIP: xx.xx.xx.xx
  ports:
  - name: http-myservice
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    service: myservice
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  labels:
    app: gateways
  name: myservice-gateway
  namespace: myns
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - myservice.mydomain.com
    port:
      name: https-default
      number: 443
      protocol: HTTPS
    tls:
      credentialName: myservice-ssl
      mode: SIMPLE
```

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: myservice-vs
  namespace: myns
spec:
  gateways:
  - myservice-gateway
  hosts:
  - myservice.mydomain.com
  http:
  - retries:
      attempts: 5
      perTryTimeout: 1s
      retryOn: gateway-error,connect-failure,refused-stream
    route:
    - destination:
        host: myservice
        port:
          number: 80
```

```
curl https://myservice.mydomain.com/
404 page not found (its normal reply from service)
```
This policy doesn't return 401 error.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
client version: 1.3.4
control plane version: 1.3.4
```
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**

> helm chart

**Comment by adurai81** [comment]
I'm seeing the same behavior as well. I'm able to access the end-point un-authenticated.

**Comment by Starefossen** [comment]
I am seeing the exact same behavior on the same version of Istio.

**Comment by diemtvu** [comment]
Just to make sure, which namespace did you submit the authN policy to? It should be in the same namespace as your application (`myns`, I think)

**Comment by adurai81** [comment]
Got it, the VirtualService must be in the same namespace as that of the Service.

Thanks my issue is resolved.

**Comment by incfly** [comment]
Basically the request fails at routing stage. Expected behavior should be after correct routing, request fails at authentication phase.

Which istio.io doc you are following through?

Maybe this can be warned via a Galley validation webhook, when applying VirtualService, give a warn message if there's no service in the corresponding namespace? @ayj @sushicw not sure if that check will be too spamming and cause some false positive.

**Comment by Starefossen** [comment]
Here is my configuration. Everything except for the `Certificate` and corresponding secret is in the `default` namespace.

```
---
# Source: my-app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: default
  labels:
    app: my-app
    version: "2.1.2"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8181
      protocol: TCP
      name: http-my-app
  selector:
    app: my-app
    version: "2.1.2"

---
# Source: my-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: default
  labels:
    app: my-app
    version: "2.1.2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      version: "2.1.2"
  template:
    metadata:
      labels:
        app: my-app
        version: "2.1.2"
    spec:
      containers:
        # my-app Image
        - name: my-app
          image: "gcr.io/my-app/my-app:v2.1.2"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-my-app
              containerPort: 8181
              protocol: TCP
          env:
            - name: GUNICORN_BIND
              value: "0.0.0.0:8181"
            - name: GUNICORN_WORKERS
              value: "4"
            - name: GUNICORN_THREADS
              value: "4"
          readinessProbe:
            httpGet:
              path: /healthz
              port: http-my-app
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http-my-app
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 5

---
# Source: my-app/templates/istio-jwt-policy.yaml

---
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: my-app
  namespace: default
  labels:
    app: my-app
    version: "2.1.2"
spec:
  targets:
  - name: my-app
    ports:
    - number: 80
  origins:
  - jwt:
      issuer: https://securetoken.google.com/my-app
      jwksUri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
  principalBinding: USE_ORIGIN
  peers:
  - mtls: {}
  #triggerRules:
  #- includedPaths:
  #  - prefix: /
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: my-app
  namespace: default
  labels:
    app: my-app
    version: "2.1.2"
spec:
  host: "my-app.default.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

---
# Source: my-app/templates/certificate.yaml
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: my-app-example-com
  namespace: istio-system
  labels:
    app: my-app
    version: "2.1.2"
spec:
  secretName: my-app-example-com-tls
  renewBefore: 720h
  commonName: my-app.example.com
  dnsNames:
    - my-app.example.com

  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer

---
# Source: my-app/templates/istio-gateway.yaml

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-app
  namespace: default
  labels:
    app: my-app
    version: "2.1.2"
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - my-app.example.com

      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - my-app.example.com

      tls:
        mode: SIMPLE
        credentialName: my-app-example-com-tls

---
# Source: my-app/templates/istio-serviceentry.yaml

---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: my-app-google-apis
  namespace: default
  labels:
    app: my-app
    version: "2.1.2"
spec:
  hosts:
  - vision.googleapis.com
  ports:
  - number: 443 # https
    name: https
    protocol: HTTPS
  exportTo:
  - "."
  location: MESH_EXTERNAL
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-app-google-apis
  namespace: default
  labels:
    app: my-app
    version: "2.1.2"
spec:
  hosts:
  - vision.googleapis.com
  tls:
  - match:
    - port: 443
      sni_hosts:
      - vision.googleapis.com
    route:
    - destination:
        host: vision.googleapis.com

---
# Source: my-app/templates/istio-virtualservice.yaml

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-app
  namespace: default
  labels:
    app: my-app
    version: "2.1.2"
spec:
  hosts:
    - my-app.example.com

  gateways:
  - my-app
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: my-app
        port:
          number: 80
```
