### ISSUE TITLE
HTTP calls with host header ending with a dot is blocked by sidecar

### ISSUE THREAD

**Issue by ffarozan** [istio/istio#18904]
**Bug description**
404 is returned when http calls contain host with a trailing dot. For ex: http://webservice.svc.cluster.local.:8080/

**Expected behavior**

**Steps to reproduce the bug**
On any kubernetes webservice, access the service using the trailing dot url.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
$ istioctl version
client version: 1.3.3
control plane version: 1.3.3

**How was Istio installed?**
https://istio.io/docs/setup/install/helm/#option-1-install-with-helm-via-helm-template

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
The challenge with this is that there is a huge matrix of clients/server behavior:
* Client sends trailing . but strips it from Host header
* Client sends trailing . and keeps in in Host header
* Server accepts trailing .
* Server rejects trailing .
* Server sends a 301 for trailing dot

From Istio perspective, we would likely need to double the virtualHosts so we have variants with `.` and without

**Comment by GregHanson** [comment]
@ffarozan if you define a VirtualService for the hostname in question `webservice.svc.cluster.local.`, does routing behave as you expect?  The trailing `.` should make it through Istio's validation logic

**Comment by ffarozan** [comment]
I haven't defined a VirtualService. My initial use-case with istio is to observe layer 4 metrics from all pods. So there is no use-case for me to define a VirtualService.

**Comment by kirecek** [comment]
Was this somehow resolved already by any chance?

We just discovered that FQDN hosts are not matched because of the mentioned problem. So we have to actually create double records for each host in gateways and virtualservices.

**Comment by derekcrovo** [comment]
We hit this old issue here in October 2021. If you're seeing it too and don't like the idea of doubling all your VirtualServices and ServiceEntries, try this EnvoyFilter. It toggles the Envoy `strip_trailing_host_dot` feature. It completely solved the problem for us.


```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: strip-trailing-dot
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          strip_trailing_host_dot: true
```

🎃
