### ISSUE TITLE
Galley's ingress resource controller incorrectly handles Ingress resource with multiple rules

### ISSUE THREAD

**Issue by utako** [istio/istio#18963]
**Bug description**

When supplying multiple route rules as part of an Ingress spec:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echo
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - host: echo1.example.com
    http:
      paths:
      - backend:
          serviceName: echo1
          servicePort: 80
  - host: echo2.example.com
    http:
      paths:
      - backend:
          serviceName: echo2
          servicPort: 80
```

when using the Ingress controller as part of Processing2 (`EnableServiceDiscovery: true`), I see that `curl echo1.example.com` hit the echo1 service, and `curl echo2.example.com` also hit the echo1 service. If you flip the order of these rules around, you'll see `curl echo2.example.com` go to `echo2`, and `curl echo1.example.com` go to `echo2`. 

**Expected behavior**
Given the following Ingress spec:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echo
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - host: echo1.example.com
    http:
      paths:
      - backend:
          serviceName: echo1
          servicePort: 80
  - host: echo2.example.com
    http:
      paths:
      - backend:
          serviceName: echo2
          servicPort: 80
```
I expect curling `echo1.example.com` to route to the `echo1` backend. I expect curling `echo2.example.com` to route to the `echo2` backend.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

control plane version: 1.5-alpha.405874959a998d5020f6bd3f944bee00dc8020ee

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-gke.17", GitCommit:"27b48e2b4c9535d185ec945c6a513537e4d116cf", GitTreeState:"clean", BuildDate:"2019-10-21T20:10:26Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}

Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
