### ISSUE TITLE
Finer-grained control over locality load balancing priorities

### ISSUE THREAD

**Issue by nicktrav** [istio/istio#18966]
**Describe the feature request**

Currently, when using locality load balancing, the priorities sent to Envoy are set up according to:

- priority 0 - same region, same zone
- priority 1 - same region
- priority 2 - different region

#### Issue 1. - different regions are fungible

In the case where an Envoy has connectivity to endpoints located in other regions, there can exist a situation where all endpoints in the same region are unavailable, but endpoints in other regions are healthy. In this case, all endpoints across all regions are treated as equal.

Consider the case where the workload is located in `us-west2`, but candidate endpoints exist in `us-central1` and `asia-southeast2`. In the event that no destination endpoints are located in `us-west2`, endpoints in the other two regions will be considered and treated equally. A sustained load will round-robin across all of these endpoints.

#### Issue 2. - zones are not fungible

Consider the case where a source workload has all instances in zone `us-west2-a`, and there are 5 potential destination endpoints, 1 located in `us-west2-a`, 4 located in either `us-west2-b` and `us-west2-c`. In this case all of the load from the source workload will be pinned to the single instance of the destination workload. The remaining destination endpoints receive no traffic.

A potential solution to both of these problems would be to allow an operator a means of configuring a precedence to use when setting up the priorities. For example, I could say that I want endpoints in the same region and same zone to be treated as fungible, _and_ also specify an ordering for regions to be considered, which could differ based on where the Envoy is located (e.g. consider `us-central1` before `asia-southeast2` if the workload is in `us-west2`, but the opposite if the workload is in `asia-south1`).

In our case, we run regional control planes, so we'd have the configuration differ per control-plane, though perhaps some installations elsewhere might require more configuration here if they have a single control plane looking after Envoys in multiple regions.

Such a configuration could have a structure that resembles the following:

```yaml
priorities:
# ordered list of priorities
# name is arbitrary, order is important
- p0: # all zones in us-west2 are fungible
  - us-west/us-west2-a/*
  - us-west/us-west2-b/*
  - us-west/us-west2-c/*
- p1: # consider us-central1 _before_ asia
  - us-central1/us-central1-a/*
  - us-central1/us-central1-b/*
  - us-central1/us-central1-c/*
- p2: # all other regions are fungible
  - asia-southeast2/asia-southeast2-a/*
  - asia-southeast2/asia-southeast2-b/*
  - asia-southeast2/asia-southeast2-c/*
  - asia-south1/asia-south1-a/*
  - asia-south1/asia-south1-b/*
  - asia-south1/asia-south1-c/*
```

Obvious downside is that it requires specifying the full set of regions up front.

This is obvious a very rough proposal, but the main idea / request is the ability to have finer grained control over the priorities sent to Envoy, and how they are inferred and mapped.

**Describe alternatives you've considered**

As an alternative, there already exists a mechanism to specify the `istio-locality` label, though it was already been noted in istio/istio.io#4938 that this is an internal implementation detail.
