### ISSUE TITLE
Tweak envoy stats inclusion to include outlier detection stats

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#18973]
Right now its pretty hard to figure out when a service is marked as unhealthy. It would be useful to have metrics that expose these. As far as I know, Envoy has these stats and we exclude them, which we should include. This is especially useful for locality lb situations

**Comment by Stono** [comment]
+1

**Comment by Aaron-ML** [comment]
@howardjohn Was anything done regarding this, currently running into this problem now. Thanks

**Comment by dasch** [comment]
I'd also love to hear more about this, we really lack good observability of outlier detection that is also integrated with the Istio stats. Istio _exposes_ this Envoy functionality, so I feel it should also provide out-of-the-box observability of it.

**Comment by keithmattix** [comment]
Just ran into this myself; it's pretty surprising behavior. Any update on remediation?

**Comment by mosakashaka** [comment]
Hi, any update on this issue?

I've enabled outlier detection by `DestinationRule` and  tried to add the following annotation to my `deployment`, but got nothing report on the `Prometheus`.

yaml
```
      annotations:
        proxy.istio.io/config: |-
          proxyStatsMatcher:
            inclusionSuffixes:
            - "envoy_cluster_outlier_detection"
            - "outlier_detection"

```

I can see the Prometheus can auto-copmlete metrics names like `envoy_cluster_outlier_detection_ejections_consecutive_5xx` or `envoy_cluster_outlier_detection_ejections_active`, but when I execute the query, got empty result.

I can confirm the outlier detection is working in my `DestinationRule` config. (I have two pod in one deployment and make one of them return 500 responses)
