### ISSUE TITLE
Make "xdsapi.RouteConfiguration" capable for other RPC protocols

### ISSUE THREAD

**Issue by seflerZ** [istio/istio#18981]
**Describe the feature request**
Currently the "xdsapi.RouteConfiguration" is designed for HTTP only and no way to fit other RPC protocols like Apache Dubbo. This makes it difficult to generate non-HTTP Routes under full pushing. Because Dubbo also implemented its own RouteConfiguration, It's incompatible to fit into the rawRoutes and con.RouteConfigs:
```
func (s *DiscoveryServer) pushRoute(con *XdsConnection, push *model.PushContext, version string) error {
	pushStart := time.Now()
	rawRoutes := s.generateRawRoutes(con, push)
	if s.DebugConfigs {
		for _, r := range rawRoutes {
			con.RouteConfigs[r.Name] = r
			if adsLog.DebugEnabled() {
				resp, _ := protomarshal.ToJSONWithIndent(r, " ")
				adsLog.Debugf("RDS: Adding route:%s for node:%v", resp, con.node.ID)
			}
		}
	}
...
}
```

Here suggest constructing a parent sturct and make (HTTP or others)*.RouteConfiguration inherit from it in someway and add an extension point to generate route configurations within "ConfigGeneratorImpl" like below:
```
for _, p := range configgen.Plugins {
	p.OnBuildRoutes(...);
}
```
}. In that way, both Dubbo and HTTP can keep their own route configurations and easy to maintain.

**Describe alternatives you've considered**
1. enhance "xdsapi.RouteConfiguration" to universal route configuration which is suitable for every RPC protocol.
2. Add a new TypeUrl to handle Dubbo RDS individually

I've also noticed the Plugin interface has supported several listener methods but the "OnOutboundRouteConfiguration" and "OnInboundRouteConfiguration" are aimed to provide modification capability not appending. We can add some new methods here.

**Additional context**

**Comment by seflerZ** [comment]
@lizan How do you think about this?

**Comment by rshriram** [comment]
where are the protos?

**Comment by lizan** [comment]
From Envoy xDS/UDPA side, the current Envoy RDS is designed from HTTP only and hard to adopt other protocol. We've been talking adding abstraction layer to UDPA-DM for better support other protocols in the previous CNCF UDPA WG meeting, but there's no concrete proposal yet and no enough community interest. If you're interested you can talk to the WG. cc @htuch

Istio can provide the abstraction in its own, but if we agree this should be in UDPA that would be even better.

**Comment by htuch** [comment]
@lizan there is an initial design doc in this space at https://docs.google.com/document/d/1orxTIL9FXtgmyl5TtPRBqGjgp1ekL7oOKDd95wxeCRY/edit#heading=h.49inj0pvxl8p. I think it would benefit from some comment on how it can be made suitably generic to cover the case you describe, which I think is worth supporting.

**Comment by seflerZ** [comment]
@rshriram You can take a look [here](https://github.com/envoyproxy/envoy/tree/3f5580fb1ec23cc2e99d974d54eba054e14ee837/source/extensions/filters/network/dubbo_proxy) and here is an example of Dubbo listeners:
```
filter_chains:
      filters:
      - name: envoy.filters.network.dubbo_proxy
        config:
          stat_prefix: dubbo_incomming_stats
          protocol_type: Dubbo
          enable_unit_protection: true
          static_route_config: 
            route_config:
            - name: com.baba.middleware.hsf.HelloWorldService:1.0.0.TLS
              interface: com.baba.middleware.hsf.HelloWorldService # Required
              version: 1.0.0
              group: HSF 
              app_name: xxx_business 
              write_mode: center_or_unit
              route_idx: 1
              enable_unit_protection: true 
              routes:
              - match:
                  method:
                    name: add_method 
                    params_length: 3
                    params: 
                    - index: 0
                      type: int 
                      range_match:
                        start: 100
                        end: 200
                    - index: 1
                      type: string
                      prefix_match: "user_id:"
                    - index: 2
                      type: string
                      regex_match: "0.[5-9]"
                  headers:
                  - name: custom1
                    exact_match: 123
                  - name: custom2
                    exact_match: 456
                    invert_match: true
                  headers_for_list_any_of_matcher:
                  - name: custom1
                    value:
                      patterns:
                        - exact_match: 123
                        - prefix_match: 456
                route:
                  cluster: cluster_xxxx
              - match:
                method:
                  name: sub_method
                headers:
                - name: custom1
                  exact_match: 123
                - name: custom2
                  exact_match: 456
                  invert_match: true
                route:
                  cluster: cluster_xxxx
              - match:
                method:
                  name: :default
                route:
                  cluster: cluster_xxxx
```
The Dubbo proxy's routes are nested in listeners. It will be hard to extract to RDS because RouteType handler in pilot supports "xdsapi.RouteConfiguration" only.
