### ISSUE TITLE
istioctl analyze fails to parse a file with a commented document separator

### ISSUE THREAD

**Issue by selmanj** [istio/istio#18998]
**Bug description**

`istioctl analyze`, when pointed at a file with a line containing `# ---`, emits a parse error of 
```
 * error processing istio-manifests.yaml[0]: failed finding spec for group/kind: /`
```

Likely the parser used by istioctl is trying to split on end-of-stream markers incorrectly and not realizing its commented out.

This sounds innocuous, but it's not - the frequently used microservices-demo app at  https://github.com/GoogleCloudPlatform/microservices-demo for example has this comment in its generated istio config, which triggers the bug:
```
# ----------------------------------------------------------
# WARNING: This file is autogenerated. Do not manually edit.
# ----------------------------------------------------------
```

**Expected behavior**

`istioctl x analyze` ignores commented out lines.

**Steps to reproduce the bug**
Create a file named `my-test-file.yaml` with the below contents (note that the actual object doesn't matter much beyond being a valid resource - what's important is the `# ---`):
```
# ---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: frontend-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
```

Run istioctl analyze on the file:

```
$ istioctl x analyze my-test-file.yaml
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.4.0
