### ISSUE TITLE
Invalid source.namespace when pod name contains a dot

### ISSUE THREAD

**Issue by chaudyg** [istio/istio#19015]
**Bug description**

Mixer `source.namespace` attribute missconfigured on the envoy sidecar when the pod name includes a dot. `.` .

For example, if the pod name is 'foo.bar-1234-5678' in the namespace 'demo', the source namespace inside the sidecar proxy will be set to 'bar-1234-5678' instead of 'demo'.

Impact:
- istio metrics (TCP and http) are reported as "unknow".
- sadly for me, I have around 200+ services with a dot in the deployment name 🤦‍♂ 

NOTE: I am not very familiar with the istio codebase.  I am struggling to identify the lines of code where the namespace is parsed. I am more than happy to raise the PR to fix this issue. Would someone be willing to point me in the right direct?

**Expected behavior**

- the `source.namespace` attribute should be set to the correct value when the pod name includes a dot.
- mixer generated metrics should include the correct source identify instead of "unknown"

**Steps to reproduce the bug**

Create a new `demo` injected namespace

```
kubectl create ns demo
kubectl label ns demo istio-injection=enabled
```

Create a deployment with a dot `.` in the name
```
cat << EOF | kubectl apply -f -
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx
    version: v1
  name: foo.bar
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      version: v1
  template:
    metadata:
      labels:
        app: nginx
        version: v1
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: http
EOF
```

Check the `source.namespace` mixer attribute in the envoy config.
```
kubectl port-forward foo.bar-cdb8b9694-rtfbx 15000:15000

curl localhost:15000/config_dump | grep -C 10 "source.namespace"
--
              "mixer_attributes": {
               "attributes": {
                "context.proxy_version": {
                 "string_value": "1.3.5"
                },
                "context.reporter.kind": {
                 "string_value": "outbound"
                },
                "context.reporter.uid": {
                 "string_value": "kubernetes://foo.bar-78774dfcd9-z688n.demo"
                },
                "source.namespace": {
                 "string_value": "bar-78774dfcd9-z688n"
                },
                "source.uid": {
                 "string_value": "kubernetes://foo.bar-78774dfcd9-z688n.demo"
                }
               }
              },
              "forward_attributes": {
               "attributes": {
                "source.uid": {
                 "string_value": "kubernetes://foo.bar-78774dfcd9-z688n.demo"
                }
               }
              }
             }
            },
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

Tried with istio 1.2.9, 1.3.5, 1.4.0
```
istioctl version --remote
client version: 1.2.1
citadel version: 1.3.5
galley version: 1.3.5
pilot version: 1.3.5
policy version: 1.3.5
sidecar-injector version: 1.3.5
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-19T13:57:45Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

- Using official helm chart

**Environment where bug was observed (cloud vendor, OS, etc)**
- minikube
- Kops 1.14
