### ISSUE TITLE
Istioctl analyze check failed

### ISSUE THREAD

**Issue by HamzaK8s** [istio/istio#19016]
**Bug description**
While evaluating the new diagnostic tool `istioctl analyze` I'm getting a strange behavior with non understood issue

**Expected behavior**
```
$ istioctl x analyze vs.yaml
✔ No validation issues found
```
**Steps to reproduce the bug**
I used the following virtualservice and destinationRule
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
   name: reviews-vs
spec:
 hosts:
 - reviews.default.svc.cluster.local
 gateways:
 - mesh
 http:
 - route:
   - destination:
        host: reviews.default.svc.cluster.local
        subset: v1
     weight: 50
   - destination:
         host: reviews.default.svc.cluster.local
         subset: v3
     weight: 50
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
   name: reviews-dr
spec:
  host: reviews.default.svc.cluster.local
  subsets:
  - name: v1
    labels:
       version: v1
  - name: v2
    labels:
      version: v2
  - name: v3
    labels:
      version: v3
```
```
$ istioctl x analyze vs.yaml
Error [IST0101] (VirtualService reviews-vs.default) Referenced host+subset in destinationrule not found: "reviews.default.svc.cluster.local+v1"
Error [IST0101] (VirtualService reviews-vs.default) Referenced host+subset in destinationrule not found: "reviews.default.svc.cluster.local+v3"
Error: Analyzer found issues.
```
But trying to create the vs directly I had no problem 
```
$ kubectl apply -f vs.yaml 
virtualservice.networking.istio.io/reviews-vs created
```
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
 $ istioctl version
client version: 1.4.0
control plane version: 1.4.0
data plane version: 1.4.0 (8 proxies)
```
**How was Istio installed?**
using `istioctl` command 
**Environment where bug was observed (cloud vendor, OS, etc)**
Kind cluster
