### ISSUE TITLE
gateway

### ISSUE THREAD

**Issue by aaron-37** [istio/istio#19024]
**Bug description**
Gateway will close all listeners after a period of time,
it's warn log is:
```shell
[14][warning][config] [external/envoy/source/common/config/grpc_mux_impl.cc:153] Ignoring unwatched type URL type.googleapis.com/envoy.api.v2.RouteConfiguration
```

it's my deploy.yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: ingress
  labels:
    app: gateway
spec:
  selector:
    app: gateway
  ports:
  - name: http-a
    port: 8081
  - name: http-b
    port: 8080
  - name: http-kiali
    port: 20001
  - name: http-jager-query
    port: 16686
  - name: http-grafana
    port: 9090
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gateway
  namespace: ingress
  labels:
    app: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        role: ingress
      containers:
      - name: istio-proxy
        image: istio/proxyv2:1.3.4
        ports:
        - containerPort: 15090
          protocol: TCP
          name: http-envoy-prom
        args:
        - proxy
        - router
        - --domain=$(POD_NAMESPACE).svc.cluster.local
        - --drainDuration=45s
        - --parentShutdownDuration=1m0s
        - --connectTimeout=10s
        - --serviceCluster=istio-proxy
        - --zipkinAddress=zipkin.istio-system.svc.cluster.local:9411
        - --statusPort=15020
        - --controlPlaneAuthPolicy=NONE
        - --discoveryAddress=istio-pilot.istio-system.svc.cluster.local:15010
        - --trust-domain=cluster.local
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: ISTIO_META_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: ISTIO_META_CONFIG_NAMESPACE
          value: istio-system
```
it's my gateway.yaml
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kiali
  namespace: ingress
spec:
  selector:
    app: gateway
  servers:
    - port:
        number: 20001
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali
  namespace: ingress
spec:
  hosts:
  - "*"
  gateways:
  - kiali
  http:
  - route:
    - destination:
        host: kiali.istio-system.svc.cluster.local
        port:
          number: 20001

```

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
all component version is 1.3.4

**How was Istio installed?**
Manual installed
**Environment where bug was observed (cloud vendor, OS, etc)**
