### ISSUE TITLE
There are duplicated map field exists in attributemanifest (config.istio.io/v1alpha2) which istioctl manifest generates

### ISSUE THREAD

**Issue by dirty49374** [istio/istio#19030]
**Bug description**

yaml that istioctl manifest command generates has duplicated map entry and is makes some yaml reader cannot read.

```
apiVersion: "config.istio.io/v1alpha2"
kind: attributemanifest
metadata:
  name: istioproxy
  namespace: istio-system
  labels:
    app: istio-telemetry
    release: istio
spec:
  attributes:
...
    context.proxy_version:
      valueType: STRING
...
    context.proxy_version:
      valueType: STRING
```

**Expected behavior**
```
$ istioctl manifest generate | grep context.proxy_version
    context.proxy_version:
```

**Steps to reproduce the bug**
```
$ istioctl manifest generate | grep context.proxy_version
    context.proxy_version:
    context.proxy_version:
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
client version: 1.4.0
control plane version: 1.4.0
data plane version: 1.4.0 (16 proxies)

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
linux
