### ISSUE TITLE
Istio-proxyv2 (>1.3.0), Kubernetes 1.14.x and Canary

### ISSUE THREAD

**Issue by vaikzs** [istio/istio#19038]
**Bug description**
Upon running the application with `docker.io/istio/proxyv2:1.3.0` on Kubernetes v 1.14.7, was the getting the following when verifying the heartbeat using a request header based canary routing: 
response status: `415`
grpc-status-code: 13
grpc-message: `Content-Type is missing from the request`

**Expected behavior**
response status: `200`
grpc-status-code: 0
grpc-message: `{ "message" : "success" }`

**Steps to reproduce the bug**
Use `docker.io/istio/proxyv2` 1.3.0 version in your application deployment plan. (e.g., `docker.io/istio/proxyv2:1.3.0`)

Note: `docker.io/istio/proxyv2:1.2.0` works fine.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

*istioctl version --remote*
```
client version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.4-10-g9b6d31b"}
citadel version: version.BuildInfo{Version:"1.3.0", GitRevision:"c2bd59595ce699b31d0f931885f023028ff7902b-dirty", User:"root", Host:"2795c9cf-d4de-11e9-bd7e-6a558b8effed", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.3.0-rc.3-6-gc2bd595"}
galley version: version.BuildInfo{Version:"1.3.0", GitRevision:"c2bd59595ce699b31d0f931885f023028ff7902b-dirty", User:"root", Host:"2795c9cf-d4de-11e9-bd7e-6a558b8effed", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.3.0-rc.3-6-gc2bd595"}
ingressgateway version: version.BuildInfo{Version:"1.3.0", GitRevision:"c2bd59595ce699b31d0f931885f023028ff7902b", User:"root", Host:"2795c9cf-d4de-11e9-bd7e-6a558b8effed", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.3.0-rc.3-6-gc2bd595"}
ingressgateway version: version.BuildInfo{Version:"1.3.0", GitRevision:"c2bd59595ce699b31d0f931885f023028ff7902b", User:"root", Host:"2795c9cf-d4de-11e9-bd7e-6a558b8effed", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.3.0-rc.3-6-gc2bd595"}
ingressgateway version: version.BuildInfo{Version:"1.3.0", GitRevision:"c2bd59595ce699b31d0f931885f023028ff7902b", User:"root", Host:"2795c9cf-d4de-11e9-bd7e-6a558b8effed", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.3.0-rc.3-6-gc2bd595"}
ingressgateway version: version.BuildInfo{Version:"1.3.0", GitRevision:"c2bd59595ce699b31d0f931885f023028ff7902b", User:"root", Host:"2795c9cf-d4de-11e9-bd7e-6a558b8effed", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.3.0-rc.3-6-gc2bd595"}
ingressgateway version: version.BuildInfo{Version:"1.3.0", GitRevision:"c2bd59595ce699b31d0f931885f023028ff7902b", User:"root", Host:"2795c9cf-d4de-11e9-bd7e-6a558b8effed", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.3.0-rc.3-6-gc2bd595"}
ingressgateway version: version.BuildInfo{Version:"1.3.0", GitRevision:"c2bd59595ce699b31d0f931885f023028ff7902b", User:"root", Host:"2795c9cf-d4de-11e9-bd7e-6a558b8effed", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.3.0-rc.3-6-gc2bd595"}
ingressgateway version: version.BuildInfo{Version:"1.3.0", GitRevision:"c2bd59595ce699b31d0f931885f023028ff7902b", User:"root", Host:"2795c9cf-d4de-11e9-bd7e-6a558b8effed", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.3.0-rc.3-6-gc2bd595"}
ingressgateway version: version.BuildInfo{Version:"1.3.0", GitRevision:"c2bd59595ce699b31d0f931885f023028ff7902b", User:"root", Host:"2795c9cf-d4de-11e9-bd7e-6a558b8effed", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.3.0-rc.3-6-gc2bd595"}
ingressgateway version: version.BuildInfo{Version:"1.3.0", GitRevision:"c2bd59595ce699b31d0f931885f023028ff7902b", User:"root", Host:"2795c9cf-d4de-11e9-bd7e-6a558b8effed", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.3.0-rc.3-6-gc2bd595"}
ingressgateway version: version.BuildInfo{Version:"1.3.0", GitRevision:"c2bd59595ce699b31d0f931885f023028ff7902b", User:"root", Host:"2795c9cf-d4de-11e9-bd7e-6a558b8effed", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.3.0-rc.3-6-gc2bd595"}
ingressgateway version: version.BuildInfo{Version:"1.3.0", GitRevision:"c2bd59595ce699b31d0f931885f023028ff7902b", User:"root", Host:"2795c9cf-d4de-11e9-bd7e-6a558b8effed", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.3.0-rc.3-6-gc2bd595"}
ingressgateway version: version.BuildInfo{Version:"1.3.0", GitRevision:"c2bd59595ce699b31d0f931885f023028ff7902b", User:"root", Host:"2795c9cf-d4de-11e9-bd7e-6a558b8effed", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.3.0-rc.3-6-gc2bd595"}
ingressgateway version: version.BuildInfo{Version:"1.3.0", GitRevision:"c2bd59595ce699b31d0f931885f023028ff7902b", User:"root", Host:"2795c9cf-d4de-11e9-bd7e-6a558b8effed", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.3.0-rc.3-6-gc2bd595"}
ingressgateway version: version.BuildInfo{Version:"1.3.0", GitRevision:"c2bd59595ce699b31d0f931885f023028ff7902b", User:"root", Host:"2795c9cf-d4de-11e9-bd7e-6a558b8effed", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.3.0-rc.3-6-gc2bd595"}
ingressgateway version: version.BuildInfo{Version:"1.3.0", GitRevision:"c2bd59595ce699b31d0f931885f023028ff7902b", User:"root", Host:"2795c9cf-d4de-11e9-bd7e-6a558b8effed", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.3.0-rc.3-6-gc2bd595"}
ingressgateway version: version.BuildInfo{Version:"1.3.0", GitRevision:"c2bd59595ce699b31d0f931885f023028ff7902b", User:"root", Host:"2795c9cf-d4de-11e9-bd7e-6a558b8effed", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.3.0-rc.3-6-gc2bd595"}
ingressgateway version: version.BuildInfo{Version:"1.3.0", GitRevision:"c2bd59595ce699b31d0f931885f023028ff7902b", User:"root", Host:"2795c9cf-d4de-11e9-bd7e-6a558b8effed", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.3.0-rc.3-6-gc2bd595"}
ingressgateway version: version.BuildInfo{Version:"1.3.0", GitRevision:"c2bd59595ce699b31d0f931885f023028ff7902b", User:"root", Host:"2795c9cf-d4de-11e9-bd7e-6a558b8effed", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.3.0-rc.3-6-gc2bd595"}
ingressgateway version: version.BuildInfo{Version:"1.3.0", GitRevision:"c2bd59595ce699b31d0f931885f023028ff7902b", User:"root", Host:"2795c9cf-d4de-11e9-bd7e-6a558b8effed", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.3.0-rc.3-6-gc2bd595"}
ingressgateway version: version.BuildInfo{Version:"1.3.0", GitRevision:"c2bd59595ce699b31d0f931885f023028ff7902b", User:"root", Host:"2795c9cf-d4de-11e9-bd7e-6a558b8effed", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.3.0-rc.3-6-gc2bd595"}
pilot version: version.BuildInfo{Version:"1.3.0", GitRevision:"c2bd59595ce699b31d0f931885f023028ff7902b-dirty", User:"root", Host:"2795c9cf-d4de-11e9-bd7e-6a558b8effed", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.3.0-rc.3-6-gc2bd595"}
sidecar-injector version: version.BuildInfo{Version:"1.3.0", GitRevision:"c2bd59595ce699b31d0f931885f023028ff7902b-dirty", User:"root", Host:"2795c9cf-d4de-11e9-bd7e-6a558b8effed", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.3.0-rc.3-6-gc2bd595"}
telemetry version: version.BuildInfo{Version:"1.3.0", GitRevision:"c2bd59595ce699b31d0f931885f023028ff7902b-dirty", User:"root", Host:"2795c9cf-d4de-11e9-bd7e-6a558b8effed", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.3.0-rc.3-6-gc2bd595"}
```

*kubectl version*

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:39:02Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

*helm version*

```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

**How was Istio installed?**

Using helm charts

**Environment where bug was observed (cloud vendor, OS, etc)**

Browser / Rest Client

**Comment by howardjohn** [comment]
What exactly is the request you are sending? any way we can reproduce this on our side?

**Comment by vaikzs** [comment]
Simple heartbeat check from the application created (say a Java endpoint with `/health`). The issue can be reproduced once you have the same Kubernetes version with Istio 1.3.0, `IstioProxyv2/1.3.0` and a CANARY based deployment. In my case, it was a request header routed canary.

**Comment by howardjohn** [comment]
Is this grpc traffic?

**Comment by vaikzs** [comment]
I'm afraid so. Is that an open issue logged, that I'm missing?

**Comment by howardjohn** [comment]
No, I have never seen this, I want to reproduce it so we can root cause. Can you give a minimal reproducer, or we are unlikely to figure this out

**Comment by vaikzs** [comment]
Unfortunately, I'm unable to provide the reproducer at the moment but I can prepare parallelly. To add more details to reproduce: 
1) 3 `deployment.yaml` (assume distinct images for each) with 1 `service.yaml`
2) These plans have manual sidecar injection (which is a practice we plan to get rid off) that specifies
`istio-proxy : 1.3.0` and `istio-proxy-init : 1.3.0` images separately
3) Apps in the deployments are gRPC services WITH gRPC transcoding EnvoyFilter, exposing the REST interface. Having the descriptor mounted from Cloud Storage at the time of pod init phase 
4) Finally, focused canary based virtual service is present to route request with different headers to deployment plans 1, 2, or 3 (defaults to 1)


After reverting istio-proxy and istio-proxy-init version from 1.3.0 to 1.2.0 in step 2), the issue was resolved.

**Comment by howardjohn** [comment]
> Apps in the deployments are gRPC services WITH gRPC transcoding EnvoyFilter, exposing the REST interface. Having the descriptor mounted from Cloud Storage at the time of pod init phase

So you guys have some custom stuff running here? It seems really likely this is related... can you give more info

> Finally, focused canary based virtual service is present to route request with different headers to deployment plans 1, 2, or 3 (defaults to 1)

can you give the virtual service config?

It is very hard to debug without more exact information

**Comment by vaikzs** [comment]
> `java-grpc-application.yaml`
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: java-grpc-application
    version: v1
  name: java-grpc-application-1
  namespace: java-grpc-application-namespace
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 10
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: java-grpc-application
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /
        prometheus.io/port: "8082"
        prometheus.io/scrape: "true"
        sidecar.istio.io/status: '{"version":"761ebc5a63976754715f22fcf548f05270fb4b8db07324894aebdb31fa81d960","initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["istio-envoy","istio-certs"],"imagePullSecrets":null}'
      creationTimestamp: null
      labels:
        app: java-grpc-application
        version: v1
    spec:
      containers:
      # - env:
        # .... bunch of environmental variables for the image
        image: java-grpc-application-imagepath:1.0
        imagePullPolicy: IfNotPresent
        # livenessProbe for the grpc health check
        livenessProbe:
          exec:
            command:
            - ./bin/grpc_health_probe
            - -addr=localhost:50051
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
        name: java-grpc-application-1
        ports:
        - containerPort: 50051
          name: grpc
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 1
          successThreshold: 1
          tcpSocket:
            port: 50051
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "7"
            memory: 18Gi
          requests:
            cpu: "6"
            memory: 16Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        # volume 
        volumeMounts:
        # assume that its an azure storage
        - mountPath: /etc/filterfiles
          name: cloudstorage
      - args:
        - proxy
        - sidecar
        - --domain
        - $(POD_NAMESPACE).svc.cluster.local
        - --configPath
        - /etc/istio/proxy
        - --binaryPath
        - /usr/local/bin/envoy
        - --serviceCluster
        - java-grpc-application-1.$(POD_NAMESPACE)
        - --drainDuration
        - 45s
        - --parentShutdownDuration
        - 1m0s
        - --discoveryAddress
        - istio-pilot.istio-system:15010
        - --zipkinAddress
        - zipkin.istio-system:9411
        - --dnsRefreshRate
        - 300s
        - --connectTimeout
        - 10s
        - --proxyAdminPort
        - "15000"
        - --concurrency
        - "2"
        - --controlPlaneAuthPolicy
        - NONE
        - --statusPort
        - "15020"
        - --applicationPorts
        - "50051"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: ISTIO_META_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: ISTIO_META_CONFIG_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: ISTIO_META_INTERCEPTION_MODE
          value: REDIRECT
        - name: ISTIO_META_INCLUDE_INBOUND_PORTS
          value: "50051"
        - name: ISTIO_METAJSON_LABELS
          value: |
            {"app":"java-grpc-application-1"}
        image: docker.io/istio/proxyv2:1.3.0
        imagePullPolicy: IfNotPresent
        name: istio-proxy
        ports:
        - containerPort: 15090
          name: http-envoy-prom
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 1337
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/filterfiles
          name: azurestorage
        - mountPath: /etc/istio/proxy
          name: istio-envoy
        - mountPath: /etc/certs/
          name: istio-certs
          readOnly: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: java-grpc-application-secrets
      initContainers:
      - args:
        - -p
        - "15001"
        - -u
        - "1337"
        - -m
        - REDIRECT
        - -i
        - '*'
        - -x
        - ""
        - -b
        - "50051"
        - -d
        - "15020"

        image: docker.io/istio/proxy_init:1.3.0
        imagePullPolicy: IfNotPresent
        name: istio-init
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 10Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          runAsNonRoot: false
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/filterfiles
          name: cloudstorage
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - azureFile:
          readOnly: true
          secretName: azure-secret
          shareName: descriptor
        name: cloudstorage
      - emptyDir:
          medium: Memory
        name: istio-envoy
      - name: istio-certs
        secret:
          defaultMode: 420
          optional: true
          secretName: istio.default
status:
  availableReplicas: 10
  conditions:
  - lastTransitionTime: "2019-11-19T21:26:16Z"
    lastUpdateTime: "2019-11-19T21:26:16Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 8
  readyReplicas: 10
  replicas: 10
  updatedReplicas: 10

```
> `java-grpc-application-service.yaml`
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: java-grpc-application
  name: java-grpc-application
  namespace: java-grpc-application-namespace
spec:
  clusterIP: 10.0.0.0
  ports:
  - name: grpc-port
    port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: java-grpc-application
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

```
> `EnvoyFilter.yaml`
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: envoy-proxy
  namespace: java-grpc-application-namespace
spec:
  filters:
  - filterConfig:
      printOptions:
        add_whitespace: true
        alwaysPrintPrimitiveFields: false
      proto_descriptor: /etc/filterfiles/descriptor_set.pb
      services:
      - grpc.health.v1.Health
    filterName: envoy.grpc_json_transcoder
    filterType: HTTP
    insertPosition:
      index: FIRST
      relativeTo: envoy.router
    listenerMatch:
      listenerProtocol: HTTP
      listenerType: SIDECAR_INBOUND
      portNumber: 50051
  workloadLabels:
    app: java-grpc-application
```
> java-grpc-application-virtual-service.yaml
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: java-grpc-application-virtual-service
  namespace: istio-system
spec:
  gateways:
  - grpc-gateway
  - http-gateway
  hosts:
  - ...
  http:
  - match:
    - headers:
        version:
          exact: v2
      uri:
        prefix: /
    route:
    - destination:
        host: java-grpc-application.java-grpc-application-namespace.svc.cluster.local
        port:
          number: 50051
        subset: v2
      headers:
        response:
          set:
            version: v2
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: java-grpc-application.java-grpc-application-namespace.svc.cluster.local
        port:
          number: 50051
        subset: v1
      headers:
        response:
          set:
            version: v1

```
> `gateways.yaml`
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: http-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http2
      number: 80
      protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: grpc-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http2
      number: 50051
      protocol: HTTP

```
> `destination-rule.yaml`
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: java-grpc-application-destination-rule
  namespace: istio-system
spec:
  host: java-grpc-application.java-grpc-application-namespace.svc.cluster.local
  port:
    number: 50051
  subsets:
  - labels:
      version: v1
    name: v1
  - labels:
      version: v2
    name: v2

```
