### ISSUE TITLE
Mixer - Fluentd Adapter can't encode time with milliseconds

### ISSUE THREAD

**Issue by weimch** [istio/istio#19070]
Hi guys. When I use Fluentd collecting logentry, I find that current Fluentd Adapter can't encode timestamp with milliseconds(result from fluentd stdout).
`
2019-11-19 10:40:44.000000000 +0000 weimch-multisvc-log-instance.instance.default: {"reporter":"destination","severity":"info","responseCode":200,"source":"frontend","destination":"currencyservice","lantency":6}
`
The environment of my situation is: 
1. istio(v1.3.0) 
2. fluentd(1.7.4)

I really want the milliseconds part because my study will adopt queuing theory in which some values are canculated using this information.

So, I checked the source of fluentd adatper and the [fluent-logger-golang](https://github.com/fluent/fluent-logger-golang/) library you use. I find that with a tiny changed, the fluentd adater can encode timestamp with milliseconds.

The change I made is (line 129 of [this file](https://github.com/istio/istio/blob/master/mixer/adapter/fluentd/fluentd.go)):
``` golang
han.logger, err = newFluentd(fluent.Config{FluentPort: p, FluentHost: h, BufferLimit: int(batchBytes), WriteTimeout: timeout, SubSecondPrecision: true})
```

Just a SubSecondPrecision will reach below result(also got from fluentd)
`
2019-11-19 13:50:38.519705000 +0000 weimch-multisvc-log-instance.instance.default: {"destination":"currencyservice","lantency":2,"severity":"info","reporter":"source","responseCode":200,"source":"frontend"}
`

I find the **SubSecondPrecision: true** from config of [fluent-logger-golang this file](https://github.com/fluent/fluent-logger-golang/blob/master/fluent/fluent.go) library
``` golang
type Config struct {
        ...
	// Sub-second precision timestamps are only possible for those using fluentd
	// v0.14+ and serializing their messages with msgpack.
	SubSecondPrecision bool `json:"sub_second_precision"`
       ...
}
```

Maybe the developers don't encoded for better compatible with all the fluentd version, but sometimes the situation like me, it's stronly needed.

For me, this issuse is more like a feature than a bug. Will you consider to add the milliseconds support? I think it's very easy to  add some code. Maybe some additional options should be supported by fluentd adapter.(such as sub_second_precision bool or fluentd_version)

Thanks ! ! ! !

I will paste my config for you can easily reproduce my situation.

**telemetry config: instance-handler-rule**
```yaml
# Configuration for metric instances
apiVersion: config.istio.io/v1alpha2
kind: instance
metadata:
  name: weimch-multisvc-log-instance
  namespace: default
spec:
  compiledTemplate: logentry
  params:
    severity: '"info"'
    timestamp: request.time
    variables:
      reporter: conditional((context.reporter.kind | "inbound") == "outbound", "source", "destination")
      source: source.labels["app"] | source.workload.name | "unknown"
      destination: destination.labels["app"] | destination.workload.name | "unknown"
      responseCode: response.code | 0
      lantency: response.duration | "0ms"
      # at: request.time
    monitored_resource_type: '"UNSPECIFIED"'
---
# Configuration for a Prometheus handler
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: weimch-multisvc-log-handler
  namespace: default
spec:
  # compiledAdapter: stdio
  # params:
  #   severity_levels:
  #     INFO : INFO
  #   outputAsJson: true
  compiledAdapter: fluentd
  params:
    address: "fluentd.default.svc.cluster.local:24224"
    integerDuration: true
    instanceBufferSize: 10240
    pushIntervalDuration: "10s"
---
# Rule to send metric instances to a Prometheus handler
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: weimch-multisvc-log-rule
  namespace: default
spec:
  match: 'destination.workload.name!="redis-cart" && source.workload.name!="unknown"'
  actions:
  - handler: weimch-multisvc-log-handler
    instances: [ weimch-multisvc-log-instance ]
---
```
**Fluentd config**
```
<match fluent.**>
  @type null
</match>
<source>
  @type forward
</source>
<filter **>
  @type stdout
</filter>
<match **>
  @type elasticsearch
  @log_level info
  include_tag_key true
  host elasticsearch
  port 9200
  logstash_format true
  <buffer>
    flush_thread_count 2
    flush_interval 5s
    retry_forever 
    retry_max_interval 30
    chunk_limit_size 2M
    queue_limit_length 8
  </buffer>
</match>
```
