### ISSUE TITLE
Provide A client-ip header from istio ingress

### ISSUE THREAD

**Issue by nigeltiany** [istio/istio#19075]
**Describe the feature request**
Provide a header from istio ingress which the originating client ip.
My use case: GRPC web with a Golang backend
**Describe alternatives you've considered**
1) setting ```externalTrafficPolicy: Local``` 
This is not an option because of micro-servicing. A micro-service pod may be summoned and it may not be in the same VM
2) Adding an ```EnvoyFilter``` with a ```listener filter```:```envoy.listener.proxy_protocol``` did not work
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: proxy-protocol
spec:
  configPatches:
  - applyTo: LISTENER
    patch:
      operation: MERGE
      value:
        listener_filters:
        - name: envoy.listener.proxy_protocol
```

[X] Configuration Infrastructure
[X] Networking

**Additional context**
This issue was being tracked [here](https://github.com/istio/istio/issues/7679) but it is now stale
[This comment seemed to offer a solution](https://github.com/istio/istio/issues/7679#issuecomment-412739471)
[Another related discussion](https://github.com/istio/api/pull/897)
[And another related discussion](https://github.com/istio/istio/pull/8001)
[filters work around](https://github.com/istio/istio/pull/12748)

Adding the Envoy filter causes connections to be dropped.
- The server which could connect to a redis instance via an internal ip cannot connect
```read tcp 10.<internal>:55986->10.<internal>:6379: read: connection reset by peer```
- Web client connections get dropped too
```net::ERR_CONNECTION_RESET```

Golang metadata from context
```
map[
  :authority:[the.app] 
  accept:[*/*] 
  accept-encoding:[gzip, deflate, br] 
  accept-language:[en-US,en;q=0.9] 
  authorization [eyJhbGciOiJIUzI1NiIsInR5cVXmMdY..] 
  content-type:[application/grpc] 
  grpc-accept-encoding:[identity,deflate,gzip] 
  origin:[https://the.app] 
  referer:[https://the.app/] 
  sec-fetch-mode:[cors] 
  sec-fetch-site:[same-site] 
  user-agent:[Mozilla/5.0 (X11; Linux...] 
  x-b3-parentspanid:[d829fede12935a91] 
  x-b3-sampled:[0] 
  x-b3-spanid:[c7a42c5b427488bc] 
  x-b3-traceid:[e62c2bc0c9923a03d829fede12935a91] 
  x-envoy-internal:[true] 
  x-forwarded-for:[10.<internal>] 
  x-forwarded-proto:[https] 
  x-grpc-web:[1] 
  x-request-id:[5db9525c-09a8-419f-82c1-591a5f51d712] 
  x-user-agent:[grpc-web-dart/0.1]
]
```
A separate header would maintain the expected behavior, save istio from possible vulnerabilities and still meet the requirement
