### ISSUE TITLE
GKE Istio Telemetry responding with "connection refused" on port 42422

### ISSUE THREAD

**Issue by rbraeunlich** [istio/istio#19099]
**Bug description**
I configured my existing Prometheus to scrape metrics from all of the Istio services by copied the jobs from the Istio Prometheus configuration. The job that reads the "prometheus port" from the istio-telemetry service only get a "connection refused" as answer.
The Prometheus job looks like this:
```
        - job_name: 'istio-mesh'
          kubernetes_sd_configs:
            - role: endpoints
              namespaces:
                names:
                  - istio-system
          relabel_configs:
            - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
              action: keep
              regex: istio-telemetry;prometheus
```
The telemetry service is alive and well. There is nothing to see in the logging, except for 
`warn adapters Unknown workload instance type: unknown {"adapter": "handler.stackdriver.istio-system"}`, which I think is not related to my problem. 

**Expected behavior**

The service should expose its metrics to Prometheus.

**Steps to reproduce the bug**

Install Istio in GKE and configure Prometheus.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
`istioctl version --remote`
client version: 1.4.0
control plane version: 0f52910f512029f0f8860b4c586cf9667545dd35
data plane version:  (25 proxies)
`kubectl version`
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-gke.23", GitCommit:"81c87c699557fed991e292cd328b2129c2f242a2", GitTreeState:"clean", BuildDate:"2019-11-07T19:23:23Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
`helm version`
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

**How was Istio installed?**

GKE checkbox

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE
