### ISSUE TITLE
istio ingress gateway is not sending traffic to virtual host

### ISSUE THREAD

**Issue by dhineshbabuelango** [istio/istio#19094]
We are using istio in AWS EKS. We have 2 istio ingress gateway(admin and ingress) use for 2 different purpose. one of the ingress gateway which was working fine earlier was getting the below error. I tried re-installing istio but still the same issue

gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) 0.0.0.0_443: error adding listener '0.0.0.0:443': multiple filter chains with the same matching rules are defined

I am using istio version 1.3.1, it was working fine till today morning and everytime I try to hit the application, seeing the log mentioned above in the ingress gateway.

Below is the only gateway i used for the selector admin-ingressgateway

```
spec:
  selector:
    istio: admin-ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: ingressgateway-certs
      maxProtocolVersion: TLSV1_2
      minProtocolVersion: TLSV1_2
      mode: SIMPLE
  - hosts:
    - '*.isam.internal.dev.com'
    port:
      name: https-isam
      number: 443
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
```
