### ISSUE TITLE
Request: analyzer for missing gateway certificateName

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19097]
See docs https://istio.io/docs/tasks/traffic-management/ingress/secure-ingress-sds/

Its pretty easy to reference a secret that does not exist here

**Comment by JimmyCYJ** [comment]
@howardjohn Could you please elaborate more on the analyzer, e.g. current status of analyzer, expected behavior of the analyzer?

**Comment by JimmyCYJ** [comment]
https://github.com/istio/istio/blob/master/galley/pkg/config/analysis/README.md

**Comment by howardjohn** [comment]
@JimmyCYJ the analyzer tool is shipped, see https://istio.io/docs/ops/diagnostic-tools/istioctl-analyze/

**Comment by sushicw** [comment]
Some notes:

* We'd need to add Secret as another k8s resource type ingested for analysis, similar to how we've done for Deployments, Pods, etc. 

* Example YAML that should trigger a validation message: 
```yaml
apiVersion: v1
data:
  cert: aHVzaCBodXNoIGh1c2gK
  key: c2VjcmV0IHNlY3JldAo=
kind: Secret
metadata:
  name: httpbin-credential
  namespace: istio-system
type: Opaque
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mygateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: "httpbin-credential" # Correct credential
    hosts:
    - "httpbin.example.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mygateway-bogus
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 4430
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: "httpbin-credential-bogus" # Should break, wrong credential name
    hosts:
    - "httpbin.example.com"
```
