### ISSUE TITLE
Timeout doesn't work with HTTPS hosts

### ISSUE THREAD

**Issue by hubermark** [istio/istio#19101]
**Bug description**
I try to configure a timeout for an HTTPS host but the configuration has no effect.

Followed instructions of [Access External Service](https://preliminary.istio.io/docs/tasks/traffic-management/egress/egress-control/#access-an-external-https-service) and [Timeouts](https://preliminary.istio.io/docs/tasks/traffic-management/request-timeouts/)

**Expected behavior**
When a timeout of 0.001s is configured I expect all calls fail by Istio with a 504 Gateway Timeout

**Steps to reproduce the bug**
Set outbound traffic policy mode to REGISTRY_ONLY

 1. check if an outgoing call is now forbidden for not configured hosts (out of pod)
`curl -v http://httpstat.us/200?sleep=5000` -> 502 Bad Gateway

2. Define ServiceEntry to allow outgoing call
```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
    name: se-httpstat
    namespace: istio-apps
spec:
    hosts:
        - httpstat.us
    location: MESH_EXTERNAL
    ports:
        - name: httpstat
          number: 80
          protocol: HTTP
    resolution: DNS
    location: MESH_EXTERNAL
EOF
```

3. Check if an outgoing call is now allowed (out of pod)
`curl -v http://httpstat.us/200?sleep=5000` -> 200 OK

4. Define a timeout for host httpstat.us
```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
    name: vs-httpstat-timeout
    namespace: istio-apps
spec:
    hosts:
    - httpstat.us
    http:
    - route:
      - destination:
          host: httpstat.us
      timeout: 1.1s
EOF
```

5. Check if an outgoing call is now running into the defined timeout (out of pod)
`curl -v http://httpstat.us/200?sleep=5000` -> 504 Gateway Timeout

6.  Check if an outgoing HTTPS call is not allowed (out of pod)
`curl -v https://www.google.com` -> SSL_ERROR_SYSCALL

7. Define ServiceEntry to allow outgoing HTTPS call
```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
    name: se-google
    namespace: istio-apps
spec:
    hosts:
        - www.google.com
    location: MESH_EXTERNAL
    ports:
        - name: https-google
          number: 443
          protocol: HTTPS
    resolution: DNS
    location: MESH_EXTERNAL
EOF
```

8.  Check if the outgoing HTTPS call is now allowed (out of pod)
`curl -I https://www.google.com | grep  "HTTP/"` -> HTTP/2 200

So everything is fine until now when I try to set a timeout for the HTTPS call

9. Define timeout for host www.google.com
```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
    name: vs-google-timeout
    namespace: istio-apps
spec:
    hosts:
    - www.google.com
    http:
    - route:
      - destination:
          host: www.google.com
      timeout: 0.001s
EOF
```

10. Check if an outgoing call is now running into the defined timeout (out of pod)
`curl -I https://www.google.com | grep  "HTTP/"` 
Got -> HTTP/2 200 instead of 504 Gateway Timeout

I used www.google.com as an example to hide the real HTTPS endpoint I want to call but the effect is the same.

**Version `kubectl version` and `helm version` if you used Helm)**
Istio:
client version: 1.2.0
citadel version: 1.3.3
egressgateway version: 1.3.3
galley version: 1.3.3
ingressgateway version: 1.3.3
pilot version: 1.3.3
policy version: 1.3.3
sidecar-injector version: 1.3.3
telemetry version: 1.3.3

Kubernetes
Client Version: version.Info{Major:"1", Minor:"14",
Server Version: version.Info{Major:"1", Minor:"14+"

Helm
Client: &version.Version{SemVer:"v2.14.1"

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
GCP

**Comment by hubermark** [comment]
I found a way to bypass the problem

From Step 7. Define ServiceEntry to allow outgoing HTTPS call

1. Only define HTTP outgoing ServiceEntry instead HTTPS
```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
    name: se-google
    namespace: istio-apps
spec:
    hosts:
        - www.google.com
    location: MESH_EXTERNAL
    ports:
        - name: http-google
          number: 80
          protocol: HTTP
    resolution: DNS
    location: MESH_EXTERNAL
EOF
```

2. Define VirtualService to re-route
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
    name: vs-google
spec:
    hosts:
        - www.google.com
    http:
        - name: "google-route"
          match:
              - port: 80
          route:
              - destination:
                    host: www.google.com
                    subset: google-tls-origination
                    port:
                        number: 443
          timeout: 0.5s
```

3. Create DestinationRule to change from internal HTTP to outgoing HTTPS (mTLS)
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
    name: google-mms
spec:
    host: www.google.com
    trafficPolicy:
        portLevelSettings:
            - port:
                  number: 443
              tls:
                  mode: SIMPLE # or ISTIO_MUTUAL if global mTLS is configured
    subsets:
        - name: google-tls-origination
```
You hava HTTPS and Timeout also is working and additionally you can see Traffic in Istio Service Dashboard on Grafana
