### ISSUE TITLE
Updating hosts list in existing gateway causes unexpected results

### ISSUE THREAD

**Issue by jaygorrell** [istio/istio#19110]
**Bug description**
I have an existing Istio Gateway with a list of 6 domains and a `SIMPLE` tls cert. These domains all work fine. After adding a new domain to the list that also should work with the same (wildcard) certificate, the new domain returns `curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to test.mydomain.com:443` from curl, while the existing domains continue to function properly.

Moving the new domain to a new item under the `servers` list (with only that domain in `servers.hosts` and all other settings (port, tls) the same) fixes the issue.

**Expected behavior**
Editing an existing gateway's host list should work as expected.

**Steps to reproduce the bug**
1. Create a gateway like this:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mygateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - "mydomain.com"
        - "www.mydomain.com"
      port:
        number: 443
        name: https-mydomain
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: "mycert"
```
2. Verify these settings work as expected.
3. Update the Gateway with a new domain like:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mygateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - "mydomain.com"
        - "www.mydomain.com"
        - "test.mydomain.com"
      port:
        number: 443
        name: https-mydomain
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: "mycert"
```
4. Verify that `mydomain.com` and `www.mydomain.com` continue to work while `test.mydomain.com` returns SSL errors.
5. Move the new domain to it's own item in the list, like:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mygateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - "mydomain.com"
        - "www.mydomain.com"
      port:
        number: 443
        name: https-mydomain
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: "mycert"
    - hosts:
        - "test.mydomain.com"
      port:
        number: 443
        name: https-mydomain
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: "mycert"
```
6. Verify that all domains work correctly.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.3.5

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS

**Comment by howardjohn** [comment]
I attempted to reproduce:

```yaml
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls
  namespace: istio-system
spec:
  secretName: tls-cert
  issuerRef:
    name: letsencrypt-staging
  commonName: MY_IP.xip.io
  dnsNames:
  - MY_IP.xip.io
  - MY_IP.nip.io
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tls
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: tls-cert
    hosts:
    - MY_IP.xip.io
    - MY_IP.nip.io # Added later
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tls
spec:
  hosts:
  - "*"
  gateways:
  - tls
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: httpbin
        port:
          number: 80
```

When I applied this, requests to xip.io worked. Then, I tried nip.io (not yet in gateway) and got the same `curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection`.

Then i added nip.io to the gateway, and nip.io worked. This was on Istio 1.6.

So it seems like the update to the gateway just didn't go through. This could be propagation delays, but seems unlikely. It may also be some bug in the older version that has since been fixed ,ro I failed to properly reproduce
