### ISSUE TITLE
istioctl doesn't seem to respect disablePolicyChecks

### ISSUE THREAD

**Issue by tbarrella** [istio/istio#19139]
**Bug description**
When using `istioctl manifest`, `values.global.disablePolicyChecks` doesn't seem to have an effect

**Expected behavior**
Setting `disablePolicyChecks: false` configures the mesh data properly in the istio ConfigMap

**Steps to reproduce the bug**
- Create IstioControlPlane config `config.yaml` like
```yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  values:
    global:
      disablePolicyChecks: false
      policyCheckFailOpen: true  # this is still respected
```
- `istioctl manifest generate -f config.yaml | grep disablePolicyChecks:`
- disablePolicyChecks is `true`

Looking at https://github.com/istio/istio/blob/1.4.0/install/kubernetes/helm/istio/templates/configmap.yaml suggests that maybe `values.mixer.policy.enabled` needs to be set to `true`, but that didn't seem to help

**Version**
1.4.0

**How was Istio installed?**
istioctl

**Comment by richardwxn** [comment]
The issue is coming from installer, https://github.com/istio/installer/blob/master/istio-control/istio-discovery/templates/configmap.yaml#L90, the configmap value depends on values.pilot.policy.enabled instead of values.global.disablePolicyChecks although we have disablePolicyChecks defined in global. I may need to think what's the best way to reduce the confusion here.

For now you can use this config as a workaround:
```yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  values:
    pilot:
      policy:
        enabled: true
    global:
      policyCheckFailOpen: true
```
