### ISSUE TITLE
istio-ingressgateway is not getting a load balancer External IP(AWS eks)

### ISSUE THREAD

**Issue by abhinavkorpal** [istio/istio#19138]
**Bug description**

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed? - using all profiles istioctl and helm both

**Environment where bug was observed (cloud vendor, OS, etc) : Ubuntu AWS EKS

**Comment by howardjohn** [comment]
I suspect this is not istio specific. Can you apply a simple load balancer type? Like
```yaml
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  ports:
  - name: http
    port: 80
  type: LoadBalancer
```

if that works, then it may be Istio specific. If not, you make need to configure something in AWS
