### ISSUE TITLE
Mixer telemetry needs liveness check for 42422

### ISSUE THREAD

**Issue by rvennam** [istio/istio#19164]
**Bug description**

Sometimes my Istio gets into a state where istio-telemetry pod shows Running, but nothing responds on 42422/metrics. 

Prometheus Dashboard -> Status -> Targets shows 42422 is down.
![image](https://user-images.githubusercontent.com/5502967/69480763-4af6b280-0dd8-11ea-824e-0ff14b513111.png)

Manually restarting the telemetry pod fixes it.

istio-telemetry exposes ports 9091/TCP, 15014/TCP, 42422/TCP. Liveness check exists for :15014/version but not 9091 or 42422

Can a liveness check be added to :42422/metrics? Something like:

``` 
        livenessProbe:
          httpGet:
            path: /metrics
            port: 42422
          initialDelaySeconds: 5
          periodSeconds: 5
```

**Expected behavior**
If istio-telemetry pod shows Running, then 42422/metrics should not be down.

**Steps to reproduce the bug**
Does not happen consistently. It has to do with installation ordering in the operator.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

client version: 1.4.0
control plane version: 1.4.0
data plane version: 1.4.0 (11 proxies)

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T23:49:20Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3+IKS", GitCommit:"6511e42c1f1568ac32d99ae33316985c43dbcca6", GitTreeState:"clean", BuildDate:"2019-11-13T22:36:46Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
Operator

**Environment where bug was observed (cloud vendor, OS, etc)**
IBM Cloud

[mixer.log](https://github.com/istio/istio/files/3882594/mixer.log)

**Comment by mandarjog** [comment]
The problem usually is when config cannot be loaded or has an error. It seems odd to kill mixer or mark it unready.
In your case why was it not listening on the port ?

**Comment by rvennam** [comment]
See attached log from my mixer pod: [mixer.log](https://github.com/istio/istio/files/3882594/mixer.log)

There are a lot of errors at startup. I think it might be that CRD's are not in place yet? Would need someone with more expertise to take a look. Could be a ordering issue laying down the components (I'm using the new operator to install)

I'll chase this down with the operator team too, but maybe mixer can also benefit from better health checks

**Comment by sdake** [comment]
> The problem usually is when config cannot be loaded or has an error. It seems odd to kill mixer or mark it unready.
> In your case why was it not listening on the port ?

@mandarjog I took a look at a related log a few days ago, and there were 20+ looping failures withOUT a restart of mixer.  @douglas-reid had indicated the mixer code should retry 3 times, then exit, then restart and all should be golden:

<img width="891" alt="Screen Shot 2019-11-23 at 7 42 30 PM" src="https://user-images.githubusercontent.com/755849/69488647-81a8e900-0e29-11ea-8abe-1d252c4809f5.png">

**Comment by sdake** [comment]
> See attached log from my mixer pod: [mixer.log](https://github.com/istio/istio/files/3882594/mixer.log)
> 
> There are a lot of errors at startup. I think it might be that CRD's are not in place yet? Would need someone with more expertise to take a look. Could be a ordering issue laying down the components (I'm using the new operator to install)

CRDs may not be installed yet - not a mixer genius so I am unclear...  but...  reordering the install is not the right solution.  The problem here - from people who are mixer geniuses (e.g. @douglas-reid), speculatively appears to be galley hasn't done something correctly, and then mixer essentially spins until universe heat death..

> 
> I'll chase this down with the operator team too, but maybe mixer can also benefit from better health checks

Can't say I disagree, only that I would trust and defer to the telemetry team to make the right technical judgment around healthchecking of mixer.

**Comment by sdake** [comment]
Release blocker for 1.5, and should be prioritized for 1.4 as this reproduces on all platforms and results in broken telemetry.

**Comment by mandarjog** [comment]
Mixer should die If it cannot get config from galley in a reasonable amt of time. If Base CRDs are not available then mixer should exit, that is definitely the intent. was it the situation that Mixer never got ready even though eventually galley got ready and all crds were in place.

**Comment by sdake** [comment]
@mandarjog I believe the CRDs were in place, and I believe galley was ready, but I can't confirm galley was ready.  This is reproducible atleast in @rvennam 's environment.  In the next iteration of reproduction perhaps @rvennam can provide more information.  We were both at kubecon during the initial reproduction and had minimal debug time.

Cheers
-steve

**Comment by linsun** [comment]
@rvennam can you clarify whether you hit this during the initial install time or afterwards for a while?  For the initial install time, it is common for mixer telemetry to restart 2 times to reach running.

Re livenessProbe, i don't think you can do multiple probes in there.   Also, it is best not to put dependencies in the livenessProbe.   I propose we use readinessProbe if port 42422 is a hard dependency for mixer telemetry to be useful.  One thing interest: `the readiness probe will continue to be called throughout the lifetime of the container, every periodSeconds, so that the container can make itself temporarily unavailable when one of its dependencies is unavailable, or while running a large batch job, performing maintenance, or something similar.`

Can you clarify what is broken with port 42422 isn't listening?  Are mixer no longer passing any telemetry data and send to backend systems?  

cc @mandarjog @douglas-reid @costinm  for input and thoughts.

**Comment by rvennam** [comment]
The problem is not during Install. I waited a long time after install and telemetry pods showed `Running`. 

First thing I noticed was that the various dashboards (grafana, kiali) are not showing any application data. 

I followed this guide: https://istio.io/docs/ops/common-problems/network-issues/ and saw that istio-telemetry:42422/metrics is DOWN

I did a port-forward to the telemetry pod:
`kubectl port-forward -n istio-system istio-telemetry-75b777cd59-pftm9 42422 &`
and then tried `curl 127.0.0.1:42422/metrics` and got a Connection Refused. 

`k logs istio-telemetry-75b777cd59-pftm9 -n istio-system -c mixer`:
[mixer.log](https://github.com/istio/istio/files/3887915/mixer.log)
```
2019-11-20T00:09:55.544128Z	error	36 errors occurred:
	* instance='attributes.instance.istio-system': error evaluating AttributeBinding expression for attribute key 'destination.uid': unknown attribute destination.uid
	* instance='tcpbytereceived.instance.istio-system': failed to evaluate expression for field 'Value'; unknown attribute connection.received.bytes
	* instance='tcpconnectionsopened.instance.istio-system': failed to evaluate expression for field 'Dimensions[reporter]'; unknown attribute context.reporter.kind
	* instance='tcpconnectionsclosed.instance.istio-system': failed to evaluate expression for field 'Dimensions[reporter]'; unknown attribute context.reporter.kind
	* instance='tcpbytesent.instance.istio-system': failed to evaluate expression for field 'Value'; unknown attribute connection.sent.bytes
	* instance='requestduration.instance.istio-system': failed to evaluate expression for field 'Value'; unknown attribute response.duration
	* instance='responsesize.instance.istio-system': failed to evaluate expression for field 'Value'; unknown attribute response.size
	* instance='requestcount.instance.istio-system': failed to evaluate expression for field 'Dimensions[source_principal]'; unknown attribute source.principal
	* instance='requestsize.instance.istio-system': failed to evaluate expression for field 'Value'; unknown attribute request.size
	* rule='promtcpconnectionclosed.rule.istio-system'.Match: unknown attribute context.protocol
	* action='promtcpconnectionclosed.rule.istio-system[0]': Instance not found: instance='tcpconnectionsclosed'
	* action='promtcpconnectionclosed.rule.istio-system[0]': No valid instances found
	* rule=promtcpconnectionclosed.rule.istio-system: No valid actions found in rule
	* rule='promtcpconnectionopen.rule.istio-system'.Match: unknown attribute context.protocol
	* action='promtcpconnectionopen.rule.istio-system[0]': Instance not found: instance='tcpconnectionsopened'
	* action='promtcpconnectionopen.rule.istio-system[0]': No valid instances found
	* rule=promtcpconnectionopen.rule.istio-system: No valid actions found in rule
	* action='kubeattrgenrulerule.rule.istio-system[0]': Instance not found: instance='attributes'
	* action='kubeattrgenrulerule.rule.istio-system[0]': No valid instances found
	* rule=kubeattrgenrulerule.rule.istio-system: No valid actions found in rule
	* rule='promhttp.rule.istio-system'.Match: unknown attribute context.protocol
	* action='promhttp.rule.istio-system[0]': Instance not found: instance='requestcount'
	* action='promhttp.rule.istio-system[0]': Instance not found: instance='requestduration'
	* action='promhttp.rule.istio-system[0]': Instance not found: instance='requestsize'
	* action='promhttp.rule.istio-system[0]': Instance not found: instance='responsesize'
	* action='promhttp.rule.istio-system[0]': No valid instances found
	* rule=promhttp.rule.istio-system: No valid actions found in rule
	* rule='promtcp.rule.istio-system'.Match: unknown attribute context.protocol
	* action='promtcp.rule.istio-system[0]': Instance not found: instance='tcpbytesent'
	* action='promtcp.rule.istio-system[0]': Instance not found: instance='tcpbytereceived'
	* action='promtcp.rule.istio-system[0]': No valid instances found
	* rule=promtcp.rule.istio-system: No valid actions found in rule
	* rule='tcpkubeattrgenrulerule.rule.istio-system'.Match: unknown attribute context.protocol
	* action='tcpkubeattrgenrulerule.rule.istio-system[0]': Instance not found: instance='attributes'
	* action='tcpkubeattrgenrulerule.rule.istio-system[0]': No valid instances found
	* rule=tcpkubeattrgenrulerule.rule.istio-system: No valid actions found in rule
```
I deleted the istio-telemetry pod and waited until another one got recreated. Now, everything works as expected.

**Comment by douglas-reid** [comment]
We cannot put a readiness/liveness probe on mixer for a port exposed by an adapter. There is no requirement that mixer be run with the prometheus adapter, and I don't think we should introduce one now.

I'm not sure what is happening, but as @mandarjog relates, Mixer is already checking for existence of required CRDs from galley. I said that Mixer typically restarts 3 times, because that is typically the amount of cycles of checks it takes until galley is up and running.

It seems like the first telemetry pod is getting incomplete config from galley?  And this results in the rest of mixer not functioning properly?

**Comment by douglas-reid** [comment]
For debugging, we probably need to modify the telemetry deployment to set the logging scope `mcp` to `debug` and look at the logs for collections received, etc. 

We probably also need detailed galley logs when we get in this situation.

I'd like to answer the question of "Why aren't the CRs for the CRDs being synced to Mixer?".

**Comment by kramvan1** [comment]
@douglas-reid   from what I see happening:
when the telemetry logs contain:
```
2019-12-02T21:36:15.910136Z     info    mcp     New MCP sink stream created
2019-12-02T21:36:15.914047Z     error   mcp     Error receiving MCP resource: rpc error: code = Unavailable desc = upstream connect error or disconnect/reset before headers. reset reason: connection failure
2019-12-02T21:36:15.914255Z     error   mcp     Error receiving MCP response: rpc error: code = Unavailable desc = upstream connect error or disconnect/reset before headers. reset reason: connection failure
```
it seems to restart and try again (4 or 5 times in my working cases).
when the logs contains:
```
2019-12-02T19:43:01.576077Z	error	36 errors occurred:
	* instance='requestsize.instance.istio-system': failed to evaluate expression for field 'Value'; unknown attribute request.size
	* instance='tcpbytesent.instance.istio-system': failed to evaluate expression for field 'Value'; unknown attribute connection.sent.bytes
	* instance='tcpbytereceived.instance.istio-system': failed to evaluate expression for field 'Value'; unknown attribute connection.received.bytes
	* instance='attributes.instance.istio-system': error evaluating AttributeBinding expression for attribute key 'source.workload.namespace': unknown attribute source.workload.namespace
...
```
this seams to hang the pod and no restarts.

**Comment by douglas-reid** [comment]
@kramvan1 what do the galley logs look like at the same time? Those logs indicate that Mixer is not receiving the attributes CR from galley.

**Comment by kramvan1** [comment]
@douglas-reid 
[galley.log](https://github.com/istio/istio/files/3913488/galley.log)

**Comment by kramvan1** [comment]
@douglas-reid Some steps to reproduce this issue:

Steps to reproduce:

Fully Manual Install.
1) Clone down 1.4.0 community istio operator
`git clone https://github.com/istio/operator.git`
`cd operator`
`git checkout 1.4.0`
Edit deploy/operator.yaml to have the 1.4.0 image. It should be
`          image: docker.io/istio/operator:1.4.0`
2) Apply the community operator
`kubectl apply -k deploy/`
3) Apply our ICP (see bottom)
4) Wait for Istio to setup completely. (All pods ready N/N)
5) Test Telemetry
`kubectl run -n istio-system -it --rm --restart=Never test --image=tutum/curl -- sh -c 'curl -I http://istio-telemetry:42422/metrics'`
We see a happy 200 return code at this time.
```
HTTP/1.1 200 OK
Content-Type: text/plain; version=0.0.4; charset=utf-8
Date: Tue, 03 Dec 2019 18:50:23 GMT

pod "test" deleted
```
6) Delete our ICP which causes the operator to uninstall istio
`kubectl delete icp -n istio-operator managed-istiocontrolplane`
Wait until all istio pods are removed from the istio-system namespace.
The istio-system namespace will remain along with some uncleaned up secrets, issue https://github.com/istio/istio/issues/18384
7) Apply our ICP again to reinstall Istio
8) Wait for Istio to setup again
9) Test Telemetry again
`kubectl run -n istio-system -it --rm --restart=Never test --image=tutum/curl -- sh -c 'curl -I http://istio-telemetry:42422/metrics'`
We see an unhappy failure this time.
```
curl: (7) Failed to connect to istio-telemetry port 42422: Connection refused
pod "test" deleted
pod istio-system/test terminated (Error)
```

Additional test variations between disable (Step 6) and enable (Step 7)
If the istio-system namespace is deleted, then Telemetry works.
If everything (see below for kubectl get literally all) is removed from the istio-system namespace, then Telemetry fails.
`kubectl api-resources --verbs=list --namespaced -o name | xargs -t -n 1 kubectl get --show-kind --ignore-not-found -n istio-system`
If the istio-system namespace was deleted and then an exact duplicate was applied, then Telemetry fails.



Our ICP (with small tweaks to run in community environment)
```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  annotations:
    armada-service: addon-istio
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"install.istio.io/v1alpha2","kind":"IstioControlPlane","metadata":{"annotations":{"armada-service":"addon-istio","version":"1.4.0_891"},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile"},"name":"managed-istiocontrolplane","namespace":"ibm-operators"},"spec":{"gateways":{"components":{"egressGateway":{"enabled":true,"k8s":{"affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"podAffinityTerm":{"labelSelector":{"matchExpressions":[{"key":"app","operator":"In","values":["istio-egressgateway"]}]},"topologyKey":"kubernetes.io/hostname"},"weight":100}]}},"hpaSpec":{"maxReplicas":5,"minReplicas":2,"scaleTargetRef":{"apiVersion":"apps/v1","kind":"Deployment","name":"istio-egressgateway"}}}},"ingressGateway":{"enabled":true,"k8s":{"affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"podAffinityTerm":{"labelSelector":{"matchExpressions":[{"key":"app","operator":"In","values":["istio-ingressgateway"]}]},"topologyKey":"kubernetes.io/hostname"},"weight":100}]}},"hpaSpec":{"maxReplicas":5,"minReplicas":2,"scaleTargetRef":{"apiVersion":"apps/v1","kind":"Deployment","name":"istio-ingressgateway"}}}}}},"hub":"icr.io/ext/istio","policy":{"components":{"policy":{"enabled":true,"k8s":{"affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"podAffinityTerm":{"labelSelector":{"matchExpressions":[{"key":"app","operator":"In","values":["istio-policy"]}]},"topologyKey":"kubernetes.io/hostname"},"weight":100}]}}}}}},"profile":"default","tag":"1.4.0","telemetry":{"components":{"telemetry":{"enabled":true,"k8s":{"affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"podAffinityTerm":{"labelSelector":{"matchExpressions":[{"key":"app","operator":"In","values":["istio-telemetry"]}]},"topologyKey":"kubernetes.io/hostname"},"weight":100}]}},"overlays":[{"kind":"Deployment","name":"istio-telemetry","patches":[{"path":"spec.template.metadata.annotations","value":{"prometheus.io/port":"42422","prometheus.io/scrape":"true"}}]}]}}}},"trafficManagement":{"components":{"pilot":{"enabled":true,"k8s":{"affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"podAffinityTerm":{"labelSelector":{"matchExpressions":[{"key":"app","operator":"In","values":["pilot"]}]},"topologyKey":"kubernetes.io/hostname"},"weight":100}]}}}}}},"values":{"global":{"proxy":{"accessLogFile":"/dev/stdout"}},"grafana":{"enabled":true,"image":{"repository":"icr.io/ext/istio/grafana/grafana"}},"kiali":{"createDemoSecret":false,"enabled":true,"hub":"icr.io/ext/istio/kiali"},"prometheus":{"enabled":true,"hub":"icr.io/ext/istio/prom"},"tracing":{"enabled":true,"jaeger":{"hub":"icr.io/ext/istio/jaegertracing"}}}}}
    version: 1.4.0_891
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
  name: managed-istiocontrolplane
  namespace: istio-operator
spec:
  gateways:
    components:
      egressGateway:
        enabled: true
        k8s:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - istio-egressgateway
                  topologyKey: kubernetes.io/hostname
                weight: 100
          hpaSpec:
            maxReplicas: 5
            minReplicas: 2
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: istio-egressgateway
      ingressGateway:
        enabled: true
        k8s:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - istio-ingressgateway
                  topologyKey: kubernetes.io/hostname
                weight: 100
          hpaSpec:
            maxReplicas: 5
            minReplicas: 2
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: istio-ingressgateway
  hub: docker.io/istio
  policy:
    components:
      policy:
        enabled: true
        k8s:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - istio-policy
                  topologyKey: kubernetes.io/hostname
                weight: 100
  profile: default
  tag: 1.4.0
  telemetry:
    components:
      telemetry:
        enabled: true
        k8s:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - istio-telemetry
                  topologyKey: kubernetes.io/hostname
                weight: 100
          overlays:
          - kind: Deployment
            name: istio-telemetry
            patches:
            - path: spec.template.metadata.annotations
              value:
                prometheus.io/port: "42422"
                prometheus.io/scrape: "true"
  trafficManagement:
    components:
      pilot:
        enabled: true
        k8s:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - pilot
                  topologyKey: kubernetes.io/hostname
                weight: 100
  values:
    global:
      proxy:
        accessLogFile: /dev/stdout
    grafana:
      enabled: true
    kiali:
      createDemoSecret: false
      enabled: true
    prometheus:
      enabled: true
    tracing:
      enabled: true
```

**Comment by kramvan1** [comment]
Looks like the ICP content is not directly related, can be recreated with just:
```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  name: managed-istiocontrolplane
  namespace: istio-operator
spec:
  profile: default
```

**Comment by linsun** [comment]
@kramvan1 can you confirm that if you *delete* the `istio.default` secret in the istio-system namespace at step 6 then continue to step 7, 8, and 9 would work for you with 200 return code?

If so, I think there may be a compatibility issue between the `istio.default` secret from prior ICP install and the istio CA secret and the few other secrets (citadel-sa-token, galley-sa-token etc) in the new ICP install.

**Comment by linsun** [comment]
So control plane security is enabled by default in 1.4.0 default profile.  The error in istio-telemetry log seemed to indicate istio-telemetry pod can't establish connection with galley.

**Comment by linsun** [comment]
```
2019-12-04T02:29:31.988165Z	error	mcp	Failed to create a new MCP sink stream: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp [::1]:15019: connect: connection refused"
```

Note the erorr is transport connection refused.  so mTLS among mixer-telemetry to MCP failed on port 15019.

**Comment by rvennam** [comment]
@linsun @kramvan1 deleting the istio.default secret between deleting and reapplying the ICP (step 6 and 7) fixes the telemetry issue.

**Comment by linsun** [comment]
tagging security team @incfly @myidpt @yangminzhu could you shed some light on this?  My guess is the  istio.default secret generated from the prior ICP/istio install doesn't work with the new citadel and CA from the new ICP/istio.   Rebooting the telemetry pod will have the secrets refreshed with updated secret/certs issued from the new CA.  (for details, just read few comments from today).

**Comment by kramvan1** [comment]
@linsun  
We were unable to replicate that result. When we delete the istio.default secret between deleting and reapplying the ICP, or even all secrets in the istio-system namespace, we still replicate the telemetry error.

We have even gone to deleting literally every kubernetes resource in the istio-system namespace (Even Events). As long as the namespace itself is not deleted, the telemetry error occurs.

**Comment by crhuber** [comment]
We are also having issues with istio-telemetry pod shows Running, but nothing responds on 42422/metrics. We are using regular helm to install and not using istio operator

**Comment by sdake** [comment]
> ```
> 2019-12-04T02:29:31.988165Z	error	mcp	Failed to create a new MCP sink stream: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp [::1]:15019: connect: connection refused"
> ```
> 
> Note the erorr is transport connection refused. so mTLS among mixer-telemetry to MCP failed on port 15019.

@linsun the error `connection refused` indicates a bind()/listen() has not been executed within the MCP server.

**Comment by incfly** [comment]
yes. connection refused is not indicator of tls handshake failure, which usually ends up with a `upstream connection reset` msg.

**Comment by rvennam** [comment]
I disabled controlPlaneSecurityEnabled and set global log level: "mcp:debug" as requested by @douglas-reid  Please see attached logs for telemetry and galley. 

[galley_debug_.log](https://github.com/istio/istio/files/3925007/galley_debug_.log)
[telemetry_debug.log](https://github.com/istio/istio/files/3925008/telemetry_debug.log)

```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  namespace: istio-operator
  name: example-istiocontrolplane
spec:
  profile: default
  values:
    global:
      controlPlaneSecurityEnabled: false
      logging:
        level: "mcp:debug"
```
