### ISSUE TITLE
ISTIO_MUTUAL to ingress gateway

### ISSUE THREAD

**Issue by malakhrevan** [istio/istio#19180]
**Bug description**
Tried unsuccessfully to apply ISTIO_MUTUAL to ingress gateway. I want to use ISTIO_MUTUAL to ingress-gateway so request from services to gateway will be authenticated.

**Expected behavior**
Successful connection from service to ingress-gateway with ISTIO_MUTUAL

**Steps to reproduce the bug**
Apply following config
```
apiVersion: "authentication.istio.io/v1alpha1"
kind: "MeshPolicy"
metadata:
  name: "default"
spec:
  peers:
  - mtls: {}
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "httpbin-mtls"
  namespace: httpbin
spec:
  host: httpbin.httpbin.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```
Deploy httpbin and sleep from samples
```
kubectl create ns httpbin
kubectl apply -f <(istioctl kube-inject -f samples/httpbin/httpbin.yaml) -n httpbin
kubectl apply -f <(istioctl kube-inject -f samples/sleep/sleep.yaml) -n httpbin
```
Create gateway and endpoints to gateway
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
  namespace: httpbin
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - app.httpbin.com
    - httpbin-gw.httpbin
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-virtual-service
  namespace: httpbin
spec:
  hosts:
  - app.httpbin.com
  - httpbin-gw.httpbin
  gateways:
  - httpbin-gateway
  http:
  - match:
    - uri:
        prefix: /headers
    route:
    - destination:
        port:
          number: 8000
        host: httpbin.httpbin.svc.cluster.local
---
apiVersion: v1
kind: Endpoints
metadata:
  name: httpbin-gw
  namespace: httpbin
subsets:
  - addresses:
    - ip: {{ingress gateway load balancer IP}}
    ports:
    - port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-gw
  namespace: httpbin
spec:
  clusterIP: None
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin-gw
  namespace: httpbin
---
```
At this point, request to `httpbin-gw` will work
```
kubectl exec $(kubectl get pod -l app=sleep -n httpbin -o jsonpath={.items..metadata.name}) -c sleep -n httpbin -- curl http://httpbin-gw.httpbin/headers
```
Add ISTIO_MUTUAL destination rule
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: httpbin-gateway-destination-rule
  namespace: httpbin
spec:
  host: httpbin-gw.httpbin.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```
request to `httpbin-gw` failed with `503 Service Unavailable`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
istioctl version --remote
client version: 1.4.0
control plane version: 1.4.0
data plane version: 1.4.0 (4 proxies)
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-gke.17", GitCommit:"188432a69210ca32cafded81b4dd1c063720cac0", GitTreeState:"clean", BuildDate:"2019-11-13T20:47:11Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**
istioctl manifest apply --set values.global.proxy.logLevel=debug 

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by vadimeisenbergibm** [comment]
You can do it in the following way:

1. Change the port of the gateway. service, endpoints to 443, the protocol and name to TLS/tls.
2. Add the `tls` section:
```
  servers:
  - port:
      number: 443
      name: tls
      protocol: TLS
    hosts:
    - app.httpbin.com
    - httpbin-gw.httpbin
    tls:
      mode: MUTUAL
      serverCertificate: /etc/certs/cert-chain.pem
      privateKey: /etc/certs/key.pem
      caCertificates: /etc/certs/root-cert.pem
```

3. Add a virtual service to direct the traffic from port 80 to port 443. See an example of such virtual service in https://istio.io/docs/tasks/traffic-management/egress/egress-tls-origination/#tls-origination-for-egress-traffic .
