### ISSUE TITLE
Out-of-process adapter is not session based

### ISSUE THREAD

**Issue by NilsRenaud** [istio/istio#19194]
**Bug description**

I've created an out-of-process adapter, it's working well. I want it to be customisable and added a configuration proto and Yml files. Now this static configuration is passed for each request next to the payload.

That's great, but I rather like to have this configuration passed once at the adapter startup instead of for every requests. 

So i tried to switch the "session_based" attribute from "false" to "true" and to implement the InfrastructureBackend proto file in my adapter. 

And here is the bug : I can't see any calls to my new InfrastructureBackend service (validate, createSession, closeSession), but my configuration is not totally ignored since I no longer receive the configuration for every requests.

So, is the session_based adapter not yet implemented ? Is there a bug ? Or, better, what am I doing wrong ? :)

( I tried to get answers on StackOverflow few days ago but I didn't have any luck : https://stackoverflow.com/posts/58875770/edit )

**Expected behavior**

When toggling the session_based attribute of my adapter.config.istio.io/v1alpha2 yml file, My InfrastructureBackend should be called at the adapter startup or at least produce some errors in the mixer log (istio-policy/telemetry).

**Steps to reproduce the bug**

If I understood the concept correctly, I only need to : 

- Create a config.proto with my parameters : 
```
syntax = "proto3";

package config;

import "gogoproto/gogo.proto";

option (gogoproto.goproto_getters_all) = false;
option (gogoproto.equal_all) = false;
option (gogoproto.gostring_all) = false;

message Params {
  string value1 = 1;

  string value2 = 2;
}

```
- compile it with protoc to output a descriptor_set file
- base64 this descriptor set in adapter.yml
```
apiVersion: "config.istio.io/v1alpha2"
kind: adapter
metadata:
  name: exampleadapter
  namespace: istio-system
spec:
  description: "A sample adapter for test purposes"
  session_based: true
  templates:
    - ...
  config: ...config.proto descriptor set base64 encoded ...
```
- implement this gRPC protobuf interface : 
```
syntax = "proto3";

package istio.mixer.adapter.model.v1beta1;

option go_package="istio.io/api/mixer/adapter/model/v1beta1";
option cc_generic_services = true;

import "google/protobuf/any.proto";
import "google/rpc/status.proto";


service InfrastructureBackend {
  
  rpc  Validate(ValidateRequest) returns (ValidateResponse);

  rpc  CreateSession(CreateSessionRequest) returns (CreateSessionResponse);

  rpc  CloseSession(CloseSessionRequest) returns (CloseSessionResponse);
}

message CreateSessionRequest {
  google.protobuf.Any adapter_config = 1;
  map<string, google.protobuf.Any> inferred_types = 2;
}

message CreateSessionResponse {
  string session_id = 1;
  google.rpc.Status status = 2;
}

message ValidateRequest {
  google.protobuf.Any adapter_config = 1;
  map<string, google.protobuf.Any> inferred_types = 2;
}

message ValidateResponse {
  google.rpc.Status status = 1;
}

message CloseSessionRequest {
  string session_id = 1;
}

message CloseSessionResponse {
  google.rpc.Status status = 1;
}

```
- Create a Handler istio config file that set the config values :
```
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: h1
  namespace: istio-system
spec:
  adapter: exampleadapter
  connection:
    address: exampleadapter:9070
  params:
    value1: testVal111
    value2: testVal2222
```

So I've done all this steps, but **my Validate/CreateSession methods are never called**.

I tried to check mixer (istio-policy) logs, even in debug, but I don't have any clues why this config step is totally ignored !

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

I'm still using 1.3.3 because of this issue ( https://github.com/istio/istio/issues/19067 )
```
control plane version: 1.3.3
data plane version: 1.3.3 (3 proxies)
```

**How was Istio installed?**

On Minikube, MacOs with : 

```
for i in ${ISTIO_DIR}/install/kubernetes/helm/istio-init/files/crd*yaml; do kubectl apply -f $i; done
kubectl apply -f ${ISTIO_DIR}/install/kubernetes/istio-demo.yaml
```

**Environment where bug was observed (cloud vendor, OS, etc)**

Minikube, MacOs.
