### ISSUE TITLE
Analysis should consider <namespace>.svc.cluster.local

### ISSUE THREAD

**Issue by esnible** [istio/istio#19195]
If a DestinationRule specifies a host ending in `.svc.cluster.local`, and `--use-kube` is selected, check that the namespace exists.

A user showed me this DestinationRule.  The intention had been to deploy examples in a `prod` namespace, but they had been put into `default`, yet the full-qualified hostname the rule applied to was in the `prod` namespace.

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: frontend
spec:
  host: frontend.prod.svc.cluster.local
  subsets:
...
```

cc @sdake
