### ISSUE TITLE
[Operator]Tracing component doesn't honor 'defaultNodeSelector' in global values

### ISSUE THREAD

**Issue by morvencao** [istio/istio#19216]
**Bug description**

Deploy operator controller, apply the following ICP CR to cluster:
```
# cat deploy/crds/istio_v1alpha2_istiocontrolplane_cr.yaml
---
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  name: example-istiocontrolplane
spec:
  profile: demo
  values:
    global:
      defaultNodeSelector:
        role: worker
...
```

I found that the `tracing` pod is keep pending because `defaultNodeSelector` isn't taking effect on it.
```
root@mcdev1:~/go/src/istio.io/operator# kc -n istio-system get pod
NAME                                      READY   STATUS    RESTARTS   AGE
grafana-575b7f467b-jd79c                  1/1     Running   0          3m36s
istio-citadel-854f5c4bd6-9nnfj            1/1     Running   0          3m37s
istio-egressgateway-68b84fd964-58m5h      1/1     Running   0          3m45s
istio-galley-78c4d6b44b-vk567             1/1     Running   0          3m36s
istio-ingressgateway-76f5d6c4f8-t8xnq     1/1     Running   0          3m40s
istio-pilot-6649df94bc-7s94g              1/1     Running   0          3m36s
istio-policy-8d97889bc-dv785              1/1     Running   0          3m36s
istio-sidecar-injector-5f485677cd-2rhc6   1/1     Running   0          3m36s
istio-telemetry-84cbfb6875-rkv25          1/1     Running   0          3m34s
istio-tracing-78548677bc-m6xct            0/1     Pending   0          3m45s
kiali-b74b9fdc5-x9sps                     1/1     Running   0          3m37s
prometheus-85ddd99fdf-4lphf               1/1     Running   0          3m38s
```

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
