### ISSUE TITLE
Istio 1.4.0 ClusterRole for Pilot is a bit confusing

### ISSUE THREAD

**Issue by Stono** [istio/istio#19226]
**Bug description**
The ClusterRole for pilot is a little confusing, firstly secrets are defined twice:

```
- apiGroups:
  - ''
  resources:
  - endpoints
  - pods
  - services
  - namespaces
  - nodes
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - create
  - get
  - watch
  - list
  - update
  - delete
```

The second block (added in 1.4.0) gives pilot permission to create, update and delete secrets too.  What is that permission used for?

**Expected behavior**
The RBAC config to be concise and an explanation in the upgrade notes as to any privilege changes.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4.0

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
