### ISSUE TITLE
Istioctl unable to set cni properties according to the documentation

### ISSUE THREAD

**Issue by thecodejunkie** [istio/istio#19230]
**Bug description**
I've downloaded Istio 1.4.0 and took the command straight from https://istio.io/docs/setup/additional-setup/cni/#excluding-specific-kubernetes-namespaces but there is a problem with Istio CNI value overrides

**Expected behavior**
That the code exampels execute correctly

**Steps to reproduce the bug**

I've downloaded Istio 1.4.0 and took the command straight from https://istio.io/docs/setup/additional-setup/cni/#excluding-specific-kubernetes-namespaces but there is a problem with Istio CNI value overrides
```
istioctl manifest generate \
    --set cni.enabled=true \
    --set values.cni.logLevel=info \
    --set values.cni.excludeNamespaces={"istio-system,kube-system,foo_ns,bar_ns"}

bad path=value (values.cni.logLevel=info): unknown field "logLevel" in v1alpha1.CNIConfig
```

Same for the **excludeNamespaces** parameter

```
istioctl manifest generate \
    --set cni.enabled=true \
    --set values.cni.excludeNamespaces={"istio-system,kube-system,foo_ns,bar_ns"} 

bad path=value (values.cni.excludeNamespaces={istio-system): json: cannot unmarshal string into Go value of type []json.RawMessage
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4.0

**How was Istio installed?**
`curl -L https://istio.io/downloadIstio | sh -`

**Environment where bug was observed (cloud vendor, OS, etc)**
macOS Catalina

**Comment by richardwxn** [comment]
@thecodejunkie Looks like the doc is not correct, thanks for pointing out, I would update that. There are two issues here, 1. cni.loglevel is not added to our internal values schema, so that's why you got the first bad path error saying unknown field. So you need to add --force flag to bypass. 2. We do not support using set overlay with array values yet, also we encourage to use file based override with complicated case.

So for your case, you can run istioctl manifest generate --force -f cni.yaml, and your cni.yaml can be defined as below:
```yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  cni:
    enabled: true
  values:
    cni:
        logLevel: info
        excludeNamespaces:
         - istio-system
         - kube-system
         - foo
         - bar
```
