### ISSUE TITLE
CNI should set status/annotation field on pod after it has process a pod

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19242]
Right now its pretty hard to tell that CNI actually worked or not. Its easy with the init container, since it will either crash or there are logs from the init container about what happened. 

For CNI this is much more transparent. 

We should consider adding a status field or annotation to the pod after we process it, so we can more clearly tell that a pod has successfully been process by CNI

**Comment by johscheuer** [comment]
This is also something that other CNI implementations like `calico` do:

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: 192.168.46.204/32
```
