### ISSUE TITLE
1.4 behavior change when VirtualSystem port set to `{}`

### ISSUE THREAD

**Issue by esnible** [istio/istio#19271]
A user reports that their VirtualServices contain `port: {}` when they intended to leave port blank.  This is not the issue.

The issue is that in Istio 1.3 `port: {}` seemed to have no effect.  In 1.4 it seems to prevent traffic to the service.  This may be related to auto mTLS.  `istioctl x analyze` correctly reports a problem.   `istioctl x describe` reports `Pod is DISABLE, client protocol unspecified` which is undocumented and ungrammatical.

This issue is to determine if validation webhook should allow `port: {}`.  If so, should it have a regression test case?

```
  apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  metadata:
    name: reviews-experiment
  spec:
    hosts:
    - reviews
    http:
    - route:
      - destination:
          host: reviews
          port: {}
          subset: baseline
        weight: 100
      - destination:
          host: reviews
          port: {}
          subset: candidate
        weight: 0
```

cc @GregHanson

**Comment by GregHanson** [comment]
@esnible need a little more clarification.  Is `port: {}` the same as omitting it, or are users specifically adding the line `port: {}` in their spec?  

Assuming users are specifically trying to set `port: {}`, I don't think we should support it because logically it doesn't make a lot a sense.  Declaring a rule with `port: {}` would be the same as specifying `subset: ""`.  Also from a Go standpoint, `nil` != `{}` so istio validator and XDS code could detect the difference between these field values but I don't know what the distinct behavior for each case should be

Regarding the auto mtls comment: I was specifically testing the bookinfo rules in my auto mtls tests and those rules look like:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: details
spec:
  hosts:
  - details
  http:
  - route:
    - destination:
        host: details
        subset: v1
```
 Also, on another note, I strongly believe having a destination with `weight: 0` is flirting with potentially introducing undefined behavior.  We have some logic in place currently(see [here](https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/route/route.go#L453)) but I don't think we have e2e test for this.
