### ISSUE TITLE
Global Envoy Filter

### ISSUE THREAD

**Issue by Stono** [istio/istio#19285]
**Describe the feature request**
I caveat all the below with "i'm a envoy filter amateur".

I'd like to be able to apply an EnvoyFilter to _all_ workloads in _all_ namespaces, the envoy filter I can currently add to each workload is this one, to add a simple `x-calling-service` header.

Also, I'd like to be able to infer the current workload app in the `request_handle:headers():add("x-calling-service", "some-app")` line, does anyone know how I can do that?

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: add-calling-service
spec:
  workloadSelector:
    labels:
      app: some-app
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_OUTBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.router"
    patch:
      operation: INSERT_BEFORE
      value:
       name: envoy.lua
       config:
         inlineCode: |
           function envoy_on_request(request_handle)
             request_handle:headers():add("x-calling-service", "some-app")
           end
```

**Describe alternatives you've considered**
Creating one of these for every app (300+)

**Additional context**

**Comment by mandarjog** [comment]
I think there is already a feature request to parameterize EnvoyFilter API, we heard about it at kubecon.

Metadata exchange filter does something similar, so wasm sandbox api supports accessing node metadata.
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-envoy-downstream-service-cluster    Perhaps you can do this instead?

**Comment by Stono** [comment]
@mandarjog that sounds like exactly what I need, I don't suppose you have any code examples?

**Comment by lfundaro** [comment]
Hello folks ! 👋 I just ran @Stono `EnvoyFilter` and it works for me, however I cannot get it to work for `OUTBOUND`. I'm using 
```
client version: 1.3.4
control plane version: 1.3.4
```
and here's the filter:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: add-calling-service-inbound
spec:
  workloadSelector:
    labels:
      app: echo-ping
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.router"
    patch:
      operation: INSERT_BEFORE
      value:
       name: envoy.lua
       config:
         inlineCode: |
           function envoy_on_request(request_handle)
             request_handle:headers():add("x-foo", "bar")
           end
```
Note that I'm not specifying `listerner.portNumber` because I want this to be applied to all applications in my cluster. 

could I be missing something here ? 

Thanks !
