### ISSUE TITLE
Clarification needed on how to configure gateway ports with istiocl manifest

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#19295]
**Describe the feature request**

It is not clear how to configure gateway ports with istioctl manifest. The instructions to use helm values do not work.

Context: Istio gateways are part of Istio a-la carte concept and should be customisable. In particular, the user should be able to deploy multiple gateways in different namespaces for different purposed. One of the basic customisation tasks is to customise ports of the gateway - the gateway should accept traffic for different protocols on different ports. For simplicity, let's start with the task of defining a single port for Istio egress gateway, port 7777, TCP protocol.

1.  The helm way works:

```
helm template install/kubernetes/helm/istio/ --name istio-egressgateway --namespace istio-system -x charts/gateways/templates/deployment.yaml -x charts/gateways/templates/service.yaml --set gateways.istio-ingressgateway.enabled=false --set gateways.istio-egressgateway.enabled=true --set gateways.istio-egressgateway.ports[0].port=7777 --set gateways.istio-egressgateway.ports[0].name=tcp
...
kind: Service
metadata:
  name: istio-egressgateway
  namespace: istio-system
  annotations:
  labels:
    chart: gateways
    heritage: Tiller
    release: istio-egressgateway
    app: istio-egressgateway
    istio: egressgateway
spec:
  type: ClusterIP
  selector:
    release: istio-egressgateway
    app: istio-egressgateway
    istio: egressgateway
  ports:
    -
      name: tcp
      port: 7777
...
Deployment
...
         ports:
            - containerPort: 7777
...
```

2. Using the same values with the prefix "values.*" does not work. From the documentation:
> For backwards compatibility, the previous Helm installation options are also fully supported. To set them on the command line, prepend the option name with “values.”.

```
istioctl manifest apply --set values.gateways.istio-egressgateway.ports[0].port=7777 --set values.gateways.istio-egressgateway.ports[0].name=tcp
```

3. Using `IstioControlPlane` does not work either:

Attached 

**Additional context**

**Comment by irisdingbj** [comment]
```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  namespace: istio-operator
  name: example-istiocontrolplane
spec:
  profile: demo
  gateways:
    enabled: true
  values:
    gateways:
      istio-egressgateway:
        ports:
          - port: 7777
            name: tc
```

**Comment by irisdingbj** [comment]
@vadimeisenbergibm try to put the ports into values part like above. I have got below 

```
apiVersion: v1
kind: Service
metadata:
  name: istio-egressgateway
  namespace: istio-system
  annotations:
  labels:
    app: istio-egressgateway
    release: istio
    istio: egressgateway
spec:
  type: ClusterIP
  selector:
    app: istio-egressgateway
  ports:
    -
      name: tcp
      port: 7777
```
