### ISSUE TITLE
After the Pod is injected into the sidecar of istio, the websocket connection will be interrupted abnormally

### ISSUE THREAD

**Issue by lys0224** [istio/istio#19298]
The backend uses Springboot to provide a websocket connection and sets the maximum idle time to 3 minutes. The program runs well in local . After 3 minutes of idle, the connection will be disconnected as scheduled. It can also be accessed normally by nodeport service when deployed in kubernetes.

But when I inject sidecar into this backend pod, there is a problem . The connection doesn't work properly, often breaks, and is completely irregular.Sometimes when the frontend and backend are sending messages, it is interrupted suddenly.Sometimes it is interrupted after about 2 minutes idle.And sometimes the connection can only last for tens of seconds.

When the connection is interrupted, the backend will throw java.io.EOFException, and the frontend will receive the onclose event.

This phenomenon will occur as long as sidecar is injected into pod(Even if I use nodeport service to access the pod).Also I did a test , I used nginx to transfer the request to port 31380 of istio-ingressgateway, and configured the gateway  vs and dr as follows.But the result is the same.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: msapi
    version: product
  name: msapi
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      run: msapi
  template:
    metadata:
      labels:
        run: msapi
    spec:            
      containers:
      - env:
        - name: JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              key: jvm.options
              name: test-config
        image: test/msapi:1.0.0
        imagePullPolicy: Always
        name: msapi
        ports:
        - containerPort: 9000
          protocol: TCP   
---
apiVersion: v1
kind: Service
metadata:
  name: msapi
  namespace: test
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9000
  selector:
    run: msapi
  type: ClusterIP
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingress-test
  namespace: test
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*.ingress.xxx.com'
    port:
      name: http
      number: 80
      protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: msapi
  namespace: test
spec:
  gateways:
  - ingress-test
  hosts:
  - msapi.ingress.xxx.com
  http:
  - match:
    - headers:
        cookie:
          regex: ^(.*?; ?)?(version=pre)(;.*)?$
    route:
    - destination:
        host: msapi
        subset: pre
  - route:
    - destination:
        host: msapi
        subset: product
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: msapi
  namespace: test
spec:
  host: msapi
  subsets:
  - labels:
      version: product
    name: product
  - labels:
      version: pre
    name: pre
```
the version of istio is 1.2.4
