### ISSUE TITLE
Istio 1.4 with cert-manager 0.11.0 and SDS enabled get 404 with http01 solver

### ISSUE THREAD

**Issue by ichasco** [istio/istio#19296]
**Bug description**

I am having problems deploying istio 1.4 with sds and cert-manger 0.11

**Expected behavior**

Get Let's encrypt certificates with http01 solver

**Steps to reproduce the bug**

## Deploy Istio 1.4

```
istioctl manifest apply \
  --set values.gateways.istio-ingressgateway.sds.enabled=true \
  --set values.global.k8sIngress.enabled=true \
  --set values.global.k8sIngress.enableHttps=true \
  --set values.global.k8sIngress.gatewayName=ingressgateway
```

## Deploy cert-manager 0.11.0

`kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v0.11.0/cert-manager.yaml`

```
NAME                                       READY   STATUS    RESTARTS   AGE
cert-manager-cainjector-74bb68d67c-s8nmq   1/1     Running   0          111s
cert-manager-f7f8bf74d-789qg               1/1     Running   0          111s
cert-manager-webhook-645b8bdb7-7ck68       1/1     Running   0          74s
```

## Create Issuer

```
cat <<EOF | kubectl apply -f -
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: istio-system
spec:
  acme:
    email: test@asdad.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: lets-encrypt-app-cert
    solvers:
    - selector: {}
      http01:
        ingress: {}
---
EOF
```
 Result:
```
NAME                  AGE
letsencrypt-staging   40s
```
```
Status:
  Acme:
    Last Registered Email:  test@asdad.com
    Uri:                    https://acme-staging-v02.api.letsencrypt.org/acme/acct/11672446
  Conditions:
    Last Transition Time:  2019-11-28T17:36:57Z
    Message:               The ACME account was registered with the ACME server
    Reason:                ACMEAccountRegistered
    Status:                True
    Type:                  Ready
Events:                    <none>
```

## Create certificate

```
cat <<EOF | kubectl apply -f -
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: lets-encrypt-app-cert
  namespace: istio-system
spec:
  secretName: lets-encrypt-app-cert
  commonName: lets-encrypt-app.34.77.30.109.nip.io
  dnsNames:
  - lets-encrypt-app.34.77.30.109.nip.io
  issuerRef:
    name: letsencrypt-staging
    kind: Issuer
  acme:
    config:
    - http01:
        ingressClass: istio
      domains:
      - lets-encrypt-app.34.77.30.109.nip.io
---
EOF
```

Result:
Cert:
```
Status:
  Conditions:
    Last Transition Time:  2019-11-28T17:39:18Z
    Message:               Waiting for CertificateRequest "lets-encrypt-app-cert-276943243" to complete
    Reason:                InProgress
    Status:                False
    Type:                  Ready
Events:
  Type    Reason     Age   From          Message
  ----    ------     ----  ----          -------
  Normal  Requested  27s   cert-manager  Created new CertificateRequest resource "lets-encrypt-app-cert-276943243"
```
Order:
```
Events:
  Type    Reason   Age   From          Message
  ----    ------   ----  ----          -------
  Normal  Created  42s   cert-manager  Created Challenge resource "lets-encrypt-app-cert-276943243-2104889026-4276716748" for domain "lets-encrypt-app.34.77.30.109.nip.io"
```
Pods:
```
istio-system   cm-acme-http-solver-zlh8t   NodePort       10.19.251.58    <none>         8089:32231/TCP                                                                                                               4m13s
```
Ingress:
```
Events:
  Type    Reason  Age    From                     Message
  ----    ------  ----   ----                     -------
  Normal  ADD     6m19s  loadbalancer-controller  istio-system/cm-acme-http-solver-lz544
  Normal  CREATE  5m4s   loadbalancer-controller  ip: 35.244.238.184
```

cert-manager logs:

```
I1128 17:45:10.698282       1 pod.go:58] cert-manager/controller/challenges/http01/selfCheck/http01/ensurePod "level"=0 "msg"="found one existing HTTP01 solver pod" "dnsName"="lets-encrypt-app.34.77.30.109.nip.io" "related_resource_kind"="Pod" "related_resource_name"="cm-acme-http-solver-8xqd7" "related_resource_namespace"="istio-system" "resource_kind"="Challenge" "resource_name"="lets-encrypt-app-cert-276943243-2104889026-4276716748" "resource_namespace"="istio-system" "type"="http-01" 
I1128 17:45:10.698389       1 service.go:43] cert-manager/controller/challenges/http01/selfCheck/http01/ensureService "level"=0 "msg"="found one existing HTTP01 solver Service for challenge resource" "dnsName"="lets-encrypt-app.34.77.30.109.nip.io" "related_resource_kind"="Service" "related_resource_name"="cm-acme-http-solver-zlh8t" "related_resource_namespace"="istio-system" "resource_kind"="Challenge" "resource_name"="lets-encrypt-app-cert-276943243-2104889026-4276716748" "resource_namespace"="istio-system" "type"="http-01" 
I1128 17:45:10.698466       1 ingress.go:91] cert-manager/controller/challenges/http01/selfCheck/http01/ensureIngress "level"=0 "msg"="found one existing HTTP01 solver ingress" "dnsName"="lets-encrypt-app.34.77.30.109.nip.io" "related_resource_kind"="Ingress" "related_resource_name"="cm-acme-http-solver-lz544" "related_resource_namespace"="istio-system" "resource_kind"="Challenge" "resource_name"="lets-encrypt-app-cert-276943243-2104889026-4276716748" "resource_namespace"="istio-system" "type"="http-01" 
E1128 17:45:10.704109       1 sync.go:184] cert-manager/controller/challenges "msg"="propagation check failed" "error"="wrong status code '404', expected '200'" "dnsName"="lets-encrypt-app.34.77.30.109.nip.io" "resource_kind"="Challenge" "resource_name"="lets-encrypt-app-cert-276943243-2104889026-4276716748" "resource_namespace"="istio-system" "type"="http-01" 
´´´

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

client version: 1.4.0
control plane version: 1.4.0
data plane version: 1.4.0 (1 proxies)

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-gke.17", GitCommit:"188432a69210ca32cafded81b4dd1c063720cac0", GitTreeState:"clean", BuildDate:"2019-11-13T20:47:11Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
istioctl

**Comment by mauricioadlima** [comment]
I have the same issue. @ichasco did you create some workaround to certificate your cluster?

**Comment by ichasco** [comment]
No, I am still looking for a workaround.

**Comment by mauricioadlima** [comment]
On yesterday I created a workaround and it worked. Basically I created a service to the pod which is used for cert-manager to generated the certificate and mapped that service on my gateway.

`apiVersion: v1
kind: Service
metadata:
  name: cert-manager-solver
  labels:
    app: cert-manager-solver
spec:
  ports:
    - port: 8089
      protocol: TCP
      targetPort: http
  selector:
    acme.cert-manager.io/http01-solver: "true"
  # The trick is here, the cert-manager create a pod with this label and use this pod to generate the certificate.
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtual-service-cert-manager-solver
spec:
  hosts:
    - my-url-here
  gateways:
    - istio-gateway # the name of my gateway (I use custom gateway)    
  http:
    - match:
      - uri:
          prefix: /.well-known/acme-challenge/
      route:
      - destination:
          host: cert-manager-solver
`

**Comment by ichasco** [comment]
Thanks @mauricioadlima with your workaround I could get the certificate. 
I've upgrade istio to 1.4.1 and cert-manager to 0.12.0

I have configured the gateway to get the certificate from SDS but it doesn't work:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: letsencrypt-poc
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - "*"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      credentialName: lets-encrypt-app-cert
      mode: SIMPLE
      privateKey: sds
      serverCertificate: sds
    hosts:
      - "*"
```

The cert is created:

```
NAME                    READY   SECRET                  AGE
lets-encrypt-app-cert   True    lets-encrypt-app-cert   92m
```
And the secret exists:
```
lets-encrypt-app-cert                                Opaque                                3      92m
```

But If I do a curl to https port it fails
```
curl: (60) SSL certificate problem: unable to get local issuer certificate
```

I don't know what can be happening, I will continue investigating.

Thanks for the help

**Comment by mauricioadlima** [comment]
Did you activate the SDS?  Verify if your ingress gateway has a sidecar with name ingress-sds.

**Comment by ichasco** [comment]
Yes, the SDS is enabled. Did you enabled mTLS?

**Comment by mauricioadlima** [comment]
No, I didn't. I'll not use the mTLS at this moment. What the SDS sidecar is reporting in the log?

**Comment by ichasco** [comment]
The ingress log reports:

```
2019-12-07T11:18:27.137989Z     warn    secretFetcherLog        failed load server cert/key pair from secret lets-encrypt-app-cert: server cert or private key is empty
2019-12-07T11:18:54.797525Z     info    secretFetcherLog        scrtUpdated is called on kubernetes secret lets-encrypt-app-cert
2019-12-07T11:18:54.797876Z     warn    secretFetcherLog        failed load server cert/key pair from secret lets-encrypt-app-cert: server cert or private key is empty
2019-12-07T11:18:54.800273Z     info    sdsServiceLog   CONNECTION ID: router~10.16.1.3~istio-ingressgateway-d56559c95-2ddc9.istio-system~istio-system.svc.cluster.local-1, RESOUR
CE NAME: lets-encrypt-app-cert, EVENT: pushed key/cert pair to proxy
```

Maybe is because the ca is empty?
```
Data
====
ca.crt:   0 bytes
tls.crt:  3610 bytes
tls.key:  1675 bytes
```

I have update secret with dummy base64 text 
```
Data
====
ca.crt:   3 bytes
tls.crt:  3610 bytes
tls.key:  1675 bytes
```
and the ingress reports:
```
2019-12-07T11:25:17.050040Z     info    secretFetcherLog        scrtUpdated is called on kubernetes secret lets-encrypt-app-cert
2019-12-07T11:25:17.050711Z     info    secretFetcherLog        secret lets-encrypt-app-cert does not change, skip update
```

And it continuous not working :(


My pods:

```
NAME                                      READY   STATUS    RESTARTS   AGE
istio-citadel-75c8bb7cf6-xbk96            1/1     Running   0          19m
istio-galley-6c968f76b8-dmcbj             2/2     Running   0          19m
istio-ingressgateway-d56559c95-2ddc9      2/2     Running   0          19m
istio-pilot-5f767854f6-9kf2k              2/2     Running   0          19m
istio-policy-5fcf58866d-gjgxf             2/2     Running   1          19m
istio-sidecar-injector-587c7fb978-9dxtc   1/1     Running   0          19m
istio-telemetry-5576c4f7df-lfpqx          2/2     Running   2          19m
kiali-7964898d8c-gg5dw                    1/1     Running   0          19m
lets-encrypt-app-6b48bd6cdc-sb2p2         1/1     Running   0          8m7s
prometheus-586d4445c7-zzbsp               1/1     Running   0          19m
```

My svc:
```
cert-manager-solver      ClusterIP      10.19.240.240   <none>           80/TCP                                                                                                   
                    11m
istio-citadel            ClusterIP      10.19.245.230   <none>           8060/TCP,15014/TCP                                                                                       
                    20m
istio-galley             ClusterIP      10.19.254.72    <none>           443/TCP,15014/TCP,9901/TCP,15019/TCP                                                                     
                    20m
istio-ingressgateway     LoadBalancer   10.19.243.178   X.X.X.X   15020:32389/TCP,80:32416/TCP,443:31418/TCP,15029:32279/TCP,15030:31949/TCP,15031:31465/TCP,15032:31313/TC
P,15443:30422/TCP   20m
istio-pilot              ClusterIP      10.19.253.64    <none>           15010/TCP,15011/TCP,8080/TCP,15014/TCP                                                                   
                    20m
istio-policy             ClusterIP      10.19.255.251   <none>           9091/TCP,15004/TCP,15014/TCP                                                                                                 20m
istio-sidecar-injector   ClusterIP      10.19.250.233   <none>           443/TCP                                                                                                                      20m
istio-telemetry          ClusterIP      10.19.240.133   <none>           9091/TCP,15004/TCP,15014/TCP,42422/TCP                                                                                       19m
kiali                    ClusterIP      10.19.241.181   <none>           20001/TCP                                                                                                                    20m
lets-encrypt-app         ClusterIP      10.19.248.28    <none>           80/TCP                                                                                                                       8m46s
prometheus               ClusterIP      10.19.246.84    <none>           9090/TCP 
```

Gateways:

```
NAME              AGE
ingressgateway    20m
letsencrypt-poc   6m31s
```

VirtualServies:

```
lets-encrypt-app                      [letsencrypt-poc]   [lets-encrypt-app.X.X.X.X.nip.io]   9m59s
virtual-service-cert-manager-solver   [letsencrypt-poc]   [lets-encrypt-app.X.X.X.X.nip.io]   12m
```

**Comment by a7i** [comment]
Were you able to resolve this?

**Comment by kaotika** [comment]
I ran into another bug that might be related to this: https://github.com/istio/istio/issues/19371

**Comment by dmaxim** [comment]
When I attempted the work around the certificate was not generated.  The cert-manager logs showed a 503 response.  I added a Destination rule to disable mutual tls for the cert manager service which allowed the certificate request to complete.

````
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: cert-manager-destination-rule
spec:
  host: cert-manager-solver
  trafficPolicy:
    tls:
      mode: DISABLE
````

**Comment by balamuru** [comment]
What I'm seeing is similar to https://istio.io/docs/ops/common-problems/network-issues/#404-errors-occur-when-multiple-gateways-configured-with-same-tls-certificate **but shouldn't happen since I use different certificates for each gateway**

**Comment by howardjohn** [comment]
I am able to get this working With 1.6:

```
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: istio-system
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ...
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - selector: {}
      http01:
        ingress:
          class: istio
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls
  namespace: istio-system
spec:
  secretName: tls-cert
  issuerRef:
    name: letsencrypt-staging
  commonName: 130.211.223.148.xip.io
  dnsNames:
  - 130.211.223.148.xip.io
  - 130.211.223.148.nip.io
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tls
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: tls-cert
    hosts:
    - 130.211.223.148.xip.io
    - 130.211.223.148.nip.io
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tls
spec:
  hosts:
  - "*"
  gateways:
  - tls
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: httpbin
        port:
          number: 80

```

I think the problem is all of the configs above have the solver ingress missing the `class`. So the Ingress created won't have the `istio` class and by default the Istio ingress will ignore these.
