### ISSUE TITLE
can't disable install component by  IstioControlPlane file

### ISSUE THREAD

**Issue by wu0407** [istio/istio#19294]
**Bug description**
If use IstioControlPlane file to disable prometheus  install use  istioctl  dose not take effect.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
prometheus not installed
**Steps to reproduce the bug**
1. manifest.yaml
```
values:
........
  prometheus:
    contextPath: /prometheus
    enabled: false
```

2. istioctl manifest apply -f manifest.yaml
3. get pod
```
kubectl get pod -n istio-system                         
NAME                                      READY   STATUS    RESTARTS   AGE
istio-citadel-56465d79b9-zpgsn            1/1     Running   0          2m21s
istio-galley-6b9495645d-mhnfd             2/2     Running   0          2m21s
istio-ingressgateway-5df799fdbd-l6pqj     1/1     Running   0          2m22s
istio-pilot-c9bdc55bd-vkn2f               2/2     Running   0          2m21s
istio-policy-74cf89cb66-k6d8z             2/2     Running   1          2m21s
istio-sidecar-injector-759bf6b4bc-vkbt7   1/1     Running   0          2m21s
istio-telemetry-77b6dfb4ff-pzmt7          2/2     Running   1          2m21s
prometheus-586d4445c7-qjm2r               1/1     Running   0          2m21s
```
it also repetition in minimal profile
```
istioctl profile dump minimal >minimal.yaml
```
header append kind and apiVersion
```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
```
apply config
```
istioctl manifest apply  -f minimal.yaml 
```
get pod 
```
kubectl get pod -n istio-system 
NAME                                      READY   STATUS    RESTARTS   AGE
istio-citadel-56465d79b9-4nh88            1/1     Running   0          25s
istio-galley-6b9495645d-lsfqt             2/2     Running   0          25s
istio-ingressgateway-5df799fdbd-wxqsb     0/1     Running   0          26s
istio-pilot-c9bdc55bd-22j5d               1/2     Running   0          25s
istio-policy-74cf89cb66-xrr25             2/2     Running   1          25s
istio-sidecar-injector-759bf6b4bc-lxfh4   1/1     Running   0          25s
istio-telemetry-77b6dfb4ff-h749s          2/2     Running   0          25s
prometheus-586d4445c7-82chp               0/1     Running   0          25s
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
k8s 1.14
istioctl 1.4.0

**How was Istio installed?**
istioctl 
**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by wu0407** [comment]
it is my misstake, not add spec in the file.
```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane

autoInjection:
  components:
    injector:
      enabled: true
      k8s:
        replicaCount: 1
        strategy:
          rollingUpdate:
            maxSurge: 100%
            maxUnavailable: 25%
  enabled: false
```
