### ISSUE TITLE
readinessProbe for istio-telemetry always fails when MCP is enabled

### ISSUE THREAD

**Issue by nak3** [istio/istio#19290]
**Bug description**

- When readinessProbe is configured for istio-telemetry on MCP enabled cluster, probe always fails.
- This is because MCP does not support probe so [ReadinessProbe for ConfigStore](https://github.com/istio/istio/blob/0a5be9d306e88a5d243dfea0b4400a7460a24bc6/mixer/pkg/server/server.go#L260) is not updating probe file.

**Expected behavior**

- ReadinessProbe works fine when MCP is used.

**Steps to reproduce the bug**

#### 2. Configure readinessProbe

```
kubectl edit deployments -n istio-system  istio-telemetry
```

Configure as below:

```
      containers:
      - args:
        ... snip ...
        - --readinessProbePath=/tmp/healthready
        - --readinessProbeInterval=1s

... snip ...

        readinessProbe:
          exec:
            command:
            - /usr/local/bin/mixs
            - probe
            - --probe-path=/tmp/healthready
            - --interval=10s
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
````

### 3. (Result) Readiness probe fails due to `/tmp/healthready` is not found

```
istio-telemetry-7f5f8b9cc8-pcqbq          1/2     Running     0          50s
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.0-alpha.0.1451+896c901684e774", GitCommit:"896c901684e774169dbd477aecd880df1be6bdd0", GitTreeState:"clean", BuildDate:"2019-06-25T04:30:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

$ istioctl version --remote
client version: f26becf4462c4cc6dd66d93b6ff1f4b498cb113a
cluster-local-gateway version:
cluster-local-gateway version:
citadel version: 1.4.0
galley version: 1.4.0
ingressgateway version: 1.4.0
ingressgateway version: 1.4.0
pilot version: 1.4.0
pilot version: 1.4.0
policy version: 1.4.0
sidecar-injector version: 1.4.0
telemetry version: 1.4.0
data plane version: 1.4.0 (6 proxies)
```

**How was Istio installed?**

- Here is the template: https://gist.github.com/nak3/9bb252eefc96aa44bde3ff313f31f49f

**Environment where bug was observed (cloud vendor, OS, etc)**

- k8s on AWS (But I believe it does not matter.)
