### ISSUE TITLE
Can't enable istio-sidecar-injectior on minimal profile

### ISSUE THREAD

**Issue by vvbogdanov87** [istio/istio#19302]
I try to install istio
```bash
istioctl manifest apply -f staging.yaml
```
staging.yaml
```yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  autoInjection:
    enabled: true
  cni:
    enabled: false
  configManagement:
    enabled: false
  gateways:
    enabled: false
  policy:
    enabled: false
  security:
    enabled: false
  telemetry:
    enabled: false
  trafficManagement:
    enabled: true
  values:
    global:
      useMCP: false
      controlPlaneSecurityEnabled: false
      proxy:
        autoInject: disabled
      mtls:
        auto: false
    pilot:
      sidecar: false
      useMCP: false
    prometheus:
      enabled: false
```
My goal is to have minimal istio installation with auto-injection enabled and configured to inject proxy only to annotated containers. But injector pod can't be started because of missing secret
```bash
kubectl describe pod istio-sidecar-injector-759bf6b4bc-9p5r8 -n istio-system
...
Volumes:
...
  certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio.istio-sidecar-injector-service-account
    Optional:    false
...
MountVolume.SetUp failed for volume "certs" : secret "istio.istio-sidecar-injector-service-account" not found
```
```bash
kubectl get secrets -n istio-system
NAME                                                 TYPE                                  DATA   AGE
default-token-jcdtg                                  kubernetes.io/service-account-token   3      105m
istio-pilot-service-account-token-l8496              kubernetes.io/service-account-token   3      104m
istio-reader-service-account-token-j49bz             kubernetes.io/service-account-token   3      105m
istio-sidecar-injector-service-account-token-5s487   kubernetes.io/service-account-token   3      104m
```
If I install the default profile and later apply my profile, the injector starts successfully. Looks like the secret is created by another component. 

[x] Configuration Infrastructure
[x] Installation

**Version**
```
istioctl version
client version: 1.4.0
control plane version: 1.4.0
data plane version: 1.4.0 (1 proxies)
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**
Kops on AWS
