### ISSUE TITLE
Missing instructions on how to deploy a new gateway with istioctl manifest

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#19323]
**Describe the feature request**

Gateways should easily deployed. Having multiple gateways is a design feature of Istio. Customers want to use different gateways (per namespace, per different LoadBalancer, etc.)

**Describe alternatives you've considered**

**Additional context**

**Comment by vadimeisenbergibm** [comment]
Thanks to @irisdingbj, the instructions to deploy an egress gateway **in a separate namespace** are as follows:
To reproduce:

1.  Create a namespace for the new gateway:
`kubectl create namespace mynamespace`

2. Use attached 
[egress-gateway-icp.txt](https://github.com/istio/istio/files/3916261/egress-gateway-icp.txt)

istioctl manifest apply -f egress-gateway-icp.txt --set values.global.istioNamespace=istio-system

3. 
```
kubectl get pods -n mynamespace
NAME                                READY   STATUS    RESTARTS   AGE
istio-egressgateway-9694557-spq62   1/1     Running   0          9m8s
```

The limitations:
1.   Only one ingress/egress gateway per namespace can be created.

2.   Currently, due to https://github.com/istio/istio/issues/19348, prometheus is configured as well.

**Comment by erezzarum** [comment]
@vadimeisenbergibm You could also disabe prometheus using the "values" field.
```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  trafficManagement:
    enabled: false
  policy:
    enabled: false
  telemetry:
    enabled: false
  security:
    enabled: false
  configManagement:
    enabled: false
  autoInjection:
    enabled: false
  gateways:
    components:
       ingressGateway:
         enabled: true
         namespace: istio-ingressgateway-test
       egressGateway:
         enabled: false
  values:
    prometheus:
      enabled: false
```
The only thing it will create along the ingress gateway in this case (you could switch to egress or use both) it's the CRDs (you can't disable their creation) and other cluster resources (which you can also disable using the "values.clusterResources" flag)
