### ISSUE TITLE
The listcheck of rule  not effect with external serviceentry

### ISSUE THREAD

**Issue by wu0407** [istio/istio#19325]
**Bug description**
I want  to set whitelist to access external service, it use listcheck handler, but it like not work serviceentry.  it work with k8s sevice.
https://discuss.istio.io/t/how-to-restricted-access-external-service-on-special-app/4583

**Expected behavior**
it limit  access for serviceentry host

**Steps to reproduce the bug**
istioctl manifest generate -f config.yaml | grep disablePolicyChecks:
 disablePolicyChecks: false

create ServiceEntry and virtualservice
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: example
spec:
  hosts:
  - example.com
  addresses:
  - 192.168.0.13
  ports:
  - number: 8888
    name: tcp-8888
    protocol: TCP
  - number: 443
    name: tcp-443
    protocol: TCP
  location: MESH_EXTERNAL
  exportTo:
    - .

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: example
spec:
  hosts: 
  - example.com
  addresses:
   - 192.168.0.13
  http:
   - match:
     - port: 8888
     route:
       - destination:
           host: example.com
```
policy
```
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: whitelist
spec:
  compiledAdapter: listchecker
  params:
    overrides:
      - app1
    blacklist: false

---
apiVersion: config.istio.io/v1alpha2
kind: instance
metadata:
  name: appname
spec:
  compiledTemplate: listentry
  params:
    value: source.labels["app"]

---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: checkapp
spec:
  match: destination.service.host == "example.com"
  actions:
  - handler: whitelist
    instances: [ appname ]
```
```
curl 192.168.0.13:8888 -sv
* Rebuilt URL to: 192.168.0.13:8888/
*   Trying 192.168.0.13...
* TCP_NODELAY set
* Connected to 192.168.0.13 (192.168.0.13) port 8888 (#0)
> GET / HTTP/1.1
> Host: 192.168.0.13:8888
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< server: envoy
< date: Mon, 02 Dec 2019 14:39:04 GMT
< content-type: application/octet-stream
< content-length: 6
< x-envoy-upstream-service-time: 0
< 
10888
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
root@test-k8s-master:~# istioctl version --remote
client version: 1.4.0
control plane version: 1.4.0
data plane version: 1.4.0 (3 proxies)
root@test-k8s-master:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.4", GitCommit:"a87e9a978f65a8303aa9467537aa59c18122cbf9", GitTreeState:"clean", BuildDate:"2019-07-08T08:43:10Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.4", GitCommit:"a87e9a978f65a8303aa9467537aa59c18122cbf9", GitTreeState:"clean", BuildDate:"2019-07-08T08:43:10Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
istioctl manifest apply --set profile=demo --set values.pilot.policy.enabled=true
**Environment where bug was observed (cloud vendor, OS, etc)**
