### ISSUE TITLE
Kubectl diff not working as expected with Istio

### ISSUE THREAD

**Issue by pawelprazak** [istio/istio#19349]
When using `kubectl diff`:
```
kubectl diff -R -f /REDACTED/istio-system
```

I get a difference that should not be there (as it is not a difference actually), a false positive:
```
diff -u -N /tmp/LIVE-835569441/admissionregistration.k8s.io.v1beta1.MutatingWebhookConfiguration..istio-sidecar-injector /tmp/MERGED-071657484/admissionregistration.k8s.io.v1beta1.MutatingWebhookConfiguration..istio-sidecar-injector
--- /tmp/LIVE-835569441/admissionregistration.k8s.io.v1beta1.MutatingWebhookConfiguration..istio-sidecar-injector       2019-12-03 15:40:48.684300441 +0100
+++ /tmp/MERGED-071657484/admissionregistration.k8s.io.v1beta1.MutatingWebhookConfiguration..istio-sidecar-injector     2019-12-03 15:40:48.728300888 +0100
@@ -5,7 +5,7 @@
     kubectl.kubernetes.io/last-applied-configuration: REDACTED
   creationTimestamp: "2019-08-13T07:53:42Z"
-  generation: 30
+  generation: 31
   labels:
     app: sidecarInjectorWebhook
     release: istio
@@ -17,7 +17,6 @@
 - admissionReviewVersions:
   - v1beta1
   clientConfig:
-    caBundle: REDACTED
     service:
       name: istio-sidecar-injector
       namespace: istio-system
```

The manifest:
```
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: istio-sidecar-injector
  labels:
    app: sidecarInjectorWebhook
    release: istio
webhooks:
  - name: sidecar-injector.istio.io
    clientConfig:
      service:
        name: istio-sidecar-injector
        namespace: istio-system
        path: "/inject"
      caBundle: ""
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        istio-injection: enabled
```

**Expected behavior**
No difference.

**Steps to reproduce the bug**
(above)
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
Client Version: v1.14.8
Server Version: v1.14.8-eks-b8860f
```

**How was Istio installed?**
`kubectl` (from Helm template output)

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS
