### ISSUE TITLE
panic in istio-init

### ISSUE THREAD

**Issue by rshriram** [istio/istio#19380]
```
circleci@default-f18c7071-2f52-4a76-881b-d3468b0cb644:~/tetrate$ kubectl logs httpbin-7d9d5b55b9-5rdlq -n httpbin-middle -c istio-init
Environment:
------------
ENVOY_PORT=
INBOUND_CAPTURE_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_MARK=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=

Variables:
----------
PROXY_PORT=15001
PROXY_INBOUND_CAPTURE_PORT=15006
PROXY_UID=1337
INBOUND_INTERCEPTION_MODE=REDIRECT
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=*
INBOUND_PORTS_EXCLUDE=15020
OUTBOUND_IP_RANGES_INCLUDE=*
OUTBOUND_IP_RANGES_EXCLUDE=
OUTBOUND_PORTS_EXCLUDE=
KUBEVIRT_INTERFACES=
ENABLE_INBOUND_IPV6=

iptables-restore --noflush /tmp/iptables-rules-1575471817338096531.txt362075769
iptables-restore: line 2 failed
iptables-save 
# Generated by iptables-save v1.6.1 on Wed Dec  4 15:03:37 2019
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:ISTIO_INBOUND - [0:0]
:ISTIO_IN_REDIRECT - [0:0]
:ISTIO_OUTPUT - [0:0]
:ISTIO_REDIRECT - [0:0]
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp -m tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A ISTIO_OUTPUT -s 127.0.0.6/32 -o lo -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
COMMIT
# Completed on Wed Dec  4 15:03:37 2019
ip6tables-save 
panic: exit status 1

goroutine 1 [running]:
istio.io/istio/tools/istio-iptables/pkg/dependencies.(*RealDependencies).RunOrFail(0xd68820, 0x964bef, 0x10, 0xc00000cc80, 0x2, 0x2)
	istio.io/istio@v0.0.0/tools/istio-iptables/pkg/dependencies/implementation.go:70 +0x96
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeIptablesRestoreCommand(0xc0000edd30, 0x7effa01f7001, 0x0, 0x0)
	istio.io/istio@v0.0.0/tools/istio-iptables/pkg/cmd/run.go:484 +0x3aa
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeCommands(0xc0000edd30)
	istio.io/istio@v0.0.0/tools/istio-iptables/pkg/cmd/run.go:491 +0x42
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).run(0xc0000edd30)
	istio.io/istio@v0.0.0/tools/istio-iptables/pkg/cmd/run.go:440 +0x1ace
istio.io/istio/tools/istio-iptables/pkg/cmd.glob..func1(0xd43600, 0xc0000ae900, 0x0, 0x10)
	istio.io/istio@v0.0.0/tools/istio-iptables/pkg/cmd/root.go:36 +0xbf
github.com/spf13/cobra.(*Command).execute(0xd43600, 0xc00001e130, 0x10, 0x11, 0xd43600, 0xc00001e130)
	github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xd43600, 0x40574f, 0xc00006a058, 0x0)
	github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.5/command.go:864
istio.io/istio/tools/istio-iptables/pkg/cmd.Execute()
	istio.io/istio@v0.0.0/tools/istio-iptables/pkg/cmd/root.go:181 +0x2d
main.main()
	github.com/tetrateio/istio@/tools/istio-iptables/main.go:22 +0x20
```
(ignore the v0.0.0). This is from master branch. When the test is run on a circleci vm. The VM does have ipv6

```
circleci@default-f18c7071-2f52-4a76-881b-d3468b0cb644:~/tetrate$ ifconfig
docker0   Link encap:Ethernet  HWaddr 02:42:00:60:4e:1a  
          inet addr:172.17.0.1  Bcast:172.17.255.255  Mask:255.255.0.0
          inet6 addr: fe80::42:ff:fe60:4e1a/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:15948 errors:0 dropped:0 overruns:0 frame:0
          TX packets:17185 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:1474556 (1.4 MB)  TX bytes:9272515 (9.2 MB)

ens4      Link encap:Ethernet  HWaddr 42:01:0a:8e:01:e1  
          inet addr:10.142.1.225  Bcast:10.142.1.225  Mask:255.255.255.255
          inet6 addr: fe80::4001:aff:fe8e:1e1/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1460  Metric:1
          RX packets:160543 errors:0 dropped:0 overruns:0 frame:0
          TX packets:104259 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:2486876849 (2.4 GB)  TX bytes:9515959 (9.5 MB)
```

**Comment by rshriram** [comment]
@abhide / @rlenglet ^^^ this has broken a bunch of environments internally. Please fix or lets revert the PR

**Comment by rlenglet** [comment]
@rshriram can you give the full istio-init container spec from the pod spec of one of the failing pods? We'll need that to generate the ip6tables-restore file to debug this.

**Comment by rshriram** [comment]
you mean the k8s yaml from kubectl describe po?

**Comment by rlenglet** [comment]
Yes, please.

**Comment by abhide** [comment]
Looks like iptables-restore failed for ipv4: `istio.io/istio@v0.0.0/tools/istio-iptables/pkg/cmd/run.go:491`

**Comment by abhide** [comment]
To help debugging such issues, I think we should add a fix to `cat` rules files that is passed to `iptables-restore`

**Comment by rlenglet** [comment]
Sure. But in this case, having the istio-init container spec should be sufficient to reproduce this, since that's the only input used to generate the iptables-restore file.

**Comment by rshriram** [comment]
```yaml
{
  "metadata": {
    "name": "simple-http-84b9b6b65c-m79vq",
    "generateName": "simple-http-84b9b6b65c-",
    "namespace": "httpbin-front",
    "selfLink": "/api/v1/namespaces/httpbin-front/pods/simple-http-84b9b6b65c-m79vq",
    "uid": "19c359f8-d62a-429d-86d3-047293caae54",
    "resourceVersion": "2070",
    "creationTimestamp": "2019-12-05T14:49:05Z",
    "labels": {
      "app": "simple-http",
      "pod-template-hash": "84b9b6b65c",
      "security.istio.io/tlsMode": "istio"
    },
    "annotations": {
      "sidecar.istio.io/status": "{\"version\":\"07717017a3fe4a18e81e9619bca2f2da081c80ea9142434e22a502c18ce2e822\",\"initContainers\":[\"istio-init\"],\"containers\":[\"istio-proxy\"],\"volumes\":[\"istio-envoy\",\"istio-certs\"],\"imagePullSecrets\":null}"
    },
    "ownerReferences": [
      {
        "apiVersion": "apps/v1",
        "kind": "ReplicaSet",
        "name": "simple-http-84b9b6b65c",
        "uid": "9e3ad08f-65cb-490c-97b5-92747c112061",
        "controller": true,
        "blockOwnerDeletion": true
      }
    ]
  },
  "spec": {
    "volumes": [
      {
        "name": "default-token-7jkpl",
        "volumeSource": {
          "secret": {
            "secretName": "default-token-7jkpl",
            "defaultMode": 420
          }
        }
      },
      {
        "name": "istio-envoy",
        "volumeSource": {
          "emptyDir": {
            "medium": "Memory"
          }
        }
      },
      {
        "name": "istio-certs",
        "volumeSource": {
          "secret": {
            "secretName": "istio.default",
            "defaultMode": 420,
            "optional": true
          }
        }
      }
    ],
    "initContainers": [
      {
        "name": "istio-init",
        "image": "docker.io/tetrate/proxyv2:0.6.6-istio-bc183b651",
        "args": [
          "-p",
          "15001",
          "-z",
          "15006",
          "-u",
          "1337",
          "-m",
          "REDIRECT",
          "-i",
          "*",
          "-x",
          "",
          "-b",
          "*",
          "-d",
          "15020"
        ],
        "resources": {
          "limits": {
            "cpu": "100m",
            "memory": "50Mi"
          },
          "requests": {
            "cpu": "10m",
            "memory": "10Mi"
          }
        },
        "volumeMounts": [
          {
            "name": "default-token-7jkpl",
            "readOnly": true,
            "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount"
          }
        ],
        "terminationMessagePath": "/dev/termination-log",
        "terminationMessagePolicy": "File",
        "imagePullPolicy": "IfNotPresent",
        "securityContext": {
          "capabilities": {
            "add": [
              "NET_ADMIN"
            ]
          },
          "runAsUser": "0",
          "runAsNonRoot": false
        }
      }
    ],
    "containers": [
      {
        "name": "simple-http",
        "image": "docker.io/arifsetiawan/simple-http:0.2",
        "args": [
          "-service-url",
          "http://httpbin.httpbin-middle.svc.cluster.local:8000/headers"
        ],
        "ports": [
          {
            "containerPort": 9000,
            "protocol": "TCP"
          }
        ],
        "resources": {

        },
        "volumeMounts": [
          {
            "name": "default-token-7jkpl",
            "readOnly": true,
            "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount"
          }
        ],
        "terminationMessagePath": "/dev/termination-log",
        "terminationMessagePolicy": "File",
        "imagePullPolicy": "IfNotPresent"
      },
      {
        "name": "istio-proxy",
        "image": "docker.io/tetrate/proxyv2:0.6.6-istio-bc183b651",
        "args": [
          "proxy",
          "sidecar",
          "--domain",
          "$(POD_NAMESPACE).svc.cluster.local",
          "--configPath",
          "/etc/istio/proxy",
          "--binaryPath",
          "/usr/local/bin/envoy",
          "--serviceCluster",
          "simple-http.$(POD_NAMESPACE)",
          "--drainDuration",
          "45s",
          "--parentShutdownDuration",
          "1m0s",
          "--discoveryAddress",
          "istio-pilot.istio-system:15011",
          "--zipkinAddress",
          "zipkin.istio-system:9411",
          "--dnsRefreshRate",
          "300s",
          "--connectTimeout",
          "10s",
          "--envoyAccessLogService",
          "{\"address\":\"oap.istio-system:11800\",\"tlsSettings\":{\"subjectAltNames\":[]},\"tcpKeepalive\":{\"probes\":3,\"time\":\"10s\",\"interval\":\"10s\"}}",
          "--proxyAdminPort",
          "15000",
          "--concurrency",
          "2",
          "--controlPlaneAuthPolicy",
          "MUTUAL_TLS",
          "--statusPort",
          "15020"
        ],
        "ports": [
          {
            "name": "http-envoy-prom",
            "containerPort": 15090,
            "protocol": "TCP"
          }
        ],
        "env": [
          {
            "name": "POD_NAME",
            "valueFrom": {
              "fieldRef": {
                "apiVersion": "v1",
                "fieldPath": "metadata.name"
              }
            }
          },
          {
            "name": "ISTIO_META_POD_PORTS",
            "value": "[\n    {\"containerPort\":9000,\"protocol\":\"TCP\"}\n]"
          },
          {
            "name": "ISTIO_META_CLUSTER_ID",
            "value": "Kubernetes"
          },
          {
            "name": "POD_NAMESPACE",
            "valueFrom": {
              "fieldRef": {
                "apiVersion": "v1",
                "fieldPath": "metadata.namespace"
              }
            }
          },
          {
            "name": "INSTANCE_IP",
            "valueFrom": {
              "fieldRef": {
                "apiVersion": "v1",
                "fieldPath": "status.podIP"
              }
            }
          },
          {
            "name": "SERVICE_ACCOUNT",
            "valueFrom": {
              "fieldRef": {
                "apiVersion": "v1",
                "fieldPath": "spec.serviceAccountName"
              }
            }
          },
          {
            "name": "ISTIO_AUTO_MTLS_ENABLED",
            "value": "true"
          },
          {
            "name": "ISTIO_META_POD_NAME",
            "valueFrom": {
              "fieldRef": {
                "apiVersion": "v1",
                "fieldPath": "metadata.name"
              }
            }
          },
          {
            "name": "ISTIO_META_CONFIG_NAMESPACE",
            "valueFrom": {
              "fieldRef": {
                "apiVersion": "v1",
                "fieldPath": "metadata.namespace"
              }
            }
          },
          {
            "name": "SDS_ENABLED",
            "value": "false"
          },
          {
            "name": "ISTIO_META_INTERCEPTION_MODE",
            "value": "REDIRECT"
          },
          {
            "name": "ISTIO_METAJSON_LABELS",
            "value": "{\"app\":\"simple-http\",\"pod-template-hash\":\"84b9b6b65c\"}\n"
          },
          {
            "name": "ISTIO_META_WORKLOAD_NAME",
            "value": "simple-http"
          },
          {
            "name": "ISTIO_META_OWNER",
            "value": "kubernetes://apis/apps/v1/namespaces/httpbin-front/deployments/simple-http"
          }
        ],
        "resources": {
          "limits": {
            "cpu": "2",
            "memory": "1Gi"
          },
          "requests": {
            "cpu": "25m",
            "memory": "128Mi"
          }
        },
        "volumeMounts": [
          {
            "name": "istio-envoy",
            "mountPath": "/etc/istio/proxy"
          },
          {
            "name": "istio-certs",
            "readOnly": true,
            "mountPath": "/etc/certs/"
          },
          {
            "name": "default-token-7jkpl",
            "readOnly": true,
            "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount"
          }
        ],
        "readinessProbe": {
          "handler": {
            "httpGet": {
              "path": "/healthz/ready",
              "port": 15020,
              "scheme": "HTTP"
            }
          },
          "initialDelaySeconds": 1,
          "timeoutSeconds": 1,
          "periodSeconds": 2,
          "successThreshold": 1,
          "failureThreshold": 30
        },
        "terminationMessagePath": "/dev/termination-log",
        "terminationMessagePolicy": "File",
        "imagePullPolicy": "IfNotPresent",
        "securityContext": {
          "runAsUser": "1337",
          "readOnlyRootFilesystem": true
        }
      }
    ],
    "restartPolicy": "Always",
    "terminationGracePeriodSeconds": "30",
    "dnsPolicy": "ClusterFirst",
    "serviceAccountName": "default",
    "serviceAccount": "default",
    "nodeName": "minikube",
    "securityContext": {

    },
    "schedulerName": "default-scheduler",
    "tolerations": [
      {
        "key": "node.kubernetes.io/not-ready",
        "operator": "Exists",
        "effect": "NoExecute",
        "tolerationSeconds": "300"
      },
      {
        "key": "node.kubernetes.io/unreachable",
        "operator": "Exists",
        "effect": "NoExecute",
        "tolerationSeconds": "300"
      }
    ],
    "priority": 0,
    "enableServiceLinks": true
  },
  "status": {
    "phase": "Running",
    "conditions": [
      {
        "type": "Initialized",
        "status": "True",
        "lastProbeTime": null,
        "lastTransitionTime": "2019-12-05T14:49:15Z"
      },
      {
        "type": "Ready",
        "status": "True",
        "lastProbeTime": null,
        "lastTransitionTime": "2019-12-05T14:50:10Z"
      },
      {
        "type": "ContainersReady",
        "status": "True",
        "lastProbeTime": null,
        "lastTransitionTime": "2019-12-05T14:50:10Z"
      },
      {
        "type": "PodScheduled",
        "status": "True",
        "lastProbeTime": null,
        "lastTransitionTime": "2019-12-05T14:49:05Z"
      }
    ],
    "hostIP": "10.142.3.9",
    "podIP": "172.17.0.20",
    "startTime": "2019-12-05T14:49:05Z",
    "initContainerStatuses": [
      {
        "name": "istio-init",
        "state": {
          "terminated": {
            "reason": "Completed",
            "startedAt": "2019-12-05T14:49:12Z",
            "finishedAt": "2019-12-05T14:49:12Z",
            "containerID": "docker://3c27e08a2365b0a72628f0f7b11619fdb28a023461cf3a8592b6cfa2497c2122"
          }
        },
        "lastState": {

        },
        "ready": true,
        "image": "tetrate/proxyv2:0.6.6-istio-bc183b651",
        "imageID": "docker-pullable://tetrate/proxyv2@sha256:0399e3d5de7ded9a3171af70f9d09c38419adfc85343d73ce77d98ae5c0a9bb3",
        "containerID": "docker://3c27e08a2365b0a72628f0f7b11619fdb28a023461cf3a8592b6cfa2497c2122"
      }
    ],
    "containerStatuses": [
      {
        "name": "istio-proxy",
        "state": {
          "running": {
            "startedAt": "2019-12-05T14:50:09Z"
          }
        },
        "lastState": {

        },
        "ready": true,
        "image": "tetrate/proxyv2:0.6.6-istio-bc183b651",
        "imageID": "docker-pullable://tetrate/proxyv2@sha256:0399e3d5de7ded9a3171af70f9d09c38419adfc85343d73ce77d98ae5c0a9bb3",
        "containerID": "docker://09d0b1ed0ee3a9767544fbaf1c8822554ace57ad90a531e0f1bd17b802dfc614"
      },
      {
        "name": "simple-http",
        "state": {
          "running": {
            "startedAt": "2019-12-05T14:50:08Z"
          }
        },
        "lastState": {

        },
        "ready": true,
        "image": "arifsetiawan/simple-http:0.2",
        "imageID": "docker-pullable://arifsetiawan/simple-http@sha256:eeb2cdef084beb13c8a8c2e36396e497ce9263cf98522abf325779e51f9a8f51",
        "containerID": "docker://ba02b2fd49d47f1ab6394c348762129e07e8071bc50c5a7d7d64f9f53c927264"
      }
    ],
    "qosClass": "Burstable"
  }
}
```

the proxyv2:0.6.6-istio-bc183b651 corresponds to image built from latest master.
