### ISSUE TITLE
Istio fails using PSP through ClusterRoleBinding in namespace

### ISSUE THREAD

**Issue by davidkarlsen** [istio/istio#19396]
**Bug description**

I have a deployment where the container uses hostPath. This worked just fine, but as soon as I label the namespace for injection `k label namespace eos-jfr-srv-d1 istio-injection=enabled` the pod never gets created due to:

```
status:
    conditions:
    - lastTransitionTime: "2019-12-04T22:28:15Z"
      message: 'pods "eos-jfr-srv-d1-fsjetty-76f7f7fbd5-xqmbx" is forbidden: unable
        to validate against any pod security policy: [spec.volumes[2]: Invalid value:
        "hostPath": hostPath volumes are not allowed to be used]'
      reason: FailedCreate
      status: "True"
      type: ReplicaFailure
    observedGeneration: 1
    replicas: 0
```

PSP is provided through:
```
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-anyuid-hostpath-clusterrole
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:eos-jfr-srv-d1
```

w/o the istio label on the namespace it works just fine.
The pod has access to hostpath by using a PSP allowing so (which is provided through a rolebinding allowing so). If I remove the istio label on the namespace and delete the rs so that the pod is re-created it starts just fine.

**Expected behavior**

Sidecar injection should work.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**
IBM Cloud Private, 3.2.1, which is istio 1.2.2, installed with helm. Using CNI.

**Environment where bug was observed (cloud vendor, OS, etc)**
IBM Cloud Private 3.2.1.
