### ISSUE TITLE
istioctl manifest --set with a list does not work

### ISSUE THREAD

**Issue by prune998** [istio/istio#19392]
**Bug description**
When trying to generate a manifest or deploy Istio using `istioctl manifest generate/apply`, the command fail if you try to pass a list (array) of arguments using `--set`

**Expected behavior**
The behaviour should be the same as using `helm` : 
```
helm template istio install/kubernetes/helm/istio --set global.imagePullSecrets="{aaaaa,bbbbb}" > generated.yml
```
gives a file including : 
```
---
# Source: istio/charts/sidecarInjectorWebhook/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
  - name: aaaaa
  - name: bbbbb
```

**Steps to reproduce the bug**
I tried a lot of combinations like : 
```
istioctl manifest generate --set values.global.imagePullSecrets='{a,b}'

istioctl manifest generate --set values.global.imagePullSecrets="{a,b}"

istioctl manifest generate --set values.global.imagePullSecrets=a,b

istioctl manifest generate --set values.global.imagePullSecrets='a,b'
```
giving the error : 
```
bad path=value (values.global.imagePullSecrets={a}): json: cannot unmarshal string into Go value of type []json.RawMessage
```

or : 
```
istioctl manifest generate --set values.global.imagePullSecrets={a,b}
```
giving : 
```
Error: generate accepts no positional arguments, got []string{"values.global.imagePullSecrets=b"}
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
istioctl version
client version: 1.4.0
```
```
helm version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

**How was Istio installed?**
not relevant. 

**Environment where bug was observed (cloud vendor, OS, etc)**

running commands on OsX
remote cluster on AKS

**Comment by richardwxn** [comment]
--set with a list is not supported yet. Now if you need to overlay list of values, you have to create a IstioControlPlane CR yaml to override.
```yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
   values:
      global:
         imagePullSecrets:
          - a
          - b
```
