### ISSUE TITLE
Fields unconfigurable through operator

### ISSUE THREAD

**Issue by XanderStrike** [istio/istio#19398]
**Bug description**

Some fields that were formerly configurable in the helm values are no longer configurable with operator.

**Expected behavior**

I am able to configure `tolerations` (and _all_ other fields) on ingress gateways (and _all_ other components).

**Steps to reproduce the bug**

Run `istioctl manifest apply -f controlplane.yaml`

where `controlplane.yaml` contains

```
kind: IstioControlPlane
metadata:
  namespace: istio-operator
  name: example-istiocontrolplane
spec:
  profile: default
  values:
    gateways:
      istio-ingressgateway:
        tolerations:
        - key: 'something'
```

An error is returned:

```
Failed to generate and apply manifests, error: failed to generate manifest: input file failed validation with the following errors: unknown field "tolerations" in v1alpha1.IngressGatewayConfig
```

This is because the value is not present in the struct operator attempts to marshal the json into:

https://github.com/istio/operator/blob/master/pkg/apis/istio/v1alpha1/values_types.pb.go#L2043

From what I understand, the intention is to support the complete set of options presented [here](https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/pilot/values.yaml). Is that not the case?

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ ./istio-1.4.0/bin/istioctl version --remote
client version: 1.4.0
control plane version: 1.4.0
data plane version: 1.4.0 (1 proxies)
```

**How was Istio installed?**

`istioctl manifest apply`

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE

CC @astrieanna

**Comment by howardjohn** [comment]
This should work:

```
ik manifest generate -f <(cat <<EOF
kind: IstioControlPlane
metadata:
  namespace: istio-operator
  name: example-istiocontrolplane
spec:
  profile: default
  gateways:
    components:
      ingressGateway:
        k8s:
          tolerations:
          - key: 'my-toleration'

EOF
) | grep my-toleration
```
