### ISSUE TITLE
Not able to route the traffic through egress gateway

### ISSUE THREAD

**Issue by dhineshbabuelango** [istio/istio#19408]
We are using istio in eks. We are trying to configure egress gateway to route our egress traffic through egress gateway for our service which listens on port 8443. But currently only if we create service entry we are able to reach our service on 8443 but if we create egress gateway and virtual service 

Error:
![image](https://user-images.githubusercontent.com/51995628/70205238-5f369a00-175e-11ea-869b-ba6e37ce8545.png)

**Service entry:**
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: kong
spec:
  hosts:
  - ip-10-88-2-78.us-east-1.compute.internal
  ports:
  - number: 8443
    name: tls
    protocol: TLS
  resolution: DNS
```

**Egress Gateway**
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kong-egressgateway
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 8443
      name: tls
      protocol: TLS
    hosts:
    - ip-10-88-2-78.us-east-1.compute.internal
    tls:
      mode: PASSTHROUGH
```

**DestinationRule**
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-kong
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: kong
```

**Virtual Service**
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kong-through-egress-gateway
spec:
  hosts:
  - ip-10-88-2-78.us-east-1.compute.internal
  gateways:
  - mesh
  - kong-egressgateway
  tls:
  - match:
    - gateways:
      - mesh
      port: 8443
      sni_hosts:
      - ip-10-88-2-78.us-east-1.compute.internal
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: kong
        port:
          number: 443
  - match:
    - gateways:
      - kong-egressgateway
      port: 8443
      sni_hosts:
      - ip-10-88-2-78.us-east-1.compute.internal
    route:
    - destination:
        host: ip-10-88-2-78.us-east-1.compute.internal
        port:
          number: 8443
      weight: 100
```

**Comment by vadimeisenbergibm** [comment]
@dhineshbabuelango Note that you use port 443 in the virtual service to direct the traffic to the egress gateway:

```
 tls:
  - match:
    - gateways:
      - mesh
      port: 8443
      sni_hosts:
      - ip-10-88-2-78.us-east-1.compute.internal
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: kong
        port:
          number: 443
```

It seems you should use port 8443.
