### ISSUE TITLE
Adding Memory in HPA when deploying Istio using Helm Charts

### ISSUE THREAD

**Issue by AdheipSingh** [istio/istio#19423]
**Add support for memory in Horizontal Pod Scaling**

**Currently we have autoscaling/v2beta1, can we upgrade to autoscaling/v2beta2, and add memory metrics for scaling also**

```
{{- if and .Values.autoscaleEnabled .Values.autoscaleMin .Values.autoscaleMax }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: istio-pilot
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "pilot.name" . }}
    chart: {{ template "pilot.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  maxReplicas: {{ .Values.autoscaleMax }}
  minReplicas: {{ .Values.autoscaleMin }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istio-pilot
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: {{ .Values.cpu.targetAverageUtilization }}
        type: Utilization
  - resource:
      name: memory
      target:
        averageUtilization: {{ .Values.memory.targetAverageUtilization }}
        type: Utilization
    type: Resource
```

Add the above in helm charts for telemetry, gateways and pilot. I guess v2beta2 will need to be enabled for this.

**Additional context**
