### ISSUE TITLE
Old envoy.lua filter code not deleted

### ISSUE THREAD

**Issue by maciejqantas** [istio/istio#19425]
**Bug description**
We're using an EnvoyFilter written in Lua. We were trying to deploy a new version when we realised some Istio pods were not healthy. We re-installed Istio and re-created the filter. Now, in our ingress gateway in envoy's config_dump we can see two filters named envoy.lua - one with old code version, one with new code version. We cannot get rid of the old one, and as a result, both filters are executed.
Is there anything we can do to delete the stale envoy.lua filter?

Our filter template looks like this (code removed):
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ include "istio-gateway.fullname" . }}-filters
  labels:
    app.kubernetes.io/name: {{ include "istio-gateway.name" . }}
    helm.sh/chart: {{ include "istio-gateway.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  filters:
    - listenerMatch:
        listenerType: GATEWAY
        listenerProtocol: HTTP
      filterType: HTTP
      filterName: envoy.lua
      filterConfig:
        inlineCode: |
```

**Expected behavior**
Old filter code replaced with new filter code

**Steps to reproduce the bug**
N/A

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
istioctl version --remote

client version: 1.4.0
citadel version: 1.2.5
galley version: 1.2.5
ingressgateway version: 1.2.5
ingressgateway-internal version:
pilot version: 1.2.5
policy version: 1.2.5
sidecar-injector version: 1.2.5
telemetry version: 1.2.5
data plane version: 1.2.5 (72 proxies)
```
```
kubectl version

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-eks-b7174d", GitCommit:"b7174db5ee0e30c94a0b9899c20ac980c0850fc8", GitTreeState:"clean", BuildDate:"2019-10-18T17:56:01Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

helm version: gcr.io/kubernetes-helm/tiller:v2.13.1

**How was Istio installed?**
With Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
EKS
