### ISSUE TITLE
portLevelSettings with trafficPolicy works only for outbound traffic?

### ISSUE THREAD

**Issue by moonspirit** [istio/istio#19442]
I'm testing istio traffic policy for a server named matchsvr, both inbound and outbound are effected if i didn't bound it to a specified port:

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: matchsvr-dr 
spec:
  host: matchsvr 
  trafficPolicy:
    connectionPool:
      http:
         http2MaxRequests: 10 
         maxRequestsPerConnection: 10 
```

This effects both inbound and outbound traffic policy:
istioctl pc cluster terrific-sabertooth-matchsvr-7dcf57d559-ntlbp --fqdn matchsvr.default.svc.cluster.local --direction inbound -o json
```
    {
        "name": "inbound|5000|grpc|matchsvr.default.svc.cluster.local",
        "type": "STATIC",
        "connectTimeout": "1s",
        "loadAssignment": {
            "clusterName": "inbound|5000|grpc|matchsvr.default.svc.cluster.local",
            "endpoints": [
                {
                 ....
                }
            ]
        },
        "maxRequestsPerConnection": 10,
        "circuitBreakers": {
            "thresholds": [
                {
                    "maxConnections": 4294967295,
                    "maxPendingRequests": 4294967295,
                    "maxRequests": 10,
                    "maxRetries": 4294967295
                }
            ]
        },
        "metadata": {
            "filterMetadata": {
                "istio": {
                    "config": "/apis/networking/v1alpha3/namespaces/default/destination-rule/matchsvr-dr"
                }
            }
        }
    }
```
and the outbound:
istioctl pc cluster terrific-sabertooth-matchsvr-7dcf57d559-ntlbp --fqdn matchsvr.default.svc.cluster.local --direction outbound -o json
```
    {
        "name": "outbound|5000||matchsvr.default.svc.cluster.local",
        "type": "EDS",
        "edsClusterConfig": {
            "edsConfig": {
                "ads": {}
            },
            "serviceName": "outbound|5000||matchsvr.default.svc.cluster.local"
        },
        "connectTimeout": "1s",
        "maxRequestsPerConnection": 10,
        "circuitBreakers": {
            "thresholds": [
                {
                    "maxConnections": 4294967295,
                    "maxPendingRequests": 4294967295,
                    "maxRequests": 10,
                    "maxRetries": 4294967295
                }
            ]
        },
        "metadata": {
            "filterMetadata": {
                "istio": {
                    "config": "/apis/networking/v1alpha3/namespaces/default/destination-rule/matchsvr-dr"
                }
            }
        }
    }
```

however, if i use portLevelSettings to specify the port like this:
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: matchsvr-dr 
spec:
  host: matchsvr 
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 5000
      connectionPool:
        http:
          http2MaxRequests: 10 
          maxRequestsPerConnection: 10
```
the output of inbound show circuitBreakers config are default values:
```
    {
        "name": "inbound|5000|grpc|matchsvr.default.svc.cluster.local",
        "type": "STATIC",
        "connectTimeout": "1s",
        "loadAssignment": {
            "clusterName": "inbound|5000|grpc|matchsvr.default.svc.cluster.local",
            "endpoints": [
                {
                ...
                }
            ]
        },
        "circuitBreakers": {
            "thresholds": [
                {
                    "maxConnections": 4294967295,
                    "maxPendingRequests": 4294967295,
                    "maxRequests": 4294967295,
                    "maxRetries": 4294967295
                }
            ]
        },
        "metadata": {
            "filterMetadata": {
                "istio": {
                    "config": "/apis/networking/v1alpha3/namespaces/default/destination-rule/matchsvr-dr"
                }
            }
        }
    }
```

Is this expected behaviour?
the version of istio i'm using is istio-1.4.0.

NOTE：fix the indent in the second destination rule.

**Comment by hzxuzhonghu** [comment]
The config is not right,  ithink you want this 
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: matchsvr-dr 
spec:
  host: matchsvr 
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 5000
      connectionPool:
        http:
          http2MaxRequests: 10 
          maxRequestsPerConnection: 10
```

**Comment by moonspirit** [comment]
@hzxuzhonghu Yes, looks like it's the same with my original post.

My question is if we add portLevelSettings in trafficPolicy, only outbound traffic will be affected.
But without portLevelSettings, both inbound and outbound traffic are affected.

Is it so designed?

**Comment by hzxuzhonghu** [comment]
They are different, look at the indents of `connectionPool`

**Comment by moonspirit** [comment]
Sorry it's a copy-paste issue, the indent in original post is invalid, kubectl will report error:
```
admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: port traffic policy must have at least one field
```
i will fix the original post.

**Comment by howardjohn** [comment]
I think this is fixed by the indent - or at least in Istio 1.6 it seems to be. If that is not correct please reopen

I applied

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: matchsvr-dr 
spec:
  host: shell
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 9087
      connectionPool:
        http:
          http2MaxRequests: 10
          maxRequestsPerConnection: 10
```

and got 
```
     "version_info": "2020-05-13T21:56:00Z/8",
     "cluster": {
      "@type": "type.googleapis.com/envoy.api.v2.Cluster",
      "name": "inbound|9087|http|shell.default.svc.cluster.local",
      "type": "STATIC",
      "connect_timeout": "10s",
      "max_requests_per_connection": 10,
      "circuit_breakers": {
       "thresholds": [
        {
         "max_connections": 4294967295,
         "max_pending_requests": 4294967295,
         "max_requests": 10,
         "max_retries": 4294967295
        }
       ]
      },
```
