### ISSUE TITLE
Analyzer for gateway hosts contraint

### ISSUE THREAD

**Issue by sushicw** [istio/istio#19443]
From https://istio.io/docs/reference/config/networking/gateway/:

> It is possible to restrict the set of virtual services that can bind to a gateway server using the namespace/hostname syntax in the hosts field. For example, the following Gateway allows any virtual service in the ns1 namespace to bind to it, while restricting only the virtual service with foo.bar.com host in the ns2 namespace to bind to it.

e.g. this should produce a validation message:

```bash
$ cat <<EOF > test.yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http2
      protocol: HTTP2
    hosts:
    - "ns1/somethingelse.com" # Since this restriction is specified, the httpbin virtualservice can't bind to it
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - "*"
  gateways:
  - httpbin-gateway
  http:
  - route:
    - destination:
        host: httpbin-gateway
EOF

$ istioctl x analyze test.yaml
```

**Comment by sushicw** [comment]
Another related condition to check, from the same doc:

> Only virtual services exported to the gateway’s namespace (e.g., exportTo value of *) can be referenced. Private configurations (e.g., exportTo set to .) will not be available. Refer to the exportTo setting in VirtualService, DestinationRule, and ServiceEntry configurations for details.

Also, we should correctly handle wildcards and "this namespace" symbols as described in the doc. 

Can we reasonably share all this selection logic with Pilot instead of duplicating it?

**Comment by howardjohn** [comment]
Similar thing that would be useful is just the hosts not even matching. For example, this config is broken:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  creationTimestamp: null
  name: gateway-istio-autogenerated-k8s-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - my.domain.example
    port:
      name: http-80-gateway-gateway-istio-system
      number: 80
      protocol: http
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: http-istio-autogenerated-k8s-gateway
  namespace: istio-system
spec:
  exportTo:
  - .
  gateways:
  - gateway-istio-autogenerated-k8s-gateway
  hosts:
  - something-else.com
  http:
  -
    match:
    - headers:
        my-header:
          exact: some-value
      uri:
        prefix: /get
    route:
    - destination:
        host: httpbin
---
```

because `something-else.com` does not equal `my.domain.example`.

Should dig into the implementation for what exactly is valid though. I assume if there is some intersection between the two lists its fine but if not its bad?
