### ISSUE TITLE
JSON response for handler/denier

### ISSUE THREAD

**Issue by ismailbaskin** [istio/istio#19455]
Original Question : https://discuss.istio.io/t/json-response-for-handler-denier/4642
Is there a way for converting handler/denier’s responses to JSON response? Following denier produces “FAILED_PRECONDITION:handler.demo:Not allowed” But I need something like ‘{“message”: “Not Allowed”}’

```yaml
apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
  name: handler
  namespace: demo
spec:
  compiledAdapter: denier
  params:
    status:
      code: 7
      message: Not allowed
```
Thank you.
