### ISSUE TITLE
Destination rule to set mTLS ignores specific host

### ISSUE THREAD

**Issue by FrimIdan** [istio/istio#19459]
**Bug description**
Following the discussion [here](https://discuss.istio.io/t/destination-rule-to-set-mtls-ignores-specific-host/4528).
DestinationRule host resolution is wrong when DestinationRule with a specific host is affecting wildcard service entry host.
 

**Expected behavior**
Only service entry with the exact host should be affected by the DestinationRule

**Steps to reproduce the bug**
Create 2 service entries:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-http
spec:
  hosts:
  - "*.test.com" 
  location: MESH_EXTERNAL
  ports:
  - number: 8080
    name: http
    protocol: HTTP
  resolution: NONE

apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: specific-external-svc-http
spec:
  hosts:
  - test.test.com 
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: NONE
```

Create a DestinationRule to encrypt traffic only for the specific host
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: test-test-istio-mtls
  namespace: test
spec:
  host: "test.test.com"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```

Look at any service config dump and found that the wildcard service entry was affected

```
{
 "version_info": "2019-11-26T12:50:00Z/42",
 "cluster": {
  "name": "outbound|8080||*.test.com",
  "type": "ORIGINAL_DST",
  "connect_timeout": "10s",
  "lb_policy": "CLUSTER_PROVIDED",
  "circuit_breakers": {
   "thresholds": [
    {
     "max_retries": 1024
    }
   ]
  },
  "tls_context": {
   "common_tls_context": {
    "tls_certificates": [
     {
      "certificate_chain": {
       "filename": "/etc/certs/cert-chain.pem"
      },
      "private_key": {
       "filename": "/etc/certs/key.pem"
      }
     }
    ],
    "validation_context": {
     "trusted_ca": {
      "filename": "/etc/certs/root-cert.pem"
     }
    },
    "alpn_protocols": [
     "istio"
    ]
   },
   "sni": "outbound_.80_._.*.test.com"
  },
  "metadata": {
   "filter_metadata": {
    "istio": {
     "config": "/apis/networking/v1alpha3/namespaces/test/destination-rule/test-test-istio-mtls"
    }
   }
  }
 },
 "last_updated": "2019-11-26T12:50:00.192Z"
}
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Istio 1.3.2

**How was Istio installed?**
Not relevant to the bug

**Environment where bug was observed (cloud vendor, OS, etc)**
Not relevant to the bug
