### ISSUE TITLE
Add metric server nanny config for perf cluster

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19457]
The metric server is always dead on these clusters because it is scaled for 30pods/node (Not sure why...). We should specify our own config using https://github.com/kubernetes/autoscaler/tree/master/addon-resizer#example-deployment-file. Its just a config map in kube-system.

**Comment by howardjohn** [comment]
starter: 

```
cat <<EOF | kubectl apply -n kube-system -f -
apiVersion: v1
data:
  NannyConfiguration: |-
    apiVersion: nannyconfig/v1alpha1
    kind: NannyConfiguration
    baseCPU: 100m
    baseMemory: 200Mi
kind: ConfigMap
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
  name: metrics-server-config
  namespace: kube-system
EOF
```


not well tuned though
