### ISSUE TITLE
istioctl manifest apply -f istio.aks.yaml on AKS not working

### ISSUE THREAD

**Issue by JasonAlcoholic** [istio/istio#19470]
**Bug description**
Using https://docs.microsoft.com/en-us/azure/aks/servicemesh-istio-install?pivots=client-operating-system-windows as guide to install istio 1.4.1.
After installation, some of the pods can't start properly.
Sidebar, how to install with istioctl and set up a internal LB? I've checked the document for IstioControlPlane, there seems not have a serviceAnnotations?

```
kubectl get pods --namespace istio-system
NAME                                     READY   STATUS             RESTARTS   AGE
grafana-66b57bdbd5-s5px6                 1/1     Running            0          36m
istio-citadel-6f9859765c-tcgz6           1/1     Running            0          36m
istio-galley-77dfdbcb67-rshwx            2/2     Running            0          36m
istio-ingressgateway-7c5bb64996-f42cz    0/1     Running            0          36m
istio-pilot-66b6dd8749-2mtd6             1/2     Running            0          36m
istio-policy-85474c4599-rr6jn            1/2     CrashLoopBackOff   17         36m
istio-sidecar-injector-cdd5ddc45-t28v5   1/1     Running            0          36m
istio-telemetry-7d8d7f47b-hwbfb          2/2     Running            17         36m
istio-tracing-59545ff57-n2v99            0/1     CrashLoopBackOff   13         36m
kiali-6864df5756-xxq4j                   1/1     Running            0          36m
prometheus-7cf945fbfb-gnbxk              1/1     Running            0          36m
```

**Expected behavior**
Successfully deployed
**Steps to reproduce the bug**
1. Create ns
`kubectl create namespace istio-system --save-config
`
2. Create secrets
```
apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: istio-system
  labels:
    app: grafana
type: Opaque
data:
  username: Z3JhZmFuYQ==
  passphrase: Z3JhZmFuYXBzd2Q=
```

```
apiVersion: v1
kind: Secret
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
type: Opaque
data:
  username: a2lhbGk=
  passphrase: a2lhbGlwc3dk
```

3. Create install yaml
```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  # Use the default profile as the base
  # More details at: https://istio.io/docs/setup/additional-setup/config-profiles/
  profile: default
  values:
    global:
      # Ensure that the Istio pods are only scheduled to run on Linux nodes
      defaultNodeSelector:
        beta.kubernetes.io/os: linux
      # Enable mutual TLS for the control plane
      controlPlaneSecurityEnabled: true
      mtls:
        # Require all service to service communication to have mtls
        enabled: false
    grafana:
      # Enable Grafana deployment for analytics and monitoring dashboards
      enabled: true
      security:
        # Enable authentication for Grafana
        enabled: true
    kiali:
      # Enable the Kiali deployment for a service mesh observability dashboard
      enabled: true
    tracing:
      # Enable the Jaeger deployment for tracing
      enabled: true
```
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
istioctl version --remote
client version: 1.4.1
control plane version: 1.4.1
data plane version: none
Error: 2 errors occurred:
        * error execing into istio-policy-85474c4599-rr6jn mixer container: unable to upgrade connection: container not found ("mixer")
        * error execing into istio-telemetry-7d8d7f47b-hwbfb mixer container: unable to upgrade connection: container not found ("mixer")
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.12", GitCommit:"a8b52209ee172232b6db7a6e0ce2adc77458829f", GitTreeState:"clean", BuildDate:"2019-10-15T12:04:30Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
AKS
Windows with AZ CLI
