### ISSUE TITLE
Doesn't seem possible to set accessLogEncoding using installer

### ISSUE THREAD

**Issue by tbarrella** [istio/istio#19516]
**Bug description**
When using `istioctl manifest`, `values.global.proxy.accessLogEncoding` doesn't seem to have an effect

**Expected behavior**
Setting `accessLogEncoding: JSON` changes the format for proxy access logs

**Steps to reproduce the bug**
- Create IstioControlPlane config `control-plane.yaml` like
```yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  values:
    global:
      proxy:
        accessLogEncoding: JSON
        accessLogFile: /dev/stdout
```
- `istioctl manifest apply -f control-plane.yaml`
- View istio-proxy logs for e.g. Pilot

**Version**
1.4.2

**How was Istio installed?**
istioctl
