### ISSUE TITLE
Inconsistent configuration required for accessing VirtualServices between Gateways and Pods

### ISSUE THREAD

**Issue by desek** [istio/istio#19520]
**Bug description**

Inconsistent configuration required when accessing VirtualServices from Pods and Gateway.

Accessing a VirtualService from Pods require spec.hosts=service.namespace

```yaml
# Working example
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mySVC
  namespace: myNS
  labels:
    app: mySVC
    lifecycle: service
spec:
  hosts:
  - mySVC.myNS # works with namespace suffix
  http:
  - route:
    - destination:
        port:
          number: 80
        host: mySVC
        subset: v1-3-77-dev
```

```yaml
# Not working example
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mySVC
  namespace: myNS
  labels:
    app: mySVC
    lifecycle: service
spec:
  hosts:
  - mySVC # no namespace suffix
  http:
  - route:
    - destination:
        port:
          number: 80
        host: mySVC
        subset: v1-3-77-dev
```

Accessing a VirtualService via a Gateway through the hosts specified in the gateway only requires VirtualService spec.host=service if Gateway is within the same namespace as the VirtualService.

```yaml
# Working example
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mySVC
  namespace: myNS
  labels:
    app: mySVC
    lifecycle: service
spec:
  hosts:
  - mySVC # no namespace suffix
  gateway:
  - mySVC-gw
  http:
  - route:
    - destination:
        port:
          number: 80
        host: mySVC
        subset: v1-3-77-dev
```

[ ] Configuration Infrastructure  
[ ] Docs  
[ ] Installation  
[X] Networking  
[ ] Performance and Scalability  
[ ] Policies and Telemetry  
[ ] Security  
[ ] Test and Release  
[ ] User Experience  
[ ] Developer Infrastructure  

**Expected behavior**

Declaring spec.hosts=service (without namespace, if VS and SVC is within the same namespace) should work for both Pods and Gateways

**Steps to reproduce the bug**

Deploy a VirtualService that's not attached to a Gateway that has a spec.host that ommits namespace (see "Not working example") and use a pod (i.e. nicolaka/netshoot) within the same namespace as the VirtualService to curl the hostname (i.e. curl -vk http://mySVC).

If VirtualService spec.hosts does not have the namespace as suffix it will return a 404.
When spec.hosts is suffixed with the namespace it will return a 200 when running the same command (curl -vk http://mySVC).

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```bash
> istioctl version --remote
client version: unknown
control plane version: 1.3.5
```

```bash
> kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:39:02Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

Istio was installed on Azure Kubernets Service (AKS) with Helm chart version 1.3.5 and app version 1.3.5 and the below global values:

```yaml
global:
  k8sIngress:
    enabled: false
  controlPlaneSecurityEnabled: false
  disablePolicyChecks: true
  enableTracing: true
  mtls:
    enabled: true
  sds:
    enabled: false
  proxy:
    autoInject: enabled
    includeIPRanges: "*"
    excludeIPRanges: ""
    accessLogFile: "/dev/stdout"
    logLevel: debug
  outboundTrafficPolicy:
    mode: ALLOW_ANY
gateways:
  enabled: true
  istio-ingressgateway:
    enabled: true
    autoscaleMin: 2
    autoscaleMax: 8
    serviceAnnotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      external-dns.alpha.kubernetes.io/hostname: OMITTED
    sds:
      enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 1024Mi
```

**Environment where bug was observed (cloud vendor, OS, etc)**

Azure AKS running Kubernetes 1.14.7 on Ubuntu 16.04.
