### ISSUE TITLE
EnvoyFilter inbound doesn't work

### ISSUE THREAD

**Issue by lfundaro** [istio/istio#19549]
**Bug description**

adding this config doesn't work

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: add-calling-service-inbound
spec:
  workloadSelector:
    labels:
      app: echo-ping
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.router"
    patch:
      operation: INSERT_BEFORE
      value:
       name: envoy.lua
       config:
         inlineCode: |
           function envoy_on_request(request_handle)
             request_handle:headers():add("x-foo", "bar")
           end
```

**Expected behavior**

Lua code will be called for every incoming service call. 

**Steps to reproduce the bug**

apply the filter and check headers on the receiving end 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$> istioctl version
client version: 1.4.2
control plane version: 1.4.2
data plane version: 1.4.2 (3 proxies)

$> kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

`istioctl manifest apply`

**Environment where bug was observed (cloud vendor, OS, etc)**

`microk8s`

[istio-dump.tar.gz](https://github.com/istio/istio/files/3956042/istio-dump.tar.gz)

Thanks in advance

**Comment by lfundaro** [comment]
cc @rshriram @hzxuzhonghu

**Comment by rshriram** [comment]
You might need to use typedConfig (the any form of a filter and specify the filter's type 'apis.google.co...' [you can get this from envoy]

**Comment by nmnellis** [comment]
i am seeing the same thing with the following yaml, no logs in pilot or sidecar, also its not showing up in the listener filter list.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: tenant-service
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/name: tenant-service

  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          portNumber: 5050
          filterChain:
            filter:
              name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
              subFilter:
                name: envoy.grpc_json_transcoder
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.grpc_json_transcoder
          config:
            printOptions:
              alwaysPrintPrimitiveFields: false
              preserveProtoFieldNames: false
            convertGrpcStatus: True
            services:
              - summaft.tenantservice.v1.TenantAPI
            protoDescriptorBin: <bin>
```

**Comment by nmnellis** [comment]
@lfundaro the old spec for EnvoyFilter seems to still work.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: tenant-service
spec:
  workloadLabels:
    app.kubernetes.io/name: tenant-service
  filters:
  - listenerMatch:
      portNumber: 5050
      listenerType: SIDECAR_INBOUND
    insertPosition:
      index: BEFORE
      relativeTo: envoy.router
    filterName: envoy.grpc_json_transcoder
    filterType: HTTP
    filterConfig:
      printOptions:
        alwaysPrintPrimitiveFields: False
        preserveProtoFieldNames: False
      convertGrpcStatus: True
      services:
        - summaft.tenantservice.v1.TenantAPI
      protoDescriptorBin: <bin>
```

**Comment by hzxuzhonghu** [comment]
@nmnellis  The below seems not right, firstly, we have no `typed_config` field in listener match, secondly, i do not think  `envoy.grpc_json_transcoder` has been configured.

```
          filterChain:
            filter:
              name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
              subFilter:
                name: envoy.grpc_json_transcoder
```

**Comment by hobbytp** [comment]
The new envoy filter and old one difference are :
1. with the new spec lua envoyfilter configured, it only modify one listener which name “<POD_IP>_9080”
2. with the old spec lua envoy filter configured. it will modify two listener <POD_IP>_9080 and virtualInbound (0.0.0.0: 15006)
without the modification for virtualInbound, it will fail.

**Comment by devstein** [comment]
@hobbytp Do you have an example of fixing the 1st one to also modify the virutalInbound?

**Comment by TimVosch** [comment]
Is there any update on this? I walked into the same issue/bug. A solution is removing the `portNumber` altogether.

```diff
...
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
-          portNumber: 5000
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
              subFilter:
                name: "envoy.router"
      patch:
...
```

**Comment by lainra** [comment]
@TimVosch I came to the same conclusion as the solution you suggested above. However, this is a regression from the previous specification of the EnvoyFilter as you will apply this filter to all listeners in an Envoy proxy.
This poses problems when you want to have specific filter for one specific port (which is quite standard use case), i.e one HTTP port, one gRPC port, using gRPC-JSON transcoding, you want to apply this on the gRPC endpoint only.

@howardjohn Do you have any feedback on this? We should keep the same granularity level as the old EnvoyFilter format to incentivize users to migrate to the new format.

As of now, it is better to keep using the deprecated version. (deprecated Since 1.3?)

**Comment by mstrYoda** [comment]
I've similar issue: https://github.com/istio/istio/issues/22618

Is there any solution? I could not make it work the lua filters.

**Comment by rshriram** [comment]
@TimVosch you can do 
```
listener:
 name: VirtualInbound
```

in order to appl ythe filter to the virtual inbound as well.

**Comment by lizongshen** [comment]
I have encountered similar problems. Is there any progress?

**Comment by mstrYoda** [comment]
@lfundaro @lizongshen I've find a solution yesterday. Be sure that you have a service for your deployment and in your service define ports as below:
```

spec:
  ports:
  - name: http # this is the important part
  port: <port>
  targetPort: <targetPort>
```

**Comment by lizongshen** [comment]
@mstrYoda Thank you for being right!

**Comment by james-thomson** [comment]
Sorry if I'm off base here and misunderstand how this works but I don't see how this has been fixed.
The associated PR uses the "destinationPort" to match but that isn't the servicePort, which is what I've used previously to match on port and also what the EnvoyFilter docs say to use.

For example, say I have the httpbin sample running, which uses the service port 8000. This EnvoyFilter should work

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: test-port-matching
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              name: envoy.router
        portNumber: 8000
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.lua
        typed_config:
          '@type': type.googleapis.com/envoy.config.filter.http.lua.v2.Lua
          inlineCode: |
            function envoy_on_request(request)
                request:respond({[":status"] = "200"}, "It works!")
            end
  workloadSelector:
    labels:
      app: httpbin
```
but this does not. It's only when I change the portNumber in the listener match to 80 that it is applied to the required listeners.

Using the deprecated format did work eg
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: test-legacy-port-matching
  namespace: httpbin
spec:
  workloadLabels:
    app: httpbin
  filters:
  - listenerMatch:
      portNumber: 8000
      listenerType: SIDECAR_INBOUND
      listenerProtocol: HTTP
    filterName: envoy.lua
    filterType: HTTP
    filterConfig:
      inlineCode: |
        function envoy_on_request(request)
            request:respond({[":status"] = "200"}, "It works!")
        end
```

but support for this old envoyfilter format appears to have been removed since 1.6 so this workaround is no longer available.

So I think this ticket should be reopened.
