### ISSUE TITLE
istioctl profile should be relative to the default

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19552]
Right now if I run `istioctl profile {diff,dump}` it is outputing a huge amount of info since it is related to the default profile. It should be able what is changed since the default

For example, `istioctl profile dump` should show:
```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  security:
    components:
      nodeAgent:
        enabled: true
  values:
    global:
      controlPlaneSecurityEnabled: true
      mtls:
        enabled: true
      sds:
        enabled: true
        udsPath: "unix:/var/run/sds/uds_path"
        token:
          aud: "istio-ca"
    nodeagent:
      image: node-agent-k8s
      env:
        CA_PROVIDER: "Citadel"
        CA_ADDR: "istio-citadel:8060"
        VALID_TOKEN: true
```

Similarly, diff should probably just show the above, not 1000 lines of all the default stuff. Its not even accurate if you say `ik profile diff sds default` since it doesn't account for the fact that sds is applied above default.
