### ISSUE TITLE
istio-operator: ingressgateway type not honored

### ISSUE THREAD

**Issue by Morriz** [istio/istio#19575]
**Bug description**
When using the IstioControlPlane profile `default` with override `values.gateways.istio-ingressgateway.type=ClusterIP` the gateway is still instantiated as type `LoadBalancer`

**Expected behavior**
to get a gateway of type ClusterIP

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio:
client version: 1.4.0
control plane version: 1.4-alpha.10f63ffc12a557209341a7289e5716cf8021578c
data plane version: 1.4-alpha.10f63ffc12a557209341a7289e5716cf8021578c (12 proxies)

k8s: v1.14.8
helm: v2.16.0

**How was Istio installed?**
istio-operator

**Environment where bug was observed (cloud vendor, OS, etc)**
azure

**Comment by Morriz** [comment]
closing as it I did it incorrectly but is possible:
```yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  namespace: istio-operator
  name: istiocontrolplane
spec:
  profile: default
  gateways:
    components:
      ingressGateway:
        k8s:
          readinessProbe:
            failureThreshold: 20
  values:
    gateways:
      istio-ingressgateway:
        type: ClusterIP
```
