### ISSUE TITLE
Rate Limiting does not work to a HTTPS service

### ISSUE THREAD

**Issue by jonnysgomes** [istio/istio#19580]
(NOTE: This is used to report product bugs:
To report a security vulnerability, please visit https://istio.io/about/security-vulnerabilities/
To ask questions about how to use Istio, please visit https://discuss.istio.io
)

**Bug description**

When configuring rate limiting to a HTTPS service, the rate limiting configuration is not working. The service always returns 200 instead of returns 429 when the limit is hit.

**Affected product area**

**Expected behavior**

Service returning the 429 status code when the rate limiting is hit.

Steps to reproduce the bug

eg. Assume I'd like to limit rate to 10 requests in 10min.
If I configure the rate limiting handler with:

```
      maxAmount: 10
      validDuration: 10m
```

When I use that configuration to a HTTP service, it works. I mean, after some requests, the service returns 429, as expected. But when I apply that configuration to a HTTPS service, I never receive 429.

**Version**

istio: 1.3.5
kubernetes: 1.12.10

**How was Istio installed?**

helm

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS EKS Cluster with Kubernetes v1.12.10

**Note**

The whole rate limiting configuration is the following:
```
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: redishandler
  namespace: istio-system
spec:
  compiledAdapter: redisquota
  params:
    redisServerUrl: redis-cluster-svc.redis.svc.cluster.local:6379
    connectionPoolSize: 10
    quotas:
    - name: requestcountquota.instance.istio-system
      maxAmount: 10
      validDuration: 10m
      bucketDuration: 1s
      rateLimitAlgorithm: ROLLING_WINDOW
---
apiVersion: config.istio.io/v1alpha2
kind: instance
metadata:
  name: requestcountquota
  namespace: istio-system
spec:
  compiledTemplate: quota
  params:
    dimensions:
      requestPath: request.path | "unknown"
---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpec
metadata:
  name: requestcountquotaspec
  namespace: istio-system
spec:
  rules:
  - quotas:
    - charge: 1
      quota: requestcountquota
---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpecBinding
metadata:
  name: requestcountquotaspecbinding
  namespace: istio-system
spec:
  quotaSpecs:
  - name: requestcountquotaspec
    namespace: istio-system
  services:
  - name: https-svc
    namespace: echoserver-ns
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: requestcountquotarule
  namespace: istio-system
spec:
  actions:
  - handler: redishandler
    instances:
    - requestcountquota

```
