### ISSUE TITLE
IstioControlPlane global.defaultTolerations not working

### ISSUE THREAD

**Issue by elvizlai** [istio/istio#19605]
**Bug description**

```
helm template install/kubernetes/helm/istio \
    --set global.defaultTolerations[0].key="node-role.kubernetes.io/master" \
    > $HOME/istio.yaml
```
~~NOT work now, any break change?~~

**SOLVED: changing `oh-my-zsh` to `bash` works.**

Then I tried using `istioctl` with `IstioControlPlane`
```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  security:
    components:
      certManager:
        enabled: true
  values:
    global:
      defaultTolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Equal"
          effect: "PreferNoSchedule"
```

It's output:
```
input file failed validation with the following errors: unknown field "defaultTolerations" in v1alpha1.GlobalConfig
```

[ ] Configuration Infrastructure
[ ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
v1.4.2

helm:
```
Client: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
```

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
