### ISSUE TITLE
http is ok https is 503

### ISSUE THREAD

**Issue by cheerego** [istio/istio#19614]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
http is ok
https is not ok, got 503 response code and response body is `upstream connect error or disconnect/reset before headers. reset reason: connection termination`
```
curl -v https://stage.xxx.com
* Rebuilt URL to: https://stage.xxx.com/
*   Trying 51.xxx.142.168...
* TCP_NODELAY set
* Connected to stage.makex.io (51.124.142.168) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.xxx.com
*  start date: May 30 00:00:00 2019 GMT
*  expire date: May 29 12:00:00 2020 GMT
*  subjectAltName: host "stage.makex.io" matched cert's "*.makex.io"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=RapidSSL RSA CA 2018
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f86de004600)
> GET / HTTP/2
> Host: stage.xxx.com
> User-Agent: curl/7.54.0
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 503
< content-length: 95
< content-type: text/plain
< date: Mon, 16 Dec 2019 15:26:19 GMT
< server: istio-envoy
<
* Connection #0 to host stage.makex.io left intact
upstream connect error or disconnect/reset before headers. reset reason: connection termination%
```

**Steps to reproduce the bug**
```


apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: abc-gateway
  namespace: gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*/stage.xxx.com"
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        serverCertificate: /etc/istio/ingressgateway-certs/makexio.pem
        privateKey: /etc/istio/ingressgateway-certs/makexio.key
      hosts:
        - "*/stage.xxx.com"

---
apiVersion: v1
kind: Service
metadata:
  name: stage
  namespace: prod
  labels:
    app: stage
    helm.sh/chart: stage-helm-0.1.0
spec:
  selector:
    app: stage
  ports:
    - port: 3008
  type: ClusterIP

---
# Source: stage-helm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stage-v1
  namespace: prod
  labels:
    app: stage-v1
    helm.sh/chart: stage-helm-0.1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stage
      version: v1
  template:
    metadata:
      labels:
        app: stage
        version: v1
        helm.sh/chart: stage-helm-0.1.0
        commit/id: 78d2bc60fcd6dea29272e4beccfeefdde82fe46a
    spec:
      containers:
        - name: stage
          image: nginx
          imagePullPolicy: Always
          ports:
            - name: stage
              containerPort: 80

---
# Source: stage-helm/templates/virtualservice.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: stage
  namespace: prod
  labels:
    helm.sh/chart: stage-helm-0.1.0
spec:
  hosts:
  - stage.xxx.com
  gateways:
  - gateway/abc-gateway
  http:
  - route:
    - destination:
        host: stage
        port:
          number: 80
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: stage
  namespace: prod
  labels:
    helm.sh/chart: stage-helm-0.1.0
spec:
  host: stage
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
  subsets:
  - name: v1
    labels:
      version: v1

```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
istioctl version --remote
client version: 1.4.0
control plane version: 1.4.0
data plane version: 1.4.0 (19 proxies)
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-07T09:57:54Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"1da9875156ba0ad48e7d09a5d00e41489507f592", GitTreeState:"clean", BuildDate:"2019-11-14T05:19:20Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
```
istioctl manifest apply -f istio.aks.yaml
```
**Environment where bug was observed (cloud vendor, OS, etc)**
```
ms azure
```

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by cheerego** [comment]
I need help or I will lose my job.

**Comment by stewartbutler** [comment]
I'm fairly certain that that is not a valid Gateway. The hosts section in particular looks suspicious -- I don't think the hosts are formatted correctly.

Take a look at https://istio.io/docs/tasks/traffic-management/ingress/ingress-control/ and see if that helps get you pointed in the right direction. 

I'm not sure why HTTP would be working if the gateway is messed up. Are you sure you are getting valid data back from the HTTP endpoint, and that that data path is passing through your gateway?

**Comment by cheerego** [comment]
> I'm fairly certain that that is not a valid Gateway. The hosts section in particular looks suspicious -- I don't think the hosts are formatted correctly.
> 
> Take a look at https://istio.io/docs/tasks/traffic-management/ingress/ingress-control/ and see if that helps get you pointed in the right direction.
> 
> I'm not sure why HTTP would be working if the gateway is messed up. Are you sure you are getting valid data back from the HTTP endpoint, and that that data path is passing through your gateway?

the hosts is normal host , I just don't want to export the true domain , I write it as a error domain.

**Comment by cheerego** [comment]
I resolve this issue.

https://istio.io/docs/ops/deployment/requirements/

![image](https://user-images.githubusercontent.com/13394349/70978327-89874080-20ea-11ea-82d4-f8b2e94f20bc.png)


I need set `name` to Service

```
apiVersion: v1
kind: Service
metadata:
  name: stage
  namespace: prod
  labels:
    app: stage
    helm.sh/chart: stage-helm-0.1.0
spec:
  selector:
    app: stage
  ports:
    - port: 3008
      ## important,we need add this 
      name: http
     ## important,we need add this 
  type: ClusterIP


```
