### ISSUE TITLE
ingressgateway tls PASSTHROUGH does not handle hostnames with dashes

### ISSUE THREAD

**Issue by beckend** [istio/istio#19610]
**Bug description**

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
client version: 1.4.2
citadel version: 1.4.2
nodeagent version: 
sidecar-injector version: 1.4.2
galley version: 1.4.2
policy version: 1.4.2
telemetry version: 1.4.2
pilot version: 1.4.2
ingressgateway version: 1.4.2
data plane version: 1.4.2 (12 proxies)

**How was Istio installed?**
```shell
istioctl manifest generate \
    --set profile=sds \
    --set values.nodeagent.enabled=true \
    --set values.istiocoredns.enabled=true \
    --set values.istiocoredns.coreDNSImage="coredns/coredns:latest" \
    --set values.pilot.policy.enabled=true \
    --set values.mixer.policy.enabled=true \
    --set values.global.disablePolicyChecks=false \
    --set values.grafana.enabled=true \
    --set values.kiali.enabled=true \
    --set values.kiali.createDemoSecret=true \
    --set values.kiali.dashboard.jaegerURL="http://jaeger-query:16686" \
    --set values.kiali.dashboard.grafanaURL="http://grafana:3000" \
    --set values.tracing.enabled=true \
    --set values.gateways.istio-egressgateway.enabled=true \
    --set values.global.mtls.enabled=false \
    --set values.global.mtls.auto=false \
    --set values.global.controlPlaneSecurityEnabled=true \
    --set values.gateways.istio-ingressgateway.sds.enabled=true | kubectl apply -f -
```
**Environment where bug was observed (cloud vendor, OS, etc)**

Arch Linux - Kernel 5.4.3-arch1-1
K3S V1.0
```shell
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--no-deploy=traefik,local-storage,servicelb --flannel-iface=net0"
```
MetalLB
```shell
  curl https://raw.githubusercontent.com/google/metallb/v0.8.3/manifests/metallb.yaml | kkapp -
  
  cat <<EOF | kkapp -
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.1.101-192.168.1.150
```

LoadBalancer ingressgateway:
```shell
istio-system           istio-ingressgateway        LoadBalancer   10.43.51.21     192.168.1.101   15020:31381/TCP,80:32732/TCP,443:30678/TCP,15029:31451/TCP,15030:31575/TCP,15031:30896/TCP,15032:30503/TCP,15443:31463/TCP,9735:32000/TCP,9736:32001/TCP   17h   app=istio-ingressgateway
```

### Service:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: admin-ldap-mailserver
  namespace: default
  labels:
    deployment: admin-ldap-mailserver
spec:
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
  selector:
    deployment: admin-ldap-mailserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-ldap-mailserver
  namespace: default
  labels:
    deployment: admin-ldap-mailserver
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: admin-ldap-mailserver
      version: v1
  template:
    metadata:
      labels:
        deployment: admin-ldap-mailserver
        version: v1
    spec:
      containers:
        - name: admin-ldap-mailserver
          image: wheelybird/ldap-user-manager:latest
          ports:
            - containerPort: 80
            - containerPort: 443
          env:
            - name: LDAP_URI
              value: "ldap://ldap-mailserver:389"
            - name: LDAP_BASE_DN
              value: "dc=localdomain,dc=local"
            - name: LDAP_ADMIN_BIND_DN
              value: "cn=admin,dc=localdomain,dc=local"
            - name: LDAP_ADMIN_BIND_PWD
              value: "weirdfact26jumpymice26"
            - name: LDAP_ADMINS_GROUP
              value: "admins"
            - name: SERVER_HOSTNAME
              value: "admin-ldap-mailserver.home.arpa"
            - name: LDAP_USER_OU
              value: "users"
            - name: LDAP_GROUP_OU
              value: "groups"
            - name: EMAIL_DOMAIN
              value: "username@localdomain.local"
            - name: DEFAULT_USER_SHELL
              value: "/bin/zsh"
            - name: SITE_NAME
              value: "Test"
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
              readOnly: true
            - name: cert-pem
              mountPath: /opt/ssl/server.crt
              readOnly: true
            - name: cert-key-pem
              mountPath: /opt/ssl/server.key
              readOnly: true
      volumes:
        - name: tz-config
          hostPath:
            path: /mnt/storage-1/@/srv/docker/volumes/common/etc/localtime
            type: File
        - name: cert-pem
          hostPath:
            path: /etc/certificates-custom/_wildcard.home.arpa+4.pem
            type: File
        - name: cert-key-pem
          hostPath:
            path: /etc/certificates-custom/_wildcard.home.arpa+4-key.pem
            type: File

```
---
# Replication
---
##Working:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway-admin-ldap-mailserver
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https-admin-ldap-mailserver
        protocol: HTTPS
      hosts:
        - "hi.home.arpa"
      tls:
        mode: PASSTHROUGH
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-admin-ldap-mailserver
  namespace: default
spec:
  hosts:
    - "hi.home.arpa"
  gateways:
    - gateway-admin-ldap-mailserver
  tls:
    - match:
        - port: 443
          sni_hosts:
            - "hi.home.arpa"
      route:
        - destination:
            host: admin-ldap-mailserver
            port:
              number: 443

```

Results:
```shell
$ curl -v --resolve hi.home.arpa:443:192.168.1.101  https://hi.home.arpa -k
* Added hi.home.arpa:443:192.168.1.101 to DNS cache
* Hostname hi.home.arpa was found in DNS cache
*   Trying 192.168.1.101:443...
* TCP_NODELAY set
* Connected to hi.home.arpa (192.168.1.101) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: O=mkcert development certificate; OU=root@mini-server-1
*  start date: Jun  1 00:00:00 2019 GMT
*  expire date: Dec 16 10:32:20 2029 GMT
*  issuer: O=mkcert development CA; OU=root@archiso; CN=mkcert root@archiso
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: hi.home.arpa
> User-Agent: curl/7.67.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Mon, 16 Dec 2019 12:49:09 GMT
< Server: Apache/2.4.25 (Debian)
< X-Powered-By: PHP/7.0.33
< Vary: Accept-Encoding
< Content-Length: 709
< Content-Type: text/html; charset=UTF-8
< 
<HTML>
<HEAD>
 <TITLE>Test</TITLE>
 <meta charset="utf-8">
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</HEAD>
<BODY>
  <nav class="navbar navbar-default">
   <div class="container-fluid">
   <div class="navbar-header">
     <a class="navbar-brand" href="#">LINKEN</a>
   </div>
     <ul class="nav navbar-nav">
     <li><a href='/log_in'>Log In</a></li>
    </ul>
   </div>
  </nav>
  </BODY>
</HTML>
* Connection #0 to host hi.home.arpa left intact
```

## Not working:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway-admin-ldap-mailserver
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https-admin-ldap-mailserver
        protocol: HTTPS
      hosts:
        - "admin-ldap-mailserver.home.arpa"
      tls:
        mode: PASSTHROUGH
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-admin-ldap-mailserver
  namespace: default
spec:
  hosts:
    - "admin-ldap-mailserver.home.arpa"
  gateways:
    - gateway-admin-ldap-mailserver
  tls:
    - match:
        - port: 443
          sni_hosts:
            - "admin-ldap-mailserver.home.arpa"
      route:
        - destination:
            host: admin-ldap-mailserver
            port:
              number: 443
```

Results:
```shell
$ curl -v --resolve admin-ldap-mailserver.home.arpa:443:192.168.1.101  https://admin-ldap-mailserver.home.arpa -k
* Added admin-ldap-mailserver.home.arpa:443:192.168.1.101 to DNS cache
* Hostname admin-ldap-mailserver.home.arpa was found in DNS cache
*   Trying 192.168.1.101:443...
* TCP_NODELAY set
* Connected to admin-ldap-mailserver.home.arpa (192.168.1.101) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to admin-ldap-mailserver.home.arpa:443 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to admin-ldap-mailserver.home.arpa:443
```
