### ISSUE TITLE
Document confusing

### ISSUE THREAD

**Issue by elvizlai** [istio/istio#19629]
**Bug description**

file `bootstrap.yaml`
```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  values:
    mixer:
      telemetry:
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
```

istioctl manifest generate -f ./bootstrap.yaml > $HOME/generated-manifest.yaml resouce not changed!

the generate `manifest.yaml` not changed to `cpu: 50m, memory: 100Mi` as expected.
```
          requests:
            cpu: 1000m
            memory: 1G
```

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**
v1.4.2

**Environment where bug was observed (cloud vendor, OS, etc)**
