### ISSUE TITLE
istioctl profile dump and migrate should add ICP header

### ISSUE THREAD

**Issue by luanlengli** [istio/istio#19659]
- istio version: 1.4.2

- Problem 1
```shell
istioctl profile dump demo > istio-demo.yaml
istioctl manifest apply -f istio-demo.yaml
```
it returns fail like
```shell
could not unmarshal the overlay file: error decoding object: error unmarshaling JSON: while decoding JSON: Object 'Kind' is missing in
```
add this to file header will work fine
```yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
   ...
```

- Problem 2

The Profile samples in [Installation Configuration Profiles](https://istio.io/docs/reference/config/istio.operator.v1alpha12.pb/) also not work !

> 6. Default install with values.yaml customizations for proxy
> ```yaml
> spec:
>   traffic_management:
>     components:
>       proxy:
>         values:
>         - global.proxy.enableCoreDump: true
>         - global.proxy.dnsRefreshRate: 10s
> ```

use this will work fine
```yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  values:
    global:
      proxy:
        enableCoreDump: true
        dnsRefreshRate: 10s
```
