### ISSUE TITLE
Too low pod CPU limit makes curl fail in REGISTRY_ONLY mode, but not in ALLOW_ANY

### ISSUE THREAD

**Issue by nostra** [istio/istio#19660]
**Bug description**

When running the sleep pod from the sample directory with a cpu limit of `30m`,
curl will fail with exit code 35 even with a valid service entry. 

With a higher cpu limit (`100m`), the behaviour is as expected, i.e. the https 
content  is retrieved. If I change the istio mode from `REGISTRY_ONLY` to `ALLOW_ANY`,
the behaviour is also as expected.

The curious thing about this, is that it is not discernible that the cpu limit is
the cause for this behaviour. The istio-proxy sidecar gives no output at all.

```
```

**Expected behavior**

That it is possible to discern between a endpoint without a valid ServiceEntry and 
wrongly configured pod. Current behaviour will give the same kind of response for 
both scenarios.  

**Steps to reproduce the bug**

Using the sleep sample: https://github.com/istio/istio/blob/master/samples/sleep/sleep.yaml

The manifest is modified with:
```
        resources:
          limits:
            cpu: 30m
```

Using https://slack.com as an example, I add a service entry:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: slack.com
spec:
  hosts:
  - "slack.com" 
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
```

Enter the pod to execute curl:
```
/ # curl https://slack.com
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to slack.com:443 
```

**Version**

Istio version: 1.3.6

**How was Istio installed?**

```
kubectl create namespace istio-system
helm template istio-init install/kubernetes/helm/istio-init --set global.mtls.enabled=true --namespace istio-system |  kubectl apply -f -
helm template istio install/kubernetes/helm/istio  --namespace istio-system | kubectl apply -f -
kubectl get configmap istio -n istio-system -o yaml | sed 's/mode: ALLOW_ANY/mode: REGISTRY_ONLY/g' | kubectl replace -n istio-system -f -
```

**Environment where bug was observed (cloud vendor, OS, etc)**

Google cloud: v1.13.11-gke.14, on a private cluster with VPC.
