### ISSUE TITLE
Istio 1.3 to Istio 1.4 Upgrade causes RouteConfigurationValidationError's.

### ISSUE THREAD

**Issue by dominicgunn** [istio/istio#19665]
**Bug description**

We currently run Istio v1.3.6 in our clusters, and things are working just fine, however when trying to upgrade to Istio v1.4.2 the Istio Pilot bombs out with the following error message, followed by ~40,000 lines worth of configuration.

```
2019-12-18T13:37:41.020003Z	warn	ads	ADS:RDS: ACK ERROR 172.30.112.5:44284 router~172.30.112.5~my-gateway-76964dfd44-485vr.istio-system~istio-system.svc.cluster.local-18 (my-gateway-76964dfd44-485vr.istio-system) 
    Internal:Proto constraint validation failed (RouteConfigurationValidationError.VirtualHosts[i]: ["embedded message failed validation"] | caused by VirtualHostValidationError.Routes[i]: ["embedded message failed validation"] | caused by RouteValidationError.Match: ["embedded message failed validation"] | caused by field: "path_specifier", reason: is required): name: "http.443"
```

I realize this is likely something on our side, but I'm not quite sure what, my best guess is it's something to do with the Envoy generated configuration shown below, particularly the `1: ""` block, but I'm not sure.

```
    match {
      case_sensitive {
        value: true
      }
      headers {
        name: "the-service"
        exact_match: "my-service"
      }
      10 {
        2: "^/my-url.*"
        1: ""
      }
    }
```

The matching Istio configuration for the VS looks like this, which works just fine in v1.3.6.

```
  - match:
    - headers:
        sms-routing:
          exact: the-service
        sms-servicename:
          exact: my-service
      uri:
        regex: ^/my-url.*
    route:
    - destination:
        host: my-service.default.svc.cluster.local
        subset: default
  - match:
    - headers:
        sms-routing:
          exact: the-service
        sms-servicename:
          exact: my-service
    route:
    - destination:
        host: my-service.default.svc.cluster.local
        subset: default
```

I could be way off on my analysis, but at current, this is my best guess. Could anybody point me in the right direction>

**Expected behavior**

Upgrade to v1.4.2 from v1.3.6 is seamless.

**Steps to reproduce the bug**

We have thousands of routes, and VS's so it could really be anything, but I've posted my best guess above.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ istioctl version --remote
client version: 1.4.2
citadel version: 1.3.6
galley version: 1.3.6
ingressgateway version: 1.3.6
pilot version: 1.3.6
policy version: 1.3.6
sidecar-injector version: 1.3.6
telemetry version: 1.3.6
rw-internal-ingressgateway version:
rw-internal-ingressgateway version:
data plane version: 1.3.6 (144 proxies), 1.2.2 (31 proxies), 1.4.2 (11 proxies)
```

```
$  kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.9", GitCommit:"500f5aba80d71253cc01ac6a8622b8377f4a7ef9", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:04Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

The helm template method.

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS, CoreOS.
