### ISSUE TITLE
istioctl profile diff generate unexpected outputs

### ISSUE THREAD

**Issue by elfinhe** [istio/istio#19692]
I was following this doc:
https://preliminary.istio.io/docs/setup/install/istioctl/#show-differences-in-profiles

But the commands gave me different outputs:
`istioctl profile diff <(istioctl profile dump default) <(istioctl profile dump demo)`
```
 taohe@taohe:~/istio.io/operator$ istioctl profile diff <(istioctl profile dump default) <(istioctl profile dump sds)
Difference of profiles are:
 autoInjection:
   components:
     injector:
       enabled: true
       k8s:
         replicaCount: 1
         strategy:
           rollingUpdate:
             maxSurge: 100%
             maxUnavailable: 25%
   enabled: true
 cni:
...
...
```

`istioctl profile diff default demo`

```
 taohe@taohe:~/istio.io/operator$ istioctl profile diff default demo
Difference of profiles are:
 apiVersion: install.istio.io/v1alpha2
 kind: IstioControlPlane
 spec:
-  autoInjection:
-    components:
-      injector:
-        enabled: true
-        k8s:
-          replicaCount: 1
-          strategy:
-            rollingUpdate:
-              maxSurge: 100%
-              maxUnavailable: 25%
-    enabled: true
-  cni:
-    enabled: false
-  configManagement:
-    components:
-      galley:
-        enabled: true
...
...
```
