### ISSUE TITLE
TLS-terminated gRPC alternative ports receive Status UNIMPLEMENTED but gRPC-Web works

### ISSUE THREAD

**Issue by gertvdijk** [istio/istio#19699]
**Bug description**

I am trying to use Istio 1.4.2 to expose a gRPC service (plaintext) with Istio doing the TLS termination at the edge using a Gateway *on a secondary HTTPS port*. What I find is that:
- gRPC-Web works fine, using TLS enabled HTTP/2.
- gRPC clients using TLS always get status UNIMPLEMENTED.
- plaintext HTTP/1 services are terminated just fine and exposed as TLS enabled HTTP/2.

_On the default primary HTTPS (443) port this works fine. That's the smoking gun._

<details>
<summary>Reasoning</summary>
The reason for me to configure an additional port is that I want to expose the same cluster of services in a multi-home network, e.g.: https/443 via NodePort X serves VirtualServices a and b. https-alt/8443 via NodePort Y serves VirtualServices a, b **and c**. All of that should be possible without the hassle of defining multiple ingress gateways, right? (e.g. (https://medium.com/swlh/public-and-private-istio-ingress-gateways-on-aws-f968783d62fe)
</details>

**Expected behavior**

If gRPC-Web is working on HTTP/2 TLS using a `grpc-web` Service port, then gRPC should be served as well, regardless of the port numbers used.

**Steps to reproduce the bug**

My configuration looks like this:

```
---
kind: Service
apiVersion: v1
metadata:
  namespace: mynamespace
  name: myapp-grpc
  labels:
    app: myapp
    service: myapp-grpc
spec:
  selector:
    app: myapp
  ports:
  - name: grpc-web          ## THIS activates gRPC with gRPC-Web filter IIUC
    port: 10013
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: mynamespace
  name: myapp
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/ingressgateway-mygateway
  http:
  - match:                  ## I've also tried to leave out match+rewrite altogether.
    - uri:
        prefix: /myorg.api.MyAppService/
    rewrite:
      uri: /myorg.api.MyAppService/
    route:
    - destination:
        host: myapp-grpc
        port:
          number: 10013
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  # ... snip some unrelated ...
  labels:
    release: istio
  name: ingressgateway-mygateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - mynamespace/sub.mydomain.tld
    port:
      name: https-secondary
      number: 8443               ### THIS is an alternate port on the istio-ingressgateway Service
      protocol: HTTPS
    tls:
      credentialName: my-credential
      maxProtocolVersion: TLSV1_2
      mode: SIMPLE
---
apiVersion: v1
kind: Service
metadata:
  # ... snip some unrelated ...
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
  clusterIP: 10.99.136.227
  externalTrafficPolicy: Cluster
  ports:
  - name: status-port
    nodePort: 31999
    port: 15020
    protocol: TCP
    targetPort: 15020
  - name: http2
    nodePort: 31002
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 31005
    port: 443
    protocol: TCP
    targetPort: 443
  - name: https-secondary     #### THIS is my additional port that is affected
    nodePort: 31006
    port: 8443
    protocol: TCP
    targetPort: 8443
    # ... snip some other system ports ...
  selector:
    app: istio-ingressgateway
  sessionAffinity: None
  type: LoadBalancer
```

- I've deleted any other Gateway in `istio-system` namespace; it's a completely clean kubeadm-deployed cluster (1.16.4).
- I'm accessing the service on NodePort 31006.
- `myapp` is a Java gRPC server running on port 10013 in plaintext mode.
- URI matching/rewriting is used, but disabling it and making it the only service still reproduces the issue.
- Python, Java and Go clients all receive the same error.
- With logging enabled on the Envoy sidecars I did not notice anything in particular - just looks like HTTP/2 plaintext internally, identical for the gRPC-Web and gRPC traffic.

The following edits to the config make it work as expected (but on the primary HTTPS port):

-  Set the `https-secondary` port number on the Gateway to 443.
- accessing the service on NodePort 31005 as mapped in the Service.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ istioctl --kubeconfig /path/to/my/config version --remote
client version: 1.4.2
control plane version: 1.4.2
data plane version: 1.4.2 (5 proxies)
```

```
$ kubectl --kubeconfig /path/to/my/config version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:37:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

Istio 1.4.2 with:

    istioctl --kubeconfig /path/to/my/config manifest apply \
        --set values.gateways.istio-egressgateway.enabled=false \
        --set values.gateways.istio-ingressgateway.sds.enabled=true

Then:

- removed default gateway Gateway/ingressgateway
- applied Gateway/ingressgateway-mygateway (see above)
- removed default service for this gateway
- applied my own Service/istio-ingressgateway (see above, with additional HTTPS port)
- set pod injection policy to disabled in ConfigMap/istio-sidecar-injector, using per-Deployment `sidecar.istio.io/inject: "true"`, this is working as expected.

I've tried an installation with Istio mutual TLS enabled; no change.

**Environment where bug was observed (cloud vendor, OS, etc)**

Self-installed Ubuntu 18.04 boxes, with plain kubeadm getting started and Calico. One master, 4 worker nodes.

**Comment by diegomarangoni** [comment]
@gertvdijk did you find a solution to this?

**Comment by prabath** [comment]
I too get the same error with Istio 1.6.3, but on the default 443 port, always when the gRPC client outside the Kubernetes cluster, invoking the gRPC service.

Following is the Gateway configuration, which enables TLS, that does not work, and results in the error: 
**WARNING: RPC failed: Status{code=UNIMPLEMENTED, description=Method not found: sample02.Inventory/UpdateInventory, cause=null}**

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ecomm-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      number: 443
      name: grpc
      protocol: https
    tls:
      mode: SIMPLE # enables HTTPS on this port
      credentialName: ecomm-credential
    hosts:
    - "gateway.ecomm.com"
```
Just by disabling the TLS at the Gateway, it works with a non-TLS gRPC client. Following is the TLS disabled Gateway configuration.

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ecomm-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      number: 443
      name: grpc
      protocol: http
    hosts:
    - "gateway.ecomm.com"
```
Appreciate any suggestions to fix this?

**Comment by gertvdijk** [comment]
I haven't found a solution to this, but I noticed there's some hope in merged PRs like https://github.com/istio/istio/pull/24712 (in upcoming 1.7.x).
In the meantime the pain of having to deploy a second Gateway is a lot less by leveraging the new profile options, e.g.:

```
#   $ istioctl manifest generate -f thisfile.yaml

apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
      # A default Ingress gateway, with HTTP & HTTPS on NodePorts 31002 & 31005 respectively.
      - name: istio-ingressgateway
        enabled: true
        k8s:
          service:
            ports:
              - name: status-port
                port: 15021
                targetPort: 15021
              - name: http2
                port: 80
                targetPort: 8080
                nodePort: 31002
              - name: https
                port: 443
                targetPort: 8443
                nodePort: 31005
              - name: tls
                port: 15443
                targetPort: 15443
      # A second Ingress gateway, with HTTPS on NodePort 31006 for internal traffic (Internal only).
      # Reusing the same IngressGateway Deployment and assigning a secondary HTTPS port should work just as well, but
      # fails with gRPC: https://github.com/istio/istio/issues/19699 (should be revalidated if still the case with 1.6.)
      # (We need to have a different port or instance because you can't rely on SNI to restrict internal-only services.)
      # This is a pure work-around and should be dropped in the future, [...]
      - name: istio-ingressgateway-second
        enabled: true
        k8s:
          # much smaller deployment
          hpaSpec:
            minReplicas: 1
            maxReplicas: 2
          strategy:
            rollingUpdate:
              maxSurge: 100%
              maxUnavailable: 50%
          service:
            ports:
              - name: status-port
                port: 15021
                targetPort: 15021
              - name: http2
                port: 80
                targetPort: 8080
              - name: https
                port: 443
                targetPort: 8443
                nodePort: 31006
              - name: tls
                port: 15443
                targetPort: 15443
```
cc @diegomarangoni.

Istio team: How do I "reopen the issue" as per the comment of your bot? The explanation on the istio-policy-bot wiki page does not mention this. I'm discouraged a lot by bots closing tickets. Please don't. Just really. Drives chaos. Stop this auto-closing. Noisy. Annoying.
