### ISSUE TITLE
Auto mTLS does not work with headless service.

### ISSUE THREAD

**Issue by incfly** [istio/istio#19703]
**Bug description**

## Problems

Headless services cluster type is `ORIGIN_DST`, rather than EDS typed cluster. Auto mTLS's `transport_socket_matches`, is matching on endpoint labels, so when auto mTLS transport socket matches are created, `istio: tlsmode-Istio` match can't be applied, and the upstream socket is using plain text always, even if remote side endpoint having sidecar injected.

So if the headless service mTLS policy is STRICT, and auto mTLS is enabled, no destination rule is used for mTLS, traffic fails. Auto mTLS can't deliver the same UX, to have mTLS effect as other EDS based cluster type...

## Reproducing steps

1. create a headless service as below

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-headless
  labels:
    app: httpbin-headless
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8001
    targetPort: 80
  selector:
    app: httpbin-headless
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-headless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin-headless
  template:
    metadata:
      labels:
        app: httpbin-headless
        version: v1
    spec:
      serviceAccountName: httpbin-headless
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80
```

1. Create a Mesholicy with STRICT and enable auto mTLS

1. Sending traffic from sleep to this headless via `curl` starts to fail.

Thanks @hzxuzhonghu for catching this.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
