### ISSUE TITLE
Erratic behaviour with istio mixer objects

### ISSUE THREAD

**Issue by etiennejournet** [istio/istio#19718]
**Bug description**

I'm experiencing problems setting up whitelisting with mixer objects :
1. The bookinfo as described in istio documentation works if you strictly follow it, but if I delete the handlers/rule/instance, error 403 persists for about 2-3 minutes.
2.  I tried to expose a test service : "monitoring/grafana" with IP whitelisting, using gateway "istio-system/ingressgateway" and couldn't find a logical solution for where to put the handlers/rule/instance objects : 
- it seems like it never works (never throw 403) if I create handlers/rule/instance objects in monitoring namespace, creating a gateway in monitoring namespace doesn't change
- it seems to work if objects are in istio-system namespace BUT takes a loooong while ~5 minutes) to switch from 200 to 503 (and back).
- Adding / Deleting handlers/rule/instance works and is faster for default namespace (see bookinfo exemple), even if I use istio-system/gateway instead of bookinfo-gateway

It's unclear whether those objects should be in the same namespace as the gateway, or as the service.

[ X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Should throw 200/503 depending whether I activate the handler/rule/instance or not

**Steps to reproduce the bug**

```
$ cat virtualService.yaml 
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: monitoring
  name: grafana
spec:
  hosts:
  - grafana.dev
  gateways:
  - istio-system/ingressgateway
  http:
  - route:
    - destination:
        host: grafana.monitoring.svc.cluster.local
```

```
---
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: whitelistip
  namespace: monitoring
spec:
  compiledAdapter: listchecker
  params:
    # providerUrl: ordinarily black and white lists are maintained
    # externally and fetched asynchronously using the providerUrl.
    overrides: ["10.57.0.0/16"]
    blacklist: false
    entryType: IP_ADDRESSES
---
apiVersion: config.istio.io/v1alpha2
kind: instance
metadata:
  name: sourceip
  namespace: monitoring
spec:
  compiledTemplate: listentry
  params:
    value: source.ip | ip("0.0.0.0")
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: checkip
  namespace: monitoring
spec:
  match: source.labels["istio"] == "ingressgateway"
  actions:
  - handler: whitelistip
    instances: [ sourceip ]
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

`$ istioctl version --remote
client version: 1.4.1
control plane version: 1.4.1
data plane version: 1.4.1 (9 proxies)`

`$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"1da9875156ba0ad48e7d09a5d00e41489507f592", GitTreeState:"clean", BuildDate:"2019-11-14T05:19:20Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}`

`$ helm version
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}`

**How was Istio installed?**
`kubectl apply -f <$(istioctl manifest generate -f manifest) `
```
---
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  # Old API using helm, should be migrated
  values:
    prometheus:
      enabled: false
    tracing:
      enabled: true
    kiali:
      enabled: true
      dashboard:
        jaegerURL: "http://jaeger-query:16686"
        grafanaURL: "http://grafana.monitoring:3000"
    gateways:
      istio-ingressgateway:
        loadBalancerIP: 1.2.4.5
    pilot:
      policy:
        enabled: true
    global:
      disablePolicyChecks: false
      proxy:
        accessLogFile: "/dev/stdout"
  # New incomplete IstioControlPlane API
  security:
    enabled: true
    components:
      certManager:
        enabled: true
```

**Environment where bug was observed (cloud vendor, OS, etc)**
Azure AKS
