### ISSUE TITLE
setting kiali prometheusAddr parameter does not work with istioctl

### ISSUE THREAD

**Issue by bergur88** [istio/istio#19719]
When using istioctl with helm customization as described [here](https://istio.io/docs/setup/install/istioctl/#customize-istio-settings-using-the-helm-api) and trying to set prometheusAddr parameter described [here](https://istio.io/docs/reference/config/installation-options/#kiali-options) results in the error: 

> input file failed validation with the following errors: unknown field "prometheusAddr" in v1alpha1.KialiConfig

**Expected behavior**
Prometheus url being set in Kiali configMap

**Steps to reproduce the bug**
Create config.yaml file:
````
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  name: istio-config
spec:
  values:
    kiali:
      enabled: true
      prometheusAddr: http://other-prom.monitoring.svc.cluster.local:9090
````

run:
`istioctl manifest generate -f config.yaml
`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by thequailman** [comment]
Seems like the value doesn't exist in the Kiali spec: https://github.com/istio/operator/blob/master/pkg/apis/istio/v1alpha1/values_types.proto#L1885

**Comment by darren-bell-nanthealth** [comment]
Is there a workaround for this until all options are available as passthrough? Can I patch the resulting configmap or anything?

**Comment by christianAckman** [comment]
try this @darren-bell-nanthealth 

```
spec:
  unvalidatedValues:
    kiali:
      prometheusAddr: http://other-prom.monitoring.svc.cluster.local:9090
```

**Comment by pbecotte** [comment]
That does not work.

Looks like the 1.4.3 version of the helm chart is using `http://prometheus.{{ .Values.global.prometheusNamespace }}.svc.cluster.local:9090`

Unfortunately, setting that value still doesn't work, because that triggers the `base` chart to try and create a namespace (which already exists).

Two questions-
1. Is the docs that say "1.4" at the top of the page not actually pulling from a 1.4 version of the code?
2. The tag `1.4.3` doesn't actually have the helm chart that the operator is using. I went back to 1.1 and still don't see it (at least at the path where I found it). Is there a way to see the charts that are packed into those versions that I am missing? I keep hitting bugs, and it is very hard to troubleshoot when you can't find the code.

**Comment by crhuber** [comment]
@pbecotte Did you manage to resolve this. Running into the same problem on 1.4.4.

**Comment by framled** [comment]
Running istio 1.4.6, same problem I want to change the prometheus url to my own prometheus installation

```
{{- if .Values.global.prometheusNamespace }}
        url: http://prometheus.{{ .Values.global.prometheusNamespace }}:9090
{{ else }}
        url: http://prometheus:9090
{{- end }}
```

my workaround was install another service.

**Comment by pbecotte** [comment]
Not directly.

I put this in my IstioControlPlane (and now, IstioOperator)
```
  values:
    prometheus:
      enabled: false
```

And then created a service seperately like

```
kind: Service
apiVersion: v1
metadata:
  name: prometheus
spec:
  type: ExternalName
  externalName: prometheus.monitoring.svc.cluster.local
  ports:
  - port: 9090
```
