### ISSUE TITLE
Control plane components need overlay to run with restrictive PodSecurityPolicy

### ISSUE THREAD

**Issue by michaelbannister** [istio/istio#19720]
**Bug description**
Since #16014 most control plane components run as user 1337 by default, but if the cluster has a PodSecurityPolicy requiring RunAsNonRoot it does not allow the pods to run, as installed via operator. I've had to use the `.k8s.overlays` to set the securityContext.runAsUser to 1337 in order to allow pods to be created.

I'd like to propose the Deployment templates be updated to set `securityContext.runAsUser: 1337` for the control plane's containers.
Happy to submit a PR to this effect if someone can indicate it's likely to be accepted!

**Expected behavior**
Deployment for control plane components which run as 1337 (see #16014) should specify that they run as user 1337.

**Steps to reproduce the bug**
On a GKE cluster with a PodSecurityPolicy including the following rule:
```
  runAsUser:
    rule: 'MustRunAsNonRoot'
```
Ensure the service accounts in the istio-system namespace have a rolebinding to a role/clusterrole allowing it to `use` the PodSecurityPolicy.

Pods including pilot, galley, citadel and telemetry cannot be created because they do not satisfy any PodSecurityPolicy.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4

**How was Istio installed?**
Using istio-operator

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE 1.13.11-gke.14 with PodSecurityPolicy enabled.

**Comment by yangminzhu** [comment]
cc @myidpt and @rlenglet for comments on the changes to psp.

**Comment by rlenglet** [comment]
This is a duplicate of https://github.com/istio/istio/issues/17318.
This issue has been fixed with https://github.com/istio/istio/pull/17427 and https://github.com/istio/installer/pull/628 and those fixes are available in Istio 1.4.3.

**Comment by rlenglet** [comment]
My bad, this is about the control plane containers. It's similar to https://github.com/istio/istio/issues/17318 but that issue was only about injected sidecars.

**Comment by HenriAW** [comment]
I'm also looking to run istio in a non-root environment. 
@michaelbannister are you currently using istioctl with --set to as a workaround? If so I'd be interested to know how you used this to set securityContext.runAsUser to 1337.

**Comment by michaelbannister** [comment]
@HenriAW I was using the new operator and an `IstioControlPlane` custom resource – I haven't used the `istioctl` command line tool directly but I believe it can take the same format as config?

```yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  namespace: istio-operator
  name: istio
spec:
  autoInjection:
    components:
      injector:
        k8s:
          overlays:
          - apiVersion: apps/v1
            kind: Deployment
            name: istio-sidecar-injector
            patches:
            - path: spec.template.spec.securityContext
              value:
                runAsUser: 1337
  configManagement:
    components:
      galley:
        namespace: istio-system
        k8s:
          overlays:
          - apiVersion: apps/v1
            kind: Deployment
            name: istio-galley
            patches:
            - path: spec.template.spec.securityContext
              value:
                runAsUser: 1337
  gateways:
    components:
      ingressGateway:
        enabled: false
  policy:
    components:
      policy:
        k8s:
          overlays:
          - apiVersion: apps/v1
            kind: Deployment
            name: istio-policy
            patches:
            - path: spec.template.spec.securityContext
              value:
                runAsUser: 1337
  security:
    components:
      citadel:
        k8s:
          overlays:
          - apiVersion: apps/v1
            kind: Deployment
            name: istio-citadel
            patches:
            - path: spec.template.spec.securityContext
              value:
                runAsUser: 1337
  telemetry:
    components:
      telemetry:
        k8s:
          overlays:
          - apiVersion: apps/v1
            kind: Deployment
            name: istio-telemetry
            patches:
            - path: spec.template.spec.securityContext
              value:
                runAsUser: 1337
  trafficManagement:
    components:
      pilot:
        k8s:
          overlays:
          - apiVersion: apps/v1
            kind: Deployment
            name: istio-pilot
            patches:
            - path: spec.template.spec.securityContext
              value:
                runAsUser: 1337
```

HTH
