### ISSUE TITLE
doc: help converting nginx ingress w/ cert-manager to argocd server

### ISSUE THREAD

**Issue by shaunc** [istio/istio#19737]
**Describe the feature request**

I am having trouble following guides to convert an nginx ingress to a gateway/virtual service. The ingress is as follows below. If converting this is not simply a documentation issue, then this is an enhancement proposal.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: ${cluster_issuer}
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: ${argocd_domain}
    http:
      paths:
      - backend:
          serviceName: argocd-server
          servicePort: https
        path: /
  tls:
  - hosts:
    - ${argocd_domain}
    secretName: argocd-secret # do not change, this is provided by Argo CD
```
where ${cluster-issuer} corresponds to appropriate the cert-manager ClusterIssuer (letsencrypt staging or production).

**Describe alternatives you've considered**

I have read the guides for pass through and for tls using cert-manager -- don't seem to cover this case. I have tried `istioctl convert-ingress`, resulting in:
```
istioctl convert-ingress -f nginx-gateway.yaml
2019-12-22T00:28:39.312080Z	info	invalid ingress rule argocd:argocd-server-ingress for host "xxx.domain.com", no backend defined for path
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: xxx-domain-com-argocd-server-ingress-istio-autogenerated-k8s-ingress
  namespace: argocd
spec:
  gateways:
  - istio-system/istio-autogenerated-k8s-ingress
  hosts:
  - xxx.domain.com
  http: []
Error: 1 error occurred:
	* output config(s) are invalid: http, tcp or tls must be provided in virtual service
```

[X] Configuration Infrastructure (possibly)
[X] Docs (definitely)
[X] Installation (possibly)
[X] Networking (possibly)
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

Using istio 1.4.2; cert-manager 0.12

NB: cert-manager is setup to use dns01 solver w/ route53 and a service account. After some struggle have got certificate generation (when using nginx ingress) working.

**Comment by howardjohn** [comment]
The error message here is incorrect, but the problem is port name is not supported: https://github.com/istio/istio/blob/997c137d68ef0907eebc51d295d3eff2929d1545/pilot/pkg/config/kube/ingress/conversion.go#L228

It needs to be a port number, like `          servicePort: 443`


if you do that you will get output:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: foo-argocd-server-ingress-istio-autogenerated-k8s-ingress
  namespace: argocd
spec:
  gateways:
  - istio-system/istio-autogenerated-k8s-ingress
  hosts:
  - foo
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: argocd-server.argocd.svc.cluster.local
        port:
          number: 443
      weight: 100
```
