### ISSUE TITLE
Make use of Envoy's %REQ(header-name)% feature when setting response headers

### ISSUE THREAD

**Issue by nicktrav** [istio/istio#19761]
**Describe the feature request**

In a similar request to the original upstream feature request from envoyproxy/envoy#8683, we'd like to be able to set response headers to values that were present in the request headers. Our initial use-case for this is for echoing tracing headers to an external client, for debugging purposes.

Can we backport the patch from envoyproxy/envoy#8782 into `istio/envoy`?

Without this, Pilot receives the following ACK errors from the Envoys that we have making up some of our ingress gateways:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
...
spec:
...
  http:
  - route:
    - destination:
        host: istio-ping.istio-ping.svc.cluster.local
        port:
          number: 80
    headers:
      response:
        set:
          x-b3-traceid: "%REQ(x-b3-traceid)%"
          x-request-id: "%REQ(x-request-id)%"
```

```
2019-12-23T18:24:35.935645Z     warn    ads     ADS:RDS: ACK ERROR 127.0.0.1:38530 router~10.20.9.65~istio-ingressgateway-6464bf6f96-qrnkx.external-gateway~external-gateway.svc.-183784 (istio-ingressgatewa
y-6464bf6f96-qrnkx.external-gateway) Internal:field 'REQ(x-b3-traceid)' not supported as custom header
```

Happy to open a PR to cherry-pink this in, but wasn't sure what the process looked like, given `istio/envoy` is a fork.

**Describe alternatives you've considered**

Using Lua filters via `EnvoyFilter`. Though it doesn't seem like the tracing headers have been set by the time the filter runs.
