### ISSUE TITLE
Not clear why certain requests with mTLS fail with 503

### ISSUE THREAD

**Issue by nerusnayleinad** [istio/istio#19777]
Probably this is not a bug, but I am not getting why is this happening.

So, according to the documentation, when you enable mTLS, it enables it only for server side, and you need to create a `DestinationRule` for the client side; otherwise you get 503.

That's exactly what happens until I create this DR, and it returns 200:

```
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "default"
  namespace: "istio-system"
spec:
  host: "*.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```

Now, when I set the destination rule in the `namespace` `foo` or `bar`, this is the result:

```
~# for from in "foo" "bar"; do for to in "foo" "bar"; do kubectl exec $(kubectl get pod -l app=sleep -n ${from} -o jsonpath={.items..metadata.name}) -c sleep -n ${from} -- curl "http://httpbin.${to}:8000/ip" -s -o /dev/null -w "sleep.${from} to httpbin.${to}: %{http_code}\n"; done; done
sleep.foo to httpbin.foo: 503
sleep.foo to httpbin.bar: 503
sleep.bar to httpbin.foo: 200
sleep.bar to httpbin.bar: 503
```

So, only 1 of the requests goes through. in this case, the DR was in the `namespace: bar`.

> Starting with Istio 1.1, only destination rules in the client namespace, server namespace and global namespace (default is istio-system) will be considered for a service, in that order.

Question: Shouldn't `bar` to `bar` succeed as well? Why is it failing.

If I switch it to `foo`, the second request (`foo` to `bar`) succeeds, and the rest fail with 503. And if I create the DR in both namespaces, all requests fail.

I believe it somehow overwrites the certs? Could you explain this behavior please?
