### ISSUE TITLE
404 response when accessing https (http are works fine) with Gateway + VirtualService configured

### ISSUE THREAD

**Issue by wickedev** [istio/istio#19787]
**Bug description**

As mentioned in the title, 404 response when accessing https (http are works fine) with Gateway + VirtualService configured

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

200 responds when you run a command `curl --insecure -v https://amki.app/hello`

**Steps to reproduce the bug**

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: amki-gateway
  namespace: amki-app
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
    - hosts:
        - "amki.app"
      port:
        number: 80
        name: http
        protocol: HTTP
    - hosts:
        - "amki.app"
      port:
        number: 443
        name: https-default
        protocol: HTTPS
      tls:
        credentialName: ingress-cert
        mode: SIMPLE
        privateKey: sds
        serverCertificate: sds
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: amki-app-vs
  namespace: amki-app
spec:
  hosts:
    - "amki.app"
  gateways:
    - amki-gateway
  http:
    - match:
        - uri:
          exact: /
      route:
        - destination:
            host: helloworld.amki-app.svc.cluster.local
            port:
              number: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: amki-app
  labels:
    app: helloworld
spec:
  ports:
    - port: 5000
      name: http
  selector:
    app: helloworld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: amki-app
spec:
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: istio/examples-helloworld-v1
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
```
Above is the yaml file I applied. then run the command `curl --insecure -v http://amki.app/hello` and it will respond as shown below.

```sh
$ curl --insecure -v http://amki.app/hello
*   Trying 220.74.47.111...
* TCP_NODELAY set
* Connected to amki.app (220.74.47.111) port 80 (#0)
> GET /hello HTTP/1.1
> Host: amki.app
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 200 OK
< content-type: text/html; charset=utf-8
< content-length: 57
< server: istio-envoy
< date: Wed, 25 Dec 2019 09:51:45 GMT
< x-envoy-upstream-service-time: 124
<
Hello version: v1, instance: helloworld-6b489b9859-mfwhj
* Connection #0 to host amki.app left intact
```

However, the command `curl --insecure -v https://amki.app/hello` will respond with a 404 like this:

```sh
$ curl --insecure -v https://amki.app/hello
*   Trying 220.74.47.111...
* TCP_NODELAY set
* Connected to amki.app (220.74.47.111) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Unknown (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Client hello (1):
* TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=amki.app
*  start date: Dec 25 07:54:38 2019 GMT
*  expire date: Mar 24 07:54:38 2020 GMT
*  issuer: CN=Fake LE Intermediate X1
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* Using Stream ID: 1 (easy handle 0x557c8640a580)
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
> GET /hello HTTP/2
> Host: amki.app
> User-Agent: curl/7.58.0
> Accept: */*
>
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
< HTTP/2 404
< location: https://amki.app/hello
< date: Wed, 25 Dec 2019 09:53:59 GMT
< server: istio-envoy
<
* Connection #0 to host amki.app left intact
```

```sh
$ kubectl describe secret ingress-cert -n amki-app
Name:         ingress-cert
Namespace:    amki-app
Labels:       <none>
Annotations:  cert-manager.io/alt-names: amki.app
              cert-manager.io/certificate-name: ingress-cert
              cert-manager.io/common-name: amki.app
              cert-manager.io/ip-sans:
              cert-manager.io/issuer-kind: ClusterIssuer
              cert-manager.io/issuer-name: letsencrypt-staging
              cert-manager.io/uri-sans:

Type:  kubernetes.io/tls

Data
====
ca.crt:   0 bytes
tls.crt:  3529 bytes
tls.key:  1675 bytes
```

```sh
$ kubectl describe certificate ingress-cert -n amki-app
Name:         ingress-cert
Namespace:    amki-app
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"cert-manager.io/v1alpha2","kind":"Certificate","metadata":{"annotations":{},"name":"ingress-cert","namespace":"amki-app"},"...
API Version:  cert-manager.io/v1alpha2
Kind:         Certificate
Metadata:
  Creation Timestamp:  2019-12-25T09:29:12Z
  Generation:          1
  Resource Version:    9363
  Self Link:           /apis/cert-manager.io/v1alpha2/namespaces/amki-app/certificates/ingress-cert
  UID:                 7854b0c8-61d8-46fa-b97e-0e0f26641557
Spec:
  Dns Names:
    amki.app
  Issuer Ref:
    Group:      cert-manager.io
    Kind:       ClusterIssuer
    Name:       letsencrypt-staging
  Secret Name:  ingress-cert
Status:
  Conditions:
    Last Transition Time:  2019-12-25T09:29:14Z
    Message:               Certificate is up to date and has not expired
    Reason:                Ready
    Status:                True
    Type:                  Ready
  Not After:               2020-03-24T08:29:13Z
Events:
  Type    Reason        Age   From          Message
  ----    ------        ----  ----          -------
  Normal  GeneratedKey  29m   cert-manager  Generated a new private key
  Normal  Requested     29m   cert-manager  Created new CertificateRequest resource "ingress-cert-1824166152"
  Normal  Issued        29m   cert-manager  Certificate issued successfully
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```sh
$ istioctl version --remote
client version: 1.4.1
control plane version: 1.4.1
data plane version: 1.4.1 (1 proxies)
```

**How was Istio installed?**
```sh
$ istioctl manifest apply \
        --set values.global.proxy.accessLogFile="/dev/stdout" \
	--set values.kiali.enabled=true \
	--set values.prometheus.enabled=true \
	--set values.grafana.enabled=true \
	--set values.tracing.enabled=true \
	--set values.tracing.provider=jaeger \
	--set values.tracing.ingress.enabled=true \
	--set values.gateways.istio-ingressgateway.sds.enabled=true \
	--set values.global.k8sIngress.enabled=true \
	--set values.global.k8sIngress.enableHttps=true \
	--set values.global.k8sIngress.gatewayName=ingressgateway
```

**Environment where bug was observed (cloud vendor, OS, etc)**

```sh
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

```sh
# I installed k3s on my local machine using the command below.
$ EXTERNAL_IP=$(dig +short myip.opendns.com @resolver1.opendns.com)
$ curl -sfL https://get.k3s.io | sh -s - \
	--no-deploy=traefik \
	--write-kubeconfig-mode=644 \
	--tls-san=${EXTERNAL_IP}
```

[istio-dump.tar.gz](https://github.com/istio/istio/files/4000214/istio-dump.tar.gz)
