### ISSUE TITLE
How can instance configure the collection access log to customize the fetch cookie field

### ISSUE THREAD

**Issue by Hwting** [istio/istio#19785]
**Describe the feature request**
```yaml
apiVersion: config.istio.io/v1alpha2
kind: instance
metadata:
  name: testaccesslog
  namespace: istio-system
spec:
  compiledTemplate: logentry
  params:
    monitored_resource_type: '"UNSPECIFIED"'
    severity: '"info"'
    timestamp: request.time
    variables:
      method: request.method | ""
      protocol: request.scheme | context.protocol | ""
      requestSize: request.size | 0
      responseCode: response.code | 0
      url: request.path | ""
      userAgent: request.useragent | ""
      uuid: request.headers["cookie"]| "-"
      wxuuid: request.headers["wxuuid"] | "-"
```
curl  -b 'foo=bar' -v  http://example.com/api/info
The result of getting the uuid is "uuid": "foo=bar"
How to instance so that the expected result is "uuid": "bar"

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
