### ISSUE TITLE
Ingress Gateway without TLS Termination But VirtualService Version Control does not work

### ISSUE THREAD

**Issue by fujianan** [istio/istio#19794]
I have read this page(https://istio.io/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/)
There is a nginx application in my environment  and all proxy through nginx
I created virtualsevice and appoint the version:v1  
![image](https://user-images.githubusercontent.com/22000011/71473122-bafdbb80-2810-11ea-80fb-7b455c6ea3bb.png)
there are my yaml files:

nginx-gateway.yaml
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  annotations:
  name: tengine-gateway
  namespace: triones
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "*"
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - "*"
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
```

one-dr.yaml
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: one-ds
spec:
  host: one.triones.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
```

one-vs.yaml
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: one-route
spec:
  hosts:
  - one.triones.svc.cluster.local
  http:
  - route:
    - destination:
        host: one.triones.svc.cluster.local
        subset: v1
```
What should I do?
