### ISSUE TITLE
Locality Load Balancing is not working for multi-cluster mesh

### ISSUE THREAD

**Issue by zhongfox** [istio/istio#19793]
**Bug description**
I setup a multi-clusers mesh, the 2 clusters are in different regions. 
follow: https://archive.istio.io/v1.3/docs/setup/install/multicluster/shared-gateways/ 
I want test 「Locality Load Balancing」 in this mesh.

![image](https://user-images.githubusercontent.com/463772/71470434-10cd6600-2807-11ea-82e6-cc646391c753.png)

why 「distributed between instances on cluster1 and cluster2 」?

[ x]Networking

**Expected behavior**

if  「Locality Load Balancing」 is working ,  pod sleep in cluster1 should always access helloworld-v1, because helloworld-v1 is in cluster1
pod sleep in cluster2 should always access helloworld-v2
is there something Im missing? how can I make 「Locality Load Balancing」 working?

this is the eds info from pilot debug port:
![image](https://user-images.githubusercontent.com/463772/71470600-a5d05f00-2807-11ea-8055-b226cb9bd524.png)

the configmap istio in primary cluster:
```
localityLbSetting:
  enabled: true
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
k8s: 1.14
istio: 1.3.6

**How was Istio installed?**
https://archive.istio.io/v1.3/docs/setup/install/multicluster/shared-gateways/

**Comment by howardjohn** [comment]
you need to configure outlier detection

https://preliminary.istio.io/docs/ops/configuration/traffic-management/locality-load-balancing/#requirements

**Comment by zhongfox** [comment]
hi @howardjohn 
then I add this dr:
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: helloworld
  namespace: sample
spec:
  host: helloworld.sample.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    outlierDetection:
      consecutiveErrors: 3
      interval: 30s
      baseEjectionTime: 3m
```

after this,  the cluster1 seems ok, sleep in cluster1 will always access helloworld v1, which is in cluster1
but, sleep in cluster2 still can access helloworld v1 and helloworld v2

```
% kubectl exec --context=$CTX_CLUSTER2 -it -n sample -c sleep $(kubectl get pod --context=$CTX_CLUSTER2 -n sample -l app=sleep -o jsonpath='{.items[0].metadata.name}') -- curl helloworld.sample:5000/hello
Hello version: v1, instance: helloworld-v1-7bb88866c4-6bfp5
% kubectl exec --context=$CTX_CLUSTER2 -it -n sample -c sleep $(kubectl get pod --context=$CTX_CLUSTER2 -n sample -l app=sleep -o jsonpath='{.items[0].metadata.name}') -- curl helloworld.sample:5000/hello
Hello version: v2, instance: helloworld-v2-6cd449dff4-qvwq6
```
