### ISSUE TITLE
mesh profile dump not generating ICPS CR format output

### ISSUE THREAD

**Issue by elfinhe** [istio/istio#19804]
We should consider generating a ICPS which can be piped into `kubectl apply` cmd. `profile diff` should also get updated to support ICPS as input.

Current output of `mesh profile dump `
```
base:
  components:
    base:
      enabled: true
  enabled: true
...
```

Expected output
```yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  base:
    enabled: true
    components:
      base:
```
