### ISSUE TITLE
TCP route based on matched port doesn't seem to be working.

### ISSUE THREAD

**Issue by nerusnayleinad** [istio/istio#19887]
I am testing the following example from your website:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: server-vs
spec:
  hosts:
  - server.istio.svc.cluster.local
  tcp:
  - match:
    - port: 12345
    route:
    - destination:
        host: nginx.istio.svc.cluster.local
        port:
          number: 80
```
And this is the explanation:

> Describes match conditions and actions for routing TCP traffic. The following routing rule forwards traffic arriving at port 27017 for mongo.prod.svc.cluster.local to another Mongo server on port 5555.

What I have change are the service names and ports. But have not added or removed anything. Instead of `mongo.prod` it's `server.istio`, which based on the port match, would send the traffic to `nginx.istio` service.

Note: `server.istio` is a service pointing to `nginx` and `apache` backeds, while `nginx.istio` only points to `nginx` backends.

So, if I'd curl `server` on port 12345, I should always get nginx serving this requests. But if I do that, Envoy times out:

```
/ # curl server:12345
curl: (56) Recv failure: Connection reset by peer
```
Then I thought may be it should be on the port that `server.istio` is actually expecting to get requests, so I changed `server` service port to 12345. But now I just get 50% serving `nginx` and 50% `apache`.

Is this feature actually working? Seems to be pretty simple and it is not working. Am I doing something wrong?

I am using Istio 1.4.2 and k8s 1.16.4.
