### ISSUE TITLE
Error access with protocol HTTP2

### ISSUE THREAD

**Issue by yanolol** [istio/istio#19886]
**Bug description**
When we try access with protocol HTTP2 return thios error:
upstream connect error or disconnect/reset before headers. reset reason: connection termination

**Expected behavior**

**Steps to reproduce the bug**
After create gateway, virtualservice and destinationrule
https://raw.githubusercontent.com/yanolol/logs/master/PCOoMqqQlTibl5VF43RroiccrION8Qi9.yaml

We tried access with curl with protocol HTTP 1.1 works
Logs istio-ingressgateway: 
[2020-01-02T16:17:33.193Z] "GET /appstorefront/_ui/desktop/common/images/flag.png HTTP/1.1" 200 - "-" "-" 4 759 3 3 "10.233.98.0" "PostmanRuntime/7.21.0" "9600c2b7-ee85-9105-a6d8-8998992a2fc0" "dev.app.com" "10.233.92.211:8088" outbound|8088||http2-dev-app-storefront.dev-app.svc.cluster.local - 10.233.91.225:443 10.233.98.0:65438 dev.app.com -

But when we tried access with protocol HTTP2 like a browser return 503 and "upstream connect..."
Logs istio-ingressgateway: 
[2020-01-02T16:18:18.260Z] "GET /appstorefront/_ui/desktop/common/images/flag.png HTTP/2" 503 UC "-" "-" 0 95 16 - "10.233.98.0" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36" "ca03e427-214b-9b26-9c0a-6c5777dcd7b1" "dev.app.com" "10.233.92.211:8088" outbound|8088||http2-dev-app-storefront.dev-app.svc.cluster.local - 10.233.91.225:443 10.233.98.0:49180 dev.app.com -

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Istio 1.4.2
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
Helm/tiller

**Environment where bug was observed (cloud vendor, OS, etc)**
Calico
RHEL 7.6

**Comment by howardjohn** [comment]
I think you may need to make the protocol HTTP2: https://istio.io/docs/reference/config/networking/gateway/#Port

**Comment by yanolol** [comment]
> I think you may need to make the protocol HTTP2: https://istio.io/docs/reference/config/networking/gateway/#Port

My aplication runner only that protocol HTTP 1.1, in gateway is set with HTTPS, i tried to change like this, but doesn't work

``` yaml
  servers:
    - hosts:
        - dev.app.com
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - dev.app.com
      port:
        name: http-test
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        privateKey: /etc/istio/ingressgateway-certs/tls.key
        serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
```
Is there any way to block HTTP2?

**Comment by yanolol** [comment]
Guys, i resolve this problem addind https-grpc-service in my service.

**Comment by patrickppeng** [comment]
Hi yanolol,
I'm experiencing the same issue with Istio 1.4.2. Can you provide more details how you added the https-grpc-service to make it work?

thanks,

**Comment by patrickppeng** [comment]
@howardjohn do you know anything changed on HTTP2 in proxy 1.4.x? or any new configuration required? It worked on the same upstream service with Istio 1.3.1.

**Comment by yanolol** [comment]
Hello @patrickppeng 
I addind https-grpc in the service name port 

``` yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    heritage: Tiller
  name: my-aplication
  namespace: default
spec:
  clusterIP: 10.222.44.241
  ports:
  - name: https-grpc-app
    port: 8088
    protocol: TCP
    targetPort: 8088
```

I am still trying to understand why this issue occurs, but I believe it is something related to TLS because of its authentication.
