### ISSUE TITLE
gRPC connection is closed right after a request is done

### ISSUE THREAD

**Issue by xiaozhongliu** [istio/istio#19883]
**Bug description**
gRPC connection is closed right after a request is done.
Below is the response got on client side:
![image](https://user-images.githubusercontent.com/17674404/71664225-315f6800-2d93-11ea-9b73-e12276c26978.png)
Below is the request log from istio gateway:
```json
{
"requested_server_name": "-",
"bytes_received": "12",
"istio_policy_status": "-",
"bytes_sent": "18",
"upstream_cluster": "outbound|80||k8s-demo-grpc.stage-c1.svc.cluster.local",
"downstream_remote_address": "172.22.1.39:37632",
"authority": "k8s-demo-grpc.internal.unicareer.com:80",
"path": "/greeter.Greeter/sayHello",
"protocol": "HTTP/1.1",
"upstream_service_time": "0",
"upstream_local_address": "-",
"duration": "1",
"downstream_local_address": "172.22.1.153:80",
"upstream_transport_failure_reason": "-",
"response_code": "200",
"user_agent": "grpc-node/1.24.2 grpc-c/8.0.0 (linux; chttp2; ganges)",
"response_flags": "-",
"start_time": "2020-01-02T10:55:56.172Z",
"method": "POST",
"request_id": "b327ccac-5643-4d20-9d44-ca07dfede9cd",
"upstream_host": "172.22.1.117:50051",
"x_forwarded_for": "172.22.1.39"
}
```

**Expected behavior**
The client can get data normally and connection keeps open.

**Steps to reproduce the bug**
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway-isolated
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - k8s-demo-grpc.internal.sample.com
      port:
        number: 80
        name: grpc
        protocol: GRPC

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: k8s-demo-grpc-isolated
  namespace: stage-c1
spec:
  hosts:
    - k8s-demo-grpc.internal.sample.com
  gateways:
    - default/gateway-isolated
  http:
    - route:
        - destination:
            host: k8s-demo-grpc
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
~ istioctl version --remote
client version: 1.2.7
grafana version:
citadel version: 1.2.7
galley version: 1.2.7
ingressgateway version: 1.2.7
ingressgateway version: 1.2.7
pilot version: 1.2.7
pilot version: 1.2.7
pilot version: 1.2.7
pilot version: 1.2.7
pilot-gateway version:
policy version: 1.2.7
policy-gateway version:
sidecar-injector version: 1.2.7
telemetry version: 1.2.7
telemetry version: 1.2.7
telemetry version: 1.2.7
telemetry-gateway version:
kiali version:
prometheus version:
```
```
~ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:19Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-aliyun.1", GitCommit:"8cb561c", GitTreeState:"", BuildDate:"2019-05-23T11:28:17Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Aliyun ACK, Operator

**Environment where bug was observed (cloud vendor, OS, etc)**
Aliyun ACK, CentOS 7
