### ISSUE TITLE
How does `istio-ingressgateway` behave as edge proxy without proxy and can I create another pod and make it to be ingress gateway as well?

### ISSUE THREAD

**Issue by nerusnayleinad** [istio/istio#19904]
I am going through another issue blindfolded. I want to understand the role of `ingress gateway`. In your 1000s of examples, you are using the `gateway` object as follows:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "httpbin.example.com"
```

From the docs, I quote:

> Gateway describes a load balancer operating at the edge of the mesh receiving incoming or outgoing HTTP/TCP connections.

And then, another example where the selector of the `gateway` object is `app: my-gateway-controller`, it says:

> The gateway will be applied to the proxy running on a pod with labels app: my-gateway-controller.

Now, `istio-ingressgateway` has just one container, so I assume there is no Envoy running inside it, but according to the docs, a `gateway` object will be applied to the proxy in the pod that has the label. So, what happens here?

**Second part of the question**

I said OK , let's create a pod with some labels, then let's create a gateway object setting as selector, the labels of that pod, and it should behave as ingress-gateway. And I did:

Let's assume I have an nginx pod with labels `run: nginxgateway` and a service pointing to it, that gets the requests on port 12345 and forward them to 80.

The `gateway` object:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: port-match
spec:
  selector:
    run: nginxgateway
  servers:
  - hosts:
    - '*'
    port:
      name: tcp
      number: 12345
      protocol: TCP
```

The `virtualservice` object:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: server-vs
spec:
  gateways:
  - port-match
  hosts:
  - '*'
  tcp:
  - match:
    - port: 12345
    route:
    - destination:
        host: apache.istio.svc.cluster.local
        port:
          number: 80
```

And finally I have an apache server and a service pointing to it that gets requests on port 80 and forwards them to port 80 as well.

With this config I should talk to nginx service on port 12345, the `VirtualService` should intercept this call, and send the request to apache service. But it doesn't happen. Nginx responds the request.

So what happens with this `ingress gateway` object? Why `istio-ingressgateway` without a sidecar is being configured as edge proxy, and everything works, but when I try to set up my own `ingress gateway` it fails?

Are there any constraints of how has to be the pod with ingress gateway? I mean, is it a special pod, like ingress controllers or other CRDs? Is `istio-ingressgateway` the only pod that I can link a `gateway` object without having to write my own controller?
