### ISSUE TITLE
Multi-cluster setup: missing envoy filter, destination rule in target cluster results in double (nested) mTLS

### ISSUE THREAD

**Issue by devkid** [istio/istio#19901]
**Bug description**

I have set up istio on two different Kubernetes cluster (replicated control plane with shared root CA). I'm trying to set up cross-cluster failover now and followed the documentation [here](https://istio.io/docs/setup/install/multicluster/gateways/). However, I started out with the bookinfo application, not with httpbin and sleep, in the `istio-test` namespace.

**Bug 1:** The documentation doesn't mention that you need to install istio with `--set global.multiCluster.enabled=true`. If you don't do that, the helm chart will not install the SNI gateway on port 15443 nor the destination rule that enables mTLS for `*.global`.

After enabling multi-cluster option in both clusters, I created the following `ServiceEntry` in the first cluster to access the `details` service in the second cluster.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: details-global
spec:
  hosts:
  - details.istio-test.global
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 9080
    protocol: http
  resolution: DNS
  addresses:
  - 240.0.0.2
  endpoints:
  - address: ingressgateway.second-cluster.com
    ports:
      http: 15443
```

After that, I exec'ed into the productpage pod in the first cluster and tried with curl to access `http://details.istio-test.global:9080`. This returned HTTP 503 and I turned on trace logging in the envoy proxy of the ingress gateway at `ingressgateway.second-cluster.com`. I saw that it got the request, saw the SNI field as `outbound_.9080_._.details.istio-test.global` and transformed it to `outbound_.9080_._.details.istio-test.svc.cluster.local` due to the envoy filter defined in the helm chart [here](https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/gateways/templates/preconfigured.yaml#L208-L218). However, the request was just aborted afterwards because it was looking for a cluster called `outbound_.9080_._.details.istio-test.svc.cluster.local` in the envoy configuration. Instead, the cluster is called `outbound|9080||details.istio-test.svc.cluster.local`. I assumed this is a missing envoy filter and added the following filter:
```yaml
  - listenerMatch:
      portNumber: 15443
      listenerType: GATEWAY
    insertPosition:
      index: AFTER
      relativeTo: envoy.filters.network.sni_cluster
    filterName: envoy.filters.network.tcp_cluster_rewrite
    filterType: NETWORK
    filterConfig:
      cluster_pattern: "_\\."
      cluster_replacement: "|"
```
Afterwards, the SNI field got rewritten to `outbound|9080||details.istio-test.svc.cluster.local` and envoy found the correct cluster and started initiating a request to the correct backend pod. I'm not sure if this **Bug 2** or if I missed something here and this additional filter shouldn't be necessary.

At this point, the request still returned 503. I also switched on trace logging in the envoy proxy of the target pod and found the following error:
```
[Envoy (Epoch 0)] [2020-01-03 09:24:05.120][31][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:274] [C87] dispatch error: http/1.1 protocol error: HPE_INVALID_METHOD
```

This looks to me like the ingress gateway initiated an mTLS connection to the target pod (because of a destination rule that is in place in the second cluster that enables mTLS for the target because it's supposed to be used internally as well) but then just forwarded the mTLS stream it got from the client from the first cluster verbatim _inside_ its own mTLS connection, leading to a double / nested mTLS stream, leading to the envoy proxy in the target pod trying to recognize the inner mTLS as HTTP. That would be **Bug 3**. When I disabled mTLS in the destination rule in the second cluster, the request from the first cluster finally went through, but then the communication with the `details` service was broken in the second cluster because the service expected mTLS and clients didn't do mTLS. Here I'm also not sure if this is really a bug or if I'm missing yet another configuration that would make the ingress gateway _not_ initiate mTLS itself when it recognizes that the client already sent mTLS.

Regarding Bug 3, I found the following issue that seems to be related but doesn't use a cross-cluster setup: https://github.com/istio/istio/issues/13422 But the SNI gateway on port 15443 that comes with the helm chart already has its mode set to `AUTO_PASSTHROUGH`.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-16T16:29:58Z", GoVersion:"go1.12.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.9", GitCommit:"e09f5c40b55c91f681a46ee17f9bc447eeacee57", GitTreeState:"clean", BuildDate:"2019-05-27T15:58:45Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

$ helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

$ istioctl version --remote
client version: 1.4.0
control plane version: 1.4.0
data plane version: 1.4.0 (7 proxies)
```

**How was Istio installed?**
Using helm.

**Environment where bug was observed (cloud vendor, OS, etc)**
First cluster is EKS, second cluster is diamanti.
