### ISSUE TITLE
CNI setup fails with istioctl

### ISSUE THREAD

**Issue by cagataygurturk** [istio/istio#19923]
**Bug description**

The same issue described [here](https://github.com/istio/istio/issues/14977) exists with istioctl installation. IstioControlPlane  installs  istio-cni-node to istio-system which causes the following error:

````
Error creating: pods "istio-cni-node-" is forbidden: pods with system-cluster-critical priorityClass is not permitted in istio-system namespace
````

[ ] Configuration Infrastructure
[ ] Docs
[x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
I think https://github.com/istio/installer/pull/626 fixes this

**Comment by cagataygurturk** [comment]
The linked Pr seems to be a documentation change only. How will it fix the problem with istioctl @howardjohn ?

**Comment by howardjohn** [comment]
oh I think the pr changed since I last looked at it

**Comment by howardjohn** [comment]
In the short term you can manually set it with `--set cni.enabled=true --set cni.components.cni.namespace=kube-system`

**Comment by cagataygurturk** [comment]
@howardjohn @clyang82 

As of 1.5.1 `cni.components.cni.namespace` does not work and I can't find any other value to set the namespace. The changes from istio/operator#732 are removed in a later commit as far as I understand. How can I set the namespace?

**Comment by BrandonSharp** [comment]
@cagataygurturk Ran into a similar issue just now. If you haven't solved it yet, using `--set cni.namespace=kube-system` seems to work for me.  HTH!

**Comment by Cajga** [comment]
Same issue here (with AWS EKS) and `--set components.cni.namespace=kube-system` solves the problem. This should be documented on the istio CNI installation site.

**Comment by mickstevenson** [comment]
> @howardjohn @clyang82
> 
> In 1.5.1 and later `cni.components.cni.namespace` does not work and I can't find any other value to set the namespace. The changes from [istio/operator#732](https://github.com/istio/operator/pull/732) are removed in a later commit as far as I understand. How can I set the namespace?
> 
> ```
> apiVersion: install.istio.io/v1alpha1
> kind: IstioOperator
> metadata:
>   namespace: istio-system
> spec:
>   profile: demo
>   components:
>     cni:
>       enabled: true
>       components:
>         cni:
>           namespace: kube-system
> ```
> 
> gets
> 
> `Error: failed to apply manifests: failed to generate manifest: unknown field "components" in v1alpha1.ComponentSpec:`

@howardjohn 

The yaml from your example should be the following. Hope this helps.

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  profile: demo
  components:
    cni:
      enabled: true
      namespace: kube-system
```

**Comment by mickstevenson** [comment]
The following works for Azure AKS.

Hope this helps someone.

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrol-plane
spec:
  components:
    cni:
      enabled: true
      namespace: kube-system
  values:
    cni:
      excludeNamespaces:
       - istio-system
       - kube-system
      logLevel: info
```
