### ISSUE TITLE
Empty subject in x-forwarded-client-cert

### ISSUE THREAD

**Issue by kalyank23** [istio/istio#19933]
I am trying to get my client certificate common name in headers of my service, but unfortunately I am getting empty string for subject.

`X-Forwarded-Client-Cert: By=spiffe://cluster.local/ns/default/sa/default;Hash=afb15b2fa11e07b572fb8cc549a07a71b169bdd818199ab1c2ad90f6f05fb2aa;Subject="";URI=spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account`

Could you please let me know what I am doing wrong.

Also I am not using any load balancer to my application, so do i need to use external load balancer to get the subject in above header field? or is it because I am calling gateway and gateway is using service account to call my helloworld service and helloworld service is displaying service account details instead of client certificate details?

**Comment by kalyank23** [comment]
I am using istio 1.2 version. Do I need to use EnvoyFilter to get the certificate subject?

**Comment by kalyank23** [comment]
Gateway yaml file:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mygateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    - helloworld.example.com
```

And virtual service:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helloworld-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - mygateway
  http:
  - match:
    - uri:
        exact: /flask1
    route:
    - destination:
        port:
          number: 5000
        host: helloworld-service
  tls:
  - match:
    - port: 443
      sni_hosts:
      - "*"
    route:
    - destination:
        port:
          number: 5000
        host: helloworld-service
```

Mesh policy:

```
apiVersion: "authentication.istio.io/v1alpha1"
kind: "MeshPolicy"
metadata:
  name: "default"
spec:
  peers:
  - mtls: {}
```

Destination rule:

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: helloworld-dr
  namespace: default
spec:
  host: helloworld-service
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```

I tried with both Secure Gateways (SDS) and Secure Gateways (File Mount), but no luck.
