### ISSUE TITLE
Pilot stops pushing routes when tcp:443/https:443 service entries are created

### ISSUE THREAD

**Issue by edude03** [istio/istio#19935]
**Bug description**
If you create two wildcard ServiceEntries for port 443 with https/tcps protocol likes so

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
spec:
  hosts:
  - '*.site-a.com'
  ports:
  - name: https
    number: 443
    protocol: HTTPS
```

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
spec:
  hosts:
  - '*.site-b.com'
  ports:
  - name: tcp
    number: 443
    protocol: TCP
```
Internal:Error adding/updating listener(s) 0.0.0.0_443: error adding listener '0.0.0.0:443': multiple filter chains with the same matching rules are defined
```
and the LDS status to be stale for all proxies



**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

Istio 1.4.1

**How was Istio installed?**

Helm template

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE Kubernetes 1.14
