### ISSUE TITLE
The corresponding Endpoint remains after the ServiceEntry resource is deleted

### ISSUE THREAD

**Issue by yangdihangN** [istio/istio#19964]
**Bug description**
 The corresponding Endpoint remains after the ServiceEntry resource is deleted

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
There is no  corresponding Endpoint in envoy memory， when ServiceEntry has been deleted.

**Steps to reproduce the bug**
1. create Service
```
apiVersion: v1
kind: Service
metadata:
  name: a
  namespace: powerful-gray
  labels:
    app: a
spec:
  ports:
  - name: http-a
    nodePort: 31938
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
status:
  loadBalancer: {}
```

2. create ServiceEntry, specially the host is same with K8S svc
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: qz-backup-a
  namespace:  powerful-gray
spec:
  endpoints:
  - address: 7.7.7.7
  hosts:
  # same with K8S svc,
  - a.powerful-gray.svc.cluster.local
  ports:
  - name: http
    number: 80
    protocol: http
  resolution: STATIC
```
3. use istioctl to dump endpoint
```
istioctl pc ep {pod} | grep a.powerful-gray
172.31.52.7:8080        HEALTHY     OK                outbound|80||a.powerful-gray.svc.cluster.local
7.7.7.7:80              HEALTHY     OK                outbound|80||a.powerful-gray.svc.cluster.local
```
there is ep here

4. delete ServiceEntry, and dump endpoint
 istioctl pc ep {pod} | grep a.powerful-gray
```
172.31.52.7:8080        HEALTHY     OK                outbound|80||a.powerful-gray.svc.cluster.local
7.7.7.7:80              HEALTHY     OK                outbound|80||a.powerful-gray.svc.cluster.local
```
the ep is still here

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.3.5
**How was Istio installed?**
use helm, whitout galley and mixer

**Environment where bug was observed (cloud vendor, OS, etc)**
k8s 1.13
