### ISSUE TITLE
ServiceEntry instance deletion does not work

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19961]
Create a deployment, httpbin, in default namespace

```
cat <<EOF | kaf -
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin-egress
spec:
  hosts:
  - httpbin.default.svc.cluster.local
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: STATIC
  endpoints:
  - address: 10.31.241.103
    locality: egress
    ports:
      http: 80
EOF
```

Now if you check /clusters you will see 2 endpoints.

Delete the service entry, you will see 2 endpoints still, when there should be one.

I think what we need to do is:

If event == delete, then update instances here to delete: https://github.com/istio/istio/blob/master/pilot/pkg/serviceregistry/external/servicediscovery.go#L91

This won't be enough, we need to trigger update on EDS internal indexes by calling EDSUpdate. Just copying https://github.com/istio/istio/blob/master/pilot/pkg/serviceregistry/external/servicediscovery.go#L116 will not work -- I think that code is broken today. It should not be curr.Name, it should be the hostname. Name of service entry != hostname.
