### ISSUE TITLE
In VirtualService, the only host that works is the one with the same name as the service.

### ISSUE THREAD

**Issue by nerusnayleinad** [istio/istio#19972]
I am not seeing why is this failing, but when I add hosts (other then the services inside the cluster) to the VirtualService, I get 404 for all requests.

I have 2 services; one of them is serving "nginx", and the other one "apache" on `/path1`.

/ # for i in `seq 1 10`; do curl server/path1/; done
apache
nginx
apache
nginx
nginx
apache
nginx
apache
nginx
apache

Now, I create the VirtualService and the DestinationRule to have 80-20.

DR:

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: server-dr
spec:
  host: server.istio.svc.cluster.local
  subsets:
  - name: nginx
    labels:
      app: nginx
  - name: apache
    labels:
      app: apache
```

VS:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: server-vs
spec:
  hosts:
  - "host1.domain.com"
  - "host2.domain.com"
  http:
  - match:
    - headers:
        end-user:
          exact: a-user
      uri:
        prefix: /hola/
    - uri:
        prefix: /adios/
    rewrite:
      uri: /path1/
    route:
    - destination:
        host: server.istio.svc.cluster.local
        subset: nginx
      weight: 80
    - destination:
        host: server.istio.svc.cluster.local
        subset: apache
      weight: 20
```
But when I curl the service on any of these endpoints, I am not getting to nowhere.

```
/ # curl -H "Host: host1.domain.com" server/adios/ -I
HTTP/1.1 404 Not Found
date: Tue, 07 Jan 2020 18:08:16 GMT
server: envoy
transfer-encoding: chunked

/ # curl -H "Host: host1.domain.com" 10.100.153.252/adios/ -I
HTTP/1.1 404 Not Found
date: Tue, 07 Jan 2020 18:09:19 GMT
server: envoy
transfer-encoding: chunked

/ # curl -H "end-user: a-user" -H "Host: host1.domain.com" 10.100.153.252/hola/ -I
HTTP/1.1 404 Not Found
date: Tue, 07 Jan 2020 18:10:44 GMT
server: envoy
transfer-encoding: chunked
```
I can see the load balancing though, so it is working. It's just there is nothing under `/adios`

```
/ # curl server/adios/
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.17.6</center>
</body>
</html>

/ # curl server/adios/
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
</body></html>
```

Now, all I do is to add host "server" to the VirtualService. And now it starts working fine for host `server`:
```
...
  hosts:
  - "server"               <- added this line
  - "host1.domain.com"
  - "host2.domain.com"
  http:
...
```
```
/ # for i in `seq 1 10`; do curl -H "end-user: a-user" server/hola/; done
nginx
nginx
nginx
apache
nginx
nginx
nginx
apache
nginx
nginx

/ # for i in `seq 1 10`; do curl server/adios/; done
nginx
nginx
nginx
nginx
apache
nginx
nginx
nginx
nginx
apache

/ # for i in `seq 1 10`; do curl 10.100.153.252/adios/; done
nginx
nginx
nginx
nginx
apache
nginx
nginx
nginx
nginx
nginx
```

Note: 10.100.153.252 is the IP of `server`. Not sure why this last one is working, since there is no host.

But it doesn't work for other hosts:

```
/ # curl -H "end-user: a-user" -H "Host: host1.domain.com" server/hola/ -I
HTTP/1.1 404 Not Found
date: Tue, 07 Jan 2020 18:22:31 GMT
server: envoy
transfer-encoding: chunked

/ # curl -H "end-user: a-user" -H "Host: host1.domain.com" 10.100.153.252/hola/ -I
HTTP/1.1 404 Not Found
date: Tue, 07 Jan 2020 18:23:09 GMT
server: envoy
transfer-encoding: chunked
```

Is this normal? Why it isn't getting the other hosts?
