### ISSUE TITLE
Ingress Gateway is Ready before a config is synced which causes connection refuses on client

### ISSUE THREAD

**Issue by infa-rbliznet** [istio/istio#19980]
**The bug description:** 
When we try to update ingress-gateway or when it's autoscalled by Horizontal Pod Autoscaller we see connection drops (connection is refused on the client side). Time duration is very short, less than 1s but we fill it can be an issue with high traffic volume.  We found that Ingress is Ready as soon as Envoy is ready however initial configuration from pilot might not applied yet and listener is not created.

**Affected product area:**

**Expected behavior:** On startup, Ingress should wait till Pilot will sync initial configuration and do not accept traffic before it.

**Steps to reproduce the bug:**
1. Configure ingress gateway, for our testing we configured a custom gateway in separate namespace but it's actually inmatter
`helm install --name custom-gw -f values-gw-only.yaml istio-1.4.2/install/kubernetes/helm/istio`

**values-gw-only.yaml**
```
# Common settings.
global:
  # Omit the istio-sidecar-injector configmap when generate a
  # standalone gateway. Gateways may be created in namespaces other
  # than `istio-system` and we don't want to re-create the injector
  # configmap in those.
  omitSidecarInjectorConfigMap: true

  # Istio control plane namespace: This specifies where the Istio control
  # plane was installed earlier.  Modify this if you installed the control
  # plane in a different namespace than istio-system.
  istioNamespace: istio-system

  proxy:
    # Sets the destination Statsd in envoy (the value of the "--statsdUdpAddress" proxy argument
    # would be <host>:<port>).
    # Disabled by default.
    # The istio-statsd-prom-bridge is deprecated and should not be used moving forward.
    envoyStatsd:
      # If enabled is set to true, host and port must also be provided. Istio no longer provides a statsd collector.
      enabled: false
      host: # example: statsd-svc.istio-system
      port: # example: 9125


#
# Gateways Configuration
# By default (if enabled) a pair of Ingress and Egress Gateways will be created for the mesh.
# You can add more gateways in addition to the defaults but make sure those are uniquely named
# and that NodePorts are not conflicting.
# Disable specific gateway by setting the `enabled` to false.
#
gateways:
  enabled: true

  istio-ingressgateway:
    enabled: false

  custom-gateway:
    enabled: true
    labels:
      app: custom-gateway
      #replicaCount: 1
    autoscaleEnabled: true
    autoscaleMin: 1
    autoscaleMax: 5
    resources:
      limits:
        cpu: 2
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 40Mi
    cpu:
      targetAverageUtilization: 80
    loadBalancerIP: ""
    loadBalancerSourceRanges: {}
    externalIPs: []
    serviceAnnotations: {}
    podAnnotations: {}
    type: NodePort  #change to NodePort, ClusterIP or LoadBalancer if need be
    #externalTrafficPolicy: Local #change to Local to preserve source IP or Cluster for default behaviour or leave commented out
    ports:
      ## You can add custom gateway ports
    - port: 443
      name: https
    secretVolumes:
    - name: customgateway-certs
      secretName: istio-customgateway-certs
      mountPath: /etc/istio/customgateway-certs
    - name: customgateway-ca-certs
      secretName: istio-customgateway-ca-certs
      mountPath: /etc/istio/customgateway-ca-certs

# all other components are disabled except the gateways
security:
  enabled: false

sidecarInjectorWebhook:
  enabled: false

galley:
  enabled: false

mixer:
  policy:
    enabled: false
  telemetry:
    enabled: false

pilot:
  enabled: false

grafana:
  enabled: false

prometheus:
  enabled: false

tracing:
  enabled: false

kiali:
  enabled: false

certmanager:
  enabled: false
```
2. Configure Gateway and VirtualService
apiVersion: networking.istio.io/v1alpha3
```
kind: Gateway
metadata:
  name: custom-gw
  namespace: default
spec:
  selector:
    app: custom-gateway
  servers:
  - hosts:
    - '*'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      caCertificates: /etc/istio/customgateway-ca-certs/ca-chain.cert.pem
      mode: MUTUAL
      privateKey: /etc/istio/customgateway-certs/tls.key
      serverCertificate: /etc/istio/customgateway-certs/tls.crt
      
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: custom-gw-myservice
  namespace: default
spec:
  gateways:
  - default/custom-gw
  hosts:
  - "*"
  http:
  - match:
    - uri:
        prefix: /myservice
    route:
    - destination:
        host: myservice.svc.cluster.local
        port:
          number: 8443
```

3. Configure a container that simulate a load, we used a curl like that:
```
while true; do
    date
    curl -I -X GET -k -fsS --cacert root.pem --cert client-key-bundle.pem https://$1:443/myservice/healthy 2>&1
done
```
4. Scale UP Ingress gateway to say 15 instances. Or if you have several already, just do rolling restart:
```
 kubectl patch deployment custom-gateway  -p   "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
```
4. Observe a few connection drops in curl calls.

**Versions**

**istioctl version --remote**
client version: 1.4.2
control plane version: 1.4.2
data plane version: 1.2.2 (1 proxies), 1.4.0 (2 proxies), 1.4.2 (30 proxies)
-Note: We had old proxies in legacy unused namespaces...
**kubectl version**
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:51:44Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.12-eks-eb1860", GitCommit:"eb1860579253bb5bf83a5a03eb0330307ae26d18", GitTreeState:"clean", BuildDate:"2019-12-23T08:58:45Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

**Istio was installed with istioctl. The custom gateway for testing with helm v2.14.3

**We run Kubernetes on EKS**
