### ISSUE TITLE
"Connection was Closed" error after applying AuthorizationPolicy

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [istio/istio#19990]
**Bug description**

Getting error "Connection was closed" after applying authorization policy. I want a micro-service to only allow incoming traffic from a single micro-service and deny all others by default.

[X ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

We have a sample application that represents an online mart. It's divided into multiple micro-services/services; inventory, cart, catalog, front-end, mysql, mongo and a gateway that is responsible for forwarding traffic from external world to these micro-services. I want to ensure that only those services can access each other that are supposed to rest should deny all by default.

**Steps to reproduce the bug**

Following are the manifests that we used:

Gateway:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
        privateKey: /etc/istio/ingressgateway-certs/tls.key
      hosts:
        - "gateway-dev.DOMAIN"
        - "web-dev.DOMAIN"
    - port:
        number: 80
        name: http
        protocol: HTTP
      tls:
        httpsRedirect: true
      hosts:
        - "gateway-dev.DOMAIN"
        - "web-dev.DOMAIN"
```

VirtualService:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gateway-dev-virtualservice
  namespace: istio-system
spec:
  hosts:
    - "gateway-dev.DOMAIN"
  gateways:
    - istio-gateway
  http:
    - route:
        - destination:
            host: gateway.nordmart-dev-apps.svc.cluster.local
```

mTLS:

```yaml
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: default
  namespace: nordmart-dev-apps
spec:
  peers:
    - mtls: {} #this will set mTLS mode to : STRICT
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: default
  namespace: nordmart-dev-apps
spec:
  host: "*.nordmart-dev-apps.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```

AuthorizationPolicy:

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: catalog-policy
  namespace: nordmart-dev-apps
spec:
  selector:
    matchLabels:
      app: catalog
  rules:
    - from:
        - source:
            principals: ["cluster.local/ns/nordmart-dev-apps/sa/gateway"]
      to:
        - operation:
            methods: ["*"]
```

Sample URL: https://gateway-dev.DOMAIN/api/products
Response: {"error":"Connection was closed"}

Logs from gateway:

```
Jan 08, 2020 7:21:26 AM io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer
INFO: Succeeded in deploying verticle
Jan 08, 2020 7:21:27 AM io.vertx.servicediscovery.kubernetes.KubernetesServiceImporter
SEVERE: Error while interacting with kubernetes
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:61)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:52)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:538)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:64)
	at io.vertx.servicediscovery.kubernetes.KubernetesServiceImporter.lambda$start$1(KubernetesServiceImporter.java:99)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:271)
	at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Failed to connect to /10.0.0.1:443
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:189)
	at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:173)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)

```

You can view the repository against which this is deployed here: https://github.com/stakater-lab/nordmart-dev-apps/tree/master/releases-istio

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

Kubectl: Client v1.15.3, Server v1.14.8
helm: v2.11.0(client & server)
Istio: Operator(v1.4.0), helm chart(v1.4.2)

**How was Istio installed?**

I have tried with both helm charts & istio-operator and the same issue persists. Currently, i am using istio-operator.

**Environment where bug was observed (cloud vendor, OS, etc)**

I think this is cloud irrelevant but i have tried on AKS and EKS.

**Comment by yangminzhu** [comment]
The gateway log seems indicating it has some problems talking to kubernetes:
```
SEVERE: Error while interacting with kubernetes
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
```

This shouldn't be caused by Istio authorization policy. Could you enable the Envoy RBAC debug logging for `app: catalog` and trigger some requests to see if there is anything wrong in the log? Check this [tutorial](https://istio.io/docs/ops/common-problems/security-issues/#ensure-proxies-enforce-policies-correctly) for doing so.

It's also worth to try to disable the mTLS to see if this error continues (you need to delete the authorization policy as well). I'm a little bit suspecting it may be somehow related to mTLS but not sure.

**Comment by ahmedwaleedmalik** [comment]
Yes maybe but this issue occurs only after applying authorizationpolicy and as soon as i delete it things work as they are supposed to. Can you take a lot at the manifests, maybe i am doing something wrong here ?

From logs, after applying authorizationPolicy: 

```
[Envoy (Epoch 0)] [2020-01-13 06:37:52.069][26][debug][rbac] [external/envoy/source/extensions/filters/network/rbac/rbac_filter.cc:36] checking connection: requestedServerName: , remoteAddress: 10.244.0.24:35550, localAddress: 10.244.0.25:8080, ssl: none, dynamicMetadata: 
[Envoy (Epoch 0)] [2020-01-13 06:37:52.069][26][debug][rbac] [external/envoy/source/extensions/filters/network/rbac/rbac_filter.cc:104] enforced denied
[Envoy (Epoch 0)] [2020-01-13 06:38:09.718][26][debug][rbac] [external/envoy/source/extensions/filters/network/rbac/rbac_filter.cc:36] checking connection: requestedServerName: , remoteAddress: 10.244.0.24:36346, localAddress: 10.244.0.25:8080, ssl: none, dynamicMetadata: 
[Envoy (Epoch 0)] [2020-01-13 06:38:09.718][26][debug][rbac] [external/envoy/source/extensions/filters/network/rbac/rbac_filter.cc:104] enforced denied
[Envoy (Epoch 0)] [2020-01-13 06:38:09.720][27][debug][rbac] [external/envoy/source/extensions/filters/network/rbac/rbac_filter.cc:36] checking connection: requestedServerName: , remoteAddress: 10.244.0.24:36352, localAddress: 10.244.0.25:8080, ssl: none, dynamicMetadata: 
[Envoy (Epoch 0)] [2020-01-13 06:38:09.720][27][debug][rbac] [external/envoy/source/extensions/filters/network/rbac/rbac_filter.cc:104] enforced denied
[Envoy (Epoch 0)] [2020-01-13 06:38:09.734][26][debug][rbac] [external/envoy/source/extensions/filters/network/rbac/rbac_filter.cc:36] checking connection: requestedServerName: , remoteAddress: 10.244.0.26:51934, localAddress: 10.244.0.25:8080, ssl: none, dynamicMetadata: 
[Envoy (Epoch 0)] [2020-01-13 06:38:09.734][26][debug][rbac] [external/envoy/source/extensions/filters/network/rbac/rbac_filter.cc:104] enforced denied

```

Tried disabling mTLS and the issue still re-occurs. Tried moving AuthorizationPolicy to `istio-system` as well but still the same issue.

**Comment by ahmedwaleedmalik** [comment]
Any update on this ?

**Comment by yangminzhu** [comment]
@ahmedwaleedmalik The following RBAC log menas you haven't enabled mTLS (note the `ssl: none` part):

```
[Envoy (Epoch 0)] [2020-01-13 06:37:52.069][26][debug][rbac] [external/envoy/source/extensions/filters/network/rbac/rbac_filter.cc:36] checking connection: requestedServerName: , remoteAddress: 10.244.0.24:35550, localAddress: 10.244.0.25:8080, ssl: none, dynamicMetadata: 
[Envoy (Epoch 0)] [2020-01-13 06:37:52.069][26][debug][rbac] [external/envoy/source/extensions/filters/network/rbac/rbac_filter.cc:104] enforced denied
```

That's strange because from your DestinationRule and AuthN Policy it seems mTLS should be enabled, could you further get the Envoy config dump of both your gateway and the catalog workload?

**Comment by Jeskz0rd** [comment]
I confirm the same behaviour happening with istio `1.4.6`. i disabled mTLS and had the same effect.

**Comment by TimVosch** [comment]
Same issue here. I have three pods -> App, db, dbadmin. When I apply an Authorizationpolicy on App (see below). The app cannot connect to the DB and even the dbadmin can't connect to the DB. Both throwing a "connection terminated unexpectedly" or "connection closed"

```yaml
---
apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
  name: sb-allow-auth
spec:
  selector:
    matchLabels:
      app: sb-identity
  action: ALLOW
  rules:
    - to:
      - operation:
          paths: ["/.well-known/jwks.json"]
      - operation:
          methods: ["POST"]
          paths: ["/auth", "/users"]
      - operation:
          methods: ["GET"]
          paths: ["/.well-known/jwks.json"]
    - from:
      - source:
          requestPrincipals: ["*"]
```
