### ISSUE TITLE
client gets connection refused when ingres pods are rotated

### ISSUE THREAD

**Issue by infa-ddeore** [istio/istio#20027]
**Bug description**
client gets connection refused when ingress pods are rotated, it looks like when ingres pod is in termination process it still receives the traffic so client gets some connection refused errors.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ x] Networking
[ x] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
client shouldn't get connection refused regardless of ingress pods rotation

**Steps to reproduce the bug**
this can be reproduced in minikube.

1) install istio with the config, this config creates 5 replicas of ingress g/w

```
$ istioctl manifest apply -f istiocontrolplane-minikube.yaml
```
istiocontrolplane-minikube.yaml:
```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  security:
    enabled: true
    components:
      citadel:
        enabled: true
        k8s:
          replicaCount: 1

  configManagement:
    enabled: true
    components:
      galley:
        enabled: true
        k8s:
          replicaCount: 1

  trafficManagement:
    enabled: true
    components:
      pilot:
        enabled: true

  policy:
    enabled: true
    components:
      policy:
        enabled: true
        k8s:
          replicaCount: 1
          hpaSpec:
            minReplicas: 1

  telemetry:
    enabled: true
    components:
      telemetry:
        enabled: true
        k8s:
          replicaCount: 1
          hpaSpec:
            minReplicas: 1

  autoInjection:
    enabled: true
    components:
      injector:
        enabled: true
        k8s:
          replicaCount: 1

  gateways:
    enabled: true
    components:
      ingressGateway:
        enabled: true
        k8s:
          service:
            type: NodePort
          hpaSpec:
            minReplicas: 5

  values:
    gateways:
      istio-ingressgateway:
        type: NodePort
    prometheus:
      enabled: false
      replicaCount: 1
    kiali:
      enabled: false
    global:
      prometheusNamespace: lamm
      proxy:
        accessLogFile: /dev/stdout
      k8sIngress:
        enabled: true
        gatewayName: ingressgateway
        enableHttps: true
```

2) Deploy httpbin app, gw, and vs
```
$ kubectl apply -f https://raw.githubusercontent.com/istio/istio/master/samples/httpbin/httpbin.yaml
$ kubectl apply -f https://raw.githubusercontent.com/istio/istio/master/samples/httpbin/httpbin-gateway.yaml
```

3) Generate some load with curl
```
$ kubectl run -i --tty --rm --generator=run-pod/v1 curl-pod --image=radial/busyboxplus:curl 
### run curl in while loop from inside the curl pod
while true; do curl -I istio-ingressgateway.istio-system.svc.cluster.local/status/200; done
```

4) Below patch will force rotate ingress pods gracefully
```
kubectl -n istio-system patch deployment istio-ingressgateway -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
```

5) once new ingress g/w pods are running fine or during their rotation, curl will get some connection refused errors
```
curl: (7) Failed to connect to istio-ingressgateway.istio-system.svc.cluster.local port 80: Connection refused
curl: (7) Failed to connect to istio-ingressgateway.istio-system.svc.cluster.local port 80: Connection refused
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ istioctl version --remote
client version: 1.4.2
control plane version: 1.4.2
data plane version: 1.4.2 (5 proxies)

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:34Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
```
$ istioctl manifest apply -f istiocontrolplane-minikube.yaml
```

**Environment where bug was observed (cloud vendor, OS, etc)**
Minikube

**Comment by hzxuzhonghu** [comment]
>it looks like when ingres pod is in termination process it still receives the traffic so client gets some connection refused errors.

When you curl ingressgateway by svc name, the flow is from curl-->iptables redirect-> gateway. The connnection refused error seems like iptables refresh is not so instantly, there must be a delay.

**Comment by infa-ddeore** [comment]
do you know how to prove that iptables is causing this problem?

and is there a solution for this issue?

**Comment by hzxuzhonghu** [comment]
I think it is very difficult to grab the rule, the delay is too short

**Comment by infa-ddeore** [comment]
looks like adding preStop hook to wait for ~5 seconds may help

ref: https://blog.gruntwork.io/delaying-shutdown-to-wait-for-pod-deletion-propagation-445f779a8304 and https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-terminating-with-grace

I will try this ans post the results

**Comment by infa-ddeore** [comment]
adding sleep in container's `preStop` hook is helping, i did few tests and there is no connection refused every time. But after removing `preStop` hook config from the deployment there is connection refused error every time pods are rotated

```
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 5
```

should this hook be added by default with istio's installation? Also user g/w should have the same hook by default.

I had to edit istio-1.4.2/install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml manually to add this hook.
