### ISSUE TITLE
Block certain IPs to access services

### ISSUE THREAD

**Issue by rnkhouse** [istio/istio#20034]
**Bug description**
I want to block certain IP list to access services. For that I am using below code but it's giving me `upstream connect error or disconnect/reset before headers. reset reason: connection termination`. Am I doing something wrong? Istio Policy is set up correctly. I checked with the given example code which was working fine but I want to block external IP.

**yaml**

    apiVersion: config.istio.io/v1alpha2
    kind: handler
    metadata:
      name: blacklistip
    spec:
      compiledAdapter: listchecker
      params:
        # providerUrl: ordinarily black and white lists are maintained
        # externally and fetched asynchronously using the providerUrl.
        overrides: ["xx.xx.xx.xx"]  # overrides provide a static list
        blacklist: true
        entryType: IP_ADDRESSES
    ---
    apiVersion: config.istio.io/v1alpha2
    kind: instance
    metadata:
      name: clientip
    spec:
      compiledTemplate: listentry
      params:
        value: request.headers["x-forwarded-for"] | "unknown"
    ---
    apiVersion: config.istio.io/v1alpha2
    kind: rule
    metadata:
      name: checkip
    spec:
      match: source.labels["istio"] == "ingressgateway"
      actions:
      - handler: blacklistip
        instances: [ clientip ]

I checked istioingressgateway logs:

    {"bytes_sent":"95","upstream_cluster":"outbound|3000||api.default.svc.cluster.local","downstream_remote_address":"xx.xx.xx.xx:59762","authority":"api.example.com","path":"/core/csrf","protocol":"HTTP/2","upstream_service_time":"-","upstream_local_address":"-","duration":"1","downstream_local_address":"10.2.0.14:443","upstream_transport_failure_reason":"-","route_name":"-","response_code":"503","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36","response_flags":"UC","start_time":"2020-01-15T16:32:21.634Z","method":"GET","request_id":"353149b6-0749-4a1a-9348-4016d20215de","upstream_host":"10.2.0.33:3000","x_forwarded_for":"xx.xx.xx.xx","requested_server_name":"api.example.com","bytes_received":"0","istio_policy_status":"-"}

Istio proxy logs within the pod:

    {"authority":"-","path":"-","protocol":"-","upstream_service_time":"-","upstream_local_address":"127.0.0.1:53894","duration":"0","downstream_local_address":"10.2.0.33:3000","upstream_transport_failure_reason":"-","route_name":"-","response_code":"0","user_agent":"-","response_flags":"-","start_time":"2020-01-15T17:21:25.220Z","method":"-","request_id":"-","upstream_host":"127.0.0.1:3000","x_forwarded_for":"-","requested_server_name":"outbound_.3000_._.api.default.svc.cluster.local","bytes_received":"0","istio_policy_status":"-","bytes_sent":"0","upstream_cluster":"inbound|3000|https|api.default.svc.cluster.local","downstream_remote_address":"10.2.0.14:37126"}

**It looks like client IP address is there in istioingressgateway logs but not in pod istio-proxy logs.** I also logged custom logs in mixer using `newlog instance`. When I apply above yaml file, I am not getting any `request` attribute. `request.id` is also blank.

**mixer logs**

    2020-01-15T22:48:47.633162Z	error	evaluation failed at [sourceip.instance.default]'Value': 'lookup failed: 'request.headers''
    2020-01-15T22:48:47.633192Z	error	error creating instance: destination='listentry:whitelistip.default(listchecker)', error='evaluation failed at [sourceip.instance.default]'Value': 'lookup failed: 'request.headers'''
    2020-01-15T22:48:47.633204Z	error	api	Check failed: performing check operation failed: 1 error occurred:
	* evaluation failed at [sourceip.instance.default]'Value': 'lookup failed: 'request.headers''

**Expected behavior**

It should block the mentioned IP address and accept requests from other IP addresses.

**Steps to reproduce the bug**

Just apply given yaml file to your cluster. Replace `xx.xx.xx.xx` with your client/public IP address.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4.2

**How was Istio installed?**
Helm Template

**Environment where bug was observed (cloud vendor, OS, etc)**
AKS

**Comment by gargnupur** [comment]
Looks like error is coming from here: 
Check failed: performing check operation failed: 1 error occurred:
* evaluation failed at [sourceip.instance.default]'Value': 'lookup failed: 'request.headers''

Can you get the config dump of your istio proxy and see if request.headers is defined there?

**Comment by rnkhouse** [comment]
@gargnupur How can I get the istio proxy config dump?

**Comment by linuxbsdfreak** [comment]
@gargnupur @rnkhouse ,

I am facing the same issue. I have a list of whitelisted and blacklisted IP ranges stored on github in a text file. I tried the suggestion from `https://discuss.istio.io/t/istio-ingress-ip-whitelisting/2670/12` with no success.

The setup is on AWS with istio 1.4.3 on a gardener K8s cluster. 

This is my setup config

```
istioctl manifest apply --set profile=demo --set values.gateways.istio-ingressgateway.sds.enabled=true --set values.gateways.istio-egressgateway.enabled=true --set values.global.mtls.auto=true --set values.global.mtls.enabled=false --set values.global.controlPlaneSecurityEnabled=true --set values.gateways.istio-ingressgateway.externalTrafficPolicy=Local --set values.global.proxy.accessLogFile="/dev/stdout" 
```

i have a sample app in a namespace which works . 

The rules are provided in the istio-system namespace. I want it to be globally managed. 

```
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: blacklistip
spec:
  compiledAdapter: listchecker
  params:
    providerUrl: "https://raw.github.com/myrepo/blacklist.txt?token=xxxxxxxx"
    overrides: ["xxx.xxx.xxx.xxx/32"]
    blacklist: true
    entryType: IP_ADDRESSES
---
apiVersion: config.istio.io/v1alpha2
kind: instance
metadata:
  name: sourceip-blacklist
spec:
  compiledTemplate: listentry
  params:
    value: request.headers["x-forwarded-for"] | "unknown"
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: checkip-blacklist
spec:
  match: source.labels["istio"] == "ingressgateway"
  actions:
  - handler: blacklistip
    instances: [ sourceip-blacklist ]
```

If i activate the URL. It gives the following error

```
[2020-02-06T07:47:13.677Z] "GET / HTTP/2" 500 UAEX ""INTERNAL:performing check operation failed: 1 error occurred:%0A%09* Could not parse data from "https://raw.github.com/myrepo/blacklist.txt?token=xxxxxxxx": could not unmarshal data from list error unmarshaling JSON: json: cannot unmarshal string into Go value of type list.listPayload%0A%0A"" "-" 0 369 1 - "10.250.16.98"
```

I am stuck on this simple issue for so long with no fix. Could you help me out? 

Kevin
