### ISSUE TITLE
Inject istio-proxy as the first container

### ISSUE THREAD

**Issue by Stono** [istio/istio#20069]
**Describe the feature request**
Through testing we've discovered that kubelet + docker will pull and start `containers` within `pod` in order.  

Therefore it'd be great if the `sidecar-injector` injected the `istio-proxy` at position 0 in the pod, this would ensure that the proxy image was always pulled and started (albeit not waiting for ready ready) before the application image.

I appreciate that it still doesn't wait for anything to be **ready**, but the way this manifested for us was the application container was pulled and started first and then due to a slow registry, the istio-proxy container was pulled and that took 15 seconds, meanwhile the app started and crashed.   This change would guarantee the istio-proxy image was **at least** started, before the app.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by howardjohn** [comment]
the proxy image should be pulled in the init stage now since the init is using the same image, unless you are doing something custom. That being said the starting container may be an issue.

I am not sure how this interacts with things like `kubectl exec` which I think default to the first container - may not be a concern, but there may be similar issues that I haven't thought of

**Comment by Stono** [comment]
Ahh, yes it does since 1.4.  I miss-read the logs, it was our cloudsql-proxy container that hit this and I can control that one.  Thanks/sorry

**Comment by howardjohn** [comment]
No worries. If it is actually faster due to startup though I would be interested

**Comment by Stono** [comment]
Actually @howardjohn perhaps reopen this as i still think it is valuable, as having istio-proxy as container 0 will ensure that all the volume mounts are ready too (eg certificates), before starting the app.

I think there's value in ensure that istio-proxy has always started first (not just mitigating pull issues)

**Comment by Stono** [comment]
or make it a configurable option for us?  I'd certainly enable it.

**Comment by howardjohn** [comment]
Oh really, it will actually block the other container, I didn't know that. Seems useful or at least worth exploring more

**Comment by Stono** [comment]
That's what we're observing on GKE1.15.  The frustrating thing is we can't find that documented anywhere so I suppose the counter-argument here is we'd be doing something based on something that could change anyway.

**Comment by Stono** [comment]
@howardjohn here's an example btw, first containier has a volume that doesn't exist, the second and third aren't even attempted:

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    sidecar.istio.io/inject: "true"
  name: mike
spec:
  containers:
  - name: firstcontainer
    image: centos:7
    imagePullPolicy: Always
    command: ["bin/sleep"]
    args:
    - "10000000"
    volumeMounts:
    - name: mysecret
      mountPath: /etc/fewilregnungeiro
  - args:
    - "1000000000"
    image: centos:8
    imagePullPolicy: Always
    name: secondcontainer
    command: ["/bin/sleep"]
    securityContext:
      privileged: true
  - name: thirdcontainer
    image: centos:6
    imagePullPolicy: Always
    command: ["bin/sleep"]
    args:
    - "10000000"
  volumes:
  - name: mysecret
    secret:
      secretName: mysecret
```
