### ISSUE TITLE
Does istio ingress gateway support TCP-based traffic with TLS

### ISSUE THREAD

**Issue by barryzhounb** [istio/istio#20076]
**Bug description**
Error from server: error when creating "tcpserver-gateway.yaml": admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: server cannot have TLS settings for non HTTPS/TLS ports

I have a TLS client in outside of OpenShift, then I create a istio ingress gateway and inject key and certificate to istio successfully.

Then I add tls properties into Gateway yaml as following:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tcpserver-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 6677
      name: tcp
      protocol: TCP
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    - "*"
```
When I run this yaml file, I got the following errors:
```
Error from server: error when creating "tcpserver-gateway.yaml": admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: server cannot have TLS settings for non HTTPS/TLS ports
```

In my case, my client is TCP-based traffic, and port is 6677, I can not set TLS configuration successfully.

My question is, does istio ingress gateway support non-HTTP traffic (TCP-based) TLS? If support, what wrong is it in my case? How to fix it?

[ X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
Make the port:
```

      number: 6677
      name: tls
      protocol: TLS
```

**Comment by JimmyCYJ** [comment]
The validation is executed here https://github.com/istio/istio/blob/8d9c7c922efb48da79ddfc92cc250c6d2029e2ac/pkg/config/validation/validation.go#L374

Please follow @howardjohn 's comment and change the protocol.

**Comment by SteveHespelt** [comment]
I'm guessing the OP's reason for posting this issue is aligned with my interest in this issue. What about non-https TLS termination at the Gateway?  The same value in having the Gateway perform TLS termination for ingress https traffic also exists for non-https (eg. imap, smtp, etc.) traffic over TLS connections. using TLS as the protocol (according to the docs) puts the burden back onto the services. Is there a decision reason why only https TLS termination is provided?  
MTIA for any feedback.

**Comment by howardjohn** [comment]
> Is there a design reason why only https TLS termination is provided

Its not. The protocol "TLS" is for non-https traffic over TLS connections

**Comment by SteveHespelt** [comment]
Hi Howard, 
According to the docs (for 1.4.3), _"TLS implies the connection will be routed based on the SNI header to the destination without terminating the TLS connection."_  I take from this that the individual services are responsible for handling TLS, rather than Istio providing TLS termination. 
Maybe I missed the boat somewhere but why wouldn't a configuration of protocol: tcp, tls.mode: SIMPLE result in TLS termination semantics in a manner similar to protocol: https, tls.mode: SIMPLE.
The presence of the tls block dictates that TLS is handled in the manner specified by the tls.mode value, right?
So I'm still confused as to how, by using protocol: TLS, does the mesh provide non-https TLS termination?
Thanks again for your help & insights.

**Comment by incfly** [comment]
thanks @howardjohn for the ansewring. Closing as question being resolved.

> TLS implies the connection will be routed based on the SNI header to the destination without terminating the TLS connection

I think we are using that for special multi cluster setup.

**Comment by tksheth** [comment]
Sorry , Its not clear what was the resolution ? Can we terminate TLS for TCP traffic at Istio gateway ? Or does it have to be handled by the backend service ?

**Comment by nrjpoddar** [comment]
> Sorry , Its not clear what was the resolution ? Can we terminate TLS for TCP traffic at Istio gateway ? Or does it have to be handled by the backend service ?

AFAIK you cannot. Terminating TLS requires any proxy to understand higher level protocol like HTTP or FTP. Terminating TLS and then proxying TCP data is not a thing that’s possible. You would have to configure GW as TCP proxy without termination and handle TLS at the application workload itself.

**Comment by howardjohn** [comment]
@nrjpoddar I am not sure that is accurate? Why would we need HTTP? my understanding is you would create some config like

```
protocol: TLS
tls:
  mode: SIMPLE
```


In envoy, we then create a listener doing SNI matching, terminating TLS, and then sending to the cluster based on the virtual service routing?

I haven't actually tested this, just my intuition

**Comment by nrjpoddar** [comment]
> @nrjpoddar I am not sure that is accurate? Why would we need HTTP? my understanding is you would create some config like
> 
> ```
> protocol: TLS
> tls:
>   mode: SIMPLE
> ```
> 
> In envoy, we then create a listener doing SNI matching, terminating TLS, and then sending to the cluster based on the virtual service routing?
> 
> I haven't actually tested this, just my intuition

I don’t think that will work, try it out and let me know.  Remember SNI routing is not terminating, currently when you say TLS it does SNI routing without termination.

**Comment by tksheth** [comment]
I tend to agree with @howardjohn . But again even I have not tested . So ,for L4-L6 protocols If TLS will never terminate at gateway then not sure what is use of setting different TLS mode at the gateway.

**Comment by howardjohn** [comment]
It can be done but its at the gateway level rather than doing the `tls` matching in virtual service:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bookinfo-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 15443
      name: tls
      protocol: TLS
    tls:
      mode: SIMPLE
      credentialName: sds-credential
    hosts:
    - "a.${INGRESS_DOMAIN}"
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bookinfo-gateway-alt
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 15443
      name: tls
      protocol: TLS
    tls:
      mode: SIMPLE
      credentialName: sds-credential
    hosts:
    - "b.${INGRESS_DOMAIN}"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - "*"
  gateways:
  - bookinfo-gateway
  tcp:
  - match:
    - port: 15443
    route:
    - destination:
        host: echo
        port:
          number: 9090
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo-alt
spec:
  hosts:
  - "*"
  gateways:
  - bookinfo-gateway-alt
  tcp:
  - match:
    - port: 15443
    route:
    - destination:
        host: echo-alt
        port:
          number: 9090
```

then

`echo hello | openssl s_client -connect a.DOMAIN:15443 -quiet` goes to `echo` and 


`echo hello | openssl s_client -connect b.DOMAIN:15443 -quiet` goes to `echo-alt`
