### ISSUE TITLE
Custom istio-ingressgateway Service Object annotations configuration

### ISSUE THREAD

**Issue by elliottnichols** [istio/istio#20078]
**Bug description**
I'm not entirely sure if this is a bug or needs to be a feature request but I'm unable to configure annotations to the istio-ingressgateway service object. The annotations metadata is set with a null value when rendered with istioctl

I've attempted this config with overlays but I'm unable to target the null annotations path successfully. If there is a known way to target service annotations itI would solve this issue. 

Otherwise it may be a new feature to add serviceAnnotations to the K8s ServiceSpec:
https://istio.io/docs/reference/config/istio.operator.v1alpha12.pb/#k8s-io-api-core-v1-ServiceSpec 

[x] Configuration Infrastructure
[ ] Docs
[] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Overlay or serviceAnnotation support allows for rendering configuration yaml with custom service annotations.

**Steps to reproduce the bug**
`istioctl manafest generate -f ....` results in
`panic: runtime error: invalid memory address or nil pointer dereference`

Example
```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  profile: default
  gateways:
    components:
      ingressGateway:
        k8s:
          overlays:
            - name: istio-ingressgateway
              apiVersion: v1
              kind: Service
              patches:
                - path: metadata.annotations      # ERROR HERE. Many permutations of this path attempted.
                  value:
                      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
                      service.beta.kubernetes.io/azure-load-balancer-internal-subnet: jump
...
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Attempted with: `1.4.2` and `1.4.3`

**How was Istio installed?**
`curl -L https://istio.io/downloadIstio | sh -`

**Environment where bug was observed (cloud vendor, OS, etc)**
n/a
