### ISSUE TITLE
Multiple telemetry pods can lead to bad count metrics

### ISSUE THREAD

**Issue by jaygorrell** [istio/istio#20102]
**Bug description**
When running 2+ telemetry pods (or using HPA, which is default), new pods will have a fresh starting count for things like requests.

**Expected behavior**
Telemetry can be autoscaled without inaccurate fluctuations in metrics.

**Steps to reproduce the bug**
1. Run up the request count in your cluster.
2. Scale up the telemetry pods.
3. See prometheus (or any scraper) picks up fluctuating values.

**Version**
Istio 1.3.5
Kubernetes 1.14.9

![image](https://user-images.githubusercontent.com/12174604/72213261-813bde80-34b9-11ea-9ec2-15447c4fd728.png)

**Comment by howardjohn** [comment]
You should only look at the rate of any metric that is monotonically increasing, not the value, doesn't this apply to every single application with a counter or am I missing something?

**Comment by jaygorrell** [comment]
I could be misunderstanding myself, but isn't that an issue when your scrape endpoint is balanced between pods with independent counts? This works fine for a single telemetry pod but when you scrape monotonic values from multiple pods (ie. during scaling), how are you supposed to know the _rate_?

As for every other application with a counter, for example Datadog, metrics are submitted to the agents on the local host, which run as a daemonset. Some others use a shared store across pods. 

To work around this for now, I just scaled telemetry down to 1 and disabled HPA... that works fine for now, but probably isn't intended for users.

**Comment by howardjohn** [comment]
say I have 2 pods. One reports 0 at t0 and 10 at t1. The other reports 15 at t0 and 25 at t1.

We are seeing a qps of 20 in reality. If I look at the metric I see 2 data points at 10 and 25 which is meaningless. if I add `rate` I will now see 2 seriees at 10 and 10. Now we sum those and see 20, which is our expected qps

**Comment by jaygorrell** [comment]
I think I see the disconnect here, and maybe it's a problem with Datadog's documentation. They suggest the following setup for scraping:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: istio-config-map
  namespace: default
data:
  istio-config: |-
    cluster_check: true
    init_config:
    instances:
      - istio_mesh_endpoint: "http://istio-telemetry.istio-system:42422/metrics"
        mixer_endpoint: "http://istio-telemetry.istio-system:15014/metrics"
        galley_endpoint: "http://istio-galley.istio-system:15014/metrics"
        pilot_endpoint: "http://istio-pilot.istio-system:15014/metrics"
        citadel_endpoint: "http://istio-citadel.istio-system:15014/metrics"
        send_histograms_buckets: "true"
```

I believe you're referring to scraping at the pod-level so you have tag information about which pod generated which metric. In the case above, you hit a service and don't know which pod is serving that value... so in your example, at t0 we may scrape 0 and then at t1 we scrape 25.

If you agree the approach from DD is the issue here I can close this and open an issue over there for documentation changes to scrape pods directly.

Source: https://www.datadoghq.com/blog/istio-datadog/
