### ISSUE TITLE
regression: hpa spec broken with new iop API

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#20143]
Config:
```
apiVersion: operator.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
  namespace: istio-operator
spec:
  components:
    pilot:
      k8s:
        resources:
          requests:
            cpu: 2000m

    policy:
      enabled: false
    
    telemetry:
      enabled: false
    galley:
      enabled: false
    citadel:
      enabled: false
    ingressGateways:
    - enabled: true
      k8s:
         hpaSpec:
           minReplicas: 3
           maxReplicas: 10
        resources:
          limits:
            cpu: 6000m
            memory: 512Mi
          requests:
            cpu: 4000m
            memory: 512Mi
```

```
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ""
    name: ""
``

See scaleTargetRef, it is not correct.
