### ISSUE TITLE
TLS Origination from a Pod with certificates in `DestinationRule` object.

### ISSUE THREAD

**Issue by nerusnayleinad** [istio/istio#20154]
From your examples, I quote:

> The following configuration adds a set of MongoDB instances running on unmanaged VMs to Istio’s registry, so that these services can be treated as any other service in the mesh. The associated DestinationRule is used to initiate mTLS connections to the database instances.

**ServiceEntry:**

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-mongocluster
spec:
  hosts:
  - mymongodb.somedomain # not used
  addresses:
  - 192.192.192.192/24 # VIPs
  ports:
  - number: 27018
    name: mongodb
    protocol: MONGO
  location: MESH_INTERNAL
  resolution: STATIC
  endpoints:
  - address: 2.2.2.2
  - address: 3.3.3.3
```
and the associated DestinationRule
**DestinationRule:**

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mtls-mongocluster
spec:
  host: mymongodb.somedomain
  trafficPolicy:
    tls:
      mode: MUTUAL
      clientCertificate: /etc/certs/myclientcert.pem
      privateKey: /etc/certs/client_private_key.pem
      caCertificates: /etc/certs/rootcacerts.pem
```

It would be nice to have a little bit more info about the scenario, since in other pages the TLS origination is stated to be initiated with `tls.mode=SIMPLE` parameter.

Now it looks like we are starting TLS. Are there are constrains? What are these certs? I tried using the certs within the proxy of the pod, but I get this error:

> [2020-01-14T12:04:17.728Z] "GET / HTTP/1.1" 503 UF,URX "-" "TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER" 0 91 135 - "-" "curl/7.59.0" "48411800-9ddb-9133-a480-4750f29c4416" "my-endpoint.com" "xx.xx.xx.xx:80" outbound|80||my-endpoint.com - xx.xx.xx.xx:80 192.168.113.150:47424 - default
 
What are the certs I need to pass to the DestinationRule? I can't create new certs in istio-proxy container since it is  read-only file system.
