### ISSUE TITLE
istioctl random errors when using non default namespace

### ISSUE THREAD

**Issue by Laakso** [istio/istio#20168]
**Bug description**
When installing istio to non default namespace I'm getting following error:

Component Telemetry - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

Error from server (AlreadyExists): error when creating "STDIN": attributemanifests.config.istio.io "kubernetes" already exists (repeated 1 times)

istioctl applies my configuration fine to default istio-system namespace.

values.yaml below
```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  defaultNamespace: new-namespace
  values:
    telemetry:
      enabled: true
    kiali:
      enabled: true
      tag: v1.11.0
    tracing:
      enabled: true
    prometheus:
      enabled: false
    global:
      controlPlaneSecurityEnabled: true
      mtls:
        auto: false
        enabled: false
      proxy:
        accessLogEncoding: JSON
        accessLogFile: "/dev/stdout"
        accessLogFormat: ""
    gateways:
      istio-ingressgateway:
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
```

If I apply values.yaml twice, istioctl returns normally.

**Expected behavior**

Clean apply

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
istioctl -i new-namespace version
client version: 1.4.3
control plane version: 1.4.3
data plane version: 1.4.3 (1 proxies)
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**
istioctl
**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS
