### ISSUE TITLE
Job istio-security-post-install-1.4.3 fails, causes Helm upgrade to fail

### ISSUE THREAD

**Issue by tillig** [istio/istio#20184]
**Bug description**

In an existing 1.4.3 deployment of Istio, we want to update some values to change the deployed features. The `values.yaml` we use gets updated, we run `helm upgrade`, and the `istio-security-post-install-1.4.3` job fails repeatedly, causing Helm to time out during the upgrade and consider the upgrade failed.

When this happens, the `istio-security-post-install-1.4.3` job remains and a subsequent attempt to run the update fails because the job still exists. You must manually remove the job to retry.

The logs on the pod running the job show that the pod for some reason can't connect to the Kubernetes API server.

```
+ istio-security-post-install-1.4.3-4vl4l › kubectl
istio-security-post-install-1.4.3-4vl4l kubectl + '[' 1 -ne 1 ']'
istio-security-post-install-1.4.3-4vl4l kubectl + pathToResourceYAML=/tmp/security/custom-resources.yaml
istio-security-post-install-1.4.3-4vl4l kubectl + kubectl get validatingwebhookconfiguration istio-galley
istio-security-post-install-1.4.3-4vl4l kubectl + '[' 1 -eq 0 ']'
istio-security-post-install-1.4.3-4vl4l kubectl + sleep 5
istio-security-post-install-1.4.3-4vl4l kubectl + kubectl apply -f /tmp/security/custom-resources.yaml
istio-security-post-install-1.4.3-4vl4l kubectl unable to recognize "/tmp/security/custom-resources.yaml": Get https://10.0.0.1:443/api?timeout=32s: dial tcp 10.0.0.1:443: connect: connection refused
istio-security-post-install-1.4.3-4vl4l kubectl unable to recognize "/tmp/security/custom-resources.yaml": Get https://10.0.0.1:443/api?timeout=32s: dial tcp 10.0.0.1:443: connect: connection refused
istio-security-post-install-1.4.3-4vl4l kubectl unable to recognize "/tmp/security/custom-resources.yaml": Get https://10.0.0.1:443/api?timeout=32s: dial tcp 10.0.0.1:443: connect: connection refused
```

My `values.yaml` for Istio:

```yaml
gateways:
  istio-ingressgateway:
    sds:
      enabled: true
kiali:
  enabled: true
  dashboard:
    jaegerURL: http://jaeger-query.monitoring.svc.cluster.local:16686/jaeger
    grafanaURL: http://grafana.monitoring.svc.cluster.local
global:
  k8sIngress:
    enabled: false
    gatewayName: ingressgateway
    enableHttps: true
  imagePullPolicy: Always
  controlPlaneSecurityEnabled: true
  tracer:
    zipkin:
      address: jaeger-collector.monitoring.svc.cluster.local:9411
  mtls:
    enabled: true
```

I'm betting it has something to do with mTLS being enabled, but I also see that there is already the DestinationRule for the api-server that was put in there from the previous deploy. It should be excluded from mTLS.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  annotations:
  labels:
    app: security
    chart: security
    heritage: Helm
    release: istio
  name: api-server
  namespace: istio-system
spec:
  host: kubernetes.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
```

**Expected behavior**

I expect the job to be able to start and complete successfully so the Helm deployment is not blocked.

**Steps to reproduce the bug**

1. Deploy Istio 1.4.3 using Helm. Use the values above.
2. Update a value in your `values.yaml`, like enabling the k8sIngress.
3. Re-deploy Istio 1.4.3 using Helm.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

- istioctl version --remote:
  - client version: 1.4.2
  - control plane version: 1.4.3
  - data plane version: 1.4.3 (9 proxies)
- kubectl version:
  - client version: 1.17.0
  - server version: 1.13.12
- helm version: 3.0.2

**How was Istio installed?**

Helm

**Environment where bug was observed (cloud vendor, OS, etc)**

Azure Kubernetes Service running Linux nodes.
