### ISSUE TITLE
Wildcard for DestinationRule, to configure mTLS doesn't work. 

### ISSUE THREAD

**Issue by nerusnayleinad** [istio/istio#20201]
I have mTLS enabled, and when I create the `DestinationRule` to globally enable mTLS for all services, it fails.

So, `MeshPolicy` object is created and I can't make requests to another service:

```
# kubectl exec -it curler-5b5966dfcc-h8drb -n demo sh
/ # curl nginx.istio
upstream connect error or disconnect/reset before headers. reset reason: connection termination
```

Now I create the `DestinationRule` as follows:

```
kubectl apply -f - <<EOF
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "default"
  namespace: "istio-system"
spec:
  host: "*.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
EOF
```

But I still get the error:
```
...
destinationrule.networking.istio.io/default created
root@v1-16-master:~# kubectl exec -it curler-5b5966dfcc-h8drb -n demo sh
/ # curl nginx.istio
upstream connect error or disconnect/reset before headers. reset reason: connection termination 
```

But if I change the host by the one I am trying to reach, it works:

```
root@v1-16-master:~# kubectl replace -f - <<EOF
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "default"
  namespace: "istio-system"
spec:
  host: "nginx.istio.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
EOF

destinationrule.networking.istio.io/default replaced
root@v1-16-master:~# kubectl exec -it curler-5b5966dfcc-h8drb -n demo sh
/ # curl nginx.istio
...
<h1>Welcome to nginx!</h1>
...
```
Of course, you lose the 'globally' part of mTLS here.

And, it doesn't work, if I create it in the client namespace:

```
# cat <<EOF | kubectl create -n demo -f -
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: dr-nginx-mtls
spec:
  host: "nginx.istio.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
EOF

destinationrule.networking.istio.io/dr-nginx-mtls created

root@v1-16-master:~# kubectl exec -it curler-5b5966dfcc-h8drb -n demo sh
/ # curl nginx.istio -I
HTTP/1.1 503 Service Unavailable
date: Wed, 15 Jan 2020 10:03:23 GMT
server: envoy
transfer-encoding: chunked
```

I am using k8s 1.16.4 and Istio 1.4.2
