### ISSUE TITLE
issue with elasticsearch fix or not ?

### ISSUE THREAD

**Issue by xinxinzhao1212** [istio/istio#20234]
In istio1.4.2 , my client can not connect with elasticsearch server with sidecar and can be connected without sidecar ,it is the same as the issue 16851 ,but i can not find the commit in the source code ,so could anyone kindly tell me if the bug has fix or not , if it has been fixed ,could you share the commit link to me ? thank you .

https://github.com/istio/istio/issues/16851

**Comment by TomasKohout** [comment]
Hi, I've faced the same issue, but solution can be found here. https://github.com/istio/istio/issues/14662

Basically this is what should do the magic.

```
          - name: network.bind_host
            value: 127.0.0.1
          - name: network.publish_host
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
```
