### ISSUE TITLE
sidecar-injector with SDS enabled breaks pod securityContext 

### ISSUE THREAD

**Issue by btoonk** [istio/istio#20409]
**Bug description**

The pod securityContext is patched by the sidecar-injector when sds is enabled.
But it looks like the pod securityContext gets overwritten instead of properly patched.

This will also overwrite pod securityContext fields like runAsUser which results in a POD without the runAsUser pod securityContext field.

See: 
https://github.com/istio/istio/blob/master/pkg/kube/inject/inject.go#L848
https://github.com/istio/istio/blob/master/pkg/kube/inject/webhook.go#L576

This only impacts the pod securityContext spec not the securityContext field in container spec.

[ X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

When enabling SDS, we expect a Pod with a pod securityContext spec to be scheduled with these pod securityContext applied and with only the FSGroup added/overwritten. 

**Steps to reproduce the bug**

* Enable SDS (istioctl manifest apply --set profile=sds)
* Deploy helloworld:
```
kind: Deployment
metadata:
  name: helloworld
  namespace: test
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 2
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: helloworld
        image: docker.io/istio/examples-helloworld-v1
        ports:
        - containerPort: 5000
```

In our case this will result in the following events because we only allow NonRoot users with psp:
`Warning  FailedCreate  22s               replicaset-controller  Error creating: pods "helloworld-78969cf685-p8h8n" is forbidden: unable to validate against any pod security policy: []`

If we add the runAsUser in the containers securityContext spec the pods will be scheduled correctly.
```
kind: Deployment
metadata:
  name: helloworld
  namespace: test
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 2
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: helloworld
        image: docker.io/istio/examples-helloworld-v1
        ports:
        - containerPort: 5000
        securityContext:
          runAsUser: 1000
```

In the istio-sidecar-injector log we see the following in the "info	AdmissionResponse: patch" message:
{"op":"add","path":"/spec/securityContext","value":{"fsGroup":1337}}

With sds disabled we see:
{"op":"add","path":"/spec/securityContext","value":{"runAsUser":1000,"fsGroup":1}}

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istioctl version --remote
client version: 1.4.3
citadel version: 1.4.3
galley version: 1.4.3
nodeagent version:
nodeagent version:
nodeagent version:
nodeagent version:
nodeagent version:
nodeagent version:
pilot version: 1.4.3
policy version: 1.4.3
sidecar-injector version: 1.4.3
telemetry version: 1.4.3
data plane version: 1.4.3 (4 proxies)

**How was Istio installed?**

istioctl manifest apply --set profile=sds

**Environment where bug was observed (cloud vendor, OS, etc)**

We're running on GKE, tested with version v1.13.11-gke.14
