### ISSUE TITLE
Ingress Gateway does not handle reusing TCP connection when using multiple Gateways

### ISSUE THREAD

**Issue by dankirkpatrick** [istio/istio#20425]
**Bug description**
If using multiple Gateway resources, the IngressGateway does not properly handle multiple requests over the same TCP pipe.  If the user makes 2 requests to 2 different URLs (each using a different gateway), the 2nd request gets mapped by the IngressGateway to the first URL since the request uses the same TCP pipe.  The "host" HTTP header is ignored for the 2nd request (probably because it is over the same TCP pipe) and gets routed to the Gateway/VirtualService in the 1st request from the client.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
The 2nd request over the same TCP pipe should be routed to the 2nd Gateway/VirtualService.

**Steps to reproduce the bug**

1.  Create 2 Gateway objects, each pointing to a different VirtualService
2.  Open a web browser with 2 tabs.  In one tab, open the URL from the first Gateway.  In the 2nd tab, open the URL form the second Gateway.  Note that the 2nd request fails.  Also note that, in the IngressGateway's logs, the 2nd request is mapped to the wrong Gateway object, and that both requests use the same client TCP port.

Also note that if you close the browser and reopen the browser, reversing the sequence of URLs requested, the 2nd Gateway will work but the 1st Gateway will fail.

Using "curl" always succeeds, because each request will be made from a different process, and thus gets a unique TCP connection and client TCP port.

For my purposes, I used the following Gateway and VirtualService objects:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  annotations:
  name: istio-grafana-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - istio-grafana.mycompany.com
    port:
      name: http-grafana
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - istio-grafana.mycompany.com
    port:
      name: https-grafana
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kiali-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - kiali.mycompany.com
    port:
      name: http-kiali
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - kiali.mycompany.com
    port:
      name: https-kiali
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-grafana-service
  namespace: istio-system
spec:
  gateways:
  - istio-grafana-gateway
  hosts:
  - istio-grafana.mycompany.com
  http:
  - match:
    - port: 80
    - port: 443
    route:
    - destination:
        host: grafana.istio-system.svc.cluster.local
        port:
          number: 3000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali-service
  namespace: istio-system
spec:
  gateways:
  - kiali-gateway
  hosts:
  - kiali.mycompany.com
  http:
  - match:
    - port: 80
    - port: 443
    route:
    - destination:
        host: kiali
        port:
          number: 20001
```

And this is what you see in the logs with 2 requests from the same browser:
```
[2020-01-22T19:35:52.078Z] "GET /public/img/icons_dark_theme/icon_team.svg HTTP/2" 304 - "-" "-" 0 0 1 1 "172.16.88.123" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0" "e3d71968-6fe0-96db-a2a5-8dbe77457234" "istio-grafana.mycompany.com" "10.233.68.35:3000" outbound|3000||grafana.istio-system.svc.cluster.local - 10.233.71.60:443 172.16.88.123:38172 istio-grafana.mycompany.com -
[2020-01-22T19:35:56.488Z] "GET / HTTP/2" 404 NR "-" "-" 0 0 0 - "172.16.88.123" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0" "0b570a95-eae4-9269-92b6-ebbe57bb8fbf" "kiali.mycompany.com" "-" - - 10.233.71.60:443 172.16.88.123:38172 istio-grafana.mycompany.com -
```
Note that both requests use the same client TCP port (port 38172 in this example), and that the 2nd request, to "kiali.mycompany.com" gets routed to the gateway URL "istio-grafana.mycompany.com".

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
~$ istioctl version --remote
client version: 1.4.3
control plane version: 1.4.3
data plane version: 1.4.3 (37 proxies)
~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

```
istioctl manifest apply --set values.global.mtls.enabled=true --set values.global.controlPlaneSecurityEnabled=true \
    --set values.grafana.enabled=true --set values.kiali.enabled=true --set values.tracing.enabled=true
```

**Environment where bug was observed (cloud vendor, OS, etc)**

On-premises cluster running on vSphere, installed using Kubespray.  K8S hosts use Ubuntu 18.04.

**Comment by dankirkpatrick** [comment]
By the way, I've been reporting on this bug for a very long time, and it keeps getting closed without being fixed.  Here are bug reports that appear to be the same bug:

https://github.com/istio/istio/issues/5829
https://github.com/istio/istio/issues/10313
https://github.com/istio/istio/issues/11509
https://github.com/istio/istio/issues/12500
https://github.com/istio/istio/issues/12603
https://github.com/istio/istio/issues/12663

**Comment by dankirkpatrick** [comment]
Any updates on this issue?  This renders the ingress gateway effectively useless for anyone with multiple ingress endpoints.

**Comment by dankirkpatrick** [comment]
Still no updates?

**Comment by han0110** [comment]
I have istio 1.5 installed and I ran into the exact same problem. (In my case I need a admin gateway authenticated by google oauth using `EnvoyFilter` and `oauth2-proxy`)

After digging into document, I found [404-errors-occur-when-multiple-gateways-configured-with-same-tls-certificate](https://istio.io/docs/ops/common-problems/network-issues/#404-errors-occur-when-multiple-gateways-configured-with-same-tls-certificate). Then I try to  use different certificate for my gateway and it works! (In istio 1.4 maybe you need to explicitly [enable SDS for ingress-gateway](https://istio.io/docs/tasks/traffic-management/ingress/secure-ingress-sds/#configure-a-tls-ingress-gateway-using-sds)) 

Here is my second `Gateway` config (the other one is the default one created when installing istio):
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: admingateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - admin.mydomain.com
    port:
      name: https-admin
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: istio-admingateway-certs
```
