### ISSUE TITLE
Component level hub/tag overrides are broken

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#20439]
Apply yaml:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  hub: istio-testing
  tag: istio-testing
  
  components:
    cni:
       enabled: true
       hub: gcr.io/istio-testing
       tag: latest
```

`ik manifest generate -f iop.yaml | rg istio-cni-node -C 50`:
```
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: istio-cni-node
  namespace: istio-system
  labels:
    k8s-app: istio-cni-node
    release: istio
spec:
  selector:
    matchLabels:
      k8s-app: istio-cni-node
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        k8s-app: istio-cni-node
      annotations:
        # This, along with the CriticalAddonsOnly toleration below,
        # marks the pod as a critical add-on, ensuring it gets
        # priority scheduling and that its resources are reserved
        # if it ever gets evicted.
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      hostNetwork: true
      tolerations:
        # Make sure istio-cni-node gets scheduled on all nodes.
        - effect: NoSchedule
          operator: Exists
        # Mark the pod as a critical add-on for rescheduling.
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          operator: Exists
      priorityClassName: system-cluster-critical
      serviceAccountName: istio-cni
      # Minimize downtime during a rolling upgrade or deletion; tell Kubernetes to do a "force
      # deletion": https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods.
      terminationGracePeriodSeconds: 5
      containers:
        # This container installs the Istio CNI binaries
        # and CNI network config file on each node.
        - name: install-cni
          image: "istio-testing/install-cni:istio-testing"
          imagePullPolicy: Always
          command: ["/install-cni.sh"]
```

Note the image here is wrong.

**Comment by howardjohn** [comment]
```
components:
  cni:
     enabled: true
values:
  cni:
     hub: gcr.io/istio-testing
     tag: latest
```

Seems to work

**Comment by elfinhe** [comment]
overrides ordering
In our operator specs:
values.global.component.values in iop.yaml > values.component.values in iop.yaml > default.yaml

In helm templates:
values.$component.image > values.$component.hub | values.$component.tag > values.global.hub | values.global.tag

https://github.com/istio/istio/blob/80fc771a52ec5ca90e37267a9822de3d95e41a69/manifests/istio-cni/templates/daemonset.yaml#L55-L59

https://github.com/istio/istio/blob/20cac5b98782a90bc8b4ed52dbbc148f7bf1f355/manifests/istio-control/istio-discovery/templates/deployment.yaml#L65-L69

**Comment by elfinhe** [comment]
To be clear, with the PR above,

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  hub: istio-spec.hub
  tag: istio-spec.tag
  components:
    pilot:
      enabled: true
      hub: values.pilot.hub
      tag: values.pilot.tag
    cni:
       enabled: true
       hub: values.cni.hub
       tag: values.cni.tag
```

CNI will use  image: "values.cni.hub/install-cni:values.cni.tag"
Pilot will use image: "istio-spec.hub/pilot:istio-spec.tag" because the template choose to use Values.global.hub first.
