### ISSUE TITLE
OPERATOR disablePolicyChecks changing value not working

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#20456]
**Bug description**

Can seem to get disablePolicyChecks to switch back and forth using the operator controller ICP.  (Not istioctl)

**Expected behavior**

disablePolicyChecks can be changed from default of true to false and back again via the operator ICP.

**Steps to reproduce the bug**

### Starting with defaults

start with default icp values:
```
  tag: 1.4.3
  profile: default
  values:
    global:
      disablePolicyChecks: true
    mixer:
      policy:
        enabled: false
    pilot:
      enabled: true
```
Check the istio cm for the right value:
`k get cm -n istio-system istio -o yaml | grep "    disablePolicyChecks:"`
`disablePolicyChecks: true`

Now try to change the disablePolicyChecks to false
```
  tag: 1.4.3
  profile: default
  values:
    global:
      disablePolicyChecks: false
    mixer:
      policy:
        enabled: true
    pilot:
      enabled: true
```
Check the istio cm for the right value:
`k get cm -n istio-system istio -o yaml | grep "    disablePolicyChecks:"`
`disablePolicyChecks: true`

The value does not change in the configmap.

### Starting with non-defaults

start with default icp values:
```
  tag: 1.4.3
  profile: default
  values:
    global:
      disablePolicyChecks: false
    mixer:
      policy:
        enabled: true
    pilot:
      enabled: true
```
Check the istio cm for the right value:
`k get cm -n istio-system istio -o yaml | grep "    disablePolicyChecks:"`
`disablePolicyChecks: true`

Wrong value, should be false.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.4.3

**How was Istio installed?**

1.4.3 Operator deployed

**Environment where bug was observed (cloud vendor, OS, etc)**

IBM Cloud
