### ISSUE TITLE
GRPC Authorization not working as documented

### ISSUE THREAD

**Issue by cmanzi** [istio/istio#20479]
**Bug description**
I've created an AuthorizationPolicy for a GRPC service to allow another service to make calls to a certain GRPC endpoint, and it is returning a 403 RBAC access denied, when according to the docs it seems that the policy should allow it. The GRPC port is named `grpc` in the target Service, and istio seems to be properly detecting the protocol, so I don't think it's being treated as HTTP traffic.

Per the [docs](https://istio.io/docs/reference/config/security/authorization-policy/#Operation):

> For gRPC service, this should be the fully-qualified name in the form of “/package.service/method”

This is my Authz policy:
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: thanos-store
spec:
  selector:
    matchLabels:
      app: thanos-store
  rules:
  - from:
    - source:
        principals:
          - "<trust_domain>/ns/monitoring/sa/thanos-querier"
    to:
    - operation:
        methods: ["/thanos.Store/Info"]
        ports: ["10901"]
```
This produces the following logs:
(Thanos querier)
```
{"address":"<ip_addr>:10901","caller":"storeset.go:429","component":"storeset","err":"getting metadata: fetching store info from <ip_addr>:10901: rpc error: code = PermissionDenied desc = RBAC: access denied","level":"warn","msg":"update of store node failed","ts":"2020-01-24T16:14:03.687768263Z"}
```
(Envoy)
```
{"bytes_sent":"0","upstream_cluster":"-","downstream_remote_address":"<ip_addr>:60730","authority":"<ip_addr>:10901","path":"/thanos.Store/Info","protocol":"HTTP/2","upstream_service_time":"-","upstream_local_address":"-","duration":"0","downstream_local_address":"<ip_addr>:10901","upstream_transport_failure_reason":"-","route_name":"-","response_code":"200","user_agent":"grpc-go/1.22.1","response_flags":"-","start_time":"2020-01-24T16:14:03.685Z","method":"POST","request_id":"13bfa298-1d2b-4d68-8517-4f6fd71c5865","upstream_host":"-","x_forwarded_for":"-","requested_server_name":"outbound_.10901_._.thanos-store.monitoring.svc.cluster.local","bytes_received":"0","istio_policy_status":"-"}
```

If I change the Authz policy to this, however, it succeeds:
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: thanos-store
spec:
  selector:
    matchLabels:
      app: thanos-store
  rules:
  - from:
    - source:
        principals:
          - "<trust_domain>/ns/monitoring/sa/thanos-querier"
    to:
    - operation:
        methods: ["POST"]
        ports: ["10901"]
```

Since I was a little confused about the wording in the docs, I also tried the following for the `methods` field: "/thanos.Store/Info/POST", "/thanos.Store/POST".

**Expected behavior**
The Authz policy allows the GRPC traffic from the specified principal.

**Steps to reproduce the bug**
Create a test GRPC service and client, apply the above Istio authz policy with mTLS set to ISTIO_MUTUAL in the namespace. 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio: 1.4.3
kube: 1.15.7

**How was Istio installed?**
Helm template/FluxCD

**Environment where bug was observed (cloud vendor, OS, etc)**
Kops - AWS
