### ISSUE TITLE
v2 metrics missing destination labels for non-mesh destination

### ISSUE THREAD

**Issue by Stono** [istio/istio#20538]
**Bug description**
We have a service on our cluster, which does not have sidecars, named `solr`, the simplistic request flow looks like this:

`[search-one | istio-proxy] --> [solr]`

In v1 metrics, from the source reporter (`search-one`) you can see the metrics were accurately labeled:

<img width="1667" alt="Screenshot 2020-01-26 at 10 28 05" src="https://user-images.githubusercontent.com/1486729/73133864-9589ea80-4026-11ea-9d8f-69f1d1d655cb.png">

In v2 metrics, again from the source reporter (`search-one`) you can see that all of the destination labels are missing:

<img width="1663" alt="Screenshot 2020-01-26 at 10 28 45" src="https://user-images.githubusercontent.com/1486729/73133866-aa667e00-4026-11ea-8e04-7174489e2d0b.png">

I can only presume this is because the destination doesn't have a sidecar so some sort of metadata is not being propagated correctly.    Here are the details of the destination service (solr) if it helps:

```
❯ k -n search-solr get svc solr
NAME   TYPE           CLUSTER-IP   EXTERNAL-IP   PORT(S)        AGE
solr   LoadBalancer   10.192.1.7   10.193.0.9    80:30293/TCP   323d
```

```
❯ k -n search-solr get ep solr
NAME   ENDPOINTS                                      AGE
solr   10.194.31.6:80,10.194.40.3:80,10.194.42.5:80   323d
```

```
❯ k -n search-solr get destinationrule disable-mtls-to-solr -o yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: disable-mtls-to-solr
  namespace: search-solr
spec:
  host: solr
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 2147483646
        http2MaxRequests: 2147483646
        idleTimeout: 30m
        maxRequestsPerConnection: 2147483646
        maxRetries: 2147483646
      tcp:
        maxConnections: 2147483646
        tcpKeepalive:
          interval: 30s
          time: 30s
    tls:
      mode: DISABLE
```

```
❯ k -n search-solr get virtualservice solr -o yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: solr
  namespace: search-solr
spec:
  hosts:
  - solr
  - solr.search-solr.prod.k8.atcloud.io
  http:
  - retries:
      attempts: 3
      retryOn: connect-failure,refused-stream,unavailable,cancelled,resource-exhausted,retriable-status-codes
    route:
    - destination:
        host: solr
      weight: 100
    timeout: 6000s
```

**Expected behavior**
Destination labels to be correct for services on the cluster regardless of if those services have sidecars.

**Steps to reproduce the bug**
See above

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4.3

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
