### ISSUE TITLE
couldn't upgrade EnvoyFilter with new version

### ISSUE THREAD

**Issue by nadendlaprasad** [istio/istio#20640]
Hi,

I am trying to upgrade envoy filter to new version, but couldn't able to get it work

Older version of Envoy Filter

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: test-envoy-filter
spec:
  filters:
  - listenerMatch:
      portNumber: 80
      listenerType: GATEWAY # will match with the inbound listener for ingress gateway:8080
      listenerProtocol: HTTP
    filterName: envoy.lua
    filterType: HTTP
    filterConfig:
      inlineCode: |
            -- Called on the response path.
            function envoy_on_response(response_handle)
                local headers = response_handle:headers()
                headers:add("X-Envoy-Ingress", os.getenv("HOSTNAME"))
                headers:add("X-SPRK-Ingress", "good")
            end
```

New version of Envoy Filter

````
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: test-envoy-filter
spec:
  configPatches:
    # The first patch adds the lua filter to the listener/http connection manager
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        portNumber: 80
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.router"
    patch:
      operation: INSERT_BEFORE
      value: # lua filter specification
       name: envoy.lua
       config:
         inlineCode: |
            -- Called on the response path.
            function envoy_on_response(response_handle)
                local headers = response_handle:headers()
                headers:add("X-Envoy-Ingress", os.getenv("HOSTNAME"))
                headers:add("X-test-Ingress", "good")
            end
````

Older version is working very well but not the new version. can you please tell me what's wrong with the new version?

**Comment by nmnellis** [comment]
related https://github.com/istio/istio/issues/19549

**Comment by devstein** [comment]
@nadendlaprasad @nmnellis What was the resolution to this? I'm facing the same issue

**Comment by nmnellis** [comment]
@devstein i dont have an example directly for lua filters but i do have working ones for grpc2json
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: user-management
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              name: envoy.router
      portNumber: 8080
    patch:
      operation: INSERT_BEFORE
      value:
        config:
          convertGrpcStatus: true
          printOptions:
            alwaysPrintPrimitiveFields: false
            preserveProtoFieldNames: false
          protoDescriptorBin: <BINARY_HERE>
          services:
          - summaft.user.v2.UserManagementAPI
        name: envoy.grpc_json_transcoder
  workloadSelector:
    labels:
      app.kubernetes.io/name: user-management
```
