### ISSUE TITLE
SDS ingress TLS not working (404) when multiple gateways configured with different secrets

### ISSUE THREAD

**Issue by balamuru** [istio/istio#20661]
**Bug description**
[istio-dump.tar.gz](https://github.com/istio/istio/files/4131186/istio-dump.tar.gz)

When I configure multiple (gateway - virtual service) pairs in a namespace, each pointing to basic HTTP services, only one service becomes accessable. Calls to the other (typically, the second configured) return 404. If the first gateway is deleted, the second service then becomes accesible

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Multiple TLS configurations in different gateways should co-exist

**Steps to reproduce the bug**
* Deploy 2  simple services (such as httpbin, nodejs etc). 
* Create certs (using the mtls-go tool) and upload secrets to the cluster (somehost-credential and otherhost-credential)
* Associate each service to a different gateway and virtual secret
* Associate each gateway to a secret (making sure not to assign gateways to the same secret)
* Ensure that the secrets are propagated
```
[ocadmin@cmsplavm224 junk]$ kubectl logs -n istio-system $(kubectl get pod -l istio=ingressgateway -n istio-system -o jsonpath='{.items[0].metadata.name}') -c ingress-sds
.
.
.
2020-01-29T21:56:45.044519Z	info	sdsServiceLog	CONNECTION ID: router~192.168.97.151~istio-ingressgateway-69b58578fc-zlpbx.istio-system~istio-system.svc.cluster.local-4, RESOURCE NAME: somehost-credential, EVENT: pushed key/cert pair to proxy

2020-01-29T21:57:29.052850Z	info	sdsServiceLog	CONNECTION ID: router~192.168.97.151~istio-ingressgateway-69b58578fc-zlpbx.istio-system~istio-system.svc.cluster.local-3, RESOURCE NAME: somehost2-credential, EVENT: connection is terminated: rpc error: code = Canceled desc = context canceled
2020-01-29T21:57:29.052892Z	info	sdsServiceLog	Received empty resource name from "router~192.168.97.151~istio-ingressgateway-69b58578fc-zlpbx.istio-system~istio-system.svc.cluster.local"
2020-01-29T21:57:29.052898Z	error	sdsServiceLog	Remote side closed connection
2020-01-29T22:12:43.386797Z	info	sdsServiceLog	CONNECTION ID: router~192.168.97.151~istio-ingressgateway-69b58578fc-zlpbx.istio-system~istio-system.svc.cluster.local-5, RESOURCE NAME: otherhost-credential, EVENT: pushed key/cert pair to proxy

2020-01-29T22:13:27.399304Z	info	sdsServiceLog	CONNECTION ID: router~192.168.97.151~istio-ingressgateway-69b58578fc-zlpbx.istio-system~istio-system.svc.cluster.local-4, RESOURCE NAME: somehost-credential, EVENT: connection is terminated: rpc error: code = Canceled desc = context canceled
2020-01-29T22:13:27.399341Z	info	sdsServiceLog	Received empty resource name from "router~192.168.97.151~istio-ingressgateway-69b58578fc-zlpbx.istio-system~istio-system.svc.cluster.local"

```

* Make calls that you would expect to succeed (using the mapped HTTPS port obtained below)
```
[ocadmin@cmsplavm224 junk]$ kc get svc istio-ingressgateway -n istio-system
NAME                   TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                                                                                                                      AGE
istio-ingressgateway   LoadBalancer   10.96.88.186   <pending>     15020:31532/TCP,80:32368/TCP,443:31918/TCP,15029:32594/TCP,15030:31691/TCP,15031:31880/TCP,15032:30829/TCP,15443:30617/TCP   46h

```

* The following output will result
** WORKING (THIS  WAS CONFIGURED FIRST **
```
[ocadmin@cmsplavm224 junk]$ curl -v -k --noproxy "*"  https://cmsplavm224.oma2hpe.lan:31918/fooa      
* About to connect() to cmsplavm224.oma2hpe.lan port 31918 (#0)
*   Trying 10.2.125.225...
* Connected to cmsplavm224.oma2hpe.lan (10.2.125.225) port 31918 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=other.host.com,O=Dis,L=Springfield,ST=Denial,C=US
* 	start date: Jan 29 22:04:24 2020 GMT
* 	expire date: Feb 07 22:04:24 2021 GMT
* 	common name: other.host.com
* 	issuer: CN=other.host.com,O=Dis,ST=Denial,C=US
> GET /fooa HTTP/1.1
> User-Agent: curl/7.29.0
> Host: cmsplavm224.oma2hpe.lan:31918
> Accept: */*
> 
< HTTP/1.1 200 OK
< x-powered-by: Express
< content-type: text/html; charset=utf-8
< content-length: 24
< etag: W/"18-qN7KJMo1QAhzIcYWh4eTqRZdsMk"
< date: Wed, 29 Jan 2020 22:34:13 GMT
< x-envoy-upstream-service-time: 2
< server: istio-envoy
< 
Hello foo from Server A
* Connection #0 to host cmsplavm224.oma2hpe.lan left intact
[ocadmin@cmsplavm224 junk]$ 
```

** NOT WORKING (THIS WAS CONFIGURED SECOND)**

```
[ocadmin@cmsplavm224 junk]$ curl -v -k --noproxy "*"  https://cmsplavm224.oma2hpe.lan:31918/status/418
* About to connect() to cmsplavm224.oma2hpe.lan port 31918 (#0)
*   Trying 10.2.125.225...
* Connected to cmsplavm224.oma2hpe.lan (10.2.125.225) port 31918 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=other.host.com,O=Dis,L=Springfield,ST=Denial,C=US
* 	start date: Jan 29 22:04:24 2020 GMT
* 	expire date: Feb 07 22:04:24 2021 GMT
* 	common name: other.host.com
* 	issuer: CN=other.host.com,O=Dis,ST=Denial,C=US
> GET /status/418 HTTP/1.1
> User-Agent: curl/7.29.0
> Host: cmsplavm224.oma2hpe.lan:31918
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< date: Wed, 29 Jan 2020 22:15:29 GMT
< server: istio-envoy
< content-length: 0
< 

```
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
[ocadmin@cmsplavm224 junk]$ istioctl version --remote
client version: 1.4.3
citadel version: 1.4.3
galley version: 1.4.3
ingressgateway version: 1.4.3
nodeagent version: 
nodeagent version: 
pilot version: 1.4.3
policy version: 1.4.3
sidecar-injector version: 1.4.3
telemetry version: 1.4.3
data plane version: 1.4.3 (11 proxies)

```

```
ocadmin@cmsplavm224 junk]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-10T03:03:57Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

```

**How was Istio installed?**
```istioctl manifest apply --set profile=sds```

**Environment where bug was observed (cloud vendor, OS, etc)**
Kubeadm \ upstream kubernetes

** Gateway / Virtual Service Config ** 
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mygateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: "somehost-credential" # must be the same as secret
    hosts:
    - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - "*"
  gateways:
  - mygateway
  http:
  - match:
    - uri:
        prefix: /status
    - uri:
        prefix: /delay
    route:
    - destination:
        port:
          number: 8000
        host: httpbin
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mygateway-nodejs
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: "otherhost-credential" # must be the same as secret
    hosts:
    - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nodejs
spec:
  hosts:
  - "*"
  gateways:
  - mygateway-nodejs
  http:
  - match:
    - uri:
        prefix: /fooa
    route:
    - destination:
        port:
          number: 8080
        host: nodejs


---
```
