### ISSUE TITLE
Istio is not able to route on a header set using Rule.

### ISSUE THREAD

**Issue by ademariag** [istio/istio#20839]
**Bug description**

Istio is not able to route on a header set using Rule.

with the following rule I can inject a new header in the request headers
```
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: auth-headers
spec:
  request_header_operations:
  - name: X-company
    values:
    - request.auth.claims["org_human_identifier"] ##("westeros")
```

However I am not able to then make routing decisions:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: echo-server-svc
spec:
  hosts:
  - echo-server.poc03.svc.cluster.local
  http:
  - match:
    - name: header
      headers:
        x-company:
          exact: westeros
    route:
    - destination:
        host: echo-server.poc03.svc.cluster.local
        subset: westeros
  - route:
    - destination:
        host: echo-server.poc03.svc.cluster.local
        subset: devtesting
```

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: echo-server
spec:
  host: echo-server.poc03.svc.cluster.local
  subsets:
  - name: westeros
    labels:
      org: westeros
  - name: devtesting
    labels:
      org: devtesting
```

Example echo-server output

```
Request served by echo-server-devtesting-5d7bfd6884-hd94p .  <- devtesting subset

HTTP/1.1 GET /echo/dddd

Host: poc03.mydomain
[cut]
X-Auth: eXXXXXXXXXXXXXXXX
[cut]
X-Company: westeros
```

**Expected behavior**

I expect requests to be route based on the `X-Company` header added by the rule

**Steps to reproduce the bug**

Apply above configurations and use CURL to test the endpoint.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.7-gke.2", GitCommit:"96c91b15a936b36701e8704844bc356862440a21", GitTreeState:"clean", BuildDate:"2019-12-13T12:37:28Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

```
istioctl version --remote
client version: 1.4.3
citadel version: 1.4-alpha.400f9e3780af62b1742372085b45317d8fbe9810
galley version: 1.4-alpha.400f9e3780af62b1742372085b45317d8fbe9810
ingressgateway version: 1.4-alpha.17f6bfc3d7121ad527c2d617ffc27c758d6a7241
ingressgateway version: 1.4-alpha.17f6bfc3d7121ad527c2d617ffc27c758d6a7241
ingressgateway version: 1.4-alpha.17f6bfc3d7121ad527c2d617ffc27c758d6a7241
pilot version: 1.4-alpha.400f9e3780af62b1742372085b45317d8fbe9810
policy version: 1.4-alpha.17f6bfc3d7121ad527c2d617ffc27c758d6a7241
sidecar-injector version: 1.4-alpha.400f9e3780af62b1742372085b45317d8fbe9810
telemetry version: 1.4-alpha.17f6bfc3d7121ad527c2d617ffc27c758d6a7241
data plane version: 1.4-alpha.17f6bfc3d7121ad527c2d617ffc27c758d6a7241 (67 proxies)
```

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE
