### ISSUE TITLE
AKS NSG when Grafana and Kiali are Disabled in Istio Config

### ISSUE THREAD

**Issue by michaelschmit** [istio/istio#20845]
**Bug description**
When deploying istio into AKS with grafana and kiali disabled, I am still seeing the NSG being updated to allow the traffic which seems wrong to me. I know grafana and kiali are disabled properly via the config because the deployment doesn't exist in AKS under the istio-system namespace. If I enable grafana and kiali I see those deployments.

Per Microsoft (@paulbouwer),

> Good catch on the invalid NSG security rules 👍. There are a few things happening here.
> 
> From: AKS | Concepts | Azure network security groups
> 
>     To filter the flow of traffic in virtual networks, Azure uses network security group rules. These rules define the source and destination IP ranges, ports, and protocols that are allowed or denied access to resources. Default rules are created to allow TLS traffic to the Kubernetes API server. As you create services with load balancers, port mappings, or ingress routes, AKS automatically modifies the network security group for traffic to flow appropriately.
> 
> So, AKS will automatically update the NSG with the port and ip address of a Kubernetes Service of type LoadBalancer.
> 
> If you look at the values.yaml file used to deploy the istio ingress gateway by the istioctl manifest command, you will notice a bunch of hard-coded ports. These include the ones you reference.
> 
> So even though you disable grafana and kiali, and in the case of the AKS docs, we enable them, but do not provide public access, we still find that the NSG contains the ports for these services. The ip address/port combo are not connected to either grafana and/or kialia via the istio ingress gateway, but for correctness should not be in the NSG.
> 
> Could you log this as an issue in the Istio project, since my expectation would be that if I have a value of grafana.ingress.enabled=false in the grafana values.yaml, that the grafana port is not added to the gateways.istio-ingressgateway.ports list, and subsequently is not added to the NSG by AKS.
> 

> Another option is to patch the istio.aks.yaml contents in the AKS Istio Install docs.
> 
> So add gateways.istio-ingressgateway.ports under the spec.values section:

```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  # Use the default profile as the base
  # More details at: https://istio.io/docs/setup/additional-setup/config-profiles/
  profile: default
  values:
    gateways:
      istio-ingressgateway:
        ports:
        - port: 15020
          targetPort: 15020
          name: status-port
        - port: 80
          targetPort: 80
          name: http2
        - port: 443
          name: https
        # This is the port where sni routing happens
        - port: 15443
          targetPort: 15443
          name: tls
```

> I still believe that the Istio install should not render the grafana port if grafana.ingress.enabled=false is set. The above gives you flexibility in what ports you want exposed via the ingress gateway.

**Expected behavior**
If Grafana and Kiali are disabled via the istio config, the ports (and therefore the NSGs) are not opened up.

**Steps to reproduce the bug**
Disable the deployments of Grafana and Kiali via the istio config.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
istioctl version
client version: 1.4.3
control plane version: 1.4.3
data plane version: 1.4.3 (1 proxies)
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"c52f59bbba5fbf21fbb18e9a06f96e563fe4c20a", GitTreeState:"clean", BuildDate:"2020-01-31T20:00:26Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

```
helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

**How was Istio installed?**
Using istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
Cloud Vendor - Azure AKS
