### ISSUE TITLE
Retries is not working

### ISSUE THREAD

**Issue by rahul0403** [istio/istio#20928]
This is my yaml file for retry i am not getting 10s of delay when member get abort with 502, it is giving response in very quick time:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: retry-member
spec:
  hosts:
  - member
  http:
  - fault:
      delay:
        percent: 100
        fixedDelay: 2s
      abort:
        httpStatus: 502
        percent: 50
    route:
    - destination:
        host: member
    retries:
      attempts: 10
      perTryTimeout: 1s
      retryOn: 5xx
```
