### ISSUE TITLE
Istio Rule Handler lookup error 

### ISSUE THREAD

**Issue by WoodProgrammer** [istio/istio#20975]
Hello all, 
I'm working on the ISTIO version 1.14 . I have implemented rules, handlers shown as below. But telemetry returning issues about parsing i think . How I can solve that issue . There is my manifest files :
 
##rule.yaml
```
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: promhttp
  namespace: istio-system
spec:
  match: destination.service.host == "pricing.myservice.local"
  actions:
  - handler: promhandler
    instances: [ requestduration ]

```
#### handler.yaml
```
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: promhandler
  namespace: istio-system
spec:
  compiledAdapter: prometheus
  params:
    metrics:
    - name: request_count
      instance_name: requestcount.instance.istio-system
      kind: COUNTER
      label_names:
      - destination_service
      - destination_version
      - response_code
    - name: request_duration
      instance_name: requestduration.instance.istio-system
      kind: DISTRIBUTION
      label_names:
      - destination_service
      - destination_version
      - response_code
      buckets:
        explicit_buckets:
          bounds: [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10]

```
###instance.yaml
```
apiVersion: config.istio.io/v1alpha2
kind: instance
metadata:
  name: requestduration
  namespace: istio-system
spec:
  compiledTemplate: metric
  params:
    value: response.duration | "0ms"
    dimensions:
      destination_service: destination.service.host | "unknown"
      destination_version: destination.labels["version"] | "unknown"
      response_code: response.code | 200
    monitored_resource_type: '"UNSPECIFIED"'
```
Telemetry is returning this issue :: 

```
warn	input set condition evaluation error: id='8', error='lookup failed: 'destination.service.host''
```

Thanks for your helping .
