### ISSUE TITLE
Multiple clusters - istio-ingressgateway is unavailable

### ISSUE THREAD

**Issue by xichengliudui** [istio/istio#21018]
**Bug description**
```
[root@node1 istio-1.4.3]# kubectl get pods --context=$CTX_CLUSTER2 -n istio-system -l istio=ingressgateway
NAME                                    READY   STATUS    RESTARTS   AGE
istio-ingressgateway-5d474c5799-qrx5m   0/1     Running   0          13m
```
following the example deployment, the result is a failure, i've set up cluster1 watch cluter2.

**Expected behavior**
the deployment was successful

**Steps to reproduce the bug**
https://istio.io/docs/setup/install/multicluster/shared-gateways/#setup-cluster-1-primary
follow the steps in the link for deployment

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
v1.4.3

**How was Istio installed?**
Multi-cluster deployment

**Environment where bug was observed (cloud vendor, OS, etc)**
Centos7

**Comment by xichengliudui** [comment]
```
 meshNetworks: |-
    # Network config
    networks:
      network1:
        endpoints:
        - fromRegistry: Kubernetes
        gateways:
        # cluster1 Node ip
        - address: 10.20.1.100
          # for port 443
          port: 31697
      network2:
        endpoints:
        - fromRegistry: n2-k8s-config
        gateways:
        # cluster1 Node ip
        - address: 10.20.1.103
          # for port 443
          port: 31218
```
i updated network1 and network2 and values.yaml，the `istio-ingressgateway` type is `NodePort`, so `address = 10.20.1.xxx` and `port = 31xxx`
is that the reason?
looking forward to your reply. Thank you!
