### ISSUE TITLE
Please support http2 between envoys as a first class citizen

### ISSUE THREAD

**Issue by Stono** [istio/istio#21036]
**Describe the feature request**
On our cluster, http2 can make a real difference.  This graph demonstrates the following service chain:

`consumer-gateway` -> `sauron-web` -> `search-one` -> `solr`

It shows p99 response times from the perspective of `consumer-gateway`, as you can see the notable improvement when an `EnvoyFilter` is applied to upgrade the connections to http2.

<img width="801" alt="Screenshot 2020-02-11 at 18 30 24" src="https://user-images.githubusercontent.com/1486729/74269705-cdb94a80-4d01-11ea-8f3d-ca13e3a319e1.png">

This is a particular "high connection churn" set of services, on an mtls cluster, so I'm correlating the notable drop to mtls handshakes in the connection churn, as well as reduced load on proxies.

It feels to me like if Istio is really prioritising being performant, making http2 the default between envoys is frankly a no brainer.  At the least, properly supporting this through a `DestinationRule` configuration item to make it easily accessible.

**Describe alternatives you've considered**
As we deploy some 350 applications, in 350 namespaces, the only way for us to apply this is to create an EnvoyFilter in the `istio-system` namespace _for each service_, targeting its cluster.  It is also difficult to do as our application pipelines do not have permission to deploy resources into the `istio-system` namespace, so we'd be introducing a security issue to work around this.

We could create a controller, which watches for istio-enabled deployments and mutates an EnvoyFilter with all permutations of istio-enabled `EDS` upstreams.  This works around the deployment issue, but it feels dirty, and that `EnvoyFilter` will be huge, and i'm concerned about pilot discovery config churn.

We cannot create it globally, and apply it without a service match as we have a handful of services that are non-http2 compliant so the requests to those will fail.  If `EnvoyFilter` allowed me to match on `EDS`, and exclude `ORIGINAL_DST`, that may well give me a work around - but currently it doesn't.

I'm also extremely worried about prolific use of `EnvoyFilters` in production considering the extremely low level nature of the API.  Especially creating 100's of them.

**Additional Information**
This is an example of an `EnvoyFilter` I am using to enable h2:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  namespace: istio-system
  name: h2-platform-testing
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      context: SIDECAR_OUTBOUND
      cluster:
        service: app.platform-testing.svc.cluster.local
    patch:
      operation: MERGE
      value:
        http2_protocol_options: { max_concurrent_streams: 47707 }
```
