### ISSUE TITLE
PodDisruptionBudget for istio-sidecar-injector has wrong matchLabels

### ISSUE THREAD

**Issue by haf** [istio/istio#21031]
**Bug description**

The pod disruption budget for sidecar-injector doesn't properly select the pod. Event:

```
istio-system   0s          Normal    NoPods     poddisruptionbudget/istio-sidecar-injector No matching pods found
```

Solution:

```
--- a/src/Services/istio/k8s/template/istio-sidecar-injector-poddisruptionbudget.yaml
+++ b/src/Services/istio/k8s/template/istio-sidecar-injector-poddisruptionbudget.yaml
@@ -14,6 +14,6 @@ spec:
   minAvailable: 1
   selector:
     matchLabels:
-      app: sidecar-injector
+      app: sidecarInjectorWebhook
       release: istio
       istio: sidecar-injector
```

**Expected behavior**

**Steps to reproduce the bug**
install istio

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4.3

**How was Istio installed?**
istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
-

**Comment by mat285** [comment]
I've also seen this. The label on the pods is `app=sidecarInjectorWebhook`

**Comment by uncycler** [comment]
I have the same issue with 1.5.1 as well. And the Istiod pdb is also wrong, the selector is matching on "release" which is not part of istiod template metadata.

**Comment by howardjohn** [comment]
Thanks for the reports! Not only is this fixed in 1.6 but we even have testing this time to ensure we do not regress: https://github.com/istio/istio/blob/c0680c17d65da6c217620b3e8c466083927b5b25/operator/cmd/mesh/manifest-generate_test.go#L533

**Comment by js-timbirkett** [comment]
Whilst it's great that it's fixed in 1.6... this really isn't helpful to those of us lagging behind on upgrades who can't simply tear the mesh down and re-create it.

For anyone who ends up here, in 1.4.x it can be solved with an overlay:
```
spec:
  autoInjection:
    components:
      injector:
        enabled: true
        k8s:
          replicaCount: 2
          overlays:
            - kind: PodDisruptionBudget
              name: istio-sidecar-injector
              patches:
                - path: .spec.selector.matchLabels.app
                  value: sidecarInjectorWebhook
.....
.....
```

I would say that, as it eventually gets fixed, this might actually cause a problem at that point, so make sure to do plenty of inspection of the `istioctl manifest generate -f ...` prior to applying any changes. As I moved from Helm to `istioctl` and eventually to the `IstioOperator` I've found other peculiar things with mesh configs, default DestinationRules, Gateway objects that get created. I ended up with multiple pdb's for `istio-ingressgateway`. So there are plenty of strange differences between the Helm charts and the charts used by `istioctl`. Oh well... all good fun...
