### ISSUE TITLE
Document how to customise the tracing span names

### ISSUE THREAD

**Issue by objectiser** [istio/istio#21100]
**Describe the feature request**

Envoy supports the ability to define the span (operation) name to be used for a route. This can be leveraged using an EnvoyFilter to allow Istio users to customise the span names. Should this be documented? Or wait until a higher level representation (e.g. tools based on OpenAPI) are developed?

**Additional context**
Topic was discussed on yesterday's Policy and Telemetry WG call.

For example, the following trace shows that the operation can be specified and associated with both the client and server spans:

![istiogw-decorator-operation](https://user-images.githubusercontent.com/164562/74432996-775e2000-4e57-11ea-85de-af7bc0678c39.png)

This was achieved using Istio 1.4.3 with a modified bookinfo-gateway.yaml:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bookinfo-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - "*"
  gateways:
  - bookinfo-gateway
  http:
  - match:
    - uri:
        exact: /productpage
      name: mainpage
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: 9080
    name: productpage
```
and deploying the following EnvoyFilter:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: bookinfo-gateway-sampling
  namespace: istio-system
spec:
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: GATEWAY
      routeConfiguration:
        portNumber: 80
        vhost:
          name: "*:80"
          route:
            name: "productpage.mainpage"
    patch:
      operation: MERGE
      value:
        decorator:
          operation: checkProduct
```
cc @douglas-reid
