### ISSUE TITLE
IPWhitelisting/Blacklisting not working

### ISSUE THREAD

**Issue by linuxbsdfreak** [istio/istio#21102]
**Bug description**

[ ] Configuration Infrastructure
[X ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Expected behavior**
IP whitelisting and Blacklisting should work when running the example from
https://istio.io/docs/tasks/policy-enforcement/denial-and-list/#ip-based-whitelists-or-blacklists

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

 istioctl version --remote
````
client version: 1.4.3
control plane version: 1.4.3
data plane version: 1.4.3 (5 proxies)
````

kubectl version
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-21T22:17:28Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

```
istioctl manifest apply --set profile=demo --set values.gateways.istio-ingressgateway.sds.enabled=true --set values.gateways.istio-egressgateway.enabled=true --set values.global.mtls.auto=true --set values.global.mtls.enabled=false --set values.global.controlPlaneSecurityEnabled=true --set values.gateways.istio-ingressgateway.externalTrafficPolicy=Local --set values.global.proxy.accessLogFile="/dev/stdout" --set values.global.disablePolicyChecks=false
```

**Environment where bug was observed (cloud vendor, OS, etc)**

Gardener K8s cluster

** Issue**

After performing the install of Istio and following the docs. I have observed that Istio blacklist/whitelist does not work with ELB/NLB launched via Istio Ingress Gateway on AWS. 

Following is the config i tried the suggestion based on 
https://discuss.istio.io/t/istio-ingress-ip-whitelisting/2670/12

Following is the config i am trying in the the istio-system namespace
```
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: blacklistip
spec:
  compiledAdapter: listchecker
  params:
    #providerUrl: "https://raw.github.com/repo/blacklist.txt?token=xxxxxx"
    overrides: ["xxx.xxx.xxx.xxx/25"]]
    blacklist: true
    entryType: IP_ADDRESSES
---
apiVersion: config.istio.io/v1alpha2
kind: instance
metadata:
  name: sourceip-blacklist
spec:
  compiledTemplate: listentry
  params:
    value: request.headers["x-forwarded-for"] | "unknown"
    #value: request.headers["x-real-ip"] | "unknown"
    #value: source.ip | ip("0.0.0.0")
    #value: request.headers["x-envoy-external-address"] | "0.0.0.0"
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: checkip-blacklist
spec:
  match: source.labels["istio"] == "ingressgateway"
  #match:  (source.labels["istio"] | "") == "ingressgateway"  && (request.headers["x-envoy-external-address"] | "") !=""
  actions:
  - handler: blacklistip
    instances: [ sourceip-blacklist ]
```

I have an app running in another namespace which i can access and would like to restrict access to to. I have a long list of IP ranges that i need to block. 

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gw-helloworld-v1
  namespace: hello-v1
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "helloworld-v1.istio.example.com"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: "wildcard-ssl-secret"
    hosts:
    - "helloworld-v1.istio.example.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-helloworld-v1
  namespace: hello-v1
spec:
  hosts:
  - "helloworld-v1.istio.example.com"
  gateways:
  - gw-helloworld-v1
  http:
  - match:
    - uri:
        exact: /
    rewrite:
      uri: /hello
    route:
    - destination:
        host: helloworld.hello-v1.svc.cluster.local
        port:
          number: 5000
```

NOTE: I am terminating TLS on the Istio Ingress Gateway with support from the gardener annotations which automatically manages the TLS certs. 

For some reason the real client header is never forwarded for blocking. I have even added the details to the issue. https://github.com/istio/istio/issues/20034

I am not aware if this is a bug or how i can fix this issue. Ideally i would like to use an ALB on AWS. However Istio lauches an ELB.  Could anyone share any experience of a working setup? 

Regards,
Kevin
