### ISSUE TITLE
IstioControlPlane add Pod Labels to k8s resource config

### ISSUE THREAD

**Issue by iusergii** [istio/istio#21103]
**Describe the feature request**
Extend KubernetesResource with option to add additional labels to Istio Pods. 

**Describe alternatives you've considered**
I started with adding additional labels to ingress gateway and tried to do it via _values.istio-ingressgateway.labels_.  And it fails in case there are any other label except: app,istio.

`istioctl manifest generate -f manifest.yaml:
input file failed validation with the following errors: unknown field "Service" in v1alpha1.GatewayLabelsConfig`

I also tried via _unvalidatedValues.istio-ingressgateway.labels_ but additional labels don't generated.

[ * ] Configuration Infrastructure
[ ] Docs
[ * ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by esnible** [comment]
Can you attach _manifest.yaml_ to this instance so that I can see what you are trying?

**Comment by iusergii** [comment]
@esnible I'm trying to add extra labels to istio-ingressgateway pods. Istio v.**1.4.2**. I didn't find it in [k8s resources](https://istio.io/docs/reference/config/istio.operator.v1alpha12.pb/#KubernetesResourcesSpec) so trying to override via **values**/**unvalidatedValues**. 
This one fails on validation with error:  _input file failed validation with the following errors: unknown field "Service" in v1alpha1.GatewayLabelsConfig_
```yaml 
kind: IstioControlPlane
spec:
  profile: default
  defaultNamespace: istio-system 
  gateways: []
  values:    
    gateways:
      istio-ingressgateway:
        labels:
          app: istio-ingressgateway
          istio: ingressgateway
          Product: Mesh                    
          Service: Istio
```
This one doesn't add extra labels:

```yaml 
kind: IstioControlPlane
spec:
  profile: default
  defaultNamespace: istio-system 
  gateways: []
  unvalidatedValues:
    gateways:
      istio-ingressgateway:
        labels:
          app: istio-ingressgateway
          istio: ingressgateway
          Product: Mesh                    
          Service: Istio
```
