### ISSUE TITLE
istioctl analyze: Detect multiple gateways using the same wildcard TLS certificate

### ISSUE THREAD

**Issue by k3a** [istio/istio#21158]
**Describe the feature request**

It would be useful if "istioctl analyze" could detect the istio-common TLS problems:
- https://istio.io/docs/ops/common-problems/network-issues/#404-errors-occur-when-multiple-gateways-configured-with-same-tls-certificate
- https://istio.io/docs/ops/common-problems/network-issues/#port-conflict-when-configuring-multiple-tls-hosts-in-a-gateway

Those problems are very nasty. 

In the browser I started seeing HTTP 404 suddenly for the new subdomain, while the same URL worked perfectly when tried using curl. Then I tried two more browsers. One displayed 404 for the first domain, the other one for the second domain. It didn't make sense. I couldn't figure out why that happened. Finally, after some websearching, I found that in the Common problems listed.

**Additional context**

**Comment by esnible** [comment]
This seems like an common problem that deserves an analyzer.  I will work on it or find someone to work on it.

@k3a Can you attach to this issue a pair of Gateway and pair of VirtualService YAML, similar to what you used when you encountered this problem, that can be used as a test case?

@frankbu You wrote the docs for this, https://github.com/istio/istio.io/commit/ca10cc03d884d3cd251cd75b1a2cb94739354a9a , if you have an example set of gateways and virtual services I can also use yours to test an analyzer.

**Comment by k3a** [comment]
I had two Gateways using the same wildcard `*.domain.com` certificate.
They looked almost identical, maybe I had TLS redirect enabled in one of them (can't remember now).

I was also thinking that maybe by doing that, I could see the traffic separately in Kiali. So that each "area of concern" would have it's own gateway. I didn't expect that I can't use the same certificate by two different gateways. 

But the core idea was that one Gateway would be enforcing TLS (by redirecting http->https) while the other one would allow both http/https. Consider the following scenario:

1. I have a wildcard certificate for `*.domain.com`
2. I have API clients where some of them use `http://svc.domain.com` while others use `https://svc.domain.com`. Of course none follows redirects. I want to let all types of clients work without enforcing HTTPS.
3. I also have an admin interface at `admin.example.com`, I want to use the same wildcard certificate but I want to force all clients to HTTPS because those clients are browsers and there is a login form with passwords.

I still don't know how to implement this scenario (other than using two Gateways, each using a separate ingressgateway service and deployment, thus having two loadbalancer IPs). VirtualService doesn't seem to support httpsRedirect, only Gateway can do that.

[domain-com-gateway.yaml.txt](https://github.com/istio/istio/files/4314899/domain-com-gateway.yaml.txt)

**Comment by esnible** [comment]
Unassigning myself to focus in P1 items.

**Comment by An0nymous0** [comment]
same question

**Comment by zufardhiyaulhaq** [comment]
Hey folks, I can help creating analyzer for this one.

**Comment by esnible** [comment]
@zufardhiyaulhaq OK, I assigned this item to you, if you need someone to work with let me know and I will co-assign someone from the team.

**Comment by zufardhiyaulhaq** [comment]
@esnible is this https://istio.io/latest/docs/ops/common-problems/network-issues/#port-conflict-when-configuring-multiple-tls-hosts-in-a-gateway still be a common problem. I have similar use cases but found nothing all all works fine. my configuration

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: server-1-zufar-io-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "server-1.zufar.io"
    port:
      name: https-default
      number: 443
      protocol: HTTPS
    tls:
      credentialName: server-1-zufar-io-cert
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: server-1-zufardhiyaulhaq-tech-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "server-1.zufardhiyaulhaq.tech"
    port:
      name: https-default
      number: 443
      protocol: HTTPS
    tls:
      credentialName: server-1-zufardhiyaulhaq-tech-cert
      mode: SIMPLE
```

curl test:
```
infrastructure $ curl https://server-1.zufar.io/ -v         
*   Trying 10.200.100.110...
* TCP_NODELAY set
* Connected to server-1.zufar.io (10.200.100.110) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Unknown (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Client hello (1):
* TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=server-1.zufar.io
*  start date: Dec  3 14:21:57 2020 GMT
*  expire date: Dec  4 14:22:57 2020 GMT
*  subjectAltName: host "server-1.zufar.io" matched cert's "server-1.zufar.io"
*  issuer: CN=infra-lab Intermediate CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* Using Stream ID: 1 (easy handle 0x558b3ea09580)
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
> GET / HTTP/2
> Host: server-1.zufar.io
> User-Agent: curl/7.58.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
< HTTP/2 200 
< x-powered-by: Express
< content-type: application/json; charset=utf-8
< content-length: 1078
< etag: W/"436-UQnE4jlQUiRqdmiGb09Qp4vhXfY"
< date: Thu, 03 Dec 2020 16:32:47 GMT
< x-envoy-upstream-service-time: 4
< server: istio-envoy
< 
{
  "path": "/",
  "headers": {
    "host": "server-1.zufar.io",
    "user-agent": "curl/7.58.0",
    "accept": "*/*",
    "x-forwarded-for": "10.244.2.0",
    "x-forwarded-proto": "https",
    "x-request-id": "8abc909f-6f6b-4381-8242-68bad34212a0",
    "path-without-params": "/",
    "content-length": "0",
    "x-envoy-internal": "true",
    "x-forwarded-client-cert": "By=spiffe://cluster.local/ns/istio-testing/sa/default;Hash=6f0db3c373f9366018ab38b9272d75bbb4128a9e7934bd124c981e859bf39765;Subject=\"\";URI=spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account",
    "x-b3-traceid": "4223f3f82435dbb30c491d68ad938f42",
    "x-b3-spanid": "216260a75f077a1a",
    "x-b3-parentspanid": "0c491d68ad938f42",
    "x-b3-sampled": "0"
  },
  "method": "GET",
  "body": "",
  "fresh": false,
  "hostname": "server-1.zufar.io",
  "ip": "10.244.2.0",
  "ips": [
    "10.244.2.0"
  ],
  "protocol": "https",
  "query": {},
  "subdomains": [
    "server-1"
  ],
  "xhr": false,
  "os": {
    "hostname": "helloworld-654cbf76bd-wksnn"
  },
  "connection": {}
* Connection #0 to host server-1.zufar.io left intact

infrastructure $ curl https://server-1.zufardhiyaulhaq.tech/ -v
*   Trying 10.200.100.110...
* TCP_NODELAY set
* Connected to server-1.zufardhiyaulhaq.tech (10.200.100.110) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Unknown (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Client hello (1):
* TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=server-1.zufardhiyaulhaq.tech
*  start date: Nov  7 10:40:38 2020 GMT
*  expire date: Feb  5 10:40:38 2021 GMT
*  subjectAltName: host "server-1.zufardhiyaulhaq.tech" matched cert's "server-1.zufardhiyaulhaq.tech"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* Using Stream ID: 1 (easy handle 0x55ce9ba03580)
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
> GET / HTTP/2
> Host: server-1.zufardhiyaulhaq.tech
> User-Agent: curl/7.58.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
< HTTP/2 200 
< x-powered-by: Express
< content-type: application/json; charset=utf-8
< content-length: 1102
< etag: W/"44e-NJYRiAyCHRu1SOxC0huO38xTdI0"
< date: Thu, 03 Dec 2020 16:33:11 GMT
< x-envoy-upstream-service-time: 9
< server: istio-envoy
< 
{
  "path": "/",
  "headers": {
    "host": "server-1.zufardhiyaulhaq.tech",
    "user-agent": "curl/7.58.0",
    "accept": "*/*",
    "x-forwarded-for": "10.244.2.1",
    "x-forwarded-proto": "https",
    "x-request-id": "73638909-4b97-44ab-a656-379303df484c",
    "path-without-params": "/",
    "content-length": "0",
    "x-envoy-internal": "true",
    "x-forwarded-client-cert": "By=spiffe://cluster.local/ns/istio-testing/sa/default;Hash=ce9bd536777c722ce19a875a5af9eb32260e9b23c458fb276cfc8b5349480a1b;Subject=\"\";URI=spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account",
    "x-b3-traceid": "5d43f8e6defc53c562deb35ec2bb1186",
    "x-b3-spanid": "fe472b25a9847edf",
    "x-b3-parentspanid": "62deb35ec2bb1186",
    "x-b3-sampled": "0"
  },
  "method": "GET",
  "body": "",
  "fresh": false,
  "hostname": "server-1.zufardhiyaulhaq.tech",
  "ip": "10.244.2.1",
  "ips": [
    "10.244.2.1"
  ],
  "protocol": "https",
  "query": {},
  "subdomains": [
    "server-1"
  ],
  "xhr": false,
  "os": {
    "hostname": "helloworld-654cbf76bd-wksnn"
  },
  "connection": {}
* Connection #0 to host server-1.zufardhiyaulhaq.tech left intact
}#
```

**Comment by esnible** [comment]
@zufardhiyaulhaq I don't use certificates often.

If you can't reproduce this we can close it as fixed, and if someone is having this problem they are sure to re-open it.  How does that sound?

**Comment by zufardhiyaulhaq** [comment]
@esnible make sense, I will skip creating analyzer for this cases then.

**Comment by uvw** [comment]
@zufardhiyaulhaq Seems like there is an issue creep here.

I cannot reproduce https://istio.io/docs/ops/common-problems/network-issues/#port-conflict-when-configuring-multiple-tls-hosts-in-a-gateway

However, I can provide you an isolated example of https://istio.io/docs/ops/common-problems/network-issues/#404-errors-occur-when-multiple-gateways-configured-with-same-tls-certificate if you want. It is still the case with v1.7.5 at least.

**Comment by zufardhiyaulhaq** [comment]
@uvw same I also cannot reproduce this. can you provide the example. I have internal cluster that support creating certificate, don't worry.

**Comment by frankbu** [comment]
If it's true that https://istio.io/docs/ops/common-problems/network-issues/#port-conflict-when-configuring-multiple-tls-hosts-in-a-gateway has been fixed, we should also remove it from the common-problems doc.

@howardjohn Do you know if this is indeed no longer a problem?

**Comment by zufardhiyaulhaq** [comment]
folks currently I am working on multiple gateway with the same certificate. I stuck on getting `PILOT_SCOPE_GATEWAY_TO_NAMESPACE` istiod environment variable on the analyzer.

this environment variable will determine how the analyzer match the gateway. for example if `PILOT_SCOPE_GATEWAY_TO_NAMESPACE` is set to false (default value)

```
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway-01-test-03
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: "test-03-wildcard-cert"
    hosts:
    - "01.test-03.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway-02-test-03
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
    type: internal
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: "test-03-wildcard-cert"
    hosts:
    - "02.test-03.com"
```

this configuration will have validation error since both gateway object point into single gateway deployment/workload with same credential name. 

If we set `PILOT_SCOPE_GATEWAY_TO_NAMESPACE` to true, the configuration passing the analyzer because both gateway object is pointing to different gateway deployment/workload.
