### ISSUE TITLE
Prometheus operator install

### ISSUE THREAD

**Issue by Norbo11** [istio/istio#21187]
Hi - I was wondering what is the status on Prometheus Operator support, as I can't seem to get it to work. I am trying to apply the following manifest:

```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  profile: default
  values:
    prometheusOperator:
      createPrometheusResource: true
```
But `istioctl` complains about not knowing of the `createPrometheusResource` key.

I tried installing the Helm chart manually using:

`helm install istio-prometheus-operator install/kubernetes/operator/charts/istio-telemetry/prometheus-operator --set values.prometheusOperator.createPrometheusResource=true`

But this gives me `Error: no objects visited`.

Using `helm template` gives me an empty string.

I have successfully installed Prometheus Operator into my cluster, I am trying to use the above to generate the appropriate ServiceMonitor resources to scrape Istio components.

This seems to be a pretty undocumented feature - the only real bit of information I could find is the PR which introduced this chart: https://github.com/istio/installer/pull/71

Is there a supported way of installing the Prometheus Operator resources for scraping Istio components? Thanks.

**Comment by vflopes** [comment]
I just need the service monitors and I'm looking for how to generate them with istioctl, no docs found.

**Comment by estei** [comment]
@vflopes If you still havent found out how to get the servicemonitors installed via istioctl.

After some sleuthing around in the source, I got it running, by enabling it in my manifest file.

```yaml
kind: IstioControlPlane
spec:
  values:
    prometheusOperator:
      enabled: true
```

Then I had to run istioctl with `--force` to make it ignore the unrecognized setting.
@Norbo11 `--force` should also be the key for you to move on I think, together with an `enabled: true`

```sh
istioctl manifest apply --filename manifest.yaml  --force
```
I think the syntax to do it without a file is something like 
```sh
istioctl manifest apply --set values.prometheusOperator.enabled=true --force
```
[Values file for istio prometheus operator chart](https://github.com/istio/installer/blob/master/istio-telemetry/prometheus-operator/values.yaml)

**Comment by irizzant** [comment]
I confirm the above workaround with `prometheusOperator` and `--force` option is correctly generating the `serviceMonitor` resources, it would be preferable getting rid of the not recognized setting though.

Moreover, when `serviceMonitor`s are created, prometheus starts complaining of missing secrets:
```
level=error ts=2020-02-21T13:55:40.183Z caller=manager.go:123 component="scrape manager" msg="error creating new scrape pool" err="error creating HTTP client: unable to load specified CA cert /etc/prometheus/secrets/istio.prometheus/root-cert.pem: open /etc/prometheus/secrets/istio.prometheus/root-cert.pem: no such file or directory" scrape_pool=istio-system/kubernetes-pods-secure-monitor/0
```
because `kubernetes-services-secure-monitor` `kubernetes-services-secure-monitor` require `istio.prometheus` secret to scrape, while their "twins" `kubernetes-services-monitor` and `kubernetes-services-monitor` don't.

One solution could be deploying the Prometheus operator in the same namespace as Istio and then providing `istio.prometheus` as additional secret to mount through `kubernetes-services-secure-monitor`

**Comment by ostromart** [comment]
Most likely this is just a matter of a missing schema entry in values_types.proto. I'll investigate for 1.6 and backport if that's the case.

**Comment by mizhkeao** [comment]
hi, I'm running into the same issues with prometheus operator install. I am using the same command "istioctl manifest apply --set values.prometheusOperator.enabled=true --force" but am unable to see the operator being created?

**Comment by Dev25** [comment]
On istioctl 1.5.0 it's `--set addonComponents.prometheusOperator.enabled=true`, that will create the `ServiceMonitor` resources.

That being said the docs were recently updated highlighting another approach of scraping the _istio prometheus_ using prometheus federation better suited for long term production metrics (reduced cardinality)

https://istio.io/docs/ops/best-practices/observability/

**Comment by irizzant** [comment]
Sorry where is `--set addonComponents.prometheusOperator.enabled=true` documented?
I checked [here](https://istio.io/docs/reference/config/istio.operator.v1alpha1/) and [here](https://istio.io/docs/ops/best-practices/observability/) but it's missing.

Moreover, the recording rules reported [here](https://istio.io/docs/ops/best-practices/observability/#workload-level-aggregation-via-recording-rules) seem to be a reasonable default, why aren't they included in the default Istio Prometheus installation?

**Comment by rpocase** [comment]
@mizhkeao As far as I can tell, the istio integration ONLY creates the ServiceMonitor. You will need to install Prometheus Operator before applying the new manifest.

**Comment by framled** [comment]
This install the prom-operator, but first you need to install the CRDs

```yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  values:
    prometheusOperator:
      enabled: true
      createPrometheusResource: true
```

**Comment by adamrbennett** [comment]
> This install the prom-operator, but first you need to install the CRDs
> 
> ```yaml
> apiVersion: install.istio.io/v1alpha2
> kind: IstioControlPlane
> spec:
>   values:
>     prometheusOperator:
>       enabled: true
>       createPrometheusResource: true
> ```

This doesn't work for me in 1.5, although it used to (probably in 1.4.4). Now it appears you need to add the config @Dev25 mentioned. For example:

```yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioOperator
spec:
  addonComponents:
    prometheusOperator:
      enabled: true

  values:
    prometheus:
      enabled: false
    prometheusOperator:
      createPrometheusResource: true
```

**Comment by bangau1** [comment]
For istio-1.5.0, this can works (I only tried to generate the manifest via ` istioctl manifest generate --set profile=default -f istio-operator.yaml`, with the istio-operator.yaml below:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  addonComponents:
    grafana:
      enabled: false
    prometheus:
      enabled: false
    prometheusOperator:
      enabled: true
    kiali:
      enabled: false
```

Wondering though if it is possible I can only generate the `ServiceMonitor` needed to scrape the istio metrics? Currently I use another prometheus-operator (installed separately, not from istioctl). Is it possible via istioctl to create the `ServiceMonitor` without creating the prometheus-operator instance?
