### ISSUE TITLE
istioctl/operator k8s overlay patch can't delete map

### ISSUE THREAD

**Issue by jamielennox** [istio/istio#21201]
**Bug description**

I'm attempting to use the patch functionality to install the ingress-gateway as a daemonset instead of a deployment. I've got that patches set up like: 

```yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  profile: minimal
  gateways:
    enabled: true
    components:
      egressGateway:
        enabled: false
      ingressGateway:
        enabled: true
        k8s:
          overlays:
            - apiVersion: apps/v1
              kind: Deployment
              name: istio-ingressgateway
              patches:
                - path: spec.template.spec.affinity
                - path: kind
                  value: DaemonSet
  values:
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: false
```

based on documentation I would expect 
```
 - path: spec.template.spec.affinity
```
to remove the affinity information from the spec, however this doesn't work and doesn't return an error because it doesn't match the check in https://github.com/istio/istio/blob/11a9ebe9efcbff61b77b6acfa9786f108685cc6a/operator/pkg/tpath/tpath.go#L281

It's not as simple as changing `isSliceOrPtrInterface` to accept a `reflect.Map` or adding a new case there as it's relied on by other code.

**Expected behavior**

There should be no affinity information in the manifest as the patch removed it. Otherwise an error might be useful. 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

`master`

**How was Istio installed?**

For testing using `istioctl manifest generate -f test-profile.yaml`

**Comment by porkbones** [comment]
In my case, it was spec.strategy preventing me from deploying Ingress Gateway as a Daemonset. I was able to workaround this by specifying:

`          overlays:
          - apiVersion: extensions/v1beta1
            kind: Deployment
            name: istio-ingressgateway
            patches:
              - path: kind
                value: DaemonSet
              - path: spec.strategy
                value: {}`

**Comment by williansvi** [comment]
I'm having a similar problem... Prometheus deployment in generated manifest looks like:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
    release: istio
  name: prometheus
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: prometheus
        release: istio
    spec:
      containers:
      - args:
        - --storage.tsdb.retention=6h
        - --config.file=/etc/prometheus/prometheus.yml
        image: docker.io/prom/prometheus:v2.15.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: 9090
        name: prometheus
        ports:
        - containerPort: 9090
          name: http
        readinessProbe:
          httpGet:
            path: /-/ready
            port: 9090
        resources:
          requests:
            cpu: 10m
        volumeMounts:
        - mountPath: /etc/prometheus
          name: config-volume
        - mountPath: /etc/istio-certs
          name: istio-certs
```

And i want to set prometheus retention time to 1h. For this purpose i've wrote a patch.yaml file:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  addonComponents:
    prometheus:
      k8s:
        overlays:
          - apiVersion: apps/v1
            kind: Deployment
            name: prometheus
            patches:
              - path: spec.template.spec.containers.args.[--storage.tsdb.retention=6h]
                value: "--storage.tsdb.retention=1h"
```
But when i run, 

`istioctl manifest generate -f patch.yaml`

No changes are made on manifests.

Any suggestion?
