### ISSUE TITLE
Istio Ingress Gateway listens on 0.0.0.0:15090 

### ISSUE THREAD

**Issue by mattcaron** [istio/istio#21202]
**Bug description**

According to `istioctl proxy-config listener`, a default istio-ingressgateway install listens on 0.0.0.0:80 and 0.0.0.0:15090.

The former is not problematic - it is an example, and is easily modified for purpose or deleted.

However, the latter is proving quite difficult because I cannot seem to figure out how to turn it off. It doesn't seem to do anything when one connects from the world (it just times out), but something is still listening, and there doesn't seem to be a way to turn it off. There should be, because extra ports listening are security.

As I understand it, 15090 is open so Prometheus can query stats. However, that should not be passed through to the outside worlds. It seems that the other open statistics ports behave this way, and this one should as well.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

The default configuration should only have the example port 80 listening.

**Steps to reproduce the bug**

1. Install Istio per the instructions.
2. Run `istioctl proxy-config listener <pod>` and see the listeners.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

Istioctl: 1.4.3
Kubectl: 1.16.3

**How was Istio installed?**

istioctl manifest generate --set profile=sds \
         --set values.sidecarInjectorWebhook.rewriteAppHTTPProbe=true \
         --set values.gateways.istio-ingressgateway.sds.enabled=true \
         --set values.tracing.enabled=true \
         --set values.grafana.enabled=true \
         --set values.kiali.enabled=true \
         --set "values.kiali.dashboard.grafanaURL=http://grafana:3000" \
         --set "values.kiali.dashboard.jaegerURL=http://jaeger-query:16686" \
| kubectl apply -f 

**Environment where bug was observed (cloud vendor, OS, etc)**

Amazon EKS.

**Comment by howardjohn** [comment]
The istio-ingressgateway service does not expose 15090 so I don't think this is something that can be hit externally

**Comment by mattcaron** [comment]
I don't think it can be hit externally. If you try, it just times out, the same as any other port that is not shown as open (say, like 789). Otherwise I would have flagged it as a security issue. It isn't, because the traffic is not connected to anything. But, it's still listening.

If I get the service, it says:
```
istio-ingressgateway   LoadBalancer   XXXX   XXXX 15020:31496/TCP,80:32610/TCP,443:31962/TCP,15029:32330/TCP,15030:30280/TCP,15031:31339/TCP,15032:31425/TCP,15443:32583/TCP   XX
```
So, not listening on 15090. But, all of these (except 443, which I added) are not listed by `proxy-config` - so why is 15090?

**Comment by howardjohn** [comment]
15090 is listening so prometheus can scrape it, but its not exposed in the service since it shouldn't be externally accessed.

The the ones are in the Service but not listening because you don't have a Gateway set up. Technically they don't need to be in the Service, I think we just put them there by default as they are common ports to use, so we don't want people to modify the Service every time they want to expose port 443.

**Comment by mattcaron** [comment]
I don't have a Gateway set up for 15090 either, but yet it's still listed. I only have one set up for 443 (which is also listening, as it should).

Here is my Gateway and VirtualService sections. This replaces the Port 80 default section:
```
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway
spec:
  selector:
    istio: ingressgateway  # use istio default ingress gateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: PASSTHROUGH
      hosts:
        - "*"
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gateway-route-port443
spec:
  hosts:
    - "*"
  gateways:
    - gateway
  tls:
    - match:
        - port: 443
          sni_hosts:
            - "*"
      route:
        - destination:
            host: firewall
```
