### ISSUE TITLE
Adding header-based routing EnvoyFilter patch discards per_filter_config for ext_authz

### ISSUE THREAD

**Issue by moritzheiber** [istio/istio#21213]
**Bug description**

We are trying to add a header-based filter for our default route prefix `/` to disable our external authorization, added via another patch to the `envoy.http_connection_manager` filter.

Basically, the intention is (pseudo-code):

```
if header == "something" and prefix == "/" then
  disable ext_authz
end
```
However, whenever we are trying to apply our patch, the instructions fail to show up and we are getting the following error on the proxy console:

```
[...][warning][config] [external/envoy/source/common/config/grpc_mux_subscription_impl.cc:82] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) 10.0.25.208_8080: Only one of typed_configs or configs can be specified, virtualInbound: Only one of typed_configs or configs can be specified
```

This verbatim Envoy configuration works correctly and we want to replicate its behavior using Istio `EnvoyFilter` resources:

```yaml
static_resources:
  listeners:
  - name: main
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 8080
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: auto
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                  headers:
                    - name: "some-header"
                      present_match: true
                per_filter_config:
                  envoy.ext_authz:
                    disabled: true
                route:
                  cluster: some-service
              - match:
                  prefix: "/"
                route:
                  cluster: some-service
          http_filters:
          - name: envoy.ext_authz
            typed_config:
              "@type": type.googleapis.com/envoy.config.filter.http.ext_authz.v2.ExtAuthz
              http_service:
                server_uri:
                  uri: http://auth-service:8000
                  cluster: auth-service
                  timeout: 5s
                path_prefix: "/auth"
                authorization_request:
                  allowed_headers:
                    patterns:
                    - exact: some-other-header
              failure_mode_allow: false
          - name: envoy.router
            typed_config: {}

  clusters:
  - name: some-service
    connect_timeout: 0.25s
    type: strict_dns # static
    lb_policy: round_robin
    load_assignment:
      cluster_name: some-service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: some-service
                port_value: 8080

  - name: auth
    connect_timeout: 0.25s
    type: strict_dns # static
    lb_policy: round_robin
    load_assignment:
      cluster_name: auth
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: auth
                port_value: 8000
```

So far, we've come up with the following `EnvoyFilter` object:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: some-service-filter
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/name: some-service
      app.kubernetes.io/instance: some-release
  configPatches:
    - applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_INBOUND
        routeConfiguration:
          portNumber: 8080
          vhost:
            name: inbound|http|8080
      patch:
        operation: MERGE
        value:
          match:
            headers:
              - name: some-header
                present_match: true
            prefix: /
          per_filter_config:
            envoy.ext_authz:
              disabled: true

    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
              subFilter:
                name: "envoy.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.ext_authz
          config:
            failure_mode_allow: false
            http_service:
              path_prefix: /auth
              server_uri:
                uri: http:/auth.auth.svc.cluster.local:8000
                cluster: outbound|8000||auth.auth.svc.cluster.local
                timeout: 5s
              authorization_request:
                allowed_headers:
                  patterns:
                    exact: "some-other-header"
```

But it yields the warning as mentioned in the abstract above.

We are clueless as to what's the reason for the omission and at this point we think it might actually be a bug in Istio's `EnvoyFilter` resource and how it applies to the underlying Envoy configuration.

**Expected behavior**

**Steps to reproduce the bug**

1. Apply the configuration as mentioned above.
2. Observe the proxy configuration not adopting the instructions.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
client version: 1.4.3
control plane version: 1.4.4
data plane version: 1.4.2 (5 proxies), 1.4.4 (2 proxies)
```

```
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

**How was Istio installed?**

Istio Helm chart

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS EKS running on Amazon Linux 2

**Comment by mayflower-markus** [comment]
This is most likely because the inboud already has a typed_per_filter config with options concerning the istio mixer component. You can check this by checking out the running envoy configuration of the istio-proxy.
Your EnvoyFilter Patch adds a per_filter_config on an envoy object that already has a typed_per_filter_config which is invalid.

The istio/api does not include the necessary protobuf definition though, to implement it as typed_per_filter_config.

Our workaround is this
```
        patch:
        {   
          operation: 'MERGE',
          value:
          {   
            typed_per_filter_config:
            {   
              "envoy.ext_authz":
              {   
                '@type': 'type.googleapis.com/google.protobuf.Struct',
                value:
                {   
                  disabled: true
                }   
              }   
            }   
          }   
        } 
```
Even though it defeats the purpose of a typed config.

**Comment by rshriram** [comment]
@mayflower-markus you are right in that the API has typed per-filter config in the routes and you are trying to add struct based config. To use a typed config, you need the type URL (which is kind of what you are specifying here). The problem in the code is that it has no way to dynamically import the protobufs for that type so that it can pack the binary config into XDS.  We have had to do ugly workarounds in code lik https://github.com/istio/istio/blob/master/pkg/config/xds/filter_types.go to make sure all the types are imported in code, so that when pilot tries to cast your text config into a config of a specific type, the go runtime has all the type data available.

**Comment by moritzheiber** [comment]
@mayflower-markus @rshriram Thank you for the hint, however, even with the added type definition the issue of "translating" the original Envoy configuration into a valid, accepted `EnvoyFilter` still persists unfortunately, as the `HTTP_ROUTE` object only supports `MERGE` as its operation and neither `INSERT_BEFORE` or `ADD`. And patching the default route will lead to `some-header` becoming a mandatory submission to reach any endpoint at all.

**Comment by mayflower-markus** [comment]
@rshriram Thanks for the insights! It's nice to know that we can use that with the 1.5 release
@moritzheiber If applicable, I think you could try to create a virtual service that matches on the header, give that route a name and then reference the route through the name in your envoyfilter config. This way the VirtualService creates the header match configuration.

**Comment by moritzheiber** [comment]
For anyone encountering the same issue, the solution is in [this comment](https://github.com/istio/istio/issues/21213#issuecomment-587511761) and the resulting YAML looks like this:

```yaml
typed_per_filter_config:
  envoy.ext_authz:
    "@type": type.googleapis.com/google.protobuf.Struct
    value:
      disabled: true
```

My overarching problem, translating the Envoy configuration into an Istio `EnvoyFilter` isn't solved by it, but it's not a bug.

**Comment by Eslamanwar** [comment]
@moritzheiber Did you figure out solution for your original issue as we are facing the same problem as we want to bypass the envoy.ext_authz

**Comment by moritzheiber** [comment]
This is what we came up with:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ext-authz
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/name: {{ include "<your-service>.name" . }} # Enter your service name here
      app.kubernetes.io/instance: {{ .Release.Name }}
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
              subFilter:
                name: "envoy.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.ext_authz
          config:
            filter_enabled: false # Change this to true to enable the whole filter
            failure_mode_allow: true # Change this to false to enable strict handling of connections
            http_service:
              path_prefix: /decisions
              server_uri:
                uri: <your-auth-service-uri-here>
                cluster: outbound|<port>||<your-auth-service-uri-here>
                timeout: 5s
```

Obviously, it's not "production ready", but the comments should tell you where to make the appropriate adjustments
