### ISSUE TITLE
when changing the configRootNamespace, default DR gets created in istio-system still that breaks all traffic to VS's pointing at DR subsets

### ISSUE THREAD

**Issue by jbilliau5668** [istio/istio#21216]
**Bug description**
I installed Istio 1.4.3 via helm template with the following flags:

--set global.mtls.auto=true --set global.configRootNamespace=istio-config --set gateways.enabled=true

Now, what gets created is this default DestinationRule:

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: default
  namespace: istio-system
spec:
  host: '*.local'
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```

The problem, per this page here (https://istio.io/docs/ops/best-practices/traffic-management/), is the order in which DR's are evaluated: client, server, root namespace. By changing the configRootNamespace to istio-config, that means that this rule is no longer a "root" rule, but now a "client" rule, in how it pertains to traffic originating from the ingress-gateway. 

Thus, if I try externally exposing a service, using the istio-ingressgateway as my ingress, and using a VirtualService and default DestinationRule with a subset specified, it isn't recognized and upon hitting the external URL i get a 503. The reason being that the ingress-gateway is using it's default DR above and ignoring the one in the "server" namespace. This is happening because I changed the rootNamespace and thus the default DR became a client DR and not a root DR, taking precedence over my server DR.

[ X ] Configuration Infrastructure
[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Default DestinationRule should not be configured to go to Release.Namespace, but configRootNamespace (in this case, istio-config instead of istio-system).

**Steps to reproduce the bug**
1.) Install Istio 1.4.3 (probably any 1.4.X release)
2.) Use ingress-gateway as your ingress for external traffic (in my case, I am routing to it from a ALB in AWS).
3.) Create a deployment, service, gateway, virtualservice, and destinationrule, pointing at a subset. Have the virtualservice route to that destinationrule subset, like this:

```
  spec:
    hosts:
    - test-rhino.rhino.svc.cluster.local
    http:
    - match:
      - uri:
          prefix: /
      route:
      - destination:
          host: test-rhino.rhino.svc.cluster.local
          subset: v1
        weight: 100
```

It won't work unless you delete the DR **default** in the _istio-system_ namespace. This rule should've been created in the _istio-config_ namespace since I was specifying that during install. If it would've, this problem wouldn't be happening since the **client** namespace of istio-system wouldn't have a DR in it, and thus would respect the DR in my **server** namespace specifying the subset.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

Istio version 1.4.3
K8 version 1.14
Helm version 3.0.2

**How was Istio installed?**

Helm template.

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS
