### ISSUE TITLE
EnvoyFilter workloadSelector not scoping to namespaces

### ISSUE THREAD

**Issue by nmnellis** [istio/istio#21271]
**Bug description**

EnvoyFilter workloadSelector lables does not scope the filter to its provided namespace, instead its applied to every namespace with the matching labels. I do not have any filters deployed in istio-system. I verified that filters were being applied via `istioctl proxy-config listeners` 

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: user-management
  namespace: namespace1
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/name: user-management
  filters:
  - listenerMatch:
      portNumber: 8080
      listenerType: SIDECAR_INBOUND
    insertPosition:
      index: BEFORE
      relativeTo: envoy.router
    filterName: envoy.grpc_json_transcoder
    filterType: HTTP
    filterConfig:
      convertGrpcStatus: True
      printOptions:
        alwaysPrintPrimitiveFields: False
        preserveProtoFieldNames: False
      services:  
      - summaft.user.v2.UserManagementAPI
      protoDescriptorBin: <BINARY>
---

apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: user-management
  namespace: namespace2
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/name: user-management
  filters:
  - listenerMatch:
      portNumber: 8080
      listenerType: SIDECAR_INBOUND
    insertPosition:
      index: BEFORE
      relativeTo: envoy.router
    filterName: envoy.grpc_json_transcoder
    filterType: HTTP
    filterConfig:
      convertGrpcStatus: True
      printOptions:
        alwaysPrintPrimitiveFields: False
        preserveProtoFieldNames: False
      services:  
      - summaft.user.v2.UserManagementAPI
      protoDescriptorBin: <BINARY>
```

seeing the filter from each namespace showing up in every pod
```json
                                {
                                    "name": "envoy.grpc_json_transcoder",
                                    "config": {
                                        "convertGrpcStatus": true,
                                        "printOptions": {
                                            "alwaysPrintPrimitiveFields": false,
                                            "preserveProtoFieldNames": false
                                        },
                                        "protoDescriptorBin": "<BINARY>",
                                        "services": [
                                            "summaft.user.v2.UserManagementAPI"
                                        ]
                                    }
                                },
                                {
                                    "name": "envoy.grpc_json_transcoder",
                                    "config": {
                                        "convertGrpcStatus": true,
                                        "printOptions": {
                                            "alwaysPrintPrimitiveFields": false,
                                            "preserveProtoFieldNames": false
                                        },
                                        "protoDescriptorBin": "<BINARY>",
                                        "services": [
                                            "summaft.user.v2.UserManagementAPI"
                                        ]
                                    }
                                },
                                {
                                    "name": "envoy.grpc_json_transcoder",
                                    "config": {
                                        "convertGrpcStatus": true,
                                        "printOptions": {
                                            "alwaysPrintPrimitiveFields": false,
                                            "preserveProtoFieldNames": false
                                        },
                                        "protoDescriptorBin": "<BINARY>",
                                        "services": [
                                            "summaft.user.v2.UserManagementAPI"
                                        ]
                                    }
                                },
```

**Expected behavior**

**Steps to reproduce the bug**

create envoy filters in two separate namespaces with same workload selectors and all pods with those selectors will have the filter
```sh
istioctl proxy-config listeners <podname> -o json -n <namespace>
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istioctl version --remote
client version: 1.4.5
control plane version: 1.4.5
data plane version: 1.4.5 (16 proxies)

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:54Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.8", GitCommit:"a9973cbb2722793e2ea08d20880633ca61d3e669", GitTreeState:"clean", BuildDate:"2020-02-07T00:50:57Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

Helm

**Comment by nmnellis** [comment]
upgrading to the new filter config worked 
```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: user-management
  namespace: namespace1
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/name: user-management
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        portNumber: 8080
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
              subFilter:
                name: "envoy.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.grpc_json_transcoder
          config:
            convertGrpcStatus: True
            printOptions:
              alwaysPrintPrimitiveFields: False
              preserveProtoFieldNames: False
            services:
            - summaft.user.v2.UserManagementAPI
            protoDescriptorBin: <BINARY>
```
