### ISSUE TITLE
VirtualService priority for gateway proxy

### ISSUE THREAD

**Issue by ydh926** [istio/istio#21302]
**Describe the feature request**
VirtualService priority for gateway proxy. 

**Describe alternatives you've considered**
For the gateway, there may be multiple vs rules. When the effective conditions overlap, it is difficult for users to control which one takes effect. Consider the following example:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    api_service: qz
  name: qz-55-demo
  namespace: gateway-system
spec:
  gateways:
  - demo
  hosts:
  - qatest.com
  http:
  - match:
    - uri:
        prefix: /qatest
    route:
    - destination:
        host: istio-e2e-app.gateway-demo.svc.cluster.local
        port:
          number: 80
        subset: dynamic-153-demo
```
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    api_service: qz
  name: qz-56-demo
  namespace: gateway-system
spec:
  gateways:
  - demo
  hosts:
  - qatest.com
  http:
  - match:
    - uri:
        prefix: /qatest/100
    route:
    - destination:
        host: istio-e2e-app.gateway-demo.svc.cluster.local
        port:
          number: 80
        subset: dynamic-154-demo
```
When ‘qatest / 100’ request come, routing behavior becomes unpredictable.

We can consider prioritizing vs resources to solve this problem.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
