### ISSUE TITLE
operator: pilot k8s overlays have no impact

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#21314]
```
  components:
    pilot:
      k8s:
        resources:
          requests:
            cpu: 2000m
```

has no impact

This is probably due to the istiod rename?
