### ISSUE TITLE
Istio 1.5 telem not setting canonical_service metric fields

### ISSUE THREAD

**Issue by jshaughn** [istio/istio#21324]
Using 2/20/20 dev build istio-1.5-alpha.c086a1cc8247d22c0778ba8f40ad95cf6797b0e2 on OpenShift 4.3.

It looks like the proxy is not getting passed down the expected labels from the pod.  Using bookinfo I can inspect the details-v1 pod (get pod <pod> -o yaml) and see:

```
 labels:
    app: details
    pod-template-hash: 78d78fbddf
    security.istio.io/tlsMode: istio
    service.istio.io/canonical-name: details
    service.istio.io/canonical-revision: v1
    version: v1
```

but looking at the proxy config (istioctl proxy-config bootstrap <same-pod>) I see:

```
"LABELS": {
  "app": "details",
  "pod-template-hash": "78d78fbddf",
  "version": "v1"
 },
```

This is likely why I get only "unknown" for both destination_canonical_service and source_canonical_service.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ X ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Fields should be filled with the proper values.

**Steps to reproduce the bug**
See above

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
see above

**How was Istio installed?**
istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
see above
