### ISSUE TITLE
Rate-Limiting policy is leaking traffic (344% more requests than expected)

### ISSUE THREAD

**Issue by marcusschiesser** [istio/istio#21339]
**Bug description**
With the book-info example and a custom load generator (traffic produced with [Vegeta](https://github.com/tsenart/vegeta/blob/master/README.md)), the rate-limiting does not work as expected and causes leakage.

**Expected behavior**
Rate-limiting should return 429 to those with no available quota requests.

**Steps to reproduce the bug**
1. Deploy a `maxAmount: 10` policy with `validDuration: 10s` which is affecting all services

```yaml
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: quotahandler
  namespace: istio-system
spec:
  compiledAdapter: memquota
  params:
    quotas:
    - name: requestcountquota.instance.istio-system
      maxAmount: 10
      validDuration: 10s
---
apiVersion: config.istio.io/v1alpha2
kind: instance
metadata:
  name: requestcountquota
  namespace: istio-system
spec:
  compiledTemplate: quota
  params:
    dimensions:
      source: request.headers["x-forwarded-for"] | "unknown"
      destination: destination.labels["app"] | destination.service.name | "unknown"
      destinationVersion: destination.labels["version"] | "unknown"
---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpec
metadata:
  name: request-count
  namespace: istio-system
spec:
  rules:
  - quotas:
    - charge: 1
      quota: requestcountquota
---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpecBinding
metadata:
  name: request-count
  namespace: istio-system
spec:
  quotaSpecs:
  - name: request-count
    namespace: istio-system
  services:
  - service: '*'
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: quota
  namespace: istio-system
spec:
  actions:
  - handler: quotahandler
    instances:
    - requestcountquota
```

2. Create a namespace and deploy the book-info example with sidecar injection enabled

```bash
$ kubectl create book-info
$ kubectl label ns book-info istio-injection=enabled
$ kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml
```

3. Deploy load generator using the following definition:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: loadgenerator
spec:
  replicas: 3
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        run: loadgenerator
    spec:
      containers:
      - name: loadgenerator
        image: peterevans/vegeta
        command: ["/bin/sh"]
        args: ["-c", "echo 'starts load generator';while true; do echo 'GET http://productpage:9080/productpage#' | vegeta attack -duration=30s -rate=3/s | vegeta report;done"]
```

4. Observe the statistics in Prometheus

I used the following query, which is selecting the traffic inside the book-info namespace with response code 200: 

```
sum(istio_requests_total{reporter="destination",destination_service_namespace="book-info",source_workload_namespace="book-info",response_code="200"}) -sum(istio_requests_total{reporter="destination",destination_service_namespace="book-info",source_workload_namespace="book-info",response_code="200"} offset 10s)
```

The resulting output graph is:
![Screen Shot 2020-02-20 at 10 46 26 AM](https://user-images.githubusercontent.com/15179503/74896092-4db07600-53ce-11ea-928f-e6ca24ad502a.png)

This shows that we get traffic with more than 10 requests within 10 seconds.

Also, If I inspect the total requests passed within a larger interval, the following output graph shows that at the end of the interval (02:42:00), the total number of passed requests is 6167:
![Screen Shot 2020-02-20 at 10 48 54 AM](https://user-images.githubusercontent.com/15179503/74896290-e5ae5f80-53ce-11ea-91af-fb85a98d53c1.png)

and the total number of requests passed requests at the beginning (02:39:00) is 5368:
![Screen Shot 2020-02-20 at 10 52 34 AM](https://user-images.githubusercontent.com/15179503/74896475-55244f00-53cf-11ea-963c-5e2d7dd5b939.png)

This shows that we have 6167 - 5368 = 799 requests in 3 minutes, which is 344% more than we expected using our policy (60*3=180 requests).

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```bash
$ istioctl version --remote
client version: 1.4.4
control plane version: 1.4.4
data plane version: 1.4.4 (11 proxies)
```

and

```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

```bash
$ kubectl apply -f install/kubernetes/istio-demo.yaml
```

**Environment where bug was observed (cloud vendor, OS, etc)**

Local two-node cluster running CentOS 7.6 and installed via kubeadm.
