### ISSUE TITLE
Support for request hedging

### ISSUE THREAD

**Issue by utahta** [istio/istio#21338]
**Describe the feature request**

Envoy supports [request hedging](https://www.envoyproxy.io/docs/envoy/v1.12.0/intro/arch_overview/http/http_routing.html#arch-overview-http-routing-hedging), which can reduce tail latency, from v1.11.0, but it looks like Istio doesn't support to generate such Envoy configuration.

Could this be supported?

Maybe related to https://github.com/istio/istio/issues/2857

**Comment by maxenglander** [comment]
I am also interested in this, would like to have this issue reopened. Thanks!

**Comment by Temikus** [comment]
Same here. Google is very eager to recommend request hedging to customers, e.g.: https://cloud.google.com/storage/docs/best-practices

Thus it would make a lot of sense if Istio supported it.

**Comment by Bennett-Lynch** [comment]
Also interested in this feature. Hedging can drastically reduce high-tail latency. Would like to be able to manage this with Istio than at the application layer.

**Comment by kaiburjack** [comment]
We are also interested in this. Currently, we workaround the missing Istio-native configuration via an EnvoyFilter.
(here a working filter installed on the sidecar for "Service A" for calls to "Service B"):
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: service-a-to-b-req-hedging
spec:
  workloadSelector:
    labels:
      app: service-a
  configPatches:
    - applyTo: VIRTUAL_HOST
      match:
        context: SIDECAR_OUTBOUND
        routeConfiguration:
          vhost:
            name: service-b.default.svc.cluster.local:80
      patch:
        operation: MERGE
        value:
          hedge_policy:
            hedge_on_per_try_timeout: true
```
