### ISSUE TITLE
Istio's AuthorizationPolicy doesn't look for JWT's arrays into nested objects

### ISSUE THREAD

**Issue by paolodedo** [istio/istio#21340]
Hello,

I want to report an issue found reading the JWT token by the AuthorizationPolicy-kind YAML.

Basically, if I provide some roles through an external IAM provider (Keycloak in this case) that belong to a realm, I have no way of reading them through Istio.

I believe there is a parsing error or no read is made into nested objects containing arrays. In fact:

1) my JWT token: (**"realm_access" -> "roles"** object)
```
...
  "realm_access": {
    "roles": [
      "TEST-READ",
      "offline_access",
      "uma_authorization",
      "user"
    ]
  },
  "resource_access": {
    "istio": {
      "roles": [
        "user"
      ]
    },
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "profile email",
...
```

2) my Istio's AuthorizationPolicy: (**- key: request.auth.claims[realm_access.roles]**)
```
apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
  name: "test-authorization-policy"
  namespace: dev
spec:
  selector:
    matchLabels:
      app: test
  rules:
  - to:
    - operation:
        methods: ["GET"]
        # paths: ["/test*"]
    when:
    - key: request.auth.claims[realm_access.roles]
      values: ["TEST-READ"]
```

_This way, my roles aren't read correctly and every request goes into 403 Forbidden._

**But, with this following configuration, it works correctly:**

1) my JWT token, customized with a mapper that directly exposes the nested object containing the Roles-array: (**"realm_roles_array"** object)
```
...
  "realm_access": {
    "roles": [
      "TEST-READ",
      "offline_access",
      "uma_authorization",
      "user"
    ]
  },
  "resource_access": {
    "istio": {
      "roles": [
        "user"
      ]
    },
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "profile email",
  "realm_roles_array": [
      "TEST-READ",
      "offline_access",
      "uma_authorization",
      "user"
    ],
...
```

2) my Istio's AuthorizationPolicy: (**- key: request.auth.claims[realm_roles_array]**)
```
apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
  name: "test-authorization-policy"
  namespace: dev
spec:
  selector:
    matchLabels:
      app: test
  rules:
  - to:
    - operation:
        methods: ["GET"]
        # paths: ["/test*"]
    when:
    - key: request.auth.claims[realm_roles_array]
      values: ["TEST-READ"]
```

Could you please fix this behaviour?

Thank you very much
