### ISSUE TITLE
ImagePullSecret type error.

### ISSUE THREAD

**Issue by xiesheng211** [istio/istio#21358]
**Bug description**
Running into issues when configuring `global.value.imagePullSecret`:

```
$ cat test.yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
   values:
      global:
         imagePullSecrets:
          - name: a
          - name: b

```
Run `istioctl manifest generate -f test.yaml` get:

```
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
  - name: map[name:a]             <==== Wrong name.
  - name: map[name:b]
metadata:
  name: istio-reader-service-account
  namespace: istio-system
  labels:
    app: istio-reader
    release: istio

```

[ ] Configuration Infrastructure
[ ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istioctl version
client version: 1.4.5
control plane version: 1.4.3
data plane version: 1.4.3 (1 proxies)

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
This should not have the `name` part. I have verified this is working correctly with 

```
cat <<EOF | ik manifest generate -d manifests -f - | grep apple
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
   values:
      global:
         imagePullSecrets:
          - apple
          - b
EOF
```

On istioctl 1.6
