### ISSUE TITLE
Istio sidecar stripping Expect: 100-Continue header. 

### ISSUE THREAD

**Issue by JagadeeshSreeram** [istio/istio#21382]
**Bug description**

While uploading a large file we want to first authenticate the request before accepting the data. When client send Expect: 100-Continue, we want to validate authenticate the request and return 401 if request is not valid . Since istio proxy strips off the Expect headers and sent 100-continue back by default, our server doesn't even know if client sent the Expect header.

It looks like envoy supports this feature as part of 
https://github.com/envoyproxy/envoy/pull/2497

But there is no way in istio to enable this. I tried writing Envoy filter , but it fails with below error

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: enable-expect-header-envoyfilter
  namespace: confighub
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:      
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager"
          proxy_100_continue: true

```

Error 

```
admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: envoy filter: missing filters
```

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
