### ISSUE TITLE
Gateway code keys on non-unique field, leading to cross namespace gateway conflicts

### ISSUE THREAD

**Issue by bappr** [istio/istio#21394]
**Bug description**

I am trying to setup a TCP gateway in order to expose externally my databases.
But I get `connection refused`.
I already have https gateway created and exposing port `80` and `443`.

_Note: Side Car Injection is disabled_

**Expected behavior**

Istio should route my traffic correctly.

**Steps to reproduce the bug**

Might be very related to my own installation.
But basically, this

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: postgres-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - postgres.cs.kintohub.com
    port:
      name: tcp
      number: 19420
      protocol: TCP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: postgres-vs
  namespace: be8ee44a-d2b1-47e4-9a35-3084274b255f
spec:
  gateways:
  - istio-system/postgres-gateway
  hosts:
  - postgres.cs.kintohub.com
  http:
  - match:
    - port: 19420
    route:
    - destination:
        host: cs-postgres
        port:
          number: 5432
```

does not work.

```
$ root@istio-ingressgateway-78bdcc5b68-b8d7s:/# nc -v postgres.cs.kintohub.com 19420
DNS fwd/rev mismatch: postgres.cs.kintohub.com != 220.224.220.35.bc.googleusercontent.com
postgres.cs.kintohub.com [35.220.224.220] 19420 (?) : Connection refused
```

This is not a firewall error, I tried with the IP of the pod from within cluster and still getting that issue.
Also, switching from `TCP` protocol to `HTTP` solve the `nc` issue.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ istioctl version --remote
ALL 1.3.5

$ Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-gke.33", GitCommit:"2c6d0ee462cee7609113bf9e175c107599d5213f", GitTreeState:"clean", BuildDate:"2020-01-15T17:47:46Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

```
Using the helm chart + ArgoCD
```

**Environment where bug was observed (cloud vendor, OS, etc)**

```
GKE
```

**Comment by bappr** [comment]
I found the issue here.
With `TCP` gateway, the gateway has to sit in the same namespace than the virtual service.
Is it a requirement? Cause all my http gateways are in the `istio-system` namespace (read somewhere it was better).

**Comment by hzxuzhonghu** [comment]
Change your tcp port from 19420 to 31400, if you have not changed any gateway config.

**Comment by bappr** [comment]
Hey @hzxuzhonghu 
I have changed it. The config is fine.
It works fine when the gateway is in the same namespace as the virtual service.

**Comment by howardjohn** [comment]
I have reproduced this, seems cross namespace is not working

**Comment by howardjohn** [comment]
The problem is we have a map with a non unique key: https://github.com/istio/istio/blob/05552aa05a71dca94403b9e2608a7f2d73352eb0/pilot/pkg/model/gateway.go#L51

In my specific case it can be fixed by removing the duplicate gateway in the other namespace (see my config below, 2 identical GW in different namespace):
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bookinfo-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 34000
      name: tcp
      protocol: TCP
    hosts:
    - "foo.bar"
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bookinfo-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 34000
      name: tcp
      protocol: TCP
    hosts:
    - "foo.bar"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - "foo.bar"
  gateways:
  - istio-system/bookinfo-gateway
  tcp:
  - match:
    - port: 34000
    route:
    - destination:
        host: httpbin
        port:
          number: 80

```

It is definitely a bug, that just may be a feasible workaround

**Comment by howardjohn** [comment]
Related: https://github.com/istio/istio/issues/24118

**Comment by howardjohn** [comment]
not stale..

**Comment by howardjohn** [comment]
should see if https://preliminary.istio.io/latest/docs/ops/common-problems/network-issues/#port-conflict-when-configuring-multiple-tls-hosts-in-a-gateway is still accurate today. If it still is, likely won't be once we fix this

**Comment by howardjohn** [comment]
not stale

**Comment by howardjohn** [comment]
I took a stab at fixing this, its actually not due to the nonunique key. We filter it here: https://github.com/istio/istio/blob/85eaf1d38fcedfd131bbb07d01c065fed26b8c2b/pilot/pkg/model/gateway.go#L145. If we don't filter it there, we actually end up with duplicate filter chains.

What we really want, is when two identical servers are created, they are aliases for each other. Such that a VS to foo/gw1 and another to VS bar/gw2 will merge.

Changes required:
* Change key from `*networking.Server` to something else. Likely equivalent to `networking.Server` (no pointer), except that cannot be a map key
* Stop filtering
* Change  `GatewayNameForServer` to return a list of gateways, rather than a single one, and update downstream calls.
  * need to ensure VS referencing both are not duplicated

**Comment by howardjohn** [comment]
We should make sure we handle HTTPS case as well:
```
servers:
- hosts:
  - '*.app.hidden.name.com'
  port:
    name: https-443-ingress-api-ingress-develop-0
    number: 443
    protocol: HTTPS
  tls:
    credentialName: app-hidden.name.com-tls
    mode: SIMPLE
---
servers:
- hosts:
  - '*.app.hidden.name.com'
  port:
    name: https
    number: 443
    protocol: HTTPS
  tls:
    credentialName: app-hidden.name.com-tls
    mode: SIMPLE
```
for example

Its tricky to do "Change key from `*networking.Server` to something else. " since a bunch of Server contains lists, etc.
