### ISSUE TITLE
'hub' value in IstioControlPlaneSpec is not honoured by sidecarInjector

### ISSUE THREAD

**Issue by bsnape** [istio/istio#21400]
**Bug description**
sidecarInjector does not honour the value of `hub` set in an IstioControlPlaneSpec config file and is set to `docker.io/istio`.

To override this, you must set the `hub` value globally in the `values` block (helm passthrough).

My use-case is that we must use a private registry which proxies requests upstream. 

I followed a similar issue #19468.

**Expected behavior**

Setting the value of `hub` at the top level of the yaml hierarchy should be honoured (?).

**Steps to reproduce the bug**

Compare two configs with `hub` set in different ways as described above.

`hub.yml`
```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
hub: private-hub.io/istio
tag: 1.4.5
spec:
  trafficManagement:
    enabled: false
  policy:
    enabled: false  
  telemetry:
    enabled: false
  security:
    enabled: false
  configManagement:
    enabled: false
  autoInjection:
    enabled: true
    components:
      injector:
        enabled: true
  gateways:
    enabled: false
  cni:
    enabled: false
  coreDNS:
    enabled: false
  values:
    prometheus:
      enabled: false
```

`globalhub.yml`:
```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
tag: 1.4.5
spec:
  trafficManagement:
    enabled: false
  policy:
    enabled: false  
  telemetry:
    enabled: false
  security:
    enabled: false
  configManagement:
    enabled: false
  autoInjection:
    enabled: true
    components:
      injector:
        enabled: true
  gateways:
    enabled: false
  cni:
    enabled: false
  coreDNS:
    enabled: false
  values:
    prometheus:
      enabled: false    
    global:
      hub: private-hub.io/istio
```

`hub` value is ignored for `hub.yml`:
```
istioctl manifest generate -f hub.yml | ag 'image: '
        image: docker.io/istio/sidecar_injector:1.4.5
        ...
```

global `hub` value is honoured in `globalhub.yml`:
```
istioctl manifest generate -f globalhub.yml | ag 'image: '
        image: private-hub.io/istio/sidecar_injector:1.4.5
        ...
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
client version: 1.4.5
control plane version: 1.1.7
data plane version:  (3 proxies)
```

**How was Istio installed?**

Homebrew

**Environment where bug was observed (cloud vendor, OS, etc)**

OSX
