### ISSUE TITLE
Prometheus not able to scrape from Pod

### ISSUE THREAD

**Issue by a8j8i8t8** [istio/istio#21402]
**Bug description**
I've deployed Prometheus with mTLS enabled. This prometheus pod is started with secret `istio.default` mounted at `/etc/prometheus/secrets/istio.default/`.
I've another deployment with mTLS enabled where a pod has necessary annotations like below.
```
prometheus.io.port: 8080
prometheus.io.scrape: true
```
But prometheus is not able to scrape from this pod. I'm getting error.
`Get https://100.117.155.31:8080/metrics: http: server gave HTTP response to HTTPS client`
I've created below: -
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubernetes-pods-monitor-istio-secure
  namespace: foo-infra
  labels:
    monitoring: kube-pods
spec:
  selector:
    matchExpressions:
      - {key: istio-prometheus-ignore, operator: DoesNotExist}
  namespaceSelector:
    matchNames:
      - default
      - ops-infra
      - istio-system
  jobLabel: kubernetes-pods-monitor-istio-secure
  endpoints:
  - interval: 30s
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/secrets/istio.default/root-cert.pem
      certFile: /etc/prometheus/secrets/istio.default/cert-chain.pem
      keyFile: /etc/prometheus/secrets/istio.default/key.pem
      insecureSkipVerify: true  # prometheus does not support secure naming.
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
      action: keep
      regex: 'true'
    # sidecar status annotation is added by sidecar injector and
    # istio_workload_mtls_ability can be specifically placed on a pod to indicate its ability to receive mtls traffic.
    - sourceLabels: [__meta_kubernetes_pod_annotation_sidecar_istio_io_status, __meta_kubernetes_pod_annotation_istio_mtls]
      action: keep
      regex: (([^;]+);([^;]*))|(([^;]*);(true))
    - sourceLabels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
      action: drop
      regex: (http)
    - sourceLabels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
      action: replace
      targetLabel: __metrics_path__
      regex: (.+)
    - sourceLabels: [__address__]  # Only keep address that is host:port
      action: keep    # otherwise an extra target with ':443' is added for https scheme
      regex: ([^:]+):(\d+)
    - sourceLabels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      targetLabel: __address__
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - sourceLabels: [__meta_kubernetes_namespace]
      action: replace
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_pod_name]
      action: replace
      targetLabel: pod_name
``` 

**Expected behavior**
Prometheus should scrape from a pod.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
❯ istioctl version --remote
client version: 1.4.5
control plane version: 1.4.5
data plane version: 1.4.5 (16 proxies)
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:54Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"1bea6c00a7055edef03f1d4bb58b773fa8917f11", GitTreeState:"clean", BuildDate:"2020-02-11T20:05:26Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**
`istioctl manifest apply --set profile=demo --set values.grafana.enabled=false --set values.prometheus.enabled=false --set values.global.mtls.enabled=true --set values.global.controlPlaneSecurityEnabled=true`

**Comment by howardjohn** [comment]
@douglas-reid

**Comment by douglas-reid** [comment]
Is mTLS in permissive or strict mode?

Did your pod have `prometheus.io/scheme: https` ?

**Comment by a8j8i8t8** [comment]
@douglas-reid Yes pod does have annotation for scheme.
And mTLS is strict. Following is the truncated output of `istioctl authn tls-check` command.
First one is the service for my pod.
```
HOST:PORT                                                                            STATUS       SERVER         CLIENT           AUTHN POLICY                      DESTINATION RULE
servic-links.foo-infra.svc.cluster.local:8080                                        OK           STRICT         ISTIO_MUTUAL     /default                          istio-system/default
prometheus-k8s.foo-infra.svc.cluster.local:9090                                      OK           PERMISSIVE     ISTIO_MUTUAL     foo-infra/prometheus-k8s          istio-system/default
```

**Comment by douglas-reid** [comment]
does your prometheus instance have a sidecar in front of it?

**Comment by a8j8i8t8** [comment]
Yes @douglas-reid it does. As I've mentioned before, I've deployed Prometheus with mTLS enabled. It's not the one that comes with Istio.

**Comment by douglas-reid** [comment]
@a8j8i8t8 i don't believe that putting a functional sidecar (proxying traffic) in front of Prometheus will work. It certainly isn't a supported use case today. For TLS, you can mount certs to talk to istio-proxied endpoints. In 1.5, a sidecar is added to the prom deployment solely for security config, but not for proxying traffic.

**Comment by a8j8i8t8** [comment]
Thanks for clarifying @douglas-reid.
So for me, I should exclude metrics related ports from Istio. And then Prometheus will be able to scrape.
I'll close this issue.

**Comment by emrahcetiner** [comment]
@a8j8i8t8 how to exclude ports from istio? can you share to me your solution?

**Comment by a8j8i8t8** [comment]
@emrahcetiner Let's say, your istio enabled deployment is exposing metrics on port `1234`. Then you should exclude that port from both - 1. your istio enabled deployment 2. your istio enabled prometheus - using below annotations.
```
traffic.sidecar.istio.io/excludeOutboundPorts: "1234"
traffic.sidecar.istio.io/excludeInboundPorts: "1234"
```

I would choose a port that will not be used anywhere in your cluster. 
Cheers,
~Ajit

**Comment by emrahcetiner** [comment]
@a8j8i8t8 
in my cluster, prometheus pod has not istio proxy. it is running in istio-system namespace and istio-sysyem namespace disabled for auto-injection.

my application has 2 port for http and prometheus exporter. my app pod is running different namespace and istio injection enabled.

in prometheus pod i successfully reach to my app pod's prometheus exporter with curl. (but it is works only with http)

i see "http: server gave HTTP response to HTTPS client" error in targets page on prometheus dashboard(job=kubernetes-pods-istio-secure). because prometheus try to reach over https.

when i look into prometheus configuration, job which name is kubernetes-pods-istio-secure cause this in my opinion.

as a workaround solution i did remove kubernetes-pods-istio-secure job and also i remove 'drop action' in kubernetes-pods job.

**Comment by a8j8i8t8** [comment]
@emrahcetiner Mount `istio.default` secret in your prometheus, and use certs in this secret to connect to HTTPS URL.

**Comment by emrahcetiner** [comment]
@a8j8i8t8 there is already mounted like this:

```yaml
...
  volumeMounts:
  - mountPath: /etc/istio-certs
    name: istio-certs
volumes:
- name: istio-certs
   secret:
     defaultMode: 420
     secretName: istio.default
...
```

And prometheus is configured to using these certs.

```yaml
...
- job_name: 'kubernetes-pods-istio-secure'
  scheme: https
  tls_config:
    ca_file: /etc/istio-certs/root-cert.pem
    cert_file: /etc/istio-certs/cert-chain.pem
    key_file: /etc/istio-certs/key.pem
    insecure_skip_verify: true  # prometheus does not support secure naming.
...
```

iI'm not getting an error about tls. prometheus tring to scrape over https and target exporter service reject: "http: server gave HTTP response to HTTPS client"

should run my prometheus exporter in my app over https? i dont think so, because there is alraedy istio-proxy in pod. istio-proxy receive request from prometheus over https, then transmit it to my metric exporter service.  am i wrong?
