### ISSUE TITLE
Mixer sends spanName 'unknown' for client span requests to ServiceEntry

### ISSUE THREAD

**Issue by cmanzi** [istio/istio#21411]
**Bug description**
I am using the New Relic Istio adapter (https://github.com/newrelic/newrelic-istio-adapter) to forward trace spans to New Relic for our Istio multi-cluster setup. Doing this we are able to see spans for cross-cluster traffic. 

However, the root entry spans are always showing up with a spanName of 'unknown', even though one of the attributes which should populate that field (destination.service.name) is present. When enabling debugging on Mixer, we can see that the Instance seems to build correctly:
```
&Instance{Name:,Template:tracespan,Params:&types.Struct{Fields:map[string]*Value{apiProtocol: &Value{Kind:&Value_StringValue{StringValue:api.protocol | "",},XXX_unrecognized:[],},clientSpan: &Value{Kind:&Value_StringValue{StringValue:(context.reporter.kind | "inbound") == "outbound",},XXX_unrecognized:[],},destinationIp: &Value{Kind:&Value_StringValue{StringValue:destination.ip | ip("0.0.0.0"),},XXX_unrecognized:[],},destinationName: &Value{Kind:&Value_StringValue{StringValue:destination.workload.name | "unknown",},XXX_unrecognized:[],},endTime: &Value{Kind:&Value_StringValue{StringValue:response.time,},XXX_unrecognized:[],},httpStatusCode: &Value{Kind:&Value_StringValue{StringValue:response.code | 0,},XXX_unrecognized:[],},parentSpanId: &Value{Kind:&Value_StringValue{StringValue:request.headers["x-b3-parentspanid"] | "",},XXX_unrecognized:[],},requestSize: &Value{Kind:&Value_StringValue{StringValue:request.size | 0,},XXX_unrecognized:[],},requestTotalSize: &Value{Kind:&Value_StringValue{StringValue:request.total_size | 0,},XXX_unrecognized:[],},responseSize: &Value{Kind:&Value_StringValue{StringValue:response.size | 0,},XXX_unrecognized:[],},responseTotalSize: &Value{Kind:&Value_StringValue{StringValue:response.total_size | 0,},XXX_unrecognized:[],},rewriteClientSpanId: &Value{Kind:&Value_StringValue{StringValue:false,},XXX_unrecognized:[],},sourceIp: &Value{Kind:&Value_StringValue{StringValue:source.ip | ip("0.0.0.0"),},XXX_unrecognized:[],},sourceName: &Value{Kind:&Value_StringValue{StringValue:source.workload.name | "unknown",},XXX_unrecognized:[],},spanId: &Value{Kind:&Value_StringValue{StringValue:request.headers["x-b3-spanid"] | "",},XXX_unrecognized:[],},spanName: &Value{Kind:&Value_StringValue{StringValue:destination.workload.name | destination.service.name | "unknown",},XXX_unrecognized:[],},spanTags: &Value{Kind:&Value_StructValue{StructValue:&Struct{Fields:map[string]*Value{api.name: &Value{Kind:&Value_StringValue{StringValue:api.service | "unknown",},XXX_unrecognized:[],},api.version: &Value{Kind:&Value_StringValue{StringValue:api.version | "unknown",},XXX_unrecognized:[],},connection.securityPolicy: &Value{Kind:&Value_StringValue{StringValue:conditional((context.reporter.kind | "inbound") == "outbound", "unknown", conditional(connection.mtls | false, "mutual_tls", "none")),},XXX_unrecognized:[],},destination.owner: &Value{Kind:&Value_StringValue{StringValue:destination.owner | "unknown",},XXX_unrecognized:[],},destination.port: &Value{Kind:&Value_StringValue{StringValue:destination.port | 0,},XXX_unrecognized:[],},destination.service.name: &Value{Kind:&Value_StringValue{StringValue:destination.service.name | "unknown",},XXX_unrecognized:[],},destination.service.namespace: &Value{Kind:&Value_StringValue{StringValue:destination.service.namespace | "unknown",},XXX_unrecognized:[],},destination.workload.name: &Value{Kind:&Value_StringValue{StringValue:destination.workload.name | "",},XXX_unrecognized:[],},destination.workload.namespace: &Value{Kind:&Value_StringValue{StringValue:destination.workload.namespace | "unknown",},XXX_unrecognized:[],},request.auth.principal: &Value{Kind:&Value_StringValue{StringValue:request.auth.principal | "unknown",},XXX_unrecognized:[],},request.host: &Value{Kind:&Value_StringValue{StringValue:request.host | "unknown",},XXX_unrecognized:[],},request.operation: &Value{Kind:&Value_StringValue{StringValue:conditional((context.protocol | "unknown") == "grpc", request.path | "unknown", request.method | "unknown"),},XXX_unrecognized:[],},request.path: &Value{Kind:&Value_StringValue{StringValue:request.path | "",},XXX_unrecognized:[],},request.protocol: &Value{Kind:&Value_StringValue{StringValue:context.protocol | "unknown",},XXX_unrecognized:[],},source.owner: &Value{Kind:&Value_StringValue{StringValue:source.owner | "unknown",},XXX_unrecognized:[],},source.workload.name: &Value{Kind:&Value_StringValue{StringValue:source.workload.name | "unknown",},XXX_unrecognized:[],},source.workload.namespace: &Value{Kind:&Value_StringValue{StringValue:source.workload.namespace | "unknown",},XXX_unrecognized:[],},},XXX_unrecognized:[],},},XXX_unrecognized:[],},startTime: &Value{Kind:&Value_StringValue{StringValue:request.time,},XXX_unrecognized:[],},traceId: &Value{Kind:&Value_StringValue{StringValue:request.headers["x-b3-traceid"] | "",},XXX_unrecognized:[],},},XXX_unrecognized:[],},AttributeBindings:map[string]string{},CompiledTemplate:,}
```

This is the ServiceEntry for the `global` service:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: productpage-mvp
spec:
  hosts:
  # must be of form name.namespace.global
  - productpage.bookinfo.mvp.global
  location: MESH_INTERNAL
  ports:
  - name: http1
    number: 9080
    protocol: http
  resolution: DNS
  addresses:
  - 240.0.100.1
  endpoints:
  - address: cluster.example.com
    ports:
      http1: 15443 # Do not change this port value
```

As expected, the traces for this ServiceEntry show up with `destination.service.name` set to `productpage.bookinfo.mvp.global`, and workload information missing (also expected). The spanName, as stated before, is `unknown` - despite `spanName: &Value{Kind:&Value_StringValue{StringValue:destination.workload.name | destination.service.name | "unknown",}`.

The New Relic adapter does not modify the spanName value; it simply forwards the value it receives from Mixer (see https://github.com/newrelic/newrelic-istio-adapter/blob/master/trace/handler.go#L51-L101).

So, this seems like a bug, since the expected behavior would be that spanName would be set to `destination.service.name` as specified in the instance:

```
apiVersion: config.istio.io/v1alpha2
kind: instance
metadata:
  name: "newrelic-span"
  namespace: istio-system
  labels:
    app.kubernetes.io/name: newrelic-istio-adapter
    helm.sh/chart: newrelic-istio-adapter-1.0.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/version: 2.0.1
spec:
  template: tracespan
  params:
    apiProtocol: api.protocol | ""
    clientSpan: (context.reporter.kind | "inbound") == "outbound"
    destinationIp: destination.ip | ip("0.0.0.0")
    destinationName: destination.workload.name | "unknown"
    endTime: response.time
    httpStatusCode: response.code | 0
    parentSpanId: request.headers["x-b3-parentspanid"] | ""
    requestSize: request.size | 0
    requestTotalSize: request.total_size | 0
    responseSize: response.size | 0
    responseTotalSize: response.total_size | 0
    rewriteClientSpanId: "false"
    sourceIp: source.ip | ip("0.0.0.0")
    sourceName: source.workload.name | "unknown"
    spanId: request.headers["x-b3-spanid"] | ""
    spanName: destination.workload.name | destination.service.name | "unknown"
    spanTags:
      api.name: api.service | "unknown"
      api.version: api.version | "unknown"
      connection.securityPolicy: conditional((context.reporter.kind | "inbound") == "outbound", "unknown", conditional(connection.mtls | false, "mutual_tls", "none"))
      destination.owner: destination.owner | "unknown"
      destination.port: destination.port | 0
      destination.service.name: destination.service.name | "unknown"
      destination.service.namespace: destination.service.namespace | "unknown"
      destination.workload.name: destination.workload.name | "unknown"
      destination.workload.namespace: destination.workload.namespace | "unknown"
      request.auth.principal: request.auth.principal | "unknown"
      request.host: request.host | "unknown"
      request.operation: conditional((context.protocol | "unknown") == "grpc", request.path | "unknown", request.method | "unknown")
      request.path: request.path | ""
      request.protocol: context.protocol | "unknown"
      source.owner: source.owner | "unknown"
      source.workload.name: source.workload.name | "unknown"
      source.workload.namespace: source.workload.namespace | "unknown"
    startTime: request.time
    traceId: request.headers["x-b3-traceid"] | ""
```

This doesn't seem to me to be related directly to a multicluster setup...but rather the use of a ServiceEntry. 

**Expected behavior**
spanName is populated with `destination.service.name`.

**Steps to reproduce the bug**
Install Istio 1.4.5 with a ServiceEntry, generate traffic/spans, view the client spans generated.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Istio: 1.4.5
Kube: 1.15.7

**How was Istio installed?**
Helm template

**Environment where bug was observed (cloud vendor, OS, etc)**
kops - aws
