### ISSUE TITLE
Cloudwatch adapter - failed to evaluate template for log instance

### ISSUE THREAD

**Issue by MoonFalcon** [istio/istio#21413]
**Description**

When passing in a log entry to the cloudwatch adapter I receive `failed to evaluate template for log instance`, even if I heavily simplify the logentry variables and payloadTemplate

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected results** 
The cloudwatch handler should properly evaluate the logentry template using the golang template passed into payloadTemplate, and should populate the logs into cloudwatch logs

**Steps to reproduce the bug**
1. Create a yaml file that will hold all your code
2. Create a logentry
```
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
  name: accesslogentry
  namespace: istio-system
spec:
  compiledTemplate: logentry
  params:
    severity: '"Default"'
    timestamp: request.time
    variables:
      method: request.method | ""
    monitored_resource_type: '"UNSPECIFIED"'
```

3. Create a handler
```
# Configuration for a stdio handler
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: cloudwatchhandler
  namespace: "istio-system"
spec:
  compiledAdapter: cloudwatch
  params:
    namespace: "cloudwatch-istio"
    # metricInfo:
      # sizeofrequest.instance.istio-system:
       # unit: Bytes
    logGroupName: TestLogGroup
    logStreamName: TestLogStream
    logs:
      accesslog:
        payloadTemplate: '{{or (.method) "-" } [{{or (.timestamp.Format "2006-01-02T15:04:05Z07:00") "-"}}]}'
```

4. Create a rule
```
# Rule to send logentry instances to a stdio handler
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: cloudwatchrule
  namespace: istio-system
spec:
  match: "true" # match for all requests
  actions:
   - handler: cloudwatchhandler
     instances:
     # - sizeofrequest
     - accesslogentry
```

5. Apply the template, run a request against something in your cluster with istio enabled, then view the telemetry mixer logs with `kubectl logs istio-telemetry-$pod# -c mixer --tail 100`

6. Receive 
```
failed to get message for instance: accesslogentry.instance.istio-system. failed to evaluate template for log instance: &{accesslogentry.instance.istio-system map[method:POST] 2020-02-24 17:18:49.255594 +0000 UTC Default UNSPECIFIED map[]}, skipping      {"adapter": "cloudwatchhandler.istio-system"}
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
istioctl version --remoteclient version: 1.4.3
control plane version: 1.4.3
data plane version: 1.4.3 (3 proxies)
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:54Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
istioctl manifest apply

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS eks
