### ISSUE TITLE
Unable to merge envoy bootstrap configuration

### ISSUE THREAD

**Issue by kmmolex** [istio/istio#21429]
**Bug description**
kubectl logs <my_pod> -c istio-proxy
```

2020-02-24T20:07:51.958118Z	info	Envoy command: [-c /etc/istio/proxy/envoy.yaml --restart-epoch 0 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster ubuntu.test-5 --service-node sidecar~100.96.13.4~ubuntu-deployment-7dcc986dc7-vj8mm.test-5~test-5.svc.cluster.local --max-obj-name-len 189 --local-address-ip-version v4 --log-format [Envoy (Epoch 0)] [%Y-%m-%d %T.%e][%t][%l][%n] %v -l warning --component-log-level misc:error --config-yaml {
  "static_resources": {
    "listeners": [
      {
        "address": {
          "socket_address": {
            "protocol": "TCP",
            "address": "0.0.0.0",
            "port_value": 80
          }
        },
      }
    ]
  }
}
 --concurrency 2]
[Envoy (Epoch 0)] [2020-02-24 20:07:51.977][18][warning][main] [external/envoy/source/server/server.cc:354] No admin address given, so no admin HTTP server started.
[Envoy (Epoch 0)] [2020-02-24 20:07:51.977][18][critical][main] [external/envoy/source/server/server.cc:97] error initializing configuration '/etc/istio/proxy/envoy.yaml': error adding listener '0.0.0.0:80': no filter chains specified
error adding listener '0.0.0.0:80': no filter chains specified
2020-02-24T20:07:51.979284Z	warn	Failed to delete config file /etc/istio/proxy/envoy-rev0.json for 0, remove /etc/istio/proxy/envoy-rev0.json: no such file or directory
2020-02-24T20:07:51.979335Z	error	Epoch 0 exited with error: exit status 1
2020-02-24T20:07:51.979341Z	info	No more active epochs, terminating
```

Note:
I had to modify the manifest to use
```
        - name: ISTIO_BOOTSTRAP_OVERRIDE
          value: "/etc/istio/custom-bootstrap/custom_bootstrap.json"
```
instead of
`          value: "/etc/istio/custom-bootstrap/envoy_bootstrap.json"`

just to get the sidecar proxy to find the file.
 

In this example,
I am just trying to add a listener to the default bootstrap configuration. if i copy a more complete configuration like below, i'll get errors about duplicate clusters 'service_stats' (even though only one is specified)
```

apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-custom-bootstrap-config
  namespace: test-5
data:
  custom_bootstrap.json: |
    {
      "admin": {
        "access_log_path": "/dev/null",
        "address": {
          "socket_address": {
            "protocol": "TCP",
            "address": "127.0.0.1",
            "port_value": 8081
          }
        }
      },
      "static_resources": {
        "listeners": [
          {
            "address": {
              "socket_address": {
                "protocol": "TCP",
                "address": "0.0.0.0",
                "port_value": 80
              }
            },
            "filter_chains": [
              {
                "filters": [
                  {
                    "name": "envoy.http_connection_manager",
                    "config": {
                      "codec_type": "AUTO",
                      "stat_prefix": "ingress_http",
                      "route_config": {
                        "virtual_hosts": [
                          {
                            "name": "backend",
                            "domains": [
                              "*"
                            ],
                            "routes": [
                              {
                                "match": {
                                  "prefix": "/stats"
                                },
                                "route": {
                                  "cluster": "service_stats"
                                }
                              }
                            ]
                          }
                        ]
                      },
                      "http_filters": [
                        {
                          "name": "envoy.router",
                          "config": null
                        }
                      ]
                    }
                  }
                ]
              }
            ]
          }
        ],
        "clusters": [
          {
            "name": "service_stats",
            "connect_timeout": "0.250s",
            "type": "LOGICAL_DNS",
            "lb_policy": "ROUND_ROBIN",
            "hosts": [
              {
                "socket_address": {
                  "protocol": "TCP",
                  "address": "127.0.0.1",
                  "port_value": 8001
                }
              }
            ]
          }
        ]
      }
    }
```

my end goal is to expose an additional route called /stats (not /stats/prometheus) in order to get my datadog agents to retrieve metrics. 

i am currently working with their support, but they did not explain how exactly to expose the envoy /stats route through istio.
https://docs.datadoghq.com/integrations/envoy/#setup

I have tried many variations of merging values and they all fail.

i don't know if i should be creating Sidecar and EnvoyFilter resoures instead? 
I tried that, but pilot doesn't seem to be passing my configurations this way either.
```
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  annotations:
  labels:
    release: istio
  name: default
  namespace: test-5
spec:
        # workloadSelector:
        #labels:
        # app: ubuntu
  egress:
  - hosts:
    - '*/*'
```
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: expose-stats-route-for-datadog
  namespace: test-5 # TODO-MAK: use "root" namespace i.e. istio-config, to be defined in MeshConfig
spec:
  configPatches:
  - applyTo: LISTENER
    patch:
      operation: ADD
      value:
        name: listener_0
        address:
          socket_address: { address: 0.0.0.0, port_value: 80 }
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            config:
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: backend
                  domains: ["*"]
                  routes:
                  - match: { prefix: "/stats" }
                    route: { cluster: prometheus_stats }
              http_filters:
              - name: envoy.router
```

**Expected behavior**
I expected the custom-bootstrap to "merge the passed in configuration with the default configuration. "
as described in https://github.com/istio/istio/tree/master/samples/custom-bootstrap

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

$ istioctl version
client version: 1.4.3
control plane version: 1.4.3
data plane version: 1.4.3 (12 proxies)

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
istioctl manifest generate \
--set values.gateways.enabled=true \
--set values.gateways.istio-ingressgateway.enabled=true \
--set values.gateways.istio-ingressgateway.sds.enabled=true \
--set values.grafana.enabled=true \
--set values.kiali.enabled=true \
--set values.kiali.dashboard.jaegerURL=https://jaeger.<redacted>:15032 \
--set values.kiali.dashboard.grafanaURL=https://grafana.<redacted>:15031 \
--set values.prometheus.enabled=true \
--set values.tracing.enabled=true \
--set values.global.outboundTrafficPolicy.mode=ALLOW_ANY \
> manifest.yaml
 
kubectl apply -f manifest.yaml

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS, Ubuntu EC2
