### ISSUE TITLE
`global.proxy.includeInboundPorts` is broken

### ISSUE THREAD

**Issue by dozer47528** [istio/istio#21458]
**Bug description**

I installed istio by helm: `--set global.proxy.includeInboundPorts=""`.

But it has no effect after setting, and I check the final pod yaml, it is always `*`:

```yaml
   initContainers:
   - command:
     - istio-iptables
     - -p
     - "15001"
     - -z
     - "15006"
     - -u
     - "1337"
     - -m
     - REDIRECT
     - -i
     - '*'
     - -x
     - ""
     - -b
     - '*'
     - -d
     - "15020"
```

And I checked the istio source code of `install/kubernetes/helm/istio/files/injection-template.yaml`

```
  - "-b"
  - "{{ annotation .ObjectMeta `traffic.sidecar.istio.io/includeInboundPorts` `*` }}"
  - "-d"
  - "{{ excludeInboundPort (annotation .ObjectMeta `status.sidecar.istio.io/port` .Values.global.proxy.statusPort) (annotation .ObjectMeta `traffic.sidecar.istio.io/excludeInboundPorts` .Values.global.proxy.excludeInboundPorts) }}"
```

It will use the `.Values.global.proxy.excludeInboundPorts` but ignored `.Values.global.proxy.includeInboundPorts`.

**Expected behavior**

`-b` should be `''` in `initContainers`.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

client version: 1.4.5
control plane version: 1.4.5
data plane version: 1.4.2 (19 proxies), 1.4.0 (19 proxies), 1.4.4 (3 proxies), 1.4.3 (81 proxies), 1.4.5 (32 proxies)

**How was Istio installed?**

helm

**Environment where bug was observed (cloud vendor, OS, etc)**

Kubernetes 1.14
