### ISSUE TITLE
istioctl should validate IstioOperator

### ISSUE THREAD

**Issue by esnible** [istio/istio#21473]
To reproduce:

```
cat > icp.yaml <<EOF
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  namespace: istio-operator
  name: example-istiocontrolplane
spec:
  dummy:
  traffic_management:
    dummy:
    components:
      dummy:
      namespace: istio-traffic-management
EOF
istioctl validate -f icp.yaml
istioctl analyze icp.yaml
```

Obviously, the "dummy:" fields don't belong and represent some user typo for a desired field.

**Comment by esnible** [comment]
I don't believe Istio will support `Kind: IstioControlPlane`, and will use `Kind: IstioOperator` instead.  Retargetting.  New example:

```
cat > /tmp/io.yaml <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  dummy:
  traffic_management:
    dummy:
    components:
      dummy:
      namespace: istio-traffic-management
EOF
```

**Comment by esnible** [comment]
@selmanj I have an implementation for "istioctl validate".

A full solution would involve adding IstioOperator to the analysis framework.  Do you have a general feeling about the size of getting it there?  Currently there are no Pilot nor Galley collections of IstioOperator.

**Comment by esnible** [comment]
Background context via Slack message from @selmanj 

"... https://github.com/istio/istio/pull/20929/files has an example of adding the k8s ConfigMap. A new Istio type should be even easier as you won’t need to modify galley/pkg/config/source/kube/rt/known.go - HOWEVER when you run make gen there seems to be a bootstrapping problem with the proto definition. I had to directly import the proto at the top of the pkg/config/schema/resource/schema.go, run make gen, and then remove that import."

**Comment by esnible** [comment]
@ostromart I was unable to figure out how to do what you suggested in https://github.com/istio/istio/pull/22166#issuecomment-613001230 .  Can you assign someone to do that work, either as progress on this issue or to improve the docs?  I would like Istio 1.7 to be able to analyze IOPs.

**Comment by esnible** [comment]
@ostromart I added `area/environments` to this.  We need to find an owner and work on what the validations might be.

Today I tried `istioctl install --set values.pilot.keepaliveMaxServerConnectionAge="-30m"` which puts Istiod into CrashLoopBack state because it causes a **panic**, `invalid argument to Int63n`, and there is no Istio code in the backtrace.

**Comment by shamsher31** [comment]
@esnible I think it is working as expected. Mostly fixed by https://github.com/istio/istio/pull/21644.

I used the following YAML. 
```
cat > /tmp/io.yaml <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  dummy:
  traffic_management:
    dummy:
    components:
      dummy:
      namespace: istio-traffic-management
EOF
```

The `validate` works as expected.
```
$ ./out/linux_amd64/istioctl validate -f /tmp/io.yaml
Error: 1 error occurred:
        * IstioOperator/istio-system/example-istiocontrolplane: could not unmarshal: unknown field "traffic_management" in v1alpha1.IstioOperatorSpec
```
And `install also detects invalid IstioOperatorSpec.

```
$ ./out/linux_amd64/istioctl install -f /tmp/io.yaml
This will install the Istio 1.9.0 profile into the cluster. Proceed? (y/N) y
Error: failed to install manifests: unknown field "dummy" in v1alpha1.IstioOperatorSpec:

YAML:
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: example-istiocontrolplane
  namespace: istio-system
spec:
  dummy: null
  traffic_management:
    components:
      dummy: null
      namespace: istio-traffic-management
    dummy: null
```
