### ISSUE TITLE
Example customizations for proxy are invalid

### ISSUE THREAD

**Issue by esnible** [istio/istio#21474]
Web page https://preliminary.istio.io/docs/reference/config/istio.operator.v1alpha12.pb/

Number 6, "Default install with values.yaml customizations for proxy" contains incorrect YAML.

To reproduce, I clicked the "copy" button and pasted into a script that looked like this:

```
cat > icp.yaml <<EOF
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  namespace: istio-operator
  name: example-istiocontrolplane
spec:
  traffic_management:
    components:
      proxy:
        values:
        - global.proxy.enableCoreDump: true
        - global.proxy.dnsRefreshRate: 10s

EOF
istioctl manifest apply -f icp.yaml
```

The apply yielded `Error: failed to generate and apply manifests, error: failed to generate manifest: unknown field "traffic_management" in v1alpha1.IstioOperatorSpec`
