### ISSUE TITLE
panic in "istioctl manifest apply"

### ISSUE THREAD

**Issue by esnible** [istio/istio#21472]
To reproduce:

```
cat > icp.yaml <<EOF
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  namespace: istio-operator
  name: example-istiocontrolplane
spec:
EOF
istioctl manifest apply -f icp.yaml
```

I discovered this testing https://preliminary.istio.io/docs/reference/config/istio.operator.v1alpha12.pb/ which suggests the default Istio istall can be achieved with a bare `spec:`

Someone should verify if this backtraces the operator container.

**Comment by esnible** [comment]
I verified the bare `spec:` problem does not affect the operator container normally, because the schema validation on `istiooperators.install.istio.io` CRD prevents a naked `spec:`.

**Comment by esnible** [comment]
The panic is at 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x296f2a6]

goroutine 1 [running]:
istio.io/istio/operator/pkg/validate.CheckIstioOperatorSpec(0x0, 0xc00044b500, 0x0, 0x0, 0x6)
	istio.io/istio@/operator/pkg/validate/validate.go:41 +0x26
```

**Comment by esnible** [comment]
I have found another panic.

```
cat > /tmp/icp.yaml <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: default
  components:
  values:
    global:
       imagePullPolicy: Always
       sds:
         enabled: false
       mtls:
         enabled: true
EOF
./istioctl manifest generate -f /tmp/icp.yaml
```

This one is in a completely different place,

```
istio.io/istio/operator/pkg/component/controlplane.NewIstioOperator(0xc000aca900, 0xc0009fae70, 0x0, 0x0, 0xc000aca900)
	istio.io/istio@/operator/pkg/component/controlplane/control_plane.go:53 +0xa5
```

The operator does accepts this CR, and creates an istiod with no ingressgateway Deployment.
