### ISSUE TITLE
1.5 regression: HPA spec overlay broken

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#21484]
```
$ manifest generate -f iop.yaml

# Resources for IngressGateways component

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ""
    name: ""
```

note the kind and name, which are invalid and will fail to apply into a cluster. I believe this works on master and previously worked on 1.5

iop.yaml:
```yaml
apiVersion: operator.istio.io/v1alpha1
kind: IstioOperator
spec:
    ingressGateways:
    - enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2
          maxReplicas: 10
        resources:
          limits:
            cpu: 6000m
            memory: 512Mi
          requests:
            cpu: 2000m
            memory: 512Mi
```
