### ISSUE TITLE
OPERATOR Controller 1.5.0-beta.3 No Addons, No Egress. 

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#21490]
**Bug description**

Using the following iop, no addons were deployed with the operator controller
```
tag: 1.5.0-beta.3
  profile: default
  addonComponents:
    prometheus:
      enabled: true
    kiali:
      enabled: true
    grafana:
      enabled: true
    tracing:
      enabled: true
```
With the following iop, no egress was deployed
```
tag: 1.5.0-beta.3
  profile: default
  components:
    egressGateways:
    - name: istio-egressgateway
      enabled: true
```

Only see 3 pods, ingress, istiod and prometheus in istio-system.

Nothing bad happening in the operator logs.

**Expected behavior**

**Steps to reproduce the bug**

- Install the operator controller
- apply the iop's above
- watch the istio-system namespace

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.5.0-beta.3

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
