### ISSUE TITLE
As an Istio user I expect to be able to prevent plain text connections between istio components

### ISSUE THREAD

**Issue by XanderStrike** [istio/istio#21494]
**Describe the feature request**
One of the most desirable features of a mesh network is being able to force all communication over that network to be mTLS. This is a hard requirement for many of our customers.

When we enable `controlPlaneSecurityEnabled`, we expect mTLS to be enabled between control plane components (pilot, galley, etc). This is not the case, as components still accept plain text communication. This can be tested by attempting to `curl http://istio-pilot.istio-system.svc.cluster.local:8080/debug/edsz` from other containers on the cluster. Including containers that do not have a a client sidecar.

Even containers outside of the namespace are capable of accessing Istio control plane components over plain text.

**Describe alternatives you've considered**

We're have a STRICT `MeshPolicy` on the cluster, but that does not appear to affect traffic to Istio control plane components.

We also attempted to create a STRICT `Policy` specifically on Pilot, but we were still able to access it over plain text. So there is some kind of exception for Istio control plane components.

We finally tried creating a `DestinationRule` for Pilot that would require connections to be ISTIO_MUTUAL. This successfully prevents plaintext requests from containers that _do_ have a sidecar from reaching Pilot's debug endpoint, but it does nothing to prevent requests from containers that do not. 

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[X] Docs (the behavior of `controlPlaneSecurityEnabled` should be accurately documented, see #3844)
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
<details>
  <summary>Our MeshPolicy (click to expand)</summary>

```yaml
apiVersion: "authentication.istio.io/v1alpha1"
kind: "MeshPolicy"
metadata:
  name: "default"
spec:
  peers:
  - mtls:
      mode: STRICT
```
</details>

<details>
  <summary>The Policy we tried (click to expand)</summary>

```yaml
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "istio-pilot-wat"
spec:
  targets:
  - name: istio-pilot
    namespace: istio-system
  peers:
  - mtls:
      mode: STRICT
```
</details>

<details>
  <summary>The DestinationRule we tried (click to expand)</summary>

```yaml
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "istio-pilot-destination"
  namespace: "istio-system"
spec:
  host: "istio-pilot.istio-system.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```
</details>

<details>
  <summary>Relevant istio values (click to expand)</summary>

```yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  profile: default
  values:
    global:
      controlPlaneSecurityEnabled: true
      mtls:
        auto: true
```
Some values were removed for brevity but you can view our whole generated manifest [here](https://github.com/cloudfoundry/cf-for-k8s/blob/master/config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/istio-generated/xxx-generated-istio.yaml).
</details>

CC @rodolfo2488 @tcdowney @rosenhouse @utako @ndhanushkodi
