### ISSUE TITLE
Failed istioctl create -f samples/bookinfo/kube/route-rule-all-v1.yaml

### ISSUE THREAD

**Issue by yaoguais** [istio/istio#2150]
```
# istioctl create -f samples/bookinfo/kube/route-rule-all-v1.yaml

Error: configuration is invalid: 1 error occurred:

* name or service is mandatory for a service reference
```
I think it was cased by this line.
https://github.com/istio/istio/blob/d1c939b5d6a23c496e0c1a9a1a02419b3837c93d/pilot/model/validation.go#L256
```
func ValidateIstioService(svc *routing.IstioService) (errs error) {
	if svc.Name == "" && svc.Service == "" {
		errs = multierror.Append(errs, errors.New("name or service is mandatory for a service reference"))
	}
```
in route-rule-all-v1.yaml:
```
match:
    source:
      labels:
        istio: ingress

source is a type of IstioService, but has no name or service. 
```
add service name will be ok.
before: https://github.com/istio/istio/blob/master/samples/bookinfo/kube/route-rule-all-v1.yaml
after:
```
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: productpage-default
spec:
  ## Used by services inside the Kubernetes cluster
  destination:
    name: productpage
  precedence: 1
  route:
  - labels:
      version: v1
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: ingress-deny-all
spec:
  destination:
    name: productpage
  match:
    source:
      service: productpage
      labels:
        istio: ingress
  precedence: 2
  route:
  - weight: 100
  httpFault:
    abort:
      percent: 100
      httpStatus: 403
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: ingress-products-api
spec:
  destination:
    name: productpage
  match:
    source:
      service: productpage
      labels:
        istio: ingress
    request:
      headers:
        uri:
          prefix: /api/v1/products
  precedence: 3
  route:
  - labels:
      version: v1
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: ingress-productpage-logout
spec:
  destination:
    name: productpage
  match:
    source:
      service: productpage
      labels:
        istio: ingress
    request:
      headers:
        uri:
          exact: /logout
  precedence: 3
  route:
  - labels:
      version: v1
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: ingress-productpage-login
spec:
  destination:
    name: productpage
  match:
    source:
      service: productpage
      labels:
        istio: ingress
    request:
      headers:
        uri:
          exact: /login
  precedence: 3
  route:
  - labels:
      version: v1
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: ingress-productpage-landing
spec:
  destination:
    name: productpage
  match:
    source:
      service: productpage
      labels:
        istio: ingress
    request:
      headers:
        uri:
          exact: /productpage
  precedence: 3
  route:
  - labels:
      version: v1
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: reviews-default
spec:
  destination:
    name: reviews
  precedence: 1
  route:
  - labels:
      version: v1
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: ratings-default
spec:
  destination:
    name: ratings
  precedence: 1
  route:
  - labels:
      version: v1
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: details-default
spec:
  destination:
    name: details
  precedence: 1
  route:
  - labels:
      version: v1

```
