### ISSUE TITLE
Get metrics: x509: certificate is valid for 10.100.0.1, not 52.155.183.48

### ISSUE THREAD

**Issue by IbraheemAlSaady** [istio/istio#21510]
I'm getting the following error:

<img width="1672" alt="Screenshot 2020-02-26 at 1 50 22 PM" src="https://user-images.githubusercontent.com/14288490/75346423-f7947480-589e-11ea-9e3b-7f6daeb79f9a.png">

Istio is installed with istioctl on Azure AKS

This is my control plane config:

``` yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  # Use the default profile as the base
  # More details at: https://istio.io/docs/setup/additional-setup/config-profiles/
  profile: default
  cni:
    enabled: true
    components:
      namespace: kube-system
  gateways:
    components:
      egressGateway:
        enabled: true
  values:
    global:
      # Ensure that the Istio pods are only scheduled to run on Linux nodes
      defaultNodeSelector:
        beta.kubernetes.io/os: linux
      # Enable mutual TLS for the control plane
      controlPlaneSecurityEnabled: true
      mtls:
        # Require all service to service communication to have mtls
        enabled: true
        auto: true
      outboundTrafficPolicy:
        mode: REGISTRY_ONLY
      proxy:
        logLevel: info
        accessLogFile: /dev/stdout
      k8sIngress:
        enabled: true
        enableHttps: true
        gatewayName: ingressgateway
    sidecarInjectorWebhook:
      rewriteAppHTTPProbe: true
    grafana:
      # Enable Grafana deployment for analytics and monitoring dashboards
      enabled: false
      # security:
      #   # Enable authentication for Grafana
      #   enabled: true
      # env:
    kiali:
      # Enable the Kiali deployment for a service mesh observability dashboard
      enabled: true
      # dashboard:
      #   # jaegerURL: ""
    prometheus:
      # Enable the Prometheus deployment for monitoring
      enabled: true
    tracing:
      # Enable the Jaeger deployment for tracing
      enabled: true
    gateways:
      istio-ingressgateway:
        type: LoadBalancer
        sds:
          enabled: true
        serviceAnnotations:
          external-dns.alpha.kubernetes.io/hostname: ${HOST_PUBLIC}.${CLUSTER_DNS_PUBLIC}
          ${ANNOTATIONS_PUBLIC}
```

Istio Version: 1.4.5
Kube Version: 1.15.7

**Comment by joekrill** [comment]
I'm seeing the same thing on a mostly default install on Digital Ocean's Managed Kubernetes offering. I'm basically using this configuration:

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:     
    egressGateways:
    - enabled: true
  addonComponents:
    kiali:
      enabled: true
    grafana: 
      enabled: true
  values:
    gateways:
      istio-ingressgateway:
        sds:
          enabled: true
        serviceAnnotations:
          service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: 'true'
```
<img width="1309" alt="Screen Shot 2020-05-05 at 9 39 26 AM" src="https://user-images.githubusercontent.com/393220/81072685-7ec02300-8eb4-11ea-963c-a51f73a73d2c.png">
