### ISSUE TITLE
istio-ingressgateway port not opening

### ISSUE THREAD

**Issue by eddiewang** [istio/istio#21516]
**Bug description**

I'm scratching my head as to why I can't seem to open new ports on the istio ingressgateway.
I've been able to setup services before simply by running `kubectl edit service istio-ingressgateway -n istio-system`.

Running through the same process again, the port does not appear to be open, and times out when I send TCP packets through.

```
  externalTrafficPolicy: Cluster
  ports:
  - name: test-peer-6001
    nodePort: 30094
    port: 6001
    protocol: TCP
```

I'm using the LoadBalancer type on GCP, running istio v1.4.5.

Any guidance would be appreciated! Do I need to restart the ingressgateway pods or do something else in Istio/LB for the changes to take effect and for the ports to open?
