### ISSUE TITLE
Prometheus service scraping receive 403 when RBAC is enabled

### ISSUE THREAD

**Issue by aalmazanarbs** [istio/istio#21520]
**Bug description**

In k8s 1.14.0 with Istio 1.3 installed with (Helm) and mtls enabled. We have enabled ClusterRbacConfig in ON_WITH_EXCLUSION mode (excluding istio-system). Prometheus scrapper is running in the istio-system namespace.

We have te following ServiceRole:
```
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: access
  namespace: namespace
spec:
  rules:
  - services: ["service.namespace.svc.cluster.local"]
    methods: ["*"]
    paths: ["*"]
```

and ServiceRoleBinding:
```
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: access
  namespace: namespace
spec:
  subjects:
  - properties:
      source.principal: "cluster.local/ns/istio-system/sa/prometheus"
  # other access
  roleRef:
    kind: ServiceRole
    name: "access"
```

The pods running the service in the port 8080 has istio sidecar and the service is receiving requests from other services and istio-ingressgateway but from prometheus scraper no.

The url http://100.96.1.45:15090/stats/prometheus (Istio metrics) is accesible but https://100.96.15.245:8080/stats/prometheus (service metrics) are not accesible. If we run the same endpoint from other service (not prometheus) using http://service.namespace.svc.cluster.local/stats/prometheus the request is received in the service.

The service deployment has the following annotation:
```
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scheme: https
        prometheus.io/scrape: "true"
```

If we disable rbac, the prometheus scrapper works again.

**Comment by emrahcetiner** [comment]
same issue +1

**Comment by incfly** [comment]
Istio 1.3 reaches its end of support. Please confirm whether this is reproducible from 1.4 as well.

**Comment by aalmazanarbs** [comment]
Confirmed

**Comment by yangminzhu** [comment]
It's likely the prometheus is calling using plain text instead of mTLS, it gets rejected by RBAC because it doesn't have the identity ("cluster.local/ns/istio-system/sa/prometheus") when using plain text.

@aalmazanarbs For 1.3, I think you probably have to disable the RBAC policy on port 8080, For 1.4, it's strongly recommended to use the v1beta1 authorization policy that deprecates the v1alpha1 RBAC policy, and also whitelist port 8080. For 1.5, I thought we did some work to add the sidecar to prometheus? (cc @lei-tang to confirm).

**Comment by aalmazanarbs** [comment]
Thank you for your answer @yangminzhu 

How can we check if prometheus is calling or not with mTLS? We would like to check it to understand 
why, pod **istio-ingressgateway** (without istio sidecar), is able to reach **service.namespace.svc.cluster.local** if we configure in the **ServiceRoleBinding** _source.principal: "cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"_ but prometheus no. My guess is that prometheus is using the **IP** of the pod and ingress uses the service...so can we whitelist that with ServiceRole or authorizationPolicy?

On the other hand, we can not whitelist port 8080 because that port is where the api of the service is exposed. But...if we get to expose prometheus api in other port, how can we disable RBAC policy (1.3) on a expecific port?

**Comment by yangminzhu** [comment]
One quick way is just to run `kubectl get <prometheus-pod> -n istio-system` to see how many containers it has. If it's only one, then definitely it's not mTLS because there is no sidecar inside it. You could also follow https://archive.istio.io/v1.4/docs/ops/common-problems/security-issues/#ensure-proxies-enforce-policies-correctly to turn on the `rbac:debug` logging on your service and check the logging.

The pod `istio-ingressgateway` itself is an Envoy so it doesn't need sidecar, or you could think like it only has sidecar and doesn't have application container.

> if we get to expose prometheus api in other port, how can we disable RBAC policy (1.3) on a expecific port?

Yes, this is totally possible, you just need to put the port using the `destination.port` constraint in ServiceRole and bind it with a ServiceRoleBinding that grants permissions to all (`*`): https://archive.istio.io/v1.4/docs/reference/config/security/constraints-and-properties/

Note, In RBAC policy,  the `destination.port` is the service port (not the workload port). In the new AuthZ policy, it has first-class field `ports` and it's the workload port (not the service port because the whole new AuthZ policy is based on workload and not service): https://archive.istio.io/v1.4/docs/reference/config/security/authorization-policy/

**Comment by aalmazanarbs** [comment]
Thank you again @yangminzhu.

Following your advices our final solution is (keeping same port):

```
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: access
  namespace: namespace
spec:
  rules:
  - services: ["service.namespace.svc.cluster.local"]
    methods: ["GET"]
    paths: ["/stats/prometheus"]
```

```
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: access
  namespace: namespace
spec:
  subjects:
  - properties:
      source.namespace: "istio-system"
  roleRef:
    kind: ServiceRole
    name: "access"
```

Since the prometheus pod is in the istio-system, the RBAC works and ServiceRole is allowed only to that namespace. But this is a security problem because, in the istio-system names are the ingress so the endpoint may be exposed to outside cluster but it is filtered in the apigateway. I know another solution is move prometheus or ingress to other namespace but the best solution will be **source.principal: "cluster.local/ns/istio-system/sa/prometheus"** works.
