### ISSUE TITLE
Operator doesn't create serviceaccount "istiod-service-account"

### ISSUE THREAD

**Issue by esnible** [istio/istio#21532]
I discovered this by deleting my `istio-system` namespace, then installing with

```
kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: default
  values:
    global:
       imagePullPolicy: Always
       sds:
         enabled: false
EOF
```

The istiod pod is not created; `kubectl -n istio-system describe rs istiod-6698f8794c` reports
  ```Warning  FailedCreate  58s (x16 over 3m42s)  replicaset-controller  Error creating: pods "istiod-6698f8794c-" is forbidden: error looking up service account istio-system/istiod-service-account: serviceaccount "istiod-service-account" not found```

The problem is entirely YAML generation.  The same `IstioOperator`, fed to `istioctl manifest apply` or `istioctl manifest generate`, does create the serviceaccount "istiod-service-account".

Running `istioctl manifest apply` on the same file left the Deployments unchanged but allowed the istiod Pod to start.

However, the ingress rs failed with '"istio-ingressgateway-service-account" not found' and the prometheus rs failed with 'serviceaccount "prometheus" not found'.
