### ISSUE TITLE
Multicluster Replicated control planes with operator controller

### ISSUE THREAD

**Issue by elfinhe** [istio/istio#21544]
I am testing [multicluster/gateways/](https://preliminary.istio.io/docs/setup/install/multicluster/gateways/) with controller mode operator for https://github.com/istio/istio/issues/21435

Istio Version: istio-1.5.0-beta.3
K8s version: 1.15.8-gke.3
Nodes: 4

**Bug description**

1. Follow the [controller guide](https://preliminary.istio.io/docs/setup/install/standalone-operator/) to install Istio operator controller.
1. Follow the [multicluster user guide](https://preliminary.istio.io/docs/setup/install/multicluster/gateways/) to install multicluster mesh.

The same IstioOperator.yaml installs 2 different sets of pods by using controller-mode and istioctl respectively. The the ones installed by controller never reached to a AVAILABLE status.

```
kubectl get deploy -n istio-system 
NAME                   READY   UP-TO-DATE   AVAILABLE   AGE
istio-ingressgateway   0/1     1            0           6m58s
istiod                 1/1     1            1           6m54s
prometheus             0/1     1            0           6m56s
```

IstioOperator.yaml
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  addonComponents:
    istiocoredns:
      enabled: true

  components:
    egressGateways:
      - name: istio-egressgateway
        enabled: true

  values:
    global:
      # Provides dns resolution for global services
      podDNSSearchNamespaces:
        - global
        - "{{ valueOrDefault .DeploymentMeta.Namespace \"default\" }}.global"

      multiCluster:
        enabled: true

      controlPlaneSecurityEnabled: true

    # Multicluster with gateways requires a root CA
    # Cluster local CAs are bootstrapped with the root CA.
    security:
      selfSigned: false

    gateways:
      istio-egressgateway:
        env:
          # Needed to route traffic via egress gateway if desired.
          ISTIO_META_REQUESTED_NETWORK_VIEW: "external"
```

**Expected behavior**
No difference with what is installed by istioctl

**Steps to reproduce the bug**

1. Follow the [controller guide](https://preliminary.istio.io/docs/setup/install/standalone-operator/) to install Istio operator controller.
1. Follow the [multicluster user guide](https://preliminary.istio.io/docs/setup/install/multicluster/gateways/) to install multicluster mesh.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

Istio Version: istio-1.5.0-beta.3
K8s version: 1.15.8-gke.3
Nodes: 4

**Environment where bug was observed (cloud vendor, OS, etc)**
Client Linux, Server GKE.
