### ISSUE TITLE
istioctl ignores global.k8sIngress.enabled=false parameter

### ISSUE THREAD

**Issue by Henrike42** [istio/istio#21577]
**Bug description**
When running __istioctl__ with:
````
istioctl manifest apply --set global.k8sIngress.enabled=false
````
which is even the default, the default gateway _ingressgateway_ in the istio-system namespace is created.

[x ] Configuration Infrastructure
[ ] Docs
[x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
 I expect that no default gateway is created.

**Steps to reproduce the bug**
Run istioctl with the following value setting:
````
istioctl manifest apply --set global.k8sIngress.enabled=false 
````
Check created gateways:
````
kubectl get gateways --all-namespaces 
````

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**
istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
that setting is for kubernetes Ingress support it does not control the gateway deployment. Try `istioctl profile dump minimal` to see how to disable it (I'm on mobile so I cannot check)

**Comment by richardwxn** [comment]
If you want to disable the built-in ingressgateway, run istioctl manifest apply -f with below
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: false
```

**Comment by Henrike42** [comment]
Hopefully, there is not a misunderstanding, I do want to have the istio ingressgateway service as a load balancer in the istio-system namespace. 

However, I don't want to have a preconfigured instance of type gateways.networking.istio.io, because the generated one opens http ports for all hosts. 
`````
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  labels:
    operator.istio.io/component: IngressGateway
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.4.3
    release: istio
  name: ingressgateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
`````
