### ISSUE TITLE
Logging with Fluentd task

### ISSUE THREAD

**Issue by esnible** [istio/istio#21586]
The testing spreadsheet has "Logging with Fluentd" as a P1 although the banner for the istio.io docs has  **DEPRECATED**.  ("ISTIODOCSTASKSOBSERVABILITYUSING MIXER FOR TELEMETRY (DEPRECATED)LOGSLOGGING WITH MIXER AND FLUENTD").  Anyway, I tried to follow this task.

To reproduce, I installed Istio and visited https://preliminary.istio.io/docs/tasks/observability/mixer/logs/fluentd/

I then downloaded and `kubectl apply` -ed the _logging-stack.yaml_ from that page.  I did `kubectl apply -f samples/bookinfo/telemetry/fluentd-istio.yaml` and visited the Book Info UI and clicked reload a bunch of times and saw it update.

I brought up the Kibana UI and clicked “Set up index patterns” .  I was unable to put `*` in and the UI protested with

```
Couldn't find any Elasticsearch data
You'll need to index some data into Elasticsearch before you can create an index pattern. Learn how.
```

I don't know if Mixer v2 supports Fluentd by default.  I installed Istio using the Operator with

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: default
  components:
  values:
    global:
       imagePullPolicy: Always
       sds:
         enabled: false
       mtls:
         enabled: true
```

If other options are now needed, they should be presented here.
