### ISSUE TITLE
1.5 operator does not work well with customizations

### ISSUE THREAD

**Issue by sdake** [istio/istio#21590]
**Bug description**
1.5 operator does not work well with customizations.

A simple reproducer is present in the bug report.

**Expected behavior**
egress gateway is created.

**Steps to reproduce the bug**
follow installation steps.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.5-dev

**How was Istio installed?**
standalone operator with IOP:
```
sdake@beast-01:~/go/src/istio.io/istio/operator/deploy/crds$ cat istio*cr.yaml
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  hub: gcr.io/istio-testing
  tag: 1.5-dev
  profile: default
  components:
    egressGateways:
    - name: istio-egressgateway
      enabled: true
```

**Environment where bug was observed (cloud vendor, OS, etc)**
Bare metal K8s + metallb + calico AIO deployment. It also reproduces in any other environment.
