### ISSUE TITLE
istioctl manifest generate -o does not output CoreDNS manifests

### ISSUE THREAD

**Issue by elfinhe** [istio/istio#21601]
istioctl manifest generate -o does not output CoreDNS manifests to a folder.

I am using istioctl 1.4.4.

istioctl manifest generate -f below.yaml -o /tmp/a-temp-folder/

```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  coreDNS:
    enabled: true
```
I cannot find coreDNS in the in output folder. By by using `istioctl manifest generate -f below.yaml `, *without `-o`*, I can get coreDNS related manifests.

**Bug description**

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
