### ISSUE TITLE
Upgrading Istio from 1.4.5 -> 1.5.beta.5 via Helm/Tiller upgrade doc fails

### ISSUE THREAD

**Issue by jpapejr** [istio/istio#21648]
**Bug description**
Starting with a Helm-deployed Istio 1.4.3 demo profile deployment with mTLS enabled mesh-wide and trying to apply the docs at https://preliminary.istio.io/docs/setup/upgrade/cni-helm-upgrade/#upgrade-steps to update the control plane results in a failure complaining about existing assets in the cluster that didn't apply in a previous release

**Expected behavior**
Helm upgrade command should apply the updated Istio release from the release archive successfully

**Steps to reproduce the bug**
1. Install Helm with the proper service account per the [docs](https://istio.io/docs/setup/install/helm/)
2. Deploy Istio mesh via https://istio.io/docs/setup/install/helm/#option-2-install-with-helm-and-tiller-via-helm-install using the option in the `Mutual TLS enabled` tab in step 5.
3. Observe that the mesh components are deployed and are marked running as expected. Perform any desired smoke testing (i.e. curl -vvv ingressgateway-lb-ip:15020/healthz/ready)
4. Download the Istio 1.5-beta3 release, move to that directory and follow these [docs](https://preliminary.istio.io/docs/setup/upgrade/cni-helm-upgrade/#control-plane-upgrade) to do the Helm Upgrade mutually exclusive upgrade path.
5. After command `helm upgrade istio install/kubernetes/helm/istio --namespace istio-system` note the following error: 

```
 helm upgrade istio install/kubernetes/helm/istio --namespace istio-system

UPGRADE FAILED
Error: kind ServiceAccount with the name "istio-reader" already exists in the cluster and wasn't defined in the previous release. Before upgrading, please either delete the resource from the cluster or remove it from the chart
Error: UPGRADE FAILED: kind ServiceAccount with the name "istio-reader" already exists in the cluster and wasn't defined in the previous release. Before upgrading, please either delete the resource from the cluster or remove it from the chart
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
bin/istioctl version && kubectl version
client version: 1.5.0-beta.3
control plane version: 1.5.0-beta.3
data plane version: 1.5.0-beta.3 (2 proxies)
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"1bea6c00a7055edef03f1d4bb58b773fa8917f11", GitTreeState:"clean", BuildDate:"2020-02-11T20:13:57Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3+IKS", GitCommit:"f60ec7e9eb2b798894c7c3997d0d9d506bbd9615", GitTreeState:"clean", BuildDate:"2020-02-12T10:08:16Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**
Helm 

**Environment where bug was observed (cloud vendor, OS, etc)**
IKS, Ubuntu 18 workers , v1.17.3+IKS

[istio-dump.tar.gz](https://github.com/istio/istio/files/4268508/istio-dump.tar.gz)

**Comment by linsun** [comment]
@sdake thoughts?  Do we still support helm upgrade in 1.5?

**Comment by howardjohn** [comment]
> already exists in the cluster and wasn't defined in the previous release

Where did it come from? Did you create this yourself?

**Comment by jpapejr** [comment]
I did not create it. It had to be created during the 1.4.3 helm deployment. I’ll double check on Monday.

**Comment by howardjohn** [comment]
Hm maybe it's from one of those "post install" jobs we had back then? I'll take a look if I find some time

**Comment by jpapejr** [comment]
From 1.4.3 `install/kubernetes/helm/istio`
```
jtpape in kubernetes/helm/istio at dev
➜ cat ./templates/clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: istio-reader
rules:
  - apiGroups: ['']
    resources: ['nodes', 'pods', 'services', 'endpoints', "replicationcontrollers"]
    verbs: ['get', 'watch', 'list']
  - apiGroups: ["extensions", "apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]

jtpape in kubernetes/helm/istio at dev
➜ ./templates/clusterrolebinding.yaml
zsh: permission denied: ./templates/clusterrolebinding.yaml

jtpape in kubernetes/helm/istio at dev
➜ cat ./templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istio-multi
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-reader
subjects:
- kind: ServiceAccount
  name: istio-multi
  namespace: {{ .Release.Namespace }}
```

But those specs are also in 1.5.beta.4 and 1.4.5, too.. Not sure why it complained. Will continue to look..
