### ISSUE TITLE
Modifying a sidecar resource does not seem to update envoy properly

### ISSUE THREAD

**Issue by rolandkool** [istio/istio#21650]
**Bug description**
In a service mesh where services are protected using authorizationpolicies (rbac), changing egress rules in a Sidecar resource don't properly update envoy.

Example: serviceA.namespaceA talks to serviceB.namespaceB. serviceB has an authorization policy to allow namespaceA:

```
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-serviceA
  namespace: namespaceB
spec:
  rules:
  - from:
    - source:
        namespaces:
        - namespaceA
```
Without the Sidecar resource in place for serviceA, serviceA is able to to connect to serviceB.

Now add the following Sidecar resource in namespaceA:

```
---
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
  namespace: namespaceA
spec:
  egress:
  - hosts:
    - "./*"
    - "istio-system/*"
```

This will cause the envoy proxy to drop all service information/routes for serviceB.namespaceB. It also causes serviceA to be denied by serviceB with a 403 (as it now bypasses envoy, so no mtls/identity)

Next, modify the Sidecar resource and include `- "namespaceB/*"`

The expected behaviour is that serviceA should now be able to talk to serviceB again, however serviceB keeps responding with a 403. The envoy clusters/config_dump overviews do show serviceB listed. Only after restarting the pods behind serviceA will serviceA be able to talk to serviceB.

**Expected behavior**
See bug description

**Steps to reproduce the bug**
See bug description

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4.5

**How was Istio installed?**
istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by howardjohn** [comment]
> The envoy clusters/config_dump overviews do show serviceB listed

Seems like we have 3 points here: 1. working (expected), 2. not working (expected), 3. not working (when we expect it to work)

Maybe it would be useful to compare the config dump from 1 and 3 and we can see if maybe its being partially updated or similar?

**Comment by rolandkool** [comment]
I've created a gist with a working and a broken config: https://gist.github.com/rolandkool/d5bf1e6167b91829d3b5e589abf6f1cf

Working config was dumped from a pod where a full sidecar config was deployed.

The broken config was obtained following these steps:
1. remove the sidecar config, verify all still works
2. add sidecar config with one service missing (the `currencysvc`)
3. verify I get rbac error
4. apply the full config again, including access to `currencysvc`. rbac error remains

So I verified this with the hipstershop demo app.

Also tried to reproduce this with a simple hello world sample application, but I couldn't.
Could it be related to GRPC? (hipstershop demo app uses that a lot while my hello world app just uses http)

**Comment by stewartbutler** [comment]
Picking this up. Working on replicating it still.

**Comment by stewartbutler** [comment]
Replicated it yesterday, and I believe I've identified the cause (but not why it is happening yet). Hypothesis at the moment is that it has something to do with MTLS permissive mode.

@rolandkool are you guys using MTLS? How is your mesh policy configured?

**Comment by rolandkool** [comment]
Yes, we're using mTLS permissive mode.
Our policy looks like this:
```
  originIsOptional: true
  origins:
  - jwt:
      issuer: <ourissuer>
      jwksUri: https://url.to/keys
  peers:
  - mtls:
      mode: PERMISSIVE
  principalBinding: USE_ORIGIN
```

**Comment by incfly** [comment]
I'm able to reproduce, but however, you can change the sidecar resource to 

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
  namespace: namespaceA
spec:
  egress:
  - hosts:
    - "./*"
    - "namespaceB/*"
    - "istio-system/*"
```

This way, request starts to succeed again.

**Comment by incfly** [comment]
I can't reproduce, it works fine with me.

```
unzip github.zip && cd github && source seutp.sh
istio # install
setup # create workloads && crd
check # nsa sucess, return 127.0.0.1
sidecar-no-nsb # sidecar without namespaceB in namespaceA's egress blocks
check # RBAC denined, 403 error
sidecar-nsb # sidecar adding `namespaceB` to egress block
check # success, as expeted
```


[github.zip](https://github.com/istio/istio/files/4320871/github.zip)

**Comment by incfly** [comment]
i'm using istio-1.4.5 release, bin/istioctl manifest apply install.

**Comment by incfly** [comment]
my setup above in the script might have some deviations, those i don't think matter though, e.g. i don't have a jwt in the mesh policy block.

but let me know your findings, we can together narrow down the part that makes difference. @stewartbutler @rolandkool

**Comment by rolandkool** [comment]
@incfly I've also not been able to reproduce it using regular http services, which seems you are using as well (the httpbin and sleep images). I tried with istio's helloworld example.
However, I've been able to reproduce it with the hipstershop demo app, which uses a lot of grpc to communicate between services. Not sure if there's an easier grpc test app that can be used for reproduction. In my hipstershop setup, I've deployed each microservice in its own namespace in order to apply specific configuration to each component.

**Comment by incfly** [comment]
Interesting. Can you tell me between which two services from hipster apps
are demonstrating these behaviors? All pretty much applied to all gRPC
client to gRPC server? Or it's between traffic to redis, which is TCP?

Just want to see if this only exhibits between one particular pair of
client/server or applied to all gRPC client service.

**Comment by rolandkool** [comment]
I tested with the frontend to currency service connection.
Did not test with cart and redis as I deployed those together in one namespace.

On a working hipstershop, I deployed a sidecar resource without adding the currency service to the egress rules. The currency service has a authorization policy in place to allow the frontend namespace. I reloaded the page and the currency service returned an RBAC issue (expected as the call bypasses envoy now). I updated the sidecar resource to include the currency service but it keeps broken, until I restart the frontend pod.

**Comment by rolandkool** [comment]
So, removing a namespace from the sidecar resource has immediate effect on the pod, but restoring it does not.

**Comment by incfly** [comment]
works for me again for hipster app.. roughly steps

- default hipster demo
- move currency svc to nsb namespace, modify frontend currencyservice addr to point to nsb as well.
- configure authz/mtls as above
- sidecar missing egress to nsb, fail
- add egress block, succeed.

**Comment by stewartbutler** [comment]
@incfly to confirm, you have MTLS in permissive mode? I cannot replicate if MTLS is in strict mode, but if you set it to permissive you see the behavior.

**Comment by incfly** [comment]
I'm using PERMISSIVE as you can see in my uploaded zip file, github/mtls

```yaml
apiVersion: "authentication.istio.io/v1alpha1"
kind: "MeshPolicy"
metadata:
  name: "default"
spec:
  peers:
  - mtls:
      mode: PERMISSIVE
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "default"
  namespace: "istio-system"
spec:
  host: "*.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```
