### ISSUE TITLE
Not clear how to enable telemetryv2 on 1.5 with Helm

### ISSUE THREAD

**Issue by Stono** [istio/istio#21682]
**Bug description**
Hi, 
I cannot work out how to enable telemetry v2 on 1.5, using the helm installer.  Looking at the templates it doesn't look like it is supported unless you're using `istioctl` as the files live under `1.5.0-beta.4/install/kubernetes/operator/charts/istio-control`.

That would be fine if I had a manual process like we do in 1.4, but the current documentation:

https://istio.io/docs/ops/configuration/telemetry/in-proxy-service-telemetry/

Links to https://raw.githubusercontent.com/istio/istio/release-1.4/tests/integration/telemetry/stats/prometheus/testdata/metadata_exchange_filter.yaml

Which doesn't exist in the 1.5: branch

https://raw.githubusercontent.com/istio/istio/release-1.5/tests/integration/telemetry/stats/prometheus/testdata/metadata_exchange_filter.yaml

And that page doesn't exist in the 1.5 docs:
https://preliminary.istio.io/docs/ops/configuration/telemetry/in-proxy-service-telemetry/

I appreciate helm support is going away, but as it stands it's not _fully_ gone, and is pretty critical to how we template our istio deployment.  I was hoping to avoid migrating to istioctl as part of this release (which segfaults for me anyway https://github.com/istio/istio/issues/21683).

**Expected behavior**
Either support v2 installation via helm, or provide updated documentation for how to enable it manually.  Ideally i would like to use helm to generate the `stats-filter-1.4`, `stats-filter-1.5`, `metadata-exchange-1.4`, `metadata-exchange-1.5`

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.5.0-beta4

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by seeruk** [comment]
Also experiencing this issue currently, the main challenge I'm facing is trying to install Kiali 1.15, where they've moved to support Telemetry V2 (and removed support for V1). The installation for Kiali 1.14 is failing for me for some reason. I can't enable Telemetry V2 as I'm using Helm still, and I can't migrate away from Helm because `istioctl` still has some bugs (with open issues already reported) around ingress gateway support.

Feeling a bit trapped with a half-working system right now, sadly, and it's very unclear at the moment how the migration from Helm to `istioctl` is really supposed to work. How much manual effort is supposed to be involved? Will it technically be 2 installations of Istio running? Will my ingress gateways be recreated (and thus, load balancers recreated, and thus DNS records needing to be updated, and thus downtime because one is going to disappear?)

**Comment by Stono** [comment]
Agreed, it's a ballache for sure. 
Long story for short; you can't use `istioctl`, and you can't use `helm`, you need to use both :-( 

We personally use `helm` and then have a separate `stuff-istio-installer-cant-do` chart with the EnvoyFilters in (or just apply them manually in some other way).  You can get the EnvoyFilters from the istioctl output.  But here they are:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: metadata-exchange-1.4
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: ANY # inbound, outbound, and gateway
        proxy:
          proxyVersion: '1\.4.*'
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.wasm
          config:
            config:
              configuration: envoy.wasm.metadata_exchange
              vm_config:
                runtime: envoy.wasm.runtime.null
                code:
                  inline_string: envoy.wasm.metadata_exchange
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: metadata-exchange-1.5
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: ANY # inbound, outbound, and gateway
        proxy:
          proxyVersion: '1\.5.*'
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.wasm
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.config.filter.http.wasm.v2.Wasm
            value:
              config:
                configuration: envoy.wasm.metadata_exchange
                vm_config:
                  runtime: envoy.wasm.runtime.null
                  code:
                    local:
                      inline_string: envoy.wasm.metadata_exchange
```

and 

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: stats-filter-1.4
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_OUTBOUND
        proxy:
          proxyVersion: '1\.4.*'
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
              subFilter:
                name: "envoy.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.wasm
          config:
            config:
              root_id: stats_outbound
              configuration: |
                {
                  "debug": "false",
                  "stat_prefix": "istio",
                }
              vm_config:
                vm_id: stats_outbound
                runtime: envoy.wasm.runtime.null
                code:
                  inline_string: envoy.wasm.stats
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        proxy:
          proxyVersion: '1\.4.*'
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
              subFilter:
                name: "envoy.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.wasm
          config:
            config:
              root_id: stats_inbound
              configuration: |
                {
                  "debug": "false",
                  "stat_prefix": "istio",
                }
              vm_config:
                vm_id: stats_inbound
                runtime: envoy.wasm.runtime.null
                code:
                  inline_string: envoy.wasm.stats
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        proxy:
          proxyVersion: '1\.4.*'
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
              subFilter:
                name: "envoy.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.wasm
          config:
            config:
              root_id: stats_outbound
              configuration: |
                {
                  "debug": "false",
                  "stat_prefix": "istio",
                }
              vm_config:
                vm_id: stats_outbound
                runtime: envoy.wasm.runtime.null
                code:
                  inline_string: envoy.wasm.stats
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: stats-filter-1.5
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_OUTBOUND
        proxy:
          proxyVersion: '1\.5.*'
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
              subFilter:
                name: "envoy.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.wasm
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.config.filter.http.wasm.v2.Wasm
            value:
              config:
                root_id: stats_outbound
                configuration: |
                  {
                    "debug": "false",
                    "stat_prefix": "istio",
                  }
                vm_config:
                  vm_id: stats_outbound
                  runtime: envoy.wasm.runtime.null
                  code:
                    local:
                      inline_string: envoy.wasm.stats
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        proxy:
          proxyVersion: '1\.5.*'
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
              subFilter:
                name: "envoy.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.wasm
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.config.filter.http.wasm.v2.Wasm
            value:
              config:
                root_id: stats_inbound
                configuration: |
                  {
                    "debug": "false",
                    "stat_prefix": "istio",
                  }
                vm_config:
                  vm_id: stats_inbound
                  runtime: envoy.wasm.runtime.null
                  code:
                    local:
                      inline_string: envoy.wasm.stats
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        proxy:
          proxyVersion: '1\.5.*'
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
              subFilter:
                name: "envoy.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.wasm
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.config.filter.http.wasm.v2.Wasm
            value:
              config:
                root_id: stats_outbound
                configuration: |
                  {
                    "debug": "false",
                    "stat_prefix": "istio",
                  }
                vm_config:
                  vm_id: stats_outbound
                  runtime: envoy.wasm.runtime.null
                  code:
                    local:
                      inline_string: envoy.wasm.stats
```
