### ISSUE TITLE
Istio ingressgate  doesn't pass x-forward-for

### ISSUE THREAD

**Issue by catman002** [istio/istio#21746]
The version of istio I used is 1.45. I found the bug of ingressgate during the use, as follows:
1) My access form is simply as follows: client - > ingressgate - > service1
2) When the client initiates the access, the header carries "x-forward-for". After being forwarded by ingressgate, services1 cannot get "x-forward-for" content. After testing, the ingressgate did not forward the header "x-forwarded-for" at all (no similar problem occurred in other customized headers).

This bug is very important to me. I hope it can be solved

---------
-- Solutions to the above problems：create EnvoyFilter

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: rsl-envoyfilter
  namespace: istio-system
spec:
  workloadLabels:
    app: istio-ingressgateway
  filters:
    - listenerMatch:
        portNumber: 58080
        listenerType: GATEWAY
      filterName: envoy.lua
      filterType: HTTP
      filterConfig:
        inlineCode: |
          function envoy_on_request(request_handle)
            local xff_header = request_handle:headers():get("X-Forwarded-For")
            local first_ip = string.gmatch(xff_header, "(%d+.%d+.%d+.%d+)")();
            first_ip = string.gsub(first_ip, ",", "")
            request_handle:headers():add("X-Custom-User-IP", first_ip);
          end
```
Run the above envoyfilter, and we can get the real IP through request.headers ["x-custom-user-ip"] in the application or rule(mixer) or instance(mixer)

**Comment by esnible** [comment]
There is a long discussion of this this at https://github.com/istio/istio/issues/7679

There are security implications.  Someone from @istio/wg-security-maintainers might be able to explain Istio's approach to this header.

**Comment by myidpt** [comment]
Thanks Ed. We will take a look.

**Comment by JimmyCYJ** [comment]
@andraxylia, is there any helm flag that customer can set in order to pass x-forward-for? 
/cc @lambdai

**Comment by catman002** [comment]
@esnible   The above discussion does not work for 1.45: modify "use_remote_address " or ”externalTrafficPolicy“

**Comment by JimmyCYJ** [comment]
Tentatively assign to @lambdai for networking team to triage. Feel free to assign back to me.

**Comment by incfly** [comment]
hi @catman002 to ensure we understand your requirements, are you saying that a request (from curl to ingress gateway ip) already contains a  `X-forwarded-headers: 1.2.3.4` header, but after ingress gateway forward req to httpbin service, the xff is gone?

Or you are suggesting that ingress gateway envoy does not append the client IP it sees by itself to the list?

**Comment by catman002** [comment]
Solution, create EnvoyFilter：
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: rsl-envoyfilter
  namespace: istio-system
spec:
  workloadLabels:
    app: istio-ingressgateway
  filters:
    - listenerMatch:
        portNumber: 58080
        listenerType: GATEWAY
      filterName: envoy.lua
      filterType: HTTP
      filterConfig:
        inlineCode: |
          function envoy_on_request(request_handle)
            local xff_header = request_handle:headers():get("X-Forwarded-For")
            local first_ip = string.gmatch(xff_header, "(%d+.%d+.%d+.%d+)")();
            first_ip = string.gsub(first_ip, ",", "")
            request_handle:headers():add("X-Custom-User-IP", first_ip);
          end
```
Run the above envoyfilter, and we can get the real IP through request.headers ["x-custom-user-ip"] in the application or rule(mixer) or instance(mixer)
