### ISSUE TITLE
[operator] Ability to push array elements with overlays

### ISSUE THREAD

**Issue by Mokto** [istio/istio#21863]
**Describe the feature request**
Hi, maybe I missed something, but it seems like it's impossible to just push elements to an array when patching something with `overlays`.

**Describe alternatives you've considered**
Passing everything as a value, but it's not super maintainable.

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio
spec:
  profile: default
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        overlays:
          - kind: Deployment
            name: istio-ingressgateway
            patches:
            - path: spec.template.spec.containers.[name:istio-proxy].ports
              value:
              - containerPort: 15020
                protocol: TCP
              - containerPort: 80
                protocol: TCP
              - containerPort: 443
                protocol: TCP
              - containerPort: 15029
                protocol: TCP
              - containerPort: 15030
                protocol: TCP
              - containerPort: 15031
                protocol: TCP
              - containerPort: 15032
                protocol: TCP
              - containerPort: 15443
                protocol: TCP
              - containerPort: 15011
                protocol: TCP
              - containerPort: 8060
                protocol: TCP
              - containerPort: 853
                protocol: TCP
              - containerPort: 15090
                name: http-envoy-prom
                protocol: TCP
              - containerPort: 5632
                protocol: TCP
```

I would just like to push 
```
              - containerPort: 5632
                protocol: TCP
```
[X] Configuration Infrastructure
[X] Docs
[X] Installation

Thanks!
