### ISSUE TITLE
k8s.affinity configuration doesn't seem to work using installer

### ISSUE THREAD

**Issue by rushsinging** [istio/istio#21915]
Sorry if I'm missing something here.

**Bug description**

I got a error report using `k8s.affinity`  settings.

* [x] Configuration Infrastructure
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  profile: default
  components:
    ingressGateways:
    - enabled: true
      k8s:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: zone
                  operator: In
                  values:
                  - istio
```

**Expected behavior**

I want to set ingressgateway.affinity by `istioctl  manifest apply -f config.yaml`.

**Steps to reproduce the bug**

When I excute `istioctl  manifest apply -f config.yaml`. I got:

```
proto: tag has too few fields: "-"
Error: failed to apply manifests: failed to generate manifest: validation errors (use --force to override):
validate path Components.K8S.Affinity.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution, value: istio, expected ptr, got string
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio: 1.5.0
k8s: v1.15.10

**How was Istio installed?**

by istioctl
