### ISSUE TITLE
NATS protocol

### ISSUE THREAD

**Issue by Tharun-Sabbu** [istio/istio#21927]
**Bug description**
we've injected istio-proxy to the java application with NATS client trying to connect to NATS Server that is external to the cluster. And we were getting 503, I tried accessing NATS server from pilot pod which is running with istio-proxy in  istio-system namespace and seems to be working fine. However, accessing the NATS Server from the application seems to be giving 503. I tried configuring serviceentry and virtualservice with tcp protocol, but doesn't seems to be fixing the issue.

ServiceEntry:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: nats.test.com
spec:
  hosts:
  - nats.test.com
  location: MESH_EXTERNAL
  ports:
  - number: 8443
    name: tcp
    protocol: TCP
  resolution: DNS
```
```
VirtualService:
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nats-external
spec:
  hosts:
    - nats.test.com
  tcp:
  - match:
    - port: 8443
    timeout: 60s
    route:
      - destination:
          host: nats.test.com
          port:
            number: 8443
        weight: 100
```

**Version 
Istio v1.4.3

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
