### ISSUE TITLE
we can't use istioctl 1.5.0 to enabling policy enforcement

### ISSUE THREAD

**Issue by sd797994** [istio/istio#21988]
**Bug description**
we download istio 1.5.0 and  use command "istioctl manifest apply --set values.global.disablePolicyChecks=false --set values.pilot.policy.enabled=true" to initialize。when all istio contrainer was running and i use command "kubectl -n istio-system get cm istio -o jsonpath="{@.data.mesh}" | grep disablePolicyChecks" to check disablePolicyChecks it's output true。
we downgrade istio version to 1.4.6 use the same command, it's output "disablePolicyChecks:false"
like this:
[https://github.com/istio/istio/issues/19139#issue-527400476](url)
i think this bug is fixed by 1.4.x, but it reappears in the new version(1.5.0)

**Comment by charypar** [comment]
I hit the same issue, it seems like the `disablePolicyChecks` configuration is now only respected when `value.policy.mixer.enabled` (mixer, not pilot) is set to true. The following config snippet works for me:

```
spec:
  profile: demo
  values:
    global:
      disablePolicyChecks: false
    mixer:
      policy:
        enabled: true
```
