### ISSUE TITLE
EnvoyFilter Patch doesn't work per documentation

### ISSUE THREAD

**Issue by karthikt-yahoo** [istio/istio#21982]
**Bug description**
Managing NETWORK_FILTER via EnvoyFilter is not working as expected.  Applying the manifest referenced in the documents https://istio.io/docs/reference/config/networking/envoy-filter/ and https://github.com/istio/istio/wiki/EnvoyFilter-Samples has no effect.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: xff
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: ANY
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager"
          idle_timeout: 299s
          xff_num_trusted_hops: 1
```

Also tried with context: GATEWAY,  no effect. no logs in pilot. 

**Expected behavior**
idle_timeout and xff_num_trusted_hops values should reflect in filter envoy.http_connection_manager config.

**Steps to reproduce the bug**
Try any Network filter patch documented in https://github.com/istio/istio/wiki/EnvoyFilter-Samples

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Istio 1.4.6 
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"archive", BuildDate:"2020-01-21T20:41:54Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"archive", BuildDate:"2020-01-21T20:41:54Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by hzxuzhonghu** [comment]
```
kind: EnvoyFilter
metadata:
  name: xff
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: ANY
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager"
          xff_num_trusted_hops: 1
          common_http_protocol_options:
            idle_timeout: 299s

```

Apply this instead when you are using istio >= 1.4

**Comment by karthikt-yahoo** [comment]
> ```
> kind: EnvoyFilter
> metadata:
>   name: xff
>   namespace: istio-system
> spec:
>   configPatches:
>   - applyTo: NETWORK_FILTER
>     match:
>       context: ANY
>       listener:
>         filterChain:
>           filter:
>             name: "envoy.http_connection_manager"
>     patch:
>       operation: MERGE
>       value:
>         typed_config:
>           "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager"
>           xff_num_trusted_hops: 1
>           common_http_protocol_options:
>             idle_timeout: 299s
> ```
> 
> Apply this instead when you are using istio >= 1.4
```
Error from server: error when creating "test.yaml": admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: Envoy filter: can't unmarshal Any nested proto *envoy_config_filter_network_http_connection_manager_v2.HttpConnectionManager: unknown field "common_http_protocol_options" in envoy_config_filter_network_http_connection_manager_v2.HttpConnectionManager 
```

**Comment by andrewshaoyu** [comment]
i find the same problem in istio 1.3.8 with default envoy 1.12.0.

from envoydocs 1.12.0 also use the common_http_protocol_options.idle_timeout.
[envoy recommend config](https://www.envoyproxy.io/docs/envoy/v1.12.0/configuration/best_practices/edge)

but i can not set common_http_protocol_options.idle_timeout.

**Comment by clsacramento** [comment]
Hi all, in case it helps, with Istio 1.5, this works:
$ cat envoyfilter3.yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: hcm-tweaks
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER # http connection manager is a filter in Envoy
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager"
          xff_num_trusted_hops: 5
          max_request_headers_kb: 90

Main difference versus the doc: removed WorkloadSelector, removed sni, added type_config."@type"

**Comment by ceastman-ibm** [comment]
I am running into a similar issue trying to get the new envoy filter working in an istio 1.5.4 cluster: I get the following error from the following yaml:
Error [IST0106] (EnvoyFilter envoy-filter-1-6.istio-system) Schema validation error: Envoy filter: unknown field "typed_config" in envoy_api_v2.Listener

[envoy-filter-1-6.yaml.zip](https://github.com/istio/istio/files/4886761/envoy-filter-1-6.yaml.zip)

**Comment by howardjohn** [comment]
Lots of issues here:
* First was invalid config, which was updated
* Then we had not updated to include filters, which is fixed in #23932
* ` Envoy filter: unknown field "typed_config" in envoy_api_v2.Listener` - I suspect wrong version of istioctl or something... not sure. I tried in my cluster and it works. Can you open a new issue with more details about version, config dump?

**Comment by mojiQAQ** [comment]
i am running on istio 1.6.0 cluster, and get errors: 
configuration is invalid: Envoy filter: can't unmarshal Any nested proto *envoy_config_filter_network_http_connection_manager_v2.HttpConnectionManager: unknown field "common_http_protocol_options" in envoy_config_filter_network_http_connection_manager_v2.HttpConnectionManager

and my envoyfilter is follows
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: h2-control
spec:
  configPatches:
  - applyTo: NETWORK_FILTER # http connection manager is a filter in Envoy
    match:
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager"
          stream_idle_timeout: 60s
          request_timeout: 60s
          http2_protocol_options:
            max_concurrent_streams: 100
            initial_stream_window_size: 65536 # 64 KiB
            initial_connection_window_size: 1048576 # 1 MiB
          common_http_protocol_options:
            idle_timeout: 60s # 1 hour
```

**Comment by acumartini** [comment]
I am having a similar issue with 1.9.x docs. EnvoyFilter applies as expected, but changes nothing in the proxy configs when I inspect them using `istioctl`

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: custom-protocol
  namespace: istio-config # as defined in meshConfig resource.
spec:
  configPatches:
  - applyTo: NETWORK_FILTER # http connection manager is a filter in Envoy
    match:
      # context omitted so that this applies to both sidecars and gateways
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
        name: "envoy.filters.network.http_connection_manager"
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          common_http_protocol_options:
            idle_timeout: 3600s # 1 hour
          http2_protocol_options:
            max_concurrent_streams: 500
            initial_stream_window_size: 65536 # 64 KiB
            initial_connection_window_size: 1048576 # 1 MiB
          stream_idle_timeout: 300s # 5 mins, must be disabled for long-lived and streaming requests
          request_timeout: 300s # 5 mins, must be disabled for long-lived and streaming requests
```
