### ISSUE TITLE
Unable to configure multiple Istio Ingress Gateways 

### ISSUE THREAD

**Issue by linuxbsdfreak** [istio/istio#21989]
**Bug description**
Unable to setup Multiple Istio Ingress Gateways via Istio Operator install method

[X ] Configuration Infrastructure
[X] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

With the below configuration. Istio should have been able to configure multiple istio ingress gateways.

**Steps to reproduce the bug**

With the following config
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: default
  addonComponents:
    grafana:
      enabled: true
      k8s:
        replicaCount: 1
    istiocoredns:
      enabled: false
    kiali:
      enabled: true
      k8s:
        replicaCount: 1
    prometheus:
      enabled: true
      k8s:
        replicaCount: 1
    tracing:
      enabled: true
  components:
    sds:
      enabled: true
    policy:
      enabled: false
    telemetry:
      enabled: false
    egressGateways:
    - enabled: true
      k8s:
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
      name: istio-egressgateway
    ingressGateways:
    - enabled: true
      k8s:
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
      name: istio-ingressgateway
    - enabled: true
      k8s:
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
      name: istio-ingressgateway-new
  global:
    proxy:
       accessLogEncoding: TEXT
       accessLogFile: /dev/stdout
       autoInject: enabled
    sds:
       enabled: true
  values:
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: true
        debug:
        serviceAnnotations:
          cert.gardener.cloud/secretname: "wildcard-ssl-secret"
          dns.gardener.cloud/class: garden
          dns.gardener.cloud/dnsnames: "*.istio.example.ondemand.com"
          dns.gardener.cloud/ttl: "300"
        labels:
          app: istio-ingressgateway
          istio: istio-ingressgateway
        sds:
          enabled: false
        externalTrafficPolicy: Local
      istio-ingressgateway-new:
        autoscaleEnabled: true
        debug:
        serviceAnnotations:
          cert.gardener.cloud/secretname: "wildcard-ssl-secret-new"
          dns.gardener.cloud/class: garden
          dns.gardener.cloud/dnsnames: "*.new.example.ondemand.com"
          dns.gardener.cloud/ttl: "300"
        labels:
          app: istio-ingressgateway
          istio: istio-ingressgateway
        sds:
          enabled: false
        externalTrafficPolicy: Local
```
Also the below config does not work

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: default
  addonComponents:
    grafana:
      enabled: true
      k8s:
        replicaCount: 1
    istiocoredns:
      enabled: false
    kiali:
      enabled: true
      k8s:
        replicaCount: 1
    prometheus:
      enabled: true
      k8s:
        replicaCount: 1
    tracing:
      enabled: true
  components:
    sds:
      enabled: true
    policy:
      enabled: false
    telemetry:
      enabled: false
    egressGateways:
    - enabled: true
      k8s:
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
      name: istio-egressgateway
    ingressGateways:
    - name: istio-ingressgateway
      namespace: istio-system
      enabled: true
      k8s:
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
        serviceAnnotations:
          cert.gardener.cloud/secretname: "wildcard-ssl-secret"
          dns.gardener.cloud/class: garden
          dns.gardener.cloud/dnsnames: "*.istio.example.ondemand.com"
          dns.gardener.cloud/ttl: "300"
      label:
        app: istio-ingressgateway
        istio: istio-ingressgateway
    - name: istio-ingressgateway-new
      namespace: istio-system
      enabled: true
      k8s:
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
        serviceAnnotations:
          cert.gardener.cloud/secretname: "wildcard-ssl-secret-new"
          dns.gardener.cloud/class: garden
          dns.gardener.cloud/dnsnames: "*.new.example.ondemand.com"
          dns.gardener.cloud/ttl: "300"
      label:
        app: istio-ingressgateway-new
        istio: istio-ingressgateway-new
  global:
    proxy:
       accessLogEncoding: TEXT
       accessLogFile: /dev/stdout
       autoInject: enabled
    sds:
       enabled: true
```
In this case the istio ingress pod does not come up and gives the following error

```
[Envoy (Epoch 0)] [2020-03-09 10:15:05.915][27][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 14, no healthy upstream
[Envoy (Epoch 0)] [2020-03-09 10:15:05.915][27][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:54] Unable to establish new stream
2020-03-09T10:15:06.171189Z     info    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 0 rejected; lds updates: 0 successful, 0 rejected
2020-03-09T10:15:08.172077Z     info    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 0 rejected; lds updates: 0 successful, 0 rejected
2020-03-09T10:15:10.171229Z     info    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 0 rejected; lds updates: 0 successful, 0 rejected
2020-03-09T10:15:12.171071Z     info    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 0 rejected; lds updates: 0 successful, 0 rejected
2020-03-09T10:15:14.171058Z     info    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 0 rejected; lds updates: 0 successful, 0 rejected
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
istioctl version --remote
client version: 1.5.0
egressgateway version: 1.5-alpha.0e6be865d62c9b36d634896850ddcb3005e04352
istio-ingressgateway version:
pilot version: 1.5-alpha.0e6be865d62c9b36d634896850ddcb3005e04352
data plane version: 1.5-alpha.0e6be865d62c9b36d634896850ddcb3005e04352 (4 proxies)
```

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-12T13:43:46Z", GoVersion:"go1.13.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Standalone operator install method

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS with Gardener K8s Cluster
