### ISSUE TITLE
(IstioOperator) User defined ingress gateways not working in 1.5

### ISSUE THREAD

**Issue by marshallford** [istio/istio#21996]
**Bug description**

This is a two part issue:

1. When defining a custom/user defined ingress gateway in a IstioOperator CR the operator spins up a standard `istio-ingressgateway` pod/deploy/svc with the standard labels.

2. When using the Helm `values.gateways` escape hatch to set fields like `loadBalancerIP`, the operator fails to install Istio with an error that suggests `values.gateways.external` isn't valid.

**Expected behavior**

Istiod spins up along with the user defined ingress gateway.

**Steps to reproduce the bug**

1. `istioctl operator init`

2. `kubectl apply -f istiocontrolplane.yaml`

istiocontrolplane.yaml:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiocontrolplane
  namespace: istio-operator
spec:
  profile: minimal
  components:
    ingressGateways:
      - name: external
        enabled: true
        label:
          istio: external
          app: istio-ingressgateway
  values:
    gateways:
      external:
        foo: bar
    sidecarInjectorWebhook:
      rewriteAppHTTPProbe: true
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
istioctl: 1.5.0
kubectl: Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
helm: N/A
```

**How was Istio installed?**

`istioctl operator init`

**Environment where bug was observed (cloud vendor, OS, etc)**

Kubeadm 1.17.3, Ubuntu 18.04.

**Comment by howardjohn** [comment]
maybe related https://github.com/istio/istio/issues/21989

**Comment by ostromart** [comment]
Fixed, see top level tracker for gateway issues: https://github.com/istio/istio/issues/22253.

**Comment by marshallford** [comment]
I don't think this is fixed. Folks in https://github.com/istio/istio/issues/19263 are running into issues with the labels and selectors matching all of the ingress gateways. In addition, I was unable to use the Helm values escape hatch for custom gateways in 1.5.1. Helm values will be useful while the enum issue is sorted out: https://github.com/istio/istio/issues/22347.

**Comment by marshallford** [comment]
@ostromart Any update on this? It appears the only workaround is extensive overlays.

**Comment by askmeegs** [comment]
+1, having the same issue on 1.5.1 -- defined an ILB gateway in addition to the default ingress gateway, but the labels and selectors of the ILB gateway are corresponding to the ingressgateway. 

operator spec- 
```
    - enabled: true
      name: istio-ilbgateway
      label:
        app: "istio-ilbgateway"
        istio: "ilbgateway"
```

service info - 

```
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.5.1
    release: istio
  name: istio-ilbgateway
  namespace: istio-system
```
