### ISSUE TITLE
IPwhitelisting/Blacklisting not working in Istio 1.5

### ISSUE THREAD

**Issue by linuxbsdfreak** [istio/istio#21992]
**Bug description**

IPwhitelisting/Blacklisting not working in Istio 1.5 as per 
https://istio.io/docs/tasks/security/authorization/authz-ingress/#ip-based-allow-list-and-deny-list

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Based on the below config the traffic should be denied.

**Steps to reproduce the bug**

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: default
  addonComponents:
    grafana:
      enabled: true
      k8s:
        replicaCount: 1
    istiocoredns:
      enabled: false
    kiali:
      enabled: true
      k8s:
        replicaCount: 1
    prometheus:
      enabled: true
      k8s:
        replicaCount: 1
    tracing:
      enabled: true
  components:
    sds:
      enabled: true
    policy:
      enabled: false
    telemetry:
      enabled: false
    egressGateways:
    - enabled: true
      k8s:
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
      name: istio-egressgateway
    ingressGateways:
    - enabled: true
      k8s:
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
      name: istio-ingressgateway
  global:
    proxy:
       accessLogEncoding: TEXT
       accessLogFile: /dev/stdout
       autoInject: enabled
    sds:
       enabled: true
  values:
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: true
        debug:
        serviceAnnotations:
          cert.gardener.cloud/secretname: "wildcard-ssl-secret"
          dns.gardener.cloud/class: garden
          dns.gardener.cloud/dnsnames: "*.istio.example.ondemand.com"
          dns.gardener.cloud/ttl: "300"
        labels:
          app: istio-ingressgateway
          istio: istio-ingressgateway
        sds:
          enabled: false
        externalTrafficPolicy: Local
```

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gw-helloworld-v2
  namespace: hello-v2
spec:
  selector:
    istio: istio-ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "helloworld-v2.istio.example.ondemand.com"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: "wildcard-ssl-secret"
    hosts:
    - "helloworld-v2.istio.example.ondemand.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-helloworld-v2
  namespace: hello-v2
spec:
  hosts:
  - "helloworld-v2.istio.example.ondemand.com"
  gateways:
  - gw-helloworld-v2
  http:
  - match:
    - uri:
        exact: /
    rewrite:
      uri: /hello
    route:
    - destination:
        host: helloworld.hello-v2.svc.cluster.local
        port:
          number: 5000
```
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ingress-policy
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: istio-ingressgateway
  action: DENY
  rules:
  - from:
    - source:
       ipBlocks: ["xx.xx.xx.xx/25"]
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
istioctl version --remote
client version: 1.5.0
egressgateway version: 1.5-alpha.0e6be865d62c9b36d634896850ddcb3005e04352
istio-ingressgateway version:
pilot version: 1.5-alpha.0e6be865d62c9b36d634896850ddcb3005e04352
data plane version: 1.5-alpha.0e6be865d62c9b36d634896850ddcb3005e04352 (4 proxies)
```
**How was Istio installed?**

Standalone operator install method

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS with Gardener K8s Cluster

**Comment by yangminzhu** [comment]
@linuxbsdfreak The operator yaml seems incorrect, could you double check if it can generate the install yaml?

As discussed previously on slack, if you only want to set `externalTrafficPolicy: local`, could you try the following minimal operator yaml and test if the source IP works for you?
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        service:
          externalTrafficPolicy: local
```

**Comment by linuxbsdfreak** [comment]
Hi @yangminzhu . Following is the config

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: default
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        service:
          externalTrafficPolicy: Local
  global:
    proxy:
       accessLogEncoding: TEXT
       accessLogFile: /dev/stdout
       autoInject: enabled
    sds:
       enabled: true
  values:
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: true
        serviceAnnotations:
          cert.gardener.cloud/secretname: "wildcard-ssl-secret"
          dns.gardener.cloud/class: garden
          dns.gardener.cloud/dnsnames: "*.istio.poc.example.ondemand.com"
          dns.gardener.cloud/ttl: "300"
        labels:
          app: istio-ingressgateway
          istio: istio-ingressgateway
        sds:
          enabled: false
```
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ingress-policy
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  action: DENY
  rules:
  - from:
    - source:
      ipBlocks: ["xx.xx.xx.xx/25"]
```

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gw-helloworld-v1
  namespace: hello-v1
spec:
  selector:
    istio: istio-ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "helloworld-v1.istio.poc.example.ondemand.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-helloworld-v1
  namespace: hello-v1
spec:
  hosts:
  - "helloworld-v1.istio.poc.example.ondemand.com"
  gateways:
  - gw-helloworld-v1
  http:
  - match:
    - uri:
        exact: /
    rewrite:
      uri: /hello
    route:
    - destination:
        host: helloworld.hello-v1.svc.cluster.local
        port:
          number: 5000
```

The above configuration also does not work.

**Comment by yangminzhu** [comment]
@linuxbsdfreak Could you follow https://istio.io/docs/ops/common-problems/security-issues/#ensure-proxies-enforce-policies-correctly to get some debug logging of the Envoy? (Note you need to replace the productpage with istio-ingressgateway and please send some requests after you turned on the debug logging).

**Comment by linuxbsdfreak** [comment]
@yangminzhu . Following is the debug logs from the istio-ingressgateway pod

```
[Envoy (Epoch 0)] [2020-03-11 10:47:52.335][47][debug][rbac] [external/envoy/source/extensions/filters/http/rbac/rbac_filter.cc:68] checking request: remoteAddress: 10.250.97.186:26058, localAddress: 100.96.0.138:443, ssl: uriSanPeerCertificate: , subjectPeerCertificate: , headers: ':authority', 'helloworld-v1.istio.example.ondemand.com'
':path', '/'
':method', 'GET'
'user-agent', 'curl/7.47.0'
'accept', '*/*'
'x-forwarded-for', '10.250.97.186'
'x-forwarded-proto', 'https'
'x-envoy-internal', 'true'
'x-request-id', 'f51d283d-0c34-4c55-b30d-d692876d0330'
'x-envoy-decorator-operation', 'helloworld.hello-v1.svc.cluster.local:5000/'
'x-envoy-peer-metadata', 'Ch4KDElOU1RBTkNFX0lQUxIOGgwxMDAuOTYuMC4xMzgKmQIKBkxBQkVMUxKOAiqLAgodCgNhcHASFhoUaXN0aW8taW5ncmVzc2dhdGV3YXkKEwoFY2hhcnQSChoIZ2F0ZXdheXMKFAoIaGVyaXRhZ2USCBoGVGlsbGVyCh8KBWlzdGlvEhYaFGlzdGlvLWluZ3Jlc3NnYXRld2F5CiEKEXBvZC10ZW1wbGF0ZS1oYXNoEgwaCjc5Y2Y3ODc0NGYKEgoHcmVsZWFzZRIHGgVpc3Rpbwo5Ch9zZXJ2aWNlLmlzdGlvLmlvL2Nhbm9uaWNhbC1uYW1lEhYaFGlzdGlvLWluZ3Jlc3NnYXRld2F5CiwKI3NlcnZpY2UuaXN0aW8uaW8vY2Fub25pY2FsLXJldmlzaW9uEgUaAzEuNQoaCgdNRVNIX0lEEg8aDWNsdXN0ZXIubG9jYWwKLwoETkFNRRInGiVpc3Rpby1pbmdyZXNzZ2F0ZXdheS03OWNmNzg3NDRmLTlsa3A5ChsKCU5BTUVTUEFDRRIOGgxpc3Rpby1zeXN0ZW0KXQoFT1dORVISVBpSa3ViZXJuZXRlczovL2FwaXMvYXBwcy92MS9uYW1lc3BhY2VzL2lzdGlvLXN5c3RlbS9kZXBsb3ltZW50cy9pc3Rpby1pbmdyZXNzZ2F0ZXdheQqtAQoRUExBVEZPUk1fTUVUQURBVEESlwEqlAEKIAoOYXdzX2FjY291bnRfaWQSDhoMNzk4NDMwNTE1NjQ0CigKFWF3c19hdmFpbGFiaWxpdHlfem9uZRIPGg1ldS1jZW50cmFsLTFjCigKD2F3c19pbnN0YW5jZV9pZBIVGhNpLTA4ZDliNzAwMWVlZmFhNTFmChwKCmF3c19yZWdpb24SDhoMZXUtY2VudHJhbC0xCjkKD1NFUlZJQ0VfQUNDT1VOVBImGiRpc3Rpby1pbmdyZXNzZ2F0ZXdheS1zZXJ2aWNlLWFjY291bnQKJwoNV09SS0xPQURfTkFNRRIWGhRpc3Rpby1pbmdyZXNzZ2F0ZXdheQ=='
'x-envoy-peer-metadata-id', 'router~100.96.0.138~istio-ingressgateway-79cf78744f-9lkp9.istio-system~istio-system.svc.cluster.local'
, dynamicMetadata:
[Envoy (Epoch 0)] [2020-03-11 10:47:52.335][47][debug][rbac] [external/envoy/source/extensions/filters/http/rbac/rbac_filter.cc:107] enforced allowed
```

I am not sure why the local IP of the ELB is getting populated and not the real client IP. Do i have to configure something ? Istio ingress gateway launches a ELB on AWS.

**Comment by linuxbsdfreak** [comment]
Hi @yangminzhu . I was able to get it running by changing the LB to NLB on AWS with 

```
  values:
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: true
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
```

The reason could be as follows

The ELB does forward the X-Forwarded-For but it is re-written by istio and since the ELB load-balances on your ingress-gateway's service nodePort, that's what envoy sees that's because the ingress-gateway configures envoy with useRemoteAddress: true a.k.a you are on the internet don't believe the headers you see.

But NLB are not http proxies they are L4 loadbalancers, so the ingress gateway sees the connection as coming from your public IP
