### ISSUE TITLE
Default sidecar not applied to consumer only services

### ISSUE THREAD

**Issue by robertpanzer** [istio/istio#22034]
**Bug description**

**Expected behavior**
The documentation at https://istio.io/docs/reference/config/networking/sidecar/ Note 2 suggests that it is possible to create a default Sidecar configuration in the config root namespace that applies as a fallback if there is no specific or default Sidecar in the config namespace of a proxy.
However this only works for proxies that are associated with a service, consumer only proxies are not subject to the default Sidecar configuration.
This is in particular problematic for consumer only applications, like for example Jobs.

**Steps to reproduce the bug**
Install Istio and configure a Sidecar in the namespace `istio-system`:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  creationTimestamp: "2020-03-10T08:00:41Z"
  generation: 1
  name: default
  namespace: istio-system
  resourceVersion: "166482"
  selfLink: /apis/networking.istio.io/v1alpha3/namespaces/istio-system/sidecars/default
  uid: a971cfaf-1355-488f-aa0e-ae2df5f3cdd0
spec:
  egress:
  - hosts:
    - ~/*
```
This Sidecar resource should prevent pushing anything to proxies that don't have any explicitly declared dependencies.

Then install a Deployment that has no Service:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testcurl
  namespace: sr-test
spec:
  selector:
    matchLabels:
      app: testcurl
  replicas: 1
  template:
    metadata:
      labels:
        app: testcurl
    spec:
      containers:
      - name: testcurl
        image: tutum/curl
        command:
          - sleep
          - "100000"
```

I expect that no dynamic clusters are pushed to the proxy for this application. 
However I get this result from the admin endpoint:
```console
$ curl -s localhost:15000/clusters|cut -f 1 -d ':'|sort|uniq
BlackHoleCluster
InboundPassthroughClusterIpv4
PassthroughCluster
inbound|15020|mgmt-15020|mgmtCluster
outbound|14250||jaeger-collector.istio-system.svc.cluster.local
outbound|14267||jaeger-collector.istio-system.svc.cluster.local
outbound|14268||jaeger-collector.istio-system.svc.cluster.local
outbound|15010||istio-pilot.istio-system.svc.cluster.local
outbound|15011||istio-pilot.istio-system.svc.cluster.local
outbound|15014||istio-citadel.istio-system.svc.cluster.local
outbound|15014||istio-galley.istio-system.svc.cluster.local
outbound|15014||istio-pilot.istio-system.svc.cluster.local
outbound|15014||istio-sidecar-injector.istio-system.svc.cluster.local
outbound|15020||istio-ingressgateway.istio-system.svc.cluster.local
outbound|15029||istio-ingressgateway.istio-system.svc.cluster.local
outbound|15030||istio-ingressgateway.istio-system.svc.cluster.local
outbound|15031||istio-ingressgateway.istio-system.svc.cluster.local
...
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Istio 1.4.6

**How was Istio installed?**
With Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
Local Kubernetes 1.16.6 on Docker for Mac
