### ISSUE TITLE
k8s.service configuration validation doesn't work when externalIPs are set

### ISSUE THREAD

**Issue by kzimmizk** [istio/istio#22048]
**Bug description**
`istioctl manifest` throws a validation error when installing an `IstioOperator` with externalIPs configured for a ClusterIP type service via k8s.service

**Expected behavior**
When k8s.service.type=ClusterIP and k8s.service.externalIPs is set to a valid string[] value, `istioctl manifest generate` should generate a valid Service object yaml configuration without requiring the --force flag.

**Steps to reproduce the bug**
Create IstioOperator config control-plane.yaml like
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        service:
          type: ClusterIP
          externalIPs:
          - "1.2.3.4"
```
running `istioctl manifest generate -f control-plane.yaml` causes an error output:
```bash
validate path Components.K8S.Service, value: 1.2.3.4, expected ptr, got string
```
running `istioctl manifest generate -f control-plane.yaml --force` renders the expected output, and `istioctl manifest apply -f control-plane.yaml --force` installs the desired Service to the cluster.

**Version**
1.5.0

**How was Istio installed?**
istioctl

I believe this issue was raised tangentially in https://github.com/istio/istio/issues/19517
