### ISSUE TITLE
is idleTimeout only affect to upstream?

### ISSUE THREAD

**Issue by darkrasid** [istio/istio#22073]
**Expected behavior**

Hi, I found strange behavior about `idleTimeout` in DestinationRule.
From [docs](https://istio.io/docs/reference/config/networking/destination-rule), the idleTimeout means `The idle timeout for upstream connection pool connections.`.

I think that means, it affects destination envoy to application in below flow.

ingress gateway(envoy) --> [ (destination envoy) -> application ]

However I found many `TIME_WAIT` in ingress gateway node after setting idleTimeout to 5s.
```
trafficPolicy:
  connectionPool:
    http:
      idleTimeout: 5s
```

If idleTimeout affects to upstream only, I think `TIME_WAIT` should be in destination envoy.

Am I misunderstand something?

**Steps to reproduce the bug**

1. set small idleTimeout 
2. send traffic a little.
3. find TIME_WAIT in ingress Gateway node ` netstat -napo | grep timewait | grep ${application_pod_ip}

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio 1.2.5
k8s 1.11
helm 2.9.1

**How was Istio installed?**
helm

**Environment where bug was observed (cloud vendor, OS, etc)**
ubuntu

**Comment by yxue** [comment]
If you applied the destination rule to ingress gateway, the behavior is expected. `upstream connection` means the connection from ingress gateway envoy to destination envoy from the perspective of the ingress gateway. The `idleTimeout` applies to all upstream connections, i.e., connections from ingress gateway to destination envoy.

```
ingress gateway(envoy) --> [ (destination envoy) -> application ]
```

**Comment by darkrasid** [comment]
@yxue Thank you for you answer! 

However I created Destination rule for destination envoy.
```
  host: app.namespace.svc.cluster.local
  trafficPolicy:
    connectionPool:
      http:
        idleTimeout: 5s
      tcp:
        tcpKeepalive:
          interval: 10s
          time: 45s
```

 I don't have sidecar on ingress gateway, I think if I create DR for ingress gateway, it doesn't work, isn't it?

**Comment by yxue** [comment]
The ingress gateway contains only one Envoy pod (sidecar is Envoy). If you applied the above configuration, the gateway will be applied because it specifies the destination rule to the `app.namespace.svc.cluster.local`. The destination rule teaches the gateway how to connect to the host, e.g., connect timeout, load balancing policy.

**Comment by darkrasid** [comment]
Aha. You mean, if I create DR for some host, every envoy in mesh world (include ingress gateway, egress Gateway and something) will know connection spec for the host. I understand. Thank you.
ingress gateway(envoy) --> [ (destination envoy) -> application ]

How about

**Comment by darkrasid** [comment]
@yxue  Thank you for you answer.

 You mean, if I create DR for some host, every envoy in mesh world (include ingress gateway, egress Gateway and something) will know connection spec for the host. 
I understand. Thank you.

```
[ ingress gateway(envoy) ]--- 5s idle Timeout and keepalive 45s --> [ (destination envoy) -----> application ]
```

How about ` [ (destination envoy) -> application ]` flow?

I understand my DR make 5s idle Timeout from ingressGateway to destination envoy. Is the DR make same effect?

```
[ ingress gateway(envoy) ]--- 5s idle Timeout and keepalive 45s --> [ (destination envoy) --- 5s idle Timeout and keepalive 45s --> application ]
```

I know application can have its idle timeout however I'm experiencing a little 503 error between destination envoy and application. I guess this happen because  idle Timeout  of envoy is greater than application has.

**Comment by hzxuzhonghu** [comment]
>[ (destination envoy) --- 5s idle Timeout and keepalive 45s --> application ]

This is not right, by default no timeout here

**Comment by darkrasid** [comment]
@hanxiaoshuai Thank you for answer.
Am.. Let me make clear. 

```
[ ingress gateway(envoy) ]--- here --> [ (destination envoy) -----> application ]
```

From @yxue answer and my experimentation, I understand that I can create Destination Rule to set idleTimeout, keepalive or something between ingressGateway with sidecar envoy. 
Semething like this.
```
  # here is applications svc address but all envoy will be applied.
  host: app.namespace.svc.cluster.local 
  trafficPolicy:
    connectionPool:
      http:
        idleTimeout: 5s
```

However I'm still confusing about this flow 
[ ingress gateway(envoy) ]--- not here --> [ (destination envoy) --- here ---> application ]

 If DR is applied incoming request, how  I can set same things between sidecar envoy to application?

**Comment by darkrasid** [comment]
I found that DR is appied to both traffic.

With DR
```
  host: app.namespace.svc.cluster.local 
  trafficPolicy:
    connectionPool:
      http:
        idleTimeout: 10s
```

`[ ingress gateway(envoy) ]--- idle 10s --> [ (destination envoy) --- idle 10s ---> application ]`


I will close this issue.

**Comment by stanxing** [comment]
> [ (destination envoy) --- idle 10s ---> application ]

@darkrasid 

According to my test, If I config idle timeout globally, the behavior is consistent with yours.

if I only config idle timeout for single subset instead of  global, it is incorrect.  idle timeout 10s only work on client envoy(ingress gateway)

Between destination envoy and application, It depends on the default value of envoy OR application timeout set in code. 

YAML such as:

```
  host: story-service.xxx.svc.cluster.local
  subsets:
  - labels:
      version: default
    name: default
    trafficPolicy:
      connectionPool:
        http:
          idleTimeout: 10s
```
The is envoy config:

client envoy => destination envoy 

![image](https://user-images.githubusercontent.com/23288646/142375917-9e545fec-c149-4242-b611-28553615dbf6.png)

destination inbound direction config( cannot see idleTimeout config)

```
~ istioctl pc cluster story-service-66c595f9dd-28hwj --direction inbound -o json
[
    {
        "name": "inbound|3000||",
        "type": "ORIGINAL_DST",
        "connectTimeout": "10s",
        "lbPolicy": "CLUSTER_PROVIDED",
        "circuitBreakers": {
            "thresholds": [
                {
                    "maxConnections": 4294967295,
                    "maxPendingRequests": 4294967295,
                    "maxRequests": 4294967295,
                    "maxRetries": 4294967295,
                    "trackRemaining": true
                }
            ]
        },
        "cleanupInterval": "60s",
        "upstreamBindConfig": {
            "sourceAddress": {
                "address": "127.0.0.6",
                "portValue": 0
            }
        },
        "metadata": {
            "filterMetadata": {
                "istio": {
                    "services": [
                        {
                            "host": "story-service.xxx.svc.cluster.local",
                            "name": "story-service",
                            "namespace": "xxx"
                        }
                    ]
                }
            }
        }
    }
]
```
maybe  is this a bug?  

cc @yxue @bianpengyuan
