### ISSUE TITLE
mTLS is not working in 1.5

### ISSUE THREAD

**Issue by linuxbsdfreak** [istio/istio#22080]
**Bug description**
mTLS is not working in 1.5

[X ] Configuration Infrastructure
[ X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
With the below policy the mTLS should have been working

**Steps to reproduce the bug**

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: default
  addonComponents:
    grafana:
      enabled: true
      k8s:
        replicaCount: 1
    istiocoredns:
      enabled: false
    kiali:
      enabled: true
      k8s:
        replicaCount: 1
    prometheus:
      enabled: true
      k8s:
        replicaCount: 1
    tracing:
      enabled: true
  components:
    sds:
      enabled: true
    policy:
      enabled: false
    telemetry:
      enabled: false
    egressGateways:
    - enabled: true
      k8s:
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
      name: istio-egressgateway
    ingressGateways:
    - enabled: true
      k8s:
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
        service:
          externalTrafficPolicy: Local
      name: istio-ingressgateway
  global:
    proxy:
       accessLogEncoding: TEXT
       accessLogFile: /dev/stdout
       autoInject: enabled
    sds:
       enabled: true
  values:
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: true
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
          cert.gardener.cloud/secretname: "wildcard-ssl-secret"
          dns.gardener.cloud/class: garden
          dns.gardener.cloud/dnsnames: "*.istio.poc.state-fx.shoot.canary.k8s-hana.ondemand.com"
          dns.gardener.cloud/ttl: "300"
        labels:
          app: istio-ingressgateway
          istio: istio-ingressgateway
        sds:
          enabled: false
```

Apply the following policy under istio-system and another namespace 
https://istio.io/docs/tasks/security/authentication/authn-policy/#namespace-wide-policy

```
k get peerauthentications.security.istio.io --all-namespaces
NAMESPACE      NAME      AGE
hello-v1       default   23m
istio-system   default   26m
```

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gw-helloworld-v1
  namespace: hello-v1
spec:
  selector:
    istio: istio-ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "helloworld-v1.istio.example.ondemand.com"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: "wildcard-ssl-secret"
    hosts:
    - "helloworld-v1.istio.example.ondemand.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-helloworld-v1
  namespace: hello-v1
spec:
  hosts:
  - "helloworld-v1.istio.example.ondemand.com"
  gateways:
  - gw-helloworld-v1
  http:
  - match:
    - uri:
        exact: /
    rewrite:
      uri: /hello
    route:
    - destination:
        host: helloworld.hello-v1.svc.cluster.local
        port:
          number: 5000

```

```
istioctl authn tls-check helloworld-v1-578dd69f69-th2rv.hello-v1 | grep "helloworld"
helloworld.hello-v1.svc.cluster.local:5000                                AUTO       DISABLE     -          None                                         
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
client version: 1.5.0
egressgateway version: 1.5-alpha.5649adaef16df84597fcb697b8abfe04607fc01f
istio-ingressgateway version:
pilot version: 1.5-alpha.5649adaef16df84597fcb697b8abfe04607fc01f
data plane version: 1.5-alpha.5649adaef16df84597fcb697b8abfe04607fc01f (5 proxies), 1.5-alpha.0e6be865d62c9b36d634896850ddcb3005e04352 (2 proxies)

k version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-12T13:43:46Z", GoVersion:"go1.13.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Standalone operator install method

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS with Gardener K8s Cluster
