### ISSUE TITLE
Invalid validation error in istiod

### ISSUE THREAD

**Issue by rshriram** [istio/istio#22100]
Certain fields in the API are wrapped in OneOf however, none of those fields are required. For example, 
in EnvoyFilter, k8s refuses to accept a match object that has just the context field set https://istio.io/docs/reference/config/networking/envoy-filter/#EnvoyFilter-EnvoyConfigObjectMatch  eventhough it is a very valid object. The validation error is that atleast one of listenerMatch/clusterMatch/routeMatch must be set, which is not true per the API spec. 

As a result of this validation, upgrade to istiod breaks as the older configs without listener/cluster/route match fail to be added to the k8s cluster.

There are similar issues in other APIs. For example, destination rule's loadbalancer settings has a oneOf simple/consistentHash and a localityLbSetting. https://istio.io/docs/reference/config/networking/destination-rule/#LoadBalancerSettings . This validation now forces everyone to pick a hashing algorithm when trying to set the localityLbSetting. 

**Bug description**

Example config
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: example
  namespace: httpbin
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      context: GATEWAY
    patch:
      operation: ADD
      value:
        connect_timeout: 0.100s
        load_assignment:
          cluster_name: foobar
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 172.17.0.2
                    port_value: 32554
        name: foobar
        protocol_selection: USE_DOWNSTREAM_PROTOCOL
        respect_dns_ttl: true
        transport_socket:
          config:
            common_tls_context:
              validation_context: {}
          name: envoy.transport_sockets.tls
        type: STRICT_DNS
  workloadSelector:
    labels:
      app: gateway
```

**Expected behavior**
no validation error
**Steps to reproduce the bug**
see above
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.5
**How was Istio installed?**
operator
**Environment where bug was observed (cloud vendor, OS, etc)**
kind
