### ISSUE TITLE
Configure retry in Istio for HTTPS external services

### ISSUE THREAD

**Issue by ahmadsayed** [istio/istio#22114]
I am trying to configure retry in Istio for HTTPS external services , I already build a mock to test its response with different error, the current behavior as follow
if the service return 503 -> ISTIO retry 3 times I see it logged in my mock services  in less than 2 seconds and return with 503 which is expected but  I am expecting more retries
in case of 502, 504 , 500 or any other error it return instantaneously with the error and hit the backend only onetime
The external service is HTTPS, that is why I am using TLS origination
BTW, this behavior is same regardless the retries configuration in virtual services or even if I do not use it all , I assume it is default behavior
I also tried retryon 5xx,  502, and 504 explicitly
I am trying by exec a pod with sidecar already injected and curl the endpoints  using the http:// not https://

Configuration used 
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: test-test-node.au-syd.mybluemix.net
spec:
  hosts:
  - test-test-node.au-syd.mybluemix.net
  ports:
  - number: 80
    name: http-port
    protocol: HTTP
  - number: 443
    name: https-port
    protocol: HTTPS
  resolution: DNS
--
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: node-outbound
spec:
  hosts:
  - test-test-node.au-syd.mybluemix.net
  http:
  - route:
    timeout: 200s
    retries:
      attempts: 15
      perTryTimeout: 5s
      retryOn: 5xx
    - destination:
        host: test-test-node.au-syd.mybluemix.net
        port:
          number: 443
        subset: tls-origination
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: node-red-destination
spec:
  host: test-test-node.au-syd.mybluemix.net
  subsets:
  - name: tls-origination
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: SIMPLE                    
```

**Bug description**

Retry behavior is same regardless the configuration used in virtual services when using external service, it always retry 3 times only for 503 only 

**Expected behavior**

The service will retry the for the number of attempts mentioned in virtual service 15 in my example, for 502,503, 504 
**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istioctl version --remote
client version: 1.5.0
control plane version: 1.5.0
data plane version: 1.5.0 (13 proxies)

kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10+IKS", GitCommit:"18e8565daf60eb3a20c0ac29a7d3a93622659e4d", GitTreeState:"clean", BuildDate:"2020-01-16T04:08:27Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}

**How was Istio installed?**
Helm chart on Kubernetes 1.14, Istio 1.5

**Environment where bug was observed (cloud vendor, OS, etc)**

IBM Cloud Kubernetes Services
Ubuntu 18.04

Related issues
https://github.com/istio/istio/issues/13775

**Comment by hzxuzhonghu** [comment]
@ahmadsayed `retryOn: "500,502,503,504"` is not valid. https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter.html#x-envoy-retry-on

**Comment by ahmadsayed** [comment]
@hzxuzhonghu I tried all combination, 5xx,  or even 503 the problem,
also '      retryOn: gateway-error,connect-failure,refused-stream' 

I even tried to remove the 
whole section 
```
    retries:
      attempts: 15
      perTryTimeout: 5s
      retryOn: "500,502,503,504"
```
the problem that regardless of what I do the behavior is exactly the same 
retry only on 503 3 times

**Comment by ahmadsayed** [comment]
I think i found a way to do it, i tried to use egress gateway with TLS origination , instead of Egress TLS origination and I started to notice the retry behaviors started to change according to the configuration

Do you think this issue still valid, and it need to be handled for egress without gateway as well ??!! 

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: direct-cnn-through-egress-gateway
  namespace: istio-system
spec:
  gateways:
  - istio-egressgateway
  - mesh
  hosts:
  - test-test-node.au-syd.mybluemix.net
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    retries:
      attempts: 5
      retryOn: 5xx
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        port:
          number: 80
        subset: cnn
      weight: 100
  - match:
    - gateways:
      - istio-egressgateway
      port: 80
    retries:
      attempts: 5
      retryOn: 5xx
    route:
    - destination:
        host: test-test-node.au-syd.mybluemix.net
        port:
          number: 443
      weight: 100
```
