### ISSUE TITLE
Using regex in an Authorization Policy operation paths

### ISSUE THREAD

**Issue by GODBS** [istio/istio#22111]
Since PeerAuthentication and RequestAuthentication replaces the alpha Authentication Policy in Istio 1.5, I started using an Authorization Policy in order to put my excluded paths to bypass the JWT validation. I was wondering if it is possible to use regex when defining the paths in a authorization policy. ex:
```
   to:
   - operation:
       methods: ["GET"]
       paths: 
       - /project/.*/issues
```

Thanks in advance for your help
