### ISSUE TITLE
503 response when port name is prefixed with https- (mTLS enabled)

### ISSUE THREAD

**Issue by artursitarski** [istio/istio#22124]
**Bug description**
I have EKS cluster with Istio on it. mTLS is enabled. Traffic flow:
AWS ALB -> Istio IngressGateway -> VirtualService -> Service -> Pod
Configuration of particular components:
```- apiVersion: networking.istio.io/v1alpha3
  kind: Gateway
  metadata:
    name: istio-gateway
    namespace: istio-system
  spec:
    selector:
      istio: ingressgateway
    servers:
    - hosts:
      - '*'
      port:
        name: https-port
        number: 443
        protocol: HTTPS
      tls:
        credentialName: platform-cert
        minProtocolVersion: TLSV1_2
        mode: SIMPLE
```
On ingress gateway we terminate SSL traffic coming from ALB. Then we have configured mtls for Ingressgateway:
```
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: istio-ingress-to-svc
  namespace: istio-system
spec:
  peers:
  - mtls: {}
  targets:
  - name: istio-ingressgateway

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: istio-mutual
  namespace: istio-system
spec:
  host: '*.svc.cluster.local'
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```
Ingress, VirtualService and Service definitions:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pub-alb
  namespace: istio-system
spec:
  rules:
  - host: '*.dev.example.com'
    http:
      paths:
      - backend:
          serviceName: istio-ingressgateway
          servicePort: 443
        path: /*
  - host: '*.example.com'
    http:
      paths:
      - backend:
          serviceName: istio-ingressgateway
          servicePort: 443
        path: /*
status:
  loadBalancer:
    ingress:
    - hostname: XXX.elb.amazonaws.com

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: example
  namespace: playground
spec:
  gateways:
  - istio-system/istio-gateway
  hosts:
  - a1.dev.example.com
  - test.examaple.com
  http:
  - match:
    - port: 443
    route:
    - destination:
        host: application
        port:
          number: 80

apiVersion: v1
kind: Service
metadata:
  labels:
    app: application
    service: application
  name: application
  namespace: playground
spec:
  ports:
  - name: https-web
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    service: application
  type: ClusterIP
```
According to https://archive.istio.io/v1.3/docs/ops/traffic-management/protocol-selection/ I prefixed port name with `https-` as mTLS is enabled - so traffic should be encrypted.
By doing that and curling application endpoint I'm getting
```
upstream connect error or disconnect/reset before headers. reset reason: connection termination
```
In istio-proxy logs (proxy in application pod) I see: `HTTP/1.1" 503 UC,URX`
I can confirm that mTLS is enabled between Ingress and Application:
```
$ istioctl authn tls-check istio-ingressgateway-f96555749-8l57r application.playground.svc.cluster.local
HOST:PORT                                  STATUS     SERVER     CLIENT     AUTHN POLICY       DESTINATION RULE
application.playground.svc.cluster.local:80     OK         mTLS       mTLS       default/playground     istio-mutual/playground
```
`playground` namespace mTLS configuration:
```
apiVersion: v1
items:
- apiVersion: authentication.istio.io/v1alpha1
  kind: Policy
  metadata:
    name: default
    namespace: playground
  spec:
    peers:
    - mtls: {}
```
The thing is that when I rename `application` Service port to be prefixed with `http-` then everything works as expected... **Is it expected behavior?** Or I have something misconfigured? I also sniffed the traffic inside the application container and looks like traffic is encrypted - all traffic grabbed by ngrep is random signs.
Moreover, `application` pod connects to other Services as a part of request processing. Those services have port names prefixed with `https-`. When playing with ports naming I observed such behavior: 
- application svc `https-` -> background svc `https-` - does not work
- application svc `https-` -> background svc `http-` - does not work
- application svc `http-` -> background svc `https-` - do work
- application svc `http-` -> background svc `http-` - does not work

**Expected behavior**
Istio passes encrypted traffic through `https-` prefixed ports when mTLS is enabled. 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.12-eks-eb1860", GitCommit:"eb1860579253bb5bf83a5a03eb0330307ae26d18", GitTreeState:"clean", BuildDate:"2019-12-23T08:58:45Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

$ helm3 version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

$ istioctl version --remote
client version: 1.3.1
citadel version: 1.3.8
galley version: 1.3.8
ingressgateway version: 1.3.8
pilot version: 1.3.8
policy version: 1.3.8
sidecar-injector version: 1.3.8
telemetry version: 1.3.8
```
**How was Istio installed?**
Helm chart using https://storage.googleapis.com/istio-release/releases/1.3.8/charts/

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS
