### ISSUE TITLE
 The visibility of dr is not as expected

### ISSUE THREAD

**Issue by ydh926** [istio/istio#22147]
**Bug description**

When the destinationrule for the same host is located in a different namespace, visibility does not match expectations

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
The order in which the sidecar obtains dr is:  local namespace> export namespace> root namespace

**Steps to reproduce the bug**
1. create dr for same host in different namespace

```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: powerful-b
  namespace: namespace1
spec:
  host: b.namespace1.svc.cluster.local
  subsets:
  - name: subset1
  - name: subset2
```

```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: powerful-b
  namespace: namespace2
spec:
  host: b.namespace1.svc.cluster.local
  subsets:
  - name: subset3
  - name: subset4
```
2. configdump for a sidecar
the expacted cluster for b.namespace1.svc.cluster.local is subset1, subset2. But we may get subset1, subset2, subset3, subset4.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
