### ISSUE TITLE
Kubernetes service with port name start with Http lead to envoy drops outbound TCP traffic

### ISSUE THREAD

**Issue by DanielQujun** [istio/istio#22150]
One day I found my pod can't connect MySQL,  I test curl IP:3306 which return 
`upstream connect error or disconnect/reset before headers. reset reason: connection termination` 

meanwhile  mysql -h IP:3306 returns nothing but hanging

After some troubleshooting, I  found it caused by a Kubernetes service which port is 3306 and portname is http-3306. and this will create A 0.0.0.0_3306 HTTP listener in the envoy. 

I understand that

> the services cannot use the same port number for different protocols
>https://istio.io/docs/ops/deployment/requirements/

but did not know this will decline all TCP traffic.

My question is if there is  HTTP service using 3306 port, how can I connect to my MySQL service. either Can I restrict this service only affect itself namespace but not all like virtualservice config  "exportTo ."

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Pod could connect MYSQL Service

**Steps to reproduce the bug**
Create svc whit portname start with http
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: teee1
    service: teee1
  name: teee1
spec:
  ports:
  - name: http-3306
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: teee1
  type: ClusterIP
```

**Version **
```
$ istioctl version --remote
client version: 1.5.0
control plane version: 1.5.0
data plane version: 1.5.0 (8 proxies)

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
helm

**Comment by howardjohn** [comment]
There should also he a listener on MySqlIp_3306. Is there not?

**Comment by DanielQujun** [comment]
Not, The MYSQL Service is in an external cluster.

**Comment by howardjohn** [comment]
I see. You will probably need to create a ServiceEntry for mysql. Its basically the same issue as https://github.com/istio/istio/issues/16458

**Comment by DanielQujun** [comment]
thanks for your advice, 
IMHO user should not register an external service into mesh explicitly since we already use ALLOW_ANY as the default mode.

Furthermore, in some situations the developer does not has the privilege to create a ServiceEntry, he needs to ask for administrator which is not convenient.

**Comment by howardjohn** [comment]
I agree, just suggesting that is how to get things to work today

**Comment by DanielQujun** [comment]
Got it, Hope we can found a better approach. :smile:

**Comment by DanielQujun** [comment]
since https://github.com/istio/istio/pull/17169 has merged, closing.

**Comment by hustshawn** [comment]
Hi @DanielQujun , I got a similar issue as you, and I know this bug could be fixed in a future release 1.6.x. But may I know how you mitigate this, except for asking the application side to change the port name of service?
To me, a ServiceEntry not help.

**Comment by hustshawn** [comment]
To me is actually redis from AWS EalsticCache. My SE looks like this, tried to comment/uncomment the options. But no lucky.

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: redis
spec:
  hosts:
  # - "*.apse1.cache.amazonaws.com"
  - "*"
  location: MESH_EXTERNAL
  ports:        
  - number: 6379
    name: redis    
    protocol: TCP 
    # protocol: REDIS
  resolution: DNS
```

**Comment by DanielQujun** [comment]
I simple merged that pr to my pilot~

I speculate  that is because your serviceentry is lack of address field since TCP protocol add an address to register a listener.

Maybe you can try:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: redis
spec:
  hosts:
  - "*.apse1.cache.amazonaws.com"
  addresses:
  - 192.168.0.220  # your service ip
  location: MESH_EXTERNAL
  ports:        
  - number: 6379
    name: redis    
    protocol: TCP 
    # protocol: REDIS
  resolution: NONE
```
