### ISSUE TITLE
[1.5] [IstioOperator] Enabling meshConfig.enableAutoMtls does not change field in config

### ISSUE THREAD

**Issue by marshallford** [istio/istio#22169]
Like the title suggests: On a fresh install of the Istio Operator and Istio `spec.meshConfig.enableAutoMtls` does not set the `enableAutoMtls` field in the istio configmap.

IstioOperator:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiocontrolplane
  namespace: istio-system
spec:
  profile: minimal
  meshConfig:
    enableAutoMtls: true
    outboundTrafficPolicy:
      mode: ALLOW_ANY
  components:
    cni:
      enabled: true
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          replicaCount: 1
          hpaSpec:
            maxReplicas: 1
  values:
    gateways:
      istio-ingressgateway:
        loadBalancerIP: 10.0.0.200
        externalTrafficPolicy: Local # can't remember why this is needed
    sidecarInjectorWebhook:
      rewriteAppHTTPProbe: true
```

Istio config:
```
❯ kubectl -n istio-system get configmap istio -o jsonpath="{.data.mesh}"              
accessLogEncoding: TEXT
accessLogFile: ""
accessLogFormat: ""
certificates: []
defaultConfig:
  concurrency: 2
  configPath: /etc/istio/proxy
  connectTimeout: 10s
  controlPlaneAuthPolicy: NONE
  discoveryAddress: istiod.istio-system.svc:15012
  drainDuration: 45s
  parentShutdownDuration: 1m0s
  proxyAdminPort: 15000
  serviceCluster: istio-proxy
  tracing:
    zipkin:
      address: zipkin.istio-system:9411
disableMixerHttpReports: true
disablePolicyChecks: true
enableAutoMtls: false
enableEnvoyAccessLogService: false
enableTracing: true
ingressClass: istio
ingressControllerMode: STRICT
ingressService: istio-ingressgateway
localityLbSetting:
  enabled: true
outboundTrafficPolicy:
  mode: ALLOW_ANY
protocolDetectionTimeout: 100ms
reportBatchMaxEntries: 100
reportBatchMaxTime: 1s
sdsUdsPath: unix:/etc/istio/proxy/SDS
trustDomain: cluster.local
trustDomainAliases: null
```
