### ISSUE TITLE
unmarshal fails for enum type

### ISSUE THREAD

**Issue by richardwxn** [istio/istio#22184]
for latest master, unmarshal fails for enum value for unknown value error e.g. 
```
outboundTrafficPolicy:
      mode: ALLOW_ANY
```
This does not happen for 1.5 though, is it possibly related to the recent changes about the marshal/unmarshal stuff? @ostromart @morvencao

**Comment by morvencao** [comment]
@richardwxn I didn't see this with following IOP:
```
# cat values-global.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      outboundTrafficPolicy:
        mode: ALLOW_ANY
```
Would you share more details?
