### ISSUE TITLE
AddonComponents status should show more detailed info

### ISSUE THREAD

**Issue by morvencao** [istio/istio#22180]
Currently status of `addonComponents` just shows an overall status:
```
$ kubectl -n istio-system get iop -o yaml
...
  status:
    componentStatus:
      AddonComponents:
        status: HEALTHY
...
```

It should provide more detailed info for each add component status:
```
  status:
    componentStatus:
      AddonComponents:
        prometheus:
          status: HEALTHY
        kiali:
          status: HEALTHY
...
```

[ X ] Installation
