### ISSUE TITLE
https redirect not working on multiple gateway s

### ISSUE THREAD

**Issue by bitgandtter** [istio/istio#22210]
**Bug description**
I had one gateway with 
```
tls:
        httpsRedirect: true
```
enabled and redirect works as expected. Now I have several gateways configured and the redirect does not work on any of them, neither the first gateway I had that works previously

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
redirect incoming http request to https on all gateways

**Steps to reproduce the bug**

1. configure one gateway with https redirection enabled
2. test redirection
3. configure a second gateway with https redirection enabled as well
4. test redirection does not work on any gateway

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
`istioctl version --remote`
client version: 1.4.2
control plane version: 1.5.0
data plane version: 1.5.0 (90 proxies)
`kubectl version`
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-12T13:43:46Z", GoVersion:"go1.13.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
`helm version`
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

**How was Istio installed?**
istioctl new installation method

**Environment where bug was observed (cloud vendor, OS, etc)**
DigitalOcean

**Comment by bitgandtter** [comment]
sadly not @gustavovalverde and also sadly this its been ignored

**Comment by gustavovalverde** [comment]
It works for me now, in my case it was an indentation problem with the `tls `parameter.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-autogenerated-k8s-ingress # We use the istio special gateway name for K8s ingress
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      tls:
        httpsRedirect: true
      hosts:
        - "*"
```

**Comment by howardjohn** [comment]
might be the same as https://github.com/istio/istio/issues/22194

**Comment by nemo83** [comment]
Hi, I have the same issue and running with the following details:
1. Kube 1.16 on EKS (AWS)
2. Istio 1.4.9
3. Multiple ingress-gateways configured with TLS termination on ELB as follows:

Custom Ingress Gateway:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '60'
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'false'
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: [redacted]
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: istio-ingressgateway
    app.kubernetes.io/instance: istio
    chart: gateways
    heritage: Tiller
    istio: ingressgateway
    release: istio
  name: [redacted]
  namespace: istio-system
spec:
  clusterIP: 172.20.112.101
  externalTrafficPolicy: Cluster
  ports:
    - name: status-port
      nodePort: 31782
      port: 15020
      protocol: TCP
      targetPort: 15020
    - name: http
      nodePort: 31382
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      nodePort: 31392
      port: 443
      protocol: TCP
      targetPort: 80
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - hostname: >-
          [redacted]
```

And gateway:
```
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: argocd
  labels:
    app.kubernetes.io/name: applications.argoproj.io
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Tiller
  annotations:
    kubernetes.io/ingress.class: "ingressgateway"
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - myhost.mydomain.com
      tls:
        httpsRedirect: true
```
