### ISSUE TITLE
Envoy not reponding to localhost:<port> in side container, and giving 503UF

### ISSUE THREAD

**Issue by rjshrjndrn** [istio/istio#22241]
**Bug description**
We've one java application which runs on port 9000. We've deployed 6 replicas of that. But when we
tried to load test, one of the containers will always give `503`. Once we restart the pod, it'll work fine for some time, then again same issue.
No clue how to check the error. 
The information which I can gather attached below.

curl localhost:9000 in side pod is failing. Envoy is giving 503 UF and erroed out.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Traffic should work properly and should get 200

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
❯ istioctl version --remote
client version: 1.5.0
ingressgateway version: 1.5.0
ingressgateway version: 1.2.2
pilot version: 1.5.0
data plane version: 1.5.0 (58 proxies), 1.2.2 (1 proxies)

❯ helm version
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.14"}

❯ k version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"c83d931fb9bece427bc63a02349755e0f8696d3e", GitTreeState:"clean", BuildDate:"2020-01-31T20:09:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

```

**How was Istio installed?**
`istioctl manifest apply -f istioComponants.yaml`
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  addonComponents:
    grafana:
      enabled: true
    kiali:
      enabled: true
    tracing:
      enabled: true
  values:
    global:
      proxy:
        accessLogFile: "/dev/stdout"
    kiali:
      contextPath: /kiali
      createDemoSecret: true
      dashboard:
        grafanaInClusterURL: http://grafana:3000
        jaegerInClusterURL: http://tracing/jaeger
```
**Environment where bug was observed (cloud vendor, OS, etc)**
Azure AKS with CNI

I had circuit breaker enabled.
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: learner
spec:
  host: learner-service.istioloadtest.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
    outlierDetection:
      baseEjectionTime: 5m
      consecutiveErrors: 7
      interval: 3m
      maxEjectionPercent: 20
    connectionPool:
      http:
        h2UpgradePolicy: UPGRADE
      tcp:
        maxConnections: 100
        connectTimeout: 3s
        tcpKeepalive:
          time: 7200s
          interval: 75s
```
Disabled ciruit breaker and tried to change the envoy log to debug, but after that pod(learner-5898446bb9-fxtrd) is showing `1/2` 
```
❯ istioctl proxy-config endpoints learner-5898446bb9-fxtrd --cluster "outbound|9000||learner-service.istioloadtest.svc.cluster.local"
ENDPOINT             STATUS      OUTLIER CHECK     CLUSTER
28.0.12.212:9000     HEALTHY     OK                outbound|9000||learner-service.istioloadtest.svc.cluster.local
28.0.12.225:9000     HEALTHY     OK                outbound|9000||learner-service.istioloadtest.svc.cluster.local
28.0.13.102:9000     HEALTHY     OK                outbound|9000||learner-service.istioloadtest.svc.cluster.local
28.0.13.36:9000      HEALTHY     OK                outbound|9000||learner-service.istioloadtest.svc.cluster.local
28.0.13.50:9000      HEALTHY     OK                outbound|9000||learner-service.istioloadtest.svc.cluster.local

learner-5898446bb9-49lhj           2/2     Running   0          24h   28.0.13.50    aks-nodepool1-10765083-8    <none>           <none>
learner-5898446bb9-8bfv2           2/2     Running   0          25h   28.0.12.225   aks-nodepool1-10765083-6    <none>           <none>
learner-5898446bb9-bmqfz           2/2     Running   0          25h   28.0.13.102   aks-nodepool1-10765083-9    <none>           <none>
learner-5898446bb9-fxtrd           1/2     Running   0          25h   28.0.13.14    aks-nodepool1-10765083-11   <none>           <none>
learner-5898446bb9-g9vpj           2/2     Running   0          25h   28.0.12.212   aks-nodepool1-10765083-10   <none>           <none>
learner-5898446bb9-lfgkx           2/2     Running   0          25h   28.0.13.36    aks-nodepool1-10765083-8    <none>           <none>
```

```
❮ stern learner-5898446bb9-fxtrd --tail 1
+ learner-5898446bb9-fxtrd › learner
+ learner-5898446bb9-fxtrd › istio-proxy
learner-5898446bb9-fxtrd istio-proxy 2020-03-17T09:32:03.475495Z        info    Envoy proxy is NOT ready: server is not live, current state is: DRAINING
learner-5898446bb9-fxtrd learner 09:32:01.186 [MyScheduler_QuartzSchedulerThread] DEBUG o.quartz.core.QuartzSchedulerThread - batch acquisition of 0 triggers
learner-5898446bb9-fxtrd istio-proxy 2020-03-17T09:32:05.475345Z        info    Envoy proxy is NOT ready: server is not live, current state is: DRAINING
learner-5898446bb9-fxtrd learner 09:32:05.674 [QuartzScheduler_MyScheduler-learner-5898446bb9-fxtrd1584347562257_ClusterManager] DEBUG o.q.impl.jdbcjobstore.JobStoreTX - ClusterManager: Check-in complete.
^C
```
Update: restarting envoy in that pod, envoy is working fine. But the issue still persists.
```
❮ kg po -o wide | grep lear
learner-5898446bb9-49lhj           2/2     Running   0          24h   28.0.13.50    aks-nodepool1-10765083-8    <none>           <none>
learner-5898446bb9-8bfv2           2/2     Running   0          25h   28.0.12.225   aks-nodepool1-10765083-6    <none>           <none>
learner-5898446bb9-bmqfz           2/2     Running   0          25h   28.0.13.102   aks-nodepool1-10765083-9    <none>           <none>
learner-5898446bb9-fxtrd           2/2     Running   1          25h   28.0.13.14    aks-nodepool1-10765083-11   <none>           <none>
learner-5898446bb9-g9vpj           2/2     Running   0          25h   28.0.12.212   aks-nodepool1-10765083-10   <none>           <none>
learner-5898446bb9-lfgkx           2/2     Running   0          25h   28.0.13.36    aks-nodepool1-10765083-8    <none>           <none>
```
```
❮ istioctl proxy-config endpoints learner-5898446bb9-fxtrd --cluster "outbound|9000||learner-service.istioloadtest.svc.cluster.local"
ENDPOINT             STATUS      OUTLIER CHECK     CLUSTER
28.0.12.212:9000     HEALTHY     OK                outbound|9000||learner-service.istioloadtest.svc.cluster.local
28.0.12.225:9000     HEALTHY     OK                outbound|9000||learner-service.istioloadtest.svc.cluster.local
28.0.13.102:9000     HEALTHY     OK                outbound|9000||learner-service.istioloadtest.svc.cluster.local
28.0.13.14:9000      HEALTHY     OK                outbound|9000||learner-service.istioloadtest.svc.cluster.local
28.0.13.36:9000      HEALTHY     OK                outbound|9000||learner-service.istioloadtest.svc.cluster.local
28.0.13.50:9000      HEALTHY     OK                outbound|9000||learner-service.istioloadtest.svc.cluster.local
```
