### ISSUE TITLE
pilot: crash during convertIngress

### ISSUE THREAD

**Issue by jmuk** [istio/istio#2226]
Originally reported as https://github.com/istio/issues/issues/137:

For some incorrectly configured Ingress, pilot crashes through processing such config objects. It should not crash, but report errors.

Sample output:
```
ERROR: logging before flag.Parse: I1218 16:51:57.537610       1 discovery.go:339] Cleared discovery service cache
ERROR: logging before flag.Parse: I1218 16:53:10.537547       1 controller.go:93] ingress event add for default/simple-ingress
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1318fc1]

goroutine 117 [running]:
istio.io/istio/pilot/adapter/config/ingress.convertIngress(0x0, 0x0, 0x0, 0x0, 0xc4204d8700, 0xe, 0x0, 0x0, 0xc4204d8710, 0x7, ...)
	pilot/adapter/config/ingress/conversion.go:54 +0x461
istio.io/istio/pilot/adapter/config/ingress.(*controller).RegisterEventHandler.func1(0x1752d00, 0xc4203371e0, 0x0, 0x0, 0x0)
	pilot/adapter/config/ingress/controller.go:117 +0x119
istio.io/istio/pilot/platform/kube.(*ChainHandler).Apply(0xc420407fc0, 0x1752d00, 0xc4203371e0, 0x0, 0xc4202fe720, 0x1)
	pilot/platform/kube/queue.go:120 +0x81
istio.io/istio/pilot/platform/kube.(*ChainHandler).Apply-fm(0x1752d00, 0xc4203371e0, 0x0, 0xc4202f3c20, 0x0)
	pilot/adapter/config/crd/controller.go:119 +0x48
istio.io/istio/pilot/platform/kube.(*queueImpl).Run(0xc4202a2ff0, 0xc42015e180)
	pilot/platform/kube/queue.go:100 +0x18d
created by istio.io/istio/pilot/adapter/config/ingress.(*controller).Run
	pilot/adapter/config/ingress/controller.go:131 +0x54
rpc error: code = Unknown desc = Error: No such container: 41c30ad9efb0c13c889b35f09f18754a9b2d439de14b5e2b477750642873be56%
```

Reproducible config data:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: simple-ingress
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - host: gohan.target.com
  - http:
      paths:
      - path: /status/.*
        backend:
          serviceName: httpbin
          servicePort: 8000
```

Seems a rule assumes existence of `http` (see https://github.com/istio/istio/blob/master/pilot/adapter/config/ingress/conversion.go#L53), but that's optional actually.

cc: @meinenec
