### ISSUE TITLE
Document how to verify Istio mTLS encryption effect

### ISSUE THREAD

**Issue by incfly** [istio/istio#22276]
I have seen too many customers complaining that `how do I know istio mTLS is working`?

and the situation is a even more obvious with recent auto-X effect.

Additionally I found the telemetry data is not always reliable. tcp/http some times can be mis-reported about mtls status ( i ran into this once a while ago)

A tcpdump kinda instructions showing the before and after mTLS is helpful.

**Comment by incfly** [comment]
I made some progress on scripting setup. paste here for memo

```
k apply -f ./samples/httpbin/httpbin.yaml
k apply -f ./samples/sleep/sleep.yaml
k apply -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep-legacy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep-legacy
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: sleep-legacy
    spec:
      serviceAccountName: sleep
      containers:
      - name: sleep
        image: governmentpaas/curl-ssl
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: IfNotPresent
EOF
k exec $(kpid -lapp=httpbin) -c istio-proxy -it -- sudo tcpdump dst port 80  -A
```

second terminal run request.

```
k exec sleep-74564b477b-4jnh2 -c sleep -- curl httpbin:8000/ip
k exec sleep-legacy-759d8bf457-zr6t4  -c sleep -- curl httpbin:8000/ip
```

from the tcpdump, see different output, the first is encrypted text, second one you can see plaintext http.
