### ISSUE TITLE
Regex rewrites using capture groups

### ISSUE THREAD

**Issue by kmai** [istio/istio#22290]
**Describe the feature request**
Given that Envoy seems to already support [regex rewrites](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route_components.proto#envoy-api-field-route-routeaction-regex-rewrite), it would be excellent if this could be used on VirtualServices to rewrite prefixes, URIs, etc.

**Describe alternatives you've considered**
Current workaround is to have a gateway with nginx doing the rewrites, but it defeats the purpose of having an ingress gateway/gateway resource.

**Additional context**
This was previously requested here: https://github.com/istio/istio/issues/15857 but closed because Envoy didn't support rewrites like this at that moment.

This was implemented here: https://github.com/envoyproxy/envoy/pull/10050

**Comment by kmai** [comment]
anyone?

**Comment by williancampos** [comment]
I upvote it.

I noticed the code sets a PrefixRewrite here https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/route/route.go#L422

But now there's also a RegexWrite available (https://github.com/envoyproxy/go-control-plane/blob/master/envoy/api/v2/route/route_components.pb.go#L1136).

May be the HTTPRewrite could have something similar to 'StringMethod method' (as in HTTPMatchRequest), in which we could specify regex or prefix.

**Comment by howardjohn** [comment]
This seems like a reasonable addition to the API, and should be fairly easy to implement. StringMethod may cause issue since there is no `exact` and it would require deprecating the existing field. We could also just add a `uriRegex` or something else.

**Comment by abhide** [comment]
@howardjohn would like to take a look into fixing this issue. 
Assigning this issue to myself.

**Comment by edyaya** [comment]
Greetings, colleagues, @abhide  , I am very interested in the progress on this task.
Have the features been included in the product development plans?

**Comment by praveenbingo** [comment]
@abhide I am interested in this feature, please let me know if i can help in anyway to speed this up..

**Comment by abhide** [comment]
@praveenbingo I have a PR in review to add the attributes to virtualService CRD: https://github.com/istio/api/pull/1566

**Comment by perezjasonr** [comment]
another issue was opened referencing this problem:
https://github.com/istio/istio/issues/25246

it would be amazing if we could get this.

**Comment by dotbalo** [comment]
How is this problem handled? I want to achieve access to /api/abc to /abc, it seems impossible?Can RegexRewrites work?

**Comment by howardjohn** [comment]
You can do that with prefix rewrite

**Comment by papovyr** [comment]
Is there istio Milestone version when this will be released ?

**Comment by abhide** [comment]
I am not actively working on this GH issue. Will un-assign myself so that someone can pick it up.

**Comment by SpecialYang** [comment]
Need this feature. Can I try to complete it?

**Comment by esnible** [comment]
@istio/wg-policies-and-telemetry-maintainers This is a common request, as is rewriting the HTTP path based on a regex.  I don't think Envoy includes support for such rewrites.  This might make a good example of using Wasm.  I created a filter to do this and it is very simple.  The non-boilerplate is just:

``` C++
FilterHeadersStatus RegexpRepl::onRequestHeaders(uint32_t header_count, bool end_of_stream) {
  // TODO modify the request headers using the EnvoyFilter configuration instead of hard-coding
  char const *key = ":path";
  char const *pattern = "banana/([0-9]*)";
  char const *replaceWith = "status/$1";

  WasmDataPtr wdpGhmv = getRequestHeader(key);
  std::string sValue = wdpGhmv->toString();

  std::regex re(pattern);
  std::string result = std::regex_replace(sValue, re, replaceWith);
  WasmResult wrRrh = replaceRequestHeader(key, result);
  if (wrRrh == WasmResult::Ok) {
    logWarn("context_id:" + strId_ + " RegexpRepl::onRequestHeaders() replaced " + sValue + " with " + result);
  } else {
    logWarn("context_id:" + strId_ + " RegexpRepl::onRequestHeaders() replaceRequestHeader() FAILED.  wrRrh is " + toString(wrRrh));
  }

  return FilterHeadersStatus::Continue;
}
```

I tested it with httpbin.  Requests for `httpbin:8000/banana/418` were processed as `httpbin:8000/banana/418`.

What do you think about me making a sample or blog about this for Istio?

If people find the performance of doing this with WASM reasonable, we could talk about smoother experience for users who want path rewrites without learning the EnvoyFilter API.

**Comment by howardjohn** [comment]
I do think having single wasm examples is useful but afaik this is supported in envoy already (https://github.com/istio/api/pull/1854)

**Comment by SpecialYang** [comment]
> @istio/wg-policies-and-telemetry-maintainers This is a common request, as is rewriting the HTTP path based on a regex. I don't think Envoy includes support for such rewrites. This might make a good example of using Wasm. I created a filter to do this and it is very simple. The non-boilerplate is just:
> 
> ```c++
> FilterHeadersStatus RegexpRepl::onRequestHeaders(uint32_t header_count, bool end_of_stream) {
>   // TODO modify the request headers using the EnvoyFilter configuration instead of hard-coding
>   char const *key = ":path";
>   char const *pattern = "banana/([0-9]*)";
>   char const *replaceWith = "status/$1";
> 
>   WasmDataPtr wdpGhmv = getRequestHeader(key);
>   std::string sValue = wdpGhmv->toString();
> 
>   std::regex re(pattern);
>   std::string result = std::regex_replace(sValue, re, replaceWith);
>   WasmResult wrRrh = replaceRequestHeader(key, result);
>   if (wrRrh == WasmResult::Ok) {
>     logWarn("context_id:" + strId_ + " RegexpRepl::onRequestHeaders() replaced " + sValue + " with " + result);
>   } else {
>     logWarn("context_id:" + strId_ + " RegexpRepl::onRequestHeaders() replaceRequestHeader() FAILED.  wrRrh is " + toString(wrRrh));
>   }
> 
>   return FilterHeadersStatus::Continue;
> }
> ```
> 
> I tested it with httpbin. Requests for `httpbin:8000/banana/418` were processed as `httpbin:8000/banana/418`.
> 
> What do you think about me making a sample or blog about this for Istio?
> 
> If people find the performance of doing this with WASM reasonable, we could talk about smoother experience for users who want path rewrites without learning the EnvoyFilter API.

In gateway, we really care about the performance of WASM, which need more benchmark test report.

**Comment by esnible** [comment]
> I do think having single wasm examples is useful but afaik this is supported in envoy already ([istio/api#1854](https://github.com/istio/api/pull/1854))

This is great!  I was unaware of https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route_components.proto#route-routeaction .  It looks like it could do what is desired!

I would be even happier with a non-WASM EnvoyFilter sample to do this.  So I tried to write one.  I created a regex EnvoyFilter based on the `VIRTUAL_HOST` sample _samples/bookinfo/policy/productpage_envoy_ratelimit.yaml_.

``` yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: no-banana
spec:
  configPatches:
    - applyTo: VIRTUAL_HOST
      match:
        routeConfiguration:
          portNumber: 8000
          vhost:
            name: "httpbin.default.svc.cluster.local:8000"
      patch:
        operation: MERGE
        value:
          # See https://www.envoyproxy.io/docs/envoy/latest/api-v2/type/matcher/regex.proto#envoy-api-msg-type-matcher-regexmatchandsubstitute
          regex_rewrite:
            pattern:
              google_re2: "banana/([0-9]*)"
              regex: "banana/([0-9]*)"
            substitution: "status/$1"
  workloadSelector:
    labels:
      app: httpbin
```

Unfortunately, the above example doesn't work!  No effect on the Envoy /config_dump.  The variations I tried made the sidecar go stale.  Anything obviously wrong with the above?

**Comment by howardjohn** [comment]
If it goes stale it likely is NACKed. Check logs of istiod or proxy for the
error?

**Comment by esnible** [comment]
> If it goes stale it likely is NACKed. Check logs of istiod or proxy for the error?

I did.  No logs from istiod, Envoy said `type.googleapis.com/envoy.config.route.v3.RouteConfiguration rejected: Proto constraint validation failed (RouteConfigurationValidationError.VirtualHosts[i]: ["embedded message failed validation"] | caused by VirtualHostValidationError.Domains: ["value must contain at least " '\x01' " item(s)"]): name: "8000"`

That message didn't come from the EnvoyFilter I posted.  I tried variations with `ADD` instead of `MERGE`, and `typed_config` with `type_url: type.googleapis.com/envoy.type.matcher.RegexMatchAndSubstitute`.  I will keep experimenting.  (I am confused why the WASM examples use `typed_config`, but the rate limit example doesn't use a typed config for config.route.v3.RateLimit).

**Comment by howardjohn** [comment]
Anything without typed_config is probably wrong and only works on older v2
XDS proxies

**Comment by esnible** [comment]
OK, I have created a working EnvoyFilter, that doesn't use WASM, that does regex rewrites:

``` yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: no-banana
spec:
  configPatches:
    - applyTo: HTTP_ROUTE
      match:
        routeConfiguration:
          vhost:
            name: "inbound|http|8000"
      patch:
        operation: MERGE
        value:
          route:
            # See https://www.envoyproxy.io/docs/envoy/latest/api-v2/type/matcher/regex.proto#envoy-api-msg-type-matcher-regexmatchandsubstitute
            regex_rewrite:
              pattern:
                 google_re2:
                   max_program_size: 100
                 regex: "^/banana/([0-9]*)$"
              # Use two backslashes in a file, four in the shell
              substitution: "/status/\\1"
  workloadSelector:
    labels:
      app: httpbin
```

To test:

``` bash
kubectl apply -f samples/httpbin/httpbin.yaml
// then create a file with the above YAML in it, and apply, then
kubectl exec -ti deploy/httpbin -c istio-proxy -- curl -v http://httpbin.default:8000/banana/418
```

Thanks to @howardjohn for patiently explaining why I needed to use `applyTo: HTTP_ROUTE`.  I also got stuck at first applying this to the outbound, not to `"inbound|http|8000"`.  I also got stuck with the fact that `google_re2` is required, but it contains only an optional member, but that member is also required!

Agreed this solution is clunky but it works in a pinch, and lets us experiment with adding this as a regular feature.

**Comment by chinaran** [comment]
@esnible great EnvoyFilter，but could this type EnvoyFilter Support rewriting multiple paths?

**Comment by esnible** [comment]
> @esnible great EnvoyFilter，but could this type EnvoyFilter Support rewriting multiple paths?

Wasm filters are extremely powerful and can do anything to the PATH.  You could easily implement a filter either with your own, compiled-in list of match conditions, or you could pass in some kind of JSON list to configure your filter.

I also suspect you could take the existing example and install N Envoy filters, one for each condition.  That isn't the most efficient thing but I suspect it would work.  I haven't tried it.

**Comment by chinaran** [comment]
@esnible Thank you. A filter must be support rewriting multiple paths.
But install N Envoy filters, one for each condition, can't work. It will use the last Envoy filters.

**Comment by fatedier** [comment]
@howardjohn Does istio plan to support regex rewrites as a regular feature?

**Comment by kmai** [comment]
Any hints on when is this going to be picked up @howardjohn ?

**Comment by Jiaweizdev** [comment]
Upvote!

**Comment by dm3ch** [comment]
I just found that Gloo have regexRewrite feature and based on their example (https://docs.solo.io/gloo-edge/latest/guides/traffic_management/request_processing/regex_rewrite/) it seems that it allows to use capture groups in rewrites. I'm not 100% sure, but I assume that they are using envoy regexRewrite feature.

Anyway it would be cool to have regexpRewrite support in Istio even without capture groups, cause it could help with stripping regex prefixes from request path

**Comment by ahharu** [comment]
@abhide what's the status on this ?

**Comment by dacloutier** [comment]
I would really like to have solution for regex capture groups in the vs configuration.

This is very important for a lot of us, how can we help get some solution to this problem into the product?

**Comment by kmai** [comment]
Based on what I've read about the Gateway API and given 1.12 was released recently, I wouldn't expect to see this until at least 1.13

@howardjohn does that make any sense?

**Comment by dacloutier** [comment]
I don't mind if it's later, I would just like confirmation that it's planned. and not doomed to go stale.

**Comment by rufreakde** [comment]
> @howardjohn any idea why we can't merge this PR? This is causing such headaches for us.

It seems some tests are failing:
https://github.com/istio/api/pull/1854

**Comment by SpecialYang** [comment]
The path rewrite and redirect features has already be merged in gateway-api https://github.com/kubernetes-sigs/gateway-api/pull/731. 
But the path regex rewrite api doesn't be included in. Istio will not add path regex rewrite feature until gateway api add this. Someone who need this api in istio should discuss gateway api like this pr https://github.com/kubernetes-sigs/gateway-api/pull/731 which will be more useful.

**Comment by dacloutier** [comment]
@SpecialYang Thanks for responding.

The PR you linked (kubernetes-sigs/gateway-api#731) has a lot of discussion around regex rewrite and capture groups. The PR was approved and merged... But it only talks about regex as a "future extension".

I've added a comment in the issue: https://github.com/kubernetes-sigs/gateway-api/issues/726 but maybe someone at istio can comment in as well to help move this solution forward? @howardjohn ?

**Comment by withnale** [comment]
Now that kubernetes-sigs/gateway-api/issues/726 is merged, is there any chance of some progression of this ticket?

**Comment by withnale** [comment]
wow. not a lot of movement on this ticket. Can someone comment as to whether this is still an active issue?

**Comment by bittelc** [comment]
It is still an active issue.

**Comment by jallaix** [comment]
Has anybody managed to use an EnvoyFilter with [RouteAction](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-routeaction) as a workaround ?
I can't find any example on the web to do that.

**Comment by ajpauwels** [comment]
@jallaix I've been trying to do just that for 3 days but for a redirect. This comment has a good overview of writing an EnvoyFilter with a route action:
https://github.com/istio/istio/issues/22290#issuecomment-774260856

However, it seems to apply when the request has been routed and is inbound to the final destination sidecar already. I need to rewrite the URI by adding a prefix to the existing path and then redirect, but I can't figure out how to do that.

**Comment by ajpauwels** [comment]
I've created my own filter for path rewriting using Lua here. Lua makes it very flexible to do just about anything you want, except change the :authority pseudo-header. Still can't find out how to do host rewrite, but this may help someone doing path re-writes BEFORE the gateway performs routing:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: regex-path-rewrite
  namespace: istio-ingress
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: 'envoy.filters.http.router'
        portNumber: 443
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.lua
        typed_config:
          '@type': 'type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua'
          inlineCode: |
            function envoy_on_request(request_handle)
              local path = request_handle:headers():get(":path")
              local tenant_name, workload_name, workload_path = string.match(path, "/t/([a-z0-9-]+)/([a-z0-9-]+)(.*)")
              local new_path = workload_name .. "/" .. workload_path
              if (tenant_name ~= nil and workload_name ~= nil) then              
                request_handle:headers():replace(":path", new_path)
              end
            end
```

**Comment by mlitvinav** [comment]
In addition to @ajpauwels solution for global rewrites ([link](https://github.com/istio/istio/issues/22290#issuecomment-1317595537)) it is also possible to rewrite routes for one route after the gateway.
The following example will regex match routes with `-\d{4}$` and prefix a locale if needed. Notice that VirtualService matches and Envoy rewrites. I believe Lua uses [RE2 flavor of Regex](https://github.com/google/re2). Just use a online Lua compiler to test if your regex matches correctly.
Credits: https://stackoverflow.com/a/69637003
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: echo
  namespace: testing
spec:
  hosts: ["*"]
  gateways:
    - istio-ingress/default-gateway
  http:
    - name: rewrite-testing # only for this
      match:
        - uri:
            regex: "^.+-[0-9]{4}$" # check before rewrite
      route:
        - destination:
            host: echo.testing.svc.cluster.local
            port:
              number: 8080
    - name: keep-as-is
      match:
        - uri:
            prefix: /stuff
      route:
        - destination:
            host: echo.testing.svc.cluster.local
            port:
              number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: regex-path-rewrite-one-route
  namespace: istio-ingress # namespace of gateway you are targetting
spec:
  configPatches:
  # Patch that creates "global" lua filter that does nothing useful
  - applyTo: HTTP_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.lua
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
          inlineCode: |
            function envoy_on_request(request_handle)
              -- Empty lua function
            end
  # Filter for http route that overrides previous "global" filter lua source code for one route
  - applyTo: HTTP_ROUTE
    match:
      context: GATEWAY
      routeConfiguration:
        vhost:
          route:
            # Corresponds to http[0].name in VirtualService
            name: rewrite-testing
    patch:
      operation: MERGE
      value:
        name: envoy.lua
        typed_per_filter_config:
          envoy.filters.http.lua:
            '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute
            source_code:
              inline_string: |
                function envoy_on_request(request_handle)
                  local old_path = request_handle:headers():get(":path")
                  local is_product_section = string.match(old_path,"-%d%d%d%d$")

                  if is_product_section ~= nil
                  then
                    if string.sub(old_path,1,7) ~= "/de_DE/"
                    and string.sub(old_path,1,7) ~= "/en_US/"
                    then
                        local new_path = "/en_US" .. old_path
                        request_handle:headers():replace(":path", new_path)
                    end
                  end
                end
```

**Comment by amne** [comment]
> In addition to @ajpauwels solution for global rewrites ([link](https://github.com/istio/istio/issues/22290#issuecomment-1317595537)) it is also possible to rewrite routes for one route after the gateway. The following example will regex match routes with `-\d{4}$` and prefix a locale if needed. Notice that VirtualService matches and Envoy rewrites. I believe Lua uses [RE2 flavor of Regex](https://github.com/google/re2). Just use a online Lua compiler to test if your regex matches correctly. Credits: https://stackoverflow.com/a/69637003
> 
> ```yaml
> apiVersion: networking.istio.io/v1alpha3
> kind: VirtualService
> metadata:
>   name: echo
>   namespace: testing
> spec:
>   hosts: ["*"]
>   gateways:
>     - istio-ingress/default-gateway
>   http:
>     - name: rewrite-testing # only for this
>       match:
>         - uri:
>             regex: "^.+-[0-9]{4}$" # check before rewrite
>       route:
>         - destination:
>             host: echo.testing.svc.cluster.local
>             port:
>               number: 8080
>     - name: keep-as-is
>       match:
>         - uri:
>             prefix: /stuff
>       route:
>         - destination:
>             host: echo.testing.svc.cluster.local
>             port:
>               number: 8080
> ---
> apiVersion: networking.istio.io/v1alpha3
> kind: EnvoyFilter
> metadata:
>   name: regex-path-rewrite-one-route
>   namespace: istio-ingress # namespace of gateway you are targetting
> spec:
>   configPatches:
>   # Patch that creates "global" lua filter that does nothing useful
>   - applyTo: HTTP_FILTER
>     match:
>       listener:
>         filterChain:
>           filter:
>             name: envoy.filters.network.http_connection_manager
>             subFilter:
>               name: envoy.filters.http.router
>     patch:
>       operation: INSERT_BEFORE
>       value:
>         name: envoy.lua
>         typed_config:
>           '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
>           inlineCode: |
>             function envoy_on_request(request_handle)
>               -- Empty lua function
>             end
>   # Filter for http route that overrides previous "global" filter lua source code for one route
>   - applyTo: HTTP_ROUTE
>     match:
>       context: GATEWAY
>       routeConfiguration:
>         vhost:
>           route:
>             # Corresponds to http[0].name in VirtualService
>             name: rewrite-testing
>     patch:
>       operation: MERGE
>       value:
>         name: envoy.lua
>         typed_per_filter_config:
>           envoy.filters.http.lua:
>             '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute
>             source_code:
>               inline_string: |
>                 function envoy_on_request(request_handle)
>                   local old_path = request_handle:headers():get(":path")
>                   local is_product_section = string.match(old_path,"-%d%d%d%d$")
> 
>                   if is_product_section ~= nil
>                   then
>                     if string.sub(old_path,1,7) ~= "/de_DE/"
>                     and string.sub(old_path,1,7) ~= "/en_US/"
>                     then
>                         local new_path = "/en_US" .. old_path
>                         request_handle:headers():replace(":path", new_path)
>                     end
>                   end
>                 end
> ```

I tried this and it looks like after rewriting the path the gateway can't route the request because the new path doesn't match any pattern in the VirtualService specs

**Comment by mlitvinav** [comment]
Hi @amne
Sry for the late response! Here is what you need to create the rewrite you are looking for:
```sh
kubectl create ns testing
kubectl label ns testing istio-injection=enabled
# My Deno echo server for debugging; Use something else if paranoid
kubectl create deploy echo --image litvinav/echo -n testing
kubectl create svc clusterip echo --tcp 8080:8080 -n testing
```
```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: echo
  namespace: testing
spec:
  selector:
    matchLabels:
      app: echo
  action: ALLOW
  rules:
    - from:
        - source:
            principals: ['cluster.local/ns/istio-ingress/sa/istio-ingress'] # make sure SA is right
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: echo
  namespace: testing
spec:
  gateways:
  # your_gateway_namespace/name_of_your_gateway
  - istio-ingress/default-gateway
  hosts:
  # your hostname
  - example.com
  http:
  - match:
    - uri:
        # assuming your user id is uuid-v4
        regex: /v1/users/[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}/stats
    # Not sure why but i had to match this path twice for it to work
    - uri:
        regex: /v1/stats/[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}
    name: rewrite-testing
    route:
    - destination:
        host: echo.testing.svc.cluster.local
        port:
          number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: echo-filter
  namespace: istio-ingress
spec:
  # in case you have multiple Gateways
  workloadSelector:
    labels:
      app: istio-ingress
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.lua
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
          inlineCode: |
            function envoy_on_request(request_handle)
              -- Empty lua function
            end
  - applyTo: HTTP_ROUTE
    match:
      context: GATEWAY
      routeConfiguration:
        vhost:
          route:
            name: rewrite-testing
    patch:
      operation: MERGE
      value:
        name: envoy.lua
        typed_per_filter_config:
          envoy.filters.http.lua:
            '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute
            source_code:
              inline_string: |
                function envoy_on_request(request_handle)
                  old_path = request_handle:headers():get(":path")
                  new_path = "/v1/stats/" .. string.sub(old_path, 11, 46)
                  request_handle:headers():replace(":path", new_path)
                end
```

Now if you call https://hostname/v1/users/C73BCDCC-2669-4Bf6-81d3-E4AE73FB11FD/stats you should see the following output in the echo server:
```json
{
  "body": null,
  "headers": {
      //...SNIP...
   },
  "url": "http://hostname/v1/stats/C73BCDCC-2669-4Bf6-81d3-E4AE73FB11FD"
}
```
Not sure why but i had to match the path twice for it to work in the VirtualService.
I thought so far that only the pre rewrite match is needed here. Maybe someone familiar with the source code and/or from the Istio team knows why? Removing one of the uri regex's from the match will not reroute this code on Istio 1.17.1 installed via a helm chart.

And a happy belated easter 😉

**Comment by amne** [comment]
Hello @mlitvinav ,

Thanks for getting back with a solution. I now realize my my initial comment was all over the place as I already had it working exactly like you suggested.
Here are more details on why the routing happens again after changing the path header: https://github.com/envoyproxy/envoy/issues/8719

In the end I used the idea of "tagging" the request with an `x-route-name` header so I can easily match it after rewriting the URL.

```
...
  http:
  - name: public_stats_route
    match:
    - uri:
        regex: /stats/([0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12})
      method:
        regex: (GET)
    - headers:
        x-route-name:
          exact: public_stats_route
...
```

```
...
    - applyTo: HTTP_ROUTE
      match:
        context: GATEWAY
        routeConfiguration:
          vhost:
            route:
              name: "public_stats_route"
      patch:
        operation: MERGE
        value:
          typed_per_filter_config:
            envoy.filters.http.lua:
              "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute"
              source_code:
                inline_string: |
                    function envoy_on_request(request_handle)
                      local uuid_pattern="%x%x%x%x%x%x%x%x%-%x%x%x%x%-%x%x%x%x%-%x%x%x%x%-%x%x%x%x%x%x%x%x%x%x%x%x"
                      local path = request_handle:headers():get(":path")
                      local account_id = string.match(path, "/stats/(" .. uuid_pattern .. ")")
                      request_handle:logDebug("account_id = " .. account_id)
                      if account_id ~= nil then
                        local new_path = "/api/v1/users/" .. account_id .. "/stats"
                        request_handle:headers():replace(":path", new_path)
                        request_handle:headers():add("x-route-name", "public_stats_route")
                      end
                    end
...
```


Once istio brings regex rewriting config support I can ditch the lua filters and have simple yaml files again.
