### ISSUE TITLE
Istio-proxy custom format access_log doesn't generate until second request. 

### ISSUE THREAD

**Issue by rohit-tiwari-scmp** [istio/istio#22317]
**Bug description**
We are running Istio (version:  1.5.0 ) under ACK cluster, applications running are using envoy filter for the custom access log. We are using ambassador service for forwarding the inbound request to the backend. There is a strange thing noticed, that custom access log generated for any incoming request does not appear immediately but appears merged with next request, however it captures the timestamp of first request. I know it sounds odd.

Here's the log:

First request log: Notice the path (/istio-auth/first-request) and timestamp (2020-03-19T14:44:44.899Z) this is default access log not the custom one.

```{"startTIME": "2020-03-19T14:15:10.161Z", "method": "GET", "Authorization": "-" ,"path": "/istio-auth/"}\\n{"bytes_sent":"103","upstream_cluster":"inbound|5050|http-app|uat-app-hello-istio-auth.technology-newsroom-system.svc.cluster.local","downstream_remote_address":"xxx.xxx.xxx.xxx:xxxx","authority":"uat-api.scmp.work","path":"/istio-auth/first-request","protocol":"HTTP/1.1","upstream_service_time":"2","upstream_local_address":"-","duration":"4","downstream_local_address":"xxx.xxx.xxx.xxx:xxxx","upstream_transport_failure_reason":"-","route_name":"default","response_code":"200","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36","response_flags":"-","start_time":"2020-03-19T14:44:44.899Z","method":"GET","request_id":"0893ed8c-0d98-9474-879d-9a155973bfc7","upstream_host":"xxx.xxx.xxx.xxx:xxxx","x_forwarded_for":"xxx.xxx.xxx.xxx","requested_server_name":"-","bytes_received":"0","istio_policy_status":"-"}```

On Second request:  Custom access log for the first request gets logged along with default log for second request.  Path: (/istio-auth/second-request), Notice the timestamp for custom access log for first request 2020-03-19T14:44:44.899Z, but it appeared only when second request was triggered.

```{"startTIME": "2020-03-19T14:44:44.899Z", "method": "GET", "Authorization": "-" ,"path": "/istio-auth/first-request"}\\n{"bytes_sent":"104","upstream_cluster":"inbound|5050|http-app|uat-app-hello-istio-auth.technology-newsroom-system.svc.cluster.local","downstream_remote_address":"xxx.xxx.xxx.xxx:xxxx","authority":"uat-api.scmp.work","path":"/istio-auth/second-request","protocol":"HTTP/1.1","upstream_service_time":"3","upstream_local_address":"-","duration":"4","downstream_local_address":"xxx.xxx.xxx.xxx:xxxx","upstream_transport_failure_reason":"-","route_name":"default","response_code":"200","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36","response_flags":"-","start_time":"2020-03-19T14:46:51.377Z","method":"GET","request_id":"ea190826-c287-986d-86ae-5bf36cfde331","upstream_host":"xxx.xxx.xxx.xxx:xxxx","x_forwarded_for":"xxx.xxx.xxx.xxx:xxxx","requested_server_name":"-","bytes_received":"0","istio_policy_status":"-"}```

I also tried to add a newline character to seperate the custom logs from default, but does not seems to work.

Kindly help us troubleshoot this issue of delay logging.

[ X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Custom format access log must be logged in realtime, along with default access log.

**Steps to reproduce the bug**
Unknown

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Istio version:

`client version: 1.4.0
control plane version: 1.4.2
data plane version: 1.4.2 (13 proxies), 1.5.0 (3 proxies)
`

kubernetes version:
`Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.9", GitCommit:"3e4f6a92de5f259ef313ad876bb008897f6a98f0", GitTreeState:"clean", BuildDate:"2019-08-05T09:22:00Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-aliyun.1", GitCommit:"51888f5", GitTreeState:"", BuildDate:"2019-10-16T08:29:13Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
`

HELM version:
`Client: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
`
**How was Istio installed?**

Using HELM client

**Environment where bug was observed (cloud vendor, OS, etc)**
Cloud Provider: Alicloud
Service: ACK (Alicloud cluster for Kubernetes)

Envoyfilter yaml:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  labels:
    env: uat
    project: hello-istio-auth
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: ANY
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
    patch:
      operation: MERGE
      value:
        typed_config:
          '@type': type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          access_log:
          - config:
              format: '{"startTIME": "%START_TIME%", "method": "%REQ(:METHOD)%", "Authorization":
                "%REQ(AUTHORIZATION)%" ,"path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"}\\n'
              path: /dev/stdout
            name: envoy.file_access_log
```
