### ISSUE TITLE
How should I install tracing and persist the data to Elasticsearch  with IstioOperator

### ISSUE THREAD

**Issue by fujianan** [istio/istio#22310]
Now I install the tracing image as all-in-one, and the data is stored in the pod. How can I ensure the data is persistent?

install-tracing.yaml: 
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  addonComponents:
    tracing:
      enabled: true
``` 
istioctl manifest apply -f  install-tracing.yaml

**Comment by edenzhong7** [comment]
maybe you can try this:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  addonComponents:
    tracing:
      enabled: true
      spec: 
        persist: true
        storageClassName: "xxx"
``` 
more  config details about `tracing` is in `manifests/istio-telemetry/tracing/values.yaml`.
I haven't apply install-tracing.yaml actually,  only read the definition of `ExternalComponentSpec` in `istio.io/api/operator/v1alpha1/component.pb.go`
