### ISSUE TITLE
Healthchecks are failed because of AuthorizationPolicy

### ISSUE THREAD

**Issue by selcukusta** [istio/istio#22316]
**Bug description**

I'm using AuthorizationPolicy to allow any user who has IP it's in my whitelist to reach the app path. Manifest is;

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ump-lan-auth-policy
  namespace: default
spec:
  selector:
    matchLabels:
      app: user-management-panel-ui
  action: ALLOW
  rules:
    - to:
        - operation:
            methods: ["GET"]
            paths: ["/users*"]
      when:
        - key: "request.headers[X-Forwarded-For]"
          values: ["XXX.XX.XX.XXX"]
```

Deployment manifest is;

```yaml
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: user-management-panel-ui
...
          livenessProbe:
            httpGet:
              path: "/self"
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: "/ready"
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
...
```

When I applied the manifest, liveness (path is `/self`) and readiness (path is `/ready`) probes are affected. They're getting 403 errors. But for these paths, there's no constraint. So the container will down and I'll see `no healthy upstream`.

**Expected behavior**

Health check paths would not be affected by the policy.

**Steps to reproduce the bug**

Create any web application which has a `/users` path and apply the manifest.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

`istioctl version --remote`

```
client version: 1.5.0
control plane version: 1.5.0
data plane version: 1.5.0 (62 proxies)
```
`kubectl version``

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T23:41:24Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"c52f59bbba5fbf21fbb18e9a06f96e563fe4c20a", GitTreeState:"clean", BuildDate:"2020-01-31T20:00:26Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**

Via istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**

Azure Kubernetes Services, Linux OS

**Comment by incfly** [comment]
@yangminzhu  For authz we don't have to do anything special.

I think if you configure health checking path with another block of `rule` without specfiying any condition, that will make anyone (including kubelet) to probe the health check path.

Wouldn't that work for you?

**Comment by yangminzhu** [comment]
yes, I think you can just whitelist the paths used for probe, like the following:
```yaml
  rules:
    - to:
        - operation:
            methods: ["GET"]
            paths: ["/users*"]
      when:
        - key: "request.headers[X-Forwarded-For]"
          values: ["XXX.XX.XX.XXX"]
    - to:
        - operation:
            paths: ["/self", "/ready"]
```
