### ISSUE TITLE
IstioOperator spec.meshConfig is not applied

### ISSUE THREAD

**Issue by rocketspacer** [istio/istio#22347]
**Bug description**
**IstioOperator** `spec.meshConfig` is not applied.

**Expected behavior**

When I apply the **IstioOperator** CRD like this
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio
spec:
  namespace: istio-system
  profile: default
  meshConfig:
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
```
The generated config map should have synchronized meshConfig

**Steps to reproduce the bug**

1. Run `istioctl manfiest generate -f operator.yaml` with the above manifest
2. See that the output config map still has `outboundTrafficPolicy.mode` set to **ALWAYS_ALLOW**
![image](https://user-images.githubusercontent.com/17026876/77149191-018b4b00-6acc-11ea-838c-f4fd2d4bfabd.png)

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
![image](https://user-images.githubusercontent.com/17026876/77234196-743d1900-6be7-11ea-99d4-3cac6fb97954.png)
![image](https://user-images.githubusercontent.com/17026876/77234210-87e87f80-6be7-11ea-83d7-9f08e4fd193b.png)

**How was Istio installed?**
Using the istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
Cloud vendor: AWS (EKS)
OS: AWS Container Optimized EC2 Linux
