### ISSUE TITLE
IstioOperator API: Labels for the gateway don't work

### ISSUE THREAD

**Issue by iusergii** [istio/istio#22389]
**Bug description**
The IstioOperator API (install.istio.io/v1alpha1) GatewaySpec **label** configuration doesn't work. 

[ X] Configuration Infrastructure
[ ] Docs
[ X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Deployment for istio-ingressgateway should have configured labels.

**Steps to reproduce the bug**
```yaml apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      label:
        ProductComponents: Istio
```
```bash
istioctl manifest apply -f istio-ingressgateway.yaml
```
Deployment/pod - doesn't have label `ProductComponents: Istio`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```bash 
client version: 1.5.0
control plane version: 1.5.0
data plane version: 1.5.0 (4 proxies)
```
