### ISSUE TITLE
IstioOperator API: k8s.service.ports doesn't work

### ISSUE THREAD

**Issue by iusergii** [istio/istio#22390]
**Bug description**
The IstioOperator API (install.istio.io/v1alpha1)  k8s.service.**ports** configuration doesn't work.

**Steps to reproduce the bug**
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:ayuio[
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        service:
          externalTrafficPolicy: Local
          ports:
          - name: https
            port: 443
```
```bash
istioctl manifest apply -f istio-ingressgateway.yaml
```
Istio-ingressgateway service still has default ports:
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations: null
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
  externalTrafficPolicy: Local
  ports:
  - name: status-port
    port: 15020
    targetPort: 15020
  - name: http2
    port: 80
    targetPort: 80
  - name: https
    port: 443
  - name: kiali
    port: 15029
    targetPort: 15029
  - name: prometheus
    port: 15030
    targetPort: 15030
  - name: grafana
    port: 15031
    targetPort: 15031
  - name: tracing
    port: 15032
    targetPort: 15032
  - name: tls
    port: 15443
    targetPort: 15443
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  type: LoadBalancer
```
Expected: Service has only one port 443

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```bash
istioctl version --remote
client version: 1.5.0
control plane version: 1.5.0
data plane version: 1.5.0 (4 proxies)
```
