### ISSUE TITLE
Istioctl `separate` profile installs istiod

### ISSUE THREAD

**Issue by matthew-walters** [istio/istio#22435]
Tried with EKS (k8s 1.14.9) and minikube on mac and pc.

Downloaded the Istio 1.5.0 release
browsed to _istio-1.5.0/install/kubernetes/operator/profiles_
Executed `istio manifest apply -f separate.yaml`:

```
# The separate profile will disable istiod and bring back the old microservices model
# This will be removed in future (1.6) releases
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      istiod:
        enabled: false
```

Once finished installing, executed `kubectl -n istio-system get po`

Expected:  see pods for the microservices installed (citadel, pilot, etc)
Actual:  see istiod pod
