### ISSUE TITLE
Gateways customizations are not being picked up by istioctl

### ISSUE THREAD

**Issue by jwendell** [istio/istio#22430]
As an example, `istioctl manifest generate --set values.gateways.istio-ingressgateway.autoscaleMax=10` doesn't change anything and generates the same output as if I had not passed `--set`.

autoscale was just an example, it doesn't work with other gateways keys as well.

**Comment by morvencao** [comment]
try this:
```
cat << EOF > gateways-k8s.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          hpaSpec:
            maxReplicas: 8
EOF

istioctl manifest generate -f gateways-k8s.yaml
```
