### ISSUE TITLE
Match Routing Rule for Kubernetes Ingress

### ISSUE THREAD

**Issue by iusergii** [istio/istio#22447]
**Bug description**
Pilot creates "exact" match routes rule instead of "prefix" for standard Kubernetes Ingress paths. 

[] Configuration Infrastructure
[X] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Steps to reproduce the bug**
Apply following Ingress configuration:
```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: istio-ingress
spec:
  rules:
  - host: istio-ingress.exampple.com
    http:
      paths:
      - backend:
          serviceName: helloworld.istio-system.svc.cluster.local
          servicePort: 5000
        path: /
```

Pilot creates routes with "path" (exact) match to `/`
```bash
istioctl proxy-config route istio-ingressgateway -o json
```

```json
{
  "name": "istio-ingress.exampple.com:80",
    "domains": [
      "istio-ingress.exampple.com",
      "istio-ingress.exampple.com:80"
    ],
    "routes": [
      {
        "match": {
          "path": "/",
          "caseSensitive": true
        },
        "route": {
          "cluster": "outbound|5000||helloworld.istio-system.svc.cluster.local",
          "timeout": "0s",
          "retryPolicy": {
            "retryOn": "connect-failure,refused-stream,unavailable,cancelled,resource-exhausted,retriable-status-codes",
            "numRetries": 2,
            "retryHostPredicate": [
              {
                "name": "envoy.retry_host_predicates.previous_hosts"
              }
            ],
            "hostSelectionRetryMaxAttempts": "5",
            "retriableStatusCodes": [
              503
            ]
          },
          "maxGrpcTimeout": "0s"
        },
        "metadata": {
          "filterMetadata": {
            "istio": {
              "config": "/apis/networking.istio.io/v1alpha3/namespaces/istio-system/virtual-service/istio-ingress-exampple-com-istio-ingress-istio-autogenerated-k8s-ingress"
            }
          }
        },
        "decorator": {
          "operation": "helloworld.istio-system.svc.cluster.local:5000/"
        }
      }
    ]
  }
}
```

**Expected behavior**
From my experience with Kubernetes Ingress it's more common to have "prefix" match rule. 
Request to `istio-ingress.exampple.com/hello`  should be forward to `helloworld.istio-system.svc.cluster.local/hello`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```bash
client version: 1.5.0
control plane version: 1.5.0
data plane version: 1.5.0
```

**Additional context**
It's not much information about Istio and Kubernetes Ingress in Docs. Found a bit in [FAQ](https://istio.io/faq/traffic-management/#ingress-with-no-route-rules).  Also wondering is there any doc about ingress annotations. Example in FAQ has `ingress.kubernetes.io/rewrite-target: /` but I don't see it in [Resource Annotations](https://istio.io/docs/reference/config/annotations/)
