### ISSUE TITLE
tls-check not compatible with PeerAuthentication object

### ISSUE THREAD

**Issue by HugoPuntos** [istio/istio#22471]
**Bug description**

Hello,

The `istioctl authn tls-check` always report a status set to `CONFLICT`: it doesn't manage to retrieve the authentication policy object applying to the host.

    HOST:PORT                                  STATUS       SERVER      CLIENT           AUTHN POLICY     DESTINATION RULE
    reviews.default.svc.cluster.local:9080     CONFLICT     DISABLE     ISTIO_MUTUAL     None             default/my-destination-rule

The status seems correct when I use a `MeshPolicy` object:

    HOST:PORT                                  STATUS     SERVER     CLIENT           AUTHN POLICY     DESTINATION RULE
    reviews.default.svc.cluster.local:9080     OK         STRICT     ISTIO_MUTUAL     /default         default/my-destination-rule

**Expected behavior**

tls-check should report the correct status of mtls.

**Steps to reproduce the bug**

0. Enable automatic sidecar injection: `kubectl label namespace default istio-injection=enabled`

1. Deploy the bookinfo application (https://github.com/istio/istio/blob/master/samples/bookinfo/platform/kube/bookinfo.yaml).

2. Apply a destination rule

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: my-destination-rule
spec:
  host: reviews
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
    - name: v3
      labels:
        version: v3
```

3. Apply a virtual service

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
    - reviews
  http:
    - route:
        - destination:
            host: reviews
            subset: v1
          weight: 0
        - destination:
            host: reviews
            subset: v2
          weight: 100
        - destination:
            host: reviews
            subset: v3
          weight: 0

```

4. Apply an authentication policy

```
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "example-policy"
  namespace: "default"
spec:
  mtls:
    mode: STRICT
```

Result:

```
istioctl authn tls-check reviews-v1-756b7ff5cc-6rp7l reviews.default.svc.cluster.local
HOST:PORT                                  STATUS       SERVER      CLIENT           AUTHN POLICY     DESTINATION RULE
reviews.default.svc.cluster.local:9080     CONFLICT     DISABLE     ISTIO_MUTUAL     None             default/my-destination-rule
```

Workaround:

Use of the `MeshPolicy` type:

```
apiVersion: "authentication.istio.io/v1alpha1"
kind: "MeshPolicy"
metadata:
  name: "default"
spec:
  peers:
    - mtls: {}
```

```
HOST:PORT                                  STATUS     SERVER     CLIENT           AUTHN POLICY     DESTINATION RULE
reviews.default.svc.cluster.local:9080     OK         STRICT     ISTIO_MUTUAL     /default         default/my-destination-rule
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ > istioctl version --remote
client version: 1.5.0
control plane version: 1.5.0
data plane version: 1.5.0 (10 proxies)

$ > kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.24", GitCommit:"f2734800eba37df4400813ab9340886059d56105", GitTreeState:"clean", BuildDate:"2020-02-05T18:38:43Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

With istioctl.
