### ISSUE TITLE
Istio Operator does not create multiple ingress gateways in 1.5.1

### ISSUE THREAD

**Issue by jessebye** [istio/istio#22485]
**Bug description**

When using Istio Operator, the operator does not create any non-default ingress gateways. It only creates the default gateway.

**Expected behavior**

The custom ingress gateways are created by the operator.

**Steps to reproduce the bug**

Use the following configuration:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  components:
    ingressGateways:
      - enabled: true
        name: istio-ingressgateway
      - enabled: true
        name: istio-ingressgateway-public
```
Install via Istio Operator, i.e. `kubectl apply -f config.yaml`.

Observe that only one gateway is created.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istioctl version --remote:
```
client version: 1.5.1
control plane version: 1.5.1
data plane version: 1.5.1 (6 proxies)
```

kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T23:41:24Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-26T01:12:54Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

Operator.

**Environment where bug was observed (cloud vendor, OS, etc)**

EKS on 1.15.

**Comment by jessebye** [comment]
I found the issue was due to using the `1.5.0` operator docker image. Updating to `1.5.1` resolved this.

My problem was that I used the `https://istio.io/operator.yaml` URL to get my operator manifest, assuming it would pull down the latest operator image. But it still (as of time of writing) is giving me operator 1.5.0.

**Comment by howardjohn** [comment]
@sdake ^ can we please fix this?

**Comment by linuxbsdfreak** [comment]
Hi @jessebye @howardjohn . I had also reported this issue with the previous version

https://github.com/istio/istio/issues/21989

I have added the below config and it still does not work 

```
 components:
    policy:
      enabled: false
    telemetry:
      enabled: false
    egressGateways:
    - enabled: true
      k8s:
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
      name: istio-egressgateway
    ingressGateways:
    - enabled: true
      k8s:
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
      name: istio-ingressgateway
    - enabled: true
      k8s:
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
      name: istio-ingressgateway-public
```

The operator gives the following error

```
2020-03-31T10:44:31.286390Z     error   failed to generate IstioOperator spec, unknown field "istio-ingressgateway-public" in v1alpha1.GatewaysConfig
```
The operator is running with version 1.5.1
  image: docker.io/istio/operator:1.5.1

**Comment by linuxbsdfreak** [comment]
Hi @jessebye @howardjohn . I did one more test. Without the below it works fine

```
  values:                                                                                                                
    global:                                                                                                              
     sds:                                                                                                                
       enabled: true                                                                                                     
     proxy:                                                                                                              
       accessLogEncoding: TEXT                                                                                           
       accessLogFile: /dev/stdout                                                                                        
       autoInject: enabled                                                                                               
    gateways:                                                                                                            
      istio-ingressgateway:                                                                                              
        externalTrafficPolicy: Local                                                                                     
        autoscaleEnabled: true                                                                                           
        serviceAnnotations:                                                                                              
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"                                                       
          cert.gardener.cloud/secretname: "wildcard-ssl-secret"                                                          
          dns.gardener.cloud/class: garden                                                                               
          dns.gardener.cloud/dnsnames: "*.istio.poc.example.com"                         
          dns.gardener.cloud/ttl: "300"                                                                                  
        labels:                                                                                                          
          app: istio-ingressgateway                                                                                      
          istio: istio-ingressgateway                                                                                    
        name: istio-ingressgateway                                                                                       
        sds:                                                                                                             
          enabled: true                                                                                                  
      istio-ingressgateway-public:                                                                                       
        externalTrafficPolicy: Local                                                                                     
        autoscaleEnabled: true                                                                                           
        serviceAnnotations:                                                                                              
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"                                                       
          cert.gardener.cloud/secretname: "wildcard-ssl-secret-public"                                                   
          dns.gardener.cloud/class: garden                                                                               
          dns.gardener.cloud/dnsnames: "*.public.poc.example.com"                        
          dns.gardener.cloud/ttl: "300"                                                                                  
        labels:                                                                                                          
          app: istio-ingressgateway-public                                                                               
          istio: istio-ingressgateway-public                                                                             
        name: istio-ingressgateway-public                                                                                
        sds:                                                                                                             
          enabled: true                                                                                                  
```
This gives me the error of 

```
2020-03-31T10:44:31.286390Z     error   failed to generate IstioOperator spec, unknown field "istio-ingressgateway-public" in v1alpha1.GatewaysConfig
```

**Comment by ostromart** [comment]
The problem with the above config is that istio-ingressgateway-public: cannot be in values anymore. All values settings are under istio-ingressgateway and apply to all ingressgateways (so assuming that the above applies to all your gateways, just change istio-ingressgateway-public to istio-ingressgateway). Customizations to each gateway must be through components.ingressGateways list. e.g. 
```yaml
components:
  ingressGateways:
  - name: istio-ingressgateway-public
     k8s:
     ...
values:
  gateways:
    istio-ingressgateway:
    ...
```
It's a bit weird for sure but it's just a side effect to how the new charts are structured (there's only one gateway in the charts).
