### ISSUE TITLE
Panic when upgrading from 1.5.0 to 1.5.1 when passing in the config via stdin

### ISSUE THREAD

**Issue by bishtawi** [istio/istio#22488]
**Bug description**
Encountered a panic (`panic: assignment to entry in nil map`) with a stack trace (below) when upgrading Istio from 1.5.0 to 1.5.1.

The IstioOperator is passed in via stdin.

EDIT: Yup, its because I am passing the config via stdin. Writing to a file works. It is not because of my actual configs content.

~~The only thing that we are doing that might be a bit uncommon is that we set up two custom ingresses, each in their own separate namespace, rather than using the default istio-ingressgateway. Not sure if this is causing the panic.~~

```
$ istioctl -c './config/kubeconfig/kubeconfig_greenfield-dev-eks' upgrade --verbose -y -w -f -<<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  addonComponents:
    grafana:
      enabled: true
    kiali:
      enabled: true
    prometheus:
      enabled: true
    tracing:
      enabled: true
  components:
    ingressGateways:
      - enabled: true
        name: istio-external-ingress
        namespace: istio-external-ingress
        k8s:
          service:
            type: NodePort
          serviceAnnotations: &serviceAnnotations
            service.beta.kubernetes.io/aws-load-balancer-access-log-emit-interval: "60"
            service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "true"
            service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name: "xxx"
            service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
            service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "300"
            service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
            service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
          overlays:
            - kind: Service
              name: istio-ingressgateway # Hardcoded name in Istio 1.5.0. Might change in 1.5.1
              patches:
                - path: spec.ports[name:kiali]
                - path: spec.ports[name:prometheus]
                - path: spec.ports[name:grafana]
                - path: spec.ports[name:tracing]
                - path: spec.ports[name:tls]
      - enabled: true
        name: istio-internal-ingress
        namespace: istio-internal-ingress
        k8s:
          serviceAnnotations:
            <<: *serviceAnnotations
            service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  unvalidatedValues:
    gateways:
      istio-external-ingress:
        sds:
          enabled: true
      istio-internal-ingress:
        sds:
          enabled: true
  values:
    global:
      mtls:
        enabled: true
        auto: true
      proxy:
        accessLogFile: /dev/stdout
        accessLogEncoding: JSON
      policyCheckFailOpen: false
    sidecarInjectorWebhook:
      enabled: true
      rewriteAppHTTPProbe: true
    kiali:
      dashboard:
        jaegerURL: http://jaeger-query:16686
        grafanaURL: http://grafana:3000

EOF': exit status 2. Output: Control Plane - ingressgateway pod - istio-ingressgateway-8577f4c6f8-lt28d - version: 1.5.0
Control Plane - pilot pod - istiod-59f6fbc78f-jd2rl - version: 1.5.0

Upgrade version check passed: 1.5.0 -> 1.5.1.

panic: assignment to entry in nil map

goroutine 1 [running]:
istio.io/istio/operator/pkg/tpath.getPathContext(0xc000b18600, 0xc000ae9740, 0x1, 0x1, 0xc000ae9740, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	istio.io/istio@/operator/pkg/tpath/tpath.go:189 +0x16cb
istio.io/istio/operator/pkg/tpath.GetPathContext(...)
	istio.io/istio@/operator/pkg/tpath/tpath.go:72
istio.io/istio/operator/pkg/tpath.GetConfigSubtree(0x0, 0x0, 0x3515aea, 0x4, 0xc00000e010, 0x0, 0x0, 0x0)
	istio.io/istio@/operator/pkg/tpath/tpath.go:634 +0x19f
istio.io/istio/operator/pkg/tpath.GetSpecSubtree(...)
	istio.io/istio@/operator/pkg/tpath/tpath.go:624
istio.io/istio/operator/cmd/mesh.upgrade(0xc0007552fa, 0xc000726e00, 0xc000d19d48, 0x391cc60, 0xc00000e020)
	istio.io/istio@/operator/cmd/mesh/upgrade.go:176 +0x14cb
istio.io/istio/operator/cmd/mesh.UpgradeCmd.func1(0xc0007a0a00, 0xc000726f50, 0x0, 0x7, 0x0, 0x0)
	istio.io/istio@/operator/cmd/mesh/upgrade.go:111 +0x125
github.com/spf13/cobra.(*Command).execute(0xc0007a0a00, 0xc000726ee0, 0x7, 0x7, 0xc0007a0a00, 0xc000726ee0)
	github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0006acf00, 0x8, 0x8, 0xc0006acf00)
	github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	istio.io/istio@/istioctl/cmd/istioctl/main.go:29 +0x76
```

[ ] Configuration Infrastructure
[ ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
The upgrade to be successful with no error

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
$ istioctl version --remote
client version: 1.5.1
control plane version: 1.5.0
data plane version: 1.5.0 (27 proxies)

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-26T01:12:54Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Via istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS 1.15

**Comment by bishtawi** [comment]
Forgot to mention that when I installed Istio 1.5.0, I killed the default ingress through the command `kubectl -n istio-system delete service/istio-ingressgateway deployment.apps/istio-ingressgateway horizontalpodautoscaler.autoscaling/istio-ingressgateway` as I was attempting to just use my two custom ingresses instead of the default one.

Today I will attempt to use the default ingress with one additional custom ingress instead of my original plan of two custom ingresses. Hopefully that makes a difference?

**Comment by bishtawi** [comment]
Alright so I deleted my two namespaces `istio-internal-ingress` and `istio-external-ingress` to get rid of both of my custom ingresses. Checked kubectl and AWS console and now I have no active LBs.

Then I recreated an empty namespace `istio-internal-ingress`.

Then I ran `istioctl upgrade` on the config included below to reinstall 1.5.0 (not 1.5.1) to bring back the default ingress and one of my custom ingress. This was successful and checking kubectl and AWS console shows I have two running LBs.

Then I ran `istioctl upgrade` on the same config (below) to upgrade to 1.5.1 and got the exact same panic with the same stacktrace as I got before.

My new config:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  addonComponents:
    grafana:
      enabled: true
    kiali:
      enabled: true
    prometheus:
      enabled: true
    tracing:
      enabled: true
  components:
    ingressGateways:
      - enabled: true
        name: istio-ingressgateway
        namespace: istio-system
        k8s:
          service:
            type: NodePort
          serviceAnnotations: &serviceAnnotations
            service.beta.kubernetes.io/aws-load-balancer-access-log-emit-interval: "60"
            service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "true"
            service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name: "xxx"
            service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
            service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "300"
            service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
            service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
          overlays:
            - kind: Service
              name: istio-ingressgateway
              patches:
                - path: spec.ports[name:kiali]
                - path: spec.ports[name:prometheus]
                - path: spec.ports[name:grafana]
                - path: spec.ports[name:tracing]
                - path: spec.ports[name:tls]
      - enabled: true
        name: istio-internal-ingress
        namespace: istio-internal-ingress
        k8s:
          serviceAnnotations:
            <<: *serviceAnnotations
            service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  unvalidatedValues:
    gateways:
      istio-ingressgateway:
        sds:
          enabled: true
      istio-internal-ingress:
        sds:
          enabled: true
  values:
    global:
      mtls:
        enabled: true
        auto: true
      proxy:
        accessLogFile: /dev/stdout
        accessLogEncoding: JSON
      policyCheckFailOpen: false
    sidecarInjectorWebhook:
      enabled: true
      rewriteAppHTTPProbe: true
    kiali:
      dashboard:
        jaegerURL: http://jaeger-query:16686
        grafanaURL: http://grafana:3000
```

**Comment by bishtawi** [comment]
Ok, So I managed to install 1.5.1 by calling `istioctl upgrade` without passing in my config. So that got me the default installation but at least Im on 1.5.1.

Then I ran `istioctl manifest apply` with my config and that outputted the error `Error: failed to apply manifests: failed to generate manifest: patch error: node [name:kiali] is zero, node [name:prometheus] is zero, node [name:grafana] is zero, node [name:tracing] is zero, node [name:tls] is zero`.

So then I replaced the block:
```
          overlays:
            - kind: Service
              name: istio-ingressgateway
              patches:
                - path: spec.ports[name:kiali]
                - path: spec.ports[name:prometheus]
                - path: spec.ports[name:grafana]
                - path: spec.ports[name:tracing]
                - path: spec.ports[name:tls]
```

With
```
          service:
            ports:
              - name: status-port
                port: 15020
                protocol: TCP
                targetPort: 15020
              - name: http2
                port: 80
                protocol: TCP
                targetPort: 80
              - name: https
                port: 443
                protocol: TCP
                targetPort: 443
```

And reran `istioctl manifest apply` and that was successful. No idea if that patch error I got during a manifest apply is related to the panic I got during the upgrade.

I only want to expose the health check port, HTTP, and HTTPS ports to the external LB. I do not want the kiali, prometheus, grafana, tracing ports exposed to the public which is why I need this block. I assume this is the right way to accomplish this?

**Comment by richardwxn** [comment]
@elfinhe

**Comment by elfinhe** [comment]
I will take a look this week.

**Comment by bishtawi** [comment]
Not sure if this helps, but with the following config below (passed via stdin), the upgrade still fails on 1.5.1. I then did the upgrade with no custom config, which was obviously successful. Then I did a manifest apply on the exact same config (passed via stdin) and that is successful.

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  addonComponents:
    grafana:
      enabled: true
    kiali:
      enabled: true
    prometheus:
      enabled: true
    tracing:
      enabled: true
  components:
    ingressGateways:
      - enabled: true
        name: istio-ingressgateway
        namespace: istio-system
        k8s:
          service:
            type: NodePort
            ports:
              - name: status-port
                port: 15020
                protocol: TCP
                targetPort: 15020
              - name: http2
                port: 80
                protocol: TCP
                targetPort: 80
              - name: https
                port: 443
                protocol: TCP
                targetPort: 443
          serviceAnnotations: &serviceAnnotations
            service.beta.kubernetes.io/aws-load-balancer-access-log-emit-interval: "60"
            service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "true"
            service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name: "xxx"
            service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
            service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "300"
            service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
            service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      - enabled: true
        name: istio-ingressgateway-internal
        namespace: istio-system
        k8s:
          serviceAnnotations:
            <<: *serviceAnnotations
            service.beta.kubernetes.io/aws-load-balancer-internal: "true"
          overlays: # These overlays are needed to work around a bug present in Istio 1.5.1 regarding setting up additional ingresses https://github.com/istio/istio/issues/19263#issuecomment-605319996
            - kind: Deployment
              name: istio-ingressgateway-internal
              patches:
                - path: metadata.labels.app
                  value: istio-ingressgateway-internal
                - path: spec.selector.matchLabels.app
                  value: istio-ingressgateway-internal
                - path: spec.template.metadata.labels.app
                  value: istio-ingressgateway-internal
            - kind: Service
              name: istio-ingressgateway-internal
              patches:
                - path: metadata.labels.app
                  value: istio-ingressgateway-internal
                - path: spec.selector.app
                  value: istio-ingressgateway-internal
            - kind: Gateway
              name: ingressgateway
              patches:
                - path: metadata.name
                  value: ingressgateway-internal
                - path: spec.selector.app
                  value: istio-ingressgateway-internal
            - kind: PodDisruptionBudget
              name: ingressgateway
              patches:
                - path: metadata.name
                  value: ingressgateway-internal
                - path: spec.selector.matchLabels.app
                  value: istio-ingressgateway-internal
  unvalidatedValues:
    gateways:
      istio-ingressgateway:
        sds:
          enabled: true
      istio-ingressgateway-internal:
        sds:
          enabled: true
  values:
    global:
      mtls:
        enabled: true
        auto: true
      proxy:
        accessLogFile: /dev/stdout
        accessLogEncoding: JSON
      policyCheckFailOpen: false
    sidecarInjectorWebhook:
      enabled: true
      rewriteAppHTTPProbe: true
    kiali:
      dashboard:
        jaegerURL: http://jaeger-query:16686
        grafanaURL: http://grafana:3000
```
