### ISSUE TITLE
Can not route several GRPC Services through Ingress Gateway

### ISSUE THREAD

**Issue by nelsonyaccuzzi** [istio/istio#22503]
**Bug description**

I have several services in my cluster that exposes a GRPC API, so, I would like to be able to route to them from the Ingress Gateway, but I can't make it work.

Here is my setup

The services exposes por 8080 for rest and 9090 for GRPC

```

NAME                            TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)             AGE
serviceA             ClusterIP   10.0.106.238   <none>        8080/TCP,9090/TCP   54d
serviceB             ClusterIP   10.0.196.212   <none>        8080/TCP,9090/TCP   54d
```
```
...
  ports:
  - name: http2
    port: 8080
    protocol: TCP
    targetPort: http2
  - name: grpc
    port: 9090
    protocol: TCP
    targetPort: 9090
...
```
Deployment

```
...
ports:
        - containerPort: 8080
          name: http2
          protocol: TCP
        - containerPort: 9090
          name: grpc
          protocol: TCP
...
```
Ingress Gateway

```
- apiVersion: networking.istio.io/v1alpha3
  kind: Gateway
  metadata:
    annotations:
    name: gateway
    namespace: services
  spec:
    selector:
      istio: ingressgateway
    servers:
    - hosts:
      - '*'
      port:
        name: grpc
        number: 9090
        protocol: grpc
```

Virtual Services
```
apiVersion: v1
items:
- apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  metadata:
    annotations:
    name: serviceA
    namespace: services
  spec:
    gateways:
    - gateway
    hosts:
    - '*'
    http:
    - match:
      - port: 9090
      - uri:
          prefix: /serviceA
      route:
      - destination:
          host: serviceA.services.svc.cluster.local
          port:
            number: 9090
- apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  metadata:
    annotations:
    name: serviceB
    namespace: services
  spec:
    gateways:
    - gateway
    hosts:
    - '*'
    http:
    - match:
      - port: 9090
      - uri:
          prefix: /serviceB
      route:
      - destination:
          host: serviceB.services.svc.cluster.local
          port:
            number: 9090
kind: List
```

When I check the ingress config I see this

```
➜  ~ istioctl proxy-config routes istio-ingressgateway-5c6df4f597-8hw5z.istio-system -ojson
[
    {
        "name": "http.9090",
        "virtualHosts": [
            {
                "name": "*:9090",
                "domains": [
                    "*",
                    "*:9090"
                ],
                "routes": [
                    {
                        "match": {
                            "prefix": "/"
                        },
                        "route": {
                            "cluster": "outbound|9090||serviceA.services.svc.cluster.local",

...
{
                        "match": {
                            "prefix": "/"
                        },
                        "route": {
                            "cluster": "outbound|9090||serviceB.services.svc.cluster.local",


```

With this config I only can call the serviceA trough the ingress gateway, and that is because I create de virtual service serviceA first and the match prefix / is first, or so I guess.

I also tried to route rest services and that I make it work, but for some reason grpc doesnt work

**Expected behavior**

Ingress Gateway to be able to route between several grpc services

**Steps to reproduce the bug**

Deploy 2 or more GRPC services and try to route trough them via Ingress Gateway

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
➜  ~ istioctl version --remote
client version: 1.2.2
citadel version: 1.2.2
galley version: 1.2.2
ingressgateway version: 1.2.2
pilot version: 1.2.2
sidecar-injector version: 1.2.2
telemetry version: 1.2.2
➜  ~ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T07:10:00Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4+icp-ee", GitCommit:"d03f6421b5463042d87aa0211f116ba4848a0d0f", GitTreeState:"clean", BuildDate:"2019-01-17T13:14:09Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
➜  ~ helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

**How was Istio installed?**

IBM Istio Helm Chart

**Environment where bug was observed (cloud vendor, OS, etc)**

ICP version 3.1.2
