### ISSUE TITLE
IstioOperator API: External Prometheus with Kiali stopped working after 1.5

### ISSUE THREAD

**Issue by gopisaba** [istio/istio#22510]
**Bug description**
Setting the external Prometheus address URL in Kiali is not working. `values.kiali.prometheusAddr`

**Steps to reproduce the bug**
```yaml
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  creationTimestamp: null
spec:
  addonComponents:
    kiali:
      enabled: true
      k8s:
        replicaCount: 3
    prometheus:
      enabled: false
 ...
  values:
    kiali:
      prometheusAddr: http://prometheus-operator-prometheus.monitoring.svc.cluster.local:9090
      dashboard:
        grafanaInClusterURL: http://prometheus-operator-grafana.monitoring.svc.cluster.local
```
`istioctl manifest apply -f istio-operator.yaml`

**Expected Behaviour**
Kiali to use the external prometheus `http://prometheus-operator-prometheus.monitoring.svc.cluster.local:9090` and grafana `http://prometheus-operator-grafana.monitoring.svc.cluster.local`

**Actual Behaviour**
`prometheusAddr` still using the default value `http://prometheus.istio-system:9090`
```yaml                                                                                                                                           
apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
    release: istio
data:
  config.yaml: |
    istio_component_namespaces:
      grafana: istio-system
      tracing: istio-system
      pilot: istio-system
      prometheus: istio-system
    istio_namespace: istio-system
    auth:
      strategy: login
    deployment:
      accessible_namespaces: ['**']
    login_token:
      signing_key: "**********"
    server:
      port: 20001
      web_root: /kiali
    external_services:
      istio:
        url_service_version: http://istio-pilot.istio-system:8080/version
      tracing:
        url:
        in_cluster_url: http://tracing/jaeger
      grafana:
        url:
        in_cluster_url: http://prometheus-operator-grafana.monitoring.svc.cluster.local
      prometheus:
        url: http://prometheus.istio-system:9090
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
client version: 1.5.1
control plane version: 1.5.1
data plane version: 1.5.1 (5 proxies), 1.5.0 (1 proxies)
```
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-15T15:50:25Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS
