### ISSUE TITLE
values.gateways.istio-ingressgateway ports in NodePort mode not worked as expected.

### ISSUE THREAD

**Issue by elvizlai** [istio/istio#22538]
**Bug description**

Using config to assign svc NodePort, but not configured as expected.
I also tried using `istioctl manifest generate -f conf.yaml > generated-manifest.yaml` but not found the port I configured.

conf.yaml
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  addonComponents:
    kiali:
      enabled: true
      k8s:
        replicaCount: 1
    prometheus:
      enabled: true
      k8s:
        replicaCount: 1
    tracing:
      enabled: true
  values:
    gateways:
      istio-ingressgateway:
        ports:
          - name: http2
            port: 80
            nodePort: 31380
          - name: https
            port: 443
            nodePort: 31390
        type: NodePort
    global:
      jwtPolicy: first-party-jwt
```

Using config blew works, but `previous` should also be worked(profile demo has similar config).

config2.yaml
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  addonComponents:
    kiali:
      enabled: true
      k8s:
        replicaCount: 1
    prometheus:
      enabled: true
      k8s:
        replicaCount: 1
    tracing:
      enabled: true
  components: #WIP
    ingressGateways:
      - enabled: true
        k8s:
          service:
            ports:
              - name: http2
                port: 80
                nodePort: 31380
              - name: https
                port: 443
                nodePort: 31390
  values:
    gateways:
      istio-ingressgateway:
        type: NodePort
    global:
      jwtPolicy: first-party-jwt
```

**Expected behavior**

Using first config.yaml applied should have svc port `80:31380,443:31390`

**Steps to reproduce the bug**
`istioctl manifest apply -f config.yaml`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
client version: 1.5.1
control plane version: 1.5.1
data plane version: 1.5.1 (2 proxies)

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:31:31Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
CentOS7
