### ISSUE TITLE
multi-region using locality feature - how to avoid traffic loop if both region are down ?

### ISSUE THREAD

**Issue by kidiyoor** [istio/istio#22534]
**Bug description**
I have a similar two region setup as described in here: https://github.com/istio/istio/issues/19257

When httpbin deployment is down in both the region the traffic loops b/w the ingress and we see the below response (we append a header each time request hits ingress).
```
$ curl 33.44.55.66/get  -v
*   Trying IP...
* TCP_NODELAY set
* Connected to IP (IP) port 80 (#0)
> GET /get HTTP/1.1
> Host: IP
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 431 Request Header Fields Too Large
< content-length: 0
< x-envoy-upstream-service-time: 5850
< date: Fri, 27 Mar 2020 02:29:43 GMT
< server: istio-envoy
<
* Connection #0 to host 35.231.234.156 left intact
```

What is the recommended pattern to avoid this loop ?

**Expected behavior**
If both the region is down return 503

**Steps to reproduce the bug**

```
# In region central.

apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: other-region-ingress
spec:
  hosts:
  - httpbin.default.svc.cluster.local
  ports:
  - name: http
    number: 80
    protocol: http
  resolution: STATIC
  location: MESH_INTERNAL
  endpoints:
  - address: 33.44.55.77
    locality: us-east1
    ports:
      http: 80
```
```
# In region east.

kind: ServiceEntry
metadata:
  name: other-region-ingress
spec:
  hosts:
  - httpbin.default.svc.cluster.local
  ports:
  - name: http
    number: 80
    protocol: http
  resolution: STATIC
  location: MESH_INTERNAL
  endpoints:
  - address: 33.44.55.66
    locality: us-central
    ports:
      http: 80
```
```
      localityLbSetting:
        enabled: true
        failover:
        - from: us-central
          to: us-east1
        - from: us-east1
          to: us-central
```
```
  http:
  - route:
    - destination:
        host: httpbin.default.svc.cluster.local
        port:
          number: 8000
```
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istioctl version --remote
client version: 1.5.0
control plane version: 1.5.0
data plane version: 1.5.0 (3 proxies)

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by chihaiaalex** [comment]
Same issue here. Also noticed that the HPA will scale up the ingress gateway due to the big number of requests going back and forth.

**Comment by alexchihaia-oro** [comment]
Any feedback on this? The issue still persists and no solutions or workarounds were identified. Please reopen.

**Comment by chihaiaalex** [comment]
This is what I came up with. I basically add a header each time the request passes through the ingress gateway and when it reaches the 5 failovers threshold, I do a fault injection with a 503 status. Any thoughts/ideas on how I can improve it?
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: demo-vs
  namespace: default
spec:
  gateways:
    - demo-gw
  hosts:
    - demo.digitalapp.orange.intra
  http:
    - match:
        - headers:
            x-ingress-failover:
              exact: "1"
      headers:
        response:
          set:
            x-ingress-failover: "2"
        request:
          set:
            x-ingress-failover: "2"
      route:
        - destination:
            host: demo.default.svc.cluster.local
            port:
              number: 8080
    - match:
        - headers:
            x-ingress-failover:
              exact: "2"
      headers:
        response:
          set:
            x-ingress-failover: "3"
        request:
          set:
            x-ingress-failover: "3"
      route:
        - destination:
            host: demo.default.svc.cluster.local
            port:
              number: 8080
    - match:
        - headers:
            x-ingress-failover:
              exact: "3"
      headers:
        response:
          set:
            x-ingress-failover: "4"
        request:
          set:
            x-ingress-failover: "4"
      route:
        - destination:
            host: demo.default.svc.cluster.local
            port:
              number: 8080
    - match:
        - headers:
            x-ingress-failover:
              exact: "4"
      headers:
        response:
          set:
            x-ingress-failover: "5"
        request:
          set:
            x-ingress-failover: "5"
      route:
        - destination:
            host: demo.default.svc.cluster.local
            port:
              number: 8080
    - match:
        - headers:
            x-ingress-failover:
              exact: "5"
      headers:
        response:
          set:
            x-ingress-failover: "6"
        request:
          set:
            x-ingress-failover: "6"
      route:
        - destination:
            host: demo.default.svc.cluster.local
            port:
              number: 8080
    - match:
        - headers:
            x-ingress-failover:
              exact: "6"
      fault:
        abort:
          httpStatus: 503
          percentage:
            value: 100
      route:
        - destination:
            host: demo.default.svc.cluster.local
            port:
              number: 8080
    - headers:
        response:
          set:
            x-ingress-failover: "1"
        request:
          set:
            x-ingress-failover: "1"
      route:
        - destination:
            host: demo.default.svc.cluster.local
            port:
              number: 8080

```
