### ISSUE TITLE
Istio Ingress Gateway will not permit short names

### ISSUE THREAD

**Issue by vincentjorgensen** [istio/istio#22533]
**Bug description**
Short names not allowed in istio ingress gateways
```
for: "gateway-machine.yaml": admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: 1 error occurred:
	* short names (non FQDN) are not allowed
```

**Expected behavior**
In our local development environment, we use DNS search domains to so that internal-to-kubernetes shortnames and the external-to-kubernetes short names match up. For example, regardless of whether you are developing in devel or preprod, "machine" will always resolve to the correct DNS host for the development environment.

If an external application attempts to use an ingress gateway, however, to communicate inside the mesh, the gateway fails if the FQDN isn't used.

For example, this works:
```
grpcurl machine.devel.local.domain:4000 Action/Do
```

But this never does (and it never will, if I understand ingress gateways correctly)
```
grpcurl machine:4000 Action/Do
```

Even though both `machine.devel.local.domain` and `machine` resolve correctly in DNS

If ingress gateways can't route based on short name headers, is there an alternative to using ingress gateways for getting `machine` to correctly route inside the ingress gateway? I have an example manifest below

**Steps to reproduce the bug**
```
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: machine-gateway
  namespace: devel
  labels:
    app: machine
spec:
  selector:
    istio: ingressgateway
  servers: 
  - port:
      number: 4000
      name: grpc
      protocol: grpc
    hosts:
    - "machine.devel.local.domain"
    # - "machine" # this line isn't allowed
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: machine-virtualservice
  namespace: devel
  labels:
    app: machine
    service_name: machine
spec:
  hosts:
  - "machine.devel.local.domain"
  - "machine" # this line doesn't do anything
  gateways:
  - machine-gateway
  http: 
  - match:
    - port: 4000
    route:
    - destination:
        port:
          number: 4000
        host: machine
...

```
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
% istioctl version --remote
client version: 1.4.3
control plane version: 1.4.3
data plane version: 1.4.3 (147 proxies)
```
```
% kubectl version --short
Client Version: v1.17.4
Server Version: v1.14.9-eks-502bfb
```

**How was Istio installed?**
kubectl apply

**Environment where bug was observed (cloud vendor, OS, etc)**
EKS 1.14

Thank you in advance for your advice and assistance.
