### ISSUE TITLE
Unable to disable  policy in the SidecarInjectorConfig 

### ISSUE THREAD

**Issue by alexandrst88** [istio/istio#22544]
**Describe the feature request**
While using the operator, 

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-operator
spec:
  profile: default
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-internal: "0.0.0.0/0"
    sidecarInjectorWebhook:
      enabled: true
      policy: disabled
```
Policy field doesn't reflected in configmap
kubectl get -o yaml  cm istio-sidecar-injector -n istio-system
```
apiVersion: v1
data:
  config: |-
    policy: enabled
    alwaysInjectSelector:
```
**Describe alternatives you've considered**

[*] Configuration Infrastructure
[*] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[*] User Experience
[ ] Developer Infrastructure

**Additional context**
