### ISSUE TITLE
User defined gateways lead to errors in operator

### ISSUE THREAD

**Issue by ostromart** [istio/istio#22548]
User reported in controller case with the following config:

```yaml
  components:
    policy:
      enabled: false
    telemetry:
      enabled: false
    egressGateways:
    - enabled: true
      k8s:
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
      name: istio-egressgateway
    ingressGateways:
    - enabled: true
      k8s:
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
        service:
          ports:
          - name: status-port
            port: 15020
            targetPort: 15020
          - name: http2
            port: 80
            targetPort: 80
          - name: https
            port: 443
          - name: kiali
            port: 15029
            targetPort: 15029
          - name: prometheus
            port: 15030
            targetPort: 15030
          - name: grafana
            port: 15031
            targetPort: 15031
```

leads to error: 

```
 * invalid envoy access log service address ":": port () is not a number: strconv.Atoi: parsing "": invalid syntax
```
