### ISSUE TITLE
requestPrincipals["*"] in AuthorizationPolicy don't match when sub claim is empty

### ISSUE THREAD

**Issue by uncycler** [istio/istio#22540]
**Bug description**
I'm using Cloudflare Access in front of Istio and I validate the token using RequestAuthentication. It works fine with the browser since the JWT token include a subject. When I use their "Access Token" feature, the generated JWT token's subject is an empty string and the AuthorizationPolicy with requestPrincipals["*"] in the source reject it (RBAC: access denied).

**Expected behavior**
The wildcard should match empty string as well.

**Steps to reproduce the bug**
Present a JWT token without subject. 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.5.0

**How was Istio installed?**
istioctl install

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS/EKS

**Comment by yangminzhu** [comment]
This is the intended behavior because the `*` actually means **non-empty** in the authorization policy. There was some confusion in previous documentation (maybe today).

To fix this, if you only need to ensure the JWT validation and doesn't care the principal, you could use the following workaround if the `iss` claim is always non-empty:

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: require-jwt
spec:
  rules:
  - when:
    - key: request.auth.claims[iss]
      values: ["*"]
```
