### ISSUE TITLE
Istio Operator 1.5.1 creates ingressgateway despite flag false

### ISSUE THREAD

**Issue by nemo83** [istio/istio#22545]
**Bug description**
Despite the following `IstioOperator` manifest:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-control-plane
  namespace: istio-system
spec:
  profile: default
  addonComponents:
    prometheus:
      enabled: false
  values:
    global:
      k8sIngress:
        enabled: false
```
IstioOperator is creating the Gateway object named: `ingressgateway` in the `istio-system` namespace. 

**Expected behavior**
IstioOperator should not create the `ingressgateway` Gateway object as per default profile in IstioOperator.
 
**Steps to reproduce the bug**
Install istio operator:
```
$ helm template install/kubernetes/operator/operator-chart/ \
  --set hub=docker.io/istio \
  --set tag=1.5.1 \
  --set operatorNamespace=istio-operator \
  --set istioNamespace=istio-system | kubectl apply -f -
```
Apply `IstioOperator` chart:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-control-plane
  namespace: istio-system
spec:
  profile: default
  addonComponents:
    prometheus:
      enabled: false
  values:
    global:
      k8sIngress:
        enabled: false
```
And then this will happen, while no gateway should have been created.
```
kubectl get gateway -n istio-system
NAME             AGE
ingressgateway   49s
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
istioctl version --remote
client version: 1.5-alpha.da2d49ef041ea6b82d5da506d9f25676a1795646
control plane version: 1.5.1
data plane version: 1.5.1 (3 proxies)
```
```
 kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T23:40:44Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
Helm N/A
**How was Istio installed?**
Istio Operator, please see above.

**Environment where bug was observed (cloud vendor, OS, etc)**
docker-for-desktop
