### ISSUE TITLE
Prometheus Operator kubelet service monitor not connecting to kubelets

### ISSUE THREAD

**Issue by andrewhertog** [istio/istio#22552]
**Bug description**
When using PrometheusOperator telemetry manifests to install service monitors, the kubelet service monitor fails to connect to the kubelets as it is using the http endpoint rather than the https one. 
`Get http://10.225.136.36:10255/metrics: dial tcp 10.225.136.36:10255: connect: connection refused`

I've manually changed the service monitor and corrected it but it would be nice if the manifests here reflected that change. 

Also, on a side, the prometheus-operator helm chart ships with a kubelet service monitor, so the istio kubelet monitor duplicates it causing there to be duplicate data in prometheus. It would be nice to put a flag to toggle that service monitor. (This is the ask in #22262 i believe)

**Expected behavior**
kubelet service monitor should successfully connect to the kublet metrics endpoint

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:54Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
```
❯ istioctl version --remote -i istio-system
client version: 1.4.6
citadel version: 1.4.6
citadel version: 1.4.6
citadel version: 1.4.6
dmz-lb version:
dmz-lb version:
dmz-lb version:
dmz-lb version:
dmz-lb version:
galley version: 1.4.6
galley version: 1.4.6
galley version: 1.4.6
pilot version: 1.4.6
pilot version: 1.4.6
pilot version: 1.4.6
policy version: 1.4.6
policy version: 1.4.6
policy version: 1.4.6
prv-lb version:
prv-lb version:
prv-lb version:
prv-lb version:
prv-lb version:
pub-lb version:
pub-lb version:
pub-lb version:
pub-lb version:
pub-lb version:
sidecar-injector version: 1.4.6
sidecar-injector version: 1.4.6
sidecar-injector version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
data plane version: 1.4.3 (15 proxies)
```
```
❯ helm version
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.7"}
```

**How was Istio installed?**
` istioctl manifest generate -f istio-ctl.yaml --force > istio-ctl-generated.yaml`
with the following relevant snippet to include the prometheus operator manifests:

```yaml
  values:
    # Disabled in favour of using the Prometheus-Operator
    prometheus:
      enabled: false

    # Using this in favour of the standalone prometheus install
    # This creates the istio servicemonitors required to monitor istio
    prometheusOperator:
      enabled: true
      nodeSelector:
        nodegroup: system
```

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS 1.14

I am willing to contribute a fix for this, but wanted to submit an issue first in case someone already has it in a pipeline
