### ISSUE TITLE
Gateway TLS termination makes VirtualService port match a little baffling.

### ISSUE THREAD

**Issue by phyllisstein** [istio/istio#22553]
**Describe the feature request**
:wave: Hey folks. I wanted to pitch a possible change to the way Istio maps from `Gateway` TLS requests to `VirtualService`s.

I've been trying out Istio, and I just spent a couple days flailing at my configuration, trying to figure out why HTTP requests to a `Gateway` resolved as expected, while HTTPS requests returned Istio's fallback `404`. The first stab I took at setting up a test nginx service looked like this:

<details>
	<summary>Broken <code>nginx-test.yaml</code> manifest</summary>

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx-test
  labels:
    app.kubernetes.io/name: nginx
spec:
  ports:
    - port: 80
      name: http
  selector:
    app.kubernetes.io/name: nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx-test
  labels:
    app.kubernetes.io/name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      containers:
        - name: nginx
          image: docker.io/nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: nginx-test.k8s.ignota.cloud
  namespace: istio-system
spec:
  commonName: nginx-test.k8s.ignota.cloud
  dnsNames:
    - nginx-test.k8s.ignota.cloud
  secretName: nginx-test.k8s.ignota.cloud
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: nginx-gateway-route53
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - nginx-test/nginx-test.k8s.ignota.cloud
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - nginx-test/nginx-test.k8s.ignota.cloud
      tls:
        mode: SIMPLE
        credentialName: nginx-test.k8s.ignota.cloud

---
# 💣 1-800-ONO-HALP
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx
  namespace: nginx-test
spec:
  hosts:
    - nginx-test.k8s.ignota.cloud
  gateways:
    - istio-system/nginx-gateway
  tls:
    - match:
        - port: 443
          sniHosts: [nginx-test.k8s.ignota.cloud]
      route:
        - destination:
            host: nginx.nginx-test.svc.cluster.local
  http:
    - match:
        - port: 80
      route:
        - destination:
            host: nginx.nginx-test.svc.cluster.local
```
</details>

My assumption, based on my understanding of the docs, was that _either_ TLS traffic terminated by the `Gateway` would be redirected to port 80 as HTTP traffic, _or_ I would need the `spec.tls` block to pass it back to the K8s `Service`---so I left both in there.

After a good long while shuffling namespaces, adding FQDNs, reconfiguring the load balancers, and logging wherever I could, I tried changing the `VirtualService` spec, mostly on a whim, to match HTTP traffic on port 443:

<details>
	<summary>Working <code>VirtualService</code></summary>

```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-route53
  namespace: nginx-test
spec:
  hosts:
    - nginx-test.k8s.ignota.cloud
  gateways:
    - istio-system/nginx-gateway-route53
  http:
    - match:
        - port: 80
        - port: 443
      route:
        - destination:
            host: nginx.nginx-test.svc.cluster.local
            port:
              number: 80
```
</details>

...which, as you've probably guessed, did the trick.

It still feels a little wonky that TLS traffic terminated at the `Gateway` continues upstream on the traditional HTTPS port. I wonder if it might be worth flagging in the docs, at the very least; or maybe adding a facility for `Gateway`s to pipe HTTP traffic through to 80.

This was absolutely a failure of my own reasoning and insight, and it's possible this isn't as much a contravention of most people's expectations as it was of mine. But it felt worth suggesting. Thanks for your work on Istio, and thanks for considering it.

**Describe alternatives you've considered**
Going slightly mad.

**Additional context**
♥️

**Comment by esnible** [comment]
UX is unable to triage this or set a priority.  Can someone from @istio/wg-networking-maintainers or @istio/wg-docs-maintainers evaluate this?

**Comment by frankbu** [comment]
@phyllisstein I think the source of your confusion is thinking that the Gateway does some routing. A gateway simply accepts requests on the the defined port(s), that's all. The VirtualService that's bound to it will specify the routing for the requests. You can specify in the Gateway to redirect HTTP to HTTPS, a common security pattern, but that's sending a 301 back to the caller, not forwarding to a new port.
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: nginx-gateway-route53
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - nginx-test/nginx-test.k8s.ignota.cloud
      tls:
        httpsRedirect: true # sends 301 redirect for http requests
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - nginx-test/nginx-test.k8s.ignota.cloud
      tls:
        mode: SIMPLE
        credentialName: nginx-test.k8s.ignota.cloud
```
This config says that the gateway accepts requests on port 80 and port 443. The calls on port 80 will return 301 to the caller. Requests on port 443 will terminate the TLS, that's all that this says.

A VirtualService, bound to this gateway, is now responsible for forwarding the request, which the Gateway accepted on port 443, to some port on some implementation service (in your case, port 80 of nginx.nginx-test.svc.cluster.local).

Normally you wouldn't need to match any ports in the VirtualService, unless there will be other internal requests on some other port, that you want to route somewhere else.
```
piVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-route53
  namespace: nginx-test
spec:
  hosts:
    - nginx-test.k8s.ignota.cloud
  gateways:
    - istio-system/nginx-gateway-route53
  http:
    - route:
        - destination:
            host: nginx.nginx-test.svc.cluster.local
            port:
              number: 80
```
I hope this helps clarify things.
