### ISSUE TITLE
nodeSelectorTerms cannot be applied via IstioOperator in 1.5.0 and 1.5.1

### ISSUE THREAD

**Issue by mike1808** [istio/istio#22594]
**Bug description**
Using IstioOperator configuration file and `istioctl manifest generate` command it is not possible to configure nodeSelectorTerms on any Istio component, as `istioctl` command returns an error, or doesn't apply the change.

**Expected behavior**
I should be able to configure `nodeSelectorTerms` on any component of Istio via IstioOperator.

**Steps to reproduce the bug**
Provide any IstioOperator configuration which has `nodeSelectorTerms`, e.g. for Pilot:

```yaml
 apiVersion: install.istio.io/v1alpha1
 kind: IstioOperator
 spec:
   profile: default
   components:
     pilot:
       k8s:
         affinity:
           nodeAffinity:
             requiredDuringSchedulingIgnoredDuringExecution:
               nodeSelectorTerms:
                 - matchExpressions:
                   - key: mykey
                     operator: In
                     values:
                      - myvalue
```

And apply it:

```sh
$ ~/istio-1.5.0/bin/istioctl manifest generate -f o.yml
proto: tag has too few fields: "-"
Error: validation errors (use --force to override):
validate path Components.Pilot.K8S.Affinity.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution, value: myvalue, expected ptr, got string
```

And the same with 1.5.1:

```sh
$ ~/istio-1.5.1/bin/istioctl manifest generate -f o.yml
Error: validation errors (use --force to override):
validate path Components.Pilot.K8S.Affinity.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution, value: myvalue, expected ptr, got string
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
No dependency on the cluster.
Affected `istioctl` versions: `1.5.0`, `1.5.1`

**How was Istio installed?**
Not installed

**Environment where bug was observed (cloud vendor, OS, etc)**
macOS, Ubuntu, Windows

N/A

**Comment by mike1808** [comment]
I want to add that it's possible to set `nodeSelectorTerms` via Helm options:

```yaml
 apiVersion: install.istio.io/v1alpha1
 kind: IstioOperator
 spec:
   profile: default
   values:
     pilot:
       nodeSelector:
         mykey: myvalue
```
