### ISSUE TITLE
Multi-cluster replicated control plane without gateway-connected clusters/ServiceEntry

### ISSUE THREAD

**Issue by bplotnick** [istio/istio#22605]
**Describe the feature request**
_I think this could probably be called "federated control plane" or something, but "federation" is so overloaded that we should probably come up with a better term._

**tl;dr:** I'm looking for a way to do multiple control planes but still have the same abstractions as in shared control plane - i.e. no `ServiceEntry`, no `.global` DNS pointing to an ingress gateway, etc.

I really like the [Shared Control Plane](https://istio.io/docs/setup/install/multicluster/shared/) model. Being able to stitch together clusters so that from the application networking perspective, cluster boundaries don't exist. However, this has the disadvantage of shared fate with cluster outages and/or having a single point of failure at the control plane.

To handle the resiliency, the recommended approach is to run multiple control planes. At the very least, people are running one-per-region. In some other cases, people are running one-per-az or one-per-cluster.

Unfortunately in the [Replicated Control Plane](https://istio.io/docs/setup/install/multicluster/gateways/) model, clusters are connected via gateways - meaning that the abstractions that are set up in the Shared Control Plane (`Service`, `VirtualService`, `Endpoint`) are not the same as those in the replicated control plane (`ServiceEntry`). Additionally, in a flat network, the ingress gateways for service-to-service communication are extraneous.

What I am proposing is having replicated control planes, but with "cross registration" of cluster resources (`Services`, `Endpoints`, whatever else Istio does within a cluster/control plane domain currently) from one cluster to another.

During a cluster failure or network partition, the only thing that will happen is that cross registration will stop, but since each control plane operates independently, the remaining control planes will still work fine.

You may now be asking about scaling concerns, but let's ignore it for now. The scaling problems will likely be the same as that of a single large control plane.

**Describe alternatives you've considered**
Admiral: It doesn't handle this I believe since it still deals with `ServiceEntry`s

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[X] Performance and Scalability
[X] Policies and Telemetry - Gateways hide the true endpoint that is being hit and so make the system less observable
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Comment by linsun** [comment]
@bplotnick thanks for raising this, we havesimilar thoughts as well - as you can tell from the discussion on the networking channel.  I think I agree with you with the notion of without service entries, I do think we need gateway connected clusters with auto passthrough for multi-network scenario, similar as what is in shared control plane multi network today.

I think we could possibly defer this (cross registration of istio resources) to a second phase as this can be driven from CI/CD system.

The first phase issue is how to configure Endpoint and services across clusters when each cluster has its own control plane.  @costinm mentioned by connecting to all apiservers, which I think it is doable.  let us say i have c1 in region east, and c2 in region south.   I can give c1 to access c2's API server via istio-reader-service-account as described in https://istio.io/docs/setup/install/multicluster/shared/#configure-cross-cluster-service-registries.  Similarly, I can give c2 access to c1's API server.  @costinm could you confirm that is what you are thinking?   

cc @ayj @howardjohn @frankbu @esnible @mbanikazemi @dcberg

**Comment by howardjohn** [comment]
I recall seeing some discussion about how this approach is not preferred due to the n^2 connections from all control planes to all api servers? From @nmittler I believe

**Comment by linsun** [comment]
Agree if you have many clusters and many API servers this can be lots of connections.  I don't think this would be used often, mainly across regions.  within region, you can use single control plane.  The prob we have is we don't want to rely on single control plane across regions.

**Comment by ayj** [comment]
In principle there are several dimensions to multi-cluster deployment models:

* shared vs. replicated (where do control planes run)
* service discovery (explicit ServiceEntry vs. directly peer kube-apiservers)
* number of networks

Not every combination is supported, primarily we don't test every combination. Here's what we document on istio.io:

1. Shared, single network, service/endpoints directly from peer kube-apiservers
2. Shared, multiple network, service/endpoints directly from peer kube-apiservers
3. Replicated, multiple network, service/endpoints explicitly from ServiceEntry

IIUC, @bplotnick is asking about the following model:

4. Replicated, single network, service/endpoints directly from peer kube-apiservers

This is similar to (1) and in fact easier to configure than (1). k8s services/namespaces still need to be replicated so DNS is configured correctly. 

```
# <... install intermediate certs with common root in each cluster ...>
istioctl manifest apply --context=cluster0 --set values.global.multiCluster.clusterName=cluster0
istioctl manifest apply --context=cluster1 --set values.global.multiCluster.clusterName=cluster0
istioctl x create-remote-secret --context=cluster0 --name=cluster0 | kubectl apply -f - --context=cluster1
istioctl x create-remote-secret --context=cluster1 --name=cluster1 | kubectl apply -f - --context=cluster0
```

Also worth noting that multi-network variant of replicated control plane using kube-apiserver is also possible. 

5. Replicated, multiple network, service/endpoints directly from peer kube-apiservers

This requires more steps to configure the networks. The basic idea is to follow  https://istio.io/docs/setup/install/multicluster/shared/#main-cluster to create _both_ cluster's profile. 

For example, cluster0's network config may look like:

```
    global:
      multiCluster:
        clusterName: cluster0
      network: network0
      meshNetworks:
        network0
          endpoints:
          # registry name for the cluster that this configuration is applied to must be "Kubernetes"
          - fromRegistry: Kubernetes
          gateways:
          - registry_service_name: istio-ingressgateway.istio-system.svc.cluster.local
            port: 443
        network1
          endpoints:
          # registry name must match cluster1's global.multiCluster.clusterName
          # and remote secret name
          - fromRegistry: cluster1       
          gateways:
          - registry_service_name: istio-ingressgateway.istio-system.svc.cluster.local
            port: 443
```

And cluster1's network config may look:

```
    global:
      multiCluster:
        clusterName: cluster1
      network: network1
      meshNetworks:
        network0
          endpoints:
          # registry name must match cluster0's global.multiCluster.clusterName
          # and remote secret name
          - fromRegistry: cluster0
          gateways:
          - registry_service_name: istio-ingressgateway.istio-system.svc.cluster.local
            port: 443
        network1
          endpoints:
          # registry name for the cluster that this configuration is applied to must be "Kubernetes"
          - fromRegistry: Kubernetes  
          gateways:
          - registry_service_name: istio-ingressgateway.istio-system.svc.cluster.local
            port: 443
```

Then, apply the custom profiles to each cluster and create the remote secrets.

# <... install intermediate certs with common root in each cluster ...>
istioctl manifest apply --context=cluster0 -f <cluster0-profile.yaml>
istioctl manifest apply --context=cluster1 -f <cluster1-profile.yaml>
istioctl x create-remote-secret --context=cluster0 --name=cluster0 | kubectl apply -f - --context=cluster1
istioctl x create-remote-secret --context=cluster1 --name=cluster1 | kubectl apply -f - --context=cluster0
```
