### ISSUE TITLE
Authorization rule on egress not working

### ISSUE THREAD

**Issue by padzikm** [istio/istio#22609]
Hi, how can configure authorization rules for egress gateway based on source principals? I've installed istio 1.5 with default profile with egress gateway enabled. I've set up sample app and configured istio as:
```
apiVersion: v1
kind: Namespace
metadata:
  name: team-blue
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-blue
  namespace: team-blue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: team-blue
  labels:
    app: busybox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      serviceAccountName: sa-blue
      containers:
      - name: busybux
        image: yauritux/busybox-curl
        command:
          - sleep
          - "3600"
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-red
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-red
  namespace: team-red
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: team-red
  labels:
    app: busybox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      serviceAccountName: sa-red
      containers:
      - name: busybux
        image: yauritux/busybox-curl
        command:
          - sleep
          - "3600"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: team-red
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: team-blue
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {}
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cnn
spec:
  hosts:
  - jsonplaceholder.typicode.com
  ports:
  - number: 80
    name: http-port
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
---
  apiVersion: networking.istio.io/v1alpha3
  kind: Gateway
  metadata:
    name: istio-egressgateway
  spec:
    selector:
      istio: egressgateway
    servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
      - jsonplaceholder.typicode.com
---
  apiVersion: networking.istio.io/v1alpha3
  kind: DestinationRule
  metadata:
    name: egressgateway-for-cnn
    namespace: team-blue
  spec:
    host: istio-egressgateway.istio-system.svc.cluster.local
    subsets:
    - name: cnn
---
  apiVersion: networking.istio.io/v1alpha3
  kind: DestinationRule
  metadata:
    name: egressgateway-for-cnn
    namespace: team-red
  spec:
    host: istio-egressgateway.istio-system.svc.cluster.local
    subsets:
    - name: cnn
---
  apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  metadata:
    name: direct-cnn-through-egress-gateway
  spec:
    hosts:
    - jsonplaceholder.typicode.com
    gateways:
    - istio-egressgateway
    - mesh
    http:
    - match:
      - gateways:
        - mesh
        port: 80
      route:
      - destination:
          host: istio-egressgateway.istio-system.svc.cluster.local
          subset: cnn
          port:
            number: 80
        weight: 100
    - match:
      - gateways:
        - istio-egressgateway
        port: 80
      route:
      - destination:
          host: jsonplaceholder.typicode.com
          port:
            number: 80
        weight: 100
---
apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
  name: "egress-teamblue"
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-egressgateway
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/team-blue/sa/sa-blue"]
---
``` 

I want to let only app from team-blue namespace to access egress, but when exec command inside team-blue's pod like curl -i http://jsonplaceholder.typicode.com I get error 403 forbidden server envoy. How can I configure that properly?

**Comment by padzikm** [comment]
any info?

**Comment by Laci21** [comment]
@padzikm, We have experienced the same issue when using Authorization rules with egress gateways.

We came up with an alternative solution using the [Sidecar](https://istio.io/docs/reference/config/networking/sidecar/) resource, open-sourced an [example repository](https://github.com/banzaicloud/istio-external-demo) which demonstrates a possible solution for this use case, and published a [blog post](https://banzaicloud.com/blog/istio-external-demo/) on the subject.

**Comment by howardjohn** [comment]
cc @yangminzhu

**Comment by dmarkey** [comment]
I also have this problem. Will this be possible in 1.7?

**Comment by yangminzhu** [comment]
I haven't tested the specific policies in this issue but it looks like the authorization policy is using the `principal` field on egress gateway which is not supported before 1.7.

This should be fixed by https://github.com/istio/istio/pull/25818 in 1.7.

**Comment by dmarkey** [comment]
Trying the example in the OP I get RBAC access denied from the team blue busybox with istio 1.7 RC1 when trying to curl jsonplaceholder.typicode.com.

**Comment by yangminzhu** [comment]
I tested and I think it's due to you haven't enabled mTLS between the busybox and egress-gateway, it was using plaintext and that's why it gets rejected with RBAC access denied because the source principal is not matched with the authorization policy.

Use the following policies to enable mTLS between workloads and egress-gateway:
```yaml
---
  apiVersion: networking.istio.io/v1alpha3
  kind: Gateway
  metadata:
    name: istio-egressgateway
    namespace: team-blue
  spec:
    selector:
      istio: egressgateway
    servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
      - "*"
      tls:
        mode: ISTIO_MUTUAL
---
  apiVersion: networking.istio.io/v1alpha3
  kind: DestinationRule
  metadata:
    name: egressgateway-for-cnn
    namespace: team-red
  spec:
    host: istio-egressgateway.istio-system.svc.cluster.local
    subsets:
    - name: cnn
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
---
  apiVersion: networking.istio.io/v1alpha3
  kind: DestinationRule
  metadata:
    name: egressgateway-for-cnn
    namespace: team-blue
  spec:
    host: istio-egressgateway.istio-system.svc.cluster.local
    subsets:
    - name: cnn
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
---
  apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  metadata:
    name: direct-cnn-through-egress-gateway
    namespace: team-blue
  spec:
    hosts:
    - jsonplaceholder.typicode.com
    gateways:
    - istio-egressgateway
    - mesh
    http:
    - match:
      - gateways:
        - mesh
        port: 80
      route:
      - destination:
          host: istio-egressgateway.istio-system.svc.cluster.local
          subset: cnn
          port:
            number: 443
        weight: 100
    - match:
      - gateways:
        - istio-egressgateway
        port: 443
      route:
      - destination:
          host: jsonplaceholder.typicode.com
          port:
            number: 80
        weight: 100
---
```

And you should find that only the busybox from namespace team-blue can have the access now.

@dmarkey  @padzikm Also note this will only work for `ISTIO_MUTUAL` mode (will not work for `MUTUAL` mode)
