### ISSUE TITLE
EnvoyFilter INBOUND_LISTENER not work

### ISSUE THREAD

**Issue by mstrYoda** [istio/istio#22618]
**Bug description**
When I apply the following yaml there is not any changes happen either request flow or proxy sidecar logs.

I also try to make it work the example given here : https://istio.io/docs/reference/config/networking/envoy-filter/#EnvoyFilter but I could not be successful.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: nginx-lua
  namespace: default
spec:
  workloadLabels:
    app: nginx
  filters:
  - listenerMatch:
      portNumber: 80
      listenerType: SIDECAR_INBOUND # will match with the inbound listener for nginx:80
      listenerProtocol: HTTP
    filterName: envoy.lua
    filterType: HTTP
    filterConfig:
      inlineCode: |
        function envoy_on_request(request_handle)
          request_handle:logWarn("envoy_on_request")
          request_handle:respond(
            {[":status"] = "403"},
            "nope")
        end
```

**Expected behavior**
I expect to see response 403 and log envoy_on_request.

**Steps to reproduce the bug**

`kubectl create deployment nginx --image nginx:alpine`

create VirtualService for nginx:

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nginx-route
  namespace: default
spec:
  gateways:
  - http-gateway.istio-system
  hosts:
  - nginx.test
  http:
  - match:
    - uri:
        prefix: /
    name: nginx-routes
    route:
    - destination:
        host: nginx
```

send request to istio gateway from any pod like below:

`curl -H 'host:nginx.test' <cluster-ip>:31380`

Response comes from nginx which is default nginx welcome page. But I expect to see 403 which sends from proxy via lua filter.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istio proxy log for version: Version 1.5.0-c3c353285578eb68b334fc8766746b754b6b3789-Clean

kubectl version: 
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:22:01Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

`istioctl manifest generate -f default_profile.yaml | sed -e 's/strategy: {}//g' | kubectl apply -f -`

```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  profile: minimal
  addonComponents:
    kiali:
      enabled: true
      k8s:
        replicaCount: 1
    prometheus:
      enabled: true
      k8s:
        replicaCount: 1
  components:
    egressGateways:
    - enabled: false
      name: istio-egressgateway
    ingressGateways:
    - enabled: true
      k8s:
        overlays:
          - apiVersion: extensions/v1beta1
            kind: Deployment
            name: istio-ingressgateway
            patches:
              - path: kind
                value: DaemonSet
              - path: spec.strategy
                value: {}
  values:
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: false
        meshExpansionPorts:
        - name: tcp-pilot-grpc-tls
          port: 15011
          targetPort: 15011
        - name: tcp-citadel-grpc-tls
          port: 8060
          targetPort: 8060
        - name: tcp-dns-tls
          port: 853
          targetPort: 853
        ports:
        - name: status-port
          port: 15020
          targetPort: 15020
        - name: http2
          port: 80
          targetPort: 80
          nodePort: 31380
        - name: https
          port: 443
          nodePort: 31390
        - name: kiali
          port: 15029
          targetPort: 15029
        - name: prometheus
          port: 15030
          targetPort: 15030
        - name: grafana
          port: 15031
          targetPort: 15031
        - name: tracing
          port: 15032
          targetPort: 15032
        - name: tls
          port: 15443
          targetPort: 15443
        type: NodePort
    pilot:
      autoscaleEnabled: true
      autoscaleMax: 10
      autoscaleMin: 5
      traceSampling: 0.1
      cpu:
        targetAverageUtilization: 50
      env:
        PILOT_PUSH_THROTTLE: 300
        PILOT_INITIAL_CONNECTION_WINDOW_SIZE: 65535
        PILOT_INITIAL_STREAM_WINDOW_SIZE: 65535
    kiali:
      createDemoSecret: true
    global:
      jwtPolicy: first-party-jwt
      proxy:
        clusterDomain: stage-2sfront-idc
        concurrency: 1
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
```

**Environment where bug was observed (cloud vendor, OS, etc)**
Barematel k8s.

**Comment by mstrYoda** [comment]
I found that it works when we have a service definition like below:

```

spec:
  ports:
  - name: http # this is the important part
  port: <port>
  targetPort: <targetPort>
```
