### ISSUE TITLE
All hosts defined in VirtualService have been leaked to route of 80 port

### ISSUE THREAD

**Issue by DanielQujun** [istio/istio#22621]
The story began with my coworker want to add an alternative domain for a kubernetes service. like details.bookinfo.com instead of details.bookinfo.svc.cluster.local, this would be more convenient and nature when the user is not familiar with kubernetes. 

first, We tried:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: details
spec:
  hosts:
  - details.bookinfo.com
  http:
  - route:
    - destination:
        host: details
        subset: v1
```
this did not work, and We found `details.bookinfo.com` was under the listener of 80 port. it is reasonable since this domain name was not registered in the cluster, istio might set 80 as default listener.

then We added details to hosts
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: details
spec:
  hosts:
  - details.bookinfo.com
  - details
  http:
  - route:
    - destination:
        host: details
        subset: v1
```
It succeeds this time. after add DNS record to  resolve `details.bookinfo.com` to the cluster IP of details service, We can `curl details.bookinfo.com:9080` directly.

But the strange thing comes out, we notice that there still is a virtualhost in 80 route for  `details.bookinfo.com`, moreover, we found all hosts added in virtualservice had a corresponding virtualhost there.

**My questions:**
1. If I want to add an alternative domain name for kubernetes service, is that a recommended way that just add it below the right service name? is this a feature or just a bonus?
2. If all hosts leak to 80 route that will be a big cost when there are many virtualservice rules., is this a bug?

[x ] Networking

**Expected behavior**

**Steps to reproduce the bug**

**Comment by howardjohn** [comment]
What if you add the port to the match and/or destination?

**Comment by DanielQujun** [comment]
add port to match works. The host won't leak to 80 route. I speculate that we might have done filter somewhere~

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: details
spec:
  hosts:
  - details.bookinfo.com
  - details
  http:
  - match:
    - port: 9080
    route:
    - destination:
        host: details
        port:
          number: 9080
        subset: v1
  port: 9080
```

```
$  istioctl pc route productpage-v1-79fd758f78-b9kz8.default --name 9080 -o json |jq ".[].virtualHosts[].name"  
"allow_any"
"details.bookinfo.com:9080"
"details.default.svc.cluster.local:9080"
"productpage.default.svc.cluster.local:9080"
"ratings.default.svc.cluster.local:9080"
"reviews.default.svc.cluster.local:9080"
"reviews.xx.svc.cluster.local:9080"


$  istioctl pc route productpage-v1-79fd758f78-b9kz8.default --name 80 -o json |jq ".[].virtualHosts[].name"    
"allow_any"
"istio-egressgateway.istio-system.svc.cluster.local:80"
"istio-ingressgateway.istio-system.svc.cluster.local:80"
"productpage.default.svc.cluster.local:80"
"ratings.default.svc.cluster.local:80"
"reviews.default.svc.cluster.local:80"
"tracing.istio-system.svc.cluster.local:80"
```
