### ISSUE TITLE
Istio Sidecar Allow External Service Calls but Restrict Service Mesh Calls

### ISSUE THREAD

**Issue by Henrike42** [istio/istio#22643]
Is it possible to configure istio envoy proxies/sidecars that service mesh internal egress is namespace restricted, but any external services can be invoked?

In principal I have installed istio with __outboundTrafficPolicy__ _ALLOW_ANY_ and the following sidecar for a specific namespace: 
````
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: default
  namespace: my-namespace
spec:
  egress:
  - hosts:
    - ./*
    - istio-system/*
`````

Unfortunately, the above sidecar definition seems to block calls to external services.
