### ISSUE TITLE
upstream connect error or disconnect/reset before headers. reset reason: connection failure

### ISSUE THREAD

**Issue by stealthiscode** [istio/istio#22651]
**Bug description**

On multiple freshly deployed 1.5.1 clusters, some or all requests respond with "upstream connect error or disconnect/reset before headers. reset reason: connection failure".  One cluster did that off and on for a while and then seemed to stabilize.  Another cluster never responded correctly.

Identical deployments work fine with an older 1.4.x cluster.

Possibly related log line in ingress pod:
```
transport: loopyWriter.run returning. connection error: desc = "transport is closing"
```

**Expected behavior**

Responses should return successfully.

On a fresh EKS cluster (1.15) us ap-southeat-1, install istio:

```
istioctl manifest apply \
    --set values.global.proxy.accessLogFile=/dev/stdout \
    --set values.grafana.enabled=true \
    --set values.kiali.enabled=true \
    --set values.kiali.dashboard.grafanaURL=http://grafana:3000 \
    --set values.kiali.dashboard.jaegerURL=http://jaeger-query:16686 \
    --set values.prometheusOperator.enabled=true \
    --set values.tracing.enabled=true \
    --set values.gateways.istio-ingressgateway.enabled=false
```

Apply additional changes:
```
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: production-public-ingress-cert
  namespace: istio-system
spec:
  secretName: production-public-ingress-cert
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: api.example.io
  dnsNames:
  - "api.example.io"
  - "dashboard.example.io"
  - "grafana.example.io"

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: istio-public-ingress
    istio: public-ingress
    release: istio
  name: istio-public-ingress
  namespace: istio-system
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istio-public-ingress

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: istio-public-ingress
    istio: public-ingress
    release: istio
  name: istio-public-ingress
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-public-ingress
      istio: public-ingress
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: istio-public-ingress
        istio: public-ingress
        release: istio
        service.istio.io/canonical-name: istio-public-ingress
        service.istio.io/canonical-revision: "1.5"
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
            weight: 2
          - preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - ppc64le
            weight: 2
          - preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - s390x
            weight: 2
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
      containers:
      - args:
        - proxy
        - router
        - --domain
        - $(POD_NAMESPACE).svc.cluster.local
        - --proxyLogLevel=warning
        - --proxyComponentLogLevel=misc:error
        - --log_output_level=default:info
        - --drainDuration
        - 45s
        - --parentShutdownDuration
        - 1m0s
        - --connectTimeout
        - 10s
        - --serviceCluster
        - istio-public-ingress
        - --zipkinAddress
        - zipkin.istio-system:9411
        - --proxyAdminPort
        - "15000"
        - --statusPort
        - "15020"
        - --controlPlaneAuthPolicy
        - NONE
        - --discoveryAddress
        - istio-pilot.istio-system.svc:15012
        - --trust-domain=cluster.local
        env:
        - name: JWT_POLICY
          value: third-party-jwt
        - name: PILOT_CERT_PROVIDER
          value: istiod
        - name: ISTIO_META_USER_SDS
          value: "true"
        - name: CA_ADDR
          value: istio-pilot.istio-system.svc:15012
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: ISTIO_META_WORKLOAD_NAME
          value: istio-public-ingress
        - name: ISTIO_META_OWNER
          value: kubernetes://apis/apps/v1/namespaces/istio-system/deployments/istio-public-ingress
        - name: ISTIO_META_MESH_ID
          value: cluster.local
        - name: ISTIO_AUTO_MTLS_ENABLED
          value: "true"
        - name: ISTIO_META_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: ISTIO_META_CONFIG_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ISTIO_META_ROUTER_MODE
          value: sni-dnat
        - name: ISTIO_META_CLUSTER_ID
          value: Kubernetes
        image: docker.io/istio/proxyv2:1.5.1
        imagePullPolicy: IfNotPresent
        name: istio-proxy
        ports:
        - containerPort: 15020
        - containerPort: 80
        - containerPort: 443
        - containerPort: 15029
        - containerPort: 15030
        - containerPort: 15031
        - containerPort: 15032
        - containerPort: 15443
        - containerPort: 15011
        - containerPort: 8060
        - containerPort: 853
        - containerPort: 15090
          name: http-envoy-prom
          protocol: TCP
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /healthz/ready
            port: 15020
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /var/run/secrets/istio
          name: istiod-ca-cert
        - mountPath: /var/run/secrets/tokens
          name: istio-token
          readOnly: true
        - mountPath: /var/run/ingress_gateway
          name: public-ingresssdsudspath
        - mountPath: /etc/istio/pod
          name: podinfo
        - mountPath: /etc/istio/public-ingress-certs
          name: public-ingress-certs
          readOnly: true
        - mountPath: /etc/istio/public-ingress-ca-certs
          name: public-ingress-ca-certs
          readOnly: true
      serviceAccountName: istio-public-ingress-service-account
      volumes:
      - configMap:
          name: istio-ca-root-cert
        name: istiod-ca-cert
      - downwardAPI:
          items:
          - fieldRef:
              fieldPath: metadata.labels
            path: labels
          - fieldRef:
              fieldPath: metadata.annotations
            path: annotations
        name: podinfo
      - emptyDir: {}
        name: public-ingresssdsudspath
      - name: istio-token
        projected:
          sources:
          - serviceAccountToken:
              audience: istio-ca
              expirationSeconds: 43200
              path: istio-token
      - name: public-ingress-certs
        secret:
          optional: true
          secretName: istio-public-ingress-certs
      - name: public-ingress-ca-certs
        secret:
          optional: true
          secretName: istio-public-ingress-ca-certs

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: public-ingress
  namespace: istio-system
  labels:
    release: istio
spec:
  selector:
    istio: public-ingress
  servers:
  - hosts:
    - '*.example.io'
    port:
      name: http
      number: 80
      protocol: HTTP
  - hosts:
    - '*.example.io'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: production-public-ingress-cert
      mode: SIMPLE
      privateKey: sds
      serverCertificate: sds
  - hosts:
    - '*.example.io'
    port:
      name: grpc
      number: 8081
      protocol: GRPC

---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: public-ingress
  namespace: istio-system
  labels:
    app: istio-public-ingress
    istio: public-ingress

    release: istio
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: istio-public-ingress
      istio: public-ingress

      release: istio

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: istio-public-ingress-sds
  namespace: istio-system
  labels:
    release: istio
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-public-ingress-sds
  namespace: istio-system
  labels:
    release: istio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: istio-public-ingress-sds
subjects:
- kind: ServiceAccount
  name: istio-public-ingress-service-account

---
apiVersion: v1
kind: Service
metadata:
  name: istio-public-ingress
  namespace: istio-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: api.example.io,dashboard.example.io,grafana.example.io
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    app: istio-public-ingress
    istio: public-ingress
    release: istio
spec:
  type: LoadBalancer
  selector:
    app: istio-public-ingress
    istio: public-ingress
  ports:
    -
      name: http2
      port: 80
      targetPort: 80
    -
      name: https
      port: 443
      targetPort: 443
    -
      name: grpc
      port: 8081

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-public-ingress-service-account
  namespace: istio-system
  labels:
    app: istio-public-ingress
    istio: public-ingress
    release: istio```

Install any service with a sidecar and curl the URL.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ istioctl version 
client version: 1.5.1
public-ingress version: 
pilot version: 1.5.1
data plane version: 1.5.1 (2 proxies)
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-26T01:12:54Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}```

**How was Istio installed?**

istioctl.  See above.

**Environment where bug was observed (cloud vendor, OS, etc)**

Amazon EKS, ap-southeast-1

**Comment by harpratap** [comment]
Does you applicatio deployment have containerPorts defined?

**Comment by stealthiscode** [comment]
Yes.  Example deployment:

```
---
# Source: accounts/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "accounts"
  labels:
    helm.sh/chart: accounts-0.7.0
    app.kubernetes.io/name: accounts
    app.kubernetes.io/instance: accounts
    app.kubernetes.io/version: "0.9.1"
    app.kubernetes.io/managed-by: Helm
---
# Source: accounts/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: accounts
  labels:
    helm.sh/chart: accounts-0.7.0
    app.kubernetes.io/name: accounts
    app.kubernetes.io/instance: accounts
    app.kubernetes.io/version: "0.9.1"
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - port: 8086
      name: "http"
    - port: 8186
      name: "grpc"
  selector:
    app.kubernetes.io/name: accounts
    app.kubernetes.io/instance: accounts
---
# Source: accounts/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "accounts"
  labels:
    helm.sh/chart: accounts-0.7.0
    app.kubernetes.io/name: accounts
    app.kubernetes.io/instance: accounts
    app.kubernetes.io/version: "0.9.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: accounts
      app.kubernetes.io/instance: accounts
  template:
    metadata:
      labels:
        app.kubernetes.io/name: accounts
        app.kubernetes.io/instance: accounts
      annotations:
        release.timestamp: "20200402082938"
        prometheus.io/path: /metrics
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: "accounts"
      securityContext:
        {}
      containers:
        - name: accounts
          securityContext:
            {}
          image: "REDACTED.dkr.ecr.ap-southeast-1.amazonaws.com/accounts:0.9.1-master"
          imagePullPolicy: "Always"
          ports:
            - name: "http"
              containerPort: 8086
              protocol: TCP
            - name: "grpc"
              containerPort: 8186
              protocol: TCP
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                key: aws-access-key-id
                name: aws-access-key-id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: aws-secret-access-key
                name: aws-secret-access-key
          - name: CF_SIGNED_COOKIE_KEY_ID
            valueFrom:
              secretKeyRef:
                key: cf-signed-cookie-key-id
                name: cf-signed-cookie-key-id
          - name: CF_SIGNED_COOKIE_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                key: cf-signed-cookie-private-key
                name: cf-signed-cookie-private-key
          - name: JWT_PRIVATE_ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                key: jwt-private-encryption-key
                name: jwt-private-encryption-key
          - name: JWT_PRIVATE_SIGNING_KEY
            valueFrom:
              secretKeyRef:
                key: jwt-private-signing-key
                name: jwt-private-signing-key
          - name: JWT_PUBLIC_ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                key: jwt-public-encryption-key
                name: accounts-jwt-public-encryption-key
          - name: JWT_PUBLIC_SIGNING_KEY
            valueFrom:
              secretKeyRef:
                key: jwt-public-signing-key
                name: jwt-public-signing-key
          - name: JWT_TOKEN_DURATION_SECONDS
            valueFrom:
              secretKeyRef:
                key: jwt-token-duration-seconds
                name: accounts-jwt-token-duration-seconds
          - name: KAFKA_BROKER_LIST
            valueFrom:
              secretKeyRef:
                key: kafka-broker-list
                name: kafka-broker-list
          - name: KAFKA_IMPLEMENTATION
            valueFrom:
              secretKeyRef:
                key: kafka-implementation
                name: kafka-implementation
          - name: KAFKA_KEY
            valueFrom:
              secretKeyRef:
                key: kafka-key
                name: kafka-key
          - name: KAFKA_SECRET
            valueFrom:
              secretKeyRef:
                key: kafka-secret
                name: kafka-secret
          - name: KAFKA_VERSION
            valueFrom:
              secretKeyRef:
                key: kafka-version
                name: kafka-version
          - name: MONGO_DB_URL
            valueFrom:
              secretKeyRef:
                key: mongo-db-url
                name: mongo-db-url
          resources:
            {}
---
# Source: accounts/templates/virtualservice.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "accounts"
spec:
  hosts:
  - "*"
  gateways:
  - "istio-system/public-ingress"
  http:
  - match:
    - uri:
        prefix: "/api/v1/ams"
    route:
    - destination:
        port:
          number: 8086
        host: "accounts"
```
