### ISSUE TITLE
Cannot catch service tracing exported by ingress

### ISSUE THREAD

**Issue by packyzbq** [istio/istio#22666]
**Bug description**
Hi, I've got a problem with service tracing. I deploy jaeger in my cluster, which has two pod: jaeger-collector and jaeger-query. The jaeger-collector export port 9411 as the zipkin port. 
```
[root@k8s1 templates]# kubectl get po -n jaeger
NAME                               READY   STATUS    RESTARTS   AGE
jaeger-collector-b9bf6d75b-f5542   1/1     Running   0          35m
jaeger-query-5fd6c9dcff-xrg6g      1/1     Running   0          35m
[root@k8s1 templates]# kubectl get svc -n jaeger
NAME               TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                        AGE
jaeger-collector   ClusterIP      10.233.41.235   <none>        14267/TCP,14268/TCP,9411/TCP   2d20h
jaeger-query       LoadBalancer   10.233.42.210   <pending>     80:38559/TCP                   2d20h
zipkin             ClusterIP      10.233.26.14    <none>        9411/TCP                       2d20h
```
 The istio tracing address is `zipkin.jaeger:9411` and tracing.Sampling is 100. Then I deploy bookinfo app and create an ingress rule to export bookinfo app. However I cannot find any trace . The ingress is as below:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/upstream-vhost: productpage.bookinfo.svc.cluster.local
  name: gateway
  namespace: bookinfo
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: productpage
          servicePort: 9080
        path: /
```
When I use istio-gateway to expose bookinfo, everything is ok. 

By the way, all istio component is:
```
[root@k8s1 templates]# kubectl get po -n istio-system
NAME                                    READY   STATUS    RESTARTS   AGE
grafana-556b649566-72sdh                1/1     Running   0          2d20h
istio-ingressgateway-764646fbbb-7xb2x   1/1     Running   0          65m
istiod-56874f789c-bkw8q                 1/1     Running   0          50m
kiali-6d54b8ccbc-lpfs4                  1/1     Running   0          149m
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio version: 1.5.0

**How was Istio installed?**
I modify the default profile(`istio-1.5.0/install/kubernetes/operator/profiles/default.yaml`), then `istioctl manifest apply -f  default.yaml`

**Environment where bug was observed (cloud vendor, OS, etc)**
CentOS 7.3
