### ISSUE TITLE
Is it possible to generate jaeger-query Service description using IstioOperator?

### ISSUE THREAD

**Issue by DickChesterwood** [istio/istio#22683]
**Bug description**

Trying to generate the yaml to open up the JaegerUI as a NodePort using IstioOperator. This may be operator error but it doesn't appear to be possible using the same approach as Kiali and Grafana.

**Expected behavior**

We can generate the yaml to tune a Service for the Kiali addonComponent:

```
    kiali:
      enabled: true
      k8s:
        replicaCount: 1
        service:
          type: NodePort
          ports:
          - port: 20001
            nodePort: 30000
```

Doing the same with the tracing: addonComponent has no effect on either the "tracing" Service or the "jaeger-query" Service (the latter would be the expected behaviour).

**Steps to reproduce the bug**

Use the following in the IstioOperator yaml:

```
    tracing:
      enabled: true
      k8s:
        service:
          type: NodePort
          ports:
          - port: 16686
            nodePort: 31001
```

```
istioctl manifest generate -f .\raw_demo_profile.yaml --set values.global.jwtPolicy=first-party-jwt > .\istio-configuration.yaml   
```

istio-configuration.yaml still has an unmodified ClusterIP configuration for the jaeger-query Service.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
client version: 1.5.1
control plane version: 1.5.0
data plane version: 1.5.0 (4 proxies)
```
**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
minikube Win 10 Pro over VirtualBox
