### ISSUE TITLE
Invalid config indentation for sidecarInjectorWebhook

### ISSUE THREAD

**Issue by bzurkowski** [istio/istio#22699]
**Bug description**

Given sidecar intjector webhook spec in `IstioOperator` manifes:

```yaml
sidecarInjectorWebhook:
  neverInjectSelector:
  - matchExpressions:
    - key: lbaas
      operator: In
      values:
      - lbaas
```

The installer generates config map with invalid indentation for `neverInjectSelector` and `alwaysInjectSelector`:

```yaml
apiVersion: v1                                                                                                                                                                                                                                                        
data:                                                                                                                                                                                                                                                                 
  config: |-                                                                                                                                                                                                                                                          
    policy: enabled                                                                                                                                                                                                                                                   
    alwaysInjectSelector:                                                                                                                                                                                                                                             
            []                                                                                                                                                                                                                                                        
    neverInjectSelector:                                                                                                                                                                                                                                              
            - matchExpressions:                                                                                                                                                                                                                                       
        - key: lbaas                                                                                                                                                                                                                                                  
          operator: In                                                                                                                                                                                                                                                
          values:                                                                                                                                                                                                                                                     
          - lbaas                                                                                                                                                                                                                                                     
```

As a result, the `istiod` fails to start up:

```
2020-04-03T14:09:08.000250Z     warn    Failed to parse injectFile policy: enabled
alwaysInjectSelector:                                                                          
        []                                                  
neverInjectSelector:                                                                       
        - matchExpressions:                             
    - key: lbaas                                                                          
      operator: In                                                   
      values:                                                                                        
      - lbaas                                   
injectedAnnotations:                                                                                                
Error: failed to create discovery service: sidecar injector: failed to create injection webhook: error converting YAML to JSON: yaml: line 5: did not find expected key
```
**Affected product area**

[x] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

Config map for sidecar injector webhook is generated correctly and istiod starts successfully.

**Steps to reproduce the bug**

Install Istio using `neverInjectSelector` field.

**Version**

Istio:

```
client version: 1.5.1
control plane version: 1.5.1
data plane version: 1.5.1 (4 proxies)
```

Kubernetes:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

Using istioctl command.

**Environment where bug was observed (cloud vendor, OS, etc)**

Bare metal, RHEL 7.4, Kubernetes 1.16, Istio 1.5.1
