### ISSUE TITLE
istioctl does not set gateway name for multiple gateways

### ISSUE THREAD

**Issue by qwazerty** [istio/istio#22703]
**Bug description**

When deploying multiple gateways, istio does set the names for deployments and service (thanks to #21938 and #22138) but does not set the name for Gateway.

**Expected behavior**

```
# cat test-gateways.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: empty
  components:
    ingressGateways:
      - name: istio-ingress-1
        enabled: true
      - name: istio-ingress-2
        enabled: true
```

```
# istioctl manifest generate -f test-gateways.yaml | grep "^kind: Gateway" -A6
kind: Gateway
metadata:
  name: istio-ingress-1
  namespace: istio-system
  labels:
    release: istio
spec:
--
kind: Gateway
metadata:
  name: istio-ingress-2
  namespace: istio-system
  labels:
    release: istio
spec:
```

**Steps to reproduce the bug**

```
# istioctl manifest generate -f test-gateways.yaml | grep "^kind: Gateway" -A6
kind: Gateway
metadata:
  name: ingressgateway
  namespace: istio-system
  labels:
    release: istio
spec:
--
kind: Gateway
metadata:
  name: ingressgateway
  namespace: istio-system
  labels:
    release: istio
spec:
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
# istioctl version --remote
client version: 1.5.1
control plane version: 1.5.1
data plane version: 1.5.1 (9 proxies)

# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux
/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"c83d931fb9bece427bc63a02349755e0f8696d3e", GitTreeState:"clean", BuildDate:"2020-01-31T20:09:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linu
x/amd64"}
```
