### ISSUE TITLE
istioctl: ports are null when externalTrafficPolicy is specified

### ISSUE THREAD

**Issue by mjhuber** [istio/istio#22710]
when using istioctl, if i specify the ingressgateway's traffic policy, the generated manifest for the service lists the ports as null.  This generates the error `The Service "istio-ingressgateway" is invalid: spec.ports: Required value (repeated 1 times)` when applying the manifest.

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
      k8s:
        service:
          externalTrafficPolicy: Local
```

```
apiVersion: v1
kind: Service
metadata:
  annotations: null
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
  externalTrafficPolicy: Local
  ports: null
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  type: LoadBalancer
```

```
❯ istioctl version
client version: 1.5.1
control plane version: 1.5.1
data plane version: 1.5.1 (3 proxies)
```

**Comment by morvencao** [comment]
Istio operator is using strategic merge patch for k8s overlay, however, `ExternalTrafficPolicy ` in service spec looks like doesn't support strategic merge patch yet, see: https://github.com/kubernetes/api/blob/master/core/v1/types.go#L960 

Currently if you would like specify `externalTrafficPolicy` for ingress service, you can do it in values part.

**Comment by morvencao** [comment]
Another workaround is use k8s overlay for specifies resource:


```
cat << EOF > k8s-service-overlay.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
      k8s:
        overlays:
        - kind: Service
          name: istio-ingressgateway
          patches:
          - path: spec.externalTrafficPolicy
            value: "Local"
EOF
```

```
istioctl manifest generate -f k8s-service-overlay.yaml
```

**Comment by mjhuber** [comment]
suggested workaround is working. thanks for the help

**Comment by mike-treadway** [comment]
I just upgraded from 1.50 to 1.5.1 and I'm seeing this issue. I don't have any overlays defined in my operator file. I tried setting the externalTrafficPolicy explicitly to "Cluster" and it has the same effect. I can't seem to figure out why the generated output has `ports: null` for the ingress service.

Any idea?

**Comment by mike-treadway** [comment]
OK. I got it working by changing this:

```yaml
    ingressGateways:
      - enabled: true
        k8s:
          service:
            loadBalancerIP: 169.59.xxx.xxx
```

to

```yaml
    ingressGateways:
      - enabled: true
        k8s:
          overlays:
            - kind: Service
              name: istio-ingressgateway
              patches:
                - path: spec.loadBalancerIP
                  value: "169.59.xxx.xxx"
```

Basically just moved the load balancer IP to an overlay. I'm running IKS v1.15.11 if that helps.
