### ISSUE TITLE
istio 1.5.1  prometheus  NodePort can't be set  as values.prometheus.service.type=NodePort using istioctl

### ISSUE THREAD

**Issue by prageethw** [istio/istio#22726]
**Bug description**
tried to set NodePort to expose Prometheus in Minikube, when I ran below command it gives me error as specified.

```
istioctl manifest generate --set profile=demo \
                             --set values.grafana.service.type=NodePort \
                             --set values.kiali.service.type=NodePort \
                             --set values.tracing.service.type=NodePort \
                             --set values.prometheus.service.type=NodePort>istio-demo-profile.yam
```
produces below,
```
Error: validation errors (use --force to override):
unknown field "type" in v1alpha1.PrometheusServiceConfig

```
istiospec says service should have a type associated with service object?

`https://istio.io/docs/reference/config/istio.operator.v1alpha1/#ServiceSpec`

**Expected behavior**

I should be able to expose  Prometheus as node port using operator api as below

```
istioctl manifest generate --set profile=demo \
                            --set values.grafana.service.type=NodePort \
                            --set values.kiali.service.type=NodePort \
                            --set values.tracing.service.type=NodePort \
                            --set values.prometheus.service.type=NodePort>istio-demo-profile.yaml 
```

**Steps to reproduce the bug**

just run the above command.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
client version: 1.5.1
control plane version: 1.5.1
data plane version: 1.5.1 (3 proxies)
```

**How was Istio installed?**
istioctl manifest apply --set profile=demo

**Environment where bug was observed (cloud vendor, OS, etc)**
across everywhere

**Comment by morvencao** [comment]
It is recommended to use `k8sOverlay` to set service spec instead of old values.
Try this:
```
cat << EOF > addon-services.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  addonComponents:
    kiali:
      enabled: true
      k8s:
        service:
          type: NodePort
    tracing:
      enabled: true
      k8s:
        service:
          type: NodePort
    grafana:
      enabled: true
      k8s:
        service:
          type: NodePort
    prometheus:
      enabled: true
      k8s:
        service:
          type: NodePort
EOF
```

Then create the istio manifests with `addon-services.yaml`:
```
istioctl manifest generate --set profile=demo -f addon-services.yaml > istio-demo-profile.yaml
```
