### ISSUE TITLE
Istio tracing fails when psp is enabled

### ISSUE THREAD

**Issue by r-catania** [istio/istio#22759]
**Bug description**
When installing istio tracing using istio operator with pod security policies enabled the installation fails. 
`Error: container has runAsNonRoot and image will run as root`
There is no way to specify a service account for the deployment of istio tracing in order to tie the service account to a a PSP (pod security policy).

I tried adding an overlay to the istio operator such as 

    tracing:
      enabled: true
      k8s:
        overlays:
        - kind: Deployment
          name: istio-tracing
          patches:
          - path: spec.template.spec.serviceAccountName
            value: "istio-tracing-service-account"  

but the pod seems to be missing the patch specified above

[ ] Configuration Infrastructure
[ ] Docs
[ * ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

[ ] Multi Cluster
[ * ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
There should be a way to tie the deployment of istio-tracing to a service account in order to utilize a PSP.

**Steps to reproduce the bug**
Enable PSP 
Deploy istio with tracing enabled.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
`client version: 1.5.1
control plane version: 1.5.1
data plane version: none`

`Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}`

**How was Istio installed?**
Via istio operator

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-controlplane
spec:
  addonComponents:
    grafana:
      enabled: true
    kiali:
      enabled: true
    prometheus:
      enabled: false
    tracing:
      enabled: true
    prometheusOperator:
      enabled: true
      createPrometheusResource: false
  components:
    citadel:
      enabled: true
    cni:
      enabled: true
      namespace: kube-system
    galley:
      enabled: true
    sidecarInjector:
      enabled: true
  tag: 1.5.1
  values:
    prometheusOperator:
      enabled: true
      createPrometheusResource: false
    cni:
        logLevel: info
        excludeNamespaces:
         - istio-system
         - kube-system
    gateways:
      istio-ingressgateway:
        loadBalancerIP: 172.30.254.100
        sds:
          enabled: true
    grafana:
      persist: true
      security:
        enabled: true
        secretName: grafana-admin
        usernameKey: admin-user
        passphraseKey: admin-password
    global:
      k8sIngress:
        enableHttps: true
        enabled: true
        gatewayName: ingressgateway
      sds:
        enabled: true
```

**Environment where bug was observed (cloud vendor, OS, etc)**
Ubuntu 18.04 
Rke
