### ISSUE TITLE
Virtual Service ignore host field for TCP

### ISSUE THREAD

**Issue by tcondeixa** [istio/istio#22767]
I already updated istio to 1.5.1 but whenever I define a virtual service TCP the host is ignored, and all traffic with that port is forwarded by envoy to the same destination. I was trying to use Istio for TCP proxy for RDS databases to keep some legacy systems working, without using haproxy or nginx in EC2. All traffic from my apps to destinations on port 5432 or 5555 are caught by the virtualservice.

[x ] Networking

I was expecting that host is taking into account, so only TCP traffic for that port and that host will be forwarded from what is defined in VirtualService.

VirtualService defined:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: haproxy-testing
  namespace: istio-system
spec:
  hosts:
    - testing.preprod.zenjob.io
  gateways:
    - internal-gw.istio-system.svc.cluster.local
  tcp:
    - match:
      - port: 5432
      route:
        - destination:
            host: mydb.cluster-cgvvk1hmmejp.eu-central-1.rds.amazonaws.com
            port:
              number: 5432
```

on my Istio ingress gateway I'm allowing multiple TCP ports:
```  
. . . . 
    - hosts:
    - '*.preprod.zenjob.io'
    port:
      name: db5432-istio-internal-gateway
      number: 5432
      protocol: TCP
  - hosts:
    - '*.preprod.zenjob.io'
    port:
      name: db5555-istio-internal-gateway
      number: 5555
      protocol: TCP
. . . .
```
Thank you

**Comment by hzxuzhonghu** [comment]
It should match port 5432 before routing to `mydb.cluster-cgvvk1hmmejp.eu-central-1.rds.amazonaws.com:5432`. The host `testing.preprod.zenjob.io` here is not used.

**Comment by tcondeixa** [comment]
> It should match port 5432 before routing to `mydb.cluster-cgvvk1hmmejp.eu-central-1.rds.amazonaws.com:5432`. The host `testing.preprod.zenjob.io` here is not used.

I have more apps communicating with other databases on port 5432, how can I enforce only "testing.preprod.zenjob.io" 5432 to be forwarded to "mydb.cluster-cgvvk1hmmejp.eu-central-1.rds.amazonaws.com"?

**Comment by hzxuzhonghu** [comment]
Your above VS is for the ingress-gateway, all packet comes in with podIP:5432, how can envoy know which host it wants to connect to?

**Comment by tcondeixa** [comment]
where is the host changed to podIP instead of the original one? does it help if I define the full address on ingress gateway host? Do you have solution so I can have a TCP proxy based on ports using Istio with AWS nlb?

**Comment by howardjohn** [comment]
The IP requested is the IP of the gateway not of the pod. The only info we have when the request gets to the gateway that we can use for tcp routing is the port

**Comment by keatz55** [comment]
I'm experiencing the same issue with istio 1.5.1 via the following config:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: vms-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 1935
        name: rtmp
        protocol: TCP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vms-rtmp
spec:
  hosts:
    - domain1.test.local
  gateways:
    - vms-gateway
  tcp:
    - match:
        - port: 1935
      route:
        - destination:
            host: nginx-rtmp-server
            port:
              number: 1935
```
Does anybody know of a workaround?

**Comment by keatz55** [comment]
I tried limiting traffic at the gateway, but unfortunately ALL tcp traffic is being forwarded to the service regardless of hosts:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: nginx-rtmp-server-1-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 1935
        name: rtmp
        protocol: TCP
      hosts:
        - subdomain1.test.local
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-rtmp-server-1-virtual-service
spec:
  hosts:
    - subdomain1.test.local
  gateways:
    - nginx-rtmp-server-1-gateway
  tcp:
    - route:
        - destination:
            host: nginx-rtmp-server-1
            port:
              number: 1935

```
