### ISSUE TITLE
istio redis write: broken pipe

### ISSUE THREAD

**Issue by fujianan** [istio/istio#22770]
istio versin: 1.15.0
k8s version: 1.17.4
redis is deployed in k8s cluster and the namespace  has been automatically injected
This is my redis service yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: redis
    env: production
  name: redis
spec:
  clusterIP: 10.254.32.106
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
    env: production
  sessionAffinity: None
  type: ClusterIP

But sometime other application connect redis error:  
{"level":"error","ts":1586244833.7956085,"msg":"CaptchaStore.Get get key from redis failed","error":"write tcp 172.30.0.219:52890->10.254.32.106:6379: write: broken pipe",
How should I resolve this  problem?
Thanks

**Comment by hzxuzhonghu** [comment]
Do you enable `PILOT_ENABLE_REDIS_FILTER` and met this failure?

**Comment by fujianan** [comment]
> Do you enable `PILOT_ENABLE_REDIS_FILTER` and met this failure?

No,I didn't configure this

**Comment by EthanChouTW** [comment]
+1 met the same issue on external traffic connecting to CloudSQL
```
write tcp {internal location}->{cloud sql location}: write: broken pip
```

**Comment by fujianan** [comment]
> +1 met the same issue on external traffic connecting to CloudSQL
> 
> ```
> write tcp {internal location}->{cloud sql location}: write: broken pip
> ```

hello,Do you solve this problem?

**Comment by hzxuzhonghu** [comment]
anyone please show the configdump of both the client and server side

**Comment by fujianan** [comment]
> anyone please show the configdump of both the client and server side
redis-configmap.yaml
```yaml
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: redis
data:
  redis.conf: |-
    bind 0.0.0.0
    protected-mode no
    port 6379
    tcp-backlog 2048
    timeout 0
    tcp-keepalive 300
    pidfile  /var/run/redis.pid
    loglevel notice
    logfile "/var/log/redis.log"
    databases 16
    save 900 1
    save 300 10
    save 60 10000
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    dir /data
```
redis-service.yaml
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: triones
  labels:
    department: triones
    app: redis
    env: production
  # annotations:
  #   prometheus.io/path: "internal/metrics"
  #   prometheus.io/port: "7010"
  #   prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - port: 6379
      #targetPort: 6379
      #name: redis-test
  selector:
    department: triones
    app: redis
    env: production
```
redis-deployment.yaml
```yaml
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis
  labels:
    app: redis
    env: production
  annotations:
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: redis
        env: production
    spec:
      imagePullSecrets:
        - name: docker-secret
      dnsConfig:
        options:
          - name: ndots
            value: "2"
          - name: timeout
            value: "1"
      initContainers:
        - name: set-sysctl
          image: redis:3.2.4-alpine
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - echo 65535 > /proc/sys/net/core/somaxconn
          securityContext:
            privileged: true
      containers:
        - name: redis
          image: redis:3.2.4-alpine
          imagePullPolicy: IfNotPresent
          command: ["/usr/local/bin/redis-server"]
          args:
            - /etc/redis/redis.conf
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: config-volume
              mountPath: /etc/redis
            - name: data-volume
              mountPath: /data
            - name: log-volume
              mountPath: /var/log
      volumes:
        - name: config-volume
          configMap:
            name: redis
        - name: data-volume
          hostPath:
            path: /data/data/redis
            type: Directory
        - name: log-volume
          hostPath:
            path: /data/logs/redis
            type: Directory
```

client service configuration:
```shell
    [redis]
    addr = "redis"
    password = ""
    poolSize = 100
    db = 4
    timeout = "0.5s"
```

And this problem occurs sporadically

**Comment by fujianan** [comment]
> anyone please show the configdump of both the client and server side

Do you need more information? If necessary, please contact in time

**Comment by hzxuzhonghu** [comment]
@fujianan I mean xds configdump from envoy

**Comment by fujianan** [comment]
> @fujianan I mean xds configdump from envoy

@hzxuzhonghu Hi,What command should I execute to get con
figdump?Thanks

**Comment by hzxuzhonghu** [comment]
https://istio.io/docs/ops/diagnostic-tools/proxy-cmd/

**Comment by fujianan** [comment]
@hzxuzhonghu 
redis server
istioctl proxy-config listeners redis-6676857d78-nvc7s -o json
[redis-listener.json.zip](https://github.com/istio/istio/files/4538466/redis-listener.json.zip)

**Comment by nigeltiany** [comment]
I also tried this configuration but it did not help
```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: cluster-internal-services
spec:
  host: cluster.internal.services
  trafficPolicy:
    connectionPool:
      tcp:
        tcpKeepalive:
          time: 7200s
          interval: 75s
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: cluster-internal-services
spec:
  hosts:
    - cluster.internal.services
  addresses:
    - 10.0.0.0/8
  ports:
    - number: 5432
      name: postgres
      protocol: TCP
    - number: 6379
      name: redis
      protocol: TCP
  location: MESH_EXTERNAL
```
