### ISSUE TITLE
istioctl 1.5.1 generate incorrect pilot plugins configurations

### ISSUE THREAD

**Issue by jenningsloy318** [istio/istio#22796]
**Bug description**
I used following configure to configure pilot plugins, pass the plugin as list 
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  values:
    pilot:
      plugins: 
      - aa
      - bb
 ```

but always get error when generating manifest 
```
istioctl manifest  generate --verbose --log_output_level=default:debug --force  \
    -f istioctl-values.yaml 

json: cannot unmarshal string into Go value of type map[string]json.RawMessage
Error: generated config failed semantic validation: json: cannot unmarshal string into Go value of type map[string]json.RawMessage
```

but if we set the the plugin as maps, manifest will genterated without errors.

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  values:
    pilot:
      plugins: 
      - 0: aa
      - 1: bb
 ```
and ther result deployment of istiod is :
```
      containers:
      - args:
        - discovery
        - --monitoringAddr=:15014
        - --log_output_level=default:info
        - --domain
        - cluster.local
        - --secureGrpcAddr=:15011
        - --trust-domain=cluster.local
        - --plugins=[map[0:aa] map[1:bb]]
        - --keepaliveMaxServerConnectionAge
        - 30m
        - --disable-install-crds=true
```
which is incorrect, as `discovery` only accept `<stringSlice> ,example [authn,authz,health,mixer]`  but not `[map[0:aa] map[1:bb]]`

**Affected product area (please put an X in all that apply)**

[x] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[x] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**

```
istioctl manifest  generate --verbose --log_output_level=default:debug --force  \
    -f istioctl-values.yaml 
```
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istioctl: 1.5.1

**How was Istio installed?**
not installed yet 

**Environment where bug was observed (cloud vendor, OS, etc)**
runing istioctl on CentOS 7
