### ISSUE TITLE
istioctl 1.5.1 can't create correct pilot plugins configuration

### ISSUE THREAD

**Issue by jenningsloy318** [istio/istio#22804]
**Bug description**
I used following configure to configure install istio with additional pilot plugins, pass the plugins as slice(list)
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  values:
    pilot:
      plugins: 
      - aa
      - bb
 ```
but always get error when generating manifest 
```
istioctl manifest  generate --verbose --log_output_level=default:debug    -f istioctl-values.yaml 
json: cannot unmarshal string into Go value of type map[string]json.RawMessage
Error: generated config failed semantic validation: json: cannot unmarshal string into Go value of type map[string]json.RawMessage
```
seems ask me to pass a map into it, so if I set the the plugins as maps, manifest will be genterated without errors.
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  values:
    pilot:
      plugins: 
      - 0: aa
      - 1: bb
 ```
and ther result deployment of istiod is :
```
      containers:
      - args:
        - discovery
        - --monitoringAddr=:15014
        - --log_output_level=default:info
        - --domain
        - cluster.local
        - --secureGrpcAddr=:15011
        - --trust-domain=cluster.local
        - --plugins=[map[0:aa] map[1:bb]]
        - --keepaliveMaxServerConnectionAge
        - 30m
        - --disable-install-crds=true
```
which is incorrect,  according to [discovery document](https://istio.io/docs/reference/commands/pilot-discovery/)  only accept `<stringSlice> , [authn,authz,health,mixer]`  but not map list  `[map[0:aa] map[1:bb]]`

**Expected behavior**

istioctl generate correct conf

**Steps to reproduce the bug**

```
istioctl manifest  generate --verbose --log_output_level=default:debug    -f istioctl-values.yaml 
```
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istioctl: 1.5.1

**How was Istio installed?**
not installed yet 

**Environment where bug was observed (cloud vendor, OS, etc)**
runing istioctl on CentOS 7
