### ISSUE TITLE
TLS origination upstream_reset_before_response_started

### ISSUE THREAD

**Issue by Kyslik** [istio/istio#22802]
**Bug description**

TLS origination with mode `SIMPLE` is returning 503 instead of 200. I followed the [egress-tls-origination task](https://archive.istio.io/v1.3/docs/tasks/traffic-management/egress/egress-tls-origination/) and ~ changed the host I want to test it on and the result is:

```sh
[ root@tmp-1:/ ]$ curl -I -v http://www.confluent.io
> HEAD / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: www.confluent.io
> Accept: */*
>
< HTTP/1.1 503 Service Unavailable
HTTP/1.1 503 Service Unavailable
< content-length: 91
content-length: 91
< content-type: text/plain
content-type: text/plain
< date: Wed, 08 Apr 2020 08:42:36 GMT
date: Wed, 08 Apr 2020 08:42:36 GMT
< server: envoy
server: envoy
```

Note that above request takes 30s to _finish_. If I set timeout on VirtualService, I get 504 UT instead (istio-proxy logs: Sending local reply with details `upstream_response_timeout`).

```logs
tmp-1 istio-proxy [2020-04-08 08:42:36.539][31][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1255] [C6][S15320993954660358114] Sending local reply with details upstream_reset_before_response_started{connection failure}
tmp-1 istio-proxy [2020-04-08 08:42:36.539][31][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1448] [C6][S15320993954660358114] encoding headers via codec (end_stream=true):
tmp-1 istio-proxy ':status', '503'
tmp-1 istio-proxy 'content-length', '91'
tmp-1 istio-proxy 'content-type', 'text/plain'
tmp-1 istio-proxy 'date', 'Wed, 08 Apr 2020 08:42:36 GMT'
tmp-1 istio-proxy 'server', 'envoy'
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

n/a

**Expected behavior**

TLS origination to work as described in the docs.

**Steps to reproduce the bug**

Use following manifests:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: confluent
  namespace: tmp-namespace
spec:
  exportTo:
  - .
  hosts:
  - "www.confluent.io"
  ports:
  - number: 80
    name: http-port
    protocol: HTTP
  - number: 443
    name: https-port
    protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name:  confluent
  namespace: tmp-namespace
spec:
  exportTo:
  - .
  hosts:
  - "www.confluent.io"
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: www.confluent.io
        port:
          number: 443
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name:  confluent
  namespace: tmp-namespace
spec:
  exportTo:
  - .
  host: "www.confluent.io"
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE
```

- `curl` from istio injected pod to `www.confluent.io`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```sh
istioctl version --remote
client version: 1.5.1
citadel version: 1.3.8
galley version: 1.3.8
ingressgateway version: 1.3.8
ingressgateway version: 1.3.8
pilot version: 1.3.8
pilot version: 1.3.8
policy version: 1.3.8
sidecar-injector version: 1.3.8
telemetry version: 1.3.8
data plane version: 1.3.8 (120 proxies)
```

Kubernetes:
Client version is on 1.18.
Server version is on 1.14.

Helm V2.

**How was Istio installed?**

Via `helm template` (v2).

Notable values:

```yaml
global:
  disablePolicyChecks: false
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY
sidecarInjectorWebhook:
  rewriteAppHTTPProbe: true
```

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS (cluster brought up by Rancher).

---

Note: I am on this for couple days already and I've searched & read **all** relevant issues (closed or open) relating to 503, UT, URX, DC, TLS, `upstream_reset_before_response_started`:

- https://github.com/envoyproxy/envoy/issues/8639
- https://github.com/istio/istio/issues/15285
- https://github.com/istio/istio/issues/19101
- https://github.com/istio/istio/issues/17031
- couple more...

as well as read this awesome article about 503s https://karlstoney.com/2019/05/31/istio-503s-ucs-and-tcp-fun-times/index.html. No joy.

**Comment by howardjohn** [comment]
I installed 1.4 and applied the same config and get a 200. Maybe try updating?

**Comment by Kyslik** [comment]
I will try this out on different (smaller in number of proxies) cluster with 1.3.8 and then upgrade to 1.4. If the issue persists.

**Comment by Kyslik** [comment]
I tried this on the smaller clusters, same issue. Although this time I make requests from our smaller cluster to another cluster we run and I get `upstream connect error or disconnect/reset before headers. reset reason: connection failure` (istio-proxy logs are same as in [OP description](https://github.com/istio/istio/issues/22802#issue-596441648) 503...). 

I tried to `curl` from the app's `istio-proxy` container and I get 200 (or 301 in case `http` ✅ ). I also compared steps in between 1.3.8 docs and 1.5.x docs and there is no change, did this not work on 1.3.x or there is something odd with our cluster set up? It's clear that I don't want to give up on 1.3.8 yet as upgrading is lot's of work currently :(, however I am planning to test it out on 1.4.x who knows when. Regardless, more findings:

Note when I change `virtualservice.spec.resolution` from `DNS` to `NONE` I get slightly different error - `tmp istio-proxy [2020-04-14 12:41:30.931][33][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1255] [C68][S8472960152665020098] Sending local reply with details upstream_reset_before_response_started{connection failure,TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER}`. I checked all issues with that error or simillar, no joy.

As soon as I remove DR, I can curl 443 (and get 200) from _app_ container (same SE and same VS is in place). I can not curl port 80 (expected I guess):`

```sh
< HTTP/1.1 503 Service Unavailable
< content-length: 91
< content-type: text/plain
< date: Tue, 14 Apr 2020 15:20:18 GMT
< server: envoy
```

**Comment by Stocco** [comment]
Try to add the `sni` flag to your destinationrule and see if it works
```
  host: "www.confluent.io"
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE
        sni: www.confluent.io
```
