### ISSUE TITLE
Can istio-proxy add additional "source namespace" to http header during forwarding http request.

### ISSUE THREAD

**Issue by johnzheng1975** [istio/istio#22803]
**Describe the feature request**
Istio-proxy is can forward http request as a proxy.
Can below be implement?
One http request is send from namespace a to namespace b.
Can istio-proxy add this additional "source namespace a" to http header during forwarding http request?

We have such requirements, we hope implement it with configure, instead of customize istio-proxy code. Thanks.  

*

**Comment by howardjohn** [comment]
You can add it with https://istio.io/docs/reference/config/networking/virtual-service/#Headers-HeaderOperations. You should know the namespace so you would apply something like: `add: source: my-namespace`

**Comment by johnzheng1975** [comment]
Thanks.  My requirement is: 
serviceA.namespace1 access serviceDestination.namespaceN, need add namespace1 in http request.
serviceB.namespace2 access serviceDestination.namespaceN, need add namespace2 in http request.
So, it is not a const value, it need get dynamicly.
Does Headers-HeaderOperations support this?  Thanks a lot.

**Comment by howardjohn** [comment]
I get that its ideally dynamic, but you can statically define the VS in each namespace

**Comment by johnzheng1975** [comment]
Thanks for your answer. I define as below, but it does not works.
For namespace1:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: add-header-route
  namespace: ns1
spec:
  hosts:
  - web-service.default.svc.cluster.local
  http:
  - route:
    - destination:
        host: web-service.default.svc.cluster.local
        port:
          number: 80
      weight: 100
    headers:
      request:
        add:
          ns_id: ns1
```
For namespace2:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: add-header-route
  namespace: ns2
spec:
  hosts:
  - web-service.default.svc.cluster.local
  http:
  - route:
    - destination:
        host: web-service.default.svc.cluster.local
        port:
          number: 80
      weight: 100
    headers:
      request:
        add:
          ns_id: ns2
```
I execute `curl web-service.default` in namespace1 's pod.
However, the added header is 
`"ns_id": "ns2"`

**Comment by howardjohn** [comment]
That is a bug, I'll see if I can fix it

**Comment by johnzheng1975** [comment]
@howardjohn , thanks a lot for your quick response and excellent fix.  Can this also be included in istio 1.4 release? We are using it.

And, is there any other easy way can implement my requirement?  
Can envoy filter works for this? Could you give me an example if it works. Thanks so much!

**Comment by johnzheng1975** [comment]
Ok, I can implement my user case through exportTo.

**Comment by johnzheng1975** [comment]
With below:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: add-header-route
  namespace: ns1
spec:
  hosts:
  - web-service.default.svc.cluster.local
  exportTo:
  - "."
  http:
  - route:
    - destination:
        host: web-service.default.svc.cluster.local
        port:
          number: 80
      weight: 100
    headers:
      request:
        add:
          ns_id: ns1
```

**Comment by johnzheng1975** [comment]
I can implement my requirement with exportTo now.   So close it.
```
spec:
  hosts:
  - web-service.default.svc.cluster.local
  exportTo:
  - "."
  http:
  - route:
    - destination:
```

Thanks for your time and support. @howardjohn
