### ISSUE TITLE
Removing a locality from localityLbSetting.Distribute breaks the mesh

### ISSUE THREAD

**Issue by maruina** [istio/istio#22837]
**Bug description**

Consider the following setup:
* Multiple Service Entries with a locality of the type `prefix/az/cluster`, for example
```
- foo/eu-west-1a/cluster1
- foo/eu-west-1b/cluster2
```
* A globally configured Locality-weighted load balancing as the following
```
localityLbSetting:
  distribute:
  - from: '*'
    to: 
      foo/eu-west-1a/cluster1: 98
      foo/eu-west-1b/cluster2: 1
      eu-west-1/*: 1
```
On `cluster1`, the mesh works as expected and the routes get updated.

As soon we remove one locality from the Istio configmap, all the new envoy proxies don't get ready anymore.

For example, with this configuration
```
localityLbSetting:
  distribute:
  - from: '*'
    to: 
      foo/eu-west-1b/cluster2: 99
      eu-west-1/*: 1
```
we get the following error
```
Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 0 rejected
```

As soon as we add the locality back, the proxies become ready again. We can't see any error in the Pilot logs.

Another interesting discovery is that we just need the locality in the configmap, so if we write something like
```
localityLbSetting:
  distribute:
  - from: '*'
    to: 
      foo/eu-west-1b/cluster2: 99
      eu-west-1/*: 1
  - from: 'bar'
    to: 
      foo/eu-west-1a/cluster1: 98
      foo/eu-west-1b/cluster2: 1
      eu-west-1/*: 1
```
All the envoy proxies are starting even if `bar` is a non existing locality.

Is this an expected behavior? We couldn't find anything in the documentation mentioning this.

**Expected behavior**

I would expect the mesh working even if we remove a locality from the distribute settings.

**Steps to reproduce the bug**

See the description.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
❯ istioctl version --remote
client version: 1.4.6
crosscellgateway version:
crossregiongateway version:
defaultgateway version:
citadel version: 1.4.3
citadel version: 1.4.3
galley version: 1.4.3
galley version: 1.4.3
pilot version: 1.4.3
pilot version: 1.4.3
policy version: 1.4.3
policy version: 1.4.3
sidecar-injector version: 1.4.3
sidecar-injector version: 1.4.3
telemetry version: 1.4.3
telemetry version: 1.4.3
thanosgateway version:
thanosgateway version:
data plane version: 1.4.3 (28 proxies)
```

```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-26T06:16:15Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.9", GitCommit:"500f5aba80d71253cc01ac6a8622b8377f4a7ef9", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:04Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

Helm chart deployed with Spinnaker.

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS, AMI Amazon Linux 2

**Comment by howardjohn** [comment]
Definitely not expected.. thats very interesting. does the `Envoy proxy is NOT ready ` log continue forever (or at least a few minutes)? And there are no error logs (specifically "ACK ERROR ....")?

Can you start a pod with debug logging enabled? You can add `sidecar.istio.io/logLevel: "debug"` annotation to a pod to do it. See https://github.com/istio/istio/wiki/Troubleshooting-Istio#collecting-information-2. 

cc @lambdai might be another EDS warming case

**Comment by maruina** [comment]
> `Envoy proxy is NOT ready` log continue forever (or at least a few minutes)?

Forever, or al least we gave up after ~ 10 minutes. No other error logs, just that line.

I will get the debug logs and I will come back to you.

**Comment by lambdai** [comment]
@maruina When envoy is stuck, could you dump the clusters w/ below command?
```
istioctl pc cluster  <pod.namespace> -o json
```

I am seeing another similar case which has a STRICT_DNS cluster with no host/endpoint. Envoy cannot bring the cluster into use. When envoy receives this cluster config at start up, the envoy is stalled.

**Comment by maruina** [comment]
The logs are pretty heavy, so I added them here: https://gist.github.com/maruina/e8bd58559ab31de4c5ca9ac8f152cde0

**Comment by chaudyg** [comment]
The issues comes from a service entry only matching the locality being removed.
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: thanos.skyscanner.io
  namespace: istio-system
spec:
  addresses: []
  endpoints:
  - address: 172.16.224.11
    locality: crosscell/eu-west-1a/cellsdev-1-eu-west-1a-1
    ports:
      http: 443
  exportTo:
  - '*'
  hosts:
  - thanos.skyscanner.io
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 80
    protocol: HTTP
  resolution: DNS
```
The resulting Envoy config has a cluster with no lb_endpoints. 
```  {
     "version_info": "2020-04-13T12:47:53Z/5",
     "cluster": {
      "name": "outbound|80||thanos.skyscanner.io",
      "type": "STRICT_DNS",
      "connect_timeout": "1s",
      "max_requests_per_connection": 100,
      "circuit_breakers": {
       "thresholds": [
        {
         "max_connections": 4294967295,
         "max_pending_requests": 4294967295,
         "max_requests": 4294967295,
         "max_retries": 4294967295
        }
       ]
      },
      "tls_context": {
       "common_tls_context": {
        "validation_context": {}
       },
       "sni": "thanos.skyscanner.io"
      },
      "dns_refresh_rate": "300s",
      "dns_lookup_family": "V4_ONLY",
      "outlier_detection": {
       "interval": "30s",
       "base_ejection_time": "60s",
       "max_ejection_percent": 70,
       "enforcing_consecutive_5xx": 0,
       "consecutive_gateway_failure": 10,
       "enforcing_consecutive_gateway_failure": 100
      },
      "metadata": {
       "filter_metadata": {
        "istio": {
         "config": "/apis/networking/v1alpha3/namespaces/istio-system/destination-rule/thanos.skyscanner.io"
        }
       }
      },
      "common_lb_config": {
       "healthy_panic_threshold": {},
       "locality_weighted_lb_config": {}
      },
      "load_assignment": {
       "cluster_name": "outbound|80||thanos.skyscanner.io",
       "endpoints": [
        {
         "locality": {
          "region": "crosscell",
          "zone": "eu-west-1a",
          "sub_zone": "cellsdev-1-eu-west-1a-1"
         },
         "load_balancing_weight": 1
        }
       ]
      },
      "respect_dns_ttl": true
     },
     "last_updated": "2020-04-13T12:47:56.109Z"
    },```

Then Envoy gets stuck in PRE_INITIALIZATION
