### ISSUE TITLE
Istio operator fails to create pvc for grafana 

### ISSUE THREAD

**Issue by krackjack29** [istio/istio#22835]
**Bug description**
Istioctl manifest generated for a demo profile with grafana persistence fails to create PVC which causes the grafana pod to wait in "ConatinerCreating" status.

Problem is that it doesn't honor the namespace that is specified in the IstioOperator Spec, this is the pvc generated

```yaml
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: istio-grafana-pvc
  labels:
    app: grafana
    release: istio
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
```

**Expected behavior**
PVC for grafana should be created in the namespace specified in the IstioOperator spec.

**Steps to reproduce the bug**
using below yaml to generate manifest.
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: profile-demo-customized  
spec:
  hub: gcr.io/shared-gcr-c99a/istio
  tag: 1.5.1
  profile: demo
  # Traffic management feature
  components:
    base:
      enabled: true
    pilot:
      enabled: true
      # Policy feature
    policy:
      enabled: true
    telemetry:
      enabled: true
      
  # Config management feature
    galley:
      enabled: false

  # Auto injection feature
    sidecarInjector:
      enabled: false

  # Istio Gateway feature
    ingressGateways:
    - name: istio-ingressgateway
      enabled: false
     
    egressGateways:
    - name: istio-egressgateway
      enabled: true
      # Istio CNI feature
    cni:
      enabled: false

  addonComponents:
    prometheus:
      enabled: false
    kiali:
      enabled: true
    grafana:
      enabled: true
    tracing:
      enabled: true
    istiocoredns:
      enabled: false
  
  values:
    kiali:
      createDemoSecret: true
      dashboard:
        grafanaURL: http://grafana:3000
        secretName: kiali-admin
      prometheusAddr: http://prometheus-server:9090
    grafana:
      persist: true
      storageClassName: "standard"
      accessMode: ReadWriteOnce
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
          - name: Prometheus
            type: prometheus
            orgId: 1
            url: http://prometheus-server:9090
            access: proxy
            isDefault: true
            jsonData:
              timeInterval: 5s
            editable: true
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
client version: 1.5.1
control plane version: 1.5.1
data plane version: 1.5.1 (9 proxies)

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Com
piler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-gke.3", GitCommit:"71631703d37fb1b4b333abd427deae839aeb2032", GitTreeState:"clean", BuildDate:"2020-03-24T18:54:48Z", GoVersion:"go1.12
.17b4", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
IstioOperator
