### ISSUE TITLE
Unable to connect Elasticache Redis from inside of a istio sidecar enabled pod

### ISSUE THREAD

**Issue by abhijitio** [istio/istio#22883]
**Bug description**

I have deployed a EKS cluster and I am using Istio . I am trying to connect Elasticache Redis cluster from inside of a pod and that pod has Istio sidecar enabled. I have encryption disabled in Redis cluster. It is working as expected when I am connecting from a non-istio pod. Command to connect redis, I am using ,

```
redis-cli -h redis.xxx.amazonaws.com
redis.xxx.amazonaws.com:6379> ping
Error: Connection reset by peer
```

I have created a DestionationRule , ServiceEntry and VirtualService in that namespace from where I am trying to connect.

ServiceEntry :-

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: elasticache-svc-redis
  namespace: <NAME>
spec:
  hosts:
    - "redis.xxx.amazonaws.com"
  location: MESH_EXTERNAL
  ports:
    - number: 6379
      name: redis
      protocol: TCP
  resolution: DNS 
```

DestinationRule :- 

```
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
    name: redis-elasticcache
    namespace: <NAME>
spec:
    host: "*.amazonaws.com"
    trafficPolicy:
        tls:
            mode: DISABLE
```

VirtualService :- 

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: redis-test-cluster
  namespace: <NAME>
spec:
  hosts:
  - redis.xxx.amazonaws.com
  http:
  - timeout: 30s
    route:
    - destination:
        host: redis.xxx.amazonaws.com
```

**Observations**

I can connect through netcat but not telnet ,

```
telnet redis.xxx.amazonaws.com 6379
Trying 10.30.10.177...
Connected to redis.xxx.amazonaws.com.
Escape character is '^]'.
Connection closed by foreign host.
```

Netcat :- 

```
nc -v redis.xxx.amazonaws.com 6379
redis.xxx.amazonaws.com (10.30.10.177:6379) open
```

**Expected behavior**

```
redis-cli -h redis.xxx.amazonaws.com
redis.xxx.amazonaws.com:6379> ping
PONG
```

**Steps to reproduce the bug**

Go inside of a pod ,

`kubectl exec -it <pod_name> -n <name_spcae> -c <default_container> /bin/bash`
Run the command,
`redis-cli -h XXXXX.amazonaws.com`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

Version :-` istioctl version --remote`
```
client version: 1.5.1
internal-popcraftio-ingressgateway version: 
citadel version: 1.4.3
galley version: 1.4.3
ingressgateway version: 1.4.3
pilot version: 1.4.3
policy version: 1.4.3
sidecar-injector version: 1.4.3
telemetry version: 1.4.3
office-popcraftio-ingressgateway version: 
data plane version: 1.4.3 (88 proxies)
```

`kubectl version` :- 

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

helm version :- 

`version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}`

**How was Istio installed?**

Cluster was created using helm chart .

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS EKS Version 1.14

**Comment by esnible** [comment]
See https://github.com/istio/istio/issues/14743 https://github.com/istio/istio/issues/12079 https://github.com/istio/istio/issues/14138 https://github.com/istio/istio/issues/15429 https://github.com/istio/istio/issues/16078 <-- see this issue for possible solution

**Comment by meshok0** [comment]
We had the exact same problem. EKS 1.14, Istio 1.6.5
In our case the problem was in a sort of a race condition between envoy and app containers. App couldn't make connection to  Elasticache redis until envoy sidecar is fully up and synced.

Our app is on .Net and we are using StackExchange.Redis client lib.
Adding `resolveDns=true,connectRetry=100,connectTimeout=5000,abortConnect=false` solved the issue for us. (https://stackexchange.github.io/StackExchange.Redis/Configuration.html#configuration-options)

Look at these for a detailed explanation:
https://github.com/kubernetes/kubernetes/issues/65502
https://banzaicloud.com/blog/k8s-sidecars/

**Comment by adiseshan** [comment]
Adding annotation in Deployments as below solved the isssue.

`      annotations:`
`        traffic.sidecar.istio.io/excludeOutboundPorts: "6379"`

**Comment by Hronom** [comment]
Same here in 2023 with istio `1.18.2` able to resolve by:
```
annotations:
        traffic.sidecar.istio.io/excludeOutboundPorts: "6379"
```

we have MTLS in strict mode.

Having:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: ggg
  namespace: ggg
spec:
  hosts:
    - ggg.cache.amazonaws.com
  location: MESH_EXTERNAL
  ports:
    - name: tcp-redis
      number: 6379
      protocol: TCP
  resolution: DNS
```
not helps

Also we accessing amazon elasticache
