### ISSUE TITLE
When CNI is installed, traffic.sidecar.istio.io annotations are not injected to Pods

### ISSUE THREAD

**Issue by cagataygurturk** [istio/istio#22902]
**Bug description**

When CNI plugin is enabled and and `spec.values.global.proxy.excludeIPRanges` or `spec.values.global.proxy.includeIPRanges` is set, corresponding `traffic.sidecar.istio.io` annotations are not injected to Pods. This causes the configuration value to be ignored in the Pod.

Moreover, `istio-validation`  init container successfully passes, giving the impression that correct iptables settings are applied on the Pod.

`istio-sidecar-injector` ConfigMap have the correct values after installation. This `podRedirectAnnot` configuration is probably ignored by the sidecar injector itself.

I have only tried with `excludeIPRanges` and `includeIPRanges` but there is a high chance that this bug applies to all values defined in `podRedirectAnnot`.

See istio/cni#293 for more context.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

client version: 505cb62a5169c3752bbea0decedac9a40f10b87b-dirty
control plane version: 1.6-alpha.505cb62a5169c3752bbea0decedac9a40f10b87b
data plane version: 1.6-alpha.505cb62a5169c3752bbea0decedac9a40f10b87b (10 proxies)

**How was Istio installed?**

Via istioctl using the following configuration:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: demo
  tag: latest
  hub: gcr.io/istio-testing
  components:
    cni:
      enabled: true
  values:
    cni:
      cniBinDir: /home/kubernetes/bin
    global:
      proxy:
        excludeIPRanges: 188.166.192.215/32
```

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE
