### ISSUE TITLE
Standart K8S Ingress: Duplicate ingresses object causes crash for istiod

### ISSUE THREAD

**Issue by iusergii** [istio/istio#22910]
**Bug description**
Deploy of duplicate standard kubernetes Ingress object in different namespace causes crash for **istiod**

**Expected behavior**
Warning/Error in logs.

**Steps to reproduce the bug**
Deploy first Ingress to monitoring namespace

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: prometheus-kafka-ing
  namespace: monitoring
spec:
  rules:
  - host: kafka-prom11.dev.kube.my.com
    http:
      paths:
      - backend:
          serviceName: prometheus-kafka
          servicePort: 9090
```
Deploy second Ingress to default namespace
```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: prometheus-kafka-ing
  namespace: default
spec:
  rules:
  - host: kafka-prom11.dev.kube.my.com
    http:
      paths:
      - backend:
          serviceName: prometheus-kafka
          servicePort: 9090
```
Cause istod panic
```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x19309c2]

goroutine 28236 [running]:
istio.io/istio/pilot/pkg/config/kube/ingress.ConvertIngressVirtualService.func1(0x1, 0x0, 0x97)
        istio.io/istio@/pilot/pkg/config/kube/ingress/conversion.go:196 +0x62
sort.insertionSort_func(0xc001656428, 0xc00cbc4740, 0x0, 0x2)
        sort/zfuncversion.go:12 +0xb1
sort.stable_func(0xc001656428, 0xc00cbc4740, 0x2)
        sort/zfuncversion.go:171 +0x86
sort.SliceStable(0x2126880, 0xc00cbc4720, 0xc001656428)
        sort/slice.go:27 +0xcb
istio.io/istio/pilot/pkg/config/kube/ingress.ConvertIngressVirtualService(0x0, 0x0, 0x0, 0x0, 0xc000a5b320, 0x14, 0x0, 0x0, 0xc001395d49, 0x7, ...)
        istio.io/istio@/pilot/pkg/config/kube/ingress/conversion.go:192 +0x623
istio.io/istio/pilot/pkg/config/kube/ingress.(*controller).List(0xc000568fc0, 0x2678a6e, 0x13, 0x26638ee, 0x8, 0x266d8d6, 0xe, 0x0, 0x0, 0xc006bc4580, ...)
        istio.io/istio@/pilot/pkg/config/kube/ingress/controller.go:267 +0xa50
istio.io/istio/pilot/pkg/config/aggregate.(*store).List(0xc0000e49b0, 0x2678a6e, 0x13, 0x26638ee, 0x8, 0x266d8d6, 0xe, 0x0, 0x0, 0x30, ...)
        istio.io/istio@/pilot/pkg/config/aggregate/config.go:150 +0x221
istio.io/istio/pilot/pkg/model.(*PushContext).initVirtualServices(0xc008852000, 0xc000225180, 0xe, 0x2663801)
        istio.io/istio@/pilot/pkg/model/push_context.go:1165 +0x120
istio.io/istio/pilot/pkg/model.(*PushContext).updateContext(0xc008852000, 0xc000225180, 0xc002dc2580, 0xc006f78360, 0xc0023f3e68, 0x40ca28)
        istio.io/istio@/pilot/pkg/model/push_context.go:969 +0x1ea6
istio.io/istio/pilot/pkg/model.(*PushContext).InitContext(0xc008852000, 0xc000225180, 0xc002dc2580, 0xc006f78360, 0x0, 0x0)
        istio.io/istio@/pilot/pkg/model/push_context.go:870 +0x26e
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).Push(0xc00083e180, 0xc006f78360)
        istio.io/istio@/pilot/pkg/proxy/envoy/v2/discovery.go:213 +0x31b
istio.io/istio/pilot/pkg/proxy/envoy/v2.debounce.func1(0xc006f78360)
        istio.io/istio@/pilot/pkg/proxy/envoy/v2/discovery.go:290 +0x38
created by istio.io/istio/pilot/pkg/proxy/envoy/v2.debounce.func2
        istio.io/istio@/pilot/pkg/proxy/envoy/v2/discovery.go:306 +0x281
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```bash
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-26T06:16:15Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T20:52:22Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
```bash
istioctl version
client version: 1.5.1
control plane version: 1.5.1
data plane version: 1.5.1
```
**How was Istio installed?**
IstioOperator
