### ISSUE TITLE
Explicit document on Sidecar CR, egress listener: the combination of bind and capture mode iptables

### ISSUE THREAD

**Issue by lambdai** [istio/istio#22914]
```
kind: Sidecar
spec:
  egress:
    captureMode: IPTABLES
    bind: A_IP
    hosts:
      - "serviceX"
      - "serviceY"
```
If the capture mode is iptables and bind is not empty, we sometime generate listener reflecting the config. However, this is more like a beautiful mistake.
1. It introduce conflicts if A_IP is used by other service
2. Even the A_IP is unique, serviceX and serviceY could have conflicts under the same IP. (p.s. w/o bind A_IP, istio bind the ip according to the vip of X and Y in service registry)

The follow up
[ ] Draft new document to explain the invalid combination
[ ] new invalidation rule
[ ] #22217 assumes bind is empty string when capture mode is iptables
