### ISSUE TITLE
Service Entry doesn't allow specifying port in endpoint like document mentioned

### ISSUE THREAD

**Issue by minhtrietbkit** [istio/istio#22971]
**Bug description**
Service Entry endpoints don't allow specifying port with following error:

```
        * endpoint port 8080 is not defined by the service entry
        * endpoint port 9080 is not defined by the service entry
        * endpoint port 7080 is not defined by the service entry
```

**Expected behavior**
Service Entry is created.

**Steps to reproduce the bug**
Apply the exact same configuration in the document [here](https://istio.io/docs/reference/config/networking/service-entry)
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-dns
spec:
  hosts:
  - foo.bar.com
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
  endpoints:
  - address: us.foo.bar.com
    ports:
      https: 8080
  - address: uk.foo.bar.com
    ports:
      https: 9080
  - address: in.foo.bar.com
    ports:
      https: 7080
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
`istioctl`

client version: 1.5.0
control plane version: 1.5.0
data plane version: 1.5.0 (3 proxies)

`kubectl`

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:34Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
Using `istioctl manifest apply -f ./istio-manifest.yaml` with slightly custom istio-manifest.yaml

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS

**Comment by esnible** [comment]
The problem is that the `http: 8080` ports need a left-side that matches `name: http`.  The documentation example names the port `http` but refers to it as `https`.  This validates:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-dns
spec:
  hosts:
  - foo.bar.com
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
  endpoints:
  - address: us.foo.bar.com
    ports:
      http: 8080
  - address: uk.foo.bar.com
    ports:
      http: 9080
  - address: in.foo.bar.com
    ports:
      http: 7080
```

It also validates if we use `https` instead of `http` throughout.
