### ISSUE TITLE
Metadata and other attributes not supported for ingress operator installs

### ISSUE THREAD

**Issue by tshak** [istio/istio#22991]
**Describe the feature request**

Adding labels to a custom ingress in the ingress operator is not possible. This is required for systems like Knative which use label selectors. There is an existing closed issue regarding the custom ingress feature in which the community has proposed several brittle workarounds: https://github.com/istio/istio/issues/19263#issuecomment-607519037. 

**Describe alternatives you've considered**

See https://github.com/istio/istio/issues/19263#issuecomment-607519037

**Additional context**

We should be able to add metadata to an ingress e.g.
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: demo
  namespace: istio-system
spec:
  components:
    ingressGateways:
    - enabled: true
      k8s:
        # --- new section --- 
        metadata:
          labels:
            istio: my-custom-lable
       # --- /new section ---
      name: my-custom-gateway
```

**Comment by morvencao** [comment]
The yaml is incorrect!

You can add labels for custom gateway after this PR: https://github.com/istio/istio/pull/22981

```
kind: IstioOperator
metadata:
  name: demo
  namespace: istio-system
spec:
  components:
    ingressGateways:
    - name: my-custom-gateway
      enabled: true
      # --- new section --- 
      label:
        istio: my-custom-label
      # --- /new section ---
```

Backport to 1.5.x is pending: https://github.com/istio/istio/pull/23026
