### ISSUE TITLE
When CNI is installed, Pods cannot communicate with each other

### ISSUE THREAD

**Issue by Jul13nT** [istio/istio#22995]
**Bug description**

When installing Istio with CNI enabled on GKE, I have the impression that pods cannot communicate with each other. For testing, I'm installing [the following chart](https://github.com/helm/charts/tree/master/stable/mongodb-replicaset) with default values, in the default namespace (which is labelled for Istio injection). All 3 Mongo pods are able to start and seems fine, but in reality there are 3 different replica sets with only one host in each one.
If I disable Istio injection, I have only one replica set with the 3 nodes in it.

I am not seeing any error in Istio logs, but maybe I'm not looking in the right place.

**Affected product area**

[X] Networking

**Expected behavior**

The MongoDB pods should be able to communicate with each other and form a single replica set.

**Steps to reproduce the bug**

[Platform setup](https://istio.io/docs/setup/platform-setup/gke/), then:

```bash
$ istioctl manifest apply -f manifest.yaml  (with the manifest provided below)
$ kubectl label namespace default istio-injection=enabled
$ helm3 install mongo stable/mongodb-replicaset
```

From this point, I can check if the replica set is correct by running:

```bash
$ kubectl exec mongodb-mongodb-replicaset-0 -c mongodb-replicaset -- sh -c 'mongo --eval="printjson(rs.isMaster())"'
```

I should have the following response:

```json
"hosts" : [
        "mongodb-mongodb-replicaset-0.mongodb-mongodb-replicaset.default.svc.cluster.local:27017",
        "mongodb-mongodb-replicaset-1.mongodb-mongodb-replicaset.default.svc.cluster.local:27017",
        "mongodb-mongodb-replicaset-2.mongodb-mongodb-replicaset.default.svc.cluster.local:27017"
]
```

But I'm seeing:

```json
"hosts" : [
        "mongodb-mongodb-replicaset-0.mongodb-mongodb-replicaset.default.svc.cluster.local:27017"
]
```

**Version**

```bash
$ istioctl version --remote
client version: 1.5.1
control plane version: 1.5.1
data plane version: 1.5.1 (5 proxies)
```
```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.24", GitCommit:"39e41a8d6b7221b901a95d3af358dea6994b4a40", GitTreeState:"clean", BuildDate:"2020-02-29T01:24:35Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

From https://istio.io/docs/setup/install/istioctl/ with the following manifest:

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  addonComponents:
    grafana:
      enabled: true
    kiali:
      enabled: true
    tracing:
      enabled: true
  components:
    cni:
      enabled: true
      namespace: kube-system
  values:
    sidecarInjectorWebhook:
      enabled: true
    cni:
      cniBinDir: /home/kubernetes/bin
      excludeNamespaces:
        - istio-system
        - kube-system
      logLevel: info
```

Prerequisites for GKE were followed (enable-network-policy and cluster admin permissions).

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE with 3 n2-standard-2 nodes, Container-Optimized OS. Kubernetes version 1.15.9-gke.24 (same problem with 1.16.8-gke.8)
I have observed the exact same problem with a Kubernetes cluster on Scaleway (1.16.8 and 1.17.4)

[istio-dump.tar.gz](https://github.com/istio/istio/files/4487650/istio-dump.tar.gz)
