### ISSUE TITLE
CIDR doesnt work in ServiceEntry spec.addresses for HTTP traffic

### ISSUE THREAD

**Issue by infa-ddeore** [istio/istio#23024]
**Bug description**
I am trying to make pod-to-pod connection work over mtls (dont ask why :-)) and following mongodb [serviceentry](https://preliminary.istio.io/docs/reference/config/networking/service-entry/) example, when I use single ip in `spec.addresses` then a pod can connect to another pod over its ip but when i use a CIDR as given in mongodb example "- 192.192.192.192/24 # VIPs" the communication doesnt happen

**Expected behavior**
pod to pod communication should happen with CIDR same way it happens with single ip

**Steps to reproduce the bug**
1) create a namespace `target`, enable istio injection and set strict mtls
```
kubectl create ns target

kubectl label ns target istio-injection=enabled

kubectl apply -n target -f - <<EOF
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
spec:
  mtls:
    mode: STRICT
EOF
```

2) create a pod in `target` namespace
```
kubectl -n target apply -f https://raw.githubusercontent.com/istio/istio/master/samples/httpbin/httpbin.yaml
```

3) create a `source` namespace with istio injection enabled
```
kubectl create ns source

kubectl label ns source istio-injection=enabled
```

4) create a pod in `source` namespace and access `target` pod directly with its ip, it doesnt work because another pod's ip is not a known cluster
```
kubectl -n source run -i --tty --rm --generator=run-pod/v1 curl-pod --image=radial/busyboxplus:curl

[ root@curl-pod:/ ]$ curl http://172.17.0.22/get; echo
upstream connect error or disconnect/reset before headers. reset reason: connection termination
```

5) use `serviceentry` and `destinationrule` to make it work
```
kubectl -n source apply -f - <<EOF 
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: pod-to-pod.local
spec:
  hosts:
  - pod-to-pod.local # not used
  addresses:
  - 172.17.0.22 # VIPs
  ports:
  - number: 80
    name: http
    protocol: HTTP
  #By default "*" is used in exportTo, which means this entry is exposed to every namespace. 
  # "." restricts it to the current namespace only. 
  exportTo:
  - "."    
  location: MESH_INTERNAL
  resolution: NONE
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: pod-to-pod.local
spec:
  host: pod-to-pod.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
EOF
```

6) communication works at this point 
```
[ root@curl-pod:/ ]$ curl http://172.17.0.22/get; echo
{
  "args": {}, 
  "headers": {
    "Accept": "*/*", 
    "Content-Length": "0", 
    "Host": "172.17.0.22", 
    "User-Agent": "curl/7.35.0", 
    "X-B3-Parentspanid": "5481269a111a25ee", 
    "X-B3-Sampled": "0", 
    "X-B3-Spanid": "7a67cae4261e40e5", 
    "X-B3-Traceid": "d50a6075b4f8e9bf5481269a111a25ee", 
    "X-Forwarded-Client-Cert": "By=spiffe://cluster.local/ns/default/sa/httpbin;Hash=b85ce75e61bf234151f40228c96f3a6d0650e2f8b7f5bb1ad7544f6287ec1846;Subject=\"\";URI=spiffe://cluster.local/ns/lamm/sa/default"
  }, 
  "origin": "127.0.0.1", 
  "url": "http://172.17.0.22/get"
}
```
7) now replace `172.17.0.22` in `spec.addresses` in `ServiceEntry` with cidr as per the example given in document, something like `172.17.0.0/16` (or /24) and reapply serviceentry and destinationrule, curl can't communicate to the pod after this change

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
$ istioctl version --remote
client version: 1.5.1
control plane version: 1.5.1
data plane version: 1.5.1 (10 proxies)

$ kubectl version 
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:34Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
minikube on MacOS
