### ISSUE TITLE
External requests fail, and "Problem with the SSL CA cert" when sending an HTTPS request from the istio-proxy

### ISSUE THREAD

**Issue by markvincze** [istio/istio#2306]
I installed istio and injected the sidecar into one of my services. My issue is that with the sidecar container being in place, I cannot send any requests to external services from my actual container, and I'm trying to investigate what the problem can be.

If I enter the `istio-proxy` container with bash, and execute `curl http://example.com`, then it works, but if I do `curl https://example.com`, then I receive
```
curl: (77) Problem with the SSL CA cert (path? access rights?)
```

Is this expected? If not, what can cause this?

The actual issue that I'm investigating is that if I'm trying to do the same curl command (`curl http://example.com`) in my actual application container, I get
```
root@myservice-6f548df4d5-v4kmj:/# curl http://example.com
curl: (7) Failed to connect to example.com port 80: Connection refused
```
I have already followed the [guide](https://istio.io/docs/tasks/traffic-management/egress.html#before-you-begin) about setting up the rule for egress traffic, and I applied the following rul:
```
apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: examplecom-egress-allow-rule
spec:
  destination:
    service: example.com
  ports:
    - port: 80
      protocol: http
    - port: 443
      protocol: https
```
Should external requests work properly?
It'd be great if you could give me some pointers about where to start troubleshooting this issue.
