### ISSUE TITLE
Unable to drain k8s node, error due to Pod has more than one PDB, which the eviction subresource does not support

### ISSUE THREAD

**Issue by laurentiuspurba** [istio/istio#23075]
**Bug description**
I set `replicaCount: 2` and hpaSpec `minReplicas: 2` in IstioControlPlane, and I can see pods are doubled. But when drained the node got the following error message
```
error: error when evicting pod "istio-ingressgateway-5b694f6978-pc4f9": This pod has more than one PodDisruptionBudget, which the eviction subresource does not support.
```

**Expected behavior**
After increased the number of replicas to 2, the node draining should be completed without error.
I saw similar issues was reported, and some of the reported successfully by increasing the replicas to 2. But for some reason, that is not the case on my situation.
* https://github.com/istio/istio/issues/12602
* kubernetes ticket - https://github.com/kubernetes/kubernetes/pull/90253

**Steps to reproduce the bug**
1. Set `minReplicas: 2` on Istio HPAs
2. Check the pods, make sure they are duplicated
3. Make sure istio-ingressgateway pod is duplicated
4. Drain one of the nodes (preferably that has Istio resources in it)
5. Error was thrown with the following message:
```
error: error when evicting pod "istio-ingressgateway-5b694f6978-pc4f9": This pod has more than one PodDisruptionBudget, which the eviction subresource does not support.
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
* istioctl: v1.4.3
* kubectl: 1.14
* helm version: v2.10.0

**How was Istio installed?**
* Generate manifest files through helm template command
* Use `kubectl apply -f` against generated manifest files

**Environment where bug was observed (cloud vendor, OS, etc)**
* GKE

**Comment by laurentiuspurba** [comment]
IstioControlPlane resource

```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  autoInjection:
    components:
      injector:
        k8s:
          replicaCount: 2
          hpaSpec:
            minReplicas: 2

  policy:
    components:
      policy:
        k8s:
          replicaCount: 2
          hpaSpec:
            minReplicas: 2

  security:
    components:
      certManager:
        enabled: false
      citadel:
        k8s:
          replicaCount: 2
          hpaSpec:
            minReplicas: 2

  trafficManagement:
    components:
      pilot:
        k8s:
          replicaCount: 2
          hpaSpec:
            minReplicas: 2

  gateways:
    components:
      ingressGateway:
        enabled: true
        k8s:
          replicaCount: 2
          hpaSpec:
            minReplicas: 2
      egressGateway:
        enabled: true
        k8s:
          replicaCount: 2
          hpaSpec:
            minReplicas: 2

  configManagement:
    components:
      galley:
        k8s:
          replicaCount: 2
          hpaSpec:
            minReplicas: 2

  telemetry:
    components:
      telemetry:
        k8s:
          replicaCount: 2
          hpaSpec:
            minReplicas: 2

  coreDNS:
    enabled: true
    components:
      coreDNS:
        k8s:
          replicaCount: 2
          hpaSpec:
            minReplicas: 2
...
```

Snippet of the HPA (check:  minReplicas: 2)
```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istio-ingressgateway
```

**Comment by howardjohn** [comment]
This is a duplicate of https://github.com/istio/istio/issues/12602, lets track there to make things simpler. Thanks!

**Comment by agilgur5** [comment]
So the error message here (and linked k8s issues) is different from #12602:
- Here: `This pod has more than one PodDisruptionBudget, which the eviction subresource does not support.`
- There: `Cannot evict pod as it would violate the pod's disruption budget.`

Here the error is that two PDBs were added somehow, not that there was a PDB/HPA mismatch. I'm not quite sure how it would get into that state based on my reading of the configurations though (only one PDB per component)

**Comment by samwhitford** [comment]
@agilgur5 we recently hit the same error. 
It turned out we had an old PDB present from an earlier version of Istio still deployed.
Fix was to simply remove the PDB with the older Istio version reference.

**Comment by agilgur5** [comment]
@samwhitford that would confirm this is a separate issue from #12602 and should be reopened. I have a PR out for that issue with #25873 but it does not resolve the issue here of multiple PDBs. That sounds like a separate issue with `istioctl upgrade`

**Comment by shawntoffel** [comment]
For anyone with multiple ingress/egress gateways make sure you have the appropriate PodDisruptionBudget label/selector patches in place. 

I recently ran into this issue on Istio 1.9.5 as a result of having multiple ingress gateways defined in my operator yaml but missing the PodDisruptionBudget label and selector patches for the gateway with a different name. 

```yaml
overlays:
  - kind: PodDisruptionBudget
    name: istio-ingressgateway-internal
    patches: 
      - path: metadata.labels.app
        value: istio-ingressgateway-internal
      - path: metadata.labels.istio
        value: ingressgateway-internal
      - path: spec.selector.matchLabels.app
        value: istio-ingressgateway-internal
      - path: spec.selector.matchLabels.istio
        value: ingressgateway-internal
```
Without defining these patches multiple PDBs will be created with the same selectors resulting in multiple PDBs applying to a single pod.
