### ISSUE TITLE
VirtualService HTTPMatchRequest headers StringMatch ignores header 'host'

### ISSUE THREAD

**Issue by nsainaney** [istio/istio#23083]
**Bug description**
We are trying to route base on host header such that `foo.bar.somethingA.example.com` can be routed to the same service as `foo.bar.somethingB.example.com`. We would like to match on `foo.*.example.com`. `http: match: headers: user-agent: regex: ...` works fine so we know it's not a configuration issue but putting in host or Host for header does not work.

Followed @howardjohn suggestion for #15456 and encountered this issue.

**Expected behavior**
The documentation [HTTPMatchRequest](https://istio.io/docs/reference/config/networking/virtual-service/#HTTPMatchRequest) does not indicate that 'host' or 'Host' is treated differently. Expect to be able to match on Host (tried variations) but nothing works.

We have been looking through the code over the weekend to determine if the host header is treated differently but don't see anything in pilot/config and networking though we are not very familiar with the codebase.

**Steps to reproduce the bug**
Create a simple port 80 gateway (host: '*')
Add the appropriate DNS for the LoadBalancer
Add the following virtual service:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: example-vs
  namespace: testing
spec:
  gateways:
  - traxitt-system/system-gateway
  hosts:
  - '*'
  http:
  - match:
    - headers:
        host:
          exact: foo.bar.example.com
    route:
    - destination:
        host: example-service
        port:
          number: 80
```

All variations (exact, prefix, regex) are ignored for host header

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.3.0 and 1.4.7 (1.5.1 failed to start on our cluster because of #22463 )

**How was Istio installed?**
istioctl (everything else works - we have ~10 services running)

**Environment where bug was observed (cloud vendor, OS, etc)**
DigitalOcean

**Comment by howardjohn** [comment]
See https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto.html?highlight=header%20match#config-route-v3-headermatcher, I think you need `Host` -> `:authority`

**Comment by nsainaney** [comment]
I don't think I'd have found that without your help. Thank you!

Not sure how to update the istio docs but I'll go ahead and close this issue.

**Comment by howardjohn** [comment]
You can submit a PR or issue to istio/istio.io repo. Thanks!

Actually if its part of
https://istio.io/docs/reference/config/networking/virtual-service/ it would
be the istio/api repo though since those are generated from the API directly

**Comment by buzypi** [comment]
Thanks a lot! That saved my day!

For anyone stumbling on this, here is a functioning Virtual Service:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-service
spec:
  hosts:
    - "*.example.com"
  gateways:
    - my-gateway
  http:
    - match:
        - headers:
            ":authority":
              regex: ".*-foo.example.com"
      route:
        - destination:
            host: service1
            port:
              number: 80
    - match:
        - headers:
            ":authority":
              regex: ".*-bar.example.com"
      route:
        - destination:
            host: service2
            port:
              number: 80
```

So when you apply this and:

```
curl https://hello-foo.example.com/
```

goes to service1, while:

```
curl https://hello-bar.example.com/
```

goes to service2
