### ISSUE TITLE
Egress gateway doesn't work

### ISSUE THREAD

**Issue by nnk-khang-nguyen** [istio/istio#23100]
We have deployed istio version 1.5 with helm on Google Kubernetes Engine, follow the instructions here https://istio.io/docs/setup/install/helm/ and deploy demo profile to get egress gateway. But it does not work as documentation.

After deployment I have followed the instructions here:
https://istio.io/docs/tasks/traffic-management/egress/egress-control/. I have taken step:
**Controlled access to external services > Change to the blocking-by-default policy**
```
kubectl` get configmap istio -n istio-system -o yaml | sed 's / mode: ALLOW_ANY / mode: REGISTRY_ONLY / g' | kubectl replace -n istio-system -f -
configmap "istio" replaced
```
```
kubectl` exec -it $ SOURCE_POD -c sleep - curl -I https://www.google.com | grep "HTTP /"; kubectl exec -it $ SOURCE_POD -c sleep - curl -I https://edition.cnn.com | grep "HTTP /"
HTTP/2 200 
HTTP/2 200 
```
The result is:

> HTTP/2 200 
   HTTP/2 200 

instead of:
> command terminated with exit code 35
   command terminated with exit code 35

- This is my istio information:
```
kubectl -n istio-system get pods
istio-citadel-6ff47464c-lhx8t             1/1     Running     0          22h
istio-egressgateway-6c8fd9fcdb-4tnng      1/1     Running     0          22h
istio-galley-55f4df7fc8-dvwkz             1/1     Running     0          22h
istio-grafana-post-install-1.5.0-v6qz9    0/1     Completed   0          23h
istio-ingressgateway-65c86dd47b-rbbxf     1/1     Running     0          22h
istio-init-crd-all-1.5.0-h58wj            0/1     Completed   0          23h
istio-init-crd-mixer-1.5.0-kvzcq          0/1     Completed   0          23h
istio-pilot-7d8b5bccb4-5nw2r              2/2     Running     0          22h
istio-policy-8489c8478b-dhtbf             2/2     Running     0          22h
istio-security-post-install-1.5.0-d88q6   0/1     Completed   0          23h
istio-security-post-install-1.5.1-c4rxc   0/1     Completed   0          23h
istio-sidecar-injector-64cc49d9b4-25lqz   1/1     Running     0          22h
istio-telemetry-89d695b76-8vt2r           2/2     Running     0          23h
istio-telemetry-f699548d-qp47g            0/2     Pending     0          22h
istio-tracing-78c465f699-gknwr            1/1     Running     0          22h
kiali-dcdfdb4d-vl6mm                      1/1     Running     0          22h
prometheus-76c4c58b66-6s6s4               1/1     Running     0          22h

kubectl -n istio-system get svc
NAME                        TYPE           CLUSTER-IP    EXTERNAL-IP      PORT(S)                                                                                                                                      AGE
grafana                     ClusterIP      10.8.10.136   <none>           3000/TCP                                                                                                                                     23h
istio-citadel               ClusterIP      10.8.3.96     <none>           8060/TCP,15014/TCP                                                                                                                           23h
istio-egressgateway         ClusterIP      10.8.11.203   <none>           80/TCP,443/TCP,15443/TCP                                                                                                                     23h
istio-galley                ClusterIP      10.8.3.159    <none>           443/TCP,15014/TCP,9901/TCP                                                                                                                   23h
istio-ingressgateway        LoadBalancer   10.8.1.80     35.225.141.179   15020:30318/TCP,80:31380/TCP,443:31390/TCP,31400:31400/TCP,15029:30068/TCP,15030:31344/TCP,15031:32203/TCP,15032:31021/TCP,15443:31353/TCP   23h
istio-pilot                 ClusterIP      10.8.2.139    <none>           15010/TCP,15011/TCP,8080/TCP,15014/TCP                                                                                                       23h
istio-policy                ClusterIP      10.8.11.160   <none>           9091/TCP,15004/TCP,15014/TCP                                                                                                                 23h
istio-sidecar-injector      ClusterIP      10.8.6.249    <none>           443/TCP,15014/TCP                                                                                                                            23h
istio-telemetry             ClusterIP      10.8.14.11    <none>           9091/TCP,15004/TCP,15014/TCP,42422/TCP                                                                                                       23h
jaeger-agent                ClusterIP      None          <none>           5775/UDP,6831/UDP,6832/UDP                                                                                                                   23h
jaeger-collector            ClusterIP      10.8.14.208   <none>           14267/TCP,14268/TCP,14250/TCP                                                                                                                23h
jaeger-collector-headless   ClusterIP      None          <none>           14250/TCP                                                                                                                                    23h
jaeger-query                ClusterIP      10.8.2.115    <none>           16686/TCP                                                                                                                                    23h
kiali                       ClusterIP      10.8.5.219    <none>           20001/TCP                                                                                                                                    23h
prometheus                  ClusterIP      10.8.14.158   <none>           9090/TCP                                                                                                                                     23h
tracing                     ClusterIP      10.8.11.180   <none>           80/TCP                                                                                                                                       23h
zipkin                      ClusterIP      10.8.11.194   <none>           9411/TCP                                                                                                                                     23h
```
- values-istio-demo.yaml:
```
# This is used to generate istio.yaml for minimal, demo mode.
# It is shipped with the release, used for bookinfo or quick installation of istio.
# Includes components used in the demo, defaults to alpha3 rules.
global:
  controlPlaneSecurityEnabled: false
  
  proxy:
    accessLogFile: "/dev/stdout"
    resources:
      requests:
        cpu: 10m
        memory: 40Mi

  disablePolicyChecks: false

  mtls:
    # Default setting for service-to-service mtls. Can be set explicitly using
    # destination rules or service annotations.
    enabled: false

sidecarInjectorWebhook:
  enabled: true
  # If true, webhook or istioctl injector will rewrite PodSpec for liveness
  # health check to redirect request to sidecar. This makes liveness check work
  # even when mTLS is enabled.
  rewriteAppHTTPProbe: false

pilot:
  autoscaleEnabled: false
  traceSampling: 100.0
  resources:
    requests:
      cpu: 10m
      memory: 100Mi

mixer:
  policy:
    enabled: true
    autoscaleEnabled: false
    resources:
      requests:
        cpu: 10m
        memory: 100Mi

  telemetry:
    enabled: true
    autoscaleEnabled: false
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
 
  adapters:
    stdio:
      enabled: true
 
grafana:
  enabled: true

tracing:
  enabled: true

kiali:
  enabled: true
  createDemoSecret: true

gateways:
  istio-ingressgateway:
    autoscaleEnabled: false
    resources:
      requests:
        cpu: 10m
        memory: 40Mi
    type: LoadBalancer #change to NodePort, ClusterIP or LoadBalancer if need be
    externalTrafficPolicy: Local #change to Local to preserve source IP or Cluster for default behaviour or leave commented out

  istio-egressgateway:
    enabled: true
    autoscaleEnabled: false
    resources:
      requests:
        cpu: 10m
        memory: 40Mi
```
- Google Kubernetes Engine version 1.14.10-gke.27
- Istio version 1.5
How to make egress work, I need it to manage outbound access. Please help me, thanks!
