### ISSUE TITLE
envoyfilter created in one namespace will impact other namespace

### ISSUE THREAD

**Issue by johnzheng1975** [istio/istio#23111]
**Bug description**
envoyfilter created in one namespace will impact other namespace

1 Created envoyfilter in vr namespace
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ef-vr-easytry
  namespace: vr
spec:
  filters:
  - listenerMatch:
      portNumber: 80
      listenerType: SIDECAR_OUTBOUND
      listenerProtocol: HTTP
    filterName: envoy.lua
    filterType: HTTP
    filterConfig:
      inlineCode: |
        function envoy_on_request(request_handle)
          request_handle:logInfo("******* enter envoy_on_request ef-vr")
          request_handle:headers():replace("x-hh-tenant-id","vr")
        end
```

2  The header will be added for ALL pods All namespace.
```
tryc2@ip-172-31-0-31:~$ k exec -ti jnginxll-76474cf48b-7pck7 -n ll -- curl web-service.default
Defaulting container name to jnginxll.
{
  "path": "/",
  "headers": {
    "host": "web-service.default",
...
    "x-hh-tenant-id": "vr",
... 

```

3  If I created another specific envoyfilter in ll namespace 
```
kind: EnvoyFilter
metadata:
  name: ef-ll-easytry
  namespace: ll
spec:
  filters:
  - listenerMatch:
      portNumber: 80
      listenerType: SIDECAR_OUTBOUND
      listenerProtocol: HTTP
    filterName: envoy.lua
    filterType: HTTP
    filterConfig:
      inlineCode: |
        function envoy_on_request(request_handle)
          request_handle:logInfo("******* enter envoy_on_request ef-ll")
          request_handle:headers():replace("x-hh-tenant-id","ll")
        end 
```

4 The test result is still not changed. It is as same as test result in step 2.

istio version： 1.3/ 1.4

**Comment by johnzheng1975** [comment]
Note that for below Envoyfilter (different type), it can work ONLY for this namespace
```
tryc2@ip-172-31-0-31:~/tutorial-istio-envoy-lua-filters/example-6-istio/bk_sidecar/b4$ cat efvr1.yaml 
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: efvr1
  namespace: vr
spec:
  workloadSelector:
    labels:
      app: jn2
  configPatches:
    # The first patch adds the lua filter to the listener/http connection manager
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_OUTBOUND
      listener:
        portNumber: 80
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.router"
    patch:
      operation: INSERT_BEFORE
      value: # lua filter specification
       name: envoy.lua
       config:
         inlineCode: |
           function envoy_on_request(request_handle)
             request_handle:logInfo("******* enter envoy_on_request ef-vr")
             request_handle:headers():replace("tenant_id","vr")
           end
```
