### ISSUE TITLE
ServiceEntry Endpoints are not updated

### ISSUE THREAD

**Issue by yann-soubeyrand** [istio/istio#23151]
**Bug description**

When adding an endpoint to a ServiceEntry, this endpoint is not propagated to the sidecar proxies.

**Expected behavior**

Updates to ServiceEntry endpoins should be propagated to the sidecar proxies.

**Steps to reproduce the bug**

Let's start with the following ServiceEntry:

```
apiVersion: "networking.istio.io/v1alpha3"
kind: "ServiceEntry"
metadata:
  name: "database-replicas"
spec:
  location: "MESH_EXTERNAL"
  hosts:
    - "database-replicas.external"
  ports:
    - name: "postgresql"
      protocol: "TCP"
      number: 5432
  endpoints:
    - address: "xxxxxxxxxxxxx-001.eu-west-1.rds.amazonaws.com."
      ports:
        postgresql: 5432
  resolution: "DNS"
```

`istioctl proxy-config endpoints proxy-name | grep 5432` shows the endpoint:

```
10.0.4.92:5432                  HEALTHY     OK                outbound|5432||database-replicas.external
```

Then add an endpoint to it:

```
apiVersion: "networking.istio.io/v1alpha3"
kind: "ServiceEntry"
metadata:
  name: "database-replicas"
spec:
  location: "MESH_EXTERNAL"
  hosts:
    - "database-replicas.external"
  ports:
    - name: "postgresql"
      protocol: "TCP"
      number: 5432
  endpoints:
    - address: "xxxxxxxxxxxxx-001.eu-west-1.rds.amazonaws.com."
      ports:
        postgresql: 5432
    - address: "xxxxxxxxxxxxx-002.eu-west-1.rds.amazonaws.com."
      ports:
        postgresql: 5432
  resolution: "DNS"
```

`istioctl proxy-config endpoints proxy-name | grep 5432` does not show the added endpoint:

```
10.0.4.92:5432                  HEALTHY     OK                outbound|5432||database-replicas.external
```

In istiod logs, we can however see that it should have been added (if I understand correctly):

```
2020-04-22T18:24:35.686114Z	info	ads	Push debounce stable[3] 1: 100.103254ms since last change, 100.103086ms since last push, full=false
2020-04-22T18:24:35.686219Z	info	ads	XDS:EDSInc Pushing:2020-04-22T18:22:26Z/2 Services:map[database-replicas.external:{}] ConnectedEndpoints:2
2020-04-22T18:24:35.686311Z	info	ads	Cluster init time 80.629µs 2020-04-22T18:22:26Z/2
```

Restarting istiod, `istioctl proxy-config endpoints proxy-name | grep 5432` shows the added endpoint:

```
10.0.4.92:5432                  HEALTHY     OK                outbound|5432||database-replicas.external
10.0.5.151:5432                 HEALTHY     OK                outbound|5432||database-replicas.external
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
❯ istioctl version --remote
client version: 1.5.1
control plane version: 1.5.1
data plane version: 1.5.1 (2 proxies)
```

```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-21T23:37:18Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-26T01:12:54Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

```
❯ helm version                                
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

**How was Istio installed?**

Istio was installed using the operator:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  labels:
    argocd.argoproj.io/instance: istio
  name: istio
  namespace: istio-system
spec:
  profile: default
```

**Environment where bug was observed (cloud vendor, OS, etc)**

The Kubernetes cluster is an AWS EKS cluster version 1.15 eks.1 using managed node groups.
