### ISSUE TITLE
Using DestinationRule subsets per RPC method instead of per service

### ISSUE THREAD

**Issue by lainra** [istio/istio#23163]
Hi everyone, I’m currently considering a design for Istio abstraction for microservices and wanted to hear your opinion about it, especially the feasibility with Istio.

The idea is to create DestinationRule subset and VirtualService destination per RPC method instead of per service.

This would define the atomicity of a service down to RPC method instead of the service itself. Since a service has several RPC methods, the idea is to define different circuit breaking policies per RPC method. On top of that, defining different versions of these APIs with different subsets. It seems doable at Envoy-layer by defining clusters per method but the Istio DestinationRule approach isn't straightforward for this use case.

I didn’t find any use cases on the Internet, documentations and GitHub about this approach, which should show that either:
- This is a revolutionary approach
- This is too weird to be considered
- I didn’t search well enough

All approaches are mostly basic version subsetting at a service (pod) level.

My main concern is when m service has n RPC methods, p versions, one service will result in O(n*m) subsets and TrafficPolicies, and O(n*m*p) subsets, instead of O(m*p) with a standard service approach, also m is the biggest scale factor when going over 100+ (micro)services.

Could you give your opinion regarding this use case? Would really appreciate the help! :bow:

A possible implementation of a VirtualService and DestinationRule would look like below:

```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: echo-service
  namespace: echo-service
spec:
  hosts:
    - grpc-dev.echo-service.svc.cluster.local
  http:
    - name: "/platform.echoservice.v1.Greeter/SayHello"
      match:
        - headers:
            path:
              exact: "/platform.echoservice.v1.Greeter/SayHello"
      route:
        - destination:
            host: grpc-dev.echo-service.svc.cluster.local
            subset: "platform-echoservice-v1-greeter-sayhello"
      retries:
        attempts: 1
        perTryTimeout: 3s
        retryOn: "internal,unavailable"
    - name: "/platform.echoservice.v1.Greeter/SayMorning"
      match:
        - headers:
            path:
              exact: "/platform.echoservice.v1.Greeter/SayMorning"
      route:
        - destination:
            host: grpc-dev.echo-service.svc.cluster.local
            subset: "platform-echoservice-v1-greeter-saymorning"
      retries:
        attempts: 0
    - name: "/platform.echoservice.v2.Greeter/SayHello"
      match:
        - headers:
            path:
              exact: "/platform.echoservice.v2.Greeter/SayHello"
      route:
        - destination:
            host: grpc-dev.echo-service.svc.cluster.local
            subset: "platform-echoservice-v2-greeter-sayhello"
      retries:
        attempts: 1
        perTryTimeout: 3s
        retryOn: "internal,unavailable"
    - name: "/platform.echoservice.v2.Greeter/SayMorning"
      match:
        - headers:
            path:
              exact: "/platform.echoservice.v2.Greeter/SayMorning"
      route:
        - destination:
            host: grpc-dev.echo-service.svc.cluster.local
            subset: "platform-echoservice-v2-greeter-saymorning"
      retries:
        attempts: 0
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: echo-service
  namespace: echo-service
spec:
  host: grpc-dev.echo-service.svc.cluster.local
  subsets:
    - name: "platform-echoservice-v1-greeter-sayhello"
      version: v1
      trafficPolicy:
        connectionPool:
          http:
            http1MaxPendingRequests: 1000
            http2MaxRequests: 1000
        outlierDetection:
          consecutiveGatewayErrors: 1000
          consecutive5xxErrors: 1000
          interval: 10s
          baseEjectionTime: 10s
          maxEjectionPercent: 100
    - name: "platform-echoservice-v1-greeter-saymorning"
      version: v1
      trafficPolicy:
        connectionPool:
          http:
            http1MaxPendingRequests: 10
            http2MaxRequests: 10
        outlierDetection:
          consecutiveGatewayErrors: 10
          consecutive5xxErrors: 10
          interval: 5s
          baseEjectionTime: 10s
          maxEjectionPercent: 100
    - name: "platform-echoservice-v2-greeter-sayhello"
      version: v2
      trafficPolicy:
        connectionPool:
          http:
            http1MaxPendingRequests: 1000
            http2MaxRequests: 1000
        outlierDetection:
          consecutiveGatewayErrors: 1000
          consecutive5xxErrors: 1000
          interval: 10s
          baseEjectionTime: 10s
          maxEjectionPercent: 100
    - name: "platform-echoservice-v2-greeter-saymorning"
      version: v2
      trafficPolicy:
        connectionPool:
          http:
            http1MaxPendingRequests: 10
            http2MaxRequests: 10
        outlierDetection:
          consecutiveGatewayErrors: 10
          consecutive5xxErrors: 10
          interval: 5s
          baseEjectionTime: 10s
          maxEjectionPercent: 100
---
```
