### ISSUE TITLE
xff not work on https port

### ISSUE THREAD

**Issue by erdun** [istio/istio#23170]
**Bug description**

https://github.com/istio/istio/wiki/EnvoyFilter-Samples
EnvoyFilter-Samples 

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: xff
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: ANY
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager"
          use_remote_address: true
          xff_num_trusted_hops: 1

```

https port not works

HTTP filters:
![image](https://user-images.githubusercontent.com/16429864/80079491-f02dd680-8582-11ea-802b-787137f95bb6.png)

https filters:
![image](https://user-images.githubusercontent.com/16429864/80079142-77c71580-8582-11ea-8906-0386911efdf1.png)

**Expected behavior**

Get `xff` passby https port

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

client version: 1.5.0
control plane version: 1.5.0
data plane version: 1.5.0

kubenetes: v1.15.2

**How was Istio installed?**

istioclt upgrade
