### ISSUE TITLE
istioctl install in non istio-system namespace having a broken PodDisruptionBudget

### ISSUE THREAD

**Issue by erks** [istio/istio#23218]
**Bug description**

When installing istio using `istioctl manifest` command in a non istio-system namespace, some PDB resources (e.g. istio-ingress, istio-egress) are not matching any pods due to mismatching label selectors. 

This is due to:
- https://github.com/istio/istio/blob/811b5d365613b65fca3222bc1234dc9f917a9e1a/manifests/charts/gateways/istio-ingress/templates/poddisruptionbudget.yaml#L10
- https://github.com/istio/istio/blob/811b5d365613b65fca3222bc1234dc9f917a9e1a/manifests/charts/gateways/istio-ingress/templates/deployment.yaml#L27-L31

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

```
istioctl manifest generate --set values.global.istioNamespace=istio-test > test.yaml
```

Should generate `PodDisruptionBudget` resource for `istio-ingressgateway` deployment with matching selector to that of `istio-ingressgateway` deployment pod spec.

**Steps to reproduce the bug**

- Run `istioctl manifest generate --set values.global.istioNamespace=istio-test > test.yaml`
- Examine `istio-ingressgateway` deployment and poddisruptionbudget resources in `test.yaml`

```
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ingressgateway
  namespace: istio-test
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    
    release: istio
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
      
      release: istio
```

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
  name: istio-ingressgateway
  namespace: istio-test
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: istio-ingressgateway
        istio: ingressgateway
        service.istio.io/canonical-name: istio-ingressgateway
        service.istio.io/canonical-revision: "1.5"
    spec:
... <the rest of pod spec>
```

Note that the deployment template label is:
```
      labels:
        app: istio-ingressgateway
        istio: ingressgateway
        service.istio.io/canonical-name: istio-ingressgateway
        service.istio.io/canonical-revision: "1.5"
```
while pdb selector is:
```
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
      
      release: istio
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
> istioctl -i istio-test version --remote
client version: 1.5.1
control plane version: 1.5.1
data plane version: 1.5.1 (4 proxies)
> kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5", GitCommit:"0e9fcb426b100a2aea5ed5c25b3d8cfbb01a8acf", GitTreeState:"clean", BuildDate:"2019-08-05T09:21:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.12-eks-eb1860", GitCommit:"eb1860579253bb5bf83a5a03eb0330307ae26d18", GitTreeState:"clean", BuildDate:"2019-12-23T08:58:45Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

`istioctl manifest generate` then `kubectl apply`

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS EKS
