### ISSUE TITLE
Gateway StatefulSet GRPC Proxy not work

### ISSUE THREAD

**Issue by xiaoxi1989** [istio/istio#23224]
**Bug description**
StatefulSet GRPC Port use istiogateway proxy failed.

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: cxxtest-entry
  namespace: cxxtest
spec:
  endpoints:
  - address: cxxtest-2.cxxtest.cxxtest.svc.cluster.local
    ports:
      grpc: 9192
  - address: cxxtest-1.cxxtest.cxxtest.svc.cluster.local
    ports:
      grpc: 9192
  - address: cxxtest-0.cxxtest.cxxtest.svc.cluster.local
    ports:
      grpc: 9192
  hosts:
  - cxxtest.cxxtest.svc.cluster.local
  location: MESH_INTERNAL
  ports:
  - name: grpc
    number: 9192
    protocol: GRPC
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: cxxtest
  namespace: asset
spec:
  gateways:
  - cxxtest
  hosts:
  - 'cxxtest.cxxtest.svc.cluster.local'
  http:
  - math:
    - uri:
        regex: ".+"
    route:
    - destination:
        host: cxxtest.cxxtest.svc.cluster.local
        port:
          number: 9192
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: cxxtest
  namespace: cxxtest
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - 'cxxtest.cxxtest.svc.cluster.local'
    port:
      name: grpc
      number: 80
      protocol: HTTP
```
Did I do something wrong？

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
client version: 1.5.1
control plane version: 1.5.1
data plane version: 1.5.1 (3 proxies)
```
**How was Istio installed?**
istioctl daemon

**Environment where bug was observed (cloud vendor, OS, etc)**
Centos 7.6
Kubernetes 1.7
