### ISSUE TITLE
istio-system/ingressgateway name changed to istio-system/istio-ingressgateway in 1.5.2

### ISSUE THREAD

**Issue by cameronbraid** [istio/istio#23225]
I had deployed virtualservices like the following that worked with istio 1.5.1

```
...
spec:
  gateways:
  - istio-system/ingressgateway
...
```

however the `ingressgateway` name has been changed to `istio-ingressgateway` meaning I have to update all of my virtual services

This should be explicitly highlighted in the release notes

**Comment by hzxuzhonghu** [comment]
Not sure i understand you right. The vs's gateway specifies the gateway name. And the gateway(I mean the api object here) is created by yourself.

**Comment by cameronbraid** [comment]
I deploy istio with
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:

  values:

   ...

    gateways:
      istio-ingressgateway:
        tls: true
        autoscaleEnabled: false
        replicaCount: 1
        type: ClusterIP
        # type: NodePort
        # externalTrafficPolicy: Local
        sds:
          enabled: true
...
```

And the gateway that is deployed form this is the gateway I am using.

**Comment by hzxuzhonghu** [comment]
IC, not an expert on operator. @howardjohn may help

**Comment by nairb774** [comment]
Is it related to #22737 and https://github.com/istio/istio/commit/022c2ee467a207bdd4bdcd27c51547b0e36094e2?

**Comment by rvennam** [comment]
If you upgrade Istio 1.4 to 1.5.2, it now has both Gateways:
```
~/istio-1.5.2/bin 🏎  $ k get gateways -n istio-system
NAME                               AGE
ingressgateway                     3m20s
istio-ingressgateway               15s
istio-multicluster-egressgateway   3m20s
```

@morvencao

**Comment by morvencao** [comment]
Currently we can deploy gateways with:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
      - name: istio-ingressgateway # name of ingress gateway
        enabled: true
```

the name of ingress gateway can be specified in istio operator api.
