### ISSUE TITLE
Question: is it possible to use Istio as a reverse proxy? (similar to nginx proxy_pass)

### ISSUE THREAD

**Issue by illidan80** [istio/istio#23298]
I running on AWS + EKS + Istio, and I using AWS Elasticsearch Service for logging. By default, AWS Kibana is not exposed to the Internet, and in order to do that they [propose three approaches](https://aws.amazon.com/premiumsupport/knowledge-center/kibana-outside-vpc-cognito-elasticsearch/). One of the approaches is to deploy a dedicated Nginx to serve as a reverse proxy, which will pass traffic to the Kibana.

I wondering, since I already have Istio, maybe I can save from redundant Nginx deployment and just use Istio traffic management capabilities.

I want to navigate from the Internet to URL https://logs.myproduct.net, traffic will arrive to Istio gateway, it will terminate SSL and then establish connection to the Kibana and pass the traffic.

In order to do that, I created a virtual service:

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kibana-proxy
  namespace: myproduct
spec:
  hosts:
  - "logs.myproduct.net"
  gateways:
  - myproductgateway
  http:
    - route:
      - destination:
          port:
            number: 443
          host: vpc-xxxxxx.amazonaws.com
```

I getting 503. 

Is it possible to do what I intending for or I completely not in the right direction?
