### ISSUE TITLE
Two Version of apiVersion Declared in istio-ca-plugin-certs.yaml

### ISSUE THREAD

**Issue by garystafford** [istio/istio#2330]
The current v0.4.0 version of `/istio-0.4.0/install/kubernetes/istio-ca-plugin-certs.yaml` has two entires for `apiVersion` in the Deployment section.

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-ca-service-account
  namespace: istio-system
---
apiVersion: v1 # <--- first apiVersion
kind: Deployment
apiVersion: extensions/v1beta1 # <--- second apiVersion
metadata:
  name: istio-ca
  namespace: istio-system
  annotations:
    sidecar.istio.io/inject: "false"
```
