### ISSUE TITLE
Unexpected behavior when using 2 Gateways in different namespaces with the same host specified

### ISSUE THREAD

**Issue by kauana** [istio/istio#23318]
**Bug description**
Given `gateway1`:
```
 - hosts:                                                                                                                                                                                                                                                 
      - namespace-1/*.example.com                                                                                                                                                                                                                     
      port:                                                                                                                                                                                                                                                  
        name: https                                                                                                                                                                                                                                          
        number: 443                                                                                                                                                                                                                                          
        protocol: HTTPS                                               
      tls:                                                            
        credentialName: secret-1                
        mode: SIMPLE                
```

and `gateway2`:
```
 - hosts:                                                          
      - namespace-2/*.example.com             
      port:                                                           
        name: https                            
        number: 443                                                   
        protocol: HTTPS                                               
      tls:                                                            
        credentialName: secret-2
        mode: SIMPLE
```
and a virtual service for `app.example.com` in `namespace-2` that selects `gateway-2`. Then, when we send a request to `app.example.com`, we get a 404.





**Expected behavior**
When we send a request to `app.example.com` we expect that the correct gateway configuration takes affect (the cert from secret-2 is used in our example), and we ultimately reach our app.

**Steps to reproduce the bug**
1. Create resources as described above
2. Curl the application.

We suspect that it's not deterministic which gateway will take precedence, so if at first it doesn't fail as expected consider changing which gateway the virtualservice selects.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Istio version: 1.4.5
Kubectl version: 1.18.2

**How was Istio installed?**
With `istioctl manifest generate`

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE


cc: @XanderStrike @rosenhouse

**Comment by howardjohn** [comment]
What do your virtual services look like? I assume despite the overlapping wildcard in the gateways, each namespace will have unique virtual service hostnames? Otherwise its not clear how we can determine the certificate to use

**Comment by howardjohn** [comment]
not stale.

**Comment by howardjohn** [comment]
@kauana do you have more info about the exact VS? If I apply
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: "alpha"
  namespace: "default"
spec:
  selector:
    istio: ingressgateway
  servers:
  -
    hosts:
      - ns-1/*.example.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: sds-credential
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: "beta"
  namespace: "default"
spec:
  selector:
    istio: ingressgateway
  servers:
  -
    hosts:
      - ns-2/*.example.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: sds-credential
      mode: SIMPLE
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: default
  namespace: ns-1
spec:
  hosts:
  - "ns-1.example.com"
  gateways:
  - alpha
  tcp:
  - route:
    - destination:
        host: echo
```
 I get `warning envoy config    gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_8443: error adding listener '0.0.0.0:8443': filter chain '' has the same matching rules defined as ''` which is also an issue but a different one - but the same as https://github.com/istio/istio/issues/24638. I think this one might be a duplicate of that, or I misunderstood your config. let me know. THanks!
