### ISSUE TITLE
labels to user g/w in IstioOperator object doesn't work in 1.5

### ISSUE THREAD

**Issue by infa-ddeore** [istio/istio#23341]
**Bug description**
labels to user g/w in IstioOperator object doesn't work 

**Expected behavior**
g/w pod should get the provided labels in `IstioOperator` object (workaround is to use helm api overrides)

**Steps to reproduce the bug**

Generate manifest with below file:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: empty
  components:
    ingressGateways:
    - name: user-gateway
      enabled: true
      namespace: default 
      label:
        app: custom-user-gw
        istio: custom-user-gw
```

labels dont appear in g/w deployment, it takes the default labels, as per [document](https://istio.io/docs/reference/config/istio.operator.v1alpha1/#GatewaySpec) it should work
```
istioctl manifest generate -f /tmp/gw.yaml |grep "kind: Deployment" -A 30 |grep template: -A 5
  template:
    metadata:
      labels:
        app: istio-ingressgateway
        istio: ingressgateway
```

workaround is to use helm overrides 

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: empty
  components:
    ingressGateways:
    - name: user-gateway
      enabled: true
      namespace: default 

  values:
    gateways:
      istio-ingressgateway:
        labels:
          app: custom-user-gw-helm
          istio: custom-user-gw-helm
```

```
istioctl manifest generate -f /tmp/gw.yaml |grep "kind: Deployment" -A 30 |grep template: -A 5
  template:
    metadata:
      labels:
        app: custom-user-gw-helm
        istio: custom-user-gw-helm
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ istioctl version --remote
1.5.2

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:34Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
istioctl manifest generate | kubectl apply -f -

**Environment where bug was observed (cloud vendor, OS, etc)**
EKS, minikube
