### ISSUE TITLE
unable to run 1.5.2 on openshift 4.3.13

### ISSUE THREAD

**Issue by ryandawsonuk** [istio/istio#23375]
In the 1.5.x docs there's a [section on installing to openshift with the cni plugin that says it only applies for 1.4.x](https://istio.io/docs/setup/additional-setup/cni/#instructions-for-istio-1-4-x-and-openshift). But I see the initContainers fail with connection refused when running [the bookinfo sample](https://istio.io/docs/examples/bookinfo/) with the [privileges set for the namespace](https://istio.io/docs/setup/platform-setup/openshift/#privileged-security-context-constraints-for-application-sidecars) - the same as described in https://github.com/istio/istio/issues/21266

What I used to install istio 1.5.2 when getting the connection refused error was:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    cni:
      enabled: true
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
  values:
    cni:
      excludeNamespaces:
       - istio-system
       - kube-system
      logLevel: info 
```
(Applied with `istioctl manifest apply -f`.) 

So then I tried to install istio using [something similar to the 1.4.x settings](https://istio.io/docs/setup/additional-setup/cni/#instructions-for-istio-1-4-x-and-openshift) (but still on 1.5.2):
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    cni:
      enabled: true
      namespace: kube-system
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
  values:
    cni:
      chained: false
      cniBinDir: /var/lib/cni/bin
      cniConfDir: /etc/cni/multus/net.d
      cniConfFileName: istio-cni.conf
      excludeNamespaces:
       - istio-system
       - kube-system
      logLevel: debug 
    sidecarInjectorWebhook:
      injectedAnnotations:
        "k8s.v1.cni.cncf.io/networks": istio-cni
```
Then the bookinfo pods get stuck in initalizing with the error:
```
  Warning  FailedCreatePodSandBox  4s         kubelet, ip-10-0-164-206.eu-west-1.compute.internal  Failed create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_details-v1-78d78fbddf-wpsfl_bookinfo_fb6f83d6-7218-4335-a669-393d393e8c37_0(60059780d5ecf144be09dc7d9b644235448a1d31def4e315a4df262423fa9d5e): Multus: [bookinfo/details-v1-78d78fbddf-wpsfl]: error loading k8s delegates k8s args: TryLoadPodDelegates: error in getting k8s network from pod: GetNetworkDelegates: failed getting the delegate: getKubernetesDelegate: cannot find get a network-attachment-definition (istio-cni) in namespace (bookinfo): the server could not find the requested resource
```
This is openshift 4.3.13 (k8s 1.16.2). Issue seems to be specifically for namespaces where sidecar injection is enabled

**Comment by jwendell** [comment]
You need to follow the steps described here: https://istio.io/docs/setup/platform-setup/openshift/#additional-requirements-for-the-application-namespace

**Comment by ryandawsonuk** [comment]
Have just tried putting the `networkattachmentdefinition.k8s.cni.cncf.io/istio-cni` in the bookinfo namespace (which has sidecar injection on) with the first configuration above and in the bookinfo pods I still get:
```
in new validator: 10.131.0.47
Listening on 127.0.0.1:15001
Listening on 127.0.0.1:15006
Error connecting to 127.0.0.6:15002: dial tcp 127.0.0.1:0->127.0.0.6:15002: connect: connection refused
Error connecting to 127.0.0.6:15002: dial tcp 127.0.0.1:0->127.0.0.6:15002: connect: connection refused
```
Will try the second configuration.

**Comment by ryandawsonuk** [comment]
With the second configuration it works. Thanks!

**Comment by bharaththiruveedula** [comment]
@ryandawsonuk I have the same issue. What is the second configuration you were referring to?

**Comment by ryandawsonuk** [comment]
@bharaththiruveedula This one:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    cni:
      enabled: true
      namespace: kube-system
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
  values:
    cni:
      chained: false
      cniBinDir: /var/lib/cni/bin
      cniConfDir: /etc/cni/multus/net.d
      cniConfFileName: istio-cni.conf
      excludeNamespaces:
       - istio-system
       - kube-system
      logLevel: debug 
    sidecarInjectorWebhook:
      injectedAnnotations:
        "k8s.v1.cni.cncf.io/networks": istio-cni
```
