### ISSUE TITLE
contextPath not honored in client

### ISSUE THREAD

**Issue by Morriz** [istio/istio#23383]
The concept of `contextPath` is consistently used throughout the configuration for at least the following services:
- grafana
- prometheus
- tracing
- kiali

If we, as users wish to expose them behind one telemetry domain without separate ports,  the results are not as expected.

I would expect `https://$TELEMETRY_HOST/$SERVICE` to show a working service, but this does not work as the client charts are not properly wired with the contextPath (statics like js and css are not using the contextPath as base path).

Pointers to fix:

- grafana: https://github.com/istio/istio/issues/13279#issuecomment-485008091 (but it might be nicer to give the right helm chart value)
- prometheus: look at prometheus-operator doing it

**Comment by Morriz** [comment]
I managed to quick fix grafana in my `Kind: IstioOperator`:
```yaml
...
    spec:
      values:
        grafana:
          env:
            GF_SERVER_ROOT_URL: /grafana-istio/
          contextPath: '/grafana-istio'
...
```
And would love to see this possible for the other apps. Let's see...

**Comment by jamesthegiantpeach** [comment]
For prometheus you can set the —web.external-url in the server run command.

**Comment by joherma1** [comment]
After some digging, it worked for me but I had to override also the property `serve_from_sub_path`.

My final values.yaml in the `IstioOperator` was:
```yaml
...
spec:
  values:
    grafana:
      env:
        GF_SERVER_ROOT_URL: /grafana-istio/
        GF_SERVER_SERVE_FROM_SUB_PATH: true
      contextPath: '/grafana-istio'
...
```
