### ISSUE TITLE
Allow providing a Service endpoints from a ServiceEntry

### ISSUE THREAD

**Issue by yann-soubeyrand** [istio/istio#23387]
**Describe the feature request**

When adding a TCP ServiceEntry with DNS resolution, you need to provide a virtual IP on which Istio will create a listener, otherwise the listener will use 0.0.0.0 and will conflict with other ServiceEntry using the same port.

Service of type ClusterIP can already provide such virtual IP with the guarantee that it's unique cluster wide. The idea is to create a ClusterIP Service without selector (and thus no endpoints) and to create a ServiceEntry with the Service short name in the hosts array. Istio would then create listeners for the virtual IP and each port of the Service which matches a port of the ServiceEntry. These listeners would direct the traffic to the clusters created for the ServiceEntry.

Here are exemple Service and ServiceEntry:

```
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: database
spec:
  hosts:
    - database
  ports:
    - name: postgresql
      protocol: TCP
      number: 5432
  location: MESH_EXTERNAL
  endpoints:
    - address: database-1.example.com.
    - address: database-2.example.com.
  resolution: DNS
```

Istio would create a listener on the database Service ClusterIP and port 5432 load balancing traffic to database-1.example.com and database-2.example.com.

**Describe alternatives you've considered**

As a workaround, I create the following Service, ServiceEntry and VirtualService:

```
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: database
spec:
  hosts:
    - database.external
  ports:
    - name: postgresql
      protocol: TCP
      number: 5432
  location: MESH_EXTERNAL
  endpoints:
    - address: database-1.example.com.
    - address: database-2.example.com.
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: database
spec:
  hosts:
    - database
  tcp:
    - route:
        - destination:
            host: database.external
```

This does the trick but the VirtualService seems unnecessary and a listener is created for the ServiceEntry on 0.0.0.0:5432 which conflicts with other ServiceEntry created for other databases.

At least, the creation of a listener on 0.0.0.0 for a TCP ServiceEntry should be, IMHO, an opt in choice.

**Additional context**
