### ISSUE TITLE
idleTimeout does not apply to upstream TLS TCP proxied connections

### ISSUE THREAD

**Issue by cbarton** [istio/istio#23435]
**Bug description**
I've been experimenting with leveraging the mesh's ability for maintaining HTTP keep-alive for our `MESH_EXTERNAL` calls so we can push that responsibility away from the applications. 

During that investigation, I found that setting the `trafficPolicy.connectionPool.http.idleTimeout` works as expected for both TCP keep-alive and not for non-HTTPS traffic where envoy can do 
the TLS origination (or the traffic is HTTP).

When envoy is used as a TCP proxy when TLS is originated in the downstream, that setting does not apply and it falls back to the default of 60 minutes. Maybe I am missing where the documentation is, but the [envoy code](https://github.com/envoyproxy/envoy/blob/release/v1.12/source/common/tcp_proxy/tcp_proxy.cc#L559-L565) seems to indicate that this timeout is configurable like the http proxies would. 

It's also a bummer that they can't maintain a connection pool for these connections as that would reduce the complexity of maintaining them in the application, but that is out of scope from this issue (including it in case I missed something here as well).

**Expected behavior**
Setting `trafficPolicy.connectionPool.http.idleTimeout = 1m` should terminate an application that maintains an open TCP socket for longer than 1 minute.

**Steps to reproduce the bug**
Creating a `ServiceEntry`/`DestinationRule` for `https://foo.com:443` and setting `trafficPolicy.connectionPool.http.idleTimeout = 1m`:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: star-foo-com
spec:
  hosts:
    - "*.foo.com"
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: star-foo-com
spec:
  host: "*.foo.com"
  trafficPolicy:
    connectionPool:
      http:
        idleTimeout: 1m
```

Spin up a TCP keep-alive connection to that host:

```javascript
const tls = require('tls');
const socket = tls.connect(443, 'subdomain.foo.com', () => {
  console.log('onopen');
}); 
client.setKeepAlive(true);
socket.on('close', (e) => console.log('onclosed', e));
socket.on('error', (e) => console.log('onerr', e));
socket.on('data', (data) => console.log('ondata', data.toString()));
```

Wait for over a minute and verify that the socket is still in use (and will remain for 60min unless the remote server closes the connection, which is how we found out about the issue):

```
ss -iep dst <ip>:https
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
istioctl version --remote
client version: 1.4.6
control plane version: 1.4.6
data plane version: 1.4.6 (139 proxies)

 kubectl version
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-gke.5", GitCommit:"a5bf731ea129336a3cf32c3375317b3a626919d7", GitTreeState:"clean", BuildDate:"2020-03-31T02:49:49Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}

helm version
Server: &version.Version{SemVer:"v2.16.6", GitCommit:"dd2e5695da88625b190e6b22e9542550ab503a47", GitTreeState:"clean"}
```

**How was Istio installed?**
Via Helm with minimal configuration changes, outbound traffic policy is `ALLOW_ANY`.

**Environment where bug was observed (cloud vendor, OS, etc)**
We run on GKE, but we maintain the Istio install.
