### ISSUE TITLE
Regression: Kiali ingress no longer gets created

### ISSUE THREAD

**Issue by mitom** [istio/istio#23455]
**Bug description**
Kiali ingress no longer gets created when specifying the configuration as per the reference [docs](https://istio.io/docs/reference/config/installation-options/#kiali-options). The settings get validated, but the resource is no longer in the [chart template](https://github.com/istio/istio/tree/master/manifests/charts/istio-telemetry/kiali/templates) - I'm not familiar with the project, but I've found [another instance of this](https://github.com/istio/istio/tree/master/operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-telemetry/kiali/templates). I assume that's a duplicate for the helm/operator way respectively. This was previously part of the [chart](https://github.com/istio/istio/blob/1.4.8/install/kubernetes/helm/istio/charts/kiali/templates/ingress.yaml).

**Expected behavior**

Kiali ingress to be created when configured

**Steps to reproduce the bug**

1. Create a config file with
```
# config.yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  profile: minimal
  values:
    kiali:
      enabled: true
      ingress:
        enabled: true
        hosts:
          - kiali.test
```
2. Generate a manifest `istioclt manifest generate -f config.yaml`
3. Verify in the created manifest that there is no ingress resource for kiali

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
client version: 1.5.2
control plane version: 1.5.2
data plane version: 1.5.1 (14 proxies)
```

**How was Istio installed?**
istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
EKS
