### ISSUE TITLE
redis connection failing from nodejs app container to redis cache container in istio 

### ISSUE THREAD

**Issue by Invictus17** [istio/istio#23476]
Error:
```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to redis:6379 failed - connect ECONNREFUSED 10.102.3.79:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1142:16)
Emitted 'error' event on RedisClient instance at:
    at RedisClient.on_error (/app/node_modules/redis/index.js:406:14)
    at Socket.<anonymous> (/app/node_modules/redis/index.js:279:14)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:96:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '10.102.3.79',
  port: 6379
}
```
redis service:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    io.kompose.service: redis
status:
  loadBalancer: {}
```
