### ISSUE TITLE
Can't communicate to external TLS services after upgrade to 1.5.x

### ISSUE THREAD

**Issue by bernardoVale** [istio/istio#23489]
**Bug description**

Istio stopped all external TLS communications after upgrade from 1.4 to 1.5, it seems to be related to the new default `values.global.mtls.auto=true`. 

**Expected behavior**

I simple curl to any external URL to return a 200 response

```
root@helloworld-v2-85bc988875-6r79g:/opt/microservices# curl https://www.google.com
curl: (35) Unknown SSL protocol error in connection to www.google.com:443 
```

**Steps to reproduce the bug**

Upgrade cluster from 1.4.6 to 1.5.0 then to 1.5.2 with the following control plane config:

```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  profile: default
  addonComponents:
    grafana:
      enabled: true
    kiali:
      enabled: true
  components:
    citadel:
      enabled: true
    ingressGateways:
    - enabled: false
  values:
    global:
      logging:
        level: "default:info"
      proxy:
        accessLogFile: /dev/stdout
      # Utilizar caso tivermos um nodepool dedicado ao istio
      defaultNodeSelector:
        group: istio
      mtls:
        enabled: false
```

Access any sidecar injected pod and send a curl request to any external host that DOES NOT have a `ServiceEntry` associated.

The problem was fixed after changing:

```
values:
  mtls:
    auto: false
    enabled: false
```

Note that I'm not controlling egress traffic:

```
kubectl get configmap istio -n istio-system -o yaml | grep -o "mode: ALLOW_ANY"                      
mode: ALLOW_ANY
mode: ALLOW_ANY
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ istioctl version --remote
client version: 1.5.2
control plane version: 1.5.2
data plane version: 1.5.2 (11 proxies)

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T18:56:40Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-26T01:12:54Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**

Using `istioctl`

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS/EKS, Amazon Linux 2.

**Comment by howardjohn** [comment]
This seems like it might be related to https://github.com/istio/istio/issues/16458, although I don't think auto mtls would impact that? tl;dr is an http port on port 443 will break this. Its fixed in 1.6 but not 1.5. Can you try checking if you have the http port on 443? If not this may be a different issue

**Comment by mandarjog** [comment]
@incfly PTAL if it turns out *not to be* a port collision on 443.

**Comment by maflaven** [comment]
I'm seeing the same issue with 1.6.1 and the following config:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      proxy:
        tracer: zipkin # for use with jaeger
      controlPlaneSecurityEnabled: false
      disablePolicyChecks: true
      enableTracing: true
      mtls:
        auto: false
        enabled: false
      defaultNodeSelector:
        node_type: cpu
        spotinst.io/node-lifecycle: od
      outboundTrafficPolicy:
        mode: ALLOW_ANY
    certmanager:
      enabled: false
    gateways:
      enabled: true
      istio-ingressgateway:
        enabled: true
        serviceAnnotations: {} # TODO: add cert, http(s) annotations
      istio-egressgateway:
        enabled: false
    grafana:
      enabled: false # using separately maintained installation
    istio_cni:
      enabled: false
    kiali:
      enabled: true
      dashboard:
        auth:
          strategy: anonymous
        viewOnlyMode: true
        grafanaURL: https://grafana.arturo.ai
        grafanaInClusterURL: http://grafana.monitoring:80
        jaegerURL: '' # TODO: add public-facing URL
        jaegerInClusterURL: http://tracing/jaeger
      prometheusAddr: http://prometheus-operated.monitoring:9090
      security:
        enabled: false
    mixer:
      policy:
        enabled: false # if enabled, global.disablePolicyChecks has affect
      telemetry:
        enabled: true
    prometheus:
      enabled: false # using separately maintained installation
    tracing:
      enabled: true
      provider: jaeger
    pilot:
      traceSampling: 1.0 # 100%, suitable for a "low traffic mesh" https://istio.io/docs/tasks/observability/distributed-tracing/overview/#trace-sampling
```

@howardjohn @mandarjog what debug info can I give you?
