### ISSUE TITLE
Make Pod IPs addressable directly even in the mesh

### ISSUE THREAD

**Issue by markusthoemmes** [istio/istio#23494]
**Describe the feature request**

Istio's is a **Service** mesh, thus it loadbalances and routes mainly services. However, it has a couple of nice secondary features (like mTLS) that make it worthwhile using as well.

In Knative, we employ our own loadbalancing mechanisms to allow us to scale to and from zero efficiently and even more importantly: To implement the concurrency limits in our workload containers. To do that, we use our own loadbalancer that keeps track of the downstream capacity and only sends as many requests as are possible. To make this work in a distributed system, all loadbalancers get a sliced portion of the actual downstream servers, so they don't trample each others' state.

Secondarily, our autoscaler needs to scrape workload pods for metrics to do its job.

Both of these benefit **enormously** from being able to address pods directly by their IPs, however Istio doesn't support that when running in a mesh configuration today. Has it been considered to allow/implement this?

A few possible implementations that come to mind:
1. Respect the `x-envoy-original-dst-host` header.
2. Allow for host spoofing, where all potential mTLS etc. rules are applied via the `Host` header, while routing information from the IP is used if available (`curl -H "Host: serviceA" 1.2.3.4:8080` for example)

**Describe alternatives you've considered**

We've implemented various workarounds here. It'd be great to transparently allow this though to not have to specialcase mesh logic anymore.

[X] Networking
[X] Performance and Scalability
[X] User Experience

---

Sorry if this is a duplicate. I tried a couple of searches but haven't found anything related or anything stating it as explicitly.

**Comment by howardjohn** [comment]
> It'd be great to transparently allow this 

The challenge here is that most of our configuration is Service based, but pods are not 1:1 with Service. So we don't know if you send a `curl 1.2.3.4` which logic we should apply.

Can you use the PASSTHROUGH lb option? https://istio.io/docs/reference/config/networking/destination-rule/#LoadBalancerSettings-SimpleLB. It seems like that should get you at least a bit closer to what you are looking for

**Comment by markusthoemmes** [comment]
@howardjohn what about the provided examples though? Don't they both adress the pod/service disconnect?

**Comment by howardjohn** [comment]
I think it handles both of those, but I may be missing some details

> x-envoy-original-dst-host

I think this is more or less the same as the PASSTHROUGH lb except looking in the original request looking at the header? This might already work with PASSTHROUGH set, not 100% sure if it needs another setting.

> Allow for host spoofing, where all potential mTLS etc. rules are applied via the Host header, while routing information from the IP is used if available (curl -H "Host: serviceA" 1.2.3.4:8080 for example)

This sounds the same as PASSTHROUGH to me - perhaps I am missing some more details on the expected behavior here?

**Comment by markusthoemmes** [comment]
I guess the issue I see with PASSTHROUGH is that I kinda need to "original" loadbalancing to work as well.
Directly addressing the IP will only be done in certain cases (i.e. from the autoscaler or if we use "our" loadbalancing) and should not be enacted if requests are hitting the service specifically. It'd need to work per-client.

**Comment by howardjohn** [comment]
@markusthoemmes got it, that makes sense. I think you should be able to do this with some combination of subsets or similar. Have some VS that matches "x-knative-passthrough: true" header or whatever that forwards to a subset with PASSTHROUGH, and then non-match just to the default subset

**Comment by ramaraochavali** [comment]
@markusthoemmes We do similar to what @howardjohn suggested above to get the pod->pod work with a special subset called "direct"  with PASSTHROUGH LB and control it via some header to match in the VS. See https://discuss.istio.io/t/503-between-pod-to-pod-communication-1-5-1/6121/15 for complete information. 

`x-envoy-original-dst-host` - Does not work by default even for PassThrough clusters.  We need to set "use_http_header" specifically to enable that feature in the original dst lb config https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#config-cluster-v3-cluster-originaldstlbconfig

**Comment by markusthoemmes** [comment]
YAY, so I had some level of success with this, but PASSTHROUGH loadbalancing seems to not interact nicely with mTLS setup and AuthorizationPolicy.

Here's the reproducer/information:

## Istio setup

Istio setup looks like this, most important here is the `outboundTrafficPolicy` and the enabled sidecar injection

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      proxy:
        autoInject: enabled
      useMCP: false
      # The third-party-jwt is not enabled on all k8s.
      # See: https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens
      jwtPolicy: first-party-jwt
    pilot:
      autoscaleMin: 3
      autoscaleMax: 10
      cpu:
        targetAverageUtilization: 60
    gateways:
      istio-ingressgateway:
        autoscaleMin: 2
        autoscaleMax: 5
    sidecarInjectorWebhook:
      rewriteAppHTTPProbe: true

  meshConfig:
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
    accessLogFile: /dev/stdout
    defaultConfig:
      proxyMetadata:
        TERMINATION_DRAIN_DURATION_SECONDS: "20"

  addonComponents:
    pilot:
      enabled: true
    prometheus:
      enabled: false

  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          resources:
            limits:
              cpu: 3000m
              memory: 2048Mi
            requests:
              cpu: 1000m
              memory: 1024Mi
```

## App under test

The app under test has 2 ports, 8012 and 9090 and I want to be able to reach its pods via IP. It's deployed into the `test` namespace to test namespace differences too.

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: test
  labels:
    app: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: nginx
        image: docker.io/markusthoemmes/istio-direct-3e0eb0945cd0350fc4e0bca82c310cfe@sha256:02be3c98f2210003f69299875a7d9094857cb2ea770dc3664071d18327d2c18e
        ports:
        - name: http
          containerPort: 8012
        - name: http-autometric
          containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: test
spec:
  type: ClusterIP
  selector:
    app: server
  ports:
  - name: http
    protocol: TCP
    port: 8012
    targetPort: http
  - name: http-autometric
    protocol: TCP
    port: 9090
    targetPort: http-autometric
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: server
  namespace: test
spec:
  host: server.test.svc.cluster.local
  subsets:
  - name: normal
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
  - name: direct
    trafficPolicy:
      loadBalancer:
        simple: PASSTHROUGH
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: server
  namespace: test
spec:
  hosts:
  - server.test.svc.cluster.local
  http:
  - match:
    - headers:
        use-direct:
          exact: "true"
    route:
    - destination:
        host: server.test.svc.cluster.local
        subset: direct
  - route:
    - destination:
        host: server.test.svc.cluster.local
        subset: normal
---
```

## Tester

The tester is just an app that has a server (so the pod sticks around) and `curl` installed so I can actually test stuff. It's deployed to the default namespace.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: nginx
        image: registry.svc.ci.openshift.org/openshift/knative-v0.17.3:knative-serving-test-helloworld
```

---

With all of these applied, pod addressability works "like a charm" with one caveat: I found that the ports of the service **need** to match the ports on the pod. An `80 -> 8012` translation did not work for me.

A curl like this now works `curl $IP:8012 -H "Host: server.test" -H "use-direct: true"`. YAY! I was also able to make this work in Knative end-to-end so that's a big win right here!

Now mTLS and AuthorizationPolicy... Not so good yet.

## AuthorizationPolicy

With the above setup, we apply a Policy like this:

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-all
  namespace: test
spec:
  {}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-namespaces
  namespace: test
spec:
  action: ALLOW
  rules:
  - from:
    - source:
       namespaces: ["default"]
```

So I should be able to curl from the pod in default. `curl server.test:8012` works fine but `curl -v $IP:8012 -H "Host: server.test" -H "use-direct: true"` yields a 403: RBAC: access denied.

## mTLS

With the above setup, we apply mTLS setup like this:

```yaml
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "mtls-services"
  namespace: "test"
spec:
  host: "*.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
  namespace: "istio-system"
spec:
  mtls:
    mode: STRICT
---
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
  namespace: "test"
spec:
  mtls:
    mode: STRICT
---
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
  namespace: "default"
spec:
  mtls:
    mode: STRICT
```

And again, with `curl server.test:8012` this works fine, but `curl -v $IP:8012 -H "Host: server.test" -H "use-direct: true"` yields a 503: upstream connect error or disconnect/reset before headers. reset reason: connection termination.

HALP! :joy: Am I doing something wrong here? The `80 -> 8012` port not working made me suspicious that I'm not correctly hooked into the istio config or something but I'm somewhat lost.

**Comment by howardjohn** [comment]
What version of istio is this? It actually works for me. I suspect the issue is auto mtls worked poorly for older versions with headless/passthrough services. Your `mtls-services` does not kick in since the `server` Dr has precedence and there is no merging.

I would suspect if you upgrade OR add the tls settings to the `server` DR it would work. I suspect if you look at envoy config, `outbound|8092|direct|server.test.svc.cluster.local` does not have transport_socket

**Comment by markusthoemmes** [comment]
@howardjohn thanks a ton for your help this far! I"m **almost** there!

Using the following setup, I get errors like

```
upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
```

If the receiving end has no sidecars injected but the sending container has. I've googled this a bit of course and seemingly this should've been fixed as of https://github.com/istio/istio/pull/26486 and surely enough, it works if I don't use the direct (PASSTHROUGH) loadbalancer:

```
$ curl -H "Host: server.test" 10.244.0.12:8012
Listening on 8012: bar 10.244.0.11
```

Using the PASSTHROUGH loadbalancer yields:

```
$ curl -H "Host: server.test" -H "use-direct: true" 10.244.0.12:8012
upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
```

So I'm guessing the filter implementation is somehow bypassed by using a PASSTHROUGH LB? Any insights?

# Reproducer

## Istio setup (Istio v1.8.2)

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      proxy:
        autoInject: enabled
        clusterDomain: cluster.local
      useMCP: false
      # The third-party-jwt is not enabled on all k8s.
      # See: https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens
      jwtPolicy: first-party-jwt
    pilot:
      autoscaleMin: 1
      autoscaleMax: 3
      cpu:
        targetAverageUtilization: 60
    gateways:
      istio-ingressgateway:
        autoscaleMin: 1
        autoscaleMax: 3
        type: NodePort
    sidecarInjectorWebhook:
      rewriteAppHTTPProbe: true

  meshConfig:
    defaultConfig:
      proxyMetadata:
        TERMINATION_DRAIN_DURATION_SECONDS: "20"

  addonComponents:
    pilot:
      enabled: true

  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
```

## mTLS setup

```yaml
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
  namespace: "istio-system"
spec:
  mtls:
    mode: STRICT
```

Tester and app-under-test are the same as above, but app-under-test has the sidecar injection label turned off.

**Comment by howardjohn** [comment]
There is this commit: 50643368c2 "Do not enable auto mtls when cluster type is `Cluster_ORIGINAL_DST". But its not really disabling auto mtls; its instead making it so its *always* mtls because we don't hit this code (https://github.com/istio/istio/blob/82166afcb050de623e70757dfbe6acf9864d66df/pilot/pkg/networking/core/v1alpha3/cluster.go#L882) but we have already set transport socket at this point.

Looks like it might have worked at some point (where "worked" is a bit of a stretch - it just never sent TLS, even if the backend had a sidecar), but then been reverted by https://github.com/istio/istio/commit/165c5ccd74e319eff194cd13fddfeefa2c027d09.

The problem is https://github.com/istio/istio/blob/4d82810481d20d05ac00f5c6378a9236ead943f7/pilot/pkg/model/push_context.go#L1803 doesn't take the destination rule into account.

I hacked together a fix: https://github.com/istio/istio/compare/master...howardjohn:pilot/auto-mtls-passthrough-dr?expand=1.

One caveat - if there is a mixed workload (some with sidecar some without) we will downgrade to plaintext. not much we can do about this.

@incfly @hzxuzhonghu let me know what you think.

**Comment by howardjohn** [comment]
Also in the short term if you know the pods have no sidecars, you can do it explicitly:
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: server
spec:
  host: echo
  subsets:
  - name: normal
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
  - name: direct
    trafficPolicy:
      loadBalancer:
        simple: PASSTHROUGH
      tls:
        mode: DISABLE
```

that will work today.
