### ISSUE TITLE
It seems envoy filter grpc_http1_reverse_bridge does not apply.

### ISSUE THREAD

**Issue by sp-manuel-jurado** [istio/istio#23509]
**It seems envoy filter grpc_http1_reverse_bridge does not apply.**

It seems envoy filter grpc_http1_reverse_bridge does not apply.
This is a filter that enables converting an incoming gRPC request into a HTTP/1.1 request to allow a server that does not understand HTTP/2 or gRPC semantics to handle the request.

Error received:
```
grpcurl -v \
-proto ../proto/SP/Rpc/ping_service.proto \
-plaintext \
-import-path ../proto \
-d '{}' \
dns-xxx:80 \
sp.rpc.PingService/Ping

Resolved method descriptor:
rpc Ping ( .google.protobuf.Empty ) returns ( .google.protobuf.Empty );

Request metadata to send:
(empty)

Response headers received:
content-type: application/grpc+proto
date: Mon, 04 May 2020 19:36:50 GMT
server: istio-envoy
x-envoy-upstream-service-time: 17

Response trailers received:
(empty)
Sent 1 request and received 0 responses
ERROR:
  Code: Internal
  Message: server closed the stream without sending trailers
```

**Expected behavior**
```
grpcurl -v \
-proto ./proto/SP/Rpc/ping_service.proto \
-plaintext \
-import-path ./proto \
-d '{}' \
localhost:10000 \
sp.rpc.PingService/Ping

Resolved method descriptor:
rpc Ping ( .google.protobuf.Empty ) returns ( .google.protobuf.Empty );

Request metadata to send:
(empty)

Response headers received:
content-type: application/grpc
date: Mon, 04 May 2020 20:03:33 GMT
server: envoy
x-envoy-upstream-service-time: 0

Response contents:
{

}

Response trailers received:
(empty)
Sent 1 request and received 1 response
```

**Steps to reproduce the bug**
- https://github.com/sp-manuel-jurado/istio-grpc-http1-reverse-bridge/tree/master/kubernetes

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
istioctl version --remote
client version: 1.5.2
control plane version: 1.5.2
data plane version: 1.5.2 (7 proxies)
```

**How was Istio installed?**
```
~ istioctl manifest apply --set addonComponents.prometheus.enabled=false --set profile=default
...
~ kubectl label namespace lab-test istio-injection=enabled --overwrite
```

**Notes**
Proto definition:
```
syntax = "proto3";

package sp.rpc;

import "google/protobuf/empty.proto";

service PingService {
    rpc Ping(google.protobuf.Empty) returns (google.protobuf.Empty);
}
```

 Curl http1.1 (simulating envoy call applying reverse bridge filter)
```
curl -v http://...:80/sp.rpc.PingService/Ping
*   Trying ...
* TCP_NODELAY set
* Connected to ... port 80 (#0)
> GET /sp.rpc.PingService/Ping HTTP/1.1
> Host: ...
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< content-type: application/grpc+proto
< date: Mon, 04 May 2020 20:16:01 GMT
< x-envoy-upstream-service-time: 1
< server: istio-envoy
< transfer-encoding: chunked
<
* Connection #0 to host ... left intact
```

HTTP server used in grpc-http service:
- https://github.com/sp-manuel-jurado/istio-grpc-http1-reverse-bridge/blob/master/services/ping-http/main.go

Envoy config used to get the expected behaviour:
- https://github.com/sp-manuel-jurado/istio-grpc-http1-reverse-bridge/blob/master/services/ping-http/envoy.yaml

Thank you so much

**Comment by sp-manuel-jurado** [comment]
Could it be related to this fix: https://github.com/istio/istio/pull/23030 ?

**Comment by sp-manuel-jurado** [comment]
Although it is in the repository that I added above, this is the filter spec:

```
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: lab-test
  namespace: lab-test
spec:
  workloadSelector:
    labels:
      app: ping-http
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          portNumber: 8888 # ping-http svc port named http
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
              subFilter:
                name: "envoy.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.grpc_http1_reverse_bridge
          typed_config:
            "@type": type.googleapis.com/envoy.config.filter.http.grpc_http1_reverse_bridge.v2alpha1.FilterConfig
            content_type: application/grpc+proto
            withhold_grpc_frames: true
```

**Comment by sp-manuel-jurado** [comment]
Finally, It seems, I got to inject correctly, using the deprecated API:
```
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ping-http-reverse-bridge
  namespace: lab-test
spec:
  workloadLabels:
    app: ping-http
  filters:
    - listenerMatch:
        portNumber: 8888
        listenerType: SIDECAR_INBOUND
        listenerProtocol: HTTP
      filterName: envoy.filters.http.grpc_http1_reverse_bridge
      filterType: HTTP
      filterConfig:
        contentType: application/grpc+proto
        withholdGrpcFrames: true
```

But related to the protocol selection: https://istio.io/docs/ops/configuration/traffic-management/protocol-selection/
I guess is a special case:
- The upstream only understand http1.1 with protocol buffers.
- The client makes the call in grpc/http2 -> envoy transform it in http1.1 with the filter -> upstream http1.1 responding with headers "content-type/grpc+proto" so that envoy understand it to transform the stream back in grpc/http2 again.

I played changing the name of the service port between tcp/http/grpc but I didn't get the expected behaviour.
