### ISSUE TITLE
"istioctl x authz check" output

### ISSUE THREAD

**Issue by esnible** [istio/istio#23526]
The `istioctl x authz check` is underdocumented and the output may be incorrect.

The output is a report with four columns.  The meaning of each column is unclear.  As an enhancement, the `Long:` description for `check` should define what appears in each column.

The output of the CERTIFICATE column is sometimes `noneSDS: default` and I do not know what that means.  Seems like a bug.

If I deploy the AuthorizationPolicy below the output of the "AuthZ (RULES)" column is, in one case, `yes (1: ns[default]-policy[integ-test]-rule[0])`.  This seems to mean there is a v1beta1.AuthorizationPolicy, named integ-test, and the 0th rule applies to a listener.  Seems confusing.  I'd rather see the column named "AuthorizationPolicy" and the value be "integ-test.default rule #0".  Maybe someone on security can give a better idea of what the value should be, but `ns[default]` is not a good way to say the "default" namespace".

To reproduce, deploy Bookinfo, and add a policy:
```
kubectl apply -f - <<EOF
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: integ-test
 namespace: default
spec:
 rules:
 - from:
   - source:
       principals: ["cluster.local/ns/default/sa/sleep"]
   to:
   - operation:
       methods: ["GET"]
   when:
   - key: request.headers[version]
     values: ["v1", "v2"]
EOF
```

cc @howardjohn who pointed out part of this in https://github.com/istio/istio/pull/23502#discussion_r419775071
