### ISSUE TITLE
Circuit Breaking does not take effect for grpc service

### ISSUE THREAD

**Issue by lcx102737** [istio/istio#23527]
**Bug description**
I start a grpc server and client and set up a circuit breaker,the circuit breaker did not take effect.

Version
1.0.5

Cluster state
On kubernetes 1.12

server.yaml
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grpc-test-jbh-master-default-1234
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: grpc-test-jbh-master-default-1234
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grpc-test-jbh-master-default-1234
        version: 2020.04.27-15.23.12
    spec:
      containers:
      - image: xxxxxxx
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 15
        livenessProbe:
          failureThreshold: 5
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 50051
          timeoutSeconds: 1
        name: grpc-test-jbh-master-default-1234
        ports:
        - containerPort: 8080
          name: grpc-0
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 50051
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 100Gi
            memory: 512Mi
          requests:
            cpu: 100m
            ephemeral-storage: 2Gi
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        env: dev
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: schedule
        operator: Equal
        value: "no"
```
service yaml
```
apiVersion: v1
kind: Service
metadata:
  labels:
    service: grpc-test-jbh-master-default-1234
  name: grpc-test-jbh-master-default-1234
spec:
  ports:
  - name: grpc
    port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: grpc-test-jbh-master-default-1234
  sessionAffinity: None
  type: ClusterIP
```
client.yaml
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grpc-test-jbh-master-default
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: grpc-test-jbh-master-default
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grpc-test-jbh-master-default
        version: 2020.04.27-22.32.03
    spec:
      containers:
      - command:
        - /root/greeter_clinet
        - grpc-test-jbh-master-default-1234.default:50051
        image:xxxxxxxx
        imagePullPolicy: IfNotPresent
        name: grpc-test-jbh-master-default
        ports:
        - containerPort: 8080
          name: http-0
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 100Gi
            memory: 512Mi
          requests:
            cpu: 100m
            ephemeral-storage: 2Gi
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        env: dev
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: schedule
        operator: Equal
        value: "no"
```
DestinationRule
```
cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: grpc-test-jbh-master-default-1234
spec:
  host: grpc-test-jbh-master-default-1234
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 1
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
    outlierDetection:
      consecutiveErrors: 1
      interval: 1s
      baseEjectionTime: 3m
      maxEjectionPercent: 100
EOF
```
From the server's istio-proxy log, there is no statistical information about GRPC.Log as follows
```
kubectl exec grpc-test-jbh-master-default-1234-788675f94c-zthxz -c istio-proxy -- sh -c 'curl localhost:15000/stats' | grep grpc-test-jbh-master-default-1234 |grep pend
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0cluster.inbound|50051||grpc-test-jbh-master-default-1234.default.svc.cluster.local.upstream_rq_pending_active: 0
cluster.inbound|50051||grpc-test-jbh-master-default-1234.default.svc.cluster.local.upstream_rq_pending_failure_eject: 0
cluster.inbound|50051||grpc-test-jbh-master-default-1234.default.svc.cluster.local.upstream_rq_pending_overflow: 0
cluster.inbound|50051||grpc-test-jbh-master-default-1234.default.svc.cluster.local.upstream_rq_pending_total: 0
cluster.outbound|50051||grpc-test-jbh-master-default-1234.default.svc.cluster.local.upstream_rq_pending_active: 0
cluster.outbound|50051||grpc-test-jbh-master-default-1234.default.svc.cluster.local.upstream_rq_pending_failure_eject: 0
cluster.outbound|50051||grpc-test-jbh-master-default-1234.default.svc.cluster.local.upstream_rq_pending_overflow: 0
cluster.outbound|50051||grpc-test-jbh-master-default-1234.default.svc.cluster.local.upstream_rq_pending_total: 0
100 6514k    0 6514k    0     0  48.1M      0 --:--:-- --:--:-- --:--:-- 48.1M
cluster.outbound|50051||grpc-test-jbh-master-default-1234.dev.svc.cluster.local.upstream_rq_pending_active: 0
cluster.outbound|50051||grpc-test-jbh-master-default-1234.dev.svc.cluster.local.upstream_rq_pending_failure_eject: 0
cluster.outbound|50051||grpc-test-jbh-master-default-1234.dev.svc.cluster.local.upstream_rq_pending_overflow: 0
cluster.outbound|50051||grpc-test-jbh-master-default-1234.dev.svc.cluster.local.upstream_rq_pending_total: 0
```
The client requests all return 200
```
kubectl exec grpc-test-jbh-master-default-698d995b6f-2jbvp -c istio-proxy -- sh -c 'curl localhost:15000/stats' | grep grpc-test-jbh-master-default-1234 | grep external.upstream_rq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0cluster.outbound|50051||grpc-test-jbh-master-default-1234.default.svc.cluster.local.external.upstream_rq_200: 12165
cluster.outbound|50051||grpc-test-jbh-master-default-1234.default.svc.cluster.local.external.upstream_rq_2xx: 12165
cluster.outbound|50051||grpc-test-jbh-master-default-1234.default.svc.cluster.local.external.upstream_rq_completed: 12165
100 6502k    0 6502k    0     0  46.0M      0 --:--:-- --:--:-- --:--:-- 46.3M
cluster.outbound|50051||grpc-test-jbh-master-default-1234.default.svc.cluster.local.external.upstream_rq_time: P0(1,1) P25(1.025,1.02514) P50(1.05,1.05027) P75(1.075,1.07541) P90(1.09,1.09049) P95(1.095,1.09552) P99(1.099,1.09954) P99.9(1.0999,5.04592) P100(1.1,8.1)

```
