### ISSUE TITLE
Status not showing when operator controller is reconciling

### ISSUE THREAD

**Issue by ostromart** [istio/istio#23521]
When Istio is healthy, the status is displayed:
```
kc get istiooperators.install.istio.io -n istio-system example-istiocontrolplane -o yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
...
  profile: demo
status:
  componentStatus:
    AddonComponents:
      status: HEALTHY
    EgressGateways:
      status: HEALTHY
    IngressGateways:
      status: HEALTHY
    Pilot:
      status: HEALTHY
  status: HEALTHY

```
when controller is reconciling (e.g. change profile to default), the status disappears until reconcile is complete.

**Comment by jacob-delgado** [comment]
cc @richardwxn what is the status of this? It will have to wait until 1.6.1

**Comment by morvencao** [comment]
I can't reproduced this in master or release-1.6
The status is updated to `RECONCILING` immediately after edit the IOP instance:
```
  status:
    componentStatus:
      AddonComponents:
        status: RECONCILING
      Base:
        status: RECONCILING
      IngressGateways:
        status: RECONCILING
      Pilot:
        status: RECONCILING
    status: RECONCILING
```
