### ISSUE TITLE
fluentd adapter does not get created, despite adding overrides to istio 1.5.2

### ISSUE THREAD

**Issue by sagarkal** [istio/istio#23544]
Hi,

I just installed istio 1.5.2 on my kubernetes cluster where my service mesh is located. I understand that mixer is deprecated, but since mixer is going to be supported until 1.7, I want to temporarily continue using the mixer adapters, especially [fluentd](https://istio.io/docs/reference/config/policy-and-telemetry/adapters/fluentd/) with a logentry and a rule to send events to an external log store.
I see that after installing istio 1.5.2, if I try to install a fluentd CRD (manifest file below)

```
apiVersion: "config.istio.io/v1alpha2"
kind: fluentd
metadata:
  name: <some_name>
  namespace: <some_namespace>
spec:
  address: <some_address>
  integerDuration: true
```

I get an expected error 
`Error: unable to recognize "": no matches for kind "fluentd" in version "config.istio.io/v1alpha2"`

So I add the below overrides to istio helm chart
```
mixer:
  adapters:
    fluentd: 
      enabled: true
```
I installed istio chart release with this override. But I still get the same error I highlighted above, if I try to create the fluentd CRD. 
Could you please help me here?

**Comment by sagarkal** [comment]
Hi,

I saw that I need to use the updated manifest file format for the same. The below manifest file works for istio 1.5.2

```
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: <some_name>
  namespace: <some_namespace>
spec:
  compiledAdapter: fluentd
  params:
    address: <some_address>
    integerDuration: true
```
