### ISSUE TITLE
Install Istio using latest-1.6 release got unknown field "security" validation error

### ISSUE THREAD

**Issue by carolynhu** [istio/istio#23564]
This issue happened when I was trying to create a multi-cluster Istio setup.

To reproduce: 

- Download Istio release: I'm installing Istio using istio-1.6-alpha.68e623cb1793eb25f1d8a8d7c9e155b8435039d2, which can be downloaded here: https://gcsweb.istio.io/gcs/istio-build/dev/1.6-alpha.68e623cb1793eb25f1d8a8d7c9e155b8435039d2

- In my main cluster, I ran the following command to create cacert:

```
kubectl create namespace istio-system
kubectl create secret generic cacerts -n istio-system \
    --from-file=samples/certs/ca-cert.pem \
    --from-file=samples/certs/ca-key.pem \
    --from-file=samples/certs/root-cert.pem \
    --from-file=samples/certs/cert-chain.pem
```

- Created a istio-main-cluster.yaml

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    # selfSigned is required if Citadel is enabled, that is when values.global.istiod.enabled is false.
    security:
      selfSigned: false

    global:
      multiCluster:
        clusterName: ${MAIN_CLUSTER_NAME}
      network: ${MAIN_CLUSTER_NETWORK}

      # Mesh network configuration. This is optional and may be omitted if
      # all clusters are on the same network.
      meshNetworks:
        ${MAIN_CLUSTER_NETWORK}:
          endpoints:
          # Always use Kubernetes as the registry name for the main cluster in the mesh network configuration
          - fromRegistry: Kubernetes
          gateways:
          - registry_service_name: istio-ingressgateway.istio-system.svc.cluster.local
            port: 443

        ${REMOTE_CLUSTER_NETWORK}:
          endpoints:
          - fromRegistry: ${REMOTE_CLUSTER_NAME}
          gateways:
          - registry_service_name: istio-ingressgateway.istio-system.svc.cluster.local
            port: 443

      # Use the existing istio-ingressgateway.
      meshExpansion:
        enabled: true
```

- Then install Istio via:

```
istioctl manifest apply -f istio-main-cluster.yaml
```

I got the following error:

```
Error: failed to apply manifests: validation errors (use --force to override):
unknown field "security" in v1alpha1.Values
```

If I install with `--force` flag, will it impact any of the cluster settings or not?
