### ISSUE TITLE
V2 Telemetry: selectable metrics

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#23637]
Make V2 metrics selectable.
At present it is *not* possible to stop collecting any metrics.
Distributions are expensive and customers may not want to use them all the time.

1. Make metrics selectable
2. Measure performance impact of removing distributions.

====
For 1.5 / 1.6 releases it may not be possible to do this, but it *is* possible to filter out metrics at Envoy.

At present we use the following bootstrap
```yaml
    "stats_matcher": {
      "inclusion_list": {
        "patterns": [
          {
          "prefix": "reporter="
          },
          {{- range $a, $s := .inclusionPrefix }}
          {
          "prefix": "{{$s}}"
          },
```
Instead of using `prefix: "reporter="` we can enumerate our metrics as suffixes as below:
```yaml
    "stats_matcher": {
      "inclusion_list": {
        "patterns": [
          {
          "suffix": "_istio_requests_total"
          },
          {
          "suffix": "_istio_request_bytes"
          },
          {{- range $a, $s := .inclusionPrefix }}
          {
          "prefix": "{{$s}}"
          },
```
This ensures that only specific metrics are collected. We should *only* document this if there are savings *in the proxy* in removing distributions.
