### ISSUE TITLE
Ingress config is ignored for Kiali and tracing in istio-1.5.2

### ISSUE THREAD

**Issue by GoelDeepak** [istio/istio#23648]
**Bug description**
Ingress is not created for Kiali and Tracing

```yaml
values:
    kiali:
      ingress:
        enabled: true
    tracing:
       ingress:
          enabled: true
```

**Expected behavior**
Ingress to get created 

**Steps to reproduce the bug**
Looking at the code, it seems `ingress.yaml` is missing
https://github.com/istio/istio/tree/release-1.5.1-patch/manifests/istio-telemetry/kiali/templates

**How was Istio installed?**
istio-operator
