### ISSUE TITLE
redirect from http to https ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by aymann90** [istio/istio#23674]
**Bug description**

[] Multi Cluster
[ X] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istioctl versio 1.5.2
kubectl verstio 1.15.9

**How was Istio installed?**
using istioctl 
**Environment where bug was observed (cloud vendor, OS, etc)**

ERR_TOO_MANY_REDIRECTS when try to redirect http to https
i'm using GCP loadbalancer

i try to set tls.httpsredirect = true same issue and try 
and try using 

My Gateway and VS

`
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: staging-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http-backend
        protocol: HTTP
      tls:
        httpsRedirect: true
      hosts:
        - "example.com"
```
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: backend
spec:
  hosts:
    - "example.com"
  gateways:
    - staging-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: cloudrun
            port:
              number: 8080`
```
