### ISSUE TITLE
Istio Operator can't set the Prometheus to use pvc

### ISSUE THREAD

**Issue by swimablefish** [istio/istio#23685]
**Bug description**

**Expected behavior**
The prometheus created by istio operator can be set to use pvc

**Steps to reproduce the bug**
Use the following yaml to generate manifest
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: controlplane
  namespace: istio-system
spec:
  addonComponents:
    prometheus:
      enabled: true
  profile: default
  values:
    prometheus:
      persist: true
      storageClassName: "standard"
      accessMode: ReadWriteOnce
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
$ istioctl version --remote
client version: 1.5.2
pilot version: 1.5.2
data plane version: 1.5.2 (1 proxies)


Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
IstioOperator

**Environment where bug was observed (cloud vendor, OS, etc)**
