### ISSUE TITLE
Can't connect to aws mysql rds via egress gateway

### ISSUE THREAD

**Issue by padzikm** [istio/istio#23692]
Hi, I have mysql client inside mesh and external aws mysql rds. I can connect to mysql server with only service entry defined, but I can't connect after defining egress gateway. I' getting error from mysql client - ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet'. Below is my configuration, rds is hosted under database-2.cwbnoj5bvq8z.eu-central-1.rds.amazonaws.com address.
```
apiVersion: v1
kind: Namespace
metadata:
  name: sql-blue
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-blue
  namespace: sql-blue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: sql-blue
  labels:
    app: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      serviceAccountName: sa-blue
      containers:
      - name: mysql
        image: mysql:5.7.28
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: my-secret-pw
---
  apiVersion: "security.istio.io/v1beta1"
  kind: "PeerAuthentication"
  metadata:
    name: "default"
    namespace: sql-blue
  spec:
    mtls:
      mode: STRICT
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: mysql
spec:
  hosts:
  - database-2.cwbnoj5bvq8z.eu-central-1.rds.amazonaws.com
  ports:
  - number: 3306
    name: tcp
    protocol: TCP
  resolution: DNS
---
  apiVersion: networking.istio.io/v1alpha3
  kind: Gateway
  metadata:
    name: istio-egressgateway-mysql
  spec:
    selector:
      istio: egressgateway
    servers:
    - port:
        number: 3306
        name: tcp
        protocol: TCP
      hosts:
      - database-2.cwbnoj5bvq8z.eu-central-1.rds.amazonaws.com
---
  apiVersion: networking.istio.io/v1alpha3
  kind: DestinationRule
  metadata:
    name: egressgateway-for-sql
    namespace: sql-blue
  spec:
    host: istio-egressgateway.istio-system.svc.cluster.local
    subsets:
    - name: mysql
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-mysql-through-egress-gateway
spec:
  hosts:
  - database-2.cwbnoj5bvq8z.eu-central-1.rds.amazonaws.com
  gateways:
  - mesh
  - istio-egressgateway-mysql
  tcp:
  - match:
    - gateways:
      - mesh
      port: 3306
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: mysql
        port:
          number: 3306
  - match:
    - gateways:
      - istio-egressgateway-mysql
      port: 3306
    route:
    - destination:
        host: database-2.cwbnoj5bvq8z.eu-central-1.rds.amazonaws.com
        port:
          number: 3306
      weight: 100
---
```
How to make it work?
