### ISSUE TITLE
Better visibility on error messages returned by kube-inject

### ISSUE THREAD

**Issue by GregHanson** [istio/istio#23717]
**Bug description**
Performed `istioctl kube-inject` on a spec with `hostNetwork: true` which is mentioned in the docs here as item 2: https://istio.io/docs/ops/common-problems/injection/#the-result-of-sidecar-injection-was-not-what-i-expected

There is an error message [here](https://github.com/istio/istio/blob/master/pkg/kube/inject/inject.go#L724) but it gets hidden in the output returned:

```
$ istioctl kube-inject -f deamon-test.yaml 
Skipping injection because "hello" has host networking enabled
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  name: hello
spec:
  selector:
    matchLabels:
```

**Expected behavior**
istioctl should convey error messages such that they are visible to user.  Two istio devs found the problem in code and docs before noticing during debug that istioctl output contained an error message.

**Steps to reproduce the bug**
Run istioctl kube-inject on the modified yaml file from inject testdata:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hello
spec:
  selector:
    matchLabels:
      app: hello
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: hello
        tier: backend
        track: stable
    spec:
      containers:
        - name: hello
          image: "fake.docker.io/google-samples/hello-go-gke:1.0"
          ports:
            - name: http
              containerPort: 80
      hostNetwork: true
```
