### ISSUE TITLE
"valueOrDefault" not defined when using custom IstioOperator (-f) with manifest apply

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#23711]
**Bug description**

With 1.6.0-beta.1:
```
landow@landow-macbookpro3:istio-1.6.0-beta.1 $ istioctl version
no running Istio pods in "istio-system"
1.6.0-beta.1
landow@landow-macbookpro3:istio-1.6.0-beta.1 $ istioctl --context=$CTX_1 manifest apply -f manifests/examples/multicluster/values-istio-multicluster-gateways.yaml
Error: failed to apply manifests: template: :258: function "valueOrDefault" not defined
```

With 1.5.1 it works fine:
```
landow@landow-macbookpro3:istio-1.5.1 $ ./bin/istioctl version
2020-05-11T17:22:06.026750Z	warn	will use `--remote=false` to retrieve version info due to `no Istio pods in namespace "istio-system"`
1.5.1
landow@landow-macbookpro3:istio-1.5.1 $ ./bin/istioctl manifest apply -f install/kubernetes/operator/examples/multicluster/values-istio-multicluster-gateways.yaml
- Applying manifest for component Base...
```

**Comment by morvencao** [comment]
This happens on `release-1.6`branch, looks like this is caused by
```
  values:
    global:
      # Provides dns resolution for global services
      podDNSSearchNamespaces:
        - global
        - "{{ valueOrDefault .DeploymentMeta.Namespace \"default\" }}.global"
```

https://github.com/istio/istio/blob/release-1.6/operator/data/examples/multicluster/values-istio-multicluster-gateways.yaml#L18

which will be rendered in `values` of istio-sidecar-injector configMap.

I can see that the line `"{{ valueOrDefault .DeploymentMeta.Namespace \"default\" }}.global"` has removed from master.
