### ISSUE TITLE
istio virtual service header exact match rule not working

### ISSUE THREAD

**Issue by ajitchahal** [istio/istio#23767]
**Bug description**

The virtual service rule describes a http-> header->exact match rule, which is not enforced.
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  annotations:
    meta.helm.sh/release-name: nginx-test-1
    meta.helm.sh/release-namespace: kiwis
  generation: 1
  labels:
    app: nginx-test-1
    app.kubernetes.io/managed-by: Helm
  name: nginx-test-1
  namespace: kiwis
spec:
  gateways:
  - cds-gateway.commontools.svc.cluster.local
  hosts:
  - nginx-test-1.internal.b.stage.context.cloud.test
  http:
  - match:
    - headers:
        authorization:
          exact: Basic dGVzdDpwYXNz
    route:
    - destination:
        host: nginx-test-1.kiwis.svc.cluster.local
        port:
          number: 80
    timeout: 35s
  - fault:
      abort:
        httpStatus: 403
        percent: 100
    route:
    - destination:
        host: nginx-test-1.kiwis.svc.cluster.local
        port:
          number: 80
    timeout: 35s
```

Gateway:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: cds-gateway
  namespace: commontools
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*.internal.b.stage.context.cloud.test'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
```




**Expected behavior**
Here I expect the request with authorisation header to fail:
```bash
curl --location --request GET 'https://nginx-test-1.internal.b.stage.context.cloud.test'
...
HTTP/2 200
server: istio-envoy
```
**Steps to reproduce the bug**
Deployed a simple service with istio side car injected and mtls enabled.
Used a virtual service so that only the request with basic auth headers are allowed by matching exact headers in istio VS.
This used to work up until istio 1.2.2 (our last version)

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```bash
istioctl version                                                                                                                                                                                                                                  
client version: 1.5.1
control plane version: 1.5.1
data plane version: 1.5.1 (50 proxies)
````
**How was Istio installed?**
via istioctl - default profile

**Environment where bug was observed (cloud vendor, OS, etc)**
k8s cluster deployed via gardner
```bash
k version                                                                                                                                                                                                                                         
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by madan522** [comment]
+1

**Comment by howardjohn** [comment]
I think the issue is `fault` is not working here. If I set the host to `bogus` on the unauthorized one this works

**Comment by howardjohn** [comment]
The config is not correct. `percent` should be `percentage`. 

Like

```
  - fault:
      abort:
        httpStatus: 403
        percentage:
          value: 100
```

This is a bit annoying that we don't give any indication about this error. In Istio 1.6 we would catch this though
