### ISSUE TITLE
"istioctl x describe" documentation uses removed CR authentication.istio.io/v1alpha1

### ISSUE THREAD

**Issue by esnible** [istio/istio#23777]
https://preliminary.istio.io/docs/ops/diagnostic-tools/istioctl-describe/#verifying-strict-mutual-tls

The `kubectl apply` produces

```
Error from server: error when creating "STDIN": admission webhook "validation.istio.io" denied the request: unrecognized type Policy
```

A replacement for the Policy could be

```
kubectl apply -f - <<EOF
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: ratings-strict
spec:
  selector:
    matchLabels:
      app: ratings
  mtls:
    mode: STRICT
EOF
```

However, because of https://github.com/istio/istio/issues/23776 this section doesn't show anything useful.  Perhaps just replace this YAML in the docs and wait for that fix?
