### ISSUE TITLE
Envoy filter: unknown message type "envoy.config.transport_socket.tap.v2alpha.Tap"

### ISSUE THREAD

**Issue by hobbytp** [istio/istio#23795]
**Bug description**
envoy proxy provides [traffic tapping](https://www.envoyproxy.io/docs/envoy/v1.13.1/operations/traffic_tapping) function, so I want to use envoyfilter to configure and then use it by using istio 1.5.1. Currently I have tried HTTP tap, it can work correctly. but I can not apply envoyfilter for TCP tap in both LISTENER and CLUSTER.  when I try the tcp tap, the istio validation admission webhook always return failed like "admission webhook "validation.istio.io" denied the request: configuration is invalid: Envoy filter: unknown message type "envoy.config.transport_socket.tap.v2alpha.Tap", any more info needed, please let me know.

The V2 envoyfilter yaml file is as below:
```yaml
kubectl -n tcp-server apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: tcp-echo-server-tcp-tap
  namespace: tcp-server
spec:
  workloadSelector:
    labels:
      app: tcp-echo-server
  configPatches:
    - applyTo: CLUSTER
      match:
        context: SIDECAR_INBOUND
        cluster:
          name: "inbound|9000|tcp|tcp-echo-server.tcp-server.svc.cluster.local"
      patch:
        operation: MERGE
        value:
          transport_socket_matches:
          - name: "defaultToPlaintext"
            match:
              acceptMTLS: true
            transport_socket:
              name: envoy.transport_sockets.tap
              typed_config:
                "@type": type.googleapis.com/envoy.config.transport_socket.tap.v2alpha.Tap
                common_config:
                  static_config:
                    match_config:
                      any_match: true
                    output_config:
                      sinks:
                        - format: PROTO_BINARY
                          file_per_tap:
                            path_prefix: /tmp/
EOF
```
The difference between v2 and v3 is only in typed_config
V3 is as below: 
```yaml
typed_config:
                "@type": type.googleapis.com/envoy.extensions.transport_sockets.tap.v3.Tap
```

Try V2 API, the error log is:
```
Error from server: error when creating "STDIN": admission webhook "validation.istio.io" denied the request: configuration is invalid: Envoy filter: unknown message type "envoy.config.transport_socket.tap.v2alpha.Tap"
```

Try V3 API, the error log is:
```
Error from server: error when creating "STDIN": admission webhook "validation.istio.io" denied the request: configuration is invalid: Envoy filter: unknown message type "envoy.extensions.transport_sockets.tap.v3.Tap"
```

The envoy proxy tcp tapping info can be found here:
https://www.envoyproxy.io/docs/envoy/latest/operations/traffic_tapping

**Expected behavior**
The envoyfilter can configure envoy proxy tcp tapping function.

**Steps to reproduce the bug**
*** Step 1: Create namespace tcp-server with istio-injection=true
*** Step 2: Install tcp-echo-server by using yaml file
```yaml
apiVersion: v1
kind: Service
metadata:
  name: tcp-echo-server
  namespace: tcp-server
  labels:
    app: tcp-echo-server
spec:
  ports:
  - name: tcp
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: tcp-echo-server
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tcp-echo-server-v1
  namespace: tcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp-echo-server
      version: v1
  template:
    metadata:
      labels:
        app: tcp-echo-server
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: tcp-echo-server
        image: istio/tcp-echo-server:1.1
        imagePullPolicy: IfNotPresent
        args: [ "9000", "hello" ]
        ports:
        - containerPort: 9000
          protocol: TCP

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tcp-echo-gateway
  namespace: tcp-server
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: tcp-tls
      number: 31400
      protocol: TLS
    tls:
      mode: MUTUAL
      serverCertificate: /etc/certs/cert-chain.pem
      privateKey: /etc/certs/key.pem
      caCertificates: /etc/certs/root-cert.pem
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tcp-echo-server
  namespace: tcp-server
spec:
  gateways:
  - tcp-echo-gateway
  hosts:
  - '*'
  tcp:
  - match:
    - port: 31400
    route:
    - destination:
        host: tcp-echo-server
        port:
          number: 9000
```
*** Step 3: Install tcp tap yaml file
The yaml file is provided in section "Bug description"

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
$ istioctl version --remote
client version: 1.5.1
control plane version: 1.5.1
data plane version: 1.5.1 (12 proxies)

sudo minikube version
minikube version: v1.9.0
commit: 48fefd43444d2f8852f527c78f0141b377b1e42a

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

helm version
Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}

**How was Istio installed?**
follow https://istio.io/docs/setup/install/istioctl/ to install demo profile

**Environment where bug was observed (cloud vendor, OS, etc)**
minikube installed in vm
minikube version: v1.9.0
commit: 48fefd43444d2f8852f527c78f0141b377b1e42a

$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
