### ISSUE TITLE
Make envoy.router filter configurable

### ISSUE THREAD

**Issue by penglei** [istio/istio#23805]
**Bug description**
I want to disable dynamic_stats to improve envoy performance. This can be implemented by patching filter with EnvoyFilter CRD, but I found the following configuration didn't work.

````
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: http-dynamic-stats-disabled
  namespace: istio-system
spec:
  configPatches:
  - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        proxy:
          proxyVersion: '^1\.5.*'
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
              subFilter:
                name: "envoy.router"
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": type.googleapis.com/envoy.config.filter.http.router.v2.Router
            dynamic_stats: false

````

After I checked the source code, I think envoy.router can be built with typed_config in buildHTTPConnectionManager.

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
client version: 1.5.1
control plane version: 1.5.1
data plane version: 1.5.1 (2 proxies), 1.5-dev (1 proxies)
```

**How was Istio installed?**

istioctl apply
