### ISSUE TITLE
Traffic mirroring to an external service in another cluster does not work

### ISSUE THREAD

**Issue by Hmerac** [istio/istio#23814]
**Bug description**
I'm currently trying to mirror traffic from A cluster(service) to B cluster(service), yet, when I make a request to the httpbin Service in A cluster via a `curl` Pod I created, I can see the requests in the A service, but can't see any kind of requests in the B service. Both services are injected with sidecar.

I also cannot execute `tcpdump` on sidecars because `tcpdump` doesn’t work in the sidecar pod - the container doesn’t run as root.

These are the debugging outputs in A Cluster:
```
$ istioctl-1.4 pc routes httpbin-v2-5b7749cd64-zw8sf -ojson
...
             {
                "name": "httpbin.default.stage.foo.bar:80",
                "domains": [
                    "httpbin.default.stage.foo.bar",
                    "httpbin.default.stage.foo.bar:80"
                ],
                "routes": [
                    {
                        "name": "default",
                        "match": {
                            "prefix": "/"
                        },
                        "route": {
                            "cluster": "outbound|80||httpbin.default.stage.foo.bar",
                            "timeout": "0s",
                            "retryPolicy": {
                                "retryOn": "connect-failure,refused-stream,unavailable,cancelled,resource-exhausted,retriable-status-codes",
                                "numRetries": 2,
                                "retryHostPredicate": [
                                    {
                                        "name": "envoy.retry_host_predicates.previous_hosts"
                                    }
                                ],
                                "hostSelectionRetryMaxAttempts": "5",
                                "retriableStatusCodes": [
                                    503
                                ]
                            },
                            "maxGrpcTimeout": "0s"
                        },
                        "decorator": {
                            "operation": "httpbin.default.stage.foo.bar:80/*"
                        },
                        "typedPerFilterConfig": {
                            "mixer": {
                                "@type": "type.googleapis.com/istio.mixer.v1.config.client.ServiceConfig",
                                "disableCheckCalls": true,
                                "mixerAttributes": {
                                    "attributes": {
                                        "destination.service.host": {
                                            "stringValue": "httpbin.default.stage.foo.bar"
                                        },
                                        "destination.service.name": {
                                            "stringValue": "httpbin.default.stage.foo.bar"
                                        },
                                        "destination.service.namespace": {
                                            "stringValue": "default"
                                        }
                                    }
                                },
                                "forwardAttributes": {
                                    "attributes": {
                                        "destination.service.host": {
                                            "stringValue": "httpbin.default.stage.foo.bar"
                                        },
                                        "destination.service.name": {
                                            "stringValue": "httpbin.default.stage.foo.bar"
                                        },
                                        "destination.service.namespace": {
                                            "stringValue": "default"
                                        }
                                    }
                                }
                            }
                        }
                    }
                ]
            },
            {
                "name": "httpbin.default.svc.cluster.local:80",
                "domains": [
                    "httpbin.default.svc.cluster.local",
                    "httpbin.default.svc.cluster.local:80"
                ],
                "routes": [
                    {
                        "match": {
                            "prefix": "/"
                        },
                        "route": {
                            "cluster": "outbound|8080||httpbin.default.svc.cluster.local",
                            "timeout": "0s",
                            "retryPolicy": {
                                "retryOn": "connect-failure,refused-stream,unavailable,cancelled,resource-exhausted,retriable-status-codes",
                                "numRetries": 2,
                                "retryHostPredicate": [
                                    {
                                        "name": "envoy.retry_host_predicates.previous_hosts"
                                    }
                                ],
                                "hostSelectionRetryMaxAttempts": "5",
                                "retriableStatusCodes": [
                                    503
                                ]
                            },
                            "requestMirrorPolicy": {
                                "cluster": "outbound|80||httpbin.default.stage.foo.bar",
                                "runtimeFraction": {
                                    "defaultValue": {
                                        "numerator": 100
                                    }
                                }
                            },
                            "maxGrpcTimeout": "0s"
                        },
                        "metadata": {
                            "filterMetadata": {
                                "istio": {
                                    "config": "/apis/networking/v1alpha3/namespaces/default/virtual-service/httpbin"
                                }
                            }
                        },
                        "decorator": {
                            "operation": "httpbin.default.svc.cluster.local:8080/*"
                        },
                        "typedPerFilterConfig": {
                            "mixer": {
                                "@type": "type.googleapis.com/istio.mixer.v1.config.client.ServiceConfig",
                                "disableCheckCalls": true,
                                "mixerAttributes": {
                                    "attributes": {
                                        "destination.service.host": {
                                            "stringValue": "httpbin.default.svc.cluster.local"
                                        },
                                        "destination.service.name": {
                                            "stringValue": "httpbin"
                                        },
                                        "destination.service.namespace": {
                                            "stringValue": "default"
                                        },
                                        "destination.service.uid": {
                                            "stringValue": "istio://default/services/httpbin"
                                        }
                                    }
                                },
                                "forwardAttributes": {
                                    "attributes": {
                                        "destination.service.host": {
                                            "stringValue": "httpbin.default.svc.cluster.local"
                                        },
                                        "destination.service.name": {
                                            "stringValue": "httpbin"
                                        },
                                        "destination.service.namespace": {
                                            "stringValue": "default"
                                        },
                                        "destination.service.uid": {
                                            "stringValue": "istio://default/services/httpbin"
                                        }
                                    }
                                }
                            }
                        }
                    }
                ]
            },
...
```
```
$ istioctl-1.4 pc cluster httpbin-v2-5b7749cd64-zw8sf
    {
        "name": "outbound|80||httpbin.default.stage.foo.bar",
        "type": "STRICT_DNS",
        "connectTimeout": "10s",
        "loadAssignment": {
            "clusterName": "outbound|80||httpbin.default.stage.foo.bar",
            "endpoints": [
                {
                    "lbEndpoints": [
                        {
                            "endpoint": {
                                "address": {
                                    "socketAddress": {
                                        "address": "httpbin.default.stage.foo.bar",
                                        "portValue": 80
                                    }
                                }
                            },
                            "loadBalancingWeight": 1
                        }
                    ],
                    "loadBalancingWeight": 1
                }
            ]
        },
        "circuitBreakers": {
            "thresholds": [
                {
                    "maxConnections": 4294967295,
                    "maxPendingRequests": 4294967295,
                    "maxRequests": 4294967295,
                    "maxRetries": 4294967295
                }
            ]
        },
        "dnsRefreshRate": "300s",
        "respectDnsTtl": true,
        "dnsLookupFamily": "V4_ONLY"
    },
    {
        "name": "outbound|8000||httpbin.default.svc.cluster.local",
        "type": "EDS",
        "edsClusterConfig": {
            "edsConfig": {
                "ads": {}
            },
            "serviceName": "outbound|8000||httpbin.default.svc.cluster.local"
        },
        "connectTimeout": "10s",
        "circuitBreakers": {
            "thresholds": [
                {
                    "maxConnections": 4294967295,
                    "maxPendingRequests": 4294967295,
                    "maxRequests": 4294967295,
                    "maxRetries": 4294967295
                }
            ]
        }
    },
    {
        "name": "inbound|8000|http|httpbin.default.svc.cluster.local",
        "type": "STATIC",
        "connectTimeout": "10s",
        "loadAssignment": {
            "clusterName": "inbound|8000|http|httpbin.default.svc.cluster.local",
            "endpoints": [
                {
                    "lbEndpoints": [
                        {
                            "endpoint": {
                                "address": {
                                    "socketAddress": {
                                        "address": "127.0.0.1",
                                        "portValue": 80
                                    }
                                }
                            }
                        }
                    ]
                }
            ]
        },
        "circuitBreakers": {
            "thresholds": [
                {
                    "maxConnections": 4294967295,
                    "maxPendingRequests": 4294967295,
                    "maxRequests": 4294967295,
                    "maxRetries": 4294967295
                }
            ]
        }
    }
```

**Expected behavior**
When I make a request to httpbin Service in the A cluster with 
`kubectl exec -it sleep-67957cdd96-hlcds -c sleep -- sh -c 'curl http://httpbin:8000/headers'`, I expect the request to be mirrored to the httpbin Service in the B cluster.

Interestingly, with this Virtual Service in A Cluster, the traffic gets mirrored but this is not usable in my case:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
  namespace: default
spec:
  hosts:
    - httpbin.default.stage.foo.bar
  http:
  - route:
    - destination:
        host: httpbin.default.stage.foo.bar
        port:
          number: 80
      weight: 100
    mirror:
      host: httpbin
      port:
        number: 8000
    mirror_percent: 100
```

**Steps to reproduce the bug**

In A Cluster:
- Create a httpbin Service and Deployment.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        command: ["gunicorn", "--access-logfile", "-", "-b", "0.0.0.0:80", "httpbin:app"]
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: default
  labels:
    app: httpbin
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: httpbin
```

- Create a Virtual Service for mirroring.
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
  namespace: default
spec:
  hosts:
    - httpbin
  http:
  - route:
    - destination:
        host: httpbin
        port:
          number: 8000
      weight: 100
    mirror:
      host: httpbin.default.stage.foo.bar
      port:
        number: 80
    mirror_percent: 100
```

- Create a Service Entry for the external service.

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: set
  namespace: default
spec:
  hosts:
  - httpbin.default.stage.foo.bar
  exportTo:
  - "."
  ports:
  - number: 80
    name: http
    protocol: HTTP
  location: MESH_EXTERNAL
  resolution: DNS
```

In B Cluster:

- Create the same httpbin Service and Deployment.

- Create a Gateway for the ingress traffic.
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-ingress
  namespace: shared
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*.stage.foo.bar'
    port:
      name: http2-dev
      number: 80
      protocol: http2
```

- Create a Virtual Service to route ingress traffic to the httpbin Service.
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: 'http2-default'
  namespace: 'shared'
spec:
  gateways: ["istio-ingress"]
  hosts:
  - "*.stage.foo.bar"
  - match:
      - port: 80
        authority:
          prefix: "httpbin.default"
    route:
      - destination:
          host: "httpbin.default.svc.cluster.local"
          port:
            number: 8000
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

- **A Cluster:**
```
$ istioctl version --remote
client version: 1.5.1
control plane version: 1.4.5
data plane version: 1.4.5 (121 proxies)
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-10T21:53:51Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-gke.3", GitCommit:"71631703d37fb1b4b333abd427deae839aeb2032", GitTreeState:"clean", BuildDate:"2020-03-24T18:54:48Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
```
- **B Cluster:**
```
$ istioctl version --remote
client version: 1.5.1
control plane version: 1.5.2
data plane version: 1.5.2 (11 proxies)
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-10T21:53:51Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-gke.9", GitCommit:"e1af17fd873e15a48769e2c7b9851405f89e3d0d", GitTreeState:"clean", BuildDate:"2020-04-06T20:56:54Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Istio was installed using Helm.

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by hendrikmaus** [comment]
Hey, I am with @Hmerac on this one. It popped back into my head, that we can tcpdump anyway since the network interface in the pod is shared by all containers, hence we can see all packets. 
Anyhow, here is what I found when curling the httpbin from the above mentioned curl pod.

```
GET /status/200 HTTP/1.1
host: httpbin-shadow:8000
user-agent: curl/7.52.1
accept: */*
x-forwarded-proto: http
x-request-id: df05de93-5778-91df-a4ae-bd657b86e148
x-envoy-decorator-operation: httpbin.default.svc.cluster.local:8000/*
x-istio-attributes: CiUKGGRlc3RpbmF0aW9uLnNlcnZpY2UubmFtZRIJEgdodHRwYmluCisKHWRlc3RpbmF0aW9uLnNlcnZpY2UubmFtZXNwYWNlEgoSCGhvdGVsYWRzCjEKCnNvdXJjZS51aWQSIxIha3ViZXJuZXRlczovL2R1bW15LTMwMTQyLmhvdGVsYWRzCkAKGGRlc3RpbmF0aW9uLnNlcnZpY2UuaG9zdBIkEiJodHRwYmluLmhvdGVsYWRzLnN2Yy5jbHVzdGVyLmxvY2FsCj4KF2Rlc3RpbmF0aW9uLnNlcnZpY2UudWlkEiMSIWlzdGlvOi8vaG90ZWxhZHMvc2VydmljZXMvaHR0cGJpbg==
x-b3-traceid: 0f30c8ed91a0587664df136fae19aa22
x-b3-spanid: 64df136fae19aa22
x-b3-sampled: 1
x-envoy-internal: true
x-forwarded-for: 10.246.167.119
content-length: 0

HTTP/1.1 404 Not Found
date: Thu, 14 May 2020 06:55:34 GMT
server: istio-envoy
content-length: 0
```

The host header for the mirrored request was set to `httpbin-shadow:8000`. I would have expected to see `httpbin.default.stage.foo.bar-shadow` or `httpbin.default.stage.foo.bar-shadow:80`.

What are we missing?

**Comment by arnecls** [comment]
As far as I can see from the config dump, the mirroring sends requests directly to the cluster (see `requestMirrorPolicy`), i.e. the request is neither modified nor goes through any kind of routing (like one would expect when setting up a virtual service for the mirror target in the source cluster).

I.e. the `host` of the curl request should be `httpbin.default.svc.cluster.local` or any kind of abbreviation of the service host. I don't see though where the `httpbin-shadow` come from. Did you curl that host?

Given that finding, the gateway on the target cluster needs to react on the original host (which is not in *.stage.foo.bar`), otherwise the request will be dropped.

**Comment by hendrikmaus** [comment]
The `httpbin-shadow` comes from Envoy; its mirroring module suffixes the `host`/`authority` header with `-shadow` and the port is added at the very end as well.

We curled `http://httpbin:8000/status/200` in cluster A.

**Comment by arnecls** [comment]
We got this figured out.

Envoy textually appends "-shadow" to the host header, i.e. you can end up with one the following values, depending on how you target the service in the source cluster (the one you want to mirror):
`<service>-shadow`, `<service>.<namespace>-shadow` and `<service>.<namespace>.svc.cluster.local-shadow`.

On the target cluster, the only chance you currently have is to react on "*" in the servers/host section of the ingress' gateway resource, otherwise you would need to add all possible combinations there. This is IMO a good reason for a feature request in envoy to make this configurable (e.g. to change it to ".shadow").

```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
# [...]
spec:
  servers:
  - hosts:
    - '*' # < --- allow all hosts
```

On the target cluster, you have to also add a "*-shadow" to the host section of the virtual services attached to the ingress gateway. If you match for hosts in the http section, you should use "prefix", which will cover names ending with "-shadow".

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
# [...]
spec:
  hosts:
  # [...]
  - "*-shadow"  # <--- allow shadowed hosts
  http:
  - match:
      - authority:
          prefix: "<service>" # <--- use prefix for host matching
```
