### ISSUE TITLE
DestinationRule serving file over SDS grabs wrong cert

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#23822]
Steps:

```
kubectl create svc clusterip deny --tcp=15443

cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: deny
spec:
  host: deny
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 15443
      tls:
        mode: MUTUAL
        caCertificates: deny
        clientCertificate: deny
        privateKey: deny
EOF
```

End result:

```
$ ik pc secret `kp details`
RESOURCE NAME           TYPE           STATUS     VALID CERT     SERIAL NUMBER                               NOT AFTER                NOT BEFORE
file-cert:deny~deny     Cert Chain     ACTIVE     true           320532614494485619321747892129760595003     2020-05-14T18:33:20Z     2020-05-13T18:33:20Z
default                 Cert Chain     ACTIVE     true           297036474108991828497880616870512301375     2020-05-14T18:13:18Z     2020-05-13T18:13:18Z
file-root:deny                         ACTIVE     false
ROOTCA                  CA             ACTIVE     true           47837858401102914562180051696189883294      2030-05-10T23:09:45Z     2020-05-12T23:09:45Z
```

The file-root:deny is invalid, and file-cert:deny~deny is generating a new cert

@ramaraochavali do you have a chance to take a look? Let me know if not
