### ISSUE TITLE
[release-1.6] istiodRemote and base can not be specified in iop in release-1.6

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#23846]
Using latest rc.0 build: https://github.com/istio/istio/releases/tag/1.6.0-rc.0
`istioctl install -f multi-remote-cluster.yaml`

`Error: failed to apply manifests: validation errors (use --force to override):
unknown field "base" in v1alpha1.GlobalConfig`

`cat multi-remote-cluster.yaml`

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: empty
  components:
    base:
      enabled: true
    pilot:
      enabled: false
    istiodRemote:
      enabled: true
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
  values:
    global:
      multiCluster:
        clusterName: remotecluster
      network: remotenetwork
      centralIstiod: true
      istiodRemote:
        injectionURL: https://irisdingbj:15017/inject
      base:
        validationURL: https://irisdingbj15017/validate
```

**Comment by irisdingbj** [comment]
@linsun

**Comment by linsun** [comment]
Thanks @irisdingbj I will download rc.0 and try.  I noticed one issue, why is your profile empty?

**Comment by linsun** [comment]
@irisdingbj I think this may be an user error.  I just downloaded rc.0 and manifest generates fine for me.  Below is the IO yaml I used.

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    base:
      enabled: true
    pilot:
      enabled: false  
    istiodRemote:
      enabled: true 
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true 
  
  addonComponents:
    prometheus:
      enabled: false
  values:
    global:
      # The remote cluster's name and network name must match the values specified in the
      # mesh network configuration of the main cluster.
      multiCluster:
        clusterName: remote0 
      network: network2        
      centralIstiod: true
      
      # Replace ISTIOD_REMOTE_EP with the the value of ISTIOD_REMOTE_EP set earlier.
      remotePilotAddress: 169.x.x.x
    
    istiodRemote:
      injectionURL: https://169.x.x.x:15017/inject

    base:
      validationURL: https://169.x.x.x:15017/validate

  ## The istio-ingressgateway is not required in the remote cluster if both clusters are on
  ## the same network. To disable the istio-ingressgateway component, uncomment the lines below.
  #

```
