### ISSUE TITLE
Gateway values do not apply without explicitly gateway enablement

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#23877]
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
    - enabled: true
  values:
    gateways:
      istio-ingressgateway:
        ports:
          - name: http2
            port: 80
            nodePort: 31380
          - name: https
            port: 443
            nodePort: 31390
        type: NodePort
```

Works completely

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    gateways:
      istio-ingressgateway:
        ports:
          - name: http2
            port: 80
            nodePort: 31380
          - name: https
            port: 443
            nodePort: 31390
        type: NodePort
```

Applies only the nodeport type, not the ports part
