### ISSUE TITLE
Istio cannot upgrade addon components using istioctl

### ISSUE THREAD

**Issue by CatchZeng** [istio/istio#23880]
**Bug description**

When I use istioctl to upgrade istio, from v1.5.0 to v1.5.4, the output is stuck in `Applying manifest for component AddonComponents...` , and all AddonComponents are not installed.

```
- Applying manifest for component Base...
✔ Finished applying manifest for component Base.
- Applying manifest for component Pilot...
✔ Finished applying manifest for component Pilot.
- Applying manifest for component IngressGateways...
- Applying manifest for component AddonComponents...
✔ Finished applying manifest for component IngressGateways.

```
<img width="1045" alt="istio" src="https://user-images.githubusercontent.com/10027281/82043755-ba41c500-96de-11ea-92b3-b748ba8e4811.png">

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ istioctl version --remote
client version: 1.5.4
ingressgateway version: 1.5.4
pilot version: 1.5.4
xxx-ingressgateway version: 
data plane version: 1.5.0 (49 proxies), 1.5.4 (2 proxies)
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"126eb499523e5fffc0138e8e2e031787e5ab1943", GitTreeState:"clean", BuildDate:"2020-04-03T17:45:13Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

```shell
istioctl manifest apply -f istio-1.5.0.yaml
```

istio-1.5.0.yaml
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  values:
    gateways:
      istio-ingressgateway:
        ports:
          - name: status-port
            port: 15020
            targetPort: 15020
          - name: http2
            port: 80
            targetPort: 80
          - name: https
            port: 443
          - name: kiali
            port: 15029
            targetPort: 15029
          - name: prometheus
            port: 15030
            targetPort: 15030
          - name: grafana
            port: 15031
            targetPort: 15031
          - name: tracing
            port: 15032
            targetPort: 15032
          - name: tls
            port: 15443
            targetPort: 15443
    pilot:
      env:
        PILOT_HTTP10: 1
    grafana:
      enabled: true
      persist: true
      security:
        enabled: true
    kiali:
      enabled: true
    tracing:
      enabled: true
```

**How was Istio upgraded?**

```shell
istioctl manifest upgrade -f istio-1.5.4.yaml
```

istio-1.5.4.yaml
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          service:
            ports:
            - port: 15020
              targetPort: 15020
              name: status-port
            - port: 80
              targetPort: 80
              name: http2
            - port: 443
              name: https
            - port: 15029
              targetPort: 15029
              name: kiali
            - port: 15030
              targetPort: 15030
              name: prometheus
            - port: 15031
              targetPort: 15031
              name: grafana
            - port: 15032
              targetPort: 15032
              name: tracing
            - port: 15443
              targetPort: 15443
              name: tls
            - port: 31400
              name: tcp
     - name: xxx-ingressgateway
        enabled: true
        label:
          app: xxx-ingressgateway
          istio: xxx-ingressgateway
        k8s:
          service:
            ports:
            - port: 15020
              targetPort: 15020
              name: status-port
            - port: 80
              targetPort: 80
              name: http2
            - port: 443
              name: https
            - port: 15029
              targetPort: 15029
              name: kiali
            - port: 15030
              targetPort: 15030
              name: prometheus
            - port: 15031
              targetPort: 15031
              name: grafana
            - port: 15032
              targetPort: 15032
              name: tracing
            - port: 15443
              targetPort: 15443
              name: tls
            - port: 31400
              name: tcp
 
  addonComponents:
    prometheus:
      enabled: true
    kiali:
      enabled: true
    grafana:
      enabled: true
    tracing:
      enabled: true

  values:
    pilot:
      env:
        PILOT_HTTP10: 1
    grafana:
      persist: true
      security:
        enabled: true
```

**Comment by CatchZeng** [comment]
The reason is that I did not configure the storageClassName for grafana. It works in istioctl v1.5.0, but it needs to be specified in v1.5.4.

Below is my solution.

istio-1.5.4.yaml
```yaml
......
    grafana:
      persist: true
      storageClassName: "managed-standard-retain"
      security:
        enabled: true
```
