### ISSUE TITLE
PASSTHROUGH mode for ingress gateway does not work

### ISSUE THREAD

**Issue by mbanikazemi** [istio/istio#23886]
**Bug description**

Has there been any change in the use of the PASSTHROUGH mode for gateways? The exact set of resources (that is, Istio gateway, vs, and dr) which were working fine with 1.4.* do not work anymore. The traffic gets directed to destination pod through the port  15443 but the request fails with no healthy upstream error. I do not use *.global and do not need the rewrite.

requests get top the service but eventually fail with 503 and "no healthy upstream"

The same exact resources works fine with Istio 1.4.2

**Expected behavior**

Using PASSTHROUGH with a VS to get to a service

**Steps to reproduce the bug**
```
apiVersion: networking.istio.io/v1beta1
  kind: Gateway
 metadata:
  name: helloworld-gateway
  spec:
    selector:
      istio: ingressgateway
    servers:
    - hosts:
      - helloworld.default.svc.cluster.local
      port:
        name: helloworld
        number: 15443
        protocol: TLS
      tls: {}
---
 apiVersion: networking.istio.io/v1beta1
  kind: VirtualService
  spec:
    gateways:
    - helloworld-gateway
    hosts:
    - '*'
    tls:
    - match:
      - port: 15443
        sniHosts:
        - helloworld.default.svc.cluster.local
      route:
      - destination:
          host: helloworld.default.svc.cluster.local
          port:
            number: 5000
          subset: notls
---
  apiVersion: networking.istio.io/v1beta1
  kind: DestinationRule
  spec:
    host: helloworld.default.svc.cluster.local
    subsets:
    - name: notls
      trafficPolicy:
        tls: {}
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ istioctl version
client version: 1.6.0-rc.0
control plane version: 1.6.0-rc.0
data plane version: 1.6.0-rc.0 (6 proxies)
```
**How was Istio installed?**

```
istioctl manifest apply \
         -f manifests/examples/multicluster/values-istio-multicluster-gateways.yaml
```

**Environment where bug was observed (cloud vendor, OS, etc)**
