### ISSUE TITLE
Ordering of fields in injected container

### ISSUE THREAD

**Issue by erictune** [istio/istio#239]
When you inject a container with istio proxy, it looks like:

```
    spec:
      containers:
      - image: gcr.io/google_containers/echoserver:1.4
        name: echoheaders
        ports:
        - containerPort: 8080
        resources: {}
      - args:
        - proxy
        - sidecar
        - -v
        - "2"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: docker.io/istio/proxy:0.1.0
        imagePullPolicy: Always
        name: proxy
        resources: {}
        securityContext:
          runAsUser: 1337
```

It would be classy if the order of the fields were such that either "image" or "name" was first for the proxy container.
