### ISSUE TITLE
Impossible to configure aggregate clusters via an EnvoyFilter

### ISSUE THREAD

**Issue by robertpanzer** [istio/istio#23909]
**Bug description**

**Expected behavior**
The EnvoyFilter should allow adding arbitrary clusters as long as Envoy supports the configuration.
However it is not possible to configure an aggregate cluster.

**Steps to reproduce the bug**
Try to configure an aggregate cluster with this EnvoyFilter:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: patch-clusters
spec:
  configPatches:
    - applyTo: CLUSTER
      match:
        context: SIDECAR_OUTBOUND
      patch:
        operation: ADD
        value:
          name: my_aggregate_cluster
          connect_timeout: 2s
          lb_policy: CLUSTER_PROVIDED
          cluster_type:
            name: envoy.clusters.aggregate
            typed_config:
              "@type": "type.googleapis.com/envoy.config.cluster.aggregate.v2alpha.ClusterConfig"
              clusters:
                - cluster_a
                - cluster_b
```

The configuration is rejected with this error:
```
for: ".../filtertest.yaml": admission webhook "validation.istio.io" denied the request: configuration is invalid: Envoy filter: unknown message type "envoy.config.cluster.aggregate.v2alpha.ClusterConfig"
```

The problem seems to come from the corresponding packages of the envoyproxy/go-control-plane not being imported, therefore the port types are not registered and hence unknown when the configuration is validated.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Istio 1.6.0-rc.2

**How was Istio installed?**
With `istioctl operator`.

**Environment where bug was observed (cloud vendor, OS, etc)**
Local Docker for Mac.
