### ISSUE TITLE
no upgrade path for observability in 1.5 to 1.6.

### ISSUE THREAD

**Issue by sdake** [istio/istio#23912]
Istio 1.5 has instructions for exposing telemetry over port 15029-15032. During an upgrade from 1.5 to 1.6, observability breaks. A pre-canned yaml blob is needed to continue export over 15032. Then the upgrade documentation should guide users to transitioning to the new model.

**Comment by sdake** [comment]
@howardjohn is busy, and I don't immediately know how to write the precanned yaml blob. i had spoken to John about this two weeks back, and he said he would get to it. This may miss the initial upgrade notes.

This is not an upgrade blocker and can be managed shortly after 1.6 releases.

**Comment by howardjohn** [comment]
```yaml
   ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        service:
          ports:
            - port: 15020
              targetPort: 15020
              name: status-port
            - port: 80
              targetPort: 80
              name: http2
            - port: 443
              name: https
            - port: 15029
              targetPort: 15029
              name: kiali
            - port: 15030
              targetPort: 15030
              name: prometheus
            - port: 15031
              targetPort: 15031
              name: grafana
            - port: 15032
              targetPort: 15032
              name: tracing
            - port: 15443
              targetPort: 15443
              name: tls
            - port: 31400
              name: tcp
```

can retain the old ports (copy+paste from default profile in 1.5)
