### ISSUE TITLE
Missing Istio Mutual TLS between sidecars and egress gateways

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#23910]
**Bug description**

Setting Istio Mutual TLS for traffic to egress gateways was removed from istio.io by the following PRs:
https://github.com/istio/istio.io/pull/6795, https://github.com/istio/istio.io/pull/6805 .

While Auto mTLS applies to traffic between sidecars, it probably cannot work for traffic between a sidecar and an egress gateway, since the gateway expects plain HTTP traffic and it has no sidecar proxy to perform mTLS for it (the gateway is itself a proxy). The users could think that thanks to auto mTLS all the traffic in their mesh is encrypted automatically, which is probably not true for the traffic between application pods and egress gateways. Consider a case when the users direct HTTP traffic through the egress gateway and the egress gateway performs TLS origination to an external service. In Istio 1.4 all the traffic was encrypted. In Istio 1.5, the traffic between the application pod and the egress gateway is probably not encrypted.

I tried to use Destination Rules with TLS Mode ISTIO_MUTUAL and SNI, and set the TLS mode of the server in the egress gateway, as in Istio 1.4, but it does not work with Istio 1.5 for some reason.

**Expected behavior**
The traffic from the sidecars to the egress gateway must be encrypted.

**Steps to reproduce the bug**

Follow the instructions in https://preliminary.istio.io/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/ and verify that the traffic between Istio sidecar and the egress gateway is not encrypted.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
client version: 1.5.4
control plane version: 1.5.4
data plane version: 1.5.4 (4 proxies)

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by linsun** [comment]
@GregHanson can you look at this?  Is autoMTLS not working (or not intended to work) from sidecar to egress gw?

**Comment by frankbu** [comment]
@GregHanson Any progress on this problem? Could it maybe be related to https://github.com/istio/istio/issues/24251?

**Comment by frankbu** [comment]
Added needs-escalation label because 2 of our documented egress tasks are currently broken in both 1.5 and 1.6 docs.

**Comment by nschhina** [comment]
@frankbu which 2 egress tasks are broken? I think Egress Gateway TLS origination is broken for the mutual TLS section- if you can provide me this info it'd be great. This is quite essential to the feature I'm working on

**Comment by frankbu** [comment]
@nschhina, I'm not exactly sure since I haven't look at these tasks lately, but I'm guessing the wildcard-egress-hosts tasks, based on this comment: https://github.com/istio/istio.io/pull/6217#issuecomment-629709256

**Comment by vadimeisenbergibm** [comment]
@nschhina All the egress tasks involving mutual TLS between the proxy and the gateway seem to be broken (there is no mutual TLS between the proxy and the gateway).

**Comment by nschhina** [comment]
mTLS origination task in https://istio.io/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/ is also broken

**Comment by GregHanson** [comment]
I tried to implement ISTIO_MUTUAL in the originating TLS task: 
https://preliminary.istio.io/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/#perform-tls-origination-with-an-egress-gateway
With the following rules: 

```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cnn
spec:
  hosts:
  - edition.cnn.com
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 80
      name: https
      protocol: HTTPS
    hosts:
    - edition.cnn.com
    tls:
      mode: ISTIO_MUTUAL  
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-cnn
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: cnn
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 80
        tls:
          mode: ISTIO_MUTUAL
          sni: edition.cnn.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-cnn-through-egress-gateway
spec:
  hosts:
  - edition.cnn.com
  gateways:
  - istio-egressgateway
  - mesh
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: cnn
        port:
          number: 80
      weight: 100
  - match:
    - gateways:
      - istio-egressgateway
      port: 80
    route:
    - destination:
        host: edition.cnn.com
        port:
          number: 443
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-tls-for-edition-cnn-com
spec:
  host: edition.cnn.com
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE # initiates HTTPS for connections to edition.cnn.com
EOF
```
But it results in a 503
```
$ kubectl exec $SOURCE_POD -c sleep -- curl -sL -o /dev/null -D - http://edition.cnn.com/politics
HTTP/1.1 503 Service Unavailable
content-length: 95
content-type: text/plain
date: Fri, 12 Jun 2020 21:36:48 GMT
server: envoy
```
trace level logs from sleep pod:
https://gist.github.com/GregHanson/d9cdf778017c0d2aa6e81a911fdf57fd
Most notable that I could find:
```
2020-06-12T21:29:32.883286Z	trace	envoy filter	[src/envoy/tcp/metadata_exchange/metadata_exchange.cc:153] Alpn Protocol Not Found. Expected istio-peer-exchange, Got 
```
the clusters for egress gateway show the ISTIO_MUTUAL transport socket matches, which require the `security.istio.io/tlsMode=istio` label in order to work -  but egress gateway does not have that label.  Should Egress gateway have this label by default? cc @lambdai

**Comment by GregHanson** [comment]
CDS output for egress gateway on sleep pod:
https://gist.github.com/GregHanson/d01fb020e9c4acb4f2b72eeb421d118f

**Comment by vadimeisenbergibm** [comment]
@GregHanson 
> Should Egress gateway have this label by default?

Note that Egress gateway does not have to have a `server` with MUTUAL_TLS port. So if you add this label, maybe non-TLS traffic to the egress gateway will be broken.

**Comment by nickperry** [comment]
I really need a solution to this. We're currently 1.5 and 1.6, using mTLS within our meshes and doing some access to external services using VS, DR and SE to initiate SIMPLE TLS direct from the client pods. However, I urgently need to get the traffic to external services working via an egress gateway instead. And I need the traffic between the client pod and the egress gateway to be mTLS. I've spent most of the last couple of days trying to make it work, to no avail.

**Comment by spicysomtam** [comment]
I was just trying out [Perform mutual TLS origination with an egress gateway](https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/#perform-mutual-tls-origination-with-an-egress-gateway) with 1.6.4. I get this when it should be doing mTLS:
```
$ kubectl exec -it $SOURCE_POD -c sleep -- curl -s --resolve nginx.example.com:80:1.1.1.1 http://nginx.example.com
upstream connect error or disconnect/reset before headers. reset reason: connection failure
```
Its a rather complex example, so might spend a bit of time ensuring I got it right, but all my cutting and pasting from the other examples have been fine (and I'm sure there is an deliberate attempt to make the instructions easy to follow).

**Comment by spicysomtam** [comment]
So it would be great if the default mTLS example through an egress gateway actually worked! Just gone through all this, including checking the certs are correct on the egress gateway (they are).

**Comment by frankbu** [comment]
@spicysomtam Exactly! That's what I mentioned almost 3 weeks ago now: https://github.com/istio/istio/issues/23910#issuecomment-640712731. I've been told that there is progress being made on this problem, but sadly a fix hasn't been provided yet.

**Comment by spicysomtam** [comment]
I just freshly deployed istio 1.4.10 in an empty rancher k3s 1.18.4 k8s cluster and the instructions for 1.6.4 [Perform mutual TLS origination with an egress gateway](https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/#perform-mutual-tls-origination-with-an-egress-gateway) work perfectly:

```
$ kubectl exec -it $SOURCE_POD -c sleep -- curl -s --resolve nginx.example.com:80:1.1.1.1 http://nginx.example.com
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
amunro@laptop15 ~/git/surge $ kubectl logs -l istio=egressgateway -n istio-system | grep 'nginx.example.com' | grep HTTP
[2020-07-03T11:07:45.686Z] "GET / HTTP/1.1" 200 - "-" "-" 0 612 10 7 "10.42.2.24" "curl/7.35.0" "f3d81aff-a358-9962-ba92-1305ed83189d" "nginx.example.com" "10.43.208.35:443" outbound|443||nginx.example.com - 10.42.0.7:443 10.42.2.24:32882 nginx.example.com -
```

I think the issue may be missing certs on the egress gateway; these defined in the sleep ns gateway (I am sure these were missing; all 3 files):
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - nginx.example.com
    tls:
      mode: MUTUAL
      serverCertificate: /etc/certs/cert-chain.pem
      privateKey: /etc/certs/key.pem
      caCertificates: /etc/certs/root-cert.pem
```

Let me copy off those files from 1.4 and put them on 1.6.4 and I'll get back to you with my testing.
