### ISSUE TITLE
Load balance not working as expected with outlierDetection

### ISSUE THREAD

**Issue by 1hanymhajna** [istio/istio#23914]
We are using istio v1.4.7, no sds, mtls enabled
We are trying to configure **circuit breaking** by creating `destinationRule` with `outlierDetection` for specific service, but we face that after we adding it and all the pods are healthy,
 it just sends the request to the first pod in the list without doing any round robin/ (or random),
I tried to configure it manually as well to be "round robin" but got same behavior.

is there any known issue? 

my destination-rule:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: circuit-breaking-test
  namespace: delivery
spec:
  host: circuit-breaking-test-service
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    outlierDetection:
      consecutiveErrors: 1
      interval: 1s
      baseEjectionTime: 5s
      maxEjectionPercent: 10
```
**Please notice, when the first pod start return 502,503,504, it already detach it out, and we start see the round robin is working fine, You can reproduce it just if your first pod return 200,201,202**
 
After deleting the `destionationRole` or creating it without `outlierDetection` it working fine - Rounding
