### ISSUE TITLE
No validation for duplicate YAML keys

### ISSUE THREAD

**Issue by mbanikazemi** [istio/istio#23930]
User submitted YAML with the same key and two different values; none of the Istio tools noticed this.  I tried several online YAML validators.  https://onlineyamltools.com/validate-yaml caught this; most others did not.

Was:

**Bug description**

~~In a destination rule if you specify a traffic policy for a subset it does not take effect. The overall traffic policy is what is being applied.~~

**Expected behavior**

**Steps to reproduce the bug**

1- install booking example
```
kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml
```
2- install the DRs
```
kubectl apply -f samples/bookinfo/networking/destination-rule-all-mtls.yaml
```
3- make sure you enforce use of mtls
```
kubectl apply -f - <<EOF
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
spec:
  mtls:
    mode: STRICT
EOF
```
4- update the reviews DR 
```
cat > test.yaml <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews
spec:
  host: reviews
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
  - name: v2
    labels:
      version: v2
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
  - name: v3
    labels:
      version: v3
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
  trafficPolicy:
    tls: {}
EOF
istioctl validate -f test.yaml
istioctl analyze test.yaml
kubectl apply -f test.yaml
```
-5  access the service. it fails to access reviews.
```
kubectl exec -it $(kubectl get pod -l app=ratings -o jsonpath='{.items[0].metadata.name}') -c ratings -- curl productpage:9080/productpage
```
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.6.0-rc.0 ( I think this issue exists in 1.5 s well)
