### ISSUE TITLE
auto mtls might be breaking regular TLS

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#23951]
Configure DR like
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: istiod
  namespace: istio-system
spec:
  host: istiod.istio-system.svc.cluster.local
  subsets:
    # Set up TLS to istiod backends
    - name: tls
      trafficPolicy:
        connectionPool:
          http:
            h2UpgradePolicy: UPGRADE
        tls:
          mode: SIMPLE
```

config_dump shows both transport_socket and transport_socket_matches and the traffic is wrong - its neither recognized as a TLS handshake nor is it plaintext. 

Disabling auto mtls and everything works.

Assigning to myself to investigate further
