### ISSUE TITLE
Having port range or port wildcard in configurations and rules

### ISSUE THREAD

**Issue by tvdinh** [istio/istio#23983]
**Describe the feature request**
Having port range or port wildcard in configurations and rules.

Context:

1. Configure external service (Apache ActiceMQ server in particular) for Istio Service Mesh

2. External services like Apache ActiceMQ, they have a few standards ports but then also use a random port to communicate with established clients (via JMS etc.). So to whitelist them, it would be useful that port range/wildcard can be defined like the below.

For example, defining a `ServiceEntry`

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: "activemq"
spec:
  hosts:
  - activemq.external
  location: MESH_EXTERNAL
  resolution: DNS
  ports:
  - name: "all-ports-activemq"
    number: *
    protocol: TCP
```

**Describe alternatives you've considered**
No obvious alternatives. Please suggest if there is an alternative

**Additional context**

**Comment by howardjohn** [comment]
I am not sure this is really possible in Envoy. I assume you do not want to whitelist literally all traffic, and instead just any IP addressed returned from DNS for activemq.external, on any port?

As far as I know Envoy cannot do this; its DNS resolution is only for load balancing

**Comment by howardjohn** [comment]
And if you want to allow all traffic, you can use ALLOW_ANY

**Comment by tvdinh** [comment]
> And if you want to allow all traffic, you can use ALLOW_ANY

ALLOW_ANY is not a preferable for my use case as mentioned in https://istio.io/docs/tasks/traffic-management/egress/egress-control/, we want any service internal/external to be registered (to be aware of)



> I am not sure this is really possible in Envoy. I assume you do not want to whitelist literally all traffic, and instead just any IP addressed returned from DNS for activemq.external, on any port?
> 
You are right, only for `activemq.external` host  and any port.

I think the use case is quite straightforward, is there a way to achieve that ?

**Comment by howardjohn** [comment]
TCP traffic doesn't have a host header so you cannot do traffic routing based on host for tcp traffic

**Comment by tvdinh** [comment]
> TCP traffic doesn't have a host header so you cannot do traffic routing based on host for tcp traffic

Thanks for pointing that out, I've used IP range instead and it works for single port, but the enquiry on the port range is still valid:

This works:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: "activemq"
spec:
  hosts:
  - dummy.com
  location: MESH_EXTERNAL
  resolution: NONE
  addresses:
  - <IP address> 
  ports:
  - name: "broker-port"
    number: 61616
    protocol: TCP
```

This doesn't:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: "activemq"
spec:
  hosts:
  - dummy.com
  location: MESH_EXTERNAL
  resolution: NONE
  addresses:
  - <IP address> 
  ports:
  - name: "all-ports"
    number: *
    protocol: TCP
```
