### ISSUE TITLE
clarification about tls origination/reverse proxy

### ISSUE THREAD

**Issue by pleasestopsayingno** [istio/istio#24013]
# problem
our stack, `rubberducky`, is required to have the one configuration per environment despite having dependencies that are region specific (which would require region specific configuration overrides)

# summary
rubberducky is deployed in many regions

in any given region we:
- have two environments: prod and qa
- have many instances of the rubberducky stack
- communicate with external services specific to that region

so our helm config looks like this:
```
ops/helm/rubberducky/charts/webserver/values.yaml
ops/env/prod/values.yaml
ops/env/qa/values.yaml
```
```
helm install -f $overrides/qa/values.yaml qarubberducky $charts/rubberducky
helm install -f $overrides/prod/values.yaml prodrubberducky $charts/rubberducky
```
with no room for region specific overrides

# tls origination
i've seen from the documentation that tls origination works for http(s) protocol(s) but i can't seem to make it work for tcp protocol

## tcp -> tls orignation setup
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: kafka
spec:
  hosts:
  - kafka.region.notrubberducky.com
  ports:
  - number: 80
    name: plaintext-port
    protocol: tcp
  - number: 443
    name: secure-port-used-by-tls-origination
    protocol: tls
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kafka
spec:
  hosts:
  - kafka.region.notrubberducky.com
  tcp:
  - match:
    - port: 80
    route:
    - destination:
        host: kafka.region.notrubberducky.com
        subset: tls-origination
        port:
          number: 443
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: kafka
spec:
  host: kafka.region.notrubberducky.com
  subsets:
  - name: tls-origination
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: SIMPLE
```
### what happened
if we change the tcp protocol to be http and the tls protocol to be https, everything work as expected.

### why use tcp traffic?
our external services are not http(s)... they're:
- amqps
- sasl_ssl 
- anything else built on top of tls

### why not use tls
tls would be nice since you can route on use a host, inspect sni, etc, but my client service would have to validate the certificate, which would require that the hostname to which i'm connecting would match the certificate's CN/SAN -- which it won't. right?

also, in my example above, we would configure orignation for mtls, but left that out to simplify things for PoC

### what else did we try
we tried using an egress gateway to do the origination, but that isn't necessary since each envoy proxy is directly hitting the external service (so all traffic exiting the node would be encrypted, if it works)

# next steps
you tell me...
