### ISSUE TITLE
Unable to create EnvoyFilter for ExtAuthz with typed config

### ISSUE THREAD

**Issue by hagen93** [istio/istio#24052]
**Bug description**

I tried to apply the following EnvoyFilter config;
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ext-authz
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.http_connection_manager
              subFilter:
                name: envoy.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.ext_authz
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
            grpc_service:
              envoy_grpc:
                cluster_name: ext-authz
```
but ended up with the error below (formatted for readability):
```
Error from server: error when creating "debug/envoyfilter.yaml":
admission webhook "validation.istio.io" denied the request:
configuration is invalid:
Envoy filter: unknown message type "envoy.extensions.filters.http.ext_authz.v3.ExtAuthz"
```
As far as I can tell this should work as [pkg/config/xds/filter_types.gen.go](https://github.com/istio/istio/blob/release-1.6/pkg/config/xds/filter_types.gen.go) contains an import of `envoy/extensions/filters/http/ext_authz/v3` which should register the related proto. Am I missing something here?

I also tried the same with `envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute` and `envoy.extensions.filters.http.header_to_metadata.v3.Config` as i need them too for what I'm building, but same problem arises.

The documentation has an example doing this same ting with `type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager` which seems to pass validation so I assume this is not a local problem with my installation.

**Expected behavior**
The provided config should pass validation

**Steps to reproduce the bug**
Apply the provided config

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
client version: 1.6.0
control plane version: 1.6.0
data plane version: 1.6.0 (10 proxies), 1.5.1 (2 proxies)

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-21T01:25:41Z", GoVersion:"go1.13.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.2-41+b5cdb79a4060a3", GitCommit:"b5cdb79a4060a307d0c8a56a128aadc0da31c5a2", GitTreeState:"clean", BuildDate:"2020-04-27T17:31:24Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
With istioctl. Installed over Istio v1.5.1.

**Environment where bug was observed (cloud vendor, OS, etc)**
Ubuntu 18.04 running MicroK8s
