### ISSUE TITLE
Using custom gateway with certmanager prevents ACME cert assignment with 1.6.0

### ISSUE THREAD

**Issue by SeanWallace** [istio/istio#24055]
**Bug description**

In the 1.6 branch the `values.global.k8sIngress` field was removed. A field of significant importance to those using custom gateways is apparently the `gatewayName` as without this setting certificates from sources such as LetsEncrypt are no longer able to use the certmanager HTTP solver.

I have rolled back to v1.5.4 (which by the way was the first I've seen to fully support custom gateways, before this I had a custom deployment) and am using the following IstioOperator config which works exactly as I expect:

```
  values:
    gateways:
      istio-ingressgateway:
        sds:
          enabled: true
        autoscaleEnabled: true
        autoscaleMax: 3
        autoscaleMin: 2
    global:
      k8sIngress:
        enabled: true
        enableHttps: false
        gatewayName: istio-ingressgateway-mine
```

Has this simply moved to a different configuration now?

**Expected behavior**

I would expect that when I'm using certmanager with SDS enabled (which I've read is now the default) this would continue to work as before with a custom gateway.

**Steps to reproduce the bug**

For the most part look above. The demo profile with another custom gateway and a Gateway attached to that with a Certificate as such:

```
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: my-cert
  namespace: istio-system
spec:
  dnsNames:
    - my.name.com
  secretName: my-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
```

Will result in failure to resolve via the custom gateway.

**How was Istio installed?**

`istioctl manifest apply -f my.yaml`

**Environment where bug was observed (cloud vendor, OS, etc)**

Personal Kubernets cluster 1.18.

**Comment by rauanmayemir** [comment]
Have you been able to find a workaround for this?

I don't have an issue with it because I use dns01 acme for cert generation, but now nothing with a proxy sidecar can't be deployed. (I suspect it's because there's no default or autogenerated gateway which I deleted thinking I no longer need it)

**Comment by howardjohn** [comment]
In 1.6 pilot will internally generate the Gateway required and not persist to the cluster. Can you post the Ingress you are using? This should be working correctly out of the box by just creating an Ingress with a tls section and the Certificate

**Comment by howardjohn** [comment]
See also https://preliminary.istio.io/docs/ops/integrations/certmanager/#kubernetes-ingress

**Comment by rauanmayemir** [comment]
I generate my certificates with cert-manager. I use istio, not kubernetes' nginx ingress. Here's my gateway config:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: public-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - "*"
      port:
        number: 80
        name: http
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - "redacted.com"
        - "*.redacted.com"
      port:
        name: https-default
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: cert-redacted-com-tls
        # also tried commenting out sds
        privateKey: sds
        serverCertificate: sds
```

But the issue is not with gateway itself, but istio proxy:

```
2020-05-25T14:42:14.802009Z	warning	envoy config	[external/envoy/source/common/config/grpc_subscription_impl.cc:101] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) 0.0.0.0_80: error adding listener '0.0.0.0:80': multiple filter chains with the same matching rules are defined
2020-05-25T14:42:16.754945Z	warn	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 3 successful, 0 rejected; lds updates: 0 successful, 3 rejected
```

I upgraded to `1.6.0` from `1.5.4`, wondering if something's missing there. Because upgrade was not smooth at all, I then followed someone's suggestion to run install instead of upgrade.

**Comment by rauanmayemir** [comment]
Those istio-proxy errors pop up even if there are no gateways at all.

**Comment by howardjohn** [comment]
I think your issue is different. Can you please get a config dump from the pod https://github.com/istio/istio/wiki/Troubleshooting-Istio, open a new issue and mention me?

**Comment by SeanWallace** [comment]
> In 1.6 pilot will internally generate the Gateway required and not persist to the cluster. Can you post the Ingress you are using? This should be working correctly out of the box by just creating an Ingress with a tls section and the Certificate

Here is an example of a gateway I have:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: mygateway
  namespace: mynamespace
spec:
  selector:
    istio: istio-ingressgateway-mine
  servers:
  - hosts:
    - my.example.com
    port:
      name: http
      number: 80
      protocol: HTTP
  - hosts:
    - my.example.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: mygateway-cert
      minProtocolVersion: TLSV1_2
      mode: SIMPLE
      privateKey: sds
      serverCertificate: sds
```

Given this is an environment I predominately need to work, I didn't get a chance to test additional things I wanted to and instead just reverted back to 1.5.4. I suspect if the selector was for the main gateway this issue wouldn't be present, however I didn't actually test that.
