### ISSUE TITLE
istio1.6.0: examples on gRPC-JSON transcode needed

### ISSUE THREAD

**Issue by hrkenshin** [istio/istio#24060]
I succeeded with setting below in istio1.5.2 version by referring to https://github.com/istio/istio/issues/7652
But after installing with istio1.6.0 version, `Content-Type 'application / json' is not supported` error occurs.
How to set EnvoyFilter in istio1.6.0 version?
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: test-api
  namespace: default
spec:
  workloadLabels:
    app: test-api
  filters:
    - listenerMatch:
        listenerType: SIDECAR_INBOUND
      insertPosition:
        index: BEFORE
        relativeTo: envoy.router
      filterName: envoy.grpc_json_transcoder
      filterType: HTTP
      filterConfig:
        proto_descriptor: /etc/envoy/proto.pb
        services:
          - examples.CommonService
        print_options:
          add_whitespace: false
          always_print_enums_as_ints: true
          always_print_primitive_fields: true
          preserve_proto_field_names: true
```

<img width="1051" alt="스크린샷 2020-05-24 오후 2 01 24" src="https://user-images.githubusercontent.com/2384832/82746110-1edbde80-9dc7-11ea-9c70-de3d9b77e61d.png">

**Comment by EDGsheryl** [comment]
@hrkenshin Hi, My service works, so I suppose these yaml files may help you.

My istio version is:
```
istioctl version
client version: 1.6.5
control plane version: 1.6.5
data plane version: 1.6.5 (13 proxies)
```

and my envoy filter plugin is 
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: backend-grpc-filter-chain
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        listener:
          portNumber: 5000
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
              subFilter:
                name: "envoy.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.grpc_json_transcoder
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
            proto_descriptor: "/etc/envoy/proto.pb"
            services: ["xxx.XXX"]
            print_options:
              add_whitespace: true
              always_print_primitive_fields: true
              always_print_enums_as_ints: false
              preserve_proto_field_names: false
  workloadLabels:
    app: mylabel
```

Besides, I recommend you to use `istioctl proxy-status` and `istioctl proxy-config listener service-name --port 5000 -o json`, it helps me a lot.
