### ISSUE TITLE
Gateway for HTTP2 protocol get 404 if same selector exists in the cluster

### ISSUE THREAD

**Issue by nak3** [istio/istio#24061]
**Bug description**

- Gateway for HTTP2 protocol get 404 if same selector exists in the cluster.
- Please refer to the reproducer below.

[X] Networking

**Expected behavior**

* Any gateway does not effect on other gateways' functionality.

**Steps to reproduce the bug**

### 1. Create a gateway with `istio: ingressgateway` selector.

```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: blocker
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "test.example.com"
EOF
```

#### 2-1. Deploy httpdbin app

```
cd $GOPATH/src/github.com/istio/istio
kubectl apply -f samples/httpbin/httpbin.yaml
```

#### 2-2. Deploy VirtualService

```
INGRESS=`kubectl get svc  -n istio-system  istio-ingressgateway  -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'`
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - $INGRESS
  gateways:
  - httpbin-gateway
  http:
  - match:
    - uri:
        prefix: /status
    - uri:
        prefix: /delay
    route:
    - destination:
        port:
          number: 8000
        host: httpbin
EOF
```

#### 2-3. Deploy another Gateway with `istio: ingressgateway` selector. 

```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "$INGRESS"
EOF
```

### 3. Access to the service (success)

```
curl $INGRESS/status/200 -o /dev/null -w '%{http_code}\n' -s
200
```

### 4. Change protocol HTTP to HTTP2 in httpbin-gateway gateway

```
kubectl edit gateway httpbin-gateway 
```

e.g.
```
    port:
      name: http2
      number: 80
      protocol: HTTP2
```

### 5. Access to the service (fail)

```
$ curl $INGRESS/status/200 -o /dev/null -w '%{http_code}\n' -s
404
```
NOTE: if you created httpbin-gateway gateway before blocker gateway, this issue does not happen.

### (extra step) 6. Same access works if we deleted the blocker gateway

```
kubectl delete gateway blocker
```

```
curl $INGRESS/status/200 -o /dev/null -w '%{http_code}\n' -s
200
```

So, the blocker gateway must be the culprit.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ istioctl version
client version: 1.5.4
cluster-local-gateway version: 
cluster-local-gateway version: 
ingressgateway version: 1.5.4
ingressgateway version: 1.5.4
pilot version: 1.5.4
pilot version: 1.5.4
pilot version: 1.5.4
data plane version: 1.5.4 (4 proxies)
```

**How was Istio installed?**

```
istioctl manifest apply
```
