### ISSUE TITLE
Unknown fields issue using Istioctl 1.6

### ISSUE THREAD

**Issue by prateek-gupta-wawa** [istio/istio#24062]
Bug description
Unable to do an istioctl install using a YAML file
Receive error: Error: failed to apply manifests: unknown field "autoInjection" in v1alpha1.IstioOperatorSpec

[X ] Installation
[X ] Developer Infrastructure

Expected behavior
The istio components should be installed

Steps to reproduce the bug
Download istioctl-1.6.0-win.zip new release on Windows 10.
Add it to the path
Use the command istioctl install -f C:\istio\setup-istio-local.yaml
(Attached the file)
Output: Error: f
[setup-istio-local.txt](https://github.com/istio/istio/files/4673810/setup-istio-local.txt)
ailed to apply manifests: unknown field "autoInjection" in v1alpha1.IstioOperatorSpec:

Version 1.6.0

How was Istio installed?
Download through release version and add it to environment variables

**Comment by morvencao** [comment]
Try the following yaml:
```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  meshConfig:
    accessLogFile: "/dev/stdout"
    accessLogEncoding: "JSON"
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
    enableTracing: false
    enableAutoMtls: false
  components:
    telemetry:
      enabled: false # disable istio-telemetry
    pilot:
      k8s:
        resources:
          requests:
            cpu: 200m # override from default 500m
            memory: 1Gi # ... default 2048Mi
  values:
    global:
      controlPlaneSecurityEnabled: false # Not required for local development
    sidecarInjectorWebhook:
      rewriteAppHTTPProbe: true # Required for health checks
    prometheus:
      enabled: false
```

The api for istio operator has evolved, all components are defined in `components` fields.
Besides, the `meshConfig` can be configured for sidecar settings, eg, `accessLogFile`, `enableTracing`...

For mTLS, try to use [PeerAuthentication](https://istio.io/docs/reference/config/security/peer_authentication/) instead.
