### ISSUE TITLE
paths configuration failed in AuthorizationPolicy

### ISSUE THREAD

**Issue by lys0224** [istio/istio#24089]
I want to config an authorization policy that allows two sources, the cluster.local/ns/test/sa/inner service account and the dev namespace, to access the workloads with the run: test label in the test namespace with the path /inner/*.

The AuthorizationPolicy like this:

```
apiVersion: "security.istio.io/v1beta1"
kind: AuthorizationPolicy
metadata:
  name: test-policy
  namespace: test
spec:
  selector:
    matchLabels:
      run: test
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/test/sa/inner"]
    - source:
        namespaces: ["test"]
    to:
    - operation: 
        paths: ["/inner/*"]
```

But it doesn't work.When I add the 'to' field all interfaces are inaccessible.And when I remove the 'to' filed it works well.How should I configure the 'to' filed?

**Comment by lys0224** [comment]
```
apiVersion: "security.istio.io/v1beta1"
kind: AuthorizationPolicy
metadata:
  name: test-policy
  namespace: test
spec:
  selector:
    matchLabels:
      run: test
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/test/sa/inner"]
    - source:
        namespaces: ["test"]
  - to:
    - operation: 
        paths: ["/inner/*"]
```
