### ISSUE TITLE
Error adding/updating listener(s) 0.0.0.0_80: error adding listener '0.0.0.0:80': multiple filter chains with the same matching rules are defined

### ISSUE THREAD

**Issue by rauanmayemir** [istio/istio#24084]
**Bug description**

When I upgraded to istio 1.6.0, istio proxy stopped working. No pods can be started because `istio-proxy` sidecar fails with:

```
2020-05-25T18:13:13.365524Z	warning	envoy filter	[src/envoy/http/authn/http_filter_factory.cc:83] mTLS PERMISSIVE mode is used, connection can be either plaintext or TLS, and client cert can be omitted. Please consider to upgrade to mTLS STRICT mode for more secure configuration that only allows TLS connection with client cert. See https://istio.io/docs/tasks/security/mtls-migration/
2020-05-25T18:13:13.366997Z	warning	envoy filter	[src/envoy/http/authn/http_filter_factory.cc:83] mTLS PERMISSIVE mode is used, connection can be either plaintext or TLS, and client cert can be omitted. Please consider to upgrade to mTLS STRICT mode for more secure configuration that only allows TLS connection with client cert. See https://istio.io/docs/tasks/security/mtls-migration/
2020-05-25T18:13:13.368143Z	warning	envoy config	[external/envoy/source/common/config/grpc_subscription_impl.cc:101] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) 0.0.0.0_80: error adding listener '0.0.0.0:80': multiple filter chains with the same matching rules are defined

2020-05-25T18:13:14.930471Z	warn	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 1 rejected
```

**Steps to reproduce the bug**

Install istio `1.6.0` on top of `1.5.4`.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
client version: 1.6.0
control plane version: 1.6.0
data plane version: 1.6.0 (4 proxies)
```

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-15T15:50:25Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

**How was Istio installed?**

`istioctl install -f manifest.yaml` (`IstioOperator` spec extending on `default` profile)

**Environment where bug was observed (cloud vendor, OS, etc)**

ubuntu 18.04 lts (bare-metal)

Config dump was huge, so I put it here: https://gist.github.com/rauanmayemir/65e737ea6eca8d6a0f0ec2fa156fdfdd

Cc: @howardjohn

**Comment by rauanmayemir** [comment]
I think it was the wrong config dump, here's the dump from `istio-proxy`: https://gist.github.com/rauanmayemir/7001c7de839e919d2f0ff90cfde7c533.

**Comment by hzxuzhonghu** [comment]
@rauanmayemir Can you show all your services with 80 port? I am not sure whether this related to tcp fail through feature

**Comment by rauanmayemir** [comment]
@hzxuzhonghu Here it is:

```
apiVersion: v1
kind: Service
metadata:
  name: echo
  labels:
    app: echo
spec:
  ports:
    - port: 80
      targetPort: 5678
      name: http
  selector:
    app: echo
```

(I can also see that istio tracing svc binds to port 80)

**Comment by rauanmayemir** [comment]
I deleted tracing component and switched echo to a different port, still seeing same issues.

**Comment by hzxuzhonghu** [comment]
I tried to create multi services with 80 on istio 1.6.0, but can not reproduce.  Not sure why the passthrough filter chain match with application protocol set.

**Comment by rauanmayemir** [comment]
@hzxuzhonghu I deleted everything that were bound to 80, but still seeing the error.

**Comment by howardjohn** [comment]
`click-s5-russia.esv2.com` service entry is the problem. Reproducer:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: break-80
spec:
  hosts:
  - httpbin.org
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: tcp
    protocol: TCP
  resolution: NONE
```

**Comment by howardjohn** [comment]
We end up with FCMs:

```
tcp match all SE
1.0/1.1/h2c -> 80
1.0/1.1/h2c -> passthrough
```

We should have

```
tcp match all SE
1.0/1.1/h2c -> 80
```

**Comment by rauanmayemir** [comment]
@howardjohn Wow, that was something I couldn't make work and forgot it even existed (the idea was to proxy incoming https request to insecure external endpoint).

Is that a bug, or did I do something I wasn't supposed to?

**Comment by howardjohn** [comment]
@rauanmayemir its a bit of both. We shouldn't send invalid config to envoy like we are today as it gets rejected like you saw, but the config is pretty abnormal

**Comment by hzxuzhonghu** [comment]
@howardjohn 👍 great finding

**Comment by rolandkool** [comment]
We're running into the same error when applying this ServiceEntry:
```
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  annotations:
  name: proxyserver
  namespace: istio-system
spec:
  hosts:
  - proxyserver.internal.company.com
  location: MESH_EXTERNAL
  ports:
  - name: https-8080
    number: 8080
    protocol: HTTPS
  resolution: DNS
```
Workloads need to reach a proxy outside the mesh that runs on port 8080 and requires https.
Because every proxy in the mesh has by default an entry for `outbound|8080||istio-pilot.istio-system.svc.cluster.local` , adding this service entry causes this error for each service and in addition results in no ready envoys after a restart.

**Comment by howardjohn** [comment]
@rolandkool what version? I am surprised this is failing at all but a quick test on 1.6 shows this behaving properly

**Comment by rolandkool** [comment]
This is on 1.6

**Comment by howardjohn** [comment]
Can you post the config dump?

**Comment by rolandkool** [comment]
Created one: https://gist.github.com/rolandkool/febcbbe5e41fdccd1eb070c956a3aaf4

**Comment by rolandkool** [comment]
When changing the SE to `http`, the error disappears.

**Comment by rauanmayemir** [comment]
I wonder if it's related, but I also couldn't expose a tcp port on istio ingress. Here's my config:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: amqp-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - "rabbitmq.redacted.tld"
      port:
        number: 5672
        name: tcp-amqp-5672
        protocol: TCP
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: tcp-amqp
spec:
  hosts:
    - rabbitmq.redacted.tld
  gateways:
    - istio-system/amqp-gateway
  tcp:
    - match:
        - port: 5672
      route:
        - destination:
            host: rabbitmq-headless.default.svc.cluster.local
            port:
              number: 5672
```

And here's how it looks in `service/istio-ingressgateway`:

```
spec:
  ports:
  # ...
  - name: tcp-amqp
    # auto-set by k8s, not me:
    nodePort: 30769
    port: 5672
    protocol: TCP
    targetPort: 5672
```

This config seemed to work on `1.5.4`, but telnetting on `1.6.0` gives me this:

```
$ telnet rabbitmq.redacted.tld 5672
Trying ip...
Connected to rabbitmq.redacted.tld.
Escape character is '^]'.
Connection closed by foreign host.
```

I.e connection is being closed immediately.
