### ISSUE TITLE
loadBalancer LEAST_CONN not working 

### ISSUE THREAD

**Issue by packyzbq** [istio/istio#24138]
**Bug description**
I am testing the loadBalancer settings. I find that the `LEAST_CONN` setting doesn't work. Now I have 3 pod as follows. Those are http servers and httpbin-0 response delays 5s while httpbin-1 and httpbin-2 response delays 200ms.
```
root@node5:~/zhaobq/istio-1.5.4/samples/httpbin# kubectl get po -n lb |grep httpbin
httpbin-0                        2/2     Running   0          11m
httpbin-1                        2/2     Running   0          12m
httpbin-2                        2/2     Running   0          12m
```
The vs and dr are as follows:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - httpbin
  http:
  - route:
    - destination:
        host: httpbin
        subset: v1
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: httpbin
spec:
  host: httpbin
  subsets:
  - labels:
      version: v1
    name: v1
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
```

I also add annotation `sidecar.istio.io/statsInclusionRegexps: .*` to the httpbin-0 pod and check the statistics of istio-proxy using command `kubectl exec httpbin-0 -c istio-proxy -- curl localhost:15000/stats`, but there's nothing useful. I found that the statistics items are much less than the official envoy documentation.

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio version: 1.5.4
kubernetes version: 1.17.5

**How was Istio installed?**
`istioctl manifest apply --set profile=demo`

**Environment where bug was observed (cloud vendor, OS, etc)**
