### ISSUE TITLE
Virtual service is applied to gateways with the same name in two namespaces

### ISSUE THREAD

**Issue by yan-dblinf** [istio/istio#24135]
**Bug description**

Routes defined in a virtual service are not only deployed to the gateway explicitly configured in the manifest, but also to another gateway with the same name but in a different namespace. 

**Affected product area**

- Docs
- Networking

**Expected behavior**
The virtual service is supposed to be only applied to gateways explicitly configured if any.  

**Steps to reproduce the bug**

0. Add two custom ingress gateways by following the section _How was Istio installed?_

1. Apply two virtual services
```
cat <<EOF | kubectl apply -f -
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtual-service
  namespace: foo
spec:
  gateways:
  - foo/istio-ingressgateway-dev
  hosts:
  - '*'
  http:
  - route:
    - destination:
        host: svc-foo
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtual-service
  namespace: bar
spec:
  gateways:
  - bar/istio-ingressgateway-dev
  hosts:
  - '*'
  http:
  - route:
    - destination:
        host: svc-bar
EOF
```

2. Get the name of ingress gateway pod in namespace foo
```
IG_POD_NAME=kubectl -n foo get pod -l app=istio-ingressgateway-dev | tail -1 | awk '{print $1}'
``` 

3. Check routes in the the pod
```
istioctl pc r $IG_POD_NAME.foo --name http.80 -o json | grep bar | grep '"cluster"'
```
The output is
```
                            "cluster": "outbound|80||svc-bar.bar.svc.cluster.local",
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

client version: 1.5.2
control plane version: 1.5.2
data plane version: 1.5.2 

**How was Istio installed?**

Istio is installed by running `istioctl manifest apply -f istio-operator.yaml`, where an IstioOperator is defined with two custom ingress gateways in namespace foo and bar, respectively.

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
spec:
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
      - name: istio-ingressgateway-dev
        enabled: true
        namespace: foo
        k8s:
          overlays:
            - kind: HorizontalPodAutoscaler
              name: istio-ingressgateway-dev
              patches:
                - path: metadata.labels.app
                  value: istio-ingressgateway-dev
                - path: metadata.labels.istio
                  value: ingressgateway-dev
            - kind: Deployment
              name: istio-ingressgateway-dev
              patches:
                - path: metadata.labels.app
                  value: istio-ingressgateway-dev
                - path: metadata.labels.istio
                  value: ingressgateway-dev
                - path: spec.selector.matchLabels.app
                  value: istio-ingressgateway-dev
                - path: spec.selector.matchLabels.istio
                  value: ingressgateway-dev
                - path: spec.template.metadata.labels.app
                  value: istio-ingressgateway-dev
                - path: spec.template.metadata.labels.istio
                  value: ingressgateway-dev
            - kind: Gateway
              name: istio-ingressgateway-dev
              patches:
                - path: metadata.name
                  value: istio-ingressgateway-dev
                - path: spec.selector.app
                  value: istio-ingressgateway-dev
                - path: spec.selector.istio
                  value: ingressgateway-dev
            - kind: PodDisruptionBudget
              name: ingressgateway
              patches:
                - path: metadata.name
                  value: ingressgateway-dev
                - path: metadata.labels.app
                  value: istio-ingressgateway-dev
                - path: metadata.labels.istio
                  value: ingressgateway-dev
                - path: spec.selector.matchLabels.app
                  value: istio-ingressgateway-dev
                - path: spec.selector.matchLabels.istio
                  value: ingressgateway-dev
            - kind: Service
              name: istio-ingressgateway-dev
              patches:
                - path: metadata.labels.app
                  value: istio-ingressgateway-dev
                - path: metadata.labels.istio
                  value: ingressgateway-dev
                - path: spec.selector.app
                  value: istio-ingressgateway-dev
                - path: spec.selector.istio
                  value: ingressgateway-dev
      - name: istio-ingressgateway-dev
        enabled: true
        namespace: bar
        k8s:
          overlays:
            - kind: HorizontalPodAutoscaler
              name: istio-ingressgateway-dev
              patches:
                - path: metadata.labels.app
                  value: istio-ingressgateway-dev
                - path: metadata.labels.istio
                  value: ingressgateway-dev
            - kind: Deployment
              name: istio-ingressgateway-dev
              patches:
                - path: metadata.labels.app
                  value: istio-ingressgateway-dev
                - path: metadata.labels.istio
                  value: ingressgateway-dev
                - path: spec.selector.matchLabels.app
                  value: istio-ingressgateway-dev
                - path: spec.selector.matchLabels.istio
                  value: ingressgateway-dev
                - path: spec.template.metadata.labels.app
                  value: istio-ingressgateway-dev
                - path: spec.template.metadata.labels.istio
                  value: ingressgateway-dev
            - kind: Gateway
              name: istio-ingressgateway-dev
              patches:
                - path: metadata.name
                  value: istio-ingressgateway-dev
                - path: spec.selector.app
                  value: istio-ingressgateway-dev
                - path: spec.selector.istio
                  value: ingressgateway-dev
            - kind: PodDisruptionBudget
              name: ingressgateway
              patches:
                - path: metadata.name
                  value: ingressgateway-dev
                - path: metadata.labels.app
                  value: istio-ingressgateway-dev
                - path: metadata.labels.istio
                  value: ingressgateway-dev
                - path: spec.selector.matchLabels.app
                  value: istio-ingressgateway-dev
                - path: spec.selector.matchLabels.istio
                  value: ingressgateway-dev
            - kind: Service
              name: istio-ingressgateway-dev
              patches:
                - path: metadata.labels.app
                  value: istio-ingressgateway-dev
                - path: metadata.labels.istio
                  value: ingressgateway-dev
                - path: spec.selector.app
                  value: istio-ingressgateway-dev
                - path: spec.selector.istio
                  value: ingressgateway-dev
```  

**Environment where bug was observed (cloud vendor, OS, etc)**
k8s v1.16.9 managed by kops v1.16.0 on AWS
