### ISSUE TITLE
CORS preflight OPTIONS requests returning 403 response in Istio v1.6.0.

### ISSUE THREAD

**Issue by andrewridout** [istio/istio#24145]
**Bug description**
Since upgrading to Istio v1.6.0, all CORS preflight HTTP OPTIONS requests sent from a UI to a backend service fail with `HTTP 403` response. When running Istio v1.5.4 CORS requests worked successfully.

The browser console shows this error:
```
Access to XMLHttpRequest at 'https://api.example.com/example-svc/example' from origin 'https://ui.example.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

And we get this error logged to GCP Stackdriver:
```
"OPTIONS /example-svc/example HTTP/1.1" 403 - "-" "-" 0 19 0 - "<redacted IP>" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36" "9db54f9f-ea1d-4184-8e32-99d4783843c1" "api.example.com" "-" - - <redacted IP>:3000 <redacted IP>:0 outbound_.3000_._.example-service.default.svc.cluster.local -
```

Virtual Service:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: example-service
  namespace: default
spec:
  hosts:
    - '*'
  gateways:
    - istio-system/default-gateway
  http:
    - match:
        - uri:
            prefix: /example-svc/
        - uri:
            prefix: /example-svc
      rewrite:
        uri: /
      route:
        - destination:
            host: example-service
            port:
              number: 3000
      corsPolicy:
        allowOrigin:
          - https://ui.example.com
        allowHeaders:
          - Authorization
          - Content-Type
        allowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
```

Authorization Policy:
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: example-service-admin
  namespace: default
spec:
  selector:
    matchLabels:
      app: example-service
  rules:
    - when:
        - key: request.auth.claims[scp]
          values: ["example_svc"]
```

**Expected behavior**
CORS OPTIONS requests do not return a 403 and are successful as per behavior in Istio 1.5.4.

**Steps to reproduce the bug**
Upgrade from Istio 1.5.4 to 1.6.0 and make a CORS request from a browser-based UI to a backend service.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
`istioctl version --remote` output:
```
client version: 1.6.0
control plane version: 1.6.0
data plane version: 1.6.0 (8 proxies)
```
`kubectl version` output:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-15T15:50:38Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.36", GitCommit:"34a615f32e9a0c9e97cdb9f749adb392758349a6", GitTreeState:"clean", BuildDate:"2020-04-06T16:33:17Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
`istioctl manifest apply -f istio-config.yaml`

**Environment where bug was observed (cloud vendor, OS, etc)**
Google Kubernetes Engine
