### ISSUE TITLE
remotePilotAddress only accept IP not hostname

### ISSUE THREAD

**Issue by linsun** [istio/istio#24155]
@dcberg configured remotePilotAddress as a hostname vs an IP address, and he got an error at installation.  The error indicated that the endpoints object we create for istiod only takes IP address but not hostname:

```
kind: Endpoints
metadata:
  name: istiod
  namespace: {{ .Release.Namespace }}
subsets:
- addresses:
  - ip: {{ .Values.global.remotePilotAddress }}
```

This would affect both central istiod or shared control plane multicluster in general.  One thought to fix this is to base on the remotePilotAddress to 1) If IP is provided, create headless service that has endpoints with IP has today or 2) If hostname is provided, create a headless service with externalName without endpoints.

Welcome input from folks @howardjohn @costinm @nmittler 

[ ] Configuration Infrastructure
[ ] Docs
[ x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**
Run either central istiod or shared control plane steps with remotePilotAddress configured as the hostname of the ingress gw on main cluster

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.6.0

**Comment by spaghettifunk** [comment]
Is this issue actually solved? We are having issue with `istiod-remote` because it still cannot accept a hostname. Give this simple `remote` configuration for `mutlicluster`

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: remote
  namespace: istio-system
spec:
  addonComponents:
    tracing:
      enabled: true
    prometheus:
      enabled: false
  values:
    global:
      multiCluster:
        clusterName: cluster2
      network: network1
      remotePilotAddress: xxxxxxxxxx.elb.eu-west-1.amazonaws.com

  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: false
```

the operator returns the following error 

```
✘ Istio core encountered an error: failed to create "Endpoints/istio-system/istiod-remote": Endpoints "istiod-remote" is invalid: [subsets[0].addresses[0].ip: Invalid value: "xxxxxxxxx.elb.eu-west-1.amazonaws.com": must be a valid IP address, (e.g. 10.9.8.7), subsets[0].addresses[0].ip: Invalid value: "xxxxxxxx.elb.eu-west-1.amazonaws.com": must be a valid IP address]
```

Any advice?
