### ISSUE TITLE
Add support for regex rewrite in HttpRewrite

### ISSUE THREAD

**Issue by Lynskylate** [istio/istio#24172]
**Describe the feature request**
Evnoy support regex rewrite in the [pr](https://github.com/envoyproxy/envoy/pull/10050) .Add regex rewrite for HttpRewrite maybe a good idea.

VirtualService config maybe like below.
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ratings-route
spec:
  hosts:
  - ratings.prod.svc.cluster.local
  http:
  - match:
    - uri:
        regex: ^/new(.*?)_endpoint(.*)$"
    rewrite:
      substitution_url: /\1_rewritten_endpoint\2
    route:
    - destination:
        host: ratings.prod.svc.cluster.local
        subset: v1
```

[X ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
