### ISSUE TITLE
sidecar failed to proxy with interceptionMode TPROXY

### ISSUE THREAD

**Issue by erdun** [istio/istio#24170]
**Bug description**

Sidecar failed to proxy with mod `TPROXY`

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istioctl version --remote    
```                                                                                                                                                             
client version: 1.6.0
pilot version: 1.5.0
istiod version: 1.6.0
data plane version: 1.6.0 (4 proxies), 1.5.0 (232 proxies)
```

kubectl version
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
istioctl install --set revision=canary -f value.yaml

**Environment where bug was observed (cloud vendor, OS, etc)**
CentOS Linux release 7.7.1908 (Core)

Example deployment:
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: server
spec:
  template:
    metadata:
      labels:
        app: server
      annotations:
        sidecar.istio.io/interceptionMode: TPROXY
    spec:
      containers:
      - name: app
        image: erdun/http
        ports:
        - containerPort: 8080
          hostPort: 80
          name: http
          protocol: TCP
```

Can't connect to the pod with annotations `sidecar.istio.io/interceptionMode: TPROXY`, but can be connected in `REDIRECT` mode
