### ISSUE TITLE
Istio 1.6 Istiod error messages

### ISSUE THREAD

**Issue by gopisaba** [istio/istio#24189]
**Bug description**
After installing the Istio 1.6, these warning messages are flooding in Istiod pods. I don't know the impact of these error messages though my initial test to the applications are working fine.

```
2020-05-28T21:39:57.965601Z	warn	k8s.io/client-go@v0.18.0/tools/cache/reflector.go:125: watch of *v1.PartialObjectMetadata ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode watch event: no kind \"Node\" is registered for version \"v1\" in scheme \"pkg/runtime/scheme.go:101\"") has prevented the request from succeeding
2020-05-28T21:40:37.973025Z	warn	k8s.io/client-go@v0.18.0/tools/cache/reflector.go:125: watch of *v1.PartialObjectMetadata ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode watch event: no kind \"Node\" is registered for version \"v1\" in scheme \"pkg/runtime/scheme.go:101\"") has prevented the request from succeeding
```

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

No error/warning messages on Istiod deployment.

**Steps to reproduce the bug**

1. Get the IstioOperator manifest
```yaml
# manifest.yaml
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  addonComponents:
    kiali:
      enabled: true
      k8s:
        replicaCount: 3
    prometheus:
      enabled: false
    prometheusOperator:
      enabled: true
  components:
    base:
      enabled: true
    pilot:
      enabled: true
      k8s:
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
        hpaSpec:
          maxReplicas: 6
          metrics:
            - resource:
                name: cpu
                targetAverageUtilization: 80
              type: Resource
          minReplicas: 3
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: istiod
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 3
          timeoutSeconds: 5
        strategy:
          rollingUpdate:
            maxSurge: 100%
            maxUnavailable: 25%
    ingressGateways:
      - enabled: true
        k8s:
          env:
            - name: ISTIO_META_ROUTER_MODE
              value: sni-dnat
          hpaSpec:
            maxReplicas: 6
            metrics:
              - resource:
                  name: cpu
                  targetAverageUtilization: 80
                type: Resource
            minReplicas: 3
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: istio-ingressgateway
          resources:
            limits:
              cpu: 2000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 128Mi
          overlays:
            - apiVersion: v1
              kind: Service
              name: istio-ingressgateway
              patches:
                - path: spec.type
                  value: NodePort
                - path: spec.ports.[name:status-port].nodePort
                  value: 32717
                - path: spec.ports.[name:http2].nodePort
                  value: 32715
                - path: spec.ports.[name:https].nodePort
                  value: 32716
        name: istio-ingressgateway
    telemetry:
      enabled: true
      k8s:
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: GOMAXPROCS
            value: "6"
        hpaSpec:
          maxReplicas: 6
          metrics:
            - resource:
                name: cpu
                targetAverageUtilization: 80
              type: Resource
          minReplicas: 3
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: istio-telemetry
  meshConfig:
    rootNamespace: istio-system
    enableAutoMtls: true
  values:
    global:
      defaultPodDisruptionBudget:
        enabled: true
    kiali:
      dashboard:
        viewOnlyMode: true
```
2. Install Istio with `istioctl install -f manifest.yaml`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```bash
# istioctl version --remote
client version: 1.6.0
control plane version: 1.6.0
data plane version: 1.6.0 (7 proxies)
# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-15T15:50:25Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-f459c0", GitCommit:"f459c0672169dd35e77af56c24556530a05e9ab1", GitTreeState:"clean", BuildDate:"2020-03-18T04:24:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**
IstioOperator API
**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS
