### ISSUE TITLE
Can't override root namespace deny-all AuthorizationPolicy with namespace specific workload policy.

### ISSUE THREAD

**Issue by vitaliy-zinchenko** [istio/istio#24217]
**Bug description**

When the istio root namespace is used to deny-all authorization policy the requests are denied even when namespace specific workload policy is specified.

**What I try to achieve**
I want to deny-all across all namespaces by doing this:

```
# Deny everywhere
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-all
  namespace: istio-config # Istio Root namespace
spec:
  {}
```
And then put additional policy to allow requests to specific pods in specific namespaces.

After I applied the policy above any requests to istio enabled pod is denied, I tested it and it works as expected.

But when I add allow for specific pod:
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: open-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: testapp
  rules:
    - {}
```
Here I allow any request to the pod (with label "app: testapp"). And I still see the requests are denied despite my allow policy.
I would expect this last allow policy to open the requests.
Is it a bug or expected behaviour or I miss configure something?

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

I would expect when I use root namespace policy to deny-all, then I am able to allow requests for specific namespace and specific workload. But it seems to me that if I use root namespace based deny-all authorization policy the specific policies are ignored.

**Steps to reproduce the bug**

See above.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istioctl version --remote
client version: 1.5.1
control plane version: 1.5.1
data plane version: 1.5.1 (3 proxies)

kubectl version
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-beta.0", GitCommit:"14ede42c4fe699a7078b566d89abc160f26857a2", GitTreeState:"archive", BuildDate:"1970-01-01T00:00:01Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

**How was Istio installed?**

with helm

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS

**Comment by vitaliy-zinchenko** [comment]
I was able to resolve this issue by opening all for "istio-system" (where "istio-system" is not root in my case) namespace:

```

apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: open-for-istio-system-namespace
  namespace: istio-system
spec:
  rules:
    - {}

```

Don't know why it works for sure would like to hear some explanation from community. Please, clarify why it worked for me and is it good way to go?
