### ISSUE TITLE
OPERATOR: 1.6.0 with default profile:  proto: tag has too few fields: "-"

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#24223]
**Bug description**

```
2020-05-29T21:37:48.543008Z     info    installer       ReadProfileYAML for profile name: default
2020-05-29T21:37:48.543043Z     info    installer       Loading values from compiled in VFS at path profiles/default.yaml
2020-05-29T21:37:48.550526Z     info    proto: tag has too few fields: "-"
```

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

no tags errors in the log

**Steps to reproduce the bug**

1. istioctl operator init
2. Create IOP with:
```
apiVersion: install.istio.io/v1alpha1
  kind: IstioOperator
  metadata:
    name: istio
    namespace: istio-system
  spec:
    profile: default
```
3. check the operator logs

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.6.0

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
