### ISSUE TITLE
OPERATOR: Changing WATCH_NAMESPACE seems to cause controller to leak on delete

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#24222]
**Bug description**

Changing the operator controller WATCH_NAMESPACE to different that istio-system is causing some resources (pods and services) to not get cleaned up/pruned when the IOP is deleted.

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

The operator controller pod should cleanup it's resources properly regardless of where the IOP is located.

**Steps to reproduce the bug**

Failing scenario:
1. create ns ibm-operators #24073 
2.  ./istio-1.6.0/bin/istioctl operator init  --operatorNamespace ibm-operators --istioNamespace ibm-operators
3. create iop in ns ibm-operators with just:
```
  apiVersion: install.istio.io/v1alpha1
  kind: IstioOperator
  metadata:
    name: istio
    namespace: ibm-operators
  spec:
    profile: default
```
4. wait for control plane to come up in istio-system
5. k delete iop -n ibm-operators istio
6. pods and services in istio-system ns are not cleaned up

Working scenario:
1. create ns istio-system 
2.  ./istio-1.6.0/bin/istioctl operator init
3. create iop in ns istio-system with just:
```
  apiVersion: install.istio.io/v1alpha1
  kind: IstioOperator
  metadata:
    name: istio
    namespace:  istio-system
  spec:
    profile: default
```
4. wait for control plane to come up in istio-system
5. k delete iop -n  istio-system istio
6. pods and services in istio-system ns are cleaned up

Logs show a much shorter prune list for the failure case, but no obvious errors.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
