### ISSUE TITLE
EnvoyFilter workloadselector cannot handle `-` in the label name

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#24290]
EnvoyFilter workloadSelector fails to match anything if the label name contains a `-`.
This issue was found for Istio 1.4.

The following works
```yaml
WorkloadSelector:
  labels:
     alphakey: alphaval
```
The following  *does not* work.
```yaml
WorkloadSelector:
  labels:
     alpha-with-dash-key: alphaval
```

This needs to be verified  for 1.5 and 1.6.
If it works, it is ok to close this issue.
