### ISSUE TITLE
Apply Lua script filter will close existed http/2 long live connection

### ISSUE THREAD

**Issue by hobbytp** [istio/istio#24316]
**Bug description**
After I configure envoy.lua by using envoyfilter API, the existed HTTP2 connection will be closed by getting GOAWAY response. And later new re-created connection can work correctly.

My concern is the runtime configuration of envoy.lua shall NOT break the existed connection for it only add one more http filter under envoy.http_connection_manager.  Current behavious will make traffic lost when the envoy.lua takes effect, I don't think it is reasonable.

Any info need please let me know.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
After configure envoy.lua by using envoy filter API, the existed long live http2 connection shall not be closed by GOAWAY sending from envoy proxy, and later http request and response in the same http2 connection can go through the new added envoy lua filter after the lua filter takes effect.

**Steps to reproduce the bug**
The envoy filter is as below, when I configure it, the existed connections will be closed. but new created connection will print the log in lua filter.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-lua-ingress
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        portNumber: 8443 
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.cors"
    patch:
      operation: INSERT_BEFORE
      value: # lua filter specification
       name: envoy.lua
       typed_config:
         "@type": "type.googleapis.com/envoy.config.filter.http.lua.v2.Lua"
         inlineCode: |
           function envoy_on_request(request_handle)
             request_handle:logInfo("=========== Request ===========")   
           end
           
           function envoy_on_response(response_handle)   
             response_handle:logInfo("============= End =============")
           end
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istioctl version --remote
client version: 1.4.6
control plane version: 1.4.6
data plane version: 1.4.6 (8 proxies)

kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeSt
ate:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeSt
ate:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
istioctl install --set profile=demo

**Environment where bug was observed (cloud vendor, OS, etc)**
