### ISSUE TITLE
EnvoyFilter: Update UpstreamTlsContext config not working

### ISSUE THREAD

**Issue by smercier74** [istio/istio#24330]
**Bug description**
For a specific use case we need to update the Envoy configuration of the Egress gateway (Allow TLS renegotiation for a given out going domain with TLS 1.2). An EnvoyFilter patch is used to update the UpstreamTlsContext config. However the merge action doesn't work properly. Instead of updating the existing config it replaces all the current content by the new one. 

EnvoyFilter example:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: allow-tls-renegotiation
  namespace: istio-system
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      cluster:
        name: outbound|443||<domain>
    patch:
      operation: MERGE
      value:
        transportSocket:
          name: envoy.transport_sockets.tls
          typed_config:
              "@type": "type.googleapis.com/envoy.api.v2.auth.UpstreamTlsContext"
              allow_renegotiation: true
  workloadSelector:
    labels:
      istio: egressgateway
```

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Existing config:
```
        "transportSocket": {
            "name": "envoy.transport_sockets.tls",
            "typedConfig": {
                "@type": "type.googleapis.com/envoy.api.v2.auth.UpstreamTlsContext",
                "commonTlsContext": {
                    "tlsCertificates": [
                        {
                            "certificateChain": {
                                "filename": "/etc/..../tls.crt"
                            },
                            "privateKey": {
                                "filename": "[redacted]"
                            }
                        }
                    ]
                },
                "sni": "<domain>"
            }
        },
```
After the apply of the envoy filter patch, the istio-proxy config should be:
```
        "transportSocket": {
            "name": "envoy.transport_sockets.tls",
            "typedConfig": {
                "@type": "type.googleapis.com/envoy.api.v2.auth.UpstreamTlsContext",
                "commonTlsContext": {
                    "tlsCertificates": [
                        {
                            "certificateChain": {
                                "filename": "/etc/..../tls.crt"
                            },
                            "privateKey": {
                                "filename": "[redacted]"
                            }
                        }
                    ]
                },
                "sni": "<domain>",
                "allowRenegotiation": true
            }
        },
```
and not 
```
        "transportSocket": {
            "name": "envoy.transport_sockets.tls",
            "typedConfig": {
                "@type": "type.googleapis.com/envoy.api.v2.auth.UpstreamTlsContext",
                "allowRenegotiation": true
            }
        },
```
All existing settings are lost.

**Steps to reproduce the bug**
On an istio 1.5 env
- Create an endpoint for an external domain with mutual tls using TLS 1.2 via the egress gateway
- Check the config of the egress gateway envoy proxy:
     ```
     istioctl proxy-config cluster istio-egressgateway-.....istio-system --fqdn <domain> -o json 
     ```
- Create an envoy filter patch with merge action on the UpstreamTlsContext (allowRenegotiation for example)
- Apply the EnvoyFilter patch
- Check again the config. All existing settings sni, commonTlsContext are lost.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Istio 1.5.3

**How was Istio installed?**
Installed with Helm 2.14

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS 1.15 environment
Istio 1.5.3

**Comment by howardjohn** [comment]
its not a deep merge. Its merging at the cluster level. I don't think a deep merge like this is even entirely possible given we operator on arbitrary inputs - although we may be able to solve this specific case, as we do something similar for HTTP connection manager

cc @rshriram

**Comment by smercier74** [comment]
In the previous version of Istio 1.4.x we used an envoy filter like below to update the egress gateway config:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: allow-tls-renegotiation
spec:
  workloadSelector:
    labels:
      istio: egressgateway
  configPatches:
    - applyTo: CLUSTER
      match:
        cluster:
          name: outbound|<port>||<domain>
      patch:
        operation: MERGE
        value:
          tls_context:
            allow_renegotiation: true
            sni: <domain>
```
However since these apis are now deprecated and according to the doc: https://istio.io/docs/reference/config/networking/envoy-filter/#EnvoyFilter-ClusterMatch . We updated the envoy filter to match we new apis. 
Can you give us more detail about the method you speak to update the HTTP Connection Manager config ?

**Comment by smercier74** [comment]
Hello, do you have an idea if the hack applied on filters and hcm is applicable for the upstream tls context ? If yes do you have an idea about the version where it will be available ? 1.5.7 
Thanks in advance

**Comment by imcheck** [comment]
This will work ! :) @smercier74 
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: test
spec:
  workloadSelector:
    labels:
      istio: egressgateway
  configPatches:
  - applyTo: CLUSTER
    clusterMatch:
      name: outbound|<port>||<domain>
    patch:
      operation: MERGE
      value:
        transport_socket:
          name: "envoy.transport_sockets.tls"
          typed_config:
            "@type": "type.googleapis.com/envoy.api.v2.auth.UpstreamTlsContext"
            allow_renegotiation: true
```

**Comment by smercier74** [comment]
Thanks for your test @imcheck . Can you give us more details about how did you do your test because i did again a test with the EnvoyFilter below on istio 1.5.3 and the merge result is not good ? The existing config is always lost.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: signature-management-allow-tls-renegotiation-sni
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: egressgateway
  configPatches:
  - applyTo: CLUSTER
    clusterMatch:
      name: outbound|<port>||<domain>
    patch:
      operation: MERGE
      value:
        transport_socket:
          name: "envoy.transport_sockets.tls"
          typed_config:
            "@type": "type.googleapis.com/envoy.api.v2.auth.UpstreamTlsContext"
            allow_renegotiation: true
```
Result obtained:
```
        "transportSocket": {
            "name": "envoy.transport_sockets.tls",
            "typedConfig": {
                "@type": "type.googleapis.com/envoy.api.v2.auth.UpstreamTlsContext",
                "allowRenegotiation": true
            }
        },
```
Result expected:
```
        "transportSocket": {
            "name": "envoy.transport_sockets.tls",
            "typedConfig": {
                "@type": "type.googleapis.com/envoy.api.v2.auth.UpstreamTlsContext",
                "commonTlsContext": {
                    "tlsCertificates": [
                        {
                            "certificateChain": {
                                "filename": "/etc/..../tls.crt"
                            },
                            "privateKey": {
                                "filename": "[redacted]"
                            }
                        }
                    ]
                },
                "sni": "<domain>",
                "allowRenegotiation": true
            }
        },
```
