### ISSUE TITLE
VirtualService/HTTPRedirect: URI overwriting query parameters

### ISSUE THREAD

**Issue by cupello** [istio/istio#24354]
We are having an issue with Istio Virtual Service HttpRedirect. According to the documentation (https://istio.io/docs/reference/config/networking/virtual-service/#HTTPRedirect) when a URI value is provided just the path portion of the URL should be overwritten, but the whole query string is being overwritten too. Am I missing something or this is a bug?

Thanks in advance.

**Comment by bunchesofdonald** [comment]
We're having the same issue, it would be really nice to be able to preserve query params.

**Comment by howardjohn** [comment]
I could not reproduce

```yaml

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test
spec:
  hosts:
  - echo
  http:
  - match:
    - uri:
        exact: /v1/getProductRatings
    redirect:
      uri: /v1/bookRatings
  - match:
    - uri:
        exact: /v1/bookRatings
    route:
    - destination:
        host: echo
        port:
          number: 8080
```

```
$ curl echo:8080/v1/getProductRatings?foo=bar -L
ServiceVersion=
ServicePort=8080
Host=echo:8080
URL=/v1/bookRatings?foo=bar
```

Seems it is preserved? Am I missing something?

**Comment by cupello** [comment]
Hi @howardjohn, 

I have tried again and the problem still occurs at version 1.6.7:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
    name: istio-vs
spec:
    hosts:
    - "istio-gateway-test"
    gateways:
    - istio-ingressgateway
    http:
    - match:
      - uri:
          exact: /v1/getProductRatings
      redirect:
        uri: /v1/bookRatings
```
```
curl -v ".../v1/getProductRatings?foo=bar"
> GET /v1/getProductRatings?foo=bar HTTP/1.1
> User-Agent: curl/7.68.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Date: Thu, 06 Aug 2020 17:49:20 GMT
< Content-Length: 0
< Connection: keep-alive
< location: http://istio-gateway-test/v1/bookRatings
< server: istio-envoy
```

Which version are you using?
