### ISSUE TITLE
Unable to create VirtualService (delegate)

### ISSUE THREAD

**Issue by robert-blackman** [istio/istio#24368]
**Bug description**

When following [this](https://istio.io/docs/reference/config/networking/virtual-service/#Delegate) document to create a `VirtualService` describing a delegate `VirtualService`. Istio validation fails with: `HTTP route or redirect is required`, however the docs also state that `It (delegate) can be set only when Route and Redirect are empty`.

**Expected behavior**

`VirtualService` is created successfully.

**Steps to reproduce the bug**

Attempting to apply the following manifest results in the error message.

<details open>
<summary>example</summary>

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - "bookinfo.com"
  gateways:
  - mygateway
  http:
  - match:
    - uri:
        prefix: "/productpage"
    delegate:
       name: productpage
       namespace: nsA
  - match:
    - uri:
        prefix: "/reviews"
    delegate:
        name: reviews
        namespace: nsB
```
</details>

**Version**

```
client version: 1.6.0
control plane version: 1.6.0
data plane version: 1.6.0 (35 proxies)
```
Though I did see this with 1.5.1 too.

**How was Istio installed?**

istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS EKS 1.15
