### ISSUE TITLE
Request denied with RequestAuthentication and an unknown jwt token and an allowing AuthorizationPolicy 

### ISSUE THREAD

**Issue by btoonk** [istio/istio#24371]
**Bug description**

With a RequestAuthentication active in a namespace all requests with an invalid or unknown jwt token is getting denied. While this seems normal behavior this also happens with an authorizationpolicy active in the same namespace which should allow all requests from the namespace or source IPs.

RequestAuthentication:
```
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: default
  namespace: test
spec:
  jwtRules:
  - issuer: aaa-auth
    jwksUri: https://<url-to-keys>/keys
```
AuthorizationPolicy:
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-own-namespace
  namespace: test
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces:
        - test
```

A request returns a 401 with the message "Jwt issuer is not configured" or "Jwt is not in the form of Header.Payload.Signature".

With Istio 1.4.x and the authenticationpolicy this was allowed.
Is this expected behavior?

[ ] Configuration Infrastructure
[x ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

If a namespace is allowed with an AuthorizationPolicy all requests from that namespace should be allowed regardless of what jwt token is provided in the request.

**Steps to reproduce the bug**

Create the described policies and request a service in that namespace with a jwt token.
`curl -v -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ0b3B0YWwuY29tIiwiZXhwIjoxNDI2NDIwODAwLCJodHRwOi8vdG9wdGFsLmNvbS9qd3RfY2xhaW1zL2lzX2FkbWluIjp0cnVlLCJjb21wYW55IjoiVG9wdGFsIiwiYXdlc29tZSI6dHJ1ZX0.yRQYnWzskCZUxPwaQupWkiUzKELZ49eM7oWxAQK_ZXw" http://service`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.5.x and above

**How was Istio installed?**

istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE
