### ISSUE TITLE
istioctl verify-install doesn't work with custom gateway

### ISSUE THREAD

**Issue by akhamar** [istio/istio#24374]
**Bug description**
If you create a custom profile with custom ingress gateway (and with custom deployment name) while deactivating the default gateway, you will get an error during the verify-install command.
The very-install will be looking for a deployment called istio-ingressgateway which doesn't exist

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
istioctl verify-install should properly give a green status on the installation

**Steps to reproduce the bug**

Create a custom profile from the default one.
`istioctl profile dump default > TO_SOME_CUSTOM_PROFILE_FILE`

Edit this file (TO_SOME_CUSTOM_PROFILE_FILE) with the following in the spec > components > ingressGateways
```
      # Public gateway
      - name: public-istio-ingressgateway
        enabled: true
        label:
          app: public-ingress
          istio: ingressgateway
        k8s:
          env:
            - name: ISTIO_META_ROUTER_MODE
              value: sni-dnat
          hpaSpec:
            maxReplicas: 4
            metrics:
              - resource:
                  name: cpu
                  targetAverageUtilization: 80
                type: Resource
            minReplicas: 2
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: public-istio-ingressgateway
          resources:
            limits:
              cpu: 2000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 128Mi
          service:
            ports:
              - name: status-port
                port: 15021
                targetPort: 15021
              - name: http2
                port: 80
                targetPort: 8080
              - name: https
                port: 443
                targetPort: 8443
              - name: tls
                port: 15443
                targetPort: 15443
          strategy:
            rollingUpdate:
              maxSurge: 100%
              maxUnavailable: 25%

      # Private gateway
      - name: private-istio-ingressgateway
        enabled: true
        label:
          app: private-ingress
          istio: ingressgateway
        k8s:
          env:
            - name: ISTIO_META_ROUTER_MODE
              value: sni-dnat
          hpaSpec:
            maxReplicas: 4
            metrics:
              - resource:
                  name: cpu
                  targetAverageUtilization: 80
                type: Resource
            minReplicas: 2
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: private-istio-ingressgateway
          resources:
            limits:
              cpu: 2000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 128Mi
          service:
            ports:
              - name: status-port
                port: 15021
                targetPort: 15021
              - name: http2
                port: 80
                targetPort: 8080
              - name: https
                port: 443
                targetPort: 8443
              - name: tls
                port: 15443
                targetPort: 15443
          strategy:
            rollingUpdate:
              maxSurge: 100%
              maxUnavailable: 25%

      # Deactivate default gateway
      - name: istio-ingressgateway
        enabled: false
```

Install istio with the custom profil
`istioctl manifest apply -f TO_SOME_CUSTOM_PROFILE_FILE`

Verify istio install
`istioctl verify-install -f TO_SOME_CUSTOM_PROFILE_FILE`
> IstioOperator: .default checked successfully
> Checked 25 custom resource definitions
> Checked 0 Istio Deployments
> No Istio installation found
> Error: no Istio installation found

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

`istioctl version --remote`
> client version: 1.6.0
> control plane version: 1.6.0
> data plane version: 1.6.0 (5 proxies)

`kubectl version`
> Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-gke.15", GitCommit:"9cabee15e0922c3b36724de4866a98f6c2da5e6a", GitTreeState:"clean", BuildDate:"2020-05-01T21:47:04Z", GoVersion:"go1.13.8b4", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
With a custom profile from the default one.

**Environment where bug was observed (cloud vendor, OS, etc)**
