### ISSUE TITLE
Allow injection webhook to be namespace scoped

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#24383]
**Describe the feature request**

Allow the sidecar injection webhook to be namespaced scoped such that a list of namespaces (kube-system, ...) could be optd out of injection.

The raw issue is that whenever the injection webhook pod is down, pod creates start to fail for all namespaces.   When that happens for critical pods in kube-system, the cluster can begin to do down.

**Describe alternatives you've considered**

1. More HA and priority around the istiod pod, but it can still go down for various reasons.
2. namespaceSelector in the webhook, but this requires that namespaces have labeling in place to base the selector on.   This might be a good workaround.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

Current webhook spec:
```
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle:  xxx 
  service:
      name: istiod
      namespace: istio-system
      path: /inject
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: sidecar-injector.istio.io
  namespaceSelector:
    matchLabels:
      istio-injection: enabled
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 30
```
