### ISSUE TITLE
Multiple Ingress resources with same host result in 404 for HTTPS

### ISSUE THREAD

**Issue by verysonglaa** [istio/istio#24385]
**Bug description**
Multiple ingress resources with the same hostname will result in http 404 with https (but not http) (same like https://istio.io/docs/ops/common-problems/network-issues/#404-errors-occur-when-multiple-gateways-configured-with-same-tls-certificate , I guess an ingress resource create also a gw in the background). Also gateways serving the same hosts will not work anymore.

I guess this should be mentioned in the docs as well. Also a solution without virtualservice but using multiple ingress resources with tls and the same hostname should be possible (we have many ingress in different namespaces from different teams but only one hostname). In 1.5.4. with istio-autogenerated-k8s-ingress this was no problem.

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
HTTP 200 instead of 404 for https connections

**Steps to reproduce the bug**
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echoserver-ingress-2
  namespace: echoserver
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - host: testurl.com
    http:
      paths:
      - backend:
          serviceName: echo-service
          servicePort: 80
        path: /echoserver2
  tls:
  - hosts:
    - testurl.com
    secretName: ingressgateway-certs
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echoserver-ingress-1
spec:
  rules:
  - host: testurl.com
    http:
      paths:
      - backend:
          serviceName: echo-service
          servicePort: 80
        path: /echoserver1
  tls:
  - hosts:
    - testurl.com
    secretName: ingressgateway-certs
```
now try to open both urls in browser:
testurl.com//echoserver2 -> 200
testurl.com//echoserver1 -> 404

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
k8s: 1.15.7

istioctl version
client version: 1.6.0
control plane version: 1.6.0
data plane version: 1.6.0 (3 proxies)

**How was Istio installed?**
IstioOperator

**Comment by howardjohn** [comment]
Does this work if you have 1 Ingress like:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echoserver-ingress-1
spec:
  rules:
  - host: testurl.com
    http:
      paths:
      - backend:
          serviceName: echo-service
          servicePort: 80
        path: /echoserver1
  - host: testurl.com
    http:
      paths:
      - backend:
          serviceName: echo-service
          servicePort: 80
        path: /echoserver2
  tls:
  - hosts:
    - testurl.com
    secretName: ingressgateway-certs
```

?

Or are the Ingress in different namespaces even?
