### ISSUE TITLE
outlierDetection.maxEjectionPercent not working without annotations sidecar.istio.io/statsInclusionPrefixes: cluster.outbound

### ISSUE THREAD

**Issue by packyzbq** [istio/istio#24419]
**Bug description**
I am testing the circuit breaking settings. I create 4 pods which always response 502 error, then I start a fortio pod with annotation `sidecar.istio.io/statsInclusionPrefixes: cluster.outbound`，the dr is as follows:
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: bc-httpbin
spec:
  host: bc-httpbin
  subsets:
  - labels:
      version: v1
    name: v1
  trafficPolicy:
    outlierDetection:
      baseEjectionTime: 10s
      consecutiveErrors: 3
      interval: 1s
      maxEjectionPercent: 50
```
I use command `kubectl exec $fortio-pod -n test -- /usr/bin/fortio load -c 2 -qps 0 -n 20 http://bc-httpbin:38080/get ` to test the  circuit breaking and it's working. Only 2 pods response and other 2 pods receive nothing.

However when I delete the fortio's annotation `sidecar.istio.io/statsInclusionPrefixes: cluster.outbound` , the `maxEjectionPercent` setting doesn't work. As a result, all pods are removed from connection pool and receive nothing. It seems `maxEjectionPercent` changed to 100.

I think this annotation is only used to control which statistics can be display, not to control the actual actions.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Without the annotation, circuits breaking settings are working.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio: 1.5.4
k8s: 1.18.3

**How was Istio installed?**
`istioctl manifest apply --set profile=demo`

**Environment where bug was observed (cloud vendor, OS, etc)**
