### ISSUE TITLE
Host Based Routing fails when tls mode is set as PASSTHROUGH in Gateway

### ISSUE THREAD

**Issue by Adharsh-Muraleedharan** [istio/istio#24424]
**Bug description**
When the Gateway has tls set as "PASSTHROUGH" we are unable to specify any host value other than a generic all allowing "*" in our virtualservice. If the host value is mentioned we are getting a 502 BAD GATEWAY error.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
To allow host based routing by allowing traffic to route to services based on the host mentioned in the virtualservice.

**Steps to reproduce the bug**
Applying the below gateway and virtual service. when i am hitting the host (https://somename.somedomain.com) receiving a bad gateway error.

If i replace the host and snihosts in the gateway and virtualservice with an "*" allowing all it routes to my service correctly. This is seen when we are setting the tls mode as PASSTHROUGH.

```apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mygateway1
  namespace: test
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
    hosts:
    - 'somename.somedomain.com'
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-vs
  namespace: test
spec:
  hosts:
  - 'somename.somedomain.com'
  gateways:
  - mygateway1
  tls:
  - match:
    - port: 443
      sniHosts:
      - 'somename.somedomain.com'
    route:
    - destination:
        host: test-service
        port:
          number: 443

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**
Istio was installed through Istioctl manifest generate 
**Istioctl versions**
client version: 1.5.2
control plane version: 1.5.2
data plane version: 1.5.2 (22 proxies)
**kubectl version**
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS cloud

**Comment by Adharsh-Muraleedharan** [comment]
@ramaraochavali - Could you help us with this ?

**Comment by howardjohn** [comment]
I could not reproduce. Config:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mygateway1
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
    hosts:
    - 'foo.<myip>.nip.io'
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-vs
spec:
  hosts:
  - 'foo.<myip>.nip.io'
  gateways:
  - mygateway1
  tls:
  - match:
    - port: 443
      sniHosts:
      - 'foo.<myip>.nip.io'
    route:
    - destination:
        host: echo
        port:
          number: 8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: echo
  namespace: default
spec:
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - args:
        - --tcp=7070
        - --port=8080
        - --grpc=9090
        - --port=8443
        - --tls=8443
        - --crt=/cert.crt
        - --key=/cert.key
        image: gcr.io/istio-testing/app:latest
        imagePullPolicy: Always
        name: echo
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
  - name: tcp
    port: 7070
  - name: grpc
    port: 9090
  - name: https
    port: 8443
  selector:
    app: echo
```

Can you provide more info? https://github.com/istio/istio/wiki/Troubleshooting-Istio Specficially config dump and access logs from the server and ingress
