### ISSUE TITLE
Configuring components.ingressGateways.k8s.service.externalTrafficPolicy breaks ingress gateways

### ISSUE THREAD

**Issue by XanderStrike** [istio/istio#24432]
**Bug description**

Setting `externalTrafficPolicy` to `Local` wipes out all the default configuration for the ingressgateway service, including the ports.

[x] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
A valid service is generated with a mix of configured values and defaults.
When generating a manifest with the following configuration:

**Steps to reproduce the bug**

Generate a manifest using the following IstioOperator:
```
apiVersion: install.istio.io/v1alpha2
kind: IstioOperator
spec:
  hub: gcr.io/cf-routing
  profile: default
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          service:
             externalTrafficPolicy: Local
```

**Observed:**
The istio-ingressgateway service lacks any ports:

```
apiVersion: v1
kind: Service
metadata:
  annotations: null
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
  externalTrafficPolicy: Local
  ports: null
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  type: LoadBalancer
```

**Desired:**
A valid service is produced:

```
apiVersion: v1
kind: Service
metadata:
  annotations: null
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
  externalTrafficPolicy: Local
  ports:
  - name: status-port
    port: 15021
    targetPort: 15021
  - name: http2
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8443
  - name: tls
    port: 15443
    targetPort: 15443
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  type: LoadBalancer
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
17:48 $ istioctl version
client version: 1.6.0
```

**How was Istio installed?**
N/A

**Environment where bug was observed (cloud vendor, OS, etc)**
N/A
