### ISSUE TITLE
Pilot crash when set illegal host in sidecar resource

### ISSUE THREAD

**Issue by ydh926** [istio/istio#24453]
**Bug description**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Steps to reproduce the bug**
1. disable validatingwebhook
2.  apply a illegal sidecar
```yaml
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: a
  namespace: powerful-debug-2
spec:
  egress:
  - bind: 0.0.0.0
    hosts:
    - b
  workloadSelector:
    labels:
      app: a

```
3. pilot crash
```
panic: runtime error: index out of range [1] with length 1

goroutine 4397 [running]:
istio.io/istio/pilot/pkg/model.convertIstioListenerToWrapper(0xc009e2a3c0, 0xc00104bd30, 0x10, 0xc002d52660, 0x1)
	/home/yangdihang/work/go/gopath/src/istio.io/istio/pilot/pkg/model/sidecar.go:275 +0x5b9
istio.io/istio/pilot/pkg/model.ConvertToSidecarScope(0xc009e2a3c0, 0xc00363c420, 0xc00104bd30, 0x10, 0x3)
	/home/yangdihang/work/go/gopath/src/istio.io/istio/pilot/pkg/model/sidecar.go:206 +0x15a
istio.io/istio/pilot/pkg/model.(*PushContext).initSidecarScopes(0xc009e2a3c0, 0xc0003bcf30, 0x0, 0x0)

```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

build from master
