### ISSUE TITLE
gateway.runAsRoot has invalid fields

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#24469]
```
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        privileged: false
        readOnlyRootFilesystem: true
```

Are only valid on container.securityContext, not pod.securityContext.

Somehow `istioctl install` works but `istioctl manifest generate` fails.. need to investigate more
