### ISSUE TITLE
Unable to modify components via standalone operator

### ISSUE THREAD

**Issue by ranjb** [istio/istio#24465]
**Bug description**

When the istio control plane services are deployed through the standalone operator install, modification (enable/disable) of these services is not possible after the initial install. This should be possible per the [docs](https://istio.io/docs/setup/install/standalone-operator/#update)

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Expected behavior**

It should be possible to add/remove components after the initial install by reapplying the modified configuration

**Steps to reproduce the bug**

- Deploy standalone operator
`istioctl operator init`
- Apply initial configuration to deploy control plane services. Example below:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: my-k8s-istiocontrolplane
spec:
  profile: minimal
  tag: "1.6.1"
  addonComponents:
    kiali:
      enabled: false
      k8s:
        replicaCount: 1
    tracing:
      enabled: true
```
- Now try adding a component, for e.g. Prometheus
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: my-k8s-istiocontrolplane
spec:
  profile: minimal
  tag: "1.6.1"
  addonComponents:
    prometheus:
      enabled: true
      k8s:
        replicaCount: 1
    kiali:
      enabled: false
      k8s:
        replicaCount: 1
    tracing:
      enabled: true
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ istioctl version --remote
client version: 1.6.1
control plane version: 1.6.1
data plane version: none

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:08:59Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

Standalone operator install as described in the "Steps to Reproduce" section

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS, Kubernetes v1.15.11 (kops), flatcar OS
