### ISSUE TITLE
Connecting to external docker registry

### ISSUE THREAD

**Issue by munjalpatel** [istio/istio#24475]
Hello,

I am setting up local k8s environment with `istio` `demo` profile.
I also have a `docker registry` setup on my local machine outside of k8s.

Here is how I configured my local `k8s` cluster and `docker registry`
```shell
#!/bin/sh
set -o errexit

# create registry container unless it already exists
reg_name='kind-registry'
reg_port='5000'
running="$(docker inspect -f '{{.State.Running}}' "${reg_name}" 2>/dev/null || true)"
if [ "${running}" != 'true' ]; then
  docker run \
    -d --restart=always -p "${reg_port}:5000" --name "${reg_name}" \
    registry:2
fi

# create a cluster with the local registry enabled in containerd
cat <<EOF | kind create cluster --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 32000
    hostPort: 80
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:${reg_port}"]
    endpoint = ["http://${reg_name}:${reg_port}"]
EOF

# connect the registry to the cluster network
docker network connect "kind" "${reg_name}"

# tell https://tilt.dev to use the registry
# https://docs.tilt.dev/choosing_clusters.html#discovering-the-registry
for node in $(kind get nodes); do
  kubectl annotate node "${node}" \
    "kind.x-k8s.io/registry=localhost:${reg_port}" \
    "tilt.dev/registry=localhost:${reg_port}" \
    "tilt.dev/registry-from-cluster=${reg_name}:${reg_port}";
done
```

And here is how I configured `istio`
```shell
# Setup Istio
curl -L https://github.com/istio/istio/releases/download/1.5.1/istioctl-1.5.1-osx.tar.gz | tar xvz -
sudo mv istioctl /usr/local/bin
istioctl manifest apply --set profile=demo
istioctl manifest generate --set profile=demo | istioctl verify-install -f -
kubectl patch service istio-ingressgateway -n istio-system --patch "$(cat ./config/patch-ingressgateway-nodeport.yaml)"

# Setup Knative
kubectl apply -f https://github.com/knative/serving/releases/download/v0.14.0/serving-crds.yaml
kubectl apply -f https://github.com/knative/serving/releases/download/v0.14.0/serving-core.yaml
kubectl apply -f https://github.com/knative/net-istio/releases/download/v0.14.0/net-istio.yaml
kubectl apply -f https://github.com/knative/serving/releases/download/v0.14.0/serving-hpa.yaml
kubectl patch configmap/config-domain \
  --namespace knative-serving \
  --type merge \
  --patch '{"data":{"127.0.0.1.nip.io":""}}'
```

I am deploying the following `knative` service:
```yaml
apiVersion: v1
data:
  TWITTER_TOKEN_KEY: base64-encoded-value
  TWITTER_TOKEN_SECRET: base64-encoded-value
kind: Secret
metadata:
  name: svc-data-twitter
type: Opaque
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: svc-data-twitter
spec:
  template:
    spec:
      containers:
      - env:
        - name: TWITTER_TOKEN_KEY
          valueFrom:
            secretKeyRef:
              key: TWITTER_TOKEN_KEY
              name: svc-data-twitter
        - name: TWITTER_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              key: TWITTER_TOKEN_SECRET
              name: svc-data-twitter
        image: svc-data-twitter:dev
```

However, creating of the service fails since k8s is not able to fetch an image from my local docker registry configured in the previous step.

Here is the error I get:
```
[K8s EVENT: Revision svc-data-twitter-xwr8d (ns: default)] failed to resolve image to 
digest: failed to fetch image information: Get https://kind-registry:5000/v2/: 
http: server gave HTTP response to HTTPS client
```

It seems like `istio` is upgrading `http` request to `https` while my private registry is not setup with TLS. Hence the failure.

Is there a way to allow non-https traffic to a single endpoint? In this case: `http://kind-registry:5000`.
