### ISSUE TITLE
Unable to configure EnvoyFilter to do auth redirect

### ISSUE THREAD

**Issue by kopasiak** [istio/istio#24480]
**Bug description**

I'm trying to prepare a setup with TLS termination at ingress-gateway, JWT based authz and automated redirection to the login page when user arrives without a valid JWT token.
Currently everything works fine apart from redirection to login page.

I've tried to used both "new" and "old" style to define EnvoyFilters:
New:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: authn-filter
  namespace: istio-system
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.router"
      patch:
        # For some reason, INSERT_FIRST doesn't work
        operation: INSERT_BEFORE
        value:
          name: "envoy.filters.http.ext_authz"
          config:
            http_service:
              server_uri:
                uri: http://oauthproxy-service.auth-proxy.svc.cluster.local
                cluster: outbound|4180||oauthproxy-service.auth-proxy.svc.cluster.local
                timeout: 10s
              authorization_request:
                allowed_headers:
                  patterns:
                  - exact: "cookie"
                  - exact: "x-forwarded-access-token"
                  - exact: "x-forwarded-user"
                  - exact: "x-forwarded-email"
                  - exact: "authorization"
                  - exact: "x-forwarded-proto"
                  - exact: "proxy-authorization"
                  - exact: "user-agent"
                  - exact: "x-forwarded-host"
                  - exact: "from"
                  - exact: "x-forwarded-for"
                  - exact: "accept"
                  - prefix: "x-forwarded"
                  - prefix: "x-auth-request"
              authorization_response:
                allowedClientHeaders:
                  patterns:
                  - exact: "location"
                  - exact: "proxy-authenticate"
                  - exact: "set-cookie"
                  - exact: "authorization"
                  - exact: "www-authenticate"
                  - prefix: "x-forwarded"
                  - prefix: "x-auth-request"
                allowedUpstreamHeaders:
                  patterns:
                  - exact: "location"
                  - exact: "proxy-authenticate"
                  - exact: "set-cookie"
                  - exact: "authorization"
                  - exact: "www-authenticate"
                  - prefix: "x-forwarded"
                  - prefix: "x-auth-request"
```
old:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: authn-filter
  namespace: istio-system
spec:
  workloadLabels:
    app: istio-ingressgateway
  filters:
  - filterConfig:
      http_service:
        server_uri:
          uri: http://oauthproxy-service.auth-proxy.svc.cluster.local
          cluster: outbound|4180||oauthproxy-service.auth-proxy.svc.cluster.local
          timeout: 10s
        authorizationRequest:
          allowedHeaders:
            patterns:
            - exact: "cookie"
            - exact: "x-forwarded-access-token"
            - exact: "x-forwarded-user"
            - exact: "x-forwarded-email"
            - exact: "authorization"
            - exact: "x-forwarded-proto"
            - exact: "proxy-authorization"
            - exact: "user-agent"
            - exact: "x-forwarded-host"
            - exact: "from"
            - exact: "x-forwarded-for"
            - exact: "accept"
            - prefix: "x-forwarded"
            - prefix: "x-auth-request"
        authorizationResponse:
          allowedClientHeaders:
            patterns:
            - exact: "location"
            - exact: "proxy-authenticate"
            - exact: "set-cookie"
            - exact: "authorization"
            - exact: "www-authenticate"
            - prefix: "x-forwarded"
            - prefix: "x-auth-request"
          allowedUpstreamHeaders:
            patterns:
            - exact: "location"
            - exact: "proxy-authenticate"
            - exact: "set-cookie"
            - exact: "authorization"
            - exact: "www-authenticate"
            - prefix: "x-forwarded"
            - prefix: "x-auth-request"
      statusOnError:
        code: GatewayTimeout
    filterName: envoy.ext_authz
    filterType: HTTP
    insertPosition:
      index: FIRST
    listenerMatch:
      portNumber: 443
      listenerType: GATEWAY
```
Unfortunately non of them works. Nothing happens when I create those resources I always get "RBAC: access denied" just like it was before creating EnvoyFilter.

[x ] Configuration Infrastructure
[ x] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

When I access the webpage without a valid JWT token I should be redirected to the login page

**Steps to reproduce the bug**

Create any service, expose it via ingress and add JWT filtering.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Kubectl
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:08:59Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```
istioctl
```
client version: 1.6.0
control plane version: 1.6.0
data plane version: 1.6.0 (16 proxies)
```

**Environment where bug was observed (cloud vendor, OS, etc)**
OpenStack VM, kubernetes 1.15.11

**Comment by yangminzhu** [comment]
How do you expect the EnvoyFilter to redirect to a login page?

**Comment by kopasiak** [comment]
@yangminzhu 
Yes that's exactly what we are trying to achieve

**Comment by kopasiak** [comment]
> How do you expect the EnvoyFilter to redirect to a login page?

I'm not an expert on this but I based my assumption on this blog post:
https://homelab.blog/blog/devops/Istio-OIDC-Config/

**Comment by kopasiak** [comment]
> envoy config dump from the gateway would help. Just need the HTTP Connection manager config for that port

Any hint how to extract this from a running instance?

**Comment by c-p-i-o** [comment]
> > envoy config dump from the gateway would help. Just need the HTTP Connection manager config for that port
> 
> Any hint how to extract this from a running instance?

I think you can get the dump by running the following command on istio 1.6.x
`istioctl experimental authz check <name of pod>`

**Comment by howardjohn** [comment]
https://github.com/istio/istio/wiki/Troubleshooting-Istio to get config dump

**Comment by jeesmon** [comment]
@kopasiak With the help of below two blog posts and hours of troubleshooting, I think we have a working setup and would like to share if that helps you in anyway.

Blog posts:

* https://homelab.blog/blog/devops/Istio-OIDC-Config/ (The link you mentioned but it's based on old version of Istio)
* https://www.paraesthesia.com/archive/2020/09/03/setting-up-oauth2-proxy-with-istio/ (Updated for new Istio version)

Our working config:

EnvoyFilter:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: auth-filter
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              # In Istio 1.6.4 this is the first filter. The examples showing insertion
              # after some other authorization filter or not showing where to insert
              # the filter at all didn't work for me. Istio just failed to insert the
              # filter (silently) and moved on.
              name: istio.metadata_exchange
          sni: "xxxx.yyyy.nip.io"
    patch:
      operation: INSERT_AFTER
      value:
        name: envoy.filters.http.ext_authz
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
          http_service:
            authorizationRequest:
              allowedHeaders:
                patterns:
                - exact: accept
                - exact: authorization
                - exact: cookie
                - exact: from
                - exact: proxy-authorization
                - exact: user-agent
                - exact: x-forwarded-access-token
                - exact: x-forwarded-email
                - exact: x-forwarded-for
                - exact: x-forwarded-host
                - exact: x-forwarded-proto
                - exact: x-forwarded-user
                - prefix: x-auth-request
                - prefix: x-forwarded
            authorizationResponse:
              allowedClientHeaders:
                patterns:
                - exact: authorization
                - exact: location
                - exact: proxy-authenticate
                - exact: set-cookie
                - exact: www-authenticate
                - prefix: x-auth-request
                - prefix: x-forwarded
              allowedUpstreamHeaders:
                patterns:
                - exact: authorization
                - exact: location
                - exact: proxy-authenticate
                - exact: set-cookie
                - exact: www-authenticate
                - prefix: x-auth-request
                - prefix: x-forwarded
            server_uri:
              # URIs here should be to the oauth2-proxy service inside your
              # cluster, in the namespace where it was deployed. The port
              # in that 'cluster' line should also match up.
              cluster: outbound|80||auth-proxy.oauth.svc.cluster.local
              timeout: 1.5s
              uri: http://auth-proxy.oauth.svc.cluster.local
```

Gateway:

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: tenant-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "xxxx.yyyy.nip.io"
    port:
      # The name here must be unique across all of the ports named
      # in the Istio ingress.
      name: http-xxxx-yyyy-nip-io
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - "xxxx.yyyy.nip.io"
    port:
      # The name here must be unique across all of the ports named
      # in the Istio ingress.
      name: https-xxxx-yyyy-nip-io
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
```

Tricky part is troubleshooting the proxy config.

1. After you created Gateway and EnvoyProxy, make sure the listener for your gateway is created correctly. You can run the following command to verify it.

`istioctl pc listener istio-ingressgateway-xxxx-yyyy.istio-system -o json` where `istio-ingressgateway-xxxx-yyyy` is the name of the ingressgateway pod in istio-system namespace.

In the json output, make sure you have a section with the details like below:

```
               "filterChainMatch": {
                    "serverNames": [
                        "xxxx.yyyy.nip.io", <- Host(s) in your Gateway
                    ]
                },
                "filters": [
                    {
                        "name": "mixer",
....
                               {
                                    "name": "envoy.filters.http.ext_authz",
                                    "typedConfig": {
                                        "@type": "type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz",
                                        "httpService": {
                                            "serverUri": {
                                                "uri": "http://auth-proxy.oauth.svc.cluster.local",
                                                "cluster": "outbound|80||auth-proxy.oauth.svc.cluster.local",
                                                "timeout": "1.500s"
                                            },
                                            "authorizationRequest": {
                                                "allowedHeaders": {
                                                    "patterns": [
                                                        {
                                                            "exact": "accept"
                                                        },
                                                        {
                                                            "exact": "authorization"
....
```

As you can see, the patch in your EnvoyFilter is applied to the listener

2. Make sure `server_uri:` is configured correctly in your EnvoyFilter. If either service name in `cluster` doesn't match with `uri` or port in `cluster` is wrong, you will not see successful redirection. In my case, I run an nginx reverse proxy in front of oauth2-proxy and that's why you see port 80 in my config. Direct use oauth2-proxy on port 4180 should work well too. I use nginx to proxy_pass multiple oath2-proxy pods based on vhost in my case.

Hope this will give you or anyone some clue for troubleshooting EnvoyFilter config.
