### ISSUE TITLE
error "no matches for kind "MeshPolicy" in version "authentication.istio.io/v1alpha1"

### ISSUE THREAD

**Issue by woodliu** [istio/istio#24502]
**Bug description**
Deploy Policy according to the [doc](https://istio.io/docs/ops/diagnostic-tools/istioctl-describe/#verifying-strict-mutual-tls)
```
kubectl apply -f - <<EOF
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "ratings-strict"
spec:
  targets:
  - name: ratings
  peers:
  - mtls:
      mode: STRICT
EOF
```
It shows `error: unable to recognize "STDIN": no matches for kind "MeshPolicy" in version "authentication.istio.io/v1alpha1"`

[ ] Configuration Infrastructure
[X] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Deploy successfully
**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
# istioctl version --remote
client version: 1.6.0
control plane version: 1.6.0
data plane version: 1.6.0 (3 proxies)
# oc version
Client Version: 4.3.5
Server Version: 4.3.5
Kubernetes Version: v1.16.2
```

**How was Istio installed?**
I tried demo profile and default profile,but the same result
**Environment where bug was observed (cloud vendor, OS, etc)**
Openshift 4.3
