### ISSUE TITLE
VirtualService retries repeatedly try the same destination instead of trying a different one

### ISSUE THREAD

**Issue by XanderStrike** [istio/istio#24512]
**Bug description**

When a VirtualService is configured with retries, the ingress envoy is configured to hit the same host repeatedly, instead of trying other hosts which may be healthy.

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Steps to reproduce the bug**

Create the following deployments, services, and virtual service:

Context: The `xanderstrike/resp` image will always return an empty HTTP response with the value of the RESPONSE_STATUS environment variable as the status response code.

<details>
<summary>Click here to expand</summary>

```
---
apiVersion: v1
kind: Service
metadata:
  name: good
  labels:
    app: good
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: good
---
apiVersion: v1
kind: Service
metadata:
  name: bad
  labels:
    app: bad
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: bad
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: good-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: good
  template:
    metadata:
      labels:
        app: good
        test: quicktest
    spec:
      containers:
      - name: resp
        image: xanderstrike/resp
        imagePullPolicy: Always
        env:
        - name: RESPONSE_STATUS
          value: "204"
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bad
  template:
    metadata:
      labels:
        app: bad
        test: quicktest
    spec:
    spec:
      containers:
      - name: resp
        image: xanderstrike/resp
        imagePullPolicy: Always
        env:
        - name: RESPONSE_STATUS
          value: "500"
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: quicktest-route
spec:
  gateways:
  - cf-system/istio-ingressgateway
  hosts:
  - quicktest.example.com
  http:
  - name: "good"
    route:
    - destination:
        host: good.default.svc.cluster.local
      weight: 50
    - destination:
        host: bad.default.svc.cluster.local
      weight: 50
    retries:
      retryOn: 5xx
      attempts: 10
      perTryTimeout: 1s
```
</details>

Repeatedly make requests:

```
while true; do curl -s -o /dev/null -w "%{http_code}\n" quicktest.example.com; sleep 0.25; done
```

**Expected Behavior**

Only 204s are returned, because 500s are retried.

**Observed Behavior**

Exactly 50/50 split between 204s and 500s, retrying is failing to produce a success.

On further inspection, each time a 500 is returned, 10 requests can be observed on the `bad` pod, indicating that requests are retried but only to the same endpoint.

**Version**

```
18:10 $ istioctl version
client version: 1.4.5
control plane version: 1.4.5
data plane version: 1.4.5 (24 proxies)
```

**How was Istio installed?**

`istioctl manifest generate` and kapp

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE
