### ISSUE TITLE
Unknown field error while trying to generate custom-manifest using istioctl 1.6.0

### ISSUE THREAD

**Issue by ahilmathew** [istio/istio#24522]
**Bug description**
In the overlay-mainfest that I am using, I've set the `SidecarInjectorConfig` to be enabled and `rewriteAppHTTPProbe` to true.
```
  values:
    cni:
      psp_cluster_role: eks:podsecuritypolicy:privileged
    sidecarInjectorWebhook:
      enabled: true
      rewriteAppHTTPProbe: true
```
However this is what I get with istioctl 1.6.0. This worked fine in istioctl 1.5.4.
```
Error: validation errors (use --force to override): 
unknown field "enabled" in v1alpha1.SidecarInjectorConfig
```
