### ISSUE TITLE
per_filter_config not allowing 'disabled: false' values

### ISSUE THREAD

**Issue by abdulsalama** [istio/istio#24548]
**Bug description**
I'm trying to configure ext_authz filter per virtual hosts. Currently I have ext_authz filter as follow:
```
kind: EnvoyFilter
metadata:
  name: authn-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.router"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.ext_authz
        config:
          http_service:
            server_uri:
              uri: http://authservice.istio-system.svc.cluster.local
              cluster: outbound|8080||authservice.istio-system.svc.cluster.local
              failure_mode_allow: false
              timeout: 10s
            authorization_request:
              allowed_headers:
                patterns:
                - exact: "cookie"
                - exact: "X-Auth-Token"
            authorization_response:
              allowed_upstream_headers:
                patterns:
                - exact: "kubeflow-userid"
          status_on_error:
            code: GatewayTimeout
```
I don't want to apply this filter to all virtual hosts so I'm excluding some virtual hosts as follow:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: bypass-auth-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: VIRTUAL_HOST
    match:
      routeConfiguration:
        vhost:
          name: a.example.com:80
    patch:
        operation: MERGE
        value:
          per_filter_config:
            envoy.ext_authz:
              disabled: true
```
 However, I would like if I can do it such that I apply the filter on specific virtual hosts rather than having to exclude every hosts that doesn't need auth (more like a whitelist solution rather than a blacklist)

So I tried doing this:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: all-bypass-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: VIRTUAL_HOST
    match:
      routeConfiguration:
        vhost:
          route:
            name: '/'
    patch:
        operation: MERGE
        value:
          per_filter_config:
            envoy.ext_authz:
              disabled: true
  - applyTo: VIRTUAL_HOST
    match:
      routeConfiguration:
        vhost:
          name: 'b.example.com:80'
    patch:
        operation: MERGE
        value:
          per_filter_config:
            envoy.ext_authz:
              disabled: false
```
Here I only want the authentication on b.example.com. So I tried disabling the filter on everything, then re-enable it only for that specific virtual hosts. But when applying this filter, I get the following error:

```
[Envoy (Epoch 0)] [2020-06-09 15:11:50.796][20][warning][config] [external/envoy/source/common/config/grpc_mux_subscription_impl.cc:82] gRPC config for type.googleapis.com/envoy.api.v2.RouteConfiguration rejected: Proto constraint validation failed (ExtAuthzPerRouteValidationError.Disabled: ["value must equal " %!q(bool=true)]): disabled: false
```
Why it is not allowed to set disabled to false?

[x] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
ext_authz filter is disabled on all virtual hosts but b.example.com

**Steps to reproduce the bug**
Apply the envoyfilters mentioned above using kubectl apply -f file.yaml

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio version 1.4

**How was Istio installed?**
By admin as part of EKS cluster setup

**Environment where bug was observed (cloud vendor, OS, etc)**
Cloud - EKS cluster

**Comment by howardjohn** [comment]
I think this is the same problem as https://github.com/istio/istio/issues/18169?

**Comment by howardjohn** [comment]
Closing as duplicate of https://github.com/istio/istio/issues/18169

**Comment by haf** [comment]
This is not a duplicate of #18169 because the value `true` is not a protobuf default value, see https://developers.google.com/protocol-buffers/docs/proto3#default

@abdulsalama you want something like:

```yaml

  # Skip requiring Bearer tokens when logging in:
  # https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-EnvoyConfigObjectPatch
  - applyTo: VIRTUAL_HOST
    # https://istio.io/docs/reference/config/networking/envoy-filter/#EnvoyFilter-EnvoyConfigObjectMatch
    match:
      # https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-PatchContext
      context: GATEWAY
      # https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-RouteConfigurationMatch
      routeConfiguration:
        gateway: istio-system/ingress
        # https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-RouteConfigurationMatch-VirtualHostMatch
        vhost:
          name: accounts.example.com:443
          # route: ...
    patch:
      # https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-Patch-Operation
      operation: MERGE
      # -------- Envoy record is merged with the value
      # https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#struct
      value:
        name: envoy.ext_authz_disabled
        # https://www.envoyproxy.io/docs/envoy/v1.16.1/api-v3/config/route/v3/route_components.proto.html?highlight=per_filter_config
        typed_per_filter_config:
          envoy.filters.http.ext_authz:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute
            disabled: true

```
