### ISSUE TITLE
Istio completely fails with custom namespaces

### ISSUE THREAD

**Issue by nadenf** [istio/istio#24541]
**Bug description**

If you try and force Istio to install everything in a custom namespace it fails to install.

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Steps to reproduce the bug**

Using the values.yaml  below with a standard istioctl install -f:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: system-ingress
spec:
  addonComponents:
    kiali:
      namespace: system-ingress
      enabled: true
    prometheus:
      namespace: system-ingress
      enabled: true
  components:
    egressGateways:
      - name: istio-egressgateway
        enabled: true
        namespace: system-ingress
        k8s:
          nodeSelector:
            type: egress
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        namespace: system-ingress
        k8s:
          nodeSelector:
            type: ingress
    pilot:
      k8s:
        nodeSelector:
          type: service
  values:
    global:
      configNamespace: system-ingress
      istioNamespace: system-ingress
      prometheusNamespace: system-ingress
    kiali:
      createDemoSecret: true
```

Results in the following messages with no Istio pods created:
```
✔ Istio core installed
✘ Istiod encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the condition
Deployment/system-ingress/istiod
- Processing resources for Addons, Egress gateways, Ingress gateways. Waiting for Deployment/system-ingress/istio-egressgateway, Deployment/system-ingress/istio-ingressgateway, Deployment/system-ingress/kiali, ...
```
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

Istio 1.6.1

Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
