### ISSUE TITLE
The VirtualService on Istio 1.6.x is not running properly when using wildcard domain names

### ISSUE THREAD

**Issue by farmerluo** [istio/istio#24576]
**Bug description**
Here is my ISTIO configuration file:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: dubbo-gateway
  namespace: public-ops-tomcat-qa
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*.ops.k8s1.internal.testqa.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: public-ops-dubbo-demo-web-tomcat-qa
  namespace: public-ops-tomcat-qa
spec:
  hosts:
  - "*.ops.k8s1.internal.testqa.com"
  - "public-ops-dubbo-demo-web-tomcat-qa"
  gateways:
  - dubbo-gateway
  http:
  - route:
    - destination:
        host: public-ops-dubbo-demo-web-tomcat-qa
        port:
          number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: public-ops-dubbo-demo-web-tomcat-qa
  namespace: public-ops-tomcat-qa
spec:
  host: public-ops-dubbo-demo-web-tomcat-qa
  subsets:
  - name: v1
    labels:
      version: v1
```
When I use curl to request it, it returns a status code of 404,NR:
```
# curl -I -m 10 -o /dev/null -s -w %{http_code}  http://dubbo-demo.ops.k8s1.internal.testqa.com/test
404
```
On Istio.1.5.x, it works fine.
```
# curl -I -m 10 -o /dev/null -s -w %{http_code}  http://dubbo-demo.ops.k8s1.internal.testqa.com/test
200
```

if set VirtualService configure in Istio 1.6.x as:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: public-ops-dubbo-demo-web-tomcat-qa
  namespace: public-ops-tomcat-qa
spec:
  hosts:
  - "dubbo-demo.ops.k8s1.internal.testqa.com"
  - "public-ops-dubbo-demo-web-tomcat-qa"
  gateways:
  - dubbo-gateway
  http:
  - route:
    - destination:
        host: public-ops-dubbo-demo-web-tomcat-qa
        port:
          number: 8080
```
it works fine too.

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
# istioctl version --remote
client version: 1.6.1
control plane version: 1.6.1
data plane version: 1.6.1 (5 proxies)
# kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:41:00Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:32:32Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
custom_profile.yaml:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-operator
spec:
  profile: default
  meshConfig:
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
    egressGateways:
    - name: istio-egressgateway
      enabled: true
      k8s:
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
  addonComponents:
    kiali:
      enabled: true
    grafana:
      enabled: true
    tracing:
      enabled: true
    prometheus:
      enabled: true
  values:
    global:
      proxy:
        autoInject: disabled
    gateways:
      istio-egressgateway:
        autoscaleEnabled: false
      istio-ingressgateway:
        autoscaleEnabled: false
        type: NodePort
    kiali:
      createDemoSecret: true
    prometheus:
     # hub: dockerhub.azk8s.cn/prom
    sidecarInjectorWebhook:
      enableNamespacesByDefault: false
      objectSelector:
        enabled: false
        autoInject: true
    pilot:
      traceSampling: 100
```
```
istioctl manifest apply -f custom_profile.yaml
```

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
I tried to reproduce with:

`~/istio/istio-1.6.1/bin/istioctl install`

Followed by

```yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: public-ops-tomcat-qa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      containers:
      - name: httpbin
        image: docker.io/kennethreitz/httpbin
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /get
            port: 80
            scheme: HTTP
          initialDelaySeconds: 4
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: public-ops-dubbo-demo-web-tomcat-qa
spec:
  selector:
    app: httpbin
  ports:
  - name: http
    port: 8080
    targetPort: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: dubbo-gateway
  namespace: public-ops-tomcat-qa
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*.<MYIP>.nip.io"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: public-ops-dubbo-demo-web-tomcat-qa
  namespace: public-ops-tomcat-qa
spec:
  hosts:
  - "*.<MYIP>..nip.io"
  - "public-ops-dubbo-demo-web-tomcat-qa"
  gateways:
  - dubbo-gateway
  http:
  - route:
    - destination:
        host: public-ops-dubbo-demo-web-tomcat-qa
        port:
          number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: public-ops-dubbo-demo-web-tomcat-qa
  namespace: public-ops-tomcat-qa
spec:
  host: public-ops-dubbo-demo-web-tomcat-qa
  subsets:
  - name: v1
    labels:
      version: v1
```

and was unable to reproduce the issue. `curl foo.<MYIP>.nip.io/get` succeeds.
Maybe you can try that config as well to see if there is some difference between our setup or maybe it is environmental. I would also recommend adding a config dump of the gateway, see https://github.com/istio/istio/wiki/Troubleshooting-Istio for info on doing this.

Is the 404 NR from the gateway or the backend? does the backend have a sidecar?
