### ISSUE TITLE
multicluster shared controlplane with ILB fails cannot create an external load balancer with mix protocols

### ISSUE THREAD

**Issue by samos123** [istio/istio#24596]
**Bug description**
Multicluster shared control palne with ILB fails due to unable to create LB with mixed protocols. See below:
```
istioctl install -f istio-main-cluster.yaml
✔ Istio core installed
  Processing resources for Istiod.
2020-06-11T03:00:43.315880Z     error   installer       failed to create "Service/istio-system/istiod": Service "istiod" is invalid: spec.ports: Invalid value: []core.ServicePort{core.ServicePort{Name:"grpc-xds", Protocol:"TCP", Port:15010, TargetPort:intstr.IntOrString{Type:0, IntVal:15010, StrVal:""}, NodePort:0}, core.ServicePort{Name:"https-dns", Protocol:"TCP", Port:15012, TargetPort:intstr.IntOrString{Type:0, IntVal:15012, StrVal:""}, NodePort:0}, core.ServicePort{Name:"https-webhook", Protocol:"TCP", Port:443, TargetPort:intstr.IntOrString{Type:0, IntVal:15017, StrVal:""}, NodePort:0}, core.ServicePort{Name:"http-monitoring", Protocol:"TCP", Port:15014, TargetPort:intstr.IntOrString{Type:0, IntVal:15014, StrVal:""}, NodePort:0}, core.ServicePort{Name:"dns", Protocol:"UDP", Port:53, TargetPort:intstr.IntOrString{Type:0, IntVal:15053, StrVal:""}, NodePort:0}, core.ServicePort{Name:"dns-tls", Protocol:"TCP", Port:853, TargetPort:intstr.IntOrString{Type:0, IntVal:15053, StrVal:""}, NodePort:0}}: cannot create an external load balancer with mix protocols
✘ Istiod encountered an error: failed to create "Service/istio-system/istiod": Service "istiod" is invalid: spec.ports: Invalid value: []core.ServicePort{core.ServicePort{Name:"grpc-xds", Protocol:"TCP", Port:15010, TargetPort:intstr.IntOrString{Type:0, IntVal:15010, StrVal:""}, NodePort:0}, core.ServicePort{Name:"https-dns", Protocol:"TCP", Port:15012, TargetPort:intstr.IntOrString{Type:0, IntVal:15012, StrVal:""}, NodePort:0}, core.ServicePort{Name:"https-webhook", Protocol:"TCP", Port:443, TargetPort:intstr.IntOrString{Type:0, IntVal:15017, StrVal:""}, NodePort:0}, core.ServicePort{Name:"http-monitoring", Protocol:"TCP", Port:15014, TargetPort:intstr.IntOrString{Type:0, IntVal:15014, StrVal:""}, NodePort:0}, core.ServicePort{Name:"dns", Protocol:"UDP", Port:53, TargetPort:intstr.IntOrString{Type:0, IntVal:15053, StrVal:""}, NodePort:0}, core.ServicePort{Name:"dns-tls", Protocol:"TCP", Port:853, TargetPort:intstr.IntOrString{Type:0, IntVal:15053, StrVal:""}, NodePort:0}}: cannot create an external load balancer with mix protocols
- Processing resources for Addons, Ingress gateways. Waiting for Deployment/istio-system/istio-ingressgateway, Deployment/is
```

[ ] Configuration Infrastructure
[x] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Ability to install istio with pilot being exposed over ILB

**Steps to reproduce the bug**
Folow docs described here: https://istio.io/latest/docs/setup/install/multicluster/shared/
1. Deploy GKE cluster
2. Install istio with following manifest `istioctl install -f `:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      multiCluster:
        clusterName: main-1
      network: network1


  # Change the Istio service  and add the cloud provider specific annotations. See
  # https://kubernetes.io/docs/concepts/services-networking/service/\#internal-load-balancer for more
  # information. The example below shows the configuration for GCP/GKE.
  components:
    pilot:
      k8s:
        service:
          type: LoadBalancer
        service_annotations:
          cloud.google.com/load-balancer-type: Internal
          networking.gke.io/internal-load-balancer-allow-global-access: "true"
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
istioctl version
client version: 1.6.1
control plane version: 1.6.1
data plane version: 1.6.1 (2 proxies)
```

**How was Istio installed?**
istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE
