### ISSUE TITLE
http alpn override applied to external services breaks connections

### ISSUE THREAD

**Issue by pbohman** [istio/istio#24619]
### Describe the bug 
Connections to external HTTP services configured with SIMPLE_TLS destination rules are aborted by the external server or envoy due to non-negotiated alpn errors.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### Expected behavior
Envoy and the external service should connect using http 1.1. or h2. Istio/envoy should not send an ALPN list consisting entirely of unsupported protocols (ie, ["istio-http1.1", "istio"]). Unsupported protocols are not ignored by servers.

>In the event that the server supports no protocols that the client advertises, then the server SHALL respond with a fatal "no_application_protocol" alert.
https://tools.ietf.org/html/rfc7301#section-3.1

### Steps to Reproduce
Apply:
```
apiVersion: apps/v1                  
kind: Deployment
metadata:                               
  name: sleep     
spec:    
  selector:      
    matchLabels:
      app: sleep
  template:  
    metadata:
      annotations:
      labels:            
        app: sleep
    spec:
      containers:                       
      - name: sleep  
        image: pstauffer/curl
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: IfNotPresent
--- 
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: http2.pro
spec:
  hosts:
  - http2.pro
  ports:
  - name: http
    number: 443
    protocol: HTTP
  location: MESH_EXTERNAL
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: http2.pro
spec:
  host: http2.pro
  trafficPolicy:
    tls:
      mode: SIMPLE
```
Attempt to access external service and observe failure:
```
$ kubectl exec -t sleep-69bd787db7-tmvqn -n istio-monitoring -c sleep -- curl -v -s --http2  http://http2.pro:443/api/v1
*   Trying 8.9.5.7...
* TCP_NODELAY set
* Connected to http2.pro (8.9.5.7) port 443 (#0)
> GET /api/v1 HTTP/1.1
> Host: http2.pro:443
> User-Agent: curl/7.60.0
> Accept: */*
> Connection: Upgrade, HTTP2-Settings
> Upgrade: h2c
> HTTP2-Settings: AAMAAABkAARAAAAAAAIAAAAA
>
upstream connect error or disconnect/reset before headers. reset reason: connection failure< HTTP/1.1 503 Service Unavailable
< content-length: 91
< content-type: text/plain
< date: Fri, 12 Jun 2020 01:50:04 GMT
< server: envoy
<
```
Envoy log:
```
[2020-06-12T01:50:04.423Z] "GET /api/v1 HTTP/1.1" 503 "upstream_reset_before_response_started{connection failure,TLS error: 268435715:SSL routines:OPENSSL_internal:INVALID_ALPN_PROTOCOL 268435605:SSL rout
ines:OPENSSL_internal:ERROR_PARSING_EXTENSION 268435646:SSL routines:OPENSSL_internal:PARSE_TLSEXT}" UF,URX "-" "TLS error: 268435715:SSL routines:OPENSSL_internal:INVALID_ALPN_PROTOCOL 268435605:SSL rout
ines:OPENSSL_internal:ERROR_PARSING_EXTENSION 268435646:SSL routines:OPENSSL_internal:PARSE_TLSEXT" 0 91 503 - "-" "curl/7.60.0" "dc47bd2e-7827-46df-a123-c52f5733e96c" "http2.pro:443" "8.9.5.7:443" outbou
nd|443||http2.pro - 8.9.5.7:443 172.23.5.168:51367 - default 
```
### Analysis
We first noticed connections to external services defined in ServiceEntries with envoy TLS origination no longer worked when we upgraded from 1.4.X to 1.5.4.

It appears that the outbound HTTP connection manager always overrides the alpn with istio-h2 or istio-http1.1. Could it add the non-istio variants as well?
https://github.com/istio/istio/blob/1.5.4/pilot/pkg/networking/core/v1alpha3/listener.go#L1802

Response from 1.4.4:
```
$ kubectl exec -t sleep-69bd787db7-hb66q -n istio-monitoring -c sleep -- curl  -s --http2  http://http2.pro:443/api/v1
{"http2":0,"protocol":"HTTP\/1.1","push":0,"user_agent":"curl\/7.60.0"}
```

**Comment by gargnupur** [comment]
@pbohman , @robertpanzer : Looks like ALPN filter was enabled in 1.4 too. Did anything change in your setup from 1.4 to 1.5 to cause this?

**Comment by pbohman** [comment]
Hey @gargnupur , thanks for taking a look. Where do you see the ALPN filter in 1.4? I don't see it in this function: https://github.com/istio/istio/blob/1.4.7/pilot/pkg/networking/core/v1alpha3/listener.go#L1658

I also don't see it when I dump the envoy config from a 1.4 proxy, but maybe I'm missing something.

**Comment by gargnupur** [comment]
+ @diemtvu from security team. This is with respect to Alpn Filter.
@pbohman : I got it from the code in 1.5.4 => if util.IsIstioVersionGE14(pluginParams.Node).. so thought it would be there in 1.4 too.. 
Probably, it was not enabled by default in 1.4. 

@pbohman : Can you share the config dump from 1.5.4 where you are seeing this error?

**Comment by pbohman** [comment]
@gargnupur, sure, here is the listener corresponding to the service in the repro steps:
https://gist.github.com/pbohman/121ce75fe643137bdfbdecbefc247598

**Comment by gargnupur** [comment]
Can you try setting these 2 variables on istiod and see if that helps:
PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_INBOUND=false and PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_OUTBOUND=false

**Comment by pbohman** [comment]
@gargnupur , I set both to false and saw the same connection behavior, error log, and istio.alpn filter in the envoy config.

**Comment by lambdai** [comment]
The entire story is, istio-proxy terminate plain text http request and recreate an https request.

Normally if http2.pro is a mesh internal host which will be terminated by another istio-proxy, the alpn should be overridden to istio or istio-http. This is done by alpn filter.

However, in http2.pro case, the endpoint in outbound cluster is not  an istio-proxy protected endpoint. But the outbound HCM doesn't have that knowledge.

The potential solutions includes
1. create a new filter chain containing HCM for this particular host http2.pro, or
2. Make alpn_filter smarter by prefeching the cluster, or apply the apln_filter per route or per virtualhost
3. Strip alpn_filter as @robertpanzer did, as if the 443 port is external and the entire 443 is mesh external for any ip. It might violate the security policy or connectivity between outbound istio-proxy and inbound istio-proxy on another k8s service. CC @incfly

**Comment by gargnupur** [comment]
Option 1 seems reasonable to me...

**Comment by incfly** [comment]
> strip alpn filter as if 443 port is external.

We can't make that assumption right? as you mentioned, customer can host 443 https within the mesh.

@gargnupur  Why not 2? I don't quite follow 1. Will we create one filter chain per such host?

I think relying on `ServiceEntry.MeshExternal` is better than port 443, although I somehow think we no longer rely on MESH_EXTERNAL before. This might introduce new dependencies on the field.

**Comment by tmshort** [comment]
> However, in http2.pro case, the endpoint in outbound cluster is not an istio-proxy protected endpoint. But the outbound HCM doesn't have that knowledge.

Yes, it does, the ServiceEntry explicitly states that http2.pro is MESH_EXTERNAL (and the DestinationRule tls mode is SIMPLE).

But if istio needs to distinguish between 3 cases:
* Inside the mesh (MESH_INTERNAL)
* Outside the mesh to non-istio (MESH_EXTERNAL?)
* Outside the mesh to istio (MESH_EXTERNAL?)

then three values for ServiceEntry.spec.location should be available to distinguish the last two.

Alternatively, why not include "http/1.1" in addition to "istio-http1.1" and "istio"? If the external proxy is an istio-mesh, it will select one of the "istio" options, otherwise, it will select "http/1.1"? This sounds like a reasonable and easy solution.

**Comment by sergeydeg** [comment]
I am facing this problem also on 1.5 and 1.6. But Actual problem in my case that WindowsServer 2016 incorrectly implements APLN RFC that states - 
> The server will  ignore any protocol name that it does not recognize.

Will be good if either add "http/1.1" to apln list or make possibility to disable istio.alpn filter with ServiceEntry or DestinationRule

**Comment by sergeydeg** [comment]
This patch worked for me in Istio 1.6 (I am using HTTP/S rewrite technique from Istio documentation)
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: alpn-envoytweak
  namespace: istio-system
spec:
  configPatches:
  - applyTo: HTTP_FILTER # Applies the patch to the HTTP filter chain in the http connection manager
    match:
      context: SIDECAR_OUTBOUND
      listener:
        name: "0.0.0.0_80"
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "istio.alpn"
    patch:
      operation: REMOVE  
  - applyTo: HTTP_FILTER # Applies the patch to the HTTP filter chain in the http connection manager
    match:
      context: SIDECAR_OUTBOUND
      listener:
        name: "0.0.0.0_80"
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.cors"
    patch:
      operation: INSERT_BEFORE
      value:
        name: "istio.alpn"
        typed_config:
          "@type": "type.googleapis.com/istio.envoy.config.filter.http.alpn.v2alpha1.FilterConfig"
          alpn_override:
          - alpn_override:
            - "istio-http/1.0"
            - "istio"
          - upstream_protocol: "HTTP11"
            alpn_override:
            - "istio-http/1.1"
            - "istio"
            - "http/1.1"
          - upstream_protocol: "HTTP2"
            alpn_override:
            - "istio-h2"
            - "istio"
```

**Comment by hobbytp** [comment]
@sergeydeg I try the similar envoyfilter for the original http2.pro (without rewrite from 80 to 443) example, it also works. Thanks,

**Comment by PiotrSikora** [comment]
None of the `istio`, `istio-http/1.1` or `istio-h2` values should be sent outside of the service mesh, so this seems like a regression in 1.5. @incfly could you take a look?

**Comment by hobbytp** [comment]
@piotrkpc @incfly @lambdai I use the same configuration (SE +DR) to connect www.facebook.com and http2.pro, the TLS origination for www.facebook.com can work, but it fails to connect to http2.pro. 
So is there any tricky difference here?

1. **Successful one for www.facebook.com**
**This configuration also works for www.google.com, www.cloudflare.com, banzaicloud.com**
```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: facebook-com
spec:
  hosts:
  - www.facebook.com
  location: MESH_EXTERNAL
  ports:
  - name: http-port-for-tls-origination
    number: 443
    protocol: HTTP
  resolution: NONE
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: facebook-com
spec:
  host: www.facebook.com
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE
```
The test command is: 
`
 kubectl exec -it sleep-8f795f47d-7ccdp -n hobby -c sleep -- curl --http2-prior-knowledge  -vvvv -sL -o /dev/null -D -  http://www.facebook.com:443
`

2. **Failed one for http2.pro**
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: http2.pro
spec:
  hosts:
  - http2.pro
  ports:
  - name: http
    number: 443
    protocol: HTTP
  location: MESH_EXTERNAL
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: http2.pro
spec:
  host: http2.pro
  trafficPolicy:
    tls:
      mode: SIMPLE
```
The test command is: 
`
 kubectl exec -it sleep-8f795f47d-7ccdp -n hobby -c sleep -- curl --http2-prior-knowledge  -vvvv -sL -o /dev/null -D -  http://http2.pro:443
`
The accesslog is:
`
[2020-09-23T06:40:30.158Z] "GET / HTTP/2" 503 UF,URX "-" "TLS error: 268435715:SSL routines:OPENSSL_internal:INVALID_ALPN_PROTOCOL 268435605:SSL routines:OPENSSL_internal:ERROR_PARSING_EXTENSION 268435646:SSL routines:OPENSSL_internal:PARSE_TLSEXT" 0 91 652 - "-" "curl/7.64.0" "8fcf3ff4-a5f6-9d36-82d4-709a0c3e609b" "http2.pro:443" "8.9.5.7:443" outbound|443||http2.pro - 8.9.5.7:443 192.168.240.8:47088 - default
`
