### ISSUE TITLE
Unable run istio-telemetry, istiocoredns, prometheus, kiali as nonroot in cluster with PSP enable

### ISSUE THREAD

**Issue by feliperfmarques** [istio/istio#24614]
Hello, I have clusters with multi control plane and unprivileged PSP policy. But, my setup fails because istio-telemetry, istiocoredns, prometheus, kiali run as root. I looked at code base and can see that this template components don't have `securityPolicy`. I will trying to submit a PR later, but but if anyone can do it before... 
 
```
44s         Warning   Failed                         pod/istio-telemetry-5c7674b586-xxxmn           Error: container has runAsNonRoot and image will run as root
107s        Warning   Failed                         pod/istiocoredns-7ffc9b7fcf-9kxwx              Error: container has runAsNonRoot and image will run as root
107s        Warning   Failed                         pod/istiocoredns-7ffc9b7fcf-9kxwx              Error: container has runAsNonRoot and image will run as root
14s         Warning   Failed                         pod/kiali-6f457f5964-xb2nl                     Error: container has runAsNonRoot and image has non-numeric user (kiali), cannot verify user is non-root
119s        Warning   Failed                         pod/prometheus-69d8b457f9-7wwjc                Error: container has runAsNonRoot and image has non-numeric user (nobody), cannot verify user is non-root
119s        Warning   Failed                         pod/prometheus-69d8b457f9-7wwjc                Error: container has runAsNonRoot and image will run as root
```

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Setup should works without fails when PSP is enabled and using unprivileged policy.

**Steps to reproduce the bug**

Setup cluster with PSP enable and unprivileged policy.

istio-unprivileged.yaml
```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: istio-operator
  annotations:
    kubernetes.io/description: This policy grants the minimum amount of privilege necessary to run istio.
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default,runtime/default'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName: 'runtime/default'
    apparmor.security.beta.kubernetes.io/defaultProfileName: 'runtime/default'
spec:
  privileged: false
  # Required to prevent escalations to root.
  allowPrivilegeEscalation: false
  # This is redundant with non-root + disallow privilege escalation,
  # but we can provide it for defense in depth.
  requiredDropCapabilities:
    - ALL
  # Allow core volume types.
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'  
    - 'downwardAPI'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    # Require the container to run without root privileges.
    rule: 'MustRunAsNonRoot'
    ranges:
      # Forbid adding the root group.
      - min: 1337
        max: 1337
  seLinux:
    # This policy assumes the nodes are using AppArmor rather than SELinux.
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1337
        max: 1337
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1337
        max: 1337
``` 

**How was Istio installed?**

`istioctl manifest apply -f istio_overlay.yaml`

`istio_overlay.yaml` 
```
      addonComponents:
        prometheus:
          enabled: true
        grafana:
          enabled: true
        kiali:
          enabled: true
        istiocoredns:
          enabled: true

      components:
        egressGateways:
          - name: istio-egressgateway
            enabled: true
        ingressGateways:
          - name: istio-ingressgateway
            enabled: true
        cni:
          enabled: true
        telemetry:
          enabled: true

      values:
        global:
          # Provides dns resolution for global services
          podDNSSearchNamespaces:
            - global

          multiCluster:
            enabled: true

          controlPlaneSecurityEnabled: true

        gateways:
          istio-egressgateway:
            runAsRoot: false
            env:
              # Needed to route traffic via egress gateway if desired.
              ISTIO_META_REQUESTED_NETWORK_VIEW: "external"
          istio-ingressgateway:
            runAsRoot: false
```

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE v1.16.8-gke.15

**Comment by feliperfmarques** [comment]
I has submited a PR adding necesary securityContext for istiocoredns:

```
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        privileged: false
        runAsGroup: 1337
        fsGroup: 1337
        runAsNonRoot: true
        runAsUser: 1337
```

**Comment by ytpessoa** [comment]
I also have submited two PRs #24621(kiali) and #24620(prometheus)  adding necessary  `securityContext`:

```
    spec:
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000        
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL       
        privileged: false
```

**Comment by feliperfmarques** [comment]
I percept run `istioctl manifest generate -f istio_overlay`  that it doesn't generating correct `securityContext` for istio-telemetry Deployment manifest, I got:

```
      securityContext:
        fsGroup: 1337
```
But, correct should to be (at least that's what I can see in the code base):

```
        securityContext:
          runAsUser: 1337
          runAsGroup: 1337
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
```

**Comment by tgunsch** [comment]
> I percept run `istioctl manifest generate -f istio_overlay` that it doesn't generating correct `securityContext` for istio-telemetry Deployment manifest, I got:
> 

I have deployd istio-telemetry with istioctl 1.6.7 and following overlay:
```
    telemetry:
      enabled: true
      k8s:
        overlays:
        - kind: Deployment
          name: istio-telemetry
          patches:
          - path: spec.template.spec.securityContext
            value:
              fsGroup: 1337
              runAsGroup: 1337
              runAsNonRoot: true 
              runAsUser: 1337 
              capabilities:
                drop:
                  - ALL
```
mixer starts successful, but istio-proxy container got a CrashLoopBackOff:
```
info    pickfirstBalancer: HandleSubConnStateChange: 0xc000859410, {CONNECTING <nil>}
error    sds    Failed to set up UDS path: listen unix ./etc/istio/proxy/SDS: bind: no such file or directory
info    sds    SDS gRPC server for workload UDS starts, listening on "./etc/istio/proxy/SDS"
info    Starting proxy agent
info    Subchannel picks a new address "istiod.istio-system.svc:15012" to connect
info    Channel Connectivity change to CONNECTING
info    sds    Start SDS grpc server
warn    sds    Failed to create directory for ./etc/istio/proxy/SDS: mkdir etc/istio/proxy: permission denied
error    sds    Failed to listen on unix socket "./etc/istio/proxy/SDS": listen unix ./etc/istio/proxy/SDS: bind: no such file or directory
error    sds    SDS grpc server for workload proxies failed to set up UDS: listen unix ./etc/istio/proxy/SDS: bind: no such file or directory
info    Opening status port 15020
info    Received new config, creating new Envoy epoch 0
info    Epoch 0 starting
error    Failed to generate bootstrap config: mkdir ./etc/istio/proxy: permission denied       
```
Any hints how to fix the proxy non-root issue ?
