### ISSUE TITLE
can the service in istio cluster access to the external device using netconf protocol? 

### ISSUE THREAD

**Issue by lcfang** [istio/istio#24628]
**Describe the feature request**
support netconf protocol
**Describe alternatives you've considered**
I have a k8s cluster with istio, some of my service in the cluster need to communicate with some external devices using netconf protocol, I build an app with a NodePort service in my cluster, I can visit the external device using passthroug mode, it means that "outboundTrafficPolicy" in istio configmap is "ALLOW_ANY",But it doesn't work when I change the mode to "REGISTRY_ONLY" and config a ServiceEntry, I can't understand the reason, can any one help me?
I didn't get any error log in istio-proxy except  below:
`[Envoy (Epoch 0)] [2020-06-12 06:46:30.241][15][trace][connection] [external/envoy/source/common/network/raw_buffer_socket.cc:38] [C1] read error: Resource temporarily unavailable`

**Additional context**
```
$cat svcEntry.yaml 
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: netconf-ext
spec:
  hosts:
  - lcfnetconf.com
  ports:
  - number: 830
    name: netconf
    protocol: TCP
  resolution: STATIC 
  location: MESH_EXTERNAL
  endpoints:
  - address: ${deviceIP}
```
```
$kubectl  get pod  -owide
NAME                                       READY   STATUS    RESTARTS   AGE    IP              NODE          NOMINATED NODE   READINESS GATES
netconf-test-56db4b8f9d-ct4gp              2/2     Running   0          8h     172.30.152.8    k8s-worker2   <none>           <none>
```
```
$kubectl  get svc
NAME                      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                          AGE
netconf-test              NodePort    10.254.149.6     <none>        8075:30075/TCP                   8h
```
```
$kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
$ istioctl version
```
client version: 1.4.3
control plane version: 1.4.3
data plane version: 1.4.3 (10 proxies)
```
