### ISSUE TITLE
`AuthorizationPolicy` unexpected behavior

### ISSUE THREAD

**Issue by nerusnayleinad** [istio/istio#24665]
I am trying to understand the functionality of `AuthorizationPolicy` object. This policy should allow requests from service account `foo` to service `demo`, and deny all other requests in the namespace istio right?

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: demo
  namespace: istio
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/istio/sa/foo"]
  - to:
    - operation:
        hosts: ["demo.istio"]
```

It does deny all requests to all other services in `istio` namespace, but it also allows requests to `demo` service from any service account. It is like `from` section doesn't get applied at all.

Do I have to do anything with the service account permissions?

This is a request from a service with the `default` service account.

```
$ kubectl exec -it curler -- curl -I demo.istio
Defaulting container name to curler.
Use 'kubectl describe pod/curler -n default' to see all of the containers in this pod.
HTTP/1.1 200 OK
server: envoy
date: Sun, 14 Jun 2020 14:00:07 GMT
content-type: text/html
content-length: 612
last-modified: Tue, 26 May 2020 15:00:20 GMT
etag: "5ecd2f04-264"
accept-ranges: bytes
x-envoy-upstream-service-time: 2
```

The same request to a different service fails, as expected

```
$ kubectl exec -it curler -- curl -I demo2.istio
Defaulting container name to curler.
Use 'kubectl describe pod/curler -n default' to see all of the containers in this pod.
HTTP/1.1 403 Forbidden
content-length: 19
content-type: text/plain
date: Sun, 14 Jun 2020 14:06:02 GMT
server: envoy
x-envoy-upstream-service-time: 15
```
Note: The `curler` service is within the mesh.

**Comment by incfly** [comment]
I can't tell reason by looking at the config. Seems legit. But I am very confident this basic feature should work by istio as well...

Have you turned on mTLS?
Do you have any other policies that might interfere with results?

/cc @yangminzhu

**Comment by nerusnayleinad** [comment]
there is not much really. mTLS was set to PERMISSIVE but automTLS was set to true. In the requests above it doesn't appear the request to be plain text. I set it now to STRICT, but still am able to reach the service. There are no other authorization policies.

Im using Istio 1.6.

```
$ kubectl get peerauthentication --all-namespaces
NAMESPACE      NAME                          AGE
istio-system   default                       4m20s
istio-system   grafana-ports-mtls-disabled   14d
$ kubectl get authorizationpolicy --all-namespaces
NAMESPACE   NAME   AGE
istio       demo   45h
$ kubectl get po curler -oyaml | grep -i serviceaccount:
  serviceAccount: default
$ kubectl exec -it curler -- curl -I demo.istio
Defaulting container name to curler.
Use 'kubectl describe pod/curler -n default' to see all of the containers in this pod.
HTTP/1.1 200 OK
server: envoy
date: Tue, 16 Jun 2020 10:21:54 GMT
content-type: text/html
content-length: 612
last-modified: Tue, 26 May 2020 15:00:20 GMT
etag: "5ecd2f04-264"
accept-ranges: bytes
x-envoy-upstream-service-time: 2
```

**Comment by nerusnayleinad** [comment]
I created another `AuthorizationPolicy` object explicitly denying the requests from the `default` service account; in the namespace istio, and now it works.

```
$ kubectl get authorizationpolicy -n istio
NAME              AGE
demo              45h
deny-deafult-sa   2m40s
$ kubectl exec -it curler -- curl -I demo.istio
Defaulting container name to curler.
Use 'kubectl describe pod/curler -n default' to see all of the containers in this pod.
HTTP/1.1 403 Forbidden
content-length: 19
content-type: text/plain
date: Tue, 16 Jun 2020 10:36:59 GMT
server: envoy
x-envoy-upstream-service-time: 0 
```
I though with the first one only was enough, as from the following doc:

If there are any DENY policies that match the request, deny the request.
If there are no ALLOW policies for the workload, allow the request.
If any of the ALLOW policies match the request, allow the request.
Deny the request.

Can you please explain the rules above?

**Comment by yangminzhu** [comment]
```
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/istio/sa/foo"]
  - to:
    - operation:
        hosts: ["demo.istio"]
```

This has **2** rules, the **1st** rule allows all requests from principal `cluster.local/ns/istio/sa/foo`, the **2nd** rule allows all requests to hosts `demo.istio`.

**Comment by incfly** [comment]
Aha, good catch! Missed the `-` before `to`.

**Comment by nerusnayleinad** [comment]
Oh! ok, that makes sense. It works now. Thank you!

Since we are here already, I'd like to confirm couple of things with this rule as an example:

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: demo
  namespace: istio
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/istio/sa/foo
    to:
    - operation:
        hosts:
        - demo.istio
```

1.- It will allow that condition and deny everything else in the namespace. Is this statement correct?

Say, if I have lots of service accounts across the cluster (and there is one; `foo` in istio namespace) and several services (demo, demo1, .., demo100) in namespace istio. Once I create the rule above, it will allow requests from any pod in the namespace istio with service account `foo` to the service `demo`, and it will deny any other request from any pod, in any namespace with any service account to the services `demo1` to `demo100`. Am I right? I mean I do not need to create the `DENY` rule explicitly right?

2.- I realize it allows ONLY request to `demo.istio`, but it denies requests to `demo` from the same namespace and `demo.istio.svc.slucter.local`. All requests done from the same pod (with service account `foo`). I do succeed if I pass `istio.demo` header to the request, so I guess it just checks the header. Am I right?
