### ISSUE TITLE
IngressGateway do not take the default mesh config

### ISSUE THREAD

**Issue by GregoireW** [istio/istio#24666]
I currently use istio 1.6.2. 

I use a production tracing system. I setup istio to send trace to this system. 

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: minimal
  components:
    ingressGateways:
      - name: istio-ingress
        enabled: true
        namespace: gateway
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        zipkin:
          address: my.monitoring:9411
      sds:
        enabled: true
  values:
    global:
      tracer:
        zipkin:
          address: my.monitoring:9411
```

I got traces yeeeeaaaahhhh. Except those traces have an error "parent trace not found".

Tracing is set correctly on the istio sidecar. There is an environment variable: 

`PROXY_CONFIG={"tracing":{"zipkin":{"address":"my.monitoring:9411"}},"sds":{"enabled":true},"proxyMetadata":{"DNS_AGENT":""}}` 

But such environment variable is not present in the ingress gateway. So the default setup apply and the effective config look like:

```
2020-06-14T13:48:05.147146Z	info	Effective config: binaryPath: /usr/local/bin/envoy
configPath: ./etc/istio/proxy
discoveryAddress: istiod.istio-system.svc:15012
drainDuration: 45s
envoyAccessLogService: {}
envoyMetricsService: {}
parentShutdownDuration: 60s
proxyAdminPort: 15000
serviceCluster: istio-external
statNameLength: 189
statusPort: 15020
tracing:
  zipkin:
    address: zipkin.istio-system:9411
```

Setting up an environment variable on the gateway solve the "no parent trace" error.

To fix, my first guess would be to modify the deployment template file [manifests/charts/gateways/istio-ingress/templates/deployment.yaml](https://github.com/istio/istio/blob/master/manifests/charts/gateways/istio-ingress/templates/deployment.yaml) to add an environment variable like

```
        - name: PROXY_CONFIG
          value: |
                 {{ toJson .Values.global.meshConfig.defaultConfig }}
```
but I'm not entirely sure if all args are needed and if there is no overriding somewhere.

I'm guessing this change may be interesting on egress gateway too.

Is anybody have any though about this?
