### ISSUE TITLE
istioctl manifest generate - IstioOperator revision cannot contain "."

### ISSUE THREAD

**Issue by nmnellis** [istio/istio#24677]
**Bug description**
Setting the revision to a string containing a period causes `istioctl manifest generate --filename operator.yaml` to fail with the following error `Error: path [Deployment:istiod-v1.6].spec.strategy has an unexpected first element [Deployment:istiod-v1 in OverlayK8sSettings`

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  creationTimestamp: null
spec:
  profile: default
  revision: "v1.6"
```

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
can use versions in revision for upgrades

**Steps to reproduce the bug**
`istioctl manifest generate --filename operator.yaml`

operator.yaml
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  creationTimestamp: null
spec:
  profile: default
  revision: "v1.6"
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.6.2
