### ISSUE TITLE
Unable to create k8s Ingress

### ISSUE THREAD

**Issue by vbottu** [istio/istio#24693]
We have the following version of Istio on out on prem cluster that has load balancer support
```
client version: 1.4.0
control plane version: 1.4.0
data plane version: 1.4.0 (50 proxies)

```
When I try to create ingress object using the below file it throws an error
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: openunison
  namespace: test-dev
spec:
  rules:
  - host: REDACTED
    http:
      paths:
      - backend:
          serviceName: springboot-sample
          servicePort: 8080
        path: /springboot 
```
I am seeing the below error
`Error from server (InternalError): error when creating ".\ingress.yml": Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post https://ingress-nginx-controller-admission.ingress-nginx.svc:443/extensions/v1beta1/ingresses?timeout=30s: service "ingress-nginx-controller-admission" not found`

I have added the below parameters to istio configmap and restarted pilot,galley and gateway pods
```
ingressClass: istio
ingressControllerMode: "DEFAULT"
```

Is there anything that I am missing.
