### ISSUE TITLE
PassthroughCluster downgrades http2 when on an existing http port

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#24706]
```
/ $ curl echo.echo:8080 --http2
ServiceVersion=
ServicePort=8080
Host=echo.echo:8080
URL=/
Cluster=
Method=GET
Proto=HTTP/1.1
RemoteAddr=10.244.0.60:33716
X-B3-Traceid=cd5372e24052f165ca52e16c43c9bd59
X-B3-Spanid=ca52e16c43c9bd59
Content-Length=0
Accept=*/*
X-Forwarded-Proto=http
X-Request-Id=bec88583-0111-4a07-9033-821fac66d8ba
X-Envoy-Attempt-Count=1
X-B3-Sampled=0
User-Agent=curl/7.69.1
Hostname=echo-bd57f9874-npztg
/ $ curl echo.echo:8081 --http2
ServiceVersion=
ServicePort=8081
Host=echo.echo:8081
URL=/
Cluster=
Method=GET
Proto=HTTP/1.1
RemoteAddr=10.244.0.60:48132
User-Agent=curl/7.69.1
Accept=*/*
Connection=Upgrade, HTTP2-Settings
Upgrade=h2c
Http2-Settings=AAMAAABkAAQCAAAAAAIAAAAA
Hostname=echo-bd57f9874-npztg
```

Port 8080 has an existing service, so it goes through routing and drops h2, while port 8081 is direct TCP so it works fine

**Comment by howardjohn** [comment]
Looks identical to https://github.com/istio/istio/issues/17102 which was closed without resolution but came to the same conclusion I did

**Comment by howardjohn** [comment]
I think we jsut need use_downstream_proto in the passthrough cluster. This will fix h2 prior knowledge, but not h2c upgrade due to https://github.com/envoyproxy/envoy/issues/1502

**Comment by howardjohn** [comment]
Made a quick test script:
```
echo "    Check uncaptured:"
curl echo.echo:8081 --http2 -s | egrep "(Http2|^Proto)"
echo "    Check captured prior:"
curl echo.echo:8080 --http2-prior-knowledge -s | egrep "(Http2|^Proto)"
echo "    Check captured upgrade:"
curl echo.echo:8080 --http2 -s | egrep "(Http2|^Proto)"
echo "    Check captured h1:"
curl echo.echo:8080 -s | egrep "(Http2|^Proto)"

echo "    Check sidecar-http2 captured prior:"
curl echo:9080 --http2-prior-knowledge -s | egrep "(Http2|^Proto)"
echo "    Check sidecar-http2 captured upgrade:"
curl echo:9080 --http2 -s | egrep "(Http2|^Proto)"
echo "    Check sidecar-http2 captured h1:"
curl echo:9080 -s | egrep "(Http2|^Proto)"

echo "    Check sidecar-http captured prior:"
curl echo:9081 --http2-prior-knowledge -s | egrep "(Http2|^Proto)"
echo "    Check sidecar-http captured upgrade:"
curl echo:9081 --http2 -s | egrep "(Http2|^Proto)"
echo "    Check sidecar-http captured h1:"
curl echo:9081 -s | egrep "(Http2|^Proto)"
```

**Comment by howardjohn** [comment]
with config:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  name: echo
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: echo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: echo
    spec:
      containers:
      - args:
        - --port=8081
        - --port=8080
        image: registry:5000/app:1592322138
        imagePullPolicy: Always
        name: echo
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: default
spec:
  clusterIP: 10.107.159.243
  ports:
  - name: http2
    port: 9080
    targetPort: 8080
  - name: http
    port: 9081
    targetPort: 8081
  - name: grpc
    port: 9087
    targetPort: 9090
  selector:
    app: echo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  name: echo
  namespace: echo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: echo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: echo
    spec:
      containers:
      - args:
        - --port=8081
        - --port=8080
        image: registry:5000/app:1592322138
        imagePullPolicy: Always
        name: echo
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: echo
spec:
  clusterIP: 10.96.188.198
  ports:
  - name: http
    port: 8080
  - name: http-alt
    port: 8081
  - name: grpc
    port: 9087
    targetPort: 9090
  selector:
    app: echo

---
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: sidecar
  namespace: default
spec:
  egress:
  - hosts:
    - ./*


```
