### ISSUE TITLE
Not able to access virtual service created in different namespace 

### ISSUE THREAD

**Issue by kpiyush17** [istio/istio#24716]
Hi,

I have two services, dsl-A, and dsl-B. Both have sidecar and I have defined virtual service and destination rule for dsl-B. dsl-A is accessing dsl-B using an environment variable.

Virtualservice:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dsl-B
spec:
  hosts:
  - dsl-B
  http:
  - route:
    - destination:
        host: dsl-B.ns1.svc.cluster.local
        port:
          number: 80
```  

DestinationRule:
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dsl-B
spec:
  host: dsl-B.ns1.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      mode: ISTIO_MUTUAL
```
Now, in dsl-A configMap, I have given dsl-B endpoint as `http://dsl-B` so that the traffic goes through virtual service. Also, when I did curl from dsl-A pod to `http://dsl-B`, it worked.

Now, I moved dsl-A to a different namespace (ns2), in that I am not able to access virtual service. I read in docs that VS is exposed to all namespace by default but still `http://dsl-B` is not getting resolved in the different namespace.

**Istio version: 1.6.1**
