### ISSUE TITLE
Update to use non-debug proxy sidecar and ingress

### ISSUE THREAD

**Issue by linsun** [istio/istio#2471]
The debug proxy side car container currently requires the following:

```
        securityContext:
          privileged: true
          readOnlyRootFilesystem: false
          runAsUser: 1337
```

We need to determine if this is absolutely required as this requires k8s admin to give developer role additional RBAC rules to be able to deploy privileged container for a given namespace.  In talking to @kyessenov, seems this is not needed.  Opening this issue to track this.

Related:  https://github.com/istio/istio/issues/1435
