### ISSUE TITLE
Deprecation warnings or (patch type warnings) for EnvoyFilter patches

### ISSUE THREAD

**Issue by esnible** [istio/istio#24743]
EnvoyFilters in 1.5 patch by adding a `config`, in Master they patch by adding a `typed_config`:

Perhaps `istioctl analyze` and the deprecation analyzer should say that using `config` instead of `typed_config` is deprecated?  This is somewhat complex to implement, because the valid type at any place depends on the `applyTo`, but because it is difficult for the user there is benefit to providing automated guidance when it is incorrect.

Currently a mistake makes the sidecars go STALE and the problem is undetected by `analyze`.

When I upgraded from 1.5 to master I saw errors in the sidecar logs like this:

```
2020-06-17T13:15:21.602759Z	warning	envoy config	[external/envoy/source/common/config/grpc_subscription_impl.cc:101] gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) virtualInbound: Failed to create WASM VM with unspecified runtime.
```

This happened when there was a specified runtime, but it was specified in config rather than typed_config.

The documentation around this is poor.  The docs only say the value is a "struct".  This makes sense, as the `applyTo` allows the value to be anywhere.  It would be better if the documentation had a table showing the Envoy type that is needed for the typical applyTo settings.
 https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-Patch

Example from 1.5:

```
    patch:
      operation: INSERT_BEFORE
      value:
        config:
          config:
            configuration: world
            name: myfilter
            rootId: add_header
            vmConfig:
              code:
                local:
                  filename: /var/local/lib/wasme-cache/ed2c7837b886619d94823dc82dd0f3692a8b720996b564ce64097395df7980c2
              runtime: envoy.wasm.runtime.null
              vmId: myfilter
        name: envoy.filters.http.wasm
```

EnvoyFilters in Master patch like this:

```
    patch:
      operation: INSERT_BEFORE
      value:
        name: istio.metadata_exchange
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          value:
            config:
              configuration: |
                {}
              vm_config:
                code:
                  local:
                    inline_string: envoy.wasm.metadata_exchange
                runtime: envoy.wasm.runtime.null
```

cc @mandarjog @therealmitchconnors

**Comment by esnible** [comment]
In addition to the problem with patches, in Istio 1.5 there is a message

```
Warn [IST0002] (EnvoyFilter envoy-filter.istio-system) Deprecated: EnvoyFilter.filters is deprecated
```

@linsun points out the message does not make it obvious that only using `filters` is deprecated, the other fields of EnvoyFilter are not a problem

**Comment by linsun** [comment]
I think the other key thing missing from the warning message is what should users do if they are using envoyfilter.filters now that it is deprecated or unsupported, which John indicated earlier to use https://istio.io/v1.5/docs/reference/config/networking/envoy-filter/#EnvoyFilter-EnvoyConfigObjectPatch instead.

**Comment by esnible** [comment]
@istio/wg-docs-maintainers Adding `kind/docs` because Lin's comment suggests each deprecated field needs a guidance message.  There are several kinds of deprecation:

- not-yet-implemented: the message is just to warn users away from an experimental field.
- renamed: there is a new field that is substantially similar
- "it's complicated": there is a new way to do it, but hand-written documentation is needed for this field
- oops: sunset with no replacement (I don't think we have any of these; maybe fields removed because of security)

We delete in phases

- Document as deprecated
- Hide from docs
- Remove protobuf from binary

For 2 and 3, we have no good place to put the suggestion of the replacement.  It is possible the CLI should point the user at a **back level** doc, such as

```
Sidecar field "banana" was removed in 1.4; see https://istio.io/v1.4/docs/reference/config/networking/sidecar/#banana"
```

**Comment by howardjohn** [comment]
Analyze is hard because the field doesn't even exist anymore. But `validate` does capture it since we get the raw yaml before being applied (and pruned!) by api-server. 

```
$ ik validate -f /tmp/ef.yaml
Error: 1 error occurred:
        * EnvoyFilter//payload-check: cannot parse proto message: YAML decoding error: filters:
- filterConfig:
    inlineCode: "function envoy_on_request(request_handle)\n  local body_size = request_handle:body():length()\n  if body_size > 1000 then  \n      request_handle:respond({[\":status\"] = \"413\"},\"Request Body Too Large\")\n  end\nend \n"
  filterName: envoy.lua
  filterType: HTTP
  listenerMatch:
    listenerProtocol: HTTP
    listenerType: SIDECAR_INBOUND
 unknown field "filters" in v1alpha3.EnvoyFilter
```

**Comment by linsun** [comment]
Would it be hard for users to figure out which cmds to use?  BTW, i just realized we still have `validate`... Could we consolidate them into 1 cmd that does both?

**Comment by esnible** [comment]
> Would it be hard for users to figure out which cmds to use? BTW, i just realized we still have `validate`... Could we consolidate them into 1 cmd that does both?

I would like to consolidate the commands.  We have tried (and failed!) before.

@therealmitchconnors Let me know if you have any ideas?
@jasonwzm Can we beef up the K8s openAPI schema validation around the deprecated fields?

`validate` checks the YAML parsing, and then uses the same pass/fail code as the webhook.
`analyze` loads the in-memory model, and then does global comparison against the whole thing, and also invokes the same pass/fail code as the webhook.

@howardjohn I believe K8s keeps the full JSON.  What do you think of having _/Users/snible/go/src/istio.io/istio/galley/pkg/config/source/kube/rt/dynamic.go_ try to parse everything twice, once with strict, to look for unknown fields, and squirrel them away for later reporting?

**Comment by howardjohn** [comment]
I think EnvoyFilter is a special case around the openapi schema not validating unknown fields because envoyfilter supports arbitrary inputs so we have it set to allow anything. This is a limitation of our usage of the schema, not Kubernetes itself. I could be wrong here. Based on `x-kubernetes-preserve-unknown-fields` field

@esnible k8s will actually prune the unknown fields, but we set `x-kubernetes-preserve-unknown-fields` for Envoyfilter. So yes technically we can get the full thing, but its probably a better to fix to make the `x-kubernetes-preserve-unknown-fields` apply only to the fields we need it?

I am likely not 100% accurate here - defer to @jasonwzm for the full truth

**Comment by jasonwzm** [comment]
>So yes technically we can get the full thing, but its probably a better to fix to make the `x-kubernetes-preserve-unknown-fields` apply only to the fields we need it?
We are only adding it to the field that needs it, not the entire CRD. https://github.com/istio/api/blob/master/kubernetes/customresourcedefinitions.gen.yaml#L2522

>Can we beef up the K8s openAPI schema validation around the deprecated fields?
Like John said, k8s will prune unknown fields, so filters will not show up in k8s if user config has the field.

**Comment by howardjohn** [comment]
@jasonwzm I agree its not on the entire CRD but somehow its not behaving how I expect.

Should this be rejected?
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: payload-check
spec:
  filters:
  - listenerMatch:
      listenerType: SIDECAR_INBOUND
      listenerProtocol: HTTP
    filterName: envoy.lua
    filterType: HTTP
    filterConfig:
      inlineCode: |
        function envoy_on_request(request_handle)
          local body_size = request_handle:body():length()
          if body_size > 1000 then  
              request_handle:respond({[":status"] = "413"},"Request Body Too Large")
          end
        end 
```

Given the spec doesn't have `filters`?

![2020-30-07_14-25-59](https://user-images.githubusercontent.com/623453/88976265-9a975300-d270-11ea-9a3e-7ebe29ede8cf.png)

**Comment by jasonwzm** [comment]
Yes, it is rejected by client validation.

**Comment by howardjohn** [comment]
Oh I don't know what happened but I tried again on latest fresh cluster and its rejected correctly. Must have had old CRD somehow. Thanks!

**Comment by mandarjog** [comment]
@jasonwzm Is it possible to issue "This field was removed, check <this doc>" while rejecting config? 
This would be one level above deprecation warning.

**Comment by jasonwzm** [comment]
@mandarjog I think we are talking about a field that no longer exists in the proto. So analyzer does not know about the field. If the field is not removed, but just marked as deprecated, we can warn in analyzer.

**Comment by mandarjog** [comment]
I thought the validation worked on open api spec, and we can add whatever we want there. Perhaps the pipeline joins it at the hip,  but  it does not have to.

**Comment by jasonwzm** [comment]
Yes the API server validation works on openapi spec but the output is defined by k8s.

**Comment by esnible** [comment]
> I thought the validation worked on open api spec, and we can add whatever we want there. Perhaps the pipeline joins it at the hip, but it does not have to.

@mandarjog We have open API schema validation, but it doesn't always help with EnvoyFilter which contains some "objects".
We have hand-written CRD validation.

The `admitPilot()` validation webhook receives the complete JSON.  We have a function `checkFields()` that looks for unknown K8s top-level keys.  I propose we add a "JSONPath blacklist" to each CRD.  This would let us check for unknown Spec fields.

**Comment by esnible** [comment]
@mandarjog @douglas-reid re-opening because we discussed having deprecation (or similar) warnings in 1.9 at yesterday's Telemetry/Extensions meeting.

**Comment by howardjohn** [comment]
@esnible what exactly do we want to warn on?

Since #28931 we now warn on deprecated filter names, deprecated types, and unknown fields

**Comment by esnible** [comment]
@howardjohn Fair enough, I didn't notice that one.

Closing as a duplicate of https://github.com/istio/istio/issues/28920

**Comment by maciejqantas** [comment]
> Yes, it is rejected by client validation.

How did you find that out? I'm facing a similar issue, yet I can't see any logs indicating rejection. I'm on Istio 1.6.13.

**Comment by howardjohn** [comment]
I agree, @jasonwzm it is not rejected in master code:

```
$ cat <<EOF | kubectl apply -f -
pipe heredoc> apiVersion: networking.istio.io/v1alpha3
pipe heredoc> kind: EnvoyFilter
pipe heredoc> metadata:
pipe heredoc>   name: payload-check
pipe heredoc> spec:
pipe heredoc>   filters:
pipe heredoc>   - listenerMatch:
pipe heredoc>       listenerType: SIDECAR_INBOUND
pipe heredoc>       listenerProtocol: HTTP
pipe heredoc>     filterName: envoy.lua
pipe heredoc>     filterType: HTTP
pipe heredoc>     filterConfig:
pipe heredoc>       inlineCode: |
pipe heredoc>         function envoy_on_request(request_handle)
pipe heredoc>           local body_size = request_handle:body():length()
pipe heredoc>           if body_size > 1000 then
pipe heredoc>               request_handle:respond({[":status"] = "413"},"Request Body Too Large")
pipe heredoc>           end
pipe heredoc>         end
pipe heredoc> EOF
envoyfilter.networking.istio.io/payload-check created
```

**Comment by jasonwzm** [comment]
@howardjohn Which fields need to be rejected specifically?

**Comment by esnible** [comment]
Not stale.

**Comment by tampler** [comment]
Any updates on this ? I'm trying to add support for `grpc-web` with Istio 1.10.0, but I can't apply an Envoy filter due to this issue.
Here's what I have:
```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: grpc-web-filter
spec:
  workloadLabels:
    app: server
  filters:
    - listenerMatch:
        listenerType: SIDECAR_INBOUND
        listenerProtocol: HTTP
      insertPosition:
        index: FIRST
      filterType: HTTP
      filterName: "envoy.grpc_web"
      filterConfig: {}
```
`istioctl validate envoy.yml` gives the following:
```bash
Error: 1 error occurred:
        * EnvoyFilter//grpc-web-filter: cannot parse proto message: unknown field "filters" in v1alpha3.EnvoyFilter
 ```


Any ideas?
