### ISSUE TITLE
Istioctl generates duplicated resources!

### ISSUE THREAD

**Issue by ysjjovo** [istio/istio#24767]
**Bug description**

[x] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Generate unique resources.
**Steps to reproduce the bug**
Run following comands
```
cat << EOF > ./istio-minimal-operator.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      proxy:
        autoInject: disabled
      useMCP: false
      # The third-party-jwt is not enabled on all k8s.
      # See: https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens
      jwtPolicy: first-party-jwt

  addonComponents:
    pilot:
      enabled: true
    prometheus:
      enabled: false

  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
      - name: cluster-local-gateway
        enabled: true
        label:
          istio: cluster-local-gateway
          app: cluster-local-gateway
        k8s:
          service:
            type: ClusterIP
            ports:
            - port: 15020
              name: status-port
            - port: 80
              name: http2
            - port: 443
              name: https
EOF
./istioctl manifest generate -f istio-minimal-operator.yaml --set hub=registry.cn-chengdu.aliyuncs.com/istio-releases>istio-minimal.yaml
```
You will find line 12 is the same with line 7589 in 'istio-minimal.yaml'

**Environment where bug was observed (cloud vendor, OS, etc)**
[root@bin0 0.15.0]# uname -a
Linux bin0 3.10.0-957.12.2.el7.x86_64 #1 SMP Tue May 14 21:24:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[root@bin0 0.15.0]# kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:09:21Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
[root@bin0 0.15.0]# kubectl get no
NAME       STATUS   ROLES    AGE   VERSION
10.3.0.5   Ready    <none>   22h   v1.15.1
[root@bin0 0.15.0]# ./istioctl version
client version: 1.6.1
cluster-local-gateway version:
pilot version: 1.6.1
data plane version: 1.6.1 (2 proxies)
