### ISSUE TITLE
Istio-Pilot / Istiod HPA shows 0% cpu utilization

### ISSUE THREAD

**Issue by Prashansa-K** [istio/istio#24809]
**Bug description**
On installing istio, an HPA is created named as 'istiod' and target deployment as 'istio-pilot' which shows 0% cpu utilization at all times. In 1.6.0, there is no specific deployment called istio-pilot. Even if I edit the HPA and put istiod as scaleTargetRef Deployment, then too it shows 0%.

[X] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[X] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
HPA should be configured based on proper deployment and show correct cpu utilization.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.6.0

**How was Istio installed?**
istioctl 

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS

**Comment by howardjohn** [comment]
Where does that HPA come from?
`~/istio/istio-1.6.0/bin/istioctl manifest generate` shows:
```yaml


# Cni component is disabled.

# EgressGateways istio-egressgateway component is disabled.

# Resources for IngressGateways component

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istio-ingressgateway

---

# IstiodRemote component is disabled.

# Resources for Pilot component

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: istiod
  namespace: istio-system
  labels:
    app: istiod
    release: istio
    istio.io/rev: default
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istiod
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80

```

No istio-pilot is found
