### ISSUE TITLE
HPA specs with quantities causes install errors.

### ISSUE THREAD

**Issue by liamawhite** [istio/istio#24839]
**Bug description**

Setting quantities in the IstioOperator CR causes unmarshalling errors.

```
2020-06-19T14:57:34.491412Z	error	k8s.io/client-go@v0.18.0/tools/cache/reflector.go:125: Failed to list *v1alpha1.IstioOperator: v1alpha1.IstioOperatorList.Items: []v1alpha1.IstioOperator: v1alpha1.IstioOperator.Status: Spec: unmarshalerDecoder: json: cannot unmarshal number into Go value of type map[string]json.RawMessage, error found in #10 byte of ...|d":true}}},"status":|..., bigger context ...|emo","values":{"pilot":{"autoscaleEnabled":true}}},"status":{"componentStatus":{"AddonComponents":{"|...
```

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

To be able to install when setting quantities in the HPA spec

**Steps to reproduce the bug**

Create the below CR. It appears this is only quantities because if I change `targetAverageValue: 1000` to `targetAverageUtilization: 1000` then this works. The difference here is the latter is of type `integer` not `Quantity`

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  values:
    pilot:
      autoscaleEnabled: true
  profile: demo
  components:
    pilot:
      k8s:
        hpaSpec:
          scaleTargetRef:
            apiVersion: extensions/v1beta1
            kind: Deployment
            name: istiod
          minReplicas: 1
          maxReplicas: 5
          metrics:
          - type: Resource
            resource:
              name: cpu
              targetAverageValue: 1000
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
client version: 1.6.3
control plane version: 1.6.1
data plane version: 1.6.1 (12 proxies)
```
