### ISSUE TITLE
AuthorizationPolicy causing DENY in tcp services without match with any rule

### ISSUE THREAD

**Issue by JohnWillker** [istio/istio#24845]
**Bug description**
I have created an `AuthorizationPolicy` to block any IP except my private CIDR to some HTTP services, but this affect other TCP service that has no correlation with this rule.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

I expect to block some HTTP services to all IPS except to my private range.
This rule is for the Telemetry services in `istio-system` namespace.
- Kiali
- Jaeger
- Grafana

**Steps to reproduce the bug**

The AuthorizationPolicy:
```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: whitelist
  namespace: istio-system
spec:
  action: DENY
  rules:
  - from:
    - source:
        notIpBlocks:
        - 1.2.3.4/24
    to:
    - operation:
        hosts:
        - kiali.some-domain.net
        - grafana.some-domain.net
        - tracing.some-domain.net
  selector:
    matchLabels:
      app: istio-ingressgateway
```

The Telemetry gateway

```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: global-telemetry
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
     - kiali.some-domain.net
     - grafana.some-domain.net
     - tracing.some-domain.net
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: certs
      maxProtocolVersion: TLSV1_3
      minProtocolVersion: TLSV1_2
      mode: SIMPLE

```

The Kiali VirtualService

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kiali-vs
  namespace: istio-system
spec:
  gateways:
  - istio-system/global-telemetry
  hosts:
  - kiali.some-domain.net
  http:
  - route:
    - destination:
        host: kiali
        port:
          number: 20001

```

I have a TCP server in another namespace with an Ingress enabled to the internet.

The `Service` of the `tcp-server`

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: production
  name: production
  namespace: infra-prod
spec:
  ports:
  - name: production
    port: 2727
    protocol: TCP
    targetPort: 2727
  selector:
    app: production
  sessionAffinity: None
  type: ClusterIP
```

The `tcp-server` `Virtual Service`

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: production
  namespace: infra-prod
spec:
  gateways:
  - production
  hosts:
  - tcp-server.some-domain.net
  tcp:
  - match:
    - port: 2727
    route:
    - destination:
        host: production
        port:
          number: 2727
```

The `tcp-server` `Gateway`

```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
  name: production
  namespace: payment-infra-prod
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - tcp-server.some-domain.net
    port:
      name: tcp
      number: 2727
      protocol: TCP

```

From any internet IP, a cannot reach the `Kiali` service(what is what I really want).
But I also can't reach my `tcp-server`, but it works from addresses on my network where I put it in the `notIpBlocks:` field in AuthorizationPolicy rule above.

I cannot understand how my `tcp-server` is affected by the AuthorizationPolicy rules above.

I have look at the ingress logs a see this:

```logs
[Envoy (Epoch 0)] [2020-06-21 01:46:41.795][23][debug][connection] [external/envoy/source/common/network/connection_impl.cc:707] [C38] connection in progress
[Envoy (Epoch 0)] [2020-06-21 01:46:41.795][23][debug][pool] [external/envoy/source/common/tcp/conn_pool.cc:109] queueing request due to no available connections
[Envoy (Epoch 0)] [2020-06-21 01:46:41.795][23][debug][conn_handler] [external/envoy/source/server/connection_handler_impl.cc:353] [C37] new connection
[Envoy (Epoch 0)] [2020-06-21 01:46:41.797][23][debug][connection] [external/envoy/source/common/network/connection_impl.cc:570] [C38] connected
[Envoy (Epoch 0)] [2020-06-21 01:46:41.797][23][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:191] [C38] handshake expecting read
[Envoy (Epoch 0)] [2020-06-21 01:46:41.798][23][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:176] [C38] handshake complete
[Envoy (Epoch 0)] [2020-06-21 01:46:41.798][23][debug][pool] [external/envoy/source/common/tcp/conn_pool.cc:285] [C38] assigning connection
[Envoy (Epoch 0)] [2020-06-21 01:46:41.798][23][debug][filter] [external/envoy/source/common/tcp_proxy/tcp_proxy.cc:578] TCP:onUpstreamEvent(), requestedServerName:
[Envoy (Epoch 0)] [2020-06-21 01:46:41.798][23][debug][rbac] [external/envoy/source/extensions/filters/network/rbac/rbac_filter.cc:37] checking connection: requestedServerName: , remoteAddress: x.x.x.x:4486, localAddress: 10.0.2.3:2727, ssl: none, dynamicMetadata:
[Envoy (Epoch 0)] [2020-06-21 01:46:41.798][23][debug][rbac] [external/envoy/source/extensions/filters/network/rbac/rbac_filter.cc:106] enforced denied
[Envoy (Epoch 0)] [2020-06-21 01:46:41.798][23][debug][connection] [external/envoy/source/common/network/connection_impl.cc:101] [C37] closing data_to_write=0 type=1
[Envoy (Epoch 0)] [2020-06-21 01:46:41.798][23][debug][connection] [external/envoy/source/common/network/connection_impl.cc:192] [C37] closing socket: 1
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

Istio version:

client version: 1.5.4
control plane version: 1.5.4
data plane version: 1.5.4 (3 proxies)

Kubectl version: 

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.36", GitCommit:"34a615f32e9a0c9e97cdb9f749adb392758349a6", GitTreeState:"clean", BuildDate:"2020-04-06T16:33:17Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"

Helm version(used only for template and kubectl to apply):
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

**How was Istio installed?**

```shell
 helm template install/kubernetes/helm/istio --name istio --namespace istio-system \
    --set global.mtls.enabled=true \
    --set global.mtls.auto=false \
    --set grafana.enabled=true \
    --set kiali.enabled=true \
    --set prometheus.enabled=true \
    --set gateways.istio-ingressgateway.loadBalancerIP=$INGRESS_IP \
    --set gateways.istio-ingressgateway.sds.enabled=true \
    --set pilot.env.PILOT_SIDECAR_USE_REMOTE_ADDRESS=true \
    --set pilot.env.PILOT_SKIP_VALIDATE_TRUST_DOMAIN=true \
    --set sidecarInjectorWebhook.rewriteAppHTTPProbe=true \
    --set global.disablePolicyChecks=false \
    --set tracing.enabled=true \
    --set global.proxy.logLevel=info \
    --set global.proxy.accessLogFile="/dev/stdout" \
    --set global.proxy.accessLogEncoding=JSON \
    --set global.proxy.resources.requests.cpu="100m" \
    --set global.proxy.resources.requests.memory="128Mi" \
    --set global.proxy.resources.limits.cpu="300m" \
    --set global.proxy.resources.limits.memory="256Mi" \
    --set global.proxy.protocolDetectionTimeout="500s"
    --set gateways.istio-ingressgateway.ports[0].port=80 \
    --set gateways.istio-ingressgateway.ports[0].name=http2 \
    --set gateways.istio-ingressgateway.ports[0].targetPort=80 \
    --set gateways.istio-ingressgateway.ports[1].port=443 \
    --set gateways.istio-ingressgateway.ports[1].name=https \
    --set gateways.istio-ingressgateway.ports[2].port=2727 \
    --set gateways.istio-ingressgateway.ports[2].name=ping-tcp \
    --set gateways.istio-ingressgateway.autoscaleMin=3 \
    --set gateways.istio-ingressgateway.autoscaleMax=10 \
    --set gateways.istio-ingressgateway.externalTrafficPolicy=Local | kubectl apply -f -
```

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE with the default installation in version: `v1.14.10-gke.36`

**Comment by yangminzhu** [comment]
Thanks for the detail report. I suspect the host part is ignored when generating the config on a TCP filter chain because TCP doesn't support any of these HTTP fields. 

Could you try if you change the Gateway port protocol to HTTP and see what happens? I will try to reproduce this and get back to you soon.

**Comment by JohnWillker** [comment]
> Thanks for the detail report. I suspect the host part is ignored when generating the config on a TCP filter chain because TCP doesn't support any of these HTTP fields.
> 
> Could you try if you change the Gateway port protocol to HTTP and see what happens? I will try to reproduce this and get back to you soon.

@yangminzhu 

You are right I made a different change adding `ports: ["443"]` in `operations`:
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: whitelist
  namespace: istio-system
spec:
  action: DENY
  rules:
  - from:
    - source:
        notIpBlocks:
        - 1.2.3.4/24
    to:
    - operation:
        hosts:
        - kiali.some-domain.net
        - grafana.some-domain.net
        - tracing.some-domain.net
       ports: ["443"]  <------------------- ADD THIS AND SOLVED THE PROBLEM
  selector:
    matchLabels:
      app: istio-ingressgateway
```

Now when a made a TCP connection using 2727 port the rule do not match and the connection is established.
