### ISSUE TITLE
Promote distroless to the default image type

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#24857]
We have had distroless images tested+released for 3+ releases. It would be nice to promote them to the default option, if not the only option (maybe), for security (both legitimate and theater and minimal image sizes. This tracks efforts and blockers for doing so

[ ] We need a way to debug images. This includes running curl, openssl, netstat, view iptables, and copy files (ie perf profiles) for within the network namespace of the proxy. One way to manage this is ephemeral containers, but its not necessarily the only way.

[ ] Users will need a way to opt out, at least for the initial release. We should start publishing `foo`, `foo-ubuntu`, and `foo-distroless` today. Currently `foo` will be an alias for `foo-ubuntu`, but in the future we will switch it to distroless

[ ] We need to update tests and documentation to use `pilot-agent request` where possible instead of `curl`. We mostly already do this, but probably some slipped through

[ ] Post release: we need to evaluate if we can remove the ubuntu images entirely

**Comment by howardjohn** [comment]
Forgot one: https://github.com/istio/istio/issues/17656

**Comment by howardjohn** [comment]
not stale

**Comment by howardjohn** [comment]
not stale

**Comment by mmerickel** [comment]
Considering a preStop hook with some bash is basically the only way to implement a real graceful shutdown for istio (especially for workloads that are not web services), I hope we can hold off on making this change, or at least leave a way to use the non-distroless sidecar until istio can handle things better. See for example the gist in https://github.com/istio/istio/issues/36640#issuecomment-1036545852 for a preStop hook using bash, `nc`, etc which I suspect will not work with distroless sidecars.

**Comment by howardjohn** [comment]
preStop hooks are one of the main reasons we aren't/haven't made it default

**Comment by howardjohn** [comment]
We need to decide if we make it default by setting global.variant=distroless, or by making the `<version>` tag now be distroless.

Currently we ave:
* `<version>`, `<version>-debug` - debug
* `<version>-distroless` - distroless

**Comment by qudongfang** [comment]
is it possible to have the option to override `variant` per deployment/pod?

use case:  preStop hook to ensure istio-proxy is the last to terminate(not all workloads require this exact termination order)

```
        - name: istio-proxy
          image: auto
          lifecycle:
            preStop:
              exec:
                # This prevents istio/envoy from shutting down by checking if any of the containers in the pod still have a port that is listening.
                # When a pod is marked as terminating it goes, preStop -> SIGTERM -> pilot-agent (drain/graceful terminiation) -> SIGTERM -> envoy
                command:
                  - "/bin/sh"
                  - "-c"
                  - "while [ $(netstat -plunt | grep tcp | grep -v envoy | grep -v pilot-agent | wc -l | xargs) -ne 0 ]; do sleep 1; done"
```
