### ISSUE TITLE
connections to DB getting timedout frequently in istio

### ISSUE THREAD

**Issue by dhineshbabuelango** [istio/istio#24856]
When I am doing performacne test, the pod connecting to DB, some connections are getting failed with the below error
java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
When i do the same test without istio sidecar it is workign fine, is there a timeout set in istio

**Comment by jronak** [comment]
Does it happen on idle connections only?
Most probably idle timeouts on the envoy sidecar might be causing it, default idletimeout is 1 hour.
[More details](https://istio.io/latest/docs/reference/config/networking/destination-rule/#ConnectionPoolSettings-HTTPSettings)

**Comment by dhineshbabuelango** [comment]
not idle connections, for performance test, each of my pod actually establishes 50 connections to the DB and I have more than 4 pods.

**Comment by jronak** [comment]
Could you share sidecar logs and details about your setup?

**Comment by dhineshbabuelango** [comment]
This is the error log    form app, actually there is no error logs in the side car, i have even enabled the access logging but still i dont see any error. the same application works fine if i dont use istio sidecar. The pods will make around 200 connections to DB, will that be a problem will istio timeout the connection after the count reaches certain limit
 "errorCode": "E0001",
      "errorDescription": "System error.",
      "errorRootCause": "Could not open JPA EntityManager for transaction; nested exception is org.hibernate.TransactionException: JDBC begin transaction failed: "
    },
    "throwable": {
      "cause": "CannotCreateTransactionException",
      "rootCause": "SQLException",
      "exceptionStackTrace"

**Comment by howardjohn** [comment]
Does this happen on every request? Can you provide a reproducible example? Can you provide a config dump https://github.com/istio/istio/wiki/Troubleshooting-Istio? Have you seen https://istio.io/latest/faq/security/#mysql-with-mtls?

**Comment by howardjohn** [comment]
@dhineshbabuelango any more info ^?

**Comment by yoep** [comment]
Hi 

I'm running against the exact same issue when using **MTLS** with **Postgres**.
I did follow the FAQ regarding MTLS on MYSQL and applied it to the Postgres deployment.
I hope I can provide additional information surrounding this issue with the information/configuration listed below.

**Client side**
```java
Caused by: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:339)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:153)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:103)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:678)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617)
	... 30 common frames omitted
Caused by: java.io.EOFException: null
	at org.postgresql.core.PGStream.receiveChar(PGStream.java:372)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2043)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
```

**Destination Rule**
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  labels:
    app: spring-dataflow-postgres
  name: spring-dataflow-postgres
spec:
  host: spring-dataflow-postgres.magda-dev.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```

**Policy**
```yaml
kind: Policy
apiVersion: authentication.istio.io/v1alpha1
metadata:
  name: spring-dataflow-postgres
[config-dump.txt](https://github.com/istio/istio/files/5238685/config-dump.txt)

spec:
  targets:
    - name: spring-dataflow-postgres
  peers:
    - mtls:
        mode: STRICT
```

**Config Dump**
[config-dump.txt](https://github.com/istio/istio/files/5238689/config-dump.txt)

**Comment by howardjohn** [comment]
https://preliminary.istio.io/latest/docs/ops/deployment/requirements#server-first-protocols may be useful

**Comment by tariq1890** [comment]
> https://preliminary.istio.io/latest/docs/ops/deployment/requirements#server-first-protocols may be useful

This assumes that MySQL databse hosting application is a part of k8s cluster and service mesh, correct?

@howardjohn Some of our users have reported the same exception stacktrace as reported by @yoep . Only difference is that our postgres database is external to the service mesh and we have permissive mTLS to allow external(to the mesh) network calls

**Comment by howardjohn** [comment]
I would suggest first taking a look at
https://istio.io/latest/docs/ops/deployment/requirements/#server-first-protocols
and ensuring you are following one of the options listed there

**Comment by tariq1890** [comment]
qq, Is `Postgres 5432` a server-first protocol?

**Comment by howardjohn** [comment]
I am not certain, but since mysql is I suspect postgres may be as well

**Comment by maateen** [comment]
A nice workaround, at least when you are using an external PostgreSQL service like AWS RDS, can be excluding the port from redirection to Envoy. You can do that by setting the following annotation at the pod:

```
annotations:
  traffic.sidecar.istio.io/excludeOutboundPorts: "5432"
```

Reference: https://istio.io/latest/docs/reference/config/annotations/

**Comment by howardjohn** [comment]
Seems like this issue has become a dumping ground of a bunch of vague issues without enough details to solve or using very old versions of Istio. I tried to reproduce with an in mesh and external, and everything works.

if you are actively seeing issues in Istio 1.8.3+, please open a new issue with more info on how to reproduce it and config dumps.

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: sql
spec:
  hosts:
  - "hh-pgsql-public.ebi.ac.uk"
  ports:
  - number: 5432
    name: sql
    protocol: TCP
  resolution: DNS
```

and `psql postgres://reader:NWDMCE5xdipIjRrp@hh-pgsql-public.ebi.ac.uk:5432/pfmegrnargs'` is a good way to reproduce as its a publicly accessible DB. Thanks everyone.
