### ISSUE TITLE
MUTUAL tls mode for service running inside of cluster

### ISSUE THREAD

**Issue by vbottu** [istio/istio#24884]
I have a service that runs on port 8443 with a self signed certificate(for testing, CA signed certs will be used later). I have created a gateway as follows

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: nginx-test-gateway
  namespace: test-dev
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
    hosts:
    - "login.example.com"
```
The VirtualService is 
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-test
  namespace: test-dev
spec:
  hosts:
  - login.example.com
  gateways:
  - nginx-test-gateway
  tls:
  - match:
    - port: 443
      sniHosts:
      - login.example.com
    route:
    - destination:
        host: my-nginx
        port:
          number: 443

```
The above combination works when tlsmode is PASSTHROUGH. Is there a way that I can implement mutual tls mode to the service running on port 443. 

Istio Version: 1.4.0
K8s version: 1.15.5
