### ISSUE TITLE
Add request.path to instance failed

### ISSUE THREAD

**Issue by lurenjia528** [istio/istio#24888]
istio can not get request.path request.host..

``` yaml
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
  name: myrequestcount
  namespace: platform
  labels:
    app: istio-telemetry
    release: istio
spec:
  compiledTemplate: metric
  params:
    value: "1"
    dimensions:
      request_protocol: api.protocol | context.protocol | "unknown"
      request_url_path: request.url_path | "unknown"
      request_host: request.host | "unknown"
      request_path: request.path | "unknown"
      response_code: response.code | 666666
---
apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
  name: myprometheus
  namespace: platform
  labels:
    app: istio-telemetry
    release: istio
spec:
  compiledAdapter: prometheus
  params:
    metricsExpirationPolicy:
      metricsExpiryDuration: "10m"
    metrics:
    - name: my_requests_total
      instance_name: myrequestcount.instance.platform
      kind: COUNTER
      label_names:
      - request_protocol
      - request_url_path
      - request_path
      - request_host
      - response_code
---

apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: mypromhttp
  namespace: platform
  labels:
    app: istio-telemetry
    release: istio
spec:
  actions:
  - handler: myprometheus
    instances:
    - myrequestcount

```

![image](https://user-images.githubusercontent.com/37833630/85375247-976dc080-b568-11ea-905f-f42a88e3e6cf.png)

``` bash
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"archive", BuildDate:"2019-05-29T08:20:47Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"archive", BuildDate:"2019-05-29T08:20:47Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/arm64"}

```

istio 1.4.2

ubuntu arm64
