### ISSUE TITLE
Implement gateway authorization break the ingress gateway

### ISSUE THREAD

**Issue by jerry153fish** [istio/istio#24894]
**Bug description**
Try to implement gateway authorization from [this tutorial](https://istio.io/latest/docs/tasks/security/authorization/authz-ingress/).

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ingress-policy
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  action: ALLOW
  rules:
  - from:
    - source:
       ipBlocks: ["xx.xx.xx.xx"]
```

Not working due to connection timeout, then I delete the policy by `kubectl delete`. The whole cluste is not woking all the connections timeouts.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Deletion of the policy should not break the ingress gateway

**Steps to reproduce the bug**
1. patch the ingress gateway  ` kubectl patch svc istio-ingressgateway -n istio-system -p '{"spec":{"externalTrafficPolicy":"Local"}}'`
2. apply the policy 
3. delete the policy
4. cluster not working

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

> istioctl version --remote
```
client version: 1.6.3
control plane version: 1.6.3
data plane version: 1.6.3 (3 proxies)
```

> kubectl version
```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

`istioctl install -f overwrites.yaml`

> overwrites.yaml

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
```

**Environment where bug was observed (cloud vendor, OS, etc)**
on latest eks cluster

**Comment by jerry153fish** [comment]
It turns out the `"externalTrafficPolicy": "Local"` not working on EKS, need to apply patch to kube-proxy

```
---
spec:
  template:
    spec:
      containers:
        - name: kube-proxy
          command:
            - kube-proxy
            - --hostname-override=$(NODE_NAME)
            - --v=2
            - --config=/var/lib/kube-proxy-config/config
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
```
