### ISSUE TITLE
struct "IstioComponentSetSpec" miss field citadel

### ISSUE THREAD

**Issue by thefuckingcode** [istio/istio#24900]
**Bug description**
I want to  use istio-operator(tag 1.6.3) to install istio.I also need to add some code to implement my own function.So i meet the problem.
* First,I dont know what version of istio/api i should import.So i imported the default version,maybe it's the latest
![image](https://user-images.githubusercontent.com/23526448/85411633-2abfe980-b59b-11ea-9828-e6a9dce7df42.png)
* Second,here is the bug
![image](https://user-images.githubusercontent.com/23526448/85412501-36f87680-b59c-11ea-9b6e-414ea473a288.png)

**Expected behavior**
When I create an IstioOperator, the independent operator can install istio successfully.

**Steps to reproduce the bug**
1. clone code
2. execut: git checkout 1.6.3
3. copy the operator directory as a new project
4. execute : go mod init github.com/myproject/istio-operator
5. use ide to replace all istio.io/istio with github.com/myproject/istio-operator
6. execut: go mod tidy && go mod vendor
7. start project
8. execute:
```
kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: demo
EOF
istiooperator.install.istio.io/example-istiocontrolplane created
```
9. check out the output log. The result as fllows:
![image](https://user-images.githubusercontent.com/23526448/85413452-6c519400-b59d-11ea-9688-d044c4ed548c.png)

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

tag 1.6.3

**Environment where bug was observed (cloud vendor, OS, etc)**
MacOs
