### ISSUE TITLE
DestinationRule subset label selection for EDS inconsistent

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#24926]
Start with config:

```yaml
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google
spec:
  hosts:
  - google.com
  ports:
  - number: 80
    name: http-port
    protocol: HTTP
  resolution: STATIC
  endpoints:
  - address: 1.2.3.4
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: google
spec:
  host: googlle.com
  subsets:
  - name: foo
EOF
```

Endpoints:
```
1.2.3.4:80                       HEALTHY     OK                outbound|80||google.com
```

Add literally any labels to the endpoint:
```yaml
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google
spec:
  hosts:
  - google.com
  ports:
  - number: 80
    name: http-port
    protocol: HTTP
  resolution: STATIC
  endpoints:
  - address: 1.2.3.4
    labels:
      foo: bar
      other: label
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: google
spec:
  host: google.com
  subsets:
  - name: foo
EOF
```

Endpoints:
```
1.2.3.4:80                       HEALTHY     OK                outbound|80|foo|google.com
1.2.3.4:80                       HEALTHY     OK                outbound|80||google.com
```
