### ISSUE TITLE
Not able to route grpc services

### ISSUE THREAD

**Issue by kpiyush17** [istio/istio#24932]
Hi,

I have two GRPC services running in same namespace which needs to be exposed through ingressgateway and will be routed based on endpoints.

Istio Configs:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: rpc
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: grpc
      protocol: GRPC
    hosts:
    - "rpc.example.com"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "rpc.example.com"
    tls:
      mode: SIMPLE
      credentialName: rpc-certs

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rpc
spec:
  hosts:
  - "rpc.example.com"
  - "rpc-B.ns1.svc.cluster.local"
  - "rpc-A.ns1.svc.cluster.local"
  gateways:
  - rpc
  http:
  - match:
    - uri:
        prefix: /profile
    route:
    - destination:
        host: rpc-B.ns1.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: rpc-A.ns1.svc.cluster.local
        port:
          number: 80

---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: rpc-B
spec:
  selector:
    matchLabels:
      app: rpc-B
  mtls:
    mode: STRICT

---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: rpc-A
spec:
  selector:
    matchLabels:
      app: rpc-A
  mtls:
    mode: STRICT

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: rpc-B
spec:
  host: rpc-B.ns1.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      mode: ISTIO_MUTUAL

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: rpc-A
spec:
  host: rpc-A.ns1.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      mode: ISTIO_MUTUAL
```

Service YAML for rpc-A:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: rpc-A
    meta.helm.sh/release-namespace: ns1
  labels:
    app.kubernetes.io/instance: rpc-A
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: app-deploy
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: app-deploy-0.1.0
    service: rpc-A
  name: rpc-A
  namespace: ns1
spec:
  clusterIP: <ip>
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: http
  selector:
    app: rpc-A
    app.kubernetes.io/instance: rpc-A
    app.kubernetes.io/name: app-deploy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

I am not sure what is wrong with the configuration as I am getting the error:
`upstream connect error or disconnect/reset before headers. reset reason: connection termination`
