### ISSUE TITLE
Applying policies on istio-system pods while working with knative

### ISSUE THREAD

**Issue by Shashankft9** [istio/istio#24949]
**Bug description**
I am working on applying authorization policies while working with knative, and for one of the red flag I am required to put a policy on a pod `cluster-local-gateway` running on ns `istio-system` to only accept traffic from some particular namespaces or service accounts [for my case - only the `default` ns]. I have applied this policy for the same purpose:
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ingress-policy
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: cluster-local-gateway
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: ["default" ]
```
But after applying this, traffic is blocked from everywhere on the `cluster-gateway-pod`, I can't even send traffic from `default` ns.
I understand that for this, I need to enable the mTLS, which I did on the `istio-system` ns. 
I notice that ns `istio-system` is labeled as `istio-injection=disabled`. So I guess while being a bug, it is more of a question too - Is this even possible, applying such policy? 

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
I should be able to block the traffic and allow it from only particular namespaces and serviceaccounts. 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.6.2
**How was Istio installed?**
Using IstioOperator and istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
Kubernetes, CentOS

**Comment by williamaronli** [comment]
@incfly  A customer question : 
while istio-system is labeled as istio-injection=disabled, Is this even possible, applying such policy?

**Comment by howardjohn** [comment]
> I understand that for this, I need to enable the mTLS, which I did on the istio-system ns.

How did you do this? You will need to ensure that pods in `default` are sending traffic using mTLS to  cluster-local-gateway. Which may not be happening

**Comment by Shashankft9** [comment]
@howardjohn there is one problem with a knative deployment running as a mesh pod in the `default` ns, I'll reach out to knative folks for this. Other than that, I wanted to know can I enable mTLS on the `istio-system` ns with it having this label `istio-injection=disabled`? Or do I need to change the label?

**Comment by Shashankft9** [comment]
I mean simply put, in order to block certain namespaces to reach `cluster-local-gateway` I need to ensure that mTLS is enabled on said namespaces and this policy should work?
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ingress-policy
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: cluster-local-gateway
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: ["default" ]
```

or do i need to enable mTLS on `istio-system` ns as well?
