### ISSUE TITLE
DestinationRule with subsets but without an endpoint label selector selects nothing

### ISSUE THREAD

**Issue by robertpanzer** [istio/istio#24969]
**Bug description**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

When I create a DestinationRule with multiple subsets with a null Subset.labels, no endpoint from a ServiceEntry is selected if they don't have any labels either.
I expect that all endpoints are included by a Subset without a labelSelector.

**Steps to reproduce the bug**

Create a ServiceEntry like this:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: testserver-dev
spec:
  endpoints:
  - address: 192.168.0.248
    ports:
      http: 8086
  exportTo:
  - .
  hosts:
  - testserver-dev.wmt
  ports:
  - name: http
    number: 80
    protocol: HTTP
  resolution: STATIC
```

Then create a DestinationRule that applies multiple different traffic configurations to this ServiceEntry:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: testserver-dev
spec:
  exportTo:
  - .
  host: testserver-dev.wmt
  subsets:
  - name: a
    trafficPolicy:
      outlierDetection:
        baseEjectionTime: 30s
      tls: {}
  - name: b
    trafficPolicy:
      outlierDetection:
        baseEjectionTime: 40s
      tls: {}
```

Start a proxy that "sees" this configuration and check the response to the /clusters endpoint.
While the default cluster has the endpoint, the clusters for the subsets a and b don't get any endpoint.

Also Pilot/Istiod reports `pilot_eds_no_instances` for these clusters.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Istio 1.6.1 on Docker for Mac

**How was Istio installed?**
Istio Operator

**Environment where bug was observed (cloud vendor, OS, etc)**
Docker for Mac
