### ISSUE TITLE
Istio Ingress Gateway with TLS termination returning 503 service unavailable

### ISSUE THREAD

**Issue by vbottu** [istio/istio#24993]
**Bug description**
Istio Ingress Gateway with TLS termination returning 503 service unavailable. I have a service that runs on port 443 with self signed certificate , i have created a secret with tls.crt and tls.key from that service in the same namespace where the service is running and below are my gateway,virtualservice and destination rule 
**Gateway**
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: myapp-gateway
  namespace: myapp
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: app-tls-certificate
    hosts:
    - "myapp.example.com"
```
**VirtualService**
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: myapp-virtualservice
  namespace: myapp
spec:
  hosts:
  - "myapp.example.com"
  gateways:
  - myapp-gateway
  http:
  - match:
    - uri:
        port: https
        prefix: /
    route:
    - destination:
        host: myapp.myapp.svc.cluster.local
        port:
          number: 8443
```
**DestinationRule**

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: myapp-destinationrule
  namespace: myapp
spec:
  host: myapp.myapp.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 8443 
      tls:
        mode: SIMPLE
```
Logs from ingress gateway pod

` HTTP/2" 503 NR "-" "-" 0 0 0 - "*.*.*.*" "curl/7.58.0" "2539c018-f804-4dbb-a1af-178fd9efee03" "myapp.example.com" "-" - - *.*.*.*:443 *.*.*.*:58300 myapp.example.com`

logs from ingress-sds container

`2020-06-25T14:49:38.739339Z     info    sdsServiceLog   CONNECTION ID: router~*.*.*.*~istio-ingressgateway-d6c54f96d-65j75.istio-system~istio-system.svc.cluster.local-10, RESOURCE NAME: app-tls-certificate, EVENT: pushed key/cert pair to proxy`

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
The service should be accessible 
**Steps to reproduce the bug**
deploy a service with self signed certificate and deploy gateway,virtualservice and destinationrule to access the service 
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio version: 1.4.0
k8s version: 1.15.5

**How was Istio installed?**
kubectl apply -f
**Environment where bug was observed (cloud vendor, OS, etc)**
On prem

**Comment by nschhina** [comment]
can you also post log from your sidecar container?

**Comment by vbottu** [comment]
Here are the logs from the side car when i run the below command
`curl -v -k https://myapp.example.com/`

```
[2020-06-27T19:27:03.538Z] "- - -" 0 - "-" "-" 0 0 4 - "-" "-" "-" "-" "127.0.0.1:8443" inbound|443|https-myapp|myapp.myapp.svc.cluster.local 127.0.0.1:34168 10.*.*.*:8443 10.*.*.*:53670 outbound_.443_._.myapp.myapp.svc.cluster.local-
[2020-06-27T19:27:03.724Z] "- - -" 0 - "-" "-" 0 0 3 - "-" "-" "-" "-" "127.0.0.1:8443" inbound|443|https-myapp|myapp.myapp.svc.cluster.local 127.0.0.1:34176 10.*.*.*:8443 10.*.*.*:53676 outbound_.443_._.myapp.myapp.svc.cluster.local -
```
I tried with the following destinationrule,since mutual tls is enabled globally

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: myapp
  namespace: myapp
spec:
  host: myapp.myapp.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 443 
      tls:
        mode: ISTIO_MUTUAL
```
