### ISSUE TITLE
VirtualService header modification does not support TLS parameters

### ISSUE THREAD

**Issue by tmshort** [istio/istio#25005]
**Bug description**

Per #19761 header modification with parameters is fully supported. However, certain parameters are not filled in when specified. Any parameters that need to look at the SSL connection remain blank. The intent is to have a friendlier header field with just the URI SANs to provide to the service, rather than the current X-Forwarded-Client-Cert (which would require server-side code modification).

The virtual service is:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpbin
  namespace: header-test
spec:
  hosts:
  - httpbin.header-test.svc.cluster.local
  http:
  - match:
    - port: 8000
    route:
    - destination:
        host: httpbin.header-test.svc.cluster.local
        port:
          number: 8000
      headers:
        request:
          set:
            x-foo00: "Hello"
            x-foo01: "PROTOCOL %PROTOCOL%"
            x-foo02: "DOWNSTREAM_REMOTE_ADDRESS %DOWNSTREAM_REMOTE_ADDRESS%"
            x-foo03: "DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT %DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
            x-foo04: "DOWNSTREAM_LOCAL_ADDRESS %DOWNSTREAM_LOCAL_ADDRESS%"
            x-foo05: "DOWNSTREAM_LOCAL_ADDRESS_WITHOUT_PORT %DOWNSTREAM_LOCAL_ADDRESS_WITHOUT_PORT%"
            x-foo06: "DOWNSTREAM_LOCAL_PORT %DOWNSTREAM_LOCAL_PORT%"
            x-foo07: "DOWNSTREAM_PEER_URI_SAN %DOWNSTREAM_PEER_URI_SAN%"
            x-foo08: "DOWNSTREAM_LOCAL_URI_SAN %DOWNSTREAM_LOCAL_URI_SAN%"
            x-foo09: "DOWNSTREAM_PEER_ISSUER %DOWNSTREAM_PEER_ISSUER%"
            x-foo10: "DOWNSTREAM_PEER_SUBJECT %DOWNSTREAM_PEER_SUBJECT%"
            x-foo11: "DOWNSTREAM_LOCAL_SUBJECT %DOWNSTREAM_LOCAL_SUBJECT%"
            x-foo12: "DOWNSTREAM_TLS_SESSION_ID %DOWNSTREAM_TLS_SESSION_ID%"
            x-foo13: "DOWNSTREAM_TLS_CIPHER %DOWNSTREAM_TLS_CIPHER%"
            x-foo14: "DOWNSTREAM_TLS_VERSION %DOWNSTREAM_TLS_VERSION%"
            x-foo15: "DOWNSTREAM_PEER_FINGERPRINT_256 %DOWNSTREAM_PEER_FINGERPRINT_256%"
            x-foo16: "DOWNSTREAM_PEER_SERIAL %DOWNSTREAM_PEER_SERIAL%"
            x-foo17: "DOWNSTREAM_PEER_CERT %DOWNSTREAM_PEER_CERT%"
            x-foo18: "DOWNSTREAM_PEER_CERT_V_START %DOWNSTREAM_PEER_CERT_V_START%"
            x-foo19: "DOWNSTREAM_PEER_CERT_V_END %DOWNSTREAM_PEER_CERT_V_END%"
            x-foo20: "START_TIME %START_TIME%"
            x-foo21: "PER_REQUEST_STATE(source.principal) %PER_REQUEST_STATE(source.principal)%"
            x-foo22: "HOSTNAME %HOSTNAME%"
```

The above list is based on the envoy 1.14.1 code for header parameter replacement.

It may be that the configuration of the `request_headers_to_add` is done at too early a point, although TLS values ought to be available immediately after the connection is established. The headers are listed in the envoy config (see below). Envoy documentation indicates an order of the of header processing, indicating that *RouteAction* before *VirtualHost* before *RouteConfig*. As far as I can tell, the `request_headers_to_add` configuration is added at the RouteAction level.

Collapsed configuration:
```
{
    "configs": [
        {
            "@type": "type.googleapis.com/envoy.admin.v3.RoutesConfigDump", 
            "static_route_configs": [], 
            "dynamic_route_configs": [
                {
                    "version_info": "2020-06-25T14:54:41Z/49", 
                    "route_config": {
                        "@type": "type.googleapis.com/envoy.api.v2.RouteConfiguration", 
                        "name": "8000", 
                        "virtual_hosts": [
                            {
                                "name": "httpbin.header-test.svc.cluster.local:8000", 
                                "domains": [], 
                                "routes": [
                                    {
                                        "match": {}, 
                                        "route": {}, 
                                        "metadata": {}, 
                                        "decorator": {}, 
                                        "request_headers_to_add": [
                                            {
                                                "header": {
                                                    "key": "x-foo00", 
                                                    "value": "Hello"
                                                }, 
                                                "append": false
                                            }, 
...
                                        ], 
                                    }
                                ]
                            }
                        ], 
                        "validate_clusters": false
                    }, 
                    "last_updated": "2020-06-25T14:54:41.921Z"
                }
            ]
        }, 
        {}
    ]
}
```

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

Define a simple service service using the sleep and httpbin examples. Use curl to access the httpbin service from the sleep pod. The headers returned are not fully populated.

```
$ kubectl exec -it -n header-test deploy/sleep -c sleep -- curl http://httpbin.header-test.svc.cluster.local:8000/headers
{
  "headers": {
    "Accept": "*/*", 
    "Content-Length": "0", 
    "Host": "httpbin.header-test.svc.cluster.local:8000", 
    "User-Agent": "curl/7.58.0", 
    "X-B3-Parentspanid": "51e527d20c434527", 
    "X-B3-Sampled": "0", 
    "X-B3-Spanid": "3ad37af34763205d", 
    "X-B3-Traceid": "ef10126fd86809d251e527d20c434527", 
    "X-Foo00": "Hello", 
    "X-Foo01": "PROTOCOL HTTP/1.1", 
    "X-Foo02": "DOWNSTREAM_REMOTE_ADDRESS 172.23.5.105:58756", 
    "X-Foo03": "DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT 172.23.5.105", 
    "X-Foo04": "DOWNSTREAM_LOCAL_ADDRESS 10.3.0.235:8000", 
    "X-Foo05": "DOWNSTREAM_LOCAL_ADDRESS_WITHOUT_PORT 10.3.0.235", 
    "X-Foo06": "DOWNSTREAM_LOCAL_PORT 8000", 
    "X-Foo07": "DOWNSTREAM_PEER_URI_SAN", 
    "X-Foo08": "DOWNSTREAM_LOCAL_URI_SAN", 
    "X-Foo09": "DOWNSTREAM_PEER_ISSUER", 
    "X-Foo10": "DOWNSTREAM_PEER_SUBJECT", 
    "X-Foo11": "DOWNSTREAM_LOCAL_SUBJECT", 
    "X-Foo12": "DOWNSTREAM_TLS_SESSION_ID", 
    "X-Foo13": "DOWNSTREAM_TLS_CIPHER", 
    "X-Foo14": "DOWNSTREAM_TLS_VERSION", 
    "X-Foo15": "DOWNSTREAM_PEER_FINGERPRINT_256", 
    "X-Foo16": "DOWNSTREAM_PEER_SERIAL", 
    "X-Foo17": "DOWNSTREAM_PEER_CERT", 
    "X-Foo18": "DOWNSTREAM_PEER_CERT_V_START", 
    "X-Foo19": "DOWNSTREAM_PEER_CERT_V_END", 
    "X-Foo20": "START_TIME 2020-06-25T19:34:58.064Z", 
    "X-Foo21": "PER_REQUEST_STATE(source.principal)", 
    "X-Foo22": "HOSTNAME sleep-68995f5554-csf5j", 
    "X-Forwarded-Client-Cert": "By=spiffe://example.com/dev/ns/header-test/sa/default;Hash=xxxx;Subject=\"\";URI=spiffe://example.com/dev/ns/header-test/sa/default;DNS=default.header-test.dev.example.com;DNS=*.default.header-test.smc.example.com"
  }
}
```
Note that none of the headers referencing TLS values are filled.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

kubernetes v1.17.3
istio 1.5.4
The istio-proxy envoy claims to be based on 1.14.1

**How was Istio installed?**

Helm chart

**Environment where bug was observed (cloud vendor, OS, etc)**

kubernetes v1.17.3

**Comment by tmshort** [comment]
Sample configuration.
[istio-bug.yaml.txt](https://github.com/istio/istio/files/4833665/istio-bug.yaml.txt)

**Comment by tmshort** [comment]
We played with envoy config, and when we put the `request_headers_to_add` into the `route_config` section, we were able to get the header updated as we wanted; if it's deeper in the `route` section (where istio puts it), it doesn't work.

**Comment by tmshort** [comment]
```
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "example.com"
              routes:
              - match:
                  prefix: "/service/1"
                route:
                  cluster: service1
# does not work - this is where istio puts this configuration
#                  request_headers_to_add:
#                    - header:
#                        key: "x-foo"
#                        value: "ciphers: %DOWNSTREAM_TLS_CIPHER%"
              - match:
                  prefix: "/service/2"
                route:
                  cluster: service2
# works
            request_headers_to_add:
              - header:
                  key: "x-foo"
                  value: "ciphers: %DOWNSTREAM_TLS_CIPHER%"

**Comment by howardjohn** [comment]
This seems like an envoy bug, I can't imagine its intended behavior that it only works at the top level and not in the route...

@lambdai any idea?

**Comment by lambdai** [comment]
it seems legit to evaluate the downstream cipher var. Let me check...

**Comment by tmshort** [comment]
Yes, it might be an envoy bug, but istio could also work around it.

**Comment by tmshort** [comment]
> it seems legit to evaluate the downstream cipher var. Let me check...

It's all TLS-related variables.

**Comment by tmshort** [comment]
Any update on this?

**Comment by lambdai** [comment]
My understanding is that there are 3 connections
sleep --(rawtcp)--> sleepsidecar --(TLS)--> httpbinsidecar --(rawtcp)--> httpbin

Only httpbinsidecar could see downstream as tls, while sleepsidecar see downstream as rawtcp with no tls information.
However, the virtual service is actually applied the "header-evaluate-and-add" to sleepsidecar. sleepsidecar fill the header with 
`x-foo12: "DOWNSTREAM_TLS_SESSION_ID %DOWNSTREAM_TLS_SESSION_ID%"` to 
`x-foo12: "DOWNSTREAM_TLS_SESSION_ID`

Looks like you need to modify the route at **httpbinsidecar**

**Comment by tmshort** [comment]
> Looks like you need to modify the route at httpbinsidecar, and override any existing x-foo12 if any
By "you", I'm assuming you mean istio?

The defined virtual service is specified for httpbin.

**Comment by lambdai** [comment]
We all agree headers_to_add is the key functionality to achieve the goal before we introduce cutting edge wasm plugin.

Though I am not fully sure but I need a confirmation that your goal is to deliver the TLS info between two envoy sidecar to the header to httpbin app. 

So we actually have two issues here.
1. which sidecar envoy is supposed to evaluate the downstream tls info? According to my understanding above, the answer is httpbin sidecar. But istio is putting `headers to add` in sleep sidecar. 
2. regardless which envoy we put `header to add`, the `add` operation doesn't work if it falls into per route. I haven't looked into this yet.

**Comment by tmshort** [comment]
Yes, the httpbin sidecar is to evaluate the downstream info; the goal is to get the httpbin application to evaluate TLS connection information.

**Comment by tmshort** [comment]
> 2. regardless which envoy we put header to add, the add operation doesn't work if it falls into per route. I haven't looked into this yet.

It appears that it needs to be done at the `route_config` level

**Comment by lambdai** [comment]
@tmshort 
I run envoy from istio 1.5.6 and envoy could evaluate DOWNSTREAM_TLS_XXX variables under per route 
```
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend2
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/echo"
                route:
                  cluster: "echo_cluster"
              - match:
                  prefix: "/headers"
                route:
                  cluster: "clusterhttpbin"
                request_headers_to_add:
                  - header:
                      key: "x-foo"
                      value: "ciphers: %DOWNSTREAM_TLS_CIPHER%"
                  - header:
                      key: "x1-foo"
                      value: "bar"
```
My local env is 
curl ---TLS---> (listener localhost:15009) envoy (cluster:httpbin) ---rawtcp---> httpbin

curl -k https://localhost:15009/headers

```
$ curl -k https://localhost:15009/headers
{
  "headers": {
    "Accept": "*/*",
    "Content-Length": "0",
    "Host": "localhost:15009",
    "User-Agent": "curl/7.58.0",
    "X-Envoy-Expected-Rq-Timeout-Ms": "15000",
    "X-Foo": "ciphers: TLS_AES_256_GCM_SHA384",
    "X1-Foo": "bar"
  }
}
```
