### ISSUE TITLE
Can't reference a secret from a different namespace

### ISSUE THREAD

**Issue by southbanksoftwaredeveloper** [istio/istio#25018]
**Bug description**

Cannot reference a secret from a different namespace when configuring the gateway.

**Expected behavior**

There should probably be a way to reference  a secret from a different namespace when configuring the gatway.

**Steps to reproduce the bug**

I have a gateway resource configured like this

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
    - hosts:
        - "*"
      port:
        number: 80
        protocol: http
        name: http
      tls:
        httpsRedirect: true
    - hosts:
        - "*"
      port:
        number: 443
        protocol: https
        name: https
      tls:
        mode: SIMPLE
        credentialName: tls-cert
    - hosts:
        - "*.dev.mydomain.io"
      port:
        number: 27017
        protocol: TLS
        name: mongo
      tls:
        mode: PASSTHROUGH
```

Here, the gateway is setup in `istio-system` namespace. However, my tls cert secret is stored in a different namespace (`dev` namespace). 
Basically, I want to do something like `credentialName: dev/tls-cert`

I confirmed that if the certificate is present in `istio-system`, then it works fine.
Is it possible to do this?

**Version 

```
istioctl version --remote                                                         
client version: 1.5.4
citadel version: 1.5-alpha.38674083a2444b732ac4f29f9afef4aa1743d191
galley version: 1.5-alpha.927fa988824d95916cd1a466ad27777049885b51
ingressgateway version: 1.5-alpha.927fa988824d95916cd1a466ad27777049885b51
pilot version: 1.5-alpha.927fa988824d95916cd1a466ad27777049885b51
policy version: 1.5-alpha.927fa988824d95916cd1a466ad27777049885b51
sidecar-injector version: 1.5-alpha.38674083a2444b732ac4f29f9afef4aa1743d191
telemetry version: 1.5-alpha.927fa988824d95916cd1a466ad27777049885b51
data plane version: 1.5-alpha.8b1cc6aa35e0bbc85db2325f0a9c5d86d1344f00 (8 proxies), 1.5-alpha.927fa988824d95916cd1a466ad27777049885b51 (26 proxies), 1.4-alpha.c4305fa078fbc14ae143f63e395c6f0c8e886670 (4 proxies), 1.5-alpha.38674083a2444b732ac4f29f9afef4aa1743d191 (6 proxies), 1.4-alpha.0f242b04e7b3ea62e13d3e89ea8890c1add57916 (2 proxies)
 ~ ▓▒░ kubectl version                                                              
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"2b13e288f94dd2577d4ff7261f9eb76b1d5692a1", GitTreeState:"clean", BuildDate:"2020-06-01T21:55:34Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
 ~ ▓▒░ helm version                                                                   
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

**How was Istio installed?**

using helm
