### ISSUE TITLE
Feature: Support `minReadySeconds` on ingressgateway Deployment

### ISSUE THREAD

**Issue by aaron-trout** [istio/istio#25029]
**Describe the feature request**
Would like to have the ability to configure `minReadySeconds` field on `Deployment.spec` so that I can give the AWS Load Balancer (NLB) enough time to update the target hosts when `externalTrafficPolicy: Local` is set on the ingressgateway service.

At present, if you need/want to use `externalTrafficPolicy: Local`, there is potential downtime when restarting the ingressgateway deployment (or if a node dies etc), because the AWS NLB does not update the target group fast enough. 

This would be easily resolved by setting `minReadySeconds` on the ingressgateway deployment to more than `(target group probe interval * target group probe success threshold) / ingressgateway replica count`, however it is currently not possible to set this value in the Helm chart or the Operator (as of 1.6.3).

**Describe alternatives you've considered**

Alternative is to manage the ingressgateway manually outside of operator / helm. This may work I guess. Other than that the only option I see is to not use `externalTrafficPolicy: Local`

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
Can this be solved with patching (if using the operator) or something like kustomize (if using kubectl)? This seems like a pretty obscure setting - we cannot feasibly support every single option in Kubernetes, that is what other tools are meant for

**Comment by aaron-trout** [comment]
@howardjohn Yeah I think this is solvable with Kustomize, but that is not a supported deployment method afaik? Seems like the recommended way going forwards is the Operator, is that right? I couldn't see any options in the Operator docs for how to set this; if there is some generic overlay functionality in the operator I can use, please point me in that direction :-)

**Comment by howardjohn** [comment]
You can use https://preliminary.istio.io/latest/docs/setup/install/istioctl/#patching-the-output-manifest. I am pretty sure it will support this but not certain

**Comment by aaron-trout** [comment]
Thanks @howardjohn, looks like this is indeed possible with the Operator! Here is my config for reference:

```yaml
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-operator
spec:
  profile: default
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      label:
        istio: ingressgateway
        app: istio-ingressgateway
      k8s:
        overlays:
        - apiVersion: v1
          kind: Service
          name: istio-ingressgateway
          patches:
          - path: metadata.annotations
            value: |
              service.beta.kubernetes.io/aws-load-balancer-type: nlb
          - path: spec.externalTrafficPolicy
            value: Local
        - apiVersion: apps/v1
          kind: Deployment
          name: istio-ingressgateway
          patches:
          - path: spec.minReadySeconds
            value: 90
```
