### ISSUE TITLE
Configuring Custom Ingress Gateway to make it work

### ISSUE THREAD

**Issue by sb1975** [istio/istio#25038]
**Bug description**
There is page for Gateway configuration - https://istio.io/latest/docs/reference/config/networking/gateway/
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
  namespace: some-config-namespace
spec:
  selector:
    app: my-gateway-controller
Here - app: my-gateway-controller - this needs to be configured on the ingress-gateway isnt it ?

There is no clarity how the ingress-gateway would be configured to make this work ?

[ ] Configuration Infrastructure
[x ] Docs
[x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by sb1975** [comment]
It is not clear how this field label is configured in the docs page - https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/

https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#GatewaySpec

label | map<string, string> | Labels for the gateway. | No

**Comment by morvencao** [comment]
@sb1975 
You can achieve that by creating IOP instance similar to this:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
      - name: my-gateway
        enabled: true
        label:
           app: my-gateway-controller
```
