### ISSUE TITLE
PII scrubbing YAML tool

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#25048]
For various scenarios, its useful to get information about a users configuration. However, users often don't want to provide it as it may contain confidential information. It would be useful to have a tool that takes these configs and scrubs identifiable information. This would be especially useful when analyzing scaling/perf issues, as we can get an exact dump of their cluster state.

How I envision this is to have a schema aware tool, which would block out any custom fields in the yaml. Ideally, it would also maintain referential integrity. For example

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: reviews-route
spec:
  hosts:
  - reviews.prod.svc.cluster.local
  http:
  - match:
    - sourceLabels:
        env: prod
    route:
    - destination:
        host: reviews.prod.svc.cluster.local
        subset: v1
```

would be come
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: lorem-ipsum
spec:
  hosts:
  - dolorsitamet
  http:
  - match:
    - sourceLabels:
        consectetur: adipiscing
    route:
    - destination:
        host: dolorsitamet # NOTE!! this matches "hosts" above
        subset: foobar
```

Things to note:
* `reviews` is replaced with the same string in all referenced locations.
* We are also not just simply changing values; see the `env` field which is part of a `map[string]string`, where we replace the key and the value

cc @ostromart might be related to your support-ability work
