### ISSUE TITLE
WorloadEntry does not support Authorization

### ISSUE THREAD

**Issue by fscz** [istio/istio#25078]
**Bug description**

I created the following yaml configuration that uses a WorkloadEntry/ServiceEntry combination in order to link to an application running on a virtual machine. By doing that in combination with an AuthorizationPolicy, I was hoping to implement an elegant replacement for what is described in the docs. See https://istio.io/latest/docs/examples/virtual-machines/single-network/. 

However, unfortunately, the AuthorizationPolicy does not seem to select the WorkloadEntry and thus I cannot control access to the application on the virtual machine. This is unfortunate because configuring a virtual machine in the sense of the above document requires installation of a client program that is available for Linux machines but not Windows or Mac. Windows or Mac machines thus cannot join the Service Mesh.
```
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: simple-testinst
spec:
  address: 172.19.135.43
  ports:
    http: 8080
  labels:
    app: simple-testinst
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: simple-testinst
  labels:
    app: simple-testinst
spec:
  hosts:
  - simple-testinst.datalab-dev.ddc.company.de
  - simple-testinst.default.svc.cluster.local
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: STATIC
  location: MESH_INTERNAL
  workloadSelector:
    labels:
      app: simple-testinst
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: simple-testinst
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-80
      protocol: http
    hosts:
    - simple-testinst.datalab-dev.ddc.company.de
    - simple-testinst.default.svc.cluster.local
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: simple-testinst
spec:
  hosts:
  - simple-testinst.datalab-dev.ddc.company.de
  - simple-testinst.default.svc.cluster.local
  gateways:
  - simple-testinst
  - mesh
  http:
  - route:
    - destination:
        host: simple-testinst.datalab-dev.ddc.company.de
---
apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
  name: simple-testinst
spec:
  selector:
    matchLabels:
      app: simple-testinst
  action: ALLOW
  rules:
  - when:
    - key: request.auth.claims[iss]
      values: ["https://keycloak.datalab-dev.ddc.company.de/auth/realms/badatalab"]
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[x ] Policies and Telemetry
[ x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
I would expect the AuthorizationPolicy from the above configuration to control access to the WorkloadEntry resource. 

**Steps to reproduce the bug**
Apply the yaml file and test ingress access to the app running on the instance, f.e. with a browser.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.6.3

**How was Istio installed?**
istioctl 

**Environment where bug was observed (cloud vendor, OS, etc)**
aws/eks
