### ISSUE TITLE
Getting 503 - Replicated Control Planes

### ISSUE THREAD

**Issue by kpiyush17** [istio/istio#25077]
Hi,

I have been following this doc: https://istio.io/latest/docs/setup/install/multicluster/gateways/ for setting up multi-cluster istio. I followed the same steps but I am getting 503 when using the curl command:
`kubectl exec -it sleep-6bdb595bcb-ssb58 -n foo -c sleep -- curl -I httpbin.bar.global:8000/headers`

I used CoreDNS >=  1.4.0. I want to use Egress's way of connecting two services. I tried both the hostname and IP address option of service entry.

For IP Address, I am doing nslookup for LB for istio-ingressgateway of httpbin cluster and putting the IP in place of `${CLUSTER2_GW_ADDR}`
```
endpoints:
  - address: ${CLUSTER2_GW_ADDR}
    network: external
    ports:
      http1: 15443 # Do not change this port value
  - address: ${CLUSTER1_EGW_ADDR}
    ports:
      http1: 15443
```

For hostname, I am putting LB address in place of `${CLUSTER2_GW_ADDR}`
```
endpoints:
  - address: ${CLUSTER2_GW_ADDR}
    network: external
    ports:
      http1: 15443
  - address: istio-egressgateway.istio-system.svc.cluster.local
    ports:
      http1: 15443
```

Both ways are not working and I am getting 503 errors. I am not sure how to debug this? Do, I need to create virtualservice/destination if httpbin?

Thanks

**Comment by ClareChu** [comment]
hi! @kpiyush17  install Replicated Control Planes , remote cluster  does not require creating an virtualservice/destination, What are the error logs?  istiod ,coredns

**Comment by kpiyush17** [comment]
Hi, 

I checked istiod, coredns, and istio-proxy logs. I used `kubectl logs -f` and I do not see any logs when I am calling:
```
> kubectl exec -it sleep-6bdb595bcb-ssb58 -c sleep -- curl -I http://httpbin.bar.global:8000/headers
HTTP/1.1 503 Service Unavailable
content-length: 91
content-type: text/plain
date: Mon, 29 Jun 2020 04:17:43 GMT
server: envoy
```

**Comment by ClareChu** [comment]
Do you create resources ServiceEntry ?  in ManagerCluster

**Comment by kpiyush17** [comment]
Yes, my current ServiceEntry:

```
kubectl apply -n foo -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin-bar
spec:
  hosts:
  - httpbin.bar.global
  location: MESH_INTERNAL
  ports:
  - name: http1
    number: 8000
    protocol: http
  resolution: DNS
  addresses:
  - 240.0.0.5
  endpoints:
  - address: <>.eu-west-1.elb.amazonaws.com
    network: external
    ports:
      http1: 15443
  - address: istio-egressgateway.istio-system.svc.cluster.local
    ports:
      http1: 15443
EOF
```

**Comment by ClareChu** [comment]
Do you telnet  <>.eu-west-1.elb.amazonaws.com: 15443  your RemoteCluster is  successful?

**Comment by kpiyush17** [comment]
Yes, it is successful.

**Comment by kpiyush17** [comment]
Can anyone help me with this?

**Comment by ClareChu** [comment]
Can you tell me the detailed operation steps

**Comment by kpiyush17** [comment]
Istio version: 1.6.1
K8s version: 1.15 AWS EKS

Access log  from sleep proxy:

```
2020-06-29T23:11:31.227036061Z {"bytes_sent":"0","upstream_cluster":"outbound|8000||httpbin.bar.global","downstream_remote_address":"192.168.96.232:52516","authority":"httpbin.bar.global:8000","path":"/headers","protocol":"HTTP/1.1","upstream_service_time":"-","upstream_local_address":"-","duration":"31","upstream_transport_failure_reason":"-","route_name":"default","downstream_local_address":"240.0.0.5:8000","user_agent":"curl/7.69.1","response_code":"503","response_flags":"UF,URX","start_time":"2020-06-29T23:11:26.760Z","method":"HEAD","request_id":"a90caa24-a48e-4f5c-b0ec-77c15ad0e3ab","upstream_host":"10.100.46.111:15443","x_forwarded_for":"-","requested_server_name":"-","bytes_received":"0","istio_policy_status":"-"}
```

In the above log `"upstream_host":"10.100.46.111:15443"`, this is egress cluster IP.
But there are no access logs on the egress side. So, I am assuming traffic not going to egress properly.   

My istio yaml:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  addonComponents:
    istiocoredns:
      enabled: true
    kiali:
      enabled: true
    tracing:
      enabled: true
    prometheus:
      enabled: false

  components:
    egressGateways:
      - name: istio-egressgateway
        enabled: true
    telemetry:
        enabled: true
    citadel:
        enabled: true

  meshConfig:
    accessLogFile: "/dev/stdout"
    accessLogEncoding: JSON

  values:
    global:
      # Provides dns resolution for global services
      podDNSSearchNamespaces:
        - global

      multiCluster:
        enabled: true

      controlPlaneSecurityEnabled: true

      proxy:
        privileged: true

    gateways:
      istio-egressgateway:
        env:
          ISTIO_META_REQUESTED_NETWORK_VIEW: "external"
```

**Comment by ClareChu** [comment]
do you create k8s `secret` source in remote-cluster  and manager-cluster?  

example
`
➜  ~ kc get secret -n istio-system cacerts
NAME      TYPE     DATA   AGE
cacerts   Opaque   4      19d
`

 check your remote-cluster  and manager-cluster it is consistent?

**Comment by kpiyush17** [comment]
Yes, the secrets were created. I am using the one provided in the samples by istio. Both clusters using the same istio yaml. Is `meshExpansion` mandatory?

**Comment by ClareChu** [comment]
yes ! It has to be  `meshExpansion `,

this is istio doc yaml

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  addonComponents:
    istiocoredns:
      enabled: true

  components:
    egressGateways:
      - name: istio-egressgateway
        enabled: true

  values:
    global:
      # Provides dns resolution for global services
      podDNSSearchNamespaces:
        - global
 #       - "{{ valueOrDefault .DeploymentMeta.Namespace \"default\" }}.global"

      multiCluster:
        enabled: true

      controlPlaneSecurityEnabled: true

    gateways:
      istio-egressgateway:
        env:
          # Needed to route traffic via egress gateway if desired.
          ISTIO_META_REQUESTED_NETWORK_VIEW: "external"
```

**Comment by kpiyush17** [comment]
@ClareChu But I am not seeing meshExpansion in the above yaml.

**Comment by ClareChu** [comment]
you need to take care `istio-ingressgateway` sevice EXTERNAL-IP

```bash
➜  multicluster kc get svc -n istio-system istio-ingressgateway
NAME                   TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                                                                                                                   AGE
istio-ingressgateway   LoadBalancer   10.70.131.67   10.10.10.11   15021:27145/TCP,80:35849/TCP,443:37072/TCP,15443:22904/TCP,15011:36129/TCP,15012:31516/TCP,8060:28389/TCP,853:31960/TCP   19d
```

**Comment by kpiyush17** [comment]
In my service entry yaml, I am using Load Balancer URL only provided by AWS.

```
kubectl apply -n foo -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin-bar
spec:
  hosts:
  - httpbin.bar.global
  location: MESH_INTERNAL
  ports:
  - name: http1
    number: 8000
    protocol: http
  resolution: DNS
  addresses:
  - 240.0.0.5
  endpoints:
  - address: <>.eu-west-1.elb.amazonaws.com
    network: external
    ports:
      http1: 15443
  - address: istio-egressgateway.istio-system.svc.cluster.local
    ports:
      http1: 15443
EOF
```

**Comment by ClareChu** [comment]
> @ClareChu But I am not seeing meshExpansion in the above yaml. Adding `meshExpansion` and applying it.

`meshExpansion` didn't do it

**Comment by ClareChu** [comment]
```yaml
  - address: istio-egressgateway.istio-system.svc.cluster.local
    ports:
      http1: 15443
```
what does this one mean?

**Comment by kpiyush17** [comment]
I think this is for the traffic to go through egress. Using this yaml provided in the doc: [https://istio.io/latest/docs/setup/install/multicluster/gateways/#send-remote-traffic-via-an-egress-gateway]

**Comment by ClareChu** [comment]
```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  creationTimestamp: "2020-06-12T11:32:15Z"
  generation: 7
  name: httpbin-bar
  namespace: foo
  resourceVersion: "1662199"
  selfLink: /apis/networking.istio.io/v1beta1/namespaces/foo/serviceentries/httpbin-bar
  uid: 07862e34-4848-455e-9e20-f517b488d84a
spec:
  addresses:
  - 240.0.0.2
  endpoints:
  - address: 10.10.10.11
    ports:
      http1: 15443
  hosts:
  - httpbin.bar.global
  location: MESH_INTERNAL
  ports:
  - name: http1
    number: 8000
    protocol: http
  resolution: DNS
```

**Comment by ClareChu** [comment]
> 我认为这是为了让流量通过出口。使用文档中提供的以下Yaml：[https](https://istio.io/latest/docs/setup/install/multicluster/gateways/#send-remote-traffic-via-an-egress-gateway)：[//istio.io/latest/docs/setup/install/multicluster/gateways/#send-remote-traffic-via-an-egress-gateway](https://istio.io/latest/docs/setup/install/multicluster/gateways/#send-remote-traffic-via-an-egress-gateway)
> 
> 我正在使用主机名yaml之一。

@kpiyush17  I do not using  AWS Load Balancer URL, So this place didn't help you

**Comment by kpiyush17** [comment]
So, in the case of your ServiceEntry yaml, the sidecar will directly talk to the ingress-gateway of the remote cluster which is working. But, I want the traffic to go through egress gateway.

**Comment by ClareChu** [comment]
ok， Then I'll let you know after I've tried.  I think No problem
And tell you how to configure it

**Comment by ClareChu** [comment]
Send remote traffic via an egress gateway

 serviceentry.yml
```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1beta1","kind":"ServiceEntry","metadata":{"annotations":{},"creationTimestamp":"2020-06-12T11:32:15Z","generation":11,"name":"httpbin-bar","namespace":"foo","resourceVersion":"5471232","selfLink":"/apis/networking.istio.io/v1beta1/namespaces/foo/serviceentries/httpbin-bar","uid":"07862e34-4848-455e-9e20-f517b488d84a"},"spec":{"addresses":["240.0.0.2"],"endpoints":[{"address":"10.10.13.34","network":"external","ports":{"http1":15443}},{"address":"10.10.13.30","ports":{"http1":15443}}],"hosts":["httpbin.bar.global"],"location":"MESH_INTERNAL","ports":[{"name":"http1","number":8000,"protocol":"http"}],"resolution":"DNS"}}
  creationTimestamp: "2020-07-02T11:04:07Z"
  generation: 2
  name: httpbin-bar
  namespace: foo
  resourceVersion: "5507354"
  selfLink: /apis/networking.istio.io/v1beta1/namespaces/foo/serviceentries/httpbin-bar
  uid: 77437706-b3db-49a9-96dd-9a857cca0cbe
spec:
  addresses:
  - 240.0.0.2
  endpoints:
  - address: 10.10.10.11
    network: external
    ports:
      http1: 15443
  - address: 10.70.129.207
    ports:
      http1: 15443
  hosts:
  - httpbin.bar.global
  location: MESH_INTERNAL
  ports:
  - name: http1
    number: 8000
    protocol: http
  resolution: STATIC
```


```bash
kubectl get --context=$CTX_CLUSTER2 svc --selector=app=istio-ingressgateway \
    -n istio-system -o jsonpath="{.items[0].status.loadBalancer.ingress[0].ip}"
```

CLUSTER2_GW_ADDR = 10.70.129.207

```yaml
  - address: 10.70.129.207
    ports:
      http1: 15443
```

**Comment by kpiyush17** [comment]
@ClareChu Thanks. I will try this. `10.10.10.11` what is this IP, internal egress one?

**Comment by ClareChu** [comment]
> @ClareChu谢谢。我会尝试的。`10.10.10.11`集群1的内部出口IP是什么？

10.10.10.11 ---> remote-cluster gateway address

**Comment by kpiyush17** [comment]
Then, both IPs `10.10.10.11`, `10.70.129.207` are remote cluster gateway?

This is also remote gateway address as mentioned above ---> CLUSTER2_GW_ADDR = 10.70.129.207?

**Comment by ClareChu** [comment]
```bash
➜  ~ kc get svc -n istio-system istio-egressgateway --context manager-cluster
NAME                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                    AGE
istio-egressgateway   ClusterIP   10.70.129.207   10.10.13.32   80/TCP,443/TCP,15443/TCP   20d
```

do you konw?

**Comment by kpiyush17** [comment]
It seems to be working using IPs and `resolution: STATIC`. But is there a way to ensure that it is going through egress?

**Comment by ClareChu** [comment]
> 它似乎正在使用IP和`resolution: STATIC`。但是有没有办法确保它正在通过出口？
> 
> PS：如果我更改`CLUSTER1_EGW_ADDR= 10.70.129.207`为服务FQDN名称：`istio-egressgateway.istio-system.svc.cluster.local`，它将停止工作。

yes,  you update CLUSTER1_EGW_ADDR to istio-egressgateway svc address , It's also working 

`resolution: DNS`

**Comment by kpiyush17** [comment]
Sorry for the late reply. So, here is what I have tried:

In my primary cluster: 10.100.46.111 --> Egress cluster IP

1. This is working. But in the sleep service access logs, the upstream host is <remote_cluster_external_ingress_ip> which I assuming is not going through egress.
```
resolution: STATIC
- address: <remote_cluster_external_ingress_ip>
    network: external
    ports:
      http1: 15443
  - address: 10.100.46.111
    ports:
      http1: 15443
```

2. > yes, you update CLUSTER1_EGW_ADDR to istio-egressgateway svc address , It's also working

I tried this, 
```
resolution: DNS
- address: <remote_cluster_external_ingress_ip>
    network: external
    ports:
      http1: 15443
  - address: istio-egressgateway.istio-system.svc.cluster.local
    ports:
      http1: 15443
```
This is giving 503. Error `upstream connect error or disconnect/reset before headers. reset reason: connection failure`. Here the upstream host is showing 10.100.46.111. Can you check the access logs for the upstream host?

3. I tried this also:
```
resolution: DNS
  - address: <load_balancer_url>.amazonaws.com
    network: external
    ports:
      http1: 15443
- address: istio-egressgateway.istio-system.svc.cluster.local
    ports:
      http1: 15443
```
Same error as point 2.

**Comment by minhhoangvn** [comment]
Hi, I got the same issue. Below are images when I debugging Envoy and Istiod:

![image](https://user-images.githubusercontent.com/17515250/90165444-daa71b80-ddc2-11ea-98d3-6f67251e5096.png)
![image](https://user-images.githubusercontent.com/17515250/90165413-cfec8680-ddc2-11ea-8933-83f360455202.png)
![image](https://user-images.githubusercontent.com/17515250/90165434-d67afe00-ddc2-11ea-953a-87d7dfd83bff.png)

My sample config for 2 k8s clusters:

Cluster A:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
    global:53 {
        errors
        cache 30
        forward . 10.107.133.68:53
    }
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin-foo
spec:
  hosts:
  # must be of form name.namespace.global
  - httpbin.foo.global
  # Treat remote cluster services as part of the service mesh
  # as all clusters in the service mesh share the same root of trust.
  location: MESH_INTERNAL
  ports:
  - name: http1
    number: 8000
    protocol: http
  resolution: DNS
  addresses:
  - 240.0.0.2
  endpoints:
  # This is the routable address of the ingress gateway in cluster2 that
  # sits in front of sleep.foo service. Traffic from the sidecar will be
  # routed to this address.
  - address: 192.168.10.51
    ports:
      http1: 30538 # Do not change this port value

---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin-bar
spec:
  hosts:
  # must be of form name.namespace.global
  - httpbin.bar.global
  # Treat remote cluster services as part of the service mesh
  # as all clusters in the service mesh share the same root of trust.
  location: MESH_INTERNAL
  ports:
  - name: http1
    number: 8000
    protocol: http
  resolution: DNS
  addresses:
  - 240.0.0.3
  endpoints:
  # This is the routable address of the ingress gateway in cluster2 that
  # sits in front of sleep.foo service. Traffic from the sidecar will be
  # routed to this address.
  - address: 192.168.10.51
    ports:
      http1: 30538 # Do not change this port value
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin-legacy
spec:
  hosts:
  # must be of form name.namespace.global
  - httpbin.legacy.global
  # Treat remote cluster services as part of the service mesh
  # as all clusters in the service mesh share the same root of trust.
  location: MESH_INTERNAL
  ports:
  - name: http1
    number: 8000
    protocol: http
  resolution: DNS
  addresses:
  - 240.0.0.4
  endpoints:
  # This is the routable address of the ingress gateway in cluster2 that
  # sits in front of sleep.foo service. Traffic from the sidecar will be
  # routed to this address.
  - address: 192.168.10.51
    ports:
      http1: 30538 # Do not change this port value
```

Cluster B:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
    global:53 {
        errors
        cache 30
        forward . 10.107.226.111:53
    }
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin-foo
spec:
  hosts:
  # must be of form name.namespace.global
  - httpbin.foo.global
  # Treat remote cluster services as part of the service mesh
  # as all clusters in the service mesh share the same root of trust.
  location: MESH_INTERNAL
  ports:
  - name: http1
    number: 8000
    protocol: http
  resolution: DNS
  addresses:
  - 240.0.0.50
  endpoints:
  # This is the routable address of the ingress gateway in cluster2 that
  # sits in front of sleep.foo service. Traffic from the sidecar will be
  # routed to this address.
  - address: 192.168.10.50
    ports:
      http1: 32690 # Do not change this port value

---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin-bar
spec:
  hosts:
  # must be of form name.namespace.global
  - httpbin.bar.global
  # Treat remote cluster services as part of the service mesh
  # as all clusters in the service mesh share the same root of trust.
  location: MESH_INTERNAL
  ports:
  - name: http1
    number: 8000
    protocol: http
  resolution: DNS
  addresses:
  - 240.0.0.51
  endpoints:
  # This is the routable address of the ingress gateway in cluster2 that
  # sits in front of sleep.foo service. Traffic from the sidecar will be
  # routed to this address.
  - address: 192.168.10.50
    ports:
      http1: 32690 # Do not change this port value
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin-legacy
spec:
  hosts:
  # must be of form name.namespace.global
  - httpbin.legacy.global
  # Treat remote cluster services as part of the service mesh
  # as all clusters in the service mesh share the same root of trust.
  location: MESH_INTERNAL
  ports:
  - name: http1
    number: 8000
    protocol: http
  resolution: DNS
  addresses:
  - 240.0.0.52
  endpoints:
  # This is the routable address of the ingress gateway in cluster2 that
  # sits in front of sleep.foo service. Traffic from the sidecar will be
  # routed to this address.
  - address: 192.168.10.50
    ports:
      http1: 32690 # Do not change this port value

```
