### ISSUE TITLE
EnvoyFilter doesn't change Ingress Gateway listener alpn option.

### ISSUE THREAD

**Issue by imcheck** [istio/istio#25081]
**Bug description**
I'm trying to change ingress gateway listener filter to edit `alpn_protocols` option.
I created `EnvoyFilter` resource like below to change the order of protocols in `alpn_protocols`.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: custom-alpn
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: istio-ingressgateway
  configPatches:
  - applyTo: LISTENER
    match:
      listener:
        portNumber: <TARGET_PORT_NUMBER>
    patch:
      operation: MERGE # INSERT_FIRST doesn't work too.
      value:
        filter_chains:
        - transport_socket:
            name: "envoy.transport_socket.custom_alpn"
            typed_config:
              "@type": "type.googleapis.com/envoy.api.v2.auth.DownstreamTlsContext"
              common_tls_context:
                alpn_protocols:
                  - "http/1.1"
                  - "h2"

```
But this resource doesn't change anything. 
The public guidance of Istio is not nice about `EnvoyFilter` resource so that we can't use it easily. 😢 
Is there anyone who let me know how to solve this...

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
Before
```
"transportSocket": {
    "name": "envoy.transport_sockets.tls",
    "typedConfig": {
        "@type": "type.googleapis.com/envoy.api.v2.auth.DownstreamTlsContext",
        "commonTlsContext": {
            "tlsCertificateSdsSecretConfigs": [
                {
                    "name": "realtor-cert",
                    "sdsConfig": {
                        "apiConfigSource": {
                            "apiType": "GRPC",
                            "grpcServices": [
                                {
                                    "googleGrpc": {
                                        "targetUri": "unix:/var/run/ingress_gateway/sds",
                                        "statPrefix": "sdsstat"
                                    }
                                }
                            ]
                        }
                    }
                }
            ],
            "alpnProtocols": [
                "h2",
                "http/1.1"
            ]
        },
        "requireClientCertificate": false
    }
}

```
After
```
"transportSocket": {
    "name": "envoy.transport_sockets.tls",
    "typedConfig": {
        "@type": "type.googleapis.com/envoy.api.v2.auth.DownstreamTlsContext",
        "commonTlsContext": {
            "tlsCertificateSdsSecretConfigs": [
                {
                    "name": "realtor-cert",
                    "sdsConfig": {
                        "apiConfigSource": {
                            "apiType": "GRPC",
                            "grpcServices": [
                                {
                                    "googleGrpc": {
                                        "targetUri": "unix:/var/run/ingress_gateway/sds",
                                        "statPrefix": "sdsstat"
                                    }
                                }
                            ]
                        }
                    }
                }
            ],
            "alpnProtocols": [ # I want to change the order this `alpnProtocols`
                "http/1.1",
                "h2"
            ]
        },
        "requireClientCertificate": false
    }
}

```
**Steps to reproduce the bug**
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
# ISTIO VERSION
client version: 1.5.1
control plane version: 1.5.1
data plane version: 1.5.1 (60 proxies)

# K8S VERSION
1.15.11

# HELM VERSION
v3.1.1
```

**How was Istio installed?**
Using Helm
**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
