### ISSUE TITLE
Error adding/updating listener(s) 0.0.0.0_443: Invalid path: sds

### ISSUE THREAD

**Issue by laurentiuspurba** [istio/istio#25105]
**Bug description**
Toggling _true_ and _false_ for the following parameters
`global.k8sIngress.enabled: true`, 
`global.k8sIngress.enableHttps: true`, 
`gateways.istio-ingressgateway.sds.enabled: true`
gives me `Invalid path: sds` in istio-ingressgateway pods, and `503 Service Unavailable` executing Ingress Gateways traffic management task as documented [here](https://archive.istio.io/v1.4/docs/tasks/traffic-management/ingress/ingress-control/).

_I don't know if this is the same issue as described in this ticket https://github.com/istio/istio/issues/21577_

**Affected product area (please put an X in all that apply)**

[x ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
The [Ingress Gateways traffic management task](https://archive.istio.io/v1.4/docs/tasks/traffic-management/ingress/ingress-control/) should return 200 OK result and can be accessible from the browser

**Steps to reproduce the bug**
1. Enable the following
`global.k8sIngress.enabled: true`, 
`global.k8sIngress.enableHttps: true`, 
`gateways.istio-ingressgateway.sds.enabled: true`
2. Execute [Ingress Gateways traffic management task](https://archive.istio.io/v1.4/docs/tasks/traffic-management/ingress/ingress-control/)
3. Disable the following:
`global.k8sIngress.enabled: false`, 
`global.k8sIngress.enableHttps: false`, 
`gateways.istio-ingressgateway.ds..enabled: false`
4. Re-run [Ingress Gateways traffic management task](https://archive.istio.io/v1.4/docs/tasks/traffic-management/ingress/ingress-control/)
5. YOou will see similar error like the following from istio-ingressgateway pods
`[Envoy (Epoch 0)] [2020-06-30 01:00:21.194][23][warning][config] [external/envoy/source/common/config/grpc_mux_subscription_impl.cc:82] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) 0.0.0.0_443: Invalid path: sds`
or
`[Envoy (Epoch 0)] [2020-06-30 01:02:17.056][16][warning][config] [external/envoy/source/common/config/grpc_mux_subscription_impl.cc:82] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) 0.0.0.0_443: Invalid path: /etc/istio/ingressgateway-certs/tls.crt`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
`istioctl version --remote=false 
1.4.3`

`kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.36", GitCommit:"34a615f32e9a0c9e97cdb9f749adb392758349a6", GitTreeState:"clean", BuildDate:"2020-04-06T16:33:17Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}`

`helm version
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}`

**How was Istio installed?**
helm template and istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
cloud vendor: GKE
OS: linux

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
please provide the exact config you applied? Also 1.4 is EOL, can you try upgrading: https://istio.io/latest/news/support/announcing-1.4-eol-final/

**Comment by laurentiuspurba** [comment]
@howardjohn below is the config that I use. Just wanted to make sure is this the [link](https://archive.istio.io/v1.4/docs/setup/upgrade/) to upgrade procedure?
Thank you. 

```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  security:
    components:
      certManager:
        enabled: false
      citadel:
        k8s:
          replicaCount: 2
          hpaSpec:
            maxReplicas: 5
            minReplicas: 2

  policy:
    components:
      policy:
        k8s:
          replicaCount: 2
          hpaSpec:
            maxReplicas: 5
            minReplicas: 2

  trafficManagement:
    components:
      pilot:
        k8s:
          replicaCount: 2
          hpaSpec:
            maxReplicas: 5
            minReplicas: 2

  gateways:
    components:
      ingressGateway:
        enabled: true
        k8s:
          replicaCount: 2
          hpaSpec:
            maxReplicas: 5
            minReplicas: 2
      egressGateway:
        enabled: true
        k8s:
          replicaCount: 2
          hpaSpec:
            maxReplicas: 5
            minReplicas: 2

  configManagement:
    components:
      galley:
        k8s:
          replicaCount: 2
          hpaSpec:
            maxReplicas: 5
            minReplicas: 2

  telemetry:
    components:
      telemetry:
        k8s:
          replicaCount: 2
          hpaSpec:
            maxReplicas: 5
            minReplicas: 2

  coreDNS:
    enabled: true
    components:
      coreDNS:
        k8s:
          replicaCount: 2
          hpaSpec:
            maxReplicas: 5
            minReplicas: 2

  values:
    prometheus:
      enabled: false

    grafana:
      enabled: false

    kiali:
      enabled: true
      replicaCount: 2

    tracing:
      enabled: true

    global:
      podDNSSearchNamespaces:
        - global
        - "{{ valueOrDefault .DeploymentMeta.Namespace \"default\" }}.global"

      multiCluster:
        enabled: true

      controlPlaneSecurityEnabled: true

      mtls:
        enabled: true

      proxy:
      # disabled istio-proxy injection by default - annotation is required to enable it
        autoInject: disabled

      k8sIngress:
        enabled: true
        enableHttps: true

    security:
      selfSigned: false

    gateways:
      istio-egressgateway:
        env:
          # Needed to route traffic via egress gateway if desired.
          ISTIO_META_REQUESTED_NETWORK_VIEW: "external"
      istio-ingressgateway:
        sds:
          enabled: true

```

**Comment by howardjohn** [comment]
Do you have any Gateway objects though?

**Comment by howardjohn** [comment]
Or Ingress

**Comment by laurentiuspurba** [comment]
The Gateway object is basically from [here](https://archive.istio.io/v1.4/docs/tasks/traffic-management/ingress/ingress-control/), which is

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "httpbin.example.com"
```

When I set the values of those properties to _**false**_, then I started getting _**503 Service Unavailable**_
