### ISSUE TITLE
sni_hosts under VirtualService renamed to sniHosts in 1.6.0

### ISSUE THREAD

**Issue by prabath** [istio/istio#25103]
Tried to deploy the same VirtualService that was running on Istio 1.5.3 on Istio 1.6.3 - and got the following error.

ValidationError(VirtualService.spec.tls[0].match[0]): unknown field "sni_hosts" in io.istio.networking.v1alpha3.VirtualService.spec.tls.match;

The reason seems to be, in Istio 1.6+, sni_hosts under VirtualService is renamed to sniHosts.

Because this change is done under the same API version (http://networking.istio.io/v1alpha3) - thought this could be a bug.

WDYT?

**Comment by howardjohn** [comment]
The field name didn't change, the serialization/deserialization might have. What is the validation error from?

**Comment by prabath** [comment]
This is my VirtualService.

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ecomm-virtual-service
spec:
  hosts:
  - "*"
  gateways:
  - ecomm-gateway.istio-system.svc.cluster.local
  tls:
    - match:
      - port: 443
        sni_hosts:
        - inventory.ecomm.com
      route:
      - destination:
          host: inventory-service
          port:
            number: 443
```
The validation error gets while applying the VirtualService definition.

```
\> k apply -f inventory.yaml

error: error validating "inventory.yaml": error validating data: ValidationError(VirtualService.spec.tls[0].match[0]): unknown field "sni_hosts" in io.istio.networking.v1alpha3.VirtualService.spec.tls.match; if you choose to ignore these errors, turn validation off with --validate=false
```

Thanks!
