### ISSUE TITLE
workloadSelector in ServiceEntry can not select pods

### ISSUE THREAD

**Issue by dozer47528** [istio/istio#25110]
**Bug description**

Base on the service entry document: https://istio.io/latest/docs/reference/config/networking/service-entry/
> In addition, the endpoints of a service entry can also be dynamically selected by using the workloadSelector field. These endpoints can be VM workloads declared using the WorkloadEntry object or Kubernetes pods.

But with my config, the service entry can't select the pods.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

ServiceEntry workloadSelector can select pods.

**Steps to reproduce the bug**

Apply this two resources.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: serviceentry-test
spec:
  hosts:
  - serviceentry.test.com
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: STATIC
  workloadSelector:
    labels:
      app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
```

Run 'istioctl dashboard envoy nginx-d46f5678b-9tz4c' -p 8080

Check the cluster and listens from this URL `http://localhost:8080/clusters`

I can not find and listens under this cluster:

```
outbound|80||serviceentry.test.com::default_priority::max_connections::4294967295
outbound|80||serviceentry.test.com::default_priority::max_pending_requests::4294967295
outbound|80||serviceentry.test.com::default_priority::max_requests::4294967295
outbound|80||serviceentry.test.com::default_priority::max_retries::4294967295
outbound|80||serviceentry.test.com::high_priority::max_connections::1024
outbound|80||serviceentry.test.com::high_priority::max_pending_requests::1024
outbound|80||serviceentry.test.com::high_priority::max_requests::1024
outbound|80||serviceentry.test.com::high_priority::max_retries::3
outbound|80||serviceentry.test.com::added_via_api::true
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

client version: 1.6.3
control plane version: 1.6.3
data plane version: 1.6.3 (5 proxies)

**How was Istio installed?**

```bash
istioctl operator init

kubectl create namespace istio-system

kubectl label namespace default istio-injection=enabled

kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: demo
EOF
```

**Environment where bug was observed (cloud vendor, OS, etc)**

minikube in Ubuntu 20.04

**Comment by stevenctl** [comment]
The docs do mention:

> Applicable only for MESH_INTERNAL services. Only one of endpoints or workloadSelector can be specified. Selects one or more Kubernetes pods or VM workloads (specified using WorkloadEntry) based on their labels. The WorkloadEntry object representing the VMs should be defined in the same namespace as the ServiceEntry.

Although I can replicate this in 1.6.5 even when setting location to `MESH_INTERNAL` on the service entry.

**Comment by stevenctl** [comment]
Creating a service with an arbitrary name that selects the same pods causes the serviceentry to start working as you'd expect

```yaml
apiVersion: v1
kind: Service
metadata:
  name: arbitrary
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: nginx
```

```
outbound|80||serviceentry.test.com::added_via_api::true
outbound|80||serviceentry.test.com::10.4.1.26:80::cx_active::0
...
```

**Comment by stevenctl** [comment]
Similar to https://github.com/istio/istio/issues/12957

**Comment by stevenctl** [comment]
After creating the Deployment and service entry:
```
$ istioctl proxy-config endpoint nginx-85ff79dd56-sdjsh | grep serviceentry 
# no results
```

After adding the service in the comment above things work fine:
```
$ kubectl apply -f svc.yaml
$ istioctl proxy-config endpoint nginx-85ff79dd56-sdjsh | grep serviceentry
10.4.0.232:80                    HEALTHY     OK                outbound|80||serviceentry.test.com
$ kubectl exec nginx-85ff79dd56-sdjsh curl serviceentry.test.com
<html>
...
```

Deleting the service results in another endpoint coming up without removing the first one. Traffic still works. 
```
$ kubectl delete svc arbitrary
$ istioctl proxy-config endpoint nginx-85ff79dd56-sdjsh | grep serviceentry
10.4.0.232:80                    HEALTHY     OK                outbound|80||serviceentry.test.com
127.0.0.1:80                     HEALTHY     OK                inbound|80|http|serviceentry.test.com
$ kubectl exec nginx-85ff79dd56-sdjsh curl serviceentry.test.com
<html>
```

After this, deleting/recreating the deployment and serviceentry keeps the first endpoint, but there is no connectivity
```
$ istioctl proxy-config endpoint nginx-85ff79dd56-6c9kc | grep serviceentry
10.4.0.232:80                    HEALTHY     OK                outbound|80||serviceentry.test.com
$ kubectl exec nginx-85ff79dd56-6c9kc curl serviceentry.test.com; echo
upstream connect error or disconnect/reset before headers. reset reason: connection failure
```

Repeating 1. delete/recreate deployment & serviceentry 2. create service causes more lingering endpoints
```
istioctl proxy-config endpoint nginx-85ff79dd56-fv499 | grep serviceentry
10.4.0.232:80                    HEALTHY     OK                outbound|80||serviceentry.test.com
10.4.2.229:80                    HEALTHY     OK                outbound|80||serviceentry.test.com
10.4.2.230:80                    HEALTHY     OK                outbound|80||serviceentry.test.com
```

**Comment by feuyeux** [comment]
I met the same issue using 1.6.4
And I created service/deployment/serviceentry/workloadentry, according to the official document, the logical chain is:
->sevice->serviceentry->(pod|vm).
But if service set the selector to the deployment, it cannot route to serviceentry, otherwise, the serviceentry can only locate to workloadentry, and cannot find/select the pod.
So, I think the right way to let it work is fix serviceentry to choose both pod and vm.

**Comment by iandyh** [comment]
Yes. I am also experiencing this issue in Istio 1.7.0

**Comment by stevenctl** [comment]
@dozer47528 I can't replicate the issue as originally described as of 1.7.0:

repro.yaml:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: serviceentry-test
spec:
  hosts:
  - serviceentry.test.com
  location: MESH_INTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: STATIC
  workloadSelector:
    labels:
      app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
```

reproduction:
```
$ istioctl install
...
$ kubectl apply -f repro.yaml
...
$ kubectl apply -f $ISTIO/samples/sleep/sleep.yaml
...
$ k exec -it sleep-8f795f47d-9zjwm -- curl serviceentry.test.com
Defaulting container name to sleep.
Use 'kubectl describe pod/sleep-8f795f47d-9zjwm -n default' to see all of the containers in this pod.
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
...
```

**Comment by stevenctl** [comment]
@feuyeux I can't replicate this as you're describing. Given the following yaml:

<details> 

<summary>repro.yaml</summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: serviceentry-test
spec:
  hosts:
  - f29b31bad30a552829d0cf5f03b07c07.m.pipedream.net
  location: MESH_INTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: STATIC
  workloadSelector:
    labels:
      app: nginx
---
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: we-nginx
spec:
    address: 54.210.116.43
    labels:
      app: nginx
      instance-id: vm1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
```

</details>

I can reach both the WorkloadEntry and the Pod, via either of the Service or ServiceEntry hosts.

```
~ ❯❯❯ istioctl proxy-config endpoints sleep-8f795f47d-6fhz9 | grep pipedream
10.244.0.15:80                   HEALTHY     OK                outbound|80||f29b31bad30a552829d0cf5f03b07c07.m.pipedream.net
54.210.116.43:80                 HEALTHY     OK                outbound|80||f29b31bad30a552829d0cf5f03b07c07.m.pipedream.net
~ ❯❯❯ istioctl proxy-config endpoints sleep-8f795f47d-6fhz9 | grep nginx
10.244.0.15:80                   HEALTHY     OK                outbound|80||nginx.default.svc.cluster.local
54.210.116.43:80                 HEALTHY     OK                outbound|80||nginx.default.svc.cluster.local
```

There are open issues regarding updates for existing ServiceEntry/WorkloadEntry: https://github.com/istio/istio/issues/27183  https://github.com/istio/istio/issues/27151 with a fix in progress: https://github.com/istio/istio/issues/27185. In my reproduction, I would restart istiod after each change to ensure proper config. Is it possible the bugs you've seen could be due to updates not being processed properly? 

Could provide detailed steps to reproduce?

**Comment by iandyh** [comment]
This becomes tricky. I had a similar setup in 1.7.0:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: multi-cluster-demo
  namespace: caas-sentinel
spec:
  hosts:
  - sample-app.global
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 80
    protocol: http
  resolution: STATIC
  workloadSelector:
    labels:
      app: sample-app
```

The workloads are in the same namespace
```
NAME                          READY   STATUS    RESTARTS   AGE
sample-app-59658795fb-h28fv   2/2     Running   0          6d
```

But I had no endpoints pushed into Envoy sidecar:

```
➜  multi-cluster-sd k exec -it curl-app-7f589d544d-46t5r -c istio-proxy -- curl localhost:15000/clusters | grep global
outbound|80||sample-app.global::default_priority::max_connections::4294967295
outbound|80||sample-app.global::default_priority::max_pending_requests::4294967295
outbound|80||sample-app.global::default_priority::max_requests::4294967295
outbound|80||sample-app.global::default_priority::max_retries::4294967295
outbound|80||sample-app.global::high_priority::max_connections::1024
outbound|80||sample-app.global::high_priority::max_pending_requests::1024
outbound|80||sample-app.global::high_priority::max_requests::1024
outbound|80||sample-app.global::high_priority::max_retries::3
outbound|80||sample-app.global::added_via_api::true
```
