### ISSUE TITLE
Error code=UNIMPLEMENTED while invoking a gRPC service via the Ingress Gateway over TLS

### ISSUE THREAD

**Issue by prabath** [istio/istio#25132]
I get the following error with Istio 1.6.3 on the default 443 port, always when the gRPC client outside the Kubernetes cluster, invoking a gRPC service over TLS.

Following is the Gateway configuration, which enables TLS, that does not work, and results in the error:
**WARNING: RPC failed: Status{code=UNIMPLEMENTED, description=Method not found: sample02.Inventory/UpdateInventory, cause=null}**

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ecomm-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      number: 443
      name: grpc
      protocol: https
    tls:
      mode: SIMPLE # enables HTTPS on this port
      credentialName: ecomm-credential
    hosts:
    - "gateway.ecomm.com"
```

Just by **disabling** the TLS at the Gateway, it works with a non-TLS gRPC client. Following is the **TLS disabled** Gateway configuration.

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ecomm-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      number: 443
      name: grpc
      protocol: http
    hosts:
    - "gateway.ecomm.com"
```

In both the cases (TLS and non-TLS), I verified that the request reaches the envoy proxy of the corresponding pod (gRPC service) - and prints the following log.

[2020-06-30T20:54:47.836Z] "POST /sample02.Inventory/UpdateInventory HTTP/2" 200 - "-" "-" 61 0 118 103 "192.168.65.3" "grpc-java-netty/1.20.0" "ee7ced2c-2b3f-906b-b5c3-7dc1920a313e" "gateway.ecomm.com:443" "127.0.0.1:50051" inbound|443|grpc|inventory-service.default.svc.cluster.local 127.0.0.1:57038 10.1.3.79:50051 192.168.65.3:0 outbound_.443_._.inventory-service.default.svc.cluster.local default

Appreciate any suggestions to fix this?
