### ISSUE TITLE
Grpc service cannot work cross multi-cluster

### ISSUE THREAD

**Issue by johnzheng1975** [istio/istio#25141]
**Bug description**
1  I set up multi-cluster per below:
https://archive.istio.io/v1.4/docs/setup/install/multicluster/gateways/
2  I set up service entry for normal service. I can access successfully with service1.myns.global
3  I set up service entry for grpc service, I cannot access successfully with service-grpc.myns.global

Can step 3 works? Or any examples for this? 
Thanks

**Comment by johnzheng1975** [comment]
Sorry, got it, using TCP protocol works.
```
kind: ServiceEntry
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1alpha3","kind":"ServiceEntry","metadata":{"annotations":{},"name":"se-test-core-directory","namespace":"default"},"spec":{"addresses":["240.0.0.120"],"endpoints":[{"address":"internal-ab5f1f9f898cd4255958e08e5c2ecbac-1326440145.us-east-1.elb.amazonaws.com","ports":{"http1":15443}}],"hosts":["directory.test-core.global"],"location":"MESH_INTERNAL","ports":[{"name":"http1","number":3000,"protocol":"tcp"}],"resolution":"DNS"}}
  generation: 1
  name: se-test-core-directory
  selfLink: /apis/networking.istio.io/v1alpha3/namespaces/default/serviceentries/se-test-core-directory
spec:
  addresses:
  - 240.0.0.120
  endpoints:
  - address: internal-ab5f1f9f898cd4255958e08e5c2ecbac-1326440145.us-east-1.elb.amazonaws.com
    ports:
      http1: 15443
  hosts:
  - directory.test-core.global
  location: MESH_INTERNAL
  ports:
  - name: http1
    number: 3000
    protocol: tcp
  resolution: DNS
```
