### ISSUE TITLE
Pod creation fails when name length exceeds 63 characters

### ISSUE THREAD

**Issue by bbenzikry** [istio/istio#25157]
**Bug description**
Pod creation fails when name length is above 63 characters due to ``service.istio.io/canonical-name`` label limitation.

**Expected behavior**
Pod name limits should adhere to k8s spec ( resource names up to 253 chars ) 

**Steps to reproduce the bug**
```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: xxxxxxxcxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  namespace: istioenablednamespace
  # annotations:
  # sidecar.istio.io/inject: "false"
spec:
  containers:
    - args: ["/bin/sh"]
      image: busybox:1.28
      imagePullPolicy: IfNotPresent
      name: containername
      stdin: true
      stdinOnce: true
      tty: true
  restartPolicy: Never
EOF
```

```
The Pod "xxxxxxxcxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" is invalid: metadata.labels: Invalid value: "xxxxxxxcxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx": must be no more than 63 characters
```

audit logs: 
```json
{"op":"add","path":"/metadata/labels/service.istio.io~1canonical-name","value":"xxxxxxxcxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

client version: 1.6.3
control plane version: 1.6.3
data plane version: 1.6.3

Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
istioctl/operator

**Environment where bug was observed (cloud vendor, OS, etc)**
EKS ( 1.16.8 )
