### ISSUE TITLE
Istio-operator is not installing Kiali with a custom prometheus instance

### ISSUE THREAD

**Issue by Shashankft9** [istio/istio#25174]
**Bug description**
I am trying to point Kiali to my own prometheus instance running in the monitoring namespace. For that I change my install config file as:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: default
  components:
    telemetry:
      enabled: false
  addonComponents:
    kiali:
      enabled: true
    grafana:
      enabled: false
    prometheus:
      enabled: false
    tracing:
      enabled: false
  values:
    kiali:
      prometheusAddr: http://prometheus-k8s.monitoring.svc.cluster.local:9090
```

But when the installation is done and I check the configmap of kiali in namespace `istio-system`, I still see that the url mentioned there points to `prometheus.istio-system:9090`.

Even when I run `istioctl manifest generate -f install.yaml > test.yaml` and I open the `test.yaml`, it shows this:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
    release: istio
data:
  config.yaml: |
    istio_component_namespaces:
      grafana: istio-system
      tracing: istio-system
      istiod: istio-system
      prometheus: istio-system
    istio_namespace: istio-system
    auth:
      strategy: login
    deployment:
      accessible_namespaces: ['**']
    login_token:
      signing_key: "xxxxxxxx"
    server:
      port: 20001
      web_root: /kiali
    external_services:
      istio:
        url_service_version: http://istiod.istio-system:15014/version
      tracing:
        url:
        in_cluster_url: http://tracing/jaeger
      grafana:
        url:
        in_cluster_url: http://grafana:3000
      prometheus:
        url: http://prometheus.istio-system:9090
```

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Expected behavior**
The configmap should be updated with the my own prometheus instance. 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio v1.6.3
kubernetes v1.15

**How was Istio installed?**
using: https://istio.io/latest/docs/setup/install/standalone-operator/

**Comment by JoeSainsburys** [comment]
I think that I've just ran in to this issue (or a similar one) where I can't reach Prometheus if it is in a non standard namespace. I've been going through the code starting in the /api/istio/status endpoint. 
I might be misunderstanding the code but it seems like it searches for deployments in the same namespace as istiod and doesn't pay any attention to PrometheusAddr or ExternalServices.Prometheus.URL. [See here](https://github.com/kiali/kiali/blob/f8b09ce62c02882900868bc015ff4216db545cd8/business/istio_status.go#L69). Sorry if this is a separate issue - I'm not sure how to check if Prometheus integration is actually working or not.

**Comment by Shashankft9** [comment]
This could be the root cause of why this is happening, good find! 
You can check the integration by the reproducible files that I have mentioned in the issue?

**Comment by Shashankft9** [comment]
@JoeSainsburys were you able to find a solution for this?

**Comment by JoeSainsburys** [comment]
No, but I think we are experiencing different problems. I get the little red warning in the top right saying kiali cant reach Prometheus, Jaeger etc but it actually can. So my solution was just to avoid looking at that area of the screen.

**Comment by Shashankft9** [comment]
@JoeSainsburys same thing for me as well actually. It works but this is perhaps a hacky way to point kiali to the prometheus or grafana instance (applying configmap and then restarting the pod). 

There is another way to install kiali - installing it through kiali operator which is much better than this manual intervention fix. I am gonna try that in some time if there is still no fix for this, you should also give this a shot. I think that little red dot will still be there though showing warnings, I think it looks for in-cluster instances thats why.

**Comment by xeor** [comment]
Did you find a solution? I'm unable to find a solution to this when using istioctl and profiles as well..

**Comment by Shashankft9** [comment]
@xeor  Nope, right now I edit the kiali configmap and restart the pod.

**Comment by xeor** [comment]
I just found out that if I use the istioOperator with istioctl install -f ..., I can do

```
  values:
    kiali:
      prometheusAddr: http://prometheus.istio-monitoring.svc.cluster.local:9090
```

**Comment by laurentiuspurba** [comment]
@Shashankft9 I just wanted to make sure I understand what you did.
So, basically, you edit kiali config map and update `url: http://prometheus.istio-system:9090` to `url:  http://prometheus-k8s.monitoring.svc.cluster.local:9090`, and then restart kiali pod(s) on `istio-system` namespace, right?

My situation is a little bit different, I used [K8sObjectOverlay](https://istio.io/v1.6/docs/reference/config/istio.operator.v1alpha1/#K8sObjectOverlay) in my IstioOperator.yaml file, and populated `prometheusAddr` with the url of my prometheus.

This is snippet of my IstioOperator.yaml
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  addonComponents:
    grafana:
      enabled: false
      k8s:
        replicaCount: 1
    istiocoredns:
      enabled: true
    kiali:
      enabled: true
      k8s:
        replicaCount: 2
        overlays:
          - kind: ConfigMap
            name: kiali
            patches:
              - path: data
                value: |
                  config.yaml: |
                      istio_component_namespaces:
                        grafana: istio-system
                        tracing: istio-system
                        istiod: istio-system
                        prometheus: istio-system
                      istio_namespace: istio-system
                      auth:
                        strategy: login
                      deployment:
                        accessible_namespaces: ['**']
                      login_token:
                        signing_key: "BOGUS123"
                      server:
                        port: 20001
                        web_root: /kiali
                      external_services:
                        istio:
                          url_service_version: http://istiod.istio-system:15014/version
                        tracing:
                          url:
                          in_cluster_url: http://tracing/jaeger
                        grafana:
                          url:
                          in_cluster_url: http://grafana:3000
                        prometheus:
                          url: http://prometheus-prometheus-oper-prometheus.prometheus.svc.cluster.local:9090/
```

and on the `values` stanza
```
kiali:
      contextPath: /kiali
      createDemoSecret: false
      prometheusAddr: http://prometheus-prometheus-oper-prometheus.prometheus.svc.cluster.local:9090/
      dashboard:
```

My kiali configmap is configured with the right prometheus url
```
▶ kubectl -n istio-system get configmap kiali -o yaml
apiVersion: v1
data:
  config.yaml: |
    istio_component_namespaces:
      grafana: istio-system
      tracing: istio-system
      istiod: istio-system
      prometheus: istio-system
    istio_namespace: istio-system
    auth:
      strategy: login
    deployment:
      accessible_namespaces: ['**']
    login_token:
      signing_key: "BOGUS123"
    server:
      port: 20001
      web_root: /kiali
    external_services:
      istio:
        url_service_version: http://istiod.istio-system:15014/version
      tracing:
        url:
        in_cluster_url: http://tracing/jaeger
      grafana:
        url:
        in_cluster_url: http://grafana:3000
      prometheus:
        url: http://prometheus-prometheus-oper-prometheus.prometheus.svc.cluster.local:9090/
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.yaml":"istio_component_namespaces:\n  grafana: istio-system\n  tracing: istio-system\n  istiod: istio-system\n  prometheus: istio-system\nistio_namespace: istio-system\nauth:\n  strategy: login\ndeployment:\n  accessible_namespaces: ['**']\nlogin_token:\n  signing_key: \"BOGUS123\"\nserver:\n  port: 20001\n  web_root: /kiali\nexternal_services:\n  istio:\n    url_service_version: http://istiod.istio-system:15014/version\n  tracing:\n    url:\n    in_cluster_url: http://tracing/jaeger\n  grafana:\n    url:\n    in_cluster_url: http://grafana:3000\n  prometheus:\n    url: http://prometheus-prometheus-oper-prometheus.prometheus.svc.cluster.local:9090/\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"kiali","release":"istio"},"name":"kiali","namespace":"istio-system"}}
  labels:
    app: kiali
    release: istio
  name: kiali
  namespace: istio-system

```

Any thoughts on this?
