### ISSUE TITLE
Webhook can't handle large EnvoyFilter inline_bytes

### ISSUE THREAD

**Issue by esnible** [istio/istio#25180]
To reproduce, apply the attached EnvoyFilter.  The message is

```
Error from server: error when creating "/tmp/add-header-filter.yaml": admission webhook "validation.istio.io" denied the request: cannot decode configuration: error converting YAML to JSON: yaml: control characters are not allowed
```

The YAML is valid according to `istioctl validate` and `kubectl apply --dry-run=client`.

The problem is not completely the webhook validation.  If the validatingwebhookconfiguration is deleted, Istiod will attempt to push the filter to httpbin's sidecar, which reports

```text
warning envoy config [external/envoy/source/common/config/grpc_subscription_impl.cc:101] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) virtualInbound: Failed to initialize WASM code from <inline>
```

(To see that second error deploy Istio's httpbin _sample_ and watch the sidecar logs.)

[add-header-filter.yaml.txt](https://github.com/istio/istio/files/4864847/add-header-filter.yaml.txt)

A smaller `inline_bytes` does not trigger the problem validation problem.  The problem is also not "control characters", because if the inline bytes are replaced with the output of `echo '\a' | base64` or `echo $'\x00' | base64` the validation is accepted.

The same bytes used here work when placed in a ConfigMap, mounted on the sidecar, and referred to in the EnvoyFilter by `filename`.

**Comment by esnible** [comment]
cc @rvennam This is what we talked about.  It should be possible to use WebAssembly without mounting anything, but I couldn't make it work.  On envoyproxy.slack.com, #envoy-wasm channel, Yaroslav from Tetrate.io agreed that inline_bytes can hold a WASM file.

**Comment by esnible** [comment]
The problem seems to be related to the sequence of bytes.  Here is an 8 character `inline_bytes` that fails, even though much larger ones succeed:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: httpbin
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              name: envoy.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: myfilter
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          value:
            config:
              configuration: world
              root_id: add_header
              vm_config:
                code:
                  local:
                    inline_bytes: !!binary |
                      AUkMYAJ/fwE=
                runtime: envoy.wasm.runtime.v8
                vm_id: myfilter
  workloadSelector:
    labels:
      app: httpbin
```

The byte sequence is `01  49  0c  60  02  7f  7f  01`.

**Comment by esnible** [comment]
Adding `policies and telemetry` because that working group knows more about EnvoyFilter and Web Assembly than Networking.

**Comment by kyessenov** [comment]
Inline bytes must follow proto JSON mapping, that is you need to base64 encode bytes in YAML.

**Comment by esnible** [comment]
> Inline bytes must follow proto JSON mapping, that is you need to base64 encode bytes in YAML.

They are base 64 encoded.  The short example I use has AUkMYAJ/fwE=.

```
echo AUkMYAJ/fwE= | base64 -D | od -tx1
0000000    01  49  0c  60  02  7f  7f  01                       
```

**Comment by mandarjog** [comment]
I am not sure how is !!binary being processed and by whom.
Though this should work, in practice we will never use it in the way.
You should use a local file load or a url fetch.

**Comment by esnible** [comment]
@mandarjog I had a request for a user to be able to apply WASM without mounts.

Feel free to set priority to P>2.  I may take a look to understand the problem more deeply after my 1.7 commitments are delivered.

I took an initial look earlier this week.  _pkg/webhooks/validation/server/server.go_ `admitPilot()` calls `github.com/ghodss/yaml.Unmarshal()` to convert the request from K8s into crd.IstioKind.  Eventually this conversion winds up in _gopkg.in/yaml.v2@v2.3.0/readerc.go_ which believes it is decoding UTF-16 input.  When it encounters a sequence that is illegal in a UTF-16 stream, it rejects it.

It is unclear if the problem is in how Kubernetes passes the JSON to the webhook, Istio not communicating the encoding to the JSON library, or the JSON libraries themselves being confused.

**Comment by rvennam** [comment]
Some context and reasoning for why we want WASM without mounts...users using Istio managed by a cloud provider who want to write a EnvoyFilter to target gateways do not have the ability to modify the Istio Gateway workload to mount files. A url fetch should also be okay.

**Comment by esnible** [comment]
The problem was a general problem with odd data because the webhook used ghodss yaml.Unmarshal to parse simple JSON.

For example, if I sent 
```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: details
spec:
  host: details
  subsets:
  - name: v1
    labels:
      version: !!binary |
        AUkMYAJ/fwE=
EOF
```

The system complained that "Error from server: error when creating "STDIN": admission webhook "validation.istio.io" denied the request: cannot decode configuration: error converting YAML to JSON: yaml: control characters are not allowed".  With this fix, it gives the message `* invalid tag value: "\x01I\f`\x02\u007f\u007f\x01"` which comes from our validator.

Our API is mostly simple strings, we really only need this support for `inline_bytes`.
