### ISSUE TITLE
How to support grpc requests (log metadata, read metadata, modify metadata) in envoyfilter. Thanks. 

### ISSUE THREAD

**Issue by johnzheng1975** [istio/istio#25193]
**Describe the feature request**
How to support grpc requests (log metadata, read metadata, modify metadata) in envoyfilter. 
In the envoyfilter
1  I need get each grpc request, get its metadata.
2  Make a call to get more info based on grpc request metadata.
3  Finally, add a new metadata in grpc request. 
4  Continue grpc request.

***Background*
I wrote envoyfilter in istio1.4.6 as below, it works for http request.
However, for grpc request, it cannot enter envoy_on_request at all.  
Is there any way to implement my requirements? Read/write grpc requests (log metadata, read metadata, modify metadata) in envoyfilter.  No matter you are using lua filter, or grpc-web filter, or others...

Please provide an example to me if it can be do.
Please tell me GA for my requirement, if it cannot be done so far.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: istio-multicluster-ingressgateway-tenant-id
  namespace: istio-system
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_OUTBOUND
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              name: envoy.router
        #portNumber: 3000
    patch:
      operation: INSERT_BEFORE
      value:
        config:
          inlineCode: |
            function envoy_on_request(request_handle)
              request_handle:logInfo("******* enter envoy_on_request : Set x-tenant-name by x-tenant-id")
              local headers = request_handle:headers()
              for key,value in pairs(headers) do request_handle:logInfo(key.." "..value) end
              request_handle:headers():replace("john","22222222222")

              request_handle:logInfo("----metadata")
              local metad = request_handle:metadata()
              local xid = metad:get("tenantID")
              request_handle:logInfo(xid)
              for keym,valuem in pairs(metad) do request_handle:logInfo(keym,valuem)  end
            end
        name: envoy.lua 

```

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[x] Developer Infrastructure

**Comment by rshriram** [comment]
does lua filter work for grpc?

**Comment by ramaraochavali** [comment]
Yes. It works for gRPC. Can you provide a config dump after inserting this filer?

**Comment by johnzheng1975** [comment]
@rshriram , @ramaraochavali , Thanks so much for your care.
Does that means the upper example I list is not using lua filter, although I wrote lua script? Otherwise, why grpc requests cannot enter into inline code (but http request can)?

Does that means I need use below format for lua filter?
```
name: envoy.filters.http.lua
typed_config:
  "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.lua
  inline_code: |
```
Appreciate your answer.

**Comment by ramaraochavali** [comment]
Yes. By just specifying inlineCode it does not know what is the filter type

**Comment by johnzheng1975** [comment]
@ramaraochavali , is this typed_config only support from istio1.5.x.

I am using 1.4.6, it raise error, thanks.

Error from server: error when creating "new_combine.yaml": admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: Envoy filter: unknown message type "envoy.config.filter.http.lua.v2.Lua"

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: istio-multicluster-ingressgateway-tenant-id
  namespace: istio-system
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_OUTBOUND
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              name: envoy.router
        #portNumber: 3000
    patch:
      operation: INSERT_BEFORE
      value: # lua filter specification
       name: envoy.lua
       typed_config:
         "@type": "type.googleapis.com/envoy.config.filter.http.lua.v2.Lua"
         inlineCode: |
           function envoy_on_request(request_handle)
             request_handle:logInfo("******* enter envoy_on_request : Set x-tenant-name by x-tenant-id")
             local headers = request_handle:headers()

             request_handle:logInfo("----metadata")
             local metad = request_handle:metadata()
             local xid = metad:get("tenantID")
             request_handle:logInfo(xid)
             for keym,valuem in pairs(metad) do request_handle:logInfo(keym,valuem)  end
           end
       name: envoy.lua
```

**Comment by ramaraochavali** [comment]
For 1.4, try with config not typed config

**Comment by johnzheng1975** [comment]
@ramaraochavali , for 1.4, as I said the top, it can catch http request, but not catch grpc request. That's why I raise this request.
Can you confirm istio1.4.6 lua filter cannot catch grpc request? Thanks
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: istio-multicluster-ingressgateway-tenant-id
  namespace: istio-system
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_OUTBOUND
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              name: envoy.router
        #portNumber: 3000
    patch:
      operation: INSERT_BEFORE
      value:
        config:
          inlineCode: |
            function envoy_on_request(request_handle)
              request_handle:logInfo("******* enter envoy_on_request : Set x-tenant-name by x-tenant-id")
              local headers = request_handle:headers()
              for key,value in pairs(headers) do request_handle:logInfo(key.." "..value) end
              request_handle:headers():replace("john","22222222222")

              request_handle:logInfo("----metadata")
              local metad = request_handle:metadata()
              local xid = metad:get("tenantID")
              request_handle:logInfo(xid)
              for keym,valuem in pairs(metad) do request_handle:logInfo(keym,valuem)  end
            end
        name: envoy.lua 
```

**Comment by ramaraochavali** [comment]
AFAIK, there is no difference in lua filter being invoked for gRPC in 1.4.x. Can you please share config dump after this filter is applied?

**Comment by johnzheng1975** [comment]
@ramaraochavali , oh, yes, it works in istio1.4.6. I am so sorry for confuse I bring.
The reason I was fail is: I am trying cross multi-cluster grpc, I set protocol to "tcp" in service entry. This makes envoyfilter cannot catch such requests.
Now I change protocal to "grpc", it works! Thanks a lot.
```
kind: ServiceEntry
metadata:
  name: se-test-core-hello
spec:
  addresses:
  - 240.0.0.106
  endpoints:
  - address: internal-ab5f1f9f898cd4255958e08e5c2ecbac-1326440145.us-east-1.elb.amazonaws.com
    ports:
      http1: 15443
  hosts:
  - testg.hpbp-dev-core.global
  location: MESH_INTERNAL
  ports:
  - name: http1
    number: 3000
    protocol: grpc
  resolution: DNS
```
