### ISSUE TITLE
For istio 1.5.7 `istioctl manifest generate` creates a yaml file that is not applicable on on a clean system

### ISSUE THREAD

**Issue by mhenke1** [istio/istio#25196]
**Bug description**
For istio 1.5.7  
`istioctl manifest generate` creates a yaml file that is not applicable on on a clean system
because namepaced objects are created before creating the namspace `istio-system`and 
`EnvoyFilter` CRs are created before the `envoyfilters.networking.istio.io` CRD is registered.

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
A yaml that applies correctly.

**Steps to reproduce the bug**

1) create the `istio-minimal-operator.yaml` config (taken from the [istio install documentation of knative](https://knative.dev/docs/install/installing-istio/)) 

```
cat << EOF > ./istio-minimal-operator.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      proxy:
        autoInject: disabled
      useMCP: false
      # The third-party-jwt is not enabled on all k8s.
      # See: https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens
      jwtPolicy: first-party-jwt

  addonComponents:
    pilot:
      enabled: true
    prometheus:
      enabled: false

  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
      - name: cluster-local-gateway
        enabled: true
        label:
          istio: cluster-local-gateway
          app: cluster-local-gateway
        k8s:
          service:
            type: ClusterIP
            ports:
            - port: 15020
              name: status-port
            - port: 80
              name: http2
            - port: 443
              name: https
EOF
```

2.) Generate the yaml file

```
istioctl manifest generate -f istio-minimal-operator.yaml > istio.yaml
```

3) Explore `istio.yaml` generated in step 2 (my version is attached below)

You will find that 6 namespaced `EnvoyFilter` CRs, starting on line 1608 of the generated file,  are located 
before the `envoyfilters.networking.istio.io` CRD  is created in line 5553 
and the namespace `istio-system` is created in line 8471

The `EnvoyFilter` CRs  are included a second time in the file, starting at line 10891, and could be removed.
I am not sure whether this is true for all namespaced objects located above the namespace.

My `istio.yaml`:
[istio.yaml.gz](https://github.com/istio/istio/files/4870065/istio.yaml.gz)

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
client version: 1.5.7

**How was Istio installed?**
No istio installed

**Environment where bug was observed (cloud vendor, OS, etc)**
macos targeting IBM Cloud Kubernetes
