### ISSUE TITLE
Allow multiple namespaces watch config for operator #24682 Does not Work

### ISSUE THREAD

**Issue by sb1975** [istio/istio#25208]
**Bug description**
iop cr does not work in any namesapce other than the istio-system.

It was clarified in the merge :   , the below should work but it does not.

```
# With this PR, this should work:
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: alpha-istiocontrolplane
  namespace: istio-system
spec:
  profile: demo
  values:
    revision: "alpha"
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: beta-istiocontrolplane
  namespace: NOT-istio-system
spec:
  profile: demo
  values:
    revision: "beta"
```

Even the simplified version of having the control plane in istio-system ns and a subset for just the ingress-gw in not-istio-system ns does not.

```
esudbat@kubernetes:~/istio-1.6.4$ cat demo.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: alpha-istiocontrolplane
  namespace: istio-system
spec:
  profile: demo
  values:
    revision: "alpha"
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: wk1-gwconfig
spec:
  profile: empty
  components:
    ingressGateways:
      - name: wk1-ingressgw
        namespace: not-istio-system
        enabled: true
        label:
          istio: ingressgateway-1
          app: istio-ingressgateway
        k8s:
          podAnnotations:
            ippools: workspace-ipv4-pool
  values:
    gateways:
      istio-ingressgateway:
        debug: error
esudbat@kubernetes:~/istio-1.6.4$
esudbat@kubernetes:~/istio-1.6.4$ kubectl apply -f demo.yaml
istiooperator.install.istio.io/alpha-istiocontrolplane unchanged
istiooperator.install.istio.io/wk1-gwconfig created
esudbat@kubernetes:~/istio-1.6.4$ kubectl get all -n not-istio-system
NAME                                 READY   STATUS    RESTARTS   AGE
pod/wk1-ingressgw-5b7684665b-vzwgj   0/1     Running   0          4m14s

NAME                    TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                                                      AGE
service/wk1-ingressgw   LoadBalancer   10.110.205.92   <pending>     15021:31816/TCP,80:30555/TCP,443:30000/TCP,15443:30938/TCP   4m13s

NAME                            READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/wk1-ingressgw   0/1     1            0           4m15s

NAME                                       DESIRED   CURRENT   READY   AGE
replicaset.apps/wk1-ingressgw-5b7684665b   1         1         0       4m15s

NAME                                                REFERENCE                  TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
horizontalpodautoscaler.autoscaling/wk1-ingressgw   Deployment/wk1-ingressgw   <unknown>/80%   1         5         1          4m14s
```

[x ] Configuration Infrastructure
[x ] Docs
[ x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ x] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

$ istioctl operator init

$ istioctl version
client version: 1.6.4
control plane version: 1.6.4
data plane version: 1.6.4 (3 proxies)
**Environment where bug was observed (cloud vendor, OS, etc)**
