### ISSUE TITLE
vitrualservice match even withoutHeaders is match，the route goes v3

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#25213]
**Bug description**
```
[root@master01 virtualservice]# cat vs-match-withoutHeaders.yaml 
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
  - reviews
  http:
  - match:
    - withoutHeaders:
        end-user:
          exact: mark
    route:
    - destination:
        host: reviews
        subset: v2
  - route:
    - destination:
        host: reviews
        subset: v3
```

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**
create the vs，the bookinfo demo,don't login ,so this will match withoutHeaders,but goes v3 route

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
[root@master01 tls]# istioctl version
client version: 1.6.1
control plane version: 1.6.1
data plane version: 1.6.1 (15 proxies)

···
[root@master01 tls]# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2020-05-12T09:28:18Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"linux/amd64"}
···

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
