### ISSUE TITLE
Variety of failures manifesting as 503UC and 0DPE

### ISSUE THREAD

**Issue by Stono** [istio/istio#25218]
**Bug description**
I don't even know where to start with this one... I have no idea what went wrong but I'm going to share what info I do have here in case it gets anyones attention because it was quite a significant failure which in the end was recovered by restarting the source workload (`nginx`).  

I know correlation != causation, but we've been stable on 1.5.0-1.5.6 for some time, and upgraded to 1.5.7 4 days ago.

Symptoms:
We started to see waves of request fail between two specific workloads on the cluster (all other workloads were fine).  The source workload being `nginx` and the destination workload being `consumer-gateway`.

<img width="1246" alt="Screenshot 2020-07-05 at 19 16 21" src="https://user-images.githubusercontent.com/1486729/86539459-5e343980-bef4-11ea-952b-c799290aa218.png">

The errors came in waves of decreasing duration, you can see the scatter plot from Jaeger here how you get a spike, they gradually fail faster before eventually recovering.

![image](https://user-images.githubusercontent.com/1486729/86539530-1f52b380-bef5-11ea-9155-f93930683df9.png)

The errors primarily manifested in two ways:

**1. 503UC from the source sidecar**
This represented the majority of errors recorded, a 503 was recorded from the source (`nginx`) sidecar.  There was no span recorded from the destination (`consumer-gateway`) leading me to believe the request was never even sent.

<img width="1680" alt="Screenshot 2020-07-05 at 18 47 57" src="https://user-images.githubusercontent.com/1486729/86539454-5379a480-bef4-11ea-8adb-7b4129e39be1.png">

**2. 0DPE**
There was also a fair few of these "Downstream Protocol Errors" recorded by the destination (`consumer-gateway`) sidecar.  These are interesting because it shows the request reached `consumer-gateway` 

<img width="1680" alt="Screenshot 2020-07-05 at 19 16 57" src="https://user-images.githubusercontent.com/1486729/86539485-9b98c700-bef4-11ea-93b2-42bd695aa92c.png">

So far I've checked the following:
 - There was nothing in pilot logs, nothing in the istio-proxy logs (although we run those in warn).  
 - There was no correlation from an infrastructure perspective (we observed failures across several nodes, across all zones).  The only correlation was the fact the issue was between just these two workloads.
  - We have rafts of network testing which indicated no issue.

Both workloads have been running for 4 days, since we upgraded to `1.5.7` (which is actually the only thing which has changed recently).

It's worth nothing we use both mTLS **and** http2 (via EnvoyFilter):
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: consumer-gateway
  namespace: consumer-gateway
spec:
  host: app
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 2147483646
        http2MaxRequests: 2147483646
        idleTimeout: 30m
        maxRequestsPerConnection: 2147483646
        maxRetries: 2147483646
      tcp:
        maxConnections: 2147483646
        tcpKeepalive:
          interval: 30s
          time: 30s
    loadBalancer:
      simple: RANDOM
    outlierDetection:
      baseEjectionTime: 2m
      consecutiveErrors: 2
      interval: 5s
      maxEjectionPercent: 50
      minHealthPercent: 50
    tls:
      mode: ISTIO_MUTUAL
```

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: h2-consumer-gateway
  namespace: istio-system
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      cluster:
        service: app.consumer-gateway.svc.cluster.local
      context: SIDECAR_OUTBOUND
    patch:
      operation: MERGE
      value:
        http2_protocol_options:
          max_concurrent_streams: 47707
```

However neither of these things have changed in way over 6 months 

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
Not to break :-)

**Steps to reproduce the bug**
I've not managed to reproduce this

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.5.7

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE 1.15

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
