### ISSUE TITLE
Istio 503 - Timeout issue on *.global calls

### ISSUE THREAD

**Issue by vipinlalvs** [istio/istio#25214]
**Bug description**
We are using [Istio Replicated control plane](https://istio.io/latest/docs/setup/install/multicluster/gateways/) for our micro services, which are deployed on different AKS. When we connect from one POD to POD deployed in other AKS cluster, application container throws **ThreadCancelledException** intermittent.
Flow of call is like follows.
**[ dotnet core app A ]** -> Sidecar Envoy Proxy -> ingress gateway of cluster 2 (PORT 15443) -> Sidecar Envoy Proxy -> **[ dotnet core app B]**.

We did a debug on the **dotnentcore app A POD** & got to know that whenever it throws ThreadCancelledException, it was like a long running call.  So we did a sniff and figured out that there were some re-transmission happens intermittent and that makes the call lengthy. 

**TCP dump** [tcp-dump.log](https://github.com/istio/istio/files/4874739/tcp-dump.log)
```
"No.","Time","Source","Destination","Protocol","Length","Info"
"320","16.158226","10.54.170.249","10.151.128.134","TLSv1.2","1219","Application Data"
"334","16.373529","10.54.170.249","10.151.128.134","TCP","1219","[TCP Retransmission] 51354  >  15443 [PSH, ACK] Seq=1 Ack=1 Win=4568 Len=1151 TSval=977998358 TSecr=2570071991"
"336","16.589516","10.54.170.249","10.151.128.134","TCP","1219","[TCP Retransmission] 51354  >  15443 [PSH, ACK] Seq=1 Ack=1 Win=4568 Len=1151 TSval=977998574 TSecr=2570071991"
"339","17.037538","10.54.170.249","10.151.128.134","TCP","1219","[TCP Retransmission] 51354  >  15443 [PSH, ACK] Seq=1 Ack=1 Win=4568 Len=1151 TSval=977999022 TSecr=2570071991"
"352","17.901550","10.54.170.249","10.151.128.134","TCP","1219","[TCP Retransmission] 51354  >  15443 [PSH, ACK] Seq=1 Ack=1 Win=4568 Len=1151 TSval=977999886 TSecr=2570071991"
"383","19.629509","10.54.170.249","10.151.128.134","TCP","1219","[TCP Retransmission] 51354  >  15443 [PSH, ACK] Seq=1 Ack=1 Win=4568 Len=1151 TSval=978001614 TSecr=2570071991"
"446","23.149534","10.54.170.249","10.151.128.134","TCP","1219","[TCP Retransmission] 51354  >  15443 [PSH, ACK] Seq=1 Ack=1 Win=4568 Len=1151 TSval=978005134 TSecr=2570071991"
"587","30.061503","10.54.170.249","10.151.128.134","TCP","1219","[TCP Retransmission] 51354  >  15443 [PSH, ACK] Seq=1 Ack=1 Win=4568 Len=1151 TSval=978012046 TSecr=2570071991"
"833","43.889542","10.54.170.249","10.151.128.134","TCP","1219","[TCP Retransmission] 51354  >  15443 [PSH, ACK] Seq=1 Ack=1 Win=4568 Len=1151 TSval=978025874 TSecr=2570071991"
"1345","71.277497","10.54.170.249","10.151.128.134","TCP","1219","[TCP Retransmission] 51354  >  15443 [PSH, ACK] Seq=1 Ack=1 Win=4568 Len=1151 TSval=978053262 TSecr=2570071991"
"2088","116.065048","10.54.170.249","10.151.128.134","TLSv1.2","99","Encrypted Alert"
```

**Service entry**

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: bwo-storage-tomdatasvc-dev2-se
  namespace: istio-system
spec:
  hosts:
  - hrblock-ocap-tax-data-storage-reader.taxprepflow-capabilities-dev2.global
  location: MESH_INTERNAL
  ports:
  - name: http1
    number: 80
    protocol: http
  resolution: DNS
  addresses:
  - 240.0.0.2
  endpoints:
  - address: ocap-platform-services-dev2.example.com
    ports:
      http1: 15443
```

It happens intermittently & most of the other times global calls returns in less than 100ms.
@howardjohn 

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[X] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
It should return 200.

**Steps to reproduce the bug**
1. Install [Istio Replicated control plane](https://istio.io/latest/docs/setup/install/multicluster/gateways/) 
2. Create one application which connects to another using service entry.
3. Try to hit multi cluster pod (B) from pod (A). POD A - throws DC time out exception intermittently. 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

AKS 1 - Istio 1.4.3
AKS 2 - Istio 1.4.2

**How was Istio installed?**
Helm.

**Environment where bug was observed (cloud vendor, OS, etc)**
AKS.
