### ISSUE TITLE
[upgrade by operator from 1.5.1 to 1.5.4] istiod rbac problem: clusterrole is binding a wrong service-account

### ISSUE THREAD

**Issue by pixystone** [istio/istio#25235]
**Bug description**

```
$ kubectl get pod -n istio-system
NAME                                    READY   STATUS    RESTARTS   AGE
istio-citadel-787c4f9ff7-vb7c4          1/1     Running   0          23d
istio-ingressgateway-6f4564fff9-xmp2c   0/1     Running   0          4h1m
istio-ingressgateway-755bff46bb-sn7hp   1/1     Running   0          73d
istio-tracing-d497b9c9b-kkv4c           1/1     Running   0          73d
istiod-68459f8cf7-g6xf2                 1/1     Running   0          23d
istiod-947f49958-nzrpl                  0/1     Running   0          4h3m
kiali-6bc5c6f578-czrd5                  1/1     Running   0          73d
prometheus-597c595499-8xvzh             1/2     Running   0          23d
prometheus-7d99cfd4fb-hn767             2/2     Running   0          73d
```

```
$ kubectl logs istiod-947f49958-nzrpl

2020-07-06T06:28:11.798816Z     error   k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1beta1.MutatingWebhookConfiguration: mutatingwebhookconfigurations.admissionregistration.k8s.io "istio-sidecar-injector" is forbidden: User "system:serviceaccount:istio-system:istiod-service-account"cannot list resource "mutatingwebhookconfigurations" in API group "admissionregistration.k8s.io" at the cluster scope
```

the clusterrolebinding config: 

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: pilot
    operator.istio.io/component: Pilot
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.5.4
    release: istio
  name: istio-pilot-istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-pilot-istio-system
subjects:
- kind: ServiceAccount
  name: istio-pilot-service-account
  namespace: istio-system
```

no `istiod-service-account` binding in subjects

I added `istiod-service-account` to this clusterrolebinding and fixed it:

```
subjects:
- kind: ServiceAccount
  name: istio-pilot-service-account
  namespace: istio-system
- kind: ServiceAccount
  name: istiod-service-account   # <--- the missing one
  namespace: istio-system
```

```
$ kubectl get pod -n istio-system
NAME                                    READY   STATUS        RESTARTS   AGE
istio-citadel-787c4f9ff7-vb7c4          1/1     Running       0          23d
istio-ingressgateway-6f4564fff9-xmp2c   0/1     Running       0          4h14m
istio-ingressgateway-755bff46bb-sn7hp   1/1     Running       0          73d
istio-tracing-d497b9c9b-kkv4c           1/1     Running       0          73d
istiod-68459f8cf7-g6xf2                 1/1     Terminating   0          23d
istiod-947f49958-nzrpl                  1/1     Running       0          4h15m
kiali-6bc5c6f578-czrd5                  1/1     Running       0          73d
prometheus-597c595499-8xvzh             1/2     Running       0          23d
prometheus-7d99cfd4fb-hn767             2/2     Running       0          73d
```

[ ] Configuration Infrastructure
[ ] Docs
[ x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
