### ISSUE TITLE
virtualservice http redirect service unavailable

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#25232]
**Bug description**
```
[root@master01 virtualservice]# vi vs-http-redirect.yaml 
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ratings
spec:
  hosts:
  - ratings
  http:
  - match:
    - uri:
        prefix: /ratings
    redirect:
      uri: /ratings/1
      authority: new-ratings.istio.svc.cluster.local:9080
  - route:
    - destination:
        host: new-ratings
```
```
[root@master01 virtualservice]# kubectl get svc -n istio
NAME          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)     AGE
details       ClusterIP   10.68.193.9     <none>        9080/TCP    4d
mongodb       ClusterIP   10.68.76.222    <none>        27017/TCP   3d19h
mysqldb       ClusterIP   10.68.7.37      <none>        3306/TCP    3d18h
new-ratings   ClusterIP   10.68.89.222    <none>        9080/TCP    77m
productpage   ClusterIP   10.68.213.193   <none>        9080/TCP    4d
ratings       ClusterIP   10.68.40.57     <none>        9080/TCP    4d
reviews       ClusterIP   10.68.5.93      <none>        9080/TCP    4d
```
```
An extremely entertaining play by Shakespeare. The slapstick humour is refreshing!

Reviewer1
Ratings service is currently unavailable
```

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
