### ISSUE TITLE
Istio install with updated configs doesn't delete Prometheus ServiceMonitor objects

### ISSUE THREAD

**Issue by sameerbhadouria** [istio/istio#25231]
**Bug description**

I have Istio configured with an external Prometheus and I have the Prometheus ServiceMonitor objects configured using the built in Prometheus operator based on the discussion in this issue: https://github.com/istio/istio/issues/21187

For most part this works fine, except that I noticed that the `kubernetes-services-secure-monitor` and the `kubernetes-pods-secure-monitor` were also created and this resulted in Prometheus throwing certificate not found errors, as expected because I have not set these up.

```
"level=error ts=2020-07-06T03:43:33.464Z caller=manager.go:188 component="scrape manager" msg="error creating new scrape pool" err="error creating HTTP client: unable to load specified CA cert /etc/prometheus/secrets/istio.prometheus/root-cert.pem: open /etc/prometheus/secrets/istio.prometheus/root-cert.pem: no such file or directory" scrape_pool=istio-system/kubernetes-pods-secure-monitor/0
```

I also noticed that the service monitor creation can be disabled by using the `Values.prometheus.provisionPrometheusCert` flag as per this: https://github.com/istio/istio/blob/a671e62bd1ca3e6fd09bd0fbe03545c136b0f3f5/manifests/charts/istio-telemetry/prometheusOperator/templates/servicemonitors.yaml#L119

However, re-applying the config using `istioctl install did not delete those service monitors. 

Does `istioctl install` command not delete/prune existing resources? 

Here is my configuration:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioControlPlane
metadata:
  namespace: istio-system
  name: istio-controlplane
  labels:
    istio-injection: enabled
spec:
  profile: default
  addonComponents:
    prometheus:
      enabled: false
    prometheusOperator:
      enabled: true
    grafana:
      enabled: false
    kiali:
      enabled: true
      namespace: staging
    tracing:
      enabled: false
  values:
    global:
      proxy:
        logLevel: warning
      mountMtlsCerts: false
      prometheusNamespace: monitoring
      tracer:
        zipkin:
          address: jaeger-collector.staging:9411

    prometheusOperator:
      createPrometheusResource: false

    prometheus:
      security:
        enabled: false
      provisionPrometheusCert: false
```

[x ] Configuration Infrastructure
[ ] Docs
[x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
The existing ServiceMonitor resource that were disabled should have been deleted

**Steps to reproduce the bug**
1. Setup Istio to use external Prometheus
2. Enable service monitor resource creation using the Prometheus Operator. 
  ```
  prometheusOperator:
      enabled: true
  values:
    prometheusOperator:
      createPrometheusResource: false
  ```
3. Check creation of ServiceMonitors: `kubectl get servicemonitors.monitoring.coreos.com --namespace=istio-system`
This should display something like this:
```
NAME                                 AGE
envoy-stats-monitor                  4d5h
istio-component-monitor              4d5h
istio-mesh-monitor                   4d5h
kubelet                              4d5h
kubernetes-pods-monitor              4d5h
kubernetes-pods-secure-monitor       4d5h
kubernetes-services-monitor          4d5h
kubernetes-services-secure-monitor   4d5h
```
4. Disable Cert provision: 
```
prometheus:
      security:
        enabled: false
      provisionPrometheusCert: false
```
Check output of `kubectl get servicemonitors.monitoring.coreos.com --namespace=istio-system` again.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
-- istioctl version
client version: 1.6.3
control plane version: 1.6.3
data plane version: 1.6.3 (16 proxies)

-- kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.9-gke.6", GitCommit:"14bc8ad5f8c245f1240a8e4eab128c4d51bfeffe", GitTreeState:"clean", BuildDate:"2020-05-30T02:07:03Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}

-- helm version
Client: &version.Version{SemVer:"v2.16.7", GitCommit:"5f2584fd3d35552c4af26036f0c464191287986b", GitTreeState:"clean"}

**How was Istio installed?**
Manually downloading the release
wget https://github.com/istio/istio/releases/download/1.6.3/istio-1.6.3-linux-amd64.tar.gz

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by WarpRat** [comment]
We noticed the same thing, although we only changed this:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  addonComponents:
    prometheus:
      enabled: true -> false
      k8s:
        replicaCount: 1
```
I would have expected this to clean up the prometheus server that was created in the initial install, but it does not. Is this expected? If so, is there a declarative way to install Istio? I didn't expected it to make a difference, but I tested this by calling the install directly from istioctl as well as having istioctl generate manifests and pass them to kubectl and both methods failed to remove the prometheus resources.
