### ISSUE TITLE
virtualservice tls config ,404response

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#25233]
**Bug description**
```
[root@master01 tls]# cat vs-tls-product.yaml 
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: bookinfo
spec:
  exportTo:
  - '*'
  gateways:
  - bookinfo-gateway
  hosts:
  - '*'
  tls:
  - match:
    - port: 443
      sniHosts:
      - bookinfo.demo
    route:
    - destination:
        host: productpage.istio.svc.cluster.local
        port:
          number: 9080
  - match:
    - port: 443
      sniHosts:
      - ratings.demo
    route:
    - destination:
        host: ratings.istio.svc.cluster.local
        port:
          number: 9080
```
```
[root@master01 tls]# cat ../../gateway/gateway-tls.yaml 
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bookinfo-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: httpS
      protocol: HTTPS
    hosts:
    - "bookinfo.demo"
    - "ratings.demo"
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
```
找不到 bookinfo.demo 的网页找不到与以下网址对应的网页：https://bookinfo.demo/productpage
HTTP ERROR 404

```
[2020-07-06T06:00:37.556Z] "GET /productpage HTTP/2" 404 - "-" "-" 0 0 0 - "172.20.1.0" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36" "bea0a92d-118a-9345-af02-c19d0517441c" "bookinfo.demo" "-" - - 172.20.0.177:8443 172.20.1.0:53650 bookinfo.demo default
172.20.0.177:8443[2020-07-06T06:03:00.221Z] "GET /ratings/1 HTTP/2" 404 - "-" "-" 0 0 0 - "172.20.1.0" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36" "ae86b383-efb9-9356-a348-cfa6c8f92320" "ratings.demo" "-" - - 172.20.0.177:8443 172.20.1.0:53724 ratings.demo default
[2020-07-06T06:03:02.681Z] "GET /productpage HTTP/2" 404 - "-" "-" 0 0 0 - "172.20.1.0" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36" "5d1443e3-743c-91b3-83c2-c4f6cc28cc2c" "bookinfo.demo" "-" - - 172.20.0.177:8443 172.20.1.0:53650 bookinfo.demo default
[2020-07-06T06:03:19.310Z] "GET /productpage HTTP/2" 404 - "-" "-" 0 0 0 - "172.20.1.0" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36" "d1c90880-aa0a-91cb-8ad8-6f2f2373d50f" "bookinfo.demo" "-" - - 172.20.0.177:8443 172.20.1.0:53650 bookinfo.demo default
```

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by GregHanson** [comment]
What is the output of `istioctl proxy status`, is there anything marked STALE?  

What is your `istioctl version`?  Depending on the version those secrets may no longer be present on istio ingress gateway unless specifically mounted.
```
$ kubectl exec -n istio-system "$(kubectl get pod -l istio=ingressgateway -n istio-system -o jsonpath='{.items[0].metadata.name}')" -- ls -al /etc/istio/ingressgateway-certs/tls.crt
ls: cannot access '/etc/istio/ingressgateway-certs/tls.crt': No such file or directory
command terminated with exit cod
```
Is the 404 access log from your ingress gateway?

**Comment by 13567436138** [comment]
```
[root@master01 ~]# istioctl proxy-status
NAME                                                   CDS        LDS        EDS        RDS          PILOT                           VERSION
details-v1-78db589446-vg6z2.istio                      SYNCED     SYNCED     SYNCED     SYNCED       istio-pilot-b96cbf8c9-9nlmw     1.4.10
details-v2-74dc577dd9-wmlp8.istio                      SYNCED     SYNCED     SYNCED     SYNCED       istio-pilot-b96cbf8c9-9nlmw     1.4.10
istio-egressgateway-68d9cccb64-hw7lv.istio-system      SYNCED     SYNCED     SYNCED     NOT SENT     istio-pilot-b96cbf8c9-9nlmw     1.4.10
istio-ingressgateway-5b57f4f788-gx7h9.istio-system     SYNCED     SYNCED     SYNCED     SYNCED       istio-pilot-b96cbf8c9-9nlmw     1.4.10
mongodb-v1-7f5d579b68-v8cw2.istio                      SYNCED     SYNCED     SYNCED     SYNCED       istio-pilot-b96cbf8c9-9nlmw     1.4.10
productpage-v1-c7c4989cb-lxf7z.istio                   SYNCED     SYNCED     SYNCED     SYNCED       istio-pilot-b96cbf8c9-9nlmw     1.4.10
ratings-v1-756b788d54-vr8c9.istio                      SYNCED     SYNCED     SYNCED     SYNCED       istio-pilot-b96cbf8c9-9nlmw     1.4.10
ratings-v2-689868d94f-9prcw.istio                      SYNCED     SYNCED     SYNCED     SYNCED       istio-pilot-b96cbf8c9-9nlmw     1.4.10
ratings-v2-mysql-7b95dd484-bk78n.istio                 SYNCED     SYNCED     SYNCED     SYNCED       istio-pilot-b96cbf8c9-9nlmw     1.4.10
reviews-v1-66558f876f-pq9wb.istio                      SYNCED     SYNCED     SYNCED     SYNCED       istio-pilot-b96cbf8c9-9nlmw     1.4.10
reviews-v2-8d6fdf549-g92qh.istio                       SYNCED     SYNCED     SYNCED     SYNCED       istio-pilot-b96cbf8c9-9nlmw     1.4.10
reviews-v3-69fc8bc477-zrkkt.istio                      SYNCED     SYNCED     SYNCED     SYNCED       istio-pilot-b96cbf8c9-9nlmw     1.4.10
```
```
[root@master01 ~]# istioctl version
client version: 1.4.10
control plane version: 1.4.10
data plane version: 1.4.10 (12 proxies)
```
```
[root@master01 ~]# kubectl exec -n istio-system "$(kubectl get pod -l istio=ingressgateway -n istio-system -o jsonpath='{.items[0].metadata.name}')" -- ls -al /etc/istio/ingressgateway-certs/tls.crt
lrwxrwxrwx 1 root root 14 Jul 18 04:29 /etc/istio/ingressgateway-certs/tls.crt -> ..data/tls.crt
```

**Comment by 13567436138** [comment]
```
[root@master01 virtualservice]# cat vs-bookinfo.yaml 
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - "bookinfo.com"
  gateways:
  - bookinfo-gateway
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: 9080
        subset: v1
```
when gateway using ssl,virtualservice using http,it is success.vs using tls,404
