### ISSUE TITLE
Customizing Istio Metrics via envoyFilters not working for istio 1.5.6

### ISSUE THREAD

**Issue by Madan-Lal** [istio/istio#25245]
**Bug description**
As per Istio [documentation](https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/)  customisation of istio metrics is possible. However, following the guide for istio 1.5.6 does not bring that new entry in metrics.
Is this documentation not compatible for istio 1.5.6?

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behaviour**
Prometheus should have `destination_port` & `request_host` in `istio_requests_total` metrics as described in the documentation above.

**Steps to reproduce the bug**
Deploy istio 1.5.6, with following configuration
```
  components:
    telemetry:
      enabled: false
  global:
    telemetry:
      enabled: true
      v1:
        enabled: false
      v2:
        enabled: true
```
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
client version: 1.5.6
control plane version: 1.5.6
```
**How was Istio installed?**
Using istioctl

Additionally, envoy proxy container logs do not have the new values in the metrics
