### ISSUE TITLE
Support for nginx-ingress based rewrite in Istio VirtualService for sub-path routing

### ISSUE THREAD

**Issue by MeghanaSrinath** [istio/istio#25246]
Is there a way in Istio where the subpaths accessed by the application can be specified using a wildcard entry? For ex, in [nginx-ingress,](https://kubernetes.github.io/ingress-nginx/examples/rewrite/#rewrite-target) this sub route rewrite is handled by mentioning the path as  `path: /something(/|$)(.*)`
For instance, we have configured the below VirtualService which rewrites `https://IP/weave` to `https://IP/`. 
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sample-vs
spec:
  hosts:
    - "*"
  gateways:
    - istio-system/mastergateway
  http:
    - match:
        - uri:
            prefix: /weave
      rewrite:
        uri: "/"
      route:
        - destination:
            host: weave.default.svc.cluster.local
            port:
              number: 80
```

The app further calls others APIs to render the dashboards, few css files etc. These APIs run at `/topology `or `/api`,  etc paths. We might not be having the knowledge of the sub-paths that many of these apps use as well. In this case, is there a way in which any wildcards can be specified here(similar to nginx ingress) so that we do not have to worry on the app specific routing and Istio can handle the rest of the sub paths? This would be helpful and be easier to put any of the open source or custom tools behind Istio, since this is relatively easier to achieve with [nginx-ingress](https://kubernetes.github.io/ingress-nginx/examples/rewrite/#rewrite-target).
