### ISSUE TITLE
400 Bad Request with Export to '.' with istio ingress

### ISSUE THREAD

**Issue by ceastman-ibm** [istio/istio#25253]
**Bug description**
When opening a browser and going to a virtual service path defined as: /testpath/overview we get the following error from the browser:

400 Bad Request
The plain HTTP request was sent to HTTPS port
nginx

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Web page renders correctly 

**Steps to reproduce the bug**
Define destination rules and service entries with "Export to '.' "

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.5.4

**How was Istio installed?**
IBM - Managed istio

**Environment where bug was observed (cloud vendor, OS, etc)**
IBM

[gateway.yaml.zip](https://github.com/istio/istio/files/4880798/gateway.yaml.zip)
[redacted-host-DR.cloud.ibm.com.yaml.zip](https://github.com/istio/istio/files/4880800/redacted-host-DR.cloud.ibm.com.yaml.zip)
[redacted-host-SE.cloud.ibm.com.yaml.zip](https://github.com/istio/istio/files/4880802/redacted-host-SE.cloud.ibm.com.yaml.zip)
[redacted-host-virtual-service.yaml.zip](https://github.com/istio/istio/files/4880803/redacted-host-virtual-service.yaml.zip)

**Comment by linsun** [comment]
@ceastman-ibm can you update the desp with yaml formatted properly?

**Comment by howardjohn** [comment]
Easy reproducer:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: httpbin.org
  namespace: istio-system
spec:
  exportTo:
    - "."
  host: httpbin.org
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: httpbin.org
  namespace: istio-system
spec:
  exportTo:
    - "."
  hosts:
    - httpbin.org
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ondeck-virtual-service
  namespace: istio-system
spec:
  hosts:
    - "ingress.httpbin.local"
  gateways:
    - gateway
  http:
    - match:
        - uri:
            prefix: /testpath/
      rewrite:
        authority: httpbin.org
        uri: /
      route:
        - destination:
            host: httpbin.org
            port:
              number: 443

```
