### ISSUE TITLE
Endpoints port error when remove any endpoints in ServiceEntry

### ISSUE THREAD

**Issue by dozer47528** [istio/istio#25309]
**Bug description**

I created a ServiceEntry which includes some endpoints, the cluster port, and endpoints port is different.
When I try to remove some endpoints in the ServiceEntry, the port of the endpoint generated to Envoy is wrong.

[x] Networking

**Expected behavior**

The port should be correct.

**Steps to reproduce the bug**

1. Create a ServiceEntry
```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: httpbin
  namespace : default
spec:
  hosts:
  - httpbin.com
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: STATIC
  endpoints:
  - address: 2.2.2.2
    ports:
      http: 8080
  - address: 3.3.3.3
    ports:
      http: 8080
```

2. check the envoy clster API: `http://pod-ip:57361/clusters`

```
outbound|80||httpbin.com::default_priority::max_connections::4294967295
outbound|80||httpbin.com::default_priority::max_pending_requests::4294967295
outbound|80||httpbin.com::default_priority::max_requests::4294967295
outbound|80||httpbin.com::default_priority::max_retries::4294967295
outbound|80||httpbin.com::high_priority::max_connections::1024
outbound|80||httpbin.com::high_priority::max_pending_requests::1024
outbound|80||httpbin.com::high_priority::max_requests::1024
outbound|80||httpbin.com::high_priority::max_retries::3
outbound|80||httpbin.com::added_via_api::true
outbound|80||httpbin.com::2.2.2.2:8080::cx_active::0
outbound|80||httpbin.com::2.2.2.2:8080::cx_connect_fail::0
outbound|80||httpbin.com::2.2.2.2:8080::cx_total::0
outbound|80||httpbin.com::2.2.2.2:8080::rq_active::0
outbound|80||httpbin.com::2.2.2.2:8080::rq_error::0
outbound|80||httpbin.com::2.2.2.2:8080::rq_success::0
outbound|80||httpbin.com::2.2.2.2:8080::rq_timeout::0
outbound|80||httpbin.com::2.2.2.2:8080::rq_total::0
outbound|80||httpbin.com::2.2.2.2:8080::hostname::
outbound|80||httpbin.com::2.2.2.2:8080::health_flags::healthy
outbound|80||httpbin.com::2.2.2.2:8080::weight::1
outbound|80||httpbin.com::2.2.2.2:8080::region::
outbound|80||httpbin.com::2.2.2.2:8080::zone::
outbound|80||httpbin.com::2.2.2.2:8080::sub_zone::
outbound|80||httpbin.com::2.2.2.2:8080::canary::false
outbound|80||httpbin.com::2.2.2.2:8080::priority::0
outbound|80||httpbin.com::2.2.2.2:8080::success_rate::-1.0
outbound|80||httpbin.com::2.2.2.2:8080::local_origin_success_rate::-1.0
outbound|80||httpbin.com::3.3.3.3:8080::cx_active::0
outbound|80||httpbin.com::3.3.3.3:8080::cx_connect_fail::0
outbound|80||httpbin.com::3.3.3.3:8080::cx_total::0
outbound|80||httpbin.com::3.3.3.3:8080::rq_active::0
outbound|80||httpbin.com::3.3.3.3:8080::rq_error::0
outbound|80||httpbin.com::3.3.3.3:8080::rq_success::0
outbound|80||httpbin.com::3.3.3.3:8080::rq_timeout::0
outbound|80||httpbin.com::3.3.3.3:8080::rq_total::0
outbound|80||httpbin.com::3.3.3.3:8080::hostname::
outbound|80||httpbin.com::3.3.3.3:8080::health_flags::healthy
outbound|80||httpbin.com::3.3.3.3:8080::weight::1
outbound|80||httpbin.com::3.3.3.3:8080::region::
outbound|80||httpbin.com::3.3.3.3:8080::zone::
outbound|80||httpbin.com::3.3.3.3:8080::sub_zone::
outbound|80||httpbin.com::3.3.3.3:8080::canary::false
outbound|80||httpbin.com::3.3.3.3:8080::priority::0
outbound|80||httpbin.com::3.3.3.3:8080::success_rate::-1.0
outbound|80||httpbin.com::3.3.3.3:8080::local_origin_success_rate::-1.0
```
The port is correct.

3. Remove one endpoint
```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: httpbin
  namespace : default
spec:
  hosts:
  - httpbin.com
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: STATIC
  endpoints:
  - address: 2.2.2.2
    ports:
      http: 8080
```

4. check the cluster API again:

```
outbound|80||httpbin.com::default_priority::max_connections::4294967295
outbound|80||httpbin.com::default_priority::max_pending_requests::4294967295
outbound|80||httpbin.com::default_priority::max_requests::4294967295
outbound|80||httpbin.com::default_priority::max_retries::4294967295
outbound|80||httpbin.com::high_priority::max_connections::1024
outbound|80||httpbin.com::high_priority::max_pending_requests::1024
outbound|80||httpbin.com::high_priority::max_requests::1024
outbound|80||httpbin.com::high_priority::max_retries::3
outbound|80||httpbin.com::added_via_api::true
outbound|80||httpbin.com::2.2.2.2:80::cx_active::0
outbound|80||httpbin.com::2.2.2.2:80::cx_connect_fail::0
outbound|80||httpbin.com::2.2.2.2:80::cx_total::0
outbound|80||httpbin.com::2.2.2.2:80::rq_active::0
outbound|80||httpbin.com::2.2.2.2:80::rq_error::0
outbound|80||httpbin.com::2.2.2.2:80::rq_success::0
outbound|80||httpbin.com::2.2.2.2:80::rq_timeout::0
outbound|80||httpbin.com::2.2.2.2:80::rq_total::0
outbound|80||httpbin.com::2.2.2.2:80::hostname::
outbound|80||httpbin.com::2.2.2.2:80::health_flags::healthy
outbound|80||httpbin.com::2.2.2.2:80::weight::1
outbound|80||httpbin.com::2.2.2.2:80::region::
outbound|80||httpbin.com::2.2.2.2:80::zone::
outbound|80||httpbin.com::2.2.2.2:80::sub_zone::
outbound|80||httpbin.com::2.2.2.2:80::canary::false
outbound|80||httpbin.com::2.2.2.2:80::priority::0
outbound|80||httpbin.com::2.2.2.2:80::success_rate::-1.0
outbound|80||httpbin.com::2.2.2.2:80::local_origin_success_rate::-1.0
```

the port of endpoint is wrong, it should be `8080` instead of `80`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
client version: 1.6.4
control plane version: 1.6.4
data plane version: 1.6.4 (2 proxies)
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-27T00:38:11Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
```sh
istioctl operator init

kubectl create namespace istio-system

kubectl label namespace default istio-injection=enabled

kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-default
spec:
  profile: default
  addonComponents:
    prometheus:
      enabled: false
  values:
    global:
      proxy:
        logLevel: debug
EOF
```

**Environment where bug was observed (cloud vendor, OS, etc)**

minikube
