### ISSUE TITLE
IngressClass declared instead of 'kubernetes.io/ingress.class' annotation doesn't configure Ingress status

### ISSUE THREAD

**Issue by vugardzhamalov** [istio/istio#25308]
**Bug description**
I am trying to deploy 'Ingress' object with 'ingressClassName: istio' flag enabled instead of `kubernetes.io/ingress.class: istio` annotation as per [this](https://istio.io/latest/docs/tasks/traffic-management/ingress/kubernetes-ingress/#specifying-ingressclass) example in Istio traffic management documentation.

I am simply trying to reproduce this on my Minikube Cluster, but 'Ingress' object without annotation just won't work as expected. While it works with annotation - it doesn't work with 'ingressClassName: istio' flag.

Strangely enough if I happen to deploy Minikube's Ingress addon - it actually starts working -  but it doesn't go via Istion Ingress Gateway anymore - I am not sure if this is expected.  

[ ] Configuration Infrastructure
[X ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X ] User Experience
[X ] Developer Infrastructure

**Expected behavior**
Running things on Minikube, Kubernetes version is 1.18.3 I was under impression that switching from `kubernetes.io/ingress.class: istio `annotation in favour of `ingressClassName: istio` flag won't result in any changes in terms of 'Ingress' objects not working without additional Ingress Controllers deployed. But it seems like it just won't pick-up Istio ingress controller at all... not sure if this is expected maybe I am missing the point.

**Steps to reproduce the bug**
1. Create Istio IngressClass object

  ```
apiVersion: networking.k8s.io/v1beta1
  kind: IngressClass
  metadata:
    name: istio
  spec:
    controller: istio.io/ingress-controller
```

2. Create Ingress object

  ```
apiVersion: networking.k8s.io/v1beta1
  kind: Ingress

  metadata:
    name: 'ingress-hnb'
    namespace: 'istio-ingress-lab'

  spec:
    ingressClassName: istio

    rules:
      - host: 'fancy.example.com'
        http:
          paths:
            - path: '/*'
              backend:
                serviceName: 'fancy-service'
                servicePort: 9999
```

3. Apply Ingress object configuration and describe it - one should see following (if minikube Ingress addon(aka kubernetes ingress controller)) has been deployed):

kubectl describe --namespace=istio-ingress-lab ingresses.networking.k8s.io ingress-hnb

```
Annotations:               Events:
  Type                     Reason  Age    From                      Message
  ----                     ------  ----   ----                      -------
  Normal                   CREATE  3m43s  nginx-ingress-controller  Ingress istio-ingress-lab/ingress-hnb
  Normal                   UPDATE  3m12s  nginx-ingress-controller  Ingress istio-ingress-lab/ingress-hnb

```

As you can see FROM is set to 'nginx-ingress-controller' I am not sure if this is correct...

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

bin/istioctl version --remote
```
client version: 1.6.4
control plane version: 1.6.4
data plane version: 1.6.4 (1 proxies)
```

kubectl version
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
`bin/istioctl manifest apply --set profile=default --set addonComponents.prometheus.enabled=false`

**Environment where bug was observed (cloud vendor, OS, etc)**
minikube version
```
minikube version: v1.11.0
commit: 57e2f55f47effe9ce396cea42a1e0eb4f611ebbd
```
