### ISSUE TITLE
what guarantees prometheus scraping from multiple mixer ?

### ISSUE THREAD

**Issue by kidiyoor** [istio/istio#2531]
Looking at the configuration of prometheus its not clear on how prometheus scrapping guarantee no data loss from mixer in case of multiple mixer.

Currently prometheus scrape from multiple mixer based on IP returned(load balanced) by kube dns ?  

Prometheus might loose data from few mixer instance if operator screws up the scrap time interval ? 

```
global:
  scrape_interval: 15s
scrape_configs:

- job_name: 'istio-mesh'
  # Override the global default and scrape targets from this job every 5 seconds.
  scrape_interval: 5s
  # metrics_path defaults to '/metrics'
  # scheme defaults to 'http'.
  static_configs:
  - targets: ['istio-mixer.istio-system:42422']

- job_name: 'envoy'
  # Override the global default and scrape targets from this job every 5 seconds.
  scrape_interval: 5s
  # metrics_path defaults to '/metrics'
  # scheme defaults to 'http'.
  static_configs:
  - targets: ['istio-mixer.istio-system:9102']

- job_name: 'mixer'
  # Override the global default and scrape targets from this job every 5 seconds.
  scrape_interval: 5s
  # metrics_path defaults to '/metrics'
  # scheme defaults to 'http'.
  static_configs:
  - targets: ['istio-mixer.istio-system:9093']
```
