### ISSUE TITLE
add sidecar resource, egress did not specify Istio namespace, but the workload in Istio namespace still can invoke outside workload

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#25347]
**Bug description**

```
[root@master01 sidecar]# cat sidecar-bookinfo-egress.yaml
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
spec:
  workloadSelector:
    labels:
      app: productpage
  ingress:
  - port: 
      number: 9080
      protocol: http
    defaultEndpoint: 127.0.0.1:9080
  egress:
  - port:
      number: 9080
      protocol: HTTP
      name: egresshttp
    hosts:
    - "xxx/*"
  - hosts:
    - "istio-system/*"
```
my deployed namespace is istio,egress didn't specifiy istio namespace,but productpage workload still can visite details and reviews,why

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
[root@master01 sidecar]# istioctl version
client version: 1.6.1
control plane version: 1.6.1
data plane version: 1.6.1 (14 proxies)
```
```
[root@master01 sidecar]# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2020-05-12T09:28:18Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
