### ISSUE TITLE
Please could we add `name` as a field on HTTPRouteDestination

### ISSUE THREAD

**Issue by Stono** [istio/istio#25415]
**Describe the feature request**
We currently use a `name` field on the [HTTPRouteDestination](https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRouteDestination) object to differentiate our routes, for example:

```
  spec:
    hosts:
    - solr
    http:
    - name: default
      retries:
        attempts: 3
        retryOn: connect-failure,refused-stream,unavailable,cancelled,resource-exhausted,retriable-status-codes
      route:
      - destination:
          host: solr
        name: default
        weight: 100
      - destination:
          host: solr.search-solr.bcp.k8.atcloud.io
          port:
            number: 8080
        name: bcp
        weight: 0
      timeout: 20s
```

This allows us to build GUI's which allow people to switch traffic to other regions, and we use that field to deterministically identify the relevant route.

![Screenshot 2020-07-10 at 10 12 42](https://user-images.githubusercontent.com/1486729/87138151-e8cebd00-c295-11ea-81ca-d3371a7ffa85.png)

This is because lookup the bcp route by `name===bcp`

However name isn't actually a valid field, and in `1.5.8` and `1.6.5` `istioctl validate` (ironically at [my request](https://github.com/istio/istio/issues/24860)) now validates that there aren't any additional fields, and we use `istioctl validate` in our pipelines in order to validate the manifests that are generated before deploy time.

**Describe alternatives you've considered**
I thought about this quite a bit, and other ways I could tackle the problem, but actually I feel `name` is a good field to add to a HTTPRouteDestination in the same way that it is present on [HttpRoute](https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRoute)

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[x] Developer Infrastructure

**Additional context**
This is actually going to prevent us from making further upgrades to istio, so we would either need agreement on the istio side or we will need to go away and find a new way to handle this in our applications.

If this gets the go-ahead it's be great if it can be back ported to 1.5.7, as we can't go to 1.5.8 due to the istioctl validate change (and that also contains a security fix!)
