### ISSUE TITLE
How to disable image of istio/proxyv2:1.6.3 keep pulling when deployment istio enabled

### ISSUE THREAD

**Issue by hillbun** [istio/istio#25412]
I have installed istio offline, all istio images load locally

```
istio/proxyv2                                        1.6.3               1613fdc0b66b        3 weeks ago         304MB
istio/pilot                                          1.6.3               5979ad1c6607        3 weeks ago         237MB
grafana/grafana                                      6.7.4               be4c69a1aae8        5 weeks ago         233MB
prom/prometheus                                      v2.15.1             61bf337f2956        6 months ago        133MB
jaegertracing/all-in-one                             1.16                fea586ade9d0        6 months ago        50.5MB
```
but when deployment deployed and startup, pods keeps pulling istio/proxyv2:1.6.3

how to solve this problem?

**Comment by howardjohn** [comment]
I don't understand the issue - why do you expect istio/proxyv2 to not be pulled? It is a required image for the proxy

**Comment by hillbun** [comment]
@howardjohn 

My server do not have internet connection, so I have to install istio offline.

I have load all required images to local copy.

```
istio/proxyv2                                        1.6.3               1613fdc0b66b        3 weeks ago         304MB
istio/pilot                                          1.6.3               5979ad1c6607        3 weeks ago         237MB
grafana/grafana                                      6.7.4               be4c69a1aae8        5 weeks ago         233MB
prom/prometheus                                      v2.15.1             61bf337f2956        6 months ago        133MB
jaegertracing/all-in-one                             1.16                fea586ade9d0        6 months ago        50.5MB
```

I installed istio with kubectl apply method and set all image imagePullPolicy: IfNotPresent

istio is running correctly

```
[root@vm-0001 ~]# kubectl get pods -n istio-system -o wide
NAME                                    READY   STATUS    RESTARTS   AGE   IP            NODE                NOMINATED NODE   READINESS GATES
grafana-b54bb57b9-cb96w                 1/1     Running   0          44h   10.244.0.5    vm-0001.novalocal   <none>           <none>
istio-ingressgateway-766c84dfdc-bdlxc   1/1     Running   0          44h   10.244.0.8    vm-0001.novalocal   <none>           <none>
istio-tracing-9dd6c4f7c-wvq8r           1/1     Running   0          44h   10.244.0.4    vm-0001.novalocal   <none>           <none>
istiod-56dddc5db8-m6qq2                 1/1     Running   0          44h   10.244.0.7    vm-0001.novalocal   <none>           <none>
kiali-d45468dc4-7zn6m                   1/1     Running   0          44h   10.244.0.6    vm-0001.novalocal   <none>           <none>
prometheus-565d67bf69-xq5tz             2/2     Running   0          43h   10.244.0.11   vm-0001.novalocal   <none>           <none>
```

But when I deploy pods with istio enabled, it still keep pulling istio/proxyv2, and cranched.

**Comment by howardjohn** [comment]
Ok then it sounds like either image pull policy is NOT IfNotPresent or it's a k8s bug (less likely).Maybe look at the full pod yaml

**Comment by hillbun** [comment]
@howardjohn 

deployment.yaml 


```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test
  name: miop-ui
spec:
  selector:
    matchLabels:
      app: miop-ui
      version: zhongshan
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: miop-ui
        version: zhongshan
    spec:
      containers:
      - name: miop-ui
        image: xxx.xxxx.com/xxxxxx/miop_ui:zhongshan
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

```

kubectl get pods -n test -o wide

```
NAME                       READY   STATUS     RESTARTS   AGE     IP       NODE                NOMINATED NODE   READINESS GATES
miop-ui-5897df69d4-d8ppx   0/2     Init:0/1   0          2m44s   <none>   vm-0001.novalocal   <none>           <none>
miop-ui-5897df69d4-tfj7t   0/2     Init:0/1   0          2m45s   <none>   vm-0001.novalocal   <none>           <none>
```

kubectl describe pods miop-ui-5897df69d4-d8ppx -n test 

```
Events:
  Type    Reason     Age        From                        Message
  ----    ------     ----       ----                        -------
  Normal  Scheduled  <unknown>  default-scheduler           Successfully assigned test/miop-ui-5897df69d4-d8ppx to vm-0001.novalocal
  Normal  Pulling    3m52s      kubelet, vm-0001.novalocal  Pulling image "docker.io/istio/proxyv2:1.6.3"

```

but proxyv2:1.6.3 is local copied.

```
docker images -a |grep proxyv2
istio/proxyv2                                           1.6.3               1613fdc0b66b        3 weeks ago         304MB


```

maybe is imagePullPolicy: always is hard coded in istio for image proxyv2:1.6.3 enjected？
