### ISSUE TITLE
Support mTLS for Grpc

### ISSUE THREAD

**Issue by hunkeelin** [istio/istio#25437]
The below config works for mtls on https REST. 
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-foo
  namespace: api
spec:
  selector:
    istio: istio-foo
  servers:
    - port:
        number: 9001
        name: http-ingress
        protocol: https
      hosts:
          - "*"
      tls:
        mode: MUTUAL
        serverCertificate: /etc/istio/istio-foo-ingressgateway-certs/tls.crt
        privateKey: /etc/istio/istio-foo-ingressgateway-certs/tls.key
        caCertificates: /etc/istio/istio-foo-ca-certs/myCA.pem
```

If I change the protocol to `grpc`, `apply` will complain `cannot have TLS settings for plain text HTTP ports`. If I change the protocol to `https`/`tls` istio-gateway silently drops grpc request. 

Base on my observation it seems istio gateway doesn't support grpc with mtls. If it doesn't this issue serve as a feature request. If it does, please let me know what the correct config is.

**Comment by hunkeelin** [comment]
After some research; it seems it's not standard to expose grpc to public. So this feature request is not in high priority. It is strongest suggest to expose rest + mtls, exposing grpc to public go against CS philosophy where server should accept anything. If one really need grpc+envoy filter one could write an envoy filter. E.G
https://github.com/tetratelabs/istio-tools/tree/master/grpc-transcoder

**Comment by zufardhiyaulhaq** [comment]
@hunkeelin I am testing gRPC without mutual TLS (just plain gRPC) and its working via the gateway.

**Comment by hunkeelin** [comment]
grpc without mtls is working. but grpc + mtls is not supported in `istio`

**Comment by johnzheng1975** [comment]
How you test grpc? Can you provide examples? 
https://github.com/envoyproxy/envoy/issues/12127

**Comment by hunkeelin** [comment]
> How you test grpc? Can you provide examples?
> My issue is similar: [envoyproxy/envoy#12127](https://github.com/envoyproxy/envoy/issues/12127)

I tested without mtls. If you want mtls you will have to write your own envoy filter or do the transcoding yourself.

**Comment by parviz-93** [comment]
@hunkeelin, I correctly understood that there will be the same issue with http2 +  mtls via the gateway?

**Comment by ramaraochavali** [comment]
Based on the current implementation the behaviour is as expected i.e. gRPC is considered plain text protocol and we can not have TLS settings for plain text protocols. If you want TLS, you should specify the port protocol as `HTTPS` which you mentioned it works - May be we should enhance the docs.

@howardjohn WDYT? Am I missing any thing here?

**Comment by howardjohn** [comment]
Agreed

**Comment by mipnw** [comment]
@ramaraochavali, @hunkeelin: what would be the drawbacks of using port protocol `https`, along with a `tls` section, in the specification for a `gateway`, if the clients actually send gRPC requests? 

Would the requests still be routed to a destination given a `virtualservice` or would they fail at the gateway?

**Comment by hunkeelin** [comment]
> @ramaraochavali, @hunkeelin: what would be the drawbacks of using port protocol `https`, along with a `tls` section, in the specification for a `gateway`, if the clients actually send gRPC requests?
> 
> Would the requests still be routed to a destination given a `virtualservice` or would they fail at the gateway?

it will silently fail.

**Comment by mipnw** [comment]
@hunkeelin: Thanks, I'm glad I asked! 

I need to do gRPC + mTLS through an Istio ingress. You've suggested https://github.com/tetratelabs/istio-tools/tree/master/grpc-transcoder. Is this something you tried, was that a lot of work?

**Comment by mipnw** [comment]
@ramaraochavali @hunkeelin 
Couldn't an external gRPC client go through an istio gateway by setting [tlsMode=PASSTHROUGH](https://istio.io/latest/docs/reference/config/networking/gateway/#ServerTLSSettings-TLSmode) and a [protocol=tls](https://istio.io/latest/docs/reference/config/networking/gateway/#Port)? That should "tell" the ingress, this is binary, don't try an look at the data as though it was HTTP, no?

**Comment by pc-rshetty** [comment]
@howardjohn is this problem only for the gateway or any service to service grpc with mtls wont work ?
I am planning to start using grpc since we have move whole production to kubernetes + isito on mtls

**Comment by hunkeelin** [comment]
> @howardjohn is this problem only for the gateway or any service to service grpc with mtls wont work ?
> I am planning to start using grpc since we have move whole production to kubernetes + isito on mtls

The thing about istio is this. The engineer behind them strongly believe grpc is for internal use only. For internal calls istio have mtls on by default so we good but when we expose it out in istio-gateway mtls is not supported; the solution is to simply use rest instead.

**Comment by mipnw** [comment]
@hunkeelin @pc-rshetty 

I'm using mTLS for gRPC between an external client and a kubernetes service via an Istio gateway. It works but I had to make that opaque to Istio, meaning I opened a port on the ingressgateway, configured for TLS PASSTHROUGH, and configured the port on the Kubernetes service for TCP. Basically nowhere in the configuration does it say HTTP. HTTPS or GPRC.

**Comment by pc-rshetty** [comment]
Cool @hunkeelin and @mipnw

**Comment by pc-rshetty** [comment]
Also curious if folks on java using any spring libraries for gRPC

**Comment by howardjohn** [comment]
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: echo
  namespace: default
spec:
  gateways:
  - echo
  hosts:
  - '*'
  http:
  - route:
    - destination:
        host: echo
        port:
          number: 9090
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: echo
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
  - hosts:
    - '*'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: sds-credential
      mode: SIMPLE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: gcr.io/istio-testing/app:latest
        args:
        - --tcp=7070
        - --tcp=7071
        - --port=8080
        - --grpc=9090
        - --port=8443
        - --tls=8443
        - --server-first=7071
        - --crt=/cert.crt
        - --key=/cert.key
---
apiVersion: v1
kind: Service
metadata:
  name: echo
spec:
  selector:
    app: echo
  ports:
  - name: http
    port: 8080
  - name: https
    port: 8443
  - name: tcp
    port: 7070
  - name: tcp-sf
    port: 7071
  - name: grpc
    port: 9090
```

Then `$ grpcurl --insecure <ingress-ip>:443 proto.EchoTestService/Echo`

this works for me. For those having issues, please post your GW/VS configs and config dump from gw: https://github.com/istio/istio/wiki/Troubleshooting-Istio
