### ISSUE TITLE
"RequestAuthentication" doesnt get applied to ingressgateway in istio 1.6.2

### ISSUE THREAD

**Issue by r-kotagudem** [istio/istio#25449]
@itsmurugappan
"RequestAuthentication" doesnt get applied to ingressgateway in istio 1.6.2. Same policy works when applied to service pod with side car enabled.

```
apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: "jwt-example"
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
  - issuer: "https://authserver.com:443/oauth2"
    jwksUri: "http://authserver.com/oauth2/rest/security"

apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: "jwt-example"
  namespace: default
spec:
  selector:
    matchLabels:
      app: bookinfo
  jwtRules:
  - issuer: "https://authserver.com:443/oauth2"
    jwksUri: "http://authserver.com/oauth2/rest/security"
```

[ ] Security

**Expected behavior**
RequestAuthentication when applied to ingressgateway wont validate the  jwt token.
Same apolicy when applied to service pod with side car works fine. validate jwt token.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio 1.6.2

**How was Istio installed?**
istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
