### ISSUE TITLE
Egress TLS Origination for TCP using VirtualService does not work if ServiceEntry is not DNS

### ISSUE THREAD

**Issue by juanamat** [istio/istio#25450]
Istio 1.5.5

I followed the step for Egress TLS Origination from the doc but using TCP instead.
I really needed a VirtualService to map my non secure port used in my application to the secure port use to contact the external TCP service (think LDAP:389/LDAPS:636).
If I use a ServiceEntry with resolution:NONE  like this:
```
 apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: my-service-entry
spec:
  hosts:
  - my.host
  addresses:
  - IP/32
  ports:
  - number: PORT
    name: tcp
    protocol: TCP
  - number: PORT_SECURE
    name: tcp-secure
    protocol: TCP
  location: MESH_EXTERNAL
  resolution: NONE
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-virtual-service
spec:
  hosts:
  - my.host
  tcp:
  - match:
    - port: PORT
    route:
    - destination:
        host: my.host
        subset: tls-origination
        port:
          number: PORT_SECURE
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: my-destination-rule
spec:
  host: my.host
  subsets:
  - name: tls-origination
    trafficPolicy:
      portLevelSettings:
      - port:
          number: PORT_SECURE
        tls:
          mode: SIMPLE
```

This does not work.
More precisely the traffic will be upgraded from non secure to secure, but the outgoing traffic will still use PORT and not PORT_SECURE.

Now if I created a dns entry for 'my.host' and modify the ServiceEntry to use 'resolution: DNS', then it works fine.

It should work correctly in both case.
