### ISSUE TITLE
Operator Helm Chart is published within Helm Hub / Artifact Hub

### ISSUE THREAD

**Issue by desaintmartin** [istio/istio#25467]
**Describe the feature request**

It would be nice if Operator Helm Chart would be published somewhere like the Helm Hub or the Artifact Hub in order to ease installation/search.

https://hub.helm.sh/
https://artifacthub.io/

Note that I volunteer to do it for the Helm Hub if needed and accepted. 

**Describe alternatives you've considered**

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by JuanSeBestia** [comment]
Please!

Also, I tried to install it with HelmOperator with git option like this
``` yaml
# istio-operator-release
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: istio-operator
spec:
  releaseName: istio-operator
  forceUpgrade: false
  chart:
    git: https://github.com/istio/istio.git
    ref: 1.7.4
    path: manifests/charts/istio-operator
```

but your repo wight 706MB, it is too much!

It doesn’t work :(
