### ISSUE TITLE
test infra: false positives in tests

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#25463]
All tests are passing, regardless of status. See https://prow.k8s.io/view/gcs/istio-prow/logs/integ-k8s-116_istio_postsubmit/2878 for example

I will temporarily block all PRs until resolved

**Comment by howardjohn** [comment]
I have opened https://github.com/istio/test-infra/pull/2772 to temporarily disable ALL merging until we figure this out

**Comment by howardjohn** [comment]
A pod that failed has

```
  - containerID: containerd://de7e28f6ae73ca2bad6b0f4820a9a0919ab9937ae6ace46068bc17358d743398
    image: gcr.io/istio-testing/build-tools:master-2020-07-10T02-22-20
    imageID: gcr.io/istio-testing/build-tools@sha256:34116eb1e9a7a742b8c96e15b29f14162e95f7bbe7d39d1fcac9ae645fd2d3c5
    lastState: {}
    name: test
    ready: false
    restartCount: 0
    state:
      terminated:
        containerID: containerd://de7e28f6ae73ca2bad6b0f4820a9a0919ab9937ae6ace46068bc17358d743398
        exitCode: 0
        finishedAt: "2020-07-13T14:42:37Z"
        reason: Completed
        startedAt: "2020-07-13T14:13:29Z"
```

in the status. So it may be returning the exit code == 0, indicating its an issue on our side not prow

**Comment by howardjohn** [comment]
First know false positive is https://github.com/istio/istio/pull/25384

**Comment by howardjohn** [comment]
Testing locally with a dummy job that jsut runs `exit 5`, confirm exit code is set appropriately:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: build-tools
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: build-tools
    spec:
      containers:
      - name: build-tools
        image: gcr.io/istio-testing/build-tools:master-2020-05-31T23-50-32
        command:
          - entrypoint
          - sh
          - -c
          - exit 5
        resources:
          requests:
            cpu: 1000m
            memory: 1000M
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
          readOnly: true
        - mountPath: /var/lib/docker
          name: docker-root
      volumes:
      - hostPath:
          path: /lib/modules
          type: Directory
        name: modules
      - hostPath:
          path: /sys/fs/cgroup
          type: Directory
        name: cgroup
      - name: docker-root
```

```
$ kgp -oyaml | rg exitCode
          exitCode: 5
          exitCode: 5
```

Need to see if its related to our kind setup/cleanup

**Comment by howardjohn** [comment]
Merging is blocked, in theory at least

**Comment by howardjohn** [comment]
Running `prow/integ-suite-kind.sh --skip-build fail`, where fail is a target in make I defined for `exit 5`, fails appropriate locally

**Comment by howardjohn** [comment]
Another job which *does* fail properly:

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    prow.k8s.io/job: integ-k8s-116_istio_postsubmit
    testgrid-alert-email: istio-oncall@googlegroups.com
    testgrid-dashboards: istio_istio_postsubmit
    testgrid-num-failures-to-alert: "1"
  labels:
    created-by-prow: "true"
    event-GUID: e7a6f99a-c512-11ea-949b-848296245337
    prow.k8s.io/build-id: "2881"
    prow.k8s.io/id: ed34f524-c512-11ea-a5ad-9a0b20faf5f7
    prow.k8s.io/job: integ-k8s-116_istio_postsubmit
    prow.k8s.io/refs.org: istio
    prow.k8s.io/refs.repo: istio
    prow.k8s.io/type: postsubmit
  name: ed34f524-c512-11ea-a5ad-9a0b20faf5f7
  namespace: prow
spec:
  automountServiceAccountToken: false
  containers:
  - command:
    - /tools/entrypoint
    env:
    - name: INTEGRATION_TEST_FLAGS
      value: ' --istio.test.retries=1 '
    - name: BUILD_WITH_CONTAINER
      value: "0"
    - name: ARTIFACTS
      value: /logs/artifacts
    - name: BUILD_ID
      value: "2881"
    - name: BUILD_NUMBER
      value: "2881"
    - name: CI
      value: "true"
    - name: GOPATH
      value: /home/prow/go
    - name: JOB_NAME
      value: integ-k8s-116_istio_postsubmit
    - name: JOB_SPEC
      value: '{"type":"postsubmit","job":"integ-k8s-116_istio_postsubmit","buildid":"2881","prowjobid":"ed34f524-c512-11ea-a5ad-9a0b20faf5f7","refs":{"org":"istio","repo":"istio","base_ref":"master","base_sha":"a736986dd3b7523300a9bc611d991c586266aa11","base_link":"https://github.com/istio/istio/compare/18179f10c07e...a736986dd3b7","path_alias":"istio.io/istio"}}'
    - name: JOB_TYPE
      value: postsubmit
    - name: PROW_JOB_ID
      value: ed34f524-c512-11ea-a5ad-9a0b20faf5f7
    - name: PULL_BASE_REF
      value: master
    - name: PULL_BASE_SHA
      value: a736986dd3b7523300a9bc611d991c586266aa11
    - name: PULL_REFS
      value: master:a736986dd3b7523300a9bc611d991c586266aa11
    - name: REPO_NAME
      value: istio
    - name: REPO_OWNER
      value: istio
    - name: ENTRYPOINT_OPTIONS
      value: '{"timeout":14400000000000,"grace_period":15000000000,"artifact_dir":"/logs/artifacts","args":["entrypoint","prow/integ-suite-kind.sh","fake-target"],"process_log":"/logs/process-log.txt","marker_file":"/logs/marker-file.txt","metadata_file":"/logs/artifacts/metadata.json"}'
    image: gcr.io/istio-testing/build-tools:master-2020-07-10T02-22-20
    imagePullPolicy: IfNotPresent
    name: test
    resources:
      limits:
        memory: 24Gi
      requests:
        cpu: "5"
        memory: 3Gi
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /lib/modules
      name: modules
      readOnly: true
    - mountPath: /sys/fs/cgroup
      name: cgroup
      readOnly: true
    - mountPath: /var/lib/docker
      name: docker-root
    - mountPath: /logs
      name: logs
    - mountPath: /tools
      name: tools
    - mountPath: /home/prow/go
      name: code
    workingDir: /home/prow/go/src/istio.io/istio
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - command:
    - /clonerefs
    env:
    - name: CLONEREFS_OPTIONS
      value: '{"src_root":"/home/prow/go","log":"/logs/clone.json","git_user_name":"ci-robot","git_user_email":"ci-robot@k8s.io","refs":[{"org":"istio","repo":"istio","base_ref":"master","base_sha":"a736986dd3b7523300a9bc611d991c586266aa11","base_link":"https://github.com/istio/istio/compare/18179f10c07e...a736986dd3b7","path_alias":"istio.io/istio"}]}'
    image: gcr.io/k8s-prow/clonerefs:v20200708-1254fdd37f
    imagePullPolicy: IfNotPresent
    name: clonerefs
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /logs
      name: logs
    - mountPath: /home/prow/go
      name: code
    - mountPath: /tmp
      name: clonerefs-tmp
  - args:
    - /entrypoint
    - /tools/entrypoint
    command:
    - /bin/cp
    image: gcr.io/k8s-prow/entrypoint:v20200708-1254fdd37f
    imagePullPolicy: IfNotPresent
    name: place-entrypoint
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /tools
      name: tools
  terminationGracePeriodSeconds: 15
  volumes:
  - hostPath:
      path: /lib/modules
      type: Directory
    name: modules
  - hostPath:
      path: /sys/fs/cgroup
      type: Directory
    name: cgroup
  - emptyDir: {}
    name: docker-root
  - emptyDir: {}
    name: logs
  - emptyDir: {}
    name: tools
  - name: gcs-credentials
    secret:
      defaultMode: 420
      secretName: service-account
  - emptyDir: {}
    name: clonerefs-tmp
  - emptyDir: {}
    name: code
```

might be in the makefile where the issue arises I suppose...
