### ISSUE TITLE
Fails to define POD-NAMESPACE for pilot

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#25490]
I have below IOP:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    base:
      enabled: true
    pilot:
      enabled: true
      namespace: iris1
      k8s:
        env:
          - name: POD_NAMESPACE
            value: "istio-remote-system"
```
Then when I run `istioctl install -f myiop.yaml` it fails with below error:
```
2020-07-14T07:12:03.092900Z	error	installer	failed to create "Deployment/iris1/istiod": Deployment.apps "istiod" is invalid: spec.template.spec.containers[0].env[4].valueFrom: Invalid value: "": may not be specified when `value` is not empty
✘ Istiod encountered an error: failed to create "Deployment/iris1/istiod": Deployment.apps "istiod" is invalid: spec.template.spec.containers[0].env[4].valueFrom: Invalid value: "": may not be specified when `value` is not empty
```
I run `istioctl manifest generate -f myiop.yaml > out.yaml` and founds out the generated out.yaml has below lines:
```
        - name: POD_NAMESPACE
          value: istio-remote-system
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
```
So seems the merge logic has some issue .

**Comment by irisdingbj** [comment]
@ostromart @richardwxn Do we support above scenario? Thanks.

**Comment by howardjohn** [comment]
@irisdingbj you can probably explicitly set ValueFrom=nil, or use values.pilot.env.POD_NAMESPACE=foo

**Comment by morvencao** [comment]
Currently the extra k8s settings are applied to the corresponding components through strategic merge patch, which is either replaced or merged depending on its patch strategy. The patch strategy is specified by the value of the `patchStrategy` key in a field tag in the Kubernetes source code.

For `env` field, the patch strategy is **merge** based on key `name`, https://github.com/kubernetes/api/blob/master/core/v1/types.go#L2255 

For this case, you can also try to use k8s overlay to explicitly set `valueFrom` to be empty:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    pilot:
      enabled: true
          patches:
          - path: spec.template.spec.containers.[name:discovery].env.[name:POD_NAMESPACE].value
            value: "istio-remote-system" # OVERRIDDEN
          - path: spec.template.spec.containers.[name:discovery].env.[name:POD_NAMESPACE].valueFrom
            value:
```
