### ISSUE TITLE
Egress gateway does't work correctly when adding multiple external services 

### ISSUE THREAD

**Issue by hyogyunbang** [istio/istio#25491]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
I was trying to define multiple external services(redis: AWS ElastiCache) to route through egress gateway. I applied the following config, but it didn't work correctly and I could find error logs. Is this a bug or is there any solution?

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway-redis-1
  namespace: test
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      name: redis
      number: 6379
      protocol: TCP
    hosts:
    - "aaa.aaa.ng.0001.apne1.cache.amazonaws.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: egress-redis-1
  namespace: test
spec:
  hosts:
  - aaa.aaa.ng.0001.apne1.cache.amazonaws.com
  ports:
  - name: egress-redis-1
    number: 6379
    protocol: TCP
  location: MESH_EXTERNAL
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: egress-redis-1
  namespace: test
spec:
  hosts:
  - aaa.aaa.ng.0001.apne1.cache.amazonaws.com
  gateways:
  - istio-egressgateway-redis-1
  - mesh
  tcp:
  - match:
    - gateways:
      - mesh
      port: 6379
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: egress-redis-1
        port:
          number: 6379
  - match:
    - gateways:
      - istio-egressgateway-redis-1
      port: 6379
    route:
    - destination:
        host: aaa.aaa.ng.0001.apne1.cache.amazonaws.com
        port:
          number: 6379
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egress-redis-1
  namespace: test
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: egress-redis-1
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway-redis-2
  namespace: test
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      name: redis
      number: 6379
      protocol: TCP
    hosts:
    - "bbb.bbb.clustercfg.apne1.cache.amazonaws.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: egress-redis-2
  namespace: test
spec:
  hosts:
  - bbb.bbb.clustercfg.apne1.cache.amazonaws.com
  ports:
  - name: egress-redis-2
    number: 6379
    protocol: TCP
  location: MESH_EXTERNAL
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: egress-redis-2
  namespace: test
spec:
  hosts:
  - bbb.bbb.clustercfg.apne1.cache.amazonaws.com
  gateways:
  - istio-egressgateway-redis-2
  - mesh
  tcp:
  - match:
    - gateways:
      - mesh
      port: 6379
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: egress-redis-2
        port:
          number: 6379
  - match:
    - gateways:
      - istio-egressgateway-redis-2
      port: 6379
    route:
    - destination:
        host: bbb.bbb.clustercfg.apne1.cache.amazonaws.com
        port:
          number: 6379
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egress-redis-2
  namespace: test
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: egress-redis-2
```

Istio error logs
```
2020-07-14T08:24:42.803875Z#011info#011ads#011Push Status: {
    "pilot_conflict_outbound_listener_tcp_over_current_tcp": {
        "0.0.0.0:6379": {
            "proxy": "member-11111-22222.test",
            "message": "Listener=0.0.0.0:6379 AcceptedTCP=aaa.aaa.clustercfg.apne1.cache.amazonaws.com RejectedTCP=bbb.bbb.ng.0001.apne1.cache.amazonaws.com TCPServices=1"
        }
    }
}
```

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Kubernetes : 1.18.5
Istio : 1.6.4

**How was Istio installed?**
istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS, Ubuntu Server 20.04 LTS

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by GregHanson** [comment]
@honillusion ServiceEntry's are not scoped by namespace, and unlike HTTP and HTTPS/TLS, having two TCP services (ServiceEntry's in this case) both defined on 6379 will cause a port conflict.  I suggest defining one ServiceEntry and multiple labeled endpoints, with a corresponding DestinationRule to match:
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: httpbin
spec:
  hosts:
  - "*.apne1.cache.amazonaws.com"
  location: MESH_EXTERNAL
  ports:
  - number: 6379
    name: egress-redis
    protocol: TCP
  resolution: DNS
  endpoints:
  - address: aaa.aaa.ng.0001.apne1.cache.amazonaws.com
    labels:
      version: aaa
  - address: bbb.bbb.clustercfg.apne1.cache.amazonaws.com
    labels:
      version: bbb
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: redis-example
spec:
  host: "*.apne1.cache.amazonaws.com"
  subsets:
  - name: aaa
    labels:
      version: aaa
  - name: bbb
    labels:
      version: bbb
```

and update your VirtualServices to use the correct hostname so that it matches with the DestinationRule:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: egress-redis-2
  namespace: test
spec:
  hosts:
  - bbb.bbb.clustercfg.apne1.cache.amazonaws.com
  gateways:
  - istio-egressgateway-redis-2
  - mesh
  tcp:
  - match:
    - gateways:
      - mesh
      port: 6379
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: egress-redis-2
        port:
          number: 6379
  - match:
    - gateways:
      - istio-egressgateway-redis-2
      port: 6379
    route:
    - destination:
        host: "*.apne1.cache.amazonaws.com"
        subset: aaa
```

**Comment by honillusion** [comment]
@GregHanson  

I tried it as following and it still didn't work. Could you please review the configuration? 

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway-redis
  namespace: test
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      name: egress-redis
      number: 6379
      protocol: TCP
    hosts:
    - "*.apne1.cache.amazonaws.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: egress-redis
spec:
  hosts:
  - "*.apne1.cache.amazonaws.com"
  ports:
  - name: egress-redis
    number: 6379
    protocol: TCP
  resolution: DNS
  endpoints:
  - address: aaa.aaa.ng.0001.apne1.cache.amazonaws.com
    labels:
      version: aaa
  - address: bbb.bbb.clustercfg.apne1.cache.amazonaws.com
    labels:
      version: bbb
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: egress-redis-1
  namespace: test
spec:
  hosts:
  - aaa.aaa.ng.0001.apne1.cache.amazonaws.com
  gateways:
  - istio-egressgateway-redis
  - mesh
  tcp:
  - match:
    - gateways:
      - mesh
      port: 6379
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: egress-redis
        port:
          number: 6379
  - match:
    - gateways:
      - istio-egressgateway-redis
      port: 6379
    route:
    - destination:
        host: "*.apne1.cache.amazonaws.com"
        subset: aaa
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: egress-redis-2
  namespace: test
spec:
  hosts:
  - bbb.bbb.clustercfg.apne1.cache.amazonaws.com
  gateways:
  - istio-egressgateway-redis
  - mesh
  tcp:
  - match:
    - gateways:
      - mesh
      port: 6379
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: egress-redis
        port:
          number: 6379
  - match:
    - gateways:
      - istio-egressgateway-redis
      port: 6379
    route:
    - destination:
        host: "*.apne1.cache.amazonaws.com"
        subset: bbb
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egress-redis
  namespace: test
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: egress-redis
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: egress-redis-distinct
spec:
  host: "*.apne1.cache.amazonaws.com"
  subsets:
  - name: aaa
    labels:
      version: aaa
  - name: bbb
    labels:
      version: bbb
```

**Comment by GregHanson** [comment]
@honillusion can you elaborate on what isn't working? 

Are you still seeing problems with rejected configs?
```
istioctl proxy-status
```
Is anything `STALE`?  If so re-run with `istioctl proxy-status <podname>.<namespace>` to see what is different

If everything is showing as `SYNCED` in istioctl, what do the access logs look like? for the app istio-proxy container?  For one of the egress gateways?

**Comment by honillusion** [comment]
It couldn't connect both of the redis clusters and all was SYNCED in result of "istioctl proxy-status".

Client istio-proxy access log
```
[2020-07-21T06:43:22.701Z] "- - -" 0 - "-" "-" 0 0 1 - "-" "-" "-" "-" "10.244.1.89:9000" outbound|9000|egress-test|istio-egressgateway.istio-system.svc.cluster.local 10.244.2.33:34834 10.250.72.71:9000 10.244.2.33:41718 - -
```

Egress gateway istio-proxy access log
```
[2020-07-21T06:43:22.702Z] "- - -" 0 NR "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.244.1.89:9000 10.244.2.33:34834 - -
```

For test, I installed two tcp services so that port of the logs was 9000.

**Comment by honillusion** [comment]
@GregHanson It couldn't connect both of the redis clusters and all was SYNCED in result of "istioctl proxy-status".

Client istio-proxy access log
```
[2020-07-21T06:43:22.701Z] "- - -" 0 - "-" "-" 0 0 1 - "-" "-" "-" "-" "10.244.1.89:9000" outbound|9000|egress-test|istio-egressgateway.istio-system.svc.cluster.local 10.244.2.33:34834 10.250.72.71:9000 10.244.2.33:41718 - -
```

Egress gateway istio-proxy access log
```
[2020-07-21T06:43:22.702Z] "- - -" 0 NR "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.244.1.89:9000 10.244.2.33:34834 - -
```

For test, I installed two tcp services so that port of the logs was 9000.

**Comment by honillusion** [comment]
@GregHanson I had a test with the following manifest. In both cases of conneting to tcp1.test.com and tcp2.test.com, it is routed to only tcp1.test.com.

tcp1.test.com ---> tcp1.test.com
tcp2.test.com ---> tcp1.test.com

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway-test-1
  namespace: qa2
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      name: egress-test
      number: 9000
      protocol: TCP
    hosts:
    - "tcp1.test.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway-test-2
  namespace: qa2
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      name: egress-test
      number: 9000
      protocol: TCP
    hosts:
    - "tcp2.test.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: egress-test
spec:
  hosts:
  - "*.test.com"
  ports:
  - name: egress-test
    number: 9000
    protocol: TCP
  resolution: DNS
  endpoints:
  - address: tcp1.test.com
    labels:
      version: aaa
  - address: tcp2.test.com
    labels:
      version: bbb
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: egress-test-1
  namespace: qa2
spec:
  hosts:
  - "tcp1.test.com"
  gateways:
  - istio-egressgateway-test-1
  - mesh
  tcp:
  - match:
    - gateways:
      - mesh
      port: 9000
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: egress-test-1
        port:
          number: 9000
  - match:
    - gateways:
      - istio-egressgateway-test-1
      port: 9000
    route:
    - destination:
        host: "*.test.com"
        subset: aaa
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: egress-test-2
  namespace: qa2
spec:
  hosts:
  - "tcp2.test.com"
  gateways:
  - istio-egressgateway-test-2
  - mesh
  tcp:
  - match:
    - gateways:
      - mesh
      port: 9000
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: egress-test-2
        port:
          number: 9000
  - match:
    - gateways:
      - istio-egressgateway-test-2
      port: 9000
    route:
    - destination:
        host: "*.test.com"
        subset: bbb
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egress-test-1
  namespace: qa2
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: egress-test-1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egress-test-2
  namespace: qa2
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: egress-test-2
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: egress-test-distinct
spec:
  host: "*.test.com"
  subsets:
  - name: aaa
    labels:
      version: aaa
  - name: bbb
    labels:
      version: bbb
```
