### ISSUE TITLE
captureMode=NONE behavior change from 1.4 to 1.5 (and later)

### ISSUE THREAD

**Issue by phsiao** [istio/istio#25515]
**Bug description**

Without iptables injection, in 1.4 one can use the following Sidecar spec to get an egress endpoint.

```
spec:
  egress:
  - hosts:
    - "./*"
    port:
      number: 18080
      protocol: HTTP
      name: egresshttp
    bind: 127.0.0.1
    captureMode: NONE
```

However, in 1.5 this stops working.  Chatted with @rshriram and he suggested to change the protocol to HTTP_PROXY, and it makes the egress endpoint to start up.

There is one additional strange behavior --- it would create egress endpoints with 127.0.0.1:svc-port, where the svc-port matches imported services, when using protocol=HTTP.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

egress endpoint configuration that works under 1.4 should work in 1.5+.

**Steps to reproduce the bug**

Configure a sidecar with captureMode: NONE for an engress endpoint.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.5.8.

**How was Istio installed?**

istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**

On-prem, baremetal Kubernetes clusters, running CentOS 7.
