### ISSUE TITLE
Istio 1.6.5 - istiod failed to read mesh networks configuration

### ISSUE THREAD

**Issue by serrien** [istio/istio#25512]
**Bug description**

Istiod failed to read mesh networks configuration when meshNetworks.[network].gateways.address is configured with an externally resolvable DNS.

[ ] Configuration Infrastructure
[x] Docs
[x] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

According to the [documentation]( https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#Network-IstioNetworkGateway), meshNetworks.[network].gateways.address can be configured with an externally resolvable DNS address.

However, when this is the case, Istiod pod can not load mesh networks configuration.

**Steps to reproduce the bug**

Deploy a manifest with following configuration

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    gateways:
      istio-ingressgateway:
        meshExpansionPorts:
          - port: 15017
            targetPort: 15017
            name: tcp-webhook
          - port: 15012
            targetPort: 15012
            name: tcp-istiod

    global:
      multiCluster:
        clusterName: master
      network: network1
      centralIstiod: true
      caAddress: istiod.istio-system.svc:15012

      # Mesh network configuration. This is optional and may be omitted if
      # all clusters are on the same network.
      meshNetworks:
       network1:
         endpoints:
           # Always use Kubernetes as the registry name for the main cluster in the mesh network configuration
           - fromRegistry: master
         gateways:
           - address: a6d0c82c65478765f3af0ef863186a0ab-293021176.eu-west-3.elb.amazonaws.com
             port: 443

       network2:
         endpoints:
           - fromRegistry: remote1
         gateways:
           - address: d7d0c82c65478765f3af0ef876986a0ab-293027654.eu-west-3.elb.amazonaws.com
             port: 443

      # Use the existing istio-ingressgateway.
      meshExpansion:
        enabled: true
```

Istiod pod logs:

```
2020-07-14T21:19:10.085309Z	info	failed to read mesh networks configuration from "/etc/istio/config/meshNetworks": 2 errors occurred:
	* invalid network network1: a6d0c82c65478765f3af0ef863186a0ab-293021176.eu-west-3.elb.amazonaws.com is not a valid IP
	* invalid network network2: d7d0c82c65478765f3af0ef876986a0ab-293027654.eu-west-3.elb.amazonaws.com is not a valid IP


2020-07-14T21:19:10.085319Z	info	mesh networks configuration not provided
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
istioctl version --remote
client version: 1.6.5
control plane version: 1.6.5
data plane version: 1.6.5 (4 proxies)
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

`istioctl install -f manifest.yaml`

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS EKS 1.16
