### ISSUE TITLE
logWindowDuration setting leads to Istio proxy errors

### ISSUE THREAD

**Issue by cagataygurturk** [istio/istio#25550]
**Bug description**

Setting `.Values.telemetry.v2.accessLogPolicy.logWindowDuration` to a duration value produces incorrect JSON in the `stackdriver-sampling-accesslog-filter-1.6` EnvoyFilter, that leads to errors in Istio proxy.

The produced JSON is

```
...
value:
        name: istio.access_log
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          value:
            config:
              configuration: |
                {
                  "log_window_duration": 43200s
                }
              vm_config:
                code:
                  local:
                    inline_string: envoy.wasm.access_log_policy
...

```

`wasm log : Cannot parse AccessLog plugin configuration JSON string`

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
