### ISSUE TITLE
istio-ingressgateway pods do not gracefully terminate for drain durations greater than 30 seconds

### ISSUE THREAD

**Issue by ed-radical** [istio/istio#25575]
**Bug description**

Despite having env `TERMINATION_DRAIN_DURATION_SECONDS=310` set, when an istio-ingressgateway pod's istio-proxy container enters "graceful termination", the istio-proxy only waits for ~30 seconds before being killed or shutdown. 

As a result, clients encounter 504s for in-flight requests that take longer than 30 seconds.

End of istio-proxy logs:
```
istio-system/istio-ingressgateway-785f4c8f5d-xnrnn[istio-proxy]: 2020-07-15T21:11:14.591809Z	info	Agent draining Proxy
istio-system/istio-ingressgateway-785f4c8f5d-xnrnn[istio-proxy]: 2020-07-15T21:11:14.591871Z	info	Status server has successfully terminated
istio-system/istio-ingressgateway-785f4c8f5d-xnrnn[istio-proxy]: 2020-07-15T21:11:14.591925Z	error	accept tcp [::]:15020: use of closed network connection
istio-system/istio-ingressgateway-785f4c8f5d-xnrnn[istio-proxy]: 2020-07-15T21:11:14.593421Z	info	Graceful termination period is 5m10s, starting...
istio-system/istio-ingressgateway-785f4c8f5d-xnrnn[istio-proxy]: 2020-07-15T21:11:44.605749Z	warning	envoy main	[external/envoy/source/server/server.cc:527] caught SIGTERM
istio-system/istio-ingressgateway-785f4c8f5d-xnrnn[istio-proxy]: 2020-07-15T21:11:44.605779Z	warning	envoy main	[external/envoy/source/server/server.cc:527] caught SIGTERM
```

The istio-ingressgateway deployment and pod spec shows `terminationGracePeriodSeconds: 30`.

Although istio-proxy (envoy) warns that it "caught SIGTERM" after ~30 seconds, I suspect the it is actually being killed by SIGKILL. 

I do not encounter this bug, after I manually edited the istio-ingressgateway deployment spec to have `terminationGracePeriodSeconds: 310`.

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

The istio-ingressgateway pod should have waited the full graceful termination period specified (5m10s) before being killed or shutdown. 

**Steps to reproduce the bug** 

1. Create a service/deployment that can take > 1min to respond to HTTP requests along with the virtualservice and gateway resources necessary to route requests from the istio-ingressgateway to this service.

2. Send a HTTP request with an expected response time > 1min through the istio-ingressgateway to the upstream service.

3. Immediately after step 2, delete the istio-ingressgateway pod. The pod is usually killed after ~30-40 seconds, and the HTTP client receives a 504 response from the ELB.
```
❯ time kubectl delete pods -n istio-system istio-ingressgateway-785f4c8f5d-xnrnn
pod "istio-ingressgateway-785f4c8f5d-xnrnn" deleted
kubectl delete pods -n istio-system istio-ingressgateway-785f4c8f5d-xnrnn  0.42s user 0.14s system 1% cpu 32.943 total
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
❯ istioctl version --remote
client version: 1.6.5
cluster-local-gateway version:
cluster-local-gateway version:
pilot version: 1.6.5
pilot version: 1.6.5
data plane version: 1.6.5 (12 proxies)
```
```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-07-04T15:01:15Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

`istioctl upgrade -f <manifest_below>`
``` 
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-operator
spec:
  namespace: istio-system

  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          env:
            - name: 'ISTIO_DEFAULT_REQUEST_TIMEOUT'
              value: '300s'
            - name: 'TERMINATION_DRAIN_DURATION_SECONDS'
              value: '310'
          replicaCount: 1
          podDisruptionBudget:
            minAvailable: 1

  meshConfig:
    accessLogEncoding: JSON
    accessLogFile: /dev/stdout
    defaultConfig:
      drainDuration: "301s"
      parentShutdownDuration: "302s"
      proxyMetadata:
        TERMINATION_DRAIN_DURATION_SECONDS: "303"
```

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by ed-radical** [comment]
Here's a workaround:
```
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          env:
            - name: 'TERMINATION_DRAIN_DURATION_SECONDS'
              value: '310'
          overlays:
            - kind: Deployment
              name: istio-ingressgateway
              patches:
                - path: spec.template.spec.terminationGracePeriodSeconds
                  value: 310
```
