### ISSUE TITLE
Istiod not pushing RDS to ingress-gateway in 1.6

### ISSUE THREAD

**Issue by pslobo** [istio/istio#25657]
**Bug description**
 I have a relatively simple setup that was working fine in 1.5.4. When attempting to upgrade to 1.6, I noticed that ingress-gateway stopped working as expected. Health checks from the load balancer (GCP) failed and service came offline. When analysing, I noticed that `istiooctl ps` shows `RDS` as `NOT SENT` for ingress, no matter how long I wait.

With **1.5.4**, the following VirtualService works:

```yaml
k apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: health
spec:
  gateways:
    - istio-system/istio-ingressgateway
  hosts:
    - "*"
  http:
    - match:
        - headers:
            user-agent:
              prefix: GoogleHC
              #prefix: kube-probe
          method:
            exact: GET
          uri:
            exact: /
      rewrite:
        authority: istio-ingressgateway.istio-system.svc.cluster.local:15020
        uri: /healthz/ready
      route:
        - destination:
            host: istio-ingressgateway.istio-system.svc.cluster.local
            port:
              number: 15020
```

```bash
$ istioctl ps | grep -v default
NAME                                                   CDS        LDS        EDS        RDS          PILOT                       VERSION
istio-egressgateway-5f4df9c787-rh7g9.istio-system      SYNCED     SYNCED     SYNCED     NOT SENT     istiod-74c6d9ccdb-lfcwx     1.5.4
istio-ingressgateway-65745cc777-xv986.istio-system     SYNCED     SYNCED     SYNCED     SYNCED       istiod-74c6d9ccdb-lfcwx     1.5.4
prometheus-564768879c-2jwlc.istio-system               SYNCED     SYNCED     SYNCED     SYNCED       istiod-74c6d9ccdb-lfcwx     1.5.4
```

```bash
$ istioctl pc routes istio-ingressgateway-65745cc777-xv986.istio-system -ojson | grep -A2 -B2 healthz
                        "route": {
                            "cluster": "outbound|15020||istio-ingressgateway.istio-system.svc.cluster.local",
                            "prefixRewrite": "/healthz/ready",
                            "hostRewrite": "istio-ingressgateway.istio-system.svc.cluster.local:15020",
                            "timeout": "0s",
```

However, when doing the exact same thing with **1.6.5**, it doesn't work as I'd expect

```bash
$ istioctl ps
NAME                                                  CDS        LDS        EDS        RDS          PILOT                       VERSION
istio-egressgateway-65ddddfbdd-8zsj5.istio-system     SYNCED     SYNCED     SYNCED     NOT SENT     istiod-7697c784c4-cqvht     1.6.5
istio-ingressgateway-5d46b6779-q27nt.istio-system     SYNCED     SYNCED     SYNCED     NOT SENT     istiod-7697c784c4-cqvht     1.6.5
prometheus-7c4b6d955-qt6j8.istio-system               SYNCED     SYNCED     SYNCED     SYNCED       istiod-7697c784c4-cqvht     1.6.5

$ istioctl pc routes istio-ingressgateway-5d46b6779-q27nt.istio-system | grep -A2 -B2 healthz

```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**How was Istio installed?**
```yaml
$ istioctl manifest apply -f setup.yaml

$ cat setup.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    accessLogFile: "/dev/stdout"

  addonComponents:
    grafana:
      enabled: true
    prometheus:
      enabled: true
    kiali:
      enabled: true
    tracing:
      enabled: true

  components:
    egressGateways:
      - name: istio-egressgateway
        enabled: true
        k8s:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: app
                          operator: In
                          values:
                            - istio-egressgateway
                    topologyKey: kubernetes.io/hostname
                  weight: 100
          hpaSpec:
            maxReplicas: 5
            minReplicas: 1
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: istio-egressgateway

    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: app
                          operator: In
                          values:
                            - istio-ingressgateway
                    topologyKey: kubernetes.io/hostname
                  weight: 100
          hpaSpec:
            maxReplicas: 5
            minReplicas: 1
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: istio-ingressgateway
          serviceAnnotations:
            cloud.google.com/neg: '{"ingress": true}'
          overlays:
            - kind: Service
              name: istio-ingressgateway
              patches:
                - path: spec.type
                  value: NodePort
```

**Environment where bug was observed (cloud vendor, OS, etc)**

Currently running on GKE cluster with k8s at 1.16.9

Edit: I can pretty much destroy and redo anything on this cluster for now. In a couple of weeks will be harder, so let me know if you want me to test anything in particular.

**Comment by howardjohn** [comment]
Likely due to https://istio.io/latest/news/releases/1.6.x/announcing-1.6/upgrade-notes/#change-the-readiness-port-of-gateways? Can you change the port?

**Comment by pslobo** [comment]
Yeah, I had picked up on that change and tried that too. IIRC, had the same issue but will re-deploy 1.6 in the morning and try again. One thing I did notice however was the port seemed wrong in the demo profile (or default profile).

```yaml
❯ istioctl profile dump demo --config-path components.ingressGateways | yq r - .k8s.service.ports
- name: status-port
  port: 15020
  targetPort: 15020
- name: http2
  port: 80
  targetPort: 8080
- name: https
  port: 443
  targetPort: 8443
- name: tcp
  port: 31400
  targetPort: 31400
- name: tls
  port: 15443
  targetPort: 15443

❯ istioctl profile dump default --config-path components.ingressGateways | yq r - .k8s.service.ports
- name: status-port
  port: 15021
  targetPort: 15021
- name: http2
  port: 80
  targetPort: 8080
- name: https
  port: 443
  targetPort: 8443
- name: tls
  port: 15443
  targetPort: 15443
```

Likely nothing to do with this issue in particular, but something to look into I guess.
