### ISSUE TITLE
`workloadSelector` result in ServiceEntry is wrong after change the labels in WorkloadEntry

### ISSUE THREAD

**Issue by dozer47528** [istio/istio#25678]
**Bug description**

```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: test-se
  namespace: default
spec:
  hosts:
  - www.test.com
  location: MESH_EXTERNAL
  ports:
  - name: http
    number: 80
    protocol: HTTP
  resolution: STATIC
  workloadSelector:
    labels:
      ready: "true"
      app: "test"
---
apiVersion: networking.istio.io/v1beta1
kind: WorkloadEntry
metadata:
  name: test-we
  namespace: default
spec:
  address: 8.8.8.8
  labels:
    ready: "true"
    app: "test"
  ports:
    http: 80
```

I have a ServiceEntry with workloadSelector which can match the target WorkloadEntries.

If the WorkloadEntry is not available, I don't want to delete it, I just change the label to make it not match.

But after change the label `ready` to `false` in WorkloadEntry, I still can see the WorkloadEntry in Envoy `/clusters` apis

```
outbound|80||www.test.com::default_priority::max_connections::4294967295
outbound|80||www.test.com::default_priority::max_pending_requests::4294967295
outbound|80||www.test.com::default_priority::max_requests::4294967295
outbound|80||www.test.com::default_priority::max_retries::4294967295
outbound|80||www.test.com::high_priority::max_connections::1024
outbound|80||www.test.com::high_priority::max_pending_requests::1024
outbound|80||www.test.com::high_priority::max_requests::1024
outbound|80||www.test.com::high_priority::max_retries::3
outbound|80||www.test.com::added_via_api::true
outbound|80||www.test.com::8.8.8.8:80::cx_active::0
outbound|80||www.test.com::8.8.8.8:80::cx_connect_fail::0
outbound|80||www.test.com::8.8.8.8:80::cx_total::0
outbound|80||www.test.com::8.8.8.8:80::rq_active::0
outbound|80||www.test.com::8.8.8.8:80::rq_error::0
outbound|80||www.test.com::8.8.8.8:80::rq_success::0
outbound|80||www.test.com::8.8.8.8:80::rq_timeout::0
outbound|80||www.test.com::8.8.8.8:80::rq_total::0
outbound|80||www.test.com::8.8.8.8:80::hostname::
outbound|80||www.test.com::8.8.8.8:80::health_flags::healthy
outbound|80||www.test.com::8.8.8.8:80::weight::1
outbound|80||www.test.com::8.8.8.8:80::region::
outbound|80||www.test.com::8.8.8.8:80::zone::
outbound|80||www.test.com::8.8.8.8:80::sub_zone::
outbound|80||www.test.com::8.8.8.8:80::canary::false
outbound|80||www.test.com::8.8.8.8:80::priority::0
outbound|80||www.test.com::8.8.8.8:80::success_rate::-1.0
outbound|80||www.test.com::8.8.8.8:80::local_origin_success_rate::-1.0
```

After changing the label, even if I delete the WorkloadEntry, the endpoint is still visible in Envoy.

**Affected product area (please put an X in all that apply)**

[x] Networking

**Expected behavior**

The endpoint should disappear in Envoy after changing the label or delete the WorkloadEntry.

**Steps to reproduce the bug**

1. Install the WorkloadEntry and ServiceEntry
2. Change the label `ready` to `false` in WorkloadEntry
3. Run `istioctl dashboard envoy [any-pod-in-mesh] --port 8080` and visit `http://localhost:8080/clusters` to check endpoints
4. Delete WorkloadEntry
5. visit `http://localhost:8080/clusters` again

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

client version: 1.6.5
control plane version: 1.6.5

**How was Istio installed?**

```sh
istioctl operator init

kubectl create namespace istio-system

kubectl label namespace default istio-injection=enabled

kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: demo
EOF
```

**Environment where bug was observed (cloud vendor, OS, etc)**

minikube v1.12.1
