### ISSUE TITLE
can not get metrics value of api.version api.service api.operation

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#25736]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

```
[root@master01 httpapispec]# vi httpapispec.yaml 
apiVersion: config.istio.io/v1alpha2
kind: HTTPAPISpec
metadata:
  name: products
spec:
  attributes:
    attributes:
      api.service:
        stringValue: productpage
      api.version:
        stringValue: 1.0.0
  patterns:
  - attributes:
      attributes:
        api.operation:
          stringValue: /productpage
    httpMethod: GET
    uriTemplate: /productpage

[root@master01 httpapispecbinding]# cat httpapispecbinding.yaml 
apiVersion: config.istio.io/v1alpha2
kind: HTTPAPISpecBinding
metadata:
  name: products-binding
spec:
  api_specs:
  - name: products
    namespace: istio
  services:
  #- domain: svc.cluster.local
  - name: productpage
    namespace: istio


[root@master01 telemetry]# cat metrics.yaml 
# Configuration for metric instances
apiVersion: config.istio.io/v1alpha2
kind: instance
metadata:
  name: doublerequestcount
  namespace: istio-system
spec:
  compiledTemplate: metric
  params:
    value: "2" # count each request twice
    dimensions:
      reporter: conditional((context.reporter.kind | "inbound") == "outbound", "client", "server")
      source: source.workload.name | "unknown"
      destination: destination.workload.name | "unknown"
      message: '"twice the fun!"'
      api_operation: api.operation | "unknown"
      api_service: api.service | "unknown"
      api_version: api.version | "unknown"
    monitored_resource_type: '"UNSPECIFIED"'
---
# Configuration for a Prometheus handler
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: doublehandler
  namespace: istio-system
spec:
  compiledAdapter: prometheus
  params:
    metrics:
    - name: bb_double_request_count # Prometheus metric name
      instance_name: doublerequestcount.instance.istio-system # Mixer instance name (fully-qualified)
      kind: COUNTER
      label_names:
      - reporter
      - source
      - destination
      - message
      - api_operation
      - api_version
      - api_service
---
# Rule to send metric instances to a Prometheus handler
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: doubleprom
  namespace: istio-system
spec:
  actions:
  - handler: doublehandler
    instances: [ doublerequestcount ]
```

![image](https://user-images.githubusercontent.com/31508490/88144995-5979c000-cc2c-11ea-9ad4-76bc7db40c3f.png)

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
[root@master01 telemetry]# istioctl version
client version: 1.4.10
control plane version: 1.4.10
data plane version: 1.4.10 (12 proxies)

```
[root@master01 telemetry]# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2020-05-12T09:28:18Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"linux/amd64"}
[root@master01 telemetry]# 
```
**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
