### ISSUE TITLE
Received HTTP code 404 from proxy after CONNECT - istio-ingressgateway pod logs

### ISSUE THREAD

**Issue by cooldudesam** [istio/istio#25753]
Use case: To access external AWS S3 service via VPC endpoint from On-prem servers so that the traffic does not traverse the internet. 

onprem-->COLO-->NLB--->ISTIO-->EKS (httpd pod acting as proxy to external service)--->S3 VPC endpoint

I have deployed httpd pod (acting as fwd proxy) with istio sidecar injected in EKS and exposed it over istio ingress and NLB. Iam able to access the httpd via NLB host just fine. but when I try to use the deployed httpd pod as proxy and try to connect to S3 service via simple curl command I get "Received HTTP code 404 from proxy after CONNECT - istio-ingressgateway pod logs.

# curl -v -x aec822f71432511eaa1e10a7b4d9f41b-a33ebd786be79bd3.elb.us-east-1.amazonaws.com:80 https://s3.us-east-1.amazonaws.com
* About to connect() to proxy aec822f71432511eaa1e10a7b4d9f41b-a33ebd786be79bd3.elb.us-east-1.amazonaws.com port 80 (#0)
*   Trying 10.48.240.142...
* Connected to aec822f71432511eaa1e10a7b4d9f41b-a33ebd786be79bd3.elb.us-east-1.amazonaws.com (10.48.240.142) port 80 (#0)
* Establish HTTP proxy tunnel to s3.us-east-1.amazonaws.com:443
> CONNECT s3.us-east-1.amazonaws.com:443 HTTP/1.1
> Host: s3.us-east-1.amazonaws.com:443
> User-Agent: curl/7.29.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 404 Not Found
< date: Wed, 22 Jul 2020 15:42:15 GMT
< server: istio-envoy
< content-length: 0
<
* Received HTTP code 404 from proxy after CONNECT
* Connection #0 to host aec822f71432511eaa1e10a7b4d9f41b-a33ebd786be79bd3.elb.us-east-1.amazonaws.com left intact
curl: (56) Received HTTP code 404 from proxy after CONNECT

*****************************
# kubectl logs -f -l istio=ingressgateway -n istio-system
[2020-07-22T15:43:48.045Z] "CONNECT s3.us-east-1.amazonaws.com:443 HTTP/1.1" 404 - "-" "-" 0 0 0 - "-" "curl/7.29.0" "-" "s3.us-east-1.amazonaws.com:443" "-" - - 10.48.240.79:80 10.48.240.172:52121 - -

I dont see the request reached httpd pod . I followed the below links but still no help

https://istio.io/latest/docs/tasks/traffic-management/egress/http-proxy/

https://istio.io/latest/docs/tasks/traffic-management/egress/egress-tls-origination/#tls-origination-for-egress-traffic

Did anyone face the similar issue? Did this kind of setup work with istio or not?

**Comment by cooldudesam** [comment]
One thing that i noticed is if i try to access external service with HTTP i see some progress and get HTTP 403 Forbidden error but not fixed entirely. 

# curl -v -x aec822f71432511eaa1e10a7b4d9f41b-a33ebd786be79bd3.elb.us-east-1.amazonaws.com:80 http://s3.us-east-1.amazonaws.com
* About to connect() to proxy aec822f71432511eaa1e10a7b4d9f41b-a33ebd786be79bd3.elb.us-east-1.amazonaws.com port 80 (#0)
*   Trying 10.48.240.142...
* Connected to aec822f71432511eaa1e10a7b4d9f41b-a33ebd786be79bd3.elb.us-east-1.amazonaws.com (10.48.240.142) port 80 (#0)
> GET http://s3.us-east-1.amazonaws.com/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: s3.us-east-1.amazonaws.com
> Accept: */*
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 403 Forbidden
< date: Wed, 22 Jul 2020 17:27:59 GMT
< server: istio-envoy
< content-length: 199
< content-type: text/html; charset=iso-8859-1
< x-envoy-upstream-service-time: 8
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
</body></html>
* Connection #0 to host aec822f71432511eaa1e10a7b4d9f41b-a33ebd786be79bd3.elb.us-east-1.amazonaws.com left intact

******************************
The logs from ingressgateway pod

# kubectl logs -f -l istio=ingressgateway -n istio-system
[2020-07-22T17:28:00.079Z] "GET / HTTP/1.1" 403 - "-" "-" 0 199 9 8 "10.48.240.186" "curl/7.29.0" "a384b4d9-979c-4994-9a50-74e21878fbd5" "s3.us-east-1.amazonaws.com" "10.48.240.183:80" outbound|80||apache-s3proxy-svc.test-ns.svc.cluster.local - 10.48.240.44:80 10.48.240.186:54325 - -

****************************************
The logs from  httpd proxy pod inside EKS
# kubectl logs -f apache-s3proxy-649b4dbf47-wpnt9 -n test-ns -c httpd
10.48.240.186 - - [22/Jul/2020:17:28:00 +0000] "GET / HTTP/1.1" 403 199 "-" "curl/7.29.0" 876 344 188

**Comment by cooldudesam** [comment]
It looks like Envoy’s default matchers match based on host and path. Because CONNECT requests (generally) do not have a path, most matchers will fail to match CONNECT requests, and Envoy will send a 404 because the route is not found. The solution for HTTP/1.1 CONNECT requests, is to use a connect_matcher as described in the CONNECT section of the upgrade documentation.

Did anyone pass this config config.route.v3.RouteMatch.ConnectMatcher as Envoy Filter and did it work?

**Comment by cooldudesam** [comment]
Iam trying to apply the below EnvoyFilter but facing issues. Any suggestion/help is much appreciated

apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: connect-proxy
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER # http connection manager is a filter in Envoy
    match:
      context: ANY
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
    patch:
      operation: MERGE
      value:
        name: "envoy.http_connection_manager"
        typed_config:
          "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager.UpgradeConfig"
          "upgrade_type": "CONNECT"
          "enabled": true
  - applyTo: HTTP_FILTER # http connection manager is a filter in Envoy
    match:
      context: ANY
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.router"
    patch:
      operation: MERGE
      value:
        name: "envoy.http_connection_manager"
        typed_config:
          "@type": "type.googleapis.com/envoy.config.route.v3.RouteMatch"
          connect_matcher: 12

$ kubectl apply -f EnvoyFilter.yaml -n istio-system
Error from server: error when creating "EnvoyFilter.yaml": admission webhook "validation.istio.io" denied the request: configuration is invalid: Envoy filter: can't unmarshal Any nested proto *envoy_config_route_v3.RouteMatch: unknown field "connect_matcher" in envoy_config_route_v3.RouteMatch

**Comment by nicole-chen-fivestars** [comment]
@cooldudesam were you able to get this to work?

**Comment by eddiewang** [comment]
trying to solve the same problem - @nicole-chen-fivestars were you able to find a solution by chance?

**Comment by cooldudesam** [comment]
Sorry for the late reply! I did not get it to work. We have bypassed istio in our case.

**Comment by whalecold** [comment]
I try it and it takes effect.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: proxy-connect-matcher
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: SIDECAR_OUTBOUND
      listener:
        name: "0.0.0.0_8118"
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          upgrade_configs:
          # enable econnect upgrade
          - upgrade_type: "CONNECT"
            enabled: true
  - applyTo: HTTP_ROUTE
    match:
      context: SIDECAR_OUTBOUND
      routeConfiguration:
        name: "8118"
        vhost: 
          name: allow_any
          route:
            name: allow_any
    patch:
      operation: INSERT_AFTER
      value:
        name: allow_connect
        match:
          # allow connect match
          connect_matcher: {}
        route:
          cluster: PassthroughCluster
          timeout: 0s
          max_grpc_timeout: 0s

```

**Comment by jamesdavidson** [comment]
If you have a pod in an Istio environment that is trying to connect with HTTPS_PROXY environment variable set then I would recommend using the traffic.sidecar.istio.io/excludeOutboundPorts annotation.

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    sidecar.istio.io/inject: "true"
    traffic.sidecar.istio.io/excludeOutboundPorts: "3128"
...
```

In the case described in this ticket you might need `traffic.sidecar.istio.io/excludeInboundPorts: "3128"` instead.

**Comment by Moulick** [comment]
For future reference if anyone is looking to make use of an HTTP Proxy. Even if it's http and not https, still has to be defined at TCP

```
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: <name>
  namespace: <namespace>
spec:
  hosts:
    - <proxy-host> # Not ignored!
  ports:
    - number: 80 # or any port
      name: tcp
      protocol: TCP
  location: MESH_EXTERNAL
  resolution: DNS
```

Docs at https://istio.io/latest/docs/tasks/traffic-management/egress/http-proxy/ say that the `.spec.host` is ignored. Not sure if that's suppose to mean that it happens only if `.spec.addresses` is given or always.

In my testing (version 1.27.1) if I define host without `.spec.addresses` as above it works. Then `curl -x http://<proxy-host>:80 --proxy-user user:password -k https://example-files.online-convert.com/document/txt/example.txt` will work from a istio injected pod without having to define `excludeInboundPorts`
