### ISSUE TITLE
IstioOperator puts same selector on different ingress gateways' Deployment objects.

### ISSUE THREAD

**Issue by dsbos** [istio/istio#25771]
When using "`istioctl manifest generate ...`" with an `IstioOperator` YAML file that specifies two ingress gateways, the two generated K8s Deployments for the two ingress controller services have the same value for `spec.selector` (`matchLabels` with the same set of label names and values).

Doesn't that mean that each of the Deployments will think that it owns all the pods created by either one of the Deployments, rather than just the pods it created? (I'm relatively new to K8s, so maybe I don't understand this correctly.)

(Each Deployment does label its created pods uniquely. The labels in `spec.template.metadata.labels` do include one that copies the corresponding ingress name from the IstioOperator file, making the pods' set of labels unique.)

For example, this `IstioOperator` file:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  components:
    ingressGateways:
    - name: istio-ingressgateway1
      enabled: true
    - name: istio-ingressgateway2
      enabled: true
```
processed via `istioctl manifest generate -f ...` (with `istioctl` from Istio 1.6.5) outputs a YAML file including the following:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-ingressgateway1
  namespace: istio-system
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
  ...
  template:
    metadata:
      labels:
        app: istio-ingressgateway
        istio: ingressgateway
        heritage: Tiller
        release: istio
        chart: gateways
        service.istio.io/canonical-name: istio-ingressgateway1
        service.istio.io/canonical-revision: latest
...

apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-ingressgateway2
  namespace: istio-system
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
  ...
  template:
    metadata:
      labels:
        app: istio-ingressgateway
        istio: ingressgateway
        heritage: Tiller
        release: istio
        chart: gateways
        service.istio.io/canonical-name: istio-ingressgateway2
        service.istio.io/canonical-revision: latest
...
```
In particular, note how each Deployment has:
```
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
```
(not narrowing down the match to only the pods created by that Deployment).

Additionally, a number of other things in the generated K8s-objects file don't seem right.  (See other labels and selectors involving values containing "`ingressgateway`" but not specific gateway names, and 
ConfigMap `istio-system`, whose `data.mesh.ingressService` has the value `istio-ingressgateway` (which is not the name of either Service created for the ingresses in the IstioOperator file).)
