### ISSUE TITLE
Having Issues Connecting to Redis UI headless service using Anthos Istio gateway

### ISSUE THREAD

**Issue by harshjay04** [istio/istio#25802]
We have deployed Anthos GKE on-prem and trying to connect to Redis UI service and it is failing, we haven't injected envoy side car as when we do that Redis deployment itself fails due to Redis Operator not able to communicate with POD's, we realized that Redis is not integrated with Istio Service Mesh yet ( may be creating the problem) , so we tried only with Ingress gateway config and getting the error captured in the thread, Can someone guide us how to make this work with Istio Ingress Gateway

We have the config like exernal URL--> Ingress gateway TLS(Certificate applied through Secrets)--> Gateway yaml---> Virtualservice yaml--> service entry yaml 

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: redis-enterprise
  namespace: redis
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - redis-gke-poc-ui.test.com
    port:
      name: https-redis
      number: 443
      protocol: HTTPS
    tls:
      credentialName: redis-certificate
      mode: SIMPLE

------------------

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: redis-enterprise-ui
  namespace: redis
spec:
  gateways:
  - redis-enterprise-gateway
  hosts:
  - redis-gke-poc-ui.test.com
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: redis-enterprise-0.redis-enterprise.redis.svc.cluster.local
        port:
          number: 9443
-----------------------------------------

apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: redis-enterprise-ui
  namespace: redis
spec:
  hosts:
  - redis-enterprise-0.redis-enterprise.redis.svc.cluster.local
  location: MESH_INTERNAL
  ports:
  - name: https
    number: 9443
    protocol: TCP
  resolution: DNS (edited) 
```

This is the Error we are getting when we try to access the UI through LB external IP

```
< HTTP/1.1 503 Service Unavailable
< content-length: 91
< content-type: text/plain
< date: Wed, 15 Jul 2020 04:56:48 GMT
< server: istio-envoy
<
upstream connect error or disconnect/reset before headers. reset reason: connection failure* Connection #0 to host redis-gke-poc-ui.test.com left intact
```
