### ISSUE TITLE
[Networking] TLS minProtocolVersion doesn't work

### ISSUE THREAD

**Issue by framled** [istio/istio#25801]
**Bug description**
it seems, minProtocolVersion is not working, because when I execute testssl or just force connection to use TLSv1.1 I got a response from the server.
```
No engine or GOST support via engine with your /usr/local/opt/openssl@1.1/bin/openssl

###########################################################
    testssl.sh       3.0.2 from https://testssl.sh/
    (9094d70 2020-07-20 16:46:51 -- )

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.1.1g  21 Apr 2020" [~80 ciphers]
 on MacBook-Pro-2:/usr/local/opt/openssl@1.1/bin/openssl
 (built: "Apr 21 13:30:00 2020", platform: "darwin64-x86_64-cc")


 Start 2020-07-23 12:19:26        -->> REDACTED <<--

 rDNS (34.96.74.194):    194.74.96.34.bc.googleusercontent.com.
 Service detected:       HTTP


 Testing protocols via sockets except NPN+ALPN

 SSLv2      not offered (OK)
 SSLv3      not offered (OK)
 TLS 1      not offered
 TLS 1.1    offered (deprecated)
 TLS 1.2    offered (OK)
 TLS 1.3    offered (OK): final
 NPN/SPDY   not offered
 ALPN/HTTP2 h2, http/1.1, grpc-exp (offered)
```

**Affected product area**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

no offer TSL 1.1

**Steps to reproduce the bug**

Configure the following gateway
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  labels:
    operator.istio.io/component: IngressGateway
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.5.1
    release: istio
  name: default-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - REDACTED
      port:
        name: http
        number: 80
        protocol: http
      tls:
        httpsRedirect: true
    - hosts:
        - REDACTED
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        minProtocolVersion: TLSV1_2
        maxProtocolVersion: TLSV1_3
        serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
        privateKey: /etc/istio/ingressgateway-certs/tls.key
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istioctl versión
```
client version: 1.6.5
control plane version: 1.6.5
data plane version: 1.6.5 (12 proxies)
```

kubectl versión
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"756f1dd1a3bbaf6cb927ec798ad64d62a3130501", GitTreeState:"clean", BuildDate:"2020-06-01T20:41:30Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

istio was installed with istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
Azure AKS.

**Comment by hasusuf** [comment]
This issue is a blocker of at least 3 of our clients. We are not able to pass the penetration test to be production ready!

We will appreciated, any workaround or hotfix here to eliminate that issue.

We are using istio 1.5.1 on GCP.

**Comment by hasusuf** [comment]
The problem got resolved after restarting the control plane using the following command 🤷🏻‍♂️
`kubectl -n istio-system get deployment --no-headers -o custom-columns=":metadata.name" | xargs kubectl -n istio-system rollout restart deployment`

**Comment by httran13** [comment]
can we reopen this issue? I've tried to use the soln above but tls scans still reports tls v1.0 and v1.1 as enabled

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  annotations:
  name: xxx-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - 'xxx-0001.us-south.containers.appdomain.cloud'
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - 'xxx-0001.us-south.containers.appdomain.cloud'
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: xxx-0001
        minProtocolVersion: TLSV1_3
        maxProtocolVersion: TLSV1_3
        cipherSuites:
          - ECDHE-ECDSA-AES128-GCM-SHA256
          - ECDHE-RSA-AES128-GCM-SHA256
          - ECDHE-ECDSA-AES128-SHA
          - AES128-GCM-SHA256
          - AES128-SHA
          - ECDHE-ECDSA-AES256-GCM-SHA384
          - ECDHE-RSA-AES256-GCM-SHA384
          - ECDHE-ECDSA-AES256-SHA
          - AES256-GCM-SHA384
          - AES256-SHA
         ```
