### ISSUE TITLE
Make SECRET_TTL and SECRET_ROTATION_CHECK_INTERVAL of istio-agent be configurable via istioctl

### ISSUE THREAD

**Issue by mike1808** [istio/istio#25808]
**Describe the feature request**

We want to change the value of `SECRET_TTL` and `SECRET_ROTATION_CHECK_INTERVAL` environment variables of istio-agent via an option for IstioOperator. 

**Describe alternatives you've considered**

Currently, to change those values we have to edit `envs` field in the sidecar injector template. 

**Affected product area (please put an X in all that apply)**

- [x] Configuration Infrastructure
- [ ] Docs
- [x] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [x] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

For our use case, we want to set different values and modifying the injector template will cause us to maintain it and probably cause issues when Istio updates. 

Also, currently, docs for those values are out-dated, see #24221.

cc @tcdowney

**Comment by howardjohn** [comment]
You can do this today:
```
apiVersion: operator.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
  namespace: istio-operator
spec:
  meshConfig:
    defaultConfig:
      proxyMetadata:
        SECRET_TTL: 10m
```
