### ISSUE TITLE
can't set Values.global.proxy.env

### ISSUE THREAD

**Issue by lcx102737** [istio/istio#25826]
**Bug description**
refer to https://github.com/istio/istio/pull/18333

version: 1.6.5
I want to set the environment terminal _drain_duration_seconds value to 10

The configuration file is as follows
```
  values:
    global:
      istioNamespace: istio-system
      istiod:
        enabled: true
        enableAnalysis: false
      logging:
        level: "default:info"
      logAsJson: false
      pilotCertProvider: istiod
      jwtPolicy: first-party-jwt
      proxy:
        env: {
          TERMINATION_DRAIN_DURATION_SECONDS: 10
        }
```

error info
```
unknown field "env" in v1alpha1.ProxyConfig
spec invalid; continuing because of --force: unknown field "env" in v1alpha1.ProxyConfig
```

Values.global.proxy.env is currently supported?Is there another way to set it in the IstioOperator Yaml?

**Comment by morvencao** [comment]
Try to use **meshConfig**:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  meshConfig:
    defaultConfig:
      proxyMetadata:
        TERMINATION_DRAIN_DURATION_SECONDS: 10
```

**Comment by lcx102737** [comment]
@morvencao Thank you very much,configuration to take effect

The thing to notice is the string type
```
spec:
  meshConfig:
    defaultConfig:
      proxyMetadata:
        TERMINATION_DRAIN_DURATION_SECONDS: "10"
```
