### ISSUE TITLE
Document Behavior: Authorization policy impacting TCP traffic.

### ISSUE THREAD

**Issue by kuuji** [istio/istio#25832]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

I have an authorization policy attempting to block traffic on a specific path and coming with a specific user-agent header.
See the configuration below.
When this policy is applied, it also blocks all non HTTP traffic in my cluster. It seems like it's trying to apply the policy to the TCP traffic but since it can't figure out the path or the header, it just defaults to DENY.

```
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name:useragent-filter
  namespace: istio-system
spec:
  action: DENY
  rules:
  - when:
    - key: request.headers[User-Agent]
      values: ["User-Agent: redacted"]
    to:
    - operation:
        paths:
        - /path/*
```

Our current fix is to make this policy more scoped by also targeting a port in the operation field. I was assuming that by having the path and the header, it would make this policy apply to HTTP traffic only. I didn't find any other way to configure a policy so that it would only apply to a specific protocol (HTTP in that case).

I wasn't sure if it was the intended design for authorization policy or if it is actually a bug..

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

Authorization policies applying to path or header should only apply to HTTP traffic or Authorization policies should have a way to specify which protocol they apply to.

**Steps to reproduce the bug**

- Create a DENY policy on a specific path + request header.
- Try accessing any non http service.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istio: 1.6.2
kubernetes (eks): 1.16
helm: 3.2.4

**How was Istio installed?**

We are using the istio operator.

**Environment where bug was observed (cloud vendor, OS, etc)**

amazon eks.

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
