### ISSUE TITLE
Resolution NONE stopped working for HTTPS/TLS ServiceEntries

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#25844]
**Bug description**

Resolution NONE stopped working for HTTPS/TLS ServiceEntries.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
Egress traffic control should work with HTTPS ServiceEntries with resolution NONE.

**Steps to reproduce the bug**

Set outbound traffic policy to REGISTRY_ONLY:

1. `kubectl patch istiooperator installed-state -n istio-system --type='json' -p='[{"op": "replace", "path": "/spec/meshConfig/outboundTrafficPolicy/mode", "value": "REGISTRY_ONLY"}]'`

Create a service entry for google.com as in https://preliminary.istio.io/latest/docs/tasks/traffic-management/egress/egress-control/#access-an-external-https-service, but with resolution `NONE`:

```
kubectl apply -f - <<EOF
    apiVersion: networking.istio.io/v1alpha3
    kind: ServiceEntry
    metadata:
      name: google
    spec:
      hosts:
      - www.google.com
      ports:
      - number: 443
        name: https
        protocol: HTTPS
      resolution: NONE
      location: MESH_EXTERNAL
EOF
```

1.  Send a request to google.com:

`kubectl exec -it $SOURCE_POD -c sleep -- curl -I https://www.google.com`

```
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.google.com:443 
command terminated with exit code 35
```

I checked the listeners - there is no listener for `0.0.0.0_443`.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
istioctl version --remote
client version: 1.7.0-alpha.1
control plane version: 1.7.0-alpha.1-cd46a166947eac363380c3aa3523b26a8c391f98
data plane version: 1.7.0-alpha.1 (3 proxies)
```

**How was Istio installed?**

`istioctl istioctl install --set profile=demo`

**Environment where bug was observed (cloud vendor, OS, etc)**
IBM IKS
