### ISSUE TITLE
nil pointer error with `istioctl verify-install` on v1.6.x

### ISSUE THREAD

**Issue by phenixblue** [istio/istio#25848]
**Bug description**

Getting a nil pointer error exception when running `istioctl verify-install -f my-cool-istio-overlay.yaml`

This seems to only be the case when a config overlay is passed. If I use the default profile with no overlays, I get no error.

I've tested this with istioctl v1.6.3, v1.6.4, and v1.6.5 and it's been consistent

I saw there was a recent change to the way helm chart values get merged, so wondering if this is related.

Possibly related to #25194 and #25830

Here's the exact error:

```
Error: template: istio-discovery/templates/telemetryv2_1.6.yaml:147:56: executing "istio-discovery/templates/telemetryv2_1.6.yaml" at <.Values.global.multiCluster.clusterName>: nil pointer evaluating interface {}.clusterName, template: istio-ingress/templates/service.yaml:38:12: executing "istio-ingress/templates/service.yaml" at <$.Values.global.meshExpansion.enabled>: nil pointer evaluating interface {}.enabled, template: istio-egress/templates/poddisruptionbudget.yaml:1:14: executing "istio-egress/templates/poddisruptionbudget.yaml" at <.Values.global.defaultPodDisruptionBudget.enabled>: nil pointer evaluating interface {}.enabled, template: prometheus/templates/deployment.yaml:59:76: executing "prometheus/templates/deployment.yaml" at <.Values.meshConfig.enablePrometheusMerge>: nil pointer evaluating interface {}.enablePrometheusMerge
```

Here's the istio operator config:

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  addonComponents:
    grafana:
      enabled: true
      k8s:
        replicaCount: 2
        overlays:
          - kind: Deployment
            name: grafana
            patches:
              - path: spec.template.metadata.labels.release
                value: "istio"
    prometheus:
      enabled: true
    tracing:
      enabled: true
    kiali:
      enabled: true
      k8s:
        replicaCount: 2
  components:
    pilot:
      enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2
    egressGateways:
    - enabled: true
      k8s:
        replicaCount: 3
        hpaSpec:
          minReplicas: 3
    ingressGateways:
    - enabled: true
      k8s:
        hpaSpec:
          minReplicas: 3
        service:
          ports:
          - name: https
            nodePort: 30100
            port: 443
          type: NodePort
        replicaCount: 3
    nodeAgent:
      enabled: true
      k8s:
        env:
        - name: CA_ADDR
          value: istio-citadel:8060
        - name: CA_PROVIDER
          value: Citadel
    sidecarInjector:
      enabled: true
      k8s:
        replicaCount: 2
      spec:
        rewriteAppHTTPProbe: true
    galley:
      enabled: true
      k8s:
        replicaCount: 2
    citadel:
      enabled: true
  values:
    grafana:
      security:
        enabled: true
```

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

It should verify the installation based on the provided overlay config

**Steps to reproduce the bug**

- Install Istio v1.6.x with a configuration overlay
- Run `istioctl verify-install -f my-cool-istio-overlay.yaml`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ istioctl version --remote
client version: 1.6.5
control plane version: 1.6.4
data plane version: 1.6.4 (15 proxies), 1.6.1 (3 proxies)
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

Using `istioctl` with config overlay

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
