### ISSUE TITLE
Tracing (to lightstep): allow to enable in per-pod proxy config, allow to get token via secret; outdated documentation:

### ISSUE THREAD

**Issue by devkid** [istio/istio#25841]
**Describe the feature request**

Currently I need to specify the following options for the operator to enable tracing to Lightstep:
```yaml
spec:
  values:
    global:
      proxy:
        tracer: lightstep
    meshConfig:
      enableTracing: true
      defaultConfig:
        tracing:
          lightstep:
            address: '<address>'
            accessToken: '<token>'
          tlsSettings: ...
```

Via the per-pod annotation `proxy.istio.io/config` I can only overwrite what's under `spec.meshConfig.defaultConfig`, so I can't enable / disable tracing and I can't chose the tracer per pod. I would like to be able to do this. Also, it should be possible to specify that the `accessToken` should be retrieved / mounted from a Kubernetes `Secret`.

Also, since #23220 the documentation [here](https://istio.io/latest/docs/tasks/observability/distributed-tracing/lightstep/) is outdated (the TLS / CA options now need to go under `tlsSettings`).

**Describe alternatives you've considered**

I was successful in providing dummy values for the `address` and `accessToken` fields in the mesh config and overwrite these with the real values in the per-pod annotation (leaving the `tracing` section empty makes `istiod` crash). However, then istio-proxy (in pods that don't have the overwritten values) on every request tries to connect to some dummy IP to send traces, which is less than optimal. Also, this doesn't allow to choose the tracer per-pod.

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
