### ISSUE TITLE
Wrong URL reported by global.istiod.enableAnalysis

### ISSUE THREAD

**Issue by esnible** [istio/istio#25852]
For example, I do `kubectl get vs ratings -o yaml` and see 
```
<the virtual service yaml>
status:
  validationMessages:
  - code: IST0101
    documentation_url: https://istio.io/docs/reference/config/analysis/IST0101?ref=status-controller
    level: Error
    message: 'Referenced gateway not found: "bogus-gateway"'
```

The problem is the `documentation_url`.  It should be https://preliminary.istio.io/latest/docs/reference/config/analysis/ist0101 , with a 'latest' in the URL.

To reproduce, first install 1.7 using `istioctl install --set values.global.istiod.enableAnalysis=true`

Then create a bogus CR:
```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ratings
  namespace: default
spec:
  gateways:
  - bogus-gateway
  hosts:
  - ratings
  http:
  - route:
    - destination:
        host: ratings
        subset: v1
EOF
```

@therealmitchconnors @frankbu Is the problem the URLs being reported (to be fixed by UX) or the URLs being incorrect (to be fixed by Docs?)
