### ISSUE TITLE
Error on internal communication by gateway

### ISSUE THREAD

**Issue by mcdemir** [istio/istio#25862]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
I setup istio v1.6.5 on azure kubernetes v17.7.7
I configure gateway, virtualservices, destinationrules(I will share yaml files below) and allow https and http communications. It was perfectly work with https but not http. I always get 404 not found

but v1.5.4, v1.5.8 works with same configuration.
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: prod-gateway
  namespace: namespace1
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      credentialName: ingress-cert
      mode: SIMPLE
      credentialName: ingress-cert # This should match the Certifcate secretName
    hosts:
    - PUBLIC_DOMAIN
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - INTERNALKUBERNETESSERVICE
```
This config for my internal domain points to ingressgateway in istio-system namespace
```
kind: Service
apiVersion: v1
metadata:
  name: INTERNALKUBERNETESSERVICE
  namespace: istio-system
  labels:
    app: APP1-prod
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
```
virtual service configuration
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtualservice1
  namespace: namespace1
spec:
  hosts:
  - INTERNALKUBERNETESSERVICE
  - PUBLIC_DOMAIN
  gateways:
  - prod-gateway
  http:
  - match:
    - uri:
        prefix: /endpoint1
    route:
    - destination:
        host: service1
        subset: v1
        port:
          number: 80
    retries:
      attempts: 3
      perTryTimeout: 3s
      retryOn: gateway-error,connect-failure,refused-stream
```
in this virtual service configuration I tried to add also `- mesh` in gateways as in documentaion but not worked.
https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-control/#configuring-ingress-using-an-istio-gateway

destination rule:
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: service1-version-rule
  namespace: namespace1
spec:
  host: service1
  subsets:
  - name: v1
    labels:
      version: v1
```
---
as these configurations I can make https calls from public network and perfectly work but not in internal network. I am making curl requests from one pod. here is the results. but again I face this issue v:1.6.5 
It works in v1.5.4, v1.5.8

```
curl "http://INTERNALKUBERNETESSERVICE/endpoint1" -v
*   Trying 10.0.101.111...
* TCP_NODELAY set
* Connected to INTERNALKUBERNETESSERVICE (10.0.101.111) port 80 (#0)
> GET /endpoint1 HTTP/1.1
> Host: INTERNALKUBERNETESSERVICE
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< date: Fri, 24 Jul 2020 11:21:25 GMT
< server: envoy
< content-length: 0
< 
* Curl_http_done: called premature == 0
* Connection #0 to host INTERNALKUBERNETESSERVICE left intact
```

```
curl "https://PUBLIC_DOMAIN/endpoint1" -v
*   Trying 10.0.101.111...
* TCP_NODELAY set
* Connected to PUBLIC_DOMAIN (10.0.101.111) port 80 (#0)
> GET /endpoint1 HTTP/1.1
> Host: PUBLIC_DOMAIN
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< date: Fri, 24 Jul 2020 11:39:20 GMT
< content-type: application/json; charset=utf-8
< server: envoy
< x-envoy-upstream-service-time: 1
< transfer-encoding: chunked
< 
* Curl_http_done: called premature == 0
* Connection #0 to host PUBLIC_DOMAIN  left intact
RESULT
```

If I test service itself it also works well

```
curl "http://service1" -v

< HTTP/1.1 200 OK
< date: Fri, 24 Jul 2020 11:39:20 GMT
< content-type: application/json; charset=utf-8
< server: envoy
< x-envoy-upstream-service-time: 1
< transfer-encoding: chunked
< 
* Curl_http_done: called premature == 0
* Connection #0 to host endpoint1 left intact
RESULT
```

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[X] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

```
curl "http://INTERNALKUBERNETESSERVICE/endpoint1" -v
*   Trying 10.0.101.111...
* TCP_NODELAY set
* Connected to INTERNALKUBERNETESSERVICE (10.0.101.111) port 80 (#0)
> GET /endpoint1 HTTP/1.1
> Host: INTERNALKUBERNETESSERVICE
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< date: Fri, 24 Jul 2020 11:21:25 GMT
< server: envoy
< content-length: 0
< 
* Curl_http_done: called premature == 0
* Connection #0 to host INTERNALKUBERNETESSERVICE left intact
```
this result shouldn't be 404. it should be 200.

**Steps to reproduce the bug**
I described on above.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
client version: 1.6.5
control plane version: 1.6.5
data plane version: 1.6.5 (13 proxies)

**How was Istio installed?**
by istioctl

```
istioctl install --set values.gateways.istio-ingressgateway.sds.enabled=true --set values.global.k8sIngress.enabled=true --set values.global.k8sIngress.enableHttps=true --set values.global.k8sIngress.gatewayName=ingressgateway --force
```

**Environment where bug was observed (cloud vendor, OS, etc)**
azure, linux, kubernetes v17.7.7

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
