### ISSUE TITLE
Proxy Protocol on health check port

### ISSUE THREAD

**Issue by jgournet** [istio/istio#25875]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
Setup:
- NLB with TLS termination, and proxy protocol enabled
- proxy protocol enabled on istio with:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: proxy-protocol
  namespace: istio-system
spec:
  configPatches:
  - applyTo: LISTENER
    patch:
      operation: MERGE
      value:
        listener_filters:
        - name: envoy.listener.proxy_protocol
        - name: envoy.listener.tls_inspector
  workloadSelector:
    labels:
      istio: ingressgateway
```
- Target Group health check with HTTP test pointing to /healthz/ready, on the health check port.

Result: the AWS instances are marked as "unhealthy": the istio-ingress gateway replies with 400.

Note: if I disable proxy protocol on the target group, the instances are marked as healthy after ~30seconds.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
istio should be able to handle proxy protocol on its healthcheck port.

**Steps to reproduce the bug**
See the setup above.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
istioctl version --remote
client version: 1.5.0
control plane version: 1.5.8
data plane version: 1.5.8 (36 proxies)
```
**How was Istio installed?**
via rancher

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
