### ISSUE TITLE
EnvoyFilter is failed to do http communication with sidecar

### ISSUE THREAD

**Issue by ajoysinha** [istio/istio#25884]
istio version 1.5.4

Problem Statement : Trying to develop EnvoyFilter for external authorization. but if **http-** prefix is not added on ports.name in service.yaml file then http_connection_manger filter is not incorporate in proxyconfig [istioctl proxy-config listeners hello-world-t2-548c8d58cb-hzlxj --port 15006 -o json -n nexus-sitb] . 

hence any http communication from EnvoyFilter do not work. 

Any workaround to insert http_connection_manger without using **http-**.

My Envoy Filter
```
############################################################
# Envoy External Authorization filter that will query OPA.
############################################################
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ext-authz
  namespace: nexus-sitb
spec:
  filters:
  - insertPosition:
      index: FIRST
    listenerMatch:
      listenerType: SIDECAR_INBOUND
      listenerProtocol: HTTP
    filterType: HTTP
    filterName: "envoy.ext_authz"
    filterConfig:
      with_request_body:
        max_request_bytes: 8192
        allow_partial_message: true
      failure_mode_allow: true
      grpc_service:
        # NOTE(tsandall): when this was tested with the envoy_grpc client the gRPC
        # server was receiving check requests over HTTP 1.1. The gRPC server in
        # OPA-Istio would immediately close the connection and log that a bogus
        # preamble was sent by the client (it expected HTTP 2). Switching to the
        # google_grpc client resolved this issue.
        google_grpc:
          target_uri: 127.0.0.1:9191
          stat_prefix: "ext_authz"
```

My Service.yaml
```
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-t2
  namespace: nexus-sitb
  labels:
    app: hello-world-t2
    environment: dev
spec:
  ports:
  - port: 9898
    name: hello-world-t2
    protocol: TCP
    targetPort: 9898
  selector:
    app: hello-world-t2
    environment: dev
---

```
