### ISSUE TITLE
HYBRID DNS resolution support in ServiceEntry construct

### ISSUE THREAD

**Issue by aattuluri** [istio/istio#25898]
**Describe the feature request**
`HYBRID` DNS resolution support in ServiceEntry construct. 

Consider the following service entry:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: meshbackend-se
  namespace: admiral-sync
spec:
  addresses:
  - 240.0.10.1
  endpoints:
  - address: a7646cxxxxxxxxxxx-286260733.us-east-2.elb.amazonaws.com
    locality: us-east-2
    ports:
      http: 15443
  - address: backend-app.mesh-backend.svc.cluster.local
    locality: us-west-2
    ports:
      http: 8080
  hosts:
  - stage.backend.global
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 80
    protocol: http
  resolution: DNS
```

The above results in the following EDS generation:
```
172.20.255.51:8080         HEALTHY     OK                outbound|80||stage.backend.global
34.218.153.156:15443     HEALTHY     OK                outbound|80||stage.backend.global
35.166.124.22:15443       HEALTHY     OK                outbound|80||stage.backend.global
44.225.141.143:15443     HEALTHY     OK                outbound|80||stage.backend.global
```

where `172.20.255.51` is the Cluster IP of the service `backend-app.mesh-backend.svc.cluster.local`. 
This causes load balancing to fail as the pods are behind `172.20.255.51` and the source proxy cannot connect to them directly instead to this IP address.

**Proposal:**
While generating EDS for `cluster.local` endpoints should use the Pod IPs associated with the service (with associated labels if present on the endpoint) instead of resolving it against the DNS.

I think the implementation is straightforward given all the information necessary is already stored in Pilot, just need to treat endpoints differently based on this resolution type. 

Expected EDS:
```
10.193.224.173:8080        HEALTHY     OK                outbound|80||stage.backend.global
10.193.221.41:8080           HEALTHY     OK                outbound|80||stage.backend.global
34.218.153.156:15443      HEALTHY     OK                outbound|80||stage.backend.global
35.166.124.22:15443        HEALTHY     OK                outbound|80||stage.backend.global
44.225.141.143:15443      HEALTHY     OK                outbound|80||stage.backend.global
```

Where 10.193.224.173 and 10.193.221.41 are the pod IPs associated with `backend-app.mesh-backend.svc.cluster.local`

This use case also applies to:
i) mesh expansion where there are workload instances running both as a k8s deployment and also on the VMs
ii) gRPC load balancing

**Describe alternatives you've considered**
Using STATIC resolution and adding pod IPs which is not a scalable solution

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[X] Virtual Machine
[X] Multi Control Plane

**Additional context**

**Comment by aattuluri** [comment]
CC @jwebb49

**Comment by aattuluri** [comment]
@rshriram @hzxuzhonghu Any thoughts?

**Comment by hzxuzhonghu** [comment]
We should service selecting wles or SE select pods in this case?

**Comment by aattuluri** [comment]
@hzxuzhonghu 

I think what I am looking for is the `cluster.local endpoints` should be treated as STATIC DNS and pilot delivering those IPs in EDS, for Ex:

```yaml
-  address: backend-app.mesh-backend.svc.cluster.local
    labels:
       version: v1
    locality: us-west-2
    ports:
      http: 8080
```

Should deliver EDS with IPs of pods labeled `version: v1` if subset v1 is being used in the DR, else IPs of all pods that belong to the service `backend-app.mesh-backend.svc.cluster.local`

I think this would be similar to https://github.com/istio/istio/issues/9527 except for in this case `cluster.local` endpoints in a SE are treated similar to STATIC DNS where the IPs are delivered by Pilot based on the label filters.

**Comment by hzxuzhonghu** [comment]
>We should service selecting wles or SE select pods in this case?

What i mean is you can declare a SE with workload selector and it can select the workloadentry and pods

The labels here is not to select endpoints, it is used to be selected by workload selector of SE. I donot think we want to change the semantics.

**Comment by iandyh** [comment]
@hzxuzhonghu I think what @aattuluri means is that, given a host, let's say `foo.global`, Envoy sidecar should be able to send the traffic based on locality or weight configured in the `ServiceEntry`.

According to docs

> Only one of endpoints or workloadSelector can be specified.

I don't see how `workloadSelector` can help in this case as we need the config like below:

```
  endpoints:
  - address: a7646cxxxxxxxxxxx-286260733.us-east-2.elb.amazonaws.com
    locality: us-east-2
    ports:
      http: 15443
  - address: backend-app.mesh-backend.svc.cluster.local
    locality: us-west-2
    ports:
      http: 8080
```

**Comment by hzxuzhonghu** [comment]
>I  don't see how workloadSelector can help in this case as we need the config like below:

I will answer this one first:
you just need a serviceentry with label selector and define a WorkloadEntry for `a7646cxxxxxxxxxxx-286260733.us-east-2.elb.amazonaws.com`. Thus istio will mark both `a7646cxxxxxxxxxxx-286260733.us-east-2.elb.amazonaws.com` and `backend-app` pods as its endpoints

>Envoy sidecar should be able to send the traffic based on locality or weight configured in the ServiceEntry.

For this, workloadentry allows setting weight, but i donot think we can do that for a pod. If we do have the use case, we can provide a way to do that.

**Comment by iandyh** [comment]
@hzxuzhonghu Thanks for the great suggestion. After playing it, it's working with no issues. 

Currently, we don't have the requirement for assigning weights to pod level.

**Comment by hzxuzhonghu** [comment]
Ok, that's great. So i think we can close this issue

**Comment by aattuluri** [comment]
@hzxuzhonghu Thanks for your responses, I think this should suffice, I will reopen if we need a feature not supported.

**Comment by aattuluri** [comment]
> @hzxuzhonghu Thanks for the great suggestion. After playing it, it's working with no issues.
> 
> Currently, we don't have the requirement for assigning weights to pod level.

Were you able to get loadbalancing across pods with this approach? If so, admiral can switch to this approach if a cluster has Istio 1.6, WDUT?

**Comment by iandyh** [comment]
@aattuluri Yes, I can see the stats per endpoint which means the pod native load balancing is happening inside Envoy. mTLS also has no issues.

**Comment by aattuluri** [comment]
Perfect!

**Comment by l8huang** [comment]
> For this, workloadentry allows setting weight, but i donot think we can do that for a pod. If we do have the use case, we can provide a way to do that.

@hzxuzhonghu We have a use case for traffic splitting, for example, forward 80% requests to pods  and 20% to WorkloadEntry.  As you mentioned, pods' weight can't be set, so we can't archive that. Setting pods' weight could be a useful feature, WDUT?

**Comment by l8huang** [comment]
@aattuluri When `ServiceEntry`'s `resolution` is `DNS`, the generated Envoy cluster type is `STRICT_DNS`, not `EDS`, right? I'm a little confused because you mentioned `EDS generation`.

**Comment by iandyh** [comment]
@hzxuzhonghu Hello. While i was writing some docs internally, I try to finish the setup in Istio 1.7.0 but notice some issues. Just for double check, could you confirm this is the correct configuration:

```
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: remote-service
spec:
  address: 10.0.0.1
  locality: others
  ports:
    http-sample: 80
  labels:
    app: sample-app
```

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: multi-cluster-demo
spec:
  hosts:
  - sample.global.domain
  location: MESH_INTERNAL
  ports:
  - name: http-sample
    number: 80
    protocol: http
  resolution: STATIC
  workloadSelector:
    labels:
      app: sample-app
```

In Istio 1.7.0, I don't see the endpoint gets pushed into sidecar. The cluster is there but the endpoint list is empty. (This is actually a different behavoiur with 1.6.8, in 1.6.8, I have other funky results which I am trying to find out why by looking at source code)
