### ISSUE TITLE
istioctl gateway port options merging incorrect

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#25919]
Apply spec:

```yaml
components:
  ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        service:
          ports:
            - port: 31400
              name: tcp
```

Output:
```yaml
  ports:
  - name: tcp
    nodePort: 31316
    port: 31400
  - name: tcp-istiod
    nodePort: 32629
    port: 15012
  - name: tcp-dns-tls
    nodePort: 31748
    port: 853
    targetPort: 8853
```

It removes some ports and keeps others
