### ISSUE TITLE
gRPC - Log Request/Response Metadata using lua filter

### ISSUE THREAD

**Issue by ashoke-cube** [istio/istio#25981]
I am trying to log the request/response metadata for gRPC requests. I am using the route-guide gRPC service. I am able to access the service and get the response, but I do not find the lua filter getting executed as I do not find any log message that I have as part of the lua filter code.

This the YAML config I am using.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: test-lua
  namespace: staging-as
  labels:
    app: route-guide
spec:
  workloadLabels:
    component: route-server
    namespace: staging-as
  filters:
  - listenerMatch:
      #portNumber: 8080
      listenerType: SIDECAR_INBOUND
      listenerProtocol: HTTP
    insertPosition:
      index: FIRST
    filterName: envoy.lua
    filterType: HTTP
    filterConfig:
      inlineCode: |
                function envoy_on_response(response_handle)
                  print ("**********************")
                  request_handle:logInfo("Envoy request");
                end
                function envoy_on_request(request_handle)
                  print ("**********************")
                  response_handle:logInfo("Envoy response");
                end
```

I only find the following log message in the istio-proxy container.

[2020-07-30T19:09:14.636Z] "- - -" 0 - "-" "-" 1383 5347 10805 - "-" "-" "-" "-" "127.0.0.1:8980" inbound|8980||route-guide-service.staging-as.svc.cluster.local 127.0.0.1:42810 100.96.14.229:8980 100.96.14.1:63350 - -

Could you please let me know if the config is right?
