### ISSUE TITLE
TLS: Session resumption IDs assigned but not accepted

### ISSUE THREAD

**Issue by gertvdijk** [istio/istio#26009]
**Bug description**

Recently I've upgraded Istio from 1.4.7 to 1.6.6. An SSL Labs server tests now shows a warning on the bottom of the page in the "Protocol Details" section; "Session resumption (caching)": "No (IDs assigned but not accepted)".

![Screenshot_20200731_143630](https://user-images.githubusercontent.com/1550527/89035696-ab60cb00-d33b-11ea-8b4c-c5ceb524ac8e.png)

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

I'd expect it to be all green on SSL Labs with a modern TLS configuration. Either assign session IDs or not, and if you do, accept them later as session cache.

**Steps to reproduce the bug**

1. Deploy Istio with a `Gateway` that has `tls_mode` enabled (e.g. SIMPLE, see below for my config with a slightly customized TLS config, but nothing that should break anything, right?).
2. Run SSL Lab's Server analyzer. https://www.ssllabs.com/ssltest/

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  labels:
    release: istio
  name: ingressgateway-mygateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - mynamespace/sub.domain.tld
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - mynamespace/sub.domain.tld
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      cipherSuites:
      - '[ECDHE-ECDSA-AES128-GCM-SHA256|ECDHE-ECDSA-CHACHA20-POLY1305]'
      - '[ECDHE-RSA-AES128-GCM-SHA256|ECDHE-RSA-CHACHA20-POLY1305]'
      - ECDHE-ECDSA-AES256-GCM-SHA384
      - ECDHE-RSA-AES256-GCM-SHA384
      credentialName: my-credential
      minProtocolVersion: TLSV1_2
      mode: SIMPLE
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
$ istioctl --kubeconfig ~/.kube/config-mycluster version --remote
client version: 1.6.6
control plane version: 1.6.6
data plane version: 1.6.6 (18 proxies)
```
```
$ kubectl --kubeconfig ~/.kube/config-mycluster version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:44:03Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:36:15Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

```
$ istioctl manifest generate -f myprofile.yaml | kubectl --kubeconfig ~/.kube/config-mycluster apply
```

With `myprofile.yaml`:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    # Trusted networking cluster; save resources by disabling mTLS.
    enableAutoMtls: false
  values:
    global:
      proxy:
        # Do not auto-inject sidecar, but require:
        # - the namespace of the Deployment/Pod to have a label istio-injection = enabled.
        # - an annotation to be set on the Deployment/Pod (sidecar.istio.io/inject: "true")
        # See for more info: https://istio.io/latest/docs/ops/configuration/mesh/injection-concepts/
        autoInject: disabled
  addonComponents:
    prometheus:
      enabled: false
  components:
    ingressGateways:
      # A default but small scale Ingress gateway, with HTTP & HTTPS on NodePorts 31002 & 31005 respectively.
      - name: istio-ingressgateway
        enabled: true
        k8s:
          hpaSpec:
            minReplicas: 1
            maxReplicas: 2
          strategy:
            rollingUpdate:
              maxSurge: 100%
              maxUnavailable: 50%
          service:
            ports:
              - name: status-port
                port: 15021
                targetPort: 15021
              - name: http2
                port: 80
                targetPort: 8080
                nodePort: 31002
              - name: https
                port: 443
                targetPort: 8443
                nodePort: 31005
              - name: tls
                port: 15443
                targetPort: 15443
      # A second Ingress gateway, [omitted]
```

**Environment where bug was observed (cloud vendor, OS, etc)**

kubeadm-installed self-managed cluster.

I'm happy to provide a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) if needed.
