### ISSUE TITLE
gRPC - Istio 1.38 EnvoyFilter not working

### ISSUE THREAD

**Issue by ashoke-cube** [istio/istio#26018]
**Bug description**
I am using the following Lua filter to log request/response data. But the Lua filter doesn't seem to be executed.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: lua-test
  namespace: staging-as
spec:
  workloadSelector:
    labels:
      app: route-guide
      component: route-server
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        #portNumber: 8980
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "mixer"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.lua
        config:
          inline_code: |
            function envoy_on_request(handle)
              handle:logWarn("DEBUG REQUEST")
              print ("**********************")
              handle:logInfo("Envoy request");
            end
            function envoy_on_response(handle)
              handle:logWarn("DEBUG RESPONSE")
              print ("**********************")
              handle:logInfo("Envoy response");
            end
```

I get only the following log message after the gRPC client completes receiving its response from gRPC service

`[2020-07-31T16:43:28.410Z] "- - -" 0 - "-" "-" 1400 5804 8980 - "-" "-" "-" "-" "127.0.0.1:8980" inbound|8980||route-guide-service.staging-as.svc.cluster.local 127.0.0.1:58936 100.96.14.229:8980 172.20.60.44:22380 - -`

I tried adding the below 
```
       typed_config:
         "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager"
```

but got this error:
`admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: envoy filter: can't unmarshal Any nested proto *v2.HttpConnectionManager: unknown field "inlineCode" in v2.HttpConnectionManager`

I already raised issue [#25981](https://github.com/istio/istio/issues/25981), but pre-maturely closed as duplicate.

gRPC service is running in port 8980 in Kubernetes. The following is the service+deployment info

```
apiVersion: v1
kind: Service
metadata:
  name: route-guide-service
  namespace: staging-as
  labels:
    app: route-guide
    component: route-server
spec:
  type: LoadBalancer
  ports:
  - port: 8980
    protocol: TCP
    targetPort: 8980
  selector:
    component: route-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: staging-as
spec:
  replicas: 1
  selector:
    matchLabels:
      component: route-server
  template:
    metadata:
      labels:
        app: route-guide
        component: route-server
        namespace: staging-as
    spec:
      containers:
      - name: route-guide
        image: cubeiocorp/grpc-route-guide-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8980
```

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
The log messages in the envoy_on_request/envoy_on_response to be executed.

**Steps to reproduce the bug**
Apply the config shared and send a gRPC request.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Istio version - 1.3.8

`kubectl version` displays the following:

`Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:34Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10", GitCommit:"37d169313237cb4ceb2cc4bef300f2ae3053c1a2", GitTreeState:"clean", BuildDate:"2019-08-19T10:44:49Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}`

**How was Istio installed?**
Using docker image 
docker.io/istio/proxyv2:1.3.8

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS
