### ISSUE TITLE
hpaSpec and values required to set istiod HPA

### ISSUE THREAD

**Issue by liamawhite** [istio/istio#26020]
[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

When setting just the `hpaSpec` and nothing in values in the `IstioOperator` resource I expect an HPA to get created. Setting just an `hpaSpec` works for gateways.

The reason it doesn't is that the HPA isn't created at all so there is nothing to overlay with the translator. [This](https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/templates/autoscale.yaml#L1) is the offending line.

```
2020-07-31T17:50:13.730052Z	info	translator	resource Kind:name HorizontalPodAutoscaler:istiod doesn't exist in the output manifest, skip overlay.
```

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiocontrolplane
  namespace: istio-system
spec:
  components:
    pilot:
      k8s:
       hpaSpec:
         maxReplicas: 10
         metrics:
         - resource:
           name: cpu
           targetAverageUtilization: 75
           type: Resource
         minReplicas: 1
         scaleTargetRef:
           apiVersion: extensions/v1beta1
           kind: Deployment
           name: istiod
```

**Comment by morvencao** [comment]
HPA is by default enabled, I think the cause for your issue should be the indention issue at `resource`, please try with the following yaml:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiocontrolplane
  namespace: istio-system
spec:
  components:
    pilot:
      k8s:
       hpaSpec:
         maxReplicas: 10
         metrics:
         - resource:
             name: cpu
             targetAverageUtilization: 75
           type: Resource
         minReplicas: 1
         scaleTargetRef:
           apiVersion: extensions/v1beta1
           kind: Deployment
           name: istiod
```
