### ISSUE TITLE
Over 30k VirtualService configurations Cause all SideCar OOM

### ISSUE THREAD

**Issue by liuzheng** [istio/istio#26060]
**Bug description**
I am tested the profmance about the configurations, I think that is a design issue.
Over 30k VirtualService configurations inserted into k8s, the all istio-proxy SideCar OOM, and never alive.
I suggest using some tags to control each SideCar to load only it needed, but if it need more than 30k still die...

[ ] Docs
[ ] Installation
[ ] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
istio proxy sidecar running healthy

**Steps to reproduce the bug**
insert 30k VirtualSerivces
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-cnn-through-egress-gateway
spec:
  hosts:
  - edition.cnn.com
  gateways:
  - istio-egressgateway
  - mesh
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: cnn
        port:
          number: 80
      weight: 100
  - match:
    - gateways:
      - istio-egressgateway
      port: 80
    route:
    - destination:
        host: edition.cnn.com
        port:
          number: 80
      weight: 100
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio: 1.6.2
k8s: v1.18.2

**How was Istio installed?**
istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
