### ISSUE TITLE
ServiceEntry with DNS resolution works not correctly

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#26098]
**Bug description**

When i create the below SE and WLE

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: details-svc
spec:
  hosts:
  - details.bookinfo.com
  location: MESH_INTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
    targetPort: 8080
  resolution: DNS
  workloadSelector:
    labels:
      app: details-legacy
---  
apiVersion: networking.istio.io/v1beta1
kind: WorkloadEntry
metadata:
  name: details-svc
spec:
  # use of the service account indicates that the workload has a
  # sidecar proxy bootstrapped with this service account. Pods with
  # sidecars will automatically communicate with the workload using
  # istio mutual TLS.
  serviceAccount: details-legacy
  address: vm1.vpc01.corp.net
  labels:
    app: details-legacy
    instance-id: vm1
```
I got the below cluster
```
        "name": "outbound|80||details.bookinfo.com",
        "type": "STRICT_DNS",
        "connectTimeout": "10s",
        "loadAssignment": {
            "clusterName": "outbound|80||details.bookinfo.com",
            "endpoints": [
                {
                    "locality": {},
                    "lbEndpoints": [
                        {
                            "endpoint": {
                                "address": {
                                    "socketAddress": {
                                        "address": "details.bookinfo.com",
                                        "portValue": 80
                                    }
                                }
                            },
                            "loadBalancingWeight": 1
                        },
                        {
                            "endpoint": {
                                "address": {
                                    "socketAddress": {
                                        "address": "vm1.vpc01.corp.net",
                                        "portValue": 8080
                                    }
                                }
                            },
                            "metadata": {
                                "filterMetadata": {
                                    "envoy.transport_socket_match": {
                                        "tlsMode": "istio"
                                    }
                                }
                            },
                            "loadBalancingWeight": 1
                        }
                    ],
                    "loadBalancingWeight": 2
                }
            ]
        },

```

I expect the endpoints only include `vm1.vpc01.corp.net`

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

# istioctl version
client version: bc84cc29965752674282df8385523c3d23f899ac-dirty
control plane version: ae114df4d90253d6ebb6664ef53d81718852e594-dirty-ae114df4d90253d6ebb6664ef53d81718852e594
data plane version: 1.8-dev (5 proxies)

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by hzxuzhonghu** [comment]
And there is another bug found during this reproduction:

When i create an additional workloadentry , it does not occur in the cluster, only when a full push triggered. It is included

```
apiVersion: networking.istio.io/v1beta1
kind: WorkloadEntry
metadata:
  name: details-svc-2
spec:
  # use of the service account indicates that the workload has a
  # sidecar proxy bootstrapped with this service account. Pods with
  # sidecars will automatically communicate with the workload using
  # istio mutual TLS.
  serviceAccount: details-legacy
  address: 192.168.1.100
  labels:
    app: details-legacy
    instance-id: vm2
```
