### ISSUE TITLE
Service not getting rule on port 8080, only on 80

### ISSUE THREAD

**Issue by aroundthecode** [istio/istio#26107]
Hi there

I'm trying to upgrade from 1.0.5 to 1.2.10 (latest working on my 1.12 K8 cluster)

I configured all My DestinationRule/Virtualservice and I notice that traffic management isn't working unless i move my k8 services from port 8080 to 80.

here is my configuration 

 ```
kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: myservice-service-destination
  namespace: flcloudns
  ...
  labels:
    app: myservice-service
    buildNum: '189'
    chart: fl-mesh-1.0.0
    heritage: Tiller
    profile: ns
    release: myservice-service
spec:
  host: myservice.flcloudns.svc.cluster.local
  trafficPolicy: ~
  subsets:
    - labels:
        version: blue
      name: blue-myservice
    - labels:
        version: green
      name: green-myservice
```

```
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: myservice-service-vservice
  namespace: flcloudns
  labels:
    app: myservice-service
    heritage: Tiller
    profile: ns
    release: myservice-service
spec:
  hosts:
    - myservice.flcloudns.svc.cluster.local
  gateways: ~
  http:
    - match:
        - headers:
            myservice:
              exact: green
      route:
        - destination:
            host: myservice.flcloudns.svc.cluster.local
            subset: green-myservice
    - match:
        - headers:
            myservice:
              exact: blue
      route:
        - destination:
            host: myservice.flcloudns.svc.cluster.local
            subset: blue-myservice
    - route:
        - destination:
            host: myservice.flcloudns.svc.cluster.local
            subset: blue-myservice
  tcp: ~
  tls: ~
  exportTo: ~
 ```
```
metadata:
  name: myservice
  namespace: flcloudns
    app: myservice
    buildNum: '189'
    chart: fl-mesh-1.0.0
    heritage: Tiller
    profile: ns
    release: myservice-service
spec:
  ports:
    - name: http-web
      protocol: TCP
      port: 8080
      targetPort: http-web
  selector:
    app: myservice
    profile: ns
  clusterIP: *********
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
kind: Service
```

What am I supposed to do to have it work on port 8080? Just changing the port tom 8080 to 80 let traffig routes back to work.
No evidence of error in log nor kiali UI.
