### ISSUE TITLE
ext_authz envoy filter Downstream protocol error

### ISSUE THREAD

**Issue by JacobSMoller** [istio/istio#26116]
**Bug description**
When using the autogenerated cluster name for an external auth service, calls fail with a DPE(Downstream protocol error) flag. (Might be a duplicate of https://github.com/istio/istio/issues/21841).

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Send working ext_authz /Check call without needing to patch the name of the cluster.
**Steps to reproduce the bug**
1: Deploy a service that implements the /Check endpoint according to envoy specs. 
2: Check envoy configuration of istio-ingressgateway to see that a cluster configuration for the service has been added. (In my case called envoy-services and living in the envoy-services namespace)
  2.1  `istioctl dashboard envoy "ingress-gateway-pod-name"` 
  2.2: 
```json
"cluster": {
    "@type": "type.googleapis.com/envoy.api.v2.Cluster",
    "name": "outbound|50051||envoy-services.envoy-services.svc.cluster.local",
    "type": "EDS",
    "eds_cluster_config": {
        "eds_config": {
             "ads": {}
          },
          "service_name": "outbound|50051||envoy-services.envoy-services.svc.cluster.local"
      },...
```

3: 
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ext-authz-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        portNumber: 443
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.router"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.ext_authz
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.http.ext_authz.v2.ExtAuthz
          failure_mode_allow: false
          grpc_service:
            envoy_grpc:
              cluster_name: "outbound|50051||envoy-services.envoy-services.svc.cluster.local"
```
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```bash
istioctl version --remote
client version: 1.6.5
control plane version: 1.6.5
data plane version: 1.6.5 (13 proxies)

kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-19T13:57:45Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.11-gke.5", GitCommit:"baccd25d44f1a0d06ad3190eb508784efbb990a5", GitTreeState:"clean", BuildDate:"2020-06-25T22:55:26Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**
kubectl generated istio manifests as follows.
```
istioctl manifest generate -f istio-operator.yaml > generated.yaml
kubectl apply -f 
```

**Environment where bug was observed (cloud vendor, OS, etc)**
GCP, Unix pods running in k8s.

**Fixes** 
As mentioned in https://github.com/istio/istio/issues/21841 you can add a patch to the cluster naming, this will make the error go away.
This can be closed if its to much of a duplicate. Might be the error just surfaces in a different way in newer istio versions. But looking at it quickly the error seems to be something else.
