### ISSUE TITLE
Istio multi-cluster,  aws domain name cannot be accessed sometimes.

### ISSUE THREAD

**Issue by johnzheng1975** [istio/istio#26111]
istio 1.4.6
Kube-system coredns   602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/coredns:v1.6.6
Istio-System coredns  coredns/coredns:1.6.2    istio/coredns-plugin:0.2-istio-1.1
aws eks: 1.5

**Bug description**
I setup a multi-cluster, I configured an elb domain in service entry. 
However, sometimes the connect to elb will fail for next 5 minutes.
So I changed dnsRefreshRate from 300s to 60s, in configure map istio and istio-sidecar-injector. Now the elb will fail for next 1 minute sometimes but more frequently.
 

Here is log in coredns, why it add .global for domain?
```
[ERROR] plugin/errors: 2 a754fd45ebb504c17bba1e9ba759472b-5d84b639aeda3e81.elb.us-east-1.amazonaws.com.global. A: read udp 10.204.78.110:57603->172.20.41.175:53: i/o timeout
[ERROR] plugin/errors: 2 a754fd45ebb504c17bba1e9ba759472b-5d84b639aeda3e81.elb.us-east-1.amazonaws.com.global. A: read udp 10.204.78.110:59881->172.20.41.175:53: i/o timeout
Thanks for your help. (edited)
```

**Comment by johnzheng1975** [comment]
My service entry is:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: se-xxx-dev-core-xxx-users-service
  namespace: default
spec:
  addresses:
  - 240.0.0.58
  endpoints:
  - address: a754fd45ebb504c17bba1e9ba759472b-5d84b639aeda3e33.elb.us-east-1.amazonaws.com
    ports:
      http1: 15443
  hosts:
  - xx-dev-core-xx-users-service.xx-dev-core.global
  location: MESH_INTERNAL
  ports:
  - name: http1
    number: 80
    protocol: http
  resolution: DNS
```
