### ISSUE TITLE
having double slash in the uri match to a prefix doesnt work

### ISSUE THREAD

**Issue by pc-rshetty** [istio/istio#26133]
**Bug description**
I have defined a virtual service something like this . Some legacy clients have code which sends extra slash (//). It works file when they send /adm but doesnt work when they send //adm . I configured this rewrite rule and it doesnt seems to work. I get a http 500 on the ingress gateway logs. I am thinking if the workaround is to specify some kinda escape charachter for double slash ?

  - match:
    - uri:
        prefix: //adm
    - uri:
        prefix: /adm
    - uri:
        prefix: /
    rewrite:
      uri: "/adm"
    timeout: 120s
    route:
    - destination:
        host: adm-service
        port:
          number: {{ .Values.service.port }}

[ ] Docs
[ ] Installation
[Y ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
/adm and //adm should both route in similar way

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio 1.4.7
**How was Istio installed?**
helm
**Environment where bug was observed (cloud vendor, OS, etc)**
EKS

**Comment by howardjohn** [comment]
Why not split it up?

```yaml

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kafka
spec:
  hosts:
  - echo
  http:
  - match:
    - uri:
        prefix: //adm
    rewrite:
      uri: "/"
    timeout: 120s
    route:
    - destination:
        host: echo
        port:
          number: 8080
  - match:
    - uri:
        prefix: /adm
    rewrite:
      uri: "/"
    timeout: 120s
    route:
    - destination:
        host: echo
        port:
          number: 8080
  - match:
    - uri:
        prefix: /
    timeout: 120s
    route:
    - destination:
        host: echo
        port:
          number: 8080
```

Test:
```
$ curl echo:8080//adm -s | grep URL; curl echo:8080/adm -s | grep URL; curl echo:8080/ -s | grep URL;
URL=/
URL=/
URL=/
```
