### ISSUE TITLE
Annotation "client-max-body-size"

### ISSUE THREAD

**Issue by latios93** [istio/istio#26152]
Hi guys!

I need some help. I am migrating to istio but I think that some k8s annotations cannot be replace in a simple way.

I need the annotation "client-max-body-size" (nginx), it is used by k8s to generate a response with the 413 http code when the body size is greater than a threshold. Is there a way to replicate it in Istio?

I was thinking to replicate it with an Envoy Filter, but it's quite complicated.

I just tried to write the following code without success:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: istio-envoy-my-filter
  namespace: <my-app-namespace>
spec:
  workloadSelector:
    labels:
      app: <my-app-name>
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.router"
     patch:
       operation: INSERT_BEFORE
       value:
         name: "envoy.lua_client_max_body_size" # Here I can write the patch's name, is it correct? Or is this a name of a precompiled filter?
         config:
           inlineCode: |
              function envoy_on_request(handle)
                 local MAX_SIZE_ALLOWED = 5 * 1024 * 1024 # 5mb
                 local size = handle:body():length()
                 if size > MAX_SIZE_ALLOWED then
                    handle:respond({ [":status"] = "413" })
                 end 
              end
```

But with this, I don't see the http code 413 even if I set to 0,5 mb the max size allowed.
I tried also to use:
```
              function envoy_on_request(handle)
                 handle:respond({ [":status"] = "413" })
              end
```
but I don't see the 413 response code when I curl to the app.
Any suggestions?
