### ISSUE TITLE
enable prometheus configuration for remote write

### ISSUE THREAD

**Issue by papovyr** [istio/istio#26150]
As of right now prometheus configuration is very limited via istioctl
I have case where i need to configure prometheus to remote write to remote destination 
this is done pretty well on prometheus helm package 

it will be nice to have same capabilities to tune prometheus configuration via istioctl and use istio prometheus for monitoring

`val-prom.yaml`
```
server:
  remoteWrite:
  - url: http://remote_address
    queue_config:
      capacity: 100000
      max_shards: 1000
      max_samples_per_send: 1000
      batch_send_deadline: 5s
      min_backoff: 30ms
      max_backoff: 100ms
  basicAuth:
    username: user
    password: pass
```

```
helm upgrade --install prometheus -n prometheus stable/prometheus -f ./val-prom.yaml
```
