### ISSUE TITLE
istio k8s ingress gateway returns 503 when large number of changes pushed from istiod

### ISSUE THREAD

**Issue by darkstarmv** [istio/istio#26183]
**Bug description**
istio k8s ingress pods freeze and return `503` error code when approximately 1000 pods start for ~ 70 services at the same time.
 

[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Ingress pods should not stop serving requests while receiving updates from istiod.

**Steps to reproduce the bug**
- sidecars are not enabled, only k8s istio  ingress is enabled as default k8s cluster ingress.

I'm running steady load of about 4K rps and perform periodic scale up of application pods keeping front door load the same.  if varnish gets an error, it will retry call to the backend.

[client] --> [Varnish] --> [K8s nodeport kube-proxy]-->[ istio k8s ingress gateway]-->[app services]
1.  scale up application pods across 70 services, total of ~1000 pods
1.  Cluster autoscaler add new workers and pods get scheduled
1.  proxy starts reporting `stale` status and ingress pods may start failing readiness check
1. Ingress pod log stops moving, but no errors reported
1. istiod is very active and sometimes it shows this message `{"level":"info","time":"2020-08-05T16:55:49.512869Z","scope":"ads","msg":"ADS: \"172.28.69.65:53208\" router~172.28.0.111~istio-ingressgateway-5d978c867f-6gdtg.istio-system~istio-system.svc.cluster.local-38 terminated rpc error: code = Canceled desc = context canceled"}`
1. Varnish reports 100% `503` errors
1. approximately in 2-3 minutes everything recovers back to normal. 
1. If workers are already in place and we reduce number of simultaneously starting pods to about 500, we don't see `503` errors

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
istioctl version --remote
client version: 1.6.7
control plane version: 1.6.7
data plane version: 1.6.7 (30 proxies)

 kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:08:59Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:09:48Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

 helm version
version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}

```

**How was Istio installed?**
Istio installed using helm

**Environment where bug was observed (cloud vendor, OS, etc)**
GCE BYO K8s 

```
gateways:
  istio-ingressgateway:
    name: istio-ingressgateway
    rollingMaxSurge: 100%
    rollingMaxUnavailable: 25%
    autoscaleEnabled: true
    autoscaleMin: 30
    autoscaleMax: 100
    cpu:
      targetAverageUtilization: 50
    resources:
      requests:
        cpu: 5
        memory: 5Gi
      limits:
        cpu: 10
        memory: 10Gi
```
```
## Discovery Settings
pilot:
  autoscaleEnabled: true
  autoscaleMin: 2
  autoscaleMax: 5
  # replicaCount: 10
  rollingMaxSurge: 100%
  rollingMaxUnavailable: 25%

  # Resources for a small pilot install
  resources:
    requests:
      cpu: 5
      memory: 5Gi
    limits:
      cpu: 10
      memory: 10Gi
  cpu:
    targetAverageUtilization: 50
```
