### ISSUE TITLE
istioctl analyze errors with IST0101 when VS is referencing k8s service without SE

### ISSUE THREAD

**Issue by Kyslik** [istio/istio#26222]
**Bug description**
`istioctl analyze` errors with:

```sh
Error [IST0101] (VirtualService foo.bar-ns) Referenced host not found: "foo.foo-ns.svc.cluster.local"
```

I am not sure if `IST0101` is referencing the `spec.hosts` field or `spec.http.match.route.destination.host` field. In anycase the error seems to be invalid as in the docs it says for both fields (`.hosts` and `...destination.host`) that:

> The name of a service from the service registry. Service names are looked up from the platform’s service registry (e.g., Kubernetes services, Consul services, etc.) and from the hosts declared by ServiceEntry. Traffic forwarded to destinations that are not found in either of the two, will be dropped.

As soon as I add SE for `foo.foo-ns.svc.cluster.local` error is gone:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: foo
  namespace: bar-ns
spec:
  exportTo:
  - "."
  hosts:
  - foo.foo-ns.svc.cluster.local
  location: MESH_INTERNAL
  ports:
  - number: 8080
    name: http
    protocol: HTTP
  resolution: DNS
```

Analysis link: https://istio.io/latest/docs/reference/config/analysis/ist0101/

**Affected product area (please put an X in all that apply)**

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Expected behavior**

`istioctl analyze` should not error with IST0101 when referencing Service in different namespace.

**Steps to reproduce the bug**

Apply following manifests:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: bar-ns
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: foo-ns
---
kind: Service
apiVersion: v1
metadata:
  name: foo
  namespace: foo-ns
spec:
  selector:
    app: foo
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: foo
  namespace: bar-ns
spec:
  exportTo:
  - .
  hosts:
  - foo.foo-ns.svc.cluster.local
  http:
  - match:
    - method:
        exact: GET
      uri:
        prefix: /v1
    name: GET-/v1
    retries:
      attempts: 2
      perTryTimeout: 2s
      retryOn: gateway-error,connect-failure,retriable-status-codes
    route:
    - destination:
        host: foo.foo-ns.svc.cluster.local
        port:
          number: 8080
      headers:
        request:
          add:
            x-envoy-retriable-status-codes: 408,423
    timeout: 10s
```

and run analysis:

```sh
# for whatever reason istioctl analyze -n bar-ns times out
kubens bar-ns
istioctl analyze
Error [IST0101] (VirtualService foo.bar-ns) Referenced host not found: "foo.foo-ns.svc.cluster.local"
Error: Analyzers found issues when analyzing namespace: bar-ns.
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```sh
$ istioctl version --remote
client version: 1.6.4
control plane version: 1.5.8
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
```
helm version - not relevant

**How was Istio installed?**

`helm template`

**Environment where bug was observed (cloud vendor, OS, etc)**

Not relevant.
