### ISSUE TITLE
Unable to launch LoadBalancer type EgressGateway Service 

### ISSUE THREAD

**Issue by ramsateesh** [istio/istio#26240]
**Bug description**
Unable to launch LoadBalancer type EgressGateway Service even after overriding the values in the operator spec.

[ ] Docs
[ x ] Installation
[ x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
istio-egressgateway service of type LoadBalancer is created

**Steps to reproduce the bug**
Use below IstioOperator spec to install istio using 
```bash
istioctl manifest apply -f <below spec>
```

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-operator
spec:
  # Use the default profile as the base
  # More details at: https://istio.io/docs/setup/additional-setup/config-profiles/
  profile: default
  namespace: istio-system

  components:
    ingressGateways:
    - enabled: true
    egressGateways:
    - enabled: true
    pilot:
      enabled: true
    sidecarInjector:
      enabled: true
    telemetry:
      enabled: true
    citadel:
      enabled: true
    galley:
      enabled: true
  meshConfig:
    enableAutoMtls: true
  values:
    global:
      controlPlaneSecurityEnabled: true
    gateways:
      istio-egressgateway:
        type: LoadBalancer
```

Creates a egress service as shown below:

```bash
NAME                  TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                    AGE
istio-egressgateway   ClusterIP   10.11.206.21   <none>        80/TCP,443/TCP,15443/TCP   7d18h
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
client version: 1.5.7
control plane version: 1.5.7
data plane version: 1.5.7 (6 proxies)

**How was Istio installed?**
using istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
Azure AKS

**Comment by morvencao** [comment]
What do you expect? IP allocated for istio-egressgateway service?

**Comment by ramsateesh** [comment]
Yes.

**Comment by morvencao** [comment]
The loadbalancer IP depends on your cloud provider, it's not an issue of istio.

**Comment by ramsateesh** [comment]
istio-egressgateway service created is of ClusterIP type instead of LoadBalancer type.

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    ...
  labels:
    app: istio-egressgateway
    istio: egressgateway
    operator.istio.io/component: EgressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.5.7
    release: istio
  name: istio-egressgateway
  namespace: istio-system
spec:
  clusterIP: 10.11.206.21
  ports:
  - name: http2
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: tls
    port: 15443
    protocol: TCP
    targetPort: 15443
  selector:
    app: istio-egressgateway
    istio: egressgateway
  sessionAffinity: None
  type: ClusterIP
```

This is output from my cluster, and the service type is ClusterIP.  Ingress Gateway service was defined to be LoadBalancer and External IP was created by the cloud provider and assigned to the service.

**Comment by morvencao** [comment]
You should use k8s resource overlay to set the service type instead of helm values:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-operator
spec:
  # Use the default profile as the base
  # More details at: https://istio.io/docs/setup/additional-setup/config-profiles/
  profile: default
  namespace: istio-system

  components:
    ingressGateways:
    - enabled: true
    egressGateways:
    - enabled: true
      k8s:
        overlays:
        - kind: Service
          name: istio-egressgateway
          patches:
          - path: spec.type
            value: LoadBalancer
    pilot:
      enabled: true
    sidecarInjector:
      enabled: true
    telemetry:
      enabled: true
    citadel:
      enabled: true
    galley:
      enabled: true
  meshConfig:
    enableAutoMtls: true
  values:
    global:
      controlPlaneSecurityEnabled: true
```
