### ISSUE TITLE
[1.7] Add jaeger-collector in sample addons?

### ISSUE THREAD

**Issue by jotak** [istio/istio#26256]
**Describe the feature request**

In the 1.7 alpha2, there is no out-of-the-box jaeger collector service exposed for receiving application traces. It seems to me that the demo profile + sample addons are there to ease the user experience, so I think it would be nice if it was exposed.

For example, just add this to `samples/addons/jaeger.yaml`

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: istio-system
  labels:
    app: jaeger
spec:
  type: ClusterIP
  ports:
    - name: http-query
      port: 80
      protocol: TCP
      targetPort: 14268
  selector:
    app: jaeger
```

(I can open a PR if it's agreed)

**Describe alternatives you've considered**

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**
