### ISSUE TITLE
Can not add a new label to already existing prometheus metric requestcount

### ISSUE THREAD

**Issue by grvcurefit** [istio/istio#26262]
**Bug description**
Can not add a new label to the `requestcount` metric in prometheus

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Prometheus evaluates the new label being added
**Steps to reproduce the bug**
I'm trying to add a new label `source_ip` to the prometheus metric `requestcount`
I've added the attribute to prom handler

```
params:
    metrics:
    - instance_name: requestcount.instance.istio-system
      kind: COUNTER
      label_names:
      - reporter
      - source_ip
      - source_app
```
and added a dimension to requestcount instance

```
compiledTemplate: metric
  params:
    dimensions:
      reporter: conditional((context.reporter.kind | "inbound") == "outbound", "source", "destination")
      source_app: source.labels["app"] | "unknown"
      source_ip: source.ip | "unknown"
```
and added an attribute_binding to the attributes instance

```
spec:
  attributeBindings:
    destination.workload.namespace: $out.destination_workload_namespace | "unknown"
    destination.workload.uid: $out.destination_workload_uid | "unknown"
    source.ip: $out.source_pod_ip | ip("0.0.0.0")
```
yet, `source_ip` label is not included in the `istio_request_total` metric reported by prometheus.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
`istioctl version --remote
client version: 1.6.7
control plane version: 1.5.2
data plane version: 1.5.2 (128 proxies)

`kubectl version`
1.18.3

**How was Istio installed?**
istioctl 
**Environment where bug was observed (cloud vendor, OS, etc)**
aws-eks cluster

**Comment by bianpengyuan** [comment]
The type of source.ip is `IP_ADDRESS`, but this expression `source.ip | "unknown"` assumes the type to be string. If you look at your istio-telemetry pod log you should be see error log about wrong expression. I would suggest to update the expression to `source_ip: source.ip | ip("0.0.0.0")` and use `"0.0.0.0"` to represent `unknown`.

Note mixer is going to be removed by 1.8, so please consider switching to telemetry v2. Starting from 1.5, we have supported metric customization and many improvement has been made on this feature as well in 1.6: https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/

**Comment by grvcurefit** [comment]
I tried replacing it with `ip("0.0.0.0")`, still no luck, the new label doesn't show up. I have already disabled mixer, so there's no telemetry pod, will these logs be available in proxy sidecar?
I tried going through the sidecar logs, didn't see any error as such.

**Comment by bianpengyuan** [comment]
@grvcurefit Sorry I am confused. The configuration you edited (instance, handler) are consumed by Mixer. If mixer is disabled, they are not effective for sure.

I guess the metrics you are looking at are generated by telemetry v2, so to customize those metrics, you need to follow this guide: https://istio.io/v1.5/docs/reference/config/telemetry/configurable_metrics/  Note, metric customization support in 1.5 is experimental. 1.6 support for metric customization is more solid: https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/

**Comment by grvcurefit** [comment]
@bianpengyuan Thanks for pointing it out, I didn't realize that instance, handler, etc were part of mixer itself.

I tried to follow the documentation that you shared. This is what my [stats filter](https://pastebin.com/yJQfrPGM) looks like.
And annotated the deployment as well:
```
spec:
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: '2020-05-06T22:03:39+05:30'
        sidecar.istio.io/extraStatTags: source_ip
        sidecar.istio.io/interceptionMode: TPROXY
        traffic.sidecar.istio.io/includeOutboundIPRanges: '*'
```

But even this does not seem to solve the problem.
