### ISSUE TITLE
VirtualService on Istio 1.4.x generates different config than Istio 1.5.x

### ISSUE THREAD

**Issue by Kyslik** [istio/istio#26263]
**Bug description**

Given VS:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: bar
  namespace: foo-ns
spec:
  exportTo: 
    - "."
  hosts:
    - bar.bar-ns.svc.cluster.local
  http:
    - name: GET-/
      match:
        - uri:
            prefix: /
          method:
            exact: GET
      route:
        - destination:
            host: bar.bar-ns.svc.cluster.local
            port:
              number: 8080
          headers:
            request:
              add:
                x-envoy-retriable-status-codes: "408,423"
      timeout: 4s
      retries: 
        attempts: 3
        perTryTimeout: 1s
        retryOn: gateway-error,connect-failure,retriable-status-codes
    - name: provider-global-default
      route:
        - destination:
            host: bar.bar-ns.svc.cluster.local
            port:
              number: 8080
```

When we compare _config_dump_ between the two versions (Istio 1.4.x and 1.5.x) we can see that `provider-global-default` route is missing in the 1.5.x dump. Routes with name `GET-/` are present in both.

<details>
  <summary>1.5 portion of dump (click to expand):</summary>
  
```json
"routes": [
    {
    "match": {
    "prefix": "/",
    "case_sensitive": true,
    "headers": [
    {
        "name": ":method",
        "exact_match": "GET"
    }
    ]
    },
    "route": {
    "cluster": "outbound|8080||foo.foo-ns.svc.cluster.local",
    "timeout": "4s",
    "retry_policy": {
    "retry_on": "gateway-error,connect-failure,retriable-status-codes",
    "num_retries": 3,
    "per_try_timeout": "1s",
    "retry_host_predicate": [
        {
        "name": "envoy.retry_host_predicates.previous_hosts"
        }
    ],
    "host_selection_retry_max_attempts": "5"
    },
    "max_grpc_timeout": "4s"
    },
    "metadata": {
    "filter_metadata": {
    "istio": {
        "config": "/apis/networking.istio.io/v1alpha3/namespaces/bar/virtual-service/foo"
    }
    }
    },
    "decorator": {
    "operation": "foo.foo-ns.svc.cluster.local:8080/*"
    },
    "request_headers_to_add": [
    {
    "header": {
        "key": "x-envoy-retriable-status-codes",
        "value": "408,423"
    },
    "append": true
    }
    ],
    "typed_per_filter_config": {
    "mixer": {
    "@type": "type.googleapis.com/istio.mixer.v1.config.client.ServiceConfig",
    "disable_check_calls": true,
    "mixer_attributes": {
        "attributes": {
        "destination.service.host": {
        "string_value": "foo.foo-ns.svc.cluster.local"
        },
        "destination.service.name": {
        "string_value": "foo"
        },
        "destination.service.namespace": {
        "string_value": "foo-ns"
        },
        "destination.service.uid": {
        "string_value": "istio://foo-ns/services/foo"
        }
        }
    },
    "forward_attributes": {
        "attributes": {
        "destination.service.host": {
        "string_value": "foo.foo-ns.svc.cluster.local"
        },
        "destination.service.name": {
        "string_value": "foo"
        },
        "destination.service.namespace": {
        "string_value": "foo-ns"
        },
        "destination.service.uid": {
        "string_value": "istio://foo-ns/services/foo"
        }
        }
    }
    }
    },
    "name": "GET-/"
    }
]
}
```
</details>

<details>
  <summary>1.4 portion of dump (click to expand)</summary>
  
```json
"routes": [
    {
    "match": {
    "prefix": "/",
    "case_sensitive": true,
    "headers": [
    {
        "name": ":method",
        "exact_match": "GET"
    }
    ]
    },
    "route": {
    "cluster": "outbound|8080||foo.foo-ns.svc.cluster.local",
    "timeout": "4s",
    "retry_policy": {
    "retry_on": "gateway-error,connect-failure,retriable-status-codes",
    "num_retries": 3,
    "per_try_timeout": "1s",
    "retry_host_predicate": [
        {
        "name": "envoy.retry_host_predicates.previous_hosts"
        }
    ],
    "host_selection_retry_max_attempts": "5"
    },
    "max_grpc_timeout": "4s"
    },
    "metadata": {
    "filter_metadata": {
    "istio": {
        "config": "/apis/networking/v1alpha3/namespaces/bar/virtual-service/foo"
    }
    }
    },
    "decorator": {
    "operation": "foo.foo-ns.svc.cluster.local:8080/*"
    },
    "request_headers_to_add": [
    {
    "header": {
        "key": "x-envoy-retriable-status-codes",
        "value": "408,423"
    },
    "append": true
    }
    ],
    "typed_per_filter_config": {
    "mixer": {
    "@type": "type.googleapis.com/istio.mixer.v1.config.client.ServiceConfig",
    "disable_check_calls": true,
    "mixer_attributes": {
        "attributes": {
        "destination.service.host": {
        "string_value": "foo.foo-ns.svc.cluster.local"
        },
        "destination.service.name": {
        "string_value": "foo"
        },
        "destination.service.namespace": {
        "string_value": "foo-ns"
        },
        "destination.service.uid": {
        "string_value": "istio://foo-ns/services/foo"
        }
        }
    },
    "forward_attributes": {
        "attributes": {
        "destination.service.host": {
        "string_value": "foo.foo-ns.svc.cluster.local"
        },
        "destination.service.name": {
        "string_value": "foo"
        },
        "destination.service.namespace": {
        "string_value": "foo-ns"
        },
        "destination.service.uid": {
        "string_value": "istio://foo-ns/services/foo"
        }
        }
    }
    }
    },
    "name": "GET-/"
    },
    {
    "match": {
    "prefix": "/"
    },
    "route": {
    "cluster": "outbound|8080||foo.foo-ns.svc.cluster.local",
    "timeout": "0s",
    "retry_policy": {
    "retry_on": "connect-failure,refused-stream,unavailable,cancelled,resource-exhausted,retriable-status-codes",
    "num_retries": 2,
    "retry_host_predicate": [
        {
        "name": "envoy.retry_host_predicates.previous_hosts"
        }
    ],
    "host_selection_retry_max_attempts": "5",
    "retriable_status_codes": [
        503
    ]
    },
    "max_grpc_timeout": "0s"
    },
    "metadata": {
    "filter_metadata": {
    "istio": {
        "config": "/apis/networking/v1alpha3/namespaces/bar/virtual-service/foo"
    }
    }
    },
    "decorator": {
    "operation": "foo.foo-ns.svc.cluster.local:8080/*"
    },
    "typed_per_filter_config": {
    "mixer": {
    "@type": "type.googleapis.com/istio.mixer.v1.config.client.ServiceConfig",
    "disable_check_calls": true,
    "mixer_attributes": {
        "attributes": {
        "destination.service.host": {
        "string_value": "foo.foo-ns.svc.cluster.local"
        },
        "destination.service.name": {
        "string_value": "foo"
        },
        "destination.service.namespace": {
        "string_value": "foo-ns"
        },
        "destination.service.uid": {
        "string_value": "istio://foo-ns/services/foo"
        }
        }
    },
    "forward_attributes": {
        "attributes": {
        "destination.service.host": {
        "string_value": "foo.foo-ns.svc.cluster.local"
        },
        "destination.service.name": {
        "string_value": "foo"
        },
        "destination.service.namespace": {
        "string_value": "foo-ns"
        },
        "destination.service.uid": {
        "string_value": "istio://foo-ns/services/foo"
        }
        }
    }
    }
    },
    "name": "provider-global-default"
    }
]
}
```
</details>

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

- [x] Traffic Management 🤷 

**Expected behavior**

We expect the dumps be _identical_.

**Steps to reproduce the bug**

Apply VS posted above and compare dumps.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
# cluster where it works fine
istioctl version --remote
client version: 1.6.4
control plane version: 1.4.10
# cluster where it's not working
istioctl version --remote
client version: 1.6.4
control plane version: 1.5.8
```

Both clusters are on 

**How was Istio installed?**

`helm template`

**Environment where bug was observed (cloud vendor, OS, etc)**

Not relevant.
