### ISSUE TITLE
Conflicting ServiceEntries cause istio-proxy crash

### ISSUE THREAD

**Issue by khernyo** [istio/istio#26273]
**Bug description**

Two ServiceEntries with conflicting configuration causes Istio to send invalid configuration to istio-proxy which responds with `multiple filter chains with the same matching rules are defined` error. Sometimes, istio-proxy crashes when receiving the invalid configuration. When this happens, istio-proxy restarts but fails to become ready with the following message in its log: `Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 2 successful, 0 rejected; lds updates: 0 successful, 2 rejected`. Deleting one of the ServiceEntries brings the service mesh back to a running state.

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Expected behavior**
1. Istio should not send invalid configuration to envoy
1. Istio should report the invalid configuration to the user

**Steps to reproduce the bug**
1. `kind create cluster`
1. `istioctl install --set profile=minimal`
1. apply the following resources:
    ```
    apiVersion: v1
    kind: Namespace
    metadata:
      labels:
        istio-injection: enabled
      name: test-app
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: test-app
      namespace: test-app
    spec:
      containers:
        - name: sleep
          image: alpine:3.12
          command: ['sh', '-c', 'sleep 3600']
      terminationGracePeriodSeconds: 0
    ---
    apiVersion: networking.istio.io/v1beta1
    kind: ServiceEntry
    metadata:
      name: github-com
      namespace: test-app
    spec:
      hosts:
        - github.com
        - '*.googleapis.com'
      ports:
        - name: https
          number: 443
          protocol: HTTPS
    ---
    apiVersion: networking.istio.io/v1beta1
    kind: ServiceEntry
    metadata:
      name: slack-hook-https
      namespace: test-app
    spec:
      hosts:
        - hooks.slack.com
      ports:
        - name: tcp
          number: 443
          protocol: TCP
    ```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
$ istioctl version --remote
client version: 1.6.7
control plane version: 1.6.7
data plane version: 1.6.7 (1 proxies)
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

`istioctl install --set profile=minimal`

**Environment where bug was observed (cloud vendor, OS, etc)**
```
$ kind version
kind v0.8.1 go1.14.2 linux/amd64
```

Not attaching a cluster state archive because this bug should be easily reproducible, but let me know if it would be helpful and I'll attach one.
