### ISSUE TITLE
Istio throwing 503 UH errors for external service calls and cluster has multiple ServiceEntry for same host

### ISSUE THREAD

**Issue by keerthig9** [istio/istio#26282]
**Bug description**
We recently enabled Egress for external service calls in our cluster and all was working fine for a week, later we observed spikes of 503 UH errors for external service calls in envoy sidecar and recovered automatically. 2 days it was a small spike but one day the errors went up for nearly 4 hours causing availability drop for cluster and recovered automatically. We disabled egress as mitigation and now we are trying to root cause the issue. Interestingly we observed below logs in pilot and suspected this might be cause for failures.
```
2020-07-27T19:56:47.446198Z info    ads Push Status: {
    "ProxyStatus": {
        **"pilot_duplicate_envoy_clusters": {
            "outbound|443|http-calls|externalservice.com": {
                "proxy": “pod-77fcb84d67-qlv92.istio-system",
                "message": "Duplicate cluster outbound|443|http-calls|externalservice.com found while pushing CDS"
            },
            "outbound|443||externalservice.com": {
                "proxy": “pod-77fcb84d67-qlv92.istio-system",
                "message": "Duplicate cluster outbound|443||externalservice.com found while pushing CDS"
            }
        },**
        "pilot_eds_no_instances": {
            ….
        }
    },
    "Version": "jNI6sdquBTYRY=asds”
}
```
**and pod sidecar had below logs**
Successful request log:
```
[2020-07-27T18:10:57.205Z] "GET /products/xxx HTTP/1.1" 200 - "-" "-" 0 5754 11 11 "-" “xxx-1.5.0” "a76ec2c0-bc79-42df-a201-f1d29d26bc96" “externalservice.com:30445" “x.x.x.x:443" outbound|443|http--calls|externalservice.com - x.x.x.x:30445 x.x.x.x:59772 - -
```
Failed request log:
```
[2020-07-27T18:10:57.252Z] "GET /products/xxx HTTP/1.1"  503 UH "-" "-" 0 19 0 - "-" “xxx-1.5.0” "95b75970-03a3-4548-9440-d9eff293de97" "externalservice.com:30445" "-" - - 10.0.31.98:30445 10.0.19.196:60416 - -
```
**Note: In above logs for a request with 503 errors, outbound rule is not present.**
**and on debugging further we observed we had two ServiceEntry for same host externalservice.com.**
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-api-with-tls-origination
  namespace: default
spec:
  hosts:
    - externalservice.com
  ports:
    - number: 30445
      name: http-port-for-tls-origination
      protocol: HTTP
    - name: https
      number: 443
      protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
  endpoints:
    - address: externalservice.com
      ports:
        https: 443
```

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-api
  namespace: default
spec:
  hosts:
    - externalservice.com
  ports:
    - number: 443
      name: https
      protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
```
Note: One service entry has spec for only port 443 and another one has for port 30445, 443.

**Questions:**
**1) When we have two ServiceEntry for same host with different spec, which one will be picked by pilot? Will Istio merge the ServiceEntry config? (If pilot picks one of it, Am suspecting few istio-pilot pods picked serviceEntry config without port 30445 and pushed config for a sometime, which might have caused outbound rule to miss and later push might have brought serviceEntry with port 30445 bcoz of which cluster recovered)**
**2) How frequently pilot send config to pods and will pilot refresh config at regular intervals?**
** 3) Will each pilot pod makes decision of its own which config to pick when we have two?**
**3) Do you have any suggestions for how to reproduce the bug?**

[ ] Docs
[ ] Installation
[X ] Networking
[ X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ X] Test and Release
[X ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**
Not able to reproduce

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4.5

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS Kubernetes cluster
