### ISSUE TITLE
Conflicting ServiceEntries cause outbound traffic restrictions to be ignored

### ISSUE THREAD

**Issue by khernyo** [istio/istio#26303]
**Bug description**

When two service entries contain conflicting protocol for the same port (one TCP and the other HTTPS) the resulting envoy config ends up with a catch all filter chain. This can allow all outbound traffic on a supposedly locked down cluster.

Possibly related issue: #26273 

Istio-proxy logs contain the following warning:
```
warning	envoy config	[external/envoy/source/server/listener_impl.cc:502] adding listener '0.0.0.0:443': filter chain match rules require TLS Inspector listener filter, but it isn't configured, trying to inject it (this might fail if Envoy is compiled without it)
```

The envoy config shows that there is a catch all filter chain (supposedly for hooks.slack.com) and another one for github.com. Here is a snippet with some of the unrelated parts removed:
```
      "dynamic_listeners": [
        {
          "name": "0.0.0.0_443",
          "active_state": {
            "version_info": "2020-08-08T15:48:17Z/19",
            "listener": {
              "@type": "type.googleapis.com/envoy.api.v2.Listener",
              "name": "0.0.0.0_443",
              "address": {
                "socket_address": {
                  "address": "0.0.0.0",
                  "port_value": 443
                }
              },
              "filter_chains": [
                {
                  "filters": [
                    {
                      "name": "envoy.tcp_proxy",
                      "typed_config": {
                        "@type": "type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy",
                        "stat_prefix": "outbound|443||hooks.slack.com",
                        "cluster": "outbound|443||hooks.slack.com",
                      }
                    }
                  ]
                },
                {
                  "filter_chain_match": {
                    "server_names": [
                      "github.com"
                    ]
                  },
                  "filters": [
                    {
                      "name": "envoy.tcp_proxy",
                      "typed_config": {
                        "@type": "type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy",
                        "stat_prefix": "outbound|443||github.com",
                        "cluster": "outbound|443||github.com",
                      }
                    }
                  ]
                }
              ],
              "deprecated_v1": {
                "bind_to_port": false
              },
              "traffic_direction": "OUTBOUND"
            },
            "last_updated": "2020-08-08T16:08:59.003Z"
          }
        },
      ]

```

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Expected behavior**

1. Istio should not send invalid configuration to envoy.
1. Istio should reject and report the invalid configuration to the user

**Steps to reproduce the bug**

1. `kind create cluster`
1. `istioctl install --set profile=demo`
1. Apply the following resources:
    ```
    apiVersion: v1
    kind: Namespace
    metadata:
      labels:
        istio-injection: enabled
      name: test-app
    ---
    apiVersion: networking.istio.io/v1beta1
    kind: Sidecar
    metadata:
      name: test-app-restrict
      namespace: test-app
    spec:
      egress:
        - hosts:
            - ./*
      outboundTrafficPolicy:
        mode: REGISTRY_ONLY
    ---
    apiVersion: networking.istio.io/v1alpha3
    kind: Gateway
    metadata:
      name: egress
      namespace: istio-system
    spec:
      selector:
        app: istio-egressgateway
      servers:
        - port:
            number: 443
            name: tls
            protocol: TLS
          hosts:
            - "*"
          tls:
            mode: ISTIO_MUTUAL
    ---
    apiVersion: networking.istio.io/v1alpha3
    kind: VirtualService
    metadata:
      name: github-egress
      namespace: istio-system
    spec:
      hosts:
        - github.com
        - www.github.com
      gateways:
        - istio-system/egress
      tcp:
        - match:
            - gateways:
                - istio-system/egress
              port: 443
          route:
            - destination:
                host: github.com
                port:
                  number: 443
    ---
    apiVersion: networking.istio.io/v1alpha3
    kind: VirtualService
    metadata:
      name: slack-egress
      namespace: istio-system
    spec:
      hosts:
        - hooks.slack.com
      gateways:
        - istio-system/egress
      tcp:
        - match:
            - gateways:
                - istio-system/egress
              port: 443
          route:
            - destination:
                host: hooks.slack.com
                port:
                  number: 443
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: test-app
      namespace: test-app
    spec:
      containers:
        - name: curl
          image: curlimages/curl:7.71.1
          command: ['sh', '-c', 'sleep 3600']
      terminationGracePeriodSeconds: 0
    ---
    apiVersion: networking.istio.io/v1beta1
    kind: ServiceEntry
    metadata:
      name: github-com
      namespace: test-app
    spec:
      hosts:
        - github.com
      ports:
        - name: https
          number: 443
          protocol: HTTPS
    ---
    apiVersion: networking.istio.io/v1beta1
    kind: ServiceEntry
    metadata:
      name: slack-hook-https
      namespace: test-app
    spec:
      hosts:
        - hooks.slack.com
      ports:
        - name: tcp
          number: 443
          protocol: TCP
    ```
1. Check that github.com and hooks.slack.com is reachable on HTTPS
    ```
    $ kubectl exec -ti -n test-app test-app -c curl -- curl -iI https://github.com
    $ kubectl exec -ti -n test-app test-app -c curl -- curl -iI https://hooks.slack.com
    ```
    Both commands succeed as expected.
1. Check that other hosts are denied:
    ```
    $ kubectl exec -ti -n test-app test-app -c curl -- curl -iI https://google.com
    ```
    This command shouldn't succeed, but it does!

1. To fix the issue, change the port protocol from TCP to HTTPS:
    ```
    $ kubectl patch se -n test-app slack-hook-https --type=json -p='[{"op": "replace", "path": "/spec/ports/0/protocol", "value": "HTTPS"}]'
    ```
    Now the above curl commands work as expected. The first two succeed while the third one fails.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ istioctl version --remote
client version: 1.6.7
control plane version: 1.6.7
data plane version: 1.6.7 (4 proxies)
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

`istioctl install --set profile=demo`

**Environment where bug was observed (cloud vendor, OS, etc)**

```
$ kind version
kind v0.8.1 go1.14.2 linux/amd64
```
