### ISSUE TITLE
Can't create multiple ingress gateway using istioctl and customized operator manifest

### ISSUE THREAD

**Issue by minhtrietbkit** [istio/istio#26337]
**Bug description**
Following [guide](https://istio.io/v1.5/docs/setup/install/istioctl/#configure-gateways) to bootstrap istio with multiple ingress gateway doesn't work.

My IstioOperator is as follows:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: empty
  components:
    base:
      enabled: true
    ingressGateways:
      - name: istio-private-ingressgateway
        enabled: true
        k8s:
          nodeSelector:
            alpha.eksctl.io/nodegroup-name: private-ingress
          service:
            type: NodePort
            ports:
              - name: http2
                port: 80
                targetPort: 80
              - name: https
                port: 443
      - name: istio-public-ingressgateway
        enabled: true
        k8s:
          nodeSelector:
            alpha.eksctl.io/nodegroup-name: public-ingress
          service:
            type: NodePort
            ports:
              - name: http2
                port: 80
                targetPort: 80
              - name: https
                port: 443
    pilot:
      enabled: true
      k8s:
        nodeSelector:
          alpha.eksctl.io/nodegroup-name: istio
  hub: docker.io/istio
  tag: 1.5.0
    global:
      proxy:
        accessLogFile: /dev/stdout
        logLevel: info
```

The result from running `istioctl manifest generate -f istio-manifest.yaml` does not reflect custom gateways as described. Only Gateway manifests are pasted here:

```
# Resources for IngressGateways component

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    
    release: istio
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istio-ingressgateway
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
---


apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: istio-ingressgateway
        chart: gateways
        heritage: Tiller
        istio: ingressgateway
        release: istio
        service.istio.io/canonical-name: istio-ingressgateway
        service.istio.io/canonical-revision: "1.5"
    spec:
<...omitted deployment spec>

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingressgateway
  namespace: istio-system
  labels:
    release: istio
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - "*"
    # Additional ports in gateaway for the ingressPorts - apps using dedicated port instead of hostname
---


apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ingressgateway
  namespace: istio-system
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    
    release: istio
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
      
      release: istio
<omitted roles, rolebindings...>

---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
<omitted service spec>
<omitted some more resources>
---
# Resources for IngressGateways component

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    
    release: istio
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istio-ingressgateway
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
---


apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
<omitted 2nd deployment spec>
<omitted some more resources identical to the 1 st set>
```

Summary of the generated manifests: 2 identical sets of 
* Deployment
* Gateway
* Service
... some more

are deployed. 

**Idential** means the `metadata` and `selector` fields are the same. Furthermore, they do not reflect the metadata set in the Operator manifest such as the value of name label.

[X] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

2 separate sets of above resources are generated with metadata reflecting customized value in Operator manifest.

**Steps to reproduce the bug**

run `istioctl manifest generate -f istio-manifest.yaml`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

* istioctl: 1.5.0
* kubectl version: 
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:34Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-f459c0", GitCommit:"f459c0672169dd35e77af56c24556530a05e9ab1", GitTreeState:"clean", BuildDate:"2020-03-18T04:24:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
`istioctl manifest apply -f istio-manifest.yaml`

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS 1.14

**Comment by morvencao** [comment]
There a few issues with your IstioOperator manifest:
1. You missed the `values` field for **global** setting which results the error:
```
Error: error converting YAML to JSON: yaml: line 42: mapping values are not allowed in this context:
```
It should be:
```
  values:
    global:
      proxy:
        accessLogFile: /dev/stdout
        logLevel: info
```

2. You have to add labels for different gateway:
```
    ingressGateways:
      - name: istio-private-ingressgateway
        enabled: true
        label:
          app: istio-private-ingressgateway
        k8s:
          nodeSelector:
            alpha.eksctl.io/nodegroup-name: private-ingress
          service:
            type: NodePort
            ports:
              - name: http2
                port: 80
                targetPort: 80
              - name: https
                port: 443
      - name: istio-public-ingressgateway
        enabled: true
        label:
          app: istio-public-ingressgateway
        k8s:
          nodeSelector:
            alpha.eksctl.io/nodegroup-name: public-ingress
          service:
            type: NodePort
            ports:
              - name: http2
                port: 80
                targetPort: 80
              - name: https
                port: 443
```

3. Please try with latest istio(1.6.x), I'm not sure if istio 1.5.0 include the fix to create customized gateway.


You can use the following istiooperator:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: empty
  components:
    base:
      enabled: true
    ingressGateways:
      - name: istio-private-ingressgateway
        enabled: true
        label:
          app: istio-private-ingressgateway
        k8s:
          nodeSelector:
            alpha.eksctl.io/nodegroup-name: private-ingress
          service:
            type: NodePort
            ports:
              - name: http2
                port: 80
                targetPort: 80
              - name: https
                port: 443
      - name: istio-public-ingressgateway
        enabled: true
        label:
          app: istio-public-ingressgateway
        k8s:
          nodeSelector:
            alpha.eksctl.io/nodegroup-name: public-ingress
          service:
            type: NodePort
            ports:
              - name: http2
                port: 80
                targetPort: 80
              - name: https
                port: 443
    pilot:
      enabled: true
      k8s:
        nodeSelector:
          alpha.eksctl.io/nodegroup-name: istio
  values:
    global:
      proxy:
        accessLogFile: /dev/stdout
        logLevel: info
```
