### ISSUE TITLE
Missing install-cni distroless image fails install

### ISSUE THREAD

**Issue by akath19** [istio/istio#26360]
**Bug description**

Attempting to install a distroless version of 1.6.7 with CNI fails because `install-cni:1.6.7-distroless` image doesn't exist, this image tag only exists in 1.7.0 beta, this is causing all proxies to fail because istio-validation fails.

**Affected product area (please put an X in all that apply)**

[x] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Installing istio with distroless tag and CNI should success without issues

**Steps to reproduce the bug**

1. Use default profile

1. Enable cni via `--set components.cni.enabled=true` & --set `components.cni.namespace=kube-system`

1. Set image tag to distroless as described [here](https://istio.io/latest/docs/ops/configuration/security/harden-docker-images/) with `--set tag=1.6.7-distroless`

1. Install via `istioctl install`

1. Check status of istio-cni-node in kube-system, status is `ImagePullBackoff` due to `Failed to pull image "docker.io/istio/install-cni:1.6.7-distroless": rpc error: code = Unknown desc = failed to resolve image "docker.io/istio/install-cni:1.6.7-distroless": docker.io/istio/install-cni:1.6.7-distroless not found`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

Kubectl version:
`Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.11-gke.5", GitCommit:"baccd25d44f1a0d06ad3190eb508784efbb990a5", GitTreeState:"clean", BuildDate:"2020-06-25T22:55:26Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}`

Istio version:
`client version: 1.6.7
control plane version: 1.6.7
data plane version: 1.6.7 (1 proxies)`

**How was Istio installed?**

`istioctl install -f istio.yaml` with the below file:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  tag: 1.6.7-distroless
  addonComponents:
    kiali:
      enabled: true
    prometheus:
      enabled: false
    tracing:
      enabled: true
  components:
    citadel:
      enabled: true
    cni:
      enabled: true
      namespace: kube-system
    ingressGateways:
    - enabled: true
    policy:
      enabled: true
    telemetry:
      enabled: true
  values:
    gateways:
      istio-ingressgateway:
        loadBalancerIP: {REDACTED}
    global:
      controlPlaneSecurityEnabled: true
      imagePullPolicy: Always
    kiali:
      createDemoSecret: false
      dashboard:
        grafanaInClusterURL: http://grafana.monitoring:3000/
        jaegerInClusterURL: http://tracing/jaeger
        secretName: kiali-credentials
    tracing:
      jaeger:
        persist: false
```

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE version 1.16.11-gke.5
