### ISSUE TITLE
sidecarInjectorWebhook.objectSelector settings assume sidecar.istio.io/inject is a label

### ISSUE THREAD

**Issue by james-mathiesen** [istio/istio#26378]
**Bug description**

This IstioOperator resource produces an istio-sidecar-injector that assumes `sidecar.istio.io/inject` is a label but all documentation and examples show `sidecar.istio.io/inject` as an annotation.

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    sidecarInjectorWebhook:
      objectSelector:
        enabled: true
        autoInject: false
```

[X] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Unclear. In practice turning this on in an existing cluster is likely to disable all injection since the documentation and the injector describe `sidecar.istio.io/inject` as an annotation not a label.

**Steps to reproduce the bug**

Using `istioctl manifest generate` with the above profile.  The generated MutatingWebhookConfiguration for the injector will include this section:

```
 objectSelector:
    matchLabels:
     sidecar.istio.io/inject: 'true'
```

But `sidecar.istio.io/inject` is expected to be an annotation not a label so turning this on is likely to cause very unexpected results to any existing workload.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

Istio 1.6.7

**How was Istio installed?**

`istioctl manifest generate`
**Environment where bug was observed (cloud vendor, OS, etc)**
