### ISSUE TITLE
The istio-sidecar-injector configuration parameters produce broken configurations

### ISSUE THREAD

**Issue by james-mathiesen** [istio/istio#26376]
**Bug description**

The following IstioOperator resource does not change the namespaceSelector in istio-sidecar-injector:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    sidecarInjectorWebhook:
      injectLabel: networking.mycompany.com/istio
```

[X] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Passing the above configuration would modify the namespaceSelector portion of the MutatingWebhookConfiguration but it does not.

**Steps to reproduce the bug**

Use istioctl to build a set of manifests that include the injector.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.6.7 using istioctl manifest generate.

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
