### ISSUE TITLE
Istioctl install does not honor serviceAnnotations specified using IstioOperatorAPI syntax when applying a previously generated manifest

### ISSUE THREAD

**Issue by geekifier** [istio/istio#26373]
**Bug description**

When installing via `istioctl`, the `serviceAnnotations` are not applied when configured using the Istio Operator API, despite being present in the final install manifest.

This only happens when the manifest is first generated, and then applied via a separate apply command. If the manifest is applied directly (without first generating it), the annotations are created.

[X] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Service annotations are present on the istio-ingressgateway service.

**Steps to reproduce the bug**

Prepare the overlay file:

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  hub: "docker.io/istio"
  profile: "minimal"
  addonComponents:
    pilot:
      enabled: true
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-internal: "0.0.0.0/0"
      - name: cluster-local-gateway
        enabled: true
        label:
          istio: cluster-local-gateway
          app: cluster-local-gateway
        k8s:
          service:
            type: ClusterIP
            ports:
            - port: 15020
              name: status-port
            - port: 80
              name: http2
            - port: 443
              name: https
```

```bash
istioctl manifest generate -f /path/to/above/overlay.yml > /tmp/manifest.yml
istioctl manifest apply -f /tmp/manifest.yml
```

Verify the manifest and notice the annotations are there:

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
```

Verify that the annotations were not created

`k get svc istio-ingressgateway -n istio-system -o yaml`

**But wait, there is more!**

If the overlay is applied directly, that is, without using `manifest generate`, then the annotations are properly applied:

`istioctl manifest apply -f /path/to/above/overlay.yml`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```bash
istioctl version --remote
client version: 1.6.3
control plane version: 1.6.7
data plane version: 1.6.7 (2 proxies)
```

**How was Istio installed?**

Via istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**

MacOS 10.14.6.
Tested against AWS EKS 1.17, as well as local Docker Desktop Kubernetes running 1.16.5.
