### ISSUE TITLE
Istio proxy failed to start due to failure to load WASM based listener

### ISSUE THREAD

**Issue by marklu2018** [istio/istio#26388]
**Bug description**
Follow the README instructions in https://github.com/proxy-wasm/proxy-wasm-cpp-sdk to build a `myproject.wasm` using emscripten and configured a listener to load the `myproject.wasm` in the envoy proxy. But the Envoy proxy failed to start and saw the following error messages. The error message is ambiguous. Is the WASM file missing ABI version? or it's using an unsupported API version (which version is supported, and what's the version in the WASM file)? A little bit more detail will be helpful.
```
E 2020-08-11T20:53:49.524885993Z virtualInbound: WASM missing Proxy-Wasm ABI version or requires an unsupported version.
E 2020-08-11T21:23:36.410958254Z warning	envoy config	[external/envoy/source/common/config/grpc_subscription_impl.cc:101] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) 10.0.81.172_853: WASM missing Proxy-Wasm ABI version or requires an unsupported version. 
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Expect the `myproject.wasm` filter to be loaded and taking effect.

**Steps to reproduce the bug**
1. Build `myproject.wasm` following the README instructions int he Proxy WASM C++ SDK project.
2. Configure an EnvoyFilter to load the WASM binary in a http listener. But the Istio-Proxy container failed to start with the error messages listed above.
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.6.7
**How was Istio installed?**
Follow the Istio installation tutorial, and installed bookinfo demo.
**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by canthefason** [comment]
I've spent the whole day yesterday on understanding WASM, and making an Envoy filter work on Istio version 1.6. I ended up with running into the exact same issue with you. Someone with more knowledge around this can fill me in, but my basic findings around this problem are as follows:
- To support Istio 1.7, [proxy-wasm-cpp-sdk](https://github.com/proxy-wasm/proxy-wasm-cpp-sdk) switched to a more recent version of ABI which is 0.2.1. (https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/pull/45). This is the main reason why you're getting that `WASM missing Proxy-Wasm ABI version or requires an unsupported version.` error, since that version is incompatible with earlier version of Envoy/Istio.  
- Definitely you can switch to Istio v1.7 and that would supposedly solve the problem for you. (after that switch I started getting `Unable to create Wasm HTTP filter` error in which I'll be looking into today.
- I've switched to an earlier version of `proxy-wasm-cpp-sdk` and recompiled it(https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/commit/a96408d4418e0610494cff99478ae10b77eb813b). 
- Another option is, you can look into [wasme](https://github.com/solo-io/wasme), however I found build times being too long for it. There might be a way to optimize it, but so far my experience has been, on a laptop it takes plenty of time to build it even for a single change. On the other hand, the filter I built with Wasme worked all good on Istio v1.6

While doing ABI version switches, you'll encounter that there are some method signature changes between these two. So you might need to update your code to comply with these version changes.

**Comment by salrashid123** [comment]
@canthefason   Any progress on the v1.7 error?  I think i'm running into this as well

` 

I'm using a base build of [envoy-wasm helloworld](https://github.com/envoyproxy/envoy-wasm/tree/master/examples/wasm)  which i know works on envoy direct on version
```
./envoy  version: c5594b41f48b2e45df83105de84623f2930d23cd/1.15.0/clean-getenvoy-a5345f6-envoy/RELEASE/BoringSSL
```

but  on istio `1.7.2, if i startup and define a configmap with `.wasm` that i generated
```
export ISTIO_VERSION=1.7.2
istioctl install --set profile=demo

kubectl create cm -n default example-filter  --from-file=/path/to/envoy-wasm/bazel-bin/examples/wasm/envoy_filter_http_wasm_example.wasm       
```

Thendefine the filter 
```yaml 
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ui-examplefilter
  namespace: default
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      proxy:
        proxyVersion: '1\.7.*'      
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              name: envoy.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.wasm
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          value:
            config:
              root_id: my_root_id
              vm_config:
                code:
                  local:
                    filename: /var/local/lib/wasm-filters/envoy_filter_http_wasm_example.wasm
                runtime: envoy.wasm.runtime.v8
                allow_precompiled: true
                vm_id: my-example
  workloadSelector:
    labels:
      app: myapp
      version: v1
```

and deployment with annotations 
```yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-v1
spec:
  selector:
    matchLabels:
      app: myapp
      version: v1   
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
        version: v1
      annotations:
        sidecar.istio.io/userVolume: '[{"name":"wasmfilters-dir","configMap": {"name": "example-filter"}}]'
        sidecar.istio.io/userVolumeMount: '[{"mountPath":"/var/local/lib/wasm-filters","name":"wasmfilters-dir"}]'        
    spec:
      serviceAccountName: myapp-sa
      containers:
      - name: myapp-container
        image: salrashid123/istioinit:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080        

```

I'll see errors on GKE like

```
2020-09-22T13:26:38.529219Z	warning	envoy config	gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) virtualInbound: Unable to create Wasm HTTP filter 

2020-09-22T13:26:38.527303Z	error	envoy wasm	Wasm VM failed Failed to initialize Wasm code
```

and yeah, wasme takes forever to build..
