### ISSUE TITLE
The default istio-sidecar-injector can block creation of new istiod pods

### ISSUE THREAD

**Issue by james-mathiesen** [istio/istio#26380]
**Bug description**

After the MutatingWebhookConfiguration/istio-sidecar-injector is patched with the CA and failurePolicy the istio control plane cannot recover from a complete istiod outage.

If all istiod pods are down for any reason the MutatingWebhookConfiguration will prevent creation of replacement pods.

IMO the MutatingWebhookConfiguration should be structured so that it cannot block a cold start of the Istio control plane.

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Expected behavior**

I expect istio control plane to be eventually consistent so having istiod fail to start because istiod is down is kind of a problem.  I think the MutatingWebhookConfiguration should in some way always exclude the pods required to bootstrap the istio control plane.

**Steps to reproduce the bug**

Create a configuraton with istio-sidecar-injector enabled.  Ensure that the injector is on by default or otherwise includes the istio-system namespace.

Allow the control plane to start and patch istio-sidecar-injector with the CA and failurePolicy.

Use a command such as `kubectl -n istio-system scale deployment istiod --replicas 0` (deleting pods might work too, but is racy).

After all istiod instances have exited use a command such as `kubectl -n istio-system scale deployment istiod --replicas 3` to start the instances up again.

Use a command such as `kubectl -n istio-system get event --watch` and observe that istiod pods cannot be created because all instances of the injector are down.

Note that this is a synthetic recreation of an issue we discovered during a version upgrade.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istio 1.6.7

**How was Istio installed?**

`istioctl manifest generate`

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
You should not label the istiod namespace with istio-injection=enabled

**Comment by james-mathiesen** [comment]
We aren't using that specific label... but we have a huge cluster (2000+ namespaces) and only some are using Istio.  To make the Kiali label filter different from the injection label filter means that we need two labels on every user namespace (one to turn on Kiali and one to opt-in to the injector). I saw the optional objectSelector and started to use it, then realized that it wouldn't help because all the documentation and examples assume sidecar.istio.ios/inject is an annotation, not a label so then every pod would need both a label and an annotation to opt-in to the injector.

**Comment by howardjohn** [comment]
I am not sure what we can do here...

>  I think the MutatingWebhookConfiguration should in some way always exclude the pods required to bootstrap the istio control plane.

My understanding is we do not include these pods, but you are making custom modifications which is selecting these. In this case, it seems your responsibility to ensure the custom modifications are not breaking yourself? Or am I misunderstanding the situation?

**Comment by james-mathiesen** [comment]
I think I have goals that are unexpected. We're introducing istio into large clusters with many existing cluster-wide opt-in services.  The effect I want is for istio to be opt-in by namespace and for the injector to be opt-in by pod. I've found this a bit difficult. There's nothing to do here unless our concerns overlap though.

Maybe the earliest divergence is that I want a namespace label that means "is this namespace related to istio" but the helm charts and the label name assume my goal is "turn on the injector"

But following along from the configuration options available and trying to reach a point that meets or needs has been hard.

```
.Values.sidecarInjectorWebhook.enableNamespacesByDefault
.Values.revision
.Values.sidecarInjectorWebhook.objectSelector.enabled
.Values.sidecarInjectorWebhook.objectSelector.autoInject
```

there's also .Values.global.proxy.autoInject which is related but isn't considered when building the MutatingWebhookConfiguration.

These runtime conditions:

- Is the namespace labeled for opt-in, opt-out, unspecified or ill-formed
- Is the pod labeled for opt-in, opt-out, opt-in-by-version, unspecified or ill-formed
- Is the pod annotated for opt-in, opt-out, opt-in-by-version, unspecified or ill-formed

And these outcomes:

- injector can deadlock startup of istiod
- injector will be offered pod
- injector will modify pod

Ends up with fine-grained variation that doesn't seem useful.

- How do we handle namespace opt-in for Kiali?
- What happens when pod label/annotation are not identical?



For example if you use an opt-out strategy at the namespace level the istio-system namespace is excluded but if you use an opt-in strategy it is not.



```
{{- if .Values.sidecarInjectorWebhook.enableNamespacesByDefault }}
      matchExpressions:
      - key: name
        operator: NotIn
        values:
        - {{ .Release.Namespace }}
      - key: istio-injection
        operator: NotIn
        values:
        - disabled
      - key: istio-env
        operator: DoesNotExist
      - key: istio.io/rev
        operator: DoesNotExist
{{- else if .Values.revision }}
      matchExpressions:
      - key: istio-injection
        operator: DoesNotExist
      - key: istio.io/rev
        operator: In
        values:
        - {{ .Values.revision }}
{{- else }}
      matchLabels:
        istio-injection: enabled
{{- end }}
{{- if .Values.sidecarInjectorWebhook.objectSelector.enabled }}
    objectSelector:
{{- if .Values.sidecarInjectorWebhook.objectSelector.autoInject }}
      matchExpressions:
      - key: "sidecar.istio.io/inject"
        operator: NotIn
        values:
        - "false"
{{- else if .Values.revision }}
      matchExpressions:
      - key: "sidecar.istio.io/inject"
        operator: DoesNotExist
      - key: istio.io/rev
        operator: In
        values:
        - {{ .Values.revision }}
{{- else }}
      matchLabels:
        "sidecar.istio.io/inject": "true"
{{- end }}
{{- end }}
```
