### ISSUE TITLE
Galley permits Virtual Service with invalid Envoy header manipulation config

### ISSUE THREAD

**Issue by terev** [istio/istio#26397]
**Bug description**
We hit an issue today (in 1.3.6) where Galley permits a Virtual Service object that it probably should not have. The Virtual Service contained a header manipulation rule that set a header to a value containing a `%` character. When the config was pushed to Envoy it began throwing the following warning:

`[2020-08-11 16:28:47.840][38][warning][config] [external/envoy/source/common/config/grpc_mux_subscription_impl.cc:81] gRPC config for type.googleapis.com/envoy.api.v2.RouteConfiguration rejected: Invalid header configuration. Un-terminated variable expression '*****'` 

Where * are characters after the `%` character. We believe this prevented Envoy proxies from accepting any more config updates as we began seeing 404's for new routes added to our ingress gateway. After removing the offending virtual service new configs seemed to make it to proxies.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Either Galley should reject Virtual Service objects containing unterminated variable expressions to prevent messing with Envoy. Or Pilot could escape any unterminated variable expressions before pushing the config. Is the former a better choice? It could probably easily done by adding an analyzer here: https://github.com/istio/istio/tree/master/galley/pkg/config/analysis/analyzers/virtualservice ?

**Steps to reproduce the bug**
1. Create a virtual service that contains a header manipulation rule with an unterminated variable expression, ex:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: broken-vs
spec:
  hosts:
    - example.com
  gateways:
    - istio-system/istio-gateway
  http:
    - match:
        - uri:
            prefix: /some-path
      route:
        - destination:
            port:
              number: 80
            host: api
          headers:
            request:
              set:
                Some-Header: abcd%oijasodifj
```
2. Attempt to hit the new route and you should be faced with a 404
3. Add another virtual service with a route for some other path that doesn't contain a header manipulation rule, ex:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-should-work
spec:
  hosts:
    - example.com
  gateways:
    - istio-system/istio-gateway
  http:
    - match:
        - uri:
            prefix: /another-path
      route:
        - destination:
            port:
              number: 80
            host: api
```
4. Attempt to hit this new path and notice that you are faced with a 404 again

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
istioctl version --remote
client version: 1.6.7
control plane version: 1.3.6
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T23:30:39Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.42", GitCommit:"42bef28c2031a74fc68840fce56834ff7ea08518", GitTreeState:"clean", BuildDate:"2020-06-02T16:07:00Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**
Istio was installed using the Helm chart.

**Environment where bug was observed (cloud vendor, OS, etc)**
Google Kubernetes Engine, Linux
