### ISSUE TITLE
Consider stricter validation of Envoyfilter

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#26390]
Not sure if this is possible - but I applied config like
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: custom-protocol
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      context: SIDECAR_OUTBOUND
    patch:
      operation: ADD
      value:
        name: redis-test
        type: STRICT_DNS
        lb_policy: MAGLEV
        connect_timeout: '0.5s'
        load_assignment:
          cluster_name: redis-test
          endpoints:
          - lb_endpoints:
            - endpoint:
              address:
                socket_address:
                  address: redis-test
                  port_value: 6379
```

spot the error? `address` is indented wrong. We get no indication, it is silently ignored.

In theory we could possibly do strict marshaling here. In practice this might be complicated and even harmful (new field, for example, not in go-control-plane - but would we end up dropping it anyways? I think maybe yes)

cc @mandarjog @rshriram @esnible
