### ISSUE TITLE
Ingress Gateway with Hostnetwork won't listen on the requested ports

### ISSUE THREAD

**Issue by christhomas** [istio/istio#26462]
I'm trying to install Istio on my bare metal 3 node cluster, I don't have any autoscaling requirements, the setup is static. So I'm going to install Istio without any loadbalancers or cloud, I'm just going to use DNS with multiple A-records as a loadbalancer (cause it's free). So I'm trying to setup Istio to use hostNetwork and I'm finding that even though I'm trying to ask the ingressgateway to listen on the requested ports. I find none of those ports are actually being listened to.

I've in the past had good success with ingress-nginx, you setup the ports, both HTTP and TCP types and use hostnetwork and you can find on the nodes that it was installed on that it listens and the traffic enters the cluster. 

I've removed the autoscaling from the manifest since I don't need it and can't use it anyway. There is also a node selector because I'm limiting this daemonset to only run on one node until I can deploy it across all three nodes. 

From my understanding, I can run this proxyv2 pod, bind it to the correct ports on the hostnetwork and this acts as the actual ingress for traffic to flow through, then I have to target that pod with an Istio Gateway that targets the ports it wants to listen for traffic on. Then you have a virtual service mechanism which connects the gateway with the service that'll process the traffic.

A side question would be how does the gateway know which ingress to attach to. Is it using those "istio: istiogateway" labels I am seeing being attached to all the nodes? I'm just looking for a confirmation about that cause I think I'm understanding this part ok, but if you think I've made a misunderstanding, please let me know.

But what I get on the node is that envoy is only binding itself to the following:
```
# netstat -tupln | grep envoy
tcp        0      0 0.0.0.0:15021           0.0.0.0:*               LISTEN      10071/envoy
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      10071/envoy
tcp        0      0 0.0.0.0:15090           0.0.0.0:*               LISTEN      10071/envoy
tcp        0      0 127.0.0.1:15000         0.0.0.0:*               LISTEN      10071/envoy
```

I've attached my manifest at the bottom of this ticket. 

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Envoy should listen on all the requested ports

**Steps to reproduce the bug**
Install the manifest
look on vps server for ports listened to using: netstat -tupln

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.6.7

**How was Istio installed?**
istioctl manifest generate

**Environment where bug was observed (cloud vendor, OS, etc)**
Bare metal VPS server cluster

My Ingress manifest is:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
        sidecar.istio.io/inject: "false"
      labels:
        app: istio-ingressgateway
        chart: gateways
        heritage: Tiller
        istio: ingressgateway
        release: istio
        service.istio.io/canonical-name: istio-ingressgateway
        service.istio.io/canonical-revision: latest
    spec:
      nodeSelector:
        ingress: "istio"
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
            weight: 2
          - preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - ppc64le
            weight: 2
          - preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - s390x
            weight: 2
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
      containers:
      - args:
        - proxy
        - router
        - --domain
        - $(POD_NAMESPACE).svc.cluster.local
        - --proxyLogLevel=warning
        - --proxyComponentLogLevel=misc:error
        - --log_output_level=default:info
        - --serviceCluster
        - istio-ingressgateway
        - --trust-domain=cluster.local
        env:
        - name: JWT_POLICY
          value: third-party-jwt
        - name: PILOT_CERT_PROVIDER
          value: istiod
        - name: CA_ADDR
          value: istiod.istio-system.svc:15012
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: CANONICAL_SERVICE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['service.istio.io/canonical-name']
        - name: CANONICAL_REVISION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['service.istio.io/canonical-revision']
        - name: ISTIO_META_WORKLOAD_NAME
          value: istio-ingressgateway
        - name: ISTIO_META_OWNER
          value: kubernetes://apis/apps/v1/namespaces/istio-system/deployments/istio-ingressgateway
        - name: ISTIO_META_MESH_ID
          value: cluster.local
        - name: ISTIO_META_ROUTER_MODE
          value: sni-dnat
        - name: ISTIO_META_CLUSTER_ID
          value: Kubernetes
        image: docker.io/istio/proxyv2:1.6.7
        name: istio-proxy
        securityContext:
          privileged: true
        ports:
          - name: http
            containerPort: 80
          - name: https
            containerPort: 443
          - name: gitlab-ssh
            containerPort: 10022
          - name: mail-25
            containerPort: 25
          - name: mail-465
            containerPort: 465
          - name: mail-587
            containerPort: 587
          - name: mail-143
            containerPort: 143
          - name: mail-993
            containerPort: 993
          - containerPort: 15021
          - containerPort: 8080
          - containerPort: 8443
          - containerPort: 15443
          - containerPort: 15011
          - containerPort: 15012
          - containerPort: 8060
          - containerPort: 853
          - containerPort: 15090
            name: http-envoy-prom
            protocol: TCP
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /healthz/ready
            port: 15021
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /etc/istio/proxy
          name: istio-envoy
        - mountPath: /etc/istio/config
          name: config-volume
        - mountPath: /var/run/secrets/istio
          name: istiod-ca-cert
        - mountPath: /var/run/secrets/tokens
          name: istio-token
          readOnly: true
        - mountPath: /var/run/ingress_gateway
          name: ingressgatewaysdsudspath
        - mountPath: /etc/istio/pod
          name: podinfo
        - mountPath: /etc/istio/ingressgateway-certs
          name: ingressgateway-certs
          readOnly: true
        - mountPath: /etc/istio/ingressgateway-ca-certs
          name: ingressgateway-ca-certs
          readOnly: true
      serviceAccountName: istio-ingressgateway-service-account
      volumes:
      - configMap:
          name: istio-ca-root-cert
        name: istiod-ca-cert
      - downwardAPI:
          items:
          - fieldRef:
              fieldPath: metadata.labels
            path: labels
          - fieldRef:
              fieldPath: metadata.annotations
            path: annotations
        name: podinfo
      - emptyDir: {}
        name: istio-envoy
      - emptyDir: {}
        name: ingressgatewaysdsudspath
      - name: istio-token
        projected:
          sources:
          - serviceAccountToken:
              audience: istio-ca
              expirationSeconds: 43200
              path: istio-token
      - configMap:
          name: istio
          optional: true
        name: config-volume
      - name: ingressgateway-certs
        secret:
          optional: true
          secretName: istio-ingressgateway-certs
      - name: ingressgateway-ca-certs
        secret:
          optional: true
          secretName: istio-ingressgateway-ca-certs
```

My Istio Gateway manifest is:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bookinfo-gateway
  namespace: istio-system
spec:
  selector:
    app: my-gateway-controller
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
    - port:
        number: 443
        name: https
        protocol: HTTP
      hosts:
        - "*"
    - port:
        number: 10022
        name: gitlab-ssh
        protocol: TCP
      hosts:
        - "*"
    - port:
        number: 25
        name: mail-25
        protocol: TCP
      hosts:
        - "*"
    - port:
        number: 465
        name: mail-465
        protocol: TCP
      hosts:
        - "*"
    - port:
        number: 587
        name: mail-587
        protocol: TCP
      hosts:
        - "*"
    - port:
        number: 143
        name: mail-143
        protocol: TCP
      hosts:
        - "*"
    - port:
        number: 993
        name: mail-993
        protocol: TCP
      hosts:
        - "*"
```
