### ISSUE TITLE
VirtualService Gateway reference no longer accepts FQDN

### ISSUE THREAD

**Issue by phenixblue** [istio/istio#26479]
**Bug description**

When upgrading from Istio v1.6.4 to v1.6.7 or v1.6.8 existing VirtualServices referencing the Gateway by FQDN (ie. `std-https-gateway.istio-system.svc.cluster.local`) no longer work. This format has worked since at least Istio v1.1.x through v1.6.4 and I did not find any reference to this change in the release notes specifying functionality would change.

[ X] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[X ] Test and Release
[X ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Existing FQDN reference should continue to work or changes should be noted in the release documentation of incompatibility/breaking functionality

**Steps to reproduce the bug**

- Instal Istio v1.6.4
- Install sample app (httpbin) and expose via Virtual Service using an FQDN for the Gateway reference
- Upgrade to istio v1.6.7+
- Ingres Gateway will serve a 404 as the existing VirtualService doesn't trigger discovery
- Edit VirtualService to only use `<gateway_name>.<gateway_namespace>`
- Endpoint should now be reachable

Example of existing VirtualService that has been working since Istio v1.1.x, but fails on Istio v1.6.7+

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpbin
  namespace: default
spec:
  gateways:
  - std-https-gateway.istio-system.svc.cluster.local
  hosts:
  - httpbin.example.com
  http:
  - match:
    - uri:
        prefix: /ip
    - uri:
        prefix: /delay
    - uri:
        prefix: /headers
    route:
    - destination:
        host: httpbin
        port:
          number: 8000
```

Example of edited VirtualService that works on Istio v1.6.7+

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpbin
  namespace: default
spec:
  gateways:
  - std-https-gateway.istio-system
  hosts:
  - httpbin.example.com
  http:
  - match:
    - uri:
        prefix: /ip
    - uri:
        prefix: /delay
    - uri:
        prefix: /headers
    route:
    - destination:
        host: httpbin
        port:
          number: 8000
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ istioctl version --remote
client version: 1.6.8
control plane version: 1.6.7
data plane version: 1.6.7 (8 proxies)
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

Using istioctl with operator config

**Environment where bug was observed (cloud vendor, OS, etc)**

On-premise using Pivotal Container Servicer (PKS)
