### ISSUE TITLE
Listeners & Clusters out of sync when a headless service is delete and reapplied in the same namespace

### ISSUE THREAD

**Issue by ufese** [istio/istio#26476]
**Bug description**
The listeners and clusters configuration between envoy and pilot are in sync the first time a headless service is applied into a namespace. However if the headless service is deleted and applied again into the same namespace, the listeners and clusters go out of sync. 
[X] Networking

**Steps to reproduce the bug**

1. `kubectl create ns mongodb`
2. `kubectl label namespace mongodb istio-injection=enabled --overwrite`
3. `kubectl apply -f mongo_conf.yml -n mongodb`
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      disc: mongodb
  template:
    metadata:
      labels:
        disc: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.0.8
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-storage
        labels:
          disc: mongodb
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    disc: mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    disc: mongodb
```
4. `kubectl apply -f  istio-1.6.5/samples/sleep/sleep.yaml -n mongodb`
5. `istioctl proxy-status  sleep-8f795f47d-8pg8h -n mongodb`
```
yousef@beast:~/Repos/owner_management/config/kubernetes/mongodb$ istioctl proxy-status  sleep-8f795f47d-8pg8h -n mongodb
Clusters Match
Listeners Match
Routes Match (RDS last loaded at Thu, 13 Aug 2020 15:52:42 EDT)
```

6. `kubectl delete -f mongo_conf.yml -n mongodb`
7. `kubectl apply -f mongo_conf.yml -n mongodb`
8. `istioctl proxy-status  sleep-8f795f47d-8pg8h -n mongodb`
```
yousef@beast:~/Repos/owner_management/config/kubernetes/mongodb$ istioctl proxy-status  sleep-8f795f47d-8pg8h -n mongodb
--- Pilot Clusters
+++ Envoy Clusters
@@ -761,19 +761,15 @@
                                  ]
                               }
                            }
                         }
                      ],
                      "combinedValidationContext": {
                         "defaultValidationContext": {
-                           "matchSubjectAltNames": [
-                              {
-                                 "exact": "spiffe://cluster.local/ns/mongodb/sa/default"
-                              }
-                           ]
+
                         },
                         "validationContextSdsSecretConfig": {
                            "name": "ROOTCA",
                            "sdsConfig": {
                               "apiConfigSource": {
                                  "apiType": "GRPC",
                                  "grpcServices": [

--- Pilot Listeners
+++ Envoy Listeners
@@ -1077,68 +1077,14 @@
                      "typedConfig": {
                         "@type": "type.googleapis.com/envoy.config.filter.listener.http_inspector.v2.HttpInspector"
                      }
                   }
                ],
                "listenerFiltersTimeout": "0.100s",
                "continueOnListenerFiltersTimeout": true,
-               "trafficDirection": "OUTBOUND"
-            }
-         }
-      },
-      {
-         "activeState": {
-            "listener": {
-               "@type": "type.googleapis.com/envoy.api.v2.Listener",
-               "name": "10.1.52.45_27017",
-               "address": {
-                  "socketAddress": {
-                     "address": "10.1.52.45",
-                     "portValue": 27017
-                  }
-               },
-               "filterChains": [
-                  {
-                     "filters": [
-                        {
-                           "name": "istio.stats",
-                           "typedConfig": {
-                              "@type": "type.googleapis.com/udpa.type.v1.TypedStruct",
-                              "typeUrl": "type.googleapis.com/envoy.extensions.filters.network.wasm.v3.Wasm",
-                              "value": {
-                                    "config": {
-                                             "configuration": "{\n  \"debug\": \"false\",\n  \"stat_prefix\": \"istio\"\n}\n",
-                                             "root_id": "stats_outbound",
-                                             "vm_config": {
-                                                      "code": {
-                                                               "local": {
-                                                                        "inline_string": "envoy.wasm.stats"
-                                                                     }
-                                                            },
-                                                      "runtime": "envoy.wasm.runtime.null",
-                                                      "vm_id": "tcp_stats_outbound"
-                                                   }
-                                          }
-                                 }
-                           }
-                        },
-                        {
-                           "name": "envoy.tcp_proxy",
-                           "typedConfig": {
-                              "@type": "type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy",
-                              "statPrefix": "outbound|27017||mongodb.mongodb.svc.cluster.local",
-                              "cluster": "outbound|27017||mongodb.mongodb.svc.cluster.local"
-                           }
-                        }
-                     ]
-                  }
-               ],
-               "deprecatedV1": {
-                  "bindToPort": false
-               },
                "trafficDirection": "OUTBOUND"
             }
          }
       },
       {
          "activeState": {
             "listener": {

Routes Match (RDS last loaded at Thu, 13 Aug 2020 15:52:42 EDT)
```
We have tried waiting up to 5 minutes in between `kubectl delete` and `kubectl apply` commands which did not fix the issue. The `proxy-status` command reports out of sync even 10 minutes after the headless service is reapplied.
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio 1.6.5
kubectl 1.18.3
**How was Istio installed?**
using the default profile. 
**Environment where bug was observed (cloud vendor, OS, etc)**
microk8s
