### ISSUE TITLE
[mutatingwebhook] replace sidecarInjectorWebhook.objectSelector.autoInject by global.proxy.autoInject

### ISSUE THREAD

**Issue by hobbytp** [istio/istio#26505]
**Bug description**
In mutatingwebhook.yaml I think {{- if .Values.sidecarInjectorWebhook.objectSelector.autoInject }} shall be changed to use {{- if eq  .Values.global.proxy..autoInject "disable" }}, Otherwise user need to modify 2 places when they want to enable/disable auto injection during installation, and easy to miss the 2nd place in mutatingwebhook.yaml

The mutatingwebhook.yaml snippet is as below:
```yaml
{{- if .Values.sidecarInjectorWebhook.objectSelector.enabled }}
    objectSelector:
{{- if .Values.sidecarInjectorWebhook.objectSelector.autoInject }}  #===here shall change to ==>> {{- if eq  .Values.global.proxy..autoInject "enabled" }}
      matchExpressions:
      - key: "sidecar.istio.io/inject"
        operator: NotIn
        values:
        - "false"
{{- else if .Values.revision }}
      matchExpressions:
      - key: "sidecar.istio.io/inject"
        operator: DoesNotExist
      - key: istio.io/rev
        operator: In
        values:
        - {{ .Values.revision }}
{{- else }}
      matchLabels:
        "sidecar.istio.io/inject": "true"
{{- end }}
{{- end }}
```

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
N/A
**Steps to reproduce the bug**
N/A

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio 1.6.2

**How was Istio installed?**
install by using istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
