### ISSUE TITLE
Added environment variable is gone after 1-2 weeks passed

### ISSUE THREAD

**Issue by Arnuphap-Yupuech** [istio/istio#26503]
**Bug description**
Istiod deployment environment variable is missing after applied 1-2 weeks later
We have added **PILOT_SCOPE_GATEWAY_TO_NAMESPACE**="true" in istiod deployment as follow

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: istiod
    istio: pilot
    release: istio
  name: istiod
  namespace: istio-system
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: istiod
        istio: pilot
      containers:
        env:
        ...
        - name: PILOT_TRACE_SAMPLING
          value: "1"
        - name: CONFIG_NAMESPACE
          value: istio-config
        - name: PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_OUTBOUND
          value: "true"
        - name: PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_INBOUND
          value: "false"
        - name: INJECTION_WEBHOOK_CONFIG_NAME
          value: istio-sidecar-injector
        - name: ISTIOD_ADDR
          value: istiod.istio-system.svc:15012
        - name: PILOT_EXTERNAL_GALLEY
          value: "false"
        - name: CLUSTER_ID
          value: Kubernetes
        - name: PILOT_SCOPE_GATEWAY_TO_NAMESPACE
          value: "true"
          ...

```

[ ] Docs
[ X ] Installation
[ X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Environment variable that we have added should not be gone

**Steps to reproduce the bug**
This setting can be last for 1-2 weeks. It can separate our custom gateway in others namespace. After 1-2 weeks, our developer reported unexpected behavior where the development gateway is pointing to another environment. When we check istiod deployment environment variable and found PILOT_SCOPE_GATEWAY_TO_NAMESPACE that we set earlier is gone.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
$ istioctl version --remote
```
client version: 1.5.1
control plane version: 1.5.1
data plane version: 1.5.1 (325 proxies)
```
$ kubectl version
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS
