### ISSUE TITLE
Standalone Istio Operator does not apply tolerations defined for istiod

### ISSUE THREAD

**Issue by fcervantes2** [istio/istio#26522]
**Bug description**
When installing Istio using the operator and IstioOperator custom resource applied, the operator does not honor tolerations applied to pilot (i.e., istiod). This issue is not observed when applying the same IstioOperator custom resource applied via `istioctl manifest apply` command; Tolerations are applied correctly when Installing Istio with CLI.

Example IstioOperator structure:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    pilot:
      k8s:
        tolerations:
          - key: dedicated
            operator: Equal
            value: istio
```

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Tolerations should be applied regardless of how IstioOperator resource is applied (`istioctl manifest apply` or Istio Operator) 

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
control plane version: 1.6.7
data plane version: 1.6.7 (6 proxies)
```

**How was Istio installed?**
Istio Operator:
```
istioctl operator init --operatorNamespace istio-system
```

**Environment where bug was observed (cloud vendor, OS, etc)**
N/A

**Comment by fcervantes2** [comment]
Was looking into it a bit myself and it might be due to a missing `tolerations` in both the `values.yaml` and `deployment.yaml` of `istio-discovery` helm chart: 
* https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
* https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/values.yaml

Checking other charts, such as the gateways, does seem to define `tolerations`.

**Comment by fcervantes2** [comment]
Did a bit more testing and it doesn't seem to be related to what's stated above specifically. It seems it only happens when there is an existing deployment of IstioOperator, which was done via CLI, then migrating to standalone operator.

**Comment by fcervantes2** [comment]
With the release of istio 1.7, and support for canary releases with the operator, it's possible this is fixed. Will test it out in the coming days.

**Comment by peter-fe** [comment]
@fcervantes2,

We observed the same issue on our setups, it used to work with istio 1.5.1 and fails with 1.6.8 and 1.7.0

We don't set the affinity and tolerations as k8s resource, we use the values operator notation and the "Customizable Install with Istioctl" way of installing.

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    gateways:
      istio-ingressgateway:
        type: NodePort
    global:
      defaultNodeSelector:
        node-dedication: istio-pool
      defaultTolerations:
        - key: node-pool
          value: istio-pool
          effect: NoSchedule
```

When you run an "istioctl install -f ../values.yaml" the tolerations & affinity get applied to the **ingress-gateway** and **prometheus** deployments but are completely missing on the **istiod** one.
 
The versions we tested so far:

1.5.1 => works as expected
1.6.8 => missing affinity & tolerations on istiod
1.7.0 => missing affinity & tolerations on istiod

Running an "istioctl manifest generate -f ../values.yaml" shows the same missing affinity & tolerations, so I would assume they are missing in the internal charts.
