### ISSUE TITLE
Links inside Grafana Dashboards to other Dashboards are Absolute

### ISSUE THREAD

**Issue by opnarius** [istio/istio#26544]
**Bug description**
Built in Grafna dashboards are not linked correctly when Grafana is exposed under sub-path.

Specifically `istio-mesh-dashboard` and it's linking to `istio-workload-dashboard`. When Grafana is served from sub-path the link from `istio-mesh-dashboard` to `istio-workload-dashboard` ignores the sub-path. I believe the issue to be that the `istio-mesh-dashboard` is using absolute url `/dashboard`, https://github.com/istio/istio/blob/master/manifests/addons/dashboards/istio-mesh-dashboard.json#L728 .

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
When clicking on a service inside `istio-mesh-dashboard` the `istio-workload-dashboard` loads following the created sub-path

**Steps to reproduce the bug**
1. Expose Grafana using virtual service with sub-path. 
2. Navigate to `{ingess-url}/grafana/`
3. Select Istio Mesh Dashboard 
4. Locate HTTP/GRPC Workloads panel and click on any service.
5. Browser is redirected to `{ingess-url}/dashboard/db/istio-service-dashboard` without `/grafana` sub-path.

Relevant operator config:
```yaml
grafana:
  env:
    GF_SERVER_ROOT_URL: "https://my-custom-domain.example/grafana/"
    GF_SERVER_DOMAIN: "my-custom-domain.example"
    GF_SERVER_SERVE_FROM_SUB_PATH: "false"
    GF_PANELS_DISABLE_SANITIZE_HTML: "true"
```

Virtual Service:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: xea-smart-virtual-service
spec:
  hosts:
  - "my-custom-domain.example"
  gateways:
  - istio-system/istio-ingressgateway
  http:
  - match:
    - uri:
        prefix: /grafana/
      ignoreUriCase: true
    - uri:
        prefix: /grafana
      ignoreUriCase: true
    route:
    - destination:
        port:
          number: 3000
        host: grafana.istio-system.svc.cluster.local
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
client version: 1.5.2
control plane version: 1.5.2
data plane version: 1.5.2 (150 proxies)
```

**How was Istio installed?**
Operator install 

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by douglas-reid** [comment]
@carolynhu can you add this to your list of things to look at when reviewing the dashboards?

**Comment by carolynhu** [comment]
@douglas-reid yes, will take a look of this.

**Comment by carolynhu** [comment]
Hi @opnarius, I could not reproduce your issue. Also, the yaml you provided looks not correct, like the way you set gateways: ` - istio-system/istio-ingressgateway` (should be name followed by namespace, also you'd better specify the namespace). In the `spec.http` section, you have duplicate match uri, also, your indentation has issues in that section as well. Could you provide your whole working file, like your `kind: Gateway` yaml, and `kind: DestinationRule` yaml.  Thanks.

**Comment by opnarius** [comment]
@carolynhu I've updated virtual service yaml. The ingress gateway is the default object as deployed by Istio Operator.

**Comment by carolynhu** [comment]
Hi @opnarius we are able to reproduce your issue, i mean reproduce is to get all things setup as your ways. And everything works fine when we visit the Mesh Dashboard and Workload Dashboard, they do have a prefix of `/grafana` there (the url looks like: http://34.122.248.187/grafana/d/G8wLrJIZk/istio-mesh-dashboard?orgId=1).

One thing I noticed that your setting of those env var for grafana is incorrect, where the `GF_SERVER_SERVE_FROM_SUB_PATH` should be set to be "true". Please ref here: https://grafana.com/tutorials/run-grafana-behind-a-proxy/#1 to make correct reverse proxy setting, thanks!

**Comment by kjetillilleby** [comment]
Hi,
I have tried all the suggestions here, but I still get the wrong links in the mesh dashboard. 
I install grafana through a helm chart. and I'm exposing it through oauth2 reverse proxy. 
values.yaml:
```yaml
# https://artifacthub.io/packages/helm/grafana/grafana
image:
  tag: 7.2.1

service:
  port: 3000
  portName: http

grafana.ini:
  server:
    root_url: "%(protocol)s://%(domain)s/system/grafana"
    serve_from_sub_path: true
  auth.basic:
    enabled: false
  auth.anonymous:
    enabled: true
    org_role: Admin  # Viewer, Editor or Admin

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus:9090
      access: proxy
      isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        options:
          path: /var/lib/grafana/dashboards/default
      - name: 'istio'
        orgId: 1
        folder: 'istio'
        type: file
        disableDeletion: false
        options:
          path: /var/lib/grafana/dashboards/istio
      - name: 'istio-services'
        orgId: 1
        folder: 'istio'
        type: file
        disableDeletion: false
        options:
          path: /var/lib/grafana/dashboards/istio-services

dashboards:
  default:
    prometheus-stats:
      # Ref: https://grafana.com/dashboards/2
      gnetId: 2
      revision: 2
      datasource: Prometheus
  istio:
    istio-mesh:
      # Ref: https://grafana.com/dashboards/7639
      gnetId: 7639
      revision: 46  # update to match istio version
      datasource: Prometheus
    istio-control-plane:
      # Ref: https://grafana.com/dashboards/7645
      gnetId: 7645
      revision: 46  # update to match istio version
      datasource: Prometheus
    istio-mixer:
      # Ref: https://grafana.com/dashboards/7642
      gnetId: 7642
      revision: 46  # update to match istio version
      datasource: Prometheus
    istio-workload:
      # Ref: https://grafana.com/dashboards/7630
      gnetId: 7630
      revision: 46  # update to match istio version
      datasource: Prometheus
    istio-performance:
      # Ref: https://grafana.com/dashboards/11829
      gnetId: 11829
      revision: 46  # update to match istio version
      datasource: Prometheus
  istio-services:
    istio-service:
      # Ref: https://grafana.com/dashboards/7636
      gnetId: 7636
      revision: 46  # update to match istio version
      datasource: Prometheus
```
Open the mesh dashboard, then the links for the service and workspace is missing /system/grafana

![grafana](https://user-images.githubusercontent.com/9693382/119665648-e2f1b400-be34-11eb-86e4-17c6c4a0df4c.png)
