### ISSUE TITLE
403 instead of 401 when there's no JWT

### ISSUE THREAD

**Issue by GJKrupa** [istio/istio#26559]
**Bug description**

I have the following configuration in my namespace:

```
apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
  name: "standard-istio-jwt-policy"
  namespace: development
spec:
  selector:
    matchLabels:
        jwt-validation: "true"
  rules:
    - from:
      - source:
          requestPrincipals: ["*"]
    - to:
      - operation:
          paths:
            - /actuator/health
            - /actuator/prometheus
            - /health
            - /metrics
            - /nginx-health
            - /oauth/health
            - /app-health
---
apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
  name: "standard-istio-jwt-policy-system"
  namespace: development
spec:
  selector:
    matchLabels:
      jwt-validation: "true"
  rules:
  - from:
      - source:
          namespaces: ["istio-system", "kube-system", "infrastructure"]
---
apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: "standard-istio-jwt-policy-tmp"
  namespace: development
spec:
  selector:
    matchLabels:
      jwt-validation: "true"
  jwtRules:
    - issuer: "https://my-keycloak/auth/realms/dev"
      jwksUri: "http://my-keycloak/auth/realms/dev/protocol/openid-connect/certs"
      forwardOriginalToken: true
```

When making a simple HTTP request to a labelled pod from another pod in the same namespace with no Authroization header (using curl) I get a 403 instead of a 401 as expected.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Envoy proxy should respond with a 401 Unauthorized because there is no Authorization header.

**Steps to reproduce the bug**

Use the above configuration (or similar) and execute something like `curl -v http://my-labelled-service/`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

Istio: 1.5.8
k8s: v1.14.9-eks-f459c0
helm: v2.14.3

**How was Istio installed?**

Modified Helm chart. mTLS fully enabled in permissive mode, SDS deployed to provide certs.

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS EKS
