### ISSUE TITLE
Ingress Gateway can't access HTTPS backend service

### ISSUE THREAD

**Issue by ronak-agarwal** [istio/istio#26554]
Followed this link - https://github.com/istio/istio/issues/8029, but couldn't make it work.

Same issue as mentioned in the above post, I'm able to make it work with PASSTHROUGH but we have requirement for TLS termination so trying nginx sample & also we need to use our custom certs mounted on ingress gateway (can't use ISTIO_MUTUAL)

**ISSUE** - I tried to set up a gateway and virtual service for an https service (nginx server). But the gateway can only send clear http request to the https service. And the https service return 400 Bad Request - The plain HTTP request was sent to HTTPS port.

I'm using istio 1.6.3, and running on my kind cluster locally.

```
`curl https://client-1.clients.alice.com:31308 -vvv --cacert ca.crt --cert client.crt --key client.key
* Rebuilt URL to: https://client-1.clients.alice.com:31308/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to client-1.clients.alice.com (127.0.0.1) port 31308 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: ca.crt
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS handshake, CERT verify (15):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=client-1.clients.alice.com
*  start date: Aug 17 09:42:23 2020 GMT
*  expire date: Aug 18 09:42:52 2020 GMT
*  issuer: C=GB; ST=England; O=Alice Ltd; OU=Alice Ltd Certificate Authority; CN=Alice Ltd Intermediate CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fb82080a400)
> GET / HTTP/2
> Host: client-1.clients.alice.com:31308
> User-Agent: curl/7.54.0
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
*< HTTP/2 400
*< server: istio-envoy
*< date: Mon, 17 Aug 2020 11:55:28 GMT
*< content-type: text/html
*< content-length: 255
*< x-envoy-upstream-service-time: 3
*<
*<html>
*<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
*<body>
*400 Bad Request
*<center>The plain HTTP request was sent to HTTPS port</center>
*<center>nginx/1.19.2</center>`
```

 **### LOGS in ingress gateway pod -**

[2020-08-17T11:56:41.422Z] "GET / HTTP/2" 400 - "-" "-" 0 255 4 3 "10.244.0.64" "curl/7.54.0" "2b515097-1a44-901c-9da9-36095f523cea" "client-1.clients.alice.com:31308" "10.244.0.65:443" outbound|443||nginx-service.development.svc.cluster.local 10.244.0.64:38048 127.0.0.1:8443 127.0.0.1:40514 client-1.clients.alice.com -

**### Below are yamls**

```

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: development
spec:
 selector:
  app: nginx-container
 ports:
 - name: https
   protocol: TCP
   port: 443
   targetPort: 443

```

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: istio-system
  name: nginx-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 443
      name: https
      protocol: https
    tls:
      mode: MUTUAL
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      caCertificates: /etc/istio/ingressgateway-ca-certs/ca-chain.crt
    hosts:
    - "*"
```

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-virtual-service
  namespace: development
spec:
  hosts:
  - "*"
  gateways:
  - nginx-gateway.istio-system.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: nginx-service.development.svc.cluster.local
        port:
          number: 443
```

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: nginx-mtls
  namespace: development
spec:
  host: nginx-service.development.svc.cluster.local
  trafficPolicy:
    tls:
      mode: MUTUAL
      clientCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      caCertificates: /etc/istio/ingressgateway-ca-certs/ca-chain.crt
    portLevelSettings:
    - port:
        number: 443
      loadBalancer:
        simple: ROUND_ROBIN
```

And I'm successfully able to curl from ingress-gateway using same tls.crt and tls.key

kubectl -n istio-system exec -it $(kubectl -n istio-system get pod -l app=istio-ingressgateway -o jsonpath={.items..metadata.name}) -c istio-proxy -- curl -vvv https://nginx-service.development.svc.cluster.local:443 --cacert /etc/istio/ingressgateway-certs/ca-chain.crt --cert /etc/istio/ingressgateway-certs/tls.crt --key /etc/istio/ingressgateway-certs/tls.key

```
* Rebuilt URL to: https://nginx-service.development.svc.cluster.local:443/
*   Trying 10.99.206.108...
* TCP_NODELAY set
* Connected to nginx-service.development.svc.cluster.local (10.99.206.108) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/istio/ingressgateway-certs/ca-chain.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS handshake, CERT verify (15):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=nginx-service.development.svc.cluster.local
*  start date: Aug 17 12:46:39 2020 GMT
*  expire date: Aug 18 12:47:09 2020 GMT
*  subjectAltName: host "nginx-service.development.svc.cluster.local" matched cert's "nginx-service.development.svc.cluster.local"
*  issuer: C=GB; ST=England; O=Alice Ltd; OU=Alice Ltd Certificate Authority; CN=Alice Ltd Intermediate CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55dc5c077580)
> GET / HTTP/2
> Host: nginx-service.development.svc.cluster.local
> User-Agent: curl/7.58.0
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200
< server: nginx/1.19.2
< date: Mon, 17 Aug 2020 12:51:25 GMT
< content-type: text/html
< content-length: 8626
< last-modified: Mon, 17 Aug 2020 12:47:25 GMT
< etag: "5f3a7c5d-21b2"
< accept-ranges: bytes
<
<html>
<body>
<p>Some secrets:</p>
```

NOTE- As per the link I also tried changing port name of my nginx service from https to http2-myport but it started giving 503, and also my curl from ingress gateway to nginx svc started failing with below error
```
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number
* stopped the pause stream!
* Closing connection 0
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
command terminated with exit code 35
```

```
curl https://client-1.clients.alice.com:31308 -vvv --cacert ca.crt --cert client.crt --key client.key
* Rebuilt URL to: https://client-1.clients.alice.com:31308/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to client-1.clients.alice.com (127.0.0.1) port 31308 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: ca.crt
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS handshake, CERT verify (15):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=client-1.clients.alice.com
*  start date: Aug 17 09:42:23 2020 GMT
*  expire date: Aug 18 09:42:52 2020 GMT
*  subjectAltName: host "client-1.clients.alice.com" matched cert's "client-1.clients.alice.com"
*  issuer: C=GB; ST=England; O=Alice Ltd; OU=Alice Ltd Certificate Authority; CN=Alice Ltd Intermediate CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f96ef009800)
> GET / HTTP/2
> Host: client-1.clients.alice.com:31308
> User-Agent: curl/7.54.0
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 503
< content-length: 95
< content-type: text/plain
< date: Mon, 17 Aug 2020 14:24:03 GMT
< server: istio-envoy
< x-envoy-upstream-service-time: 44
<
* Connection #0 to host client-1.clients.alice.com left intact
upstream connect error or disconnect/reset before headers. reset reason: connection termination
```
