### ISSUE TITLE
istiod getting scheduled on windows nodes.

### ISSUE THREAD

**Issue by jellebens** [istio/istio#26583]
**Bug description**
I have a mixed linux/windows node cluster. I specified the following
```yaml
global:
      # Ensure that the Istio pods are only scheduled to run on Linux nodes
      defaultNodeSelector:
        kubernetes.io/os: linux
```
but this does not seemls to be taken into consederation when deploying addons nor istiod

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
When setting default nodeselector  to kubernetes.io/os: linux that it takes it into consuderation

**Steps to reproduce the bug**
deploy with the above snippet

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
isitoctl 1.6.8

**How was Istio installed?**
istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
Azure
