### ISSUE TITLE
ingressgateway-certs related volume shall be removed from istio-ingressgateway

### ISSUE THREAD

**Issue by hobbytp** [istio/istio#26598]
**Bug description**
from istio 1.6, the SDS is enabled by default for ingressgateway, but after installation, I still can find following mount point in istio-ingressgateway pod/deployment, but they are useless, user just need to add credentialName in Gateway to enable secret related info. 
```yaml
    - mountPath: /etc/istio/ingressgateway-ca-certs
      name: ingressgateway-ca-certs
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: istio-ingressgateway-service-account-token-jkwds
      readOnly: true
```

From output of "istioctl profile dump demo", I found the following secretVolumes section under values.istio-ingressgateway.

```yaml
        secretVolumes:
        - mountPath: /etc/istio/ingressgateway-certs
          name: ingressgateway-certs
          secretName: istio-ingressgateway-certs
        - mountPath: /etc/istio/ingressgateway-ca-certs
          name: ingressgateway-ca-certs
          secretName: istio-ingressgateway-ca-certs
```

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
secretVolume is not in ingress gateway deployment and pod

**Steps to reproduce the bug**
istioctl install --set profile=demo
check istio-ingressgateway deployment or pod yaml

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio 1.6.8

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
