### ISSUE TITLE
sidecar.istio.io/inject annotation in the pod has No effect

### ISSUE THREAD

**Issue by pantianying** [istio/istio#26600]
**Bug description**
follow https://istio.io/latest/docs/ops/common-problems/injection/#the-result-of-sidecar-injection-was-not-what-i-expected
the namespace does not have label:`istio-injection: enabled`
I want to use pod's annotations overrides the the default policy like this:
```yaml  
template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-inject
      annotations:
        sidecar.istio.io/inject: 'true'
```
but it seem has No effect. At the moment, I want to use auto injection, only the namespace label useful
**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio:1.6.7 ;k8s 1.18
**How was Istio installed?**
istio install
**Environment where bug was observed (cloud vendor, OS, etc)**
openshift 4.5
Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by pantianying** [comment]
oc get mutatingwebhookconfigurations istio-sidecar-injector -o yaml:
![image](https://user-images.githubusercontent.com/20589945/90485419-10a12280-e16a-11ea-9bb9-62a336c46f7e.png)

**Comment by lihuixian001** [comment]
I have the same problem.

It seems that only when "namespaceselector" match,   "sidecar.istio.io/inject" will take effect


https://istio.io/latest/docs/ops/configuration/mesh/injection-concepts/

**Comment by bdschaap** [comment]
Not sure if you experienced  the same problem I was having... but for my issue I finally realized the web hook config and istio injection configmap had similarly named settings that controlled different behavior.  The proxy section below controls the istio injection configmap's **_policy_** setting which uses an **_annotation_** to control its behavior.  The istio injection configmap's policy setting is mentioned in this [blog post](https://istio.io/latest/blog/2019/data-plane-setup/).  The sidecarInjectorWebhook section below controls the web hook config which uses a _**label**_  to control its behavior.  The values of the annotation and the label are both sidecar.istio.io/inject: "true" or "false".  Hope this helps!

```
  values:
    global:
      proxy:
        autoInject: "disabled"
    sidecarInjectorWebhook:
      enableNamespacesByDefault: true   
      objectSelector:
        enabled: false           
          autoInject: false
```
