### ISSUE TITLE
When set outboundTrafficPolicy: mode: REGISTRY_ONLY, internal svc.cluster.local traffic is blocked.

### ISSUE THREAD

**Issue by decewei** [istio/istio#26609]
When set outboundTrafficPolicy: mode: REGISTRY_ONLY, internal svc.cluster.local traffic is blocked when I access a service in a different namespace from a pod. Is this an expected behavior? Do we need to add it to service entry?

If so, what's the way of doing that? I tried the following, but it does NOT work.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: svc.cluster.local
spec:
  hosts:
  - "*.svc.cluster.local"
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  resolution: NONE
  location: MESH_EXTERNAL
```

**Comment by decewei** [comment]
I found a solution using wildcard for accessing services in a namespace. Else I have to manually list every host.

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: svc.cluster.local
spec:
  hosts:
  - "*.namespace.svc.cluster.local"
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: NONE
  location: MESH_INTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: svc-cluster-local-routing
spec:
  hosts:
  - "*.namespace.svc.cluster.local"
  http:
  - route:
    - destination:
        host: "cluster-local-gateway.istio-system.svc.cluster.local"
```
