### ISSUE TITLE
Not possible to configure user egress gateways with SNI proxy using the Istio operator

### ISSUE THREAD

**Issue by casparrolfe** [istio/istio#26635]
**Bug description**

It is not possible to configure user egress gateways like in the below documentation:

https://istio.io/latest/docs/tasks/traffic-management/egress/wildcard-egress-hosts/#wildcard-configuration-for-arbitrary-domains

While it is possible to apply the values to **all** gateways using the passthrough to the Helm API (see: https://github.com/istio/istio/blob/1.6.8/operator/pkg/apis/istio/v1alpha1/values_types.proto#L297-L306), this is not appropriate for a number of reasons, such as not wanting to deploy an SNI proxy on all egress gateway deployments, differences in the SNI proxy config, secret volumes mounted for TLS client certificates shouldn't be mounted to all egress gateways, etc.

It is also not possible to configure additional ports on user gateways without configuring those ports on all egress or ingress gateways.

**Affected product area (please put an X in all that apply)**

[X] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

Should be able to configure the following per ingress/egress gateway, rather than across all:

* additional containers
* ports
* config volumes
* secret volumes

Full example of configurable gateway values using Helm install below:

https://github.com/istio/istio/blob/1.4.10/install/kubernetes/helm/istio/charts/gateways/values.yaml

There are likely other values that are not configurable with the operator install.

**Steps to reproduce the bug**

* Follow the documentation here: https://istio.io/latest/docs/tasks/traffic-management/egress/wildcard-egress-hosts/#wildcard-configuration-for-arbitrary-domains
* Migrate configuration to the operator install
* Automated migration will fail and there is no way to manually migrate the values.

Example of configuration that was possible with Helm, but is no longer possible with the operator install:

```yaml
gateways:
  istio-egressgateway:
    enabled: true
    autoscaleMin: 1
    autoscaleMax: 5
    # ...

  istio-egressgateway-custom:
    enabled: true
    # ...
    additionalContainers:
      - image: nginx
        name: sni-proxy
        volumeMounts:
          - mountPath: /etc/nginx
            name: sni-proxy-config
            readOnly: true
    configVolumes:
      - configMapName: egressgateway-custom-sni-proxy-config
        name: sni-proxy-config
    secretVolumes:
      - mountPath: /etc/istio/my-super-secret-tls-client-certs
        name: my-super-secret-tls-client-certs
        secretName: my-super-secret-tls-client-certs
    ports:
      - name: https
        port: 1337
        targetPort: 1337
      - name: https
        port: 1338
        targetPort: 1338
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

* Istio 1.4.10 to 1.6.8
* Helm v2.16

**How was Istio installed?**

Migration of istio 1.4 Helm install to Istio operator 1.6 install

**Environment where bug was observed (cloud vendor, OS, etc)**

Unlikely to be applicable
