### ISSUE TITLE
"json: cannot unmarshal object into Go value of type []json.RawMessage" when parsing IstioOperator CR

### ISSUE THREAD

**Issue by alesharik** [istio/istio#26640]
**Bug description**
Operator fails to parse IstioOperator CR with message:
```
2020-08-19T10:30:12.611639Z	error	k8s.io/client-go@v0.18.0/tools/cache/reflector.go:125: Failed to list *v1alpha1.IstioOperator: v1alpha1.IstioOperatorList.ListMeta: v1.ListMeta.TypeMeta: Kind: Items: []v1alpha1.IstioOperator: v1alpha1.IstioOperator.Spec: unmarshalerDecoder: json: cannot unmarshal object into Go value of type []json.RawMessage, error found in #10 byte of ...|false}}}}}}],"kind":|..., bigger context ...|ometheus":{"enabled":true,"wasmEnabled":false}}}}}}],"kind":"IstioOperatorList","metadata":{"continu|...
```
**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
Operator should parse CR and try to apply it into cluster
**Steps to reproduce the bug**
<details>
  <summary>
    apply IstioOperator CR
  </summary>

  ```yaml
  apiVersion: install.istio.io/v1alpha1
  kind: IstioOperator
  metadata:
    name: istio
    namespace: istio-system
  spec:
    hub: docker.io/istio
    tag: 1.6.7
    namespace: istio-system
    profile: default
    meshConfig:
      enablePrometheusMerge: true
      h2_upgrade_policy: DO_NOT_UPGRADE
    components:
      base:
        enabled: true
      pilot:
        enabled: true
      policy:
        enabled: true
      telemetry:
        enabled: true
      cni:
        enabled: false
      ingressGateways:
        - enabled: true
          k8s:
            hpaSpec:
              maxReplicas: 2
              scaleTargetRef:
                apiVersion: apps/v1
                kind: Deployment
                name: istio-ingressgateway
              metrics:
                - type: Resource
                  resource:
                    name: cpu
                    targetAverageUtilization: 80
            service:
              ports:
                - name: status-port
                  nodePort: 32710
                  port: 15020
                  targetPort: 15020
                - name: http2
                  nodePort: 31380
                  port: 80
                  targetPort: 80
                - name: https
                  nodePort: 31390
                  port: 443
                  targetPort: 443
              type: NodePort
          name: istio-ingressgateway
        - enabled: true
          name: main-ingressgateway
          labels:
            app: main-ingressgateway
            istio: main-ingressgateway
          k8s:
            hpaSpec:
              maxReplicas: 2
              scaleTargetRef:
                apiVersion: apps/v1
                kind: Deployment
                name: main-ingressgateway
              metrics:
                  - type: Resource
                    resource:
                      name: cpu
                      targetAverageUtilization: 80
            env:
              ISTIO_META_ROUTER_MODE: "sni-dnat"
              ISTIO_META_TLS_SERVER_CERT_CHAIN: "/etc/istio/ingressgateway-certs/chain.crt"
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 2000m
                memory: 1024Mi
            strategy:
              rollingUpdate:
                maxUnavailable: 25%
                maxSurge: 100%
            service:
              type: NodePort
              ports:
                - name: status-port
                  nodePort: 32001
                  port: 15020
                  targetPort: 15020
                - name: http2
                  nodePort: 30002
                  port: 80
                  targetPort: 80
                - name: https
                  nodePort: 30001
                  port: 443
                  targetPort: 443
      egressGateways:
        - name: istio-egressgateway
          enabled: false
          k8s:
            env:
              - name: ISTIO_META_ROUTER_MODE
                value: "sni-dnat"
            service:
              ports:
                - port: 80
                  name: http2
                  targetPort: 8080
                - port: 443
                  name: https
                  targetPort: 8443
                - port: 15443
                  targetPort: 15443
                  name: tls
            hpaSpec:
              maxReplicas: 5
              minReplicas: 1
              scaleTargetRef:
                apiVersion: apps/v1
                kind: Deployment
                name: istio-egressgateway
              metrics:
                - type: Resource
                  resource:
                    name: cpu
                    targetAverageUtilization: 80
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 2000m
                memory: 1024Mi
            strategy:
              rollingUpdate:
                maxSurge: "100%"
                maxUnavailable: "25%"
    addonComponents:
      grafana:
        enabled: false
      istiocoredns:
        enabled: false
      kiali:
        enabled: true
      prometheus:
        enabled: false
    values:
      gateways:
        main-ingressgateway:
          sds:
            enabled: true
            image: node-agent-k8s
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 2000m
                memory: 1024Mi
          secretVolumes:
            - name: ingressgateway-certs
              secretName: istio-ingressgateway-certs
              mountPath: /etc/istio/ingressgateway-certs
            - name: ingressgateway-ca-certs
              secretName: istio-ingressgateway-ca-certs
              mountPath: /etc/istio/ingressgateway-ca-certs
      sidecarInjectorWebhook:
        enableNamespacesByDefault: false
        rewriteAppHTTPProbe: true
        objectSelector:
          enabled: false
          autoInject: true
      istiocoredns:
        coreDNSImage: coredns/coredns
        coreDNSTag: 1.6.2
        coreDNSPluginImage: istio/coredns-plugin:0.2-istio-1.1
      clusterResources: true
      telemetry:
        enabled: true
        v2:
          enabled: true
          prometheus:
            wasmEnabled: false
            enabled: true
      base:
        enableCRDTemplates: false
        validationURL: ""
      pilot:
        autoscaleEnabled: true
        autoscaleMin: 1
        autoscaleMax: 5
        replicaCount: 1
        image: pilot
        traceSampling: 1.0
        cpu:
          targetAverageUtilization: 80
        keepaliveMaxServerConnectionAge: 30m
        enableProtocolSniffingForOutbound: true
        enableProtocolSniffingForInbound: true
        configMap: true
      global:
        istiod:
          enableAnalysis: false
        arch:
          amd64: 2
          ppc64le: 2
          s390x: 2
        configValidation: true
        controlPlaneSecurityEnabled: false
        defaultPodDisruptionBudget:
          enabled: true
        defaultResources:
          requests:
            cpu: 10m
        defaultTolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: master
        disablePolicyChecks: true
        enableHelmTest: false
        enableTracing: true
        imagePullPolicy: IfNotPresent
        logging:
          level: all:warn
        monitoringPort: 15014
        mtls:
          enabled: false
        oneNamespace: false
        outboundTrafficPolicy:
          mode: ALLOW_ANY
        policyCheckFailOpen: false
        priorityClassName: ""
        proxy:
          accessLogEncoding: TEXT
          accessLogFile: ""
          accessLogFormat: ""
          autoInject: enabled
          clusterDomain: cluster.local
          componentLogLevel: filter:error,misc:error
          concurrency: 2
          enableCoreDump: false
          envoyMetricsService:
            enabled: false
          envoyStatsd:
            enabled: false
          excludeIPRanges: ""
          excludeOutboundPorts: ""
          image: proxyv2
          includeIPRanges: '*'
          logLevel: all:warning
          privileged: false
          readinessFailureThreshold: 30
          readinessInitialDelaySeconds: 1
          readinessPeriodSeconds: 2
          resources:
            limits:
              cpu: 2000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 128Mi
          statusPort: 15020
          tracer: zipkin
        proxy_init:
          image: proxyv2
        sds:
          enabled: false
          udsPath: ""
          useNormalJwt: false
          useTrustworthyJwt: false
        useMCP: true
      kiali:
        dashboard:
          grafanaURL: http://monitoring.cloud.tularegion.ru/
          jaegerURL: http://jaeger.cloud.tularegion.ru/
        prometheusAddr: http://prometheus-operated.monitoring.svc.cluster.local:9090/
  ```
</details>

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
client version: 1.6.8
citadel version: 1.4.2
galley version: 1.4.2
pilot version: 1.4.2
policy version: 1.4.2
sidecar-injector version: 1.4.2
telemetry version: 1.4.2
main-ingressgateway version: 
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"archive", BuildDate:"2020-05-01T14:27:52Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce", GitTreeState:"clean", GoVersion:"go1.13.4"}
```
**How was Istio installed?**
Istio was installed via helm and now I am trying to reinstall it using operator
**Environment where bug was observed (cloud vendor, OS, etc)**
Bare Metal Cloud, Debian-like os
