### ISSUE TITLE
AuthorizationPolicy for source IP does not work for IP whitelisting

### ISSUE THREAD

**Issue by faizanbashir** [istio/istio#26656]
**AuthorizationPolicy for source IP does not work for IP whitelisting**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Istio should allow access to the service for requests made from the whitelisted IP as mentioned [here](https://istio.io/latest/docs/tasks/security/authorization/authz-ingress/#ip-based-allow-list-and-deny-list).

**Steps to reproduce the bug**
Update `externalTrafficPolicy` from `Cluster` to `Local`
```
kubectl patch svc istio-ingressgateway -n istio-system -p '{"spec":{"externalTrafficPolicy":"Local"}}'
```
Add the `AuthorizationPolicy`:
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ingress-policy
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  action: ALLOW
  rules:
  - from:
    - source:
        ipBlocks: ["52.24.252.78"]
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
`istioctl version --remote`
```
client version: 1.6.7
control plane version: 1.6.7
data plane version: 1.6.7 (34 proxies)
```
`kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Using IstioOperator:
```
istioctl operator init
```
IstioOperator yaml file:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: fb
  namespace: istio-system
spec:
  profile: demo
  tag: 1.6.7
  hub: docker.io/istio
  addonComponents:
    kiali:
      enabled: true
      k8s:
        replicaCount: 1
    tracing:
      enabled: true
    grafana:
      enabled: true
      k8s:
        replicaCount: 1
    istiocoredns:
      enabled: false
    prometheus:
      enabled: true
      k8s:
        replicaCount: 1
```

**Environment where bug was observed (cloud vendor, OS, etc)**
Cloud: AWS
EKS v1.15
Loadbalancer: ELB
