### ISSUE TITLE
Http 401 unauthorized error in multicluster replicated control plane 1.5.6

### ISSUE THREAD

**Issue by ECuRyDIN** [istio/istio#26661]
Hello,

I have setup multicluster in 2 clusters using replicated control plane following the doc (https://istio.io/v1.5/docs/setup/install/multicluster/gateways/) with mtls enabled. When I try to call service Y (in cluster B) from service X (in cluster A), I get http 401 unauthorized error. I am not able to pinpoint the issue. Can someone help with this? 

$ kubectl exec --context=$CTX_CLUSTER1 $SLEEP_POD -n foo -c sleep – curl -I httpbin.bar.global:8000/headers
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:–:-- --:–:-- --:–:-- 0HTTP/1.1 401 Unauthorized
content-length: 27
content-type: text/plain
date: Mon, 17 Aug 2020 22:14:58 GMT
server: envoy
x-envoy-upstream-service-time: 5

0 27 0 0 0 0 0 0 --:–:-- --:–:-- --:–:-- 0

I checked the envoy proxy of httpbin in cluster 2, here’s the logs:

[Envoy (Epoch 0)] [2020-08-17 20:27:18.589][22][error][filter] [src/envoy/http/authn/authenticator_base.cc:73] [C34] trust domain validation failed: peer trust domain aks-clustera different from local trust domain aks-cluster-b
[Envoy (Epoch 0)] [2020-08-17 20:31:54.551][15][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 13,
[Envoy (Epoch 0)] [2020-08-17 20:43:36.583][22][error][filter] [src/envoy/http/authn/authenticator_base.cc:73] [C37] trust domain validation failed: peer trust domain aks-cluster-a different from local trust domain aks-cluster-b

Istio version: 1.5.6
Kubernetes: 1.16.10

Cluster A Configuration:

```
kubectl apply --context=$CTX_CLUSTER1 -n foo -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin-bar
spec:
  hosts:
  # must be of form name.namespace.global
  - httpbin.bar.global
  # Treat remote cluster services as part of the service mesh
  # as all clusters in the service mesh share the same root of trust.
  location: MESH_INTERNAL
  ports:
  - name: http1
    number: 8000
    protocol: http
  resolution: DNS
  addresses:
  # the IP address to which httpbin.bar.global will resolve to
  # must be unique for each remote service, within a given cluster.
  # This address need not be routable. Traffic for this IP will be captured
  # by the sidecar and routed appropriately.
  - 240.0.0.2
  endpoints:
  # This is the routable address of the ingress gateway in cluster2 that
  # sits in front of sleep.foo service. Traffic from the sidecar will be
  # routed to this address.
  - address: ${CLUSTER2_GW_ADDR}
    ports:
      http1: 15443 # Do not change this port value
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: httpbin-dr
spec:
  host: "*"
  ports:
  - number: 15443
    name: https-istio
    protocol: TLS
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
EOF

```
Cluster B Configuration

```
kubectl apply -n bar -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  selector:
    istio: ingressgateway # use Istio's default ingress gateway
  servers:
  - port:
      name: https-istio
      number: 15443
      protocol: HTTPS
    tls:
      mode: ISTIO_MUTUAL
    hosts:
    - "*" # This can be specific URLs
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-vs
spec:
  hosts:
  - "*" # This can be specific URLs
  gateways:
  - httpbin-gateway
  http:
  - match:
    - uri:
	    prefix: /
    route:
    - destination:
        host: httpbin.bar.svc.cluster.local
        # Optional, but this should be the port that the Service is listening on.
        port:
          number: 80
EOF
```
