### ISSUE TITLE
Operator 1.7 ordering change hpaSpec.minReplicas now overrides values...autoscaleMin 

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#26667]
**Bug description**
Related to https://github.com/istio/istio/issues/25683

2 different ways to specify the HPA scale min/max.  
- values.gateways.istio-egressgateway.autoscaleMin
    - template has https://github.com/istio/istio/blob/1.7.0-rc.2/manifests/charts/gateways/istio-ingress/templates/autoscale.yaml#L12-L13
- components.ingresswateways…hpaSpec.minReplicas
   - profile has https://github.com/istio/istio/blob/1.7.0-rc.2/manifests/profiles/default.yaml#L134-L136

In 1.6, the values section would override the hpaSpec section, that appears to be reversed in 1.7.

Using this used to work in 1.6, but does not in 1.7, the hpaSpec is overriding this now.
```
values:
    gateways:
      istio-egressgateway:
        autoscaleMin: 2
      istio-ingressgateway:
        autoscaleMin: 2
```

Seems like the processing order changed here. Wanted to confirm this before I made a change.
For istiod, the values.pilot section is still working for min/max.

Questions
- Was this change intended?   
- if yes, What is the purpose of the old value section then?   Should be removed?

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

values section would continue to override the component section for hpa values.

**Steps to reproduce the bug**

using 1.7 rc.2 with iop
```
spec:
  values:
    gateways:
      istio-ingressgateway:
        autoscaleMin: 2
```

hpa min scale will remain at  default of 1.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.7 rc.2

**How was Istio installed?**

operator controller pod

**Environment where bug was observed (cloud vendor, OS, etc)**
