### ISSUE TITLE
EndUserAuthenticationSpec not allowing http

### ISSUE THREAD

**Issue by kameshsampath** [istio/istio#2668]
When configuring EndUserAuthenticationSpec the `istioctl create -f <auth_config>` is throwing validation error as `* jwks_uri must have http:// or https:// scheme` inspite of the jwks_uri having right http scheme.  Though the same works with `oc apply -f  <auth_config>`. The configuration used is as follows:

```
--- 
apiVersion: config.istio.io/v1alpha2
kind: EndUserAuthenticationPolicySpec
metadata: 
  name: cars-api-auth-policy
  namespace: myproject
spec: 
  jwts: 
    - issuer: http://keycloak-myproject.192.168.64.50.xip.io/auth/realms/istio
      jwks_uri: https://keycloak-myproject.192.168.64.50.xip.io/auth/realms/istio/protocol/openid-connect/certs
      audiences: 
        - cars-web     
--- 
apiVersion: config.istio.io/v1alpha2
kind: EndUserAuthenticationPolicySpecBinding
metadata:
  name: cars-api-auth-policy-binding
  namespace: myproject
spec:
  policies:
    - name: cars-api-auth-policy
      namespace: myproject
  services:
    - name: cars-api
      namespace: myproject
```
