### ISSUE TITLE
Egress gateway traffic for multiple ports on the same host

### ISSUE THREAD

**Issue by Freakazoid182** [istio/istio#26689]
**Describe the feature request**

This is more of a question and possibly a feature request if there is no valid option to resolve an issue we are facing.

We are running an application on a AKS cluster and like to connect to an Azure SQL Server Database through the egress gateway.

As we are running everything within Azure, the application's SQL client will connect through the `Redirect` connection policy as described here:

https://docs.microsoft.com/en-us/azure/azure-sql/database/connectivity-architecture#connection-policy

>Redirect (recommended): Clients establish connections directly to the node hosting the database, leading to reduced latency and improved throughput. For connections to use this mode, clients need to:
> - Allow outbound communication from the client to all Azure SQL IP addresses in the region on ports in the range of 11000 11999. Use the Service Tags for SQL to make this easier to manage.
> - Allow outbound communication from the client to Azure SQL Database gateway IP addresses on port 1433.

![image](https://user-images.githubusercontent.com/5238563/90766967-a9f84200-e2ec-11ea-90a6-841a5be565ed.png)

It looks like this means we'll need to be able to establish a connection for a single hostname or IP for port 1433 (gateway) + port range 11000-11999. 

The trouble that we're are facing is that traffic between the application sidecar proxy and the egress gateway workload is done through port 443. The sidecar proxy can receive the request on any of the ports above, and needs to send it through on port 443 to the egress gateway. The egress gateway receives the request and matches on port 443 and the SNI hostname. The port the original request was intended for is sadly lost in the mean time, so it's not possible to set the correct port for the destination.

The manifests below work for connecting only through port 1433, which will work for the `Proxy` connection strategy. But is there any proper way (or workaround) to make sure the egress gateway proxies to the destination port from the original request of the application dynamically? If not, then would it be possible to introduce such a feature?

```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: sql-tls
spec:
  hosts:
  - <azure sql hostname>
  location: MESH_EXTERNAL
  ports:
  - name: tls
    number: 443
    protocol: TLS
  - name: tls-1433
    number: 1433
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: istio-egressgateway-for-sql-tls
  namespace: istio-system
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: sql-tls
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-egressgateway-sql-tls
spec:
  selector:
    istio: egressgateway
  servers:
  - hosts:
    - <azure sql hostname>
    port:
      name: tls
      number: 443
      protocol: TLS
    tls:
      mode: PASSTHROUGH
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: direct-sql-tls-through-egress-gateway
spec:
  gateways:
  - istio-egressgateway-sql-tls
  - mesh
  hosts:
  - <azure sql hostname>
  tls:
  - match:
    - gateways:
      - mesh
      port: 1433
      sniHosts:
      - <azure sql hostname>
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        port:
          number: 443
        subset: sql-tls
      weight: 100
  - match:
    - gateways:
      - istio-egressgateway-sql-tls
      port: 443
      sniHosts:
      - <azure sql hostname>
    route:
    - destination:
        host: <azure sql hostname>
        port:
          number: 1433
      weight: 100

```

**Describe alternatives you've considered**

We could force the SQL Server to use the `Proxy` connection strategy, so we only have to port 1433 to deal with. But this is not the recommended strategy and could start causing us latency and/or throughput issues.

Another alternative would be to make an exception for these SQL connections and allow directly connecting from the sidecar proxies. This doesn't have our preference though, as we are working to control all outbound traffic through the egress gateway workloads. 

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
