### ISSUE TITLE
If containerPort < 1024, envoy segfaults

### ISSUE THREAD

**Issue by sdake** [istio/istio#26690]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
If the container port specified is <= 1024, Envoy segfaults. This occurs because Envoy needs CAP_NET to bind to ports 1024 and below. In 1.7 a change was introduced to ensure Envoy does not run as UID 0. This is a good change, however, Envoy should recognize the listener ports it can't respond on and appropriately fail, rather than continuously segfault.

**Affected product area (please put an X in all that apply)**
Istio 1.7.0-rc3

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
No segfault.

**Steps to reproduce the bug**
Install knative following existing upstream documentation. Specifically:

Use this file for `isito-minimal-operator.yaml`

```
cat << EOF > ./istio-minimal-operator.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      proxy:
        autoInject: disabled
      useMCP: false
      # The third-party-jwt is not enabled on all k8s.
      # See: https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens
      jwtPolicy: first-party-jwt

  addonComponents:
    pilot:
      enabled: true
    prometheus:
      enabled: false

  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
      - name: cluster-local-gateway
        enabled: true
        label:
          istio: cluster-local-gateway
          app: cluster-local-gateway
        k8s:
          service:
            type: ClusterIP
            ports:
            - port: 15020
              name: status-port
            - port: 80
              name: http2
            - port: 443
              name: https
EOF
 ./istioctl manifest generate -f istio-minimal-operator.yaml --set values.gateways.istio-egressgateway.enabled=false --set values.gateways.istio-ingressgateway.sds.enabled=true --set values.gateways.istio-ingressgateway.autoscaleMin=3 --set values.gateways.istio-ingressgateway.autoscaleMax=6 --set values.pilot.autoscaleMin=3 --set values.pilot.autoscaleMax=6 > istio-1.7.0.yaml
kubectl apply -f istio-1.7.0.yaml
kubectl apply --filename https://github.com/knative/serving/releases/download/v0.16.0/serving-crds.yaml
kubectl apply --filename https://github.com/knative/serving/releases/download/v0.16.0/serving-core.yaml
kubectl apply --filename https://github.com/knative/net-istio/releases/download/v0.16.0/release.yaml

```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istioctl 1.7.0 rc3

**How was Istio installed?**
see above.

**Environment where bug was observed (cloud vendor, OS, etc)**
virtual machine cluster using metallb across 15 worker nodes. 4cpu + 16gb ram per node.

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

A working IOP is:
```
sdake@scale-cp:~$ more istio-minimal-operator.yaml 
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      proxy:
        autoInject: disabled
      useMCP: false
      # The third-party-jwt is not enabled on all *8s.
      # See: https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens
      # This should be enabled......
      jwtPolicy: first-party-jwt

  addonComponents:
    pilot:
      enabled: true
    prometheus:
      enabled: false

  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
      - name: cluster-local-gateway
        enabled: true
        label:
          istio: cluster-local-gateway
          app: cluster-local-gateway
        k8s:
          service:
            type: ClusterIP
            ports:
            - name: status-port
              port: 15021
              targetPort: 15021
            - name: http2
              port: 80
              targetPort: 8080
            - name: https
              port: 443
              targetPort: 8443
```
