### ISSUE TITLE
Unable to edit HTTP_ROUTE with EnvoyFilter

### ISSUE THREAD

**Issue by GregHanson** [istio/istio#26692]
**Bug description**

While attempting to replicate the following behavior using Envoy [direct response](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-route-direct-response), there is currently not a clean way to implement with EnvoyFilter

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.bluemix.net/server-snippets: |
      resolver kube-dns.kube-system.svc.cluster.local valid=5s;
      location /health {
        add_header Content-Type "application/json";
        return 200 "{ \"healthy\": true, \"message\": \"$host OK\" }";
      }
```

Using sleep and httpbin sample applications and the following EnvoyFilter:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: gihanson
spec:
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: SIDECAR_OUTBOUND
      routeConfiguration:
        portNumber: 8000
        vhost:
          name: "httpbin.default.svc.cluster.local:8000"
    patch:
      operation: INSERT_FIRST
      value:
        name: "aaaa"
        match:
          prefix: "/headers"
        directResponse:
          body:
            inlineString: '{"message":"direct response"}'
          status: 400
        responseHeadersToAdd:
        - append: false
          header:
            key: "content-type"
            value: "application/json"
```

The correct `route` object is generated, but the order of the routes is such that the default route `/` will always be selected and never the direct response

```
                "routes": [
                    {
                        "name": "default",
                        "match": {
                            "prefix": "/"
                        },
                        "route": {
                            "cluster": "outbound|8000||httpbin.default.svc.cluster.local",
                             ...
                             ...
                    },
                    {
                        "name": "aaaa",
                        "match": {
                            "prefix": "/headers"
                        },
                        "directResponse": {
                            "status": 400,
                            "body": {
                                "inlineString": "{\"message\":\"direct response\"}"
                            }
                        },
                        "responseHeadersToAdd": [
                            {
                                "header": {
                                    "key": "content-type",
                                    "value": "application/json"
                                },
                                "append": false
                            }
                        ]
                    }
```

If you create a VirtualService to define the `/headers` API, it is inserted before the default route.  The problem then is that this generated route does not contain a `name` field to match against in the EnvoyFilter matching criteria so it cannot be modified via MERGE operation without also impacting the default route as well.  The only way to isolate which route is impacted by the MERGE is to define a dummy redirect in the VirtualService so that `route.action.REDIRECT` can be used in the matching criteria

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: gihanson
spec:
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: SIDECAR_OUTBOUND
      routeConfiguration:
        portNumber: 8000
        vhost:
          name: "httpbin.default.svc.cluster.local:8000"
          route:
            action: REDIRECT
    patch:
      operation: MERGE
      value:
        name: "aaaa"
        match:
          prefix: "/headers"
        directResponse:
          body:
            inlineString: '{"message":"direct response"}'
          status: 400
        responseHeadersToAdd:
        - append: false
          header:
            key: "content-type"
            value: "application/json"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: gihanson
spec:
  hosts:
  - httpbin
  http:
  - match:
    - uri:
        prefix: "/headers"
    redirect:
      uri: "/dummy"
      authority: httpbin
  - route:
    - destination:
        host: httpbin
```

Either the proper `INSERT_FIRST` behavior should be supported for EnvoyFilter `HTTP_ROUTE` filters, or RDS api should add a `name` field for routes generated as a result of VirtualService rules so that they can be edited using `MERGE` operations

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
