### ISSUE TITLE
Gateway replies with 404 after upgrade

### ISSUE THREAD

**Issue by anton-yurchenko** [istio/istio#26695]
**Bug description**
Gateway always returns 404 after an upgrade on any version higher (including) 1.6.6.

I have encountered that issue when I tried to upgrade from 1.6.0->1.6.8. Basically I was able to go all the way from 1.6.0->1.6.5 with no issues but any further upgrade (1.6.6-1.6.8) resulted in the same behavior when a gateway was not forwarding the traffic to the services.
There is no issue inside the cluster, services are able to talk to one another, only external traffic is affected.

Upgrade is performed (target version binary) by: `istioctl upgrade -f operator.yaml`
*Same results with `istioctl install -f operator.yaml`*

**Affected product area (please put an X in all that apply)**

[ ] Docs
[x] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
Requests that match the path should be forwarded to a service.

**Steps to reproduce the bug**
Here is an example from one of my applications:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app: app
spec:
  gateways:
  - domain-a.istio-system.svc.cluster.local
  hosts:
  - host.domain.com
  http:
  - match:
    - uri:
        prefix: /app/
    rewrite:
      uri: /
    route:
    - destination:
        host: app.namespace.svc.cluster.local
        port:
          number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  labels:
    app: app
spec:
  host: app.namespace.svc.cluster.local
  trafficPolicy:
    portLevelSettings:
    - loadBalancer:
        simple: LEAST_CONN
      port:
        number: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: app
  sessionAffinity: None
  type: ClusterIP
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
**istioctl version --remote**:```
client version: 1.6.5
control plane version: 1.6.5
data plane version: 1.6.5 (19 proxies)
```

**kubectl version**:```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:51:23Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**helm version**: `version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}`

**How was Istio installed?**
`istioctl install -f operator.yaml`

**operator.yaml**:
```yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioOperator
spec:
  profile: default
  components:
    pilot:
      k8s:
        hpaSpec:
          minReplicas: 2
    ingressGateways:
      - name: ingressgateway-domain-a
        namespace: istio-system
        enabled: true
        label:
          domain: domain-a
        k8s:
          hpaSpec:
            minReplicas: 2
          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-type: nlb
            service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
            service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
            service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <acm-arn>
            service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
            external-dns.alpha.kubernetes.io/hostname: <hosname>
          overlays:
            - kind: Service
              name: ingressgateway-domain-a
              patches:
                - path: spec.loadBalancerSourceRanges
                  value:
                    - 0.0.0.0/0
      - name: ingressgateway-domain-b
        namespace: istio-system
        enabled: true
        label:
          domain: domain-b
        k8s:
          hpaSpec:
            minReplicas: 2
          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-type: nlb
            service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
            service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
            service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <acm-arn>
            service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
            external-dns.alpha.kubernetes.io/hostname: <hostname>
          overlays:
            - kind: Service
              name: ingressgateway-domain-b
              patches:
                - path: spec.loadBalancerSourceRanges
                  value:
                    - 0.0.0.0/0
  values:
    global:
      proxy:
        excludeIPRanges: 169.254.169.254/32
    prometheus:
      enabled: false
```

**gateways.yaml**:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: domain-a
  namespace: istio-system
  labels:
    release: istio
spec:
  selector:
    istio: ingressgateway
    domain: domain-a
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*.domain-a"
    - port:
        number: 443
        name: https
        protocol: HTTP
      hosts:
        - "*.domain-a"
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: domain-b
  namespace: istio-system
  labels:
    release: istio
spec:
  selector:
    istio: ingressgateway
    domain: domain-b
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*.domain-b"
    - port:
        number: 443
        name: https
        protocol: HTTP
      hosts:
        - "*.domain-b"
```

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS 1.16/1.17

*P.S: not sure why, but `istioctl analyze -A` returns: `Error [IST0101] (VirtualService app.namespace) Referenced gateway not found: "domain-a.istio-system.svc.cluster.local"`*
