### ISSUE TITLE
Multi-level Wildcard Ordering

### ISSUE THREAD

**Issue by Veraticus** [istio/istio#26715]
**Bug description**

I have a gateway with two hosts, like this:

```
- *.test.com
- *.id.test.com
```

And two virtualServices like this:

```
hosts:
- *.test.com
match:
  - uri:
    prefix: /
```

```
hosts:
- *.id.test.com
match:
  - uri:
    prefix: /
```

It seems like no matter what I do the less-specific wildcard (`*.test.com`) is chosen every time over the more-specific wildcard (`*.id.test.com`). Is this expected behavior? Should multi-level wildcards not reside in the same host?

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

Via `istioctl`.

**Environment where bug was observed (cloud vendor, OS, etc)**
