### ISSUE TITLE
Workloads named "y" reports wrong telemetry

### ISSUE THREAD

**Issue by lucasponce** [istio/istio#26717]
A workload named "y" introduces a bug in the Istio telemetry stack:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "y"
spec:
  selector:
    matchLabels:
      app: "y"
      version: v1
  replicas: 1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: "y"
        version: v1
    spec:
      containers:
        - name: "y"
          image: kiali/demo_error_rates_server:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          securityContext:
            privileged: false
          env:
            - name: CODE_REQUESTS
              value: "200,9;500,1"
---
apiVersion: v1
kind: Service
metadata:
  name: "y"
  labels:
    app: "y"
spec:
  ports:
    - name: http
      port: 8888
  selector:
    app: "y"
```

At some point, the workload name is parsed internally as a "true"  value that reaches the prometheus metric label:

```
destination_workload="true"
```

```
istio_requests_total{app="d",connection_security_policy="unknown",destination_app="y",destination_canonical_revision="v1",destination_canonical_service="y",destination_principal="spiffe://cluster.local/ns/alpha/sa/default",destination_service="y.alpha.svc.cluster.local",destination_service_name="y",destination_service_namespace="alpha",destination_version="v1",destination_workload="true",destination_workload_namespace="alpha",instance="172.17.0.15:15020",istio_io_rev="default",job="kubernetes-pods",kubernetes_namespace="alpha",kubernetes_pod_name="d-bcfb9b7d5-d6wpj",pod_template_hash="bcfb9b7d5",reporter="source",request_protocol="http",response_code="200",response_flags="-",security_istio_io_tlsMode="istio",service_istio_io_canonical_name="d",service_istio_io_canonical_revision="v1",source_app="d",source_canonical_revision="v1",source_canonical_service="d",source_principal="spiffe://cluster.local/ns/alpha/sa/default",source_version="v1",source_workload="d",source_workload_namespace="alpha",version="v1"}
```

We have detected this using Kiali for some experiments where clients were named a,b,c and servers x,y,z

https://github.com/kiali/kiali/issues/3143
