### ISSUE TITLE
istioctl experimental add-to-mesh  will change the deploy ownerReferences

### ISSUE THREAD

**Issue by tanjunchen** [istio/istio#26720]
**Bug description**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Sidecar injection does not modify the OwnerReferences of the original deploy

**Steps to reproduce the bug**

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ratings-test
    version: v1
  name: ratings-test
  ownerReferences:
  - apiVersion: release.xxx.io/v1alpha1
    kind: Release
    name: ratings-test
    uid: f95356d1-e2a3-xxxx-8cd8-005056930daa=
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ratings-test
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ratings-test
        version: v1
    spec:
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: docker.io/istio/examples-bookinfo-ratings-v1:1.15.0
        imagePullPolicy: IfNotPresent
        name: c0
        resources:
          limits:
            cpu: 600m
            memory: 500Mi
          requests:
            cpu: 600m
            memory: 500Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: false
      terminationGracePeriodSeconds: 30
```

1. kubectl apply -f test.yaml 
2. istioctl x add-to-mesh deployment ratings-test
3. kubectl get deploy -o yaml, and see the content of yaml，OwnerReferences disappeared

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
[root@vm10-master ~]# istioctl version --remote
client version: 1.6.0
control plane version: 1.6.0
data plane version: 1.6.0 (4 proxies)
```

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
