### ISSUE TITLE
Istio 1.7: "rewriteAppHTTPProbe=false" results in "connection reset" for probe endpoints. Works in Istio 1.6.x

### ISSUE THREAD

**Issue by alecor191** [istio/istio#26737]
**Bug description**
We have pods that expose liveness and readiness endpoints on ports other than the service port (e.g. probe endpoints on port 8800, service port 80). Isito is configured with `sidecarInjectorWebhook.rewriteAppHTTPProbe=false`. 

This setup **worked fine in Istio 1.6.x.**

Starting **Istio 1.7.0 this fails**. We observe:

- Probe requests don't reach the pods anymore
- K8S considers pods unhealthy as requests to readiness probe endpoint result in `Readiness probe failed: Get http://10.1.0.16:8800/ready: read tcp 10.1.0.1:33932->10.1.0.16:8800: read: connection reset by peer`

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

K8S is able to send requests to the liveness and readiness endpoints of our pods successfully as it did in 1.6.x.

**Steps to reproduce the bug**

- Setup K8S cluster with Istio 1.7 (tried both with Docker Desktop as well as AKS cluster) with the following configuration:

  - `sidecarInjectorWebhook.rewriteAppHTTPProbe=false`
  - Configure Istio with requiring `STRICT` mode:

    ```yaml
    apiVersion: security.istio.io/v1beta1
    kind: PeerAuthentication
    metadata:
      name: default
      namespace: istio-system
    spec:
      mtls:
        mode: STRICT
    ```

- Deploy a pod that exposes liveness and readiness endpoints on a port other than the service port

  ```yaml
  containers:
    - name: myapp
      ...
      ports:
        - containerPort: 80
          protocol: TCP
      ...
      livenessProbe:
        httpGet:
          path: /live
          port: 8800
          scheme: HTTP
          ...
      readinessProbe:
        httpGet:
          path: /ready
          port: 8800
          scheme: HTTP
          ...
      ...
  ```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```shell
istioctl version --remote

client version: 1.7.0
control plane version: 1.7.0
data plane version: 1.7.0 (8 proxies)

kubectl version

Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.7", GitCommit:"5737fe2e0b8e92698351a853b0d07f9c39b96736", GitTreeState:"clean", BuildDate:"2020-06-24T19:54:11Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

helm version

version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}
```

**How was Istio installed?**

```shell
istioctl install -s profile=default -f "istioctl-params.yml"
```

where `istioctl-params.yml` looks as follows:

```yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  components:
    cni:
      namespace: kube-system
      enabled: true
  values:
    global:
      jwtPolicy: third-party-jwt
      proxy:
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
    sidecarInjectorWebhook:
      rewriteAppHTTPProbe: false
    gateways:
      istio-ingressgateway:
        serviceAnnotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
          service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "<redacted>"
        loadBalancerIP: "<redacted>"
        sds:
          enabled: true
    cni:
      excludeNamespaces:
        - istio-system
        - kube-system
        - kube-public
        - kube-node-lease
      logLevel: info
```

**Environment where bug was observed (cloud vendor, OS, etc)**

- AKS
- Docker Desktop (Windows 10)

**Comment by sdake** [comment]
@howardjohn - You are right, this does appear on by default, however...

From values.yaml encoded in the manifest after running `./istioctl manifest generate -f ./manifest.yaml --set revision=v170 > z
`:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-sidecar-injector-v170
  namespace: istio-system
  labels:
    istio.io/rev: v170
    release: istio
data:
...
      "istio_cni": {
        "enabled": true
      },
      "revision": "v170",
      "sidecarInjectorWebhook": {
        "alwaysInjectSelector": [],
        "enableNamespacesByDefault": false,
        "injectLabel": "istio-injection",
        "injectedAnnotations": {},
        "neverInjectSelector": [],
        "objectSelector": {
          "autoInject": true,
          "enabled": false
        },
        "rewriteAppHTTPProbe": false
      }
    }
```

Everywhere else revision is set to default if revision is not set except the values.yaml encoding:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-sidecar-injector
  namespace: istio-system
  labels:
    istio.io/rev: default
```
...
      "istio_cni": {
        "enabled": true
      },
      "revision": "",
      "sidecarInjectorWebhook": {
        "alwaysInjectSelector": [],
        "enableNamespacesByDefault": false,
        "injectLabel": "istio-injection",
        "injectedAnnotations": {},
        "neverInjectSelector": [],
        "objectSelector": {
          "autoInject": true,
          "enabled": false
        },
        "rewriteAppHTTPProbe": false
      }
```

I am unclear if the revision field should be set to default to match the rest of the system during a fresh installation in values.yaml nor how that field is used.

Feels like there are a couple of issues at play here - I am in a hotel until 3pm before I have access to my cluster to take a look.

Cheers,
-steve
