### ISSUE TITLE
ExternalIPs of ingressgateway not effect using helm values

### ISSUE THREAD

**Issue by cwocwo** [istio/istio#26736]
**Bug description**
Istio version: 1.6.8
kubernetes version: 1.14.3
Use operator installing istio and set externalIPs in helm values:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  addonComponents:
    prometheus:
      enabled: false
  values:
    gateways:
      istio-ingressgateway:
        type: NodePort
        externalIPs: ["10.110.22.99"]
```
The externalIP of istio-ingressgateway service was none.
```
NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP    PORT(S)                                                      AGE
istio-ingressgateway   NodePort    10.150.42.122   <none>   15021:30749/TCP,80:32591/TCP,443:31002/TCP,15443:30959/TCP   15m
```

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
The istio-ingressgateway service should have an externalIP as `10.110.22.99`
```
NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP    PORT(S)                                                      AGE
istio-ingressgateway   NodePort    10.150.42.122   10.110.22.99   15021:30749/TCP,80:32591/TCP,443:31002/TCP,15443:30959/TCP   20m
```

**Steps to reproduce the bug**
- init istio operator
```
istioctl operator init
```
- install istio
```
cat <<EOF | kubectl apply -f -
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  addonComponents:
    prometheus:
      enabled: false
  values:
    gateways:
      istio-ingressgateway:
        type: NodePort
        externalIPs: ["10.110.22.99"]
EOF 
```

**Version**
- istioctl version --remote
```
client version: 1.6.8
control plane version: 1.6.8
data plane version: 1.6.8 (1 proxies)
```
- kubectl version
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"archive", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"$Format:%H$", GitTreeState:"archive", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**
Use istio operator
**Environment where bug was observed (cloud vendor, OS, etc)**
OS
```
✗ uname -a
Linux lcm-server 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by cwocwo** [comment]
@mustafakirimli thanks for your reply.  I think the `overlays` way is a litte bit complex.  Why helm values doesnt work, is this a bug?

I think helm values is simple than the other two ways, the configurations and properties have been already documented in helm template and values file.

**Comment by chitashvili** [comment]
I have tried multiple patterns and finally got it working with this minimal override:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-controlplane
spec:
  profile: default
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          service:
            type: ClusterIP
            externalIPs:
              - 192.168.1.100
              - 192.168.1.101
```
I find out that I was not setting up following 2 parameters under ingressGateways resource:
```
      - name: istio-ingressgateway
        enabled: true
```
So looks like enabled and name was required but in docs it is saying that it is optional fields.
https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#GatewaySpec
