### ISSUE TITLE
IstioOperator does not support proxyConfig.envoyAccessLogService

### ISSUE THREAD

**Issue by samirspatel** [istio/istio#26745]
**Bug description**
When I try to set `proxyConfig` option using `IstioOperator` CRD I get the following error 

Error: failed to generate Istio configs from file [operator.yaml], error: unknown field "proxyConfig" in v1alpha1.IstioOperatorSpec:

[x] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Expected behavior**
IstioOperator CRD should support `proxyConfig.envoyAccessLogService` as outlined in the [docs](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#RemoteService)

**Steps to reproduce the bug**
Save the following CRD as a file `operator.yaml`
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
  meshConfig:
    accessLogFile: "/dev/stdout"
    accessLogEncoding: "JSON"
    enableEnvoyAccessLogService: true
  proxyConfig:
    envoyAccessLogService: 
      address: "istio-access-log-service:5000"
```

Apply the following command `istioctl upgrade -f operator.yaml`

**Version**

istioctl version --remote
```
client version: 1.6.8
control plane version: 1.6.8
data plane version: none
```

kubectl version
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:17:59Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-gke.9", GitCommit:"0bfb4b7e4478e9ccb67f3c55ce3a5eb20d3bb586", GitTreeState:"clean", BuildDate:"2020-06-26T16:49:38Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
```
istioctl manifest apply \
        --set values.grafana.enabled=true \
        --set values.pilot.enableProtocolSniffingForInbound=true \
        --set values.gateways.istio-ingressgateway.sds.enabled=true \
        --set values.mixer.adapters.prometheus.metricsExpiryDuration=720h \
        --set gateways.components.ingressGateway.k8s.hpaSpec.minReplicas=5 \
        --set gateways.components.ingressGateway.k8s.hpaSpec.maxReplicas=10 \
        --set gateways.components.ingressGateway.enabled=true
```

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE `1.15.12-gke.9`
