### ISSUE TITLE
Istio Operator overlays need documentation case

### ISSUE THREAD

**Issue by tanjunchen** [istio/istio#26759]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

```
overlays:
  - apiVersion: apps/v1
    kind: Deployment
    name: prometheus
    patches:
      - path: spec.template.spec
        value:
          hostNetwork: true
      - path: spec.template.spec
        value:
          dnsPolicy: "ClusterFirstWithHostNet"
```

Is there any document examples that use this iop overlays? The above parameters seem to override the spec.template.spec .After ** istioctl manifest generate -f test.yaml**, The Deployment of prometheus is:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
    release: istio
  name: prometheus
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: prometheus
        release: istio
    spec:
      dnsPolicy: ClusterFirstWithHostNet
```

It seems that the following yaml is ok.

```
overlays:
  - apiVersion: apps/v1
    kind: Deployment
    name: istio-ingressgateway
    patches:
    - path: spec.template.spec.hostNetwork
      value: true
    - path: spec.template.spec.dnsPolicy
      value: "ClusterFirstWithHostNet"
```

**Affected product area (please put an X in all that apply)**

[x] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

There are more documentation on the use of overlays。

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
client version: 1.6.0
control plane version: 1.6.0
data plane version: 1.6.0 (2 proxies)
```

**How was Istio installed?**

Istio Operator

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
