### ISSUE TITLE
SSL_ERROR_CERTIFICATE_UNKNOWN_ALERT

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#26790]
**Bug description**
```
[root@master01 certs]# curl -v -HHost:bookinfo.example.com --resolve "bookinfo.example.com:39329:192.168.198.154"  --cacert example.com.crt --cert ./client.example.com.crt --key client.example.com.key  "https://bookinfo.example.com:39329/productpage" 
* Added bookinfo.example.com:39329:192.168.198.154 to DNS cache
* About to connect() to bookinfo.example.com port 39329 (#0)
*   Trying 192.168.198.154...
* Connected to bookinfo.example.com (192.168.198.154) port 39329 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: example.com.crt
  CApath: none
* NSS: client certificate from file
*       subject: O=client organization,CN=client.example.com
*       start date: Aug 25 05:24:11 2020 GMT
*       expire date: Aug 25 05:24:11 2021 GMT
*       common name: client.example.com
*       issuer: CN=example.com,O=example Inc.
* NSS error -12224 (SSL_ERROR_CERTIFICATE_UNKNOWN_ALERT)
* SSL peer had some unspecified issue with the certificate it received.
* Closing connection 0
curl: (35) SSL peer had some unspecified issue with the certificate it received.
```

```
[root@master01 certs]# cat ../gateway-subjectAltNames.yaml 
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
 name: bookinfo-gateway
spec:
 selector:
   istio: ingressgateway 
 servers:
 - port:
     number: 443
     name: https
     protocol: HTTPS
   tls:
     mode: MUTUAL
     credentialName: bookinfo-credential 
     subjectAltNames:
     - client.example.com
     - bookinfo.example.com
     - example.com
   hosts:
   - bookinfo.example.com
```
client cn is:client.example.com
server cn is: bookinfo.example.com

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
[root@master01 certs]# istioctl version
client version: 1.7.0-beta.1
control plane version: 1.7.0-beta.1
data plane version: 1.7.0-beta.1 (18 proxies)

[root@master01 certs]# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2020-05-12T09:28:18Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"linux/amd64"}
**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
