### ISSUE TITLE
Cannot update overprovisioning factor via envoy filter 

### ISSUE THREAD

**Issue by yan-dblinf** [istio/istio#26793]
**Bug description**

New overprovisioning factor was added into the cluster via envoy filter, but it's ignored by envoy.  

```
[
    {
        "name": "outbound|9080||reviews.test.svc.cluster.local",
        "type": "EDS",
        "edsClusterConfig": {
            "edsConfig": {
                "ads": {}
            },
            "serviceName": "outbound|9080||reviews.test.svc.cluster.local"
        },
        "connectTimeout": "1s",
        "loadAssignment": {
            "clusterName": "outbound|9080||reviews.test.svc.cluster.local",
            "policy": {
                "overprovisioningFactor": 120
            }
        },
        "circuitBreakers": {
            "thresholds": [
                {
                    "maxConnections": 4294967295,
                    "maxPendingRequests": 4294967295,
                    "maxRequests": 4294967295,
                    "maxRetries": 4294967295
                }
            ]
        },
        "outlierDetection": {
            "consecutive5xx": 1,
            "interval": "1s",
            "baseEjectionTime": "3600s",
            "maxEjectionPercent": 100,
            "enforcingConsecutive5xx": 100
        },
        "commonLbConfig": {
            "healthyPanicThreshold": {},
            "localityWeightedLbConfig": {}
        },
        "metadata": {
            "filterMetadata": {
                "istio": {
                    "config": "/apis/networking.istio.io/v1alpha3/namespaces/test/destination-rule/reviews"
                }
            }
        },
        "filters": [
            {
                "name": "envoy.filters.network.upstream.metadata_exchange",
                "typedConfig": {
                    "@type": "type.googleapis.com/udpa.type.v1.TypedStruct",
                    "typeUrl": "type.googleapis.com/envoy.tcp.metadataexchange.config.MetadataExchange",
                    "value": {
                        "protocol": "istio-peer-exchange"
                    }
                }
            }
        ]
    }
]
```

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Traffic split occurs when the number of healthy endpoints in p0 drops below 83%. 

**Steps to reproduce the bug**
1. Deploy bookinfo service into test namespace
2. Deploy below envoy filter 
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: overprovisioning-factor
  namespace: test
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      context: SIDECAR_OUTBOUND
      cluster:
        name: outbound|9080||reviews.test.svc.cluster.local
    patch:
      operation: MERGE
      value:
        load_assignment:
          cluster_name: outbound|9080||reviews.test.svc.cluster.local
          policy:
            overprovisioning_factor: 120
  workloadSelector:
    labels:
      app: productpage
```
3. Update deployment productpage and reviews-v2 to run on the same node, and reviews-v1 to run on another node. 
4. Scale up deployment reviews-v2 to 10 pods 
5. Enable locality load balancing and outlier detection for reviews 
6. Make two reviews-v2 pods fail outlier detection 
7. Curl productpage and check the version of triggered reviews service by ``` for i in {1..1000}; do n=`curl http://127.0.0.1:8001/api/v1/namespaces/test/services/productpage:9080/proxy/productpage -s | grep -w black | wc -l`; if [[ "$n" -eq 0 ]]; then echo $n; fi; done```. It should output a few 0s.  

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.5.2

**How was Istio installed?**
istioctl manifest apply

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS, Kops, Kubernetes
