### ISSUE TITLE
1.7.0 istioctl installing istio-ingressgateway when enabled=false

### ISSUE THREAD

**Issue by harpratap** [istio/istio#26796]
**Bug description**
Trying to install istio 1.7.0 without istio-ingressgateway but it doesn't seem to respect `enabled: false` anymore (it worked fine in 1.6.x)
Here's my IOP -
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    base:
      enabled: true
    egressGateways:
    - enabled: false
      name: bug
    ingressGateways:
    - enabled: false
      name: bug
```
(Also for some reason I need to mention name too as described in https://github.com/istio/istio/issues/26683 )

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

No istio-ingressgateway related resources like it's deployment/service etc.

**Steps to reproduce the bug**
`istioctl manifest generate -f test.yaml` or
`istioctl install -f test.yaml`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istioctl 1.7.0

**How was Istio installed?**
Using istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
OSX istioctl binary

**Comment by ostromart** [comment]
Hi @harpratap, I just ran `istioctl manifest generate` with the following input: 

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: false

```
No gateway YAML was produced (i.e. the false turned off the ingress in the default profile). Could you try this yaml with your setup to see what happens?
