### ISSUE TITLE
Unable to Send Traffic to TCP TLS GW/VS via INGRESS (similar to #8374)

### ISSUE THREAD

**Issue by lmcdasm** [istio/istio#26795]
**Bug description**
when using TCP TLS VS and GW defintions, we see that traffic is not routed properly to the registered GWs/VS.  
This seems similar to issue #8374 - which we can see others have had more problems with since the issue was considered closed/stale... its not clear how/if this was fixed (if it was merely that we have to follow a specific "order" for installation to workaround - which we have followed in that thread but to no avail.

[ ] Docs
[ ] Installation
[X ] Networking
[ X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[X ] Developer Infrastructure

**Expected behavior**
we would expect that the TCP traffic is sent via the GW to the VS that are registered for the hosts defined.

**Steps to reproduce the bug**
here are the VS and GW configurations and LB service setup

[daniel.smith@ip-0F04 istio-tcp-gws]$ cat test-tcp-gateway.yaml
GW DEF:

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
name: test-tcp-gateway
spec:
selector:
istio: internal-istio-ingressgateway
servers:

port:
number: 31400
name: tcp-oc
protocol: TCP
hosts:
"*.ourdomain.com"
"*.region.oudomain.com"
tls:
      mode: SIMPLE
      credentialName: wildcard-outdomain-com-chain_

VS DEF:
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
name: echo-vs
namespace: echo-vs-ns
spec:
gateways:

istio-system/test-tcp-gateway
hosts:
*.ourdomain.com
*.region.ourdomain.com
tcp:
match:
port: 31400
route:
destination:
host: echo-service
port:
number: 1883
OUR ISTIO LB SERVICE
apiVersion: v1
kind: Service
metadata:
annotations:
service.beta.kubernetes.io/azure-load-balancer-internal: "true"
finalizers:

service.kubernetes.io/load-balancer-cleanup
labels:
app: internal-istio-ingressgateway
fluxcd.io/sync-gc-mark: sha256.8kPkyU3PO1km-dWxWAumByNTH_OlX7Hix5LyjWLWwvs
istio: internal-ingressgateway
release: istio
name: internal-istio-ingressgateway
namespace: istio-system
spec:
clusterIP: x.y.z.a
externalTrafficPolicy: Cluster
ports:
name: status-port
nodePort: 30902
port: 15020
protocol: TCP
targetPort: 15020
name: http2
nodePort: 32637
port: 80
protocol: TCP
targetPort: 80
name: https
nodePort: 32347
port: 443
protocol: TCP
targetPort: 443
name: tcp-oc
nodePort: 32415
port: 31400
protocol: TCP
targetPort: 31400
selector:
app: internal-istio-ingressgateway
istio: internal-ingressgateway
sessionAffinity: None
type: LoadBalancer
status:
loadBalancer:
ingress:
ip: 10.192.1.183

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

[daniel.smith@ip-0AB36F04 istio-tcp-gws]$ istioctl version --remote
1.7.0
data plane version: 1.5.8 (143 proxies), 1.5.1 (93 proxies)
[daniel.smith@ip-0AB36F04 istio-tcp-gws]$

daniel.smith@ip-0AB36F04 istio-tcp-gws]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a2cfecc33f6911261fb8a670d2df2714094002a6", GitTreeState:"clean", BuildDate:"2020-05-29T21:50:25Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
[daniel.smith@ip-0AB36F04 istio-tcp-gws]$

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
AKS

**Comment by hzxuzhonghu** [comment]
@lmcdasm Can you share the 31400 listener? And if not generated, can you share the istiod logs?

**Comment by howardjohn** [comment]
The config you provided is not valid. It failed the webhook check. Modifying it a bit to:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: test-tcp-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: tcp-oc
      protocol: TCP
    hosts:
    - "*.foo.ourdomain.com"
    - "*.region.oudomain.com"
    # tls:
    #   mode: SIMPLE
    #   credentialName: sds-credential
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: echo-vs
spec:
  gateways:
  - istio-system/test-tcp-gateway
  hosts:
  - "*.foo.ourdomain.com"
  - "*.region.ourdomain.com"
  tcp:
  - match:
    - port: 443
    route:
    - destination:
        host: echo-service
        port:
          number: 1883
```

and it works. Do you have validation on the config? Maybe you have disabled it and the invalid config is getting passed
