### ISSUE TITLE
Istio Operator cannot install Istio on a custom namespace 

### ISSUE THREAD

**Issue by BaudouinH** [istio/istio#26801]
**Bug description**

Istio Operator cannot install Istio on a custom namespace : 

I installed Istio Operator in a custom namespace (not "istio-system") and then using an istiooperators.install.istio.io objet, used the operator to install Istio's control plane, in the same custom namespace.

The install did not work, as Istio Operator tries to create 2 objects (istiod-service-account and istio-reader-service-account) in "istio-system" despite asking the Operator to install Istio in a custom namespace.
The Operator will then create other objects (in the custom namespace), and will not suceed in creating the Deployment of istiod in the custom namespace.
It will be stuck on `- Processing resources for Istiod. Waiting for Deployment/<custom-namespace>/istiod`

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

The Operator creating every object necessary for Istio's Control Plane in the custom namespace.

**Steps to reproduce the bug**

Install Istio Operator with `istioctl operator init --operatorNamespace istio-system-test --istioNamespace istio-system-test
`
Apply the following manifest with kubectl : 
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system-test
  name: "istio-staging"
spec:
  profile: "default"
  namespace: istio-system-test
```
The Operator will then try to create the control plane but will be stuck at `- Processing resources for Istiod. Waiting for Deployment/istio-system-test/istiod`, according to the logs of the pod : 

```
k logs -n istio-system-test istio-operator-7d8d7487b8-mhvq8 | grep error
2020-08-25T12:09:55.503258Z	error	installer	failed to create "ServiceAccount/istio-system/istio-reader-service-account": namespaces "istio-system" not found
2020-08-25T12:09:55.568056Z	error	installer	failed to create "ServiceAccount/istio-system/istiod-service-account": namespaces "istio-system" not found
✘ Istio core encountered an error: failed to create "ServiceAccount/istio-system/istio-reader-service-account": namespaces "istio-system" not found
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

Istio : 1.6.6 (no running Istio pods in "istio-system-test")
kubectl : 
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.9", GitCommit:"500f5aba80d71253cc01ac6a8622b8377f4a7ef9", GitTreeState:"clean", BuildDate:"2019-11-13T11:21:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Helm was not used, but I first encountered this issue with an Operator installed through Helm on an EKS 1.15 cluster.

**How was Istio installed?**

Istio was installed with the help of the Operator, in a custom namespace (see previously for all the installation details)

**Environment where bug was observed (cloud vendor, OS, etc)**

This was done on minikube v1.12.1 (Ubuntu 20.04), but I also encountered this issue on a kubernetes cluster with EKS 1.15.

**Comment by morvencao** [comment]
Try with the following IOP instance:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system-test
  name: "istio-staging"
spec:
  profile: "default"
  namespace: istio-system-test
  values:
    global:
      istioNamespace: istio-system-test
```
