### ISSUE TITLE
Session affinity doesn't work with TLS virtual service

### ISSUE THREAD

**Issue by guillomep** [istio/istio#26817]
Hello,

**Bug description**

I'm trying to run a service that use HTTPs to communicate. This application needs to have session affinity in order to work correctly.
With an ingress I was able to do so using the following annotations:
```
nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
nginx.ingress.kubernetes.io/affinity: "cookie"
nginx.ingress.kubernetes.io/session-cookie-name: "route"
nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
```

With istio I have created a VirtualService and a DestinationRule but it seems to not work (the cookie is not created)

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app-vs
spec:
  gateways:
  - app-gateway
  hosts:
  - app.example.com
  tls:
  - match:
    - sniHosts:
      - app.example.com
      uri:
        prefix: /
    route:
    - destination:
        host: app-internal
        port:
          number: 9443
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: app-session-affinity
spec:
  host: app-internal
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: route
          ttl: 0s
```

Also the application is a statefulset so I have a stateless service named `app` (`app-internal` is a service with a clusterIP) and ServiceEntry (one for each replica) to add it to istio

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: app-0
spec:
  exportTo:
  - .
  hosts:
  - app-0.app.ns.svc.cluster.local
  location: MESH_INTERNAL
  ports:
  - name: https-servlet
    number: 9443
    protocol: TCP
  resolution: DNS
```

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

The cookie should be added and the session affinity should work correctly.

**Steps to reproduce the bug**

Create a TLS VirtualService and a DestinationRule to add the cookie.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
Istio:
client version: 1.3.6
citadel version: 1.3.6
citadel version: 1.3.6
egressgateway version: 1.3.6
egressgateway version: 1.3.6
galley version: 1.3.6
galley version: 1.3.6
ingressgateway version: 1.3.6
ingressgateway version: 1.3.6
pilot version: 1.3.6
pilot version: 1.3.6
policy version: 1.3.6
policy version: 1.3.6
sidecar-injector version: 1.3.6
sidecar-injector version: 1.3.6
telemetry version: 1.3.6
telemetry version: 1.3.6

Kube:
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.12", GitCommit:"17c50ce2d686f4346924935063e3a431360e0db7", GitTreeState:"clean", BuildDate:"2020-06-26T03:33:27Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

Helm:
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

**How was Istio installed?**

With helm chart

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS
