### ISSUE TITLE
authorizationPolicy operation works unexpected

### ISSUE THREAD

**Issue by linxuyalun** [istio/istio#26847]
**Bug description**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

I am testing the authorization policy in istio 1.6.7.

the service I used is a httpbin example:

```yaml

##################################################################################################
# httpbin service
##################################################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      serviceAccountName: httpbin
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80
```

I also use virtualservice to redirect the route

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jwt-test-vs
spec:
  hosts:
  - "ec2-25-38-68-56.cn-northwest-1.compute.amazonaws.com.cn"
  gateways:
  - cc-gateway
  http:
  - match:
    - uri:
        prefix: /jwt/v1
    rewrite:
      uri: /
    route:
    - destination:
        host: httpbin
        port:
          number: 8000
    corsPolicy:
      allowOrigin:
      - "*"
      allowMethods:
      - POST
      - GET
      - PUT
      - DELETE
      allowCredentials: true
      allowHeaders:
      - "jwt"
      - "content-type"
      - "authorization"
```

And here is my RequestAuthentication and AuthorizationPlicy
```yaml
apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: "jwt-example"
spec:
  selector:
    matchLabels:
      app: httpbin
  jwtRules:
  - issuer: "testing@secure.istio.io"
    jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.5/security/tools/jwt/samples/jwks.json"
```
```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: require-jwt
spec:
  selector:
    matchLabels:
      app: httpbin
  action: ALLOW
  rules:
  - from:
    - source:
       requestPrincipals: ["testing@secure.istio.io/testing@secure.istio.io"]
    to:
    - operation:
        methods: ["GET"]
```

When I type 

```bash
curl  -I -H  "Host: ec2-25-38-68-56.cn-northwest-1.compute.amazonaws.com.cn" -H  "Authorization: Bearer $TOKEN" http://ec2-25-38-68-56.cn-northwest-1.compute.amazonaws.com.cn:30000/jwt/v1/status/200
```

I can get a 200 as expected, however when I add a `paths` field:
```diff
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: require-jwt
spec:
  selector:
    matchLabels:
      app: httpbin
  action: ALLOW
  rules:
  - from:
    - source:
       requestPrincipals: ["testing@secure.istio.io/testing@secure.istio.io"]
    to:
    - operation:
        methods: ["GET"]
+      paths: ["/status/200"]
```

I think I should get a 200 like before, but I always get a 403.

I have also replaced the path `/status/200` to `/jwt/v1/status/200`, but in vain.

**Steps to reproduce the bug**

See above

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
 istioctl version --remote
client version: 1.6.7
control plane version: 1.6.7
data plane version: 1.6.7 (22 proxies)
**How was Istio installed?**

kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

**Environment where bug was observed (cloud vendor, OS, etc)**

aws, ubuntu18.04
