### ISSUE TITLE
Istio responding 502 with AWS NLB integration, works fine for classic ELB

### ISSUE THREAD

**Issue by juandiegopalomino** [istio/istio#26872]
**Bug description**
We are running istio on version 1.7.0 with the demo profile on an EKS 1.17 cluster and permissive mTLS. Our ingress service used a nlb on a private subnet with an ACM ssl certificate for port 443. There is no cidr whitelisting on istio or on the load balancer. The istio override looks as follows:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    gateways:
      istio-ingressgateway:
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-internal: "true"
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: 'https'
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
          # Stuff added by post deployment hook
          external-dns.alpha.kubernetes.io/hostname: "*.istio.OUR.DOMAIN"
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:REDACTED:certificate/REDACTED
```

We have an httpbin example service (complete with virtual service and destination rules) which we hooked up to to the ingress gateway.  When we try to hit the host via curl or the chrome browser, sometimes we get the expected httpbin working fine for all paths.
Sometimes, however, we get a 52 empty response from the server error, which usually sticks around for a while before going away. If we get this error then the request always takes over 5 seconds, otherwise (the good requests) always takes a fraction of a second to complete. This error seems to be happening randomly and tested from multiple computers.

Looking at the kiali dashboard, there is no reported timeout errors-- it only seems to know about the good, fulfilled, requests.
When I look at the logs of the ingress gateway pod, I see a log line for each non-52 request, but I never see a log for the 52 empty response requests.

<img width="845" alt="Screen Shot 2020-08-27 at 10 45 15 AM" src="https://user-images.githubusercontent.com/10430635/91493797-afb1d280-e86c-11ea-801b-21353f1d6d88.png">

We have a while loop running in a terminal that sends 2 requests before sleeping for 1 second. So when the 52 no response doesn't happen I'm sending 2 request every ~1.5 seconds and when the error does occur I am sending 2 requests every ~11 seconds (becuase the curls are not parallelized and the error responses take about 5 seconds). This is how we guarantee traffic for visibility in kiali.

If we do a direct kubectl port-forward of the service to localhost we never get the error
We tried deleting and restarting the ingress gateway pod, and the errors are still around.
We tried deleting and recreating the nlb, and the errors are still around.
We tried removing mTLS, and the errors are still around.
We tried hitting the load balancer directly instead of the route53 record (passing the appropriate host headers), and the errors are still around.
The only log showing a possible error is the following from the curls when we get an empty response:
* TLSv1.2 (IN), TLS alert, close notify (256):
* Empty reply from server
* Connection #0 to host REDACTED left intact
curl: (52) Empty reply from server
* Closing connection 0

We were able to fix the issue by omitting the annotation provisioning an NLB and instead using the default classic ELB. This led me to believe that the error is with the NLB integration.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Do not get 52 no responses from server when hitting a dummy service hooked up to the gateway.

**Steps to reproduce the bug**
run curl or go to the domain linked to the gateway once installing istio with the settings I described. Do it in a for loop and you'll get the errors soon enough. As far as we can tell, the errors are non-deterministic.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
client version: 1.7.0
control plane version: 1.7.0
data plane version: 1.7.0 (9 proxies)
```

**How was Istio installed?**
`istioctl install --set profile=demo --filename path/to/istio_overrides.yaml` I put the override on top

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS 1.17.0
