### ISSUE TITLE
Istio multicluster 404 not found when using wildcards

### ISSUE THREAD

**Issue by ECuRyDIN** [istio/istio#26905]
I have setup multicluster replicated control plane following doc in v1.5. I am getting 404 not found when I exec:

kubectl exec --context=$CTX_CLUSTER1 $SLEEP_POD -n foo -c sleep -- curl -I -v httpbin-bar.resource.net:17443/headers

**Bug description**
Getting 404 not found for istio mutlicluster replicated control plane configuration

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
should return 200 OK response

**Steps to reproduce the bug**
Follow the official doc to setup multicluster for v1.5. 
doc: https://istio.io/v1.5/docs/setup/install/multicluster/gateways/

Setup the following in cluster 1:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin-se
spec:
  hosts:
  - "httpbin-bar"
  location: MESH_INTERNAL
  ports:
  - name: http1
    number: 17443
    protocol: http
  resolution: NONE
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: istio-mutual
spec:
  host: "*"
  ports:
  - number: 17443
    name: tls-istio-mutual
    protocol: TLS
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

```
and the following in cluster 2
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  selector:
    istio: ingressgateway # use Istio's default ingress gateway
  servers:
  - port:
      name: https-istio
      number: 17443
      protocol: HTTPS
    tls:
      mode: ISTIO_MUTUAL
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-vs
spec:
  hosts:
  - "*" # This can be specific URLs
  gateways:
  - sample-gateway
  http:
  - route:
    - destination:
        host: httpbin
        port:
          number: 8000

```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istioctl version
client version: 1.5.6
control plane version: d5fa6e530e12790609b00c898b7867f57713dff3-dirty
data plane version: 1.5-dev (7 proxies)

Kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.10", GitCommit:"89d8075525967c7a619641fabcb267358d28bf08", GitTreeState:"clean", BuildDate:"2020-06-23T02:52:37Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
Istioctl
**Environment where bug was observed (cloud vendor, OS, etc)**
Aks, Linux (ubuntu)
