### ISSUE TITLE
EnvoyFilter is not applied to gateways, only to sidecars.

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#26912]
**Bug description**
I am unable to apply EnvoyFilter to an egress gateway. I use Context `ANY` and see the filter is added to the sidecars and not to my egress gateway.

[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

The EnvoyFilter must be added to both sidecars and gateways when the context is `ANY`.

**Steps to reproduce the bug**
Follow the instructions in https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/#egress-gateway-for-https-traffic, and at the end add the following filter:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: egress-gateway-sni-verifier
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: ANY
      listener:
        portNumber: 443
        filterChain:
          filter:
            name: istio.stats
    patch:
      operation: INSERT_BEFORE
      value:
         name: sni_verifier
         config: {}
```

Check that the filter has been added to a sidecar and not the to the egress gateway.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
istioctl version --remote
client version: 1.7.0
control plane version: 1.7.0
data plane version: 1.7.0 (3 proxies)
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.11+IKS", GitCommit:"8f73c4ab44865a242f2f2ee450d5e0043f7bc341", GitTreeState:"clean", BuildDate:"2020-08-13T19:41:30Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

According to this example https://istio.io/latest/docs/setup/install/operator/#install.

**Environment where bug was observed (cloud vendor, OS, etc)**
