### ISSUE TITLE
Istioctl x describe fails to list pod virtual services for weighted clusters 

### ISSUE THREAD

**Issue by rinormaloku** [istio/istio#26910]
**Bug description and how to reproduce**
`istioctl x describe <pod>` doesn't list virtual services if those use weighted clusters.

Sample VS:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-v1-v2
spec:
#...
  http:
  - route:
    - destination:
        host: httpbin.default.svc.cluster.local
        subset: version-v1
        port:
          number: 80
      weight: 20
    - destination:
        host: httpbin.default.svc.cluster.local
        subset: version-v2
        port:
          number: 80
      weight: 80
```

**Expected output** when using `istioctl x describe pod`:
```
Pod: httpbin-v2-6dd9c95865-f9vnw
   Pod Ports: 8080 (httpbin), 15090 (istio-proxy)
--------------------
Service: httpbin
   Port: http 80/HTTP targets pod port 8080
## Abbreviated

Exposed on Ingress Gateway http://
VirtualService: httpbin-v1-v2
   Weight 80%
```

**Actual output:**
```
Pod: httpbin-v2-6dd9c95865-f9vnw
   Pod Ports: 8080 (httpbin), 15090 (istio-proxy)
--------------------
Service: httpbin
   Port: http 80/HTTP targets pod port 8080
DestinationRule: dr-httpbin for "httpbin.default.svc.cluster.local"
   Matching subsets: version-v2
      (Non-matching subsets version-v1)
   No Traffic Policy
```

**Virtual service section is missing**

[x] User Experience

[x] Istioctl
