### ISSUE TITLE
istio-init container has huge resources limits

### ISSUE THREAD

**Issue by MarianZoll** [istio/istio#26932]
**Bug description**

After upgrading to Istio 1.7 (we also switched to operator managed mode), the `istio-init` container resources limits are 2 CPUs and 1Gi memory. This is very resource-intensive for deployments that are expected to have very less traffic inside the mesh. 

As result, the node-based resource allocations would cause operations alerts in production.  

We already limit the resources of the `istio-proxy` by providing the following annotations:
```
sidecar.istio.io/proxyCPU: 75m
sidecar.istio.io/proxyCPULimit: 75m
sidecar.istio.io/proxyMemory: 75Mi
sidecar.istio.io/proxyMemoryLimit: 75Mi
sidecar.istio.io/rewriteAppHTTPProbers: "true"
```

We are looking for a similar way to restrict the limits of the `istio-init` container. From reading the docs of previous Istio releases, the limit annotations are quite new to `istio-init` as it was around (50m, 100Mi in 1.4). Additionally, you were able to configure them using:
```
global.proxy.init.resources.limits.cpu	100m	
global.proxy.init.resources.limits.memory	50Mi	
global.proxy.init.resources.requests.cpu	10m	
global.proxy.init.resources.requests.memory	10Mi	
```

Maybe I am just looking at the wrong place, but I at least hope that the issue if it is just a link to a documentation might help someone else as well. So sorry in case it is a no brainer 👍 

[ ] Docs
[ X ] Installation
[ ] Networking
[ X ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

`istio-init` container should not have huge resources limits defined.

**Steps to reproduce the bug**

1. Deploy Istio 1.7 with the provided IstioOperator
2. Deploy a deployment in a istio-injected namespace
3. Run `kubectl get po -n $NAMESPACE $POD -o yaml` and check the resources k8s limits

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ ./istioctl version --remote 
client version: 1.7.0
control plane version: 1.7.0
data plane version: 1.7.0 (17 proxies), 1.6.5 (5 proxies)
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"e3808385c7b3a3b86db714d67bdd266dc2b6ab62", GitTreeState:"clean", BuildDate:"2020-07-15T20:50:36Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

Operator mode with the following configurations for Dev only:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  meshConfig:
    accessLogFile: "/dev/stdout"
    accessLogEncoding: JSON
    enablePrometheusMerge: true
    outboundTrafficPolicy:
      mode: ALLOW_ANY
  components:
    base:
      enabled: true
      k8s:
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
    telemetry:
      enabled: true
      k8s:
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "500Mi"
            cpu: "500m"
    pilot:
      enabled: true
      k8s:
        resources:
          requests:
            memory: "300Mi"
            cpu: "300m"
          limits:
            memory: "500Mi"
            cpu: "500m"
    policy:
      enabled: true
      k8s:
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
    cni:
      enabled: false
    egressGateways:
      - name: istio-egressgateway
        enabled: false
        k8s:
          resources:
            requests:
              memory: "200Mi"
              cpu: "200m"
            limits:
              memory: "500Mi"
              cpu: "500m"
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          resources:
            requests:
              memory: "200Mi"
              cpu: "200m"
            limits:
              memory: "500Mi"
              cpu: "500m"
  addonComponents:
    prometheus:
      enabled: true
    kiali:
      enabled: true
    grafana:
      enabled: false
    tracing:
      enabled: true
```

**Environment where bug was observed (cloud vendor, OS, etc)**

AKS
