### ISSUE TITLE
Infinite request loop with istio-proxy behind Envoy

### ISSUE THREAD

**Issue by blankenshipz** [istio/istio#26946]
I think I've found an infinite request loop that's causing my `istio-proxy` to crash with an OOM error in a specific circumstance.

Here's the flow diagram:

I have just **one app in the service mesh** and the traffic coming to that app comes from an envoy proxy that's handling SSL termination

**Envoy** <-> **(istio-proxy / api-app )** -> other services 

* When I send the request directly to localhost from within **api-app** it works fine
* When I port forward directly to the **(istio-proxy / app)** pod and issue the request it also appears to work fine.
* When I send the request through Envoy I start to see thousands of identical requests in the **(istio-proxy / api-app)** logs and eventually the `istio-proxy` crashes with OOM.

When I submit the request locally to the app directly from inside the application container (the working condition) in the `istio-proxy` logs I see that the upstream_cluster is `PassthroughCluster`

However when I submit the request through the Envoy proxy I'm using for SSL termination (note: not the `istio-proxy` for the app/mesh) the request seems to be retried/repeated until the `istio-proxy` crashes with an OOM; the only `upstream_cluster` I see in those logs is `inbound|80|myapp`

It seems like the request is being routed to the wrong listener or the envoy-proxy we have sitting in front of the app that's in the mesh is somehow messing up the request.

--- 

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

I would expect that the application (api-app) wouldn't receive this request multiple times 

**Steps to reproduce the bug**

N/A

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

`istioctl version --remote`
client version: 1.6.5
control plane version: 1.6.8
data plane version: 1.6.8 (31 proxies)

`kubectl version`
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:06:54Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-gke.9", GitCommit:"0bfb4b7e4478e9ccb67f3c55ce3a5eb20d3bb586", GitTreeState:"clean", BuildDate:"2020-06-26T16:49:38Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

istio operator

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    tracing:
      enabled: false
    prometheus:
      enabled: false
    global:
      jwtPolicy: third-party-jwt
      logAsJson: true
      proxy:
        tracer: datadog
        accessLogEncoding: "JSON"
    meshConfig:
      accessLogFile: "/dev/stdout"
    pilot:
      traceSampling: 100.0
```

**Environment where bug was observed (cloud vendor, OS, etc)**

GCP/GKE

--- 
**Logs**

I'm attaching logs for both the good and bad requests flows; note that the logs are limited to the first 10k lines of output for the "bad" series

Good Request
 * Istio proxy logs
 * Application logs

[api-good-request-istio-proxy.log](https://github.com/istio/istio/files/5152316/api-good-request-istio-proxy.log)
[api-good-request-api.log](https://github.com/istio/istio/files/5152318/api-good-request-api.log)

Bad Request
 * Istio proxy logs
 * Application logs
  * Envoy logs

[api-bad-request-istio-proxy.log](https://github.com/istio/istio/files/5152317/api-bad-request-istio-proxy.log)
[api-bad-request-api-app.log](https://github.com/istio/istio/files/5152319/api-bad-request-api-app.log)
[api-bad-request-envoy-https.log](https://github.com/istio/istio/files/5152320/api-bad-request-envoy-https.log)

**Config Dump**
[config_dump.json.zip](https://github.com/istio/istio/files/5152327/config_dump.json.zip)

**Comment by howardjohn** [comment]
@lambdai

**Comment by howardjohn** [comment]
> When I send the request directly to localhost from within api-app it works fine
> When I port forward directly to the (istio-proxy / app) pod and issue the request it also appears to work fine.
> When I send the request through Envoy I start to see thousands of identical requests in the (istio-proxy / api-app) logs and eventually the istio-proxy crashes with OOM.

Both 1 and 2 will bypass iptables I believe, so I think we cannot conclusively say its ONLY envoy -> api-app, or if curl -> api-app would also loop, unless I misread this.

From the logs, it looks like in this loop, your app is getting requests as well (based on trace id). So the flow is envoy -> sidecar inbound -> app -> sidecar outbound -> sidecar inbound -> app -> ...

I think the fact that your app is involved in the loop suggests your app may actually just be calling itself. I do not see how its possible otherwise, although very well could be missing something, but it seems like if your app was not calling itself it would stop the loop.

Whats very interesting though is it doesn't happen if you bypass the sidecar. This is exactly the same as https://github.com/istio/istio/issues/28058. 

So we have two equally odd possibilities:
* Your app calls itself, but only when the request comes from sidecar (based on different header, perhaps?)
* Istio sidecar somehow is somehow sending requests to itself AND the app?

**Comment by blankenshipz** [comment]
@howardjohn A bit of detail that might be interesting; the app itself acts like a reverse proxy and does forward requests but I don't believe it would be possible for it to intentionally forward a request to itself there's a list of URLs that are picked from based on the path of the request. 

* Definitely agree that the app is seeing the requests as well - in fact it was causing an OOM issue. 
* I don't remember if I saw that the requests were going to `sidecar outbound` and then back again but that could be right 
* I eventually switched to an istio ingressgateway and the problem went away; it's definitely something about the envoy proxy

**Comment by howardjohn** [comment]
Interesting the linked issue was also a reverse proxy type app. Is it possibly forwarding some headers or something - or even worse, the Host header, which causes it to look back to itself? http requests are routed based on Host header.

One way that I think would prove this is to name the api-app port `tcp`. then it should treat it as tcp and ignore host header and route only based on ip.

That does not corroborate with the fact using Ingress Gateway avoids the problem though..

**Comment by vaibhavjain882** [comment]
@howardjohn I can confirm that after changing the svc port name to TCP my issue is fixed. I am not in an infinite loop, it works as expected. Thanks a lot.

**Comment by blankenshipz** [comment]
>  http requests are routed based on Host header.

@howardjohn My app *was* passing the host header changing this seems to have fixed the issue. I'm confused as to why the `istio-ingressgateway` avoids this problem - is the ingressgateway not passing the host header?

**Comment by howardjohn** [comment]
```
$ curl external.domain.com
ServiceVersion=
ServicePort=8080
Host=external.domain.com
```

From calling my gateway to a pod reflecting headers, looks like it will pass the original Host header from the client, which presumably is not app-api which does not rtigger the loop

**Comment by blankenshipz** [comment]
@howardjohn I think that's issue spot-on! Thanks for your help! 🍺

**Comment by nrjpoddar** [comment]
@howardjohn should we add protection against this OOM scenario? I understand it's based on HTTP host based routing but I'm not sure if we can add any defensive checks here.

**Comment by howardjohn** [comment]
@nrjpoddar I was thinking of this but I am not sure what we would do. From Envoy's perspective the app is just sending major load.

Actually the OOM seems unexpected -- I would not expect envoy to OOM even if it has high load

**Comment by nrjpoddar** [comment]
> @nrjpoddar I was thinking of this but I am not sure what we would do. From Envoy's perspective the app is just sending major load.
> 
> Actually the OOM seems unexpected -- I would not expect envoy to OOM even if it has high load

OOM I'm guessing is not due to high load but probably a bug (or by design) in Envoy where some resource is never getting released but just consuming more and more memory. Getting a memory profile might be interesting to see.

Functionally, Istio and Envoy are doing the correct thing here so I guess defensive check is not the correct thing but fixing the OOM bug seems right.

**Comment by vaibhavjain882** [comment]
@howardjohn I revisited the code and I found one discrepancy with our headers. I dopped the Host header now in the code and everything is working as expected. I changed back the service port name to "HTTP". Thanks for your help.  🍺🍺🍺

**Comment by howardjohn** [comment]
Oh oom actualy makes sense, each request is not completed, its loop, so there is many many many requests in flight at once.

```yaml
# Source: looper/templates/server.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: script
data:
  main.go: |-
    package main

    import (
      "io/ioutil"
      "log"
      "net/http"
    )

    func main() {
      http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
        log.Printf("got request %v -> %v\n", r.Host, r)
        r.RequestURI = ""
        r.URL.Scheme = "http"
        r.URL.Host = r.Host
        resp, err := http.DefaultClient.Do(r)
        if err != nil {
          log.Println(err)
          w.WriteHeader(507)
          return
        }
        defer resp.Body.Close()
        b, _ := ioutil.ReadAll(resp.Body)
        w.Write(b)
      })

      log.Fatal(http.ListenAndServe(":9001", nil))
    }



---
# Source: looper/templates/server.yaml
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
spec:
  ports:
  - port: 9001
    name: http
  selector:
    app: server
---
# Source: looper/templates/server.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: golang:1.12.5
        args:
        - go
        - run
        - /script/main.go
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
        volumeMounts:
        - name: program-volume
          mountPath: /script
      volumes:
        - name: program-volume
          configMap:
            name: script

```

can reproduce easily
