### ISSUE TITLE
Istio Operator is missing the permissions to update Service Monitors

### ISSUE THREAD

**Issue by upodroid** [istio/istio#26961]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

Istio Operator is missing the permissions to update Service Monitors

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
 root  DESKTOP-7JUP8RO  mnt  c  …  Git  ccoe-landing-zone  k8s   master  119✎  1+  #    k version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.11-gke.5", GitCommit:"baccd25d44f1a0d06ad3190eb508784efbb990a5", GitTreeState:"clean", BuildDate:"2020-06-25T22:55:26Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```
istio v1.7
**How was Istio installed?**
via Operator
**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

```
## Istio Config
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: controlplane
spec:
  profile: demo
  addonComponents:
    grafana:
      enabled: false
    prometheus:
      enabled: false
    prometheusOperator:
      enabled: true
    kiali:
      enabled: true
  values:
    prometheusOperator:
      createPrometheusResource: false
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
      - name: cluster-local-gateway
        enabled: true
        label:
          istio: cluster-local-gateway
          app: cluster-local-gateway
        k8s:
          service:
            type: ClusterIP
            ports:
            - port: 15020
              name: status-port
            - port: 80
              name: http
            - port: 443
              name: https
```

```
 root  DESKTOP-7JUP8RO  mnt  c  …  Git  ccoe-landing-zone  k8s   master  119✎  1+  ERROR  #    k describe istiooperator controlplane 
Name:         controlplane
Namespace:    istio-system
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"install.istio.io/v1alpha1","kind":"IstioOperator","metadata":{"annotations":{},"name":"controlplane","namespace":"istio-sys...
API Version:  install.istio.io/v1alpha1
Kind:         IstioOperator
Metadata:
  Creation Timestamp:  2020-08-28T15:54:29Z
  Finalizers:
    istio-finalizer.install.istio.io
  Generation:        5
  Resource Version:  17173538
  Self Link:         /apis/install.istio.io/v1alpha1/namespaces/istio-system/istiooperators/controlplane
  UID:               6234d533-345b-47de-b0ae-40fca32daf00
Spec:
  Addon Components:
    Grafana:
      Enabled:  false
    Kiali:
      Enabled:  true
    Prometheus:
      Enabled:  false
    Prometheus Operator:
      Enabled:  true
  Components:
    Ingress Gateways:
      Enabled:  true
      Name:     istio-ingressgateway
      Enabled:  true
      k8s:
        Service:
          Ports:
            Name:  status-port
            Port:  15020
            Name:  http
            Port:  80
            Name:  https
            Port:  443
          Type:    ClusterIP
      Label:
        App:    cluster-local-gateway
        Istio:  cluster-local-gateway
      Name:     cluster-local-gateway
  Profile:      demo
  Values:
    Prometheus Operator:
      Create Prometheus Resource:  false
Status:
  Component Status:
    Addon Components:
      Error:   servicemonitors.monitoring.coreos.com "envoy-stats-monitor" is forbidden: User "system:serviceaccount:istio-operator:istio-operator" cannot update resource "servicemonitors" in API group "monitoring.coreos.com" in the namespace "istio-system", servicemonitors.monitoring.coreos.com "istio-component-monitor" is forbidden: User "system:serviceaccount:istio-operator:istio-operator" cannot update resource "servicemonitors" in API group "monitoring.coreos.com" in the namespace "istio-system", servicemonitors.monitoring.coreos.com "istio-mesh-monitor" is forbidden: User "system:serviceaccount:istio-operator:istio-operator" cannot update resource "servicemonitors" in API group "monitoring.coreos.com" in the namespace "istio-system", servicemonitors.monitoring.coreos.com "kubelet" is forbidden: User "system:serviceaccount:istio-operator:istio-operator" cannot update resource "servicemonitors" in API group "monitoring.coreos.com" in the namespace "istio-system", servicemonitors.monitoring.coreos.com "kubernetes-pods-monitor" is forbidden: User "system:serviceaccount:istio-operator:istio-operator" cannot update resource "servicemonitors" in API group "monitoring.coreos.com" in the namespace "istio-system", servicemonitors.monitoring.coreos.com "kubernetes-pods-secure-monitor" is forbidden: User "system:serviceaccount:istio-operator:istio-operator" cannot update resource "servicemonitors" in API group "monitoring.coreos.com" in the namespace "istio-system", servicemonitors.monitoring.coreos.com "kubernetes-services-monitor" is forbidden: User "system:serviceaccount:istio-operator:istio-operator" cannot update resource "servicemonitors" in API group "monitoring.coreos.com" in the namespace "istio-system", servicemonitors.monitoring.coreos.com "kubernetes-services-secure-monitor" 
is forbidden: User "system:serviceaccount:istio-operator:istio-operator" cannot update resource "servicemonitors" in API group "monitoring.coreos.com" in the namespace "istio-system"
      Status:  ERROR
    Base:
      Status:  HEALTHY
    Egress Gateways:
      Status:  HEALTHY
    Ingress Gateways:
      Status:  HEALTHY
    Pilot:
      Status:  HEALTHY
  Status:      ERROR
Events:        <none>
```

I ran `istioctl operator dump` and the cluster role is missing the update verbs for servicemonitors.

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: istio-operator
rules:
# istio groups
- apiGroups:
  - authentication.istio.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - config.istio.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - install.istio.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - networking.istio.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - security.istio.io
  resources:
  - '*'
  verbs:
  - '*'
# k8s groups
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions.apiextensions.k8s.io
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - apps
  - extensions
  resources:
  - daemonsets
  - deployments
  - deployments/finalizers
  - ingresses
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - roles
  - rolebindings
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - events
  - namespaces
  - pods
  - persistentvolumeclaims
  - secrets
  - services
  - serviceaccounts
  verbs:
  - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: istio-operator
subjects:
- kind: ServiceAccount
  name: istio-operator
  namespace: istio-operator
roleRef:
  kind: ClusterRole
  name: istio-operator
  apiGroup: rbac.authorization.k8s.io
---


---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: istio-operator
  name: istio-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: istio-operator
  template:
    metadata:
      labels:
        name: istio-operator
    spec:
      serviceAccountName: istio-operator
      containers:
        - name: istio-operator
          image: docker.io/istio/operator:1.7.0
          command:
          - operator
          - server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1337
            runAsUser: 1337
            runAsNonRoot: true
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
          env:
            - name: WATCH_NAMESPACE
              value: 
            - name: LEADER_ELECTION_NAMESPACE
              value: "istio-operator"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "istio-operator"
            - name: WAIT_FOR_RESOURCES_TIMEOUT
              value: "300s"
            - name: REVISION
              value: ""
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-operator
  labels:
    istio-operator-managed: Reconcile
    istio-injection: disabled
---
apiVersion: v1
kind: Service
metadata:
  namespace: istio-operator
  labels:
    name: istio-operator
  name: istio-operator
spec:
  ports:
  - name: http-metrics
    port: 8383
    targetPort: 8383
  selector:
    name: istio-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: istio-operator
  name: istio-operator
---
# SYNC WITH manifests/charts/base/files
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: istiooperators.install.istio.io
  labels:
    release: istio
spec:
  group: install.istio.io
  names:
    kind: IstioOperator
    plural: istiooperators
    singular: istiooperator
    shortNames:
      - iop
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: Istio control plane revision
          jsonPath: .spec.revision
          name: Revision
          type: string
        - description: IOP current state
          jsonPath: .status.status
          type: string
          name: Status
        - jsonPath: .metadata.creationTimestamp
          description:
            "CreationTimestamp is a timestamp representing the server time when
            this object was created. It is not guaranteed to be set in happens-before order
            across separate operations. Clients may not set this value. It is represented
            in RFC3339 form and is in UTC. Populated by the system. Read-only. Null for
            lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata"
          name: Age
          type: date
      name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              description:
                "APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values.
                More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#resources"
              type: string
            kind:
              description:
                "Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase.
                More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
              type: string
            spec:
              description:
                "Specification of the desired state of the istio control plane resource.
                More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status"
              x-kubernetes-preserve-unknown-fields: true
              type: object
            status:
              description:
                "Status describes each of istio control plane component status at the current time.
                0 means NONE, 1 means UPDATING, 2 means HEALTHY, 3 means ERROR, 4 means RECONCILING.
                More info: https://github.com/istio/api/blob/master/operator/v1alpha1/istio.operator.v1alpha1.pb.html &
                https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status"
              x-kubernetes-preserve-unknown-fields: true
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
---

```
