### ISSUE TITLE
Sporadic "503 NR" occurrences when shutting down a pod

### ISSUE THREAD

**Issue by jtakamine** [istio/istio#26979]
**Bug description**
On some of our workloads, we are observing sporadic "503 NR" responses when shutting down a pod. These responses are observed from the istio-proxy sidecar on the destination pod (inbound logs). Would really appreciate it if someone could shed some light on this behavior.

This is a representative log from a test workload:

```
[2020-09-02T05:23:57.997Z] "GET /foo HTTP/1.1" 503 NR "-" "-" 0 0 0 - "-" "curl/7.64.0" "5086b7e4-72eb-4d59-b140-a36b6aee46ca" "nginx2" "-" - - 10.20.0.14:80 10.20.25.63:47442 - default
```

During steady-state, the test emits logs like this:

```
[2020-09-02T06:04:09.560Z] "GET / HTTP/1.1" 200 - "-" "-" 0 612 0 0 "-" "curl/7.64.0" "35e5337a-e32d-41f9-81b5-0d30d5d8d075" "nginx2" "127.0.0.1:80" inbound|80|http|nginx2.default.svc.cluster.local - 10.20.25.85:80 10.20.1.29:41156 - default
```

With debug logging, I was able to capture this (notice "cluster_not_found"):

```
[Envoy (Epoch 0)] [2020-09-02 04:22:15.728][34][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1354] [C6][S8377628336673183262] Sending local reply with details cluster_not_found
[Envoy (Epoch 0)] [2020-09-02 04:22:15.728][34][debug][filter] [src/envoy/http/mixer/filter.cc:135] Called Mixer::Filter : encodeHeaders 2
[Envoy (Epoch 0)] [2020-09-02 04:22:15.728][34][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1552] [C6][S8377628336673183262] encoding headers via codec (end_stream=true):
':status', '503'
'date', 'Wed, 02 Sep 2020 04:22:15 GMT'
'server', 'istio-envoy'
```

Note that these failed requests occur before the graceful termination period ends. I can't reproduce this consistently, so it seems likely that this is some race condition in the shutdown sequence.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[X] Virtual Machine
[X] Multi Control Plane

**Expected behavior**

During the graceful termination period, the istio-proxy sidecar on a "destination" container should be able to reliably establish connections to the main container, as long as the main container is up and accepting connections.

**Steps to reproduce the bug**

- Attaching a very simple YAML file (nginx.yaml) containing 2 workloads: nginx1 and nginx2--deploy these to some istio-enabled namespace
- Also attaching a script (loop.sh) that pings nginx2 in a tight loop--exec into one of the nginx1 pods and run it
- Tail the logs of one of the nginx2 pods
- Delete that pods using `kubectl delete pod $nginx2_pod`
- Check for "503 NR" responses

Note that I can only reproduce this sporadically.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
$ istioctl version --remote
client version: unknown
control plane version: 1.4.6

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.1", GitCommit:"688c6543aa4b285355723f100302d80431e411cc", GitTreeState:"clean", BuildDate:"2020-07-21T02:37:26Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}

$ helm version
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.6", GitCommit:"dd2e5695da88625b190e6b22e9542550ab503a47", GitTreeState:"clean"}

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
Google Kubernetes Engine

**Comment by jtakamine** [comment]
Files referenced above in the steps to reproduce:

loop.sh:
```
i=0
while true
do
  i=$((i+1))
  curl -s -o /dev/null -w "%{http_code}" http://nginx2/
	sleep .01
  echo
  echo "i: $i"
done
```

nginx.yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx1
spec:
  selector:
    matchLabels:
      app: nginx1
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx1
  labels:
    app: nginx1
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: nginx1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2
spec:
  selector:
    matchLabels:
      app: nginx2
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        lifecycle:
          preStop:
            exec:
              command: ["/bin/bash", "-c", "sleep 120"]

---

apiVersion: v1
kind: Service
metadata:
  name: nginx2
  labels:
    app: nginx2
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: nginx2
```
