### ISSUE TITLE
[istio-gateway] with both PASSTHROUGH and TLS servers will 404 PASSTHROUGH hosts depending on access order from client.

### ISSUE THREAD

**Issue by lindeneau-scott** [istio/istio#26972]
**Describe the issue**
If you have an istio-gateway configured with servers that are setup for both passthrough and tls, if the passthrough host requires mutual tls, istio will 404 the passthrough host _only_ when the passthrough host is accessed second by a single client.

Example istio-gateway:
```
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: product-tls-gateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https-passthrough
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
      httpsRedirect: true
    hosts:
    - "host1.example.com"
  - port:
      number: 443
      name: https-simple
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: certs
      httpsRedirect: true
    hosts:
    - "host2.example.com"
```

Suppose you have virtual services for host1 and host2 listening appropriately. Host1, with passthrough, requires mtls for access. Host2 is a plain http service behind the istio tls.

Using chrome, firefox, edge or I.E. (They all do slightly different variations of the following, some have infinite loops, some just fail once).

Situation 1: 
First, Access https://host1.example.com - The service will resolve, the mtls certificate prompt from the browser will pop, and you can access the service.
Second, Access https://host2.example.com - The service will resolve, and you can access the service.

**Be sure to close your browser between attempts.**

Situation 2:
First, Access https://host2.example.com - The service will resolve, and you can access the service.
Second, Access https://host1.example.com - You will get a 404. Istio logs a 404 NR. 

Close you browser and redo Situation 1. Everything will work correctly. Close your browser, try Situation 2, host1 will fail again.

This obviously has to do with client setups. However I am creating an issue for this because there is a workaround by creating two gateways, and everything will work as expected.

The following works in all situations by splitting the gateway into two gateways and having the virtual services listen on the appropriate gateway.
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: product-passthrough-gateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https-passthrough
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
      httpsRedirect: true
    hosts:
    - "host1.example.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: product-tls-gateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https-simple
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: certs
      httpsRedirect: true
    hosts:
    - "host2.example.com"
```

The following _also_ works, with **MUTUAL** instead of **TLS** as expected (everything requires client certs):
```
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: product-tls-gateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https-passthrough
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
      httpsRedirect: true
    hosts:
    - "host1.example.com"
  - port:
      number: 443
      name: https-simple
      protocol: HTTPS
    tls:
      mode: MUTUAL
      credentialName: certs
      httpsRedirect: true
    hosts:
    - "host2.example.com"
```

**Affected product area (please put an X in all that apply)**
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional Context**
This setup is also assuming STRICT mtls within the mesh.
Istio version 1.6.8 Istio running in kubernetes installed via istioctl
