### ISSUE TITLE
Authorization policy not behaving as expected when using notPath to protect certain paths

### ISSUE THREAD

**Issue by wmuizelaar** [istio/istio#26992]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[x] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
The use case is the following:

We have an RBAC-protect service running that needs to be publicly exposed (i.e.: everyone, authenticated or not needs to be able to access it), except for a specific URI (/internal). To be able to access that specific URI, you need to be authenticated and have a specific group in your JWT-token.

To set this up, I provided these 2 `AuthorizationPolicy`s to the namespace. The first one, allowing access to everything except to /internal:

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  annotations:
  name: allow-stuff-except-internal
  namespace: wietse-local2
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        notPaths:
        - /internal*
  selector:
    matchLabels:
      deployment-name: api-server
```
and the second one to allow access to everyone having the correct group set: 

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  annotations:
  name: allow-sg-team-awesome
  namespace: wietse-local2
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        methods:
        - '*'
        paths:
        - /*
    when:
    - key: request.auth.claims[groups]
      values:
      - AAD/SG_Team_Awesome
  selector:
    matchLabels:
      deployment-name: api-server
```

I would expect that everyone who doesn't have this specific claim set, would get an RBAC denied on `/internal`; but if you have that claim set, that you would get served the content of `/internal`. 

All other pages should work all the time. 

**Steps to reproduce the bug**
Apply above authorizationpolicies. Issue a request to the service's `/internal` with a correct claim. The response will be a HTTP 403 RBAC denied. 

Since there is no explicit DENY rule, I would expect this to give access, in stead of getting a deny. Could it be that the `notPath` is under the hood actually configured as a deny?

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```client version: 1.7.0
control plane version: 1.6.8-5bf4ade4e4ba40977a1bcacc07740631fb56a099
data plane version: 1.6.8 (26 proxies)
```

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-dispatcher", GitCommit:"fd22db44e150011eccc8729db223945384460143", GitTreeState:"clean", BuildDate:"2020-07-24T07:48:37Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.1", GitCommit:"688c6543aa4b285355723f100302d80431e411cc", GitTreeState:"clean", BuildDate:"2020-07-21T02:37:26Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Using `istioctl` across multiple clusters - the cluster running the workload is a different cluster then the cluster where the Istio controlplane is installed.

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE.
