### ISSUE TITLE
Headless services will break connections. 

### ISSUE THREAD

**Issue by chris530** [istio/istio#27018]
If I create a headless service in kubernetes with the same port my code is using,  connections will stop working,   even though the kubernets service is completely unrelated to istio. 

To reproduce, I spun up an app that simply talks to a postgres database every second.    This app runs with the istio-sidecar pod without issue. 

As soon as I create a kubernetes service using that same port,  connections to postgres stop, even though this service is not pointing to the db my test app is using.  

Below I crate a service called christest in a different namespace.  Does not point to the database my test app is using, and basically does nothing. 

```
apiVersion: v1
kind: Service
metadata:
  name: christest
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: christest
    port: 5432
    protocol: TCP
    targetPort: 5432
  type: ClusterIP
```

Deleting this service connections resume.    Not sure why creating a k8 service would affect istio. 

Running istio 1.5.8   but have also seen this issue in istio 1.6.x
EKS 1.15.10
Postgres runs in RDS / AWS

This issue is fixed by adding a ServiceEntry.   Why would I need to do this though ?

**Comment by howardjohn** [comment]
Root cause seems to be this: https://github.com/istio/istio/blob/485a727f70b92e5cdacb62d8035570099b7f1c49/pilot/pkg/networking/core/v1alpha3/listener.go#L902

We check the port is TCP, which excludes unnamed ports

**Comment by chris530** [comment]
Thanks @howardjohn !

**Comment by howardjohn** [comment]
No problem, to be a little more clear either name the port on the Service `tcp` or make a service entry. You shouldn't have to do this though, it's a bug, just a workaround until we have the fix

**Comment by chris530** [comment]
Yep,  confirmed it worked

```
apiVersion: v1
kind: Service
metadata:
  name: christest
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: christest
    port: 5432
    protocol: TCP
    targetPort: 5432
  type: ClusterIP
```

psql postgres:/...
psql: server closed the connection unexpectedly

Changed to 

```
apiVersion: v1
kind: Service
metadata:
  name: christest
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: tcp
    port: 5432
    protocol: TCP
    targetPort: 5432
  type: ClusterIP
```

postgres://....
psql 
WARNING: psql major version 11, server major version 12.
         Some psql features might not work.
SSL connection
Type "help" for help.


Thanks again !
