### ISSUE TITLE
Istio operator incorrectly reconciles affinity

### ISSUE THREAD

**Issue by Niksko** [istio/istio#27032]
**Bug description**

The Istio operator is not declaratively reconciling affinity properly, leading to a situation where the affinity setting for a pod is a mix of past state and current desired state.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

Affinity declared in the `IstioOperator` object is honoured.

**Steps to reproduce the bug**

1. Deploy an `IstioOperator` object with the following setting for pilot affinity:

```
    pilot:
      enabled: true
      k8s:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - istiod
                    - key: istio.io/rev
                      operator: In
                      values:
                        - default
                topologyKey: failure-domain.beta.kubernetes.io/zone
```

2. Allow the Istio operator to reconcile this, creating an `istiod` deployment with the desired affinity
3. Update the `IstioOperator` to the following pilot config:

```
    pilot:
      enabled: true
      k8s:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - istiod
                      - key: istio.io/rev
                        operator: In
                        values:
                          - default
                  topologyKey: failure-domain.beta.kubernetes.io/zone
                weight: 100
```

4. Allow the Istio operator to reconcile the `istiod` deployment.

Expected: 

I would expect that the affinity configuration for the deployment only included the latest value from the `IstioOperator`, ie the `preferredDuringSchedulingIgnoredDuringExecution`

Actual:

The deployment spec contains both the `preferredDuringSchedulingIgnoredDuringExecution` configuration as well as the `requiredDuringSchedulingIgnoredDuringExecution` configuration from the previous `IstioOperator` configuration.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

client version: 1.6.1
control plane version: 1.7.0
data plane version: 1.7.0 (9 proxies), 1.6.3 (1 proxies)

Istio operator is version 1.7.0

**How was Istio installed?**

Using the Istio operator

**Environment where bug was observed (cloud vendor, OS, etc)**

EKS 1.17

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
