### ISSUE TITLE
Gateway configuration can cause ingress gateway to crashloop

### ISSUE THREAD

**Issue by Niksko** [istio/istio#27034]
**Bug description**

It's possible to configure a `Gateway` such that the ingress gateway pods it targets crashloop. If the `Gateway` nominates a low numbered port (<1024), and the corresponding port is not declared on the ingress gateway services targeted by that gateway, the ingress gateway pod will crashloop.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

Ingress gateway pods do not crashloop simply because a `Gateway`/`Service` is misconfigured.

**Steps to reproduce the bug**

1. Deploy an ingress gateway with a service configuration as below:

```
- enabled: true
  name: my-ingressgateway
  label:
    gateway: my-ingressgateway
  k8s:
    service:
      ports:
      - name: https
         port: 443
         protocol: TCP
         targetPort: 8443
```

2. Deploy a `Gateway` that targets this ingress gateway, but with a low number port not in the service definition, eg.

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
spec:
  selector:
    istio: ingressgateway
    gateway: my-ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - some-host
```

The ingress gateway pod will fail to become ready. Logs from the ingress gateway pod show

```
2020-09-03T06:25:42.155070Z     warning envoy config    gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_80: cannot bind '0.0.0.0:80': Permission denied

2020-09-03T06:25:43.399052Z     warn    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 14 successful, 0 rejected; lds updates: 0 successful, 14 rejected
```

Adding port 80 to the `ports` section of the service configuration above with a high number target port fixes this and stops the crash looping ie.

```
- enabled: true
  name: my-ingressgateway
  label:
    gateway: my-ingressgateway
  k8s:
    service:
      ports:
      - name: https
         port: 443
         protocol: TCP
         targetPort: 8443
      - name: https
         port: 80
         protocol: TCP
         targetPort: 8080
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

client version: 1.6.1
control plane version: 1.7.0
data plane version: 1.7.0 (13 proxies), 1.6.3 (1 proxies)

**How was Istio installed?**

Using the istio operator, `1.7.0`

**Environment where bug was observed (cloud vendor, OS, etc)**

EKS 1.17

**Comment by esnible** [comment]
Is this something that could be validated on the IOP before installing/updating Istio?

**Comment by Niksko** [comment]
Not really, given that we're configuring `Gateway` resources after installation.

**Comment by guyromb** [comment]
I can confirm it happens also during installation with Istio Operator
```
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        env:
          - name: ISTIO_META_ROUTER_MODE
            value: "sni-dnat"
        serviceAnnotations:
          cloud.google.com/load-balancer-type: "Internal"
        service:
          type: LoadBalancer
          loadBalancerIP: 10.0.0.47
          ports:
            - name: status-port
              port: 15020
              targetPort: 15020
            - name: http2
              port: 80
              targetPort: 8080 # change to 80 cause to crash
            - name: https
              port: 443
              targetPort: 8443 # change to 443 cause to crash
            - name: tls
              port: 15443
              targetPort: 15443
```
