### ISSUE TITLE
unable to upgrade websocket connection when HTTP 1.1 upgraded to HTTP2

### ISSUE THREAD

**Issue by lukesiler** [istio/istio#27078]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

Destination Rule upgrades HTTP 1.1 traffic to HTTP2 via trafficPolicy.connectionPool.http.h2UpgradePolicy setting but there seems to be no way to set [envoy's cluster http2_protocol_options allow_connect](https://github.com/envoyproxy/envoy/blob/1663949aa998c28bea50af6641d875ee7e219fe6/api/envoy/api/v2/core/protocol.proto#L198) setting to true.

Not sure if this is possible via EnvoyFilter.  I have tried but unsuccessful.

**Affected product area (please put an X in all that apply)**

[ x] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

HTTP 1.1 traffic upgraded to HTTP2 with a way to allow websocket connection to be upgraded.

**Steps to reproduce the bug**

1. Create DestinationRule with trafficPolicy.connectionPool.http.h2UpgradePolicy set to UPGRADE
2. Attempt to use websocket client & server across this traffic flow, it will fail to handshake
3. Toggle trafficPolicy.connectionPool.http.h2UpgradePolicy set to DO_NOT_UPGRADE
4. Websocket client & server will successfully handshake and work as expected 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

> istioctl version --remote
client version: 1.6.8
control plane version: 1.6.8
data plane version: 1.6.8 (4 proxies)

> kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:34Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-gke.2", GitCommit:"fb7add51f767aae42655d39972210dc1c5dbd4b3", GitTreeState:"clean", BuildDate:"2020-06-01T22:20:10Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

istio operator init
IstioOperator config resource (not using helm passthrough)

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by lukesiler** [comment]
After some more time spent on this, I figured out the EnvoyFilter that was necessary here.

```
# allow websocket upgrade over HTTP/2 using https://github.com/envoyproxy/envoy/blob/cc450a2db567ca6e0e0c388de4686b2f313492b7/api/envoy/api/v2/core/protocol.proto#L198
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: h2-upgrade-wss-svcA
  namespace: ns
spec:
  workloadSelector:
    labels:
      app: svcA
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
    patch:
      operation: MERGE
      value:
        typed_config:
          '@type': type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          http2_protocol_options:
            allow_connect: true
```

@howardjohn - maybe you can add this to your [EnvoyFilter Samples wiki page](https://github.com/istio/istio/wiki/EnvoyFilter-Samples)?  I'd be happy to PR a contribution to that page if that is possible.  I also have an ingress extauthz EnvoyFilter that I can contribute.

**Comment by dmitry-tomp** [comment]
Thank goodness I found this solution! 
There is a [similar explanation](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/upgrades) in Envoy docs now, but the `allow_connect` link points to the property inside cluster configuration instead of HttpConnectionManager one. That's quite misleading.

**Comment by thesuperzapper** [comment]
This is a cross-post of my comment from https://github.com/istio/istio/pull/33581#issuecomment-1790092884, as it will probably help some people, and this issue is probably a better issue to re-open the discussion about fixing this problem.

---

@howardjohn @Monkeyanator I think this needs another look.

The warning from the Envoy docs that was raised by @howardjohn was actually under the [following section](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/upgrades#connect-support), not the section for [enabling `allow_connect`](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/upgrades#websocket-over-http-2-or-http-3-hops), and I am pretty sure it does not apply here.

We need to give a way to set `allow_connect` to `true` for a specific sidecar `HttpConnectionManager` (probably using the VirtualService or DestinationRule), so we can avoid people having to make lots of EnvoyFilters like this:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ MY_FILTER }}
  namespace: {{ MY_NAMESPACE }}
spec:
  workloadSelector:
    labels:
      aaa: {{ MY_LABEL }}}
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: SIDECAR_INBOUND
        proxy:
          proxyVersion: '^1\.*.*'
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: MERGE
        value:
          typed_config:
            ## https://www.envoyproxy.io/docs/envoy/v1.23.1/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto.html#extensions-filters-network-http-connection-manager-v3-httpconnectionmanager
            "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager

            ## https://www.envoyproxy.io/docs/envoy/v1.23.1/api-v3/config/core/v3/protocol.proto#envoy-v3-api-msg-config-core-v3-http2protocoloptions
            http2_protocol_options:
              allow_connect: true
```

For reference, this is such a long-standing issue with Istio that Alibaba has a help article on it:
- https://www.alibabacloud.com/blog/alibaba-cloud-service-mesh-faq-1-how-to-use-the-websocket-over-http2-protocol_600045
