### ISSUE TITLE
buildGatewayListeners: Have zero listeners

### ISSUE THREAD

**Issue by hbeffge** [istio/istio#27070]
**Bug description**
HTTPS configurations creates listener, TLS configuration end in error:

```
gateway omitting listener "0.0.0.0_8443" due to: must have more than 0 chains in listener: &envoy_config_listener_v3.Listener{state:impl.MessageState{NoUnkeyedLiterals:pragma.NoUnkeyedLiterals{}, DoNotCompare:pragma.DoNotCompare{}, DoNotCopy:pragma.DoNotCopy{}, atomicMessageInfo:(*impl.MessageInfo)(nil)}, sizeCache:0, unknownFields:[]uint8(nil), Name:"0.0.0.0_8443", Address:(*envoy_config_core_v3.Address)(0xc002e50c00), FilterChains:[]*envoy_config_listener_v3.FilterChain{}, PerConnectionBufferLimitBytes:(*wrapperspb.UInt32Value)(nil), Metadata:(*envoy_config_core_v3.Metadata)(nil), DeprecatedV1:(*envoy_config_listener_v3.Listener_DeprecatedV1)(nil), DrainType:0, ListenerFilters:[]*envoy_config_listener_v3.ListenerFilter(nil), ListenerFiltersTimeout:(*durationpb.Duration)(nil), ContinueOnListenerFiltersTimeout:false, Transparent:(*wrapperspb.BoolValue)(nil), Freebind:(*wrapperspb.BoolValue)(nil), SocketOptions:[]*envoy_config_core_v3.SocketOption(nil), TcpFastOpenQueueLength:(*wrapperspb.UInt32Value)(nil), TrafficDirection:2, UdpListenerConfig:(*envoy_config_listener_v3.UdpListenerConfig)(nil), ApiListener:(*envoy_config_listener_v3.ApiListener)(nil), ConnectionBalanceConfig:(*envoy_config_listener_v3.Listener_ConnectionBalanceConfig)(nil), ReusePort:false, AccessLog:[]*envoy_config_accesslog_v3.AccessLog(nil), HiddenEnvoyDeprecatedUseOriginalDst:(*wrapperspb.BoolValue)(nil)}
```

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
Listeners to be created like with HTTPS

**Steps to reproduce the bug**

When I apply the following config:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: tls-gw
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https-gw
      protocol: HTTPS
    hosts:
    - ingress.example.com
    tls:
      mode: SIMPLE
      credentialName: ingress.example.com
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: tls-vs
  namespace: istio-system
spec:
  hosts:
  - ingress.example.com
  gateways:
  - tls-gw
  http:
  - match:
    - port: 443
    route:
    - destination:
        host: fortio-http-echo.example.com
        port:
          number: 443
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: tls-dr
  namespace: istio-system
spec:
  hosts:
  - fortio-http-echo.example.com
  ports:
  - number: 443
    name: https-dr
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: tls-dr
  namespace: istio-system
spec:
  host: fortio-http-echo.example.com
  trafficPolicy:
    tls:
      mode: SIMPLE
```
I can see the listener via `istioctl proxy-config listeners istio-ingressgateway-123456789-1234 -n istio-system`.

If I change the above config to the following, it is not created and the above error shows up in the log:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: tls-gw
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: tls-gw
      protocol: TLS
    hosts:
    - ingress.example.com
    tls:
      mode: SIMPLE
      credentialName: ingress.example.com
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: tls-vs
  namespace: istio-system
spec:
  hosts:
  - ingress.example.com
  gateways:
  - tls-gw
  tls:
  - match:
    - port: 443
      sniHosts:
      - ingress.example.com
    route:
    - destination:
        host: fortio-http-echo.example.com
        port:
          number: 443
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: tls-dr
  namespace: istio-system
spec:
  hosts:
  - fortio-http-echo.example.com
  ports:
  - number: 443
    name: tls-dr
    protocol: TLS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: tls-dr
  namespace: istio-system
spec:
  host: fortio-http-echo.example.com
  trafficPolicy:
    tls:
      mode: SIMPLE
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```bash
$ istioctl version --remote
client version: 1.7.0
control plane version: 1.7.0
data plane version: 1.7.0 (1 proxies)
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.6-dhc", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"dirty", BuildDate:"2020-08-11T01:30:09Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**
istio-operator profile=default

**Environment where bug was observed (cloud vendor, OS, etc)**
N/A
