### ISSUE TITLE
VirtualService can remove the traffic from the non-existent endpoint destination

### ISSUE THREAD

**Issue by pantianying** [istio/istio#27092]
**Describe the feature request**

i have this virualservice:
```
spec:
  hosts:
  - details
  http:
  - name: remote-namespace-route
    route:
    - destination:
        host: details.A.svc.cluster.local
      weight: 50
    - destination:
        host: details.B.svc.cluster.local
      weight: 50
```

when details in namespace A has no endpoint, I think all traffic should go to another destination （details.B.svc.cluster.local）instead of 50% of requests reporting 503 errors.（Current situation）

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Look forward to hearing from the community~~~~~
