### ISSUE TITLE
VM mesh-expansion does not work with versioned (revision) Istiod

### ISSUE THREAD

**Issue by peter-fe** [istio/istio#27103]
**Bug description**

Virtual machine mesh expansion is not possible on a versioned Istio installation e.g.: 1-6-8
The same setup works flawlessly when Istio is not installed using revisions.

```
2020-09-07T09:01:46.972433Z     info    Subchannel Connectivity change to TRANSIENT_FAILURE
2020-09-07T09:01:46.972487Z     info    pickfirstBalancer: HandleSubConnStateChange: 0xc000ad91b0, {TRANSIENT_FAILURE connection error: desc = "transport: authentication handshake failed: read tcp 10.12.16.2:60072->10.12.32.100:15012: read: connection reset by peer"}
2020-09-07T09:01:46.972520Z     info    Channel Connectivity change to TRANSIENT_FAILURE
2020-09-07T09:03:25.361349Z     info    Subchannel Connectivity change to CONNECTING
2020-09-07T09:03:25.361440Z     info    Subchannel picks a new address "istiod.istio-system.svc:15012" to connect
2020-09-07T09:03:25.361861Z     info    pickfirstBalancer: HandleSubConnStateChange: 0xc000ad91b0, {CONNECTING <nil>}
2020-09-07T09:03:25.361890Z     info    Channel Connectivity change to CONNECTING
2020-09-07T09:03:25.364244Z     info    grpc: addrConn.createTransport failed to connect to {istiod.istio-system.svc:15012  <nil> 0 <nil>}. Err: connection error: desc = "transport: authentication handshake failed: EOF". Reconnecting...
2020-09-07T09:03:25.364266Z     info    Subchannel Connectivity change to TRANSIENT_FAILURE
2020-09-07T09:03:25.364317Z     info    pickfirstBalancer: HandleSubConnStateChange: 0xc000ad91b0, {TRANSIENT_FAILURE connection error: desc = "transport: authentication handshake failed: EOF"}
2020-09-07T09:03:25.364324Z     info    Channel Connectivity change to TRANSIENT_FAILURE
2020-09-07T09:05:38.836288Z     info    Subchannel Connectivity change to CONNECTING
2020-09-07T09:05:38.836376Z     info    Subchannel picks a new address "istiod.istio-system.svc:15012" to connect
2020-09-07T09:05:38.836704Z     info    pickfirstBalancer: HandleSubConnStateChange: 0xc000ad91b0, {CONNECTING <nil>}
2020-09-07T09:05:38.836718Z     info    Channel Connectivity change to CONNECTING
2020-09-07T09:05:38.838558Z     info    grpc: addrConn.createTransport failed to connect to {istiod.istio-system.svc:15012  <nil> 0 <nil>}. Err: connection error: desc = "transport: authentication handshake failed: EOF". Reconnecting...
2020-09-07T09:05:38.838608Z     info    Subchannel Connectivity change to TRANSIENT_FAILURE
2020-09-07T09:05:38.838672Z     info    pickfirstBalancer: HandleSubConnStateChange: 0xc000ad91b0, {TRANSIENT_FAILURE connection error: desc = "transport: authentication handshake failed: EOF"}
2020-09-07T09:05:38.838680Z     info    Channel Connectivity change to TRANSIENT_FAILURE
```

**Affected product area (please put an X in all that apply)**

[ ] Docs
[x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[x ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
Mesh expansion works on a revision install like on a non revision install 

**Steps to reproduce the bug**
- install Istio  as revision -r 1-6-8
- create certs
- install sidecar .deb on VM
- set /etc/hosts
- place certs
- start service

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
client version: 1.6.8
control plane version: 1.6.8
data plane version: 1.6.8 (2 proxies)
```

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.1", GitCommit:"688c6543aa4b285355723f100302d80431e411cc", GitTreeState:"clean", BuildDate:"2020-07-21T02:37:26Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

```
cat <<EOF > values.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          service:
            type: NodePort
  values:
    global:
      meshExpansion:
        enabled: true
EOF
```

```
curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.6.8 sh -
```

```
cd istio-1.6.8
bin/istioctl install -f ../values.yaml -r 1-6-8
```

**Environment where bug was observed (cloud vendor, OS, etc)**
Cluster: GCP/GKE 1.16.13-gke.1
VM: ubuntu-1804

**Comment by howardjohn** [comment]
Looks like it's trying to connect to `istiod` service - if using  revision the service name will be different and you'll need to modify the config to point to this service

**Comment by peter-fe** [comment]
@howardjohn, I assumed that too and tried to set the Pilot env. var as well as the ca_address in the cluster.env.
Then you an see the istiod-1-6-8.istio-system.svc set as discoveryAddress, but the handshake still targets istiod.istio-system.svc and fails.
Is this hard coded somewhere, or how can I override this?

**Comment by peter-fe** [comment]
It would be great if we can get some details on this, we are using VM mesh expansion heavily since Istio 1.0.

It was pointed out that the recommended way of upgrading is to do revisions, but if that breaks the mesh expansion option it should get pointed out somewhere.
That would actually be a blocker for revision upgrades in expanded meshes.

If there are special steps to take to get expansions running with revisions, it would also make sense to extend the current VM mesh expansion documentation with a revision section, to reflect those needed steps.

**Comment by peter-fe** [comment]
@irisdingbj , I just lined you in because you gave very valuable information that last time we had a similar topic.

@howardjohn,

How can we confirm if VM mesh expansion is currently (not) working with a revision of Istiod?

It is an important topic for us, as it will influence our future upgrade strategy:

- If we can go for the recommended way of doing revisions updates.
- Or if we are bound to do in place upgrades as revisions are may not supported for VMs in expanded meshes.

It would be nice if we can get some feedback on this, also to verify that isn't a simple configuration issue or an error on our side.

Best regards

**Comment by howardjohn** [comment]
@peter-fe I haven't looked into this, but there is nothing fundamentally blocking revisions and VMs. The only difference on the VM is a different address is exposed. We likely just need to fix some docs or make some tiny config tweaks.

**Comment by peter-fe** [comment]
@howardjohn,

I'm assuming the same, but changing the pilot address to reflect the revision service name had no impact. I also tried recreating the certs to match the revision host name and setting a host record with the revision service name. It seems like connectivity is given but the cert handshake fails with that awkward "EOF" error.

**Comment by peter-fe** [comment]
@howardjohn,

I got it working finally, but it seems to be a bug though.

When creating a revisioned Istiod installation the service name including the revision e.g. istiod-1-6-8 doesn't get reflected everywhere throughout the manifests.

In this case, causing the VM expansion issues, the destination rule **"meshexpansion-dr-istiod"** and the virtual service **"meshexpansion-vs-istiod"** are referring to **"istiod.istio-system.svc.cluster.local"** instead of **"istiod-1-6-8.istio-system.svc.cluster.local"**.

Everything starts working, as soon as this gets adjusted to reflect the revision.

### DestinationRule & VirtualService created by istioctl install -f ../values-1-6.yaml -r 1-6-8
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  labels:
    install.operator.istio.io/owning-resource: installed-state-1-6-8
    install.operator.istio.io/owning-resource-namespace: istio-system
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.6.8
    release: istio
  name: meshexpansion-dr-istiod
  namespace: istio-system
spec:
  host: istiod.istio-system.svc.cluster.local
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 15012
      tls:
        mode: DISABLE
    - port:
        number: 15017
      tls:
        mode: DISABLE
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    install.operator.istio.io/owning-resource: installed-state-1-6-8
    install.operator.istio.io/owning-resource-namespace: istio-system
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.6.8
    release: istio
  name: meshexpansion-vs-istiod
  namespace: istio-system
spec:
  gateways:
  - meshexpansion-gateway
  hosts:
  - istiod.istio-system.svc.cluster.local
  tcp:
  - match:
    - port: 15012
    route:
    - destination:
        host: istiod.istio-system.svc.cluster.local
        port:
          number: 15012
  - match:
    - port: 15017
    route:
    - destination:
        host: istiod.istio-system.svc.cluster.local
        port:
          number: 443
```

### Working versions after manual adjustment
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  labels:
    install.operator.istio.io/owning-resource: installed-state-1-6-8
    install.operator.istio.io/owning-resource-namespace: istio-system
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.6.8
    release: istio
  name: meshexpansion-dr-istiod
  namespace: istio-system
spec:
  host: istiod-1-6-8.istio-system.svc.cluster.local
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 15012
      tls:
        mode: DISABLE
    - port:
        number: 15017
      tls:
        mode: DISABLE
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    install.operator.istio.io/owning-resource: installed-state-1-6-8
    install.operator.istio.io/owning-resource-namespace: istio-system
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.6.8
    release: istio
  name: meshexpansion-vs-istiod
  namespace: istio-system
spec:
  gateways:
  - meshexpansion-gateway
  hosts:
  - istiod-1-6-8.istio-system.svc.cluster.local
  tcp:
  - match:
    - port: 15012
    route:
    - destination:
        host: istiod-1-6-8.istio-system.svc.cluster.local
        port:
          number: 15012
  - match:
    - port: 15017
    route:
    - destination:
        host: istiod-1-6-8.istio-system.svc.cluster.local
        port:
          number: 443
```
