### ISSUE TITLE
Virtual service routes ignored when httpsRedirect: true in port 443 section

### ISSUE THREAD

**Issue by ceastman-ibm** [istio/istio#27157]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
Don't ignore virtual service paths when https redirect is set (incorrectly on port 443). Just warn on the httpsredirect being set on port 443, since your already https you don.t need to redirect

**Steps to reproduce the bug**

probably related to https://github.com/istio/istio/pull/24958

in the gateway.yaml: have httpsRedirect:true on port 443

```
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - hostname
    tls:
      httpsRedirect: true
      mode: SIMPLE
      credentialName: sslSecretName
```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

istioctl version
client version: 1.7.0
control plane version: 1.7.0
data plane version: 1.7.0 (561 proxies), 1.6.8 (2 proxies)

kubectl version --short
Client Version: v1.17.7
Server Version: v1.17.11+IKS

**How was Istio installed?**
IBM managed istio

**Environment where bug was observed (cloud vendor, OS, etc)**
IBM Cloud

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by linsun** [comment]
@ceastman-ibm thanks for discovering/reporting this.  I imagine it can take you a few hours to track this down.

@howardjohn @rshriram is this as designed, users should not be doing httpsredirect... and we should warn user properly on this?  Seems good to fail at validation time except users may already have this (coming from 1.6 to 1.7), which they will need to run analyzer to discover it.

cc @esnible

**Comment by howardjohn** [comment]
I need to look into it a bit more but we can likely either fail in the webhook or add a warning if it's set. If we go with warning we should make the code just ignore it instead of break

**Comment by ceastman-ibm** [comment]
@linsun users should be able to do httsredirect. It just needs to be on port 80.

I had it set on port 443 which was wrong (it just didn't fail in istio < 1.7 ) . Httpsredirect doesn't make sense on port 443 since that is already https so there is no need to redirect to 443.

**Comment by linsun** [comment]
@ceastman-ibm Yes, agreed, only didn't make sense if it is already using https.
@howardjohn yep at least warning... i think fail would be good if we can detect it precisely, e.g. when a VS is bounded to such a GW but users can deploy VS first.

**Comment by esnible** [comment]
I am happy to write an analyzer for this.

I am uncertain what the exact triggering condition for the warning should be.  Any Gateway with httpsRedirect AND port 443?

**Comment by linsun** [comment]
Thanks Ed!

Yes, pretty much any config like this where `httpsRedirect: true` is used on HTTPS protocol, which is port 443 by default for our gws.

```
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - hostname
    tls:
      httpsRedirect: true
```
