### ISSUE TITLE
istio-agent DNS resolving breaks DNS type Kubernetes Services in ServiceEntries

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#27154]
```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-service
spec:
  endpoints:
  - address: external.external
  hosts:
  - fake3.example.com
  location: MESH_EXTERNAL
  ports:
  - name: http
    number: 80
    protocol: HTTP
  resolution: DNS
```

Results in endpoints:
```
$ ik pc ep `kp vm` | rg fake
69.172.201.153:80                HEALTHY     OK                outbound|80||fake3.example.com
```

`69.172.201.153` is `external.external.com`. Envoy is not going through the dns capture so it uses upstream resolver which doesn't have k8s services. The same happens if using an FQDN
