### ISSUE TITLE
ECDHE-ECDSA-AES256-SHA384 cipherSuite not supported

### ISSUE THREAD

**Issue by tru-cstavares** [istio/istio#27164]
**Bug description**
Have istio v1.4.10 with following config:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  labels:
    app: gateways
  name: istio-autogenerated-k8s-ingress
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - abc.example.com
    port:
      name: https-abc.example.com
      number: 443
      protocol: HTTPS
    tls:
      cipherSuites:
      - '[ECDHE-ECDSA-AES128-GCM-SHA256|ECDHE-ECDSA-CHACHA20-POLY1305]'
      - '[ECDHE-RSA-AES128-GCM-SHA256|ECDHE-RSA-CHACHA20-POLY1305]'
      - ECDHE-ECDSA-AES256-SHA384
      - ECDHE-ECDSA-AES128-SHA
      - ECDHE-ECDSA-AES256-GCM-SHA384
      - ECDHE-ECDSA-AES256-SHA
      - ECDHE-RSA-AES256-GCM-SHA384
      credentialName: ingress-cert-abc.example.com
      maxProtocolVersion: TLSV1_3
      minProtocolVersion: TLSV1_2
      mode: SIMPLE
      privateKey: sds
      serverCertificate: sds
```

If we then restart istio-ingressgateways pods (with restart I mean delete pods one-by-one) and then execute a curl towards https://abc.example.com we get the error: _curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL_. On curl verbosity output I do not see any details about TLS.

After some debug realized that issue was related with cypher ECDHE-ECDSA-AES256-SHA384. If we remove this cypher from istio-autogenerated gateway and if restart istio-ingressgateways pods the url https://abc.example.com response is successfull again.

**Affected product area**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features**

[x] Multi Cluster
[ ] Virtual Machine
[x] Multi Control Plane

**Expected behavior**
Istio should accept cypher ECDHE-ECDSA-AES256-SHA384.

**Steps to reproduce the bug**
Add the config above (describe under "Bug description") with cypher ECDHE-ECDSA-AES256-SHA384 and then restart istio-ingressgateway pods. You should see the SSL error on curl.

Then try to remove cypher (editing istio-autogenerated), curl should have success. Then restart istio-ingressgateway pods. curl should continue with success.

**Version**

```
➜  istioctl version --remote
client version: 1.4.3
citadel version: 1.4.10
galley version: 1.4.10
galley version: 1.4.10
ingressgateway version: 1.4.10
ingressgateway version: 1.4.10
internalingressgateway version:
internalingressgateway version:
nodeagent version:
nodeagent version:
nodeagent version:
nodeagent version:
nodeagent version:
nodeagent version:
pilot version: 1.4.10
pilot version: 1.4.10
policy version: 1.4.10
policy version: 1.4.10
sidecar-injector version: 1.4.10
sidecar-injector version: 1.4.10
telemetry version: 1.4.10
data plane version: 1.4.10 (21 proxies), 1.4.3 (5 proxies)
```

```
➜  kubectl version --short
Client Version: v1.17.3
```

**How was Istio installed?**

Helm template to yaml files and then kubectl apply those files.

**Environment where bug was observed**

Istio is installed on EKS v1.16
