### ISSUE TITLE
Unable to create gateways in istio-system in Istio 1.7

### ISSUE THREAD

**Issue by raswinraaj** [istio/istio#27166]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
Unable to create gateways in istio-system
**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
Should be able to route to the gateway in istio-system as well.
**Steps to reproduce the bug**
Istio Version : 1.7.0 . 
I already have a gateway which is the bookinfo-gateway with tls enabled and port 443 in default namespace. This is working perfectly fine.
Next, I am trying to create a gateway for kiali which is in istio-system. Below is the gateway I have created for kiali. When i try to hit https://mydomain.com:15029/kiali, it doesnt work. Similar setting used to work in Istio 1.4.3. 

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kiali-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 15029
      name: https-kiali
      protocol: HTTPS
    tls:
      mode: SIMPLE      
      credentialName: "my-domain-tls" 
    hosts:
    - "mydomain.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali-vs
  namespace: istio-system
spec:
  hosts:
  - "mydomain.com"
  gateways:
  - kiali-gateway
  http:
  - match:
    - port: 15029
    route:
    - destination:
        host: kiali
        port:
          number: 20001
---
```
I am also attaching my bookinfo-gateway for reference
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bookinfo-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: "my-
[istio-dump.zip](https://github.com/istio/istio/files/5195323/istio-dump.zip)
domain-tls" # must be the same as secret
    hosts:
    - "mydomain.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - "mydomain.com"
  gateways:
  - bookinfo-gateway
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: 9080
```
`
**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
istio:
client version: 1.7.0
control plane version: 1.7.0
data plane version: 1.7.0 (7 proxies)
kubectl version;
Client Version: v1.18.2
Server Version: v1.17.7
**How was Istio installed?**
istioctl install
**Environment where bug was observed (cloud vendor, OS, etc)**
Azure Kubernetes Service
Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
