### ISSUE TITLE
serviceCluster value cannot be overridden by  adding the proxy.istio.io/config annotation

### ISSUE THREAD

**Issue by osswangxining** [istio/istio#27189]
**Bug description**

ProxyConfig defines variables for individual Envoy instances described from the document https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig

The field serviceCluster defines the name for the service_cluster of current Envoy proxy. The default value of this field serviceCluster is from  the  –service-cluster flag in Envoy startup command.

By adding the proxy.istio.io/config annotation to the application Pod metadata specification to override this value, I  did the following config:

```yaml
template:
    metadata:
      annotations:
        proxy.istio.io/config: '{"defaultConfig" : {"serviceCluster" : "MYTEST001" } }'
```
But its value still points to the default value instead of the specified value from annotation.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

The default value should be overridden by annotation.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
1.6.8

**Comment by osswangxining** [comment]
Shown from the source code /pilot/cmd/pilot-agent/config.go as below, it explicitly assigns the value of  –service-cluster flag to the proxyConfig.ServiceCluster.

Confusing why we cannot assign the value from annotation.

func constructProxyConfig() (meshconfig.ProxyConfig, error) {
	......
	
	proxyConfig.Concurrency = int32(concurrency)
	proxyConfig.ServiceCluster = serviceCluster
	// resolve statsd address

**Comment by osswangxining** [comment]
ask for help @hzxuzhonghu @howardjohn

**Comment by lighteness** [comment]
@osswangxining 
try with the below expression, does it works out for you?
```
template:
    metadata:
      annotations:
        proxy.istio.io/config: '{"serviceCluster" : "MYTEST001" } '
```
