### ISSUE TITLE
[1.7] k8s Ingress / Gateway returns 404 and not passing to service || Cannot get k8s Ingress to work together with Istio gateway/virtualservice

### ISSUE THREAD

**Issue by guyromb** [istio/istio#27205]
**Bug description**

IngressGateway (k8s) / Gateway returns 404 and not passing to service/virtualservice. I have a multi gateways setup (private+public). Sometimes it works, sometimes not (http and https).

**UPDATE:**

After playing around for hours.. I could find the following pattern, but I do not how to fix it. 
If we use:
ingressService: istio-ingressgateway-public
ingressClass: istio
ingressSelector: istio-ingressgateway-public

Then the Kubernetes ingresses are working (some old services are still using Ingress kind). But not the Istio gateway with virtual services.
If we change the ingress values in Operator to something else / random, obviously it breaks the Kubernetes ingresses (native ingress) but the Istio gateway and virtual services are working.

Also, I had to manually create "istio-autogenerated-k8s-ingress". This previously was done automatically (e.g. in 1.5.x). Is it that right? 
//

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ x ] Multi Cluster
[ x ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

IngressGateway (k8s) / Gateway should pass to service/virtualservice and give 200

**Steps to reproduce the bug**

Installed a fresh istio

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio
spec:
  hub: docker.io/istio
  tag: 1.7.0

  addonComponents:
    istiocoredns:
      enabled: true

  components:
    egressGateways:
      - name: istio-egressgateway
        enabled: false

    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        env:
          - name: ISTIO_META_ROUTER_MODE
            value: "sni-dnat"
        serviceAnnotations:
          cloud.google.com/load-balancer-type: "Internal"
        service:
          type: LoadBalancer
          loadBalancerIP: {PRIVATE.IP}
          ports:
            - name: status-port
              port: 15020
              targetPort: 15020
            - name: http2
              port: 80
              targetPort: 8080
            - name: https
              port: 443
              targetPort: 8443
            - name: tls
              port: 15443
              targetPort: 15443
        hpaSpec:
          maxReplicas: 5
          minReplicas: 1
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: istio-ingressgateway
          metrics:
            - type: Resource
              resource:
                name: cpu
                targetAverageUtilization: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 2000m
            memory: 1024Mi
        strategy:
          rollingUpdate:
            maxSurge: "100%"
            maxUnavailable: "25%"
    - name: istio-ingressgateway-public
      enabled: true
      label: 
        app: istio-ingressgateway-public
        istio: istio-ingressgateway-public
      k8s:
        env:
        - name: ISTIO_META_ROUTER_MODE
          value: sni-dnat
        hpaSpec:
          maxReplicas: 5
          metrics:
          - resource:
              name: cpu
              targetAverageUtilization: 80
            type: Resource
          minReplicas: 1
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: istio-ingressgateway-public
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        service:
          loadBalancerIP: {PUBLIC_IP}
          type: LoadBalancer
          ports:
            - port: 80
              targetPort: 8080
              name: http2
            - port: 443
              targetPort: 8443
              name: https
            - port: 1935
              name: tcp
        strategy:
          rollingUpdate:
            maxSurge: 100%
            maxUnavailable: 25%

  values:
    meshConfig:
      accessLogFile: "/dev/stdout"
      accessLogFormat: ""
      accessLogEncoding: JSON
      enableTracing: true
      ingressService: istio-ingressgateway-public
      ingressClass: istio
    global:
      # Provides dns resolution for global services
      podDNSSearchNamespaces:
        - global
      logging:
        level: "default:info"
      logAsJson: false
      jwtPolicy: third-party-jwt
      tracer:
        zipkin:
          address: "jaeger-agent.default:5778"
        datadog:
          address: "$(HOST_IP):8126"
        stackdriver:
          debug: false
          maxNumberOfAttributes: 200
          maxNumberOfAnnotations: 200
          maxNumberOfMessageEvents: 200
      trustDomain: "cluster.local"
      outboundTrafficPolicy:
        mode: ALLOW_ANY

      multiCluster:
        enabled: true

      controlPlaneSecurityEnabled: true

    pilot:
      autoscaleEnabled: true
      autoscaleMin: 1
      autoscaleMax: 3
      replicaCount: 1
      image: pilot
      traceSampling: 1.0

    gateways:
      istio-egressgateway:
        env:
          # Needed to route traffic via egress gateway if desired.
          ISTIO_META_REQUESTED_NETWORK_VIEW: "external"
      istio-ingressgateway:
        sds:
          enabled: true
        autoscaleEnabled: true
        debug: info

    sidecarInjectorWebhook:
      enableNamespacesByDefault: false
      rewriteAppHTTPProbe: true
      injectLabel: istio-injection
      objectSelector:
        enabled: false
        autoInject: true
```

**Gateway:**
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-autogenerated-k8s-ingress
  namespace: istio-system
spec:
  selector:
    istio: istio-ingressgateway-public
  servers:
  - hosts:
    - '*.EXAMPLE.COM'
    port:
      name: http
      number: 80
      protocol: HTTP
  - hosts:
    - '*.EXAMPLE.COM'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: ingress-cert
      mode: SIMPLE
```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

1.7.0

**How was Istio installed?**

Istio Operator (using istioctl)

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
> istio-autogenerated-k8s-ingress

This is done automatically internally to Istio now.

Can you show the config dump (https://github.com/istio/istio/wiki/Troubleshooting-Istio) when you are getting 404s (as well as what path you are getting 404 on) and the output of `curl localhost:8080/debug/configz` from the istiod pod? That should see if there are some sort of conflict going on

**Comment by guyromb** [comment]
Thanks @howardjohn 
Example for end-point that returns 404 (uses Kubernetes Ingress): api-master.app.HIDDEN.NAME.COM

Here are the files:

**GW1 istio-ingressgateway**
[gw1_config_dump.json.log](https://github.com/istio/istio/files/5210620/gw1_config_dump.json.log)

**GW2 istio-ingressgateway-public**
[gw2_public_config_dump.json.log](https://github.com/istio/istio/files/5210621/gw2_public_config_dump.json.log)

**istiod config**
[istiod-discovery.config.json.log](https://github.com/istio/istio/files/5210647/istiod-discovery.config.json.log)

**Comment by guyromb** [comment]
FYI, I tried to upgrade to 1.7.1. Same issue

**Comment by guyromb** [comment]
Checking the issues, it seems related to "404 errors occur when multiple gateways configured with same TLS certificate".
The suggested way to avoid it is "..by configuring a single wildcard Gateway, instead of two (gw1 and gw2).".

However, since the Gateways are generated automatically by Istio, I am not sure how to tackle this?

**Comment by ldemailly** [comment]
I also see ~50% 404 failure with

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dashboard-virtualservice
  namespace: istio-system
spec:
  hosts:
    - our.actual.host
  gateways:
    - istio-system/dashboard-gateway # Gateway that allows port 800
  http:
                     
    - match:
        - uri:
            prefix: /grafana
        - uri:
            prefix: /dashboard

      route:
        - destination:
            host: grafana.istio-system.svc.cluster.local
            port:
              number: 3000
    - match:
        - uri:
            prefix: /kiali
      route:
        - destination:
            host: kiali.istio-system.svc.cluster.local
            port:
              number: 20001
    - match:
        - uri:
            prefix: /jaeger       
      route:
        - destination:
            host: jaeger-query.istio-system.svc.cluster.local
            port:
              number: 16686 
    - match:
        - uri:
            prefix: /fortio
      route:
        - destination:
            host: fortio-client.fortio.svc.cluster.local
            port:
              number: 8080          
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: prometheus.istio-system.svc.cluster.local
            port:
              number: 9090
```

```shell
$ curl -I https://our-actual-ingress-url/jaeger/static/js/1.d7e3159f.chunk.js
HTTP/2 404 
content-type: text/plain; charset=utf-8
x-content-type-options: nosniff
date: Thu, 12 Nov 2020 20:49:40 GMT
content-length: 19
x-envoy-upstream-service-time: 0
server: istio-envoy

$ curl -I https://our-actual-ingress-url/jaeger/static/js/1.d7e3159f.chunk.js
HTTP/2 200 
accept-ranges: bytes
content-length: 2131263
content-type: application/javascript
last-modified: Tue, 17 Dec 2019 11:55:06 GMT
date: Thu, 12 Nov 2020 20:49:41 GMT
x-envoy-upstream-service-time: 0
server: istio-envoy
```

ingress logs:
```
[2020-11-12T21:11:54.199Z] "HEAD /jaeger/static/js/1.d7e3159f.chunk.js HTTP/2" 200 - "-" "-" 0 0 0 0 "10.128.35.19" "curl/7.64.1" "89b37e93-1860-4fef-8b7d-5d6fd0b26095" "our-actual-ingress-url" "10.128.37.175:16686" outbound|16686||jaeger-query.istio-system.svc.cluster.local 10.128.36.158:49836 10.128.36.158:8443 10.128.35.19:11930 dashboard-west-2.dev.msc.rokulabs.net -
[2020-11-12T21:11:56.819Z] "HEAD /jaeger/static/js/1.d7e3159f.chunk.js HTTP/2" 404 - "-" "-" 0 0 0 0 "10.128.32.8" "curl/7.64.1" "64cca1cf-9970-48e7-95dd-5fee53c2b1b1" "our-actual-ingress-url" "10.128.37.169:16686" outbound|16686||jaeger-query.istio-system.svc.cluster.local 10.128.36.158:47206 10.128.36.158:8443 10.128.32.8:10683 dashboard-west-2.dev.msc.rokulabs.net -
```

**Comment by stamak** [comment]
Have the similar issue after upgrade form *1.6.11* to *1.7.4* 
Requests to some services returns 404
We also have 2 ingress gateways - public and internal
We do not have jaeger deployed 😞

**Comment by guyromb** [comment]
@stamak @ldemailly this is the solution - https://github.com/istio/istio/pull/27326
Unfortunately, it is not merged yet by Istio team @howardjohn .

**Comment by stamak** [comment]
@guyromb  thx 
Seems I found root cause of 404, btw we do not use k8s ingress
Public ingress-gateway access logs show that traffic is sent to other service instead!

1.7.4 Public ingress-gateway access logs
```
[2020-11-13T08:13:46.881Z] "GET /health HTTP/2" 404 - "-" "-" 0 5051 4 3 "172.29.6.194" "curl/7.64.1" "79eef750-49a2-4e1d-a05d-93bf251d30e2" 
"serviceA.fqdn.net" "172.29.2.34:8080" outbound|8080||serviceB.NAMESPACE.svc.cluster.local 
172.29.5.237:51562 172.29.5.237:8443 172.29.6.194:48326 serviceA.fqdn.net -
```

After downgrading back to 1.6.11 everything is working
Public ingress-gateway access logs
```
[2020-11-13T10:37:32.603Z] "GET /health HTTP/2" 200 - "-" "-" 0 17 4 4 "172.29.83.30" "curl/7.64.1" "2a1faf00-2c73 46d0-96d3-60136208ea90" 
"serviceA.fqdn.net" "172.29.4.118:4455" outbound|4455||serviceA.NAMESPACE.svc.cluster.local 
172.29.51.205:44326 172.29.51.205:8443 172.29.83.30:1503 serviceA.fqdn.net -
```

**Comment by howardjohn** [comment]
Looking into this, this is a duplicate of https://github.com/istio/istio/issues/24385. I chose that one as the source of truth since its referenced in our codebase already. Please follow that one ,thanks!

**Comment by howardjohn** [comment]
@guyromb to the original config, your configuration looks like this:
```yaml

servers:
- hosts:
  - '*.app.hidden.name.com'
  port:
    name: https-443-ingress-api-ingress-develop-0
    number: 443
    protocol: HTTPS
  tls:
    credentialName: app-hidden.name.com-tls
    mode: SIMPLE
---
servers:
- hosts:
  - '*.app.hidden.name.com'
  port:
    name: https
    number: 443
    protocol: HTTPS
  tls:
    credentialName: ingress-cert
    mode: SIMPLE
```

if/when we fix the underlying bug that these are not merged ever, they are still in conflict as the credentials are different, so would always be in conflcit
