### ISSUE TITLE
Calling a gRPC service results in status code 2: "No status received"

### ISSUE THREAD

**Issue by xiaozhongliu** [istio/istio#27207]
**Bug description**
Error occurs when calling a gRPC service which is behind the istio gateway:
![image](https://user-images.githubusercontent.com/17674404/92720206-defd2f00-f396-11ea-924b-bcb03052753e.png)

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
We should get status code 0: "OK"

**Steps to reproduce the bug**
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway-isolated
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - k8s-demo-grpc.internal.sample.com
      port:
        name: grpc
        number: 80
        protocol: GRPC
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: k8s-demo-grpc-isolated
  namespace: stage-c1
spec:
  hosts:
    - k8s-demo-grpc.internal.sample.com
  gateways:
    - default/gateway-isolated
  http:
    - route:
        - destination:
            host: k8s-demo-grpc
```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
```bash
~ istioctl version --remote
1.6.8

~ kubectl version --short
Client Version: v1.17.0
Server Version: v1.16.9-aliyun.1
```

**How was Istio installed?**
Aliyun ASM

**Environment where bug was observed (cloud vendor, OS, etc)**
Aliyun ASM, CentOS 7
