### ISSUE TITLE
Ingress gateway use case of HTTPS to HTTPS doesn't work.

### ISSUE THREAD

**Issue by bjwyun** [istio/istio#27208]
installed by Service mesh operator 1.1.7 
![image](https://user-images.githubusercontent.com/31024715/92723866-4669ad80-f39c-11ea-9f88-c2b3aca9b96a.png)

Two namespaces is used, 
first is my nginx namespace:  ns1
second is istio-system.
purpose:
Https request from Webpage and using gateway pass it to nginx HTTPS port 443.

1. Webpage 443 to nginx HTTP 80 port, as HTTP of nginx is redirect to HTTPS port. so web page got so much redirect error.but it seems works.
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cpd-nginx-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*"
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-svc
spec:
  hosts:
  - "*"
  gateways:
  - cpd-nginx-gateway
  tcp:
  - match:
    - uri:
        exact: /*
    route:
    - destination:
        host: nginx-svc.ns1.svc.cluster.local
        port:
          number: 80
```

2. using tls in VirtualService returns 404

```

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cpd-nginx-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "a.example.com"
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-svc
spec:
  hosts:
  - "a.example.com"
  gateways:
  - cpd-nginx-gateway
  tls:
  - name: "https-nginx-route"
    match:
    - uri:
        exact: /*
      sni_hosts:
      - "a.example.com"
    route:
    - destination:
        host: nginx-svc.ns1.svc.cluster.local
        port:
          number: 443
```

logs from ingressgate is 
```
[2020-09-10T05:47:47.316Z] "GET /zen HTTP/2" 404 - "-" "-" 0 0 0 - "10.254.4.1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36" "ea9f7fa1-6aaf-9694-af5a-fd9c19cdbbac" "a.example.com" "-" - - 10.254.8.76:8443 10.254.4.1:46464 a.example.com default
{"duration":"0","route_name":"default","upstream_transport_failure_reason":"-","downstream_local_address":"10.254.8.76:8443","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36","response_code":"404","response_flags":"-","start_time":"2020-09-10T05:47:47.316Z","request_id":"ea9f7fa1-6aaf-9694-af5a-fd9c19cdbbac","method":"GET","upstream_host":"-","x_forwarded_for":"10.254.4.1","requested_server_name":"a.example.com","bytes_received":"0","istio_policy_status":"-","bytes_sent":"0","upstream_cluster":"-","downstream_remote_address":"10.254.4.1:46464","path":"/zen","authority":"a.example.com","protocol":"HTTP/2","upstream_service_time":"-","upstream_local_address":"-"}
```

**Comment by howardjohn** [comment]
> using tls in VirtualService returns 404

This is expected, you cannot do tls routing since the gateway is terminating TLS.

**Comment by bjwyun** [comment]
@howardjohn So do you have any ideas to solve this situation ?  
should be 
```
client sends HTTPS -> TLS termination by the ingress gateway -> HTTP -> HTTP routing by the VirtualService -> TLS origination by the DestinationRule sends HTTPS -> destination service
``` ?

**Comment by howardjohn** [comment]
Yes use you first config with destination rule should work ok?

**Comment by bjwyun** [comment]
@howardjohn thanks. i'll try in this way 
```
client -> ingress gateway 443 ->virtualService 80 -> DestinationRule -> destination service 443
```

**Comment by bjwyun** [comment]
@howardjohn do you have any simple for this process ?

**Comment by bjwyun** [comment]
@howardjohn  I add a destination rule in VS to translate HTTP to HTTPS by
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: nginx-svc
spec:
  host: nginx-svc
  subsets:
  - name: nginx
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: SIMPLE
          serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
          privateKey: /etc/istio/ingressgateway-certs/tls.key
          sni: nginx-svc
```
but got a new error of 
```
[2020-09-11T06:57:57.391Z] "GET /zen HTTP/2" 503 UF,URX "-" "TLS error: 336151568:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure" 0 91 28 - "10.254.4.1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36" "fcff3621-02b1-929b-8617-a947e64196ec" "a.apps.dmcbvt.os.fyre.ibm.com" "10.254.0.223:8443" outbound|443|nginx|nginx-svc.cpd.svc.cluster.local - 10.254.8.76:8443 10.254.4.1:57406 a.example.com -
{"upstream_cluster":"outbound|443|nginx|nginx-svc.cpd.svc.cluster.local","downstream_remote_address":"10.254.4.1:57406","path":"/zen","authority":"a.example.com","protocol":"HTTP/2","upstream_service_time":"-","upstream_local_address":"-","duration":"28","route_name":"-","upstream_transport_failure_reason":"TLS error: 336151568:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure","downstream_local_address":"10.254.8.76:8443","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36","response_code":"503","response_flags":"UF,URX","start_time":"2020-09-11T06:57:57.391Z","request_id":"fcff3621-02b1-929b-8617-a947e64196ec","method":"GET","upstream_host":"10.254.0.223:8443","x_forwarded_for":"10.254.4.1","requested_server_name":"a.example.com","bytes_received":"0","istio_policy_status":"-","bytes_sent":"91"}
```

**Comment by morvencao** [comment]
I found some relevant issues that may helps:
https://github.com/istio/istio/issues/19609
https://github.com/istio/istio/issues/8029

**Comment by bjwyun** [comment]
@howardjohn @morvencao thanks guys, it's my nginx configuration error, after I disable ssl_ciphers, everything goes well

**Comment by raonelakurti** [comment]
@bjwyun   @morvencao 
Not able to access Jenkins from browser seeing "**400 Bad Request** The plain HTTP request was sent to HTTPS port". Using Istio-ingress gateway

Jenkins installed through helm chart with a custom installation path.

    helm install argo-jenkins -f jenkins-volume.yaml jenkinsci/jenkins -n jenkins --set controller.jenkinsUriPrefix='/jenkinsargo'

We have a front-end Istio-ingress gateway from all the browser requests.
GW.Yaml:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: jenkins-gw
  namespace: jenkins
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
```

VS.Yaml:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jenkins-vs
  namespace: jenkins
spec:
  gateways:
  - jenkins-gw.jenkins
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /jenkinsargo
    route:
    - destination:
        host: argojenkins.jenkins.svc.cluster.local
        port:
          number: 8080
```

Able to access jenkins home page, when trying to configure the jenkins security seeing above error.

PFA for the initial home page and error page.
[Error page after redirecting][1]


[Jenkins home page][2]


  [1]: https://i.stack.imgur.com/j3zo9.png
  [2]: https://i.stack.imgur.com/sEXR6.png

**Comment by bjwyun** [comment]
@rajusharma I also meet the errors when i try to use http request to visit https port after Service mesh operator updated in Open shift market.
I've seen that the security errors is try to visit port 443. does this port is for HTTPS ?

**Comment by bjwyun** [comment]
@rajusharma  maybe you should add something like
```
- port:
         number: 443
         name: https
         protocol: HTTPS
       hosts:
       - "*.{yourip}"
       tls:
         mode: PASSTHROUTH
```
in ingressgateway
NOT FOR SURE about the value for ``mode``

**Comment by raonelakurti** [comment]
@bjwyun  Already tried with 

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: jenkins-gw
  namespace: jenkins
spec:
  selector:
    custom: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
    hosts:
    - "*"
```

Same error.

**Comment by bjwyun** [comment]
@raonelakurti I think there's still some changes needed about uri mapping in VS.yaml. as we can see the HTTPS security URL also contain ``/jenkinsargo``, you can check about this doc about how https works.
https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/

**Comment by raonelakurti** [comment]
@bjwyun 
This what I'm trying.
Gw.yaml
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: jenkins-gw
  namespace: jenkins
spec:
  selector:
    custom: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
    hosts:
    - "*"
```

VirtualService1.Yaml:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jenkins-vs
  namespace: jenkins
spec:
  gateways:
  - jenkins-gw.jenkins
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /jenkinsargo
    route:
    - destination:
        host: argojenkins.jenkins.svc.cluster.local
        port:
          number: 8080
```

VirtualService2.yaml:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jenkins-vs1
  namespace: jenkins
spec:
  gateways:
  - jenkins-gw.jenkins
  hosts:
  - '*'
  tls:
  - match:
    - port: 443
      sniHosts:
      - "*"
    route:
    - destination:
        host: argojenkins.jenkins.svc.cluster.local
        port:
          number: 8080
```

**Comment by bjwyun** [comment]
@raonelakurti in VirtualService2.yaml the - destination: may need some change
1. we should check the  service of ``argojenkins.jenkins.svc.cluster.local`` check if it opens HTTPS port such as ``8443`` 
2. route HTTPS request to the {HTTPS port}

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jenkins-vs1
  namespace: jenkins
spec:
  gateways:
  - jenkins-gw.jenkins
  hosts:
  - '*'
  tls:
  - match:
    - port: 443
      sniHosts:
      - "*"
    route:
    - destination:
        host: argojenkins.jenkins.svc.cluster.local
        port:
          number: {HTTPSPORT}
```

![image](https://user-images.githubusercontent.com/31024715/117271419-bfb69300-ae8c-11eb-94fc-bacea0b4b20c.png)

**Comment by bjwyun** [comment]
if ``targetPort`` doesn't work please try ``port``

**Comment by raonelakurti** [comment]
@bjwyun 
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jenkins-vs
  namespace: jenkins
spec:
  gateways:
  - jenkins-gw.jenkins
  hosts:
  - '*'
  http:
  - headers:
      request:
        set:
          x-forwarded-port: "443"
          x-forwarded-proto: https 
    match:
    - uri:
        prefix: /jenkinsargo
    route:
    - destination:
        host: argojenkins.jenkins.svc.cluster.local
        port:
          number: 8080
```

After adding x-forward port, it's working fine.
Thanks
