### ISSUE TITLE
sidecar metrics disappear when runAsUser or RunAsGroup is 1337

### ISSUE THREAD

**Issue by axelgobletbdr** [istio/istio#27202]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

When running a pod where the main container has a `securityContext` containing value 1337 in either `runAsUser` or `runAsGroup`, metrics like `istio_requests_total` disappear from the sidecar prometheus endpoint. 1337 is the value assigned to the sidecar security context fields.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

The sidecar metrics are shown if runAsUser or RunAsGroup is 1337

**Steps to reproduce the bug**

1. Tested using minikube 1.13. Start cluster using `minikube start --cni=calico --memory=10000 --cpus=4 --network-plugin=cni`
2. Install istio (1.7.0) using `istioctl install -f istio.yaml` where `istio.yaml` is the `IstioOperator` manifest shown below.
3. Deploy a mesh of services with various security contexts (see manifest 2 below).
4. When all pods are running, check the sidecar metrics of each pod: `k exec -it -n n0 <pod-name> -c istio-proxy -- curl localhost:15000/stats/prometheus | grep istio_requests_total`. You will see no metrics for deployment `client1337`, and metrics for the others. 

```
apiVersion: install.istio.io/v1alpha2
kind: IstioOperator
metadata:
  name: istio-operator
  namespace: istio-system
spec:
  profile: minimal
  components:
    cni:
      enabled: true
  values:
    cni:
      excludeNamespaces:
      - istio-system
      - kube-system
      logLevel: info
```

```
apiVersion: v1
kind: Namespace
metadata:
  name: n0
  labels:
    name: n0
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: n0
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: main
        image: bitnami/nginx
        ports:
        - containerPort: 8080
        volumeMounts:
        # required for permissions
        - mountPath: /opt/bitnami/nginx/tmp
          name: nginx-tmp
      volumes:
      # required for permissions
      - name: nginx-tmp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: n0
  labels:
    app: server
spec:
  type: ClusterIP
  selector:
    app: server
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client1338
  namespace: n0
  labels:
    app: client1338
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client1338
  template:
    metadata:
      labels:
        app: client1338
    spec:
      containers:
      - name: main
        securityContext:
          runAsNonRoot: true
          runAsUser: 1338
          runAsGroup: 1338
        image: busybox
        command: 
        - /bin/sh
        - -c
        - "while true; do wget -O/dev/null server:8080 && sleep 10; done"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client1337
  namespace: n0
  labels:
    app: client1337
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client1337
  template:
    metadata:
      labels:
        app: client1337
    spec:
      containers:
        - name: main
          securityContext:
            runAsNonRoot: true
            runAsUser: 1337
            runAsGroup: 1337
          image: busybox
          command:
            - /bin/sh
            - -c
            - "while true; do wget -O/dev/null server:8080 && sleep 10; done"
```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

```
istioctl version --remote

client version: 1.7.0
control plane version: 1.7.0
data plane version: 1.7.0 (3 proxies)
```

```
kubectl version --short

Client Version: v1.18.6
Server Version: v1.19.0
```

**How was Istio installed?**

Described in **steps to reproduce**.

**Environment where bug was observed (cloud vendor, OS, etc)**

Minikube, Ubuntu 19.10

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
