### ISSUE TITLE
envoy.filters.network.tcp_cluster_rewrite doesn't work

### ISSUE THREAD

**Issue by tholcman** [istio/istio#27204]
**Bug description**
We have followed https://istio.io/latest/docs/setup/install/multicluster/gateways/ to have multi-cluster mesh configured. Traffic is properly routed from source cluster to the remote one but the ingressgateway says:

```
[2020-09-10T08:33:49.743Z] "- - -" 0 NR "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.179.64.13:15443 10.179.64.1:51854 - -
[2020-09-10T08:33:49.747Z] "- - -" 0 NR "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.179.64.13:15443 10.128.154.61:15808 - -
...
```

It is probably connected to not-working EnvoyFilter which should replace global -> svc.cluster.local
```
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  ...
spec:
  workloadSelector:
 ...
  configPatches:
  - ...
    patch:
      operation: INSERT_AFTER
      value:
        name: "envoy.filters.network.tcp_cluster_rewrite"
        config:
          cluster_pattern: "\\.global$"
          cluster_replacement: ".svc.cluster.local"
```

if we check the proxy configuration, we see that the config is missing:
```
$ istioctl  proxy-config listener istio-ingressgateway-768fd8b85-p68cx.istio-system --port 15443 -o json
...
                    {
                        "name": "envoy.filters.network.tcp_cluster_rewrite"
                    },
...
```
and I guess it should look like:
```
...
                    {
                        "name": "envoy.filters.network.tcp_cluster_rewrite",
                        "config": {
                            "cluster_pattern": "\\.global$",
                            "cluster_replacement": ".svc.cluster.local"
                        }
                    },
...
```

I am not sure what is relation config - typed_config, if the tcp_cluster_rewrite, which is custom istio-proxy filter, do support typed_config somehow.

**Affected product area (please put an X in all that apply)**

[X] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
Crosscluster mTLS described in docs works.

**Steps to reproduce the bug**
Follow the guide in docs

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
```
$ istioctl version
client version: 1.7.0
control plane version: 1.7.0
data plane version: 1.7.0 (10 proxies)
```

**How was Istio installed?**
IstioOperator.install.istio.io/v1alpha1

If necessary I can provide whole manifest.

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE v1.16.13-gke.1

**Comment by tholcman** [comment]
In version 1.6.8 it does work! And the mentioned part of Envoy config looks like 
```
                    {
                        "name": "envoy.filters.network.tcp_cluster_rewrite",
                        "hiddenEnvoyDeprecatedConfig": {
                            "cluster_pattern": "\\.global$",
                            "cluster_replacement": ".svc.cluster.local"
                        }
                    },
```
the `hiddenEnvoyDeprecatedConfig` seems very suspicious! :D

**Comment by GusTheSadGeek** [comment]
This is happening to me with 1.7.1

**Comment by cocotyty** [comment]
👍

**Comment by mwhittington21** [comment]
Running into the same problem on 1.7.0 at the moment.

**Comment by tholcman** [comment]
Just re-posting workaround from @kirecek PR so it is visible at the first sight:

in EnvoyFilter you can use typed_config:
```
      ...
      operation: INSERT_AFTER
      value:
        name: "envoy.filters.network.tcp_cluster_rewrite"
        typed_config:
          "@type": "type.googleapis.com/istio.envoy.config.filter.network.tcp_cluster_rewrite.v2alpha1.TcpClusterRewrite"
          cluster_pattern: "\\.global$"
          cluster_replacement: ".svc.cluster.local"
```
