### ISSUE TITLE
Setting DestinationRule.caCertificates breaks cluster wide mTLS

### ISSUE THREAD

**Issue by nairb774** [istio/istio#27218]
**Bug description**

Applying the following yaml seems to break all mTLS communication in the cluster:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: google
  namespace: some-other-ns
spec:
  hosts:
  - www.google.com
  ports:
  - number: 443
    name: http
    protocol: TCP
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: google
  namespace: some-other-ns
spec:
  host: "www.google.com"
  trafficPolicy:
    tls:
      mode: SIMPLE
      caCertificates: /etc/ssl/certs/ca-certificates.crt
```

It may take a minute or two for SSL errors like the following to start showing up:
```
[2020-09-11T18:34:41.098Z] "GET / HTTP/1.1" 503 UF,URX "-" "TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED" 0 91 21 - "-" "curl/7.69.1" "cadc0151-7ada-44f7-a209-f52a6fefe17f" "httpbin.sample-app.svc.cluster.local" "10.1.0.19:80" outbound|80||httpbin.sample-app.svc.cluster.local - 10.106.161.48:80 10.1.0.18:59016 - default
```

If the `DestinationRule.caCertificates` attribute is not set, then communication within the cluster is not broken. Removing the `caCertificates` attribute is not usually sufficient to have the cluster recover. In many cases it requires all affected sidecars to be restarted.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

The caCertificates feature is functions, and is able to be used to properly validate Egress TLS Origination.

**Steps to reproduce the bug**

The following was isolated on Docker Desktop for Mac running Kubernetes 1.16.5.

Install the Istio 1.7.0 operator (istioctl installed via brew):
```bash
$ istioctl operator init
Using operator Deployment image: docker.io/istio/operator:1.7.0
✔ Istio operator installed
✔ Installation complete
```

Install the control plane with the following yaml:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-system
  namespace: istio-system
spec:
  profile: default
  meshConfig:
    accessLogFile: /dev/stdout # Only needed for observing the broken communication.
```

Configure a few services to be able to communicate with each other. The httpbin/curl pod combo used in many of the examples is sufficient. These services can be running in _any_ namespace you choose.

Apply the ServiceEntry/DestinationRule to _any_ namespace. They can be applied to a brand new namespace, empty namespace.

Make periodic attempts to communicate between the sample services installed. Within a few minutes (usually less than 10), communication will start to fail, and log lines like above will be generated by Envoy.

Full reproduction yaml: ~[drca-repro.yaml.gz](https://github.com/istio/istio/files/5203867/drca-repro.yaml.gz)~ (<- old version with typos) [drca-repro.yaml.gz](https://github.com/istio/istio/files/5210955/drca-repro.yaml.gz) It may need to be applied a few times, and pods restarted to trigger injection, but all the parts are there.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

```
$ istioctl version --remote
client version: 1.7.0
control plane version: 1.7.0
data plane version: 1.7.0 (3 proxies)
$ kubectl version --short
Client Version: v1.19.1
Server Version: v1.16.6-beta.0
```

**How was Istio installed?**

Operator, default profile.

**Environment where bug was observed (cloud vendor, OS, etc)**

Initially observed on AWS EKS 1.16.13, but was able to reproduce with Docker Desktop for Mac running Kubernetes 1.16.5.

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

~[istio-dump.tar.gz](https://github.com/istio/istio/files/5203866/istio-dump.tar.gz)~ (<- From bad repro)

[istio-dump.tar.gz](https://github.com/istio/istio/files/5210966/istio-dump.tar.gz)
