### ISSUE TITLE
Provided additionalContainers definition not properly implemented by Istio Operator.

### ISSUE THREAD

**Issue by abhioncbr** [istio/istio#27226]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
I am providing `additionalContainers` configuration to the ingress-gateway for the demo profile. Installation is getting processed through the istio-operator, however, some of the pod configurations are getting dropped in the final deployment of ingress-gateway. Here are the provided configs

```yaml
    additionalContainers:
          - name: appgw-ssl-readiness-probe
            image: abc:0.22
            containerPort:
              - port: 15022
                name: ssl-status-port  
            readinessProbe:
              failureThreshold: 20
              httpGet:
                path: /healthz/ready
                port: 15022
                scheme: HTTPS
              initialDelaySeconds: 1
              periodSeconds: 2
              successThreshold: 1
              timeoutSeconds: 1
            volumeMount:
              - name: appgw-ssl-readiness-probe-certs
                mountPath: /home/node/app/certs/
                readOnly: true
```

Deployment of the ingress-controller consist following output for the provided additional container:
```yaml
           -  name: appgw-ssl-readiness-probe
              image: abc:0.22
              readinessProbe:
               failureThreshold: 20
               httpGet:
                path: /healthz/ready
                port: 15022
                scheme: HTTPS
               initialDelaySeconds: 1
               periodSeconds: 2
               successThreshold: 1
               timeoutSeconds: 1
```

The expectation is ingress gateway should have all the configurations including volumeMounts & containerPort.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
The expectation is ingress gateway should have all the configurations including volumeMounts & containerPort.

**Steps to reproduce the bug**
Install istio ingress gateway through istio-operator with the above-mentioned configs.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
* For Istio 1.6.5
* Kubectl 1.18.5

**How was Istio installed?**
Through istio operator. For Istio 1.6.5

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
