### ISSUE TITLE
Istio 1.6.6 with mTLS breaks default Bitnami Postgres deployment

### ISSUE THREAD

**Issue by shosti** [istio/istio#27235]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

The [Bitnami postgresql chart](https://hub.helm.sh/charts/bitnami/postgresql) works fine with istio <=1.6.5, but with 1.6.6 all connections fail with SSL negotiation errors.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

Requests to postgres from pods with mTLS should connect correctly.

**Steps to reproduce the bug**

Apply the following PeerAuthentication config:

```
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
spec:
  mtls:
    mode: STRICT
```

Then, in a namespace with istio-injection enabled:

- `helm install pgtest bitnami/postgresql --version 9.4.1`
- Run an alpine worker pod in the same namespace with `kubectl run -it --rm --restart=Never --image=alpine:3.11 alpine -- sh`
- From the pod, run `apk add postgresql-client && psql -h pgtest-postgresql`

With Istio <= 1.6.5, an authentication prompt happens (which is expected). With Istio >= 1.6.6, there is a message `psql: error: could not connect to server: received invalid response to SSL negotiation:`.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

1.6.6

**How was Istio installed?**

Istio Operator with the following installation configuration:

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio
spec:
  meshConfig:
    accessLogFile: /dev/stdout
  values:
    sidecarInjectorWebhook:
      rewriteAppHTTPProbe: true
    gateways:
      istio-ingressgateway:
        type: LoadBalancer
```

(Possibly related: https://github.com/istio/istio/issues/27042)

**Environment where bug was observed (cloud vendor, OS, etc)**

Self-managed cluster on OpenStack (Ubuntu 20.04, Kubernetes 1.19.0, Cilium for CNI).

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by nirvanatao** [comment]
@shosti  have you defined DR for PostgreSql? something like this:
```
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: dr-postgresql
spec:
  host: "ad-postgresql-headless.kensho2-infra.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```

**Comment by shosti** [comment]
@nirvanatao looks like the problem is still there with a DR. I applied the following:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  namespace: pgtest
  name: pgtest
spec:
  host: pgtest-postgresql.pgtest.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
````

and the error still occurs. (In case it's important: the chart deploys both a ClusterIP and a headless service, and I'm trying to connect to the ClusterIP.)
