### ISSUE TITLE
k8s settings other than overlays are not working on BaseComponentSpec

### ISSUE THREAD

**Issue by galindro** [istio/istio#27240]
**Bug description**
I can't install istio by using a custom IstioOperator CR YAML file which defines k8s settings in BaseComponentSpec. This isn't the exactly same problem reported by https://github.com/istio/istio/issues/24476, because the error message is different this time:

Before the release 1.6.8 (which is the one that introduced the commits from PRs https://github.com/istio/istio/pull/24571 and https://github.com/istio/api/pull/1465), I had this error:
```bash
Error: failed to apply manifests: unknown field "k8s" in v1alpha1.BaseComponentSpec:
```

From 1.6.8 til 1.7.1, I got:
```bash
Error: failed to install manifests: errors occurred during operation
```

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
The k8s overlays should work on BaseComponentSpec

**Steps to reproduce the bug**
1. Create the following file:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  components:
    base:
      enabled: true
      k8s:
        imagePullPolicy: Always
```
2. Try to install istio by executing the following command:
```bash
istioctl install -f myfile.yaml
```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
All istioctl versions starting 1.6.8 til 1.7.1
Helm version: `version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}`

**Environment where bug was observed (cloud vendor, OS, etc)**
Ubuntu 20.04

**Comment by howardjohn** [comment]
cc @ostromart

**Comment by morvencao** [comment]
> base component can only have k8s.overlays, not other K8s settings

Are you intent to set imagePullPolicy to all the components? If yes, you have to set it by k8s settings for each component.

**Comment by galindro** [comment]
> Are you intent to set imagePullPolicy to all the components? If yes, you have to set it by k8s settings for each component.

No @morvencao . That was just an example. I'm trying to set affinity instead.

**Comment by morvencao** [comment]
@galindro Currently base component can only have k8s.overlays, not other K8s settings.

**Comment by galindro** [comment]
@morvencao ah ok, now I got it. Would be nice to have this information clear under https://istio.io/v1.6/docs/reference/config/istio.operator.v1alpha1/#BaseComponentSpec. There, it points out that the whole https://istio.io/v1.6/docs/reference/config/istio.operator.v1alpha1/#KubernetesResourcesSpec can be used, but that's not true.

BTW, is it possible to implement all KubernetesResourcesSpec settings on BaseComponentSpec? Would be a nice feature and would make the configuration standard among all other components that makes use of KubernetesResourcesSpec

**Comment by chaospuppy** [comment]
Is there a reason that only `base.k8s.overlays` can be dictated in the IstioOperator CR?  It would be very helpful if it were possible to do something like the following for testing istio in a resource-constrained environment:

```yaml
apiiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiocontrolplane
  namespace: {{ .Release.Namespace }}
spec:
  profile: {{ .Values.profile }}
  hub: {{ .Values.hub }}
  tag: {{ .Values.tag }}

  components:
    {{- if .Values.base.enabled }}
    base:
      enabled: true
      k8s:
        resources:
          limits:
            cpu: {{ .Values.base.k8s.resources.limits.cpu }}
            memory: {{ .Values.base.k8s.resources.limits.memory }}
          requests:
            cpu: {{ .Values.base.k8s.resources.requests.cpu }}
            memory: {{ .Values.base.k8s.resources.requests.memory }}
```
