### ISSUE TITLE
Cannot get Certificate through istio

### ISSUE THREAD

**Issue by osaffer** [istio/istio#27244]
Hi,

I'm trying to access harbor through HTTPS protocol. My first test was about HTTP, and I did not have any problem.

kubectl version --short
Client Version: v1.19.0
Server Version: v1.19.0

istioctl version
client version: 1.7.0
control plane version: 1.7.0
data plane version: 1.7.0 (5 proxies)

Architecture, I have a Haproxy configured in PassThrough, already used with a nginx ingress controller, and here, no problem with HTTPS.

If I expose the Service as NodePort, 
openssl s_client workernode:32001 will show me the certificate.

When I do an openssl s_client VIP:443 the certificate is not showed.

HAProxy redirect VIP to my workers nodes by using the NodePort.

This is my GW section:

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: harbor-gateway
  namespace: harbor
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*"
    tls:
      mode: SIMPLE
      credentialName: server-certs
      #serverCertificate: /opt/Harbor/server.crt
      #privateKey: /opt/Harbor/serverk.key

I even tried to use mode: PASSTHROUGH

But the certificate is never taken. 

Thanks for your help.

**Comment by howardjohn** [comment]
Ca nyou try running:

```
istioctl pc listener INGERSS_POD
istioctl pc secret
istioctl pc route
```

These will give useful info. If not, get a full config dump and post here: https://github.com/istio/istio/wiki/Troubleshooting-Istio

**Comment by osaffer** [comment]
Hi,

I am sorry for the late reply, 

I think it is more a Haproxy configuration issue. 
HAproxy is configured as passthrough: 
frontend https_istio
   mode http
   option forwardfor
   bind VIP:443 transparent
   default_backend https_istio_back

backend https_istio_back
    mode http
    option log-health-checks
    balance roundrobin
    timeout connect 10s
    timeout server 1m
    server host1 IP1:30602 check fall 3 rise 2 
    server host2 IP2:30602 check fall 3 rise 2
    server host3 IP3:30602 check fall 3 rise 2


 istioctl pc listener istio-ingressgateway-6785d64647-dc55l -n istio-system
ADDRESS PORT  MATCH DESTINATION
0.0.0.0 5432  ALL   Cluster: outbound|5432||postgres-b2g-postgresql-ha-pgpool.b2g.svc.cluster.local
0.0.0.0 8080  ALL   Route: http.80
0.0.0.0 15021 ALL   Inline Route: /healthz/ready*
0.0.0.0 15090 ALL   Inline Route: /stats/prometheus*

istioctl pc secret istio-ingressgateway-6785d64647-dc55l -n istio-system
RESOURCE NAME     TYPE           STATUS     VALID CERT     SERIAL NUMBER                               NOT AFTER                NOT BEFORE
default           Cert Chain     ACTIVE     true           163095856524359579433041700859108685722     2020-09-16T00:55:27Z     2020-09-15T00:55:27Z
ROOTCA            CA             ACTIVE     true           21767561330579796279867322371727544403      2030-08-31T13:09:03Z     2020-09-02T13:09:03Z

istioctl pc route istio-ingressgateway-6785d64647-dc55l -n istio-system
NOTE: This output only contains routes loaded via RDS.
NAME        DOMAINS     MATCH                  VIRTUAL SERVICE
http.80     *           /kiali*                kiali-vs.istio-system
http.80     *           /apache/*              apache-vs.default
            *           /healthz/ready*
            *           /stats/prometheus*

Regards,

**Comment by howardjohn** [comment]
Looks like there are no listeners for 443 at all. Do you have any virtual services defined for the gateway?

If I just apply the GW you had in the original issue, I get the same result. Adding a virtual service adds the listener. See:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: harbor-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*"
    tls:
      mode: SIMPLE
      credentialName: server-certs
      #serverCertificate: /opt/Harbor/server.crt
      #privateKey: /opt/Harbor/serverk.key
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - "*"
  gateways:
  - harbor-gateway
  http:
  - match:
    - uri:
        exact: /productpage
    route:
    - destination:
        host: productpage
        port:
          number: 9080
```

for example
