### ISSUE TITLE
Set reasonable "max_connection_duration" and "drain_timeout" default in istio ingress 

### ISSUE THREAD

**Issue by softcane** [istio/istio#27280]
**Background:**
We are migrating our ingress controller from Nginx to Istio ingress gateway. We are running ingress proxy on NodePort behind ALB in AWS. Kube proxy is running in the IPtable mode and externalTrafficPolicy is configured to Cluster.

During the load test (40K/sec), we figured out that requests are not evenly distributed between the ingress pods and Deployment/Scaling skew the thing even further.

**Problem:**
Kube-proxy has very Poor support for keepalive connections if it runs in the "Iptable" mode. In "Iptable" mode, kube-proxy use a compound probability to pick up a pod IP during routing. Problem is, these rules were invocated only the first time when it opens the TCP connection and since then all subsequent requests are channelled through the same TCP connection (POD).

**_Why it was not an issue in the Ngnix?_**

keepalive_timeout  75s;
keepalive_requests 100;
http://nginx.org/en/docs/http/ngx_http_core_module.html#keepalive_requests

Sets the maximum number of requests that can be served through one keep-alive connection. After the maximum number of requests are made, the connection is closed.
Closing connections periodically is necessary to free per-connection memory allocations. Therefore, using the too high maximum number of requests could result in excessive memory usage and not recommended.
As the istio-proxy works at layer 7, it does request-load-balancing on persistent connections for in/outbound connections between pods in the cluster. Connections are not recycled periodically since the envoy can handle large bursts of requests with a very small footprint.

**Describe the feature request**
Envoy allow you to set "max_connection_duration" and "drain_timeout" which helps to mitigate this issue.
https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/protocol.proto#envoy-api-msg-core-httpprotocoloptions

**Describe alternatives you've considered**
We patched the istio ingress proxy configuration using EnvoyFilter but could be nice if it's supported natively.

[ ] Docs
[ ] Installation
[ ] Networking
[* ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[* ] User Experience
[ ] Developer Infrastructure

**Before/After the patch**
![1](https://user-images.githubusercontent.com/1730359/93028468-791ddb00-f614-11ea-8986-b974ea93f0f1.png)
![3](https://user-images.githubusercontent.com/1730359/93028469-79b67180-f614-11ea-8dd7-5a6467141288.png)

**Comment by ramaraochavali** [comment]
Can you please provide the values that you have tried in your custom Envoy filter?

**Comment by softcane** [comment]
```
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
    patch:
      operation: MERGE
      value:
        config:
          common_http_protocol_options:
            idle_timeout: 300s
            max_connection_duration: 75s

```

**Comment by ramaraochavali** [comment]
is n't `idle_timeout` redundant in your case?  The connection would be drained after `75s` any way - so it will never reach idle_timeout?

**Comment by softcane** [comment]
I would say those are values from my experiment. In our actual config, it's only `max_connection_duration`

**Comment by softcane** [comment]
@ramaraochavali We also notice some 502 on our ALB when traffic rate drops which is very wired.

**Comment by ramaraochavali** [comment]
https://github.com/envoyproxy/envoy/issues/13388 - Relevant discussion here. It seems based on https://github.com/envoyproxy/envoy/issues/13388#issuecomment-704330236 - max_connection_duration by itself does not solve all cases - still there seems to be a race.

Thanks @softcane for initiating that discussion in Envoy

cc: @nrjpoddar @howardjohn

**Comment by howardjohn** [comment]
It seems like there is no reasonable default for `max_connection_duration`. If we did this we would get a ton of issues about gRPC/websocket/other streams closing (we already do...). I would be against adding a default - maybe a configurable option though?

**Comment by howardjohn** [comment]
This is a good issue but lets track in https://github.com/istio/istio/issues/24715 which has substantial overlap. Thanks

**Comment by revandarth** [comment]
Can we set `max_connection_duration` to all downstreams that are configured to a specific upstream service?

The following envoyfilter will terminate the connection to all downstreams that listen at ingressgateway

```
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
    patch:
      operation: MERGE
      value:
        name: envoy.http_connection_manager
        typed_config:
          '@type': type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          common_http_protocol_options:
            idle_timeout: 340s
            max_connection_duration: 600s
```


I'm looking for a way to terminate all downstreams that are configured for a specific service. Lets say I have `helloworld` service, and the following virtual services hello.com, helloworld.com are configured to serve `helloworld` service.

`hello.com/helloworld.com/any(downstream) -- > ingressgateway --> (upstream)service helloworld`  

Here, I want to apply `max_connection_duration: 600s` only for above-mentioned route.

If I understanding correctly, seems we can limit this config to specific downstream say `helloworld.con` using filtermatch with sni as follows

```
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          sni: helloworld.com
          filter:
            name: envoy.http_connection_manager
            
```

but this is for specific downstream instead of all downstreams that are associated with `helloworld` service. wondering if we can limit above config using the upstream service name as same as limiting  using`sni`. 

I would appreciate any insights on this. Thanks
