### ISSUE TITLE
TCP Traffic Shifting not working on Minikube

### ISSUE THREAD

**Issue by dsarosi** [istio/istio#27283]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

TCP Traffic Shifting not working with istio on minikube.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[X] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**

Install minikube v1.13.0.
Start minikube.
Install istio 1.7.1 with profile demo.
Follow instructions https://istio.io/latest/docs/tasks/traffic-management/tcp-traffic-shifting/.
Set `export INGRESS_HOST=$(minikube ip)`
Set `export TCP_INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="tcp")].port}')`

Execute `nc -v $INGRESS_HOST $TCP_INGRESS_PORT`

Result: nc: connect to 172.17.0.2 port 31400 (tcp) failed: Connection refused

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

**How was Istio installed?**

`istioctl install --set profile=demo`

**Environment where bug was observed (cloud vendor, OS, etc)**

Minikube v1.13.0
Istio 1.7.1

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

```
NAMESPACE                       NAME                                        READY   STATUS    RESTARTS   AGE
istio-io-tcp-traffic-shifting   pod/sleep-854565cb79-2h77j                  2/2     Running   0          20m
istio-io-tcp-traffic-shifting   pod/tcp-echo-v1-7dd5c5dcfb-829p9            2/2     Running   0          19m
istio-io-tcp-traffic-shifting   pod/tcp-echo-v2-56cd9b5c4f-nw4jq            2/2     Running   0          19m
istio-system                    pod/istio-egressgateway-6db9994577-zwcsv    1/1     Running   0          21m
istio-system                    pod/istio-ingressgateway-58649bfdf4-6fmkt   1/1     Running   0          21m
istio-system                    pod/istiod-dd4b7db5-hdsl7                   1/1     Running   0          22m
kube-system                     pod/coredns-f9fd979d6-hskmt                 1/1     Running   1          33m
kube-system                     pod/etcd-minikube                           1/1     Running   0          23m
kube-system                     pod/kube-apiserver-minikube                 1/1     Running   0          23m
kube-system                     pod/kube-controller-manager-minikube        1/1     Running   1          33m
kube-system                     pod/kube-proxy-9q7tt                        1/1     Running   1          33m
kube-system                     pod/kube-scheduler-minikube                 1/1     Running   1          33m
kube-system                     pod/storage-provisioner                     1/1     Running   1          33m

NAMESPACE                       NAME                           TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                      AGE
default                         service/kubernetes             ClusterIP      10.96.0.1        <none>        443/TCP                                                                      33m
istio-io-tcp-traffic-shifting   service/sleep                  ClusterIP      10.99.190.187    <none>        80/TCP                                                                       20m
istio-io-tcp-traffic-shifting   service/tcp-echo               ClusterIP      10.110.167.241   <none>        9000/TCP,9001/TCP                                                            19m
istio-system                    service/istio-egressgateway    ClusterIP      10.104.119.86    <none>        80/TCP,443/TCP,15443/TCP                                                     21m
istio-system                    service/istio-ingressgateway   LoadBalancer   10.106.29.176    <pending>     15021:32722/TCP,80:32254/TCP,443:32529/TCP,31400:32303/TCP,15443:30697/TCP   21m
istio-system                    service/istiod                 ClusterIP      10.98.8.251      <none>        15010/TCP,15012/TCP,443/TCP,15014/TCP,853/TCP                                22m
kube-system                     service/kube-dns               ClusterIP      10.96.0.10       <none>        53/UDP,53/TCP,9153/TCP                                                       33m

NAMESPACE     NAME                        DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
kube-system   daemonset.apps/kube-proxy   1         1         1       1            1           kubernetes.io/os=linux   33m

NAMESPACE                       NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
istio-io-tcp-traffic-shifting   deployment.apps/sleep                  1/1     1            1           20m
istio-io-tcp-traffic-shifting   deployment.apps/tcp-echo-v1            1/1     1            1           19m
istio-io-tcp-traffic-shifting   deployment.apps/tcp-echo-v2            1/1     1            1           19m
istio-system                    deployment.apps/istio-egressgateway    1/1     1            1           21m
istio-system                    deployment.apps/istio-ingressgateway   1/1     1            1           21m
istio-system                    deployment.apps/istiod                 1/1     1            1           22m
kube-system                     deployment.apps/coredns                1/1     1            1           33m

NAMESPACE                       NAME                                              DESIRED   CURRENT   READY   AGE
istio-io-tcp-traffic-shifting   replicaset.apps/sleep-854565cb79                  1         1         1       20m
istio-io-tcp-traffic-shifting   replicaset.apps/tcp-echo-v1-7dd5c5dcfb            1         1         1       19m
istio-io-tcp-traffic-shifting   replicaset.apps/tcp-echo-v2-56cd9b5c4f            1         1         1       19m
istio-system                    replicaset.apps/istio-egressgateway-6db9994577    1         1         1       21m
istio-system                    replicaset.apps/istio-ingressgateway-58649bfdf4   1         1         1       21m
istio-system                    replicaset.apps/istiod-dd4b7db5                   1         1         1       22m
kube-system                     replicaset.apps/coredns-f9fd979d6                 1         1         1       33m
```

**Comment by howardjohn** [comment]
Seems the doc is teling you to use the nodePort (`export TCP_INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="tcp")].nodePort}')`) but you use .port. Can you try that instead?

**Comment by howardjohn** [comment]
Or maybe it gives conflicting advice - if so we need to  update the doc

**Comment by avoidik** [comment]
not only `.nodePort`, but also profile settings must be changed to create services with `type: NodePort` attribute

**Comment by dsarosi** [comment]
I tried this on a full cluster and it still didn't work.  I also tried to get this another sample to work with the following configurations and was able to make the following observation.  I'm able to connect to a pod, but I can't send tcp messages through the connection.

https://www.alibabacloud.com/help/doc-detail/112785.htm

```
$ kubectl create namespace tcpecho
$ kubectl label namespace tcpecho
```

**deployment.yaml**
```
$ kubectl apply -f deployment.yaml -n tcpecho
```
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tcp-echo-v1
  labels:
    app: tcp-echo
    system: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp-echo
  template:
    metadata:
      labels:
        app: tcp-echo
        system: example
        version: v1
    spec:
      containers:
        - name: tcp-echo-container
          image: registry-intl.eu-central-1.aliyuncs.com/kmon-net-cn/tcp-echo:0.1
          imagePullPolicy: Always
          env:
            - name: TCP_PORT
              value: "3333"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          ports:
            - name: tcp-echo-port
              containerPort: 3333
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tcp-echo-v2
  labels:
    app: tcp-echo
    system: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp-echo
  template:
    metadata:
      labels:
        app: tcp-echo
        system: example
        version: v2
    spec:
      containers:
        - name: tcp-echo-container
          image: registry-intl.eu-central-1.aliyuncs.com/kmon-net-cn/tcp-echo:0.1
          imagePullPolicy: Always
          env:
            - name: TCP_PORT
              value: "3333"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          ports:
            - name: tcp-echo-port
              containerPort: 3333                
```



**service.yaml**

```
$ kubectl apply -f service.yaml -n tcpecho
```

```
apiVersion: v1
kind: Service
metadata:
  name: "tcp-echo"
  labels:
    app: tcp-echo
    system: example
spec:
  selector:
    app: "tcp-echo"
  ports:
    - protocol: "TCP"
      port: 3333
      targetPort: 3333
  type: ClusterIP
```

**gateway.yaml**
```
$ kubectl apply -f gateway.yaml -n tcpecho
```
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: tcp-echo-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 31400
      name: tcp
      protocol: TCP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: tcp-echo-gateway-v2
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 31401
      name: tcp
      protocol: TCP
    hosts:
    - "*"
```

**destination-rule-all.yaml**
```
$ kubectl apply -f destination-rule-all.yaml -n tcpecho
```
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: tcp-echo
spec:
  host: tcp-echo
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
```

**virtualservice.yaml**
```
$ kubectl apply -f virtualservice.yaml -n tcpecho
```
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: tcp-echo
spec:
  hosts:
  - "*"
  gateways:
  - tcp-echo-gateway
  - tcp-echo-gateway-v2
  tcp:
  - match:
    - port: 31400
      gateways:
        - tcp-echo-gateway
    route:
    - destination:
        host: tcp-echo.tcpecho.svc.cluster.local
        subset: v1
        port:
          number: 3333
  - match:
    - port: 31401
      gateways:
        - tcp-echo-gateway-v2
    route:
    - destination:
        host: tcp-echo.tcpecho.svc.cluster.local
        subset: v2
        port:
          number: 3333        
```

```
$ export TCP_INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="tcp")].port}')
$ export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
$ nc $INGRESS_HOST $TCP_INGRESS_PORT
Welcome, you are connected to node k8s.ffm.staging192168000217wkr.
Running on Pod tcp-echo-v1-bd6855b87-xhm5h.
In namespace tcpecho.
With IP address 172.20.0.124.
Service default.
Test 1
Test 2
```

These messages "Test1", "Test2" do not show up in the logs and the nc connection quits after the second input.  However, when I ssh into the pod and execute it there, the messages appear.  It seems that istio block tcp traffic to the pod.

```
kubectl logs -f tcp-echo-v1-bd6855b87-xhm5h -c tcp-echo-container -n tcpecho | grep Received
```

```
$ kubectl get all -n tcpecho

NAME                               READY   STATUS    RESTARTS   AGE
pod/tcp-echo-v1-bd6855b87-xhm5h    2/2     Running   0          15m
pod/tcp-echo-v2-86d97bfbc6-8ql72   2/2     Running   0          15m

NAME               TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/tcp-echo   ClusterIP   172.21.15.228   <none>        3333/TCP   12m

NAME                          READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/tcp-echo-v1   1/1     1            1           15m
deployment.apps/tcp-echo-v2   1/1     1            1           15m

NAME                                     DESIRED   CURRENT   READY   AGE
replicaset.apps/tcp-echo-v1-bd6855b87    1         1         1       15m
replicaset.apps/tcp-echo-v2-86d97bfbc6   1         1         1       15m
```
