### ISSUE TITLE
virtual service rewrite doing urldecoding

### ISSUE THREAD

**Issue by ceastman-ibm** [istio/istio#27301]
**Bug description**

when a path is rewritten in the virtual service, that path that is forwarded onto the endpoint is urldecoded.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
to have the uri remain unchanged, or at least a feature flag to disable this feature.

**Steps to reproduce the bug**
Setup a virtual service rewrite to an external authority and then pass an url that is encoded, see virtual service yaml at the end of issue

https://hostname.com/api/apim/crn%3Av1%3Astaging%3Apublic%3A

is getting sent to endpoint.com as:

/apim/crn:v1:staging:public:

we need it to remain url encoded

/apim/crn%3Av1%3Astaging%3Apublic%3A

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
istioctl version --remote
client version: 1.7.0
control plane version: 1.6.9-6b4199d7f1330ad476c6c9c0bfab96a0ce67ebd1
data plane version: 1.6.9 (54 proxies), 1.6.8 (547 proxies)

kubectl version --short
Client Version: v1.17.7
Server Version: v1.17.11+IKS

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
IBM Cloud 

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: proxy-istio
spec:
  hosts:
    - hostname.com
  gateways:
  - proxy-istio
  http:
    - match:
        - uri:
            prefix: /api
      rewrite:
        authority: endpoint.com
        uri: " "
      route:
        - destination:
            host: endpoint.com
            port:
              number: 443
```
