### ISSUE TITLE
Way to expose application metrics when using authorization policies and/or mTLS

### ISSUE THREAD

**Issue by Shashankft9** [istio/istio#27328]
**Describe the feature request**
I have been trying to use the Merge Metrics option in Istio through which I can aggregate metrics (app and envoy) on `15020` port of `istio-proxy` container through https://istio.io/latest/docs/ops/integrations/prometheus/#option-1-metrics-merging. The motive behind using this is to simply expose my application metrics whenever I use mTLS or istio authorization policies, but the problem with doing that is, my prometheus instance wont be allowed to access the metrics endpoint of my application container since prometheus is not part of the mesh and hence I went with the metrics merge option. 

And this works, but what I can't get working is - exposing these metrics on prometheus dashboard through a `servicemonitor`. I tried to make use of https://github.com/istio/istio/blob/release-1.7/manifests/charts/istio-telemetry/prometheusOperator/templates/servicemonitors.yaml#L42-L72 but with port `15020` instead of `15090` but this does not work because this port is not mentioned in the `spec` of the `istio-proxy` sidecar added to workload. So to make it work, I have to do a bit of hardcoding which is - I make a service for each mesh workload with port `15020` mentioned, and use the same `servicemonitor` as here https://github.com/istio/istio/blob/release-1.7/manifests/charts/istio-telemetry/prometheusOperator/templates/servicemonitors.yaml#L42-L72 with the port obviously changed and simply `port` instead of `targetPort`, my working configuration:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-stats-monitor-test
  namespace: istio-system
  labels:
    monitoring: istio-proxies
    release: istio-system
spec:
  selector:
    matchExpressions:
      - {key: istio-prometheus-ignore, operator: DoesNotExist}
  namespaceSelector:
    any: true
  jobLabel: envoy-stats-test
  endpoints:
  - path: /stats/prometheus
    port: http-envoy-app
    interval: 10s
    relabelings:
    - action: labeldrop
      regex: "__meta_kubernetes_pod_label_(.+)"
    - sourceLabels: [__meta_kubernetes_namespace]
      action: replace
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_pod_name]
      action: replace
      targetLabel: pod_name

``` 

**Describe alternatives you've considered**
I'd very much prefer to avoid this hardcoding of port `15020` in the service of mesh workload, and do it with one generic servicemonitor, currently there is no documentation in Istio for this. I'd imagine if a user is going to use the merge metrics feature which would happen quite often since no one would want to part ways with application metrics just to get more security. 

I am trying myself to come up with said `servicemonitor` but I'd really appreciate if others can comment on this or if they have some better working solutions/ideas. 

I am using istio v1.6.3
 

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Additional context**
some relevant conversation here: https://istio.slack.com/archives/C382V8Q92/p1599737111109900

**Comment by dntosas** [comment]
posting here for reference, an idea for a possible workaround, not yet checked --> https://github.com/prometheus-operator/prometheus-operator/issues/3354

**Comment by grzesuav** [comment]
I believe exposing named port from `istio-proxy` container should be the way

**Comment by dntosas** [comment]
managed to do proper scraping without changing anything but `serviceMonitor` with this:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-stats-service
  namespace: {{ .Release.Namespace }}
  labels:
    monitoring: istio
    release: {{ .Release.Name }}
spec:
  selector:
    matchExpressions:
      - {key: istio-prometheus-ignore, operator: DoesNotExist}
  namespaceSelector:
    any: true
  jobLabel: envoy-stats-service
  endpoints:
  - path: '/stats/prometheus'
    interval: 15s
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_container_name]
      action: keep
      regex: istio-proxy
    - sourceLabels: [__meta_kubernetes_namespace]
      action: replace
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_pod_name]
      action: replace
      targetLabel: pod_name
```

removed `targetPort` and filter `pod_container_name=istio-proxy` will do the job

**Comment by Shashankft9** [comment]
@dntosas how do make sure in this `servicemonitor` that the scraping is done from port `15020` instead of `15090`?

**Comment by dntosas** [comment]
@Shashankft9 our goal is to scrape both `business/application` + `istio-proxy` metrics right?

What we observed is that upon merging all metrics to port `15020`, we didn't see both metrics exposed but only the Istio ones.

So, we disabled merging and we scrape business metrics from application port (lets say 80) and scrape istio-proxy from 15090. What this serviceMonitor does is simply doesn't need to do any extra config work on your current environment.

**Comment by Shashankft9** [comment]
@dntosas I think there is some misunderstanding here - merge works for me, I can see the `application` metrics and the `istio-proxy` metrics on the port `15020` locally, its just that I am unable to expose this port on prometheus. If you are getting this error:

> What we observed is that upon merging all metrics to port 15020, we didn't see both metrics exposed but only the Istio ones.

this is probably because you still have the shipped istio servicemonitor that scrapes metrics from `15090` port, once you remove that you wont be able to see the `istio-proxy` metrics as well. 

> So, we disabled merging and we scrape business metrics from application port (lets say 80) and scrape istio-proxy from 15090.

This issue is when mTLS is on and you have applied some istio policy, which will block prometheus from scraping metrics from the port `80` (since prometheus is not part of the mesh) or a local curl to its `<pod-ip>:80`, this is why we wanted to use merging feature from the start, because we can curl `<pod-ip:15020>` even when mTLS and authorization policies are in place.

I also think that your current servicemonitor is basically scrapping the metrics from 15090, which is already shipped by istio. 

Please correct me if I am adding further confusion here.

**Comment by dntosas** [comment]
@Shashankft9 my misunderstanding ^^ and yes, you are correct, we are scraping proxy metrics through `15090` port ^^ 

our problem was different so i am responsible for adding confusion in here, and sorry for that :)

**Comment by douglas-reid** [comment]
I had to get something like working today. Here's what I came up with:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: envoy-stats-monitor-pod
  labels:
    monitoring: istio-proxies
    release: istio
spec:
  selector:
    matchExpressions:
    - {key: istio-prometheus-ignore, operator: DoesNotExist}
  namespaceSelector:
    any: true
  jobLabel: envoy-stats
  podMetricsEndpoints:
  - path: /stats/prometheus
    interval: 15s
    relabelings:
    - action: keep
      sourceLabels: [__meta_kubernetes_pod_container_name]
      regex: "istio-proxy"
    - action: keep
      sourceLabels: [__meta_kubernetes_pod_annotationpresent_prometheus_io_scrape]
    - sourceLabels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      targetLabel: __address__
    - action: labeldrop
      regex: "__meta_kubernetes_pod_label_(.+)"
    - sourceLabels: [__meta_kubernetes_namespace]
      action: replace
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_pod_name]
      action: replace
      targetLabel: pod_name
```

The only thing hard-coded is the path, but honestly, I think that could be easily replaced in the relabelings.  I used a `PodMonitor`, but I think that should be OK.

Thoughts?  If this looks acceptable, and works for others, I'll update the sample config to match.

**Comment by Shashankft9** [comment]
As I mentioned in the slack thread, I believe this would also pick up additional ports of pods for example `cluster-local-gateway` and `istio-ingressgateway` as the target endpoints on prometheus dashbaord, although that would not necessarily effect anything but it would show these additional ports as DOWN on the prometheus dashboard. (it would be nice if anyone can test this and confirm) 

A way to get around this would be, to modify this `PodMonitor` to look like this: 
```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: envoy-stats-monitor-pod
  namespace: monitoring
  labels:
    monitoring: istio-proxies
    release: istio
spec:
  selector:
    matchLabels:
      istio.io/rev: default
    matchExpressions:
    - {key: istio-prometheus-ignore, operator: DoesNotExist}
  namespaceSelector:
    any: true
  jobLabel: envoy-stats
  podMetricsEndpoints:
  - path: /stats/prometheus
    interval: 15s
    relabelings:
    - action: keep
      sourceLabels: [__meta_kubernetes_pod_container_name]
      regex: "istio-proxy"
    - action: keep
      sourceLabels: [__meta_kubernetes_pod_annotationpresent_prometheus_io_scrape]
    - sourceLabels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      targetLabel: __address__
    - action: labeldrop
      regex: "__meta_kubernetes_pod_label_(.+)"
    - sourceLabels: [__meta_kubernetes_namespace]
      action: replace
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_pod_name]
      action: replace
      targetLabel: pod_name
```
This would only pick up pods running in the mesh (basically the pods with istio-proxy as sidecar, if merge metrics is on - port `150201` will be selected for scraping, otherwise port `15090` will be selected), because of the additional `matchLabels` added.

Then additionally apply a servicemonitor for `istio-ingressgateway` and `cluster-local-gateway` metrics. Although this does add components, it would keep the targets page clean on prometheus dashboard.
