### ISSUE TITLE
can't trace x-request-id by using DestinationRule for HTTPS

### ISSUE THREAD

**Issue by bjwyun** [istio/istio#27338]
ENV:  OCP 4.3 + istio 1.48
USING ingressgate as:
```
client sends HTTPS -> TLS termination by the ingress gateway -> HTTP -> HTTP routing by the VirtualService -> TLS origination by the DestinationRule sends HTTPS -> destination service
```

the request will be  first go to  ``nginx`` service then nginx service will redirect the request to different pod in the same namespace by using ``HTTPS``.

and from jeager we only can get the request about istio-ingressgateway, can't get more detail info about which service this request have been redirect to.

![image](https://user-images.githubusercontent.com/31024715/93284535-7d5d1a80-f805-11ea-977a-8e957f87a42a.png)

we hope to get the network like this:
![image](https://user-images.githubusercontent.com/31024715/93285043-90bcb580-f806-11ea-8d18-e2c3c343edab.png)

**Comment by bjwyun** [comment]
here is the  DestinationRule
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: nginx-svc
spec:
  host: nginx-svc
  subsets:
  - name: nginx
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: MUTUAL
          clientCertificate: /etc/istio/ingressgateway-certs/tls.crt
          privateKey: /etc/istio/ingressgateway-certs/tls.key
          caCertificates: /etc/istio/ingressgateway-certs/tls.crt
          sni: nginx-svc
```

**Comment by bjwyun** [comment]
and in istio-proxy logs we found we've lost ``x-request-id``

```
[2020-09-16T09:16:01.406Z] "- - -" 0 - "-" "-" 560 2044 29 - "-" "-" "-" "-" "127.0.0.1:8443" inbound|443|nginx-https-port|nginx-svc.cpd.svc.cluster.local 127.0.0.1:44290 10.254.1.77:8443 10.254.0.1:40358 - -
```

**Comment by bianpengyuan** [comment]
Does the application pod populated trace context: https://istio.io/latest/docs/tasks/observability/distributed-tracing/overview/#trace-context-propagation?

Also does application sidecar terminate TLS or application itself terminate it? If application terminates TLS, then it is expected that trace won't be generated, because TLS encrypted request is opaque to proxy and thus it cannot instrument trace span based on that.

**Comment by bjwyun** [comment]
@bianpengyuan  in My ENV istio-ingressgate push request to  nginx service. and in nginx log we can see all the header metioned in  https://istio.io/latest/docs/tasks/observability/distributed-tracing/overview/#trace-context-propagation
```
host: a.apps.dmcbvt.os.fyre.ibm.com
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
content-type: application/json
accept: */*
sec-fetch-site: same-origin
sec-fetch-mode: cors
sec-fetch-dest: empty
referer: https://a.apps.dmcbvt.os.fyre.ibm.com/zen/
accept-encoding: gzip, deflate, br
accept-language: en,zh;q=0.9,en-US;q=0.8
x-forwarded-for: 10.254.16.1
x-forwarded-proto: https
x-envoy-internal: true
x-request-id: 9e88cbbe-282a-957e-a546-30d6c311117f
x-envoy-decorator-operation: ibm-nginx-svc.cpd.svc.cluster.local:443/*
x-istio-attributes: Ck4KCnNvdXJjZS51aWQSQBI+a3ViZXJuZXRlczovL2lzdGlvLWluZ3Jlc3NnYXRld2F5LTZiNWJkZGY5NS1jc3hiMi5pc3Rpby1zeXN0ZW0KQQoYZGVzdGluYXRpb24uc2VydmljZS5ob3N0EiUSI2libS1uZ2lueC1zdmMuY3BkLnN2Yy5jbHVzdGVyLmxvY2FsCj8KF2Rlc3RpbmF0aW9uLnNlcnZpY2UudWlkEiQSImlzdGlvOi8vY3BkL3NlcnZpY2VzL2libS1uZ2lueC1zdmMKKwoYZGVzdGluYXRpb24uc2VydmljZS5uYW1lEg8SDWlibS1uZ2lueC1zdmMKJgodZGVzdGluYXRpb24uc2VydmljZS5uYW1lc3BhY2USBRIDY3Bk
x-b3-traceid: 506693dcdd2987ed0ae5fd8a6deee5da
x-b3-spanid: 0ae5fd8a6deee5da
x-b3-sampled: 1
```
and I think is  sidercar terminate the TLS, here's all the  configuration I've done in my namespace

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*.apps.dmcbvt.os.fyre.ibm.com"
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-nginx-through-ingress-gateway
spec:
  hosts:
  - "*.apps.dmcbvt.os.fyre.ibm.com"
  gateways:
  - istio-egressgateway
  http:
  - match:
    - port: 443
    route:
    - destination:
        host: nginx-svc
        subset: nginx
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: nginx-svc
spec:
  host: nginx-svc
  subsets:
  - name: nginx
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: MUTUAL
          clientCertificate: /etc/istio/ingressgateway-certs/tls.crt
          privateKey: /etc/istio/ingressgateway-certs/tls.key
          caCertificates: /etc/istio/ingressgateway-certs/tls.crt
          sni: nginx-svc

```
