### ISSUE TITLE
Multiple Gateways - Routing problem 404

### ISSUE THREAD

**Issue by luiof** [istio/istio#27331]
Hi team!
I defined two gateway on the same selector `istio: ingressgateway` with different hosts and two virtualservice on these hosts (two urls for each virtualservice). Each host is defined without the wildcard, they are in the form of www.somesite.somedomain .
To show the problem, I use an example's set of URL (I can't show the url directly):

-  URL_1 in the gateway X with the cert1
-  URL_2 in the gateway X with the cert2
-  URL_3 in the gateway Y with the cert1
-  URL_4 in the gateway Y with the cert2

There is a strange behavior. If I call the first host URL_1 I get a 404 NR error:

```
istio-proxy "GET /v2/health HTTP/2" 404 NR "-" "-" 0 0 0 - "10.45.105.84" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:80.0) Gecko/20100101 Firefox/80.0" "40b11b93-f081-4edf-8786-69d320fb3b9f" "URL_1" "-" - - 172.30.130.167:8443 10.45.105.84:10712 URL_3 -
```

It seems that there is a wrong match routing; does the url above match on the wrong url ?
Is it allowed to use multiple gateway on the same selector istio ingressgateway ?

The others two endpoints URL_2 and URL_4 works fine without problem. It is strange.
I also noticed that if I curl to each host (URL_1 and URL_3), than it works without problems. If I use a browser (firefox, safari or chrome also) than only one of them works, the other one returns a 404 code error. I was thinking about a cookie problem but we don't use them, so it's strange.

I ask since if I use only one gateway with all the following hosts, it works without problem (I need to split it into two gateways due to the microservice installation with helm).

The configuration is the following:

- Gateway 1:
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-gateway-X
  namespace: mynamespace
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - URL_1
    port:
      name: https-url-1-label
      number: 443
      protocol: HTTPS
    tls:
      credentialName: cert1
      mode: SIMPLE
  - hosts:
    - URL_2
    port:
      name: https-url-2-label
      number: 443
      protocol: HTTPS
    tls:
      credentialName: cert2
      mode: SIMPLE
```
with these virtualservice:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: istio-virtual-service-set-1
  namespace: mynamespace
spec:
  gateways:
  - istio-gateway-X
  hosts:
  - URL_1
  - URL_2
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: service-set-1
        port:
          number: 3000
    timeout: 600s
```

While the second gateway:
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-gateway-Y
  namespace: mynamespace
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - URL_3
    port:
      name: https-url-3-label
      number: 443
      protocol: HTTPS
    tls:
      credentialName: cert1
      mode: SIMPLE
  - hosts:
    - URL_4
    port:
      name: https-url-4-label
      number: 443
      protocol: HTTPS
    tls:
      credentialName: cert2
      mode: SIMPLE
```
with the virtualservice:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: istio-virtual-service-set-2
  namespace: mynamespace
spec:
  gateways:
  - istio-gateway-Y
  hosts:
  - URL_3
  - URL_4
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: service-set-2
        port:
          number: 3000
    timeout: 600s
```

**Comment by luiof** [comment]
I tried the SNI routing also, without success. Any ideas?

**Comment by linsun** [comment]
can you supply your plan with SNI routing?  Also are you using istio 1.7?

please also run istioctl analyzer on your yaml as well.

**Comment by luiof** [comment]
We are using Managed Istio 1.7.1.
This is the virtual service used:

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: istio-virtual-service-set-2
  namespace: mynamespace
spec:
  gateways:
  - istio-gateway-Y
  hosts:
  - URL_3
  http:
  - match:
     - port: 443
        sniHosts:
        - URL_3
    route:
    - destination:
        host: service-set-2
        port:
          number: 3000
  - match:
     - port: 443
        sniHosts:
        - URL_4
    route:
    - destination:
        host: service-set-2
        port:
          number: 3000
```

The analyzer shows only some warning:
```
istioctl analyze -n mynamespace
Warn [IST0002] (CustomResourceDefinition clusterrbacconfigs.rbac.istio.io) Deprecated: Custom resource type rbac.istio.io ClusterRbacConfig is removed
Warn [IST0002] (CustomResourceDefinition rbacconfigs.rbac.istio.io) Deprecated: Custom resource type rbac.istio.io RbacConfig is removed
Warn [IST0002] (CustomResourceDefinition servicerolebindings.rbac.istio.io) Deprecated: Custom resource type rbac.istio.io ServiceRoleBinding is removed
Warn [IST0002] (CustomResourceDefinition serviceroles.rbac.istio.io) Deprecated: Custom resource type rbac.istio.io ServiceRole is removed
```

Is it necessary to use PASSTHROUGH mode in the gateway for SNI routing?

**Comment by linsun** [comment]
From our [doc](https://github.com/istio/api/blob/482a96e7a99dc7bb2ff864e336b9f1b596c2d34c/networking/v1beta1/virtual_service.proto#L805), SNI routing configured via sniHosts in virtual service assumes passthrough is used in the corresponding gateway.  @howardjohn from networking WG kindly confirmed it for me as well.

I think this explains why your routes don't work with SNI.

**Comment by howardjohn** [comment]
I was unable to reproduce:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-gateway-x
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - u1.1.2.3.4.nip.io
    port:
      name: https-url-1-label
      number: 443
      protocol: HTTPS
    tls:
      credentialName: sds-credential
      mode: SIMPLE
  - hosts:
    - u2.1.2.3.4.nip.io
    port:
      name: https-url-2-label
      number: 443
      protocol: HTTPS
    tls:
      credentialName: sds-credential-alt
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: istio-virtual-service-set-1
spec:
  gateways:
  - istio-gateway-x
  hosts:
  - u1.1.2.3.4.nip.io
  - u2.1.2.3.4.nip.io
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: echo
        port:
          number: 8080
    timeout: 600s
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-gateway-y
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - u3.1.2.3.4.nip.io
    port:
      name: https-url-3-label
      number: 443
      protocol: HTTPS
    tls:
      credentialName: sds-credential
      mode: SIMPLE
  - hosts:
    - u4.1.2.3.4.nip.io
    port:
      name: https-url-4-label
      number: 443
      protocol: HTTPS
    tls:
      credentialName: sds-credential-alt
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: istio-virtual-service-set-2
spec:
  gateways:
  - istio-gateway-y
  hosts:
  - u3.1.2.3.4.nip.io
  - u4.1.2.3.4.nip.io
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: httpbin
        port:
          number: 80
    timeout: 600s
```

Replace 1.2.3.4 with your gateway IP.

Then running `for i in {1..4}; do curl https://u$i.1.2.3.4.nip.io/get -ks; done` shows all successful

**Comment by howardjohn** [comment]
you should post a config dump: https://github.com/istio/istio/wiki/Troubleshooting-Istio

**Comment by linsun** [comment]
I noticed John didn't use a custom ns like your example and I was half way through running the example anyway...but I can't recreate this either.   It works pretty nicely for me.

Here is my plans:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: helloworld-gateway
  namespace: hello
spec:
  selector:
    istio: ingressgateway # use istio default ingress
  servers:
  - port:
      number: 443
      name: https-1
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: mycluster-wdc06-b-x1    
    hosts:
    - "hello.mycluster-wdc06-b-x1.us-east.containers.appdomain.cloud"
  - port:
      number: 443
      name: https-2
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: mycluster-wdc06-b-x0    
    hosts:
    - "hello.mycluster-wdc06-b-x0.us-east.containers.appdomain.cloud"
```

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helloworld
  namespace: hello
spec:
  hosts:
  - "hello.mycluster-wdc06-b-x1.us-east.containers.appdomain.cloud"
  - "hello.mycluster-wdc06-b-x0.us-east.containers.appdomain.cloud"
  gateways:
  - helloworld-gateway
  http:
  - match:
    - uri:
        exact: /hello
    route:
    - destination:
        host: helloworld.hello.svc.cluster.local
        port:
          number: 5000
```

```
$ curl https://hello.mycluster-wdc06-b-x1.us-east.containers.appdomain.cloud/hello
Hello version: v2, instance: helloworld-v2-5d5d5bccf6-l956v
(⎈ |mycluster-wdc06-b3c.4x16/bs76p72w0qc3sa93oti0:default)
~/go/src/istio.io/testingdir ⌚ 16:28:29
$ curl https://hello.mycluster-wdc06-b-x0.us-east.containers.appdomain.cloud/hello
Hello version: v1, instance: helloworld-v1-6f5c87b877-ftz65
```

For your NR error, make sure you are using fully qualified host name as destination host like my example.  I have ran into that when using custom namespace.  If still not work, pls collect the all info from John's https://github.com/istio/istio/issues/27331#issuecomment-697927365.
