### ISSUE TITLE
ingressgate no traceid

### ISSUE THREAD

**Issue by hmthoo** [istio/istio#27348]
**questions**
Now,  istio has been connect local zipkin， bookinfo app has traceid， but  ingressgate reponse headers no traceid. The official website documentation does not seem to have this description. I want add zipkin traceid in ingressgateway reponse, what should i do ? Thank you!

**version**
```
client version: 1.6.9
control plane version: 1.6.9
data plane version: 1.6.9 (13 proxies)
```

**install command**
```
istioctl manifest apply --set profile=demo \
--set components.telemetry.enabled=true \
--set components.policy.enabled=true \
--set components.citadel.enabled=true \
--set addonComponents.tracing.enabled=true \
--set tracing.ingress.enabled=true
--set addonComponents.kiali.enabled=true \
--set addonComponents.grafana.enabled=true \
--set values.gateways.istio-ingressgateway.type=NodePort \
--set values.global.tracer.zipkin.address="192.168.100.10:9411" \
--set values.global.proxy.accessLogFile="/dev/stdout"
```

**screenshot**
![image](https://user-images.githubusercontent.com/42607426/93317274-db0e5880-f83f-11ea-82d9-6277559580ac.png)
![image](https://user-images.githubusercontent.com/42607426/93317365-f6796380-f83f-11ea-8528-e32fd7115b2a.png)

**Comment by douglas-reid** [comment]
Can your ingressgateway reach the zipkin service?

I notice:

```
--set values.gateways.istio-ingressgateway.type=NodePort \
--set values.global.tracer.zipkin.address="192.168.100.10:9411"
```

Do you have error logs in the ingressgateway pod that mention Zipkin?

**Comment by hmthoo** [comment]
@douglas-reid  no error logs in ingressateway with zipkin. Now , I'am used set header in virtualservice to reponse traceid.
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
...
  http:
  - headers:
      response:
        set:
          x-b3-spanid: '"%REQ(x-b3-spanid)%"'
          x-b3-traceid: '"%REQ(x-b3-traceid)%"'
          x-request-id: '"%REQ(x-request-id)%"'
    route:
    - destination:
        host: test
        subset: v1
```
But this way is stupid and needs to be configured in multiple virtualservice. I want to know if there is any other easier way. 
Thank you!
