### ISSUE TITLE
Istio Ingress Gateway's public AWS Classic load balancer fails health checks 

### ISSUE THREAD

**Issue by artyom-gatalsky** [istio/istio#27356]
**Bug description**

I have multiple Istio Ingress Gateways in the cluster.
In one namespace I have 2 Istio Ingress Gateways: 1 with public AWS Classic LoadBalancer and 1 with private AWS Classic LoadBalancer.
Both load balancers have default TCP healthchecks.
For some reason, _public_ AWS Classic LoadBalancer periodically fails healthcheck to TCP port of kubernetes nodes.
No errors in istiod or in the pod that is standing behind the service of type LoadBalancer.
At the same time, _private_ AWS Classic LoadBalancer has no issues with the same healthcheck (except the port number).
The issue can be "fixed" by making any change that will make a call to AWS in service with type LoadBalancer and used by public Istio Ingress Gateway.

So it seems to me like it hangs somewhere until I do any change in istio resources that will make an API call to AWS.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
```
istioctl version --remote
client version: 1.6.4
control plane version: 1.6.4
data plane version: 1.6.4 (73 proxies)
```
```
kubectl version --short
Client Version: v1.19.0
Server Version: v1.15.11-eks-065dce
```

**How was Istio installed?**
operator

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS

Configuration of LoadBalancer:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: shop-istio-gateway-public
    meta.helm.sh/release-namespace: shop-spa-develop
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-security-groups: sg-xxx,sg-yyy
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-west-1:xxx:certificate/yyy
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
  labels:
    app: shop-spa-develop-public-istio-ingressgateway
    app.kubernetes.io/managed-by: Helm
    istio: shop-spa-develop-public-ingressgateway
    release: istio
  name: shop-spa-develop-public-istio-ingressgateway
  namespace: shop-spa-develop
spec:
  clusterIP: 10.100.137.70
  externalTrafficPolicy: Cluster
  ports:
  - name: status-port
    nodePort: 32538
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: http2
    nodePort: 31686
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 31547
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: tls
    nodePort: 31769
    port: 15443
    protocol: TCP
    targetPort: 15443
  selector:
    app: shop-spa-develop-public-istio-ingressgateway
    istio: shop-spa-develop-public-ingressgateway
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: xxx.eu-west-1.elb.amazonaws.com
```

Configuration of Gateway for this loadbalancer:
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  annotations:
    externaldns/zone: public
    meta.helm.sh/release-name: shop-istio-gateway-public
    meta.helm.sh/release-namespace: shop-spa-develop
  labels:
    app.kubernetes.io/managed-by: Helm
  name: shop-spa-develop-public-gateway
  namespace: shop-spa-develop
spec:
  selector:
    istio: shop-spa-develop-public-ingressgateway
  servers:
  - hosts:
    - xxx.yy
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - xxx.yy
    port:
      name: https-443
      number: 443
      protocol: HTTP
```
