### ISSUE TITLE
Istioctl x uninstall --filename does not remove ingressGateways

### ISSUE THREAD

**Issue by nak3** [istio/istio#27350]
**Bug description**

- Istioctl x uninstall --filename does not remove ingress-gateways.
- Please refer to the `steps to reproduce the bug` below.

[X] Installation

**Expected behavior**

- Ingress gateways are removed.

**Steps to reproduce the bug**

#### 1. Install Istio with the following operator manifest

```
cat <<EOF > istio-ci-no-mesh.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      useMCP: false

  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
      - name: cluster-local-gateway
        enabled: true
        label:
          istio: cluster-local-gateway
          app: cluster-local-gateway
        k8s:
          service:
            type: ClusterIP
            ports:
            - port: 15020
              name: status-port
            - port: 80
              targetPort: 8080
              name: http2
            - port: 443
              targetPort: 8443
              name: https
EOF
```

```
istioctl install -f istio-ci-no-mesh.yaml
```

Now, Istio installation works fine.

```sh
$ kubectl get pod -n istio-system
NAME                                     READY   STATUS    RESTARTS   AGE
cluster-local-gateway-55f95697ff-s2wrx   1/1     Running   0          19s
istio-ingressgateway-57c4698556-gw2xh    1/1     Running   0          18s
istiod-84b8878668-s9js7                  1/1     Running   0          26s
```

#### 2. Uninstall istio

```sh
$ istioctl x uninstall -f istio-ci-no-mesh.yaml
Detected that your cluster does not support third party JWT authentication. Falling back to less secure first party JWT. See https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens for details.
  Removed HorizontalPodAutoscaler:istio-system:istiod.
  Removed ConfigMap:istio-system:istio.
  Removed Deployment:istio-system:istiod.
  Removed ConfigMap:istio-system:istio-sidecar-injector.
  Removed MutatingWebhookConfiguration::istio-sidecar-injector.
  Removed PodDisruptionBudget:istio-system:istiod.
  Removed Service:istio-system:istiod.
  Removed EnvoyFilter:istio-system:metadata-exchange-1.6.
  Removed EnvoyFilter:istio-system:tcp-metadata-exchange-1.6.
  Removed EnvoyFilter:istio-system:stats-filter-1.6.
  Removed EnvoyFilter:istio-system:tcp-stats-filter-1.6.
  Removed EnvoyFilter:istio-system:metadata-exchange-1.7.
  Removed EnvoyFilter:istio-system:tcp-metadata-exchange-1.7.
  Removed EnvoyFilter:istio-system:stats-filter-1.7.
  Removed EnvoyFilter:istio-system:tcp-stats-filter-1.7.
✔ Uninstall complete
```

#### 3. Verify uninstallation (still ingressGateways are running)

```
$ kubectl get pod -n istio-system 
NAME                                     READY   STATUS    RESTARTS   AGE
cluster-local-gateway-55f95697ff-s2wrx   1/1     Running   0          38s
istio-ingressgateway-57c4698556-gw2xh    1/1     Running   0          37s
```

**Version

- Istio 1.7.1
- Istio (Build on master branch)
