### ISSUE TITLE
Support partial headless apps by build two different outbound clusters.

### ISSUE THREAD

**Issue by incfly** [istio/istio#27376]
**Describe the feature request**
Comments from the thread, https://github.com/istio/istio/pull/27105#discussion_r487629499

We can further enhance usability for auto mTLS w.r.t headless services. They would work as if normal HTTP/TCP service, even only partial workloads have sidecar.

The idea is that we build two outbound cluster, one have mtls configured, one does not. We already build one outbound listener per pod IP for headless/statefulset applications. Their tcp_proxy filter config is updated to point to one of these clusters, depending on that pod has mtls ready label or not, plus the serivce has mTLS PeerAuthentication Policy configured. 

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X ] Security
[ ] Test and Release
[X ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
This would be useful beyond headless I think. For example, with standard service we cannot tell:
```yaml
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: v1
spec:
  selector:
    matchLabels:
      version: v1
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: v2
spec:
  selector:
    matchLabels:
      version: v2
  mtls:
    mode: DISABLE
```

to not send mTLS to both.

Maybe its a different problem, but its a similar issue at least
