### ISSUE TITLE
Wrong source_principal field stored in Telemetry

### ISSUE THREAD

**Issue by lucasponce** [istio/istio#27388]
We have noticed that workloads without serviceAccount reports an incorrect source_principal in the telemetry metrics.

This impacts Kiali as AuthorizationPolicies can be generated from principal reported by telemetry info.

How to reproduce with bookinfo:
```
# Install bookinfo
kubectl label namespace default istio-injection=enabled
kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml

# Remove bookinfo-review-v2.yaml
kubectl delete -f samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml

# Notice that bookinfo-reviews-v2.yaml doesn't have a ServiceAccount defined so expectation is that when re-deploy bookinfo-reviews-v2.yaml it gets the default SA

# Reinstall bookinfo-review-v2.yaml
kubectl apply -f samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml

# Generate traffic
```

bookinfo-review-v2.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v2
  labels:
    app: reviews
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v2
  template:
    metadata:
      labels:
        app: reviews
        version: v2
    spec:
      containers:
      - name: reviews
        image: docker.io/istio/examples-bookinfo-reviews-v2:1.16.2
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}
```

Metrics from ratings where source is reviews v2 where "source_principal" is wrong:
![image](https://user-images.githubusercontent.com/1662329/93460270-3cd3ce80-f8e3-11ea-974b-81e251d6e5e1.png)

It is expected to get "default" SA for workloads not using an explicit ServiceAccount.
