### ISSUE TITLE
Installation issue for Istio ingress gateway installation with different readiness probe through Istio operator.

### ISSUE THREAD

**Issue by abhioncbr** [istio/istio#27398]
**Bug description**
I am trying to install the istio ingress gateway with a different readiness probe than the usual one. Following below is my istio-operator manifest
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  profile: demo
  components:
    egressGateways:
      - name: istio-egressgateway
        enabled: true
    ingressGateways:
      - name: istio-ingressgateway
        enabled: false
      - name: internal-ingressgateway
        enabled: true
        label:
          istio: internal-ingressgateway
          app: internal-istio-ingressgateway
        k8s:
          readinessProbe:
            failureThreshold: 20
            exec:
              command:
              - "curl"
              - "-f"
              - "127.0.0.1:15021/healthz/ready"
            initialDelaySeconds: 1
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 1
          serviceAnnotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"      
    cni:
      enabled: true
      namespace: kube-system 
  hub: aa.azurecr.io/vendor/istio
  values:
    prometheus:
      hub: aa.azurecr.io/vendor
    kiali:
      dashboard:
        auth:
          strategy: token
      createDemoSecret: false  
      hub: aa.azurecr.io/vendor
    tracing: 
      jaeger:
        hub: aa.azurecr.io/vendor/jaegertracing 
    grafana:
      image:
        repository: aa.azurecr.io/vendor/grafana
    cni:
      excludeNamespaces:
        - istio-system
        - kube-system
      logLevel: info 
      psp_cluster_role: istio-cni-psp
    gateways:
      istio-egressgateway:
        runAsRoot: false
      istio-ingressgateway:
        name: internal-ingressgateway
        ports:
            - port: 15021
              targetPort: 15021
              name: status-port
            - port: 80
              targetPort: 8080
              name: http2
            - port: 443
              targetPort: 8443
              name: https
            - port: 15443
              targetPort: 15443
              name: tls
            - port: 8080
              targetPort: 8080
              name: azappgw 
        runAsRoot: false
```

while applying through istio-operator following logs, I noticed
```bash
2020-09-17T18:57:56.327813Z    error  installer  Deployment.apps "internal-ingressgateway" is invalid: spec.template.spec.containers[0].readinessProbe.httpGet: Forbidden: may not specify more than 1 handler type
- Pruning removed resources
✘ Ingress gateways encountered an error: Deployment.apps "internal-ingressgateway" is invalid: spec.template.spec.containers[0].readinessProbe.httpGet: Forbidden: may not specify more than 1 handler type
```

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
**Istio-operator should apply the readiness probe as it is without merging.**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
