### ISSUE TITLE
Path parameters allow bypassing of AuthorizationPolicy rules

### ISSUE THREAD

**Issue by rolandkool** [istio/istio#27409]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
Envoy does not seem to be doing proper path normalization when path parameters are added to the path.
This allows for bypassing authorization policy rules.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
Path parameters shouldn't make it possible to bypass policies.

**Steps to reproduce the bug**
AuthorizationPolicy:
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: policyname
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        methods:
        - GET
        paths:
        - /
        - /v1/*
        - /internal/path1
        - /internal/path1/path2
        - /internal/path1/path3
        - /internal/path1/path4
    when:
    - key: request.auth.claims[groups]
      values:
      - groupname
```

When accessing path `https://some.site.name/v1/../internal/path1/path5` access is denied
When accessing path `https://some.site.name/v1/..;/internal/path1/path5` or `https://some.site.name/v1/..;path_param=value/internal/path1/path5` access is allowed

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
1.7.1

**How was Istio installed?**
istioctl install

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE 1.16

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
