### ISSUE TITLE
The ratings service is currently unavailable while integrated the bookinfo demo with a virtual machine

### ISSUE THREAD

**Issue by rootsongjc** [istio/istio#27412]
**Bug description**

[x] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

I followed both articles and installed Istio 1.7.1 in GKE and booted up a virtual machine to install Istio.

- https://istio.io/latest/docs/setup/platform-setup/gke/
- https://istio.io/latest/docs/examples/bookinfo/
- https://istio.io/latest/docs/examples/virtual-machines/single-network/
- https://istio.io/latest/docs/examples/virtual-machines/bookinfo/

The `ratings` service is currently unavailable, as shown below.

![image](https://user-images.githubusercontent.com/3328185/93591765-8d325580-f9e3-11ea-88eb-eb0a921bfbb6.png)

The deployment architecture is shown below.

![image](https://user-images.githubusercontent.com/3328185/93592066-16e22300-f9e4-11ea-947f-a7d590a63b6d.png)

**Expected behavior**

The `ratings` service is available and the stars show on the product page.

**Steps to reproduce the bug**

**Version**

Istio

- client version: 1.7.1
- control plane version: 1.7.1
- data plane version: 1.7.1 (8 proxies), 1.7.0 (1 proxies)

Kubernetes

- Client Version: v1.19.0
- Server Version: v1.16.13-gke.400

**How was Istio installed?**

Follow this doc: https://istio.io/latest/docs/setup/platform-setup/gke/

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE

**`ratings-mysql-vm` pod log dump**

```
at Server.emit (events.js:315:20) {
--
at Server.handleRequest (/opt/microservices/ratings.js:248:16)
at HttpDispatcher.dispatch (/opt/microservices/node_modules/httpdispatcher/httpdispatcher.js:74:14)
at HttpDispatcher.doDispatch (/opt/microservices/node_modules/httpdispatcher/httpdispatcher.js:58:13)
at HttpChain.next (/opt/microservices/node_modules/httpdispatcher/httpdispatcher.js:123:9)
at /opt/microservices/node_modules/httpdispatcher/httpdispatcher.js:130:3
at /opt/microservices/ratings.js:109:18
at Connection.connect (/opt/microservices/node_modules/mysql/lib/Connection.js:116:18)
at Protocol.handshake (/opt/microservices/node_modules/mysql/lib/protocol/Protocol.js:51:23)
at Protocol._enqueue (/opt/microservices/node_modules/mysql/lib/protocol/Protocol.js:144:48)
--------------------
Error: Connection lost: The server closed the connection.     at Protocol.end (/opt/microservices/node_modules/mysql/lib/protocol/Protocol.js:112:13)     at Socket.<anonymous> (/opt/microservices/node_modules/mysql/lib/Connection.js:94:28)     at Socket.<anonymous> (/opt/microservices/node_modules/mysql/lib/Connection.js:526:10)     at Socket.emit (events.js:327:22)     at endReadableNT (_stream_readable.js:1221:12)     at processTicksAndRejections (internal/process/task_queues.js:84:21)
GET /ratings/0
2020-09-18T02:43:15.186300Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 13,
}
code: 'PROTOCOL_CONNECTION_LOST'
fatal: true,
```

**Solutions**

[The Bookinfo with a Virtual Machine document](https://istio.io/latest/docs/examples/virtual-machines/bookinfo/) is not a complete narrative and is also missing key actions. You also need to install WorkloadEntry, ServiceEntry, and DestinationRule for the virtual machine. Here's the YAML I added.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mtls-mysqldb-vm
spec:
  host: mysqldb.vm.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: mysqldb-vm
spec:
  hosts:
  - mysqldb.vm.svc.cluster.local
  location: MESH_INTERNAL
  ports:
  - number: 3306
    name: mysql
    protocol: mysql
  resolution: STATIC
  workloadSelector:
    labels:
      app: mysqldb-vm
---
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: mysqldb-vm
spec:
  address: #This is the IP address of the VM
  labels:
    app: mysqldb-vm
    instance-id: ubuntu-vm-mariadb
```

These YAML were applied to the `bookinfo` namespace with the command below.

I think that's the right way to think about it, but it still doesn't have the effect I expected.
@SecurityInsanity could you help me to check it?

[log.zip](https://github.com/istio/istio/files/5245174/log.zip)
