### ISSUE TITLE
Istio Ingressgateway pods are running on not-edge nodes.

### ISSUE THREAD

**Issue by luiof** [istio/istio#27437]
Hi team! 
We are using the Istio managed provided as Addon in the IBM Cloud. The ingressgateway pods are running on not-edge nodes. We checked each ingressgateway pod and we found that there are not ingressgateways on our edge nodes.

From the istio-ingressdeployment we can see the affinity:

```
spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: dedicated
                operator: In
                values:
                - edge
            weight: 100
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - istio-ingressgateway
              topologyKey: kubernetes.io/hostname
            weight: 100
```
But the affinity doesn't seem to work.
A solution could be to create a custom gateway as in [https://github.com/rvennam/istio-on-iks/blob/master/custom-istio-ingress.md](https://github.com/rvennam/istio-on-iks/blob/master/custom-istio-ingress.md):

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: managed-istio-custom-gw
  namespace: mynamespace
spec:
  profile: empty
  components:
    ingressGateways:
      - name: istio-ingressgateway
        label:
          istio: istio-ingressgateway
        namespace: mynamespace
        enabled: true
        k8s:
          hpaSpec:
            minReplicas: 2
          tolerations:
          - key: dedicated
            value: edge
          overlays:
          - kind: Deployment
            name: istio-ingressgateway
            patches:
            - path: spec.template.spec.affinity
              value:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                      - matchExpressions:
                        - key: dedicated
                          operator: NotIn
                          values:
                          - internal
                        - key: dedicated
                          operator: In
                          values:
                          - edge
                podAntiAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                  - labelSelector:
                      matchExpressions:
                      - key: app
                        operator: In
                        values:
                        - istio-ingressgateway
                    topologyKey: kubernetes.io/hostname
```
But this requires an extra effort to manage custom components. 

Is there any chance to have this addressed in managed istio? It'll be highly appreciated.

**Comment by morvencao** [comment]
Any taint in edge node? Looks like you also need to set tolerations to gateway deployment.

**Comment by luiof** [comment]
Yes, the edge node has the taint `dedicated=edge:NoExecute`. 
How can we add the tolerations to the gw deployment without create a custom component in the managed istio?

**Comment by luiof** [comment]
I made some tests. The custom gateway works in my initial test! (https://github.com/rvennam/istio-on-iks/blob/master/custom-istio-ingress-1.7.md#other-recommended-customizations)

Just for information, in our case it works but it is not necessary (or not enough) to change the affinity on the node from preferred to required . In our case, we have the edge node with taints, so we added:

```
tolerations:
   - key: dedicated
     value: edge
```

If we change only the affinity to required, we get the error:
`0/6 nodes are available: 3 node(s) didn't match node selector, 3 node(s) had taints that the pod didn't tolerate`.
So, to fix we add only the tolerations on the custom iop. If someone want to use the same configuration for a test, that it is:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: ibm-operators
  name: mycustom-ingressgateway-iop
spec:
  profile: empty
  hub: icr.io/ext/istio
  tag: 1.7.2 
  revision: mycustom-ingressgateway 
  components:
    ingressGateways:
      - name: mycustom-ingressgateway
        label:
          istio: mycustom-ingressgateway
        namespace: ghost
        enabled: true
        k8s:
          hpaSpec:
            minReplicas: 2
          tolerations:
          - key: dedicated
            value: edge
          serviceAnnotations:
            service.kubernetes.io/ibm-load-balancer-cloud-provider-ip-type: public 
```
