### ISSUE TITLE
Multicluster mTLS throws 503 error for istio 1.5.7

### ISSUE THREAD

**Issue by y0zg** [istio/istio#27433]
I followed standard istio multicluster version 1.5.7 deployment as per documentation 
- https://istio.io/v1.5/docs/setup/install/multicluster/gateways/
- https://istio.io/latest/docs/setup/install/multicluster/gateways/

Added recommended local ServiceEntry as mentioned in  https://github.com/istio/istio/issues/27321#issuecomment-693690717
but this didn't help

```
k get se httpbin-bar -o yaml -n bar --export
Flag --export has been deprecated, This flag is deprecated and will be removed in future.
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1alpha3","kind":"ServiceEntry","metadata":{"annotations":{},"name":"httpbin-bar","namespace":"bar"},"spec":{"addresses":["240.0.0.2"],"endpoints":[{"address":"10.48.11.134","ports":{"http":8000}}],"hosts":["httpbin.bar.global"],"location":"MESH_INTERNAL","ports":[{"name":"http","number":8000,"protocol":"http"}],"resolution":"DNS"}}
  generation: 1
  name: httpbin-bar
  selfLink: /apis/networking.istio.io/v1beta1/namespaces/bar/serviceentries/httpbin-bar
spec:
  addresses:
  - 240.0.0.2
  endpoints:
  - address: 10.48.11.134
    ports:
      http: 8000
  hosts:
  - httpbin.bar.global
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 8000
    protocol: http
  resolution: DNS
```

[x] Docs
[x] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

**How was Istio installed?**
Helm chart

```
helm template install/kubernetes/helm/istio \
  --namespace istio-system \
  --set gateways.istio-ingressgateway.sds.enabled=true \
  --set global.k8sIngress.enabled=false \
  --set global.k8sIngress.enableHttps=false \
  --set global.k8sIngress.gatewayName=ingressgateway \
  --set certmanager.enabled=true \
  --set certmanager.tag=v0.10.0 \
  --set certmanager.email=user@example.com \
  --set certmanager.extraArgs={--webhook-namespace=istio-system} \
  --set kiali.enabled=true \
  --set kiali.tag="v1.18" \
  --set kiali.createDemoSecret=true \
  --set grafana.enabled=true \
  --set tracing.enabled=true \
  --set gateways.istio-egressgateway.enabled=true \
  --set prometheus.retention=7d \
  --set global.controlPlaneSecurityEnabled=true \
  -f install/kubernetes/helm/istio/example-values/values-istio-multicluster-gateways.yaml > istio-install-multi.yaml
```

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.7", GitCommit:"b4455102ef392bf7d594ef96b97a4caa79d729d9", GitTreeState:"clean", BuildDate:"2020-06-17T11:39:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-gke.1504", GitCommit:"fb367de18820fe57bac5d97ad60b7a2cef8765e9", GitTreeState:"clean", BuildDate:"2020-09-09T01:00:23Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

```
helm version
Client: &version.Version{SemVer:"v2.16.10", GitCommit:"bceca24a91639f045f22ab0f41e47589a932cf5e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.10", GitCommit:"bceca24a91639f045f22ab0f41e47589a932cf5e", GitTreeState:"clean"}
```

Cluster 1:
```
istioctl proxy-status
NAME                                                   CDS        LDS        EDS        RDS          PILOT                            VERSION
istio-egressgateway-f74b8fb5c-tqktm.istio-system       SYNCED     SYNCED     SYNCED     NOT SENT     istio-pilot-76d887f946-wk5fc     1.5.7
istio-ingressgateway-5f657c8bfc-gxwb8.istio-system     SYNCED     SYNCED     SYNCED     NOT SENT     istio-pilot-76d887f946-wk5fc     1.5.7
sleep-f8cbf5b76-694jz.foo                              SYNCED     SYNCED     SYNCED     SYNCED       istio-pilot-76d887f946-wk5fc     1.5.7
```

Cluster 2:
```
istioctl proxy-status
NAME                                                   CDS        LDS        EDS        RDS          PILOT                            VERSION
httpbin-779c54bf49-xxvk7.bar                           SYNCED     SYNCED     SYNCED     SYNCED       istio-pilot-76d887f946-kfhgt     1.5.7
istio-egressgateway-f74b8fb5c-ccpkf.istio-system       SYNCED     SYNCED     SYNCED     NOT SENT     istio-pilot-76d887f946-kfhgt     1.5.7
istio-ingressgateway-5f657c8bfc-mvl65.istio-system     SYNCED     SYNCED     SYNCED     NOT SENT     istio-pilot-76d887f946-kfhgt     1.5.7
```

Calling httpbin from Cluster 1 **error**:

```
kubectl exec sleep-f8cbf5b76-694jz -n foo -c sleep -- curl -Is httpbin.bar.global:8000/headers
HTTP/1.1 503 Service Unavailable
content-length: 91
content-type: text/plain
date: Mon, 21 Sep 2020 09:25:49 GMT
server: envoy
```

cluster 2 ingress logs:
```
[Envoy (Epoch 0)] [2020-09-21 09:25:17.792][26][debug][grpc] [src/envoy/utils/grpc_transport.cc:44] Sending Report request: attributes {
  strings {
    key: 3
    value: -1
  }
  strings {
    key: 4
    value: -7
  }
  strings {
    key: 125
    value: -3
  }
  strings {
    key: 131
    value: 124
  }
  strings {
    key: 171
    value: -6
  }
  strings {
    key: 197
    value: -1
  }
  strings {
    key: 201
    value: 220
  }
  strings {
    key: 202
    value: -5
  }
  strings {
    key: 221
    value: -4
  }
  int64s {
    key: 126
    value: 0
  }
  int64s {
    key: 127
    value: 0
  }
  int64s {
    key: 128
    value: 0
  }
  int64s {
    key: 129
    value: 0
  }
  int64s {
    key: 151
    value: 15443
  }
  bools {
    key: 177
    value: false
  }
  timestamps {
    key: 133
    value {
      seconds: 1600680316
      nanos: 793452000
    }
  }
  durations {
    key: 130
    value {
      nanos: 151000
    }
  }
  bytes {
    key: -2
    value: "\n\200\000 "
  }
  bytes {
    key: 0
    value: "\n\200\000 "
  }
  bytes {
    key: 150
    value: "\n,\001\013"
  }
}
default_words: "kubernetes://istio-ingressgateway-5f657c8bfc-mvl65.istio-system"
default_words: "origin.ip"
default_words: "ab8102ea-0004-4a24-b3dc-d15351edfe63-35"
default_words: "1.5.7"
default_words: "outbound_.8000_._.httpbin.bar.global"
default_words: "close"
default_words: "istio-system"
global_word_count: 222
repeated_attributes_semantics: INDEPENDENT_ENCODING

[Envoy (Epoch 0)] [2020-09-21 09:25:17.792][26][debug][filter] [./src/envoy/utils/header_update.h:45] Mixer forward attributes set: Ck8KCnNvdXJjZS51aWQSQRI/a3ViZXJuZXRlczovL2lzdGlvLWluZ3Jlc3NnYXRld2F5LTVmNjU3YzhiZmMtbXZsNjUuaXN0aW8tc3lzdGVt
[Envoy (Epoch 0)] [2020-09-21 09:25:17.792][26][debug][router] [external/envoy/source/common/router/router.cc:474] [C0][S15730288589287968518] cluster 'outbound|15004||istio-telemetry.istio-system.svc.cluster.local' match for URL '/istio.mixer.v1.Mixer/Report'
```

Cluster 1 resolution of httpbin.bar.global:
```

kubectl exec sleep-f8cbf5b76-694jz -n foo -c sleep -- dig +short 10.8.0.156 A httpbin.bar.global
10.8.0.156
240.0.0.2
```

[istio-dump-cluster1.tar.gz](https://github.com/istio/istio/files/5254701/istio-dump-cluster1.tar.gz)
[istio-dump-cluster2.tar.gz](https://github.com/istio/istio/files/5254703/istio-dump-cluster2.tar.gz)

[k8s_resources_cluster1-2.zip](https://github.com/istio/istio/files/5254708/k8s_resources_cluster1-2.zip)
