### ISSUE TITLE
Disable RequestAuthentication JWT rules for specific paths

### ISSUE THREAD

**Issue by senthilrch** [istio/istio#27432]
**Describe the feature request**
I am using the RequestAuthentication API at the Istio Ingress Gateway to enforce clients to present a valid JWT token. This is working fine.

However there are some workloads within the cluster which need to be exposed without the need to have a valid JWT token. One such workload is Keycloak which serves as the OAuth provider. Keycloak is responsible for issuing tokens, so clients accessing the Keycloak's path (/auth) can NEVER present a valid JWT token. Similarly there could be other paths that I need to expose without JWT token.

In the RequestAuthentication API, there are no fields to specify excluded paths. See below the API specification in version 1.7:-
https://istio.io/latest/docs/reference/config/security/request_authentication/

In the legacy Authentication API (in Istio version 1.4) it had support for excluded paths. See below link for the API specification in Istio 1.4:-
https://istio.io/v1.4/docs/reference/config/security/istio.authentication.v1alpha1/

See below text from above link:-
>A JWT for all requests except request at path /health_check and path with prefix /status/. This is useful to expose some paths for public access but keep others JWT validated.
>
>issuer: https://example.com
>jwksUri: https://example.com/.well-known/jwks.json
>triggerRules:
>- excludedPaths:
>  - exact: /health_check
>  - prefix: /status/

**However when the API's were re-designed in Istio 1.5, this functionality is missing.**

Find below the YAML manifests of RequestAuthentication and AuthorizationPolicy I am using (these manifests enforce JWT authentication for ALL paths and specifically would permit access to path /nginx subject to meeting the rules defined in the authorization policy):-
```yaml
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: my-request-authentication
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
  jwtRules:
  - issuer: "https://www.example.com/auth/realms/mxe"
    jwksUri: "https://www.example.com/auth/realms/mxe/protocol/openid-connect/certs"
```

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: my-authorization-policy
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
  action: ALLOW
  rules:
  - from:
    - source:
        requestPrincipals: ["https://www.example.com/auth/realms/mxe/4374027b-f16e-4da1-8445-b0ebd09f5905"]
    to:
    - operation:
        paths: ["/nginx"]
```

**Describe alternatives you've considered**
The moment I install a ReqestAuthentication object and an AuthorizationPolicy object, Ingress Gateway expects EVERY request to fulfill the JWT rules specified in ReqestAuthentication. I don't know if my requirement can be achieved in an alternate manner using the existing APIs.

If there are alternate ways to fulfil my requirement, I would be glad if someone can point me towards that.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by xulingqing** [comment]
@yangminzhu Hi Yangming, could you take a look? Thanks!

**Comment by yangminzhu** [comment]
> The moment I install a ReqestAuthentication object and an AuthorizationPolicy object, Ingress Gateway expects EVERY request to fulfill the JWT rules specified in ReqestAuthentication. I don't know if my requirement can be achieved in an alternate manner using the existing APIs.

It's also doable in the new API, you can use the following to exclude path (e.g. "/healthz") from JWT:
```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: my-authorization-policy
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
  action: ALLOW
  rules:
  - from:
    - source:
        requestPrincipals: ["https://www.example.com/auth/realms/mxe/4374027b-f16e-4da1-8445-b0ebd09f5905"]
    to:
    - operation:
        paths: ["/nginx"]
  - to:
    # The 2nd rule doesn't have `from` allowing any access (without JWT) to /healthz
    - operation:
        paths: ["/healthz"]
```


Also see https://istio.io/latest/docs/tasks/security/authentication/authn-policy/#require-valid-tokens-per-path

**Comment by senthilrch** [comment]
@yangminzhu : the solution you provided works. thanks.
closing this issue.

**Comment by lizongshen** [comment]
@yangminzhu Dose paths: ["/nginx"]  support path prefix?

**Comment by VladMasarik** [comment]
You might want to exclude the path also from EnvoyFilter https://stackoverflow.com/questions/63448933/istio-exclude-service-from-ext-auth
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: bypass-authn
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: HTTP_ROUTE
      match:
        routeConfiguration:
          vhost:
            route:
              name: /public/path
      patch:
        operation: MERGE
        value:
          name: envoy.ext_authz_disabled
          typed_per_filter_config:
            envoy.ext_authz:
              "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute
              disabled: true
```
