### ISSUE TITLE
Cryptic unmarshalerDecoder error message when install istio using istio operator

### ISSUE THREAD

**Issue by bobbui** [istio/istio#27453]
**Bug description**
Getting this error message print out on istio operator after deploy a new istio operator CRD instance
```
v1alpha1.IstioOperator: v1alpha1.IstioOperator.Status: Spec: unmarshalerDecoder: json: cannot unmarshal bool into Go value of type string, error found in #10 byte of ... ││ |way"}]}}}},"status":|..., bigger context ...|io/hostname","values":"istio-ingressgateway"}]}}}},"status":{"componentStatus":{"Base":{"status":"HE|...
```

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Istio should print out more detail error message which indicates exactly what go wrong

**Steps to reproduce the bug**
using this YAML to deploy istio
```YAML
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-default-instance
  namespace: istio-system
spec:
  components:
    base:
      enabled: true
    cni:
      enabled: false
    ingressGateways:
      - enabled: true
        name: istio-ingressgateway
        k8s:
          priorityClassName: infra-critical
          nodeSelector:
            node.kubernetes.io/lifecycle: normal
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
            service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: true
            service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS-1-1-2017-01
            service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
          env:
            - name: ISTIO_META_ROUTER_MODE
              value: sni-dnat
          hpaSpec:
            maxReplicas: 5
            minReplicas: 1
            metrics:
              - resource:
                  name: cpu
                  targetAverageUtilization: 80
                type: Resource
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: istio-ingressgateway
          service:
            ports:
              - name: status-port
                port: 15021
                targetPort: 15021
              - name: http2
                port: 80
                targetPort: 8080
              - name: https
                port: 443
                targetPort: 8443
              - name: tls
                port: 15443
                targetPort: 15443
          strategy:
            rollingUpdate:
              maxSurge: 100%
              maxUnavailable: 24%
  hub: docker.io/istio
  tag: 1.7.2
  values:
    gateways:
      istio-ingressgateway:
        podAntiAffinityTermLabelSelector:
          - topologyKey: kubernetes.io/hostname
            operator: In
            key: app
            values: istio-ingressgateway
```
**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
istioctl 
```
client version: 1.7.1
control plane version: 1.7.1
data plane version: 1.7.1 (1 proxies)
```
kubectl 
```
Client Version: v1.18.2
Server Version: v1.16.13-eks-2ba888
```

helm 
```
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}
```
**How was Istio installed?**
using istio operator
**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS
