### ISSUE TITLE
Readiness probe traffic currently identifies as unknown traffic, should be properly categorized. 

### ISSUE THREAD

**Issue by abhioncbr** [istio/istio#27475]
**Describe the feature request**
Readiness-probe traffic currently identifies as unknown traffic, it should be properly categorized to avoid confusion with the actual unknown source traffic. 

Deployment manifest
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    version: v2
    app:  frontend-nodejs-app
  name: frontend-nodejs-app-2
  namespace: istio-ssl-sample
spec:
  selector:
    matchLabels:
      app:  frontend-nodejs-app
      version: v2
  template:
    metadata:
      labels:
        app:  frontend-nodejs-app
        version: v2
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "false"  
    spec:
      serviceAccountName: frontend-nodejs-app-sa
      containers:
        - name: frontend-app
          image: frontend-nodejs-app:v2
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /ready
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3          
          ports:
          - name: https
            containerPort: 8443
          volumeMounts:
            - name: certs
              mountPath: /home/node/app/certs/
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 90Mi
            limits:
              cpu: 50m
              memory: 90Mi
      volumes:
        - name: certs
          secret:
            secretName: ssl-certs  
```

The main thing to notice using `annotation: rewriteAppHTTPProbers`.  Traffic coming for readinessProbe is shown as **unkonwn** in Kiali which is based on telemetry data. Also, the attached Kiali graph for reference.

<img width="1021" alt="Screen Shot 2020-09-23 at 2 48 58 PM" src="https://user-images.githubusercontent.com/1076944/94057412-950c4400-fdad-11ea-858c-85aa808f0c5e.png">

**Installed Istio version: 1.6.5**

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
