### ISSUE TITLE
Enable EndpointSlice by default for Kubernetes 1.19+

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#27472]
Since 1.18, EndpointSlice is enabled by default in Kubernetes. Additionally, since 1.19+, any manual endpoints are mirrored: https://github.com/kubernetes/kubernetes/pull/91637.

Based on this, the vast majority of users will be running with EndpointSlice. For the few users explicitly disabling ES in k8s, they can also explicitly opt out in Istiod.

**Comment by howardjohn** [comment]
cc @costinm @rshriram @ramaraochavali @hzxuzhonghu any concerns?

**Comment by howardjohn** [comment]
BTW I am expecting to have this auto detect k8s version - we already have code that auto detects k8s version at install for other features

**Comment by howardjohn** [comment]
Need to take into account https://github.com/kubernetes/website/blob/master/content/en/docs/concepts/services-networking/endpoint-slices.md#duplicate-endpoints

**Comment by howardjohn** [comment]
not stale

**Comment by jacob-delgado** [comment]
EndpointSlices became stable in K8s 1.21 and were deemed Beta in K8s 1.17. Istio 1.11 will support K8s 1.18, at a minimum based on support in Istio 1.10.

Looking ahead, K8s 1.21 turns on dual-stack support by default and is considered Beta. EndpointSlices are the only structure that support both IP family types; using Endpoints results in a single IP family being found. What remaining things are left to enable this by default? Looking around I see **https://github.com/istio/istio/issues/27946** as a potential roadblock, but perhaps there are other issues.


Steps to create a kind cluster in dual stack mode

```
1. Build head of **https://github.com/kubernetes-sigs/kind** repo
2. kind create cluster --image aojea/kindnode:1.22rc --config cluster.yaml
3. kubectl set image ds/kindnet kindnet-cni=kindest/kindnetd:v20210326-1e038dc5 -n kube-system
```

cluster.yaml
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: dual
nodes:
- role: control-plane
- role: worker
- role: worker
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  featureGates:
    IPv6DualStack: true
```
