### ISSUE TITLE
protocol conflicts on Gateway transparently droppped 

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#27481]
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: beta
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: tcp
      protocol: TCP
    hosts:
    - "foo.bar"
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: alpha
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "foo.bar"
```

Swap the names or creation order, and you will get two different results. **This is not logged or warned about anywhere**
