### ISSUE TITLE
istio operator cannot delete iop

### ISSUE THREAD

**Issue by cocotyty** [istio/istio#27499]
**Bug description**

[ ] Docs
[*] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
```
kubectl delete istiooperators.install.istio.io -n istio-system op
```
should delete all resource related to this iop.
**Steps to reproduce the bug**

But istio-operator hang on 
```
Deleting IstioOperator
Reconciling IstioOperator
Deleting IstioOperator
Reconciling IstioOperator
Deleting IstioOperator
Reconciling IstioOperator
...
```

Change the istio-operator's log level, and see this logs:
```
2020-09-24T08:23:09.595464Z	info	Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"istiod-1-7-2-5d6f6f65d7-2rr7m:8080\" is forbidden: User \"system:serviceaccount:istio-operator:istio-operator-1-7-2\" cannot get resource \"pods/proxy\" in API group \"\" in the namespace \"istio-system\"","reason":"Forbidden","details":{"name":"istiod-1-7-2-5d6f6f65d7-2rr7m:8080","kind":"pods"},"code":403}
```
So try to edit the clusterrole:
```
kubectl edit clusterrole -n istio-operator istio-operator-1-7-2 
```
change the clusterrole:
```yaml
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - events
  - namespaces
  - pods
  - pods/proxy
  - persistentvolumeclaims
  - secrets
  - services
  - serviceaccounts
  verbs:
  - '*'
```
Then the istio operator works!

It seems like that the clusterrole generated miss  **pods/proxy** permission.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
istio 1.7.2 k8s v1.16.8.
**How was Istio installed?**
istio operator.
**Environment where bug was observed (cloud vendor, OS, etc)**
k8s v1.16.8.
