### ISSUE TITLE
validatingwebhookconfigurations not work with revision

### ISSUE THREAD

**Issue by cocotyty** [istio/istio#27501]
**Bug description**
validatingwebhookconfigurations not work with revision.
istiod always print such logs:
```
info	validationController	Reconcile(enter): retry dry-run creation of invalid config
info	validationController	Not ready to switch validation to fail-closed: dummy invalid config not rejected
info	validationController	validatingwebhookconfiguration istiod-istio-system (failurePolicy=Ignore, resourceVersion=6800611) is up-to-date. No change required.
```

[ ] Docs
[*] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
No such logs.

And ValidatingWebhookConfiguration/istiod-istio-system may be like this:
```
service:
      name: istiod-1-7-2
      namespace: istio-system
      path: /validate
      port: 443
```
**Steps to reproduce the bug**
the template file is wrong!
[https://github.com/istio/istio/blob/4bf96efd959522e3f1adb0cd5f75f889270f9d9b/manifests/charts/base/templates/validatingwebhookconfiguration.yaml#L17]()

```yaml
 service:
        name: istiod
        namespace: {{ .Values.global.istioNamespace }}
        path: "/validate"
```

should  be like this file:
[https://github.com/istio/istio/blob/4bf96efd959522e3f1adb0cd5f75f889270f9d9b/manifests/charts/istio-control/istio-discovery/templates/mutatingwebhook.yaml#L19]()
```yaml
service:
        name: istiod{{- if not (eq .Values.revision "") }}-{{ .Values.revision }}{{- end }}
        namespace: {{ .Release.Namespace }}
        path: "/inject"
```
**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
istio 1.7.2.
k8s v1.16.8.
**How was Istio installed?**
istio operator.
**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by marcus-sa** [comment]
So that's why the sidecars are not being automatically injected..

**Comment by aaaaahaaaaa** [comment]
Is there currently a workaround for this? I'm encountering the same issue on a pristine GKE cluster when trying to install 1.8.1 with the default configuration. I tried to install via istioctl, the operator and also Helm.

**Comment by kameshsampath** [comment]
I get this error with 1.11.4 and 1.11.5 when using revisions with operator

**Comment by itsmesuniljacob** [comment]
Hi Team,

Was there an update on this issue? I have the same same issue when upgrading from 1.11.1 -> 1.12.2

`error when creating "samples/bookinfo/networking/bookinfo-gateway.yaml": Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=10s": no endpoints available for service "istiod"`

**Comment by kelvinwijaya** [comment]
I face a similar issue as well when using revision:

`error occurred: failed calling webhook "rev.object.sidecar-injector.istio.io": Post "https://istiod-1-13-0.istio-system-poc.svc:443/inject?timeout=10s": Address is not allowed`

Notice the error message a bit different and not related to cert issue

**Comment by jt-shippit** [comment]
I am having the same issue while trying to upgrade from version 1.9.9 to 1.11.8:

`2022-05-23T02:39:16.308388Z	info	validationController	Not ready to switch validation to fail-closed: dummy invalid rejected for the wrong reason: Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=30s": service "istiod" not found`

**Comment by itsmesuniljacob** [comment]
@jt-shippit I used the solution describe as below
`https://github.com/istio/istio/issues/28880`

```
apiVersion: v1
kind: Service
metadata:
  name: istiod
  namespace: istio-system
spec:
  ports:
    - name: https-webhook
      port: 443
      protocol: TCP
      targetPort: 15017
  selector:
    app: istiod
    istio.io/rev: 1-9-1
```
