### ISSUE TITLE
cam authentication policy support "exclude option method"?

### ISSUE THREAD

**Issue by johnzheng1975** [istio/istio#27547]
For istio jwt verify,  I am using authentication policy.
https://istio.io/v1.4/docs/reference/config/security/istio.authentication.v1alpha1/

I want to exclude all api with "option" method, can it be possible? Thanks.
Currently seems it only support excludedPaths
```
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: productpage-mTLS-with-JWT
  namespace: frod
spec:
  targets:
  - name: productpage
    ports:
    - number: 9000
  peers:
  - mtls:
  origins:
  - jwt:
      issuer: "https://securetoken.google.com"
      audiences:
      - "productpage"
      jwksUri: "https://www.googleapis.com/oauth2/v1/certs"
      jwtHeaders:
      - "x-goog-iap-jwt-assertion"
      triggerRules:
      - excludedPaths:
        - exact: /health_check
  principalBinding: USE_ORIGIN
```
