### ISSUE TITLE
ingress gateway authorization policy with the hostname  rather than the IP addresses and authorize based on the last IP address/hostname which contacts the ingress gateway(not all hops)

### ISSUE THREAD

**Issue by Bhanu88** [istio/istio#27545]
Hi All,

I was trying to implement ingress gateway authorization policy with the hostname  rather than the IP addresses 

currently, I implemented the policy using the with the combination of the deny all policy and allow IP but it takes too many IP addresses to allows any request and also the IP address the are fluctuating continuously so its difficult to maintain it for a long time 

I looked at the documentation but I don't found anything.

so I wish the following  

1.authorize based on the **last IP address/hostname** which contacts the ingress gateway(not all hops).
2.autohrization based on hostname rather than IP address 

steps I followed (Istio 1.5.7)

Deny all 
----------------------------------------------
```yaml
kubectl apply -f - <<EOF
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-all
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
EOF
```
allow certain IP blocks
-----------------------------------------------------------------------
```yaml
kubectl apply -f - <<EOF
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ingress-policy
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  action: ALLOW
  rules:
  - from:
    - source:
       ipBlocks: ["xx.xx.xx.xx/xx","xx.xx.xx.xx","xx.xx.xx.xx"]
EOF
```
