### ISSUE TITLE
A Failure to use Lua external modules in EnvoyFilter

### ISSUE THREAD

**Issue by michalrubaj** [istio/istio#27546]
**Bug description**

I've got an Envoy Filter in which I add a header to every HTTP request. The header's value comes from an external API. I have a Lua script to fetch that data and then to set it as a headers' value. The filter itself works because I checked whether it added a hardcoded version of my header and it did. But when I switched to fetch the value from API it didn't. I wasn't quite sure what might have been the reason so I basically deleted a line after line of my Lua script to see where it crashes and it seems that the reason is a require keyword because I left my Lua as shown below and it didn't add the header to the request. Though I have installed that module to my Kubernetes cluster and I can execute my Lua script via shell it seems like EnvoyFilter cannot execute it in the filter itself.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: lua-filter
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: ANY
      listener:
        portNumber: 7123
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.router"
    patch:
      operation: INSERT_BEFORE
      value:
       name: envoy.lua
       typed_config:
         "@type": "type.googleapis.com/envoy.config.filter.http.lua.v2.Lua"
         inlineCode: |
            function envoy_on_request(request_handle)
                local http = require('socket.http')
                request_handle:headers():add("authorization", "it works!")
            end
```

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
A header is added to HTTP request

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
istioctl :  1.5.10
kubectl:  v1.15.0

**How was Istio installed?**
istioctl
**Environment where bug was observed (cloud vendor, OS, etc)**
on premises, centos 7
