### ISSUE TITLE
Circuit Breaker with TLS Doesn't Return x-envoy-overloaded Header

### ISSUE THREAD

**Issue by nicole-chen-fivestars** [istio/istio#27544]
**Expected behavior**
When a circuit breaker (outlier detection) trips, we expect to see [x-envoy-overloaded](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#x-envoy-overloaded) header returned as part of the response. But, not seeing that with TLS origination.

**Steps to reproduce the bug**
```
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: httpbin
spec:
  hosts:
  - httpbin.org
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - httpbin.org
  http:
  - headers:
      request:
        set:
          x-envoy-retriable-status-codes: "429"
    name: http-route
    match:
    - port: 80
    route:
    - destination:
        host: httpbin.org
        subset: tls-origination
        port:
          number: 443
    retries:
      attempts: 1
      retryOn: retriable-status-codes,reset
      perTryTimeout: 0.5s

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: httpbin
spec:
  host: httpbin.org
  subsets:
  - name: tls-origination
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE
        sni: httpbin.org
      outlierDetection:
        consecutiveErrors: 1
        interval: 5s
        baseEjectionTime: 5s
        maxEjectionPercent: 100
        minHealthPercent: 0
```

Then, `curl -I httpbin.org/delay/1` a couple times and a 503 should trip.

I do notice that, when a 503 or 504 is returned, there seems to be no header at all compared to a normal 200 return. Examples:
```
$ curl -I http://httpbin.org/status/200
HTTP/1.1 200 OK
date: Fri, 25 Sep 2020 08:00:18 GMT
content-type: text/html; charset=utf-8
content-length: 0
server: envoy
access-control-allow-origin: *
access-control-allow-credentials: true
x-envoy-upstream-service-time: 375
```

```
$ curl -I http://httpbin.org/status/200
HTTP/1.1 503 Service Unavailable
content-length: 19
content-type: text/plain
date: Fri, 25 Sep 2020 07:59:34 GMT
server: envoy
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
$ istioctl version --remote
client version: 1.6.2
control plane version: 1.6.2
data plane version: 1.6.2 (3 proxies)
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:20:18Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:11:50Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
