### ISSUE TITLE
Istio locality load balancing not working from ingress

### ISSUE THREAD

**Issue by bseenu** [istio/istio#27552]
**Bug description**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**
I have an tcp ingress gateway with 2 ingress pods in 2 zones ( us-east-1a and us-east-1b) and my application deployed in 2 zones us-east-1a and us-east-1b, I was expecting the locality loadbalancing will be sending the requests to the same zone pod which is not happening

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

bash-3.2$ istioctl version
client version: 1.7.2
control plane version: 1.7.2
data plane version: 1.7.2 (8 proxies)

**How was Istio installed?**
https://istio.io/latest/docs/setup/getting-started/

**Environment where bug was observed (cloud vendor, OS, etc)**
cloud - AWS

**Comment by christian-posta** [comment]
Did you set up a destination rule with outlier detection configured for the services?

**Comment by bseenu** [comment]
Yes i did, here is my destination rule config

```
apiVersion: networking.istio.io/v1alpha3
 kind: DestinationRule
 metadata:
   name: tcp-lb
   namespace: istio-system
 spec:
   host: tcp-app.svc.cluster.local
   trafficPolicy:
     loadBalancer:
       simple: LEAST_CONN
       localityLbSetting:
         enabled: true
     outlierDetection:
       consecutiveErrors: 7
       interval: 30s
       baseEjectionTime: 30s
```
