### ISSUE TITLE
Custom ingressgateway is unable to install, looking for help

### ISSUE THREAD

**Issue by houshengbo** [istio/istio#27558]
I tried to use the latest source code of istio to install custom ingressgateway with the operator, but failed to launch any custom ingressgateway.

Steps to produce the issue:
1. Download the source code of istio with `gie clone git@github.com:istio/istio.git`.
2. Go to the directory of istio and run the following commands to build and push the images:
```
make gen-charts
HUB=docker.io/my-own-name TAG=latest make docker.pilot
HUB=docker.io/my-own-name TAG=latest make docker.proxyv2
HUB=docker.io/my-own-name TAG=latest make docker.operator
docker push my-own-name/pilot:latest
docker push my-own-name/operator:latest
docker push my-own-name/proxyv2:latest
```

3. Modify the file `manifests/charts/istio-operator/values.yaml` by changing hub: gcr.io/istio-testing into docker.io/my-own-name.

4. Create the CRD of istio operator with `kubectl apply -f manifests/charts/istio-operator/crds`.
5. Launch the istio operator with `helm template manifests/charts/istio-operator/ | kubectl apply -f - `. Operator is running:
```
NAME             READY   UP-TO-DATE   AVAILABLE   AGE
istio-operator   1/1     1            1           14s
```

6. Create the istiooperator CR to launch istiod, ingressgateway and egressgateway.
```
kubectl create namespace istio-system
kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: demo
EOF
```

All pods are running:
```
NAME                                    READY   STATUS    RESTARTS   AGE
istio-egressgateway-84d4c7777c-7jbs9    1/1     Running   0          10s
istio-ingressgateway-849bf9df44-trzjz   1/1     Running   0          10s
istiod-55d7979748-5xqlq                 1/1     Running   0          18s
```

Check the ingress gateway with`kubectl get svc -n istio-system istio-ingressgateway`:
```
NAME                   TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)                                                                      AGE
istio-ingressgateway   LoadBalancer   172.21.121.115   169.60.125.138   15021:32476/TCP,80:31762/TCP,443:32297/TCP,31400:31554/TCP,15443:32233/TCP   90s
```

7. Create a ns custom-gateways with `kubectl create namespace custom-gateways`.

8. Create a new istiooperator CR with
```
kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: custom-ingressgateway-iop
spec:
  profile: empty
  hub: docker.io/my-own-name
  tag: latest 
  revision: custom-ingressgateway
  components:
    ingressGateways:
      - name: custom-ingressgateway
        label: 
          istio: custom-ingressgateway
        namespace: custom-gateways
        enabled: true
        k8s:
          serviceAnnotations:
            service.kubernetes.io/ibm-load-balancer-cloud-provider-ip-type: public
EOF
```

9. The deployment `custom-ingressgateway` launched. Shit! This issue is gone.
