### ISSUE TITLE
istioOperator API - proper way to add volumeMount into Deployment with K8sObjectOverlay-PathValue

### ISSUE THREAD

**Issue by y0zg** [istio/istio#27569]
I tried to add extra grafana dashboards into `IstioOperator` manifest but it allows only to create `volume` and not `volumeMount`

Followed this documentation and noticed  _For add, the path should be a new leaf._ (tried various options)
- K8sObjectOverlay-PathValue https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#K8sObjectOverlay-PathValue 
- https://github.com/istio/api/blob/master/operator/v1alpha1/operator.proto#L270

Here is one of the example I tried:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  hub: docker.io/istio
  tag: 1.7.2

  meshConfig:
    accessLogFile: "/dev/stdout"

  # Traffic management feature
  components:
    base:
      enabled: true
    pilot:
      enabled: true

    # Policy feature
    policy:
      enabled: false

    # Telemetry feature
    telemetry:
      enabled: false

    # Istio Gateway feature
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true

    egressGateways:
    - name: istio-egressgateway
      enabled: true

    # Istio CNI feature
    cni:
      enabled: false

  addonComponents:
    prometheus:
      enabled: true
    kiali:
      enabled: true
    grafana:
      enabled: true
      k8s:
        overlays:
          - apiVersion: apps/v1
            kind: Deployment
            name: grafana
            patches: 
            - path: spec.template.spec.containers.[name:grafana]
              value: |
                volumeMounts:  
                  - mountPath: /var/lib/grafana/dashboards/istio/artemis-dashboard.json
                    name: artemis
                    readOnly: true
                    subPath: artemis-dashboard.json
                  - mountPath: /data/grafana
                    name: data
                  - mountPath: /var/lib/grafana/dashboards/istio/istio-mesh-dashboard.json
                    name: dashboards-istio-istio-mesh-dashboard
                    readOnly: true
                    subPath: istio-mesh-dashboard.json
                  - mountPath: /var/lib/grafana/dashboards/istio/istio-performance-dashboard.json
                    name: dashboards-istio-istio-performance-dashboard
                    readOnly: true
                    subPath: istio-performance-dashboard.json
                  - mountPath: /var/lib/grafana/dashboards/istio/istio-service-dashboard.json
                    name: dashboards-istio-istio-service-dashboard
                    readOnly: true
                    subPath: istio-service-dashboard.json
                  - mountPath: /var/lib/grafana/dashboards/istio/istio-workload-dashboard.json
                    name: dashboards-istio-istio-workload-dashboard
                    readOnly: true
                    subPath: istio-workload-dashboard.json
                  - mountPath: /var/lib/grafana/dashboards/istio/mixer-dashboard.json
                    name: dashboards-istio-mixer-dashboard
                    readOnly: true
                    subPath: mixer-dashboard.json
                  - mountPath: /var/lib/grafana/dashboards/istio/pilot-dashboard.json
                    name: dashboards-istio-pilot-dashboard
                    readOnly: true
                    subPath: pilot-dashboard.json
                  - mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
                    name: config
                    subPath: datasources.yaml
                  - mountPath: /etc/grafana/provisioning/dashboards/dashboardproviders.yaml
                    name: config
                    subPath: dashboardproviders.yaml
            - path: spec.template.spec
              value: |
                volumes:
                - configMap:
                    defaultMode: 420
                    name: istio-grafana-configuration-dashboards-artemis-dashboard
                  name: artemis
                - configMap:
                    defaultMode: 420
                    name: istio-grafana
                  name: config
                - emptyDir: {}
                  name: data
                - configMap:
                    defaultMode: 420
                    name: istio-grafana-configuration-dashboards-istio-mesh-dashboard
                  name: dashboards-istio-istio-mesh-dashboard
                - configMap:
                    defaultMode: 420
                    name: istio-grafana-configuration-dashboards-istio-performance-dashboard
                  name: dashboards-istio-istio-performance-dashboard
                - configMap:
                    defaultMode: 420
                    name: istio-grafana-configuration-dashboards-istio-service-dashboard
                  name: dashboards-istio-istio-service-dashboard
                - configMap:
                    defaultMode: 420
                    name: istio-grafana-configuration-dashboards-istio-workload-dashboard
                  name: dashboards-istio-istio-workload-dashboard
                - configMap:
                    defaultMode: 420
                    name: istio-grafana-configuration-dashboards-mixer-dashboard
                  name: dashboards-istio-mixer-dashboard
                - configMap:
                    defaultMode: 420
                    name: istio-grafana-configuration-dashboards-pilot-dashboard
                  name: dashboards-istio-pilot-dashboard      
      
    tracing:
      enabled: true
    istiocoredns:
      enabled: true

  values:
    global:
      istioNamespace: istio-system
      podDNSSearchNamespaces:
        - global
      multiCluster:
        enabled: true
      logging:
        level: "default:info"
      jwtPolicy: third-party-jwt
      proxy:
        image: proxyv2
        clusterDomain: "cluster.local"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 2000m
            memory: 1024Mi
        logLevel: warning
        componentLogLevel: "misc:error"
        privileged: true # ENABLED FOR TESTING PURPOSE
        enableCoreDump: false
        statusPort: 15020
        readinessInitialDelaySeconds: 1
        readinessPeriodSeconds: 2
        readinessFailureThreshold: 30
        includeIPRanges: "*"
        excludeIPRanges: ""
        excludeOutboundPorts: ""
        excludeInboundPorts: ""
        autoInject: enabled
        tracer: "zipkin"
      proxy_init:
      operatorManageWebhooks: false
      controlPlaneSecurityEnabled: true
      trustDomain: "cluster.local"
      sds:
        token:
          aud: istio-ca
      sts:
        servicePort: 0
    base:
      validationURL: ""
    pilot:
      image: pilot
      policy:
        enabled: false

    telemetry:
      enabled: true
      v1:
        enabled: false
      v2:
        enabled: true
        metadataExchange: {}
        prometheus:
          enabled: true
        stackdriver:
          enabled: false
          logging: false
          monitoring: false
          topology: false
          configOverride: {}
    mixer:
      adapters:
        stdio:
          enabled: false
          outputAsJson: false
        prometheus:
          enabled: true
          metricsExpiryDuration: 10m
        kubernetesenv:
          enabled: true
        stackdriver:
          enabled: false
          auth:
            appCredentials: false
            apiKey: ""
            serviceAccountPath: ""
          tracer:
            enabled: false
            sampleProbability: 1
        useAdapterCRDs: false

      policy:
        autoscaleEnabled: true
        image: mixer
        sessionAffinityEnabled: false
        adapters:
          kubernetesenv:
            enabled: true
          useAdapterCRDs: false

    gateways:
      istio-egressgateway:
        zvpn: {}
        env:
          # Needed to route traffic via egress gateway if desired.
          ISTIO_META_REQUESTED_NETWORK_VIEW: "external"
        autoscaleEnabled: true
        type: ClusterIP
        name: istio-egressgateway

      istio-ingressgateway:
        autoscaleEnabled: true
        applicationPorts: ""
        debug: info
        domain: ""
        type: LoadBalancer
        name: istio-ingressgateway
        zvpn: {}
        env: {}

    sidecarInjectorWebhook:
      enableNamespacesByDefault: false
      rewriteAppHTTPProbe: true
      injectLabel: istio-injection
      objectSelector:
        enabled: false
        autoInject: true

    prometheus:
      hub: docker.io/prom
      tag: v2.15.1
      scrapeInterval: 15s
      contextPath: /prometheus

      security:
        enabled: true
      nodeSelector: {}
      tolerations: []
      podAntiAffinityLabelSelector: []
      podAntiAffinityTermLabelSelector: []
      provisionPrometheusCert: true

    grafana:
      image:
        repository: grafana/grafana
        tag: 6.7.4
      persist: false
      storageClassName: ""
      accessMode: ReadWriteMany
      contextPath: /grafana
      service:
        annotations: {}
        name: http
        type: ClusterIP
        externalPort: 3000
        loadBalancerIP:
        loadBalancerSourceRanges:
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
            - name: 'istio'
              orgId: 1
              folder: 'istio'
              type: file
              disableDeletion: false
              options:
                path: /var/lib/grafana/dashboards/istio
      nodeSelector: {}
      tolerations: []
      podAntiAffinityLabelSelector: []
      podAntiAffinityTermLabelSelector: []
      env: {}
      envSecrets: {}

    tracing:
      provider: jaeger

    kiali:
      createDemoSecret: true
```

**Affected product area (please put an X in all that apply)**

[x] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

**Expected behavior**
volumeMount artemis should be added into grafana deployment

**Steps to reproduce the bug**

```
istioctl install -f istioOperator.yaml 
! addonComponents.grafana.enabled is deprecated; use the samples/addons/ deployments instead
! addonComponents.tracing.enabled is deprecated; use the samples/addons/ deployments instead
! addonComponents.kiali.enabled is deprecated; use the samples/addons/ deployments instead
! addonComponents.prometheus.enabled is deprecated; use the samples/addons/ deployments instead
✔ Istio core installed                                                                                                                                                         
✔ Istiod installed                                                                                                                                                             
✔ Egress gateways installed                                                                                                                                                    
✔ Ingress gateways installed                                                                                                                                                   
✔ Addons installed                                                                                                                                                             
✔ Installation complete                                                       
```

Only `configMap` is added:

```
      - configMap:
          defaultMode: 420
          name: istio-grafana-configuration-dashboards-artemis-dashboard
        name: artemis
```

but not `volumeMount`

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
```
istioctl version
client version: 1.7.2
control plane version: 1.7.2
data plane version: 1.7.2 (18 proxies)
```

**How was Istio installed?**
Istio operator

**Comment by morvencao** [comment]
`K8sObjectOverlay` will always replace the **value** for corresponding **path**, so if you just want to replace the **volumes** and **volumeMounts**, you have to add the **volumes** and **volumeMounts** to the path of K8sObjectOverlay , so your example, the following iop spec works:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  components:
    base:
      enabled: true
    pilot:
      enabled: true
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
    egressGateways:
    - name: istio-egressgateway
      enabled: true
  addonComponents:
    prometheus:
      enabled: true
    grafana:
      enabled: true
      k8s:
        overlays:
          - apiVersion: apps/v1
            kind: Deployment
            name: grafana
            patches: 
            - path: spec.template.spec.containers.[name:grafana].volumeMounts
              value:
                - mountPath: /var/lib/grafana/dashboards/istio/artemis-dashboard.json
                  name: artemis
                  readOnly: true
                  subPath: artemis-dashboard.json
                - mountPath: /data/grafana
                  name: data
                - mountPath: /var/lib/grafana/dashboards/istio/istio-mesh-dashboard.json
                  name: dashboards-istio-istio-mesh-dashboard
                  readOnly: true
                  subPath: istio-mesh-dashboard.json
                - mountPath: /var/lib/grafana/dashboards/istio/istio-performance-dashboard.json
                  name: dashboards-istio-istio-performance-dashboard
                  readOnly: true
                  subPath: istio-performance-dashboard.json
                - mountPath: /var/lib/grafana/dashboards/istio/istio-service-dashboard.json
                  name: dashboards-istio-istio-service-dashboard
                  readOnly: true
                  subPath: istio-service-dashboard.json
                - mountPath: /var/lib/grafana/dashboards/istio/istio-workload-dashboard.json
                  name: dashboards-istio-istio-workload-dashboard
                  readOnly: true
                  subPath: istio-workload-dashboard.json
                - mountPath: /var/lib/grafana/dashboards/istio/mixer-dashboard.json
                  name: dashboards-istio-mixer-dashboard
                  readOnly: true
                  subPath: mixer-dashboard.json
                - mountPath: /var/lib/grafana/dashboards/istio/pilot-dashboard.json
                  name: dashboards-istio-pilot-dashboard
                  readOnly: true
                  subPath: pilot-dashboard.json
                - mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
                  name: config
                  subPath: datasources.yaml
                - mountPath: /etc/grafana/provisioning/dashboards/dashboardproviders.yaml
                  name: config
                  subPath: dashboardproviders.yaml
            - path: spec.template.spec.volumes
              value:
                - configMap:
                    defaultMode: 420
                    name: istio-grafana-configuration-dashboards-artemis-dashboard
                  name: artemis
                - configMap:
                    defaultMode: 420
                    name: istio-grafana
                  name: config
                - emptyDir: {}
                  name: data
                - configMap:
                    defaultMode: 420
                    name: istio-grafana-configuration-dashboards-istio-mesh-dashboard
                  name: dashboards-istio-istio-mesh-dashboard
                - configMap:
                    defaultMode: 420
                    name: istio-grafana-configuration-dashboards-istio-performance-dashboard
                  name: dashboards-istio-istio-performance-dashboard
                - configMap:
                    defaultMode: 420
                    name: istio-grafana-configuration-dashboards-istio-service-dashboard
                  name: dashboards-istio-istio-service-dashboard
                - configMap:
                    defaultMode: 420
                    name: istio-grafana-configuration-dashboards-istio-workload-dashboard
                  name: dashboards-istio-istio-workload-dashboard
                - configMap:
                    defaultMode: 420
                    name: istio-grafana-configuration-dashboards-mixer-dashboard
                  name: dashboards-istio-mixer-dashboard
                - configMap:
                    defaultMode: 420
                    name: istio-grafana-configuration-dashboards-pilot-dashboard
                  name: dashboards-istio-pilot-dashboard      
  values:
    prometheus:
      hub: docker.io/prom
      tag: v2.15.1
      scrapeInterval: 15s
      contextPath: /prometheus

      security:
        enabled: true
      nodeSelector: {}
      tolerations: []
      podAntiAffinityLabelSelector: []
      podAntiAffinityTermLabelSelector: []
      provisionPrometheusCert: true

    grafana:
      image:
        repository: grafana/grafana
        tag: 6.7.4
      persist: false
      storageClassName: ""
      accessMode: ReadWriteMany
      contextPath: /grafana
      service:
        annotations: {}
        name: http
        type: ClusterIP
        externalPort: 3000
        loadBalancerIP:
        loadBalancerSourceRanges:
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
            - name: 'istio'
              orgId: 1
              folder: 'istio'
              type: file
              disableDeletion: false
              options:
                path: /var/lib/grafana/dashboards/istio
      nodeSelector: {}
      tolerations: []
      podAntiAffinityLabelSelector: []
      podAntiAffinityTermLabelSelector: []
      env: {}
      envSecrets: {}
```

**Comment by y0zg** [comment]
Thank you, it works, indeed!
And if I want to **add** only volume/volumeMounts into the existing Deployment, what would be the config look like?

**Comment by morvencao** [comment]
@y0zg Then you have to specify the index for each changed volume/volumeMount in the path.

**Comment by y0zg** [comment]
**replace** solution is fine but probably I miss something with **add** , that's the reason why I tried to use `value: |` before


```
      k8s:
        overlays:
          - apiVersion: apps/v1
            kind: Deployment
            name: grafana
            patches: 
            - path: spec.template.spec.containers.[name:grafana].volumeMounts[0]
              value:
                - mountPath: /var/lib/grafana/dashboards/istio/blackbox-exporter.json
                  name: grafana-extra-dashboards
                  readOnly: true
            - path: spec.template.spec.volumes[0]
              value: 
                - configMap:
                    defaultMode: 420
                    name: grafana-extra-dashboards
                  name: grafana-extra-dashboards
```

Error:
```
istioctl install -f istioOperator.yaml 
! addonComponents.grafana.enabled is deprecated; use the samples/addons/ deployments instead
! addonComponents.tracing.enabled is deprecated; use the samples/addons/ deployments instead
! addonComponents.kiali.enabled is deprecated; use the samples/addons/ deployments instead
! addonComponents.prometheus.enabled is deprecated; use the samples/addons/ deployments instead
✔ Istio core installed                                                                                                                                                         
✔ Istiod installed                                                                                                                                                             
✔ Egress gateways installed                                                                                                                                                    
✔ Ingress gateways installed                                                                                                                                                   
- Processing resources for Addons.                                                                                                                                             2020-09-28T10:20:45.742093Z	error	installer	Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.VolumeMounts: []v1.VolumeMount: readObjectStart: expect { or n, but found [, error found in #10 byte of ...|Mounts":[[{"mountPat|..., bigger context ...|rces":{"requests":{"cpu":"10m"}},"volumeMounts":[[{"mountPath":"/var/lib/grafana/dashboards/istio/bl|...
✘ Addons encountered an error: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.VolumeMounts: []v1.VolumeMount: readObjectStart: expect { or n, but found [, error found in #10 byte of ...|Mounts":[[{"mountPat|..., bigger context ...|rces":{"requests":{"cpu":"10m"}},"volumeMounts":[[{"mountPath":"/var/lib/grafana/dashboards/istio/bl|...
- Pruning removed resources                                                                                                                                                    Error: failed to install manifests: errors occurred during operation

```

**Comment by morvencao** [comment]
@y0zg You don't need to add `-` in value any more, the following spec will be working:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  addonComponents:
    prometheus:
      enabled: true
    grafana:
      enabled: true
      k8s:
        overlays:
          - apiVersion: apps/v1
            kind: Deployment
            name: grafana
            patches:
            - path: spec.template.spec.containers.[name:grafana].volumeMounts[0]
              value:
                mountPath: /var/lib/grafana/dashboards/istio/blackbox-exporter.json
                name: grafana-extra-dashboards
                readOnly: true
            - path: spec.template.spec.volumes[0]
              value:
                configMap:
                  defaultMode: 420
                  name: grafana-extra-dashboards
                name: grafana-extra-dashboards
```

**Comment by y0zg** [comment]
Thank you!

I appreciate if you answer to the last question and then we can close this issue (answer indeed would be helpful for others!)

I'm checking an option to replace default prometheus configmap and this example works for me:

```
        - apiVersion: apps/v1    
            kind: ConfigMap
            name: prometheus
            patches: 
            - path: data
              value: |
                    prometheus.yml: |-
                      global:
                        scrape_interval: 15s
                  
                      rule_files:
                        - /etc/prometheus/prometheus.rules
                      alerting:
                        alertmanagers:
                        - scheme: http
                          static_configs:
                          - targets:
                            - "alertmanager.istio-system.svc:9093"
                  
                      scrape_configs:
                  
                      - job_name: 'istio-mesh'
                        kubernetes_sd_configs:
                        - role: endpoints
                          namespaces:
                            names:
                            - istio-system
                  
                        relabel_configs:
                        - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
                          action: keep
                          regex: istio-telemetry;prometheus
                  
```

but have issue with this example:

```
          - apiVersion: apps/v1    
            kind: ConfigMap
            name: prometheus
            patches: 
            - path: data
              value: |
                    prometheus.rules: |-
                      groups:
                      - name: common alerts
                        rules:
                        - alert: EndpointDown
                          expr: probe_success == 0
                          for: 10s
                          labels:
                            severity: "critical"
                          annotations:
                            summary: "Endpoint {{ $labels.instance }} down"
```

```
istioctl install -f IstioOperator.yaml 
! addonComponents.grafana.enabled is deprecated; use the samples/addons/ deployments instead
! addonComponents.tracing.enabled is deprecated; use the samples/addons/ deployments instead
! addonComponents.kiali.enabled is deprecated; use the samples/addons/ deployments instead
! addonComponents.prometheus.enabled is deprecated; use the samples/addons/ deployments instead
Error: failed to install manifests: template: :176: undefined variable "$labels"
```

I tried different escape options for `$` like below
- `                            summary: "Endpoint {{ $$labels.instance }} down"`
```
Error: failed to install manifests: template: :176: unexpected bad character U+0024 '$' in command
```
- `                            summary: "Endpoint {{ {{ $labels.instance }}  }} down"`
```
Error: failed to install manifests: template: :176: unexpected "{" in command
```
- `                            summary: 'Endpoint {{ $$labels.instance }} down'`
```
Error: failed to install manifests: template: :176: unexpected bad character U+0024 '$' in command
```

**Comment by linhuatan** [comment]
@morvencao  if  @y0zg  want to just add a volumeMount, he should choose a big index that doesn't exist, hence create the new leaf, or else it will replace the volumeMount at index `0`,  this one should work:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  addonComponents:
    prometheus:
      enabled: true
    grafana:
      enabled: true
      k8s:
        overlays:
          - apiVersion: apps/v1
            kind: Deployment
            name: grafana
            patches:
            - path: spec.template.spec.containers.[name:grafana].volumeMounts[10000] # big index to create the new leaf 
              value:
                mountPath: /var/lib/grafana/dashboards/istio/blackbox-exporter.json
                name: grafana-extra-dashboards
                readOnly: true
            - path: spec.template.spec.volumes[10000] # big index to create the new leaf  
              value:
                configMap:
                  defaultMode: 420
                  name: grafana-extra-dashboards
                name: grafana-extra-dashboards
```
