### ISSUE TITLE
istioctl upgrade from 1.4.10 to 1.5.10 fails with "Asset charts/security/certmanager not found"

### ISSUE THREAD

**Issue by Heraclitus** [istio/istio#27564]
**Bug description**
I have a successful and functioning installation of Istio 1.4.10 running in KIND. It was created by way of istioctl (1.4.10) and personalized IstioControlPlane CRD. 
I'm trying to upgrade to 1.5.10.
I get his error when running istioctl upgrade
```
2020-09-26T14:28:02.080363Z	info	Error: failed to apply the Istio Control Plane specs. Error: failed to generate manifest: Asset charts/security/certmanager not found

Error: failed to apply the Istio Control Plane specs. Error: failed to generate manifest: Asset charts/security/certmanager not found
```
more details below...

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Successful upgrade from 1.4.10 to 1.5.10

**Steps to reproduce the bug**
Get your KIND cluster running with some nodes, I happen to have two nodes.
```
docker ps 
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                                                                    NAMES
971f066271b8        kindest/node:v1.18.2   "/usr/local/bin/entr…"   8 minutes ago       Up 8 minutes                                                                                 kind-worker
4de640966873        kindest/node:v1.18.2   "/usr/local/bin/entr…"   8 minutes ago       Up 8 minutes        0.0.0.0:8080->80/tcp, 0.0.0.0:8443->443/tcp, 127.0.0.1:34577->6443/tcp   kind-control-plane
```

I supply istioctl with an IstioControlPlane crd (as per documentation https://istio.io/v1.5/docs/setup/upgrade/istioctl-upgrade/#upgrade-steps which states if you installed istio with IstioControlPlane you should supply it to istioctl for upgrade )
```
If you installed Istio using the -f flag, for example istioctl manifest apply -f <IstioControlPlane-custom-resource-definition-file>, then you must provide the same -f flag value to the istioctl upgrade command.
```
I use this command... 
```
~/Downloads/istio-1.5.10/bin/istioctl upgrade -f /depot/localkube/terraform/istio-manifest.yaml --force --log_output_level debug
```
the `--force` option is necessary as the istioctl upgrade command fails without it.

Prior to failure of upgade I am greeted with the following message.
```
user@user-lu:/depot/user/localkube$ ~/Downloads/istio-1.5.10/bin/istioctl upgrade -f /depot/user/localkube/terraform/istio-manifest.yaml --force --log_output_level debug
2020-09-26T14:26:23.220015Z	debug	Config loaded from file: /depot/user/localkube/kind/kubeconfig.yaml

proto: tag has too few fields: "-"
2020-09-26T14:26:23.255771Z	info	installer	ReadProfileYAML for profile name: default
2020-09-26T14:26:23.255902Z	info	installer	Loading values from compiled in VFS at path profiles/default.yaml
Control Plane - citadel pod - istio-citadel-5f4959969-wtpdv - version: 1.4.10
Control Plane - galley pod - istio-galley-6bcf8f95b9-crxbx - version: 1.4.10
Control Plane - pilot pod - istio-pilot-854cd475fb-tn2rp - version: 1.4.10
Control Plane - policy pod - istio-policy-7845546488-v9bz7 - version: 1.4.10
Control Plane - sidecar-injector pod - istio-sidecar-injector-797d656c8f-cxb96 - version: 1.4.10
Control Plane - telemetry pod - istio-telemetry-6b796d944d-k5rwh - version: 1.4.10

Upgrade version check passed: 1.4.10 -> 1.5.10.

2020-09-26T14:26:32.143431Z	info	installer	ReadProfileYAML for profile name: /tmp/istio-install-packages/istio-1.4.10/install/kubernetes/operator/profiles/default.yaml
2020-09-26T14:26:32.143547Z	info	installer	Loading values from local filesystem at path /tmp/istio-install-packages/istio-1.4.10/install/kubernetes/operator/profiles/default.yaml
Upgrade check: Warning!!! The following IOPS will be changed as part of upgrade. Please double check they are correct:
addonComponents:
  grafana:
    k8s: -> map[replicaCount:1]
  istiocoredns: -> map[enabled:false]
  kiali:
    enabled: false -> true
    k8s: -> map[replicaCount:1]
  prometheus:
    k8s: -> map[replicaCount:1]
  tracing:
    enabled: false -> true
components:
  base: -> map[enabled:true]
  egressGateways:
    '[#0]':
      k8s: map[hpaSpec:map[maxReplicas:5 metrics:[map[resource:map[name:cpu targetAverageUtilization:80]
        type:Resource]] minReplicas:1 scaleTargetRef:map[apiVersion:apps/v1 kind:Deployment
        name:istio-egressgateway]] resources:map[limits:map[cpu:2000m memory:1024Mi]
        requests:map[cpu:100m memory:128Mi]] strategy:map[rollingUpdate:map[maxSurge:100%
        maxUnavailable:25%]]] ->
  ingressGateways:
    '[#0]':
      enabled: true -> false
      k8s: map[hpaSpec:map[maxReplicas:5 metrics:[map[resource:map[name:cpu targetAverageUtilization:80]
        type:Resource]] minReplicas:1 scaleTargetRef:map[apiVersion:apps/v1 kind:Deployment
        name:istio-ingressgateway]] resources:map[limits:map[cpu:2000m memory:1024Mi]
        requests:map[cpu:100m memory:128Mi]] strategy:map[rollingUpdate:map[maxSurge:100%
        maxUnavailable:25%]]] ->
  pilot:
    k8s:
      env:
        '[?->0]': -> map[name:PILOT_ENABLE_FALLTHROUGH_ROUTE value:1]
        '[0->?]': map[name:POD_NAME valueFrom:map[fieldRef:map[apiVersion:v1 fieldPath:metadata.name]]]
          ->
        '[1->?]': map[name:POD_NAMESPACE valueFrom:map[fieldRef:map[apiVersion:v1
          fieldPath:metadata.namespace]]] ->
      hpaSpec: map[maxReplicas:5 metrics:[map[resource:map[name:cpu targetAverageUtilization:80]
        type:Resource]] minReplicas:1 scaleTargetRef:map[apiVersion:apps/v1 kind:Deployment
        name:istio-pilot]] ->
      readinessProbe:
        periodSeconds: 30 -> 5
installPackagePath: /tmp/istio-install-packages/istio-1.4.10/install/kubernetes/operator
  ->
values:
  certmanager: map[hub:quay.io/jetstack image:cert-manager-controller tag:v0.6.2]
    ->
  gateways:
    istio-egressgateway:
      env: map[ISTIO_META_ROUTER_MODE:sni-dnat] ->
      name: -> istio-egressgateway
      ports: '[map[name:http2 port:80] map[name:https port:443] map[name:tls port:15443
        targetPort:15443]] ->'
      zvpn: map[enabled:true suffix:global] ->
    istio-ingressgateway:
      env: map[ISTIO_META_ROUTER_MODE:sni-dnat] ->
      meshExpansionPorts:
        '[?->1]': -> map[name:tcp-istiod port:15012 targetPort:15012]
      name: -> istio-ingressgateway
      ports: '[map[name:status-port port:15020 targetPort:15020] map[name:http2 port:80
        targetPort:80] map[name:https port:443] map[name:kiali port:15029 targetPort:15029]
        map[name:prometheus port:15030 targetPort:15030] map[name:grafana port:15031
        targetPort:15031] map[name:tracing port:15032 targetPort:15032] map[name:tls
        port:15443 targetPort:15443]] ->'
      zvpn:
        enabled: true -> false
  global:
    istioNamespace: -> istio-system
    istiod: -> map[enabled:true]
    jwtPolicy: -> third-party-jwt
    mountMtlsCerts: -> false
    mtls:
      auto: false -> true
    pilotCertProvider: -> istiod
    sts: -> map[servicePort:0]
  grafana:
    image:
      tag: 6.4.3 -> 6.7.4
    replicaCount: 1 ->
  istiocoredns:
    enabled: false ->
  kiali:
    dashboard:
      grafanaInClusterURL: -> http://grafana:3000
      jaegerInClusterURL: -> http://tracing/jaeger
    replicaCount: 1 ->
  mixer:
    telemetry:
      useMCP: true ->
  pilot:
    ingress:
      ingressControllerMode: OFF -> STRICT
    useMCP: true ->
  prometheus:
    provisionPrometheusCert: -> true
    replicaCount: 1 ->
    tag: v2.12.0 -> v2.15.1
  security:
    trustDomain: cluster.local ->
  sidecarInjectorWebhook:
    rewriteAppHTTPProbe: false -> true
  telemetry:
    v1:
      enabled: true -> false
    v2:
      enabled: false -> true
  tracing:
    jaeger:
      tag: 1.14 -> 1.16

Confirm to proceed [y/N]? y
2020-09-26T14:28:01.700552Z	info	Running the following hooks which match source->target versions 1.4.10->1.5.10: istio.io/istio/operator/pkg/hooks.checkInitCrdJobs
2020-09-26T14:28:01.700636Z	info	Running hook istio.io/istio/operator/pkg/hooks.checkInitCrdJobs
2020-09-26T14:28:01.757251Z	info	installer	ReadProfileYAML for profile name: default
2020-09-26T14:28:01.757618Z	info	installer	Loading values from compiled in VFS at path profiles/default.yaml
Detected that your cluster does not support third party JWT authentication. Falling back to less secure first party JWT. See https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens for details.
2020-09-26T14:28:01.835151Z	info	installer	Applying Cluster specific settings: spec:
  values:
    global:
      jwtPolicy: first-party-jwt

2020-09-26T14:28:02.080363Z	info	Error: failed to apply the Istio Control Plane specs. Error: failed to generate manifest: Asset charts/security/certmanager not found

Error: failed to apply the Istio Control Plane specs. Error: failed to generate manifest: Asset charts/security/certmanager not found
```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
Istioctl binary for upgrade 
`1.5.10`

Istioctl currently installed below: 
```
./terraform/istio-1.4.10/bin/istioctl version 
client version: 1.4.10
control plane version: 1.4.10
data plane version: 1.4.10 (1 proxies)
```
helm versions
```
helm version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}

```

Kubectl Version
```
kubectl version --short
Client Version: v1.18.8
```

**How was Istio installed?**
`./istio-1.4.10/bin/istioctl manifest apply -f ./istio-manifest.yaml -w --readiness-timeout 60s`
the contents of that `./istio-manifest.yaml` file are ...
```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  creationTimestamp: null
spec:
  defaultNamespace: istio-system
  autoInjection:
    components:
      injector:
        enabled: true
    enabled: true
  configManagement:
    components:
      galley:
        enabled: true
    enabled: true
  gateways:
    components:
      egressGateway:
        enabled: false
      ingressGateway:
        enabled: false
    enabled: false
  policy:
    components:
      policy:
        enabled: true
    enabled: true
  security:
    components:
      certManager:
        enabled: false
      citadel:
        enabled: true
      nodeAgent:
        enabled: false
    enabled: true
  telemetry:
    components:
      telemetry:
        enabled: true
    enabled: true
  trafficManagement:
    components:
      pilot:
        enabled: true
        k8s:
          env:
            - name: PILOT_ENABLE_FALLTHROUGH_ROUTE
              value: "1"
    enabled: true
  values:
    global:
      proxy:
        accessLogFile: "/dev/stdout"
        accessLogEncoding: JSON
        envoyStatsd:
          enabled: false
        concurrency: 1
      useMCP: false
      outboundTrafficPolicy:
        mode: ALLOW_ANY
    pilot:
      sidecar: false
      traceSampling: 100
    prometheus:
      enabled: true
      retention: 7d
    tracing:
      enabled: true
    kiali:
      enabled: true
    grafana:
      enabled: false
```

**Environment where bug was observed (cloud vendor, OS, etc)**
Linux VM w/KIND installed 
```
uname -a
Linux myworkstation-lu 5.3.0-64-generic #58-Ubuntu SMP Fri Jul 10 19:33:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
