### ISSUE TITLE
Kibana is not accessible using Virtual service and gateway

### ISSUE THREAD

**Issue by aii-ssvinoth22** [istio/istio#27571]
- [ ] (NOTE: This is used to report product bugs:

  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
I've install ELK and I was using Nginx ingress controller,
I was using annotation for SSL redirect
```
nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
nginx.ingress.kubernetes.io/ssl-redirect: "true"
nginx.ingress.kubernetes.io/ssl-passthrough: "true"
```
Which is working fine.
Issues is on how I configure to access SSL redirect in istio.
I've setup gateway and vs, but getting SSL redirect error

```
**vs file**
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kibana-vs
spec:
  hosts:
  - kibana.example.com
  gateways:
  - kibana-gateway
  http:
    - name: "kibana-scan-route"
      route:
      - destination:
          host: kibana-kibana
          port:
            number: 5601`
---
**gateway file**

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: kibana-cert
  namespace: istio-system
spec:
  secretName: kibana-cert
  issuerRef:
    name: letsencrypt-prod
  dnsNames:
  - kibana.example.com
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kibana-gateway
  namespace: logging
spec:
  selector:
    istio: aii-public-ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: true
    hosts:
    - kibana.example.com
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
            #httpsRedirect: true
      mode: SIMPLE
      credentialName: kibana-cert # This should match the Certificate secretName
    hosts:
    - kibana.example.com
```
when i access in browser got below error
`upstream connect error or disconnect/reset before headers. reset reason: connection termination`

kibana logs

```
"tags":["connection","client","error"],"pid":7,"level":"er │
│ ror","error":{"message":"140191226451840:error:1408F09C:SSL routines:ssl3_get_record:http request:../deps/open │
│ ssl/openssl/ssl/record/ssl3_record.c:322:\n","name":"Error","stack":"Error: 140191226451840:error:1408F09C:SSL │
│  routines:ssl3_get_record:http request:../deps/openssl/openssl/ssl/record/ssl3_record.c:322:\n"},"message":"14 │
│ 0191226451840:error:1408F09C:SSL routines:ssl3_get_record:http request:../deps/openssl/openssl/ssl/record/ssl3 │
│ _record.c:322:\n"}`
```
**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
```
istioctl version --remote
client version: 1.7.2
control plane version: 1.7.2
data plane version: 1.7.2 (9 proxies)
```
`kubectl version --short
Client Version: v1.19.1
Server Version: v1.17.9-eks-4c6976`
**How was Istio installed?**
https://istio.io/latest/docs/setup/install/istioctl/

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
