### ISSUE TITLE
[istio-operator] operator fails to reconcile istiod's hpaSpec correctly

### ISSUE THREAD

**Issue by StefanCenusa** [istio/istio#27581]
**Bug description**
I am using latest istioctl version (1.7.2) to setup a new istio install on my kubernetes clusters. I've been encountering issues with istio operator randomly updating  the hpa spec of istiod to defaults (min 1, max 5) although I've set something different in the IstioOperator CR.


[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure



**Expected behavior**
The hpa spec of the istiod deployment to remain in sync with the spec defined on IstioOperator custom resource

**Steps to reproduce the bug**
I have the following IstioOperator spec:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
  namespace: istio-system
spec:
  profile: default
  addonComponents:
    prometheus:
      enabled: false
  components:
    base:
      enabled: true
    pilot:
      k8s:
        resources:
          requests:
            cpu: "1"
            memory: 1Gi
          limits:
            cpu: "2"
            memory: 2Gi
        hpaSpec:
          maxReplicas: 2
          minReplicas: 2
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      istio: pilot
                  topologyKey: kubernetes.io/hostname
                weight: 100
    ingressGateways:
      - enabled: false
        name: istio-ingressgateway
  hub: docker.io/istio
  meshConfig:
    defaultConfig:
      concurrency: 2
    enablePrometheusMerge: false
    enableTracing: false
    enableAutoMtls: false
    trustDomain: <REDACTED>
    disableReportBatch: true
  tag: 1.7.2
  values:
    global:
      proxy:
        clusterDomain: <REDACTED>
      meshID: <REDACTED>
      trustDomain: <REDACTED>
    pilot:
      traceSampling: 0
```
This is the current hpa status:

```
➜ kubectl get hpa
NAME     REFERENCE           TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
istiod   Deployment/istiod   19%/80%   1         5         1          10d
```

although this is the current IstioOperator status (spec is the same as above in kubernetes too):
```
status:
  componentStatus:
    Base:
      status: HEALTHY
    Pilot:
      status: HEALTHY
  status: HEALTHY
```
If I try to re-apply the IstioOperator cr:
```
➜ kubectl apply -f istio.yaml
istiooperator.install.istio.io/istio unchanged
```
but if I am using `istioctl upgrade` I get the following:
```
➜ istioctl upgrade -f istio.yaml 
2020-09-28T09:53:52.116050Z     info    proto: tag has too few fields: "-"
Control Plane - pilot pod - istiod-7c5fc49bd5-ldkzl - version: 1.7.2
Control Plane - pilot pod - istiod-7c5fc49bd5-vtt58 - version: 1.7.2
Control Plane - pilot pod - istiod-7c5fc49bd5-zfzsb - version: 1.7.2

Upgrade version check passed: 1.7.2 -> 1.7.2.

Upgrade check: Warning!!! The following IOPS will be changed as part of upgrade. Please double check they are correct:
addonComponents:
  prometheus: -> map[enabled:false]
components:
  ingressGateways:
    '[#0]':
      enabled: true -> false
  pilot:
    k8s:
      affinity: -> map[podAntiAffinity:map[preferredDuringSchedulingIgnoredDuringExecution:[map[podAffinityTerm:map[labelSelector:map[matchLabels:map[istio:pilot]] topologyKey:kubernetes.io/hostname] weight:100]]]]
      hpaSpec: -> map[maxReplicas:2 minReplicas:2]
      resources: -> map[limits:map[cpu:2 memory:2Gi] requests:map[cpu:1 memory:1Gi]]
installPackagePath: /var/folders/rt/y2m1glz501g_wbyfm2_0lrf40000gn/T/istio-install-packages/istio-1.7.2/manifests ->

Confirm to proceed [y/N]? 
```
If I proceed, this happens:

```
✔ Istio core installed                                                                                                                                                                                                                    
✔ Istiod installed                                                                                                                                                                                                                        
✔ Installation complete                                                                                                                                                                                                                   ..........
Upgrade rollout completed. All Istio control plane pods are running on the target version.


Control Plane - pilot pod - istiod-7c5fc49bd5-5ssw7 - version: 1.7.2
Control Plane - pilot pod - istiod-7c5fc49bd5-8zlrr - version: 1.7.2
Control Plane - pilot pod - istiod-7c5fc49bd5-ldkzl - version: 1.7.2

Success. Now the Istio control plane is running at version 1.7.2.

To upgrade the Istio data plane, you will need to re-inject it.
If you’re using automatic sidecar injection, you can upgrade the sidecar by doing a rolling update for all the pods:
    kubectl rollout restart deployment --namespace <namespace with auto injection>
If you’re using manual injection, you can upgrade the sidecar by executing:
    kubectl apply -f < (istioctl kube-inject -f <original application deployment yaml>)
```
and now, the hpa spec is correct
```
➜ kubectl get hpa
NAME     REFERENCE           TARGETS    MINPODS   MAXPODS   REPLICAS   AGE
istiod   Deployment/istiod   199%/80%   2         2         2          10d
```
However, if update de IstioOperator cr with a hpaSpec value - min 3, max 3 for example -  the hpa spec changes to default - min 1, max 5 - then to the desired state:
```
➜ kubectl get hpa
NAME     REFERENCE           TARGETS    MINPODS   MAXPODS   REPLICAS   AGE
istiod   Deployment/istiod   199%/80%   1         5         4          10d

// after a few seconds

➜ kubectl get hpa
NAME     REFERENCE           TARGETS    MINPODS   MAXPODS   REPLICAS   AGE
istiod   Deployment/istiod   200%/80%   3         3         3          10d
```
and after some time or changes (couldn't really reproduce) it gets back to min 1, max 5 (values I never set explicitly on the IstioOperator cr) - it might be some race condition.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
```
➜ istioctl version --remote
client version: 1.7.2
control plane version: 1.7.2
data plane version: 1.7.2 (1329 proxies)
```
**How was Istio installed?**
istioctl & istio operator

**Environment where bug was observed (cloud vendor, OS, etc)**
Aws, kops k8s cluster
