### ISSUE TITLE
Pod fails to start when injected with istio-cni on Azure AKS with Kubenet networking (Istio 1.7.2)

### ISSUE THREAD

**Issue by anyname2** [istio/istio#27591]
**Bug description**
When istio is installed with `cni` enabled on **Azure AKS** cluster with **Kubenet (Basic)** networking, when pod is injected with istio containers, istio-validation fails:
```log
Error connecting to 127.0.0.6:15002: dial tcp 127.0.0.1:0->127.0.0.6:15002: connect: connection refused
```
If `repair-cni` is enabled, pod is constantly beeing deleted and recreated.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Pod with injected istio container successfully starts on Azure AKS with Kubenet networking.

**Steps to reproduce the bug**
1. Create Azure AKS cluster with Kubenet (basic) networking
2. Install istio using `istioctl install -f` with the following config:
    ```yaml
    apiVersion: install.istio.io/v1alpha1
    kind: IstioOperator
    spec:
      profile: default
      tag: 1.7.2-distroless
      components:
        cni:
          enabled: true
        ingressGateways:
          - enabled: false
            name: istio-ingressgateway
      values:
        cni:
          excludeNamespaces:
          - istio-system
          - kube-system
          - kube-public
          - kube-node-lease
    ```
3. Add `istio-injection: enabled` label to a namespace
4. Create a deployment in the namespace

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
* `istioctl version --remote`
    ```bash
    client version: 1.7.2
    control plane version: 1.7.2
    data plane version: 1.7.2 (7 proxies)
    ```
* `kubectl version --short`
    ```bash
    Client Version: v1.18.9
    Server Version: v1.18.8
    ```

**How was Istio installed?**
`istioctl install` (see reproduction step 2 for details)

**Environment where bug was observed (cloud vendor, OS, etc)**
* Cloud: Azure AKS
* Networking: Kubenet (basic)
* OS: `Ubuntu 18.04.5 LTS`
* Kernel: `5.4.0-1026-azure`
* Container Runtime: `docker://19.3.12`
* [istio-dump.tar.gz](https://github.com/istio/istio/files/5293724/istio-dump.tar.gz)
