### ISSUE TITLE
Egress gateway for HTTPS resources does not establish MTLS between istio-proxy and egress gateway

### ISSUE THREAD

**Issue by AlexKulbiy** [istio/istio#27616]
**Bug description**

I'm using istio 1.6.9 and trying to setup Egress for HTTPS traffic using the [guide](https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/#egress-gateway-for-https-traffic). 

In my use case I have multiple applications going through egress gateway, but I only want to allow certain applications to access certain external resources. E.g. I have `svc A`, which uses egress gateway to access https://google.com and `svc B`, which uses egress gateway to access https://cnn.com. In the same time `svc A` should not be able to access https://cnn.com and `svc B` should not be able to access https://google.com.

From what I found, I could use `AuthorizationPolicy` and limit access based on the namespace or a service account my `svc` pods are using. However, that requires MTLS between my `svc` pods and the egress gateway. I'm trying to set this up by adding `ISTIO_MUTUAL` traffic policy on the destination rule like this:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-google
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
    - name: google
      trafficPolicy:
        tls:
          mode: ISTIO_MUTUAL
          sni: google.com
```

Using MTLS in this case I would expect that istio proxy will establish TLS session with egress gateway and egress gateway in turn will establish a TLS session with google.com. This way traffic external to mesh between google.com and egress will be using a certificate signed by google CA and internal mesh traffic will be using istio CA.

Looking at the traffic flow I see my proxy attempting to establish a TLS session with google.com. Egress proxy sends and receives traffic from google.com and passes it to my istio proxy "as is". Istio proxy at this point is rejecting TLS session as it's expecting MTLS being signed by our istio CA and instead it's getting a certificate signed by google's CA.

The example of exchange can be seen in an attached pcap 
[pcap.zip](https://github.com/istio/istio/files/5299085/pcap.zip)

Is there anything I'm doing wrong in this case or is this setup not working as expected?

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

MTLS session will be established between istio-proxy and egress gateway as I've explained above

**Steps to reproduce the bug**

1. Follow steps in [Egress gateway for HTTPS traffic guide](https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/#egress-gateway-for-https-traffic);
2. Modify `DestinationRule` adding the following `trafficPolicy` as shown in the description above;
3. Try to `curl https://google.com` from the source pod behind the istio proxy.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used 
Helm)**

```
client version: 1.6.7
control plane version: 1.6.9
data plane version: 1.6.9 (45 proxies)
```

**How was Istio installed?**

using istio-operator

**Environment where bug was observed (cloud vendor, OS, etc)**

this is happening in our on-premises cluster, which is running CentOS.

**Comment by bianpengyuan** [comment]
The guide you linked will passthrough TLS request from the application at egressgateway. I think this is what you are looking for? https://istio.io/latest/docs/tasks/traffic-management/egress/egress-tls-origination/

**Comment by AlexKulbiy** [comment]
Hey @bianpengyuan , thanks for reaching out and sorry for the late reply. If I understand correctly how TLS origination works, I don't think that's an option for us. From the example, it looks like egress will upgrade an HTTP request to HTTPs. Some of our clients already perform HTTPs requests to external services and ideally we would like to avoid changes to the clients.

Basically, we have a way to work with the following scenarios:
* HTTP client <- mtls -> egress Gateway <-> HTTP server - this scenario is possible with egress gateway;
* HTTP client <- mtls -> egress Gateway <-> HTTPS server - this scenario is possible with egress TLS origination (or egress gateway with TLS origination);

The scenario I can't get to work is:
* HTTPS client <- mtls -> egress Gateway <-> HTTPS server

In this case TLS origination will not really work as this would mean that egress gateway needs to somehow supply a server's certificate to the HTTPS client. The way I can see HTTPS + mtls setup working is to wrap HTTPS session in mtls session. This definitely does not sound optimal, but I can't think of another way to achieve what we want.

**Comment by nickperry** [comment]
Istio auto mTLS does not seem to work from sidecars to egress gateways.

Add a DestinationRule like:
`apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: egress-gateway-mtls
  namespace: istio-system
spec:
  host: 'istio-egressgateway.istio-system.svc.cluster.local'
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
`

**Comment by AlexKulbiy** [comment]
I haven't added any DestinationRules aside from the one I've mentioned in the issue description for the `google` subset. Auto mTLS between sidecar and egress doesn't work for me. I was expecting the DestinationRule will enable exactly this part of mTLS manually. @nickperry - do you have the rule you've posted in addition to the mTLS for the subset or is this the only one that should work for all traffic to the gateway?

**Comment by nickperry** [comment]
I actually never got it to work with a subset historically. I need to try the current documented approach again on 1.7 and see if it works for me now.

Our full config to reach an external service with TLS origination and mTLS to get from the sidecar to the egress gateway looks like

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: originate-tls-for-foo-bar
  namespace: foo
spec:
  host: foo.bar
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 443
      tls:
        caCertificates: ""
        mode: SIMPLE

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
  name: foo
  namespace: default
spec:
  gateways:
  - mesh
  - istio-system/istio-egressgateway
  hosts:
  - foo.bar
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        port:
          number: 80
      weight: 100
  - match:
    - gateways:
      - istio-system/istio-egressgateway
      port: 80
    route:
    - destination:
        host: foo.bar
        port:
          number: 443
      weight: 100

apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: foo-bar
  namespace: default
spec:
  endpoints:
  - address: a.b.c.d
  hosts:
  - foo.bar
  location: MESH_EXTERNAL
  ports:
  - name: http-port
    number: 80
    protocol: HTTP
  - name: https-port-for-tls-origination
    number: 443
    protocol: HTTPS
  resolution: STATIC

apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: egress-gateway-mtls
  namespace: istio-system
spec:
  host: 'istio-egressgateway.istio-system.svc.cluster.local'
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

apiVersion: networking.istio.io/v1beta1
kind: Gateway
  name: istio-egressgateway
  namespace: istio-system
spec:
  selector:
    istio: egressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTPS
    tls:
      mode: ISTIO_MUTUAL
```
