### ISSUE TITLE
IstioOperator does not create Gateway since 1.6

### ISSUE THREAD

**Issue by qwazerty** [istio/istio#27622]
**Bug description**
We use `istioctl` and `IstioOperator` to deploy to our Kubernetes cluster.
In version 1.5.10, istio did create a Gateway in the cluster but that is not the case in 1.6.10 (nor 1.7).
I tried using `istioctl manifest generate` to reproduce this issue.

I did not find any mention of this change in the documentation nor upgrade procedure. Is this configuration still supported or is there a new official way to declare an ingress gateway?

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
```
# cat istio-test.yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioOperator
spec:
  profile: default
  components:
    ingressGateways:
    - enabled: true
```
```
# ~/istio-1.5.10/bin/istioctl manifest generate -f istio-test.yaml | grep '^kind: Gateway' -B2 -A10

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingressgateway
  namespace: istio-system
  labels:
    release: istio
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
```
```
# ~/istio-1.6.10/bin/istioctl manifest generate -f istio-test.yaml | grep '^kind: Gateway' -B2 -A10

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingressgateway
  namespace: istio-system
  labels:
    release: istio
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
# 
```

**Steps to reproduce the bug**
```
# cat istio-test.yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioOperator
spec:
  profile: default
  components:
    ingressGateways:
    - enabled: true
```
```
# ~/istio-1.6.10/bin/istioctl manifest generate -f istio-test.yaml | grep '^kind: Gateway' -B2 -A10
# echo $?
1
```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
```
# ~/istio-1.5.10/bin/istioctl version
client version: 1.5.10
# ~/istio-1.6.10/bin/istioctl version
client version: 1.6.10
```

**How was Istio installed?**
Not installed, only generating the manifest
