### ISSUE TITLE
Not able to load balance gRPC Client Request using Istio

### ISSUE THREAD

**Issue by safvankothawala** [istio/istio#27621]
I am unable to load balance the gRPC requests where my Client and Server applications are both Istio Injected.
**Istio Version:** 1.7.2

**Scenario:**
gRPC-Server is an Istio service having multiple Pods in Kubernetes Cluster.
gRPC-Client is another Istio service having single Pod in Kubernetes Cluster.
gRPC-Client calls gRPC-Server service using its Kubernetes ServiceName and ServicePort.
Virtual Service and Destination Rule is also created for gRPC-Server service.

**Expected Behavior:**
Request calls from gRPC-Client must land on all available gRPC-Server pods in round robin fashion.

**Actual Behavior:**
The request call every time lands on same gRPC-Server pod only.

Following is the gRPC-Server Service Yaml file:
[grpc-server-svc-yaml.txt](https://github.com/istio/istio.io/files/5299164/grpc-server-svc-yaml.txt)

Following is the gRPC-Server Virtual Service and Destination Rule file:
[grpc-server-vs-dr-yaml.txt](https://github.com/istio/istio.io/files/5299171/grpc-server-vs-dr-yaml.txt)

If I route the request via any other Envoy based application like Ambassador then load balancing is done perfectly.
As Istio is also based on Envoy, load balancing must also be done seamlessly.

**Comment by howardjohn** [comment]
This is in port 6565 right?

It looks like your subset labels and pod labels do not match.

**Comment by safvankothawala** [comment]
Yes, the port is 6565.
Can it work without creating Virtual Service and Destination Rule for gRPC-Server service?
I tried but in vain.

**Comment by howardjohn** [comment]
it should work without vs and Dr, but if you create invalid ones it may
make thing not work as expected

**Comment by safvankothawala** [comment]
Hello,
I recreated all the k8s artifacts and then it worked !!
I also applied timeout using VS/DR and it also worked fine.
Just to confirm, is it mandatory to make a gRPC-Server k8s svc a Headless Service or it can be a NodePort or ClusterIP service also?

**Comment by howardjohn** [comment]
It can be a clusterip as well. glad its working now!

**Comment by M-A-N-I-S-H-K** [comment]
Hi, I am observing this while trying to hit grpc, when I try to connect using `grpc-headless.default.svc.cluster.local:50051` it works but when I use route `grpc-headless.default.svc.cluster.local` it fails

``` 14 UNAVAILABLE: upstream connect error or disconnect/reset before headers. reset reason: connection failure
Error: 14 UNAVAILABLE: upstream connect error or disconnect/reset before headers. reset reason: connection failure
    at Object.exports.createStatusError (/usr/src/app/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/usr/src/app/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/usr/src/app/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/usr/src/app/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/usr/src/app/node_modules/grpc/src/client_interceptors.js:847:24)
```


here is my config  for virutal service and headless
```
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: route-grpc
spec:
  hosts:
  - grpc-headless.default.svc.cluster.local
  http:
  - name: "grpc"
    route:
    - destination:
        host: grpc-headless.default.svc.cluster.local
        subset: v1
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: destination-grpc
spec:
  host: grpc-headless.default.svc.cluster.local
  subsets:
  - name: v1
    labels:
      app: grpc-headless
      version: v1
---
```
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpc-headless
    version: v1
  name: grpc-headless
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: grpc
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
```
