### ISSUE TITLE
istio-ingressgateway as DaemonSet using istioctl

### ISSUE THREAD

**Issue by dolumberist** [istio/istio#27666]
**Describe the feature request**
It's already has been opened
https://github.com/istio/installer/pull/398
**Describe alternatives you've considered**
At the moment manual editing of YAML files are needed to have DaemonSet

[ ] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Additional context**
AWS Target groups sees nodes as "Unhealthy" if they do not have istio-ingressgateway pod running on them, manual editing is needed to split pods accross nodes, allowing to set kind Deployment ir DaemonSet for istio-ingressgateway with istioctl would limit possible human errors, less custom interaction with istio install.

**Comment by jhughes2112** [comment]
Yes, please.  Not being able to get source IP address easily causes a lot of trouble.  Istio supporting this mode out of the box would be incredibly helpful.

**Comment by tehleet** [comment]
any update?

**Comment by dolumberist** [comment]
Seems like the issue was ignored, anyway it is achievable with k8s overlays, leaving code snippet for reference

```YAML
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
      k8s:
        overlays:
        - kind: Deployment
          name: istio-ingressgateway
          patches:
            - path: kind
              value: DaemonSet
```

**Comment by mehyedes** [comment]
Would be great if that would also be possible for people who prefer using the helm chart instead of the operator
https://github.com/istio/istio/blob/master/manifests/charts/gateways/istio-ingress/templates/deployment.yaml

**Comment by mehyedes** [comment]
> Seems like the issue was ignored, anyway it is achievable with k8s overlays, leaving code snippet for reference
> 
> ```yaml
> apiVersion: install.istio.io/v1alpha1
> kind: IstioOperator
> spec:
>   components:
>     ingressGateways:
>     - enabled: true
>       name: istio-ingressgateway
>       k8s:
>         overlays:
>         - kind: Deployment
>           name: istio-ingressgateway
>           patches:
>             - path: kind
>               value: DaemonSet
> ```

For anyone who faced the issue that the Daemonset is not created, you'd also want to delete the `spec.strategy` config because it's not supported in DaemonSets:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
      k8s:
        overlays:
        - kind: Deployment
          name: istio-ingressgateway
          patches:
            - path: kind
              value: DaemonSet
            - path: spec.strategy
```
