### ISSUE TITLE
Istio stackdriver configuration looks to be dropping traces unexpectedly 

### ISSUE THREAD

**Issue by krubot-sky** [istio/istio#27729]
**Bug description**

Istio stackdriver integration looks to drop a lot of traces even when `traceSampling` is set to `100`. 

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Alls traces should be retained from the `istio-proxy` since variable `traceSampling` is set to `100`. 

**Steps to reproduce the bug**

I've got the following simple pod setup to expose an HTTP nginx endpoint service on my istio-injection enabled namespace:

```
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: nginx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
  labels:
    account: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: nginx
      containers:
      - name: nginx
        image: nginx:alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
```

When I getting logs from the istio-proxy you can see *x-b3-traceid* logs for when you curl this endpoint from another pod on the cluster i.e.

```
$ k logs nginx-66d89c74cb-fhfz9 istio-proxy -f | grep x-b3-traceid
'x-b3-traceid', '76efcb930e2818425629db7aa6f497cc'
'x-b3-traceid', '76efcb930e2818425629db7aa6f497cc'
```
However, when viewing stackdriver these traces seem to be missing:

![image](https://user-images.githubusercontent.com/56029308/95087284-667d5a00-0719-11eb-9156-76470c3bc053.png)

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

```
$ istioctl version --remote
client version: 1.7.0
control plane version: 1.6.7-2511ab8c8c59a203e77bb804846593c3690fcf4a
data plane version: 1.6.7 (5 proxies)
$ kubectl version --short
Client Version: v1.18.6
Server Version: v1.14.10-gke.46
```

**How was Istio installed?**

Using the istio operator with the following configuration:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: default
  namespace: istio-system
spec:
  addonComponents:
    grafana:
      enabled: false
    istiocoredns:
      enabled: false
    kiali:
      enabled: true
    prometheus:
      enabled: false
    tracing:
      enabled: true
  components:
    base:
      enabled: true
    citadel:
      enabled: true
    cni:
      enabled: false
    egressGateways:
    - enabled: false
    ingressGateways:
    - enabled: false
    istiodRemote:
      enabled: false
    pilot:
      enabled: true
    policy:
      enabled: true
    proxy:
      enabled: true
    telemetry:
      enabled: true
  hub: docker.io/istio
  tag: 1.6.7
  values:
    global:
      configValidation: true
      controlPlaneSecurityEnabled: true
      defaultResources:
        requests:
          cpu: 10m
      istioNamespace: istio-system
      istiod:
        enableAnalysis: true
        enabled: true
      logAsJson: true
      multiCluster:
        clusterName: pre-dev
        enabled: true
      operatorManageWebhooks: false
      pilotCertProvider: istiod
      logging:
        level: default:debug
      proxy:
        autoInject: enabled
        envoyStatsd:
          enabled: true
        image: proxyv2
        logLevel: debug
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        statusPort: 15020
        tracer: zipkin
      proxy_init:
        image: proxyv2
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 10Mi
      sds:
        token:
          aud: istio-ca
      sts:
        servicePort: 0
      tracer:
        zipkin:
          address: zipkin.istio-system.svc.cluster.local:9411
      useMCP: false
    kiali:
      dashboard:
        auth:
          strategy: anonymous
        grafanaInClusterURL: http://gf-grafana.monitoring.svc:3000
        jaegerInClusterURL: http://tracing/jaeger
        viewOnlyMode: true
      hub: quay.io/kiali
      prometheusAddr: http://po-promop-prometheus.monitoring.svc:9090
      tag: v1.22
    mixer:
      adapters:
        kubernetesenv:
          enabled: true
        prometheus:
          enabled: true
          metricsExpiryDuration: 10m
        stackdriver:
          auth:
            appCredentials: false
          enabled: true
          tracer:
            enabled: true
      policy:
        adapters:
          kubernetesenv:
            enabled: true
          useAdapterCRDs: false
        sessionAffinityEnabled: true
      telemetry:
        autoscaleEnabled: true
        image: mixer
        loadshedding:
          latencyThreshold: 100ms
          mode: enforce
        replicaCount: 1
        sessionAffinityEnabled: false
    pilot:
      autoscaleEnabled: true
      autoscaleMax: 5
      autoscaleMin: 1
      configMap: true
      configNamespace: istio-config
      enableProtocolSniffingForInbound: true
      enableProtocolSniffingForOutbound: true
      image: pilot
      policy:
        enabled: true
      replicaCount: 1
      traceSampling: 100
    sidecarInjectorWebhook:
      enableNamespacesByDefault: false
      injectLabel: istio-injection
      objectSelector:
        autoInject: true
        enabled: false
      rewriteAppHTTPProbe: true
    telemetry:
      enabled: true
      v1:
        enabled: true
      v2:
        enabled: false
        prometheus:
          enabled: true
        stackdriver:
          enabled: false
    tracing:
      enabled: true
      jaeger:
        hub: docker.io/jaegertracing
        persist: false
        tag: 1.16
      provider: jaeger
      service:
        externalPort: 9411
        name: http-query
        type: ClusterIP
```

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE cluster with kubernetes version 1.14
