### ISSUE TITLE
PodDisruptionBudget of istio-egressgateway does not match any pods

### ISSUE THREAD

**Issue by rmoesbergen** [istio/istio#27730]
**Bug description**
The PodDisruptionBudget create for the istio-egressgateway has invalid selectors, so it doesn't match any pods:

```
3m42s       Normal    NoPods                   poddisruptionbudget/istio-egressgateway       No matching pods found
```

PDB pod selector:
```
  selector:
    matchLabels:
      app: istio-egressgateway
      istio: egressgateway
      release: istio
```
Actual labels:
```
  labels:
    app: istio-egressgateway
    istio: egressgateway
```

The 'release: istio' label is not present on the pods.

[ ] Docs
[X] Installation
[ ] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
PDB's that match pods, so nodes can be properly drained.

**Steps to reproduce the bug**
1. Install istio egress gateway
2. Check PDB status / events

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
control plane version: 1.7.3

**How was Istio installed?**
using istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by morvencao** [comment]
Please append more info about the spec to install egressgateway.

**Comment by rmoesbergen** [comment]
Not sure what additional info you're looking for, but I think I found the cause:

In manifests/charts/gateways/istio-egress/templates/deployment.yaml, the release: istio label is only added if egress gateway is deployed in the 'istio-system' namespace. In our case we deploy into a different namespace ('istio-egress').
```
{{- if eq .Release.Namespace "istio-system"}}
        heritage: Tiller
        release: istio
        chart: gateways
{{- end }}
```

However, in the pdb this release: label is always added:

```
spec:
  minAvailable: 1
  selector:
    matchLabels:
{{ $gateway.labels | toYaml | indent 6 }}
      release: {{ .Release.Name }}
{{- end }
```

So the issue pops up if istio egress gateway is deployed into a different namespace than 'istio-system'...
So the fix would be to either remove the 'release:' label from the PDB selector, or make sure the release label is always added, even if namespace != 'istio-system'
