### ISSUE TITLE
Ingressgateway searches for TLS secret in the wrong namespace

### ISSUE THREAD

**Issue by mipnw** [istio/istio#27740]
**Bug description**

When one configures a gateway in Kubernetes namespace `ns1`, the [credentialName](https://istio.io/latest/docs/reference/config/networking/gateway/#ServerTLSSettings) should reference a Kubernetes secret in that same namespace `ns1`.

When the gateway selector is `istio: ingressgateway`, and that service lives in namespace `istio-system`, it appears the ingressgateway pods looks for the secret in the `istio-system` namespace instead of `ns1`.

IngressGateway Logs (gateway, secret are in namespace `httpbin`, ingress-gateway is in namespace `istio-system`)
```
 2020-10-05T17:27:03.406257Z    info    sds    resource:httpbin-tls-certificate new connection                                                                                   │
│ 2020-10-05T17:27:03.409868Z    warn    secretfetcher    Cannot find secret httpbin-tls-certificate, searching for fallback secret gateway-fallback                              │
│ 2020-10-05T17:27:03.409889Z    error    secretfetcher    cannot find secret httpbin-tls-certificate and cannot find fallback secret gateway-fallback                            │
│ 2020-10-05T17:27:03.409895Z    warn    cache    resource:httpbin-tls-certificate SecretFetcher cannot find secret httpbin-tls-certificate from cache                            │
│ 2020-10-05T17:27:03.409905Z    warn    sds    resource:httpbin-tls-certificate waiting for gateway secret for proxy "router~192.168.124.134~istio-ingressgateway-6c7644bd49-q4g

```

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**
Go through https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/ but install httpbin in its own namespace, and create the secret in that namespace as well. Here's what that would look like:

```
kubectl create namespace httpbin

kubectl create -n httpbin secret tls \
		httpbin-tls-certificate \
		--key=httpbin.example.com.key \
		--cert=httpbin.example.com.crt
```

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
  namespace: httpbin
  labels:
    app: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: httpbin
  labels:
    app: httpbin
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      serviceAccountName: httpbin
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin
  namespace: httpbin
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "httpbin.example.com"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: httpbin-tls-certificate
    hosts:
    - httpbin.example.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
  namespace: httpbin
spec:
  hosts:
  - "httpbin.example.com"
  gateways:
  - httpbin
  http:
  - match:
    - uri:
        prefix: /status
    - uri:
        prefix: /delay
    route:
    - destination:
        host: httpbin
        port:
          number: 80
```

**Version

```$ istioctl version --remote
client version: 1.7.0
control plane version: 1.7.0
data plane version: 1.7.0 (2 proxies)
```
``` 
$ kubectl version --short
Client Version: v1.17.7-eks-bffbac
Server Version: v1.17.9-eks-4c6976
```

**How was Istio installed?**
`istioctl install --set profile=demo`

**Environment where bug was observed (cloud vendor, OS, etc)**
EKS

**Comment by howardjohn** [comment]
This is working as intended. The option to allow cross namespace reading is tracked in https://github.com/istio/istio/issues/14598

**Comment by lmmarsano** [comment]
> This is working as intended.
Is this clearly documented?
If so, then where?
If not, then reopen & leave this open until that's done, please: no one should have to guess.

**Comment by ian-k** [comment]
I wasted a day of work on it, still no documentation and totally unclear

**Comment by speedythesnailnpg** [comment]
> I wasted a day of work on it, still no documentation and totally unclear

A year and a half later, I spent two days on this issue (separate, months apart) before I turned on trace logging and looked at istiod logs, only to discover that Istio was looking in the istio-system namespace instead of the namespace the "gateway" is in.

The ingressgateway is in the istio-system namespace (istio deployed using the demo profile), and the gateway was in the corresponding namespace as my application.

**Comment by edrandall** [comment]
Anyone coming here trying to find a solution, the following allowed us to keep all the application-related resources together in its own app-namespace.

1. Deply your certificate normally as a secret in your app-namespace, not istio-system.

2. In your Gateway resource YAML, specify your secret like this:
```
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: your-gateway
  namespace: app-namespace
spec:
    tls:
      mode: SIMPLE
      credentialName: kubernetes-gateway://app-namespace/tls-cert-secret-name
```

3. Although your Gateway resource is in your own namespace, add a ReferenceGrant as if it were in istio-system:
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: tls-cert-refgrant
  namespace: app-namespace
spec:
  from:
    - group: networking.istio.io
      kind: Gateway
      namespace: istio-system
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: istio-system
  to:
    - group: ''
      kind: Secret
      name: tls-cert-secret-name
  
```

This kubernetes://namespace/name for the credentialName syntax was found here: 
https://github.com/istio/istio/blob/master/pilot/pkg/config/kube/gateway/testdata/reference-policy-tls.yaml.golden
