### ISSUE TITLE
`istioctl version` does not work with revisioned Istio control plane when ver>=1.7.2

### ISSUE THREAD

**Issue by elfinhe** [istio/istio#27756]
**Bug description**
`istioctl version` does not work with revisioned Istio control plane when ver>=1.7.2

```
$ istioctl172 install --revision=rev172
This will install the default Istio profile into the cluster. Proceed? (y/N) y
✔ Istio core installed
✔ Istiod installed
✔ Ingress gateways installed
✔ Installation complete
```

```
$ istioctl172 version
no running Istio pods in "istio-system"
1.7.2
data plane version: 1.7.2 (1 proxies)
```

This bug is a result from 

https://github.com/istio/istio/pull/27357/files reduced the query to label `istio=pilot` instead of label `istio`.

And 

inconsistent label between revision-ed control plane and non-revision control plane. i.e., 

With revision, istiod is using istio: istiod for pods:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: istiod
    istio: pilot
    istio.io/rev: oss17
    release: istio
  name: istiod-oss17
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istiod
      istio.io/rev: oss17
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
  template:
    metadata:
      annotations:
        prometheus.io/port: "15014"
        prometheus.io/scrape: "true"
        sidecar.istio.io/inject: "false"
      labels:
        app: istiod
        istio: istiod <<<<<<< inconsistent label
        istio.io/rev: oss17
```

Without revision, istiod is using  istio: pilot for pods:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: istiod
    istio: pilot
    istio.io/rev: default
    release: istio
  name: istiod
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: pilot
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
  template:
    metadata:
      annotations:
        prometheus.io/port: "15014"
        prometheus.io/scrape: "true"
        sidecar.istio.io/inject: "false"
      labels:
        app: istiod
        istio: pilot <<<<<<< inconsistent label
        istio.io/rev: default
```

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
