### ISSUE TITLE
ext_authz upstream/downstream hang when with_request_body enabled for GRPC workloads

### ISSUE THREAD

**Issue by dkiser** [istio/istio#27777]
**Bug description**

When utilizing `ext_authz` in Envoy with `with_request_body` enabled, GRPC traffic to the destination service indefinitely hangs for both the upstream/downstream connection.

Viewing `debug` logs from the workload's Envoy container yields the following `ext_authz filter is buffering the request` log when a GRPC request is initiated from a client.  At this time, the client indefinitely hangs, and the `ext_authz` implementation (in this case https://github.com/open-policy-agent/opa-envoy-plugin) never sees a connection request.

Disabling the entire `with_request_body` configuration allows the RPC to pass.

```bash 
[Envoy (Epoch 0)] [2020-09-29 23:56:04.329][42][debug][filter] [external/envoy/source/extensions/filters/http/ext_authz/ext_authz.cc:99] [C12][S8985123515695601360] ext_authz filter is buffering the request
```

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Expected behavior**

GRPC traffic to a destination workload with `ext_authz` enabled including a `with_request_body` configuration should succeed with no timeouts.

**Steps to reproduce the bug**

* Deploy a GRPC destination workload
* Make sure `EnvoyFilter` resource is created for and matches the workload 
* Enable `ext_authz` per the configuration in the `EnvoyFilter` resource below.
* Perform a GRPC request to the workload. Notice a connection hang.
* Disable the `with_request_body` configuration
* Perform a GRPC request to the workload.  Notice it works!

**version**
```bash
➜  ~ istioctl --context=grpc-mc-a version --remote
client version: 1.7.2
control plane version: 1.4.6
```

**example Envoy Filter**
```yaml
############################################################
# Envoy External Authorization filter that will query OPA.
############################################################
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ext-authz
  # Leave in config root-namespce so that
  # this will match for any applicable workloadSelector
  # in ANY namespace.  This allows the filter to be applied
  # to apps that live in their current namespaces.
  namespace: istio-system
spec:
  # https://istio.io/docs/reference/config/networking/sidecar/#WorkloadSelector
  workloadSelector:
    # The scope of label search is restricted to the configuration namespace 
    # in which the the resource is present.
    labels:
      # PODs created with the following label will automatically be
      # a candidate for this EnvoyFilter.  Creation of this
      # label is done by the OPA admission controller logic.
      opa-istio-injected: "true"
  configPatches:
    # Make sure to add this HTTP filter BEFORE envoy.router, which
    # is the last HTTP filter in the http_connection_manager top
    # level filter.
    #
    # Istio Authentication Policies will add jwt_authn filters and
    # Istio specific authn filters, which will be higher up in the 
    # chain, so that this ext_authz plugin is the last filter called
    # before routing.
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
              subFilter:
                name: "envoy.router"
      patch: 
        operation: INSERT_BEFORE
        value: 
          name: "envoy.ext_authz"
          # Values from https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/ext_authz/v2/ext_authz.proto
          config: 
            grpc_service:
              google_grpc:
                target_uri: 127.0.0.1:9191
                stat_prefix: "ext_authz"
    - applyTo: NETWORK_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: envoy.tcp_proxy
      patch: 
        operation: INSERT_BEFORE
        value: 
          name: "envoy.ext_authz"
          # Values from https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/ext_authz/v2/ext_authz.proto
          config:
            stat_prefix: "ext_authz" 
            with_request_body:
              max_request_bytes: 8192
              allow_partial_message: true
            grpc_service:
              google_grpc:
                target_uri: 127.0.0.1:9191
                stat_prefix: "ext_authz" 
```

**How was Istio installed?**

Utilizing `istioctl` with the following settings:

```yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  autoInjection:
    components:
      injector:
        enabled: true
    enabled: true
  configManagement:
    components:
      galley:
        enabled: true
      namespace: istio-system
    enabled: true
  coreDNS:
    components:
      coreDNS:
        enabled: true
    enabled: true
  defaultNamespace: istio-system
  gateways:
    components:
      egressGateway:
        enabled: false
      ingressGateway:
        enabled: true
    enabled: true
  policy:
    components:
      namespace: istio-system
      policy:
        enabled: true
    enabled: true
  security:
    components:
      citadel:
        enabled: true
      namespace: istio-system
      nodeAgent:
        enabled: true
    enabled: true
  telemetry:
    components:
      namespace: istio-system
      telemetry:
        enabled: true
    enabled: true
  trafficManagement:
    components:
      pilot:
        enabled: true
        k8s:
          env: 
            - name: PILOT_SKIP_VALIDATE_TRUST_DOMAIN
              value: "true"
    enabled: true
  values:
    global:
      controlPlaneSecurityEnabled: true
      meshID: zion
      mtls:
        auto: true
        enabled: true
      multiCluster:
        enabled: true
      sds:
        enabled: true
        udsPath: "unix:/var/run/sds/uds_path"
        token:
          aud: "istio-ca"
      trustDomain: <PROVIDED AT RUNTIME FOR EACH CLUSTER>
      useMCP: true
      # Provides dns resolution for global services
      podDNSSearchNamespaces:
        - global
        - "{{ valueOrDefault .DeploymentMeta.Namespace \"default\" }}.global"
    security:
      selfSigned: false
    nodeagent:
      env:
        CA_PROVIDER: "Citadel"
        CA_ADDR: "istio-citadel:8060"
        VALID_TOKEN: true
```

**Environment where bug was observed (cloud vendor, OS, etc)**

* Minikube Local Cluster
* GCP GKE

**Comment by howardjohn** [comment]
cc @yangminzhu

**Comment by yangminzhu** [comment]
Seems like https://github.com/envoyproxy/envoy/issues/9822, I think you can set the new `pack_as_bytes` field to fix the issue.

**Comment by srenatus** [comment]
Hi there! I'm trying to use the pack_as_bytes option recently added to envoy's v3 ext_authz config, with istio 1.7.0.
in the output of `kubectl -n istio-system get envoyfilter.networking.istio.io/ext-authz -oyaml`, I find it:
```yaml
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.ext_authz
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
          grpc_service:
            google_grpc:
              stat_prefix: ext_authz
              target_uri: 127.0.0.1:9191
          status_on_error:
            code: ServiceUnavailable
          transport_api_version: V3
          with_request_body:
            allow_partial_message: true
            max_request_bytes: 8192
            pack_as_bytes: true
```

but in `istioctl proxy-config listeners greeter-54769df99b-85bzf.default -o json`, all I get is
```
"transportApiVersion": "V3",
"withRequestBody": {
  "maxRequestBytes": 8192,
  "allowPartialMessage": true
},
"statusOnError": {
  "code": "ServiceUnavailable"
}
```
Would you have an idea what I'm missing? Am I too far behind in Istio versions?
