### ISSUE TITLE
TLS termination of HTTPS on ingress gateway appears to be broken

### ISSUE THREAD

**Issue by mipnw** [istio/istio#27784]
**Bug description**

Tutorial https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/ is about deploying httpbin to Kubernetes, and configuring Istio's ingress gateway for HTTPS. I followed exactly that tutorial and the curl client fails to connect.

```
# create a namespace for the httpbin application
kubectl create ns httpbin
kubectl label namespace httpbin istio-injection=enabled
kubectl label namespace httpbin app=httpbin

# create a secret in istio-system namespace
openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -subj '/O=example Inc./CN=example.com' -keyout example.com.key -out example.com.crt
openssl req -out httpbin.example.com.csr -newkey rsa:2048 -nodes -keyout httpbin.example.com.key -subj "/CN=httpbin.example.com/O=httpbin organization"
openssl x509 -req -days 365 -CA example.com.crt -CAkey example.com.key -set_serial 0 -in httpbin.example.com.csr -out httpbin.example.com.crt

kubectl create -n istio-system secret tls httpbin-tls-certificate --key=httpbin.example.com.key --cert=httpbin.example.com.crt

# deploy httpbin
kubectl apply -f httpbin.yaml
```
and httpbin.yaml
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
  namespace: httpbin
  labels:
    app: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: httpbin
  labels:
    app: httpbin
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      serviceAccountName: httpbin
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin
  namespace: httpbin
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "httpbin.example.com"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: httpbin-tls-certificate
    hosts:
      - "httpbin.example.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
  namespace: httpbin
spec:
  hosts:
  - "httpbin.example.com"
  gateways:
  - httpbin
  http:
  - match:
    - uri:
        prefix: /status
    - uri:
        prefix: /delay
    route:
    - destination:
        host: httpbin
        port:
          number: 80
```

```
INGRESS_HOST = kubectl get svc istio-ingressgateway -n istio-system -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'
INGRESS_PORT =  kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].port}'
INGRESS_PORT_SECURE = kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="https")].port}'
```

Plaintext works: `curl -i -HHost:httpbin.example.com "http://$(INGRESS_HOST):$(INGRESS_PORT)/status/200"` returns status OK.

HTTPS does not work `curl -v -i -HHost:httpbin.example.com --cacert example.com.crt "https://$(INGRESS_HOST):$(INGRESS_PORT_SECURE)/status/200` returns 
```
*   Trying [redacted IP]...
* Connected to [redacted domain].us-west-2.elb.amazonaws.com ([redacted IP]) port 443 (#0)
* found 1 certificates in example.com.crt
* found 526 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* gnutls_handshake() failed: The TLS connection was non-properly terminated.
* Closing connection 0
```

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

The tutorial works

**Steps to reproduce the bug**

```
$ istioctl version --remote
client version: 1.7.0
control plane version: 1.7.0
data plane version: 1.7.0 (3 proxies)

$ kubectl version --short
Client Version: v1.17.7-eks-bffbac
Server Version: v1.17.9-eks-4c6976
```

**How was Istio installed?**
```
istioctl install --set profile=demo
```

**Environment where bug was observed (cloud vendor, OS, etc)**
* EKS 1.17
* Istio ingress gateway logs: `Version 1.7.0-2022348138e47498c4b54995b4cb5a1656817c4e-Clean`

**Comment by shamsher31** [comment]
Looks like it's a doc issue. @ericvn  can you please move this issue to istio.io repo?

**Comment by mipnw** [comment]
@shamsher31 I think there's a product bug that goes beyond a bug in the tutorial. I'm unable to configure the ingress gateway for HTTPS with tls:SIMPLE, meaning TLS termination of HTTPS on the ingress gateway may be a broken feature right now.

**Comment by s-bauer** [comment]
@shamsher31 @mipnw Having the same issue: https://github.com/istio/istio/issues/27784 
Maybe I'm missing something but I can't get TLS termination to work! I didn't try it with the httpbin example yet, but I'm having a similar setup that gives me a similar error. Please take a look at this as it might be a serious product bug! Meanwhile I guess the only option for me is to move to another ingress controller to expose my api-gateway.

**Comment by williamaronli** [comment]
it seems a doc updated issue could we move it to backlog?

**Comment by howardjohn** [comment]
is your AWS LB terminating the TLS then re-originating without SNI header causing it to not match

**Comment by adnankobir** [comment]
> is your AWS LB terminating the TLS then re-originating without SNI header causing it to not match

@howardjohn how do we get around this today? It looks like this exactly whats going on with my setup:

`curl -v https://httpbin.v7-test-use1.redacted.com
*   Trying 10.134.29.210...
* TCP_NODELAY set
* Connected to httpbin.v7-test-use1.redacted.com (10.134.29.210) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=v7-test-use1.redacted.com
*  start date: Jul 13 00:00:00 2020 GMT
*  expire date: Aug 13 12:00:00 2021 GMT
*  subjectAltName: host "httpbin.v7-test-use1.redacted.com" matched cert's "*.v7-test-use1.redacted.com"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: httpbin.v7-test-use1.redacted.com
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
< date: Tue, 02 Mar 2021 20:47:53 GMT
< server: istio-envoy
< content-length: 0
<
* Connection #0 to host httpbin.v7-test-use1.redacted.com left intact
* Closing connection 0`

**Comment by howardjohn** [comment]
Basically the only option is to use `hosts: *` in gateway. That makes it so there is no SNI routing. Note that this also means you can only have a single certificate at the gateway. if you need more, you would need distinct gateway deployments

**Comment by adnankobir** [comment]
> Basically the only option is to use `hosts: *` in gateway. That makes it so there is no SNI routing. Note that this also means you can only have a single certificate at the gateway. if you need more, you would need distinct gateway deployments

Settings hosts to `*` didn't solve the issue for me:

```
curl -v https://httpbin.v7-test-use1.redacted.com
*   Trying 72.44.53.229...
* TCP_NODELAY set
* Connected to httpbin.v7-test-use1.redacted.com (72.44.53.229) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=v7-test-use1.redacted.com
*  start date: Jul 13 00:00:00 2020 GMT
*  expire date: Aug 13 12:00:00 2021 GMT
*  subjectAltName: host "httpbin.v7-test-use1.redacted.com" matched cert's "*.v7-test-use1.redacted.com"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: httpbin.v7-test-use1.redacted.com
> User-Agent: curl/7.64.1
> Accept: */*
>
* TLSv1.2 (IN), TLS alert, close notify (256):
* Empty reply from server
* Connection #0 to host httpbin.v7-test-use1.redacted.com left intact
curl: (52) Empty reply from server
* Closing connection 0
```

Gateway and vs config:

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: httpbin
  namespace: default
spec:
  selector:
    app: istio-ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: httpbin
      mode: SIMPLE

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  annotations:
  name: httpbin
  namespace: default
spec:
  gateways:
  - httpbin
  hosts:
  - httpbin.v7-test-use1.redacted.com
  http:
  - route:
    - destination:
        port:
          number: 80
        host: httpbin
```

`httpbin` secret is deployed via cert-manager:

```
kubectl get secret -n istio-system  | grep httpbin
httpbin                                                     kubernetes.io/tls                     3      43m
```

Any thoughts on how to troubleshoot this further?
