### ISSUE TITLE
Better External Authorization support

### ISSUE THREAD

**Issue by yangminzhu** [istio/istio#27790]
**Describe the feature request**
Add a new `EXTERNAL` action in authorization policy to integrate the Envoy ext_authz filter, this solves the 2 big pain points in current EnvoyFilter flow that 
1) EnvoyFilter is generally hard to configure, use and debug (e.g. cluster name, common mistakes, typo in config and some other tricky issues);
2) support triggering the ext_authz conditionally based on various request attributes (path, host, header, etc.);

Design doc: https://docs.google.com/document/d/1V4mCQCw7mlGp0zSQQXYoBdbKMDnkPOjeyUb85U07iSI/edit# (join Istio community group to gain access)

**Describe alternatives you've considered**
Continue to use EnvoyFilter for integrating Envoy ext_authz filter.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by haf** [comment]
Related once you have it mostly configured, but need to opt-out at some points https://github.com/istio/istio/issues/27790

**Comment by yangminzhu** [comment]
@haf I'm writing a blog as well as a task for the feature, but the following is a quick tutorial for trying it out for now:

1. Deploy the Istio from master branch (https://github.com/istio/istio/wiki/Dev%20Builds)

2. Edit the meshconfig (`kubectl edit configma istio -n istio-system`) to add the extension provider definitions (only the `extensionProviders` part):
```yaml
apiVersion: v1
data:
  mesh: |-
    accessLogFile: /dev/stdout
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      proxyMetadata:
        DNS_AGENT: ""
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
    enablePrometheusMerge: true
    rootNamespace: istio-system
    trustDomain: cluster.local
    extensionProviders:
    - name: "example-ext-authz-http"
      envoyExtAuthzHttp:
        service: "ext-authz.default.svc.cluster.local"
        port: "8000"
    - name: "example-ext-authz-grpc"
      envoyExtAuthzGrpc:
        service: "ext-authz.default.svc.cluster.local"
        port: "9000"
  meshNetworks: 'networks: {}'
```

3. Deploy the example ext-authz server in the mesh: https://github.com/istio/istio/blob/master/samples/extauthz/ext-authz.yaml


3. Apply the authorization policy with CUSTOM action only for path /headers, you can specify other rules to opt-out a request from the ext-authz enforcement, you can also specify the workload to control where to apply the policy (e.g. httpbin pod, or some namespace or the whole cluster):

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: httpbin-standalone
spec:
  selector:
    matchLabels:
      app: httpbin
  action: CUSTOM
  provider:
    name: "example-ext-authz-grpc" # can also use the `example-ext-authz-http`
  rules:
  - to:
    - operation:
        paths: ["/headers"]
```

4. Send some requests from sleep to httpbin to verify the logs in the ext-authz server, see https://github.com/istio/istio/blob/master/samples/extauthz/README.md for more details

**Comment by haf** [comment]
So what's the syntax for using `rules` to opting out, say, a specific dns name?

**Comment by yangminzhu** [comment]
> So what's the syntax for using `rules` to opting out, say, a specific dns name?

It's the same syntax as the current authorization policy. You can use the `hosts` or `notHosts` field, for example, the following policy enables the ext authz flow on all hosts **except** "example.com":

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: httpbin-standalone
spec:
  selector:
    matchLabels:
      app: httpbin
  action: CUSTOM
  provider:
    name: "example-ext-authz-grpc" # can also use the `example-ext-authz-http`
  rules:
  - to:
    - operation:
        notHosts: ["example.com"]
```

see more in https://istio.io/latest/docs/reference/config/security/authorization-policy/#Operation

**Comment by theganyo** [comment]
I was just checking this out on new Istio 1.9 release and noticed that there is no way to set `metadata_context_namespaces` to pass Envoy metadata to the authz service. Without this, there is no way to read the authenticated JWT claims from the jwt_authn filter as documented [here](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto#envoy-v3-api-msg-extensions-filters-http-ext-authz-v3-extauthz).

**Comment by ikawalec** [comment]
@yangminzhu I'm looking for a way to send a request body to the authorizer.  Is this possible via authorization policy or extension provider or any other way? This is sth that is configurable here https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto -> with_request_body

**Comment by ikawalec** [comment]
> @yangminzhu I'm looking for a way to send a request body to the authorizer. Is this possible via authorization policy or extension provider or any other way? This is sth that is configurable here https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto -> with_request_body

I found an example of how this can be done: https://github.com/istio/istio/issues/31182#issuecomment-789175835

**Comment by christian1607** [comment]
Actually the extension Provider configures envoy with  no timeout  therefore envoy sets  the timeout to 200ms, which means that if any request takes more than 200ms it will fail because of timeout. I think the extension provider should have that property.

Like this:
```
- name: "opa-sidecar"
      envoyExtAuthzGrpc:
        service: "local-opa-grpc.local"
        port: "9191" 
        timeout: 1s
```

**Comment by yangminzhu** [comment]
> Actually the extension Provider configures envoy with no timeout therefore envoy sets the timeout to 200ms, which means that if any request takes more than 200ms it will fail because of timeout. I think the extension provider should have that property.
> 
> Like this:
> 
> ```
>    name: "opa-sidecar"
>    envoyExtAuthzGrpc:
>      service: "local-opa-grpc.local"
>      port: "9191" 
>      timeout: 1s
> ```

@christian1607 the `timeout` was set to a default value of `600s` in 1.9 and is exposed for configuring in 1.10: https://github.com/istio/api/blob/02def630fd33ba87387ce6e359abfb3c68433ac3/mesh/v1alpha1/config.proto#L526

**Comment by fiftoine** [comment]
Is there a way to setup envoyExtAuthzHttp to access an exposed service on the internet with https?
something like :
```
extensionProviders:
    - name: "example-ext-authz-http"
      envoyExtAuthzHttp:
        service: "https://my-oauth2-proxy.my-domain.com"
        port: "443"
```
