### ISSUE TITLE
Explicitly defining ingress on Sidecar results brief service impact

### ISSUE THREAD

**Issue by Stono** [istio/istio#27796]
**Bug description**
Whilst working around https://github.com/istio/istio/issues/17465, we're having to explicitly define `ingress` on our sidecar.  In the vast majority of circumstances, this changes nothing about the inbound listeners; for example we added:

```
    ingress:
    - defaultEndpoint: 127.0.0.1:8080
      port:
        name: http-app
        number: 8080
        protocol: HTTP
    - defaultEndpoint: 127.0.0.1:8081
      port:
        name: http-admin
        number: 8081
        protocol: HTTP
```

To this service/endpoint:
```
❯ kubectl get ep
NAME    ENDPOINTS                                                             AGE
admin   10.194.1.49:8081,10.194.13.197:8081,10.194.19.176:8081 + 12 more...   560d
app     10.194.1.49:8080,10.194.13.197:8080,10.194.19.176:8080 + 12 more...   2y28d
```

Which is basically, identical in terms of configuration.  However the service is under load and when the ingress was applied to `Sidecar` we had a large spike in `503NR` errors from `reporter=source`:

<img width="1670" alt="Screenshot 2020-10-07 at 13 20 01" src="https://user-images.githubusercontent.com/1486729/95330329-4deb7c00-08a0-11eb-9adb-4498cddf1632.png">

[ ] Docs
[ ] Installation
[x] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Should be able to add listeners to the `Sidecar` which match existing listeners without service impact.

**Steps to reproduce the bug**
Have an existing `Sidecar` resource with no `ingress`, and then add `ingress` matching an existing listener generated from the pod ports.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
1.5
