### ISSUE TITLE
1.7 REGRESSOIN: Prometheus cannot scrape pods when enablePrometheusMerge disabled

### ISSUE THREAD

**Issue by mike1808** [istio/istio#27824]
**Bug description**

When `meshConfig.enablePrometheusMerge` is disabled Prometheus fails to scrape pods with injected sidecars with `server returned HTTP status 503 Service Unavailable` error. 

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Prometheus should be able to scrape the pods over mTLS when `enablePrometheusMerge` is disabled and `provisionPrometheusCert` is enabled.

**Steps to reproduce the bug**

Deploy Istio 1.7.x with the following config:

```yaml
---
apiVersion: install.istio.io/v1alpha2
kind: IstioOperator
spec:
  profile: default
  namespace: istio-system
  components:
  values:
    prometheus:
      enabled: true
      provisionPrometheusCert: true
    grafana:
      enabled: true
    meshConfig:
      enablePrometheusMerge: false
      enableAutoMtls: true
    global:
      controlPlaneSecurityEnabled: true
```

And then deploy an app with prometheus metrics in a sidecar injectable namespace, e.g.:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: prometheus-example-app
  name: prometheus-example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-example-app
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: /metrics
      labels:
        app.kubernetes.io/name: prometheus-example-app
    spec:
      containers:
      - name: prometheus-example-app
        image: quay.io/brancz/prometheus-example-app:v0.3.0
        ports:
        - name: web
          containerPort: 8080
```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

```bash
$ istioctl version --remote
client version: 1.6.8
control plane version: 1.7.3
data plane version: 1.7.1 (1 proxies), 1.7.3 (2 proxies)
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-gke.500", GitCommit:"98a221da900b81cfd64fa0e00bfad2a084ea918b", GitTreeState:"clean", BuildDate:"2020-09-21T09:19:38Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?** 

```bash
istioctl manifest generate -f values.yml | kubectl apply -f -
```

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE 1.19

**Notes**:

I'm trying to scrape metrics over mTLS so I disabled `enablePrometheusMerge` which will make istioctl to manually inject istio-proxy and save the cert in tmpfs and configures Prometheus to use those certs. After some investigation turns out that if you try to curl the metrics port using HTTP2 it will fail with: `upstream connect error or disconnect/reset before headers. reset reason: connection termination`, but if you curl with HTTP1.1 it works. And turns out that Prometheus uses HTTP2.

E.g.:

```bash
# this works
kubectl exec -n istio-system prometheus-6556574667-ggxm8 -c istio-proxy -- curl https://10.64.1.30:8080/metrics --cacert /etc/istio-certs/root-cert.pem --cert /etc/istio-certs/cert-chain.pem --key /etc/istio-certs/key.pem -k --http1.1 -sS

# this doesn't
kubectl exec -n istio-system prometheus-6556574667-ggxm8 -c istio-proxy -- curl https://10.64.1.30:8080/metrics --cacert /etc/istio-certs/root-cert.pem --cert /etc/istio-certs/cert-chain.pem --key /etc/istio-certs/key.pem -k --http2 -sS
```
