### ISSUE TITLE
Failed to call headless service after mtls enabled with error: connection termination

### ISSUE THREAD

**Issue by wangmeng** [istio/istio#27831]
**Bug description**

I have 2 kube headless services (service1 and service2) in the same namespace ns1.   And ns1 has applied the `istio-injection=enabled` label.

```
k get service -n ns1
NAME                                   TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)              AGE
service1                               ClusterIP   None             <none>        8080/TCP             15h
service2                               ClusterIP   None             <none>        8080/TCP             15h
```

I also applied the whole kube cluster level's mtls 
```
---
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
  namespace: "istio-system"
spec:
  mtls:
    mode: STRICT
```

These 2 services could be accessible via Gateway&VirtualService successfully (based on the https://github.com/istio/istio/pull/27096)

But after I enabled mtls, when trying to call from service1 to service2, I will get the following error.  

> kubectl exec <service1_pod> -n ns1  -- curl -v http://service2.ns1.svc.cluster.local:8080
```
* Rebuilt URL to: http://service2.ns1.svc.cluster.local:8080/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 172.30.112.229...
* TCP_NODELAY set
* Connected to service2.ns1.svc.cluster.local (172.30.112.229) port 8080 (#0)
> GET / HTTP/1.1
> Host: service2.ns1.svc.cluster.local:8080
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 503 Service Unavailable
< content-length: 95
< content-type: text/plain
< date: Thu, 08 Oct 2020 15:33:20 GMT
< server: envoy
<
{ [95 bytes data]
* Curl_http_done: called premature == 0
100    95  100    95    0     0   5565      0 --:--:-- --:--:-- --:--:--  5937
* Connection #0 to host service2.ns1.svc.cluster.local left intact
upstream connect error or disconnect/reset before headers. reset reason: connection termination%
```

Please notes:

Note1: if removing the above PeerAuthentication, the call can work. 

Note2: Is this due to such headless service is defined as "ORIGINAL_DST"? 

>  kubectl <service1_pod> -n ns1 -- curl -v http://127.0.0.1:15000/config_dump
```
    {
     "version_info": "2020-10-08T12:54:59Z/415",
     "cluster": {
      "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
      "name": "outbound|8080||service2.ns1.svc.cluster.local",
      "type": "ORIGINAL_DST",
      "connect_timeout": "10s",
      "lb_policy": "CLUSTER_PROVIDED",
      "circuit_breakers": {
       "thresholds": [
```

Note3: I also tried to apply a DestinationRule, but still have the same behavior. 

```
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: ns1-destination-rule
  namespace: ns1
spec:
  host: "*.ns1.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

The cmd should work
kubectl exec <service1_pod> -n ns1  -- curl -v http://service2.ns1.svc.cluster.local:8080

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

> istioctl version --remote
```
client version: 1.7.2
control plane version: 1.7.3
data plane version: 1.7.3 
```

> kubectl version --short
```
kubectl version --short
Client Version: v1.18.5
Server Version: v1.17.12+IKS
```

**How was Istio installed?**
IBM IKS managed istio

**Environment where bug was observed (cloud vendor, OS, etc)**
IBM IKS managed istio

**Comment by linsun** [comment]
@wangmeng can you please advise how to recreate this?  which specific headless service?

For now, I would recommend you to exclude the port (that is used for pods communication within your headless service) out from istio so the mtls is focused on communications among your services.

**Comment by linsun** [comment]
https://istio.io/latest/faq/traffic-management/#controlling-inbound-ports - check this out to use exclude port.

**Comment by wangmeng** [comment]
Thanks @linsun  

Here are the reproduce steps:

```
kubectl create ns foo1
kubectl label namespace foo1 istio-injection=enabled
kubectl apply -f httpbin.yaml -n foo1
kubectl apply -f sleep.yaml -n foo1

kubectl get service -n foo1
NAME      TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
httpbin   ClusterIP   None         <none>        8000/TCP   41s
sleep     ClusterIP   None         <none>        80/TCP     28s


kubectl exec "$(kubectl get pod -l app=sleep -n foo1 -o jsonpath={.items..metadata.name})" -c sleep -n foo1 -- curl http://httpbin.foo1/ip
```


httpbin.yaml:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      serviceAccountName: httpbin
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80

```


sleep.yaml
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sleep
---
apiVersion: v1
kind: Service
metadata:
  name: sleep
  labels:
    app: sleep
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 80
    name: http
  selector:
    app: sleep
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      serviceAccountName: sleep
      containers:
      - name: sleep
        image: governmentpaas/curl-ssl
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /etc/sleep/tls
          name: secret-volume
      volumes:
      - name: secret-volume
        secret:
          secretName: sleep-secret
          optional: true
---
```

without mtls:
```
[2020-10-08T18:53:21.805Z] "GET /ip HTTP/1.1" 200 - "-" "-" 0 28 3 2 "-" "curl/7.69.1" "f8be4bc5-5fa2-4ce1-9315-6e4e6e60ffde" "httpbin.foo1.svc.cluster.local" "172.30.209.173:80" outbound|80||httpbin.foo1.svc.cluster.local 172.30.209.171:58130 172.30.209.173:80 172.30.209.171:58128 - default
```

after enabled mtls:
```
[2020-10-08T18:54:19.633Z] "GET /ip HTTP/1.1" 503 UC "-" "-" 0 95 1 - "-" "curl/7.69.1" "bad612ed-f991-4fd5-a0e8-6a5bd93b7971" "httpbin.foo1.svc.cluster.local" "172.30.209.173:80" outbound|80||httpbin.foo1.svc.cluster.local 172.30.209.171:59098 172.30.209.173:80 172.30.209.171:59096 - default
```
