### ISSUE TITLE
Istio operator can not recover from conflicing secondary iops

### ISSUE THREAD

**Issue by rvennam** [istio/istio#27840]
**Bug description**

If you apply a secondary IOP (no revision set) which conflicts with the first IOP, you can not recover back to the first by deleting the second one.

[ ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Deleting the second IOP should cause the operator to just use the first IOP as the source of truth.

**Steps to reproduce the bug**
1. Deploy the Istio operator:
```
istioctl operator init
kubectl create ns istio-system
```
2. Apply first IOP `example-istiocontrolplane`
```
kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: demo
EOF
```
3. wait until istiod, ingress and egress pods are up and running. Then, apply this secondary IOP `example-istiocontrolplane2`
```
kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane2
spec:
  profile: default
EOF
```
4. Wait a few moments and and delete the second example-istiocontrolplane2 IOP 
```
kubectl delete iop example-istiocontrolplane2 -n istio-system
```

Result: After a few minutes istiod and ingress pods are gone...only egress left. But they should still be there because the first IOP (demo profile) is still there.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
1.7.0

**How was Istio installed?**
Operator

**Environment where bug was observed (cloud vendor, OS, etc)**
IKS

cc: @sdake
