### ISSUE TITLE
Changes to workload entries are not pushed to sidecar proxies until a restart of istiod

### ISSUE THREAD

**Issue by sreerajan-ambattumyalil** [istio/istio#27841]
**Bug description**

On deleting a workload entry, the cluster still shows the deleted entry as an endpoint until a restart of istiod pods.

[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Changes to workload entries should trigger a push to broadcast the changes to all sidecar proxies.

**Steps to reproduce the bug**

1. Create a new cluster with 2 endpoints using service and workload entries.

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: egress-service-entry
spec:
  hosts:
  - egress.backend.internal
  ports:
  - name: tls
    number: 443
    protocol: TLS
  resolution: DNS
  workloadSelector:
    labels:
      app: egress

apiVersion: networking.istio.io/v1beta1
kind: WorkloadEntry
metadata:
  name: egress-workload-entry-0
spec:
  address: host-1.egress.backend.internal
  labels:
    app: egress

apiVersion: networking.istio.io/v1beta1
kind: WorkloadEntry
metadata:
  name: egress-workload-entry-1
spec:
  address: host-2.egress.backend.internal
  labels:
    app: egress
```

2. Check the cluster definition 

`istioctl proxy-config clusters <pod-name> --fqdn "outbound|443||egress.backend.internal" -o json`

3. Delete the workload entry _egress-workload-entry-1_

4. Check the cluster definition again

`istioctl proxy-config clusters <pod-name> --fqdn "outbound|443||egress.backend.internal" -o json`

**The entry for _egress-workload-entry-1_ will still be visible in the endpoints.**

5. Restart **istiod**

6. Check the cluster definition again

`istioctl proxy-config clusters <pod-name> --fqdn "outbound|443||egress.backend.internal" -o json`

**The entry for _egress-workload-entry-1_ will not be visible in the endpoints.**

**Version**

***Istio Version***
`1.6.0
data plane version: 1.6.4 (296 proxies)
`

***kubectl Version***
`
Client Version: v1.17.0
Server Version: v1.16.13-gke.401
`

**How was Istio installed?**

`istioctl` with local manifests.

**Environment where bug was observed **

GKE
