### ISSUE TITLE
Automatically set outbound (envoy as client) SNI based on host/authority

### ISSUE THREAD

**Issue by nickperry** [istio/istio#27847]
**Describe the feature request**

I would like Istio to be able to automatically set the outbound (envoy as client) SNI based on host/authority.

Currently, for all egress cases where I am doing TLS origination AND the destination host expects SNI to be set, I need to use a DestinationRule with a subset like
```
  subsets:
  - name: foo.bar
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: ISTIO_MUTUAL
          sni: foo.bar
```
to manually set the SNI value.

Having to do this for every egress destination is painful.

**Describe alternatives you've considered**

Lua Envoy filter.
or
CRD for egress destinations, and a controller which would manage the underlying VirtualService, DestinationRule, ServiceEntry and Gateway resources.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-field-config-core-v3-upstreamhttpprotocoloptions-auto-sni

https://github.com/envoyproxy/envoy/issues/2690
