### ISSUE TITLE
Unable to set affinity in the components

### ISSUE THREAD

**Issue by Stono** [istio/istio#27870]
**Bug description**
As per https://istio.io/latest/docs/setup/install/istioctl, I'm expecting to be able to set the `istioid` affinity, using a configuration like this:

```
  components:
    pilot:
      k8s:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - istiod
                topologyKey: kubernetes.io/hostname
              weight: 100
```

However, when i run `istioctl manifest generate`, the templated istiod is lacking this configuration.

Other components of `k8s`, such as `nodeSelector`, work fine.

[x] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[x] Developer Infrastructure

**Expected behavior**
To be able to configure whatever affinity rules I chose.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
1.6.12

**How was Istio installed?**
Helm/istioctl generate manifest 

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by morvencao** [comment]
```
# ./bin/istioctl version
invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
1.6.12
# cat << EOF | ./bin/istioctl manifest generate -f - | grep podAntiAffinity -A 8
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-operator
spec:
  profile: default
  components:
    pilot:
      k8s:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - istiod
                topologyKey: kubernetes.io/hostname
              weight: 100
EOF
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - istiod
```

It is working in my local env, would you please verify again? or append debug log?
