### ISSUE TITLE
Feature Request: envoy ipRanges from central config

### ISSUE THREAD

**Issue by Stono** [istio/istio#2790]
Hi, 
Rather than doing `istioctl --includeIpRanges=cidr,cidr,cidr` on every deployment, it'd be nice `docker.io/istio/proxy_init` could pull the includeIpRanges from pilot perhaps?

Our use case here is that our istio network is VPN'd to our on-prem network, which doesn't run istio, and we need to globally exclude (by including just the istio ranges) the cidr ranges of our on prem kit from mTLS.

**Comment by ayj** [comment]
This is doable with the templated injection configuration (see https://github.com/istio/istio/pull/2760). Here's the basic idea:

1) update the injection template to conditionally add the `-i` flag to the `proxy_init` container based some value in the to-be-injected pod (see 
https://gist.github.com/ayj/cfe9673cefd5bcf4f14f1d7c973a496d#file-template-yaml-L11).

```yaml
  initContainers:
  - name: istio-init
    image: unknown/proxy_init:unknown
    args:
    - "-p"
    - {{ .MeshConfig.ProxyListenPort }}
    - "-u"
    - 1337
    {{ if ne "" (index .ObjectMeta.Labels "include-ip-range") -}}
    - "-i"
    - {{ index .ObjectMeta.Labels "include-ip-range" }}
    {{ end }} 
```

2) use the `include-ip-range` label to define per-pod overrides (see https://gist.github.com/ayj/7e570714b61e92b33244c185b7b514ad#file-sleep-yaml-L41)

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sleep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sleep
        include-ip-range: "192.168.1.0/24,10.0.0.1/32"
```

3) `kube-inject` or the automatic injection will apply the template to the source pod and conditionally set the flag (see https://gist.github.com/ayj/67a422376460d638a6d3c088c1170bb2#file-sleep-injected-yaml-L118)

```yaml
      initContainers:
      - args:
        - -p
        - "15001"
        - -u
        - "1337"
        - -i
        - 192.168.1.0/24,10.0.0.1/32
        image: unknown/proxy_init:unknown
        imagePullPolicy: IfNotPresent
        name: istio-init
```

**Comment by ayj** [comment]
Also, an annotation would be a better choice than a label as I've described above for per-pod overrides.

**Comment by Stono** [comment]
Hey both, thank you for your responses.

The request came because of the award position that I am in at the moment, using GKE1.8.6 I don't have auto initialisers available, and we are using helm to deploy our charts so there is no kube-inject either.

Instead our chart developers are currently manually adding the required bits to their deployment templates.  

The complexity then becomes because we want to change those IP ranges depending on which cluster (environment) they are being deployed too, and wanted to avoid having to run every helm install with a "set includeRange=" set according to the deployment target.  This is why some sort of global, cluster level setting for includeIpRanges would have been nice.

**Comment by ayj** [comment]
You could use a configmap and environment variables to dynamically configure the include range. It isn't perfect (requires new configmap per namespace) but is closer to globally derived config.

1) add the following to the list of arguments in the `istio-init` container in your helm templates.

```yaml
- -i
- ${INCLUDE_IP_RANGE:-""
```

2) Define `INCLUDE_IP_RANGE` based on the value from a configmap in the same namespace.

```yaml
      env:
          - name: INCLUDE_IP_RANGE
            valueFrom:
              configMapKeyRef:
                name: istio-proxy-init
                key: include-ip-range
```

3) Define the configmap with per-namespace (pseudo global) CIDR range.

```
 kubectl create cm istio-proxy-init --from-literal=include-ip-range=192.168.2.2
```

_note_: the following prototype fails if the configmap isn't defined or the value is missing. This could be improved by tweaking the init container start-up script.
