### ISSUE TITLE
wasm c++ grpcCallHandler() not being called for istio 1.7.2

### ISSUE THREAD

**Issue by salrashid123** [istio/istio#27918]
Isito `1.7.2` wasm does not invoke gRPC call handler.

I've generated a a c++ wasm filter not using wasme but off of the manual steps [here](https://github.com/salrashid123/istio_helloworld#webassembly)
(i.e basically added on grpc to the helloworld:

```bash
git clone --single-branch --branch  release-1.7 https://github.com/istio/envoy.git
bazel build examples/wasm:envoy_filter_http_wasm_example.wasm
```

That plugin calls  a gRPC service using  `gRPCCallHandler()`.  If i run a grpc serivice on my laptop and the envoy version and config shown below, the handler is called.

```
$ envoy  version: c5594b41f48b2e45df83105de84623f2930d23cd/1.15.0/clean-getenvoy-a5345f6-envoy/RELEASE/BoringSSL
```

envoy -c [envoy.yaml](https://gist.githubusercontent.com/salrashid123/fe6b5e966e9a366f446a599a306542da/raw/732c103f2c930656d1cea24c52115a87e0b35127/envoy.yaml)

however, if i deploy to istio `1.7.2` manually (i.e use `sidecar.istio.io/userVolumeMount` on the Deployment pod), i can see the wasm plugin gets loaded and that it is invoked on the `onRequestHeaders` call (i.,e i see the log line shown below).

However, the grpc call handler is never invoked.   I can tell by bumping up the wasm logs on the sidecar

**Affected product area 
[x] Extensions and Telemetry

**Expected behavior**

the `MyGrpcCallHandler` should be called and an `envoy_grpc` cluster/service called `ext-dlp.default.svc.cluster.local` should be invoked

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ui-examplefilter
  namespace: default
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      proxy:
        proxyVersion: '1\.7.*'      
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              name: envoy.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.wasm
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          value:
            config:
              root_id: my_root_id
              configuration:
                "@type": "type.googleapis.com/google.protobuf.StringValue"
                value: |
                  {
                    "clustername": "ext-dlp.default.svc.cluster.local",
                  }                 
              vm_config:
                code:
                  local:
                    filename: /var/local/lib/wasm-filters/envoy_filter_http_wasm_example.wasm
                runtime: envoy.wasm.runtime.v8
                allow_precompiled: true
                vm_id: my-example                
  workloadSelector:
    labels:
      app: httpbin
      version: v1
```

**Steps to reproduce the bug**

**Version 

```bash
$ istioctl version --remote
client version: 1.7.2
control plane version: 1.7.2
data plane version: 1.7.2 (2 proxies)

$ kubectl version --short
Client Version: v1.18.6
Server Version: v1.18.6-gke.4801
```

**How was Istio installed?**

```bash
* create gke  --cluster-version "1.18"
* istioctl install --set profile=demo \
   --set values.global.controlPlaneSecurityEnabled=true  \
   --set meshConfig.enableAutoMtls=true \
   --set values.gateways.istio-ingressgateway.runAsRoot=true
```

**Environment where bug was observed*

GKE 1.18

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching the dump file to this issue.

```cpp
FilterHeadersStatus ExampleContext::onRequestHeaders(uint32_t, bool) {

  LOG_DEBUG(std::string("onRequestHeaders ") + std::to_string(id()));
  auto result = getRequestHeaderPairs();
  auto pairs = result->pairs();
  LOG_INFO(std::string("headers: ") + std::to_string(pairs.size()));
  for (auto& p : pairs) {
    LOG_INFO(std::string(p.first) + std::string(" -> ") + std::string(p.second));
  }

  LOG_INFO(">>>>>>>>>>>>>  Calling GRPC");
  ExampleRootContext *a = dynamic_cast<ExampleRootContext*>(root());

  GrpcService grpc_service;
  grpc_service.mutable_envoy_grpc()->set_cluster_name(a->config_.clustername());  
  std::string grpc_service_string;
  grpc_service.SerializeToString(&grpc_service_string);

  HelloRequest request;
  request.set_name("fooo");
  std::string st2r = request.SerializeAsString();
  HeaderStringPairs initial_metadata;
  initial_metadata.push_back(std::pair("parent", "bar"));
  auto res =  root()->grpcCallHandler(grpc_service_string, HelloworldServiceName, SayHelloMethodName, initial_metadata, st2r, 1000,
                             std::unique_ptr<GrpcCallHandlerBase>(new MyGrpcCallHandler(this)));
  return FilterHeadersStatus::StopIteration;

  //addRequestHeader("fromenvoy", "newheadervalue");
  //return FilterHeadersStatus::Continue;
}

class MyGrpcCallHandler : public GrpcCallHandler<google::protobuf::Value> {
 public:
  MyGrpcCallHandler(ExampleContext *context) { context_ = context;  }

  void onSuccess(size_t body_size) override { 
    LOG_INFO(">>>>>>>>>>>>>  GRPC SUCCESS");
    WasmDataPtr response_data = getBufferBytes(WasmBufferType::GrpcReceiveBuffer, 0, body_size);
    const HelloReply& response = response_data->proto<HelloReply>();
    LOG_DEBUG(response.message());

    context_->setEffectiveContext(); 

    auto res = addRequestHeader("fromgrpc", response.message());
    if (res != WasmResult::Ok) {
      LOG_ERROR("Modifying Header data failed: " + toString(res));
    }
    continueRequest();  
  }
  void onFailure(GrpcStatus status) override {
    LOG_INFO(">>>>>>>>>>>>>  GRPC FAILURE");
    auto p = getStatus();
    LOG_DEBUG(std::string("failure ") + std::to_string(static_cast<int>(status)) +
             std::string(p.second->view()));
    context_->setEffectiveContext();              
    closeRequest();
  }

 private:
  ExampleContext *context_;

};
```

**Comment by salrashid123** [comment]
the `WasmResult` for the `grpcCallHandler()` shows `InternalFailure`

```
2020-10-14T11:13:49.643145Z	error	envoy wasm	wasm log: [examples/wasm/envoy_filter_http_wasm_example.cc:164]::onRequestHeaders() gRPCCall failed: InternalFailure
```

```c++
  auto res =  root()->grpcCallHandler(grpc_service_string, HelloworldServiceName, SayHelloMethodName, initial_metadata, st2r, 1000,
                              std::unique_ptr<GrpcCallHandlerBase>(new MyGrpcCallHandler(this)));

  if (res != WasmResult::Ok) {
    LOG_ERROR("gRPCCall failed: " + toString(res));
  }  

```

**Comment by salrashid123** [comment]
any suggestions on troubleshooting this?  (the only error i see even onthe proxy logs is  `InternalFailure`). 

as mentioned, i buildt the plugin using the default envoy 1.7 branch here and envoy `1.7.2` (tried `1.7.3` too today)
```
git clone --single-branch --branch  release-1.7 https://github.com/istio/envoy.git
```

note, i'm trying to call a grpc service thats in cluster...i think i set it up right

the wasm plugin loads the target service to contact

```yaml
                rootId: my_root_id
                configuration:
                  "@type": "type.googleapis.com/google.protobuf.StringValue"
                  value: |
                    {
                      "clustername": "ext-dlp.default.svc.cluster.local",
                    }  
```

and i define and run an incluster service 

https://gist.github.com/salrashid123/8252529c62c0ddb0c0cbc7d8eaa3f925

**Comment by salrashid123** [comment]
@kyessenov @douglas-reid 

could we reopen this?  I tried the sample envoy app again and it even held the connectin open to the downstream for ~30mins after failing on the grpc call.

Note, the istio config i'm using, i'm calling an incluster service

```log
2021-01-21T23:00:19.560706Z	warning	envoy wasm	wasm log: [examples/wasm/envoy_filter_http_wasm_example.cc:114]::onCreate() onCreate 2
2021-01-21T23:00:19.561353Z	error	envoy wasm	wasm log: [examples/wasm/envoy_filter_http_wasm_example.cc:142]::onRequestHeaders() Modifying Header data failed: InternalFailure

[2021-01-21T23:00:19.560Z] "GET /headers HTTP/1.1" 0 DC "-" 0 0 1228574 - "10.128.0.76" "curl/7.72.0" "d55b1565-151a-98e3-8a36-bc46d6ffdba3" "httpbin.example.com" "-" - - 10.12.3.9:80 10.128.0.76:0 outbound_.8000_._.httpbin.default.svc.cluster.local -


2021-01-21T23:20:48.154189Z	warning	envoy wasm	wasm log: [examples/wasm/envoy_filter_http_wasm_example.cc:172]::onLog() onLog 2
2021-01-21T23:20:48.154399Z	warning	envoy wasm	wasm log: [examples/wasm/envoy_filter_http_wasm_example.cc:170]::onDone() onDone 2
2021-01-21T23:20:48.154526Z	warning	envoy wasm	wasm log: [examples/wasm/envoy_filter_http_wasm_example.cc:174]::onDelete() onDelete 2
```

the service wasm is calling is `ext-dlp.default.svc.cluster.local`

```
$ kubectl get po,svc,pvc
NAME                           READY   STATUS    RESTARTS   AGE
pod/ext-dlp-756bfd45cb-s6mqt   2/2     Running   0          29m
pod/httpbin-5c8b98d945-rj7bz   2/2     Running   0          28m

NAME                 TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)     AGE
service/ext-dlp      ClusterIP   10.10.36.17   <none>        50051/TCP   29m
service/httpbin      ClusterIP   10.10.45.57   <none>        8000/TCP    28m
service/kubernetes   ClusterIP   10.10.32.1    <none>        443/TCP     175m
```

**Comment by fbalicchia** [comment]
Hi @salrashid123 I don't know if you already resolved but I think so. I stumbled into the same problem and to resolve I haven't needed to add additional structured but using this naming convention works for me `outbound|myport||myservice.istio-system.svc.cluster.local` in my case though filter was applied only on ingress

**Comment by salrashid123** [comment]
@fbalicchia  thanks. i actually never got it working (abandoned the effort)  but will give your suggestions a try...do you mean

the `set_cluster_name` here shoudl be in that format you used?

```cpp
  GrpcService grpc_service;
  grpc_service.mutable_envoy_grpc()->set_cluster_name(a->config_.clustername());  
```

---

i'm much more comfortable w/ go but grpc support there is not there yet
  https://github.com/tetratelabs/proxy-wasm-go-sdk/issues/14

**Comment by fbalicchia** [comment]
> @fbalicchia thanks. i actually never got it working (abandoned the effort) but will give your suggestions a try...do you mean
> 
> the `set_cluster_name` here shoudl be in that format you used?
> 
> ```c++
>   GrpcService grpc_service;
>   grpc_service.mutable_envoy_grpc()->set_cluster_name(a->config_.clustername());  
> ```

Yes I used this approach

**Comment by salrashid123** [comment]
ok, the rpc made it to the destination grpc server's proxy using name format you cited.

unfortunately, it stpps there since it can't resolve the name:

```
 invalid http2: Invalid HTTP header field was received: frame type: 1, 
     stream: 1, name: [:authority], value: [outbound|50051||ext-dlp.default.svc.cluster.local]
```

where there any other changes (i.,e overrides or filters) that was setup?

(this is kinda academic for me but it'd stil be good to get it working)


```log
2021-12-02T03:23:41.526598Z	debug	envoy filter	original_dst: New connection accepted
2021-12-02T03:23:41.526629Z	debug	envoy filter	tls inspector: new connection accepted
2021-12-02T03:23:41.526636Z	trace	envoy filter	tls inspector: recv: 2083
2021-12-02T03:23:41.526653Z	trace	envoy filter	tls:onALPN(), ALPN: istio-peer-exchange,istio,h2
2021-12-02T03:23:41.526662Z	debug	envoy filter	tls:onServerName(), requestedServerName: outbound_.50051_._.ext-dlp.default.svc.cluster.local
2021-12-02T03:23:41.527315Z	trace	envoy filter	Alpn Protocol Not Found. Expected istio-peer-exchange, Got h2
2021-12-02T03:23:41.527338Z	trace	envoy http2	Codec does not have Metadata frame support.

2021-12-02T03:23:41.527436Z	debug	envoy http2	[C403] invalid http2: Invalid HTTP header field was received: frame type: 1, stream: 1, name: [:authority], value: [outbound|50051||ext-dlp.default.svc.cluster.local]
2021-12-02T03:23:41.527441Z	debug	envoy http2	[C403] invalid frame: Invalid HTTP header field was received on stream 1
```

---

```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ext-dlp-virtualservice
spec:
  hosts:
  - ext-dlp
  - ext-dlp.default.svc.cluster.local
  gateways:
  - mesh
  http:   
  - match: 
    - uri:
        prefix: /  
    route:
    - destination:
        host: ext-dlp
        port:
          number: 50051   
---
```
