### ISSUE TITLE
ServiceEntry for OracleDB cause timeout exception

### ISSUE THREAD

**Issue by lukaszpy** [istio/istio#27934]
**Bug description**
We want to connect service to external Oracle DB cluster. When we define Serviceentry for DB we are getting timeout excpetion

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: milus-dev
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
        version: blue
    spec:
      containers:
        - name: database-blue
          image: $IMAGE_VAR
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 65
            timeoutSeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 5
      imagePullSecrets:
        - name: gitlab-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: milus-dev
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: database
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: database
  namespace: milus-dev
spec:
  hosts:
    - database-dev.lp-k8s-m2.milus.net
  gateways:
    - ingresgateway
  http:
  - route:
    - destination:
       host: database
       port:
        number: 8080 

```

ServiceEntry used for ORACLE:

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: milus-database
  namespace: milus-dev
spec:
  hosts:
    - milus.tcp.svc
  exportTo:
    - "."
  addresses:
    - 14.10.104.100/32
  ports:
    - number: 1521
      name: tcp
      protocol: TCP
  location: MESH_INTERNAL
  resolution: STATIC
  endpoints:
    - address: 111.37.74.70
      ports:
        tcp: 1521
```

connection string used in application:
`jdbc:oracle:thin:@//14.10.104.100:1521/mt-services`

also external DB has a walid host: 
`mirus-test-db.ista.net`
but even if we define SE with this host it gives same result.

exception geting in service:
`java.sql.SQLRecoverableException: IO Error: Connection reset by peer, connect lapse 3078 ms., Authentication lapse 0 ms.\n\tat oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:794)\n\tat oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:688)\n\tat oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:39)\n\tat oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:691)`

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

We are able to connect from service to external Oracle DB

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
```
istioctl:
client version: 1.7.0
control plane version: 1.7.0
data plane version: 1.7.0 (6 proxies)

kubectl:
Client Version: v1.19.0
Server Version: v1.19.0
```

**How was Istio installed?**
with Istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
On-Prem Kubernetes on virtual machines
