### ISSUE TITLE
Service Entry is getting the incorrect workloads with selector

### ISSUE THREAD

**Issue by iandyh** [istio/istio#27935]
**Bug description**
A sample serviceentry

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: multi-cluster-demo
spec:
  hosts:
  - sample.global
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 80
    protocol: http
  resolution: STATIC
  workloadSelector:
    labels:
      app: exporter-app
```
And have a deployment pointing to exporter-app. Restart the deployment couple of times you can see some stale endpoints lingering in the Envoy configurations. It does not happen after every restart but should be pretty easy to reproduce after couple of restarting. (The issue is gone after restarting the istiod)

Another observation: An unready pod could also be added to the outbound list, which should not happen. 

[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
ServiceEntry endpoint list should only contain serving pods that have passed the readiness check 

**Steps to reproduce the bug**
Described as above

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
```
client version: 1.7.0
control plane version: 1.7.3
data plane version: 1.7.3 (10 proxies), 1.7.1 (18 proxies), 1.6.5 (23 proxies), 1.6.4 (57 proxies), 1.6.8 (28 proxies)
```

**How was Istio installed?**
Istio operator

**Environment where bug was observed (cloud vendor, OS, etc)**
