### ISSUE TITLE
Don’t ignore prometheus-operator community

### ISSUE THREAD

**Issue by Morriz** [istio/istio#27940]
You have chosen to only target prometheus and stated that annotations have become "the defacto method" for configuration, but I think most deployments in the wild use prometheus-operator, which brought a more robust "standard": ServiceMonitor CRD. I strongly advise to add a flag to be able to choose deployment of these ServiceMonitor CRs by the operator.

Benefits: no metrics merging is needed (istio proxies/components will get their own endpoints) so the user can separately view metrics for istio only. This would allow for more community efforts into the realm of istio performance observability.

**Comment by Morriz** [comment]
Awesome. Did not see this before. I think it is a bit hard to navigate all the istio docs, which seem to be spread over multiple places.

But would those 2 service monitors in the example docs then cover all istio targets? And what about sane default alerting rules?

It would be nice to see support for the two prometheus scraping flavors that exist, and let the operator manage the prometheus configuration and resources. I don't think it makes sense to let the community keep up with the istio scraping endpoints. 

I am not deep into the matter, but as a platform engineer, this is my concern: that I can rely on the operator to deliver prometheus metrics with sane alerting rules out of the box.

So something like this could suffice imo:

```
prometheus:
  enabled: false
  rulesEnabled: # any istio rules? all enabled by default
    someRule: false # override, like in prom-op
  prometheusOperator:
    enabled: true # this will result in deployment of service monitors and deliver rules as CRs
  prometheus: '' # prometheus instance to deliver metrics to
```

Or am I on the wrong track here? I always feel a bit dumb as an outside user, but maybe that can help simplify things as well ;)
