### ISSUE TITLE
Doc example RequestAuthentication not working

### ISSUE THREAD

**Issue by hbeffge** [istio/istio#27943]
**Bug description**

Example of path based `RequestAuthentication` from the [docs](https://istio.io/latest/docs/reference/config/security/request_authentication/) (last example) is not working. I still get a 403 for `/healthz`

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Select a workload via label and except some paths from `RequestAuthentication` e.g. we have some paths on our ingress gateway which provide a opaque Access Token e.g. `Authorization: Bearer dsf5sd7f6d7fsdjkfh` which needs to be except from token verification.

**Steps to reproduce the bug**
Follow the docs

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
```
istioctl version --remote
client version: 1.7.3
control plane version: 1.7.0
data plane version: 1.7.0 (1 proxies)`
kubectl version --short
Client Version: v1.18.6
Server Version: v1.18.6
```

**How was Istio installed?**
Istio Operator

**Environment where bug was observed (cloud vendor, OS, etc)**
OnPrem Cluster

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching the dump file to this issue.

**Comment by Kampe** [comment]
I see the same issues using a keycloak server as the provider.

```
apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: "keycloak-authentication"
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
  - issuer: "http://keycloak:8080/auth/realms/istio"
    jwksUri: "http://keycloak:8080/auth/realms/istio/protocol/openid-connect/certs"
```
