### ISSUE TITLE
Istio port interception changes from 1.5 to 1.6 causing non-mtls failure

### ISSUE THREAD

**Issue by Stono** [istio/istio#27995]
**Bug description**
Something has changed between 1.5 and 1.6 meaning that the `istio-proxy` is intercepting all ports on the pod now, whereas I swear it used to only intercept ports explicitly defined in the `PodSpec`.

This manifests for us because all of our apps expose two ports, `8080` for web (mtls) and `9090` for prometheus metrics.  Only 8080 is defined in the `PodSpec` however:

```
    ports:                                                                                                                                                                                                         
    - containerPort: 8080
      name: http-web
      protocol: TCP 
```

And the sidecar:

```
  spec:
    ingress:
    - defaultEndpoint: 127.0.0.1:8080
      port:
        name: http-app
        number: 8080
        protocol: HTTP
    workloadSelector:
      labels:
        app: istio-test-app-1
        group: delivery-platform
```

Our prometheus instance plain-text scrapes 9090 and this works fine on 1.5.  After upgrading to 1.6, the scrape to `9090` failed unless we explicitly add an annotation on our workload `traffic.sidecar.istio.io/includeInboundPorts: 8080`

We tried to set `9090` as globally excluded in the main `PeerAuthentication` policy, but that didn't work either (see https://github.com/istio/istio/issues/27994)


[x] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure



**Expected behavior**
Minor version upgrades to not containing breaking changes.  For istio to only concern itself with ports defined in the `PodSpec` or `Sidecar`

**Steps to reproduce the bug**
Above

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
1.6.12

**How was Istio installed?**
Helm 

**Environment where bug was observed (cloud vendor, OS, etc)**
