### ISSUE TITLE
Circuit Breaker doesn't work with HTTPS

### ISSUE THREAD

**Issue by luiof** [istio/istio#27991]
Hi Team!
I am using the managed Istio 1.7.3 on a IKS cluster with the `REGISTRY_ONLY` mode enabled to allow only the hostname in my serviceentry.
I am trying to configure the circuit breaker with 502-503-504 errors. Following the official doc ([here](https://istio.io/latest/docs/tasks/traffic-management/circuit-breaking/)), I made some test.
Considering the following DestinationRule:
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: circuit-breaker-es
  namespace: <mynamespace>
spec:
  host: httpbin.org
  exportTo:
    - "."
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 5000 #Default 2^32-1
      http:
        http1MaxPendingRequests: 5000 #Default 2^32-1
        http2MaxRequests: 5000 #default 2^32-1
        maxRequestsPerConnection: 5000 # 0 unlimited up to 2^29
        maxRetries: 10 # Defaults to 2^32-1
    outlierDetection:
      consecutiveGatewayErrors: 1 #disabled by default or when set to the value 0 - 502, 503, or 504 return code qualifies as a gateway error
      consecutive5xxErrors: 1 #This feature defaults to 5 but can be disabled by setting the value to 0
      interval: 1s #1h/1m/1s/1ms. MUST BE >=1ms. Default is 10s
      baseEjectionTime: 30s #Minimum ejection duration - Default 30s
      maxEjectionPercent: 100 #default 10% - Maximum % of hosts in the load balancing pool for the upstream service that can be ejected
```
and the following ServiceEntry:
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: cb-es
  namespace: <mynamespace>
spec:
  hosts:
  - "httpbin.org"
  exportTo:
    - "."
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http-circuit-breaker-es
    protocol: HTTP
  - number: 443
    name: https-circuit-breaker-es
    protocol: HTTPS
  resolution: DNS
```

I made multiple tests changing the resolution between DNS and NONE to manage wildcard hosts also and to verify that it works with HTTPS also. But, the circuit breaker seems to be broken.
The changes are in the following table:
| Protocol | Resolution | Result |
| ------------- | ------------- | ------------- |
| HTTP | DNS  | Triggered 503 with success  |
| HTTPS  | DNS | Not working  |
| HTTP  | NONE | Not working  |
| HTTPS  | NONE | Not working  |

To trigger the 503 response (and to open the circuit breaker) with `HTTP` and `RESOLUTION: DNS` I executed the following command multiple times:
```
kubectl exec -it $POD -c $APPCONTAINER -n <mynamespace> -- curl -is http://httpbin.org/status/502

HTTP/1.1 200 OK
date: Thu, 15 Oct 2020 11:24:57 GMT
content-type: text/html; charset=utf-8
content-length: 0
server: envoy
access-control-allow-origin: *
access-control-allow-credentials: true
x-envoy-upstream-service-time: 165
```
that after some calls it returns me:
```
HTTP/1.1 503 Service Unavailable
content-length: 19
content-type: text/plain
date: Thu, 15 Oct 2020 11:25:07 GMT
server: envoy

no healthy upstream
```

Just to be sure, I executed the same command in parallel with:
```
seq 1 200 | xargs -n1 -P10 kubectl exec -it -it $POD -c $APPCONTAINER -n <mynamespace>-- curl -is http://httpbin.org/status/502
```
and the result are 503 as they should be. So the combination HTTP and DNS works.

After this, I tried the other three combinations without luck. The circuit breaker seems to be broken since the curl returns me always 502 as response code (I should get 503).

```
kubectl exec -it $POD -c $APPCONTAINER -n <mynamespace> -- curl -is https://httpbin.org/status/502

HTTP/2 502 
date: Thu, 15 Oct 2020 11:25:27 GMT
content-type: text/html; charset=utf-8
content-length: 0
server: gunicorn/19.9.0
access-control-allow-origin: *
access-control-allow-credentials: true
```
With this, I get always the same response code.

I need to use always the HTTPS protocol with some domains and with a subset of them I have to use a wildcard, so this is crucial to me.

Any ideas? The above yaml configuration is wrong? 
Maybe, with the HTTPS this doesn't work due to the lack of HTTPS inspection. Can this be the case?
