### ISSUE TITLE
Disable mTLS for application based on origin

### ISSUE THREAD

**Issue by Christoph-Raab** [istio/istio#27997]
**Describe the feature request**
Scenario A: I have pod A and pod B. Both are part of the mesh, meshwide mTLS is enabled.

Pod A is running. When pod B starts, an init-container does a http request to fetch some data and do something with that.
But since mTLS is enabled and pod B's sidecar is not running, pod B can not connect to pod A.

Scenario B: I have pod C and pod D. Pod C is part of the mesh. Meshwide mTLS is enabled.
Pod D is part of 3rd party library, using it with sidecar does not work.

For both scenarios I would like to have the possibility to disable mTLS for the host from a certain origin.

**Describe alternatives you've considered**
Scenario A:
- I could enabled PERMISSIVE mode for pod A, but I don't want that.
- I could use the ``traffic.sidecar.istio.io/excludeOutboundIPRanges`` annotation, but from my understanding this would fail because of mTLS.
https://istio.io/latest/docs/setup/additional-setup/cni/#compatibility-with-application-init-containers
- At the moment I am using a job with a sidecar instead of a init-container and a shared mounted volume. I first run the job. If that was successful I run pod B.

Sencario B:
- I have allowed PERMISSIVE mode for pod C, ok but not ideal.

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
If a different solution exists, please let me know.

**Comment by shankgan** [comment]
How do you hope to identify the "host" that is initiating the mTLS connection here? Not sure if IP ranges make sense in a K8s environment where the IP's keep changing. Or perhaps you are hoping to add an exception for mesh-wide mtLS for inbound connections from a particular service/service entry?

Trying to understand in scenario (A), how pod A will be able to distinguish between actual application running in pod B and the init-container, given that both of them will have the same IP.

**Comment by shankgan** [comment]
Adding @incfly for comment

**Comment by incfly** [comment]
For scenario A, I'm curious why would job solves the problem but not the init container? Are you saying the job container is running in the same pod of pod B and put the responded data from pod A into the shared volume? The difference here is that job would be able to send mTLS request but not your init container pod? Mind showing some details of the two setup's pod spec yaml? (Just sample snippet would be enough)

Scnario B, unclear to me why it matters if it's the 3rd party code?

**Comment by Christoph-Raab** [comment]
@incfly: 
> why would job solves the problem but not the init container

This is the config that I would like to run:
```
apiVersion: apps/v1
kind: StatefulSet
      [...]
spec:
      [...]
    spec:
      volumes:
        - name: share-B
          persistentVolumeClaim:
            claimName: share-B
      initContainers:
        - name: update-init
          image: placeholder/update-job
          volumeMounts:
            - mountPath: "/path"
              name: appdata-B
              subPath: "path"
      containers:
        - name: app
          image: placeholder/app
          volumeMounts:
            - mountPath: "/path"
              name: appdata-B
              subPath: "path"
```
The 'update-init' init-container fetches some data via http from another pod and does some config in the app-data-B share. After that the main app runs using this configured data. But the update-init doesn't work, because of mTLS and the missing sidecar.

So I run a Job, that does the same as the init-container and because it runs in it's own pod, there is a sidecar and everything works fine.
```
apiVersion: batch/v1
kind: Job
  [...]
spec:
      [...]
    spec:
      volumes:
        - name: share-B
          persistentVolumeClaim:
            claimName: share-B
      containers:
        - name: update-job
          image: placeholder/update-job
          volumeMounts:
            - mountPath: "/path"
              name: share-B
              subPath: "path"
```
After that I can run the app from above but without the init-container.
It's not the best workflow but it's an legacy application, so I can not change this.

> Scnario B, unclear to me why it matters if it's the 3rd party code?

I work with keda to fetch metrics from my RabbitMQ (inside mesh) and scale some pods based on that. Keda seams to have a specific setup process on startup for ssl, etc. When I label the keda namespace with sidecar injection, the keda application can not start, because of issues reaching the kube-apiserver. Maybe this could be solved with the new "hold application until proxy startup" feature. But I rather think that I have to configure istio behavior per pod in the keda namespace. Meaning I would have to download the sources and change them manually, which I don't want to do.

At the moment I run keda outside the mesh and have ``PERMISSIVE`` mode enabled on the management port of rabbitMq, so keda can fetch metrics. But that feels like a workaround.

>How do you hope to identify the "host" that is initiating the mTLS connection here? Not sure if IP ranges make sense in a K8s environment where the IP's keep changing. Or perhaps you are hoping to add an exception for mesh-wide mtLS for inbound connections from a particular service/service entry?

An exception would be a good start. In the end I want mTLS everywhere. And I would like to disable it for a given scenario (A/B), but not for every orgin. Best would be that the sidecar would accept inbound traffic as plain text or mTLS for a certain sender and mTLS only for everyone else.
I don't know enough about kubernetes/istio networking internals to answer your question of how to achieve that. 

Maybe my init-container app can set a specific header with kubernetes secret and receiving sidecar can work with that? Not 100 % save, but still better than enabling PERMISSIVE mode.

As I said, if there is a solution to solve scenario A/B, I am open to use that.
