### ISSUE TITLE
how can we write a authorization policy on ingress gateway which allows request only when request payload have certain header value

### ISSUE THREAD

**Issue by Bhanu88** [istio/istio#28008]
I am trying to write an authorization policy on ingress gateway which blocks all the request which do not contain a certain header with a specific value

currently as per doc ingress gateway only support IP based filtering which works fine

```
kubectl apply -f - <<EOF
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: journeyapi-app
 namespace: istio-system
spec:
 selector:
   matchLabels:
     app: xxxxxxxxx-app
 action: ALLOW	 
 rules:
  - to:
    - operation:
        methods: ["GET", "PUT", "POST", "OPTIONS", "PATCH", "DELETE"]
    when:
    - key: request.headers[kube-token]
      values: ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
EOF
```
.
above policy works fine for a defined app but if I want to apply in ingress gateway authorization poly then what should be the way 

my ingress policy looks like this 
```
kubectl apply -f - <<EOF
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ingress-policy
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  action: ALLOW
  rules:
  - from:
    - source:
       ipBlocks: ["xxxxxxxxxx","xxxxxxxxxx","xxxxxxxxxx"]
EOF
```

currently, I am using istio 1.7.3 on azure AKS

Affected product area (please put an X in all that apply)

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastrcture

I appreciate any guidance or help

**Comment by xulingqing** [comment]
Hi Bhanu,

You can try using [authentication with tokens per path](https://istio.io/latest/docs/tasks/security/authentication/authn-policy/#require-valid-tokens-per-path). 
@yangminzhu  do you have any suggestions?

**Comment by Bhanu88** [comment]
combination of following policy work perfectly for me in the case where I want to allow request on basis of the certain token value

```
kubectl apply -f - <<EOF
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-all
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
EOF
```



```
kubectl apply -f - <<EOF
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: ingpolicy
 namespace: istio-system
spec:
 selector:
   matchLabels:
     app: istio-ingressgateway
 action: ALLOW	 
 rules:
 - to:
   - operation:
       methods: ["GET", "PUT", "POST", "OPTIONS", "PATCH", "DELETE"]
   when:
   - key: request.headers[kube-token]
     values: ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
EOF

```
