### ISSUE TITLE
Istioctl not generate pod securityContext

### ISSUE THREAD

**Issue by twitty-onica** [istio/istio#28014]
**Bug description**
In a new, clean deployment of Istio 1.6.9 on Kubernetes 1.17.11. Istioctl is not respecting the SecurityPolicy field for istio-ingressgateway.

Below is a snippet from the overlay file
```
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
```

This securityContext field is not being set in the pod spec for the generated `istio-ingressgateway` deployment manifest.
The runAsUser and runAsGroup needs to be set in order to ensure non-root policy enforcement by our PSPs so the pod can start.

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

```
istioctl version --remote
client version: 1.6.9
control plane version: 1.6.9
data plane version: none
```

**How was Istio installed?**
istioctl with overlay file

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS
