### ISSUE TITLE
xds-grpc 15010 always use tls, controlPlaneAuthPolicy not working

### ISSUE THREAD

**Issue by zhongfox** [istio/istio#28028]
**Bug description**

try xds-grpc using port 15010, but envoy always try to connect istiod with tls.
I tried :
1. annotation for pod "sidecar.istio.io/controlPlaneAuthPolicy: NONE"
2. change  in global mesh config : "controlPlaneAuthPolicy: NONE" 
no one works

mesh config:

```
apiVersion: v1
data:
  mesh: |-
    accessLogFile: /dev/stdout
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15010
      controlPlaneAuthPolicy: NONE

```

pod:

```

  metadata:
    annotations:
      sidecar.istio.io/controlPlaneAuthPolicy: NONE
      sidecar.istio.io/discoveryAddress: kdebug.default:8080
    labels:
      app: sleep
  spec:

```

version: 1.7.3
