### ISSUE TITLE
[1.5] EnvoyFilter not adding listeners. Errors with "Error adding/updating listener(s) proxy: duplicate listener proxy found"

### ISSUE THREAD

**Issue by DandyDeveloper** [istio/istio#28022]
**Bug description**
I'm trying to apply the following LISTENER with a bunch of filter chains through the EnvoyFilter CRD: 

```  yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: new-proxy
  namespace: ytest 
spec:
  workloadSelector:
    labels:
      release: xyz
  configPatches:
  - applyTo: LISTENER
    patch:
      operation: ADD
      value:
        name: proxy
        address:
          socket_address:
            protocol: TCP
            address: 0.0.0.0
            port_value: 8083
        filter_chains:
        - filters:
          - name: "envoy.http_connection_manager"
            config:
              stat_prefix: ingress_proxy
              route_config:
                name: route_a
                virtual_hosts:
                - name: envoy_cyz
                  domains:
                  - "domain.x"
                  routes:
                  - match:
                      prefix: "/api/v1/cyz"
                    route:
                      cluster: cluster123
  - applyTo: CLUSTER
    patch:
      operation: ADD
      value:
        name: cluster123
        connect_timeout: 2.00s
        type: STRICT_DNS
        dns_lookup_family: V4_ONLY
        max_requests_per_connection: 1
        hosts:
        - socket_address:
            address: xyz
            port_value: 80
```

However, after adding this, I get the following error in sidecar injected pods:
```
[Envoy (Epoch 0)] [2020-10-16 04:33:16.104][27][warning][config] [external/envoy/source/common/config/grpc_subscription_impl.cc:87] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) proxy: duplicate listener proxy found
...
2020-10-16T04:40:39.619300Z     info    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 3 successful, 0 rejected; lds updates: 0 successful, 3 rejected
```

This then leaves the pod in a NotReady. But if I look at it through istioctl:
> istioctl proxy-config listener $POD -n ytest --port 8083
```
ADDRESS     PORT     TYPE
0.0.0.0     8083     HTTP
```

And outputting json shows all the routers. Clusters are also added successfully to this pod. 

Is this a bug in 1.5? I can't find any historic issues about this. 

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Listener is added and pod is in ready state. 

**Steps to reproduce the bug**
Apply the above CRD to a 1.5 Istio (Deployed using Istioctl operator)

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
istio:
```
client version: 1.5.4
control plane version: 1.5.4
data plane version: 1.5.4 (162 proxies)
```

k8s:
```
Client Version: v1.19.2
Server Version: v1.14.10
```

**How was Istio installed?**
Istioctl Operator using a custom profile. 

**Environment where bug was observed (cloud vendor, OS, etc)**
BareMetal  (CoreOS)

**Comment by bianpengyuan** [comment]
I think you need to add direction context:
```
  configPatches:
  - applyTo: LISTENER
    match:
      context: SIDECAR_INBOUND
    patch:
      operation: ADD
      value:
```
