### ISSUE TITLE
ISTIOD_ENABLE_SDS_SERVER=true connection reset by peer

### ISSUE THREAD

**Issue by nmnellis** [istio/istio#28029]
**Bug description**
Enabling ISTIOD_ENABLE_SDS_SERVER (which is now default) causes our https tests to fail. We currently mount certificates to our gateway and when upgrading istio our https endpoints now fail

```
 2020-10-16T06:45:38.107866Z	error	tf	Attempt 3: send request failed with status code: -1: failed to send request for https://httpbin.tetrate.io:8443/headers with method GET: Get "https://httpbin.tetrate.io:8443/headers": dial tcp 172.18.255.166:8443: connect: connection refused


2020-10-16T06:46:04.351643Z	error	tf	Attempt 3: send request failed with status code: -1: failed to send request for https://httpbin.tetrate.io:8443/headers with method GET: Get "https://httpbin.tetrate.io:8443/headers": read tcp 172.18.0.1:35556->172.18.255.166:8443: read: connection reset by peer
```

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Https ports would work with mounted certificates.

Attached envoy logs of gateways as well as istiod logs

[envoy.log](https://github.com/istio/istio/files/5391846/envoy.log)
[istiod.log](https://github.com/istio/istio/files/5391849/istiod.log)

Found these in istiod logs. might be relavent
```
2020-10-15T19:52:20.819159802Z stdout F 2020-10-15T19:52:20.819084Z	error	authorization	skipped rule ns[httpbin-gateway-1-32651]-policy[e2e-test-gw-httpbin-mesh-internal]-rule[0]: :authority must not be used in TCP
2020-10-15T19:52:20.819176205Z stdout F 2020-10-15T19:52:20.819106Z	erro


r	authorization	skipped rule ns[httpbin-gateway-1-32651]-policy[e2e-test-gwmesh-external]-rule[0]: :authority must not be used in TCP
```

**Steps to reproduce the bug**

Use the below configuration for a gateway and attempt to hit the https endpoint. https works if ISTIOD_ENABLE_SDS_SERVER=false

Operator Config
```yaml
meshConfig:
  accessLogFile: "/dev/stdout"
  defaultConfig:
    proxyMetadata:
      ISTIO_META_PROXY_XDS_VIA_AGENT: "true"
      ISTIO_META_DNS_CAPTURE: "true"
values:
  global:
    proxy:
      logLevel: debug
components:
  pilot:
    k8s:
      env:
      - name: PILOT_SCOPE_GATEWAY_TO_NAMESPACE
        value: "true"
      - name: PILOT_FILTER_GATEWAY_CLUSTER_CONFIG
        value: "true"
      - name: ISTIOD_ENABLE_SDS_SERVER
        value: "true"
  ingressGateways:
  - name: istio-ingressgateway
    enabled: false
  - name: istio-egressgateway
    enabled: false
  - name: istio-eastwestgateway
    enabled: false    
  - name: httpbin-gateway
    namespace: httpbin-gateway-1-71427
    enabled: true
    label:
      app: httpbin-gateway
    k8s:
      env:
      - name: ISTIO_META_ROUTER_MODE
        value: "standard"
      service:
        ports:
        ## Default ports
        - port: 15021
          targetPort: 15021
          name: status-port
        - port: 8080
          targetPort: 8080
          name: http2
        - port: 8443
          targetPort: 8443
          name: https
        - port: 15443
          name: https-istio
      hpaSpec:
        maxReplicas: 1
        minReplicas: 1
      resources:
        requests:
          cpu: 10m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 1024Mi
```

```yaml
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: httpbin-gw
  namespace: xcp-system
spec:
  selector:
    app: httpbin-gateway
  servers:
    - port:
        number: 8443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: xcp-gateway-simple-http-1
      hosts:
        - "httpbin.tetrate.io"
    - port:
        number: 8080
        name: http
        protocol: HTTP
      hosts:
        - "httpbin.tetrate.io"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpbin-vs
  namespace: xcp-system
spec:
  hosts:
    - "httpbin.tetrate.io"
  gateways:
    - httpbin-gw
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: simple-http-1.httpbin-simple-2-61349.svc.cluster.local
            port:
              number: 8080
      retries:
        attempts: 1
        perTryTimeout: 2s

```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
istio-testing:1.8-alpha.3590fd8b69526a43411b58dbad2215a04eee7b3b

**How was Istio installed?**
Istio test framework: 
istio-testing:1.8-alpha.3590fd8b69526a43411b58dbad2215a04eee7b3b

**Environment where bug was observed (cloud vendor, OS, etc)**
Kind cluster using istio test framework
