### ISSUE TITLE
Make injection template customizable for operator based installs.

### ISSUE THREAD

**Issue by liamawhite** [istio/istio#28038]
**Describe the feature request**
Currently, customising the sidecar injector template requires an overlay replacing the entire injection `ConfigMap`, not just the template.

```
  components:
    pilot:
      k8s:
        overlays:
        - apiVersion: v1
          kind: ConfigMap
          name: istio-sidecar-injector
          patches:
          - path: data
            value:
			  <entire-sidecar-injector-config-map-plus-modifications>
```

This will mean any fields set outside of the template ([config](https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/templates/istiod-injector-configmap.yaml#L20) or [`.Values`](https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/templates/istiod-injector-configmap.yaml#L12)) in the Operator API will need to be changed in this overlay as well. Ideally, I would like to provide/edit the injector template only.

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
