### ISSUE TITLE
[1.7.3] Intermittent SSL errors with endpoints outside the mesh

### ISSUE THREAD

**Issue by kmai** [istio/istio#28030]
**Bug description**

Using EKS/AWS, with mTLS permissive and mesh outboundTrafficPolicy set to ALLOW_ANY, connections to HTTPS/TCP endpoints outside the mesh either fail. 

This behaviour started after upgrading from 1.6.7 using the demo profile to 1.7.3 with the default profile.

I don't see RDS being pushed to the egress gateway, but sidecars should use the Passthrough cluster if traffic is not forced through the egress.

Adding a virtual service, DR and gateway for the egress gateway returned connectivity, but it should not be necessary.

Documentation isn't clear on how to troubleshoot serviceEntries in this scenario.

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Pods with sidecar injection shouldn't have trouble connecting to an endpoint outside the cluster, specially if the traffic is not forced through the egress gateway.

**Steps to reproduce the bug**

Deploy using istioctl and the following command (using the 1.6.7 tooling):

```
istioctl install --set profile=demo --set meshConfig.outboundTrafficPolicy.mode=ALLOW_ANY
```

Then upgrade to 1.7.3 and changing to use this manifest:

```yaml 
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: staging-istiocontrolplane
spec:
  profile: default
  meshConfig:
    outboundTrafficPolicy:
      mode: ALLOW_ANY

  addonComponents:
    istiocoredns:
      enabled: true

  components:
    egressGateways:
      - name: istio-egressgateway
        enabled: true

  values:
    global:
      # Provides dns resolution for global services
      podDNSSearchNamespaces:
        - global

      multiCluster:
        enabled: true

      controlPlaneSecurityEnabled: true

    gateways:
      istio-egressgateway:
        env:
          # Needed to route traffic via egress gateway if desired.
          ISTIO_META_REQUESTED_NETWORK_VIEW: "external"
```

(Using istioctl 1.7.3):

`istioctl upgrade -f manifest.yaml`

Related, I know there is a bug regarding `installed-state` not being updated: https://github.com/istio/istio/issues/27973#issuecomment-709586892

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

Istio
```
istioctl version --remote
client version: 1.7.3
control plane version: 1.7.3
data plane version: 1.7.3 (39 proxies), 1.6.7 (1 proxies)
```

Kubernetes
```
kubectl version --short
Client Version: v1.17.9
Server Version: v1.17.9-eks-4c6976
```

**How was Istio installed?**
istioctl 1.6.7 using demo profile and `--set` parameters -> upgrade done through istioctl 1.7.3 + manifest

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS/EKS 1.17.9
