### ISSUE TITLE
Istio Operator marks status of Gateway as Healthy even though pods are not ready

### ISSUE THREAD

**Issue by bnutt** [istio/istio#28041]
**Bug description**
When running the istio gateway as a Daemonset and using update strategy: OnDelete, the istio operator will mark the istio gateway status as healthy even though changes to the Daemonset have not been propagated. 

The root cause of this seems to be that in https://github.com/istio/istio/blob/1.7.3/operator/pkg/helmreconciler/wait.go#L88 we only check if the pods of the Daemonset are ready, this gives a false positive because the new pods of the Daemonset have not even be scheduled yet due to OnDelete update strategy. The fix should be to have a method similar to [deploymentReady](https://github.com/istio/istio/blob/1.7.3/operator/pkg/helmreconciler/wait.go#L263), which checks if the *new* pods in the replicaset are all ready before marking the deployment as ready. Similarly, daemonsetReady should check if status.numberReady < status.desiredNumberScheduled. This would keep the operator status in a reconciling state until the gateway pods have been replaced with the new revision. Regardless of the usage of OnDelete, the check for the readiness of the Daemonset should involve checking the status of the Daemonset object vs the pods currently in the Daemonset.

I believe this same issue could be observed in StatefulSet's as well, if someone chose to run the control plane that way. Fixing this is important for those who decide to not run their gateway as a deployment and want the confidence that when the operator marks the status of the gateway as healthy, it is matching with the state of the cluster.

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**
1. Create istiooperator resource which deploys an istio gateway as a Daemonset instead of a deployment and updateStrategy: OnDelete. 

# install.yaml
```
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
  namespace: istio-system
spec:
  components:
    base:
      enabled: true
    ingressGateways:
    - enabled: true
      k8s:
        overlays:
        - kind: Deployment
          name: istio-ingressgateway
          patches:
          - path: kind
            value: DaemonSet
          - path: spec.strategy
          - path: spec.updateStrategy
            value: |
              type: OnDelete
        - kind: Service
          name: istio-ingressgateway
          patches:
          - path: spec.externalTrafficPolicy
            value: Local
        service:
          ports:
          - name: http2
            port: 80
            targetPort: 8080
          - name: https
            port: 443
            targetPort: 8443
      label:
        app: istio-ingressgateway
      name: istio-ingressgateway
```

2. Deploy istio operator using istioctl.

  `istioctl operator init`

3. Apply resource specified in step 1.
  `kubectl create -f install.yaml`
4. Wait for all gateway and istiod pods to be up and running.

5. Add new port to istiogateway service to force a change of the daemonset.

```
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
  namespace: istio-system
spec:
  components:
    base:
      enabled: true
    ingressGateways:
    - enabled: true
      k8s:
        overlays:
        - kind: Deployment
          name: istio-ingressgateway
          patches:
          - path: kind
            value: DaemonSet
          - path: spec.strategy
          - path: spec.updateStrategy
            value: |
              type: OnDelete
        - kind: Service
          name: istio-ingressgateway
          patches:
          - path: spec.externalTrafficPolicy
            value: Local
        service:
          ports:
          - name: http2
            port: 80
            targetPort: 8080
          - name: https
            port: 443
            targetPort: 8443
         - name: tcp
            port: 25
      label:
        app: istio-ingressgateway
      name: istio-ingressgateway
```

6. Check istio gateway service to observe that service now has new port exposed.

`kubectl get svc -n istio-system`
```
NAME                           TYPE           CLUSTER-IP     EXTERNAL-IP    PORT(S)                                         AGE
istio-ingressgateway  LoadBalancer   REDACTED REDACTED    80:30499/TCP,443:30458/TCP,25:30665/TCP         5h12m
```

7. Check istio gateway pod. Since OnDelete is set, the pods will not be deleted. This is expected.
`kubectl get ds -n istio-system`

```
NAME                           DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE    CONTAINERS    IMAGES                          SELECTOR
istio-ingressgateway  3         3         3       0            3           <none>          5h9m   istio-proxy   docker.io/istio/
```

8. However, the istio operator will mark the update as healthy when it should be reconciling because the daemonset is not up to date yet and the port change has not been applied. 

```
kubectl describe iop -n istio-system
...
...
Status:
  Component Status:
    Base:
      Status:  HEALTHY
    Ingress Gateways:
      Status:  HEALTHY
```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

istioctl version --remote:
```
client version: 1.7.3
control plane version: 1.7.3
data plane version: 1.7.3 (6 proxies)
````

kubectl version --short:
```
Client Version: v1.16.13
Server Version: v1.16.15
```
**How was Istio installed?**
Istio Operator, version 1.7.3
**Environment where bug was observed (cloud vendor, OS, etc)**
Any cloud.
