### ISSUE TITLE
Issue when using coreDNS rewrite to point to outbound proxy

### ISSUE THREAD

**Issue by jacob-koren-zooz** [istio/istio#28049]
**Environment:**
EKS 1.15
Istio 1.4.7

**Description:**
We are trying to build an outbound filtering feature into our k8s system. The general idea is that coreDNS rewrites a query to an external domain into an internal k8s service that serves as a proxy.
An example connection would be:
Client pod (client.apps.svc.cluster.local) makes a call to github.com -> coreDNS rewrites the DNS query to k8s-nginx-test.outbound.svc.cluster.local -> Nginx proxy service gets the request -> Nginx pod passthrough the request external domain.
_apps_ - namespace with sidecar injection
_outbound_ - namespace without sidecar injection
That works well when the client is in a namespace without istio. However, when the client is in a namespace with istio we get 404.
We checked the Nginx proxy logs, envoy logs and sniffed the traffic and it's clear that client pods envoy returns this 404 answer.

Looking at the docs we tried to resolve the issue using virtual service and egress rule without success.
**Config:**
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: k8s-nginx-test
spec:
  hosts:
  - "github.com"
  http:
  - timeout: 5s
    route:
    - destination:
        host: k8s-nginx-test.outbound.svc.cluster.local
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: outbound-traffic
spec:
  hosts:
  - github.com
  location: MESH_EXTERNAL
  ports:
  - name: outbound
    number: 80
    protocol: HTTP
  resolution: DNS
```

**Client pod envoy logs:**

> [Envoy (Epoch 0)] [2020-10-16 10:13:44.959][22][debug][upstream] [external/envoy/source/common/upstream/strict_dns_cluster.cc:156] DNS refresh rate reset for github.com, refresh rate 5000 ms
> [Envoy (Epoch 0)] [2020-10-16 10:13:44.983][29][debug][filter] [external/envoy/source/extensions/filters/listener/original_dst/original_dst.cc:18] original_dst: New connection accepted
> [Envoy (Epoch 0)] [2020-10-16 10:13:44.984][29][debug][filter] [external/envoy/source/extensions/filters/listener/tls_inspector/tls_inspector.cc:78] tls inspector: new connection accepted
> [Envoy (Epoch 0)] [2020-10-16 10:13:44.984][29][debug][filter] [external/envoy/source/extensions/filters/listener/http_inspector/http_inspector.cc:37] http inspector: new connection accepted
> [Envoy (Epoch 0)] [2020-10-16 10:13:44.984][29][debug][conn_handler] [external/envoy/source/server/connection_handler_impl.cc:333] [C107] new connection
> [Envoy (Epoch 0)] [2020-10-16 10:13:44.984][29][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:259] [C107] new stream
> [Envoy (Epoch 0)] [2020-10-16 10:13:44.984][29][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:708] [C107][S5187076473235402788] request headers complete (end_stream=true):
> ':authority', 'github.com'
> ':path', '/'
> ':method', 'GET'
> 'user-agent', 'curl/7.60.0'
> 'accept', '*/*'
> [Envoy (Epoch 0)] [2020-10-16 10:13:44.984][29][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1257] [C107][S5187076473235402788] request end stream
> [Envoy (Epoch 0)] [2020-10-16 10:13:44.984][29][debug][filter] [src/envoy/http/mixer/filter.cc:47] Called Mixer::Filter : Filter
> [Envoy (Epoch 0)] [2020-10-16 10:13:44.984][29][debug][filter] [src/envoy/http/mixer/filter.cc:148] Called Mixer::Filter : setDecoderFilterCallbacks
> [Envoy (Epoch 0)] [2020-10-16 10:13:44.984][29][debug][filter] [src/envoy/http/mixer/filter.cc:60] Called Mixer::Filter : decodeHeaders
> [Envoy (Epoch 0)] [2020-10-16 10:13:44.984][29][debug][filter] [./src/envoy/utils/header_update.h:45] Mixer forward attributes set: CjgKCnNvdXJjZS51aWQSKhIoa3ViZXJuZXRlczovL3NsZWVwLTZiYzQ3N2Q0NjgtcTY1MmQuYXBwcw==
> [Envoy (Epoch 0)] [2020-10-16 10:13:44.984][29][debug][filter] [src/envoy/http/mixer/filter.cc:156] Called Mixer::Filter : check complete OK
> [Envoy (Epoch 0)] [2020-10-16 10:13:44.984][29][debug][router] [external/envoy/source/common/router/router.cc:376] [C107][S5187076473235402788] no cluster match for URL '/'
> [Envoy (Epoch 0)] [2020-10-16 10:13:44.984][29][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1354] [C107][S5187076473235402788] Sending local reply with details route_not_found
> [Envoy (Epoch 0)] [2020-10-16 10:13:44.984][29][debug][filter] [src/envoy/http/mixer/filter.cc:135] Called Mixer::Filter : encodeHeaders 2
> [Envoy (Epoch 0)] [2020-10-16 10:13:44.984][29][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1552] [C107][S5187076473235402788] encoding headers via codec (end_stream=true):
> ':status', '404'
> 'date', 'Fri, 16 Oct 2020 10:13:44 GMT'
> 'server', 'envoy'
>
