### ISSUE TITLE
Weigh-based routing for ServiceEntry not working

### ISSUE THREAD

**Issue by alekodu** [istio/istio#28054]
**Bug description**
For istio replicated control plane, the weighted load balancing ServiceEntry->Endpoint->weight seems not to be working.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
I expect requests to be routed to the service entries based on the assigned weights.

**Steps to reproduce the bug**
I have a setup with 3 clusters. I created a namespace called sample and enabled sidecar injection. Then I deployed helloworld-v1 in cluster1 and helloworld-v2 in cluster 3. Furthermore, I deployed sleep in cluster2.

Then I created a ServiceEntry to have access from sleep to the helloworld instances in the remote clusters by:

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: helloworld-sample-c1
  namespace: sample
spec:
  addresses:
  - 240.0.0.2
  - 240.0.0.3
  endpoints:
  - address: $IP_IGW_CLUSTER1
    ports:
      http1: 15443
    weight: 100
  - address: $IP_IGW_CLUSTER3
    ports:
      http1: 15443
    weight: 0
  hosts:
  - helloworld.sample.global
  location: MESH_INTERNAL
  ports:
  - name: http1
    number: 5000
    protocol: http
  resolution: DNS
```

When I call: kubectl exec --context=cluster2 -it -n sample -c sleep $(kubectl get pod --context=cluster2 -n sample -l app=sleep -o jsonpath='{.items[0].metadata.name}') -- curl helloworld.sample.global:5000/hello

I still can access to both versions, the one in cluster1 and the one in cluster3, even though the weights indicate to route all requests to the helloworld version in cluster1.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
istioctl version --remote:
client version: 1.5.10
control plane version: 1.5.10
data plane version: 1.5.10 (4 proxies)

kubectl version --short:
Client Version: v1.14.0
Server Version: v1.17.0

**How was Istio installed?**
Following https://istio.io/v1.5/docs/setup/install/multicluster/gateways/

**Environment where bug was observed (cloud vendor, OS, etc)**
Local deployment based on KinD
