### ISSUE TITLE
"enablePrometheusMerge: true" not merging the app metrics with Istio's in 1.7.3

### ISSUE THREAD

**Issue by alexandrefilgueira** [istio/istio#28069]
**Bug description**
Deployed Istio 1.7.3 with meshConfig.enablePrometheusMerge to TRUE, and addonComponents.prometheusOperator.enabled to TRUE.
My services had already prometheus.io annotations and after restarting, I can see that Istio overwrote those with the ones that Istio uses and as env variables I can see the old values, for example:

`ISTIO_PROMETHEUS_ANNOTATIONS:  {"scrape":"true","path":"/metrics","port":"50000"}
`

I can also see in prometheus the rule istio-system/envoy-stats-monitor created based on the installed ServiceMonitor by Istio all the services UP.

But trying to query my metrics from prometheus or just doing a curl request to :15090/stats/prometheus of one of my services only returns Istio's metrics, and not our app's metrics.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
I should be able to see my app's metrics when enablePrometheusMerge is TRUE using Prometheus Operator.

**Steps to reproduce the bug**
Install  Istio 1.7.3 with the following config in the manifest:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  hub: docker.io/istio
  tag: 1.7.3

  meshConfig:
    enablePrometheusMerge: true
 
  addonComponents:
    prometheusOperator:
      enabled: true

    prometheus:
      enabled: false
```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

1.7.3

**How was Istio installed?**

istioctl install -f manifest.yaml

**Environment where bug was observed (cloud vendor, OS, etc)**

Cloud vendor: Google Cloud GKE
Kubernetes:  v1.16.13
