### ISSUE TITLE
EnvoyFilter httpCall/ClusterDefinition not working as expected with Istio 1.7

### ISSUE THREAD

**Issue by bleggett** [istio/istio#28108]
**Bug description**
According to https://istio.io/latest/docs/reference/config/networking/envoy-filter/ (and all other docs I can find on the subject), the following EnvoyFilter should redirect all outgoing HTTP requests to `127.0.0.1:3001/proxy` in the same pod:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: proxy-filter
  namespace: default
  labels:
    app: sa-istio-config
    chart: sa-istio-config-0.2.0
    release: RELEASE-NAME
    heritage: Helm
spec:
  workloadSelector:
    labels:
      filter-applied: "true"
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_OUTBOUND
      listener:
        # portNumber: 80
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.router"
    patch:
      operation: INSERT_BEFORE
      value: # lua filter specification
        name: envoy.filters.http.lua
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
          inlineCode: |
            function envoy_on_request(handle)
              local path = handle:headers():get(":path")
              local auth = handle:headers():get(":authority")
              handle:logInfo(string.format("Request from authority: %s and path %s", auth, path))
              if not handle:headers():get("filtered") and not string.match(path, "^/hub") then
                handle:logInfo("passing request to proxy-sidecar")

                local headers, body = handle:httpCall(
                "lua_cluster",
                {
                  [":method"] = "HEAD",
                  [":path"] = "/proxy",
                  [":authority"] = "127.0.0.1",
                },
                "",
                300000)

                handle:logInfo(headers[":status"])
              end
              handle:logInfo("end request")

            end
            function envoy_on_response(handle)
            end

  # The second patch adds the cluster that is referenced by the lua code
  # cds match is omitted as a new cluster is being added
  - applyTo: CLUSTER
    patch:
      operation: ADD
      value: # cluster specification
        name: "lua_cluster"
        type: STRICT_DNS
        connect_timeout: 0.5s
        lb_policy: ROUND_ROBIN
        hosts:
        - socket_address:
            protocol: TCP
            address: "127.0.0.1"
            port_value: 3001


  ## This patch makes sure header casing is correct
  - applyTo: NETWORK_FILTER # http connection manager is a filter in Envoy
    match:
      # if context omitted then this applies to both sidecars and gateways
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager"
          http_protocol_options:
            header_key_format:
              proper_case_words: {}

``` 

Instead, the `httpCall` from the filter never reaches the proxy sidecar in the same pod, and I get this:

```
2020-10-20T16:32:35.032182Z info envoy lua script log: Request from authority: test.s3.amazonaws.com and path /housing-data/plaintext.csv
2020-10-20T16:32:35.032198Z info envoy lua script log: passing request to proxy-sidecar
2020-10-20T16:32:35.032253Z debug envoy lua async HTTP response complete
2020-10-20T16:32:35.032269Z info envoy lua script log: 503
2020-10-20T16:32:35.032273Z info envoy lua script log: end request
2020-10-20T16:32:35.032277Z debug envoy lua coroutine finished
2020-10-20T16:32:35.052586Z debug envoy lua coroutine finished
```

I have verified that manually invoking `curl -I http://127.0.0.1:3001/proxy` from the `istio-proxy` sidecar **_does_** reach the proxy sidecar in the same pod, so why can't `handle:httpCall`?

Either the docs are wrong/outdated, or there's a bug here. From what I can tell, the above produces valid Envoy configuration, so I'm at a loss.

[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
The filter definition above should trigger on all outgoing HTTP pod traffic, and issue an HTTP request to `127.0.0.1:3001/proxy`

**Steps to reproduce the bug**
Apply the above and test with an echo server pod.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

» istioctl version --remote                                                                                                                                                                          
client version: 1.7.3
control plane version: 1.7.3
data plane version: 1.7.3 (10 proxies)

 » kubectl version --short                                                                                                                                                                            
Client Version: v1.19.3
Server Version: v1.17.9-eks-4c6976

------------------------------------------------

**How was Istio installed?**

istioctl install \
    --set profile=demo \
    --set meshConfig.accessLogFile="/dev/stdout" \

**Environment where bug was observed (cloud vendor, OS, etc)**

EKS cluster running k8s 1.17.9

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching the dump file to this issue.

[istio-dump.tar.gz](https://github.com/istio/istio/files/5410288/istio-dump.tar.gz)
