### ISSUE TITLE
Gateway mode should support Cloud Foundry ingress routing

### ISSUE THREAD

**Issue by rosenhouse** [istio/istio#2812]
We want to replace the existing ingress routing system in Cloud Foundry (known as "gorouter") with Istio.

The `Gateway` model seems appropriate.

Some requirements:
- define a single port for HTTP and a single port for HTTPS listening
- handle all hosts (shouldn't need to provide a complete list of hosts in my config, it comes from the platform)

Some things we'd like in the future:
- run-time configurable SNI

cc: @shalako @rshriram @ZackButcher 

references:
- [background slides](https://docs.google.com/presentation/d/1gtYNr8te2qeGgWrtH4S073JHmpbkKUkDHWvuLWTSenE/edit#slide=id.g2f930e7539_0_184)
- [background google doc](https://docs.google.com/document/d/10uzw4N11NY_vWxWu2l79Ag96fvPT6w-OGzD_buvILM0/edit)
- [initial PR for gateway](https://github.com/istio/api/pull/254)
- [related issues in istio/api](https://github.com/istio/api/issues?utf8=%E2%9C%93&q=+gateway+)

**Comment by ZackButcher** [comment]
Runtime configuration for SNI is something we'll be shipping in the not too distant future to support other ingress use cases (cc @costinm).

Can you expand some on what you mean by the "handle all hosts" bullet? Today the `hosts` field of the Gateway supports wildcards, so a configuration like `hosts: "*"` is valid.

**Comment by ZackButcher** [comment]
Single port for HTTP/HTTPS aligns well with k8s ingress too - that's the first segment of support for Gateways that I'll be landing, so that aligns well. (The assumption here is that they'll be on ports 80/443 respectively, but that shouldn't be too hard to rework if CF needs something different.)

**Comment by rosenhouse** [comment]
ok, cool.  @rshriram was there something else that you inferred was required of Gateway for Cloud Foundry use case, beyond what has been covered in this issue?

It sounds like we're asking for nothing more than a vanilla Gateway.

**Comment by rosenhouse** [comment]
Ok, here's one thing (copied from [here](https://docs.google.com/presentation/d/1gtYNr8te2qeGgWrtH4S073JHmpbkKUkDHWvuLWTSenE/edit?disco=AAAABoxMzPM&ts=5a691dba&usp=comment_email_document))

> However, if we wanted to support SNI, and allow users to provide custom certs for certain hosts, would we then need to make a separate Gateway resource for each server-cert? Or could a single Gateway resource list many pairs of {hosts, tls}

**Comment by rshriram** [comment]
Here is what I am assuming:

1. Apps created by CF users automatically get a hostname that gets exposed at the ingress. We are talking about 1000s of hosts being added/removed. No single user controls the gateway config.

2. For every request that hits the ingress router with a valid hostname, the request has to be automatically load balanced among the service instances associated with that hostname. (This is essentially an empty route rule of the form

```yaml
hosts:
- myapp.pivotal.io
http:
- route:
   - destination:
           name: myapp.pivotal.io
```

Given that we have 1000s of hosts, we are looking at 1000s of such route rules floating in the system, created automatically by some backend system. (this could be as high as 250K routes?)

3. We also want users to be able to explicitly control the routing. like for requests to myapp.pivotal.io, send 50% to myapp-v1.pivotal.io and other 50% to myapp-v2.pivotal.io. Now, these are likely to be added manually by the user (or through some CI/CD system, etc.). Something has to merge these user generated routes with teh auto-generated routes.

4. Users want to define custom certs for certain domains. You can specify what these custom certs are, using the gateway spec, but since the user is not touching the gateway spec, there has to be something else that takes in the user specified cert, updates the wildcard gateway spec with something like 

```
ports:
- 80
   hosts: *
tls:
- hosts: myapp.pivotal.io
   certs:path-to-my-certs
```

Will this model scale to dynamic add/remove of 1000s of hosts/certs?

Given all this, my suggestion was to provide a few knobs in the gateway spec like this:

```yaml
ports:
- port 80
   get_hosts_from_service_registry: true
   # now hosts spec is not allowed
   # Pilot will automatically generate virtual hosts, and map them to default clusters
tls:
   get_certs_from_secret_service: true # CF folks have to implement Envoy secret discovery service
   secret_service_endpoint: CF-secret-service.foo.bar:8888
   # now manual tls specs are not allowed.
```

A config like above allows the hosts and tls certs in the gateway to be controlled directly by xDS servers without requiring the values to be materialized in the gateway spec. Its a lot less brittle than having to serialize all this in the gateway file and load them up in pilot, and transmit to Envoys. (Keep in mind that CF will not have a k8s api server running in their platform)
