### ISSUE TITLE
[WASM] Help needed with supplying configuration to custom envoy filter

### ISSUE THREAD

**Issue by aejeet** [istio/istio#28145]
I am following the steps at https://docs.solo.io/web-assembly-hub/latest/tutorial_code/build_tutorials/building_cpp_filters/ to write a custom envoy filter. I am unable to supply custom configuration to my filter and have not been able to find any example on internet. 

**Language**: c++

**My envoy proxy image:** istio/proxyv2:1.7.3

**My filter.proto**
```
syntax = "proto3";
package test_filter;
message Config {
    repeated RouteMatch routes  = 1;
    string  action = 2;
}
message RouteMatch {
    oneof path_specifier {
        string prefix = 1;
        string path = 2;
        string regex = 3;
    }
    bool ignore_case = 4;
}
```

**My envoy config**
```
admin:
  accessLogPath: /dev/null
  address:
    socketAddress:
      address: 0.0.0.0
      portValue: 19000
staticResources:
  clusters:
  - name: static-cluster
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: jsonplaceholder.typicode.com
    lb_policy: LEAST_REQUEST
    load_assignment:
      cluster_name: static-cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: jsonplaceholder.typicode.com
                port_value: 443
  listeners:
  - name: listener_0
    address:
      socketAddress:
        address: 0.0.0.0
        portValue: 8080
    filterChains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          httpFilters:
          - name: envoy.filters.http.wasm
            typed_config:
              "@type": type.googleapis.com/udpa.type.v1.TypedStruct
              type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
              value:
                config:
                  name: add_header_root_id
                  root_id: add_header_root_id
                  configuration:
                    "@type": type.googleapis.com/udpa.type.v1.TypedStruct
                    type_url: type.googleapis.com/test_filter.Config
                    value:
                      routes:
                      - prefix: /foo
                      - path: /bar
                        ignore_case: true
                      action: block
                  vm_config:
                    runtime: "envoy.wasm.runtime.v8"
                    vm_id: add_header_root_id
                    code:
                      local:
                        filename: "/Users/av736300/.wasme/store/d74a01f81edf4d3323818b4562af800b/filter.wasm"
                    configuration: {}
          - name: envoy.filters.http.router
          routeConfig:
            name: test
            virtualHosts:
            - domains:
              - '*'
              name: jsonplaceholder
              routes:
              - match:
                  prefix: /
                route:
                  autoHostRewrite: true
                  cluster: static-cluster
          statPrefix: ingress_http
```

Inside the filter, in `onConfigure()` method i am doing the following
```
  auto conf = getBufferBytes(WasmBufferType::PluginConfiguration, 0, config_buffer_length);
  test_filter::Config config = conf->proto<test_filter::Config>();
```

Though envoy starts, it spits errors like `contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes` and in the filter i don't see the config loaded correctly.

I tried many other variations but with other variations envoy does not even start.
