### ISSUE TITLE
sidecar egress mtls configuration override ROOTCA to cause internal mtls failure

### ISSUE THREAD

**Issue by hobbytp** [istio/istio#28143]
**Bug description**
I found after adding client cert/key/CA in pod annotation (sidecar.istio.io/userVolume and sidecar.istio.io/userVolumeMount), the CA will override the ROOTCA in envoy proxy configuration, and then internal mtls communication will failed even external mtls is ok. 

The client cert/key/CA will be used to connect to external service for MTLS communication ( I use sidecar directly instead of through egress gateway). The annotation will auto add volume/volumeMount to the pod when pod creating, and sidecar can use it later which cert/key/CA path is also identified in DR, and then I add SE and DR to try to enable external mtls communication.
After that, the external mtls is ok, but internal mtls is failed for ROOTCA body is replaced by the new CA in annotation. I don't find the same problem in egress gateway. 
More detail can be found in the reproduce steps later.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
After configuring sidecar egress mtls (annotation + SE +DR(with cert/key/CA path), internal mtls ROOTCA is not be override and also can work. 

**Steps to reproduce the bug**
**0. Create both client cert/key/CA and server client.**
```
openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -subj '/O=example Inc./CN=example.com' -keyout example.com.key -out example.com.crt

openssl req -out my-nginx.mesh-external.svc.cluster.local.csr -newkey rsa:2048 -nodes -keyout my-nginx.mesh-external.svc.cluster.local.key -subj "/CN=my-nginx.mesh-external.svc.cluster.local/O=some organization"
openssl x509 -req -days 365 -CA example.com.crt -CAkey example.com.key -set_serial 0 -in my-nginx.mesh-external.svc.cluster.local.csr -out my-nginx.mesh-external.svc.cluster.local.crt

openssl req -out client.example.com.csr -newkey rsa:2048 -nodes -keyout client.example.com.key -subj "/CN=client.example.com/O=client organization"
openssl x509 -req -days 365 -CA example.com.crt -CAkey example.com.key -set_serial 1 -in client.example.com.csr -out client.example.com.crt
```
```
kubectl -n hobby create secret generic client-certs-cacert --from-file=ca-chain.cert.pem=./example.com.crt
kubectl -n hobby create secret tls client-certs --cert ./client.example.com.crt --key ./client.example.com.key
```

**1. Deploy client to connect to external mtls server**
_1.1 deploy sleep with sidecar and client cert/key/CA in NS hobby_
```
kubectl -n hobby apply -f <(istioctl kube-inject -f samples/sleep/sleep.yaml)
```
_1.2. Add annotation to assign client cert/key/CA_
Add the following annotation in sleep deployment to add new volume for cert/key/CA which will be used to communicate with external mtls service later.
```yaml
         sidecar.istio.io/userVolume: '{"egress-secret":{"secret":{"secretName":"client-certs","optional":true}},"egress-ca-secret":{"secret":{"secretName":"client-certs-cacert"}}}'
        sidecar.istio.io/userVolumeMount: '{"egress-secret":{"mountPath":"/etc/istio/egress-certs/","readOnly":true},"egress-ca-secret":{"mountPath":"/etc/istio/egress-ca-certs/","readOnly":true}}'
```
**2. Add external service mtls configuration (SE + DR) in NS hobby**
```yaml
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: first-service-entry
  namespace: hobby
spec:
  exportTo:
  - .
  hosts:
  - my-nginx.mesh-external.svc.cluster.local
  location: MESH_EXTERNAL
  ports:
  - name: http-port-for-tls-origination
    number: 31443
    protocol: HTTP
  resolution: NONE
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: first-destination-rule
  namespace: hobby
spec:
  exportTo:
  - .
  host: my-nginx.mesh-external.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 31443
      tls:
        caCertificates: /etc/istio/egress-ca-certs/ca-chain.cert.pem
        clientCertificate: /etc/istio/egress-certs/tls.crt
        mode: MUTUAL
        privateKey: /etc/istio/egress-certs/tls.key
        sni: my-nginx.mesh-external.svc.cluster.local 
EOF
```
**3. Add external mtls service (ngnix)**

```bash
kubectl create namespace mesh-external
kubectl create -n mesh-external secret tls nginx-server-certs --key my-nginx.mesh-external.svc.cluster.local.key --cert my-nginx.mesh-external.svc.cluster.local.crt
kubectl create -n mesh-external secret generic nginx-ca-certs --from-file=example.com.crt
```

```conf
$ cat <<\EOF > ./nginx.conf
events {
}

http {
  log_format main '$remote_addr - $remote_user [$time_local]  $status '
  '"$request" $body_bytes_sent "$http_referer" '
  '"$http_user_agent" "$http_x_forwarded_for"';
  access_log /var/log/nginx/access.log main;
  error_log  /var/log/nginx/error.log;

  server {
    listen 443 ssl;

    root /usr/share/nginx/html;
    index index.html;

    server_name my-nginx.mesh-external.svc.cluster.local;
    ssl_certificate /etc/nginx-server-certs/tls.crt;
    ssl_certificate_key /etc/nginx-server-certs/tls.key;
    ssl_client_certificate /etc/nginx-ca-certs/example.com.crt;
    ssl_verify_client on; # In mutual TLS, server verifies client's certificate
  }
}
EOF
```

```bash
kubectl create configmap nginx-configmap -n mesh-external --from-file=nginx.conf=./nginx.conf
```
```yaml
kubectl apply -f - <<EOF
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  namespace: mesh-external
  labels:
    run: my-nginx
spec:
  ports:
  - port: 31443
    protocol: TCP
    targetPort: 443
  selector:
    run: my-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  namespace: mesh-external
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 443
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx
          readOnly: true
        - name: nginx-server-certs
          mountPath: /etc/nginx-server-certs
          readOnly: true
        - name: nginx-ca-certs
          mountPath: /etc/nginx-ca-certs
          readOnly: true
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-configmap
      - name: nginx-server-certs
        secret:
          secretName: nginx-server-certs
      - name: nginx-ca-certs
        secret:
          secretName: nginx-ca-certs
EOF
```

**4. Verification Steps**
The external mtls communication work correctly as below screenshot, but internal mtls can not work for ROOTCA is replaced by new CA assigned in sleep annotation.

```bash
$ kubectl -n hobby exec "$(kubectl -n hobby get pod -l app=sleep -o jsonpath={.items..metadata.name})" -c sleep -- curl -s http://my-nginx.mesh-external.svc.cluster.local:31443
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
...
```
The secret of ROOTCA is replaced by ca-chain.cert.pem , you can find the "NOT AFTER" and "NOT BEFORE" are the same now
```
$ istioctl pc secret sleep-747dcdbd6f-rbpkx.hobby
RESOURCE NAME                                                                 TYPE           STATUS     VALID CERT     SERIAL NUMBER                                        NOT AFTER                NOT BEFORE
file-cert:/etc/istio/egress-certs/tls.crt~/etc/istio/egress-certs/tls.key     Cert Chain     ACTIVE     true           1                                                    2021-10-20T02:49:14Z     2020-10-20T02:49:14Z
default                                                                       Cert Chain     ACTIVE     true           129588817028178672933431284968727571656              2020-10-21T07:57:35Z     2020-10-20T07:57:35Z
file-root:/etc/istio/egress-ca-certs/ca-chain.cert.pem                        CA             ACTIVE     true           279620839875612486678315663074644359785194352408     2021-10-20T02:48:52Z     2020-10-20T02:48:52Z
ROOTCA                                                                        CA             ACTIVE     true           279620839875612486678315663074644359785194352408     2021-10-20T02:48:52Z     2020-10-20T02:48:52Z

```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
$ istioctl version --remote
client version: 1.7.3
control plane version: 1.7.3
data plane version: 1.7.3 (4 proxies)

**How was Istio installed?**
istioctl install --profile=demo

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
