### ISSUE TITLE
Add analyzer for incompatible host between VS and GW

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#28172]
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gw
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - foo.com
    port:
      name: http
      number: 80
      protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service
spec:
  gateways:
  - istio-system/gw
  hosts:
  - bar.com
  http: {..}
```

This config will not apply, since foo.com and bar.com are not compatible

I think we can warn if a VS references any non-mesh gateways, and non of the gateway servers match
