### ISSUE TITLE
k8s ingress: suspicious generated config when tls.host and rules.host mismatch

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#28174]
Example config:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: service
spec:
  tls:
  - hosts:
      - "foo.io"
    secretName: certs
  rules:
    - host: bar.io
      http:
        paths:
          - backend:
              serviceName: service
              servicePort: 80
```

Generated output will have gateway.server.host equal tls.hosts, but the VS will have rules.host, which may never match.

We should look into if this is the expected behavior, as it seems like it may lead to confusing behavior. We should see what other Ingress providers do here
