### ISSUE TITLE
ValidatingWebhookConfiguration hardcoded to istiod service

### ISSUE THREAD

**Issue by bnutt** [istio/istio#28211]
**Bug description**
The ValidatingWebhook configuration generated by the istioperator is hard coded to look for service `istiod` in the namespace where the istioperator resource is deployed. However, if .Values.revision is set, the name of the istiod service generated by the istiooperator resource includes the revision name, e.g. `istio-$rev`. This makes any requests coming in to the ValidatingWebhook fail because the service is not resolvable. The issue generates from the following:

1. `istiod` service is hard coded https://github.com/istio/istio/blob/master/manifests/charts/base/templates/validatingwebhookconfiguration.yaml#L17. Even though the validating webhook may be unique to the namespace of that istio deployment.
2. istio-$revision serivce is made if .Values. revision is set. https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/templates/service.yaml#L4 A user may want to set revision if they have multiple control planes and want to use the revision label to decide which control plane proxies in a namespace should connect to. This is done via the istio.io/rev label, as indicated here https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/templates/mutatingwebhook.yaml#L59.

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
The ValidatingWebhook created should reference the same service generated by the istio operator, this will make validating requests for any of the istio API groups work.

**Steps to reproduce the bug**
1. Install istio operator 1.7.3 onto kubernetes cluster

2. Apply manifest with .Values.Revision set

```
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiopperator
spec:
  components:
    base:
      enabled: true
    pilot:
      enabled: true
  profile: empty
  tag: 1.7.3
  values:
    revision: blue
    meshConfig:
      rootNamespace: istio-blue
    base:
    clusterResources: true
    global:
      configValidation: true
      controlPlaneSecurityEnabled: true
      defaultPodDisruptionBudget:
        enabled: true
      enableHelmTest: false
      istioNamespace: istio-blue
      omitSidecarInjectorConfigMap: false
      pilotCertProvider: istiod
    sidecarInjectorWebhook:
      enableNamespacesByDefault: false
      injectLabel: istio.io/rev
      objectSelector:
        autoInject: true
        enabled: false
      rewriteAppHTTPProbe: true
    version: ""

```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

**How was Istio installed?**
Istio Operator 1.7.3
Istio 1.7.3 control plane

**Environment where bug was observed (cloud vendor, OS, etc)**
Any cloud

Here is an example istiooperator resource which provides a workaround via patching
```
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiopperator
spec:
  components:
    base:
      enabled: true
      k8s:
        overlays: # patching the name of service that is called in the webhook since istiod is hardcoded
          - kind: ValidatingWebhookConfiguration
            name: istiod-istio-blue
            patches:
              - path: webhooks[0].clientConfig.service.name
                value: istiod-blue
```
