### ISSUE TITLE
GatewayPortNotOnWorkload analyzer logic seems to be incorrect

### ISSUE THREAD

**Issue by nrjpoddar** [istio/istio#28259]
**Bug description**
The `GatewayPortNotOnWorkload` analyzer [checks](https://github.com/istio/istio/blob/ba1e0b596999483f00e7fe6f2887b71fca3cc8a4/galley/pkg/config/analysis/analyzers/gateway/gateway.go#L89) that Gateway resource ports are defined in the Service ports list. While this seems correct at the first glance, I think the Gateway resource ports refer to "workload" ports which means that this checker should be validating that the service "targetPort" list has the Gateway resource ports defined instead of service ports itself.

This is further complicated by how the predefined service ports "80" & "443" are handled as a special case where the Gateway resource port "80" & "443" get converted to target ports "8080" & "8443" for the gateway workload ports to get the around the priveleges issue related to ports under 1024.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
Analyzer doesn't surface false positive messages

**Steps to reproduce the bug**
* Install Istio 1.7.3 with demo profile
* Deploy a GW resource like this:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: frontend-gateway
spec:
  selector:
    # use Istio default gateway implementation
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
```
* Run "istioctl analyze -n default" and no error messages are displayed which is correct but notice that the istio-ingressgateway service forwards traffic on service port `80` to target port `8080` and the Envoy config dump on the ingress gateway pod will show that the configured listener is also on port `8080`.
* Update the gateway resource to use port `8080`:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: frontend-gateway
spec:
  selector:
    # use Istio default gateway implementation
    istio: ingressgateway
  servers:
  - port:
      number: 8080
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
```
* Run "istioctl analyze -n default" and a warning message is displayed which is not correct as the traffic still flows correctly due to service port `80` being mapped to gateway workload port `8080`. I'm assuming Istio control plane is doing this translation on for ports `80` and `443` for backwards compatibility.
```bash
Warn [IST0104] (Gateway frontend-gateway.default) The gateway refers to a port that is not exposed on the workload (pod selector istio=ingressgateway; port 8080)
```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

**How was Istio installed?**
Via istioctl following steps [here](https://istio.io/latest/docs/setup/getting-started/).
