### ISSUE TITLE
PSQL / PgBouncer - mTLS Disabled - Unable to connect ("pgbouncer cannot connect to server")

### ISSUE THREAD

**Issue by DandyDeveloper** [istio/istio#28264]
**Bug description**
After enabling the sidecar injection on a pgbouncer instance and postgresql instance, pgbouncer seems unable to pool connections / establish connections to Postgresql. 

I have mTLS set to DISABLED via PeerAuth in Istio root:
```yaml
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: istio-system
spec:
  mtls:
    mode: DISABLE
```

Accessing the Psql instance from within the PGBouncer pod works perfectly: 

```
dandy@DESKTOP-2GSHJ08:/istio$ kubectl exec -it pgbouncer-master-689594c497-92hqn -c pgbouncer -- sh
/ $ psql -U postgres -h postgresql-master
psql (10.10, server 10.7 (Debian 10.7-1.pgdg90+1))
Type "help" for help.

postgres=# \l
                                  List of databases
   Name    |   Owner    | Encoding |  Collate   |   Ctype    |   Access privileges
-----------+------------+----------+------------+------------+-----------------------
 postgres  | postgres   | UTF8     | en_US.utf8 | en_US.utf8 |
(6 rows)
```

I can also pSQL from a random Alpine container for testing: 
```
/ # psql -h postgresql-master -U postgres
psql (12.4, server 10.7 (Debian 10.7-1.pgdg90+1))
Type "help" for help.

postgres=#
```

However, attempting to access PGBouncer from the same Alpine pod gives me: 
```
 / # psql -h pgbouncer-master -U postgres
psql: error: could not connect to server: ERROR:  pgbouncer cannot connect to server
/ #
```

The service of PGBouncer seems OK: 
```
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-master
  namespace: default
spec:
  clusterIP: 10.98.204.232
  ports:
  - name: tcp-psql
    port: 5432
    protocol: TCP
    targetPort: 5432
  - name: http-metrics
    port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    app: pgbouncer
    release: pgbouncer-master
  sessionAffinity: None
  type: ClusterIP
```

In this case, it'll be going TCP -> TCP. Does Istio have a problem with this? 

One curious thing is I don't see a route does this in the `pc routes`. I see a number of other routes to other dbs inside the cluster, but not the one in question: 
```
dandy@DESKTOP-2GSHJ08:~$ istioctl pc routes pgbouncer-master-689594c497-92hqn.default | grep postgres
postgres-master-replicas.kubedb.svc.cluster.local:5432                                 1
pdns-postgresql.platform.svc.cluster.local:5432                                        1
postgres-master.kubedb.svc.cluster.local:5432                                          1
dandy@DESKTOP-2GSHJ08:~$
```

I do see a cluster though:
```
dandy@DESKTOP-2GSHJ08:~$ istioctl pc cluster pgbouncer-master-689594c497-92hqn.default | grep postgres
postgresql-master.default.svc.cluster.local                                   5432      -                outbound      EDS
postgresql-master.default.svc.cluster.local                                   9187      -                outbound      EDS
```

Endpoints are also registered correctly: 
```
10.244.15.157:5432               HEALTHY     OK                outbound|5432||postgresql-master.default.svc.cluster.local
10.244.15.157:9187               HEALTHY     OK                outbound|9187||postgresql-master.default.svc.cluster.local
```

Does anyone have any suggestions on what may be happening here? Note, removing the sidecar resolves this. It works perfectly.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[x] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
I'd expect the connection to go through without any problems. 

**Steps to reproduce the bug**
Deploy an instances of PGBouncer, postgresql OR any TCP -> TCP pooler service that may be similar. Attempt a connection. 

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
```
client version: 1.6.11
control plane version: 1.6.11
data plane version: 1.6.11 (168 proxies)
```

k8s version 1.14.11. **Note, I get the same behaviour on 1.5 of Istio.**

**How was Istio installed?**
`istioctl` using a custom profile. 

**Environment where bug was observed (cloud vendor, OS, etc)**
CoreOS Baremetal instance. 

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
