### ISSUE TITLE
feat(tls certificate gateway), impossible to configure two or more gateways pointing to the same tls certificate

### ISSUE THREAD

**Issue by mbfmbf** [istio/istio#28305]
**Bug description**
The fact of adding a gateway that points to the same certificate as another gateway, this disrupts the proper functioning of the urls of the old gateway and the response of requests starts to alternate between status 200 and 404 not found

**Affected product area (please put an X in all that apply)**
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[X] Developer Infrastructure

**Affected features (please put an X in all that apply)**
[X] Multi Cluster
[ ] Virtual Machine
[X] Multi Control Plane

**Version**
client version: 1.7.3
control plane version: 1.7.3
data plane version: 1.7.3 (83 proxies)

**How was Istio installed?**
istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
Cloud Kubernetes v1.18.6

**Comment by connatix-cradulescu** [comment]
I did create multiple gateways with the same certificate and never had an issue. Can you provide your configuration of the gateways and virtual services?

**Comment by mbfmbf** [comment]
Hello and sorry for this late return, here are the configuration of the two virtual services and gateways carrying the same certificate, in this case: elasticsearch and kibana:

```yaml
# GW elasticsearch
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  labels:
    app.kubernetes.io/component: elasticsearch
  name: elasticsearch-gateway
  namespace: kube-logs-efk
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - elasticsearch.mydomain.dev
    port:
      name: http-elasticsearch
      number: 80
      protocol: HTTP
  - hosts:
    - elasticsearch.mydomain.dev
    port:
      name: https-elasticsearch
      number: 443
      protocol: HTTPS
    tls:
      credentialName: mydomain-tls
      mode: SIMPLE
---
# VS Elasticsearch
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: elasticsearch
  namespace: kube-logs-efk
spec:
  gateways:
  - kube-logs-efk/elasticsearch-gateway
  hosts:
  - elasticsearch.mydomain.dev
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: elasticsearch
        port:
          number: 9200

#====================================================================#
---
# GW kibana
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  labels:
    app.kubernetes.io/component: kibana
  name: kibana-gateway
  namespace: kube-logs-efk
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - kibana.mydomain.dev
    port:
      name: http-kibana
      number: 80
      protocol: HTTP
  - hosts:
    - kibana.mydomain.dev
    port:
      name: https-kibana
      number: 443
      protocol: HTTPS
    tls:
      credentialName: mydomain-tls
      mode: SIMPLE
---
# VS kibana
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kibana
  namespace: kube-logs-efk
spec:
  gateways:
  - kube-logs-efk/kibana-gateway
  hosts:
  - kibana.mydomain.dev
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: kibana
        port:
          number: 5601
```

**Comment by mbfmbf** [comment]
And the logs of the two urls are as below:

```console
[2021-01-25T12:54:18.059Z] "GET / HTTP/2" 200 - "-" 0 332 12 11 "10.244.0.1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36" "84aec6bb-dbaf-9708-88fc-402f950623dd" "elasticsearch.mydomain.dev" "10.244.0.44:9200" outbound|9200||elasticsearch.kube-logs-efk.svc.cluster.local 10.244.0.41:56770 10.244.0.41:8443 10.244.0.1:23637 elasticsearch.mydomain.dev -

[2021-01-25T12:56:46.038Z] "GET / HTTP/2" 404 NR "-" 0 0 0 - "10.244.0.1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36" "517bdb0c-693f-9d31-acae-17f1713262a0" "kibana.mydomain.dev" "-" - - 10.244.0.41:8443 10.244.0.1:23637 elasticsearch.mydomain.dev -
```

**Comment by connatix-cradulescu** [comment]
Hi @mbfmbf 

You have to use a single gateway and use a wildcard on hosts:
```
 servers:
  - hosts:
    - '*'
```
You are going to use the same gateway for elastic and kibana too.

**Comment by mbfmbf** [comment]
@connatix-cradulescu
thank's for this quick feedback, 

But I have other url which have other certificate, how to do?

**Comment by connatix-cradulescu** [comment]
Create a wildcard cerfificate

**Comment by mbfmbf** [comment]
so if I understand, it doesn't work with a .dev and .com hosted in the same kube cluster

**Comment by connatix-cradulescu** [comment]
If you are using a different certificate u have to use the above configuration that you listed and just use different names for the secret TLS

**Comment by mbfmbf** [comment]
thanks, I found the solution, I pose here so that it stays for others

```yaml
# GW for mydomain.dev
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  labels:
    app.kubernetes.io/component: elasticsearch
  name: mydomain-gateway
  namespace: kube-logs-efk
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*.mydomain.dev'
    port:
      name: http-mydomain
      number: 80
      protocol: HTTP
  - hosts:
    - '*.mydomain.dev'
    port:
      name: https-mydomain
      number: 443
      protocol: HTTPS
    tls:
      credentialName: mydomain-tls
      mode: SIMPLE
#====================================================================#
---
# VS Elasticsearch
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: elasticsearch
  namespace: kube-logs-efk
spec:
  gateways:
  - kube-logs-efk/mydomain-gateway
  hosts:
  - elasticsearch.mydomain.dev
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: elasticsearch
        port:
          number: 9200

#====================================================================#
---
# VS kibana
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kibana
  namespace: kube-logs-efk
spec:
  gateways:
  - kube-logs-efk/mydomain-gateway
  hosts:
  - kibana.mydomain.dev
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: kibana
        port:
          number: 5601
```
and for other domain with other certificates:
```yaml
# GW for seconddomain.dev
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  labels:
    app.kubernetes.io/component: elasticsearch
  name: seconddomain-gateway
  namespace: kube-logs-efk
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*.seconddomain.dev'
    port:
      name: http-seconddomain
      number: 80
      protocol: HTTP
  - hosts:
    - '*.seconddomain.dev'
    port:
      name: https-seconddomain
      number: 443
      protocol: HTTPS
    tls:
      credentialName: seconddomain-tls
      mode: SIMPLE
---
# VS myapp
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: myapp
  namespace: kube-logs-efk
spec:
  gateways:
  - kube-logs-efk/seconddomain-gateway
  hosts:
  - myapp.seconddomain.dev
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: myapp
        port:
          number: 80
