### ISSUE TITLE
The 503(no healthy upstream) error occurs intermittently when accessing the istio-ingressgateway

### ISSUE THREAD

**Issue by ImmortanJoe** [istio/istio#28312]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

istio 1.6.9

two clusters with shared control plane in cluster1,two istiod pods
![image](https://user-images.githubusercontent.com/14193852/97305161-b7571d00-1897-11eb-84a9-fe27ff41ac7f.png)

After some operations(I forgot what I did), two istiods have different endpointShardz. 

Endpoints of productpage in istiod-1 are:
172.16.1.3:9080 HEALTHY OK outbound.9080._.productpage.default.svc.cluster.local
172.16.1.3:9080 HEALTHY OK outbound|9080||productpage.default.svc.cluster.local

Endpoints of productpage in istiod-2 are:
172.16.1.3:9080 HEALTHY OK outbound.9080..productpage.default.svc.cluster.local
172.16.1.3:9080 HEALTHY OK outbound.9080.v1.productpage.default.svc.cluster.local
172.16.1.3:9080 HEALTHY OK outbound|9080|v1|productpage.default.svc.cluster.local
172.16.1.3:9080 HEALTHY OK outbound|9080||productpage.default.svc.cluster.local

When the istio-ingressgateway is connected to the istiod-1, the 503(no healthy upstream) error occurs.
When the istio-ingressgateway is connected to the istiod-2, the access is normal

the config of gateway：
 ```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: productpage
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - 100.xx.xx.xx
    port:
      name: http-89f36691
      number: 9080
      protocol: http

```

the config of virtualservice using delegate feature：

 ```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: productpage-8a0bf26a
  namespace: istio-system
spec:
  gateways:
  - productpage.istio-system.svc.cluster.local
  - mesh
  hosts:
  - 100.xx.xx.xx
  - productpage
  http:
  - delegate:
      name: productpage
      namespace: default
    match:
    - uri:
        prefix: /productpage

```

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: productpage
  namespace: default
spec:
  http:
  - match:
    - gateways:
      - mesh
      port: 9080
    route:
    - destination:
        host: productpage.default.svc.cluster.local
        port:
          number: 9080
        subset: v1
  - match:
    - gateways:
      - productpage.istio-system.svc.cluster.local
      port: 9080
      uri:
        prefix: /productpage
    name: ext-productpage-9080
    route:
    - destination:
        host: productpage.default.svc.cluster.local
        port:
          number: 9080
        subset: v1

```

the config of destinationrule:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: productpage
  namespace: default
spec:
  host: productpage
  subsets:
  - labels:
      version: v1
    name: v1

```
**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
