### ISSUE TITLE
Istio-ingress nodeport service changes

### ISSUE THREAD

**Issue by jbrongtr** [istio/istio#28310]
## Versions
We are using the operator deployed by istioctl
istio - v1.7.0

## Issue
Occasionally the istio-ingress service nodeports change and this will break our ingress. 

## Setup
We have a DeamonSet proxy sitting on all nodes that listens on port 80 &443 then xfers the connection to the istio-ingress service at the specific nodeport its listening on.

## Possible cause

I think that when the HPA gets triggered and a new deployment of the istio-ingress is spun up, the ports get changed to new available ports, which breaks our static daemonset configs.

## Summary

I think that the older versions of istio scaled pods instead of deployments. Is there a benefit to doing it the other way around.

**Comment by jbrongtr** [comment]
Actually it seems to correspond to the hpa for istiod. We are right on the tipping point of 2 to 3 replicas based on cpu and each time it spins up a new replica of istiod, the nodeports change for the istio-ingress service.

**Comment by howardjohn** [comment]
@jbrongtr I am too surprised the node port changes as I think this is a known bug fixed by #27924. I would be surprised if the HPA of Istiod is somehow impacting the node port of ingress, that seems odd. Does this issue still occur if you remove the HPA?

I am fuzzy on the details but @richardwxn probably knows more

**Comment by bnutt** [comment]
@howardjohn Will https://github.com/istio/istio/pull/27924 be back-ported to 1.7? I am observing this issue on 1.7.3. Using custom gateways, each time the istio operator reconciles, it updates the nodePorts for the service, which triggers new target groups(NLB) to be created and causes downtime for services which ingress through the gateway in the cluster. This issue occurs even if the istio operator pod is restarted, since it does a reconciliation once on a fresh pod. If it's not backported, is there any estimate for when 1.8 will be available? Trend shows it will be sometime later this month, but I figure its worth asking since this is a critical issue blocking me from updating all our clusters to 1.7. https://discuss.istio.io/t/istio-operator-1-6-8-install-issues-nlb-target-groups-being-recreated/8034 suggests to hard code the nodePort which I will be doing for now, but it would be great to be able to avoid doing so.

**Comment by jbrongtr** [comment]
@bnutt Have you tried hard coding the ports in the istio operator manifest?

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: mss-istiocontrolplane
spec:
  profile: default
  hub: artifactory/istio
  meshConfig:
    accessLogFile: /dev/stdout
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        service:
          ports:
            - name: status-port
              port: 15021
              nodePort: 30267
              targetPort: 15021
            - name: http2
              port: 80
              nodePort: 31480
              targetPort: 8080
            - name: https
              port: 443
              nodePort: 31443
              targetPort: 8443
            - name: tls
              port: 15443
              nodePort: 30057
              targetPort: 15443
```
I can verify that installing with the above manifest does set the nodePorts to the configured values. Though sometime after that they change again.

When i pull the manifest using `kubectl -n istio-system get IstioOperator installed-state -o yaml > installed-state.yaml` i see my changes made above, but inspecting the svc for `istio-ingress`shows that the node ports have chained from my original config above.
