### ISSUE TITLE
Error Deploying Istio with HELM v3 

### ISSUE THREAD

**Issue by abhassine** [istio/istio#28375]
Hello @hickeyma Martin 

When I tried to deploy Istio using Helm v3 following the [read me](https://github.com/istio/istio/blob/master/manifests/charts/README-helm3.md) I get the following `Error: create: failed to create: Request entity too large: limit is 3145728`

Context: I'm deploying on EKS v1.17

Thank you by advance

**Comment by morvencao** [comment]
Do you accidentally include any .tgz or any other large file in the chart directory?

**Comment by abhassine** [comment]
No !
I even deleted some files :

```
$ du -sh ./istio/*/*
144K	./istio/crds/crd-all.gen.yaml
4.0K	./istio/crds/crd-operator.yaml
8.0K	./istio/templates/clusterrole.yaml
4.0K	./istio/templates/clusterrolebinding.yaml
4.0K	./istio/templates/crds.yaml
4.0K	./istio/templates/endpoints.yaml
4.0K	./istio/templates/role.yaml
4.0K	./istio/templates/rolebinding.yaml
4.0K	./istio/templates/serviceaccount.yaml
4.0K	./istio/templates/services.yaml
4.0K	./istio/templates/validatingwebhookconfiguration.yaml
```

**Comment by hickeyma** [comment]
@abhassine Where did you get the charts from? Is there a `manifests/charts` directory?

**Comment by abhassine** [comment]
Hello @hickeyma 

I used this charts https://github.com/abhassine/istio/tree/master/manifests/charts/base but without success. 

Finally, I was able to deploy ISTIO with Helm3 through ISTIO Operator.

I just included the configuration **profile manifest** under i**stio-operator/templates** into ISTIO OPERATOR charts removed namespace.yaml 

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: demo
EOF

```
by this

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: {{ .Values.nameProfile }}
spec:
  profile: {{ .Values.Profile }}
```
and I was able to deploy successfully 👍 

```
COUW3026476:charts abenhassine$ kgpoall
NAMESPACE              NAME                                                        READY     STATUS    RESTARTS   AGE
istio-operator         istio-operator-5b7798f566-5gq7n                             1/1       Running   0          19s
istio-system           istio-egressgateway-6488cc97fc-qql7s                        1/1       Running   0          20m
istio-system           istio-ingressgateway-6bd9856d48-gf9sx                       1/1       Running   0          20m
istio-system           istiod-69fd878578-jkwrs                                     1/1       Running   0          20m
```

Thanks
