### ISSUE TITLE
istio root namespace should default to istioNamespace first

### ISSUE THREAD

**Issue by linsun** [istio/istio#28400]
**Bug description**
I'm deploying istio to istio2 namespace, and if I don't have below, the generated manifest will use istio-system as root namespace.  root namespace should default to istioNamespace vs hardcoded to istio-system as today.

```
  values:
    global:
      caAddress: istiod2.management-cluster-85f044fc29ce613c264409c04a76c95d-0001.us-east.containers.appdomain.cloud:15012
      istioNamespace: istio2

    meshConfig:
      rootNamespace: istio2
```

generated yaml via istioctl manifest generate without meshConfig.rootNamespace: istio2

```

  mesh: |-
    defaultConfig:
      discoveryAddress: istiod.istio2.svc:15012
      meshId: cluster.local
      proxyMetadata:
        DNS_AGENT: ""
      tracing:
        zipkin:
          address: zipkin.istio2:9411
    enablePrometheusMerge: true
    rootNamespace: istio-system
    trustDomain: cluster.local
```

[ ] Docs
[x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
