### ISSUE TITLE
istioctl analyze missing schema validation errors

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#28445]
```
cat <<EOF | istioctl analyze - --use-kube=false -A
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: reviews-cb-policy
spec:
  host: reviews.prod.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http2MaxRequests: 1000
        maxRequestsPerConnection: 10
    outlierDetection:
      foobar: baz
      consecutiveErrors: 7
      interval: 5m
      baseEjectionTime: -1s
EOF
```

No errors reported. `istioctl validate` properly finds the errors.

Should see info about unknown field and baseEjectionTime being negative
