### ISSUE TITLE
RBAC doesn't seem to work with Virtual Machines

### ISSUE THREAD

**Issue by djannot** [istio/istio#28480]
**Bug description**

I deployed Istio 1.7.4 and a Virtual Machine.
After enforcing mTLS (with a PeerAuthentication object), I can have the VM accessing a Service running on Kubernetes from the VM and a Service running on the VM from Kubernetes.
So, this part is fine.
Then, I enabled RBAC (by creating an AuthorizationPolicy with `spec: {}` in the istio-system namespace) and get a `RBAC: access denied` response in both cases, which is expected.
Finally, I create AuthorizationPolicies to allow the  communications in both direction and if works to enable the communication from the VM to Kubernetes, but it doesn't work to enable the communication from Kubernetes to the VM.

When I set the logging level for `rbac` to `trace` on the VM, I see the SPIFFE ID I expect, but I still get a `RBAC: access denied`.

And when I look at the `config_dump`, I don't see any RBAC rules (all empty `{}`).

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
RBAC should work the same way with VirtualMachines

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
Kubernetes 1.18 and Istion 1.7.4

**How was Istio installed?**
With the following object:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      meshExpansion:
        enabled: true
      multiCluster:
        clusterName: kube-cluster
      network: main-network
      meshNetworks:
        main-network:
          endpoints:
          - fromRegistry: kube-cluster
          gateways:
          - registryServiceName: istio-ingressgateway.istio-system.svc.cluster.local
            port: 443
        vm-network:
```
