### ISSUE TITLE
Operator resources ignored

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#28489]
```
apiVersion: operator.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
spec:
  components:
    egressGateways:
    - name: istio-egressgateway
      enabled: true
  values:
    global:
      proxy:
        resources:
          requests:
            cpu: 30m
            memory: 65Mi
          limits:
            memory: 512Mi
    gateways:
      istio-ingressgateway:
        resources:
          requests:
            cpu: 30m
            memory: 65Mi
          limits:
            memory: 512Mi
```

```
$ ik manifest generate -d manifests -f /tmp/iop.yaml | k grep Deployment/istio-ingressgateway | rg resources: -A 6
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
```

You can see it does nothing
