### ISSUE TITLE
How to debug istio's pilot component

### ISSUE THREAD

**Issue by carryxyh** [istio/istio#28523]
How to debug the pilot component of istio? I try to use telepresence, but telepresence can only forward traffic on a specific port to the local.

I prefer a way to debug the pilot all the way (meaning from the start). Is there any way or suggestion?
Thanks.

**Comment by howardjohn** [comment]
What exactly are you looking to debug? if you need access tocertain ports you can use `kubectl port-forward`

**Comment by carryxyh** [comment]
Hi, I want to debug the entire life cycle of istio components. Take the pilot as an example. I want to debug its startup, accept configuration, push configuration to sidecar, etc.
Just like using `dlv` to remotely debug a normal golang project. I want to know how it works. Is there any good way?

**Comment by howardjohn** [comment]
You can use dlv (https://medium.com/@linsun_unc/debug-istio-components-with-goland-b0f9f9f60384 may help) just like any other golang app. You can also run it locally in a debugger connected to a remote k8s cluster. otherwise the localhost:8080/debug/* endpoints and logs are a good start

**Comment by carryxyh** [comment]
Thanks for answering. I will try the approach you mentioned. 

> You can also run it locally in a debugger connected to a remote k8s cluster. 

This way seems better, any docs for help ?

**Comment by carryxyh** [comment]
hi, I tried to start pilot-discovery locally, and it seems to be working properly. I can receive config changes from k8s.

But there is still a problem, I cannot link to the sidecar in the k8s cluster. This means that I cannot debug the actual push process. What do I need to do, can some one help?

By the way, I think there is currently a lack of documentation on debugging code line by line in our documentation. Will this doc welcome?

**Comment by howardjohn** [comment]
Sure, you are welcome to suggest additional docs from http://github.com/istio/istio/wiki

**Comment by carryxyh** [comment]
@howardjohn 

sorry for bothering.

I tried to let sidecar in the k8s cluster to connect to the local pilot to debug the information in the push process.

I add an annotation to the injected deployment file like this: 

```
sidecar.istio.io/discoveryAddress: myhost:15010
```

to tell the sidecar connect to my pilot address.

After that, seems sidecar start failed..

![image](https://user-images.githubusercontent.com/12047600/99537640-e2401700-29e6-11eb-9a76-18f737606d46.png)

May I ask what went wrong?

If this way is not correct, how can I connect the sidecar to the local pilot?

**Comment by carryxyh** [comment]
```
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: helloworld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    version: v1
  name: helloworld-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      version: v1
  strategy: {}
  template:
    metadata:
      annotations:
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "15020"
        prometheus.io/scrape: "true"
        sidecar.istio.io/interceptionMode: REDIRECT
        sidecar.istio.io/status: '{"version":"8e6e902b765af607513b28d284940ee1421e9a0d07698741693b2663c7161c11","initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["istio-envoy","istio-data","istio-podinfo","istiod-ca-cert"],"imagePullSecrets":null}'
        traffic.sidecar.istio.io/excludeInboundPorts: "15020"
        traffic.sidecar.istio.io/includeInboundPorts: "5000"
        traffic.sidecar.istio.io/includeOutboundIPRanges: '*'
        sidecar.istio.io/discoveryAddress: 10.242.208.185:15010
      creationTimestamp: null
      labels:
        app: helloworld
        istio.io/rev: ""
        security.istio.io/tlsMode: istio
        version: v1
    spec:
      containers:
      - image: docker.io/istio/examples-helloworld-v1
        imagePullPolicy: IfNotPresent
        name: helloworld
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
      - args:
        - proxy
        - sidecar
        - --domain
        - $(POD_NAMESPACE).svc.cluster.local
        - --serviceCluster
        - helloworld.$(POD_NAMESPACE)
        - --proxyLogLevel=warning
        - --proxyComponentLogLevel=misc:error
        - --trust-domain=cluster.local
        - --concurrency
        - "2"
        env:
        - name: JWT_POLICY
          value: first-party-jwt
        - name: PILOT_CERT_PROVIDER
          value: istiod
        - name: CA_ADDR
          value: istiod.istio-system.svc:15012
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: CANONICAL_SERVICE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['service.istio.io/canonical-name']
        - name: CANONICAL_REVISION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['service.istio.io/canonical-revision']
        - name: PROXY_CONFIG
          value: |
            {"proxyMetadata":{"DNS_AGENT":""}}
        - name: ISTIO_META_POD_PORTS
          value: |-
            [
                {"containerPort":5000}
            ]
        - name: ISTIO_META_APP_CONTAINERS
          value: helloworld
        - name: ISTIO_META_CLUSTER_ID
          value: Kubernetes
        - name: ISTIO_META_INTERCEPTION_MODE
          value: REDIRECT
        - name: ISTIO_META_WORKLOAD_NAME
          value: helloworld-v1
        - name: ISTIO_META_OWNER
          value: kubernetes://apis/apps/v1/namespaces/default/deployments/helloworld-v1
        - name: ISTIO_META_MESH_ID
          value: cluster.local
        - name: DNS_AGENT
        - name: ISTIO_KUBE_APP_PROBERS
          value: '{}'
        image: docker.io/istio/proxyv2:1.7.3
        imagePullPolicy: Always
        name: istio-proxy
        ports:
        - containerPort: 15090
          name: http-envoy-prom
          protocol: TCP
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /healthz/ready
            port: 15021
          initialDelaySeconds: 1
          periodSeconds: 2
        resources:
          limits:
            cpu: "2"
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 40Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 1337
          runAsNonRoot: true
          runAsUser: 1337
        volumeMounts:
        - mountPath: /var/run/secrets/istio
          name: istiod-ca-cert
        - mountPath: /var/lib/istio/data
          name: istio-data
        - mountPath: /etc/istio/proxy
          name: istio-envoy
        - mountPath: /etc/istio/pod
          name: istio-podinfo
      initContainers:
      - args:
        - istio-iptables
        - -p
        - "15001"
        - -z
        - "15006"
        - -u
        - "1337"
        - -m
        - REDIRECT
        - -i
        - '*'
        - -x
        - ""
        - -b
        - '*'
        - -d
        - 15090,15021,15020
        env:
        - name: DNS_AGENT
        image: docker.io/istio/proxyv2:1.7.3
        imagePullPolicy: Always
        name: istio-init
        resources:
          limits:
            cpu: "2"
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 10Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsGroup: 0
          runAsNonRoot: false
          runAsUser: 0
      securityContext:
        fsGroup: 1337
      volumes:
      - emptyDir:
          medium: Memory
        name: istio-envoy
      - emptyDir: {}
        name: istio-data
      - downwardAPI:
          items:
          - fieldRef:
              fieldPath: metadata.labels
            path: labels
          - fieldRef:
              fieldPath: metadata.annotations
            path: annotations
        name: istio-podinfo
      - configMap:
          name: istio-ca-root-cert
        name: istiod-ca-cert
status: {}
---
```
