### ISSUE TITLE
Missing istio_requests_* and istio_response_* metrics

### ISSUE THREAD

**Issue by nguyenhoaibao** [istio/istio#28531]
**Bug description**

We have several services running behind istio-ingressgateway. 

The `istio_requests_*` and `istio_response_*` metrics don't exist in both the gateways and the sidecar, but the `istio_tcp_*` metrics still exist.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Expect the `istio_requests_*` and `istio_response_*` metrics exists.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
1.7.3

**How was Istio installed?**
By istioctl command, using this config:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  profile: default

  meshConfig:
    outboundTrafficPolicy:
      mode: ALLOW_ANY
    enableAutoMtls: false
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
```

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by howardjohn** [comment]
Can you give more info about your services and config? Services need to be http type to get these metrics. see https://preliminary.istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/

**Comment by nguyenhoaibao** [comment]
Here is my service config:
```
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  clusterIP: 10.x.x.x
  ports:
  - name: grpc-web-port
    port: 5050
    protocol: TCP
    targetPort: grpc
  selector:
    app.kubernetes.io/instance: app
    app.kubernetes.io/name: app
  type: ClusterIP
```

The envoy filter stats config:

```
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_OUTBOUND
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              name: envoy.router
      proxy:
        proxyVersion: ^1\.7.*
    patch:
      operation: INSERT_BEFORE
      value:
        name: istio.stats
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          value:
            config:
              configuration:
                '@type': type.googleapis.com/google.protobuf.StringValue
                value: |
                  {
                    "debug": "false",
                    "stat_prefix": "istio"
                  }
              root_id: stats_outbound
              vm_config:
                code:
                  local:
                    inline_string: envoy.wasm.stats
                runtime: envoy.wasm.runtime.null
                vm_id: stats_outbound
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              name: envoy.router
      proxy:
        proxyVersion: ^1\.7.*
    patch:
      operation: INSERT_BEFORE
      value:
        name: istio.stats
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          value:
            config:
              configuration:
                '@type': type.googleapis.com/google.protobuf.StringValue
                value: |
                  {
                    "debug": "false",
                    "stat_prefix": "istio"
                  }
              root_id: stats_inbound
              vm_config:
                code:
                  local:
                    inline_string: envoy.wasm.stats
                runtime: envoy.wasm.runtime.null
                vm_id: stats_inbound
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              name: envoy.router
      proxy:
        proxyVersion: ^1\.7.*
    patch:
      operation: INSERT_BEFORE
      value:
        name: istio.stats
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          value:
            config:
              configuration:
                '@type': type.googleapis.com/google.protobuf.StringValue
                value: |
                  {
                    "debug": "false",
                    "stat_prefix": "istio",
                    "disable_host_header_fallback": true
                  }
              root_id: stats_outbound
              vm_config:
                code:
                  local:
                    inline_string: envoy.wasm.stats
                runtime: envoy.wasm.runtime.null
                vm_id: stats_outbound
```

We have 2 environments, staging and production. We were using istioctl to install istio for both of them, using the same istio operator config above.
In staging, I can see the `istio_requests_*` and `istio_response_*` metrics, but they don't exist in production environment. I suppose there might be some missing configuration so that the pilot cannot patch the envoy filter, but I don't know how to debug.

Can you guide me on how to debug this?

**Comment by howardjohn** [comment]
The first step would be to get a config dump (see https://github.com/istio/istio/wiki/Troubleshooting-Istio) and ensure the configuration is correct. I would also enable access logs if possible and verify the requests are matching up with the correct cluster we expect and isn't somehow getting routed incorrectly (due to misconfig or bug)

**Comment by nguyenhoaibao** [comment]
Thanks, I dumped the config from my staging and production, and I noticed that the staging configuration has this filter:
```
 {
  "name": "istio.stats",
  "typed_config": {
    "@type": "type.googleapis.com/udpa.type.v1.TypedStruct",
    "type_url": "type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm",
    "value": {
      "config": {
        "root_id": "stats_outbound",
        "vm_config": {
          "vm_id": "stats_outbound",
          "runtime": "envoy.wasm.runtime.null",
          "code": {
            "local": {
              "inline_string": "envoy.wasm.stats"
            }
          }
        },
        "configuration": {
          "@type": "type.googleapis.com/google.protobuf.StringValue",
          "value": "{\n  \"debug\": \"false\",\n  \"stat_prefix\": \"istio\",\n  \"disable_host_header_fallback\": true\n}\n"
        }
      }
    }
  }
}
```
while the production config doesn't, maybe that's the reason why the production doesn't have `istio_requests_*` metrics.

Do you have any idea why those filters don't exist on production? The installation command is the same for both environment, so I wonder why those config are mismatch.

**Comment by howardjohn** [comment]
that is what generates the stats, so it would explain it. Can you check `kubectl get envoyfilter -n istio-system` to ensure they are all aligned?

The other thing I would check, at the top fo the config dump will be ISTIO_VERSION. That needs to match the `proxyVersion` match on the envoyfilter, perhaps its somehow out of sync

**Comment by nguyenhoaibao** [comment]
Thanks, I ran `kubectl get envoyfilters.networking.istio.io -n istio-system stats-filter-1.7-1-7-3`, and see this output:

```
- applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              name: envoy.router
      proxy:
        proxyVersion: ^1\.7.*
    patch:
      operation: INSERT_BEFORE
      value:
        name: istio.stats
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          value:
            config:
              configuration:
                '@type': type.googleapis.com/google.protobuf.StringValue
                value: |
                  {
                    "debug": "false",
                    "stat_prefix": "istio",
                    "disable_host_header_fallback": true
                  }
              root_id: stats_outbound
              vm_config:
                code:
                  local:
                    inline_string: envoy.wasm.stats
                runtime: envoy.wasm.runtime.null
                vm_id: stats_outbound
```

But in the config dump output, this filter doesn't exist :thinking: 

> The other thing I would check, at the top fo the config dump will be ISTIO_VERSION. That needs to match the proxyVersion match on the envoyfilter

I checked and see that the ISTIO_VERSION from the config dump is `1.7.3`, and the `proxyVersion` is `^1\.7.*`, that means they're match right?

**Comment by douglas-reid** [comment]
@kyessenov can you take a look?

**Comment by kyessenov** [comment]
Is there some difference in ingress labels between staging and prod?

**Comment by Kaezon** [comment]
I'm having this issue with the 1.9.2 Helm charts.
Been digging around in the telemetry docs, but I'm pretty lost at this point.

Would any config data from my deployment help move this issue forward?

**Comment by Kaezon** [comment]
I found #29654, but adding a hub and tag and redeploying didn't change the situation. Besides, the docs seem to indicate setting those values is not needed in >= 1.9.0

**Comment by Kaezon** [comment]
Did more digging, and by running my EKS deployment into Microk8s, Istio provides the standard metrics which are absent in EKS.
I guess the good news is that I have an environment where this is broken and an environment where it's working. I just need to figure out why now.

**Comment by Kaezon** [comment]
I ran diffs of all the EnvoyFilters, Deployments, and ConfigMaps in istio-system between EKS and Microk8s.
I didn't find any differences except the UUIDs. I did notice while diffing the test workload, that Microk8s is apprently backed by containerd, while EKS is backed by Docker. I'm not sure if this would result in the problem I'm seeing, but it's there anyways.

**Comment by Kaezon** [comment]
@kyessenov I've now replicated the problem locally as well by deploying to a kind cluster.
As a brief recap. The metrics are missing for me when I deploy to EKS and kind. They are present when I deploy to microk8s.

Here is the kind cluster config I used:
```yaml
kind: Cluster
 apiVersion: kind.x-k8s.io/v1alpha4
 featureGates:
   # any feature gate can be enabled here with "Name": true
   # or disabled here with "Name": false
   # not all feature gates are tested, however
   TokenRequest: true
   TokenRequestProjection: true
 kubeadmConfigPatches:
   - |
     apiVersion: kubeadm.k8s.io/v1beta2
     kind: ClusterConfiguration
     metadata:
       name: config
     apiServer:
       extraArgs:
         "service-account-issuer": "kubernetes.default.svc"
         "service-account-signing-key-file": "/etc/kubernetes/pki/sa.key"
```
