### ISSUE TITLE
Intermittent 503 UH errors for egress to external services without duplicated service entries

### ISSUE THREAD

**Issue by h35gao** [istio/istio#28548]
**Bug Description**
Similar to https://github.com/istio/istio/issues/26282, we're getting intermittent 503 UH errors for egress to external services, _however_, we don't have duplicated service entries for the host.

**Istio sidecar logs**
Failed call with 503
```
{
                "authority": "example.com",
                "bytes_received": "0",
                "bytes_sent": "19",
                "downstream_local_address": "x.x.x.x:80",
                "downstream_remote_address": "x.x.x.x:41414",
                "duration": "0",
                "istio_policy_status": "-",
                "method": "POST",
                "path": "/as/token.oauth2",
                "protocol": "HTTP/1.1",
                "request_id": "7c747122-0506-4a04-9c52-2b580b3d4266",
                "requested_server_name": "-",
                "response_code": "503",
                "response_flags": "UH",
                "route_name": "-",
                "start_time": "2020-10-24T05:13:34.602Z",
                "upstream_cluster": "-",
                "upstream_host": "-",
                "upstream_local_address": "-",
                "upstream_service_time": "-",
                "upstream_transport_failure_reason": "-",
                "user_agent": "Java/11.0.4",
                "x_forwarded_for": "-"
}
```
Successful call
```
{
                "authority": "example.com",
                "bytes_received": "44",
                "bytes_sent": "557",
                "downstream_local_address": "x.x.x.x:80",
                "downstream_remote_address": "x.x.x.x:47960",
                "duration": "39",
                "istio_policy_status": "-",
                "method": "POST",
                "path": "/as/token.oauth2",
                "protocol": "HTTP/1.1",
                "request_id": "037ccd89-f078-4d07-9f9d-ff8af0021fac",
                "requested_server_name": "-",
                "response_code": "200",
                "response_flags": "-",
                "route_name": "-",
                "start_time": "2020-10-28T16:43:16.783Z",
                "upstream_cluster": "outbound|443|tls-origination|example.com",
                "upstream_host": "x.x.x.x:443",
                "upstream_local_address": "-",
                "upstream_service_time": "39",
                "upstream_transport_failure_reason": "-",
                "user_agent": "Java/11.0.4",
                "x_forwarded_for": "-"
}
```

**Configuration**
service entry, virtual service, and destination rule
```
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: example.com
spec:
  hosts:
  - example.com
  ports:
  - number: 80
    name: http-port
    protocol: HTTP
  - number: 443
    name: https-port-for-tls-origination
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: example.com
spec:
  hosts:
  - example.com
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: example.com
        subset: tls-origination
        port:
          number: 443
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: example.com
spec:
  host: example.com
  subsets:
  - name: tls-origination
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: SIMPLE
```

**Version (include the output of istioctl version --remote and kubectl version and helm version if you used Helm)**
istio: 1.4.9
k8s: 1.15.10

**How was Istio installed?**
helm template + kubectl apply

**Environment where bug was observed (cloud vendor, OS, etc)**
Azure Kubernetes Services
