### ISSUE TITLE
TCP connection closed after client sends data

### ISSUE THREAD

**Issue by bitmexgmarkey** [istio/istio#28574]
**Bug description**
Ingress connections are closed prematurely when the client sends data. I have confirmed that there is *some* application data flow, as I am primarily testing with a server-first application (NATS) and am able to receive the protocol preamble header.

I've tested with both TLS (via `openssl`) and TCP (via `nc`) modes on the gateway and both seem to show the same behaviour. I've also tested client-first by deploying an echo server, which just closes the connection immediately after I send a string + newline. I have also set the protocol selection via port names to `tcp-blah` for both my server first and client first services. Sidecar and ingress pods both show the connection in their log, but the log line appears to be normal. Note that I am purposely configuring a HTTP service as TCP inside the Istio configuration to demonstrate the problem.

Configuration notes:
* Deployed with IstioOperator.
* Using namespaced Istio ingress controllers via ELB/NLB (neither makes a difference to behaviour).

Behaviour in server-first (tested from outside cluster):
```
Connection to <fqdn> port 4222 [tcp/*] succeeded!
INFO {"server_id":"NAOTD2GMFDTXIRBUAQTGE6V7P64VCU7RNWWWFFLCSNHIYXOCTDQ3W4PO","server_name":"NAOTD2GMFDTXIRBUAQTGE6V7P64VCU7RNWWWFFLCSNHIYXOCTDQ3W4PO","version":"2.1.8","proto":1,"git_commit":"c0b574f","go":"go1.14.8","host":"0.0.0.0","port":4222,"max_payload":1048576,"client_id":17007,"client_ip":"127.0.0.1"}
PING
<connection is closed>
```

Behaviour in client-first (tested from outside cluster):
```
Connection to <fqdn> port 4222 [tcp/*] succeeded!
HEAD / HTTP/1.1
<connection is closed>
```

Gateway:
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  annotations:
  name: nats-dev
  namespace: nats-dev
spec:
  selector:
    istio: istio-private-ingressgateway-nats-dev
  servers:
  - hosts:
    - <fqdn>
    port:
      name: nats
      number: 4222
      protocol: TCP
```

VirtualService:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nats-dev
  namespace: nats-dev
spec:
  gateways:
  - nats-dev
  hosts:
  - <fqdn>
  tcp:
  - match:
    - port: 4222
    route:
    - destination:
        host: nats-dev-client.nats-dev.svc.cluster.local
        port:
          number: 4222
```

IstioOperator (main):
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
  namespace: istio-system
spec:
  components:
    cni:
      enabled: true
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
  hub: docker.io/istio
  meshConfig:
    accessLogFile: /dev/stdout
    protocolDetectionTimeout: 1s
  profile: default
  tag: 1.6.4
  values:
    cni:
      excludeNamespaces:
      - istio-system
      - kube-system
      logLevel: info
status:
  componentStatus:
    IngressGateways:
      status: HEALTHY
  status: HEALTHY
```

IstioOperator (ingress gateway):
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-ingressgateway-nats-dev
  namespace: istio-system
spec:
  components:
    cni:
      enabled: false
    egressGateways:
    - enabled: false
      name: istio-egressgateway
    ingressGateways:
    - enabled: false
      name: istio-ingressgateway
    - enabled: true
      k8s:
        replicaCount: 1
        service:
          ports:
          - name: status-port
            port: 15021
            targetPort: 15021
          - name: http2
            port: 80
            targetPort: 80
          - name: https
            port: 443
            targetPort: 8443
          - name: tls
            port: 15443
            targetPort: 15443
          - name: custom
            port: 4222
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-internal: "true"
          service.beta.kubernetes.io/aws-load-balancer-type: elb
      label:
        app: istio-private-ingressgateway-nats-dev
        istio: istio-private-ingressgateway-nats-dev
      name: istio-private-ingressgateway-nats-dev
      namespace: nats-dev
    - enabled: false
      k8s:
        replicaCount: 1
        service:
          ports:
          - name: status-port
            port: 15021
            targetPort: 15021
          - name: http2
            port: 80
            targetPort: 80
          - name: https
            port: 443
            targetPort: 8443
          - name: tls
            port: 15443
            targetPort: 15443
          - name: custom
            port: 4222
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-internal: "false"
          service.beta.kubernetes.io/aws-load-balancer-type: elb
      label:
        app: istio-public-ingressgateway-nats-dev
        istio: istio-public-ingressgateway-nats-dev
      name: istio-public-ingressgateway-nats-dev
      namespace: nats-dev
    istiodRemote:
      enabled: false
    policy:
      enabled: false
    telemetry:
      enabled: false
  hub: docker.io/istio
  meshConfig:
    accessLogFile: /dev/stdout
    protocolDetectionTimeout: 5s
  profile: empty
  tag: 1.6.4
status:
  componentStatus:
    IngressGateways:
      status: HEALTHY
  status: HEALTHY
```

[ ] Docs
[ ] Installation
[ x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Expected behaviour in server-first (tested from inside cluster, to ClusterIP service):
```
<fqdn> [172.20.189.191] 4222 (?) open
INFO {"server_id":"NCGAUK4MVMVIXEQJZNPNHKXSTEHRYQCOJLQMRSGGWBKPGYNZ75JJSGA7","server_name":"NCGAUK4MVMVIXEQJZNPNHKXSTEHRYQCOJLQMRSGGWBKPGYNZ75JJSGA7","version":"2.1.8","proto":1,"git_commit":"c0b574f","go":"go1.14.8","host":"0.0.0.0","port":4222,"max_payload":1048576,"client_id":17006,"client_ip":"127.0.0.1"}
PING
PONG
^C
```

Expected behaviour in client-first (tested from inside cluster, to ClusterIP service):
```
<fqdn> [172.20.51.215] 80 (?) open
HEAD / HTTP/1.1
Host: localhost

HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Content-Length: 2908
ETag: W/"b5c-nBWCtuDxXFVGBTIYUg3VBK7xJZk"
Date: Wed, 04 Nov 2020 10:54:51 GMT
Connection: keep-alive

^C sent 33, rcvd 192
```

**Steps to reproduce the bug**

See attached configurations; example command `nc <fqdn> 4222 -vv`

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

Istio (I had issues with headless services being unusable in v1.7.x and downgraded to this version based on recommendations in other bug reports):
```
client version: 1.6.4
control plane version: 1.6.4
data plane version: 1.6.4 (10 proxies)
```

Kubectl:
```
Client Version: v1.18.8
Server Version: v1.17.9-eks-4c6976
```

Helm:
```
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.6"}
```

**How was Istio installed?**

Helm installed the IstioOperator chart.

**Environment where bug was observed (cloud vendor, OS, etc)**

EKS v1.17.9-eks-4c6976, Kubelets are custom AMI based on Ubuntu 20.04 with K8s version 1.17.12.
