### ISSUE TITLE
"No healthy host for TCP connection pool" on plain TCP Services in Multicluster - 1.7.x

### ISSUE THREAD

**Issue by blackenz** [istio/istio#28573]
**Bug description**
Plain TCP services on a replicated control plane multicluster steup, fail with with a "No healthy host for TCP connection pool". Bug does not affect HTTP services.
This bug seems to affect every 1.7.x version.
Also, 1.7.4 version doesn't seem to fix the new EnvoyFilter bug referecend in [https://github.com/istio/istio/issues/27909](url)

[ x ] Docs
[ ] Installation
[ x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Plain TCP services should have the same behavior as HTTP services

**Actual behavior**
Ingress gateway logs on cluster1:

```
2020-11-03T18:55:16.325974Z	debug	envoy filter	tls inspector: new connection accepted
2020-11-03T18:55:16.326041Z	trace	envoy filter	tls inspector: recv: 228
2020-11-03T18:55:16.326098Z	debug	envoy filter	tls:onServerName(), requestedServerName: outbound_.7000_._.istio-multicluster-test.default.global
2020-11-03T18:55:16.326306Z	debug	envoy filter	[C52] new tcp proxy session
2020-11-03T18:55:16.326339Z	trace	envoy connection	[C52] readDisable: disable=true disable_count=0 state=0 buffer_length=0
2020-11-03T18:55:16.326363Z	trace	envoy filter	[C52] sni_cluster: new connection with server name outbound_.7000_._.istio-multicluster-test.default.global
2020-11-03T18:55:16.326412Z	trace	envoy filter	[C52] tcp_cluster_rewrite: new connection with server name outbound_.7000_._.istio-multicluster-test.default.global
2020-11-03T18:55:16.326460Z	trace	envoy filter	[C52] tcp_cluster_rewrite: final tcp proxy cluster name outbound_.7000_._.istio-multicluster-test.default.svc.cluster.local
2020-11-03T18:55:16.326535Z	debug	envoy filter	[C52] Creating connection to cluster outbound_.7000_._.istio-multicluster-test.default.svc.cluster.local
2020-11-03T18:55:16.326577Z	debug	envoy pool	creating a new connection
2020-11-03T18:55:16.326665Z	debug	envoy pool	[C53] connecting
2020-11-03T18:55:16.326680Z	debug	envoy connection	[C53] connecting to 10.32.0.13:7000
2020-11-03T18:55:16.327064Z	debug	envoy connection	[C53] connection in progress
2020-11-03T18:55:16.327098Z	debug	envoy pool	queueing request due to no available connections
2020-11-03T18:55:16.327110Z	debug	envoy conn_handler	[C52] new connection
2020-11-03T18:55:16.327157Z	trace	envoy connection	[C52] socket event: 2
2020-11-03T18:55:16.327165Z	trace	envoy connection	[C52] write ready
2020-11-03T18:55:16.327172Z	trace	envoy connection	[C53] socket event: 2
2020-11-03T18:55:16.327177Z	trace	envoy connection	[C53] write ready
2020-11-03T18:55:16.327187Z	debug	envoy connection	[C53] connected
2020-11-03T18:55:16.327197Z	debug	envoy pool	[C53] assigning connection
2020-11-03T18:55:16.327241Z	trace	envoy connection	[C52] readDisable: disable=false disable_count=1 state=0 buffer_length=0
2020-11-03T18:55:16.327268Z	debug	envoy filter	TCP:onUpstreamEvent(), requestedServerName: outbound_.7000_._.istio-multicluster-test.default.global
2020-11-03T18:55:16.327292Z	trace	envoy connection	[C52] socket event: 3
2020-11-03T18:55:16.327298Z	trace	envoy connection	[C52] write ready
2020-11-03T18:55:16.327305Z	trace	envoy connection	[C52] read ready. dispatch_buffered_data=false
2020-11-03T18:55:16.327329Z	trace	envoy connection	[C52] read returns: 228
2020-11-03T18:55:16.327350Z	trace	envoy connection	[C52] read error: Resource temporarily unavailable
2020-11-03T18:55:16.327364Z	trace	envoy filter	[C52] downstream connection received 228 bytes, end_stream=false
2020-11-03T18:55:16.327373Z	trace	envoy filter	Alpn Protocol Not Found. Expected istio-peer-exchange, Got 
2020-11-03T18:55:16.327384Z	trace	envoy connection	[C53] writing 228 bytes, end_stream false
2020-11-03T18:55:16.327399Z	trace	envoy connection	[C53] socket event: 2
2020-11-03T18:55:16.327405Z	trace	envoy connection	[C53] write ready
2020-11-03T18:55:16.327528Z	trace	envoy connection	[C53] write returns: 228
2020-11-03T18:55:16.334763Z	trace	envoy connection	[C53] socket event: 3
2020-11-03T18:55:16.334796Z	trace	envoy connection	[C53] write ready
2020-11-03T18:55:16.334805Z	trace	envoy connection	[C53] read ready. dispatch_buffered_data=false
2020-11-03T18:55:16.334827Z	trace	envoy connection	[C53] read returns: 6659
2020-11-03T18:55:16.334846Z	trace	envoy connection	[C53] read error: Resource temporarily `unavailable`
```

kubectl describe pod istio-multicluster-test-69b66d64df-kq8mq:

```
Name:         istio-multicluster-test-69b66d64df-kq8mq
Namespace:    default
Priority:     0
Node:         cluster1-slave1/192.168.10.21
Start Time:   Tue, 03 Nov 2020 18:40:34 +0000
Labels:       app=istio-multicluster-test
              istio.io/rev=default
              pod-template-hash=69b66d64df
              security.istio.io/tlsMode=istio
              service.istio.io/canonical-name=istio-multicluster-test
              service.istio.io/canonical-revision=latest
Annotations:  prometheus.io/path: /stats/prometheus
              prometheus.io/port: 15020
              prometheus.io/scrape: true
              sidecar.istio.io/status:
                {"version":"8e6e902b765af607513b28d284940ee1421e9a0d07698741693b2663c7161c11","initContainers":["istio-init"],"containers":["istio-proxy"]...
Status:       Running
IP:           10.32.0.13
IPs:
  IP:           10.32.0.13
Controlled By:  ReplicaSet/istio-multicluster-test-69b66d64df
Init Containers:
  istio-init:
    Container ID:  docker://437d860e25b2986bc882fd4cd81b0e4a45ea5232fb1855b5551c3cd2ae77abce
    Image:         docker.io/istio/proxyv2:1.7.4
    Image ID:      docker-pullable://istio/proxyv2@sha256:17faf9ddc1254ad98cc70fb11fa74043ce2705f3272eace3fa7011a29576c8f1
    Port:          <none>
    Host Port:     <none>
    Args:
      istio-iptables
      -p
      15001
      -z
      15006
      -u
      1337
      -m
      REDIRECT
      -i
      *
      -x

      -b
      *
      -d
      15090,15021,15020
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 03 Nov 2020 18:40:37 +0000
      Finished:     Tue, 03 Nov 2020 18:40:38 +0000
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:     10m
      memory:  10Mi
    Environment:
      DNS_AGENT:
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-kcn8b (ro)
Containers:
  busybox-nc-server:
    Container ID:  docker://9b1c94b006fe7c51d82fbf103ef06ae61c2e09167caba9d6161f1162fd658ee2
    Image:         busybox:1.28
    Image ID:      docker-pullable://busybox@sha256:141c253bc4c3fd0a201d32dc1f493bcf3fff003b6df416dea4f41046e0f37d47
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
    Args:
      while ! wget -q -O - http://localhost:15000/server_info | \
            grep '"state": "LIVE"' ; do
          echo "Waiting for proxy"
      done
      exec nc -nlp 7000 > /tmp/out.txt

    State:          Running
      Started:      Tue, 03 Nov 2020 18:55:31 +0000
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 03 Nov 2020 18:55:17 +0000
      Finished:     Tue, 03 Nov 2020 18:55:18 +0000
    Ready:          True
    Restart Count:  2
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-kcn8b (ro)
  istio-proxy:
    Container ID:  docker://1310135b360f5c88cdad336b3e2ec17cdefe4cfc351773072a2daafc1ecdff35
    Image:         docker.io/istio/proxyv2:1.7.4
    Image ID:      docker-pullable://istio/proxyv2@sha256:17faf9ddc1254ad98cc70fb11fa74043ce2705f3272eace3fa7011a29576c8f1
    Port:          15090/TCP
    Host Port:     0/TCP
    Args:
      proxy
      sidecar
      --domain
      $(POD_NAMESPACE).svc.cluster.local
      --serviceCluster
      istio-multicluster-test.$(POD_NAMESPACE)
      --proxyLogLevel=warning
      --proxyComponentLogLevel=misc:error
      --trust-domain=cluster.local
      --concurrency
      2
    State:          Running
      Started:      Tue, 03 Nov 2020 18:40:41 +0000
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:      100m
      memory:   128Mi
    Readiness:  http-get http://:15021/healthz/ready delay=1s timeout=1s period=2s #success=1 #failure=30
    Environment:
      JWT_POLICY:                    first-party-jwt
      PILOT_CERT_PROVIDER:           istiod
      CA_ADDR:                       istiod.istio-system.svc:15012
      POD_NAME:                      istio-multicluster-test-69b66d64df-kq8mq (v1:metadata.name)
      POD_NAMESPACE:                 default (v1:metadata.namespace)
      INSTANCE_IP:                    (v1:status.podIP)
      SERVICE_ACCOUNT:                (v1:spec.serviceAccountName)
      HOST_IP:                        (v1:status.hostIP)
      CANONICAL_SERVICE:              (v1:metadata.labels['service.istio.io/canonical-name'])
      CANONICAL_REVISION:             (v1:metadata.labels['service.istio.io/canonical-revision'])
      PROXY_CONFIG:                  {"proxyMetadata":{"DNS_AGENT":""}}

      ISTIO_META_POD_PORTS:          [
                                     ]
      ISTIO_META_APP_CONTAINERS:     busybox-nc-server
      ISTIO_META_CLUSTER_ID:         Kubernetes
      ISTIO_META_INTERCEPTION_MODE:  REDIRECT
      ISTIO_META_WORKLOAD_NAME:      istio-multicluster-test
      ISTIO_META_OWNER:              kubernetes://apis/apps/v1/namespaces/default/deployments/istio-multicluster-test
      ISTIO_META_MESH_ID:            cluster.local
      DNS_AGENT:
      ISTIO_KUBE_APP_PROBERS:        {}
    Mounts:
      /etc/istio/pod from istio-podinfo (rw)
      /etc/istio/proxy from istio-envoy (rw)
      /var/lib/istio/data from istio-data (rw)
      /var/run/secrets/istio from istiod-ca-cert (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-kcn8b (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
```

istioctl proxy-config listeners istio-multicluster-test-69b66d64df-kq8mq.default output on 

```
ADDRESS        PORT  MATCH                                      DESTINATION
10.96.0.10     53    ALL                                        Cluster: outbound|53||kube-dns.kube-system.svc.cluster.local
10.97.57.156   53    ALL                                        Cluster: outbound|53||istiocoredns.istio-system.svc.cluster.local
0.0.0.0        80    App: HTTP                                  Route: 80
0.0.0.0        80    ALL                                        PassthroughCluster
10.108.41.66   443   ALL                                        Cluster: outbound|443||istiod.istio-system.svc.cluster.local
10.96.0.1      443   ALL                                        Cluster: outbound|443||kubernetes.default.svc.cluster.local
10.99.194.39   443   App: HTTP                                  Route: kubernetes-dashboard.kubernetes-dashboard.svc.cluster.local:443
10.99.194.39   443   ALL                                        Cluster: outbound|443||kubernetes-dashboard.kubernetes-dashboard.svc.cluster.local
10.99.99.91    443   ALL                                        Cluster: outbound|443||istio-ingressgateway.istio-system.svc.cluster.local
10.108.41.66   853   App: HTTP                                  Route: istiod.istio-system.svc.cluster.local:853
10.108.41.66   853   ALL                                        Cluster: outbound|853||istiod.istio-system.svc.cluster.local
10.111.191.110 7000  ALL                                        Cluster: outbound|7000||istio-multicluster-test.default.svc.cluster.local
<Redacted>
0.0.0.0        8383  App: HTTP                                  Route: 8383
0.0.0.0        8383  ALL                                        PassthroughCluster
0.0.0.0        9090  App: HTTP                                  Route: 9090
0.0.0.0        9090  ALL                                        PassthroughCluster
10.96.0.10     9153  App: HTTP                                  Route: kube-dns.kube-system.svc.cluster.local:9153
10.96.0.10     9153  ALL                                        Cluster: outbound|9153||kube-dns.kube-system.svc.cluster.local
0.0.0.0        15001 ALL                                        PassthroughCluster
0.0.0.0        15006 Trans: tls; App: HTTP TLS; Addr: 0.0.0.0/0 Inline Route: /*
0.0.0.0        15006 App: HTTP; Addr: 0.0.0.0/0                 Inline Route: /*
0.0.0.0        15006 Trans: tls; App: TCP TLS; Addr: 0.0.0.0/0  InboundPassthroughClusterIpv4
0.0.0.0        15006 Addr: 0.0.0.0/0                            InboundPassthroughClusterIpv4
0.0.0.0        15006 App: TCP TLS                               Cluster: inbound|7000|tcp-nc|istio-multicluster-test.default.svc.cluster.local
0.0.0.0        15006 ALL                                        Cluster: inbound|7000|tcp-nc|istio-multicluster-test.default.svc.cluster.local
0.0.0.0        15010 App: HTTP                                  Route: 15010
0.0.0.0        15010 ALL                                        PassthroughCluster
10.108.41.66   15012 ALL                                        Cluster: outbound|15012||istiod.istio-system.svc.cluster.local
0.0.0.0        15014 App: HTTP                                  Route: 15014
0.0.0.0        15014 ALL                                        PassthroughCluster
0.0.0.0        15021 ALL                                        Non-HTTP/Non-TCP
10.99.99.91    15021 App: HTTP                                  Route: istio-ingressgateway.istio-system.svc.cluster.local:15021
10.99.99.91    15021 ALL                                        Cluster: outbound|15021||istio-ingressgateway.istio-system.svc.cluster.local
0.0.0.0        15090 ALL                                        Non-HTTP/Non-TCP
10.99.99.91    15443 ALL                                        Cluster: outbound|15443||istio-ingressgateway.istio-system.svc.cluster.local
0.0.0.0        20001 App: HTTP                                  Route: 20001
0.0.0.0        20001 ALL                                        PassthroughCluster
```

**Steps to reproduce the bug**
Using the following deployment on cluster1:

```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: istio-multicluster-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istio-multicluster-test
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: istio-multicluster-test
    spec:
      containers:
        - name: busybox-nc-server
          image: 'busybox:1.28'
          command:
            - /bin/sh
            - '-c'
          args:
            - |
              while ! wget -q -O - http://localhost:15000/server_info | \
                    grep '"state": "LIVE"' ; do
                  echo "Waiting for proxy"
              done
              exec nc -nlp 7000
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
```
ServiceEntry on cluster2:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: istio-multicluster-test-se
  namespace: default
spec:
  addresses:
    - 240.0.0.222
  endpoints:
    - address: <Redacted>
      ports:
        netcat: 30331
  hosts:
    - istio-multicluster-test.default.global
  location: MESH_INTERNAL
  ports:
    - name: netcat
      number: 7000
      protocol: TCP
  resolution: DNS
```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
```
➜  ~ istioctl version
client version: 1.7.4
control plane version: 1.7.4
data plane version: 1.7.4 (3 proxies)
```

```
➜  ~ kubectl version --short
Client Version: v1.18.2
Server Version: v1.19.3
```

**How was Istio installed?**
2 virtualized 1.19.3 Kubernetes clusters on Ubuntu 20.04
Vanilla istio instalation made with istioctl operator init command. The following configuration was applied in both clusters:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-controlplane
  namespace: istio-system
spec:
  profile: default
  meshConfig:
    accessLogEncoding: JSON
  addonComponents:
    kiali:
      enabled: true
    prometheus:
      enabled: true
    istiocoredns:
      enabled: true
    ingressGateways:
      enabled: true
  components:
    ingressGateways:
      - label:
          custom-ingress: global-prod
        name: istio-ingressgateway
  values:
    gateways:
      istio-ingressgateway:
        sds:
          enabled: true
    global:
      hub: docker.io/istio
      multiCluster:
        enabled: true
      controlPlaneSecurityEnabled: true
      podDNSSearchNamespaces:
        - global
```

**Environment where bug was observed (cloud vendor, OS, etc)**
On prem clusters
Ingress gateway configured as NodePort, but with the same behavior when configured as LoadBalancer
