### ISSUE TITLE
Multiple Egress not Working and Inconsistent Behavior with Deploy Order

### ISSUE THREAD

**Issue by LSChyi** [istio/istio#28613]
**Bug description**
Some external service is getting 503 when deploying multiple HTTP egress resources. Also, this bug is related to the order of when the resource is deployed. This issue exists when deploying resources with some specific orders.

When getting the 503, the sidecar log shows there is no route (`503 NR`), and the traffic is not sent to the `istio-egressgateway` pod for no logs emerges in it.

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Traffic with multiple egress resources should not be blocked, also, the order of deploying egress resources should not affect the traffic.

**Steps to reproduce the bug**

There are two sets of egress resources to two different external websites:

1. [TEIL](http://teilab.ee.ntu.edu.tw/)
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: teilab-ee-ntu-edu-tw
spec:
  hosts:
  - teilab.ee.ntu.edu.tw
  ports:
  - number: 80
    name: teilab-ee-ntu-edu-tw-80-HTTP
    protocol: HTTP
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: teilab-ee-ntu-edu-tw
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 80
      name: teilab-ee-ntu-edu-tw-80-HTTP
      protocol: HTTP
    hosts:
    - teilab.ee.ntu.edu.tw
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: teilab-ee-ntu-edu-tw
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: teil
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: teilab-ee-ntu-edu-tw
spec:
  hosts:
  - teilab.ee.ntu.edu.tw
  gateways:
  - teilab-ee-ntu-edu-tw
  - mesh
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: teil
        port:
          number: 80
  - match:
    - gateways:
      - teilab-ee-ntu-edu-tw
      port: 80
    route:
    - destination:
        host: teilab.ee.ntu.edu.tw
        port:
          number: 80
```

2. [CNN](http://edition.cnn.com/)

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cnn
spec:
  hosts:
  - edition.cnn.com
  ports:
  - number: 80
    name: http-port
    protocol: HTTP
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cnn
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 80
      name: http-port
      protocol: HTTP
    hosts:
    - edition.cnn.com
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: cnn
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: cnn
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cnn
spec:
  hosts:
  - edition.cnn.com
  gateways:
  - cnn
  - mesh
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: cnn
        port:
          number: 80
  - match:
    - gateways:
      - cnn
      port: 80
    route:
    - destination:
        host: edition.cnn.com
        port:
          number: 80
```

If first deloy all the resources of CNN then TEIL, the traffic is ok; if first deploy the CNN then TEIL, accessing the `http://edition.cnn.com/politics` endpoint will get a HTTP 503 response but traffic to TEIL is ok.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

```
$ istioctl version --remote
client version: 1.6.11
control plane version: 1.6.11
data plane version: 1.6.11 (4 proxies)
```

```
$ kubectl version --short
Client Version: v1.19.3
Server Version: v1.15.12
```

**How was Istio installed?**

```
$ ./istioctl install --set profile=demo
```

**Environment where bug was observed (cloud vendor, OS, etc)**

The bug is observed on a Rancher v2.2.13 installed cluster.
