### ISSUE TITLE
Istio 1.5.6 Retries Not working

### ISSUE THREAD

**Issue by rajivml** [istio/istio#28614]
HI,

Environment: Baremetal Kubernetes 1.16
Istio Version: 1.5.6
Http Method: POST

Am trying to configure retries for all 5xx errors but looks like none of the requests are getting retried. If we notice the route that is generated, it's getting overwritten always with retriableStatusCodes as 503 regardless of what ever value that I specify for retryOn field

This is my Virtual Service Config:

```
kubectl -n c6b482ca-0f32-4d06-b752-62e56f056d6a get vs sl-ac4a938e-51a6-4cca-86e9-23861ca5502e -o yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app: sl-ac4a938e-51a6-4cca-86e9-23861ca5502e
  name: sl-ac4a938e-51a6-4cca-86e9-23861ca5502e
  namespace: c6b482ca-0f32-4d06-b752-62e56f056d6a
spec:
  gateways:
  - istio-system/xxxx-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        exact: xxxx
    - uri:
        exact: xxxx
    retries:
      attempts: 3
      perTryTimeout: 5s
      retryOn: 5xx,reset
    rewrite:
      uri: /predict
    route:
    - destination:
        host: sl-ac4a938e-51a6-4cca-86e9-23861ca5502e-1
        port:
          number: 5000
    timeout: 10s
  - match:
    - uri:
        exact: xxxx/iriswithtrain/info/model
    - uri:
        exact: xxxx/iriswithtrain/info/model
    retries:
      attempts: 3
      perTryTimeout: 1s
      retryOn: 5xx,reset
    rewrite:
      uri: /info
    route:
    - destination:
        host: sl-ac4a938e-51a6-4cca-86e9-23861ca5502e-1
        port:
          number: 5000

```

And this is the route,

./bin/istioctl proxy-config routes ac4a938e-51a6-4cca-86e9-23861ca5502e-1-5b8b7f6bf9-29lgh --namespace c6b482ca-0f32-4d06-b752-62e56f056d6a --name 5000 -o json

```
"routes": [
                    {
                        "name": "default",
                        "match": {
                            "prefix": "/"
                        },
                        "route": {
                            "cluster": "outbound|5000||sl-ac4a938e-51a6-4cca-86e9-23861ca5502e-1.c6b482ca-0f32-4d06-b752-62e56f056d6a.svc.cluster.local",
                            "timeout": "0s",
                            "retryPolicy": {
                                "retryOn": "connect-failure,refused-stream,unavailable,cancelled,resource-exhausted,retriable-status-codes",
                                "numRetries": 2,
                                "retryHostPredicate": [
                                    {
                                        "name": "envoy.retry_host_predicates.previous_hosts"
                                    }
                                ],
                                "hostSelectionRetryMaxAttempts": "5",
                                "retriableStatusCodes": [
                                    503
                                ]
                            },
                            "maxGrpcTimeout": "0s"
                        },
                        "decorator": {
                            "operation": "sl-ac4a938e-51a6-4cca-86e9-23861ca5502e-1.c6b482ca-0f32-4d06-b752-62e56f056d6a.svc.cluster.local:5000/*"
                        }
                    }
                ]
```

How do I make sure that all 5xx are retried here ? am I missing any config here ? I have been debugging from last 2 days and couldn't figure out what's the reason for the same

**Comment by hzxuzhonghu** [comment]
`"retryOn": "connect-failure,refused-stream,unavailable,cancelled,resource-exhausted,retriable-status-codes",`
This is the default retry policy, it seems the vs you declared that not matching the root path

**Comment by howardjohn** [comment]
Becauseo f 

>  gateways:
>  - istio-system/xxxx-gateway

This only applies to the gateway. Looks like the config you have is a sidecar. You should add gateways=[mesh] for it to apply to sidecars

**Comment by rajivml** [comment]
@howardjohn thanks for your reply,  I have modified the config as you suggested, where I have set gateways to mesh and I can now see the default config is overrided i.e retryOn is set to 5xx now

But now the problem am facing is, I have one gateway which is common to all the namespaces and all the VS in other namespaces are pointing to the common GW, but after changing the gateway to mesh, the traffic isn't getting routed, I tried adding both mesh and my_gateway as list under gateways but still traffic isn't getting routed 


```
kubectl -n c6b482ca-0f32-4d06-b752-62e56f056d6a get vs -o yaml
apiVersion: v1
items:
- apiVersion: networking.istio.io/v1beta1
  kind: VirtualService
  metadata:
    labels:
      app: sl-2936cdfa-d6b6-499b-97f2-385bb2f44e8e
    name: sl-2936cdfa-d6b6-499b-97f2-385bb2f44e8e
    namespace: c6b482ca-0f32-4d06-b752-62e56f056d6a
  spec:
    gateways:
    - mesh
    hosts:
    - sl-2936cdfa-d6b6-499b-97f2-385bb2f44e8e-1
    http:
    - match:
      - uri:
          exact: /xxx/host/c6b482ca-0f32-4d06-b752-62e56f056d6a/iris
      - uri:
          exact: /xxx-test/host/c6b482ca-0f32-4d06-b752-62e56f056d6a/iris
      retries:
        attempts: 3
        perTryTimeout: 10s
        retryOn: 5xx
      rewrite:
        uri: /predict
      route:
      - destination:
          host: sl-2936cdfa-d6b6-499b-97f2-385bb2f44e8e-1
          port:
            number: 5000
    - match:
      - uri:
          exact: /xxxx/host/c6b482ca-0f32-4d06-b752-62e56f056d6a/iris/info/model
      - uri:
          exact: /xxxx-test/host/c6b482ca-0f32-4d06-b752-62e56f056d6a/iris/info/model
      retries:
        attempts: 3
        perTryTimeout: 10s
        retryOn: 5xx
      rewrite:
        uri: /info
      route:
      - destination:
          host: sl-2936cdfa-d6b6-499b-97f2-385bb2f44e8e-1
          port:
            number: 5000
```

**Comment by rajivml** [comment]
> `"retryOn": "connect-failure,refused-stream,unavailable,cancelled,resource-exhausted,retriable-status-codes",`
> This is the default retry policy, it seems the vs you declared that not matching the root path

HI, can you plz share an example, not sure what do u meant by root path

**Comment by rajivml** [comment]
Step 1) istio-gateway installed under istio-system namespace and this GW is common for the VS present in all the namespaces 

```
kubectl -n istio-system get gw istio-gateway -o yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-gateway
  namespace: istio-system
  selfLink: /apis/networking.istio.io/v1beta1/namespaces/istio-system/gateways/istio-gateway
  uid: cd33e82d-619a-4c9a-bee1-e93c8e05abe2
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: istio-ingressgateway-certs
      mode: SIMPLE
      privateKey: sds
      serverCertificate: sds
```
			

Step 2) 

VS config of the target namespace, as per the suggestion over this thread, I have added "mesh" to the list of gateways and since we can't use "*" with "mesh", I have changed 
the hosts to point to my service short name i.e sl-a7862744-2cd5-4c33-a221-7d5014925389-1


```
kubectl -n c6b482ca-0f32-4d06-b752-62e56f056d6a get vs sl-a7862744-2cd5-4c33-a221-7d5014925389 -o yaml

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sl-a7862744-2cd5-4c33-a221-7d5014925389
  namespace: c6b482ca-0f32-4d06-b752-62e56f056d6a
spec:
  gateways:
  - istio-system/istio-gateway
	- mesh 
  hosts:
  - 'sl-a7862744-2cd5-4c33-a221-7d5014925389-1'
  http:
  - match:
    - uri:
        exact: /models/host/c6b482ca-0f32-4d06-b752-62e56f056d6a/iris
    - uri:
        exact: /models-test/host/c6b482ca-0f32-4d06-b752-62e56f056d6a/iris
    retries:
      attempts: 3
      perTryTimeout: 600s
      retryOn: 5xx,gateway-error,connect-failure,refused-stream
    rewrite:
      uri: /predict
    route:
    - destination:
        host: sl-a7862744-2cd5-4c33-a221-7d5014925389-1
        port:
          number: 5000
  - match:
    - uri:
        exact: /models/host/c6b482ca-0f32-4d06-b752-62e56f056d6a/iris/info/model
    - uri:
        exact: /models-test/host/c6b482ca-0f32-4d06-b752-62e56f056d6a/iris/info/model
    retries:
      attempts: 3
      perTryTimeout: 600s
      retryOn: 5xx,gateway-error,connect-failure,refused-stream
    rewrite:
      uri: /info
    route:
    - destination:
        host: sl-a7862744-2cd5-4c33-a221-7d5014925389-1
        port:
          number: 5000
```
					
Now, after adding "mesh" to the list of gateways and changing host from "*" to serviceName, forget retries, the entire routing stopped working. Do you guys see any issue with this 
config ?

My use case is, I want the envoy to retry 3 times for any 5xx , by default 503's are only retriable but in my case even 503's aren't getting retried
