### ISSUE TITLE
Istio metrics causes Kiali to show incorrect graph - "unknown" instatead of "istio-ingressgateway"

### ISSUE THREAD

**Issue by niscoveanumircea** [istio/istio#28618]
**Bug description**

My workloads are deployed in the `default` namespace along with the `gateway` and the `virtualService` that I use to configure the `istio-ingressgateway` which is installed in the `istio-system` namespace.
When I use Kiali to visualize any graph in the `default` namespace, it shows that the entry of the traffic in the mesh is represented by the object `unknown` instead of `istio-ingressgateway`.  In all demos and images on google it shows that the edge/entry is represented by the `istio-ingressgateway` from `istio-system` namespace.

Is this the normal behavior of istio newer versions or it is a bug ?
First I raised this issue on Kiali google group _kiali-users_ and I was advised to raise the issue to Istio because Kiali is only showing the graphs based on the metrics from the mesh.

Gateway:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway-default
  namespace: default
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
```
VirtualService
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-default-vs    # also tried with "default/gateway-default" value
  namespace: default
spec:
  hosts:
  - "*"
  gateways:
  - gateway-default
  http:
  - match:
    - headers:
        Host:
          exact: mail.kube.avan.local
    route:
    - destination:
        host: mailhog.default.svc.cluster.local
        port:
          number: 8025
... ...a long list of matching rules based on host header
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
The edge/entry in the mesh should represented by the `istio-ingressgateway` from `istio-system` namespace:

[What I expect in the graph](https://user-images.githubusercontent.com/22934144/98263517-9bd2cd00-1f8f-11eb-9faa-5c371dd39965.jpg)
(https://aws1.discourse-cdn.com/business4/uploads/istio/original/2X/1/1d7f31ba3168e3b657b94fbf9f90ed97e738e4af.png)
![what-i-expect](https://user-images.githubusercontent.com/22934144/98263932-071c9f00-1f90-11eb-85c7-8eb90c40ea13.png)

[What i get - with "unknown" as entry in the mesh](https://05364756918471548399.googlegroups.com/attach/34757dcf65d0a/Auto%20Generated%20Inline%20Image%202?part=0.2&view=1&vt=ANaJVrFQzL0IpStA8gLU-TvbbOsq2myzmPBSEvhYeerf8ZV90FA4V54lhioFPrCUcqCX2g8wrhOEXiPWYzNmdTmHCcHBC6hB4olPpJTMqy9D5D2ftxOI8UE)
![what-i-get](https://user-images.githubusercontent.com/22934144/98263972-17347e80-1f90-11eb-81fd-a6b2d0b8b447.png)

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
```
# istioctl version --remote
client version: 1.7.3
control plane version: 1.7.3
data plane version: 1.7.3 (66 proxies)
```
```
kubectl version --short
Client Version: v1.19.2
Server Version: v1.19.2

PS: I have also tried with kubernetes 1.18. and istio 1.6.1 and I get the same result.
```
**How was Istio installed?**
```
istioctl manifest generate --set values.global.jwtPolicy=first-party-jwt --set profile=demo | kubectl apply -f -
+
kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.7/samples/addons/kiali.yaml
+
$ kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.7/samples/addons/prometheus.yaml
```
**Environment where bug was observed (cloud vendor, OS, etc)**
`CentOS Linux release 7.7 -> single node kubernetes installed with kubeadm`

**Comment by niscoveanumircea** [comment]
Hi everyone. Any thoughts on this issue ?  Have anyone faced this ?
Thank you in advance.

**Comment by niscoveanumircea** [comment]
It seems that I had a misconfiguration that caused the behavior I described. It is mandatory to name the ports of the Services in order to get the correct graphs in Kiali.

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: core-www
  name: core-www
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
    name: "http-8081"
  selector:
    app: core-www
  type: ClusterIP
```
