### ISSUE TITLE
Seeing istio-proxy envoy errors on ingress and egress gateways

### ISSUE THREAD

**Issue by akhilgoel09** [istio/istio#28631]
I am seeing the below warning messages on my ingress and egress gateway:

```
shutdown-time-s 60 --service-cluster istio-egressgateway --service-node router~100.108.109.202~istio-egressgateway-6798874b8-bngkr.istio-system~istio-system.svc.cluster.local --local-address-ip-version v4 --log-format-prefix-with-location 0 --log-format %Y-%m-%dT%T.%fZ	%l	envoy %n	%v -l warning --component-log-level misc:error]
2020-11-05T19:59:13.759618Z	warning	envoy runtime	Unable to use runtime singleton for feature envoy.reloadable_features.activate_fds_next_event_loop
2020-11-05T19:59:13.790458Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 14, no healthy upstream
2020-11-05T19:59:13.790485Z	warning	envoy config	Unable to establish new stream
2020-11-05T19:59:13.798457Z	info	sds	resource:default new connection
2020-11-05T19:59:13.798527Z	info	sds	Skipping waiting for gateway secret
2020-11-05T19:59:14.412247Z	info	cache	Root cert has changed, start rotating root cert for SDS clients
2020-11-05T19:59:14.412347Z	info	cache	GenerateSecret default
2020-11-05T19:59:14.412849Z	info	sds	resource:default pushed key/cert pair to proxy
2020-11-05T19:59:14.414760Z	warning	envoy main	there is no configured limit to the number of allowed active connections. Set a limit via the runtime key overload.global_downstream_max_connections
2020-11-05T19:59:16.053243Z	info	Envoy proxy is ready
2020-11-05T20:00:00.734863Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 13, 
2020-11-05T20:00:01.900737Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: local reset
2020-11-05T20:00:03.299764Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: local reset
2020-11-05T20:28:45.248137Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 13, 
2020-11-05T20:57:13.014664Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 13, 
2020-11-05T21:27:03.152377Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 13, 
2020-11-05T21:53:27.065957Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 13, 
2020-11-05T21:53:28.456074Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: local reset
2020-11-05T21:53:30.343998Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: local reset
2020-11-05T22:23:18.602373Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 13, 
2020-11-05T22:54:07.511750Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 13, 
```

```
jenkins@ip-172-31-31-108:~/kubernetes-deployments/saturn.cap.expressplay-pd.net/istio-system/external-dns$ istioctl proxy-status istiod-64855f5d5b-wdbh5   -n istio-system
2020-11-05T18:40:38.427670Z	error	an error occurred forwarding 42433 -> 15000: error forwarding port 15000 to pod 09a0fb2faff5835c6f8cfd6dbc7686f428221685de6cbbd50b3ab1500a551711, uid : exit status 1: 2020/11/05 18:40:38 socat[1185677] E connect(5, AF=2 127.0.0.1:15000, 16): Connection refused

Error: failure running port forward process: Get "http://localhost:42433/config_dump": EOF
```

Below are version for istio, kube and kops and I installed istio with default profile to start with:

```
istioctl version:

client version: 1.7.3
control plane version: 1.7.3
data plane version: 1.7.3 (49 proxies)

kops version:
Version 1.18.1 (git-453d7d96be)

kubectl version:

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

```
installed istio 1.7.3 from curl command using istio doc and then installed ingress gateway by using default configuration steps shown below:

```
istioctl install --set profile=default
istioctl install --set components.telemetry.enabled=true
kubectl label namespace default istio-injection=enabled
kubectl label namespace cap-staging istio-injection=enabled
kubectl label namespace istio-system istio-injection=enabled
kubectl get namespace -L istio-injection
kubectl apply -f base/files

```

1) Added some custom config to ingressgateway to add aws arn in  ingress.yml:

```
---


apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingressgateway
  namespace: istio-system
  labels:
    release: istio
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - "*"
    # Additional ports in gateaway for the ingressPorts - apps using dedicated port instead of hostname
---


apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ingressgateway
  namespace: istio-system
  labels:
    app: istio-ingressgateway
    release: istio
    istio: ingressgateway
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: istio-ingressgateway
      release: istio
      istio: ingressgateway
---


apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  annotations:
    #service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
   # service.beta.kubernetes.io/aws-load-balancer-type alb: "alb"
    service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "True"
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name: "s3-logs-elb-logs-kube-staging"
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-prefix: "saturn"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
  labels:
    app: istio-ingressgateway
    release: istio
    istio: ingressgateway
spec:
  type: LoadBalancer
  selector:
    app: istio-ingressgateway
  ports:
    -
      name: http2
      port: 80
      targetPort: 80
    -
      name: https
      port: 443
    -
      name: http-health
      port: 15021
      targetPort: 15021


---


apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-ingressgateway-service-account
  namespace: istio-system
  labels:
    app: istio-ingressgateway
    release: istio
---

```

2) grpc-ingress.yml:

```
---


apiVersion: v1
kind: Service
metadata:
  name: istio-telemetry
  namespace: istio-system
  labels:
    app: mixer
    istio: mixer
    release: istio
spec:
  ports:
  - name: grpc-mixer
    port: 9091
  - name: grpc-mixer-mtls
    port: 15004
  - name: http-monitoring
    port: 15014
  - name: prometheus
    port: 42422
  selector:
    istio: mixer
    istio-mixer-type: telemetry

---


apiVersion: v1
kind: Service
metadata:
  # Must match the certificate, this is used in the node agent in same namespace.
  name: istio-citadel
  namespace: istio-system
  labels:
    app: security
    istio: citadel
    release: istio

spec:
  ports:
    - name: grpc-citadel
      port: 8060
      targetPort: 8060
      protocol: TCP
    - name: http-monitoring
      port: 15014
  selector:
    app: citadel
---


apiVersion: v1
kind: Service
metadata:
  name: istio-galley
  namespace: istio-system
  labels:
    app: galley
    istio: galley
    release: istio
spec:
  ports:
  - port: 443
    name: https-validation
    targetPort: 9443
  - port: 15014
    name: http-monitoring
  - port: 9901
    name: grpc-mcp
  - port: 15019
    name: grpc-tls-mcp
  selector:
    istio: galley

---


apiVersion: v1
kind: Service
metadata:
  name: istio-pilot
  namespace: istio-system
  labels:
    app: pilot
    release: istio
    istio: pilot
spec:
  ports:
  - port: 15010
    name: grpc-xds # direct
  - port: 15011
    name: https-xds # mTLS
  - port: 8080
    name: http-legacy-discovery # direct
  - port: 15014
    name: http-monitoring
  selector:
    istio: pilot
---
---


apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: istio-policy
  namespace: istio-system
  labels:
    app: istio-policy
    release: istio
spec:
  host: istio-policy.istio-system.svc.cluster.local
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 15004 # grpc-mixer-mtls
      tls:
        mode: ISTIO_MUTUAL
    - port:
        number: 9091 # grpc-mixer
      tls:
        mode: DISABLE
    connectionPool:
      http:
        http2MaxRequests: 10000
        maxRequestsPerConnection: 10000
---



---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: grpc-ingressgateway
  namespace: istio-system
  labels:
    release: istio
    app: grpc-ingressgateway
    istio: grpc-ingressgateway
spec:
  minAvailable: 1
  selector:
    matchLabels:
      release: istio
      app: grpc-ingressgateway
      istio: grpc-ingressgateway
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-ingressgateway
  namespace: istio-system
  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    release: istio
    app: grpc-ingressgateway
    istio: grpc-ingressgateway
spec:
  type: LoadBalancer
  selector:
    release: istio
    app: grpc-ingressgateway
    istio: grpc-ingressgateway
  ports:
    -
      name: http2
    #  nodePort: 31380
      port: 80
      targetPort: 80
    -
      name: https
    #  nodePort: 31390
      port: 443
    -
      name: http-health
      port: 15021
      targetPort: 15021

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-ingressgateway
  namespace: istio-system
  labels:
    release: istio
    app: grpc-ingressgateway
    istio: grpc-ingressgateway

spec:
  selector:
    matchLabels:
      app: grpc-ingressgateway
      istio: grpc-ingressgateway
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grpc-ingressgateway
        chart: gateways
        heritage: Tiller
        istio: grpc-ingressgateway
        release: istio
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      volumes:
        - name: istio-envoy
          emptyDir: {}
        - name: istiod-ca-cert
          configMap:
            name: istio-ca-root-cert
            defaultMode: 420
        - name: podinfo
          downwardAPI:
            items:
              - path: labels
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels
              - path: annotations
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.annotations
            defaultMode: 420
        - name: config-volume
          configMap:
            name: istio
            defaultMode: 420
            optional: true
        - name: ingressgateway-grpc-certs
          secret:
            optional: true
            secretName: istio-grpcingressgateway-certs
        - name: ingressgateway-ca-certs
          secret:
            optional: true
            secretName: istio-ingressgateway-ca-certs
      serviceAccountName: grpc-ingressgateway-service-account
      containers:
        - name: istio-proxy
          image: 'docker.io/istio/proxyv2:1.7.3'
          args:
            - proxy
            - router
            - --domain
            - $(POD_NAMESPACE).svc.cluster.local
            - --proxyLogLevel=warning
            - --proxyComponentLogLevel=misc:error
            - --log_output_level=default:info
            - --drainDuration
            - 45s
            - --parentShutdownDuration
            - 1m0s
            - --connectTimeout
            - 10s
            - --serviceCluster
            - istio-egressgateway
            - --zipkinAddress
            - zipkin.istio-system:9411
            - --proxyAdminPort
            - "15000"
            - --statusPort
            - "15020"
            - --controlPlaneAuthPolicy
            - MUTUAL_TLS
            - --discoveryAddress
            - istio-pilot.istio-system:15012
            - --trust-domain=cluster.local
          ports:
            - containerPort: 15021
            - containerPort: 8080
            - containerPort: 8443
            - containerPort: 31400
            - containerPort: 15090
            - containerPort: 80
            - containerPort: 443
            - containerPort: 853
            - containerPort: 31400
            - containerPort: 15011
            - containerPort: 8060
            - containerPort: 15029
            - containerPort: 15030
            - containerPort: 15031
            - containerPort: 15032
            - containerPort: 15443
            - containerPort: 15020
            - containerPort: 15090
              protocol: TCP
              name: http-envoy-prom


          env:
          - name: SDS_ENABLED
            value: "false"
          - name: JWT_POLICY
            value: first-party-jwt
          - name: PILOT_CERT_PROVIDER
            value: istiod
          - name: CA_ADDR
            value: 'istiod.istio-system.svc:15012'
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: INSTANCE_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: HOST_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          - name: SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          - name: ISTIO_META_POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: ISTIO_META_CONFIG_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: ISTIO_META_WORKLOAD_NAME
            value: grpc-ingressgateway
          - name: ISTIO_META_OWNER
            value: kubernetes://api/apps/v1/namespaces/istio-system/deployments/grpc-ingressgateway
          - name: ISTIO_META_ROUTER_MODE
            value: sni-dnat
          - name: ISTIO_META_MESH_ID
            value: cluster.local
          - name: ISTIO_METAJSON_LABELS
            value: |
              {"app":"grpc-ingressgateway"}
          - name: ISTIO_META_CLUSTER_ID
            value: Kubernetes

          resources:
            limits:
              cpu: '2'
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 40Mi
          volumeMounts:
            - name: config-volume
              mountPath: /etc/istio/config
            - name: istiod-ca-cert
              mountPath: /var/run/secrets/istio
            - name: podinfo
              mountPath: /etc/istio/pod
            - name: ingressgateway-grpc-certs
              mountPath: /etc/istio/ingressgateway-certs
            - name: ingressgateway-ca-certs
              mountPath: /etc/istio/ingressgateway-ca-certs
            - name: istio-envoy
              mountPath: /etc/istio/proxy
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: 15021
              scheme: HTTP
            initialDelaySeconds: 1
            timeoutSeconds: 1
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 30
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: istio-ingressgateway-service-account
      serviceAccount: istio-ingressgateway-service-account
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - ppc64le
                      - s390x
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 2
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
            - weight: 2
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - ppc64le
            - weight: 2
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - s390x
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 100%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600


---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: grpc-ingressgateway
    istio: grpc-ingressgateway
    release: istio
  name: grpc-ingressgateway
  namespace: istio-system
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grpc-ingressgateway
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grpc-ingressgateway-service-account
  namespace: istio-system
  labels:
    app: grpc-ingressgateway
    release: istio
---

```

3) egress.yml:
```
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: istio-multicluster-egressgateway
  namespace: istio-system
  labels:
    app: istio-egressgateway
    release: istio
spec:
  workloadSelector:
    labels:
      istio: egressgateway
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: GATEWAY
        listener:
          portNumber: 15443
          filterChain:
            filter:
              name: "envoy.filters.network.sni_cluster"
      patch:
        operation: MERGE
        value:
          common_http_protocol_options:
            idle_timeout: 30s
          xff_num_trusted_hops: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: istio-egressgateway
    istio: egressgateway
    release: istio
  name: istio-egressgateway
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-egressgateway
      istio: egressgateway
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: istio-egressgateway
        chart: gateways
        heritage: Tiller
        istio: egressgateway
        release: istio
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
            weight: 2
          - preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - ppc64le
            weight: 2
          - preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - s390x
            weight: 2
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
      containers:
      - args:
        - proxy
        - router
        - --domain
        - $(POD_NAMESPACE).svc.cluster.local
        - --proxyLogLevel=warning
        - --proxyComponentLogLevel=misc:error
        - --log_output_level=default:info
        - --drainDuration
        - 45s
        - --parentShutdownDuration
        - 1m0s
        - --connectTimeout
        - 10s
        - --serviceCluster
        - istio-egressgateway
        - --zipkinAddress
        - zipkin.istio-system:9411
        - --proxyAdminPort
        - "15000"
        - --statusPort
        - "15021"
        - --controlPlaneAuthPolicy
        - MUTUAL_TLS
        - --discoveryAddress
        - istio-pilot.istio-system:15012
        - --trust-domain=cluster.local
        env:
          - name: SDS_ENABLED
            value: "false"
          - name: JWT_POLICY
            value: first-party-jwt
          - name: PILOT_CERT_PROVIDER
            value: istiod
          - name: CA_ADDR
            value: 'istiod.istio-system.svc:15012'
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: INSTANCE_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: HOST_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          - name: SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.serviceAccountName
          - name: CANONICAL_SERVICE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: 'metadata.labels[''service.istio.io/canonical-name'']'
          - name: CANONICAL_REVISION
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: 'metadata.labels[''service.istio.io/canonical-revision'']'
          - name: ISTIO_META_WORKLOAD_NAME
            value: istio-ingressgateway
          - name: ISTIO_META_OWNER
            value: >-
              kubernetes://apis/apps/v1/namespaces/istio-system/deployments/istio-ingressgateway
          - name: ISTIO_META_MESH_ID
            value: cluster.local
          - name: ISTIO_META_ROUTER_MODE
            value: sni-dnat
          - name: ISTIO_META_CLUSTER_ID
            value: Kubernetes
        image: docker.io/istio/proxyv2:1.7.3
        imagePullPolicy: IfNotPresent
        name: istio-proxy
        ports:
        - containerPort: 15021
        - containerPort: 8080
        - containerPort: 8443
        - containerPort: 15443
        - containerPort: 15090
        - containerPort: 80
        - containerPort: 443
        - containerPort: 15443
        - containerPort: 15090
          name: http-envoy-prom
          protocol: TCP
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /healthz/ready
            port: 15021
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 10m
            memory: 40Mi
        volumeMounts:
        - mountPath: /etc/istio/egressgateway-certs
          name: egressgateway-certs
          readOnly: true
        - mountPath: /etc/istio/egressgateway-ca-certs
          name: egressgateway-ca-certs
          readOnly: true
        - name: config-volume
          mountPath: /etc/istio/config
        - name: istiod-ca-cert
          mountPath: /var/run/secrets/istio
        - name: podinfo
          mountPath: /etc/istio/pod

      volumes:
      - name: istiod-ca-cert
        configMap:
          name: istio-ca-root-cert
          defaultMode: 420
      - name: podinfo
        downwardAPI:
          items:
            - path: labels
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.labels
            - path: annotations
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations
          defaultMode: 420
      - name: config-volume
        configMap:
          name: istio
          defaultMode: 420
          optional: true
      - name: egressgateway-certs
        secret:
          optional: true
          secretName: istio-egressgateway-certs
      - name: egressgateway-ca-certs
        secret:
          optional: true
          secretName: istio-egressgateway-ca-certs

---

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: istio-egressgateway
  namespace: istio-system
  labels:
    app: istio-egressgateway
    istio: egressgateway
    release: istio
spec:
  minAvailable: 1
  selector:
    matchLabels:
        app: istio-egressgateway
        istio: egressgateway
        release: istio
---


apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-multicluster-egressgateway
  namespace: istio-system
  labels:
    app: istio-egressgateway
    release: istio
spec:
  selector:
    istio: egressgateway
  servers:
  - hosts:
    - "*.global"
    port:
      name: tls
      number: 15443
      protocol: TLS
    tls: {}
---


apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-multicluster-egressgateway
  namespace: istio-system
  labels:
    app: istio-egressgateway
    release: istio
spec:
  gateways:
  - istio-multicluster-egressgateway
  hosts:
  - "*.global"
  tls:
  - match:
    - port: 15443
      sniHosts:
      - "*.global"
    route:
    - destination:
        host: non.existent.cluster
        port:
          number: 15443
      weight: 100

---


apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: istio-multicluster-destinationrule
  namespace: istio-system
  labels:
    app: istio-egressgateway
    release: istio
spec:
  host: "*.global"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---


apiVersion: v1
kind: Service
metadata:
  name: istio-egressgateway
  namespace: istio-system
  annotations:
  labels:
    app: istio-egressgateway
    release: istio
    istio: egressgateway
spec:
  type: ClusterIP
  selector:
    app: istio-egressgateway
  ports:
    -
      name: http2
      port: 80
    -
      name: https
      port: 443
    -
      name: tls
      port: 15443
      targetPort: 15443
```

external dns configuration:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: istio-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
  namespace: istio-system
rules:
- apiGroups: [""]
  resources: ["services","endpoints","pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions","networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
- apiGroups: ["networking.istio.io"]
  resources: ["gateways", "virtualservices"]
  verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: istio-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: istio-system
  labels:
    app: external-dns
spec:
  selector:
    matchLabels:
      app: external-dns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: k8s.gcr.io/external-dns/external-dns:v0.7.3
        args:
        - --source=service
        - --source=ingress
        - --source=istio-gateway
        - --source=istio-virtualservice
        - --annotation-filter=type notin (grpc)
        - --domain-filter=expressplay-npd.net
        - --provider=aws
        - --policy=upsert-only # would prevent ExternalDNS from deleting any records, omit to enable full synchronization
        - --registry=txt
        - --txt-owner-id=saturn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-grpc
  namespace: istio-system
  labels:
    app: external-dns-grpc
spec:
  selector:
    matchLabels:
      app: external-dns-grpc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns-grpc
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: k8s.gcr.io/external-dns/external-dns:v0.7.3
        args:
        - --source=service
        - --source=ingress
        - --source=istio-gateway
        - --source=istio-virtualservice
        - --annotation-filter=type=grpc
        #- --istio-ingress-gateway=istio-system/grpc-ingressgateway
        - --domain-filter=expressplay-npd.net
        - --provider=aws
        - --policy=upsert-only # would prevent ExternalDNS from deleting any records, omit to enable full synchronization
        - --registry=txt
        - --txt-owner-id=saturn-grpc


```

Let me know if am missing anything
