### ISSUE TITLE
Add possibility to define custom labels

### ISSUE THREAD

**Issue by samuel-hopko** [istio/istio#28641]
**Description**
I would like to see a possibility to add custom labels to Istio components when installing via IstioOperator. I would like to have labels unified in all apps running in Kubernetes cluster, but istio is only one which has just its default labels. 

**Use case**
I am installing _prometheus_ an _kiali_ to my cluster. I would like to add there cluster-wide set of labels: 

- app.kubernetes.io/version
- app.kubernetes.io/component
- app.kubernetes.io/part-of

There is no option for that in configuration. Apps provisioned have just default labels from istio:
```
app=kiali,pod-template-hash=586dbcd5fc,release=istio
app=prometheus,pod-template-hash=764b46fbbc,release=istio
```

**Alternatives considered**
Alternative that I tried were overlays. It works as expected, but only on pods that are already running, when bootstraping app from the scratch, it fails. More details can be found in this [thread](https://discuss.istio.io/t/possibility-to-add-custom-labels/8859/3). 

**Example**
```
  addonComponents:
    prometheus:
      enabled: true
      k8s:
        replicaCount: 1
        overlays:
        - apiVersion: apps/v1
          kind: Deployment
          name: prometheus
          patches:
            value: |
              app.kubernetes.io/component: prometheus
          - path: spec.template.metadata.labels
            value: |
              app.kubernetes.io/component: prometheus
```

**Affected product area**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features**

**Comment by zufardhiyaulhaq** [comment]
IIRC this is possible
```
spec:
  components:
    ingressGateways:
        - enabled: true
          name: istio-ingressgateway
          label:
            app: istio-ingressgateway
            istio: ingressgateway
```
