### ISSUE TITLE
Connection between pod and external Kafka works randomly with Istio sidecar enabled

### ISSUE THREAD

**Issue by kzzalews** [istio/istio#28646]
**Bug description**

We're using AWS EKS in which we have installed Istio and running some Kafka consumers. Outside of EKS, in the same VPC, we've installed three Kafka nodes. We've created `Service` (so called headless service), `Endpoints` and `ServiceEntry` K8s objects to expose Kafka into service mesh (see steps to reproduce).

This configuration works flawlessly as long as you create pods with Istio sidecar disabled or with Kafka IPs configured as not handled by Istio.

When Istio sidecar is affecting Kafka connections (Istio sidecar fully enabled) only 1 in 3 connections with Kafka results with data retrieval (we have 3 Kafka nodes, Kafka producer created topic using replication 3). We've tried to set `DestinationRule` to use different load balancing options (e.g. PASSTHROUGH), but it doesn't change situation.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Fully working connection with Kafka

**Steps to reproduce the bug**

Create 3 node Kafka cluster outside K8s cluster. Create below K8s objects.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: lumigu-kafka
spec:
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092
---
apiVersion: v1
kind: Endpoints
metadata:
  name: lumigu-kafka
subsets:
  - addresses:
      - ip: 10.0.1.201
      - ip: 10.0.2.118
      - ip: 10.0.3.182
    ports:
      - port: 9092
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: lumigu-kafka
spec:
  hosts:
    - "lumigu-kafka"
  addresses:
    - 10.0.1.201/32
    - 10.0.2.118/32
    - 10.0.3.182/32
  ports:
    - number: 9092
      name: kafka
      protocol: TCP
  location: MESH_EXTERNAL
  resolution: STATIC
  endpoints:
    - address: 10.0.1.201
    - address: 10.0.2.118
    - address: 10.0.3.182
```

Run `ubuntu` image inside K8s cluster to test Kafka connectivity.
```
# Sidecar enabled - random problems with connectivity
kubectl run kzzalews-shell --rm -i --tty --image ubuntu -- bash

# Sidecar disabled - works great!
kubectl run kzzalews-shell --rm -i --tty --image ubuntu --overrides='{ "apiVersion": "v1", "metadata": {"annotations": { "sidecar.istio.io/inject":"false" } } }' -- bash

# Sidecar disabled for Kafka nodes - works great!
kubectl run kzzalews-shell --rm -i --tty --image ubuntu --overrides='{ "apiVersion": "v1", "metadata": {"annotations": { "traffic.sidecar.istio.io/excludeOutboundIPRanges":"10.0.1.201/32,10.0.2.118/32,10.0.3.182/32" } } }' -- bash
```

To test Kafka, we're using below code (run in `ubuntu` pod):
```
apt update && apt install kafkacat
kafkacat -C -b lumigu-kafka:9092 -t multiBroker -X security.protocol=sasl_plaintext -X sasl.mechanisms=PLAIN -X sasl.username='USER' -X sasl.password='PASSWORD'
```
In case of working Istio sidecar - you'll get data only 1 in 3 attempts.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

```
$ istioctl version --remote
client version: 1.6.0
cluster-local-gateway version:
pilot version: 1.6.12
data plane version: 1.6.12 (13 proxies)
```

```
$ kubectl version --short
Client Version: v1.19.3
Server Version: v1.18.8-eks-7c9bda
```

**How was Istio installed?**

```
cat > manifest.yaml <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
  values:
    meshConfig:
      disablePolicyChecks: false
    prometheus:
      enabled: false
    grafana:
      enabled: false
    kiali:
      enabled: true
    gateways:
      enabled: true
      istio-ingressgateway:
        type: NodePort
EOF
istioctl install -f manifest.yaml
istioctl operator init
```

**Environment where bug was observed (cloud vendor, OS, etc)**

N/A
