### ISSUE TITLE
Improve memory footprint of dynamic route config when handling multiple domains 

### ISSUE THREAD

**Issue by e-zhang** [istio/istio#28659]
**Describe the feature request**

For our use case, we have a single Gateway object that has many domains attached under the `hosts` section of the spec. 

We also have multiple VirtualServices, each with multiple http routes, that are attached to this Gateway. 

An example config would be

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - 'a.35.184.249.94.nip.io'
    - 'b.35.184.249.94.nip.io'
    - 'c.35.184.249.94.nip.io'
    - 'd.35.184.249.94.nip.io'
    - 'e.35.184.249.94.nip.io'
    - 'f.35.184.249.94.nip.io'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: sds-credential
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: a
  namespace: default
spec:
  gateways:
  - gateway
  hosts:
  - '*.35.184.249.94.nip.io'
  http:
  - match:
    - uri:
        exact: /productpage
    route:
    - destination:
        host: productpage
        port:
          number: 9080
  - match:
    - uri:
        exact: /productpage/2
    route:
    - destination:
        host: productpage
        port:
          number: 9080
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: b
  namespace: default
spec:
  gateways:
  - gateway
  hosts:
  - '*.35.184.249.94.nip.io'
  http:
  - match:
    - uri:
        exact: /productpage/3
    route:
    - destination:
        host: productpage
        port:
          number: 9080
  - match:
    - uri:
        exact: /productpage/4
    route:
    - destination:
        host: productpage
        port:
          number: 9080
```

What we've noticed is that the envoy config pushed to the IngressGateway essentially forms the cartesian product between gateway domains and virtualservice routes. The `dynamic_routes_config` creates a single `virtual_host` with 1 domain for each domain and each `virtual_host` contains the full set of `routes`. So going with this example, we would have 6 virtual hosts entries (a, b, c, d, e, f) each with the same 4 routes (productpage, productpage/2, productpage/3, productpage/4). 

What would be ideal, is if the config could be collapsed such that there would only be a single `virtual_host` with all 6 domains listed and the 4 routes part of that single virtual_host. 

In our lab setup, we had ~50 VirtualServices each with ~10 routes and a single Gateway with 150 domain. This led to the proliferation of ~75000 routes on ~150 virtual hosts resulting in ~ 9M lines in the envoy_config and using ~20GB in memory.

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[ ] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

We saw this same behavior in Istio 1.4.x and 1.6.x running in our labs.
