### ISSUE TITLE
Entries are not getting created in route-53 istio 1.7.3 version issue

### ISSUE THREAD

**Issue by akhilgoel09** [istio/istio#28668]
```
Hi Guys,

Need help with the ingressgateway issue i am getting, when installed istio 1.7.3 version and installing default profile using istioctl command for default profiles, entires in the route-53 is not getting created and i can see in the istiod logs below errors:


020-11-06T21:18:03.369530Z\u0009info\u0009ads\u0009Push Status: {
    \"pilot_conflict_outbound_listener_tcp_over_current_tcp\": {
        \"0.0.0.0:3306\": {
            \"proxy\": \"revoked-device-service-69cbd98b55-258b2.cap-staging\",
            \"message\": \"Listener=0.0.0.0:3306 AcceptedTCP=dynamodb.eu-west-2.amazonaws.com RejectedTCP=my.service1.com TCPServices=1\"
        },
        \"0.0.0.0:587\": {
            \"proxy\": \"revoked-device-service-69cbd98b55-258b2.cap-staging\",
            \"message\": \"Listener=0.0.0.0:587 AcceptedTCP=dynamodb.eu-west-1.amazonaws.com RejectedTCP=email-smtp.us-west-2.amazonaws.com TCPServices=1\"
        },
        \"0.0.0.0:9092\": {
            \"proxy\": \"revoked-device-service-69cbd98b55-258b2.cap-staging\",
            \"message\": \"Listener=0.0.0.0:9092 AcceptedTCP=pkc-4kgmg.us-west-2.aws.confluent.cloud RejectedTCP=pkc.us-west-1.aws.confluent.cloud TCPServices=1\"
        }
    },
    \"pilot_duplicate_envoy_clusters\": {
        \"outbound|587||email-smtp.eu-west-1.amazonaws.com\": {
            \"proxy\": \"revoked-device-service-69cbd98b55-258b2.cap-staging\",
            \"message\": \"Duplicate cluster outbound|587||email-smtp.eu-west-2.amazonaws.com found while pushing CDS\"
        },
        \"outbound|587||email-smtp.us-east-1.amazonaws.com\": {
            \"proxy\": \"revoked-device-service-69cbd98b55-258b2.cap-staging\",
            \"message\": \"Duplicate cluster outbound|587||email-smtp.us-east-2.amazonaws.com found while pushing CDS\"
        },
        \"outbound|9092||pkc-4kgmg.us-west-2.aws.confluent.cloud\": {
            \"proxy\": \"revoked-device-service-69cbd98b55-258b2.cap-staging\",
            \"message\": \"Duplicate cluster outbound|9092||pkc.us-west-1.aws.confluent.cloud found while pushing CDS\"
        }
    },
    \"pilot_eds_no_instances\": {
        \"outbound_.80_._.api-service.svc.cluster.local\": {},
        \"outbound|80||api-service.cap-staging.svc.cluster.local\": {}
    }
}`

**Below is my configurations for custom ingressgateway, egressgateway and external dns files:

I have a custom ingress-gateway file to route traffic of to aws elb:**

--- 


apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingressgateway
  namespace: istio-system
  labels:
    release: istio
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - "*"
    # Additional ports in gateaway for the ingressPorts - apps using dedicated port instead of hostname
---


apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ingressgateway
  namespace: istio-system
  labels:
    app: istio-ingressgateway
    release: istio
    istio: ingressgateway
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: istio-ingressgateway
      release: istio
      istio: ingressgateway
---


apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  annotations:
    #service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
   # service.beta.kubernetes.io/aws-load-balancer-type alb: "alb"
    service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "True"
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name: "s3-logs-elb-logs-kube-staging"
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-prefix: "saturn"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
  labels:
    app: istio-ingressgateway
    release: istio
    istio: ingressgateway
spec:
  type: LoadBalancer
  selector:
    app: istio-ingressgateway
  ports:
    -
      name: http2
      port: 80
      targetPort: 8080
    -
      name: https
      port: 443
      targetPort: 8443
    -
      name: status-port
      port: 15021
      targetPort: 15021


---


apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-ingressgateway-service-account
  namespace: istio-system
  labels:
    app: istio-ingressgateway
    release: istio
---

my egress-gateway file:



---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: istio-multicluster-egressgateway
  namespace: istio-system
  labels:
    app: istio-egressgateway
    release: istio
spec:
  workloadSelector:
    labels:
      istio: egressgateway
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: ANY
        listener:
          portNumber: 15443
          filterChain:
            filter:
              name: "envoy.filters.network.sni_cluster"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.lua
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
            inlineCode: |
              function envoy_on_request(handle)
                request_handle:headers():add("foo", "bar")
              end
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: istio-egressgateway
    istio: egressgateway
    release: istio
  name: istio-egressgateway
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-egressgateway
      istio: egressgateway
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: istio-egressgateway
        chart: gateways
        heritage: Tiller
        istio: egressgateway
        release: istio
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
            weight: 2
          - preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - ppc64le
            weight: 2
          - preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - s390x
            weight: 2
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
      containers:
      - args:
        - proxy
        - router
        - --domain
        - $(POD_NAMESPACE).svc.cluster.local
        - --proxyLogLevel=warning
        - --proxyComponentLogLevel=misc:error
        - --log_output_level=default:info
        - --drainDuration
        - 45s
        - --parentShutdownDuration
        - 1m0s
        - --connectTimeout
        - 10s
        - --serviceCluster
        - istio-egressgateway
        - --zipkinAddress
        - zipkin.istio-system:9411
        - --proxyAdminPort
        - "15000"
        - --statusPort
        - "15021"
        - --controlPlaneAuthPolicy
        - MUTUAL_TLS
        - --discoveryAddress
        - istio-pilot.istio-system:15011
        - '--trust-domain=cluster.local'
        env:
          - name: SDS_ENABLED
            value: "false"
          - name: JWT_POLICY
            value: first-party-jwt
          - name: PILOT_CERT_PROVIDER
            value: istiod
          - name: CA_ADDR
            value: 'istiod.istio-system.svc:15012'
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: INSTANCE_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: HOST_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          - name: SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.serviceAccountName
          - name: CANONICAL_SERVICE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: 'metadata.labels[''service.istio.io/canonical-name'']'
          - name: CANONICAL_REVISION
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: 'metadata.labels[''service.istio.io/canonical-revision'']'
          - name: ISTIO_META_WORKLOAD_NAME
            value: istio-ingressgateway
          - name: ISTIO_META_OWNER
            value: >-
              kubernetes://apis/apps/v1/namespaces/istio-system/deployments/istio-ingressgateway
          - name: ISTIO_META_MESH_ID
            value: cluster.local
          - name: ISTIO_META_ROUTER_MODE
            value: sni-dnat
          - name: ISTIO_META_CLUSTER_ID
            value: Kubernetes
        image: docker.io/istio/proxyv2:1.7.3
        imagePullPolicy: IfNotPresent
        name: istio-proxy
        ports:
        - containerPort: 15021
        - containerPort: 8080
        - containerPort: 8443
        - containerPort: 31400
        - containerPort: 15090
        - containerPort: 80
        - containerPort: 443
        - containerPort: 853
        - containerPort: 31400
        - containerPort: 15011
        - containerPort: 15012
        - containerPort: 8060
        - containerPort: 15029
        - containerPort: 15030
        - containerPort: 15031
        - containerPort: 15032
        - containerPort: 15443
        - containerPort: 15020
        - containerPort: 15090
          name: http-envoy-prom
          protocol: TCP
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /healthz/ready
            port: 15021
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 10m
            memory: 40Mi
        volumeMounts:
        - mountPath: /etc/istio/egressgateway-certs
          name: egressgateway-certs
          readOnly: true
        - mountPath: /etc/istio/egressgateway-ca-certs
          name: egressgateway-ca-certs
          readOnly: true
        - name: config-volume
          mountPath: /etc/istio/config
        - name: istiod-ca-cert
          mountPath: /var/run/secrets/istio
        - name: podinfo
          mountPath: /etc/istio/pod

      volumes:
      - name: istiod-ca-cert
        configMap:
          name: istio-ca-root-cert
          defaultMode: 420
      - name: podinfo
        downwardAPI:
          items:
            - path: labels
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.labels
            - path: annotations
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations
          defaultMode: 420
      - name: config-volume
        configMap:
          name: istio
          defaultMode: 420
          optional: true
      - name: egressgateway-certs
        secret:
          optional: true
          secretName: istio-egressgateway-certs
      - name: egressgateway-ca-certs
        secret:
          optional: true
          secretName: istio-egressgateway-ca-certs

---

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: istio-egressgateway
  namespace: istio-system
  labels:
    app: istio-egressgateway
    istio: egressgateway
    release: istio
spec:
  minAvailable: 1
  selector:
    matchLabels:
        app: istio-egressgateway
        istio: egressgateway
        release: istio
---


apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-multicluster-egressgateway
  namespace: istio-system
  labels:
    app: istio-egressgateway
    release: istio
spec:
  selector:
    istio: egressgateway
  servers:
  - hosts:
    - "*.global"
    port:
      name: tls
      number: 15443
      protocol: TLS
    tls: {}
---


apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-multicluster-egressgateway
  namespace: istio-system
  labels:
    app: istio-egressgateway
    release: istio
spec:
  gateways:
  - istio-multicluster-egressgateway
  hosts:
  - "*.global"
  tls:
  - match:
    - port: 15443
      sniHosts:
      - "*.global"
    route:
    - destination:
        host: non.existent.cluster
        port:
          number: 15443
      weight: 100

---


apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: istio-multicluster-destinationrule
  namespace: istio-system
  labels:
    app: istio-egressgateway
    release: istio
spec:
  host: "*.global"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---


apiVersion: v1
kind: Service
metadata:
  name: istio-egressgateway
  namespace: istio-system
  annotations:
  labels:
    app: istio-egressgateway
    release: istio
    istio: egressgateway
spec:
  type: ClusterIP
  selector:
    app: istio-egressgateway
  ports:
    -
      name: http2
      port: 80
      targetPort: 8080
    -
      name: https
      port: 443
      targetPort: 8443


My external dns file:

apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: istio-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
  namespace: istio-system
rules:
- apiGroups: [""]
  resources: ["services","endpoints","pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions","networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
- apiGroups: ["networking.istio.io"]
  resources: ["gateways", "virtualservices"]
  verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: istio-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: istio-system
  labels:
    app: external-dns
spec:
  selector:
    matchLabels:
      app: external-dns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: k8s.gcr.io/external-dns/external-dns:v0.7.3
        args:
        - --source=service
        - --source=ingress
        - --source=istio-gateway
        - --source=istio-virtualservice
        - --annotation-filter=type notin (grpc)
        - --domain-filter=play-npd.net
        - --provider=aws
        - --policy=upsert-only # would prevent ExternalDNS from deleting any records, omit to enable full synchronization
        - --registry=txt
        - --txt-owner-id=saturn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-grpc
  namespace: istio-system
  labels:
    app: external-dns-grpc
spec:
  selector:
    matchLabels:
      app: external-dns-grpc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns-grpc
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: k8s.gcr.io/external-dns/external-dns:v0.7.3
        args:
        - --source=service
        - --source=ingress
        - --source=istio-gateway
        - --source=istio-virtualservice
        - --annotation-filter=type=grpc
        #- --istio-ingress-gateway=istio-system/grpc-ingressgateway
        - --domain-filter=play-npd.net
        - --provider=aws
        - --policy=upsert-only # would prevent ExternalDNS from deleting any records, omit to enable full synchronization
        - --registry=txt
        - --txt-owner-id=saturn-grpc
`

Then i have micro service ingress.yml and service yml file that needs to be expose and create entry in rout-53 dns:

`
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: admin-portal
#  annotations:
#   ingress.kubernetes.io/force-ssl-redirect: "true"
#   kubernetes.io/ingress.class: "istio-gateway"
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - portal.staging.play.com
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTP
    hosts:
    - portal.staging.play.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: admin-portal
spec:
  hosts:
  - "admin-portal.com"
  - "portal.com"
#  - "*"
  gateways:
  - admin-portal
  http:
  - route:
    - destination:
        host: admin-portal
        port:
          number: 8080

`
service.yml file:


kind: Service
apiVersion: v1
metadata:
  name: xyz-portal
  labels:
    app: xyz-portal
spec:
  ports:
  - name: http
    port: 8080
   # targetPort: 8080
  selector:
    app: xyz-portal


let me know what i am missing
```
