### ISSUE TITLE
HTTP traffic through Gateway is blocked between Pods

### ISSUE THREAD

**Issue by irizzant** [istio/istio#28662]
**Bug description**
Hello
I have a cluster with a wildcard Gateway defined as below:
```yaml
kind: Gateway
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: wildcard
  namespace: istio-system
spec:
  servers:
    - hosts:
        - '*.sdbit.gq'
      port:
        name: http
        number: 80
        protocol: HTTP2
      tls:
        httpsRedirect: true
    - hosts:
        - '*.sdbit.gq'
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        credentialName: sdbit-tls
        mode: SIMPLE
  selector:
    istio: ingressgateway

```

Which exposes one web application through the following virtual service and DestinationRule:
```yaml
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: eapglf73
  namespace: eapglf73
spec:
  hosts:
    - webapps73.sdbit.gq
    - mesh
  gateways:
    - istio-system/wildcard
  http:
    - match:
        - port: 58080
      name: jmx-metrics
      route:
        - destination:
            host: eapglf73.eapglf73.svc.cluster.local
            port:
              number: 58080
            subset: v1
    - match:
        - uri:
            prefix: /glf
      name: http
      route:
        - destination:
            host: eapglf73.eapglf73.svc.cluster.local
            port:
              number: 8080
            subset: v1
    - match:
        - uri:
            exact: /
      redirect:
        uri: /webtng
  tcp:
    - match:
        - port: 7600
      route:
        - destination:
            host: eapglf73.eapglf73.svc.cluster.local
            port:
              number: 7600

kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: eapglf73
  namespace: eapglf73
spec:
  host: eapglf73.eapglf73.svc.cluster.local
  trafficPolicy:
    connectionPool:
      http:
        h2UpgradePolicy: UPGRADE
    loadBalancer:
      consistentHash:
        httpCookie:
          name: glf
          ttl: 0s
    portLevelSettings:
      - port:
          number: 58080
        tls:
          mode: DISABLE
      - port:
          number: 7600
        tls:
          mode: DISABLE
    tls:
      mode: ISTIO_MUTUAL
  subsets:
    - labels:
        version: v1
      name: v1

```

The Gateway is using a TLS certificate from LetsEncrypt that is valid.
The problem is that I cannot curl the domain from the web application, this is what I get:
```
$ curl -vLi https://webapps73.sdbit.gq/glf
* Expire in 0 ms for 6 (transfer 0x564c1c660e80)
* Expire in 1 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 1 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 1 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 1 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 1 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 1 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 1 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 1 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 1 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 1 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 1 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 1 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 1 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 1 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 1 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 1 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 1 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 1 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 1 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 1 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 1 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 1 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 0 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 1 ms for 1 (transfer 0x564c1c660e80)
* Expire in 1 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 1 ms for 1 (transfer 0x564c1c660e80)
* Expire in 1 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 1 ms for 1 (transfer 0x564c1c660e80)
* Expire in 1 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 3 ms for 1 (transfer 0x564c1c660e80)
* Expire in 3 ms for 1 (transfer 0x564c1c660e80)
* Expire in 2 ms for 1 (transfer 0x564c1c660e80)
* Expire in 3 ms for 1 (transfer 0x564c1c660e80)
* Expire in 3 ms for 1 (transfer 0x564c1c660e80)
* Expire in 4 ms for 1 (transfer 0x564c1c660e80)
* Expire in 4 ms for 1 (transfer 0x564c1c660e80)
* Expire in 4 ms for 1 (transfer 0x564c1c660e80)
* Expire in 4 ms for 1 (transfer 0x564c1c660e80)
* Expire in 4 ms for 1 (transfer 0x564c1c660e80)
* Expire in 4 ms for 1 (transfer 0x564c1c660e80)
* Expire in 8 ms for 1 (transfer 0x564c1c660e80)
* Expire in 6 ms for 1 (transfer 0x564c1c660e80)
* Expire in 6 ms for 1 (transfer 0x564c1c660e80)
* Expire in 8 ms for 1 (transfer 0x564c1c660e80)
* Expire in 7 ms for 1 (transfer 0x564c1c660e80)
* Expire in 7 ms for 1 (transfer 0x564c1c660e80)
* Expire in 8 ms for 1 (transfer 0x564c1c660e80)
* Expire in 8 ms for 1 (transfer 0x564c1c660e80)
* Expire in 8 ms for 1 (transfer 0x564c1c660e80)
* Expire in 8 ms for 1 (transfer 0x564c1c660e80)
* Expire in 10 ms for 1 (transfer 0x564c1c660e80)
* Expire in 10 ms for 1 (transfer 0x564c1c660e80)
* Expire in 8 ms for 1 (transfer 0x564c1c660e80)
* Expire in 11 ms for 1 (transfer 0x564c1c660e80)
* Expire in 11 ms for 1 (transfer 0x564c1c660e80)
* Expire in 16 ms for 1 (transfer 0x564c1c660e80)
* Expire in 14 ms for 1 (transfer 0x564c1c660e80)
* Expire in 14 ms for 1 (transfer 0x564c1c660e80)
* Expire in 16 ms for 1 (transfer 0x564c1c660e80)
* Expire in 14 ms for 1 (transfer 0x564c1c660e80)
* Expire in 14 ms for 1 (transfer 0x564c1c660e80)
* Expire in 16 ms for 1 (transfer 0x564c1c660e80)
* Expire in 50 ms for 1 (transfer 0x564c1c660e80)
* Expire in 50 ms for 1 (transfer 0x564c1c660e80)
* Expire in 16 ms for 1 (transfer 0x564c1c660e80)
* Expire in 50 ms for 1 (transfer 0x564c1c660e80)
* Expire in 50 ms for 1 (transfer 0x564c1c660e80)
* Expire in 32 ms for 1 (transfer 0x564c1c660e80)
* Expire in 50 ms for 1 (transfer 0x564c1c660e80)
* Expire in 50 ms for 1 (transfer 0x564c1c660e80)
* Expire in 32 ms for 1 (transfer 0x564c1c660e80)
* Expire in 50 ms for 1 (transfer 0x564c1c660e80)
* Expire in 50 ms for 1 (transfer 0x564c1c660e80)
* Expire in 64 ms for 1 (transfer 0x564c1c660e80)
* Expire in 50 ms for 1 (transfer 0x564c1c660e80)
* Expire in 50 ms for 1 (transfer 0x564c1c660e80)
* Expire in 64 ms for 1 (transfer 0x564c1c660e80)
* Expire in 50 ms for 1 (transfer 0x564c1c660e80)
* Expire in 50 ms for 1 (transfer 0x564c1c660e80)
* Expire in 64 ms for 1 (transfer 0x564c1c660e80)
* Expire in 50 ms for 1 (transfer 0x564c1c660e80)
* Expire in 50 ms for 1 (transfer 0x564c1c660e80)
* Expire in 64 ms for 1 (transfer 0x564c1c660e80)
* Expire in 50 ms for 1 (transfer 0x564c1c660e80)
* Expire in 50 ms for 1 (transfer 0x564c1c660e80)
* Expire in 200 ms for 1 (transfer 0x564c1c660e80)
*   Trying 10.118.122.128...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x564c1c660e80)
* Connected to webapps73.sdbit.gq (10.118.122.128) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to webapps73.sdbit.gq:443 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to webapps73.sdbit.gq:443
```
This kind of traffic should be Passthrough and accepted back from Istio ingress gateway.

I also managed to reproduce this behaviour using the bookinfo application.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Being able to perform the curl above

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
```
client version: 1.7.3
control plane version: 1.7.3
data plane version: 1.7.3 (24 proxies)
```
kubectl
```
Client Version: v1.19.0
Server Version: v1.18.9
```
**How was Istio installed?**
I used Istio Operator with the following manifest:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
 name: istiooperator
 namespace: istio-system
spec:
  profile: default
  components:
    pilot:
      enabled: true
      k8s:
        affinity:          
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - istio-ingressgateway
                topologyKey: kubernetes.io/hostname
        replicaCount: 2 # necessario perchè il PodDisruptionBudget è 1
        hpaSpec:
          minReplicas: 2 # necessario perchè il PodDisruptionBudget è 1
    ingressGateways:
    - enabled: true
      k8s:
        service:
          externalTrafficPolicy: Local
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - istio-ingressgateway
                topologyKey: kubernetes.io/hostname
              weight: 100
        replicaCount: 2 # necessario perchè il PodDisruptionBudget è 1
        hpaSpec:
          minReplicas: 2 # necessario perchè il PodDisruptionBudget è 1
      name: istio-ingressgateway
  values:
    sidecarInjectorWebhook:
      rewriteAppHTTPProbe: true # necessario per far funzionare con Istio i liveness e readiness probes
    gateways:
      istio-ingressgateway:
        type: LoadBalancer # corretto se si usa MetalLB
```
**Environment where bug was observed (cloud vendor, OS, etc)**
kubespray latest release on Ubuntu 20.04
