### ISSUE TITLE
Ability to annotate Ingress and Egress gateway service accounts

### ISSUE THREAD

**Issue by cagataygurturk** [istio/istio#28688]
**Describe the feature request**

Istio Operator should have an option to add annotations for gateway service accounts.

This is mainly required to add Workload Identity support to gateways.

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by morvencao** [comment]
I can see the straightforward way to implement this is using advanced k8s overlay:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
    - namespace: istio-system
      name: istio-ingressgateway
      enabled: true
      k8s:
        overlays:
          - kind: ServiceAccount
            name: istio-ingressgateway-service-account
            patches:
              - path: metadata.annotations.kkk
                value: vvv
```

which will generate `istio-ingressgateway-service-account`:
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kkk: vvv
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
  name: istio-ingressgateway-service-account
  namespace: istio-system
---
```

**Comment by cagataygurturk** [comment]
@morvencao this is promising but I have an issue when the annotation name contains dots. The configuration below is ignored by the operator

```
        k8s:
          overlays:
            - kind: ServiceAccount
              name: istio-ingressgateway-service-account
              patches:
                - path: metadata.annotations."iam.gke.io/gcp-service-account"
                  value: SOME_GSA_EMAIL
```

I am not sure whether there is a special syntax for this.

**Comment by morvencao** [comment]
You can escape the dot in the annotation key, for example:
```
        k8s:
          overlays:
            - kind: ServiceAccount
              name: istio-ingressgateway-service-account
              patches:
                - path: metadata.annotations.iam\.gke\.io/gcp-service-account
                  value: SOME_GSA_EMAIL
```
