### ISSUE TITLE
LDAP protocol is not working with mutual TLS and traffic policy ISTIO_MUTUAL

### ISSUE THREAD

**Issue by aalmazanarbs** [istio/istio#28684]
**Bug description**
When a client pod tries to connect to another pod (statefulSet) with LDAP protocol (STARTTLS or SSL) the Istio sidecar is not handling connection properly. The following logs are present in the istio-proxy container of the LDAP server:
[2020-11-07T21:30:46.625Z] "- - -" 0 URX "-" "-" 0 0 0 - "-" "-" "-" "-" "127.0.0.1:1389" inbound|1389|tcp-ldap|ldap.default.svc.cluster.local - 100.113.109.133:1389 100.113.109.132:47908 - -
[2020-11-07T21:30:46.625Z] "- - -" 0 - "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 100.113.109.133:1389 100.113.109.132:47904 - -
[2020-11-07T21:30:46.626Z] "- - -" 0 UF,URX "-" "-" 0 0 0 - "-" "-" "-" "-" "127.0.0.1:1389" inbound|1389|tcp-ldap|ldap.default.svc.cluster.local - 100.113.109.133:1389 100.113.109.132:47906 - -
[2020-11-07T21:30:46.670Z] "- - -" 0 - "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 100.113.109.133:1389 100.113.109.132:47918 - -

In the istio-proxy container that is trying to connect to LDAP the same logs are present.

Is the setup wrong or Istio is not supporting LDAP?

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
If the ldap server is configured with sidecar.istio.io/inject: "false" and 
```
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
spec:
  host: "ldap.default.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: DISABLE
```
client pod can connect to ldap server without any other modification

**Steps to reproduce the bug**
High level configuration:

server
```
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: ldap
spec:
  ports:
    - name: tcp-ldap
      port: 1389
      targetPort: 1389
      protocol: TCP
  clusterIP: None

---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  namespace: default
  name: ldap
spec:
  rules:
    - services: ["ldap.default.svc.cluster.local"]
      constraints:
      - key: "destination.port"
        values: ["1389"]

---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  namespace: default
  name: bind-ldap
spec:
  subjects:
    - properties:
        source.principal: "cluster.local/ns/default/sa/client"
  roleRef:
    kind: ServiceRole
    name: "ldap"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: default
  name: ldap
spec:
  serviceName: ldap
  replicas: 1
  ...
  template:
    ...
    spec:
      containers:
        - name: ldap
          ...
          ports:
            - containerPort: 1389
              name: tcp-ldap
```

client
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: client

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: client
spec:
  replicas: 1
  ...
  template:
    metadata:
      name: am
    ...
    spec:
      serviceAccountName: am
      ...
```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
Istio 1.3
Kubernetes 1.14

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS KOPS
