### ISSUE TITLE
tls listener for sidecar

### ISSUE THREAD

**Issue by sbvitok** [istio/istio#28682]
**Bug description**
TLSRoute of VirtualSevice dose not create tls listener in envoy for mesh gateway.

[x] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Creating TLSRoute in VirtualSevice must create tls listener in envoy for mesh gateway.
How does this happen with ingress and egress gateways.

**Steps to reproduce the bug**

```
meshConfig:
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY
```

```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: siege
  namespace: default
spec:
  workloadSelector:
    labels:
      app: siege
  egress:
  - hosts:
    - ./whoami.default.svc.cluster.local
    - ./ya.ru
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: ya-ru
  namespace: istio-system
spec:
  hosts:
  - ya.ru
  exportTo:
  - '.'
  - 'istio-system'
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-egressgateway
  namespace: istio-system
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 443
      name: tls
      protocol: TLS
    hosts:
    - "*"
    tls:
      mode: PASSTHROUGH
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: siege-ya-ru-routing
  namespace: default
spec:
  hosts:
  - ya.ru
  exportTo:
  - '.'
  - 'istio-system'
  gateways:
  - mesh
  - istio-system/istio-egressgateway
  http:
  - match:
    - port: 80
      gateways:
      - mesh
      sourceLabels:
        app: siege
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
  - match:
    - port: 80
      gateways:
      - istio-system/istio-egressgateway
    route:
    - destination:
        host: ya.ru
        port:
          number: 443
  tls:
  - match:
    - port: 443
      gateways:
      - mesh
      sniHosts:
      - ya.ru
      sourceLabels:
        app: siege
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
  - match:
    - port: 443
      gateways:
      - istio-system/istio-egressgateway
      sniHosts:
      - ya.ru
    route:
    - destination:
        host: ya.ru

```
In this configuration in sidecar config exist http listener but not exist tls listener, why?
If change namespace for ServiceEntry to default, then tls listener exist in envoy sidecar config. But why I need to put ServiceEntry in default namespace for scheme:
app(default) -> sidecar(default) -> egressgateway(istio-system) -> ya-ru-service-entry(istio-system)
HTTPRoute for sidecar works as expected with ServiceEntry in istio-system namespace
TLSRoute for egressgateway also works as expected with ServiceEntry in both namespaces with right exportTo config.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
1.7.3

**How was Istio installed?**
Helm charts

**Environment where bug was observed (cloud vendor, OS, etc)**
CentOS 7 kubernetes 1.18.3
