### ISSUE TITLE
Inject sidecar with resouce limit warn log

### ISSUE THREAD

**Issue by champly** [istio/istio#28696]
When i inject a sidecar with annotation

```yaml
annotations:
  sidecar.istio.io/inject: "true"
  sidecar.istio.io/interceptionMode: "NONE"
  sidecar.istio.io/proxyCPU: "100m"
  sidecar.istio.io/proxyCPULimit: "1"
  sidecar.istio.io/proxyMemory: "128Mi"
  sidecar.istio.io/proxyMemoryLimit: "512Mi"
```

will inject succ. But `istiod` print warn log

```log
2020-11-09T02:01:31.439140Z	warn	Potentially misspelled annotation 'sidecar.istio.io/proxyCPULimit' with value '1' encountered
2020-11-09T02:01:31.439143Z	warn	Potentially misspelled annotation 'sidecar.istio.io/proxyMemoryLimit' with value '512Mi' encountered
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

```shell
$ istioctl version
client version: 1.7.4
control plane version: 1.7.4
```

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
