### ISSUE TITLE
Unable to set serviceAnnotations using Istio operator 

### ISSUE THREAD

**Issue by Coder63** [istio/istio#28695]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
I'm unable to set ingressGateway to use internal loadbalancer using istio operator 

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**
1) Deploy private GKE  cluster 
2) Install Istio operator 1.7.4
3) Try installing Istio control plane with default profile and set ingress gateway service annotations to use internal loadbalancer.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

Istioctl version 1.7.4
kubectl version
client v1.18.8
server v1.16.13-gke.401

**How was Istio installed?**
Via Operator 

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE 

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

```apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-control-plane
  namespace: istio-system
spec:
  profile: default
    components:
      ingressGateways:
        k8s:
          serviceAnnotation:
            cloud.google.com/load-balancer-type: Internal ```

**Comment by morvencao** [comment]
There are quite problems with your IstioOperator CR:
1. `components` is same level field with `profile`
2. the content of `ingressGateways` can slice, not object
3. `serviceAnnotation` should be `serviceAnnotations`

The correct IstioOperator CR should be:
```
kind: IstioOperator
metadata:
  name: istio-control-plane
  namespace: istio-system
spec:
  profile: default
  components:
    ingressGateways:
    - name: istio-ingressgateway
      k8s:
        serviceAnnotations:
          cloud.google.com/load-balancer-type: Internal
```
