### ISSUE TITLE
Unable to route application traffic on mesh gateway with port other than 80

### ISSUE THREAD

**Issue by kunalekawde** [istio/istio#28709]
**Bug description**
I'm not sure if this is bug but posting it here as I'm not able to get through this.
Posted the scenario and observation here: https://discuss.istio.io/t/egress-traffic-to-multiple-ports-on-same-server/8711/3

Briefly, the case is, if traffic has to steered from application --> istio-proxy(sidecar) --> egress --> out, where application wishes to address to different port other than 80.

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-hook-to-egress-gateway-vs
  namespace: tra-ns
spec:
  exportTo:
  - .
  gateways:
  - mesh
  hosts:
  - 10.15.25.235
  http:
  - headers:
      request:
        set:
          host: hook.1avf0jr.com
          x-forwarded-port: "80"
    match:
    - port: 9910
    route:
    - destination:
        host: istio-egressgateway.tra-ns.svc.cluster.local
        port:
          number: 80
        subset: 1avf0jr-com

```
So, application could try, curl http://10.15.25.235:9910

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Traffic is routed from local istio-proxy to egress.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
client version: 1.4.2
control plane version: 1.4.2
data plane version: 1.4.2 (21 proxies)

kubectl version --short
Client Version: v1.18.3
Server Version: v1.18.3

**How was Istio installed?**
helm

**Environment where bug was observed (cloud vendor, OS, etc)**
K8 cluster using openstack VM's
