### ISSUE TITLE
Istio Operator Reconciliation causes downtime

### ISSUE THREAD

**Issue by jaronoff97** [istio/istio#28707]
**Bug description**
We manage our istio configuration through the istio operator on istio 1.6.4, and recently we've seen that on pod eviction or a restart, our operator (as expected) begins the reconciliation loop. Once it begins the loop, it finds MANY diffs between the current and desired states – even though we haven't updated our IstioOperator configuration between the restarts. We see these logs from our istio operator, right before our ingress gateway began throwing 5XXs

```
2020-11-08 21:36:18 | 2020-11-09T02:36:18.693370Z	info	installer	The following objects differ between generated manifest and cache:
-- | --
  |   | 2020-11-08 21:36:18 | - HorizontalPodAutoscaler:istio-system:external-ingressgateway
  |   | 2020-11-08 21:36:18 | - Deployment:istio-system:external-ingressgateway
  |   | 2020-11-08 21:36:18 | - PodDisruptionBudget:istio-system:external-ingressgateway
  |   | 2020-11-08 21:36:18 | - Role:istio-system:external-ingressgateway-sds
  |   | 2020-11-08 21:36:18 | - RoleBinding:istio-system:external-ingressgateway-sds
  |   | 2020-11-08 21:36:18 | - Service:istio-system:external-ingressgateway
  |   | 2020-11-08 21:36:18 | - ServiceAccount:istio-system:external-ingressgateway-service-account
```

![Screen Shot 2020-11-09 at 10 57 43 AM](https://user-images.githubusercontent.com/10070047/98564473-6b827b80-227a-11eb-8ea4-12dd5fe889be.png)

We have also tested this in our QA environment and saw the same behavior.

![Screen Shot 2020-11-09 at 11 54 24 AM](https://user-images.githubusercontent.com/10070047/98571248-57db1300-2282-11eb-8778-91f6cd82ed41.png)

[ ] Docs
[X] Installation
[ ] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Istio reconciliation shouldn't cause downtime and shouldn't be finding a diff without state change.

**Steps to reproduce the bug**

1. Install istio via the istiooperator with a custom ingressgateway
ex:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: drift-istiocontrolplane
spec:
  profile: default
  meshConfig:
    accessLogFile: "/dev/stdout"
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: false
      - enabled: true
        namespace: istio-system
        name: external-ingressgateway
        label:
          app: external-ingressgateway
          istio: external-ingressgateway
        k8s:
          env:
          - name: ISTIO_META_ROUTER_MODE
            value: sni-dnat
          hpaSpec:
            maxReplicas: 50
            metrics:
            - resource:
                name: cpu
                targetAverageUtilization: 50
              type: Resource
            minReplicas: 12
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: external-ingressgateway
          resources:
            limits:
              cpu: 6000m
              memory: 1024Mi
            requests:
              cpu: 1000m
              memory: 1024Mi
          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-ssl-cert: XXXXXXXXXXXXXXXXXXXXXXXXXXX
            service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS-1-2-2017-01
            service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
            service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
            service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
            service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
            service.beta.kubernetes.io/aws-load-balancer-type: nlb
          service:
            ports:
            - name: https
              port: 443
            - name: http
              port: 80
            externalTrafficPolicy: Local
          strategy:
            rollingUpdate:
              maxSurge: 100%
              maxUnavailable: 0%
```
2. restart the istio operator
3. 5XXs are generated from the ingressgateway 

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
```
⫸ istioctl version --remote
client version: 1.6.4
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
external-ingressgateway version:
internal-ingressgateway version:
internal-ingressgateway version:
pilot version: 1.6.4
data plane version: 1.6.4 (64 proxies)
```
```
⫸ kubectl version --short
Client Version: v1.15.11
Server Version: v1.16.13-eks-2ba888
```

**How was Istio installed?**

via the istio operator

**Environment where bug was observed (cloud vendor, OS, etc)**

EKS 1.16
