### ISSUE TITLE
ServiceEntry cannot select Pod in other clusters

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#28715]
**Bug description**

Given two (primary) clusters, a Pod in each cluster labeled `app: helloworld`, and a ServiceEntry like this in each cluster:

```yaml
kind: ServiceEntry
metadata:
  name: cluster-select-se
spec:
  resolution: STATIC
  location: MESH_INTERNAL
  hosts:
  - helloworld.multicluster
  ports:
  - number: 5000
    name: https
    protocol: TLS
  workloadSelector:
    labels:
      app: helloworld
```

A `sleep` pod in each cluster only has endpoints for the `helloworld` Pod in the local cluster. The same behavior can be expected in a primary-remote scenario. 

We only setup the WorkloadHandler on the "primary" k8s registry:

https://github.com/istio/istio/blob/89850ae760e3fefb80955b3318a0d41b633dd09f/pilot/pkg/bootstrap/servicecontroller.go#L62-L65

but do not create this coupling for multi-cluster registries: 

https://github.com/istio/istio/blob/89850ae760e3fefb80955b3318a0d41b633dd09f/pilot/pkg/serviceregistry/kube/controller/multicluster.go#L128-L132

A WIP PR: #28538 (also have a local-only branch that puts this into the aggregate serviceregistry)

**Expected behavior**

`workloadSelector` selects Pods from all clusters.

**Steps to reproduce the bug**

1.8-alpha.9bf204e92d

**How was Istio installed?**

Following latest 1.8 multicluster guide. 

**Environment where bug was observed (cloud vendor, OS, etc)**
 
GKE
