### ISSUE TITLE
[Istio 1.2] Setting global.proxy.accessLogFormat seems to disable access logs

### ISSUE THREAD

**Issue by drmaciej** [istio/istio#28731]
**Bug description**
I do realise I'm on a very old Istio version, and I am in the process of upgrading, but I can't just flick to latest right away. As a result, I'm hoping to get this to work on 1.2.5. It's entirely possible it's not a bug, but my misuse.

By default, I deploy my Istio with 
```
global:
  proxy:
    accessLogFile: /dev/stdout
```
in values.yaml.

To change the log format, I would do something like `helm template ./istio-1.2.5/install/kubernetes/helm/istio --namespace=istio-system -x templates/configmap.yaml --set global.proxy.accessLogFile="/dev/stdout" --set global.proxy.accessLogFormat='[%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%"' | k replace -f -`. 

I can confirm this propagates into Envoy by using `istioctl dashboard envoy` and looking at `envoy.http_connection_manager` in the config dump. I can also see Pilot's logs say `mesh configuration updated to:` with the right config there.

When this is done, there are no access logs at all.

When I restore the default via `helm template ./istio-1.2.5/install/kubernetes/helm/istio --namespace=istio-system -x templates/configmap.yaml --set global.proxy.accessLogFile="/dev/stdout" --set global.proxy.accessLogFormat='' | k replace -f -`, I can see the default log format in Envoy's config dump. Logs work again.

When I explicitly set the default log format with `--set`, I can see it set in config dump - and it's identical to what I see when I set the log format with an empty string. This, again, results in no logs at all.

I tried to use some additional flags and would get `RPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) 10.34.131.34_8080: Not supported field in StreamInfo: DOWNSTREAM_LOCAL_PORT` when Envoy tries to log.

To summarise - only setting `accessLogFormat` to `''` results in logs. Whenever I set them to anything else, I no longer get logs.

All I really want to do is add some internal headers we use to Envoy's logs. Is there a different way to do this?

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Envoy logs printed using the requested access format.

**Steps to reproduce the bug**
```
helm template ./istio-1.2.5/install/kubernetes/helm/istio --namespace=istio-system -x templates/configmap.yaml --set global.proxy.accessLogFile="/dev/stdout" --set global.proxy.accessLogFormat='[%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% "%DYNAMIC_METADATA(istio.mixer:status)%" "%UPSTREAM_TRANSPORT_FAILURE_REASON%" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% ' | k replace -f -
```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
Istio: 1.2.5
k8s: 1.15.11 (EKS)
Helm: 2.13.1

**How was Istio installed?**
With Helm, using istio-init & istio charts.

**Environment where bug was observed (cloud vendor, OS, etc)**
EKS, OS is Amazon Linux 2.

**Comment by howardjohn** [comment]
I strongly suspect you are missing a newline at the end of the logs, causing envoy to buffer it all up into one massive line which may never actually get logged if nothing triggers a newline

Source: I made the same mistake 10 minutes ago :slightly_smiling_face:

**Comment by maciejqantas** [comment]
@howardjohn 
you are very correct, I am missing it :)

I can't see it in the default config format under http://localhost:15000/config_dump though, which is why I never included it in my config.

https://discuss.istio.io/t/access-log-format/669/4 also points to a similar issue, which I found thanks to your input.

I'll give it a go and see what happens. Thanks heaps!

**Comment by howardjohn** [comment]
@istio/wg-policies-and-telemetry-maintainers can/should we validate this? or transparently add a newline? I cannot imagine anyone *not* wanting a newline

**Comment by douglas-reid** [comment]
This feels like the kind of thing that we should validate (or auto-correct), as it leads to mysterious behavior. I feel like I saw an Envoy issue about this recently -- and I thought it was going to be handled better there. But now I can't find it .

**Comment by maciejqantas** [comment]
@douglas-reid I've just seen this: https://github.com/envoyproxy/envoy/pull/5755

I was able to get it to work with manual updates of the ConfigMap, but that's obviously not ideal.

Because of https://github.com/helm/helm/issues/4030 I was not able to get this to work with `--set`, so I just used `helm template ./istio-1.2.5/install/kubernetes/helm/istio --namespace=istio-system -x templates/configmap.yaml --values istio/values.yaml | k replace -f -`  instead. In my values file, I have

```
global:
  proxy:
    accessLogFile: /dev/stdout
    accessLogFormat: "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% \"%DYNAMIC_METADATA(istio.mixer:status)%\" \"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% \"c:%REQ(custom-header)%\" \n"
``` 

This does the trick, I now get access logs in my desired form.
