### ISSUE TITLE
how to enable access logging by service?

### ISSUE THREAD

**Issue by vjoke** [istio/istio#28744]
**Describe the feature request**
Want to have the ability to enable access logging by service, instead of using meshConfig. accessLogFile

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by AEGQ** [comment]
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: access-log # change  me
  namespace: default # change  me
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: ANY
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
    patch:
      operation: MERGE
      value:
        typed_config:
          '@type': type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          access_log:
          - config:
              format: |
                [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% "%UPSTREAM_TRANSPORT_FAILURE_REASON%" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%
              path: /dev/stdout
            name: envoy.file_access_log
  workloadSelector:
    labels:
      app: whoami  # change  me
```

```
Client                                    Server                                    Format

[2020-10-01T12:39:50.861Z]                [2020-10-01T12:28:26.011Z]                [%START_TIME%]                            
"GET                                      "GET                                      \"%REQ(:METHOD)%
/                                         /                                         %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% 
HTTP/1.1"                                 HTTP/1.1"                                 %PROTOCOL%\"
200                                       200                                       %RESPONSE_CODE% 
-                                         -                                         %RESPONSE_FLAGS% 
"-"                                       "-"                                       \"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" 
0                                         0                                         %BYTES_RECEIVED% 
403                                       403                                       %BYTES_SENT% 
2                                         0                                         %DURATION% 
1                                         0                                         %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% 
"-"                                       "-"                                       \"%REQ(X-FORWARDED-FOR)%\"
"curl/7.72.0-DEV"                         "curl/7.72.0-DEV"                         \"%REQ(USER-AGENT)%\" 
"1e18430c-1f58-4e24-809b-a0d55a177d23"    "01e99f93-f08b-4d22-98cd-e45c8ecb6ca2"    \"%REQ(X-REQUEST-ID)%\" 
"whoami"                                  "whoami"                                  \"%REQ(:AUTHORITY)%\" 
"172.31.10.15:80"                         "172.31.10.15:80"                         \"%UPSTREAM_HOST%\"
PassthroughCluster                        InboundPassthroughClusterIpv4             %UPSTREAM_CLUSTER% 
172.31.18.184:44720                       127.0.0.6:49453                           %UPSTREAM_LOCAL_ADDRESS% 
172.31.10.15:80                           172.31.10.15:80                           %DOWNSTREAM_LOCAL_ADDRESS% 
172.31.18.184:48346                       172.31.18.184:44704                       %DOWNSTREAM_REMOTE_ADDRESS% 
-                                         -                                         %REQUESTED_SERVER_NAME% 
allow_any                                 default                                   %ROUTE_NAME%\n
```

**OR** 

```
curl -XPOST localhost:15000/logging?level=debug
```

@vjoke have a try ... :)
