### ISSUE TITLE
No Expected Outlier Actions

### ISSUE THREAD

**Issue by hairongGao** [istio/istio#28746]
**Bug description**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
outliers ejected from pool
**Steps to reproduce the bug**

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: recommendation 
spec:
  hosts:
    - recommendation 
    - "recommendation-demo.com"
  gateways:
    - istio-system/monitoring-gateway
  http:
  - name: "v2-route"
    route:
    - destination:
        host: recommendation
        subset: v2
      weight: 100
    - destination:
        host: recommendation
        subset: v1
      weight: 0
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: recomm-dr
spec:
  host: recommendation
  trafficPolicy:
    outlierDetection:
      consecutiveErrors: 2 
      interval: 30s
      baseEjectionTime: 30s
      maxEjectionPercent: 50
  subsets:
  - name: v2
    labels:
      version: v2
  - name: v1
    labels:
      version: v1

```
I have 6 pods in the same zone in recommendation svc and I manually turn one of them to return 503.Then I  curl
kubectl exec -it  $CLIENT_POD   -c istio-proxy  -- sh -c 'while true; do curl -L recommendation-demo.com; sleep 1; done'
All requests success (I though I would got two 503 errors and then the unhealth pod got ejected,and see 503 errors after 30 seconds)
kubectl exec -it -n micro $CLIENT_POD  -c istio-proxy  -- pilot-agent request GET stats  | grep v2 | grep outlier
```
cluster.outbound|8080|v2|recommendation.micro.svc.cluster.local.outlier_detection.ejections_active: 0
cluster.outbound|8080|v2|recommendation.micro.svc.cluster.local.outlier_detection.ejections_consecutive_5xx: 0
cluster.outbound|8080|v2|recommendation.micro.svc.cluster.local.outlier_detection.ejections_detected_consecutive_5xx: 0
cluster.outbound|8080|v2|recommendation.micro.svc.cluster.local.outlier_detection.ejections_detected_consecutive_gateway_failure: 0
cluster.outbound|8080|v2|recommendation.micro.svc.cluster.local.outlier_detection.ejections_detected_consecutive_local_origin_failure: 0
cluster.outbound|8080|v2|recommendation.micro.svc.cluster.local.outlier_detection.ejections_detected_failure_percentage: 0
cluster.outbound|8080|v2|recommendation.micro.svc.cluster.local.outlier_detection.ejections_detected_local_origin_failure_percentage: 0
cluster.outbound|8080|v2|recommendation.micro.svc.cluster.local.outlier_detection.ejections_detected_local_origin_success_rate: 0
cluster.outbound|8080|v2|recommendation.micro.svc.cluster.local.outlier_detection.ejections_detected_success_rate: 0
cluster.outbound|8080|v2|recommendation.micro.svc.cluster.local.outlier_detection.ejections_enforced_consecutive_5xx: 0
cluster.outbound|8080|v2|recommendation.micro.svc.cluster.local.outlier_detection.ejections_enforced_consecutive_gateway_failure: 0
cluster.outbound|8080|v2|recommendation.micro.svc.cluster.local.outlier_detection.ejections_enforced_consecutive_local_origin_failure: 0
cluster.outbound|8080|v2|recommendation.micro.svc.cluster.local.outlier_detection.ejections_enforced_failure_percentage: 0
cluster.outbound|8080|v2|recommendation.micro.svc.cluster.local.outlier_detection.ejections_enforced_local_origin_failure_percentage: 0
cluster.outbound|8080|v2|recommendation.micro.svc.cluster.local.outlier_detection.ejections_enforced_local_origin_success_rate: 0
cluster.outbound|8080|v2|recommendation.micro.svc.cluster.local.outlier_detection.ejections_enforced_success_rate: 0
cluster.outbound|8080|v2|recommendation.micro.svc.cluster.local.outlier_detection.ejections_enforced_total: 0
cluster.outbound|8080|v2|recommendation.micro.svc.cluster.local.outlier_detection.ejections_overflow: 0
cluster.outbound|8080|v2|recommendation.micro.svc.cluster.local.outlier_detection.ejections_success_rate: 0
cluster.outbound|8080|v2|recommendation.micro.svc.cluster.local.outlier_detection.ejections_total: 0

```
So I'm confused whether my outlier config is taking effect . If they dont why I can't see any errors , but if they do ,why there's no records ?
**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
stioctl version --remote
client version: 1.7.4
control plane version: 1.7.4
data plane version: 1.7.4 (16 proxies)

kubectl version --short
Client Version: v1.19.3
Server Version: v1.18.8-eks-7c9bda
**How was Istio installed?**
istioctl
**Environment where bug was observed (cloud vendor, OS, etc)**
EKS
