### ISSUE TITLE
PDB maxUnavailable field cannot be set in Istio operator

### ISSUE THREAD

**Issue by sidprak** [istio/istio#28748]
Currently, it looks like there is no way to set the maxUnavailable field in the PDB for istiod, ingress gateway or egress gateway. The Istio Operator spec allows this setting:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
  namespace: istio-operator
spec:
  components:
    pilot:
        k8s:
          podDisruptionBudget:
            maxUnavailable: 1
```

However, in practice, this results in an error:
```
2020-11-10T15:28:46.939281Z	error	installer	PodDisruptionBudget.policy "istio-ingressgateway" is invalid: spec: Invalid value: policy.PodDisruptionBudgetSpec{MinAvailable:(*intstr.IntOrString)(0xc01e820180), Selector:(*v1.LabelSelector)(0xc01e8201a0), MaxUnavailable:(*intstr.IntOrString)(0xc01e8201c0)}: minAvailable and maxUnavailable cannot be both set
```

There doesn't seem to be a way to unset minAvailable so that we can set maxUnavailable.

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

I would expect to be able to set maxUnavailable in the operator spec and/or to have a way to unset minAvailable.

**Steps to reproduce the bug**

Apply the yaml above.

**Version**

```
client version: 1.7.2
control plane version: 1.7.2
data plane version: 1.7.2 (73 proxies)
```

kubectl:
```
Client Version: v1.19.3
Server Version: v1.16.13-eks-2ba888
```

**How was Istio installed?**

Using Istio operator.

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS EKS, Amazon Linux 2.

**Comment by carolynhu** [comment]
@sidprak the error is clear:`minAvailable and maxUnavailable cannot be both set`, you need to unset minAvailable to get maxUnavailable work

**Comment by sidprak** [comment]
@carolynhu thanks for the quick reply. The problem is, I haven't set `minAvailable` in my configuration. The operator seems to default it to 1 and I don't know of a way to unset it.

**Comment by sidprak** [comment]
Thank you!

**Comment by carolynhu** [comment]
hi @sidprak there is not way to unset value through overlay. For minAvaiiable, please don't install HPAs. Otherwise, if you installed HPA, the default value for minAvailable will always be 1 even if you do not set it.

**Comment by morvencao** [comment]
@sidprak A possible solution would be using the advanced k8s overlay:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
  namespace: istio-operator
spec:
  components:
    pilot:
      k8s:
        overlays:
        - kind: PodDisruptionBudget
          name: istiod
          patches:
          - path: spec.minAvailable
          - path: spec.maxUnavailable
            value: 1
```
