### ISSUE TITLE
K8s overlays implicitly change defaults

### ISSUE THREAD

**Issue by therealmitchconnors** [istio/istio#28763]
**Bug description**
Using the components.IngressGateways.K8s section of the operator file causes the minReplicas to be implicitly set to 1.

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
minReplicas stays at the default, 2.

**Steps to reproduce the bug**
```
istioctl install -f -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: default-istio-operator
spec:
  profile: default
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
      k8s:
        service:
          type: NodePort
          ports:
          - name: status-port
            nodePort: 31223
            port: 15021
            protocol: TCP
            targetPort: 15021
          - nodePort: 32659
            port: 80
            targetPort: 8080
            name: http2
          - port: 443
            targetPort: 8443
            name: https
          - port: 15012
            targetPort: 15012
            name: tcp-istiod
          - port: 15443
            targetPort: 15443
            name: tls
EOF
```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
Observed on 1.6, probably affects all versions with operator support

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE
