### ISSUE TITLE
Not able to direct TCP traffic via an egress gateway

### ISSUE THREAD

**Issue by ganeshp79** [istio/istio#28777]
**Bug description**

I have not been able to direct TCP traffic via an egress gateway. I need to access a sftp server via an egress gateway. I use the below configuration but I do not see the traffic reaching the egress gateway ( seen via egress logs ). I'm able to direct HTTP and HTTPS traffic successfully ( cnn example in ISTIO docs ).

```
Istio Version
1.7.4

Test Setup
Docker Desktop on Windows with Kubernetes

Installation Options
istioctl install --set profile=minimal --set meshConfig.outboundTrafficPolicy.mode=REGISTRY_ONLY --set meshConfig.accessLogFile="/dev/stdout" --set values.gateways.istio-egressgateway.enabled=true --set values.gateways.istio-egressgateway.runAsRoot=true

Service Entry
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: all-sftp
spec:
  hosts:
  - test.rebex.net
  addresses:
  - 195.144.107.198/32
  location: MESH_EXTERNAL
  ports:
  - number: 22
    name: tcp
    protocol: TCP
  resolution: NONE
EOF

Egress Configuration
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 22
      name: tcp
      protocol: TCP
    hosts:
    - test.rebex.net
EOF

Destination Rule:
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-all
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: all-egress
EOF

Virtual Service
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-sftp-through-egress-gateway
spec:
  hosts:
  - test.rebex.net
  gateways:
  - mesh
  - istio-egressgateway
  tcp:
  - match:
    - gateways:
      - mesh
      destinationSubnets:
      - 195.144.107.198/32
      port: 22
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: all-egress
        port:
          number: 22
  - match:
    - gateways:
      - istio-egressgateway
      port: 22
    route:
    - destination:
        host: test.rebex.net
        port:
          number: 22
      weight: 100
EOF

```

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
TCP traffic from pods reach the egress gateway 

**Steps to reproduce the bug**
1. Apply the above configuration
2. From a pod start a sftp session - sftp demo@test.rebex.net
3. Check Egress gateway logs 
4. Traffic not shown as received at the egress gateway

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
ganesh@DESKTOP-ADF35B1:~/istio/istio-1.7.4$ istioctl version --remote
client version: 1.7.4
control plane version: 1.7.4
data plane version: 1.7.4 (2 proxies)

ganesh@DESKTOP-ADF35B1:~/istio/istio-1.7.4$ kubectl version --short
Client Version: v1.19.3
Server Version: v1.19.3

**How was Istio installed?**
$ curl -L https://istio.io/downloadIstio | sh -

**Environment where bug was observed (cloud vendor, OS, etc)**
Docker Desktop on Windows

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive
by attaching the dump file to this issue.
[istio-dump.tar.gz](https://github.com/istio/istio/files/5521855/istio-dump.tar.gz)
)

**Comment by ganeshp79** [comment]
Please ignore...
Got it working using Istio Operator to open the port on the egress gateway.

**Comment by framled** [comment]
Hi @ganeshp79 I'm trying to do the same thing, would you mind help me with this?

this is my setup.
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  labels:
  name: external-sftp
  namespace: default
spec:
  hosts:
  - external.sftp.acc
  addresses:
  - x.y.z.w/32
  location: MESH_EXTERNAL
  ports:
  - name: sftp
    number: 22
    protocol: TCP
  resolution: STATIC
  endpoints:
  - address: x.y.z.w
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: external-sftp
spec:
  host: external.sftp.acc
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: egressgateway
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
    - name: sftp-external
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: direct-sftp-throught-egressgateway
spec:
  hosts:
  - external.sftp.acc
  gateways:
  - mesh
  - istio-egressgateway
  tcp:
  - match:
    - destinationSubnets:
      - x.y.z.w
      port: 22
      gateways:
        - mesh
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: sftp-external
        port:
          number: 22
  - match:
    - port: 22
      gateways:
      - istio-egressgateway
    route:
    - destination:
        host: external.sftp.acc
        port:
          number: 22
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: sftp-egressgateway
  namespace: default
spec:
  selector:
    istio: egressgateway
  servers:
  - hosts:
    - external.sftp.acc
    port:
      name: sftp
      number: 22
      protocol: TCP
  
```

and my egress gateway is open port 22.
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: default-istio-control-plane
spec:
  profile: default
  meshConfig:
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
    accessLogFile: /dev/stdout
  components:
    egressGateways:
      - enabled: true
        name: istio-egressgateway
        k8s:
          service:
            ports:
              - name: sftp
                port: 22
                targetPort: 22
```

istio Versión: 1.7.4
