### ISSUE TITLE
First class domain as a host in VS spec

### ISSUE THREAD

**Issue by papovyr** [istio/istio#28782]
Hi,

I have application which one is making HTTP request but it has Host header hardcoded to influx (curl -H 'Host: influx' .....)

Im trying to create VirtualService which will have host set to influx.

However if i set hosts to influx it will not work as it will try to refer to influx.<namespace>.svc.cluster.local (see code bellow)

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: myvs
spec:
  hosts:
  - "influx"
.....
```
I also tried code bellow didn't work (DNS FQDN style)
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: myvs
spec:
  hosts:
  - "influx."
.....
```

and this config works
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: myvs
spec:
  hosts:
  - "*"
.....
```

Should FQDN be supported to allow target first class domains?
