### ISSUE TITLE
use istioctl setup istio-gateway can not update pod securityContext

### ISSUE THREAD

**Issue by zhengqisong** [istio/istio#28783]
**Bug description**
use istioctl upgrade istio-1.7.4, change istio-gateway can not update pods securityContext.

[ ] Installation
[ ] Upgrade
deployment set managedFields  can not update pod securityContext
first install IstioOperator
```
 ingressGateways:
    - enabled: false
      name: 'istio-ingressgateway'
      namespace: 'istio-system'
    - enabled: true
      name: 'gwt-sy-in'
      namespace: 'gateway-system'
      label:
        gw: 'gwt-in'
      k8s:
        service:
```
second upgrade IstioOperator
```
 ingressGateways:
    - enabled: false
      name: 'istio-ingressgateway'
      namespace: 'istio-system'
    - enabled: true
      name: 'gwt-sy-in'
      namespace: 'gateway-system'
      label:
        gw: 'gwt-in'
      k8s:
        securityContext:
          runAsNonRoot: false
        service:
```

[ ] Multi Cluster
[ ] Multi Control Plane
