### ISSUE TITLE
Plaintext Endpoints via PeerAuthentication aren't filtered out in multi-network

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#28798]
We filter out non-tls endpoints from cross-network LoadBalancing. Without TLS we don't have SNI, required to do routing at the gateway. 

https://github.com/istio/istio/blob/86b87f2f923c62344a1887b47adbc69bd6c2ddaa/pilot/pkg/xds/ep_filters.go#L79-L82

As part of #28621 and #28720 we're seeing the test apply the following `PeerAuthentication`s, but the unreachable endpoints aren't being removed from the LoadBalancing rotation. 

<details>

<summary>Global mtls disable</summary>

```
# mTLS is disabled without destination rule.
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
  annotations:
    test-suite: "beta-mtls-off"
spec:
  mtls:
    mode: DISABLE
```

</details>

<details>

<summary>Port level mtls disable</summary>

```
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "mtls"
spec:
  selector:
    matchLabels:
      app: server
  mtls:
    mode: STRICT
  portLevelMtls:
    8090:
      mode: DISABLE
    8092:
      mode: DISABLE
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: server
spec:
  host: server.%s.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    portLevelSettings:
    - port:
        number: 8090
      tls:
        mode: DISABLE
    - port:
        number: 8092
      tls:
        mode: DISABLE
```

</details>

Does the PeerAuthentication set the tlsMode early enough in our EDS code to be filtered out properly?
