### ISSUE TITLE
Ingress from Kubernetes not supporting IP as host value

### ISSUE THREAD

**Issue by LSChyi** [istio/istio#28811]
**Bug description**
When using Kubernetes ingress definitions, the TLS fails with using IP in the host value field.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
Istio ingress gateway should be able to accept IP as the host value with TLS connections.

**Steps to reproduce the bug**

1. generate a self-signed key and certificate:
    create a `san.cnf` as follows:
    ```
    [req]
    default_bits  = 2048
    distinguished_name = req_distinguished_name
    req_extensions = req_ext
    x509_extensions = v3_req
    prompt = no
    [req_distinguished_name]
    countryName = TW
    stateOrProvinceName = Taiwan
    localityName = Taiwan
    organizationName = example.com
    commonName = example.com
    [req_ext]
    subjectAltName = @alt_names
    [v3_req]
    subjectAltName = @alt_names
    [alt_names]
    IP.1 = 52.249.185.227
    IP.2 = 23.96.127.123
    IP.3 = 127.0.0.1
    ```
    and generate with:
    ```
    $ openssl req -x509 -nodes -days 730 -newkey rsa:2048 -keyout key.pem -out cert.pem -config san.cnf
    ```
2. Create the secret in the `istio-system`:
    ```
    $ kubectl -n istio-system create secret tls bookinfo-credential --key=key.pem --cert=cert.pem
    ```
3. Apply the ingress definition
    ```yaml
    apiVersion: networking.k8s.io/v1beta1
    kind: Ingress
    metadata:
      name: test-ingress
      annotations:
        kubernetes.io/ingress.class: istio
    spec:
      tls:
      - hosts:
        - "52.249.185.227"
        - "23.96.127.123"
        - "127.0.0.1"
        secretName: bookinfo-credential
      rules:
      - http:
          paths:
          - path: /*
            backend:
              serviceName: productpage
              servicePort: 9080
    ```
4. Access the $INGRESS_HOST:$INGRESS_PORT, there is no problem; however, when accessing the $INGRESS_HOST:$SECURE_INGRESS_PORT, the connection is refused:
    ```
    $ curl https://52.249.185.227/ -k -v
    *   Trying 52.249.185.227...
    * TCP_NODELAY set
    * Connection failed
    * connect to 52.249.185.227 port 443 failed: Connection refused
    * Failed to connect to 52.249.185.227 port 443: Connection refused
    * Closing connection 0
    curl: (7) Failed to connect to 52.249.185.227 port 443: Connection refused
    ```

However, if follow the instruction in the [Secure Gateways](https://istio.io/v1.6/docs/tasks/traffic-management/ingress/secure-ingress/), there is no problem with accessing the secure gateway:

```
$ curl -v --resolve "httpbin.example.com:443:52.249.185.227" "https://httpbin.example.com" -k
```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

```
$ istioctl version --remote
client version: 1.6.11
control plane version: 1.6.11
data plane version: 1.6.11 (4 proxies)
```

```
$ kubectl version --short
Client Version: v1.19.3
Server Version: v1.15.12
```

**How was Istio installed?**
```
$ ./istioctl install --set profile=demo
```

**Environment where bug was observed (cloud vendor, OS, etc)**
The bug is observed on a Rancher v2.2.13 installed cluster.

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
