### ISSUE TITLE
Istio-init initContainer adds its own Prometheus endpoint

### ISSUE THREAD

**Issue by APuertaSales** [istio/istio#28820]
**Bug description**
When added a Proxy Envoy sidecar to a Deployment with Prometheus annotations, istio-init initContainer also receives a Prometheus endpoint in port 80.
Thanks in advance!

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
The container with the POD's application should keep the endpoint in Prometheus but the initContainer should not be publishing any target endpoint. It is exporting an 80 port with the same path configured for the Deployment that does not serve anything and end with a 503 error.

**Steps to reproduce the bug**
Configure a Deployment with Prometheus annotations:
```
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
```

Configure the sidecar injection, in my case we have to declare the annotation and label the namespace:
```
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: true
```
Restart the POD to include the Proxy Envoy sidecar.
Added the container pod label to Prometheus scraping:
```
    - job_name: kubernetes-pods
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      kubernetes_sd_configs:
      - api_server: null
        role: pod
        namespaces:
          names: []
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        separator: ;
        regex: "true"
        replacement: $1
        action: keep
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        separator: ;
        regex: (.+)
        target_label: __metrics_path__
        replacement: $1
        action: replace
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        separator: ;
        regex: (.+):(?:\d+);(\d+)
        target_label: __address__
        replacement: ${1}:${2}
        action: replace
      - separator: ;
        regex: __meta_kubernetes_pod_label_(.+)
        replacement: $1
        action: labelmap
      - source_labels: [__meta_kubernetes_namespace]
        separator: ;
        regex: (.*)
        target_label: namespace
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_pod_name]
        separator: ;
        regex: (.*)
        target_label: kubernetes_pod_name
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_pod_container_name]
        action: replace
        target_label: kubernetes_container_name

```
Check Target endpoints in Prometheus, now we can find a new endpoint from the container istio-init:

```
http://174.16.29.177:80/actuator/prometheus | DOWN | instance="174.16.29.177:80" istio_io_rev="default" job="kubernetes-pods" kubernetes_container_name="istio-init" pod_template_hash="6857745c6d" security_istio_io_tlsMode="istio" service_istio_io_canonical_revision="v1" version="v1"
-- | -- | -- server returned HTTP status 503 Service Unavailable
```
And the correct endpoint:

```
http://174.16.206.253:8080/actuator/prometheus | UP | instance="174.16.206.253:8080" istio_io_rev="default" job="kubernetes-pods" kubernetes_container_name="********" pod_template_hash="677b46c89d" security_istio_io_tlsMode="istio" service_istio_io_canonical_revision="v1" version="v1"
-- | -- | --
```

Of course, ff the injection is disabled, the istio-init endpoint disappears. In Kiali and in Grafana the 503 errors are obvious.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
Istio 1.6

# kubectl version --short
Client Version: v1.15.5
Server Version: v1.15.5

**How was Istio installed?**
Istio Operator 1.6-dev with a Helm Chart.

**Environment where bug was observed (cloud vendor, OS, etc)**
Oracle Linux Server release 7.7

Istio ConfigMap configuration:
```
apiVersion: v1
data:
  mesh: |-
    accessLogEncoding: TEXT
    accessLogFile: ""
    accessLogFormat: ""
    defaultConfig:
      concurrency: 2
      configPath: ./etc/istio/proxy
      connectTimeout: 10s
      controlPlaneAuthPolicy: NONE
      discoveryAddress: istiod.istio-system.svc:15012
      drainDuration: 45s
      parentShutdownDuration: 1m0s
      proxyAdminPort: 15000
      proxyMetadata:
        DNS_AGENT: ""
      serviceCluster: istio-proxy
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
    disableMixerHttpReports: true
    disablePolicyChecks: true
    enableAutoMtls: false
    enablePrometheusMerge: false
    ingressClass: istio
    ingressControllerMode: STRICT
    ingressService: istio-ingressgateway
    outboundTrafficPolicy:
      mode: ALLOW_ANY
    protocolDetectionTimeout: 100ms
    reportBatchMaxEntries: 100
    reportBatchMaxTime: 1s
    sdsUdsPath: unix:/etc/istio/proxy/SDS
    trustDomain: cluster.local
    trustDomainAliases: null
  meshNetworks: 'networks: {}'
kind: ConfigMap
```
Thanks in advance!
