### ISSUE TITLE
Egress Gateway mTLS Origination Error

### ISSUE THREAD

**Issue by fraserdarwent** [istio/istio#28858]
**Bug description**
When attempting to upgrade an outbound connection to mTLS I receive an error. This only happens if the client certificate is valid.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Receive response from server e.g. 200 "Hello World".

**Steps to reproduce the bug**
Install Istio and enable egress gateway. Create an `HTTPS` gateway with `tls.mode: PASSTHROUGH`, and attempt to upgrade a request through it with a destination rule to `tls.mode: MUTUAL`.
Here is my actual configuration:
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: https-mtls-darwen-tf
  namespace: default
spec:
  host: mtls.darwen.tf
  
  
  trafficPolicy:
    tls:
      mode: MUTUAL
      clientCertificate: /certificates/mtls-darwen-tf
      privateKey: /certificates/mtls-darwen-tf-key
      caCertificates:/certificates/mtls-darwen-tf-ca
      sni: mtls.darwen.tf
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: https-mtls-darwen-tf
  namespace: default
spec:
  selector:
    istio: egressgateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - mtls.darwen.tf
      tls:
        mode: PASSTHROUGH
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: https-mtls-darwen-tf
  namespace: default
spec:
  hosts:
    - mtls.darwen.tf
  ports:
    - number: 8443
      name: https
      protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: https-mtls-darwen-tf
  namespace: default
spec:
  hosts:
    - mtls.darwen.tf
  gateways:
    - mesh
    - https-mtls-darwen-tf
  tls:
    - match:
      - gateways:
          - mesh
        port: 8443
        sniHosts:
          - mtls.darwen.tf
      route:
        - destination:
            host: istio-egressgateway.istio-system.svc.cluster.local
            port:
              number: 443
    - match:
      - gateways:
          - https-mtls-darwen-tf
        port: 443
        sniHosts:
          - mtls.darwen.tf
      route:
        - destination:
            host: mtls.darwen.tf
            port:
              number: 8443
```
**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
`1.7.4`

**How was Istio installed?**
`istioctl`

**Environment where bug was observed (cloud vendor, OS, etc)**
`AKS`, and also locally reproducible with `Kind`

*With Tusted Client Certificate*

**Client Log (with trusted client certificate)**
```
/application $ curl -k -v https://mtls.darwen.tf:8443
*   Trying 51.158.170.45:8443...
* Connected to mtls.darwen.tf (51.158.170.45) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number
* Closing connection 0
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

**Server Log (with trusted client certificate)
(There is no log entry but Wireshark shows the handshake)
```
```
**Sidecar Log**
```
[2020-11-13T16:05:33.889Z] "- - -" 0 - "-" "-" 517 103 59 - "-" "-" "-" "-" "10.244.0.12:8443" outbound|443||istio-egressgateway.istio-system.svc.cluster.local 10.244.0.11:41062 51.158.170.45:8443 10.244.0.11:34734 mtls.darwen.tf -
```
**Gateway Log**
```
[2020-11-13T16:05:33.890Z] "- - -" 0 - "-" "-" 517 103 60 - "-" "-" "-" "-" "51.158.170.45:8443" outbound|8443||mtls.darwen.tf 10.244.0.12:48326 10.244.0.12:8443 10.244.0.11:41062 mtls.darwen.tf -
```

**With Untrusted Client Certificate**

**Client Log (with untrusted client certificate, to prove that the networking is sound)**
```
/application $ curl -k -v https://mtls.darwen.tf:8443
*   Trying 51.158.170.45:8443...
* Connected to mtls.darwen.tf (51.158.170.45) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to mtls.darwen.tf:8443
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to mtls.darwen.tf:8443
/application $
```
**Server Log (with untrusted client certificate, to prove that the networking is sound)**
```
2020/11/13 16:00:35 http: TLS handshake error from <MY_IP>:57388: remote error: tls: unknown certificate authority
```

**Notes**
There are no other service entries on the cluster and no plaintext services on the port as suggested in https://github.com/istio/istio/issues/16458
