### ISSUE TITLE
[1.7.4]  Upgrade, wrong route for VirtualService host, hence 404 responses

### ISSUE THREAD

**Issue by stamak** [istio/istio#28860]
**Bug description**
After upgrade to 1.7.4 traffic for VirtualService host is passed to wrong k8s service 
We have 2 ingress gateways - public and internal

Public ingress-gateway access logs show that traffic is sent to other service instead!
1.7.4 Public ingress-gateway access logs

```
[2020-11-13T08:13:46.881Z] "GET /health HTTP/2" 404 - "-" "-" 0 5051 4 3 "172.29.6.194" "curl/7.64.1" "79eef750-49a2-4e1d-a05d-93bf251d30e2" 
"serviceA.fqdn.net" "172.29.2.34:8080" outbound|8080||serviceB.NAMESPACE.svc.cluster.local 
172.29.5.237:51562 172.29.5.237:8443 172.29.6.194:48326 serviceA.fqdn.net -
```

After downgrading back to 1.6.11 everything is working
Public ingress-gateway access logs
```
[2020-11-13T10:37:32.603Z] "GET /health HTTP/2" 200 - "-" "-" 0 17 4 4 "172.29.83.30" "curl/7.64.1" "2a1faf00-2c73 46d0-96d3-60136208ea90" 
"serviceA.fqdn.net" "172.29.4.118:4455" outbound|4455||serviceA.NAMESPACE.svc.cluster.local 
172.29.51.205:44326 172.29.51.205:8443 172.29.83.30:1503 serviceA.fqdn.net -
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[X] Upgrade

**Expected behavior**

Requests are sent to right k8s service as it works in Istio 1.6.11

**Steps to reproduce the bug**

`istioctl upgrade  -f my_profile.yaml`

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

```
$ istioctl version --remote
client version: 1.7.4
control plane version: 1.7.4
data plane version: 1.7.4 (35 proxies)

$ kubectl version --short
Client Version: v1.17.0
Server Version: v1.17.9-eks-a84824
```

**How was Istio installed?**

istioctl install/upgrade

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS, EKS

**Comment by Monkeyanator** [comment]
Hi @stamak, thanks for posting. Been seeing a lot of issues around configurations with public/private ingressgateways lately. Would it be possible for you to share more of your configuration here (i.e. your VirtualService specs, config dump for the public ingressgateway)?

**Comment by stamak** [comment]
@Monkeyanator yes, sure

public IngressGateway config
```
apiVersion: networking.istio.io/v1beta1                                                                                      
kind: Gateway
metadata:
  labels:
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  servers:
  - hosts:
    - serviceA.fqdn.net
    - serviceC.fqdn.net
    - serviceD.fqdn.net
    - '*.fqdn.net'
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - serviceA.fqdn.net
    - serviceC.fqdn.net
    - serviceD.fqdn.net
    - '*.fqdn.net'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
```

VirtualService spec
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app: serviceA
  name: serviceA
  namespace: NAMESPACE.
spec:
  gateways:
  - istio-system/istio-ingressgateway
  hosts:
  - serviceA.fqdn.net
  http:
  - route:
    - destination:
        host: serviceA
        port:
          number: 4455
```
