### ISSUE TITLE
Istio ingress gateway TCP keepalive setting for downstream connection

### ISSUE THREAD

**Issue by ediezh** [istio/istio#28879]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Have a way to configure TCP keepalive settings for the downstream connection. 

We use AWS NLB for ingress gateway, however, it has a 350s idle timeout. We also have a lot of long-polling requests which would take around 30 minutes. But a lot of the times the connection gets silently disconnected due to the NLB idle timeout. The way to mitigate this is to have the ingress gateway sending out TCP keepalive probes. 

But at the moment there is no way to configure this setting on the ingress gateway. 

**Describe alternatives you've considered**

I've tried the following envoyfilter as described in https://github.com/envoyproxy/envoy/issues/3634. But it doesn't have any effect. I think the filter only works for upstream connections.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ingress-gateway-socket-options
  namespace: istio-system
spec:
  configPatches:
  - applyTo: LISTENER
    match:
      context: GATEWAY
      listener:
        name: 0.0.0.0_8443
        portNumber: 8443
    patch:
      operation: MERGE
      value:
        socket_options:
        - int_value: 1
          level: 1
          name: 9
          state: STATE_LISTENING
        - int_value: 120
          level: 6
          name: 4
          state: STATE_LISTENING
        - int_value: 60
          level: 6
          name: 5
          state: STATE_LISTENING
```

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by ediezh** [comment]
Any suggestions or workaround would be welcome.

**Comment by yteraoka** [comment]
That EnvoyFilter worked for me.
Did you restart istio-ingressgateway?

You can check applied config using istioctl command.

```
❯ istioctl proxy-config listeners istio-ingressgateway-5f795f84c4-22rr2.istio-system --port 8443 -o json | jq '.[0].socketOptions'
[
  {
    "level": "1",
    "name": "9",
    "intValue": "1",
    "state": "STATE_LISTENING"
  },
  {
    "level": "6",
    "name": "4",
    "intValue": "10",
    "state": "STATE_LISTENING"
  },
  {
    "level": "6",
    "name": "5",
    "intValue": "10",
    "state": "STATE_LISTENING"
  }
]
```

**Comment by yteraoka** [comment]
But, Just now, I tryed again with Istio 1.8.
After restarting istio-ingressgateway, the listener config that envoyfilter merged was gone 😱 
Delete envoyfiler and restart istio-ingressgateway then the listener appeared again. 🤔

**Comment by yteraoka** [comment]
> But, Just now, I tryed again with Istio 1.8.
> After restarting istio-ingressgateway, the listener config that envoyfilter merged was gone 😱
> Delete envoyfiler and restart istio-ingressgateway then the listener appeared again. 🤔

Oh, my EnvoyFilter is edited after last test, and its wrong. I fixed it then it worked.

**Comment by ediezh** [comment]
@yteraoka yes the envoyfilter is applied on the gateway. But it still only works for downstream connections.

**Comment by ediezh** [comment]
sorry to correct my last post, the socketoptions work for upstream connection but not downstream.

**Comment by yteraoka** [comment]
Yes, I know that. My IngressGateway sent keepavlie to downstream.
I checked that using tcpdump on client and ingressgateway.

**Comment by ediezh** [comment]
> Yes, I know that. My IngressGateway sent keepavlie to downstream.
> I checked that using tcpdump on client and ingressgateway.

Can I ask how do you run tcpdump on ingressgateway?

**Comment by yteraoka** [comment]
Add the below config in IstioOperator and apply to run container as root. And `kubectl -n istio-system -it exec istio-ingressgateway-xxxxx-xxxx -- bash`.

```yaml
values:
   gateways:
    istio-ingressgateway:
      runAsRoot: true
```

Or https://github.com/jordanwilson230/kubectl-plugins/blob/master/kubectl-ssh may be useful. But I didn't try kube-ssh.

```
tcpdump -i eth0 -n -nn port <your_service_port_of_ingress-gateway> or port <your_destination_port>
```

**Comment by ediezh** [comment]
thanks @yteraoka, will give it a try.

**Comment by wujiaqi** [comment]
@ediezh I am experiencing the same issue as you are. Did you ever find out what was wrong?

**Comment by ediezh** [comment]
@wujiaqi no I didn’t found out why. The envoyfileter only works for upstream connection for me.

**Comment by ramaraochavali** [comment]
For upstream connections Envoy filter is not needed. It is based on mesh config tcp keepalive settings

**Comment by jaronoff97** [comment]
I have a similar problem. I applied the linked envoyfilter to my mesh which is seeing a large amount of 0 response codes (as a result of the NLB timeout I believe), but the filter did nothing

**Comment by ramaraochavali** [comment]
This filter worked for us
```
spec:
  configPatches:
  - applyTo: LISTENER
    match:
      context: GATEWAY
    patch:
      operation: MERGE
      value:
        socket_options:
        - int_value: 1
          level: 1
          name: 9
          state: STATE_PREBIND
        - int_value: 9
          level: 6
          name: 6
          state: STATE_PREBIND
        - int_value: 120
          level: 6
          name: 4
          state: STATE_PREBIND
        - int_value: 30
          level: 6
          name: 5
          state: STATE_PREBIND
     ```
