### ISSUE TITLE
cross namespace virtualservice not working

### ISSUE THREAD

**Issue by yzhu2** [istio/istio#28909]
**Bug description**
virtual service config not working when the virtual service is cross reference a service defined in another namespace using FQDN.

```
---
apiVersion: v1
kind: Service
metadata:
  name: fortioserver
  namespace: fortioserver
spec:
  ports:
    - name: http-echo
      port: 8080
      protocol: TCP
  selector:
    app: fortioserver
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: fortioserver
  namespace: fortioclient
spec:
  hosts:
  - fortioserver.fortioserver.svc.cluster.local
  http:
  - timeout: 3s
    route:
    - destination:
        host: fortioserver.fortioserver.svc.cluster.local
      weight: 100

```
when I check the route config dump, `timeout: 3s` is not applied. if I move this virtualservice to `fortioserver` namespace, the `timeout: 3s` is correctly applied.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
namespace should not matter

**Steps to reproduce the bug**
apply the following config:
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: fortioclient
  labels:
    istio-injection: enabled
---
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: fortioclient
  namespace: fortioclient
spec:
  egress:
  - hosts:
    - fortioserver/*
  workloadSelector:
    labels:
      app: fortioclient
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortioclient
  namespace: fortioclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortioclient
  template:
    metadata:
      labels:
        app: fortioclient
    spec:
      containers:
        - name: fortioclient
          image: fortio/fortio:latest_release
---
apiVersion: v1
kind: Namespace
metadata:
  name: fortioserver
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: fortioserver
  namespace: fortioserver
spec:
  ports:
    - name: http-echo
      port: 8080
      protocol: TCP
  selector:
    app: fortioserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortioserver
  namespace: fortioserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortioserver
  template:
    metadata:
      labels:
        app: fortioserver
    spec:
      containers:
        - name: fortioserver
          image: fortio/fortio:latest_release
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: fortioserver
  namespace: fortioclient
spec:
  hosts:
  - fortioserver.fortioserver.svc.cluster.local
  http:
  - timeout: 3s
    route:
    - destination:
        host: fortioserver.fortioserver.svc.cluster.local
      weight: 100
```

then go to fortioclient namespace, `kubectl get pods` to find the fortioclient pod, and run:
`istioctl dash envoy <pod>`
check the config_dump, you could see that the timeout is not applied: ```"timeout": "0s",```

but if you move the above virtualservice to namespace fortioserver, and check the config dump again, in routes, you could see the timeout is correctly applied to 3s.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
1.6.11

**Comment by yzhu2** [comment]
adding
fortioclient/*
to the egress hosts list solves the problem
```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: fortioclient
  namespace: fortioclient
spec:
  egress:
  - hosts:
    - fortioserver/*
    - fortioclient/*
  workloadSelector:
    labels:
      app: fortioclient
```
