### ISSUE TITLE
istioctl install causes Telemetry v1 HPA scaling to be overridden with fixed Deployment replicaCount

### ISSUE THREAD

**Issue by chadlwilson** [istio/istio#28916]
**Bug description**

When installing control plane `1.6` or `1.7`, telemetry V1 always scales back in to 1 replica regardless of the `hpaSpec` in your `IstioOperator` resource. Then the HPA seems to scale it back up.

If I am reading correctly, I believe this appears to be because the `Deployment.yaml` [does not seem to have the necessary checks to omit the `spec.replicas` field from the spec](https://github.com/istio/istio/blob/8679fb5d1a8aacc8a22539ff45fac945a121bca0/manifests/charts/istio-telemetry/mixer-telemetry/templates/deployment.yaml#L11) when `.Values.mixer.telemetry.autoscaleEnabled`. 

See [`istio-policy`](https://github.com/istio/istio/blob/release-1.6/manifests/charts/istio-policy/templates/deployment.yaml)  or [`istiod`](https://github.com/istio/istio/blob/release-1.6/manifests/charts/istio-control/istio-discovery/templates/deployment.yaml) where this appears to be working correctly.

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Installation with no changes to `IstioOperator` resource should not lead to changes in the manifest; i.e they should be idempotent; not causing scale up/scale-down on re-install..

Would appreciate if we can backport/cherry-pick any fix to `1.6.x` as some of us are blocked on `1.7.x` upgrades due to the K8S `1.16` requirement.

**Steps to reproduce the bug**

Any `IstioOperator` install with telemetry v1 (relevant snippets below) should show the issue.
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    telemetry:
      enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2
  values:
    telemetry:
      v1:
        enabled: true
      v2:
        enabled: false
```

**Version**

Istio `1.6.13` (although looks like `1.7.4` has the same issue)

**How was Istio installed?**

Via `istioctl install`
