### ISSUE TITLE
Make it possible to control the order of rules in merged VirtualService definition

### ISSUE THREAD

**Issue by akhalyavka** [istio/istio#28914]
**Describe the feature request**
Currently, istio [docs](https://istio.io/latest/docs/ops/best-practices/traffic-management/#split-virtual-services) about VirtualService merging state that 
> Although the order of evaluation for rules in any given source VirtualService will be retained, the cross-resource order is UNDEFINED. In other words, there is no guaranteed order of evaluation for rules across the fragment configurations, so it will only have predictable behavior if there are no conflicting rules or order dependency between rules across fragments.

What we'd like to see is a way to control this order. The use case we have for this is "dark deploy" of developers' feature branches, nicely described in https://github.com/istio/istio/issues/22997#issuecomment-700975915:

> One user scenario we have for this is to do with "branch" deployments whereby you want to create a unique deployment of a service for each feature branch that is open for engineers to test their changes before merging to "main" branch.
> 
> In a microservice environment it's tricky to deal with routing traffic through the services but wanting a particular request to hit a specific "branch" deployment for a given service.
> 
> One way we are solving this is by using header based routing. When we deploy the "branch" environment for Service B we add an additional routing logic to only receive requests with the header x-review:my-branch-name. When an engineer makes a request to Service A with that header, the request will go to the "main" branch deployment of Service A. If Service A then makes a request to Service B, Service A will passthrough the x-review:my-branch-name header to Service B. The service mesh would then see that header and route the request to the "branch" deployment of Service B.
> 
> We deploy each "branch" deployment as a separate Helm deployment so would be nice if we could have a separate TrafficSplit in each deployment which will reference the same service but introduce a new header backend route
> 

The problem with this scenario is that it's sensitive to order of rules in merged VirtualService. Let's say we have a service bound to a gateway with prefix `/blogs`. The version-controlled VirtualService looks like this:
```
kind: VirtualService
spec:
  hosts:
    - api.company.com
  http:
    - route:
        - destination:
            host: blogs-service
      match:
        - uri:
            prefix: /blogs
```

And the VirtualService that is a part of dark deployment looks like this:
```
kind: VirtualService
spec:
  hosts:
    - api.company.com
  http:
    - route:
        - destination:
            host: blogs-service-alexey
      match:
        - uri:
            prefix: /blogs
          headers:
            x-username:
              exact: "alexey"
```
For this to work the dark deployment's rule should be evaluated before "master" rule, and currently there is no way to reliably achieve this.

**Affected product area (please put an X in all that apply)**
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
