### ISSUE TITLE
Make Canary Upgrades with Operator gitops friendly

### ISSUE THREAD

**Issue by joberdick-rcd** [istio/istio#28967]
**Describe the feature request**
Using the Istio operator enables a pull based workflow that can automatically update/install Istio from a single source of truth and has some self healing properties. Currently, it does not appear that the canary upgrade process supports gitops workflows.

I am not suggesting trying solve data plane upgrades, but atleast the removal of an old version of Istio. 
 
Currently, a single IstioOperator manifest is applied and different operators act on it based on the revision flag. The problem with this is there is not a way to remove a revision via the same IstioOperator object. Removing it entirely would remove all 
control planes. 

 **Suggestion**: add a flag to the IstioOperator manifest that restricts what revision(s) are to be installed by operators.

For example 

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-controlplane
spec:
  enabledRevisions:
  - 1-6-9 # allow older version
  - 1-7-4 # allow newer version
  - null  # this would allow non-revision operators(before canary) 
```
If the operators used this as a selector, it could add or remove versions on the fly. Omitting ```enabledRevisions``` could default to today's functionality of no restriction. 

**Describe alternatives you've considered**
Applying completely separate manifests in different namespaces. Not sure this is the intent of the direction of canary. 

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
