### ISSUE TITLE
Canary Deployment Support Default NS Labels

### ISSUE THREAD

**Issue by joberdick-rcd** [istio/istio#28969]
**Describe the feature request**
When using revisions for canary upgrades. The sidecar injection relies only on the namespace label of ```istio.io/rev=something_here```. It will ignore the value of ```istio-injection=enabled```. This presents a management challenge on the application side. We run a large enterprise with many teams that consume k8s via our custom helm charts. This includes our namespace setup. If we can't use ```istio-injection=enabled``` we are going to be chasing version labels and teams can easily have an outdated chart that will result in a broken deployment.

**Suggestion**: Have a way to define a default version via the IstioOperator manifest. For example:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-controlplane
spec:
  defaultRevison: 1-7-4
```
By defining a default revision in the manifest, operators could then still listen for ```istio-injection=enabled``` in a way that cluster admins can control. After a canary rollout is complete, the new revision could then be updated to also listen for regular injection. The Istio operator would then update either sidecar injector or CNI to act accordingly.

**Describe alternatives you've considered**

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by shamsher31** [comment]
> Suggestion: Have a way to define a default version via the IstioOperator manifest. For example:

Will this work for you?
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-controlplane
spec:
  revison: 1-7-4
```

Ref: https://preliminary.istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#IstioOperatorSpec

**Comment by joberdick-rcd** [comment]
Hi @shamsher31, I think that might solve: https://github.com/istio/istio/issues/28967. We would just need one manifest per revision?

I don't see how that solves the issue of a default namespace label though. I suppose something like this could work:

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-controlplane
spec:
  revison: 1-7-4
  default: true
```
When default is true, that version will be what istio-injection=enabled goes to.
The only risk seems to be if someone accidently sets default on more than one manifest. How that could be handled.
