### ISSUE TITLE
Subset cluster has no endpoints

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#28981]
**Bug description**

Our customers have a DestinationRule with subset like this:
```
 apiVersion: networking.istio.io/v1beta1
 kind: DestinationRule
 metadata:
   name: myapp
 spec:
   host: myapp
   trafficPolicy:
     loadBalancer:
       simple: LEAST_CONN
   subsets:
    - name: testversion
      labels:
       version: v3
     trafficPolicy:
       loadBalancer:
         simple: ROUND_ROBIN
```

However, `myapp` service are deployed with hostNetwork and without sidecar.  And after sometime, we found that the subset cluster's endpoints are all gone.

After some diagnosing, I think i found the cause. For hostNework pods, they may have same pod ip. In istio, we heavily depend on podip as a unique key to select pod.
