### ISSUE TITLE
istio-1.7.4 does not support --set values.global.proxy.accessLogEncoding="JSON"

### ISSUE THREAD

**Issue by hillbun** [istio/istio#28990]
I download https://github.com/istio/istio/releases/download/1.7.4/istio-1.7.4-linux-amd64.tar.gz

./bin/istioctl manifest generate \
--set values.global.proxy.accessLogEncoding="JSON" \
> ./generated.yaml

shows error of 

Run the command with the --force flag if you want to ignore the validation error and proceed.
Error: unknown field "accessLogEncoding" in v1alpha1.ProxyConfig

How to fixed it? thanks

**Comment by morvencao** [comment]
`accessLogEncoding` is removed from old helm values parameters, you should try set it with `meshConfig`:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    accessLogEncoding: "JSON"
```
