### ISSUE TITLE
EnvoyFilter HTTPFilter Patch Not work with 1.7.x

### ISSUE THREAD

**Issue by FqqCS** [istio/istio#29035]
Looks like when there is a patch apply to Network_Filter  envoy.http_connection_manager  with operator merge, All patches applied to  HTTP_FILTER are ignored. 

Proxy: 1.7.4
istio: 1.7.4

Envoy Filter with a patch apply to NETWORK_FILTER , it works.
Envoy Filter with a patch apply to HTTP_FILTER; i tried Lua Filter , it works.
Envoy Filter with a patch apply to NETWORK_FILTER and a patch apply to HTTP_FILTER; NETWORK_FILTER patch works, but HTTPFilter patch Not work.
Lua Filter is ignored.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: test.gateway
  namespace: test
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.router"
    patch:
      operation: INSERT_BEFORE
      value: # lua filter specification
        name: envoy.filters.http.lua
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
          inlineCode: |
            function envoy_on_request(handle)
            
            end
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
    patch:
      operation: MERGE
      value:
        name: envoy.http_connection_manager
        typed_config:
          '@type': type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          common_http_protocol_options:
            idle_timeout: 75s
          http2_protocol_options:
            initial_connection_window_size: 1048576
            initial_stream_window_size: 65536
            max_concurrent_streams: 100
  workloadSelector:
    labels:
      sharding: 1

```
