### ISSUE TITLE
Istio ingressgateway with SDS

### ISSUE THREAD

**Issue by bcochofel** [istio/istio#29047]
**Bug description**

I have deployed istio ingressgateway with SDS and certificate from Let's Encrypt. When the certificates gets renew I still need to rollout the gateway in order to have the new certificate. I'm not using custom gateway, I'm just using the default one that's installed with Istio. 

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

When the secret gets update with the new certificate the Gateway should also update.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

```
istioctl version --remote
client version: 1.5.10
control plane version: 1.5.10
data plane version: 1.5.10 (36 proxies)

kubectl version --short
Client Version: v1.17.3
Server Version: v1.17.9
```

**How was Istio installed?**

```istioctl```

**Environment where bug was observed (cloud vendor, OS, etc)**

Azure AKS

**Comment by howardjohn** [comment]
@bcochofel do you have any more logs or more info? Also would be interested if this happens on more recent versions (https://istio.io/latest/news/support/announcing-1.5-eol-final/).

This feature is pretty well tested so if its breaking for you there must be some environmental difference or similar. Does this always occur or just sometimes?

**Comment by bcochofel** [comment]
@howardjohn I can give logs, can you tell me what are the most usefull ones?

Let me try to describe the environment a bit, we have a pipeline that renews the certificate and stores it on Azure Key Vault. We are using this https://akv2k8s.io/ to sync the secret, and this is being done correctly. In order to use that we have patched the istio-system namespace with the label that's needed for akv2k8s (by the way, is there a way in the configuration to do this?) 

The ingress-gateway looks like this:

```
  - hosts:
    - '*'
    port:
      name: https-default
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
```

Should we create our own gateway to use the value from secret instead of certificates being mounted?
