### ISSUE TITLE
Istio does not update the status of service-apis's gatewayclass

### ISSUE THREAD

**Issue by nak3** [istio/istio#29043]
**Bug description**

The status of service-apis's gatewayclass is always Unknown.

[X] Networking

**Expected behavior**

The status of service-apis's gatewayclass should be updated as https://kubernetes-sigs.github.io/service-apis/gatewayclass/#gatewayclass-status

**Steps to reproduce the bug**

1. Deploy the following GatewayClass.

```
apiVersion: networking.x-k8s.io/v1alpha1
kind: GatewayClass
metadata:
  name: istio
spec:
  controller: istio.io/gateway-controller
```

2. See the status field. (It always `Unknown`.)

```
$ kubectl get gatewayclass -o yaml

  status:
    conditions:
    - lastTransitionTime: "1970-01-01T00:00:00Z"
      message: Waiting for controller
      reason: Waiting
      status: Unknown
      type: InvalidParameters
```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

#### istio version

```
$ istioctl version
client version: 1.8.0-alpha.2
control plane version: 1.8.0-alpha.2
data plane version: 1.8.0-alpha.2 (1 proxies)
```

#### service-apis version

```
$ kubectl apply -k 'github.com/kubernetes-sigs/service-apis/config/crd?ref=v0.1.0-rc1'
```

(Since Istio 1.8.0 supports v0.1.0-rc1, using v0.1.0-rc1 instead of v0.1.0.)
