### ISSUE TITLE
Fault injection and URI rewrite for "self-routing" VirtualService do not work as expected

### ISSUE THREAD

**Issue by Janesee3** [istio/istio#29044]
**Bug description**
As described in title - fault injection and URI rewrite don't work for "self-routing" VirtualService (ie. both `host` and `destination` values are the same).

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Steps to reproduce the bug**

Assume there is a Service, `dummy-service`, that doesn't have any backing pods/endpoints as such:
```
apiVersion: v1
kind: Service
metadata:
  name: dummy-service
  namespace: services
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      name: http
```

Create VS `virtualservice-one` which routes from the ingressgateway to `dummy-service`.
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: virtualservice-one
  namespace: services
spec:
  gateways:
    - web
  hosts:
    - myhost.com
  http:
    - match:
        - uri:
            exact: /test
      route:
        - destination:
            host: dummy-service.services.svc.cluster.local
```

Create another VS, `virtualservice-two`, which is a "self-routing" VS similar to how we configure retries (see https://istio.io/latest/docs/concepts/traffic-management/#retries). This VS uses fault injection to force the return of a `404` http status.
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: virtualservice-two
  namespace: services
spec:
  hosts:
    - dummy-service.services.svc.cluster.local
  http:
    - match:
        - uri:
            exact: /test
      fault:
        abort:
          percentage:
            value: 100
          httpStatus: 404
      route:
        - destination:
             host: dummy-service.services.svc.cluster.local
```

Make an HTTP call to `myhost.com/test`, and we receive `503` with flag `UH`, which means fault injection didn't take place.

The same behaviour applies even if `dummy-service` was replaced by an actual Kubernetes Service with backing endpoints. In that case instead of receiving a `503 UH`, we get the same results as we do when we hit `/test` on the Service. Eg. Receiving `403 RBAC: access denied` if we didn't allow the ingressgateway proxy to hit the `/test` route on the service's proxy.

Additionally, apart from just fault injection, `rewrite` does not work as well when it is configured in the second VS.  

Does this mean that apart from the retry settings, other settings wouldn't work for "self-routing" VS? 

**Version**
Istio
```
client version: 1.7.4
control plane version: 1.6.13-2259094caeb07b4cf631c99b71ea4a9d3840aa4e
data plane version: 1.6.13 (30 proxies)
```

Kubernetes: `Client Version: v1.16.15`

**How was Istio installed?**
Using `istioctl install` 

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS
