### ISSUE TITLE
istio-operator can't handle IstioOperator CR deletion with revision and custom namespace

### ISSUE THREAD

**Issue by apolovov** [istio/istio#29066]
**Bug description**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

istio-operator must delete all resources related to revision after deleting iop resource.

**Steps to reproduce the bug**

* Install istio-operator deployment to custom namespace `d8-istio` with actual rbac settings from master.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: d8-istio
  name: operator-v1x8x0
  labels:
    app: operator
    revision: v1x8x0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
      revision: v1x8x0
  template:
    metadata:
      labels:
        app: operator
        revision: v1x8x0
    spec:
      serviceAccountName: operator
      containers:
        - name: operator
          image: docker.io/istio/operator:1.8.0
          command:
          - operator
          - server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1337
            runAsUser: 1337
            runAsNonRoot: true
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              value: d8-istio
            - name: LEADER_ELECTION_NAMESPACE
              value: d8-istio
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: d8-istio
            - name: WAIT_FOR_RESOURCES_TIMEOUT
              value: 300s
            - name: REVISION
              value: v1x8x0
```
* create iop resource in `d8-istio` namespace:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: v1x8x0
  namespace: d8-istio
spec:
  addonComponents:
    istiocoredns:
      enabled: false
  components:
    base:
      enabled: true
    cni:
      enabled: false
    egressGateways:
    - enabled: false
      name: istio-egressgateway
    ingressGateways:
    - enabled: false
      name: istio-ingressgateway
    istiodRemote:
      enabled: false
    pilot:
      enabled: true
  meshConfig:
    rootNamespace: d8-istio
  revision: v1x8x0
  values:
    global:
      istioNamespace: d8-istio
      trustDomain: cluster.local
    pilot:
      autoscaleEnabled: false
      configNamespace: d8-istio
```
* After successfully deployed control-plane delete the `v1x8x0` iop.
* istio-operator hangs:
```
2020-11-20T01:06:00.528838Z	info	installer	Reconciling IstioOperator
2020-11-20T01:06:00.530319Z	info	installer	Deleting IstioOperator v1x8x0
2020-11-20T01:06:01.546317Z	info	installer	Reconciling IstioOperator
2020-11-20T01:06:01.548187Z	info	installer	Deleting IstioOperator v1x8x0
2020-11-20T01:06:02.558262Z	info	installer	Reconciling IstioOperator
2020-11-20T01:06:02.559506Z	info	installer	Deleting IstioOperator v1x8x0
```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
```
$ operator version
version.BuildInfo{Version:"1.8.0", GitRevision:"c87a4c874df27e37a3e6c25fa3d1ef6279685d23", GolangVersion:"go1.15.5", BuildStatus:"Clean", GitTag:"1.8.0-rc.1"}
```
```
# kubectl version --short
Client Version: v1.16.15
Server Version: v1.16.15
```

**How was Istio installed?**
istio-operartor was deployed to ns `d8-istio` with custom deployment and rbac rules from master.

**Environment where bug was observed (cloud vendor, OS, etc)**
bare metal vanilla setup.
