### ISSUE TITLE
service-api's HTTPRoute spec.gateways does not work

### ISSUE THREAD

**Issue by nak3** [istio/istio#29070]
**Bug description**

- HTTPRoute spec.gateways is not working.

[X] Networking

**Expected behavior**

**Steps to reproduce the bug**

1. Deploy service-apis

2. Deploy HTTPRoute with `spec.gateways.allow` to `FromList`.

(e.g - gatewayRefs is invalid.)

```
  spec:
    gateways:
      allow: FromList
      gatewayRefs:
      - name: bar
        namespace: foo
```

3. The HTTPRoute always work even thought the gatewayRefs is invalid.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

istio version

```
$ istioctl version
client version: 1.8.0
control plane version: 1.8.0
data plane version: 1.8.0 (1 proxies)
```

servicce-apis version

```
$ kubectl apply -k 'github.com/kubernetes-sigs/service-apis/config/crd?ref=v0.1.0-rc2'
```
