### ISSUE TITLE
Istio 1.7.4 - AWS ELB firing Backend connection errors with multiple ingressGateways

### ISSUE THREAD

**Issue by MatteoMori** [istio/istio#29079]
**Bug description**

Hello All,

I have been having some troubles with Istio **1.7.4** and **multiple ingressGateways**.

Basically, although traffic-wise the environment seems to be working fine, AWS is showing me a **consistent flow of ELB Backend connection errors** on one of the Istio ELBs. 

This is surprising to me since both ingressGateways have been configured the same way and deployed at the same time using the `IstioOperator` api.

Am I doing anything silly here?

[ ] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Considering that both ingressGateways have been deployed in the same way, I expect to see the same behavior and therefore no Backend connection errors in AWS.

**Steps to reproduce the bug**

* Deploy Istio like the following:

  ```bash
  istioctl install --set profile=default -f ./ingress_gateways.yaml 
  ```

  * Overlay definition (`ingress_gateways.yaml `):

  ```yaml
  apiVersion: install.istio.io/v1alpha1
  kind: IstioOperator
  spec:
    components:
      ingressGateways:
        - name: istio-ingressgateway
          enabled: true
          label: 
            custom_gateway: "general"
          k8s:
            service:
              ports:
              - name: status-port
                port: 15021
                targetPort: 15021
              - name: http2
                port: 80
                targetPort: 8080
              - name: https
                port: 443
                targetPort: 8443
            serviceAnnotations:
              service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
              service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
              service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
              service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "<REDACTED>"
        - name: test-ingress
          enabled: true
          label:
            custom_gateway: "test-ingress"
          k8s:
            service:
              ports:
              - name: status-port
                port: 15021
                targetPort: 15021
              - name: http2
                port: 80
                targetPort: 8080
              - name: https
                port: 443
                targetPort: 8443
            serviceAnnotations:
              service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
              service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
              service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
              service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "<REDACTED>"
    values:
      gateways:
        istio-ingressgateway:
          loadBalancerSourceRanges:
            - "<REDACTED>"
  
  ```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

* **istioclt**

  ```bash
  $ istioctl version --remote
  client version: 1.7.4
  control plane version: 1.7.4
  data plane version: 1.7.4 (6 proxies)
  ```

* **kubectl**

  ```bash
  $ kubectl version --short
  Client Version: v1.18.9
  Server Version: v1.18.9-eks
  ```

* **helm**

  ```bash
  $ helm version
  version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"dirty", GoVersion:"go1.15.4"}
  ```

  

**How was Istio installed?**

```bash
istioctl install --set profile=default -f ./ingress_gateways.yaml 
```

*see above **Steps to reproduce the bug** to see how `ingress_gateways.yaml` looks like*

**Environment where bug was observed (cloud vendor, OS, etc)**

* AWS EKS 1.18
