### ISSUE TITLE
virtual service merging should move catchall block to the end

### ISSUE THREAD

**Issue by yingzhuivy** [istio/istio#29092]
**Describe the feature request**

We want to allow clients in different namespaces override timeout & retry settings for a host.

We could achieve this by the following setup: 
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vs-client
  namespace: client
spec:
  hosts:
  - server.server
  http:
  - match:
    - sourceNamespace: client
      sourceLabels:
        app: client-1
    timeout: 3s
    delegate:
      name: vs-delegate
      namespace: server
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vs-server
  namespace: server
spec:
  hosts:
  - server.server
  http:
  - timeout: 1s
    delegate:
      name: vs-delegate
      namespace: server
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vs-delegate
  namespace: server
spec:
  http:
  - route:
    - destination:
        host: server
```
Basically we have a delegate virtual service `vs-delegate` in the server namespace that controls the route (the route may change). Then we have another catchall vs `vs-server` that delegates to `vs-delegate` with no match conditions, and timeout of 1s. If a client wants to override the timeout, it can define another vs, for example `vs-client` in its own namespace, delegating to `vs-delegate` with the timeout it wants. However, right now, this does not work because merging of those virtual services does not identify the catchall block. Ideally, this catch all block should be moved to the end of the list.

Also, I noticed that the delegate feature is not even alpha yet (https://github.com/istio/enhancements/issues/5). What's our long term plan for this feature? any plan to promote it to beta soon?

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
