### ISSUE TITLE
An authorizationPolicy in istio-system will break tls passthrough service

### ISSUE THREAD

**Issue by haohaolee** [istio/istio#29119]
**Bug description**
I have a kubernetes setup in EKS with istio 1.8.0 installed. Also I have multiple virtualservices, one of them is using passthrough without TLS termination (keycloak actually), others are still using TLS termination. Without authorization policy, everything works fine. But if I put a new authorization policy in istio-system, passthrough service stops working. The error is:
```
curl https://keycloak.xxx.com
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to keycloak.xxx.com:443
```

My authorization policy looks like the following:
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: policy
  namespace: istio-system
spec:
  action: DENY
  rules:
  - from:
    - source:
        notRemoteIpBlocks:
        - x.x.x.x
    to:
    - operation:
        hosts:
        - someservice.xxx.com
  selector:
    matchLabels:
      app: istio-ingressgateway
```

btw, the policy itself works well for my someservice, but breaks keycloak

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
The authorization policy works and TLS passthrough also works

**Steps to reproduce the bug**
Create two virtualservices one is using tls termination, the other is using tls passthrough, then add a deny authorization policy in istio-system.
tls passthrough will stop working

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
```
$ ./istioctl version
client version: 1.8.0
control plane version: 1.8.0
data plane version: 1.8.0 (13 proxies)
```

```
$ kubectl version --short
Client Version: v1.19.4
Server Version: v1.18.9-eks-d1db3c
```

**How was Istio installed?**
installed using istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS

**Comment by howardjohn** [comment]
Does the traffic match the denied IP block?

**Comment by haohaolee** [comment]
> Does the traffic match the denied IP block?

Nope. Because:
1. I have other tls-terminated services which are not affected by this rule
2. I also tried to use the IP addresses which are not in the denied IP block to visit the tls-passthrough service, still the same error

**Comment by yangminzhu** [comment]
the authorization policy also applies to pass through filter chain, the general solution is to exclude the port in the policy if you don't want it to be enforced.

> > Does the traffic match the denied IP block?
> 
> Nope. Because:
> 
> 1. I have other tls-terminated services which are not affected by this rule
> 2. I also tried to use the IP addresses which are not in the denied IP block to visit the tls-passthrough service, still the same error

Just to double check, when you say `IP addresses which are not in the denied IP block`, you mean an IP address that is `x.x.x.x` because you used `notRemoteIpBlocks` in the policy? (anything not in `x.x.x.x` should be denied), I would expect this to be allowed.

Could you upload the proxy config dump (only need the 15006 listener part) to help the debug, please remember to redact the IP addresses and any other sensitive information before uploading.

**Comment by haohaolee** [comment]
> the authorization policy also applies to pass through filter chain, the general solution is to exclude the port in the policy if you don't want it to be enforced.
I have tried some rules but could not work out one. What I have tried include:
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: keycloak-ingress-policy
  namespace: istio-system
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        hosts:
        - keycloak.xxx.com
  selector:
    matchLabels:
      app: istio-ingressgateway
```
This doesn't work. I have no idea how to write one to specify the destination port, say the port of the internal virtualservice is 8443
> 
> > > Does the traffic match the denied IP block?
> > 
> > 
> > Nope. Because:
> > 
> > 1. I have other tls-terminated services which are not affected by this rule
> > 2. I also tried to use the IP addresses which are not in the denied IP block to visit the tls-passthrough service, still the same error
> 
> Just to double check, when you say `IP addresses which are not in the denied IP block`, you mean an IP address that is `x.x.x.x` because you used `notRemoteIpBlocks` in the policy? (anything not in `x.x.x.x` should be denied), I would expect this to be allowed.

Yes. I am using the IP of x.x.x.x, which was the original idea of a whitelist
> 
> Could you upload the proxy config dump (only need the 15006 listener part) to help the debug, please remember to redact the IP addresses and any other sensitive information before uploading.
Here is my dump:
```
./istioctl proxy-config listener istio-ingressgateway-6f8778ff6f-94s7g -n istio-system
ADDRESS PORT  MATCH                                   DESTINATION
0.0.0.0 8080  ALL                                     Route: http.80
0.0.0.0 8443  SNI: xxx.com          Route: https.443.https-website.official-website.website
0.0.0.0 8443  SNI: sonarqube.xxx.com Route: https.443.https-sonarqube.sonarqube-gateway.sonarqube
0.0.0.0 8443  SNI: jenkins.xxx.com   Route: https.443.https-jenkins.jenkins-gateway.jenkins
0.0.0.0 8443  SNI: argocd.xxx.com    Route: https.443.https-argocd.argocd-gateway.argocd
0.0.0.0 8443  SNI: keycloak.xxx.com  Cluster: outbound|8443||keycloak.keycloak.svc.cluster.local
0.0.0.0 15021 ALL                                     Inline Route: /healthz/ready*
0.0.0.0 15090 ALL                                     Inline Route: /stats/prometheus*
```
Only keycloak is using TLS passthrough, others are all of TLS termination. Once I delete all the authorization policies, I can visit keycloak service


Thanks

**Comment by yangminzhu** [comment]
Normally you can use the `ports` and `notPorts` field to specify the destination port, but here you probably couldn't just use port because there are multiple sites on it.

You can also try to use [connection.sni](https://istio.io/latest/docs/reference/config/security/conditions/#supported-conditions) condition to exclude the keycloak from the authorization policy.

You can turn on the debug logging of the `rbac` filter to see the actual sni value (`istioctl pc logs <pod> --level "rbac:debug"`), and then put it in your authorization policy to exclude it.

**Comment by haohaolee** [comment]
> Normally you can use the `ports` and `notPorts` field to specify the destination port, but here you probably couldn't just use port because there are multiple sites on it.
> 
> You can also try to use [connection.sni](https://istio.io/latest/docs/reference/config/security/conditions/#supported-conditions) condition to exclude the keycloak from the authorization policy.

Tried, but it didn't work. With the following setting:
```
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: keycloak-ingress-policy
  namespace: istio-system
spec:
  action: ALLOW
  rules:
  - when:
     - key: "connection.sni"
       values: ["keycloak.xxx.com"]
```
> 
> You can turn on the debug logging of the `rbac` filter to see the actual sni value (`istioctl pc logs <pod> --level "rbac:debug"`), and then put it in your authorization policy to exclude it.

Here is the output:
```
2020-11-25T07:22:47.959885Z	debug	envoy rbac	checking connection: requestedServerName: keycloak.xxx.com, sourceIP: x.x.x.x:21633, directRemoteIP: 10.0.2.177:2159,remoteIP: 10.0.2.177:2159, localAddress: 10.0.102.165:443, ssl: none, dynamicMetadata:
2020-11-25T07:22:47.959915Z	debug	envoy rbac	enforced denied, matched policy ns[istio-system]-policy[jenkins-ingress-policy]-rule[0]
```
as you can see, this request was indeed denied by the jenkins rule which I put in the original post

**Comment by yangminzhu** [comment]
You cannot exclude it in ALLOW policy if it is to be rejected by another DENY policy because DENY policy takes precedence over ALLOW policy, see more here: https://istio.io/latest/docs/concepts/security/#implicit-enablement.

To properly exclude the `keycloak.xxx.com`, you can choose:
1. Remove the DENY policy and use only ALLOW policy:
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: policy
  namespace: istio-system
spec:
  action: ALLOW
  rules:
   # The 1st rule is converted from the original DENY policy, only IP from x.x.x.x is allowed to access someservice.xxx.com
  - from:
    - source:
        remoteIpBlocks:
        - x.x.x.x
    to:
    - operation:
        hosts:
        - someservice.xxx.com
  # The 2nd rule is also for the original DENY policy, anyone can access hosts other than someservice.xxx.com
  - to:
    - operation:
        notHosts:
        - someservice.xxx.com
  # The 3rd rule to exclude the keycloak.xxx.com, you may don't need this if the request is already allowed by the 2nd rule
  - when:
     - key: "connection.sni"
       values: ["keycloak.xxx.com"]
  selector:
    matchLabels:
      app: istio-ingressgateway
```

2. or if you cannot remove the deny policy, you can do the following, note how it uses the `notValues` in the DENY policy to exclude keycloak.xxx.com

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: policy
  namespace: istio-system
spec:
  action: DENY
  rules:
  - from:
    - source:
        notRemoteIpBlocks:
        - x.x.x.x
    to:
    - operation:
        hosts:
        - someservice.xxx.com
    when:
     - key: "connection.sni"
       notValues: ["keycloak.xxx.com"]
  selector:
    matchLabels:
      app: istio-ingressgateway
```

**Comment by haohaolee** [comment]
@yangminzhu 
Thanks very much, now it works with the 1st suggestion. I have a final question about authorization policy. Why does the following policy:
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: policy
  namespace: istio-system
spec:
  action: DENY
  rules:
  - from:
    - source:
        notRemoteIpBlocks:
        - x.x.x.x
    to:
    - operation:
        hosts:
        - someservice.xxx.com
  selector:
    matchLabels:
      app: istio-ingressgateway
```
match all the traffic? Even it is not going to someservice.xxx.com. I thought it would only deny the traffic with all conditions satisfied (from and to).
