### ISSUE TITLE
service-apis HTTPRoute with weight 100 does not add header in rules.forwardTo.filters.requestHeaderModifier

### ISSUE THREAD

**Issue by nak3** [istio/istio#29111]
**Bug description**

- `requestHeaderModifier` does not work when `weight 100` is in the filters.

**Affected product area (please put an X in all that apply)**

[X] Networking

**Expected behavior**

- Following HTTPRoute adds `foo: bar` header. Please see reproduce steps below.

```
cat <<EOF | kubectl apply -f -
apiVersion: networking.x-k8s.io/v1alpha1
kind: HTTPRoute
metadata:
  name: test
  namespace: gateway-demo
spec:
  gateways:
    allow: SameNamespace
  hostnames:
  - "*"
  rules:
  - forwardTo:
    - filters:
      - requestHeaderModifier:
          add:
            foo: bar
        type: RequestHeaderModifier
      port: 8000
      serviceName: foo-svc
      weight: 100
    matches:
    - path:
        type: Prefix
        value: /
EOF
```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

```
$ istioctl version
client version: 1.8.0
control plane version: 1.8.0
data plane version: 1.8.0 (1 proxies)
```

**Steps to reproduce the bug**

<details>
<summary>1. deploy httpbin svc (named foo)</summary>

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Namespace
metadata:
  name: gateway-demo
---
apiVersion: networking.x-k8s.io/v1alpha1
kind: GatewayClass
metadata:
  name: istio
spec:
  controller: istio.io/gateway-controller
---
kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: simple-gateway
  namespace: gateway-demo
spec:
  gatewayClassName: istio
  listeners:  # Use GatewayClass defaults for listener definition.
  - protocol: HTTP
    port: 80
    routes:
      kind: HTTPRoute
      namespaces:
        from: "All"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
  namespace: gateway-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - name: whereami
        image: docker.io/kennethreitz/httpbin
        ports:
          - containerPort: 80
        env:
        - name: METADATA
          value: "foo"
---
apiVersion: v1
kind: Service
metadata:
  name: foo-svc
  namespace: gateway-demo
spec:
  selector:
    app: foo
  ports:
  - port: 8000
    targetPort: 80
EOF
```
</details>

<details>
<summary>2. deploy HTTPRoute with header</summary>

```
cat <<EOF | kubectl apply -f -
apiVersion: networking.x-k8s.io/v1alpha1
kind: HTTPRoute
metadata:
  name: test
  namespace: gateway-demo
spec:
  gateways:
    allow: SameNamespace
  hostnames:
  - "*"
  rules:
  - forwardTo:
    - filters:
      - requestHeaderModifier:
          add:
            foo: bar
        type: RequestHeaderModifier
      port: 8000
      serviceName: foo-svc
      weight: 100
    matches:
    - path:
        type: Prefix
        value: /
EOF
```
</details>

3. Access to the svc (Header `foo:bar` is not added).

```
$ curl  $INGRESS_IP/headers
{
  "headers": {
    "Accept": "*/*",
    "Content-Length": "0",
    "Host": "xxxxxxx.ap-southeast-1.elb.amazonaws.com",
    "User-Agent": "curl/7.65.3",
    "X-B3-Sampled": "0",
    "X-B3-Spanid": "babf933bbf4a88d3",
    "X-B3-Traceid": "a5615f9a04bf1322babf933bbf4a88d3",
    "X-Envoy-Attempt-Count": "1",
    "X-Envoy-Decorator-Operation": "foo-svc.gateway-demo.svc.cluster.local:8000/*",
    "X-Envoy-Internal": "true",
    "X-Envoy-Peer-Metadata": "ChQKDkFQUF9DT05UQUlORVJTEgIaAAoaCgpDTFVTVEVSX0lEEgwaCkt1YmVybmV0ZXMKGAoNSVNUSU9fVkVSU0lPThIHGgUxLjguMAqbAwoGTEFCRUxTEpADKo0DCh0KA2FwcBIWGhRpc3Rpby1pbmdyZXNzZ2F0ZXdheQoTCgVjaGFydBIKGghnYXRld2F5cwoUCghoZXJpdGFnZRIIGgZUaWxsZXIKNgopaW5zdGFsbC5vcGVyYXRvci5pc3Rpby5pby9vd25pbmctcmVzb3VyY2USCRoHdW5rbm93bgoZCgVpc3RpbxIQGg5pbmdyZXNzZ2F0ZXdheQoZCgxpc3Rpby5pby9yZXYSCRoHZGVmYXVsdAowChtvcGVyYXRvci5pc3Rpby5pby9jb21wb25lbnQSERoPSW5ncmVzc0dhdGV3YXlzCiEKEXBvZC10ZW1wbGF0ZS1oYXNoEgwaCjVmNmM5Yzg0NjkKEgoHcmVsZWFzZRIHGgVpc3Rpbwo5Ch9zZXJ2aWNlLmlzdGlvLmlvL2Nhbm9uaWNhbC1uYW1lEhYaFGlzdGlvLWluZ3Jlc3NnYXRld2F5Ci8KI3NlcnZpY2UuaXN0aW8uaW8vY2Fub25pY2FsLXJldmlzaW9uEggaBmxhdGVzdAovCgROQU1FEicaJWlzdGlvLWluZ3Jlc3NnYXRld2F5LTVmNmM5Yzg0Njktam00cTcKGwoJTkFNRVNQQUNFEg4aDGlzdGlvLXN5c3RlbQpdCgVPV05FUhJUGlJrdWJlcm5ldGVzOi8vYXBpcy9hcHBzL3YxL25hbWVzcGFjZXMvaXN0aW8tc3lzdGVtL2RlcGxveW1lbnRzL2lzdGlvLWluZ3Jlc3NnYXRld2F5ChcKEVBMQVRGT1JNX01FVEFEQVRBEgIqAAonCg1XT1JLTE9BRF9OQU1FEhYaFGlzdGlvLWluZ3Jlc3NnYXRld2F5",
    "X-Envoy-Peer-Metadata-Id": "router~172.20.40.62~istio-ingressgateway-5f6c9c8469-jm4q7.istio-system~istio-system.svc.cluster.local"
  }
}
```

4. If the service weight is not `100` like following (same config but just split to 50 and 50 wegiths), the header is added.

```
cat <<EOF | kubectl apply -f -
apiVersion: networking.x-k8s.io/v1alpha1
kind: HTTPRoute
metadata:
  name: test
  namespace: gateway-demo
spec:
  gateways:
    allow: SameNamespace
  hostnames:
  - "*"
  rules:
  - forwardTo:
    - filters:
      - requestHeaderModifier:
          add:
            foo: bar
        type: RequestHeaderModifier
      port: 8000
      serviceName: foo-svc
      weight: 50
    - filters:
      - requestHeaderModifier:
          add:
            foo: bar
        type: RequestHeaderModifier
      port: 8000
      serviceName: foo-svc
      weight: 50
    matches:
    - path:
        type: Prefix
        value: /
EOF
```

```
$ curl  $INGRESS_IP/headers
{
  "headers": {
    "Accept": "*/*",
    "Content-Length": "0",
    "Foo": "bar",
    "Host": "xxxxxxxxx.ap-southeast-1.elb.amazonaws.com",
    "User-Agent": "curl/7.65.3",
    "X-B3-Sampled": "0",
    "X-B3-Spanid": "9c8cb7daeb2a56e3",
    "X-B3-Traceid": "140392a06c994e899c8cb7daeb2a56e3",
    "X-Envoy-Attempt-Count": "1",
    "X-Envoy-Decorator-Operation": "test-istio-autogenerated-k8s-gateway:80/*",
    "X-Envoy-Internal": "true",
    "X-Envoy-Peer-Metadata": "ChQKDkFQUF9DT05UQUlORVJTEgIaAAoaCgpDTFVTVEVSX0lEEgwaCkt1YmVybmV0ZXMKGAoNSVNUSU9fVkVSU0lPThIHGgUxLjguMAqbAwoGTEFCRUxTEpADKo0DCh0KA2FwcBIWGhRpc3Rpby1pbmdyZXNzZ2F0ZXdheQoTCgVjaGFydBIKGghnYXRld2F5cwoUCghoZXJpdGFnZRIIGgZUaWxsZXIKNgopaW5zdGFsbC5vcGVyYXRvci5pc3Rpby5pby9vd25pbmctcmVzb3VyY2USCRoHdW5rbm93bgoZCgVpc3RpbxIQGg5pbmdyZXNzZ2F0ZXdheQoZCgxpc3Rpby5pby9yZXYSCRoHZGVmYXVsdAowChtvcGVyYXRvci5pc3Rpby5pby9jb21wb25lbnQSERoPSW5ncmVzc0dhdGV3YXlzCiEKEXBvZC10ZW1wbGF0ZS1oYXNoEgwaCjVmNmM5Yzg0NjkKEgoHcmVsZWFzZRIHGgVpc3Rpbwo5Ch9zZXJ2aWNlLmlzdGlvLmlvL2Nhbm9uaWNhbC1uYW1lEhYaFGlzdGlvLWluZ3Jlc3NnYXRld2F5Ci8KI3NlcnZpY2UuaXN0aW8uaW8vY2Fub25pY2FsLXJldmlzaW9uEggaBmxhdGVzdAovCgROQU1FEicaJWlzdGlvLWluZ3Jlc3NnYXRld2F5LTVmNmM5Yzg0Njktam00cTcKGwoJTkFNRVNQQUNFEg4aDGlzdGlvLXN5c3RlbQpdCgVPV05FUhJUGlJrdWJlcm5ldGVzOi8vYXBpcy9hcHBzL3YxL25hbWVzcGFjZXMvaXN0aW8tc3lzdGVtL2RlcGxveW1lbnRzL2lzdGlvLWluZ3Jlc3NnYXRld2F5ChcKEVBMQVRGT1JNX01FVEFEQVRBEgIqAAonCg1XT1JLTE9BRF9OQU1FEhYaFGlzdGlvLWluZ3Jlc3NnYXRld2F5",
    "X-Envoy-Peer-Metadata-Id": "router~172.20.40.62~istio-ingressgateway-5f6c9c8469-jm4q7.istio-system~istio-system.svc.cluster.local"
  }
}
```
As you can see above, `"Foo": "bar"` is in the header.
