### ISSUE TITLE
Applying environment variables to istio-operator deployment

### ISSUE THREAD

**Issue by ludovicbonivert** [istio/istio#29115]
**Bug description**

Hi

I install istio through IstioOperator resource. This deploys me several components including a istio-operator deployment resource (=The operator controller deployment)
I do want to add environment variables to this deployment, however I’m afraid that this deployment is controlled by the istioOperator resource. That’s why I would like to add environment variables to the istioOperator resource instead of the deployment.

Am I correct? Or can I add environment variables to the istio-operator deployment resource without worrying that it will be overriden at some point?

How could I apply environment variables to this deployment through the istioOperator resource? I could already add environment variables to the egressgateway,ingressgateway & pilot through following config 

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: {{ .Values.namespace }}
  name: istiocontrolplane
spec:
  profile: demo
  meshConfig:
    accessLogFile: "/dev/stdout"

  components:
    pilot:
      k8s:
        env:
        - name: **KUBERNETES_SERVICE_HOST**
          value: {{ .Values.KUBERNETES_SERVICE_HOST }}
        - name: **KUBERNETES_SERVICE_PORT**
          value: "443"
        replicaCount: {{ .Values.pilotReplicaCount }}
        resources:
          requests:
            cpu: 1000m #parameter to tweak
          limits:
            cpu: 2000m #parameter to tweak
    egressGateways:
    - name: istio-egressgateway
      enabled: true
      k8s:
        env:
        - name: **KUBERNETES_SERVICE_HOST**
          value: {{ .Values.KUBERNETES_SERVICE_HOST }}
        - name: **KUBERNETES_SERVICE_PORT**
          value: "443"
        replicaCount: {{ .Values.egressGatewayReplicaCount }}
        resources:
          requests:
            cpu: 200m #parameter to tweak
          limits:
            cpu: 500m #parameter to tweak
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        env:
        - name: **KUBERNETES_SERVICE_HOST**
          value: {{ .Values.KUBERNETES_SERVICE_HOST }}
        - name: **KUBERNETES_SERVICE_PORT**
          value: "443"
        serviceAnnotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
          service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "{{ .Values.loadBalancerSubnet }}"
        replicaCount: {{ .Values.ingressGatewayReplicaCount }}
        #hpaSpec:
        #  minReplicas: 1
        #  maxReplicas: 5
        resources:
          requests:
            cpu: 200m #parameter to tweak
          limits:
            cpu: 500m #parameter to tweak
        service:
          type: LoadBalancer
          loadBalancerIP: {{ .Values.loadBalancerIP }}
          ports:
            - name: status-port
              port: 15020
              targetPort: 15020
              protocol: TCP
            - name: http2
              port: 80
              targetPort: 8080
              protocol: TCP
            - name: https
              port: 443
              targetPort: 8443
              protocol: TCP
            - name: tls
              port: 15443
              targetPort: 15443
              protocol: TCP
            - name: tcp
              port: 31400
              targetPort: 31400
              protocol: TCP

```

[ ] Docs
[ X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

Istio 1.7

**How was Istio installed?**
IstioOperator

**Environment where bug was observed (cloud vendor, OS, etc)**

Azure Kubernetes Service
