### ISSUE TITLE
changes in delegate virtual service do not take effect

### ISSUE THREAD

**Issue by yingzhuivy** [istio/istio#29123]
**Bug description**

Suppose we have following setup:

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: foo
  namespace: foo
spec:
  hosts:
  - bar.bar
  http:
  - match:
    - sourceNamespace: foo
      sourceLabels:
        app: foo
    retries:
      attempts: 3
      retryOn: gateway-error
    delegate:
      name: bar
      namespace: bar
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: bar
  namespace: bar
spec:
  http:
  - route:
    - destination:
        host: bar.bar
      weight: 90
    - destination:
        host: bar-2.bar
      weight: 10
    timeout: 3s
```

When we change the bar virtual service, for example, change the weight from 90,10 to 80,20, routes are not updated on the foo sidecar proxy. (restarting the pod gets correct config.)

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
RDS & CDS should be pushed if delegate vs changes

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
1.6.11

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
