### ISSUE TITLE
Autoregistration for VMs doesn't work (doesn't associate endpoints with services)

### ISSUE THREAD

**Issue by christian-posta** [istio/istio#29151]
Using Istio 1.8, and enabling auto-registration, the WorkloadEntrys that get created by WorkloadGroup don't seem to have any labels set. 

This happens when using the `WorkloadGroup` created by 

```
istioctl x workload group create --name "${VM_APP}" --namespace "${VM_NAMESPACE}" --labels app="${VM_APP}" --serviceAccount "${SERVICE_ACCOUNT}" > workloadgroup.yaml
```

It also doesn't work if following the docs and manually creating the WorkloadGroup:

https://istio.io/latest/docs/reference/config/networking/workload-group/

In there it says: 

```
The set of labels will be associated with each workload instance during the bootstrap process,
```

But this is not the case.

If the labels are not included correctly, then a Service or ServiceEntry cannot pick them up.

/cc @stevenctl including you as this is slightly related to https://github.com/istio/istio/issues/29125

**Comment by stevenctl** [comment]
Currently we use labels sent via node metadata, and the labels field on the workload entry template. Will roll a PR shortly to close this gap.

**Comment by stevenctl** [comment]
The manual workaround for now is to edit your workload group and copy the labels to the template section like this:

```
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadGroup
metadata:
  name: cloud-vm
  namespace: vm-ns
spec:
  metadata:
    annotations: {}
    labels:
      app: cloud-vm
  template:
    ports: {}
    serviceAccount: vm-sa
+   labels:
+     app: cloud-vm

```
