### ISSUE TITLE
Set delayed_close_timeout default to 0s (Websockets unexpected close 1006 on Chrome)

### ISSUE THREAD

**Issue by beckyconning** [istio/istio#29172]
**Bug description**
With Firefox and Safari it the close frames seem to arrive fine and when connecting via NGINX or other setups it also seems to work fine but combination of Istio and Chrome causes websockets to close with `"wasclean": false` and a code of 1006. The closing frames don't seem to show up in Chrome with Istio.

Note this works fine without the "sidecar".

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
On Chrome websocket should close with 1000 or at least not 1006.

**Steps to reproduce the bug**
Run websockets and have the server terminate the connections with close frames.

```
apiVersion: v1
kind: Service
metadata:
  name: precog
  labels:
    app: precog
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: precog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: precog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: precog
      version: v1
  template:
    metadata:
      labels:
        app: precog
        version: v1
    spec:
      imagePullSecrets:
      - name: myregistrykey
      containers:
      - name: precog
        image: precog/pro:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: precog-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: precog
spec:
  hosts:
  - "*"
  gateways:
  - precog-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: precog
      weight: 100
```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
client version: 1.8.0
control plane version: 1.8.0
data plane version: 1.8.0 (2 proxies)

**How was Istio installed?**
istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
MacOS, Linux, Windows

Additionally, please consider running `istioctl bug-report` and attach the generated
cluster-state

 tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
for more details.
[bug-report.tar.gz](https://github.com/istio/istio/files/5592936/bug-report.tar.gz)

**Comment by beckyconning** [comment]
<img width="1536" alt="Screenshot 2020-11-25 at 01 16 21" src="https://user-images.githubusercontent.com/457901/100170271-29357d00-2ebd-11eb-91cc-76b4e94359b7.png">
<img width="1536" alt="Screenshot 2020-11-25 at 01 16 28" src="https://user-images.githubusercontent.com/457901/100170277-2cc90400-2ebd-11eb-938c-9f95fbca98cb.png">

The one labelled 1 is without the sidecar, the one labelled 2 is with, notice the order of the final dance is reversed.

**Comment by beckyconning** [comment]
Probably caused by the large delay with the sidecar? I wonder if it would have responded.

**Comment by beckyconning** [comment]
Seems like Envoy has default behaviour quite different from a normal network connection. Creating / applying the following resolves the issue. I understand the need for the delayed_close_timeout and I think its super useful I think `"0s"` is a preferable default.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: cool
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:      
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager"
          delayed_close_timeout: "0s"
```

**Comment by beckyconning** [comment]
Hi! This has caused major issues for many users. At the very least this unusual default behaviour should be clearly documented if not resolved by making the config I posted above default.

**Comment by rvennam** [comment]
+1 we had a couple of users hit this and spent a lot of time debugging. cc: @GregHanson

**Comment by ramaraochavali** [comment]
We can probably add a env var to pilot that defaults to the current 1000ms and users can set it to 0s if needed - just not break any existing users.

**Comment by jhart1685** [comment]
Cross-referencing this to https://github.com/istio/istio/issues/30577 

I'm interested in whether a default value of "0s" is safe. 

We got burnt by the 1s default, and are trying different alternative values. We've found that setting it to 600s causes us other problems downstream; connection hangs, presumably due to other code that isn't closing connections cleanly but was previously getting away with it. 
Wouldn't a default value of "0s" also have that effect?

We've mitigated these side-effects by adding a `workloadSelector` to our EnvoyFilter, to limit our custom `delayed_close_timeout` to ingress pods, and avoid it destabilising other parts of our environment.

**Comment by beckyconning** [comment]
0s appears to behave the most like a normal network connection. Systems that work with a normal connection will continue to work with 0s timeout.

**Comment by ramaraochavali** [comment]
It is difficult to set a very sensible default given the wide variety of usecase. However now you can set `PILOT_HTTP_DELAYED_CLOSE_TIMEOUT` to the value you need.

**Comment by sneko** [comment]
Hi @beckyconning ,

I indeed saw some issues mentioning the `EOF` error and I'm currently facing this. I tried your `EnvoyFilter` but it does not change anything on my end.

Whereas I made sure I use the right syntax for my Istio version `v1.6.X` (2 exist):
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: hack-to-fix-delayedclosetimeout
  namespace: istio-system
spec:
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager"
            delayed_close_timeout: "0s"
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: hack-to-fix-delayedclosetimeout-istio-upper-version
  namespace: istio-system
spec:
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
            delayed_close_timeout: 0s
# https://istio.io/v1.6/docs/reference/config/networking/envoy-filter/
# https://istio.io/latest/docs/reference/config/networking/envoy-filter/
```

I cannot explain why it has no effect. I made sure to try my deployments without the Istio injection, and I have no `EOF` errors for hours whereas with Istio sidecars I have them just by waiting a few minutes (making like 1 request/second).

I'm downloading `.tar.gz` of only a few KB, this should not be a burden for sidecars... that's why I'm thinking about a `delayed_close_timeout` issue.

Is there anything to do? Or something you advise me to investigate?

Thank you,

cc @ramaraochavali
