### ISSUE TITLE
istio 1.8.0, --set values.gateways.istio-ingressgateway.sds.enabled=true is not supported

### ISSUE THREAD

**Issue by hillbun** [istio/istio#29186]
```
./bin/istioctl manifest generate --set profile=demo \
> --set values.gateways.istio-ingressgateway.sds.enabled=true \
> > ./generated.yaml
Run the command with the --force flag if you want to ignore the validation error and proceed.
Error: unknown field "sds" in v1alpha1.IngressGatewayConfig
```

How to fix it?  thanks.

**Comment by howardjohn** [comment]
This is working as intended, SDS is no longer optional and is always enabled. Please refer to the upgrade notes between versions if you are upgrading, as various settings are deprecated from time to time like this one (long ago, in 1.5 I think)

**Comment by seaurching** [comment]
as well as it always enabled. I setting an gateway with https and virtualservice, but it is not working with https.why?

**Comment by seaurching** [comment]
> This is working as intended, SDS is no longer optional and is always enabled. Please refer to the upgrade notes between versions if you are upgrading, as various settings are deprecated from time to time like this one (long ago, in 1.5 I think)
as well as it always enabled. I setting an gateway with https and virtualservice, but it is not working with https.why?

**Comment by jscontreras** [comment]
@seaurching This is not working on https. I can confirm. I followed this procedure with Istio 1.9.1 and It doesn't work for https.

**Comment by seaurching** [comment]
> @seaurching This is not working on https. I can confirm. I followed this procedure with Istio 1.9.1 and It doesn't work for https.

So do I. It's same as your. I use version 1.8.4.The configuration is:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: nginxhttps
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: ngxhttp
        protocol: HTTP
      hosts:
        - "https.magicdatatech.com"
      tls:
        httpsRedirect: true
        minProtocolVersion: TLS_AUTO
        maxProtocolVersion: TLS_AUTO
    - port:
        number: 443
        name: ngxhttps
        protocol: HTTPS
      hosts:
        - "https.magicdatatech.com"
      tls:
        mode: SIMPLE
        maxProtocolVersion: TLS_AUTO
        minProtocolVersion: TLS_AUTO
        credentialName: "magicdatatech"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-ngx
spec:
  hosts:
    - "https.magicdatatech.com"
  gateways:
    - nginxhttps
  tls:
    - match:
        - sniHosts:
            - "https.magicdatatech.com"
      route:
        - destination:
            host: my-nginx.default.svc.cluster.local
            port:
              number: 443
            subset: v1
---
kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: https
spec:
  host: my-nginx.default.svc.cluster.local
  subsets:
    - labels:
        app: nginx
      name: v1

```
