### ISSUE TITLE
Istio Operator Update Error with nodeSeletor

### ISSUE THREAD

**Issue by jmyung** [istio/istio#29188]
**Bug description**
If I change nodeSelector to another in `IstioOperator`, it was not changed to new, but just added to previous one.

IstioOperator
- before
```
  components:
    ingressGateways:
    - enabled: false
      name: istio-ingressgateway
      k8s:
        nodeSelector:
          disktype: ssd
```
- after
```
  components:
    ingressGateways:
    - enabled: false
      name: istio-ingressgateway
      k8s:
        nodeSelector:
          kubernetes.io/hostname: master
```
- result
```
$ kubectl get po istio-ingressgateway-665fcb97f-5wcdp -oyaml

apiVersion: v1
kind: Pod
metadata:
  annotations:
  ...
  nodeSelector:
    disktype: ssd          # <--- this should be removed
    kubernetes.io/hostname: master
```

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

```
$ istioctl version --remote
client version: 1.7.4
control plane version: 1.7.4
data plane version: 1.7.4 (2 proxies)

$ kubectl version --short
Client Version: v1.17.3
Server Version: v1.17.3
```

**How was Istio installed?**
Istio Operator Install
