### ISSUE TITLE
[1.8.0] New Envoy inbound cluster name format can lead to duplicated cluster issue

### ISSUE THREAD

**Issue by Laci21** [istio/istio#29199]
**Bug description**

I have a pod with two containers in it and using two different container ports. I have two services, both selecting the same pod, but the first service is targeting the first container and the second service is targeting the second container.

No matter which of those services I'm calling **always the same container will receive the request** in the pod.

[x] Docs
[x] Networking
[x] User Experience

**Expected behavior**

I would like to be able to route to both containers inside the pod, just like it was working before Istio 1.8.0.

**Steps to reproduce the bug**

1. Make sure that you install the following deployment (and services) to a namespace where istio injection is enabled:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  labels:
    k8s-app: echo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: echo
  template:
    metadata:
      labels:
        k8s-app: echo
    spec:
      terminationGracePeriodSeconds: 2
      containers:
      - name: echo-backend
        image: k8s.gcr.io/echoserver:1.10
        ports:
        - containerPort: 8080
      - name: echo-frontend
        image: k8s.gcr.io/echoserver:1.10
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: echo-backend
  labels:
    k8s-app: echo
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    k8s-app: echo
---
apiVersion: v1
kind: Service
metadata:
    name: echo-frontend
    labels:
        k8s-app: echo
    namespace: default
spec:
    ports:
    - name: http
      port: 80
      targetPort: 8081
    selector:
        k8s-app: echo
```

You should see in the `istiod` logs the following warning right away:
```
    "pilot_duplicate_envoy_clusters": {
        "inbound|80||": {
            "proxy": "echo-6dbb78ddc4-wr4bq.default",
            "message": "Duplicate cluster inbound|80|| found while pushing CDS"
        }
    }
```

1. Run a curl pod e.g. with: `kubectl run curl-test --image=radial/busyboxplus:curl -i --tty --rm`

1. Inside the curl pod, run: `curl echo-frontend.default.svc.cluster.local:80` and `curl echo-backend.default.svc.cluster.local:80`

1. If you check the logs of the echo pod's two app containers (`echo-frontend` and `echo.backend`) you should see that both calls went to the same container (instead of one request to each)

**Additional info**

If you check the config dump with something like `kubectl port-forward echo-6dbb78ddc4-wr4bq 15000`, you will only see this cluster:
```
      "load_assignment": {
       "cluster_name": "inbound|80||",
       "endpoints": [
        {
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "127.0.0.1",
              "port_value": 8080
             }
            }
           }
          }
         ]
        }
```

In older versions the config dump looked like this and this bug was not present:
```
      "load_assignment": {
       "cluster_name": "inbound|80|http|echo-backend.default.svc.cluster.local",
       "endpoints": [
        {
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "127.0.0.1",
              "port_value": 8080
             }
            }
           }
          }
         ]
        }
...
      "load_assignment": {
       "cluster_name": "inbound|80|http|echo-frontend.default.svc.cluster.local",
       "endpoints": [
        {
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "127.0.0.1",
              "port_value": 8081
             }
            }
           }
          }
         ]
        }
```

So to us it seems like this deliberate [inbound cluster name format change](https://istio.io/latest/news/releases/1.8.x/announcing-1.8/upgrade-notes/#inbound-cluster-name-format) is causing issues in this case.
Related PR: https://github.com/istio/istio/pull/27303. cc @howardjohn 

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

```
$ istioctl version --remote
client version: 1.7.3
control plane version: 1.8.0
data plane version: 1.8.0 (33 proxies)
```

```
$ kubectl version --short
Client Version: v1.18.5
Server Version: v1.18.6
```

**How was Istio installed?**

Installed by [Backyards](https://banzaicloud.com/products/backyards/), which installs Istio using the [Banzai Cloud Istio operator](https://github.com/banzaicloud/istio-operator). I did only one tweak regarding the installation, which is that I changed the Docker image for `istiod` to the upstream image to recreate this issue: `docker.io/istio/pilot:1.8.0`. The issue should happen with any other Istio 1.8.0 installation.

**Environment where bug was observed (cloud vendor, OS, etc)**

K8s cluster: Amazon [PKE](https://github.com/banzaicloud/pke) 1.18.6
OS image: `Ubuntu 18.04.4 LTS`
Kernel version: `4.15.0-1065-aws`
Container runtime: `containerd://1.3.3`
