### ISSUE TITLE
Enable istio to use external monitoring system

### ISSUE THREAD

**Issue by gyliu513** [istio/istio#2920]
Isito now has its build-in monitoring framework with Prometheus, Grafana etc, it is better to enable the customer have some configuration in istio to enable it can use external monitoring systems.

One solution is that we can update the helm charts by adding parameters to connect to external monitoring frameworks.

/cc @linsun @todkap

**Comment by linsun** [comment]
Don't you also need mixer adapter for the external monitoring system if the adapter doesn't exist?  I agree with you to allow users to configure this via helm charts.

**Comment by todkap** [comment]
Some additional background.   There are scenarios where a given platform already has provided their own logging stack with the same components Istio documents such as Prometheus (https://istio.io/docs/tasks/telemetry/metrics-logs.html).  It would be ideal if Istio could integrate with existing platform services while also providing users an easy way to do more of a step by step where none of the Istio logging services exist in the platform.

**Comment by gyliu513** [comment]
Yes, we need to update external Prometheus to scrape data from istio.

```
  - job_name: 'istio-mesh'
     scrape_interval: 5s
     static_configs:
     - targets: ['istio-mixer.istio-system:42422']

   - job_name: 'envoy'
     scrape_interval: 5s
     static_configs:
     - targets: ['istio-mixer.istio-system:9102']

   - job_name: 'mixer'
     scrape_interval: 5s
     static_configs:
     - targets: ['istio-mixer.istio-system:9093']
```
