### ISSUE TITLE
Header matching by VirtualService does not work in mesh pod-to-pod communication with holdApplicationUntilProxyStarts

### ISSUE THREAD

**Issue by sho-abe** [istio/istio#29215]
**Bug description**

When `holdApplicationUntilProxyStarts` is enabled and VirtualService is configured with header match traffic, it seem that header match is not working in mesh pod-to-pod communication.

When accessing via istio-ingressgatway, header matching works according to the settings of VirtualService, so I think that Istio has been set up correctly.
Also, when I installed Istio without enabling `holdApplicationUntilProxyStarts`, pod-to-pod communication in mesh works as expected with the same VirtualService settings.

I think that enabling `holdApplicationUntilProxyStarts` has some negative effect on the VirtualService settings.

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Header matching by VirtualService is effective in communication between pods of mesh with `holdApplicationUntilProxyStarts` enabled.

**Steps to reproduce the bug**

1. Create GKE Cluster
2. Set up Istio with holdApplicationUntilProxyStarts
```
istioctl install \
  --set profile=demo \
  --set components.cni.namespace=kube-system \
  --set values.cni.cniBinDir="/home/kubernetes/bin" \
  --set values.global.proxy.holdApplicationUntilProxyStarts=true
```
3. Apply test applications
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-v1
spec:
  selector:
    matchLabels:
      app: test
      version: v1.0.0
  template:
    metadata:
      labels:
        app: test
        version: v1.0.0
    spec:
      containers:
        - name: test
          image: gcr.io/google-samples/hello-app:1.0
          resources:
            limits:
              cpu: 300m
              memory: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-v2
spec:
  selector:
    matchLabels:
      app: test
      version: v2.0.0
  template:
    metadata:
      labels:
        app: test
        version: v2.0.0
    spec:
      containers:
        - name: test
          image: gcr.io/google-samples/hello-app:2.0
          resources:
            limits:
              cpu: 300m
              memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: test-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      name: http-test
  selector:
    app: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug
spec:
  selector:
    matchLabels:
      app: debug
  template:
    metadata:
      labels:
        app: debug
    spec:
      containers:
        - name: debug
          image: nginx:latest
```
4. Apply Gateway,DestinationRule,VirtualService resource
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: test-app-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: test-app
spec:
  host: test-app.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
    - name: v1
      labels:
        version: v1.0.0
    - name: v2
      labels:
        version: v2.0.0
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: test-app
spec:
  hosts:
    - "test-app"
    - "test-app.default.svc.cluster.local"
  gateways:
    - mesh
  http:
    - route:
        - destination:
            host: test-app.default.svc.cluster.local
            port:
              number: 80
            subset: v1
          weight: 100
      match:
        - headers:
            x-request-version:
              exact: v1.0
    - route:
        - destination:
            host: test-app.default.svc.cluster.local
            port:
              number: 80
            subset: v2
          weight: 100
      match:
        - headers:
            x-request-version:
              exact: v2.0
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: test-app-ext
spec:
  hosts:
    - "*"
  gateways:
    - test-app-gateway
  http:
    - match:
        - headers:
            x-request-version:
              exact: v1.0
      route:
        - destination:
            host: test-app.default.svc.cluster.local
            port:
              number: 80
            subset: v1
          weight: 100
    - match:
        - headers:
            x-request-version:
              exact: v2.0
      route:
        - destination:
            host: test-app.default.svc.cluster.local
            port:
              number: 80
            subset: v2
          weight: 100
```
5. Access test-app
```
## Test via istio-ingressgateway
$ kubectl get svc -n istio-system -l istio=ingressgateway
NAME                   TYPE           CLUSTER-IP    EXTERNAL-IP   PORT(S)                                                                      AGE
istio-ingressgateway   LoadBalancer   10.22.0.167   XX.XXX.XXX.XXX   15021:31633/TCP,80:31060/TCP,443:31183/TCP,31400:31936/TCP,15443:30900/TCP   143m
$ curl XX.XXX.XXX.XXX
## Expected: Access NG via ingressgateway without Header.
$ curl XX.XXX.XXX.XXX -H "x-request-version: v1.0"
$ curl XX.XXX.XXX.XXX -H "x-request-version: v2.0"
## Expected: Access OK via ingressgateway with Header.

## Test via mesh internal
$ kubectl get pod | grep debug
debug-7d75cc4986-lnmfs     2/2     Running   0          127m
$ kubectl exec debug-7d75cc4986-lnmfs -it -- /bin/bash
$ curl test-app
## Unexpected behavior: Access OK without header.
$ curl test-app -H "x-request-version: v1.0"
$ curl test-app -H "x-request-version: v2.0"
## Unexpected behavior: Access OK,  but the header match doesn't work.
```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

```
istioctl version --remote
client version: 1.8.0
control plane version: 1.8.0
data plane version: 1.8.0 (5 proxies)
```
```
kubectl version --short
Client Version: v1.19.3
Server Version: v1.16.13-gke.404
```

**How was Istio installed?**

```
istioctl install \
  --set profile=demo \
  --set components.cni.namespace=kube-system \
  --set values.cni.cniBinDir="/home/kubernetes/bin" \
  --set meshConfig.defaultConfig.holdApplicationUntilProxyStarts=true
```

**Environment where bug was observed (cloud vendor, OS, etc)**
* Cloud Vendor: Google Cloud Platform
* Platform: GKE 1.16.13
* OS: COS_CONTAINERD

Additionally, please consider running `istioctl bug-report` and attach the generated
cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
for more details.
