### ISSUE TITLE
DNS Capture breaks DNS Resolution for VMs

### ISSUE THREAD

**Issue by rinormaloku** [istio/istio#29224]
**Bug description**

While using the new DNS Capture feature, I hit the 2 bugs below (lmk if I should create separate issues)

**1. When installing Istio with the DNS Capture feature enabled the DNS resolution for public domains fails in VMs.**

To test this ssh into a **fresh** VM and:
```
# querying public domain works before starting istio agent
curl jsonplaceholder.typicode.com/users

# start agent
sudo systemctl start istio

# resolution fails
curl jsonplaceholder.typicode.com
```

**Expected behavior:** The DNS resolution should continue to work for public domains
**Actual behavior:** Public domains are not resolved

---

**2. Explicitly allowing access to an external domain using ServiceEntries, is not reliable.**

I tried to work around the first issue by specifying the ServiceEntry below:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: jsontime-entry
spec:
  hosts:
  - time.jsontest.com
  ports:
  - number: 80
    name: http-port
    protocol: HTTP
  resolution: DNS
```

That **worked for a short period!** Weirdly, the DNS resolution broke after some time passed. Envoy logs below show that the domain was resolved to the IP `216.58.208.115` for the succeeding requests and after some elapsed time all requests failed and the dns was resolved to `240.240.0.1` (or was not resolved).
```
# successful
[2020-11-26T22:12:07.908Z] "GET / HTTP/1.1" 200 [...] "time.jsontest.com" "216.58.208.115" outbound|80||time.jsontest.com 10.0.0.4:54530 240.240.0.1:80 10.0.0.4:47738 - default

# failed
[2020-11-26T22:30:12.587Z] "GET /users HTTP/1.1" 503 LR [...] "time.jsontest.com" "240.240.0.1:80" outbound|80||time.jsontest.com - 240.240.0.1:80 10.0.0.4:48562 - default
```

**Expected behavior:**  ServiceEntries are stable
**Actual behavior:**  ServiceEntries are not stable

**Important note:** Pods are not impacted by any of the above issues.

---

[x] Environments

[x] DNS Capture
[x] Virtual Machine

**Environment**
Istio 1.8, Azure AKS Kubernetes Version 1.18.10,
