### ISSUE TITLE
istio ingress gateway not working with other port except 80

### ISSUE THREAD

**Issue by btwseeu78** [istio/istio#29228]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
ingress gateway should work on other ports rather than 80

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ *] Networking
[ *] Performance and Scalability
[ *] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
istioctl version --remote
client version: 1.7.4
control plane version: 1.7.4
data plane version: 1.7.4 (4 proxies)

**How was Istio installed?**
via istio operator

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated
cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
for more details.
D:\E2EDeployment\exposegrafana.yaml

**Comment by btwseeu78** [comment]
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kiali-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-kiali
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali-vs
  namespace: istio-system
spec:
  hosts:
  - "*"
  gateways:
  - kiali-gateway
  http:
  - match:
    - uri:  # IF
        prefix: "/kiali"
    route:
    - destination:
        host: kiali
        port:
          number: 20001
  - match:
    - uri:
        prefix: "/grafna"
    route:
    - destination:
        host: grafana
        port:
          number: 3000
        
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: kiali
  namespace: istio-system
spec:
  host: kiali
  trafficPolicy:
    tls:
      mode: DISABLE
...
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: grafana
  namespace: istio-system
spec:
  host: grafana
  trafficPolicy:
    tls:
      mode: DISABLE
...
```
