### ISSUE TITLE
service-apis HTTPRoute gets 503 error when clusterDomain was changed from cluster.local

### ISSUE THREAD

**Issue by nak3** [istio/istio#29250]
**Bug description**

When clusterDomain was different from cluster.local like below, HTTPRoute stops working.

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      proxy:
        autoInject: disabled
        clusterDomain: foo.local
```

Note that the same deployments with default clusterDomain `cluster.local` works without any error.

[X] Networking

**Expected behavior**

- service-apis HTTPRoute works fine with the non-default cluster domain.

**Steps to reproduce the bug**

#### 1. Prepare k8s cluster with non-default cluster domain
<details>
<summary>2. Install Istio</summary>

For example, I am using the following manifest.
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      proxy:
        autoInject: disabled
        clusterDomain: cluster.local
      useMCP: false
      # The third-party-jwt is not enabled on all k8s.
      # See: https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens
      jwtPolicy: first-party-jwt
    pilot:
      autoscaleMin: 1
      autoscaleMax: 3
      cpu:
        targetAverageUtilization: 60
      env:
        PILOT_ENABLED_SERVICE_APIS: true

    gateways:
      istio-ingressgateway:
        autoscaleMin: 1
        autoscaleMax: 3
        type: NodePort

  addonComponents:
    pilot:
      enabled: true

  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
```

</details>

<details>
<summary>3. deploy Gateway,GatewayClass,HTTPRoute,Deployments</summary>

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Namespace
metadata:
  name: gateway-demo
---
apiVersion: networking.x-k8s.io/v1alpha1
kind: GatewayClass
metadata:
  name: istio
spec:
  controller: istio.io/gateway-controller
---
kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: simple-gateway
  namespace: gateway-demo
spec:
  gatewayClassName: istio
  listeners:  # Use GatewayClass defaults for listener definition.
  - protocol: HTTP
    port: 80
    routes:
      kind: HTTPRoute
      namespaces:
        from: "All"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
  namespace: gateway-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - name: whereami
        image: docker.io/kennethreitz/httpbin
        ports:
          - containerPort: 80
        env:
        - name: METADATA
          value: "foo"
---
apiVersion: v1
kind: Service
metadata:
  name: foo-svc
  namespace: gateway-demo
spec:
  selector:
    app: foo
  ports:
  - port: 8000
    targetPort: 80
---
apiVersion: networking.x-k8s.io/v1alpha1
kind: HTTPRoute
metadata:
  name: test
  namespace: gateway-demo
spec:
  gateways:
    allow: SameNamespace
  hostnames:
  - "*"
  rules:
  - forwardTo:
    - port: 8000
      serviceName: foo-svc
      weight: 100
    matches:
    - path:
        type: Prefix
        value: /
EOF
```
</details>

#### 4. Access to the service

It always gets 503.

```
$ curl $IP:$PORT/headers
  ...
* Mark bundle as not supporting multiuse
< HTTP/1.1 503 Service Unavailable
< date: Sun, 29 Nov 2020 11:38:57 GMT
< server: istio-envoy
< content-length: 0
```

**Version**

```
$ istioctl version
client version: 1.8.0
control plane version: 1.8.0
data plane version: 1.8.0 (1 proxies)
```

This is not a critical issue. Changing the default cluster domain (`cluster.loal`) is not common I think.
