### ISSUE TITLE
How to set docker registry for addonComponents

### ISSUE THREAD

**Issue by snowneji** [istio/istio#29283]
**Bug description**

I'm trying to install Istio on AKS under  our company environment, which means we need to refer the internal proxy of docker registries, and I'm following this link: [https://docs.microsoft.com/en-us/azure/aks/servicemesh-istio-install?pivots=client-operating-system-macos](https://docs.microsoft.com/en-us/azure/aks/servicemesh-istio-install?pivots=client-operating-system-macos) and [https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#IstioComponentSetSpec ](https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#IstioComponentSetSpec )

While constructing the IstioOperatorSpec, I'm able to get the basic to work with the `hub` argument, but I'm not able to point `addonComponents` such as grafana to the correct Docker Registry:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-control-plane
spec:
  hub: INTERNAL_DOCKER_HUB
  profile: default
  # Enable the addons that we will want to use
  addonComponents:
    grafana:
      enabled: true
      hub: INTERNAL_DOCKER_HUB

```

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade
