### ISSUE TITLE
Envoy external authorization filter is not call service without adding it to istio gateway

### ISSUE THREAD

**Issue by eddran** [istio/istio#29317]
**Bug description**
Hi, i just deployed simple http server deployment, service and meshed it to istio. I can access this service from other services as well. When i want to use this service for external authorization service, requests from envoy filter is not hit this service. 

But if i add this service as route to istio gateway, envoy filter can access to my service and validate request. Should we have to add it to gateway to work around ?

If so if i want to use grpc service instead of http service how can i add it to gateway ?

** **_Update_** **
_I tried with istio 1.6.14, it seems work but not work with istio 1.8.0_

**This is my http service deployment**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-http-deployment
  namespace: default
  labels:
    app: auth-http-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-http-deployment
      version: v1
  template:
    metadata:
      labels:
        app: auth-http-deployment
        version: v1
    spec:
      containers:
        - name: auth-http-deployment
          image: l4golas/istio-service-auth-http:v1
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "0.256"
              memory: "256Mi"
            limits:
              cpu: "0.512"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-http-service
  namespace: default
  labels:
    app: auth-http-service
    service: auth-http-service
spec:
  selector:
    app: auth-http-deployment
  ports:
    - port: 3000
      name: http
      targetPort: 3000
```

**This is my envoy filter**
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: authn-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
              subFilter:
                name: "envoy.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.ext_authz
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
            http_service:
              server_uri:
                uri: http://auth-http-service.default.svc.cluster.local
                cluster: outbound|3000||auth-http-service.default.svc.cluster.local
                timeout: 1.5s
              authorizationRequest:
                allowedHeaders:
                  patterns:
                    - exact: "cookie"
              authorizationResponse:
                allowedClientHeaders:
                  patterns:
                    - exact: "authorization"
                allowedUpstreamHeaders:
                  patterns:
                    - exact: "set-cookie"
                    - exact: "authorization"
```

_So this is not working but if i add gateway its working_
**Gateway File**
```
 apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name:site-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: auth-virtual
spec:
  hosts:
    - "*"
  gateways:
    - site-gateway
  http:
    - match:
        - uri:
            prefix: /auth
      rewrite:
        uri: /
      route:
        - destination:
            port:
              number: 3000
            host: auth-http-service
```

I do not want to people to access my auth service form outside. It should be accessible only from inside cluster.

Also i tried to use grpc service instead of http service but its not working too.

But adding it to gateway seems like trick point but how it can work with gprc service ?

[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Envoy filter should able to call my service.

**Steps to reproduce the bug**

**Version** 
istioctl version --remote
```
client version: 1.8.0
control plane version: 1.8.0
data plane version: 1.8.0 (5 proxies)
```

kubectl version --short
```
Client Version: v1.19.3
Server Version: v1.19.2
```

**How was Istio installed?**

istoctl is used.
My istio config
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  meshConfig:
    accessLogFile: /dev/stdout
```
**Environment where the bug was observed (cloud vendor, OS, etc)**
minikube
