### ISSUE TITLE
Could supports subsets by TrafficPolicy in destination-Rule?

### ISSUE THREAD

**Issue by wangfakang** [istio/istio#29322]
@howardjohn  plz help :D whether the [LB_subset_config](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/subsets) is supported by TrafficPolicy in destination-Rule? or have plans?

**Comment by howardjohn** [comment]
No, can you specify what your use case is?

**Comment by wangfakang** [comment]
> No, can you specify what your use case is?
We want to manage the traffic schedule of requests to the back end by the  [LB_subset_config](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/subsets) policy on the data plane. Such as
select back-end according to request metadata：
```
    lb_subset_config:
      fallback_policy: ANY_ENDPOINT
      subset_selectors:
      - keys:
        - idc
        - zone
        fallback_policy: KEYS_SUBSET
        fallback_keys_subset:
         - zone
      - keys:
        - idc
        fallback_policy: ANY_ENDPOINT
```
