### ISSUE TITLE
Ingress gateway occasionally hangs and stops accepting requests 

### ISSUE THREAD

**Issue by mvladev** [istio/istio#29334]
**Bug description**

On a multi-replica istio-ingressgateway, one envoy instance occasionally stops working and starts returning 503:

```
2020-12-02T00:20:00.824270Z	error	sds	Remote side closed connection
2020-12-02T00:21:51.571401Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 13, 
2020-12-02T00:50:18.686712Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 13, 
2020-12-02T00:57:01.991791Z	warning	envoy config	Ignoring unwatched type URL type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment
2020-12-02T00:57:01.993276Z	error	sds	Remote side closed connection
2020-12-02T01:18:17.912768Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 13, 
2020-12-02T01:48:31.841280Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 13, 
2020-12-02T02:18:09.391058Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 13, 
2020-12-02T02:46:28.092466Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 13, 
2020-12-02T03:16:55.024122Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 13, 
2020-12-02T03:46:34.438377Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 13, 
2020-12-02T03:53:33.162552Z	error	sds	Remote side closed connection
2020-12-02T03:54:54.530803Z	error	sds	Remote side closed connection
2020-12-02T03:55:19.667231Z	error	failed scraping envoy metrics: error scraping http://localhost:15090/stats/prometheus: Get "http://localhost:15090/stats/prometheus": context deadline exceeded
2020-12-02T03:55:19.668613Z	error	failed to write agent metrics: write tcp 10.243.132.32:15020->10.243.132.36:59528: write: broken pipe
2020-12-02T03:56:19.667755Z	error	failed scraping envoy metrics: error scraping http://localhost:15090/stats/prometheus: Get "http://localhost:15090/stats/prometheus": context deadline exceeded
2020-12-02T03:56:19.669019Z	error	failed to write agent metrics: write tcp 10.243.132.32:15020->10.243.132.36:54126: write: broken pipe
2020-12-02T03:57:19.667751Z	error	failed scraping envoy metrics: error scraping http://localhost:15090/stats/prometheus: Get "http://localhost:15090/stats/prometheus": context deadline exceeded
2020-12-02T03:57:19.669155Z	error	failed to write agent metrics: write tcp 10.243.132.32:15020->10.243.132.36:55150: write: broken pipe
2020-12-02T03:58:19.667631Z	error	failed scraping envoy metrics: error scraping http://localhost:15090/stats/prometheus: Get "http://localhost:15090/stats/prometheus": context deadline exceeded
2020-12-02T03:58:19.669000Z	error	failed to write agent metrics: write tcp 10.243.132.32:15020->10.243.132.36:56146: write: broken pipe
.... This continues until ....
2020-12-02T06:06:09.921290Z	error	failed scraping envoy metrics: error scraping http://localhost:15090/stats/prometheus, status code: 503
2020-12-02T06:07:09.916585Z	error	failed scraping envoy metrics: error scraping http://localhost:15090/stats/prometheus, status code: 503
2020-12-02T06:08:09.916912Z	error	failed scraping envoy metrics: error scraping http://localhost:15090/stats/prometheus, status code: 503
2020-12-02T06:09:09.916836Z	error	failed scraping envoy metrics: error scraping http://localhost:15090/stats/prometheus, status code: 503
2020-12-02T06:10:09.916933Z	error	failed scraping envoy metrics: error scraping http://localhost:15090/stats/prometheus, status code: 503
2020-12-02T06:11:09.916850Z	error	failed scraping envoy metrics: error scraping http://localhost:15090/stats/prometheus, status code: 503
````

[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Enovoy to not return 503 when scraping prometheus stats endpoint.

**Steps to reproduce the bug**

I've seen this error or multiple occasions in the past couple of weeks. I was not able to reliably reproduce the issue.
All Nodes in the cluster have been replaced to exclude VM issue, but after that it still persists from time to time. All other replicas work without an issue:

```console
$ kubectl -n istio-ingress top pods
NAME                                    CPU(cores)   MEMORY(bytes)
istio-ingressgateway-6ddcc556fb-6jf6d   21m          65Mi
istio-ingressgateway-6ddcc556fb-8bpvz   35m          63Mi
istio-ingressgateway-6ddcc556fb-9xstz   1007m        62Mi
istio-ingressgateway-6ddcc556fb-cf2gt   20m          65Mi
istio-ingressgateway-6ddcc556fb-w85c5   26m          64Mi
```

There is huge CPU spike at that time: 

<img width="753" alt="Screenshot 2020-12-02 at 20 21 55" src="https://user-images.githubusercontent.com/33343952/100914794-31547480-34dc-11eb-8727-7aa21fb8fb6b.png">

The offending replica `istio-ingressgateway-6ddcc556fb-9xstz` is using almost 50 times more CPU than the rest of the replicas.

You can find the envoy configuration bellow for `istio-ingressgateway`:

<details>
<summary><strong>envoy-rev0.yaml - click to expand</strong></summary>

```yaml
node:
  id: >-
    router~10.243.132.32~istio-ingressgateway-6ddcc556fb-9xstz.istio-ingress~istio-ingress.svc.cluster.local
  cluster: istio-ingressgateway
  locality: {}
  metadata:
    CLUSTER_ID: Kubernetes
    CONFIG_NAMESPACE: istio-ingress
    EXCHANGE_KEYS: >-
      NAME,NAMESPACE,INSTANCE_IPS,LABELS,OWNER,PLATFORM_METADATA,WORKLOAD_NAME,MESH_ID,SERVICE_ACCOUNT,CLUSTER_ID
    INSTANCE_IPS: 10.243.132.32
    ISTIO_PROXY_SHA: 'istio-proxy:745f989e4024e8e839de05f3c01b516fad69c278'
    ISTIO_VERSION: 1.7.2
    LABELS:
      app: istio-ingressgateway
      istio: ingressgateway
      pod-template-hash: 6ddcc556fb
      service.istio.io/canonical-name: istio-ingressgateway
      service.istio.io/canonical-revision: '1.7'
    MESH_ID: cluster.local
    NAME: istio-ingressgateway-6ddcc556fb-9xstz
    NAMESPACE: istio-ingress
    OWNER: >-
      kubernetes://apis/apps/v1/namespaces/istio-ingress/deployments/istio-ingressgateway
    POD_NAME: istio-ingressgateway-6ddcc556fb-9xstz
    PROXY_CONFIG:
      binaryPath: /usr/local/bin/envoy
      concurrency: 0
      configPath: ./etc/istio/proxy
      controlPlaneAuthPolicy: MUTUAL_TLS
      discoveryAddress: 'istiod.istio-system.svc:15012'
      drainDuration: 45s
      envoyAccessLogService: {}
      envoyMetricsService: {}
      parentShutdownDuration: 60s
      proxyAdminPort: 15000
      serviceCluster: istio-ingressgateway
      statNameLength: 189
      statusPort: 15020
      terminationDrainDuration: 5s
      tracing:
        zipkin:
          address: 'zipkin.istio-system:9411'
    ROUTER_MODE: sni-dnat
    SDS: 'true'
    SERVICE_ACCOUNT: istio-ingressgateway
    USER_SDS: 'true'
    WORKLOAD_NAME: istio-ingressgateway
layered_runtime:
  layers:
    - name: deprecation
      static_layer:
        'envoy.deprecated_features:envoy.config.listener.v3.Listener.hidden_envoy_deprecated_use_original_dst': true
    - name: admin
      admin_layer: {}
stats_config:
  use_all_default_tags: false
  stats_tags:
    - tag_name: cluster_name
      regex: ^cluster\.((.+?(\..+?\.svc\.cluster\.local)?)\.)
    - tag_name: tcp_prefix
      regex: ^tcp\.((.*?)\.)\w+?$
    - regex: '(response_code=\.=(.+?);\.;)|_rq(_(\.d{3}))$'
      tag_name: response_code
    - tag_name: response_code_class
      regex: _rq(_(\dxx))$
    - tag_name: http_conn_manager_listener_prefix
      regex: >-
        ^listener(?=\.).*?\.http\.(((?:[_.[:digit:]]*|[_\[\]aAbBcCdDeEfF[:digit:]]*))\.)
    - tag_name: http_conn_manager_prefix
      regex: '^http\.(((?:[_.[:digit:]]*|[_\[\]aAbBcCdDeEfF[:digit:]]*))\.)'
    - tag_name: listener_address
      regex: '^listener\.(((?:[_.[:digit:]]*|[_\[\]aAbBcCdDeEfF[:digit:]]*))\.)'
    - tag_name: mongo_prefix
      regex: ^mongo\.(.+?)\.(collection|cmd|cx_|op_|delays_|decoding_)(.*?)$
    - regex: (reporter=\.=(.*?);\.;)
      tag_name: reporter
    - regex: (source_namespace=\.=(.*?);\.;)
      tag_name: source_namespace
    - regex: (source_workload=\.=(.*?);\.;)
      tag_name: source_workload
    - regex: (source_workload_namespace=\.=(.*?);\.;)
      tag_name: source_workload_namespace
    - regex: (source_principal=\.=(.*?);\.;)
      tag_name: source_principal
    - regex: (source_app=\.=(.*?);\.;)
      tag_name: source_app
    - regex: (source_version=\.=(.*?);\.;)
      tag_name: source_version
    - regex: (source_cluster=\.=(.*?);\.;)
      tag_name: source_cluster
    - regex: (destination_namespace=\.=(.*?);\.;)
      tag_name: destination_namespace
    - regex: (destination_workload=\.=(.*?);\.;)
      tag_name: destination_workload
    - regex: (destination_workload_namespace=\.=(.*?);\.;)
      tag_name: destination_workload_namespace
    - regex: (destination_principal=\.=(.*?);\.;)
      tag_name: destination_principal
    - regex: (destination_app=\.=(.*?);\.;)
      tag_name: destination_app
    - regex: (destination_version=\.=(.*?);\.;)
      tag_name: destination_version
    - regex: (destination_service=\.=(.*?);\.;)
      tag_name: destination_service
    - regex: (destination_service_name=\.=(.*?);\.;)
      tag_name: destination_service_name
    - regex: (destination_service_namespace=\.=(.*?);\.;)
      tag_name: destination_service_namespace
    - regex: (destination_port=\.=(.*?);\.;)
      tag_name: destination_port
    - regex: (destination_cluster=\.=(.*?);\.;)
      tag_name: destination_cluster
    - regex: (request_protocol=\.=(.*?);\.;)
      tag_name: request_protocol
    - regex: (request_operation=\.=(.*?);\.;)
      tag_name: request_operation
    - regex: (request_host=\.=(.*?);\.;)
      tag_name: request_host
    - regex: (response_flags=\.=(.*?);\.;)
      tag_name: response_flags
    - regex: (grpc_response_status=\.=(.*?);\.;)
      tag_name: grpc_response_status
    - regex: (connection_security_policy=\.=(.*?);\.;)
      tag_name: connection_security_policy
    - regex: (permissive_response_code=\.=(.*?);\.;)
      tag_name: permissive_response_code
    - regex: (permissive_response_policyid=\.=(.*?);\.;)
      tag_name: permissive_response_policyid
    - regex: (source_canonical_service=\.=(.*?);\.;)
      tag_name: source_canonical_service
    - regex: (destination_canonical_service=\.=(.*?);\.;)
      tag_name: destination_canonical_service
    - regex: (source_canonical_revision=\.=(.*?);\.;)
      tag_name: source_canonical_revision
    - regex: (destination_canonical_revision=\.=(.*?);\.;)
      tag_name: destination_canonical_revision
    - regex: (cache\.(.+?)\.)
      tag_name: cache
    - regex: (component\.(.+?)\.)
      tag_name: component
    - regex: (tag\.(.+?);\.)
      tag_name: tag
    - regex: (wasm_filter\.(.+?)\.)
      tag_name: wasm_filter
  stats_matcher:
    inclusion_list:
      patterns:
        - prefix: reporter=
        - prefix: cluster_manager
        - prefix: listener_manager
        - prefix: http_mixer_filter
        - prefix: tcp_mixer_filter
        - prefix: server
        - prefix: cluster.xds-grpc
        - prefix: wasm
        - prefix: component
admin:
  access_log_path: /dev/null
  profile_path: /var/lib/istio/data/envoy.prof
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 15000
dynamic_resources:
  lds_config:
    ads: {}
    resource_api_version: V3
  cds_config:
    ads: {}
    resource_api_version: V3
  ads_config:
    api_type: GRPC
    transport_api_version: V3
    grpc_services:
      - envoy_grpc:
          cluster_name: xds-grpc
static_resources:
  clusters:
    - name: prometheus_stats
      type: STATIC
      connect_timeout: 0.250s
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: prometheus_stats
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      protocol: TCP
                      address: 127.0.0.1
                      port_value: 15000
    - name: agent
      type: STATIC
      connect_timeout: 0.250s
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: prometheus_stats
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      protocol: TCP
                      address: 127.0.0.1
                      port_value: 15020
    - name: sds-grpc
      type: STATIC
      http2_protocol_options: {}
      connect_timeout: 1s
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: sds-grpc
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    pipe:
                      path: ./etc/istio/proxy/SDS
    - name: xds-grpc
      type: STRICT_DNS
      respect_dns_ttl: true
      dns_lookup_family: V4_ONLY
      connect_timeout: 1s
      lb_policy: ROUND_ROBIN
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          '@type': >-
            type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          sni: istiod.istio-system.svc
          common_tls_context:
            alpn_protocols:
              - h2
            tls_certificate_sds_secret_configs:
              - name: default
                sds_config:
                  resource_api_version: V3
                  initial_fetch_timeout: 0s
                  api_config_source:
                    api_type: GRPC
                    transport_api_version: V3
                    grpc_services:
                      - envoy_grpc:
                          cluster_name: sds-grpc
            validation_context:
              trusted_ca:
                filename: ./var/run/secrets/istio/root-cert.pem
              match_subject_alt_names:
                - exact: istiod.istio-system.svc
      load_assignment:
        cluster_name: xds-grpc
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: istiod.istio-system.svc
                      port_value: 15012
      circuit_breakers:
        thresholds:
          - priority: DEFAULT
            max_connections: 100000
            max_pending_requests: 100000
            max_requests: 100000
          - priority: HIGH
            max_connections: 100000
            max_pending_requests: 100000
            max_requests: 100000
      upstream_connection_options:
        tcp_keepalive:
          keepalive_time: 300
      max_requests_per_connection: 1
      http2_protocol_options: {}
    - name: zipkin
      type: STRICT_DNS
      respect_dns_ttl: true
      dns_lookup_family: V4_ONLY
      connect_timeout: 1s
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: zipkin
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: zipkin.istio-system
                      port_value: 9411
  listeners:
    - address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 15090
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                '@type': >-
                  type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: AUTO
                stat_prefix: stats
                route_config:
                  virtual_hosts:
                    - name: backend
                      domains:
                        - '*'
                      routes:
                        - match:
                            prefix: /stats/prometheus
                          route:
                            cluster: prometheus_stats
                http_filters:
                  - name: envoy.router
                    typed_config:
                      '@type': >-
                        type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
    - address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 15021
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                '@type': >-
                  type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: AUTO
                stat_prefix: agent
                route_config:
                  virtual_hosts:
                    - name: backend
                      domains:
                        - '*'
                      routes:
                        - match:
                            prefix: /healthz/ready
                          route:
                            cluster: agent
                http_filters:
                  - name: envoy.router
                    typed_config:
                      '@type': >-
                        type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
tracing:
  http:
    name: envoy.zipkin
    typed_config:
      '@type': type.googleapis.com/envoy.config.trace.v3.ZipkinConfig
      collector_cluster: zipkin
      collector_endpoint: /api/v2/spans
      collector_endpoint_version: HTTP_JSON
      trace_id_128bit: true
      shared_span_context: false
```

</details>

There is additional `--config-yaml` flag with the following configuration

```yaml
layered_runtime:
  layers:
  - name: static_layer_0
    static_layer:
      overload:
        # Fix for https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-8663
        # https://istio.io/latest/news/security/istio-security-2020-007/
        global_downstream_max_connections: 750000
```

This is the output of `ps auxww`:

```console
istio-p+       1  0.0  0.2 784448 82728 ?        SLsl Dec01   1:06 /usr/local/bin/pilot-agent proxy router --domain=istio-ingress.svc.cluster.local --proxyLogLevel=warning --proxyComponentLogLevel=misc:error --log_output_level=all:warn,ads:error --drainDuration=45s --parentShutdownDuration=1m0s --connectTimeout=10s --serviceCluster=istio-ingressgateway --proxyAdminPort=15000 --statusPort=15021 --controlPlaneAuthPolicy=NONE --discoveryAddress=istiod.istio-system.svc:15012 --trust-domain=cluster.local
istio-p+      17 46.5  0.1 279160 59848 ?        Rl   Dec01 866:48 /usr/local/bin/envoy -c etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster istio-ingressgateway --service-node router~10.243.132.32~istio-ingressgateway-6ddcc556fb-9xstz.istio-ingress~istio-ingress.svc.cluster.local --local-address-ip-version v4 --log-format-prefix-with-location 0 --log-format %Y-%m-%dT%T.%fZ.%l.envoy %n.%v -l warning --component-log-level misc:error --config-yaml layered_runtime:   layers:   - name: static_layer_0     static_layer:       overload:         # Fix for https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-8663         # https://istio.io/latest/news/security/istio-security-2020-007/         global_downstream_max_connections: 750000
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```console
$ istioctl version --remote
control plane version: 1.7.2
data plane version: 1.7.2 (4 proxies)

$ kubectl version --short
Server Version: v1.17.12
```

**How was Istio installed?**

Custom installation based on helm manifests.

**Environment where the bug was observed (cloud vendor, OS, etc)**

- cloud provider AliCloud
- OS debian:bullseye

We have multiple installations on different cloud providers, but I've seen this error only on AliCloud.

I've tried to generate the bug-report, but it fails at:

```
The following fetches are still running:
  ProxyGet istio-ingress/istio-ingressgateway-6ddcc556fb-9xstz:certs
```
