### ISSUE TITLE
Virtual Service ambiguous http prefix name bug

### ISSUE THREAD

**Issue by paolodedo** [istio/istio#29343]
Hello,

Using

⚫**Istio v1.8⚫
🔵Kubernetes v1.19.3**🔵

I have found a bug during **Virtual Service** definition.

Basically, if I have 2 Virtual Services, one which exposes "/test" **http prefix** and the other "/test2" **http prefix**, only one Virtual Service is registered into Istio Gateway, the other is totally ignored, giving 404 response (when I remove the registered one, the unregistered gets now registered correctly, so they are auto-exclusive).
The things change if I assign 2 total different names (unfortunately, it has been very long and hard to find this bug).

Here are my files, containing deployments, services, virtual services, authorization policies, gateway and request authentication:

1) _First deployment with svc, vs, authorizationpolicy:_

```
apiVersion: v1
kind: Service
metadata:
  name: kc-istio-integr
  namespace: dev
  labels:
    app: kc-istio-integr
    service: kc-istio-integr
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: kc-istio-integr
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kc-istio-integr
  namespace: dev
spec:
  hosts:
  - "*"
  gateways:
  - test-gateway
  http:
    - match:
      - uri:
          prefix: /test                   // HERE
      route:
        - destination:
            port:
              number: 8080
            host: kc-istio-integr.dev.svc.cluster.local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kc-istio-integr
  namespace: dev
  labels:
    app: kc-istio-integr
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kc-istio-integr
      version: v1
  template:
    metadata:
      labels:
        app: kc-istio-integr
        version: v1
    spec:
      containers:
      - name: kc-istio-integr
        image: myimage
        imagePullPolicy: IfNotPresent
        env:
         - name: SERVICE.URL
           value: "http://kc-istio-integr-2:8080"
        ports:
        - containerPort: 8080
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: kc-istio-integr-authpolicy
 namespace: dev
spec:
 selector:
   matchLabels:
     app: kc-istio-integr
 rules:
 - to:
   - operation:
       methods: ["OPTIONS"]
       paths: ["*"]
 - to:
   - operation:
       methods: ["GET"]
       paths: ["/test*"]
   when:
   - key: request.auth.claims[realm_access][roles]
     values: ["ENTITY-READ"]
 - to:
   - operation:
       methods: ["POST", "PUT", "DELETE", "PATCH"]
       paths: ["/test*"]
   when:
   - key: request.auth.claims[realm_access][roles]
     values: ["ENTITY-WRITE"] 
```

2) _Second deployment with svc, vs, authorizationpolicy:_

```
apiVersion: v1
kind: Service
metadata:
  name: kc-istio-integr-2
  namespace: dev
  labels:
    app: kc-istio-integr-2
    service: kc-istio-integr-2
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: kc-istio-integr-2
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kc-istio-integr-2
  namespace: dev
spec:
  hosts:
  - "*"
  gateways:
  - test-gateway
  http:
    - match:
      - uri:
          prefix: /test2                  // HERE
      route:
        - destination:
            port:
              number: 8080
            host: kc-istio-integr-2.dev.svc.cluster.local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kc-istio-integr-2
  namespace: dev
  labels:
    app: kc-istio-integr-2
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kc-istio-integr-2
      version: v1
  template:
    metadata:
      labels:
        app: kc-istio-integr-2
        version: v1
    spec:
      containers:
      - name: kc-istio-integr-2
        image: myimage2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: kc-istio-integr-2-authpolicy
 namespace: dev
spec:
 selector:
   matchLabels:
     app: kc-istio-integr-2
 rules:
 - to:
   - operation:
       methods: ["OPTIONS"]
       paths: ["*"]
 - to:
   - operation:
       methods: ["GET"]
       paths: ["/test2*"]
   when:
   - key: request.auth.claims[realm_access][roles]
     values: ["ENTITY-READ"]
 - to:
   - operation:
       methods: ["POST", "PUT", "DELETE", "PATCH"]
       paths: ["/test2*"]
   when:
   - key: request.auth.claims[realm_access][roles]
     values: ["ENTITY-WRITE"]
```

3) _Gateway:_

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: test-gateway
  namespace: dev
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
```

4) _Request Authentication:_

```
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: test-reqauth
  namespace: dev
spec:
  jwtRules:
  - issuer: "http://keycloak/auth/realms/realm"
    jwksUri: "http://keycloak/auth/realms/realm/protocol/openid-connect/certs"
```

Thanks

**Comment by zufardhiyaulhaq** [comment]
We have the same setup, having two virtual services sometime make the route order broken. @paolodedo you can fix this by only have a single virtual service
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: combined-vs
  namespace: dev
spec:
  hosts:
  - "*"
  gateways:
  - test-gateway
  http:
    - match:
      - uri:
          prefix: /test2
      route:
        - destination:
            port:
              number: 8080
            host: kc-istio-integr-2.dev.svc.cluster.local
    - match:
      - uri:
          prefix: /test
      route:
        - destination:
            port:
              number: 8080
            host: kc-istio-integr.dev.svc.cluster.local
```
and place a more specific route on top of others.

or

you can apply virtual service with `/test2` before applying `/test` so it's got the correct order in envoy configuration.

@istio/wg-networking-maintainers this seems to happen also in 1.6.11. I check the route in envoy config dumps, route `/test2` seems to have a lower index number than `test`.
