### ISSUE TITLE
helm charts do not deploy in master on 1.7, 1.8, or 1.9 of Kubernetes

### ISSUE THREAD

**Issue by sdake** [istio/istio#2935]
```
sdake@falkor-07:~/go/src/istio.io/istio/install/kubernetes/helm$ helm install istio --name istio
Error: error unpacking initializer in istio: chart metadata (Chart.yaml) missing
```

**Comment by sdake** [comment]
Indeed the Chart.yaml file is missing from the initializer directory.

After placing a proper Chart.yaml in the initializer directory, a followup error is:
```
sdake@falkor-07:~/go/src/istio.io/istio/install/kubernetes/helm$ helm install --debug istio --name istio
[debug] Created tunnel using local port: '33769'

[debug] SERVER: "127.0.0.1:33769"

[debug] Original chart version: ""
[debug] CHART PATH: /home/sdake/go/src/istio.io/istio/install/kubernetes/helm/istio

Error: cannot load requirements: error unmarshaling JSON: json: cannot unmarshal array into Go value of type chartutil.Requirements
```

**Comment by sdake** [comment]
cc @linsun @luisyonaldo @lachie83 @sbezverk

**Comment by linsun** [comment]
I don't think we need the initializer dir, that dir should be removed.

**Comment by sdake** [comment]
I wasn't sure - I was OOO last week, so haven't kept up with the code base.

**Comment by luisyonaldo** [comment]
that was introduced by https://github.com/istio/istio/pull/2830

**Comment by luisyonaldo** [comment]
is not even a helm chart, is just a manifest definition inside the helm chart

**Comment by linsun** [comment]
With #2937, still failed with 

```
Error: render error in "istio/charts/sidecar-injector/templates/istio-sidecar-injector.yaml": template: istio/charts/sidecar-injector/templates/istio-sidecar-injector.yaml:2:14: executing "istio/charts/sidecar-injector/templates/istio-sidecar-injector.yaml" at <.Values.global.proxy...>: can't evaluate field debug in type interface {}``` 

will look into that next.

**Comment by sdake** [comment]
running `updateVersion.sh` (generating a new `values.yaml`) seems to move past the render error.

values.yaml does not properly seem to modify this tag.  I am unclear if this tag is necessary.
```
#
# initializer configuration
#
initializer:
  enabled: true
  serviceAccountName: default # used only if RBAC is not enabled
  replicaCount: 1
  imagePullPolicy: IfNotPresent
  resources: {}
  nodeSelector: {}

  initImage:
    repository: docker.io/istio/proxy_init
    tag: 0.4.0
```
