### ISSUE TITLE
Set environment variables in istio-proxy container

### ISSUE THREAD

**Issue by rsnakard-r7** [istio/istio#29395]
In our automated system we look through all our kubernetes pods for certain environment variables and depending on those flags our automated system will redirect communications and perform operations on the pods. How do I customize the environment variables in the istio-proxy container? The [istio-pilot proxy](https://istio.io/latest/docs/reference/commands/pilot-agent/#pilot-agent-proxy) configuration option doesn't seem to give it. 

We can't set it after pod creation because our system registers the flags as the pods come online.

**Comment by morvencao** [comment]
Have you tried to set env for istio-proxy through **proxyMedata**:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    defaultConfig:
      proxyMetadata:
        KEY: VALUE
```
