### ISSUE TITLE
Why can't destination rules and virtual services with same hostname be applied simultaneously?

### ISSUE THREAD

**Issue by LynnnnnnnYang** [istio/istio#29406]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

Is it possible to route traffic by applying traffic routing rules recursively?

Here is the situation: we have several independent routing rules, each of them can be described by one destination rule and one virtual service.

For example, we have three rules naming ruleA, ruleB and ruleC. According to ruleA, traffic match conditionA1 with be routed to subsetA1 and traffic match conditionA2 with be routed to subsetA2.Likewise, we have subsetB1 for conditionB1, subsetB2 for conditionB2 and subsetC1 for conditionC1, subsetC2 for conditionC2.

In that case, for traffic that matches conditionA1 and conditionB1 and conditionC1, we want it to be routed to the intersection of subsetA1, subsetB1 and subsetC1.

**Describe alternatives you've considered**

We have considered two solutions.

First one is to enumerate all possibilities of combinations of different routing rules in one destination rule and one virtual service. With the increase of the number of rules, the complexity and redundancy of configuration is becoming more and more unacceptable. In our case here, with four routing rules, each of which has more than 10 available subsets, the configuration is unreadable.

The second one is to define routing rules separately, then chain one virtual service to another. In that case, we will have clear configuration for each routing rule. However, destination rules with the same hostname will be overwrite in proxy.sidecarscope. This solution turned out to be unpractical.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
Can you give an example to help understand?

**Comment by LynnnnnnnYang** [comment]
For example, two individual destination rules and virtual services are defined for the reviews service. 
We define the first pair of vs and dr so that traffic can be routed to different versions of reviews service. While the second pair of vs and dr is defined so that all traffic from a specific user is routed to a specific group of hosts.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews-route
spec:
  hosts:
  - reviews.prod.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: "/wpcatalog"
    route:
    - destination:
        host: reviews.prod.svc.cluster.local
        subset: v2
  - match:
    - uri:
        prefix: "/catalog"
    route:
    - destination:
        host: reviews.prod.svc.cluster.local
        subset: v1

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews-destination
spec:
  host: reviews.prod.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: product-route
spec:
  hosts:
  - reviews.prod.svc.cluster.local
  http:
  - match:
    - headers:
        end-user:
          exact: jason
    route:
    - destination:
        host: reviews.prod.svc.cluster.local
        subset: user1
  - match:
    - headers:
        end-user:
          exact: jack
    route:
    - destination:
        host: reviews.prod.svc.cluster.local
        subset: user2

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: product-destination
spec:
  host: reviews.prod.svc.cluster.local
  subsets:
  - name: user1
    labels:
      userGroup: user1
  - name: user2
    labels:
      userGroup: user2
```
In order to make both of them effective, by current design, we have to define them by listing all possible combination in one VirtualService and DestinationRule as following:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: cross-destination
spec:
  host: reviews.prod.svc.cluster.local
  subsets:
  - name: user1-v1
    labels:
      userGroup: user1
      version: v1
  - name: user2-v1
    labels:
      userGroup: user2
      version: v1
  - name: user1-v2
    labels:
      userGroup: user1
      version: v2
  - name: user2-v2
    labels:
      userGroup: user2
      version: v2


apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cross-route
spec:
  hosts:
  - reviews.prod.svc.cluster.local
  http:
  - match:
    - headers:
        end-user:
          exact: jason
      uri:
        prefix: "/wpcatalog"
    route:
    - destination:
        host: reviews.prod.svc.cluster.local
        subset: user1-v2
  - match:
    - headers:
        end-user:
          exact: jack
      uri:
        prefix: "/wpcatalog"
    route:
    - destination:
        host: reviews.prod.svc.cluster.local
        subset: user2-v2
  - match:
    - headers:
        end-user:
          exact: jason
      uri:
        prefix: "/catalog"
    route:
    - destination:
        host: reviews.prod.svc.cluster.local
        subset: user1-v1
  - match:
    - headers:
        end-user:
          exact: jack
      uri:
        prefix: "/catalog"
    route:
    - destination:
        host: reviews.prod.svc.cluster.local
        subset: user2-v1
```
And when it comes to more possibilities, the complexity and redundancy of configuration is quite obvious, as picture shown below:
![77C077BE-AEA0-403E-ABB2-4277C1041DB5](https://user-images.githubusercontent.com/17975823/101329522-71d13b00-38ac-11eb-97bb-b573a2b6bcf4.png)
