### ISSUE TITLE
CORS  error for failed JWT validation

### ISSUE THREAD

**Issue by peterwhitesell** [istio/istio#29425]
**Bug description**
We use JWT authentication via `security.istio.io/v1beta1/RequestAuthentication` and `security.istio.io/v1beta1/AuthorizationPolicy` attached to an Istio ingress gateway, and the `corsPolicy` feature in `VirtualService`s attached to that gateway to allow cross origin requests to our API Gateway from our web app.

When JWT validation is successful, requests are successfully passed to our backend services, and responses include the proper CORS headers as defined in the VirtualServices. However, when JWT validation fails, responses do NOT include the proper CORS headers, which leads to browsers throwing CORS errors instead of returning the 40x responses to the javascript. 

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
JWT validation failures from `RequestAuthentication` and authorization failures from `AuthorizationPolicy` respond with CORS headers as defined in the `corsPolicy` of `VirtualServices` 

**Steps to reproduce the bug**
1. Install Istio control plane with an ingress gateway
2. configure that gateway with a `Gateway` resource
```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: foo
  namespace: istio-system
spec:
  selector:
    app: foo
  servers:
  - hosts:
    - 'a.example.com'
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - 'a.example.com'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      privateKey: /etc/istio/certs/foo/tls.key
      serverCertificate: /etc/istio/certs/foo/tls.crt
```
3. create a `RequestAuthentication` resource, specifying JWT authentication for the gateway
```yaml
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: foo
  namespace: istio-system
spec:
  jwtRules:
  - forwardOriginalToken: true
    fromHeaders:
    - name: Authorization
      prefix: 'Bearer '
    issuer: https://your.jwt.issuer
    jwksUri: https://your.jwks.endpoint
  selector:
    matchLabels:
      app: foo
```
4. Create an `AuthorizationPolicy` resource, disallowing non-authenticated requests to the gateway
```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: foo
  namespace: istio-system
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        paths:
        - /*
    when:
    - key: request.auth.claims[iss]
      values:
      - https://your.jwt.issuer
  selector:
    matchLabels:
      app: foo
```
5. create a `VirtualService` resource exposing your service behind the gateway with a `corsPolicy`
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app: bar
  name: bar
  namespace: default
spec:
  gateways:
  - istio-system/foo
  hosts:
  - a.example.com
  http:
  - corsPolicy:
      allowCredentials: true
      allowHeaders:
      - foo
      allowMethods:
      - GET
      - HEAD
      - OPTIONS
      allowOrigin:
      - https://localhost
      allowOrigins:
      - exact: https://localhost
      maxAge: 30m
    route:
    - destination:
        host: bar.default.svc.cluster.local
```
6. make a cross origin request to the gateway with proper JWT token, notice that it _does_ return expected CORS response headers
```shell
$ curl -i \
  -H 'Origin: https://localhost' \
  -H 'Access-Control-Request-Method: POST,PUT' \
  -H 'Access-Control-Request-Headers: foo' \
  https://a.example.com \
  -H 'Authorization: Bearer <REDACTED valid token>'

HTTP/2 200
access-control-allow-origin: https://localhost
access-control-allow-credentials: true
access-control-allow-methods: GET,HEAD,OPTIONS
access-control-allow-headers: foo
access-control-max-age: 1800
date: Fri, 04 Dec 2020 22:44:59 GMT
server: istio-envoy
```
7. make a cross origin request to the gateway WITHOUT proper JWT token, notice that it _DOES NOT_ return expected CORS response headers
```shell
$ curl -i \
  -H 'Origin: https://localhost' \
  -H 'Access-Control-Request-Method: POST,PUT' \
  -H 'Access-Control-Request-Headers: foo' \
  https://a.example.com \
  -H 'Authorization: Bearer <REDACTED expired token>'


HTTP/2 401
content-length: 14
content-type: text/plain
date: Fri, 04 Dec 2020 22:47:15 GMT
server: istio-envoy

Jwt is expired
```

Although the response code and response body may be different, the same behavior is observed wrt missing CORS headers for missing token, invalid token and expired token.

Please help us understand if there is a way to get these authentication and authorization failure responses to include the CORS headers configured in our VirtualService.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```shell
$ istioctl version --remote
client version: 1.6.13
foo version: 1.6.13
telemetry version: 1.6.13
telemetry version: 1.6.13
istiod version: 1.6.13
data plane version: 1.6.13 (X proxies)

$ kubectl version --short
Client Version: v1.19.3
Server Version: v1.14.10-gke.50
```

**How was Istio installed?**
using `istioctl`

**Environment where the bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by liminw** [comment]
To make sure I understand the request here, what are the expected CORS headers in the response in case of authentication/authorization errors? Should the error code 401/403 returned as part of the CORS response? It would be great if you can add a link to any RFC so we have a standard to follow.

**Comment by rbasoalto** [comment]
The CORS spec lives as part of the [`fetch()` living spec](https://fetch.spec.whatwg.org/). It's not incredibly specific about these cases, but it does say that responses to a CORS requests (actual GET/POST requests, or preflight OPTIONS requests) that don't include the `Access-Control-*` headers are interpreted as the server not understanding the CORS protocol. These responses cause the client to fail the cross-origin request just as if there was a network error, or a generic CORS error.

In authenticated cross-origin requests, though, the client can't distinguish an authorization error from a CORS error. That's why it is expected that CORS-capable endpoints respond to preflight requests with the appropriate CORS headers *before* applying any authentication filters. Examples abound around the web, just search for "cors preflight 401", and even Google's own [apigee docs have examples on how to configure API proxies to respond to CORS preflight requests bypassing authentication](https://docs.apigee.com/api-platform/develop/adding-cors-support-api-proxy).

**Comment by nmnellis** [comment]
we spoke earlier and im sure that this is a solution that will work for you but its work a try. You can use envoy filters to inject headers. you should be able to inspect the response for the 401 or 403 and still include the CORS headers as a stop gap. if you would like, i can dig up more examples. 

An example to get you started
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: lua-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.router"
    patch:
      operation: INSERT_BEFORE
      value:
       name: envoy.lua
       typed_config:
         "@type": "type.googleapis.com/envoy.config.filter.http.lua.v2.Lua"
         inlineCode: |
            function envoy_on_response(response_handle)
                response_handle:logInfo(" ========= XXXXX =========="); 
                response_handle:headers():add("X-User-Header", "worked");
            end 
```

**Comment by christian-posta** [comment]
So basically, the cors filter should come before the jwt_authn filter to get this to work as you're describing. Your best bet is to just re-order the filters like this:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: reorder-cors-before-jwt
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: istio-ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter: 
              name: "envoy.filters.http.cors"                          
    patch:
      operation: REMOVE          
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter: 
              name: "envoy.filters.http.jwt_authn"                          
    patch:
      operation: INSERT_BEFORE   
      value: 
        name: "envoy.filters.http.cors"
        typed_config: 
          "@type": "type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors"                    

```

However, I do suggest this become the default behavior if possible. I don't see a case how CORS coming earlier (ie, before JWT) would be harmful. This should work on all of Istio 1.6, 1.7, 1,8.
