### ISSUE TITLE
istio1.8.0: examples on gRPC-JSON transcode needed

### ISSUE THREAD

**Issue by shelwinnn** [istio/istio#29437]
I try to set up proxy for my gRPC service using istio 1.8.0, but not work: `upstream connect error or disconnect/reset before headers. reset reason: connection termination`.
Could you please give an example on how to do that?

gRPC proto
```proto
// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello(HelloRequest) returns (HelloReply) {
    option (google.api.http) = {
      post: "/v1/say"
      body: "*"
    };
  }
}
```

EnvoyFilter
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: my-grpc-json-transcoder
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: INSERT_BEFORE
      value:
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
          print_options:
             add_whitespace: true
             always_print_enums_as_ints: false
             always_print_primitive_fields: true
             preserve_proto_field_names: false
          proto_descriptor: /etc/envoy/greeter.pb
          match_incoming_request_route: true
          auto_mapping: false
          services:
          - helloworld.Greeter
        name: envoy.http.grpc_json_transcoder
  workloadSelector:
    labels:
      app: greeter

```

Send HTTP Request
```bash
# service name: greeter, port: 7000
curl -XPOST -H 'Content-Type: application/json' -d '{"name":"abc"}'  greeter:7000/v1/say  -vvv
```

Get Response:
```bash
*   Trying 10.68.228.110...
* TCP_NODELAY set
* Connected to greeter (10.68.228.110) port 7000 (#0)
> POST /v1/say HTTP/1.1
> Host: greeter:7000
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 14
>
* upload completely sent off: 14 out of 14 bytes
< HTTP/1.1 503 Service Unavailable
< content-length: 95
< content-type: text/plain
< date: Fri, 04 Dec 2020 18:19:49 GMT
< server: istio-envoy
< x-envoy-decorator-operation: greeter.base.svc.cluster.local:7000/*
<
* Connection #0 to host greeter left intact
upstream connect error or disconnect/reset before headers. reset reason: connection termination
```

**Comment by shelwinnn** [comment]
1.8.0 missing cluster config  `http2_protocol_options`,  so,  EnvoyFilter should be

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: my-grpc-json-transcoder
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: INSERT_BEFORE
      value:
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
          print_options:
             add_whitespace: true
             always_print_enums_as_ints: false
             always_print_primitive_fields: true
             preserve_proto_field_names: false
          proto_descriptor: /etc/envoy/greeter.pb
          match_incoming_request_route: true
          auto_mapping: false
          services:
          - helloworld.Greeter
        name: envoy.http.grpc_json_transcoder
  - applyTo: CLUSTER
    match:
      services: {{K8S_SERVICE_DOMAIN}} # example: my-svc.my-namespace.svc.cluster-domain.example
    patch:
      operation: MERGE
      value:
        http2_protocol_options: {}     
  workloadSelector:
    labels:
      app: greeter
```
