### ISSUE TITLE
Can pilot support xds configuration grayscale delivery to envoy

### ISSUE THREAD

**Issue by lzp0412** [istio/istio#29434]
Can pilot support xds configuration grayscale delivery to envoy? For example,I updated a virtualservice configuration, and I am not sure if this configuration will fail after being applied to envoy. So I want to push the configuration to certain envoy instances to verify that it is correct. If the verification is ok, then send the configuration to all envoy instances.

**Comment by howardjohn** [comment]
See https://github.com/istio/istio/issues/7794, this feature is not available currently nor is it on our roadmap.

**Comment by lzp0412** [comment]
> See #7794, this feature is not available currently nor is it on our roadmap.

Are there relevant design documents or working groups? I am more interested in this aspect, can join in to discuss and undertake part of the work.

**Comment by hzxuzhonghu** [comment]
Just like exportTo, we can add workloadselector

**Comment by lzp0412** [comment]
@howardjohn

**Comment by lzp0412** [comment]
@howardjohn 
Can we extend the support for workselector in the configuration？
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews-route
spec:
  hosts:
  - reviews.prod.svc.cluster.local
  http:
  - name: "reviews-v2-routes-canary"
    workloadSelector:
      labels:
        app: ratings   
      matchExpressions:
        - {key: canary, operator: In, values: ["gray1","gray2"]} 
    match:
    - uri:
        prefix: "/wpcatalog"
    - uri:
        prefix: "/consumercatalog"
    route:
    - destination:
        host: reviews.prod.svc.cluster.local
        subset: v2
  - name: "reviews-v2-routes"
    workloadSelector:
      matchExpressions:
        - {key: canary, operator: NotIn, values: ["gray1","gray2"]}  
    match:
    - uri:
        prefix: "/wpcatalog"
    route:
    - destination:
        host: reviews.prod.svc.cluster.local
        subset: v2
  - name: "reviews-v1-route"
    route:
    - destination:
        host: reviews.prod.svc.cluster.local
        subset: v1
```
Like this,we can filter the instances with specific label through the workloadselector, and make the newly added routing rule  effective on these instances, so as to achieve the purpose of canary publishing.
