### ISSUE TITLE
How to config envoy.grpc_json_transcoder to export grpc service

### ISSUE THREAD

**Issue by wubo0067** [istio/istio#29432]
I want to use grpc_json_transcoder export my grpc service in istio.1.7.0. EnvoyFilter configuration is below, But the configuration doesn't work.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: istio-simplegrpc-server
  namespace: istio-ns
spec:
  workloadSelector:
    labels:
      app: istio-simplegrpc-server
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        portNumber: 8081
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.router" 
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.grpc_json_transcoder
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
          proto_descriptor: /etc/envoy/helloworld.Greeter.pd
          match_incoming_request_route: true
          auto_mapping: false
          services: ["helloworld.Greeter"] # Service name defined in proto          
          print_options:
            add_whitespace: true
            always_print_enums_as_ints: false
            always_print_primitive_fields: true
            preserve_proto_field_names: `false`
```

istio verson is:
```
[root@192 deploy]# istioctl version
client version: 1.7.3
control plane version: 1.7.3
data plane version: 1.7.3 (4 proxies)
```
my grpc proto is：

```
syntax = "proto3";
 
option go_package = "istio-simplegrpc/proto/helloworld";
 
package helloworld;

import "google/api/annotations.proto";
 
// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply) {
    option (google.api.http) = {
      get: "/v1/say"
    };
  }

  // 
  rpc CreateReservation(CreateReservationRequest) returns (Reservation) {  
    option (google.api.http) = {
      post: "/v1/reservations"
      body: "reservation"
   };  
  }
}
 
// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}
 
// The response message containing the greetings
message HelloReply {
  string message = 1;
}

// Reservation
message Reservation {
    string id = 1;
    string title = 2;
    string venue = 3;
    string room = 4;
    string timestamp = 5;
    repeated Person attendees = 6;
}

message Person {
    string ssn = 1;
    string firstName = 2;
    string lastName = 3;
}

message CreateReservationRequest {
    Reservation reservation = 2;
}

message CreateReservationResponse {
    Reservation reservation = 1;
}
```
I use cmd **curl  http://greeter.istio-ns.svc.cluster.local:8081/v1/say?name=test --verbose** to call，The result returned by curl is 404
```
sh-4.2# curl  http://greeter.istio-ns.svc.cluster.local:8081/v1/say?name=test --verbose
* About to connect() to greeter.istio-ns.svc.cluster.local port 8081 (#0)
*   Trying 10.96.87.151...
* Connected to greeter.istio-ns.svc.cluster.local (10.96.87.151) port 8081 (#0)
> GET /v1/say?name=test HTTP/1.1
> User-Agent: curl/7.29.0
> Host: greeter.istio-ns.svc.cluster.local:8081
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< date: Sun, 06 Dec 2020 07:03:56 GMT
< server: envoy
< content-length: 0
< 
* Connection #0 to host greeter.istio-ns.svc.cluster.local left intact
```
