### ISSUE TITLE
Envoy external auth filter is not work with istio 1.8 version

### ISSUE THREAD

**Issue by eddran** [istio/istio#29431]
**Bug description**
I am using envoy external auth filter with istio. It work on 1.6 & 1.7 versions. But when i installed istio 1.8 it is no longer working.

This is my envoy external auth filter works in 1.6 & 1.7 version
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: authn-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain: 
            filter:
              name: "envoy.http_connection_manager"
              subFilter:
                name: "envoy.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.ext_authz
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
            clear_route_cache: true
            http_service:
              server_uri:
                uri: http://auth-http-service.default.svc.cluster.local
                cluster: outbound|3000||auth-http-service.default.svc.cluster.local
                timeout: 1.5s
              authorizationRequest:
                allowedHeaders:
                  patterns:
                    - exact: "cookie"
              authorizationResponse:
                allowedClientHeaders:
                  patterns:
                    - exact: "authorization"
                allowedUpstreamHeaders:
                  patterns:
                    - exact: "set-cookie"
                    - exact: "authorization"
```

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** 
1.8.0

**How was Istio installed?**
istioctl used

**Environment where the bug was observed (cloud vendor, OS, etc)**
minikube

**Comment by Subreptivus** [comment]
Hey @eddran 
I'm using pretty much the same EnvoyFilter, and it's working fine with 1.8. The only difference that you're using `workloadSelector`, so maybe check this one first.
Here is mine:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: auth-filter
  namespace: istio-system
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: ANY
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              name: envoy.router
        portNumber: 8443
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.ext_authz
        typedConfig:
          '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
          failureModeAllow: false
          httpService:
            authorizationRequest:
              allowedHeaders:
                patterns:
                - exact: authorization
                - exact: user-agent
                - exact: cookie
                - exact: x-forwarded-host
                - exact: x-forwarded-proto
                - exact: x-forwarded-uri
                - exact: x-forwarded-method
              headersToAdd:
                - key: x-verify-params
                  value: '{"foo-bar"}'
            authorizationResponse:
              allowedUpstreamHeaders:
                patterns:
                - exact: x-userinfo
                - exact: x-access-token
                - exact: authorization
            pathPrefix: /istio/verify-params-header
            serverUri:
              cluster: outbound|80||auth-server.auth-server.svc.cluster.local
              timeout: 120s
              uri: http://auth-server.auth-server.svc.cluster.local
          statusOnError:
            code: Forbidden
```
