### ISSUE TITLE
Liveness and readiness probes fail for Istio if AWS CNI custom network is used.

### ISSUE THREAD

**Issue by skolenkin** [istio/istio#29454]
We configured AWS CNI Custom networks for pods.  

```
kubectl get ENIconfig  
NAME     AGE  
us-west-2a   5h35m  
us-west-2b   5h35m  
us-west-2c   5h35m  
```
  
```
kubectl get ENIconfig  us-west-2a -o yaml  
apiVersion: crd.k8s.amazonaws.com/v1alpha1  
kind: ENIConfig  
metadata:  
  name: us-west-2a  
spec:  
  securityGroups:  
  - sg-XXXXXX 
  subnet: subnet-XXXXX 
```
  
```
kubectl get pods –o wide   
istio-system        istio-ingressgateway-59cf75bf7-4s557         0/1 Running        0      2m58s   100.64.157.163   ip-10-0-146-62.us-west-2.compute.internal <none>       <none>  
istio-system        istiod-6965c56995-d8jph                      0/1 Running        0      2m58s   100.64.148.223   ip-10-0-146-62.us-west-2.compute.internal <none>       <none>  
kube-system         aws-node-5jfmb                               1/1 Running        0      16m   10.0.101.133 ip-10-0-101-133.us-west-2.compute.internal   <none>       <none>  
kube-system         aws-node-qxhd4                               1/1 Running        0      16m   10.0.146.62  ip-10-0-146-62.us-west-2.compute.internal <none>       <none>  
kube-system     aws-node-xtkmc                               1/1 Running        0      15m   10.0.38.17   ip-10-0-38-17.us-west-2.compute.internal <none>       <none>  
```
  
```
kubectl –n istio-system get events  
53s         Warning   Unhealthy             pod/istiod-6965c56995-d8jph                Readiness probe failed: Get http://100.64.148.223:8080/ready: dial tcp 100.64.148.223:8080: connect: connection refused  
``` 

Kubelet can’t connect to istiod from node ip to 100.64.x.x  
Also, we have the same issue with all applications which used Health Checks.  
From pod with ip 100.64.x.x we can ping pods with ip 100.64.x.x  

We have this issue with the following components and versions: 
AWS CNI plugin versions 1.7.4, 1.7.5 and 1.7.6.  
Istio versions: 1.7.3, 1.7.4, 1.8.0 

But if try to deploy an easy application pod with Readiness and LIveness probes - it works  (for  example Nginx) 

``` 
kubectl -n kube-system get daemonset aws-node -o yaml  
   containers:  
   - env:  
     - name: ADDITIONAL_ENI_TAGS  
       value: '{}'  
     - name: AWS_VPC_CNI_NODE_PORT_SUPPORT  
       value: "true"  
     - name: AWS_VPC_ENI_MTU  
       value: "9001"  
     - name: AWS_VPC_K8S_CNI_CONFIGURE_RPFILTER  
       value: "false"  
     - name: AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG  
       value: "true"  
     - name: AWS_VPC_K8S_CNI_EXTERNALSNAT  
       value: "true"  
     - name: AWS_VPC_K8S_CNI_LOGLEVEL  
       value: DEBUG  
     - name: AWS_VPC_K8S_CNI_LOG_FILE  
       value: /host/var/log/aws-routed-eni/ipamd.log  
     - name: AWS_VPC_K8S_CNI_RANDOMIZESNAT  
       value: prng  
     - name: AWS_VPC_K8S_CNI_VETHPREFIX  
       value: eni  
     - name: AWS_VPC_K8S_PLUGIN_LOG_FILE  
       value: /var/log/aws-routed-eni/plugin.log  
     - name: AWS_VPC_K8S_PLUGIN_LOG_LEVEL  
       value: DEBUG  
     - name: DISABLE_INTROSPECTION  
       value: "false"  
     - name: DISABLE_METRICS  
       value: "false"  
     - name: ENABLE_POD_ENI  
       value: "true"  
     - name: MY_NODE_NAME  
       valueFrom:  
         fieldRef:  
           apiVersion: v1  
           fieldPath: spec.nodeName  
     - name: WARM_ENI_TARGET  
       value: "1"  
     - name: ENI_CONFIG_LABEL_DEF  
       value: failure-domain.beta.kubernetes.io/zone  
     image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.7.6-eksbuild.1  
     imagePullPolicy: Always  
     livenessProbe:  
       exec:  
         command:  
         - /app/grpc-health-probe  
         - -addr=:50051  
       failureThreshold: 3  
       initialDelaySeconds: 60  
       periodSeconds: 10  
       successThreshold: 1  
       timeoutSeconds: 1  
     name: aws-node  
     ports:  
     - containerPort: 61678  
       hostPort: 61678  
       name: metrics  
       protocol: TCP  
     readinessProbe:  
       exec:  
         command:  
         - /app/grpc-health-probe  
         - -addr=:50051  
       failureThreshold: 3  
       initialDelaySeconds: 1  
       periodSeconds: 10  
       successThreshold: 1  
       timeoutSeconds: 1  
     resources:  
       requests:  
         cpu: 10m  
     securityContext:  
       capabilities:  
         add:  
         - NET_ADMIN  
     terminationMessagePath: /dev/termination-log  
     terminationMessagePolicy: File  
     volumeMounts:  
     - mountPath: /host/opt/cni/bin  
       name: cni-bin-dir  
     - mountPath: /host/etc/cni/net.d  
       name: cni-net-dir  
     - mountPath: /host/var/log/aws-routed-eni  
       name: log-dir  
     - mountPath: /var/run/aws-node  
       name: run-dir  
     - mountPath: /var/run/dockershim.sock  
       name: dockershim  
     - mountPath: /run/xtables.lock  
       name: xtables-lock  
   dnsPolicy: ClusterFirst  
   hostNetwork: true  
   initContainers:  
   - env:  
     - name: DISABLE_TCP_EARLY_DEMUX  
       value: "true"  
     image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni-init:v1.7.6-eksbuild.1  
     imagePullPolicy: Always  
     name: aws-vpc-cni-init  
```  

We have this issue with the following components and versions: 
AWS CNI plugin versions 1.7.4, 1.7.5 and 1.7.6.  
Istio versions: 1.7.3, 1.7.4, 1.8.0
