### ISSUE TITLE
ServiceEntry host/route not resolved

### ISSUE THREAD

**Issue by skokaina** [istio/istio#29463]
Hi, 

Following the documentation, we created a service entry to route all requests from workloads targeting 'https://pulse.access.internal' to 'https://10.254.254.5'

``` logs extract from a sprintboot app pointing to it
Name or service not known executing POST https://pulse.access.internal/api/v1/leads/submit
at feign.FeignException.errorExecuting(FeignException.java:249)
at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:120)
```

Configuration of declared ServiceEntry and VirtualService:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: pulse-access-internal
  namespace: das-ms
spec:
  hosts:
    - pulse.access.internal
  tls:
  - match:
    - port: 443
      sniHosts:
      - pulse.access.internal
    route:
    - destination:
        host: pulse.access.internal
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: pulse-access-internal
  namespace: das-ms
spec:
  hosts:
    - pulse.access.internal
  addresses:
    - 10.254.254.5
  ports:
    - name: https
      number: 443
      protocol: HTTPS
  location: MESH_EXTERNAL
  resolution: STATIC
  endpoints:
    - address: 10.254.254.5
```

also, doing an nslookup from within the pod container:

```
[root@workd-2343dssc93-4dkj]/# nslookup pulse.access.internal
Server:		172.20.0.10
Address:	172.20.0.10#53

** server can't find pulse.access.internal: NXDOMAIN
``` 

For which reason is this service entry not being resolved ?

**Comment by howardjohn** [comment]
This is working as expected, Istio does not (yet, see https://preliminary.istio.io/latest/blog/2020/dns-proxy/) handle DNS for ServiceEntry

**Comment by skokaina** [comment]
thanks @howardjohn, looking at the documentation, it should be working as of 1.8:

```
Starting with Istio 1.8, the Istio agent on the sidecar will ship with a caching DNS proxy, programmed dynamically by Istiod. Istiod pushes the hostname-to-IP-address mappings for all the services that the application may access based on the Kubernetes services and service entries in the cluster. DNS lookup queries from the application are transparently intercepted and served by the Istio agent in the pod or VM. If the query is for a service within the mesh, irrespective of the cluster that the service is in, the agent responds directly to the application. If not, it forwards the query to the upstream name servers defined in /etc/resolv.conf. The following diagram depicts the interactions that occur when an application tries to access a service using its hostname
```

Also, as we are using 1.7, it means that only the following configuration shall work:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: pulse-access-internal
  namespace: das-ms
spec:
  hosts:
    - pulse.access.internal
  tls:
  - match:
    - port: 443
      sniHosts:
      - pulse.access.internal
    route:
    - destination:
        host: pulse.access.internal
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: pulse-access-internal
  namespace: das-ms
spec:
  hosts:
    - pulse.access.internal
  addresses:
    - 10.254.254.5
  ports:
    - name: https
      number: 443
      protocol: HTTPS
  location: **MESH_EXTERNAL**
  resolution: **NONE**
  endpoints:
    - address: 10.254.254.5
```

Making: "https://pulse.access.internal" handled by the proxy to "https://10.254.254.5", right ?

Sorry, we are new to Istio, however the documentation make us understand that:
```
ServiceEntry enables adding additional entries into Istio’s internal service registry, so that auto-discovered services in the mesh **can access/route to these manually specified services**. (https://istio.io/latest/docs/reference/config/networking/service-entry/)
```

Otherwise, what would a ServiceEntry in Istio do if it cannot perform any host/address resolution for describe entires ? :)
