### ISSUE TITLE
fault injection not working for calls made via ingress

### ISSUE THREAD

**Issue by kidiyoor** [istio/istio#2947]
Here is the setup : 

ingress -> service-a

fault.yaml (here is the fault rule for service-a)
```
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: ratings-delay-abort
spec:
  destination:
    name: myapp
  httpFault:
    delay:
      fixedDelay: 7s
      percent: 100
```

Fault is injected if calls are made from within the mesh eg. service-b making api call to service-a
but faults are not injected if calls are made via **ingress** eg. curl <ingress-ip>/service-a

ingress.yaml
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /service-a
        backend:
          serviceName: service-a
          servicePort: 8000
```
