### ISSUE TITLE
IstioOperator can't deploy service due to duplicate port

### ISSUE THREAD

**Issue by tobiaskohlbau** [istio/istio#29480]
**Bug description**

The IstiOperator is unable to deploy the service config for `istio-ingressgateway` and states that a duplicate port mapping exists:

```
✘ Ingress gateways encountered an error: failed to create "Service/istio-system/istio-ingressgateway": Service "istio-ingressgateway" is invalid: [spec.ports[4].name: Duplicate value: "tcp-istiod", spec.ports[4]: Duplicate value: core.ServicePort{Name:"", Protocol:"TCP", AppProtocol:(*string)(nil), Port:15012, TargetPort:intstr.IntOrString{Type:0, IntVal:0, StrVal:""}, NodePort:0}]
```

[ ] Docs
[x] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

In 1.7 the operator installed the configuration without any problems.

**Steps to reproduce the bug**

Deploy istio via the following config:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  profile: default
  values:
    global:
      meshExpansion:
        enabled: true
      multiCluster:
        clusterName: kube-cluster
      network: main-network
      meshNetworks:
        main-network:
          endpoints:
          - fromRegistry: kube-cluster
          gateways:
          - registryServiceName: istio-ingressgateway.istio-system.svc.cluster.local
            port: 443
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      proxyStatsMatcher:
        inclusionPrefixes:
        - "tcp"
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          service:
            externalTrafficPolicy: "Local"
          serviceAnnotations:
            load-balancer.hetzner.cloud/location: "fsn1"
            load-balancer.hetzner.cloud/name: "istio-internal-lb"
            load-balancer.hetzner.cloud/use-private-ip: "true"
            load-balancer.hetzner.cloud/type: "lb21"
            load-balancer.hetzner.cloud/disable-public-network: "true"
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
client version: 1.8.0
control plane version: 1.8.0
data plane version: 1.8.0 (15 proxies)
```

```
Client Version: v1.19.4
Server Version: v1.19.0
```

**How was Istio installed?**
With the help of the operator.

**Environment where the bug was observed (cloud vendor, OS, etc)**
Custom installation bootstrapped with kubeadm.
