### ISSUE TITLE
PILOT_ENABLE_ANALYSIS can't be enabled in 1.7.4

### ISSUE THREAD

**Issue by zenvdeluca** [istio/istio#29492]
**Bug description**
Installing istio 1.7.4 using the operator and when I added the following config:
```
    pilot:
      env:
        PILOT_BLOCK_HTTP_ON_443: true
        PILOT_SKIP_VALIDATE_TRUST_DOMAIN: true
        PILOT_ENABLE_ANALYSIS: true
```

the rendered manifests include both true and false, such as below:

```
@@ -20891,6 +20891,10 @@ spec:
           value: /var/run/secrets/remote/config
         - name: PILOT_BLOCK_HTTP_ON_443
           value: "true"
+        - name: PILOT_ENABLE_ANALYSIS
+          value: "true"
+        - name: PILOT_ENABLE_ANALYSIS
+          value: "false"
         - name: PILOT_SKIP_VALIDATE_TRUST_DOMAIN
           value: "true"
         - name: PILOT_TRACE_SAMPLING
```

Has this feature been deprecated and thought why it enables but further disables it? 

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Rendered manifest should have a single flag:
``` 
- name: PILOT_ENABLE_ANALYSIS
+          value: "true"
```

**Steps to reproduce the bug**
install istio 1.7.4 using the operator with the custom pilot.env.PILOT_ENABLE_ANALYSIS = true

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

1.7.4

**How was Istio installed?**
operator

**Environment where the bug was observed (cloud vendor, OS, etc)**
aws, k8s

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by zenvdeluca** [comment]
was able to reproduce the same issue on current version 1.8.1 and 1.8.2

**Comment by zenvdeluca** [comment]
confirm the behavior also in 1.9.1

**Comment by bianpengyuan** [comment]
Not sure where do you set it exactly. It works fine by setting it via component spec:
```yaml
apiVersion: operator.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    pilot:
      k8s:
        env:
          - name: PILOT_ENABLE_ANALYSIS
            value: "true"
```
