### ISSUE TITLE
log HTTP error logs only (status code >=400)

### ISSUE THREAD

**Issue by zenvdeluca** [istio/istio#29493]
I'm pursing to configure access log with status_code_filter to log only error messages (HTTP status codes >=400)

here is the snippet I configured:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: access-log-error
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: ANY
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          access_log:
          - name: envoy.file_access_log
            typed_config:
              "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog"
              path: /dev/stdout
              typed_json_format:
                start_time: "%START_TIME%"
                method: "%REQ(:METHOD)%"
                path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
                protocol: "%PROTOCOL%"
                response_code: "%RESPONSE_CODE%"
                response_flags: "%RESPONSE_FLAGS%"
                bytes_rcvd: "%BYTES_RECEIVED%"
                bytes_sent: "%BYTES_SENT%"
                duration: "%DURATION%"
                upstream_failure_reason: "%UPSTREAM_TRANSPORT_FAILURE_REASON%"
                upstream_service_time: "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%"
                x_forwarded_for: "%REQ(X-FORWARDED-FOR)%"
                user_agent: "%REQ(USER-AGENT)%"
                request_id: "%REQ(X-REQUEST-ID)%"
                authority: "%REQ(:AUTHORITY)%"
                upstream_host: "%UPSTREAM_HOST%"
                upstream_cluster: "%UPSTREAM_CLUSTER%"
                upstream_local_address: "%UPSTREAM_LOCAL_ADDRESS%"
                downstream_local_address: "%DOWNSTREAM_LOCAL_ADDRESS%"
                downstream_remote_address: "%DOWNSTREAM_REMOTE_ADDRESS%"
                requested_server_name: "%REQUESTED_SERVER_NAME%"
                route_name: "%ROUTE_NAME%"
          filter:
              status_code_filter:
                comparison:
                  op: GE
                  value:
                    runtime_key: "400"
```

at the end of the process, I see two access_logs envoy config sections rendered and the filter doesn't work as expected.
I found this behavior is also described in a 2019 mail thread here: https://discuss.istio.io/t/envoyfilter-for-access-log/4055 and apparently there is no resolution.

There seems to be an alternative way to configure envoy access log filters by using metadata: https://envoy-control.readthedocs.io/en/latest/features/access_log_filter

but I was unable to make it work too.  Is there anything I'm missing here, or is this an actual bug that needs to be addressed?

 

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
istio-proxy sidecars should only log HTTP error codes (status code >=400)

**Steps to reproduce the bug**
apply the above EnvoyFilter,  dump an istio-proxy config and verify the incorrect patched access_log config sections.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.7.4

**How was Istio installed?**
operator

**Environment where the bug was observed (cloud vendor, OS, etc)**
aws/k8s

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by douglas-reid** [comment]
Do you have access logging configured globally in your mesh configuration as well?

**Comment by zenvdeluca** [comment]
No, I have access log globally disabled and willing to enable error logs only

**Comment by derekcrovo** [comment]
For posterity, we figured this out. The 'filter' section in the yaml was outdented a level, and we were missing the default_value inside it.  Here's the working version:

apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: access-log-error
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: ANY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          access_log:
          - filter:
              status_code_filter:
                comparison:
                  op: GE
                  value:
                    default_value: 400
                    runtime_key: "null"
            name: envoy.file_access_log
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: /dev/stdout
              typed_json_format:
                authority: '%REQ(:AUTHORITY)%'
                bytes_rcvd: '%BYTES_RECEIVED%'
                bytes_sent: '%BYTES_SENT%'
                downstream_local_address: '%DOWNSTREAM_LOCAL_ADDRESS%'
                downstream_remote_address: '%DOWNSTREAM_REMOTE_ADDRESS%'
                duration: '%DURATION%'
                method: '%REQ(:METHOD)%'
                path: '%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%'
                protocol: '%PROTOCOL%'
                request_id: '%REQ(X-REQUEST-ID)%'
                requested_server_name: '%REQUESTED_SERVER_NAME%'
                response_code: '%RESPONSE_CODE%'
                response_flags: '%RESPONSE_FLAGS%'
                route_name: '%ROUTE_NAME%'
                start_time: '%START_TIME%'
                upstream_cluster: '%UPSTREAM_CLUSTER%'
                upstream_failure_reason: '%UPSTREAM_TRANSPORT_FAILURE_REASON%'
                upstream_host: '%UPSTREAM_HOST%'
                upstream_local_address: '%UPSTREAM_LOCAL_ADDRESS%'
                upstream_service_time: '%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%'
                user_agent: '%REQ(USER-AGENT)%'
                x_forwarded_for: '%REQ(X-FORWARDED-FOR)%'

**Comment by hobbytp** [comment]
I think the new Telemetry API can meet part of your requirement.

The following example can enable accesslog for pod with label "app: ratings" in namespace "hobby". In this case, I added a filter to only filter out HTTP status code >=400

```yaml
kubectl apply -f -<<EOF
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: hobby
spec:
  selector:
    matchLabels:
      app: ratings
  accessLogging:
    - providers:
      - name: envoy
    - filter:
        expression: "response.code >= 400"
EOF
```
