### ISSUE TITLE
Kubernetes default mode doesn't work with InitContainer and Istio Injection

### ISSUE THREAD

**Issue by vovkanaz** [istio/istio#29516]
**Bug description**
Hi there, we are using the helm chart to deploy our application to the K8S cluster.
Along with this process, we ran git clone with a help of the initContainer:
```
...
metadataAnnotations:
    sidecar.istio.io/inject: "true"
    traffic.sidecar.istio.io/excludeOutboundIPRanges: "*"
    traffic.sidecar.istio.io/excludeOutboundIPRanges: "0.0.0.0/0"
...
initContainers:
- name: git-sync
  image: k8s.gcr.io/git-sync:v3.1.0
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      add:
      - NET_ADMIN
      - NET_RAW
      drop:
      - ALL
    # privileged: true   <---- changed from false
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
  args:
   - "clone"
   - "-b" 
   - "staging"
   - "--depth=1"
   - "--single-branch"
   - "git@gitlab-repo.com/repo.git"
   - "/mapservice.geo"
    - name: ssh
      mountPath: "/root/.ssh/"
extraVolumes:
- name: routes
  emptyDir: {}
- name: ssh
  secret:
    secretName: ssh
    defaultMode: 256
```
And after that when we a trying to deploy our app to K8S we have faced with an error that permission to the  /root/.id_rsa is 440 are too open:
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 440 for '/root/.ssh/id_rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "/root/.ssh/id_rsa": bad permissions
```
And we have noticed that this is approach doesn't work when we enabled: sidecar.istio.io/inject: "true", so  without istio injection, we are able to clone our repo with a help of the initContainer.
As you can see we have set defaultMode: 256 which is an equivalent of chmod 0400, but every deploy of the helm chart with IstioSidecar shows us that our id_rsa has 440.

[* ] User Experience

**Expected behavior**
 We would like to have the ability to clone our private repo with a help of initContainer and Istio injection enabled because right now we see this behavior:
```
istio-app-stage-67658c7b97-s75rw                    0/2     CrashLoopBackOff:0/2                0          6s
```
Without Istio
```
-r-------- 1 root root 3243 Dec  9 12:10 /root/.ssh/..data/id_rsa
```
With Istio
```
-r--r-----    1 root     1337          3243 Dec  9 10:41 /root/.ssh/..data/id_rsa
```
**Steps to reproduce the bug**
Install any helm chart using our Values with InitContainer(ssh secrets and with git clone args) Support and Istio sidecar

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
HELM 3 Istio 1.7.4

**How was Istio installed?**
Istio has been installed with the help of theIstioOperator
**Environment where the bug was observed (cloud vendor, OS, etc)**
GKE K8S v1.17.12-gke.1501

So would you mind to help us to find out what is going. Really appreciate your efforts and thanks in andvance.

**Comment by JoeJasinski** [comment]
I'm seeing this exact same issue when upgrading from Istio 1.5.8 to 1.8.1. I'm using the IstioOperator as well. The permissions on the /root/.ssh/ directory look exactly the same as yours before and after the upgrade. This is preventing me from doing a Git clone in an init container.

**Comment by JoeJasinski** [comment]
Through some experimentation, I found that any mount inside of my user-defined init container gets a 1337 group. (My guess is that the 0440 permission comes from the umask or something.) @howardjohn mentioned that this has to do with a securityContext being set. 

First I tried setting on my init container securityContext runAsGroup to root ( https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container). However, that didn't seem to take effect when viewing the mounted key file - it still had the 1337 group. 

What I found that I could do is mount the ssh keys to a different location. Then, in the init container command args, I could copy the keys to the proper place in the /root/.ssh/id_rsa location and set the appropriate permissions (0400 and root group).

```
      initContainers:
      - args:
         # /root/ssh/ is the new mount location
        - cp /root/ssh/* /root/.ssh/ && chown root:root /root/.ssh/id_rsa && chmod
          0400 /root/.ssh/id_rsa && ls -la /root/.ssh/ && ...
```

I can understand the istio-init container needing the securityContext, but I'm still not quite sure how that's bleeding into my user-defined init container. That being said, this work-around seems to work.

**Comment by JoeJasinski** [comment]
I think these issues might be related

https://github.com/istio/istio/issues/22025
https://github.com/kubernetes/kubernetes/issues/57923

Note: I mentioned that I upgraded from istio 1.5.8. For that 1.5.8 install, I was using the old deprecated Helm carts, and never hit this issue.

**Comment by atsai1220** [comment]
Rather than mounting to `/root/.ssh/id_rsa`, we mounted to `/tmp/id_rsa` (or somewhere else, really) and used a script to `cpy` to `/root/.ssh` (and it isn't even necessary to put your keys there)

For my init container
```yaml
initContainers:
- command:
  - ssh-agent
  - sh
  - -c
  - mkdir -m700 -p /root/.ssh/; cp /tmp/id_rsa /root/.ssh/id_rsa; chmod 400
    /root/.ssh/id_rsa; ssh-add /root/.ssh/id_rsa; ssh-keyscan -t rsa ${GIT_HOST}
    >> /root/.ssh/known_hosts;git clone git@${GIT_HOST}:${GIT_REPO}/${GIT_PROJECT}.git
    -b ${GIT_BRANCH} /app; chown -R 1000 /app/*
```

Deployment Example:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jumpbox-django
    tier: web
    version: v2
  name: web-2
  namespace: dev-django
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jumpbox-django
      tier: web
      version: v2
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jumpbox-django
        tier: web
        version: v2
    spec:
      containers:
      - image: bitnami/nginx:1.14
        imagePullPolicy: IfNotPresent
        name: django-nginx
        ports:
        - containerPort: 8080
          name: 8080tcp02
          protocol: TCP
        resources:
          limits:
            cpu: 10m
            memory: 128Mi
          requests:
            cpu: 5m
            memory: 10Mi
        securityContext:
          capabilities: {}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /var/django/app
          name: git
        - mountPath: /opt/bitnami/nginx/conf/nginx.conf
          name: django-nginx
          subPath: nginx-default.conf
      - env:
        - name: APPNAME
          value: jumpbox
        - name: DJANGO_CONFIGURATION
          value: Dev
        - name: DJANGO_DEBUG
          value: "False"
        - name: DJANGO_SETTINGS_MODULE
          value: jumpbox.settings
        - name: WORKERS
          value: "8"
        envFrom:
        - secretRef:
            name: django-vice-sa
            optional: false
        - configMapRef:
            name: django-web-config
            optional: false
        - secretRef:
            name: django-postgres
            optional: false
        image: it-appsvc-docker.docker.artifactory.hello.com/kube-jumpbox-django:5.0
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: Host
              value: jumpbox.marina.hello.io
            path: /
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 2
        name: web
        ports:
        - containerPort: 8000
          name: 8000tcp02
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: Host
              value: jumpbox.marina.viasat.io
            path: /
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 2
          timeoutSeconds: 2
        resources:
          limits:
            cpu: 1500m
            memory: 20000Mi
          requests:
            cpu: 200m
            memory: 10000Mi
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /var/django/app
          name: git
        - mountPath: /var/django/app/certs/ca-viasat-io-crt
          name: vice-cert
          subPath: ca-viasat-io-crt
        - mountPath: /var/django/app/certs/idp_cert.crt
          name: vice-cert
          subPath: idp_cert.crt
        - mountPath: /var/django/app/certs/sp.crt
          name: vice-cert
          subPath: sp.crt
        - mountPath: /var/django/app/certs/sp.key
          name: vice-cert
          subPath: sp.key
        - mountPath: /var/django/app/kubeconfig
          name: sa-kubeconfig
          subPath: kubeconfig
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: it-appsvc-docker-docker-artifactory-viasat-com
      initContainers:
      - command:
        - ssh-agent
        - sh
        - -c
        - mkdir -m700 -p /root/.ssh/; cp /tmp/id_rsa /root/.ssh/id_rsa; chmod 400
          /root/.ssh/id_rsa; ssh-add /root/.ssh/id_rsa; ssh-keyscan -t rsa ${GIT_HOST}
          >> /root/.ssh/known_hosts;git clone git@${GIT_HOST}:${GIT_REPO}/${GIT_PROJECT}.git
          -b ${GIT_BRANCH} /app; chown -R 1000 /app/*
        envFrom:
        - secretRef:
            name: django-git-pull-keys
            optional: false
        image: alpine/git
        imagePullPolicy: Always
        name: gitpull
        resources:
          limits:
            cpu: 10m
            memory: 512Mi
          requests:
            cpu: 1m
            memory: 4Mi
        securityContext:
          capabilities: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app
          name: git
        - mountPath: /tmp/id_rsa
          name: pullkeys
          subPath: id_rsa
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: git
      - name: vice-cert
        secret:
          defaultMode: 511
          optional: false
          secretName: django-vice-sa
      - configMap:
          defaultMode: 420
          name: django-nginx
        name: django-nginx
      - name: sa-kubeconfig
        secret:
          defaultMode: 488
          optional: false
          secretName: sa-kubeconfig
      - name: pullkeys
        secret:
          defaultMode: 384
          optional: false
          secretName: django-git-pull-keys

```
