### ISSUE TITLE
istioctl operator init with --watchedNamespaces does not install with custom namespaces.

### ISSUE THREAD

**Issue by shamsher31** [istio/istio#29515]
Ref: https://istio.io/latest/docs/setup/install/operator/

Follow the docs to watch multiple namespace using `--watchedNamespaces`

```
$ istioctl operator init --watchedNamespaces=ns1,ns2
Installing operator controller in namespace: istio-operator using image: docker.io/istio/operator:1.8.1
Operator controller will watch namespaces: ns1,ns2
✔ Istio operator installed                                                                       
✔ Installation complete
```

Create namespaces.
```
$ kubectl create ns ns1
$ kubectl create ns ns2
```

Install with namespace `ns1`
```
$ kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: ns1
  name: example-istiocontrolplane
spec:
  profile: demo
EOF
istiooperator.install.istio.io/example-istiocontrolplane created
```
The `demo` profile never gets installed into `ns1` namespace.
```
$ kubectl get pods -n ns1 -w
```

The operator installation works fine with the default `istio-system` namespace.

```
$ istioctl version --remote=false
1.8.1
```

**Comment by morvencao** [comment]
@shamsher31 Is this expected behavior? The `watchedNamespaces` are the namespaces for the istio operator CR. For the actual namespace of installed istio control plane, it should be in the `spec.namespace` or `spec.values.global.istioNamespace`.

**Comment by shamsher31** [comment]
Let me try that, I think we should also mention that in docs.

**Comment by morvencao** [comment]
@shamsher31 It ill be clear if we add that in the doc,

**Comment by shamsher31** [comment]
@morvencao Not sure if I'm doing something wrong but specifying `spec.namespace` or `spec.values.global.istioNamespace` also does not work for me.

```
kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: example-istiocontrolplane
spec:
  profile: demo
  namespace: ns1
EOF
```

```
kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: example-istiocontrolplane
spec:
  profile: demo
  values:
    global:
      istioNamespace: ns1
EOF
```

**Comment by morvencao** [comment]
@shamsher31 I forget that we have another issue about this. If we want to installed istio control plane in other namespace rather than `istio-system`, we have to specify `values.global. istioNamespace`, so the latter one should be working:
```
kubectl apply -n ns1 -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: example-istiocontrolplane
spec:
  profile: demo
  values:
    global:
      istioNamespace: ns1
EOF
```

**Comment by shamsher31** [comment]
@morvencao Perfect. The following works for me. So we have to specify `metadata.namespace` and `values.global.istioNamespace` in order to make it work. I will update the docs accordingly. Thanks.

```
kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: ns1
  name: example-istiocontrolplane
spec:
  profile: demo
  values:
    global:
      istioNamespace: ns1
EOF
```

```
$ kubectl get pods -n ns1
NAME                                   READY   STATUS              RESTARTS   AGE
istio-egressgateway-594c7c957b-rfpxm   0/1     ContainerCreating   0          38s
istio-ingressgateway-577cbd7c7-kjv5d   0/1     ContainerCreating   0          38s
istiod-799f5c77d9-ldrlb                1/1     Running             0          38s
```
