### ISSUE TITLE
Current documentation does not cover the case to get information about mTLS STRICT status applied using policies.

### ISSUE THREAD

**Issue by skolenkin** [istio/istio#29514]
Current documentation does not cover the case to get information about mTLS STRICT status applied using policies.

Previously this information was provided with command ```istioctl authn tls-check``` which showed mTLS modes applied, but current istioctl versions 1.7 and 1.8 doesn't not support this command.
Example in previously Istio releases (1.4):
```
istioctl authn tls-check productpage-v1-596598f447-6l48d reviews.default.svc.cluster.local
HOST:PORT                                  STATUS     SERVER     CLIENT     AUTHN POLICY     DESTINATION RULE
reviews.default.svc.cluster.local:9080     AUTO       STRICT     -          /default         -
```
https://github.com/istio/istio/issues/23388

```
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
  namespace: bookinfo
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default-peer-authentication
  namespace: istio-system
spec:
  mtls:
    mode: STRICT
```

```
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "mtls-global"
  namespace: "istio-system"
spec:
  mtls:
    mode: STRICT
```

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: productpage
spec:
  host: productpage
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews
spec:
  host: reviews
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  - name: v3
    labels:
      version: v3
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ratings
spec:
  host: ratings
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  - name: v2-mysql
    labels:
      version: v2-mysql
  - name: v2-mysql-vm
    labels:
      version: v2-mysql-vm
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: details
spec:
  host: details
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
---
```

```
istioctl x describe pod productpage-v1-6987489c74-v7bd6.bookinfo
Pod: productpage-v1-6987489c74-v7bd6.bookinfo
   Pod Ports: 9080 (productpage), 15090 (istio-proxy)
--------------------
Service: productpage.bookinfo
   Port: http 9080/HTTP targets pod port 9080
DestinationRule: productpage.bookinfo for "productpage"
   Matching subsets: v1
   Traffic Policy TLS Mode: ISTIO_MUTUAL

Exposed on Ingress Gateway http://
VirtualService: bookinfo.bookinfo
   /productpage, /static*, /login, /logout, /api/v1/products*
```

I tried to use tcpdump command but it didn't help me.

```
kubectl -n bookinfo exec -it $(kubectl -n bookinfo get pod -l app=productpage -o jsonpath='{.items[0].metadata.name}') -c istio-proxy -- sudo tcpdump dst port 9080  -A
```

```
kubectl -n bookinfo exec -it $(kubectl -n bookinfo get pod -l app=ratings -o jsonpath='{.items[0].metadata.name}') -c ratings -- curl productpage:9080/productpage | grep -o "<title>.*</title>"
```

```
istioctl version
client version: 1.8.0
control plane version: 1.7.4
data plane version: 1.7.4 (14 proxies)
```
