### ISSUE TITLE
In-cluster operator should be able to create the namespace for istio control plane if it doesn't exist

### ISSUE THREAD

**Issue by morvencao** [istio/istio#29519]
**Bug description**

Currently if we initialize the istio operator with `--watchedNamespaces` to specify the istio operator watching namespace other than `istio-system`, and create the `istiooperator` CR in the watched namespace will results error `namespaces "istio-system" not found`

For example:
```
# istioctl operator init --watchedNamespaces=ns1,ns2
```

Then create istiooperator CR in ns1:
```
# cat iop.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: ns1
  name: example-istiocontrolplane
spec:
  profile: default
  namespace: istio-system
```

The In-cluster operator will report `namespaces "istio-system" not found` error.

In-cluster operator should be able to create the namespace for istio control plane if the `istiooperator` CR's namespace is different from the namespace of istio control plane.

This also align with the `istioctl`.

[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
