### ISSUE TITLE
DNS redirect iptables rules not created by istio-cni

### ISSUE THREAD

**Issue by aftab-a** [istio/istio#29511]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

We are trying to create alternate hostname with ServiceEntry for a service and use it to access the service. We are using istio-cni plugin to install the iptable rules for traffic redirection. We have enabled istio dns in sidecars via ISTIO_META_DNS_CAPTURE and ISTIO_META_PROXY_XDS_VIA_AGENT flag. However it seems that istio-cni is not installing udp rules to redirect the dns lookup to the sidecar.

I did a quick grep in the cni directory for port 15053 but could not find any match on any source file. Is the changes implemented for cni to create udp rules for dns?

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
DNS traffic needs to be captured by sidecar and resolve the same.

**Steps to reproduce the bug**
1. Install istio with cni. We used the following istio operator file :-
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: demo
  meshConfig:
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_PROXY_XDS_VIA_AGENT: "true"
  components:
    cni:
      enabled: true
  values:
    cni:
      excludeNamespaces:
       - istio-system
       - kube-system
      logLevel: info
```
2. Create a service (We used `samples/httpbin/httpbin.yaml`)
3. Create a service entry. We used following :-
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: httpbin-test1-global
spec:
  addresses:
  - 10.109.229.252
  endpoints:
  - address: httpbin.test.svc.cluster.local
    ports:
      http: 8000
  hosts:
  - httpbin.test.global
  exportTo:
  - "*"
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 8000
    protocol: http
  resolution: DNS
```
3. Try to access the service from a client pod :-
 ```
$ curl httpbin.test.global:8000
curl: (6) Could not resolve host: httpbin.test.global
/ $ curl httpbin.test.global:8000/headers
curl: (6) Could not resolve host: httpbin.test.global
/ $ command terminated with exit code 6
```
4.  Check the iptable. rules :-
```
docker exec 68194b20bcae ip netns exec cni-c623dbf9-7ac4-e2ab-e032-24d991970733 iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
ISTIO_INBOUND  tcp  --  anywhere             anywhere

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
ISTIO_OUTPUT  tcp  --  anywhere             anywhere

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination

Chain ISTIO_INBOUND (1 references)
target     prot opt source               destination
RETURN     tcp  --  anywhere             anywhere             tcp dpt:15008
RETURN     tcp  --  anywhere             anywhere             tcp dpt:22
RETURN     tcp  --  anywhere             anywhere             tcp dpt:15020
RETURN     tcp  --  anywhere             anywhere             tcp dpt:15021
RETURN     tcp  --  anywhere             anywhere             tcp dpt:15090
ISTIO_IN_REDIRECT  tcp  --  anywhere             anywhere

Chain ISTIO_IN_REDIRECT (3 references)
target     prot opt source               destination
REDIRECT   tcp  --  anywhere             anywhere             redir ports 15006

Chain ISTIO_OUTPUT (1 references)
target     prot opt source               destination
RETURN     tcp  --  anywhere             anywhere             tcp dpt:15020
RETURN     all  --  127.0.0.6            anywhere
ISTIO_IN_REDIRECT  all  --  anywhere            !localhost            owner UID match 1337
RETURN     all  --  anywhere             anywhere             ! owner UID match 1337
RETURN     all  --  anywhere             anywhere             owner UID match 1337
ISTIO_IN_REDIRECT  all  --  anywhere            !localhost            owner GID match 1337
RETURN     all  --  anywhere             anywhere             ! owner GID match 1337
RETURN     all  --  anywhere             anywhere             owner GID match 1337
RETURN     all  --  anywhere             localhost
ISTIO_REDIRECT  all  --  anywhere             anywhere

Chain ISTIO_REDIRECT (1 references)
target     prot opt source               destination
REDIRECT   tcp  --  anywhere             anywhere             redir ports 15001
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
 istioctl version --remote
client version: 1.8.0
control plane version: 1.8.0
data plane version: 1.8.0 (4 proxies)

**How was Istio installed?**
Istio was installed via operator :-
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: demo
  meshConfig:
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_PROXY_XDS_VIA_AGENT: "true"
  components:
    cni:
      enabled: true
  values:
    cni:
      excludeNamespaces:
       - istio-system
       - kube-system
      logLevel: info
```
**Environment where the bug was observed (cloud vendor, OS, etc)**
We reproduced on a kind cluster.

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
