### ISSUE TITLE
Error: unknown field "citadel" in v1alpha1.IstioComponentSetSpec

### ISSUE THREAD

**Issue by asitkumarjena** [istio/istio#29521]
Hi, 

I am getting error after installing istio. I install version 1.6.2 . I had dumped default profile and did modification to update enterprise image registry. Now I am trying to update the installation with below command and getting error
istioctl install -f default-istio-system.yaml --set meshConfig.accessLogFile=/dev/stdout --force

Also, I notice that the profile that was dumped earlier is not same if I try to dump the default profile again. 

Not sure what is wrong in this now. Below section was there while installing. 
```
  citadel:
      enabled: false
      k8s:
        strategy:
          rollingUpdate:
            maxSurge: 100%
            maxUnavailable: 25%
```
