### ISSUE TITLE
create mysql-service，don't connect from website

### ISSUE THREAD

**Issue by liyin37** [istio/istio#29548]
the version is below:
 istio：1.8.1
kubernetes：1.19.1
mysql ：8.0

the yaml file is：
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gistack-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: glusterfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: gistack-mysql
  template:
    metadata:
      labels:
        app: gistack-mysql
    spec:
      containers:
      - name: mysql
        image: www.baidu.com/example/mysql:8.0
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 500Mi
        ports:
        - containerPort: 3306
          protocol: TCP
        env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: "xxxxxx"
        - name: "TZ"
          value: "Asia/Shanghai"
        args:
          - --character-set-server=utf8mb4
          - --collation-server=utf8mb4_unicode_ci
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: gistack-mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    app: gistack-mysql
  type: NodePort
  ports:
  - name: tcp
    port: 3306
    protocol: TCP
```
then after deploy,the mysql is running ,but nodeport cannot connet from website.
[root@gistack-test yaml]# kubectl -n gistack get all |grep mysql
pod/mysql-75cfcdd777-cm9gh               2/2     Running           0          37m
service/mysql                                                    NodePort    10.43.205.225   <none>        3306:32644/TCP       37m
deployment.apps/mysql               1/1     1            1           37m
replicaset.apps/mysql-75cfcdd777               1         1         1       37m

![image](https://user-images.githubusercontent.com/42507175/101749757-118b0500-3b09-11eb-8b01-05927a871e4d.png)
Lost connection to MySQL server at 'waiting for initial communication packet', system error: 0
