### ISSUE TITLE
PeerAuthentication for mTLS service-to-service communication

### ISSUE THREAD

**Issue by paolodedo** [istio/istio#29552]
Hello,

Using

⚫Istio v1.8⚫
🔵Kubernetes v1.19.3🔵

I have found a bug in the PeerAuthentication mTLS service-to-service communication.
My aim is to let my services communicate through http (REST methods exposed) internally without going through the RequestAuthentication -> and so requesting a JWT even for internal calls; this task could be satisfied thanks to the PeerAuthentication, according to the [docs](https://istio.io/latest/docs/reference/config/security/peer_authentication/), but with the following configuration I didn't overcome my problem.

**Gateway**:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: test-gateway
  namespace: dev
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
```

**RequestAuthentication**:

```
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: test-reqauth
  namespace: dev
spec:
  jwtRules:
  - issuer: "http://keycloak/auth/realms/realm"
    jwksUri: "http://keycloak/auth/realms/realm/protocol/openid-connect/certs"

```

**PeerAuthentication**:

```
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: test-peerauth
  namespace: dev
spec:
  mtls:
    mode: STRICT
```

**Deployment 1 (+ vs, svc, authorization policy)**

```
apiVersion: v1
kind: Service
metadata:
  name: kc-istio-integr
  namespace: dev
  labels:
    app: kc-istio-integr
    service: kc-istio-integr
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: kc-istio-integr
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kc-istio-integr
  namespace: dev
spec:
  hosts:
  - "*"
  gateways:
  - test-gateway
  http:
    - match:
      - uri:
          prefix: /uno
      route:
        - destination:
            port:
              number: 8080
            host: kc-istio-integr.dev.svc.cluster.local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kc-istio-integr
  namespace: dev
  labels:
    app: kc-istio-integr
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kc-istio-integr
      version: v1
  template:
    metadata:
      labels:
        app: kc-istio-integr
        version: v1
    spec:
      containers:
      - name: kc-istio-integr
        image: image:1.0
        imagePullPolicy: IfNotPresent
        env:
         - name: SERVICE.URL
           value: "http://kc-istio-integr-2:8080"
        ports:
        - containerPort: 8080
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: kc-istio-integr-authpolicy
 namespace: dev
spec:
 selector:
   matchLabels:
     app: kc-istio-integr
 rules:
 - to:
   - operation:
       methods: ["OPTIONS"]
       paths: ["*"]
 - to:
   - operation:
       methods: ["GET"]
       paths: ["/uno*"]
   when:
   - key: request.auth.claims[realm_access][roles]
     values: ["READ"]
 - to:
   - operation:
       methods: ["POST", "PUT", "DELETE", "PATCH"]
       paths: ["/uno*"]
   when:
   - key: request.auth.claims[realm_access][roles]
     values: ["WRITE"]

```

**Deployment 2 (+ vs, svc, authorization policy)**

```
apiVersion: v1
kind: Service
metadata:
  name: kc-istio-integr-2
  namespace: dev
  labels:
    app: kc-istio-integr-2
    service: kc-istio-integr-2
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: kc-istio-integr-2
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kc-istio-integr-2
  namespace: dev
spec:
  hosts:
  - "*"
  gateways:
  - test-gateway
  http:
    - match:
      - uri:
          prefix: /due
      route:
        - destination:
            port:
              number: 8080
            host: kc-istio-integr-2.dev.svc.cluster.local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kc-istio-integr-2
  namespace: dev
  labels:
    app: kc-istio-integr-2
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kc-istio-integr-2
      version: v1
  template:
    metadata:
      labels:
        app: kc-istio-integr-2
        version: v1
    spec:
      containers:
      - name: kc-istio-integr-2
        image: image-2:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: kc-istio-integr-2-authpolicy
 namespace: dev
spec:
 selector:
   matchLabels:
     app: kc-istio-integr-2
 rules:
 - to:
   - operation:
       methods: ["OPTIONS"]
       paths: ["*"]
 - to:
   - operation:
       methods: ["GET"]
       paths: ["/due*"]
   when:
   - key: request.auth.claims[realm_access][roles]
     values: ["READ"]
 - to:
   - operation:
       methods: ["POST", "PUT", "DELETE", "PATCH"]
       paths: ["/due*"]
   when:
   - key: request.auth.claims[realm_access][roles]
     values: ["WRITE"]
```

From outside the cluster, I reach every http method with a valid JWT.
However, I have got an http method, on the 1st service, which tries to reach the 2nd service with an http request to
http://kc-istio-integr-2:8080/due/internaltest.
this should use an internal service-to-service communication granted by the PeerAuthentication - so it should work without a JWT, since the flow is cluster-internal - but it encounters 403 RBAC.

Any hint regarding that?
Maybe it is a not-handled mechanism, or bugged PeerAuthentication?
Documentation is very poor on that and I am not able to understand.

Thank you very much 💯

**Comment by rinormaloku** [comment]
Your AuthZ Policy is requesting the claim:
```
 - to:
   - operation:
       methods: ["GET"]
       paths: ["/due*"]
   when:
   - key: request.auth.claims[realm_access][roles]
     values: ["READ"]
```

In other words, none of the rules is authorizing the request and hence it is being denied. (Asap 1 authz policy is applied to a workload all requests will be denied unless specifically allowed by 1 of the policies)

**Comment by paolodedo** [comment]
I am able to authorize all these request through JWT, thanks to the RequestAuthentication. 
In this scenario, how to let this internal communication work with PeerAuthentication? (keeping the AuthorizationPolicy for the "end user" authentication)

**Comment by rinormaloku** [comment]
You need to add a rule that allows the traffic:

```
  - from:
    - source:
        principals: ["*"]
    to:
    - operation:
       methods: ["GET"]
       paths: ["/due*"]
```

**Comment by paolodedo** [comment]
Thanks for the very accurate explanation.

I have tried modifying the AuthZ Policies this way, and it works:

1)

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: kc-istio-integr-authpolicy
 namespace: dev
spec:
 selector:
   matchLabels:
     app: kc-istio-integr
 rules:
 # Internal communication
 - from:
   - source:
       namespaces: ["dev"]
   to:
   - operation:
       methods: ["GET"]
       paths: ["/uno*"]
 - from:
   - source:
       namespaces: ["dev"]
   to:
   - operation:
       methods: ["POST", "PUT", "DELETE", "PATCH"]
       paths: ["/uno*"]
 # 
 - to:
   - operation:
       methods: ["OPTIONS"]
       paths: ["*"]
 - to:
   - operation:
       methods: ["GET"]
       paths: ["/uno*"]
   when:
   - key: request.auth.claims[realm_access][roles]
     values: ["READ"]
 - to:
   - operation:
       methods: ["POST", "PUT", "DELETE", "PATCH"]
       paths: ["/uno*"]
   when:
   - key: request.auth.claims[realm_access][roles]
     values: ["WRITE"]
```

2)

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: kc-istio-integr-2-authpolicy
 namespace: dev
spec:
 selector:
   matchLabels:
     app: kc-istio-integr-2
 rules:
 # Internal communication
 - from:
   - source:
       namespaces: ["dev"]
   to:
   - operation:
       methods: ["GET"]
       paths: ["/due*"]
 - from:
   - source:
       namespaces: ["dev"]
   to:
   - operation:
       methods: ["POST", "PUT", "DELETE", "PATCH"]
       paths: ["/due*"]
 # 
 - to:
   - operation:
       methods: ["OPTIONS"]
       paths: ["*"]
 - to:
   - operation:
       methods: ["GET"]
       paths: ["/due*"]
   when:
   - key: request.auth.claims[realm_access][roles]
     values: ["READ"]
 - to:
   - operation:
       methods: ["POST", "PUT", "DELETE", "PATCH"]
       paths: ["/due*"]
   when:
   - key: request.auth.claims[realm_access][roles]
     values: ["WRITE"]
```


Then, I tried using `principals: ["*"]` but it allows me to pass even without JWT.

But, what about PeerAuthentication's utility? I have removed it and the entire flow (of the pasted AuthZ Policies) does not break -> external calls require JWT and internal calls made from namespace `dev`'s workload, do not.
