### ISSUE TITLE
AuthorizationPolicy is blocking allowed paths

### ISSUE THREAD

**Issue by NormanFoxLee12** [istio/istio#29567]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
AuthorizationPolicy is blocking allowed paths

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
AuthorizationPolicy should allow whitelisted paths

**Steps to reproduce the bug**
Case 1:
```
apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
  name: "frontend-ingress-whitelist"
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: DENY
  rules:
    - when:
        - key: request.auth.claims[iss]
          notValues: ["*"]
      to:
        - operation:
            notPaths:
              # Test web services
              - "/test/*"
```
			  
Working:
https://***/test/ui/api/p-service2 <-there is no service here, 2 added just for test
https://***/test/

Not working:
https://***/test/ui/api/p-service/profiles
https://***/test/ui/api/p-service

Error: RBAC: access denied - 403

Sending correct token does not help

Case 2:
```
apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
  name: "frontend-ingress-whitelist"
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: DENY
  rules:
    - when:
        - key: request.auth.claims[iss]
          notValues: ["*"]
      to:
        - operation:
            notPaths:
              # Data intel web services
              - "/test/*"
              - "*/profiles"
```

Working:
https://***/test/ui/api/p-service/profiles
https://***/test/ui/api/p-service2
https://***/test/

Not working:
https://***/test/ui/api/p-service

Error: RBAC: access denied

Sending correct token does not help

Case 3:
No policy

Everything is working

I need to whitelist all the links from above and       
```
to:
  - operation:
      notPaths:
        - "/test/*"
```

does not help.

Adding - "*/profiles" is just workaround. I there any way to whitelist all url which started with the - "/test/*"?

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Istio: 1.7.4
Kubectl: v1.16.15-gke.4300

**How was Istio installed?**
By using istioctl install.
IstioOperator that was used:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  hub: gcr.io/***/golden/istio
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          serviceAnnotations:
            cloud.google.com/load-balancer-type: "internal"
          service:
            loadBalancerIP: ***
            ports:
              - name: status-port
                port: 15020
              - name: http2
                port: 80
                targetPort: 8080
              - name: https
                port: 443
                targetPort: 8443
    cni:
      namespace: kube-system
      enabled: true
  values:
    prometheus:
      hub: gcr.io/***/golden/istio
    cni:
      cniBinDir: /home/kubernetes/bin
      excludeNamespaces:
        - istio-system
        - kube-system
      logLevel: info
```

istio 1.7.4 images were cloned into private gcr

**Environment where the bug was observed (cloud vendor, OS, etc)**
Google Cloud Kubernetes Cluster

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by Kampe** [comment]
seeing the same issues with `1.8.1`

**Comment by jtrbs** [comment]
Hi @NormanFoxLee12, thanks for reporting the issue! May I know if you have deployed "RequestAuthentication" before deploying the "AuthorizationPolicy"?

**Comment by NormanFoxLee12** [comment]
@jtrbs 
yes, this one:
```
apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: "jwt"
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
    - issuer: "***"
      jwksUri: "https://***/jwks"
      forwardOriginalToken: true
```
