### ISSUE TITLE
istio redirecting to wrong outbound serviceentry

### ISSUE THREAD

**Issue by Deepak1100** [istio/istio#29560]
**Bug description**
my service is trying to connect to a database. and it also connects to many other databases(different service's database) but have only one primary DB which it connects at the time of bootstrap. so i have added all the DB in serviceEntry and sidecar of the application where istio is enabled.
I am getting password authentication failed. which we have verified not the case as after removing istio it don't give us any error(and verified from local as well).

after checking the istio-proxy log we found some anomaly in logs
```
{"upstream_cluster":"outbound|5432||communication-service-db.prod","downstream_remote_address":"10.25.126.17:53054","authority":"-","path":"-","protocol":"-","upstream_service_time":"-","upstream_local_address":"10.25.126.17:44628","duration":"90024","upstream_transport_failure_reason":"-","route_name":"-","downstream_local_address":"10.22.37.9:5432","user_agent":"-","response_code":"0","response_flags":"-","start_time":"2020-12-09T14:42:24.846Z","method":"-","request_id":"-","upstream_host":"10.22.90.172:5432","x_forwarded_for":"-","requested_server_name":"-","bytes_received":"874","istio_policy_status":"-","bytes_sent":"4245"}
```
we are hitting say DB1 but logs showing us that it's hitting DB2(communication-service-db.prod) 
plus as you can see in logs that in same logs both the DB's ip is there 
```
"downstream_local_address":"10.22.37.9:5432" // the database it should hit
"upstream_host":"10.22.90.172:5432" // the database it is hitting
```
I have checked istio-proxy's iptables rule and it seems to have all iptable rule as in working sidecar.
we removed the `communication-service-db.prod(DB2)` from sidecar then it started hitting DB4

so I think istio-proxy is doing some kind of redirecting when application is trying to connect to it's primary database on bootup.

**serviceEntry of DB's**
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  annotations:
  name: communication-service-db-service-entry
  namespace: default
spec:
  hosts:
  - communication-service-db.prod
  location: MESH_EXTERNAL
  ports:
  - name: tcp
    number: 5432
    protocol: TCP
  resolution: DNS
```
similarly, all DB entries are created

**Sidecar**
```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  annotations:
  name: app-sidecar
  namespace: prod
spec:
  egress:
  - hosts:
    - '*/communication-service-db.prod'
    - '*/db2'
    - '*/db3'
    - '*/db4
    - '*/db5'
    - '*/db6'
    - '*/db7'
    - '*/db8(main DB)'
    - istio-system/*
  workloadSelector:
    labels:
      app: app
```

**we are using istio to only restrict outbound connection in our cluster**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
client version: 1.6.13
control plane version: 1.6.8
data plane version: 1.6.8 (31 proxies)
```

**How was Istio installed?**
using istioctl

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS, debian

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
not available for 1.6
