### ISSUE TITLE
DestinationRule.portLevelSettings don't work for ServiceEntry with VIPs

### ISSUE THREAD

**Issue by belenot** [istio/istio#29572]
**Bug description**

When I created ServiceEntry and DestinationRule for host "svc", portLevelSettings is not applied. However, it works, for hosts "svc.se", "svc.something" "svc.whatever" 

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behaviour**
Can't be sure, it's a but, or I missed docs. DestinationRule should be applied for single domain hostnames

**Steps to reproduce the bug**

1. Set meshConfig.outboundTrafficPolicy.mode to REGISTRY_ONLY
2. kubectl apply -f httpbin.yml
3. kubectl create deployment nginx --image nginx
4. kubectl exec -it $(kubectl get po | grep nginx | awk '{print $1}') -- sh -c 'curl http://52.3.32.149:443'
5. Got an error about http response for https port.
7. Change host in httpbin.yml for DestinationRule and ServiceEntry to svc.whatever
8. kubectl exec -it $(kubectl get po | grep nginx | awk '{print $1}') -- sh -c 'curl http://52.3.32.149:443'
9. Got an html from httpbin. Here proxy redirected my http protocol to https.

httpbin.yml:
``` yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: svc
spec:
  hosts:
    - svc # not used
  addresses:
    - 52.3.32.149 # VIPs
  ports:
    - number: 443
      name: httpbin-443
      protocol: TCP
    - number: 80
      name: httpbin-80
      protocol: TCP
  location: MESH_EXTERNAL
  resolution: STATIC
  endpoints:
    - address: 52.3.32.149
      ports:
        httpbin-443: 443
        httpbin-80: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: svc
spec:
  host: svc
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE
```

Also, here cluster configuration from proxy config_dump for my "svc" and "svc.whatever" correspondingly:
svc (missing tls_context):

``` json
    {
     "version_info": "2020-12-11T04:59:03Z/10",
     "cluster": {
      "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
      "name": "outbound|443||svc",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {},
        "resource_api_version": "V3"
       },
       "service_name": "outbound|443||svc"
      },
      "connect_timeout": "10s",
      "circuit_breakers": {
       "thresholds": [
        {
         "max_connections": 4294967295,
         "max_pending_requests": 4294967295,
         "max_requests": 4294967295,
         "max_retries": 4294967295
        }
       ]
      },
      "metadata": {
       "filter_metadata": {
        "istio": {
         "services": [
          {
           "namespace": "default",
           "host": "svc",
           "name": "svc"
          }
         ],
         "default_original_port": 443
        }
       }
      },
      "filters": [
       {
        "name": "istio.metadata_exchange",
        "typed_config": {
         "@type": "type.googleapis.com/udpa.type.v1.TypedStruct",
         "type_url": "type.googleapis.com/envoy.tcp.metadataexchange.config.MetadataExchange",
         "value": {
          "protocol": "istio-peer-exchange"
         }
        }
       }
      ]
     },
     "last_updated": "2020-12-11T04:59:07.259Z"
    },
```

svc.whatever (tls_context in place):
``` json
    {
     "version_info": "2020-12-11T05:04:38Z/11",
     "cluster": {
      "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
      "name": "outbound|443||svc.whatever",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {},
        "resource_api_version": "V3"
       },
       "service_name": "outbound|443||svc.whatever"
      },
      "connect_timeout": "10s",
      "circuit_breakers": {
       "thresholds": [
        {
         "max_connections": 4294967295,
         "max_pending_requests": 4294967295,
         "max_requests": 4294967295,
         "max_retries": 4294967295
        }
       ]
      },
      "transport_socket": {
       "name": "envoy.transport_sockets.tls",
       "typed_config": {
        "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext",
        "common_tls_context": {
         "validation_context": {}
        }
       }
      },
      "metadata": {
       "filter_metadata": {
        "istio": {
         "services": [
          {
           "name": "svc.whatever",
           "namespace": "default",
           "host": "svc.whatever"
          }
         ],
         "default_original_port": 443,
         "config": "/apis/networking.istio.io/v1alpha3/namespaces/default/destination-rule/svc"
        }
       }
      },
      "filters": [
       {
        "name": "istio.metadata_exchange",
        "typed_config": {
         "@type": "type.googleapis.com/udpa.type.v1.TypedStruct",
         "type_url": "type.googleapis.com/envoy.tcp.metadataexchange.config.MetadataExchange",
         "value": {
          "protocol": "istio-peer-exchange"
         }
        }
       }
      ]
     },
     "last_updated": "2020-12-11T05:04:41.345Z"
    },
```
**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

istioctl version --remote
```
client version: 1.8.0
control plane version: 1.8.0
data plane version: 1.8.0 (3 proxies)
```

kubectl version --short
```
Client Version: v1.18.0
Server Version: v1.18.13
```

**How was Istio installed?**
``` sh
./bin/istioctl install --set profile=demo --set meshConfig.outboundTrafficPolicy.mode=REGISTRY_ONLY
```

**Environment where the bug was observed (cloud vendor, OS, etc)**
Vagrant box ubuntu/xenial64

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
[bug-report.zip](https://github.com/istio/istio/files/5677179/bug-report.zip)

**Comment by zhj-hx** [comment]
I also encountered the same problem, 
serviceentry resolution: static 
istio version 1.11
meshconfig
      proxyMetadata:
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
        ISTIO_META_DNS_CAPTURE: `"true"`

**Comment by zhj-hx** [comment]
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: test
  labels:
    app: test
spec:
  hosts:
  - test
  exportTo:
    - "."
  ports:
    - number: 22
      name: ssh
      protocol: TCP
  resolution: STATIC
  location: MESH_EXTERNAL
  endpoints:
    - address: 1.1.1.1
      ports:
        ssh: 22
      labels:
        node: cns0
    - address: 1.1.1.2
      ports:
        ssh: 22
      labels:
        node: cns1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: test
spec:
  host: test
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      mode: DISABLE
    connectionPool:
      tcp:
        maxConnections: 1
        connectTimeout: 3ms
        tcpKeepalive:
          time: 10s
          interval: 2s
          probes: 2
    outlierDetection:
      consecutiveGatewayErrors: 3
      consecutive5xxErrors: 3
      interval: 5s
      baseEjectionTime: 30s

**Comment by zhj-hx** [comment]
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: test
  labels:
    app: test
spec:
  hosts:
  - test
  exportTo:
    - "."
  ports:
    - number: 22
      name: ssh
      protocol: TCP
  resolution: STATIC
  location: MESH_EXTERNAL
  endpoints:
    - address: 1.1.1.1
      ports:
        ssh: 22
      labels:
        node: cns0
    - address: 1.1.1.2
      ports:
        ssh: 22
      labels:
        node: cns1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: test
spec:
  host: test
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      mode: DISABLE
    connectionPool:
      tcp:
        maxConnections: 1
        connectTimeout: 3ms
        tcpKeepalive:
          time: 10s
          interval: 2s
          probes: 2
    outlierDetection:
      consecutiveGatewayErrors: 3
      consecutive5xxErrors: 3
      interval: 5s
      baseEjectionTime: 30s
```
