### ISSUE TITLE
Istio operator fails to reconcile ingress gateway service when gateway spec doesn't contain override for ports

### ISSUE THREAD

**Issue by svrakitin** [istio/istio#29608]
**Bug description**

After upgrading Istio operator to 1.8.1 from 1.7.5 it fails to reconcile existing custom ingress gateway service.

Operator logs:
```
2020-12-14T16:23:31.486226Z    info    installer    Updating Service/istio-system/istio-ingressgateway-private (istio-controlplane/)
 2020-12-14T16:23:31.486518Z    error    klog    Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x28a9640), concret
 goroutine 1013 [running]:
 k8s.io/apimachinery/pkg/util/runtime.logPanic(0x295da80, 0xc0022d76b0)
     k8s.io/apimachinery@v0.19.3/pkg/util/runtime/runtime.go:74 +0xa6
 k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
     k8s.io/apimachinery@v0.19.3/pkg/util/runtime/runtime.go:48 +0x89
 panic(0x295da80, 0xc0022d76b0)
     runtime/panic.go:969 +0x1b9
 istio.io/istio/operator/pkg/helmreconciler.saveNodePorts(0xc00000f520, 0xc00000f560, 0x0, 0x0)
     istio.io/istio/operator/pkg/helmreconciler/common.go:164 +0x396
 istio.io/istio/operator/pkg/helmreconciler.applyOverlay(0xc00000f520, 0xc003178028, 0x4, 0x4)
     istio.io/istio/operator/pkg/helmreconciler/common.go:130 +0x386
 istio.io/istio/operator/pkg/helmreconciler.(*HelmReconciler).ApplyObject.func1(0x0, 0x507b17)
     istio.io/istio/operator/pkg/helmreconciler/apply.go:210 +0x270
 k8s.io/client-go/util/retry.OnError.func1(0xcf1089, 0xc00317ced0, 0xc00327f6b8)
     k8s.io/client-go@v0.19.3/util/retry/util.go:51 +0x3c
 k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection(0xc00327f6d8, 0xcf6900, 0x0, 0x0)
     k8s.io/apimachinery@v0.19.3/pkg/util/wait/wait.go:211 +0x69
 k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x4000000000000000, 0x0, 0x3, 0x0, 0xc00327f6d8, 0xc00317a548, 0x0)
     k8s.io/apimachinery@v0.19.3/pkg/util/wait/wait.go:399 +0x55
 k8s.io/client-go/util/retry.OnError(0x989680, 0x4000000000000000, 0x0, 0x3, 0x0, 0x2f7f478, 0xc00327f920, 0x0, 0xcf0ea6)
     k8s.io/client-go@v0.19.3/util/retry/util.go:50 +0xa6
 k8s.io/client-go/util/retry.RetryOnConflict(...)
     k8s.io/client-go@v0.19.3/util/retry/util.go:104
 istio.io/istio/operator/pkg/helmreconciler.(*HelmReconciler).ApplyObject(0xc00180e190, 0xc003178028, 0xc003178000, 0x2e70eb0, 0xf)
     istio.io/istio/operator/pkg/helmreconciler/apply.go:191 +0x7a5
 istio.io/istio/operator/pkg/helmreconciler.(*HelmReconciler).ApplyManifest(0xc00180e190, 0x2e70eb0, 0xf, 0xc00305a000, 0x7b81, 0x0, 0x0, 0x0,
     istio.io/istio/operator/pkg/helmreconciler/apply.go:105 +0xc2f
 istio.io/istio/operator/pkg/helmreconciler.(*HelmReconciler).processRecursive.func1(0xc002bb5450, 0xc00180e190, 0x2e70eb0, 0xf, 0xc002bb5440,
     istio.io/istio/operator/pkg/helmreconciler/reconciler.go:192 +0x413
 created by istio.io/istio/operator/pkg/helmreconciler.(*HelmReconciler).processRecursive
     istio.io/istio/operator/pkg/helmreconciler/reconciler.go:169 +0x19f[]
 - Processing resources for Ingress gateways.panic: interface conversion: interface {} is nil, not []interface {} [recovered]
     panic: interface conversion: interface {} is nil, not []interface {}
```

Gateway spec from operator config:

```yaml
- enabled: true
  k8s:
    service:
      loadBalancerSourceRanges:
      - x.x.x.x/32
    serviceAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
  label:
    istio: private
  name: istio-ingressgateway-private
```

Looking at the code from stacktrace I see that it tries to copy ports from overlay, but it contains no override for `ports`. I have only override for `loadBalancerSourceRanges` through `k8s.service.loadBalancerSourceRanges`.

https://github.com/istio/istio/blob/f1aa586d3a2d0abd922d50077465ed96c53ff108/operator/pkg/helmreconciler/common.go#L129

https://github.com/istio/istio/blob/f1aa586d3a2d0abd922d50077465ed96c53ff108/operator/pkg/helmreconciler/common.go#L163

Could be a duplicate of https://github.com/istio/istio/issues/26507.

I can workaround this by specifying `ports` when `loadBalancerSourceRanges` is also present, but that is not expected.

**Expected behavior**

If there is no override for ports in overlay then don't try to save or require ports.

**Version**

1.8.1

**How was Istio installed?**

Istio operator helm chart (without istioctl).

**Environment where the bug was observed (cloud vendor, OS, etc)**

AWS EKS 1.18

**Comment by morvencao** [comment]
I'm curious whether it is working before you upgrade istio operator from 1.8.1 to 1.7.5.
I'm asking because you're customize the ingressgateway name to `istio-ingressgateway-private`, so the `ports` part is required. If you change the ingressgateway name to default one: ``istio-ingressgateway`, it should be working.

**Comment by howardjohn** [comment]
drive by comment: I am not familiar with the code, but as I user I would expect the config yaml in the issue to work. Port should not be required

**Comment by morvencao** [comment]
AFAIK, that's one of the differences between the build-in gateway and customized gateway.
We don't specify the `ports` in values.yaml or profile for customized gateway, that's why we need to manually specify the `ports`.

**Comment by svrakitin** [comment]
@morvencao It was working before. I downgraded back to 1.7.5 and it says that spec.ports is required as you mentioned. Not sure how we avoided that on 1.7.5🤔 I worked around it by specifying default ports explicitly and it even works on 1.8.1.

We run multiple ingress gateways in multi-tenant cluster. I expect every gateway service to use default ports if not mentioned otherwise. It seems like it is indeed a current behavior as far as you don't specify anything under k8s.service in gateway config like source ranges as it doesn't trigger service overlay 😄 Maybe we can make overlay fallback to default ports if these are nil.

**Comment by neelakansha85** [comment]
This seems like a bug possibly introduced in recent versions of istio. I applied the config to Istio Operator with version 1.7.3 and it worked fine without having to specify the ports explicitly as is the case in recent version.

**Comment by morvencao** [comment]
Istio-1.7.x also doesn't support this:
```
~/istio-1.7.3/bin/istioctl install -f iop-173.yaml
Detected that your cluster does not support third party JWT authentication. Falling back to less secure first party JWT. See https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens for details.
✔ Istio core installed
✔ Istiod installed
- Processing resources for Ingress gateways.                                                                                                                                                                                                2020-12-23T04:17:34.522243Z	error	installer	failed to create "Service/istio-system/istio-ingressgateway-private": Service "istio-ingressgateway-private" is invalid: spec.ports: Required value
✘ Ingress gateways encountered an error: failed to create "Service/istio-system/istio-ingressgateway-private": Service "istio-ingressgateway-private" is invalid: spec.ports: Required value
- Pruning removed resources
```
you need to either set ports with `service.ports` k8s setting or with legacy helm `values`:
1. `service.ports` k8s settings:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
    - namespace: istio-system
      name: istio-ingressgateway-private
      enabled: true
      label:
        istio: private
      k8s:
        ports:
        - port: 15021
          targetPort: 15021
          name: status-port
          protocol: TCP
        - port: 80
          targetPort: 8080
          name: http2
          protocol: TCP
        - port: 443
          targetPort: 8443
          name: https
          protocol: TCP
        - port: 15012
          targetPort: 15012
          name: tcp-istiod
          protocol: TCP
        - port: 15443
          targetPort: 15443
          name: tls
          protocol: TCP
```

2.  helm `values`:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
      istio-ingressgateway:
        name: istio-ingressgateway-private:
        ports:
        - port: 15021
          targetPort: 15021
          name: status-port
          protocol: TCP
        - port: 80
          targetPort: 8080
          name: http2
          protocol: TCP
        - port: 443
          targetPort: 8443
          name: https
          protocol: TCP
        - port: 15012
          targetPort: 15012
          name: tcp-istiod
          protocol: TCP
        - port: 15443
          targetPort: 15443
          name: tls
          protocol: TCP
```
