### ISSUE TITLE
spec.values.global.defaultNodeSelector is not applied to all components

### ISSUE THREAD

**Issue by omerfsen** [istio/istio#29642]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

pilot nodeSelector does not work

istiod

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

I expect istiod pods to be deployed on certian nodes

1. create istiooperator yaml file with `istioctl profile dump default`
2. Modify yaml with following (spec.values.global and spec.components.pilot )

```yaml

spec:
   values: 
      global:
        defaultNodeSelector:
          agentpool: service
    
  components:
    pilot:
        nodeSelector:
          agentpool: service
```

3. I expect istiod deployment to have  this nodeselectors so it runs on specific agent pool but they are not

**kubectl get deployments.apps -n istio-system istiod  -o yaml**  does not have any specification about nodeselector applied

**Version** 

istio 1.7.6

**How was Istio installed?**

istioctl install -f operatyor.yaml

**Environment where the bug was observed (cloud vendor, OS, etc)**

ANY

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by omerfsen** [comment]
Putting nodeSelector to 

"spec.values.pilot" worked but I think only providing 

```yaml

spec:
   values: 
      global:
        defaultNodeSelector:
          agentpool: service
```

should apply this nodeSelector to all components but it did not work
