### ISSUE TITLE
Blocked(v 1.6.8) in creating istio-certs(/etc/istio-certs) for prometheus with metadata annotations using proxy.istio.io config

### ISSUE THREAD

**Issue by varun-krishna** [istio/istio#29666]
Unable to fetch the certs for prometheus using the metadata annotations as specifed in istio docs 

Istio version : v 1.6.8

Below is the spec used 
```
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
        traffic.sidecar.istio.io/includeInboundPorts: ""   # do not intercept any inbound ports
        traffic.sidecar.istio.io/includeOutboundIPRanges: ""  # do not intercept any outbound traffic
        proxy.istio.io/config: |  # configure an env variable `OUTPUT_CERTS` to write certificates to the given folder
          proxyMetadata:
            OUTPUT_CERTS: /etc/istio-output-certs
        sidecar.istio.io/userVolume: '[{"name": "istio-certs", "emptyDir": {"medium":"Memory"}}]'  # mount the shared volume
        sidecar.istio.io/userVolumeMount: '[{"name": "istio-certs", "mountPath": "/etc/istio-output-certs"}]'
```

Any help here would be really helpful
