### ISSUE TITLE
istio-ingressgateway connection refused

### ISSUE THREAD

**Issue by zhaojizhuang** [istio/istio#29680]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
I install istio used `./istioctl install --set values.global.hub=registry.zjcdn.com/public/istio`

**1. And Pod,svc in istio-system is as follows:**

```shell
root@admin01.jscm03:~/faas_deploy/faas_deploy/istio-1.7.0/bin# kubectl get svc -n istio-system
NAME                   TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                                                      AGE
istio-ingressgateway   LoadBalancer   172.18.0.80     <pending>     15021:30228/TCP,80:32095/TCP,443:30590/TCP,15443:31217/TCP   24s
istiod                 ClusterIP      172.18.37.122   <none>        15010/TCP,15012/TCP,443/TCP,15014/TCP,853/TCP                29s


root@admin01.jscm03:~/faas_deploy/faas_deploy/istio-1.7.0/bin# kubectl get po -n istio-system
NAME                                    READY   STATUS    RESTARTS   AGE
istio-ingressgateway-76fcd45bf8-5j5d8   1/1     Running   0          36s
istiod-54945c988b-hr9zh                 1/1     Running   0          40s
```

**2. but when I curl ingress-istio-system,it is refused**

```shell
root@admin01.jscm03:~/faas_deploy/faas_deploy/istio-1.7.0/bin# curl 172.24.1.164:8080
curl: (7) Failed to connect to 172.24.1.164 port 8080: Connection refused
```

**3. enter the pod**  ,`8080` is not listened

```shell
root@admin01.jscm03:~/faas_deploy/faas_deploy/istio-1.7.0/bin# kubectl exec -it istio-ingressgateway-76fcd45bf8-5j5d8 -n istio-system bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.
istio-proxy@istio-ingressgateway-76fcd45bf8-5j5d8:/$ netstat -aunltp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:15021           0.0.0.0:*               LISTEN      43/envoy
tcp        0      0 0.0.0.0:15090           0.0.0.0:*               LISTEN      43/envoy
tcp        0      0 127.0.0.1:15000         0.0.0.0:*               LISTEN      43/envoy
tcp        0      0 127.0.0.1:49012         127.0.0.1:15020         ESTABLISHED 43/envoy
tcp        0      0 127.0.0.1:43518         127.0.0.1:15020         ESTABLISHED 43/envoy
tcp        0      0 172.24.1.164:48148      10.63.97.22:6443        ESTABLISHED 1/pilot-agent
tcp        0      0 172.24.1.164:57886      172.24.1.172:15012      ESTABLISHED 1/pilot-agent
tcp        0      0 127.0.0.1:37740         127.0.0.1:15020         ESTABLISHED 43/envoy
tcp        0      0 127.0.0.1:47382         127.0.0.1:15000         ESTABLISHED 1/pilot-agent
tcp        0      0 127.0.0.1:15000         127.0.0.1:47382         ESTABLISHED 43/envoy
tcp        0      0 172.24.1.164:37700      172.24.1.172:15012      ESTABLISHED 43/envoy
tcp6       0      0 :::15020                :::*                    LISTEN      1/pilot-agent
tcp6       0      0 127.0.0.1:15020         127.0.0.1:37740         ESTABLISHED 1/pilot-agent
tcp6       0      0 127.0.0.1:15020         127.0.0.1:43518         ESTABLISHED 1/pilot-agent
tcp6       0      0 127.0.0.1:15020         127.0.0.1:49012         ESTABLISHED 1/pilot-agent
```

**Affected product area (please put an X in all that apply)**

[X] Networking

**Expected behavior**
istio-ingressgateway work well
and 
`envoy listened on 8080 in istio-ingressgateway pod`

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
istio 1.7.0
**How was Istio installed?**

`./istioctl install --set values.global.hub=registry.zjcdn.com/public/istio`
**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by zhaojizhuang** [comment]
when I dump  envoy config in `problem` pod

![image](https://user-images.githubusercontent.com/3124692/102467544-612e7b00-408b-11eb-9d77-56df627da784.png)

Under normal circumstances, it should look like this

![image](https://user-images.githubusercontent.com/3124692/102467883-cf733d80-408b-11eb-874e-5ccda2845096.png)

**Comment by zhaojizhuang** [comment]
**check istiod’s log,  find that LDS  PUSH none listener**

```shell
2020-12-17T09:49:46.933427Z	info	ads	Pushing router~172.24.5.95~istio-ingressgateway-5bfcf785c-n8pdv.istio-system~istio-system.svc.bdcdn-tzcm-3
2020-12-17T09:49:46.935574Z	info	ads	CDS: PUSH for node:istio-ingressgateway-5bfcf785c-n8pdv.istio-system clusters:119 services:43 version:2020-12-17T09:49:46Z/44
2020-12-17T09:49:46.936474Z	info	ads	EDS: PUSH for node:istio-ingressgateway-5bfcf785c-n8pdv.istio-system clusters:118 endpoints:298 empty:44
2020-12-17T09:49:46.936580Z	info	ads	LDS: PUSH for node:istio-ingressgateway-5bfcf785c-n8pdv.istio-system listeners:0
```

Under normal circumstances, it should look like this

```shell
020-12-08T03:30:47.894676Z	info	ads	CDS: PUSH for node:istio-ingressgateway-6cfd75fc57-m2s2v.istio-system resources:2
2020-12-08T03:30:47.894940Z	info	ads	LDS: PUSH for node:istio-ingressgateway-6cfd75fc57-m2s2v.istio-system resources:2
2020-12-08T03:30:47.894997Z	info	ads	EDS: PUSH for node:istio-ingressgateway-6cfd75fc57-m2s2v.istio-system resources:1 empty:0 cached:1/1
2020-12-08T03:30:47.895616Z	info	ads	RDS: PUSH for node:istio-ingressgateway-6cfd75fc57-m2s2v.istio-system resources:2
```

**Comment by zhaojizhuang** [comment]
cc @howardjohn

**Comment by zhaojizhuang** [comment]
[X] Networking

**Comment by howardjohn** [comment]
You need a gateway and virtual service before it listens. See http://istio.io/help/bugs/#generating-a-cluster-state-archive and https://istio.io/latest/docs/tasks/traffic-management/ingress/

**Comment by zhaojizhuang** [comment]
> You need a gateway and virtual service before it listens. See http://istio.io/help/bugs/#generating-a-cluster-state-archive and https://istio.io/latest/docs/tasks/traffic-management/ingress/

@howardjohn Thank you, found it：For I haven't install knative component before it listens, which has some gateway and virtual service。Now it works well，Thank you very much。

**Comment by zhaojizhuang** [comment]
roblem solved, I will close this issue

**Comment by 631068264** [comment]
> You need a gateway and virtual service before it listens. See http://istio.io/help/bugs/#generating-a-cluster-state-archive and https://istio.io/latest/docs/tasks/traffic-management/ingress/

Can't understand what you mean . Can you give some example ?

**Comment by rayrapetyan** [comment]
For those who have landed here after googling for "istio ingress connection refused" - double check "istio" selector definition in your "Gateway". In most tutorials it's defined as:
`istio: ingressgateway`
This will not work for istio gateway installed by helm - you'll get "connection refused" errors with no traces in logs.
For helm installations it should be defined as:
`istio: ingress`

**Comment by Ivorlun** [comment]
> For those who have landed here after googling for "istio ingress connection refused" - double check "istio" selector definition in your "Gateway". In most tutorials it's defined as: `istio: ingressgateway` This will not work for istio gateway installed by helm - you'll get "connection refused" errors with no traces in logs. For helm installations it should be defined as: `istio: ingress`

You are literally life saver!

Thank you!

**Comment by seaurching** [comment]
@howardjohn I custom install istio by using istioctl, this is the svc's information for istio ingressgateway. 
![usbdingzhi](https://github.com/istio/istio/assets/7349963/85a03dc9-ab71-404c-9475-093e3ae0a603)
### Prepare for vs and gw like this
```
kind: Gateway
apiVersion: networking.istio.io/v1beta1
metadata:
  name: kiali
  namespace: kiali
spec:
  selector:
    ingress: gw-appz1p-by-in
  servers:
    - port:
        number: 80
        name: kiali
        protocol: HTTP
      hosts:
        - kiali.xpaas.lenovo.com
---
kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: kiali-ui
  namespace: kiali
spec:
  gateways:
    - kiali
  hosts:
    - kiali.xpaas.lenovo.com
  http:
    - retries:
        attempts: 3
      timeout: 5s
      name: kiali
      route:
        - destination:
            host: kiali.kiali.svc
            port:
              number: 20001
          weight: 100
```
tips connect refuse

**Comment by arafkarsh** [comment]
> For those who have landed here after googling for "istio ingress connection refused" - double check "istio" selector definition in your "Gateway". In most tutorials it's defined as: `istio: ingressgateway` This will not work for istio gateway installed by helm - you'll get "connection refused" errors with no traces in logs. For helm installations it should be defined as: `istio: ingress`

Thank you... I wish this is properly documented in Istio documentation.

**Comment by Nurlan199206** [comment]
not working for me... tricks with selector not helping. i've installed with `istioctl`

```
  selector:
    istio: ingressgateway
```

```
  selector:
    istio: ingress
```



```
nc -z -v -w 2 192.168.200.85 31892
nc: connect to 192.168.200.85 port 31892 (tcp) failed: Connection refused
```


```
kubectl -n istio-system get svc istio-ingressgateway
NAME                   TYPE       CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                      AGE
istio-ingressgateway   NodePort   10.100.149.141   <none>        15021:30347/TCP,80:31892/TCP,443:31423/TCP,31400:30426/TCP,15443:30861/TCP   19h
```

```
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: http-gateway
spec:
  # The selector matches the ingress gateway pod labels.
  # If you installed Istio using Helm following the standard documentation, this would be "istio=ingress"
  selector:
    istio: ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "test.dev-ops.kz"
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - "test.dev-ops.kz"
  gateways:
  - http-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: test-app
```
