### ISSUE TITLE
panic in pilot: GetAdapter (when Istio installed with enableAnalysis: true)

### ISSUE THREAD

**Issue by chlunde** [istio/istio#29709]
**Bug description**

```
{"level":"info","time":"2020-12-15T14:01:10.286585Z","scope":"source","msg":"CRD Discovery complete, starting listening to resources..."}
{"level":"info","time":"2020-12-15T14:01:10.286673Z","scope":"source","msg":"Creating watchers for Kubernetes CRDs"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x229b371]
goroutine 2441 [running]:
istio.io/istio/galley/pkg/config/source/kube/rt.(*Provider).GetAdapter(0x0, 0x32b7560, 0xc002527a20, 0x1)
        istio.io/istio/galley/pkg/config/source/kube/rt/provider.go:70 +0x91
istio.io/istio/galley/pkg/config/source/kube/apiserver.(*Source).startWatchers(0xc0025cee70)
        istio.io/istio/galley/pkg/config/source/kube/apiserver/source.go:196 +0x356
istio.io/istio/galley/pkg/config/source/kube/apiserver.(*Source).onCrdEvent(0xc0025cee70, 0x4, 0x32a0ec0, 0xc000af62c0, 0x0)
        istio.io/istio/galley/pkg/config/source/kube/apiserver/source.go:167 +0x4b6
istio.io/istio/pkg/config/event.(*fnHandler).Handle(0xc0029884f0, 0x4, 0x32a0ec0, 0xc000af62c0, 0x0)
        istio.io/istio/pkg/config/event/handler.go:53 +0x51
created by istio.io/istio/galley/pkg/config/source/kube/apiserver.(*watcher).start
        istio.io/istio/galley/pkg/config/source/kube/apiserver/watcher.go:92 +0x68f
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
No panics

**Steps to reproduce the bug**
Unknown, install and wait

**Version**
1.8.1, and also 1.9 from master:
```
$ istioctl version --remote
client version: 1.8.1
control plane version: 1.9-dev-60d7bd3009493eb4e55ee61fcfe0162a1a813b74
data plane version: 1.8.1 (4 proxies), 1.9-dev (1 proxies)

$ kubectl version --short
Client Version: v1.20.0
Server Version: v1.18.9-eks-d1db3c
```

**How was Istio installed?**
Istio 1.8.1 manifests

**Environment where the bug was observed (cloud vendor, OS, etc)**
EKS

With a slight patch to master, we get more info about the crash:
```diff
diff --git a/galley/pkg/config/source/kube/apiserver/source.go b/galley/pkg/config/source/kube/apiserver/source.go
index ecfb77f7f9..cb4056a0af 100644
--- a/galley/pkg/config/source/kube/apiserver/source.go
+++ b/galley/pkg/config/source/kube/apiserver/source.go
@@ -193,15 +193,16 @@ func (s *Source) startWatchers() {
        scope.Source.Info("Creating watchers for Kubernetes CRDs")
        s.watchers = make(map[collection.Name]*watcher)
        for i, r := range resources {
-               a := s.provider.GetAdapter(r.Resource())
+               scope.Source.Infof("[%d]", i)
+               scope.Source.Infof("  Name:              %s", r.Name())
+               scope.Source.Infof("  Disabled:     %v", r.IsDisabled())
+               scope.Source.Infof("  Source:       %s", r.Resource().GroupVersionKind())
 
+               a := s.provider.GetAdapter(r.Resource())
                found := s.foundResources[asKey(r.Resource().Group(), r.Resource().Kind())]
 
-               scope.Source.Infof("[%d]", i)
-               scope.Source.Infof("  Source:       %s", r.Resource().GroupVersionKind())
-               scope.Source.Infof("  Name:              %s", r.Name())
                scope.Source.Infof("  Built-in:     %v", a.IsBuiltIn())
-               scope.Source.Infof("  Disabled:     %v", r.IsDisabled())

```

```
{"level":"info","time":"2020-12-18T17:22:29.024089Z","scope":"source","msg":"CRD Discovery complete, starting listening to resources..."}
{"level":"info","time":"2020-12-18T17:22:29.024152Z","scope":"source","msg":"Creating watchers for Kubernetes CRDs"}
{"level":"info","time":"2020-12-18T17:22:29.024158Z","scope":"source","msg":"[0]"}
{"level":"info","time":"2020-12-18T17:22:29.024163Z","scope":"source","msg":"  Name:  \t\t k8s/apiextensions.k8s.io/v1beta1/customresourcedefinitions"}
{"level":"info","time":"2020-12-18T17:22:29.024167Z","scope":"source","msg":"  Disabled:     true"}
{"level":"info","time":"2020-12-18T17:22:29.024173Z","scope":"source","msg":"  Source:       apiextensions.k8s.io/v1beta1/CustomResourceDefinition"}
{"level":"info","time":"2020-12-18T17:22:29.024186Z","msg":"[Schema](CustomResourceDefinition, \"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1\", k8s.io.apiextensions_apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinition)"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x230ab11]

goroutine 46147 [running]:
istio.io/istio/galley/pkg/config/source/kube/rt.(*Provider).GetAdapter(0x0, 0x332c7c0, 0xc0039ebe40, 0x2)
        istio.io/istio/galley/pkg/config/source/kube/rt/provider.go:77 +0x111
istio.io/istio/galley/pkg/config/source/kube/apiserver.(*Source).startWatchers(0xc003dfb290)
        istio.io/istio/galley/pkg/config/source/kube/apiserver/source.go:201 +0x61d
istio.io/istio/galley/pkg/config/source/kube/apiserver.(*Source).onCrdEvent(0xc003dfb290, 0x4, 0x3316520, 0xc000960140, 0x0)
        istio.io/istio/galley/pkg/config/source/kube/apiserver/source.go:167 +0x4a8
istio.io/istio/pkg/config/event.(*fnHandler).Handle(0xc005b810f8, 0x4, 0x3316520, 0xc000960140, 0x0)
        istio.io/istio/pkg/config/event/handler.go:53 +0x51
created by istio.io/istio/galley/pkg/config/source/kube/apiserver.(*watcher).start
        istio.io/istio/galley/pkg/config/source/kube/apiserver/watcher.go:92 +0x68f
```

**Comment by hzxuzhonghu** [comment]
How do you install istio

**Comment by larhauga** [comment]
> How do you install istio

@hzxuzhonghu We install istio with the `istio-operator` through flux where the yaml is generated from the helm chart:

```
helm template istio-repo/manifests/charts/istio-operator/ \
  --set hub=docker.io/istio \
  --set tag=1.8.1 \
  --set operatorNamespace=istio-operator \
  --set enableCRDTemplates=true \
  --set watchedNamespaces=istio-system > istio-operator.yaml
```

Our IstioOperator config is the following:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-operator
  namespace: istio-system
spec:
  profile: preview
  components:
    egressGateways:
    - name: istio-egressgateway
      enabled: true

    ingressGateways:
    - name: istio-internal-ingressgateway
      enabled: true
      k8s:
        overlays: # This object will modify default properties of the component
          - kind: HorizontalPodAutoscaler
            name: istio-internal-ingressgateway
            patches:
              - path: metadata.labels.app
                value: istio-internal-ingressgateway
              - path: metadata.labels.istio
                value: internal-ingressgateway
              - path: spec.scaleTargetRef.name
                value: istio-internal-ingressgateway
          - kind: Deployment
            name: istio-internal-ingressgateway
            patches:
              - path: metadata.labels.app
                value: istio-internal-ingressgateway 
              - path: metadata.labels.istio
                value: internal-ingressgateway
              - path: spec.selector.matchLabels.app
                value: istio-internal-ingressgateway
              - path: spec.selector.matchLabels.istio
                value: internal-ingressgateway
              - path: spec.template.metadata.labels.app
                value: istio-internal-ingressgateway
              - path: spec.template.metadata.labels.istio
                value: internal-ingressgateway
          - kind: Service
            name: istio-internal-ingressgateway
            patches:
              - path: metadata.labels.app
                value: istio-internal-ingressgateway
              - path: metadata.labels.istio
                value: internal-ingressgateway
              - path: spec.selector.app
                value: istio-internal-ingressgateway
              - path: spec.selector.istio
                value: internal-ingressgateway
              - path: metadata.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-internal
                value: "true"
              - path: metadata.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-type
                value: nlb-ip
              - path: metadata.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-healthcheck-port
                value: "15021"
              - path: metadata.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-healthcheck-path
                value: "/healthz/ready"
              - path: metadata.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-healthcheck-protocol
                value: HTTP
              - path: metadata.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-healthcheck-healthy-threshold
                value: "3"
              - path: metadata.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-healthcheck-interval
                value: "10"
              - path: metadata.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-healthcheck-timeout
                value: "6"
              - path: metadata.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-healthcheck-unhealthy-threshold
                value: "3"
  meshConfig:
    accessLogFile: /dev/stdout
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
    accessLogEncoding: 'JSON'
    #accessLogFormat: '{"start_time": "%START_TIME%","req_method": "%REQ(:METHOD)%","x_envoy_original_path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%","protocol": "%PROTOCOL%","response_code": "%RESPONSE_CODE%","response_flags": "%RESPONSE_FLAGS%","bytes_received": "%BYTES_RECEIVED%","bytes_send": "%BYTES_SENT%","duration": "%DURATION%","resp_x_envoy_upstream_service_time": "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%","x_forwarded_for": "%REQ(X-FORWARDED-FOR)%","user_agent": "%REQ(USER-AGENT)%","x_request_id": "%REQ(X-REQUEST-ID)%","authority": "%REQ(:AUTHORITY)%","upstream_host": "%UPSTREAM_HOST%","upstream_cluster": "%UPSTREAM_CLUSTER%","upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%","downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%","downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%","resp_x_foo_fault_flag": "%RESP(X-FOO-FAULT-FLAG)%"}'
    enableTracing: true
    defaultConfig:
      gatewayTopology:
        numTrustedProxies: 2
      tracing: 
        zipkin:
          address: zipkin.istio-system.svc.cluster.local:9411
        sampling: 100 # in %

  values:
    global:
      istiod:
        enableAnalysis: true
      logAsJson: true
    gateways:
      istio-ingressgateway:
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-type: "alb"
    pilot:
      traceSampling: 100
```
