### ISSUE TITLE
Additional gateways in IOP create duplicate PodDisruptionBudgets

### ISSUE THREAD

**Issue by rvennam** [istio/istio#29707]
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: custom-ingressgateway-iop
spec:
  profile: empty
  components:
    ingressGateways:
      - name: custom-ingressgateway-1
        enabled: true
      - name: custom-ingressgateway-2
        enabled: true

```
generates these two PDB:
```
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: custom-ingressgateway-1
  namespace: istio-system
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
    istio.io/rev: default
    install.operator.istio.io/owning-resource: unknown
    operator.istio.io/component: "IngressGateways"
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: custom-ingressgateway-2
  namespace: istio-system
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
    istio.io/rev: default
    install.operator.istio.io/owning-resource: unknown
    operator.istio.io/component: "IngressGateways"
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
```

Notice that the `matchLabels` for both PDB are the same. 

This causes problems during draining node:
```
This pod has more than one PodDisruptionBudget, which the eviction subresource does not support.
```

Should the match labels use a different selector that is unique to each gateway? such as:
`service.istio.io/canonical-name=custom-ingressgateway-2`

[ ] Docs
[ X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Should the match labels use a different selector? such as:
`service.istio.io/canonical-name=custom-ingressgateway-2`

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.7.6

**How was Istio installed?**
istioctl manifest generate

**Environment where the bug was observed (cloud vendor, OS, etc)**
IBM Cloud Kubernetes

**Comment by rvennam** [comment]
cc @linsun

**Comment by linsun** [comment]
Thanks @rvennam for reporting this, makes sense to me.

Hi @morvencao - would like to get your thoughts?  I think there are 2 possible ways to fix this:
- if we could detect a PDB for a given label selector for ingress gateway for a ns has been created, we don't create any further PDBs.
- If the first option is not possible, allow ingress gateway to tell us if they want to have PDB created as part of the ingress gw.

cc @sdake @ostromart @costinm

**Comment by morvencao** [comment]
@rvennam @linsun 
In this case we should add label that is unique to each gateway:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: custom-ingressgateway-iop
spec:
  profile: empty
  components:
    ingressGateways:
      - name: custom-ingressgateway-1
        enabled: true
        label:
          app: custom-ingressgateway-1
      - name: custom-ingressgateway-2
        enabled: true
        label:
          app: custom-ingressgateway-2
```

Then the operator will create different PDB for different gateway, with unique `matchLabels`:

```
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: custom-ingressgateway-1
  namespace: istio-system
  labels:
    app: custom-ingressgateway-1
    istio: ingressgateway
    release: istio
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: custom-ingressgateway-1
      istio: ingressgateway
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: custom-ingressgateway-2
  namespace: istio-system
  labels:
    app: custom-ingressgateway-2
    istio: ingressgateway
    release: istio
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: custom-ingressgateway-2
      istio: ingressgateway
---
```

**Comment by rvennam** [comment]
@morvencao Thanks!

Is it safe for us to use a new label instead of `app`? For example:
```
    ingressGateways:
      - name: custom-ingressgateway-1
        label:
            gateway: zone1
        enabled: true
      - name: custom-ingressgateway-2
        enabled: true
        label:
            gateway: zone2
```
