### ISSUE TITLE
Support inverse header match in AuthorizationPolicy

### ISSUE THREAD

**Issue by yanniszark** [istio/istio#29710]
**Describe the feature request**

The AuthorizationPolicy matches traffic based on a number of conditions and then takes an action. However, it can't match the condition:
`Request does NOT have header X.`

We'd like to add support for this feature.
After looking around a bit, I found the part of Istio which translates the header match YAML to Envoy configuration:
https://github.com/istio/istio/blob/71f09fe8a8122f7b489b0305adf590bfbe0a0ba8/pilot%2Fpkg%2Fsecurity%2Fauthz%2Fmodel%2Fmatcher%2Fheader.go#L24-L56

From that, I found out that Envoy actually supports inverse matching:
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-headermatcher

And actually, this feature is used in VirtualServices, to implement the `withoutHeaders` field, which is exactly what we need:
https://github.com/istio/istio/blob/372f1427c41abba18639fc04dcf73a80177222cd/pilot%2Fpkg%2Fnetworking%2Fcore%2Fv1alpha3%2Froute%2Froute.go#L626-L630

I think the main difficulty is to decide on what the UX will be. Right now, conditions are written in pseudo-code, while in VirtualService they are written in YAML. I'd love to have some suggestion on how to express this inverse matching in AuthorizationPolicy.

BTW, you can assign this issue to me, I believe I can implement it once we agree on the UX.

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by yangminzhu** [comment]
a quick question, have you tried using the `notValues` for the negative matching? for example:

```yaml
apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
  name: "httpbin-header"
  namespace: default
spec:
  selector:
    matchLabels:
      app: httpbin
  rules:
  - when:
    - key: request.headers[foo]
      notValues: ["*"]
```
