### ISSUE TITLE
Proxy readiness probe failureThreshold is too high

### ISSUE THREAD

**Issue by cagataygurturk** [istio/istio#29727]
**Describe the feature request**

By default istio-proxy's failureThreshold is set to 30 and periodSeconds to 2. This means that it takes 60 seconds for Kubernetes to take a not ready or failing proxy out of load balancing pool. For normal applications, users tend to set these values to more custom ones, so they can respond to failures more quickly. However these values are also applied to Ingress and Egress gateways.

Responding to failures quickly by setting these values to a lower values is quite important for users who run clusters where nodes are frequently replaced due to preemptible vm/spot instance usage or users who apply any other chaos engineering techniques.

I do not want to rush to a conclusion that these default values are too high and I know that these are totally configurable but I also wonder community's opinion about setting these values lower a bit.

[ ] Docs
[x] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by hzxuzhonghu** [comment]
30 is not reasonable, we should make it small, note k8s default value is 3.

```
    readinessProbe:
      failureThreshold: 30
      httpGet:
        path: /healthz/ready
        port: 15021
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 2
      successThreshold: 1
      timeoutSeconds: 3
```

I think the periodSeconds and timeoutSeconds is not reasonable as well. IMO, the period should be larger than the timeout.
