### ISSUE TITLE
The case of the disappearing VirtualService route (from Gateway after EnvoyFilter added)

### ISSUE THREAD

**Issue by haf** [istio/istio#29734]
**Bug description**

Applying an EnvoyFilter sometimes disappears virtual services from the route table of the gateway. 

Maybe this is just me not understanding how to opt out of a filter via a MERGE operation; in which case I'd be happy take instruction. It's not really documented.

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

The VS:es should not just stop being routable

**Steps to reproduce the bug**

EnvoyFilter:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ext-authz
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway

  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              name: envoy.router

    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.ext_authz
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.http.ext_authz.v2.ExtAuthz
          failure_mode_allow: false
          # https://www.envoyproxy.io/docs/envoy/v1.16.1/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto#envoy-v3-api-msg-extensions-filters-http-ext-authz-v3-httpservice
          http_service:
            server_uri:
              uri: http://oauth2-proxy.auth.svc.cluster.local
              cluster: outbound|80||oauth2-proxy.auth.svc.cluster.local
              timeout: 5s
            # https://www.envoyproxy.io/docs/envoy/v1.16.1/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto#extensions-filters-http-ext-authz-v3-authorizationrequest
            authorization_request:
              # https://www.envoyproxy.io/docs/envoy/v1.16.1/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto#envoy-v3-api-field-extensions-filters-http-ext-authz-v3-authorizationrequest-allowed-headers
              allowed_headers:
                patterns:
                - exact: cookie
                - exact: authorization
                - exact: x-auth-request-redirect
                - prefix: x-forwarded
              # For some reason this field are not documented in the v2 schema docs at Envoy
              # https://www.envoyproxy.io/docs/envoy/v1.16.1/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto#envoy-v3-api-field-extensions-filters-http-ext-authz-v3-authorizationrequest-headers-to-add
              # kubectl sniff oauth2-proxy-867fd547fc-w6drx -n auth -f 'port 4180'
              headers_to_add:
              - key: x-auth-request-redirect
                value: "https://%REQ(:AUTHORITY)%%REQ(:PATH)%"
            authorization_response:
              allowed_client_headers:
                patterns:
                - exact: set-cookie
                - exact: authorization

  # Skip requiring Bearer tokens when logging in:
  # https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-EnvoyConfigObjectPatch
  - applyTo: VIRTUAL_HOST
    # https://istio.io/docs/reference/config/networking/envoy-filter/#EnvoyFilter-EnvoyConfigObjectMatch
    match:
      # https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-PatchContext
      context: GATEWAY
      # https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-RouteConfigurationMatch
      routeConfiguration:
        gateway: istio-system/ingress
        # https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-RouteConfigurationMatch-VirtualHostMatch
        vhost:
          name: accounts.example.com:443
          # route: ...
    patch:
      # https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-Patch-Operation
      operation: MERGE
      # -------- Envoy record is merged with the value
      # https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#struct
      value:
        name: envoy.ext_authz_disabled
        # https://www.envoyproxy.io/docs/envoy/v1.16.1/api-v3/config/route/v3/route_components.proto.html?highlight=per_filter_config
        typed_per_filter_config:
          envoy.filters.http.ext_authz:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute
            disabled: true

  # Our ingress should be accessible publicly
  - applyTo: VIRTUAL_HOST
    # https://istio.io/docs/reference/config/networking/envoy-filter/#EnvoyFilter-EnvoyConfigObjectMatch
    match:
      context: GATEWAY
      routeConfiguration:
        gateway: istio-system/ingress
        vhost:
          name: i.example.com:443
    patch:
      operation: MERGE
      value:
        name: envoy.ext_authz_disabled
        typed_per_filter_config:
          envoy.filters.http.ext_authz:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute
            disabled: true
```

And then add a VS for accounts.example.com and another for i.example.com and run

```
$ istioctl pc route istio-ingressgateway-68dfd96487-5gz2s -n istio-system
NOTE: This output only contains routes loaded via RDS.
NAME                                             DOMAINS                  MATCH                  VIRTUAL SERVICE
https.443.https-default.ingress.istio-system     accounts.example.com     /*                     oauth2-proxy.auth
http.80                                          *.example.com            /*                     404
http.80                                          example.com              /*                     404
                                                 *                        /healthz/ready*
                                                 *                        /stats/prometheus*
```

^^ i.example.com is missing.

Now remove the EnvoyFilter, and this line is also visible:

```
https.443.https-default.ingress.istio-system     i.example.com            /*                     i-example-com.ingress
```

Background info, the gateway is standard:

```yaml
apiVersion: v1
items:
- apiVersion: networking.istio.io/v1beta1
  kind: Gateway
  metadata:
    name: ingress
    namespace: istio-system
  spec:
    selector:
      istio: ingressgateway
    servers:
    - hosts:
      - '*.example.com'
      - examople.com
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
      - '*.example.com'
      - example.com
      port:
        name: https-default
        number: 443
        protocol: HTTPS
      tls:
        credentialName: example-com-tls
        mode: SIMPLE
        privateKey: sds
        serverCertificate: sds
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
$ istioctl version --remote
client version: 1.8.1
control plane version: 1.8.1
data plane version: 1.8.1 (27 proxies)
```

```
$ kubectl version --short
Client Version: v1.20.0
Server Version: v1.17.13-gke.2001
```
**How was Istio installed?**

`istioctl operator init`

**Environment where the bug was observed (cloud vendor, OS, etc)** GKE 1.17.x stable chan

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

E-mail me at henrik at haf dot se

**Comment by howardjohn** [comment]
The only reason an EnvoyFilter like this should cause it to be complete removed is if the config is rejected entirely. Do istiod logs show anything like `ACK ERROR`? Its also in the proxy logs

**Comment by hzxuzhonghu** [comment]
Noticed you are using v2 ext_auth, change it to v3

**Comment by haf** [comment]
No, no ACK errors at all. There's a bunch of warnings when this is applied that `Failed to find port for service my-ns/my-app: no suitable port for manifest`

**Comment by haf** [comment]
Could you provide an example that works, perhaps? It would seem I'm not alone in trying to make this work on the latest istio?

**Comment by haf** [comment]
@hzxuzhonghu You suggestion did not work:

```
    patch:
      operation: INSERT_BEFORE
      value:
        # https://www.envoyproxy.io/docs/envoy/v1.16.1/configuration/http/http_filters/ext_authz_filter#per-route-configuration
        name: envoy.filters.http.ext_authz
        typed_config:
          # https://www.envoyproxy.io/docs/envoy/v1.16.1/configuration/http/http_filters/ext_authz_filter#configuration-examples
          # https://www.envoyproxy.io/docs/envoy/v1.16.1/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto#envoy-v3-api-msg-extensions-filters-http-ext-authz-v3-extauthz
          # https://www.envoyproxy.io/docs/envoy/v1.16.1/api-v2/config/filter/network/ext_authz/v2/ext_authz.proto
          # "@type": type.googleapis.com/envoy.config.filter.http.ext_authz.v2.ExtAuthz
          "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
```

**Comment by haf** [comment]
I get this warning message, but I'm not sure if it's relevant:

```
-5dcd995fdc-qwx67.app resources:21"}
istiod-7bfb849f9d-hpvhc discovery {"level":"info","time":"2020-12-22T12:24:54.090049Z","scope":"ads","msg":"Push Status: {\n    \"pilot_conflict_outbound_listener_tcp_over_current_tcp\": {\n        \"169.254.169.254:443\": {\n            \"proxy\": \"analytics-db-5dcd995fdc-qwx67.app\",\n            \"message\": \"Listener=169.254.169.254:443 AcceptedTCP=metadata.google.internal RejectedTCP=storage.googleapis.com TCPServices=1\"\n        }\n    },\n    \"pilot_vservice_dup_domain\": {\n        \"metadata.google.internal:80\": {\n            \"proxy\": \"analytics-db-5dcd995fdc-qwx67.app\",\n            \"message\": \"duplicate domain from  service: metadata.google.internal:80\"\n        },\n        \"storage.googleapis.com:80\": {\n            \"proxy\": \"rutta-79d8978dd8-2nxzv.ingress\",\n            \"message\": \"duplicate domain from  service: storage.googleapis.com:80\"\n        }\n    }\n}"}
```

Which comes from this:

```
# https://github.com/istio/istio/issues/5288#issuecomment-455600510
# https://istio.io/latest/docs/reference/config/networking/service-entry/
# https://github.com/istio/istio/issues/10951
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: gcp-metadata
spec:
  hosts:
  # - "www.googleapis.com"
  - metadata.google.internal
  - storage.googleapis.com
  addresses:
  - "169.254.169.254/32" # metadata.google.internal
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  - number: 80
    name: http
    protocol: HTTP
```

But I don't see the link to `rutta`, the service behind `i.example.com` in my example above.

**Comment by haf** [comment]
Will be improved in the future https://github.com/istio/istio/issues/27790

**Comment by haf** [comment]
Perhaps https://www.paraesthesia.com/archive/2020/09/03/setting-up-oauth2-proxy-with-istio/ is a solution: with explicit opt-in per service as a workaround?

**Comment by haf** [comment]
Trying the above doesn't work: 1) if I only use the request authentication — it still shows up without me authenticating first. 2) if I also try to set an AuthorizationPolicy I get https://github.com/istio/istio/issues/29747

**Comment by haf** [comment]
Also, if I use 

```
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          sni: jaeger.logary.tech
          filter:
            name: envoy.http_connection_manager
            subFilter:
              name: istio.metadata_exchange

```

The SNI doesn't seem to matter, but if I remove the `sni` "selector" from the above filter, all request have authn required!!!
