### ISSUE TITLE
Istio operator - allow istio deployments to have custom `app` label name

### ISSUE THREAD

**Issue by xeviknal** [istio/istio#29742]
**Bug description**
Users may decide to use a different `app` label name for they deployments. The specific use case, users following the recommended kubernetes labels[1] (e.g. `app.kubernetes.io/name`).

In that case, Istio Operator doesn't allow users to change that label for the istio deployments (istiod, ingress, egress)[2]. This adds an inconsistency in the deployment, making the user deployments have one app label name and the istio deployments a hard-coded `app` label name.

Should the istio operator has a config to customize the `app` label name.
In kiali, there is the option to customize both `app` and `version` label names through the Kiali CR[3].

[1] https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels
[2] https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/templates/deployment.yaml#L34-L46
[3] https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L605-L614

Related to https://github.com/kiali/kiali/issues/3543

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Users install Istio and are able to specify the custom `app` label (e.g. `app.kubernetes.io/name`).
The resulting deployments should have the label `app.kubernetes.io/name` instead of the `app` label.

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    prometheus.io/port: "15014"
    prometheus.io/scrape: "true"
    sidecar.istio.io/inject: "false"
  creationTimestamp: "2020-12-17T12:20:30Z"
  generateName: istiod-7c9875bf99-
  labels:
    app.kubernetes.io/name: istiod
    install.operator.istio.io/owning-resource: unknown
    istio: pilot
    istio.io/rev: default
    operator.istio.io/component: Pilot
    pod-template-hash: 7c9875bf99
  name: istiod-7c9875bf99-8b8q2
  namespace: istio-system
spec:
[....]
```

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
