### ISSUE TITLE
DestinatinoRule.TLS.Simple Does not Work for ServiceEntry typed service.

### ISSUE THREAD

**Issue by florianislitzer** [istio/istio#29746]
**Bug description**

We have two clusters communicating over grpc using Istio. The goal is to run the java client/server in plaintext mode and let Istio handle TLS. With the current setup all requests fail with a "unexpected EOS on DATA frame" exepection on the client side. 
It´s working if the client side is configured to useTransportSecurity by java code or if grpcurl is used. Therefore our assumption is that the Istio configuration on the client side has errors or is incomplete. 

``

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-system-service-entry
  namespace: test
spec:
  hosts:
    - data-hub.grpc.test
  location: MESH_EXTERNAL
  ports:
    - number: 5001
      name: http-port
      protocol: HTTP
    - number: 443
      name: https-port
      protocol: HTTPS
  resolution: DNS

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: external-system-dest-rule
  namespace: test
spec:
  host: data-hub.grpc.test
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 443
        tls:
          mode: SIMPLE
          sni: data-hub.grpc.test


apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: external-system-virtual-service
  namespace: test
spec:
  hosts:
    - data-hub.grpc.test
  http:
    - match:
        - port: 5001
      route:
        - destination:
            host: data-hub.grpc.test
            port:
              number: 443
```
``

Are there any obvious problems in our client-side istio configuration or is something missing? 

**Affected product area **
[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features**

**Expected behavior**
Istio should handle mTLS/TLS between two clusters, Java grpc server/client should use plaintext. 

**Version** 
1.74

**How was Istio installed?**
istioctl 

**Environment where the bug was observed (cloud vendor, OS, etc)**
k8s 1.19
