### ISSUE TITLE
[gateways] k8s.nodeSelector does not override defaultNodeSelector on _affinity.yaml (`nodeAffinityRequiredDuringScheduling`)

### ISSUE THREAD

**Issue by n0n0x** [istio/istio#29758]
**Bug description**

when setting `k8s.nodeSelector` on an `ingressGateways`, the `defaultNodeSelector` does not get overridden in `manifests/charts/gateways/istio-ingress/templates/_affinity.tpl` section `nodeAffinityRequiredDuringScheduling`:

https://github.com/istio/istio/blob/4461a6b2324bceabd6f0ef3896ca1ca338180c45/manifests/charts/gateways/istio-ingress/templates/_affinity.tpl#L22-L28

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[x] Upgrade

**Expected behavior**

`nodeAffinityRequiredDuringScheduling` should honor value set in `k8s.nodeSelector` over `values.global.defaultNodeSelector`

**Steps to reproduce the bug**

* **Example 1**
```yaml
...
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          nodeSelector:
           key1: value1
  values:
    global:
      defaultNodeSelector:
        key2: value2
...
```
run: `istioctl manifest generate -f test.yaml > generated.yaml`

Deployment result:
```yaml
...
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
              - key: key2
                operator: In
                values:
                - value2
...
```

* **Example 2**
```yaml
...
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          nodeSelector:
           key1: value1
  values:
    global:
      defaultNodeSelector: {}
...
```
run: `istioctl manifest generate -f test.yaml > generated.yaml`

Deployment result:
```yaml
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
$ istioctl version --remote
client version: 1.6.8
pilot version: 1.6.8
data plane version: 1.6.8 (205 proxies)

$ kubectl version --short
Client Version: v1.16.8
Server Version: v1.16.8
```

**How was Istio installed?**

I think it was installed via helm then migrated to istioctl

**Comment by morvencao** [comment]
`k8s.nodeSelector` overrides `values.global.defaultNodeSelector`, but if `k8s.nodeSelector` is defined, `values.global.defaultNodeSelector` will be ignored.

**Comment by n0n0x** [comment]
You are right:

```yaml
...
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          nodeSelector:
            key1: value1
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                    - key: key3
                      operator: In
                      values:
                      - value3
  values:
    global:
      defaultNodeSelector:
        key2: value2
...
```

returns:

```yaml
...
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: key3
                operator: In
                values:
                - value3
 ...
```

but variables are quite confusing. I expected `values.global.defaultNodeSelector` override `k8s.nodeSelector` and maybe have a `values.global.defaultAffinityNodeSelector` that overrides affinity settings.

**Comment by morvencao** [comment]
1. `k8s.nodeSelector` take priority over legacy helm values. eg. `values.global. defaultNodeSelector `, because k8s overlay setting will applied after the manifest is generated.
2. I do find it is confusing for the different configuration, I believe the the legacy helm values. eg. `values.global.defaultNodeSelector` will be finally removed.
3. My suggestion is that don't use the legacy helm values, use k8s overlay setting. eg:
```
...
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          nodeSelector:
            key1: value1
```

This will only apply `key1: value1` nodeSelector to the ingressgateway.
