### ISSUE TITLE
Proxy pass jwt to application

### ISSUE THREAD

**Issue by alexandershelega** [istio/istio#29762]
Hi, 
I have bootspring application microcervices which communicate with each other with native oidc/jwt  implementation. 
Problem is the istio sidecar is not delivering jwt to my application and microcervices can't authentificate with each other.
Please advice how we can proxy pass jwt token thrue istio proxy to my application.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

1.8.1

**How was Istio installed?**

istioctl minimal profile, single cluster, single net

**Environment where the bug was observed (cloud vendor, OS, etc)**

gke

**Comment by howardjohn** [comment]
Are you using RequestAuthentication? if you so you can configure https://istio.io/latest/docs/reference/config/security/jwt/#JWTRule forwardOriginalToken

**Comment by papovyr** [comment]
@howardjohn Thanks for response 
There is no RequestAuthentication set.
We was trying to add sidecars to existing namespace where application runs, Application already uses OIDC(done on app level) for internal communication/Authentication.

Can we create empty RequestAuthentication to enable forwardOriginalToken 

like :
```
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: oidcforward
  namespace: dev
spec:
  jwtRules:
  - issuer: "issuer-foo" # required
    forwardOriginalToken: true
```
Or there are other ways to achieve this ? 

Please advice
