### ISSUE TITLE
Can istio support the InternalRedirectPolicy configuration for data plane envoy?

### ISSUE THREAD

**Issue by SpecialYang** [istio/istio#29782]
In our case, we need to trigger internal redirect according to the upstream response code. We found that the feature was supported by envoy, which was configured in VirtualHost. Can istio support the InternalRedirectPolicy configuration for data plane envoy?

referenced document:
- https://github.com/envoyproxy/envoy/blob/v1.16.0/api/envoy/config/route/v3/route_components.proto#L1827
- https://www.envoyproxy.io/docs/envoy/v1.16.0/api-v3/config/route/v3/route_components.proto.html?highlight=internalredirectpolicy#envoy-v3-api-msg-config-route-v3-internalredirectpolicy

**Comment by howardjohn** [comment]
I am a bit worried about the runtime and API complexity of this feature. It would be good to configure this with https://istio.io/docs/reference/config/networking/envoy-filter/ to test it out in the time being, which allows you to directly configure the route config.

**Comment by shortwavedave** [comment]
I have a third-party workload that is issuing a redirect. This service is accessed through a path-based virtual service prefix match, but the redirect does not get re-written. It seems that this situation is configured vie internal redirect policy. How would I write a filter to fix the response?

here's a link to the documentation:

https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_connection_management#:~:text=Internal%20redirects,response%20to%20the%20original%20request.

Here is my filter so far:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: wga121-redirect
  namespace: wga121
spec:
  workloadSelector:
    labels:
      app: wga121
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
        name: "envoy.filters.network.http_connection_manager"
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          config:
            route_config:
              internal_redirect_policy:
                max_internal_redirects: 5
                allow_cross_scheme_redirect: true
```

I get this error if I try to apply it:

`unknown field "config" in envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager`

Any ideas?
