### ISSUE TITLE
DNS resolution problems for service entries

### ISSUE THREAD

**Issue by alexandershelega** [istio/istio#29806]
Hi,
We have two ServiceEntres in same namespace for two deferent mongos.
Current  application connect to only main-mongodb-se. (main-db1-[1-3].c.internal-ai.internal )

see ServiceEntry configuration below
```
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: main-mongodb-se
spec:
  hosts:
    - main-db1-1.c.internal-ai.internal
    - main-db1-2.c.internal-ai.internal
    - main-db1-3.c.internal-ai.internal
  exportTo:
  - "."
  ports:
    - name: main-mongo-clients
      number: 27017
      protocol: TCP
  location: MESH_EXTERNAL
  resolution: NONE

---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: dcs-mongodb-se
spec:
  hosts:
    - dcsdb1-1.c.internal-ai.internal
  exportTo:
  - "."
  ports:
    - name: dcs-mongo-clients
      number: 27017
      protocol: TCP
  location: MESH_EXTERNAL
  resolution: NONE
```

When app connects to `main-mongodb-se` (main-db1-[1-3].c.internal-ai.internal) in Istio sidecar log we see that ist's connecting to dcsdb1-1.c.internal-ai.internal but in ip address we see address of main-db1-[1-3].c.internal-ai.internal.
See logs below

```
[2020-12-29T21:05:01.786Z] "- - -" 0 - "-" 2455 9183 571337 - "-" "-" "-" "-" "10.142.0.25:27017" outbound|27017||dcsdb1-1.c.internal-ai.internal 10.40.5.126:39752 10.142.0.25:27017 10.40.5.126:39746 - -

[2020-12-29T21:17:23.741Z] "- - -" 0 - "-" 13980 709444 202182 - "-" "-" "-" "-" "10.142.0.25:27017" outbound|27017||main-db1-1.c.internal-ai.internal 10.40.5.126:45682 10.142.0.25:27017 10.40.5.126:45680 - -
```

W'd expect to see main-db1-[1-3].c.internal-ai.internal this hostnames only. 
Problem above we see DNS name which we are not requesting however DNS is pointing to  main-db1-1.c.internal-ai.internal

Please advice.

[X ] Networking

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

1.8.1

**How was Istio installed?**

istioctl minimal profile 
single net
single mesh
single cluster

**Environment where the bug was observed (cloud vendor, OS, etc)**

GKE

**Comment by howardjohn** [comment]
This is not possible, generic TCP does not have enough information to distinguish these two. https://preliminary.istio.io/latest/blog/2020/dns-proxy/#external-tcp-services-without-vips has a better explanation of this

**Comment by papovyr** [comment]
Hi @howardjohn,

Thanks for reply

In other words if we are using TCP protocol in our ServiceEntry and `resolution: NONE ` (like yaml above that we have) it will create following listener 
```
ADDRESS        PORT  MATCH                                         DESTINATION
0.0.0.0        27017 ALL                                           Cluster: outbound|27017||dcsdb1-1.c.internal-ai.internal
```
And if we create second ServiceEntry with different name it will create an other listener and we will have following listeners
```
ADDRESS        PORT  MATCH                                         DESTINATION
0.0.0.0        27017 ALL                                           Cluster: outbound|27017||dcsdb1-1.c.internal-ai.internal
0.0.0.0        27017 ALL                                           Cluster: outbound|27017||main-db1-1.c.internal-ai.internal
```
And traffic will go with first matching rule (dcsdb1-1.c.internal-ai.internal in our case)

But if i use `resolution: DNS` i will expect envoy to resolve `hosts` list to ips and populate addresses list
However it looks like there is no deference between `resolution: NONE` and `resolution: DNS` for TCP protocol ServiceEntry.

Is there any automated way for Envoy to resolve `hosts` list and populate `addresses` list so there will not be any yamls update when i point DNS to deferent ips. Then it will be able to differentiate ServiceEntry by automatic hostname to IP DNS resolution.

I will hate to update `addresses` list in yaml files for each TCP  ServiceEntry each time I change DNS 

Please advice.

**Comment by howardjohn** [comment]
There is not, envoy does not currently support this. While it's likely technically possible to add there are some challenges. For example envoy and the application may get different dns responses (because dns server returns different things, or at the very least if the dns changes it would occur for some time period) which will lead to traffic breaking

**Comment by papovyr** [comment]
For TCP protocol in ServiceEntry there is no deference between `resolution: NONE` and `resolution: DNS` ?

**Comment by howardjohn** [comment]
DNS: Client sends request (likely resolving its own DNS request, but could also send directly to an IP), Envoy ignores it and sends to IP based on its own DNS resolution
NONE: Client sends request (likely resolving its own DNS request, but could also send directly to an IP), Envoy sends to the IP the client sent

**Comment by papovyr** [comment]
Thanks @howardjohn 
Now i'm confused 

in case of   `resolution: DNS`
`Envoy ignores it and sends to IP based on its own DNS resolution` DNS resolution based on host spec ? 

I see this happening for HTTP protocol where Host header is set. In case of TCP, client will resolve DNS and try to connect IP directly. How ENVOY knows original DNS that my app was trying to connect and will resolve DNS to ip and send data to it ? 

lets say i have 
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: dcs-mongodb-se
spec:
  hosts:
    - dcsdb1-1.c.internal-ai.internal
  exportTo:
  - "."
  ports:
    - name: dcs-mongo-clients
      number: 27017
      protocol: TCP
  location: MESH_EXTERNAL
  resolution: NONE
```
or 
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: dcs-mongodb-se
spec:
  hosts:
    - dcsdb1-1.c.internal-ai.internal
  exportTo:
  - "."
  ports:
    - name: dcs-mongo-clients
      number: 27017
      protocol: TCP
  location: MESH_EXTERNAL
  resolution: DNS
```

Is there any example that i can try and understand difference ?
As when i try `  resolution: DNS|NONE` i don't see any difference in `istioctl proxy-config listeners`

Thanks in advance.
