### ISSUE TITLE
TLS error: 268435696:SSL routines:OPENSSL_internal:UNSUPPORTED_PROTOCOL error for external service

### ISSUE THREAD

**Issue by keerthig9** [istio/istio#29816]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
We have externalservice which supports only TLS 1.0 version and it cannot be updated due to some internal reasons. When we enabled TLS origination for external service with Istio 1.8 version, we are getting `503 UF,URX` error `upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268435696:SSL routines:OPENSSL_internal:UNSUPPORTED_PROTOCOL`. On debugging further observed Istio 1.8 is using envoy 1.16 version and Minimum TLS protocol version by default, it’s TLSv1_2 for clients and TLSv1_0 for servers.. Maximum TLS protocol version by default, it’s TLSv1_2 for clients and TLSv1_3 for servers [link: https://github.com/envoyproxy/envoy/blob/v1.16.0/api/envoy/api/v2/auth/common.proto#L44].

Istio 1.4.5 works fine with our external service and we have issue once we migrated to 1.8 version of istio. Istio 1.4.5 was using envoy 1.12 version, in which Minimum TLS protocol version was TLSv1_0. So i think it worked well.

How can we override settings now so that we can have our calls to external service with TLSv1_0. We use ServiceEntry, DestinationRule, VirtualService and no egress gateway.
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: externalservice-api-with-tls-origination
  namespace: default
spec:
  hosts:
    - api-prod-na.rr.externalservice.com
  ports:
    - number: 30443
      name: http-port-for-tls-origination
      protocol: HTTP
    - name: https
      number: 443
      protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
  endpoints:
    - address: api-prod-na.rr.externalservice.com
      ports:
        https: 443
```
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-tls-for-externalservice-api
  namespace: default
spec:
  host: api-prod-na.rr.externalservice.com
  subsets:
    - name: http-api-calls # This catches routes for the plain HTTP subset
      trafficPolicy:
        loadBalancer:
          simple: ROUND_ROBIN
        portLevelSettings:
          - connectionPool:
              http:
                http1MaxPendingRequests: 1024  
              tcp:
                connectTimeout: 500ms
                maxConnections: 1024 
            port:
              number: 443
            tls:
              mode: SIMPLE 
              caCertificates: /etc/ssl-certs/externalservicecacerts.pem
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
      - connectionPool:
          http:
            http1MaxPendingRequests: 1024  
          tcp:
            connectTimeout: 500ms 
            maxConnections: 1024 
        port:
          number: 443
        tls:
          mode: DISABLE
          caCertificates: /etc/ssl-certs/externalservicecacerts.pem
```
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tls-for-externalservice-api
spec:
  hosts:
    - api-prod-na.rr.externalservice.com
  http:
    - match:
        - port: 30443
      route:
        - destination:
            subset: http-api-calls # Mark with subset so we can override the destination rule for TLS origination.
            host: api-prod-na.rr.externalservice.com
            port:
              number: 443
          weight: 100
```

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
