### ISSUE TITLE
Getting 504 GATEWAY_TIMEOUT with SSL termination on AWS ELB 

### ISSUE THREAD

**Issue by eladitzhakian** [istio/istio#29833]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
I'm trying to use SSL termination on ELB level with ACM.

Using the following ingress gateway service annotations:
```
annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <MY-ARN>
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: 8443,443
```

With this Gateway:
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: my-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - my-host
    port:
      name: http
      number: 80
      protocol: HTTP
  - hosts:
    - my-host
    port:
      name: https
      number: 443
      protocol: http
```

and this VirtualService:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-vs
spec:
  hosts:
  - my-host
  gateways:
  - my-gateway
  http:
  - route:
    - destination:
        host: my-service
        port:
          number: 80
```

And this Service:
```
kind: Service
metadata:
  name: my-service
spec:
  clusterIP: some-ip
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  type: ClusterIP
```

Accessing http works, but https fails after SSL verification succeeded:
```
$ curl -v https://my-host
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: my-host
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 504 GATEWAY_TIMEOUT
< Content-Length: 0
< Connection: keep-alive
<
* Connection #0 to host my-host left intact
* Closing connection 0
```

I tried setting:
```
service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
```

But that only gave me:
```
* Empty reply from server
* Connection #0 to host my-host left intact
curl: (52) Empty reply from server
* Closing connection 0
```

[ ] Docs
[x] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
I'd expect https to work without returning 504 🤷 

**Steps to reproduce the bug**
Mentioned above.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
$ istioctl version --remote
client version: 1.8.1
control plane version: 1.8.1
data plane version: 1.8.1 (3 proxies)
$ kubectl version --short
Client Version: v1.19.3
Server Version: v1.18.9-eks-d1db3c
```

**How was Istio installed?**
Using istioctl

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS EKS, executing commands from macOS

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
