### ISSUE TITLE
Service of type ExternalName breaks outgoing HTTPS connections 

### ISSUE THREAD

**Issue by cbenien** [istio/istio#29846]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
Background: we use Istio in a multi-tenant cluster and want to isolate workloads by namespace as much as possible. 

We found a bug where deploying a service in an unrelated namespace can screw up egress HTTPS requests from another namespace, thus breaking the isolation. We consider such bugs the worst case scenario and it will certainly open a discussion whether we'll continue to use Istio or not.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Any mistakes made only affect the namespace that they are deployed in. 

**Steps to reproduce the bug**
Deploy the following manifest to get a simple shell that has a copy of the curl command:
```
apiVersion: v1
kind: Namespace
metadata:
  name: shell
  labels: 
    istio-injection: enabled
---
apiVersion: v1
kind: Pod
metadata:
  name: shell
  namespace: shell
spec:
  containers:
    - name: shell
      image: curlimages/curl
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo hello; sleep 10;done"]
```

Now make a curl request to an external HTTPS endpoint from within the shell container (which has an Istio sidecar):

```
$ kubectl -n shell exec shell -c shell -- curl -v -s https://httpbin.org/get
*   Trying 54.158.248.248:443...
* Connected to httpbin.org (54.158.248.248) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /cacert.pem
*  CApath: none
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [98 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [4834 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=httpbin.org
*  start date: Dec 21 00:00:00 2020 GMT
*  expire date: Jan 19 23:59:59 2022 GMT
*  subjectAltName: host "httpbin.org" matched cert's "httpbin.org"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* Using Stream ID: 1 (easy handle 0x56487c36f680)
} [5 bytes data]
> GET /get HTTP/2
> Host: httpbin.org
> user-agent: curl/7.74.0-DEV
> accept: */*
> 
{ [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
} [5 bytes data]
< HTTP/2 200 
< date: Mon, 04 Jan 2021 15:00:46 GMT
< content-type: application/json
< content-length: 257
< server: gunicorn/19.9.0
< access-control-allow-origin: *
< access-control-allow-credentials: true
< 
{ [257 bytes data]
* Connection #0 to host httpbin.org left intact
{
  "args": {}, 
  "headers": {
    "Accept": "*/*", 
    "Host": "httpbin.org", 
    "User-Agent": "curl/7.74.0-DEV", 
    "X-Amzn-Trace-Id": "Root=1-5ff32d9e-0683312c10a40ecf0dc910df"
  }, 
  "origin": "91.38.20.122", 
  "url": "https://httpbin.org/get"
}
```

This should work fine. 

Now the nasty part. Deploy the following manifest which creates a "bad" namespace with a single service inside:
```
apiVersion: v1
kind: Namespace
metadata:
  name: bad
---
apiVersion: v1
kind: Service
metadata:
  name: bad-service
  namespace: bad
spec:
  externalName: google.com
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  sessionAffinity: None
  type: ExternalName
```

Run the above curl command again. For me it fails like this:

```
$ kubectl -n shell exec shell -c shell -- curl -v -s https://httpbin.org/get
*   Trying 184.72.216.47:443...
* Connected to httpbin.org (184.72.216.47) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /cacert.pem
*  CApath: none
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [15 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [3743 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=Mountain View; O=Google LLC; CN=*.google.com
*  start date: Nov 10 14:22:14 2020 GMT
*  expire date: Feb  2 14:22:13 2021 GMT
*  subjectAltName does not match httpbin.org
* SSL: no alternative certificate subject name matches target host name 'httpbin.org'
* Closing connection 0
} [5 bytes data]
* TLSv1.3 (OUT), TLS alert, close notify (256):
} [2 bytes data]
command terminated with exit code 60
```

Looks like I'm connecting to google.com now and that fails the TLS handshake. In other words: all outgoing HTTPS traffic will go to Google if a single service with ExternalName is defined anywhere in the cluster.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
$ istioctl version --remote
istioctl version --remote
client version: 1.8.1
control plane version: 1.8.1
data plane version: 1.8.1 (3 proxies)
```

```
$ kubectl version --short
Client Version: v1.19.3
Server Version: v1.18.8
```

**How was Istio installed?**
With the following command
```
istioctl install --set profile=demo
```

**Environment where the bug was observed (cloud vendor, OS, etc)**
Originally our cloud environment (Azure AKS), but I reproduced it in Docker Desktop

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by Monkeyanator** [comment]
Probable duplicate of: [https://github.com/istio/istio/issues/20703](https://github.com/istio/istio/issues/20703). Short-term fix from the issue seems to be either removing the port from the external-name service or renaming the service port with `https-` prefix.

Thanks for posting and we should definitely move to fix this, let's consolidate discussion on the above issue.

**Comment by isc30** [comment]
For others finding this problem, update your Service to:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: whatever
  namespace: whatever
spec:
  clusterIP: None
  ports:
    - port: 80

---
apiVersion: v1
kind: Endpoints
metadata:
  name: whatever
  namespace: whatever
subsets:
  - addresses:
      - hostname: whatever.whatever.tld
    ports:
      - port: 80
```
