### ISSUE TITLE
ext_authz Envoy filter dosen't take effect

### ISSUE THREAD

**Issue by hustshawn** [istio/istio#29842]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
Hi, I am trying to apply an ext_authz envoy filter which expect to talk with my external authz server, but it seems doesn't take effect. I am not sure if it's due to the istio/envoy version or not and expect to find some workaround if possible.

Here is the configuration.

```
apiVersion: v1
kind: Service
metadata:
  name: ext-authz
  namespace: stg-php
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: Endpoints
metadata:
  name: ext-authz
  namespace: stg-php
subsets:
  - addresses:
      - ip:  <exteranl-authz-server-ip-address>
    ports:
      - port: 80

---

apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ext-authz-ef
  namespace: stg-php
spec:
  workloadSelector:
    labels:
      # Here I am selecting the workload, instead of applying it to the istio-ingressgateway
      app: <the-workload-labels>. 
  filters:
  - listenerMatch:
      listenerType: SIDECAR_INBOUND
      listenerProtocol: HTTP 
    insertPosition:
      index: FIRST           
    filterName: envoy.ext_authz
    filterType: HTTP
    filterConfig:
      http_service:
        server_uri:
          uri: http://ext-authz.stg-php.svc.cluster.local:80
          cluster: outbound|80||ext-authz.stg-php.svc.cluster.local
          timeout: 0.25s
          failure_mode_allow: false
```
and I tried to examine the workload pod, by `istioctl pc listener <workload-pod-name> --port 80 -ojson` , but cannot find the filter `envoy.ext_authz`

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
Expect the ext_authz filter would appear on my workload listener filter chain.
**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
client version: 1.2.7
citadel version: 1.2.7
galley version: 1.2.7
ingressgateway version: 1.2.7
ingressgateway version: 1.2.7
pilot version: 1.2.7
pilot version: 1.2.7
pilot version: 1.2.7
pilot version: 1.2.7
pilot version: 1.2.7
policy version: 1.2.7
sidecar-injector version: 1.2.7
telemetry version: 1.2.7
**How was Istio installed?**
helm
**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
