### ISSUE TITLE
istio1.8.1 two envoyfilter configruation confilict with each other

### ISSUE THREAD

**Issue by jezhang2014** [istio/istio#29858]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
istio 1.8.1
I have two envoyfilters affect on enovy.http_connection_manager, one is for HTTP_FILTER, the other is for NETWORK_FILTER, once I apply NETWORK_FILTER and HTTP_FILTER together, the HTTP_FILTER will be reset to default.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Both HTTP_FILTER afftect delayed_close_timeout inside HttpConnectionManager  and  envoy.filters.http.local_ratelimit could take into effect.

**Steps to reproduce the bug**
[local-ratelimit-filter.yaml]
apiVersion: networking.istio.io/v1alpha3
  kind: EnvoyFilter
  metadata:
    name: ratelimit-http-local
  spec:
    workloadSelector:
      labels:
      ¦   io.kompose.service: backend-welink
    configPatches:
      - applyTo: HTTP_FILTER
      ¦ match:
      ¦   context: SIDECAR_INBOUND
      ¦   listener:
      ¦   ¦ name: virtualInbound
      ¦   ¦ filterChain:
      ¦   ¦   name: 0.0.0.0_8123
      ¦   ¦   filter:
      ¦   ¦   ¦ name: envoy.http_connection_manager
      ¦   ¦   ¦ subFilter:
      ¦   ¦   ¦   ¦ name: "envoy.filters.http.router"
      ¦ patch:
      ¦   operation: INSERT_BEFORE
      ¦   value:
      ¦   ¦ name: envoy.filters.http.local_ratelimit
      ¦   ¦ typedConfig:
      ¦   ¦   "@type": "type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit"
      ¦   ¦   stat_prefix: http_local_rate_limit

[backend-filter.yaml]
apiVersion: networking.istio.io/v1alpha3
  kind: EnvoyFilter
  metadata:
    name: backend-nodelay
  spec:
    workloadSelector:
      ¦ labels:
      ¦   ¦ io.kompose.service: backend
    configPatches:
      - applyTo: NETWORK_FILTER
      ¦ match:
      ¦   context: SIDECAR_INBOUND
      ¦   listener:
      ¦   ¦ name: virtualInbound
      ¦   ¦ filterChain:
      ¦   ¦   name: 0.0.0.0_8123
      ¦   ¦   filter:
      ¦   ¦   ¦ name: envoy.http_connection_manager
      ¦ patch:
      ¦   operation: MERGE
      ¦   value:
      ¦   ¦ name: envoy.http_connection_manager
      ¦   ¦ typedConfig:
      ¦   ¦   "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
      ¦   ¦   delayed_close_timeout: "0"

Apply these two filters seperately, after applied local-ratelimit-filter.yaml, use istioctl pc listeners xxxx --port 15006 -o json, you will find the local_ratelimit shows inside 0.0.0.0_8123 filter, then apply backend-filter.yaml, you will find delayed_close_timeout will be shown, but local_ratelimit configuration will disappeared.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.8.1

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ratelimit-http-local
spec:
  workloadSelector:
    labels:
        io.kompose.service: backend-welink
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          name: virtualInbound
          filterChain:
            name: 0.0.0.0_8123
            filter:
              name: envoy.http_connection_manager
              subFilter:
                  name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typedConfig:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit"
            stat_prefix: http_local_rate_limit
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: backend-nodelay
spec:
  workloadSelector:
    labels:
      io.kompose.service: backend
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          name: virtualInbound
          filterChain:
            name: 0.0.0.0_8123
            filter:
              name: envoy.http_connection_manager
      patch:
        operation: MERGE
        value:
          name: envoy.http_connection_manager
          typedConfig:
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
            delayed_close_timeout: "0"
```

same config, properly format for reproduction
