### ISSUE TITLE
EnvoyFilter does not work if the port name isn't a standard protocol name (like http, https etc)

### ISSUE THREAD

**Issue by tariq1890** [istio/istio#29893]
**Bug description**

We are trying to apply an `EnvoyFilter` which modifies the `HTTPConnectionManager` section of the Envoy config.
We have found that this filter isn't applied when port name other `http` is used.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

The `EnvoyFilter` should still work when we use an alternate port name

**Steps to reproduce the bug**

To reproduce this bug, we can use the httpbin manifests

```
##################################################################################################
# httpbin service
##################################################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
    service: httpbin
spec:
  type: LoadBalancer
  ports:
  - name: application
    port: 8000
    targetPort: 80
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
      annotations:
        "sidecar.istio.io/inject": "true"
    spec:
      serviceAccountName: httpbin
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 150Mi
          requests:
            cpu: 50m
            memory: 100Mi
        securityContext:
            runAsUser: 0
            readOnlyRootFilesystem: false
```
Use this EnvoyFilter:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: httpbin
spec:
  workloadSelector:
    labels:
      app: httpbin
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          use_remote_address: true
          skip_xff_append: false
          xff_num_trusted_hops: 1
```

Try a curl call from within a pod

```
curl httpbin:8000/v1/ip

I have no name!@foo-overlay-test-25mh8:/$ curl httpbin:8000/ip
{
  "origin": "127.0.0.1"
}

```

With the EnvoyFilter, we should be the pod IP instead. If we switch the port name in the service from `application` to `http`, then it starts printing the pod IP.

```
curl httpbin:8000/v1/ip

I have no name!@foo-overlay-test-25mh8:/$ curl httpbin:8000/ip
{
  "origin": "100.96.26.215"
}
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Istio- 1.7.6

**How was Istio installed?**
Helm

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS
