### ISSUE TITLE
Unable to use cluster-external SPIFFE URI SAN for Authz Policy

### ISSUE THREAD

**Issue by jwilner** [istio/istio#29891]
I am unable to set ingress authorization policies based on the URI SAN of client certificates.
 
**Bug description**

I have a cert for `jen` with the URI set to 
```shell
$ openssl x509 -in insecure/jen/jen.crt -text -noout  | grep 'URI\|Issuer':
        Issuer: CN=cert-manager.svc.cluster.local
                URI:spiffe://insecure/ns/local-dev/sa/jen```
```

I use the `cert-manager.svc.cluster.local` as the CA for my ingress with MUTUAL auth.

Up to this point, everything works fine:
```shell
$ curl -i --cert insecure/jen/jen.crt --key insecure/jen/jen.key --cacert insecure/cert-manager.svc.cluster.local/ca.crt https://foo.default.cluster.dev/get
HTTP/2 200
...
```

The issue comes when I attempt to apply an `AuthorizationPolicy` like so:

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ingress-policy
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  action: ALLOW
  rules:
  - from: 
    - source:
        principals: ["insecure/local-dev/jen"]
    to:
    - operation:
        methods: ["GET"]
```

The intention is that the above request should still succeed. Instead, I get:

```
curl -i --cert insecure/jen/jen.crt --key insecure/jen/jen.key --cacert insecure/cert-manager.svc.cluster.local/ca.crt https://foo.default.cluster.dev/get
HTTP/2 403
content-length: 19
content-type: text/plain
date: Wed, 06 Jan 2021 17:06:58 GMT
server: istio-envoy

RBAC: access denied
```

I have also tried various other iterations of the `source.principals` rule, e.g. including the `spiffe://` scheme and with wildcards. Significantly, even when I do `source.principals: ["*"]`, the policy doesn't work as expected -- this suggests the URI SAN isn't making it into the source.principal field.

The resulting RBAC filter in envoy looks like:
```json
{"name":"envoy.filters.http.rbac","typed_config":{"@type":"type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC","rules":{"policies":{"ns[istio-system]-policy[ingress-policy]-rule[0]":{"permissions":[{"and_rules":{"rules":[{"or_rules":{"rules":[{"header":{"name":":method","exact_match":"GET"}}]}}]}}],"principals":[{"and_ids":{"ids":[{"or_ids":{"ids":[{"metadata":{"filter":"istio_authn","path":[{"key":"source.principal"}],"value":{"string_match":{"exact":"insecure/local-dev/jen"}}}}]}}]}}]}}}}}
```

The envoy logs look like:
```
2021-01-06T17:06:58.956241Z	debug	envoy rbac	checking request: requestedServerName: foo.default.cluster.dev, sourceIP: 10.244.0.1:35695, directRemoteIP: 10.244.0.1:35695, remoteIP: 10.244.0.1:35695,localAddress: 10.244.0.8:8443, ssl: uriSanPeerCertificate: spiffe://insecure/local-dev/jen, dnsSanPeerCertificate: , subjectPeerCertificate: CN=jen, headers: ':method', 'GET'
':path', '/get'
':scheme', 'https'
':authority', 'foo.default.cluster.dev'
'user-agent', 'curl/7.64.1'
'accept', '*/*'
'x-forwarded-for', '10.244.0.1'
'x-forwarded-proto', 'https'
'x-envoy-internal', 'true'
'x-request-id', 'ac9a7dd5-4e49-45cc-9c04-c51a503b5965'
'x-forwarded-client-cert', 'Hash=712e876475ac0ce3f19cd3b67fed0baeb0d2228633a2c78d6f8cbe5a59bc28dd;Cert="-----BEGIN%20CERTIFICATE-----...-----END%20CERTIFICATE-----%0A";Subject="CN=jen";URI=spiffe://insecure/local-dev/jen'
'x-envoy-decorator-operation', '...'
'x-envoy-peer-metadata', '...'
'x-envoy-peer-metadata-id', 'router~10.244.0.8~istio-ingressgateway-64589668d7-8br6m.istio-system~istio-system.svc.cluster.local'
, dynamicMetadata:
2021-01-06T17:06:58.956281Z	debug	envoy rbac	enforced denied, matched policy none
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
The `source.principals` field should match URI SANs from client certificates when applied to ingresses

**Steps to reproduce the bug**
See above

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
$ istioctl version --remote
client version: 1.8.1
control plane version: 1.8.1
data plane version: 1.8.1 (1 proxies)
$ kubectl version --short
Client Version: v1.19.3
Server Version: v1.19.1
```

**How was Istio installed?**
istioctl

**Environment where the bug was observed (cloud vendor, OS, etc)**
Locally running on `kind`

**Comment by yangminzhu** [comment]
In the Envoy log, it seems the URI SAN is set to `spiffe://insecure/local-dev/jen` which is not the Istio spiffe format. Could you change it to `spiffe://insecure/ns/local-dev/sa/jen` and also change the policy to `principals: ["insecure/ns/local-dev/sa/jen"]`?

**Comment by jwilner** [comment]
Thanks for looking into this @yangminzhu. This was one of the iterations I've already gone through, but for posterity:

```shell
$ openssl x509 -in foo/cert.pem -text -noout  | grep 'URI\|Issuer':
        Issuer: CN=cert-manager.svc.cluster.local
                URI:spiffe://insecure/ns/local-dev/sa/foo
$ kubectl apply -f=- <<EOF
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ingress-policy
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["insecure/ns/local-dev/sa/foo"]
    to:
    - operation:
        methods: ["GET"]
EOF

authorizationpolicy.security.istio.io/ingress-policy created
$ curl --cacert cert-manager.svc.cluster.local/ca.cert.pem --key foo/key.pem --cert foo/cert.pem https://foo.default.cluster.auth.dev/get
RBAC: access denied
```

Envoy logs:
```shell
2021-01-07T04:14:09.160798Z	debug	envoy rbac	checking request: requestedServerName: foo.default.cluster.auth.dev, sourceIP: 10.244.0.1:44764, directRemoteIP: 10.244.0.1:44764, remoteIP: 10.244.0.1:44764,localAddress: 10.244.0.7:8443, ssl: uriSanPeerCertificate: spiffe://insecure/ns/local-dev/sa/foo, dnsSanPeerCertificate: , subjectPeerCertificate: CN=foo, headers: ':method', 'GET'
':path', '/get'
':scheme', 'https'
':authority', 'foo.default.cluster.auth.dev'
'user-agent', 'curl/7.64.1'
'accept', '*/*'
'x-forwarded-for', '10.244.0.1'
'x-forwarded-proto', 'https'
'x-envoy-internal', 'true'
'x-request-id', '9edfa238-2b8d-4889-85a6-251dba48b851'
'x-forwarded-client-cert', 'Hash=a5e843c07c6d768774d959c0397e415bc50dcd8c71a6b6f73da3a99cda2c77d2;Cert="-----BEGIN%20CERTIFICATE-----...-----END%20CERTIFICATE-----%0A";Subject="CN=foo";URI=spiffe://insecure/ns/local-dev/sa/foo'
'x-envoy-peer-metadata', '...'
'x-envoy-peer-metadata-id', 'router~10.244.0.7~istio-ingressgateway-64589668d7-dbd4t.istio-system~istio-system.svc.cluster.local'
, dynamicMetadata:
2021-01-07T04:14:09.160867Z	debug	envoy rbac	enforced denied, matched policy none
```

Istiod logs:
```shell
2021-01-07T04:13:56.375832Z	debug	authorization	rule ns[istio-system]-policy[ingress-policy]-rule[0] generated policy: permissions:{and_rules:{rules:{or_rules:{rules:{header:{name:":method" exact_match:"GET"}}}}}} principals:{and_ids:{ids:{or_ids:{ids:{metadata:{filter:"istio_authn" path:{key:"source.principal"} value:{string_match:{exact:"insecure/ns/local-dev/sa/foo"}}}}}}}}
```

For what it's worth, I've gotten an envoy filter working:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: access-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: istio-ingressgateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        filter_class: AUTHZ
        value:
          name: envoy.filters.http.rbac
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC
            rules:
              action: ALLOW
              policies:
                superuser:
                  principals:
                    - authenticated: { principal_name: { exact: "spiffe://insecure/ns/local-dev/sa/foo" } }
                  permissions:
                    - any: true
```
