### ISSUE TITLE
Proxy/NLB Blog Instructions lead to removal of the istio_* metrics from the istio-proxy sidecars

### ISSUE THREAD

**Issue by diranged** [istio/istio#29909]
**Bug description**
We're using Istio 1.8.1 on EKS. We've got our Ingressgateway configured with an AWS NLB as our load balancer and its been working for a few days now. We followed the instructions in https://istio.io/latest/blog/2020/show-source-ip/ - and we noticed that our Envoy sidecar containers (the istio-proxy's) stopped reporting any istio_* metrics.

Logging directly into the sidecar container, we checked the outputted metrics:

```
istio-proxy@reviews-v1-7f99cc4496-4mt5n:/$ curl -s 'localhost:15000/stats/prometheus' | grep istio               
# TYPE istio_build gauge
istio_build{component="proxy",tag="1.8.1"} 1
istio-proxy@reviews-v1-7f99cc4496-4mt5n:/$
```

As soon as we removed the two EnvoyFilters (copied below), the metrics started flowing again. These are the two EnvoyFilter's we created. Other than these two filters, we only have the stock filters installed by the IstioOperator:

```
# https://istio.io/latest/blog/2020/show-source-ip/
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: proxy-protocol
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: LISTENER
    patch:
      operation: MERGE
      value:
        listener_filters:
        - name: envoy.filters.listener.proxy_protocol
        - name: envoy.filters.listener.tls_inspector
# https://istio.io/latest/blog/2020/show-source-ip/
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: x-forwarded-for
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
    patch:
      operation: MERGE
      value:
        name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          skip_xff_append: false
          use_remote_address: true
          xff_num_trusted_hops: 1
```

```
$ k get envoyfilters -A
NAMESPACE      NAME                        AGE
istio-system   metadata-exchange-1.6       14d
istio-system   metadata-exchange-1.7       14d
istio-system   metadata-exchange-1.8       14d
istio-system   stats-filter-1.6            14d
istio-system   stats-filter-1.7            14d
istio-system   stats-filter-1.8            14d
istio-system   tcp-metadata-exchange-1.6   14d
istio-system   tcp-metadata-exchange-1.7   14d
istio-system   tcp-metadata-exchange-1.8   14d
istio-system   tcp-stats-filter-1.6        14d
istio-system   tcp-stats-filter-1.7        14d
istio-system   tcp-stats-filter-1.8        14d
$ 
```

A brief slack discussion at https://istio.slack.com/archives/C37A4KAAD/p1609986312373100 lead me to revert the change.

[x] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

I would have expected that if there were any problems with the filters, that there would be some event in the namespace thatw ould give us that indication.. and that the envoy sidecar containers would not pull down a "bad" config (if that's whats going on herE).

**Steps to reproduce the bug**

On a relatively vanilla (`default` profile) installation, go and add in the two EnvoyFilters above.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
$ istioctl version --remote
client version: 1.8.1
control plane version: 1.8.1
data plane version: 1.8.1 (9 proxies)
```

```
$ kubectl version --short
Client Version: v1.20.0
Server Version: v1.18.9-eks-d1db3c
```

**How was Istio installed?**

IstioOperator

**Environment where the bug was observed (cloud vendor, OS, etc)**

AWS using EKS with NLBs and the latest AWS Load Balancer Controller

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
