### ISSUE TITLE
Headless service with hostNetwork enabled breaks the connection from others pods

### ISSUE THREAD

**Issue by kiuby** [istio/istio#29904]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
When deploying node-exporter chart with hostNetwork enabled, it breaks the connection from our prometheus pod.
(We've got a 404 Not found that seems to be returned by istio-proxy)
When executing a curl command from the istio-proxy container, the curl is working as expected. 

This configuration was working properly with istio 1.4.10

[ ] Docs
[ ] Installation
[ X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
The curl made to the host should works when the daemonset deployement has hostNetwork set to True

**Steps to reproduce the bug**
To reproduce this issue:

1. On your kubernetes cluster, create a namespace and add the sidecar injection label:
```
kubectl create ns  node-exporter-issue
kubectl label namespace node-exporter-issue istio-injection=enabled --overwrite
kns node-exporter-issue
```

2.  Apply the following yaml, (don't forget to replace the XXX by a node ip of your cluster (you can find it using kubectl get nodes -o wide) :

```
---

apiVersion: v1
kind: Pod
metadata:
  name: curl
spec:
  containers:
  - name: curl
    image: debian:latest
    imagePullPolicy: Always
    command:
    - /bin/bash
    - -l
    - -c
    - "sleep 15; apt-get update && apt-get install curl -y; while true; do curl -snvL 'http://XXX:9100'; sleep 2; done"

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    component: "statefulset"
    app: node-exporter
    release: node-exporter
  name: node-exporter-statefulset
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
  selector:
    component: "statefulset"
    app: node-exporter
    release: node-exporter
  type: "ClusterIP"

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    component: "statefulset"
    app: node-exporter
    release: node-exporter
  name: node-exporter-statefulset
spec:
  selector:
    matchLabels:
      component: "statefulset"
      app: node-exporter
      release: node-exporter
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: "statefulset"
        app: node-exporter
        release: node-exporter
    spec:
      serviceAccountName: default
      containers:
        - name: node-exporter-statefulset
          image: "prom/node-exporter:v0.18.1"
          imagePullPolicy: "IfNotPresent"
          args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)
            - --path.rootfs=/host
          ports:
            - name: metrics
              containerPort: 9100
              hostPort: 9100
          resources:
            limits:
              cpu: 0.1
              memory: 64Mi
            requests:
              cpu: 0.1
              memory: 64Mi

          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly:  true
            - name: sys
              mountPath: /host/sys
              readOnly: true
            - name: host-ro
              mountPath: /host
              readOnly: true
      hostNetwork: true
      #hostPID: true
      tolerations:
        - effect: NoSchedule
          operator: Exists
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: host-ro
          hostPath:
            path: /
```

Without hostNetwork, it's working as expected:
```
kubectl logs -f  curl -c curl
...
< HTTP/1.1 200 OK
< date: Thu, 07 Jan 2021 08:41:40 GMT
< content-length: 150
< content-type: text/html; charset=utf-8
< x-envoy-upstream-service-time: 0
< server: istio-envoy
< x-envoy-decorator-operation: node-exporter-statefulset.node-exporter-issue.svc.cluster.local:9100/*
<
{ [150 bytes data]
* Connection #0 to host XXX left intact
<html>
                        <head><title>Node Exporter</title></head>
                        <body>
                        <h1>Node Exporter</h1>
                        <p><a href="/metrics">Metrics</a></p>
                        </body>
```

With hostNetwork set, we have : 
```
* Expire in 0 ms for 6 (transfer 0x55cede3dff90)
* Couldn't find host XXXin the .netrc file; using defaults
*   Trying XXX...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x55cede3dff90)
* Connected to XXX (XXX) port 9100 (#0)
> GET / HTTP/1.1
> Host: XXX:9100
> User-Agent: curl/7.64.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< date: Thu, 07 Jan 2021 08:39:57 GMT
< server: envoy
< content-length: 0
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Istio : 1.8.1
Kubernetes : Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
Using istioctl

**Environment where the bug was observed (cloud vendor, OS, etc)**
cloud vendor : EKS

**Related Issues**
- https://github.com/istio/istio/issues/7558

 

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
