### ISSUE TITLE
proxyMetadata cannot be set with istioctl install; manifest generate works

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#29930]
```
$ cat <<EOF | istioctl install -y -d manifests/ -f -
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
EOF
✔ Istio core installed
✔ Istiod installed
✔ Ingress gateways installed
✔ Installation complete                     
$ ki get cm istio -oyaml | k neat
apiVersion: v1
data:
  mesh: |-
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      proxyMetadata:
        DNS_AGENT: ""
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
    enablePrometheusMerge: true
    rootNamespace: istio-system
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
```

You can see the proxy metadata is dropped

But using generate works fine:

```
$ cat <<EOF | istioctl manifest generate -d manifests/ -f - | k grep ConfigMap/istio
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
EOF

apiVersion: v1
kind: ConfigMap
metadata:
  name: istio
  namespace: istio-system
data:
  mesh: |-
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      proxyMetadata:
        DNS_AGENT: ""
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
        ISTIO_META_DNS_CAPTURE: "true"
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
    enablePrometheusMerge: true
    rootNamespace: istio-system
    trustDomain: cluster.local
```

**Comment by howardjohn** [comment]
This is a regression in master, it works fine in Istio 1.8

**Comment by morvencao** [comment]
The root cause is that operator reads the IOP spec from `Stdin`, but it can only only read once, it will be empty for the following read after the first read, See: https://github.com/istio/istio/blob/d8ba753f90d8f87fd67b82938192dd54191ca19a/operator/pkg/manifest/shared.go#L249-L277

It will be OK if operator reads from file instead of `Stdin`.

I also found this also happens for `upgrade` case, because upgrade process also reads IOP spec from `Stdin` for multiple times.

**Comment by ericvn** [comment]
I wonder if this will also fix the problem in https://github.com/istio/istio/issues/29400 where 
```
+echo 'apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    telemetry:
      v2:
        prometheus:
          configOverride:
            inboundSidecar:
              metrics:
                - name: requests_total
                  dimensions:
                    destination_port: string(destination.port)
                    request_host: request.host
            outboundSidecar:
              metrics:
                - name: requests_total
                  dimensions:
                    destination_port: string(destination.port)
                    request_host: request.host
            gateway:
              metrics:
                - name: requests_total
                  dimensions:
                    destination_port: string(destination.port)
                    request_host: request.host'
+istioctl install --set tag=1.9-alpha.d6406143dfe9130d1a76ac16079753d3d7b177e9 --set hub=gcr.io/istio-testing -y -f -
```
does not update?
