### ISSUE TITLE
Intermittent lost connection on tls origination

### ISSUE THREAD

**Issue by thereallukl** [istio/istio#29935]
**Bug description**
I'm using to TLS origination feature to connect external elasticsearch cluster, running in the same network, but on separate kubernetes cluster. Elasticsearch is running behind load balancer (if it matters). Every few minutes some requests never finish and leave connection hanged (happens with application as well as curl within mesh).
When I try to connect directly to load balancer hosting ES it always responds succesfully.

There is nothing after this in curl output:
```
*   Trying 10.84.34.86...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x55ef1f44df90)
* Connected to elasticsearch-data-master.<domain> (<1.2.3.4>) port 80 (#0)
* Server auth using Basic with user '<user>'
> HEAD / HTTP/1.1
> Host: elasticsearch-data-master.<domain>
> Authorization: Basic <redacted>
> User-Agent: curl/7.64.0
> Accept: */*
>
```
After killing curl and retrying connection it works again.

This is my configuration:

**VirtualService**:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: elasticsearch-data
  namespace: istio-system
spec:
  hosts:
  - elasticsearch-data-master.<domain>
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: elasticsearch-data-master.<domain>
        port:
          number: 9200
        subset: tls-origination
```

**ServiceEntry**
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: elasticsearch-data
  namespace: istio-system
spec:
  hosts:
  - elasticsearch-data-master.<domain>
  ports:
  - name: https-port-for-tls-origination
    number: 9200
    protocol: HTTPS
  - name: http-port
    number: 80
    protocol: HTTP
  resolution: DNS
```

**DestinationRule**
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: originate-tls-for-elasticsearch-data
  namespace: istio-system
spec:
  host: elasticsearch-data-master.<domain>
  subsets:
  - name: tls-origination
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 9200
        tls:
          mode: SIMPLE
```

[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
istioctl version --remote
client version: 1.6.8
control plane version: 1.6.14
data plane version: 1.6.14 (64 proxies)
---
kubectl version --short
Client Version: v1.19.4
Server Version: v1.19.3
```

**How was Istio installed?**
istioctl
**Environment where the bug was observed (cloud vendor, OS, etc)**

Azure AKS

**Comment by thereallukl** [comment]
A little update from my side. The problem seems to be related to load balancer sending TCP_RESET for idling connections. After such event envoy doesn't remove tcp session right away, but makes 1 more attempt to reuse it. After it fails it's removed (every time I had failed connection, it was first attempt to use given session after RESET, so I presume that after such failure it is removed from pool).

This is basically how it looks in wireshark:
<img width="1430" alt="Screenshot 2021-01-15 at 09 45 17" src="https://user-images.githubusercontent.com/12996461/104702860-de92ed00-5716-11eb-94f2-06c23d224f04.png">


For the time being workaround that seems to be working for me is to add TCP keepalive in destination rule like this:
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: originate-tls-for-elasticsearch-data
  namespace: istio-system
spec:
  host: elasticsearch-data-master.<domain>
  subsets:
  - name: tls-origination
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - connectionPool:
          tcp:
            tcpKeepalive:
              interval: 180s
              time: 180s
        port:
          number: 9200
        tls:
          mode: SIMPLE
```
