### ISSUE TITLE
Istio MultiPrimary Deployment cannot resolve headless service in remote cluster 

### ISSUE THREAD

**Issue by nirvanatao** [istio/istio#29969]
I configured 2 Kubernetes cluster as a singl service mesh using Istio MultiPrimary Deployment, however I found that the headless services could not be resolved from remote cluster, I'm using istio-1.8.1

**Comment by hzxuzhonghu** [comment]
From the implement details, istiod can watch service/endpoints from the other clusters, it is same for any kind of service.

**Comment by nirvanatao** [comment]
> From the implement details, istiod can watch service/endpoints from the other clusters, it is same for any kind of service.

Hi Zhonghu, thanks for your reply, do you mean that I just need to create a stub service for headless service? do you have any sample?

Here is what I did it but not works:
created a test namespace with istio-injection=enabled in each clusters
```
kubectl create ns test  --context cluster-0
kubectl create ns test  --context cluster-1
kubectl label ns test istio-injection=enabled --context cluster-0
kubectl label ns test istio-injection=enabled --context cluster-1
```
and then I applied below yaml in cluster-0:
```
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
  namespace: test
spec:
  ports:
  - port: 80
    name: web
  selector:
    app: nginx
  clusterIP: None
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
  namespace: test
  labels:
    app: nginx
spec:
  hostname: nginx-1
  subdomain: nginx-headless
  containers:
  - image: k8s.gcr.io/nginx-slim:0.8
    name: nginx
    ports:
    - containerPort: 80
      name: web
```
and applied below yaml in cluster-1:
```
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
  namespace: test
spec:
  ports:
  - port: 80
    name: web
  selector:
    app: nginx
  clusterIP: None
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  namespace: test
  labels:
    app: nginx
spec:
  hostname: nginx-2
  subdomain: nginx-headless
  containers:
  - image: k8s.gcr.io/nginx-slim:0.8
    name: nginx
    ports:
    - containerPort: 80
      name: web
```
what I expected is that I can curl http://nginx-2.nginx-headless.test.svc.cluster.local from both cluster-0 and cluster-1, however, when I tried to curl http://nginx-2.nginx-headless.test.svc.cluster.local from cluster-0 it always fails with error ```Name or service not known```
```
root@dev:/# ping nginx-1.nginx-headless.test.svc.cluster.local
PING nginx-1.nginx-headless.test.svc.cluster.local (172.19.6.53) 56(84) bytes of data.
64 bytes from nginx-1.nginx-headless.test.svc.cluster.local (172.19.6.53): icmp_seq=1 ttl=64 time=6.96 ms
--- nginx-1.nginx-headless.test.svc.cluster.local ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 6.961/6.961/6.961/0.000 ms
root@dev:/# ping nginx-2.nginx-headless.test.svc.cluster.local
ping: nginx-2.nginx-headless.test: Name or service not known
```
