### ISSUE TITLE
Incorrect route has been created in openshift plaform

### ISSUE THREAD

**Issue by barryzhounb** [istio/istio#29982]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
I am working on OpenShift platform. I created a Openshift route and mapping route to Istio ingressgateway. My ingress-gateway port is 8888.

The route is https pass-through type, that means https will be terminated in Istio ingress-gateway. When I specify hosts with "*" in the Gateway, then I saw besides my route "mynamespace-istio-ingressgateway-route " has been created, by surprising another route "istio-system-mynamespace-ingress-gateway-frddr" has been created as well. My question is, the second route should not have, because I never create it. Moreover, once I specify hosts with host name in the route (that means hosts is same as hostname in route), then my service won't work.

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mynamespace-ingress-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 8888
      name: tls
      protocol: TLS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    - "*"
```

```
oc -n istio-system get route

NAME                                             HOST/PORT                                                                                           PATH      SERVICES                           PORT      TERMINATION          WILDCARD

istio-system-mynamespace-ingress-gateway-frddr   istio-system-mynamespace-ingress-gateway-frddr-istio-system.apps.devospreycluster.os.fyre.ibm.com             istio-ingressgateway               https     passthrough          None
mynamespace-istio-ingressgateway-route           www.osprey.com                                                                                                mynamespace-istio-ingressgateway   8888      passthrough          None
```

[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

Istio version: 1.6.x

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
