### ISSUE TITLE
ServiceEntry with TCP protocol will override other settings. It affects all outgoing traffic (also those URLs which are not in the entry)

### ISSUE THREAD

**Issue by taitelman** [istio/istio#29992]
**Bug description**
Couldn't find it in the documentation so here it is:
Imagine a K8s cluster with neither egress rules nor service entries. Default outgoing rule is ALLOW_ANY of course.
As soon as I add my first service entry to the cluster (to my isolated app namespace):
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-https
  namespace: myNS
spec:
  hosts:
    - google.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: TCP
  resolution: DNS
```

immediately all HTTPS communication to `altavista.com` will fail (the rule was set to `google.com`)
As a user I would expect to first apply REGISTRY_ONLY flag for my SE to take an effect, however, the effect is immediate and brutal. 
As if it overrides the global ALLOW_ANY egress rule.

There is no destination rule for google.

**Affected product area (please put an X in all that apply)**
[x] Docs
[x] Networking
[x] User Experience

**Expected behavior**
ServiceEntries should affect egress only when you turn on REGISTRY_ONLY flag.
in my case I turn on by:
```
kubectl patch configmap managed-istio-custom -n ibm-operators  --type=merge -p '{ "data": { "istio-global-outboundTrafficPolicy-mode":"REGISTRY_ONLY" }}'
```
(its IKS)

**Steps to reproduce the bug**

**Version** 
```
$ istioctl version --remote
client version: 1.8.1
control plane version: 1.7.6
data plane version: 1.7.6 (597 proxies)
```
**How was Istio installed?**
IBM managed Istio (IKS)

**Environment where the bug was observed (cloud vendor, OS, etc)**
vendor: IBM
OS: ubuntu 18.04

**Comment by GregHanson** [comment]
Have you tried the protocol as `HTTPS` instead of `TCP`?  `hosts` + `protocol: TCP` means hosts will be ignored and traffic will only be matched with the port 443 - therefore affecting all traffic on port 443 instead of just traffic to google.com.  With `hosts` + `protocol: HTTPS` istio/envoy should perform SNI matching to ensure only traffic to google.com is effected by the ServiceEntry

**Comment by taitelman** [comment]
Ok. I tested. indeed `protocol: HTTPS` solves the issue.
it means I need to be careful when defining a TCP SE . especially on  a port which is shared by many domains

**Comment by linsun** [comment]
cc @esnible @therealmitchconnors - anything we should look into from analyzer perspective to report these type of areas?

**Comment by esnible** [comment]
I could imagine

```
  hosts:
    - google.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: TCP
```

I can imagine generating an **INFO** or **WARNING** message `ServiceEntry hosts "google.com" ignored due to protocol=TCP.  (Use protocol=HTTPS to restrict ServiceEntry to the specified hosts only)`

@GregHanson Would that help users?  Info or Warning?  Would it make sense to do this for all cases where the protocol is TCP, or just cases where the port is a well known port such as 443?  I hadn't realized this behavior ... for **Services** specifying the port name `https` would treat it like HTTPS, for ServiceEntries it must be treating the name `https` it as TCP.  Is that really happening?  Is it expected behavior?
