### ISSUE TITLE
istio virtual service with tls - Connection reset by peer

### ISSUE THREAD

**Issue by nareshganesan** [istio/istio#29995]
**Bug description**

We are not able to access HTTPS endpoints with istio. Also, the issue is not happening consistently, meaning with the same configuration below it works sometimes. Azure AKS team checked their network logs and was able to confirm there is no network issue from the Azure side. 

```
The below issue occurs randomly, instead all the services should be accessible.
ex:
https://kial.one-dpo.com - works sometimes and doesn't work at some other time. 
https://sandbox.one-dpo.com - works sometimes and doesn't work at some other time. 
```

When the url is not accessible the following is the error `PR_CONNECT_RESET_ERROR`
```
$ curl -v https://kiali.one-dpo.com
*   Trying 20.190.14.28:443...
* TCP_NODELAY set
* Connected to kiali.one-dpo.com (20.190.14.28) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /home/ng/anaconda3/ssl/cacert.pem
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: Connection reset by peer in connection to kiali.one-dpo.com:443 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to kiali.one-dpo.com:443
```

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
The below URL is just an example, all the services deployed in the cluster if enabled with istio and cert-manager for tls certificate, should work consistently.
```
https://kiali.one-dpo.com - should work always
```
**Steps to reproduce the bug**

1. Create a AKS cluster with k8s version 1.18.10
2. install istio using the steps given below
```
curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.7.1 sh -
cd istio-1.7.1;
export PATH=$PWD/bin:$PATH
istioctl install --set profile=demo --set meshConfig.accessLogFile=/dev/stdout
kubectl apply -f samples/addons
```
3. install letsencrypt cert-manager
```
kubectl create ns cert-manager

helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --version v1.0.3 \
  --set installCRDs=true
```
4. install cluster issuer staging (use any domain) - using staging certificate issuer here!
```
kubectl apply -f - <<EOF
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: istio-system
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: developer@youremail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the HTTP-01 challenge provider
    solvers:
      - selector: {}
        http01:
          ingress:
            class: istio
EOF
```
5. install istio tools certificate
```
kubectl apply -f - <<EOF
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: istio-tools-staging-certs
  namespace: istio-system
spec:
  secretName: istio-tools-staging-certs
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: kiali.one-dpo.com
  dnsNames:
  - kiali.one-dpo.com
  - tracing.one-dpo.com
  - grafana.one-dpo.com
EOF
```
6. install istio tools gateway
```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-tools-staging-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "kiali.one-dpo.com"
    - "tracing.one-dpo.com"
    - "grafana.one-dpo.com"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: "istio-tools-staging-certs"
    hosts:
    - "kiali.one-dpo.com"
    - "tracing.one-dpo.com"
    - "grafana.one-dpo.com"
EOF
```
7. install istio tools virtual service
```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali-virtualservice
  namespace: istio-system
spec:
  hosts:
  - "kiali.one-dpo.com"
  gateways:
  - istio-tools-staging-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 20001
        host: kiali
EOF
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

```
AKS
kubernetes version --short
Client Version: v1.18.3
Server Version: v1.18.10

helm version --short
v3.4.2+g23dd3af

istioctl version --remote
client version: 1.7.1
control plane version: 1.7.1
data plane version: 1.7.1 (2 proxies)
```

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
