### ISSUE TITLE
Istio-Ingress gateway not working behind GCP layer 7 LB for port 443

### ISSUE THREAD

**Issue by devil47sid** [istio/istio#29997]
**Bug description**
I am trying to set up a GCP HTTP(S) load balancer on top of the Istio-Ingress gateway using NEG. It's working as expected for port 80 however the load balancer giving 502 error when trying to connect with port 443 (8443 container port) while the same setup is working when I am exposing it with the TCP load balancer

[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Should be able to connect over secured port without any issue

**Steps to reproduce the bug**
1. Expose NEG for istio-ingress gateway service for port 443
2. Setup HTTPS Load Balancer and have NEG as backend and set backend protocol as HTTPS

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.8.5

**How was Istio installed?**
Manually

**Environment where the bug was observed (cloud vendor, OS, etc)**
Cloud Vendor: GCP
OS: COS
Cluster: GKE

**Comment by howardjohn** [comment]
Can you get more info from the GCP side than just 502? I think most people here are only Istio experts so it will be hard to move forward without more info or a GCP expert to help out.

**Comment by howardjohn** [comment]
GCLB will not send an SNI, so if you are configuring a Gateway to match on SNI (by `hosts`) it is not going to match.

**Comment by splushii** [comment]
In your `Gateway`, you can specify (for example) the `istio-system` namespace as a catch-all, then specify the other namespaces/hosts that should be able to bind to your `Gateway`, e.g.:
```yaml
---

apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      name: https-simple
      number: 8443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: istio-gateway-cert
    hosts:
    - 'istio-system/*'
    - 'some-namespace/example.com'
    - 'some-other-namespace/*.something.else.example.com'
```

**Comment by NickScottKortical** [comment]
Im trying to do the same thing as you @devil47sid did you manage to get it working in the end? Im not sure im following @splushii, I have tried with hosts set to

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: entry-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: ingress-cert
    hosts:
      - "*"
```
