### ISSUE TITLE
Redis proxy doesn't work with mtls

### ISSUE THREAD

**Issue by zhaohuabing** [istio/istio#30022]
**Bug description**
When setting `PILOT_ENABLE_REDIS_FILTER=true`, the Redis service doesn't work as expected.

Redis client reports upstream error:
```
➜  workspace k exec -it redis-test-client-5d88bb8f7d-fwhq8 -c redis-test-client -n redis -- redis-cli -h redis-test-server
redis-test-server:6379> set foo bar
(error) upstream failure
redis-test-server:6379>  
```

Envoy sidecar complains missing TCP MetadataExchange filter at the Redis server side:
```
2021-01-13T09:23:06.058835Z	warning	envoy filter	Incorrect istio-peer-exchange ALPN magic. Peer missing TCP MetadataExchange filter.
2021-01-13T09:23:09.464270Z	warning	envoy filter	Incorrect istio-peer-exchange ALPN magic. Peer missing TCP MetadataExchange filter.
````

Deployment:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-test-server
data:
  redis.conf: |
    protected-mode no
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-test-server
spec:
  selector:
    matchLabels:
      app: redis-test-server
  template:
    metadata:
      labels:
        app: redis-test-server
        istio-injection: enabled
    spec:
      containers:
        - name: server
          image: redis:6.0.8-alpine
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 6379
              name: tcp-redis
          command: ["redis-server", "/conf/redis.conf"]
          volumeMounts:
            - name: conf
              mountPath: /conf
              readOnly: false
      volumes:
        - name: conf
          configMap:
            name: redis-test-server
            defaultMode: 0755
---
apiVersion: v1
kind: Service
metadata:
  name: redis-test-server
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
   app: redis-test-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-test-client
    istio-injection: enabled
  name: redis-test-client
spec:
  selector:
    matchLabels:
      app: redis-test-client
  template:
    metadata:
      labels:
        app: redis-test-client
        istio-injection: enabled
    spec:
      containers:
      - image: redis
        imagePullPolicy: Always
        name: redis-test-client
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
```

[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Redis client could connect to Redis server through redis proxy and work as normal just as with tcp filter.

**Steps to reproduce the bug**
1. Set pilot environment variable `PILOT_ENABLE_REDIS_FILTER=true`
2. Deploy testing redis client and server with the yaml in the bug description
3. Run `kubectl exec -it redis-test-client-5d88bb8f7d-fwhq8 -c redis-test-client -n redis -- redis-cli -h redis-test-server` and try to put/set a key

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
➜  workspace ./istio-1.6.10/bin/istioctl version --remote 
client version: 1.6.10
control plane version: 1.8-dev
data plane version: 1.8.0 (13 proxies), 65536.65536.65536 (1 proxies)
➜  workspace kubectl version --short
Client Version: v1.19.3
Server Version: v1.18.4-tk8s.1
➜  workspace helm version --short
v3.4.2+g23dd3af
```

**How was Istio installed?**
Installed by Istioctl

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
