### ISSUE TITLE
Flood of DNS requests in cluster

### ISSUE THREAD

**Issue by Zastr** [istio/istio#30034]
# Problem

For STRICT_DNS clusters, respect_dns_ttl should prevent polling the default of every 5 seconds. Even with dnsRefreshRate set in the meshConfig, DNS polling is creating an excessive amount of requests. 

**Affected product area**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Polling based on DNS TTL or the set dnsRefreshRate.

**Steps to reproduce the bug**
Current IstioOperator MeshConfig
```
meshConfig:
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    defaultConfig:
      concurrency: 2
      sds:
        enabled: false
    h2UpgradePolicy: DO_NOT_UPGRADE
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
    protocolDetectionTimeout: 0s
    dnsRefreshRate: 300s
```
 
Example service:
```
▶ istioctl proxy-config cluster -n istio-system internal-ingressgateway | grep sqs
SERVICE FQDN                                         PORT      SUBSET     DIRECTION     TYPE           
email.us-west-2.amazonaws.com            443                -          outbound      STRICT_DNS
```
30 second capture of dns traffic: [tshark.txt](https://github.com/istio/istio/files/5810289/tshark.txt)

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
▶ istioctl version --remote                                     
client version: 1.7.2
control plane version: 1.7.3
data plane version: 1.7.3 (103 proxies)
```

```
▶ kubectl version --short
Client Version: v1.19.3
Server Version: v1.17.12-eks-7684af
```

**How was Istio installed?**
ArgoCD

**Environment where the bug was observed (cloud vendor, OS, etc)**
EKS
