### ISSUE TITLE
[Documentation] Istio Authorization Policy "principals" works without mTls

### ISSUE THREAD

**Issue by brunooliveiramac** [istio/istio#30039]
**Bug description**
Hi all, 
As the documentation says, we should have mtls enabled in our cluster or the microservices that want to user AuthiorizationPolicy using the principal field.

Istio uses mutual TLS to securely pass some information from the client to the server. Mutual TLS must be enabled before using any of the following fields in the authorization policy:
- the **principals** field under the source section

**Reference**: https://istio.io/v1.7/docs/concepts/security/#dependency-on-mutual-tls

The point is, we apply this configuration bellow and the AuthorizationPolicy is working without mTls enabled

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: identity-metadata-service
spec:
  selector:
    matchLabels:
      app: identity-metadata-service
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/default/sa/identity-service-account"]
    to:
    - operation:
        methods: ["GET"]
        paths: ["/actuator/info"]
```
The result works as declared on the AuthorizationPolicy file **but without any mTls enabled between the pods**.

![image](https://user-images.githubusercontent.com/10716628/104506781-9b286980-55c4-11eb-8a2f-5994e949af11.png)

![image](https://user-images.githubusercontent.com/10716628/104507013-ed698a80-55c4-11eb-917e-7986eafbea02.png)

**Expected behavior**
The AuthorizationPolicy should not work?

**Steps to reproduce the bug**
Apply any authorization policy using **principals** rule without mtls enabled

**Version**
istio 1.7
kubernetes 1.18.8

**How was Istio installed?**
Using istio operator 1.7.2
http://github.com/istio/istio/operator

**Environment where the bug was observed (cloud vendor, OS, etc)**
Azure AKS
