### ISSUE TITLE
env variable ISTIO_META_IDLE_TIMEOUT set to 0s cannot disable idle_timeout

### ISSUE THREAD

**Issue by caoyukun0430** [istio/istio#30067]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
When I install tcp-echo service(https://github.com/istio/istio/tree/release-1.1/samples/tcp-echo), I want to disable the idle_timeout on TCP level using the istio environment variable ISTIO_META_IDLE_TIMEOUT, as stated in envoy doc https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/tcp_proxy/v3/tcp_proxy.proto#envoy-v3-api-field-extensions-filters-network-tcp-proxy-v3-tcpproxy-idle-timeout, it can be disabled by set to 0s. 
So I try to disable idle_timeout using the following annotation in both client and server. 
```
annotations:
   proxy.istio.io/config: |-
      proxyMetadata:
         ISTIO_META_IDLE_TIMEOUT: "0s"
```
But the connection is still turned off automatically after 1 hour, which is exactly the same behavior as I don't define the ISTIO_META_IDLE_TIMEOUT, then default 1h value is used. 
Then I checked the proxy-config information for idle_timeout, with or without defining  ISTIO_META_IDLE_TIMEOUT: "0s", I cannot see "idleTimeout: 0s"
```
istioctl proxy-config listeners tcp-echo-778bfdcf56-gpt6b.testcase01 --port 9000 -o json
        "filterChains": [
            {
                "filters": [
                    {
                        "name": "envoy.filters.network.tcp_proxy",
                        "typedConfig": {
                            "@type": "type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy",
                            "statPrefix": "outbound|9000||tcp-echo.testcase01.svc.cluster.local",
                            "cluster": "outbound|9000||tcp-echo.testcase01.svc.cluster.local",
```
I would expect the configuration like 
```
        "filterChains": [
            {
                "filters": [
                    {
                        "name": "envoy.filters.network.tcp_proxy",
                        "typedConfig": {
                            "@type": "type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy",
                            "statPrefix": "outbound|9000||tcp-echo.testcase01.svc.cluster.local",
                            "cluster": "outbound|9000||tcp-echo.testcase01.svc.cluster.local",
                             **"idleTimeout": "0s"**
```
And I also tried to define ISTIO_META_IDLE_TIMEOUT to be any other values, for example, "60s", then I can definitely see "idleTimeout: 60s" information in the istioctl proxy-config. 
```
        "filterChains": [
            {
                "filters": [
                    {
                        "name": "envoy.filters.network.tcp_proxy",
                        "typedConfig": {
                            "@type": "type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy",
                            "statPrefix": "outbound|9000||tcp-echo.testcase01.svc.cluster.local",
                            "cluster": "outbound|9000||tcp-echo.testcase01.svc.cluster.local",
                             "idleTimeout": "60s"
```
Therefore, I think by defining ISTIO_META_IDLE_TIMEOUT: "0s", istio doesn't disable the idle_timeout, but instead set it to be default value 1h.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
By setting  ISTIO_META_IDLE_TIMEOUT: "0s", idle_timeout is disabled, and the connection will not be turned off automatically after 1 hour.
The alternative I used to disable idle_timeout is via envoyfilter. In this way, I also see the "idleTimeout: 0s" information in the istioctl proxy-config.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: listener-timeout-tcp
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.tcp_proxy
    patch:
      operation: MERGE
      value:
        name: envoy.filters.network.tcp_proxy
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          idle_timeout: 0s
```

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
$ istioctl version --remote
client version: 1.7.4
control plane version: 1.7.4
data plane version: 1.7.4 (3 proxies)
$ kubectl version --short
Client Version: v1.19.2
Server Version: v1.19.2

**How was Istio installed?**
istioctl install --set profile=default -y
**Environment where the bug was observed (cloud vendor, OS, etc)**
Virtual Machine Ubuntu 18.04.5 LTS
Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by GregHanson** [comment]
@caoyukun0430 Envoy has a few difference places where `idleTimeout` can be set - do you see the expected behavior with an EnvoyFilter that sets it at the cluster level?

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: "custom-idle-timeout"
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      context: ANY
    patch:
      operation: MERGE
      value:
        common_http_protocol_options:
          idle_timeout: 8h
```

**Comment by caoyukun0430** [comment]
> @caoyukun0430 Envoy has a few difference places where `idleTimeout` can be set - do you see the expected behavior with an EnvoyFilter that sets it at the cluster level?
> 
> ```
> apiVersion: networking.istio.io/v1alpha3
> kind: EnvoyFilter
> metadata:
>   name: "custom-idle-timeout"
> spec:
>   configPatches:
>   - applyTo: CLUSTER
>     match:
>       context: ANY
>     patch:
>       operation: MERGE
>       value:
>         common_http_protocol_options:
>           idle_timeout: 8h
> ```

Hi, I am also aware that idle_timeout in envoy has both http and tcp level, and I focus on the idle_timeout on the tcp level. So as I wrote, with the following envoyfilter configuration, I can disable the idle_timeout at TCP level as I expected. I didn't try the one you mentioned since yours is the http level idle_timeout.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: listener-timeout-tcp
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.tcp_proxy
    patch:
      operation: MERGE
      value:
        name: envoy.filters.network.tcp_proxy
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          idle_timeout: 0s
```
