### ISSUE TITLE
istioctl: manifest generation bug when combining multiple Operator.yaml files

### ISSUE THREAD

**Issue by shankgan** [istio/istio#30078]
When attempting to add a new e2e test case to istio, my istio setup config in TestMain produces a test artifact `test-iop.yaml` (below). Specifically, I add two environment variables to pilot component through k8s overlay. 

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    pilot:
      k8s:
        env:
        - name: EXTERNAL_CA
          value: ISTIOD_RA_KUBERNETES_API
        - name: K8S_SIGNER
          value: kubernetes.io/legacy-unknown
  hub: docker.io/istio
  tag: latest
  values:
    meshConfig:
      trustDomainAliases:
      - some-other
      - trust-domain-foo
```

**When I run the test however, these two environment variables (EXTERNAL_CA and K8s_SIGNER) are not a part of the istiod deployment k8s manifest whereas the meshconfig trustDomainAliases are configured correctly**. While debugging, I found that istioctl manifest generation is not happening correctly when combining my test-manifest file (test-iop.yaml) with the default test-infrastructure iop file ([iop-integration-test-defaults.yam](https://github.com/istio/istio/blob/master/tests/integration/iop-integration-test-defaults.yaml)l). 

However, when I try to generate the manifest with JUST my test-iop.yaml file, manifest generation works correctly and the two environment variables are correctly added to the istiod deployment K8s manifest. I have outlined steps to reproduce below

I am not familiar with the details of how exactly istioctl merges these multiple manifests together. Would appreciate any help to debug what is going on.  Adding e2e test is blocked on this.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[X] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
The Generated K8s Istiod Deployment Yaml should contain the new environment variables injected.

**Steps to reproduce the bug**
Get test-iop.yaml from the bug description and copy this into repo.
cd into the istio-repo and execute these commands.

`istioctl manifest generate -f test-iop.yaml > 1.yaml`

`istioctl manifest generate -f tests/integration/iop-integration-test-defaults.yaml -f test-iop.yaml > 2.yaml`

Look for the environment variable EXTERNAL_CA in the K8s Istiod deployment manifest. The Former will have it, the Latter will not have it.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
istioctl version
client version: 1.9-dev
control plane version: 1.9-dev-b1bf36ae2aef02ae4df667254cd83a3130b7a62f
data plane version: 1.9-dev (3 proxies)

**How was Istio installed?**
NA

**Environment where the bug was observed (cloud vendor, OS, etc)**
Istioctl was built for Mac OS X

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
