### ISSUE TITLE
DestinationRule and virtual service selection can lead to unexpected mismatches

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30080]
Consider a setup where I have two namespace:
* `default`, with some Service `echo` and config

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: echo
  namespace: default
spec:
  host: echo
  subsets:
  - name: v1
  - name: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: echo
  namespace: default
spec:
  hosts:
  - echo
  http:
  - route:
    - destination:
        host: echo
        subset: v1
```

*  `client`, which calls `echo`.

With this config, they will send traffic to subset v1.

Now, the client decides they want to override some server settings. They don't know anything about the `echo` Service's Istio configurations, since they do not control them (default namespace does). They create a DR:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: echo
  namespace: client
spec:
  host: echo.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
```

Now we have *removed* the subset, so the route will start failing.

In order to fix this, the `client` namespace needs to add the right subsets. To do this, they most likely need to figure out the right label selectors for pods in the default namespace, which is leaking implementation details. Additionally, if the virtual service is changed at anytime by the `default` namespace admin, `client` will be broken.
