### ISSUE TITLE
Getting external service connection issue with ALLOW_ANY mode

### ISSUE THREAD

**Issue by Arnuphap-Yupuech** [istio/istio#30108]
**Bug description**
We are facing connection issue when we trying to connect external service with HTTP 500 with "no healthy upstream" error. We already applied Service Entry, Virtual Service, and Destination Rule already but we still got the same error.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
We should be able to connect to external service.

**Steps to reproduce the bug**

1. We apply Service Entry, Virtual Service, and Destination Rule as follow.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-service
spec:
  exportTo:
    - "."
  hosts:
    - external.service.
  location: MESH_EXTERNAL
  ports:
    - number: 8448
      name: https
      protocol: HTTPS
    - number: 80
      name: http
      protocol: HTTP
  resolution: DNS
```
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: external-service
spec:
  exportTo:
    - "."
  hosts:
    - external.service
  http:
    - route:
        - destination:
            host: external.service.
            subset: tls-origination
            port:
              number: 8448
```
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: external-service
spec:
  exportTo:
    - "."
  host: external.service.
  subsets:
    - name: tls-origination
      trafficPolicy:
        loadBalancer:
          simple: ROUND_ROBIN
        portLevelSettings:
          - port:
              number: 8448
            tls:
              mode: SIMPLE
              sni: external.service.
```

2. We exec into the application pod and try to curl the host that we set
3. We getting HTTP 500 with "no healthy upstream" error

**Workaround**
We come up with a workaround by adding the static IP after resolved at the endpoints of the service entry as follow.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-service
spec:
  endpoints:
  - address: x.x.x.x
  exportTo:
    - "."
  hosts:
    - external.service.
  location: MESH_EXTERNAL
  ports:
    - number: 8448
      name: https
      protocol: HTTPS
    - number: 80
      name: http
      protocol: HTTP
  resolution: DNS
```

**Version** 
Istio version 1.7.2
Kubernetes version 1.18.9

**How was Istio installed?**
```shell
istioctl install -f <istio_profile.yaml>
```

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS EKS Service with Linux worker node
