### ISSUE TITLE
status: reconciled unexpectedly goes from True -> False

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30127]
The expectation for reconciled is its a "circuit breaker": once we have reconciled a given generation, we will always stay reconciled until the generation changes.

This is not the observed behavior, however:

```
$ for i in {3..5}; do cat xx0$i | rg ^status -A 10; done
status:
  conditions:
  - lastProbeTime: "2021-01-15T21:29:14.596607993Z"
    lastTransitionTime: "2021-01-15T21:29:14.596608327Z"
    message: 2456/2456 proxies up to date.
    status: "True"
    type: Reconciled
  observedGeneration: "68"
status:
  conditions:
  - lastProbeTime: "2021-01-15T21:29:14.997033897Z"
    lastTransitionTime: "2021-01-15T21:29:14.997034120Z"
    message: 2460/2460 proxies up to date.
    status: "True"
    type: Reconciled
  observedGeneration: "68"
status:
  conditions:
  - lastProbeTime: "2021-01-15T21:29:19.596660535Z"
    lastTransitionTime: "2021-01-15T21:29:19.596660812Z"
    message: 2452/2456 proxies up to date.
    status: "False"
    type: Reconciled
  observedGeneration: "68"
```

This shows 3 updates on  a single resource. We can see it goes from Reconciled=true -> Reconciled=false and the proxy count looks unexpected

**Comment by howardjohn** [comment]
```
status:
  conditions:
  - lastProbeTime: "2021-01-15T21:29:23.596060576Z"
    lastTransitionTime: "2021-01-15T21:29:23.596060945Z"
    message: 2456/2456 proxies up to date.
    status: "True"
    type: Reconciled
  observedGeneration: "68"
status:
  conditions:
  - lastProbeTime: "2021-01-15T21:29:23.996805237Z"
    lastTransitionTime: "2021-01-15T21:29:23.996805566Z"
    message: 2460/2460 proxies up to date.
    status: "True"
    type: Reconciled
  observedGeneration: "68"
status:
  conditions:
  - lastProbeTime: "2021-01-15T21:29:27.596086249Z"
    lastTransitionTime: "2021-01-15T21:29:27.596086612Z"
    message: 2456/2456 proxies up to date.
    status: "True"
    type: Reconciled
  observedGeneration: "68"
```

Aside from the flip flopping back to false, I also get a bunch of flip flopping of proxy amounts. I ended up seeing 50 writes for a single generation.
