### ISSUE TITLE
Status API issues

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30120]
After deploying an invalid VS, from PR https://github.com/istio/istio/pull/29275/files, I see:

```yaml
status:
  conditions:
  - lastProbeTime: "2021-01-15T19:45:54.504546007Z"
    lastTransitionTime: "2021-01-15T19:45:54.504547691Z"
    message: 4/4 proxies up to date.
    status: "True"
    type: Reconciled
  observedGeneration: "1"
  validationMessages:
  - documentation_url: https://istio.io/v1.1/docs/reference/config/analysis/ist0101/?ref=status-controller
    level: 3
    type:
      code: IST0101
  - documentation_url: https://istio.io/v1.1/docs/reference/config/analysis/ist0132/?ref=status-controller
    level: 8
    type:
      code: IST0132
```

A few concerns here:
* `4/4 proxies up to date` is wrong/misleading. I have many more proxies in my cluster at this point. I recommend we just say its been distributed to ALL proxies, rather than a fixed number. I think the number is also (sometimes?) 4x the number of proxies, one for each resource type.
* `level: 3` does not help, it should be a string. Somehow it showed strings once, but then never after that, so I don't know what happened there
* The message only has a code, which is not very useful. I get a link to the docs - but I never see the error message so I don't know what isthe problem. A code is not sufficient to diagnose, I may have 100s of fields in some resource and only one is invalid, for example
* We mix camel and snake case in a bunch of places
* The version is wrong. Its meant to be v1.10, (Which is also wrong, is it doesn't exist yet) because we do `baseVersion[:3]` in the code so it doesn't handle 2 digit numbers.
