### ISSUE TITLE
Istio Virtual Service DNS not resolving

### ISSUE THREAD

**Issue by juandiegopalomino** [istio/istio#30132]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
I am running istio v1.8.1 on an EKS v18 cluster with the demo profile, installed via the istio operator.
I created a virtual service in the hello-world namespace with the following spec:
```
spec:
  gateways:
  - mesh
  hosts:
  - hello-world.hello-world
  - hello-world
  - google.com
  - blah.dev
  http:
  - match:
    - port: 80
    - port: 443
    route:
    - destination:
        host: hello-world.hello-world.svc.cluster.local
```
But it seems like there is dns resolution problems:
Coming from a pod in the service mesh in the SAME namespace: hello-world, hello-world.hello-world and google.com all resolve to the VS' destination with no problem, but "blah.dev" could not resolve host: `curl: (6) Could not resolve host: blah.dev`

Coming from a pod in the service mesh in a DIFFERENT namespace: hello-world.hello-world and google.com resolve to the VS' destination with no problem, but "blah.dev" and "hello-world" do not with the same issue as before.

It seems to me that the pod (at least when using curl) can not resolve dns hosts defined by istio virtual services. Rather, the host _must_ exist either as a public domain or one defined as a k8s service. If the dns can be resolved by the pod (e.g. google.com or hello-world in the same namespace as the service, or the expanded hello-world.hello-world which includes the namespace), then istio will route it correctly.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
hello-world, and blah.dev resolve to the virtual service's destination regardless of namespace.

**Steps to reproduce the bug**
Please see description above

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**
Via the istio operator. Here is the profile:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
  labels:
  {{- include "istio-vanilla-profile.labels" . | nindent 4 }}
spec:
  profile: default
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          service:
            externalTrafficPolicy: Local
            ports:
            - name: status-port
              port: 15021
              protocol: TCP
              targetPort: 15021
            - name: http2
              port: 80
              protocol: TCP
              targetPort: 8080
            - name: https
              port: 443
              protocol: TCP
              targetPort: 8443
            - name: tcp
              port: 31400
              protocol: TCP
              targetPort: 31400
            - name: grpc
              port: 50051
              protocol: TCP
              targetPort: 50051
            - name: tls
              port: 15443
              protocol: TCP
              targetPort: 15443
  values:
    gateways:
      istio-ingressgateway:
        loadBalancerSourceRanges:
          - 0.0.0.0/0
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https,grpc"
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: REDACTED
          external-dns.alpha.kubernetes.io/hostname: REDACTED
```

**Environment where the bug was observed (cloud vendor, OS, etc)**
EKS v 1.18, freshly spun up

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

[bug-report.zip](https://github.com/istio/istio/files/5823231/bug-report.zip)
