### ISSUE TITLE
Sampling value for tracing configuration cannot be overriden by deployment metadata specification using proxy.istio.io/config annotation

### ISSUE THREAD

**Issue by mkaman** [istio/istio#30141]
**Bug description**

Related documentation:
https://istio.io/latest/docs/tasks/observability/distributed-tracing/configurability/#create-a-meshconfig-with-trace-settings

No tracing data of the pods that have been overriden by proxy.istio.io/config annotation could be sent to / viewed on jaeger, when sampling value is specified in deployment metadata specification using proxy.istio.io/config annotation. There is no problem when only meshConfig is used / configured.

```yml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    defaultConfig:
      tracing:
        sampling: 20
```
Deployment metadata:

```yml
spec:
  template: 
    metadata:
      annotations:
        proxy.istio.io/config: |
          tracing:
            sampling: 100
```
**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ X] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

The meshConfig sampling value (in this case 20) should be overridden by using proxy.istio.io/config annotation (100)  and tracing data should be collected by jaeger.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

istioctl:
client version: 1.8.1
control plane version: 1.8.1
data plane version: 1.8.1 (5 proxies)

kubectl:
Client Version: v1.19.0
Server Version: v1.20.0

minikube 
version: v1.16.0

**How was Istio installed?**

via istioctl 

**Environment where the bug was observed (cloud vendor, OS, etc)**

Ubuntu 20.04

[bug-report.zip](https://github.com/istio/istio/files/5824697/bug-report.zip)
