### ISSUE TITLE
Istio internal DNS resolution intermittent failures

### ISSUE THREAD

**Issue by jejikenwogu** [istio/istio#30153]
### Bug description

When doing DNS resolution for databases added using ServiceEntry's I get mixed results.  The majority of the time we get back a non-routable internal VIP (240.240.0.8) which is expected, but once every few minutes it looks like the istio agent fails to intercept a DNS request and I get the actual IP back.  This is causing failovers in our connection pool since the IP address keeps changing back and forth.

```
/ # while true; do dig economy-apg-w.loadtest.example.local.example.com | grep -A 4 "ANSWER SECTION"; sleep 1; done

;; Query time: 0 msec
;; SERVER: 172.20.0.10#53(172.20.0.10)
;; ANSWER SECTION:
economy-apg-w.loadtest.example.local.example.com. 30 IN A 240.240.0.8

;; Query time: 0 msec
;; SERVER: 172.20.0.10#53(172.20.0.10)
;; ANSWER SECTION:
economy-apg-w.loadtest.example.local.example.com. 30 IN A 240.240.0.8

;; Query time: 0 msec
;; SERVER: 172.20.0.10#53(172.20.0.10)
;; ANSWER SECTION:
economy-apg-w.loadtest.example.local.example.com. 30 IN A 240.240.0.8

;; Query time: 0 msec
;; SERVER: 172.20.0.10#53(172.20.0.10)
;; ANSWER SECTION:
economy-apg-w.loadtest.example.local.example.com. 1 IN CNAME loadtest-apg-economy.cluster-blah.us-west-2.rds.amazonaws.com.
loadtest-apg-economy.cluster-blah.us-west-2.rds.amazonaws.com. 1 IN CNAME loadtest-apg-economy-0.blah.us-west-2.rds.amazonaws.com.
loadtest-apg-economy-0.blah.us-west-2.rds.amazonaws.com. 1 IN A 10.199.219.201

;; ANSWER SECTION:
economy-apg-w.loadtest.example.local.example.com. 30 IN A 240.240.0.8

;; Query time: 3 msec
;; SERVER: 172.20.0.10#53(172.20.0.10)
;; ANSWER SECTION:
economy-apg-w.loadtest.example.local.example.com. 30 IN A 240.240.0.8

;; Query time: 3 msec
;; SERVER: 172.20.0.10#53(172.20.0.10)
;; ANSWER SECTION:
economy-apg-w.loadtest.example.local.example.com. 30 IN A 240.240.0.8
```

### Affected product area (please put an X in all that apply)

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

### Expected behavior

I'd expect my hostname to always resolve to the non-routable internal VIP allocated by IstioD.

### Steps to reproduce the bug

1. Deploy ServiceEntry
2. Run ```dig``` in loop to see DNS changes.

ServiceEntry:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: economy-apg-w
  namespace: loadtest
spec:
  hosts:
    - "economy-apg-w.loadtest.example.local.example.com"
  location: MESH_EXTERNAL
  ports:
    - number: 5432
      name: postgres
      protocol: TCP
  resolution: DNS
```

### Version (include the output of istioctl version --remote and kubectl version --short and helm version --short if you used Helm)
```
[jejikenwogu@07098a-jejikenwogu ~] (2021-01-18 00:19:01) $ istioctl version --remote
client version: 1.8.2
control plane version: 1.8.2
data plane version: 1.8.2 (137 proxies), 1.7.0 (1 proxies) 

[jejikenwogu@07098a-jejikenwogu ~] (2021-01-18 00:19:03) $ kubectl version --short
Client Version: v1.17.12-eks-7684af
Server Version: v1.16.15-eks-ad4801
```
\* The 1 old proxy belongs to a cronjob.  Any suggestions on updating this to the newest version is also welcome. :) 

### How was Istio installed?

istioctl install -f <IstioOperator>
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  meshConfig:
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_PROXY_XDS_VIA_AGENT: "true"
  components:
    base:
      enabled: true
    pilot:
      enabled: true
      k8s:
        nodeSelector:
          type: istio
        tolerations:
          - effect: NoSchedule
            key: dedicated
            operator: Equal
            value: istio
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 3
          timeoutSeconds: 5
        strategy:
          rollingUpdate:
            maxSurge: "100%"
            maxUnavailable: "25%"
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          serviceAnnotations:
            external-dns.alpha.kubernetes.io/hostname: "services.loadtest.example.example.com"
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
            service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: "<security-group>"
            service.beta.kubernetes.io/aws-load-balancer-internal: "0.0.0.0/0"
            service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
            service.beta.kubernetes.io/aws-load-balancer-additional-tags: "cmdb_deploymoent=example,cmdb_nodepool=example-loadtest-eks-nlb,kube_cluster_name=example-loadtest"
          nodeSelector:
            type: istio
          tolerations:
            - effect: NoSchedule
              key: dedicated
              operator: Equal
              value: istio
          env:
            - name: ISTIO_META_ROUTER_MODE
              value: "sni-dnat"
          service:
            ports:
              - port: 15021
                targetPort: 15021
                name: status-port
              - port: 80
                targetPort: 8080
                name: http2
              - port: 443
                targetPort: 8443
                name: https
              - port: 15443
                targetPort: 15443
                name: tls
          hpaSpec:
            maxReplicas: 5
            minReplicas: 1
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: istio-ingressgateway
            metrics:
              - type: Resource
                resource:
                  name: cpu
                  targetAverageUtilization: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 2000m
              memory: 1024Mi
          strategy:
            rollingUpdate:
              maxSurge: "100%"
              maxUnavailable: "25%"
  values:
    global:
      istioNamespace: istio-system
      logging:
        level: "default:error"
      logAsJson: true
      proxy:
        holdApplicationUntilProxyStarts: true
    pilot:
      autoscaleEnabled: true
      autoscaleMin: 1
      autoscaleMax: 5
      replicaCount: 1
      image: pilot
    gateways:
      istio-egressgateway:
        zvpn: {}
        env: {}
        autoscaleEnabled: true
        type: ClusterIP
        name: istio-egressgateway
        secretVolumes:
          - name: egressgateway-certs
            secretName: istio-egressgateway-certs
            mountPath: /etc/istio/egressgateway-certs
          - name: egressgateway-ca-certs
            secretName: istio-egressgateway-ca-certs
            mountPath: /etc/istio/egressgateway-ca-certs
    sidecarInjectorWebhook:
      enableNamespacesByDefault: false
      rewriteAppHTTPProbe: true
      objectSelector:
        enabled: false
        autoInject: true
```

### Environment where the bug was observed (cloud vendor, OS, etc)

We have a kubernetes cluster running in AWS EKS using the Amazon EKS optimized images.
The container I'm running the ```dig``` command from is based on ```alpine:3.12```
