### ISSUE TITLE
question: how to redirect https://example.org to http://my-internal-service.default.svc.cluster.local

### ISSUE THREAD

**Issue by larsrnielsen** [istio/istio#30158]
Question: how to redirect https://example.org to http://my-internal-service.default.svc.cluster.local ?  

I think I have tried all different flavours of ServiceEntry configurations, although I like to stay clear of hard coding IP addresses. All my `curl -Iv https://example.org` testing seems to resolve the URL to the external IP rather than my service IP. 

Do I need an egress gateway for it?

thanks, 

   Lars

**Comment by esnible** [comment]
You may need a VirtualService to go with your ServiceEntry, similar to the Wikipedia example in https://istio.io/latest/docs/reference/config/networking/service-entry/

You should not need an egress gateway.

Using _curl_, the DNS lookup will return the original example.org value, not the `my-internal-service` IP address.  The Envoy sidecar on the container doing the _curl_ will see `example.org` in the SNI and call `my-internal-service` instead.

When I get stuck I set up the Wikipedia example.  If that works I save a copy of my old ServiceEntry and friends, modify the Wikipedia example to use the host names I was intending, and see if that works.  If it does, I `diff` against my own attempt to see what happened.

**Comment by larsrnielsen** [comment]
> You may need a VirtualService to go with your ServiceEntry, similar to the Wikipedia example in https://istio.io/latest/docs/reference/config/networking/service-entry/
> 
> You should not need an egress gateway.
> 
> Using _curl_, the DNS lookup will return the original example.org value, not the `my-internal-service` IP address. The Envoy sidecar on the container doing the _curl_ will see `example.org` in the SNI and call `my-internal-service` instead.
> 
> When I get stuck I set up the Wikipedia example. If that works I save a copy of my old ServiceEntry and friends, modify the Wikipedia example to use the host names I was intending, and see if that works. If it does, I `diff` against my own attempt to see what happened.

Hi,

   Thanks for your reply. I did the following:
```
cat <<EOF > wiki.yaml                                                                                                                           ✔ │ 09:01:37
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-svc-redirect
spec:
  hosts:
  - wikipedia.org
  - "*.wikipedia.org"
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: NONE
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-svc-redirect2
spec:
  hosts:
  - google.com
  - www.google.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: tls-routing
spec:
  hosts:
  - wikipedia.org
  - "*.wikipedia.org"
  tls:
  - match:
    - sniHosts:
      - wikipedia.org
      - "*.wikipedia.org"
    route:
    - destination:
        host: my-testservice.default.svc.cluster.local
EOF

> kubectl apply -f wiki.yaml
serviceentry.networking.istio.io/external-svc-redirect created
serviceentry.networking.istio.io/external-svc-redirect2 created
virtualservice.networking.istio.io/tls-routing created

> kubectl run test --image=centos -it --rm -- /bin/sh
If you don't see a command prompt, try pressing enter.

> curl -Is http://my-testservice.default.svc.cluster.local |grep HTTP
HTTP/1.1 200 OK

curl -I https://wikipedia.org
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number

curl -Is https://www.google.com |grep HTTP
HTTP/2 200
```

In other words, I am able to curl outside the cluster, but I face SSL issues when redirecting to internal services.

**Comment by howardjohn** [comment]
The example above works for me, can you post a config dump? See https://github.com/istio/istio/wiki/Troubleshooting-Istio

**Comment by larsrnielsen** [comment]
Sure, do you have an idea of which config dump(s) are important? Some of the dumps are several thousands of lines. 

Lars

```
❯ cat <<EOF |kubectl apply -f -
pipe heredoc> >....
  - wikipedia.org
  - "*.wikipedia.org"
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: NONE
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-svc-redirect2
spec:
  hosts:
  - google.com
  - www.google.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: tls-routing
spec:
  hosts:
  - wikipedia.org
  - "*.wikipedia.org"
  tls:
  - match:
    - sniHosts:
      - wikipedia.org
      - "*.wikipedia.org"
    route:
    - destination:
        host: nginx-test.cms-tools.svc.cluster.local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
pipe heredoc> EOF
serviceentry.networking.istio.io/external-svc-redirect created
serviceentry.networking.istio.io/external-svc-redirect2 created
virtualservice.networking.istio.io/tls-routing created
deployment.apps/nginx-deployment created
service/nginx-test created
```

Issue
```
❯ kubectl run test --image=centos -it --rm -- /bin/sh
If you don't see a command prompt, try pressing enter.

sh-4.4# curl -Is http://nginx-test |grep HTTP
HTTP/1.1 200 OK
sh-4.4# curl https://wikipedia.org
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

**Comment by larsrnielsen** [comment]
OK - I created a demo cluster with eksctl with EKS 1.18 as my k8s platform service. I installed AWS LB Controller, Cert-Manager, Istio Operator, Istio 1.8.2 via Helm. Istio Operator was configured with:
- 1x Istio ingress gateway, NLB configured with an ACM certificate. 

I created two Nginx deployments, one listening to port 80 and another with a self-signed certificate listening on 443. I am now able to route `http://wikipedia.org` and `https://wikipedia.org` to the internal Nginx deployments. If I reconfigure the `VirtualService` to route to the Nginx server only able to handle HTTP traffic then I get the mentioned error: `curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number`. 

My question is then, am I only able to route to internal services if I use the same protocol? I.e., *https*://wikipedia.org routed to *http*://internal.default.svc.cluster.local is *not* possible. Or can I do so, by using some other Istio configuration?

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-svc-redirect
spec:
  hosts:
  - wikipedia.org
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  - number: 80
    name: http
    protocol: HTTP
  resolution: NONE

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nginx-test
  namespace: cms-tools
spec:
  hosts:
  - wikipedia.org
  - "*.wikipedia.org"
  http:
    - name: http
      route:
      - destination:
          host: nginx-test.cms-tools.svc.cluster.local # http enabled Nginx
  tls:
  - match:
    - sniHosts:
      - wikipedia.org
      - "*.wikipedia.org"
    route:
    - destination:
        host: my2-nginx.cms-tools.svc.cluster.local # https enabled Nginx. SSL failure if this is changed to nginx-test.....

---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-svc-redirect
spec:
  hosts:
  - wikipedia.org
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  - number: 80
    name: http
    protocol: HTTP
  resolution: NONE

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nginx-test
  namespace: cms-tools
spec:
  hosts:
  - wikipedia.org
  - "*.wikipedia.org"
  http:
    - name: http
      route:
      - destination:
          host: nginx-test.cms-tools.svc.cluster.local # http enabled Nginx
  tls:
  - match:
    - sniHosts:
      - wikipedia.org
      - "*.wikipedia.org"
    route:
    - destination:
        host: my2-nginx.cms-tools.svc.cluster.local # https enabled Nginx

# SSL ENABLED NGINX BELOW

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: test-selfsigned
  namespace: cms-tools
spec:
  selfSigned: {}



---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress2-cert
  namespace: cms-tools
spec:
  dnsNames:
    - my2.example.com
  secretName: ingress2-cert
  commonName: my2.example.com
  issuerRef:
    name: test-selfsigned
---
apiVersion: v1
data:
  nginx.conf: |
    events {
    }

    http {
      log_format main ' -  []  35 '
      '""  "" '
      '"" ""';
      access_log /var/log/nginx/access.log main;
      error_log  /var/log/nginx/error.log;

      server {
        listen 443 ssl;

        root /usr/share/nginx/html;
        index index.html;

        server_name my2.example.com;
        ssl_certificate /etc/nginx-server-certs/tls.crt;
        ssl_certificate_key /etc/nginx-server-certs/tls.key;
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-24T11:52:39Z"
  name: nginx-configmap
  namespace: cms-tools
---
apiVersion: v1
kind: Service
metadata:
  name: my2-nginx
  labels:
    run: my2-nginx
  namespace: cms-tools
spec:
  ports:
  - port: 443
    protocol: TCP
  selector:
    run: my2-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my2-nginx
  namespace: cms-tools
spec:
  selector:
    matchLabels:
      run: my2-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: my2-nginx
    spec:
      containers:
      - name: my2-nginx
        image: nginx
        ports:
        - containerPort: 443
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx
          readOnly: true
        - name: nginx-server-certs
          mountPath: /etc/nginx-server-certs
          readOnly: true
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-configmap
      - name: nginx-server-certs
        secret:
          secretName: ingress2-cert
---

# HTTP ENABLED NGINX

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: cms-tools
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test
  namespace: cms-tools
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
---
apiVersion: v1
kind: Pod
metadata:
  name: tester
  namespace: cms-tools
  labels:
    name: tester
spec:
  containers:
  - name: tester
    image: centos
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
      - /bin/sh
      - -c
      - "sleep 3600"
 ---
```

**Comment by howardjohn** [comment]
```
  tls:
  - match:
    - sniHosts:
      - wikipedia.org
      - "*.wikipedia.org"
    route:
    - destination:
        host: my2-nginx.cms-tools.svc.cluster.local # https enabled Nginx. SSL failure if this is changed to nginx-test.....
```

So, if you had nginx-test here, here is what is happening:

`app ---- TLS ---> Envoy`. Envoy does NOT terminate the TLS. Instead, it is merely looking at the SNI, and determining where to send the request. If you send it to nginx-test, that is now forwarding the original TLS request to a plaintext endpoint

Even if you forward it to a TLS endpoint, your application _should_ reject the result, as the TLS handshake should be rejected. You probably need to use `curl -k` for example, or equivalent in whatever client you use.
