### ISSUE TITLE
Incorrect RemoteIP when Authorization Policy is applied to Injected Istio Proxy

### ISSUE THREAD

**Issue by anyname2** [istio/istio#30166]
**Bug description**
![IstioAuthPolicy](https://user-images.githubusercontent.com/2305836/104956010-289ffb00-59c3-11eb-9ca4-f673f85bf4b4.png)

When `AuthorizationPolicy` is applied to injected istio proxy, `remoteIpBlocks` does not work as expected when istio gateway is behind another reverse proxy (Azure Front Door). RemoteIP seems to set to the IP of the reverse-proxy deployed in front of istio gateway. (see diagram above: requests in green, configuration in blue)
```yaml
kind: AuthorizationPolicy
metadata:
  name: test-auth-policy
spec:
  action: ALLOW
  selector:
    matchLabels:
      app: test
  rules:
    - from:
        - source:
            remoteIpBlocks:
              - <clientIp>
```

Request from `<clientIp>` gets denied with the following entry in the logs:
```bash
2021-01-18T17:40:15.872025Z     debug   envoy rbac      checking request: requestedServerName: outbound_.80_._.test-service.test-ns.svc.cluster.local, sourceIP: <IstioIngressGatewayIp>:37834, directRemoteIP: <IstioIngressGatewayIp>:37834, remoteIP: <AzureFrontDoorIP>:0,localAddress: 10.240.2.152:8080, ssl: uriSanPeerCertificate: spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-public-service-account, dnsSanPeerCertificate: , subjectPeerCertificate: , headers: ':authority', 'test.example.com'
...
'x-forwarded-for', '<clientIp>,<AzureFrontDoorIP>'
...
'x-envoy-external-address', '<clientIp>'
...
'x-forwarded-client-cert', 'By=spiffe://cluster.local/ns/test-ns/sa/default;Hash=2a3d7357260f29961fd26f74bf7e9d637eaa9c23c4d735488f0541027b4c48ed;Subject="";URI=spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-public-service-account'
, dynamicMetadata: filter_metadata {
  key: "istio_authn"
  value {
    fields {
      key: "request.auth.principal"
      value {
        string_value: "cluster.local/ns/istio-system/sa/istio-ingressgateway-public-service-account"
      }
    }
    fields {
      key: "source.namespace"
      value {
        string_value: "istio-system"
      }
    }
    fields {
      key: "source.principal"
      value {
        string_value: "cluster.local/ns/istio-system/sa/istio-ingressgateway-public-service-account"
      }
    }
    fields {
      key: "source.user"
      value {
        string_value: "cluster.local/ns/istio-system/sa/istio-ingressgateway-public-service-account"
      }
    }
  }
}

2021-01-18T17:40:15.872065Z     debug   envoy rbac      enforced denied, matched policy none
```

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

`AuthorizationPolicy` allows requests from `<clientIp>`.

**Steps to reproduce the bug**
1. Install istio using `istioctl` and configure with:
    ```yaml
    ingressGateways:
      - enabled: false
        name: istio-ingressgateway
        k8s:
          replicaCount: 2
          podAnnotations:
            proxy.istio.io/config: '{"gatewayTopology" : { "numTrustedProxies": 1 } }'
          service:
            externalTrafficPolicy: Local
    ```
2. Create `AuthorizationPolicy`
    ```yaml
    kind: AuthorizationPolicy
    metadata:
      name: test-auth-policy
    spec:
      action: ALLOW
      selector:
        matchLabels:
          app: test
      rules:
        - from:
            - source:
                remoteIpBlocks:
                  - <clientIp>
    ```
3. Deploy a dummy service with the labels matching istio `AuthorizationPolicy`
4. Make a request from `<clientIp>` through a reverse proxy (or simulate with XFF header)
5. Observe the request beeing blocked, but should be allowed

**Version**

* `istioctl version --remote`
    ```bash
    client version: 1.8.2
    control plane version: 1.8.2
    data plane version: 1.8.2 (7 proxies)
    ```
* `kubectl version --short`
    ```bash
    Client Version: v1.18.15
    Server Version: v1.18.14
    ```

**How was Istio installed?**
`istioctl install -f install.yaml`
<details>
<summary>install.yaml</summary>

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  tag: 1.8.2-distroless
  meshConfig:
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
  components:
    cni:
      enabled: true
    ingressGateways:
      - enabled: false
        name: istio-ingressgateway
      - enabled: true
        name: istio-ingressgateway-public
        k8s:
          replicaCount: 2
          podAnnotations:
            proxy.istio.io/config: '{"gatewayTopology" : { "numTrustedProxies": 1 } }'
          serviceAnnotations:
            service.beta.kubernetes.io/azure-allowed-service-tags: AzureFrontDoor.Backend
          service:
            externalTrafficPolicy: Local
            loadBalancerIP: 51.145.104.39
            ports:
              - name: http2
                port: 80
                targetPort: 8080
              - name: https
                port: 443
                targetPort: 8443
          hpaSpec:
            maxReplicas: 5
            minReplicas: 2
          resources:
            limits:
              cpu: 650m
              memory: 400Mi
            requests:
              cpu: 100m
              memory: 400Mi
          overlays:
            - kind: HorizontalPodAutoscaler
              name: istio-ingressgateway-public
              patches:
                - path: metadata.labels.app
                  value: istio-ingressgateway-public
                - path: metadata.labels.istio
                  value: public-ingressgateway
                - path: spec.scaleTargetRef.name
                  value: istio-ingressgateway-public
            - kind: Deployment
              name: istio-ingressgateway-public
              patches:
                - path: metadata.labels.app
                  value: istio-ingressgateway-public  # Change the label to istio-ingressgateway-public
                - path: metadata.labels.istio
                  value: public-ingressgateway
                - path: spec.selector.matchLabels.app
                  value: istio-ingressgateway-public
                - path: spec.selector.matchLabels.istio
                  value: public-ingressgateway
                - path: spec.template.metadata.labels.app
                  value: istio-ingressgateway-public
                - path: spec.template.metadata.labels.istio
                  value: public-ingressgateway
                - path: spec.template.spec.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].labelSelector.matchExpressions[0].values[0]
                  value: istio-ingressgateway-public
            - kind: Service
              name: istio-ingressgateway-public
              patches:
                - path: metadata.labels.app
                  value: istio-ingressgateway-public
                - path: metadata.labels.istio
                  value: public-ingressgateway
                - path: spec.selector.app
                  value: istio-ingressgateway-public
                - path: spec.selector.istio
                  value: public-ingressgateway
            - kind: ServiceAccount
              name: istio-ingressgateway-public-service-account
              patches:
                - path: metadata.labels.app
                  value: istio-ingressgateway-public
                - path: metadata.labels.istio
                  value: public-ingressgateway
            - kind: PodDisruptionBudget
              name: istio-ingressgateway-public
              patches:
                - path: metadata.labels.app
                  value: istio-ingressgateway-public
                - path: metadata.labels.istio
                  value: public-ingressgateway
                - path: spec.selector.matchLabels.app
                  value: istio-ingressgateway-public
                - path: spec.selector.matchLabels.istio
                  value: public-ingressgateway
    pilot:
      k8s:
        replicaCount: 2
  values:
    global:
      defaultNodeSelector:
        beta.kubernetes.io/os: linux
      proxy:
        resources:
          limits:
            cpu: 500m
            memory: 400Mi
          requests:
            cpu: 10m
            memory: 80Mi
      proxy_init:
        resources:
          limits:
            cpu: 500m
            memory: 400Mi
          requests:
            cpu: 10m
            memory: 10Mi
    gateways:
      istio-ingressgateway:
        podAntiAffinityLabelSelector:
          - key: app
            operator: In
            values: istio-ingressgateway
            topologyKey: kubernetes.io/hostname
    cni:
      excludeNamespaces:
       - istio-system
       - kube-system
       - kube-public
       - kube-node-lease
    pilot:
      autoscaleMin: 2
```

</details>

**Environment where the bug was observed (cloud vendor, OS, etc)**
* Cloud: Azure AKS
* Networking: Azure (advanced)
* OS: `Ubuntu 18.04.5 LTS`
* Kernel: `5.4.0-1035-azure`
* Container Runtime: `docker://19.3.14`

**Comment by martinbaillie** [comment]
I have also just encountered this (and could not have summarised it better if I tried 👍🏻 ). This is exactly what I'm seeing too.

**Comment by yangminzhu** [comment]
Thanks for the very detailed report, that's a very clear description.

I haven't looked deep into this but just a quick check, have you tried setting the `numTrustedProxies` to the sidecar as well?

**Comment by kylebevans** [comment]
expanding on yangmin's answer, try this in your IstioOperator:

```
  values:
    sidecarInjectorWebhook:
      podAnnotations: 
        proxy.istio.io/config: '{"gatewayTopology" : { "numTrustedProxies": 1 } }'
```

I didn't test this, so you may need to fiddle with it.  The objective is for the output of this command:

`istioctl proxy-config listeners -o json -n $NAMESPACE $POD | grep xff`

to have this in it:

`"xffNumTrustedHops": 1,`


The normal way to do this would be to apply the `AuthorizationPolicy` on the ingress gateway, not on the service.

**Comment by anyname2** [comment]
I am pretty sure I tried it before submitting this issue, but I don't think the sidecar proxy picked up those annotations. It's only the gateway that does.

**Comment by kylebevans** [comment]
If that's the case, then you probably should either apply the `AuthorizationPolicy` to the ingress gateway itself, or you could use an `EnvoyFilter` to set `xffNumTrustedHops` to 1 on the sidecar.

**Comment by martinbaillie** [comment]
I gave a few things a try there but no joy unfortunately. It seems this stuff is perhaps codified to the gateways? I think the problem with selecting on the IGWs with an `AuthorizationPolicy` is multi-tenant platforms (like ours) tend to share gateways. Product engineering teams (the platform consumers) don't get permission to put stuff in the namespace that the IGWs reside.

-------
Quick dump of things tried:

1. Firstly, @yangminzhu's suggestion of hacking in the annotation at various levels (pod spec, deployment etc.) but didn't have any luck.

2. Then I tried to get the annotations in place with our mesh deployment (which is `istioctl`generation rather than in-cluster operator). I think the more modern Istio incantation here is something like (please correct me if wrong):
    ```
   values:
     sidecarInjectorWebhook:
       injectedAnnotations:
         proxy.istio.io/config: '{"gatewayTopology": { "numTrustedProxies": 1 } }'
    ```
    This unfortunately doesn't get accepted by our 1.8 `istiod`. It crash loops trying to parse the above from YAML to JSON. I tried a few variations but no luck. Perhaps someone else will have more joy.

3. The `EnvoyFilter` approach
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: mine
  namespace: myns
spec:
  workloadSelector:
    labels:
      app: mine
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
    patch:
      operation: MERGE
      value:
        typed_config:
          '@type': >-
            type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          xff_num_trusted_hops: 1
```
  This got me the furthest. The `istioctl listeners` objective outlined by @kylebevans is met, but still seems to have no effect, and RBAC debug logging still shows the wrong IP, unlike at the Gateway. Maybe my `EnvoyFilter` is not sliding in at the right spot?

**Comment by kylebevans** [comment]
If you run:
`istioctl proxy-config listeners -o json -n $NAMESPACE $POD | grep useRemoteAddress`

What do you see? I think it should be true.

**Comment by martinbaillie** [comment]
It's `false` by default[1] but I had also tried setting it to `true` on my filter (and also moved the filter to `applyTo: ANY`). No luck unfortunately. It feels like the issue is more around getting the Istio RBAC module to play ball given the `X-Envoy-External-Address` is correct.

[1] If I understand [the Envoy docs](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#config-http-conn-man-headers-x-forwarded-for) correctly then we'd want to keep it false for a sidecar proxy behind an edge proxy like the IGW (example 3+4).

**Comment by yangminzhu** [comment]
It looks like the annotation only work on gateway but not sidecar.

I tested the EnvoyFilter in https://github.com/istio/istio/issues/30166#issuecomment-796556188 by sending request with explicit `X-Forwarded-For` header and it is working for me (the `remoteIpBlocks` field matched to the IP that I specified in the XFF header).

The request:
```
curl http://35.224.231.58/headers -H "X-Forwarded-For: 1.2.3.4"
```

The sidecar log (note the `remoteIP` becomes to `1.2.3.4`):
```
2021-03-12T04:51:53.575650Z	debug	envoy rbac	checking request: requestedServerName: outbound_.8000_._.httpbin.default.svc.cluster.local, 
sourceIP: 10.44.3.12:44618, directRemoteIP: 10.44.3.12:44618, remoteIP: 1.2.3.4:0,localAddress: 10.44.3.11:80, 
ssl: uriSanPeerCertificate: spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account, 
dnsSanPeerCertificate: , subjectPeerCertificate: , 
headers: ':authority', '35.224.231.58'
':path', '/headers'
':method', 'GET'
':scheme', 'http'
'user-agent', 'curl/7.74.0'
'accept', '*/*'
'x-forwarded-for', '1.2.3.4,10.44.3.1'
'x-forwarded-proto', 'http'
'x-envoy-external-address', '1.2.3.4'
'x-request-id', 'd391142d-7eb0-9408-9aa4-b3a2135b1214'
...
```

Could you double check the XFF header and `remoteIp` content in your sidecar when the EnvoyFilter is enabled?

**Comment by kylebevans** [comment]
FYI, the X-Envoy-External-Address isn't calculated at the sidecar, and it is not what is used internally by RBAC.  It's calculated at the ingress gateway, and then the sidecars just pass it through among themselves.

**Comment by martinbaillie** [comment]
Sorry for the delay. @yangminzhu you're absolutely right. I double checked my test deployment and can confirm my `EnvoyFilter` from above does actually work. Our GitOps operator was wiping my changes.

Do we think this feature will ever be possible at the sidecar level in the same way it is at the gateway?

**Comment by anyname2** [comment]
Looks like the filter works indeed, however my requests through Azure Front Door are still getting blocked sometimes.
Azure Front Door can perform a number of hops before reaching Istio, each hop adds a new IP to the XFF, which means I can't use a statically configured number of trusted hops.

Would it be possible to introduce a setting to allow reading remoteIP from a configurable header: like `x-envoy-external-address` or `x-azure-socketip` (the latter is set by Azure Front Door)?

**Comment by kylebevans** [comment]
I'm not sure if/when that might be supported, but you can approximate it a couple ways:

I think an AuthorizationPolicy like this might work:

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: test-authz
spec:
 selector:
   matchLabels:
     app: test
 action: ALLOW
 rules:
 - when:
     - key: request.headers[x-azure-socketip]
       values: ["10.0.0*"]
```

That just supports basic wildcard matching right now I think, but full regex matching is on the horizon.  If you need a full regex, you could also use the VirtualService to filter the traffic with something like this:

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: testvs
  labels:
    app: test
spec:
  hosts:
  - test.example.com
  gateways:
  - testgateway.istio-system.svc.cluster.local
  http:
  - match:
    - headers:
        x-azure-socketip:
          regex: '^.*10.0.0.*'
    route:
    - destination:
        host: test
        port:
          number: 80
```

**Comment by rblaine95** [comment]
Hi there, can this issue potentially be re-opened?

We're experiencing a very similar issue (`Client -> AWS ALB -> IGW -> Sidecar -> Workload`) where `remoteIP` is the internal IP address of the AWS ALB, but not Client IP.

Istio version: `1.13.1`

Setting this Istio config:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    defaultConfig:
      gatewayTopology:
        numTrustedProxies: 1
```
Doesn't add the `"xffNumTrustedHops": 1,` proxy config, even though the sidecar logs the correct config:
```
2022-03-07T10:30:17.583866Z	info	Proxy role	ips=[10.98.106.92] type=sidecar id=workload-64d86cf69f-v4zdd.dev-fin domain=my-namespace.svc.cluster.local
2022-03-07T10:30:17.584049Z	info	Apply proxy config from env {"tracing":{"zipkin":{"address":"jaeger-collector.monitoring:9411"},"sampling":50},"gatewayTopology":{"numTrustedProxies":1}}

2022-03-07T10:30:17.590776Z	info	Effective config: binaryPath: /usr/local/bin/envoy
concurrency: 2
configPath: ./etc/istio/proxy
controlPlaneAuthPolicy: MUTUAL_TLS
discoveryAddress: istiod.istio-system.svc:15012
drainDuration: 45s
gatewayTopology:
  numTrustedProxies: 1
parentShutdownDuration: 60s
proxyAdminPort: 15000
serviceCluster: istio-proxy
statNameLength: 189
statusPort: 15020
terminationDrainDuration: 5s
tracing:
  sampling: 50
  zipkin:
    address: jaeger-collector.monitoring:9411
```

Adding the annotation to the pods `proxy.istio.io/config: '{"gatewayTopology" : { "numTrustedProxies": 1 } }'` also doesn't add the `xffNumTrustedHops` config when doing `istioctl proxy-config listeners -o json -n $NS $POD | grep xff`

Example logs from sidecar:
```2022-03-07T10:43:49.088539Z	debug	envoy rbac	checking request: requestedServerName: outbound_.80_._.workload.my-namespace.svc.cluster.local, sourceIP: 10.98.123.28:50092, directRemoteIP: 10.98.123.28:50092, remoteIP: 10.98.0.233:0,localAddress: 10.98.117.44:9000, ssl: uriSanPeerCertificate: spiffe://cluster.local/ns/istio-system/sa/external-igw-service-account, dnsSanPeerCertificate: , subjectPeerCertificate: , headers: ':authority', 'example.com'
':path', '/'
':method', 'GET'
':scheme', 'https'
'x-forwarded-for', 'IP.ADDR.REDA.CTED,10.98.0.233'
'x-forwarded-proto', 'https'
'x-forwarded-port', '443'
'x-amzn-trace-id', 'Root=1-6225e1e5-4fc1f546078bb09c2b5a52dc'
'cache-control', 'max-age=0'
'upgrade-insecure-requests', '1'
'sec-gpc', '1'
'sec-fetch-site', 'none'
'sec-fetch-mode', 'navigate'
'sec-fetch-user', '?1'
'sec-fetch-dest', 'document'
'accept-encoding', 'gzip, deflate, br'
'accept-language', 'en-US,en;q=0.9'
'x-envoy-external-address', '10.98.0.233'
'x-request-id', '1a66d03f-46c3-4e4c-a8d8-f9cb716740ef'
'x-envoy-peer-metadata', 'lotsamedatada'
'x-envoy-peer-metadata-id', 'router~10.98.123.28~external-igw-7c56b59464-rdmjc.istio-system~istio-system.svc.cluster.local'
'x-envoy-attempt-count', '1'
'x-b3-traceid', '688c118850d6cae85875fc467aae740f'
'x-b3-spanid', '5875fc467aae740f'
'x-b3-sampled', '0'
'x-envoy-original-path', '/some/workload/'
'x-forwarded-client-cert', 'By=spiffe://cluster.local/ns/my-namespace/sa/workload;Hash=e073a8f25aa7bce4353a81f080856b06bd2b2804bf549e50a15ff2b5ae19d4e7;Subject="";URI=spiffe://cluster.local/ns/istio-system/sa/external-igw-service-account'
, dynamicMetadata: filter_metadata {
  key: "istio_authn"
  value {
  }
}

2022-03-07T10:43:49.088560Z	debug	envoy rbac	enforced denied, matched policy none
2022-03-07T10:43:49.088569Z	debug	envoy http	[C275][S11657379050241880323] Sending local reply with details rbac_access_denied_matched_policy[none]
2022-03-07T10:43:49.088644Z	debug	envoy http	[C275][S11657379050241880323] encoding headers via codec (end_stream=false):
':status', '403'
'content-length', '19'
'content-type', 'text/plain'
'date', 'Mon, 07 Mar 2022 10:43:49 GMT'
'server', 'istio-envoy
```

After applying the EnvoyFilter detailed at https://github.com/istio/istio/issues/30166#issuecomment-796556188 that selects the workload pods, the `xffNumTrustedHops` config appears and the `remoteIP` is the correct Client IP:
```
2022-03-07T10:50:32.684214Z	debug	envoy rbac	checking request: requestedServerName: outbound_.80_._.workload.my-namespace.svc.cluster.local, sourceIP: 10.98.123.28:36346, directRemoteIP: 10.98.123.28:36346, remoteIP: IP.ADDR.REDA.CTED:0,localAddress: 10.98.117.44:9000, ssl: uriSanPeerCertificate: spiffe://cluster.local/ns/istio-system/sa/external-igw-service-account, dnsSanPeerCertificate: , subjectPeerCertificate: , headers: ':authority', 'example.com'
```

Side note: Also tried setting `gatewayTopology.numTrustedProxies` to higher values like `2` and `5` with no luck.

If my understanding of the documentation is correct, this appears to be a bug of some kind?

**Comment by anannaya** [comment]
@rblaine95  Did you fix it ? i set numTrustedProxies  to 1 at sidecar and mesh layer.  I see source and remote ip from envoy lof it VPC ip addresses not the remote ip. 

```
example-chart.pf.svc.cluster.local, sourceIP: 10.6.170.223:41714, directRemoteIP: 10.6.170.223:41714, remoteIP: 10.6.177.112:0,localAddress: 10.6.144.6:9080, ssl: uriSa

**Comment by rblaine95** [comment]
@anannaya I applied the following EnvoyProxy config to the `istio-system` namespace:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: fix-xff
  namespace: istio-system
spec:
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": >-
              type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            xff_num_trusted_hops: 1
```
We also have to use a Virtual Service (ALB -> Istio IGW -> Virtual Service -> Workload) to route traffic rather than Nginx Ingress (ALB -> Nginx Controller -> Workload) to get the correct IPs to show up and AuthZ to work correctly.

If using Nginx Ingress (ALB -> Nginx -> Workload) then the sidecar gets the Nginx pod IP even though the `x-forwarded-for` header contains the client IP.

**Comment by anannaya** [comment]
@rblaine95  No it didn't work for me.
Yes. my configuration also same  as AWS ALB -> Istio IGW -> Virtual Service -> Workload.

I did set  below  at mesh 
```
  meshConfig:
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    defaultConfig:
      gatewayTopology:
        numTrustedProxies: 2
        
        
Also annotation at the sidecar
```
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2022-04-26T12:16:45+05:30"
        proxy.istio.io/config: '{"gatewayTopology" : { "numTrustedProxies": 1 } }'

**Comment by rblaine95** [comment]
@anannaya 
On our side we don't have anything set on the pod and it worked.
Just the same default gateway mesh config as you and the envoy filter posted above

**Comment by anannaya** [comment]
@rblaine95  Below one worked for me
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: example-chart-policy
  namespace: pf
spec:
  action: ALLOW
  rules:
  - when:
    - key: request.headers[x-forwarded-for]
      values:
      - "xxx.39.121.86*"
      - "xx.206.173.192*"
      - "xxx.236.215.30*"
      - "xx.198.12.81*"
  selector:
    matchLabels:
      app: example-chart

**Comment by jingslunt** [comment]
> 看起来过滤器确实有效，但是我通过 Azure Front Door 的请求有时仍会被阻止。 Azure Front Door 可以在到达 Istio 之前执行多个跃点，每个跃点都会向 XFF 添加一个新 IP，这意味着我不能使用静态配置的受信任跃点数量。
> 
> 是否可以引入一个设置以允许从可配置的标头读取 remoteIP：like`x-envoy-external-address`或`x-azure-socketip`（后者由 Azure Front Door 设置）？

https://istio.io/latest/docs/ops/configuration/traffic-management/network-topologies/
> if you have a cloud based Load Balancer and a reverse proxy in front of your Istio gateway, set numTrustedProxies to 2

**Comment by anannaya** [comment]
@jingslunt  I have tried with 1 and 2 as well.  Not worked for me.

**Comment by pokidov** [comment]
@anannaya Same one issue with Client -> AWS ALB -> IGW -> Sidecar -> Workload, RBAC blocking.

**Comment by anannaya** [comment]
@pokidov Below configuration at sidecar worked , I have some which routed via ALB So i preferred to apply at the app layer, If you have a all the apps goes via ALB then create Envoyfilter in istio-system namespace.
`
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: xff-envoyfilter-alb-<APPNAME>
  namespace: <NAMESPACE>
spec:
  workloadSelector:
    labels:
      app: <APP LABEL>
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": >-
              type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            xff_num_trusted_hops: 2
`

**Comment by h0x91b-wix** [comment]
```xff_num_trusted_hops: 2``` - 2 is a magic number, works fine for me, thanks!

**Comment by nbourikas** [comment]
> - key: request.headers[x-forwarded-for]
>       values:
>       - "xxx.39.121.86*"
>       - "xx.206.173.192*"
>       - "xxx.236.215.30*"
>       - "xx.198.12.81*"

Inspired by this, I tried the following, which worked perfectly:

`apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: my-service-allow-list
  namespace: my-namespace
spec:
  action: ALLOW
  rules:
  - when:
    - key: request.headers[x-envoy-external-address]
      values:
      - 1.2.3.4
      - 1.2.3.5
  selector:
    matchLabels:
      app: my-service`

The only other required change was adding the following annotation to the pod spec of my `istio-ingressgateway` deployment, following the instructions from [the documentation](https://istio.io/latest/docs/ops/configuration/traffic-management/network-topologies/#configuring-x-forwarded-for-headers):

`proxy.istio.io/config: '{"gatewayTopology" : { "numTrustedProxies": 1 } }'`

`numTrustedProxies` is set to 1 because:
- I have a single reverse proxy upstream of my Istio ingress gateway.
- My cloud load balancer is TCP, not HTTPS, and has no ability to interact with layer 7 headers.

Prior to getting this to work, I tried every conceivable configuration of the `from` and `to` fields with no success.

Hope this helps someone.

**Comment by Jonnymcc** [comment]
@nbourikas's solution is almost ideal. When matching IPs to the header `x-envoy-external-address` it only works with specific IPs and not CIDR blocks right? 

We are currently using the envoyfilter mentioned above but it feels hacky. I understand from the Istio docs that `remoteIpBlocks` uses the `x-forwarded-for` header to determine the remote address. This works at the ingress gateway but not at Envoy sidecars attached to services. 

Wouldn't it make sense for `remoteIpBlocks` to instead use  `x-envoy-external-address`? That shouldn't affect behavior at the ingress gateway and authorization policies applied outside of the root namespace would work as expected without needing to apply the envoy filter. Am I right?

**Comment by philipp1992** [comment]
after spending hours of debugging 

> @nbourikas's solution is almost ideal. When matching IPs to the header `x-envoy-external-address` it only works with specific IPs and not CIDR blocks right?
> 
> We are currently using the envoyfilter mentioned above but it feels hacky. I understand from the Istio docs that `remoteIpBlocks` uses the `x-forwarded-for` header to determine the remote address. This works at the ingress gateway but not at Envoy sidecars attached to services.
> 
> Wouldn't it make sense for `remoteIpBlocks` to instead use `x-envoy-external-address`? That shouldn't affect behavior at the ingress gateway and authorization policies applied outside of the root namespace would work as expected without needing to apply the envoy filter. Am I right?

we have spent hours to also debug this issue and came to the exact same conclusion. works on IGW but doesnt work on the sidecar. 
Please fix this.

**Comment by AleksanderBrzozowski** [comment]
@philipp1992 Are you sure that this doesn't work? We have successfully set up a policy that restricts traffic only from a certain IP address. This policy was applied to the application sidecar. However, we set the number of trusted proxies to 0 at the ingress gateway level, as we use AWS NLB.

**Comment by wesbrownfavor** [comment]
I'm also having issues.  I was not able to get the EnvoyFilter example to work with a remoteIpBlocks setup.

I am able to get the requests.headers example to work but the security implications of that are a bit unsettling.

Lets say you did the following:
```
when:
        - key: 'request.headers[X-Forwarded-For]'
          values:
            - 123.123.123.10*
``` 

Then the IPs 
```
123.123.123.101
123.123.123.102
123.123.123.103
...
123.123.123.109
```
also have access.

Also if you wanted to allow a block of IPs you'd have to specify them all 1 by 1 or be hacky with wildcards.

**Comment by jaroslawksiezuk** [comment]
I'm bumping this topic, unfortunately it still doesn't work properly at least for me.

The exact thing is that the `remoteIpBlocks` attribute is not working correctly it seems that the value is not a real Client IP but IP of the first proxy.

```
- from:
    - source:
        remoteIpBlocks:
        - 123.123.123.123/30
```


Of course it is still possible to check the IP using headers but there is no CIDR support what is problematic I think.

```
when:
    - key: request.headers[x-forwarded-for]
      values:
       - 123.123.123.120
       - 123.123.123.121
       - 123.123.123.122
       - 123.123.123.123
```

or

```
when:
    - key: request.headers[x-envoy-external-address]
      values:
       - 123.123.123.120
       - 123.123.123.121
       - 123.123.123.122
       - 123.123.123.123
```

**Comment by bidyuthota** [comment]
Has anyone got this to work when applying policies specific to the Envoy sidecar( application namespace specific) incase they use a common NLB and dont want to filter on the ingress gateway. We are also trying to achieve defining CIDR blocks instead of individual IP's hence wanted to see if remoteIPblock clause can be successfully used . Would appreciate any feedback.

**Comment by YvesEarnix** [comment]
@bidyuthota 


Workaround validated with Istio 1.26.2 (without ambient mode).

1. Set numTrustedProxies on the Gateway
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  tag: 1.26.2
  meshConfig:
    defaultConfig:
      gatewayTopology:
        numTrustedProxies: 1 
```

2. On a EnvoyFilter, **overwrite the 'X-Forwarded-For' header** with the **X-Envoy-External-Address**
```
##
# See https://github.com/istio/istio/issues/30166
##
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: fix-x-forwarded-for
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
      patch:
        operation: INSERT_BEFORE
        value:
          name: sanitize-x-forwarded.lua
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
            inlineCode: |
              function envoy_on_request(request_handle)
                 local headers = request_handle:headers()
                 local host = headers:get("host")
                 local client_id = headers:get("X-Envoy-External-Address")
                 headers:replace("x-forwarded-for", client_id)
              end

```
3. Policy should work as expected

```
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces:
        - istio-system
        remoteIpBlocks:
         - 1.1.1.1/24
 ```
