### ISSUE TITLE
Unable to access external services when ISTIO_META_DNS_CAPTURE is set, either to true or false.

### ISSUE THREAD

**Issue by iris-garcia** [istio/istio#30177]
**Bug description**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[x] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
External services should be accessible after a ServiceEntry is created for them.
**Steps to reproduce the bug**
- istioctl install -f values.yaml
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  meshConfig:
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
    defaultConfig:
      proxyMetadata:
        # Enable Istio agent to handle DNS requests for known hosts
        # Unknown hosts will automatically be resolved using upstream dns servers in resolv.conf
        ISTIO_META_DNS_CAPTURE: "false"
```
- Create a service entry: `kubectl apply -f se.yaml`
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google
spec:
  hosts:
  - www.google.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
```
- Using the sleep pod (the one recommended in Istio documentation) run:
```sh
curl -sI https://www.google.com
```
**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
`istioctl version --remote`
```
client version: 1.8.2
control plane version: 1.8.2
data plane version: 1.8.2 (6 proxies)
```
`kubectl version --short`
```
Client Version: v1.19.4
Server Version: v1.18.14+IKS
```

**Environment where the bug was observed (cloud vendor, OS, etc)**
IKS (IBM cloud)

**Extra**
It does not matter the value of `ISTIO_META_DNS_CAPTURE`, it fails with either `false` or `true`.

The only way I have found to fix the issue is to edit the kubernetes resource: `istiooperator installed-state` and then remove completely this attribute:
- **Before**
```yaml
...
  meshConfig:
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "false"
...
```
- **After**
```yaml
  meshConfig:
    defaultConfig:
      proxyMetadata: {}
```
