### ISSUE TITLE
Is it possible to set the VirtualService/subsets in a SemVer format?

### ISSUE THREAD

**Issue by LozanoMatheus** [istio/istio#30188]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

I'm trying to use SemVer on VirtualService.spec.http.route.destination.subset. Is it possible to use SemVer (e.g.: 1.0.1) on `subset`?

**Affected product area (please put an X in all that apply)**

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane
[x] Virtual Service

**Expected behavior**

**Steps to reproduce the bug**

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-app
spec:
  hosts:
  - test-app.default.svc.cluster.local
  http:
  - name: "test-app-v1-route"
    route:
    - destination:
        host: test-app.default.svc.cluster.local
        subset: '1.0' # I tried with 1.0.2, "1.0"...
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```text
$ istioctl version --remote
client version: 1.8.2
control plane version: 1.8.2
data plane version: 1.8.2 (110 proxies)

$ kubectl version --short
Client Version: v1.17.13
Server Version: v1.17.12-eks-7684af

$ helm version --short
Client: v2.17.0+ga690bad
Server: v2.17.0+ga690bad
```

**How was Istio installed?**
Via Helm

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
