### ISSUE TITLE
HPA's scale target reference is incorrect when helm values for hpa is specified in the IOP

### ISSUE THREAD

**Issue by morvencao** [istio/istio#30203]
**Bug description**

Install istio with IOP spec in which helm values for hpa is specified explicitly, then the HPA's scale target reference is incorrect, no revision is added.
```
$ cat << EOF | istioctl install -y --set revision=canary -f -
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    pilot:
      cpu:
        targetAverageUtilization: 80
EOF
```

Then check the HPA(`istiod-canary`):
```
$ kubectl -n istio-system get hpa
NAME            REFERENCE           TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
istiod-canary   Deployment/istiod   <unknown>/80%   1         5         0          8
```

```
$ kubectl -n istio-system get hpa istiod-canary -o yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  ...
  name: istiod-canary
  namespace: istio-system
  ...
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istiod
  targetCPUUtilizationPercentage: 80
status:
  currentReplicas: 0
  desiredReplicas: 0
```

The workaround is using k8s setting for the HPA spec instead of helm values:
```
cat << EOF | istioctl install -y --set revision=canary -f -
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    pilot:
      k8s:
        hpaSpec:
          maxReplicas: 5
          minReplicas: 1
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: istiod-canary
          metrics:
            - type: Resource
              resource:
                name: cpu
                targetAverageUtilization: 80
EOF
```

**Affected product area (please put an X in all that apply)**

[ X ] Installation
