### ISSUE TITLE
Wasm StopIteration in OnHttpRequestHeaders causes filter to hang, even if there is a body (1.8+)

### ISSUE THREAD

**Issue by wouterposdijk** [istio/istio#30213]
**Bug description**
Since istio 1.8, stopping iteration of headers in a WASM filter causes the filter to hang indefinitely. OnHttpRequestBody is never triggered.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
When stopping header iteration in a WASM filter in OnHttpRequestHeaders, OnHttpRequestBody should be triggered if there is a body.
As per https://github.com/istio/envoy/blob/81b7bb3eb044842e6caaf02a46d01a50a83743f4/source/extensions/common/wasm/context.cc line 1339, and https://github.com/istio/envoy/blob/81b7bb3eb044842e6caaf02a46d01a50a83743f4/include/envoy/http/filter.h, line 28, StopIteration means the following;

```
// Do not iterate to any of the remaining filters in the chain. Returning
// FilterDataStatus::Continue from decodeData()/encodeData() or calling
// continueDecoding()/continueEncoding() MUST be called if continued filter iteration is desired.
```

Note that this explicitly mentions the possibility of continuing from decodeData() (which is mapped to OnHttpRequestBody in wasm filters).

**Steps to reproduce the bug**
Compile the following filter:

`filter.go`
```go
package main

import (
	"github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm"
	"github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/types"
	"strings"
)

func main() {
	proxywasm.SetNewHttpContext(newHeaderChangingContext)
}

type headerChangingContext struct {
	proxywasm.DefaultHttpContext
}

func newHeaderChangingContext(rootContextID, contextID uint32) proxywasm.HttpContext {
	return &headerChangingContext{}
}

func (ctx *headerChangingContext) OnHttpRequestBody(bodySize int, endOfStream bool) types.Action {
	proxywasm.LogDebug("OnHttpRequestBody")

	if endOfStream {
		// After processing the body, we want to set a header (usually content-length)
		err := proxywasm.SetHttpRequestHeader("some-header", "some-value")
		if err != nil {
			proxywasm.LogError("failed to set some-header")
			proxywasm.SendHttpResponse(500, [][2]string{}, "internal server error")
		}
		return types.ActionContinue // = 0
	}

	return types.ActionPause // = 1, we need to buffer the body first
}

func (ctx *headerChangingContext) OnHttpRequestHeaders(headers int, completed bool) types.Action {
	proxywasm.LogDebug("OnHttpRequestHeaders")

	method, _ := proxywasm.GetHttpRequestHeader(":method")
	if strings.ToUpper(method) != "POST" {
		return types.ActionContinue // = 0
	}

	return types.ActionPause // = 1, equiv. to StopIteration, we need to receive the body first to change a header based on it
}
```
with go.mod
```
module filterbugreproduction.com/filter

go 1.15

require github.com/tetratelabs/proxy-wasm-go-sdk v0.0.14
```

using e.g.:
```
docker run --rm -it -w /build \
-v ${PWD}:/build  \
tinygo/tinygo:0.16.0 \
tinygo build -o /build/bin/filter.wasm -target=wasi \
-wasm-abi=generic ./...
```

Create a configmap from said filter:
```
kubectl create cm wasm-filter --from-file=bin/filter.wasm
```

apply the following to create a service httpbin that uses the filter:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
    service: httpbin
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        wasm_filter: enabled
        version: v1
      annotations:
        sidecar.istio.io/userVolume: '[{"name":"wasmfilter-dir","configMap": {"name": "wasm-filter"}}]'
        sidecar.istio.io/userVolumeMount: '[{"mountPath":"/var/local/lib/wasm-filter","name":"wasmfilter-dir"}]'
    spec:
      serviceAccountName: httpbin
      containers:
        - image: docker.io/kennethreitz/httpbin
          imagePullPolicy: IfNotPresent
          name: httpbin
          ports:
            - containerPort: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: wasm-headerreplacer
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          portNumber: 80
          filterChain:
            filter:
              name: envoy.http_connection_manager
              subFilter:
                name: "envoy.router"
        proxy:
          proxyVersion: ^1\.*.*
      patch:
        operation: INSERT_BEFORE
        value:
          name: headerreplacer_filter
          typed_config:
            '@type': type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
            value:
              config:
                configuration:
                  '@type': type.googleapis.com/google.protobuf.StringValue
                  value: ""
                root_id: headerreplacer_root_id
                vm_config:
                  code:
                    local:
                      filename: /var/local/lib/wasm-filter/filter.wasm
                  runtime: envoy.wasm.runtime.v8
                  vm_id: headerreplacer_filter
  workloadSelector:
    labels:
      wasm_filter: enabled
```

To reproduce the bug, call:
`curl -X POST [SERVICE_DNS_OR_IP] -H 'Content-Type: text/plain' -d 'something'`

This will hang indefinitely. Upon inspecting the wasm debug logs of the proxy you should see that OnHttpRequestBody is never logged.

This bug occurs when using istio 1.8.2, but not when using istio 1.7.6.

Please let me know if you need any additional information, I'll be happy to supply it.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
istio:
client version: 1.8.2
control plane version: 1.8.2
data plane version: 1.8.2 (2 proxies)

kubernetes:
Client Version: v1.20.2
Server Version: v1.18.15
```

**How was Istio installed?**
`istioctl install`, with a tiny bit of company-specific configuration regarding ingress.

**Environment where the bug was observed (cloud vendor, OS, etc)**
microk8s cluster

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
