### ISSUE TITLE
Envoy external auth filter not working

### ISSUE THREAD

**Issue by nchardon-perso** [istio/istio#30271]
**Bug description**
Hello,
I'm trying to use an envoy filter to perform an external authentication but it's not working and I can't figure out why.

This is the envoy filter I'm using (I've simplified the header list). The filter is applied in the same namespace as my pod in `sma-app-kind`, but I've also tried in `istio-system` namespace.

The problem is that the filter seems to be completely ignored and the authentication is not performed.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: auth-filter
spec:
  workloadSelector:
    labels:
      com.myapp/secured: enabled
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          portNumber: 8080
          filterChain:
            filter:
              name: 'envoy.http_connection_manager'
              subFilter:
                name: 'envoy.router'
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.ext_authz
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
            httpService:
              authorizationRequest:
                allowedHeaders:
                  patterns:
                    - exact: authorization
                    - exact: x-custom-header1
                    - exact: x-custom-header2
              authorizationResponse:
                allowedUpstreamHeaders:
                  patterns:
                    - exact: x-user-info
              serverUri:
                cluster: outbound|8080||sma-authentication-service.sma-app-kind.svc.cluster.local
                timeout: 120s
                uri: http://sma-authentication-service.sma-app-kind.svc.cluster.local:8080/authentication/login
            statusOnError:
              code: Forbidden
```

My auth service 
```
k -n sma-app-kind get svc
NAME                         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
sma-authentication-service   ClusterIP   10.108.79.29     <none>        8080/TCP   47h
...
```

One configured pod that should implement the auth logic
```
k -n sma-app-kind get pod --show-labels 
sma-referentiel-69769757b-26djg      2/2     Running   0          27m    app.kubernetes.io/component=application-referentiel,app.kubernetes.io/managed-by=XXX,app.kubernetes.io/name=smart-access,com.myapp/secured=enabled,istio.io/rev=default,pod-template-hash=69769757b,security.istio.io/tlsMode=istio,service.istio.io/canonical-name=smart-access,service.istio.io/canonical-revision=latest
```

When logging the istiod pod i can see that the filter is picked up and pushed in my pods 
```
CDS: PUSH for node:sma-tpv-fdbc984cb-lvrh6.sma-app-kind resources:33
CDS: PUSH for node:sma-mock-service-69699f495b-v6fmt.sma-app-kind resources:33
....
```

Envoy config_dump extract

```
    {
     "version_info": "2021-01-21T15:58:01Z/23",
     "cluster": {
      "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
      "name": "outbound|8080||sma-authentication-service.sma-app-kind.svc.cluster.local",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {},
        "resource_api_version": "V3"
       },
       "service_name": "outbound|8080||sma-authentication-service.sma-app-kind.svc.cluster.local"
      },
      "connect_timeout": "10s",
      "circuit_breakers": {
       "thresholds": [
        {
         "max_connections": 4294967295,
         "max_pending_requests": 4294967295,
         "max_requests": 4294967295,
         "max_retries": 4294967295
        }
       ]
      },
      "metadata": {
       "filter_metadata": {
        "istio": {
         "default_original_port": 8080,
         "services": [
          {
           "name": "sma-authentication-service",
           "namespace": "sma-app-kind",
           "host": "sma-authentication-service.sma-app-kind.svc.cluster.local"
          }
         ]
        }
       }
      },
      "filters": [
       {
        "name": "istio.metadata_exchange",
        "typed_config": {
         "@type": "type.googleapis.com/udpa.type.v1.TypedStruct",
         "type_url": "type.googleapis.com/envoy.tcp.metadataexchange.config.MetadataExchange",
         "value": {
          "protocol": "istio-peer-exchange"
         }
        }
       }
      ],
      "transport_socket_matches": [
       {
        "name": "tlsMode-istio",
        "match": {
         "tlsMode": "istio"
        },
        "transport_socket": {
         "name": "envoy.transport_sockets.tls",
         "typed_config": {
          "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext",
          "common_tls_context": {
           "alpn_protocols": [
            "istio-peer-exchange",
            "istio"
           ],
           "tls_certificate_sds_secret_configs": [
            {
             "name": "default",
             "sds_config": {
              "api_config_source": {
               "api_type": "GRPC",
               "grpc_services": [
                {
                 "envoy_grpc": {
                  "cluster_name": "sds-grpc"
                 }
                }
               ],
               "transport_api_version": "V3"
              },
              "initial_fetch_timeout": "0s",
              "resource_api_version": "V3"
             }
            }
           ],
           "combined_validation_context": {
            "default_validation_context": {},
            "validation_context_sds_secret_config": {
             "name": "ROOTCA",
             "sds_config": {
              "api_config_source": {
               "api_type": "GRPC",
               "grpc_services": [
                {
                 "envoy_grpc": {
                  "cluster_name": "sds-grpc"
                 }
                }
               ],
               "transport_api_version": "V3"
              },
              "initial_fetch_timeout": "0s",
              "resource_api_version": "V3"
             }
            }
           }
          },
          "sni": "outbound_.8080_._.sma-authentication-service.sma-app-kind.svc.cluster.local"
         }
        }
       },
       {
        "name": "tlsMode-disabled",
        "match": {},
        "transport_socket": {
         "name": "envoy.transport_sockets.raw_buffer"
        }
       }
      ]
     },

...

{
              "name": "envoy.ext_authz",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz",
               "http_service": {
                "server_uri": {
                 "uri": "http://sma-authentication-service.sma-app-kind.svc.cluster.local:8080/authentication/login",
                 "cluster": "outbound|8080||sma-authentication-service.sma-app-kind.svc.cluster.local",
                 "timeout": "120s"
                },
                "authorization_request": {
                 "allowed_headers": {
                  "patterns": [
                   {
                    "exact": "authorization"
                   },
                   {
                    "exact": "cookie"
                   },
                   {
                    "exact": "x-custom-header1"
                   },
                   {
                    "exact": "x-custom-header2"
                   }
                  ]
                 }
                },
                "authorization_response": {
                 "allowed_upstream_headers": {
                  "patterns": [
                   {
                    "exact": "x-user-info"
                   }
                  ]
                 }
                }
               },
               "status_on_error": {
                "code": "Forbidden"
               }
              }
             },
```

[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
kubectl version --short
Client Version: v1.18.6
Server Version: v1.18.2

istioctl version --short
client version: 1.8.0
control plane version: 1.8.0
data plane version: 1.8.0 (6 proxies)
```

**How was Istio installed?**

With `istioctl install --manifests=manifests/` 

Extract of my custom manifest for the default profile. I've just set the ingress gateway service to NodePort and set HTTP and HTTPS ports to 32080 and 32443 respectively

```
    # Istio Gateway feature
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        env:
          - name: ISTIO_META_ROUTER_MODE
            value: "standard"
        service:
          ports:
            - port: 15021
              targetPort: 15021
              name: status-port
              protocol: TCP
            - port: 80
              nodePort: 32080
              targetPort: 8080
              name: http2
              protocol: TCP
            - port: 443
              nodePort: 32443
              targetPort: 8443
              name: https
              protocol: TCP
            - port: 15012
              targetPort: 15012
              name: tcp-istiod
              protocol: TCP
            - port: 15443
              targetPort: 15443
              name: tls
              protocol: TCP
...

```

**Environment where the bug was observed (cloud vendor, OS, etc)**

I've tried it with Kubernetes in Kind and in a private Kubernetes cluster (1 master 3 workers)

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by SpecialYang** [comment]
Please try this.
```
 filterChain:
    filter:
      name: envoy.filters.network.http_connection_manager
      subFilter:
        name: envoy.filters.http.router
```

**Comment by nchardon-perso** [comment]
Unfortunately, it does not change anything. The configuration is applied correctly on the istio sidecar, but nothing happens

**Comment by incfly** [comment]
There are some issues about using `|` in the cluster name of the external authz config. (an invalid character of the gRPC encoding).

But we have introduced new ext_authz feature in upcoming release.  You can see this https://preliminary.istio.io/latest/docs/tasks/security/authorization/authz-custom/ for more information.

/cc @yangminzhu for potential use case.

**Comment by sbgreene1307** [comment]
In order to use the envoyfilter resource, @incfly is correct that the `|` is a problem. To get it working you need to patch the CLUSTER service's name.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: auth-filter
spec:
  workloadSelector:
    labels:
      com.myapp/secured: enabled
  configPatches:
    - applyTo: CLUSTER
      match:
        cluster:
          service: sma-authentication-service.sma-app-kind.svc.cluster.local
      patch:
        operation: MERGE
        value:
          name: patched.sma-authentication-service.sma-app-kind.svc.cluster.local
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          portNumber: 8080
          filterChain:
            filter:
              name: 'envoy.http_connection_manager'
              subFilter:
                name: 'envoy.router'
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.ext_authz
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
            httpService:
              authorizationRequest:
                allowedHeaders:
                  patterns:
                    - exact: authorization
                    - exact: x-custom-header1
                    - exact: x-custom-header2
              authorizationResponse:
                allowedUpstreamHeaders:
                  patterns:
                    - exact: x-user-info
              serverUri:
                cluster: patched.sma-authentication-service.sma-app-kind.svc.cluster.local
                timeout: 120s
                uri: http://sma-authentication-service.sma-app-kind.svc.cluster.local:8080/authentication/login
            statusOnError:
              code: Forbidden
```

We also just found out that istio or envoy isn't honoring the path in the serverUri.uri. The istio proxy will always issue a request to the base path only.
