### ISSUE TITLE
Multiple VIPs on Service entry does not work for DNS

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30282]
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: dns
spec:
  hosts:
  - "fake.service.local"
  addresses:
  - 1.2.3.4
  - 1.2.3.6
  resolution: STATIC
  endpoints:
  - address: 1.2.3.5
  ports:
  - number: 80
    name: http
    protocol: HTTP
```

This does not work for DNS, we just return a single one. Need to investigate what happens with listener configs.
