### ISSUE TITLE
multicluster meshconfig gateways address does not resolve DNS name

### ISSUE THREAD

**Issue by samene** [istio/istio#30345]
We have a Primary-Primary MultiCluster deployment model.

According to documentation [Here](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#Network-IstioNetworkGateway) The Network.IstioNetworkGateway.address is a 

```
IP address or externally resolvable DNS address associated with the gateway.
```

But the address field only works with an IP address and not a DNS name. When we use a DNS name, we see the following in the istiod logs,

```
2021-01-21T11:59:20.727565Z     warn    failed to read mesh networks configuration from "/etc/istio/config/meshNetworks": 2 errors occurred:
        * invalid network my-network1: ab319a653587exxxxbda9786997d04d4-159xxx6485.us-east-1.elb.amazonaws.com is not a valid IP
        * invalid network my-network2: a7e9834b82342xxxxb15a7f339b08745-917x35xx4.us-east-1.elb.amazonaws.com is not a valid IP
```

Snippet of the IstioOperator

```
      # Mesh network configuration. This is optional and may be omitted if
      # all clusters are on the same network.
      meshNetworks:
       my-network1:
         endpoints:
           - fromRegistry: cluster1
         gateways:
           - address: ab319a653587exxxxbda9786997d04d4-159xxx6485.us-east-1.elb.amazonaws.com
             port: 15443

       my-network2:
         endpoints:
           - fromRegistry: cluster2
         gateways:
           - address: a7e9834b82342xxxxb15a7f339b08745-917x35xx4.us-east-1.elb.amazonaws.com
             port: 15443
```

This is same as https://github.com/istio/istio/issues/25512

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

istioctl version
client version: 1.8.0
control plane version: 1.8.1
data plane version: 1.8.1 (1 proxies)

kubectl version
Client Version: v1.18.12
Server Version: v1.18.10

How was Istio installed?
IstioOperator
