### ISSUE TITLE
PILOT_SKIP_VALIDATE_TRUST_DOMAIN not working on Istio 1.8?

### ISSUE THREAD

**Issue by g-lam** [istio/istio#30349]
**Bug description**
We created a mesh with 2 clusters in Multi-Primary setup. Everything is working when the trust domain is the same, or if we add the trust domain to the other cluster's trustDomainAlias. However our desire is to maintain the independent trust domains for authorization purpose. Prior to 1.8, we set PILOT_SKIP_VALIDATE_TRUST_DOMAIN to true. However, setting it in 1.8 doesn't seem to have any effect. We confirmed the env was indeed present in the istiod deployment.

When we call services in the other cluster, we are getting CERTIFICATE_VERIFY_FAILED. We tested on 1.8.0, 1.8.1 and 1.8.2 and the behavior is the same.

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Setting PILOT_SKIP_VALIDATE_TRUST_DOMAIN to true, or via some other mechanism to allow clusters of different trust domains to communicate with each other.

**Steps to reproduce the bug**
Install Istio on two clusters using the below config, setting meshConfig.trustDomain to cluster1 and cluster2, respectively
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-operator
spec:
  profile: default
  components:
    pilot:
      k8s:
        env:
          - name: PILOT_SKIP_VALIDATE_TRUST_DOMAIN
            value: "true"
  values:
    global:
      multiCluster:
        enabled: true
    sidecarInjectorWebhook:
      rewriteAppHTTPProbe: true
```
Create multi-cluster mesh using instructions from https://istio.io/latest/docs/setup/install/multicluster/multi-primary/ to setup multi-cluster mesh. Verification (https://istio.io/latest/docs/setup/install/multicluster/verify/) would fail.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
istioctl version
```
client version: 1.8.2
control plane version: 1.8.2
data plane version: 1.8.2 (3 proxies)
```

kubectl version
```
Client Version: v1.20.2
Server Version: v1.17.14-gke.400
```

**How was Istio installed?**
istioctl install

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
cc @incfly @yangminzhu

**Comment by incfly** [comment]
What makes you think it's `PILOT_SKIP_VALIDATE_TRUST_DOMAIN` not working?  `CERTIFICATE_VERIFY_FAILED` could be something else like root certificate in different clustes are different right? Have you done some `openssl verify` for the caller's workload certificate against the target service's cluster root?

**Comment by yangminzhu** [comment]
As @incfly mentioned, PILOT_SKIP_VALIDATE_TRUST_DOMAIN only controls the server side checking (the `match_subject_alt_names` in the validation_context in Envoy). I just checked 1.8.2 and the flag is working as expected.

**Comment by g-lam** [comment]
Thanks @incfly for validating the scenarios. We are currently using case 4 in Istio 1.6 without issues (also confirmed to work in 1.7). Here is an example:
We are granting `sleep` in trust domain `foo` access to `helloworld` in trust domain `bar`, both services run in the namespace `baz`. We grant access to `helloworld` from the source principal of `foo/ns/baz/sa/sleep-sa`. However, we don't want `sleep` in trust domain `bar`, namespace `baz`, to access `helloworld`.

If I start adding `foo` and `bar` to each other's trustDomainAliases, it equates `bar/ns/baz/sa/sleep-sa` to `foo/ns/baz/sa/sleep-sa` and therefore compromises my access control.

In 1.6, somehow we are able to leverage `PILOT_SKIP_VALIDATE_TRUST_DOMAIN` to make `foo` and `bar` workloads recognize each other. May be we are abusing that flag 😛 Please let us know if this could be done in other ways. Ideally, I want to find a way to tell `foo` and `bar` that they can trust each other, but not regard each other equally.

Once again, thank you so much for all your efforts and I am really excited to see the new simplified way in setting up multi-cluster meshes!

**Comment by yangminzhu** [comment]
> In 1.6, somehow we are able to leverage PILOT_SKIP_VALIDATE_TRUST_DOMAIN to make foo and bar workloads recognize each other. May be we are abusing that flag stuck_out_tongue Please let us know if this could be done in other ways. Ideally, I want to find a way to tell foo and bar that they can trust each other, but not regard each other equally.

One workaround is to use the authorization policy like the following:

```yaml
apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
  name: "helloworld"
  namespace: baz
spec:
  selector:
    matchLabels:
      app: helloworld
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["foo/ns/baz/sa/sleep-sa", "foo/*"]
```

This should allow the `sleep` from `foo` to access helloworld and deny the `sleep` from `bar`. Note the extra `foo/*` is needed to make this work otherwise the `sleep` from `bar` will also be allowed because the trust domain alias will also affect the principal in authorization policy: https://istio.io/latest/docs/tasks/security/authorization/authz-td-migration/
