### ISSUE TITLE
It is possible use cert-manager to selfSigned SSL secret based on IP?

### ISSUE THREAD

**Issue by hillbun** [istio/istio#30357]
```
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: 1-2-3-4-tls
  namespace: istio-system
spec:
  dnsNames:
    - 1.2.3.4
  secretName: 1-2-3-4-tls
  issuerRef:
    name: selfsigning-issuer
```

But this do not work.

PR_CONNECT_RESET_ERROR

**Comment by howardjohn** [comment]
I am not sure what this has to do with Istio, can you elaborate a bit?

**Comment by hillbun** [comment]
```
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigning-issuer
  namespace: istio-system
spec:
  selfSigned: {}
```


```
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: 12-34-56-78-tls
  namespace: istio-system
spec:
  dnsNames:
    - 12.34.56.78
  secretName: 12-34-56-78-tls
  issuerRef:
    name: selfsigning-issuer
```

```
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: istio-system
  name: istio-ingress-gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 443
      name: https-12-34-56-78
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: 12-34-56-78-tls
```

@howardjohn 

config is above.   when access https://12.34.56.78/ , is return error of PR_CONNECT_RESET_ERROR

**Comment by howardjohn** [comment]
```
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: 1-2-3-4-tls
  namespace: istio-system
spec:
  ipAddresses:
  - 192.168.0.5
  secretName: 1-2-3-4-tls
  issuerRef:
    name: selfsigning-issuer
```

Should you use ipAddresses, not dnsName?

**Comment by hillbun** [comment]
@howardjohn 

same errors

**Comment by hillbun** [comment]
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: 12-34-56-78-tls
  namespace: istio-system
spec:
  ipAddresses:
    -  12.34.56.78
  secretName: 12-34-56-78-tls
  issuerRef:
    name: selfsigning-issuer

**Comment by howardjohn** [comment]
@hillbun I was not able to reproduce. From my investigation, I believe this is the result of some middlebox or LB in front of envoy causing this issue.

Istio's responsibility is just to get the certificate to Envoy - if something upstream decides to deny it there isn't much we can do.

**Comment by hillbun** [comment]
@howardjohn 

I do not have LB in front.

I just deploy istio-ingressgateway as kind: DaemonSet

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
```

and setup NodePort as 443

```
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: istio-ingressgateway
  ports:
    -
      name: status-port
      port: 15020
      targetPort: 15020
    -
      name: http2
      port: 80
      targetPort: 80
      nodePort: 80
    -
      name: https
      port: 443
      targetPort: 443
      nodePort: 443
```
