### ISSUE TITLE
namespace isn't  resolved correctly in VirtualService delegation

### ISSUE THREAD

**Issue by RossyWhite** [istio/istio#30387]
**Bug description**

In delegated VirtualService, destination host's namespace becomes delegator's namespace

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

In delegated VirtualService, destination host's namespace matches with its resource's namespace

**Steps to reproduce the bug**

Consider the following manifests.

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: delegate-client-vs
  namespace: delegate-client-ns
spec:
  gateways:
    - istio-system/istio-ingressgateway
    - mesh
  hosts:
    - "delegate-sample"
  http:
  - delegate:
      name: delegate-server-vs
      namespace: delegate-server-ns
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: delegate-server-vs
  namespace: delegate-server-ns
spec:
  http:
   - route:
     - destination:
         host: backend-api
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api
  namespace: delegate-server-ns
  labels:
    run: backend-api
spec:
```

With this setup, Envoy returns `503 Service Unavailable`
This is because the route of `backend-api` is resolved as `backend-api.delegate-client-ns.svc.cluster.local`, but `backend-api` doesn't exists in `delegate-client-ns`. 

Of course, It works fine when namespace is specified explicitly.
(To do this, replace `host: backend-api` with `host: backend-api.delegate-server-ns.svc.cluster.local`)

Below is a part of `istioctl proxy-config route`
```json
"name": "delegate-sample.delegate-client-ns.svc.cluster.local:80",
"virtualHosts": [
    {
        "name": "delegate-sample.delegate-client-ns.svc.cluster.local:80",
        "domains": [
            "delegate-sample.delegate-client-ns.svc.cluster.local",
            "delegate-sample.delegate-client-ns.svc.cluster.local:80",
            "delegate-sample.delegate-client-ns",
            "delegate-sample.delegate-client-ns:80",
            "delegate-sample.delegate-client-ns.svc.cluster",
            "delegate-sample.delegate-client-ns.svc.cluster:80",
            "delegate-sample.delegate-client-ns.svc",
            "delegate-sample.delegate-client-ns.svc:80",
            "172.20.191.243",
            "172.20.191.243:80"
        ],
        "routes": [
            {
                "match": {
                    "prefix": "/"
                },
                "route": {
                    "cluster": "outbound|80||backend-api.delegate-client-ns.svc.cluster.local",
```

Is this expected behavior or bug?

I think it is more natural for `backend-api` to be resolved as `backend-api.delegate-server-ns.svc.cluster.local` because it is defined in `delegate-server-vs`(whose namespace is `delegate-server-ns`)

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

istio
```
client version: 1.8.2
control plane version: 1.8.2
data plane version: 1.8.2
```

k8s
```
Client Version: v1.20.1
Server Version: v1.18.9-eks-d1db3c
```

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

on Amazon EKS

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
