### ISSUE TITLE
Help me!!! istio1.3.0 error 503 Server Error: Service Unavailable

### ISSUE THREAD

**Issue by jidemoski** [istio/istio#30389]
Hi everyone: 
**Help me!!!**

when I request the istio ingress gateway, sometime it return **503 Server Error: Service Unavailable**. But I directly access the svc, the error not take place. I don't find the reason.  Can you help me?  Thank you

I deploy **kubeflow** in my k8s cluster. when I  create a app and a service.  and try to use **istio1.3** ingress intergate proxy the service. 
maybe: 
```
client --->istio ingress gateway-->istio vs-->svc-->app
```

my deploy file:
* gateway.yaml
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: test
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
````

* vs.yaml
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test
spec:
  gateways:
  - test
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /test/
    rewrite:
      uri: /
    route:
    - destination:
        host: test
        port:
          number: 80
```

* svs.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  type: ClusterIP
  selector:
    app: test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
      name: http
```

* app.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  replicas: 4
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image:  web:v1.0
        ports:
        - containerPort: 8888
        resources:
          limits:
            cpu: 800m
```

**Comment by su225** [comment]
https://istio.io/v1.3/docs/reference/config/networking/v1alpha3/virtual-service/
https://istio.io/latest/docs/reference/config/networking/virtual-service/#VirtualService
In your `VirtualService` configuration, maybe you should specify the service name under `hosts` instead of `*`? 

For example, to send traffic to test in default namespace,
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test
spec:
  gateways:
  - test
  hosts:
  - "test.default.svc.cluster.local"
....
```
