### ISSUE TITLE
span of external svc is not reported from envoy

### ISSUE THREAD

**Issue by lut777** [istio/istio#30388]
**Bug description**

I have a problem when using the tracing system.

A good system should record all tracing spans from start to finish. 

Sometimes a svc/pod within the cluster need to invoke a service outside the cluster, especial in the case of mixed VM/container deployments. However, the end of the span, which is from the end of the in-cluster pod to the external service, is not reported by envoy in current Istio(1.8.1).

I deployed a standard jaeger as [official](https://www.jaegertracing.io/docs/1.21/operator/), and I set jaeger address at global:proxy:tracer:zipkin:adress so that envoy could send data to that address.

As an example below:

This is invoking  Example: in cluster A, svc a invoke svc b, and then svc b invoke an external svc( e.g., an external elasticsearch svc).

```
||                   |             ||
  
||     svc a      => | => svc b ==>|| ==>  external svc (e.g., elasticsearch.external )   

||       ns a        |       ns b  ||

	        cluster A

```

The tracing result is shown below: 

```
Trace: ( ideal )     					  	Trace: ( actual )     

      svca.nsa =============                                      svca.nsa =============

         svca.nsa ==========                                        svca.nsa ===========             
 
             svcb.nsb=======                                            svcb.nsb ======= 

                svcb.nsb====     

```

An ideal result should include the span which starts from svcb.nsb to external service, but now the actual result does not include this span. 

However, if this external service is a internal service, the tracing is ideal.

I have tried following methods:

1, I set the tracing configuration of proxy-init as following but it does not work.

```json
{
"tracing": {
     "http": {
      "name": "envoy.tracers.zipkin",
      "typed_config": {
       "@type": "type.googleapis.com/envoy.config.trace.v3.ZipkinConfig",
       "collector_cluster": "zipkin",
       "collector_endpoint": "/api/v2/spans",
       "trace_id_128bit": true,
       "shared_span_context": true,
       "collector_endpoint_version": "HTTP_JSON"
      }
     }
}
```

2, I deploy *serviceentry* and *virtualservice* as following but it does not work.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: elastic-external
  namespace: default
spec:
  hosts:
  - elasticsearch7-se
  addresses:
  - 172.16.10.100/32
  location: MESH_EXTERNAL
  ports:
  - number: 39200
    name: http
    protocol: TCP
  resolution: NONE
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: elasticsearch-vs
  namespace: default
spec:
  hosts:
  - elasticsearch7
  http:
  - timeout: 10s
    route:
    - destination:
        host: elasticsearch7-se
```

I checked the listener which listens port 39200 and ip 172.16.10.100, and this listener does exist.

Also, I checked the cluster and I found the corresponding cluster.

I am not pretty sure which components is related to tracing. I checked the listener/cluster/init-configuration, but I could not find a config-part for the tracing of external service.

I'd like to contribute code to this feature in spare time, as long as there is a mentor willing to give me some advice...

[ ] Extensions and Telemetry
[ ] User Experience

[ ] Multi Cluster
[ ] Virtual Machine

**Expected behavior**
The span from in-cluster pod to external service should be reported from envoy.

**Steps to reproduce the bug**
Set jaeger and configuration for envoy to report.
Set a in-cluster pod to invoke an external svc.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
k8s: 1.18.12
Istio: 1.8.1, installed by IstioOperator
system: linux 4.15.0

**How was Istio installed?**
Operator

**Environment where the bug was observed (cloud vendor, OS, etc)**
Local cluster
