### ISSUE TITLE
Istio 1.8.1 ingress gateway not responding

### ISSUE THREAD

**Issue by obeyda** [istio/istio#30395]
I am having this issue on a AKS cluster, using istio 1.8.1 
using profile `default`, 
i added a gateway like this: 
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-services-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: ingress-cert-dev-tls
      privateKey: sds
      serverCertificate: sds
    hosts:
    - "*.my.domain.com"
```

when sending requests, the gateway hangs randomly and after a period ~30s i get timeout, 
when i checked the load balancer status in azure i got this

![image](https://user-images.githubusercontent.com/15065966/105865502-4ab50100-5ff3-11eb-9158-74769582684f.png)

**Comment by obeyda** [comment]
when i removed the these ports from the default profile it stopped failing health checks: 
```
# in: spec.components.ingressGateways[0].k8s.service.ports

          ports:
          # - name: status-port
          #   port: 15021
          #   protocol: TCP
          #   targetPort: 15021
          - name: http2
            port: 80
            protocol: TCP
            targetPort: 8080
          - name: https
            port: 443
            protocol: TCP
            targetPort: 8443
          # - name: tcp-istiod
          #   port: 15012
          #   protocol: TCP
          #   targetPort: 15012
          # - name: tls
          #   port: 15443
          #   protocol: TCP
          #   targetPort: 15443
```
but won't that pose problems? if so, why we have this config in the defualt profile?
