### ISSUE TITLE
Sub optimal readinessProbe configuration

### ISSUE THREAD

**Issue by Stono** [istio/istio#30436]
**Bug description**
Worlds most minor bug but on `1.8.2` `istiod` generates with the following `readinessProbe` config:

```
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 3
            timeoutSeconds: 5
```

Our platform blocks this because we believe `timeoutSeconds` should never be greater than `periodSeconds` otherwise you'll have a period where you have multiple healthchecks running.

We've worked around it with:

```
spec:
  components:
    pilot:
      k8s:
        overlays:
        - kind: Deployment
          name: istiod
          patches:
          - path: spec.template.spec.containers.[name:discovery].readinessProbe.timeoutSeconds
            value: 3
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
I think these should perhaps both be equal?

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.8.2

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
