### ISSUE TITLE
Help: converting nginx ingress to istio

### ISSUE THREAD

**Issue by Baitanik** [istio/istio#30435]
I have some onprem setup.. where some backend service is using https and some are using http..
right now we were using nginx ingress, but we are trying to replace with istio.. 
in nginx ingress ,separate ingress configuration  has annotation to define the backup protocol 

nginx.ingress.kubernetes.io/backend-protocol:HTTPS
nginx.ingress.kubernetes.io/backend-protocol:HTTP

in istio in virtual service, can we define anything like that.. so that depending on the protocol mentioned that particular service will be called in http or https mode... 
is there any way to achieve the same functionality like nginx  backend-protocol annotation..

**Comment by SpecialYang** [comment]
Try read this doc https://istio.io/latest/docs/reference/config/networking/destination-rule/#ClientTLSSettings.

**Comment by Baitanik** [comment]
Yeah thanks @SpecialYang .. I have configured the destination rules ... but i right now i am stuck at converting nginx ingress to istio vs .. 
https://github.com/istio/istio.io/issues/8874

how do I give /$2 in the istio vs rewrite rules ? or how to achieve the same functionality ..

**Comment by SpecialYang** [comment]
I think you do not need to rewrite path, try to remove the following config for every route.
```
rewrite:
      uri: /
```

**Comment by Baitanik** [comment]
This works.. Thank you @SpecialYang ... 
now it is working with http backend.. 

let me try the https backend now...

**Comment by Baitanik** [comment]
Https i am getting some errors... 
for the ingress rule mentioned below
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-control-plane
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
  labels:
    app: metalk8s-ui
    app.kubernetes.io/name: metalk8s-ui
    app.kubernetes.io/part-of: metalk8s
    heritage: salt
    metalk8s.scality.com/version: 2.6.0-dev
  name: metalk8s-ui-proxies-https
  namespace: metalk8s-ui
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: kubernetes-api
          servicePort: 443
        path: /api/kubernetes(/|$)(.*)
      - backend:
          serviceName: salt-api
          servicePort: 4507
        path: /api/salt(/|$)(.*)
 ```
I have following vs and destination rule... 
```
  gateways:
  - istio-system/istio-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /api/kubernetes/
    rewrite:
      uri: /
    route:
    - destination:
        host: kubernetes-api-ds
        port:
          number: 443
      weight: 100
  - match:
    - uri:
        prefix: /api/salt/
    rewrite:
      uri: /
    route:
    - destination:
        host: salt-api
        port:
          number: 4507
      weight: 100
```

```
metadata:
  name: kubernetes-api-ds
  namespace: metalk8s-ui
spec:
  host: kubernetes-api
  trafficPolicy:
    portLevelSettings:
    - loadBalancer:
        simple: ROUND_ROBIN
      port:
        number: 443
    tls:
      caCertificates: /etc/istio/ingressgateway-certs/tls.crt
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/tls.key

```

/api/kubernetes/ --> that is giving 503 in the ingressgate way log.. 

[2021-02-01T12:15:19.208Z] "GET /api/kubernetes/api/v1/namespaces?includeUninitialized=&pretty=&continue=&fieldSelector=metadata.name%3Dkube-system HTTP/2" 503 NR "-" 0 0 0 - "10.105.58.133" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36" "bf64c2f2-2e01-41e6-85b9-e6ac7fcd417b" "10.105.58.133:8443" "-" - - 192.168.14.216:8443 10.105.58.133:28368

what could be the reason.. could you please help

**Comment by SpecialYang** [comment]
Could you provide your gateway config?

**Comment by Baitanik** [comment]
gateway config::
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: https
      number: 8443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt

```

**Comment by SpecialYang** [comment]
Guess the host should be `kubernetes-api`.
```
route:
    - destination:
        host: kubernetes-api
        port:
          number: 443
      weight: 100
```

**Comment by Baitanik** [comment]
if i give kubernetes-api in the vs ... 

```
    rewrite:
      uri: /
    route:
    - destination:
        host: kubernetes-api
        port:
          number: 443
      weight: 100
      ```
      then it is coming 
      ```Client sent an HTTP request to an HTTPS server. ```

**Comment by SpecialYang** [comment]
Curl localhost:15014/debug/configz or Curl localhost:8080/debug/configz in pilot container. I want to see all your configs.

**Comment by Baitanik** [comment]
[configz.log](https://github.com/istio/istio/files/5904380/configz.log)
Please find the attached o/p of the debug/configz ...

**Comment by SpecialYang** [comment]
Try to read these doc. You can obtain more information about host field.
- https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRouteDestination
- https://istio.io/latest/docs/reference/config/networking/destination-rule/#DestinationRule

**Comment by Baitanik** [comment]
yeah i am going though that only... 

Tried to change the host to ```kubernetes.default.svc.cluster.local``` ..
I tried to give the vs config, like.. 
```
spec:
  gateways:
  - istio-system/rainier-istio-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /api/kubernetes/
    rewrite:
      uri: /
    route:
    - destination:
        host: kubernetes.default.svc.cluster.local
        port:
          number: 443
      weight: 100

```

but it says ```Client sent an HTTP request to an HTTPS server.``` ... 
adding destination rule is not having any impact... 
added destination rule.. 
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: kubernetes-api-ds
  namespace: metalk8s-ui
spec:
  host: kubernetes.default.svc.cluster.local
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 443
      loadBalancer:
        simple: ROUND_ROBIN
    tls:
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      caCertificates: /etc/istio/ingressgateway-certs/tls.crt

```

Without having destination rule and with having destination rule it is giving same error.
```Client sent an HTTP request to an HTTPS server.```

**Comment by SpecialYang** [comment]
Does you service has multiple ports? If not, try remove 
```
 - port:
        number: 443
      loadBalancer:
        simple: ROUND_ROBIN
```
Because portLevelSettings will override DestinationRule level setting.

If you really has more ports, then move tls under portLevelSettings.
```
trafficPolicy:
    portLevelSettings:
    - port:
        number: 443
      loadBalancer:
        simple: ROUND_ROBIN
      tls:
        mode: SIMPLE
        privateKey: /etc/istio/ingressgateway-certs/tls.key
        caCertificates: /etc/istio/ingressgateway-certs/tls.crt
```
