### ISSUE TITLE
Setting resolution and location from go client doesnt seem to work

### ISSUE THREAD

**Issue by kevin-shelaga** [istio/istio#30434]
**Bug description**
I am creating pretty simple http/https service entries in kubernetes with the istio go client.

```go
	se := &v1alpha3.ServiceEntry{
		ObjectMeta: metav1.ObjectMeta{
			Name:      name,
			Namespace: namespace,
		},
		Spec: networkingv1alpha3.ServiceEntry{
			Hosts:      hosts,
			Ports:      []*networkingv1alpha3.Port{http, https},
			Location:   networkingv1alpha3.ServiceEntry_MESH_EXTERNAL,
			Resolution: networkingv1alpha3.ServiceEntry_NONE,
		},
	}
```

However the created service entries do not have resolution and location set after the successful creation.

```yml
...
  ports:
    - name: http
      number: 80
      protocol: HTTP
    - name: https
      number: 443
      protocol: HTTPS
  location: ~
  resolution: ~
```

istio.io/client-go v1.8.2
