### ISSUE TITLE
question: External (ingress) and Internal Traffic Routing to Different Subset

### ISSUE THREAD

**Issue by jon-whit** [istio/istio#30453]
I’m trying to configure Istio (currently on 1.3.0) to route to a different service subset based on the presence of a header at the ingress and internal service layer. I’m using traefik for my ingress, not an istio gateway. And my ingress, virtual service, and destination rules look like this:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik-internal
  name: bookinfo-ingress
  namespace: istio-demo
spec:
  rules:
  - host: bookinfo.example.com
    http:
      paths:
      - backend:
          serviceName: reviews
          servicePort: 9080
status:
  loadBalancer:
    ingress:
    - hostname: internal-<uuid>.us-west-2.elb.amazonaws.com
```

and

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
  namespace: istio-demo
spec:
  hosts:
  - bookinfo.example.com
  - reviews
  http:
  - match:
    - headers:
        end-user:
          exact: jason
    route:
    - destination:
        host: reviews
        subset: v2
  - route:
    - destination:
        host: reviews
        subset: v1
```
and

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews
  namespace: istio-demo
spec:
  host: reviews
  subsets:
  - labels:
      version: v1
    name: v1
  - labels:
      version: v2
    name: v2
  - labels:
      version: v3
    name: v3
```

My goal is to be able to route to a specific subset based on header at the ingress (external) layer or internally with service to service calls. What is wrong with my config? I cannot get it to work. It just round-robin load balances when I hit the external domain `bookinfo.example.com`.
