### ISSUE TITLE
Istio Operator Not Correctly Syncing Ingress Gateway Deployment

### ISSUE THREAD

**Issue by jpaulodit** [istio/istio#30456]
**Bug description**
I'm using Istio Operator to install and manage the mesh. And I am noticing that when I update the ingress gateway configuration, specifically podAnnotations with new data. The ingress gateway deployment CRD has both the old values and the new fields. I was expecting them to be updated.

[ ] Docs
[x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**
```
> kubectl -n istio-system edit istiooperator istiocontrolplane
```
```
spec:
  components:
    ingressGateways:
    - enabled: true
      k8s:
        podAnnotations:
          # Add some annotation like the following.
          ad.datadoghq.com/istio-proxy.check_name: '["istio"]'
          ad.datadoghq.com/istio-proxy.init_configs: '[{}]'
          ....
```
The annotations that I added is then shown in the deployment CRD of the ingress gateway.

Edit the istio operator again
```
        podAnnotations:
          ad.datadoghq.com/istio-proxy.check_names: '["istio"]'.   <--- add an 's' to names.
```
When I describe the deployment of the ingress gateway, I end up with 2 entries in the annotations.
```
> kubectl describe deployment istio-ingressgateway -n istio-system
...
                    service.istio.io/canonical-name=istio-ingressgateway
                    service.istio.io/canonical-revision=latest
  Annotations: 
                    ad.datadoghq.com/istio-proxy.check_name: ["istio"]     
                    ad.datadoghq.com/istio-proxy.check_names: ["istio"]
                    ad.datadoghq.com/istio-proxy.init_configs: [{}]
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
$ istioctl version --remote
client version: 1.8.0
control plane version: 1.8.0
data plane version: 1.8.0 (7 proxies)
```

**How was Istio installed?**
Installed with IstioOperator

**Environment where the bug was observed (cloud vendor, OS, etc)**
Linux, EKS

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by morvencao** [comment]
That's because we use a strategic merge patch to update the k8s settings.
similar to https://github.com/istio/istio/issues/29188

**Comment by jpaulodit** [comment]
Thanks for the quick response @morvencao . Is this supposed to be fixed by PR [#29166 ](https://github.com/istio/istio/pull/29166/files)? I'm already on 1.18. 

Do you have any suggestions on how to handle this issue?

**Comment by morvencao** [comment]
I don't think https://github.com/istio/istio/pull/29166 fixed the issue.
Before we figure out the fix, you can use the advanced k8s overlay to workaround this, for example:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
    - enabled: true
      k8s:
        overlays:
        - kind: Deployment
          name: istio-ingressgateway
          patches:
          - path: spec.template.metadata.annotations\.ad\.datadoghq\.com/istio-proxy\.check_name
          - path: spec.template.metadata.annotations\.ad\.datadoghq\.com/istio-proxy\.check_names
            value: "istio"
```

It will delete the old annotation `ad.datadoghq.com/istio-proxy.check_name` and add new annotation: `ad.datadoghq.com/istio-proxy.check_names: istio`
