### ISSUE TITLE
It does not seem NET_ADMIN is really needed for Istio-CNI to work

### ISSUE THREAD

**Issue by somejfn** [istio/istio#30481]
**Bug description**

Running istio 1.8.1 on K8s 1.19.2 with CNI enabled and a custom PSP for the istio-cni service account,  I did not grant any capabilities (see PSP below) and traffic redirection is working... so Im confused if that requirement is something of the past.

Documentation page  https://istio.io/latest/docs/ops/common-problems/observability-issues/ says:

" PodSecurityPolicy is being enforced in your cluster, ensure the istio-cni service account can use a PodSecurityPolicy which allows the NET_ADMIN and NET_RAW capabilities."

My PSP:

```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: istio-cni
  annotations:
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'runtime/default'
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
  - ALL
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - 'configMap'
  - 'emptyDir'
  - 'projected'
  - 'secret'
  - 'downwardAPI'
  - 'hostPath'
  hostPID: false
  hostIPC: false
  hostNetwork: true
  readOnlyRootFilesystem: false
```

And a confirmation the daemon-set pod is using it:
```
$ k get pods -n istio-system istio-cni-node-ls76m -o jsonpath='{.metadata.annotations}'
map[kubernetes.io/psp:istio-cni scheduler.alpha.kubernetes.io/critical-pod: seccomp.security.alpha.kubernetes.io/pod:runtime/default sidecar.istio.io/inject:false]
```

I do see the sidecars running in the application namespace, virtual services,  traces and kiali graphs are working so I believe this is enough proof traffic redirection is indeed working.

[X ] Docs
[ X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Either documentation should be updated or Im missing something 

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

Operator CR:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiocontrolplane
spec:
  revision: 1-8-1
  tag: 1.8.1
  meshConfig:
    defaultConfig:
      tracing:
        sampling: 1
  profile: default
  components:
    cni:
      enabled: true
  values:
    cni:
      excludeNamespaces:
       - istio-system
       - kube-system
```

**Environment where the bug was observed (cloud vendor, OS, etc)**
Kubeadm based cluster, onpremise, Centos 7, docker://19.3.12, canal CNI driver in hostgw mode

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
