### ISSUE TITLE
How to Redirect HTTP to HTTPS with specificed domain name?

### ISSUE THREAD

**Issue by hillbun** [istio/istio#30501]
https://istio.io/latest/docs/reference/config/networking/gateway/

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
  namespace: some-config-namespace
spec:
  selector:
    app: my-gateway-controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - uk.bookinfo.com
    - eu.bookinfo.com
    tls:
      httpsRedirect: true
```

if I only wanto to redirect eu.bookinfo.com to HTTPS, how to setup?

**Comment by howardjohn** [comment]
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
  namespace: some-config-namespace
spec:
  selector:
    app: my-gateway-controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - uk.bookinfo.com
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - eu.bookinfo.com
    tls:
      httpsRedirect: true
```

**Comment by zengyuxing007** [comment]
@howardjohn 

If I want to redirect all exmaple.com subdomains except test.example.com, it seems that 1.8, 1.9 and the current version are not supported, I have tested it in 1.9.7 and confirmed that it is not supported.


```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: my-gateway
  namespace: default
spec:
  selector:
    app: istio-ingressgateway
  servers:
   - hosts:
     - '*.example.com'
     name: others
     port:
       name: http
       number: 80
       protocol: HTTP
     tls:
       httpsRedirect: true
   - hosts:
     - "test.example.com"
     name: test
     port:
       name: http1
       number: 80
       protocol: HTTP
     tls:
       httpsRedirect: false
   - hosts:
     - '*.example.com'
     name: httpbin-https
     port:
       name: https
       number: 443
       protocol: HTTPS
     tls:
      mode: SIMPLE
      credentialName: httpbin-credential
```
