### ISSUE TITLE
Istio with multiple ingressgateways + cert-manager with acme issuer not working

### ISSUE THREAD

**Issue by crrazyman** [istio/istio#30508]
**Bug description**
I have a situation where i need multiple istio ingressgateways (actually i need multiple loadbalancers and multiple IPs), each for each client. I want everyhting to be in the client's namespace "xxx". The ingressgateway, the cert-manager issuer, the certificate, everything.

The ingressgateway works perfect in the client's namespace:

```
$ kubectl -n xxx get all
NAME                                      READY   STATUS    RESTARTS   AGE
pod/xxx-ingressgateway-5d7b7fb9fc-dhztl   1/1     Running   0          20h

NAME                         TYPE           CLUSTER-IP       EXTERNAL-IP     PORT(S)                                                      AGE
service/xxx-ingressgateway   LoadBalancer   10.216.1.161     20.50.169.168   15021:31315/TCP,80:32573/TCP,443:32066/TCP,15443:32070/TCP   20h

NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/xxx-ingressgateway   1/1     1            1           20h

NAME                                            DESIRED   CURRENT   READY   AGE
replicaset.apps/xxx-ingressgateway-5d7b7fb9fc   1         1         1       20h

NAME                                                     REFERENCE                       TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
horizontalpodautoscaler.autoscaling/xxx-ingressgateway   Deployment/xxx-ingressgateway   2%/80%    1         5         1          20h
```
I also have a DNS entry for **xxx.example.com -> 20.50.169.168** (xxx-ingressgateway's IP)

I have configured an cert-manager issuer like this:

```
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: xxx
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: it@example.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: istio
```

The problem is that when i want to issue a certificate with this issuer **istiod** does not configure **xxx-ingressgateway** for this ingress and Letsencrypt cannot verify the domain.
I'm guessing that **solvers.http01.ingress.class: istio** is something too generic and **istiod** does not know where to configure this ingress or it configures it on the default ingressgateway (the one from istio-system namespace).

I can also see that xxx-ingressgateway is not configured:

```
$ istioctl ps
NAME                                                         CDS        LDS        EDS        RDS          ISTIOD                      VERSION
xxx-ingressgateway-5d7b7fb9fc-dhztl.bmw                      SYNCED     SYNCED     SYNCED     NOT SENT     istiod-569947dd97-h4w59     1.8.2
istio-ingressgateway-6f8bbbbd8c-cxfqp.istio-system           SYNCED     SYNCED     SYNCED     SYNCED       istiod-569947dd97-h4w59     1.8.2
```

If i change the DNS entry **xxx.example.com -> ip_address_of_ingressgateway_from_istio-system** and i generate the certificate in istio-system namespace and then i just copy the secret to xxx namespace and change the DNS back, everything works. 
I only have problems with cert-manager ingress class

[X] Networking

**Expected behavior**
istiod should configure xxx-ingressgateway for this ingress and the certificate should be generated and verified by letsencrypt.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
$ istioctl version --remote
client version: 1.8.2
control plane version: 1.8.2
data plane version: 1.8.2 (8 proxies)

$ kubectl version --short
Client Version: v1.19.4
Server Version: v1.18.14
```

**How was Istio installed?**
istioctl install -f istioCustomInstall.yaml

istioCustomInstall.yaml:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  meshConfig:
    accessLogFile: /dev/stdout
  values:
    global:
      proxy:
        excludeIPRanges: "10.216.0.1/32"
  components:
    ingressGateways:
      - name: "xxx-ingressgateway"
        namespace: xxx
        enabled: true
        label:
          istio: xxx-ingressgateway
          app: xxx-ingressgateway
```

**Environment where the bug was observed (cloud vendor, OS, etc)**
Azure AKS
