### ISSUE TITLE
status distribution: "X/Y proxies up to date" api is not feasible

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30511]
Part of https://github.com/istio/istio/issues/30120

```yaml
status:
  conditions:
  - lastProbeTime: "2021-01-15T19:45:54.504546007Z"
    lastTransitionTime: "2021-01-15T19:45:54.504547691Z"
    message: 4/4 proxies up to date.
    status: "True"
    type: Reconciled
  observedGeneration: "1"
  validationMessages:
  - documentation_url: https://istio.io/v1.1/docs/reference/config/analysis/ist0101/?ref=status-controller
    level: 3
    type:
      code: IST0101
  - documentation_url: https://istio.io/v1.1/docs/reference/config/analysis/ist0132/?ref=status-controller
    level: 8
    type:
      code: IST0132
```

4/4 proxies up to date is wrong/misleading. I have many more proxies in my cluster at this point. I recommend we just say its been distributed to ALL proxies, rather than a fixed number. I think the number is also (sometimes?) 4x the number of proxies, one for each resource type.
