### ISSUE TITLE
status: analysis documentation url is wrong

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30515]
Part of https://github.com/istio/istio/issues/30120

```yaml
status:
  conditions:
  - lastProbeTime: "2021-01-15T19:45:54.504546007Z"
    lastTransitionTime: "2021-01-15T19:45:54.504547691Z"
    message: 4/4 proxies up to date.
    status: "True"
    type: Reconciled
  observedGeneration: "1"
  validationMessages:
  - documentation_url: https://istio.io/v1.1/docs/reference/config/analysis/ist0101/?ref=status-controller
    level: 3
    type:
      code: IST0101
  - documentation_url: https://istio.io/v1.1/docs/reference/config/analysis/ist0132/?ref=status-controller
    level: 8
    type:
      code: IST0132
```

The version is wrong. Its meant to be v1.10, (Which is also wrong, is it doesn't exist yet) because we do baseVersion[:3] in the code so it doesn't handle 2 digit numbers.
