### ISSUE TITLE
Exposing istio-discovery deployment argument in Helm Template

### ISSUE THREAD

**Issue by prary** [istio/istio#30537]
**Describe the feature request**
Can't configure all the argument provided in https://istio.io/latest/docs/reference/commands/pilot-discovery/ in helm templates
e.g  log_stacktrace_level in https://github.com/istio/istio/blob/1b81be10cae774a2a8d7ab8113a437246ef230ee/manifests/charts/istio-control/istio-discovery/templates/deployment.yaml#L73
and hence in values.yaml

**Describe alternatives you've considered**
Adding missing arguements

[ X ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ X ] Developer Infrastructure

Will raise the PR if this adds value to the project.

**Comment by howardjohn** [comment]
I don't think our templates can reasonably expose every possible option. I would recommend using some patching or overlay mechanism as provided by the IstioOperator API or kustomize it many others

**Comment by morvencao** [comment]
@prary An example to set additional args to istiod deployment with k8s overlay:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    pilot:
      k8s:
        overlays:
        - kind: Deployment
          name: istiod
          patches:
          - path: spec.template.spec.containers.[name:discovery].args.[0]
            value: "--log_stacktrace_level=default:info"
```
