### ISSUE TITLE
Operator support for image digests

### ISSUE THREAD

**Issue by halvards** [istio/istio#30548]
**Describe the feature request**

The `istio.operator.v1alpha1` API should support deploying container images by digest for components such as pilot, ingress/egress gateways, and the sidecar proxy, without resorting to overlay patches.

Currently, the spec as documented only allows users to specify the tag. There is no field users can set to either instruct istioctl to resolve tags to digests prior to deployment. This could be a boolean field.

**Describe alternatives you've considered**

It's possible to use `K8sObjectOverlay` to specify an image with digest for components, and `global` values for the sidecar `proxy` and `proxy_init` image:

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: empty
  hub: gcr.io/istio-release
  components:
    base:
      enabled: true
    pilot:
      enabled: true
      k8s:
        overlays:
        - apiVersion: apps/v1
          kind: Deployment
          name: istiod
          patches:
          - path: spec.template.spec.containers.[name:discovery].image
            value: gcr.io/istio-release/proxyv2:1.8.2@sha256:2f5931b4c0856ae48a9b17cae2ddc384cdd97b0f40d455e61e8636d32a6392f3
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
  values:
    global:
      proxy_init:
        image: gcr.io/istio-release/proxyv2:1.8.2@sha256:2f5931b4c0856ae48a9b17cae2ddc384cdd97b0f40d455e61e8636d32a6392f3
      proxy:
        image: gcr.io/istio-release/proxyv2:1.8.2@sha256:2f5931b4c0856ae48a9b17cae2ddc384cdd97b0f40d455e61e8636d32a6392f3
```

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
