### ISSUE TITLE
Istio ingress does not work with ExternalNames

### ISSUE THREAD

**Issue by yuzisun** [istio/istio#30547]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

Istio ingress does not work with ExternalNames and getting 404 when accessing the ingress

```
*   Trying ::1:8080...
* Connected to localhost (::1) port 8080 (#0)
> GET /v2/models/sklearn-iris HTTP/1.1
> Host: sklearn-iris.default.example.com
> User-Agent: curl/7.73.0
> Accept: */*
> 
Handling connection for 8080
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< date: Mon, 01 Feb 2021 07:43:18 GMT
< server: istio-envoy
< x-envoy-upstream-service-time: 0
< content-length: 0
< 
* Connection #0 to host localhost left intact
```

This is the route in the envoy config and upstream service `sklearn-iris-predictor-default.default.svc.cluster.local` is an ExternalName.
```
kubectl get svc sklearn-iris-predictor-default
NAME                             TYPE           CLUSTER-IP   EXTERNAL-IP                                            PORT(S)   AGE
sklearn-iris-predictor-default   ExternalName   <none>       cluster-local-gateway.istio-system.svc.cluster.local   80/TCP    38m
```

```
                "name": "sklearn-iris.default.example.com:80",
                "domains": [
                    "sklearn-iris.default.example.com",
                    "sklearn-iris.default.example.com:*"
                ],
                "routes": [
                    {
                        "match": {
                            "prefix": "/",
                            "caseSensitive": true
                        },
                        "route": {
                            "cluster": "outbound|80||sklearn-iris-predictor-default.default.svc.cluster.local",
                            "timeout": "0s",
                            "retryPolicy": {
                                "retryOn": "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes",
                                "numRetries": 2,
                                "retryHostPredicate": [
                                    {
                                        "name": "envoy.retry_host_predicates.previous_hosts"
                                    }
                                ],
                                "hostSelectionRetryMaxAttempts": "5",
                                "retriableStatusCodes": [
                                    503
                                ]
                            },
                            "maxGrpcTimeout": "0s"
                        },
                        "metadata": {
                            "filterMetadata": {
                                "istio": {
                                    "config": "/apis/networking.istio.io/v1alpha3/namespaces/default/virtual-service/sklearn-iris-default-example-com-ingress-istio-autogenerated-k8s-ingress"
                                }
                            }
                        },
                        "decorator": {
                            "operation": "sklearn-iris-predictor-default.default.svc.cluster.local:80/*"
                        }
                    }
                ]
            }
        ],
 ```
 
 
if I curl the upstream service manually then it works.
```
kubectl exec -it istio-ingressgateway-7c768b8474-5lnvw   -n istio-system /bin/bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.
root@istio-ingressgateway-7c768b8474-5lnvw:/# curl sklearn-iris-predictor-default.default.svc.cluster.local/v2/models/sklearn-iris
{"name":"sklearn-iris","versions":[],"platform":"","inputs":[],"outputs":[]}
```

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
Istio ingress should work with ExternalNames

**Steps to reproduce the bug**
1. Create a knative service which generates an ExternalName `sklearn-iris-predictor-default`
```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sklearn-iris-predictor-default
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
        autoscaling.knative.dev/minScale: "1"
        internal.serving.kubeflow.org/storage-initializer-sourceuri: gs://seldon-models/sklearn/iris
      labels:
        component: predictor
        serving.kubeflow.org/inferenceservice: sklearn-iris
    spec:
      containerConcurrency: 0
      containers:
      - env:
        - name: MLSERVER_HTTP_PORT
          value: "8080"
        - name: MLSERVER_GRPC_PORT
          value: "9000"
        - name: MODELS_DIR
          value: /mnt/models
        - name: MLSERVER_MODEL_IMPLEMENTATION
          value: mlserver.models.SKLearnModel
        - name: MLSERVER_MODEL_NAME
          value: sklearn-iris
        - name: MLSERVER_MODEL_VERSION
          value: v1
        - name: MLSERVER_MODEL_URI
          value: /mnt/models
        image: docker.io/seldonio/mlserver:0.1.2
        name: kfserving-container
        readinessProbe:
          successThreshold: 1
          tcpSocket:
            port: 0
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
    tag: latest
```

Above generates the ExternalName which points to istio local gateway
```
kubectl get svc sklearn-iris-predictor-default
NAME                             TYPE           CLUSTER-IP   EXTERNAL-IP                                            PORT(S)   AGE
sklearn-iris-predictor-default   ExternalName   <none>       cluster-local-gateway.istio-system.svc.cluster.local   80/TCP    47m
```

2. Create Istio Ingress which points to the ExternalName `sklearn-iris-predictor-default`
```
apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
  name: istio
spec:
  controller: istio.io/ingress-controller
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  ingressClassName: istio
  rules:
  - host: sklearn-iris.default.example.com 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: sklearn-iris-predictor-default 
          servicePort: 80
```

3: Curl the ingress host and you get 404

```
curl -v -H "Host: sklearn-iris.default.example.com" http://${INGRESS_HOST}:${INGRESS_PORT}/v2/models/sklearn-iris
*   Trying ::1:8080...
* Connected to localhost (::1) port 8080 (#0)
> GET /v2/models/sklearn-iris HTTP/1.1
> Host: sklearn-iris.default.example.com
> User-Agent: curl/7.73.0
> Accept: */*
> 
Handling connection for 8080
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< date: Mon, 01 Feb 2021 07:58:10 GMT
< server: istio-envoy
< content-length: 0
< 
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.6.2 

**How was Istio installed?**
istio operator

**Environment where the bug was observed (cloud vendor, OS, etc)**
kind cluster

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
