### ISSUE TITLE
EOF issue when using istio ingress gateway

### ISSUE THREAD

**Issue by linsun** [istio/istio#30577]
**Bug description**

I have a script client that reads the file server to download the file with a given buffer size and delay.  When running the simple client with the file server (as a service in k8s exposed as LB type) directly without istio ingress gw, no issue.  However, when running the simple client through istio ingress gw then the file server (as a service in k8s), it often fails with EOF where it can't finish reading all the contents yet got EOF.

Simple client:  https://gist.github.com/jhart1685/f7101b94a5f7044873b416316c42f5e8 - instruction is also there.  Note comment line 28 or 30 would make the test pass with istio ingress gw.

File server:  https://github.com/jhart1685/staticfileserver.  It doesn't have any sidecar.

Deployment yamls:

```
apiVersion: v1
kind: Service
metadata:
  name: bigfile
  namespace: default
spec:
  ports:
  - name: http-service
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: bigfile
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bigfile
  name: bigfile
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bigfile
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      labels:
        app: bigfile
    spec:
      containers:
      - image: rvennam/simplefileserver:latest
        imagePullPolicy: IfNotPresent
        name: simplefileserver
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log/containers/simplefileserver
          name: simplefileserver
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 1000
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/log/apps/simplefileserver
          type: ""
        name: simplefileserver
```

GW + VS + DR:

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: bigfile-front-door
  namespace: istio-system
spec:
  gateways:
  - front-door
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: bigfile.default.svc.cluster.local
        port:
          number: 8080
```

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: front-door
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
```

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: bigfile-front-door
  namespace: istio-system
spec:
  host: bigfile.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
    connectionPool:
      tcp:
        maxConnections: 100
        connectTimeout: 30s
        tcpKeepalive:
          time: 7200s
          interval: 75s
      http:
        idleTimeout: 7200s
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by linsun** [comment]
An example of failed one:

```
$ go run main.go http://169.60.80.51/static/bigfile 16384 100ms
2021/02/01 22:36:19 0/2097152
2021/02/01 22:36:19 3833/2097152
2021/02/01 22:36:19 20217/2097152
2021/02/01 22:36:19 36601/2097152
2021/02/01 22:36:19 52985/2097152
2021/02/01 22:36:19 69369/2097152
2021/02/01 22:36:19 85753/2097152
2021/02/01 22:36:19 102137/2097152
2021/02/01 22:36:19 118521/2097152
2021/02/01 22:36:20 134905/2097152
2021/02/01 22:36:20 151289/2097152
2021/02/01 22:36:20 167673/2097152
2021/02/01 22:36:20 184057/2097152
2021/02/01 22:36:20 200441/2097152
2021/02/01 22:36:20 216825/2097152
2021/02/01 22:36:20 233209/2097152
2021/02/01 22:36:20 249593/2097152
2021/02/01 22:36:20 265977/2097152
2021/02/01 22:36:20 282361/2097152
2021/02/01 22:36:21 298745/2097152
2021/02/01 22:36:21 315129/2097152
2021/02/01 22:36:21 331513/2097152
2021/02/01 22:36:21 347897/2097152
2021/02/01 22:36:21 364281/2097152
2021/02/01 22:36:21 380665/2097152
2021/02/01 22:36:21 397049/2097152
2021/02/01 22:36:21 413433/2097152
2021/02/01 22:36:21 429817/2097152
2021/02/01 22:36:21 446201/2097152
2021/02/01 22:36:22 462585/2097152
2021/02/01 22:36:22 478969/2097152
2021/02/01 22:36:22 495353/2097152
2021/02/01 22:36:22 511737/2097152
2021/02/01 22:36:22 528121/2097152
2021/02/01 22:36:22 544505/2097152
2021/02/01 22:36:22 560889/2097152
2021/02/01 22:36:22 577273/2097152
2021/02/01 22:36:22 593657/2097152
2021/02/01 22:36:22 610041/2097152
2021/02/01 22:36:23 626425/2097152
2021/02/01 22:36:23 642809/2097152
2021/02/01 22:36:23 659193/2097152
2021/02/01 22:36:23 675577/2097152
2021/02/01 22:36:23 691961/2097152
2021/02/01 22:36:23 708345/2097152
2021/02/01 22:36:23 724729/2097152
2021/02/01 22:36:23 741113/2097152
2021/02/01 22:36:23 757497/2097152
2021/02/01 22:36:23 773881/2097152
2021/02/01 22:36:24 790265/2097152
2021/02/01 22:36:24 806649/2097152
2021/02/01 22:36:24 823033/2097152
2021/02/01 22:36:24 839417/2097152
2021/02/01 22:36:24 855801/2097152
2021/02/01 22:36:24 872185/2097152
2021/02/01 22:36:24 888569/2097152
2021/02/01 22:36:24 904953/2097152
2021/02/01 22:36:24 921337/2097152
2021/02/01 22:36:24 937721/2097152
2021/02/01 22:36:25 954105/2097152
2021/02/01 22:36:25 970489/2097152
2021/02/01 22:36:25 986873/2097152
2021/02/01 22:36:25 1003257/2097152
2021/02/01 22:36:25 1019641/2097152
2021/02/01 22:36:25 1036025/2097152
2021/02/01 22:36:25 1052409/2097152
2021/02/01 22:36:25 1068793/2097152
2021/02/01 22:36:25 1085177/2097152
2021/02/01 22:36:26 1101561/2097152
2021/02/01 22:36:26 1117945/2097152
2021/02/01 22:36:26 1134329/2097152
2021/02/01 22:36:26 1150713/2097152
2021/02/01 22:36:26 1167097/2097152
2021/02/01 22:36:26 1183481/2097152
2021/02/01 22:36:26 1199865/2097152
2021/02/01 22:36:26 1216249/2097152
2021/02/01 22:36:26 1232633/2097152
2021/02/01 22:36:26 1249017/2097152
2021/02/01 22:36:27 1265401/2097152
2021/02/01 22:36:27 1281785/2097152
2021/02/01 22:36:27 1298169/2097152
2021/02/01 22:36:27 1314553/2097152
2021/02/01 22:36:27 1330937/2097152
2021/02/01 22:36:27 1347321/2097152
2021/02/01 22:36:27 1363705/2097152
2021/02/01 22:36:27 1380089/2097152
2021/02/01 22:36:27 1396473/2097152
2021/02/01 22:36:27 1412857/2097152
2021/02/01 22:36:28 1429241/2097152
2021/02/01 22:36:28 1445625/2097152
2021/02/01 22:36:28 1462009/2097152
2021/02/01 22:36:28 1478393/2097152
2021/02/01 22:36:28 1494777/2097152
2021/02/01 22:36:28 1511161/2097152
2021/02/01 22:36:28 1527545/2097152
2021/02/01 22:36:28 1543929/2097152
2021/02/01 22:36:28 1560313/2097152
2021/02/01 22:36:28 1576697/2097152
2021/02/01 22:36:29 1593081/2097152
2021/02/01 22:36:29 1609465/2097152
2021/02/01 22:36:29 1623737/2097152
2021/02/01 22:36:29 Read error: unexpected EOF
exit status 1
```

**Comment by linsun** [comment]
[ingressgw.log](https://github.com/istio/istio/files/5908578/ingressgw.log)

2021-02-02T03:36:03.176129Z	is a good one

2021-02-02T03:36:19.122626Z is the bad one (EOF from client) from https://github.com/istio/istio/issues/30577#issuecomment-771339235

I noticed for the bad one `[C142599]`, I don't see any errors, neither do I see `write flush complete` which is reported on `[C142589] `

**Comment by jhart1685** [comment]
To add to @linsun 's writeup. 

This recreate (simple client, rudimentary file server) is a simplified version of a real-world problem. 
We see this symptom when copying images from one Docker registry to another. If the source registry sits behind an istio ingress, the action will often fail with an EOF. If we go via a legacy nginx ingress, the problem does not occur.

Although we have seen that making small tweaks to the client (in this simple recreate) can make the problem disappear, this is not a practicable solution for the broader problem.

**Comment by jhart1685** [comment]
In case it helps - here are some client-side tcpdumps from this simplified recreate. My client was the `192.` address , server is `141.125.66.22`.
In the failing dump, the EOF in the client is observed around 15:41:12 UTC
[tcpdumps.tar.gz](https://github.com/istio/istio/files/5912438/tcpdumps.tar.gz)

**Comment by linsun** [comment]
@PiotrSikora @lambdai could you shed some light on this?  Perhaps there is some config we should use from envoy?

**Comment by lambdai** [comment]
I doesn't make sense...
My wide guess is that chunked is somehow miss matched.

``` https://golang.org/src/net/http/response.go?s=731:4298#L25
    
    // The Body is automatically dechunked if the server replied
    // with a "chunked" Transfer-Encoding.
```
Looking at envoy log

**Comment by lambdai** [comment]
Probably this: Envoy closes connection before the client confirmed all bytes are received. Envoy leaves 1 seconds for the client. 1 second is not enough at you client. From what I can see the client can reach about 160k bytes per second while there are 537k for the client to drain.
```
2021-02-02T03:36:03.308150Z	debug	envoy connection	[C142589] closing data_to_write=537815 type=2
2021-02-02T03:36:03.308162Z	debug	envoy connection	[C142589] setting delayed close timer with timeout 1000 ms
```

**Comment by lambdai** [comment]
May client side kernel buffers some data so that go client read EOF 10s later instead of 1000ms in Envoy.

You can verify if you have a tcpdump: go client is expected to reived FIN once ~2000K bytes are transported from envoy to go client. I believe in the corrupt case, a FIN or reset is sent to go client much earlier.

**Comment by linsun** [comment]
Thank you @lambdai for looking at this!   The tcp dump is captured https://github.com/istio/istio/issues/30577#issuecomment-771734086.  I'm no expert for reading it, but I did see in the failed case, the server (ingress gw) sends  FIN, PSH and ACK to the client at around 1700k bytes are transported.

**Comment by lambdai** [comment]
Oh, great 1700K is definitely smaller than expected.  
Another proof is that there is no alert record (close_notify), but I forgot if TLS 1.3 encapsulate close_notify in plain text record....

I will look into the Envoy early close behavior. As a workaround, 
At go client use http1.1 protocol or add `keep-alive` in http request header: so by default Envoy won't close connection early.
Or use http2 :) 


Pasted the tcp packets here.
```
"No.","Time","Source","Destination","Protocol","Length","Info"
"1","2021-02-02 15:41:02.214774","192.168.188.61","141.125.66.22","TCP","78","51647  >  443 [SYN] Seq=0 Win=65535 Len=0 MSS=1460 WS=64 TSval=696983416 TSecr=0 SACK_PERM=1"
"2","2021-02-02 15:41:02.229233","141.125.66.22","192.168.188.61","TCP","74","443  >  51647 [SYN, ACK] Seq=0 Ack=1 Win=65535 Len=0 MSS=1440 SACK_PERM=1 TSval=3168357234 TSecr=696983416 WS=512"
"2006","2021-02-02 15:41:12.132945","141.125.66.22","192.168.188.61","TCP","846","443  >  51647 [FIN, PSH, ACK] Seq=1751716 Ack=623 Win=68096 Len=780 TSval=3168367108 TSecr=696992900 [TCP segment of a reassembled PDU]"
"2012","2021-02-02 15:41:13.489302","192.168.188.61","141.125.66.22","TCP","66","51647  >  443 [FIN, ACK] Seq=647 Ack=1752497 Win=188480 Len=0 TSval=696994279 TSecr=3168367108"
"2013","2021-02-02 15:41:13.501064","141.125.66.22","192.168.188.61","TCP","60","443  >  51647 [RST] Seq=1752497 Win=0 Len=0"
"2014","2021-02-02 15:41:13.501066","141.125.66.22","192.168.188.61","TCP","60","443  >  51647 [RST] Seq=1752497 Win=0 Len=0"
```

**Comment by linsun** [comment]
@lambdai thanks again for your insight!

@jhart1685, can you please advise if the workaround mentioned by @lambdai in https://github.com/istio/istio/issues/30577#issuecomment-772147077 is reasonable for your client?

**Comment by jhart1685** [comment]
@lambdai - Thanks for all the investigation so far! I have some observations:

- The client in the simple recreate (failing case) is using http1.1 , this is the default for Golang http clients.
- Based on your analysis, I did some more searching, and found this [comment in the Golang http code](https://github.com/golang/go/blob/master/src/net/http/transport.go#L277-L282) , which explains why some client configs are not upgrading to http2.
- I then ran the scenario again with `GODEBUG=http2debug=2` - to dump out verbose logging if anything ends up being http2 client side.
  - Sure enough, commenting out line 28 in the client allows it to upgrade to http2.
  - Alternatively, adding `ForceAttemptHTTP2:   true,` to the Transport definition, will allow it to use http2.
  - In this mode, I cannot recreate the failure.
- So, this does look like something that only manifests in Envoy with http1.1.
  - BUT - if you go back to Lin's original description, commenting out line 30 in the client also "fixes it". This is a different dimension to the problem. In this case, the client is still using http1.1 , but with keepalives disabled.

Using http2 does workaround the problem, but as per my earlier [comment](https://github.com/istio/istio/issues/30577#issuecomment-771544631) , this doesn't really help us in our broader scenario - due to the large and varied number of clients interacting with our service.

**Comment by jhart1685** [comment]
Following on from my previous comment - went researching early close behaviour in Envoy, and discovered the `delayed_close_timeout` option on the HttpConnectionManager. (Which defaults to 1 second).

I found that disabling this , as per the EnvoyFilter below , fixes the problem.
Question: Is this a sensible workaround? It seems a bit of a blunt instrument, and probably has consequences I haven't considered.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: delayedclose
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          delayed_close_timeout: 0s
```
