### ISSUE TITLE
Istio egress gateway with SNI-proxy with routing settings in one namespace seems to be applying for other namespaces as well

### ISSUE THREAD

**Issue by kirankumar15** [istio/istio#30574]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
I have followed the steps mentioned here https://istio.io/latest/docs/tasks/traffic-management/egress/wildcard-egress-hosts/#wildcard-configuration-for-arbitrary-domains to deploy egress gateway and route https traffic for wildcard domains in one namespace, say **dev**.
**Steps to reproduce the bug**
Install istio with egress gateway by following steps mentioned here https://istio.io/latest/docs/tasks/traffic-management/egress/wildcard-egress-hosts/#wildcard-configuration-for-arbitrary-domains
Below is the IstioOperator template used:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  values:
    global:
      configValidation: true
      proxy:
        autoInject: enabled
    gateways:
      istio-egressgateway:
        runAsRoot: true
      istio-ingressgateway:
        runAsRoot: true
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          overlays:
            - kind: Service
              name: istio-ingressgateway
              patches:
                - path: spec.ports[80]
                  value:
                    name: grpc-port
                    port: 9000
                    protocol: TCP
                    targetPort: 9000
                - path: spec.ports[90]
                  value:
                    name: http-health
                    port: 9001
                    protocol: TCP
                    targetPort: 9001
    egressGateways:
      - name: istio-egressgateway-with-sni-proxy
        enabled: true
        label:
          app: istio-egressgateway-with-sni-proxy
          istio: egressgateway-with-sni-proxy
        k8s:
          service:
            ports:
            - port: 443
              name: https
          overlays:
          - kind: Deployment
            name: istio-egressgateway-with-sni-proxy
            patches:
            - path: spec.template.spec.containers[-1]
              value: |
                name: sni-proxy
                image: nginx
                resources:
                  limits:
                    cpu: "2"
                    memory: 1Gi
                  requests:
                    cpu: 100m
                    memory: 128Mi
                volumeMounts:
                - name: sni-proxy-config
                  mountPath: /etc/nginx
                  readOnly: true
                securityContext:
                  runAsNonRoot: false
                  runAsUser: 0
            - path: spec.template.spec.volumes[-1]
              value: |
                name: sni-proxy-config
                configMap:
                  name: egress-sni-proxy-configmap
                  defaultMode: 292 # 0444
```
Install all the components required for istio to route traffic via egress gateway only in the dev namespace, below are the manifests: 

```
kubectl apply -n dev -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: sni-proxy
spec:
  hosts:
  - sni-proxy.local
  location: MESH_EXTERNAL
  ports:
  - number: 8443
    name: tcp
    protocol: TCP
  resolution: STATIC
  endpoints:
  - address: 127.0.0.1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: disable-mtls-for-sni-proxy
spec:
  host: sni-proxy.local
  trafficPolicy:
    tls:
      mode: DISABLE
EOF

cat <<EOF | kubectl -n dev create -f -
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: wikipedia
spec:
  hosts:
  - "*.org"
  - "*.com"
  - "*.net"
  - "*.io"
  ports:
  - number: 443
    name: tls
    protocol: TLS
EOF

kubectl apply -n dev -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway-with-sni-proxy
spec:
  selector:
    istio: egressgateway-with-sni-proxy
  servers:
  - port:
      number: 443
      name: tls-egress
      protocol: TLS
    hosts:
    - "*.org"
    - "*.com"
    - "*.net"
    - "*.io"
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-wikipedia
spec:
  host: istio-egressgateway-with-sni-proxy.istio-system.svc.cluster.local
  subsets:
    - name: wikipedia
      trafficPolicy:
        loadBalancer:
          simple: ROUND_ROBIN
        portLevelSettings:
        - port:
            number: 443
          tls:
            mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-wikipedia-through-egress-gateway
spec:
  hosts:
  - "*.org"
  - "*.com"
  - "*.net"
  - "*.io"
  gateways:
  - mesh
  - istio-egressgateway-with-sni-proxy
  tls:
  - match:
    - gateways:
      - mesh
      port: 443
      sniHosts:
      - "*.org"
      - "*.com"
      - "*.net"
      - "*.io"
    route:
    - destination:
        host: istio-egressgateway-with-sni-proxy.istio-system.svc.cluster.local
        subset: wikipedia
        port:
          number: 443
      weight: 100
  tcp:
  - match:
    - gateways:
      - istio-egressgateway-with-sni-proxy
      port: 443
    route:
    - destination:
        host: sni-proxy.local
        port:
          number: 8443
      weight: 100
---
# The following filter is used to forward the original SNI (sent by the application) as the SNI of the
# mutual TLS connection.
# The forwarded SNI will be will be used to enforce policies based on the original SNI value.
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: forward-downstream-sni
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: SIDECAR_OUTBOUND
      listener:
        portNumber: 443
        filterChain:
          filter:
            name: istio.stats
    patch:
      operation: INSERT_BEFORE
      value:
         name: forward_downstream_sni
         config: {}
EOF
```

Launching a pod in dev namespace works as expected and I am able to see the logs in egress-gateway sni-proxy pod. 

**Now when I create a pod in another namespace and try to access any https endpoint, it fails.** 

If I want the https traffic to work in the another namespace, then I will have to add all the above resources there to route traffic via egress gateway. 

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
$ istioctl version --remote
client version: 1.7.4
control plane version: 1.8.1
data plane version: 1.8.1 (49 proxies)`
```
```
$ kubectl version --short
Client Version: v1.19.3
Server Version: v1.18.9-eks-d1db3c
```
**How was Istio installed?**
istio was installed using istioctl
**Environment where the bug was observed (cloud vendor, OS, etc)**
on Amazon EKS 1.18
Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
