### ISSUE TITLE
Envoy masking client IP

### ISSUE THREAD

**Issue by Stono** [istio/istio#3059]
Hey, 
I am using `ingress-nginx` in my cluster, however it seems to be seeing all incoming requests from the client ip of `127.0.0.1`

```
127.0.0.1 - [127.0.0.1] - - [01/Feb/2018:16:38:25 +0000]
```

I've double checked my service, and it's set to `externalTrafficPolicy: Local` which should [preserve the client ip](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip) but it is not.

I tested removing envoy and just using ingress-nginx alone, and the client ip is correct, therefore it leads me to believe that for whatever reason, we're losing that information because of envoy.

Looking in the istio-proxy logs, it also shows 127.0.0.1:

```
[2018-02-01T16:49:52.335Z] "GET / HTTP/1.1" 200 - 0 116763 251 246 "127.0.0.1"
```

We use `ingress-nginx` for modsecurity/openwaf, so knowing that client ip is very important!  Any tips as to how we can get envoy to preserve it?

For context, we're on GKE, kubernetes 1.8.6 and istio 0.4.0

**Comment by andraxylia** [comment]
I am confused, do you use both ingress-nginx and envoy for ingress?

**Comment by Stono** [comment]
Hola.
I want to use nginx ingress as my public (external) service, IE the
entrypoint to the mesh. So it acts as my ingress controller.  We do not use
the istio ingress controller.

We inject the side car into the istio ingress pod because we use mtls
enabled, so it needs to speak to services within the mesh using mtls.

This works perfectly, all expect the client IP being lost.

**Comment by Stono** [comment]
Perhaps this explains it better.
In summary we have multiple ingresses for different sources of ingress.

![service mesh](https://user-images.githubusercontent.com/1486729/35728660-39656fba-0804-11e8-938a-da345e746c82.png)

**Comment by sakshigoel12** [comment]
@nmittler please could you work with Karl on this.

**Comment by nmittler** [comment]
FYI @PiotrSikora @ZackButcher 

@Stono could you provide details about how you're configuring the sidecar for ingress?

**Comment by Stono** [comment]
https://github.com/istio/istio/issues/3099 check on there for the yaml for my ingress controller ! Thanks

**Comment by nmittler** [comment]
@Stono thanks!

Just to clarify, the configuration is located here: https://github.com/istio/istio/issues/3099#issuecomment-363679103

**Comment by Stono** [comment]
Hey @nmittler - just wondering if you've had any progress with this? 
We're actively looking at modsecurity with nginx as part of our security strategy and a key part of this is getting the correct client IP!

**Comment by nmittler** [comment]
Hey @Stono, Sorry for the delay ... I've been trying to recreate the problem with a simplified nginx config on minikube, but haven't had any luck yet. I was generating the istio-proxy config with:

```
istioctl kube-inject -f kubernetes/nginx_basic.yaml
```

I might try moving the environment to GKE to make the environment more similar.

**Comment by Stono** [comment]
That's probably a good idea.  I will email you my exact manifests when I get into the office

**Comment by nmittler** [comment]
I've been trying to replicate the environment on GKE and have had some success.  Getting 404's but I'm still able to see the localhost issue.

Here's the **nginx** log entry:

```
127.0.0.1 - [127.0.0.1] - - [13/Feb/2018:23:11:34 +0000] "GET / HTTP/1.1" 404 0 "-" "Mozilla/5.0 zgrab/0.x" 112 0.002 [upstream-default-backend] 10.40.3.47:8080 0 0.002 404
```

In the **istio-proxy** log, I see 2 entries:

```
[2018-02-13T20:11:26.679Z] "GET /productpage HTTP/1.1" 404 NR 0 0 1 - "127.0.0.1" "curl/7.58.0" "67268b90-3df2-9672-ac9f-12161d4deaf2" "104.154.191.248" "-"
[2018-02-13T20:11:26.654Z] "GET /productpage HTTP/1.1" 404 - 0 0 32 2 "-" "curl/7.58.0" "67268b90-3df2-9672-ac9f-12161d4deaf2" "104.154.191.248" "127.0.0.1:80"
```

Since nginx is seeing localhost, it seems that the inbound request might be first handled by the isto-proxy ... so the request would look like:

```
<client> --- HTTP --- [ <sidecar><NGINX><sidecar> --- HTTP-over-mTLS --- <sidecar><backend> ]
```
@costinm any thoughts?

**Comment by costinm** [comment]
Injecting istio sidecar into nginx is likely to be the cause - and it may cause other problems as well. By default istio adds an iptables initializer, which intercepts the incoming traffic in envoy, forwards to nginx, which forwards back to sidecar for outbound mtls and telemetry/etc.

I think you need a custom iptables config (we will need to add some flags to initializer), to not intercept incoming traffic on 80 and 443. Then traffic will go to nginx directly, which will forward to sidecar where mTLS will be added.

**Comment by nmittler** [comment]
@Stono can you confirm that you're seeing 2 istio-proxy logs, like I am in https://github.com/istio/istio/issues/3059#issuecomment-365439442? If not, perhaps my environment isn't quite the same. If it is, then the fix for #3469 is probably the solution.

**Comment by Stono** [comment]
Hey @nmittler,
That definitely feels like the solution to the problem, and what we were trying to achieve by doing `-i 10.194.0.0/15,10.192.0.0/20` on the `proxy_init` container and also `auth.istio.io/80: NONE` and `auth.istio.io/443: NONE` on the nginx service.

I only see **one** log in `istio-proxy`, unless I remove the `auth.istio.io/80: NONE`, and then I do see the inbound request in `istio-proxy` too.

Ultimately #3469 would allow people to use their own ingress controllers properly, and would be a great addition to istio.

**Comment by nmittler** [comment]
@Stono ok great.  I'm going to take @costinm's suggestion and try to cook up a fix locally.  Will post my findings.

**Comment by Stono** [comment]
OK great, if there's anything I can do to aide testing let me know

**Comment by nmittler** [comment]
Quick update....

I've published a [test build of istio-proxy](https://pantheon.corp.google.com/gcr/images/nathanmittler-istio-test/GLOBAL/proxy?project=nathanmittler-istio-test&organizationId=433637338589&gcrImageListsize=50) that enables root so that we can play with iptables on the pod.

I've then manually injected the sidecar into my nginx deployment with:

```shell
istioctl kube-inject -f nginx.yaml
```
Then I tweaked the generated yaml:

- Use my test proxy image
- enable root access to the istio-proxy container

My file ended up looking like this:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nginx-ingress-controller
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-nginx
  strategy: {}
  template:
    metadata:
      annotations:
        prometheus.io/port: "10254"
        prometheus.io/scrape: "true"
        # Don't auto-inject another sidecar
        sidecar.istio.io/inject: "false"
        sidecar.istio.io/status: '{"version":"6abbe7c7c508e6dcbd844f45653076c0506b2bb092ac9354362b8dc696129258","initContainers":["istio-init","enable-core-dump"],"containers":["istio-proxy"],"volumes":["istio-envoy","istio-certs"]}'
      creationTimestamp: null
      labels:
        app: ingress-nginx
    spec:
      containers:
      - args:
        - /nginx-ingress-controller
        - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
        - --configmap=$(POD_NAMESPACE)/nginx-configuration
        - --tcp-services-configmap=$(POD_NAMESPACE)/tcp-services
        - --udp-services-configmap=$(POD_NAMESPACE)/udp-services
        - --publish-service=$(POD_NAMESPACE)/ingress-nginx
        - --annotations-prefix=nginx.ingress.kubernetes.io
        - --ingress-class=nginx-external
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.10.2
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: nginx-ingress-controller
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
      - args:
        - proxy
        - sidecar
        - --configPath
        - /etc/istio/proxy
        - --binaryPath
        - /usr/local/bin/envoy
        - --serviceCluster
        - ingress-nginx
        - --drainDuration
        - 2s
        - --parentShutdownDuration
        - 3s
        - --discoveryAddress
        - istio-pilot.istio-system:15003
        - --discoveryRefreshDelay
        - 1s
        - --zipkinAddress
        - zipkin.istio-system:9411
        - --connectTimeout
        - 1s
        - --statsdUdpAddress
        - istio-mixer.istio-system:9125
        - --proxyAdminPort
        - "15000"
        - --controlPlaneAuthPolicy
        - MUTUAL_TLS
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: gcr.io/nathanmittler-istio-test/proxy
        imagePullPolicy: IfNotPresent
        name: istio-proxy
        resources: {}
        securityContext:
          # Allow debugging
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
          # readOnlyRootFilesystem: true
          #runAsUser: 1337
          runAsUser: 0
        volumeMounts:
        - mountPath: /etc/istio/proxy
          name: istio-envoy
        - mountPath: /etc/certs/
          name: istio-certs
          readOnly: false
      initContainers:
      - args:
        - -p
        - "15001"
        - -u
        #- "1337"
        - "0"
        image: docker.io/istio/proxy_init:0.5.0
        imagePullPolicy: IfNotPresent
        name: istio-init
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
      - args:
        - -c
        - sysctl -w kernel.core_pattern=/etc/istio/proxy/core.%e.%p.%t && ulimit -c
          unlimited
        command:
        - /bin/sh
        image: alpine
        imagePullPolicy: IfNotPresent
        name: enable-core-dump
        resources: {}
        securityContext:
          privileged: true
      serviceAccountName: nginx-ingress-serviceaccount
      volumes:
      - emptyDir:
          medium: Memory
        name: istio-envoy
      - name: istio-certs
        secret:
          optional: true
          secretName: istio.nginx-ingress-serviceaccount
status: {}

```

Now when I exec into the istio-proxy pod on the nginx node, I can run `iptables-save`:

```
root@nginx-ingress-controller-57b9cf8cdc-lfdpg:/# iptables-save
# Generated by iptables-save v1.6.0 on Wed Feb 14 21:21:50 2018
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [31:1860]
:OUTPUT ACCEPT [234:19931]
:POSTROUTING ACCEPT [236:20051]
:ISTIO_OUTPUT - [0:0]
:ISTIO_REDIRECT - [0:0]
-A PREROUTING -m comment --comment "istio/install-istio-prerouting" -j ISTIO_REDIRECT
-A OUTPUT -p tcp -m comment --comment "istio/install-istio-output" -j ISTIO_OUTPUT
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m comment --comment "istio/redirect-implicit-loopback" -j ISTIO_REDIRECT
-A ISTIO_OUTPUT -m owner --uid-owner 0 -m comment --comment "istio/bypass-envoy" -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -m comment --comment "istio/bypass-explicit-loopback" -j RETURN
-A ISTIO_OUTPUT -m comment --comment "istio/redirect-default-outbound" -j ISTIO_REDIRECT
-A ISTIO_REDIRECT -p tcp -m comment --comment "istio/redirect-to-envoy-port" -j REDIRECT --to-ports 15001
COMMIT
# Completed on Wed Feb 14 21:21:50 2018
# Generated by iptables-save v1.6.0 on Wed Feb 14 21:21:50 2018
*mangle
:PREROUTING ACCEPT [7524:7966471]
:INPUT ACCEPT [7524:7966471]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [33726:3738837]
:POSTROUTING ACCEPT [33726:3738837]
COMMIT
# Completed on Wed Feb 14 21:21:50 2018
# Generated by iptables-save v1.6.0 on Wed Feb 14 21:21:50 2018
*filter
:INPUT ACCEPT [7524:7966471]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [33726:3738837]
COMMIT
# Completed on Wed Feb 14 21:21:50 2018
```

That's as far as I've managed to get today (meetings and other fires) ... next step is to play around with iptables to see if we can make the istio-proxy only engage on the mesh side.

@Stono if you have some time, perhaps you can play around with it as well.
