### ISSUE TITLE
Sidecar worker threads: unable to set the value to 0

### ISSUE THREAD

**Issue by binc75** [istio/istio#30618]
**Bug description**
We want to set the istio-proxy sidecar concurrency to 0. Currently the default value is 2. 
If we change the value in the istio ConfigMap to any value greater than 0 we see the value applied in the envoy arguments.
If the value is 0 the argument passed to envoy is 2.

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
We expect that if the value in this configMap is 0 the parameter is passed to envoy.
```
$ k get cm -n istio-system istio -o yaml
apiVersion: v1
data:
  mesh: |-
    accessLogFile: /dev/stdout
    defaultConfig:
      concurrency: 0                                                          <<<-----------------
      discoveryAddress: istiod.istio-system.svc:15012
      proxyMetadata:
        DNS_AGENT: ""
      tracing:
        zipkin:
          address: jaeger-collector.platform:9411
          ....
          ....
```

**Steps to reproduce the bug**
Edit the istio ConfigMap and set `concurrency` to **0**, bring up a pod with a sidecar and run:
`kubectl get pods  <NEWPOD> -o yaml | grep concurr -A1`
you will see that the value still **2**

Do the same with the value **3** or **1** and you will see that in this case the value is taken in consideration.

**Version** 
*Istio:*
client version: 1.8.2
control plane version: 1.8.2
data plane version: 1.8.2 (253 proxies)
*K8S*
Client Version: v1.18.0
Server Version: v1.17.14-gke.1600
*HELM*
v3.3.4+ga61ce56

**How was Istio installed?**
Installed via HELM charts

**Environment where the bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by SpecialYang** [comment]
If concurrency is 0 and role type is sidecar, it will automatically set concurrency based on CPU requests/limits for sidecars. What is CPU requests/limits of your sidecar?

**Comment by binc75** [comment]
@SpecialYang if I apply this manifest:
```
apiVersion: v1
kind: Pod
metadata: 
  name: nb-test
  annotations: 
    sidecar.istio.io/inject: "true"
spec:
  containers:
  - name: nb-test
    image: nbianchi/pywebapp
    resources:
      limits:
        cpu: "0.5"
        memory: "500Mi"
      requests:
        cpu: "0.5"
        memory: "500Mi"
```

The output of this command `kubectl get pods  nb-test -o yaml | grep concurr -A1` is:
```
    - --concurrency
    - "2"
```

I would anyway expect the parameter to be passed to envoy to be **0**, since in the configmap that's the value.

**Comment by esnible** [comment]
While troubleshooting this I became confused.  I wanted to see what would happen if I specified concurrency at install time, like this:

```
$ istioctl manifest generate --set values.global.proxy.concurrency=1
Error: unknown field "concurrency" in v1alpha1.ProxyConfig
```

I see `concurrency` at https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/ .  I tested with Istio 1.6.x and I was able to set it and make a difference in the output of `manifest generate`.  `--set values.global.proxy.concurrency=1` doesn't work in Istio 1.7.x.  Did it move?

**Comment by noah8713** [comment]
With (istio 1.7+) its part of meshConfig.defaultConfig.concurrency or via custom args using k8s overlay in operator as below:
```
 kind: Deployment
            name: istio-ingressgateway
            patches:
              # Over-ride concurrency
              - path: spec.template.spec.containers.[name:istio-proxy].args.[-1]
                value: "--concurrency=<any number>"
```
Ref : https://github.com/istio/istio/pull/30147  as we ran into same issue
