### ISSUE TITLE
Need analyzer for conflicting namespace level resources

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30626]
For example:
```yaml
apiVersion: v1
items:
- apiVersion: security.istio.io/v1beta1
  kind: PeerAuthentication
  metadata:
    name: default
    namespace: istio-system
  spec:
    mtls:
      mode: STRICT
- apiVersion: security.istio.io/v1beta1
  kind: PeerAuthentication
  metadata:
    name: default2
    namespace: istio-system
  spec:
    mtls:
      mode: DISABLE
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

One will be ignored. This applies to many types, not just PeerAuthentication - we have one just for sidecar in https://preliminary.istio.io/latest/docs/reference/config/analysis/ist0111/

**Comment by esnible** [comment]
Can you help me out with a list of the types the analyzer would check for conflicts?

Briefly looking at our docs, it looks like we should report on multiple
- security.istio.io/v1beta1/AuthorizationPolicy
- security.istio.io/v1beta1/PeerAuthentication
- security.istio.io/v1beta1/RequestAuthentication
- networking.istio.io/v1alpha3/Sidecar (already checked)

... when they are in the same namespace and have the same `spec.selector`.

**Comment by howardjohn** [comment]
Also destination rule now allows namespace level defaults by omitting
hostname. This was added yesterday.

**Comment by esnible** [comment]
Looking at the implementation of IST0111 it only reports clashes if the workload is empty for two sidecars, but doesn't notice if two non-empty workloads select the same pod.

I propose retiring IST0111 and replacing it with a more general version.  We'll need a new analysis message, for example:

```
Warning: [IST01XX] (Sidecar mysidecar.default) More than one Sidecar in namespace "default" for workload "app=httpbin,version=v1": [ mysidecar.default, yoursidecar.default]
```

This would replace 0111 and be more general.

``` yaml
description: "Multiple specifiers of the same kind in a namespace select the same workload."
template: "More than one %s in namespace %q for workload %q: %v
args:
    - name: kind
    - type: string
    - name: namespace
    - type: string
    - name: workloadSelector
      type: string
    - name: conflictingCRs
      type: "[]string"
```
