### ISSUE TITLE
pilot/istiod podAntiAffinityTermLabelSelector is not respected on IstioOperator

### ISSUE THREAD

**Issue by omerfsen** [istio/istio#30655]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

pilot/istiod podAntiAffinityTermLabelSelector is not respected on IstioOperator

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

I want istiod to run on different nodes 

**Steps to reproduce the bug**
I install Istio with following IsitioOperator values but created deployment (istiod) does not have any  podAntiAffinity rules created.

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  addonComponents:
    istiocoredns:
      enabled: false
  components:
    base:
      enabled: true
    cni:
      enabled: false
    egressGateways:
    - enabled: false
      k8s:
....

pilot:
  appNamespaces: []
  autoscaleEnabled: true
  autoscaleMax: 5
  autoscaleMin: 2
  configMap: true
  configNamespace: istio-config
  cpu:
    targetAverageUtilization: 80
  enableProtocolSniffingForInbound: true
  enableProtocolSniffingForOutbound: true
  env: {}
  image: pilot
  keepaliveMaxServerConnectionAge: 30m
  nodeSelector:
    agentpool: service
  podAntiAffinityLabelSelector: []
  podAntiAffinityTermLabelSelector:
    - key: app
      operator: In
      values: istiod
      topologyKey: kubernetes.io/hostname
  policy:
    enabled: false
  replicaCount: 2
  tolerations: []
  traceSampling: 1
```

**yq e .spec.values.pilot  custom-istio-profile.yml**  
```yaml

appNamespaces: []
autoscaleEnabled: true
autoscaleMax: 5
autoscaleMin: 2
configMap: true
configNamespace: istio-config
cpu:
  targetAverageUtilization: 80
enableProtocolSniffingForInbound: true
enableProtocolSniffingForOutbound: true
env: {}
image: pilot
keepaliveMaxServerConnectionAge: 30m
nodeSelector:
  agentpool: service
podAntiAffinityLabelSelector: []
podAntiAffinityTermLabelSelector:
  - key: app
    operator: In
    values: istiod
    topologyKey: kubernetes.io/hostname
policy:
  enabled: false
replicaCount: 2
tolerations: []
traceSampling: 1
```

I did the same for istio-ingressgateway but corresponding deployment has  podAntiAffinity in deployment specs so it is only for istiod 

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

1.7.7 

**How was Istio installed?**
IstioOperator

**Environment where the bug was observed (cloud vendor, OS, etc)**
ALL 

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
