### ISSUE TITLE
Istio Ingress respecting some route rules and not others.

### ISSUE THREAD

**Issue by nmnellis** [istio/istio#3067]
Istio 0.4.0 and Kubernetes 1.8.6.
We have multiple apps under the same url `example.com` and use path routing to hit the correct service. We also chop off the application name from the path when it reaches its destination. Ex. `example.com/app1/health` would route to `app1.ns1.svc.cluster.local/health` but in some instances it wouldn't honor the route rule and would instead route to `app1.ns1.svc.cluster.local/app1/health`. This happens to multiple applications but changes which routes are affected every time an update is made to the ingress or route rules within the cluster. 

example ingress
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: app1-ingress
  namespace: ns1
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: app1
          servicePort: 80
        path: /app1/.*
```
Example route rule
```yaml
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: app1
  namespace: ns1
spec:
  destination:
    name: app1
  match:
    request:
      headers:
        uri:
          prefix: /app1/
  rewrite:
    uri: /  
```
response from app1 `http://example.com/app1/info` .. we should have gotten the infor response not 404
```json
{
"timestamp": 1517495357726,
"status": 404,
"error": "Not Found",
"message": "No message available",
"path": "/app1/info"
}
```
Ingress /routes response
```json
{
	"version_info": "hash_5652f7f64d6507e2",
	"route_config_name": "80",
	"cluster_name": "rds",
	"route_table_dump": {
		"name": "80",
		"virtual_hosts": [{
			"name": "example.com",
			"domains": ["example.com", "example.com:80"],
			"routes": [ {
				"match": {
					"prefix": "/app1/"
				},
				"route": {
					"cluster": "out.app1.ns1.svc.cluster.local|http",
					"timeout": "0s"
				},
				"metadata": {
					"filter_metadata": {
						"envoy.router": {
							"destination.service": "app1.ns1.svc.cluster.local",
							"mixer_check": "on",
							"mixer_report": "on",
							"mixer_forward": "on"
						}
					}
				},
				"decorator": {
					"operation": "default-route"
				}
			}, {
				"match": {
					"prefix": "/app1/"
				},
				"route": {
					"cluster": "out.app1.ns1.svc.cluster.local|http",
					"prefix_rewrite": "/",
					"timeout": "0s"
				},
				"metadata": {
					"filter_metadata": {
						"envoy.router": {
							"destination.service": "app1.ns1.svc.cluster.local",
							"mixer_check": "on",
							"mixer_report": "on",
							"mixer_forward": "on"
						}
					}
				},
				"decorator": {
					"operation": "app1"
				}
			}]
		}]
	}
}
```
