### ISSUE TITLE
istio 1.8.2 ingress gateway - SSL_ERROR_SYSCALL in connection to

### ISSUE THREAD

**Issue by arief-hidayat** [istio/istio#30685]
**Bug description**

I am trying to upgrade from 1.7.3 to 1.8.2. However, I tried spliting istioOperator CR for gateway & control-plane. Trying to follow this https://istio.io/latest/docs/setup/upgrade/gateways/.

istio ingress gateway expose HTTPS endpoint where TLS cert is provided by cert-manager (lets encrypt).
```
  spec:
    selector:
      istio: ingressgateway
    servers:
    - hosts:
      - '*'
      port:
        name: https-igw
        number: 443
        protocol: HTTPS
      tls:
        credentialName: my-cert
        mode: SIMPLE
```
cert
```
  apiVersion: cert-manager.io/v1beta1
  kind: Certificate
  metadata:
    name: aicore-cert
    namespace: istio-system
  spec:
    dnsNames:
    - '*.xxx.mydomain.com'
    - '*.yyy.mydomain.com'
    issuerRef:
      kind: ClusterIssuer
      name: letsencrypt-staging-dns
    secretName: my-cert
```
`my-cert` looks fine. I can see tls.key & tls.crt populated by cert-manager.

I am not sure if I missed some configuration or there's change in behaviour. But when calling https://blabla.xxx.mydomain.com, I get 
```
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to blabla.xxx.mydomain.com:443
```

Could you please help me finding the root cause?
I tried many things, such as setting ISTIOD_ENABLE_SDS_SERVER or PILOT_SIDECAR_ENABLE_INBOUND_TLS_V2, enabling debug log, etc.

[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[x ] Upgrade

**Expected behavior**

endpoint should be accessible

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.8.2

**How was Istio installed?**
via operator

**Environment where the bug was observed (cloud vendor, OS, etc)**
Gardener Kubernetes 1.16 (on top of AWS)

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
