### ISSUE TITLE
Ingress gateway - configure k8s terminationGracePeriodSeconds

### ISSUE THREAD

**Issue by ediezh** [istio/istio#30709]
**Describe the feature request**

Is there a way to configure terminationGracePeriodSeconds for the ingress gateway pods in IstioOperator? We have some services that require a longer draining duration. We can configure the draining duration in the proxy config, but the ingress gateway pods still have the default 30s termination grace period.

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by morvencao** [comment]
This can be achieved by the k8s overlay:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
    - namespace: istio-system
      name: istio-ingressgateway
      enabled: true
      k8s:
        overlays:
        - kind: Deployment
          name: istio-ingressgateway
          patches:
          - path: spec.template.spec.terminationGracePeriodSeconds
            value: 60 # OVERRIDDEN
```
