### ISSUE TITLE
XDS_UPSTREAM doesn't work in user gateway

### ISSUE THREAD

**Issue by infa-ddeore** [istio/istio#30718]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
as per https://istio.io/v1.7/docs/reference/commands/pilot-agent/#envvars setting `XDS_UPSTREAM` variable doesn't work, meaning the discovery address doesn't change, user gateway logs show the default service address (istiod.istio-system) as `discoveryAddress`

**Affected product area (please put an X in all that apply)**

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
`discoveryAddress` should be set as per `XDS_UPSTREAM` env variable

**Steps to reproduce the bug**
1) install 1.7 istio with revision option
```
istioctl install --set revision=1-7-7
```
2) deploy user gateway with `XDS_UPSTREAM` variable pointing to `istiod-1-7-7.istio-system` (it will keep on waiting because gateway doesn't become ready)

```
cat <<EOF | istioctl manifest install -f -
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: test

spec:
  profile: empty
  components: 
    ingressGateways: 
    - name: istio-ingressgateway
      enabled: false

    - name: test-gw
      namespace: default
      enabled: true
      label: 
        istio: test-gw
        
      k8s:
        env:
        - name: XDS_UPSTREAM
          value: istiod-1-7-7.istio-system
 
        service:
          type: ClusterIP
          ports:
          - port: 80
            name: http
            targetPort: 8080
          - port: 443
            name: https
            targetPort: 8443
EOF
```

3) in another terminal, check `XDS_UPSTREAM` is set to correct value but pilot agent doesn't honor that
```
$ k describe deploy/test-gw |grep XDS_UPSTREAM
      XDS_UPSTREAM:              istiod-1-7-7.istio-system

$ k logs deploy/test-gw |grep discoveryAddress
discoveryAddress: istiod.istio-system.svc:15012
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
$ istioctl version --remote
client version: 1.6.14
istiod version: 1.6.14
istiod version: 1.7.7
pilot version: 1.5.10
data plane version: 1.7.7 (1 proxies)

$ kubectl version --short
Client Version: v1.19.3
Server Version: v1.16.0

**How was Istio installed?**
istioctl install --set revision=1-7-7

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
