### ISSUE TITLE
Operator label confusion with multiple ingress gateways

### ISSUE THREAD

**Issue by arcivanov** [istio/istio#30717]
**Bug description**

1. When creating multiple ingress gateways operator sets identical `app` labels regardless of name.
2. This produces PDBs that have confused labeling unless overwritten by hand.
3. This produces Deployments with confused deployment spec.selector. 
4. This further breaks Gateway binding for the user that used `app: ingressgateway`, then added another ingress with a different name and found that Gateway auto-binding there as well.

The only distinguishing label between the ingress gateways ends up being `service.istio.io/canonical-name`.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[X] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

Each generated Istio Ingress Gateway has at least a unique `app` label throughout all resources, producing distinct PDBs, HPAs etc and allowing gateways to be bound precisely. 

**Steps to reproduce the bug**

Install as follows. This one is on non-EKS AWS, but I presume it's irrelevant.

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: dev
spec:
  meshConfig:
    accessLogFile: /dev/stdout
  components:
    cni:
      enabled: false
    pilot:
      enabled: true
      k8s:
        hpaSpec:
          maxReplicas: 5
          minReplicas: 3
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
      k8s:
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <snip>
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
          service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
        service:
          ports:
          - name: status-port
            port: 15021
            protocol: TCP
            targetPort: 15021
          - name: http2
            port: 80
            protocol: TCP
            targetPort: 8080
          - name: https
            port: 443
            protocol: TCP
            targetPort: 8443
          - name: tls
            port: 15443
            protocol: TCP
            targetPort: 15443
        hpaSpec:
          maxReplicas: 5
          minReplicas: 3
    - enabled: true
      name: istio-cryptogateway
      k8s:
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
        service:
          ports:
          - name: status-port
            port: 15021
            protocol: TCP
            targetPort: 15021
          - name: xrp-port
            port: 51235
            protocol: TCP
            targetPort: 15235
        hpaSpec:
          maxReplicas: 5
          minReplicas: 3
```

Observe the labeling on `istio-ingressgateway`:

```
$ kubectl -n istio-system get deploy istio-ingressgateway -o yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: dev
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.8.2
    release: istio
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
  template:
      labels:
        app: istio-ingressgateway
        chart: gateways
        heritage: Tiller
        install.operator.istio.io/owning-resource: unknown
        istio: ingressgateway
        istio.io/rev: default
        operator.istio.io/component: IngressGateways
        release: istio
        service.istio.io/canonical-name: istio-ingressgateway
        service.istio.io/canonical-revision: latest
```

Observe the labeling on `istio-cryptogateway`:
```
$ kubectl -n istio-system get deploy istio-cryptogateway -o yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: dev
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.8.2
    release: istio
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
  template:
      labels:
        app: istio-ingressgateway
        chart: gateways
        heritage: Tiller
        install.operator.istio.io/owning-resource: unknown
        istio: ingressgateway
        istio.io/rev: default
        operator.istio.io/component: IngressGateways
        release: istio
        service.istio.io/canonical-name: istio-cryptogateway
        service.istio.io/canonical-revision: latest
```

Notice, that for both `istiogateway` and `cryptogateway` service labels **AND SERVICE SELECTOR LABELS** are completely identical, the `app` is identical and the only distinguishing label is `spec.template.labels["service.istio.io/canonical-name"]`

Generated PDBs are completely identical:

Default Ingress:
```
$ kubectl -n istio-system get pdb istio-ingressgateway -o yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: dev
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.8.2
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
status:
  currentHealthy: 6
  desiredHealthy: 1
  disruptionsAllowed: 5
  expectedPods: 6
  observedGeneration: 1
```

Crypto Ingress:
```
$ kubectl -n istio-system get pdb istio-cryptogateway -o yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: dev
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.8.2
    release: istio
  name: istio-cryptogateway
  namespace: istio-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
status:
  currentHealthy: 6
  desiredHealthy: 1
  disruptionsAllowed: 5
  expectedPods: 6
  observedGeneration: 1
```

Observe that healthy statuses are completely invalid due to mislabeling. K8S also agrees the situation is untenable:

```
istio-system   51m         Warning   MultiplePodDisruptionBudgets   pod/istio-ingressgateway-6788fcb955-hvpm8    Pod "istio-system"/"istio-ingressgateway-6788fcb955-hvpm8" matches multiple PodDisruptionBudgets.  Chose "istio-cryptogateway" arbitrarily.
istio-system   51m         Warning   MultiplePodDisruptionBudgets   pod/istio-ingressgateway-55499c4bf7-mswf9    Pod "istio-system"/"istio-ingressgateway-55499c4bf7-mswf9" matches multiple PodDisruptionBudgets.  Chose "istio-cryptogateway" arbitrarily.
istio-system   51m         Warning   MultiplePodDisruptionBudgets   pod/istio-ingressgateway-55499c4bf7-fc7tt    Pod "istio-system"/"istio-ingressgateway-55499c4bf7-fc7tt" matches multiple PodDisruptionBudgets.  Chose "istio-cryptogateway" arbitrarily.
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

$ istioctl version --remote
client version: 1.8.2
control plane version: 1.8.2
data plane version: 1.8.2 (70 proxies)

$ kubectl version --short
Client Version: v1.18.15
Server Version: v1.18.15

**How was Istio installed?**
Original `istioctl install` then moved to operator.

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS, Stock k8s, Ubuntu Focal 20.04.

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by arcivanov** [comment]
The PDB issue can be worked around via:

```
        podDisruptionBudget:
          selector:
            matchLabels:
              service.istio.io/canonical-name: istio-ingressgateway
```

and

```
        podDisruptionBudget:
          selector:
            matchLabels:
              service.istio.io/canonical-name: istio-cryptogateway
```

**Comment by morvencao** [comment]
Each gateway can specify the different labels, for example:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: empty
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        label:
          aaa: aaa-val
          bbb: bbb-val
        k8s:
          resources:
            requests:
              cpu: 111m
              memory: 111Mi
      - name: user-ingressgateway
        enabled: true
        label:
          ccc: ccc-val
          ddd: ddd-val
        k8s:
          resources:
            requests:
              cpu: 222m
              memory: 888Mi
```
