### ISSUE TITLE
KubernetesResourcesSpec lacks topologySpreadConstraints

### ISSUE THREAD

**Issue by arcivanov** [istio/istio#30719]
**Describe the feature request**

PodTopologySpreadConstraints are critical in ensuring high-availability. The configuration entries for `topologySpreadConstraints` in KubernetesResourcesSpec are currently unavailable.

https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/

**Describe alternatives you've considered**

Patching istiod and ingresses after every update. Extra annoying.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[x] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by donbowman** [comment]
can you use:
```
+        overlays:
+          - kind: Deployment
+            name: istio-ingressgateway
+            patches:
+              - path: spec.template.spec.topologySpreadConstraints
+                value: 
+                  - maxSkew: 1
+                    topologyKey: topology.gke.io/zone
+                    whenUnsatisfiable: ScheduleAnyway
+                    labelSelector:
+                      istio: ingressgateway
+                  - maxSkew: 1
+                    topologyKey: kubernetes.io/hostname
+                    whenUnsatisfiable: ScheduleAnyway
+                    labelSelector:
+                      istio: ingressgateway
```

**Comment by arcivanov** [comment]
Yes, I can, I do, but it's verbose. Also because of #30717 `labelSelectors` get finicky.

**Comment by arcivanov** [comment]
This issue is worked around but isn't really resolved. Can we please reopen and give it a proper disposition?

**Comment by monotek** [comment]
> +        overlays:
> +          - kind: Deployment
> +            name: istio-ingressgateway
> +            patches:
> +              - path: spec.template.spec.topologySpreadConstraints
> +                value: 
> +                  - maxSkew: 1
> +                    topologyKey: topology.gke.io/zone
> +                    whenUnsatisfiable: ScheduleAnyway
> +                    labelSelector:
> +                      istio: ingressgateway
> +                  - maxSkew: 1
> +                    topologyKey: kubernetes.io/hostname
> +                    whenUnsatisfiable: ScheduleAnyway
> +                    labelSelector:
> +                      istio: ingressgateway

matchLabels key is missing.
This should look like:
```
          overlays:
            - kind: Deployment
              name: istio-ingressgateway
              patches:
                - path: spec.template.spec.topologySpreadConstraints
                  value:
                    - maxSkew: 1
                      topologyKey: kubernetes.io/hostname
                      whenUnsatisfiable: ScheduleAnyway
                      labelSelector:
                        matchLabels:
                          istio: ingressgateway
                    - maxSkew: 1
                      topologyKey: topology.kubernetes.io/zone
                      whenUnsatisfiable: ScheduleAnyway
                      labelSelector:
                        matchLabels:
                          istio: ingressgateway
```
