### ISSUE TITLE
NPE in reconciler

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#30725]
install istio via below iop:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
spec:
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: "cluster1"
      network: "kube-network"
```
fails with `panic: assignment to entry in nil map`
