### ISSUE TITLE
Envoy can not find a cluster and answer 503 if a workload and DestinationRule/VirtualService/Gateway/ServiceEntry are defined in different namespaces

### ISSUE THREAD

**Issue by georgiiturevich-uw** [istio/istio#30730]
**Bug description**

I tried to configure Egress gateway TLS origination as described in [Istio documentation](https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/#perform-tls-origination-with-an-egress-gateway) 
with a difference that the 'sleep' deployment and required Istio resources (DestinationRule/VirtualService/Gateway/ServiceEntry) were deployed to different namespaces.

I was not able to perform an HTTP request to CNN. It responded 503 and I saw 'cannot find cluster outbound|80|cnn|istio-egressgateway.istio-system.svc.cluster.local' error message in 'sleep' istio-proxy sidecar logs.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

I expected that an HTTP-request would be passed through the Egress gateway, which would originate TLS to the CNN site as described in the documentation.

**Steps to reproduce the bug**

Install Istio
```
istioctl install --set profile=demo -y --set meshConfig.accessLogFile=/dev/stdout --set meshConfig.outboundTrafficPolicy.mode=REGISTRY_ONLY
```

Configure namespaces
```
kubectl label namespace default istio-injection=enabled
kubectl create namespace external-services
kubectl label namespace external-services istio-injection=enabled
```

Apply sleep.yaml from Istio distribution in the 'default' Kubernetes namespace
```
kubectl apply -f samples/sleep/sleep.yaml
```

Apply Istio resources to the `external-services` namespaces.
```
kubectl -n external-services apply -f  - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cnn
spec:
  hosts:
  - edition.cnn.com
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 80
      name: https-port-for-tls-origination
      protocol: HTTPS
    hosts:
    - edition.cnn.com
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-cnn
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: cnn
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 80
        tls:
          mode: ISTIO_MUTUAL
          sni: edition.cnn.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-cnn-through-egress-gateway
spec:
  hosts:
  - edition.cnn.com
  gateways:
  - istio-egressgateway
  - mesh
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: cnn
        port:
          number: 80
      weight: 100
  - match:
    - gateways:
      - istio-egressgateway
      port: 80
    route:
    - destination:
        host: edition.cnn.com
        port:
          number: 443
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-tls-for-edition-cnn-com
spec:
  host: edition.cnn.com
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE # initiates HTTPS for connections to edition.cnn.com
EOF
```

Enable debug logging in the `sleep` sidecar proxy
```
export SOURCE_POD=$(kubectl get pod -l app=sleep -o jsonpath={.items..metadata.name})
istioctl proxy-config log $SOURCE_POD --level debug
```

Send thehttp request to CNN.

```
$ kubectl exec "${SOURCE_POD}" -c sleep -- curl -sL -o /dev/null -D - http://edition.cnn.com/politics
```

I saw the following in response.
```
HTTP/1.1 503 Service Unavailable
date: Sun, 07 Feb 2021 11:49:25 GMT
server: envoy
content-length: 0
```

When I reviewed logs of istio-proxy in sleep pod
```
kubectl logs "${SOURCE_POD}" -c istio-proxy --follow
```
I saw the following messages about not found cluster.
```
2021-02-07T11:56:21.543998Z	debug	envoy filter	cannot find cluster outbound|80|cnn|istio-egressgateway.istio-system.svc.cluster.local
2021-02-07T11:56:21.544029Z	debug	envoy router	[C446][S3670754226840096868] unknown cluster 'outbound|80|cnn|istio-egressgateway.istio-system.svc.cluster.local'
2021-02-07T11:56:21.544039Z	debug	envoy http	[C446][S3670754226840096868] Sending local reply with details cluster_not_found
2021-02-07T11:56:21.544077Z	debug	envoy http	[C446][S3670754226840096868] encoding headers via codec (end_stream=true):
':status', '503'
'date', 'Sun, 07 Feb 2021 11:56:21 GMT'
'server', 'envoy'
```

When I check a list of clusters for the sleep pod, I did not find any items with the 'cnn' subset.
```
$ istioctl proxy-config cluster $SOURCE_POD 
SERVICE FQDN                                            PORT      SUBSET     DIRECTION     TYPE             DESTINATION RULE
                                                        80        -          inbound       STATIC           
BlackHoleCluster                                        -         -          -             STATIC           
InboundPassthroughClusterIpv4                           -         -          -             ORIGINAL_DST     
InboundPassthroughClusterIpv6                           -         -          -             ORIGINAL_DST     
PassthroughCluster                                      -         -          -             ORIGINAL_DST     
agent                                                   -         -          -             STATIC           
edition.cnn.com                                         80        -          outbound      STRICT_DNS       originate-tls-for-edition-cnn-com.external-services
edition.cnn.com                                         443       -          outbound      STRICT_DNS       originate-tls-for-edition-cnn-com.external-services
istio-egressgateway.istio-system.svc.cluster.local      80        -          outbound      EDS              
istio-egressgateway.istio-system.svc.cluster.local      443       -          outbound      EDS              
istio-egressgateway.istio-system.svc.cluster.local      15443     -          outbound      EDS              
istio-ingressgateway.istio-system.svc.cluster.local     80        -          outbound      EDS              
istio-ingressgateway.istio-system.svc.cluster.local     443       -          outbound      EDS              
istio-ingressgateway.istio-system.svc.cluster.local     15021     -          outbound      EDS              
istio-ingressgateway.istio-system.svc.cluster.local     15443     -          outbound      EDS              
istio-ingressgateway.istio-system.svc.cluster.local     31400     -          outbound      EDS              
istiod.istio-system.svc.cluster.local                   443       -          outbound      EDS              
istiod.istio-system.svc.cluster.local                   15010     -          outbound      EDS              
istiod.istio-system.svc.cluster.local                   15012     -          outbound      EDS              
istiod.istio-system.svc.cluster.local                   15014     -          outbound      EDS              
kube-dns.kube-system.svc.cluster.local                  53        -          outbound      EDS              
kube-dns.kube-system.svc.cluster.local                  9153      -          outbound      EDS              
kubernetes.default.svc.cluster.local                    443       -          outbound      EDS              
prometheus_stats                                        -         -          -             STATIC           
sds-grpc                                                -         -          -             STATIC           
sleep.default.svc.cluster.local                         80        -          outbound      EDS              
xds-grpc                                                -         -          -             STATIC           
zipkin                                                  -         -          -             STRICT_DNS       
```

When I deleted the sleep deployment from the default namespace and deployed it to the same `external-services` namespace 

```
kubectl delete -f samples/sleep/sleep.yaml
kubectl -n external-services apply -f samples/sleep/sleep.yaml
```
I could successfully execute an HTTP request.
```
$ export SOURCE_POD=$(kubectl -n external-services get pod -l app=sleep -o jsonpath={.items..metadata.name})
$ kubectl -n external-services exec "${SOURCE_POD}" -c sleep -- curl -sL -o /dev/null -D - http://edition.cnn.com/politics
HTTP/1.1 200 OK
content-length: 1290382
content-type: text/html; charset=utf-8
...
```

and saw a corresponding log record in istio-proxy logs
```
kubectl -n external-services logs "${SOURCE_POD}" -c istio-proxy --follow
[2021-02-07T12:00:54.733Z] "GET /politics HTTP/1.1" 200 - "-" 0 1290382 354 101 "-" "curl/7.69.1" "e8f90b33-0bdb-9a06-bc11-63ee7932ab1d" "edition.cnn.com" "10.244.1.4:8080" outbound|80|cnn|istio-egressgateway.istio-system.svc.cluster.local 10.244.1.7:46628 151.101.129.67:80 10.244.1.7:38726 - -
```

and when I checked clusters, then  items with cnn subset were in output as I expected
```
[bug-report-2021-02-08.zip](https://github.com/istio/istio/files/5943728/bug-report-2021-02-08.zip)


$ istioctl proxy-config cluster -n external-services $SOURCE_POD 

ERVICE FQDN                                            PORT      SUBSET     DIRECTION     TYPE             DESTINATION RULE
                                                        80        -          inbound       STATIC           
BlackHoleCluster                                        -         -          -             STATIC           
InboundPassthroughClusterIpv4                           -         -          -             ORIGINAL_DST     
InboundPassthroughClusterIpv6                           -         -          -             ORIGINAL_DST     
PassthroughCluster                                      -         -          -             ORIGINAL_DST     
agent                                                   -         -          -             STATIC           
edition.cnn.com                                         80        -          outbound      STRICT_DNS       originate-tls-for-edition-cnn-com.external-services
edition.cnn.com                                         443       -          outbound      STRICT_DNS       originate-tls-for-edition-cnn-com.external-services
istio-egressgateway.istio-system.svc.cluster.local      80        -          outbound      EDS              egressgateway-for-cnn.external-services
istio-egressgateway.istio-system.svc.cluster.local      443       -          outbound      EDS              egressgateway-for-cnn.external-services
istio-egressgateway.istio-system.svc.cluster.local      15443     -          outbound      EDS              egressgateway-for-cnn.external-services
istio-egressgateway.istio-system.svc.cluster.local      80        cnn        outbound      EDS              egressgateway-for-cnn.external-services
istio-egressgateway.istio-system.svc.cluster.local      443       cnn        outbound      EDS              egressgateway-for-cnn.external-services
istio-egressgateway.istio-system.svc.cluster.local      15443     cnn        outbound      EDS              egressgateway-for-cnn.external-services
istio-ingressgateway.istio-system.svc.cluster.local     80        -          outbound      EDS              
istio-ingressgateway.istio-system.svc.cluster.local     443       -          outbound      EDS              
istio-ingressgateway.istio-system.svc.cluster.local     15021     -          outbound      EDS              
istio-ingressgateway.istio-system.svc.cluster.local     15443     -          outbound      EDS              
istio-ingressgateway.istio-system.svc.cluster.local     31400     -          outbound      EDS              
istiod.istio-system.svc.cluster.local                   443       -          outbound      EDS              
istiod.istio-system.svc.cluster.local                   15010     -          outbound      EDS              
istiod.istio-system.svc.cluster.local                   15012     -          outbound      EDS              
istiod.istio-system.svc.cluster.local                   15014     -          outbound      EDS              
kube-dns.kube-system.svc.cluster.local                  53        -          outbound      EDS              
kube-dns.kube-system.svc.cluster.local                  9153      -          outbound      EDS              
kubernetes.default.svc.cluster.local                    443       -          outbound      EDS              
prometheus_stats                                        -         -          -             STATIC           
sds-grpc                                                -         -          -             STATIC           
sleep.external-services.svc.cluster.local               80        -          outbound      EDS              
xds-grpc                                                -         -          -             STATIC           
zipkin                                                  -         -          -             STRICT_DNS
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
$ istioctl version --remote
client version: 1.8.2
control plane version: 1.8.2
data plane version: 1.8.2 (3 proxies)
```

```
$ kubectl version --short
Client Version: v1.20.2
Server Version: v1.18.15
```

**How was Istio installed?**

By istioctl
```
istioctl install --set profile=demo -y --set meshConfig.accessLogFile=/dev/stdout --set meshConfig.outboundTrafficPolicy.mode=REGISTRY_ONLY
```

**Environment where the bug was observed (cloud vendor, OS, etc)**
It was reproduced locally on a Kubernetes 1.18 cluster with the `kind` tool 0.10.0 version. I also saw the same behavior on our development EKS cluster.

Bug report archive is attached.
