### ISSUE TITLE
status: analysis breaks upgrade

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30736]
```
istiod-7884b4bfbb-cwm2g discovery 2021-02-08T17:17:39.136334Z	error	klog	k8s.io/client-go@v0.19.3/tools/cache/reflector.go:156: Failed to watch *v1alpha3.VirtualService: failed to list *v1alpha3.VirtualService: v1alpha3.VirtualServiceList.ListMeta: v1.ListMeta.TypeMeta: Kind: Items: []v1alpha3.VirtualService: v1alpha3.VirtualService.Status: unmarshalerDecoder: unknown value "Error" for enum istio.analysis.v1alpha1.AnalysisMessageBase_Level, error found in #10 byte of ...|-280\""}]}}],"kind":|..., bigger context ...|inationrule not found: \"management+v1-0-280\""}]}}],"kind":"VirtualServiceList","metadata":{"contin|...[]
```

object:
```yaml
status:
  validationMessages:
  - code: IST0101
    documentation_url: https://istio.io/docs/reference/config/analysis/IST0101?ref=status-controller
    level: Error
    message: 'Referenced gateway not found: "management-gateway"'
  - code: IST0101
    documentation_url: https://istio.io/docs/reference/config/analysis/IST0101?ref=status-controller
    level: Error
    message: 'Referenced host+subset in destinationrule not found: "management+contensis-12841"'
  - code: IST0101
    documentation_url: https://istio.io/docs/reference/config/analysis/IST0101?ref=status-controller
    level: Error
    message: 'Referenced host+subset in destinationrule not found: "management+master"'
  - code: IST0101
    documentation_url: https://istio.io/docs/reference/config/analysis/IST0101?ref=status-controller
    level: Error
    message: 'Referenced host+subset in destinationrule not found: "management+v1-0-255"'
  - code: IST0101
    documentation_url: https://istio.io/docs/reference/config/analysis/IST0101?ref=status-controller
    level: Error
    message: 'Referenced host+subset in destinationrule not found: "management+v1-0-280"'
```
cc @therealmitchconnors
