### ISSUE TITLE
WASM startup times slow, scale with number of ports

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30742]
When I enabled wasm, it took ~5s to startup. I then applied a bunch of ports:
```
apiVersion: v1
kind: Service
metadata:
  name: echo
spec:
  ports:
  - name: port-25672
    port: 25672
  - name: port-4369
    port: 4369
  - name: port-4096
    port: 4096
  - name: port-5671
    port: 5671
  - name: port-35672
    port: 35672
  - name: port-35673
    port: 35673
  - name: port-35674
    port: 35674
  - name: port-35675
    port: 35675
  - name: port-35676
    port: 35676
  - name: port-35677
    port: 35677
  - name: port-35678
    port: 35678
  - name: port-35679
    port: 35679
  - name: port-35680
    port: 35680
  - name: port-35681
    port: 35681
  - name: port-35682
    port: 35682
  - name: amqp
    port: 5672
  - name: port-15672
    port: 15672
  - name: port-61614
    port: 61614
  - name: port-61613
    port: 61613
  - name: port-8883
    port: 8883
  - name: port-15674
    port: 15674
  - name: port-15675
    port: 15675
  - name: port-15692
    port: 15692
  selector:
    app: echo
```

The pod then took 14-20s to startup.

Times were recorded on master
