### ISSUE TITLE
1.8.3 generates ingress gateways, even when disabled.  1.8.2 did not

### ISSUE THREAD

**Issue by Stono** [istio/istio#30756]
**Bug description**
Templating Istio `1.8.3` using `istioctl` generates ingress gateways, despite the `istiooperator.yaml` disabling them.  The same set of values on `1.8.2` do not generate the ingress.

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  creationTimestamp:
spec:
  components:
    ...
    ingressGateways:
    egressGateways:
  meshConfig:
  ...
    ingressControllerMode: 'OFF'
  ```
