### ISSUE TITLE
kind: Sidecar returns a 502 instead of 403 when something is not allowed

### ISSUE THREAD

**Issue by ceastman-ibm** [istio/istio#30763]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
for the following yaml if your shelled into the account microservice and you try to connect to something other than google you get a 502 bad gateway error. I think it would make more sense to return a 403 forbidden status code.

```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: account
spec:
  workloadSelector:
    labels:
      app: account
  egress:
  - hosts:
    - "ondeck/www.google.com"
```

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
return a 403 forbidden instead of a 502 bad gateway when an egress is not defined in the sidecar kind resource

**Steps to reproduce the bug**

create a service entry for www.google.com, and apply the above kind:sidecar yaml
kubectl exec -it account bash
curl http://www.somethingelse.com

the curl returns a 502 bad gateway

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
istio 1.8.2

**How was Istio installed?**
ibm managed istio

**Environment where the bug was observed (cloud vendor, OS, etc)**
IBM Cloud 

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
