### ISSUE TITLE
Add headers in delegate request

### ISSUE THREAD

**Issue by arunpmohan** [istio/istio#30774]
I have the following virtual service where i would like to pass on a header for a delegate match.

Right now the headers can only be set on route destinations i believe.

This is my virtual service
```

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sample-virtual-service
spec:
  gateways:
  - shared-istio-gateway
  hosts:
  - "*"
  http:
  - headers:
      request:
        set:
          port: "8080"
  - delegate:
      name: mydelegate-vs
      namespace: mysps
    match:
    - uri:
        prefix: /services/pndservice
    - uri:
        prefix: /soap/sps/udFeNotifications
    - uri:
        prefix: /soap/notificationResponse
    - uri:
        prefix: /soap/eCommerceChargingService
    - uri:
        prefix: /nchf-proxy-request
```

This gives me an error

**Error from server: error when creating "ch1.yaml": admission webhook "validation.istio.io" denied the request: configuration is invalid: HTTP route or redirect is required**

**Comment by howardjohn** [comment]
cc @hzxuzhonghu

**Comment by arunpmohan** [comment]
is there anyway to  pass port information to the delegate virtual service from the source virtual service ?

I do not want to make the same decision i already made in source virtual service again in the delegate one.

**Comment by hzxuzhonghu** [comment]
THis is an invalid HTTPRoute 
```
  - headers:
      request:
        set:
          port: "8080"
```

Maybe what you mean is to merge this with the below route
