### ISSUE TITLE
Istioctl v1.9.0 does not allow prometheus in the value of IstioOperator option

### ISSUE THREAD

**Issue by hourglasshoro** [istio/istio#30779]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    prometheus:
      enabled: false
    prometheusOperator:
      createPrometheusResource: true
```

When I try to generate the following manifest with Istioctl v1.9.0 using the IstioOperator option, I get the following error

```unknown field "prometheus" in v1alpha1.Values```

The same is true for prometheusOperator

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

The prometheus and prometheusOperator options can be used in values.

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Istio v1.9.0

**How was Istio installed?**
istioctl command

**Environment where the bug was observed (cloud vendor, OS, etc)**
Mac OS

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
