### ISSUE TITLE
DNS service entry with multiple hosts and address defined results in strange configuration

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30771]
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: se
spec:
  addresses: [169.254.169.254]
  resolution: DNS
  hosts:
  - "httpbin.org"
  - "wikipedia.org"
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  - number: 80
    name: http
    protocol: HTTP
```

This results in a cluster for both hosts. We get a listener `169.254.169.254_443` that only forwards to the first host. We get route for HTTP that will sending to the proper hosts, but if the Host header is the IP (169.254.169.254) it will go to the first host.

if we remove the address, we are doing SNI matching and things seem to make sense.

I am not entirely sure what the correct behavior here is...
