### ISSUE TITLE
Gateway TLS mode that allows HTTPS via Host header instead of SNI

### ISSUE THREAD

**Issue by eshicks4** [istio/istio#30780]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

A TLS mode in the Gateway definition that allows HTTPS to use a generic, self-signed certificate and determine routing via the Host header the same way it does for HTTP.  This would be useful for external load balancers that don't support SNI pass-through.

**Describe alternatives you've considered**

Maintaining all SSL certificates on the Kube cluster or creating individual entries in the external LB for each and every domain. (Ours supports hard-coding SNI but not passing it through)  We can also continue using the Nginx ingress controller.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ X ] Networking
[ X ] Performance and Scalability
[ ] Extensions and Telemetry
[ X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
You can already do this. SNI matching and host matching are decoupled
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*"
    tls:
      credentialName: sds-credential
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: echo
spec:
  hosts:
  - "echo.example.com"
  gateways:
  - gateway
  http:
  - route:
    - destination:
        host: echo
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: echo
spec:
  hosts:
  - "foo.example.com"
  gateways:
  - gateway
  http:
  - route:
    - destination:
        host: foo
        port:
          number: 80
```
