### ISSUE TITLE
ServiceEndpoint does not work if stub Service is created before it

### ISSUE THREAD

**Issue by bbdimitriu** [istio/istio#30782]
**Bug description**
When defining an Istio ServiceEntry for an external API service and creating a stub K8s Service (so that the DNS name resolves in the pod), the order in which these two resources are created affects whether the ServiceEntry works at all.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
I expect that it doesn't matter in which order the Service stub and the ServiceEntry are created in order to be able to access the external service.

**Steps to reproduce the bug**
1. In my EKS cluster with an Istio mesh (not a multi-cluster mesh) I run a CLI bash pod that participates in the local mesh in order to test with `curl`.
1. I then create a stub K8s service like this:
    ```yaml
    apiVersion: v1
    kind: Service
    metadata:
      name: httpbin
    spec:
      ports:
        - protocol: TCP
          port: 8000
          targetPort: 15443
    ```
1. Then I define a ServiceEntry for an external service (that happens to be another service in a different EKS/Istio cluster, but it it NOT the same mesh) and a `DestinationRule` that forces mTLS to it.
    ```yaml
    apiVersion: networking.istio.io/v1beta1
    kind: ServiceEntry
    metadata:
      name: httpbin
    spec:
      hosts:
      - httpbin.default.svc.cluster.local
      ports:
      - number: 8000
        name: http
        protocol: HTTP
      location: MESH_EXTERNAL
      resolution: DNS
      endpoints:
      - address: <--an-external-address-of-the-service-->
        ports:
          http: 15443
    ---
    apiVersion: networking.istio.io/v1beta1
    kind: DestinationRule
    metadata:
      name: mtls-external-svc-httpbin
    spec:
      host: httpbin.default.svc.cluster.local
      trafficPolicy:
        tls:
          mode: ISTIO_MUTUAL
    ```
1. From my CLI pod I try to access the service, but I get back 503 response
    ```
    > curl -v httpbin:8000/status/203
    *   Trying 172.20.68.53:8000...
    * Connected to httpbin (172.20.68.53) port 8000 (#0)
    > GET /status/203 HTTP/1.1
    > Host: httpbin:8000
    > User-Agent: curl/7.74.0
    > Accept: */*
    >
    * Mark bundle as not supporting multiuse
    < HTTP/1.1 503 Service Unavailable
    < content-length: 19
    < content-type: text/plain
    < date: Tue, 09 Feb 2021 18:09:21 GMT
    < server: envoy
    <
    * Connection #0 to host httpbin left intact
    ```
1. I check if there are any endpoints defined for the ServiceEntry, but there are none:
    ```
    > istioctl proxy-config endpoints net-debug --cluster "outbound|8000||httpbin.default.svc.cluster.local"
    ENDPOINT     STATUS     OUTLIER CHECK     CLUSTER
    ```
1. However, if I try to delete the stub Service and re-create it, the endpoints magically appear and `curl` is successful:
    ```
    > kubectl delete service httpbin
    service "httpbin" deleted
    > kubectl apply -f -
    apiVersion: v1
    kind: Service
    metadata:
      name: httpbin
    spec:
      ports:
        - protocol: TCP
          port: 8000
          targetPort: 15443
    service/httpbin created
    > istioctl proxy-config endpoints net-debug --cluster "outbound|8000||httpbin.default.svc.cluster.local"
    ENDPOINT               STATUS      OUTLIER CHECK     CLUSTER
    10.9.137.124:15443     HEALTHY     OK                outbound|8000||httpbin.default.svc.cluster.local
    10.9.148.76:15443      HEALTHY     OK                outbound|8000||httpbin.default.svc.cluster.local
    10.9.164.53:15443      HEALTHY     OK                outbound|8000||httpbin.default.svc.cluster.local
    
    > curl -v httpbin:8000/status/203
    *   Trying 172.20.30.152:8000...
    * Connected to httpbin (172.20.30.152) port 8000 (#0)
    > GET /status/203 HTTP/1.1
    > Host: httpbin:8000
    > User-Agent: curl/7.74.0
    > Accept: */*
    >
    * Mark bundle as not supporting multiuse
    < HTTP/1.1 203 Non-Authoritative Information
    < server: envoy
    < date: Tue, 09 Feb 2021 18:12:32 GMT
    < content-type: text/html; charset=utf-8
    < access-control-allow-origin: *
    < access-control-allow-credentials: true
    < content-length: 0
    < x-envoy-upstream-service-time: 8
    <
    * Connection #0 to host httpbin left intact
    ```
    
**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
> istioctl version --remote
client version: 1.8.3
control plane version: 1.8.3
data plane version: 1.8.3 (2 proxies)
```
```
kubectl version --short
Client Version: v1.20.2
Server Version: v1.18.9-eks-d1db3
```

**How was Istio installed?**
It was installed with Istio Operator 1.8.3.
This is the operator config:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-config
spec:
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: {{ .Values.ingress_gateway.enabled }}
        namespace: default
        k8s:
          env:
            # sni-dnat adds the clusters required for AUTO_PASSTHROUGH mode to the Envoy config.
            # The gateway doesn't do pass-through without this!!!
            - name: ISTIO_META_ROUTER_MODE
              value: "sni-dnat"
          service:
            {{- if eq .Values.ingress_gateway.aws_lb_enabled true }}
            loadBalancerSourceRanges:
              - {{ .Values.ingress_gateway.loadBalancerSourceRanges }}
            type: LoadBalancer
            {{- else }}
            type: ClusterIP
            {{- end }}
          serviceAnnotations:
            {{- if eq .Values.ingress_gateway.aws_lb_enabled true }}
            service.beta.kubernetes.io/aws-load-balancer-internal: "true"
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
            service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
            {{- if .Values.ingress_gateway.domain_name }}
            external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress_gateway.domain_name }}
            {{- end }}
            {{- end }}
    cni:
      enabled: true
  meshConfig:
    accessLogFile: /dev/stderr
    enableAutoMtls: true
    defaultConfig:
      gatewayTopology:
        numTrustedProxies: 2 # required to pass the correct value for the "X-Forwarded-For" header
      # proxyMetadata:
      # Preview - introduced in Istio 1.8 to intercept DNS queries - makes ServiceEntries be discovered without
      # creating stub Services and it also greatly alleviates the Kubernetes DNS load
      #  ISTIO_META_DNS_CAPTURE: "true"
  values:
    global:
      logAsJson: true # This can be moved from istioctl 1.6 onwards to meshConfig.accessLogEncoding
      {{- if .Values.cluster.name }}
      meshID: mesh1
      multiCluster:
        clusterName: {{ .Values.cluster.name }}
      network: network1
      {{- end }}
      proxy:
        privileged: {{ .Values.enableAutoMtls | default false }}  # enable if you need to run `tcpdump` on the envoy sidecars
    sidecarInjectorWebhook:
      # disabling this because we rely on readiness probes not being overwritten by the pilot agent.
      # If that happens, the /opa-health-check probe will be routed by the pilot agent directly to the service,
      # without going through Envoy, which will make AuthX security tests fail (since the AuthZ doesn't occur for that request)
      rewriteAppHTTPProbe: false
      enableNamespacesByDefault: false # allow injection into any namespace
      objectSelector:
        enabled: false # match on the `sidecar.istio.io/inject: "true"` label
        autoInject: false # do not inject pods by default
```

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS EKS cluster with the latest Amazon Linux 2 AMI.

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
