### ISSUE TITLE
Specifying a specific service for `egress` in sidecar

### ISSUE THREAD

**Issue by hunkeelin** [istio/istio#30798]
Setup: I have 2 service in the namespace `api` call `foo` and `bar`. I am trying to use `sidecar` to control egress from `foo` to `bar`. 

Configuration 1 (baseline)
```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name:foo-sidecar-policy
  namespace: api
spec:
  workloadSelector:
    labels:
      app: foo
  egress:
  - hosts:
    - api/*
```
The above works because I am allowing all egress in name space `api`

Configuration 2
```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name:foo-sidecar-policy
  namespace: api
spec:
  workloadSelector:
    labels:
      app: foo
  egress:
  - hosts:
    - bar/*
```
Base on the documentation if I specify `bar/*` egress should allow `foo` to talk the `bar`. However. After applying the above configuration, `foo` is unable to access `bar` no more. 

Looking at the second example in the docs https://istio.io/latest/docs/reference/config/networking/sidecar/  I suspect one will need to specify the namespace and the service. So base on that logic I came up with the following configuration. 

```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name:foo-sidecar-policy
  namespace: api
spec:
  workloadSelector:
    labels:
      app: foo
  egress:
  - hosts:
    - abc/*
    - api/*
```

I specify a bogus service call `abc` then include the namespaces expecting the above configuration should cause `foo` not being able to communicate with `bar`. I was wrong, `foo` is able to communicate with `bar`. Which tells me `api/*` overrides the rule and my hypothesis that including the namespace as a requirement is not true.

So my question is, how can I only specify `bar` as egress for `foo` without including the whole namespace? Is this a bug or me missing something critical?
