### ISSUE TITLE
proxy.istio.io/config annotation - override does not work

### ISSUE THREAD

**Issue by dgpat** [istio/istio#30809]
**Bug description**

Related documentation:
https://istio.io/latest/docs/tasks/observability/distributed-tracing/configurability/#create-a-meshconfig-with-trace-settings

The value specified in the deployment (sampling 20) does not override the global value (sampling 100).
With the specified configuration, 100 percent of requests always arrive at the collector.

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    defaultConfig:
      tracing:
        sampling: 100
        zipkin:
          address: simplest-collector.observability:9411
```

Deployment metadata:
```
  template:
    metadata:
      labels:
        version: v1
      annotations:
        proxy.istio.io/config: |
          tracing:
            sampling: 20
            zipkin:
              address: simplest-collector.observability:9411
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
The meshConfig sampling value (in this case 100) should be overridden by using proxy.istio.io/config annotation (20) and tracing data should be collected by jaeger (only 20 percent).

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
istioctl version --remote
client version: 1.9.0
control plane version: 1.9.0
data plane version: 1.9.0 (3 proxies)
```

```
kubectl version --short
Client Version: v1.19.4
Server Version: v1.19.3
```

**How was Istio installed?**

```istioctl  install```

**Environment where the bug was observed (cloud vendor, OS, etc)**
Ubuntu 18.04 baremetal

**Comment by howardjohn** [comment]
This worked for me copying your config. Can you post the first ~300 lines of  logs of the proxy?

**Comment by dgpat** [comment]
@howardjohn Hello! Thanks for response.

I attach the log of the istio-proxy container.
I sent 15 requests and all 15 requests came to jaeger.

[logs-from-istio-proxy-in-ngx-frontend-red-77c75df567-lss9w.txt](https://github.com/istio/istio/files/5967227/logs-from-istio-proxy-in-ngx-frontend-red-77c75df567-lss9w.txt)

**Comment by howardjohn** [comment]
From the logs looks like it applied

can you look at the config_dump? https://github.com/istio/istio/wiki/Troubleshooting-Istio

There should be a part about the trace sampling there.

**Comment by dgpat** [comment]
```
kubectl -n test3 exec ngx-frontend-red-77c75df567-lss9w -c istio-proxy -- curl 'localhost:15000/config_dump' > config_dump.json
```
[config_dump.json.gz](https://github.com/istio/istio/files/5967318/config_dump.json.gz)

**Comment by howardjohn** [comment]
config looks right:
```
             "client_sampling": {
              "value": 100
             },
             "random_sampling": {
              "value": 20
             },
             "overall_sampling": {
              "value": 100
             },
```

**Comment by dgpat** [comment]
I do not understand. In the main config (via IstioOperator), the value is 100. The deployment config indicates the value 20.
I make 20 requests and see 20 requests in jaeger :(

**Comment by howardjohn** [comment]
I don't know either, sorry. Envoy is getting configured properlywhich is the extent on my knowledge. need someone in @istio/wg-policies-and-telemetry-maintainers to weigh in

**Comment by douglas-reid** [comment]
@dgpat are you making 20 requests directly to the target service, or do they go through another proxy somewhere (like an ingressgateway)?

**Comment by dgpat** [comment]
@douglas-reid Hello! Thanks for response.

I am making requests via VirtualService.

**Comment by dgpat** [comment]
I made a check.
```
kubectl -n test3 get svc
NAME               TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
ngx-frontend-red   ClusterIP   10.99.65.253     <none>        80/TCP    3d8
```

Checking from the kubernetes server.
```
grep testz /etc/hosts
10.99.65.253 red.testz.test.local
```
```
for i in {1..100};  do curl https://red.testz.test.local; done
```

If you do this, then everything is fine.
I make 100 requests, in jaeger I will see 20 requests

So what is the problem with using VirtualService?

**Comment by douglas-reid** [comment]
I don't think the problem is with the `VirtualService` so much as that you are going through a gateway. The gateway is itself a proxy and, critically, it makes a sampling decision for the entire request.

With your setup, I believe you have 100% sampling at the gateway. The request hits the gateway, which makes the sampling decision (essentially `sample=true`), then routes the request to your target service. The proxy in front of your target service sees that a sampling decision has already been made, and honors it.

**Comment by dgpat** [comment]
Ok. And what do I need to use to get normal behavior?

**Comment by dgpat** [comment]
By the way, I tried doing the opposite.
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    defaultConfig:
      tracing:
        sampling: 1
        zipkin:
          address: simplest-collector.observability:9411
```
Deployment metadata:

```
  template:
    metadata:
      labels:
        version: v1
      annotations:
        proxy.istio.io/config: |
          tracing:
            sampling: 100
            zipkin:
              address: simplest-collector.observability:9411
```

If you do this, then I see only 1% of requests in jaeger

**Comment by dgpat** [comment]
@howardjohn please tell me, did you use VirtaulService for check this case?

**Comment by douglas-reid** [comment]
> By the way, I tried doing the opposite.
> 
> ```
> apiVersion: install.istio.io/v1alpha1
> kind: IstioOperator
> spec:
>   meshConfig:
>     defaultConfig:
>       tracing:
>         sampling: 1
>         zipkin:
>           address: simplest-collector.observability:9411
> ```
> 
> Deployment metadata:
> 
> ```
>   template:
>     metadata:
>       labels:
>         version: v1
>       annotations:
>         proxy.istio.io/config: |
>           tracing:
>             sampling: 100
>             zipkin:
>               address: simplest-collector.observability:9411
> ```
> 
> If I do this, then I see only 1% of requests in jaeger

The key thing is that: if your request first goes through a gateway or another proxy, the _only_ sampling rate that matters is the one that is applied there. Envoy supports per route tracing decisions, but there is not support in the Istio APIs for that level of control. You can try to use EnvoyFilters to achieve your goal for ingress.

**Comment by dgpat** [comment]
I'm sorry, I did not understand.

The [documentation](https://istio.io/latest/docs/tasks/observability/distributed-tracing/configurability/) does not indicate what type (Ingress, VirtualService or something else) of connection should be used.
This [documentation](https://istio.io/latest/docs/concepts/traffic-management/) doesn't say there are sampling restrictions.
And this [documentation](https://istio.io/latest/docs/tasks/traffic-management/ingress/kubernetes-ingress/) says to use Gateway+VirtualService.

Do I need to stop using Gateway+VirtualService and switch to Ingress?

**Comment by douglas-reid** [comment]
Sampling decisions for tracing are made once per request. The sampling decision is propagated on each child request once it has been made.

If your request is flowing through a proxy, such as an ingress gateway, that makes sampling decisions, you will need to change the sampling rate *at that proxy* and not at the downstream proxy.

Here's is my lame attempt at diagramming what I _think_ is happening in your scenario:

client --> Istio IngressGateway (makes sampling decision; random sample rate of 100%) -->  Sidecar proxy (respects original sampling decision; random sampling rate here is irrelevant) --> backend

The Istio Networking APIs aren't what is relevant. It is the fact that the sampling rate at your gateway is 100%.

To get 20% sampling on requests going to your backend, you need to set the sampling rate at the gateway to be 20%. That can be blunt, and the workarounds for greater precision are a bit complex, but that is the general idea.

Does that make sense?

If you apply a 20% sampling rate at the sidecar proxy for your backend, that will *only* apply to traffic for which no prior sampling decision has been made.

**Comment by dgpat** [comment]
Ok.
Then the task "collect from all request (to all namespace) 20%, and from a separate namespace 100%" - has no solution?
That is, if I want to collect 100% from one separate namespace, do I need to turn off sampling in the gateway, and use only annotation in the deployment?

**Comment by douglas-reid** [comment]
> Ok.
> Then the task "collect from all request (to all namespace) 20%, and from a separate namespace 100%" - has no solution?
> That is, if I want to collect 100% from one separate namespace, do I need to turn off sampling in the gateway, and use only annotation in the deployment?

It has a solution, but it is more involved. It requires, at this time, some EnvoyFilter manipulation for per-route configuration. Or different gateways for different backends.

**Comment by mhbahmani** [comment]
Hi, sorry to bring up an old issue.
Isn't there a way to set client_sampling or overall_sampling in istio?

**Comment by mhbahmani** [comment]
For the record, I came up with this simple envoyfilter, which can be used to customize tracing behaviours of envoy.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: customize-tracing-configuration
  namespace: tracing-test-ns
spec:
  workloadSelector:
    labels:
      app: tracing-test-workload
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          tracing:
            overall_sampling:
              value: 50
```
More on [here](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-msg-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-tracing).

Like any other envoyfilters, it should be used on production environments with caution!
