### ISSUE TITLE
Egress Gateway TLS Origination 503 error

### ISSUE THREAD

**Issue by fxgagnon** [istio/istio#30808]
**Bug description**

Following this example works :
https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway-tls-origination-sds/
But when we change the domain name for an external one, We've keep getting a 503 error.
We've tried many resolution/solutions path, but nothing worked. Our last tried was based on that issues https://github.com/istio/istio/issues/24619, to upgrade from istio 1.7.3 to istio 1.8.2, and we still get the same error.

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Get valid http response from distant service. 

**Steps to reproduce the bug**

1. I've generated CA and server certificate key followings https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway-tls-origination-sds/#generate-ca-and-server-certificates-and-keys, for the domain jaeger.app.dev.monitoring (that is an internal domain, that can be reach from our service mesh) and I've applied the tls.crt and tls.key to our distant domain, so it exposed the certificate related to the issuer we've created in this step.  Moreover, I've run the following command to double check that the exposed certificate are issued by our issuer created in this step.
```shell
/$ openssl s_client -CAfile ./ca.crt  -showcerts -verify 5 -connect jaeger.app.dev.monitoring:443
...
...
    Verify return code: 0 (ok)
...
```
2. Since our domain is distant, we can skip the "deploy the simple tls server" steps.  So I've followed this https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway-tls-origination-sds/#configure-simple-tls-origination-for-egress-traffic with some variation specific for the domain jaeger.app.dev.monitoring

>note that I've added the namespace to target the istio-system namespace.  It's the way that I've been able to make it work with "Configure simple TLS origination for egress traffic" steps in a previous test.

The kubernetes secret have been created following the steps 1 and 2 of https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway-tls-origination-sds/#deploy-a-simple-tls-server

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
  namespace: istio-system
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - jaeger.app.dev.monitoring
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-nginx
  namespace: istio-system  
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: nginx
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: ISTIO_MUTUAL
          sni: jaeger.app.dev.monitoring
```

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-nginx-through-egress-gateway
  namespace: istio-system
spec:
  hosts:
  - jaeger.app.dev.monitoring
  gateways:
  - istio-egressgateway
  - mesh
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: nginx
        port:
          number: 443
      weight: 100
  - match:
    - gateways:
      - istio-egressgateway
      port: 443
    route:
    - destination:
        host: jaeger.app.dev.monitoring
        port:
          number: 443
      weight: 100
```

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-tls-for-nginx
  namespace: istio-system
spec:
  host: jaeger.app.dev.monitoring
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE
        credentialName: client-credential # this must match the secret created earlier without the "-cacert" suffix
        sni: jaeger.app.dev.monitoring
```
> in a disgnostic perspective, i've been able to reproduce the behavior using www.google.com domain and removing the tls.credentialName of originate-tls-for-nginx DestinationRule

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
client version: 1.8.2
control plane version: 1.8.2
data plane version: 1.7.3 (17 proxies), 1.8.2 (12 proxies)

Client Version: v1.18.14
Server Version: v1.18.12

**How was Istio installed?**

Istio-Operator

**Environment where the bug was observed (cloud vendor, OS, etc)**
RKS in Azure

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
Did you define a service entry?

What type of 503 did you get? You can check access logs for something like `503 NR cluster_not_found` or `503 UH no_healthy_upstream`

I applied this config with demo profile on Istio 1.9 and it worked:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google
spec:
  hosts:
  - "www.google.com"
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
  namespace: istio-system
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - www.google.com
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-nginx
  namespace: istio-system  
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: nginx
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: ISTIO_MUTUAL
          sni: www.google.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-nginx-through-egress-gateway
  namespace: istio-system
spec:
  hosts:
  - www.google.com
  gateways:
  - istio-egressgateway
  - mesh
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: nginx
        port:
          number: 443
      weight: 100
  - match:
    - gateways:
      - istio-egressgateway
      port: 443
    route:
    - destination:
        host: www.google.com
        port:
          number: 443
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-tls-for-nginx
  namespace: istio-system
spec:
  host: www.google.com
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE
        sni: www.google.com
```
