### ISSUE TITLE
TCP mTLS through ingressgateway "NR filter_chain_not_found"

### ISSUE THREAD

**Issue by nmnellis** [istio/istio#30819]
**Bug description**
When trying to route TCP traffic from one cluster to another clusters ingressgateway. The remote cluster ingressgateway always responds with `[2021-02-11T20:35:56.660Z] "- - -" 0 NR filter_chain_not_found - "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.16.0.15:15443 10.16.0.1:20071 - -` When trying to use ISTIO_MUTUAL or PASSTHROUGH.

Running this command in cluster 1 sleep with sidecar
```sh
kubectl exec sleep-64d7d56698-g9wsv -c sleep -n default --context=cluster1 -- sh -c (date; sleep 1) | nc 'tcp-echo.tetrate.io' 9000
# logs from sleep proxy
[2021-02-11T20:35:55.219Z] "- - -" 0 UF,URX - - "-" 0 0 6 - "-" "-" "-" "-" "34.66.156.228:15443" outbound|9000||tcp-echo.tetrate.io - 240.240.0.1:9000 10.116.2.6:42509 - -
[2021-02-11T20:35:56.658Z] "- - -" 0 UF,URX - - "-" 0 0 2 - "-" "-" "-" "-" "34.66.156.228:15443" outbound|9000||tcp-echo.tetrate.io - 240.240.0.1:9000 10.116.2.6:43755 - -
```

I am using Istio DNS proxy addresses to identity the traffic if that makes a difference.

[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
route tcp traffic to other clusters using mTLS via gateways

**Steps to reproduce the bug**
deploy istio and  sleep service to cluster1. deploy ingressgateway and tcp-echo to cluster 2

Cluster 1 configs:
```yaml
# tell all sidecars about tcp-echo in the remote cluster
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: tcp-echo-remote
  namespace: default
spec:
  endpoints:
  - address: ${CLUSTER2_INGRESS_HOST}
    ports:
      tcp: 15443
  exportTo:
  - '*'
  hosts:
  - tcp-echo.tetrate.io
  location: MESH_INTERNAL
  ports:
  - name: tcp
    number: 9000
    protocol: TCP
  resolution: STATIC
```

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: tcp-echo
spec:
  host: tcp-echo.tetrate.io
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```

cluster2 configs:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tcp-echo
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 15443
        name: tls
        protocol: TLS
      tls:
        mode: ISTIO_MUTUAL
      hosts:
        - "tcp-echo.tetrate.io"
---
# handle traffic for tcp-echo.tetrate.io and route to tcp-echo
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tcp-echo
  namespace: tcp-echo
spec:
  hosts:
  - "tcp-echo.tetrate.io"
  gateways:
  - istio-system/tcp-echo
  tcp:
  - route:
    - destination:
        host: tcp-echo
        port:
          number: 9000
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```sh
istioctl version --remote --context ${CTX_CLUSTER1} 
client version: 1.9.0
control plane version: 1.9.0
data plane version: 1.9.0 (9 proxies)
```
```sh
+ kubectl version --short --context gke_nicks-area-51_us-central1-c_cluster-11
Client Version: v1.20.2
Server Version: v1.18.12-gke.1206
```
**How was Istio installed?**

Cluster 1
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: cluster1
spec:
  meshConfig:
    accessLogFile: "/dev/stdout"
    defaultConfig:
      proxyMetadata:
        # enable proxy dns
        ISTIO_META_PROXY_XDS_VIA_AGENT: "true"
        ISTIO_META_DNS_CAPTURE: "true"
        # Enable automatic address allocation, optional
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
  values:
    global:
      proxy:
        logLevel: info
      meshID: mesh1
      multiCluster:
        clusterName: cluster1
      network: network1
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        service:
          ports:
            - name: tls
              port: 15443
              targetPort: 15443
    - name: istio-egressgateway
      enabled: false
    - name: istio-eastwestgateway
      label:
        istio: eastwestgateway
        app: istio-eastwestgateway
        topology.istio.io/network: network1
      enabled: true
      k8s:
        env:
          # sni-dnat adds the clusters required for AUTO_PASSTHROUGH mode
          - name: ISTIO_META_ROUTER_MODE
            value: "sni-dnat"
          # traffic through this gateway should be routed inside the network
          - name: ISTIO_META_REQUESTED_NETWORK_VIEW
            value: network1
        service:
          ports:
            - name: status-port
              port: 15021
              targetPort: 15021
            - name: tls
              port: 15443
              targetPort: 15443
            - name: tls-istiod
              port: 15012
              targetPort: 15012
            - name: tls-webhook
              port: 15017
              targetPort: 15017
```

Cluster 2
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: cluster2
spec:
  meshConfig:
    accessLogFile: "/dev/stdout"
    defaultConfig:
      proxyMetadata:
        # enable proxy dns
        ISTIO_META_PROXY_XDS_VIA_AGENT: "true"
        ISTIO_META_DNS_CAPTURE: "true"
        # Enable automatic address allocation, optional
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
  values:
    global:
      proxy:
        logLevel: info
      meshID: mesh1
      multiCluster:
        clusterName: cluster2
      network: network2
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        service:
          ports:
            - name: tls
              port: 15443
              targetPort: 15443
    - name: istio-egressgateway
      enabled: false
    - name: istio-eastwestgateway
      label:
        istio: eastwestgateway
        app: istio-eastwestgateway
        topology.istio.io/network: network2
      enabled: true
      k8s:
        env:
          # sni-dnat adds the clusters required for AUTO_PASSTHROUGH mode
          - name: ISTIO_META_ROUTER_MODE
            value: "sni-dnat"
          # traffic through this gateway should be routed inside the network
          - name: ISTIO_META_REQUESTED_NETWORK_VIEW
            value: network2
        service:
          ports:
            - name: status-port
              port: 15021
              targetPort: 15021
            - name: tls
              port: 15443
              targetPort: 15443
            - name: tls-istiod
              port: 15012
              targetPort: 15012
            - name: tls-webhook
              port: 15017
              targetPort: 15017
```

**Environment where the bug was observed (cloud vendor, OS, etc)**
GKE

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

Listeners of IngressGateway
`istioctl pc listeners istio-ingressgateway-6455fc7485-c7h8b -n istio-system --context ${CTX_CLUSTER2} --port 15443 -o json`
```json
[
    {
        "name": "0.0.0.0_15443",
        "address": {
            "socketAddress": {
                "address": "0.0.0.0",
                "portValue": 15443
            }
        },
        "filterChains": [
            {
                "filterChainMatch": {
                    "serverNames": [
                        "tcp-echo.tetrate.io"
                    ]
                },
                "filters": [
                    {
                        "name": "istio.stats",
                        "typedConfig": {
                            "@type": "type.googleapis.com/udpa.type.v1.TypedStruct",
                            "typeUrl": "type.googleapis.com/envoy.extensions.filters.network.wasm.v3.Wasm",
                            "value": {
                                "config": {
                                    "configuration": {
                                        "@type": "type.googleapis.com/google.protobuf.StringValue",
                                        "value": "{\n  \"debug\": \"false\",\n  \"stat_prefix\": \"istio\",\n  \"metrics\": [\n    {\n      \"dimensions\": {\n        \"source_cluster\": \"node.metadata['CLUSTER_ID']\",\n        \"destination_cluster\": \"upstream_peer.cluster_id\"\n      }\n    }\n  ]\n}\n"
                                    },
                                    "root_id": "stats_outbound",
                                    "vm_config": {
                                        "code": {
                                            "local": {
                                                "inline_string": "envoy.wasm.stats"
                                            }
                                        },
                                        "runtime": "envoy.wasm.runtime.null",
                                        "vm_id": "tcp_stats_outbound"
                                    }
                                }
                            }
                        }
                    },
                    {
                        "name": "envoy.filters.network.tcp_proxy",
                        "typedConfig": {
                            "@type": "type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy",
                            "statPrefix": "outbound|9000||tcp-echo.tcp-echo.svc.cluster.local",
                            "cluster": "outbound|9000||tcp-echo.tcp-echo.svc.cluster.local",
                            "accessLog": [
                                {
                                    "name": "envoy.access_loggers.file",
                                    "typedConfig": {
                                        "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog",
                                        "path": "/dev/stdout",
                                        "logFormat": {
                                            "textFormat": "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% \"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%\n"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                ],
                "transportSocket": {
                    "name": "envoy.transport_sockets.tls",
                    "typedConfig": {
                        "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext",
                        "commonTlsContext": {
                            "tlsCertificateSdsSecretConfigs": [
                                {
                                    "name": "default",
                                    "sdsConfig": {
                                        "apiConfigSource": {
                                            "apiType": "GRPC",
                                            "transportApiVersion": "V3",
                                            "grpcServices": [
                                                {
                                                    "envoyGrpc": {
                                                        "clusterName": "sds-grpc"
                                                    }
                                                }
                                            ],
                                            "setNodeOnFirstMessageOnly": true
                                        },
                                        "initialFetchTimeout": "0s",
                                        "resourceApiVersion": "V3"
                                    }
                                }
                            ],
                            "combinedValidationContext": {
                                "defaultValidationContext": {},
                                "validationContextSdsSecretConfig": {
                                    "name": "ROOTCA",
                                    "sdsConfig": {
                                        "apiConfigSource": {
                                            "apiType": "GRPC",
                                            "transportApiVersion": "V3",
                                            "grpcServices": [
                                                {
                                                    "envoyGrpc": {
                                                        "clusterName": "sds-grpc"
                                                    }
                                                }
                                            ],
                                            "setNodeOnFirstMessageOnly": true
                                        },
                                        "initialFetchTimeout": "0s",
                                        "resourceApiVersion": "V3"
                                    }
                                }
                            },
                            "alpnProtocols": [
                                "h2",
                                "http/1.1"
                            ]
                        },
                        "requireClientCertificate": true
                    }
                }
            }
        ],
        "listenerFilters": [
            {
                "name": "envoy.filters.listener.tls_inspector",
                "typedConfig": {
                    "@type": "type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector"
                }
            }
        ],
        "trafficDirection": "OUTBOUND",
        "accessLog": [
            {
                "name": "envoy.access_loggers.file",
                "filter": {
                    "responseFlagFilter": {
                        "flags": [
                            "NR"
                        ]
                    }
                },
                "typedConfig": {
                    "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog",
                    "path": "/dev/stdout",
                    "logFormat": {
                        "textFormat": "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% \"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%\n"
                    }
                }
            }
        ]
    }
]

```

Routes
`istioctl pc routes istio-ingressgateway-6455fc7485-c7h8b -n istio-system --context ${CTX_CLUSTER2} -o json`
```json
[
    {
        "virtualHosts": [
            {
                "name": "backend",
                "domains": [
                    "*"
                ],
                "routes": [
                    {
                        "match": {
                            "prefix": "/healthz/ready"
                        },
                        "route": {
                            "cluster": "agent"
                        }
                    }
                ]
            }
        ]
    },
    {
        "virtualHosts": [
            {
                "name": "backend",
                "domains": [
                    "*"
                ],
                "routes": [
                    {
                        "match": {
                            "prefix": "/stats/prometheus"
                        },
                        "route": {
                            "cluster": "prometheus_stats"
                        }
                    }
                ]
            }
        ]
    }
]

```

Clusters of sleep pod
`istioctl pc clusters sleep-64d7d56698-g9wsv --context ${CTX_CLUSTER1} --fqdn tcp-echo.tetrate.io -o json`
```json
[
    {
        "name": "outbound|9000||tcp-echo.tetrate.io",
        "type": "EDS",
        "edsClusterConfig": {
            "edsConfig": {
                "ads": {},
                "resourceApiVersion": "V3"
            },
            "serviceName": "outbound|9000||tcp-echo.tetrate.io"
        },
        "connectTimeout": "10s",
        "circuitBreakers": {
            "thresholds": [
                {
                    "maxConnections": 4294967295,
                    "maxPendingRequests": 4294967295,
                    "maxRequests": 4294967295,
                    "maxRetries": 4294967295
                }
            ]
        },
        "transportSocket": {
            "name": "envoy.transport_sockets.tls",
            "typedConfig": {
                "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext",
                "commonTlsContext": {
                    "tlsCertificateSdsSecretConfigs": [
                        {
                            "name": "default",
                            "sdsConfig": {
                                "apiConfigSource": {
                                    "apiType": "GRPC",
                                    "transportApiVersion": "V3",
                                    "grpcServices": [
                                        {
                                            "envoyGrpc": {
                                                "clusterName": "sds-grpc"
                                            }
                                        }
                                    ],
                                    "setNodeOnFirstMessageOnly": true
                                },
                                "initialFetchTimeout": "0s",
                                "resourceApiVersion": "V3"
                            }
                        }
                    ],
                    "combinedValidationContext": {
                        "defaultValidationContext": {},
                        "validationContextSdsSecretConfig": {
                            "name": "ROOTCA",
                            "sdsConfig": {
                                "apiConfigSource": {
                                    "apiType": "GRPC",
                                    "transportApiVersion": "V3",
                                    "grpcServices": [
                                        {
                                            "envoyGrpc": {
                                                "clusterName": "sds-grpc"
                                            }
                                        }
                                    ],
                                    "setNodeOnFirstMessageOnly": true
                                },
                                "initialFetchTimeout": "0s",
                                "resourceApiVersion": "V3"
                            }
                        }
                    },
                    "alpnProtocols": [
                        "istio-peer-exchange",
                        "istio"
                    ]
                },
                "sni": "outbound_.9000_._.tcp-echo.tetrate.io"
            }
        },
        "metadata": {
            "filterMetadata": {
                "istio": {
                    "config": "/apis/networking.istio.io/v1alpha3/namespaces/default/destination-rule/tcp-echo",
                    "default_original_port": 9000,
                    "services": [
                        {
                            "host": "tcp-echo.tetrate.io",
                            "name": "tcp-echo.tetrate.io",
                            "namespace": "default"
                        }
                    ]
                }
            }
        },
        "filters": [
            {
                "name": "istio.metadata_exchange",
                "typedConfig": {
                    "@type": "type.googleapis.com/udpa.type.v1.TypedStruct",
                    "typeUrl": "type.googleapis.com/envoy.tcp.metadataexchange.config.MetadataExchange",
                    "value": {
                        "protocol": "istio-peer-exchange"
                    }
                }
            }
        ]
    }
]
```

**Comment by howardjohn** [comment]
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: tcp-echo
spec:
  host: tcp-echo.tetrate.io
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
      sni: tcp-echo.tetrate.io
```


maybe add SNI to DR?
