### ISSUE TITLE
[Help] Can we inject faults in HTTPS traffic? 

### ISSUE THREAD

**Issue by AjithPanneerselvam** [istio/istio#30828]
I'm trying to inject fault in AWS Kinesis (it uses HTTPS). The following is the fault config for Kinesis. 

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kinesis-svc 
  namespace: dev 
spec:
  hosts:
    - kinesis.us-east-1.amazonaws.com 
  http:
  - fault:
      delay:
        fixedDelay: 20s
        percentage:
          value: 100
    route:
    - destination:
        host: kinesis.us-east-1.amazonaws.com
```

With the above fault configuration, I'm unable to inject faults in the Kinesis request. This behaviour makes me question whether fault injection is actually possible in HTTPS request with Istio? If fault injection is possible in HTTPS traffic, please lemme know what's wrong in my above fault configurations.
