### ISSUE TITLE
Cross-cluster load-balancing doesn't work

### ISSUE THREAD

**Issue by chris-makaio** [istio/istio#30832]
**Bug description**

I followed the guide here
https://istio.io/latest/docs/tasks/traffic-management/locality-load-balancing/distribute/
for locality aware load-balancing

Only difference is that I use only three clusters (+ primary)

This is the destination rule:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: helloworld
spec:
  host: helloworld.sample.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      localityLbSetting:
        enabled: true
        distribute:
        - from: region1/zone1/*
          to:
            "region1/zone1/*": 50
            "region1/zone2/*": 25
            "region2/zone3/*": 25
    outlierDetection:
      consecutive5xxErrors: 100
      interval: 1s
      baseEjectionTime: 1m
```

I've created a simple bashscript for CURLing the service a hundred times:
```shell

for i in {1..100}
do
   kubectl exec --context="${CTX_R1_Z1}" -n sample -c sleep \
  "$(kubectl get pod --context="${CTX_R1_Z1}" -n sample -l \
  app=sleep -o jsonpath='{.items[0].metadata.name}')" \
  -- curl -sSL helloworld.sample:5000/hello
done
```

### First observation: weighted load balancing doesn't seem to work

I've copied the output into a fancy Excel file to get the "replies-per-node" and this is the result:

```
region2.zone3      33
region1.zone1      35
region1.zone2      32
```

It seems it's still round-robbined.

### Second observation: cross-cluster and intra-cluster load-balancing don't work

I've scaled the helloworld deployment to 3 nodes in each cluster and this is the result (distinct nodes responding to curl):
helloworld-region1.zone1-5f557c74df-kfg5g
helloworld-region1.zone1-5f557c74df-fhj57
helloworld-region1.zone1-5f557c74df-pg9ts
helloworld-region1.zone2-74b9c5ccc7-gnljk
helloworld-region2.zone3-5565df8869-pvzkq

Obviously only the nodes within the "request-origin" cluster are load-balanced while only one node per remote cluster responds.

I already know that this is an issue which seems to affect all major service meshes, but I don't get it - is this really an exotic case? To distribute multiple services in multiple clusters and having all of them balanced?

[X] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

see above

**Steps to reproduce the bug**

see above

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**
Istio 1.9.0
Kube:
Client Version: v1.19.3
Server Version: v1.19.5

**Environment where the bug was observed (cloud vendor, OS, etc)**

see bug report attached (wow, Github doesn't accept tgz extension)
[bug-report.tar.gz](https://github.com/istio/istio/files/5972354/bug-report.tar.gz)

**Comment by howardjohn** [comment]
Can you run:
```
kubectl get nodes -L topology.kubernetes.io/zone,topology.kubernetes.io/region
```

I just realized our bug report tool doesn't capture nodes, opening an issue for that.

**Comment by chris-makaio** [comment]
wait, do these labels have to match the selectors in the DestinationRule? 
I thought they were matched against the version labels of the helloworld deployments.

But just fyi, here's the output of one cluster:
```
NAME                                        STATUS   ROLES    AGE   VERSION   ZONE   REGION
node-55dc4125-75f6-46af-bc01-844fc4c8d539   Ready    <none>   18d   v1.19.5   nova   SBG5
node-5757e41e-1920-461c-b9eb-4ef4adadb07e   Ready    <none>   18d   v1.19.5   nova   SBG5
node-af14999c-2378-460b-a37e-64186105d82c   Ready    <none>   18d   v1.19.5   nova   SBG5
```

(that's OVHCloud in case you're wondering)

**Comment by howardjohn** [comment]
```
        - from: region1/zone1/*
          to:
            "region1/zone1/*": 50
            "region1/zone2/*": 25
            "region2/zone3/*": 25
```

means send traffic in region1 zone1 to these other zones. But 100% of your pods are in region SBG5 and zone nova, so:
* This config does nothing
* any config of Locality load balancing will never do anything with your setup, since they are all in the same region/zone
