### ISSUE TITLE
istio ingressgateway `istio-ingressgateway` is always installed

### ISSUE THREAD

**Issue by gleichda** [istio/istio#30886]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

istio creates a ingressgateway `istio-ingressgateway` in any case even if a different ingressgateway name is specified.

![grafik](https://user-images.githubusercontent.com/15176026/108197945-4a53e580-711b-11eb-996d-cedef8d34c1e.png)
![grafik](https://user-images.githubusercontent.com/15176026/108198697-3d83c180-711c-11eb-8f77-6341d7352096.png)

If the name of the ingressgateway is `istio-ingressgateway` I can confirm that only one Ingress Gateway with the right config is created.

Maybe related to #30756 

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Istio will create only one ingressgateway with the name `ingressgateway`.

**Steps to reproduce the bug**

Install istio via istio operator with.

```yaml
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio
spec:
  hub: gcr.io/istio-release
  meshConfig:
    outboundTrafficPolicy:
      mode: ALLOW_ANY
    defaultConfig:
      tracing:
        sampling: 100.0
  components:
    base:
      enabled: true
    pilot:
      enabled: true
      spec:
        policy:
          enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2

    ingressGateways:
      - name: ingressgateway
        enabled: true
        k8s:
          hpaSpec:
            minReplicas: 2

    egressGateways:
      - name: egressgateway
        enabled: true
        k8s:
          hpaSpec:
            minReplicas: 2
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```shell
$ istioctl version --remote
client version: 1.9.0
control plane version: 1.9.0
data plane version: 1.9.0 (5 proxies)

$ kubectl version --short
Client Version: v1.20.2
Server Version: v1.18.12-gke.1210
```

**How was Istio installed?**

With the istio Operator helm chart:

```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: istio-operator
  namespace: istio-system
spec:
  releaseName: istio-operator
  chart:
    git: git@github.com:istio/istio.git
    ref: 1.9.0
    path: manifests/charts/istio-operator/
  values:
    hub: gcr.io/istio-release
    tag: 1.9.0
```

**Environment where the bug was observed (cloud vendor, OS, etc)**

GKE Rapid release channel

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details. -> I don't think this is required if so just ping me

**Comment by rvennam** [comment]
Try setting `profile` to empty.
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio
spec:
  profile: empty
...
```

https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#IstioOperatorSpec
