### ISSUE TITLE
Istio injection prevents NodePort connection

### ISSUE THREAD

**Issue by pavanfhw** [istio/istio#30893]
**Bug description**

Using the following manifest (for testing purposes):

```
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30006
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
 ```
 
 If I don't inject istio in the namespace (`kubectl label namespace default istio-injection=enabled`) it is possible to connect to the mysql server using the node port of the service from outside:
 `mysql -h <IP ADDR> -P 30006 -u root -ppassword`
 
 After injectiing isito in the namespace and recreating the pod so the sidecar is created. I can't connect anymore to the mysql server.
 
 How does Istio affect the node port connection?
 

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
client version: 1.9.0
control plane version: 1.9.0
data plane version: 1.9.0 (2 proxies)

Client Version: v1.18.4+k3s1
Server Version: v1.18.4+k3s1

**How was Istio installed?**

istioctl install --set profile=default -y

**Environment where the bug was observed (cloud vendor, OS, etc)**

K3OS

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

File type .tgz is not supported

**Comment by howardjohn** [comment]
https://github.com/istio/istio/issues/29548#issuecomment-780145570 may help

**Comment by pavanfhw** [comment]
@howardjohn it worked! Thank you

**Comment by pavanfhw** [comment]
For the example manifest I used, this resource is necessary to solve the problem:

```
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "mtls-mysql-policy"
spec:
  selector:
    matchLabels:
      app: mysql
  mtls:
    mode: DISABLE
```
