### ISSUE TITLE
istioctl does not respect custom control plane namespace via --set namespace

### ISSUE THREAD

**Issue by jmazzitelli** [istio/istio#30897]
**Bug description**

I want to install Istio in a control plane namespace that is different from the default (which is istio-system). I want to put the components in a namespace called `my-istio-namespace` (or whatever you want, that's just an example). In the docs, it says I can do this via the "namespace" option - see: https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#IstioOperatorSpec

However, istioctl doesn't use the custom namespace I give it for everything - it only uses it for some things. The install fails because of this.

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Istio components all installed in my custom namespace.

**Steps to reproduce the bug**

Create a namespace not named `istio-system` (e.g. `my-istio-namespace`). And pass that namespace name to istioctl via `--set namespace`. Then notice the results that are generated don't always use that name - it uses `istio-system` still:

```
$ istioctl manifest generate --set namespace=my-istio-namespace  | grep istio-system
  namespace: istio-system
  namespace: istio-system
  name: istio-reader-istio-system
  name: istiod-istio-system
  name: istio-reader-istio-system
  name: istio-reader-istio-system
    namespace: istio-system
  name: istiod-istio-system
  name: istiod-istio-system
    namespace: istio-system
  name: istiod-istio-system
        namespace: istio-system
          address: zipkin.istio-system:9411
    rootNamespace: istio-system
        "istioNamespace": "istio-system",
            value: istiod.istio-system.svc:15012
  name: istiod-istio-system
  namespace: istio-system
  name: istiod-istio-system
  namespace: istio-system
  name: istiod-istio-system
    namespace: istio-system
```

An example where istioctl does not use my custom namespace is istiod Role:

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: istiod-istio-system
  namespace: istio-system
  labels:
    app: istiod
    release: istio
```

And there are other resources (istiod service account as another) that are being created in the wrong namespace.

But notice SOME things do use my custom namespace:

```
$ istioctl manifest generate --set namespace=my-istio-namespace  | grep my-istio-namespace
  namespace: my-istio-namespace
  namespace: my-istio-namespace
  namespace: my-istio-namespace
  namespace: my-istio-namespace
  namespace: my-istio-namespace
  namespace: my-istio-namespace
  namespace: my-istio-namespace
  namespace: my-istio-namespace
  namespace: my-istio-namespace
  namespace: my-istio-namespace
      discoveryAddress: istiod.my-istio-namespace.svc:15012
  namespace: my-istio-namespace
        "namespace": "my-istio-namespace",
  name: istio-sidecar-injector-my-istio-namespace
      namespace: my-istio-namespace
  namespace: my-istio-namespace
            value: kubernetes://apis/apps/v1/namespaces/my-istio-namespace/deployments/istio-ingressgateway
  namespace: my-istio-namespace
            value: istiod.my-istio-namespace.svc:15012
  namespace: my-istio-namespace
  namespace: my-istio-namespace
  namespace: my-istio-namespace
  namespace: my-istio-namespace
  namespace: my-istio-namespace
  namespace: my-istio-namespace
  namespace: my-istio-namespace
  namespace: my-istio-namespace
```

One correct resource is the Istio ConfigMap:

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio
  namespace: my-istio-namespace
  labels:
    istio.io/rev: default
    install.operator.istio.io/owning-resource: unknown
    operator.istio.io/component: "Pilot"
    release: istio
data:
 ...
```
**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

1.9.0
