### ISSUE TITLE
Labels are not applied to deployment or pod when specified for an ingress gateway component

### ISSUE THREAD

**Issue by su225** [istio/istio#30896]
**Bug description**
This is found in 1.7 and even in 1.9

Example YAML
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-install
  namespace: istio-system
spec:
  meshConfig:
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
  profile: demo
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
      - name: httpbin-gateway
        enabled: true
        namespace: httpbin
        label:
          app-name: httpbin
          gateway: httpbin
        k8s:
          podAnnotations:
            sidecar.istio.io/inject: "false"
  values:
    global:
      istiod:
        enableAnalysis: true
    pilot:
      env:
        PILOT_ENABLE_STATUS: true
```
Here I expect `httpbin-gateway` pods or deployment to have `app-name` and `gateway` labels. It seems that labels are swallowed during overlaying process in operators as shown in the saved `IstioOperator` CR.
```yaml
    ingressGateways:
    - enabled: true
      k8s:
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
        service:
          ports:
          - name: status-port
            port: 15021
            protocol: TCP
            targetPort: 15021
          - name: http2
            port: 80
            protocol: TCP
            targetPort: 8080
          - name: https
            port: 443
            protocol: TCP
            targetPort: 8443
          - name: tcp
            port: 31400
            protocol: TCP
            targetPort: 31400
          - name: tls
            port: 15443
            protocol: TCP
            targetPort: 15443
      name: istio-ingressgateway
    - enabled: true
      k8s:
        podAnnotations:
          sidecar.istio.io/inject: "false"
      name: httpbin-gateway
      namespace: httpbin
```
Pod labels for `httpbin-gateway`
```
Name:         httpbin-gateway-6ddfcb7cc9-dkpdg
Namespace:    httpbin
Priority:     0
Node:         xcp-1-control-plane/172.18.0.4
Start Time:   Wed, 17 Feb 2021 21:10:57 +0530
Labels:       app=istio-ingressgateway
              install.operator.istio.io/owning-resource=unknown
              istio=ingressgateway
              istio.io/rev=default
              operator.istio.io/component=IngressGateways
              pod-template-hash=6ddfcb7cc9
              service.istio.io/canonical-name=httpbin-gateway
              service.istio.io/canonical-revision=latest
              sidecar.istio.io/inject=false
Annotations:  prometheus.io/path: /stats/prometheus
              prometheus.io/port: 15020
              prometheus.io/scrape: true
              sidecar.istio.io/inject: false

```
Similarly labels and annotations on deployment
```
Name:                   httpbin-gateway
Namespace:              httpbin
CreationTimestamp:      Wed, 17 Feb 2021 21:10:57 +0530
Labels:                 app=istio-ingressgateway
                        install.operator.istio.io/owning-resource=istio-install
                        install.operator.istio.io/owning-resource-namespace=istio-system
                        istio=ingressgateway
                        istio.io/rev=default
                        operator.istio.io/component=IngressGateways
                        operator.istio.io/managed=Reconcile
                        operator.istio.io/version=1.9.0
                        release=istio
Annotations:            deployment.kubernetes.io/revision: 1
```
Ideally, it should be on pods and services? 

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Label should be added to pods/services (to be decided, but pods is ideal)

**Steps to reproduce the bug**
Apply `IstioOperator` CR mentioned in this issue and check pods and deployments for additional labels.
