### ISSUE TITLE
Restric IPs able to access Deployment via gateway

### ISSUE THREAD

**Issue by pavanfhw** [istio/istio#30895]
I am using Istio on a cluster and I would like to expose a elasticsearch publicly but restrict the IP that are able to access it.

I am exposing the elasticsearch via gateway. I can access it via `http://elasticsearch.my.host`. I would like to use an Istio AuthorizationPolicy to allow only certain IPs to reach the pod.
But I am not being able to do so. The problem is the only IPs that matter to the AuthorizationPolicy are `10.42.0.0/16`. If I block `10.42.0.0/16`, no request can get to the pod. If I allow `10.42.0.0/16`, all requests can access the pod.
How do I configure Istio to get the client real IP address so the AuthorizationPolicy can filter them correctly?
Are AuthorizationPolicys only meant to be used for the Istio ingress gateway or I can use to regulate access to deployments for example? Is it possible to block IPs the way I intent to do?

My manifests:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway
  namespace: elasticsearch
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - "my.host"
      - "*.my.host"
  ```
```
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elasticsearch
spec:
  ports:
  - name: elasticsearch
    targetPort: 9200
    port: 9200
  selector:
    app: elasticsearch
```
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  namespace: elasticsearch
  name: elasticsearch-policy
spec:
  selector:
    matchLabels:
      app: elasticsearch 
  action: ALLOW 
  rules:
  - from:
    - source:
        remoteIpBlocks: ["<ALLOWED IP>"]
 ```
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: elasticsearch
  namespace: elasticsearch
spec:
  hosts:
  - "elasticsearch.my.host"
  gateways:
  - gateway
  http:
  - route:
    - destination:
        port:
          number: 9200
        host: elasticsearch
```
[ ] Docs
[ ] Installation
[] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

`curl http://elasticsearch.my.host` shoud be blocked in case I don't add my IP to the allowed IPs

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
client version: 1.9.0
control plane version: 1.9.0
data plane version: 1.9.0 (2 proxies)

Client Version: v1.18.4+k3s1
Server Version: v1.18.4+k3s1
**How was Istio installed?**
istioctl install --set profile=default
**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
