### ISSUE TITLE
host_rewrite_header not working in istio config

### ISSUE THREAD

**Issue by VinothChinnadurai** [istio/istio#30925]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

This my external request call:  `curl -H "x-fw-real-host: mavericksv3nw1045.xyz.com"  http://subdomain.xyz.internal/api/channels`

For this external request, I try to overwrite the host header `subdomain.xyz.internal` by this custom header value `x-fw-real-host` and at same time my endpoint has to be changed based on the same custom header. Say for this `mavericksv3nw1045.xyz.com`, I need to make a call to `mavericks.xyz.internal` instead of `subdomain.xyz.internal`

[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
 I tried to achieve that via the combination of lua filter + Virtual service. But I need that Lua filter needs to be run post Virtual service match.

**Steps to reproduce the bug**
1. Create a service entry & virtual service for external service request
[This will set the destination endpoint as `mavericks.xyz.internal`]
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: xyz
  namespace: istio-system
spec:
  hosts:
  - subdomain.xyz.internal
  location: MESH_EXTERNAL
  ports:
  - name: http
    number: 80
    protocol: HTTP
  resolution: DNS


apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: xyz-external-routes
  namespace: istio-system
spec:
  hosts:
    - subdomain.xyz.internal
  http:
  - match:
    - port: 80
      headers:
        x-fw-real-host:
          regex: ".*mavericksv3.*"
      
    route:
    - destination:
        host: mavericks.xyz.internal
        port:
          number: 90
      weight: 100
```
2. Envoy filter with lua 
[This will get the value of custom header and override the authority header]
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: outbound-filter
  namespace: istio-system
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_OUTBOUND
        listener:
          portNumber: 80
          filterChain:
            filter:
              name: envoy.http_connection_manager
              subFilter:
                name: envoy.router
      patch:
        operation: INSERT_AFTER
        value:
          name: envoy.lua
          typed_config:
            '@type': type.googleapis.com/envoy.config.filter.http.lua.v2.Lua
            inlineCode: |
              -- add a version to ensure the config's been swapped out while iterating on code changes
              function version()
                  return "v1"
              end
              function logWarn(handle, value)
                  handle:logWarn(version() .. ": " .. value)
              end
              
              function envoy_on_request(request_handle)
                  logWarn(request_handle, "START DISPLAYING REQUEST HEADERS")
                  local log_headers = request_handle:headers()
               
                  hostName = log_headers:get("x-fw-real-host")
                  log_headers:replace(":authority", hostName)
                  logWarn(request_handle, "END DISPLAYING REQUEST HEADERS")
              end  
```
Tried with different options like INSERT_AFTER /INSERT_BEFORE/MERGE but it's not getting apply after the above virtual service match. So I am unable to achieve my expected request handle.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

client version: 1.5.8
control plane version: 1.5.8
data plane version: 1.5.8 (49 proxies)

**How was Istio installed?**
Through Istioctl command
```istioctl manifest generate \
     --set values.gateways.istio-ingressgateway.type=NodePort \
     --set values.grafana.enabled=true \
     --set values.tracing.enabled=true \
     --set values.kiali.enabled=true \
     --set values.prometheus.enabled=true \
     --set values.kiali.dashboard.jaegerURL=http://jaeger-query:16686 \
     --set values.kiali.dashboard.grafanaURL=http://grafana:3000 > $HOME/install_istio.yml
    
   kubectl apply -f $HOME/install_istio.yml
```
**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS EKS Amazon Linux

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

https://gist.github.com/VinothChinnadurai/419e8db690ff0c9d169328cb2ba25232#file-gistfile1-txt-L15291
https://gist.github.com/VinothChinnadurai/419e8db690ff0c9d169328cb2ba25232#file-gistfile1-txt-L24978

**Comment by VinothChinnadurai** [comment]
@ramaraochavali @gargnupur @songford @bianpengyuan  can anybody help me out on this. We blocked due to this

**Comment by bianpengyuan** [comment]
why use lua filter instead of https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRewrite

**Comment by VinothChinnadurai** [comment]
@bianpengyuan  Yeah you are right, but I want that `:authority` header has to be overwritten based on whatever value given in `x-fw-real-host`. We cant set the value dynamically in HTTPRewrite right.. correct me if I am wrong?

**Comment by bianpengyuan** [comment]
> @bianpengyuan Yeah you are right, but I want that :authority header has to be overwritten based on whatever value given in x-fw-real-host. We cant set the value dynamically in HTTPRewrite right.. correct me if I am wrong?

I see, yeah that makes sense. Sorry I am not familiar with lua filter, not sure how to troubleshoot this.

**Comment by VinothChinnadurai** [comment]
oh.. Not a problem. Thanks for your quick responses 👍 . Can somebody else help me out here? @ramaraochavali

**Comment by VinothChinnadurai** [comment]
Hey folks, Tried out this and it looks its fixing the problem
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: external-routes
  namespace: istio-system
spec:
  hosts:
    - xyz.abc.internal
  http:
  - match:
    - headers:
       x-fw-real-host:
         regex: .*mavericks.*
    route:
    - destination:
        host: xyz1.abc.internal
        port:
          number: 90
      weight: 100
  - match:
    - port: 80
    route:
    - destination:
        host: xyz.abc.internal
        port:
          number: 80
      weight: 100

-------

apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: host-rewrite
  namespace: istio-system
spec:
  configPatches:
    - applyTo: HTTP_ROUTE
      match:
        routeConfiguration:
          vhost:
            name: "xyz.abc.internal:80"
            route:
              action: ANY
      patch:
        operation: MERGE
        value:
            route:
              auto_host_rewrite_header: x-fw-real-host
```

Thanks again for quick response @bianpengyuan & everyone :)
