### ISSUE TITLE
Virtual service with certificate as request header

### ISSUE THREAD

**Issue by liavyona** [istio/istio#30926]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
I'm trying to raise the following virtual service
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: example-virtual-service
  namespace: example
spec:
  gateways:
  - istio-system/istio-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /app/
    rewrite:
      uri: /
    route:
    - destination:
        host: example-host
        port:
          number: 8000
      headers:
        request:
          add:
            X-SSL-Client-Certificate: '-----BEGIN%20CERTIFICATE-----%0AMIIC1..........%0A-----END%20CERTIFICATE-----%0A'
```
Without the header I can easily `curl` to my application ('200 OK') but with the certificate as an header it fails (`404 Not Found`). I also get this warning that I bet it is related but it is an warning to an error: `warning    envoy config    gRPC config for type.googleapis.com/envoy.config.route.v3.RouteConfiguration rejected: field '20CERTIFICATE-----' not supported as custom header`.
If I change the value from the encoded certificate to `example` for example I get the value successfully in my logs ` Request has env of HTTP_X: HTTP_X_SSL_CLIENT_CERTIFICATE with value: example`. 

I need to pass the certificate as an header. Anyway to do so?

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
I can set any value as an header.

**Steps to reproduce the bug**
Load a virtual service with a certificate as a request header.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
# istio
client version: 1.8.2
control plane version: 1.8.1
data plane version: 1.8.1 (8 proxies)

# k8s
Client Version: v1.19.3
Server Version: v1.18.9-eks-d1db3c

# helm
v3.3.4+ga61ce56
```

**How was Istio installed?**
`istioctl`
**Environment where the bug was observed (cloud vendor, OS, etc)**
EKS

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
