### ISSUE TITLE
Filter liveness probe from prometheus

### ISSUE THREAD

**Issue by ConnorGraham** [istio/istio#30928]
Similar to https://github.com/istio/istio/issues/10336, I'd like to see liveness probes excluded or identifiable from prometheus `istio_*` counts.

If I want to count the number of 200 requests from my app I use `istio_requests_total{response_code=200}`. This number isn't even close to accurate as it includes all the liveness probe requests to my `/health` endpoint

**Comment by bianpengyuan** [comment]
One way to achieve this is using metric customization: https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/, where you can mark a time series as health check based on path by adding a label to it.

**Comment by howardjohn** [comment]
Are you disabling the app prober rewrite? https://istio.io/latest/docs/ops/configuration/mesh/app-health-check/

**Comment by bianpengyuan** [comment]
Close due to no response. Please reopen if you can provide more detail. Thanks!

**Comment by psandhu79** [comment]
@bianpengyuan @howardjohn i also have the same request I am trying to create accurate SLI/SLOs based on user traffic which method should I use to to exclude the following path /api/health ?

**Comment by bianpengyuan** [comment]
@psandhu79 are you seeing prober traffic at prober traffic? The same question as https://github.com/istio/istio/issues/30928#issuecomment-781537140 applies.

**Comment by psandhu79** [comment]
I’m not disabling the probe rewrite

**Comment by bianpengyuan** [comment]
No enable http rewrite should avoid prober traffic go through envoy filter chains thus no stats should be generated.

Is this a pod spec dump from your cluster? with rewrite enabled, I would expect livenss prober to be something like:

```yaml
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /app-health/liveness-http/livez
        port: 15020
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
```
