### ISSUE TITLE
Removing podAnnotations from IstioOperator does not update Deployment pod template

### ISSUE THREAD

**Issue by wujiaqi** [istio/istio#30927]
**Bug description**

Removing podAnnotations from IOP managed Ingress Gateway does not remove the annotations from Deployments it owns.

I am using Operator to manage an Ingress Gateway (IG) deployment. The IG pods have a set of annotations. I removed the podAnnotations section from the IOP. The respective change is not being reflected in the Deployment pod spec template after the reconciliation cycle.

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

When removing some podAnnotations from IOP KubernetesResourcesSpec, the respective annotations should be removed from the Deployment owned by this IOP.

**Steps to reproduce the bug**

1. Create an Ingress Gateway deployment with a set of multiple annotations
    ```YAML
    kind: IstioOperator
    ...
    spec:
      ...
      components:
        ingressGateways:
          - name: istio-ingressgateway
            namespace: namespace
            k8s:
             ...
              podAnnotations:
                pod-annotations/annotation1: "true"
                pod-annotations/annotation2: "true"
                pod-annotations/annotation3: "true"
    ```

1. Remove the `podAnnotations` section
1. Observe if Deployment gets correctly updated. The contents of the Deployment annotation `kubectl.kubernetes.io/last-applied-configuration` should contain the correct desired state with no pod template annotations, however the deployment will still have the old annotations present.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

1.9-alpha.3390873d3d0172f911b09d054e6a011688b3c4e4

**How was Istio installed?**

operator-based installation

**Environment where the bug was observed (cloud vendor, OS, etc)**

AWS EKS, proxy images are built on a centos7 base image

**Comment by wujiaqi** [comment]
@therealmitchconnors fyi

**Comment by ostromart** [comment]
could this be a side effect of SSA @richardwxn ?

**Comment by ostromart** [comment]
I can't repro this @wujiaqi. Using a simplified version of your IOP:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: empty
  components:
    base:
      enabled: true
    pilot:
      enabled: true
      k8s:
        podAnnotations:
          pod-annotations/annotation1: "true"
          pod-annotations/annotation2: "true"
```
Install to a clean GKE 1.18 cluster using master version of istioctl:

```
ic install -f ~/temp/iop.yaml
```
Verify both annotations are present in istiod Deployment. 
Remove annotation2 from iop.yaml and rerun ic command, annotation2 is gone from istiod Deployment. 
Repeated the same experiment with in-cluster controller with the same result (installed using `ic operator init -f ~/temp/iop.yaml --hub=gcr.io/istio-testing --tag=latest`, then used kc edit on the in-cluster iop).
