### ISSUE TITLE
Inbound stats can not split by different hosts

### ISSUE THREAD

**Issue by dozer47528** [istio/istio#30951]
**Describe the feature request**

Istio stats filter do not have the stats of circuit breaker and outlier detection.

So we enabled the Envoy stats based on this docs: https://istio.io/latest/docs/ops/configuration/telemetry/envoy-stats/

It works well for outbound traffic, but for inbound traffic, Istio have some problems when we have multiple service bind with same pod.

Since 1.8.x, the inbound cluster name generated by Istio will be `inbound|80||`, so Envoy can not tell the difference between traffic from difference services.The stats will be put together.

**Describe alternatives you've considered**

1. Generate different inbound cluster for different hosts.
2. In http route config, add `virtualhost` for each host instead of use a single wildcard virtual host.

[x] Networking

**Additional context**

Example resources:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/statsInclusionPrefixes: cluster.inbound,cluster.outbound # enable Envoy stats
      labels:
        app: nginx
        version: v1
    spec:
      containers:
      - name: nginx
        image: nginx:stable
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
    targetPort: 80
  selector:
    app: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx2
  labels:
    app: nginx2
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
    targetPort: 80
  selector:
    app: nginx
```
