### ISSUE TITLE
TLS origination for egress traffic fails with handshake error

### ISSUE THREAD

**Issue by shake82** [istio/istio#30966]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

Following the Task described in the Docs for **TLS origination for egress traffic** (https://istio.io/latest/docs/tasks/traffic-management/egress/egress-tls-origination/), the laid out example works perfectly with a 200 response:
```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: edition-cnn-com
spec:
  hosts:
  - edition.cnn.com
  ports:
  - number: 80
    name: http-port
    protocol: HTTP
    targetPort: 443
  - number: 443
    name: https-port
    protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: edition-cnn-com
spec:
  host: edition.cnn.com
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 80
      tls:
        mode: SIMPLE # initiates HTTPS when accessing edition.cnn.com
EOF
```
bash > ```kubectl exec "${SOURCE_POD}" -c sleep -- curl -sSL -o /dev/null -D - http://edition.cnn.com/politics```

Logs: ```[2021-02-19T21:18:21.172Z] "GET /politics HTTP/1.1" 200 - "-" 0 1285057 29 8 "-" "curl/7.69.1" "ced03081-fe0f-40b0-9787-66b5f253921d" "edition.cnn.com" "151.101.1.67:443" outbound|80||edition.cnn.com 10.0.3.17:41492 151.101.129.67:80 10.0.3.17:51716 - default```

But doing the same thing for another external service fails with a 503 response:

```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: api-openbrewerydb-org
spec:
  hosts:
  - api.openbrewerydb.org
  ports:
  - number: 80
    name: http-port
    protocol: HTTP
    targetPort: 443
  - number: 443
    name: https-port
    protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: api-openbrewerydb-org
spec:
  host: api.openbrewerydb.org
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 80
      tls:
        mode: SIMPLE # initiates HTTPS when accessing api.openbrewerydb.org
EOF
```
bash > ```kubectl exec "${SOURCE_POD}" -c sleep -- curl -sS -o /dev/null -D - http://api.openbrewerydb.org/breweries```

Logs: ```[2021-02-19T21:18:13.557Z] "GET / HTTP/1.1" 503 UF,URX "TLS error: 268436496:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE 268435610:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO" 0 273 52 - "-" "curl/7.69.1" "1af4844b-6350-4032-9cd4-f41ba6ac4ffd" "api.openbrewerydb.org" "172.67.188.242:443" outbound|80||api.openbrewerydb.org - 104.21.65.56:80 10.0.3.17:33258 - default```

I cannot see any discernible difference between *api.openbrewerydb.org* and *edition.cnn.com* so it stumps me why one would cause a handshake error and the other wouldnt. If TLS origination is not used then both curl requests work for 80 and 443 ports

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

HTTP request to external service (port 80) would be redirected to port 443 with TLS origination

**Steps to reproduce the bug**
1. Create ServiceEntry with port redirect and Destination rule with TLS origination
```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: api-openbrewerydb-org
spec:
  hosts:
  - api.openbrewerydb.org
  ports:
  - number: 80
    name: http-port
    protocol: HTTP
    targetPort: 443
  - number: 443
    name: https-port
    protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: api-openbrewerydb-org
spec:
  host: api.openbrewerydb.org
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 80
      tls:
        mode: SIMPLE # initiates HTTPS when accessing api.openbrewerydb.org
EOF
```
2. Create the sleep pod mentioned in the Docs
3. Execute ```kubectl exec "${SOURCE_POD}" -c sleep -- curl -sS -o /dev/null -D - http://api.openbrewerydb.org/breweries```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
client version: 1.8.1
control plane version: 1.8.1
data plane version: 1.8.1 (2 proxies)
```
**How was Istio installed?**
```
istioctl install --set profile=default --set meshConfig.accessLogFile=/dev/stdout -y 
```

**Environment where the bug was observed (cloud vendor, OS, etc)**

AWS EKS

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

[bug-report.zip](https://github.com/istio/istio/files/6013035/bug-report.zip)
