### ISSUE TITLE
Unable to get TLS origination working with external MongoDB

### ISSUE THREAD

**Issue by michaellzc** [istio/istio#30975]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

[X] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Ability to connect to external managed MongoDB using plain TCP connection from the pod and have the sidecar do the TLS Origination to the external MongoDB.

TLS is mandatory for the external MongoDB, using a self-signed certificate, and a CA is provided.

**Steps to reproduce the bug**

Deploy the following. The MongoDB instance is a 3-node cluster, I created a set of `ServiceEntry` and `DestinationRule` for each one of the host.

`serviceentry-01.yaml`
```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-mongo-01
  labels:
    release: demo
spec:
  hosts:
  - $HOST_01
  ports:
  - number: 30129
    name: tcp-mongo
    protocol: TCP
  resolution: DNS
  location: MESH_EXTERNAL
```

`destinationrule-01.yaml`
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: external-mongo-01
  labels:
    release: demo
spec:
  host: $HOST_01
  trafficPolicy:
    tls:
      mode: SIMPLE
      caCertificates: /etc/my-certs/3eba1f51-4aa9-11e9-a1c2-52b4b41c25ad
      sni: $HOST_01
```

`test-client.yaml`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-client
  namespace: demo
  labels:
    app: mongo-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-client
  template:
    metadata:
      labels:
        app: mongo-client
      annotations:
        sidecar.istio.io/logLevel: debug
        sidecar.istio.io/inject: "true"                                                                                 
        sidecar.istio.io/userVolumeMount: '[{"name":"demo-certs", "mountPath":"/etc/my-certs", "readonly":true}]'
        sidecar.istio.io/userVolume: '[{"name":"demo-certs", "secret":{"secretName":"demo-certs"}}]'
    spec:
      containers:
        - image: mongo:4
          name: mongo-client
          command:
            - sleep
          args: 
            - infinity
```

`exec` into the test pod, and run the following

```bash
mongo "mongodb://$USERNAME:$PASSWORD@$HOST_01:30129,$HOST_02:30129,$HOST_02:30129/db?authSource=admin&replicaSet=replset&tls=true"
```

It will hang for a while, then eventually show the following error message

```
{"t":{"$date":"2021-02-20T05:28:22.621Z"},"s":"I",  "c":"NETWORK",  "id":4333208, "ctx":"ReplicaSetMonitor-TaskExecutor","msg":"RSM host selection timeout","attr":{"replicaSet":"replset","error":"FailedToSatisfyReadPreference: Could not find host matching read preference { mode: \"primary\", tags: [ {} ] } for set replset"}}
```

NOTE: I have tried changing `spec.trafficPolicy.tls.mode=DISABLE`, and send TLS traffic directly from the Pod, and it works.

```bash
mongo --tls --tlsCAFile <CA_FILE> "mongodb://$USERNAME:$PASSWORD@$HOST_01:30129,$HOST_02:30129,$HOST_02:30129/db?authSource=admin&replicaSet=replset&tls=true"
```

You can find logs of the proxy from [here](https://gist.github.com/ExiaSR/3f90ef16f8f4b783f9d4a134e1363f72).

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
$ istioctl version --remote
client version: 1.9.0
control plane version: 1.10-alpha.765256fe5dfc84805a6ce3cfa5fa1b7b640898d3
data plane version: 1.10-alpha.765256fe5dfc84805a6ce3cfa5fa1b7b640898d3 (2 proxies)

$ kubectl version --short
Client Version: v1.19.3
Server Version: v1.19.1

$ helm version --short
v3.5.2+g167aac7
```

**How was Istio installed?**

Following the [Istio Operator Install](https://istio.io/latest/docs/setup/install/operator/).

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-controlplane
spec:
  profile: default
```

**Environment where the bug was observed (cloud vendor, OS, etc)**

`kind`

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
