### ISSUE TITLE
multiple tls settings on the same port on one gateway possible

### ISSUE THREAD

**Issue by yalctay93** [istio/istio#30978]
Hello, 

is it possible to use multiple tls settings on a gateway just like this:

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: emea-int-mg0001-r0001-gw-tswxc2
  namespace: istio-system
spec:
  selector:
    app: emea-int-mg0001 # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - dummy.com
    tls:
      mode: MUTUAL
      credentialName: secret-name1
      subjectAltNames:
      - something
  - port:
      number: 443
      name: https2
      protocol: HTTPS
    hosts:
    - dummy.com
    tls:
      mode: SIMPLE
      credentialName: secret-name2
      subjectAltNames:
      - something
```

Can I use TLS mode SIMPLE and TLS mode MUTUAL on the same port 443 just with a differnet port-name?

We are trying to figure out how it would be possible to use a Gateway deployment with the same host/port combination but with different TLS modes. As far as I know, we cannot use the same Gateway with host/port combination twice - that is why this question came up on my head.

How would we configure a gateway that supports multiple TLS modes on the same port?

Atleast when I deploy it like that, I dont see any error during “istioctl analyze”.
Is the above configuration viable?
