### ISSUE TITLE
Allow compression for the Envoy stats endpoint

### ISSUE THREAD

**Issue by svenwltr** [istio/istio#30987]
**Describe the feature request**

It should be possible to enable gzip compression for the Envoy stats endpoint (`http://127.0.0.1:15090/stats/prometheus`) to save some bandwidth. Currently it does not seem to be the case:

```
$ kubectl exec -it my-pod-0 -c server -- curl -o /dev/null -vsS --compressed http://127.0.0.1:15090/stats/prometheus
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 15090 (#0)
> GET /stats/prometheus HTTP/1.1
> Host: 127.0.0.1:15090
> User-Agent: curl/7.61.1
> Accept: */*
> Accept-Encoding: deflate, gzip
> 
< HTTP/1.1 200 OK
< content-type: text/plain; charset=UTF-8
< cache-control: no-cache, max-age=0
< x-content-type-options: nosniff
< date: Fri, 19 Feb 2021 10:42:25 GMT
< server: envoy
< x-envoy-upstream-service-time: 2
< transfer-encoding: chunked
< 
{ [26267 bytes data]
* Connection #0 to host 127.0.0.1 left intact
```

**Describe alternatives you've considered**

I tried configuring an EnvoyFilter to enable compression, but I lack knowledge of the Envoy internals and the filter concept.

<details><summary>Details</summary>
<p>

I tried crafting a filter filter, but it does not work. Disclaimer: This is also a [Stackoverflow question](https://stackoverflow.com/questions/66276235/how-to-gzip-stats-endpoint-in-istio). This is my latest attempt:

```
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: gzip
spec:
  workloadSelector:
    labels:
      app: my-pod
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: envoy.http_connection_manager
              subFilter:
                name: envoy.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.compressor
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor
            compressor_library:
              name: text_optimized
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.compression.gzip.compressor.v3.Gzip
            remove_accept_encoding_header: true
```

</p>
</details>

[ ] Docs
[ ] Installation
[x] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

Currently, we have around 100 Pods with an Istio sidecar and we are aiming to increase that number. For scaling reasons we did split our Prometheus instances into two parts: One for the Envoy Metrics and one for the actual application metrics. This means we disabled metric merging and are pointing one Prometheus instance directly to `:15090/stats/prometheus` endpoint of each pod.
