### ISSUE TITLE
Istioctl opens default ingress gateways ports even when overriden

### ISSUE THREAD

**Issue by fbsb** [istio/istio#30995]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

When installing istio with istioctl, default ports on ingress gateways are opened even when overriden in the istio operator manifest.

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

I was expecting that when explicitly defining `ports` or `meshExpansionPorts` on an ingress gateway only those ports are opened on the service.

**Steps to reproduce the bug**

Given following istio operator manifest:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
  namespace: istio-system
spec:
  hub: istio
  tag: 1.7.7
  profile: empty
  components:
    base:
      enabled: true
    cni:
      enabled: true
    pilot:
      enabled: true
    ingressGateways:
      - enabled: true
        name: istio-ingressgateway
  values:
    gateways:
      istio-ingressgateway:
        ports:
          - name: https
            port: 443
            targetPort: 8443
          - name: tls
            port: 15443
            targetPort: 15443
        meshExpansionPorts:
          - name: tcp-istiod
            port: 15012
            targetPort: 15012
    global:
      meshExpansion:
        enabled: true
      multiCluster:
        enabled: true
```

Generate k8s manifests
```
istioctl -f iop.yaml > istio_generated.yaml
```

Inspecting `istio_generated.yaml` one finds that the `istio-ingressgateway` service opens more ports than the ones defined in the operator manifest.

```
apiVersion: v1
kind: Service
metadata:
  annotations: null
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
  ports:
  - name: status-port
    port: 15021
    targetPort: 15021
  - name: http2
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8443
  - name: tls
    port: 15443
    targetPort: 15443
  - name: tcp-istiod
    port: 15012
    targetPort: 15012
  - name: tcp-dns-tls
    port: 853
    targetPort: 8853
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  type: LoadBalancer
```

When installing istio with istioctl from the same istio operator manifest
```
$ istioctl install -f iop.yaml
Detected that your cluster does not support third party JWT authentication. Falling back to less secure first party JWT. See https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens for details.
✔ Istio core installed                                                                                                                                                                      
✔ Istiod installed                                                                                                                                                                          
✔ CNI installed                                                                                                                                                                             
✔ Ingress gateways installed                                                                                                                                                                
✔ Installation complete                                                                                                                                                                     
```

And inspecting the deployed ingressgateway service
```
kubectl -n istio-system get service istio-ingressgateway
```

One finds that the service has more open ports than the ones defined in the istio operator manifest.
```
NAME                   TYPE           CLUSTER-IP    EXTERNAL-IP   PORT(S)                                                      AGE
istio-ingressgateway   LoadBalancer   10.100.8.76   <pending>     15021:30003/TCP,80:32097/TCP,443:31962/TCP,15443:30465/TCP   28m
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
$ istioctl version --remote
client version: 1.7.7
control plane version: 1.7.7
data plane version: 1.7.7 (1 proxies)
```

**How was Istio installed?**

Istio was installed with `istioctl install -f $path_to_iop`.
Installing with local manifests makes no difference, even removing the default ports from the values file (`manifests/charts/gateways/istio-ingress/values.yaml`) seems to have no effect.

**Environment where the bug was observed (cloud vendor, OS, etc)**

Initially observed in our bare metal k8s cluster installation.
Can also be reproduced in a simple minikube cluster.

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by fbsb** [comment]
The only way to close the unneeded ports we found is patching the opened ports with an overlay patch on the ingress gateway

```
...
spec:
  ingressGateways:
    - enabled: true
      name: istio-ingressgateway
      k8s:
        overlays:
          - kind: Service
            name: istio-ingressgateway
            patches:
              - path: spec.ports[name:status-port]
              - path: spec.ports[name:http2]
              - path: spec.ports[name:tcp-dns-tls]
...
```

**Comment by howardjohn** [comment]
I am pretty sure if you follow the steps in https://preliminary.istio.io/latest/docs/setup/install/istioctl/#configure-gateways it will get the behavior you desire as well. 

This still should probably behave differently if you configure it the way you did, though

**Comment by fbsb** [comment]
Unfortunately configuring the ports this way also does not really work as intended.

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
  namespace: istio-system
spec:
  hub: istio
  tag: 1.7.7
  profile: empty
  components:
    base:
      enabled: true
    cni:
      enabled: true
    pilot:
      enabled: true
    ingressGateways:
      - enabled: true
        name: istio-ingressgateway
        k8s:
          service:
            ports:
              - name: https
                port: 443
                targetPort: 8443
              - name: tls
                port: 15443
                targetPort: 15443
              - name: tcp-istiod
                port: 15012
                targetPort: 15012
  values:
    global:
      meshExpansion:
        enabled: true
      multiCluster:
        enabled: true
```

Installing istio with this iop causes an error and the installation fails.

```
$ istioctl install -f iop.yaml
Detected that your cluster does not support third party JWT authentication. Falling back to less secure first party JWT. See https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens for details.
✔ Istio core installed                                                                                                                                                                      
✔ Istiod installed                                                                                                                                                                          
  Processing resources for CNI, Ingress gateways. Waiting for Pod/istio-system/istio-cni-node-ggcqv                                                                                         2021-02-23T08:19:34.021181Z     error   installer       failed to create "Service/istio-system/istio-ingressgateway": Service "istio-ingressgateway" is invalid: [spec.ports[3].name: Duplicate value: "tcp-istiod", spec.ports[3]: Duplicate value: core.ServicePort{Name:"", Protocol:"TCP", AppProtocol:(*string)(nil), Port:15012, TargetPort:intstr.IntOrString{Type:0, IntVal:0, StrVal:""}, NodePort:0}]
✘ Ingress gateways encountered an error: failed to create "Service/istio-system/istio-ingressgateway": Service "istio-ingressgateway" is invalid: [spec.ports[3].name: Duplicate value: "tcp-istiod", spec.ports[3]: Duplicate value: core.ServicePort{Name:"", Protocol:"TCP", AppProtocol:(*string)(nil), Port:15012, TargetPort:intstr.IntOrString{Type:0, IntVal:0, StrVal:""}, NodePort:0}]
✔ CNI installed                                                                                                                                                                             
- Pruning removed resources                                                                                                                                                                 Error: failed to install manifests: errors occurred during operation
```

It seems the service now has duplicate ports plus a default port that has not been explicitly defined.

```
...
spec:
  ports:
  - name: https
    port: 443
    targetPort: 8443
  - name: tls
    port: 15443
    targetPort: 15443
  - name: tcp-istiod
    port: 15012
    targetPort: 15012
  - name: tcp-istiod
    port: 15012
    targetPort: 15012
  - name: tcp-dns-tls
    port: 853
    targetPort: 8853
...
```
