### ISSUE TITLE
Pod or statefulset can not access itself

### ISSUE THREAD

**Issue by aalmazanarbs** [istio/istio#30990]
**Bug description**
With Istio sidecar enabled, when a pod try to access itself using hostname, Istio envoy is dropping the connection. The same connection works accessing localhost or pointing hostname to localhost in /etc/hosts.

[X] Networking

**Expected behavior**
Pod can access itself using its DNS. I dont know if the problem is related with Istio or a miss configuration.

**Steps to reproduce the bug**
Configure Istio with `global.mtls.enabled: true,` `MeshPolicy -> peers: -mtls: {}` and `istio-system DestinationRule *.local ISTIO_MUTUAL`

Deploy statefulset like this:
```
---
apiVersion: v1
kind: Service
metadata:
  namespace: domain
  name: myapp
  labels:
    app: myapp
spec:
  ports:
    - name: tcp
      protocol: TCP
      port: 1111
      targetPort: 1111
  clusterIP: None
  selector:
    app: myapp
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: domain
  name: myapp
  labels:
    app: myapp
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: myapp-access
  namespace: domain
spec:
  rules:
    - services: ["myapp.domain.svc.cluster.local"]
      constraints:
        - key: "destination.port"
          values: [ "1111"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: bind-myapp-access
  namespace: domain
spec:
  subjects:
    - properties:
        source.principal: "cluster.local/ns/domain/sa/myapp"
  roleRef:
    kind: ServiceRole
    name: "myapp-access"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: domain
  name: myapp
  labels:
    app: myapp
spec:
  serviceName: myapp
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: myapp
      containers:
        - name: myapp
          ports:
            - name: tcp
              containerPort: 1111
```
If you try for example telnet or ssl conect to `myapp-0.myapp.domain.svc.cluster.local:1111` you will get a server connection close.

If you check the istio-proxy containers logs, the outbound request is not traced but the inbound request yes. If you try to connect to `myapp-1.myapp.domain.svc.cluster.local:1111` it works and inbound and outbound traffic is traced by istio-proxy.

**Version**
Istio version 1.3.1
Kubernetes version 1.14.0
Helm version 2.15.2

**How was Istio installed?**
Using Helm

**Environment where the bug was observed (cloud vendor, OS, etc)**
K8s in AWS installed using Kops
