### ISSUE TITLE
when VirtualService Status Error，istiod can not start

### ISSUE THREAD

**Issue by zhengqisong** [istio/istio#31014]
istio version: 1.18.3
kubernetes:1.18.10

**Bug description**
when VirtualService config error, istiod can not started

istiod error log:
```
{"level":"error","time":"2021-02-23T06:40:18.954868Z","scope":"klog","msg":"k8s.io/client-go@v0.19.3/tools/cache/reflector.go:156: Failed to watch *v1alpha3.VirtualService: failed to list *v1alpha3.VirtualService: v1alpha3.VirtualServiceList.Items: []v1alpha3.VirtualService: v1alpha3.VirtualService.v1alpha3.VirtualService.Status: unmarshalerDecoder: unknown value \"Error\" for enum istio.analysis.v1alpha1.AnalysisMessageBase_Level, error found in #10 byte of ...|l+v1\\\"\"}]}},{\"apiVer|..., bigger context ...|\"map-nginx.project-1925.svc.cluster.local+v1\\\"\"}]}},{\"apiVersion\":\"networking.istio.io/v1alpha3\",\"ki|...[]"}
```
error VirtualService config
```
spec:
exportTo:
- .
gateways:
- gateway-122-71
hosts:
- nginx-map.gw-wso2t-sy-in.earth.xcloud.lenovo.com
http:
- match:
- uri:
prefix: /
rewrite:
uri: /
route:
- destination:
host: map-nginx.project-1925.svc.cluster.local
port:
number: 80
subset: v1
weight: 100
status:
validationMessages:
- code: IST0101
documentation_url: https://istio.io/docs/reference/config/analysis/ist0101/?ref=status-controller
level: Error
message: 'Referenced host+subset in destinationrule not found: "map-nginx.project-1925.svc.cluster.local+v1"'
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Comment by hzxuzhonghu** [comment]
@zhengqisong can u provide a complete well indented vs to help us understand what happened?

**Comment by xichengliudui** [comment]
+1

**Comment by howardjohn** [comment]
yikes. We need to fix this. One issue - I don't know how :slightly_smiling_face:

**Comment by samirmajen** [comment]
Just ran into this exact problem when upgrading istio - had to delete the offending resources for the upgrade to work correctly

**Comment by howardjohn** [comment]
@jasonwzm do you know if its possible to discard bad configs instead of block?

**Comment by esnible** [comment]
I removed the strict deserialization from CLI things and expect it will be easy to fix for istiod.

@howardjohn To test any fixes, I need to be able to reproduce.  Two years ago it was easy to put bogus stuff in `status` using commands like `kubectl patch vs bookinfo --type=json --patch='[{"op": "replace", "path": "/status", "value": {"startTime": "2019-06-05T17:52:46Z", "state": "ACTIVE"}}]'`.  Kubernetes no longer allows it.  I made two guesses as to how to enable adding bogus stuff to /status and failed:

```
// Doesn't work, schema required
kubectl patch crd virtualservices.networking.istio.io --type='json' -p='[{"op": "remove", "path": "/spec/versions/0/schema"}]'

// Doesn't work "no change"
kubectl patch crd virtualservices.networking.istio.io --type='json' -p='[{"op": "remove", "path": "/metadata/managedFields"}]'
```

@therealmitchconnors 
Any idea what protects /status?  I know it is something in the API server, because if I do `--dry-run=client` I can set the status, but if I do `--dry-run=server` the status does not get patched.

**Comment by howardjohn** [comment]
You might need a raw api call. when you do patch it probably sends a PUT
call to /crds/virtualservices/foo or similar - we need it to go to
/crds/virtualservices/foo/status. You might be able to add -v9 to the
kubectl command to get the API its calling, add /status, then call it with
`kubectl patch --raw`?

**Comment by esnible** [comment]
There is no `patch --raw` in _kubectl_ (I checked 1.19 and 1.20).

I tried
```
MYAPISERVER=c7.us-south.containers.cloud.ibm.com:28514
echo '{"status": "banana"}' | kubectl create --raw https://${MYAPISERVER}/apis/networking.istio.io/v1beta1/namespaces/default/virtualservices/httpbin/status -f -
```
... but it fails with 'create is not supported on resources of kind "virtualservices.networking.istio.io"'

**Comment by howardjohn** [comment]
https://github.com/kubernetes/kubectl/issues/564

**Comment by jasonwzm** [comment]
It seems to be an issue when analysis is enabled during startup and the unmarshaller encountered an issue. I vaguely remember that we changed the format of message level we put in status in CRDs?

**Comment by esnible** [comment]
To manually put garbage into status, first install Istio with WITHOUT `values.global.istiod.enableAnalysis=true` and WITHOUT `values.pilot.env.PILOT_ENABLE_STATUS=true`.  Then

```
kubectl proxy &
curl -k -s -X PATCH -H "Accept: application/json, */*" \
-H "Content-Type: application/merge-patch+json" \
127.0.0.1:8001/apis/networking.istio.io/v1beta1/namespaces/default/virtualservices/httpbin/status \
--data '{"status":{"monkey":"banana"}}'
```

At this point, for master, I have no problem restarting or re-installing Istio with or without analysis.  It is possible this was fixed in an earlier version.  Checking...

**Comment by esnible** [comment]
I have a backtrace.  istio.io/istio is not in the path.  istio.io/api is generated code.  Not sure what to do.

A user with authority to do `kubectl proxy` and modify any VirtualService can use the technique in https://github.com/istio/istio/issues/31014#issuecomment-802810868 to cause trouble for the control plane.

```
istio.io/api/meta/v1alpha1.(*IstioStatus).UnmarshalJSON(0xc000df93c8, 0xc002c300f0, 0x45, 0x50, 0xc000df93c8, 0x6a48b38)
	/Users/snible/go/pkg/mod/istio.io/api@v0.0.0-20210318104759-fbefbc937cef/meta/v1alpha1/status_json.gen.go:35 +0x18d
github.com/json-iterator/go.(*unmarshalerDecoder).Decode(0xc001f6dc40, 0xc002abf1b0, 0xc000f03050)
	/Users/snible/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_marshaler.go:200 +0xdb
github.com/json-iterator/go.(*referenceDecoder).Decode(0xc001f6dc50, 0xc000df93c8, 0xc000f03050)
	/Users/snible/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_optional.go:128 +0x68
github.com/json-iterator/go.(*structFieldDecoder).Decode(0xc001f958e0, 0xc000df9200, 0xc000f03050)
	/Users/snible/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_decoder.go:1054 +0x78
github.com/json-iterator/go.(*fiveFieldsStructDecoder).Decode(0xc000b38e40, 0xc000df9200, 0xc000f03050)
	/Users/snible/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_decoder.go:739 +0x311
github.com/json-iterator/go.(*sliceDecoder).doDecode(0xc00106bd70, 0xc0002547c8, 0xc000f03050)
	/Users/snible/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_slice.go:86 +0xdd
github.com/json-iterator/go.(*sliceDecoder).Decode(0xc00106bd70, 0xc0002547c8, 0xc000f03050)
	/Users/snible/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_slice.go:60 +0x45
github.com/json-iterator/go.(*structFieldDecoder).Decode(0xc001f95c20, 0xc000254770, 0xc000f03050)
	/Users/snible/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_decoder.go:1054 +0x78
github.com/json-iterator/go.(*fourFieldsStructDecoder).Decode(0xc0010587d0, 0xc000254770, 0xc000f03050)
	/Users/snible/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_decoder.go:697 +0xbf
github.com/json-iterator/go.(*Iterator).ReadVal(0xc000f03050, 0x3ae97c0, 0xc000254770)
	/Users/snible/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:79 +0xc2
github.com/json-iterator/go.(*frozenConfig).Unmarshal(0xc000374c80, 0xc002b57000, 0xc49, 0x1000, 0x3ae97c0, 0xc000254770, 0x0, 0x0)
	/Users/snible/go/pkg/mod/github.com/json-iterator/go@v1.1.10/config.go:348 +0xb7
k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Decode(0xc000226550, 0xc002b57000, 0xc49, 0x1000, 0x0, 0x4033d98, 0xc000254770, 0xc00d5a63302ad750, 0xc059add2, 0x5cdda00, ...)
	/Users/snible/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/runtime/serializer/json/json.go:264 +0x5be
k8s.io/apimachinery/pkg/runtime.WithoutVersionDecoder.Decode(0x3ffcc00, 0xc000226550, 0xc002b57000, 0xc49, 0x1000, 0x0, 0x4033d98, 0xc000254770, 0xc002c24160, 0xc000bc5770, ...)
	/Users/snible/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/runtime/helper.go:252 +0x97
k8s.io/client-go/rest.Result.Into(0xc002b57000, 0xc49, 0x1000, 0x0, 0x0, 0x0, 0xc001337c90, 0x10, 0x0, 0x0, ...)
	/Users/snible/go/pkg/mod/k8s.io/client-go@v0.20.4/rest/request.go:1273 +0xb4
istio.io/client-go/pkg/clientset/versioned/typed/networking/v1alpha3.(*virtualServices).List(0xc002c181c0, 0x407ce28, 0xc000076098, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/snible/go/pkg/mod/istio.io/client-go@v0.0.0-20210218000043-b598dd019200/pkg/clientset/versioned/typed/networking/v1alpha3/virtualservice.gen.go:93 +0x29d
istio.io/client-go/pkg/informers/externalversions/networking/v1alpha3.NewFilteredVirtualServiceInformer.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3c28a4f, ...)
	/Users/snible/go/pkg/mod/istio.io/client-go@v0.0.0-20210218000043-b598dd019200/pkg/informers/externalversions/networking/v1alpha3/virtualservice.gen.go:63 +0x1bc
k8s.io/client-go/tools/cache.(*ListWatch).List(0xc000e16888, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/snible/go/pkg/mod/k8s.io/client-go@v0.20.4/tools/cache/listwatch.go:106 +0x75
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1.1.2(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3c28a4f, ...)
	/Users/snible/go/pkg/mod/k8s.io/client-go@v0.20.4/tools/cache/reflector.go:283 +0x75
k8s.io/client-go/tools/pager.SimplePageFunc.func1(0x407ce28, 0xc000076090, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/snible/go/pkg/mod/k8s.io/client-go@v0.20.4/tools/pager/pager.go:40 +0x75
k8s.io/client-go/tools/pager.(*ListPager).List(0xc002c39e60, 0x407ce28, 0xc000076090, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/snible/go/pkg/mod/k8s.io/client-go@v0.20.4/tools/pager/pager.go:91 +0x175
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1.1(0xc002b7f4a0, 0xc000dfe1c0, 0xc002260870, 0xc002c06860, 0xc002c1a009, 0xc002c06870, 0xc001b83bc0)
	/Users/snible/go/pkg/mod/k8s.io/client-go@v0.20.4/tools/cache/reflector.go:309 +0x1e5
created by k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1
	/Users/snible/go/pkg/mod/k8s.io/client-go@v0.20.4/tools/cache/reflector.go:271 +0x298
```

**Comment by zhengqisong** [comment]
I am test in istio 1.6.8,1.6.13 1.7.4 ,1.7.6,1.8.3 

public-system(the namespace publish service to outward)  has  gateway, virtualservice(exportTo: .)

project-1925(the namespace publish service to namespace`s service) has service, deploy, destinationrule, virtualservice(exportTo: .)  

In <=1.7.4 public-system`s   virtualservice has under error, but istod can restart
```
validationMessages:
- code: IST0101
documentation_url: https://istio.io/docs/reference/config/analysis/ist0101/?ref=status-controller
level: Error
message: 'Referenced host+subset in destinationrule not found: "map-nginx.project-1925.svc.cluster.local+v1"'
```

in 1.7.6 public-system`s   virtualservice no error

upgrade from 1.7.4 to 1.8.3, istiod(1.8.3) canot not start 

upgrade from 1.7.4 to 1.7.6, the public-system`s   virtualservice  error remain, but istiod(1.7.6) can started, and service can be connected.

upgrade from 1.7.4 to 1.7.6, then upgrade from 1.7.6 to 1.8.3, the public-system`s   virtualservice  error remain, but istiod(1.8.3) can not started,
```
{"level":"error","time":"2021-03-22T10:39:08.252656Z","scope":"klog","msg":"k8s.io/client-go@v0.19.3/tools/cache/reflector.go:156: Failed to watch *v1alpha3.VirtualService: failed to list 
*v1alpha3.VirtualService: v1alpha3.VirtualServiceList.Items: []v1alpha3.VirtualService: v1alpha3.VirtualService.v1alpha3.VirtualService.Status: unmarshalerDecoder: unknown value \"Error\" 
for enum istio.analysis.v1alpha1.AnalysisMessageBase_Level, error found in #10 byte of ...|l+v1\\\"\"}]}},{\"apiVer|..., bigger context ...|esh-b.project-1896.svc.frankfurtinp.local+v1\\\"
\"}]}},{\"apiVersion\":\"networking.istio.io/v1alpha3\",\"ki|...[]"}
```

install 1.7.6, then upgrade  upgrade from 1.7.6 to 1.8.3 the public-system`s   virtualservice  no error, istiod(1.8.3) can started

I think This issues  has two bug:
1.  vs check has a bug, destination no support other namespaces destinationrule .

vs in public-system
```
http:                                                                                                                                                                                     
  - match:                                                                                                                                                                                  
    - uri:                                                                                                                                                                                  
        prefix: /                                                                                                                                                                           
    rewrite:                                                                                                                                                                                
      uri: /                                                                                                                                                                                
    route:                                                                                                                                                                                  
    - destination:                                                                                                                                                                          
        host: map-nginx.project-1896.svc.cluster.local                                                                                                                               
        port:                                                                                                                                                                               
          number: 80                                                                                                                                                                        
        subset: v1                                                                                                                                                                          
      weight: 10
```
2. istiod(1.8.3) has a bug for parse VirtualService that has Error(level: Error)
```
status:                                                                                                                                                                                   
    validationMessages:                                                                                                                                                                     
    - code: IST0101                                                                                                                                                                         
      documentation_url: https://istio.io/docs/reference/config/analysis/ist0101/?ref=status-controller                                                                                     
      level: Error      #this line  parse Error                                                                                                                                                                    
      message: 'Referenced host+subset in destinationrule not found: "map-nginx.project-1896.svc.cluster.local+v1"
```
