### ISSUE TITLE
Reevaluate use of server-side apply in the operator

### ISSUE THREAD

**Issue by Monkeyanator** [istio/istio#31028]
Using server-side apply to apply resources that were created with a client-side apply can lead to unexpected results. For example, applying the below configuration will result in `svc` having selectors `app: shell, not-app: shell` rather than overwriting the selector to just `not-app: shell`.

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
  selector:
    app: shell
EOF
cat <<EOF | kubectl apply --server-side -f -
apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  ports:
  - port: 81
    name: http-other
    protocol: TCP
  selector:
    not-app: shell
EOF
```

The particular case that this breaks us for is the [default revision implementation](https://github.com/istio/istio/pull/30843). The design relies on us being able to _totally overwrite_ the `istiod` service. However, the installer will (when the old `istiod` service was installed with installer version `1.8`-) attempt a merge between the old and new `istiod` services leading to broken behavior.

Possible this is working as intended and we can document not to use `defaultRevision` when the existing install is from `1.8`- until after the old control plane has been removed (not sure why 1.8 is the first version that has this behavior, took a cursory look and it seemed like it still uses SSA by default).
