### ISSUE TITLE
docs: AuthorizationPolicy rule matching statement seems wrong

### ISSUE THREAD

**Issue by yanniszark** [istio/istio#31032]
**Bug description**

The docs on AuthorizationPolicy say:

> A match occurs when at least one source, operation and condition matches the request.

I believe the statement should be:
A match occurs when at least one source, operation and **all conditions** matches the request.

I tested it in my cluster by applying the following policy which allowed traffic:
```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
spec:
  rules:
  - when:
    - key: source.principal
      values:
      - '*'
```

and then adding another condition:
```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
spec:
  rules:
  - when:
    - key: source.principal
      values:
      - '*'
    - key: source.principal
      values:
      - 'foo'
```

Traffic is not allowed anymore and it's clear that conditions are ANDed while sources and operations are ORed.

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

I expected the docs to say:

A match occurs when at least one source, operation and **all conditions** matches the request.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.9.0
