### ISSUE TITLE
TLS Connection to external services add 10-15 ms latency

### ISSUE THREAD

**Issue by kaarolch** [istio/istio#31031]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

Currently we have a project that require connects from istio to external services over TLS. For a test purposes we setup Istio on EKS. As a addition we also configure ingress gateway, to support external app connections to our backend via Istio.  

We applied below configuration: 
* Ingress Gateway: 
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ext-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    #- "*"
    - "app.ourdomina.com"
```
* Our external backend endpoint:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: app-ext-backend
spec:
  hosts:
  - app-ext.ourdomain.com
  ports:
  - number: 80
    name: http
    protocol: HTTP
    targetPort: 443
  resolution: DNS
  location: MESH_EXTERNAL
```
*Virtual Services: 
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app
spec:
  hosts:
  - "app.ourdomina.com"
  gateways:
  - ext-gateway
  http:
  - name: external-app
    rewrite:
     authority: app-ext.ourdomain.com
    route:
    - destination:
        host: app-ext.ourdomain.com
        port:
          number: 80

```
* Destination policy: 
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-tls-for-nginx
  namespace: test-routing
spec:
  host: app-ext.ourdomain.com
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE
          sni: app-ext.ourdomain.com
```
Our external serivce`app-ext.ourdomain.com` is pointing to AWS NLB with TLS terminated on it. 

For a test purposes we setup two telegraf (one on EC2 and the second on inside POD). 

During tests we've observed than connection from **telegraf pod ->`istio-proxy` -> external services `app-ext.ourdomain.com` -> NLB -> our backend app**  is slower about 10-15ms compare to connection from **EC2 ->  ingress gateway(`app-ext.ourdomain.com`) -> external services `app-ext.ourdomain.com` -> NLB -> backend app**. 

Below graph display response time from external service when we go via `http://app-ext.ourdomain.com` from **telegraf in pod on EKS ->`istio-proxy` -> external services `app-ext.ourdomain.com` -> NLB -> our backend app**:
<img width="594" alt="image" src="https://user-images.githubusercontent.com/16565131/108888947-104b7d80-760c-11eb-8bfb-eb85533a4683.png">

When we use `https` to reach external app via `https://app-ext.ourdomain.com` (**telegraf in pod on EKS ->`istio-proxy` -> external services `app-ext.ourdomain.com` -> NLB -> our backend app**):: 
<img width="586" alt="image" src="https://user-images.githubusercontent.com/16565131/108889071-396c0e00-760c-11eb-9de4-85acb8b68f93.png">
latency increase for 4-6ms (I guess when we going in passthrough from pod to external service each time telegraf handshake TLS connection and istio probably keepalive current connection and this is fine for use. We also see this diff in logs.
```
[2021-02-23T10:19:41.009Z] "GET / HTTP/1.1" 200 - "-" 0 32 9 9 "-" "Go-http-client/1.1" "90188f25-1657-4fa3-87fe-62e15c166d1b" "app-ext.ourdomain.com" "xxx.xxx.xxxx.xxx:443" outbound|80||app-ext.ourdomain.com 172.21.15.142:40088 xxx.xxx.xxx.xxx:80 172.21.15.142:42780 - default

[2021-02-23T10:19:41.008Z] "- - -" 0 - "-" 634 5918 32 - "-" "-" "-" "-" "xxx.xxx.xxx.xxx:443" PassthroughCluster 172.21.15.142:53430 xxx.xxx.xxx.xxx:443 172.21.15.142:53428 -
```

But we still do not understand why when we create request from external  **EC2 ->  ingress gateway(`app.ourdomain.com`) -> external services `app-ext.ourdomain.com` -> NLB -> backend app** the response time is 3 times faster (`4-6ms`) compare to request from the pod(18-20ms): 
<img width="585" alt="image" src="https://user-images.githubusercontent.com/16565131/108889421-a7183a00-760c-11eb-8c33-2c32169997cb.png">

To test response we use `http_response` plugin, we know this is a worst scenario that we test, each time we open new connection. 
```
[[inputs.http_response]]
      urls = [
         "http://app-ext.ourdomain.com"
        ]
      method = "GET"
      response_timeout = "1s"
      interval = "1s"
```
From our understand connection from external app to backend via istio should be slower (more hops).

[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Connection from `external machines -> istion-gateway-> external services -> nlb -> backend` should be slower or similar to connection from pod inside kubernetes to external app: `pod-> istion-proxy-> external services -> nlb -> backend`.
**Steps to reproduce the bug**

**Version**
kubernetes:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-27T00:38:11Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
Istio:
```
client version: 1.8.3
control plane version: 1.8.3
data plane version: 1.8.1 (9 proxies), 1.8.3 (3 proxies)
```

**How was Istio installed?**
Default installation via istioctl: 
```
istioctl install --set meshConfig.accessLogFile=/dev/stdout
```
**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS EKS with managed nodes. 

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
