### ISSUE TITLE
Deployment for ingress/egress gateways lack the _release_ label in the spec.template.metadata when deployed to a namespace other then istio-system

### ISSUE THREAD

**Issue by primeroz** [istio/istio#31059]
**Bug description**

When deploying an ingress/egress gateway, using the istio-operator, in a namespace other than istio system the deployment will have the `release` label only in the deployment metadata but not the pod template one

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

The deployment is consistent regardless of the namespace where it was deployed

**Steps to reproduce the bug**
* install istio-operator
* Apply the following resource
```
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: standard
  namespace: istio-system
spec:
  components:
    ingressGateways:
    - enabled: true
      k8s:
        hpaSpec:
          maxReplicas: 3
          minReplicas: 2
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: 'kubernetes.io/hostname'
                labelSelector:
                  matchLabels:
                    app: istio-ingressgateway
                    istio: ingressgateway-public
        podDisruptionBudget:
          minAvailable: 2
          selector:
            matchLabels:
              app: istio-ingressgateway
              istio: ingressgateway-public
        service:
          ports:
          - name: http
            port: 80
            targetPort: 8080
          - name: https
            port: 443
            targetPort: 8443
      label:
        app: istio-ingressgateway
        istio: ingressgateway-public
      name: public-ingress
      namespace: istio-system
    - enabled: true
      k8s:
        hpaSpec:
          maxReplicas: 3
          minReplicas: 2
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: 'kubernetes.io/hostname'
                labelSelector:
                  matchLabels:
                    app: istio-ingressgateway-blah
                    istio: ingressgateway-public-blah
        podDisruptionBudget:
          minAvailable: 1
          #selector:
          #  matchLabels:
          #    app: istio-ingressgateway-blah
          #    istio: ingressgateway-public-blah
        service:
          ports:
          - name: http
            port: 80
            targetPort: 8080
          - name: https
            port: 443
            targetPort: 8443
      label:
        app: istio-ingressgateway-blah
        istio: ingressgateway-public-blah
      name: public-ingress-blah
      namespace: default
    pilot:
      enabled: true
      k8s:
        hpaSpec:
          maxReplicas: 3
          minReplicas: 2
  meshConfig:
    accessLogFile: /dev/stdout
    connectTimeout: 5s
    defaultConfig:
      sds:
        enabled: true
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
    enableTracing: false
    ingressClass: istio
  profile: default
  values:
    pilot:
      env:
        PILOT_ENABLE_EDS_FOR_HEADLESS_SERVICES: false
        PILOT_ENABLE_HEADLESS_SERVICE_POD_LISTENERS: true
        PILOT_ENABLE_STATUS: true 
    global:
      istiod:
        enableAnalysis: true
```

* kubectl get deployment -n istio-system public-ingress -o jsonpath="deployment: {.metadata.labels.release}   podtempalte: {.spec.template.metadata.labels.release}"
`deployment: istio   podtempalte: istio%`
* kubectl get deployment -n default public-ingress-blah -o jsonpath="deployment: {.metadata.labels.release}   podtempalte: {.spec.template.metadata.labels.release}"
`deployment: istio   podtempalte: %`

**Version** 
* 1.6.14
* 1.8.3

**How was Istio installed?**
* istio-operator

**Environment where the bug was observed (cloud vendor, OS, etc)** AWS and KinD

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
