### ISSUE TITLE
Support typed_json_format for Envoy access logs

### ISSUE THREAD

**Issue by bbdimitriu** [istio/istio#31060]
**Describe the feature request**
Currently it is possible to configure the IstioOperator resource to enable access logging in JSON format. However there is no option for the logged attributes to be JSON-typed.
It is especially useful when logging attributes that have a JSON structure to not be considered as simple strings and to not be escaped. This is because it is difficult to do structured querying on such logs.

It seems that [Envoy does support this feature](https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#format-dictionaries), but there is no easy way to enable it in the IstioOperator configuration.

Currently JSON access logging is enabled this way for the IstioOperator:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    accessLogFile: /dev/stderr
    accessLogEncoding: JSON
    # the JSON escaping is not necessary with 1.7+ releases: https://github.com/istio/istio/issues/24318
    # The format is documented here: https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#command-operators
    accessLogFormat: |
      {
        "accessLogFormat": "{
            \"method\": \"%REQ(:METHOD)%\",
            \"identity_json\": \"%DYNAMIC_METADATA(envoy.lua:identity-json)%\"
            ...
         }"
      }
```

**Describe alternatives you've considered**
It is possible to create an `EnvoyFilter` with the appropriate Envoy `typed_config`, along the lines specified in #29493, but this is quite inconvenient and more complex, so a configuration option in `IstioOperator` is preferable.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Additional context**
