### ISSUE TITLE
Unexpected listeners configuration when multiple k8s svc match a Gateway

### ISSUE THREAD

**Issue by JRBANCEL** [istio/istio#31084]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
When there are multiple `Gateway` resources selecting the same Envoy deployment on different ports and each port has a Kubernetes `Service` pointing to that port, we see observe some unexpected behavior.

[ X] Networking

**Expected behavior**
Gateway g_A listening on port p_A
Gateway g_B listening on port p_B
K8s Service mapping 80 -> p_A
K8s Service mapping 80 -> p_B

I expect to have the following listeners:
* Gateway g_A config applied on p_A
* Gateway g_B config applied on p_B

**Steps to reproduce the bug**

Install Istio 1.8.2 with `istioctl`.

```
istioctl  proxy-config listeners istio-ingressgateway-68c6579865-l9kkx.istio-system
ADDRESS PORT  MATCH DESTINATION
0.0.0.0 15021 ALL   Inline Route: /healthz/ready*
0.0.0.0 15090 ALL   Inline Route: /stats/prometheus*
```

Install default Gateway:

```
cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gw-80
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
EOF
```

As expected, Istio uses the 80 -> 8080 mapping defined in:

```
kubectl get svc -n istio-system istio-ingressgateway -o yaml
...
  - name: http2
    port: 80             
    protocol: TCP      
    targetPort: 8080
...
```

```
ADDRESS PORT  MATCH DESTINATION
0.0.0.0 8080  ALL   Route: http.80
0.0.0.0 15021 ALL   Inline Route: /healthz/ready*
0.0.0.0 15090 ALL   Inline Route: /stats/prometheus*
```

Now, let's create another Gateway, listening on 8081:

```
cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gw-8081
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 8081
      name: http
      protocol: HTTP
    hosts:
    - "*"
EOF
```

```
ADDRESS PORT  MATCH DESTINATION
0.0.0.0 8080  ALL   Route: http.80
0.0.0.0 8081  ALL   Route: http.8081
0.0.0.0 15021 ALL   Inline Route: /healthz/ready*
0.0.0.0 15090 ALL   Inline Route: /stats/prometheus*
```

and add a Kubernetes Service mapping 80 to 8081:

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: gw-8081 
  namespace: istio-system
spec:
  type: ClusterIP
  selector:
    istio: ingressgateway
  ports:
    - name: http2
      port: 80
      targetPort: 8081
EOF
```

still good:

```
ADDRESS PORT  MATCH DESTINATION
0.0.0.0 8080  ALL   Route: http.80
0.0.0.0 8081  ALL   Route: http.8081
0.0.0.0 15021 ALL   Inline Route: /healthz/ready*
0.0.0.0 15090 ALL   Inline Route: /stats/prometheus*
```

Now, let's delete `istio-system`:

```
kubectl delete  namespace istio-system 
```

recreate it:

```
kubectl create namespace istio-system
```

install the 8081 service back:

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: gw-8081 
  namespace: istio-system
spec:
  type: ClusterIP
  selector:
    istio: ingressgateway
  ports:
    - name: http2
      port: 80
      targetPort: 8081
EOF
```

and finally install Istio with `istioctl`.

Now: 

```
ADDRESS PORT  MATCH DESTINATION   
0.0.0.0 8081  ALL   Route: http.80  
0.0.0.0 15021 ALL   Inline Route: /healthz/ready*
0.0.0.0 15090 ALL   Inline Route: /stats/prometheus* 
```

This doesn't seem correct for two reasons:
1) In the k8s world, ordering doesn't matter and here it does, leading to non-deterministic behavior
2) Shouldn't Istio be able to figure out that there is a Gateway listening on 8081 so it shouldn't consider the k8s svc pointing to that port for the Gateway listening on 80?

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

Tested on 1.7.x and 1.8.x.

**How was Istio installed?**
`istioctl`

**Environment where the bug was observed (cloud vendor, OS, etc)**
GKE

/cc @howardjohn
This is a minimal repro for https://github.com/knative/serving/issues/10160
