### ISSUE TITLE
Probe rewrite doesn't handle `host` field well

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#31087]
```
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - image: docker.io/kennethreitz/httpbin
    name: httpbin
    readinessProbe:
      httpGet:
        host: httpbin.org
        path: /get
        port: 80
        scheme: HTTP
```

Will get rewritten to send requests to `httpbin.org:15020/app-health/httpbin/readyz`.

I would say we just drop the host entirely? The original use case was hostNetwork - we don't support this anyways. See https://github.com/kubernetes/kubernetes/pull/42902

cc @incfly 

Btw, no one noticed this for years, meaning probably no one uses this option, and its a really bad idea (https://github.com/kubernetes/kubernetes/issues/99425). So this is not a high priority
