### ISSUE TITLE
My ratelimit doesn’t work. Here’s the complete configuration：(istio 1.9)

### ISSUE THREAD

**Issue by catman002** [istio/istio#31090]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

My limit doesn’t work either. Here’s the complete configuration：(istio 1.9)

**service.yam**
```
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: ratelimit-config
        data:
          config.yaml: |
            domain: echo-ratelimit
            descriptors:
              - key: PATH
                value: "/"
                rate_limit:
                  unit: minute
                  requests_per_unit: 1
              - key: PATH
                rate_limit:
                  unit: minute
                  requests_per_unit: 1
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: redis
          labels:
            app: redis
        spec:
          ports:
          - name: grpc
            port: 6379
            targetPort: 6379
            protocol: TCP
          selector:
            app: redis

        ---

        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: redis
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: redis
          template:
            metadata:
              labels:
                app: redis
            spec:
              containers:
              - image: redis:alpine
                imagePullPolicy: Always
                name: redis
                resources:
                  requests:
                    memory: "64Mi"
                    cpu: "250m"
                  limits:
                    memory: "528Mi"
                    cpu: "500m"
                ports:
                - name: redis
                  containerPort: 6379
                  protocol: TCP
              restartPolicy: Always
    ---
        apiVersion: v1
        kind: Service
        metadata:
          name: ratelimit
          labels:
            app: ratelimit
        spec:
          ports:
          - name: "8080"
            port: 8080
            targetPort: 8080
            protocol: TCP
          - name: "8081"
            port: 8081
            targetPort: 8081
            protocol: TCP
          - name: "6070"
            port: 6070
            targetPort: 6070
            protocol: TCP
          selector:
            app: ratelimit
    ---
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: ratelimit
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: ratelimit
          strategy:
            type: Recreate
          template:
            metadata:
              labels:
                app: ratelimit
            spec:
              containers:
              - image: envoyproxy/ratelimit:v1.4.0
                imagePullPolicy: Always
                name: ratelimit
                command: ["/bin/ratelimit"]
                env:
                - name: LOG_LEVEL
                  value: debug
                - name: REDIS_SOCKET_TYPE
                  value: tcp
                - name: REDIS_URL
                  value: redis.maixiaolan-test.svc.cluster.local:6379
                - name: USE_STATSD
                  value: "false"
                - name: RUNTIME_ROOT
                  value: /data
                - name: RUNTIME_SUBDIRECTORY
                  value: ratelimit
                ports:
                - containerPort: 8080
                - containerPort: 8081
                - containerPort: 6070
                volumeMounts:
                - name: config-volume
                  mountPath: /data/ratelimit/config/config.yaml
                  subPath: config.yaml
              volumes:
              - name: config-volume
                configMap:
                  name: ratelimit-config

----------------------------


**filter.yaml**

apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-ratelimit
  namespace: istio-system
spec:
  workloadSelector:
    # select by label in the same namespace
    labels:
      istio: ingressgateway
  configPatches:
    # The Envoy config you want to modify
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
              subFilter:
                name: "envoy.router"
      patch:
        operation: INSERT_BEFORE
        # Adds the Envoy Rate Limit Filter in HTTP filter chain.
        value:
          name: envoy.filters.http.ratelimit
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
            # domain can be anything! Match it to the ratelimter service config
            domain: echo-ratelimit
            failure_mode_deny: true
            rate_limit_service:
              grpc_service:
                envoy_grpc:
                  cluster_name: rate_limit_cluster
                timeout: 10s
              transport_api_version: V3
    - applyTo: CLUSTER
      match:
        cluster:
          service: ratelimit.maixiaolan-test.svc.cluster.local
      patch:
        operation: ADD
        # Adds the rate limit service cluster for rate limit service defined in step 1.
        value:
          name: rate_limit_cluster
          type: STRICT_DNS
          connect_timeout: 10s
          lb_policy: ROUND_ROBIN
          http2_protocol_options: {}
          load_assignment:
            cluster_name: rate_limit_cluster
            endpoints:
            - lb_endpoints:
              - endpoint:
                  address:
                     socket_address:
                      address: ratelimit.maixiaolan-test.svc.cluster.local
                      port_value: 8081
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-ratelimit-svc
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: VIRTUAL_HOST
      match:
        context: GATEWAY
        routeConfiguration:
          vhost:
            name: "*:58080"
            route:
              action: ANY
      patch:
        operation: MERGE
        # Applies the rate limit rules.
        value:
          rate_limits:
            - actions: # any actions in here
              - request_headers:
                  header_name: ":path"
                  descriptor_key: "PATH"
```

**Comment by bianpengyuan** [comment]
Can you give more detail what is not working? Proxy crashes? Not rate limited?

**Comment by neumanndaniel** [comment]
@bianpengyuan I am using the same configuration. I have deployed https://github.com/envoyproxy/ratelimit within my Kubernetes cluster connected to an Azure Cache for Redis. Logs indicated that the ratelimit service is up and running and also reads its configuration correctly.

```json
{"@message":"runtime changed. loading new snapshot at /data/runtime/config","@timestamp":"2021-02-26T13:22:27.4441408Z","level":"debug"}
{"@message":"runtime: processing /data/runtime/config","@timestamp":"2021-02-26T13:22:27.444292Z","level":"debug"}
{"@message":"runtime: processing /data/runtime/config/..2021_02_26_13_22_24.938606596","@timestamp":"2021-02-26T13:22:27.4443406Z","level":"debug"}
{"@message":"runtime: processing /data/runtime/config/..data","@timestamp":"2021-02-26T13:22:27.4446108Z","level":"debug"}
{"@message":"runtime: processing /data/runtime/config/config.yaml","@timestamp":"2021-02-26T13:22:27.4446367Z","level":"debug"}
{"@message":"runtime: adding key=config.yaml value=domain: ratelimit\ndescriptors:\n  - key: PATH\n    value: \"/go-webapp\"\n    rate_limit:\n      unit: minute\n      requests_per_unit: 1\n  - key: PATH\n    rate_limit:\n      requests_per_unit: 10\n      unit: minute uint=false","@timestamp":"2021-02-26T13:22:27.4454785Z","level":"debug"}
{"@message":"connecting to redis on istio-ratelimit.redis.cache.windows.net:6380 with pool size 5","@timestamp":"2021-02-26T13:22:27.4459337Z","level":"warning"}
{"@message":"Implicit pipelining enabled: false","@timestamp":"2021-02-26T13:22:27.4460439Z","level":"debug"}
{"@message":"enabling authentication to redis on istio-ratelimit.redis.cache.windows.net:6380","@timestamp":"2021-02-26T13:22:27.4462204Z","level":"warning"}
{"@message":"statsd connection error: dial tcp 127.0.0.1:9125: connect: connection refused","@timestamp":"2021-02-26T13:22:27.4514698Z","level":"warning"}
{"@message":"enabling authentication to redis on istio-ratelimit.redis.cache.windows.net:6380","@timestamp":"2021-02-26T13:22:27.860551Z","level":"warning"}
{"@message":"loading domain: ratelimit","@timestamp":"2021-02-26T13:22:27.8959719Z","level":"debug"}
{"@message":"loading descriptor: key=ratelimit.PATH_/go-webapp ratelimit={requests_per_unit=1, unit=MINUTE}","@timestamp":"2021-02-26T13:22:27.8961213Z","level":"debug"}
{"@message":"loading descriptor: key=ratelimit.PATH ratelimit={requests_per_unit=10, unit=MINUTE}","@timestamp":"2021-02-26T13:22:27.896156Z","level":"debug"}
{"@message":"Listening for debug on ':6070'","@timestamp":"2021-02-26T13:22:27.8962738Z","level":"warning"}
{"@message":"Listening for gRPC on ':8081'","@timestamp":"2021-02-26T13:22:27.8968302Z","level":"warning"}
{"@message":"waiting for runtime update","@timestamp":"2021-02-26T13:22:27.8969587Z","level":"debug"}
{"@message":"Listening for HTTP on ':8080'","@timestamp":"2021-02-26T13:22:27.9053517Z","level":"warning"}
{"@message":"enabling authentication to redis on istio-ratelimit.redis.cache.windows.net:6380","@timestamp":"2021-02-26T13:22:28.0114608Z","level":"warning"}
{"@message":"enabling authentication to redis on istio-ratelimit.redis.cache.windows.net:6380","@timestamp":"2021-02-26T13:22:28.1693758Z","level":"warning"}
{"@message":"enabling authentication to redis on istio-ratelimit.redis.cache.windows.net:6380","@timestamp":"2021-02-26T13:22:28.3235967Z","level":"warning"}
```

Using the global rate limiting example https://istio.io/latest/docs/tasks/policy-enforcement/rate-limit/#global-rate-limit returns always a HTTP 500 error indicating a `rate_limiter_error`.

```json
{"user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36 Edg/88.0.705.74","authority":"localhost","method":"GET","upstream_host":null,"downstream_remote_address":"192.168.65.3:61512","downstream_local_address":"10.1.1.49:8080","start_time":"2021-02-26T13:30:57.317Z","response_code":500,"upstream_cluster":null,"upstream_transport_failure_reason":null,"request_id":"953dfebd-2840-4be6-9654-7b52e5bb9f34","bytes_received":0,"bytes_sent":0,"protocol":"HTTP/1.1","x_forwarded_for":"192.168.65.3","upstream_local_address":null,"response_code_details":"rate_limiter_error","route_name":null,"path":"/go-webapp","upstream_service_time":null,"response_flags":"-","duration":21,"connection_termination_details":null,"requested_server_name":null}
```

Surprisingly, the Istio Ingressgateway can talk to the ratelimit service and also submits the correct request to check for a rate limiting.

```json
"@message":"got descriptor: (PATH=/go-webapp)","@timestamp":"2021-02-26T13:30:57.3226032Z","level":"debug"}
{"@message":"starting get limit lookup","@timestamp":"2021-02-26T13:30:57.3227786Z","level":"debug"}
{"@message":"looking up key: PATH_/go-webapp","@timestamp":"2021-02-26T13:30:57.3232501Z","level":"debug"}
{"@message":"found rate limit: PATH_/go-webapp","@timestamp":"2021-02-26T13:30:57.3233017Z","level":"debug"}
{"@message":"applying limit: 1 requests per MINUTE","@timestamp":"2021-02-26T13:30:57.3233774Z","level":"debug"}
{"@message":"starting cache lookup","@timestamp":"2021-02-26T13:30:57.323486Z","level":"debug"}
{"@message":"looking up cache key: ratelimit_PATH_/go-webapp_1614346200","@timestamp":"2021-02-26T13:30:57.3235499Z","level":"debug"}
{"@message":"cache key: ratelimit_PATH_/go-webapp_1614346200 current: 1","@timestamp":"2021-02-26T13:30:57.3620557Z","level":"debug"}
{"@message":"returning normal response","@timestamp":"2021-02-26T13:30:57.3621947Z","level":"debug"}
```

Interesting part is that it does not matter if the ratelimit service uses an istio-proxy to be in the mesh or without outside the mesh.

Within the mesh the istio-proxy running beside the ratelimit service logs the following message `"response_code_details":"http2.remote_reset"`

```json
{"requested_server_name":null,"method":"POST","upstream_host":"127.0.0.1:8081","path":"/envoy.service.ratelimit.v3.RateLimitService/ShouldRateLimit","response_code_details":"http2.remote_reset","bytes_sent":0,"response_code":0,"upstream_cluster":"inbound|8081||","response_flags":"-","start_time":"2021-02-26T13:35:42.566Z","downstream_local_address":"10.1.1.62:8081","x_forwarded_for":"10.1.1.49","upstream_transport_failure_reason":null,"downstream_remote_address":"10.1.1.49:0","upstream_local_address":"127.0.0.1:56788","user_agent":null,"authority":"rate_limit_cluster","upstream_service_time":null,"duration":19,"bytes_received":38,"protocol":"HTTP/2","route_name":"default","request_id":"1f3b9410-f4f2-4c36-9185-3e182ffdc93c","connection_termination_details":null}
```

**Comment by bianpengyuan** [comment]
@neumanndaniel what is the version of the Envoy rate limit service? If you are using 1.4.0 that wouldn't work since it only supports v2 transport API: https://github.com/istio/istio/issues/30900#issuecomment-780882747

**Comment by neumanndaniel** [comment]
@bianpengyuan Nope, it is the image version that was released 10 days ago.

**Comment by bianpengyuan** [comment]
> Nope, it is the image version that was released 10 days ago.

Ok thanks. We need probably more logs from ingress to understand what's wrong. Can you turn on trace level logging there? I don't see any error logs from the snippets above.

**Comment by neumanndaniel** [comment]
Thanks @bianpengyuan for pointing out to enable the trace level logging. I identified the following message:

```log
2021-02-26T21:04:00.456575Z	debug	envoy http	async http request response headers (end_stream=true):
':status', '200'
'content-type', 'application/grpc'
'grpc-status', '14'
'grpc-message', 'upstream request timeout'
```

I just switched from the Azure Cache for Redis to a local Redis running in the same namespace and voila it is working. So, it is a latency problem between my ratelimit installation and the Azure Cache for Redis.

**Comment by bianpengyuan** [comment]
@neumanndaniel Thanks! I think this can be closed now.

For the original issue, @catman002 I think it is just because you are using a stale envoy rate limit service (1.4.0), and you need to ping it to a recent commit to have V3 transport API support. I will close this. Please reopen if things still does not work after upgrading.

**Comment by neumanndaniel** [comment]
@bianpengyuan Sorry to bother you again. Short question. I have set the following timeout in the EnvoyFilter for the grpc rate limiting service:

```yaml
            rate_limit_service:
              grpc_service:
                envoy_grpc:
                  cluster_name: rate_limit_cluster
                timeout: 1s
              transport_api_version: V3
```

Regarding the trace log it seems to be ignored and defaults to 20ms. Which would explain why my config with the Azure Cache for Redis does not work currently.

With using Azure Cache for Redis the average latency for calling my simple webapp is between 25ms-32ms.

With using the local Redis on Kubernetes variant the average latency is between 10ms-16ms.

```log
2021-02-26T21:04:00.436879Z	debug	envoy router	[C0][S984368298252979988] cluster 'rate_limit_cluster' match for URL '/envoy.service.ratelimit.v3.RateLimitService/ShouldRateLimit'
2021-02-26T21:04:00.436940Z	debug	envoy router	[C0][S984368298252979988] router decoding headers:
':method', 'POST'
':path', '/envoy.service.ratelimit.v3.RateLimitService/ShouldRateLimit'
':authority', 'rate_limit_cluster'
':scheme', 'http'
'te', 'trailers'
'grpc-timeout', '20m'
'content-type', 'application/grpc'
'x-b3-traceid', '76a7d2714286fef87db0b464ae98327e'
'x-b3-spanid', 'ed93af2db812dcbb'
'x-b3-parentspanid', '7db0b464ae98327e'
'x-b3-sampled', '0'
'x-envoy-internal', 'true'
'x-forwarded-for', '10.1.1.117'
'x-envoy-expected-rq-timeout-ms', '20'
```

**Comment by bianpengyuan** [comment]
Looks like 20 is the default timeout:
https://github.com/envoyproxy/envoy/blob/1d1b708c7bf6efa02c41d9ce22cbf1e4a1aeec2c/source/extensions/filters/http/ratelimit/config.cc#L28

And it is taken from top level time out. So I think it should be something like:
```
timeout: 1s
rate_limit_service:
  grpc_service:
    envoy_grpc:
      cluster_name: rate_limit_cluster
  transport_api_version: V3
```

**Comment by neumanndaniel** [comment]
@bianpengyuan Awesome and thanks you! 🥇  It is working now with the Azure Cache for Redis. 

```log
':method', 'POST'
':path', '/envoy.service.ratelimit.v3.RateLimitService/ShouldRateLimit'
':authority', 'rate_limit_cluster'
':scheme', 'http'
'te', 'trailers'
'grpc-timeout', '1000m'
'content-type', 'application/grpc'
'x-b3-traceid', '78a2ce63e36160b0d21402f475f6f047'
'x-b3-spanid', '2d886345d821b19b'
'x-b3-parentspanid', 'd21402f475f6f047'
'x-b3-sampled', '0'
'x-envoy-internal', 'true'
'x-forwarded-for', '10.1.1.165'
'x-envoy-expected-rq-timeout-ms', '1000'
```

**Comment by catman002** [comment]
@baranov1ch 
error: Back-off restarting failed container .  details:
```
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  <invalid>          default-scheduler  Successfully assigned maixiaolan-test/ratelimit-8696b6789b-lb55h to node3
  Normal   Pulling    41s                kubelet            Pulling image "docker.io/istio/proxyv2:1.9.0"
  Normal   Pulled     34s                kubelet            Successfully pulled image "docker.io/istio/proxyv2:1.9.0" in 6.229466325s
  Normal   Started    34s                kubelet            Started container istio-init
  Normal   Created    34s                kubelet            Created container istio-init
  Normal   Pulled     28s                kubelet            Successfully pulled image "envoyproxy/ratelimit:40393342" in 4.833663671s
  Normal   Pulling    27s                kubelet            Pulling image "docker.io/istio/proxyv2:1.9.0"
  Normal   Pulled     20s                kubelet            Successfully pulled image "docker.io/istio/proxyv2:1.9.0" in 6.601715478s
  Normal   Created    20s                kubelet            Created container istio-proxy
  Normal   Started    20s                kubelet            Started container istio-proxy
  Normal   Pulling    19s (x2 over 33s)  kubelet            Pulling image "envoyproxy/ratelimit:40393342"
  Warning  Unhealthy  18s                kubelet            Readiness probe failed: Get "http://10.244.135.7:15021/healthz/ready": dial tcp 10.244.135.7:15021: connect: connection refused
  Normal   Pulled     12s                kubelet            Successfully pulled image "envoyproxy/ratelimit:40393342" in 7.600496469s
  Normal   Created    11s (x2 over 27s)  kubelet            Created container ratelimit
  Normal   Started    11s (x2 over 27s)  kubelet            Started container ratelimit
  Warning  BackOff    8s (x2 over 9s)    kubelet            Back-off restarting failed container
```

my yaml:
```
      - image: envoyproxy/ratelimit:40393342
        imagePullPolicy: Always
        name: ratelimit
        command: ["/bin/ratelimit"]
        env:
        - name: LOG_LEVEL
          value: debug
        - name: REDIS_SOCKET_TYPE
          value: tcp
        - name: REDIS_URL
          value: redis:6379
        - name: USE_STATSD
          value: "false"
        - name: RUNTIME_ROOT
          value: /data
        - name: RUNTIME_SUBDIRECTORY
          value: ratelimit
```
