### ISSUE TITLE
Incorrect "istioctl validate" message for VirtualService with exportTo "."

### ISSUE THREAD

**Issue by esnible** [istio/istio#31107]
The following VirtualService validates with `* VirtualService//details: only .,*,~, or a valid DNS 1123 label is allowed as exportTo entry` even though exportTo is one of those things.

The cause is the missing namespace.  If the namespace isn't supplied, _istioctl_ validates `""` when exportTo is `.`.  The incorrect function is validateExportTo().

Discovered while troubleshooting https://github.com/istio/istio/issues/31014

``` yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: details
  # namespace: default
spec:
  exportTo:
  - '.'
  gateways:
  - gateway-122-71
  hosts:
  - nginx-map.gw-wso2t-sy-in.earth.xcloud.lenovo.com
  http:
  - match:
    - uri:
        prefix: /
    rewrite:
      uri: /
    route:
    - destination:
        host: map-nginx.project-1925.svc.cluster.local
        port:
          number: 80
        subset: v1
      weight: 100
```
