### ISSUE TITLE
MySQL Connection Issues with mTLS and ServiceEntries

### ISSUE THREAD

**Issue by Champ-Goblem** [istio/istio#31110]
**Bug description**
I am having issues with mTLS encrypted connection between mysql clients and a mysql database after installing cilium. The client is unable to connect to the database with mTLS enabled and setup in either `PERMISSIVE` or `STRICT` mode. Setting a timeout on the connection returns the error `waiting for initial communication packet`, but removing the sidecar from the deployment or disabling mTLS solves the issue. With mTLS enabled I managed to get the connection working by adding a ServiceEntry for the database, but running multiple ServiceEntries with the same port caused all data to be routed to the first ServiceEntry that was added, which I understand is an issue with this setup. 

I am aware that there have been issues with mysql and mTLS in the past and I have tried setting up a DestinationRule paired with PeerAuthentication policy set to `STRICT` but this did not solve the problem. I have also tried setting the name of the port on the service to `mysql-<name>` or `tcp-<name>`, neither of which had any effect. In accordance to [this](https://istio.io/latest/docs/reference/commands/pilot-discovery/#envvars) document I did also try adding `PILOT_ENABLE_MYSQL_FILTER=true` as an environment variable to istiod in the hopes that when paired with the other fixes, it might solve the issue, but again no luck.

Both connections via service DNS or pod IP have no effect and the issue still persists in both cases.

Examining the underlying packets through tcpdump shows the three way handshake (SYN, SYN ACK, ACK) but the next packet originates from the client pod and closes the connection (FIN ACK).

This issue only started happening after installing cilium as a replacement for calico and previous to this the connections worked with mTLS correctly without needing any workaround. I contacted cilium and from the details and the logs I sent them they assured me that the packets should be forwarded through correctly. Without mTLS the connection is established and all other services work with mTLS without any problems.

Examples of the templates deployed are listed below and two tcp captures are provided, one from the database pod (`cap-server-proxy`) and one from the client pod (`cap-client-proxy`).

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
A mysql client should be able to connect to the database with mTLS enabled.
I would have expected some permutation of the fixes above to solve the issue, but nothing seemed to help.

**Steps to reproduce the bug**
Install istio (with the values below)
Install cilium (with the values below)
Create a mysql database pod with sidecar and mTLS enabled
Create a client pod and attempt to connect
Connection should fail if timeout is specified, otherwise it will hang

**Version**
Istio version `1.9.0` (observed on `1.8.0` and `1.8.2`)
Cilium version `1.9.4`
K8s version `1.19.7`
Node details: `cos with docker` (`Linux 5.4.49+ x86_64`)

**How was Istio installed?**
istioctl manifest generate with the values below and applied to the cluster:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
      - name: "istio-ingressgateway"
        enabled: true
        k8s:
          hpaSpec:
            minReplicas: 3
            maxReplicas: 10
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: istio
                          operator: In
                          values:
                            - ingressgateway
                    topologyKey: kubernetes.io/hostname
          service:
            externalTrafficPolicy: Local

    pilot:
      enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2
          maxReplicas: 5

  values:
    global:
      proxy:
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 64Mi

  meshConfig:
    defaultConfig:
      holdApplicationUntilProxyStarts: true
    tcpKeepalive:
      time: 300s

```

**Extra details:**
Database yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "mysql-port-test"
  labels:
    app: mysql-test-server
spec:
  selector:
    matchLabels:
      app: mysql-test-server
  template:
    metadata:
      labels:
        app: mysql-test-server
    spec:
      containers:
      - name: mysql
        image: mysql/mysql-server:latest
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: "mysql-port-test"
spec:
  selector:
    app: mysql-test-server
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    name: mysql-aaa

```

client yaml:
```
apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
spec:
  containers:
  - name: client
    image: arey/mysql-client:latest
    command:
    - /bin/sleep
    args:
    - "50000"
```

PA & DR:
```
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: mysql-mtls-peerauthn
spec:
  selector:
    matchLabels:
      app: mysql-test-server
  mtls:
    mode: STRICT
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mysql-mtls-dr
spec:
  host: "<svc-name>.<namespace>.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```

ServiceEntry:
```
kind: ServiceEntry
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: mysql
spec:
  hosts:
    - <svc-name>.<namespace>.svc.cluster.local
  location: MESH_INTERNAL
  exportTo:
    - .
  ports:
    - name: mysql
      number: 3306
      protocol: TCP
  resolution: DNS
  workloadSelector:
    labels:
      component: master
```

Cilium helm chart values:
```
cni:
  binPath: /home/kubernetes/bin
endpointRoutes:
  enabled: false
gke:
  enabled: true
hostFirewall: false
hubble:
  listenAddress: :4244
  relay:
    enabled: true
  ui:
    enabled: true
ipam:
  mode: kubernetes
nativeRoutingCIDR: 10.48.0.0/14
nodeinit:
  enabled: true
  reconfigureKubelet: true
  removeCbrBridge: true
  restartPods: true
tunnel: vxlan

```

The two files below are tcp captures when running mTLS (txt added so github can accept them).
[cap-client-proxy.txt](https://github.com/istio/istio/files/6050983/cap-client-proxy.txt)
[cap-server-proxy.txt](https://github.com/istio/istio/files/6050985/cap-server-proxy.txt)

**Comment by howardjohn** [comment]
can you add config dump + access logs from the proxies? (https://github.com/istio/istio/wiki/Troubleshooting-Istio)

 Also why do you have a serviceEntry and Service for the same hostname? that may lead to conflicts.

Can you rename the port from `mysql` -> `tcp`?

**Comment by Champ-Goblem** [comment]
Hi howardjohn, thank you for getting back to me.

Please find the dump attached. 
To answer your other questions, referring back to my original post, the only way we could get connections to work were via ServiceEntries and I can confirm that setting either tcp or mysql for the port name did not have any effect.

If you have any more suggestions please let me know.

[dumps.tar.gz](https://github.com/istio/istio/files/6054361/dumps.tar.gz)

**Comment by howardjohn** [comment]
These logs are failed requests? or successful ones? Since they look good:
```
[2021-02-26T20:30:38.150Z] "- - -" 0 - - - "-" 0 70 23 - "-" "-" "-" "-" "10.48.1.19:3306" outbound|3306||mysql-port-test.ns-namespace-default-project.svc.cluster.local 10.48.1.227:34122 10.48.1.19:3306 10.48.1.227:34120 - -
[2021-02-26T20:30:41.539Z] "- - -" 0 - - - "-" 0 70 2 - "-" "-" "-" "-" "10.48.1.19:3306" outbound|3306||mysql-port-test.ns-namespace-default-project.svc.cluster.local 10.48.1.227:34248 10.48.1.19:3306 10.48.1.227:34246 - -
[2021-02-26T20:30:42.140Z] "- - -" 0 - - - "-" 0 70 2 - "-" "-" "-" "-" "10.48.1.19:3306" outbound|3306||mysql-port-test.ns-namespace-default-project.svc.cluster.local 10.48.1.227:34272 10.48.1.19:3306 10.48.1.227:34270 - -
[2021-02-26T20:30:42.585Z] "- - -" 0 - - - "-" 0 70 2 - "-" "-" "-" "-" "10.48.1.19:3306" outbound|3306||mysql-port-test.ns-namespace-default-project.svc.cluster.local 10.48.1.227:34292 10.48.1.19:3306 10.48.1.227:34290 - -


----

[2021-02-26T20:30:38.151Z] "- - -" 0 - - - "-" 1432 1628 40 - "-" "-" "-" "-" "127.0.0.1:3306" inbound|3306|| 127.0.0.1:55966 10.48.1.19:3306 10.48.1.227:34122 outbound_.3306_._.mysql-port-test.ns-namespace-default-project.svc.cluster.local -
[2021-02-26T20:30:41.539Z] "- - -" 0 - - - "-" 1432 1628 2 - "-" "-" "-" "-" "127.0.0.1:3306" inbound|3306|| 127.0.0.1:56092 10.48.1.19:3306 10.48.1.227:34248 outbound_.3306_._.mysql-port-test.ns-namespace-default-project.svc.cluster.local -
[2021-02-26T20:30:42.140Z] "- - -" 0 - - - "-" 1432 1628 2 - "-" "-" "-" "-" "127.0.0.1:3306" inbound|3306|| 127.0.0.1:56116 10.48.1.19:3306 10.48.1.227:34272 outbound_.3306_._.mysql-port-test.ns-namespace-default-project.svc.cluster.local -
[2021-02-26T20:30:42.585Z] "- - -" 0 - - - "-" 1432 1628 2 - "-" "-" "-" "-" "127.0.0.1:3306" inbound|3306|| 127.0.0.1:56136 10.48.1.19:3306 10.48.1.227:34292 outbound_.3306_._.mysql-port-test.ns-namespace-default-project.svc.cluster.local
```

One thing to try, explicitly enable and/or disable TLS. try both:
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: tls
  namespace: ns-namespace-default-project
spec:
  host: "mysql-port-test.ns-namespace-default-project.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: ns-namespace-default-project
spec:
  mtls:
    mode: STRICT
```


```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: tls
  namespace: ns-namespace-default-project
spec:
  host: "mysql-port-test.ns-namespace-default-project.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: ns-namespace-default-project
spec:
  mtls:
    mode: DISABLE
```

**Comment by Champ-Goblem** [comment]
I can confirm that the logs you mentioned were successful requests when a service entry was applied.

As for the other two suggestions, the connections worked when TLS was disabled and failed once TLS was enabled. I tried both of the templates above with the port name set as `mysql` and `tcp`, and for both port names disabling TLS worked and enabling it caused connections to fail again.

I have attached the logs from the sidecar, each file is labelled according to the test performed.

[istio-proxy-logs.tar.gz](https://github.com/istio/istio/files/6067706/istio-proxy-logs.tar.gz)

**Comment by howardjohn** [comment]
https://istio.io/latest/docs/ops/deployment/requirements/#server-first-protocols

The logs show `mTLS PERMISSIVE mode is used, connection can be either plaintext or TLS, and client cert can be omitted.`. So you didn't succesfully enable mTLS. I think I had the wrong namespace in my example above, looks like it should have been `ns-cameron-default-project`? Wherever mysql is, basically.

**Comment by Champ-Goblem** [comment]
Ill try it again, I was running the tests in a different namespace but I did update the two policies you sent to respect that change:
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: tls
spec:
  host: "mysql-port-test.ns-cameron-default-project.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
spec:
  mtls:
    mode: STRICT
```
and
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: tls
spec:
  host: "mysql-port-test.ns-cameron-default-project.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
spec:
  mtls:
    mode: DISABLE
```
I did try the test again with the tcp port name with TLS as enforcing, but still no luck

[istio-logs-with-tcp-portname-tls-enabled.txt](https://github.com/istio/istio/files/6070239/istio-logs-with-tcp-portname-tls-enabled.txt)
