### ISSUE TITLE
Too permissive AuthorizationPolicy when add Hosts as to/operation

### ISSUE THREAD

**Issue by drano** [istio/istio#31155]
With Istio 1.9.0, I add hosts in to/operation in AuthorizationPolicy. But, this policy becomes too permissive.

```
apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: "authentication-jwt"
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
  - issuer: "testing@secure.istio.io"
    jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.9/security/tools/jwt/samples/jwks.json"

apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: require-jwt
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: ALLOW
  rules:
  - from:
    - source:
       requestPrincipals: ["testing@secure.istio.io/*"]
  - to:
    - operation:
       hosts: ["app.ing.local.domain"]
```

Then, I execute curl -X GET "http://app.ing.local.domain/xxx/api/myApi" -H  "accept: text/plain"

Without to/operation/hosts: RBAC: access denied
With  to/operation/hosts: Success

**Comment by howardjohn** [comment]
```
  rules:
  - from:
    - source:
       requestPrincipals: ["testing@secure.istio.io/*"]
    to:
    - operation:
       hosts: ["app.ing.local.domain"]
```

Did you mean ^?
