### ISSUE TITLE
EnvoyFilter ListenerMatch FilterChainMatch not support name match

### ISSUE THREAD

**Issue by zhongfox** [istio/istio#31166]
**Bug description**

according to https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-ListenerMatch-FilterChainMatch we should support filterchain.name match, but currently it seems not.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
......
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        ......
        filterChain:
          name: "virtualOutbound-catchall-tcp"      # this is not working
          filter:
            name: "envoy.filters.network.tcp_proxy"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy"
          cluster: "outbound|80||istio-egressgateway.istio-system.svc.cluster.local"
```

![image](https://user-images.githubusercontent.com/463772/109595331-42e70000-7b4f-11eb-8bd1-f6b380c45a14.png)

[X] Networking

**How was Istio installed?**
istioctl install

**Environment where the bug was observed (cloud vendor, OS, etc)**
istio 1.8.2
