### ISSUE TITLE
Istio fail contructing route from ingress. unsupported protocol

### ISSUE THREAD

**Issue by ese** [istio/istio#3117]
**Summary**
version: Istio 0.5.0
Istio is failing to construct an envoy route due an unsupported protocol. I have an Ingress resource refering to serviceName: `app-service`  and servicePort: `80`. I expect to get this route in envoy since an Ingress resource is always a rule for an HTTP service.
Envoy is failing with this error logged by pilot:

```
2018-02-02T20:35:44.372812Z	warn	Error constructing Envoy route from ingress rule: unsupported protocol "TCP" for "app-service.default.svc.cluster.local"
```

To get this working fine I need to name the port in the service with name `http` like this:
```
# extract from app-service.yaml
[...]
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
[...]
```
Usually you have an arbitrary name with more semantic meaning like `api`, `metrics` or whatever since name is an user field to make easy references

Is this constraint really necessary? All the ingress controllers work fine with arbitrary strings naming ports in services
