### ISSUE TITLE
HTTP body missing from gRPC ExternalAuthorization provider CheckRequest

### ISSUE THREAD

**Issue by andrewweston** [istio/istio#31182]
**Bug description**

The EnvoyExternalAuthorizationGrpcProvider does not include the original HTTP body when forwarding a CheckRequest to the AuthorizationServer. I am using the server to validate requests from an external webhook by comparing request signature with hmac of the request body.

I am hoping to use this new feature to replace the Lua script we are currently using. 

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
I should be able to access the original HTTP request body (as a string or bytes)

**Steps to reproduce the bug**
 - Implement a Go-based gRPC ExternalAuthorization server per [Yangmin Zhu's blog](https://istio.io/latest/blog/2021/better-external-authz/)
 - Inspect Http.Body and Http.RawBody attributes
 
```
func (a Authz) Check(ctx context.Context, req *pb.CheckRequest) (*pb.CheckResponse, error) {

	http := req.Attributes.Request.Http
	klog.Info(http.Body)
	klog.Info(len(http.RawBody))

```

**Version**
Istio 1.9.1, Kubernetes: v1.20.2, Helm: v3.5.2+g167aac7

**How was Istio installed?**
Helm

**Environment where the bug was observed (cloud vendor, OS, etc)**
Azure Kubernetes Service

**Comment by yangminzhu** [comment]
Thanks for trying out the ext-authz feature!

Currently this is an intended limitation that EnvoyExternalAuthorizationGrpcProvider/EnvoyExternalAuthorizationHttpProvider does not expose the `with_request_body`, this was discussed in the original design and not added mainly for simplifying the API interface.

We're collecting feedback for the next update of the API, probably this should be added if it is needed by people.

Meanwhile, if you want to include the body right now, the workaround is to apply the following EnvoyFilter, it works with the extension provider and inside the EnvoyFilter you only need to configure the `with_request_body`, the filter itself and other settings will be handled by the extension provider for you:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: enable-ext-authz-request-with-body
spec:
  workloadSelector:
    labels:
      <KEY>: <VALUE>
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: ANY
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.ext_authz"
    patch:
      operation: MERGE
      value:
        name: envoy.filters.http.ext_authz
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
          with_request_body:
            # Pick the proper value for your use case. see https://github.com/envoyproxy/envoy/blob/main/api/envoy/config/filter/http/ext_authz/v2/ext_authz.proto#L120
            max_request_bytes: 8192
```

**Comment by andrewweston** [comment]
Perfect! That worked like a charm. Thank you.

**Comment by leefernandes** [comment]
Is it possible to match on rules with the EnvoyFilter as is possible with Authorization Policies?

```yaml
  rules:
    - to:
        - operation:
            notPaths: ["/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo"]
```

**Comment by leefernandes** [comment]
How do you put AuthorizationPolicy in front of the EnvoyFilter in order to use path rules?

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "api.name" . }}-ext-authz
spec:
  selector:
    matchLabels:
      app: {{ include "api.name" . }}
  action: CUSTOM
  provider:
    name: envoy.ext_authz
  rules:
    - to:
        - operation:
            notPaths: ["/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo"]
```

**Comment by leefernandes** [comment]
For anyone else finding this issue while trying to support request body parsing in their Check method, it's supported by AuthorizationPolicy now with the [includeRequestBodyInCheck](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-ExtensionProvider-EnvoyExternalAuthorizationGrpcProvider) option.

```yaml
meshConfig:
  extensionProviders:
    - name: "ext-authz-grpc"
      envoyExtAuthzGrpc:
        service: "ext-authz"
        port: "55555"
        includeRequestBodyInCheck:
          maxRequestBytes: 4096
          packAsBytes: true
          allowPartialMessage: true
```
