### ISSUE TITLE
Lightstep tracing with caCertificates defined report missing spans

### ISSUE THREAD

**Issue by AlexDHoffer** [istio/istio#31190]
**Bug description**

On Istio 1.8.2, following this doc: https://istio.io/latest/docs/tasks/observability/distributed-tracing/lightstep/#deploy-istio-with-public-or-developer-mode-satellites

... leads to broken parent spans that worked correctly prior to the upgrade:

![image](https://user-images.githubusercontent.com/19369483/109719036-ec80be00-7b5c-11eb-8ade-f1f053c609bc.png)

Our config before the upgrade was:

````
  values:
    global:
      enableTracing: true
      tracer:
        lightstep:
          address: [internal IP to satellite]
          secure: true
          cacertPath: /etc/lightstep/cacert.pem
          accessToken: [redacted]
      proxy:
        tracer: lightstep
````

Our config after the upgrade is:

````
  meshConfig:
    defaultConfig:
      tracing:
        tlsSettings:
          mode: "SIMPLE"
          caCertificates: "/etc/lightstep/cacert.pem"

  values:
    global:
      tracer:
        lightstep:
          address: [internal IP of satellite]
          accessToken: [redacted]
      proxy:
        tracer: lightstep
````

The CA cert is correctly mounted to the application pods in the mesh:

````
    Mounts:
      /etc/lightstep/ from lightstep-certs (ro)
````

And exec'ing into the istio-proxy container shows that /etc/lightstep indeed contains the correct file. Nothing shows up in the istio-proxy logs for the app pods.

However, this shows up in the ingressgateway pods:

````
2021-03-02T21:47:05.959141Z	error	cache	resource:file-root:/etc/lightstep/cacert.pem failed to generate secret for proxy from file: open /etc/lightstep/cacert.pem: no such file or directory
2021-03-02T21:47:05.959194Z	error	sds	resource:file-root:/etc/lightstep/cacert.pem Close connection. Failed to get secret for proxy "router~10.1.10.164~istio-ingressgateway-5b7475bbb6-547xf.istio-system~istio-system.svc.cluster.local" from secret cache: open /etc/lightstep/cacert.pem: no such file or directory
2021-03-02T21:47:05.959299Z	info	sds	resource:file-root:/etc/lightstep/cacert.pem connection is terminated: rpc error: code = Canceled desc = context canceled
2021-03-02T21:47:05.959527Z	warning	envoy config	StreamSecrets gRPC config stream closed: 2, open /etc/lightstep/cacert.pem: no such file or directory
````

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

All spans that correctly generated before the upgrade persist after the upgrade.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

1.8.2

**How was Istio installed?**

Profile generated from provided yaml

**Environment where the bug was observed (cloud vendor, OS, etc)**

AKS

**Comment by bianpengyuan** [comment]
Can you get a dump of tracer config?

**Comment by AlexDHoffer** [comment]
> Can you get a dump of tracer config?

where can i get that?

**Comment by bianpengyuan** [comment]
It is part of proxy config dump: https://github.com/istio/istio/wiki/Troubleshooting-Istio#sidecargateway-problems

**Comment by AlexDHoffer** [comment]
@bianpengyuan

Here is all the tracer configs from the proxy config dump that I found.

Let me know if I missed important context, I didn't want to post the whole raw thing without amending since there's plenty of personal information in there.

From the ingress:
[ingress_config_parsed.txt](https://github.com/istio/istio/files/6072316/ingress_config_parsed.txt)

From an application sidecar:
[stats_config_parsed.txt](https://github.com/istio/istio/files/6072329/stats_config_parsed.txt)

**Comment by bianpengyuan** [comment]
Can you get part of your config dump that correspond to this tracer cluster configuration: https://github.com/istio/istio/blob/670075ebe7cc2e7ec15d39edca343d05c26aa6b4/tools/packaging/common/envoy_bootstrap.json#L353-L376 and

**Comment by AlexDHoffer** [comment]
@bianpengyuan Yep...

One from the ingress:

[ingress_config_parsed.txt](https://github.com/istio/istio/files/6072543/ingress_config_parsed.txt)

One from the app pod:

[stats_config_parsed.txt](https://github.com/istio/istio/files/6072545/stats_config_parsed.txt)

**Comment by bianpengyuan** [comment]
Ok thanks! I understand the tracer tls setting better now.. Does the istio-certs volume mounted at your ingress? By broking parent span, do you mean spans are disconnected due to missing spans? If so, are the missing spans supposed to be reported from ingress?

**Comment by AlexDHoffer** [comment]
@bianpengyuan 

Here are our mounted volumes at the ingress:

````
        - mountPath: /etc/istio/proxy
          name: istio-envoy
        - mountPath: /etc/istio/config
          name: config-volume
        - mountPath: /var/run/secrets/istio
          name: istiod-ca-cert
        - mountPath: /var/run/secrets/tokens
          name: istio-token
          readOnly: true
        - mountPath: /var/run/ingress_gateway
          name: gatewaysdsudspath
        - mountPath: /var/lib/istio/data
          name: istio-data
        - mountPath: /etc/istio/pod
          name: podinfo
        - mountPath: /etc/istio/ingressgateway-certs
          name: ingressgateway-certs
          readOnly: true
        - mountPath: /etc/istio/ingressgateway-ca-certs
          name: ingressgateway-ca-certs
          readOnly: true
````

We do not expect to mount Lightstep certs at the ingress. We are unsure of why our ingress gateway is suddenly expecting the Lightstep certs to be mounted there. 

What I mean by broken parent span is that our sidecar proxy has missing spans but our application is still yielding spans. 

Here is the upgraded Istio's broken span:

![image](https://user-images.githubusercontent.com/19369483/109734397-cf0c1e00-7b75-11eb-81f9-0f8d6e676fab.png)

For the same call, this is what our old Istio's span looks like:

![image](https://user-images.githubusercontent.com/19369483/109734457-de8b6700-7b75-11eb-85f4-226c5abda975.png)

Notice how for the top picture, there is a red rectangle around the box. That's because the span is missing for the proxy server. This is not the case for the below picture, where the span for the proxy server is there.

**Comment by AlexDHoffer** [comment]
@bianpengyuan 

> Do you mean spans are disconnected due to missing spans? If so, are the missing spans supposed to be reported from ingress?

I mean network mesh spans aren't there. They shouldn't be reported from ingress because our working Istio/Lightstep config on another cluster does not have mounted Lightstep certs.

**Comment by bianpengyuan** [comment]
Can you enable envoy tracing component debug log at sidecar and see if you can capture anything suspicious? It would be great if you can use `sidecar.istio.io/componentLogLevel` annotation (`sidecar.istio.io/componentLogLevel: "tracing:debug"`), because there might be some log that we want to capture at bootstrap.

As for gateway, I think it is expected that trace span is also reported there and cert needs to be mounted.. so current behavior seems to me is working as intended. Probably there used to be a bug but got fixed in recent releases.

**Comment by AlexDHoffer** [comment]
@bianpengyuan 

> As for gateway, I think it is expected that trace span is also reported there and cert needs to be mounted.. so current behavior seems to me is working as intended. Probably there used to be a bug but got fixed in recent releases.

If it were expected to be mounted at the ingress, then why wouldn't this:

````
  meshConfig:
    defaultConfig:
      tracing:
        tlsSettings:
          mode: "SIMPLE"
          caCertificates: "/etc/lightstep/cacert.pem"
````

... also automatically mount the cert at the ingressgateway deployment? This config mounts the certs at the sidecars, but there's no way I can see in the configs to mount it automatically at the ingressgateway.

Thanks for the logging suggestion, I will do so today and report back.

**Comment by bianpengyuan** [comment]
Yeah unfortunately, the tracing config controls gateway's bootstrap config, but it does not control the gateway deployment spec yet, which will be resolved in the future. It is being worked on to unify sidecar and gateway spec generation logic (cc @howardjohn).

Meanwhile to work around this, you could add the following volumes explicitly:
```
    - name: istio-ingressgateway
      enabled: true
      k8s:
        overlays:
        - kind: Deployment
          name: istio-ingressgateway
          patches:
          - path: spec.template.spec.containers[0].volumeMounts[-1]
            value: |
              name: lightstep-certs
              mountPath: /etc/lightstep
              readOnly: true
          - path: spec.template.spec.volumes[-1]
            value: |
              name: lightstep-certs
              secret:
                secretName: lightstep.cacert
                optional: true
```

I can add this to the lightstep doc, but I don't have a lightstep env to verify the change. It would be great if you could try this first and see if this works. Meanwhile, if you, as a lightstep customer, could ask for some attention from lightstep folks to maintain and add test to Istio lightstep integration, that would be great. TBH, this part is very poorly maintained.
