### ISSUE TITLE
mTLS connection issues after upgrade from 1.8.3 to 1.9.0/1.9.1

### ISSUE THREAD

**Issue by LukaszRacon** [istio/istio#31198]
mTLS stopped working for pod to service communication after upgrade from 1.8.3 to 1.9.0/1.9.1.

I have `nwtools` and `httpbin` pods in the same `default` namespace.
Doing `curl http://httpbin/headers` from `nwtools` fails with `command terminated with exit code 56`.

Notes:
Same setup works in 1.8.3.
When PeerAuthentication is set to PERMISSIVE `nwtools` can curl `httpbin`.
Traffic from Ingress GW to `httpbin` works fine (with mTLS).

Data:
```
# kk exec nwtool-76fdf7c588-bbb2m -c nwtool -- curl -s http://httpbin/headers
command terminated with exit code 56
```

httpbin logs (nwtool curl):
```
[2021-03-03T09:02:48.666Z] "- - -" 0 NR filter_chain_not_found - "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.2.71.13:80 10.2.78.40:41080 - -
```
httpbin logs (curl public endpoint/ALB+ingress gw):
```
[2021-03-03T09:02:46.140Z] "GET /headers HTTP/1.1" 200 - via_upstream - "-" 0 730 4 3 "205.xxx.xxx.xxx,10.2.88.213" "curl/7.65.3" "1de1db4e-b525-4d34-ac13-f21c0235b2dc" "httpbin.private-domain.com" "127.0.0.1:80" inbound|80|| 127.0.0.1:60882 10.2.71.13:80 10.2.88.213:0 outbound_.80_._.httpbin.default.svc.cluster.local default
```

push-status:
```
{
    "pilot_eds_no_instances": {
        "outbound|80|v1|httpbin.default.svc.cluster.local": {},
        "outbound|80||httpbin.default.svc.cluster.local": {}
    }
}
```

PeerAuthentication is strict
```
apiVersion: security.istio.io/v1beta1   
kind: PeerAuthentication                
metadata:                               
  name: default                        
  namespace: istio-system               
spec:                                   
  mtls:                              
    mode: STRIC
```
DestinationRule is set to ISTIO_MUTUAL
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: httpbin
  namespace: default
spec:
  host: httpbin.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```

IstioOperator:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
annotations:
  meta.helm.sh/release-name: istio-operator
  meta.helm.sh/release-namespace: istio-operator
finalizers:
- istio-finalizer.install.istio.io
labels:
  app.kubernetes.io/instance: istio-operator
  app.kubernetes.io/managed-by: Helm
  app.kubernetes.io/name: istio-operator
  app.kubernetes.io/version: 1.9.1
  helm.sh/chart: istio-operator-2.1.2
name: istio-operator
namespace: istio-system
spec:
components:
  cni:
    enabled: true
    namespace: kube-system
  ingressGateways:
  - enabled: true
    k8s:
      overlays:
      - kind: Service
        name: istio-ingressgateway
        patches:
        - path: spec.ports.[name:status-port].nodePort
          value: 32520
    label:
      istio: ingressgateway
    name: istio-ingressgateway
  - enabled: true
    k8s:
      overlays:
      - kind: Service
        name: istio-ingressgateway-private
        patches:
        - path: spec.ports.[name:status-port].nodePort
          value: 32521
    label:
      istio: ingressgateway-private
    name: istio-ingressgateway-private
tag: 1.9.1
values:
  gateways:
    istio-egressgateway:
      enabled: true
      type: NodeIp
    istio-ingressgateway:
      type: NodePort
  global:
    proxy:
      includeIPRanges: 10.2.64.0/18
  meshConfig:
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
```

**Data**
https://drive.google.com/drive/folders/1GiZ-LfGZCOfPIuCLMVeiUntm2e-g31d6

config_dump:
httpbin-microservice.config_dump.json
nwtool.config_dump.json

clusters:
httpbin-microservice.clusters
nwtool.clusters
nwtool.clusters.fqdn

stats:
httpbin-microservice.stats
nwtool.stats

logs:
httpbin-microservice.proxy.log
nwtool.proxy.log

listeners/routes/filters:
httpbin-microservice.listeners
nwtool.routes
envoyfilter.yaml

**Version** 
```
# ki version --remote
kclient version: 1.9.0
control plane version: 1.9.1
data plane version: 1.9.1 (6 proxies)

# kk version --short
Client Version: v1.19.6-eks-49a6c0
Server Version: v1.19.6-eks-49a6c0

# kh version --short
v3.5.2+g167aac7
```

**How was Istio installed?**
Helm chart/istio-operator.

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS EKS 1.19, CNI/Calico
