### ISSUE TITLE
Lua debug logs not printing

### ISSUE THREAD

**Issue by logand22** [istio/istio#31192]
**Bug description**
After upgrading to v1.9.1, Lua logs don't output in istio-proxy stdout.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[X] Upgrade

**Expected behavior**
Expected Lua to output to istio-proxy stdout. 

**Steps to reproduce the bug**
Configure EnvoyFilter as such:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: x-token-enrichment
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      xtoken-enrich: enabled
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: ANY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.lua
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
            inlineCode: |
              function envoy_on_request(handle)
                handle:logCritical("REQUEST HANDLED")
              end
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

istio version
```bash
client version: 1.9.1
control plane version: 1.9.1
data plane version: 1.9.1 (2 proxies)
```

```bash
Server Version: v1.18.14
```

**How was Istio installed?**
istioctl install -f istio.yaml

istio.yaml
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        service:
          type: NodePort
          ports:
          - name: status-port
            protocol: TCP
            port: 15021
            targetPort: 15021
            nodePort: 32021
          - name: http2
            protocol: TCP
            port: 80
            targetPort: 8080
            nodePort: 32080
          - name: https
            protocol: TCP
            port: 443
            targetPort: 8443
            nodePort: 32443
          - name: tls
            protocol: TCP
            port: 15443
            targetPort: 15443
            nodePort: 32000
  meshConfig:
    accessLogFile: /dev/stdout
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
      gatewayTopology:
        numTrustedProxies: 1
```

**Environment where the bug was observed (cloud vendor, OS, etc)**
Bug occurred in Azure AKS cluster. I have used same envoy filter on a bare metal cluster w/ version 1.18.0 and 1.17.4.
