### ISSUE TITLE
ingressgateway stuck cpu and envoy dead

### ISSUE THREAD

**Issue by lurenjia528** [istio/istio#31229]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

[ ] Docs
[ ] Installation
[X] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**
root@master17:~# kubectl version 
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:52:24Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/arm64"}
root@master17:~# istioctl version
client version: 1.7.3
control plane version: 9686754643d0939c1f4dd0ee20443c51183f3589
data plane version: 1.7.3 (9 proxies)

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

os 
```bash
root@master17:~# uname -a 
Linux master17 4.4.131-20200103.kylin.server-generic #kylin SMP Mon Jan 6 10:15:56 CST 2020 aarch64 aarch64 aarch64 GNU/Linux
root@master17:~# 
```
```yaml
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
  name: istio-ingressgateway
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
  template:
    metadata:
      annotations:
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "15090"
        prometheus.io/scrape: "true"
        sidecar.istio.io/inject: "false"
      labels:
        app: istio-ingressgateway
        istio: ingressgateway
        service.istio.io/canonical-name: istio-ingressgateway
        service.istio.io/canonical-revision: latest
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 5
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 5
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        node-role.kubernetes.io/master: 'true'
      containers:
        - args:
            - proxy
            - router
            - --domain
            - $(POD_NAMESPACE).svc.cluster.local
            - --proxyLogLevel=warning
            - --proxyComponentLogLevel=misc:error
            - --log_output_level=default:info
            - --serviceCluster
            - istio-ingressgateway
            - --trust-domain=cluster.local
            - --disableInternalTelemetry
#            - --concurrency=16
          env:
            - name: JWT_POLICY
              value: first-party-jwt
            - name: PILOT_DISABLE_XDS_MARSHALING_TO_ANY
              value: "true"
            - name: PILOT_CERT_PROVIDER
              value: istiod
            - name: CA_ADDR
              value: istiod.istio-system.svc:15012
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: INSTANCE_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: CANONICAL_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['service.istio.io/canonical-name']
            - name: CANONICAL_REVISION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['service.istio.io/canonical-revision']
            - name: ISTIO_META_WORKLOAD_NAME
              value: istio-ingressgateway
            - name: ISTIO_META_OWNER
              value: kubernetes://apis/apps/v1/namespaces/istio-system/deployments/istio-ingressgateway
            - name: ISTIO_META_MESH_ID
              value: cluster.local
            - name: ISTIO_META_ROUTER_MODE
              value: sni-dnat
            - name: ISTIO_META_CLUSTER_ID
              value: Kubernetes
            - name: ISTIO_META_HTTP10
              value: "1"
            - name: ISTIO_META_HTTP11
              value: "1"
            - name: ISTIO_METAJSON_ANNOTATIONS
              value: |
                {"sidecar.istio.io/extraStatTags":"request_url_path,request_method"}
          image: "kylincloud2.hub/istio-system/proxyv2:v1.7.3"
          name: istio-proxy
          ports:
            - containerPort: 80
              hostPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              hostPort: 443
              protocol: TCP
            - containerPort: 15021
            #        - containerPort: 8080
            #        - containerPort: 8443
            - containerPort: 15443
            - containerPort: 15090
              name: http-envoy-prom
              protocol: TCP
          livenessProbe:
            failureThreshold: 30
            httpGet:
              path: /healthz/ready
              port: 15021
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 30
            httpGet:
              path: /healthz/ready
              port: 15021
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 5000m
              memory: 4096Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            #          allowPrivilegeEscalation: false
            #          capabilities:
            #            drop:
            #            - ALL
            privileged: true
          #          readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /etc/istio/proxy
              name: istio-envoy
            - mountPath: /etc/istio/config
              name: config-volume
            - mountPath: /var/run/secrets/istio
              name: istiod-ca-cert
            - mountPath: /var/run/ingress_gateway
              name: gatewaysdsudspath
            - mountPath: /etc/istio/pod
              name: podinfo
            - mountPath: /etc/istio/ingressgateway-certs
              name: ingressgateway-certs
              readOnly: true
            - mountPath: /etc/istio/ingressgateway-ca-certs
              name: ingressgateway-ca-certs
              readOnly: true
      #      securityContext:
      #        fsGroup: 1337
      #        runAsGroup: 1337
      #        runAsNonRoot: true
      #        runAsUser: 1337
      serviceAccountName: istio-ingressgateway-service-account
      volumes:
        - configMap:
            name: istio-ca-root-cert
          name: istiod-ca-cert
        - downwardAPI:
            items:
              - fieldRef:
                  fieldPath: metadata.labels
                path: labels
              - fieldRef:
                  fieldPath: metadata.annotations
                path: annotations
          name: podinfo
        - emptyDir: {}
          name: istio-envoy
        - emptyDir: {}
          name: gatewaysdsudspath
        - configMap:
            name: istio
            optional: true
          name: config-volume
        - name: ingressgateway-certs
          secret:
            optional: true
            secretName: istio-ingressgateway-certs
        - name: ingressgateway-ca-certs
          secret:
            optional: true
            secretName: istio-ingressgateway-ca-certs
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
  name: istio-ingressgateway
  namespace: istio-system
spec:
  ports:
    - name: status-port
      port: 15021
      targetPort: 15021
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
    - name: tls
      port: 15443
      targetPort: 15443
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  type: LoadBalancer

```

jmeter load test a pod, thread:200 , not  in 1h,
pod(java) error,and then envoy dead
```bash
root@master17:/# 
root@master17:/# 
root@master17:/# curl http://127.0.0.1:15000/
curl: (56) Recv failure: Connection reset by peer
root@master17:/# netstat -nltp | grep 15000
tcp      129      0 127.0.0.1:15000         0.0.0.0:*               LISTEN      22/envoy            
root@master17:/# ps -ef 
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 Mar02 ?        00:00:26 /usr/local/bin/pilot-agent proxy router --domain istio-system.svc.cluster.local --proxyLogLevel=warning --proxyComponentLogLevel=misc:error --log_output_level=defa
root        22     1 99 Mar02 ?        18:28:30 /usr/local/bin/envoy -c etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster istio-ingressgateway --se
root       212     0  0 05:52 pts/0    00:00:00 bash
root       225   212  0 05:53 pts/0    00:00:00 ps -ef
root@master17:/# 
```
in istio-ingressgateway container,envoy use 100% cpu
```bash
top - 05:53:31 up 19 days,  3:27,  0 users,  load average: 1.23, 1.57, 2.81
Tasks:   4 total,   2 running,   2 sleeping,   0 stopped,   0 zombie
%Cpu(s):  1.3 us,  0.3 sy,  0.0 ni, 98.3 id,  0.0 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem : 26587340+total, 22400249+free,  9235264 used, 32635648 buff/cache
KiB Swap:  8000448 total,  7998976 free,     1472 used. 25036185+avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                        
   22 root      20   0 2720768 1.533g  34880 R 100.0  0.6   1108:40 envoy                                                                                                                                          
    1 root      20   0  781376  74304  45952 S   0.0  0.0   0:26.19 pilot-agent                                                                                                                                    
  212 root      20   0    4608   3968   2944 S   0.0  0.0   0:00.01 bash                                                                                                                                           
  226 root      20   0    6784   4480   2624 R   0.0  0.0   0:00.00 top                                                                                                                                            

```

pilot healthcheck ok
```bash
root@master17:/# curl -v 127.0.0.1:15021/healthz/ready
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 15021 (#0)
> GET /healthz/ready HTTP/1.1
> Host: 127.0.0.1:15021
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< date: Wed, 03 Mar 2021 05:54:49 GMT
< content-length: 0
< x-envoy-upstream-service-time: 0
< server: envoy
< 
* Connection #0 to host 127.0.0.1 left intact
root@master17:/# 
```

```bash
root@master17:/var/log# kubectl top po 
NAME                         CPU(cores)   MEMORY(bytes)   
istio-ingressgateway-jlrmj   1008m        1566Mi          
istiod-845b6fd597-268fn      9m           189Mi           
root@master17:/var/log# 
```

machine cpu stuck :
```bash
top 
%Cpu57 :100.0 us,  0.0 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st


```

```bash
root@master17:/# ps aux   
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0 781376 74496 ?        Ssl  Mar02   0:26 /usr/local/bin/pilot-agent proxy router --domain istio-system.svc.cluster.local --proxyLogLevel=warning --proxyCom
root        22  103  0.6 2733056 1619392 ?     Rl   Mar02 1115:36 /usr/local/bin/envoy -c etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --parent-shutdown-tim
root       242  0.0  0.0   4608  3328 pts/0    Ss   06:00   0:00 bash
root       253  0.0  0.0   6272  3968 pts/0    R+   06:00   0:00 ps aux
root@master17:/# 
```

only restart istio-ingressgateway pod can resume
