### ISSUE TITLE
virtualservice match rule value from db ?

### ISSUE THREAD

**Issue by hmthoo** [istio/istio#31233]
now, I use cookie regex userid to manage user's version.
```
    - match:
        - headers:
            cookie:
              regex: '.*uid=([0-9]{1,3});.*'
      route:
        - destination:
            host: login.canary.svc.cluster.local
            subset: v2
```
But this method is difficult to manage when there are more users.
If i set user's version in db. How do i use userid from db get user's version in virtualservice?

For example:
db
```
userid      version
11111           v2
```
virtualservice
```
    - match:
        - headers:
               userid:
                  xxxx            # use userid to get user's version from db.  My guess.
      route:
        - destination:
            host: login.canary.svc.cluster.local
            subset: v2
```

Or there are other better ways? Please tell me, thanks!
