### ISSUE TITLE
Allow setting default HTTPRetry policy

### ISSUE THREAD

**Issue by andrewjjenkins** [istio/istio#31242]
**Describe the feature request**

I would like to define global policy for some properties of VirtualService; in my particular case the `retries` (HTTPRetry parameter.  I would like for the policy for any host to "inherit" from these global policies (and be able to override in a particular VirtualService).

Today I have to configure multiple VirtualServices.  For example, to disable retries for service `ratings.prod` I make this VirtualService:

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ratings-route
spec:
  hosts:
  - ratings.prod.svc.cluster.local
  http:
  - route:
    - destination:
        host: ratings.prod.svc.cluster.local
    retries:
      attempts: 0
```

and then for `ratings.prod` I'd make another (or at least another entry in the spec) and so on.  I'm looking for a place to define the default `maxRetries` that should be used if no VS applies, or if a VS applies but doesn't override `maxRetries`.

**Describe alternatives you've considered**

- Defining a VirtualService (or spec entry) for each service I want to talk to.  Undesirable because there are a lot of services and if I ever want to change the default, I have to change many pieces of configuration associated with disparate apps.
- Defining a wildcard VirtualService.  Won't work for my case because I don't want to e.g. send all traffic to one service - I need to configure the route information separately from the retry policy.

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**
