### ISSUE TITLE
Operator generates invalid tracing config when using DataDog tracing.

### ISSUE THREAD

**Issue by nairb774** [istio/istio#31299]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

Using the IstioOperator to configure tracing with DataDog causes the mesh config to still have the zipkin tracing config. Minimal IstioOperator config:

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-system
  namespace: istio-system
spec:
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        datadog:
          address: tracing.datadog.svc.cluster.local:8126
```

And the resulting mesh config:

```yaml
apiVersion: v1
data:
  mesh: |-
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      proxyMetadata:
        DNS_AGENT: ""
      tracing:
        datadog:
          address: tracing.datadog.svc.cluster.local:8126
        zipkin:
          address: zipkin.istio-system:9411
    enablePrometheusMerge: true
    enableTracing: true
    rootNamespace: istio-system
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
kind: ConfigMap
metadata:
  labels:
    install.operator.istio.io/owning-resource: istio-system
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio.io/rev: default
    operator.istio.io/component: Pilot
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.8.2
    release: istio
  name: istio
  namespace: istio-system
```

As you can see under the `tracing` section, both `zipkin` and `datadog` are present. There is a random chance that the sidecar is injected with zipkin configuration or with datadog configuration as a result. About half of our pods do not send tracing information to DataDog as a result.

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

The datadog configuration is used and injected into all sidecars as configured with the IstioOperator CRD.

**Steps to reproduce the bug**

The 1.8.2 operator was installed on the cluster roughly using the istioctl cli. The above IstioOperator CRD was added to the cluster, and the config map above was observed. The yaml being generated for the config map seems to violate the MeshConfig specification as the `zipkin` and `datadog` entries are supposed to be mutually exclusive (oneof).

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

From minification on a Docker Desktop 1.19.3 cluster:

```$ istioctl version
client version: 1.9.1
control plane version: 1.8.2
data plane version: 1.8.2 (2 proxies)
```

Production cluster:

```
$ istioctl version
client version: 1.9.1
control plane version: 1.8.2
data plane version: 1.8.2 (81 proxies)
```

It is entirely possible this generates with other versions, this is just the set of configs I have in front of me and most directly matches what I see in our production clusters.

**How was Istio installed?**

1.8.2 operator.

**Environment where the bug was observed (cloud vendor, OS, etc)**

AWS EKS 1.18
Docker Desktop 1.19.3

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

This bug-report is from the docker desktop minified example: [bug-report.tar.gz](https://github.com/istio/istio/files/6096186/bug-report.tar.gz)
