### ISSUE TITLE
Unable to deploy ingress-gateway as a DaemonSet with version 1.9.1

### ISSUE THREAD

**Issue by shaz1v** [istio/istio#31303]
When deploying Istio on EKS, in order to get the connecting IP, we've changed Ingress Gateway to DaemonSet and externalTrafficPolicy to Local.

Trying to upgrade from 1.8.2 to 1.9.1, or installing 1.9.1 fresh on a new cluster, receiving the following error on Istio Operator: 

![image](https://user-images.githubusercontent.com/24204613/110232317-8eb9f080-7f25-11eb-95a9-6382e6775d84.png)

[X] Installation
[X] Upgrade

**Expected behavior**
Ingress Gateway deploying successfully as a DaemonSet.

**Steps to reproduce the bug**
1. Install Istio Operator
2. Create IstioOperator CRD with overlay modifications changing the gateway to DaemonSet:
3. 
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-system
spec:
    ingressGateways:
    - enabled: true
      k8s:
        overlays:
          - kind: Service
            name: istio-ingressgateway
            patches:
              - path: spec.externalTrafficPolicy
                value: Local
          - kind: Deployment
            name: istio-ingressgateway
            patches:
              - path: kind
                value: DaemonSet
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
      name: istio-ingressgateway
```

**Version** 
1.9.1

**How was Istio installed?** 
Istio Operator

**Environment where the bug was observed (cloud vendor, OS, etc)** 
AWS EKS

**Comment by morvencao** [comment]
This should not work since the resource are updated with server side apply, the resource Kind field is support by SSA.

**Comment by kvendingoldo** [comment]
@morvencao can't gateway be deployed as DaemonSet?

**Comment by t1gr4n** [comment]
Got this working in my case. Had to unset the the `spec.strategy` in the overlay. Tried it on version 1.9.2, but should work the same way on 1.9.1 as well, as the error complains about spec.strategy, which is not a part of the DaemonSet specification.
Here's a snippet from my working YAML
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        overlays:
        - kind: Deployment
          name: istio-ingressgateway
          patches:
            - path: kind
              value: DaemonSet
            - path: spec.strategy   # <- Adding this one unsets the spec.strategy, which is not part of the DaemonSet specicifation
# The rest of my YAML ...
```
