### ISSUE TITLE
Access to revisions of an external control plane

### ISSUE THREAD

**Issue by frankbu** [istio/istio#31322]
**Describe the feature request**

When using an [external control plane](http://localhost:1313/latest/docs/setup/additional-setup/external-controlplane/), the remote istiod location is configured in several places, three of which (`discoveryAddress`, `caAddress`, and `injectionURL`) should, but currently do not, take revisions into account:

```
spec:
  meshConfig:
    defaultConfig:
      discoveryAddress: $EXTERNAL_ISTIOD_ADDR:15012
  values:
    global:
      caAddress: $EXTERNAL_ISTIOD_ADDR:15012
    istiodRemote:
      injectionURL: https://$EXTERNAL_ISTIOD_ADDR:15017/inject
```

For example, when the the `injectionURL` value is set, it will be used in the MutatingWebhookConfiguration as is, with [no regard to the webhooks associated revision](https://github.com/istio/istio/blob/f6502508b04c38f9678c300821dd54e439b832ed/manifests/charts/istiod-remote/templates/mutatingwebhook.yaml#L8). Only the not-set (`{{- else }}`) uses the revision to select the correct istiod service.

If instead, we added a new variable (`istiodRemote.istiodURL`), we could pass the revision as a path prefix, which the external control plane could use to access the appropriate istiod revision:

```
    {{- if .Values.istiodRemote.injectionURL }}
    url: {{ .Values.istiodRemote.injectionURL }}
    {{- else if .Values.istiodRemote.istiodURL }}
    url: {{ .Values.istiodRemote.istiodURL }}:15017{{- if not (eq .Values.revision "") }}/{{ .Values.revision }}{{- end }}/inject
    {{- else }}
    service:
      name: istiod{{- if not (eq .Values.revision "") }}-{{ .Values.revision }}{{- end }}
      namespace: {{ .Release.Namespace }}
      path: "/inject"
    {{- end }}
```

If we make a similar change for all three variables, this would also simplify the external control plane configuration. Only one variable (`istiodRemote.istiodURL`) would need to be configured, instead of the current three:

```
spec:
  values:
    istiodRemote:
      istiodURL: https://$EXTERNAL_ISTIOD_ADDR
```

**Describe alternatives you've considered**

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**
