### ISSUE TITLE
EnvoyFilter configuration for http local rate limit with descriptors

### ISSUE THREAD

**Issue by hania-elayoubi** [istio/istio#31324]
**Envoy added the ability to set local rate limit using descriptors. Assuming this is available in Istio 1.9 through EnvoyFilter, could you please add a snippet to the local rate limit documentation here: https://istio.io/latest/docs/tasks/policy-enforcement/rate-limit/**

**Specifically, when I look at https://github.com/istio/proxy/pull/3161 to follow it as an example, I do not know where to place the rate limit **actions** in EnvoyFilter for it to take place with my local rate limit descriptors**
```
rate_limits:
- actions:
  - request_headers:
      header_name: user-id
      descriptor_key: id
```

[X] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features **

HTTP local Rate Limiting with descriptors using EnvoyFilter

**Additional context**

This is my EnvoyFilter config

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: inbound-8000
  namespace: app-ns
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter

    - applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_INBOUND
        routeConfiguration:
          vhost:
            name: "inbound|http|8000"
            route:
              name: "default"
      patch:
        operation: MERGE
        value:
          typed_per_filter_config:
            envoy.filters.http.local_ratelimit:
              "@type": type.googleapis.com/udpa.type.v1.TypedStruct
              type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
              value:
                stat_prefix: http_local_rate_limiter
                token_bucket:
                  max_tokens: 1
                  tokens_per_fill: 1
                  fill_interval: 20s
                filter_enabled:
                  runtime_key: local_rate_limit_enabled
                  default_value:
                    numerator: 100
                    denominator: HUNDRED
                filter_enforced:
                  runtime_key: local_rate_limit_enforced
                  default_value:
                    numerator: 100
                    denominator: HUNDRED
                response_headers_to_add:
                  - append: false
                    header:
                      key: x-local-rate-limit
                      value: 'true'
                descriptors:
                 - entries:
                   - key: id
                     value: a1
                   token_bucket:
                     max_tokens: 3
                     tokens_per_fill: 3
                     fill_interval: 20s
```

I tried multiple placements of 
```
rate_limits:
- actions:
  - request_headers:
      header_name: user-id
      descriptor_key: id
```
but I just can't get it to work correctly. I do see perhaps a similar issue reported here https://github.com/envoyproxy/envoy/issues/14851 but I don't know how to translate that into Istio's EnvoyFilter.

**Comment by p53** [comment]
i have similar problem i am trying to configure rate limit per route and till now i am unsuccessful, in examples docs there is no example of per route configuration

**Comment by hania-elayoubi** [comment]
@bianpengyuan are you OK to tag this as a bug? 

All references  to rate limit actions I could find for global rate limiting (e.g. https://github.com/istio/istio/blob/master/samples/bookinfo/policy/productpage_envoy_ratelimit.yaml#L57-L88) mention the rate limits action being configured for the **virtual host**. But I see @kyessenov  mention here https://github.com/envoyproxy/envoy/issues/14851#issuecomment-769204174 that for **local** rate limit

> You need to put rate limits into route since there is no automatic fallback to virtual host rate limits. 

I am unable to configure rate limit actions for HTTP_ROUTE, so I believe the EnvoyFilter API does not correctly allow defining the rate limit **actions** for **local** rate limiting in Envoy with **descriptors**

**Comment by kyessenov** [comment]
@hania-elayoubi Yeah, I think you are right. We need to either allow per-route EnvoyFilter or update Envoy to apply virtual host actions for routes.

**Comment by bianpengyuan** [comment]
Seems to be working for me with the following patch:

```
   - applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_INBOUND
        routeConfiguration:
          vhost:
            name: "inbound|http|8000"
            route:
              name: "default"
      patch:
        operation: MERGE
        value:
          route:
            rate_limits:
            - actions:
              - request_headers:
                  header_name: user-id
                  descriptor_key: id
          typed_per_filter_config:
            envoy.filters.http.local_ratelimit:
              "@type": type.googleapis.com/udpa.type.v1.TypedStruct
              type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
              value:
```

**Comment by hania-elayoubi** [comment]
Thank you!! I can finally configure this for the HTTP_ROUTE. For reference, here's my full EnvoyFilter

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: httpbin-inbound-8000
  namespace: app-namespace
spec:
  workloadSelector:
    labels:
      app: httpbin
  configPatches:
    - applyTo: HTTP_FILTER
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter

    - applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_INBOUND
        routeConfiguration:
          vhost:
            name: "inbound|http|8000"
      patch:
        operation: MERGE
        value:
          route:
            rate_limits:
              - actions:
                - request_headers:
                    header_name: "user-id"
                    descriptor_key: "ID"

          typed_per_filter_config:
            envoy.filters.http.local_ratelimit:
              "@type": type.googleapis.com/udpa.type.v1.TypedStruct
              type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
              value:
                stat_prefix: http_local_rate_limiter

                descriptors:
                 - entries:
                   - key: ID
                     value: a
                   token_bucket:
                     max_tokens: 2
                     tokens_per_fill: 2
                     fill_interval: 20s
                 - entries:
                   - key: ID
                     value: b
                   token_bucket:
                     max_tokens: 2
                     tokens_per_fill: 2
                     fill_interval: 20s

                filter_enabled:
                  runtime_key: local_rate_limit_enabled
                  default_value:
                    numerator: 100
                    denominator: HUNDRED
                filter_enforced:
                  runtime_key: local_rate_limit_enforced
                  default_value:
                    numerator: 100
                    denominator: HUNDRED
                response_headers_to_add:
                  - append: false
                    header:
                      key: x-local-rate-limit
                      value: 'true'
                token_bucket:
                  max_tokens: 10
                  tokens_per_fill: 10
                  fill_interval: 20s
```

**Comment by bianpengyuan** [comment]
Great, thanks!

**Comment by aniket-z** [comment]
@hania-elayoubi @bianpengyuan Could you please also help me understand what I am doing wrong here? I would highly appreciate it.

I have an application which has two endpoints: "/invocations" and "/ping". I am trying to setup local-rate-limit on both these endpoints such that rate-limiting of both endpoints is independent of each other. For example: I would want 1 request-per-second rate-limit for "/invocations" endpoint and an independent 1 request-per-second rate-limit for "/ping" endpoint.

This is the EnvoyFilter I am using:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: distance-prediction-v1-ratelimit-svc
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: distance-prediction
      version: v1
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter

    - applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_INBOUND
        routeConfiguration:
          vhost:
            name: "inbound|http|8080"
            route:
              action: ANY
      patch:
        operation: MERGE
        value:
          route:
              rate_limits:
              - actions:
                - request_headers:
                    header_name: ":path"
                    descriptor_key: path 
          typed_per_filter_config:
            envoy.filters.http.local_ratelimit:
              "@type": type.googleapis.com/udpa.type.v1.TypedStruct
              type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
              value:
                stat_prefix: http_local_rate_limiter
                token_bucket:
                  max_tokens: 1
                  tokens_per_fill: 1
                  fill_interval: 1s
                filter_enabled:
                  runtime_key: local_rate_limit_enabled
                  default_value:
                    numerator: 100
                    denominator: HUNDRED
                filter_enforced:
                  runtime_key: local_rate_limit_enforced
                  default_value:
                    numerator: 100
                    denominator: HUNDRED
                response_headers_to_add:
                  - append: false
                    header:
                      key: x-local-rate-limit
                      value: "true" 
                descriptors:
                  - entries:
                    - key: path
                      value: /invocations
                    token_bucket:
                      max_tokens: 1
                      tokens_per_fill: 1
                      fill_interval: 1s
                  - entries:
                    - key: path
                      value: /ping
                    token_bucket:
                      max_tokens: 1
                      tokens_per_fill: 1
                      fill_interval: 1s
```


However, it seems that traffic to both endpoints is using same token bucket and thus rate-limiting is not independent. If I send 2 reqeusts-per-second to "/invocations" (using a simple while loop) and send 1 request-per-second to "/ping" endpoint, my expectation was that "/ping" endpoint would not get rate limited. However, I see both endpoints get rate-limited using common 1 request-per-second limit.

I am using Istio version: 1.8.1 and Kubernetes version: 1.19 (AWS EKS)
