### ISSUE TITLE
Unable to get two AuthorizationPolicies configured for same workload

### ISSUE THREAD

**Issue by alecor191** [istio/istio#31335]
I have the following scenario:

- Let OPTIONS request reach workloads even if they don't have Authorization header set
- Validate JWT token for all non-OPTIONS requests to the same workload

The way I thought we could achieve this is by:

- Have an AuthoziationPolicy that allows OPTIONS requests without "from"
- Have an AuthorizationPolicy that requires all non-OPTIONS requests coming from Ingress Gateway to have an Authorization header
- Have a RequestAuthentication that validates the JWT token ensuring it's valid and has the proper audience set

```yaml
# By default, none of the services in namespace accept incoming traffic.
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: default-deny-all
  namespace: {{ .Values.teamNamespace }}
  labels:
    {{- include "labels.shared.tpl" . | indent 4 }}
spec: {}
---
# Allow OPTIONS requests without authentication information to reach the desired workload
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: public-web-api-allow-options
  namespace: {{ .Values.teamNamespace }}
spec:
  selector:
    matchLabels:
      app.example.com/access-policy: public
      app.example.com/access-policy-audience: frontoffice
  action: ALLOW
  rules:
    - to:
        - operation:
            methods: ["OPTIONS"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: public-web-api-require-jwt-frontoffice
  namespace: {{ .Values.teamNamespace }}
spec:
  selector:
    matchLabels:
      app.example.com/access-policy: public
      app.example.com/access-policy-audience: frontoffice
  action: ALLOW
  rules:
    # The below defines: EITHER we have a request with auth information (JWT token) OR the request does not come from
    # listed namespaces. IOW we accept _anonymous_ requests from team-a, team-b namespaces but only requests with JWT
    # token from istio-system/example/default namespaces.
    - from:
        - source:
            requestPrincipals: ["*"]
        - source:
            notNamespaces: ["istio-system", "example", "default"]
    - to:
        - operation:
            notMethods: ["OPTIONS"]
---
# Ingress Gateway Traffic to services with label "app.pyracloud.com/access-policy-audience: frontoffice" will check if
# the JWT token in the incoming request contains the correct audience. If not, the request will fail.
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: ops-pyc-cluster-teamsetup-public-web-api-require-jwt-auth0-frontoffice
  namespace: {{ .Values.teamNamespace }}
spec:
  selector:
    matchLabels:
      app.example.com/access-policy: public
      app.example.com/access-policy-audience: frontoffice
  jwtRules:
    - audiences:
      - "https://api.example.com/"
      issuer: {{ $issuer }}
      jwksUri: {{ $jwksUri }}
      forwardOriginalToken: true
```

**Expected behavior**
- OPTIONS requests coming from the Ingress Gateway (istio-system namespace) will reach the desired workload
- GET requests coming from the Ingress Gateway (istio-system namespace) will only reach the desired workload if they have an "Authorization" header and that header contains a valid JWT token with audience "https://api.example.com".

**Actual behavior**
It's the opposite! OPTIONS requests fail with 403 and GET requests _without_ Authorization header reach the workload.

If I ignore the OPTIONS scenario for a moment and just want Istio to validate JWT tokens for requests with any HTTP verb, then the following works like a charm: Requests from different namespaces reach workloads without requiring Authorization header and requests coming from Ingress Gateway require a valid JWT token...with the caveat that OPTIONS requests end up getting blocked with 403.

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: default-deny-all
  namespace: {{ .Values.teamNamespace }}
  labels:
    {{- include "labels.shared.tpl" . | indent 4 }}
spec: {}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: public-web-api-require-jwt-frontoffice
  namespace: {{ .Values.teamNamespace }}
spec:
  selector:
    matchLabels:
      app.example.com/access-policy: public
      app.example.com/access-policy-audience: frontoffice
  action: ALLOW
  rules:
    - from:
        - source:
            requestPrincipals: ["*"]
        - source:
            notNamespaces: ["istio-system", "example", "default"]
---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: ops-pyc-cluster-teamsetup-public-web-api-require-jwt-auth0-frontoffice
  namespace: {{ .Values.teamNamespace }}
spec:
  selector:
    matchLabels:
      app.example.com/access-policy: public
      app.example.com/access-policy-audience: frontoffice
  jwtRules:
    - audiences:
      - "https://api.example.com/"
      issuer: {{ $issuer }}
      jwksUri: {{ $jwksUri }}
      forwardOriginalToken: true
```

Note that in the above I just removed the "to" from the rule and completely removed the AuthorizationPolicy for OPTIONS-only traffic.

Do you have any thoughts on what I'm doing wrong resp. how to implement the scenario above?

(I understand that we can set CORS policies on the VirtualService, however, that's not a viable option for us as we already have 200 services that we're migrating to Istio and they already have custom CORS logic implemented; so we just want to let OPTIONS traffic through to the workload)

**Comment by alecor191** [comment]
The issue in my posting above is that I had a typo in the YAML. The described scenario is achievable with the following yaml:

I found it by reading the very helpful [Security Problems](https://istio.io/latest/docs/ops/common-problems/security-issues/#make-sure-there-are-no-typos-in-the-policy-yaml-file) Istio article.

```yaml
# By default, none of the services in namespace accept incoming traffic.
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: default-deny-all
  namespace: {{ .Values.teamNamespace }}
  labels:
    {{- include "labels.shared.tpl" . | indent 4 }}
spec: {}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: public-web-api-require-jwt-frontoffice
  namespace: {{ .Values.teamNamespace }}
spec:
  selector:
    matchLabels:
      app.example.com/access-policy: public
      app.example.com/access-policy-audience: frontoffice
  action: ALLOW
  rules:
    # The below defines: EITHER we have a request with auth information (JWT token) OR the request does not come from
    # listed namespaces. IOW we accept _anonymous_ requests from team-a, team-b namespaces but only requests with JWT
    # token from istio-system/example/default namespaces.
    - from:
        - source:
            requestPrincipals: ["*"]
        - source:
            notNamespaces: ["istio-system", "example", "default"]
      to:
        - operation:
            notMethods: ["OPTIONS"]
    # Allow OPTIONS requests without Authentication header
    - to:
        - operation:
            methods: ["OPTIONS"]
---
# Ingress Gateway Traffic to services with label "app.pyracloud.com/access-policy-audience: frontoffice" will check if
# the JWT token in the incoming request contains the correct audience. If not, the request will fail.
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: ops-pyc-cluster-teamsetup-public-web-api-require-jwt-auth0-frontoffice
  namespace: {{ .Values.teamNamespace }}
spec:
  selector:
    matchLabels:
      app.example.com/access-policy: public
      app.example.com/access-policy-audience: frontoffice
  jwtRules:
    - audiences:
      - "https://api.example.com/"
      issuer: {{ $issuer }}
      jwksUri: {{ $jwksUri }}
      forwardOriginalToken: true
```
