### ISSUE TITLE
circuit break settings not applied to inbound cluster

### ISSUE THREAD

**Issue by yingzhuivy** [istio/istio#31346]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
circuit break settings in destination rule is only applied on the client side (outbound cluster), but not applied on the server side (inbound cluster). I'm using istio 1.7.5, and seems like the issue is fixed on 1.8.3, but I wasn't able to find which PR fixed the issue. any help would be appreciated.

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
should be applied to both outbound & inbound clusters

**Steps to reproduce the bug**
here is my destination rule config:
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: fortioserver
  namespace: fortioserver
spec:
  host:  fortioserver.fortioserver.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      http:
        http1MaxPendingRequests: 1024
        http2MaxRequests: 1024
        maxRetries: 1000
      tcp:
        connectTimeout: 0.200s
        maxConnections: 8192
```
on the client side, the config dump show:
```
cluster: {
@type: "type.googleapis.com/envoy.config.cluster.v3.Cluster",
name: "outbound|8080||fortioserver.fortioserver.svc.cluster.local",
type: "EDS",
eds_cluster_config: {
eds_config: {
ads: { },
resource_api_version: "V3"
},
service_name: "outbound|8080||fortioserver.fortioserver.svc.cluster.local"
},
connect_timeout: "0.200s",
circuit_breakers: {
thresholds: [
{
max_connections: 8192,
max_pending_requests: 1024,
max_requests: 1024,
max_retries: 1000
}
]
},
```
however, on the server side, the inbound cluster:
```
{
version_info: "2021-03-09T22:19:45Z/54233",
cluster: {
@type: "type.googleapis.com/envoy.config.cluster.v3.Cluster",
name: "inbound|8080||localhost",
type: "STATIC",
connect_timeout: "10s",
circuit_breakers: {
thresholds: [
{
max_connections: 4294967295,
max_pending_requests: 4294967295,
max_requests: 4294967295,
max_retries: 4294967295
}
]
},
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

istio 1.7.5
