### ISSUE TITLE
Unable to View VirtualService On Istio Gateway

### ISSUE THREAD

**Issue by rileyhun** [istio/istio#31354]
**Bug description**

Hello -

I'm having trouble viewing my grafana instance after I applied a virtual service against Istio Ingress Gateway on Google Kubernetes Engine. I did the same approach for my Kibana service and that seems to be viewable.  I have port-forwarded the Grafana service and I can confirm that it is working so there shouldn't be issues with the application itself. 

Virtual Service for Grafana

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana
  namespace: monitoring
spec:
  gateways:
    - istio-system/ops-gateway
  hosts:
    - '*'
  http:
    - match:
        - uri:
            prefix: /grafana/
      rewrite:
        uri: /
      route:
        - destination:
            host: seldon-core-analytics-grafana
            port:
              number: 80
```

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

This doesn't work: "http://${IP_ADDRESS}/grafana/"
This works: "http://${IP_ADDRESS}/kibana/

**Version** 
1.7.7
