### ISSUE TITLE
websocket broken link

### ISSUE THREAD

**Issue by sunnoy** [istio/istio#31360]
**Bug description**
The websocket service is disconnected after injecting the proxy container, The proxy container adds several http response headers when responding to `HTTP/1.1 101 Switching Protocols`, Why `upgrade: WebSocket` and `transfer-encoding: chunked` exist at the same time

```bash
HTTP/1.1 101 Switching Protocols
connection: Upgrade
sec-websocket-location: ws://xxx
origin: https://xxx.xxx.com
upgrade: WebSocket
sec-websocket-accept: IfU1lRATA6HUrkfL54bVbxOigPo=
date: Wed, 10 Mar 2021 09:16:01 GMT
# add http resp headers
server: istio-envoy
x-envoy-decorator-operation: xxxx.svc.cluster.local:8080/*
transfer-encoding: chunked
```

[ x] Networking

**Comment by howardjohn** [comment]
What version of istio? there were some recent changes that may have fixed this

**Comment by sunnoy** [comment]
```bash
istioctl version
client version: 1.9.1
control plane version: 1.9.1
data plane version: 1.8.2 (86 proxies), 1.9.1 (44 proxies)
```

**Comment by howardjohn** [comment]
Can you give more info on how to reproduce this? is there some public website or app we can hit?

**Comment by sunnoy** [comment]
When the client recognizes the response header, it distinguishes between upper and lower case，The client only recognizes "Sec-Web**S**ocket-Accept",envoy give  "sec-web**s**ocket-accept"

**Please pay attention to the "s" in the word "socket"**

I adjusted the case format through the following configuration but got "Sec-Web**s**ocket-Accept"

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: http-header-case
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: ANY
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          http_protocol_options:
            header_key_format:
              # Formats the header by proper casing words: 
              # the first character and any character following a special character will be capitalized if it’s an alpha character. 
              # For example, “content-type” becomes “Content-Type”, and “foo$b#$are” becomes “Foo$B#$Are”. 
              # Note that while this results in most headers following conventional casing, 
              # certain headers are not covered. For example, the “TE” header will be formatted as “Te”.
              proper_case_words: {}
```

So I wanted to rewrite the response header in the following way, but envoy changed the custom header to lowercase

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: rewrite-ws-header
  namespace: business
spec:
  workloadSelector:
    labels:
      app: access-undertow
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      # context: SIDECAR_OUTBOUND
    patch:
      operation: INSERT_BEFORE
      value: 
        name: envoy.filters.http.lua
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
          inlineCode: |-

            function envoy_on_response(response_handle)

              swa = response_handle:headers():get("sec-websocket-accept")


              response_handle:headers():add("Sec-WebSocket-Accept", swa)


            end
```

Do you have a good solution ?
