### ISSUE TITLE
Ingressgateway TLS not working

### ISSUE THREAD

**Issue by a8j8i8t8** [istio/istio#31363]
**Bug description**
Ingressgateway with TLS gateway is not working as expected.
My deployment, service and virtual-service are in namespace-1.
```
spec:
  gateways:
    - istio-system/my-gateway
  hosts:
    - links.dev.domain.us
  http:
    - match:
        - uri:
            prefix: /status
        - uri:
            prefix: /delay
      route:
        - destination:
            host: httpbin.namespace-1.svc.cluster.local
            port:
              number: 8000
```
My gateway and secrets are in istio-system namespace
```
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - '*.dev.domain.us'
      port:
        name: http-gw
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - '*.dev.domain.us'
      port:
        name: https-gw
        number: 443
        protocol: HTTPS
      tls:
        credentialName: links-credential
        mode: SIMPLE
```

For HTTP it works as expected.
```
# curl http://172.23.8.219:32400/status -v -HHost:links.dev.domain.us
*   Trying 172.23.8.219...
* TCP_NODELAY set
* Connected to 172.23.8.219 (172.23.8.219) port 32400 (#0)
> GET /status HTTP/1.1
> Host:links.dev.domain.us
> User-Agent: curl/7.61.1
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< location: https://links.dev.domain.us/status
< date: Wed, 10 Mar 2021 13:46:51 GMT
< server: istio-envoy
< content-length: 0
< 
* Connection #0 to host 172.23.8.219 left intact
```

But for HTTPS I'm getting `SSL_ERROR_SYSCALL` :-( 
```
# curl https://172.23.8.219:30975/status -v -HHost:links.dev.domain.us
*   Trying 172.23.8.219...
* TCP_NODELAY set
* Connected to 172.23.8.219 (172.23.8.219) port 30975 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 172.23.8.219:30975 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 172.23.8.219:30975
```

Ingress-gateway seems to be picking up the secret.
```
❯ istioctl proxy-config secret istio-ingressgateway-8468949c7-fc9q5.istio-system                                           
RESOURCE NAME                     TYPE           STATUS     VALID CERT     SERIAL NUMBER                              NOT AFTER                NOT BEFORE
default                           Cert Chain     ACTIVE     true           21334964214066839007526599592925687703     2021-03-11T11:11:49Z     2021-03-10T11:11:49Z
kubernetes://links-credential     Cert Chain     ACTIVE     true           0                                          2022-03-10T11:46:31Z     2021-03-10T11:46:31Z
ROOTCA                            CA             ACTIVE     true           92561758054901290433755532755216654056     2031-03-07T15:15:38Z     2021-03-09T15:15:38Z
```
**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

Istio version - 1.9.1
K8S version - 1.19.8

**How was Istio installed?**
With Istio operator.

**Comment by howardjohn** [comment]
```
    - hosts:
        - '*.dev.domain.us'
      port:
        name: https-gw
        number: 443
        protocol: HTTPS
```

Means "do an SNI match for  '*.dev.domain.us'". You are not setting an SNI because of how you are sending your curl. You need to either set up the domain with proper dns so you can curl directly (ie without manual Host header) or tell curl what to do using `--resolve`. This is described in https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/#configure-a-tls-ingress-gateway-for-a-single-host.

Closing as this is working as intended. Thanks!
