### ISSUE TITLE
Istio 1.9 - DNS capture and wildcard hosts

### ISSUE THREAD

**Issue by prashantchari** [istio/istio#31372]
I'm trying out the DNS capture functionality that's in 1.9, and I'm noticing that the DNS resolutions do not work for wildcard hosts. Curious if this is by design or if I'm missing anything here ? I'm trying the documented example where I'm using "*.address.internal" instead of the "address.internal" string,
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-address
spec:
  addresses:
  - 198.51.100.0
  hosts:
  - "*.address.internal"
  ports:
  - name: http
    number: 80
    protocol: HTTP
```

A DNS query for a subdomain of that host returns the following - 
```
# nslookup foo.address.internal
Server:         10.0.0.10
Address:        10.0.0.10#53

** server can't find foo.address.internal: NXDOMAIN
```
