### ISSUE TITLE
Istio 1.7.7 - RequestAuthentication Unknown fields "trigger_rules" and "principalBinding"

### ISSUE THREAD

**Issue by rileyhun** [istio/istio#31384]
**Bug description**
I am trying to apply an [istio authentication policy ](https://cloud.google.com/solutions/authenticating-cloud-run-on-gke-end-users-using-istio-and-identity-platform#add_an_istio_authentication_policy). 

My authentication policy looks like this:

```
apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: api-origin-auth
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
    - issuer: "https://securetoken.google.com/${PROJECT_ID}"
      audiences:
      - "${PROJECT_ID}"
      jwksUri: "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"
      trigger_rules:
      - excluded_paths:
        - exact: /api/healthz
        included_paths:
        - prefix: /api/
  principalBinding: USE_ORIGIN
```

The error I'm getting is:
```
unknown field "trigger_rules" in io.istio.security.v1beta1.RequestAuthentication.spec.jwtRules, ValidationError(RequestAuthentication.spec): unknown field "principalBinding" in io.istio.security.v1beta1.RequestAuthentication.spec]; if you choose to ignore these errors, turn validation off with --validate=false
```

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Version**
1.7.7
