### ISSUE TITLE
AuthorizationPolicy in Different Namespace

### ISSUE THREAD

**Issue by rileyhun** [istio/istio#31404]
**Bug description**

Hello - 

I tried applying authentication + authorization on a different namespace that is hosting a REST API endpoint but is being load balanced through the ingress-gateway from namespace `istio-system`.  Unfortunately, that didn’t seem to work for me, as my requests to the REST API went through and I wasn’t denied access. Any insight on this?

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
I should have been denied access without being an authorized user

**Steps to reproduce the bug**
```
---
apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: istio-ingress-jwt
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
    - issuer: "https://accounts.google.com"
      jwksUri: "https://www.googleapis.com/oauth2/v3/certs"
      audiences:
        - "${PROJECT_ID}"
      fromHeaders:
        - name: Authorization
          prefix: "Bearer "
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: istio-invoker
  namespace: '${MODELS_NAMESPACE}'
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        hosts:
        - '${IP_ADDRESS}'
    when:
    - key: request.auth.claims[aud]
      values:
      - 'http://${IP_ADDRESS}'
    - key: request.auth.claims[email]
      values:
      - "${SERVICE_ACCOUNT_EMAIL}"
    - key: request.auth.claims[iss]
      values:
      - https://accounts.google.com
  selector:
   matchLabels:
     istio: ingressgateway
```

How I'm calling the API:

```
import requests
import random
from google.auth.transport.requests import AuthorizedSession
from google.oauth2 import service_account

creds = service_account.IDTokenCredentials.from_service_account_file(
        SERVICE_ACCOUNT_FILE,
        target_audience=TARGET_AUDIENCE)

authed_session = AuthorizedSession(creds)

payload = {'data':
           {"ndarray": [[random.uniform(0, 30) for _ in range(4)]]}
          }

resp = authed_session.post(URL,
                           headers={'Content-Type': 'application/json'},
                           json=payload)

```

**Version**
1.7.7

**Environment where the bug was observed (cloud vendor, OS, etc)**
MacOS

Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by jeremyzahner** [comment]
@rileyhun Facing the same problem. Did you find a solution?

**Comment by rileyhun** [comment]
@jeremyzahner Something like this worked for me:

```
---
apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: "ai-for-good-iris-service-jwt-policy"
  namespace: ai-for-good
spec:
  selector:
    matchLabels:
        seldon-deployment-id: spt-model
  jwtRules:
  - issuer: https://accounts.google.com
    audiences:
      - "${PROJECT_ID}"
    jwksUri: https://www.googleapis.com/oauth2/v3/certs
    forwardOriginalToken: true
---
apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
  name: "ai-for-good-iris-service-authz-policy"
  namespace: ai-for-good
spec:
  selector:
    matchLabels:
      seldon-deployment-id: spt-model
  action: ALLOW
  rules:
  - to:
    - operation:
        methods: ["POST"]
    when:
      - key: request.auth.claims[aud]
        values:
          - "${PROJECT_ID}"
      - key: request.auth.claims[email]
        values:
          - "gcp-svc-key@${PROJECT_ID}.iam.gserviceaccount.com"
      - key: request.auth.claims[iss]
        values:
          - "https://accounts.google.com"
#  - from:
#    - source:
#        namespaces: ["monitoring", "ai-for-good"]
  - to:
    - operation:
        methods: ["GET"]
        paths: ["/prometheus"]
        ports: ["6000", "8000", "6001"]


```
