### ISSUE TITLE
NodePort for ingressgateway loadbalancer service change every time there is a change to the service through the operator breaking upstream cloud LoadBalancers

### ISSUE THREAD

**Issue by primeroz** [istio/istio#31418]
**Bug description**
Link to my post in the [forum](https://discuss.istio.io/t/ingressgateway-service-keep-changing-nodeport-whenever-a-change-to-the-service-is-applied-through-istio-operator-breaking-my-upstream-cloudlb/9983)

When deploying an ingressgateway using the operator a `Service` of type `LoadBalancer` is created and some nodeports are allocated. This ports are supposed to be **immutable** and in particular when used with AWS load balancer they must be since the option can't be updated in the targetgroup once the TG is created.

Whenever a change to the service is applied by the istio-operator though the `nodeport` change causing the Upstream cloud load balancer to break either temporarily , if the cloud resource can be updated, or indefinitely in aws where the tg cannot be updated with the new port. 

My Current Workaround is to set the nodeport in the service spec , but that is fragile and potentially could create conflict 

On a unmanaged `Service Loadbalancer` any change can be performed without causing the nodeport to change.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

Service managed by the istio operator should behave like a normal un-managed kubernetes service loadbalancer, nodeports should not change once allocated.

**Steps to reproduce the bug**
* Install istio operator
* apply a resource like
```
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: standard
  namespace: istio-system
spec:
  components:
    ingressGateways:
    - enabled: true
      k8s:
        service:
          ports:
          - name: http
            port: 80
            targetPort: 8080
          - name: https
            port: 443
            targetPort: 8443
      name: public-ingress
      namespace: istio-system
  profile: default
```
* wait for the service to show up nodeport is **80:31497**
```
public-ingress     LoadBalancer   10.96.195.87    <pending>     80:31497/TCP,443:32045/TCP              3m30s
```
* change port name from `http` to `http2` and apply istiooperator  - watch the nodeports change - > **80:31748**
```
public-ingress     LoadBalancer   10.96.195.87    <pending>     80:31748/TCP,443:30293/TCP              4m42s
```
* add a new port - apply the istiooperator - watch the nodeports change -> **80:30834**
```
public-ingress     LoadBalancer   10.96.195.87    <pending>     80:30834/TCP,443:30052/TCP,15443:30516/TCP   5m5s
```

For comparison when the same is done to an un-managed service everything works as expected
* create service
```
zipkin-np    LoadBalancer   10.96.139.8   <pending>     9411:32027/TCP   0s
```
* change port name from http to http2
```
zipkin-np    LoadBalancer   10.96.139.8   <pending>     9411:32027/TCP   13s
```
* Change target port
```
zipkin-np    LoadBalancer   10.96.139.8   <pending>     9411:32027/TCP   21s
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.5.10+ -> 1.9.1

**How was Istio installed?**
* istio-operator

**Environment where the bug was observed (cloud vendor, OS, etc)** both on Kind locally and AWS. k8s version 1.16.15 in both cases

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
