### ISSUE TITLE
Tracing settings do not change after updating the operator's config

### ISSUE THREAD

**Issue by F21** [istio/istio#31414]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
The tracing settings under `meshConfig.defaultConfig.tracing` does not update when updating the istio operator.

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[X] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
According to this page: https://istio.io/latest/docs/setup/install/operator/#update , the operator should be updated after the configuration is updated.

**Steps to reproduce the bug**
I am using minikube (`minikube version: v1.18.1 commit: 09ee84d530de4a92f00f1c5dbc34cead092b95bc`)

1. `minikube start`
2. `istioctl operator init`
3. `kubectl label namespace default istio-injection=enabled --overwrite`
4. `kubectl create ns istio-system`
5. Install operator:
```
kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: demo
EOF
```
5. Install bookinfo: https://istio.io/latest/docs/examples/bookinfo/
6. Install jaeger: https://istio.io/latest/docs/ops/integrations/jaeger/#installation
7. Run `minikube tunnel`
8. Access book info via `localhost/productpage`.
9. Tunnel Jaeger dashboard: `istioctl dashboard jaeger`
10. See that traces show up in jaeger
11. Update tracer config:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: demo
  meshConfig:
    defaultConfig:
      tracing:
        sampling: 100
        openCensusAgent:
          address: collector.default:55678
          context: [W3C_TRACE_CONTEXT]
```
12. Access bookinfo and go to the jaeger dashboard to find that the new traces are sent showing in jaeger.
13. Delete bookinfo and redeploy.
14. Access bookinfo and go to the jaeger dashboard to find that the new traces are sent showing in jaeger.
15. Fully delete operator and set up a new one with the updated tracer config.
16. Traces are finally sent to the correct / customized agent.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
istioctl:
client version: 1.9.1
control plane version: 1.9.1
data plane version: 1.9.1 (9 proxies)

kubectl:
Client Version: v1.19.7
Server Version: v1.20.2
```

**How was Istio installed?**
Using the operator (see steps above).

**Environment where the bug was observed (cloud vendor, OS, etc)**
Minikube with Docker Desktop 3.2.1 and WSL2 on Windows 10 20H2 (latest updates).

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
