### ISSUE TITLE
DestinationRule not disabling mTLS for specific pod

### ISSUE THREAD

**Issue by darkdatter** [istio/istio#31425]
**Bug description**

I am using STRICT mTLS in my workload namespace, and then am using a DestinationRule to set TLS mode to DISABLE for a single pod container. My external client results in a Connection refused (I can see the RST on the interface come from the host:8111 referenced below). Do I need to use PortLevelMtls in order to disable STRICT mTLS for a particular TCP port? 

**Affected product area**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
TCP clear traffic should be allowed.

**Steps to reproduce the bug**
- Create a listening service within istio-controlled namespace (i.e. test)
- Create Gateway, Virtual Service, Service, and Destination Rule
- Use client to send TCP traffic to listener in the clear 

Gateway:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
  namespace: test
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 8111
      name: tcp
      protocol: TCP
    hosts:
    - "*"
```

Virtual Service:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-virtualsvc
  namespace: test
spec:
  hosts:
  - "*" # FQDN of service
  gateways:
  - my-gateway
  tcp:
  - match:
    - port: 8111 # Arrival port (external)
    route:
    - destination:
        host: listen-service.test.svc.cluster.local # FQDN of service
        port:
          number: 8111 # Destination service port (internal)
```

Service:
```
apiVersion: v1
kind: Service
metadata:
  name: listen-service
  namespace: test
spec:
  selector:
    app: listen
  ports:
    - name: testport
      protocol: TCP
      port: 8111
      targetPort: 8111
  type: LoadBalancer
```

Destination Rule:
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: listen
  namespace: test
spec:
  host: listen-service.test.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
```

**Version** 
Istio:
client version: 1.8.2
control plane version: 1.8.2
data plane version: 1.8.2 (16 proxies)

kubectl:
Client Version: v1.18.15+k3s1
Server Version: v1.18.15+k3s1

k3s:
k3s version v1.18.15+k3s1 (60f1e80d)

**How was Istio installed?**
istioctl install
(default profile)

**Environment where the bug was observed (cloud vendor, OS, etc)**
k3s running on AWS instances (k3s version v1.18.15+k3s1 (60f1e80d))
