### ISSUE TITLE
TPROXY interception mode is ignored in VM setup

### ISSUE THREAD

**Issue by pisto** [istio/istio#31424]
**Bug description**
TPROXY interception mode is ignored in a standalone Istio sidecar installation for virtual machines.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**
Install Istio on kubernets with interception mode TPROXY, follow the guide for a VM installation (https://istio.io/latest/docs/setup/install/virtual-machine/). Inspect iptables-save, the interception mode is by redirection.

`mesh.yaml`:
```yaml
defaultConfig:
  discoveryAddress: istiod.istio-system.svc:15012
  interceptionMode: TPROXY
  meshId: cloud-native
  proxyMetadata:
    CANONICAL_REVISION: latest
    CANONICAL_SERVICE: virtualmachine
    ISTIO_META_AUTO_REGISTER_GROUP: virtualmachine
    ISTIO_META_CLUSTER_ID: eks-1
    ISTIO_META_DNS_CAPTURE: "true"
    ISTIO_META_MESH_ID: cloud-native
    ISTIO_META_NETWORK: eks-1
    ISTIO_META_WORKLOAD_NAME: virtualmachine
    ISTIO_METAJSON_LABELS: '{"app":"virtualmachine","service.istio.io/canonical-name":"virtualmachine","service.istio.io/canonical-version":"latest"}'
    POD_NAMESPACE: vm-eks-1
    SERVICE_ACCOUNT: virtualmachine
    TRUST_DOMAIN: cluster.local
  readinessProbe:
    initialDelaySeconds: 1
    periodSeconds: 5
    tcpSocket:
      port: 111
  tracing:
    zipkin:
      address: zipkin.istio-system:9411
```
`cluster.env`:
```
CANONICAL_REVISION='latest'
CANONICAL_SERVICE='virtualmachine'
ISTIO_INBOUND_PORTS='*'
ISTIO_METAJSON_LABELS='{"app":"virtualmachine","service.istio.io/canonical-name":"virtualmachine","service.istio.io/canonical-version":"latest"}'
ISTIO_META_AUTO_REGISTER_GROUP='virtualmachine'
ISTIO_META_CLUSTER_ID='eks-1'
ISTIO_META_DNS_CAPTURE='true'
ISTIO_META_MESH_ID='cloud-native'
ISTIO_META_NETWORK='eks-1'
ISTIO_META_WORKLOAD_NAME='virtualmachine'
ISTIO_NAMESPACE='vm-eks-1'
ISTIO_SERVICE='virtualmachine.vm-eks-1'
ISTIO_SERVICE_CIDR='*'
POD_NAMESPACE='vm-eks-1'
SERVICE_ACCOUNT='virtualmachine'
TRUST_DOMAIN='cluster.local'
```
output of `iptables-save`:
```
# Generated by iptables-save v1.8.4 on Fri Mar 12 16:36:39 2021
*mangle
:PREROUTING ACCEPT [16010:1981452]
:INPUT ACCEPT [16010:1981452]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [15489:1262432]
:POSTROUTING ACCEPT [15489:1262432]
COMMIT
# Completed on Fri Mar 12 16:36:39 2021
# Generated by iptables-save v1.8.4 on Fri Mar 12 16:36:39 2021
*filter
:INPUT ACCEPT [31535:217663412]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [23963:1790676]
:DOCKER - [0:0]
:DOCKER-ISOLATION-STAGE-1 - [0:0]
:DOCKER-ISOLATION-STAGE-2 - [0:0]
:DOCKER-USER - [0:0]
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION-STAGE-1
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -j RETURN
-A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -j RETURN
-A DOCKER-USER -j RETURN
COMMIT
# Completed on Fri Mar 12 16:36:39 2021
# Generated by iptables-save v1.8.4 on Fri Mar 12 16:36:39 2021
*nat
:PREROUTING ACCEPT [20:1152]
:INPUT ACCEPT [20:1152]
:OUTPUT ACCEPT [2782:180304]
:POSTROUTING ACCEPT [2859:185588]
:DOCKER - [0:0]
:ISTIO_INBOUND - [0:0]
:ISTIO_IN_REDIRECT - [0:0]
:ISTIO_OUTPUT - [0:0]
:ISTIO_REDIRECT - [0:0]
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A OUTPUT -p udp -m udp --dport 53 -m owner --uid-owner 995 -j RETURN
-A OUTPUT -p udp -m udp --dport 53 -m owner --gid-owner 995 -j RETURN
-A OUTPUT -d 192.168.0.2/32 -p udp -m udp --dport 53 -j REDIRECT --to-ports 15053
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A DOCKER -i docker0 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15008 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A ISTIO_OUTPUT -s 127.0.0.6/32 -o lo -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -p tcp -m tcp ! --dport 53 -m owner --uid-owner 995 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -p tcp -m tcp ! --dport 53 -m owner ! --uid-owner 995 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 995 -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --gid-owner 995 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -p tcp -m tcp ! --dport 53 -m owner ! --gid-owner 995 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 995 -j RETURN
-A ISTIO_OUTPUT -d 192.168.0.2/32 -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 15053
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
COMMIT
# Completed on Fri Mar 12 16:36:39 2021
```

**Version**
1.9.0

**How was Istio installed?**
Istio Operator.
