### ISSUE TITLE
Authenticating & authorizing access to GKE services using Istio

### ISSUE THREAD

**Issue by rileyhun** [istio/istio#31443]
I just had a question about authenticating & authorizing access to GKE services using istio. This is the [documentation ](https://cloud.google.com/solutions/authorizing-access-to-cloud-run-on-gke-services-using-istio)that I've been following to protect my applications with istio proxy side-car. A few months ago, I was able to get this working for my Cloud Run on Anthos instance and I basically want to do the same thing for my generic non-cloud-run-on-anthos K8s cluster with Istio Gateway installed. I did try it out and it's not working & denying me access to my application when it should be. Here's an example of the `RequestAuthentication` & `Authorization Policy` files I'm using:

```
---
apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: istio-ingress-jwt
  namespace: seldon
spec:
  selector:
    matchLabels:
      seldon-app: iris-model-example
  jwtRules:
    - issuer: "https://accounts.google.com"
      jwksUri: "https://www.googleapis.com/oauth2/v3/certs"
      audiences:
        - "${PROJECT_ID}"
      fromHeaders:
        - name: Authorization
          prefix: "Bearer "
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: istio-invoker
  namespace: seldon
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        hosts:
        - '${IP_ADDRESS}'
    when:
    - key: request.auth.claims[aud]
      values:
      - 'http://${IP_ADDRESS}'
    - key: request.auth.claims[email]
      values:
      - "${SERVICE_ACCOUNT_EMAIL}"
    - key: request.auth.claims[iss]
      values:
      - https://accounts.google.com
  selector:
   matchLabels:
     seldon-app: iris-model-example
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
I expected to be denied access when making a request to the application. 

**How was Istio installed?**
1.7.7
