### ISSUE TITLE
ServiceEntry: It's not possible to have multiple ServiceEntry resources for the same `host` name but different `ports`

### ISSUE THREAD

**Issue by yskopets** [istio/istio#31483]
**Bug description**

* It's not possible to have multiple ServiceEntry resources for the same `host` name but different `ports` (see example YAML below)
* Such configuration
  * Is not invalid according to the docs
  * Is not rejected by Istio validating weebhooks
  * Is not warned about by `istioctl analyze`

Notice that on `Istio 1.7` the issue manifests itself in a more weird way:
* the issue is NOT reproducible when `ServiceEntry`(s) deployed into namespace  named `bookinfo` 
* the issue is reproducible when `ServiceEntry`(s) deployed into namespace with a different name

Which caused the confusion for us - so, is it a supported use case or not ?

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

* Either support this use case or add missing docs, validation, analyzer

**Steps to reproduce the bug**

* Install `Istio 1.9`
* Deploy `bookinfo` app into `example` namespace (we only need `Istio Proxy` somewhere)
* Deploy `WorkloadEntry`
  ```yaml
  apiVersion: networking.istio.io/v1beta1
  kind: WorkloadEntry
  metadata:
    name: example-vm
    namespace: example
  spec:
    address: 10.0.0.1
    labels:
      app1/version: v1
      app2/version: v2
    serviceAccount: default
  ``` 
* Deploy `ServiceEntry` for app 1
  ```yaml
  apiVersion: networking.istio.io/v1beta1
  kind: ServiceEntry
  metadata:
    name: app1
    namespace: example
  spec:
    hosts:
    - example.com
    location: MESH_INTERNAL
    ports:
    - name: http-app1
      number: 8081
      protocol: HTTP
    resolution: STATIC
    workloadSelector:
      labels:
        app1/version: v1
  ``` 
* Verify that `productpage` sidecar receives CDS and EDS of `app1`:
  ```shell
  curl -s localhost:15000/clusters | grep example.com
  ``` 
  ```shell
  outbound|8081||example.com::added_via_api::true
  outbound|8081||example.com::10.0.0.1:8081::cx_active::0
  ``` 
* Deploy `ServiceEntry` for app 2
  ```yaml
  apiVersion: networking.istio.io/v1beta1
  kind: ServiceEntry
  metadata:
    name: app2
    namespace: example
  spec:
    hosts:
    - example.com
    location: MESH_INTERNAL
    ports:
    - name: http-app2
      number: 8082
      protocol: HTTP
    resolution: STATIC
    workloadSelector:
      labels:
        app2/version: v2  
  ```
* Verify that `productpage` sidecar receives CDS and EDS of `app2` but EDS of `app1` is lost:
  ```shell
  curl -s localhost:15000/clusters | grep example.com
  ``` 
  ```shell
  outbound|8081||example.com::added_via_api::true
  # no EDS for `app1` anymore

  outbound|8082||example.com::added_via_api::true
  outbound|8082||example.com::10.0.0.1:8082::cx_active::0
  ```
* Delete `ServiceEntry` for app 2
* Verify that `productpage` sidecar still has CDS of `app1` but no `EDS`:
  ```shell
  curl -s localhost:15000/clusters | grep example.com
  ```
  ```shell
  outbound|8081||example.com::added_via_api::true
  # no EDS for `app1` anymore
  ```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

`1.9.1`

**How was Istio installed?**

```shell
istioctl install --set profile=demo -y
```

**Environment where the bug was observed (cloud vendor, OS, etc)**

`GKE`
