### ISSUE TITLE
[1.8.4] Certificate verification failure on multicluster with Istio mTLS

### ISSUE THREAD

**Issue by ghost** [istio/istio#31480]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
Running Istio on a replicated control plane setup (version **1.7.8**), cross-cluster communication (Cluster 1 [POD] -> Cluster 2 [Istio-IngressGateway] using `ISTIO_MUTUAL` works without any issue.

Simply doing an in-place upgrade (using Istio-operator) to version **1.8.4**, cross-cluster communication fails:
`upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED`

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
When doing an in-place upgrade on Istio (minor releases), expected cross-cluster communication to be backwards compatible.

**Steps to reproduce the bug**
Using Istio **1.7.x** on a Multicluster Replicated Control Plane setup, use `ISTIO_MUTUAL` for cross-cluster communication.

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: cluster-aware-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: ISTIO_MUTUAL
    hosts:
    - "*.local"
```

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: wildcard-local
  namespace: istio-system
spec:
  host: "*.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```

Test cross-cluster communication via `curl` pod:

```
curl -i -v foo.sample.svc.cluster.local:80/anything
> GET /anything HTTP/1.1
> User-Agent: curl/7.35.0
> Host: foo.sample.svc.cluster.local
> Accept: */*
>
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< server: envoy
server: envoy
< date: Mon, 15 Mar 2021 21:00:26 GMT
date: Mon, 15 Mar 2021 21:00:26 GMT
< content-type: application/json
content-type: application/json
< content-length: 2414
content-length: 2414
< access-control-allow-origin: *
access-control-allow-origin: *
< access-control-allow-credentials: true
access-control-allow-credentials: true
< x-envoy-upstream-service-time: 6
x-envoy-upstream-service-time: 6

<
{
  "args": {},
  "data": "",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "*/*",
    "Content-Length": "0",
    "Host": "foo.sample.svc.cluster.local",
    "User-Agent": "curl/7.35.0",
    "X-B3-Parentspanid": "f05675202aacbc6e",
    "X-B3-Sampled": "1",
    "X-B3-Spanid": "64c19e20bcc70c82",
    "X-B3-Traceid": "a4e0e66cbfe6aaa234b050a663ae6327",
    "X-Envoy-Attempt-Count": "1",
    "X-Envoy-Expected-Rq-Timeout-Ms": "20000",
    "X-Envoy-Internal": "true",
    "X-Forwarded-Client-Cert": "By=spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account;Hash=<hashvalue>;Cert=\"-----BEGIN%20CERTIFICATE-----<certificate-content>-----END%20CERTIFICATE-----%0A\";Subject=\"\";URI=spiffe://cluster.local/ns/sample/sa/default,By=spiffe://cluster.local/ns/sample/sa/default;Hash=<hashvalue>;Subject=\"\";URI=spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"
  },
  "json": null,
  "method": "GET",
  "url": "https://foo.sample.svc.cluster.local/anything"
}
```

Execute in-place upgrade to Istio **1.8.x** and re-run `curl` command:

```
curl -i -v foo.sample.svc.cluster.local:80/anything
> GET /anything HTTP/1.1
> User-Agent: curl/7.35.0
> Host: foo.sample.svc.cluster.local
> Accept: */*
>
< HTTP/1.1 503 Service Unavailable
HTTP/1.1 503 Service Unavailable
< content-length: 195
content-length: 195
< content-type: text/plain
content-type: text/plain
< date: Mon, 15 Mar 2021 21:26:49 GMT
date: Mon, 15 Mar 2021 21:26:49 GMT
< server: envoy
server: envoy

<
upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
istioctl version --remote
client version: 1.8.3
control plane version: 1.8.4
data plane version: 1.8.4 (6 proxies)
```

```
Client Version: v1.15.1
Server Version: v1.16.15-eks-ad4801
```

**How was Istio installed?**
Istio-operator - https://istio.io/v1.8/docs/setup/upgrade/in-place/

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by bianpengyuan** [comment]
Please provide client proxy config dump and ingress gateway config dump, and debug log if possible: https://github.com/istio/istio/wiki/Troubleshooting-Istio#sidecargateway-problems.

**Comment by robjnunes** [comment]
Hi @bianpengyuan. Attached ingress/proxy debug logs and config dumps.
[logs_configdump.zip](https://github.com/istio/istio/files/6147068/logs_configdump.zip)

**Comment by bianpengyuan** [comment]
Sorry for the delay. I am wondering how does this ever work at 1.7... As the client proxy is expecting the peer's identity to be `spiffe://cluster.local/ns/sample/sa/default` (i.e. mTLS should be terminated by the sample app proxy). With you configuration, the ingress is terminating mTLS, with identity `spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account`, so client side cert verification fails. Typically the gateway should be configured as a AUTO_PASSTHROUGH, instead of terminating TLS for cross cluster traffics.

Could you provide the same dump from those two proxies with 1.7?

**Comment by robjnunes** [comment]
I've got this approach working since 1.6.x.

The main reason I choose to use `ISTIO_MUTUAL` instead of `AUTO_PASSTHROUGH`, was regarding the support of canary deployments routing on a cross-cluster setup. So if Cluster 1 has `foo` and it's VirtualService with subsets `v1`/ weight 100% and `v2`/weight 0%, when initiating traffic from Cluster 2 to `foo` I would get traffic to either subsets, using `AUTO_PASSTHROUGH`.

Using `ISTIO_MUTUAL`, the ingress terminates mTLS from Cluster 2 (proxy) to Cluster 1 (ingress), but allows the ingress at Cluster 1 to use the setup of the VirtualService to route traffic accordingly to `foo` subsets. Please do let me know if there is an easier way to mitigate this concern, as I would love to use `AUTO_PASSTHROUGH` for cross-cluster comms.

Here's the configdump for the sidecar and ingress on Istio 1.7.8 - [proxy_1_7_8_configdump.zip](https://github.com/istio/istio/files/6175387/proxy_1_7_8_configdump.zip).

**Comment by bianpengyuan** [comment]
Could you provide more detail on did you set up multi cluster? i.e. How did you configure clusters in each cluster's mesh config, and how did you configure traffic from cluster 1 to route to cluster 2 ingress.

**Comment by robjnunes** [comment]
For both Cluster 1 and Cluster 2, the IstioOperator is used to install Istio.
Each cluster is using the exact same sample plugged-in CA certificates (so they share the same root CA) as described on https://istio.io/v1.7/docs/tasks/security/cert-management/plugin-ca-cert/.

The IstioOperator CR defines the mesh and network as follows:

Cluster 1
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: cluster1
spec:
  profile: default
  values:
    global:
      meshExpansion:
        enabled: false
        useILB: false
      meshNetworks:
        networkcluster1:
          endpoints:
          - fromRegistry: cluster1
          gateways:
          - port: 443
            registry_service_name: istio-ingressgateway.istio-system.svc.cluster.local
        networkcluster2:
          endpoints:
          - fromRegistry: cluster2
          gateways:
          - address: <cluster2-ingress-lb-external-ip>
            port: 443
      multiCluster:
        clusterName: cluster1
      network: networkcluster1

    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
```

Cluster 2
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: cluster2
spec:
  profile: default
  values:
    global:
      meshExpansion:
        enabled: false
        useILB: false
      meshNetworks:
        networkcluster2:
          endpoints:
          - fromRegistry: cluster2
          gateways:
          - port: 443
            registry_service_name: istio-ingressgateway.istio-system.svc.cluster.local
        networkcluster1:
          endpoints:
          - fromRegistry: cluster1
          gateways:
          - address: <cluster1-ingress-lb-external-ip>
            port: 443
      multiCluster:
        clusterName: cluster2
      network: networkcluster2

    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
```
Pod discovery between clusters is done by following instructions on https://istio.io/v1.7/docs/setup/install/multicluster/shared/#configure-cross-cluster-service-registries.

Both clusters have the following Destination Rule and Gateway on istio root namespace:

DestinationRule
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: cluster-aware-mtls
  namespace: istio-system
spec:
  host: "*.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```

Gateway
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: cluster-aware-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: ISTIO_MUTUAL
    hosts:
    - "*.local"
```
