### ISSUE TITLE
Additional perms required by prometheus in 0.5.0 error on RBAC cluster

### ISSUE THREAD

**Issue by Stono** [istio/istio#3149]
Installing istio `0.5.0` promethus addon on RBAC cluster results in lots of errors:

```
level=error ts=2018-02-03T19:00:57.667508689Z caller=main.go:211 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: Failed to list *v1.Node: nodes is forbidden: User \"system:serviceaccount:istio-system:default\" cannot list nodes at the cluster scope: Unknown user \"system:serviceaccount:istio-system:default\""
```

Probably want to include a role etc in the installation repo

**Comment by chrisgoffinet** [comment]
I had this same error, it was resolved by adding the service account role under `istio-system`, and modifying `install/kubernetes/addons/prometheus.yaml`

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: istio-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: istio-system
```

Then under `deployment` and `spec` section under `prometheus.yaml`

```
serviceAccountName: prometheus
```

**Comment by Stono** [comment]
Yeah that's what my PR does, however there's a random, unassociated test
failure so it isn't merged :-(

**Comment by salrashid123** [comment]
This doens't seem to be in the ```0.5.1``` release.  i downloaded it and inspected the generated prometheus.yaml file.

The on git [prometheus.yaml](https://github.com/istio/istio/blob/master/install/kubernetes/templates/addons/prometheus.yaml.tmpl#L244)  here should include the ```istio-system```, correct?

eg around line 245
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace:  istio-system
```

Should i reopen this or ref this in #3150
