### ISSUE TITLE
vs:httpwrite Request rewrite failed

### ISSUE THREAD

**Issue by tanjunchen** [istio/istio#31514]
1. deploy  sleep service and deployment
kubectl label ns default istio.io/rev=iop-1-8-1
kubectl apply -f sleep.yaml
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sleep
---
apiVersion: v1
kind: Service
metadata:
  name: sleep
  labels:
    app: sleep
    service: sleep
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: sleep
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      serviceAccountName: sleep
      containers:
      - name: sleep
        image: governmentpaas/curl-ssl
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /etc/sleep/tls
          name: secret-volume
      volumes:
      - name: secret-volume
        secret:
          secretName: sleep-secret
          optional: true
```
2. deploy httpbin service and deployment
kubectl apply -f httpbin.yaml
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
    service: httpbin
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      serviceAccountName: httpbin
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80
```
3. deploy vs and dr
kubectl apply -f dr-httpbin.yaml 
kubectl apply -f vs-httpbin.yaml
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: httpbin
spec:
  host: httpbin
  subsets:
  - name: v1
    labels:
       app: httpbin
       version: v1
```

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - httpbin
  http:
  - name: headers
    match:
    - uri:
        prefix: "/ip"
    - uri:
        prefix: "/get"
    rewrite:
      uri: "/headers"
    route:
    - destination:
        host: httpbin
        subset: v1
```
4. curl from sleep to httpbin
```
[root@dev-10 httpwrite]# kubectl get pods 
NAME                       READY   STATUS    RESTARTS   AGE
httpbin-779c54bf49-mfvwv   2/2     Running   0          17m
sleep-f8cbf5b76-kx6cx      2/2     Running   0          17m
[root@dev-10 httpwrite]# kubectl exec -it sleep-f8cbf5b76-kx6cx -c sleep -- curl httpbin:8000/ip
{
  "headers": {
    "Accept": "*/*", 
    "Content-Length": "0", 
    "Host": "httpbin:8000", 
    "User-Agent": "curl/7.69.1", 
    "X-B3-Parentspanid": "d07420d4f516aa05", 
    "X-B3-Sampled": "1", 
    "X-B3-Spanid": "8829e250f73d1eb4", 
    "X-B3-Traceid": "ca034544dd431a36d07420d4f516aa05", 
    "X-Envoy-Attempt-Count": "1", 
    "X-Envoy-Original-Path": "/ip", 
    "X-Forwarded-Client-Cert": "By=spiffe://cluster.local/ns/default/sa/httpbin;Hash=2cfe135fee2667bdd47c1d502982fd70adcbb9aab1e4473bf46c1a6895e2b649;Subject=\"\";URI=spiffe://cluster.local/ns/default/sa/sleep"
  }
}
[root@dev-10 httpwrite]# kubectl exec -it sleep-f8cbf5b76-kx6cx -c istio-proxy -- curl httpbin:8000/ip
{
  "origin": "127.0.0.1"
}
```
 5. logs
 ```
kubectl logs -f httpbin-779c54bf49-mfvwv -c istio-proxy
[2021-03-17T14:01:35.402Z] "GET /ip HTTP/1.1" 200 - "-" 0 588 9 8 "-" "curl/7.69.1" "0bf7f98c-57c9-9c0d-9928-e85e3105a920" "httpbin:8000" "127.0.0.1:80" inbound|80|| 127.0.0.1:54594 192.168.174.110:80 192.168.174.70:34054 outbound_.8000_.v1_.httpbin.default.svc.cluster.local default
[2021-03-17T14:01:47.756Z] "GET /ip HTTP/1.1" 200 - "-" 0 28 2 2 "-" "curl/7.58.0" "6fb87c9f-3db9-90d1-9237-e7c1493ffbb2" "httpbin:8000" "127.0.0.1:80" inbound|80|| 127.0.0.1:54762 192.168.174.110:80 192.168.174.70:40798 - default


 kubectl logs -f httpbin-779c54bf49-mfvwv -c  httpbin
[root@dev-10 ~]# kubectl logs -f httpbin-779c54bf49-mfvwv -c httpbin
[2021-03-17 13:43:36 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2021-03-17 13:43:36 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
[2021-03-17 13:43:36 +0000] [1] [INFO] Using worker: gevent
[2021-03-17 13:43:36 +0000] [9] [INFO] Booting worker with pid: 9

```

My understanding is that if you curl from sleep to httpbin, httpbin service is set to http rewrite, /get and /ip path will be rewritte to /headers. @howardjohn Could you help me resolve this question?
