### ISSUE TITLE
TLS egress with sidecar isn't working as described in official documentation. 

### ISSUE THREAD

**Issue by maheshmadpathi** [istio/istio#31513]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
I need to connect to an AWS ALB which listens on port 9443 from my application pod, I'm leveraging istio sidecar to do TLS origination, have mounted the cert into sidecar (`/etc/mycert`) with annotations and configured ServiceEntry, VirtualService and DestinationRule as per istio [official guide ](https://istio.io/v1.5/docs/tasks/traffic-management/egress/egress-tls-origination/).

I'm on istio version `1.5.5` with distroless images which EOL already but the upgrade plan is being worked on.

when I make a curl call to ALB from my application container over http and 9080 (application container intiates connection over 9080) I expect the VirtualService to convert the traffic to 9443 and apply DestinationRule to do TLS Origination with given cacert but its not happening at the moment and I get below messages in istio proxy log:

`"TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER"`

```
curl -iv http://myalb.mydomain:9080
*   Trying X.X.X.X...
* TCP_NODELAY set
* Connected to myalb.mydomain:9080 (X.X.X.X) port 9080 (#0)
> GET / HTTP/1.1
> Host: myalb.mydomain:9080
> User-Agent: curl/7.61.1
> Accept: */*
>
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer

```

`{"start_time":"2021-03-17T09:54:23.000Z","method":"HEAD","request_id":"e53c5719-f3fc-4fb6-a953-c13f66dbdac8","upstream_host":"X.X.X.X:9080","x_forwarded_for":"-","requested_server_name":"-","bytes_received":"0","istio_policy_status":"-","bytes_sent":"0","upstream_cluster":"outbound|9443||myalb.mydomain","downstream_remote_address":"X.X.X.X:52476","authority":"myalb.mydomain:9080","path":"/","protocol":"HTTP/1.1","upstream_service_time":"-","upstream_local_address":"-","duration":"226","upstream_transport_failure_reason":"TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER","route_name":"-","downstream_local_address":"X.X.X.X:9080","user_agent":"-","response_code":"503","response_flags":"UF,URX"}`

but when I do curl on 9443 directly then I get nothing in proxy logs:

```
https://myalb.mydomain:9443
*   Trying X.X.X.X...
* TCP_NODELAY set
* Connected to myalb.mydomain (X.X.X.X) port 9443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number
* Closing connection 0
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number

```
but when I change the mode in DestinationRule to DISABLE everything works fine also when I pass` --cacert` to https curl call then works fine as well. I'm not sure whether the DestinationRule has problem or the cert I'm using.

config:
``` yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: app-egress
  namespace: my-ns
spec:
  addresses:
  - X.X.X.X/23
  - Y.Y.Y.Y/23
  - A.A.A.A/23
  exportTo:
  - .
  hosts:
  - myalb.mydomain
  location: MESH_EXTERNAL
  ports:
  - name: https-port-for-tls-origination
    number: 9443
    protocol: HTTPS
  - name: http-port
    number: 9080
    protocol: HTTP
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: alb-dr
  namespace: my-ns
spec:
  exportTo:
  - .
  host: myalb.mydomain
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 9443
      tls:
        mode: SIMPLE
        caCertificates: /etc/mycert/cpcacerts.pem
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata: 
  name: alb-vs
  namespace: my-ns
spec:
  exportTo:
  - .
  hosts:
  - myalb.mydomain
  http:
  - match:
    - port: 9080
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: 5xx
    route:
    - destination:
        host: myalb.mydomain
        port:
          number: 9443
```

I have spent significant amount of time on this issue but couldn't quite get the issue, Appreciate any help. Thanks.

[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
The http curl call from application container should reach the endpoint with TLS traffic originated from Sidecar.

**Steps to reproduce the bug**
Follow exact steps mentioned in [guide](https://istio.io/v1.5/docs/tasks/traffic-management/egress/egress-tls-origination/)

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

istio:
client version: 1.4.2
citadel version: 1.5.5
egressgateway version: 1.5.5
galley version: 1.5.5
ingressgateway version: 1.5.5
pilot version: 1.5.5
policy version: 1.5.5
sidecar-injector version: 1.5.5
telemetry version: 1.5.5
data plane version: 1.5.5 (121 proxies)

K8s:
Client Version: v1.19.3
Server Version: v1.15.12-eks-31566f

Helm:
v3.0.1+g7c22ef9

**How was Istio installed?**
Helm charts

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS EKS, ALB, istio images are distroless.

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
