### ISSUE TITLE
Load-balancing pods across multiple networks

### ISSUE THREAD

**Issue by chaudyg** [istio/istio#31549]
**Describe the feature request**
When using Istio across [multiple networks](https://istio.io/latest/docs/setup/install/multicluster/multi-primary_multi-network/), requests are not load-balanced across remote pods.

The east-west gateway is configured with [AUTO_PASSTHROUGH](https://github.com/istio/istio/blob/0c0cf2d6fbca85beca0598de8817ff90107ddd0c/samples/multicluster/expose-services.yaml#L15) . A pod running in cluster 1 only sees a single endpoint for a service running in the remote cluster ( aka the east-west gateway IP). The east-west gateway is configured as a tcp_proxy with the envoy [sni_cluster_filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/sni_cluster_filter), making the sessions  sticky between a source pod in cluster 1 and a destination pod in cluster 2. HTTP requests are not load-balanced between remote pods.
![image](https://user-images.githubusercontent.com/7817963/111606250-50e78280-87d7-11eb-90bc-88f982eff794.png)

How could we ensure that the load-balancing algorithm chosen in the [DestinationRule](https://istio.io/latest/docs/reference/config/networking/destination-rule/#LoadBalancerSettings-SimpleLB) is being applied in a multi-network scenario?
  
**Describe alternatives you've considered**

I can only see 3 options:

1. The east-west gateway is converted into a L7 proxy instead of a TCP proxy. Requests from one client session would be load-balanced between pods in the destination cluster by the east-west gateway. However there is some work needed to ensure trusts/rbac is enforced properly: a the source pod should trust the remote gateway, destination pod trusts requests from the Gateway, and the gateway must check the source is trusted by the destination. This doesn't seem trivial 🤔 .

2. Keep the east-west gateway a tcp_proxy. But instead of exposing a single endpoint with the gateway IP to the client, add multiple endpoints for the same address. This would allow the client to load balance requests across multiple sessions. It would be an improvement to the current behaviour. But it's also a hack. Two sessions from the same client pod might still be routed to the same destination pod. 
```yaml
      cluster_name: foo
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: <GW_IP>
                port_value: <GW_PORT>
        - endpoint:
            address:
              socket_address:
                address: : <GW_IP>
                port_value:  <GW_PORT>
```
 3. Find a way to map each client endpoint to the correct destination endpoint. Maybe by adding the destination pod address and a metadata of the source endpoint and somehow propagating this information to gateway?
  

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
