### ISSUE TITLE
CONNECT - HTTP/1.1" 404 NR route_not_found 

### ISSUE THREAD

**Issue by semihural** [istio/istio#31557]
We've bunch of microservices running on-prem kubernetes cluster v.1.19 with Istio 1.9.0. Some of microservice needs to call external API through our company proxy.. What ı would like to do is implement a retry logic for external API call if the service returns `5xx`.

So simply,
ServiceA can access ServiceC only through ServiceB in our case.

ServiceA(Pod) -> ServiceB(company proxy) -> ServiceC (api.example.com)

If I removed the proxy-se serviceEntry, I did not have any connection issue but although the logs in  istio-proxy with 0 code likewise below..

```
Use 'kubectl describe pod/api-dev-7d65d79f8b-c9c55 -n hub-dev' to see all of the containers in this pod.
/usr/src/app $ https_proxy=$HTTPS_PROXY curl -I -L  https://api.example.com 2>/dev/null | head -n 1
HTTP/1.1 200 Connection established

$ kubectl logs -f api-dev-7d65d79f8b-c9c55 -n dev -c istio-proxy
[2021-03-16T09:31:06.620Z] "- - -" 0 - - - "-" 987 4733 43 - "-" "-" "-" "-" "53.xx.xxx.xx:3128" outbound|3128||security-proxy.net 10.6.21.236:40810 53.xx.xx.xx:3128 10.6.21.236:40808 - -

```
When I added ServiceEntry proxy-se then I received an 404 NR error where at least ı can see the proper final destination..

I just aware of that there is a similar issue closed but not sure whether Istio 1.9.0 is included with this.. Could you please help me how can I resolve this `?`
https://github.com/envoyproxy/envoy/issues/11308

```
Use 'kubectl describe pod/oneapihub-auth-dev-578977f56c-zxhs9 -n dev' to see all of the containers in this pod.
/usr/src/app $ https_proxy=$HTTPS_PROXY curl -I -L  https://api.example.com 2>/dev/null | head -n 1
HTTP/1.1 404 Not Found
```

```
 kubectl logs -f oneapihub-auth-dev-578977f56c-zxhs9 -n dev -c istio-proxy
[2021-03-18T17:30:18.377Z] "CONNECT - HTTP/1.1" 404 NR route_not_found - "-" 0 0 0 - "-" "curl/7.69.1" "c68b6253-32a4-4439-be3b-58df15ed64cc" "api.example.com:443" "-" - - 53.xx.xx.xx:3128 10.6.5.59:57164 -
``` 

I can able to see proxy whereas cant see the api.example.com
```
$ istioctl pc route oneapihub-auth-dev-578977f56c-zxhs9.dev
NAME                                                                        DOMAINS                                              MATCH                  VIRTUAL SERVICE
3128                                                                        security-proxy.net                                       /*                     proxy-vs.hub-dev
```

Here are the resources that I created 

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: proxy-se
  namespace: dev
spec:
  hosts:
  - security-proxy.net
  ports:
  - number: 3128
    name: http
    protocol: HTTP
  location: MESH_EXTERNAL
  resolution: NONE

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: proxy-vs
  namespace: dev
spec:
  hosts:
    - "security-proxy.net"
  http:
    - name: "proxy"
      match:
        - port: 3128
      route:
        - destination:
            host: "security-proxy.net"
            port:
              number: 3128
      timeout: 90s
      retries:
        retryOn: "5xx"
        attempts: 3
        perTryTimeout: 5s
---


apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: api.example.com
  namespace: dev
spec:
  hosts:
    - api.example.com
  ports:
    - number: 443
      name: https
      protocol: HTTPS
  resolution: NONE
  location: MESH_EXTERNAL
```

**Comment by bianpengyuan** [comment]
Looks like the listener only have route for `security-proxy.net` host but not `api.example.com`. You probably need to configure a VirtualService to add a route for `api.example.com`?

**Comment by semihural** [comment]
hi @bianpengyuan 
I just added VirtualService as a below but still get same error.. Could you please let me know whether if I have to change something or not?

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api.example.com
  namespace: hub-dev
spec:
  hosts:
    - "api.example.com"
  http:
    - name: "api.example.com"
      match:
        - port: 443
      route:
        - destination:
            host: "api.example.com"
            port:
              number: 443
      timeout: 90s
      retries:
        retryOn: "5xx"
        attempts: 3
        perTryTimeout: 5s
---

```
`[2021-03-20T14:04:52.890Z] "CONNECT - HTTP/1.1" 404 NR route_not_found - "-" 0 0 1 - "-" "curl/7.69.1" "f555031e-1c21-452f-90b2-74e39323641c" "api.example.comt:443" "-" - - 53.xx.xx.xx:3128 10.6.21.70:56214 - -`
