### ISSUE TITLE
VirtualService and DestinationRules aren't applying to requests from the same namespace

### ISSUE THREAD

**Issue by ten-chh** [istio/istio#31554]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
Given a `VirtualService` and `DestinationRule` set up to manage traffic based on HTTP method, requests from `namespace-a` where the `VirtualService` and `DestinationRule` resides are not managed based on the rules. Requests from other namespaces (e.g. `namespace-b`) are managed by http method as expected.

Requests from `namespace-a` are not segregated by HTTP method - requests are routed round robin without regard for the HTTP method.
Requests from `namespace-b` are routed according to the rules defined: GET requests go to "get" pods and PATCH|POST|PUT requests go to "crud" pods.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
All requests are managed by the HTTP method as defined in the VirtualService and DestinationRule regardless of which namespace where the requests are coming from.

**Steps to reproduce the bug**
VirtualService in namespace A (where the service is deployed)
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app: service-ns-a
    app.kubernetes.io/instance: service-ns-a
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: service-ns-a
    app.kubernetes.io/part-of: namespace-a
    app.kubernetes.io/version: v1.23.0-build.2
    domain: namespace-a
    environment: dv3
    helm.sh/chart: api-special-routing-v1.23.0-build.2
    version: v1.23.0-build.2
  name: service-ns-a-internal
  namespace: namespace-a
  resourceVersion: "83485700"
  selfLink: /apis/networking.istio.io/v1beta1/namespaces/namespace-a/virtualservices/service-ns-a-internal
  uid: bb338ebc-10d1-40e2-aeb5-728f206b3989
spec:
  exportTo:
  - '*'
  hosts:
  - service-ns-a.namespace-a.svc.cluster.local
  http:
  - match:
    - method:
        regex: (GET|HEAD|OPTIONS)
    name: service-ns-a-get-internal-route
    route:
    - destination:
        host: service-ns-a.namespace-a.svc.cluster.local
        subset: get
  - match:
    - method:
        regex: (POST|PATCH|PUT|DELETE)
    name: service-ns-a-crud-internal-route
    route:
    - destination:
        host: service-ns-a.namespace-a.svc.cluster.local
        subset: crud
```

DestinationRule in namespace A (where the service is deployed)
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  annotations:
    helm.fluxcd.io/antecedent: namespace-a:helmrelease/service-ns-a
  labels:
    app: service-ns-a
    app.kubernetes.io/instance: service-ns-a
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: service-ns-a
    app.kubernetes.io/part-of: namespace-a
    app.kubernetes.io/version: v1.23.0-build.2
    domain: namespace-a
    environment: dv3
    helm.sh/chart: api-special-routing-v1.23.0-build.2
    version: v1.23.0-build.2
  name: service-ns-a-default-destination-rule
  namespace: namespace-a
spec:
  host: service-ns-a.namespace-a.svc.cluster.local
  subsets:
  - labels:
      subsetTarget: get
    name: get
  - labels:
      subsetTarget: crud
    name: crud
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
    tls:
      mode: ISTIO_MUTUAL
```

Run curl requests (from k8s pods) to the internal k8s service endpoint from `namespace-a` (same NS as the service) and `namespace-b` (different namespace from where the service is deployed).
from `namespace-a`
```
curl http://service-ns-a.namespace-a.svc.cluster.local/info?query=same-ns-get-1
curl http://service-ns-a.namespace-a.svc.cluster.local/info?query=same

-ns-patch-1 -X PATCH
```

from `namespace-b`
```
curl http://service-ns-a.namespace-a.svc.cluster.local/info?query=diff-ns-get-1
curl http://service-ns-a.namespace-a.svc.cluster.local/info?query=diff-ns-patch-1 -X PATCH
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
istioctl version --remote
client version: 1.8.0
control plane version: 1.8.0
data plane version: 1.8.0 (82 proxies)

kubectl version --short
Client Version: v1.20.1
Server Version: v1.18.9-eks-d1db3c

helm version --short
v3.4.1+gc4e7485
```

**How was Istio installed?**
Helm chart

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS Elastic Kubernetes Service version 1.18

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
