### ISSUE TITLE
Istio ingress Gateway route traffic 443 to 80 at  AWS ELB level with patching 

### ISSUE THREAD

**Issue by vangahari** [istio/istio#31597]
Hi Team,
I am applying patch for Istio ingress gateway with AWS ACM certificate for ELB, Its applying properly but one thing doesn’t working.
 My goal is, AWS ELB and Istio gateway should use same ACM Certificate (AWS ACM), and whatever the traffic comes to 443 it should redirects to 80.
Whatever the request comes to ELB with 80 or 443, should forwards the traffic to Istio gateway, at Istio gateway SSL should terminate and traffic should go through plaintext (80).
After applying the patch, manually changing the Instance 80 port to 443 (31678) at ELB as below
<img width="1061" alt="Screenshot 2021-03-20 at 4 00 32 PM" src="https://user-images.githubusercontent.com/45491142/111866723-820db180-8995-11eb-9baf-47e1f7752438.png">

Istio version: 1.9
This is my gateway file
[gateway.txt](https://github.com/istio/istio/files/6175313/gateway.txt)

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  labels:
    app: ingressgateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - '*'

Following YAML File using for applying the patch for ELB with ACM

kubectl -n istio-system patch service istio-ingressgateway --patch "$(cat<<EOF
metadata: 
  annotations: 
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "4000"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "<ARN of the ACM Certificate>"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
       name: http
       number: 80
       protocol: HTTP
       targetPort: 80
       nodePort: 31687
    hosts:
    - ‘*’
  - port:
        name: https-443
        number: 443
        protocol: HTTP
        targetPort: 80
        nodePort: 31687
    hosts:
    - ‘*’
EOF
)"
[istio-acm-patch.txt](https://github.com/istio/istio/files/6175303/istio-acm-patch.txt)

**Comment by howardjohn** [comment]
The issue seems to be missing what is not working? One thing I noticed is the servic nodee port is not matching the UI

**Comment by vangahari** [comment]
> The issue seems to be missing what is not working? One thing I noticed is the servic nodee port is not matching the UI
Hi @howardjohn, I am using AWS EKS cluster to deploy My application,I have Installed Istio-1.9 on EKS cluster and deployed Istio Gateway on EKS cluster. 
Istio is Spinning up elb loadbalancer from the AWS, so I wanted to apply SSL certificate for ELB and Istio Gateway for SSL communication.
I used patching to apply SSL certificate for ELB, So its been applying SSL properly and its working fine, but for the ELB instance listner ports should be same for both 80 and 443. When 443 and 80 requests comes to ELB, both should allow and that requests should forward to same instance port at ELB as posted in the above picture. But the issue is its applying SSL certficate for ELB, same node port (listener port) is not applying, after applying the patch i am manually updating the port at ELB with 80 of listener port
Please see the patch yaml file and gateway yaml file posted above

Note: My goal is the patch should apply ACM Certificate as well as same Listener port for 80 and 443.

**Comment by howardjohn** [comment]
@vangahari if the issue is ELB port is not correct, please file a bug with AWS. Istio has no control over that.

**Comment by zenvdeluca** [comment]
It may be related to this other case here. https://stackoverflow.com/questions/66231268/istio-terminate-tls-at-aws-nlb/66898971#66898971


I'm trying to use NLB in front of my ingress gateways with ACM SSL certificates on AWS load balancer and it all works fine if I expose my ingress gateway on port 80, but then I have to call https://<loadbalancer>:80

The problem manifests when I switch the ingress gateway to port 443 maintaining the gateway protocol as plain "HTTP". Envoy no longer replies to plain text HTTP requests.

**Comment by zenvdeluca** [comment]
my current config, for reference: (tried all the combinations possible)

ingressGateways.k8s
```
          service:
            ports:
              - name: status-port
                port: 15021
                targetPort: 15021
              - name: http2
                port: 443
                targetPort: 8080
```

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: truth-service
spec:
  selector:
    istio: ingressgateway
    visibility: private
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTP
    hosts:
    - "truth-service.pod998.zdmesh.io"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: truth-service
spec:
  hosts:
  - truth-service.pod998.zdmesh.io
  gateways:
  - truth-service
  http:
  - route:
    - destination:
        host: truth-service.truth-service.svc.cluster.local
        port:
          number: 80
```
