### ISSUE TITLE
What is the role of the data packet containing the service IP

### ISSUE THREAD

**Issue by sunnoy** [istio/istio#31604]
# Deploy the yaml file：
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
        version: apache
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: apache
          image: httpd:2.4
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apache
spec:
  selector:
    app: apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http-apache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
        # traffic.sidecar.istio.io/includeInboundPorts: "*"
        # traffic.sidecar.istio.io/excludeInboundPorts: "1989"
    spec:

      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 1989
          volumeMounts:
            - name: config-vol
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: config-vol
          configMap:
            name: config-vol
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - protocol: TCP
      port: 1989
      targetPort: 1989
      name: tcp-nginx
      nodePort: 24000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-vol
data:
  apache.conf: |
    upstream apache{
        server apache;
    }

    server {
        listen       1989;
        server_name  lr.test.com;

        location / {
            proxy_http_version 1.1;
            proxy_redirect off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_pass http://apache;

            add_header X-Accel $server_name;
        }
    }

```

# test:

` X-Accel` not converted to lowercase

```bash
curl --location --request GET '172.25.129.57:24000' --header 'Hos: lr.test.com' -v
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 172.25.129.57...
* TCP_NODELAY set
* Connected to 172.25.129.57 (172.25.129.57) port 24000 (#0)
> GET / HTTP/1.1
> Host: 172.25.129.57:24000
> User-Agent: curl/7.64.1
> Accept: */*
> Hos: lr.test.com
>
< HTTP/1.1 200 OK
< Server: nginx/1.19.6
< Date: Mon, 22 Mar 2021 02:55:29 GMT
< Content-Type: text/html
< Content-Length: 45
< Connection: keep-alive
< last-modified: Mon, 11 Jun 2007 18:53:14 GMT
< etag: "2d-432a5e4a73a80"
< accept-ranges: bytes
< x-envoy-upstream-service-time: 1
< X-Accel: lr.test.com
<
<html><body><h1>It works!</h1></body></html>
* Connection #0 to host 172.25.129.57 left intact
* Closing connection 0
```
# version
client version: 1.9.1
control plane version: 1.9.1

# Packet capture
![image](https://user-images.githubusercontent.com/19342276/111936395-873b3f80-8b00-11eb-8744-7d3a1e645b39.png)

# confusing question

What is the role of the data packet containing the service IP <21.100.43.176>?
