### ISSUE TITLE
[Q] Increased network egress/outbound traffic

### ISSUE THREAD

**Issue by ritmas** [istio/istio#31619]
I have simple Kubernetes (k8s) Ingress solution running on regional [GKE](https://cloud.google.com/kubernetes-engine) cluster for months.

Recently, I've ran a test with Istio v1.9 (not [GKE add-on](https://cloud.google.com/istio/docs/istio-on-gke/overview#should_i_use), but [Helm charts](https://istio.io/latest/docs/setup/install/helm/)) and `VirtualService` solution in order to mirror 1% of production traffic to staging environment.

The concept is quite simple:
<img width="758" alt="istio-concept" src="https://user-images.githubusercontent.com/3692760/112013343-a4890180-8b32-11eb-94d4-aeb609378926.png">

Switching the traffic from Ingress (flow A) to Istio with mirroring feature (flow B) worked as expected, but what struck me the most that GKE network egress/outbound traffic has increased up to 6 times in TB, specifically `Network Inter Zone Egress` section.
Also double-checked on other app side metrics - the inbound traffic has not changed during these testing days, the tendency is constant.

![node_received_sent_bytes](https://user-images.githubusercontent.com/3692760/112015795-d00ceb80-8b34-11eb-8c49-23da86c7adb3.png)

Is this normal Istio behaviour or misconfiguration issue?
It seems like Istio doubles/triples/Xtriples traffic internally. Can this be tweaked?

Istio gateway:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: "project-gw"
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "*"
      tls:
        mode: SIMPLE
        credentialName: example.com-certs
```

Istio VirtualService (with 26 paths/ports):
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "project-vs"
spec:
  hosts:
    - "*"
  gateways:
    - "project-gw"
  http:
    - name: port-path1
      match:
        - uri:
            exact: /path1
      route:
        - destination: &httpRouteConfig
            host: "project-lb.default.svc.cluster.local"
            port:
              number: 18001
      mirror: &httpMirrorConfig
        <<: *httpRouteConfig
        host: "project-lb-stage.default.svc.cluster.local"
      mirrorPercentage: &httpMirrorPercentConfig
        value: 1.00

...

    - name: port-path26
      match:
        - uri:
            exact: /path26
      route:
        - destination:
            <<: *httpRouteConfig
            port:
              number: 18026
      mirror:
        <<: *httpMirrorConfig
        port:
          number: 18026
      mirrorPercentage:
        <<: *httpMirrorPercentConfig
        value: 1.00
```

k8s Service (production/staging looks the same):
```
apiVersion: v1
kind: Service
metadata:
  name: "project-lb"
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    ...
  ports:
    - name: port-path1
      port: 18001
      targetPort: 8001

...

    - name: port-path26
      port: 18026
      targetPort: 8026
```

**Comment by howardjohn** [comment]
So with the GKE ingress, my understand is with NEG and externalTrafficPolicy=Local the traffic is going directly from GCLB to the pod. With the alternative route, its going 
See https://www.asykim.com/blog/deep-dive-into-kubernetes-external-traffic-policies for lots of info here

GCLB ---> ingressgateway, which may require 2 hops if we hit the wrong node first
ingress -> app sidecar (if it has a sidecar) which should be 1 hop
app sidecar -> app which should be 1 hop

That gives 4 hops instead of 1. I am not sure if the metric counts localhost ones, if not that would bring it down to 3. I am also not certain my understanding of the GCLB + external traffic policy is correct.

**Comment by ritmas** [comment]
As for a reference let me just update on this - two important takeways here:

- ensure istio-ingressgateway is covering whole regional cluster zones with [PodAntiAffinity](PodAntiAffinity)
```yaml
podAntiAffinity:
  preferredDuringSchedulingIgnoredDuringExecution:
  - podAffinityTerm:
      labelSelector:
        matchExpressions:
        - key: istio
          operator: NotIn
          values:
          - ingressgateway
      topologyKey: topology.kubernetes.io/zone
    weight: 100
```
- [LocalityLoadBalancerSetting](https://istio.io/latest/docs/reference/config/networking/destination-rule/#LocalityLoadBalancerSetting) is not missing to ensure request result is being proxied back via the same zone as request was received, e.g.:
```yaml
trafficPolicy:
  loadBalancer:
    localityLbSetting:
      enabled: true
      distribute:
      - from: europe-west1/europe-west1-d/*
        to:
          europe-west1/europe-west1-d/*: 100
      - from: europe-west1/europe-west1-c/*
        to:
          europe-west1/europe-west1-c/*: 100
      - from: europe-west1/europe-west1-b/*
        to:
          europe-west1/europe-west1-b/*: 100
```
