### ISSUE TITLE
KubernetesResourcesSpec marshaling for volumes is wrong

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#31630]
What works:

```yaml
      k8s:
        volumes:
        - name: config-volume
          volumeSource:
            configMap:
              localObjectReference:
                name: istio
```

What *should* work:
```yaml
      k8s:
        volumes:
        - name: config-volume
          configMap:
            name: istio
```

cc @morvencao
