### ISSUE TITLE
Missing telemetry metrics on the egress gateway with reporter destination

### ISSUE THREAD

**Issue by gadiener** [istio/istio#31642]
**Bug description**

I’m facing an issue with the egress gateway telemetry, looking at the metrics I cannot find any entry with `reporter="destination"`, this attribute is used by Kiali to check the mutual TLS connection. Without that metric is not possible to have this information and the traffic is marked as not encrypted.

![Screenshot 2021-03-22 at 17 11 35](https://user-images.githubusercontent.com/8479033/112124746-fc6f4900-8bc2-11eb-8db9-5d5e19459ce6.png)

Querying in prometheus for `istio_tcp_sent_bytes_total{reporter="destination"}` and `istio_requests_total{reporter="destination"}` I cannot get any result.

Is this the proper way to check for `connection_security_policy="mutual_tls"`? Looking at the documentation (https://istio.io/latest/docs/concepts/observability/#service-level-metrics) seems to be correct.

Also with `istio_tcp_sent_bytes_total{reporter="destination"}` and `istio_requests_total{connection_security_policy="mutual_tls"}` I get `Empty query result`.

Slack discussion about Kiali: https://istio.slack.com/archives/CJVRXB09F/p1616429901055400
Slack discussion about Istio Telemetry: https://istio.slack.com/archives/C382V8Q92/p1616488553005300

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

With the mutual TLS configured, and the traffic going to the egress gateway I expect to see metrics in prometheus looking for `istio_requests_total{connection_security_policy="mutual_tls"}`

**Steps to reproduce the bug**

Following the steps on this links https://istio.io/latest/blog/2018/egress-mongo/#mutual-tls-between-the-sidecar-proxies-and-the-egress-gateway I'm able to replicate the problem.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```bash
$ istioctl version --remote
client version: 1.9.1
control plane version: 1.9.1
data plane version: 1.9.1 (12 proxies)
```

```bash
$ kubectl version --short
Client Version: v1.20.2
Server Version: v1.18.10
```

**How was Istio installed?**

Istio is installed using `IstioOperator`. This is n example of the configuration used:

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: "istio-control-plane"
  namespace: "istio-system"
spec:
  profile: "default"
  tag: "1.9.1"
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          serviceAnnotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    egressGateways:
      - name: istio-egressgateway
        enabled: true
        k8s:
          service:
            ports:
              - name: https
                port: 443
                protocol: TCP
                targetPort: 8443
              - name: tls
                port: 15443
                protocol: TCP
                targetPort: 15443
  meshConfig:
    accessLogFile: /dev/stdout
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
  values:
    global:
      defaultNodeSelector:
        beta.kubernetes.io/os: linux
```

**Environment where the bug was observed (cloud vendor, OS, etc)**

Azure Kubernetes Service
