### ISSUE TITLE
Invalid env var marshalling in k8s resource spec

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#31690]
```
$ ik manifest generate --set values.pilot.env.ISTIOD_CUSTOM_HOST=1.2.3.4 -f ex.yaml
Error: could not unmarshal merged YAML: json: cannot unmarshal object into Go value of type []json.RawMessage

YAML:
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: external-istiod
spec:
  components:
    base:
      enabled: true
    cni:
      enabled: false
    egressGateways:
    - enabled: false
      name: istio-egressgateway
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
    istiodRemote:
      enabled: false
    pilot:
      enabled: true
      k8s:
        env:
          name: ISTIOD_CUSTOM_HOST
          value: 1.2.3.4
```

IOP:
```
    apiVersion: install.istio.io/v1alpha1
    kind: IstioOperator
    metadata:
      namespace: external-istiod
    spec:
      components:
        pilot:
          enabled: true
          k8s:
            env:
```

if `env` is removed, this doesn't have issues

cc @morvencao

**Comment by morvencao** [comment]
The env var accepts slice type, so it should be:

```
      k8s:
        env:
        - name: ISTIOD_CUSTOM_HOST
          value: 1.2.3.4
```

instead of:
```
      k8s:
        env:
          name: ISTIOD_CUSTOM_HOST
          value: 1.2.3.4
```

**Comment by howardjohn** [comment]
@morvencao I did not write that yaml, `istioctl` did. I did `--set values.pilot.env.ISTIOD_CUSTOM_HOST=1.2.3.4`

**Comment by morvencao** [comment]
Which version are you using? I didn't see this error in 1.8.4, 1.9.2 and master if we just add `--set values.pilot.env.ISTIOD_CUSTOM_HOST=1.2.3.4`:
```
$ ./out/linux_amd64/istioctl manifest generate --set values.pilot.env.ISTIOD_CUSTOM_HOST=1.2.3.4 2>&1 1>/dev/null
```

**Comment by howardjohn** [comment]
you need the iop above AND the set flag

**Comment by litong01** [comment]
@howardjohn @morvencao feels that the command should have been something like this.

```
istioctl manifest generate --set values.pilot.env[0].ISTIOD_CUSTOM_HOST=1.2.3.4 -f ex.yaml
```
But it still gives errors, I think the overlay logic somehow not handling the list correctly, it always tries to use map[string]interface{} rather than []struct{ Name string, Value interface{}}.

**Comment by howardjohn** [comment]
values.pilot.env is a map, not a list

**Comment by litong01** [comment]
@howardjohn if you use one of the two, it will work.

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: external-istiod
spec:
  components:
    pilot:
      enabled: true
      k8s:
        env:
        - name: ISTIO_TEST
          value: whatever
```

also this one

```apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: external-istiod
spec:
  components:
    pilot:
      enabled: true
      k8s:
        env: []
```
