### ISSUE TITLE
Stackdriver tracing failing configuration upon start can block Istio-proxy

### ISSUE THREAD

**Issue by Minh-Ng** [istio/istio#31692]
**Bug description**
Follow up from https://github.com/istio/istio/issues/17357#issuecomment-806187596 (cc @douglas-reid thanks for the quick response). Stackdriver tracing can block istio-proxy from starting up. When tracing configuration fails, it causes istio-proxy to panic rather than swallowing the tracing configuration error and starting with limited functionality. We can see that zonal locality lookup failing (in my understanding used for platform recognition) does not block istio-proxy from bootstrapping. There are arguments to be made that tracing is non-essential functionality that istio-proxy can function without.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Istio-proxy successfully starts with limited functionality (tracing does not work)

**Steps to reproduce the bug**
1) Install Istio with v2 telemetry and stackdriver tracing enabled
2) Add a network policy to block egress to instance metadata server
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-metadata
  namespace: busybox
spec:
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 169.254.169.254/32
  podSelector:
    matchLabels:
      app: busybox
  policyTypes:
  - Egress
```
3) Launch an istio-injected pod selected by the NetworkPolicy and inspect istio-proxy logs to see that it fails
```
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "infinity"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Istio 1.8.3

**How was Istio installed?**
Istioctl install

**Environment where the bug was observed (cloud vendor, OS, etc)**
GKE, GCP Compute Engine
