### ISSUE TITLE
Gateway with wildcard host and cert-manager certificate gives 404

### ISSUE THREAD

**Issue by samene** [istio/istio#31701]
I have a gateway with a wildcard host entry like this

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: mycompany-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*.mycompany.com'    # --- wildcard
    port:
      name: https-portal
      number: 443
      protocol: HTTPS
    tls:
      credentialName: mycompany-istio-gateway
      mode: SIMPLE
```

and a virtual service

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ems-openam-vs
  namespace: mycompany-cloud
spec:
  gateways:
  - istio-system/mycompany-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /openam
    route:
    - destination:
        host: ems-openam
        port:
          number: 8080
```

I am using Cert-Manager to create a wildcard certificate

```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mycompany-istio-gateway
  namespace: istio-system
spec:
  duration: 2160h0m0s
  renewBefore: 360h0m0s
  subject:
    organizations:
    - mycompany
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - '*.mycompany.com'
  secretName: mycompany-istio-gateway
  issuerRef:
    name: mycompany-issuer
    kind: Issuer
```

The certificate is created successfully 

```
kubectl get certificate -n istio-system

NAMESPACE      NAME                      READY   SECRET                    AGE
istio-system   mycompany-istio-gateway   True    mycompany-istio-gateway   42m
```

Using keytool I verified the certificate in the secret

```
Owner: O=mycompany
Issuer: CN=MYORG CA
Serial number: b53d8a5f12b47af0821ca076b3ea680c
Valid from: Thu Mar 25 10:21:29 IST 2021 until: Wed Jun 23 10:21:29 IST 2021
Certificate fingerprints:
  MD5:  78:D7:C1:BA:21:C0:4D:A5:65:1A:C0:C4:05:BE:4B:69
  SHA1: 66:BD:9E:C8:7C:FD:E5:AD:EC:27:74:20:0B:D6:E3:19:E5:5C:7C:DF
  SHA256: 9B:C1:E4:B1:13:1A:98:F9:B2:6B:2D:A7:8B:D4:5E:10:CD:69:EA:BA:E0:DC:18:AE:48:FC:E7:E9:A2:5C:73:FE
Signature algorithm name: SHA256withRSA
Subject Public Key Algorithm: 2048-bit RSA key
Version: 3

Extensions:

#1: ObjectId: 2.5.29.19 Criticality=true
BasicConstraints:[
  CA:false
  PathLen: undefined
]

#2: ObjectId: 2.5.29.37 Criticality=false
ExtendedKeyUsages [
  serverAuth
  clientAuth
]

#3: ObjectId: 2.5.29.17 Criticality=false
SubjectAlternativeName [
  DNSName: *.mycompany.com
]
```

Now when I make a request to my app I get a 404.

```
curl -k -v https://app1.mycompany.com/openam
* About to connect() to app1.mycompany.com port 31390 (#0)
*   Trying 10.93.1.60...
* Connected to app1.mycompany.com (10.93.1.60) port 31390 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*    subject: O=mycompany
*    start date: Mar 25 04:51:29 2021 GMT
*    expire date: Jun 23 04:51:29 2021 GMT
*    common name: (nil)
*    issuer: CN=MYORG CA
> GET /openam HTTP/1.1
> User-Agent: curl/7.29.0
> Host: app1.mycompany.com
> Accept: */*
>
< HTTP/1.1 404 Not Found
< date: Thu, 25 Mar 2021 05:43:30 GMT
< server: istio-envoy
< content-length: 0
<
* Connection #0 to host app1.mycompany.com left intact
```

But when I change the hosts in the gateway to "*" it works properly

```
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'   # --- change to * works
    port:
      name: https-portal
      number: 443
      protocol: HTTPS
    tls:
      credentialName: mycompany-istio-gateways-mycompany-gateway
      mode: SIMPLE
```

There is no other gateway in the cluster in any namespace. If I explicitly add hosts then also it works

```
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - 'app1.mycompany.com'     # -- works
    - 'app2.mycompany.com'     # -- works
    port:
      name: https-portal
      number: 443
      protocol: HTTPS
    tls:
      credentialName: mycompany-istio-gateways-mycompany-gateway
      mode: SIMPLE
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

istioctl version --remote
client version: 1.9.1
control plane version: 1.9.1
data plane version: 1.9.1 (28 proxies)

kubectl version --short
Client Version: v1.18.8
Server Version: v1.18.16

**How was Istio installed?**
Istio Operator

**Comment by howardjohn** [comment]
Where does port 31390 come from? You may be hitting https://github.com/istio/istio/issues/25350, but I cannot tell if its happening since it looks like you are modifying `curls` output?

**Comment by samene** [comment]
31390 is the nodeport for 443

my curl request is ```https://app1.mycompany.com:31390/openam``` The 31390 is the part that got stripped off in trying to do a 'replace-all' some sensitive information.

**Comment by howardjohn** [comment]
Ok then you are impacted by https://github.com/istio/istio/issues/25350. Basically you cannot have port in Host header and use a wildcard match

**Comment by samene** [comment]
If I know the list of subdomains, can I have multiple certificates mapped to different hosts in the same gateway like this

```
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - 'app1.mycompany.com'     
    port:
      name: https-portal-app1
      number: 443
      protocol: HTTPS
    tls:
      credentialName: app1-secret
      mode: SIMPLE
  - hosts:
    - 'app2.mycompany.com'     
    port:
      name: https-portal-app2
      number: 443
      protocol: HTTPS
    tls:
      credentialName: app2-secret
      mode: SIMPLE
	  
```
