### ISSUE TITLE
defaultExportTo overrides exportTo set in resource level

### ISSUE THREAD

**Issue by thorion3006** [istio/istio#31708]
**Bug description**
defaultExportTo set during mesh install for virtual services, destination rules or service entry takes precedence over ones set per service definition.

[ ] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
`exportTo` option set for a virtual-service/destination-rule should override global option for that service

**Steps to reproduce the bug**
gateway:
```yaml
kind: Gateway
apiVersion: networking.istio.io/v1beta1
metadata:
  name: devops-ingressgateway
  namespace: istio-system
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  servers:
    - hosts:
        - devops.example.com
      port:
        name: http2-devops
        number: 80
        protocol: HTTP2
      tls:
        httpsRedirect: true
    - hosts:
        - devops.example.com
      port:
        name: https-devops
        number: 443
        protocol: HTTPS
      tls:
        credentialName: devops-tls
        mode: SIMPLE

```

virtual service:
```yaml
---
kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: rabbitmq-virtual-service
  namespace: resources
spec:
  gateways:
    - istio-system/devops-ingressgateway
    - mesh
  hosts:
    - devops.example.com
    - rabbitmq.resources.svc.cluster.local
    - rabbitmq-nodes.resources.svc.cluster.local
  http:
    - match:
        - uri:
            prefix: '/rabbitmq'
          gateways:
            - istio-system/devops-ingressgateway
            - mesh
      route:
        - destination:
            host: rabbitmq.resources.svc.cluster.local
            port:
              number: 15672
          weight: 100
  tcp:
    - match:
        - port: 5672
          gateways:
            - mesh
      route:
        - destination:
            host: rabbitmq.resources.svc.cluster.local
            port:
              number: 5672
          weight: 100
    - match:
        - port: 4369
          gateways:
            - mesh
      route:
        - destination:
            host: rabbitmq-nodes.resources.svc.cluster.local
            port:
              number: 4369
          weight: 100
    - match:
        - port: 25672
          gateways:
            - mesh
      route:
        - destination:
            host: rabbitmq-nodes.resources.svc.cluster.local
            port:
              number: 25672
          weight: 100
  exportTo:
    - '*'

```

destination rule:
```yaml
---
kind: DestinationRule
apiVersion: networking.istio.io/v1beta1
metadata:
  name: rabbitmq-destination-rule
  namespace: resources
spec:
  host: rabbitmq.resources.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
  exportTo:
    - '*'

```

When I try to access https://devops.example.com/rabbitmq/ envoy returns 503 error

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
$ istioctl version --remote
> client version: 1.9.1
> control plane version: 1.9.1
> data plane version: 1.9.1 (8 proxies)

$ kubectl version --short
> Client Version: v1.20.4-dirty
> Server Version: v1.19.7
```
**How was Istio installed?**
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  revision: 1-9-1
  tag: 1.9.1-distroless
  components:
    egressGateways:
      - name: istio-egressgateway
        enabled: true
  meshConfig:
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    connectTimeout: 5s
    protocolDetectionTimeout: 1s
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: 'true'
        ISTIO_META_DNS_AUTO_ALLOCATE: 'true'
      proxyStatsMatcher:
        inclusionPrefixes:
          - downstream_rq_active
    defaultServiceExportTo:
      - '.'
    defaultVirtualServiceExportTo:
      - '.'
    defaultDestinationRuleExportTo:
      - '.'
    enableAutoMtls: true
    enableTracing: false
    h2UpgradePolicy: UPGRADE
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
  values:
    global:
      configValidation: true
      logAsJson: true
      logging:
        level: 'default:info'
    pilot:
      traceSampling: 0.0
    sidecarInjectorWebhook:
      useLegacySelectors: false
```
**Environment where the bug was observed (cloud vendor, OS, etc)**
Azure AKS
