### ISSUE TITLE
numTrustedProxies not works as expected

### ISSUE THREAD

**Issue by vsychov** [istio/istio#31704]
Hello,

**Bug description**
I trying implement istio ingress gateway in next schema:
`Client <-> CloudFlare <-> LoadBalancer <-(proxy protocol)-> Ingress gateway <-> VirtualService <-> POD`

As a `POD` I use instance of [mendhak/http-https-echo](https://github.com/mendhak/docker-http-https-echo).

Ingress gateway config:
```yaml
ingressGateways:
  - enabled: true
     name: custom-ingress
     namespace: custom-namespace
```

and mesh config:
```yaml
meshConfig:
  defaultConfig:
    gatewayTopology:
      numTrustedProxies: 2
```

Also I added envoy filter for proxy-protocol:
```yaml
kind: EnvoyFilter
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: proxy-protocol
  namespace: istio-system
spec:
  configPatches:
    - applyTo: LISTENER
      patch:
        operation: MERGE
        value:
          listener_filters:
            - name: envoy.filters.listener.proxy_protocol
            - name: envoy.filters.listener.tls_inspector
  workloadSelector:
    labels:
      istio: ingressgateway
```

But POD receive headers:
```
"x-forwarded-for": "<ClientIp>,<CloudflareIp>"
"x-envoy-external-address": "<CloudflareIp>"
```

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
```
"x-envoy-external-address": "<ClientIp>"
```

**Steps to reproduce the bug**

**Version**
Istio:
```
client version: 1.9.1
control plane version: 1.8.4
data plane version: 1.8.4 (15 proxies)
```

K8S:
```
Client Version: v1.18.15
Server Version: v1.18.10
```

**How was Istio installed?**
I have setup istio via operator.
