### ISSUE TITLE
503 UH error on load testing

### ISSUE THREAD

**Issue by sesha3** [istio/istio#31728]
**Bug description**
I am facing 503 UH error from istio gateway for more than half of the total request made while load testing our application in jmeter.

[ ] Docs
[ ] Installation
[x] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x] Test and Release
[x] User Experience
[x] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Istio should not return 503 UH errors for requests.

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

istioctl version:
client version: 1.7.3
control plane version: 1.7.3
data plane version: 1.7.3 (8 proxies)

kubectl version:
Client Version: v1.19.1
Server Version: v1.18.14

**How was Istio installed?**
By following the below guide.
https://docs.microsoft.com/en-us/azure/aks/servicemesh-istio-install?pivots=client-operating-system-linux 

**Environment where the bug was observed (cloud vendor, OS, etc)**
Azure Kubernetes cluster (AKS)

## Prometheus details
![image](https://user-images.githubusercontent.com/11641910/112634526-b800d900-8e60-11eb-97be-8974842c8460.png)

>istio_requests_total
{
app="istio-ingressgateway",
chart="gateways",
connection_security_policy="unknown",
destination_app="unknown",
destination_canonical_revision="latest",
destination_canonical_service="unknown",
destination_principal="unknown",
destination_service="bi-dataservice-service.default.svc.cluster.local",
destination_service_name="bi-dataservice-service.default.svc.cluster.local",
destination_service_namespace="unknown",
destination_version="unknown",
destination_workload="unknown",
destination_workload_namespace="unknown",
heritage="Tiller",
instance="10.244.0.89:15090",
istio="ingressgateway",
job="kubernetes-pods",
kubernetes_namespace="istio-system",
kubernetes_pod_name="istio-ingressgateway-59cf75bf7-k55k9",
pod_template_hash="59cf75bf7",
release="istio",
reporter="source",
request_protocol="http",
response_code="503",
response_flags="UH",
service_istio_io_canonical_name="istio-ingressgateway",
service_istio_io_canonical_revision="latest",
source_app="istio-ingressgateway",
source_canonical_revision="latest",
source_canonical_service="istio-ingressgateway",
source_principal="unknown",
source_version="unknown",
source_workload="istio-ingressgateway",
source_workload_namespace="istio-system"
}

## Istio ingress gateway pod's trace logs

> 2021-03-25T12:32:56.740779Z	trace	envoy http	[C5505][S4414120366095176296] decode headers called: filter=0x5581d81ef740 status=0
2021-03-25T12:32:56.740782Z	trace	envoy http	[C5505][S4414120366095176296] decode headers called: filter=0x5581d75661e0 status=0
2021-03-25T12:32:56.740785Z	trace	envoy http	[C5505][S4414120366095176296] decode headers called: filter=0x5581d7d09500 status=0
2021-03-25T12:32:56.740787Z	trace	envoy http	[C5505][S4414120366095176296] decode headers called: filter=0x5581d9152ea0 status=0
2021-03-25T12:32:56.740790Z	debug	envoy router	[C5505][S4414120366095176296] cluster 'outbound|6007||bi-dataservice-service.default.svc.cluster.local' match for URL '/bi/designer/v1.0/design/loaddashboard/'
2021-03-25T12:32:56.740795Z	debug	envoy upstream	no healthy host for HTTP connection pool
2021-03-25T12:32:56.740807Z	debug	envoy http	[C5505][S4414120366095176296] Sending local reply with details no_healthy_upstream
2021-03-25T12:32:56.740811Z	trace	envoy http	[C5505][S4414120366095176296] encode headers called: filter=0x5581d7e91360 status=0
2021-03-25T12:32:56.740812Z	trace	envoy http	[C5505][S4414120366095176296] encode headers called: filter=0x5581d6c070e0 status=0
2021-03-25T12:32:56.740814Z	trace	envoy http	[C5505][S4414120366095176296] encode headers called: filter=0x5581d8068e10 status=0
2021-03-25T12:32:56.740817Z	trace	envoy http	[C5505][S4414120366095176296] encode headers called: filter=0x5581d72b9400 status=0
2021-03-25T12:32:56.740824Z	debug	envoy http	[C5505][S4414120366095176296] encoding headers via codec (end_stream=false):
':status', '503'
'content-length', '19'
'content-type', 'text/plain'
'date', 'Thu, 25 Mar 2021 12:32:56 GMT'
'server', 'istio-envoy'
'connection', 'close'

My Kubernetes deployment looks like the following sample.
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: myapp
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 750Mi
        readinessProbe:
          httpGet:
            path: /health-check
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - mountPath: /mydata
          name: myvolume
      volumes:
      - name: myvolume
        persistentVolumeClaim:
          claimName: myvolume-claim
          readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service  
  labels:
    app: myapp
spec:
  type: NodePort
  ports:
  - name: myapp-port
    port: 6007
    targetPort: 80
    protocol: TCP
  selector:
    app: myapp
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: myapp-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: true
    hosts:
    - myapp.com
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: myapp-tls
    hosts:
    - myapp.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: boldbi-virtual-service
spec:
  hosts:
  - myapp.com
  gateways:
  - boldbi-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 6007
        host: myapp-service
```
