### ISSUE TITLE
Support IngressClass ingressclass.kubernetes.io/is-default-class: 'true'

### ISSUE THREAD

**Issue by sathieu** [istio/istio#31720]
**Describe the feature request**

[IngressClass](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class) can have an annotation to [be default](https://kubernetes.io/docs/concepts/services-networking/ingress/#default-ingress-class).

With the following:

```yaml
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: istio
  annotations:
    ingressclass.kubernetes.io/is-default-class: 'true' # <------ HERE
spec:
  controller: istio.io/ingress-controller
```

and if I create an ingress without `ingressClassName: istio`, it is not associated with this class.

**Describe alternatives you've considered**

[MeshConfig](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig) has an `ingressControllerMode`, I've used this as workaround:

```shell
istioctl install --set meshConfig.ingressControllerMode=DEFAULT
```

**Affected product area (please put an X in all that apply)**

[x] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
