### ISSUE TITLE
Istio mounted certificate permission issue

### ISSUE THREAD

**Issue by Stono** [istio/istio#31726]
**Bug description**
This appears to have broken since 1.9, but i'm unsure why.  We're using the common method (https://karlstoney.com/2020/10/15/istio-upgrades-prometheus-sds/) to mount istio certificates for prometheus to use.

eg:
```
        proxy.istio.io/config: |
          proxyMetadata:
            OUTPUT_CERTS: /etc/istio-output-certs
        sidecar.istio.io/userVolume: '[{"name": "istio-certs", "emptyDir": {"medium":"Memory"}}]'
        sidecar.istio.io/userVolumeMount: '[{"name": "istio-certs", "mountPath": "/etc/istio-output-certs"}]'
 ```
 
 The podspec has:
 ```
       securityContext:
        fsGroup: 65534
        runAsUser: 65534
 ```
 
 Yet it appears the certificates are owned by `1337`:
 ```
/prometheus $ ls -lah /etc/istio-output-certs/
total 16K
drwxrwsrwt    2 root     1337         100 Mar 26 11:33 .
drwxr-xr-x    1 root     root        4.0K Mar 26 11:33 ..
-rw-------    1 1337     1337        2.2K Mar 26 11:33 cert-chain.pem
-rw-------    1 1337     1337        1.6K Mar 26 11:33 key.pem
-rw-------    1 1337     1337        1.0K Mar 26 11:33 root-cert.pem
```

Is istiod chowning these certs to 1337 and chmodding to 0600?

I could add another init container to fix the perms but would istiod just change them back?

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
