### ISSUE TITLE
istio 1.9.2 spec.values.global.multiCluster.enabled=true isn't rendering any multicluster configuration 

### ISSUE THREAD

**Issue by zenvdeluca** [istio/istio#31736]
**Bug description**
When upgrading from 1.9.1 to 1.9.2 the multicluster configuration for my replicated control-planes is being removed, even being explicitly enabled in the istio operator config.

my istio-operator config includes:

```spec:
  values:
    multiCluster:
        enabled: true
        clusterName: "myawesomecluster"
        globalDomainSuffix: "myawesomecluster.mymesh.com"
        includeEnvoyFilter: true
```

when rendering the config template using istio-1.9.2 and comparing it with my 1.9.1-running-config, I see the multicluster related objects are not being rendered in 1.9.2 (DestinationRule, EnvoyFilter, Gateway)  

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[X] Upgrade

**Expected behavior**

below is the diff from 1.9.1 and 1.9.2 showing the removals. When multiCluster=enabled the below configuration should continue to be rendered 

```
-kind: DestinationRule
-metadata:
-  labels:
-    app: istio-ingressgateway
-    istio: ingressgateway
-    release: istio
-    visibility: private
-  name: istio-multicluster-ingressgateway
-  namespace: istio-system
-spec:
-  host: '*.mymesh.com'
-  trafficPolicy:
-    tls:
-      mode: ISTIO_MUTUAL
```

```
-apiVersion: networking.istio.io/v1alpha3
-kind: EnvoyFilter
-metadata:
-  name: istio-multicluster-ingressgateway
-  namespace: istio-system
-  labels:
-    app: istio-ingressgateway
-    istio: ingressgateway
-    visibility: private
-    release: istio
-spec:
-  workloadSelector:
-    labels:
-      istio: ingressgateway
-  configPatches:
-  - applyTo: NETWORK_FILTER
-    match:
-      context: GATEWAY
-      listener:
-        portNumber: 15443
-        filterChain:
-          filter:
-            name: "envoy.filters.network.sni_cluster"
-    patch:
-      operation: INSERT_AFTER
-      value:
-        name: "envoy.filters.network.tcp_cluster_rewrite"
-        typed_config:
-          "@type": "type.googleapis.com/istio.envoy.config.filter.network.tcp_cluster_rewrite.v2alpha1.TcpClusterRewrite"
-          cluster_pattern: "\\.myawesomecluster.mymesh.com$"
-          cluster_replacement: ".svc.cluster.local"
```

```
-apiVersion: networking.istio.io/v1alpha3
-kind: Gateway
-metadata:
-  name: istio-multicluster-ingressgateway
-  namespace: istio-system
-  labels:
-    app: istio-ingressgateway
-    istio: ingressgateway
-    visibility: private
-    release: istio
-    istio.io/rev: default
-    install.operator.istio.io/owning-resource: unknown
-    operator.istio.io/component: "IngressGateways"
-spec:
-  selector:
-    istio: ingressgateway
-  servers:
-  - hosts:
-    - "*.myawesomecluster.mymesh.com"
-    port:
-      name: tls
-      number: 15443
-      protocol: TLS
-    tls:
-      mode: AUTO_PASSTHROUGH
----
````

**Steps to reproduce the bug**
Enable multiCluster under spec.values.global using istio-1.9.2 isn't producing the expected configuration  

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

istio 1.9.2
helm v3.5.3+g041ce5a

**How was Istio installed?**
istio-operator

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS/EKS Cluster -- but not relevant to this case.

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by zenvdeluca** [comment]
seems like has to do with the new gateway templates, haven't figured it out how to use it yet tho

https://github.com/istio/istio/compare/1.9.1...1.9.2#diff-c14fe05b4227a3c8a0310a2c7fc92e0e7ef1630c367b8ec8259f27b5ab0b7256R123

**Comment by zenvdeluca** [comment]
reopening as even after adding 
```
values:
    gateways:
      istio-ingressgateway:
        injectionTemplate: gateway
```

to the operator config, the multiCluster configuration is never rendered. 

spec.components looks like this:
```
ingressGateways:
      - name: istio-ingressgateway
        namespace: istio-gateways
        enabled: true
        k8s:
          env:
            # sni-dnat adds the clusters required for AUTO_PASSTHROUGH mode
            - name: ISTIO_META_ROUTER_MODE
              value: "sni-dnat"
          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-internal: "true"
```


referenced from:
