### ISSUE TITLE
Perform mutual TLS origination without an egress gateway

### ISSUE THREAD

**Issue by zhengqisong** [istio/istio#31738]
**Bug description**
istio-1.8.3 The credentialName unable to work in DestinationRule.

service contrainer--http-->pod sidcar-------https---->External Services(nginx)

curl http://httpbin.example.com/headers -v
External Services(nginx) response message
```
<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx</center>
</body>
</html>
```
config yaml
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
   name: httpbin-ext
spec:
  exportTo:
  - "."
  hosts:
  - httpbin.example.com
  ports:
  - number: 443
  name: tls
  protocol: tls
  location: MESH_EXTERNAL
  resolution: STATIC
  endpoints:
  - address: 10.122.47.131
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: httpbin-ext-dr
spec:
  host: httpbin.example.com
  exportTo:
  - "."
  trafficPolicy:
    tls:
      mode: MUTUAL
      credentialName: httpbin-credential
      sni: httpbin.example.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-vs
spec:
  gateways:
  - mesh
  hosts:
  - httpbin.example.com
  exportTo:
  - "."
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: httpbin.example.com
        port:
          number: 443

```

[ ] Docs
[ ] Installation
[ *] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade
