### ISSUE TITLE
[Istio Sidecar] Reset by peer when connecting to external service

### ISSUE THREAD

**Issue by ichasco-heytrade** [istio/istio#31748]
**Bug description**

When deploying a service whitch connects to external service in this case is a grafana service and connects to postgresql RDS. Gives an error.

```
grafana-f9f4447c4-xd4xp istio-proxy [2021-03-28T14:28:33.373Z] "- - -" 0 UH - - "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.11.30.83:5432 10.11.10.97:54384 - -
```

I have added an external service also to try if with this works:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: postgresql-external-devops
  namespace: istio-system
spec:
  hosts:
    - postgresql.devops.example.com
  location: MESH_EXTERNAL
  ports:
    - number: 5432
      name: tcp-postgresql-devops
      protocol: TCP
  resolution: DNS

```

And fails. If I disable the sidecar, it works.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Permit connection

**Steps to reproduce the bug**

**Version**

istio:
```
client version: 1.9.2
control plane version: 1.9.2
data plane version: 1.9.2 (4 proxies), 1.9.1 (56 proxies)
```

Kubectl
```
Client Version: v1.20.2
Server Version: v1.19.6-eks-49a6c0
```

**How was Istio installed?**

with istioctl
