### ISSUE TITLE
Helm charts ignores nodeSelector set

### ISSUE THREAD

**Issue by setevoy2** [istio/istio#31759]
**Bug description**

When deploying Istio with Helm - it ignores both `nodeSelector` and/or `defaultNodeSelector`.

Example using Ansible Helm plugin:

```
- name: "Install Istio Base to the istio-system namespace"
  community.kubernetes.helm:
    kubeconfig: "{{ kube_config_path }}"
    name: "istio-base"
    chart_ref: "istio-1.9.1/manifests/charts/base"
    release_namespace: "istio-system"
    create_namespace: true
    values:
      global:
        istiod:
          enableAnalysis: false
        defaultNodeSelector: 
          role: "common-workers"
```

Or:

```
- name: "Install Istio Ingress Gateway to the istio-system namespace"
  community.kubernetes.helm:
    kubeconfig: "{{ kube_config_path }}"
    name: "istio-ingress"
    chart_ref: "istio-1.9.1/manifests/charts/gateways/istio-ingress"
    release_namespace: "istio-system"
    create_namespace: true
    values:
      gateways:
        istio-ingressgateway:
          serviceAnnotations:
            alb.ingress.kubernetes.io/healthcheck-path: /healthz/ready
            alb.ingress.kubernetes.io/healthcheck-port: "30218"
          type: "NodePort"
          nodeSelector:
            role: "common-workers"
```

Will result in both Deployments without `nodeSelector`.

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Istio's Deployments must have `nodeSelector` added.

**Steps to reproduce the bug**

1. add a `nodeSelector` with any label
2. install an Istio component
3. check with `kubectl -n istio-system get deploy istiod -o yaml` - no `nodeSelector` created

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
$ istioctl version --remote
client version: 1.9.1
control plane version: 1.9.1
data plane version: 1.9.1 (3 proxies)
```

**How was Istio installed?**

```
$ helm upgrade --install istiod manifests/charts/istio-control/istio-discovery -n istio-system --set pilot.nodeSelector."role=common-workers"
```

**Environment where the bug was observed (cloud vendor, OS, etc)**

AWS EKS
