### ISSUE TITLE
Kubernetes Ingress connection refused

### ISSUE THREAD

**Issue by victor-amaris** [istio/istio#31750]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
I set up Istion on GKE using Kubernetes Ingress mode (https://istio.io/latest/docs/tasks/traffic-management/ingress/kubernetes-ingress/). However, I cannot access from outside (Error: connection refused).

**Affected product area (please put an X in all that apply)**

[ ] Docs
[] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[x] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
Should be able to access from outside

**Steps to reproduce the bug**
+Step 1:  Enable Istio on GKE
+Step 2: Setup Istio with below configs: 
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: in-keycloak
                port:
                  number: 8080
```

```
apiVersion: v1
kind: Service
metadata:
  name: in-keycloak
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: keycloak
  type: ClusterIP
```
+ Step 3: Access using curl using the external ip on port 80: curl external_ip:80 

`kubectl get svc -n istio-system | grep ingressgateway`

> istio-ingressgateway     LoadBalancer   10.48.11.240   35.222.111.100   15020:30115/TCP,80:31420/TCP,443:32019/TCP,31400:31267/TCP,15029:30180/TCP,15030:31055/TCP,15031:32226/TCP,15032:30437/TCP,15443:31792/TCP   41h

`curl 35.222.111.100`

> curl: (7) Failed to connect to 35.222.111.100 port 80: Connection refused

==> Error: Connection Refused

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

`istioctl version --remote`
> client version: 1.9.1
> control plane version: 1.6.14-gke.0-8c74bce5a2449be969f3f5ae4a0876cb4af50dbf
> data plane version: 1.6.14-gke.0 (1 proxies)

`kubectl version --short`
> Client Version: v1.19.7
> Server Version: v1.19.8-gke.1000

**How was Istio installed?**
Just enabled it from GKE dashboard

**Environment where the bug was observed (cloud vendor, OS, etc)**
cloud vendor: GKE

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
