### ISSUE TITLE
Exposing a new service(in multi primary setup) in the same namespace is not resolvable across clusters.

### ISSUE THREAD

**Issue by irajdeep** [istio/istio#31760]
**Bug description**
I have `multi-primary-cluster` set up on the same network based on these [instructions](https://istio.io/latest/docs/setup/install/multicluster/multi-primary/). Cross cluster connectivity is working as expected as mentioned in these [verification docs](https://istio.io/latest/docs/setup/install/multicluster/verify/).  But exposing a new service in the same (`sample`) namespace(in cluster2) is not getting resolved from cluster1.

[x] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
The new service deployed in cluster 2 would be discoverable from the pods deployed in cluster 1.

**Steps to reproduce the bug**
i. Follow the [multi primary installation docs](https://istio.io/latest/docs/setup/install/multicluster/multi-primary/) to install istio in multi-cluster setup.
ii. Verify the setup is working as per this [verification docs](https://istio.io/latest/docs/setup/install/multicluster/verify/). 
iii. Deploy a different `service` and `pod` in the same `sample` namespace in cluster 2. Spec as below.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: hellokube
  labels:
    app: hellokube
    service: hellokube
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: hellokube
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellokube-v1
  labels:
    app: hellokube
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellokube
      version: v1
  template:
    metadata:
      labels:
        app: hellokube
        version: v1
    spec:
      containers:
      - name: hellokube
        image: docker.io/istio/examples-helloworld-v1
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
```
iv. Exec into a pod in cluster1 (in this case I exec"ed" into the sleep pod in sample namespace as per verification docs) and tried to run `curl hellokube.sample:5000/hello` 
This results in an error `curl: (6) Could not resolve host: hellokube.sample`

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
istioctl version
client version: 1.9.1
control plane version: 1.9.1
data plane version: 1.9.1 (5 proxies)
```

**How was Istio installed?**
https://istio.io/latest/docs/setup/install/multicluster/multi-primary/

**Environment where the bug was observed (cloud vendor, OS, etc)**
Deployed on AWS using KOPS.

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
