### ISSUE TITLE
Add metric for missing kubernetes secret used by istio ingress gateway

### ISSUE THREAD

**Issue by bnutt** [istio/istio#31779]
**Describe the feature request**
Users can specify kubernetes secrets in Gateway objects which will allow them to reference which TLS certs they would like to load, this is done by specifying a credentialName. 

Example:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
  namespace: some-config-namespace
spec:
  selector:
    app: my-gateway-controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - uk.bookinfo.com
    - eu.bookinfo.com
    tls:
      httpsRedirect: true # sends 301 redirect for http requests
  - port:
      number: 9443
      name: https-9443
      protocol: HTTPS
    hosts:
    - "bookinfo-namespace/*.bookinfo.com"
    tls:
      mode: SIMPLE # enables HTTPS on this port
      credentialName: bookinfo-secret # fetches certs from Kubernetes secret
```
If istiod is unable to find this secret, it currently logs 

```
failed to fetch key and certificate for kubernetes://bookinfo-secret. 
```

It would be helpful to export a prometheus metric to indicate when istiod is unable to load this secret instead of having to check istiod logs for these errors when there are issues with traffic into the ingress gateway. Alerts can then be built around this metric accordingly.

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**

Istio 1.9
Telemetry v2
