### ISSUE TITLE
Documented field security.istio.io/v1beta1 AuthorizationPolicy/spec.rules.from.source.host does not exist

### ISSUE THREAD

**Issue by ludydoo** [istio/istio#31777]
**Bug description**

In the documentation https://istio.io/latest/docs/ops/configuration/security/security-policy-examples/ , there is an example 

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: jwt-per-host
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: ALLOW
  rules:
  - from:
    - source:
        hosts: ["example.com", "*.example.com"]
        # the JWT token must have issuer with suffix "@example.com"
        requestPrincipals: ["*@example.com"]
    - source:
        hosts: [".another.org", "*.another.org"]
        # the JWT token must have issuer with suffix "@another.org"
        requestPrincipals: ["*@another.org"]
```

Though, the `hosts` field does not seem to exist in the CRD. https://github.com/istio/istio/blob/d50c9dfa5181ff0926ef4173db9ccb44f5c18fa8/manifests/charts/base/crds/crd-all.gen.yaml#L5462

[X ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade
