### ISSUE TITLE
Exposing headless service with statefulset (in multi primary setup) is not resolvable across clusters.

### ISSUE THREAD

**Issue by irajdeep** [istio/istio#31787]
**Bug description**
I have `multi-primary-cluster` set up on the same network based on these [instructions](https://istio.io/latest/docs/setup/install/multicluster/multi-primary/). Cross cluster connectivity is working as expected as mentioned in these [verification docs](https://istio.io/latest/docs/setup/install/multicluster/verify/). But exposing a `headless` service(with a statefulset) in cluster2 is not getting resolved from cluster1(using pod FQDN).

[x] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
The headless service deployed in cluster2 is getting resolved from cluster1. 

**Steps to reproduce the bug**
i. Follow the [multi primary installation docs](https://istio.io/latest/docs/setup/install/multicluster/multi-primary/) to install istio in multi-cluster setup.
ii. Verify the setup is working as per this [verification docs](https://istio.io/latest/docs/setup/install/multicluster/verify/). 
iii. Create a headless `service` backed by a `statefulset` in cluster 2.
```yaml
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
    service: helloworld
spec:
  clusterIP: None
  ports:
  - port: 5000
    name: http
  selector:
    app: helloworld
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: helloworld
spec:
  serviceName: "helloworld"
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: docker.io/istio/examples-helloworld-v2
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
```
The service object was also created in cluster1 (-- not sure if it's necessary for this use case).

iv. verify the pod FQDN is resolvable from cluster2: `curl helloworld-0.helloworld.test.svc.cluster.local:5000/hello` -- works as expected.
v. Create service entry objects corresponding to each of the statefulset pods in the `test` namespace in cluster1 to make the `pod` FQDNs resolvable from cluster1 with the following spec.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: helloworld-0
spec:
  hosts:
  - "helloworld-0.helloworld.test.svc.cluster.local"
  location: MESH_INTERNAL
  ports:
  - number: 5000
    name: http
    protocol: TCP
  resolution: DNS
```
and
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: helloworld-1
spec:
  hosts:
  - "helloworld-1.helloworld.test.svc.cluster.local"
  location: MESH_INTERNAL
  ports:
  - number: 5000
    name: http
    protocol: TCP
  resolution: DNS

```
vi. exec into a pod in cluster1(in `test` namespace) and run `curl helloworld-0.helloworld.test.svc.cluster.local:5000/hello` -- this would return `Could not resolve host: helloworld-0.helloworld.test.svc.cluster.local`

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
client version: 1.9.1
control plane version: 1.9.1
data plane version: 1.9.1 (5 proxies)
```

**How was Istio installed?**
https://istio.io/latest/docs/setup/install/multicluster/multi-primary/

**Environment where the bug was observed (cloud vendor, OS, etc)**
Deployed on AWS using KOPS.

Note: `ServiceEntry` object was created based on the discussion here: https://github.com/istio/istio/issues/7495
Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by irajdeep** [comment]
@howardjohn would appreciate any input on this

**Comment by irajdeep** [comment]
Thanks for the cue @howardjohn. I enabled DNS proxy in both clusters. Verified that it works with [this step](https://istio.io/latest/docs/ops/configuration/traffic-management/dns-proxy/#dns-capture-in-action).

Thereafter I created a ServiceEntry in cluster1 to make the statefulset pod(exposed via headless service) in cluster2 be reachable from cluster1:

ServiceEntry spec:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: helloworld-0
spec:
  hosts:
  - "helloworld-0.helloworld.test.svc.cluster.local"
  location: MESH_INTERNAL
  ports:
  - number: 5000
    name: http
    protocol: TCP
  resolution: DNS

```
This time running curl from a pod in the same namespace in cluster1, getting this error:
```
curl -v helloworld-0.helloworld.test.svc.cluster.local:5000/hello
*   Trying 240.240.0.1:5000...
* Connected to helloworld-0.helloworld.test.svc.cluster.local (240.240.0.1) port 5000 (#0)
> GET /hello HTTP/1.1
> Host: helloworld-0.helloworld.test.svc.cluster.local:5000
> User-Agent: curl/7.75.0-DEV
> Accept: */*
>
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

Any pointers on what could be going wrong here? 
Btw I have created the same ServiceEntry in both the cluster (although I am not sure if it's needed in cluster2 where the actual headless service is created).
