### ISSUE TITLE
Cannot Access Istio ingress services on Port 80 using the Master Node IP

### ISSUE THREAD

**Issue by anthonyvk** [istio/istio#31788]
**Cannot Access Istio ingress services on Port 80 using the Master Node IP (Example : http://MASTERNODEIP/service1) in the baremetal environment. All the services can only be accessed using the NodePort of the Master IP**

[X] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
I must be able to access services using the master IP without specifying NodePort. (Example : http://MASTERIP/service1)

**Steps to reproduce the bug**
- Have a Baremetal Kubernetes Cluster with 3 nodes and 1 master
- Install Istio 1.9.2 using Helm chart.
- Create a new Deployment with gateway and Virtual Service.
```

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: xyz-gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - "*"
  gateways:
    - xyz-gateway
  http:
    - match:
      - uri:
          prefix: /service1
      route:
        - destination:
            port:
              number: 80
            host: xyz-service

```
- Access the service using the Master IP.

**Version**
Helm Version : v3.3.4+ga61ce56
Kubectl Client Version: v1.18.6
Kubectl Server Version: v1.17.7

**How was Istio installed?** 
Using Helm charts (without any modifications)

**Environment where the bug was observed (cloud vendor, OS, etc)**
Baremetal Cluster

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
