### ISSUE TITLE
1.6 TLS Origination for external services that require host file for DNS 

### ISSUE THREAD

**Issue by kmcrawford** [istio/istio#31793]
**Bug description**
When following this document for istio 1.6 I can the TLS upgrade to work for any external domain that doesn't have a DNS.
https://istio.io/v1.6/docs/tasks/traffic-management/egress/egress-tls-origination/

We have another service that is internal to our company but is not managed by istio as it is on another VM in another Cloud provider (privately networked via VPN)

For the service to be called from a calling pod a hostAliases is required that maps the hostname to an IP Address.  

When updating the demo yaml from the example linked above to use this new internal service I have to make changes to my Service Entry like the below.  

However it doesn't look like the TLS upgrade is happening.  The reason for all of this is b/c I want to add outlierDetection to the TLS call since istio cannot read the HTTP status if the application originates the TLS.

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: test-internal-se
spec:
  hosts:
    - myinternalhost.mycompany.com
  location: MESH_EXTERNAL
  addresses:
    - 10.##.##.##/32 (IP hidden)
  ports:
    - number: 80
      name: http-port
      protocol: HTTP
    - number: 443
      name: https-port-for-tls-origination
      protocol: HTTPS
  resolution: NONE
```

[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
I expect the HTTP call to be TLS upgraded and call the external service using HTTPS on port 443.

**Steps to reproduce the bug**
curl http://myinternalhost.mycompany.com/v1/stuff  doesn't not work b/c the service does not accept calls on port 80.  I suspect either this is a mis-config issue with my servicEntry or there is a bug.

I also verified there are no other ServiceEntries for this host or IpAddress currently setup in the istio cluster.

**Version** 
kube version: `Server Version: v1.17.15-gke.800`
istio version: 1.6.14

**How was Istio installed?**
Operator

**Environment where the bug was observed (cloud vendor, OS, etc)**
GKE
