### ISSUE TITLE
DNS queries to zipkin when tracing is disabled

### ISSUE THREAD

**Issue by yvespp** [istio/istio#31809]
**Bug description**

I'm seeing DNS queries in coredns to zipkin even though tracing is disabled. We found this similar issue https://github.com/istio/istio/pull/13110 but we can disabled the tracer completely because we use the operator and it doesn't allow to set the tracer to "" or empty:

IstioOperator config:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      proxy:
        tracer: ""
```

Error in operator log:
```
2021-03-31T08:12:27.413703Z     info    Reconciling IstioOperator
2021-03-31T08:12:27.415035Z     info    Updating IstioOperator
2021-03-31T08:12:27.415085Z     info    installer       Loading values from compiled in VFS at path profiles/default.yaml
2021-03-31T08:12:27.595551Z     error   failed to generate IstioOperator spec, unknown value "" for enum v1alpha1.Tracer
```

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

No DNS queries to zipkin when Tracing is disabled or allow setting spec.values.global.proxy.tracer="" in operator to disable it.

**Version**
```
$ istioctl version --remote
client version: 1.8.1
control plane version: 1.7.3
data plane version: 1.7.3 (4 proxies)

$ kubectl version --short
Client Version: v1.20.5
Server Version: v1.20.5
```

**How was Istio installed?**
Operator

**Comment by bianpengyuan** [comment]
please take a look at https://github.com/istio/istio/issues/31553. Thanks!

**Comment by bianpengyuan** [comment]
Feel free to reopen if your issue is not resolved by comments there. Thanks!

**Comment by yvespp** [comment]
@bianpengyuan How do I remove the default with the operator? I tried this:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    defaultConfig:
      tracing: {}
```

But it still shows up in the istio configmap and the envoy bootstrap config:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: istio
  namespace: istio-system
data:
  mesh: |-
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      proxyMetadata:
        DNS_AGENT: ""
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
```

**Comment by bianpengyuan** [comment]
Hmm I am not sure.. probably an operator bug? I am not familiar with operator. Does restarting operator help?

**Comment by boredabdel** [comment]
In the IstioOperator file i added 

```
     defaultConfig:
       tracing: {}

```
To the spec section

**Comment by yvespp** [comment]
> In the IstioOperator file i added
> 
> ```
>      defaultConfig:
>        tracing: {}
> ```
> 
> To the spec section

Thanks for the reply!
If add it directly under spec the operator complains and doesn't rollout the config:
```
2021-04-13T12:35:55.728831Z     error   k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1alpha1.IstioOperator: v1alpha1.IstioOperatorList.Items: []v1alpha1.IstioOperator: v1alpha1.IstioOperator.Status: Spec: unmarshalerDecoder: unknown field "defaultConfig" in v1alpha1.IstioOperatorSpec, error found in #10 byte of ...|":false}}},"status":|..., bigger context ...|:{"enabled":false}}},"tracing":{"enabled":false}}},"status":{"componentStatus":{"Base":{"status":"HE|...
```

**Comment by boredabdel** [comment]
Which version of istio are you on ?

**Comment by yvespp** [comment]
1.7.3

**Comment by dvob** [comment]
@bianpengyuan Can we reopen this Issue? We are unable to remove Zipkin from the mesh config and still see the DNS requests for `zipkin.istio-system`:

Steps to reproduce:
```
$ istioctl version
client version: 1.9.4
control plane version: 1.9.4
data plane version: 1.9.4 (1 proxies)

$ istioctl manifest generate -f istiooperator.yaml | grep -C 5 tracing

  mesh: |-
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      proxyMetadata: {}
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
    enablePrometheusMerge: true
    rootNamespace: istio-system
    trustDomain: cluster.local
```
* `istiooperator.yaml`
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: default
spec:
  meshConfig:
    defaultConfig:
      tracing: {}
```

**Comment by bianpengyuan** [comment]
Yeah looks like somehow the istioctl mesh config overlay does not work and it cannot replace the generated ones.

**Comment by dvob** [comment]
@boredabdel in #31553 you said that you figured out a way to disable tracing. Can you share your full IstioOperator config or the relevant parts to disable it? With the solution you shared above I get the following error:

```
$ istioctl manifest generate -f istiooperator.yaml
Error: unknown field "defaultConfig" in v1alpha1.IstioOperatorSpec:
...
```

* `istiooperator.yaml` with `defaultConfig` in spec section:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: default
spec:
  defaultConfig:
    tracing: {}
```

I tested this with istioctl 1.9.4 and 1.6.7 (the version you mentioned in #31553) and with both versions I get the same error.
