### ISSUE TITLE
Ingress Gateway TLS PASSTHROUGH Mode

### ISSUE THREAD

**Issue by darkdatter** [istio/istio#31814]
**Bug description**

I am struggling to get a simple use case with Ingress gateway tls mode PASSTHROUGH to work. I have seen many older and newer issues relating to this task, so I feel a issue here is warranted. 

I have a simple TLS client and server, written in Python that do a mutual TLS handshake. Outside of isio, these two work just fine with my certs.  

- Demo namespace shown here is under tls STRICT mode.
- I have plugged in my own intermediate CA certs, and istio-proxies are using them.

Gateway:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: demo-gateway
  namespace: demo
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 8123
      name: tls-port
      protocol: TLS
    tls:
      mode: PASSTHROUGH
    hosts:
    - my-service.demo.svc.cluster.local
```

Virtual Service:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: demo-virtualsvc
  namespace: demo
spec:
  hosts:
  - "*" # FQDN of service i.e. something.demo.svc.cluster.local
  gateways:
  - demo-gateway
  tls:
  - match:
    - port: 8123 # Arrival port (external)
      sniHosts:
      - my-service.demo.svc.cluster.local
    route:
    - destination:
        host: my-service.demo.svc.cluster.local # FQDN of service i.e. something.demo.svc.cluster.local
        port:
          number: 8123 # Destination service port (internal)
```

When testing with my client/server outside of Istio:
- I can view the cert chain with:
```openssl s_client -showcerts -connect <IP>:8123```
- I see in this order: the server cert, intermediate ca cert, root cert. The handshake succeeds. I can also connect to the Python server from the Python client.

However, when I test this with the server internal to my demo namespace (protected with STRICT mode), I run the openssl command and get a cert chain in return containing: a random cert I have not seen before, my intermediate ca, and my root ca certs. If I test with my Python client reaching to the server, the client throws an unknown ca error. 

I am confused. What cert is this random one? Is PASSTHROUGH working, or causing my connection to get broken?

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
The TLS traffic should be passed through, resulting in a successful TLS handshake. 

**Steps to reproduce the bug**

**Version**
Istio:
client version: 1.8.2
control plane version: 1.8.2
data plane version: 1.8.2 (16 proxies)

kubectl:
Client Version: v1.18.15+k3s1
Server Version: v1.18.15+k3s1

k3s:
k3s version v1.18.15+k3s1 (60f1e80d)

**How was Istio installed?**
istioctl install
(default profile)

**Environment where the bug was observed (cloud vendor, OS, etc)**
k3s running on AWS instances (k3s version v1.18.15+k3s1 (60f1e80d))

**Comment by howardjohn** [comment]
I tried to reproduce and couldn't. Could you get a config dump to show more info: https://github.com/istio/istio/wiki/Troubleshooting-Istio

What *should* be happening is `client --- TLS ---> gateway ---> TLS+mTLS ---> sidecar ---> TLS ---> python server`. It seems like what may be happening is `client --- TLS ---> gateway ---> TLS ---> sidecar (rejects request, expects mTLS but got TLS) ---> never connected ---> python server`?

**Comment by darkdatter** [comment]
> I tried to reproduce and couldn't. Could you get a config dump to show more info: https://github.com/istio/istio/wiki/Troubleshooting-Istio
> 
> What _should_ be happening is `client --- TLS ---> gateway ---> TLS+mTLS ---> sidecar ---> TLS ---> python server`. It seems like what may be happening is `client --- TLS ---> gateway ---> TLS ---> sidecar (rejects request, expects mTLS but got TLS) ---> never connected ---> python server`?

The config dump that I have is very long (~10k lines), and I can't attach files. Is there a subset that I can send to you?

Also, I checked the information on that random cert I mentioned, and It looks like it's the sidecar's cert.

**Comment by darkdatter** [comment]
@howardjohn I had a few things wrong in my setup that I resolved. I still can't get this to work however. I tested the [ingress-sni-passthrough example ](https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/) and was able to get that to work. Take a look at my following config, it seems like traffic can't get from the GW to my service:

istio-ingressgateway:
```[2021-04-01T14:05:31.213Z] "- - -" 0 NR "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.42.2.148:8123 10.42.2.1:48263 - -``` 
2.148 is the istio-ingressgateway.

**The SAN on my server cert is ```server.cluster.local```, and the Subject = ```CN=server.cluster.local```

Service:
```
apiVersion: v1
kind: Service
metadata:
  name: listen
  namespace: demo
  labels:
    app: listen
spec:
  ports:
  - port: 8123
    protocol: TCP
  selector:
    app: listen
```
Gateway:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: demo-gateway
  namespace: demo
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 8123
      name: tls-port
      protocol: TLS
    tls:
      mode: PASSTHROUGH
    hosts:
    - server.cluster.local
```
Virtual service:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: demo-virtualsvc
  namespace: demo
spec:
  hosts:
  - server.cluster.local 
  gateways:
  - demo-gateway
  tls:
  - match:
    - port: 8123 # Arrival port (external)
      sniHosts:
      - server.cluster.local
    route:
    - destination:
        host: listen 
        port:
          number: 8123 
```
Deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: listen
  namespace: demo
spec:
  selector:
    matchLabels:
      app: listen
  replicas: 1
  template:
    metadata:
      labels:
        app: listen
    spec:
      containers:
      - name: listen
        image: <myimage>
        imagePullPolicy: Always
        ports:
        - containerPort: 8123
```

My istio-ingressgateway was edited to have the port added:
```
  - name: custom-tls
    nodePort: 31597
    port: 8123
    protocol: TCP
    targetPort: 8123
```
I am almost totally mirroring the nginx example, but with TLS instead of HTTPS.
