### ISSUE TITLE
enhance the quitquitquit API to allow a configurable sleep time

### ISSUE THREAD

**Issue by linsun** [istio/istio#31822]
**Describe the feature request**

The /quit API (https://github.com/istio/istio/issues/15041) is very handy however for users who run distroless proxy v2 image, they don't have a way to specify wait some seconds then call the /quit API

We would like to enhance the API to take a wait param, like /quitquitquit?wait=30s

[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by linsun** [comment]
cc @christian-posta @rvennam

**Comment by howardjohn** [comment]
Curious why you want to call it with delay rather than just waiting before calling it?

**Comment by linsun** [comment]
if I understand what you are asking @howardjohn, the challenge is how to wait on distroless.  Users can't call sleep cmd there.

**Comment by howardjohn** [comment]
How can you know how long to wait?

**Comment by linsun** [comment]
@jenshu is interested in working on this.

**Comment by linsun** [comment]
@howardjohn can you confirm you are okay with a configurable wait as a starting point?

**Comment by howardjohn** [comment]
I still don't get how its used. Why would you want to quit in 30s instead of immediately?

**Comment by linsun** [comment]
Let us say the app container takes 20s to shutdown so I want to call /quitquitquit?wait=20s to shutdown envoy in the prestop hook of the sidecar to ensure the app container shutdown first, then envoy.  

@howardjohn does this make sense?

**Comment by howardjohn** [comment]
I think terminationDrainDuration seems to do what you want in proxy config? it will delay exit after sigterm

**Comment by infa-ddeore** [comment]
TERMINATION_DRAIN_DURATION_SECONDS closes incoming listener (allows only outgoing connection) on the istio sidecar which denies incoming traffic which may be received while k8 removes the pod from its endpoint

**Comment by howardjohn** [comment]
It does not close the listener, it drains them which means we will send connection: close header. It shouldn't be blocking requests entirely, just promoting clients to connect to somewhere else

**Comment by infa-ddeore** [comment]
in my test after killing a test pod, sidecar closes the inbound listener

this are the listening ports before pod is getting killed, i have set `TERMINATION_DRAIN_DURATION_SECONDS` as 100:
```
$ netstat -tulpn  
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:15021           0.0.0.0:*               LISTEN      14/envoy            
tcp        0      0 0.0.0.0:15090           0.0.0.0:*               LISTEN      14/envoy            
tcp        0      0 127.0.0.1:15000         0.0.0.0:*               LISTEN      14/envoy            
tcp        0      0 0.0.0.0:15001           0.0.0.0:*               LISTEN      14/envoy            
tcp        0      0 0.0.0.0:15006           0.0.0.0:*               LISTEN      14/envoy            
tcp6       0      0 :::15020                :::*                    LISTEN      1/pilot-agent       
```
as soon as the pod is killed by kubectl, the [inbound listener](https://istio.io/latest/docs/ops/deployment/requirements/#ports-used-by-istio) is closed, `15006` isnt listening:
```
$ netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:15021           0.0.0.0:*               LISTEN      14/envoy            
tcp        0      0 0.0.0.0:15090           0.0.0.0:*               LISTEN      14/envoy            
tcp        0      0 127.0.0.1:15000         0.0.0.0:*               LISTEN      14/envoy            
tcp        0      0 0.0.0.0:15001           0.0.0.0:*               LISTEN      14/envoy        
```

**Comment by howardjohn** [comment]
I don't see the same behavior. What version are you using?

**Comment by linsun** [comment]
@infa-ddeore is using 1.7.5, @howardjohn

**Comment by howardjohn** [comment]
I am not sure implementing a new feature (in master) to workaround a limitation not present in master makes sense?

**Comment by linsun** [comment]
@howardjohn do you know if this is fixed in 1.9?  @infa-ddeore is interested in trying this with 1.9?

Thank you for raising this `TERMINATION_DRAIN_DURATION_SECONDS` field.

**Comment by howardjohn** [comment]
It is probably https://github.com/istio/istio/pull/26528 that changed it

**Comment by linsun** [comment]
@howardjohn Ah thanks, thinking the same, recalled you added it!! :)

@infa-ddeore let us know how it goes with 1.9.

**Comment by infa-ddeore** [comment]
i dont see this issue in `1.9.2` 

before kubectl delete po:

```
$ netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:15000         0.0.0.0:*               LISTEN      15/envoy            
tcp        0      0 0.0.0.0:15001           0.0.0.0:*               LISTEN      15/envoy            
tcp        0      0 0.0.0.0:15006           0.0.0.0:*               LISTEN      15/envoy            
tcp        0      0 0.0.0.0:15021           0.0.0.0:*               LISTEN      15/envoy            
tcp        0      0 0.0.0.0:15090           0.0.0.0:*               LISTEN      15/envoy            
tcp6       0      0 :::15020                :::*                    LISTEN      1/pilot-agent   
```

after deleting, `15006` still keep listening:
```
$ netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:15000         0.0.0.0:*               LISTEN      15/envoy            
tcp        0      0 0.0.0.0:15001           0.0.0.0:*               LISTEN      15/envoy            
tcp        0      0 0.0.0.0:15006           0.0.0.0:*               LISTEN      15/envoy            
tcp        0      0 0.0.0.0:15021           0.0.0.0:*               LISTEN      15/envoy            
tcp        0      0 0.0.0.0:15090           0.0.0.0:*               LISTEN      15/envoy            
```

**Comment by linsun** [comment]
That is great news, Thanks @infa-ddeore!  I'm going to close this issue as fixed in newer Istio.

**Comment by infa-ddeore** [comment]
@howardjohn `15006` port closes after ~44 seconds of term signal even though `TERMINATION_DRAIN_DURATION_SECONDS` and `terminationGracePeriodSeconds` set to 100, this is reproducible in `1.8` and `1.9` 

is that the max time inbound listener can stay open or is it a bug?

**Comment by linsun** [comment]
Hi @infa-ddeore - I am no longer seeing TERMINATION_DRAIN_DURATION_SECONDS in our code base, I think this is not being used.   One thing you could double check if your config is effective is to check the logs in pilot-agent, you should see:

```
	log.Infof("Graceful termination period is %v, starting...", a.terminationDrainDuration)
	time.Sleep(a.terminationDrainDuration)
	log.Infof("Graceful termination period complete, terminating remaining proxies.")
```

@howardjohn suggested to use [`terminationDrainDuration`](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig), which you could configure it as an annotation on your pod, examples:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hello
spec:
  replicas: 7
  selector:
    matchLabels:
      app: hello
      tier: backend
      track: stable
  strategy: {}
  template:
    metadata:
      annotations:
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "15020"
        prometheus.io/scrape: "true"
        proxy.istio.io/config: '{ "terminationGracePeriodSeconds": 100s }'
```

**Comment by linsun** [comment]
@infa-ddeore there is also another proxy config called ['drainDuration'](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig) which by default is 45s, I think that explains what you saw.  You could overwrite it similar as the example I shared earlier as an annotation.  And also adjust the proxy config 'parentShutdownDuration' as well.

**Comment by howardjohn** [comment]
It moved to terminationDrainDuration in proxy config. drainDuration
and parentShutdownDuration are different (they are envoy settings)

**Comment by linsun** [comment]
Yep - thanks @howardjohn!

I'm closing this now as I worked with @infa-ddeore offline and he has a working yaml now.  There is a few things he had to set:

terminationDrainDuration as an istio proxy config
drainDuration as an istio proxy config
parentShutdownDuration  as an istio proxy config
terminationGracePeriodSeconds as k8s pod config

**Comment by infa-ddeore** [comment]
here is a sample deployment incase anyone come here:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver

      annotations:
        proxy.istio.io/config: |-
           drainDuration: 100s
           parentShutdownDuration: 101s
           terminationDrainDuration: 101s

    spec:
      containers:
      - image: gcr.io/google_containers/echoserver:1.0
        imagePullPolicy: Always
        name: echoserver
        ports:
        - containerPort: 8080

      terminationGracePeriodSeconds: 102
```
