### ISSUE TITLE
Envoy support CONNECT

### ISSUE THREAD

**Issue by semihural** [istio/istio#31830]
We are using Istio 1.9.0 on our on-prem kubernetes cluster.. All the external traffics should go through our cooperate proxy which avoid us to use some main features that Istio present such as retry logic and ext cause seems envoy does not support CONNECT method as we discussed with below issue.

Could you please add your roadmap to support CONNECT method ?

https://github.com/istio/istio/issues/31557

**Comment by toshi-k** [comment]
We are facing the same issue. We deploy the on-prem k8s cluster and istio in our company network. We have to pass the company proxy to access the external network. When trying HTTPS external access from the pod with sidecar proxy, it is failed because of the non-support of CONNECT method.

I appreciate if there is an alternative way or I can know the plan about CONNECT method.

**Comment by toshi-k** [comment]
I solved my issue ! Now, I can access the external network from our internal cluster with istio. Basically, I followed the below introduction.

Using an External HTTPS Proxy
https://istio.io/latest/docs/tasks/traffic-management/egress/http-proxy/

The reason I had a trouble for the first time was that I didn't list all IP addresses.
Our proxy corresponds to multiple IP addresses and I needed to list all of them.
So, I configured as below.

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: proxy
  namespace: target_namespace
spec:
  hosts:
  - my-company-proxy.com
  addresses:
  - $PROXY_IP_RANGE1/24
  - $PROXY_IP_RANGE2/24
  - $PROXY_IP_RANGE3/24
  ports:
  - number: $PROXY_PORT
    name: tcp
    protocol: TCP
  location: MESH_EXTERNAL
```

@semihural Does this information help you ?
