### ISSUE TITLE
Request to configure require_client_certificate in envoy explicitly in istio ingress gateway

### ISSUE THREAD

**Issue by bigmarvin** [istio/istio#31860]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Could istio provide optional client cert validation in ingress-gateway?

**Describe alternatives you've considered**
At present, tls mode SIMPLE doesn't request client cert so clients can't send one. On the other hand, mode MUTUAL enforces the presence of client cert, by setting require_client_certificate to true in envoy. I tried to overwrite this using envoy filter and it didn't work, which I assume is my problem, but could we just provide some explicit configuration (new mode or new property) to flip this switch?

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by bigmarvin** [comment]
regarding the failed attempt to overwrite this property via some envoy filter, some warning log was found when the following envoy filter is applied, suggesting the absence of server cert in this context. the commented lines must be brought back for the envoy filter to take effect, at the cost that this piece of configuration is no longer managed by istio.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: some-envoy-filter
  namespace: istio-system
spec:
  configPatches:
  - applyTo: FILTER_CHAIN
    match:
      context: GATEWAY
      listener:
        portNumber: 12345
        filterChain:
          sni: "sni"
          filter:
            name: "envoy.transport_sockets.tls"
    patch:
      operation: MERGE
      value:
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.api.v2.auth.DownstreamTlsContext
            # common_tls_context:
            #   tls_params:
            #     tls_maximum_protocol_version: TLSv1_2
            #   validation_context:
            #     trusted_ca:
            #       filename: /tmp/ca
            #   tls_certificates:
            #   - certificate_chain:
            #       filename: /tmp/crt
            #     private_key:
            #       filename: /tmp/key
            require_client_certificate: false
```

```
[Envoy (Epoch 1)] [2021-04-02 03:45:31.966][5396][warning][config] [external/envoy/source/common/config/grpc_subscription_impl.cc:87] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) 0.0.0.0_12345: No TLS certificates found for server context
```

I assume there's some issue in merge operation of envoy filters in 1.15.0, so please let me know if it's known and fixed in some new version.
