### ISSUE TITLE
MeshNetworks docs is wrong - networks is a map not an array

### ISSUE THREAD

**Issue by jmazzitelli** [istio/istio#31862]
**Bug description**

Look at the docs here: https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshNetworks

and notice the dash (`-`) before `endpoints` in the example:

```
networks:
  network1:
  - endpoints:   <<<<----- LOOK HERE!
    - fromRegistry: registry1 #must match kubeconfig name in Kubernetes secret
    - fromCidr: 192.168.100.0/22 #a VM network for example
    gateways:
    - registryServiceName: istio-ingressgateway.istio-system.svc.cluster.local
      port: 15443
      locality: us-east-1a
    - address: 192.168.100.1
      port: 15443
      locality: us-east-1a
```

When you follow this example, the istiod pod will log the following (side note: this should NOT be an "info" level message - it should at minimum be "warn" if not "error"):

```
info	failed to read mesh networks configuration from "/etc/istio/config/meshNetworks": failed to convert to proto. json: cannot unmarshal array into Go value of type map[string]json.RawMessage
```

I happen to notice another example for this section of the config [here in this issue comment](https://github.com/istio/istio/issues/29359#issuecomment-738347706). And this is what it shows:

```
data:
  meshNetworks: |-
   networks:
     network1:
       endpoints:  <<<<---- LOOK HERE! Not array (no dash)
         - fromRegistry: cluster1
       gateways:
         - address: 1.2.3.4
           port: 15443
```

Notice the difference.

When I changed my config to match that, things parsed successfully and the istiod pod shows the parsed json.

SOLUTION:

1) The documentation needs to change - that single "dash" effectively wasted a few hours of my time :)

2) The log message should not be at "info" level - that will clearly cause istiod to misbehave since it effectively is missing configuration - it should at minimum be a "warn" message (I would think it should be "error" since the behavior of the istiod pod will be broken).

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Version**

1.9.2
