### ISSUE TITLE
Istio gateway workload selector not working across namespaces

### ISSUE THREAD

**Issue by thorion3006** [istio/istio#31889]
**Bug description**

Gateway deployed in namespace A can't access gateway workload deployed in `istio-system` namespace.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Gateway defined in any namespace should be able to attach to workload in any other namespace.

**Steps to reproduce the bug**

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: temp-gateway
  namespace: temp
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  servers:
    - hosts:
        - '*.example.com'
      port:
        name: http2-temp
        number: 80
        protocol: HTTP2
      tls:
        httpsRedirect: true
    - hosts:
        - '*.example.com'
      port:
        name: https-temp
        number: 443
        protocol: HTTPS
      tls:
        credentialName: example-com-tls
        mode: SIMPLE
```

I even tried with env variable `PILOT_SCOPE_GATEWAY_TO_NAMESPACE: 'false'` in istiod

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
$ istioctl version --remote
> client version: 1.9.2
> control plane version: 1.9.2
> data plane version: 1.9.2 (8 proxies)
```
```
$ kubectl version --short
> Client Version: v1.20.4-dirty
> Server Version: v1.19.7
```

**How was Istio installed?**

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  revision: 1-9-2
  tag: 1.9.2-distroless
  components:
    egressGateways:
      - name: istio-egressgateway
        enabled: true
  meshConfig:
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    connectTimeout: 5s
    protocolDetectionTimeout: 1s
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: 'true'
        ISTIO_META_DNS_AUTO_ALLOCATE: 'true'
      proxyStatsMatcher:
        inclusionPrefixes:
          - downstream_rq_active
    defaultServiceExportTo:
      - '.'
    defaultVirtualServiceExportTo:
      - '.'
    defaultDestinationRuleExportTo:
      - '.'
    enableAutoMtls: true
    enableTracing: false
    h2UpgradePolicy: UPGRADE
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
  values:
    global:
      configValidation: true
      logAsJson: true
      logging:
        level: 'default:info'
    pilot:
      traceSampling: 0.0
    sidecarInjectorWebhook:
      useLegacySelectors: false
```

**Environment where the bug was observed (cloud vendor, OS, etc)**

Azure AKS

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

[bug-report.zip](https://github.com/istio/istio/files/6252627/bug-report.zip)

**Comment by bianpengyuan** [comment]
Works for me. How did you check if it is taking effect? Did you see any error log in istiod?

**Comment by thorion3006** [comment]
@bianpengyuan istiod didn't throw any error, but at the same time there was log for:
`"msg":"constructed http route config for route https.443.https-temp.istio-ingressgateway.istio-system on port 443 with no vhosts; Setting up a default 404 vhost"}`
Also if I try to initiate any traffic in that gateway, it never shows up in the ingress log

P.S I this side car policy in my cluster, but I don't think that should affect this issue:
```yaml
kind: Sidecar
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: default
  namespace: istio-system
spec:
  egress:
    - hosts:
        - ./*
        - istio-system/*
```
