### ISSUE TITLE
ingressGateways do not upgraded correctly

### ISSUE THREAD

**Issue by kovalyukm** [istio/istio#31898]
**Bug description**
There is an issue with upgrading of ingressGateways using ether Canary or In-place method on 1.7-1.9 versions.

Istioctl upgrades only the last gateway in order and merges some values from previous one, seems those that not set in the last one.

[ ] Docs
[ X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ X] Upgrade

**Steps to reproduce the bug**
```yaml
# istioctl upgrades only the last item of ingressGateways and with wrong loadBalancerSourceRanges, serviceAnnotations
istioctl upgrade -f test.yaml

spec:
  components:
    ingressGateways:
      '[#0]':
        k8s: -> map[priorityClassName:medium resources:map[requests:map[cpu:500m]] service:map[externalTrafficPolicy:Local loadBalancerSourceRanges:[1.1.1.1/32] ports:[map[name:status-port nodePort:30649 port:15021 protocol:TCP targetPort:15021] map[name:http2 nodePort:31860 port:80 protocol:TCP targetPort:8080] map[name:https nodePort:30512 port:443 protocol:TCP targetPort:8443] map[name:grpc nodePort:31689 port:8080 protocol:TCP targetPort:8080]]] serviceAnnotations:map[service.beta.kubernetes.io/aws-load-balancer-eip-allocations:eipalloc-000,eipalloc-111,eipalloc-222 service.beta.kubernetes.io/aws-load-balancer-internal:true service.beta.kubernetes.io/aws-load-balancer-type:nlb]]
        namespace: -> istio-ingressgateway-internal
```
```yaml
  components:

    ingressGateways:
    - enabled: false
      name: istio-ingressgateway

    - namespace: istio-ingressgateway-external
      name: istio-ingressgateway
      enabled: true
      k8s:
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
          service.beta.kubernetes.io/aws-load-balancer-eip-allocations: "eipalloc-000,eipalloc-111,eipalloc-222"
        service:
          ports:
          - name: status-port
            nodePort: 32148
            port: 15021
            targetPort: 15021
          - name: https
            nodePort: 30682
            port: 443
            targetPort: 8443
          loadBalancerSourceRanges:
          - 1.1.1.1/32
          externalTrafficPolicy: Local
        priorityClassName: "high"

    - namespace: istio-ingressgateway-internal
      name: istio-ingressgateway
      enabled: true
      k8s:
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
          service.beta.kubernetes.io/aws-load-balancer-internal: "true"
        service:
          ports:
            - name: status-port
              nodePort: 30649
              port: 15021
              protocol: TCP
              targetPort: 15021
            - name: http2
              nodePort: 31860
              port: 80
              protocol: TCP
              targetPort: 8080
            - name: https
              nodePort: 30512
              port: 443
              protocol: TCP
              targetPort: 8443
            - name: grpc
              nodePort: 31689
              port: 8080
              protocol: TCP
              targetPort: 8080
          externalTrafficPolicy: Local
        resources:
          requests:
            cpu: 500m
        priorityClassName: "medium"
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
kubectl version --short
Client Version: v1.20.4-dirty
Server Version: v1.19.6-eks-49a6c0

istioctl version 1.9.2
```

**How was Istio installed?**
istioctl install -f ${overlay_config}

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS

I suppose that the issue might be with the same `name` in ingressGateways.

Please advise.
