### ISSUE TITLE
analyzer false negative on virtual service match

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#31916]
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vs
spec:
  gateways:
  - good-gateway
  hosts:
  - foo.bar
  http:
  - match:
    - gateways:
      - bad-gateway
    route:
    - destination:
        host: something
        port:
          number: 1234
```

`bad-gateway` is not detected as non-existent
