### ISSUE TITLE
VirtualService.Status.ObservedGeneration does not increment

### ISSUE THREAD

**Issue by dprotaso** [istio/istio#31931]
**Bug description**

[x] Extensions and Telemetry (because CLI and other non-human programming of Istio are affected by this)
[x] User Experience (Advanced K8s users would expect this value to increment like other K8s resources)

**Expected behavior**

When a VirtualService's spec is changed and the istio controller's does it's thing I expect the `status.observedGeneration` to match that of the `metadata.generation`

**Steps to reproduce the bug**

Apply bookinfo with the v1 VirtualService. Manually add some random host to one of the VirtualService and look at the `observedGeneration`

**How was Istio installed?**

Running kind 1.19
Istio version 1.9.1
Used `istioctl manifest generate` with the following operator config

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      proxy:
        autoInject: enabled
      useMCP: false
      # The third-party-jwt is not enabled on all k8s.
      # See: https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens
      jwtPolicy: first-party-jwt
    pilot:
      autoscaleMin: 3
      autoscaleMax: 10
      cpu:
        targetAverageUtilization: 60
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: false
    sidecarInjectorWebhook:
      rewriteAppHTTPProbe: true

  meshConfig:
    defaultConfig:
      proxyMetadata:
        TERMINATION_DRAIN_DURATION_SECONDS: "20"

  addonComponents:
    pilot:
      enabled: true

  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          replicaCount: 3
          env:
            - name: 'TERMINATION_DRAIN_DURATION_SECONDS'
              value: '20'
          resources:
            limits:
              cpu: 3000m
              memory: 2048Mi
            requests:
              cpu: 1000m
              memory: 1024Mi
```

**Environment where the bug was observed (cloud vendor, OS, etc)**
Kind 1.19.7
kind config
```
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  image: kindest/node:v1.19.7@sha256:a70639454e97a4b733f9d9b67e12c01f6b0297449d5b9cbbef87473458e26dca
- role: worker
  image: kindest/node:v1.19.7@sha256:a70639454e97a4b733f9d9b67e12c01f6b0297449d5b9cbbef87473458e26dca
# This is needed in order to
# (1) support projected volumes with service account tokens. See
#     https://kubernetes.slack.com/archives/CEKK1KTN2/p1600268272383600
# (2) use a random cluster suffix
kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: ClusterConfiguration
    metadata:
      name: config
    apiServer:
      extraArgs:
        "service-account-issuer": "kubernetes.default.svc"
        "service-account-signing-key-file": "/etc/kubernetes/pki/sa.key"
```

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
