### ISSUE TITLE
1.9.x: HTTP requests intermittently routed locally instead of to the appropriate service

### ISSUE THREAD

**Issue by schantaraud** [istio/istio#31971]
**Bug description**

With Istio 1.9.1 and 1.9.2, a small percentage (~0.02%) of internal HTTP requests (from service A to B in the same mesh, through a common service - see details below) are routed back to the requester (service A) instead of to service B.

Observed in 2 separate clusters/regions. Downgrading Istio to 1.8.4 fixes the issue.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

All internal HTTP requests from service A to B are routed to service B.

**Steps to reproduce the bug**

Simplified configuration:

```
apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    istio-injection: enabled
    name: app
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: app
spec:
  mtls:
    mode: STRICT
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: default
  namespace: app
  labels:
    app: app-api
spec:
  host: "*.app.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: v1
kind: Service
metadata:
  name: app-api
  namespace: app
  labels:
    app: app-api
spec:
  selector:
     app: app-api
  ports:
  - name: http
    port: 8080
    appProtocol: http
---
apiVersion: v1
kind: Service
metadata:
  name: app-api-a
  labels:
    app: app-api
    app-api-resource: a
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    - name: metrics
      port: 15020
      protocol: TCP
      targetPort: 15020
  selector:
    app: app-api
    app-api-resource: a
---
apiVersion: v1
kind: Service
metadata:
  name: app-api-b
  labels:
    app: app-api
    app-api-resource: b
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    - name: metrics
      port: 15020
      protocol: TCP
      targetPort: 15020
  selector:
    app: app-api
    app-api-resource:b
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app
  namespace: app
spec:
  hosts:
  - app.mydomain.com
  - app-api.app.svc.cluster.local
  gateways:
  - istio-system/istio-public-ingressgateway
  - mesh
  http:
  [redacted: other matches]
  - match:
    - uri:
        prefix: /api
    delegate:
       name: app-api
       namespace: app
  - redirect:
        authority: www.mydomain.com
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app-api
  namespace: app
spec:
  http:
  - match:
    - uri:
        prefix: /api/v1/a
    rewrite:
      uri: /a
    route:
    - destination:
        host: app-api-a.app.svc.cluster.local
        port:
          number: 8080
    timeout: 5s
    retries:
      attempts: 0
  - match:
    - uri:
        prefix: /api/v1/b
    rewrite:
      uri: /b
    route:
    - destination:
        host: app-api-b.app.svc.cluster.local
        port:
          number: 8080
    timeout: 5s
    retries:
      attempts: 0
```

- 3-5 pods behind each service
- External user calls service A: `GET https://app.mydomain.com/api/v1/a`
- On each request to service A (received as `GET /a`), service A internally calls service B: `GET http://app-api.app.svc.cluster.local:8080/api/v1/b`
- Most (~99.98%) of the internal requests are routed to service B and received as `GET /b` → 200
- Some (~0.02%) of the internal requests are improperly routed back to the caller (service A) and received as `GET /api/v1/b` → 404

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

Istio 1.9.1, 1.9.2.

```
istioctl version --remote
client version: 1.9.2
control plane version: 1.9.2
data plane version: 1.9.2 (51 proxies)
```

```
kubectl version --short
Client Version: v1.20.4-dirty
Server Version: v1.19.7
```

**How was Istio installed?**

Operator

**Environment where the bug was observed (cloud vendor, OS, etc)**

- AWS
- Kubernetes 1.19.7 (Kops)
- Calico 3.17.2 (bpf, wireguard)
- Ubuntu 20.04 nodes
- *-distroless Istio images
- cert-manager-istio-csr

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
