### ISSUE TITLE
istioctl uninstall fails when I only have gateways

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#31976]
Using external istiod
```
$ istioctl x uninstall -f gateway.yaml
failed to get proxy infos: unable to find any Istiod instances
No resources will be pruned from the cluster. Please double check the input configs

✔ Uninstall complete
```

gateway.yaml:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: gateways
  namespace: istio-system
spec:
  revision: "foo"
  components:
    base:
      enabled: false
    pilot:
      enabled: false
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
    egressGateways:
    - enabled: true
      name: istio-egressgateway
  values:
    gateways:
      istio-ingressgateway:
        injectionTemplate: gateway
      istio-egressgateway:
        injectionTemplate: gateway

```
