### ISSUE TITLE
SIDECAR_OUTBOUND HTTP_FILTER not being applied to HTTPS traffic 

### ISSUE THREAD

**Issue by atoy3731** [istio/istio#32007]
**Bug description**

When applying the following envoyfilter:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: logging-filter 
  namespace: istio-system
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_OUTBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
    patch:
      operation: INSERT_BEFORE
      value: # lua filter specification
        name: envoy.lua
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
          inlineCode: |
            function envoy_on_response(response_handle)
              response_handle:logWarn("envoy_on_response")
            end
```

I would expect proxy logs from istio-injected pods to output `envoy_on_response` for all outbound HTTP and HTTPS requests.

When I exec into a pod and use curl, `http` requests work as expected and I get the log:

```
# curl http://www.google.com
2021-04-07T17:47:53.274738Z	warning	envoy lua	script log: envoy_on_response
```

However, curl requests to `https` yield nothing in the logs.
```
# curl https://www.google.com
# Nothing in proxy logs. :-(
```

[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

HTTPS requests also pass through HTTP_FILTER envoyfilter.

**Steps to reproduce the bug**

1. Install above envoyfilter
2. Tail proxy logs of istio-injected pod with curl installed
3. Exec into Istio-injected pod and curl an HTTPS endpoint
4. Check logs to confirm no output 

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Istio:
```
client version: 1.9.0
control plane version: 1.9.0
data plane version: 1.9.0 (5 proxies)
```
Kubernetes:
```
Client Version: v1.16.4
Server Version: v1.20.2+k3s1
```

**How was Istio installed?**
istioctl install

**Environment where the bug was observed (cloud vendor, OS, etc)**
Proxmox VM
