### ISSUE TITLE
Enable preserve HTTP Header casing

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#32008]
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/header_casing#config-http-conn-man-header-casing

This makes us more transparent, probably a good idea. cc @nrjpoddar

**Comment by su225** [comment]
I would like to work on this. At first glance, as this comes on the cluster side, the changes should be in CDS and we can add new boolean field in `DestinationRule` called `preserverHttpHeaderCasing`. Further, we can add a corresponding field in mesh config for mesh-wide defaults. The one in mesh config should be `false` from backward compatibility perspective. What do you think?

**Comment by nrjpoddar** [comment]
> https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/header_casing#config-http-conn-man-header-casing
> 
> This makes us more transparent, probably a good idea. cc @nrjpoddar

Yes, absolutely! We should at the very least give users a way to configure it and we can debate on the “default” behavior going forward.

**Comment by howardjohn** [comment]
I am not sure we even need an option, on initial thought.. perhaps at the
mesh level, but in destination rule feels wrong if it requires users to set
it for all services. I would be surprised if *not* transforming the casing
could break users but we would need to investigate a bit more

**Comment by su225** [comment]
@howardjohn - Ah! I see your point. At present, **applications which don't care should not be affected by changing header case anyways**. If an app cares about specific casing, then other apps interacting should also comply with casing requirements. It forces all sidecars to preserve the case. So it makes more sense to have it **only at mesh level**.

Coming to default values - In order not to accidentally disturb applications on upgrade, I prefer keeping existing behavior of lower-casing everything as the default.

**Comment by zhongfox** [comment]
hi @howardjohn @ramaraochavali I notice this feature was merged (https://github.com/istio/istio/pull/33030), but then  reverted (https://github.com/istio/istio/pull/33122).

I want to know is there any plan to fix and reopen it ?
and if it's safe that we use envoyfiler to enable this feature?(PreserveCaseFormatterConfig)

**Comment by howardjohn** [comment]
We do not intend to ever merge this feature into Istio, as we have medium
term plans to use HTTP2 ~everywhere and any http2 hop destroys casing.

You can apply EnvoyFilter at your own risk, with the knowledge that it
*will* break sooner or later

**Comment by Adharsh-Muraleedharan** [comment]
@howardjohn @ramaraochavali - I am using the below envoyfilter on istio version 1.9.3 but getting this error "**Http1ProtocolOptionsValidationError.HeaderKeyFormat: ["embedded message failed validation"] | caused by field: "header_format", reason: is required**". How can i avoid this and preserve the request header case ? 
``` apiVersion: networking.istio.io/v1alpha3
 kind: EnvoyFilter
 metadata:
   name: header-casing
   namespace: istio-system
 spec:
   configPatches:
   - applyTo: NETWORK_FILTER
     match:      
       listener:
         filterChain:
           filter:
             name: "envoy.filters.network.http_connection_manager"
     patch:
       operation: MERGE
       value:
         typed_config:
           "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
           http_protocol_options:
             header_key_format:
               stateful_formatter:
                 name: preserve_case
                 typed_config:
                   "@type": type.googleapis.com/envoy.extensions.http.header_formatters.preserve_case.v3.PreserveCaseFormatterConfig

**Comment by ramaraochavali** [comment]
Sorry not sure if 1.9.3 has that support in the proxy shipped. But if your filter looks correct.

**Comment by ningyougang** [comment]
@Adharsh-Muraleedharan 
I tested in my local, after you added below `applyTo: CLUSTER` part, it would wok
```
  - applyTo: CLUSTER
    match:
      context: ANY
    patch:
      operation: MERGE
      value:
        typed_extension_protocol_options:
          envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
            '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
            use_downstream_protocol_config:
              http_protocol_options:
                header_key_format:
                  stateful_formatter:
                    name: preserve_case
                    typed_config:
                      '@type': type.googleapis.com/envoy.extensions.http.header_formatters.preserve_case.v3.PreserveCaseFormatterConfig
```
