### ISSUE TITLE
mTLS in STRICT mode block additional init containers

### ISSUE THREAD

**Issue by elkh510** [istio/istio#32039]
Hi
When STRICT mode is enabled for the mTLS Istio mesh policy all traffic between Pods covered by the policy must use mTLS. This means that the Istio sidecars (istio-proxy Envoy container) must be ready before Pods can successfully communicate with each other over the network. See the Istio Security docs for much information all of this.

The issue with our app right now is that it is using an init container to run database migrations. This init container runs before the regular istio-proxy container on the Pod is ready so there is no client sidecar in place to mediate the mTLS connection with the sidecar running on the database Pod1.

Are there some configuration options within Istio that would help here?
Thanks!

**Comment by howardjohn** [comment]
This is not currently supported today

**Comment by elkh510** [comment]
hi
>This is not currently supported today
are there any plans for the implementation of such functionality? 
or maybe you can suggest some workaround ? 
Thanks!

**Comment by howardjohn** [comment]
https://github.com/istio/istio/issues/11130 tracks long term and has some workarounds. But k8s doesn't allow us to do much here unfortunately.

**Comment by mandarjog** [comment]
@elkh510 do you need to use init containers for that? Can you not put the `db-migration` container as the first container in the list and then use `postStart` lifecycle hook to wait until migration is done?

**Comment by mandarjog** [comment]
@howardjohn why do you say it is not supported? Is the user sets `holdApplicationUntilProxyStarts` then we will ensure `istio-proxy` get read first, followed by `dm-migrate` container, which should now have full access to MTLS etc.
If `dm-migrate` container also uses `postStart` then this is supported today.

The only reason to not do it would be if the privileges needed by `dm-migrate` are more, and they don't want those to be present in running containers.

**Comment by howardjohn** [comment]
It sounds like you are describing a normal container, not an `initContainer`. Perhaps you can hack around it with undocumented implementation details of kubernetes pod startup with postStart hooks, but its not an init container.

**Comment by mandarjog** [comment]
I am asking why does the container have to be init container.
If it does not, then they can just make it a normal
Container with the above changes and it will work.  It is not an api, but the behaviour is unlikely to change without explicit notification.

**Comment by muvaf** [comment]
@howardjohn it seems like https://github.com/istio/istio/issues/11130 tracks the race between application and envoy and somehow making one start only after the other one is ready. However, this issue is specifically about init container's network connection, meaning there is no sidecar running to race or depend on.

**Comment by EronWright** [comment]
Just want to point out that the lack of mTLS for init container traffic also inhibits the use of Istio authorization policies.

**Comment by mohammadsuha** [comment]
i am trying to do some setup by connecting to external service from init-container but i am unable connect to external service in ISTIO strict mode.
i found out about ISTIO CNI so i want to know whether ISTIO CNI will help to resolve the issue?

https://istio.io/latest/docs/setup/additional-setup/cni/#compatibility-with-application-init-containers

in above document it says there are 3 ways we can do it

i want to know whether those 3 ways actually work to resolve the issue?

**Comment by jesuisundev** [comment]
> 

This will work in a permissive MTLS context, not a strict one.

I've found a way to keep the initContainer pattern in a Strict MTLS context tho.
I use a K8s job to make the database migration while the initcontainer is simply waiting for this job to complete.
Since the job will be created with a istio-proxy sidecar in the same pod, the TLS connexion on both side (job and database) will be valid.

The tricky part is to wait for istio-proxy sidecar to be ready on the job pod and wait for the job to finish from the initContainer.

the job
```
apiVersion: batch/v1
kind: Job
metadata:
  name: <name-job>
spec:
  template:
    metadata:
      name: <name-job>
      annotations:
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }' <=== wait for the istio-proxy to be ready
    spec:
      containers:
        - image: <image-job>
          name: <name-job>
          command:
            - "/bin/sh"
            - "-c"
          args:
            - >-
              you-command-to-db-migration
       restartPolicy: OnFailure <==== This will retry the migration if the db is not ready yet for example
```
       
in the deployment
```
initContainers:
  - name: wait-for-db-migration
    image: ghcr.io/groundnuty/k8s-wait-for:v1.6
    imagePullPolicy: Always
    args:
      - "job"
      - "<name-job>"
```

An addtional cluster role / cluster role binding is necessary to check the state of the job from the initContainer.
