### ISSUE TITLE
When using httpsRedirect on Gateway, http requests return http404 if route for port 80 is not present in VirtualService

### ISSUE THREAD

**Issue by JMisset** [istio/istio#32033]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
When using a Gateway that listens on port 80 (http) and port 443 (https), and uses `tls.httpsRedirect: True` for the http port, I would expect that all traffic on port 80 gets redirected to port 443, regardless of routes defined in a VirtualService.
Instead, when the VirtualService only contains HTTPRoutes that match port 443, (and no routes that match port 80), http requests receive an HTTP404 instead of an HTTP301.

**Steps to reproduce the bug**
Define a Gateway and a VirtualService
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: http-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "example.com"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: "example.com-credential"
    hosts:
    - "example.com"

```
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: http-virtualservice
spec:
  hosts:
    - "example.com"
  gateways:
  - http-gateway
  http:
    - name: "http-routes"
      match:
      - port: 443
      route:
        - destination:
            host: exampleService
```

Then go to http://example.com.
In stead of http301 redirecting to https://example.com, you will receive http404.
 
**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Istio:
client version: 1.9.0
control plane version: 1.9.0
data plane version: 1.9.0 (22 proxies)
Kubernetes
Client Version: v1.18.3
Server Version: v1.18.9-eks-d1db3c

**How was Istio installed?**
Using istioctl install -f <manifestfile>

**Environment where the bug was observed (cloud vendor, OS, etc)**
Amazon EKS

If this is expected behaviour, then might I suggest adding a few remarks on this in the documentation for the httpRedirect field.

Regards,
Jasper Misset

**Comment by sridharlreddy** [comment]
@JMisset, This is expected behaviour, redirect will happen only when a matching route is defined. What you are trying to do can be achieved as below but practically there is no benefit as you will hit 404 if there is no route defined for port 443, hence your usecase itself becomes invalid.

@howardjohn Should this be updated in document?

```
spec:
  hosts:
    - "example.com"
  gateways:
  - http-gateway
  http:
    - name: "redirect"
      match:
      - port: 80
      redirect:
        authority: example.com 
    - name: "http-routes"
      match:
      - port: 443
      route:
        - destination:
            host: exampleService

```
