### ISSUE TITLE
Sidecar crd has no effect on ingress gateway

### ISSUE THREAD

**Issue by sunnoy** [istio/istio#32041]
sidecar config is 

```yaml
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: sdkng-sdksvc
  namespace: mid
spec:
  workloadSelector:
    labels:
      app: istio-ingressgateway
  egress:
    - hosts:
      - "mm/abc.mm.svc.cluster.local"
  outboundTrafficPolicy:
    mode: ALLOW_ANY
```
