### ISSUE TITLE
egress-gateway deployment fails on Kubernetes 1.18 when TRUST_DOMAIN is configured

### ISSUE THREAD

**Issue by rolandkool** [istio/istio#32045]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
When deploying Istio egress-gateway on a Kubernetes 1.18 cluster, the installer fails with this error:

> Egress gateways encountered an error: failed to update resource with server-side apply for obj Deployment/istio-egress/istio-egressgateway: failed to create manager for existing fields: failed to convert new object (apps/v1, Kind=Deployment) to smd typed: .spec.template.spec.containers[name="istio-proxy"].env: duplicate entries for key [name="TRUST_DOMAIN"]

This happens when the Istio install values contains a setting for TRUST_DOMAIN

Removing the meshConfig value for TRUST_DOMAIN does not immediately fix it as the deployment is already containing a duplicate entry and a patch doesn't seem to fix it.

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Works on 1.17, should also work on 1.18.

**Steps to reproduce the bug**
The configuration we have for the egress gateway looks like:
```      
      egressGateways:
      - name: istio-egressgateway
        namespace: istio-egress
        enabled: true
        k8s:
          nodeSelector:
            node-class: pool1
          hpaSpec:
            minReplicas: 2
```
The meshconfig looks like.

```
   meshConfig:
       defaultConfig:
         proxyMetadata:
           GCE_METADATA_HOST: "metadata.google.internal"
           TRUST_DOMAIN: "cluster.local"
           CA_PROVIDER: "Citadel"
           PLUGINS: ""
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
ASM 1.9.1, rev 1

**How was Istio installed?**
istioctl.

**Environment where the bug was observed (cloud vendor, OS, etc)**
GKE 1.18

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
