### ISSUE TITLE
No Services in Jaeger UI (Jaeger separate installation)

### ISSUE THREAD

**Issue by Shohou** [istio/istio#32044]
**Bug description**

This might be the same as #31802 or #32026, but I don't use helm for istio or jaeger installation. Istio is installed through IstioOperator and Jaeger through Jaeger operator. Both configs in description. I see no new services except jaeger-query

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
new services appear in Jaeger UI with spans

**Steps to reproduce the bug**

I had Istio already installed by
1. istioctl operator init
2. kubectl create namespace istio-system --dry-run=client -o yaml | kubectl apply -f -
3. kubectl apply -f istio.yaml -n istio-system
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  profile: default

  meshConfig:
    accessLogFile: "/dev/stdout"
    defaultConfig:
      holdApplicationUntilProxyStarts: true
```
4. I installed Jaeger operator and installed Jaeger in a separate namespace "jaeger"
```
apiVersion: jaegertracing.io/v1
kind: "Jaeger"
metadata:
  name: "jaeger-aio"
spec:
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:1.22
    options:
      log-level: trace
      query:
        base-path: /jaeger
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 256Mi
  storage:
    options:
      memory:
        max-traces: 100000
  ingress:
    enabled: false
```
5. Then I modified IstioOperator to enable tracing
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  profile: default

  meshConfig:
    enableTracing: true
    accessLogFile: "/dev/stdout"
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      tracing:
        sampling: 100.0
        zipkin:
          address: jaeger-aio-collector.jaeger.svc.cluster.local:9411
```
Unfortunately in Jaeger UI I see only one service jaeger-query. I tried deleting pods for istio-ingressgateway, istiod, applications, and they was recreated from deployments, but whatever I do I see no new services

I tried `k exec your-app-pod -c istio-proxy -- curl -X POST localhost:15000/logging?tracing=trace` to istio-ingressgateway, and adding `sidecar.istio.io/componentLogLevel: tracing:trace` to my app. I see in logs
```
istio-proxy 2021-04-08T14:42:46.684184Z    info    Apply proxy config from env {"tracing":{"zipkin":{"address":"jaeger-aio-collector.jaeger.svc.cluster.local:9411"},"sampling":100},"holdApplicationUntilProxyStarts":true}

istio-proxy tracing:                                                                                                                                                                       
istio-proxy   sampling: 100                                                                                                                                                                istio-proxy   zipkin:                                                                                                                                                                      
istio-proxy     address: jaeger-aio-collector.jaeger.svc.cluster.local:9411

istio-proxy 2021-04-08T14:42:46.991074Z    info    envoy tracing    instantiating a new tracer: envoy.tracers.zipkin
```
Tracing related parts of bootstrap
```
                   "PROXY_CONFIG": {
                                "binaryPath": "/usr/local/bin/envoy",
                                "concurrency": 2,
                                "configPath": "./etc/istio/proxy",
                                "controlPlaneAuthPolicy": "MUTUAL_TLS",
                                "discoveryAddress": "istiod.istio-system.svc:15012",
                                "drainDuration": "45s",
                                "holdApplicationUntilProxyStarts": true,
                                "parentShutdownDuration": "60s",
                                "proxyAdminPort": 15000,
                                "serviceCluster": "api-app.default",
                                "statNameLength": 189,
                                "statusPort": 15020,
                                "terminationDrainDuration": "5s",
                                "tracing": {
                                            "sampling": 100,
                                            "zipkin": {
                                                        "address": "jaeger-aio-collector.jaeger.svc.cluster.local:9411"
                                                    }
                                        }
                            },

            "clusters": [
                {
                    "name": "zipkin",
                    "type": "STRICT_DNS",
                    "connectTimeout": "1s",
                    "loadAssignment": {
                        "clusterName": "zipkin",
                        "endpoints": [
                            {
                                "lbEndpoints": [
                                    {
                                        "endpoint": {
                                            "address": {
                                                "socketAddress": {
                                                    "address": "jaeger-aio-collector.jaeger.svc.cluster.local",
                                                    "portValue": 9411
                                                }
                                            }
                                        }
                                    }
                                ]
                            }
                        ]
                    },
                    "dnsRefreshRate": "30s",
                    "respectDnsTtl": true,
                    "dnsLookupFamily": "V4_ONLY"
                }
            ]


        "tracing": {
            "http": {
                "name": "envoy.tracers.zipkin",
                "typedConfig": {
                    "@type": "type.googleapis.com/envoy.config.trace.v3.ZipkinConfig",
                    "collectorCluster": "zipkin",
                    "collectorEndpoint": "/api/v2/spans",
                    "traceId128bit": true,
                    "sharedSpanContext": false,
                    "collectorEndpointVersion": "HTTP_JSON"
                }
            }
        },
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
$ istioctl version --remote
client version: 1.9.1
control plane version: 1.9.1
data plane version: 1.9.1 (21 proxies)
```
```
$ kubectl version --short
Client Version: v1.19.7
Server Version: v1.20.5-34+40f5951bd9888a
```

**Environment where the bug was observed (cloud vendor, OS, etc)**
I use microk8s

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by Shohou** [comment]
So the reason was that I installed jaeger-operator from helm chart which had version 1.21 and set jaeger image version to 1.22 and from changelog it has new name for parameter for zipkin port, so old operator couldn't set it for new image and so zipkin was disabled... doh

**Comment by tampler** [comment]
Hello I'm having exactly the same issue... I did the following:

1. Download istioctl v.1.10.0
2. Install Jaeger Operator from [docs](https://www.jaegertracing.io/docs/1.22/getting-started/)
3. Installed Jaeger with the following config:
```yaml
---
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-aoi
spec:
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:1.23
    options:
      log-level: debug
      query:
        base-path: /jaeger
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 64Mi
  storage:
    options:
      memory:
        max-traces: 10000
  ingress:
    enabled: false
```
4. istioctl operator init --watchedNamespaces=istio-system
5. Installed Istio WITH tracing enabled with this:
```yaml
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-control-plane
spec:
  profile: default
  components:
    pilot:
      k8s:
        env:
          - name: PILOT_HTTP10
            value: "1"
  meshConfig:
    accessLogFile: "/dev/stdout"
    enableTracing: true
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      tracing:
        sampling: 100.0
        max_path_tag_length: 256
        zipkin:
          address: jaeger-aio-collector.observability.svc.cluster.local:9411
```
6. Validated successful Istio setup with `istioctl verify-install`
7. Deployed a bookinfo app from [here](https://istio.io/latest/docs/examples/bookinfo/)
8. Sent and verified traffic to be traced from [here](https://istio.io/latest/docs/tasks/observability/distributed-tracing/jaeger/)
9. Now I open the Jaeger gui with `kubectl port-forward svc/jaeger-aoi-query 16686 -n observability` and find only `jaeger-query` service

Debug:
1. Validated istio injection in the bookinfo namespace
2. Validated PROXY_CONFIG for bookinfo/productpage pod: 
`PROXY_CONFIG:                  {"tracing":{"zipkin":{"address":"jaeger-aio-collector.observability.svc.cluster.local:9411"},"maxPathTagLength":256,"sampling":100},"holdApplicationUntilProxyStarts":true}`
3. `k exec your-app-pod -c istio-proxy -- curl -X POST localhost:15000/logging?tracing=trace` - I see traces and 200s in the productpage logs
4. Run `for i in $(seq 1 100); do curl -s -o /dev/null "http://$GATEWAY_URL/productpage"; done` again
5. I checked Jaeger Pod logs and I see that it doesn't get traces. I see only few traces from its own `jaeger-query` service

Any clues how to debug this?

Thanks!

**Comment by chadlwilson** [comment]
@tampler As for @Shohou 's problem, I believe the problem is Jaeger itself. More recent versions appear to require you to specifically enable the Zipkin-format collector port on `9411`. Note that their docs have a specific arg to set this now.


We had this issue when upgrading to Jaeger `1.22` independent of any Istio change.

Try with
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-aoi
spec:
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:1.23
    options:
      log-level: debug
      query:
        base-path: /jaeger
      collector: # <--- See here
        zipkin:
          host-port: 9411
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 64Mi
  storage:
    options:
      memory:
        max-traces: 10000
  ingress:
    enabled: false
```
