### ISSUE TITLE
Istio-cni forcibly replaced the cni version of existing plugins to 0.3.1

### ISSUE THREAD

**Issue by stanxing** [istio/istio#32137]
**Bug description**

istio-cni deleted the cni version  of the existing plugin when merging istio cni plugin to chained plugins even if they have different cni versions. [here is code link](https://github.com/istio/istio/blob/8cb305701d59a88a56c4c3d1acecdabe91d77aba/cni/pkg/install-cni/pkg/install/cniconfig.go#L291).

My source cni config file is as below:

```json
// 10-terway.conf
    {
      "cniVersion": "0.3.0",
      "name": "terway",
      "type": "terway"
    }
```

after installing instio-cni,  cni config was changed as below: 

```json
// 10-terway.conflist
{
    "plugins": [
        {
            "name": "terway",
            "type": "terway",
        },
        {
            "name": "istio-cni",
            "type": "istio-cni",
            "log_level": "debug",
            "kubernetes": {
                "kubeconfig": "/etc/cni/net.d/ZZZ-istio-cni-kubeconfig",
                "cni_bin_dir": "/opt/cni/bin",
                "exclude_namespaces": [
                    "istio-system",
                    "kube-system"
                ]
            }
        }
    ],
    "name": "k8s-pod-network",
    "cniVersion": "0.3.1"
}
```
Unfortunately, [terway](https://github.com/AliyunContainerService/terway/issues/190) does not support the version of 0.3.1 currently so that kublet throw the error in logs.

![image](https://user-images.githubusercontent.com/23288646/114497708-4e9d0a80-9c55-11eb-8b55-aee25317d6e0.png)

Maybe istio-cni should  keep respective cni version when merging mulitple cni plugins. But I am not sure if cni spec is allowed to do that. I also open a [issue](https://github.com/containernetworking/cni/issues/832) for that.

[x] Networking

**Expected behavior**

istio-cni can keep respective cni version when merging mulitple cni plugins.

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
client version: 1.9.2
control plane version: 1.9.2
data plane version: 1.9.2 (2 proxies)
kubernetes: 1.18
```

**How was Istio installed?**

```yaml
# operator-cni-1.9.2.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-control-plane
spec:
  profile: demo
  components:
    cni:
      enabled: true
      namespace: kube-system
  values:
    cni:
      excludeNamespaces:
       - istio-system
       - kube-system
      logLevel: debug
      chained: true
```
istioctl install -f operator-cni-1.9.2.yaml

**Environment where the bug was observed (cloud vendor, OS, etc)**

cloud vendor: Aliyun ACK
