### ISSUE TITLE
Unable to round-trip http request to upstream: read tcp 192.168.198.1:64026->192.168.198.154:30986: wsarecv: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#32199]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
Unable to round-trip http request to upstream: read tcp 192.168.198.1:64026->192.168.198.154:30986: wsarecv: An existing connection was forcibly closed by the remote host.
after add configuation
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: proxy-protocol
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: LISTENER
    patch:
      operation: MERGE
      value:
        listener_filters:
        - name: envoy.filters.listener.proxy_protocol
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.listener.proxy_protocol.v3.ProxyProtocol
        - name: envoy.filters.listener.tls_inspector
```
listener config 
[a.txt](https://github.com/istio/istio/files/6316822/a.txt)

[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
can accesss
**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
[root@master01 envoyfilters]# istioctl version --remote
client version: 1.9.2
control plane version: 1.9.2
data plane version: 1.9.2 (17 proxies)

[root@master01 envoyfilters]# kubectl version --short
Client Version: v1.20.5
Server Version: v1.20.5

**How was Istio installed?**
istioctl install --set profile=demo
**Environment where the bug was observed (cloud vendor, OS, etc)**

[root@master01 envoyfilters]# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
