### ISSUE TITLE
credentialName in destination rule

### ISSUE THREAD

**Issue by yalctay93** [istio/istio#32202]
Hello,

according to the istio 1.9 documentation, the field "credentialName" is only applicable for gateways.
Is there a reason why that field is not used at destination rule? I'd like to specify a k8s secret istead of doing filemounts into the istio-ingressgateway.

for example:

DestinationRule
```yaml
        portLevelSettings:
        - port:
            number: 666
          tls:
            mode: MUTUAL
            credentialName: credential.name (k8s secret)
            sni: test.test.com
            subjectAltNames:
            - test.test.com
```

Whenever I deploy a destionationrule like this, I get the istioctl analyze error that I cannot specify tls mode Mutual without providing a caCertificate. 

Is there a roadmap as to when the field "credentialName" will be supported in kind DestinationRule?
According to https://github.com/istio/istio/issues/24908 it should be available since istio 1.7 (we are using 1.9 version)

Thanks!
