### ISSUE TITLE
projected secrets have bad permissions using defaultMode with sidecar

### ISSUE THREAD

**Issue by daveoy** [istio/istio#32217]
**Bug description**

when projecting secrets into a deployment from a volume and using the defaultMode setting, it appears the permissions are always adding group read and a dodgy group inside the workload container when sidecar injection is taking place. this causes issues with things like ssh and git where strict file permissions are required for operation.

**Expected behavior**

i expect to enable sidecar injection without having to modify my application workload

**Steps to reproduce the bug**

1. configure application to use secrets from a volume with defaultMode specified.
2. add sidecar
3. file permissions are overridden with group ownership and mode bits modified

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

kubernetes 1.20, istio 1.8

**How was Istio installed?**

helm 3

**Environment where the bug was observed (cloud vendor, OS, etc)**

kubeadm cluster

deployment yaml:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: r10k-webhook
  namespace: foreman-proxy
spec:
  selector:
    matchLabels:
      app: r10k-webhook
  replicas: 1
  template:
    metadata:
      name: r10k-webhook
      labels:
        app: r10k-webhook
        role: r10k-webhook
      annotations:
        sidecar.istio.io/inject: "false"
      namespace: foreman-proxy
    spec:
        volumes:
          - name: foreman-proxy-config
            configMap:
              name: foreman-proxy-config
          - name: puppet-code
            nfs:
              server: {{ .Values.storage.server }}
              path: {{ .Values.storage.path }}/puppet-code/
          - name: known-hosts
            secret:
              secretName: known-hosts
              defaultMode: 0640
          - name: ssh-id
            secret:
              secretName: ssh-id
              defaultMode: 0400
          - name: ssh-id-pub
            secret:
              secretName: ssh-id-pub
              defaultMode: 0644
          - name: ssh-config
            secret:
              secretName: ssh-config
              defaultMode: 0600
        containers:
        - name: r10k-webhook
          image: {{ .Values.webhookReceiver.image }}
          env:
          - name: REACT_APP_MILL_SITE
            value: {{ .Values.site.short }}
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
              name: r10k-webhook
          volumeMounts:
            - mountPath: /root/.ssh/known_hosts
              subPath: known-hosts
              name: known-hosts
            - mountPath: /root/.ssh/config
              subPath: config
              name: ssh-config
            - mountPath: /root/.ssh/id_rsa.pub
              subPath: id_rsa.pub
              name: ssh-id-pub
            - mountPath: /root/.ssh/id_rsa
              subPath: id_rsa
              name: ssh-id
            - mountPath: /etc/hosts
              subPath: etc-hosts-{{ .Values.site.short }}
              name: foreman-proxy-config
            - mountPath: /code
              name: puppet-code
            - mountPath: /r10k.yaml
              subPath: r10k-config
              name: foreman-proxy-config
```
file permissions without sidecar:
```
root@puppet:/# ls -al /root/.ssh/
total 12
drwxr-xr-x 2 root root   57 Apr 15 20:10 .
drwx------ 1 root root   18 Apr 15 20:10 ..
-rw------- 1 root root 1679 Apr 15 20:10 id_rsa
-rw-r--r-- 1 root root  400 Apr 15 20:10 id_rsa.pub
-rw-r--r-- 1 root root  831 Apr 15 20:10 known_hosts
```
file permissions with sidecar:
```
root@puppet:~# cd /root/.ssh
root@puppet:~/.ssh# ls -al
total 12
drwxr-xr-x 2 root root   57 Apr 15 15:46 .
drwx------ 1 root root   18 Apr 15 15:46 ..
-rw-r----- 1 root 1337 1679 Apr 15 15:46 id_rsa
-rw-r--r-- 1 root 1337  400 Apr 15 15:46 id_rsa.pub
-rw-r--r-- 1 root 1337  831 Apr 15 15:46 known_hosts
```
