### ISSUE TITLE
Support fragmented VirtualService Host merging

### ISSUE THREAD

**Issue by alecor191** [istio/istio#32229]
**Describe the feature request**
According to [Istio Documentation](https://istio.io/latest/docs/ops/best-practices/traffic-management/#split-virtual-services) it's possible to split `VirtualService` into multiple resources. However, according to that doc, this is not supported to merge Hosts:

> A VirtualService can only be fragmented this way if it is bound to a gateway. Host merging is not supported in sidecars.

The problem I'm trying to solve is quite straight forward: I want to deploy one or more canary releases of my services side-by-side to the "production" version of the service. It should be possible to "helm uninstall" any of the canary releases at any time.

Here an example:

1. Deploy a Helm chart that contains deployments, destinationrules, virtualservices. The VirtualService looks like this:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  ...
spec:
  hosts:
    - myservice.mynamespace.svc.cluster.local
  http:
    - route:
        - destination:
            host: myservice.mynamespace.svc.cluster.local
            port:
              number: 80
            subset: production
```

2. Deploy the Helm chart a second time with a 'canary' parameter: The Helm chart should deploy the deployment, destinationrule, virtualservice with canary definition. The VirtualService looks as follows for canary releases:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  ...
spec:
  hosts:
    - myservice.mynamespace.svc.cluster.local
  http:
    - match:
        - headers:
            use-canary:
              exact: "true"
      route:
        - destination:
            host: myservice.mynamespace.svc.cluster.local
            port:
              number: 80
            subset: canary
```

The problem is that Istio is currently not able to merge the two VirtualServices above. If I deploy a VirtualService that contains both of the above, everything works fine. But I would need a solution where I have 2 Helm charts and I can install/uninstall them independently. Having a shared `VirtualService` isn't really an option.

**Describe alternatives you've considered**
- Have the VirtualService outside the Helm chart. This seems cumbersome and error prone as every canary deployment needs to update + apply the VirtualService (incl. when uninstalling Helm charts).
- Have only a single Helm chart that contains 1 VirtualService and multiple deployments (one deployment per canary release). This is also cumbersome and adds a lot of coupling.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[X] Developer Infrastructure

**Additional context**
