### ISSUE TITLE
Service Mesh can't through the dedicated outbound when service port not equal  targetPort

### ISSUE THREAD

**Issue by EugeneCI** [istio/istio#32231]
**Bug description**

We have a situation when service port and targetPort is different, the request in the service mesh goes through the PassthroughCluster instead of the dedicated outbound . But if the request is from the istio gateway, it is normal.

**Affected product area**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features**

**Expected behavior**

All requests to "gqc-my-home-crd.crd-test.svc.cluster.local" goes through the mesh.

**Steps to reproduce the bug**
1. Start pod&service in a namespace with sidecar injection enabled  
service yaml:  
    ```yaml
    apiVersion: v1
    kind: Service
    metadata:
      labels:
        app.kubernetes.io/instance: gqc-my-home-crd
        app.kubernetes.io/name: gqc-my-home-crd
      name: gqc-my-home-crd
      namespace: crd-test
    spec:
      clusterIP: 10.217.22.206
      ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: http #8220
      selector:
        app.kubernetes.io/instance: gqc-my-home-crd
        app.kubernetes.io/name: gqc-my-home-crd
      sessionAffinity: None
      type: ClusterIP
    ```
2. Config  DestinationRule&VirtualService:
    ```yaml
    kind: DestinationRule
    apiVersion: networking.istio.io/v1alpha3
    metadata:  
      labels:
        app.kubernetes.io/instance: gqc-my-home-crd
        app.kubernetes.io/name: gqc-my-home-crd
      name: gqc-my-home-crd
      namespace: crd-test  
    spec:
      host: gqc-my-home-crd
      subsets:
        - labels:
            version: default
          name: default
        - labels:
            version: v2
          name: v2
    ---
    apiVersion: networking.istio.io/v1alpha3
    kind: VirtualService
    metadata:
      labels:
        app.kubernetes.io/instance: gqc-my-home-crd
        app.kubernetes.io/name: gqc-my-home-crd
      name: gqc-my-home-crd
      namespace: crd-test
    spec:
      hosts:
        - gqc-my-home-crd.crd-test.svc.cluster.local
      http:
        - match:
            - headers:
                x-project:
                  exact: v2
          route:
            - destination:
                host: gqc-my-home-crd.crd-test.svc.cluster.local
                subset: v2
              headers:
                request:
                  add:
                    x-project: v2
                response:
                  add:
                    x-project: v2
        - route:
            - destination:
                host: gqc-my-home-crd.crd-test.svc.cluster.local
                subset: default
              headers:
                request:
                  add:
                    x-project: default
                response:
                  add:
                    x-project: default
              weight: 100
    ```
3. Wait until the pod is READY
4. Verify the istio-proxy container is up and running
5. in other namespace pod (sidecar injection enabled),use curl to send rquest[GET]
    ###### CURL LOG
    ```
    [root@gqc-log-85b477456b-nsfvk Log]# curl -v http://gqc-my-home-crd.crd-test/faq
    * About to connect() to gqc-my-home-crd.crd-test port 80 (#0)
    *   Trying 10.217.22.206...
    * Connected to gqc-my-home-crd.crd-test (10.217.22.206) port 80 (#0)
    > GET /faq HTTP/1.1
    > User-Agent: curl/7.29.0
    > Host: gqc-my-home-crd.crd-test
    > Accept: */*
    >
    < HTTP/1.1 200 OK
    < x-server-id: GQC-Server
    < x-faq-servicehost: http://172.16.168.84:3000
    < date: Fri, 16 Apr 2021 08:38:35 GMT
    < content-length: 4
    < x-envoy-upstream-service-time: 35
    < server: envoy
    <
    * Connection #0 to host gqc-my-home-crd.crd-test left intact
    true
    ```
    ###### ISTIO-PROXY ACCESS LOG

    ```
    [2021-04-16T08:38:35.729Z] "GET /faq HTTP/1.1" 200 - via_upstream - "-" 0 4 37 35 "-" "curl/7.29.0" "ddab2953-9d64-98c4-958c-5b910e6c8e3a" "gqc-my-home-crd.crd-test" "10.216.9.177:8220" PassthroughCluster 10.216.12.233:59668 10.216.9.177:8220 10.216.12.233:59666 - allow_any
    ```
     Highlights:
    - Header is not added
    - Mesh goes through the PassthroughCluster

 6.  If i change k8s service port to 8220  
```yaml
  ports:
      - name: http
        port: 8220
        protocol: TCP
        targetPort: http  #8220
```

7. Use curl to send rquest[GET]
    ###### CURL LOG
    ```
    [root@gqc-logx-85b477456b-nsfvk Log]# curl -v http://gqc-my-home-crd.crd-test:8220/faq
    * About to connect() to gqc-my-home-crd.crd-test port 8220 (#0)
    *   Trying 10.217.22.206...
    * Connected to gqc-my-home-crd.crd-test (10.217.22.206) port 8220 (#0)
    > GET /faq HTTP/1.1
    > User-Agent: curl/7.29.0
    > Host: gqc-my-home-crd.crd-test:8220
    > Accept: */*
    >
    < HTTP/1.1 200 OK
    < x-server-id: GQC-Server
    < x-faq-servicehost: http://172.16.168.84:3000
    < date: Fri, 16 Apr 2021 08:46:32 GMT
    < content-length: 4
    < x-envoy-upstream-service-time: 47
    < server: envoy
    < x-project: default
    <
    * Connection #0 to host gqc-my-home-crd.crd-test left intact
    true

    ```
    ###### ISTIO-PROXY ACCESS LOG

    ```
    [2021-04-16T08:46:32.701Z] "GET /faq HTTP/1.1" 200 - via_upstream - "-" 0 4 49 47 "-" "curl/7.29.0" "6ed948f6-0d15-944f-8820-0785766ceeba" "gqc-my-home-crd.crd-test:8220" "10.216.13.224:8220" outbound|8220|default|gqc-my-home-crd.crd-test.svc.cluster.local 10.216.12.233:48176 10.216.9.177:8220 10.216.12.233:41816 - -
    ```
     Highlights:
    - Header "x-project" is added
    - mesh goes through the outbound
    
8.  It works (only port = targetPort can work )
9. Check Envoy Config 
  This is the config of Port 80, and there is no difference in the config of Port 8220.  
    ```json
    {
    "name": "gqc-my-home-crd.crd-test.svc.cluster.local:80",
    "domains": [
      "gqc-my-home-crd.crd-test.svc.cluster.local",
      "gqc-my-home-crd.crd-test.svc.cluster.local:80",
      "gqc-my-home-crd",
      "gqc-my-home-crd:80",
      "gqc-my-home-crd.crd-test.svc.cluster",
      "gqc-my-home-crd.crd-test.svc.cluster:80",
      "gqc-my-home-crd.crd-test.svc",
      "gqc-my-home-crd.crd-test.svc:80",
      "gqc-my-home-crd.crd-test",
      "gqc-my-home-crd.crd-test:80",
      "10.217.22.206",
      "10.217.22.206:80"
    ],
    "routes": [
      {
       "match": {
        "prefix": "/",
        "case_sensitive": true,
        "headers": [
         {
          "name": "x-project",
          "exact_match": "v2"
         }
        ]
       },
       "route": {
        "cluster": "outbound|80|v2|gqc-my-home-crd.crd-test.svc.cluster.local",
        "timeout": "0s",
        "retry_policy": {
         "retry_on": "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes",
         "num_retries": 2,
         "retry_host_predicate": [
          {
           "name": "envoy.retry_host_predicates.previous_hosts"
          }
         ],
         "host_selection_retry_max_attempts": "5",
         "retriable_status_codes": [
          503
         ]
        },
        "max_stream_duration": {
         "max_stream_duration": "0s"
        }
       },
       "metadata": {
        "filter_metadata": {
         "istio": {
          "config": "/apis/networking.istio.io/v1alpha3/namespaces/crd-test/virtual-service/gqc-my-home-crd"
         }
        }
       },
       "decorator": {
        "operation": "gqc-my-home-crd.crd-test.svc.cluster.local:80/*"
       },
       "request_headers_to_add": [
        {
         "header": {
          "key": "x-project",
          "value": "v2"
         },
         "append": true
        }
       ],
       "response_headers_to_add": [
        {
         "header": {
          "key": "x-project",
          "value": "v2"
         },
         "append": true
        }
       ]
      },
      {
       "match": {
        "prefix": "/"
       },
       "route": {
        "cluster": "outbound|80|default|gqc-my-home-crd.crd-test.svc.cluster.local",
        "timeout": "0s",
        "retry_policy": {
         "retry_on": "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes",
         "num_retries": 2,
         "retry_host_predicate": [
          {
           "name": "envoy.retry_host_predicates.previous_hosts"
          }
         ],
         "host_selection_retry_max_attempts": "5",
         "retriable_status_codes": [
          503
         ]
        },
        "max_stream_duration": {
         "max_stream_duration": "0s"
        }
       },
       "metadata": {
        "filter_metadata": {
         "istio": {
          "config": "/apis/networking.istio.io/v1alpha3/namespaces/crd-test/virtual-service/gqc-my-home-crd"
         }
        }
       },
       "decorator": {
        "operation": "gqc-my-home-crd.crd-test.svc.cluster.local:80/*"
       },
       "request_headers_to_add": [
        {
         "header": {
          "key": "x-project",
          "value": "default"
         },
         "append": true
        }
       ],
       "response_headers_to_add": [
        {
         "header": {
          "key": "x-project",
          "value": "default"
         },
         "append": true
        }
       ]
      }
    ],
    "include_request_attempt_count": true
    },
    ```

**Version** 
```
$ bin/istioctl version --remote
client version: 1.9.2
control plane version: 1.9.2
data plane version: 1.9.2 (24 proxies)

$ kubectl version --short
Client Version: v1.20.0
Server Version: v1.19.8

cilium version: 1.9.5 
    loadBalancer.mode=hybrid 
    hostServices.enabled=true
    kubeProxyReplacement=strict
    ...
```

**How was Istio installed?**
IstioOperator  
```yaml
kind: IstioOperator
apiVersion: install.istio.io/v1alpha1
metadata:
  name: installed-state
  namespace: istio-system
spec:
  components:
    base:
      enabled: true
    cni:
      enabled: true
    egressGateways:
      - enabled: false
        name: istio-egressgateway
    ingressGateways:
      - enabled: true
        name: istio-ingressgateway
    istiodRemote:
      enabled: false
    pilot:
      enabled: true
  hub: docker.io/istio
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      proxyMetadata: {}
      tracing:
        sampling: 100
        zipkin:
          address: 'jaeger-collector.kube-event:9411'
    enablePrometheusMerge: true
  profile: default
  tag: 1.9.2
  values:
    base:
      enableCRDTemplates: false
      validationURL: ''
    gateways:
      istio-egressgateway:
        autoscaleEnabled: true
        env: {}
        name: istio-egressgateway
        secretVolumes:
          - mountPath: /etc/istio/egressgateway-certs
            name: egressgateway-certs
            secretName: istio-egressgateway-certs
          - mountPath: /etc/istio/egressgateway-ca-certs
            name: egressgateway-ca-certs
            secretName: istio-egressgateway-ca-certs
        type: ClusterIP
        zvpn: {}
      istio-ingressgateway:
        autoscaleEnabled: true
        env: {}
        name: istio-ingressgateway
        secretVolumes:
          - mountPath: /etc/istio/ingressgateway-certs
            name: ingressgateway-certs
            secretName: istio-ingressgateway-certs
          - mountPath: /etc/istio/ingressgateway-ca-certs
            name: ingressgateway-ca-certs
            secretName: istio-ingressgateway-ca-certs
        type: LoadBalancer
        zvpn: {}
    global:
      arch:
        amd64: 2
        ppc64le: 2
        s390x: 2
      configValidation: true
      defaultNodeSelector: {}
      defaultPodDisruptionBudget:
        enabled: true
      defaultResources:
        requests:
          cpu: 10m
      imagePullPolicy: ''
      imagePullSecrets: []
      istioNamespace: istio-system
      istiod:
        enableAnalysis: false
      jwtPolicy: third-party-jwt
      logAsJson: false
      logging:
        level: 'default:info'
      meshNetworks: {}
      mountMtlsCerts: false
      multiCluster:
        clusterName: ''
        enabled: false
      network: ''
      omitSidecarInjectorConfigMap: false
      oneNamespace: false
      operatorManageWebhooks: false
      pilotCertProvider: istiod
      priorityClassName: ''
      proxy:
        autoInject: enabled
        clusterDomain: cluster.local
        componentLogLevel: 'misc:error'
        enableCoreDump: false
        excludeIPRanges: ''
        excludeInboundPorts: ''
        excludeOutboundPorts: ''
        image: proxyv2
        includeIPRanges: '*'
        logLevel: warning
        privileged: true
        readinessFailureThreshold: 30
        readinessInitialDelaySeconds: 1
        readinessPeriodSeconds: 2
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        statusPort: 15020
        tracer: zipkin
      proxy_init:
        image: proxyv2
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 10m
            memory: 10Mi
      sds:
        token:
          aud: istio-ca
      sts:
        servicePort: 0
      tracer:
        datadog: {}
        lightstep: {}
        stackdriver: {}
        zipkin: {}
      useMCP: false
    istiodRemote:
      injectionURL: ''
    pilot:
      autoscaleEnabled: true
      autoscaleMax: 5
      autoscaleMin: 1
      configMap: true
      cpu:
        targetAverageUtilization: 80
      enableProtocolSniffingForInbound: true
      enableProtocolSniffingForOutbound: true
      env:
        ENABLE_LEGACY_FSGROUP_INJECTION: false
      image: pilot
      keepaliveMaxServerConnectionAge: 30m
      nodeSelector: {}
      replicaCount: 1
      traceSampling: 1
    telemetry:
      enabled: true
      v2:
        enabled: true
        metadataExchange:
          wasmEnabled: false
        prometheus:
          enabled: true
          wasmEnabled: false
        stackdriver:
          configOverride: {}
          enabled: false
          logging: false
          monitoring: false
          topology: false
```
**Environment where the bug was observed (cloud vendor, OS, etc)**
Private kubernetes cluster

##### I got this issue after using cilium& upgrade istio, VirtualService was normal before,so I don’t know if it is caused by a configuration error or a bug .
