### ISSUE TITLE
[release-1.8.0]  virtualservice is not valid

### ISSUE THREAD

**Issue by hmthoo** [istio/istio#32259]
The following configuration is ok .
```
# See more at https://istio.io/blog/2017/0.1-canary/
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sophon
  namespace: canary
spec:
  hosts:
  - sophon-service 
  http:
  - match:
    - sourceLabels:
        version: v2
    route:
    - destination:
        host: sophon-service.canary.svc.cluster.local
        subset: v2
  - route:
    - destination:
        host: sophon-service.canary.svc.cluster.local
        subset: v1
```

The following configuration is not vaild.   
other server v1 Incoming traffic is forwarded to v2 

```
# See more at https://istio.io/blog/2017/0.1-canary/
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: trisolaris
  namespace: canary
spec:
  hosts:
  - trisolaris-service
  http:
  - match:
    - sourceLabels:
        version: v2
    route:
    - destination:
        host: trisolaris-service.canary.svc.cluster.local
        subset: v2
  - route:
    - destination:
        host: trisolaris-service.canary.svc.cluster.local
        subset: v1
```

Is there any way to troubleshoot this problem.  thanks.
