### ISSUE TITLE
pass upgrade_configs parameters to envoy

### ISSUE THREAD

**Issue by rtttech** [istio/istio#32264]
The following is a config file works for envoy. The key part is the "upgrade_configs" param after route item. Can I set the "upgrade_configs" param to VirtualService as a item of route?

This configuration terminates a POST request and sends the POST payload upstream.
It can be used to test TCP tunneling as described in docs/root/intro/arch_overview/http/upgrades.rst

```yaml
admin:
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9902
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 127.0.0.1
        port_value: 10001
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
                - "*"
              routes:
                - match:
                    prefix: "/"
                    headers:
                      - name: ":method"
                        exact_match: "POST"
                  route:
                    cluster: test_service
                    upgrade_configs:
                      - upgrade_type: CONNECT
                        connect_config:
                          allow_post: true
          http_filters:
          - name: envoy.filters.http.router
  clusters:
  - name: test_service
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: test_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8888
```
