### ISSUE TITLE
Ingress gateway access log - wrong requested_server_name

### ISSUE THREAD

**Issue by ediezh** [istio/istio#32271]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

The istio ingress gateway access log has wrong `requested_server_name`. Example log below:
```
{
  "upstream_cluster": "outbound|8080||jenkins.cicd.svc.cluster.local",
  "downstream_remote_address": "10.0.1.43:57961",
  "authority": "jenkins.example.com",
  "path": "/job/build-node-base-image/wfapi/runs?since=%2315(master)&fullStages=true&_=1618817993157",
  "protocol": "HTTP/2",
  "upstream_service_time": "1",
  "upstream_local_address": "10.202.37.10:55052",
  "duration": "1",
  "upstream_transport_failure_reason": "-",
  "route_name": "http",
  "downstream_local_address": "10.202.37.10:8443",
  "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36",
  "response_code": "200",
  "response_flags": "-",
  "start_time": "2021-04-19T08:29:23.180Z",
  "method": "GET",
  "request_id": "6e02288a-e2e9-9dea-8f2f-2a8376feac59",
  "upstream_host": "10.202.39.30:8080",
  "x_forwarded_for": "10.0.1.43",
  "requested_server_name": "argocd.example.com",
  "bytes_received": "0",
  "istio_policy_status": "-",
  "bytes_sent": "5741"
}
```

Note that the `requested_server_name = "argocd.example.com"`. But `authority = "jenkins.example.com"` and `upstream_cluster = "outbound|8080||jenkins.cicd.svc.cluster.local"`.

The only correlation is that `argocd.example.com` and `jenkins.example.com` are defined in the same ingress gateway.

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: internal-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway-internal
  servers:
  - hosts:
    - argocd.example.com
    - jenkins.example.com
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - argocd.example.com
    - jenkins.example.com
    port:
      name: https-shared
      number: 443
      protocol: HTTPS
    tls:
      credentialName: example-com-wildcard-cert
      minProtocolVersion: TLSV1_2
      mode: SIMPLE
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

The access log has correct `requested_server_name` recorded.

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.7.6

**How was Istio installed?**
istio operator

**Environment where the bug was observed (cloud vendor, OS, etc)**

EKS 1.7

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
