### ISSUE TITLE
No response code on ingressgateway

### ISSUE THREAD

**Issue by jaronoff97** [istio/istio#32289]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

We are using istio behind an AWS NLB and are seeing that many of our connections in our production environment are responding with `0` response code to clients of our application. Below is an example access log we see consistently:

```	json
{
  "referer": "XXXXXXXXXXXXXXXXXX",
  "response_duration": null,
  "bytes_sent": 0,
  "upstream_cluster": "outbound|8000||ourapp.ourapp.svc.cluster.local",
  "downstream_remote_address": "YY.YYY.YYY.YY:45078",
  "path": "/playbooks/?status=ENABLED&status=DISABLED&status=SENT&status=SCHEDULED&status=ARCHIVED",
  "authority": "conversation2.api.driftqa.com",
  "protocol": "HTTP/1.1",
  "upstream_service_time": null,
  "upstream_local_address": "ZZ.ZZ.ZZ.ZZZ:50970",
  "duration": 6767,
  "downstream_local_address": "ZZ.ZZ.ZZ.ZZZ:8443",
  "upstream_transport_failure_reason": null,
  "response_code": 0,
  "connection_termination_details": null,
  "response_flags": "DC",
  "response_tx_duration": null,
  "requested_server_name": null,
  "bytes_received": 0,
  "downstream_direct_remote_address": "YY.YYY.YYY.YY:45078",
  "request_duration": 0,
  "connection_id": 5713,
  "route_name": null,
  "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4143.7 Safari/537.36 Chrome-Lighthouse",
  "response_code_details": "downstream_remote_disconnect",
  "start_time": "2021-04-19 16:50:02.980466",
  "request_id": "c7337fbe-02ce-4332-8ba2-12a9efc4f048",
  "method": "GET",
  "upstream_host": "XX.XX.XX.XX:8000",
  "x_forwarded_for": "YY.YYY.YYY.YY"
}
```

After reading [this](https://medium.com/tenable-techblog/lessons-from-aws-nlb-timeouts-5028a8f65dda) article, and noticing we are seeing pretty much the same behavior we decided to look in to this more. We've attempted to adjust the socket options for TCP keep alive (as described [here](https://github.com/istio/istio/issues/28879)), with the following envoy filter:

``` yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ingress-gateway-socket-options
  namespace: istio-system
spec:
  configPatches:
  - applyTo: LISTENER
    match:
      context: GATEWAY
      listener:
        name: 0.0.0.0_8443
        portNumber: 8443
    patch:
      operation: MERGE
      value:
        socket_options:
        # SOL_SOCKET = 1
        # SO_KEEPALIVE = 9
        - int_value: 1
          level: 1
          name: 9
          state: STATE_LISTENING
        # IPPROTO_TCP = 6
        # TCP_KEEPIDLE = 4
        - int_value: 120
          level: 6
          name: 4
          state: STATE_LISTENING
        # IPPROTO_TCP = 6
        # TCP_KEEPINTVL = 5
        - int_value: 60
          level: 6
          name: 5
          state: STATE_LISTENING
```

we've also set the following in our meshconfiguration:

``` yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio
  namespace: istio-system
  labels:
    istio.io/rev: default
    install.operator.istio.io/owning-resource: unknown
    operator.istio.io/component: "Pilot"
    release: istio
data:
...
    tcpKeepalive:
      interval: 60s
      time: 120s
...
```

After all of this, however, we are still consistently seeing these problems. Below is a chart that shows the sum of istio_requests_total with a 0 response code in one of our environments:

![2021-04-19 at 2 01 PM](https://user-images.githubusercontent.com/10070047/115282164-df715b80-a117-11eb-99a3-8512088db9f8.png)

[ ] Docs
[ ] Installation
[x] Networking
[x] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

The TCP keep alive is being respected and a response code is given to the client.

**Steps to reproduce the bug**

Create an Istio ingress gateway in EKS using the NLB annotation. Configure a gateway, virtual service and kubernetes service. Open a long-lived tcp connection and observe "no response code"

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
⫸ istioctl version --remote
client version: 1.8.2
control plane version: 1.8.2
data plane version: 1.8.2 (27 proxies)
⫸ kubectl version --short
Client Version: v1.15.11
Server Version: v1.18.9-eks-d1db3c
```

**How was Istio installed?**

The following istio operator config was rendered as a manifest (`istioctl manifest generate -f istioconfig.yaml > manifest.yaml`) and applying using `k apply -f `
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  profile: default
  meshConfig:
    accessLogFile: "/dev/stdout"
    accessLogEncoding: JSON
    accessLogFormat: |
        {
          "start_time": "%START_TIME(%Y-%m-%d %H:%M:%S.%6f)%",
          "request_id": "%REQ(X-REQUEST-ID)%",
          "connection_id": "%CONNECTION_ID%",
          "authority": "%REQ(:AUTHORITY)%",
          "protocol": "%PROTOCOL%",
          "method": "%REQ(:METHOD)%",
          "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
          "referer": "%REQ(REFERER)%",
          "route_name": "%ROUTE_NAME%",
          "requested_server_name": "%REQUESTED_SERVER_NAME%",
          "bytes_received": "%BYTES_RECEIVED%",
          "bytes_sent": "%BYTES_SENT%",
          "user_agent": "%REQ(USER-AGENT)%",
          "duration": "%DURATION%",
          "request_duration": "%REQUEST_DURATION%",
          "response_duration": "%RESPONSE_DURATION%",
          "response_tx_duration": "%RESPONSE_TX_DURATION%",
          "response_code": "%RESPONSE_CODE%",
          "response_code_details": "%RESPONSE_CODE_DETAILS%",
          "response_flags": "%RESPONSE_FLAGS%",
          "connection_termination_details": "%CONNECTION_TERMINATION_DETAILS%",
          "upstream_cluster": "%UPSTREAM_CLUSTER%",
          "upstream_host": "%UPSTREAM_HOST%",
          "upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%",
          "upstream_service_time": "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%",
          "upstream_transport_failure_reason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%",
          "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%",
          "downstream_direct_remote_address": "%DOWNSTREAM_DIRECT_REMOTE_ADDRESS%",
          "x_forwarded_for": "%REQ(X-FORWARDED-FOR)%",
          "downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%"
        }

    enablePrometheusMerge: false
    tcpKeepalive:
      interval: 60s
      time: 120s
  components:
    pilot:
      enabled: true
      k8s:
        replicaCount: 3
        strategy:
          rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 0%
        podDisruptionBudget:
          minAvailable: 1
          selector:
            matchLabels:
              app: istiod
              istio: pilot
        hpaSpec:
          maxReplicas: 5
          metrics:
          - resource:
              name: cpu
              targetAverageUtilization: 50
            type: Resource
          minReplicas: 3
    ingressGateways:
      - name: istio-ingressgateway
        enabled: false
      - enabled: true
        namespace: istio-system
        name: external-ingressgateway
        label:
          app: external-ingressgateway
          istio: external-ingressgateway
        k8s:
          replicaCount: 5
          env:
          - name: ISTIO_META_ROUTER_MODE
            value: sni-dnat
          podDisruptionBudget:
            minAvailable: 5
            selector:
              matchLabels:
                app: external-ingressgateway
                istio: external-ingressgateway
          hpaSpec:
            maxReplicas: 50
            metrics:
            - resource:
                name: cpu
                targetAverageUtilization: 50
              type: Resource
            minReplicas: 5
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: external-ingressgateway
          resources:
            limits:
              cpu: 6000m
              memory: 1024Mi
            requests:
              cpu: 1000m
              memory: 1024Mi
          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-ssl-cert: CERT-XXXXXXXXXXXXXXXXXX
            service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS-1-2-2017-01
            service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
            service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
            service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
            service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
            service.beta.kubernetes.io/aws-load-balancer-type: nlb
          service:
            ports:
            - name: https
              port: 443
              targetPort: 8443
            - name: http
              port: 80
              targetPort: 8080
            externalTrafficPolicy: Local
          strategy:
            rollingUpdate:
              maxSurge: 25%
              maxUnavailable: 0%
  values:
    telemetry:
      v2:
        prometheus:
          configOverride:
            gateway:
              disable_host_header_fallback: true
              metrics:
                - name: requests_total
                  dimensions:
                    request_operation: istio_operationId

```

**Environment where the bug was observed (cloud vendor, OS, etc)**

EKS

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by bbl232** [comment]
The client is closing the connection before you respond by the looks of this. I'm basing that on the response flag "DC" in your output.

**Comment by jaronoff97** [comment]
Yep I believe the client connection is being closed because of the NLB timeout, and I expected the istio tcpKeepAlive timeout being set to _well under_ the 350 second NLB timeout would cause a reconnect before the NLB has a chance to disconnect the client. However, even with the keep alive being set on the Istio side, we are still seeing these problems. I've confirmed that the configuration from the EnvoyFilter is indeed being applied:

```
⫸ istioctl proxy-config listeners external-ingressgateway-b74497984-9tnq8  --port 8443 -o json | jq '.[0].socketOptions'
[
  {
    "level": "1",
    "name": "9",
    "intValue": "1",
    "state": "STATE_LISTENING"
  },
  {
    "level": "6",
    "name": "4",
    "intValue": "120",
    "state": "STATE_LISTENING"
  },
  {
    "level": "6",
    "name": "5",
    "intValue": "60",
    "state": "STATE_LISTENING"
  }
]

```

Is there anything else I can do to debug this?

**Comment by pk-hugo** [comment]
@jaronoff97 Did you find any solution for this? We have the exact same setup and we are also facing the same issue.

**Comment by parshva-shah-dsw** [comment]
@pk-hugo were you able to find any solution for the DC downstream remote disconnect error??

We are facing the same issue in our AWS Env.
We are using below services : 
Aws eks 1.31
Aws nlb created using annotation - Aws load balancer controller 
Istio 1.24.0

**Comment by pk-hugo** [comment]
@parshva-shah-dsw the below configuration worked for us

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: custom-tcp-keepalive-protocol
  namespace: service
spec:
  workloadSelector:
    labels:
      name: istio-ingress
  configPatches:
    - applyTo: LISTENER
      match:
        context: GATEWAY
      patch:
        operation: MERGE
        value:
          socket_options:
            - int_value: 1   # (level: 1, name: 9) -> With the above configuration, TCP Keep-Alives can be enabled in socket with Linux, which can be used in listener’s or admin’s socket_options.
              level: 1  # SOL_SOCKET
              name: 9  # SO_KEEPALIVE
              state: STATE_PREBIND
            - int_value: 9  # TCP_KEEPIDLE (level: 6, name: 6) -> Sets the idle time before keepalive probes start to 9 seconds.
              level: 6
              name: 6
              state: STATE_PREBIND  # This indicates that the socket option should be set before the socket is bound to an address.
            - int_value: 120  # TCP_KEEPALIVE (level: 6, name: 4) -> Sets the interval between keepalive probes to 120 seconds.
              level: 6
              name: 4
              state: STATE_PREBIND
            - int_value: 30  # TCP_KEEPINTVL (level: 6, name: 5) -> Sets the time between individual keepalive probes when no response is received to 30 seconds.
              level: 6
              name: 5
              state: STATE_PREBIND
    - applyTo: NETWORK_FILTER
      match:
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: MERGE
        value:
          name: envoy.filters.network.http_connection_manager
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            common_http_protocol_options:
              idle_timeout: 100s
```
