### ISSUE TITLE
Additional Ingress gateway is missing service port

### ISSUE THREAD

**Issue by safredAAs** [istio/istio#32317]
Hello,

I have a terraform project, which sets up multiple ingress gateways on our GKE cluster.

```
resource "kubectl_manifest" "istio-operator" {
  #language=YAML
  yaml_body = <<YAML
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-operator
  namespace: "${kubernetes_namespace.istio-system.metadata[0].name}"
  labels:
    app.kubernetes.io/part-of: "service-mesh"
    app.kubernetes.io/managed-by: "Terraform"
spec:
  profile: default
  components:
      ingressGateways:
        - name: istio-ingressgateway
          enabled: true
        - name: internal-ingressgateway
          namespace: istio-system
          enabled: true
          label:
            istio: internal-istio-ingressgateway
            app: internal-istio-ingressgateway
          k8s:
            serviceAnnotations:
              "networking.gke.io/load-balancer-type": "Internal"
              "cloud.google.com/load-balancer-type": "internal"
              "cloud.google.com/neg": "{\"ingress\": true}"
              "beta.cloud.google.com/backend-config": '{"default": "internal-ingress"}'
            env:
            - name: ISTIO_META_ROUTER_MODE
              value: sni-dnat
            hpaSpec:
              maxReplicas: 5
              metrics:
              - resource:
                  name: cpu
                  targetAverageUtilization: 80
                type: Resource
              minReplicas: 1
              scaleTargetRef:
                apiVersion: apps/v1
                kind: Deployment
                name: istio-internal-ingressgateway
            resources:
              limits:
                cpu: 2000m
                memory: 1024Mi
              requests:
                cpu: 100m
                memory: 128Mi
            service:
              ports:
              - name: status-port
                port: 15022
                targetPort: 15022
              - name: http2
                port: 80
                targetPort: 8080
              - name: tls
                port: 15444
                targetPort: 15444
              type: NodePort
            strategy:
              rollingUpdate:
                maxSurge: 100%
                maxUnavailable: 25%
  values:
    gateways:
      istio-ingressgateway:
        serviceAnnotations:
          "cloud.google.com/neg": "{\"ingress\": true}"
          "beta.cloud.google.com/backend-config": '{"default": "main-ingress"}'
        type: NodePort
YAML

  depends_on = [
    helm_release.istio-operator
  ]
}
```

Both Ingress are created and visible in kubectl. The Problem I'm having now is that the internal ingress is not serving on Port 8080, which is required for our health check.

See netstat outputs from both docker containers:
Internal-Ingress
```
istio-proxy@internal-ingressgateway-7f4f96b4ff-6swm7:/$ netstat -tupln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:15021           0.0.0.0:*               LISTEN      19/envoy            
tcp        0      0 0.0.0.0:15090           0.0.0.0:*               LISTEN      19/envoy            
tcp        0      0 127.0.0.1:15000         0.0.0.0:*               LISTEN      19/envoy            
tcp6       0      0 :::15020                :::*                    LISTEN      1/pilot-agent
```

External Inggress
```
istio-proxy@istio-ingressgateway-7cc49dcd99-8lnn6:/$ netstat -tupln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:15021           0.0.0.0:*               LISTEN      17/envoy            
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      17/envoy            
tcp        0      0 0.0.0.0:15090           0.0.0.0:*               LISTEN      17/envoy            
tcp        0      0 127.0.0.1:15000         0.0.0.0:*               LISTEN      17/envoy            
tcp6       0      0 :::15020                :::*                    LISTEN      1/pilot-agent
```

What am I doing wrong, that the External Ingress is serving on Port 8080, but the not the internal ingress?

Thank you for your help!
