### ISSUE TITLE
Deploying istiod but failed to list CRDs:Unauthorized

### ISSUE THREAD

**Issue by 6174495** [istio/istio#32318]
Deployment and Configmap:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio
  namespace: kube-system
  labels:
    istio.io/rev: default
    install.operator.istio.io/owning-resource: unknown
    operator.istio.io/component: "Pilot"
    release: istio
data:
  meshNetworks: |-
    networks: {}
  mesh: |-
    defaultConfig:
      discoveryAddress: istiod.kube-system.svc:15012
      proxyMetadata: {}
      tracing:
        zipkin:
          address: zipkin.kube-system:9411
    enablePrometheusMerge: true
    rootnamespace: kube-system
    trustDomain: cluster.local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istiod
  namespace: kube-system
  labels:
    app: istiod
    istio.io/rev: default
    install.operator.istio.io/owning-resource: unknown
    operator.istio.io/component: "Pilot"
    istio: pilot
    release: istio
spec:
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
  selector:
    matchLabels:
      istio: pilot
  template:
    metadata:
      labels:
        app: istiod
        istio.io/rev: default
        install.operator.istio.io/owning-resource: unknown
        sidecar.istio.io/inject: "false"
        operator.istio.io/component: "Pilot"
        istio: pilot
      annotations:
        prometheus.io/port: "15014"
        prometheus.io/scrape: "true"
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: istiod-service-account
      securityContext:
        fsGroup: 1337
      containers:
        - name: discovery
          image: "192.168.12.66:20202/kube-system/pilot:1.9.0"
          args:
          - "discovery"
          - --monitoringAddr=:15014
          - --log_output_level=default:info
          - --domain
          - cluster.local
          - --keepaliveMaxServerConnectionAge
          - "30m"
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 15010
            protocol: TCP
          - containerPort: 15017
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 3
            timeoutSeconds: 5
          env:
          - name: REVISION
            value: "default"
          - name: JWT_POLICY
            value: first-party-jwtm
          - name: PILOT_CERT_PROVIDER
            value: istiod
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.serviceAccountName
          - name: KUBECONFIG
            value: /var/run/secrets/remote/config
          - name: PILOT_TRACE_SAMPLING
            value: "1"
          - name: PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_OUTBOUND
            value: "true"
          - name: PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_INBOUND
            value: "true"
          - name: ISTIOD_ADDR
            value: istiod.kube-system.svc:15012
          - name: PILOT_ENABLE_ANALYSIS
            value: "false"
          - name: CLUSTER_ID
            value: "Kubernetes"
          - name: EXTERNAL_ISTIOD
            value: "false"
          resources:
            requests:
              cpu: 500m
              memory: 2048Mi
          securityContext:
            runAsUser: 1337
            runAsGroup: 1337
            runAsNonRoot: true
            capabilities:
              drop:
              - ALL
          volumeMounts:
          - name: config-volume
            mountPath: /etc/istio/config
          - name: local-certs
            mountPath: /var/run/secrets/istio-dns
          - name: cacerts
            mountPath: /etc/cacerts
            readOnly: true
          - name: istio-kubeconfig
            mountPath: /var/run/secrets/remote
            readOnly: true
          - name: inject
            mountPath: /var/lib/istio/inject
            readOnly: true
      nodeSelector:
        istio: control
      volumes:
      # Technically not needed on this pod - but it helps debugging/testing SDS
      # Should be removed after everything works.
      - emptyDir:
          medium: Memory
        name: local-certs
      # Optional: user-generated root
      - name: cacerts
        secret:
          secretName: cacerts
          optional: true
      - name: istio-kubeconfig
        secret:
          secretName: istio-kubeconfig
          optional: true
      # Optional - image should have
      - name: inject
        configMap:
          name: istio-sidecar-injector
      - name: config-volume
        configMap:
          name: istio
---
```
command:
```
kubectl apply -f Pilot.yaml
error:
2021-04-20T13:17:12.529054Z     info    initializing mesh handlers
2021-04-20T13:17:12.529074Z     info    creating CA and initializing public key
2021-04-20T13:17:12.529100Z     info    Use local CA certificate
2021-04-20T13:17:12.531265Z     info    initializing controllers
2021-04-20T13:17:12.531299Z     info    No certificates specified, skipping K8S DNS certificate controller
2021-04-20T13:17:12.653740Z     error   kube    failed to list CRDs: Unauthorized
2021-04-20T13:17:13.657258Z     error   kube    failed to list CRDs: Unauthorized
2021-04-20T13:17:15.660347Z     error   kube    failed to list CRDs: Unauthorized
2021-04-20T13:17:19.663317Z     error   kube    failed to list CRDs: Unauthorized
2021-04-20T13:17:27.666387Z     error   kube    failed to list CRDs: Unauthorized
2021-04-20T13:17:43.670710Z     error   kube    failed to list CRDs: Unauthorized
2021-04-20T13:18:15.675421Z     error   kube    failed to list CRDs: Unauthorized
```
