### ISSUE TITLE
Can no longer set preStop in global.proxy.lifecycle

### ISSUE THREAD

**Issue by michaelst** [istio/istio#32361]
**Bug description**
I am upgrading from 1.8.1
```
admission webhook "sidecar-injector.istio.io" denied the request: failed to run injection template: failed parsing generated injected YAML (check Istio sidecar injector configuration): unmarshal patched pod: json: cannot unmarshal number into Go struct field ExecAction.spec.containers.lifecycle.preStop.exec.command of type string
```

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[x] Upgrade

**Expected behavior**
It should allow me to specify preStop in the proxy lifecycle

**Steps to reproduce the bug**
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: minimal
  meshConfig: 
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
  components:
    cni:
      enabled: true
      namespace: kube-system
  values:
    cni:
      cniBinDir: /home/kubernetes/bin
    global:
      proxy:
        lifecycle:
          postStart:
            exec:
              command:
              - pilot-agent
              - wait
          preStop:
            exec:
              command:
              - sleep
              - 30
```

istioctl install -f istio/operator.yaml
kubectl rollout restart deployment --namespace xxx

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
client version: 1.9.3
control plane version: 1.9.3
data plane version: 1.9.3 (7 proxies)
```

```
Client Version: v1.20.4
Server Version: v1.18.16-gke.502
```

**Comment by howardjohn** [comment]
Should probably be:
```yaml
          preStop:
            exec:
              command:
              - sleep
              - "30"
```
?

Note the 30 -> "30"
