### ISSUE TITLE
The remote installation profile should not install istiod

### ISSUE THREAD

**Issue by frankbu** [istio/istio#32370]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

The [remote installation profile](https://github.com/istio/istio/blob/master/manifests/profiles/remote.yaml) is supposed to be used on remote clusters that have a remote istiod, instead of a locally installed one, but it is currently installing default settings (the same as the `default` profile), which includes istiod and a lot of other things.

It should, instead, only be installing what's needed in a data-plane-only cluster, which is only the injector mutating webhook configuration. Everything else (istiod, ingress-gateway, configmaps, and envoyfilters) should not be installed.

[x] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

The `remote` profile should be defined something like this:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    base:
      enabled: false
    pilot:
      enabled: false
    ingressGateways:
    - name: istio-ingressgateway
      enabled: false
    istiodRemote:
      enabled: true
  values:
    telemetry:
      enabled: false
    pilot:
      configMap: false
    global:
      omitSidecarInjectorConfigMap: true
```

This will install nothing but the mutating webhook configuration.

Using this profile, a remote cluster using an external istiod could be installed with an IOP like this:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: remote
  values:
    istiodRemote:
      injectionURL: https://${REMOTE_ISTIOD_ADDR}:15017/inject/:ENV:cluster=cluster1:ENV:net=network1
```

A config cluster for an external control plane would also need to install the CRDs:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: remote
  values:
    istiodRemote:
      injectionURL: https://${REMOTE_ISTIOD_ADDR}:15017/inject/:ENV:cluster=cluster1:ENV:net=network1
  components:
    base:
      enabled: true # install CRDs for config cluster
```

If the `remote` profile cannot be changed (for backward-compatibility), we should deprecate it, since it's exactly the same as profile=default, and create a new profile, e.g., `external-istiod`, with the new (istiod-less) definition.

**Steps to reproduce the bug**

istioctl install --set profile=remote

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

latest version.

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
