### ISSUE TITLE
Global ratelimit not working

### ISSUE THREAD

**Issue by arjunkrishnasb** [istio/istio#32381]
Hi,

I have installed istio and was trying to test ratelimiting features. I followed the tutorial (https://istio.io/latest/docs/tasks/policy-enforcement/rate-limit/) but could not get ratelimiting working. I tried to check through the logs of my ratelimiting pod and gateway pod, but could not find any useful information.
Can someone help me understand what am i doing wrong here and how to troubleshoot this ?

Istio version: 
```
(base) ARJSRIRA-M-L0XP:~ arjsrira$ istioctl version
client version: 1.9.3
control plane version: 1.9.1
data plane version: 1.9.1 (9 proxies)
```
Installation was done using the operator:
```
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-control-plane
spec:
  profile: default
```
Bookinfo app:
```
(base) ARJSRIRA-M-L0XP:kubespray arjsrira$ kubectl get all,virtualservice,gateway -n bookinfo -o wide
NAME                                  READY   STATUS    RESTARTS   AGE   IP             NODE                      NOMINATED NODE   READINESS GATES
pod/details-v1-66b6955995-p6shp       2/2     Running   0          23d   10.1.254.193   dev-fab3-k8s-worker-001   <none>           <none>
pod/productpage-v1-5d9b4c9849-mjv8f   2/2     Running   0          23d   10.1.244.166   dev-fab3-k8s-worker-002   <none>           <none>
pod/ratelimit-c9c6ddfd4-hskj8         2/2     Running   1          71m   10.1.244.10    dev-fab3-k8s-worker-002   <none>           <none>
pod/ratings-v1-fd78f799f-jp6zw        2/2     Running   0          23d   10.1.254.194   dev-fab3-k8s-worker-001   <none>           <none>
pod/redis-58767bf578-n4n4p            2/2     Running   0          16d   10.1.254.179   dev-fab3-k8s-worker-001   <none>           <none>
pod/reviews-v1-6549ddccc5-jlmrv       2/2     Running   0          23d   10.1.254.196   dev-fab3-k8s-worker-001   <none>           <none>
pod/reviews-v2-76c4865449-8jp55       2/2     Running   0          23d   10.1.244.165   dev-fab3-k8s-worker-002   <none>           <none>
pod/reviews-v3-6b554c875-kksps        2/2     Running   0          23d   10.1.254.198   dev-fab3-k8s-worker-001   <none>           <none>

NAME                  TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                      AGE   SELECTOR
service/details       ClusterIP   10.1.182.85    <none>        9080/TCP                     23d   app=details
service/productpage   ClusterIP   10.1.175.78    <none>        9080/TCP                     23d   app=productpage
service/ratelimit     ClusterIP   10.1.128.211   <none>        8080/TCP,8081/TCP,6070/TCP   16d   app=ratelimit
service/ratings       ClusterIP   10.1.163.124   <none>        9080/TCP                     23d   app=ratings
service/redis         ClusterIP   10.1.151.240   <none>        6379/TCP                     16d   app=redis
service/reviews       ClusterIP   10.1.163.79    <none>        9080/TCP                     23d   app=reviews

NAME                             READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS    IMAGES                                                    SELECTOR
deployment.apps/details-v1       1/1     1            1           23d   details       docker.io/istio/examples-bookinfo-details-v1:1.16.2       app=details,version=v1
deployment.apps/productpage-v1   1/1     1            1           23d   productpage   docker.io/istio/examples-bookinfo-productpage-v1:1.16.2   app=productpage,version=v1
deployment.apps/ratelimit        1/1     1            1           16d   ratelimit     envoyproxy/ratelimit:6f5de117                             app=ratelimit
deployment.apps/ratings-v1       1/1     1            1           23d   ratings       docker.io/istio/examples-bookinfo-ratings-v1:1.16.2       app=ratings,version=v1
deployment.apps/redis            1/1     1            1           16d   redis         redis:alpine                                              app=redis
deployment.apps/reviews-v1       1/1     1            1           23d   reviews       docker.io/istio/examples-bookinfo-reviews-v1:1.16.2       app=reviews,version=v1
deployment.apps/reviews-v2       1/1     1            1           23d   reviews       docker.io/istio/examples-bookinfo-reviews-v2:1.16.2       app=reviews,version=v2
deployment.apps/reviews-v3       1/1     1            1           23d   reviews       docker.io/istio/examples-bookinfo-reviews-v3:1.16.2       app=reviews,version=v3

NAME                                        DESIRED   CURRENT   READY   AGE   CONTAINERS    IMAGES                                                    SELECTOR
replicaset.apps/details-v1-66b6955995       1         1         1       23d   details       docker.io/istio/examples-bookinfo-details-v1:1.16.2       app=details,pod-template-hash=66b6955995,version=v1
replicaset.apps/productpage-v1-5d9b4c9849   1         1         1       23d   productpage   docker.io/istio/examples-bookinfo-productpage-v1:1.16.2   app=productpage,pod-template-hash=5d9b4c9849,version=v1
replicaset.apps/ratelimit-c9c6ddfd4         1         1         1       16d   ratelimit     envoyproxy/ratelimit:6f5de117                             app=ratelimit,pod-template-hash=c9c6ddfd4
replicaset.apps/ratings-v1-fd78f799f        1         1         1       23d   ratings       docker.io/istio/examples-bookinfo-ratings-v1:1.16.2       app=ratings,pod-template-hash=fd78f799f,version=v1
replicaset.apps/redis-58767bf578            1         1         1       16d   redis         redis:alpine                                              app=redis,pod-template-hash=58767bf578
replicaset.apps/reviews-v1-6549ddccc5       1         1         1       23d   reviews       docker.io/istio/examples-bookinfo-reviews-v1:1.16.2       app=reviews,pod-template-hash=6549ddccc5,version=v1
replicaset.apps/reviews-v2-76c4865449       1         1         1       23d   reviews       docker.io/istio/examples-bookinfo-reviews-v2:1.16.2       app=reviews,pod-template-hash=76c4865449,version=v2
replicaset.apps/reviews-v3-6b554c875        1         1         1       23d   reviews       docker.io/istio/examples-bookinfo-reviews-v3:1.16.2       app=reviews,pod-template-hash=6b554c875,version=v3

NAME                                          GATEWAYS             HOSTS   AGE
virtualservice.networking.istio.io/bookinfo   [bookinfo-gateway]   [*]     23d

NAME                                           AGE
gateway.networking.istio.io/bookinfo-gateway   23d
```
Istio system namespace resources:
```
(base) ARJSRIRA-M-L0XP:kubespray arjsrira$ kubectl get all,envoyfilter -n istio-system -o wide
NAME                                       READY   STATUS    RESTARTS   AGE   IP             NODE                      NOMINATED NODE   READINESS GATES
pod/istio-ingressgateway-8dd44598c-qfc8b   1/1     Running   0          24d   10.1.254.175   dev-fab3-k8s-worker-001   <none>           <none>
pod/istiod-848bf7f678-7t7z5                1/1     Running   0          24d   10.1.254.190   dev-fab3-k8s-worker-001   <none>           <none>

NAME                           TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                                                                      AGE   SELECTOR
service/istio-ingressgateway   LoadBalancer   10.1.167.21    <pending>     15021:32549/TCP,80:30717/TCP,443:31437/TCP,15012:31146/TCP,15443:30333/TCP   24d   app=istio-ingressgateway,istio=ingressgateway
service/istiod                 ClusterIP      10.1.170.106   <none>        15010/TCP,15012/TCP,443/TCP,15014/TCP                                        24d   app=istiod,istio=pilot

NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS    IMAGES                          SELECTOR
deployment.apps/istio-ingressgateway   1/1     1            1           24d   istio-proxy   docker.io/istio/proxyv2:1.9.1   app=istio-ingressgateway,istio=ingressgateway
deployment.apps/istiod                 1/1     1            1           24d   discovery     docker.io/istio/pilot:1.9.1     istio=pilot

NAME                                             DESIRED   CURRENT   READY   AGE   CONTAINERS    IMAGES                          SELECTOR
replicaset.apps/istio-ingressgateway-8dd44598c   1         1         1       24d   istio-proxy   docker.io/istio/proxyv2:1.9.1   app=istio-ingressgateway,istio=ingressgateway,pod-template-hash=8dd44598c
replicaset.apps/istiod-848bf7f678                1         1         1       24d   discovery     docker.io/istio/pilot:1.9.1     istio=pilot,pod-template-hash=848bf7f678

NAME                                                       REFERENCE                         TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
horizontalpodautoscaler.autoscaling/istio-ingressgateway   Deployment/istio-ingressgateway   3%/80%    1         5         1          24d
horizontalpodautoscaler.autoscaling/istiod                 Deployment/istiod                 1%/80%    1         5         1          24d

NAME                                                        AGE
envoyfilter.networking.istio.io/filter-ratelimit            24h
envoyfilter.networking.istio.io/filter-ratelimit-svc        24h
envoyfilter.networking.istio.io/metadata-exchange-1.8       24d
envoyfilter.networking.istio.io/metadata-exchange-1.9       24d
envoyfilter.networking.istio.io/stats-filter-1.8            24d
envoyfilter.networking.istio.io/stats-filter-1.9            24d
envoyfilter.networking.istio.io/tcp-metadata-exchange-1.8   24d
envoyfilter.networking.istio.io/tcp-metadata-exchange-1.9   24d
envoyfilter.networking.istio.io/tcp-stats-filter-1.8        24d
envoyfilter.networking.istio.io/tcp-stats-filter-1.9        24d
```
Envoy Filter:
```
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-ratelimit
  namespace: istio-system
spec:
  workloadSelector:
    # select by label in the same namespace
    labels:
      istio: ingressgateway
  configPatches:
    # The Envoy config you want to modify
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        # Adds the Envoy Rate Limit Filter in HTTP filter chain.
        value:
          name: envoy.filters.http.ratelimit
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
            # domain can be anything! Match it to the ratelimter service config
            domain: productpage-ratelimit
            failure_mode_deny: true
            rate_limit_service:
              grpc_service:
                envoy_grpc:
                  cluster_name: rate_limit_cluster
                timeout: 10s
              transport_api_version: V3
    - applyTo: CLUSTER
      match:
        cluster:
          service: ratelimit.bookinfo.svc.cluster.local
      patch:
        operation: ADD
        # Adds the rate limit service cluster for rate limit service defined in step 1.
        value:
          name: rate_limit_cluster
          type: STRICT_DNS
          connect_timeout: 10s
          lb_policy: ROUND_ROBIN
          http2_protocol_options: {}
          load_assignment:
            cluster_name: rate_limit_cluster
            endpoints:
            - lb_endpoints:
              - endpoint:
                  address:
                     socket_address:
                      address: ratelimit.bookinfo.svc.cluster.local
                      port_value: 8081

---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-ratelimit-svc
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: VIRTUAL_HOST
      match:
        context: GATEWAY
        routeConfiguration:
          vhost:
            name: "*:*"
            route:
              action: ANY
      patch:
        operation: MERGE
        # Applies the rate limit rules.
        value:
          rate_limits:
            - actions: # any actions in here
              - request_headers:
                  header_name: ":path"
                  descriptor_key: "PATH"
```
Ratelimit config:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: bookinfo
  name: ratelimit-config
data:
  config.yaml: |
    domain: productpage-ratelimit
    descriptors:
      - key: PATH
        value: "/productpage"
        rate_limit:
          unit: minute
          requests_per_unit: 1
      - key: PATH
        value: "/api/v1/products"
        rate_limit:
          unit: minute
          requests_per_unit: 1
      - key: PATH
        rate_limit:
          unit: minute
          requests_per_unit: 1
```
Ratelimit service i directly copied from https://github.com/istio/istio/blob/release-1.9/samples/ratelimit/rate-limit-service.yaml and added bookinfo namespace

**Comment by arjunkrishnasb** [comment]
```
(base) ARJSRIRA-M-L0XP:~ arjsrira$ istioctl pc listeners istio-ingressgateway-8dd44598c-qfc8b.istio-system -o json
.....
....
....
                                {
                                    "name": "envoy.filters.http.ratelimit",
                                    "typedConfig": {
                                        "@type": "type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit",
                                        "domain": "productpage-ratelimit",
                                        "failureModeDeny": true,
                                        "rateLimitService": {
                                            "grpcService": {
                                                "envoyGrpc": {
                                                    "clusterName": "rate_limit_cluster"
                                                },
                                                "timeout": "10s"
                                            },
                                            "transportApiVersion": "V3"
                                        }
                                    }
                                },
                                {
                                    "name": "envoy.filters.http.router",
                                    "typedConfig": {
                                        "@type": "type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"
                                    }
                                }
                            ],
...
....
....
```

**Comment by arjunkrishnasb** [comment]
Also in my setup, we are using node port for ingress gateway

**Comment by hendrikmaus** [comment]
It might be match on the `vhost.name`:

```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-ratelimit-svc
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: VIRTUAL_HOST
      match:
        context: GATEWAY
        routeConfiguration:
          vhost:
            name: "*:*"    # <---- needs to match your domain:port exactly
            route:
              action: ANY
      patch:
        operation: MERGE
        # Applies the rate limit rules.
        value:
          rate_limits:
            - actions: # any actions in here
              - request_headers:
                  header_name: ":path"
                  descriptor_key: "PATH"
```

If your application is exposed as `some-service.example.com` on port `80` you'd need to match on `some-service.example.com:80`.

**Comment by arjunkrishnasb** [comment]
Hi @hendrikmaus , thanks you so much for your response. 

Since it is a POC setup, i have my istio gateway exposed using node port. 

I changed the config to include `<host-ip>:<node-port>` but still i dont see my traffic getting rate limited

Any suggestions on further troubleshooting this would be awesome :)

**Comment by hendrikmaus** [comment]
Ok, I would suggest to cump the envoy config of your ingressgateway pod and then find the actual virtual host definition in there. I reckon you will find the host defined in your `VirtualService` then.

To dump the config, I usually port-forward port `15000` of one of the ingressgateway pods to my local host and then I `curl -s http://localhost:15000/config_dump > envoy-config.json`

**Comment by hendrikmaus** [comment]
Just confirmed in my test setup. I use httpbin for testing, but the concept is the same.

I have a `VirtualService` that roughly looks like so:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app: httpbin
  name: httpbin
spec:
  gateways:
    - shared/istio-ingress-internal
  hosts:
    - httpbin.example.com
# snip
```

Since I use port `80`, my `vhost.name` is set to `httpbin.example.com:80`

**Comment by hendrikmaus** [comment]
I reckon that my port `80` is derived from the `Gateway` resource.

**Comment by arjunkrishnasb** [comment]
Hi @hendrikmaus, After messing around these filters, my istio started behaving weird and even routing based on hostname was not working fine. Now reinstalled the setup and things are good with the routing, but rate limiting is not working yet.

Made some modifications to my Virutal service and gateway by adding the hostnames.
```
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: bookinfo
  name: bookinfo-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "dev-fab3-k8s-worker-001.cisco.com"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: bookinfo
  name: bookinfo
spec:
  hosts:
  - "dev-fab3-k8s-worker-001.cisco.com"
  gateways:
  - bookinfo-gateway
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: 9080
```

Like i mentioned before, the istio ingress gateway is exposed as a node port. The weird part is, in the gateway config, if i give that nodeport, it is not accepting the traffic. Only if i give it as 80, it is accepting.

Next, i modified the envoy filter as expected
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-ratelimit-svc
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: VIRTUAL_HOST
      match:
        context: GATEWAY
        routeConfiguration:
          vhost:
            name: "dev-fab3-k8s-worker-001.cisco.com:80"
            route:
              action: ANY
      patch:
        operation: MERGE
        # Applies the rate limit rules.
        value:
          rate_limits:
            - actions: # any actions in here
              - request_headers:
                  header_name: ":path"
                  descriptor_key: "PATH"
              - request_headers:
                  header_name: "path"
                  descriptor_key: "PATH"
              - request_headers:
                  header_name: "test"
                  descriptor_key: "TEST"
```

Like you mentioned, i got the envoy configs of my istio ingress gateway and it has route config as below

```
   "dynamic_route_configs": [
    {
     "version_info": "2021-04-27T06:19:13Z/15",
     "route_config": {
      "@type": "type.googleapis.com/envoy.config.route.v3.RouteConfiguration",
      "name": "http.80",
      "virtual_hosts": [
       {
        "name": "dev-fab3-k8s-worker-001.cisco.com:80",
        "domains": [
         "dev-fab3-k8s-worker-001.cisco.com",
         "dev-fab3-k8s-worker-001.cisco.com:*"
        ],
        "routes": [
         {
          "match": {
           "path": "/productpage",
           "case_sensitive": true
          },
```

Not sure why the rate limiting is not working. Is this an issue because the gateway is exposed as nodeport or  I am not really sure.

**Comment by arjunkrishnasb** [comment]
Woorrayy!! It seems working now!
After the above fix, i realised that, in my filter-ratelimit-svc the action is based on 3 request headers. Which means, it is getting was sent to the rate limit service, but there the descriptors i had were for individual headers. Hence there was no match and it ended up allowing the requests.
Now i modified the actions piece to match it with the rate limit config, so things are working fine.

```
time="2021-04-27T09:34:59Z" level=debug msg="got descriptor: (PATH=/productpage)"
time="2021-04-27T09:34:59Z" level=debug msg="starting get limit lookup"
time="2021-04-27T09:34:59Z" level=debug msg="looking up key: PATH_/productpage"
time="2021-04-27T09:34:59Z" level=debug msg="found rate limit: PATH_/productpage"
time="2021-04-27T09:34:59Z" level=debug msg="applying limit: 1 requests per MINUTE"
time="2021-04-27T09:34:59Z" level=debug msg="got descriptor: (TEST=test)"
time="2021-04-27T09:34:59Z" level=debug msg="starting get limit lookup"
time="2021-04-27T09:34:59Z" level=debug msg="looking up key: TEST_test"
time="2021-04-27T09:34:59Z" level=debug msg="looking up key: TEST"
time="2021-04-27T09:34:59Z" level=debug msg="found rate limit: TEST"
time="2021-04-27T09:34:59Z" level=debug msg="applying limit: 1 requests per MINUTE"
time="2021-04-27T09:34:59Z" level=debug msg="starting cache lookup"
time="2021-04-27T09:34:59Z" level=debug msg="looking up cache key: productpage-ratelimit_PATH_/productpage_1619516040"
time="2021-04-27T09:34:59Z" level=debug msg="looking up cache key: productpage-ratelimit_TEST_test_1619516040"
time="2021-04-27T09:34:59Z" level=debug msg="cache key: productpage-ratelimit_PATH_/productpage_1619516040 current: 3"
time="2021-04-27T09:34:59Z" level=debug msg="cache key: productpage-ratelimit_TEST_test_1619516040 current: 3"
time="2021-04-27T09:34:59Z" level=debug msg="returning normal response"
```

**Comment by hendrikmaus** [comment]
Congrats 🎉

**Comment by arjunkrishnasb** [comment]
I see that, global rate limiting is something we apply at the gateway level. This way it becomes common for all the applications/namespaces. The only way we could restrict to a specific application is by using the DNS name right ?

Otherwise if i give anything like * that gets applied as a global default ratelimiting for all the applications.

Even in redis, the keys are based on the domain and the descriptor and there is no way to relate it to an application.

So if i provide the rate limiting as a service for the clients using our service mesh setup what is the best way to do it ?

1. Should there be different domains for each application or namespace when we create envoy filters?
2. Can we just setup a single ratelimiting service with redis and somehow allow clients to share it or should there be different ratelimiting setup for each namespace ?
3. What would be the best way for them to create envoy filters ? The reason i ask is, if the clients mess up the configuration, that could potentially bring the gateway down. 

Any guidance here would be appreciated :) 
We are currently looking into using istio as both gateway and service mesh and eventually give it for the clients.

**Comment by hendrikmaus** [comment]
> Otherwise if i give anything like * that gets applied as a global default rate limiting for all the applications.

Did you get that working? I am trying to do just that and haven't succeeded.

> So if i provide the rate limiting as a service for the clients using our service mesh setup what is the best way to do it ?

I have a POC on rate limiting per `VirtualService`, but it always involves updating the `ConfigMap` of envoyproxy/ratelimit. Currently, I think you would need to build an operator for your use case.

**Comment by hendrikmaus** [comment]
There is an operator for ingress-level rate limiting https://github.com/softonic/rate-limit-operator but I have not tried it - read through most of the code though.

**Comment by arjunkrishnasb** [comment]
Hey @hendrikmaus 
Actually using * in envoy filter did not work for me as well yet. I am not sure if there is any other way for doing global ratelimiting for all the applications..

But i tried another scenario for using a same ratelimiting service for two applications. It was working fine after some trial and error.  :) 

The main issue i faced was getting the config map to ratelimit service. I was mounting it without the `subPath` option and it did not work. The reason i removed subpath is that `A container using a ConfigMap as a subPath volume mount will not receive ConfigMap updates`. But if i mount without this, it was giving me some weird issues like the file was created in `..data/config.yaml` and the `config.yaml` seem as a symlink to it. In that case the rate limit server did not accept the connection and in its log it just said 
```
time="2021-04-28T08:11:14Z" level=debug msg="caught error during call"
time="2021-04-28T08:11:17Z" level=debug msg="[gostats] flushing counter ratelimit.service.call.should_rate_limit.service_error: 5"
```
The worst part is, the curl was giving me 500 and did not ignore the ratelimiting!

**Comment by hendrikmaus** [comment]
> The worst part is, the curl was giving me 500 and did not ignore the ratelimiting!

You can influence that by setting `failure_mode_deny: false` in the `EnvoyFilter` that inserts `envoy.filters.http.ratelimit`.

> The main issue i faced was getting the config map to ratelimit service I was mounting it without the `subPath` (...)

Kubernetes does not refresh the contents of volume mounts when `subPath` is used. There are several steps here to make it work for the ratelimit service:

- remove `subPath` from the volume mount
- set the env var `RUNTIME_IGNOREDOTFILES` on ratelimit to `"true"` - this takes care of the ../data warnings
- set the env var `RUNTIME_WATCH_ROOT` on ratelimit to `"false"` - this allows us to update the contents of `RUNTIME_ROOT/RUNTIME_SUBDIRECTORY/config/` directly via a config map as volume mount
- to update the config, update the `ConfigMap` and then annotate the ratelimit pods. this will immediately refresh the file in the volume mount as the kubelet sync interval and caches are bypassed - now your new config is applied in the ratelimit service within seconds

**Comment by arjunkrishnasb** [comment]
Thanks @hendrikmaus !

**Comment by catman002** [comment]
I have the same problem, the port can only be 80?

**Comment by hendrikmaus** [comment]
I have only worked with port 80 on the gateway level.

**Comment by harishb93** [comment]
Hi. I am trying to use Global RateLimiting for rate limiting based on the contextPath variable. 
As per the docs available, the configuration is provided only for Gateway and hence the rate limiter service is showing the logs for "/productpage" when it's hit. 

But I would like this call to be made by every proxy container to the rate limiter service(/ratings, /reviews, /details) and not just the ones called at the ingressgateway. 

What would be the EnvoyFilter I should apply if I have to make it port, selectorLabel, and namespace agnostic? (all applications of all namespaces to call the Global RateLimiting service if there's a match in the rate_limits actions). 

Stuck here for a few weeks, any help would be appreciated.

**Comment by pangsq** [comment]
`*` can be used in `vhost.domains` rather than in `vhost.name`, because the `vhost.name` does not contain wildcard.
For example, my `envoyfilter` config is like below, and the raltelimiter works fine for all applications.
```yaml
  configPatches:
    - applyTo: VIRTUAL_HOST
      match:
        context: GATEWAY
        routeConfiguration:
          vhost:
            domains:
            - "*:80"
            route:
              action: ANY
      patch:
        operation: MERGE
        value:
          rate_limits:
            - actions: # any actions in here
              - request_headers:
                  header_name: "host" # used as ratelimit key
                  descriptor_key: "HOST"
```
And my ratelimit-config's content is (which means any host only can recieve 1 request per minute)
```yaml
    domain: echo-ratelimit
    descriptors:
      - key: HOST
        rate_limit:
          unit: minute
          requests_per_unit: 1
```
