### ISSUE TITLE
Locality load balancing won't work if use header based routing for virtual service

### ISSUE THREAD

**Issue by cynial** [istio/istio#32419]
**Bug description**

1. Locality load balancing is working fine without virtual service
   
- **hello-v1 down, istio can failover to hello-v2**

![11](https://user-images.githubusercontent.com/323831/115834457-d51ccd80-a447-11eb-91b6-ec13c60f312d.png) 

2. If use header based routing for virtual service, locality load balancing won't work
```
  spec:
    hosts:
    - hello
    http:
    - match:
      - headers:
          region:
            regex: v1
      route:
      - destination:
          host: hello
          subset: v1
    - route:
      - destination:
          host: hello
          subset: v2
```
-  **hello-v1 down, istio can't failover to hello-v2**

![33](https://user-images.githubusercontent.com/323831/115837942-b7516780-a44b-11eb-90e1-a2592bad41c9.png)

3. I need header based routing and failover feature, but it doesn't seem to work with locality load balancing, it seems the prioirity of header based routing is higher than locality load balancing?

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

Locality load balancing work with header based routing for virtual service

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
# istio
client version: 1.8.1
control plane version: 1.8-dev-806fb24bc121bf93ea06f6a38b7ccb3d78d1f326
data plane version: 1.8.1 (18 proxies)

# k8s
Client Version: v1.14.3
Server Version: v1.16.3

# helm 
v3.3.4+ga61ce56
```
