### ISSUE TITLE
StreamExtensionConfigs gRPC config stream closed: 12, unknown service envoy.service.extension.v3.ExtensionConfigDiscoveryService

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#32415]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
StreamExtensionConfigs gRPC config stream closed: 12, unknown service envoy.service.extension.v3.ExtensionConfigDiscoveryService
after apply the following config ,show the error:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: apply-to
spec:
  configPatches:
  - applyTo: EXTENSION_CONFIG
    patch:
      operation: ADD 
      value:
        name: my-wasm-extension
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          config:
            root_id: my-wasm-root-id
            vm_config:
              vm_id: my-wasm-vm-id
              runtime: envoy.wasm.runtime.v8
              code:
                local:
                  inline_string: "envoy.wasm.stats"
                #remote:
                #  http_uri:
                #    uri: http://my-wasm-binary-uri
            configuration:
              "@type": "type.googleapis.com/google.protobuf.StringValue"
              value: |
                {}
  - applyTo: HTTP_FILTER
    match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: my-wasm-extension 
        config_discovery:
          config_source:
            api_config_source:
              api_type: GRPC
              transport_api_version: V3
              grpc_services:
              - envoy_grpc:
                  cluster_name: xds-grpc
          type_urls: ["envoy.extensions.filters.http.wasm.v3.Wasm"]
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
[root@master01 ~]# istioctl version --remote
client version: 1.9.2
control plane version: 1.9.2
data plane version: 1.9.2 (15 proxies)

[root@master01 ~]# kubectl version --short
Client Version: v1.20.5
Server Version: v1.20.5

**How was Istio installed?**
istioctl install --set profile=demo
**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
