### ISSUE TITLE
authentication callback error for application behind istio-ingress-gateway

### ISSUE THREAD

**Issue by MirtoBusico** [istio/istio#32421]
**An application behind istio-ingress gateway receives an error in the authentication callback**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**The application asks for user authentication and receives a callback with jwt token**

**Bug description**

**Framework**

- private cesrtification authority (CA)
- all certificates involved are signed by this CA
- CA certificate is installed in every node operating system, in every machine involved and in every browser
- CA certificate is added to istio operator (without this authentication don't work see bug [29366](https://github.com/istio/istio/issues/29366)
- the keycloak authentication server is reachable at "https://k6k.m.net/auth/realms/m-project"
- the istio ingress url is "https://www.m.net"
- the application name is fpresenter

**Istio configuration relevant files**
RequestAuthentication
```
sysop@m-serv:~/software/m-project$ cat m-ra.yaml 
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name:  m-ra
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
  - issuer: "https://k6k.m.net/auth/realms/m-project"
    jwksUri: "https://k6k.m.net/auth/realms/m-project/protocol/openid-connect/certs"
    forwardOriginalToken: true
    outputPayloadToHeader: x-jwt-payload

sysop@m-serv:~/software/m-project$
```

The first lines of www.m-net virtual service are:
```
sysop@m-serv:~/software/m-project$ cat m-gateway.yaml m-vservice.yaml 
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mproject-gateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: www-ingress-tls # must be the same as secret
    hosts:
    - www.m.net

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: fservices
spec:
  hosts:
  - "www.m.net"
  gateways:
  - mproject-gateway
  http:
  - match:
    - uri:
        prefix: "/pres"
    route:
    - destination:
        port:
          number: 3000
        host: fpresenter
  - match:
    - uri:
        prefix: "/presstatic"
    route:
    - destination:
        port:
          number: 3000
        host: fpresenter
  - match:
    - uri:
        exact: "/"
    route:
    - destination:
        port:
          number: 3000
        host: fpresenter
  - match:
    - uri:
        exact: "/logout"
    route:
    - destination:
        port:
          number: 3000
        host: fpresenter
  - match:
    - uri:
        prefix: "/user"
    rewrite:
      uri: "/headers"
    route:
    - destination:
        port:
          number: 8000
        host: fuser

[other services definitions not implied in this report]
```
**Test execution**

- access unprotected page "https://www.m.net": the page shows correctly
- access protected page "https://www.m.net/pres/secured": the application redirect to the keycloak server
- the user authenticate with keycloak and is redirected to url "https://www.m.net/pres/secured?auth_callback=1&state=1579e275-0ea8-4db2-809a-4d0d7c809758&session_state=1234e0e1-9f4d-4bca-a68d-e8a177d24488&code=1381c0ff-7b90-4ee1-8304-f16c853f2457.1234e0e1-9f4d-4bca-a68d-e8a177d24488.e624b94f-f568-4249-9cb0-73f8c25b3955"
- instead of showing the redirected page, you receive an access denied error

In the application log you see:
```
GET /pres/secured 302 296.581 ms - 548
Could not obtain grant code: Error: Client network socket disconnected before secure TLS connection was established
GET /pres/secured?auth_callback=1&state=1579e275-0ea8-4db2-809a-4d0d7c809758&session_state=1234e0e1-9f4d-4bca-a68d-e8a177d24488&code=1381c0ff-7b90-4ee1-8304-f16c853f2457.1234e0e1-9f4d-4bca-a68d-e8a177d24488.e624b94f-f568-4249-9cb0-73f8c25b3955 403 59.105 ms - -
```

To test in a simpler framework I have

- an apache2 server (url https://m-serv.m.net ) acting as reverse proxy for port 3000
- a docker container running the same image deployed in kubernetes

In these conditions the test gives the results

- access unprotected page "https://m-serv.m.net": the page shows correctly
- access protected page "https://m-serv.m.net/pres/secured": the application redirect to the keycloak server
- the user authenticate with keycloak and is redirected to url "https://m-serv.m.net/pres/secured" and the protected page is shown

In this case the callback is visible only in the logs:
```
GET /pres/secured?auth_callback=1&state=307c0161-192a-418e-82fd-c36b22513887&session_state=8120c770-6763-4cb5-a84e-32fd193422c2&code=8c790088-87e6-46d1-bcb1-dd76764dd969.8120c770-6763-4cb5-a84e-32fd193422c2.e624b94f-f568-4249-9cb0-73f8c25b3955 302 104.896 ms - 70
```

**Logs for istio-proxy/application (error) and apache2/application( works correctly)**
[istio_log.txt](https://github.com/istio/istio/files/6364741/istio_log.txt)

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
sysop@m-serv:~$ istioctl version --remote
client version: 1.9.3
control plane version: 1.9.3
data plane version: 1.9.3 (6 proxies)
sysop@m-serv:~$ kubectl version --short
Client Version: v1.20.4
Server Version: v1.20.6+k3s1
sysop@m-serv:~$ 
```

**How was Istio installed?**
Istio 1.9.3 is installed using istio operator and setting a private CA certificate (as in bug [29366](https://github.com/istio/istio/issues/29366) solution)

**Environment where the bug was observed (cloud vendor, OS, etc)**
3 KVM virtual machines with Ubuntu 20.04
K3S master and two workers on the 3 virtual machines

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**UPDATE 2021/04/26**
Loking at the itstio-ingressgateway logs the operations sequence was:

**1)** user browser ask for "https://www.m.net/pres/secured"
**2)** istio-ingressgateway forward the request to the fpresenter application and in the istio-ingressgateway logs I see:
```
[2021-04-26T16:44:48.395Z] "GET /pres/secured HTTP/2" 302 - via_upstream - "-" 0 548 44 44 "10.42.0.1" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0" "387d5cd4-5769-9188-91a7-56e33fb77c25" "www.m.net" "10.42.1.6:3000" outbound|3000||fpresenter.m-project.svc.cluster.local 10.42.0.61:51784 10.42.0.61:8443 10.42.0.1:28398 www.m.net -
```
**3)** the fpresenter application redirects to the keycloak sever at "https://k6k.m.net/auth/realms/m-project".
**4)** the keycloak login windows shows up and the user can authenticate
**5)** the keycloak server sends back the to the "https://www.m.net/pres/secured" url adding the jwt token but this cause an error and in the user browser arriva an "**Access denied**" error. In the istio-ingressgateway logs I see:
```
[2021-04-26T16:44:52.422Z] "GET /pres/secured?auth_callback=1&state=4bc93ed1-dcb8-4282-88ca-c92c9cdc8011&session_state=774d1a0e-cd3f-4ffe-bb02-615ea3c8f987&code=0c49634e-8ea5-4ec7-b771-c378eabfc8d2.774d1a0e-cd3f-4ffe-bb02-615ea3c8f987.e624b94f-f568-4249-9cb0-73f8c25b3955 HTTP/2" 403 - via_upstream - "-" 0 13 49 27 "10.42.0.1" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0" "201bf77b-a399-9138-b621-e291daa1ee5a" "www.m.net" "10.42.1.6:3000" outbound|3000||fpresenter.m-project.svc.cluster.local 10.42.0.61:51784 10.42.0.61:8443 10.42.0.1:28398 www.m.net -
```

What can be the problem?
