### ISSUE TITLE
pilot-agent wait doesn't wait long enough on postStart

### ISSUE THREAD

**Issue by michaelst** [istio/istio#32439]
**Bug description**
After upgrading to 1.9.3 we are having issues where network requests are getting a econnrefused error on startup. 

We have the pod lifecycle set to use `pilot-agent wait` which was working on 1.8.1

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
The application container should not be allowed to start due to `pilot-agent wait` until network requests will succeed.

**Steps to reproduce the bug**

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: minimal
  meshConfig: 
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
  components:
    cni:
      enabled: true
      namespace: kube-system
  values:
    cni:
      cniBinDir: /home/kubernetes/bin
    global:
      proxy:
        excludeIPRanges: 10.0.0.0/8 # internal range covered by egress network policies
        lifecycle:
          postStart:
            exec:
              command:
              - pilot-agent
              - wait
          preStop:
            exec:
              command:
              - sleep
              - "30"
```

```
istioctl install -f istio/operator.yaml
kubectl rollout restart deployment --namespace xxx
```

**Version** 

client version: 1.9.3
control plane version: 1.9.3
data plane version: 1.9.3 (7 proxies)
Client Version: v1.20.4
Server Version: v1.18.16-gke.502
