### ISSUE TITLE
envoy code status 413

### ISSUE THREAD

**Issue by baoervsdier** [istio/istio#32449]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
The version of istio we installed is 1.7.4. One of the services returned a status code of 413. I understand that it should be to modify a parameter similar to max_request_bytes. I looked for the relevant configuration on the Internet, but after the test, it was found to have no effect. The status code is still 413, and the configuration is as follows:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: request-size-limit
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.buffer
          typed_config:
            '@type': type.googleapis.com/udpa.type.v1.TypedStruct
            value:
              maxRequestBytes: 104857600  # 100 MB
```
Error screenshot:
![image](https://user-images.githubusercontent.com/32762305/115990310-0c7cad00-a5f5-11eb-9d48-e2e421070e29.png)
