### ISSUE TITLE
VirtualService mismatch has no validation

### ISSUE THREAD

**Issue by hmthoo** [istio/istio#32451]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
```
The traffic from service A to service B is forwarded to the first ip of the endpoint through PassthroughCluster.
 Virtualservice does not appear to be working.
```

[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
App A version: stable upstream to App B version: stable
**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
# istioctl version --remote
client version: 1.9.3
control plane version: 1.9.3
data plane version: 1.9.3 (23 proxies)

# kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**
```
istioctl install  \
--set values.global.jwtPolicy=first-party-jwt \
--set components.pilot.enabled=true \
--set meshConfig.accessLogFile="/dev/stdout" \
--set values.global.logging.level=debug \
```

**my virtualservice and DestinationRule yaml**
```
# App B virtualservice and DestinationRule
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sophon
  namespace: canary
spec:
  hosts:
  - sophon-service 
  http:
  - match:
    - sourceLabels:
        version: canary
    route:
    - destination:
        host: sophon-service.canary.svc.cluster.local
        subset: canary
  - route:
    - destination:
        host: sophon-service.canary.svc.cluster.local
        subset: stable
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: sophon
  namespace: canary
spec:
  host: sophon-service
  subsets:
  - name: stable
    labels:
      version: stable
  - name: canary
    labels:
      version: canary


# App B virtualservice and DestinationRule
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: halo
  namespace: canary
spec:
  hosts:
  - halo-service 
  http:
  - match:
    - sourceLabels:
        version: canary
    route:
    - destination:
        host: halo-service.canary.svc.cluster.local
        subset: canary
  - route:
    - destination:
        host: halo-service.canary.svc.cluster.local
        subset: stable
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: halo
  namespace: canary
spec:
  host: halo-service
  subsets:
  - name: stable
    labels:
      version: stable
  - name: canary
    labels:
      version: canary
```

**my k8s yaml**
APP A
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sophon
    product: saas-pro
    version: stable
  name: sophon-service
  namespace: canary
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: sophon
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sophon
    product: saas-pro
    version: stable
  name: stable-sophon
  namespace: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sophon
      product: saas-pro
      version: stable
  template:
    metadata:
      labels:
        app: sophon
        product: saas-pro
        version: stable
    spec:
      containers:
        - env:
            - name: JAVA_OPTS
              value: >-
                -Dloader.path=lib/ -Dnacos.logging.path=logs/nacos
                -Duser.timezone=GMT+08 -Xmx1344M -Xms1344M -Xmn448M
                -XX:MaxMetaspaceSize=192M -XX:MetaspaceSize=192M
          image: 'xxx/ygjpro/sophon:202102181736'
          imagePullPolicy: Always
          name: sophon
          ports:
            - containerPort: 8080
              name: http
      imagePullSecrets:
        - name: harbor-secret
      serviceAccountName: saaspro
```

APP B
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: halo
    product: saas-pro
    version: stable
  name: halo-service
  namespace: canary
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: halo
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: halo
    product: saas-pro
    version: stable
  name: stable-halo
  namespace: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: halo
      product: saas-pro
      version: stable
  template:
    metadata:
      labels:
        app: halo
        product: saas-pro
        version: stable
    spec:
      containers:
        - env:
            - name: JAVA_OPTS
              value: >-
                -Dloader.path=lib/ -Dnacos.logging.path=logs/nacos
                -Duser.timezone=GMT+08 -Xmx1344M -Xms1344M -Xmn448M
                -XX:MaxMetaspaceSize=192M -XX:MetaspaceSize=192M
          image: 'xxx/ygjpro/halo:202102191511'
          imagePullPolicy: Always
          name: halo
          ports:
            - containerPort: 8080
              name: http
      imagePullSecrets:
        - name: harbor-secret
      serviceAccountName: saaspro
```
