### ISSUE TITLE
AuthorizationPolicy affects TCP ingress

### ISSUE THREAD

**Issue by ediezh** [istio/istio#32456]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
I have an ingress gateway accepts both http and tcp traffic as below:
```
- name: istio-ingressgateway-internal
  enabled: true
  label:
    istio: ingressgateway-internal
  k8s:
    imagePullPolicy: IfNotPresent
    env:
      - name: ISTIO_META_ROUTER_MODE
        value: sni-dnat
      - name: ISTIO_METAJSON_ANNOTATIONS
        value: |
          {"sidecar.istio.io/extraStatTags":"request_url"}
    readinessProbe:
      timeoutSeconds: 5
    hpaSpec:
      maxReplicas: 5
      metrics:
      - resource:
          name: cpu
          targetAverageUtilization: 80
        type: Resource
      minReplicas: 3
      scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: istio-ingressgateway-internal
    resources:
      limits:
        cpu: 2000m
        memory: 2048Mi
      requests:
        cpu: 500m
        memory: 1024Mi
    serviceAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
      service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "true"
    service:
      externalTrafficPolicy: Local
      ports:
      - name: status-port
        port: 15021
        targetPort: 15021
      - name: http2
        port: 80
        targetPort: 8080
      - name: https
        port: 443
        targetPort: 8443
      - name: grpc
        port: 10901
        targetPort: 10901
      - name: tls
        port: 15443
        targetPort: 15443
      - name: psql
        port: 5432
        targetPort: 5432
    strategy:
      rollingUpdate:
        maxSurge: 100%
        maxUnavailable: 25%
```

I created an authorizationpolicy to control the http traffic. This AuthorizationPolicy applies to all istio ingress gateways including the one above.
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: test-auth-policy
  namespace: istio-system
spec:
  action: DENY
  rules:
  - to:
    - operation:
        hosts:
        - test.example.com
        paths:
        - /healthz*
  - from:
    - source:
        notIpBlocks:
        - 10.202.0.0/16
        - 10.200.103.108/32
        - 10.0.1.0/24
    to:
    - operation:
        hosts:
        - test.example.com
        paths:
        - /api/v1/test/*
  selector:
    matchLabels:
      app: istio-ingressgateway
```

This AuthorizationPolicy causes the connection to port 5432 to fail. I have a psql virtualservice on port 5432.
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: psql-internal-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway-internal
  servers:
  - hosts:
    - '*'
    port:
      name: tcp-psql
      number: 5432
      protocol: TCP

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: postgres
  namespace: ds
spec:
  gateways:
  - istio-system/psql-internal-gateway
  hosts:
  - '*'
  tcp:
  - match:
    - port: 5432
    route:
    - destination:
        host: postgres
        port:
          number: 5432
```

I get the below error when trying to connect to postgres:
```
 ~/ psql -h 10.202.187.21 -p 5432 -U o8tsuperuser -d postgres
psql: error: could not connect to server: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

The connection worked fine before applying the authorizationpolicy. It also worked fine if I remove the authorizationpolicy.

Please advise.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.7.6

**How was Istio installed?**
Istio operator

**Environment where the bug was observed (cloud vendor, OS, etc)**
EKS 1.17

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
