### ISSUE TITLE
istio + outboundTrafficPolicy.mode = REGISTRY_ONLY + nodejs

### ISSUE THREAD

**Issue by jonbcampos-alto** [istio/istio#32453]
**Bug description**
I have a simple NodeJS tester that calls to google.com and cnn.com (to replicate the [Accessing External Services](https://istio.io/latest/docs/tasks/traffic-management/egress/egress-control/)). When testing against the service using the Curl + Sleep pod the endpoints are blocked or unblocked as appropriate based on the Service Entry. However from within my NodeJS application the service is never blocked. Is there some way that the NodeJS application needs to be setup to use this feature and communicate through the sidecar?

Example code for call below:
```typescript
export function call(url: string, data: any): Promise<any> {
  const parsed = parseURL(url);
  const request: AxiosRequestConfig = {
    method: "GET",
    url,
    headers: {
      Host: parsed?.host,
    },
  };
  logger.info(`call: ${url}`, request);
  return axios(request)
    .then((results: AxiosResponse<string>) => {
      logger.info(`[${results.status}] ${url} completed`, {
        siteData: results.data.slice(0, 1000),
      });
      return data;
    })
    .catch((e) => {
      logger.error("call error");
      logger.error(e);
      return data;
    });
}
```

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**
- Create GKE cluster
- Install Istio 1.9.2 with operator
- install NodeJS callling google.com and cnn.com
- View that calls are successful

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
client version: 1.9.2
control plane version: 1.9.2
data plane version: 1.9.2 (9 proxies)

**How was Istio installed?**
operator, yaml file included
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
  namespace: istio-system
spec:
  profile: default
  components:
    egressGateways:
      - name: istio-egressgateway
        enabled: true
  meshConfig:
    enableTracing: true
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
    defaultConfig:
      tracing:
        sampling: 100.0
        zipkin:
          address: "tracing-collector.telemetry:9411"
  values:
    gateways:
      istio-ingressgateway:
        loadBalancerIP: "load balancer IP address"
        secretVolumes:
          - mountPath: /etc/istio/grafana-gateway-certs
            name: grafana-gateway-certs
            secretName: istio-grafana-gateway-certs
          - mountPath: /etc/istio/kiali-gateway-certs
            name: kiali-gateway-certs
            secretName: istio-kiali-gateway-certs
        type: LoadBalancer
    global:
      proxy:
        includeIPRanges: "cluster specific IP Range for GCP"
        excludeIPRanges: "recommended exclude IP Range"
    telemetry:
      v2:
        stackdriver:
          enabled: true
          monitoring: true
          topology: true

```

**Environment where the bug was observed (cloud vendor, OS, etc)**
GKE v1.19.8-gke.1600

Additionally, please consider running `` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by jonbcampos-alto** [comment]
[bug-report.tgz.zip](https://github.com/istio/istio/files/6373392/bug-report.tgz.zip)

**Comment by jonbcampos-alto** [comment]
full application code
```typescript
import axios, {AxiosRequestConfig, AxiosResponse} from "axios";

require("module-alias/register");

if (process.env.env !== "development") {
  const {name, version} = require("../package.json");
  require("@google-cloud/trace-agent").start({
    serviceContext: {
      service: name,
      version: version,
    },
  });
  require("@google-cloud/profiler").start({
    serviceContext: {
      service: name,
      version: version,
    },
  });
}
import * as http from "http";
import {AddressInfo} from "net";
import express, {Application} from "express";
import morgan from "morgan";
import {StatusCodes} from "http-status-codes";

class Server {
  constructor() {
    this.appHttpServer = this.startApp(3000, () => {
      const app: Application = express();
      app.use(morgan("dev"));
      app.use(express.json());
      app.get("/?", (req, res) => {
        res.set("Content-Type", "application/json");
        res.status(StatusCodes.OK).json({});
      });
      setInterval(() => {
        this.call("http://www.google.com")
          .then(() => this.call("http://edition.cnn.com"))
          .then(() => {
            console.log("run complete");
          });
      }, 30_000);
      return app;
    });
    this.k8sHttpServer = this.startApp(8001, () => {
      const app: Application = express();
      app.use(morgan("dev"));
      app.use(express.json());
      app.get("/healthcheck", require("express-healthcheck")());
      app.get("/readiness", function (req, res, next) {
        res.set("Content-Type", "application/json");
        res.status(StatusCodes.OK).json({ready: true});
      });
      return app;
    });
  }

  public appHttpServer: http.Server;
  public k8sHttpServer: http.Server;

  private call(url: string): Promise<any> {
    const request: AxiosRequestConfig = {
      method: "GET",
      url
    };
    console.log(`call: ${url}`, request);
    return axios(request)
      .then((results: AxiosResponse<string>) => {
        console.log(`[${results.status}] ${url} completed`, {
          siteData: results.data.slice(0, 1000),
        });
      })
      .catch((e) => {
        console.error("call error");
        console.error(e);
      });
  }

  private startApp(port: number, project: () => Application): http.Server {
    const server: http.Server = project().listen(port, () => {
      const activePort = (server.address() as AddressInfo).port;
      console.log(`App listening on port ${activePort}`);
    });
    return server;
  }
}

// ------------------------------------
// shutdown
// ------------------------------------
process.on("SIGTERM", function () {
  // cleanup environment, this is about to be shut down
  process.exit(0);
});

const activeServer = new Server();
export const applicationServer = activeServer.appHttpServer;
export const k8sServer = activeServer.k8sHttpServer;

```

**Comment by jonbcampos-alto** [comment]
yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  name: request
  labels:
    app: request
    service: request
spec:
  ports:
    - port: 80
      name: http-request
      protocol: TCP
      targetPort: 8080
  selector:
    app: request
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: request
spec:
  replicas: 1
  selector:
    matchLabels:
      app: request
  template:
    metadata:
      labels:
        app: request
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: request
          image: gcr.io/gcp-project/request:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: env
              value: production
          livenessProbe:
            failureThreshold: 3
            httpGet:
              port: 8001
              path: /healthcheck
              scheme: HTTP
            initialDelaySeconds: 40
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              port: 8001
              path: /readiness
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          ports:
            - containerPort: 8080
              name: request
              protocol: TCP
---

```
