### ISSUE TITLE
IstioOperator don't separate all configuration between proxy and proxy_init

### ISSUE THREAD

**Issue by wolfmah** [istio/istio#32452]
**Bug description**
I want to override the default values for the proxy sidecar as well as the proxy initContainer. When setting different values for both, values from the proxy configuration are applied to both the sidecar and initContainer.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Having the proxy initContainer get the values specified in the configuration.

**Steps to reproduce the bug**
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-default
spec:
  profile: default
  tag: 1.8.3
  values:
    global:
      istioNamespace: istio-system
      proxy:
        autoInject: enabled
        logLevel: warning
        resources:
          requests:
            cpu: 300m
            memory: 150Mi
          limits:
            cpu: 400m
            memory: 350Mi
      proxy_init:
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: 200m
            memory: 128Mi
```

Using this config to start IstioOperator should yeild different requests/limits for the two proxy containers, but all the values will end up with `proxy` requests/limits, ignoring `proxy_init`.

Code reference: https://github.com/istio/istio/blob/21a12a752207e3328ad44f2fbd3cb612ef30b9c7/manifests/charts/istio-control/istio-discovery/files/injection-template.yaml#L93-L116

If it's by design, the documentation should point out that `proxy_init` only support modifying the image; anything else will be ignore.

**Version**
`istioctl version --remote`: 
```bash
client version: 1.9.3
control plane version: 1.8.3
data plane version: 1.8.3 (51 proxies)
```

`kubectl version --short`: 
```bash
Client Version: v1.21.0
Server Version: v1.18.9-eks-d1db3c
```

**How was Istio installed?**
Via Kustomize. Got the manifests by exporting the Helm chart result.

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS EKS
