### ISSUE TITLE
filter chain not found when using tls mode passthrough

### ISSUE THREAD

**Issue by yalctay93** [istio/istio#32466]
Hello,

we are trying to configure a the following TLS route:

```yaml
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: haproxy-gw
  namespace: haproxy
spec:
  selector:
    app: test-ingressgateway
  servers:
  - port:
      number: 30000
      name: tls-haproxy
      protocol: TLS
    tls:
      mode: PASSTHROUGH
    hosts:
    - "test-ingressgateway.com"
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: haproxy-se
  namespace: haproxy
spec:
  hosts:
  - test-destination.com
  ports:
  - number: 5671
    name: tls-haproxy
    protocol: TLS
  location: MESH_EXTERNAL
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: haproxy-vs
  namespace: haproxy
spec:
  hosts:
  - "test-ingressgateway.com"
  gateways:
  - haproxy-gw
  tls:
  - match:
    - port: 30000
      sniHosts:
      - test-ingressgateway.com
    route:
    - destination:
        host: test-destination.com
        port:
          number: 5671
EOF
```

However, any request sent to test-ingressgateway.com:30000 fails with the following error in the istio-ingressgateway:

```bash
{"x_forwarded_for":null,"response_flags":"NR","upstream_cluster":null,"downstream_local_address":"192.168.131.212:30000","bytes_received":0,"authority":null,"request_id":null,"connection_termination_details":null,"method":null,"requested_server_name":null,"upstream_service_time":null,"upstream_local_address":null,"response_code_details":"filter_chain_not_found","protocol":null,"downstream_remote_address":"192.168.0.188:45881","upstream_host":null,"route_name":null,"bytes_sent":0,"start_time":"2021-04-26T15:34:43.455Z","upstream_transport_failure_reason":null,"path":null,"response_code":0,"user_agent":null,"duration":10}
{"response_flags":"NR","upstream_local_address":null,"response_code_details":"filter_chain_not_found","authority":null,"connection_termination_details":null,"protocol":null,"upstream_transport_failure_reason":null,"response_code":0,"request_id":null,"user_agent":null,"downstream_remote_address":"192.168.0.100:48759","route_name":null,"upstream_host":null,"requested_server_name":null,"downstream_local_address":"192.168.131.212:30000","x_forwarded_for":null,"upstream_cluster":null,"path":null,"upstream_service_time":null,"start_time":"2021-04-26T15:34:46.608Z","bytes_sent":0,"method":null,"duration":40,"bytes_received":0}
{"downstream_local_address":"192.168.131.212:30000","requested_server_name":null,"request_id":null,"upstream_local_address":null,"x_forwarded_for":null,"response_code":0,"authority":null,"protocol":null,"start_time":"2021-04-26T15:34:46.608Z","upstream_host":null,"user_agent":null,"path":null,"response_code_details":"filter_chain_not_found","upstream_cluster":null,"method":null,"response_flags":"NR","upstream_transport_failure_reason":null,"upstream_service_time":null,"downstream_remote_address":"192.168.0.46:4953","bytes_sent":0,"duration":40,"route_name":null,"connection_termination_details":null,"bytes_received":0}
{"route_name":null,"requested_server_name":null,"connection_termination_details":null,"x_forwarded_for":null,"bytes_received":0,"duration":40,"path":null,"response_code_details":"filter_chain_not_found","protocol":null,"downstream_remote_address":"192.168.0.188:57121","upstream_cluster":null,"upstream_host":null,"response_code":0,"start_time":"2021-04-26T15:34:46.608Z","upstream_local_address":null,"method":null,"bytes_sent":0,"response_flags":"NR","upstream_transport_failure_reason":null,"user_agent":null,"authority":null,"request_id":null,"downstream_local_address":"192.168.131.212:30000","upstream_service_time":null}
{"request_id":null,"route_name":null,"response_code_details":"filter_chain_not_found","protocol":null,"bytes_sent":0,"upstream_transport_failure_reason":null,"upstream_service_time":null,"x_forwarded_for":null,"start_time":"2021-04-26T15:34:46.650Z","downstream_local_address":"192.168.131.212:30000","authority":null,"response_code":0,"duration":3,"upstream_cluster":null,"upstream_local_address":null,"connection_termination_details":null,"downstream_remote_address":"192.168.0.188:58045","response_flags":"NR","method":null,"bytes_received":0,"user_agent":null,"requested_server_name":null,"path":null,"upstream_host":null}

```

Envoy gives us this error message, but its rather hard to solve because its not very specific:
```"response_code_details":"filter_chain_not_found"``` 

Our istio-ingressgateway runs with no issues at all. Any HTTP/HTTPS traffic works with no problems. Just this setup on port 30000 and tls mode set to passthrough/simple does not work. Of course, when we set the tls.mode to "simple" we also provide a serverCertificate and privateKey - the result is the same.

Disabling tls mode and setting the protocol to TCP works, however that is not what we want. As soon as TLS mode is configured in the Gateway, the above error occurs.

Here is our service deployment for the istio-ingressgateway (I removed the loadBalancerIP for security reasons):

```yaml
spec:
  clusterIP: 192.168.104.215
  clusterIPs:
  - 192.168.104.215
  externalTrafficPolicy: Cluster
  loadBalancerIP: x.x.x.x
  loadBalancerSourceRanges:
  - x.x.x.x/x
  ports:
  - name: http
    nodePort: 39010
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 34012
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: tls
    nodePort: 31142
    port: 30000
    protocol: TCP
    targetPort: 30000
  - name: status-port
    nodePort: 40975
    port: 15021
    protocol: TCP
    targetPort: 15021
  selector:
    app: test-ingressgateway
    istio: ingressgateway
  sessionAffinity: None
  type: LoadBalancer
```

Any help in order to narrow down our faulty configuration is HIGHLY appreciated!
