### ISSUE TITLE
envoyfilter routeConfiguration can not apply,no affect,envoyfilter and virtualservice with is processed first

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#32478]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
envoyfilter routeConfiguration can not apply

[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

apply the following config:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: apply-to
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: ROUTE_CONFIGURATION
    match:
      context: ANY
      routeConfiguration:
        portNumber: 8080
        name: http.80
    patch:
      operation: MERGE
      value:
            name: http.80
            virtual_hosts:
            - name: "*:80"
              domains:
              - "*"
              cors:
                allow_methods: "GET,POST,OPTIONS"
                allow_headers: "content-type"
                max_age: "60"
                allow_origin_string_match:
                - exact: "http://mytest.com:8081"
                filter_enabled:
                  default_value:
                    numerator: 100
                    denominator: HUNDRED
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
[root@master01 cors]# istioctl version --remote
client version: 1.9.2
control plane version: 1.9.2
data plane version: 1.9.2 (12 proxies)

[root@master01 cors]# kubectl version --short
Client Version: v1.20.5
Server Version: v1.20.5
**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
