### ISSUE TITLE
istioctl generated ValidatingWebhookConfiguration doesn't use the correct service with revision

### ISSUE THREAD

**Issue by bvandewalle** [istio/istio#32477]
**Bug description**

We are using istioctl to generate all the objects to deploy 1.9.3. We are using a revision tag as we deploy it with a canary dual control plane. The revision tag is in this case set to `1-9`

All the objects seem to correctly version themselves with the revision tag, except the ValidatingWebhookConfiguration which is generated with the following endpoint, missing the revision tag:

```
webhooks:
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    caBundle: ""
    service:
      name: istiod
      namespace: istio-system
      path: /validate
 ```

What is expected is to have:

```
webhooks:
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    caBundle: ""
    service:
      name: istiod-1-9
      namespace: istio-system
      path: /validate
```

Or was this intended in order to use the previous istiod installation for the validating webhook?

[ ] Docs
[ x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Comment by bvandewalle** [comment]
After digging a bit, this seem to be the same issue as :

- https://github.com/istio/istio/issues/27501
- https://github.com/istio/istio/issues/32143

What made it very confusing and slightly different in my case is that we had a service called `istiod` in the `istio-system` namespace (our previous version of istio), which means that the `ValidatingWebhookConfiguration` was accepted by K8S API, and it took us a bit of retro engineering to figure out that the new `ValidatingWebhookConfiguration` was sending the request to the old istio.

**Comment by BobVanB** [comment]
Something else i noticed, there are 2 different ValidatingWebhookConfiguration in the master branch.  
Didn't have time to look into it yet, but this doesn't feel okay.

`Commit: f38465f8f5c1edd944ed7776c1253ffa2d9768b2`
`./main manifest generate ...`

```
kind: ValidatingWebhookConfiguration
metadata:
  name: istiod-1-10-0
  labels:
    app: istiod
    release: istio
    istio: istiod
    istio.io/rev: 1-10-0
```

```
kind: ValidatingWebhookConfiguration
metadata:
  name: istiod-istio-system
  labels:
    app: istiod
    release: istio
    istio: istiod
```
