### ISSUE TITLE
HTTP/1.1 CONNECT - 404 NR

### ISSUE THREAD

**Issue by nicole-chen-fivestars** [istio/istio#32494]
I am exploring HTTP/1.1 CONNECT with istio. 

To demonstrate the problem, let's use this example from [verygoodsecurity](https://www.verygoodsecurity.com/docs/code-samples):
```
curl https://echo.apps.verygood.systems/post -k \
  -x USiyQvWcT7wcpy8gvFb1GVmz:2b48a642-615a-4b3c-8db5-e02a88147174@tntsfeqzp4a.sandbox.verygoodproxy.com:8080 \
  -H "Content-type: application/json" \
  -d '{"account_number": "tok_sandbox_w8CBfH8vyYL2xWSmMWe3Ds"}'
```

I'm developing this in Kubernetes, and first executed the above curl inside my container that has an envoy sidecar container within the pod. 

```
$ curl https://echo.apps.verygood.systems/post -k \
>   -x USiyQvWcT7wcpy8gvFb1GVmz:2b48a642-615a-4b3c-8db5-e02a88147174@tntsfeqzp4a.sandbox.verygoodproxy.com:8080 \
>   -H "Content-type: application/json" \
>   -d '{"account_number": "tok_sandbox_w8CBfH8vyYL2xWSmMWe3Ds"}'
curl: (56) Received HTTP code 404 from proxy after CONNECT
```
Here's the istio access log, which shows a 404 NR response:
```
{"connection_termination_details":null,"upstream_transport_failure_reason":null,"response_code":404,"upstream_local_address":null,"upstream_cluster":null,"bytes_received":0,"start_time":"2021-04-27T23:49:26.872Z","response_code_details":"route_not_found","upstream_host":null,"authority":"echo.apps.verygood.systems:443","x_forwarded_for":null,"downstream_remote_address":"redacted","method":"CONNECT","upstream_service_time":null,"requested_server_name":null,"bytes_sent":0,"response_flags":"NR","request_id":"f00483aa-f254-423f-9bb6-afcba8a8062a","path":null,"route_name":null,"downstream_local_address":"redacted","user_agent":"curl/7.64.0","protocol":"HTTP/1.1","duration":0}
```

I then added a Service Entry per Istio's [Using an External HTTPS Proxy](https://istio.io/latest/docs/tasks/traffic-management/egress/http-proxy/) doc:
```
spec:
    hosts:
    - tntsfeqzp4a.sandbox.verygoodproxy.com
    addresses:
    - 3.215.204.48
    - 3.215.240.222
    - 107.20.75.87
    location: MESH_EXTERNAL
    ports:
    - name: tcp
      number: 8080
      protocol: TCP
```

Adding this SE indeed helped the request to succeed. The curl succeeded and the access log:
```
{"upstream_host":"redacted","method":null,"path":null,"route_name":null,"upstream_cluster":"outbound|8080||tntsfeqzp4a.sandbox.verygoodproxy.com","response_flags":"-","upstream_service_time":null,"request_id":null,"upstream_transport_failure_reason":null,"response_code":0,"duration":186,"start_time":"2021-04-23T00:01:57.845Z","downstream_remote_address":"redacted","authority":null,"connection_termination_details":null,"upstream_local_address":"redacted","response_code_details":null,"downstream_local_address":"redacted","user_agent":null,"protocol":null,"bytes_received":1171,"bytes_sent":3370,"x_forwarded_for":null,"requested_server_name":null}
```

My questions:

1. Is there a way to set up HTTP/1.1 CONNECT to succeed WITHOUT specifying IP addresses? The external API I use doesn't guarantee static IPs. 
2. Why does istio require a Service Entry here for HTTP/1.1 CONNECT succeed?

**Comment by nicole-chen-fivestars** [comment]
hi @sridharlreddy, it turns out I was mistaken about my original problem, and that there had been a service entry created for `sandbox.verygoodproxy.com` in another namespace but its effect was cluster wide and I didn't realize.

I updated my original thread with new questions - would appreciate any feedback!

**Comment by sridharlreddy** [comment]
1. Addresses is optional and needed only when you use IP address instead of hostname. You can remove 
2. Istio does not support HTTP CONNECT yet, hence if CONNECT is used i.e if http proxy is used, it should be defined as TCP instead of HTTP.

ServiceEntries are visible to all namespaces by default unless scoped using exportTo.

**Comment by nicole-chen-fivestars** [comment]
Hi @sridharlreddy, when I don't provide an IP address, like so:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: vgs
spec:
  hosts:
  - sandbox.verygoodproxy.com
  ports:
  - number: 8080
    name: https-port
    protocol: TCP
  resolution: DNS
  location: MESH_EXTERNAL
```

I get 404 NR error from istio when I do the curl command:
```
curl https://echo.apps.verygood.systems/post -k \
  -x USiyQvWcT7wcpy8gvFb1GVmz:2b48a642-615a-4b3c-8db5-e02a88147174@tntsfeqzp4a.sandbox.verygoodproxy.com:8080 \
  -H "Content-type: application/json" \
  -d '{"account_number": "tok_sandbox_w8CBfH8vyYL2xWSmMWe3Ds"}'
```

Here's the access log:
```
{"start_time":"2021-05-03T22:22:29.288Z","duration":0,"response_code_details":"route_not_found","response_flags":"NR","authority":"echo.apps.verygood.systems:443","x_forwarded_for":null,"upstream_service_time":null,"upstream_host":null,"bytes_received":0,"upstream_cluster":null,"downstream_remote_address":"redacted","user_agent":"curl/7.64.0","response_code":404,"protocol":"HTTP/1.1","upstream_local_address":null,"route_name":null,"path":null,"request_id":"312b1257-8e7b-4f3b-98ec-3bc8762fdfde","connection_termination_details":null,"downstream_local_address":"redacted","upstream_transport_failure_reason":null,"bytes_sent":0,"method":"CONNECT","requested_server_name":null}
```

 Any guidance there?

**Comment by nicole-chen-fivestars** [comment]
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: vgs
spec:
  hosts:
  - sandbox.verygoodproxy.com
  ports:
  - number: 8080
    name: tcp-port
    protocol: TCP
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: connect-proxy
spec:
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: SIDECAR_OUTBOUND
      routeConfiguration:
        portNumber: 8080
        vhost:
          name: "allow_any"
    patch:
      operation: MERGE
      value:
        name: "proxy-connect"
        match:
          connect_matcher: {"8080"}
        route:
          upgrade_configs:
          - upgrade_type: CONNECT
            connect_config: {}
```

This is my latest config that has gotten me past the CONNECT error. I'm seeing an access log of 200 on CONNECT. But, I am now getting an SSLError which I had not been getting before this istio adoption:

```
$ curl https://echo.apps.verygood.systems/post -k \
>   -x USiyQvWcT7wcpy8gvFb1GVmz:2b48a642-615a-4b3c-8db5-e02a88147174@tntsfeqzp4a.sandbox.verygoodproxy.com:8080 \
>   -H "Content-type: application/json" \
>   -d '{"account_number": "tok_sandbox_w8CBfH8vyYL2xWSmMWe3Ds"}'
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

Any guidance here appreciated! I'm not sure if there's something I'm missing about the networking layer.

**Comment by sridharlreddy** [comment]
> Hi @sridharlreddy, when I don't provide an IP address, like so:
> 
> ```
> apiVersion: networking.istio.io/v1alpha3
> kind: ServiceEntry
> metadata:
>   name: vgs
> spec:
>   hosts:
>   - sandbox.verygoodproxy.com
>   ports:
>   - number: 8080
>     name: https-port
>     protocol: TCP
>   resolution: DNS
>   location: MESH_EXTERNAL
> ```
> 
> I get 404 NR error from istio when I do the curl command:
> 
> ```
> curl https://echo.apps.verygood.systems/post -k \
>   -x USiyQvWcT7wcpy8gvFb1GVmz:2b48a642-615a-4b3c-8db5-e02a88147174@tntsfeqzp4a.sandbox.verygoodproxy.com:8080 \
>   -H "Content-type: application/json" \
>   -d '{"account_number": "tok_sandbox_w8CBfH8vyYL2xWSmMWe3Ds"}'
> ```
> 
> Here's the access log:
> 
> ```
> {"start_time":"2021-05-03T22:22:29.288Z","duration":0,"response_code_details":"route_not_found","response_flags":"NR","authority":"echo.apps.verygood.systems:443","x_forwarded_for":null,"upstream_service_time":null,"upstream_host":null,"bytes_received":0,"upstream_cluster":null,"downstream_remote_address":"redacted","user_agent":"curl/7.64.0","response_code":404,"protocol":"HTTP/1.1","upstream_local_address":null,"route_name":null,"path":null,"request_id":"312b1257-8e7b-4f3b-98ec-3bc8762fdfde","connection_termination_details":null,"downstream_local_address":"redacted","upstream_transport_failure_reason":null,"bytes_sent":0,"method":"CONNECT","requested_server_name":null}
> ```
> 
> Any guidance there?

hostname in service entry and request are different. Create service entry with correct hostname and try, that should solve your issue. If you have multiple list all and if you have too many hostnames to be matched, then use wildcard *.sandbox.verygoodproxy.com with resolution: NONE

**Comment by luboszk** [comment]
@sridharlreddy Can you point us in the direction of the documentation which describes why Istio does not support `CONNECT`? Based on Envoy's documentation `CONNECT` should be supported, but in `HTTP/1.1` it needs an additional `connect_matcher` which you can't configure via Istio currently ([docs](https://www.envoyproxy.io/docs/envoy/latest/faq/debugging/why_is_envoy_404ing_connect_requests)).

The problem with that request is that it's a PROXY connection. So Envoy should establish a TCP connection tunnel with `VGS` which then should be used to send requests to the other system. When `SE` is being created without addresses, it seems that Envoy is not able to match that `SE` config with the IP. Adding addresses section fixes the problem but it has its own downside that we need to manage that list of IP addresses instead of looking up them from DNS.

**Comment by sridharlreddy** [comment]
@nicole-chen-fivestars Thats the catch for ServiceEntry without addresses. If address is defined, destination is identified based on ip and port. If there is no address defined, any traffic that matches the port will be sent to the service. So you should avoid sharing the port in such scenarios. Please refer to this for detailed description https://istio.io/latest/docs/reference/config/networking/service-entry/#ServiceEntry-addresses.

In your case, looks like you have a rule that matches ALL HTTP(/*) on 8080, you can check with the command below.

`istioctl proxy-config routes sleep --name 8080`

**Comment by nicole-chen-fivestars** [comment]
@sridharlreddy Thanks, I'd like to clarify my understandings:

1. If the address is defined, envoy identifies route based on ip/port and forwards the traffic. Is this only for TCP cases? Based on the doc (For HTTP traffic, generated route configurations will include http route domains for both the addresses and hosts field values and the destination will be identified based on the HTTP Host/Authority header), I'm guessing HTTP traffic can also be identified based on HTTP Host (i.e. not solely based on port even if IP isn't specified)?

2. If address isn't defined, envoy identifies route based on port only. Here's where I'm confused - I saw this article https://istio.io/latest/blog/2020/dns-proxy/#external-tcp-services-without-vips about envoy blindly forwarding traffic when the ServiceEntry is defined without address, as TCP, with resolution: NONE. So I expected this to work:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: vgs
spec:
  hosts:
  - sandbox.verygoodproxy.com
  ports:
  - number: 8080
     name: tcp
     protocol: TCP
  resolution: NONE
  location: MESH_EXTERNAL
```
Does it not work in the CONNECT case because CONNECT requires finding a route match rather than blindly forwarding the traffic?

**Comment by sridharlreddy** [comment]
@nicole-chen-fivestars My bad I missed to mention, yes thats for TCP as ip and port are the options to identify TCP traffic. For HTTP, domain, path and headers can be  used.
For 2 not working it is not related to CONNECT, as I said previously you have to routes defined on 8080 one HTTP and one TCP.

![image](https://user-images.githubusercontent.com/2922487/118071820-1f57f580-b3db-11eb-8166-1d33be153ad0.png)

**Comment by nicole-chen-fivestars** [comment]
@sridharlreddy I understand I have two routes defined on 8080. My confusion comes from this: I have 2 other databases defined as follows and egress traffic to both databases are ok. Why is my traffic to the database on port 8080 successful, but not for my HTTP/1.1 CONNECT traffic to sandbox.verygoodproxy.com on port 8080?

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: db
spec:
  hosts:
  - <Database DNS>
  ports:
  - number: 8080
     name: tcp
     protocol: TCP
  resolution: NONE
  location: MESH_EXTERNAL
```
