### ISSUE TITLE
Istio API support for envoy ext_proc

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#32490]
Envoy [External Process Filter](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_proc/v3alpha/ext_proc.proto) creates a deeper integration filter than ext_authz. This filter has full streaming access to all data, headers that trailers. At present this only supports http.

Istio support Wasm as an extension mechanism.

However ext_proc enables additional use cases
1. If the Wasm sandbox is more restrictive than a user can tolerate.
2. If a user has existing libraries in non-wasm languages, it is easier to write extensions in that language. This is similar to Out-of-process Mixer adapters.

What ext_proc will not give you is any process management. The user will be on the hook to manage and scale the ext_proc service.

Options
1. Add ext_proc as another extensionProvider similar to ext_authz
2. Ask users to use EnvoyFilter api :-( 

@kyessenov @gbrail

**Comment by migueleliasweb** [comment]
Can we open this issue back again?

The ext-proc filter is super powerful but the barrier to entry, due users having to deal with patches to the raw Envoy, is just too high.

Making ext-proc easily supported from Istio will bring loads of more options.

🙏

**Comment by migueleliasweb** [comment]
EnvoyGateway seems to natively support injecting Envoy Ext Proc via a super nice interface (CRD). Could Istio take some inspiration from it?

https://gateway.envoyproxy.io/docs/tasks/extensibility/ext-proc/

**Comment by migueleliasweb** [comment]
I've been digging a bit trying to understand how EnvotGateway handles `ext_proc`. I've found a few things:

- https://github.com/envoyproxy/gateway/blob/main/internal/xds/translator/extproc.go - XDS translator that handles generating the actual Envoy config
- https://github.com/envoyproxy/gateway/blob/main/api/v1alpha1/ext_proc_types.go#L64
- https://github.com/envoyproxy/gateway/blob/main/internal/ir/xds.go - Intermediate Representation (I think this is used between the CRD and the final XDS representation)

**Comment by dprotaso** [comment]
One limitation of ext-proc in envoy gateway is the ability to attach it to a Kubernetes Service. They don't map k8s services to v3.clusters cleanly (ref: https://github.com/envoyproxy/gateway/issues/5307)

**Comment by migueleliasweb** [comment]
I hope when using the `EnvoyFilter` CRD and implementing it using Istio instead, I can use service names directly and leverage the underlying Istio gRPC load balancing.

I'll report back with findings when I get further with my implementation. 🖖

**Comment by migueleliasweb** [comment]
> One limitation of ext-proc in envoy gateway is the ability to attach it to a Kubernetes Service. They don't map k8s services to v3.clusters cleanly (ref: [envoyproxy/gateway#5307](https://github.com/envoyproxy/gateway/issues/5307))

Could you expand on why would this be a problem?

Are you talking about the fact that the gateway itself needs to reach out to a given service so it can perform the mutations in the requests yeah? There are other challenges as well like the fact gRPC cannot be easily load balanced using the kube-proxy (but this might be fine as the service that contains the EnvoyFilter will also be part of the mesh?)

If so, I was thinking on two options to workaround the limitation you mentioned:

1. Create a second gateway and place it in front of the service that contains the envoy filter and add a service entry for that. I hope that's enough to map things correctly.
2. Add the VS for the EnvoyFilter service directly to the new Gateway that will call it 🤞 

I'll report back once I have something funcitonal.

**Comment by migueleliasweb** [comment]
I've been working for almost a month now on building an External Processor on Envoy (via Istio) and after getting it working the way I wanted, I wanted to share some of my findings.

My findings (a brain dump):

- There is NO WAY to call a ServiceEntry directly from an EnvoyFilter (with ExternalProcessor config) as the module that makes the call (as far as I could tell) is NOT quite part of the mesh and behaves as a normal client from within your Kubernetes Cluster. This client is unable to properly terminate Istio's mTLS and/or talk directly to the internal service registry (from ServiceEntries). With this in mind, your External Processor service will have to accept normal TLS instead of relying on Istio's mTLS magic. See this comment for more info: https://github.com/istio/istio/issues/32490#issuecomment-2668989896.
- Follow the upstream example from https://github.com/envoyproxy/gateway/blob/main/examples/grpc-ext-proc/main.go to create a gRPC server that is able to receive RPC calls from Envoy and properly generate mutations to then Envoy can patch them to the original request.
- If you want your gRPC server to be production ready, you likely want TLS between your server and Envoy. You can achive this by managing your own TLS certs with cert-manager but you will need to also manage their renewal process both in Envoy (with `channel_credentials`) and inside your own Go code. Although possible, I'd recommend not to do this and instead place an internal load balancer + a separate Istio Gateway in front of this new service and get the load balancer endpoint and place it on your EnvoyFilter configuration for the External Processor.
- Yes, you'll likely need 2 gateways
    - One is the real Gateway that will be matched on the EnvoyFilter configuration
    - One is the Gateway to allow TLS (externally) + mTLS (internally) for your External Processor code (likely in Go?)
- There are plenty of landmines to avoid when setting up the VirtualServices and ServiceEntries
    - Triple check everything. Trust me.
    - When setting up the VS, make sure the service doesn't NOT HAVE THE MESH GATEWAY unles you want to match your External Processor to every single worload within your cluster. You probably don't want to funnel every single request in your cluster through a single service.
- Check the below manifest for the EnvoyFilter

EnvoyFilter:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: my-envoy-filter
  namespace: myns
spec:
  workloadSelector:
    labels:
      # This MUST match labels from the deployment linked to an Istio GW
      istio: ingressgateway 
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      # Ensures the ext-proc is always called before matching ANY other routes
      operation: INSERT_FIRST 
      value:
        name: envoy.filters.http.ext_proc
        typed_config:
          "@type": type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: "type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor"
          value:
            stat_prefix: my-ext-proc  # stat prefix gets added into ext proc metrics name
            failure_mode_allow: false # If true, allow requests to continue if the gRPC cal fails
            mutation_rules: # See reference: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/common/mutation_rules/v3/mutation_rules.proto#envoy-v3-api-msg-config-common-mutation-rules-v3-headermutationrules
              allow_all_routing: true
            message_timeout: "2s"
            processing_mode: # See reference: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_proc/v3/processing_mode.proto#envoy-v3-api-msg-extensions-filters-http-ext-proc-v3-processingmode
              request_header_mode: "SKIP"
              response_header_mode: "SEND"
            grpc_service:
              google_grpc: # We want to use Google's implementation because of: https://github.com/envoyproxy/envoy/issues/22727
                retry_policy:
                  num_retries: 5
                  # Most cases, errors will fall under `internal`
                  # See: https://www.envoyproxy.io/docs/envoy/v1.34.1/configuration/http/http_filters/router_filter#config-http-filters-router-x-envoy-retry-grpc-on
                  retry_on: "cancelled,deadline-exceeded,internal,unavailable"
                  retry_back_off:
                    base_interval:
                      milliseconds: 100
                    max_interval:
                      milliseconds: 250
                # Needed for TLS based endpoints - Using the "defaults" with `{}` will only  
                # work for publicly trusted certificates (such as LetsEncrypt)!!!!!
                channel_credentials: 
                    ssl_credentials: {}
                stat_prefix: somethingnotused
                # You must not use internal K8s service names here such as
                # mysvc.myns.svc.cluster.local due to the fact that Kubernetes (KubeProxy)
                # is unable to proprely load balance gRPC requests!!!
                #
                # You cannot rely on internal service names from ServiceEntries either as this
                # module doesn't have access to that info. The endpoint must answer with normal TLS.
                #
                # This would ideally be an endpoint for an internal load balancer
                # linked to an Istio GW so then you can safety make changes to the
                # underlying code and via "Istio subnets" and have concurrent active versions
                # of your underlying External Processor code. With an Istio GW in front of your
                # service that handles the gRPC calls from Envoy, you also avoid managing
                # yourself a TLS cert. There are options here to inject custom certs but
                # you will have to not only patch the GW but also manage the hot-reload
                # capabilities on your own service. I'd avoid that if I was you.
                target_uri: "this-url-must-not-be-part-of-the-mesh:443"
```
