### ISSUE TITLE
Ingressgateways return 404 HTTP code when there are two Gateways with the same host on different ingressgateways

### ISSUE THREAD

**Issue by kovalyukm** [istio/istio#32533]
We noticed the issue during replacing of the ingressgateway to another one using blue-green deployment. Both are in the separate namespaces.

**Steps to reproduce the bug**
- Create new ingressgateway and wildcard Certificate in new namespace
istioctl part:
```yaml
    - namespace: istio-ingressgateway-temp
      name: ingress-temp
      enabled: true
      k8s:
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
          service.beta.kubernetes.io/aws-load-balancer-internal: "true"
        service:
          ports:
            - name: https
              protocol: TCP
              port: 443
              targetPort: 8443
              nodePort: 32234
```
- Create copy of `Gateway` in new namespace
- Add newly-created `Gateway` to `gateways` field of `VirtualService`
Now there are both Gateways are working.
  
The problem appears after removing old Gateway from `gateways` field of `VS` - 404 error code from both ingressgateways with logs like - 404 NR route_not_found.
  
```yaml
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: testgw
  namespace: istio-ingressgateway-int
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: wildcard-letsencrypt
    hosts:
    - "test.dev.bit.sysa.io"
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: testgw
  namespace: istio-ingressgateway-temp
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: wildcard-letsencrypt
    hosts:
    - "test.host.name"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: testvs
  namespace: istio-system
spec:
  hosts:
  - "test.host.name"
  gateways:
  - istio-ingressgateway-int/testgw
#  - istio-ingressgateway-temp/testgw
  http:
  - route:
    - destination:
        host: kiali.istio-system.svc.cluster.local
        port:
          number: 20001
```

Deleting old `Gateway` resource fixes the issue.

**Version**
Istio version: 1.9.2

**How was Istio installed?**
Using `istioctl install`.

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS EKS.

Thanks!

[ ] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure
[ ] Upgrade
