### ISSUE TITLE
Service switches occasionally dropped at multinetwork gateway

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#32542]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/32483/integ-pilot-multicluster-tests_istio/1387079418416992256

Test applies service:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: b-alt-2
  labels:
    app: b
spec:
  ports:
  - name: tcp
    port: 80
    targetPort: 19092
  selector:
    app: b
```

Server side sets up 19092 inbound listener correctly. Eastwest GW sets up cluster for b-alt-2, but it gets no endpoints.

Access logs:
Client: `"- - -" 0 UF,URX - - "-" 0 0 1 - "-" "-" "-" "-" "172.18.255.156:15443" outbound|80||b-alt-2.echo-1-31003.svc.cluster.local - 10.255.30.73:80 10.30.0.11:35086 - -`
EW: `"- - -" 0 UH - - "-" 0 0 16 - "-" "-" "-" "-" "-" outbound_.80_._.b-alt-2.echo-1-31003.svc.cluster.local - 10.20.0.9:15443 10.20.0.1:26157 - -`
Server: None, doesn't hit server

The same-network calls succeed.

The eastwest gateway does have endpoints for `b`, which *should* be the same as b-alt.

Interestingly, *both* clusters are missing it in their eastwest gw. They also don't have it in egress or ingress gw. So all sidecars get it, no gws do. They do get the cluster, just no endpoints for the cluster.
