### ISSUE TITLE
Server cipher suite preference for TLS 1.3

### ISSUE THREAD

**Issue by bnutt** [istio/istio#32558]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
Specifying a gateway with TLS and cipher suites for that TLS

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-tls-ingress
spec:
  selector:
    app: my-tls-ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*"
    tls:
      mode: SIMPLE
      serverCertificate: /etc/certs/server.pem
      privateKey: /etc/certs/privatekey.pem
      cipherSuites: ....
```

Even if a user specifies just `AES256-GCM-SHA384, AES128-GCM-SHA256`, or there is some specific ordering of the 1.3 suites, envoy does not set the server preference. Additionally, if you remove one of the TLS 1.3 suites, it still is able to be used during negotiation. This seems to be due to an underlying way envoy consumes this setting https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto.html. It should be called out in the docs that the cipher suites for 1.3 will never have server preference like TLS 1.2 does.

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Cipher suites specified in gateway should be the only used, in the order that they were specified.

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.9.3

**How was Istio installed?**
Istio Operator
**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
