### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED is there any wrong with my method of generate certs

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#32562]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
[2021-04-30T08:19:22.064Z] "GET /productpage HTTP/1.1" 503 UF,URX upstream_reset_before_response_started{connection_failure,TLS_error:_268435581:SSL_routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED} - "TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED" 0 195 77 - "172.20.1.53" "curl/7.76.1-DEV" "621a908e-393d-967a-8a35-77d382fbbdf4" "productpage.istio.svc.cluster.local:9080" "172.20.0.23:9080" outbound|9080||productpage.istio.svc.cluster.local - 10.68.55.29:9080 172.20.1.53:44932 - default

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**
openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -subj '/O=example Inc./CN=example.com' -keyout example.com.key -out example.com.crt 

 openssl req -out productpage.csr -newkey rsa:2048 -nodes -keyout productpage.key -subj "/CN=productpage.istio.svc.cluster.local:9080/O=some organization"  

 openssl x509 -req -days 365 -CA example.com.crt -CAkey example.com.key -set_serial 0 -in productpage.csr -out productpage.crt 

 kubectl create -n istio   secret generic  productpage-credential --from-file=tls.key=productpage.key   --from-file=tls.crt=productpage.crt --from-file=ca.crt=example.com.crt 

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: productpage
spec:
  host: productpage.istio.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 9080
      loadBalancer:
        simple: RANDOM
      tls:
        mode: SIMPLE
#        clientCertificate: /etc/istio/ingressgateway-certs/tls.crt
#        privateKey: /etc/istio/ingressgateway-certs/tls.key
        caCertificates: /etc/my-cert/ca.crt
        sni: productpage.istio.svc.cluster.local
        subjectAltNames: 
        - productpage.istio.svc.cluster.local
```
**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
