### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#32585]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
Bad Request[root@master01 ~]# curl   -H "x-envoy-original-dst-host=172.20.0.38:9080" http://bookinfo.demo:30986/productpage
Bad Request[root@master01 ~]# curl   -H "x-envoy-original-dst-host=172.20.0.38:9080" http://bookinfo.demo:30986/productpage
Bad Request[root@master01 ~]# curl   -H "x-envoy-original-dst-host=172.20.0.38:9080" http://bookinfo.demo:30986/productpage
Bad Request[root@master01 ~]# curl   -H "x-envoy-original-dst-host=172.20.0.38:9080" http://bookinfo.demo:30986/productpage
**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**
````
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: productpage
spec:
  host: productpage.istio.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  trafficPolicy:
    loadBalancer:
      simple: PASSTHROUGH
```
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: lb-passthrough
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
        name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          codec_type: AUTO
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: upstream
              domains:
              - "*"
              routes:
              - match:
                  path: "/productpage"
                route:
                  cluster: outbound|9080||productpage.istio.svc.cluster.local
                request_headers_to_add: 
                - header:
                    key: "x-envoy-original-dst-host"
                    value: "172.20.0.38:9080"
                  append: true
  - applyTo: CLUSTER
    match:
      cluster:
        name: outbound|9080||productpage.istio.svc.cluster.local
    patch:
        operation: MERGE
        value:
          original_dst_lb_config:
            use_http_header: true
  - applyTo: LISTENER
    patch:
      operation: MERGE
      value:
        listener_filters:
        - name: "envoy.filters.listener.original_dst"
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.listener.original_dst.v3.OriginalDst"
```

[2021-05-02T03:39:42.083Z] "- - HTTP/1.1" 400 DPE http1.codec_error - "-" 0 11 0 - "-" "-" "-" "-" "-" - - 172.20.1.75:8080 172.20.0.0:50138 - -
[2021-05-02T03:39:42.917Z] "- - HTTP/1.1" 400 DPE http1.codec_error - "-" 0 11 0 - "-" "-" "-" "-" "-" - - 172.20.1.75:8080 172.20.0.0:50150 - -


**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
