### ISSUE TITLE
VirtualService: When setting the host header / authority, istio also redirects traffic to that host instead of the route.destination.host

### ISSUE THREAD

**Issue by lenalebt** [istio/istio#32594]
**Bug description**

For this VirtualService definition:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: swagger-ui
  labels:
    app: swagger-ui
spec:
  gateways:
    - documentation-gateway
  hosts:
    - {{ .Values.ingress.apiDocsDomain }}
  http:
    - rewrite:
        authority: swagger-ui.documentation
      route:
        - destination:
            host: swagger-ui-oauth2-proxy.documentation.svc.cluster.local
            port:
              number: 80
```
I expect requests to hit `swagger-ui-oauth2-proxy.documentation.svc.cluster.local` with a `Host`-header setting of `swagger-ui.documentation`. Instead, they hit `swagger-ui.documentation` directly.

I'm trying to work around a case where OAuth2-Proxy seems to interpret `Host` headers where I actually don't want it to do that in the first place, see https://github.com/oauth2-proxy/oauth2-proxy/issues/1179

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

I expect requests to hit `swagger-ui-oauth2-proxy.documentation.svc.cluster.local` with a `Host`-header setting of `swagger-ui.documentation`.

**Steps to reproduce the bug**

Apply the above `VirtualService`.

**Version**

```
./istioctl version --remote
client version: 1.9.4
control plane version: 1.9.4
data plane version: 1.9.4 (3 proxies), 1.9.2 (4 proxies)
```
```
kubectl version --short
Client Version: v1.21.0
Server Version: v1.20.5-gke.2000
```

**How was Istio installed?**
`istioctl install -f ../../istioctl-config.yaml`

**Environment where the bug was observed (cloud vendor, OS, etc)**

GKE running cos images.
