### ISSUE TITLE
Only one Gateway with wildcard certificate works in the browser

### ISSUE THREAD

**Issue by kovalyukm** [istio/istio#32592]
Hello,
There is HTTP ERROR 404 codes when opening in the browser any host with wildcard certificate after accessing some with the same certificate.

When using browser incognito mode or curl the issue is gone.

**Steps to reproduce the bug**
Create Gateways with some VSs and try to access them one by one in the same browser.

```yaml
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: testgw1
  namespace: istio-ingressgateway-int
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: wildcard-letsencrypt
    hosts:
    - "test1.domain.zone"
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: testgw2
  namespace: istio-ingressgateway-int
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: wildcard-letsencrypt
    hosts:
    - "test2.domain.zone"
```

Log entries from ingressgateway:
```text
[2021-05-03T12:05:15.832Z] "GET / HTTP/2" 200 - via_upstream - "-" 0 2 67 66 "XXX.YYY.240.246" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" "de426a9d-8ed4-4aee-b694-ca086f860812" "test1.domain.zone" "XXX.YYY.188.237:8080" outbound|80||test1.default.svc.cluster.local XXX.YYY.72.67:44042 XXX.YYY.72.67:8443 XXX.YYY.240.246:19241 test1.domain.zone -

[2021-05-03T12:06:43.078Z] "GET / HTTP/2" 404 NR route_not_found - "-" 0 0 0 - "XXX.YYY.240.246" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" "9e0d5299-de10-4e39-bc87-93f2195be03b" "test2.domain.zone" "-" - - XXX.YYY.72.67:8443 XXX.YYY.240.246:19241 test1.domain.zone -
```

**Version**
client version: 1.9.2
control plane version: 1.9.2
data plane version: 1.9.2

**How was Istio installed?**
Using `istioctl install`.

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS EKS.

Please advise.
Thanks!

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure
[ ] Upgrade
