### ISSUE TITLE
mTLS support for direct communication between services outside the mesh to services inside the mesh

### ISSUE THREAD

**Issue by sha-rath** [istio/istio#32595]
**Describe the feature request**
Consider a scenario where both client and server are in the same cluster/namespace, but the client is outside the mesh (no sidecar) and the server is inside the mesh. The direct mTLS communication between such a client and server is not handled by Istio. Isn’t this a quite common use case?? In a big cluster, we can usually expect few services inside the mesh and a few outside.

One possible workaround to have mTLS between such a client and server is by using an Ingress Gateway. The client can reach the server with mTLS through this gateway, but the main drawback here is the extra hop involved which increases latency.

It would be really beneficial if Istio somehow supports direct mTLS between services outside the mesh to services inside the mesh. A possible solution maybe is to extend the Sidecar API since it already supports the IstioIngressListener (https://istio.io/latest/docs/reference/config/networking/sidecar/#IstioIngressListener) and have TLS configuration options just like how we have for the Gateway now.

A good example for this use case is the Prometheus application as described in the blog post here: https://istio.io/latest/blog/2020/proxy-cert/
My request is similar to this, but I also want the certificates to be provisioned by a custom PKI (Public Key Infrastructure) and not Istio. 

If you consider the TLS Settings for Prometheus when Strict mTLS is enabled, as described here (https://istio.io/latest/docs/ops/integrations/prometheus/#tls-settings), it can be seen that it is not a perfect mTLS solution as Prometheus cannot verify the certificate from the server inside the mesh (_insecure_skip_verify: true_), which uses SPIFFE that Prometheus doesn't understand.

**Describe alternatives you've considered**
We came up with a custom solution to avoid the extra hop mentioned above. On the server-side, the listener can serve multiple certificates namely:

1. mesh internal certificate (with SPIFFE ID) for in-mesh mTLS communication
2. normal certificate (e.g. FQDN ID) to accept mTLS request from a client outside the mesh

We know that _port 15006_ is used for Envoy inbound and this intercepts all inbound traffic. In order to serve a new mTLS inbound traffic from a client outside the mesh, the server needs a new SNI that is different from the in-mesh SNI. This is done by adding a new filter chain for the _port 15006_ inbound listener. A new _transport_socket_ with crt/key and CA cert is also added. The self-signed CA cert and server crt/key are added to the server by using the annotation + volume mount. In our example, httpbin service is considered as the server inside the mesh.

This configuration is applied using the EnvoyFilter as follows:
```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: httpbin-ef-osm2ism
  namespace: test
spec:
  workloadSelector:
    labels:
      app: httpbin
  configPatches:
  - applyTo: FILTER_CHAIN
    match:
      context: SIDECAR_INBOUND
      listener:
        portNumber: 15006
    patch:
      operation: INSERT_FIRST
      value:
        name: 0.0.0.0_80
        filter_chain_match:
          transport_protocol: tls
          application_protocols:
          - h2
          - http/1.1
          server_names:
          - httpbin.test.svc.cluster.local
          - httpbin
          destination_port: 80
        filters:
        - name: envoy.filters.network.http_connection_manager
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            stat_prefix: inbound_0.0.0.0_80
            route_config:
              name: inbound|80||
              virtual_hosts:
              - name: inbound|http|8000
                domains:
                - "*"
                routes:
                - match:
                    prefix: "/"
                  route:
                    cluster: inbound|80||
                    timeout: 0s
                    max_stream_duration:
                      max_stream_duration: 0s
                  decorator:
                    operation: httpbin.test.svc.cluster.local:8000/*
                  name: default
              validate_clusters: false
            http_filters:
            - name: envoy.filters.http.router
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router           
            http2_protocol_options:
              max_concurrent_streams: 1000
              max_outbound_frames: 1000
              stream_error_on_invalid_http_messaging: true
            server_name: istio-envoy
            use_remote_address: false
            forward_client_cert_details: APPEND_FORWARD
            set_current_client_cert_details:
              subject: true
              dns: true
              uri: true
            upgrade_configs:
            - upgrade_type: websocket
            stream_idle_timeout: 0s
            normalize_path: true
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
            common_tls_context:
              tls_params:
                tls_minimum_protocol_version: TLSv1_2
              alpn_protocols:
              - h2
              - http/1.1
              tls_certificate_sds_secret_configs:
              - name: file-cert:/etc/istio/osm-certs/tls.crt~/etc/istio/osm-certs/tls.key
                sds_config:
                  api_config_source:
                    api_type: GRPC
                    grpc_services:
                    - envoy_grpc:
                        cluster_name: sds-grpc
                    transport_api_version: V3
                  resource_api_version: V3
              combined_validation_context:
                default_validation_context: {}
                validation_context_sds_secret_config:
                  name: file-root:/etc/istio/osm-ca-certs/ca.crt
                  sds_config:
                    api_config_source:
                      api_type: GRPC
                      grpc_services:
                      - envoy_grpc:
                          cluster_name: sds-grpc
                      transport_api_version: V3
                    resource_api_version: V3
            require_client_certificate: true
```

With this patch, a client (with CA cert, client crt/key) outside the mesh can establish a direct mTLS communication with the server inside the mesh, bypassing the Ingress Gateway.

As EnvoyFilter is not friendly to use and also not so recommended, can this feature be somehow supported by Istio?

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
