### ISSUE TITLE
Configuring ingress to work with TCP mode with TLS configurations 

### ISSUE THREAD

**Issue by Shashankft9** [istio/istio#32612]
**Bug description**
I am trying to use the TLS remote cluster feature of elastic, in which a proxy needs to send requests to a server running in a remote cluster, the said remote cluster has istio installed. The server expects TLS. 

Premise: I tried doing the above scenario by exposing that remote cluster server service using nodeport, and then the proxy is able to send requests, everything works fine. 

Bug: This is what I first tried with istio, which I think is probably wrong because it doesnt mention TLS details?
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: es-gateway
  namespace: es-remote
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 9400
      name: test
      protocol: TCP
    hosts:
    - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: es-vs
  namespace: es-remote
spec:
  hosts:
  - "*"
  gateways:
  - es-gateway
  tcp:
  - match:
    - port: 9400
    route:
    - destination:
        port:
          number: 9300
        host: quickstart-es-transport.es-remote.svc.cluster.local
```
After applying the above, I was getting UH flag in the istio ingress logs. 
So I applied this next:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: es-gateway
  namespace: es-remote
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 9400
      name: tls-es
      protocol: TLS
    hosts:
    - "*"
    tls:
      mode: PASSTHROUGH

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: es-vs
  namespace: es-remote
spec:
  hosts:
  - "*"
  gateways:
  - es-gateway
  tls:
  - match:
    - sniHosts:
      - quickstart-es-http.es-cloud.es.local
      port: 9400
    route:
    - destination:
        host: quickstart-es-transport.es-remote.svc.cluster.local
        port:
          number:  9300
```
But after applying this, I am not even getting logs of incoming requests in the istio ingressgateway pods. And ultimately all requests are failing.  I wanted to check if the routes are created to verfiy why the logs are not coming, but I found out that `istioctl proxy-config route istio-ingressgateway-zzjmw -n istio-system -o json` isnt showing the tcp routes even for other cases where TCP mode is working. 
Is this configuration correct? I didnt use `SIMPLE` in tls since I would want the TLS conigs to be preserved. I am more so stuck to debug this because I cant find anywhere to start on, like missing logs or missing envoy rules.

[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ X] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**How was Istio installed?**
Running v1.6 of istio, installed using istioctl. 

**Environment where the bug was observed (cloud vendor, OS, etc)**
centos8, k8s v1.20
