### ISSUE TITLE
GKE 19 - Istio 1.6.14 - TLS Termination SDS 443 Connection Refused

### ISSUE THREAD

**Issue by caominhvu** [istio/istio#32610]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
- I got error: Connection Refused when trying to use https (port 443)

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[x] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
- Port 443 should be able to access successfully

**Steps to reproduce the bug**
- Create a cluster using GKE
- Enable Istio
- Upgrade Istio to 1.6.14
- Using Certbot to create a certificate for a domain
- Create a kubernetes secret of the certificate
- Create an Istio Gateway and Service
- Try with: curl http://mydomain.com-> successfully
- Try with: curl https://mydomain.com-> Connection Refused
**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
istioctl version --remote
client version: 1.9.1
control plane version: 1.6.14-gke.1-006dfdf1f9b4b4ab5877d4775988099cc7bd69fd
data plane version: 1.6.14-gke.1 (1 proxies)
```

```
kubectl version --short
Client Version: v1.19.7
Server Version: v1.19.9-gke.1400
```

**How was Istio installed?**
- Enabled from GKE

**Environment where the bug was observed (cloud vendor, OS, etc)**
- GKE 1.19

This is my configuration file:

```
#Istio Gateway Configuration
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: sample-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
#      tls:
#       httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "mydomain.com"
      tls:
        mode: SIMPLE
        credentialName: diamed-credential
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtualservice-sample
spec:
  hosts:
    - "mydomain.com"
  gateways:
    - sample-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: myservicehost
            port:
              number: 8080
```

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
