### ISSUE TITLE
envoyfilter match routeConfiguration portName gateway cann't match any routeConfiguration 

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#32637]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
envoyfilter match routeConfiguration portName gateway cann't match any routeConfiguration 

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**
apply following yaml config:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: match
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: VIRTUAL_HOST
    match:
      context: GATEWAY
      routeConfiguration:
        portName: http
        gateway: istio/bookinfo-gateway
        vhost:
          name: "*:80"
    patch:
      operation: REMOVE
  - applyTo: VIRTUAL_HOST
    match:
      context: GATEWAY
      routeConfiguration:
        portName: http
        gateway: istio/bookinfo-gateway
        name: "http.80"
    patch:
      operation: ADD
      value:
            name: "*:80"
            domains:
            - "*"
            routes:
            - match:
                prefix: "/"
              direct_response:
                status: 200
                body:
                  inline_string: "example body\n"
```
```
[root@master01 match]# kubectl get gw -n istio
NAME                  AGE
bookinfo-gateway      13d
istio-egressgateway   4d1h
mysql                 16d
```
```
[root@master01 match]# kubectl get gw bookinfo-gateway -n istio -o yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1beta1","kind":"Gateway","metadata":{"annotations":{},"name":"bookinfo-gateway","namespace":"istio"},"spec":{"selector":{"istio":"ingressgateway"},"servers":[{"hosts":["*"],"port":{"name":"http","number":80,"protocol":"HTTP"}}]}}
  creationTimestamp: "2021-04-21T04:50:50Z"
  generation: 5
  managedFields:
  - apiVersion: networking.istio.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        .: {}
        f:selector:
          .: {}
          f:istio: {}
        f:servers: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-04-21T04:50:50Z"
  name: bookinfo-gateway
  namespace: istio
  resourceVersion: "1491063"
  uid: 08570ff9-3b85-4600-9296-c89612faf26a
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
```
**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
[root@master01 match]# istioctl version --remote
client version: 1.9.2
control plane version: 1.9.2
data plane version: 1.9.2 (14 proxies)
[root@master01 match]# kubectl version --short
Client Version: v1.20.5
Server Version: v1.20.5

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by ramaraochavali** [comment]
Since you have operation "REMOVE" on virtualhost Istio removes that virtual host. If you want to update virtualhost use MERGE operation.

**Comment by 13567436138** [comment]
what I delete is vhost,not routeConfiguration.
also:
Replace contents of a named filter with new contents. REPLACE operation is only valid for HTTP_FILTER and NETWORK_FILTER. If the named filter is not found, this operation has no effect.

**Comment by 13567436138** [comment]
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: match
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: VIRTUAL_HOST
    match:
      context: GATEWAY
      routeConfiguration:
        portName: http
        gateway: istio/bookinfo-gateway
        name: "http.80"
    patch:
      operation: MERGE
      value:
            name: "*:80"
            domains:
            - "*"
            routes:
            - match:
                prefix: "/"
              direct_response:
                status: 200
                body:
                  inline_string: "example body\n"
```
I used merge no affect

**Comment by 13567436138** [comment]
I think this is a bug。

@ramaraochavali

**Comment by howardjohn** [comment]
port name match only works for https. I believe this is documented

**Comment by 13567436138** [comment]
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: match
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: VIRTUAL_HOST
    match:
      context: GATEWAY
      routeConfiguration:
        portName: httpS
    #    gateway: istio/bookinfo-gateway
    patch:
      operation: MERGE
      value:
            name: "*:443"
            domains:
            - "*"
            routes:
            - match:
                prefix: "/"
              direct_response:
                status: 200
                body:
                  inline_string: "example body\n"
```
no effect
