### ISSUE TITLE
csrf filter is not work correctly

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#32639]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
csrf filter is not work correctly

[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**
deployment
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csrf
  labels:
    app: csrf
spec:
  selector:
    matchLabels:
      app: csrf
  replicas: 1
  template:
    metadata:
      labels:
        app: csrf
        version: v1
    spec:
      containers:
        - name: csrf
          image: registry.cn-hangzhou.aliyuncs.com/hxpdocker/csrf-satesite:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: csrf
spec:
  selector:
    app: csrf
  ports:
    - name: tcp-csrf
      protocol: TCP
      port: 8080
      targetPort: 8080
---
```
vs
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: csrf
spec:
  hosts:
  - "*"
  gateways:
  - bookinfo-gateway
  http:
  - match:
    - uri:
        prefix: /
    corsPolicy:
      allowOrigins:
      - exact: http://bookinfo.demo:30986
      - exact: http://192.168.198.154:8081
      allowMethods:
      - GET
      - OPTIONS
      - POST
      maxAge: "1m"
      allowHeaders:
      - content-type
    route:
    - destination:
        host: csrf.istio.svc.cluster.local
        port:
          number: 8080
```
envoyfilter
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: apply-to
spec:
  workloadSelector:
    labels:
      app: csrf
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        name: 0.0.0.0_8080  
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
        name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          codec_type: AUTO
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: www
              domains:
              - "*"
              typed_per_filter_config:
                envoy.filters.http.csrf:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.csrf.v3.CsrfPolicy
                  filter_enabled:
                    default_value:
                      numerator: 100
                      denominator: HUNDRED
                    runtime_key: csrf.www.enabled
                  shadow_enabled:
                    default_value:
                      numerator: 0
                      denominator: HUNDRED
                    runtime_key: csrf.www.shadow_enabled
              routes:
              - match:
                  prefix: "/csrf/disabled"
                route:
                  cluster: generic_service
                typed_per_filter_config:
                  envoy.filters.http.csrf:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.csrf.v3.CsrfPolicy
                    filter_enabled:
                      default_value:
                        numerator: 0
                        denominator: HUNDRED
              - match:
                  prefix: "/csrf/shadow"
                route:
                  cluster: generic_service
                typed_per_filter_config:
                  envoy.filters.http.csrf:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.csrf.v3.CsrfPolicy
                    filter_enabled:
                      default_value:
                        numerator: 0
                        denominator: HUNDRED
                    shadow_enabled:
                      default_value:
                        numerator: 100
                        denominator: HUNDRED
              - match:
                  prefix: "/csrf/additional_origin"
                route:
                  cluster: generic_service
                typed_per_filter_config:
                  envoy.filters.http.csrf:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.csrf.v3.CsrfPolicy
                    filter_enabled:
                      default_value:
                        numerator: 100
                        denominator: HUNDRED
                    additional_origins:
                    - safe_regex:
                        google_re2: {}
                        regex: .*
              - match:
                  prefix: "/"
                route:
                  cluster: generic_service
  - applyTo: HTTP_FILTER
    match:
        listener:
          name: 0.0.0.0_8080  
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
    patch:
        operation: INSERT_BEFORE
        value:           
          name: envoy.filters.http.csrf
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.csrf.v3.CsrfPolicy
            filter_enabled:
              default_value:
                numerator: 100
                denominator: HUNDRED 
  - applyTo: CLUSTER
    match:
      context: ANY
      cluster: {} 
    patch:
      operation: ADD
      value:
        name: generic_service
        connect_timeout: 0.25s
        type: STATIC
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: generic_service
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 8080
```
index.html
```
<!DOCTYPE html>
<html>
<head>
    <title>Envoy CSRF Wepage</title>
    <link rel="shortcut icon" href="https://www.envoyproxy.io/img/favicon.ico">
    <script type="text/javascript">
        var client = new XMLHttpRequest();
        var resultText;

        function submitToDomain() {
            var remoteIP = document.getElementById("destinationip").value;
            var enforcement = document.querySelector('input[name="csrf"]:checked').value;
            var method = enforcement !== 'ignored' ? 'POST' : 'GET';
            if(client) {
                var url = `http://${remoteIP}:80/csrf/${enforcement}`;
                client.open(method, url, true);
                client.onreadystatechange = handler;
                client.send();
            } else {
                resultText = "Could not find client to make request.";
                document.getElementById("results").textContent = resultText;
            }
        }

        function handler() {
            var responseCode = client.status;
            if (client.readyState == 4 && responseCode == 403) {
                resultText = 'Rejected by CSRF';
            }
            else if (client.readyState == 4 && responseCode == 200) {
                resultText = client.responseText;
            }
            else if (client.readyState == 4) {
                resultText = 'Unknown Error. Check the console.';
            }
            document.getElementById("results").textContent = resultText;
        }
    </script>
</head>
<body>
    <h1>
        Envoy CSRF Demo
    </h1>
    <p>
        This page demonstrates a few scenarios for CSRF.
    </p>
    <p>
        Enter the IP address of the destination Docker container.<br/>
    </p>
    <div>
        <input id="destinationip" type="text" placeholder="Destination IP" value="localhost"/>
        <button id="submit" onclick="submitToDomain()">Post to destination</button><br/>
        <div style="width:20%;float:left;">
            <h5>CSRF Enforcement</h5>
            <input type="radio" name="csrf" value="disabled" checked="checked"/> Disabled<br/>
            <input type="radio" name="csrf" value="shadow"/> Shadow Mode<br/>
            <input type="radio" name="csrf" value="enabled"/> Enabled<br/>
            <input type="radio" name="csrf" value="ignored"/> Ignored<br/>
            <input type="radio" name="csrf" value="additional_origin"/> Additional Origin<br/>
            <br/>
        </div>
        <div style="float:left;">
            <h3>Request Results</h3>
            <p id="results"></p>
        </div>
    </div>
</body>
<script>
    var input = document.getElementById("remoteip");
    if (input) {
        input.addEventListener("keyup", function(event) {
            event.preventDefault();
            if (event.keyCode === 13) {
                document.getElementById("submit").click();
            }
        });
    }
</script>
</html>
```
**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
