### ISSUE TITLE
Can not connect to an AWS RDS instance from pod which has a sidecar.

### ISSUE THREAD

**Issue by NewmanJ1987** [istio/istio#32659]
**Bug description**
The order in which I create my `serviceentry` and `service` causes a problem when I try to connect to my aws rds database from a pod running with a sidecar.  

I will try to describe the problem in a example. 

RDS_1 - An aws rds instance.
RDS_2 - A different aws rds instance.

Service_1 - service of type ExternalService for RDS_1
Service_2 - service of type ExternalService for RDS_2

ServiceEntry_1 -  Service entry pointing to RDS_1
ServiceEntry_2 - Service entry pointing to RDS_2

If I create the services before the service entries when I try to reach the database I run into the following scenario

RDS_1 with RDS_1 username and RDS_1 password  WORK!
RDS_2 with RDS_2 username and RDS_2 password  **DOES NOT WORK!**
RDS_2 with RDS_1 username and RDS_1 password  WORK!

This is what I have as an output of `istioctl proxy-config listener newman-test-pod |grep 3306`

``` bash
0.0.0.0        3306  ALL                                           Cluster: outbound|3306||mysql-1.default.svc.cluster.local
3.14.19.40     3306  ALL                                           Cluster: outbound|3306||aws_rds_1.endpoint
52.14.226.11  3306  ALL                                           Cluster: outbound|3306||aws_rds_2.endpoint
```

If I do the reverse and create the service entries before the mysql I get the expected behavior. 

[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Connect to RDS_1 with RDS_1 endpoint url and connect to RDS_2 with RDS_2 endpoint.

**Steps to reproduce the bug**
Create the `services` like so 
```yaml
kind: Service
metadata:
  name: mysql-1
spec:
  externalName: aws_rds_1.endpoint
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  type: ExternalName
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-2
spec:
  externalName: aws_rds_2.endpoint
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  type: ExternalName
```
Create the `serviceentry` like so 
```yaml 
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: mysql-external-1
spec:
  hosts:
  - aws_rds_1.endpoint
  ports:
  - name: tcp
    number: 3306
    protocol: tcp
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: aws_rds_2.endpoint
spec:
  hosts:
  - database-2.cngpp03teyle.us-east-2.rds.amazonaws.com
  ports:
  - name: tcp
    number: 3306
    protocol: tcp
  location: MESH_EXTERNAL

```
Launch a pod and then try to connect to an AWS RDS instance and you can only connect to one db no matter what url you use. 

```bash
mysql -uadmin -ppassword1 -h mysql-1
```

```bash
mysql -uadmin -ppassword1 -h mysql-2
```

**NOTE** this problem does not occur if you do the process in reverse and create the service entries before the services. 

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```bash 
istioctl version --remote
client version: 1.8.2
control plane version: 1.8.2
data plane version: 1.8.2 (10 proxies)
```
``` bash
kubectl version --short
Client Version: v1.19.1
Server Version: v1.19.1
```

**How was Istio installed?**
Installed with the istioctl binary
```bash
 istioctl install --set profile=demo
 ```

**Environment where the bug was observed (cloud vendor, OS, etc)**
PC
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
