### ISSUE TITLE
MERGE on `route` not supported / Not working (Internal_Redirect_Policy)

### ISSUE THREAD

**Issue by DandyDeveloper** [istio/istio#32673]
**Bug description**
I'm attempting to patch a merge into the `route` on a specific set of routes on a VirtualHost. Specifically, I want to enable internal_redirect_policy via https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-internalredirectpolicy

To achieve this I am creating an EnvoyFilter that resembles this;

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: follow-redirects
  namespace: default
spec:
  workflowSelector:
    labels:
      app: example
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: ANY
    patch:
      operation: MERGE
      value:
        route:
          internal_redirect_policy:
            max_internal_redirects: 5
            redirect_response_codes: ["308"]
```

My expectation on this is on any route, merge the above `internal_redirect_policy`. However, when applying this, I see that nothing is being changed; 

Example route generated by Pilot; 
```sh
            {
                "name": "example:80",
                "domains": [
                    "example",
                    "example:80",
                    "10.97.240.28",
                    "10.97.240.28:80"
                ],
                "routes": [
                    {
                        "name": "default",
                        "match": {
                            "prefix": "/"
                        },
                        "route": {
                            "cluster": "outbound|80||example",
                            "timeout": "0s",
                            "retryPolicy": {
                                "retryOn": "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes",
                                "numRetries": 2,
                                "retryHostPredicate": [
                                    {
                                        "name": "envoy.retry_host_predicates.previous_hosts"
                                    }
                                ],
                                "hostSelectionRetryMaxAttempts": "5",
                                "retriableStatusCodes": [
                                    503
                                ]
                            },
                            "maxGrpcTimeout": "0s"
                            #### I EXPECT IT TO BE MERGED HERE ####
                        },
                        "decorator": {
                            "operation": "example:80/*"
                        }
                    }
                ],
                "includeRequestAttemptCount": true
            },
```

However, if I try a similar action appending to the `routes` (not the route itself) it seems to work; 

EnvoyFilter:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: follow-redirects
  namespace: default
spec:
  workflowSelector:
    labels:
      app: example
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: ANY
    patch:
      operation: MERGE
      value:
        tracing:
          random_sampling:
            numerator: 9990
            denominator: TEN_THOUSAND
```

Route:
```
            {
                "name": "ambrose.default.svc.cluster.local:80",
                "domains": [
                    "example.default.svc.cluster.local",
                    "10.97.240.28",
                    "10.97.240.28:80"
                ],
                "routes": [
                    {
                        "name": "default",
                        "match": {
                            "prefix": "/"
                        },
                        "route": {
                             ....
                            },
                            "maxGrpcTimeout": "0s"
                        },
                        "decorator": {
                            "operation": "example.default.svc.cluster.local:80/*"
                        },
                        "tracing": {
                            "randomSampling": {
                                "numerator": 9990,
                                "denominator": "TEN_THOUSAND" <- Working fine
                            }
                        }
                    }
                ],
                "includeRequestAttemptCount": true
            },
```

This seems intentional, but to me is a blocker on migration of certain applications that require 308 redirects in the Infra. 

Is this intentional behavior? I'm trying to find the appropriate code that manages this. 

[X ] Docs
[X] Extensions and Telemetry

**Expected behavior**
I would expect it to append the keys I have given in the `route` that has been generated. 

**Steps to reproduce the bug**
Apply the above example EnvoyFilters and check the route output using `istioctl ps route` 

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Istio
```
client version: 1.6.11
control plane version: 1.6.11
data plane version: 1.6.11 (142 proxies)
```
Kubernetes Bare Metal: 1.15

**How was Istio installed?**
Istioctl

**Environment where the bug was observed (cloud vendor, OS, etc)**
Bare Metal / Flatcar OS

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
