### ISSUE TITLE
Istio-operator sidecar injection issues

### ISSUE THREAD

**Issue by JonasJasas** [istio/istio#32746]
**Bug description**
After installation following these instructions: https://istio.io/latest/docs/setup/upgrade/gateways/#installation-with-operator
Sidecar injection is not working.

[X] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Injected sidecars for the NS with the `istio-injection: enabled`

**Steps to reproduce the bug**
Install Istio using `istioctl operator init --revision 1-9-4`

It is undocumented or a bug as `Mutatingwebhookconfigurations` is using this strange NS selector:
```yaml
...
  namespaceSelector:
    matchExpressions:
    - key: istio-injection
      operator: DoesNotExist
    - key: istio.io/rev
      operator: In
      values:
      - 1-9-4
...
```
