### ISSUE TITLE
virtual service definition works ok when tied to ingress gateway but not with egress

### ISSUE THREAD

**Issue by kameshchauhan** [istio/istio#32755]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
Virtual Service definition to dynamically route traffic based on `header` match condition works ok when tied to ingress gateway but when the similar header match condition is added in the virtual service for egress, the condition seems failing to match. 
However, if i change it to `OR` condition, even though the header match seems failiing (which it shouldn't as i am passing the correct header value), the other condition of gateway match is satisfied and the egress routing happening as expected.

[x] Docs
[] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Below two sample virtual service definitions which are similar where in both uses the `env` header match should work as expected. 
***Below is tied to `istio-ingressgateway` and works fine***
```
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: service-a
  namespace: default
spec:
  hosts:
    - '*'
  gateways:
    - istio-config/common-ingress-gateway
  http:
    - match:
        - headers:
            env: 
              exact: prod
          uri:
            prefix: /test
      name: prod-env-v3
      route:
        - destination:
            host: service-a
            subset: version-v3
          weight: 100
    - match:
        - headers:
            env:
              exact: uat
          uri:
            prefix: /test
      name: uat-env-v2
      route:
        - destination:
            host: service-a
            subset: version-v2
          weight: 100
    - match:
        - headers:
            env:
              exact: dev
        - uri:
            prefix: /test
      name: dev-default-env-v1
      route:
        - destination:
            host: service-a
            subset: version-v1
          weight: 100

````

***However, the below virtual service tied to `istio-egressgateway` is not working fine due to `env` header match issue.***
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: direct-external-through-egress-gateway
  namespace: default
spec:
  gateways:
  - dev-egress-gateway
  - prod-egress-gateway
  - mesh
  hosts:
  - dev.xyz.com
  - prod.xyz.com
  http:
  - match:
    - gateways:
      - mesh
      port: 80
      headers:
        env:
          exact: nonprod  
    name: nonprod-mesh
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        port:
          number: 443
        subset: dev
      weight: 100
  - match:
    - gateways:
      - mesh
      headers:
        env:
          exact: prod
      port: 80
    name: prod-mesh
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        port:
          number: 443
        subset: prod
      weight: 100
  - match:
    - gateways:
      - dev-egress-gateway
      port: 443
    name: nonprod-egress
    route:
    - destination:
        host: dev.xyz.com
        port:
          number: 7443
      weight: 100
  - match:
    - gateways:
      - prod-egress-gateway
      port: 443
    name: prod-egress
    route:
    - destination:
        host: prod.xyz.com
        port:
          number: 7443
      weight: 100
```

**Steps to reproduce the bug**
Apply 1st virtual service and related destination rules tied to `ingress` gateway and a sample curl sending the `env=prod` request header works fine.
However, the similar curl sending request header `env=prod` is not routing the egress request to the desired destination even though the virtual service tied to egress gateway has similar env header match condition. 
Note that I haven't shared the above the sample definition of destination rules, service entry etc....but rest assured that all those definition are correct and working fine when i remove the header match condition from the egress virtual service.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Istio 1.8.2
K8s 1.17

**How was Istio installed?**
Using IstioOperator

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS Cloud, Centos 7

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by kameshchauhan** [comment]
> can you run https://istio.io/latest/about/bugs/#generating-a-cluster-state-archive

This is sensitive customer env. Let me know if you need any specific information. Be aware that all the required service entry, virtual service , destination rule are deployed.

**Comment by su225** [comment]
I wonder why you are attaching the following
```yaml
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        port:
          number: 443
        subset: dev
      weight: 100
```
to the egress gateway. It makes sense for a sidecar (gateway=mesh), but not for egress gateway. Maybe, you need to configure like shown in this docs page - https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/ . Notice the "gateways" section at route level. The `istio-egressgateway.istio-system.svc` route is applicable for `mesh` (sidecars) where as for the same host, but gateway called `egress-gateway`, it is routed to the actual endpoint outside the cluster.
