### ISSUE TITLE
 Subset supports selecting multiple sets of instances

### ISSUE THREAD

**Issue by ydh926** [istio/istio#32779]
**Describe the feature request**
For example，Define a subset of v2.x, which contains instances of version 2.0 and 2.1.

**Describe alternatives you've considered**
Maybe we can simply change the labels to an array to support this feature, as follows
```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: bookinfo-ratings
spec:
  host: ratings.prod.svc.cluster.local
  subsets:
  - name: v2.x
    selectors:
    - version: v2.0
       xxx: xx
    - version: v2.1
       yyy: yy
```

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
