### ISSUE TITLE
Patching in overlays doesn't work for adding/appending new leaf list to lists

### ISSUE THREAD

**Issue by aravindarc** [istio/istio#32787]
**Bug description**
I wanted to patch the spec.template.spec.volumes list in deployment istio-ingressgateway, the patch is to add a new volume.
installation.yaml
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-operator
spec:
  profile: default
  components: 
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
      k8s:
        overlays:
        - kind: Deployment
          name: istio-ingressgateway
          patches:
          - path: spec.template.spec.volumes.[name:test]
            value:
              name: test
              configMap:
                name: test
```
The idea is that this should override if name:test already exists, if not it should append to existing volumes, but this error is reported when using` istioctl manifest generate -f installation.yaml`

Error:
`Error: path spec.template.spec.volumes.[name:test]: element [name:test] not found`

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
The new volume mentioned in the patch should be appended to the existing volumes list.

**Steps to reproduce the bug**
1. create installation.yaml:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-operator
spec:
  profile: default
  components: 
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
      k8s:
        overlays:
        - kind: Deployment
          name: istio-ingressgateway
          patches:
          - path: spec.template.spec.volumes.[name:test]
            value:
              name: test
              configMap:
                name: test
```
2.` istioctl manifest generate -f installation.yaml`

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
$ istioctl version --remote
client version: 1.9.0
control plane version: 1.9.0
data plane version: 1.9.0 (2 proxies)
```

**How was Istio installed?**
No installation was done, this happens during the manifest generation

**Environment where the bug was observed (cloud vendor, OS, etc)**
OS: Ubuntu 20

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
