### ISSUE TITLE
Unable to run 2 replicas of istiod

### ISSUE THREAD

**Issue by mabushey** [istio/istio#32800]
**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
✗  $IC version --remote
client version: 1.9.4
control plane version: 1.9.4
data plane version: 1.9.4 (3 proxies)
✗  kubectl version --short 
Client Version: v1.19.10
Server Version: v1.19.9-gke.1900
```

**How was Istio installed?**
```
kubectl delete namespace istio-system  ## wish upgrades worked
export IC=istioctl-194
$IC operator init
kustomize build --enable-alpha-plugins | kubectl apply -f -
```

**Environment where the bug was observed (cloud vendor, OS, etc)**
GKE

✗  cat ../base/operator.yaml
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-control-plane
  namespace: istio-system
spec:
  profile: default
  components:
    base:
      - enabled: true
        k8s:
          hpaSpec:
            minReplicas: 2
    ingressGateways:
      - enabled: true
        k8s:
          hpaSpec:
            minReplicas: 2
        name: istio-ingressgateway
  meshConfig:
    enableTracing: true
```
    
I correctly get 2 replicas for ingressGateways, but istiod does not scale up. I'm assuming base=istiod, The docs have gotten better but they're still abysmal.

**Comment by mabushey** [comment]
Great, once again the docs sent me on a wild goose chase. Pilot has NOT been deprecated/removed. It's still the same [upgraded] pilot container. The pod name is Istiod, the container is still pilot. Who thought this was a good idea?????

However replacing base with pilot in the IstioOperator file still does nto get two pods of istiod.

**Comment by rytswd** [comment]
You seem to have incorrect array notation under `base` (as you mentioned, it should be `pilot`).

---

With this below file

```bash
cat tester.yaml
```

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-control-plane
  namespace: istio-system
spec:
  profile: default
  components:
    pilot:
      enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2
    ingressGateways:
      - enabled: true
        k8s:
          hpaSpec:
            minReplicas: 2
        name: istio-ingressgateway
  meshConfig:
    enableTracing: true
```

You can also confirm how the above CR gets handled by Istio with `istioctl manifest generate`:

```bash
istioctl manifest generate -f tester.yaml | grep -A 20 Horizontal
```

```console
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: unknown
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
--
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: istiod
    install.operator.istio.io/owning-resource: unknown
    istio.io/rev: default
    operator.istio.io/component: Pilot
    release: istio
  name: istiod
  namespace: istio-system
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
```

---

I agree the documentation can be misleading at places, and debugging tips such as using `istioctl manifest generate` can be highlighted more IMO.

**Comment by mabushey** [comment]
@rytswd Thanks for taking the time to respond.

```
  components:
    pilot:
      enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2
```
This fails as it wants a `-` on `enabled: true`, just like ingressGateways. However adding at dash it appears to apply, but either corrupts Istio or does nothing (still one Pilot container) running.

I use kustomize for each env with a base image, I don't think the istioctl manifest command will really help me, `kubectl diff` is how I do this.

**Comment by mabushey** [comment]
```
✗  kustomize build --enable-alpha-plugins > tester.yaml
✗  $IC manifest generate -f tester.yaml | grep -A 20 Horizontal
kind: HorizontalPodAutoscaler
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
    istio.io/rev: default
    install.operator.istio.io/owning-resource: unknown
    operator.istio.io/component: "IngressGateways"
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istio-ingressgateway
  metrics:
    - type: Resource
      resource:
--
kind: HorizontalPodAutoscaler
metadata:
  name: istiod
  namespace: istio-system
  labels:
    app: istiod
    release: istio
    istio.io/rev: default
    install.operator.istio.io/owning-resource: unknown
    operator.istio.io/component: "Pilot"
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istiod
  metrics:
  - type: Resource
    resource:
      name: cpu
```

That's not correct, while Pilot is not scaling up to 2, ingressgateway is and this is showing it is not. K8s is in disagreement with `istioctl manifest`. I'm going to assume this manifest command is really based on helm, which is in turn based on dog do-do.

**Comment by mabushey** [comment]
```
✗  kubectl -n istio-system get iop istio-control-plane -o yaml | grep -A 30 ^spec
spec:
  components:
    ingressGateways:
    - enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2
      name: istio-ingressgateway
    pilot:
    - enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2
  meshConfig:
    enableTracing: true
  profile: default
status:
  componentStatus:
    Base:
      status: HEALTHY
    IngressGateways:
      status: HEALTHY
    Pilot:
      status: HEALTHY
  status: HEALTHY
  ```
  
  ```
  ✗  kubectl -n istio-system get hpa                                               
NAME                   REFERENCE                         TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
istio-ingressgateway   Deployment/istio-ingressgateway   4%/80%    2         5         2          6d
istiod                 Deployment/istiod                 1%/80%    1         5         1          6d
```

Looks like a bug in the operator, it's set to `minReplicas: 2` but generating a hpa with `minReplicas: 1`

**Comment by mabushey** [comment]
@howardjohn ^^ This is a bug. Probably because developers got confused over what's pilot and what's istiod.

**Comment by howardjohn** [comment]
what is "tester.yaml"?
```
$ ik manifest generate --set components.pilot.k8s.hpaSpec.minReplicas=2 | k grep HorizontalPodAutoscaler/istiod

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: istiod
    install.operator.istio.io/owning-resource: unknown
    istio.io/rev: default
    operator.istio.io/component: Pilot
    release: istio
  name: istiod
  namespace: istio-system
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istiod
```

This seems to work for me at first glance

**Comment by rytswd** [comment]
> This fails as it wants a - on enabled: true, just like ingressGateways.

No, that shouldn't be the case. You can check out the IstioOperator spec [here](https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#IstioComponentSetSpec), where it shows IngressGateway and EgressGateway are backed by array based `GatewaySpec[]`, but Istiod (and thus pilot) is backed by a single `ComponentSpec`. 

> I use kustomize for each env with a base image, I don't think the istioctl manifest command will really help me, kustomize build --enable-alpha-plugins | kubectl diff -f - is how I do this.

It shouldn't matter how you apply, IstioOperator controller is reconciling your IstioOperator CR and figuring out what to apply. If you are getting HPA with minReplica of 1, that means your config from IstioOperator CR not being applied correctly. Could you try setting `enabled: false` on the pilot spec, and see if it gets removed correctly? I doubt it would still create `istiod` pods, as it's simply ignored by IstioOperator because of CR spec not matching the expected format.

--

I've got quite an extensive list of Istio installation specs in [my test repo here](https://github.com/rytswd/get-istio-multicluster/tree/main/clusters). I have HPA working just fine with minReplica of 3 for my own use case (though I don't the exact copy spec in the repo).

Re: tester.yaml, I just created a yaml named that, sorry if it caused confusion.

**Comment by rytswd** [comment]
I had HPA setup here - though it's commented out for my testing.

https://github.com/rytswd/get-istio-multicluster/blob/main/clusters/armadillo/istio/installation/operator-usage/istio-control-plane.yaml

**Comment by mabushey** [comment]
@rytswd This would not be the 1st (or 2nd, 3rd, 4th) time the Istio specs are wrong:
```
✗  git diff ../base/operator.yaml | cat
...
-      - enabled: true
+      enabled: true
...
✗  kustomize build --enable-alpha-plugins | kubectl apply -f -
Error: accumulating resources: accumulation err='accumulating resources from '../base': '/home/ubuntu/Projects/kubernetes-gcp/istio-system/base' must resolve to a file': recursed accumulation of path '/home/ubuntu/Projects/kubernetes-gcp/istio-system/base': accumulating resources: accumulation err='accumulating resources from 'operator.yaml': yaml: line 16: mapping values are not allowed in this context': got file 'operator.yaml', but '/home/ubuntu/Projects/kubernetes-gcp/istio-system/base/operator.yaml' must be a directory to be a root
error: no objects passed to apply

✗  git checkout ../base/operator.yaml 
Updated 1 path from the index

✗  kustomize build --enable-alpha-plugins | kubectl apply -f -
namespace/istio-system unchanged
secret/kiali unchanged
istiooperator.install.istio.io/istio-control-plane unchanged
gateway.networking.istio.io/lb-gateway unchanged
virtualservice.networking.istio.io/grafana unchanged
virtualservice.networking.istio.io/kiali unchanged
```

**Comment by rytswd** [comment]
@mabushey I have been hit by some spec weirdness multiple times, but I have been finding a bit more stable these days.
Could you share the output of `kustomize build --enable-alpha-plugins`? I have the HPA setup working in production, so wonder what's different between your config and mine.

**Comment by mabushey** [comment]
removing the enabled line completely from the operator:
```
    pilot:
      k8s:
        hpaSpec:
          minReplicas: 2
    ingressGateways:
      - enabled: true
        k8s:
          hpaSpec:
            minReplicas: 2
```

It adds it back in, and yest it has a `-`:
```
✗  kubectl -n istio-system get iop istio-control-plane -o yaml | grep -A 12 ^spec
spec:
  components:
    ingressGateways:
    - enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2
      name: istio-ingressgateway
    pilot:
    - enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2
```

**Comment by mabushey** [comment]
```
✗  kubectl -n istio-system delete hpa istiod
horizontalpodautoscaler.autoscaling "istiod" deleted 

✗  kubectl -n istio-system get hpa                                               
NAME                   REFERENCE                         TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
istio-ingressgateway   Deployment/istio-ingressgateway   4%/80%    2         5         2          6d
```

Part of this bug is the operator is not recreating the pilot HPA.

**Comment by mabushey** [comment]
@howardjohn Ignore the tester part. The bug is:
1. `kubectl -n istio-system get iop istio-control-plane -o yaml | grep -A 30 ^spec` shows 2 min replicas, but that is not being applied
2. Deleting the HPA should result in the operator regenerating it. It does not.

**Comment by mabushey** [comment]
@rytswd absolutely. :)
```
✗  kustomize build --enable-alpha-plugins | grep -A24 "apiVersion: install.istio.io/v1alpha1"
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-15"
  labels:
    app.kubernetes.io/instance: dev-cdx-istio-system
  name: istio-control-plane
  namespace: istio-system
spec:
  components:
    ingressGateways:
    - enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2
      name: istio-ingressgateway
    pilot:
      k8s:
        hpaSpec:
          minReplicas: 2
  meshConfig:
    enableTracing: true
  profile: default
---
```

What's more important is how this is interpreted by the iop, in three posts above you can see it's adding the `- enabled: true` under pilot.

**Comment by rytswd** [comment]
I just tested with a clean KinD cluster, and confirmed that HPA was being applied correctly. I'm using 1.9.5 istioctl here.

Installation 

```bash
{
    istioctl=~/Coding/bin/istio-1.9.5/bin/istioctl # Update to your istioctl location

    kind create cluster --name tester
    $istioctl version --remote=false
    $istioctl operator init

    cat > tester.yaml <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-control-plane
  namespace: istio-system
spec:
  profile: default
  components:
    pilot:
      enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2
    ingressGateways:
      - enabled: true
        k8s:
          hpaSpec:
            minReplicas: 2
        name: istio-ingressgateway
  meshConfig:
    enableTracing: true
EOF
    kubectl create namespace istio-system
    kubectl apply -f tester.yaml
}
```

Verification after `istio-operator` works out the deployments

```bash
{
    kubectl get deployment istiod -n istio-system
    kubectl get hpa istiod -n istio-system
}
```

I get something like below

```console
NAME     READY   UP-TO-DATE   AVAILABLE   AGE
istiod   2/2     2            2           115s
NAME     REFERENCE           TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
istiod   Deployment/istiod   <unknown>/80%   2         5         2          115s
```

What do you see in your istio-operator controller logs? I'm just wondering if the original spec with `-` in "pilot" stanza caused some reconciliation errors, and thus you are seeing operator not handling resource creation correctly. Also, if I'm not mistaken, istio-operator controller works out the IOP input sequentially, so if there is anything stuck, it wouldn't be able to process the new input.

**Comment by mabushey** [comment]
@rytswd I think you're right about the operator being "stuck". I'm also using 1.9.5, but I use `$IC` as it's easier to type than `$istioctl`. ;)
I copy-pasted the cat to tester.yaml code.
```
✗  kubectl apply -f tester.yaml
istiooperator.install.istio.io/istio-control-plane configured
✗  kubectl get deployment istiod -n istio-system
NAME     READY   UP-TO-DATE   AVAILABLE   AGE
istiod   1/1     1            1           6d1h
✗  kubectl get hpa istiod -n istio-system
Error from server (NotFound): horizontalpodautoscalers.autoscaling "istiod" not found
```

I'll try this from scratch

**Comment by mabushey** [comment]
@rytswd Thank you very much for the help. Yes, deleting the iop and starting all over worked. This basically confirms that Istio upgrades NEVER work, you always have to blow it away and start all over. The main issue I have with this is a new load balancer is created, so I have to update the terraform config and there's downtime mostly due to DNS propagation. I need to figure out a way to assign non changing 'elastic' IPs to the LB on GCP/GKE.

**Comment by rytswd** [comment]
@mabushey For my production setup, I use GCP/GKE. It is not very obvious from the spec, but assigning static IP to the IngressGateway is certainly possible, and in fact, I do exactly that. I use Terraform for most of the ground work (static IP, cluster creation, DNS setup, etc.), and Istio configurations are made along with it. If you want to know more, I can certainly provide more details.

Because I use Argo CD for GitOps cluster management, all the configurations needed to be declarative, and for that, I use `istioctl manifest generate` rather than IstioOperator controller - mainly because operator approach didn't exist when I started Istio journey. Given the problem you saw with IstioOperator getting stuck, I personally feel IstioOperator is still not production ready, and good old manifest generation approach is easier to understand and maintain.

>  This basically confirms that Istio upgrades NEVER work, you always have to blow it away and start all over.

I think that statement is a bit too bold and not quite true - Istio upgrades without downtime is certainly possible, even without canary upgrade. But it is not easy, and I have been bitten by the upgrade issues myself.
I think the best material you can find about managing Istio installation is by another Istio user, Karl: https://karlstoney.com/2021/03/04/ci-for-istio-mesh/.

I'm currently experimenting the canary upgrades, and it seems to work for most cases (I'm not using operator approach, though). I think I'll get more clarity and will be able to share my findings in a week or so - if you are curious, I can certainly follow up on Slack or some other means 👍

**Comment by mabushey** [comment]
@rytswd I'm also on GCP/GKE. I created a static IP in Terraform, but having issues applying it to the ingressgateways. I tried this:
```
spec:
  components:
    ingressGateways:
    - enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2
        service:
          loadBalancerIP: 34.120.X.X
```
but the IP stays `<pending>` on the LoadBalancer.

I'm definitely interested in hearing about your upcoming experience with the canary upgrades.

**Comment by rytswd** [comment]
Hmm, I don't see any issue with your spec. I have very similar configuration, and get this for `istioctl manifest generate`

```
apiVersion: v1
kind: Service
metadata:
  annotations: null
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
  loadBalancerIP: 35.201.X.X
```

IIRC, you may be able to see some more details as to what's happening to IP association from GCP Console, but I might be wrong...
