### ISSUE TITLE
Network policies do not get applied in real time in an istio enabled kubernetes landscape

### ISSUE THREAD

**Issue by budanm** [istio/istio#32816]
**Bug description**
Network policies are not getting enforced at real-time in an istio enabled Kubernetes cluster. 

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
Network policies should get applied at runtime

**Steps to reproduce the bug**

- The set of k8s commands used for reproducing the setup

```
kubectl create ns t1
kubectl label namespace t1 nsname=ngt1
 
kubectl create ns t2
kubectl label namespace t2 nsname=t2


kubectl -n t1 apply -f - <<EOF
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: t1-nwpolicy
spec:
  podSelector:
    matchLabels:
      app: nginx1
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          nsname: ngt2
      podSelector:
        matchLabels:
          app: nginx2
EOF






kubectl -n t1 apply -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxd1
  labels:
    app: nginx1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx1
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx1
  name: nginxs1
spec:
  type: ClusterIP 
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx1

EOF


kubectl -n t2 apply -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxd2
  labels:
    app: nginx2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80

---


apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx2
  name: nginxs2
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx2
EOF


kubectl -n t2 apply -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxd3
  labels:
    app: nginx3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx3
  template:
    metadata:
      labels:
        app: nginx3
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx3
  name: nginxs3
spec:
  type: ClusterIP 
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx3

EOF
```

- Based on the network policy, the calls from nginx2 is allowed on nginx1 only. From nginx3 to nginx1 is not allowed.

- When we change the network policy's podSelector to app:nginx3 , the calls from nginx3 to nginx1 starts working . But the problem is the calls from nginx2 to nginx1 continues to work. When I restart the pod nginx2, the calls fail which is an expected behavior.

- Note : I have tested this in a normal k8s environment as well ( non-istio ), and there i dont see this issue. The calls from nginx2 to nginx1 starts failing immediately after I change the network policy.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
 * **istioctl version --remote**
        client version: 1.7.0
        control plane version: 1.9.1
        data plane version: 1.9.1 (37 proxies)
 * **kubectl version --short**
        Client Version: v1.18.5
        Server Version: v1.18.17
 * **helm version --short**
       v3.2.4+g0ad800e

**Environment where the bug was observed (cloud vendor, OS, etc)**
Kubernetes

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
