### ISSUE TITLE
Outlier detection scenarios miss proper labels in telemetry 

### ISSUE THREAD

**Issue by lucasponce** [istio/istio#32820]
When outlier detection scenarios are present telemetry introduced "unknown" values that are confusing for the user.

And example:

- A "circuit breaker" set up on the "w-server" service from this scenario:
![image](https://user-images.githubusercontent.com/1662329/117965391-fecc6480-b322-11eb-87a2-cf0d44c515f1.png)

- With a typical config as:
```
...
spec:
  host: w-server.alpha.svc.cluster.local
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 1
      tcp:
        maxConnections: 1
    outlierDetection:
      consecutiveErrors: 1
  subsets:
    - labels:
        version: v1
      name: v1
```

Working as expected:
![image](https://user-images.githubusercontent.com/1662329/117965306-e5c3b380-b322-11eb-9957-9e11e1b7e2e1.png)

But with Kiali we can see that some of the telemetry is missing "workload" and "namespace" values, which could be easily infered.

With that chart we can see how the "unknown" traffic is sent by the proxy (also Kiali can show the logs details), but telemetry should capture the namespace where the proxy is running and potentially the workload where is happening.

Otherwise the user needs to "understand" why this is an expected result.
