### ISSUE TITLE
Documentation of cniConfDir parameter seems inaccurate

### ISSUE THREAD

**Issue by rhrazdil** [istio/istio#32827]
**Bug description**

Hello,

I've been having issues with installation of Istio on a k8s cluster with calico and multus CNIs.

In my environment, the cni configuration files are located in:
`/etc/cni/net.d/` folder, so based on what documentation says about `cniConfDir` :
`Must be the same as the environment’s --cni-conf-dir setting (kubelet parameter).`
I set the path to be the same (that is `/etc/cni/net.d`)

However, when I then try to run a pod with a sidecar, I get:

```
Warning  FailedCreatePodSandBox  10s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox 
k8s_samplepod_default_d9d52c03-47bd-4902-a1d5-5fb63dfd76ac_0(38dca257d76fedc69ce513f524b594a954838cf1edf312eeb1d454259e2d86ec): 
Multus: [default/samplepod]: error loading k8s delegates k8s args: TryLoadPodDelegates: 
error in getting k8s network from pod: GetNetworkDelegates: failed getting the delegate: 
GetCNIConfig: err in GetCNIConfigFromFile: No networks found in /etc/cni/multus/net.d
```

Notice the last part of the error: `No networks found in /etc/cni/multus/net.d`
I'm perplexed where this path comes from.

After using the following configuration, with the `cniConfDIr` set to this very path `/etc/cni/multus/net.d`, everything
works as expected:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-operator
spec:
  profile: demo
  components:
    cni:
      enabled: true
      namespace: kube-system
  values:
    global:
      jwtPolicy: first-party-jwt
    cni:
      chained: false
      cniBinDir: /opt/cni/bin
      cniConfDir: /etc/cni/multus/net.d
      cniConfFileName: "istio-cni.conf"
      excludeNamespaces:
       - istio-system
       - kube-system
      logLevel: debug 
    sidecarInjectorWebhook:
      injectedAnnotations:
        "k8s.v1.cni.cncf.io/networks": istio-cni
```

Also, the `/etc/cni/multus/net.d` now contains the "istio-cni.conf" config file.
So this leads me to a conclusion, that `cniConfDir` should be described as a path to directory
where cni configuration files will be generated.

Another question that I must ask is, where is the path `/etc/cni/multus/net.d` coming from?
Is istio-cni binary looking here for configuration by default?
If so, it should be documented somewhere, ideally noted in the description of the `cniConfDir` field.

**Affected product area (please put an X in all that apply)**

[ x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.9.0
**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**
Cent0S_8_Stream

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
