### ISSUE TITLE
envoyfilter does not respect sni in http_filter when gateway has multiple hosts defined

### ISSUE THREAD

**Issue by samene** [istio/istio#32862]
**Bug description**

I have a Gateway

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: myapp-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - bosk21portal.myapp.com
    - testorg1.myapp.com   #<---- note this entry
    port:
      name: https-portal
      number: 443
      protocol: HTTPS
    tls:
      credentialName: myapp-istio-gateways-myapp-gateway
      minProtocolVersion: TLSV1_2
      mode: SIMPLE
  - hosts:
    - testorg2.myapp.com
    port:
      name: https-portal-testorg1-myapp-com
      number: 443
      protocol: HTTPS
    tls:
      credentialName: myapp-istio-gateways-testorg1-myapp-com
      minProtocolVersion: TLSV1_2
      mode: SIMPLE
```
And a envoy filter 

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ext-authn
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
          sni: bosk21portal.myapp.com   # <---- note this entry
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.ext_authz
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
          grpc_service:
            google_grpc:
              stat_prefix: ext_authz
              target_uri: ems-authn.authn.svc:8000
            timeout: 1s
          status_on_error:
            code: Unauthorized
          transport_api_version: V3
```
**Expectation**

Filter should only apply for ```bosk21portal.myapp.com```. But it also applies for ```testorg1.myapp.com```.

```testorg2.myapp.com``` on the other hand is correctly not filtered.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Istio 1.9.1

**How was Istio installed?**
Istio Operator

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS
BareMetal K8s 1.20

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
