### ISSUE TITLE
Traffic mirroring guide uses deprecated parameters

### ISSUE THREAD

**Issue by natanmoraes** [istio/istio#32884]
I was following the instructions from https://istio.io/latest/docs/tasks/traffic-management/mirroring/ to implement traffic mirroring and I noticed that in the first bullet of the section `Mirroring traffic to v2` it says to configure the `mirrorPercent` property. Now, the [Virtual Service doc](https://istio.io/latest/docs/reference/config/networking/virtual-service/) states that the property is deprecated in favor of `mirrorPercentage` so the mirroring doc should be updated to use the correct property.
**How it is now:**
```
...
    mirror:
      host: httpbin
      subset: v2
    mirrorPercent: 100
```
**How it should be, according to the docs:**
```
...
    mirror:
      host: httpbin
      subset: v2
    mirrorPercentage:
      value: 100.0
```
