### ISSUE TITLE
Istiod not correctly loading some configured meshconfig values

### ISSUE THREAD

**Issue by frankbu** [istio/istio#32886]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

When installing Istio with the following configuration, some of the meshconfig settings are not properly loaded:

```
cat <<EOF > test-configmap.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  meshConfig:
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
    localityLbSetting:
      enabled: false
    enableAutoMtls: false
    ingressClass: foo
    defaultConfig:
      drainDuration: 46s
EOF
istioctl install -f test-configmap.yaml
```

Looking at the istiod logs, it shows that the `ingressClass` and `drainDuration` are correctly set to `foo` and `46s`, but the other 3 seem to have empty values, as shown here:

2021-05-14T20:44:17.376817Z	info	Loaded MeshConfig config from Kubernetes API server.
2021-05-14T20:44:17.376959Z	info	mesh configuration updated to: (*v1alpha1.MeshConfig)(0xc000a94fc0)(proxy_listen_port:15001 connect_timeout:<seconds:10 > protocol_detection_timeout:<> ingress_class:"foo" ingress_service:"istio-ingressgateway" ingress_controller_mode:STRICT enable_tracing:true default_config:<config_path:"./etc/istio/proxy" binary_path:"/usr/local/bin/envoy" service_cluster:"istio-proxy" drain_duration:<seconds:46 > parent_shutdown_duration:<seconds:60 > discovery_address:"istiod.istio-system.svc:15012" proxy_admin_port:15000 control_plane_auth_policy:MUTUAL_TLS stat_name_length:189 concurrency:<value:2 > tracing:<zipkin:<address:"zipkin.istio-system:9411" > > status_port:15020 termination_drain_duration:<seconds:5 > > outbound_traffic_policy:<> enable_auto_mtls:<> trust_domain:"cluster.local" default_service_export_to:"*" default_virtual_service_export_to:"*" default_destination_rule_export_to:"*" root_namespace:"istio-system" locality_lb_setting:<enabled:<> > dns_refresh_rate:<seconds:5 > thrift_config:<> enable_prometheus_merge:<value:true > )

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

`outbound_traffic_policy` should have value `mode: REGISTRY_ONLY`, `locality_lb_setting.enabled` and `enable_auto_mtls` should have values `false`.

**Steps to reproduce the bug**

See description.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

Latest build.

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
