### ISSUE TITLE
AKS + ISTIO 1.9 + CNI + AZURE polixy erro to create sidecar

### ISSUE THREAD

**Issue by mcabrito** [istio/istio#32883]
(** NOTE **: This is used to report product bugs:
  To report a security vulnerability, visit <https://istio.io/about/security-vulnerabilities>
  To ask questions on how to use Istio, visit <https://discuss.istio.io>)

** Description of the bug **
Error creating the sidecar and the error message appears on the deployment:

```
  Error creating: Internal error occurred: failed calling webhook
  "sidecar-injector.istio.io": Post
  "https: //istiod.istio-system.svc: 443 / inject? timeout = 30s": dial tcp
  10.0.60.118:443: i / o timeout
```

** Affected product area (put an X in all applicable options) **

[] Docs
[] Installation
[] Networking
[] Performance and scalability
[] Extensions and telemetry
[ ] Safety
[X] Test and Release
[X] User experience
[] Developer infrastructure
[] Improvement

** Affected features (put an X in all that apply) **

[] Multi Cluster
[ ] Virtual machine
[] Multiple control plan

**Expected behavior**

** Steps to reproduce the bug **
Install AKS cluster with kubernetes version 1.19.9, enable CNI and use policy Azure.
Install istio using the manifest:
istioctl install -f install-istio.yaml
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-control-plane
spec:
  components:
    cni:
      enabled: true
    base:
      enabled: true
    pilot:
      enabled: true
  # Use the default profile as the base
  # More details at: https://istio.io/docs/setup/additional-setup/config-profiles/
  profile: default
  values:
    global:
      # Ensure that the Istio pods are only scheduled to run on Linux nodes
      defaultNodeSelector:
        beta.kubernetes.io/os: linux
    cni:
      excludeNamespaces:
       - istio-system
       - kube-system
       - kube-node-lease
       - kube-public
      logLevel: info
```

Install bookinfo:
https://istio.io/latest/docs/examples/bookinfo/
https://docs.microsoft.com/pt-br/azure/aks/servicemesh-istio-install?pivots=client-operating-system-linux

** Version ** (includes the output of `istioctl version --remote` and` kubectl version --short` and` helm version --short` if you used Helm)
```
$ istioctl version --remote
2 errors occurred:
        * error port-forwarding into istiod-9445656d7-zggd5.istio-system: an error on the server ("unknown") has prevented the request from succeeding (get pods istiod-9445656d7-zggd5: 15014)
        * error exec'ing into istiod-9445656d7-zggd5 discovery container: error exec'ing into istiod-9445656d7-zggd5 / istio-system discovery container: error dialing backend: dial tcp 10.183.0.5:10250: i / o timeout
1.9.5
```

```
$ kubectl version --short
Client Version: v1.21.0
Server Version: v1.19.9
```

** How was Istio installed? **
It was installed using the guidelines that are in the links:
https://istio.io/latest/docs/setup/additional-setup/cni/
https://docs.microsoft.com/en-us/azure/aks/servicemesh-istio-install?pivots=client-operating-system-linux

** Environment where the bug was observed (cloud vendor, operating system, etc.) **

Azure AKS.

Also, consider running `istioctl bug-report` and attach the cluster state tarball generated for this problem.
See [cluster status file] (http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

```
[istio-1.9.5 / samples / bookinfo $ istioctl bug-report

Target cluster context: aks

Running with the following config:

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {}
exclude: {Namespaces: kube-system, kube-public, kube-node-lease, local-path-storage} AND {Namespaces: kube-system, kube-public, kube-node-lease, local-path-storage}
end-time: 2021-05-14 12: 51: 01.9497592 -0300 -03


The following Istio control plane revisions / versions were found in the cluster:
Revision default:
2 errors occurred:
        * error port-forwarding into istiod-9445656d7-zggd5.istio-system: an error on the server ("unknown") has prevented the request from succeeding (get pods istiod-9445656d7-zggd5: 15014)
        * error exec'ing into istiod-9445656d7-zggd5 discovery container: error exec'ing into istiod-9445656d7-zggd5 / istio-system discovery container: error dialing backend: dial tcp 10.183.0.5:10250: i / o timeout



The following proxy revisions / versions were found in the cluster:


Fetching proxy logs for the following containers:

httpd / httpd-deployment / httpd-deployment-765d4d7947-n6n7x / httpd
istio-operator / istio-operator / istio-operator-c6cb49d99-dmln5 / istio-operator
istio-system // istio-cni-node-8pwn6 / install-cni
istio-system // istio-cni-node-8pwn6 / repair-cni
istio-system // istio-cni-node-8tr42 / install-cni
istio-system // istio-cni-node-8tr42 / repair-cni
istio-system // istio-cni-node-p7dxm / install-cni
istio-system // istio-cni-node-p7dxm / repair-cni
istio-system / istio-ingressgateway / istio-ingressgateway-5dc85cccdb-r76nv / istio-proxy
istio-system / istiod / istiod-9445656d7-zggd5 / discovery
nginx / nginx-deployment / nginx-deployment-7559c7bfff-ph28l / nginx

Fetching Istio control plane information from cluster.

The following fetches are still running:
  ProxyGet istio-system / istio-ingressgateway-5dc85cccdb-r76nv: certs
  PodExec istio-system / istiod-9445656d7-zggd5 / discovery: pilot-discovery request GET debug / adsz
  PodLogs istio-operator / istio-operator-c6cb4

9d99-dmln5 / istio-operator
  PodLogs istio-system / istiod-9445656d7-zggd5 / discovery
  PodExec istio-system / istio-ingressgateway-5dc85cccdb-r76nv / istio-proxy: find / var / lib / istio -name core. *
  PodExec istio-system / istio-ingressgateway-5dc85cccdb-r76nv / istio-proxy: netstat -natpw
  PodLogs istio-system / istio-ingressgateway-5dc85cccdb-r76nv / istio-proxy

Running istio analyze on namespace nginx.
Running istio analyze on namespace httpd.
Running istio analyze on namespace istio-operator]([url](url))
```
[bug-report.zip](https://github.com/istio/istio/files/6479993/bug-report.zip)
