### ISSUE TITLE
Failed to extract node metadata: json: cannot unmarshal string into Go struct field BootstrapNodeMetadata2.POD_PORTS of type []model.PodPort

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#32894]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
workloadgroup has port，makes this bug。
**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**
```
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadGroup
metadata:
  name: httpd
  namespace: vm-httpd
spec:
  metadata:
    labels:
      app: httpd
      type: vm
  template:
    ports:
      http: 80
    serviceAccount: sa-httpd
    network: ""
```
**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
[root@master01 workloadgroups]# istioctl version --remote
client version: 1.10.0-rc.1
control plane version: 1.10.0-rc.1
data plane version: 1.10.0-rc.1 (3 proxies)
**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
