### ISSUE TITLE
Is it possible to shifting traffic between different hosts

### ISSUE THREAD

**Issue by chenlein** [istio/istio#32915]
**Describe the feature request**
I created three svc for different versions:
```shell
[root@m-0 ~]# kubectl get svc -n stage 
NAME          TYPE       CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
details       NodePort   10.105.52.35     <none>        9080:32399/TCP   137m
productpage   NodePort   10.106.80.182    <none>        9080:31454/TCP   118m
ratings       NodePort   10.110.18.221    <none>        9080:30752/TCP   136m
reviews       NodePort   10.98.64.72      <none>        9080:30141/TCP   41m
reviews-1     NodePort   10.103.61.220    <none>        9080:32072/TCP   129m
reviews-2     NodePort   10.96.208.189    <none>        9080:32163/TCP   127m
reviews-3     NodePort   10.111.148.140   <none>        9080:30278/TCP   126m
```
and can I use vs like the following?
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: supposedly-pleased-stag
  namespace: notably-distinct-ocelot
spec:
  hosts:
  - reviews
  http:
  - route:
    - destination:
        host: reviews-1.stage.svc.cluster.local
        port:
          number: 9080
      weight: 30
    - destination:
        host: reviews-2.stage.svc.cluster.local
        port:
          number: 9080
      weight: 30
    - destination:
        host: reviews-3.stage.svc.cluster.local
        port:
          number: 9080
      weight: 40
```

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
