### ISSUE TITLE
How to configure istio to open port 80 / 443?

### ISSUE THREAD

**Issue by catman002** [istio/istio#32931]
[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**istio1.19.5**

How to configure istio to open port 80 / 443?
I set istio ingress gateway (80) and gateway (80), it doesn't work. 
Don't I have permission?

**Comment by catman002** [comment]
**edit istio-ingressgateway:**
 ISTIO_META_UNPRIVILEGED_POD=true was set, removed that env var.
 then changed the securityContext like this:
···
        securityContext: 
          privileged: true
          readOnlyRootFilesystem: true
···

**Comment by jmajoor** [comment]
Where / how do you set these configurations?
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    discoverySelectors:
      - matchLabels:
          istio-discovery: enabled
    accessLogFile: /dev/stdout
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "false"
  values:
    global:
      logging:
        level: 'all:debug'
      meshID: mesh1
      multiCluster:
        clusterName: east-cluster
      network: network1
    gateways:
      istio-ingressgateway:
        runAsRoot: true
        env:
          ISTIO_META_UNPRIVILEGED_POD: "false"
```
However I still get the  ` skipping privileged gateway port 443 for node istio-ingressgateway-559d9c4ccf-vsr4h.istio-system as it is an unprivileged pod` in the log and no listeners for the ingress gateway.
