### ISSUE TITLE
IST0128 is not always an error

### ISSUE THREAD

**Issue by arcivanov** [istio/istio#32936]
**Bug description**
```
$ istioctl analyze -A 
Error [IST0128] (DestinationRule external-service.istio-system) DestinationRule istio-system/external-service in namespace istio-system has TLS mode set to SIMPLE but no caCertificates are set to validate server identity for host: service.example.com
```

This error is valid for when `service.example.com` is not a ServiceEntry remote host with MESH_EXTERNAL. 
But if it is external, no caCertificates have to be specified as default public CA trusts are, presumably, used.

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[x] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Either downgrade to a warning or check if referenced service is part of an external mesh ServiceEntry and then warn, otherwise error.

**Steps to reproduce the bug**
1.
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-service
  namespace: istio-system
spec:
  hosts:
  - service.example.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: external-service
  namespace: istio-system
spec:
  host: service.example.com
  trafficPolicy:
    tls:
      mode: SIMPLE
```
2. istioctl analyze -A

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

1.8.6

**How was Istio installed?**

Operator
