### ISSUE TITLE
Istio-Proxy fails to start with K8S Egress NetworkPolicy

### ISSUE THREAD

**Issue by unmarshall** [istio/istio#32945]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
With egress network policy, the istio-proxy container should come up.

**Steps to reproduce the bug**

Set of commands to reproduce the issue:
```
kubectl create ns t1
kubectl label ns t1 nsname=t1ns

kubectl create ns t2
kubectl label ns t2 nsname=t2ns

kubectl create ns t3
kubectl label ns t3 nsname=t3ns


kubectl -n t1 apply -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx1
  labels:
    app: nginx1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx1
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx1
  name: nginxs1
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx1
EOF

kubectl -n t2 apply -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2
  labels:
    app: nginx2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx2
  name: nginxs2
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx2
EOF

kubectl -n t3 apply -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx3
  labels:
    app: nginx3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx3
  template:
    metadata:
      labels:
        app: nginx3
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx3
  name: nginxs3
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx3
EOF
```

Create a network policy and apply it on t1 namespace

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: t1-netpol
  namespace: t1
spec:
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          nsname: t2ns
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          nsname: t3ns
      podSelector:
        matchLabels:
          app: nginx3
  podSelector:
    matchLabels:
      app: nginx1
```

Restart nginx1 deployment. Istio-Proxy sidecar does not come up, however the nginx container comes up. If you set 1proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'` annotation then nginx container will also not come up since it will then wait for the istio-proxy container to come up.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

- istioctl version                                                                                                                                                        git:master*
client version: 1.9.1
control plane version: 1.9.1
data plane version: 1.9.1

- kubectl version --short
 Client Version: v1.21.0
 Server Version: v1.17.17
`testing `
**Environment where the bug was observed (cloud vendor, OS, etc)**
Kubernetes

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by unmarshall** [comment]
[nginx1-5fb6bf9d75-xrz44.log](https://github.com/istio/istio/files/6508540/nginx1-5fb6bf9d75-xrz44.log)
Attaching the logs from the istio-proxy container.

**Comment by unmarshall** [comment]
The readiness probe fails with the following message:
`Readiness probe failed: HTTP probe failed with statuscode: 503`

**Comment by howardjohn** [comment]
Pods need to be able to talk to kube-dns and istiod to start.

**Comment by unmarshall** [comment]
I tried to add an additional egress rule to allow traffic to `namespaceSelector` for istio-system. The issue is that if an egress rules explicitly requires to allow istio-system then all containers within a pod will get access to privileged namespaces like kube-system (where dns pods are running) and istio-system (where istiod is running). This makes using egress not possible.

**Comment by howardjohn** [comment]
Can you call `curl https://istiod.istio-system:443` from the pod? if not perhaps your rules are set up wrong still

**Comment by unmarshall** [comment]
I was able to change the network policies to make this work. I will close this issue now.

**Comment by unmarshall** [comment]
To help anyone else who also faces this issue, following are the network policies that i applied. Please check the labels in your own setup and make changes accordingly.

Allow egress to kube-dns in order to use cluster DNS
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns-access
  namespace: t1
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
    - ports:
        - protocol: UDP
          port: 8053
        - protocol: TCP
          port: 8053
      to:
        - podSelector:
            matchExpressions:
              - key: k8s-app
                operator: In
                values:
                  - kube-dns
          namespaceSelector:
            matchLabels:
              gardener.cloud/purpose: kube-system
```
Allow egress to istiod
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-to-istiod
  namespace: t1
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: istio-system
      podSelector:
        matchLabels:
          istio: pilot
```
Allow egress to t2ns namespace only
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-to-t2ns
  namespace: t1
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          nsname: t2ns
      podSelector: {}
```
Allowing ingress from nginx3 only
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-from-nginx3
  namespace: t1
spec:
  podSelector:
    matchLabels:
      app: nginx1
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: nginx3
        namespaceSelector: {}
```
