### ISSUE TITLE
egress gateway with PASSTHROUGH TLS configuration results in 400  DPE errors in downstream

### ISSUE THREAD

**Issue by darkstarmv** [istio/istio#32954]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
I have setup Istio in K8s cluster *A* to proxy services in  k8s cluster *B* using Istio Ingress and Egress gateways with VirtualServices and corresponding ServiceEntries and DestinationRules. Everything works fine with HTTP and HTTPS termination in cluster *A*.

`client ---> [istio Ingress Gateway Cluster A]-->[istio Egress Gateway Cluster A]-->[istio K8s Ingress  Cluster B]-->[Application in  Cluster B]`

We want to have TLS from client all the way to Application in cluster B.
When I tried to configure  TLS PASSTHROUGH in Istio K8s Cluster A, I can see *400* DPE errors in K8s Cluster B Istio ingress logs:

**{"response_code":400,"connection_termination_details":null,"request_id":null,"upstream_cluster":null,"downstream_local_address":"192.168.192.38:8443","bytes_sent":11,"user_agent":null,"downstream_remote_address":"192.168.192.33:58691","path":null,"bytes_received":0,"route_name":null,"upstream_host":null,"x_forwarded_for":null,"duration":0,"start_time":"2021-05-18T20:38:57.785Z","response_flags":"DPE","response_code_details":"http1.codec_error","requested_server_name":"sampleapp.remote.sample.com","method":null,"upstream_transport_failure_reason":null,"authority":null,"protocol":"HTTP/1.1","upstream_local_address":null,"upstream_service_time":null}**

and `error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number` in the curl response.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
I should be able to configure TLS Proxy to external services

**Steps to reproduce the bug**
#### 1. Ingress and Egress Gateways are setup with:
```
spec:
  selector:
    app: istio-gw-internal
    istio: ingressgateway
  servers:
  - hosts:
     - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
  - hosts:
    - '*'
    port:
      name: tls
      number: 443
      protocol: TLS
    tls:
      mode: PASSTHROUGH
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
```
#### 2. Virtual Service:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-sampleapp
  namespace: istio-namespace
spec:
  exportTo:
  - .
  gateways:
  - istio-namespace/istio-egressgateway
  - istio-namespace/istio-gw-internal
  hosts:
  - sampleapp.sample.com
  tls:
  - match:
    - gateways:
      - istio-namespace/istio-gw-internal
      port: 443
      sniHosts:
      - sampleapp.sample.com
    route:
    - destination:
        host: istio-egressgateway.istio-namespace.svc.cluster.local
        subset: egress-dr
  - match:
    - gateways:
      - istio-namespace/istio-egressgateway
      port: 443
      sniHosts:
      - sampleapp.sample.com
    route:
    - destination:
        host: sampleapp.remote.sample.com
        port:
          number: 443

```
#### 4. Service Entry

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: vs-sampleapp
  namespace: istio-namespace
spec:
  hosts:
  - sampleapp.remote.sample.com
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
  endpoints:
  - address: sampleapp.remote.sample.com
    network: external
  - address: istio-egressgateway.istio-namespace.svc.cluster.local

```

#### 5. Destination rules

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: istio-proxy-egress-lb
  namespace: istio-namespace
spec:
  host: sampleapp.remote.sample.com
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE
        sni: sampleapp.remote.sample.com

```

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egress-dr
  namespace: istio-namespace
spec:
  exportTo:
  - .
  host: istio-egressgateway.istio-namespace.svc.cluster.local
  subsets:
    - name: egress-dr
```
####  Execute curl command:

```
curl -Ivso --http2   https://sampleapp.sample.com
*   Trying 10.49.54.20...
* TCP_NODELAY set
* Connected to sampleapp.sample.com (10.49.54.20) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [282 bytes data]
* error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
* Closing connection 0
```
####  Cluster A Ingress Proxy log

{"level":"debug","time":"2021-05-18T20:38:57.779567Z","scope":"envoy filter","msg":"tls:onServerName(), requestedServerName: sampleapp.sample.com"}
{"level":"debug","time":"2021-05-18T20:38:57.781623Z","scope":"envoy filter","msg":"[C2614] TCP:onUpstreamEvent(), requestedServerName: sampleapp.sample.com"}
{"requested_server_name":"sampleapp.sample.com","start_time":"2021-05-18T20:38:57.770Z","upstream_transport_failure_reason":null,"x_forwarded_for":null,"response_flags":"-","downstream_local_address":"172.30.128.231:8443","upstream_cluster":"outbound|443|egress-dr|istio-egressgateway.istio-namespace.svc.cluster.local","response_code_details":null,"route_name":null,"response_code":0,"method":null,"duration":104,"connection_termination_details":null,"user_agent":null,"bytes_sent":162,"downstream_remote_address":"172.30.128.225:10690","authority":null,"upstream_local_address":"172.30.128.231:39146","bytes_received":287,"protocol":null,"path":null,"upstream_host":"172.30.128.39:15443","upstream_service_time":null,"request_id":null}

####  Cluster A Egress Proxy Log

{"level":"debug","time":"2021-05-18T20:38:57.782024Z","scope":"envoy filter","msg":"tls:onServerName(), requestedServerName: sampleapp.sample.com"}
{"level":"debug","time":"2021-05-18T20:38:57.782107Z","scope":"envoy filter","msg":"[C173] Creating connection to cluster outbound|443||sampleapp.remote.sample.com"}
{"level":"debug","time":"2021-05-18T20:38:57.785108Z","scope":"envoy filter","msg":"[C173] TCP:onUpstreamEvent(), requestedServerName: sampleapp.sample.com"}
{"method":null,"start_time":"2021-05-18T20:38:57.781Z","bytes_received":287,"response_flags":"-","path":null,"authority":null,"protocol":null,"upstream_host":"172.31.91.232:443","x_forwarded_for":null,"upstream_local_address":"172.30.128.39:51332","downstream_remote_address":"172.30.128.231:39146","route_name":null,"downstream_local_address":"172.30.128.39:15443","upstream_transport_failure_reason":null,"upstream_cluster":"outbound|443||sampleapp.remote.sample.com","response_code_details":null,"requested_server_name":"sampleapp.sample.com","bytes_sent":162,"duration":1005,"request_id":null,"connection_termination_details":null,"response_code":0,"user_agent":null,"upstream_service_time":null}

####  Remote Cluster B Istio K8s Ingress log

{"level":"debug","time":"2021-05-18T20:38:57.784569Z","scope":"envoy filter","msg":"tls:onServerName(), requestedServerName: sampleapp.remote.sample.com"}
{"response_code":400,"connection_termination_details":null,"request_id":null,"upstream_cluster":null,"downstream_local_address":"192.168.192.38:8443","bytes_sent":11,"user_agent":null,"downstream_remote_address":"192.168.192.33:58691","path":null,"bytes_received":0,"route_name":null,"upstream_host":null,"x_forwarded_for":null,"duration":0,"start_time":"2021-05-18T20:38:57.785Z","response_flags":"DPE","response_code_details":"http1.codec_error","requested_server_name":"sampleapp.remote.sample.com","method":null,"upstream_transport_failure_reason":null,"authority":null,"protocol":"HTTP/1.1","upstream_local_address":null,"upstream_service_time":null}

 

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
istioctl version --remote
client version: 1.9.0
control plane version: 1.9.5
data plane version: 1.9.5 (7 proxies)
```
```
kubectl version --short
Client Version: v1.18.19
Server Version: v1.18.17
```
```
helm version --short
v3.5.3+g041ce5a
```

**How was Istio installed?**
Istio installed with Helm

**Environment where the bug was observed (cloud vendor, OS, etc)**

BYO K8s running in GCE

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
