### ISSUE TITLE
Getting 502s for external services after enabling sidecar

### ISSUE THREAD

**Issue by leoncard** [istio/istio#32988]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

Hello, I am trying to add the sidecar to one of our pods.

I added the following `ServiceEntry` with the `port` and `address` of the external load balancer (nginx) the pod needs to communicate with.

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  annotations:
  name: integrationlb
  namespace: integration
spec:
  hosts:
  - mynginx.ext
  location: MESH_EXTERNAL
  ports:
  - name: http2
    number: 90
    protocol: tcp
  - name: httplb
    number: 8888
    protocol: tcp
  resolution: DNS
```

Without the sidecar, all my requests work giving a 200.

With the sidecar enabled if I try to reach an endpoint such as `http://mynginx.ext:8888/mypath` it still works.

However, for endpoints that need a host header such as `http://mynginx.ext:90/mypath- H "Host: myheader"` I get 502s.

We have to pass the host header so that it can be redirected correctly on nginx.

The istio-proxy  which is running on the pod gives me the log 

`433:[2021-05-20T09:42:53.211Z] "GET /mypath HTTP/1.1" 502 - "-" "-" 0 0 0 - "-" "curl/7.64.0" "bb49707a-95de-91e2-baad-51af2b124275" "myheader" "-" - - 192.137.0.4:90 10.244.9.91:43292 - block_all`

Where `192.137.0.4` is the ip of `mynginx.ext` and `10.244.9.91` the ip of the pod.

The output of the failing curl command is

```
* Expire in 0 ms for 6 (transfer 0x555fed48dfb0)   // This appears many times
...
*   Trying 192.137.0.4...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x555fed48dfb0)
* Connected to mynginx.ext (192.137.0.4) port 90 (#0)
> GET /mypath HTTP/1.1
> Host: myheader
> User-Agent: curl/7.64.0
> Accept: */*
> 
< HTTP/1.1 502 Bad Gateway
< date: Thu, 20 May 2021 10:02:09 GMT
< server: envoy
< content-length: 0
< 
* Connection #0 to host mynginx.ext left intact
```
If I change the host header to anything else like `myheaderXYZ` it also gives a 502 even though  `myheaderXYZ` doesn't exist.

I can't find any logs on nginx related with the request.

It seems that the request is getting lost somewhere when I apply the sidecar, without the sidecar it just works.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Calls to `http://mynginx.ext:90/mypath- H "Host: myheader"` should return 200.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
./istioctl version
client version: 1.7.3
control plane version: 1.7.3
data plane version: 1.7.3 (76 proxies)
```

```
kubectl version --short
Client Version: v1.13.1
Server Version: v1.19.1
```

**How was Istio installed?**

Through istioctl

**Environment where the bug was observed (cloud vendor, OS, etc)**

Ubuntu 20 Virtual Machine on HyperV
