### ISSUE TITLE
Make endpoint of sidecar /quitquitquit triggered with GET HTTP call

### ISSUE THREAD

**Issue by dntosas** [istio/istio#33017]
**Describe the feature request**
Make endpoint of sidecar `http://127.0.0.1:15020/quitquitquit` be capable of triggered also with `GET` HTTP requests instead of `POST` only.

This will enable the usage of `httpGet` [handler of Kubernetes](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#Handler) on `preStop` hooks and gives users the opportunity to more efficiently manage resources like cronJobs etc.

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by dntosas** [comment]
Here is the code block that rejects anything but POST method --> https://github.com/istio/istio/blob/c1493b869ffd0693b369109aa7286b44c4e26a89/pilot/cmd/pilot-agent/status/server.go#L502-L505

**Comment by howardjohn** [comment]
This seems potentially dangerous.

Does this actually work for cronjob? i tested with:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  template:
    spec:
      containers:
      - name: alpine
        image: howardjohn/shell
        command: ["sh", "-c", "sleep 5; echo done"]
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - |
                curl -XPOST localhost:15020/quitquitquit
      restartPolicy: Never

```

and it doesn't work, the prestop only runs if k8s terminates the container, not if it exits on its own
