### ISSUE TITLE
Attaching multiple gateways to a single istio ingressgateway

### ISSUE THREAD

**Issue by V3ckt0r** [istio/istio#33015]
**Bug description**
Not 100% this is a bug and may be intended behaviour. I'm facing the same issue described in [this](https://discuss.istio.io/t/attaching-multiple-gateways-to-istios-ingressgateway/5294) post. TL:DR, I can't attach multiple gateways to a single ingress-gateway without hitting an issue over listener port clashes
```
2021-05-18T20:24:19.069384Z    warning    envoy config    gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_8443: duplicate listener 0.0.0.0_8443 found
```
I haven't been able to find any documentation on this so reaching out. If this a known thing can we get some docs in the appropriate location to state this. 
The second part to this is - if this is indeed expected behaviour, what is the idiomatic way for having one ingress-gateway route through two separate hosts with respective certs? 

[X] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Two separate hosts get routed to their respective destinations.

**Steps to reproduce the bug**
Follow steps described [here](https://discuss.istio.io/t/attaching-multiple-gateways-to-istios-ingressgateway/5294). For brevity I've pasted the yaml below:

First gateway
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gw1
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - ns1/*
    port:
      name: http
      number: 80
      protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs1
  namespace: ns1
spec:
  gateways:
  - gw1.istio-system.svc.cluster.local
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /devapi
    route:
    - destination:
        host: devapi-service.ns1.svc.cluster.local
        port:
          number: 8080
```

Second gateway
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gw2
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - istio-system/*
    port:
      name: http
      number: 80
      protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs2
  namespace: istio-system
spec:
  gateways:
  - gw2.istio-system.svc.cluster.local
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /query
    route:
    - destination:
        host: query-service.istio-system.svc.cluster.local
        port:
          number: 8080
```
Ignore for a moment why this service is deployed to istio-system namespace

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
istioctl
```
istioctl version --remote
client version: 1.9.4
control plane version: 1.8.4
data plane version: 1.8.4 (12 proxies)
```

kubectl
```
Client Version: v1.18.5
Server Version: v1.18.9-eks-d1db3c
```

**How was Istio installed?**
Operator

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS EKS

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
Hi, I think there must be more Gateway configs causing this. Both of these are for port 80 HTTP, so I don't think it would cause the error. Can you show all of your configs?

my guess is you have one gateway pointing to the service port (443) and one to the target port (8443)?

**Comment by V3ckt0r** [comment]
Hey @howardjohn - sorry to cause confusion. I copied the yaml above from that post. where as the duplicate listener error I provided is from my system. You can find my yaml config at the end. I wanted to get at the point that both my gateways are bound to the same ingress-gateway via the selector and this shouldn't cause a duplicate listener error.

The ingress-gateway itself is setup with port 443 to targetPort 8443. For gw1 I have a successful listener setup as can be seen below with istioctl:
```
ADDRESS PORT  MATCH                              DESTINATION
0.0.0.0 8443  SNI: example.com Route: https.443.https.gw1.istio-system
```

however for gw1 which is using 8443 the listener doesn't come up and I hit the duplicate listener issue.

@bianpengyuan Thanks for linking that PR. Looking at the history and related mentions this does seem to look like the same thing. 

gateway yaml:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gw1
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - ns1/*
    port:
      name: https
      number: 443
      protocol: HTTPS
```

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gw2
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - istio-system/*
    port:
      name: https
      number: 8443
      protocol: HTTPS
```
