### ISSUE TITLE
configSources not working for Istio 1.10.0

### ISSUE THREAD

**Issue by lucasslima** [istio/istio#33027]
**Bug description**
I'm developing a MCP over XDS solution using minikube, but noticed that moving from `1.9.5` to `1.10.0` my XDS server stops receiving requests altogether. Only the initial DiscorveryRequest by the configSource XDS server is registered in istiod logs, no `adsc` logs from istiod are logged.

Here's is the 

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Istiod should 
**Steps to reproduce the bug**

Just get a working configSource in version `1.9.5` and move to `1.10.0`
**How was Istio installed?**
I'm using the Istio Operator with the following configuration:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
  namespace: istio-system
spec:
  values:
    global:
      jwtPolicy: third-party-jwt
  profile: default
  tag: 1.10.0
  # revision: stable
  meshConfig:
    enableAutoMtls: true
    # accessLogFile: /dev/stdout
    outboundTrafficPolicy:
      mode: ALLOW_ANY
    defaultConfig:
      meshId: minikube
    configSources:
    - address: xds://192.168.49.1:1109
  components:
    pilot:
      k8s:
        service: 
          type: NodePort
    ingressGateways:
    - name: istio-ingressgateway
      enabled: false
```
**Environment where the bug was observed (cloud vendor, OS, etc)**
minikube
This was observed on a `minikube` installation.
