### ISSUE TITLE
Locality failover load balancing not working from istio ingress gateway -- istio 1.9.4

### ISSUE THREAD

**Issue by vijay2308** [istio/istio#33024]
**Bug description**
I have istio 1.9.4 installed with multi cluster ,multi primary, different network setup. 

i am trying to implement  locality failover load balancing from istio ingress gw, ( external endpoint ) used by UI . Based on my understanding, istio can do locality failover load balancing based on the outlier configs we provide in `DR`. 

here are my configs:

i have deployed one sample app in both regions where istio installed. i was able to fetch the app using virtual service configuring route and DR to point to my deployment using subsets. 

However, while implementing locality failover loadbalancing, for this to work, i have drained the envoy on `eastus2` region , so that connections will be sent to `centralus` region . 
GW:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
  namespace: apps-dev
spec:
  selector:
    app: istio-ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - eastus2.apis-test.myapp.cloud
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https-443
      protocol: HTTPS
    hosts:
    - eastus2.apis-test.myapp.cloud
    tls:
      mode: SIMPLE # enables HTTPS on this port
      credentialName: my-secret
```
VS:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: sample-service
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: sample-service
    app.kubernetes.io/part-of: portal-sample-service
    app.kubernetes.io/version: 1.0.4
  name: sample-service
  namespace: apps-dev
spec:
  gateways:
    - istio-system/apis-istio-gateway
  hosts:
    - eastus2.apis-test.myapp.cloud
  http:
    - match:
        - uri:
            regex: .*sample-service.* --> path based routing , we are doing 
      route:
        - destination:
            host: sample-service.apps-dev.svc.cluster.local
            port:
              number: 8080
            subset: sample-service

```
 ```

kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: sample-service
  namespace: apps-dev
spec:
  host: sample-service.apps-dev.svc.cluster.local
  subsets:
    - labels:
        app.kubernetes.io/component: api
        app.kubernetes.io/instance: sample-service
        app.kubernetes.io/name: template-service
      name: sample-service
  trafficPolicy:
    connectionPool:
      http:
        maxRequestsPerConnection: 1
    loadBalancer:
      localityLbSetting:
        enabled: true
        failover:
          - from: cluster-eastus2
            to: cluster-centralus
      simple: ROUND_ROBIN
    outlierDetection:
      baseEjectionTime: 1m
      consecutive5xxErrors: 1
      interval: 1s
```

one interesting thing i have observed is , i have deployed sleep pod in eastus2 cluster  and when i request sample-service from this sleep pod eg:

`curl -sSL http://sample-service.apps-dev.svc.cluster.local:8080/sample-service/ ` , i have observed the request is going to centralus region sample service through istio ingress gw on port **15443** which is expcted.

when i request the same thing from gw exposed 
`hostname: eastus2.apis-test.myapp.cloud` , i am getting `no healthy upstream` , which suggests the request is going to local service itself ( which is intentionally drained ) .

what i need ? 
when the request comes from istio ingress , and if the request fails on eastus2 , based on outlier detection configs on DR , it should route to centralus service. 

Am i missing something here ? 

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**How was Istio installed?**
Istio Operator 

**Environment where the bug was observed (cloud vendor, OS, etc)**
Azure AKS 

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
