### ISSUE TITLE
IstioOperator proxy value not applied in sidecar injector configmap

### ISSUE THREAD

**Issue by chriskim06** [istio/istio#33026]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
I tried adding a custom prestop hook for the sidecar proxies in my `IstioOperator` spec and expected the value to reflect in the sidecar injector configmap but noticed that the configmap doesn't reflect the value. Here's a snippet from the `IstioOperator` that sets the prestop command:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  revision: 1-8-5
  values:
    global:
      jwtPolicy: first-party-jwt
      proxy:
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - while [ $(netstat -plunt | grep tcp | grep -v envoy | wc -l | xargs) -ne 0 ]; do sleep 1; done
  ...
```
When I run `istioctl manifest generate --filename iop.yml` I see the configmap has the value 
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-sidecar-injector-1-8-5
  namespace: istio-system
  labels:
    istio.io/rev: 1-8-5
    install.operator.istio.io/owning-resource: unknown
    operator.istio.io/component: "Pilot"
    release: istio
data:

  values: |-
    {
      "global": {
        ...
        "proxy": {
          "autoInject": "disabled",
          "clusterDomain": "cluster.local",
          "componentLogLevel": "misc:error",
          "enableCoreDump": false,
          "excludeIPRanges": "",
          "excludeInboundPorts": "",
          "excludeOutboundPorts": "",
          "holdApplicationUntilProxyStarts": false,
          "image": "proxyv2",
          "includeIPRanges": "*",
          "lifecycle": {
            "preStop": {
              "exec": {
                "command": [
                  "/bin/sh",
                  "-c",
                  "while [ $(netstat -plunt | grep tcp | grep -v envoy | wc -l | xargs) -ne 0 ]; do sleep 1; done"
                ]
              }
            }
          },
          "logLevel": "warning",
          "privileged": false,
          "readinessFailureThreshold": 30,
          "readinessInitialDelaySeconds": 1,
          "readinessPeriodSeconds": 2,
          "resources": {
            "limits": {
              "cpu": "2000m",
              "memory": "1024Mi"
            },
            "requests": {
              "cpu": "100m",
              "memory": "128Mi"
            }
          },
          "statusPort": 15020,
          "tracer": "zipkin"
        },
        ...
    }
```
the actual configmap that gets created after running `istioctl install --istioNamespace istio-system --filename iop.yml` just has this for the prestop command
```json
        "proxy": {
          "autoInject": "disabled",
          "clusterDomain": "cluster.local",
          "componentLogLevel": "misc:error",
          "enableCoreDump": false,
          "excludeIPRanges": "",
          "excludeInboundPorts": "",
          "excludeOutboundPorts": "",
          "holdApplicationUntilProxyStarts": false,
          "image": "proxyv2",
          "includeIPRanges": "*",
          "lifecycle": {
            "preStop": {
              "exec": {
                "command": [
                  "sleep",
                  "10"
                ]
              }
            }
          },
          "logLevel": "warning",
          "privileged": false,
          "readinessFailureThreshold": 30,
          "readinessInitialDelaySeconds": 1,
          "readinessPeriodSeconds": 2,
          "resources": {
            "limits": {
              "cpu": "2000m",
              "memory": "1024Mi"
            },
            "requests": {
              "cpu": "100m",
              "memory": "128Mi"
            }
          },
          "statusPort": 15020,
          "tracer": "zipkin"
        },
```

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
I think the configmap should have the prestop command specified in the `IstioOperator` since I can see it does when running `istioctl manifest generate`

**Steps to reproduce the bug**
1. add the following to an `IstioOperator` file
```yaml
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - while [ $(netstat -plunt | grep tcp | grep -v envoy | wc -l | xargs) -ne 0 ]; do sleep 1; done
```
2. run `istioctl install --istioNamespace istio-system --filename FILENAME`
3. check the created sidecar injector configmap to see if it has the default `sleep 10` command (I think this is default, but not sure) or the expected command defined in the `IstioOperator`

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
$ istioctl version --remote
client version: 1.8.5
istiod version: 1.7.8
istiod version: 1.7.8
istiod version: 1.8.5
istiod version: 1.8.5
data plane version: 1.7.8 (6 proxies), 1.8.5 (24 proxies)

$  kubectl version --short
Client Version: v1.16.15
Server Version: v1.16.15-eks-ad4801
```

**How was Istio installed?**
I installed it using the `IstioOperator` pasted above but without the prestop command (trying to overwrite that now). We are using canary releases going from 1.7.8 to 1.8.5.

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS EKS

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
