### ISSUE TITLE
secretfetcher   cannot find secret istio gateway

### ISSUE THREAD

**Issue by calvinShan** [istio/istio#33020]
Hello 

We can not traffic to service through istio, here is my config, the service works well
we have another http url thta works well, the https does not work
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: thebasetestapi-app
  namespace: thebase
spec:
  hosts:
  - "xxx.xx.com"
  gateways:
  - app-gateway
  http:
  - match:
    - uri:
        prefix: /thebase-test
    rewrite:
      uri: /
    route:
    - destination:
        host: xxxxx
        port:
          number: 80
---
# voting-app-gateway.yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: app-gateway
  namespace: thebase
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: aks-istio-secret
    hosts:
    - "xxx.xx.com"
```

The error from istio gateway
kubectl.exe logs istio-ingressgateway-6f86b4785f-sx7h7 -n istio-system
2021-05-21T14:40:00.805614Z     error   secretfetcher   cannot find secret aks-istio-secret and cannot find fallback secret gateway-fallback
2021-05-21T14:40:00.805620Z     warn    cache   resource:aks-istio-secret SecretFetcher cannot find secret aks-istio-secret from cache
2021-05-21T14:40:00.805628Z     warn    sds     resource:aks-istio-secret waiting for gateway secret for proxy "router~10.123.16.170~istio-ingressgateway-6f86b4785f-sx7h7.istio-system~istio-system.svc.cluster.local"

2021-05-21T14:41:00.788669Z     info    sds     resource:aks-ingress-secret connection is terminated: rpc error: code = Canceled desc = context canceled
2021-05-21T14:41:00.788707Z     info    sds     Received empty resource name from "router~10.123.16.170~istio-ingressgateway-6f86b4785f-sx7h7.istio-system~istio-system.svc.cluster.local". No need to respond
2021-05-21T14:41:00.788714Z     error   sds     Remote side closed connection

Do you have any suggestions please?

**Comment by howardjohn** [comment]
Please upgrade Istio, this code has not been used in recent versions and older versions that do are no longer supported: https://istio.io/latest/news/support/announcing-1.8-eol-final/

Also check `kubectl get secrets -n istio-system` and make sure it has  aks-istio-secret. Note it must be in istio-system, NOT `thebase`

**Comment by calvinShan** [comment]
> Please upgrade Istio, this code has not been used in recent versions and older versions that do are no longer supported: https://istio.io/latest/news/support/announcing-1.8-eol-final/
> 
> Also check `kubectl get secrets -n istio-system` and make sure it has aks-istio-secret. Note it must be in istio-system, NOT `thebase`

thanks for your reply, I have created the secret in namespace istio-system
PS C:\Users\swu\projet> kubectl get secrets -n istio-system                                                                                                                                  NAME                                               TYPE                                  DATA   AGE
aks-istio-secret                                   kubernetes.io/tls                     2      37h

But it doesn't work, the new error are:
kubectl logs istio-ingressgateway-6f86b4785f-t2bmc -n istio-system
2021-05-25T09:10:30.858656Z     info    Envoy proxy is ready
2021-05-25T09:19:42.659019Z     info    sds     resource:aks-istio-secret new connection
2021-05-25T09:19:42.665848Z     warn    secretfetcher   skip loading secret. Kubernetes secret aks-istio-secret contains a server certificate that fails to parse: failed to parse certificate: asn1: structure error: tags don't match (2 vs {class:0 tag:6 length:9 isCompound:false}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false}  @2
2021-05-25T09:19:42.665873Z     info    secretfetcher   Fail to extract secret aks-istio-secret found by direct api call
2021-05-25T09:19:42.665880Z     warn    secretfetcher   Cannot find secret aks-istio-secret, searching for fallback secret gateway-fallback
2021-05-25T09:19:42.665886Z     error   secretfetcher   cannot find secret aks-istio-secret and cannot find fallback secret gateway-fallback
2021-05-25T09:19:42.665892Z     warn    cache   resource:aks-istio-secret SecretFetcher cannot find secret aks-istio-secret from cache
2021-05-25T09:19:42.665903Z     warn    sds     resource:aks-istio-secret waiting for gateway secret for proxy "router~10.123.16.187~istio-ingressgateway-6f86b4785f-t2bmc.istio-system~istio-system.svc.cluster.local"

2021-05-25T09:20:22.665028Z     warning envoy config    StreamAggregatedResources gRPC config stream closed: 13,
2021-05-25T09:20:23.687954Z     warning envoy config    StreamAggregatedResources gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: local reset

do you have any suggestion please?

**Comment by howardjohn** [comment]
Sounds like the cert is not valid. It needs to be x509 format

**Comment by calvinShan** [comment]
> x509 format

hello, notre certifcate is pfx format, so it should be x509 format? 
what we did is :
```
openssl pkcs12 -in xxx.pfx -clcerts  -out xxx.crt
openssl pkcs12 -in xxx.pfx -nocerts -out  aaa.key
openssl rsa -in aaa.key -out xxx.key

kubectl create secret tls aks-istio-secret --cert $xxx.crt --key xxx.key -ns isitio-system

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: app-gateway
  namespace: thebase
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: aks-istio-secret
```

so it is not the right way to do so?

Thansks
