### ISSUE TITLE
Unable to install istio using istio operator - Error during reconcile: path [:].spec.template.spec.tolerations has an unexpected first element [:] in OverlayK8sSettings

### ISSUE THREAD

**Issue by aldor007** [istio/istio#33059]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

I have istio manifest like below. I want to update k8s settings. By in some cases I'm getting error.
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  annotations:
    meta.helm.sh/release-name: istio
    meta.helm.sh/release-namespace: istio-system
  creationTimestamp: "2021-05-24T17:43:49Z"
  finalizers:
  - istio-finalizer.install.istio.io
  generation: 15
  labels:
    app.kubernetes.io/managed-by: Helm
  name: istio-operator
  namespace: istio-system
spec:
  components:
    base:
      enabled: true
    egressGateways:
    - enabled: true
      name: istio-egressgateway
    ingressGateways:
    - enabled: true
      k8s:
        service:
          externalTrafficPolicy: Cluster
          loadBalancerIP: 10.100.112.17
          ports:
          - name: status-port-ingress
            port: 15021
            protocol: TCP
            targetPort: 15021
          - name: http-ingress
            port: 80
            protocol: TCP
            targetPort: 8080
          - name: https-ingress
            port: 443
            protocol: TCP
            targetPort: 8443
          - name: tls-http
            port: 15443
            protocol: TCP
            targetPort: 15443
          selector:
            app: istio-ingressgateway
            istio: istio-ingressgateway
        serviceAnnotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
          service.beta.kubernetes.io/azure-load-balancer-internal-subnet: aks-app2-svc
      label:
        app: istio-ingressgateway
        istio: istio-ingressgateway
      name: istio-ingressgateway
      namespace: istio-system
    - enabled: true
      k8s:
        service:
          externalTrafficPolicy: Cluster
          loadBalancerIP: 10.100.112.20
          ports:
          - name: cerebro
            port: 9001
            protocol: TCP
            targetPort: 9001
          selector:
            app: istio-tcp
            istio: istio-tcp
        serviceAnnotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
          service.beta.kubernetes.io/azure-load-balancer-internal-subnet: aks-app2-svc
      label:
        app: istio-tcp
        istio: istio-tcp
      name: istio-tcp
      namespace: istio-system
    istiodRemote:
      enabled: true
      k8s:
        tolerations: # adding this create error in logs 
        - effect: NoSchedule
          key: kubernetes.azure.com/scalesetpriority
          operator: Equal
          value: spot
        - effect: NoSchedule
          key: inveox.com/pool
          operator: Equal
          value: services
    pilot:
      enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2
        tolerations:
        - effect: NoSchedule
          key: kubernetes.azure.com/scalesetpriority
          operator: Equal
          value: spot
        - effect: NoSchedule
          key: inveox.com/pool
          operator: Equal
          value: services
  meshConfig:
    accessLogFile: /dev/stdout
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
  profile: default
  tag: 1.10.0
```

istio-operator logs
```
021-05-24T18:09:45.505134Z	info	installer	Reconciling IstioOperator
2021-05-24T18:09:45.506544Z	info	installer	Updating IstioOperator
2021-05-24T18:09:45.551850Z	info	installer	Detecting third-party JWT support
2021-05-24T18:09:46.602463Z	info	klog	Throttling request took 1.047081381s, request: GET:https://10.100.96.1:443/apis/configuration.konghq.com/v1?timeout=32s
2021-05-24T18:09:50.550476Z	error	installer	Error during reconcile: path [:].spec.template.spec.tolerations has an unexpected first element [:] in OverlayK8sSettings
```

[ ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Istio-operator update istio
**Steps to reproduce the bug**

1. Pre installed istio by istio-operator
2. Add k8s tolerations
3. Error should be visivle

**Version** 
istio 1.10.0
istio-operator: 1.10.0
kubernetes  AKS 1.19.7

**How was Istio installed?**

By istio-operator

**Environment where the bug was observed (cloud vendor, OS, etc)**
Azure, AKS
