### ISSUE TITLE
Ability to utilize VirtualService Selector within Authorization Policies

### ISSUE THREAD

**Issue by Kampe** [istio/istio#33058]
Hello,

It would be massively beneficial to be able to refer to a virtual service by name or identifier to then apply authorization policies on.  This would also greatly clarify the entire policy definition as well.

Ex:

```
apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
  name: "metrics-ingress-policy"
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: DENY
  rules:
  - from:
    - virtualService: ["my-vs"]
    to:
    - operation:
        paths: ["/api/*"]
```

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**
