### ISSUE TITLE
Internal error occurred: failed calling webhook gateway

### ISSUE THREAD

**Issue by calvinShan** [istio/istio#33076]
kubectl.exe apply -f .\gatewayhello                                                                                                                                Error from server (InternalError): error when creating ".\\gatewayhello": Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=30s": context deadline exceeded

The command works for a while and does not work for a while, it is not stable, can't understand what is the problem please.
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: thebasetestapi-app
spec:
  hosts:
  - "*"
  gateways:
  - app-gateway
  http:
  - match:
    - uri:
        prefix: /thebase-test
    rewrite:
      uri: /
    route:
    - destination:
        host: thebasetestapi.thebase.svc.cluster.local
        port:
          number: 80
---
# voting-app-gateway.yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: app-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
```

istio version: 1.7.3
aks 1.19.7
