### ISSUE TITLE
Istio 1.8.2 does not require TLS cert mounted on istio-ingressgateway deployment to match TLS cert stationed at gateway

### ISSUE THREAD

**Issue by AlexDHoffer** [istio/istio#33084]
**Bug description**

We recently switched to using cert manager to provide a TLS cert at our gateway like so:

````
  - hosts:
    - '*.mydomain'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: k-gateway-cert-cm-secret
      mode: SIMPLE
````

Previously, we had just used a static TLS cert that we had stored in the secrets of the namespace, called ``istio-ingressgateway-certs``.

After deploying, we hit this bug: https://github.com/istio/istio/issues/14205

We realized that our istio-ingressgateway deployment was failing to cycle or scale because its deployment was trying to mount ``istio-ingressgateway-certs``. Further, by re-adding this secret to the cluster, the pods were successfully able to cycle and scale.

My question, then, is: why are these certs allowed to be different, and what is the ``istio-ingressgateway-certs`` in the deployment responsible for?

[ x ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ x ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Consistent application of TLS certs at the gateway level

**Steps to reproduce the bug**

Remove ``istio-ingressgateway-certs`` secret from namespace and roll ``istio-ingressgateway`` deployment.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

1.8.2

**How was Istio installed?**

Standalone Operator

**Environment where the bug was observed (cloud vendor, OS, etc)**

AKS

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
A default install outputs this:
```
      - name: ingressgateway-certs
        secret:
          optional: true
          secretName: istio-ingressgateway-certs
```

So it should not block. Did you customize it to not be optional?
