### ISSUE TITLE
How to disable sidecar injection for manually created jobs?

### ISSUE THREAD

**Issue by mcandre** [istio/istio#33116]
I have the sidecar.istio.io/inject: "false" label in my cronjob pod template, yet istio continues to sidecar inject pods triggered with `kubectl create job --from`...

How do we fix this?

Related: https://github.com/jenkinsci/helm-charts/issues/374

**Comment by howardjohn** [comment]
What does the resulting pod spec look like? Not familiar with `kubectl create job`, Istio just acts on the annotation on the pod

**Comment by keyboardfann** [comment]
Hi @mcandre 
    Add  sidecar.istio.io/inject: "false" can manually disable sidecar injection.

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
...
...
```
