### ISSUE TITLE
regex istio VirtualService

### ISSUE THREAD

**Issue by calvinShan** [istio/istio#33114]
Hello,
I want to route the traffic to the service through istio gateway, I need to use regex during the traffic.

It works well by using ingress like this
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
   - host: {{ .Values.tls.host }}
     http:
      paths:
      - path: /route(/|$)(.*)
        backend:
          serviceName: {{ .Values.rules.apitest.serviceName }}
          servicePort: {{ .Values.rules.apitest.servicePort }}
```

I have tried to realize the traffic with the configuration file belows, but it does **not** work
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: xxx-app
spec:
  hosts:
  - "*"
  gateways:
  - app-gateway
  http:
  - match:
    - uri:
        prefix: route
    rewrite:
      uri: /
    route:
    - destination:
        host: xxx.thebase.svc.cluster.local
        port:
          number: 80
```

How could I change the virtualservice to do this regex traffic please, something like this?

```
  - match:
    - uri:
        prefix: route(/|$)(.*)
    rewrite:
      uri: /$2
```

Thansk
