### ISSUE TITLE
destination rule split trafficPolicy can not work 

### ISSUE THREAD

**Issue by woshihaoren** [istio/istio#33147]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
This can work
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: reviews
spec:
  host: reviews
  subsets:
  - labels:
      version: v1
    name: v1
  - labels:
      version: v2
    name: v2
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
```
```
#istioctl x describe pod reviews-v1-545db77b95-pg2hs 
Pod: reviews-v1-545db77b95-pg2hs
   Pod Ports: 9080 (reviews), 15090 (istio-proxy)
--------------------
Service: reviews
   Port: http 9080/HTTP targets pod port 9080
DestinationRule: reviews for "reviews"
   Matching subsets: v1
      (Non-matching subsets v2,v3)
   load balancer
VirtualService: reviews
   1 HTTP route(s)
```
this can not work
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: reviews
spec:
  host: reviews
  subsets:
  - labels:
      version: v1
    name: v1
  - labels:
      version: v2
    name: v2
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: reviews-policy
spec:
  host: reviews
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
```
```
#istioctl x describe pod reviews-v1-545db77b95-pg2hs 
Pod: reviews-v1-545db77b95-pg2hs
   Pod Ports: 9080 (reviews), 15090 (istio-proxy)
--------------------
Service: reviews
   Port: http 9080/HTTP targets pod port 9080
DestinationRule: reviews for "reviews"
   Matching subsets: v1
      (Non-matching subsets v2,v3)
   No Traffic Policy
VirtualService: reviews
   1 HTTP route(s)

```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
split still work,because doc say,
```
A DestinationRule can also be fragmented with similar merge semantics and restrictions.

There should only be one definition of any given subset across multiple destination rules for the same host. If there is more than one with the same name, the first definition is used and any following duplicates are discarded. No merging of subset content is supported.
There should only be one top-level trafficPolicy for the same host. When top-level traffic policies are defined in multiple destination rules, the first one processed will be used. Any following top-level trafficPolicy configuration is discarded.
Unlike virtual service merging, destination rule merging works in both sidecars and gateways.
```
**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
#istioctl version --remote
client version: 1.9.2
control plane version: 1.9.2
data plane version: 1.9.2 (8 proxies)
#kubectl version --short
Client Version: v1.20.5
Server Version: v1.20.5

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
