### ISSUE TITLE
Using istio-operator to install istio is missing exposed ports

### ISSUE THREAD

**Issue by clarechu** [istio/istio#33176]
**Bug description**

in istio 1.6.0, I didn't set externalIps when I created the IOP resource,The exposed port is missing.

exmaple

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: example
  namespace: istio-system
spec:
  addonComponents:
    istiocoredns:
      enabled: true
    kiali:
      enabled: false
    prometheus:
      enabled: false
  components:
    egressGateways:
    - enabled: false
      name: istio-egressgateway
    ingressGateways:
    - enabled: true
      k8s:
        env:
        - name: ISTIO_META_ROUTER_MODE
          value: sni-dnat
        hpaSpec:
          maxReplicas: 5
          metrics:
          - resource:
              name: cpu
              targetAverageUtilization: 80
            type: Resource
          minReplicas: 1
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: istio-ingressgateway
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        service:
          ports:
          - name: status-port
            port: 15021
            targetPort: 15021
          - name: http2
            port: 8080
            targetPort: 8080
          - name: https
            port: 443
            targetPort: 8443
          - name: tls
            port: 15443
            targetPort: 15443
          - name: promethues
            port: 9090
            targetPort: 9090
          
```

```bash
$ kubectl get svc -n istio-system 
NAME                   TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                                                                                                                   AGE
istio-egressgateway    ClusterIP      10.70.212.178   <none>        80/TCP,443/TCP,15443/TCP                                                                                                  302d
istio-ingressgateway   LoadBalancer   10.70.205.52    <pending>     15021:39956/TCP,80:23210/TCP,443:23646/TCP,15443:21506/TCP,15011:37732/TCP,15012:26105/TCP,8060:39474/TCP,853:39087/TCP   9m33s
istiocoredns           ClusterIP      10.70.253.194   <none>        53/UDP,53/TCP                                                                                                             302d
istiod                 NodePort       10.70.139.166   <none>        15010:24427/TCP,15012:22815/TCP,443:26632/TCP,15014:26313/TCP,53:23965/UDP,853:39326/TCP                                  302d
kiali                  ClusterIP      10.70.202.128   <none>        20001/TCP                                                                                                                 302d
prometheus             NodePort       10.70.39.152    <none>        9090:31865/TCP                                                                                                            32d
tracing                ClusterIP      10.70.165.231   <none>        80/TCP                                                                                                                    143d
zipkin                 ClusterIP      10.70.186.7     <none>        9411/TCP                                                                                                                  143d
```

missing 9090 prometheus exposed port, If I set externalips, it will appear.

```yaml
    ingressGateways:
    - enabled: true
      k8s:
        env:
        - name: ISTIO_META_ROUTER_MODE
          value: sni-dnat
        hpaSpec:
          maxReplicas: 5
          metrics:
          - resource:
              name: cpu
              targetAverageUtilization: 80
            type: Resource
          minReplicas: 1
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: istio-ingressgateway
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        service:
          externalIPs:
          - xxx.xx.xx.xx
```

```bash
➜  ~ k get svc
NAME                   TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                                                                                                                                                                                                                 AGE
istio-egressgateway    ClusterIP      10.70.212.178   <none>        80/TCP,443/TCP,15443/TCP                                                                                                                                                                                                302d
istio-ingressgateway   LoadBalancer   10.70.205.52    xxx.xxx.x.x   15021:35504/TCP,8080:36199/TCP,443:31567/TCP,15443:24602/TCP,9090:32558/TCP  
istiocoredns           ClusterIP      10.70.253.194   <none>        53/UDP,53/TCP                                                                                                                                                                                                           302d
istiod                 NodePort       10.70.139.166   <none>        15010:24427/TCP,15012:22815/TCP,443:26632/TCP,15014:26313/TCP,53:23965/UDP,853:39326/TCP                                                                                                                                302d
kiali                  ClusterIP      10.70.202.128   <none>        20001/TCP                                                                                                                                                                                                               302d
prometheus             NodePort       10.70.39.152    <none>        9090:31865/TCP                                                                                                                                                                                                          32d
tracing                ClusterIP      10.70.165.231   <none>        80/TCP                                                                                                                                                                                                                  143d
zipkin                 ClusterIP      10.70.186.7     <none>        9411/TCP                                                                                                                                                                                                                143d

```


[ ] Docs
[ X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade


* install steps

```bash
$ istioctl operator init 

$ kubectl apply -f iop.yaml 

```
