### ISSUE TITLE
Upgrade to 1.10.0 breaks VirtualService redirection

### ISSUE THREAD

**Issue by adamkgray** [istio/istio#33189]
**Bug description**

Upgrading from 1.9.x to 1.10.0 breaks domain redirection in some virtual services

I am using 2 other frameworks, namely knative and kfserving

Ingressgateway:
```
knative-ingressgateway   ClusterIP      172.20.91.109    <none>        15021/TCP,80/TCP,443/TCP

spec:
  ports:
  - name: status-port
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: http2
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: istio-ingressgateway
    istio: knative-ingressgateway
  sessionAffinity: None
  type: ClusterIP
```

Gateway
```
spec:
  selector:
    istio: knative-localgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
```

VirtualService
```
spec:
  gateways:
  - knative-serving/knative-local-gateway
  hosts:
  - sklearn.models.svc.cluster.local
  http:
  - match:
    - authority:
        regex: ^sklearn\.models(\.svc(\.cluster\.local)?)?(?::\d{1,5})?$
      gateways:
      - knative-serving/knative-local-gateway
    route:
    - destination:
        host: knative-localgateway.istio-system.svc.cluster.local
        port:
          number: 80
      headers:
        request:
          set:
            Host: sklearn-predictor-default.models.svc.cluster.local
      weight: 100
```

The top level domain is a Service of type ExternalName with no port specified:
```
sklearn                                   ExternalName   <none>          knative-localgateway.istio-system.svc.cluster.local   <none>          
```

When I hit this top level domain in v1.9.x, istio redirects the top level domain to the new host correctly. The logs for the ingressgateway look like this when it works:
```
2021-05-31T07:53:57.046Z] "GET / HTTP/2" 404 - via_upstream - "-" 0 22 4 3 "10.10.94.140,10.10.48.216" "curl/7.64.0" "212a17bb-45ef-47a7-a74f-9d46073a8878" "sklearn-predictor-default.models.svc.cluster.local" "10.10.92.99:8012" outbound|80||sklearn-predictor-default-00002.models.svc.cluster.local 10.10.48.216:42708 10.10.48.216:8080 10.10.48.216:57876 - -
```

However in v1.10.0 it gets stuck in some infinite loop (logs truncated).
```
"GET / HTTP/2" 0 - http2.remote_reset - "-" 0 0 4 - "10.10.92.99,10.10.56.174,10.10.56.174,10.10.56.174,10.10.56.174,10.10.56.174,10.10.56.174,10.10.56.174, ... 10.10.56.174,10.10.56.174,10.10.56.174,10.10.56.174,10.10.56.174,10.10.56.174,10.10.56.174,10.10.56.174,10.10.56.174,10.10.56.174,10.10.56.174" "curl/7.64.0" "191b3e1e-e2e9-4ae9-900f-fb1a463c8a8a" "sklearn.models.svc.cluster.local" "10.10.56.174:8080" outbound|80||knative-localgateway.istio-system.svc.cluster.local 10.10.56.174:40622 10.10.56.174:8080 10.10.56.174:40624 - -
```

This bug does _not_ affect the other knative services. So the bug is unique to services of type external name with no port specified.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

Users should be able to call an ingressgateway, and the VirtualServices + Gateways applied to that gateway should correctly handle the redirection to the downstream service

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

istioctl generate manifest, istioctl apply -f

**Environment where the bug was observed (cloud vendor, OS, etc)**

EKS

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
