### ISSUE TITLE
AWS NLB aws-load-balancer-nlb-target-type annotation doesn't work

### ISSUE THREAD

**Issue by keyboardfann** [istio/istio#33197]
**Bug description**
![image](https://user-images.githubusercontent.com/1110451/120272819-3e61ed00-c2e0-11eb-9daa-06b1d5f8cf88.png)
I use AWS EKS and create Istio Internal Ingress ( NLB ), when two pods in the same EC2 want to communicate through Internal Ingress, the connection will hang and timeout.

From https://aws.amazon.com/tw/premiumsupport/knowledge-center/target-connection-fails-load-balancer/ , it's because src ip and dst ip are the same and ELB doesn't support loop. The Resolution from AWS is change to use IP target type.

From https://docs.aws.amazon.com/zh_tw/eks/latest/userguide/network-load-balancing.html#network-load-balancing-service-sample-manifest , AWS support service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip annotataion

But when I add service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip to istio config and re-create the internal ingress gateway, the target group still use instance target group, not ip target group.
![image](https://user-images.githubusercontent.com/1110451/120275728-576c9d00-c2e4-11eb-93ba-7189c2e92901.png)

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ X ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
Add service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip to istio ingress should use ip target group, not instance ip target group
Pod1 can access Pod2 through Internal NLB

**Steps to reproduce the bug**
1. Deploy istio components using config
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  hub: docker.io/istio
  tag: 1.9.1
  revision: 1-9-1
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
  components:
    egressGateways:
    - name: istio-egressgateway
      enabled: true
    ingressGateways:
    - name: internal-istio-ingressgateway
      enabled: true
      k8s:
        env:
           - name: ISTIO_META_ROUTER_MODE
             value: sni-dnat
        hpaSpec:
          maxReplicas: 5
          metrics:
            - resource:
                name: cpu
                targetAverageUtilization: 80
              type: Resource
          minReplicas: 1
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: internal-istio-ingressgateway
        overlays:
          - kind: HorizontalPodAutoscaler
            name: internal-istio-ingressgateway
            patches:
              - path: metadata.labels.app
                value: internal-istio-ingressgateway
              - path: metadata.labels.istio
                value: internal-ingressgateway
              - path: spec.scaleTargetRef.name
                value: internal-istio-ingressgateway
          - kind: HorizontalPodAutoscaler
            name: internal-istio-ingressgateway
            patches:
              - path: metadata.labels.app
                value: internal-istio-ingressgateway
              - path: metadata.labels.istio
                value: internal-ingressgateway
              - path: spec.scaleTargetRef.name
                value: internal-istio-ingressgateway
          - kind: Deployment
            name: internal-istio-ingressgateway
            patches:
              - path: metadata.labels.app
                value: internal-istio-ingressgateway
              - path: metadata.labels.istio
                value: internal-ingressgateway
              - path: spec.selector.matchLabels.app
                value: internal-istio-ingressgateway
              - path: spec.selector.matchLabels.istio
                value: internal-ingressgateway
              - path: spec.template.metadata.labels.app
                value: internal-istio-ingressgateway
              - path: spec.template.metadata.labels.istio
                value: internal-ingressgateway
          - kind: Service
            name: internal-istio-ingressgateway
            patches:
              - path: metadata.labels.app
                value: internal-istio-ingressgateway
              - path: metadata.labels.istio
                value: internal-ingressgateway
              - path: spec.selector.app
                value: internal-istio-ingressgateway
              - path: spec.selector.istio
                value: internal-ingressgateway
              - path: spec.type
                value: LoadBalancer
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        service:
          externalTrafficPolicy: Local
          ports:
            - name: http2
              port: 80
              protocol: TCP
              targetPort: 8080
            - name: https
              port: 443
              protocol: TCP
              targetPort: 8443
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
          service.beta.kubernetes.io/aws-load-balancer-internal: "true"
          service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
        strategy:
          rollingUpdate:
            maxSurge: 100%
            maxUnavailable: 25%

```

2. Check AWS NLB target, still use instance target group , not ip target group

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
client version: 1.9.1
control plane version: 1.9.1
data plane version: 1.9.1 (31 proxies)

**How was Istio installed?**
```
istioctl install -f istio-config.yaml
```

**Environment where the bug was observed (cloud vendor, OS, etc)**
EKS1.19 , Internal NLB

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
I am not sure there is anything we, the Istio project, can do here. We are adding the `service.beta.kubernetes.io/aws-load-balancer-nlb-target-type` annotation to the Service as expected. if AWS doesn't do the right thing with that annotation... that is an EKS problem?

Let me know if I misunderstood. Thanks!

**Comment by keyboardfann** [comment]
Thanks @howardjohn, Maybe it's about EKS issue, I will verify and reply later.

**Comment by keyboardfann** [comment]
Have checked the issue, it needs to install the required component and change the annotation.

https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/service/nlb/
```
Prerequisites¶
AWS LoadBalancer Controller >= v2.2.0
Kubernetes >= v1.16 for Service type NodePort
Kubernetes >= v1.20 or EKS >= 1.16 or the following patch releases for Service type LoadBalancer
1.18.18+ for 1.18
1.19.10+ for 1.19
```
istio ingress config
```
    - name: internal-istio-ingressgateway
      enabled: true
      k8s:
        env:
           - name: ISTIO_META_ROUTER_MODE
             value: sni-dnat
        hpaSpec:
          maxReplicas: 5
          metrics:
            - resource:
                name: cpu
                targetAverageUtilization: 80
              type: Resource
          minReplicas: 1
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: internal-istio-ingressgateway
        overlays:
          - kind: HorizontalPodAutoscaler
            name: internal-istio-ingressgateway
            patches:
              - path: metadata.labels.app
                value: internal-istio-ingressgateway
              - path: metadata.labels.istio
                value: internal-ingressgateway
              - path: spec.scaleTargetRef.name
                value: internal-istio-ingressgateway
          - kind: HorizontalPodAutoscaler
            name: internal-istio-ingressgateway
            patches:
              - path: metadata.labels.app
                value: internal-istio-ingressgateway
              - path: metadata.labels.istio
                value: internal-ingressgateway
              - path: spec.scaleTargetRef.name
                value: internal-istio-ingressgateway
          - kind: Deployment
            name: internal-istio-ingressgateway
            patches:
              - path: metadata.labels.app
                value: internal-istio-ingressgateway
              - path: metadata.labels.istio
                value: internal-ingressgateway
              - path: spec.selector.matchLabels.app
                value: internal-istio-ingressgateway
              - path: spec.selector.matchLabels.istio
                value: internal-ingressgateway
              - path: spec.template.metadata.labels.app
                value: internal-istio-ingressgateway
              - path: spec.template.metadata.labels.istio
                value: internal-ingressgateway
          - kind: Service
            name: internal-istio-ingressgateway
            patches:
              - path: metadata.labels.app
                value: internal-istio-ingressgateway
              - path: metadata.labels.istio
                value: internal-ingressgateway
              - path: spec.selector.app
                value: internal-istio-ingressgateway
              - path: spec.selector.istio
                value: internal-ingressgateway
              - path: spec.type
                value: LoadBalancer
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        service:
          externalTrafficPolicy: Local
          ports:
            - name: http2
              port: 80
              protocol: TCP
              targetPort: 8080
            - name: https
              port: 443
              protocol: TCP
              targetPort: 8443
            ## Custom port ##
            - name: internalsystem-use
              port: 9999
              protocol: TCP
            - name: internalsystem-use-https
              port: 10000
              protocol: TCP
            - name: fortest
              port: 15012
              protocol: TCP
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-name: "internalistioingress"
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-type: "external"
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
          service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Name=InternalIstioIngress,Project=Infra,Department=SRE"       
          service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
          service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
        strategy:
          rollingUpdate:
            maxSurge: 100%
            maxUnavailable: 25%
```
