### ISSUE TITLE
istio Gateway ignores SSL certificate updates

### ISSUE THREAD

**Issue by calvinShan** [istio/istio#33198]
hello,

I have created the secret to hold the certificat of istio gateway
kubectl create secret tls istio-ingressgateway-certs --cert xxx.crt --key xxx.key
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: app-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    - "*"
```

ANd i want to use a new certificat, so I recreate the secret
kubectl delete secret tls istio-ingressgateway-certs --certxxx.crt --key xxx.key
kubectl create secret tls istio-ingressgateway-certs --certxxx.crt --key xxx.key

However, the certificat does not update without restarting istiogateway pod.

I read the doc https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/, which can specify the certificat to use by CURL.
But we want to refresh the certificat from chrome, so how to update the certificat directly from browser please?
Https://xxxxx/test, we could update certificat directly 

Thanks
