### ISSUE TITLE
503 between services deployed on a VM even with authentication disabled

### ISSUE THREAD

**Issue by ferrarimarco** [istio/istio#33207]
**Bug description**

I've deployed Bookinfo on a VM, and it works fine. As soon as I install Istio in a GKE cluster, and I install Istio on the VM, the service-to-service communication breaks, with 503 errors such as this one, from curl running in a Pod in the GKE cluster, and from the Istio logs on the VM:

```
$ curl -v productpage.default.svc.cluster.local:9080
* Rebuilt URL to: productpage.default.svc.cluster.local:9080/
*   Trying 240.240.0.8...
* TCP_NODELAY set
* Connected to productpage.default.svc.cluster.local (240.240.0.8) port 9080 (#0)
> GET / HTTP/1.1
> Host: productpage.default.svc.cluster.local:9080
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 503 Service Unavailable
< content-length: 190
< content-type: text/plain
< date: Mon, 31 May 2021 20:18:30 GMT
< server: envoy
<
* Connection #0 to host productpage.default.svc.cluster.local left intact
upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
```

```
[2021-05-31T20:18:30.595Z] "GET / HTTP/1.1" 503 UF,URX upstream_reset_before_response_started{connection_failure,TLS_error:_268435703:SSL_routines:OPENSSL_internal:WRONG_VERSION_NUMBER} - "TLS error: 268435703:SSL 
```

This is true for all the services of the bookinfo app deployed on the VM, regardless of accessing them directly, or if exposed via an Istio gateway running in the GKE cluster. I can still access the services from localhost on the VM directly:

```
$ curl -v localhost:9083
* Rebuilt URL to: localhost:9083/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9083 (#0)
> GET / HTTP/1.1
> Host: localhost:9083
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 200 OK
< content-type: text/html; charset=utf-8
< content-length: 1683
< server: envoy
< date: Mon, 31 May 2021 20:57:23 GMT
< x-envoy-upstream-service-time: 3
<
<!DOCTYPE html>
<html>
....
```

If I stop istio on the VM (systemctl stop istio), I can access the services again from the VM public IP.

If I disable the peer authentication and mTLS (see below to reproduce), I'm able to access the services with curl, but the services cannot communicate with each other:

```
DEBUG:urllib3.connectionpool:http://reviews:9080 "GET /reviews/0 HTTP/1.1" 503 91
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): reviews:9080
send: b'GET /reviews/0 HTTP/1.1\r\nHost: reviews:9080\r\nuser-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nX-B3-TraceId: 6ef28298d8a3b8f4\r\nX-B3-SpanId: 6ef28298d8a3b8f4\r\nX-B3-Sampled: 1\r\n\r\n'
reply: 'HTTP/1.1 503 Service Unavailable\r\n'
header: content-length: 91
header: content-type: text/plain
header: date: Tue, 01 Jun 2021 14:31:40 GMT
header: server: istio-envoy
header: x-envoy-decorator-operation: :0/*
DEBUG:urllib3.connectionpool:http://reviews:9080 "GET /reviews/0 HTTP/1.1" 503 91
```

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

1. Istio should take care of configuring authenticatiion between services, without the need to explicitly disable it.
2. Istio should allow plaintext communications, but this was not the case. I had to disable authentication entirely (`PERMISSIVE` was not enough).
3. Istio should allow service-to-service communication in the above scenarios.

**Steps to reproduce the bug**

(for info, I also attached the output of `istioctl bug-report`

1. Provision a GCE VM, and open the 9080-9084 TCP port ranges in the firewall.
2. Deploy bookinfo with docker compose on the GCE VM: `docker-compose -f bookinfo.yaml up -d`

`bookinfo.yaml`

```yaml
---
version: '3'
services:
  details:
    image: istio/examples-bookinfo-details-v1:1.16.2
    expose:
      - "9080"
    ports:
      - "9082:9080"
  productpage:
    image: istio/examples-bookinfo-productpage-v1:1.16.2
    expose:
      - "9080"
    ports:
      - "9083:9080"
  ratings:
    image: istio/examples-bookinfo-ratings-v1:1.16.2
    expose:
      - "9080"
    ports:
      - "9081:9080"
  reviews:
    image: istio/examples-bookinfo-reviews-v3:1.16.2
    expose:
      - "9080"
    ports:
      - "9084:9080"
...
```

3. Verify that it works if you try to load productpage from the external IP
4. Provision a GKE cluster.
5. Install Istio (see below) in the GKE cluster and in the GCE VM
6. Deploy a Gateway

```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: default-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
...
```

7. Deploy the following WorkloadEntries (add the public IP of the GCE VM first):

```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: productpage
spec:
  address: # PUBLIC IP OF THE GCE VM
  labels:
    app: productpage
    instance-id: source-environment-vm
  serviceAccount: bookinfo-gce
...
---
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: details
spec:
  address: # PUBLIC IP OF THE GCE VM
  labels:
    app: details
    instance-id: source-environment-vm
  serviceAccount: bookinfo-gce
...
---
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: ratings
spec:
  address: # PUBLIC IP OF THE GCE VM
  labels:
    app: ratings
    instance-id: source-environment-vm
  serviceAccount: bookinfo-gce
...
---
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: reviews
spec:
  address: # PUBLIC IP OF THE GCE VM
  labels:
    app: reviews
    instance-id: source-environment-vm
  serviceAccount: bookinfo-gce
...
```

8. Deploy the following ServiceEntries:

```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: productpage
spec:
  hosts:
    - productpage
    - productpage.default.svc.cluster.local
  location: MESH_INTERNAL
  ports:
    - number: 9080
      name: http
      protocol: HTTP
      targetPort: 9083
  resolution: STATIC
  workloadSelector:
    labels:
      app: productpage
...
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: details
spec:
  hosts:
    - details
    - details.default.svc.cluster.local
  location: MESH_INTERNAL
  ports:
    - number: 9080
      name: http
      protocol: HTTP
      targetPort: 9082
  resolution: STATIC
  workloadSelector:
    labels:
      app: details
...
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: ratings
spec:
  hosts:
    - ratings
    - ratings.default.svc.cluster.local
  location: MESH_INTERNAL
  ports:
    - number: 9080
      name: http
      protocol: HTTP
      targetPort: 9081
  resolution: STATIC
  workloadSelector:
    labels:
      app: ratings
...
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: reviews
spec:
  hosts:
    - reviews
    - reviews.default.svc.cluster.local
  location: MESH_INTERNAL
  ports:
    - number: 9080
      name: http
      protocol: HTTP
      targetPort: 9084
  resolution: STATIC
  workloadSelector:
    labels:
      app: reviews
...
```

9. Deploy the following VirtualServices:

```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: productpage
spec:
  hosts:
    - "*"
  gateways:
    - istio-system/default-gateway
  http:
    - match:
        - uri:
            exact: /productpage
        - uri:
            exact: /login
        - uri:
            exact: /logout
        - uri:
            prefix: /api/v1/products
        - uri:
            prefix: /static
      route:
        - destination:
            host: productpage.default.svc.cluster.local
...
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: details
spec:
  hosts:
    - details
  http:
    - route:
      - destination:
          host: details.default.svc.cluster.local
...
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ratings
spec:
  hosts:
    - ratings
  http:
    - route:
      - destination:
          host: ratings.default.svc.cluster.local
...
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
    - reviews
  http:
    - route:
      - destination:
          host: reviews.default.svc.cluster.local
...
```

10. To disable peer authentication and mTLS:

```yaml
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: default
spec:
  mtls:
    mode: DISABLE
...
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: productpage-short
spec:
  host: productpage
  trafficPolicy:
    tls:
      mode: DISABLE
...
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: details-short
spec:
  host: details
  trafficPolicy:
    tls:
      mode: DISABLE
...
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ratings-short
spec:
  host: ratings
  trafficPolicy:
    tls:
      mode: DISABLE
...
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews-short
spec:
  host: reviews
  trafficPolicy:
    tls:
      mode: DISABLE
...
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
client version: 1.10.0
control plane version: 1.10.0
data plane version: 1.10.0 (5 proxies)
```

```
Client Version: v1.21.1
Server Version: v1.20.6-gke.1000
```

**How was Istio installed?**

With `istioctl`

```yaml
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
spec:
  components:
    ingressGateways:
      - name: istio-eastwestgateway
        label:
          istio: eastwestgateway
          app: istio-eastwestgateway
        enabled: true
        k8s:
          env:
            # sni-dnat adds the clusters required for AUTO_PASSTHROUGH mode
            - name: ISTIO_META_ROUTER_MODE
              value: "sni-dnat"
          service:
            ports:
              - name: status-port
                port: 15021
                targetPort: 15021
              - name: tls
                port: 15443
                targetPort: 15443
              - name: tls-istiod
                port: 15012
                targetPort: 15012
              - name: tls-webhook
                port: 15017
                targetPort: 15017
  meshConfig:
    defaultConfig:
      proxyMetadata:
        # Enable basic DNS proxying
        ISTIO_META_DNS_CAPTURE: "true"
        # Enable automatic address allocation
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: "Kubernetes"
      network: ""
...
```

On the VM, I installed Istio by following [Istio VM setup](https://istio.io/latest/docs/setup/install/virtual-machine/) and the following `workload-group.yaml` and `VM_NAMESPACE=default`:

```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadGroup
metadata:
  name: bookinfo
  namespace: default
spec:
  metadata:
    labels:
      app: bookinfo
  template:
    serviceAccount: bookinfo-gce
    network: ""
...
```

**Environment where the bug was observed (cloud vendor, OS, etc)**

Google Kubernetes Engine, Google Compute Engine

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

DONE

[bug-report.tar.gz](https://github.com/istio/istio/files/6580234/bug-report.tar.gz)
