### ISSUE TITLE
Host header not rewritten on HTTPRoute

### ISSUE THREAD

**Issue by theofpa** [istio/istio#33226]
**Bug description**
Trying to set the host header in v1.10 using a header request fails to create the virtualservice.

Related issues:
* kubeflow/kfserving#1643
* #31844

Example:
```
  http:
  - match:
    - authority:
        regex: ^torchserve-transformer\.default(\.svc(\.cluster\.local)?)?(?::\d{1,5})?$
      gateways:
      - knative-local-gateway.knative-serving
    - authority:
        regex: ^torchserve-transformer\.default\.example\.com(?::\d{1,5})?$
      gateways:
      - knative-ingress-gateway.knative-serving
    route:
    - destination:
        host: knative-local-gateway.istio-system.svc.cluster.local
        port:
          number: 80
      headers:
        request:
          set:
            Host: torchserve-transformer-transformer-default.default.svc.cluster.local
```
returns:
```
2021-06-02T10:52:54.536044Z	info	validationServer	configuration is invalid: invalid header "Host": cannot set Host header
```

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
The virtualservice should be created. In Istio 1.9 it works. We are not necessary injecting the proxy in kfserving.

**Steps to reproduce the bug**

**Versions**

* istio control plane version: 1.10.0
* istio data plane version: 1.10.0 (1 proxies)
* kubernetes version: v1.19.11

**How was Istio installed?**
via istio-operator

**Environment where the bug was observed (cloud vendor, OS, etc)**
using kind

/cc @howardjohn
