### ISSUE TITLE
istio Gateway ignores SSL certificate updates

### ISSUE THREAD

**Issue by calvinShan** [istio/istio#33228]
hello,

I have created the secret to hold the certificat of istio gateway
kubectl create secret tls istio-ingressgateway-certs --cert xxx.crt --key xxx.key

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: thebasetestapi-app
spec:
  hosts:
  - "*"
  gateways:
  - app-gateway
  http:
  - match:
    - uri:
        prefix: /
    rewrite:
      uri: /
    route:
    - destination:
        host: thebasetestapi.thebase.svc.cluster.local
        port:
          number: 80
---
# voting-app-gateway.yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: app-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: istio-ingressgateway-certs
    hosts:
    - "*"
```
ANd i want to use a new certificat, so I recreate the secret
kubectl delete secret tls istio-ingressgateway-certs --certxxx.crt --key xxx.key
kubectl create secret tls istio-ingressgateway-certs --certxxx.crt --key xxx.key

However, the certificat does not update without restarting istiogateway pod.

I read the doc https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/, which can specify the certificat to use by CURL.
But we want to refresh the certificat from chrome, so how to update the certificat directly from browser please?
Https://xxxxx/test, we could update certificat directly

Thanks

**Comment by irisdingbj** [comment]
The secret name should not begin with istio or prometheus, and the secret should not contain a token field as described in https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/

**Comment by calvinShan** [comment]
> The secret name should not begin with istio or prometheus, and the secret should not contain a token field as described in https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/

I have recreated the secret like this: kubectl.exe create secret tls ingressgateway  -n istio-system --key=aksappsvc-istio-dev-01.key --cert=aksappsvc-istio-dev-01.crt

It does not work

My current version is 1.7.3, to use credentialName, is it ok  to use 1.7.3? Thanks
istioctl.exe version
client version: 1.10.0-rc.1
control plane version: 1.7.3
data plane version: 1.7.3 (2 proxies)

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: app-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: sauringressgateway
    hosts:
```
