### ISSUE TITLE
Issues when generating the mesh configuration to add VMs to the mesh

### ISSUE THREAD

**Issue by ferrarimarco** [istio/istio#33225]
**Bug description**

The generated configuration to add VMs to the mesh has the following issues:

1. There's no protocol being passed when building the `ISTIO_META_POD_PORTS` in `cluster.env` and in `mesh.yaml`. I suppose that for `cluster.env` this is due to the [workloadEntryToPodPortsMeta](https://github.com/istio/istio/blob/master/istioctl/cmd/workload.go#L525) not populating the protocol. Wasn't able to trace the issue for `mesh`.
2. The `ISTIO_META_POD_PORTS` is passed as a string, while it should be a JSON object. Related issue: https://github.com/istio/istio/issues/32894

Because of point 2 above, if you try to start Istio on the VM with the generated config, you get the following error:

```
Failed to extract node metadata: json: cannot unmarshal string into Go struct field BootstrapNodeMetadata2.POD_PORTS of type []model.PodPort
```

Example (cluster.env):

```
CANONICAL_REVISION='latest'
CANONICAL_SERVICE='reviews'
ISTIO_INBOUND_PORTS='9080'
ISTIO_LOCAL_EXCLUDE_PORTS='15090,15021'
ISTIO_METAJSON_LABELS='{"app":"reviews","app.kubernetes.io/name":"reviews","service.istio.io/canonical-name":"reviews","service.istio.io/canonical-version":"latest"}'
ISTIO_META_CLUSTER_ID='Kubernetes'
ISTIO_META_DNS_AUTO_ALLOCATE='true'
ISTIO_META_DNS_CAPTURE='true'
ISTIO_META_MESH_ID='mesh1'
ISTIO_META_NETWORK=''
ISTIO_META_POD_PORTS='"[{\"name\":\"http\",\"containerPort\":9080,\"protocol\":\"\"}]"'
ISTIO_META_WORKLOAD_NAME='reviews'
ISTIO_NAMESPACE='default'
ISTIO_SERVICE='reviews.default'
ISTIO_SERVICE_CIDR='*'
POD_NAMESPACE='default'
SERVICE_ACCOUNT='bookinfo-gce'
TRUST_DOMAIN='cluster.local'
```

Example (mesh.yaml):

```yaml
defaultConfig:
  discoveryAddress: istiod.istio-system.svc:15012
  meshId: mesh1
  proxyMetadata:
    CANONICAL_REVISION: latest
    CANONICAL_SERVICE: productpage
    ISTIO_META_CLUSTER_ID: Kubernetes
    ISTIO_META_DNS_AUTO_ALLOCATE: "true"
    ISTIO_META_DNS_CAPTURE: "true"
    ISTIO_META_MESH_ID: mesh1
    ISTIO_META_NETWORK: ""
    ISTIO_META_POD_PORTS: '[{"name":"http","containerPort":9080,"protocol":""}]'
    ISTIO_META_WORKLOAD_NAME: productpage
    ISTIO_METAJSON_LABELS: '{"app":"productpage","app.kubernetes.io/name":"productpage","service.istio.io/canonical-name":"productpage","service.istio.io/canonical-version":"latest"}'
    POD_NAMESPACE: default
    SERVICE_ACCOUNT: bookinfo-gce
    TRUST_DOMAIN: cluster.local
  readinessProbe:
    failureThreshold: 3
    httpGet:
      path: /
      port: 9080
      scheme: HTTP
    initialDelaySeconds: 5
    periodSeconds: 4
    successThreshold: 3
    timeoutSeconds: 3
  tracing:
    zipkin:
      address: zipkin.istio-system:9411
```

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[x] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

1. The protocol field should be populated in both `cluster.env` and `mesh.yaml`.
2. The `ISTIO_META_POD_PORTS` should be a JSON object, rather than a string, in both `cluster.env` and `mesh.yaml`.

**Steps to reproduce the bug**

1. Download istioctl
2. Generate the mesh configuration with the following WorkloadGroup: `istioctl x workload entry configure -f workload-group.yaml -o /tmp/config --clusterID "Kubernetes"`

```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadGroup
metadata:
  name: productpage
  namespace: default
spec:
  metadata:
    labels:
      app: productpage
      app.kubernetes.io/name: productpage
  probe:
    initialDelaySeconds: 5
    timeoutSeconds: 3
    periodSeconds: 4
    successThreshold: 3
    failureThreshold: 3
    httpGet:
     path: /
     port: 9080
     scheme: HTTP
  template:
    network: ""
    ports:
      http: 9080
    serviceAccount: bookinfo-gce
...
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
client version: 1.10.0
control plane version: 1.10.0
data plane version: 1.10.0 (5 proxies)
```

```
Client Version: v1.21.1
Server Version: v1.20.6-gke.1000
```

**How was Istio installed?**

With `istioctl`

```yaml
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
spec:
  components:
    ingressGateways:
      - name: istio-eastwestgateway
        label:
          istio: eastwestgateway
          app: istio-eastwestgateway
        enabled: true
        k8s:
          env:
            # sni-dnat adds the clusters required for AUTO_PASSTHROUGH mode
            - name: ISTIO_META_ROUTER_MODE
              value: "sni-dnat"
          service:
            ports:
              - name: status-port
                port: 15021
                targetPort: 15021
              - name: tls
                port: 15443
                targetPort: 15443
              - name: tls-istiod
                port: 15012
                targetPort: 15012
              - name: tls-webhook
                port: 15017
                targetPort: 15017
  meshConfig:
    defaultConfig:
      proxyMetadata:
        # Enable basic DNS proxying
        ISTIO_META_DNS_CAPTURE: "true"
        # Enable automatic address allocation
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: "Kubernetes"
      network: ""
...
```

**Environment where the bug was observed (cloud vendor, OS, etc)**

Google Kubernetes Engine, Google Compute Engine

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
