### ISSUE TITLE
VirtualService routing on pre-ext-auth headers

### ISSUE THREAD

**Issue by ddseapy** [istio/istio#33220]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Previously if using the following for setting/replacing headers, the header set by the adapter was used in any routing decisions in virtualservices:
https://github.com/istio/istio/wiki/Route-directive-adapter-development-guide for authorization

With the external auth (https://istio.io/latest/docs/tasks/security/authorization/authz-custom/), a virtualservice matches headers from the original request, not the one set by the external authorizer.

Since the external authorizer is setting/replacing those headers, it seems like the routing should be based on the new header values and not ones that a user could pass through.

**Steps to reproduce the bug**
Install the operator with spec->meshConfig->extensionProviders having a envoyExtAuthzGrpc service/port
Headers should be returned,which looks like this (headers is non-empty []*corev3.HeaderValueOption):
```golang
return &authv3.CheckResponse{
	HttpResponse: &authv3.CheckResponse_OkResponse{
		OkResponse: &authv3.OkHttpResponse{
			Headers: headers,
		},
	},
	Status: &status.Status{Code: int32(rpc.OK)},
}, nil
```
Deploying httpbin, I can see the headers being set (or replaced if the client sets them) if just using a `uri`.  However if adding `headers` it only matches if i set `my-auths` header in the request from the client.
```yaml
- uri:
    prefix: /anything
  headers:
    my-auths:
      regex: ".*"
```

If this is intended, it might be good to document on https://istio.io/latest/docs/tasks/security/authorization/authz-custom/ since I suspect anyone using an external authorizer would want any routing to be based on the headers it sets, especially since those headers are likely to be used for authorization decisions.  Using pre-authorized (unsanitized) headers, could result in a security issue if someone isn't aware.  Also, if it is intended, is there a way to route on the headers that the workload (in this case httpbin) will receive?

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

kubernetes version:
Client Version: v1.21.1
Server Version: v1.21.1

istio version is 1.10.0

**How was Istio installed?**
istio operator

**Environment where the bug was observed (cloud vendor, OS, etc)**
on-prem centos 7
Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
cc @yangminzhu

**Comment by ddseapy** [comment]
@yangminzhu I forgot to mention, but the AuthorizationPolicy is on the ingress gateway:
```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ext-authz
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  action: CUSTOM
  provider:
    name: ccri-ext-authz-grpc
  rules:
  - {}
```
If you know where generally in the istio/envoy code I can look at, that would also be helpful.  As I understand it the ordering is:
ingress-gateway -> external auth -> ingress-gateway -> httpbin (& other apps with similar virtual services)

Any references to code that might relate to supporting the routing decision being made after the external auth request comes back to the ingress-gateway based on the new headers would be super helpful.  I'm happy poke at it if that is a change makes sense.

Thanks!

**Comment by ddseapy** [comment]
I think envoy's `clear_route_cache` setting is what I'm after.  Will see if I can set that with an EnvoyFilter on the ingress-gateway pod.

**Comment by ddseapy** [comment]
filter looks like it does the right thing to the envoy config, but routing is still using the request's headers (httpbin still showing the correct headers that come from ext auth, not the request).  haven't quite figured out why the routing is using the request headers, maybe more of an envoy question at this point.  hoping if we can find an EnvoyFilter that works, then contributing an istio change to support headers based on ext auth without an EnvoyFilter shouldn't be too difficult.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ds-ingress-envoyfilter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
    patch:
      operation: MERGE
      value:
        name: envoy.filters.http.ext_authz
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
          clear_route_cache: true
```
```json
...
             {
              "name": "envoy.filters.http.ext_authz",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz",
               "grpc_service": {
                "envoy_grpc": {
                 "cluster_name": "outbound|9000||istioauth-ds-auths-istio-plugin.istio-system.svc.cluster.local",
                 "authority": "outbound_.9000_._.istioauth-ds-auths-istio-plugin.istio-system.svc.cluster.local"
                },
                "timeout": "600s"
               },
               "clear_route_cache": true,
               "transport_api_version": "V3",
               "filter_enabled_metadata": {
                "filter": "envoy.filters.http.rbac",
                "path": [
                 {
                  "key": "istio_ext_authz_shadow_effective_policy_id"
                 }
                ],
                "value": {
                 "string_match": {
                  "prefix": "istio-ext-authz"
                 }
                }
               }
              }
             },
...
```
