### ISSUE TITLE
Gateway injection spins up tons of pods

### ISSUE THREAD

**Issue by linsun** [istio/istio#33237]
**Bug description**

I set up my istio 1-8-3 using some cmds like below:

```
kubectl apply -f istiod-service.yaml
istioctl install -y -n istio-system -f control-plane.yaml --revision 1-8-3
istioctl install -y -n istio-ingress -f ingress-gateways.yaml --revision 1-8-3
```

```
cat ingress-gateways.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-ingress-gw-install
spec:
  profile: empty
  values:
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: false
  components:
    ingressGateways:
    - name: istio-ingressgateway
      namespace: istio-ingress
      enabled: true
      k8s:
        overlays:
        - apiVersion: apps/v1
          kind: Deployment
          name: istio-ingressgateway
          patches:
          - path: spec.template.spec.containers[name:istio-proxy].lifecycle
            value:
               preStop:
                 exec:
                   command: ["sh", "-c", "sleep 5"]

cat istiod-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: istiod
    istio: pilot
    release: istio
  name: istiod
  namespace: istio-system
spec:
  type: ClusterIP
  ports:
  - name: grpc-xds
    port: 15010
  - name: https-dns
    port: 15012
  - name: https-webhook
    port: 443
    targetPort: 15017
  - name: http-monitoring
    port: 15014
  selector:
    app: istiod

cat control-plane.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: control-plane
spec:
  profile: minimal
  meshConfig:
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
    enablePrometheusMerge: true
```
Then I install istiod 1-10-0, then used gw injection to deploy canary of the gw.

```
istioctl install -y -n istio-system --revision 1-10-0 -f control-plane.yaml
istioctl x revision tag set canary --revision 1-10-0
# copy cm of istio-1-8-3 and istio-1-10-0 to istio-ingress namespace
kubectl apply -f ../ingress-gateway-injection-canary-image.yaml -n istio-ingress
# this ^^ doesn't create many pods, only 1 pod, failed to reach running.

kubectl label namespace istio-ingress istio.io/rev=canary --overwrite
kubectl apply -f ../ingress-gateway-injection-canary.yaml -n istio-ingress
# this ^^ creates many pods many are able to reach running, many are pending before I kill them all.
```

```
cat ingress-gateway-injection-canary-image.yaml                          (8d0h42m) 16:24:45
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-ingressgateway-canary
  namespace: istio-ingress
spec:
  selector:
    matchLabels:
      istio: ingressgateway
      istio.io/rev: canary
  template:
    metadata:
      annotations:
        # Enable gateway injection
        inject.istio.io/templates: gateway
      labels:
        # Set a unique label for the gateway. This is required to ensure Gateways
        # can select this workload
        istio: ingressgateway
        # Enable gateway injection. If connecting to a revisioned control plane, replace with
        istio.io/rev: canary
        # sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: istio-proxy
        image: docker.io/istio/proxyv2:1.10.0 # The image will automatically update each time the pod starts.
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "5"]

cat ingress-gateway-injection-canary.yaml                                (8d0h42m) 16:25:02
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-ingressgateway-canary
  namespace: istio-ingress
spec:
  selector:
    matchLabels:
      istio: ingressgateway
      istio.io/rev: canary
  template:
    metadata:
      annotations:
        # Enable gateway injection
        inject.istio.io/templates: gateway
      labels:
        # Set a unique label for the gateway. This is required to ensure Gateways
        # can select this workload
        istio: ingressgateway
        # Enable gateway injection. If connecting to a revisioned control plane, replace with
        istio.io/rev: canary
        # sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: istio-proxy
        image: auto # The image will automatically update each time the pod starts.
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "5"]
```

[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade
