### ISSUE TITLE
Customise the text returned when a request is routed into fault/abort

### ISSUE THREAD

**Issue by drmaciej** [istio/istio#33249]
**Describe the feature request**
Currently, when a request is routed into a fault, a generic `fault filter abort` is returned. It would be good to customise this message. This can be seen for a `VirtualService` like:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-vs-external
spec:
  hosts:
    - example.com
  gateways:
    - gateway-external
  http:
    # reject requests to /hidden
    - match:
      - uri:
          prefix: /hidden
      fault:
        abort:
          percentage:
            value: 100
          httpStatus: 418
      route:
      - destination:
          host: none
    # catch-all route
    - route:
      - destination:
          port:
            number: 8888
          host: my-service
```          

**Describe alternatives you've considered**
I've looked at ways to route requests to all paths, but /hidden using `regex`, but it looks like Re2 doesn't allow for an expression like 'does not start with /hidden'.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
