### ISSUE TITLE
ServiceEntry with a single host and multiple IPs generates pilot_duplicate_envoy_clusters error.

### ISSUE THREAD

**Issue by michalgcc** [istio/istio#33259]
**Bug description**

Deploying a ServiceEntry containing a single host and multiple IPs results in a pilot_duplicate_envoy_clusters error.
It generates multiple clusters with the same name which is reported as pilot_duplicate_envoy_clusters [here](https://github.com/istio/istio/blob/1.9.2/pilot/pkg/networking/core/v1alpha3/cluster.go#L137).

The log and metric is pushed in [normalizeCluster ](https://github.com/istio/istio/blob/1.9.2/pilot/pkg/networking/core/v1alpha3/cluster.go#L130) function.

Prometheus:
```
pilot_duplicate_envoy_clusters{app="istiod", container="discovery", endpoint="http-monitoring", instance="10.x.x.x:x", job="pilot", namespace="istio-system", pod="istiod-xx", service="istiod"} 1 
```

Istiod:
```
"pilot_duplicate_envoy_clusters": {
    "outbound|1433||test.database.windows.net": {
        "proxy": "microservice",
        "message": "Duplicate cluster outbound|1433||test.database.windows.net found while pushing CDS"
    }
}
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Do not generate pilot_duplicate_envoy_clusters log and metric for a ServiceEntry with single host and multiple IPs.

**Steps to reproduce the bug**

Deploy a ServiceEntry containing a single host and multiple IPs:
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: mssql-tcp-external
  namespace: istio-system
spec:
  hosts:
  - test.database.windows.net
  addresses:
  - 20.45.121.1/32
  - 20.49.88.1/32
  ports:
  - number: 1433
    name: tcp
    protocol: TCP
  location: MESH_EXTERNAL
```

**Version**:
```
> istioctl version --remote
client version: 1.10.0
control plane version: 1.9.2
data plane version: 1.9.2 (x proxies)

> kubectl version --short
Client Version: v1.21.1
Server Version: v1.20.5
```

**How was Istio installed?**
Using `istioctl`.

**Environment where the bug was observed (cloud vendor, OS, etc)**
Azure Kubernetes Service. Kubernetes version: 1.20.5.
