### ISSUE TITLE
[1.10.0][multi-cluster] endpoint not discovered correctly when gateways are specified in meshConfig

### ISSUE THREAD

**Issue by samene** [istio/istio#33256]
Istio multi-cluster 'multi-primary on different networks' not working when ```gateways``` are configured. This **used to work in 1.9.1** so must be a regression.

Snippet of IstioOperator spec from 1st cluster. Not including the 2nd one.

```
  values:
    global:
      meshID: cluster.local
      meshNetworks:
        my-network1:
          endpoints:
          - fromRegistry: myapp-cluster1
          gateways:
          - address: 192.168.199.6
            port: 31391
        my-network2:
          endpoints:
          - fromRegistry: myapp-cluster2
          gateways:
          - address: 192.168.199.8
            port: 31391
      multiCluster:
        clusterName: myapp-cluster1
      network: my-network1
```

We have a jenkins pipeline which runs the helloworld-sleep tests on an installation and it has failed since upgrding istio to 1.10.0 from 1.9.1.

in 1.9.1 istioctl proxy-config endpoint would give the right IP address for the remote service

```
$ istioctl proxy-config endpoint sleep-557747455f-6vhdc -n sample | grep hello
10.42.70.160:5000                HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
192.168.199.8:31391              HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
```

But with 1.10.0 it returns the pod IP address of remote service and not the gateway.

```
$ istioctl proxy-config endpoint sleep-557747455f-6vhdc -n sample | grep hello
10.42.70.160:5000                HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
10.52.34.127:5000                HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
```

This works when we have a loadbalancer and 
```
`- registryServiceName: istio-ingressgateway.istio-system.svc.cluster.local`
```
is configured.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

Istio 1.10.0
Kubernetes 1.20.2

**How was Istio installed?**

Istio Operator

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
