### ISSUE TITLE
Delegate virtualservice without specified namespace is invalid

### ISSUE THREAD

**Issue by fatedier** [istio/istio#33251]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: example-delegate
  namespace: default
spec:
  http:
  - route:
    - destination:
        host: productpage
        port:
          number: 9080
---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: example
  namespace: default
spec:
  hosts:
  - "example"
  http:
  - delegate:
      name: example-delegate
```

This VirtualService is invalid and no rules pushed to envoy if deletegate's namespace is empty.

Then it's valid after i specified delegate namespace to default.

But from this document: https://istio.io/latest/docs/reference/config/networking/virtual-service/#Delegate

> Namespace specifies the namespace where the delegate VirtualService resides. By default, it is same to the root’s.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
client version: 1.9.4
control plane version: 1.9.4
data plane version: 1.9.4 (5 proxies)

I update istiod to 1.10 and the problem also happens.

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
