### ISSUE TITLE
Update /etc/istio/ingressgateway-certs/tls.crt istio

### ISSUE THREAD

**Issue by calvinShan** [istio/istio#33260]
Hello, 

I have create the secret 
kubectl create -n istio-system secret tls istio-ingressgateway-certs --key=xxx.key --cert=xxx.crt

The gateway works. Now we want to implement a new certificat, I have recreated the secret
kubectl delete -n istio-system secret istio-ingressgateway-certs 
kubectl create -n istio-system secret tls istio-ingressgateway-certs --key=xx2.key --cert=xx2.crt

And I restarted the pod ingress gateway(by deleting the pod), but the certificat is never updated

 kubectl exec -it -n istio-system $(kubectl -n istio-system get pods -l istio=ingressgateway -o jsonpath='{.items[0].metadata.name}') -- cat /etc/istio/ingressgateway-certs/tls.crt 
It is always the last crt, and we can't remove it, so how can I **update** the file /etc/istio/ingressgateway-certs/tls.crt please?

TE-----
kubectl exec -it -n istio-system $(kubectl -n istio-system get pods -l istio=ingressgateway -o jsonpath='{.items[0].metadata.name}') -- rm /etc/istio/ingressgateway-certs/tls.crt
rm: cannot remove '/etc/istio/ingressgateway-certs/tls.crt': Read-only file system

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: app-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
```
