### ISSUE TITLE
[1.10.0] Istio / Grafana don't capture data from services

### ISSUE THREAD

**Issue by lhmoraes** [istio/istio#33261]
After install Kubernetes 1.21 and Istio 1.10.0 (profile demo) without Helm, I deploy a single service in a default namespace, but in mesh dashboard of Grafana (Istio Service Dashboard) I can’t see any register for the services.

Below my K8s configuration to deploy my Spring Boot Application:

```
#
# Deployment Configuration
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-lab
  labels:
    app: kubernetes-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-lab
  template:
    metadata:
      labels:
        app: kubernetes-lab
        version: 1.0.RELEASE
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: docker-registry-credentials
      containers:
      - name: kubernetes-lab
        image: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        imagePullPolicy: Always
        volumeMounts:
          - name: kubernetes-lab-data
            mountPath: "/var"
        resources:
          requests:
            memory: "900Mi"
            cpu: "0.5"
          limits:
            memory: "900Mi"
        ports:
          - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SERVER_PORT
          value: "8080"
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 10
      volumes:
        - name: kubernetes-lab-data
          persistentVolumeClaim:
            claimName: pvc-nfs-api-claim
---

#
# Service Configuration
#
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-lab
  labels:
    app: kubernetes-lab
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: kubernetes-lab

---

#
# Horizontal Pod Autoscaler
#
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: kubernetes-lab
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kubernetes-lab
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 90
  - type: Resource
    resource:
      name: memory
      targetAverageValue: 900Mi

---

#
# Service Monitor
#
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-prometheus-kubernetes-lab-service-monitor
  labels:
    app: kubernetes-lab
    release: prometheus
spec:
  selector:
    matchLabels:
      app: kubernetes-lab
  endpoints:
    - port: http-traffic
      path: "/actuator/prometheus"
```

**Bug description**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Using Grafana and the Istio / Istio Service Dashboard the **kubernetes-lab** application should be displayed on the **service** drop-down box and the metrics being displayed on the General Panel.

**Steps to reproduce the bug**
Deploy a Spring Boot application using the K8s configuration above.
Spring Boot: 2.4.3
Kotlin: 1.4.30
Spring Cloud: 2020.0.1
Spring-Cloud-Starter-Kubernetes-Client-Config
Spring-Cloud-Kubernetes-Fabric8-Istio

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
~]# istioctl version --remote
client version: 1.10.0
control plane version: 1.10.0
data plane version: 1.10.0 (10 proxies)

~]# kubectl version --short
Client Version: v1.21.1
Server Version: v1.21.1

~]#  helm version --short
bash: helm: command not found
*** Not using Helm

**How was Istio installed?**
~]# istioctl install --set profile=demo

**Environment where the bug was observed (cloud vendor, OS, etc)**
Linux Centos OS 7.0
Kubernetes 1.21

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
[bug-report.tar.gz](https://github.com/istio/istio/files/6592021/bug-report.tar.gz)
