### ISSUE TITLE
Traffic to a WorkloadEntry doesn't take the version label into consideration when reporting metrics to Prometheus

### ISSUE THREAD

**Issue by ferrarimarco** [istio/istio#33299]
**Bug description**

I deployed a bookinfo instance on Compute Engine VMs and in a GKE cluster. After configuring mesh expansion with `WorkloadEntries` and ServiceEntries that select both the VM workloads and the Pods running in GKE, I see that Prometheus reports traffic directed to the VM workloads as the `latest` version, instead of taking into account what I specified in the WorkloadEntry.

Here's an example WorkloadEntry:

```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: details
spec:
  address: [IP_OF_THE_VM]
  labels:
    app: details
    instance-id: source-environment-vm
    version: compute-engine
  serviceAccount: bookinfo-gce
...

```

`latest` version:

```
istio_requests_total{app="productpage", connection_security_policy="unknown", destination_app="details", destination_canonical_revision="latest", destination_canonical_service="details", destination_cluster="Kubernetes", destination_principal="spiffe://cluster.local/ns/default/sa/bookinfo-gce", destination_service="details", destination_service_name="details", destination_service_namespace="default", destination_version="unknown", destination_workload="details", destination_workload_namespace="default", instance="192.168.3.9:15020", istio_io_rev="default", job="kubernetes-pods", kubernetes_namespace="default", kubernetes_pod_name="productpage-v1-6b746f74dc-lwrrv", pod_template_hash="6b746f74dc", reporter="source", request_protocol="http", response_code="200", response_flags="-", security_istio_io_tlsMode="istio", service_istio_io_canonical_name="productpage", service_istio_io_canonical_revision="v1", source_app="productpage", source_canonical_revision="v1", source_canonical_service="productpage", source_cluster="Kubernetes", source_principal="spiffe://cluster.local/ns/default/sa/bookinfo-productpage", source_version="v1", source_workload="productpage-v1", source_workload_namespace="default", version="v1"}
```

`v1` version:

```
istio_requests_total{app="productpage", connection_security_policy="unknown", destination_app="details", destination_canonical_revision="v1", destination_canonical_service="details", destination_cluster="Kubernetes", destination_principal="spiffe://cluster.local/ns/default/sa/bookinfo-details", destination_service="details", destination_service_name="details", destination_service_namespace="default", destination_version="v1", destination_workload="details-v1", destination_workload_namespace="default", instance="192.168.3.9:15020", istio_io_rev="default", job="kubernetes-pods", kubernetes_namespace="default", kubernetes_pod_name="productpage-v1-6b746f74dc-lwrrv", pod_template_hash="6b746f74dc", reporter="source", request_protocol="http", response_code="200", response_flags="-", security_istio_io_tlsMode="istio", service_istio_io_canonical_name="productpage", service_istio_io_canonical_revision="v1", source_app="productpage", source_canonical_revision="v1", source_canonical_service="productpage", source_cluster="Kubernetes", source_principal="spiffe://cluster.local/ns/default/sa/bookinfo-productpage", source_version="v1", source_workload="productpage-v1", source_workload_namespace="default", version="v1"}
```

As you can see, in the VM case (first output), `destination_version` (and the related revision information) is reported as `"unknown"`

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Istio should correctly report the version information as the WorkloadEntry configured.

**Steps to reproduce the bug**

1. Deploy Bookinfo in a VM and in a GKE cluster.
2. Run the following Prometheus query:

```
istio_requests_total{reporter="source", destination_service_name="details"}
```

3. Inspect the results and note that the revision for traffic to the VM instances is not reporting the correct revision.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

client version: 1.10.0
control plane version: 1.10.0
data plane version: 1.10.0 (5 proxies)
Client Version: v1.21.1
Server Version: v1.20.6-gke.1000

**How was Istio installed?**

With istioctl and the following configuration:

```yaml
With istioctl

---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
spec:
  components:
    ingressGateways:
      - name: istio-eastwestgateway
        label:
          istio: eastwestgateway
          app: istio-eastwestgateway
        enabled: true
        k8s:
          env:
            # sni-dnat adds the clusters required for AUTO_PASSTHROUGH mode
            - name: ISTIO_META_ROUTER_MODE
              value: "sni-dnat"
          service:
            ports:
              - name: status-port
                port: 15021
                targetPort: 15021
              - name: tls
                port: 15443
                targetPort: 15443
              - name: tls-istiod
                port: 15012
                targetPort: 15012
              - name: tls-webhook
                port: 15017
                targetPort: 15017
  meshConfig:
    defaultConfig:
      proxyMetadata:
        # Enable basic DNS proxying
        ISTIO_META_DNS_CAPTURE: "true"
        # Enable automatic address allocation
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: "Kubernetes"
      network: ""
...
```

**Environment where the bug was observed (cloud vendor, OS, etc)**

Compute Engine, Kubernetes Engine

**Comment by ferrarimarco** [comment]
Discovered after reporting https://github.com/kiali/kiali/issues/4071

**Comment by howardjohn** [comment]
cc @douglas-reid I am not sure the full path for this, I assume its supposed to end up in some node metadata that we are missing?

**Comment by douglas-reid** [comment]
@howardjohn yes.

@ferrarimarco how did you set up your VMs?  Did you use `istioctl x workload entry configure` or similar?  It should generate the correct configuration artifacts to put on the VM..

**Comment by ferrarimarco** [comment]
Yes, I used that method. See the details in these other issues I posted: https://github.com/istio/istio/issues/33225 https://github.com/istio/istio/issues/33207 (unrelated to this one, I think)

Thanks!

**Comment by douglas-reid** [comment]
Skimming those quickly, i didn't see anything that confirms the issue. Did you have a `WorkloadGroup` resource that provided the template for that configuration?  Was it labelled properly?  What does your `mesh.yaml` file look like on the VM?

**Comment by douglas-reid** [comment]
@ferrarimarco i looked closer. i think the issue is that you attempted to label the `WorkloadEntry` after the fact. Try labels on the `WorkloadGroup` (either in the metadata or in the template spec) before generation.

**Comment by ferrarimarco** [comment]
@douglas-reid good pointers. After fixing my WorkloadGroup (and WorkloadEntries), here's what I have (example for the `productpage` instance deployed in the VM):

WorkloadGroup:

```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadGroup
metadata:
  name: productpage
  namespace: default
spec:
  metadata:
    labels:
      app: productpage
      app.kubernetes.io/instance: productpage-compute-engine
      app.kubernetes.io/name: productpage
      app.kubernetes.io/version: compute-engine
      instance-id: source-environment-productpage
      version: compute-engine
  probe:
    initialDelaySeconds: 5
    timeoutSeconds: 3
    periodSeconds: 4
    successThreshold: 3
    failureThreshold: 3
    httpGet:
     path: /
     port: 9080
     scheme: HTTP
  template:
    labels:
      app: productpage
      app.kubernetes.io/instance: productpage-compute-engine
      app.kubernetes.io/name: productpage
      app.kubernetes.io/version: compute-engine
      instance-id: source-environment-productpage
      version: compute-engine
    network: ""
    ports:
      http: 9080
    serviceAccount: bookinfo-gce
...
```

Results in:

```yaml
defaultConfig:
  discoveryAddress: istiod.istio-system.svc:15012
  meshId: mesh1
  proxyMetadata:
    CANONICAL_REVISION: compute-engine
    CANONICAL_SERVICE: productpage
    ISTIO_META_CLUSTER_ID: Kubernetes
    ISTIO_META_DNS_AUTO_ALLOCATE: "true"
    ISTIO_META_DNS_CAPTURE: "true"
    ISTIO_META_MESH_ID: mesh1
    ISTIO_META_NETWORK: ""
    ISTIO_META_POD_PORTS: '[{"name":"http","containerPort":9080,"protocol":""}]'
    ISTIO_META_WORKLOAD_NAME: productpage
    ISTIO_METAJSON_LABELS: '{"app":"productpage","app.kubernetes.io/instance":"productpage-compute-engine","app.kubernetes.io/name":"productpage","app.kubernetes.io/version":"compute-engine","instance-id":"source-environment-productpage","service.istio.io/canonical-name":"productpage","service.istio.io/canonical-version":"compute-engine","version":"compute-engine"}'
    POD_NAMESPACE: default
    SERVICE_ACCOUNT: bookinfo-gce
    TRUST_DOMAIN: cluster.local
  readinessProbe:
    failureThreshold: 3
    httpGet:
      path: /
      port: 9080
      scheme: HTTP
    initialDelaySeconds: 5
    periodSeconds: 4
    successThreshold: 3
    timeoutSeconds: 3
  tracing:
    zipkin:
      address: zipkin.istio-system:9411
```

And here's the WorkloadEntry I deployed in the cluster:

```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: productpage
spec:
  address: 35.222.227.100
  labels:
    app: productpage
    app.kubernetes.io/instance: productpage-compute-engine
    app.kubernetes.io/name: productpage
    app.kubernetes.io/version: compute-engine
    instance-id: source-environment-productpage
    version: compute-engine
  serviceAccount: bookinfo-gce
...
```

It works now! I supposed that adding that information to the workload entry was enough.

Closing!
