### ISSUE TITLE
Gateway-API's Gateway does not work when it points to the "second" k8s service

### ISSUE THREAD

**Issue by nak3** [istio/istio#33298]
**Bug description**

- K8S Gateway does not work when it points to the "second" k8s service. (Pleases see the reproduce steps below for what is the second service.)

[X] Networking

**Expected behavior**

- K8S Gateway works with the "second " k8s service.

**Steps to reproduce the bug**

#### 1. install gateway-api, istio and sleep client pod

```
kubectl apply -k 'github.com/kubernetes-sigs/gateway-api/config/crd?ref=v0.3.0'
istioctl install -y
kubectl apply -f samples/sleep/sleep.yaml
```

#### 2. Deploy a second with `istio: ingressgateway` selector

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: knative-local-gateway
  namespace: istio-system
spec:
  type: ClusterIP
  selector:
    istio: ingressgateway
  ports:
    - name: http2
      port: 80
      targetPort: 8081
EOF
```

Now, the service and endpoint like this:

```
$ kubectl get svc -n istio-system  -o wide
NAME                    TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                                      AGE   SELECTOR
istio-ingressgateway    NodePort    10.96.150.167   <none>        15021:31634/TCP,80:30081/TCP,443:30267/TCP   13m   app=istio-ingressgateway,istio=ingressgateway
istiod                  ClusterIP   10.96.201.250   <none>        15010/TCP,15012/TCP,443/TCP,15014/TCP        14m   app=istiod,istio=pilot
knative-local-gateway   ClusterIP   10.96.145.203   <none>        80/TCP                                       12m   istio=ingressgateway

$ kubectl get ep -n istio-system 
NAME                    ENDPOINTS                                                        AGE
istio-ingressgateway    10.244.1.4:15021,10.244.1.4:8080,10.244.1.4:8443                 11m
istiod                  10.244.1.5:15012,10.244.1.5:15010,10.244.1.5:15017 + 1 more...   12m
knative-local-gateway   10.244.1.4:8081                                                  10m
```

(I updated istio-ingressgateway svc to NodePort, but it should not be matter.)

#### 3. Create Gateway to use `knative-local-gateway.istio-system`

```
cat <<EOF | kubectl apply -f -
apiVersion: networking.x-k8s.io/v1alpha1
kind: GatewayClass
metadata:
  name: istio
spec:
  controller: istio.io/gateway-controller
---
kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: test-local-gateway
  namespace: knative-serving
spec:
  gatewayClassName: istio
  addresses:
  - type: NamedAddress
    value: knative-local-gateway.istio-system.svc.cluster.local
  listeners:
  - protocol: HTTP
    port: 8081
    routes:
      kind: HTTPRoute
      namespaces:
        from: "All"
EOF
```

The status looks fine.

```
$ kubectl get gateway -n knative-serving -o yaml
 
  status:
    conditions:
    - lastTransitionTime: "2021-06-07T12:34:15Z"
      message: Resources available
      observedGeneration: 2
      reason: ResourcesAvailable
      status: "True"
      type: Scheduled
    - lastTransitionTime: "2021-06-07T12:34:15Z"
      message: Listeners valid, assigned to service(s) knative-local-gateway.istio-system.svc.cluster.local
      observedGeneration: 2
      reason: ListenersValid
      status: "True"
      type: Ready
    listeners:
    - conditions:
      - lastTransitionTime: "2021-06-07T12:34:15Z"
        message: No error found
        observedGeneration: 2
        reason: ListenerReady
        status: "True"
        type: Ready
      port: 8081
      protocol: HTTP
```

#### 4. Access to the test gateway

It gets `Connection refused`.

```
$ kubectl exec -it sleep-557747455f-vjvst sh
/ $ curl  10.96.145.203 
curl: (7) Failed to connect to 10.96.145.203 port 80: Connection refused
```

Even if any HTTPRoute created, the service returns `Connection refused`. So I omit the steps to create HTTPRoute.

#### (Side Note) For the purposes of comparison, create Istio Gateway.

```
cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: knative-local-gateway
  namespace: knative-serving
  labels:
    serving.knative.dev/release: devel
    networking.knative.dev/ingress-provider: istio
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 8081
        name: http
        protocol: HTTP
      hosts:
        - "*"
EOF
```

It gets `404 Not Found` so Ingress Gateway allows me to access to the knative-local-gateway svc.

```
/ $ curl  10.96.145.203
  ...
< HTTP/1.1 404 Not Found
```

We would like to create the same Istio Gateway by k8s Gateway, but it seems not work with any configuration.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
$ istioctl version --remote
client version: 1.11-alpha.0f317e2a34ebd17cd2dbdc2ab6410a84a060ba73
control plane version: 1.11-alpha.0f317e2a34ebd17cd2dbdc2ab6410a84a060ba73
data plane version: 1.11-alpha.0f317e2a34ebd17cd2dbdc2ab6410a84a060ba73 (1 proxies)
```

**Comment by howardjohn** [comment]
```
kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: test-local-gateway
  namespace: istio-system
spec:
  gatewayClassName: istio
  addresses:
  - type: NamedAddress
    value: knative-local-gateway.istio-system.svc.cluster.local
  listeners:
  - protocol: HTTP
    port: 80
    routes:
      kind: HTTPRoute
      namespaces:
        from: "All"
```

Is the correct config. Note the changed port number and the namespace. It will technically work in knative-serving for now, but I will fix that - its a bug.

I will try to send a PR to make the status more clear
