### ISSUE TITLE
ElastiCache Redis Cluster access breaks when using TLS?

### ISSUE THREAD

**Issue by diranged** [istio/istio#33337]
**Bug description**

This bug is related to https://github.com/istio/istio/issues/33336 - but not the same. On the heels of us debugging https://github.com/istio/istio/issues/33336, we thought that perhaps we needed to use TLS mode so that Envoy might be able to report some metrics. Also, TLS is good - right? So we thought we would convert our ElastiCache cluster to use encryption for all traffic, and then configure our environment to have Envoy handle the TLS for us.

As we mention in #33336, we need to have Envoy do the backend redirection for us (`enable_redirection: true`) so that our clients can be dumb and simple, letting Envoy handle all of the "MOVED" calls for example. Just as a reminder, this configuration below _works_:

_Working Configuration to Non-TLS Endpoint_:
```yaml
---
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: test
spec:
  workloadSelector:
    labels:
      run: debug-diranged
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY
  egress:
    - bind: 127.0.0.1
      captureMode: NONE
      port:
        number: 6379
        protocol: REDIS
        name: redis 
      hosts:
        - ./*
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: redis-proxy
spec:
  resolution: DNS
  hosts:
    - benchmark.....clustercfg.usw2.cache.amazonaws.com
  endpoints:
    - address: benchmark.....clustercfg.usw2.cache.amazonaws.com
      ports:
        redis: 6379
  exportTo: [.]
  location: MESH_EXTERNAL
  ports:
    - number: 6379
      name: redis
      protocol: REDIS
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: redis-proxy
spec:
  host: benchmark.....clustercfg.usw2.cache.amazonaws.com
  exportTo: [.]
  trafficPolicy:
    connectionPool:
      tcp:
        connectTimeout: 500ms
        tcpKeepalive:
          time: 300s
          interval: 60s
          time: 300s
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: redis-proxy
spec:
  workloadSelector:
    labels:
      run: debug-diranged
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        listener:
          name: 127.0.0.1_6379
          filterChain:
            filter:
              name: envoy.filters.network.redis_proxy
      patch:
        operation: REPLACE
        value:
          name: envoy.filters.network.redis_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
            latencyInMicros: true
            stat_prefix: outbound|6379||benchmark.....clustercfg.usw2.cache.amazonaws.com
            prefix_routes:
              catch_all_route:
                cluster: outbound|6379||benchmark.....clustercfg.usw2.cache.amazonaws.com
            settings:
              op_timeout: 0.3s
              enable_redirection: true
              enable_command_stats: true
              read_policy: ANY

    - applyTo: CLUSTER
      match:
        context: SIDECAR_OUTBOUND
        cluster:
          port: 6379
          service: benchmark.....clustercfg.usw2.cache.amazonaws.com
      patch:
        operation: MERGE
        value:
          health_checks:
            - custom_health_check:
                name: envoy.health_checkers.redis
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.health_checkers.redis.v3.Redis
              timeout: 0.5s
              interval: 2s
              unhealthy_threshold: 2
              healthy_threshold: 1
```

```bash
root@debug-diranged:/data# redis-cli mget a b c d e f g
1) (nil)
2) (nil)
3) (nil)
4) (nil)
5) (nil)
6) (nil)
7) (nil)
root@debug-diranged:/data# 
```

Switching the configuration to use a TLS backend (with a modified `DestinationRoute`) causes the redirection to break:
```yaml
---
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: test
spec:
  workloadSelector:
    labels:
      run: debug-diranged
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY
  egress:
    - bind: 127.0.0.1
      captureMode: NONE
      port:
        number: 6379
        protocol: REDIS
        name: redis 
      hosts:
        - ./*
    - hosts:
        - '*/*' 

---

apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: redis-proxy
spec:
  resolution: DNS
  hosts:
    - clustercfg.benchmark-tls.....clustercfg.usw2.cache.amazonaws.com
   endpoints:
    - address: clustercfg.benchmark-tls.....clustercfg.usw2.cache.amazonaws.com
      ports:
        redis: 6379
  exportTo: [.]
  location: MESH_EXTERNAL
  ports:
    - number: 6379
      name: redis
      protocol: REDIS

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: redis-proxy
spec:
  host: clustercfg.benchmark-tls.....clustercfg.usw2.cache.amazonaws.com
  exportTo: [.]
  trafficPolicy:
    tls:
      mode: SIMPLE
      caCertificates: /etc/ssl/certs/ca-certificates.crt
    connectionPool:
      tcp:
        connectTimeout: 500ms
        tcpKeepalive:
          time: 300s
          interval: 60s
          time: 300s

---

apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: redis-proxy
spec:
  workloadSelector:
    labels:
      run: debug-diranged
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        listener:
          name: 127.0.0.1_6379
          filterChain:
            filter:
              name: envoy.filters.network.redis_proxy
      patch:
        operation: REPLACE
        value:
          name: envoy.filters.network.redis_proxy
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
            latencyInMicros: true
            stat_prefix: outbound|6379||clustercfg.benchmark-tls.....clustercfg.usw2.cache.amazonaws.com
            prefix_routes:
              catch_all_route:
                cluster: outbound|6379||clustercfg.benchmark-tls.....clustercfg.usw2.cache.amazonaws.com
            settings:
              op_timeout: 0.3s
              enable_redirection: true
              enable_command_stats: true
              read_policy: ANY

    - applyTo: CLUSTER
      match:
        context: SIDECAR_OUTBOUND
        cluster:
          port: 6379
          service: clustercfg.benchmark-tls.....clustercfg.usw2.cache.amazonaws.com
      patch:
        operation: MERGE
        value:
          health_checks:
            - custom_health_check:
                name: envoy.health_checkers.redis
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.health_checkers.redis.v3.Redis
              timeout: 0.5s
              interval: 2s
              unhealthy_threshold: 2
              healthy_threshold: 1
```

```bash
root@debug-diranged:/data# redis-cli mget a b c d e f g
1) (error) MOVED 15495 benchmarkt-tls-0003-001.benchmarkt-tls....usw2.cache.amazonaws.com:6379
2) (error) MOVED 3300 benchmarkt-tls-0001-001.benchmarkt-tls....usw2.cache.amazonaws.com:6379
3) (error) MOVED 7365 benchmarkt-tls-0002-001.benchmarkt-tls....usw2.cache.amazonaws.com:6379
4) (nil)
5) (nil)
6) (nil)
7) (error) MOVED 7233 benchmarkt-tls-0002-001.benchmarkt-tls....usw2.cache.amazonaws.com:6379
```

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

I am not expecting that just by switching to a TLS backed Redis cluster, the `enable_redirection: true` flag seems to no longer work or apply. I am not sure if I have a mistake in my configuration, or if this is a known issue.

**Steps to reproduce the bug**

Launch an ElastiCache cluster in AWS with a few Node Groups and Replicas and with Transit Encryption turned on.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```bash
$ istioctl version --remote
client version: 1.10.0
control plane version: 1.10.0
data plane version: 1.9.0 (2 proxies), 1.10.0 (10 proxies)
$ kubectl version --short
Client Version: v1.21.1
Server Version: v1.20.4-eks-6b7464
```

**How was Istio installed?**

Via the Istio Operator

**Environment where the bug was observed (cloud vendor, OS, etc)**

EKS on AWS
