### ISSUE TITLE
traffic mirroring does not work with short name

### ISSUE THREAD

**Issue by yingzhuivy** [istio/istio#33330]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
when using short name, wrong config is generated:

suppose `svc-a -> svc-b`, and we mirror traffic going to `svc-b` to `svc-c`

for example, virtual service definition:
```
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: svc-b
  namespace: ns-b
spec:
  hosts:
  - svc-b.ns-b.svc.cluster.local
  http:
  - route:
    - destination:
        host: svc-b.ns-b.svc.cluster.local
      weight: 100
    mirror:
      host: svc-c.ns-c
      port:
        number: 8080
    mirrorPercentage:
      value: 1
```
and check envoy config for svc-a:

```
request_mirror_policies: [
{
cluster: "outbound|8080||svc-c.ns-c",
runtime_fraction: {
default_value: {
numerator: 10000,
denominator: "MILLION"
}
},
trace_sampled: false
}
],
```

i would expect the cluster name to be `outbound|8080||svc-c.ns-c.svc.cluster.local` instead of  `outbound|8080||svc-c.ns-c`. after changing the virtual service mirror setting to use full name, mirroring works.
**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
described above
**Steps to reproduce the bug**
described above
**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.9
**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
