### ISSUE TITLE
Session stickiness does not work with weighted canary distribution

### ISSUE THREAD

**Issue by dibosh** [istio/istio#33343]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

For a setup like below-

```yaml
- route:
    - destination:
        host: beauty-service
        subset: live
      weight: 80
      
    - destination:
        host: beauty-service
        subset: canary
      weight: 20
```

The session stickiness does not work for weighted distribution. Some request that got initiated in live version ends up in canary, and vice-versa. Guessing the problem is because of [this](https://github.com/envoyproxy/envoy/issues/8167), but there was a new [PR](https://github.com/envoyproxy/envoy/pull/14875) on Envoy side which is supposed to solve the issue.

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
