### ISSUE TITLE
cannot configure zipkin address in `IstioOperator` on GKE

### ISSUE THREAD

**Issue by errordeveloper** [istio/istio#33353]
**Bug description**

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Having defined:

```yaml
apiVersion: install.istio.io/v1alpha1
...
spec:
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 60
        zipkin:
          address: jaeger-default-collector.observability:9411
...
```

It should result in `--zipkingAddress` argument of sidecars and relevant fields in `istio-sidecar-injector` configmap to be set to the given address, but it doesn't.

However, what does seem to do something is this:

```yaml
  values:
    global:
      tracer:
        zipkin:
          address: jaeger-default-collector.observability:9411
```

However, it only updates `istio-system:ConfigMap/istio-sidecar-injector-istio-1611`, which the `istio-sidecar-injector` pod doesn't mount, it only mounts `istio-system:ConfigMap/istio-sidecar-injector`.

**Steps to reproduce the bug**

1. deploy a GKE cluster 1.19.9-gke.1900 with Istio enabled
2. add `meshConfig.defaultConfig.tracing.zipkin.address=jaeger-default-collector.observability:9411` to `istio-system:IstioOperator/istio-1-6-11-gke-0`
3. check `kubectl get ConfigMap -n istio-system istio-sidecar-injector-istio-1611 -o json | jq  -r .data.values | jq .global.tracer.zipkin.address`, it will return empty string, but should be the desired address
4. add `values.global.tracer.zipkin.address=jaeger-default-collector.observability:9411` to `istio-system:IstioOperator/istio-1-6-11-gke-0`
5. check `kubectl get ConfigMap -n istio-system istio-sidecar-injector-istio-1611 -o json | jq  -r .data.values | jq .global.tracer.zipkin.address`  and it will have the desired address
6. recreate pods and check sidecar args, those should be set to empty string and not the desired address

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
client version: 1.10.0
control plane version: 1.6.14-gke.1-006dfdf1f9b4b4ab5877d4775988099cc7bd69fd
data plane version: 1.6.14-gke.1 (1 proxies)
```

**How was Istio installed?**

Using GKE, via the console.

**Environment where the bug was observed (cloud vendor, OS, etc)**

GKE.
