### ISSUE TITLE
FilterEnvoy only executes on SIDECAR_OUTBOUND despite ANY config

### ISSUE THREAD

**Issue by jessberg** [istio/istio#33358]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Given the below Envoy filter, I expect that the WASM filter should be executing on both inbound and outbound messages.  However, it only executes on outbound.  I know this because the WASM filter prints out whether there is an inbound/outbound request/response, and it only prints out request outbound and response outbound.

**Steps to reproduce the bug**
I used the following YAML on the BookInfo application running in Minikube.  I also replaced the ANY with SIDECAR_INBOUND on line 11, and it did execute the inbound code.  However, if I set it to ANY instead, only the outbound code is executed, when I expected both to be executed.

```
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ui-examplefilter
  namespace: default
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: ANY
        proxy:
          proxyVersion: '1\.9.*'
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.wasm
          config_discovery:
            config_source:
              ads: {}
              initial_fetch_timeout: 0s # wait indefinitely to prevent bad Wasm fetch
            type_urls: [ "type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm"]

---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ui-examplefilter-config
  namespace: default
spec:
  configPatches:
    - applyTo: EXTENSION_CONFIG
      match:
        context: ANY
      patch:
        operation: ADD
        value:
          name: envoy.filters.http.wasm
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
            value:
              config:
                # The configuration for the Wasm extension itself
                configuration:
                  '@type': type.googleapis.com/google.protobuf.StringValue
                  value: my-config
                root_id: bidi_root_id
                vm_config:
                  code:
                    remote:
                      http_uri:
                        uri: http://storage-upstream.storage.svc.cluster.local:8080/filter/filter.wasm
                      # Optional: specifying sha256 checksum will let istio agent verify the checksum of downloaded artifacts.
                      # It is **highly** recommended to provide the checksum, since missing checksum will cause the Wasm module to be downloaded repeatedly.
                      # To compute the sha256 checksum of a Wasm module, download the module and run `sha256sum` command with it.
                      sha256: 8e4f2018093af9c90ec8ac80d5c0d15599ff72b4df359d243ac7c9a85affce08
                  runtime: envoy.wasm.runtime.v8
                  vm_id: my-example
                  allow_precompiled: true
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Istio:
client version: 1.9.3
control plane version: 1.9.3
data plane version: 1.9.3 (9 proxies)

Kubectl:
Client Version: v1.21.1
Server Version: v1.20.2

**How was Istio installed?**
istioctl install --set profile=demo --set meshConfig.enableTracing=true

**Environment where the bug was observed (cloud vendor, OS, etc)**
Minikube run on Ubuntu 20.04.2

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
