### ISSUE TITLE
Istio Egress Gateway using secret from other namespace for mTLS request

### ISSUE THREAD

**Issue by nv1-0** [istio/istio#33368]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

We want to use istio egress gateway in a multi tenant way where each namespace will be having its own Egress Gateway created to connect with external endpoints. Now suppose if there is same external endpoint which can only be connected with mTLS is created  in both namespaces it needs a Destination Rule where a secret name is given in tls field of DR as shown below
```yaml
 tls:
   credentialName: secret-name
   mode: MUTUAL
```
Now in both namespaces the name of secret is name, lets set it secret-name.

So ideally if secret-name is created in one namespace, then only the requests originating from that namespace should be successful and the requests from other namespace where the secret is not created should fail.

But thats not happening. If i create secret in one namespace...its automatically sent to egress gateway of other namespace creating a kind of security breach since namespace resources should be isolated from each other.

So egress gateway of one namespace can use the secrets created only in its own namespace

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**
* Install istio with PILOT_SCOPE_GATEWAY_TO_NAMESPACE set to true.
* Set up egress gateways with different label selectors in two namespaces.
* Expose a mTLS endpoint in both namespaces by creating Service Entry, Virtual Service and Destination Rule.
* Destination rules should be like this
```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
spec:
  exportTo:
  - .
  host: <mtls-host>
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: <port>
      tls:
        credentialName: secret-name
        mode: MUTUAL
        sni: <mtls-host>
```
* Create secret secret-name needed by DR only in one namespace.
* Hit requests from both of the namespaces. The requests will work.

Ideally they shouldn't. Or if they are doing it right is there a way to restrict that.

There is one environment variable set in istiod i.e `ISTIOD_ENABLE_SDS_SERVER=false`. But that also didn't help

**Version** 
```bash
root@machine:~$ sudo istioctl version
client version: 1.9.5
control plane version: 1.9.5
data plane version: 1.9.5 (86 proxies)
```

**How was Istio installed?**
`
`istioctl install -f ~/istio-operator.yaml``

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS EKS 

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
Hey, thanks for the report. This is an (unfortunately fairly long standing) feature request that can be followed here https://github.com/istio/istio/issues/14598.

Thanks!

**Comment by nv1-0** [comment]
Hi, Thanks for the reply. I read the issue you shared. The issue looks more concerned towards fetching secret from other namespace whereas we want totally opposite of that i.e to deny access of secrets from other namespaces.

Does your work on that ticket also has some feature regarding that?

**Comment by nv1-0** [comment]
Hi,
To verify again...i exposed same dummy  mTLS endpoint example.com in two namespaces.
The content of the resources is as follows

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: test-cross-secret
spec:
  exportTo:
    - .
  hosts:
    - example.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
  resolution: DNS

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-cross-secret
spec:
  exportTo:
    - .
  gateways:
    - istio-egressgateway
    - mesh
  hosts:
    - example.com
  http:
    - match:
        - gateways:
            - mesh
          port: 80
      route:
        - destination:
            host: istio-egressgateway.psd2-2.svc.cluster.local #namespace changes here for egress gateway 
            port:
              number: 80
    - match:
        - gateways:
            - istio-egressgateway
          port: 80
      route:
        - destination:
            host: example.com
            port:
              number: 443

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: test-cross-secret
spec:
  exportTo:
    - .
  host: example.com
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
      - port:
          number: 443
        tls:
          credentialName: test-cross-secret
          mode: MUTUAL
          sni: example.com


```

I created secret only in one namespace
The output is as follows

![image](https://user-images.githubusercontent.com/11692785/121875712-6745a180-cd26-11eb-8d31-aae6540a9e77.png)

Then i run the istioctl pc s command for both of the gateways

Here is the output
```bash
root@machine:~$ sudo istioctl pc s istio-egressgateway-5d6c8bddbd-27n7w.psd2-1
RESOURCE NAME                                                 TYPE           STATUS     VALID CERT     SERIAL NUMBER                                        NOT AFTER                NOT BEFORE
kubernetes://test-cross-secret                                Cert Chain     ACTIVE     true           614601718806992197                                   2021-08-07T15:51:31Z     2018-08-07T15:51:31Z
kubernetes://test-cross-secret-cacert                         CA             ACTIVE     true           10944719598952040374951832963794454346               2031-11-10T00:00:00Z     2006-11-10T00:00:00Z
root@machine:~$ sudo istioctl pc s istio-egressgateway-5cc9954f98-dz5kt.psd2-2
RESOURCE NAME                                                 TYPE           STATUS     VALID CERT     SERIAL NUMBER                                        NOT AFTER                NOT BEFORE
kubernetes://test-cross-secret                                Cert Chain     ACTIVE     true           614601718806992197                                   2021-08-07T15:51:31Z     2018-08-07T15:51:31Z
kubernetes://test-cross-secret-cacert                         CA             ACTIVE     true           10944719598952040374951832963794454346               2031-11-10T00:00:00Z     2006-11-10T00:00:00Z

```

**Comment by nv1-0** [comment]
Hi,
To verify again...i exposed same dummy  mTLS endpoint example.com in two namespaces.
The content of the resources is as follows

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: test-cross-secret
spec:
  exportTo:
    - .
  hosts:
    - example.com
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
  resolution: DNS

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-cross-secret
spec:
  exportTo:
    - .
  gateways:
    - istio-egressgateway
    - mesh
  hosts:
    - example.com
  http:
    - match:
        - gateways:
            - mesh
          port: 80
      route:
        - destination:
            host: istio-egressgateway.tenant-2.svc.cluster.local #namespace changes here for egress gateway for tenant-2
            port:
              number: 80
    - match:
        - gateways:
            - istio-egressgateway
          port: 80
      route:
        - destination:
            host: example.com
            port:
              number: 443

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: test-cross-secret
spec:
  exportTo:
    - .
  host: example.com
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
      - port:
          number: 443
        tls:
          credentialName: test-cross-secret
          mode: MUTUAL
          sni: example.com


```

I created secret only in one namespace
The output is as follows

```bash
root@machine:~$ sudo kubectl get secret -n tenant-1 | grep test-cross-secret
root@machine:~$ sudo kubectl get secret -n tenant-2 | grep test-cross-secret
test-cross-secret                                 Opaque                                3      27m
```

Then i run the istioctl pc s command for both of the gateways

Here is the output
```bash
root@machine:~$ sudo istioctl pc s istio-egressgateway-5d6c8bddbd-27n7w.tenant-1
RESOURCE NAME                                                 TYPE           STATUS     VALID CERT     SERIAL NUMBER                                        NOT AFTER                NOT BEFORE
kubernetes://test-cross-secret                                Cert Chain     ACTIVE     true           614601718806992197                                   2021-08-07T15:51:31Z     2018-08-07T15:51:31Z
kubernetes://test-cross-secret-cacert                         CA             ACTIVE     true           10944719598952040374951832963794454346               2031-11-10T00:00:00Z     2006-11-10T00:00:00Z
root@machine:~$ sudo istioctl pc s istio-egressgateway-5cc9954f98-dz5kt.tenant-2
RESOURCE NAME                                                 TYPE           STATUS     VALID CERT     SERIAL NUMBER                                        NOT AFTER                NOT BEFORE
kubernetes://test-cross-secret                                Cert Chain     ACTIVE     true           614601718806992197                                   2021-08-07T15:51:31Z     2018-08-07T15:51:31Z
kubernetes://test-cross-secret-cacert                         CA             ACTIVE     true           10944719598952040374951832963794454346               2031-11-10T00:00:00Z     2006-11-10T00:00:00Z

```
