### ISSUE TITLE
istio overlay metadata.annotations not patched

### ISSUE THREAD

**Issue by yalctay93** [istio/istio#33376]
It is not possible to patch the metadata.annotations field for services. Here is the sample:

```yaml
              overlays:
                - apiVersion: v1
                  kind: Service
                  name: {{.Name}} 
                  patches:
                    - path: spec.type
                      value: LoadBalancer
                    - path: spec.loadBalancerIP
                      value: {{ .LoadBalancerIP}} # default, will be overwritten by kubefed
                    - path: spec.loadBalancerSourceRanges
                      value:
                        - x.x.x.x/x
                    - path: metadata.annotations
                      - value:
                          - loadbalancer.openstack.org/proxy-protocol: true
```

the path metadata.annotations I would assume is correct. When creating the svc, the istio-operator logs no error however, when checking the svc, the annotation that is set here ```loadbalancer.openstack.org/proxy-protocol: true``` is not included.

Are we using a wrong syntax for the patch field? If not, it seems to be a bug?

Thanks for your help!
