### ISSUE TITLE
virtual service url match rule only appear in envoy config of gateways

### ISSUE THREAD

**Issue by rtttech** [istio/istio#33371]
istio 1.8.3

I found virtual service url match rule only appear in envoy config of gateways. No config found in pod sidecar envoy config of namespace virtual service applied to by kubectl apply -f  xxx.yaml -n xxx-namespace.

virtual service:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mq-svc
spec:
  hosts:
  - "*"
  gateways:
  - mygateway
  http:
  - match:
    - uri:
        exact: /hellomq
  route:
  -  destination:
         host: mq-svc
         port:
             number: 8888
       
```
