### ISSUE TITLE
defunct `meshConfig.defaultConfig.tracing.zipkin.address` field in `IstioOperator`

### ISSUE THREAD

**Issue by errordeveloper** [istio/istio#33372]
**Bug description**

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Having set
```yaml
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 60
        zipkin:
          address: jaeger-default-collector.observability:9411
 ```

`.global.tracer.zipkin.address` in `istio-sidecar-injector` configmap and `--zipkinAddress` sidecar flag should both be set to `jaeger-default-collector.observability:9411`.

**Steps to reproduce the bug**

Install the operator:
```
istioctl operator init
```

Create initial config:
```
kubectl apply -f - << EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  labels:
    k8s-app: istio
  name: istio
  namespace: istio-system
spec: {}
EOF
```

Check mesh config:
```
$ kubectl get cm -n istio-system  istio -o json | jq -r .data.mesh 
defaultConfig:
  discoveryAddress: istiod.istio-system.svc:15012
  proxyMetadata: {}
  tracing:
    zipkin:
      address: zipkin.istio-system:9411
enablePrometheusMerge: true
rootNamespace: istio-system
trustDomain: cluster.local
$
```

Check injector config - empty string:
```
$ kubectl get cm -n istio-system istio-sidecar-injector -o json | jq -r .data.values | jq .global.tracer.zipkin.address
""
$
```

Update config to zipkin address:
```
kubectl apply -f - << EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  labels:
    k8s-app: istio
  name: istio
  namespace: istio-system
spec:
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 60
        zipkin:
          address: jaeger-default-collector.observability:9411
EOF
```

Check mesh config - zipkin address is set as intended(!):
```
$ kubectl get cm -n istio-system istio -o json | jq -r .data.mesh 
defaultConfig:
  discoveryAddress: istiod.istio-system.svc:15012
  proxyMetadata: {}
  tracing:
    zipkin:
      address: jaeger-default-collector.observability:9411
enablePrometheusMerge: true
rootNamespace: istio-system
trustDomain: cluster.local
$
```

Check injector config - still empty string:
```
$ kubectl get cm -n istio-system istio-sidecar-injector -o json | jq -r .data.values | jq .global.tracer.zipkin.address
""
```

Update config to set `values.global.tracer.zipkin.address`:
```
kubectl apply -f - << EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  labels:
    k8s-app: istio
  name: istio
  namespace: istio-system
spec:
  components:
    ingressGateways:
    - enabled: false
      name: istio-ingressgateway
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 60
        zipkin:
          address: jaeger-default-collector.observability:9411
  values:
    global:
      tracer:
        zipkin:
          address: jaeger-default-collector.observability:9411
EOF
```

Check mesh and injector configs - both are set now(!):
```
 $ kubectl get cm -n istio-system istio -o json | jq -r .data.mesh
defaultConfig:
  discoveryAddress: istiod.istio-system.svc:15012
  proxyMetadata: {}
  tracing:
    sampling: 60
    zipkin:
      address: jaeger-default-collector.observability:9411
enablePrometheusMerge: true
enableTracing: true
rootNamespace: istio-system
trustDomain: cluster.local
$ kubectl get cm -n istio-system istio-sidecar-injector -o json | jq -r .data.values | jq .global.tracer.zipkin.address 
"jaeger-default-collector.observability:9411"
```

Update config to remove defunct field:
```
kubectl apply -f - << EOF                                                                                                          
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  labels:
    k8s-app: istio
  name: istio
  namespace: istio-system
spec:
  components:
    ingressGateways:
    - enabled: false
      name: istio-ingressgateway
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 60
  values:
    global:
      tracer:
        zipkin:
          address: jaeger-default-collector.observability:9411
EOF
```

Check mesh and injector configs - both are still set as desired(!):
```
$ kubectl get cm -n istio-system istio -o json | jq -r .data.mesh
defaultConfig:
  discoveryAddress: istiod.istio-system.svc:15012
  proxyMetadata: {}
  tracing:
    sampling: 60
    zipkin:
      address: jaeger-default-collector.observability:9411
enablePrometheusMerge: true
enableTracing: true
rootNamespace: istio-system
trustDomain: cluster.local
$ kubectl get cm -n istio-system istio-sidecar-injector -o json | jq -r .data.values | jq .global.tracer.zipkin.address
"jaeger-default-collector.observability:9411"
$ 
```

Update config to use two conflicting values:
```
kubectl apply -f - << EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  labels:
    k8s-app: istio
  name: istio
  namespace: istio-system
spec:
  components:
    ingressGateways:
    - enabled: false
      name: istio-ingressgateway
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 60
        zipkin:
          address: not-working:9411                           
  values:
    global:
      tracer:
        zipkin:
          address: working:9411                               
EOF
```

Check mesh and sidecar injector configs - each uses separate values:
```
$ kubectl get cm -n istio-system istio -o json | jq -r .data.mesh
defaultConfig:
  discoveryAddress: istiod.istio-system.svc:15012
  proxyMetadata: {}
  tracing:
    sampling: 60
    zipkin:
      address: not-working:9411
enablePrometheusMerge: true
enableTracing: true
rootNamespace: istio-system
trustDomain: cluster.local
$ kubectl get cm -n istio-system istio-sidecar-injector -o json | jq -r .data.values | jq .global.tracer.zipkin.address
"working:9411"
$
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
$ istioctl version
client version: 1.10.0
control plane version: 1.10.0
data plane version: 1.10.0 (1 proxies)
$ kubectl version           
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:15:04Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
$
```

**How was Istio installed?**

Using the operator on Docker for Mac.

**Environment where the bug was observed (cloud vendor, OS, etc)**

Docker for Mac 3.3.3 with Kubernetes 1.19.7.

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
