### ISSUE TITLE
regression: custom TLS settings in envoyfilter no longer merge

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#33385]
An envoyfilter like:

```
      value:
         transport_socket:
           name: my-custom-config
           typed_config:
             ...
```

No longer has an effect. Broken by https://github.com/istio/istio/commit/1461bd714e10aad760a2a7ad1c817004e3297be2
