### ISSUE TITLE
Envoy connection buffer limits, badly need documentation please!

### ISSUE THREAD

**Issue by gopakumarce** [istio/istio#33416]
So by default, envoy seems to buffer up like 256Mb or so per connection (which I dont understand why, makes no sense to me). So for example when I have a scenario like this - client<----istio(k8s cluster)<------speedtest.net - and I do a speedtest, the client to k8s cluster is say 50Mbps, but k8s cluster to speedtest.net can be like gigs of bandwidth. So envoy buffers up like crazy and gets OOM killed eventually.

I understand that envoy filters can be used to change all that, I tried it, I typed all the envoy commands to ensure that the configs are in place, but I still see envoy buffering up and going belly up. The yaml I used is below - I have burnt a lot of time on this thing, can someone please tell me what I might be doing wrong ? Also does this need to be done per namespace ?
---
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: envoy-filter-for-nextensio-global
  namespace: istio-system
spec:
  configPatches:
    - applyTo: CLUSTER
      patch:
        operation: MERGE
        value:
          per_connection_buffer_limit_bytes: 65536
    - applyTo: NETWORK_FILTER
      match:
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager"
            http2_protocol_options:
              max_concurrent_streams: 100
              initial_stream_window_size: 65536
              initial_connection_window_size: 65536
    - applyTo: LISTENER
      patch:
        operation: MERGE
        value:
          per_connection_buffer_limit_bytes: 65536
```
---

**Comment by antoniovicente** [comment]
cc @yanavlasov 

I think that an issue you may be running into is that http2_protocol_options needs to be applied not only to listeners, but also to cluster configs.  The listeners are probably getting the right config and sending small window settings to downstream clients, but the clusters are still advertising very large windows to upstream servers.

Some recommendations can be found at:
https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/edge

**Comment by gopakumarce** [comment]
Thanks a lot @antoniovicente - that really helped ! So finally this is what made everything stable for me - pasting it here with comments, for future reference to anyone who runs into similar issues

---

```

# I apply the below to istio-system namespace AND my own namespace 'nextensio' 
# seen later down, the istio-system stuff takes care of istio ingress/egress gateways
# and my own namespace is for the sidecars in my namespace
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: nextensio-limit-buffering
  namespace: istio-system
spec:
  configPatches:
    - applyTo: CLUSTER
      # If I dont have a match statement and let it just apply to all ports by default (I would like that),
      # it has the undesirable side-effect of forcing ALL cluster ports to http2 - I dont know why !! So
      # I have some cluster ports to handle websocket, and obviously they cant to http2, if there is no
      # explicit match here, my websocket starts getting http2 !! So to prevent that, I explicitly match
      # on the http2 port that I use, port 80. And the match format was a lot of trial and error, I havent
      # seen any document explain how to write a match for cluster, I mean I dont know why a match+cluster
      # is needed when there is already an applyTo: CLUSTER, but without match+cluster+portNumber 
      # combo, it wont really match a specific port 
      match:
        cluster:
          portNumber: 80 
      patch:
        operation: MERGE
        value:
          http2_protocol_options:
            initial_stream_window_size: 65536  
            initial_connection_window_size: 65536 
          per_connection_buffer_limit_bytes: 65536
    # There is again a cluster rule here because the above rule only matches port 80
    # and hence the per_connection_buffer_limit_bytes setting there will only apply
    # to port 80. But I want to apply per_connection_buffer_limit_bytes to ALL ports,
    # http2 and non-http2 (web socket in my case). So this rule will apply to all other
    # ports (in my case port 443 websocket) and set their envoy buffer limit
    - applyTo: CLUSTER
      patch:
        operation: MERGE
        value:
          per_connection_buffer_limit_bytes: 65536
    - applyTo: NETWORK_FILTER
      match:
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: MERGE
        value:
          typed_config:
            # All envoy example pages say use v3.HttpConnectionManager, but kubectl apply
            # validation complains that the v3 version doesnt have http2 options and such,
            # v2 seems to work fine
            "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager"
            http2_protocol_options:
              max_concurrent_streams: 100000
              initial_stream_window_size: 65536
              initial_connection_window_size: 65536
    - applyTo: LISTENER
      patch:
        operation: MERGE
        value:
          per_connection_buffer_limit_bytes: 65536
---
# Exact same stuff as above for istio-system namespace repeated for my namespace,
# looks like we need to do this for every namespace of interest
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: nextensio-limit-buffering
  namespace: nextensio
spec:
  configPatches:
    - applyTo: CLUSTER
      match:
        cluster:
          portNumber: 80
      patch:
        operation: MERGE
        value:
          http2_protocol_options:
            initial_stream_window_size: 65536  
            initial_connection_window_size: 65536 
          per_connection_buffer_limit_bytes: 65536
    - applyTo: CLUSTER
      patch:
        operation: MERGE
        value:
          per_connection_buffer_limit_bytes: 65536
    - applyTo: NETWORK_FILTER
      match:
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager"
            http2_protocol_options:
              max_concurrent_streams: 100000
              initial_stream_window_size: 65536
              initial_connection_window_size: 65536
    - applyTo: LISTENER
      patch:
        operation: MERGE
        value:
          per_connection_buffer_limit_bytes: 65536


```
