### ISSUE TITLE
IstioOperator ingressGateway service type

### ISSUE THREAD

**Issue by JonasJasas** [istio/istio#33468]
**Bug description**

`type: NodePort` not changing service type.

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: gateways
  namespace: istio-system
spec:
  components:
    base:
      enabled: true
      
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          priorityClassName: system-node-critical
          resources:
            limits:
              memory: 5Gi
              
          strategy:
            type: RollingUpdate
            rollingUpdate: 
              maxSurge: 1
              maxUnavailable: 0
              
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: node-role.kubernetes.io/master
                        operator: DoesNotExist
          overlays:
            - kind: Deployment
              name: istio-ingressgateway
              patches:
                - path: spec.template.spec.topologySpreadConstraints
                  value: 
                    - maxSkew: 1
                      topologyKey: kubernetes.io/hostname
                      whenUnsatisfiable: ScheduleAnyway
                      labelSelector:
                        matchLabels:
                          istio: ingressgateway
              
          service:
            type: NodePort
            externalTrafficPolicy: Local
            selector:
              app: istio-ingressgateway          
            ports:
              - name: http
                port: 8000
                targetPort: 8000
                nodePort: 80
              - name: https
                port: 1443
                targetPort: 1443
                nodePort: 443
```

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Create NodePort type service

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
istioctl version --remote
client version: 1.10.1
control plane version: 1.10.1
data plane version: 1.10.1 (3 proxies)

Client Version: v1.21.1
Server Version: v1.21.1
```
**How was Istio installed?**
`istioctl operator init`

**Environment where the bug was observed (cloud vendor, OS, etc)**
Baremetal Ubuntu 18.04

---
**Update**
This issue is related to another IstioOperator resource:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: meshconfig
  namespace: istio-system
spec:
  profile: default
  meshConfig:
    defaultConfig:
      terminationDrainDuration: '600s'
```

These two resources can't coexist. This issue appears not always, I guess race condition or order is important.
