### ISSUE TITLE
KubernetesResourceSpec volumes and volumeMounts doesnot work with csi volumeType

### ISSUE THREAD

**Issue by vijay2308** [istio/istio#33497]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
KubernetesResourceSpec(k8s) volumes and volumeMounts doesnot work with csi driver volume mount type. 
Upon providing extra volumes and volumeMounts with csi driver with `secretProviderClass` type on istio ingress gateway component in `IstioOperator` CR , we cant see  `volumes` and `volumeMounts` getting appended to ingress gateway component. 

istio version : 1.10.0 

volumes and volumeMounts block:

    ingressGateways:
      - enabled: true
        k8s:
          volumeMounts:
            - mountPath: /secrets
              name: istio-secrets
          volumes:
          - name: istio-secrets
            volumeSource:
              csi:
                driver: secrets-store.csi.k8s.io
                readOnly: true
                volumeAttributes:
                  secretProviderClass: istio-gateway-secretproviderclass

`IstioOperator` CR:
```
kind: IstioOperator
apiVersion: install.istio.io/v1alpha1
metadata:
  annotations:
    meta.helm.sh/release-name: istio
    meta.helm.sh/release-namespace: istio-system
  name: istio-controlplane
  namespace: istio-system
spec:
  components:
    base:
      enabled: true
    cni:
      enabled: true
      namespace: kube-system
    ingressGateways:
      - enabled: true
        k8s:
          volumeMounts:
            - mountPath: /secrets
              name: istio-secrets
          volumes:
          - name: istio-secrets
            volumeSource:
              csi:
                driver: secrets-store.csi.k8s.io
                readOnly: true
                volumeAttributes:
                  secretProviderClass: istio-gateway-secretproviderclass
          env:
            - name: ISTIO_META_ROUTER_MODE
              value: sni-dnat
            - name: ISTIO_META_REQUESTED_NETWORK_VIEW
              value: eastus2
          podAnnotations:
            prometheus.io/path: /stats/prometheus
            prometheus.io/port: '15020'
            prometheus.io/scrape: 'true'
          replicaCount: 3
          resources:
            limits:
              cpu: '2'
              memory: 1Gi
            requests:
              cpu: 1500m
              memory: 1G
          service:
            loadBalancerIP: xx.xx.xx.xx
            ports:
              - name: status-port
                port: 15021
                targetPort: 15021
              - name: tls
                port: 15443
                targetPort: 15443
              - name: tls-istiod
                port: 15012
                targetPort: 15012
              - name: tls-webhook
                port: 15017
                targetPort: 15017
              - name: tcp
                port: 31400
                targetPort: 31400
        label:
          app: istio-ingressgateway
          istio: ingressgateway
          topology.istio.io/network: eastus2
        name: istio-ingressgateway
        namespace: istio-system
  meshConfig:
    accessLogEncoding: JSON
    accessLogFile: /dev/stdout
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_AUTO_ALLOCATE: 'true'
        ISTIO_META_DNS_CAPTURE: 'true'
  tag: 1.10.0
  unvalidatedValues:
    cni:
      logLevel: info
  values:
      logLevel: info
    global:
      imagePullPolicy: IfNotPresent
      meshID: mesh-eastus2
      multiCluster:
        clusterName: cluster-eastus2
      network: eastus2

```

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

[] Multi Cluster
[] Multi Control Plane

**Expected behavior**
KubernetesResourceSpec's volumes and volumeMounts should work!

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
istio version: 1.10.0 
kubernetes:
Client Version: v1.19.5
Server Version: v1.19.9

helm version: 
version.BuildInfo{Version:"v3.5.1", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"dirty", GoVersion:"go1.15.7"}

**How was Istio installed?**
IstioOperator

**Environment where the bug was observed (cloud vendor, OS, etc)**
AKS ( Azure Kubernetes Service ) 

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
