### ISSUE TITLE
source.remoteIpBlocks of  AuthorizationPolicy will set all clinet ip  when accept a reuqest of http/https lb 

### ISSUE THREAD

**Issue by luohua13** [istio/istio#33513]
**Bug description**

When I Create a gateway and a vs and a AuthorizationPolicy on foo namespace and set  IpAllowList for source.remoteIpBlocks with a ip:

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: httpbin
  namespace: foo
spec:
  selector:
    matchLabels:
      app: httpbin
  action: ALLOW
  rules:
  - from:
    - source:
       remoteIpBlocks: ["192.168.22.1"]
```
then I send a request from node[192.168.22.1] by http/https lb.
return result is **RBAC: access denied**
and pod log show:
```shell
'x-forwarded-for', '192.168.22.1, 192.168.22.1,100.64.0.2'
```

and then I update AuthorizationPolicy:
```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: httpbin
  namespace: foo
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        remoteIpBlocks:
        - 192.168.22.1
        - 100.64.0.2
  selector:
    matchLabels:
      app: httpbin
```
then I send a request from node[192.168.22.1], return result is:
```shell
{
  "origin": "192.168.22.1, 192.168.22.1,100.64.0.2"
}
```
It is ok!

So source.remoteIpBlocks of AuthorizationPolicy will set all client ip in a request chain?
But I just want to set origin client IP.
It is a bug?

**Version** 
control plane version: 1.8.3-b5ba77de-3.4.0
data plane version: 1.8.3-b5ba77de-3.4.0 (20 proxies)
