### ISSUE TITLE
No image docker.io/istio/auto

### ISSUE THREAD

**Issue by fccmks** [istio/istio#33512]
**Bug description**

I am trying to deploy istio-ingress in separate namespace with following config:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-gateways-1-10-1 # REQUIRED
  namespace: istio-ingress
spec:
  profile: empty # REQUIRED
  revision: 1-10-1 # REQUIRED
  components:
    ingressGateways:
      - name: istio-ingressgateway
        namespace: istio-ingress
        enabled: true
        label:
          # Set a unique label for the gateway. This is required to ensure Gateways
          # can select this workload
          istio: ingressgateway
          app: istio-ingressgateway
            
  values:
    gateways:
      istio-ingressgateway:
        # Enable gateway injection
        injectionTemplate: gateway  
        type: NodePort
        replicaCount: 3
        autoscaleMin: 3
        ports:
        - name: status-port
          protocol: TCP
          port: 15021
          targetPort: 15021
          nodePort: 30021
        - name: http2
          protocol: TCP
          port: 80
          targetPort: 8080
          nodePort: 30080
        - name: https
          protocol: TCP
          port: 443
          targetPort: 8443
          nodePort: 30443
```

but pods failing with error:
```
Normal   BackOff    24s (x5 over 109s)  kubelet            Back-off pulling image "auto"
  Warning  Failed     24s (x5 over 109s)  kubelet            Error: ImagePullBackOff
  Normal   Pulling    13s (x4 over 111s)  kubelet            Pulling image "auto"
  Warning  Failed     11s (x4 over 109s)  kubelet            Failed to pull image "auto": rpc error: code = Unknown desc = failed to resolve image "docker.io/library/auto:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
istio-ingressgateway pods up and running

**Steps to reproduce the bug**
1. Install Istio operator with
```
istioctl operator init --watchedNamespaces=istio-system,istio-ingress
```
2. Deploy Istiod using IstioOperator CR and _minimal_ profile
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-controlplane-1-10-1
spec:
  profile: minimal
  revision: 1-10-1
  values:
    pilot:
      replicaCount: 3
      autoscaleMin: 3
```
3. Deploy istio-ingressgateway as described [here](https://istio.io/latest/docs/setup/additional-setup/gateway/)

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
istioctl version --remote
client version: 1.10.1
control plane version: 1.10.1
data plane version: none
```
```
kubectl version --short
Client Version: v1.18.16
Server Version: v1.18.16
```

**How was Istio installed?**
https://istio.io/latest/docs/setup/install/operator/

**Environment where the bug was observed (cloud vendor, OS, etc)**
k8s in our office environment
