### ISSUE TITLE
Istio config gen fails when sum of endpoint weights over uint32 max

### ISSUE THREAD

**Issue by arkodg** [istio/istio#33536]
**Bug description**

Seeing this `ClusterLoadAssignmentValidationError` in `Istiod` logs 
```
value must be greater than or equal to " '\x01']
```

which relates to empty weight here
```
    load_balancing_weight {
    }
```

which should have a weight of 1.

Detailed error:   

```
2021-06-20T18:55:27.150890Z	warn	ads	ADS:CDS: ACK ERROR router~10.1.0.7~istio-egressgateway-789b64c5f4-lw4cg.istio-system~istio-system.svc.cluster.local-2 Internal:Proto constraint validation failed (ClusterValidationError.LoadAssignment: ["embedded message failed validation"] | caused by ClusterLoadAssignmentValidationError.Endpoints[i]: ["embedded message failed validation"] | caused by LocalityLbEndpointsValidationError.LoadBalancingWeight: ["value must be greater than or equal to " '\x01']): name: "outbound|80||www.bookinfo.com"
type: STRICT_DNS
connect_timeout {
  seconds: 10
}
circuit_breakers {
  thresholds {
    max_connections {
      value: 4294967295
    }
    max_pending_requests {
      value: 4294967295
    }
    max_requests {
      value: 4294967295
    }
    max_retries {
      value: 4294967295
    }
  }
}
dns_refresh_rate {
  seconds: 5
}
dns_lookup_family: V4_ONLY
metadata {
  filter_metadata {
    key: "istio"
    value {
      fields {
        key: "default_original_port"
        value {
          number_value: 80
        }
      }
      fields {
        key: "services"
        value {
          list_value {
            values {
              struct_value {
                fields {
                  key: "host"
                  value {
                    string_value: "www.bookinfo.com"
                  }
                }
                fields {
                  key: "name"
                  value {
                    string_value: "www.bookinfo.com"
                  }
                }
                fields {
                  key: "namespace"
                  value {
                    string_value: "default"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
load_assignment {
  cluster_name: "outbound|80||www.bookinfo.com"
  endpoints {
    locality {
      region: "us-west-2"
    }
    lb_endpoints {
      endpoint {
        address {
          socket_address {
            address: "10.0.0.1"
            port_value: 15443
          }
        }
      }
      load_balancing_weight {
        value: 1
      }
    }
    load_balancing_weight {
      value: 1
    }
  }
  endpoints {
    locality {
      region: "us-east-2"
    }
    lb_endpoints {
      endpoint {
        address {
          socket_address {
            address: "10.0.0.2"
            port_value: 15443
          }
        }
      }
      load_balancing_weight {
        value: 4294967295
      }
    }
    lb_endpoints {
      endpoint {
        address {
          socket_address {
            address: "10.0.0.3"
            port_value: 15443
          }
        }
      }
      load_balancing_weight {
        value: 1
      }
    }
    load_balancing_weight {
    }
  }
}
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
According to https://istio.io/latest/docs/reference/config/networking/workload-entry/#WorkloadEntry
any weight value in the range of 0-4294967295 (uint32 max) is supported for the endpoint, so any endpoint weight can be in the above range

**Steps to reproduce the bug**
Apply this Service Entry where the sum of all the endpoint weights is greater than 4294967295
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: se-w-total-ep-wights-over-uint32-max 
spec:
  endpoints:
  - address: 10.0.0.1
    locality: us-west-2
    ports:
      http: 15443
    weight: 1
  - address: 10.0.0.2
    locality: us-east-2
    ports:
      http: 15443
    weight: 4294967295
  - address: 10.0.0.3 
    locality: us-east-2
    ports:
      http: 15443
    weight: 1
  exportTo:
  - '*'
  hosts:
  - www.bookinfo.com 
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 80
    protocol: HTTP
  resolution: DNS
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
istioctl version --remote
client version: 1.9.0
control plane version: 1.9.0
data plane version: 1.9.0 (2 proxies)
```
**How was Istio installed?**
```
istioctl install --set profile=demo -y
```
**Environment where the bug was observed (cloud vendor, OS, etc)**
```
Docker Desktop v3.3.3
```

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
