### ISSUE TITLE
Istio delegate does not work and get 404

### ISSUE THREAD

**Issue by yuzisun** [istio/istio#33530]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Istio delegate should work when routing from one virtual service to the other.

**Steps to reproduce the bug**
1) Create a knative service which creates the following virtual service 
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: torchserve-transformer-transformer-default-ingress
  namespace: default
spec:
  gateways:
  - knative-serving/knative-ingress-gateway
  hosts:
  - torchserve-transformer-transformer-default.default.example.com
  - match:
    - authority:
        prefix: torchserve-transformer-transformer-default.default.example.com
      gateways:
      - knative-serving/knative-ingress-gateway
    retries: {}
    route:
    - destination:
        host: torchserve-transformer-transformer-default-00001.default.svc.cluster.local
        port:
          number: 80
      headers:
        request:
          set:
            Knative-Serving-Namespace: default
            Knative-Serving-Revision: torchserve-transformer-transformer-default-00001
      weight: 100
```
send a request to the service via istio ingress gateway with HOST `torchserve-transformer-transformer-default.default.example.com`, it works and get 200 response

2)   Create the following delegate
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: torchserve-transformer
  namespace: default
spec:
  gateways:
  - knative-serving/knative-ingress-gateway
  hosts:
  - torchserve-transformer.default.example.com
  http:
  - delegate:
      name: torchserve-transformer-transformer-default-ingress
      namespace: default
```
send a request to the service via istio ingress gateway with HOST `torchserve-transformer.default.example.com`, it works and get 404 response
 
run following istioctl command does not see the routes generated for the delegate HOST
```
istioctl proxy-config routes istio-ingressgateway-6d8565884d-bgqt5.istio-system
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
istioctl version --remote
client version: 1.9.0
control plane version: 1.9.0
data plane version: 1.9.0 (3 proxies)
```

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**
Kind create cluster

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
