### ISSUE TITLE
Websocket over http2 does not work on version 10.1

### ISSUE THREAD

**Issue by skk2142** [istio/istio#33534]
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Bug description**
Envoy does not forward websocket upgrade request to the application. It instead just returns an 400 http error. Non-websocket requests work fine. I have added envoy debug logs.
This is how the request looks like:
```
gateway-dark-5b7488dd7b-zjwrl istio-proxy ':method', 'GET'
gateway-dark-5b7488dd7b-zjwrl istio-proxy ':authority', 'gully.to'
gateway-dark-5b7488dd7b-zjwrl istio-proxy ':scheme', 'https'
gateway-dark-5b7488dd7b-zjwrl istio-proxy ':path', '/graphql'
gateway-dark-5b7488dd7b-zjwrl istio-proxy 'pragma', 'no-cache'
gateway-dark-5b7488dd7b-zjwrl istio-proxy 'cache-control', 'no-cache'
gateway-dark-5b7488dd7b-zjwrl istio-proxy 'user-agent', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36'
gateway-dark-5b7488dd7b-zjwrl istio-proxy 'origin', 'https://gully.to'
gateway-dark-5b7488dd7b-zjwrl istio-proxy 'sec-websocket-version', '13'
gateway-dark-5b7488dd7b-zjwrl istio-proxy 'accept-encoding', 'gzip, deflate, br'
gateway-dark-5b7488dd7b-zjwrl istio-proxy 'accept-language', 'en-US,en;q=0.9,fr;q=0.8,la;q=0.7'
gateway-dark-5b7488dd7b-zjwrl istio-proxy 'x-prop-gateway-dark', 'true'
gateway-dark-5b7488dd7b-zjwrl istio-proxy 'sec-websocket-extensions', 'permessage-deflate; client_max_window_bits'
gateway-dark-5b7488dd7b-zjwrl istio-proxy 'sec-websocket-protocol', 'graphql-transport-ws'
gateway-dark-5b7488dd7b-zjwrl istio-proxy 'x-forwarded-for', '74.72.131.115'
gateway-dark-5b7488dd7b-zjwrl istio-proxy 'x-forwarded-proto', 'https'
gateway-dark-5b7488dd7b-zjwrl istio-proxy 'x-envoy-external-address', '74.72.131.115'
gateway-dark-5b7488dd7b-zjwrl istio-proxy 'x-request-id', '180d4217-54d6-4dfe-9b68-02e4fb49f8b9'
gateway-dark-5b7488dd7b-zjwrl istio-proxy 'x-envoy-attempt-count', '1'
gateway-dark-5b7488dd7b-zjwrl istio-proxy 'x-envoy-original-path', '/api/graphql'
gateway-dark-5b7488dd7b-zjwrl istio-proxy 'cookie', '<REDACTED>'
gateway-dark-5b7488dd7b-zjwrl istio-proxy 'upgrade', 'websocket'
gateway-dark-5b7488dd7b-zjwrl istio-proxy 'connection', 'upgrade'
gateway-dark-5b7488dd7b-zjwrl istio-proxy 'content-length', '0'
gateway-dark-5b7488dd7b-zjwrl istio-proxy 'x-forwarded-client-cert', <REDACTED>
gateway-dark-5b7488dd7b-zjwrl istio-proxy 'x-b3-traceid', 'e6dd4b7ccb0099750e0db59a1aa2db7f'
gateway-dark-5b7488dd7b-zjwrl istio-proxy 'x-b3-spanid', 'b02ff16f82baa22e'
gateway-dark-5b7488dd7b-zjwrl istio-proxy 'x-b3-parentspanid', '0e0db59a1aa2db7f'
gateway-dark-5b7488dd7b-zjwrl istio-proxy 'x-b3-sampled', '0'
```

The request does not get to the main application. This is the response log from envoy.
```
gateway-dark-5b7488dd7b-zjwrl istio-proxy 
gateway-dark-5b7488dd7b-zjwrl istio-proxy 2021-06-19T17:33:12.661587Z	debug	envoy pool	queueing stream due to no available connections
gateway-dark-5b7488dd7b-zjwrl istio-proxy 2021-06-19T17:33:12.661591Z	debug	envoy pool	trying to create new connection
gateway-dark-5b7488dd7b-zjwrl istio-proxy 2021-06-19T17:33:12.661596Z	debug	envoy pool	creating a new connection
gateway-dark-5b7488dd7b-zjwrl istio-proxy 2021-06-19T17:33:12.661663Z	debug	envoy client	[C353] connecting
gateway-dark-5b7488dd7b-zjwrl istio-proxy 2021-06-19T17:33:12.661668Z	debug	envoy connection	[C353] connecting to 10.96.0.24:3000
gateway-dark-5b7488dd7b-zjwrl istio-proxy 2021-06-19T17:33:12.661748Z	debug	envoy connection	[C353] connection in progress
gateway-dark-5b7488dd7b-zjwrl istio-proxy 2021-06-19T17:33:12.661792Z	debug	envoy connection	[C353] connected
gateway-dark-5b7488dd7b-zjwrl istio-proxy 2021-06-19T17:33:12.661797Z	debug	envoy client	[C353] connected
gateway-dark-5b7488dd7b-zjwrl istio-proxy 2021-06-19T17:33:12.661804Z	debug	envoy pool	[C353] attaching to next stream
gateway-dark-5b7488dd7b-zjwrl istio-proxy 2021-06-19T17:33:12.661808Z	debug	envoy pool	[C353] creating stream
gateway-dark-5b7488dd7b-zjwrl istio-proxy 2021-06-19T17:33:12.661817Z	debug	envoy router	[C51][S4812833863188107822] pool ready
gateway-dark-5b7488dd7b-zjwrl istio-proxy 2021-06-19T17:33:12.663017Z	debug	envoy router	[C51][S4812833863188107822] upstream headers complete: end_stream=false
gateway-dark-5b7488dd7b-zjwrl istio-proxy 2021-06-19T17:33:12.663125Z	debug	envoy http	[C51][S4812833863188107822] encoding headers via codec (end_stream=false):
gateway-dark-5b7488dd7b-zjwrl istio-proxy ':status', '400'
gateway-dark-5b7488dd7b-zjwrl istio-proxy 'content-type', 'text/html'
gateway-dark-5b7488dd7b-zjwrl istio-proxy 'content-length', '11'
gateway-dark-5b7488dd7b-zjwrl istio-proxy 'x-envoy-peer-metadata', '<REDACTED>'
gateway-dark-5b7488dd7b-zjwrl istio-proxy 'x-envoy-peer-metadata-id', 'sidecar~10.96.0.24~gateway-dark-5b7488dd7b-zjwrl.production~production.svc.cluster.local'
gateway-dark-5b7488dd7b-zjwrl istio-proxy 'date', 'Sat, 19 Jun 2021 17:33:12 GMT'
gateway-dark-5b7488dd7b-zjwrl istio-proxy 'server', 'istio-envoy'
gateway-dark-5b7488dd7b-zjwrl istio-proxy 
gateway-dark-5b7488dd7b-zjwrl istio-proxy 2021-06-19T17:33:12.663215Z	debug	envoy client	[C353] response complete
gateway-dark-5b7488dd7b-zjwrl istio-proxy 2021-06-19T17:33:12.663232Z	debug	envoy router	[C51][S4812833863188107822] resetting pool request
gateway-dark-5b7488dd7b-zjwrl istio-proxy 2021-06-19T17:33:12.663247Z	debug	envoy http	[C51][S4812833863188107822] doEndStream() resetting stream
gateway-dark-5b7488dd7b-zjwrl istio-proxy 2021-06-19T17:33:12.663260Z	debug	envoy http	[C51][S4812833863188107822] stream reset
```

Service for the application looks like this:
```
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "production.labels" . | nindent 4 }}
spec:
  selector:
    app: gateway
  ports:
    - port: 80
      targetPort: 3000
      name: http-app
      protocol: TCP
```
Also, I have enabled http2 for envoy to allow for connection upgrades.
```json
"http2ProtocolOptions": {
    "allowConnect": true
},
"upgradeConfigs": [
      {
          "upgradeType": "websocket"
      }
  ],
```
**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

client version: 1.10.1
control plane version: 1.10.1
data plane version: 1.10.1 (23 proxies)

+ kubectl version --short
Client Version: v1.19.11
Server Version: v1.19.9-gke.1900

**How was Istio installed?**
istioctl
**Environment where the bug was observed (cloud vendor, OS, etc)**
GKE
Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by Monkeyanator** [comment]
Quick brain dump: from the [HTTP spec](https://datatracker.ietf.org/doc/html/rfc2616#section-4.3) we see:

> presence of a message-body in a request is signaled by the inclusion of a Content-Length or Transfer-Encoding header field in the request's message-headers

And from the Envoy docs on proxying websockets over HTTP2:

> the HTTP/2+ upgrade path has very strict HTTP/1.1 compliance, so will not proxy WebSocket upgrade requests or responses with bodies

From request-side Envoy logs we see `gateway-dark-5b7488dd7b-zjwrl istio-proxy 'content-length', '0'` so could be inclusion of that header throwing things off? I'm a bit confused since I thought we removed the header in `1.10` but we we can see it there in the logs

**Comment by Monkeyanator** [comment]
@skk2142 how are you going about "enabling http2 for envoy to allow for connection upgrades"? With `meshConfig.h2UpgradePolicy=UPGRADE`?

From local testing I found that websockets didn't work with that `h2UpgradePolicy=UPGRADE` enabled and that adding `AllowConnect: true` to the _inbound listener_ [here](https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/listener.go#L285) seemed to fix things

**Comment by skk2142** [comment]
I using the http2 upgrade in the destination rule for individual services in the mesh (including the `gateway` service which receives websocket connection.
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: gateway
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "production.labels" . | nindent 4 }}
spec:
  host: gateway.{{ $.Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    connectionPool:
      http:
        h2UpgradePolicy: "UPGRADE"
  subsets:
```
Also, I'm using an envoy filter for `allow_connect` 
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: envoy-http2-websocket-and-request-id-response
  namespace: istio-system
  labels: {{- include "production.labels" . | nindent 4 }}
spec:
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
            always_set_request_id_in_response: true
    - applyTo: NETWORK_FILTER
      match:
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
            http2_protocol_options:
              # for websocket
              allow_connect: true

```
