### ISSUE TITLE
Istio-proxy memory usage behaviour where AuthzPolicy and ReqAuth CRs are created

### ISSUE THREAD

**Issue by shydefoo** [istio/istio#33563]
**Bug description**
Istio-proxy memory usage increases when AuthzPolicy and ReqAuth CRs are created and deleted (expected). However, when the pod is restarted, the istio-proxy memory usage is much lower, even though the CRs created earlier were not deleted. Memory usage levels does not drop even after waiting for an extended period of time. This begs the question as to why the memory usage of the istio-proxy container after the CRs created is so much higher compared to after the pod was restarted. This behaviour is also observed when the pod replica is scaled from 1 to 2.

1 Pod running
Create 100 Authz and ReqAuth CRs each with 
```
        "selector": {
          "matchLabels": {
            "app": "httpbin-istio-test"
          }
```
![image](https://user-images.githubusercontent.com/20089568/122853383-b736f080-d344-11eb-8fb4-1d265f40c4f8.png)
* Memory increases to 500Mb

Scale up 2nd pod
![image](https://user-images.githubusercontent.com/20089568/122853430-c9b12a00-d344-11eb-855e-08347ff4c8ec.png)
* 2nd pod only has 118Mb even though same istio-proxy config applied

[ ] Docs
[ ] Installation
[ ] Networking
[x ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Memory usage of istio-proxy container after Istio CRs were created should drop to somewhat the same level as an istio-proxy container in a restarted pod. 

**Steps to reproduce the bug**
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    meta.helm.sh/release-name: httpbin-istio-proxy-sdfoo
    meta.helm.sh/release-namespace: ipp3
  name: httpbin-istio-test
  namespace: ipp3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: httpbin-istio-test
  template:
    metadata:
      annotations:
        sidecar.istio.io/proxyCPU: 500m
        sidecar.istio.io/proxyCPULimit: "2"
        sidecar.istio.io/proxyMemory: 512Mi
        sidecar.istio.io/proxyMemoryLimit: 6Gi
      creationTimestamp: null
      labels:
        app: httpbin-istio-test
    spec:
      containers:
      - image: kennethreitz/httpbin
        imagePullPolicy: Always
        name: httpbin
        ports:
        - containerPort: 80
          protocol: TCP
```
* Create 100 AuthorizationPolicy and 100 RequestAuthentication CRs while observing memory usage metrics
* Delete pod / Scale number of pods to 2 and wait for replicaset to create new pod

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
➜ istioctl version --remote
client version: 1.10.0
control plane version: 1.8.5
data plane version: 1.8.5 (105 proxies)
```
```
➜ kubectl version --short
Client Version: v1.20.2
Server Version: v1.18.18
```

**How was Istio installed?**
* Istio-operator

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
