### ISSUE TITLE
Unable to use WorkloadEntry

### ISSUE THREAD

**Issue by JonasJasas** [istio/istio#33567]
**Bug description**

Getting `no healthy upstream` with the similar configuration described here: 
https://istio.io/latest/blog/2020/workload-entry/

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
To balance between external service and local pod.

**Steps to reproduce the bug**
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: config
  namespace: istio-system
spec:
  profile: default
  components:
    base:
      enabled: true

    ingressGateways:
          service:
            type: NodePort
            externalTrafficPolicy: Local
            selector:
              app: istio-ingressgateway
            ports:
              - name: http
                port: 8000
                targetPort: 8000
                nodePort: 80
                
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp

spec:
  selector:
    matchLabels:
      app: myapp

  template:
    metadata:
      labels:
        app: myapp

    spec:
      containers:
        - name: myapp
          image: hashicorp/http-echo
          args: ['-listen=:8000', '-text="hello world"']
          
          ports:
            - name: http
              containerPort: 8000
              
---

apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
    - name: http
      appProtocol: http
      targetPort: http
      port: 8000
      
---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gw

spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation

  servers:
    - hosts:
        - '*'
      port:
        number: 8000
        name: http
        protocol: HTTP
        
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: myvs
spec:
  hosts:
    - '*'

  gateways:
    - gw

  http:
    - name: myapp
      match:
        - uri:
            prefix: /
      route:
        - destination:
            host: myapp.default.svc.cluster.local
            port:
              number: 8000
      retries:
        attempts: 20
        retryOn: 503,retriable-status-codes,connect-failure,reset
        retryRemoteLocalities: true

---

apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: myapp
spec:
  address: example.com
  ports:
    http: 80
  labels:
    app: myapp

---

apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: myapp
spec:
  hosts:
    - myapp.default.svc.cluster.local
  location: MESH_INTERNAL
  ports:
    - number: 8000
      name: http
      protocol: HTTP
      targetPort: 8000
  resolution: DNS
  workloadSelector:
    labels:
      app: myapp
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
istioctl version --remote
client version: 1.10.1
control plane version: 1.10.1
data plane version: 1.10.1 (1 proxies)
```
```
kubectl version --short
Client Version: v1.21.2
Server Version: v1.21.2
```

**How was Istio installed?**
`istioctl operator init`

**Environment where the bug was observed (cloud vendor, OS, etc)**
Baremetal Ubuntu 20.04

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

[bug-report.tar.gz](https://github.com/istio/istio/files/6692988/bug-report.tar.gz)

**Comment by JonasJasas** [comment]
NodePort range is extended down to 80.

**Comment by devincd** [comment]
I had reproduce the bug, and I will check the pilot code, try to give a fix method.

**Comment by JonasJasas** [comment]
I found that if `Service` is removed everything starts to work. Should service side-effect this way?

**Comment by devincd** [comment]
I see the config of istio-ingressgateway workload, shows there are no endpoints of `outbound|8000||myapp.default.svc.cluster.local` cluster. I think the endpoints should consist of the pods and workloadEntry.

**Comment by JonasJasas** [comment]
Should `ServiceEntry` alone add DNS record for `myapp.default.svc.cluster.local`?

**Comment by devincd** [comment]
yes， When you apply both the `service` and `serviceEntry`
```
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
    - name: http
      appProtocol: http
      targetPort: http
      port: 8000
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: myapp
spec:
  hosts:
    - myapp.default.svc.cluster.local
  location: MESH_INTERNAL
  ports:
    - number: 8000
      name: http
      protocol: HTTP
      targetPort: 8000
  resolution: DNS
  workloadSelector:
    labels:
      app: myapp
```
We can find the `myapp.default.svc.cluster.local` cluster type is `EDS`:
```
$ istioctl pc clusters istio-ingressgateway-58dd94cdfb-7flwj.istio-system
SERVICE FQDN                                            PORT      SUBSET     DIRECTION     TYPE           DESTINATION RULE
myapp.default.svc.cluster.local                   8000      -                outbound         EDS
```
But, there are no endpoints for the `myapp.default.svc.cluster.local` cluster, and I find the logs in Pilot:
```
......
2021-07-06T11:27:28.321891Z	info	ads	cluster outbound|8000||myapp.default.svc.cluster.local in eds cluster, but its resolution now is updated to DNS, skipping it.
......
2021-07-06T11:27:37.011053Z	info	ads	Push Status: {
    "pilot_duplicate_envoy_clusters": {
        "outbound|8000||myapp.default.svc.cluster.local": {
            "proxy": "details-v1-67bb4996c8-7x2kb.default",
            "message": "Duplicate cluster outbound|8000||myapp.default.svc.cluster.local found while pushing CDS"
        }
    }
}
````
Obviously, when pilot builds eds for the `myapp.default.svc.cluster.local` cluster,  its resolution now is updated to DNS. 

My doubt is why the cluster's resolution is EDS when pilot builds cds, but change to DNS when pilot builds eds?
