### ISSUE TITLE
Global Rate Limit not working with mTLS

### ISSUE THREAD

**Issue by ArchdukeNavaron** [istio/istio#33568]
**Bug description**

We implemented the envoy rate limit service into our mesh but are not able to get it working with a mTLS connection between our ingress gateway and the rate limit service.

[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

We want a secure and authenticated connection between our ingress gateway and the rate limit service.

**Steps to reproduce the bug**

1. Deploy the envoy rate limit service into a separate namespace.
2. Add the following envoyfilters and adapt them to your needs (service, ports, sni, etc.)
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: example-rate-limit
  namespace: istio-ingressgateway
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
          sni: sub.example.com
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.ratelimit
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
          domain: rate-limit-domain
          failure_mode_deny: true
          rate_limit_service:
            grpc_service:
              envoy_grpc:
                cluster_name: rate_limit_service
              timeout: 10s
            transport_api_version: V3
  - applyTo: CLUSTER
    match:
      cluster:
        service: rate-limit.rate-limit
    patch:
      operation: ADD
      value:
        connect_timeout: 10s
        http2_protocol_options: {}
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: rate_limit_service
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: rate-limit.rate-limit
                    port_value: 8081
        name: rate_limit_service
        type: STRICT_DNS
  workloadSelector:
    labels:
      app: istio-ingressgateway
```
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: example-rate-limit-svc
  namespace: istio-ingressgateway
spec:
  configPatches:
  - applyTo: VIRTUAL_HOST
    match:
      context: GATEWAY
      routeConfiguration:
        vhost:
          name: sub.example.com:443
          route:
            action: ANY
    patch:
      operation: MERGE
      value:
        rate_limits:
        - actions:
          - header_value_match:
              descriptor_value: example-key
              headers:
              - contains_match: 'foo'
                name: X-Example-Header
        - actions:
          - request_headers:
              descriptor_key: example-key-two
              header_name: X-Example-Header-Two
          - header_value_match:
              descriptor_value: example-key-three
              expect_match: false
              headers:
              - contains_match: 'foo'
                name: X-Example-Header-Three
  workloadSelector:
    labels:
      app: istio-ingressgateway
```
3. Create a authorization policy
```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: rate-limit-allow-ingress
  namespace: rate-limit
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/istio-ingressgateway/sa/istio-ingressgateway-service-account
    to:
    - operation:
        ports:
        - "8081"
  selector:
    matchLabels:
      app.kubernetes.io/name: rate-limit
```

***PERMISSIVE***

1. Create a peer authentication policy in the rate limit namespace
```yaml
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: rate-limit-mtls
  namespace: rate-limit
spec:
  mtls:
    mode: PERMISSIVE
```

2. You will get a `rbac_access_denied_matched_policy[none]` error in the rate-limit istio-proxy container

***STRICT***

1. Create a peer authentication policy in the rate limit namespace
```yaml
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: rate-limit-mtls
  namespace: rate-limit
spec:
  mtls:
    mode: STRICT
```

2. You will get a `NR filter_chain_not_found` error in the rate-limit istio-proxy container

***Debug logs and information***

When set to strict these logs are generated in the istio-proxy sidecar.
```yaml
rate-limit-68b459b57f-xcvm6 istio-proxy 2021-06-22T09:19:40.281441Z	debug	envoy conn_handler	[C36532] new connection
rate-limit-68b459b57f-xcvm6 istio-proxy 2021-06-22T09:19:40.282182Z	debug	envoy conn_handler	[C36532] adding to cleanup list
rate-limit-68b459b57f-xcvm6 istio-proxy 2021-06-22T09:19:40.423327Z	debug	envoy filter	original_dst: New connection accepted
rate-limit-68b459b57f-xcvm6 istio-proxy 2021-06-22T09:19:40.423357Z	debug	envoy filter	tls inspector: new connection accepted
rate-limit-68b459b57f-xcvm6 istio-proxy 2021-06-22T09:19:40.423362Z	trace	envoy filter	tls inspector: recv: 417
rate-limit-68b459b57f-xcvm6 istio-proxy 2021-06-22T09:19:40.423380Z	debug	envoy conn_handler	closing connection: no matching filter chain found
```

`istioctl proxy-config listeners rate-limit`
```
ADDRESS       PORT  MATCH                                                   DESTINATION
0.0.0.0            15006 Trans: tls; Addr: *:8081                         Cluster: inbound|8081||
```

`istioctl proxy-config routes rate-limit --name 8081`
```
NAME     DOMAINS        MATCH     VIRTUAL SERVICE
8081       *                       /*
8081       rate-limit         /*
```

`istioctl proxy-config cluster -n istio-ingressgateway  istio-ingressgateway`
```
SERVICE FQDN                                      PORT     SUBSET     DIRECTION     TYPE                    DESTINATION RULE
rate-limit.rate-limit.svc.cluster.local    8081      -                  outbound        EDS
rate_limit_service                                  -             -                  -                       STRICT_DNS
```

We have configured many services with basically the same authorization policy and therefore it should work just fine.

So the question is, is this a bug or did I misconfigure anything?
Or is it just possible when adding clusters etc. manually with an envoy filter the mTLS configuration does not match anymore (is not configured correctly) and I therefore cant use mTLS?

**Version**

control plane version: 1.10.1
data plane version: 1.10.1

**How was Istio installed?**

Operator
