### ISSUE TITLE
External Authorization outside of the mesh

### ISSUE THREAD

**Issue by fiftoine** [istio/istio#33595]
**Bug description**

Having oauth2-proxy inside the cluster and configuring provider envoyExtAuthzHttp service to the internal DNS name of the oauth2-proxy service, I can get Okta integrated correctly.

When I externalize oauth2-proxy with an istio gateway (and external-DNS) and use the domain as envoyExtAuthzHttp service, I get a 403 without even reaching oauth2-proxy.

Note: I want to do that as I want some other clusters to leverage the one and only oauth2-proxy deployment and avoid updating Okta redirect callbacks for each cluster.

It should be possible as it's described in the doc: https://istio.io/latest/docs/tasks/security/authorization/authz-custom/

> Alternatively, you can also deploy the external authorizer as a separate container in the same pod of the application that needs the external authorization or **even deploy it outside of the mesh**. In either case, you will also need to create a service entry resource to register the service to the mesh and make sure it is accessible to the proxy.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Ingress can reach to externalized oauth2-proxy with 

**Steps to reproduce the bug**

Deploy istio with an extra ingress (labelled `istio-secured-ingressgateway` and certificate attached to the ingresses lb svcs) as helm release with the following mesh config:
```
extensionProviders:
    - envoyExtAuthzHttp:
        ...
        port: "443"
        service: istio-auth.my-domain.com
```
Deploy external-DNS with sources to istio-gateway.
Deploy oauth2-proxy with internet exposition like the following:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-gateway-oauth-proxy
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - istio-auth.my-domain.com
      port:
        name: https-443
        number: 443
        protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-gateway-oauth-proxy
  namespace: istio-system
spec:
  gateways:
    - istio-gateway-oauth-proxy
  hosts:
    - istio-auth.my-domain.com
  http:
    - route:
        - destination:
            host: istio-gateway-oauth-proxy
          weight: 100
---
apiVersion: v1
kind: Service
metadata:
  name: istio-gateway-oauth-proxy
  namespace: istio-system
spec:
  ports:
    - name: web
      port: 4180
      protocol: TCP
  selector:
    app: oauth-proxy
```
At this point, everything works as expected (login to Okta flow) if I configure mesh config like this:
```
 extensionProviders:
    - envoyExtAuthzHttp:
        ...
        port: "4180"
        service: istio-gateway-oauth-proxy.istio-system.svc.cluster.local
``` 

Now I want use the internet exposed url of oauth2-proxy:
```
extensionProviders:
    - envoyExtAuthzHttp:
        ...
        port: "443"
        service: istio-auth.my-domain.com
``` 
I noticed that istio cannot start correctly because the service  `istio-auth.my-domain.com` is not part of the service registry, so I have to add a ServiceEntry.
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: oauth-proxy-external
  namespace : istio-system
spec:
  hosts:
  - istio-auth.my-domain.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
``` 

Doing that turns the working solution into getting a 403 on the browser without any logs in oauth2-proxy and getting an error in ingress-gateway `ext_authz_error`

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Istio
```
client version: 1.10.0
control plane version: 1.10.0
data plane version: 1.10.0 (14 proxies)
```
Kubectl
```
Client Version: v1.15.3
Server Version: v1.18.9-eks-d1db3c
```
Helm
```
v3.3.4+ga61ce56
```
**How was Istio installed?**
As helm release with an extra ingress
