### ISSUE TITLE
Cert-Manager ACME Certificate HTTP Challenge fails with 404 when tls httpsRedirect is set to true for Gateway

### ISSUE THREAD

**Issue by ktogias** [istio/istio#33593]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[X ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

Cert-manager let's encrypt certificates should be successfully issued and renewed for istio Gateways with the tls httpsRedirect directive for 80 port.

**Steps to reproduce the bug**

Create a certificate with letsencrypt cluster issuer and a gateway for the same domain with tls httpsRedirect true for port 80 . e.g.:

```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certname
  namespace: istio-system
spec:
  dnsNames:
  - example.domain.name
  secretName: certsecretname
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: example.domain.name

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gatewayname
  namespace: gatewaynamespace
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "example.domain.name"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: certsecretname
    hosts:
    - "example.domain.name"
```

cert-manager challenge remains pending with 404 error due to http to https redirection when getting the token

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
$ istioctl version --remote
client version: 1.8.1
control plane version: 1.8.1
data plane version: 1.8.1 (3 proxies)

$ kubectl version --short
Client Version: v1.20.0
Server Version: v1.20.2

$ helm version --short
v3.5.0+g32c2223

```
**How was Istio installed?**

istioctl operator init

**Environment where the bug was observed (cloud vendor, OS, etc)**

Self-hosted kuberentes cluster on centos8 vsphere vms

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
