### ISSUE TITLE
The destinationRule wants to support the same functionality as the NGINX error_page

### ISSUE THREAD

**Issue by chanyying** [istio/istio#33607]
**Describe the feature request**
`The destinationRule wants to support the same functionality as the NGINX error_page`
**Describe alternatives you've considered**
```
subsets:
  - name: testversion
    labels:
      version: v3
    errorPage:
        code:
            - 503
            - 404
        route:
           # cluster external
            - disable: false
               type: redirect
               url: http://xxx.com
          # cluster internal
           - disable: true
              type: host
              host: ratings.prod.svc.cluster.local
              labels:
                   version: v3
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[x] Developer Infrastructure

**Additional context**

Envoy endorses a similar ability
https://github.com/envoyproxy/envoy/blob/main/docs/root/configuration/http/http_conn_man/local_reply.rst
