### ISSUE TITLE
When Sidecar is injected, the service invocation appear 404 and response_flag is NR

### ISSUE THREAD

**Issue by pantianying** [istio/istio#33632]
**Bug description**
after sidecar is injected, the downstream app request upstream app use pod ip , then downstream istio-proxy return 404.
```
[2021-06-23T07:15:29.541Z] \"POST /user/query/encryptMobile HTTP/1.1\" 404 NR \"-\" \"-\" 0 0 0 - \"10.128.17.153\" \"Java/1.8.0_292\" \"ad1b3656-5d61-9757-8f56-27ab511cc632\" \"10.128.32.225:8080\" \"-\" - - 10.128.32.225:8080 10.128.17.153:46632 - -
```
When I found out about this, I looked at the logs on the up and down Envoy and saw the following exception log. It's not clear whether it was an error
```
gRPC config for type.googleapis.com/envoy.api.v2.RouteConfigur
ation rejected: Proto constraint validation failed (RouteConfigurationValidationError.VirtualHosts[i]: [\"embedded message failed validation\"] | caused by VirtualHostValidationError.Domains: [\"value must contain at least \" '\\x01' \" item(s)\"]): name: \"80\""
```
After my investigation, the above abnormal log, the route format problem is caused by the configuration of the service, do not know what problem exists with the service

```
kind: Service
apiVersion: v1
metadata: 
  name: ossproxy
  namespace: dna-infra
spec: 
  ports: 
    - name: http2
      protocol: TCP
      port: 80
      targetPort: 80
  type: ExternalName
  sessionAffinity: None
  externalName: kourier-internal.knative-serving-ingress.svc.cluster.local
status: 
  loadBalancer: {}
```
I think I need to understand the reasons and risks behind these phenomena

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade
