### ISSUE TITLE
simple tls problems when using the dr to tls original traffic

### ISSUE THREAD

**Issue by FeiYing9** [istio/istio#33633]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
I want to test the function of [ClientTLSSetting](https://istio.io/latest/docs/reference/config/networking/destination-rule/#ClientTLSSettings) in DR。
I find the DR didn't work sometimes when it's created in other namespace where the workload not exist.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**
1. install a k8s with single master node.
2. isntall the istio
3. deploy the workload in namespace `https` with the config
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: goserver-tls
  name: goserver-tls
spec:
  ports:
  - name: https
    port: 9090
    protocol: TCP
    targetPort: 8080
  selector:
    app: goserver-tls
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: goserver-tls
  name: goserver-tls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goserver-tls
  template:
    metadata:
      labels:
        app: goserver-tls
    spec:
      containers:
      - image: goserver-tls:v1.0.0
        imagePullPolicy: IfNotPresent
        name: goserver
        ports:
          - name: https
            containerPort: 8080
            protocol: TCP
```
to make sure it works fine whether in container or node environment
```bash
# kubectl -nhttps get po
NAME                            READY   STATUS    RESTARTS   AGE
goserver-tls-6fdcf6f5db-bmrlp   1/1     Running   0          4d1h
# kubectl -nhttps get svc
NAME            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)         AGE
goserver-tls    ClusterIP   10.105.3.144     <none>        9090/TCP        11d
# curl -s -HHost:goserver-tls --resolve "goserver-tls:9090:10.105.3.144" --cacert ./ca.crt  https://goserver-tls:9090/healthz
{"status":"healthy","hostName":"goserver-tls-6fdcf6f5db-bmrlp"}
```
4. inject the sidecar
    also to makje sure it works fine
5. create dr in namespace `https` like this
```yaml
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "goserver-tls"
spec:
  exportTo:         # export to all namespace explicitly
  - "*"
  host: goserver-tls.https.svc.cluster.local
  trafficPolicy:
    tls:
      mode: SIMPLE
      caCertificates: /etc/sleep/tls/goserver-tls/ca.crt
```
6. create deploy of `sleep` in namespace `https`
```bash
# kubectl apply -f samples/sleep/sleep.yaml -n https
```
7. mount the cert file into the sidecar like this
```yaml
kind: Deployment
spec:
      containers:
      - name: sleep               # sleep container
        image: curlimages/curl
      - name: istio-proxy         # sidecar container
        image: registry.hundsun.com/hcs/proxyv2:1.9.2      
        volumeMounts:
        - mountPath: /path/tls    # the path used by DR
          name: cert
      volumes:
      - hostPath:
          path: /path/to/cert       # where the ca.crt exists
          type: ""
        name: cert
```
8. make sure the DR works fine
```bash
# curl -i http://goserver-tls:9090/healthz
HTTP/1.1 200 OK
...
{"status":"healthy","hostName":"goserver-tls-6fdcf6f5db-bmrlp"}

# curl -i --cacert ./ca.crt  https://goserver-tls:9090/healthz
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```
9. create deploy of `sleep` in namespace `foo` and `bar` and mount the cert file into the sidecar as above shows
10. the DR works fine
11. delete the DR in namespace `https` and create it in namespace `foo` or `bar`
12. to test 
```bash
# kubectl -nfull exec -it deploy/sleep -c sleep -- curl -i http://goserver-tls.https.svc.cluster.local:9090/healthz
HTTP/1.0 400 Bad Request

Client sent an HTTP request to an HTTPS server.
#
# kubectl -nhttps exec -it deploy/sleep -c sleep -- curl -i http://goserver-tls:9090/healthz
HTTP/1.1 200 OK
Date: Fri, 25 Jun 2021 02:42:07 GMT
Content-Length: 63
Content-Type: text/plain; charset=utf-8

{"status":"healthy","hostName":"goserver-tls-64b8d888f9-hmwqv"}
```
13. when the DR is deployed in root namespace , all works fine.  I dont't know why sometimes the DR didn't work when it's deployed in other namespace though it's export to all namespace explicitly.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```bash
istioctl version --remote
  client version: 1.9.2
  control plane version: 1.9.2
  data plane version: 1.9.2 (9 proxies)
kubectl version --short
  Client Version: v1.18.2
  Server Version: v1.18.2
```

**How was Istio installed?**
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  hub: ${registry_url}
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
    defaultConfig:
      holdApplicationUntilProxyStarts: true
  values:
    global:
      imagePullPolicy: IfNotPresent
  components:
    egressGateways:
    - name: istio-egressgateway
      enabled: true
    pilot:
      k8s:
        podDisruptionBudget:
          minAvailable: 1
```

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
