### ISSUE TITLE
Istio Operator hangs when Deleting IstioOperator With Revision

### ISSUE THREAD

**Issue by murphye** [istio/istio#33649]
**Bug description**

If I create a control plane containing Istio Revision, I cannot delete it. Istio Operator hangs.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

`k delete istiooperator -n istio-system` should trigger Istio Operator to delete a control plane, when it's using revisions.

**Steps to reproduce the bug**

```
kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: gloo-istiocontrolplane
spec:
  profile: default
  tag: 1.10.2
  revision: 1-10-2
  components:
    pilot:
      k8s:
        resources:
          requests:
            memory: 10Mi
            cpu: 10m
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        resources:
          requests:
            memory: 10Mi
            cpu: 10m
        service:
          ports:
            - name: http2
              port: 8080
              targetPort: 8080
            - name: https
              port: 20443
              targetPort: 8443
            - name: tcp-status-port
              port: 15021
              targetPort: 15021
            - name: tls
              port: 8443
              targetPort: 15443
            - name: tcp-istiod
              port: 15012
              targetPort: 15012
            - name: tcp-webhook
              port: 15017
              targetPort: 15017
EOF
```
Then check the control plane deployment. Looks good.
```
k get pod -n istio-system
NAME                                   READY   STATUS    RESTARTS   AGE
istiod-1-10-2-6f8bd67fbb-zn984         1/1     Running   0          13s
svclb-istio-ingressgateway-wbsp6       6/6     Running   0          6s
svclb-istio-ingressgateway-9b9bt       6/6     Running   0          6s
istio-ingressgateway-6f8c99d7f-5xlvl   1/1     Running   0          6s
```
Now, try to delete the control plane. Deletion is hanging.

```
k delete istiooperator -n istio-system gloo-istiocontrolplane 
istiooperator.install.istio.io "gloo-istiocontrolplane" deleted <---- Hangs
```

Check the Istio Operator Logs. Deletion is hanging.

```
k logs -n istio-operator istio-operator-769c594554-z58h5
...
2021-06-25T22:58:25.020033Z	info	installer	Reconciling IstioOperator
2021-06-25T22:58:25.025068Z	info	installer	Deleting IstioOperator gloo-istiocontrolplane <---- Hangs
```
Control plane pods are still `Running`. They should be `Terminating`
```
k get pod -n istio-system
NAME                                   READY   STATUS    RESTARTS   AGE
istiod-1-10-2-6f8bd67fbb-zn984         1/1     Running   0          13s
svclb-istio-ingressgateway-wbsp6       6/6     Running   0          6s
svclb-istio-ingressgateway-9b9bt       6/6     Running   0          6s
istio-ingressgateway-6f8c99d7f-5xlvl   1/1     Running   0          6s
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

1.10.2

**How was Istio installed?**

Istio Operator 1.10.2

**Environment where the bug was observed (cloud vendor, OS, etc)**

Civo (k3s)

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
