### ISSUE TITLE
Istio 503 error spike hourly

### ISSUE THREAD

**Issue by bryan-kc** [istio/istio#33648]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
This is an extension on the previous issue I filed, but with more information.
https://github.com/istio/istio/issues/33283

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
No spike in latency.

**Steps to reproduce the bug**
- Setup a long running service with an ALB ingress
- Monitor percentile latency of application's Target Group.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
client version: 1.10.0
control plane version: 1.9.1
data plane version: 1.9.1 (65 proxies)
```

**How was Istio installed?**
Istio operator install with the following manifest

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  values:
    telemetry:
      v2:
        prometheus:
          configOverride:
            outboundSidecar:
              debug: false
              stat_prefix: istio
              metrics:
                - name: request_duration_milliseconds
                  dimensions:
                    cache_status: response.headers['X-Proxy-Cache']
  profile: default
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 100
        zipkin:
          address: opentelemetry-collector.opentelemetry-collector:9411
  components:
    pilot:
      k8s:
        hpaSpec:
          minReplicas: 2
        replicaCount: 2
```

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS EKS

`Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-eks-ad4801", GitCommit:"ad4801fd44fe0f125c8d13f1b1d4827e8884476d", GitTreeState:"clean", BuildDate:"2020-10-20T23:27:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
