### ISSUE TITLE
[gateway-api] address field in Gateway should be able to reply on GatewayClass

### ISSUE THREAD

**Issue by nak3** [istio/istio#33654]
**Describe the feature request**

Let's say we have two k8s svc for Istio ingress like:

```bash
$ kubectl get svc -n istio-system
NAME                    TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                                      AGE
istio-ingressgateway    LoadBalancer   10.96.21.133    <pending>     15021:30702/TCP,80:31614/TCP,443:30872/TCP   14m
knative-local-gateway   ClusterIP      10.96.246.238   <none>        80/TCP                                       3s
```

Then, the current Gateway needs to specify the address field as:

(Gateway for istio-ingressgateway)

```yaml
kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: test-gateway
  namespace: istio-system
spec:
  gatewayClassName: istio
  addresses:
  - type: NamedAddress
    value: istio-ingressgateway.istio-system.svc.cluster.local
```

(Gateway for knative-local-gateway)

```yaml
kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: test-local-gateway
  namespace: istio-system
spec:
  gatewayClassName: istio
  addresses:
  - type: NamedAddress
    value: knative-local-gateway.istio-system.svc.cluster.local
```

However, the Gateways are not portable.

**Expected feature**

We would like to omit the address field and rely on GatewayClass as:

(Gateway for istio-ingressgateway)

```yaml
kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: test-gateway
  namespace: <__namespace should be arbitrarily__>
spec:
  gatewayClassName: istio-ingressgateway
```

(Gateway for knative-local-gateway)

```yaml
kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: test-local-gateway
  namespace: <__namespace should be arbitrarily__>
spec:
  gatewayClassName: istio-knative-local-gateway
```

It seems that Gateway-API doc also say that users can omit the fields and reply on GatewayClass:

https://gateway-api.sigs.k8s.io/concepts/api-overview/#gateway
> As the Gateway spec captures user intent, it may not contain a complete specification for all attributes in the spec. For example, the user may omit fields such as addresses, ports, TLS settings. This allows the controller managing the GatewayClass to provide these settings for the user, resulting in a more portable spec. This behaviour will be made clear using the GatewayClass Status object.

[X] Networking
