### ISSUE TITLE
high memory utilisation of istio-proxy with long running websocket

### ISSUE THREAD

**Issue by chaudyg** [istio/istio#33661]
**Bug description**

High memory utilisation of the `istio-proxy` sidecar when proxying websocket traffic.

I spend some time trying to understand the root cause of this issue but I am now struggling to gather more information, and  I need some help 🙇 . 

**The memory utilisation of the proxy is significantly higher when proxying websocket traffic**

The request flow is the following
```
 [browser] --> [istio-gateway] --> [app (istio-injected)] --> [upstream svc (not injected)] 
```
The graph below shows the memory utilisation of the `istio-sidecar` container. One the left, all the websocket traffic is routed to a different service. On the right, the websocket connections are routed to the actual service.

* The proxy only handles a small amount of traffic (5-10 rps) and only around 100 websocket requests concurrently (it's browser traffic, one websocket per user). 
* The requests are long running. The connection can be open for hours (until the client closes the tab). 
* very small payload (a few bytes per minute per connection).
* The baseline memory utilisation is high because the application needs to reach a large number of upstream services (~10k). One important note.
* The memory utilisation of the istio gateway is flat, even if it's handling the same traffic.
* For websocket, the application only proxies through the request from the upstream to the downstream (using a go [reverseproxy](https://golang.org/pkg/net/http/httputil/#ReverseProxy.ServeHTTP))

![image](https://user-images.githubusercontent.com/7817963/123597377-8f87d280-d7f3-11eb-821b-260714df1b38.png)

I ran a 15 minutes pprof (but I am terrible at reading it 😓 ). Maybe this helps. 
[profile001.pdf](https://github.com/istio/istio/files/6724884/profile001.pdf) . Some notes on this pprof:
* I'am sending only websocket traffic to this pod (using a virtual service matching the upgrade=websocket header)
* Using a slightly modified sidecar (baseline memory usage is 1/2 the memory of the screenshot above).

[ ] Docs
[ ] Installation
[x] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
The memory utilisation of the sidecar should be closer to the memory utilisation of the gateway handling the same traffic (basically, flat).

**Steps to reproduce the bug**
Not sure yet. I can try to reproduce with a dummy installation.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
# istio
client version: 1.9.5
control plane version: 1.9.5
data plane version: 1.9.5 (11 proxies)
# k8s
Server Version: v1.17.17-gke.490
```
**How was Istio installed?**
Istio operator
```
  apiVersion: install.istio.io/v1alpha1
  kind: IstioOperator
  components:
    ingressGateways:
    - <one custom gateway>
    pilot:
      k8s:
        env:
        - name: PILOT_ENABLE_EDS_FOR_HEADLESS_SERVICES
          value: "true"
        - name: PILOT_ENABLE_FLOW_CONTROL
          value: "true"
  meshConfig:
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
        ISTIO_META_DNS_CAPTURE: "true"
  profile: minimal
  values:
    global:
      meshID: redacted
      multiCluster:
        clusterName: redacted
      network: redacted

```
**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
