### ISSUE TITLE
How to use envoyfilter to 'filter' different host ?

### ISSUE THREAD

**Issue by dearboll** [istio/istio#33694]
Hi, all, I have lot of domains(hosts) in my istio ingressgateway, but I need to forward some domains' request to a special module. Now I want use envoyfilter to deal with it, I except that the envoyfilter can filter the specific domain by proper configurations(such as 'myexample.com'). I edit the configuration yaml as below, but it does not work. 

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ef-1
  namespace: istio-system
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
          sni: myexample.com
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.lua
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
          inlineCode: |
            function envoy_on_request(request_handle)
              // process the request
              request_handle:logWarn(host)
            end
```
Use `istioctl pc listeners istio-ingressgateway-765c569d45-lvxd7.istio-system --port 8080 -o json` ,there is not any thing much the 'myexample.com'.   And When I annotation the 'sni:myexample.com' , all the request will be matched by the filter.

So, how can I specify the host/domain needed to be filtered ?

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
