### ISSUE TITLE
Envoy does not select HTTPS protocol when specified in ServiceEntry

### ISSUE THREAD

**Issue by msvechla** [istio/istio#33692]
**Bug description**

I have some issues intercepting outbound sidecar traffic to a `MESH_EXTERNAL` `HTTPS` service. I think the issue is that somehow envoy selects `TCP` as a protocol when it should in fact use `HTTPS`.

I created a ServiceEntry  with the following config:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: postman-echo
spec:
  hosts:
  - postman-echo.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
```

When I execute a request from a sidecar-injected pod like:

```
curl https://postman-echo.com
```

The request is successful, however, my custom envoy filter is not applied.
I can see the following in the logs, which lead me to the conclusion that envoy detects `TCP`  as protocol instead of `HTTPS`:

```
2021-06-29T10:12:16.863872Z     debug   envoy filter    original_dst: New connection accepted
2021-06-29T10:12:16.863942Z     debug   envoy filter    tls inspector: new connection accepted
2021-06-29T10:12:16.873353Z     debug   envoy filter    tls:onServerName(), requestedServerName: postman-echo.com
2021-06-29T10:12:16.873422Z     debug   envoy filter    [C1932] new tcp proxy session
2021-06-29T10:12:16.873445Z     debug   envoy filter    [C1932] Creating connection to cluster outbound|443||postman-echo.com
2021-06-29T10:12:16.963976Z     debug   envoy filter    [C1932] TCP:onUpstreamEvent(), requestedServerName: postman-echo.com
```

I tested the same setup a while ago on Istio `v1.9.x` where this worked. Also if I connect to the host via `http://` the `HTTP` protocol is selected correctly.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Envoy selects the `HTTPS` protocol based on the protocol set in the `ServiceEntry`.

**Steps to reproduce the bug**

Deploy an istio-proxy injected pod and use the `ServiceEntry` described above. Then check the logs for which protocol was selected.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
❯ istioctl version --remote
client version: 1.10.2
control plane version: 1.10.2
data plane version: 1.10.2 (2 proxies)
```

```
❯ kubectl version --short
Client Version: v1.20.3
Server Version: v1.19.8-eks-96780e
```

**How was Istio installed?**

Istio Operator:

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    accessLogFile: /dev/stdout
    accessLogFormat: '[%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(x-service-token)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%"\n'
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
  values:
    global:
      proxy:
        autoInject: disabled
```

**Environment where the bug was observed (cloud vendor, OS, etc)**

AWS EKS
