### ISSUE TITLE
holdApplicationUntilProxyStarts doesn't show in a profile dump 

### ISSUE THREAD

**Issue by zahidferz** [istio/istio#33702]
**Bug description**
 
 holdApplicationUntilProxyStarts doesn't show when you do a `istioctl profile dump --config-path meshConfig.defaultConfig`

**Affected product area (please put an X in all that apply)**

[ ] Docs
[] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X ] User Experience
[ ] Developer Infrastructure
[X ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[x ] Multi Control Plane

**Expected behavior**

holdApplicationUntilProxyStarts: true

**Steps to reproduce the bug**

```yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioOperator
spec:
  meshConfig:
    accessLogFile: ""
    defaultConfig:
      holdApplicationUntilProxyStarts: true
```
istioctl install -y -f istio-operator.yaml

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```bash
istioctl version --remote
client version: 1.8.5
control plane version: 1.8.5
data plane version: 1.8.5 (96 proxies), 1.7.4 (1 proxies)

kubectl version --short
Client Version: v1.19.8
Server Version: v1.19.8-eks-96780e

**How was Istio installed?**

istioctl install

**Environment where the bug was observed (cloud vendor, OS, etc)**

aws eks istio 1.8.5
