### ISSUE TITLE
expose redis to outside with istio sidecar?

### ISSUE THREAD

**Issue by calvinShan** [istio/istio#33728]
Hello, i want to expose redis to outside with istio, The server redis is well exposed via the Service

However, il does not work to expose the redis to outside with istio
export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
redis-cli -h $INGRESS_HOST -p 11337
Here is the code below, Do you have any ideals pls

Thans

```
kind: Deployment
metadata:
  namespace: redis
  name: azure-vote-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-back
  template:
    metadata:
      labels:
        app: azure-vote-back
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: azure-vote-back
        image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 6379
          protocol: TCP
          name: redis-port
---
apiVersion: v1
kind: Service
metadata:
  namespace: redis
  name: azure-vote-back
spec:
  ports:
  - name: redis-port
    port: 6379
    protocol: TCP
  selector:
    app: azure-vote-back
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: azure-vote-back
  namespace: redis
spec:
  hosts:
  - "*"
  gateways:
  - redis-gateway
  tcp:
  - route:
    - destination:
        host: azure-vote-back.redis.svc.cluster.local
        port:
          number: 6379
---
# voting-app-gateway.yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: redis-gateway
  namespace: redis
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 11337
      name: redis-port
      protocol: TCP
    hosts:
    - "*"
```
