### ISSUE TITLE
Unable to provide ipv6 address to `DNS` `ServiceEntry`

### ISSUE THREAD

**Issue by EItanya** [istio/istio#33735]
**Bug description**
Currently it is not possible to provide an `ipv6` address in a `DNS` `ServiceEntry`. This is happening for 2 reasons. Istio will accept a standard ipv6 address in the `DNS` `ServiceEntry`, however, envoy will then reject it, as per [this issue](https://github.com/envoyproxy/envoy/issues/10489). Unfortunately, when modifying the url to be properly formatted, istio will reject it.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
One of two things is expected here.
1. Istio accepts the ipv6 standard format `2001:db8:10a:c751::ffff:42ba` and transforms it to the envoy accepted version before sending it. `tcp://[2001:db8:10a:c751::ffff:42ba]`
2. Istio accepts the ipv6 in the envoy acceptable format and sends it directly `tcp://[2001:db8:10a:c751::ffff:42ba]`

**Steps to reproduce the bug**
First install istio `istioctl install`

There are 2 bugs to reproduce here.
1. istio rejecting a valid ipv6 url
```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-dns
spec:
  hosts:
  - foo.bar.com
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
  endpoints:
  - address: tcp://[2001:db8:10a:c751::ffff:42ba]
    ports:
      http: 8080
EOF
```
```
admission webhook "validation.istio.io" denied the request: configuration is invalid: endpoint address "tcp://[2001:db8:10a:c751::ffff:42ba]" is not a valid FQDN or an IP address
```
2. Istio accepts an ipv6 ip which is then rejected by envoy
```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-dns
spec:
  hosts:
  - foo.bar.com
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
  endpoints:
  - address: 2001:db8:10a:c751::ffff:42ba
    ports:
      http: 8080
EOF
```
```
kubectl logs -n istio-system deploy/istiod

2021-06-30T14:48:36.463225Z     warn    ads     ADS:CDS: ACK ERROR router~10.244.0.6~istio-ingressgateway-7d899b4c65-cqvwm.istio-system~istio-system.svc.cluster.local-1 Internal:Error adding/updating cluster(s) outbound|80||foo.bar.com: malformed url: tcp://2001:db8:10a:c751::ffff:42ba:8080
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
istioctl version --remote
client version: 1.10.2
control plane version: 1.10.2
data plane version: 1.10.2 (1 proxies)
```

```
kubectl version --short
Client Version: v1.21.1
Server Version: v1.18.2
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1
```

**How was Istio installed?**
`istioctl`
