### ISSUE TITLE
https redirect

### ISSUE THREAD

**Issue by jgournet** [istio/istio#33779]
**Describe the feature request**
Using this basic setup:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test
spec:
  gateways:
  - test
  hosts:
  - test.com
  http:
  - redirect:
      authority: testredirect.com
      redirectCode: 302
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: test
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - test.com
    port:
      name: http
      number: 80
      protocol: HTTP2
```
This creates a working redirect to "http://testredirect.com"   <= this is because our gateway listens on port 80, as we terminate SSL on the load balancer.
It would be great to have a flag somewhere (maybe in http.redirect, like http.redirect.protocol ? or add 2 flags: protocol and port ? or change "authority" to accept the scheme ?) to force istio to redirect to **https**

**Describe alternatives you've considered**
Tried creating a DestinationRule and ServiceEntry

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by maxbischoff** [comment]
In your gateway.servers[0] specify:

```
    tls:
      httpsRedirect: true
 ```
 
 that works for me.
 
 Full example:
 
 ```yaml
 apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: test
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - test.com
    port:
      name: http
      number: 80
      protocol: HTTP2
    tls:
      httpsRedirect: true
  - hosts:
    - test.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      # specify secrets here
 ```
 
 This is also in the first example in the docs here: https://istio.io/latest/docs/reference/config/networking/gateway/

**Comment by jgournet** [comment]
I know that it works great, but as mentioned:
> this is because our gateway listens on port 80, as we terminate SSL on the load balancer.

because of that, we can't put that tls.httpsRedirect where we need it, thus this request

**Comment by jgournet** [comment]
Update:
```
redirect:
  authority: "testredirect.com"
headers:
  response:
    set:
      location: "https://testredirect.com"
```
does the trick

It's not perfect as I can't "multi-hosts https redirects", like this:
```
  - match:
    - uri:
        exact: /url
    redirect:
      uri: /url/
```
as I don't "know" the host in this case (I admit: that redirect is silly, but I don't make the rules)

**Comment by dimatomp** [comment]
Here is one more simple (but a bit hacky) way to do it:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: redirect-preserve-https
spec:
  workloadSelector:
    labels:
      gateway: your-gateway
  configPatches:
  - applyTo:
      HTTP_ROUTE
    match:
      context: GATEWAY
      routeConfiguration:
        vhost:
          name: your.host.name.com:80
    patch:
      operation: MERGE
      value:
        redirect:
          httpsRedirect: true
```
