### ISSUE TITLE
Is it possiable to control source service or the destination service version in rate limit

### ISSUE THREAD

**Issue by garyyang85** [istio/istio#33827]
I am using rate limit since istio 1.1, now seems the rate limit usage mode is completely changed. Just have a quick test about demo envoy filter configuration, https://istio.io/v1.9/docs/tasks/policy-enforcement/rate-limit/, it works good. Here is more detail scenario.  I have below configuration to control source(productpage service) to destination(details v1) worked before. But now by envoy filter, seems it not easy to control the **source** service or the **destination service version**? Thanks for your kindly help.
```
spec:
  quotas:
    - name: requestcount.quota.istio-system
      maxAmount: 5000
      validDuration: 1s
      overrides:
        - dimensions:
            destination: details
            destinationVersion: v1
            source: productpage
          maxAmount: 1
          validDuration: 1s
```

----------
In istio 1.1, I can do rate limit simply, like above configuration. It will control the invoke from productpage service to details service v1 version,  1 time per second, if more than 1 invoke, it will return 429.   Now in istio 1.9, I cannot achieve such result by envoyfilter.Below configuration is just a control any invoke to "details" will be limited. I want to do more control, such as "source service" or "destination service version" like the result in isito 1.1

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
 labels:
   app: ratelimit-demo
 name: filter-ratelimit-actions
spec:
 configPatches:
   - applyTo: VIRTUAL_HOST
     match:
       context: SIDECAR_INBOUND
       routeConfiguration:
         vhost:
           name: inbound|http|9080
     patch:
       operation: MERGE
       value:
         rate_limits:
           - actions:
               - header_value_match:
                   descriptor_value: path
                   headers:
                     - name: :path
                       prefix_match: /
  workloadSelector:
    labels:
      app: details
```
