### ISSUE TITLE
`create-remote-secret` cmd return an error: error validating "STDIN"

### ISSUE THREAD

**Issue by kebe7jun** [istio/istio#33831]
**Bug description**
Following https://istio.io/latest/docs/setup/install/multicluster/multi-primary_multi-network/#enable-endpoint-discovery

```console
 ✘ kebe@Kebe-PC  ~  istioctl x create-remote-secret --context kind-cluster2 --name cluster2 | kubectl apply -f -
error: error validating "STDIN": error validating data: invalid object to validate; if you choose to ignore these errors, turn validation off with --validate=false
```

**Affected product area (please put an X in all that apply)**

[X] Installation

**Affected features (please put an X in all that apply)**

[X] Multi Cluster

**Steps to reproduce the bug**
I have a kubeconfig as following:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: gtewe
    server: https://127.0.0.1:35529
  name: kind-cluster1
- cluster:
    certificate-authority-data: gasd
    server: https://127.0.0.1:42747
  name: kind-cluster2
contexts:
- context:
    cluster: kind-cluster1
    user: kind-cluster1
  name: kind-cluster1
- context:
    cluster: kind-cluster2
    user: kind-cluster2
  name: kind-cluster2
current-context: kind-cluster1
kind: Config
preferences: {}
users:
- name: kind-cluster1
  user:
    client-certificate-data: rrrrrr
    client-key-data: xxxxxx
- name: kind-cluster2
  user:
    client-certificate-data: xxxxxx
    client-key-data: xxx
```

Run `istioctl x create-remote-secret --context kind-cluster2 --name cluster2 | kubectl apply -f -`

It was because `istioctl x create-remote-secret --context kind-cluster2 --name cluster2` print a waining message to stdout like: 
```
2021-07-05T09:48:17.063776Z	warn	Server in Kubeconfig is https://127.0.0.1:42747. This is likely not reachable from inside the cluster.
If you're using Kubernetes in Docker, pass --server with the container IP for the API Server.
```
