### ISSUE TITLE
Service manifest rendered for the gateway with same port number but different protocol (TCP & UDP) is incorrect

### ISSUE THREAD

**Issue by su225** [istio/istio#33841]
**Bug description**
I have the following `IstioOperator` manifest. As you can see the bookinfo-ingress has two ports - both 443, but different protocols. The use case is that I would like to have both TCP and UDP listeners exposed on that port so that for an HTTPS listener I can create a corresponding QUIC listener to support HTTP/3 (Context - https://github.com/istio/istio/pull/33817) 
```yml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-with-quic
  namespace: istio-system
spec:
  meshConfig:
    accessLogFile: /dev/stdout
  hub: localhost:5000
  tag: istio-quic
  profile: minimal
  components:
    ingressGateways:
    - name: bookinfo-ingress
      namespace: bookinfo
      enabled: true
      label:
        gateway: bookinfo
        quic: enabled
      k8s:
        service:
          type: LoadBalancer
          ports:
          - name: https-tcp
            port: 443
            targetPort: 8443
            protocol: TCP
          - name: http3-quic
            port: 443
            targetPort: 8443
            protocol: UDP
  values:
    global:
      imagePullPolicy: Always
      logging:
        level: "all:debug"
    pilot:
      env:
        PILOT_ENABLE_QUIC_LISTENERS: "true"
```

**Actual**: The corresponding service rendered
```yml
apiVersion: v1
kind: Service
metadata:
  annotations: null
  labels:
    app: istio-ingressgateway
    gateway: bookinfo
    install.operator.istio.io/owning-resource: unknown
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    quic: enabled
    release: istio
  name: bookinfo-ingress
  namespace: bookinfo
spec:
  ports:
  - name: http3-quic
    port: 443
    protocol: UDP
    targetPort: 8443
  - name: http3-quic
    port: 443
    protocol: UDP
    targetPort: 8443
  selector:
    app: istio-ingressgateway
    gateway: bookinfo
    istio: ingressgateway
    quic: enabled
  type: LoadBalancer
```

**Expected**: Expected service
```yml
apiVersion: v1
kind: Service
metadata:
  annotations: null
  labels:
    app: istio-ingressgateway
    gateway: bookinfo
    install.operator.istio.io/owning-resource: unknown
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    quic: enabled
    release: istio
  name: bookinfo-ingress
  namespace: bookinfo
spec:
  ports:
  - name: https-tcp
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: http3-quic
    port: 443
    protocol: UDP
    targetPort: 8443
  selector:
    app: istio-ingressgateway
    gateway: bookinfo
    istio: ingressgateway
    quic: enabled
  type: LoadBalancer
```

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.11-dev built from the master branch

**How was Istio installed?**
istioctl
