### ISSUE TITLE
Modifying the value of the workload entry spec.locality does not take effect

### ISSUE THREAD

**Issue by ChenglongGao327** [istio/istio#33868]
**Bug description**
Modifying the value of the workload entry spec.locality  and then view envoy's config_dump configuration does not take effect
still the previous value

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
The expected behavior should be synchronized to envoy when the value of the workload entry locality is modified

**Steps to reproduce the bug**
1.create k8s service 
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: client
  name: client
  namespace: default
spec:
  ports:
  - name: http
    port: 7777
    protocol: TCP
  selector:
    name: client
  sessionAffinity: None
  type: ClusterIP
```

2.create workload entry 
```
apiVersion: networking.istio.io/v1beta1
kind: WorkloadEntry
metadata:
  name: client-we
  namespace: default
spec:
  address: 172.16.0.51
  labels:
    name: client
  locality: cn-north-7/cn-north-7c               // only modify this value
  ports:
    http: 6666
```
3. only modify the value of client-we spec.locality
```kubectl edit we client-we ```

4. view envoy's config_dump configuration
    the outbound(outbound|7777||client.default.svc.cluster.local) locality.region/zone is not update
```
kubectl exec -it productpage-v1-596598f447-8vmt9  -c istio-proxy -- curl -X POST 127.0.0.1:15000/clusters?format=json > config_dump.json;vim config_dump.json
```
```
 {
   "name": "outbound|7777||client.default.svc.cluster.local",
   "added_via_api": true,
   "host_statuses": [
    {
     "address": {
      "socket_address": {
       "address": "172.16.0.51",
       "port_value": 7777
      }
     },
     "stats": [
      {
       "name": "cx_connect_fail"
      },
      {
       "name": "cx_total"
      },
      {
       "name": "rq_error"
      },
      {
       "name": "rq_success"
      },
      {
       "name": "rq_timeout"
      },
      {
       "name": "rq_total"
      },
      {
       "type": "GAUGE",
       "name": "cx_active"
      },
      {
       "type": "GAUGE",
       "name": "rq_active"
      }
     ],
     "health_status": {
      "eds_health_status": "HEALTHY"
     },
     "weight": 1,
     "locality": {                      
      "region": "cn-north-7",      // this value is not update
      "zone": "cn-north-7c"
     }
    }
   ],
   "circuit_breakers": {
    "thresholds": [
     {
      "max_connections": 4294967295,
      "max_pending_requests": 4294967295,
      "max_requests": 4294967295,
     },
     {
      "priority": "HIGH",
      "max_connections": 1024,
      "max_pending_requests": 1024,
      "max_requests": 1024,
      "max_retries": 3
     }
    ]
   },
   "observability_name": "outbound|7777||client.default.svc.cluster.local"
  },
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
k8s version : v1.17.5
istio version :  v1.10.2

**How was Istio installed?**
istioctl install --set profile=demo -y

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by ChenglongGao327** [comment]
Misoperation

**Comment by ChenglongGao327** [comment]
Misoperation

**Comment by howardjohn** [comment]
The locality field you are looking at does not control routing information, nor can it be dynamically changed since its a part of bootstrap.

**Comment by vikaschoudhary16** [comment]
> The locality field you are looking at does not control routing information, nor can it be dynamically changed since its a part of bootstrap.

it is part of the bootstrap for the envoy only, right? Issue is about endpoint locality. Actually I too encountered this issue. In my env, I can see that SE has locality for the endpoints but if i check envoy configs, it is missing.. does not get updated even after istio restarts. Actually I dug further and verified that istiod is acutally sending updated endpoint, but some emvoy is not getting updated.

ServiceEntry endpoint:
```
   endpoints:
    - address: 10.255.10.194
      labels:
        security.istio.io/tlsMode: istio
        xcp.tetrate.io/serviceType: localGateway
      locality: us-east1
      ports:
```

Sidecar config:
```
root@http-client-v1-7c5b6cbb78-j6vwq:/# curl -s localhost:15000/clusters | grep echo.tetrate.io | grep region
outbound|80||echo.tetrate.io::10.255.10.194:15443::region::
outbound|80||echo.tetrate.io::172.18.255.165:15443::region::us-east1
outbound|80||echo.tetrate.io::172.18.255.175:15443::region::us-east1
outbound|80||echo.tetrate.io::172.18.255.185:15443::region::us-east1
```
After adding some custom logging in istiod, verified that istiod is doing its job fine and could see a `envoy.config.endpoint.v3.ClusterLoadAssignment` object being pushed with all the 4 endpoints in the us-east1 locality.
