### ISSUE TITLE
Orphan routes remains since deleted kubernetes ingress

### ISSUE THREAD

**Issue by tpai** [istio/istio#33901]
**Bug description**

I expose my application at 80/443 port with Kubernetes ingress, then I go check the route, it works as expected.

```console
$ istioctl proxy-config routes istio-ingressgateway-xxx.istio-system

NAME                                                                                                       DOMAINS                 MATCH                  VIRTUAL SERVICE
http.80                                                                                                    httpbin.example.com     /*                     httpbin-example-com-k8s-ingress-istio-autogenerated-k8s-ingress.foo
https.443.https-443-ingress-k8s-ingress-foo-0.k8s-ingress-istio-autogenerated-k8s-ingress.istio-system     httpbin.example.com     /*                     httpbin-example-com-k8s-ingress-istio-autogenerated-k8s-ingress.foo
                                                                                                           *                       /stats/prometheus*
                                                                                                           *                       /healthz/ready*
```

But after I delete the Kubernetes ingress, the routes still exist.

```console
$ kubectl delete -f httpbin-ingress.yaml
```

`httpbin-ingress.yaml`

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
  namespace: foo
  name: istio
spec:
  controller: istio.io/ingress-controller
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: foo
  name: k8s-ingress
spec:
  ingressClassName: istio
  tls:
    - hosts:
      - httpbin.example.com
      secretName: https-secret
  rules:
  - host: httpbin.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: httpbin
          servicePort: 8000

```

Is there any ways to delete the routes manually?

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

The routes should be gone.

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```shell
# istioctl version
client version: 1.10.2
control plane version: 1.10.2
data plane version: 1.10.2 (2 proxies)

# kubectl version
Client Version: v1.19.7
Server Version: v1.18.14
```

**How was Istio installed?**

```shell
curl -L https://istio.io/downloadIstio | sh -
istioctl operator init
istioctl install --set profile=default -y
```

**Environment where the bug was observed (cloud vendor, OS, etc)**

AKS 1.18
