### ISSUE TITLE
Sidecar is not injected as first container when `holdApplicationUntilProxyStarts` is set

### ISSUE THREAD

**Issue by thib92** [istio/istio#33911]
**Bug description**

Thanks to #24737, we can set `holdApplicationUntilProxyStarts` to inject a `postStart` hook in the sidecar container to wait for the Envoy proxy to be ready, and then unblock the actual entrypoints of the other containers to run, fixing issues where a race condition would have the main container start trying to connect to external services before the Envoy sidecar proxy is ready (creating "Connection Refused" errors).

This works because `kubelet` calls each `postStart` hook synchronously, one by one, in the order of the containers in the list of the `Pod` spec. **This means that the sidecar should be the first container of the pod.**

#24737 implemented [`injectContainers`](https://github.com/istio/istio/pull/24737/files#diff-3658c8df7815d0014a39c664de6ee52d83c4e85d6f57d2eadfc829c008e87bf1R814-R836) that doesn't just append the sidecar container, but actually inserts it in first instead of last.

However, looking at the main branch of the repo, this function does not exist anymore.

Looking at [the history for the file](https://github.com/istio/istio/commits/master?before=c4af985cbef0639403a5ceb0bb4cdfe64f0eabb1+35&branch=master&path%5B%5D=pkg&path%5B%5D=kube&path%5B%5D=inject&path%5B%5D=inject.go), it seems like #26596 introduced the regression.

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

The sidecar should be injected in first in the container list, under the condition that `holdApplicationUntilProxyStarts` is set. Otherwise there are unexpected behaviors explained in #24737 (`kubectl exec` would default to the first container, aka the proxy).

**Steps to reproduce the bug**

* Create a pod with sidecar injection enabled
* Notice that the sidecar is not in first place in the containers list

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

Kubernetes:
```
Client Version: v1.19.7
Server Version: v1.16.15-eks-cf75c9
```

Istio: 1.9.1

**How was Istio installed?**

Helm charts

**Environment where the bug was observed (cloud vendor, OS, etc)**

AWS EKS

**Comment by howardjohn** [comment]
using the config:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: hello
        tier: backend
        track: stable
      annotations:
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": false }'
    spec:
      containers:
      - name: hello
        image: "fake.docker.io/google-samples/hello-go-gke:1.0"
        ports:
        - name: http
          containerPort: 80
        livenessProbe:
          httpGet:
            port: http
        readinessProbe:
          httpGet:
            port: 3333
```

I see it injected first. Can you describe more how you reproduced this?

**Comment by thib92** [comment]
Interesting. I am installing Istio through Helm. Here is my `values.yaml` file for `istiod`:

```yaml
meshConfig:
  defaultConfig:
    holdApplicationUntilProxyStarts: true
```

After applying the update, I annotated my namespace to enable sidecar injection, and deleted one by one my pods to have the injection on new pods, and it was injected last.

Let me try with a `proxy.istio.io/config` annotation and see if it works.

Did you try with `1.9.1`?
