### ISSUE TITLE
Question: Preserve original src ip

### ISSUE THREAD

**Issue by keyboardfann** [istio/istio#33925]
From https://github.com/istio/istio/pull/28457 , the Preserve original src ip has merge to istio. 
But when I send traffic through AWS internal NLB and try to get original src ip  from dest pod, always get the istio ingress pod ip.
Is there anything wrong or missing

Workflow
![image](https://user-images.githubusercontent.com/1110451/125018848-7959fc00-e0a8-11eb-9714-a2b9e269d3b6.png)

ELB target group use ip target group and enable proxy protocol v2
![image](https://user-images.githubusercontent.com/1110451/125019022-c63dd280-e0a8-11eb-8da5-ef58b32689a0.png)

Istio 1.9.1 config
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  hub: gcr.io/istio-release
  tag: 1.9.1
  revision: 1-9-1
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
  components:
    egressGateways:
    - name: istio-egressgateway
      enabled: true
    ingressGateways:    
	- name: internal-istio-ingressgateway
      enabled: true
      k8s:
        env:
           - name: ISTIO_META_ROUTER_MODE
             value: sni-dnat
        hpaSpec:
          maxReplicas: 5
          metrics:
            - resource:
                name: cpu
                targetAverageUtilization: 80
              type: Resource
            - resource:
                name: memory
                targetAverageUtilization: 80
              type: Resource
          minReplicas: 2
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: internal-istio-ingressgateway
        overlays:
          - kind: HorizontalPodAutoscaler
            name: internal-istio-ingressgateway
            patches:
              - path: metadata.labels.app
                value: internal-istio-ingressgateway
              - path: metadata.labels.istio
                value: internal-ingressgateway
              - path: spec.scaleTargetRef.name
                value: internal-istio-ingressgateway
          - kind: HorizontalPodAutoscaler
            name: internal-istio-ingressgateway
            patches:
              - path: metadata.labels.app
                value: internal-istio-ingressgateway
              - path: metadata.labels.istio
                value: internal-ingressgateway
              - path: spec.scaleTargetRef.name
                value: internal-istio-ingressgateway
          - kind: Deployment
            name: internal-istio-ingressgateway
            patches:
              - path: metadata.labels.app
                value: internal-istio-ingressgateway
              - path: metadata.labels.istio
                value: internal-ingressgateway
              - path: spec.selector.matchLabels.app
                value: internal-istio-ingressgateway
              - path: spec.selector.matchLabels.istio
                value: internal-ingressgateway
              - path: spec.template.metadata.labels.app
                value: internal-istio-ingressgateway
              - path: spec.template.metadata.labels.istio
                value: internal-ingressgateway
          - kind: Service
            name: internal-istio-ingressgateway
            patches:
              - path: metadata.labels.app
                value: internal-istio-ingressgateway
              - path: metadata.labels.istio
                value: internal-ingressgateway
              - path: spec.selector.app
                value: internal-istio-ingressgateway
              - path: spec.selector.istio
                value: internal-ingressgateway
              - path: spec.type
                value: LoadBalancer
          - kind: PodDisruptionBudget
            name: internal-istio-ingressgateway
            patches:
              - path: metadata.labels.app
                value: internal-istio-ingressgateway
              - path: metadata.labels.istio
                value: internal-ingressgateway
              - path: spec.selector.matchLabels.app
                value: internal-istio-ingressgateway
              - path: spec.selector.matchLabels.istio
                value: internal-ingressgateway
        resources:
          limits:
            cpu: 2000m
            memory: 1500Mi
          requests:
            cpu: 300m
            memory: 256Mi
        service:
          externalTrafficPolicy: Local
          ports:
            - name: http2
              port: 80
              protocol: TCP
              targetPort: 8080
            - name: https
              port: 443
              protocol: TCP
              targetPort: 8443
            ## Custom port ##
            - name: pgbouncer
              port: 5432
              protocol: TCP
            - name: internalsystem-use
              port: 9999
              protocol: TCP
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-name: "internalistioingress"
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-type: "external"
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
          service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
          service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
        strategy:
          rollingUpdate:
            maxSurge: 100%
            maxUnavailable: 25%
```

EnvoyFilter
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ingressgateway-settings
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          skip_xff_append: false
          use_remote_address: true
          xff_num_trusted_hops: 1
```

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: internalingress-proxy-protocol
  namespace: istio-system
spec:
  configPatches:
  - applyTo: LISTENER
    patch:
      operation: MERGE
      value:
        listener_filters:
        - name: envoy.filters.listener.proxy_protocol
        - name: envoy.filters.listener.tls_inspector
  workloadSelector:
    labels:
      istio: internal-ingressgateway
```

pgbouncer deployment
```
apiVersion: apps/v1
kind: Deployment
...
...
      annotations:
        sidecar.istio.io/interceptionMode: TPROXY
...
...
```

# Test1 # 
centos
```
[root@centos-84b59fcb69-mjbqd /]# psql -h xxxxx -U postgres -d postgres
Password for user postgres: 
psql (10.17, server )
Type "help" for help.

postgres=>
```

pgbouncer log , always show internal ingress pod ip . not source ip.
```
2021-07-08 07:46:48.981 UTC [1] LOG C-0x5642cef80e20: postgres/postgres@10.2.6.207:60467 login attempt: db=postgres user=postgres tls=no
```

# Test2 
Use the example for test
https://github.com/hzxuzhonghu/istio-demo/tree/main/istiocon-2021/tcp

Inner cluster communcation, pod to pod, can get the right Source IP.
without sidecar.istio.io/interceptionMode: TPROXY
```
[root@centos-84b59fcb69-mjbqd /]#  curl httpbin.default:8000/ip
{
  "origin": "127.0.0.1"
}
```

with sidecar.istio.io/interceptionMode: TPROXY
```
[root@centos-84b59fcb69-mjbqd /]#  curl httpbin.default:8000/ip
{
  "origin": "10.2.6.77"
}
```

# Test 3
Use the example for test
https://github.com/hzxuzhonghu/istio-demo/tree/main/istiocon-2021/tcp

Testing through Internal ingress gateway
gateway.yaml
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-tcp-gateway
spec:
  selector:
    istio: internal-ingressgateway
  servers:
    - port:
        number: 9999
        name: tcp
        protocol: TCP
      hosts:
      - "test.nxd.net"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-tcp
spec:
  hosts:
  - "test.nxd.net"
  gateways:
  - httpbin-tcp-gateway
  tcp:
    - match:
      - port: 9999
      route:
      - destination:
           host: httpbin
           port:
              number: 8000
```

Test, will show internal ingress pod ip.... not the src ip.
```
[root@centos-84b59fcb69-mjbqd /]# curl test.nxd.net:9999/ip
{
  "origin": "10.2.4.87"
}
[root@centos-84b59fcb69-mjbqd /]# curl test.nxd.net:9999/ip
{
  "origin": "10.2.4.87"
}
[root@centos-84b59fcb69-mjbqd /]# curl test.nxd.net:9999/ip
{
  "origin": "10.2.4.87"
}
[root@centos-84b59fcb69-mjbqd /]# curl test.nxd.net:9999/ip
{
  "origin": "10.2.4.87"
}
[root@centos-84b59fcb69-mjbqd /]# curl test.nxd.net:9999/ip
{
  "origin": "10.2.4.87"
}
[root@centos-84b59fcb69-mjbqd /]# curl test.nxd.net:9999/ip
{
  "origin": "10.2.4.87"
}
[root@centos-84b59fcb69-mjbqd /]# curl test.nxd.net:9999/ip
{
  "origin": "10.2.6.207"
}
[root@centos-84b59fcb69-mjbqd /]# curl test.nxd.net:9999/ip
{
  "origin": "10.2.6.207"
}
[root@centos-84b59fcb69-mjbqd /]# curl test.nxd.net:9999/ip
{
  "origin": "10.2.4.87"
}
[root@centos-84b59fcb69-mjbqd /]# curl test.nxd.net:9999/ip
{
  "origin": "10.2.6.207"
}
```

**Comment by keyboardfann** [comment]
@hzxuzhonghu Do you have any thinking about why this happens? Any mistake config?

**Comment by hzxuzhonghu** [comment]
Does istio ingress gateway see the original source ip? Otherwise you need other way to make this

**Comment by keyboardfann** [comment]
Hi @hzxuzhonghu,
   Thanks for your time, the following is the information about logs and test.

# information #
centos pod (10.2.6.77) 
two internal ingress pod( 10.2.6.205 , 10.2.6.9)
pgbouncer pod(10.2.6.105)

Test 
centos pod -> internal NLB -> internal ingress gateway -> pgbouncer pod

istio internal ingress gateway log
```
[2021-07-19T09:46:27.529Z] "- - -" 0 - - - "-" 97 10 3 - "-" "-" "-" "-" "10.2.6.105:5432" outbound|5432||sre-pgbouncer-svc.monitoring.svc.cluster.local 10.2.6.9:33604 10.2.6.158:5432 10.2.6.77:60908 - -
```

pgbouncer log
```
2021-07-19 09:46:27.531 UTC [1] LOG C-0x5642cef888a0: postgres/postgres@10.2.6.9:43035 login attempt: db=postgres user=postgres tls=no
2021-07-19 09:46:28.403 UTC [1] LOG C-0x5642cef9a350: postgres/postgres@10.2.6.9:43027 login attempt: db=postgres user=postgres tls=no
```

**Comment by hzxuzhonghu** [comment]
ingress gateway need to enable proxy protocol transport socket

the backend pod need to enable proxy protocol filter

**Comment by keyboardfann** [comment]
I try to apply the internalingress-proxy-protocol-Upstream.yaml but it will cause service doesn't work. Seems it will conflict with internalingress-proxy-protocol, is there config wrong?

internalingress-proxy-protocol.yaml
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: internalingress-proxy-protocol
  namespace: istio-system
spec:
  configPatches:
  - applyTo: LISTENER
    patch:
      operation: MERGE
      value:
        listener_filters:
        - name: envoy.filters.listener.proxy_protocol
        - name: envoy.filters.listener.tls_inspector
  workloadSelector:
    labels:
      istio: internal-ingressgateway
```

internalingress-proxy-protocol-Upstream.yaml
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: internalingress-proxy-protocol-Upstream
  namespace: istio-system
spec:
  configPatches:
  - applyTo: CLUSTER
    patch:
      operation: MERGE
      value:
        transport_socket:
          name: envoy.transport_sockets.upstream_proxy_protocol
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.proxy_protocol.v3.ProxyProtocolUpstreamTransport
            config:
              version: V2
            transport_socket:
              name: "envoy.transport_sockets.raw_buffer"
  workloadSelector:
    labels:
      istio: internal-ingressgateway
```

pgbouncer log
```
2021-07-22 07:25:52.915 UTC [1] LOG C-0x555db8cb2060: (nodb)/(nouser)@10.2.4.184:38649 closing because: client sent partial pkt in startup phase (age=0s)
2021-07-22 07:25:52.915 UTC [1] WARNING C-0x555db8cb2060: (nodb)/(nouser)@10.2.4.184:38649 pooler error: client sent partial pkt in startup phase
2021-07-22 07:25:58.614 UTC [1] LOG C-0x555db8cb2060: (nodb)/(nouser)@10.2.4.184:37505 closing because: client sent partial pkt in startup phase (age=0s)
2021-07-22 07:25:58.614 UTC [1] WARNING C-0x555db8cb2060: (nodb)/(nouser)@10.2.4.184:37505 pooler error: client sent partial pkt in startup phase
2021-07-22 07:26:02.266 UTC [1] LOG C-0x555db8cb2060: (nodb)/(nouser)@10.2.6.224:37087 closing because: client sent partial pkt in startup phase (age=0s)
2021-07-22 07:26:02.266 UTC [1] WARNING C-0x555db8cb2060: (nodb)/(nouser)@10.2.6.224:37087 pooler error: client sent partial pkt in startup phase
2021-07-22 07:26:02.275 UTC [1] LOG C-0x555db8cb2060: (nodb)/(nouser)@10.2.6.224:37411 closing because: client sent partial pkt in startup phase (age=0s)
2021-07-22 07:26:02.275 UTC [1] WARNING C-0x555db8cb2060: (nodb)/(nouser)@10.2.6.224:37411 pooler error: client sent partial pkt in startup phase
2021-07-22 07:26:02.933 UTC [1] LOG C-0x555db8cb2060: (nodb)/(nouser)@10.2.6.224:48689 closing because: client sent partial pkt in startup phase (age=0s)
2021-07-22 07:26:02.933 UTC [1] WARNING C-0x555db8cb2060: (nodb)/(nouser)@10.2.6.224:48689 pooler error: client sent partial pkt in startup phase
2021-07-22 07:26:02.939 UTC [1] LOG C-0x555db8cb2060: (nodb)/(nouser)@10.2.6.224:58767 closing because: client sent partial pkt in startup phase (age=0s)
2021-07-22 07:26:02.939 UTC [1] WARNING C-0x555db8cb2060: (nodb)/(nouser)@10.2.6.224:58767 pooler error: client sent partial pkt in startup phase
```
