### ISSUE TITLE
toleration for grafana components

### ISSUE THREAD

**Issue by calvinShan** [istio/istio#33972]
Hello,

We have added taint for one node and we want to install all the pods about istio in this node.

In this way, we have configured toleration for IstioOperator to be placed in this node. after deploying the cluster,
only the pod istio-ingressgateway is placed in that node. 

However, the other pods are in other nodes, 
- grafana
- istio-tracing
- istiod
- kiali
- prometheus

so, how to configure toleration for the pods of addcomponents and istiod istio-tracing pls? 

Here is my code:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-control-plane
spec:
  # Use the default profile as the base
  # More details at: https://istio.io/docs/setup/additional-setup/config-profiles/
  profile: default
  # Enable the addons that we will want to use
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          serviceAnnotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
          service:
            type: LoadBalancer
            loadBalancerIP: x.x.x.x
          tolerations:
          - key: "service"
            operator: "Equal"
            value: "istio"
            effect: "NoSchedule"
  addonComponents:
    grafana:
      enabled: true
    prometheus:
      enabled: true
    tracing:
      enabled: true
    kiali:
      enabled: true
  values:
    global:
      # Ensure that the Istio pods are only scheduled to run on Linux nodes
      defaultNodeSelector:
        kubernetes.azure.com/mode: system
    kiali:
      dashboard:
        auth:
          strategy: anonymous
```
