### ISSUE TITLE
ssl for redis with istio

### ISSUE THREAD

**Issue by calvinShan** [istio/istio#34004]
Hi,

I want to active ssl for redis whic is exposed by istio gateway. 
The redis is well deployed to outside by adding the custom port in istio-ingressgateway svc

```
kubectl edit svc istio-ingressgateway -n istio-system
- name: redis-port
  nodePort: 31402
  port: 11337
  protocol: TCP
  targetPort: 6379
```
However, the ssl is not correctly actived. How could we confgiure gateway to active SSL for redis pls
Here is my code:

```
# voting-app-gateway.yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: redis-gateway
  namespace: redis
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 11337
      name: tls
      protocol: TLS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    - "*"
```

**Comment by hobbytp** [comment]
@calvinShan  several points need to check:
1. Does your ingress gateway deployment have "containerPort" 6379? if not, add it or change it to 31402 and add it.
2. Have you tried "protocol: TCP", if not, please try it.
3. Have you tried to add a VS  to mapping the port to 6379? if not, add it.

**Comment by calvinShan** [comment]
> @calvinShan several points need to check:
> 
> 1. Does your ingress gateway deployment have "containerPort" 6379? if not, add it or change it to 31402 and add it.
> 2. Have you tried "protocol: TCP", if not, please try it.
> 3. Have you tried to add a VS  to mapping the port to 6379? if not, add it.

Here is all my code, the container port is 6379. After this, we can still connect the redis by relis-cli -h $url -p $port directly.
So how can we assure that ssl works?

```
      containers:
      - name: iot-redis-back
        image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
        ports:
        - containerPort: 6379
          protocol: TCP
          name: redis-port
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: iot-redis-back
  namespace: redis
spec:
  hosts:
  - "*"
  gateways:
  - redis-gateway
  tcp:
  - match:
    - port: 11337
    route:
    - destination:
        host: iot-redis-back.redis.svc.cluster.local
        port:
          number: 6379
---
# voting-app-gateway.yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: redis-gateway
  namespace: redis
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 11337
      name: redis-port
      protocol: TCP
    hosts:
    - "*"
```
