### ISSUE TITLE
DNS Proxying with address auto allocation not working in IPv6 cluster

### ISSUE THREAD

**Issue by emike922** [istio/istio#34002]
**Bug description**
The DNS proxying and address auto allocation feature does not work in IPv6 environments

Basic KIND IPv6 cluster (https://kind.sigs.k8s.io/docs/user/configuration/#ip-family):
```
$ kubectl exec sleep-79cbd6fdbb-wlsp5 --container sleep -- curl --silent --verbose --max-time 5 http://nginx.example.com/
* Resolving timed out after 5513 milliseconds
* stopped the pause stream!
* Closing connection 0
command terminated with exit code 28
```

Another IPv6 cluster (not KIND):
```
$ kubectl exec sleep-6bfbbcf6ff-479x5 --container sleep -- curl --silent --verbose --max-time 5 http://nginx.example.com/
* Could not resolve host: nginx.example.com
* Closing connection 0
command terminated with exit code 6
```

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Same behavior as in IPv4 clusters (status 200)

**Steps to reproduce the bug**
1. Deploy sleep pod with DNS capture and DNS auto-allocate enabled:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sleep
  name: sleep
spec:
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      annotations:
        proxy.istio.io/config: |
          proxyMetadata:
            ISTIO_META_DNS_CAPTURE: "true"
            ISTIO_META_DNS_AUTO_ALLOCATE: "true"
        sidecar.istio.io/inject: "true"
      labels:
        app: sleep
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - command:
        - /bin/sleep
        - 3650d
        image: pstauffer/curl
        name: sleep
```

2. Deploy nginx in the same namespace but w/o sidecar:
```
kubectl create deployment nginx --image=nginx
kubectl expose deployment nginx --port=80
```

3. Create SE to resolve nginx.example.com to local nginx service:
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: nginx
spec:
  hosts:
  - nginx.example.com
  ports:
  - name: http
    number: 80
    protocol: HTTP
  resolution: DNS
  endpoints:
  - address: nginx
```

4. Curl nginx.example.com from sleep container:
```
kubectl exec sleep-55f56c69b9-drstk --container sleep -- curl --silent --verbose --max-time 5 http://nginx.example.com/
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Istio 1.10.2
Kubernetes 1.21.2 and 1.20.4

**How was Istio installed?**
helm install --namespace istio-system --create-namespace istio-base manifests/charts/base
helm install --namespace istio-system istiod manifests/charts/istio-control/istio-discovery

**Environment where the bug was observed (cloud vendor, OS, etc)**
KIND and local KaaS cluster
