### ISSUE TITLE
empty regex cause envoy warnings

### ISSUE THREAD

**Issue by kebe7jun** [istio/istio#34065]
**Bug description**

Envoy output the following logs:
```
2021-07-15T03:52:44.189014Z	warning	envoy config	gRPC config for type.googleapis.com/envoy.config.route.v3.RouteConfiguration rejected: Proto constraint validation failed (RouteConfigurationValidationError.VirtualHosts[i]: ["embedded message failed validation"] | caused by VirtualHostValidationError.Routes[i]: ["embedded message failed validation"] | caused by RouteValidationError.Match: ["embedded message failed validation"] | caused by RouteMatchValidationError.Headers[i]: ["embedded message failed validation"] | caused by HeaderMatcherValidationError.SafeRegexMatch: ["embedded message failed validation"] | caused by RegexMatcherValidationError.Regex: ["value length must be at least " '\x01' " runes"]): name: "80"
```

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Steps to reproduce the bug**
Virtual Service psec:
```yaml
  spec:
    hosts:
    - s1.default.svc.cluster.local
    http:
    - match:
      - method:
          regex: ""
        name: 80_default
      route:
      - destination:
          host: s1.default.svc.cluster.local
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.9
