### ISSUE TITLE
Invalid cipherSuites lead to NACKs

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#34084]
```
ADS:LDS: ACK ERROR istio-ingressgateway-588b68dbb6-l89ss.istio-system-8 Internal:Error adding/updating listener(s) 0.0.0.0_8443: Failed to initialize cipher suites fake. The following ciphers were rejected when tried individually: fake
```

```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: echo
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      cipherSuites:
      - fake
      credentialName: istio-ingressgateway-certs
      mode: SIMPLE
```

Depending on order of the Gateway and secret creation, sometimes it is the SDS that NACKs, not LDS.

cc @lambdai @mandarjog
