### ISSUE TITLE
istio-proxy container reports wrong information in logs

### ISSUE THREAD

**Issue by zioproto** [istio/istio#34108]
When the `istio-proxy` container receives an invalid configuration from Pilot the message printed in the logs is:

`config not received from Pilot (is Pilot running?)`

This information is wrong, because Pilot is running, and the configuration is received but it is invalid.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

It should be logged that the configuration received is invalid.

**Steps to reproduce the bug**

Istio version 

```
client version: 1.8.0
control plane version: 1.10.2-asm.3
data plane version: 1.10.2-asm.3 (2 proxies)
image: gcr.io/gke-release/asm/proxyv2:1.10.2-asm.3`
```
GKE version:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.9-gke.1900", GitCommit:"008fd38bf3dc201bebdd4fe26edf9bf87478309a", GitTreeState:"clean", BuildDate:"2021-04-14T09:22:08Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}
```
Apply the following manifest

```
---
apiVersion: v1
kind: Namespace
metadata:
  name: echoserver
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: echoserver-v1
  namespace: echoserver
spec:
  gateways:
  - gateway-echoserver
  hosts:
  - '*'
  tcp:
  - match:
    - port: 27017
    route:
    - destination:
        host: echoserver0
        port:
          number: 27017
  - match:
    - port: 27018
    route:
    - destination:
        host: echoserver1
        port:
          number: 27018
  - match:
    - port: 27019
    route:
    - destination:
        host: echoserver2
        port:
          number: 27019
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: gateway-echoserver
  namespace: echoserver
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: echoserver0
      number: 27017
      protocol: TCP
  - hosts:
    - '*'
    port:
      name: echoserver1
      number: 27018
      protocol: TCP
  - hosts:
    - '*'
    port:
      name: echoserver2
      number: 27019
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    networking.gke.io/load-balancer-type: "Internal"
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: unknown
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: ingressgateway
    istio.io/rev: asm-1102-3
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.10.2-asm.3
    release: istio
  name: istio-ingressgateway-internal2
  namespace: istio-system
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: name1
    port: 27017
    protocol: TCP
    targetPort: 27017
  - name: name2
    port: 27018
    protocol: TCP
    targetPort: 27017
  - name: bug-port
    port: 27019
    protocol: TCP
    targetPort: 27017
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  sessionAffinity: None
  type: LoadBalancer
```

As soon as you apply this you will get:

```
istio-ingressgateway-5666754dfd-klc5j istio-proxy 2021-07-16T13:45:18.852377Z   warning envoy config    gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_27017: duplicate listener 0.0.0.0_27017 found
```

This is expected, because the above manifest created a Duplicate listener. Envoy will reject this change and will continue to work with the previous configuration. However this is very dangerous because look what happens when you restart envoy:

Now delete the istio-ingressgateway pods like `kubectl delete pods -l app=istio-ingressgateway`

When the new pods try to come up you get:

```
istio-ingressgateway-5666754dfd-rd78n istio-proxy 2021-07-16T13:49:45.479942Z   warning envoy config    gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_27017: duplicate listener 0.0.0.0_27017 found
istio-ingressgateway-5666754dfd-rd78n istio-proxy
istio-ingressgateway-5666754dfd-rd78n istio-proxy 2021-07-16T13:49:45.743251Z   warning envoy config    gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_27017: duplicate listener 0.0.0.0_27017 found
istio-ingressgateway-5666754dfd-rd78n istio-proxy
istio-ingressgateway-5666754dfd-rd78n istio-proxy 2021-07-16T13:49:46.515614Z   warn    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 2 successful, 0 rejected; lds updates: 0 successful, 2 rejected
istio-ingressgateway-5666754dfd-rd78n istio-proxy 2021-07-16T13:49:48.514891Z   warn    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 2 successful, 0 rejected; lds updates: 0 successful, 2 rejected
istio-ingressgateway-5666754dfd-rd78n istio-proxy 2021-07-16T13:49:50.514771Z   warn    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 2 successful, 0 rejected; lds updates: 0 successful, 2 rejected
istio-ingressgateway-5666754dfd-rd78n istio-proxy 2021-07-16T13:49:52.514224Z   warn    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 2 successful, 0 rejected; lds updates: 0 successful, 2 rejected
```

The above is not a **warning** but should be an **error** because prevents the Pods from working completely.

Pilot is running and it is sending a wrong configuration so the message `config not received from Pilot (is Pilot running?)` is totally wrong.

**How was Istio installed?**

`install_asm` script
