### ISSUE TITLE
Domain expansion for the KGateway's NamedAddress value 

### ISSUE THREAD

**Issue by nak3** [istio/istio#34127]
**Bug description**

- KGateway supports the `istio-ingressgateway` in spec.addresses.value but does not support `istio-ingressgateway.istio-system` or `istio-ingressgateway.istio-sytem.svc`.
- It seems that the `istio-ingressgateway.istio-system` and `istio-ingressgateway.istio-system.svc` are not supported for the ServiceEntry but then `istio-ingressgateway` should not be supported?

[X] Networking

**Expected behavior**

- Make it clear that the rule of the expansion.

**Steps to reproduce the bug**

#### 1. Install Gateway API

Just install KGateway as https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/

#### 2. Update `spec.addresses`

- Change the Gateway to:

```
apiVersion: networking.x-k8s.io/v1alpha1
kind: Gateway
metadata:
  name: gateway
  namespace: istio-system
spec:
  addresses:
  - type: NamedAddress
    value: istio-ingressgateway.istio-system
  gatewayClassName: istio
  listeners:
  - hostname: "*"
    port: 80
    protocol: HTTP
    routes:
      namespaces:
        from: All
      selector:
        matchLabels:
          selected: "yes"
      kind: HTTPRoute
```

This does not work as:

```
    - lastTransitionTime: "2021-07-18T10:33:22Z"
      message: 'failed to assign to any requested addresses: hostname "istio-ingressgateway.istio-system"
        not found'
```

#### 3. Update `spec.addresses`

```
apiVersion: networking.x-k8s.io/v1alpha1
kind: Gateway
metadata:
  name: gateway
  namespace: istio-system
spec:
  addresses:
  - type: NamedAddress
    value: istio-ingressgateway
  gatewayClassName: istio
  listeners:
  - hostname: "*"
    port: 80
    protocol: HTTP
    routes:
      namespaces:
        from: All
      selector:
        matchLabels:
          selected: "yes"
      kind: HTTPRoute
```

This does work as:

```
    - lastTransitionTime: "2021-07-18T10:33:39Z"
      message: Gateway valid, assigned to service(s) istio-ingressgateway.istio-system.svc.cluster.local:80
```

**Version**

```
$ istioctl version
client version: 1.11-alpha.6591c8112b4fe18728af60d356b42371c8e240b4
control plane version: 1.11-alpha.6591c8112b4fe18728af60d356b42371c8e240b4
data plane version: 1.11-alpha.6591c8112b4fe18728af60d356b42371c8e240b4 (1 proxies)
```

**How was Istio installed?**

```
istioctl install -y
```

**Comment by howardjohn** [comment]
> Make it clear that the rule of the expansion.

Just want to clarify, this is just a documentation issue? We are fine with the current behavior?

**Comment by nak3** [comment]
KGateway cannot support the ServiceEntry host without dot(`.`), but I guess it is alright?
If it is no problem, I think the current behavior is fine.

e.g. The following KGateway does not work.

```
apiVersion: networking.x-k8s.io/v1alpha1
kind: Gateway
metadata:
  name: gateway
  namespace: istio-system
spec:
  addresses:
  - type: NamedAddress
    value: my-gateway-svc
  gatewayClassName: istio
  listeners:
  - hostname: "*"
    port: 80
    protocol: HTTP
    routes:
      namespaces:
        from: All
      kind: HTTPRoute
```

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: example
spec:
  hosts:
  - my-gateway-svc
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
```
