### ISSUE TITLE
Recommended RBAC for namespace admins? (or non-cluster-admins in general)

### ISSUE THREAD

**Issue by agilgur5** [istio/istio#34130]
**Describe the feature request**
There is currently no official recommendation from Istio in the docs of what RBAC to apply for namespace admins (or, in general, non-cluster-admins).
Of course, every cluster and every user is different, but I would think there is some recommendation of what a namespace admin generally _should_ and _shouldn't_ be able to do with Istio based on some generic assumptions.

Perhaps a guide with what RBAC to use for different use-cases and assumptions could be optimal.

There are some small references in the existing docs around this, but no complete, elaborated documentation:
- https://istio.io/latest/docs/examples/microservices-istio/setup-kubernetes-cluster/ -- this leaves out `install.istio.io` for instance
    - this also lists `rbac.istio.io` which, as far as I know, [no longer exists](https://istio.io/latest/blog/2019/v1beta1-authorization-policy/) and was replaced with `security.istio.io`
- https://istio.io/latest/docs/ops/best-practices/security/#restrict-gateway-creation-privileges -- this says to restrict `Gateway` creation to cluster-admins only

**Describe alternatives you've considered**
Applying my own RBAC and iterating on it based on my own assumptions.

E.g. I started by taking a partial copy of the [Operator's RBAC](https://github.com/istio/istio/blob/39e6e3922878f292e89c8267aaa3c64cff3f6d38/manifests/charts/istio-operator/files/gen-operator.yaml#L26) for namespace admins:
```yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aggregate:istio:admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups:
      - authentication.istio.io
      - config.istio.io
      - install.istio.io
      - networking.istio.io
      - security.istio.io
    resources:
      - '*'
    verbs:
      - '*'
```

Then pruning it down, removing `install.istio.io`, only allowing `view` on the `Gateway` resource in `networking`, etc.

Maybe I'm missing other API Groups? There isn't really a cohesive list of resources and API Groups in the docs either as far as I could tell, which makes crafting RBAC even harder

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**
