### ISSUE TITLE
Configure distributed tracing of sampling But it didn't work

### ISSUE THREAD

**Issue by zhengtianchi** [istio/istio#34161]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
First question:
I have modified the tracing sampling rate configuration of the meshConfig in istio configmap and restarted the istiod pod, which will not make the sampling rate configuration take effect. 
Second question :
I used proxy.istio.io/config annotation for trace Settings and restarted the corresponding POD, this will also not make the sample rate configuration work.

**Affected product area (please put an X in all that apply)**

[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
I have used two ways to modify the sampling rate of the tracing. The first way is to modify the global meshConfig configuration, and the second way is to modify the annotation in the deployment to add proxy.istio.io/config.  I want both to be able to modify the sample rate and run at the sample rate I want.

**Steps to reproduce the bug**
1. setup mesh
```yaml
istioctl install -f my-config.yaml

my-config.yaml:
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  hub: registry.xxxxx.com
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
  values:
    global:
      imagePullPolicy: IfNotPresent
  components:
    egressGateways:
    - name: istio-egressgateway
      enabled: true
```
2. modify configmap of istio
```yaml
kubectl edit configmap istio -n isito-system
.........
data:
  mesh: |-
    accessLogFile: /dev/stdout
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      proxyMetadata: {}
      tracing:
        sampling: 50  # add this
        zipkin:
          address: zipkin.istio-system:9411
    enablePrometheusMerge: true
    enableTracing: true
    rootNamespace: istio-system
    trustDomain: cluster.local
.........
```
3. restart the istiod pod
```shell
kubectl delete po istiod-xxxxxxx-xxxx -n istio-system
```
4. after the restarted istiod pod  is running, i check the config in pilot container
```yaml
kubectl exec istiod-xxxx-xxx -n istio-system -- cat /etc/istio/config/mesh

accessLogFile: /dev/stdout
defaultConfig:
  discoveryAddress: istiod.istio-system.svc:15012
  proxyMetadata: {}
  tracing:
    sampling: 50
    zipkin:
      address: zipkin.istio-system:9411
enablePrometheusMerge: true
enableTracing: true
rootNamespace: istio-system
```
The sample rate configuration has already appeared in the mesh configuration file
5. deploy two test service: httpbin and sleep
```shell
kubectl create ns httpbin
kubectl create ns sleep
kubectl label namespace httpbin istio-injection=enabled
kubectl label namespace sleepistio-injection=enabled
kubectl apply -f  ./sample/httpbin/httpbin.yaml
kubectl apply -f ./sample/sleep/sleep.yaml
```
6. Use the script to make a request to HttpBin from the sleep loop, and then look at Jaeger
```shell
#!/bin/bash
sum=0
for ((i=1; i<=300; i++))
do
    kubectl exec sleep-64d7d56698-79mch -n sleep -c sleep -- curl -s  httpbin.httpbin:8000/headers
    ((sum += i))
done
echo "over"
```
![image](https://user-images.githubusercontent.com/45617395/126266861-4f630990-5d67-4f46-8031-0c2d889a5900.png)

In Jaeger, instead of sampling at a 50% sampling rate, it's sampling at almost 1% of the default
This appears to be the actual sample rate configuration that is not read by the MESHCONFIG
So, I tried a different approach:
7.Modify the environment variable in the istiod Deployment: PILOT_TRACE_SAMPLING
```
The original environment variable
        - name: PILOT_TRACE_SAMPLING
          value: "1"
The changed environment variable
        - name: PILOT_TRACE_SAMPLING
          value: "50"
```
I then run the above script again and look at the report on Jaeger to see that the sampling rate is finally in effect.

Is the current reading of the actual sampling rate set by istio based on the istiod environment variable? This is my first question. I wonder if other configuration items in meshConfig will be modified as well as the sampling rate and will not take effect dynamically. Because I wanted to be able to directly modify the parameters of MeshConfig in ISTIO ConfigMap, but I encountered these problems when modifying the sampling rate.

8. I used proxy.istio.io/config annotation for trace Settings
```yaml
kubectl edit deploy httpbin -n httpbin

apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: httpbin
spec:
  selector:
    matchLabels:
      app: httpbin
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        proxy.istio.io/config: |
          tracing:
            sampling: 1.0    # I set sampling to 1.0 , current sampling in istiod ENV is 50.0
            customTags:
              custom_tag:
                literal:
                  value: "Test Tag"   # set a Tag to test Whether it take effect
            zipkin:
              address: zipkin.istio-system:9411
      creationTimestamp: null
      labels:
        app: httpbin
        version: v1
    spec:
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccount: httpbin
      serviceAccountName: httpbin
      terminationGracePeriodSeconds: 30
```
9. Executing the script again, making repeated requests to HttpBin, and then checking out the tracing on Jaeger
![image](https://user-images.githubusercontent.com/45617395/126271025-0b3407da-c91e-41c5-9a9a-43e9058b310d.png)

"Test Tag" appears in custom_tag. This looks like the proxy configuration in POD is in effect. But when I run the test script again and look at Jaeger's tracing, I find that tracing appears at a very high frequency, similar to the previous sampling rate of 50%, instead of sampling at the 1% sampling rate I configured.

As for the change of sampling rate, I don't know whether it is a current bug of ISTIO or something wrong with my configuration, and I am curious whether the remaining configuration can be updated by modifying ISTIO ConfigMap, or the remaining configuration cannot be hot-updated just like the sampling rate.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
istio version: 1.9.2
kubernetes version: 1.18.2

**How was Istio installed?**
installed istio with istioctl 
```yaml
istioctl install -f my-config.yaml

my-config.yaml:
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  hub: registry.xxxxx.com
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
  values:
    global:
      imagePullPolicy: IfNotPresent
  components:
    egressGateways:
    - name: istio-egressgateway
      enabled: true
```

**Environment where the bug was observed (cloud vendor, OS, etc)**
Personal server with centos7.5.1804

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by chenbodeng719** [comment]
same problem...

**Comment by mugioka** [comment]
same bug occurred

**Comment by dellnoantechnp** [comment]
istio 1.23.2  same problem.....

**Comment by dellnoantechnp** [comment]
istio 1.24.2  also same problem ....

**Comment by zirain** [comment]
For all supported release, please move to use Telemetry API instead of the tradditional way.

**Comment by tylermichael** [comment]
@zirain I'm unable to configure tracing via the Telemetry API for Waypoints. The [comment](https://github.com/istio/istio/issues/53481#issuecomment-2401178489) here seems to suggest that something might be wrong here as well. Here's another [comment](https://github.com/istio/istio/issues/52590#issuecomment-2485001137) that also supports this.

I'm using this Telemetry config. As an aside, if I use any value besides what's listed [here](https://github.com/istio/api/blob/master/mesh/v1alpha1/proxy.pb.go#L416) for `providers[].name`, no tracing config makes it's way into the waypoints running config. I first tried to use opentelemetry as that is mentioned to be supported in many other locations in the documentation, but came across this problem. Using "datadog" here also doesn't work, but I was relying on the default tracing provider config for datadog that you get when using the `meshConfig` method.

```yaml
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: default
  namespace: default
spec:
  # I've tried with and without the targetRefs
  targetRefs:
  - kind: Gateway
    name: waypoint
    group: gateway.networking.k8s.io
  tracing:
  - providers:
    - name: "datadog" # the default 'datadog' extension provider
    randomSamplingPercentage: 100
EOF
```

In my helm `values.yaml` file when I use this, it partially works when I make a request that goes through an NGINX ingress, but I'm still unable to control the sampling rate at a global level for pod -> pod requests; only from within my services code.

```yaml
istiod:
  profile: ambient
  ambient:
    enabled: true
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: "100" # none of these values help
      tracingServiceName: "CANONICAL_NAME_ONLY"
      terminationDrainDuration: 30s
      proxyHeaders:
        forwardedClientCert: SANITIZE
        server:
          disabled: true
        requestId:
          disabled: true
        attemptCount:
          disabled: true
        envoyDebugHeaders:
          disabled: true
        metadataExchangeHeaders:
          mode: IN_MESH
      proxyMetadata:
        DD_REMOTE_CONFIGURATION_ENABLED: "false"
        DD_INSTRUMENTATION_TELEMETRY_ENABLED: "false"
        DD_TRACE_SAMPLE_RATE: "1.0" # none of these values help
  global:
    pilot:
      traceSampling: "100" # none of these values help
    proxy:
      tracer: datadog # NOTE: you have to set this value for tracing to happen in the waypoint. I was unable to get anything else to work except for this
      sampling: "100" # none of these values help
      holdApplicationUntilProxyStarts: true
```

Making a request in my cluster, I'm seeing a sampling rate of "X-Datadog-Sampling-Priority: -1", which explicitly drops the trace.
```bash
$ curl httpbin.default.svc.cluster.local:8000/dump/request
GET /dump/request HTTP/1.1
Host: httpbin.default.svc.cluster.local:8000
Accept: */*
Traceparent: 00-6786e1f1000000002abd90a429216fe7-2abd90a429216fe7-00
Tracestate: dd=s:-1;p:2abd90a429216fe7
User-Agent: curl/8.5.0
X-Datadog-Parent-Id: 3079776754930380775
X-Datadog-Sampling-Priority: -1
X-Datadog-Tags: _dd.p.tid=6786e1f100000000
X-Datadog-Trace-Id: 3079776754930380775
X-Forwarded-Proto: http
```

I'm no Istio expert, but it feels like there are varying degrees of support for configuring tracing for sidecars or waypoints via Telemetry or `meshConfig` and the documentation doesn't acknowledge this.
