### ISSUE TITLE
Istio Not adding VirtualService.spec.hosts fields to generated routeConfig

### ISSUE THREAD

**Issue by Buffer0x7cd** [istio/istio#34171]
**Bug description**
Istio Not adding VirtualService.spec.hosts fields to generated routeConfig

[ x] Networking
[ x] User Experience

**Expected behavior**
Istio should generate routeConfig that matches all of the virtualHosts provided in VirtualService.spec.hosts section
**Steps to reproduce the bug**

Hey , I am hitting an issue while trying to use VirtualService to route traffic to different subesets of backend. For the Context the VirtualService looks something like this
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata: {namespace: istio, name: service-A}
spec:
  hosts:
    - service-A
    - service-A.v2
    - service-A.v3
  http:
  # a rule per registration
  - match:
      - headers: {":authority": {exact: service-A.v2}}
    route:
    - destination: {host: service-A, subset: v2}
      weight: 100
  - match:
      - headers: {":authority": {exact: service-A.v3}}
    route:
    - destination: {host: service-A, subset: v3}
      weight: 100

```.   
And the DestionationRule look like something this
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata: {namespace: istio, name: service-A}
spec:
  host: service-A # k8s service name
  subsets:
  - name: v2
    labels: {version: v2}
  - name: v3
    labels: {version: v3}

For the endpoint discovery we have a single k8s service that contain all backends irrespective  of the version they are running

```
apiVersion: v1
kind: Service
metadata: {namespace: istio, name: service-A}
spec:
  selector: {service: service-A}
  ports: [{protocol: TCP, port: 8888}]

```

 We were assuming that we can hit the the service name with specific host header and that will route the traffic to correct subset. For example
`curl service-A:8080 -H "Host: service-A.v3" ------> Backend from subest v3 `

While trying to debug the issue, I noticed that in the route config of envoy there is an entry like below for listener bound to 172.x.x.x:8888 (172.x.x.x is service IP of service-A service).
```
"virtualHosts": [
 {
 "name": "service-A.istio.svc.cluster.local:8888",
 "domains": [
 "service-A.istio.svc.cluster.local:8888",
"172.x.x.x:8888". 
 ]
```
     
I was assuming that the extra headers in VirtualService.pec.Hosts like service-A.v2 and service-A.v3 will also be added on the above routeConfig but that doesn’t seem to be case. Due to this any request send to above service with these specific host headers fail.
After searching the routeConfig for service-A.v2 or v3 and found a route config block port 80 (which i found weird since the service is  listening on port 80 ) something like this
```
Port: 80
"virtualHosts": [
 {
 "name": "service-A.v2",
 "domains": [
 "service-A.v2",
 ]}]```.      

I tried using this route config by trying to do curl like below
`curl localhost:80 -H "Host: service-A.v2"`
```
But i am getting connection refused on port 80 which seems a bit weird since i can see a listener is bounded in envoy to address `0.0.0.0:80`

So for TLDR, there are two questions
1.   Is it possible to add additional hostname entries in VirtualService.spec.hosts  that doesn’t exist in k8s service registry ( example service-A.V2 and still add them to some existing  routeConfig block in Envoy , I was assuming this can be done by adding those extra hostnames inside Virtualservice.spec.hosts but this doesn’t seem to be case
2.   Is there some additional config require to access listener on port 80 since i can see a listener on 0.0.0.0:80 but i can’t access them and getting connection refused
```


Istio Version: 1.10.2

**Comment by howardjohn** [comment]
@ramaraochavali this seems related to https://github.com/istio/istio/pull/34137

@Buffer0x7cd does it work if you make 3 virtual services (on for each hostname) instead of a single one?

**Comment by Buffer0x7cd** [comment]
I didn’t tried with creating 3 Virtual services but i did tried with creating 3 K8s services (one for each version) and it seem to work since now we have theree different routeConfig objects binded to 3 different Listeners  objects ( created on serviceIP:Port). The issue with this approach is that K8s does not allow putting dots in service names ( and out clients use the format of Service.Version , So we want to support clients calling services in Service-Name.Version format).

I will try with creating 3 different VirtualService and update here.

**Comment by keymone** [comment]
@howardjohn no, that doesn't work either, curling on port 80 (to hit route 80) with correct Host header results in "503 NC cluster_not_found"

related questions:

1. is there a way to stop istio from generating anything related to k8s Service object (listener on 8888, routes, etc)
2. why is our virtual service intercepted on port 80 and can this be changed?

**Comment by ramaraochavali** [comment]
I have added a test case https://github.com/istio/istio/pull/34208 - It seems to generate routes correctly. Not sure why you are getting routes under "80".  Is it possible for you to validate against master?

**Comment by Buffer0x7cd** [comment]
@ramaraochavali We have deployed the current system using master branch so not sure what you meant with  `Is it possible for you to validate against master?`

**Comment by ramaraochavali** [comment]
Istio Version: 1.10.2 - I see this. So I thought you are running 1.10.2? I meant running master build https://github.com/istio/istio?

**Comment by Buffer0x7cd** [comment]
ohh sure, will try with master. We got some partial success after switching to multiple VS , but we ran into a different issue from there
https://github.com/istio/istio/issues/34213

**Comment by keymone** [comment]
to be more specific, we had to specify `port: {number: 8888}` in our VS/route/destination for istio to correctly pick outbound cluster port, previouysly it was trying to send traffic to outbound port 80 which didn't exist

**Comment by ramaraochavali** [comment]
I am not sure where "80" route is coming from. Are you able to reproduce this in master? 

@hzxuzhonghu Any idea why 80 is coming? I am not able to reproduce it master but istio 1.10.2 has it seems. Was any of your recent fixes would have fixed this?

**Comment by keymone** [comment]
could this be due to the fact that we're not using helm to install istio and instead generate and apply the manifest manually using `istioctl menifest generate`?

i see istio-ingressgateway service mentioning port 80:

```
---
apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  annotations:
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
    istio.io/rev: default
    install.operator.istio.io/owning-resource: unknown
    operator.istio.io/component: "IngressGateways"
spec:
  type: LoadBalancer
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  ports:
    -
      name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    -
      name: http2
      port: 80
      protocol: TCP
      targetPort: 8080
    -
      name: https
      port: 443
      protocol: TCP
      targetPort: 8443
```

**Comment by Buffer0x7cd** [comment]
@ramaraochavali  @hzxuzhonghu Considering even if we have port 80 listener created due to ingress-gateway, we are still not sure why we can see the routeConfig generated by VirtulalService binded on port 80
Our VirtualService looks something like this 

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata: {namespace:istio, name: service-A-V2}
spec:
  hosts: [service-A.V2]
  http:
  - route:
    - destination: {host: service-A, subset:V2, port: {number: 8888}}
      weight: 100


apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata: {namespace: istio, name: service-A-destination}
spec:
  host: service-A # k8s service name
  subsets:
  - name: V2
    labels: {version:  V2}
  - name: V3
    labels: {version: V3}
    
 apiVersion: v1
kind: Service
metadata: {namespace: istio, name: service-A}
spec:
  selector: {service: service-A}
  ports: [{protocol: TCP, port: 8888}]
```

Since the port for the k8s service is 8888 we assumed that the generated routeConfig for `service-A.V2` will be binded to listener on port 8888, but we can see that this routeConfig to also being attached to the Listener on port 80
