### ISSUE TITLE
upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268435612:SSL routines:OPENSSL_internal:HTTP_REQUES

### ISSUE THREAD

**Issue by Buffer0x7cd** [istio/istio#34212]
While trying to debug https://github.com/istio/istio/issues/34171, We decided to experiment with creating multiple VirtualHosts  entry (https://github.com/istio/istio/issues/34171#issuecomment-883652451) After applying the changes we noticed that the requests to endpoints service-A.V2 and service-A.v3 are successful from the pods of service-A.V3 container, but when we tried to curl the service-A.V3 endpoint from the v2 pods it fails with the following error

`upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268435612:SSL routines:OPENSSL_internal:HTTP_REQUES`

```
From pod with label V3 
service-A.V3$.   curl -v -H "Host:  service-A.V3"   1.0.0.1/testing # Returns 200 
service-A.V3$.   curl -v -H "Host:  service-A.V2"   1.0.0.1/testing # Returns 200 


From Pod with label V2
service-A.V2$.   curl -v -H "Host:  service-A.V2"  1.0.0.1/testing # Returns 200 
service-A.V2$.   curl -v -H "Host:  service-A.V2"  1.0.0.1/testing # Returns 503 with  message
 
upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268435612:SSL routines:OPENSSL_internal:HTTP_REQUES
```

The configurations for Service, DestinationRule and VirtualServices Looks like this

```
apiVersion: v1
kind: Service
metadata: {namespace: istio, name: service-A}
spec:
  selector: {service: service-A}
  ports: [{protocol: TCP, port: 8888}]

```

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata: {namespace: istio, name: service-A-destination}
spec:
  host: service-A # k8s service name
  subsets:
  - name: V2
    labels: {version:  V2}
  - name: V3
    labels: {version: V3}
```

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata: {namespace:istio, name: service-A-V2}
spec:
  hosts: [service-A.V2]
  http:
  - route:
    - destination: {host: service-A, subset:V2, port: {number: 8888}}
      weight: 100

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata: {namespace:istio, name: service-A-V3}
spec:
  hosts: [service-A.V3]
  http:
  - route:
    - destination: {host: service-A, subset:V3, port: {number: 8888}}
      weight: 100
```
