### ISSUE TITLE
Istio 1.10 local rate limit EnvoyFilter validation error - unknown field "listener"

### ISSUE THREAD

**Issue by kenthua** [istio/istio#34219]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
Istio 1.10+ local rate limit EnvoyFilter does not pass validation.

```
k apply -f /tmp/envoyfilter.yaml 
error: error validating "/tmp/envoyfilter.yaml": error validating data: ValidationError(EnvoyFilter.spec.configPatches[0]): unknown field "listener" in io.istio.networking.v1alpha3.EnvoyFilter.spec.configPatches; if you choose to ignore these errors, turn validation off with --validate=false
```

envoyfilter.yaml as noted in [docs](https://istio.io/latest/docs/tasks/policy-enforcement/rate-limit/
)
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-local-ratelimit-svc
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: productpage
  configPatches:
    - applyTo: HTTP_FILTER
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter
              token_bucket:
                max_tokens: 10
                tokens_per_fill: 10
                fill_interval: 60s
              filter_enabled:
                runtime_key: local_rate_limit_enabled
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              filter_enforced:
                runtime_key: local_rate_limit_enforced
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              response_headers_to_add:
                - append: false
                  header:
                    key: x-local-rate-limit
                    value: 'true'
```

[X ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Istio 1.9.6
```
k apply -f /tmp/envoyfilter.yaml 
envoyfilter.networking.istio.io/filter-local-ratelimit-svc created
```

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
./istioctl version --remote
client version: 1.10.0
control plane version: 1.10.0
data plane version: 1.10.0 (1 proxies)
```

1.10.0 - 1.10.3 are all affected

```
k version --short
Client Version: v1.21.2
Server Version: v1.19.9-gke.1900
```

**How was Istio installed?**
```
./istioctl install -y
```

**Environment where the bug was observed (cloud vendor, OS, etc)**
GKE, ubuntu

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by bianpengyuan** [comment]
I think there is no need to include this block:

```
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
```
