### ISSUE TITLE
Istio virtual service with * host doesnt get picked up and so gets 404

### ISSUE THREAD

**Issue by arunpmohan** [istio/istio#34223]
Istio version : 1.9.x

I have 2 virtual services binded to a gateway .

**Gateway** 

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: shared-istio-gateway
spec:
  selector:
    app: arunsps
  servers:
  - hosts:
    - '*'
    port:
      name: http-80
      number: 80
      protocol: HTTP
  - hosts:
    - '*'
    port:
      name: https-443
      number: 443
      protocol: HTTPS
    tls:
      credentialName: my-credential
      mode: SIMPLE
```

**First Virtual Service**

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: firstvs
spec:
  gateways:
  - shared-istio-gateway
  hosts:
  - site1-samson.dyn.demo.com
  http:
  - match:
    - uri:
        prefix: /test/monitoring
    route:
    - destination:
        host: my-sample-service
        port:
          number: 8080

```

**Second virtual service.**
```

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name:  secondvs
spec:
  gateways:
  - shared-istio-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /soap/demo
    route:
    - destination:
        host: my-sample2-service
        port:
          number: 8080
```

Notice that the first virtual service has my actual fqdn while second one is *. Now if i do a curl request on fqdn

if i do curl -vk https://site1-samson.dyn.demo.com/soap/demo ...
then i  get 404.

Why is this happening ?  Now if i remove the specific hostname from firstvirtual service then everything works. 

**Logs**
`
[2021-07-21T19:32:33.685Z] "GET /soap/demo HTTP/2" 404 NR route_not_found - "-" 0 0 0 - "10.139.155.152" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0" "d616c534-9c99-9620-a86f-82fcac491e21" "site1-samson.dyn.demo.com" "-" - - 172.18.162.147:443 10.139.155.152:39782 site1-samson.dyn.demo.com -`
