### ISSUE TITLE
Kubernetes httpGet liveness/readiness probes fail if Istio-proxy has to follow redirect

### ISSUE THREAD

**Issue by SeanWallace** [istio/istio#34238]
**Bug description**

After upgrading from 1.9.5 to 1.10.3 I've noticed that I have some pods that are in crash loop backoff and the thing they all have in common is their readiness/liveness probes point to an endpoint that returns a 301 redirect.

They have the following readiness/liveness probes:

```
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: apache
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
```

Pod description:

```
Readiness probe failed: Get "http://172.16.147.130:15020/app-health/apache/readyz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

Proxy logs:

```
2021-07-22T00:53:39.186449Z	error	Request to probe app failed: Get "https://www.mydomain.com/new/location": context deadline exceeded (Client.Timeout exceeded while awaiting headers), original URL path = /app-health/apache/readyz
app URL path = /
```

So, it appears that proxy is attempting to follow this redirect however from the pod in question the networking policies prohibit that traffic, so it would never be able to.

The Kubernetes spec does say:

> Any code greater than or equal to 200 and less than 400 indicates success. Any other code indicates failure.

So a 301 would be a perfectly acceptable return code however proxy is failing with a `HTTP/1.1 500 Internal Server Error` when curl'd directly.

I'm sure this is extreme edge case and really it's super easy to work around but in the event it's unexpected or unwanted behavior I thought it worth the bug report.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

In previous versions pods that returned 301 at their probes did not fail via proxy when queried by Kubernetes.

**Steps to reproduce the bug**

At a minimum create a pod that always returns a 301 via HTTP GET. Set the liveness/readiness probe as `httpGet` and I believe proxy will always return a 500 (will verify with time).

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
$ istioctl version
client version: 1.10.3
control plane version: 1.10.3
data plane version: 1.10.3 (125 proxies), 1.9.5 (2 proxies)
```
(Note, the 2 proxies are the ones that have this behavior and therefore Kubernetes won't kill since the new version won't become ready.)

```
$ kubectl version --short
Client Version: v1.21.2
Server Version: v1.20.5
```

**How was Istio installed?**

istioctl

**Environment where the bug was observed (cloud vendor, OS, etc)**

Custom Kubernetes cluster.

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
IIRC the k8s probe actually follows the redirect, it won't just succeed in the initial 301. https://github.com/istio/istio/issues/29468 is similar issue.

I am a bit surprised the behavior changed between 1.9 and 1.10

**Comment by SeanWallace** [comment]
Best I can tell it's not Kubernetes trying to follow the redirect since the probe has to flow through the proxy. Perhaps I'm mistaken on that though.

**Comment by howardjohn** [comment]
Oh I know why. It's trying to send the request to a legit external address. This is probably a horrible idea to ever do, and led to a CVE in k8s that is still unfixed (SSRF).

So it sounds like maybe we are actually following the redirect and it blows up since the redirect goes external?Need to investigate more

**Comment by howardjohn** [comment]
> Best I can tell it's not Kubernetes trying to follow the redirect since the probe has to flow through the proxy. Perhaps I'm mistaken on that though.

I meant in general without istio involved, it would follow the redirect not just check 301

**Comment by SeanWallace** [comment]
> Oh I know why. It's trying to send the request to a legit external address. This is probably a horrible idea to ever do, and led to a CVE in k8s that is still unfixed (SSRF).
> 
> So it sounds like maybe we are actually following the redirect and it blows up since the redirect goes external?Need to investigate more

Yes, specifically in this case the redirect is external of the cluster entirely.

**Comment by howardjohn** [comment]
Thanks for the report! https://github.com/istio/istio/pull/34291 should fix this

**Comment by tamipangadil** [comment]
I have similar issue. I couldn't get my deployment probes to work even after adding `Sidecar` config to bind my `istio-proxy` to `lo` network. I'm running out of option and the Istio document recommendation seems not working. Any updates on this please?

**Comment by howardjohn** [comment]
@tamipangadil the Sidecar change does not work inthis case; https://github.com/istio/istio/pull/34291 is required.

**Comment by tamipangadil** [comment]
Thanks @howardjohn . When do you think you can merge your PR? I'm downgrading back to 1.9 now.

**Comment by howardjohn** [comment]
Hopefully soon... is your probe using redirects though? If not, it should work.

**Comment by tamipangadil** [comment]
I'm not sure about the redirects. I set our deployment probes like this:
```
livenessProbe:
  tcpSocket:
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 2
  successThreshold: 1
  failureThreshold: 5
readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 150
  periodSeconds: 5
  successThreshold: 3
  failureThreshold: 3
```

The readiness probe should get the status from application like `http://127.0.0.1:8080/health` path.
