### ISSUE TITLE
Configure traffic to external HTTPS proxy (Squid) by the domain name of a Kubernetes service

### ISSUE THREAD

**Issue by MaciekLeks** [istio/istio#34245]
**Bug description**

I've followed the entire subject of [Using an External HTTPS Proxy][1] that pointed out that it's a VIP based example not k8s service approach. But in my case Squid is accessible via k8s service and I would like to use FQDN not IP address.

I've changed the config removing `addresses` part: 

Squid Istio Service Entry:
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: proxy
spec:
  hosts:
  - squid.external.svc.cluster.local
  location: MESH_EXTERNAL
  exportTo: 
  - "."
  ports:
  - number: 3128
    name: tcp
    protocol: TCP
```

Mesh External Squid parts in `external` ns:

Squid Pod:
```
  ports:
  - containerPort: 3128
    name: http
    protocol: TCP
```
Squid k8s Service:
```
  ports:
  - name: http
    port: 3128
    protocol: TCP
    targetPort: http
```

Curling from `sleep` cointaner:
```
HTTPS_PROXY=http://squid.external.svc.cluster.local:3128 curl https://en.wikipedia.org/wiki/Main_Page
```

gives the result on the sleep sidecar:
```
[2021-07-21T06:46:23.938Z] "CONNECT - HTTP/1.1" 404 NR route_not_found - "-" 0 0 0 - "-" "curl/7.77.0-DEV" "424a0870-af92-4a59-a3af-c8dc91b31512" "en.wikipedia.org:443" "-" - - 192.168.101.185:3128 10.10.2.8:39744 - -
```
where 192.168.101.185 is the squid service IP.

Envoy error says that there is no route, but it found the service. I'm not assuming it's an istio bug, but who knows. What is missing and what is wrong? I appreciate any help or suggestion.

  [1]: https://istio.io/latest/docs/tasks/traffic-management/egress/http-proxy/

[x] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Proper tunneling over https proxy from Istio managed PODs. From non istio mamaged PODs works OK.

**Steps to reproduce the bug**
1. Follow the steps [Deploy an HTTPS proxy](https://istio.io/latest/docs/tasks/traffic-management/egress/http-proxy/#deploy-an-https-proxy)
2. Create Squid service
```
kubectl apply -f - <<EOF
apiVersion: v1
kind: Service
metadata:
  labels:
    app: squid
  name: squid
  namespace: external
spec:
  ports:
  - name: http
    port: 3128
    protocol: TCP
    targetPort: 3128
  selector:
    app: squid    
EOF
```

3. Let's assume your test POD is in `test` namespace and it's managed by istio. Create Service Entry in test ns.
```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: proxy
spec:
  hosts:
  - squid.external.svc.cluster.local
  location: MESH_EXTERNAL
  exportTo: 
  - "."
  ports:
  - number: 3128
    name: http
    protocol: TCP 
EOF
``` 

4. Enter the POD container (e.g. sleep) in the test ns and run:
```
HTTPS_PROXY=http://common-squid.external.svc.cluster.local:3128 curl https://en.wikipedia.org/wiki/Main_Page
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.10.3

**How was Istio installed?**
Using IstioOperator CRD from file (not by the operator)

**Environment where the bug was observed (cloud vendor, OS, etc)**
GKE

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
