### ISSUE TITLE
gateway name can not been found in envoy proxy config

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#34307]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
the gateway name is bookinfo-gateway,but I can not find it in envoy proxy config.

[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**
```
name: "0.0.0.0_8080",
active_state: {
version_info: "2021-07-24T03:44:01Z/9",
listener: {
@type: "type.googleapis.com/envoy.config.listener.v3.Listener",
name: "0.0.0.0_8080",
address: {
socket_address: {
address: "0.0.0.0",
port_value: 8080
}
},
```

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: bookinfo-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
    name: bookinfo-gateway
```
the gateway name is bookinfo-gateway,but I can not find it in envoy proxy config.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
