### ISSUE TITLE
gateway protocol is http2,but actually the connection is http1.1

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#34308]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: bookinfo-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 15444
      name: http2
      protocol: HTTP2
      targetPort: 15444
    hosts:
    - "*"
```

[2021-07-24T05:54:11.368Z] "GET /productpage HTTP/1.1" 200 - via_upstream - "-" 0 5179 165 164 "172.20.0.0" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36" "5b9ef22b-dd20-97f4-bec3-65db60149b50" "bookinfo.demo:31001" "172.20.2.161:9080" outbound|9080||productpage.istio.svc.cluster.local 172.20.1.219:54534 172.20.1.219:15444 172.20.0.0:54697 - -

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
