### ISSUE TITLE
what is the envoy config of gateway mode passthough

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#34316]
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: bookinfo-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https-443
      protocol: HTTPS
    hosts:
    - "nginx.example.com"
    tls:
      mode: PASSTHROUGH
```
mode is PASSTHROUGH,I can not find any config in envoy config,that indicate this is passthough?
