### ISSUE TITLE
gateway tlsmode is ISTIO_MUTUAL,how can client get client certs to connect to server

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#34317]
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: bookinfo-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: ISTIO_MUTUAL
      credentialName: "bookinfo-credential"
    hosts:
    - "*"
```
because it's istio_mutual，so I did not need to specifiy client certs，so if I can not link istiod，how can client get certs

```
[root@master01 certs]# curl -v -HHost:bookinfo.example.com --resolve "bookinfo.example.com:32032:192.168.198.154"  --cacert example.com.crt  "https://bookinfo.example.com:32032/productpage"
* Added bookinfo.example.com:32032:192.168.198.154 to DNS cache
* About to connect() to bookinfo.example.com port 32032 (#0)
*   Trying 192.168.198.154...
* Connected to bookinfo.example.com (192.168.198.154) port 32032 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: example.com.crt
  CApath: none
* Server certificate:
*       subject: O=some organization,CN=bookinfo.example.com
*       start date: Jul 25 06:38:41 2021 GMT
*       expire date: Jul 25 06:38:41 2022 GMT
*       common name: bookinfo.example.com
*       issuer: CN=example.com,O=example Inc.
* NSS error -8182 (SEC_ERROR_BAD_SIGNATURE)
* Peer's certificate has an invalid signature.
* Closing connection 0
curl: (60) Peer's certificate has an invalid signature.
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```
