### ISSUE TITLE
Egress Gateway routing fails for HTTP/S endpoints if the default port is not set

### ISSUE THREAD

**Issue by mtenrero** [istio/istio#34324]
**Bug description**
When configuring a new Egress Gateway with even plain HTTP connections with a port different than 80 or 443, Istio is not able to find the cluster in the routing table and the request cannot progress through the Egress Gateway.

It also affects ServiceEntries with static external IP. One thing observed, is when deleting the VirtualService and avoiding the route proxying through the egress gateway the request can progress.

It can be reproduced with the CNN example available in the official docs.

The actual workaround I could found is to configure all the internal communication inside the mesh with the 80 and 443 ports and in the final VS configuration, point out the connection to the destination port. Also setting the protocol to TCP solves the problem.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

With any port / protocol in the egress gateway configuration, all request have to reach their destination.

**Steps to reproduce the bug**

Deploy Egress Gateway using the official example in the docs ([https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/](https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/))

That should work. Change the endpoint to a different HTTP server serving in another port and that will fail:

```
[2021-07-19T08:24:30.097Z] "GET / HTTP/1.1" 503 NC cluster_not_found - "-" 0 0 0 - "-" "curl/7.64.0" "17491dbf-8f4c-40bb-b7e6-805e42f4bb85" "service.external:3000" "-" - - 240.240.0.1:3000 10.244.52.73:37796 - -
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

client version: 1.10.0
control plane version: 1.10.0
data plane version: 1.10.0 (50 proxies)

Client Version: v1.21.1
Server Version: v1.18.10

v3.6.0+g7f2df64

**How was Istio installed?**

Istio Operator

**Environment where the bug was observed (cloud vendor, OS, etc)**

Bare Metal, CentOs 7, Calico, metalLB

**Comment by ramswish** [comment]
@mtenrero  I am also kind of facing similar issue. can you pls help me with the configuration you used for static IP with TLS though egress gateway ?

**Comment by mtenrero** [comment]
> @mtenrero I am also kind of facing similar issue. can you pls help me with the configuration you used for static IP with TLS though egress gateway ?

Here you got it:

There are some internal function references, you can freeley remove them for basic usage.

```yaml
{{ range $serviceEntryName, $serviceEntry := .Values.externalServices }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ $serviceEntryName | lower }}-external
spec:
  {{- if $serviceEntry.isTCP }}
  addresses:
    {{- if include "common.isIPV4" $serviceEntry.destination }}
    - {{ $serviceEntry.destination }}/32
    {{- else if include "common.isIPV6" $serviceEntry.destination }}
    - {{ $serviceEntry.destination }}/128
    {{- end }}
  {{- end }}
  hosts:
  - {{ $serviceEntry.source.host }}
  ports:
  {{- range $portName, $port := $serviceEntry.ports }}
  {{ if eq $port.internal.protocol "TCP" }}
  - name: "{{ $portName | lower }}-int-{{ $port.internal.number }}"
    number: {{ $port.external.number | default 80 }}
    protocol: {{ $port.external.protocol | default "TCP" }}
  {{ else }}
  - name: "{{ $portName | lower }}-int-{{ $port.internal.number }}"
    number: {{ $port.internal.number | default 80 }}
    protocol: {{ $port.internal.protocol | default "HTTP" }}
  - name: "{{ $portName | lower }}-ext-{{ $port.external.number }}"
    number: {{ $port.external.number | default 443 }}
    protocol: {{ $port.external.protocol | default "HTTPS" }}
  {{ end }}
  {{- end }}
  resolution: STATIC
  endpoints:
  - address: {{ $serviceEntry.destination }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ printf "%s-istio-destrule-mtls" $serviceEntryName | lower }}
spec:
  host: {{ $serviceEntry.source.host }}
  {{- if $serviceEntry.ports }}
  trafficPolicy:
    portLevelSettings:
    {{- range $portName, $port := $serviceEntry.ports }}
    {{- $tlsMode := $port.tlsMode | default "DISABLE" }}
    - port:
        number: {{ $port.external.number | default 443 }}
      tls:
        mode: {{ $tlsMode }}
    {{- if eq $tlsMode "MUTUAL" }}
        credentialName: {{ $serviceEntryName | lower }}-certificates
        sni: {{ $serviceEntry.source.host }}
    {{- end }}
    {{- end }}
  {{- end }}
---
{{ $defaultGateway := "istio-egressgateway-default" }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ $serviceEntryName | lower }}-istio-egressgateway
spec:
  selector:
    istio: "{{ $.Release.Namespace }}-{{ $serviceEntry.egressGatewayName | default $defaultGateway }}"
  servers:
  {{- range $portName, $port := $serviceEntry.ports }}
    - port:
      {{- $protocol := $port.internal.protocol | default "HTTP" }}
      {{- if eq $protocol "HTTP" }}
        number: 80
      {{- else }}
        number: {{ $port.internal.number }}
      {{- end }}
        name: {{ $portName | lower }}
        protocol: {{ $protocol }}
      hosts:
      {{ if eq $protocol "TCP" }}
        - '*'
        - {{ $serviceEntry.source.host }}
      {{ else }}
        - {{ $serviceEntry.source.host }}
      {{ end }}
      {{- if eq $protocol "HTTPS" }}
      tls:
        mode: PASSTHROUGH
        minProtocolVersion: {{ $port.minTlsProtocol | default "TLS_AUTO" }}
      {{- end }}
  {{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $serviceEntryName | lower }}-external-vs
spec:
  gateways:
    - {{ $serviceEntryName | lower }}-istio-egressgateway
    - mesh
  hosts:
    - {{ $serviceEntry.source.host }}
  {{- range $portName, $port := $serviceEntry.ports }}
  {{ $targetPort := $port.internal.number | default 80 }}
  {{ $port.internal.protocol | lower }}:
  - match:
    - gateways:
      - mesh
      port: {{ int $targetPort }}
      {{ if eq $port.internal.protocol "TCP" }}
      destinationSubnets:
        - {{ $serviceEntry.destination }}/32
      {{ end }}
    route:
    - destination:
        host: {{ $serviceEntry.egressGatewayName | default $defaultGateway }}
        port: 
          number: {{ int $targetPort }}
  - match:
    - gateways:
      - {{ $serviceEntryName | lower }}-istio-egressgateway
      {{- if eq $port.internal.protocol "HTTP" }}
      port: 80
      {{- else }}
      port: {{ $port.internal.number }}
      {{- end }}
    route:
    - destination:
        host: {{ $serviceEntry.source.host }}
        port:
          number: {{ $port.external.number }}
  {{- end }}
---
{{ end }}
```
