### ISSUE TITLE
Cert Manager ACME HTTP Solver

### ISSUE THREAD

**Issue by MateusAmin** [istio/istio#34334]
I would like there to be a way for me to use HTTP based  ACME solving with Istio & Cert Manger.

I can use DNS based ACME solving with Istio & Cert Manger.

[x] Networking
[x] User Experience

**Additional context**

Switching from Nginx ingress to the Istio stack forces me to switch from a HTTP solver to a DNS solver which forces me to change my dns provider.

The Cert Manger team has pushed support for K8s Gateway API in the 1.5 alpha. But I do not see support the External filters needed for grpc-web translation in Istio for the K8s Gateway API? Which would be the only blocker there other then a lack of documentation.

Although, I suppose I could leave the grpc-web translation to a proxy sidecar, and move the gateway controller to the same namespace?..

**Comment by howardjohn** [comment]
ACME HTTP solver should work fine with Istio, see https://preliminary.istio.io/latest/docs/ops/integrations/certmanager. Can you give more details about the issues you are seeing

**Comment by MateusAmin** [comment]
Thanks for taking a look. This is news to me (but I am new to Istio). All the guides I found when running into the problem reccomended switching the DNS solver.

I did however try to get it working with Istio. This config for the issuer failed to produce a working solver using a default istio install (I have tested some example gateways but not ingresses). 

```yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: example-issuer
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: example-issuer-account-key
    solvers:
    - http01:
       ingress:
         class: istio
```

I suppose I could install a namespace nginx ingress with cert manager as well.
