### ISSUE TITLE
allow opt-in for access log per pod

### ISSUE THREAD

**Issue by ngtuna** [istio/istio#34354]
**Describe the feature request**

Enable access log mesh-wide via `meshConfig.accessLogFile` might destroy log system. That would be great to have an opt-in approach where access log is disabled by default and providing pod annotation to enable access log on particular pod.

Something like: `sidecar.istio.io/accessLogFile: /dev/stdout`

Of course EnvoyFilter is needed for log format and other configurations.

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[x] Developer Infrastructure

**Additional context**

**Comment by bianpengyuan** [comment]
Finer granular access log control is added in new the telemetry API and will be ready by 1.11/1.12. It can enable access log based on workload labels etc. However it does not provide per pod control. If that is desired I think the only way is to make runtime call to the proxy: `istioctl proxy-config log POD --level=debug`.

**Comment by ngtuna** [comment]
Workload label is cool enough. Thanks for the confirmation @bianpengyuan

**Comment by bianpengyuan** [comment]
Let's track this issue with https://github.com/istio/istio/issues/24287. Thanks again for your report!

**Comment by ngtuna** [comment]
Hm.. it's strange I can not see any access log in envoy sidecar log (debug level). Not sure what I am missing or configuring wrong. Here is the envoyfilter for it:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: api-access-log
  namespace: default
spec:
  workloadSelector:
    labels:
      app: api
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: SIDECAR_OUTBOUND
        listener:
          portNumber: 8080
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
            access_log:
              - name: envoy.access_loggers.file
                typed_config:
                  "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog"
                  path: /dev/stdout
                  log_format:
                    json_format:
                      start_at: "%START_TIME%"
                      route_name: "%ROUTE_NAME%"
                      protocol: "%PROTOCOL%"
                      method: "%REQ(:METHOD)%"
                      path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
                      x_forwarded_for: "%REQ(X-FORWARDED-FOR)%"
                      user_agent: "%REQ(USER-AGENT)%"
                      cxid: "%REQ(X-REQUEST-ID)%"
                      response: "%RESPONSE_CODE%"
                      res_flag: "%RESPONSE_FLAGS%"
                      destination: "%REQ(:AUTHORITY)%"
                      duration: "%DURATION%"
```

pod is listening at port 8080
