### ISSUE TITLE
Egress Gateways - UF,URX on client proxy

### ISSUE THREAD

**Issue by MaciekLeks** [istio/istio#34357]
**Bug description**
Can't egress traffic from pod through egress gateway with REGISTER_ONLY outbound policy. I get UF,URX error.
I've tested it on minikube and it worked. Then I moved to gke (with real business config) and the error come out. Then I came back to minikube and the error appeared even there (I might changed something but I do not know what). 

Running curl from sleep container gives:
result:
```
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to www.google.com:443
```
and the istio-proxy log:
```
[2021-07-27T11:45:11.004Z] "- - -" 0 UF,URX - - "-" 0 0 21 - "-" "-" "-" "-" "172.17.0.5:8443" outbound|443|google|istio-egressgateway.istio-system.svc.cluster.local - 142.250.20 │
│ 3.132:443 172.17.0.6:37482 - -
```
egress gateway istio-proxy is not event touched (no logs) despite of the fact it seems to be healthy:
```
istioctl pc endpoints  sleep-598ffff477-9nccn.internal  --cluster "outbound|443||istio-egressgateway.istio-system.svc.cluster.local"                
ENDPOINT            STATUS      OUTLIER CHECK     CLUSTER
172.17.0.5:8443     HEALTHY     OK                outbound|443||istio-egressgateway.istio-system.svc.cluster.local
```
At the same time istio egress-gateway listeners look like this:
```
istioctl pc listener istio-egressgateway-54578bcc85-gfr5s.istio-system                                                                                
ADDRESS PORT  MATCH DESTINATION
0.0.0.0 15021 ALL   Inline Route: /healthz/ready*
0.0.0.0 15090 ALL   Inline Route: /stats/prometheus*
```
shouldn't be there also 0.0.0.0:443 for my egress gateway config (see step $4 in Steps to reproduce the bug)?

The next strange thing is that I can curl from istio eggress pod anywhere (see the first sentence on REGISTER_ONLY) :/

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Passing through egress gateway.

**Steps to reproduce the bug**
1. Install clean istio
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: my-istio-operator
  namespace: istio-system
spec:
  values:
    global:
      proxy:
        autoInject: enabled
      useMCP: false
      # The third-party-jwt is not enabled on all k8s.
      # See: https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens
      jwtPolicy: first-party-jwt

  addonComponents:
    pilot:
      enabled: true
  
  meshConfig:
    accessLogFile: /dev/stdout
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY

  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true    
    egressGateways:
    - name: istio-egressgateway
      enabled: true
```

2. Create test namespace
```
kubectl create ns internal
kubectl label namespace internal istio-injection=enabled
```
3. Apply sleep pod inside internal ns
```
kubectl -f sleep.yml -n internal
```
4. Apply traffic management:
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: google
  namespace: internal
spec:
  ##exportTo:
  ##- "."
  ##- "istio-system"
  hosts:
  - www.google.com
  ports:  
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: one-istio-egressgateway
  namespace: internal
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: tls
      protocol: TLS
    hosts:
    - www.google.com
    tls:
      mode: PASSTHROUGH
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: egressgateway-for-google
  namespace: internal
spec:
  ##exportTo:
  ##- "."
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: google
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: direct-google-through-egress-gateway
  namespace: internal
spec:
  hosts:
  - www.google.com
  gateways:
  - mesh
  - istio-egressgateway
  ##exportTo: 
  ##- "."
  #- "istio-system"
  tls:
  - match:
    - gateways:
      - mesh
      port: 443
      sniHosts:
      - www.google.com
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: google
        port:
          number: 443
      weight: 100
  - match:
    - gateways:
      - istio-egressgateway
      port: 443
      sniHosts:
      - www.google.com
    route:
    - destination:
        host: www.google.com
        port:
          number: 443
      weight: 100
```

5. From sleep container run:
```
curl https://www.google.com
```
 
**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.10.3

**How was Istio installed?**
```
istioctl install -f istio.yml
```

**Environment where the bug was observed (cloud vendor, OS, etc)**
- minikube
- gke

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by MaciekLeks** [comment]
OK, I figured out that some strict host/sni names not working, e.g. www.google.com. I followed the instruction (Egress using Wildcard Hosts)[https://istio.io/latest/docs/tasks/traffic-management/egress/wildcard-egress-hosts/] changing www.google.com to "*.google.com" and intruducing to Service Entries: one for *.google.com and another for www.google.com and it worked. But... when I did the same for my real business domains this approach did not work (I cannot see listener for my sni on egress gateway) 

What is a rule behind this magic? I've changed all manifests to be inline with the article I mentioned above and still nothing.

Any help is appreciated.

**Comment by MaciekLeks** [comment]
Let me show you a concret business case:
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: opl
  namespace: opl
spec:
  hosts:
  - dane.biznes.gov.pl
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: opl-egressgateway
  namespace: opl
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: tls
      protocol: TLS
    hosts:
    - dane.biznes.gov.pl
    tls:
      mode: PASSTHROUGH
      #minProtocolVersion: TLSV1_0
      #minProtocolVersion: TLSV1_3
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: egressgateway-for-opl
  namespace: opl
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: ced
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: direct-opl-through-egress-gateway
  namespace: opl
spec:
  hosts:
  - dane.biznes.gov.pl
  gateways:
  - mesh
  - istio-egressgateway
  tls:
  - match:
    - gateways:
      - mesh
      port: 443
      sniHosts:
      - dane.biznes.gov.pl
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: ced
        port:
          number: 443
  - match:
    - gateways:
      - istio-egressgateway
      port: 443
      sniHosts:
      - dane.biznes.gov.pl
    route:
    - destination:
        host: dane.biznes.gov.pl
        port:
          number: 443
      weight: 100
```
Results:
1. From sleep container in opl ns:
```
/ $ curl https://dane.biznes.gov.pl
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to dane.biznes.gov.pl:443 
```
2. sleep istio-proxy log for 1:
```
[2021-07-28T10:04:58.456Z] "- - -" 0 - - - "-" 517 0 194 - "-" "-" "-" "-" "172.17.0.5:8443" outbound|443|ced|istio-egressgateway.istio-system.svc.cluster.local 172.17.0.9:36226 82.177.1 │
│ 78.85:443 172.17.0.9:55786 dane.biznes.gov.pl -
```
For these manifets eggress reacts:
3. Egress log for 1:
```
[2021-07-28T10:04:58.648Z] "- - -" 0 NR filter_chain_not_found - "-" 0 0 0 - "-" "-" "-" "-" "-" - - 172.17.0.5:8443 172.17.0.9:36226 - -
```
Additions:
Egress proxy still do not create listener for the gateway (there are only working listeners):
```
istioctl pc listener istio-egressgateway-54578bcc85-gfr5s.istio-system                                                                                        
ADDRESS PORT  MATCH                DESTINATION
0.0.0.0 8443  SNI: *.google.com    Cluster: outbound|443||www.google.com
0.0.0.0 8443  SNI: edition.cnn.com Cluster: outbound|443||edition.cnn.com
0.0.0.0 15021 ALL                  Inline Route: /healthz/ready*
0.0.0.0 15090 ALL                  Inline Route: /stats/prometheus*
```

Could any suggest what the hell is going on?

**Comment by MaciekLeks** [comment]
My fault.

Of course I confused istio-system egress gateway svc name with my gateway in manifests.
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: opl
  namespace: opl
spec:
  hosts:
  - dane.biznes.gov.pl
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: opl-egressgateway #my gateway
  namespace: opl
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: tls
      protocol: TLS
    hosts:
    - dane.biznes.gov.pl
    tls:
      mode: PASSTHROUGH
      #minProtocolVersion: TLSV1_0
      #minProtocolVersion: TLSV1_3
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: egressgateway-for-opl
  namespace: opl
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: ced
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: direct-opl-through-egress-gateway
  namespace: opl
spec:
  hosts:
  - dane.biznes.gov.pl
  gateways:
  - mesh
  - opl-egressgateway #my gateway
  tls:
  - match:
    - gateways:
      - mesh
      port: 443
      sniHosts:
      - dane.biznes.gov.pl
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: ced
        port:
          number: 443
  - match:
    - gateways:
      - opl-egressgateway #my gateway
      port: 443
      sniHosts:
      - dane.biznes.gov.pl
    route:
    - destination:
        host: dane.biznes.gov.pl
        port:
          number: 443
      weight: 100
```
