### ISSUE TITLE
support topology.istio.io/cluster label on gateways

### ISSUE THREAD

**Issue by nmnellis** [istio/istio#34366]
**Describe the feature request**
Today there is support on the gateway for `topology.istio.io/network` but not `topology.istio.io/cluster` and has to be specified in the global properties. It would be nice to be able to supply both as labels.

How it works today
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: eastwest-gateway-1-10-3
  namespace: istio-gateways
spec:
  profile: empty
  revision: 1-10-3
  components:
    ingressGateways:
      - name: istio-eastwestgateway
        namespace: istio-gateways
        enabled: true
        label:
          istio: eastwestgateway
          version: 1-10-3
          app: istio-eastwestgateway
          # matches spec.values.global.network in istiod deployment
          topology.istio.io/network: production-cluster-network
        k8s:
          env:
            # traffic through this gateway should be routed inside the network
            # matches spec.values.global.network in istiod deployment
            - name: ISTIO_META_REQUESTED_NETWORK_VIEW
              value: production-cluster-network
          service:
            ports:
              - name: status-port
                port: 15021
                targetPort: 15021
              - name: tls
                port: 15443
                targetPort: 15443
              - name: tls-istiod
                port: 15012
                targetPort: 15012
              - name: tls-webhook
                port: 15017
                targetPort: 15017
  values:
    global:
      # needed for connecting VirtualMachines to the mesh
      network: production-cluster-network
      # needed for annotating istio metrics with cluster
      multiCluster:
        clusterName: production-cluster
```

how i would like it
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: eastwest-gateway-1-10-3
  namespace: istio-gateways
spec:
  profile: empty
  revision: 1-10-3
  components:
    ingressGateways:
      - name: istio-eastwestgateway
        namespace: istio-gateways
        enabled: true
        label:
          istio: eastwestgateway
          version: 1-10-3
          app: istio-eastwestgateway
          # matches spec.values.global.network in istiod deployment
          topology.istio.io/network: production-cluster-network
          # matches spec.values.global.multiCluster.clusterName in istiod deployment
          topology.istio.io/cluster: production-cluster
        k8s:
          env:
            # traffic through this gateway should be routed inside the network
            # matches spec.values.global.network in istiod deployment
            - name: ISTIO_META_REQUESTED_NETWORK_VIEW
              value: production-cluster-network
          service:
            ports:
              - name: status-port
                port: 15021
                targetPort: 15021
              - name: tls
                port: 15443
                targetPort: 15443
              - name: tls-istiod
                port: 15012
                targetPort: 15012
              - name: tls-webhook
                port: 15017
                targetPort: 15017
```

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by linsun** [comment]
@stevenctl could you comment on this?   from reading the doc, the label `topology.istio.io/cluster` is intended for cluster selection during DR.  Could we expand this to indicate which cluster the gw belongs to?  This will help eliminate this values.global.multicluster.clustername config in gateway's IOP since we now recommend users to install gw separately from istiod.

**Comment by stevenctl** [comment]
So currently `topology.istio.io/cluster` is sort of a virtual label that exists only in the control-plane's internal model. We don't actually inject that label onto Pods. 

What is the need for the cluster label existing on the Pods? For networks, this label helps us figure out which network the gateway can act as an ingress to. For clusters I'm not sure what that would be. Is this for metrics purposes only? IIRC we still set `ISTIO_META_CLUSTER_ID` on the proxy/gateway which may or may not be propagated in metrics.

**Comment by linsun** [comment]
hey @stevenctl the thought that Nick raised is: can we use the cluster label on gw pod to indicate which cluster's registry the gw belongs to, so he doesn't have to configure it via `values.global.multicluster.clustername`.

This is not possible in our code base because we determine the cluster id from ISTIO_META_CLUSTER_ID which is configured in the injection template:

```
        - name: ISTIO_META_CLUSTER_ID
          value: "{{ valueOrDefault .Values.global.multiCluster.clusterName `Kubernetes` }}"
```

ISTIO_META_CLUSTER_ID is not only used in metrics, but also used in configuring which cluster the gw belongs to, for example, we see this in the log when `values.global.multicluster.clustername` is not set thus uses the default value `Kubernetes`.

```
xdsproxy	Initializing with upstream address "istiod-1-10-3.istio-system.svc:15012" and cluster "Kubernetes"
```

**Comment by stevenctl** [comment]
I still don't understand what benefit this gets us? What is that label doing? Is that label now the way we set `ISTIO_META_CLUSTER_ID`? It it a mechanism for overriding ISTIO_META_CLUSTER_ID?

**Comment by stevenctl** [comment]
I can understand that we want to de-dupe the # of places we have to specify `network` but I'm not sure about cluster.

**Comment by nmnellis** [comment]
for me its just consistency and ease of use, if you look at the the documentation you see them side by side and would assume that they would work the same. i do see that the documentation on network has a gateway section though. It definitely not clear when the cluster label can be used.

<img width="1118" alt="Screen Shot 2021-07-28 at 11 15 13 AM" src="https://user-images.githubusercontent.com/22355055/127358790-d1914121-ff8e-4fd1-b5be-4e3723622ddf.png">

**Comment by stevenctl** [comment]
I think the documentation could be a bit more clear on the cluster label. It's sort of a virtual label today, and should probably stay that way for most Pods. You can select it with Istio CR's, but it shouldn't get added to every pod in k8s because there is a cost of indexing labels (vs annotations). 

I can see the argument for allowing it's use as a configuration utility, but I'm not sure when a user would actually set it on a k8s resource. We know what cluster a resource is in pretty easily – networks may not be directly tied to clusters so we need to differentiate/override. 

It seems like the only place we might set it is in the IstioOperator label section. We'd have to go through the templates and add something similar to the below in several places. 

```sprig
{{ $clusterName := index $.labels "topology.istio.io/cluster" | default  "{{ $.Values.global.multiCluster.clusterName | default `Kubernetes` }}
```

cc @nmittler

**Comment by hzxuzhonghu** [comment]
For me, i doubt if this label is redundant now, as we can get the cluster ID without it now. So i do not understand what is the label for.

**Comment by linsun** [comment]
So there are 2 issues:

1. we recommend gw to be installed separately from control plane.  For control plane install, we had to specify values.global.multiCluster.clusterName. It is not obvious to user that field is also required on gw install when gw is installed separately.  (ideally, I think this should not be required, as when user installs the gw, they also specify which istiod to use.)

2. The docs on the `topology.istio.io/cluster` label isn't clear.  It is not clear to me if this label is only configured during istiod install?   It seems to indicate this label is also for workload in the cluster.  Given we support gw injection now, seems this label should be auto injected if it is configured in Istiod's install?

**Comment by stevenctl** [comment]
>  It is not obvious to user that field is also required on gw install

I don't see how the label would solve this. To get around this the install tool would have to check the cluster to find the cluster ID, then use that if the user didn't set it. 

> docs aren't clear

Agreed. This label is pretty much a "virtual" label that k8s objects won't actually contain. It's only used internally to the control plane, to allow workloadSelectors to reference it such as in DR> 

> this label should be auto injected

I don't know about the label, but we can certainly override the env?

**Comment by linsun** [comment]
hey @stevenctl I agree with your comment on "don't see how label would solve".  certainly our unclear doc on the label likely misled @nmnellis to think label could help.  I think we have 2 follow ups:

1. update the label doc. I will start a PR on this.
2. @nmnellis if you use gateway injection, do you still have this prob?

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: ingress
spec:
  profile: empty # Do not install CRDs or the control plane
  components:
    ingressGateways:
    - name: ingressgateway
      namespace: istio-ingress
      enabled: true
      label:
        # Set a unique label for the gateway. This is required to ensure Gateways
        # can select this workload
        istio: ingressgateway
  values:
    gateways:
      istio-ingressgateway:
        # Enable gateway injection
        injectionTemplate: gateway
    global:
      # needed for connecting VirtualMachines to the mesh
      network: production-cluster-network
```

cc @howardjohn
