### ISSUE TITLE
Add default system-node-critical ResourceQuota to the namespace istio-cni installed

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#34371]
Istio CNI runs with `system-node-critical` which prevents it from being evicted when node is under resource pressure. However most cloud providers only set node critical `ResourceQuota` in `kube-system` and istio installation does not create `ResourceQuota` by default in CNI namespace, which prevents istio-cni pods being scheduled outside kube-system out of the box. We should consider adding the following `ResourceQuota` when CNI is enabled.

```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: istio-critical-pods
  namespace: <cni installed-namespace>
spec:
  hard:
    pods: 1G
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values:
      - system-node-critical
```

cc @mandarjog @howardjohn
