### ISSUE TITLE
Istio Operator chart installation failing for 1.10.2

### ISSUE THREAD

**Issue by Caaslund** [istio/istio#34386]
**Bug description**

I have been installing istio onto clusters using a Helm chart to deploy istio-operator to in turn deploy all needed istio charts, and we have been using this approach since istio 1.5.6, most recently in istio 1.9.4, but when attempting to move to istio 1.10.2, I have been running into the following error when attempting to apply the control plane spec:

```
error	installer	Error during reconcile: failed to create Istio control plane with spec: 
profile:"default" install_package_path:"/istio/manifests" [...]
error: read file: read /istio/manifests/charts/base/..data: is a directory
```

For our deployment spec, the following is specified in the deployment YAML:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  [...]
spec:
  [...]
  template:
    metadata:
      labels:
        name: istio-operator
    spec:
      [...]        
      containers:
        - name: istio-operator
          [...]
          volumeMounts:
          - name: base
            mountPath: /istio/manifests/charts/base
          - name: base-files 
            mountPath: /istio/manifests/charts/base/files
          - [...]
      volumes:
        - name: base
          configMap:
            name: base
        - [...]
```

And the following base config map is what gets referenced above:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: base
  namespace: istio-operator
data:
{{ (.Files.Glob "istio-charts/base/*").AsConfig | indent 2 }}
```

The `istio-charts/base/*` is a copy of `manifests/charts/base/*` from the official release. Through version 1.9.4 this method worked effectively, although the behavior breaks with 1.10.2, which I did not expect, since although the `base` charts change, the file structure of that folder did not change between 1.9 and 1.10. Is there some less obvious change between 1.9 and 1.10 that could have broken our deployments?

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Version**

* Istio 1.10.2
* K8s 1.19.9

**How was Istio installed?**

Istio was installed from the official releases published on GitHub.

**Comment by Caaslund** [comment]
The issue appears to stem from the changes in #31410. After those changes, how should istio-operator provide the configmaps for istio to use?

**Comment by litong01** [comment]
@Caaslund can you please provide a bit instructions on how to reproduce this error?

**Comment by Caaslund** [comment]
We mounted all istio charts to an istio-operator pod along with an IstioOperator yaml spec for it to execute. In previous versions, this was sufficient, although with Istio 1.10, helm charts failed to get loaded from the volume mounts following PR #29963. We were able to resolve this issue for our specific deployment by building a custom version of istio operator 1.10 with that PR effectively reverted, but we were not able to get the deployment working with the PR's changes included.

**Comment by litong01** [comment]
@Caaslund I was looking for rather detailed steps such as what commands were run to setup istio, then what was changed and used to reproduce this error. For example , the steps should look like the following:

```
1. Use Istio 1.9.7 helm install to setup istio in a k8s env setup by using kind
2. Create a file named aaa.yaml and place in this directory 
3. Run command like this xxxx (example command)
4. Run more command (example command) , then the error appears in this a place (stdout, stderr, or log file)
```

Without similar instructions, it is a guess work to reproduce this error.

**Comment by litong01** [comment]
@Caaslund Can you at least provide the entire deployment yaml file so that I can try this?

**Comment by litong01** [comment]
@Caaslund Can you also provide how you arrange your files. like where the files are and templates are.

**Comment by litong01** [comment]
@Caaslund Here are the steps that I tried.

1. Download the two releases of istio 1.9.7 and 1.10.2
2. In different release folders, create configmap.yaml in manifests/charts/istio-operator/templates directory, here is the content of the configmap.yaml file:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: base
  namespace: istio-operator
data:
{{ (.Files.Glob "istio-charts/basett/*").AsConfig | indent 2 }}
```
3. Modify deployment.yaml file in the same directory to use the configmap like the description says
4. Use a clean k8s cluster
5. Create namespace istio-operator
6. Run this command to deploy the operator:
` helm install istio-operator -n istio-operator manifests/charts/istio-operator`
7. Run the following command to deploy controlplan
```
$ kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: default
EOF
```

Check both operator and istiod pod logs, there is no error in either release.
I've also tested with the configmap points to a non exist fold to produce a data empty configmap which also worked just fine.

This is tested in cluster created using kind. @Caaslund please verify if the steps are the steps that you took. If not, please indicate where things differ.
