### ISSUE TITLE
WorkloadEntry telemetry does not report correct canonical_revision

### ISSUE THREAD

**Issue by nrfox** [istio/istio#34395]
**Bug description**

Given a `WorkloadEntry` with a `version: v1` label and generated from `istioctl workload entry configure ...`, telemetry for the workload reports `source_canonical_revision="latest"` instead of `v1`. Telemetry does correctly report `source_version="v1"` and `version="v1"` though.

WorkloadEntry
```
apiVersion: networking.istio.io/v1beta1
kind: WorkloadEntry
metadata:
  name: details-v1
  namespace: bookinfo
spec:
  address: 10.10.10.10
  labels:
    app: details
    version: v1
  network: Kubernetes
  serviceAccount: details-service-account
```

When the workload entry VM files are created with `istioctl workload entry configure`, the `"service.istio.io/canonical-version"` label gets generated but not the `"service.istio.io/canonical-revision"` label.

mesh.yaml
```
defaultConfig:
  discoveryAddress: istiod.istio-system.svc:15012
  meshId: mesh1
  proxyMetadata:
    CANONICAL_REVISION: v1
    CANONICAL_SERVICE: details
    ISTIO_META_CLUSTER_ID: Kubernetes
    ISTIO_META_DNS_CAPTURE: "true"
    ISTIO_META_MESH_ID: mesh1
    ISTIO_META_NETWORK: Kubernetes
    ISTIO_META_WORKLOAD_NAME: details-v1
    ISTIO_METAJSON_LABELS: '{"app":"details","service.istio.io/canonical-name":"details","service.istio.io/canonical-version":"v1","version":"v1"}'
    POD_NAMESPACE: bookinfo
    SERVICE_ACCOUNT: vm-service-account
    TRUST_DOMAIN: cluster.local
  tracing:
    zipkin:
      address: zipkin.istio-system:9411
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Expected `canonical_revision` in telemetry to match `version` label.

**Steps to reproduce the bug**

1. Create a `WorkloadGroup` template with a `version: v1` label.
2. Run `istioctl workload entry configure ...` to create the `WorkloadEntry` and VM config files (mesh.yaml, cluster.env, etc.)
3. Start the workload and inspect telemetry for that workload noting that `canonical_revision="latest"`.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
$ istioctl version --remote
client version: 1.10.0
control plane version: 1.10.3
data plane version: 1.10.3 (8 proxies), 1.10.0 (6 proxies)
```

```
$ kubectl version --short
Client Version: v1.21.3
Server Version: v1.19.9-gke.1900
```

```
$ helm version --short
v3.5.4+g1b5edb6
```

**How was Istio installed?**
Helm for CRDs and Operator. Operator for Istio controlplane.

**Environment where the bug was observed (cloud vendor, OS, etc)**
GKE
