### ISSUE TITLE
Istio ExtAuthz with Oauth2-proxy removing headers in upstream

### ISSUE THREAD

**Issue by ricosega** [istio/istio#34421]
**Bug description**

I am trying to configure ExtAuthz with Oauth2-proxy and Keycloak.
The authentication is successful but many headers are being removed from the Response Headers.
Just set **istioctl proxy-config log deploy/frontend --level "http:debug"** to check what was happening and I can see the headers reaching the istio-proxy but they aren't being shown in the browsers.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
To see all the **headersToUpstreamOnAllow** set in the EnvouyExtAuthzHttp in the browser.

**Steps to reproduce the bug**
I applied the following config:

**IstioOperator**
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: default
spec:
  hub: docker.io/istio
  tag: 1.10.0
  profile: default

  meshConfig:
    extensionProviders:
    - name: "oauth"
      envoyExtAuthzHttp:
        service: "oauth-oauth2-proxy.oauth.svc.cluster.local"
        port: 80
        includeHeadersInCheck:
          - authorization
          - cookie
        headersToUpstreamOnAllow:
          - authorization
          - path
          - cookie
          - x-auth-request-access-token
          - x-auth-request-user
          - x-auth-request-email
        headersToDownstreamOnDeny:
          - content-type
          - set-cookie          
        includeAdditionalHeadersInCheck:
          X-Auth-Request-Redirect: '%REQ(x-forwarded-proto)%://%REQ(:authority)%%REQ(:path)%'

  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        overlays:
          - apiVersion: apps/v1
            kind: Deployment
            name: istio-ingressgateway
            patches:
              - path: kind
                value: DaemonSet
              - path: spec.strategy
              - path: spec.updateStrategy
                value:
                  rollingUpdate:
                    maxUnavailable: 33%
                  type: RollingUpdate
              - path: spec.template.spec.containers.[name:istio-proxy].ports.[containerPort:8080].hostPort
                value: 80
              - path: spec.template.spec.containers.[name:istio-proxy].ports.[containerPort:8443].hostPort
                value: 443
```
**RequestAuthentication**
```
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: require-jwt
  namespace: frontend
spec:
  jwtRules:
    - issuer: "https://keycloak.example.com/auth/realms/example"
      jwksUri: "https://keycloak.example.com/auth/realms/example/protocol/openid-connect/certs"
```
**AuthorizationPolicy**
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: require-jwt
  namespace: frontend
spec:
  action: CUSTOM
  provider:
    name: "oauth"
  rules: 
  - to:
    - operation:
        paths: ["*"]
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
istioctl version --remote
client version: 1.10.0
control plane version: 1.10.0
data plane version: 1.10.0 (26 proxies)

kubectl version --short
Client Version: v1.19.4
Server Version: v1.20.0

helm version --short
v3.4.1+gc4e7485
```

**How was Istio installed?**
Through istio-operator helm chart.

**Environment where the bug was observed (cloud vendor, OS, etc)**
Baremetal

**Comment by yangminzhu** [comment]
Could you also add the Oauth2-proxy config? 

> Just set istioctl proxy-config log deploy/frontend --level "http:debug" to check what was happening and I can see the headers reaching the istio-proxy but they aren't being shown in the browsers.

So you mean you can see the headers in the proxy but the ext-authz filter does not forward it to the backend? what are the missing headers here?

**Comment by ricosega** [comment]
Here the Oauth2-proxy config:
```
  oauth2_proxy.cfg: |-
    provider = "oidc"
    provider_display_name = "KEYCLOAK"
    email_domains = ["*"]
    pass_access_token = true
    pass_authorization_header = true
    pass_host_header = true
    pass_user_headers = true
    set_authorization_header = true
    set_xauthrequest = true
    standard_logging = true
    auth_logging = true
    request_logging = true
    skip_auth_preflight = true
    cookie_secure = true
    scope = "email profile openid"
    reverse_proxy = false
    ssl_insecure_skip_verify = true
    skip_provider_button = true
    cookie_httponly = false
    upstreams = ["static://200"]
    whitelist_domains = [".example.com"]
    cookie_domains = [".example.com"]
    oidc_issuer_url = "https://keycloak.example.com/auth/realms/example"
    login_url = "https://keycloak.example.com/auth/realms/example/protocol/openid-connect/auth"
    redeem_url = "https://keycloak.example.com/auth/realms/example/protocol/openid-connect/token"
    profile_url = "https://keycloak.example.com/auth/realms/example/protocol/openid-connect/userinfo"
    validate_url = "https://keycloak.example.com/auth/realms/example/protocol/openid-connect/userinfo"
    session_store_type = "redis"
    redis_connection_url = "redis://redis-master.redis:6379"
    redis_password = "password"
```
About the headers, this are the only headers I can see in any response headers call in the browser:
```
HTTP/2 200 OK
server: istio-envoy
date: Fri, 30 Jul 2021 08:39:22 GMT
content-type: text/html
content-length: 5446
last-modified: Fri, 23 Jul 2021 09:05:37 GMT
etag: "60fa8661-1546"
accept-ranges: bytes
x-envoy-upstream-service-time: 12
X-Firefox-Spdy: h2
```

And this is what I see in the istio-proxy sidecar container logs:
```
frontend-5f9d9ffb98-66m9d istio-proxy 
frontend-5f9d9ffb98-66m9d istio-proxy 2021-07-30T08:39:22.576925Z	debug	envoy http	[C302408] new stream
frontend-5f9d9ffb98-66m9d istio-proxy 2021-07-30T08:39:22.577058Z	debug	envoy http	[C302408][S7269752094645315160] request headers complete (end_stream=true):
frontend-5f9d9ffb98-66m9d istio-proxy ':authority', 'frontend.example.com'
frontend-5f9d9ffb98-66m9d istio-proxy ':path', '/'
frontend-5f9d9ffb98-66m9d istio-proxy ':method', 'GET'
frontend-5f9d9ffb98-66m9d istio-proxy 'user-agent', 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0'
frontend-5f9d9ffb98-66m9d istio-proxy 'accept', 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
frontend-5f9d9ffb98-66m9d istio-proxy 'accept-language', 'en-US,en;q=0.5'
frontend-5f9d9ffb98-66m9d istio-proxy 'accept-encoding', 'gzip, deflate, br'
frontend-5f9d9ffb98-66m9d istio-proxy 'dnt', '1'
frontend-5f9d9ffb98-66m9d istio-proxy 'upgrade-insecure-requests', '1'
frontend-5f9d9ffb98-66m9d istio-proxy 'sec-fetch-dest', 'document'
frontend-5f9d9ffb98-66m9d istio-proxy 'sec-fetch-mode', 'navigate'
frontend-5f9d9ffb98-66m9d istio-proxy 'sec-fetch-site', 'none'
frontend-5f9d9ffb98-66m9d istio-proxy 'sec-fetch-user', '?1'
frontend-5f9d9ffb98-66m9d istio-proxy 'te', 'trailers'
frontend-5f9d9ffb98-66m9d istio-proxy 'cookie', '_oauth2_proxy=X29hdXRoMl9wcm94eS05ZmVmNTg1YTExOWE5ZjQxYzZkMGM5ZDg0ZWEzNzIwNS5iRnNIVnJ3dGpoM05pSEl4UmxIQmZ3|1627634362|sV0dj08Nn2QDBlVh7csSUJUdoT4UwNxHgdw0JqAqY2o='
frontend-5f9d9ffb98-66m9d istio-proxy 'x-forwarded-for', '10.242.0.254'
frontend-5f9d9ffb98-66m9d istio-proxy 'x-forwarded-proto', 'https'
frontend-5f9d9ffb98-66m9d istio-proxy 'x-envoy-internal', 'true'
frontend-5f9d9ffb98-66m9d istio-proxy 'x-request-id', '9653a1f6-a05e-4314-878a-821e5edc749e'
frontend-5f9d9ffb98-66m9d istio-proxy 'x-envoy-decorator-operation', 'frontend.frontend.svc.cluster.local:80/*'
frontend-5f9d9ffb98-66m9d istio-proxy 'x-envoy-peer-metadata', 'ChQKDkFQUF9DT05UQUlORVJTEgIaAAoaCgpDTFVTVEVSX0lEEgwaCkt1YmVybmV0ZXMKGQoNSVNUSU9fVkVSU0lPThIIGgYxLjEwLjAK5gMKBkxBQkVMUxLbAyrYAwodCgNhcHASFhoUaXN0aW8taW5ncmVzc2dhdGV3YXkKEwoFY2hhcnQSChoIZ2F0ZXdheXMKKAoYY29udHJvbGxlci1yZXZpc2lvbi1oYXNoEgwaCjY4Nzg3YjlmYmIKFAoIaGVyaXRhZ2USCBoGVGlsbGVyCjYKKWluc3RhbGwub3BlcmF0b3IuaXN0aW8uaW8vb3duaW5nLXJlc291cmNlEgkaB3Vua25vd24KGQoFaXN0aW8SEBoOaW5ncmVzc2dhdGV3YXkKGQoMaXN0aW8uaW8vcmV2EgkaB2RlZmF1bHQKMAobb3BlcmF0b3IuaXN0aW8uaW8vY29tcG9uZW50EhEaD0luZ3Jlc3NHYXRld2F5cwoeChdwb2QtdGVtcGxhdGUtZ2VuZXJhdGlvbhIDGgExChIKB3JlbGVhc2USBxoFaXN0aW8KOQofc2VydmljZS5pc3Rpby5pby9jYW5vbmljYWwtbmFtZRIWGhRpc3Rpby1pbmdyZXNzZ2F0ZXdheQovCiNzZXJ2aWNlLmlzdGlvLmlvL2Nhbm9uaWNhbC1yZXZpc2lvbhIIGgZsYXRlc3QKIgoXc2lkZWNhci5pc3Rpby5pby9pbmplY3QSBxoFZmFsc2UKGgoHTUVTSF9JRBIPGg1jbHVzdGVyLmxvY2FsCiQKBE5BTUUSHBoaaXN0aW8taW5ncmVzc2dhdGV3YXktN2Q5YjQKGwoJTkFNRVNQQUNFEg4aDGlzdGlvLXN5c3RlbQpdCgVPV05FUhJUGlJrdWJlcm5ldGVzOi8vYXBpcy9hcHBzL3YxL25hbWVzcGFjZXMvaXN0aW8tc3lzdGVtL2RlcGxveW1lbnRzL2lzdGlvLWluZ3Jlc3NnYXRld2F5ChcKEVBMQVRGT1JNX01FVEFEQVRBEgIqAAonCg1XT1JLTE9BRF9OQU1FEhYaFGlzdGlvLWluZ3Jlc3NnYXRld2F5'
frontend-5f9d9ffb98-66m9d istio-proxy 'x-envoy-peer-metadata-id', 'router~192.168.9.101~istio-ingressgateway-7d9b4.istio-system~istio-system.svc.cluster.local'
frontend-5f9d9ffb98-66m9d istio-proxy 'x-envoy-attempt-count', '1'
frontend-5f9d9ffb98-66m9d istio-proxy 'x-b3-traceid', 'ecb88cd2451a6a0b3852c2b9b2ea965b'
frontend-5f9d9ffb98-66m9d istio-proxy 'x-b3-spanid', '3852c2b9b2ea965b'
frontend-5f9d9ffb98-66m9d istio-proxy 'x-b3-sampled', '0'
frontend-5f9d9ffb98-66m9d istio-proxy 
frontend-5f9d9ffb98-66m9d istio-proxy 2021-07-30T08:39:22.577073Z	debug	envoy http	[C302408][S7269752094645315160] request end stream
frontend-5f9d9ffb98-66m9d istio-proxy 2021-07-30T08:39:22.577272Z	debug	envoy rbac	checking request: requestedServerName: outbound_.80_._.frontend.frontend.svc.cluster.local, sourceIP: 192.168.9.101:57606, directRemoteIP: 192.168.9.101:57606, remoteIP: 10.242.0.254:0,localAddress: 192.168.148.171:80, ssl: uriSanPeerCertificate: spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account, dnsSanPeerCertificate: , subjectPeerCertificate: , headers: ':authority', 'frontend.example.com'
frontend-5f9d9ffb98-66m9d istio-proxy ':path', '/'
frontend-5f9d9ffb98-66m9d istio-proxy ':method', 'GET'
frontend-5f9d9ffb98-66m9d istio-proxy ':scheme', 'https'
frontend-5f9d9ffb98-66m9d istio-proxy 'user-agent', 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0'
frontend-5f9d9ffb98-66m9d istio-proxy 'accept', 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
frontend-5f9d9ffb98-66m9d istio-proxy 'accept-language', 'en-US,en;q=0.5'
frontend-5f9d9ffb98-66m9d istio-proxy 'accept-encoding', 'gzip, deflate, br'
frontend-5f9d9ffb98-66m9d istio-proxy 'dnt', '1'
frontend-5f9d9ffb98-66m9d istio-proxy 'upgrade-insecure-requests', '1'
frontend-5f9d9ffb98-66m9d istio-proxy 'sec-fetch-dest', 'document'
frontend-5f9d9ffb98-66m9d istio-proxy 'sec-fetch-mode', 'navigate'
frontend-5f9d9ffb98-66m9d istio-proxy 'sec-fetch-site', 'none'
frontend-5f9d9ffb98-66m9d istio-proxy 'sec-fetch-user', '?1'
frontend-5f9d9ffb98-66m9d istio-proxy 'te', 'trailers'
frontend-5f9d9ffb98-66m9d istio-proxy 'cookie', '_oauth2_proxy=X29hdXRoMl9wcm94eS05ZmVmNTg1YTExOWE5ZjQxYzZkMGM5ZDg0ZWEzNzIwNS5iRnNIVnJ3dGpoM05pSEl4UmxIQmZ3|1627634362|sV0dj08Nn2QDBlVh7csSUJUdoT4UwNxHgdw0JqAqY2o='
frontend-5f9d9ffb98-66m9d istio-proxy 'x-forwarded-for', '10.242.0.254'
frontend-5f9d9ffb98-66m9d istio-proxy 'x-forwarded-proto', 'https'
frontend-5f9d9ffb98-66m9d istio-proxy 'x-request-id', '9653a1f6-a05e-4314-878a-821e5edc749e'
frontend-5f9d9ffb98-66m9d istio-proxy 'x-envoy-attempt-count', '1'
frontend-5f9d9ffb98-66m9d istio-proxy 'x-b3-traceid', 'ecb88cd2451a6a0b3852c2b9b2ea965b'
frontend-5f9d9ffb98-66m9d istio-proxy 'x-b3-spanid', '3852c2b9b2ea965b'
frontend-5f9d9ffb98-66m9d istio-proxy 'x-b3-sampled', '0'
frontend-5f9d9ffb98-66m9d istio-proxy 'x-envoy-internal', 'true'
frontend-5f9d9ffb98-66m9d istio-proxy 'x-forwarded-client-cert', 'By=spiffe://cluster.local/ns/frontend/sa/default;Hash=3d653c4a30497c51c04e6d9c7128a36faf66dca13ef4aa53f4798f20e70a54ba;Subject="";URI=spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account'
frontend-5f9d9ffb98-66m9d istio-proxy , dynamicMetadata: 
frontend-5f9d9ffb98-66m9d istio-proxy 2021-07-30T08:39:22.577295Z	debug	envoy rbac	shadow denied, matched policy istio-ext-authz-ns[frontend]-policy[require-jwt]-rule[0]
frontend-5f9d9ffb98-66m9d istio-proxy 2021-07-30T08:39:22.577305Z	debug	envoy rbac	no engine, allowed by default
frontend-5f9d9ffb98-66m9d istio-proxy 2021-07-30T08:39:22.585134Z	debug	envoy http	async http request response headers (end_stream=false):
frontend-5f9d9ffb98-66m9d istio-proxy ':status', '200'
frontend-5f9d9ffb98-66m9d istio-proxy 'authorization', 'Bearer JWT_TOKEN'
frontend-5f9d9ffb98-66m9d istio-proxy 'gap-auth', 'test@example'
frontend-5f9d9ffb98-66m9d istio-proxy 'x-auth-request-access-token', 'JWT_TOKEN'
frontend-5f9d9ffb98-66m9d istio-proxy 'x-auth-request-email', 'test@example'
frontend-5f9d9ffb98-66m9d istio-proxy 'x-auth-request-groups', '/operator'
frontend-5f9d9ffb98-66m9d istio-proxy 'x-auth-request-preferred-username', 'test'
frontend-5f9d9ffb98-66m9d istio-proxy 'x-auth-request-user', '62b02dd6-22a2-4871-8ca9-e56227058e1c'
frontend-5f9d9ffb98-66m9d istio-proxy 'date', 'Fri, 30 Jul 2021 08:39:22 GMT'
frontend-5f9d9ffb98-66m9d istio-proxy 'content-length', '13'
frontend-5f9d9ffb98-66m9d istio-proxy 'content-type', 'text/plain; charset=utf-8'
frontend-5f9d9ffb98-66m9d istio-proxy 'x-envoy-upstream-service-time', '7'
frontend-5f9d9ffb98-66m9d istio-proxy 'server', 'istio-envoy'
frontend-5f9d9ffb98-66m9d istio-proxy 'x-envoy-decorator-operation', 'oauth-oauth2-proxy.oauth.svc.cluster.local:80/*'
frontend-5f9d9ffb98-66m9d istio-proxy 
frontend-5f9d9ffb98-66m9d istio-proxy 2021-07-30T08:39:22.585720Z	debug	envoy upstream	transport socket match, socket default selected for host with address 192.168.148.171:80
frontend-5f9d9ffb98-66m9d istio-proxy 2021-07-30T08:39:22.585731Z	debug	envoy upstream	Created host 192.168.148.171:80.
frontend-5f9d9ffb98-66m9d istio-proxy 2021-07-30T08:39:22.585812Z	debug	envoy upstream	addHost() adding 192.168.148.171:80
frontend-5f9d9ffb98-66m9d istio-proxy 2021-07-30T08:39:22.585879Z	debug	envoy upstream	membership update for TLS cluster inbound|80|| added 1 removed 0
frontend-5f9d9ffb98-66m9d istio-proxy 2021-07-30T08:39:22.585884Z	debug	envoy upstream	re-creating local LB for TLS cluster inbound|80||
frontend-5f9d9ffb98-66m9d istio-proxy 2021-07-30T08:39:22.585892Z	debug	envoy upstream	membership update for TLS cluster inbound|80|| added 1 removed 0
frontend-5f9d9ffb98-66m9d istio-proxy 2021-07-30T08:39:22.585908Z	debug	envoy upstream	re-creating local LB for TLS cluster inbound|80||
frontend-5f9d9ffb98-66m9d istio-proxy 2021-07-30T08:39:22.586012Z	debug	envoy upstream	membership update for TLS cluster inbound|80|| added 1 removed 0
frontend-5f9d9ffb98-66m9d istio-proxy 2021-07-30T08:39:22.586024Z	debug	envoy upstream	re-creating local LB for TLS cluster inbound|80||
frontend-5f9d9ffb98-66m9d istio-proxy 2021-07-30T08:39:22.588290Z	debug	envoy http	[C302408][S7269752094645315160] encoding headers via codec (end_stream=false):
frontend-5f9d9ffb98-66m9d istio-proxy ':status', '200'
frontend-5f9d9ffb98-66m9d istio-proxy 'server', 'istio-envoy'
frontend-5f9d9ffb98-66m9d istio-proxy 'date', 'Fri, 30 Jul 2021 08:39:22 GMT'
frontend-5f9d9ffb98-66m9d istio-proxy 'content-type', 'text/html'
frontend-5f9d9ffb98-66m9d istio-proxy 'content-length', '5446'
frontend-5f9d9ffb98-66m9d istio-proxy 'last-modified', 'Fri, 23 Jul 2021 09:05:37 GMT'
frontend-5f9d9ffb98-66m9d istio-proxy 'etag', '"60fa8661-1546"'
frontend-5f9d9ffb98-66m9d istio-proxy 'accept-ranges', 'bytes'
frontend-5f9d9ffb98-66m9d istio-proxy 'x-envoy-upstream-service-time', '2'
frontend-5f9d9ffb98-66m9d istio-proxy 'x-envoy-peer-metadata', 'ChkKDkFQUF9DT05UQUlORVJTEgcaBXdhcmlvChoKCkNMVVNURVJfSUQSDBoKS3ViZXJuZXRlcwoZCg1JU1RJT19WRVJTSU9OEggaBjEuMTAuMArfAQoGTEFCRUxTEtQBKtEBCg4KA2FwcBIHGgV3YXJpbwoZCgxpc3Rpby5pby9yZXYSCRoHZGVmYXVsdAohChFwb2QtdGVtcGxhdGUtaGFzaBIMGgo1ZjlkOWZmYjk4CiQKGXNlY3VyaXR5LmlzdGlvLmlvL3Rsc01vZGUSBxoFaXN0aW8KKgofc2VydmljZS5pc3Rpby5pby9jYW5vbmljYWwtbmFtZRIHGgV3YXJpbwovCiNzZXJ2aWNlLmlzdGlvLmlvL2Nhbm9uaWNhbC1yZXZpc2lvbhIIGgZsYXRlc3QKGgoHTUVTSF9JRBIPGg1jbHVzdGVyLmxvY2FsCiAKBE5BTUUSGBoWd2FyaW8tNWY5ZDlmZmI5OC02Nm05ZAoXCglOQU1FU1BBQ0USChoIZnJvbnRlbmQKSgoFT1dORVISQRo/a3ViZXJuZXRlczovL2FwaXMvYXBwcy92MS9uYW1lc3BhY2VzL2Zyb250ZW5kL2RlcGxveW1lbnRzL3dhcmlvChcKEVBMQVRGT1JNX01FVEFEQVRBEgIqAAoYCg1XT1JLTE9BRF9OQU1FEgcaBXdhcmlv'
frontend-5f9d9ffb98-66m9d istio-proxy 'x-envoy-peer-metadata-id', 'sidecar~192.168.148.171~frontend-5f9d9ffb98-66m9d.frontend~frontend.svc.cluster.local'
frontend-5f9d9ffb98-66m9d istio-proxy 
```

I've noticed this in the above log:
```
frontend-5f9d9ffb98-66m9d istio-proxy 2021-07-30T08:39:22.577295Z	debug	envoy rbac	shadow denied, matched policy istio-ext-authz-ns[frontend]-policy[require-jwt]-rule[0]
frontend-5f9d9ffb98-66m9d istio-proxy 2021-07-30T08:39:22.577305Z	debug	envoy rbac	no engine, allowed by default
```

Could this be the reason?

**Comment by yangminzhu** [comment]
> I've noticed this in the above log:
> frontend-5f9d9ffb98-66m9d istio-proxy 2021-07-30T08:39:22.577295Z	debug	envoy rbac	shadow denied, matched policy istio-ext-authz-ns[frontend]-policy[require-> jwt]-rule[0]
> frontend-5f9d9ffb98-66m9d istio-proxy 2021-07-30T08:39:22.577305Z	debug	envoy rbac	no engine, allowed by default
> Could this be the reason?

No, this log is expected, it means the proxy is going to call your oauth2-proxy server.

I tried this with the following oauth2-proxy config with okta and could see all the headers in the backend:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: oauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - args:
        - --http-address=0.0.0.0:4180
        - --provider=oidc
        - --redirect-url=http://redacted/oauth2/callback
        - --oidc-issuer-url=https://redacted.okta.com/oauth2/redacted
        - --email-domain=*
        - --cookie-refresh=1h
        - --cookie-secure=false # Set to false for test environment only
        - --set-xauthrequest # X-Auth-Request-User, X-Auth-Request-Email, X-Auth-Request-Preferred-Username, X-Auth-Request-Groups
        - --pass-access-token # X-Auth-Request-Access-Token, must first enable --set-xauthrequest
        - --set-authorization-header # Authorization: Bearer <JWT>
        - --upstream="static://200"
        - --reverse-proxy
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          value: "redacted"
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: "redacted"
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: "YW5lUnVvdWt2dUJaQ1ZDR05IcGVNdz09"
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.0.1
        imagePullPolicy: IfNotPresent
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: oauth-oauth2-proxy
  namespace: oauth
spec:
  selector:
    app: oauth2-proxy
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
```

The following is the response from the httpbin backend after sign-in with a test user I created in okta:
```
{
  "headers": {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9", 
    "Accept-Encoding": "gzip, deflate", 
    "Accept-Language": "en-US,en;q=0.9", 
    "Authorization": "Bearer redacted", 
    "Cache-Control": "max-age=0", 
    "Cookie": "_oauth2_proxy=redacted", 
    "Dnt": "1", 
    "Host": "redacted", 
    "Upgrade-Insecure-Requests": "1", 
    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36", 
    "X-Auth-Request-Access-Token": "redacted", 
    "X-Auth-Request-Email": "testuser@example.com", 
    "X-Auth-Request-User": "redacted", 
    "X-B3-Parentspanid": "295a4fa2036da11b", 
    "X-B3-Sampled": "0", 
    "X-B3-Spanid": "c17cf2d54ba9c6a4", 
    "X-B3-Traceid": "7257f08bbf6970e7295a4fa2036da11b", 
    "X-Envoy-Attempt-Count": "1", 
    "X-Envoy-Internal": "true", 
    "X-Forwarded-Client-Cert": "By=spiffe://cluster.local/ns/foo/sa/httpbin;Hash=ea17bd3845fc122a1f43d9a2733e316c95ea4e0ca072c9e0c23d9429b64cea38;Subject=\"\";URI=spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"
  }
}
```

There are some differences in the oauth2-proxy config but I'm not sure which one caused the issue in your case (also not sure if this might be related to the version of oauth2-proxy), could you try to use the above config to see if it fixes your issue?
