### ISSUE TITLE
accessLogFormat doesn't work.

### ISSUE THREAD

**Issue by soleimaniamir** [istio/istio#34466]
Hello,
I'm trying to config IstioOperator to change log format because I need "TraceID" to trace logs in Jaeger. this is my Istio "meshconfig":
```
meshConfig:
  enableTracing: true
  accessLogFile: /dev/stdout
  accessLogEncoding: JSON
  accessLogFormat: |
    {
      "accessLogFormat": "{\"traceID\": \"%REQ(x-b3-traceid)%\",\"protocol\": \"%PROTOCOL%\",\"upstream_service_time\": \"%REQ(x-envoy-upstream-service-time)%\",\"upstream_local_address\": \"%UPSTREAM_LOCAL_ADDRESS%\",\"duration\": \"%DURATION%\",\"upstream_transport_failure_reason\": \"%UPSTREAM_TRANSPORT_FAILURE_REASON%\",\"route_name\": \"%ROUTE_NAME%\",\"downstream_local_address\": \"%DOWNSTREAM_LOCAL_ADDRESS%\",\"user_agent\": \"%REQ(USER-AGENT)%\",\"response_code\": \"%RESPONSE_CODE%\",\"response_flags\": \"%RESPONSE_FLAGS%\",\"start_time\": \"%START_TIME%\",\"method\": \"%REQ(:METHOD)%\",\"request_id\": \"%REQ(X-REQUEST-ID)%\",\"upstream_host\": \"%UPSTREAM_HOST%\",\"x_forwarded_for\": \"%REQ(X-FORWARDED-FOR)%\",\"requested_server_name\": \"%REQUESTED_SERVER_NAME%\",\"bytes_received\": \"%BYTES_RECEIVED%\",\"istio_policy_status\": \"-\",\"bytes_sent\": \"%BYTES_SENT%\",\"upstream_cluster\": \"%UPSTREAM_CLUSTER%\",\"downstream_remote_address\": \"%DOWNSTREAM_REMOTE_ADDRESS%\",\"authority\": \"%REQ(:AUTHORITY)%\",\"path\": \"%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%\"}"
    }
  defaultConfig:
    tracing:
      sampling: 100
    proxyMetadata: {}
  enablePrometheusMerge: true
  outboundTrafficPolicy:
    mode: ALLOW_ANY
```
after configuring Istio with the above config, there is no change in the Envoy log format as you see below:

`[2021-08-02T04:23:15.645Z] "POST /vehicles/ HTTP/1.1" 200 - via_upstream - "-" 121 0 0 0 "-" "Java/1.8.0_131" "3d9b018e-2ad4-9f6a-9985-b47e08f9d1d7" "fleetman-vehicle-telemetry:8080" "127.0.0.1:8080" inbound|8080|| 127.0.0.1:53666 172.17.0.13:8080 172.17.0.9:45938 outbound_.8080_._.fleetman-vehicle-telemetry.default.svc.cluster.local default`

I have to mention there is a "guid:x-request-id" tag in the request header but when I try to search between traces with that hearder, I got this error in Jaeger:

`{   "data": null,   "total": 0,   "limit": 0,   "offset": 0,   "errors": [     {       "code": 400,       "msg": "TraceID cannot be longer than 32 hex characters: 6f849240-3163-93d2-961a-b30629cac664"     }   ] }`

minikube and istioctl version:
```
PS> istioctl.exe version
client version: 1.9.1
control plane version: 1.9.1
data plane version: 1.9.1 (9 proxies)
PS> minikube version
minikube version: v1.15.1
commit: 23f40a012abb52eff365ff99a709501a61ac5876
```
