### ISSUE TITLE
can not find destinationrule connectionPool http config of envoy

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#34463]
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: productpage
spec:
  host: productpage
  subsets:
  - name: v1
    labels:
      version: v1
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 115
        connectTimeout: 30ms
        tcpKeepalive:
          time: 7200s
          interval: 75s
          probes: 10
      http:
        http2MaxRequests: 115
        maxRequestsPerConnection: 115
        http1MaxPendingRequests: 115
        maxRetries: 115
        idleTimeout: 115s
        h2UpgradePolicy: DEFAULT
```

tcp config in envoy can be found,but http config can not find in envoy?
