### ISSUE TITLE
can not find destinationrule loadBalancer localityLbSetting envoy config

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#34483]
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: productpage
spec:
  host: productpage.istio.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  trafficPolicy:
    loadBalancer:
      localityLbSetting:
        enabled: true
        distribute:
        - from: "us-central2/z2/*"
          to:
            "us-central3/z3/*": 100
            #"us-central2/z2/*": 100
            #"us-central1/z1/*": 100
    outlierDetection:
      consecutive5xxErrors: 1
      interval: 5m
      baseEjectionTime: 15m
```

![1627966029(1)](https://user-images.githubusercontent.com/31508490/127963273-fc824bfa-d00c-4103-9ea2-af73fdfad6ed.jpg)

search us-central of whole envoy config ,match nothing...
