### ISSUE TITLE
Istio Egress Gateway component doesn't support volumes from secrets

### ISSUE THREAD

**Issue by mvukadinoff** [istio/istio#34488]
**Bug description**
According the documentation in order to mount extra certificates for mutual TLS we should patch the deployment of istio egress gateway.

https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/

However this configuration is not persistent when we're creating our egress gateway with a CR. 

In theory the CR specification allows to define volumes as per the kubernetes specification for volumes, however the operator is not recognizing the "secret" keyword.
https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#k8s-io-api-core-v1-Volume

Also tried to place the secret definition under volumeSource , then we don't see an error, but the volume with the secret is not mounted at all.

[ ] Docs
[ ] Installation
[ X ] Networking
[ X ] Performance and Scalability
[ X ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

The defined volumes from secrets to get mounted in the volume mount paths.

**Steps to reproduce the bug**

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-dedicated-egressgw
  namespace: mynamespace
spec:
  profile: empty
  meshConfig:
    accessLogFile: /dev/stdout
  components:
    egressGateways:
    - name: istio-dedicated-egressgw
      namespace: mynamespace
      enabled: true
      label:
        protocol: http
      k8s:
        hpaSpec:
          maxReplicas: 1
          minReplicas: 1
        volumes:
        - name: test-ca-cert
          secret:
            defaultMode: 420
            optional: true
            secretName: test-ca-cert
        volumeMounts:
        - mountPath: /etc/istio/test-ca-cert
          name: test-ca-cert
          readOnly: true
```

## Logs of operator

2021-08-03T11:30:41.245704Z     error   klog    k8s.io/client-go@v0.20.5/tools/cache/reflector.go:167: Failed to watch *v1alpha1.IstioOperator: failed to list *v1alpha1.IstioOperator: v1alpha1.IstioOperatorList.ListMeta: v1.ListMeta.TypeMeta: Kind: Items: []v1alpha1.IstioOperator: v1alpha1.IstioOperator.Spec: unmarshalerDecoder: unknown field "secret" in v1.Volume, error found in #10 byte of ...|":"empty"}}],"kind":|..., bigger context ...|{"accessLogFile":"/dev/stdout"},"profile":"empty"}}],"kind":"IstioOperatorList","metadata":{"continu|...

## apply the other version, results in no mounts

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-dedicated-egressgw
  namespace: mynamespace
spec:
  profile: empty
  meshConfig:
    accessLogFile: /dev/stdout
  components:
    egressGateways:
    - name: istio-dedicated-egressgw
      namespace: mynamespace
      enabled: true
      label:
        protocol: http
      k8s:
        hpaSpec:
          maxReplicas: 1
          minReplicas: 1
        volumes:
        - name: test-ca-cert
          volumeSource:
            secret:
              defaultMode: 420
              optional: true
              secretName: test-ca-cert
        volumeMounts:
        - mountPath: /etc/istio/test-ca-cert
          name: test-ca-cert
          readOnly: true
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

Version of istio:  1.10   ( istio/operator:1.10.2  )
kubectl version --short
Client Version: v1.20.1-5-g76a04fc
Server Version: v1.20.4-eks-6b7464
helm version: v3.5.4+g1b5edb6

**How was Istio installed?**
helm chart - istio operator
custom resource

**Environment where the bug was observed (cloud vendor, OS, etc)**
 AWS , EKS

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
