### ISSUE TITLE
DestionationRule routes traffic to incorrect host and ignores the specified host in the spec

### ISSUE THREAD

**Issue by agill17** [istio/istio#34506]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
DestionationRule routes traffic to incorrect host and ignores the specified host in the spec, when multiple services with similar selectors exist.

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
The request should get routed to the host (k8s service) thats defined in the istio DR when multiple services with similar selectors exist.

**Steps to reproduce the bug**
1. create a simple deployment
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample
      hash: jhf812
  template:
    metadata:
      labels:
        app: sample
        hash: jhf812
    spec:
      containers:
        - name: sample
          image: agill17/sample-http-app:0.1.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
```
1. Create 2 k8s services ( one with just 1 pod label and 2nd one with all pod labels  )
```
apiVersion: v1
kind: Service
metadata:
  name: sample
spec:
  type: ClusterIP
  selector:
    app: sample
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sample-canary
spec:
  type: ClusterIP
  selector:
    app: sample
    hash: jhf812
  ports:
    - name: http
      port: 8080
      targetPort: 8080
```
1. Create DR with 2 subsets ( include both pod selectors in both subsets )
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: sample
spec:
  host: sample
  subsets:
  - name: sample-canary
    labels:
      app: sample
      hash: jhf812
  - name: sample-stable
    labels:
      app: sample
      hash: jhf812
```
1. Create VS and send 100% of traffic to stable subset
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sample
spec:
  hosts:
  - sample
  http:
  - name: default
    route:
    - destination:
        host: sample
        subset: sample-stable
      weight: 100
    - destination:
        host: sample
        subset: sample-canary
      weight: 0
```
Now send some request to `sample:8080/app` -- which in kiali shows all traffic goes to "sample-canary" and not "sample" host when clearly the host in the DR is set to "sample".  If the 2nd service does not exist, I see expected results but I have to have a second ( maybe 3 ) services in total to do some canaries with ambassador too.

Prometheus metric also shows the incorrect `destination_service` 
```
istio_requests_total{app="sample", connection_security_policy="mutual_tls", destination_app="sample", destination_canonical_revision="latest", destination_canonical_service="sample", destination_cluster="Kubernetes", destination_principal="spiffe://cluster.local/ns/default/sa/default", destination_service="sample-canary.default.svc.cluster.local", destination_service_name="sample-canary", destination_service_namespace="default", destination_version="unknown", destination_workload="sample", destination_workload_namespace="default", hash="jhf812", instance="10.244.1.46:15020", istio_io_rev="default", job="kubernetes-pods", kubernetes_namespace="default", kubernetes_pod_name="sample-744df8d9b7-vbvpk", pod_template_hash="744df8d9b7", reporter="destination", request_protocol="http", response_code="200", response_flags="-", security_istio_io_tlsMode="istio", service_istio_io_canonical_name="sample", service_istio_io_canonical_revision="latest", source_app="unknown", source_canonical_revision="latest", source_canonical_service="curl", source_cluster="Kubernetes", source_principal="spiffe://cluster.local/ns/default/sa/default", source_version="unknown", source_workload="curl", source_workload_namespace="default"}
```
Istiod also shows the following conflict message
```
        "sample-765fc5cb5d-cbdp2.default": {
            "proxy": "sample-765fc5cb5d-cbdp2.default",
            "message": "Conflicting inbound listener:8080. existing: sample-canary.default.svc.cluster.local, incoming: sample.default.svc.cluster.local"
        }
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
 istioctl version --remote
client version: 1.10.2
control plane version: 1.10.2
data plane version: 1.10.2 (2 proxies)
```
```
Client Version: v1.21.2
Server Version: v1.20.2
```

**How was Istio installed?**
- using istio operator + minimal profile

**Environment where the bug was observed (cloud vendor, OS, etc)**
- local kind cluster

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
