### ISSUE TITLE
destinationrule has portLevelSettings setting,but subset did not have tls config.my config was outside subset,it should effective to all subset??

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#34508]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
destinationrule has portLevelSettings setting,but subset did not have tls config.
my config was outside subset,it should effective to all subset??
**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
v1 cluster has tls config
**Steps to reproduce the bug**

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: productpage
spec:
  host: productpage.istio.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 9080
      loadBalancer:
        simple: RANDOM
      tls:
        mode: SIMPLE
        caCertificates: /etc/my-cert/ca.crt
        sni: productpage.istio.svc.cluster.local
        subjectAltNames: 
        - spiffe://cluster.local/ns/istio/sa/bookinfo-productpage
```

![1628065361(1)](https://user-images.githubusercontent.com/31508490/128147844-8abebcb3-2829-4bd9-86a7-2409a89f0bf3.jpg)

![1628065434(1)](https://user-images.githubusercontent.com/31508490/128147977-3c959dc7-fda1-4159-9bd9-f18c952a5a53.jpg)

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

istio 1.10.0

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
