### ISSUE TITLE
Helm chart does not support numTrustedProxies

### ISSUE THREAD

**Issue by linxcat** [istio/istio#34526]
Even though the format for the istio ingress helm values is the same as what one would create to set meshConfig.defaultConfig.gatewayTopology.numTrustedProxies, it is completely incapable of setting those values, since it ignores the existence of gatewayTopology in the templating stage.

https://github.com/istio/istio/blob/master/manifests/charts/gateways/istio-ingress/values.yaml#L312

The only way to do this shouldn't be altering the deployment itself, the documentation says that this process should be the same as istioctl or the Operator (citing https://istio.io/latest/docs/setup/install/helm/)

**Comment by howardjohn** [comment]
I am not suggesting its not confusing at all, but the way to do it is to configure it on the istio-control chart. Note if your ingress gw is not in the same namespace, you MUST use https://istio.io/latest/docs/setup/additional-setup/gateway/ method for it to work.

**Comment by linxcat** [comment]
I'd like to place a correction here that the easiest way to do it without actual support is to directly annotate. Here's the structure:
```
gateways:
  istio-ingressgateway:
    podAnnotations:
      proxy.istio.io/config: '{"gatewayTopology" : { "numTrustedProxies": 1}}'
```
