### ISSUE TITLE
bug: no labels on SE+DR subset == no match

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#34566]
```
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: redis
  namespace: default
spec:
  hosts:
  - httpbin.org
  ports:
  - number: 6978
    name: tcp
    protocol: TCP
  resolution: DNS
  location: MESH_EXTERNAL
  endpoints:
    - address: httpbin.org
      labels:
        foo: bar
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: redis-originate-tls
  namespace: default
spec:
  host: httpbin.org
  subsets:
  - name: redis-originate-TLS
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 6978
        tls:
          mode: SIMPLE
          sni: httpbin.org
```

If remove
```
      labels:
        foo: bar
```

we end up with no endpoints matched
