### ISSUE TITLE
serviceEntry addresses only the last address is effective,can not find other address config in envoy config

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#34577]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
serviceEntry addresses only the last address is effective,can not find other address config in envoy config

[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
192.168.198.177 and 192.168.198.178 both effective
**Steps to reproduce the bug**
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: details-se
spec:
  hosts:
  - details.bookinfo.com
  addresses:
  - 192.168.198.177/32
  - 192.168.198.178/32
  location: MESH_INTERNAL
  ports:
  - number: 9080
    name: http
    protocol: HTTP
  resolution: STATIC
  workloadSelector:
    labels:
      app: details
```

![1628311481(1)](https://user-images.githubusercontent.com/31508490/128588243-0ebe3e59-b618-417a-8e0b-54d58a20b294.jpg)

there is no 192.168.198.177's config

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
istio 1.10.0
**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
