### ISSUE TITLE
ServiceEntry for external redis instance redirects all 6379 port traffic to this instance only

### ISSUE THREAD

**Issue by h4ckroot** [istio/istio#34585]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
I am trying to create a circuit breaker for the external Redis instance (GCP Redis memory store). I have configured two objects for that:
1. Service Entry with the below configs:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: redis
spec:
  hosts:
    - redis.mycloud99.net.
  resolution: DNS
  location: MESH_EXTERNAL
  ports:
  - number: 6379
    name: tcp
    protocol: REDIS
  endpoints:
  - address: redis.mycloud99.net.
```
2. Destination rule to apply connection settings and outlier detection:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: circuit-breaker-for-redis-instance
spec:
  host: "redis.mycloud99.net."
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
        connectTimeout: 1s
    outlierDetection: 
      maxEjectionPercent: 100
      consecutiveGatewayErrors: 1
      interval: 15s
      baseEjectionTime: 60s
```
Now, this had a very weird impact on my cluster, as now all pods inside the cluster that is connecting to different Redis instances, are now using my new instance. In other words, all traffic on port 6379 from other pods is redirected to my new instance, even if it is using a completely different hostname!.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

[ ] Multi Cluster
[] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

I would expect that the sidecar proxy would take into consideration the host, and not direct all traffic to the same host because it happened that is using the same port (6379).

**Steps to reproduce the bug**
Create two Redis Instances and add a DNS record for it, then apply the above resources.
**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

client version: 1.6.5
control plane version: 1.6.5
data plane version: 1.6.5 (176 proxies)

**How was Istio installed?**
regular manifest YAML files.

**Environment where the bug was observed (cloud vendor, OS, etc)**
GKE

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
