### ISSUE TITLE
Headless service (in multi primary mode) is not resolvable across clusters in Istio 1.9.2.

### ISSUE THREAD

**Issue by irajdeep** [istio/istio#34582]
**Bug description**
I have `multi-primary-cluster` set up on the same network based on these [instructions](https://istio.io/latest/docs/setup/install/multicluster/multi-primary/). Cross cluster connectivity is working as expected as mentioned in these [verification docs](https://istio.io/latest/docs/setup/install/multicluster/verify/). But exposing a `headless` (`clusterIp: None`) service in cluster1 is not getting resolved from cluster2 in Istio version `1.9.2`. Note: this works in version `1.9.1`.

[x] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
The headless service deployed in cluster1 is getting resolved in cluster1 

**Steps to reproduce the bug**
i. Follow the [multi primary installation docs](https://istio.io/latest/docs/setup/install/multicluster/multi-primary/) to install istio in multi-cluster setup.
ii. Verify the setup is working as per this [verification docs](https://istio.io/latest/docs/setup/install/multicluster/verify/). 
iii. Create a headless `service` backed by a `statefulset` in cluster 1. Note the service object targets a pod to use service FQDN.
```yaml
apiVersion: v1
kind: Service
metadata:
  name: helloworld-0
  namespace: test
  labels:
    app: helloworld
    service: helloworld
spec:
  clusterIP: None
  ports:
  - port: 5000
    name: http
  selector:
    statefulset.kubernetes.io/pod-name: helloworld-0
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: helloworld
  namespace: test
spec:
  serviceName: "helloworld"
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: docker.io/istio/examples-helloworld-v2
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
```
vi. exec into a pod in cluster2(in `test` namespace) and run `curl helloworld-0.test.svc.cluster.local:5000/hello` -- this would return `Could not resolve host: helloworld-0.test.svc.cluster.local` (using service FQDN).

**Note: this however works in Istio version `1.9.1`**
**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
client version: 1.9.2
control plane version: 1.9.7
data plane version: 1.9.7 (1 proxies)
```
**How was Istio installed?**
https://istio.io/latest/docs/setup/install/multicluster/multi-primary/

**Environment where the bug was observed (cloud vendor, OS, etc)**
Deployed on AWS using KOPS.
