### ISSUE TITLE
HTTPS redirect doesn't work and 404 is returned

### ISSUE THREAD

**Issue by seed-248** [istio/istio#34609]
**Bug description**
HTTPS redirects configured in the Gateway resource don't work anymore if a virtual service that only matches HTTPS traffic is configured. Further explanations can be found in the example comments.

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
  namespace: my-namespace
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "example.com"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "example.com"
    tls:
      # TLS termination at the gateway
      mode: SIMPLE
      credentialName: my-cert
      minProtocolVersion: TLSV1_2

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-service
  namespace: my-namespace
spec:
  gateways:
  - my-gateway
  hosts:
  - "example.com"
  http:
  - name: example
    # This matching rule causes HTTP requests to 'example.com'. To return 404 (Not Found) responses instead of 301 (Moved Permanently).
    # If the matching rule is commented out, the HTTPS redirects work as expected. HTTPS requests work in both cases.
    match:
    - port: 443
    route:
    - destination:
        host: my-kubernetes-service
        port:
          number: 443
```
 

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

HTTPS redirects shouldn't be influenced by VirtualServices. 

**Steps to reproduce the bug**

1. Install istio with the default configuration
2. Create a Gateway and a VirtualService resource similar to the ones described above

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.9.7

**How was Istio installed?**
istioctl operator init + IstioOperator resource

**Environment where the bug was observed (cloud vendor, OS, etc)**
AKS

**Comment by howardjohn** [comment]
I can reproduce this on master

**Comment by anyname2** [comment]
I've hit this same issue with 1.10.1.
I added this to my http routes as a workaround:
```yaml
...
  http:
  - match:
    - port: 80
    redirect:
      uri: /
...
```
