### ISSUE TITLE
sidecar ingress egress capture mode is none，but the iptables is still there

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#34600]
```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: productpage
spec:
  workloadSelector:
    labels:
      app: productpage
  ingress:
  - captureMode: NONE
    defaultEndpoint: 127.0.0.1:9080
    port:
      number: 9080
      protocol: HTTP
      name: http
  egress:
  - hosts:
    - "./*"
    port:
      number: 9080
      protocol: HTTP
      name: egresshttp
    bind: 127.0.0.1
    captureMode: NONE
```

![1628573472(1)](https://user-images.githubusercontent.com/31508490/128813287-9b55ad59-52cf-44c5-852a-03ade8c3c8ab.jpg)

**Comment by yankunsam** [comment]
What's the value of ISTIO_META_INTERCEPTION_MODE(the proxy metadata) in your mesh?

**Comment by hzxuzhonghu** [comment]
The iptables are set in init-container or by cni, it is long before `Sidecar` creation and take effect.

**Comment by 13567436138** [comment]
how to get  ISTIO_META_INTERCEPTION_MODE value?

**Comment by 13567436138** [comment]
the iptables can not change?if capturemode is none,the iptables rule is still there will the traffic be captured?

**Comment by yankunsam** [comment]
> how to get ISTIO_META_INTERCEPTION_MODE value?

Like this,
`kubectl --context cluster1 get pod productpage-v1-6877d4d9b6-8rdxn -o yaml`

**Comment by 13567436138** [comment]
````
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: productpage
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/userVolume: '[{"name":"my-cert", "secret":{"secretName":"productpage-credential"}}]'
        sidecar.istio.io/userVolumeMount: '[{"name":"my-cert", "mountPath":"/etc/my-cert",
          "readonly":true}]'
      creationTimestamp: null
      labels:
        app: productpage
        version: v1
    spec:
      containers:
      - image: docker.io/istio/examples-bookinfo-productpage-v1:1.16.2
        imagePullPolicy: IfNotPresent
        name: productpage
        ports:
        - containerPort: 9080
          protocol: TCP
        resources: {}
        securityContext:
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /etc/my-cert
          name: secret-vol
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: bookinfo-productpage
      serviceAccountName: bookinfo-productpage
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: tmp
      - name: secret-vol
        secret:
          defaultMode: 420
          secretName: productpage-credential
```
no this env?
