### ISSUE TITLE
Envoy access logs are not showing up destination proxy sidecar container

### ISSUE THREAD

**Issue by pavanponugoti** [istio/istio#34620]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
Istio 1.10.2 is installed on GKE cluster and envoy access logs are set to output in JSON format globally. The logs are only visible in ingress gateways in istio-system namespace, but there are no log entries in side car proxies. 

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
For a given http request, a log entry should be available in both istio proxy containers, one being the ingress gateway and the other being the sidecar running along side with the application. This request is forwarded from ingress gateway to sidecar container.

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
istioctl version --remote
client version: 1.10.2
control plane version: 1.10.2
data plane version: 1.10.2

kubectl version --short
Client Version: v1.18.18-dispatcher
Server Version: v1.20.8-gke.900

**How was Istio installed?**
Using Istio operator, and the operator was deployed on to GKE cluster using helm charts. Here is the manifest of istiooperator inside k8s clusters:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  finalizers:
  - istio-finalizer.install.istio.io
spec:
  components:
    ingressGateways:
    - enabled: false
      k8s:
        serviceAnnotations:
          cloud.google.com/load-balancer-type: internal
          networking.gke.io/internal-load-balancer-allow-global-access: "true"
      name: istio-ingressgateway
  meshConfig:
    accessLogEncoding: JSON
    accessLogFile: /dev/stdout
    protocolDetectionTimeout: 10000ms
  profile: default
  values:
    global:
      proxy:
        tracer: stackdriver
    pilot:
      traceSampling: 1
    sidecarInjectorWebhook:
      injectedAnnotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: true
      rewriteAppHTTPProbe: true
    telemetry:
      enabled: true
      v2:
        enabled: true
        stackdriver:
          enabled: true
          logging: true
          monitoring: true
          topology: false
```

**Environment where the bug was observed (cloud vendor, OS, etc)**
GCP and GKE

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
