### ISSUE TITLE
istio dns proxy may cause pod/service ip conflicts

### ISSUE THREAD

**Issue by imliuda** [istio/istio#34627]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

In primary-remote and diffrent networks deployment, if both cluster has save pod and servicer cidr range, the envoy listener ip man conflict with actual pod/cluster ip in k8s. for example, both cluster use 10.254.0.0/16 as service cidr, and 10.0.0.0/16 as pod cidr, when 

- we deploy a nginx in cluster A under test namespace, k8s assign 10.254.1.1 as it's clusterIP. then deploy a nginx in cluster B under default namespace, set it's clusterIP as 10.254.1.1 . when istio dns proxy enabled, in a envoy injected pod, the nginx.default domain will resolve to 10.254.1.1, then traffic will send to pod in cluster A, not service in cluster B.
- or we deploy a zookeeper with headless service in cluster A, assume it has three pods of 10.0.1.1, 10.0.1.2 and 10.0.1.3, then all envoy proxy will have these listeners, no matter dns proxy enabled or not, these listener's cluster will be zookeeper.default.svc.cluster.local and it's destination will be ORIGINAL_DST, if we want access zookeeper in cluster A, then the traffic will send to cluster B's Pod with that ip. if cluster B do not have those pods, traffic will loss, in another word, we can not access headless service in different cluster if we use multi networks model.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

when istio dns proxy enabled, if a conflict is detected, istio should not directly use clusterIP as listener ip, is should use a virtual service ip out of a cluster cidr range.

when use different network model and dns proxy enabled, we can access headless service in another cluster, and listener's destination should be a normal envoy cluster use endpoint discovery, not ORIGINAL_DST. 

if both cluster have same headless services we use local services, if dns proxy is enabled, it should resolve to local services.

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

1.10.3

**How was Istio installed?**

IstioOperator

**Environment where the bug was observed (cloud vendor, OS, etc)**

Kingsoft Cloud KCE Platform 

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by hzxuzhonghu** [comment]
>we deploy a nginx in cluster A under test namespace, k8s assign 10.254.1.1 as it's clusterIP. then deploy a nginx in cluster B under default namespace, set it's clusterIP as 10.254.1.1 . when istio dns proxy enabled, in a envoy injected pod, the nginx.default domain will resolve to 10.254.1.1, then traffic will send to pod in cluster A, not service in cluster B.

If both nginx service has same tcp port, then i guess there will be a listener conflict. So one could take preference, which means all access to nginx would be go to one svc's destination. Haven't looked in to other cases.

**Comment by hzxuzhonghu** [comment]
>or we deploy a zookeeper with headless service in cluster A, assume it has three pods of 10.0.1.1, 10.0.1.2 and 10.0.1.3, then all envoy proxy will have these listeners, no matter dns proxy enabled or not, these listener's cluster will be zookeeper.default.svc.cluster.local and it's destination will be ORIGINAL_DST, if we want access zookeeper in cluster A, then the traffic will send to cluster B's Pod with that ip. if cluster B do not have those pods, traffic will loss, in another word, we can not access headless service in different cluster if we use multi networks model.

Did you test this? Or just your assumption

**Comment by imliuda** [comment]
> > we deploy a nginx in cluster A under test namespace, k8s assign 10.254.1.1 as it's clusterIP. then deploy a nginx in cluster B under default namespace, set it's clusterIP as 10.254.1.1 . when istio dns proxy enabled, in a envoy injected pod, the nginx.default domain will resolve to 10.254.1.1, then traffic will send to pod in cluster A, not service in cluster B.
> 
> If both nginx service has same tcp port, then i guess there will be a listener conflict. So one could take preference, which means all access to nginx would be go to one svc's destination. Haven't looked in to other cases.

这个我测试过了，如果clusterIP和监听的端口都一样就是冲突的，测试结果是流量会到先创建的那个服务上。而且就算一个是4层一个是7层也不行，只要是clusterIP和端口冲突就有问题。

I have tested this case, if both clusterIP and Port are same, the traffic will forward to the first service, even one is http service and another one is tcp service.

**Comment by imliuda** [comment]
> > or we deploy a zookeeper with headless service in cluster A, assume it has three pods of 10.0.1.1, 10.0.1.2 and 10.0.1.3, then all envoy proxy will have these listeners, no matter dns proxy enabled or not, these listener's cluster will be zookeeper.default.svc.cluster.local and it's destination will be ORIGINAL_DST, if we want access zookeeper in cluster A, then the traffic will send to cluster B's Pod with that ip. if cluster B do not have those pods, traffic will loss, in another word, we can not access headless service in different cluster if we use multi networks model.
> 
> Did you test this? Or just your assumption

I also tested this case, please refer these outputs, /tmp/config2 is my remote cluster's kubeconfig.

```shell
[root@vm10-88-11-134 ~]# kubectl get svc -n f4b203e58cdf52ef4ccf23a5cba0b277 | grep -v ann | grep redis
redis-sentinel                        ClusterIP      None             <none>        6379/TCP,26379/TCP,9121/TCP     14m
[root@vm10-88-11-134 ~]# kubectl get ep -n f4b203e58cdf52ef4ccf23a5cba0b277 | grep -v ann | grep redis
redis-sentinel                        10.2.6.41:26379,10.2.7.62:26379,10.2.8.190:26379 + 6 more...   14m
[root@vm10-88-11-134 ~]# nslookup redis-sentinel.f4b203e58cdf52ef4ccf23a5cba0b277 10.254.0.10
Server:		10.254.0.10
Address:	10.254.0.10#53

Name:	redis-sentinel.f4b203e58cdf52ef4ccf23a5cba0b277.svc.cluster.local
Address: 10.2.6.41
Name:	redis-sentinel.f4b203e58cdf52ef4ccf23a5cba0b277.svc.cluster.local
Address: 10.2.8.190
Name:	redis-sentinel.f4b203e58cdf52ef4ccf23a5cba0b277.svc.cluster.local
Address: 10.2.7.62

[root@vm10-88-11-134 ~]# istioctl --kubeconfig=/tmp/config2 pc listener dnsutils.default --address=10.2.7.62 --port=6379
^[[AADDRESS   PORT MATCH DESTINATION
10.2.7.62 6379 ALL   Cluster: outbound|6379||redis-sentinel.f4b203e58cdf52ef4ccf23a5cba0b277.svc.cluster.local
[root@vm10-88-11-134 ~]# istioctl --kubeconfig=/tmp/config2 pc cluster dnsutils.default --fqdn='outbound|6379||redis-sentinel.f4b203e58cdf52ef4ccf23a5cba0b277.svc.cluster.local'
SERVICE FQDN                                                          PORT     SUBSET     DIRECTION     TYPE             DESTINATION RULE
redis-sentinel.f4b203e58cdf52ef4ccf23a5cba0b277.svc.cluster.local     6379     -          outbound      ORIGINAL_DST
[root@vm10-88-11-134 ~]#
```

**Comment by imliuda** [comment]
> Could you share the meshconfig for clusterA/B? what is the value of global.network?

primary's config:

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-primary
  namespace: istio-system
spec:
  # istio.io/api/mesh/v1alpha1/config.pb.go
  # operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  # istio.io/api/operator/v1alpha1/operator.pb.go
  # manifests/charts
  profile: default
  tag: 1.10.3
  meshConfig:
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
    accessLogFile: /dev/stdout
    enableTracing: true
    enableAutoMtls: true
    ingressControllerMode: DEFAULT
    tcpKeepalive:
      probes: 5
      time: 300s
      interval: 75s
  components:
    # pilot:
    #   k8s:
    #     serviceAnnotations:
    #       service.beta.kubernetes.io/ksc-loadbalancer-type: internal
    #       service.beta.kubernetes.io/ksc-loadbalancer-subnet-id: e148a6ee-8020-4be9-ae99-c5e8a0fe6bb8
    #     service:
    #       type: LoadBalancer
    egressGateways:
    - name: istio-egressgateway
      enabled: true
    ingressGateways:
    - name: istio-eastwestgateway
      enabled: true
      label:
        istio: eastwestgateway
        app: istio-eastwestgateway
        topology.istio.io/network: network1
      k8s:
        serviceAnnotations:
          service.beta.kubernetes.io/ksc-loadbalancer-type: internal
          service.beta.kubernetes.io/ksc-loadbalancer-subnet-id: e148a6ee-8020-4be9-ae99-c5e8a0fe6bb8
        service:
          ports:
            - name: status-port
              port: 15021
              targetPort: 15021
            - name: tls
              port: 15443
              targetPort: 15443
            - name: tls-istiod
              port: 15012
              targetPort: 15012
            - name: tls-webhook
              port: 15017
              targetPort: 15017
        env:
          # sni-dnat adds the clusters required for AUTO_PASSTHROUGH mode
          - name: ISTIO_META_ROUTER_MODE
            value: "sni-dnat"
          # traffic through this gateway should be routed inside the network
          - name: ISTIO_META_REQUESTED_NETWORK_VIEW
            value: network1
    - name: istio-ingressgateway
      enabled: true
      k8s:
        serviceAnnotations:
          service.beta.kubernetes.io/ksc-loadbalancer-type: "internal"
          service.beta.kubernetes.io/ksc-loadbalancer-subnet-id: "e148a6ee-8020-4be9-ae99-c5e8a0fe6bb8"
        service:
          ports:
          - name: status-port
            port: 15021
            protocol: TCP
            targetPort: 15021
          - name: http2
            port: 80
            protocol: TCP
            targetPort: 8080
          - name: https
            port: 443
            protocol: TCP
            targetPort: 8443
  values:
    global:
      meshID: mesh1
      jwtPolicy: first-party-jwt
      logging:
        level: "default:debug"
      externalIstiod: false
      multiCluster:
        enabled: true
        clusterName: primary
      network: network1
      meshNetworks:
        network1:
          endpoints:
          - fromRegistry: primary
          gateways:
          - registryServiceName: istio-eastwestgateway.istio-system.svc.cluster.local
            port: 15443
        network2:
          endpoints:
          - fromRegistry: remote1
          gateways:
          - registryServiceName: istio-eastwestgateway.istio-system.svc.internal-bigdata.com
            port: 15443
```

remote's config:

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-remote1
  namespace: istio-system
spec:
  # istio.io/api/mesh/v1alpha1/config.pb.go
  # operator/pkg/apis/istio/v1alpha1/values_types.pb.go
  # istio.io/api/operator/v1alpha1/operator.pb.go
  # manifests/charts
  profile: default
  tag: 1.10.3
  meshConfig:
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
    accessLogFile: /dev/stdout
    enableTracing: true
    enableAutoMtls: true
    ingressControllerMode: DEFAULT
    tcpKeepalive:
      probes: 5
      time: 300s
      interval: 75s
  components:
    egressGateways:
    - name: istio-egressgateway
      enabled: true
    ingressGateways:
    - name: istio-eastwestgateway
      enabled: true
      label:
        istio: eastwestgateway
        app: istio-eastwestgateway
        topology.istio.io/network: network2
      k8s:
        serviceAnnotations:
          service.beta.kubernetes.io/ksc-loadbalancer-type: "internal"
          service.beta.kubernetes.io/ksc-loadbalancer-subnet-id: "e148a6ee-8020-4be9-ae99-c5e8a0fe6bb8"
        env:
          # sni-dnat adds the clusters required for AUTO_PASSTHROUGH mode
          - name: ISTIO_META_ROUTER_MODE
            value: "sni-dnat"
          # traffic through this gateway should be routed inside the network
          - name: ISTIO_META_REQUESTED_NETWORK_VIEW
            value: network2
        service:
          ports:
            - name: status-port
              port: 15021
              targetPort: 15021
            - name: tls
              port: 15443
              targetPort: 15443
    - name: istio-ingressgateway
      enabled: true
      k8s:
        serviceAnnotations:
          service.beta.kubernetes.io/ksc-loadbalancer-type: "internal"
          service.beta.kubernetes.io/ksc-loadbalancer-subnet-id: "e148a6ee-8020-4be9-ae99-c5e8a0fe6bb8"
    # Today, the remote profile will install an istiod server in the remote cluster which
    # will be used for CA and webhook injection for workloads in that cluster. Service discovery,
    # however, will be directed to the control plane in the primary cluster.
    # Future releases will remove the need for having an istiod in the remote cluster altogether.
    # Stay tuned!
    pilot:
      enabled: true
  values:
    pilot:
      env:
        # https://github.com/istio/istio/issues/31740
        # https://github.com/kubernetes/kubernetes/commit/3db7275b549559696c42c0b5f51c9a2397e9571d
        ENABLE_LEGACY_FSGROUP_INJECTION: true
    global:
      meshID: mesh1
      jwtPolicy: first-party-jwt
      logging:
        level: "default:debug"
      multiCluster:
        enabled: true
        clusterName: remote1
      network: network2
      remotePilotAddress: 10.88.1.213
      # meshNetworks:
      #   network1:
      #     endpoints:
      #     - fromRegistry: primary
      #     gateways:
      #     - registryServiceName: istio-eastwestgateway.istio-system.svc.cluster.local
      #       port: 15443
      #   network2:
      #     endpoints:
      #     - fromRegistry: remote1
      #     gateways:
      #     - registryServiceName: istio-eastwestgateway.istio-system.svc.internal-bigdata.com
      #       port: 15443
```
