### ISSUE TITLE
sidecar when outboundTrafficPolicy is set to REGISTRY_ONLY,what the envoy config will changed to be,I can not find the changed config?

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#34632]
```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: sleep
spec:
  workloadSelector:
    labels:
      app: sleep
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY
```

sidecar when outboundTrafficPolicy is set to REGISTRY_ONLY,what the envoy config will changed to be,I can not find the changed config?
