### ISSUE TITLE
EnvoyFilter workloadSelector does not apply to VM workloads.

### ISSUE THREAD

**Issue by Arsen-Uulu** [istio/istio#34641]
**Bug description**
Testing EnvoyFilters on VM and Pods workloads. 

```---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: my-test-filter
  namespace: default
spec:
  workloadSelector:
    labels:
      app: hello-world # WORKS because this workload runs in K8s.
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_OUTBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value: # lua filter specification
        name: envoy.lua
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
          inlineCode: |
            function envoy_on_response(response_handle)
              response_handle:headers():add("X-User-Header", "this works")
            end
```
```
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: my-test-filter-vm
  namespace: vm
spec:
  workloadSelector:
    labels:
      app: hello-world-vm  #THIS does not  work, this workload is running on VM's
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_OUTBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value: # lua filter specification
        name: envoy.lua
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
          inlineCode: |
            function envoy_on_response(response_handle)
              response_handle:headers():add("X-User-Header", "this works")
            end
```

However if I omit the workloadSelector from `my-test-filter-vm` it does work, but it gets applied to all my VM workload in the same namespace. 

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
I'd expect this to be working the same way as for workloads running on K8s. 
Even docs are stating this

```
workloadSelector | 
WorkloadSelector | 
Criteria used to select the specific set of **pods/VMs** on which this patch configuration should be applied. If omitted, the set of patches in this configuration will be applied to all workload instances in the same namespace. If omitted, the EnvoyFilter patches will be applied to all workloads in the same namespace. If the EnvoyFilter is present in the config root namespace, it will be applied to all applicable workloads in any namespace.
```

**Steps to reproduce the bug**
Please install istio-sidecar on VM and try creating EnvoyFilter for it

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Istio version 1.10.3

**How was Istio installed?**
IstioOperator

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS, Centos8

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by hzxuzhonghu** [comment]
Can you show the vm proxy's metadata labels? I guess it is not same as expected

**Comment by Arsen-Uulu** [comment]
@hzxuzhonghu the labels I gave are from WorkloadSelector. It’s matching the workloadSelector labels.  I should provide different set of labels?

**Comment by hzxuzhonghu** [comment]
I mean the proxy labels is not equal to wle's labels. Can you show the bootstrap config?

**Comment by Arsen-Uulu** [comment]
@hzxuzhonghu 
```"ISTIO_METAJSON_LABELS":"{\"proxy\":\"istio-demo\"}"```
This is the label from `/etc/istio/proxy/envoy-rev0.json`. 

When I create Envoy Filter I should provide this proxyMetadata labels?

**Comment by Arsen-Uulu** [comment]
@hzxuzhonghu 
```
2021-08-12T17:06:49.093796Z	debug	failed to read pod labels: open ./etc/istio/pod/labels: no such file or directory
2021-08-12T17:06:49.093815Z	debug	failed to read pod annotations: open ./etc/istio/pod/annotations: no such file or directory
```

I noticed that when I apply the filter it's trying to read this files

**Comment by Arsen-Uulu** [comment]
Added correct label from proxyMetadata and still no luck. 
```
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: my-test-filter-vm
  namespace: vm
spec:
  workloadSelector:
    labels:
      proxy: istio-demo
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value: # lua filter specification
        name: envoy.lua
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
          inlineCode: |
            function envoy_on_response(response_handle)
              response_handle:headers():add("X-User-Header", "worked")
            end
```

is this similar issue? 
https://github.com/istio/istio/issues/25601
