### ISSUE TITLE
outside TLS traffic gives 503 after long wait

### ISSUE THREAD

**Issue by lukaszpy** [istio/istio#34643]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
![istio](https://user-images.githubusercontent.com/3368012/129090791-a905f31e-3209-4321-b290-c38bfd6c20f7.png)

As on above image I want to have access to resource on cluster. The problem is is probably in TLS. Waht we want to archive:
1. user want to acess to resource on public service domain called: `https://service.public-domain.com/some-resource.wsdl`
2. traffic goes to WAF, where it is routed from `service.public-domain:443` to internal domain: `service.internal-domain.net:443` - it needs to be routed on 443 because baskend service doing translation of resource and properly generate links inside this WSDL file. Also this internal domain have it's own cert for `*.internal-domain.net`
3. then traffic should go throught inges to public-gateway
4. from gateway should goes to service using routing defined in VS

With provided configuration on picture I'm getting 503 after long time waiting (around 4 min) 
When I switch traffic on WAF from 443 port for internal domain to 80 it starts working but this translation of WSDL file on backend service provides links in resouce to `http://service.publkic-domain.com:80/service` and is is wrong because should be https://service.public-domain.com:443/service

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: public-gateway
  namespace: public
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*.public-domain.com'
    port:
      name: http-80
      number: 80
      protocol: HTTP
  - hosts:
    - '*.public-domain.com'
    port:
      name: httpsout-443
      number: 443
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
```

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: service
  namespace: sevice-env
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - service.internal-domain.net
    - '*.service.internal-domain.net'
    port:
      name: http-80
      number: 80
      protocol: HTTP
  - hosts:
    - service.internal-domain.net
    - '*.service.internal-domain.net'
    port:
      name: httpsint-443
      number: 443
      protocol: HTTPS
    tls:
      credentialName: credit.internal.cert
      mode: SIMPLE
```

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: service
  namespace: service-env
spec:
  hosts:
    - service
    - internal-domain.net
    - service.internal-domain.net
  gateways:
    - service
  http:
  - route:
    - destination:
        host: webservice
        port:
          number: 8080
```

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: service-public
  namespace: service-env
spec:
  gateways:
  - public/public-gateway
  hosts:
  - service.public-domain.com
  tls:
  - match:
    - port: 443
      sniHosts:
      - service.public-domain.com
    route:
    - destination:
        host: webservice
        port:
          number: 8080
```

**Version**
**Istio:**
client version: 1.10.3
control plane version: 1.10.3
data plane version: 1.10.3 (159 proxies)
**K8S:**
Client Version: v1.19.9
Server Version: v1.17.8

**How was Istio installed?**
istioctl

**Environment where the bug was observed (cloud vendor, OS, etc)**
self managment cluster on premis
