### ISSUE TITLE
False positive warning [IST0132] when Gateway uses a namespace prefix in the hosts field

### ISSUE THREAD

**Issue by tbcardoso** [istio/istio#34653]
**Bug description**

When creating a Gateway that specifies a host with a namespace prefix (e.g. `./my-service.example.com`) and a VirtualService that binds to that Gateway and to the same host, then `istioctl analyze` gives the warning [IST0132](https://istio.io/latest/docs/reference/config/analysis/ist0132/).

Example:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: my-gateway
  namespace: my-namespace
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - ./my-service.example.com
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: my-virtualservice
  namespace: my-namespace
spec:
  hosts:
    - my-service.example.com
  exportTo:
    - "."
  gateways:
    - my-gateway
  http:
    - route:
        - destination:
            host: my-service.my-namespace.svc.cluster.local
            port:
              number: 80
```

These resources work as expected. The traffic that reaches the gateway with host `my-service.example.com` is correctly routed to `my-service.my-namespace.svc.cluster.local` using the VirtualService rules.

However, running `istioctl analyze` gives the warning:

> Warning [IST0132] (VirtualService my-virtualservice.my-namespace) one or more host [my-service.example.com] defined in VirtualService my-namespace/my-virtualservice not found in Gateway my-namespace/my-gateway.

The same issue applies if the Gateway host is defined as `*/my-service.example.com` or `my-namespace/my-service.example.com`. The only way to avoid the warning is to define the host without the namespace prefix which is not desired when we just want to select virtual services from a single namespace.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

No warning should be given by `istioctl analyze`.

**Steps to reproduce the bug**

Apply the Gateway and Virtual Service resources mentioned above then run `istioctl analyze --all-namespaces`.

**Version**

```
$ istioctl version --remote
client version: 1.10.3
control plane version: 1.10.3
data plane version: 1.10.3 (11 proxies)
```

```
$ kubectl version --short
Client Version: v1.21.3
Server Version: v1.20.8-gke.900
```

I also saw this happening in previous Istio versions.

**How was Istio installed?**

Installed with istioctl following the [documentation](https://istio.io/latest/docs/setup/install/istioctl/).

**Environment where the bug was observed (cloud vendor, OS, etc)**

GKE.
