### ISSUE TITLE
Disabling Retries by setting attemps=0 on egress virtual service is not reflected in istio proxy config

### ISSUE THREAD

**Issue by kameshchauhan** [istio/istio#34667]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Description**
In order to disable default retry, we followed  the guide at https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRetry and set the value of `attempts=0`.

The `retries` block was added as below
```
retries:
   attempts: 0
```
The issue is that the above block added into the virtual service attached to the `ingerss`  gateway works just fine as expected and showing the config change reflected in Istio Envoy Proxy Routes configuration.  
The proxy configuration was checked by running `istioctl pc routes <istio-ingressgateway-pod> -o json`. As expected, disabling the retries removes the policy block from the envoy routes config.

However, when the same configuration applied to the virtual service attached to the `egress` gateway is not behaving as expected. The retry block mentioned above had to be added at both the routes (within-mesh, outgoing) to achieve the effect. 
The configuration in virtual service and resulting enovy route config was inconsistent in below different scenarios.

**1.  Below config DOES NOT disable the retries and always shows the default retry policy with attempts-2 in Proxy Routes config**
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: direct-external-through-egress-gateway
  namespace: default
spec:
  gateways:
  - dev-egress-gateway
  - mesh
  hosts:
  - dev.xyz.com
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    name: nonprod-mesh
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        port:
          number: 443
        subset: dev
      weight: 100
  - match:
    - gateways:
      - dev-egress-gateway
      port: 443
    name: nonprod-egress
    _retries:
       attempts: 0_
    route:
    - destination:
        host: dev.xyz.com
        port:
          number: 443
      weight: 100
 ```
**2.  Below config disables the retries but doesn't show the same in Istio Proxy Routes config**
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: direct-external-through-egress-gateway
  namespace: default
spec:
  gateways:
  - dev-egress-gateway
  - mesh
  hosts:
  - dev.xyz.com
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    name: nonprod-mesh
    _retries:
       attempts: 0_
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        port:
          number: 443
        subset: dev
      weight: 100
  - match:
    - gateways:
      - dev-egress-gateway
      port: 443
    name: nonprod-egress
    route:
    - destination:
        host: dev.xyz.com
        port:
          number: 443
      weight: 100
 ``` 
**3. Below config disables the retries and shows the policy block removed in Istio Proxy Route config also**
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: direct-external-through-egress-gateway
  namespace: default
spec:
  gateways:
  - dev-egress-gateway
  - mesh
  hosts:
  - dev.xyz.com
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    name: nonprod-mesh
    _retries:
       attempts: 0_
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        port:
          number: 443
        subset: dev
      weight: 100
  - match:
    - gateways:
      - dev-egress-gateway
      port: 443
    name: nonprod-egress
    _retries:
       attempts: 0_
    route:
    - destination:
        host: dev.xyz.com
        port:
          number: 443
      weight: 100
 ```
 **4. However, the expected configuration should be as below and at the same time this should show the Retry Policy block removed in Istio Envoy Proxy Routes configuration**
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: direct-external-through-egress-gateway
  namespace: default
spec:
  gateways:
  - dev-egress-gateway
  - mesh
  hosts:
  - dev.xyz.com
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    name: nonprod-mesh    
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        port:
          number: 443
        subset: dev
      weight: 100
  - match:
    - gateways:
      - dev-egress-gateway
      port: 443
    name: nonprod-egress
    _retries:
       attempts: 0_
    route:
    - destination:
        host: dev.xyz.com
        port:
          number: 443
      weight: 100
 ```

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Setting attempts = 0, for the in-mesh routes achieves the behavior of disabling the retries, but that should also get reflected in Istio Proxy Envoy routes configuration. As mentioned in the 4th scenario;
 **The expected configuration should be as below and at the same time this should show the Retry Policy block removed in Istio Envoy Proxy Routes configuration**
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: direct-external-through-egress-gateway
  namespace: default
spec:
  gateways:
  - dev-egress-gateway
  - mesh
  hosts:
  - dev.xyz.com
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    name: nonprod-mesh    
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        port:
          number: 443
        subset: dev
      weight: 100
  - match:
    - gateways:
      - dev-egress-gateway
      port: 443
    name: nonprod-egress
    _retries:
       attempts: 0_
    route:
    - destination:
        host: dev.xyz.com
        port:
          number: 443
      weight: 100
 ``` 

**Steps to reproduce the bug**
1. Use above 4 use case configuration to disable  the Retries by adding it in Egress virtual service 
2. Observe the effect of this configuration by running the command `istioctl pc routes <istio-egressgateway-pod> -o json`. You should not see any block called `retriesPolicy`.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Istio 1.8.2
K8s 1.17

**How was Istio installed?**
Using IstioOperator

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS Cloud, Centos 7

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
