### ISSUE TITLE
IST0139: Is the istio operator bumping to v1.12-alpha without my consent?

### ISSUE THREAD

**Issue by djfinnoy** [istio/istio#34709]
**Bug description**
Istio Operator pod stuck in error loop:
```
error   installer       Error during reconcile: creating default tag would conflict:
Error [IST0139] (MutatingWebhookConfiguration istio-sidecar-injector-1-11-0) Webhook overlaps with others: [istio-system/istio-sidecar-injector-1-11-0/rev.namespace.sidecar-injector.istio.io]. This may cause injection to occur twice.
Error [IST0139] (MutatingWebhookConfiguration istio-sidecar-injector-1-11-0) Webhook overlaps with others: [istio-system/istio-sidecar-injector-1-11-0/rev.object.sidecar-injector.istio.io]. This may cause injection to occur twice.
Error [IST0139] (MutatingWebhookConfiguration istio-sidecar-injector-1-11-0.istio-system ) Webhook overlaps with others: [istio-sidecar-injector-1-11-0/rev.namespace.sidecar-injector.istio.io]. This may cause injection to occur twice.
Error [IST0139] (MutatingWebhookConfiguration istio-sidecar-injector-1-11-0.istio-system ) Webhook overlaps with others: [istio-sidecar-injector-1-11-0/rev.object.sidecar-injector.istio.io]. This may cause injection to occur twice.
```

This happens on fresh cluster installations. I am not upgrading in place (at least not intentionally).
The Istio Operator gets installed via ArgoCD,  targeting the  helm chart at `manifests/charts/istio-operator`, with the `1.11.0` github tag.

When this problem first occurred, I was targeting the `1.10.1` branch. It was working fine back in late June.
When provisioning a new cluster last week, the problem above started occurring without any code changes on my end.
I suspect the problem lies with the operators behavior, and not my configuration. 

Here is my `IstioOperator` config:
```
      apiVersion: install.istio.io/v1alpha1
      kind: IstioOperator
      metadata:
        name: installation
        namespace: istio-system
        annotations:
          argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
          argocd.argoproj.io/sync-wave: "2"
      spec:
        revision: 1-11-0
        tag: latest
        profile: default
        namespace: istio-system
        defaultRevision: true
        values:
          global:
            defaultNodeSelector:
              cloud.google.com/gke-nodepool: core-workers
        components:
          pilot:
            enabled: true
          ingressGateways:
            - name: istio-ingressgateway
              enabled: true
            - name: istio-oauth-ingressgateway
              enabled: true
              label:
                app: istio-oauth-ingressgateway
                istio: oauth-ingressgateway
        meshConfig:
          extensionProviders:
            - name: oauth2-proxy
              envoyExtAuthzHttp:
                service: oauth2-proxy.oauth2-proxy.svc.cluster.local
                port: 80
                includeHeadersInCheck:
                  - authorization
                  - cookie
                includeAdditionalHeadersInCheck:
                  X-Auth-Request-Redirect: '%REQ(x-forwarded-proto)%://%REQ(:authority)%%REQ(:path)%'
                headersToUpstreamOnAllow:
                  - authorization
                  - cookie
                headersToDownstreamOnDeny:
                  - content-type
                  - set-cookie
```

Something quite odd is that when I inspect the `MutatingWebhookConfiguration` thats throwing the error, I see the following label:
`operator.istio.io/version: 1.12-alpha.79cf1c1e98faacb417928581952ea7af192e630d`.
Version 1.12-alpha is also mentioned in the `istioctl bug-report` excerpt at the bottom.

Perhaps I'm unintentionally running the 1.12 alpha version of the istio operator?
How to I get the Istio Operator to install version 1.11.0, are there any mistakes in the config above?
The deployment is running the following image: `gcr.io/istio-testing/operator:latest `

[ ] Docs
[ x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Istio Operator should install version 1.11.0, without running any upgrades that leave me with an `IST0139` error.

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**
Istio Operator installed via Helm with ArgoCD by targetting the chart under `manifests/charts/operator/` in the `1.11.0` github tag.

The `istio-system` namespace is created before the Operator is installed, there are no labels on this namespace.

**Environment where the bug was observed (cloud vendor, OS, etc)**
Google Kubernetes Engine

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

```
The following Istio control plane revisions/versions were found in the cluster:
Revision 1-11-0:
&version.MeshInfo{
    {
        Component: "istiod",
        Info:      version.BuildInfo{Version:"1.12-alpha.841df32cc3a6e88a72d3fada384ba2992fae6c9f", GitRevision:"841df32cc3a6e88a72d3fada384ba2992fae6c9f", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.12-alpha.841df32cc3a6e88a72d3fada384ba2992fae6c9f"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision 1-11-0: Versions {1.12-alpha.841df32cc3a6e88a72d3fada384ba2992fae6c9f}

```
