### ISSUE TITLE
Issue to update the **pack_trace_reason** parameter

### ISSUE THREAD

**Issue by Adaendra** [istio/istio#34772]
## Bug description
I'm trying to update the **pack_trace_reason** parameter to keep the same value in the **x-request-id** header. 
*[Envoy Documentation about pack_trace_reason](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/request_id/uuid/v3/uuid.proto#envoy-v3-api-field-extensions-request-id-uuid-v3-uuidrequestidconfig-pack-trace-reason)*

I used an EnvoyFilter to update it (with a lot of different parameters), but I have the following error
```
EnvoyFilter : could not resolve Any message type: type.googleapis.com/envoy.extensions.request_id.uuid.v3.UuidRequestIdConfig
```

I also tried with **request_id_extension** and **type_url**.
```
"@type": type.googleapis.com/udpa.type.v1.TypedStruct
type_url:type.googleapis.com/envoy.extensions.request_id.uuid.v3.UuidRequestIdConfig
```
 The EnvoyFilter can be created, but the **x-request-id** is still updated.

I don't know what else I can do to do it. At this step, I don't know if it's an error about how to create it or if it's a bug with istio.

## 
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

## 

## **Expected behavior**
To be able to apply the update of pack_trace_reason.

## **Steps to reproduce the bug**
Create an EnvoyFilter with
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: reviews-request-operation
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
    patch:
      operation: MERGE
      value:
        typed_config:
         "@type": type.googleapis.com/envoy.extensions.request_id.uuid.v3.UuidRequestIdConfig
         pack_trace_reason: false
```

## **Version** 
1.9.5

## **How was Istio installed?**
With Istio operator

**Comment by howardjohn** [comment]
could be https://github.com/istio/istio/issues/18169

**Comment by Adaendra** [comment]
About #18169, I did 2 tests: 
```yaml
 patch:
      operation: MERGE
      value:
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.request_id.uuid.v3.UuidRequestIdConfig
              value:
                pack_trace_reason: false
```

```yaml
patch:
      operation: MERGE
      value:
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          request_id_extension:
            typed_config:
              "@type": type.googleapis.com/udpa.type.v1.TypedStruct
              type_url: type.googleapis.com/envoy.extensions.request_id.uuid.v3.UuidRequestIdConfig
              value:
                pack_trace_reason: false
```

For the first one
![image](https://user-images.githubusercontent.com/36586573/130289832-4a862fce-c04e-4cbb-b29b-79138ef46562.png)

For the second one, it's like anything was set.


I also do some tests with https://github.com/istio/istio/issues/10875#issuecomment-544751041 
And it's like anything was set.
