### ISSUE TITLE
VirtualService is ignored for egress traffic

### ISSUE THREAD

**Issue by YuryHrytsuk** [istio/istio#34783]
**Bug description**
`VirtualService` is ignored when routing egress traffic.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
The request is sent to `postman-echo.com`

**Actual behavior**
The request is sent to `www.python.org`

**Steps to reproduce the bug**
1) Connect to any pod
2) Execute `curl www.python.org`

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```yaml
client version: 1.10.0
control plane version: 1.10.0
data plane version: 1.10.0 (40 proxies)
```

**How was Istio installed?**
Using `IstioOperator`

**Environment where the bug was observed (cloud vendor, OS, etc)**
Kubernetes

**Istio templates**
```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: python-external
spec:
  endpoints:
  - address: 199.232.56.223
  hosts:
  - www.python.org
  ports:
  - name: https
    number: 80
    protocol: HTTPS
    targetPort: 443
  resolution: STATIC
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: python-istio-destrule-mtls
spec:
  host: www.python.org
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 80
      tls:
        mode: SIMPLE
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: python-istio-egressgateway
spec:
  selector:
    istio: istio-egressgateway
  servers:
  - hosts:
    - www.python.org
    port:
      name: http
      number: 80
      protocol: HTTP
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: python-external-vs
spec:
  gateways:
  - python-istio-egressgateway
  - mesh
  hosts:
  - www.python.org
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: istio-egressgateway
      weight: 100
  - match:
    - gateways:
      - python-istio-egressgateway
      port: 80
    route:
    - destination:
        host: postman-echo.com
        port:
          number: 80
      weight: 100
---

```
