### ISSUE TITLE
Allow TLS traffic to egress gateway without configuring service entry for individual host

### ISSUE THREAD

**Issue by incfly** [istio/istio#34792]
**Describe the feature request**

In our [egress access control](https://istio.io/latest/docs/tasks/traffic-management/egress/egress-tls-origination/) tutorial, we want app requests go through sidecar -> egress gateway -> internet. For TLS traffic, we ask customer to configure:

1. VirtualService: route requests of `edition.cnn.com` from sidecar to egress gateway; for gateway, route it to a dedicated STRICT_DNS cluster.
2. Gateway for egress gw, hosts as `edition.cnn.com`.
3. ServiceEntry for `edition.cnn.com`. This ensures a cluster can be generated on the gateway for the requests routed to internet.

One issue for this approach is: we ask customer to configure such for each TLS website they want to access. This is because for sidecar, we use SNI filter chain match plus the dedicated clusters. All those have envoy fields filled with specific TLS website hosts directly.

This won't work if app workloads need to access a dynamic list of the TLS webiste, that can't be known beforehand.

## Solution

I am able to let sleep pod curl `https://google.com` and `https://edition.cnn.com` while without configuring anything specific to these two URL. This is done via dynamic forward filter and dynamic forward cluster[1]. The configuration for prototype is showed below.

This FR is suggesting, **instead of using EnovyFilter, we should consider to add this logic into Istiod natively.**

The details can be discussed here. My initial thought could be: if there's wildecard match in the  sniHost for gateway, we generate this dynamic forward proxy config for the gateway.

```yaml
# https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/sni_dynamic_forward_proxy_filter
# https://istio.io/latest/docs/reference/config/networking/envoy-filter/
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: egress-dynamic-forward-proxy
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: istio-egressgateway
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        portNumber: 8443 # TODO(incfly): check whether this always makes sense.
        filterChain:
          filter:
            name: "envoy.filters.network.tcp_proxy"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.network.sni_dynamic_forward_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.sni_dynamic_forward_proxy.v3alpha.FilterConfig
          port_value: 443
          dns_cache_config:
            name: dynamic_forward_proxy_cache_config
            dns_lookup_family: V4_ONLY
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        portNumber: 8443 # TODO(incfly): check whether this always makes sense.
        filterChain:
          filter:
            name: "envoy.filters.network.tcp_proxy"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy"
          statPrefix: "tcp"
          cluster: "dynamic_forward_proxy_cluster"
  - applyTo: CLUSTER
    match:
      context: GATEWAY
    patch:
      operation: ADD
      value: # cluster specification
        name: "dynamic_forward_proxy_cluster"
        lb_policy: CLUSTER_PROVIDED
        cluster_type:
          name: envoy.clusters.dynamic_forward_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
            dns_cache_config:
              name: dynamic_forward_proxy_cache_config
              dns_lookup_family: V4_ONLY
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: direct-cnn-through-egress-gateway
  namespace: default
spec:
  gateways:
  - mesh
  - istio-egressgateway
  hosts:
  # - edition.cnn.com
  - "*.com"
  tls:
  - match:
    - gateways:
      - mesh
      port: 443
      sniHosts:
      - "*.com"
      # - edition.cnn.com
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        port:
          number: 443
        subset: cnn
  - match:
    - gateways:
      - istio-egressgateway
      port: 443
      sniHosts:
      - "*.com"
      # - edition.cnn.com
    route:
    - destination:
        host: "*.com"
        # host: edition.cnn.com
        port:
          number: 443
      weight: 100

---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cnn
spec:
  hosts:
  - "*.com"
  ports:
  - number: 80
    name: http-port
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
```

**Describe alternatives you've considered**

We don't want to use ALLOW_ANY since the traffic going through egress gateway can still allow additional authorization check, saying namespace "foo" can visit https://storage.googleapis.com for GCS buckets.

I saw https://istio.io/latest/docs/tasks/traffic-management/egress/wildcard-egress-hosts/#wildcard-configuration-for-arbitrary-domains also mentioned a workaround, but this is less ideal since requiring envoyfilter and specific deployments with nginx.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by incfly** [comment]
Essentially what is used to be provided by nginx now can be done natively in Envoy. The limitation is gone.

> This is due to a limitation of Envoy, the proxy used by the default Istio egress gateway. Envoy routes traffic either to predefined hosts, predefined IP addresses, or to the original destination IP address of the request

**Comment by GregHanson** [comment]
@incfly possibly a separate issue but some overlap for the use cases.

ServiceEntry with wildcard and CIDR blocks
```
kind: ServiceEntry
spec:
  hosts:
  - "*.domain.cloud"
  addresses:
  - 22.22.0.0/24
  - 33.33.0.0/22
  location: MESH_EXTERNAL
  ports:
  - number: XXXX
    name: https
    protocol: HTTPS
  resolution: NONE
```
VirtualService to route traffic through egress gateway
```
kind: VirtualService
spec:
  hosts:
  - "*.domain.cloud"
  gateways:
  - mesh
  - istio-egressgateway
  tls:
  - match:
    - gateways:
      - mesh
      port: XXXX
      sniHosts:
      - "*.domain.cloud"
      destinationSubnets:
      - "22.22.0.0/24"
      - "33.33.0.0/22"
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        port:
          number: XXXX
  tls:
  - match:
    - gateways:
      - istio-egressgateway
      port: XXXX
      sniHosts:
      - "*.domain.cloud"
    route:
    - destination:
        host: "*.domain.cloud"
        port:
          number: XXXX
```
There could be thousands of IPs (lb appliances) associated with this particular external service.  The application's client code has already resolved an IP, and has a requirement to have all external traffic go through an egress gateway.  The original IP is lost when the request is forwarded to the egress gateway, and a valid VirtualService destination requires a resolvable hostname or a known endpoint.  Ideally, egress gateway would complete the request to the original IP called by the client.

I am still reading about the dynamic SNI filter so I don't know how easily the IP use case drops in to the proposed solution
