### ISSUE TITLE
Upgrade from 1.10 -> 1.11 w/ CNI already enabled causes "DaemonSet.apps "istio-cni-node" is invalid" error

### ISSUE THREAD

**Issue by diranged** [istio/istio#34795]
**Bug description**
When upgrading from Istio 1.10 to 1.11, we ran into a problem where the `istio-cni-node` DaemonSet could not be patched by the Operator. The error we saw was this:

```
2021-08-19T20:32:03.649762Z	info	installer	using server side apply to update obj: ServiceAccount/istio-system/istio-ingressgateway-service-account
- Processing resources for CNI.
2021-08-19T20:32:03.664956Z	info	installer	using server side apply to update obj: ConfigMap/istio-system/istio-cni-config
2021-08-19T20:32:03.672458Z	info	installer	using server side apply to update obj: ServiceAccount/istio-system/istio-public-ingressgateway-service-account
2021-08-19T20:32:03.683386Z	info	installer	using server side apply to update obj: Deployment/istio-system/istio-ingressgateway
2021-08-19T20:32:03.692884Z	info	installer	using server side apply to update obj: DaemonSet/istio-system/istio-cni-node
2021-08-19T20:32:03.735222Z	error	installer	failed to update resource with server-side apply for obj DaemonSet/istio-system/istio-cni-node: DaemonSet.apps "istio-cni-node" is invalid: spec.template.spec.containers[1].image: Required value
2021-08-19T20:32:03.735333Z	info	installer	using server side apply to update obj: RoleBinding/istio-system/istio-cni-psp
- Processing resources for CNI, Ingress gateways.
✘ CNI encountered an error: failed to update resource with server-side apply for obj DaemonSet/istio-system/istio-cni-node: DaemonSet.apps "istio-cni-node" is invalid: spec.template.spec.containers[1].image: Required value
```

This error struck us as strange because the `[1]` container is no longer defined in the cni-node template per https://github.com/istio/istio/pull/33713.

**Troubleshooting**

We ran the operator in `all:debug` log mode, and got a copy of the new DaemonSet YAML and it looked how we expected it to:

```yaml
# This manifest installs the Istio install-cni container, as well
# as the Istio CNI plugin and config on
# each master and worker node in a Kubernetes cluster.
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: istio-cni-node
  namespace: istio-system
  labels:
    k8s-app: istio-cni-node
    release: istio
    istio.io/rev: default
    install.operator.istio.io/owning-resource: unknown
    operator.istio.io/component: "Cni"
spec:
  selector:
    matchLabels:
      k8s-app: istio-cni-node
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        k8s-app: istio-cni-node
        sidecar.istio.io/inject: "false"
      annotations:
        # This, along with the CriticalAddonsOnly toleration below,
        # marks the pod as a critical add-on, ensuring it gets
        # priority scheduling and that its resources are reserved
        # if it ever gets evicted.
        scheduler.alpha.kubernetes.io/critical-pod: ''
        sidecar.istio.io/inject: "false"
        # Add Prometheus Scrape annotations
        prometheus.io/scrape: 'true'
        prometheus.io/port: "15014"
        prometheus.io/path: '/metrics'
        # Custom annotations
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        # Make sure istio-cni-node gets scheduled on all nodes.
        - effect: NoSchedule
          operator: Exists
        # Mark the pod as a critical add-on for rescheduling.
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          operator: Exists
      priorityClassName: system-node-critical
      serviceAccountName: istio-cni
      # Minimize downtime during a rolling upgrade or deletion; tell Kubernetes to do a "force
      # deletion": https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods.
      terminationGracePeriodSeconds: 5
      containers:
        # This container installs the Istio CNI binaries
        # and CNI network config file on each node.
        - name: install-cni
          image: "gcr.io/istio-release/install-cni:1.11.0"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
          command: ["install-cni"]
          env:
            # The CNI network config to install on each node.
            - name: CNI_NETWORK_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: istio-cni-config
                  key: cni_network_config
            - name: CNI_NET_DIR
              value: /etc/cni/net.d
            # Deploy as a standalone CNI plugin or as chained?
            - name: CHAINED_CNI_PLUGIN
              value: "true"
            - name: REPAIR_ENABLED
              value: "true"
            - name: REPAIR_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: REPAIR_LABEL_PODS
              value: "true"
            # Set to true to enable pod deletion
            - name: REPAIR_DELETE_PODS
              value: "true"
            - name: REPAIR_RUN_AS_DAEMON
              value: "true"
            - name: REPAIR_SIDECAR_ANNOTATION
              value: "sidecar.istio.io/status"
            - name: REPAIR_INIT_CONTAINER_NAME
              value: "istio-validation"
            - name: REPAIR_BROKEN_POD_LABEL_KEY
              value: "cni.istio.io/uninitialized"
            - name: REPAIR_BROKEN_POD_LABEL_VALUE
              value: "true"
          volumeMounts:
            - mountPath: /host/opt/cni/bin
              name: cni-bin-dir
            - mountPath: /host/etc/cni/net.d
              name: cni-net-dir
            - mountPath: /var/run/istio-cni
              name: cni-log-dir
      volumes:
        # Used to install CNI.
        - name: cni-bin-dir
          hostPath:
            path: /opt/cni/bin
        - name: cni-net-dir
          hostPath:
            path: /etc/cni/net.d
        # Used for UDS log
        - name: cni-log-dir
          hostPath:
            path: /var/run/istio-cni
```

**Fix**

Our fix was to delete the `istio-cni-node` daemonset and restart the operator.. it was then able to create the daemonset properly:

```bash
$ k delete daemonset istio-cni-node && k -n istio-operator rollout restart deployment/istio-operator
daemonset.apps "istio-cni-node" deleted
deployment.apps/istio-operator restarted
# ... sleep ...
$ k get pods
NAME                                          READY   STATUS    RESTARTS   AGE
istio-cni-node-27jb9                          1/1     Running   0          23s
istio-cni-node-64xvt                          1/1     Running   0          23s
istio-cni-node-6q8lt                          1/1     Running   0          23s
istio-cni-node-9p9rl                          1/1     Running   0          23s
istio-cni-node-g6whc                          1/1     Running   0          23s
istio-cni-node-g7rxb                          1/1     Running   0          23s
istio-cni-node-jz4cg                          1/1     Running   0          23s
istio-cni-node-kqpgc                          1/1     Running   0          23s
istio-cni-node-wdd4z                          1/1     Running   0          23s
istio-cni-node-whlzw                          1/1     Running   0          23s
istio-cni-node-zwqmk                          1/1     Running   0          23s
istio-ingressgateway-7b5bb5986d-ltppk         1/1     Running   0          48m
istio-ingressgateway-7b5bb5986d-ntcs9         1/1     Running   0          76m
istio-ingressgateway-7b5bb5986d-tw4wx         1/1     Running   0          76m
istio-public-ingressgateway-75df697f7-bnbw4   1/1     Running   0          76m
istio-public-ingressgateway-75df697f7-hfsrs   1/1     Running   0          47m
istio-public-ingressgateway-75df697f7-j82t5   1/1     Running   0          76m
istiod-d5fd69468-5j9hc                        1/1     Running   0          47m
istiod-d5fd69468-wl6k6                        1/1     Running   0          76m
kiali-7c55968fbc-9h5bh                        1/1     Running   0          5h29m
$ k describe pod istio-cni-node-27jb9 
Name:                 istio-cni-node-27jb9
Namespace:            istio-system
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 ip-10-32-17-88.us-west-2.compute.internal/10.32.17.88
Start Time:           Thu, 19 Aug 2021 15:11:15 -0700
Labels:               app=istio-cni-node
                      controller-revision-hash=98874475d
                      k8s-app=istio-cni-node
                      pod-template-generation=1
                      sidecar.istio.io/inject=false
Annotations:          kubernetes.io/psp: eks.privileged
                      prometheus.io/path: /metrics
                      prometheus.io/port: 15014
                      prometheus.io/scrape: true
                      scheduler.alpha.kubernetes.io/critical-pod: 
                      sidecar.istio.io/inject: false
Status:               Running
IP:                   100.64.31.79
IPs:
  IP:           100.64.31.79
Controlled By:  DaemonSet/istio-cni-node
```

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
I'm guessing there is a merge issue with the way the operator is trying to update the `istio-cni-node` resource. Rather than merging against whatever is in Kubernetes, I would expect it to replace it.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```bash
$ istioctl version --remote
client version: 1.10.0
control plane version: 1.11.0
data plane version: 1.11.0 (6 proxies), 1.11-alpha.0bf5210b6d18b8426d715fd182ce5ba0084d5b77 (7 proxies)
$ kubectl version --short
Client Version: v1.21.1
Server Version: v1.21.2-eks-0389ca3
$ helm version --short
v3.5.4+g1b5edb6

```
**How was Istio installed?**

Using ArgoCD to launch the Istio Operator, and ArgoCD to launch our various Istio resources.

**Comment by richardwxn** [comment]
I cannot reproduce the issue between 1.10 and 1.11..What is the IstioOperator definition you are using?

How did you install 1.10 before, with Istioctl or operator? Seems like you already delete the original daemonset, but can you reproduce and send the manifest yaml before and after upgrade(include managedFields section please).

**Comment by diranged** [comment]
@richardwxn Thanks for the response.. so we have 9 clusters in total. This failed upgrade behavior happened on our 3 development/test clusters, but interestingly did not happen on our production clusters as we rolled the change out. I couldn't tell you why, it was really strange.

A few quick notes, we actually were upgrading from `1.11-alpha.0bf5210b6d18b8426d715fd182ce5ba0084d5b77` to `1.11.0`. My mistake -  when I wrote this up I meant to fix that, and I forgot to go back and adjust it. Perhaps that makes a meaningful difference in how the change happened. 

To answer your questions, we are using ArgoCD to deploy the Istio Operator as one `Application`[1]. We then use ArgoCD to deploy a separate `Application` that creates our `IstioOperator` resource[2] and all of the supporting resources. (Of course, Argo like K8S doesn't guarantee ordering.. so its always possible that the Operator process began slightly after the Istio application upgrade started).

Lastly - unfortunately I did delete the `DaemonSet`'s to move through the problem. That said, here are the current DaemonSet annotations/labels.
```
$ k get ds istio-cni-node -o yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "3"
...
  creationTimestamp: "2021-08-19T22:11:15Z"
  generation: 3
  labels:
    install.operator.istio.io/owning-resource: istio-control-plane
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio.io/rev: default
    k8s-app: istio-cni-node
    operator.istio.io/component: Cni
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.11.0
    release: istio
  name: istio-cni-node
  namespace: istio-system
  resourceVersion: "238382828"
  uid: 56c1ebdb-5362-4e40-b851-b459215b3dff
spec:
```

[1]: Here is our Istio Operator `Application` in ArgoCD:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-operator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Release.Name }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: istio-operator
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  # istio modifies the NS once its created.. so we just let helm create it once and then walk away
  source:
    path: vendor/istio/istio-1.11.0
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      values: |
        operatorNamespace: istio-operator
        watchedNamespaces: istio-system
        hub: gcr.io/istio-release
        waitForResourcesTimeout: 3600s  # default: 300s
```

Here is a copy of our primary IstioOperator resource:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-control-plane
spec:
  profile: default
  hub: {{ .Values.image.hub }}
  tag: {{ .Values.image.tag }}
  meshConfig:
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    enableTracing: true
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: 'true'
        ISTIO_META_DNS_AUTO_ALLOCATE: 'true'
  values:
    global:
      logAsJson: true
      proxy:
        excludeIPRanges: 172.20.0.1/32
      tracer:
        zipkin:
          address: jaeger-collector:9411
    cni:
      psp_cluster_role: eks:podsecuritypolicy:privileged
      excludeNamespaces:
        - {{ .Release.Namespace }}
        - kube-system
        - default
        - prometheus
        - prometheus-operator
  components:
    pilot:
      enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2  # default is 1
          maxReplicas: 5  # default is 1
        podDisruptionBudget:
          minAvailable:  1
        env:
          - name: PILOT_ENABLE_REDIS_FILTER
            value: 'true'
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            # cpu: 500m
            memory: 2Gi
    cni:
      enabled: true
      k8s:
        tolerations:
          - operator: Exists
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            # cpu: 512m
            memory: 256Mi
    ingressGateways:
      - enabled: true
        name: istio-ingressgateway
        k8s:
          resources:
            {{- .Values.istio_ingressgateway.resources | toYaml | nindent 12 }}
          hpaSpec:
            {{- .Values.istio_ingressgateway.hpaSpec | toYaml | nindent 12 }}
          podDisruptionBudget:
            {{- .Values.istio_ingressgateway.podDisruptionBudget | toYaml | nindent 12 }}
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      # matches deployment selectors
                      - {key: app, operator: In, values: [istio-ingressgateway]}
                      - {key: istio, operator: In, values: [ingressgateway]}
                  topologyKey: kubernetes.io/hostname
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                      - {key: app, operator: In, values: [istio-ingressgateway]}
                      - {key: istio, operator: In, values: [ingressgateway]}
                    topologyKey: failure-domain.beta.kubernetes.io/zone
          strategy:
            type: RollingUpdate
            rollingUpdate:
              maxUnavailable: 0
              maxSurge: 10%
          overlays:
            - apiVersion: apps/v1
              kind: Deployment
              name: istio-ingressgateway
              patches:
                - path: spec.minReadySeconds
                  value: 150
          service:
            ports:
              - port: 80
                targetPort: 8080
                name: http2
                protocol: TCP
              - port: 443
                targetPort: 8443
                name: https
                protocol: TCP

          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
            service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
            service.beta.kubernetes.io/aws-load-balancer-internal: 'true'
            service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
            service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: deregistration_delay.connection_termination.enabled=true,deregistration_delay.timeout_seconds=120
            service.beta.kubernetes.io/aws-load-balancer-ssl-ports: '443'
            service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: traffic-port
            service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /
            service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: TCP
            service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: '10'
            service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: '10'
            service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: '2'
            service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: '2'
            service.beta.kubernetes.io/aws-load-balancer-alpn-policy: HTTP2Preferred
            service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl

      - enabled: true
        name: istio-public-ingressgateway
        label:
          istio: public-ingressgateway
        k8s:
          resources:
            {{- .Values.istio_ingressgateway.resources | toYaml | nindent 12 }}
          hpaSpec:
            {{- .Values.istio_ingressgateway.hpaSpec | toYaml | nindent 12 }}
          podDisruptionBudget:
            {{- .Values.istio_ingressgateway.podDisruptionBudget | toYaml | nindent 12 }}
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      # matches deployment selectors
                      - {key: app, operator: In, values: [istio-ingressgateway]}
                      - {key: istio, operator: In, values: [public-ingressgateway]}
                  topologyKey: kubernetes.io/hostname
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                      - {key: app, operator: In, values: [istio-ingressgateway]}
                      - {key: istio, operator: In, values: [public-ingressgateway]}
                    topologyKey: failure-domain.beta.kubernetes.io/zone
          strategy:
            type: RollingUpdate
            rollingUpdate:
              maxUnavailable: 0
              maxSurge: 10%
          overlays:
            - apiVersion: apps/v1
              kind: Deployment
              name: istio-public-ingressgateway
              patches:
                - path: spec.minReadySeconds
                  value: 150

          service:
            ports:
              - port: 80
                targetPort: 8080
                name: http2
                protocol: TCP
              - port: 443
                targetPort: 8443
                name: https
                protocol: TCP

          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
            service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
            service.beta.kubernetes.io/aws-load-balancer-internal: 'false'
            service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: deregistration_delay.connection_termination.enabled=true,deregistration_delay.timeout_seconds=120
            service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'false'
            service.beta.kubernetes.io/aws-load-balancer-ssl-ports: '443'
            service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: traffic-port
            service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /
            service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: TCP
            service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: '10'
            service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: '10'
            service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: '2'
            service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: '2'
            service.beta.kubernetes.io/aws-load-balancer-alpn-policy: HTTP2Preferred
            service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
``
