### ISSUE TITLE
Not able to connect to Oracle cluster DB using SCAN IP Address using external service and Istio service  entry  

### ISSUE THREAD

**Issue by nataraj24** [istio/istio#34827]
Any resolution for the above issue.  envoy is not able to connect to three scan ip address which is getting returned and database connection is not happening.

_Originally posted by @nataraj24 in https://github.com/istio/istio/issues/12350#issuecomment-903599823_

**Comment by alexisph** [comment]
I had this same issue and was able to find a solution.

Due to the way the connection is created when using [Oracle SCANs](https://docs.oracle.com/en/database/oracle/oracle-database/12.2/rilin/how-database-connections-are-created-when-using-scans.html#GUID-DDA82589-44DB-4681-B0BC-32898D3083BA), the client connects to the SCAN host, which directs the client to the most appropriate database server. The solution:

1. Created ServiceEntries for all hosts in the database cluster (SCAN host, database instances etc.) with TCP protocol, static IPs and static resolution
2. (optional) Created a mTLS Gateway to listen for traffic on TLS 443 for all the hosts defined in the ServiceEntries above
3. Created a Destinationrule per host defined in the ServiceEntries
4. (optional) Created a VirtualService to route TCP traffic, matching destinationSubnets and port from the mesh to the Gateway
5. Created a VirtualService to route TCP traffic, matching destinationSubnets and port from the Gateway to the external hosts

**Comment by michael-wirth** [comment]
I face the same issue...

@alexisph could you provide a yaml sample of your service entry configurations?

**Comment by alexisph** [comment]
> I face the same issue...
> 
> @alexisph could you provide a yaml sample of your service entry configurations?

Based on this: https://docs.oracle.com/en/database/oracle/oracle-database/12.2/rilin/how-database-connections-are-created-when-using-scans.html#GUID-DDA82589-44DB-4681-B0BC-32898D3083BA

```yaml
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: oracle-scan-host
spec:
  hosts:
  - scan.domain.tld
  addresses:
  - 10.0.0.10
  - 10.0.0.11
  - 10.0.0.12
  ports:
  - name: tcp-db
    number: 1521
    protocol: TCP
  resolution: STATIC
  endpoints:
  - 10.0.0.10
  - 10.0.0.11
  - 10.0.0.12
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: oracle-db-instance01
spec:
  hosts:
  - db01.domain.tld
  addresses:
  - 10.0.0.20
  ports:
  - name: tcp-db
    number: 1521
    protocol: TCP
  resolution: STATIC
  endpoints:
  - 10.0.0.20
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: oracle-db-instance02
spec:
  hosts:
  - db02.domain.tld
  addresses:
  - 10.0.0.21
  ports:
  - name: tcp-db
    number: 1521
    protocol: TCP
  resolution: STATIC
  endpoints:
  - 10.0.0.21
```
