### ISSUE TITLE
the gateway does not work after global Rate limit is used

### ISSUE THREAD

**Issue by xichengliudui** [istio/istio#34824]
**Bug description**
access in sleep pod
```
/ $ curl -vv -H 'Host: productpage.com'  http://istio-ingressgateway.istio-system:80/productpage
*   Trying 10.102.196.47:80...
* Connected to istio-ingressgateway.istio-system (10.102.196.47) port 80 (#0)
> GET /productpage HTTP/1.1
> Host: productpage.com
> User-Agent: curl/7.78.0-DEV
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< date: Mon, 23 Aug 2021 06:53:17 GMT
< server: envoy
< content-length: 0
< x-envoy-upstream-service-time: 0
<
* Connection #0 to host istio-ingressgateway.istio-system left intact
```
**istio-ingressgateway log**
```
[2021-08-23T09:05:08.139Z] "GET /productpage HTTP/1.1" 500 - rate_limiter_error - "-" 0 0 0 - "10.0.140.71" "curl/7.78.0-DEV" "2e15abca-fa7d-90c8-bb20-017fed3ace76" "productpage.com" "-" outbound|9080||productpage.sun-system.svc.cluster.local - 10.0.140.105:8080 10.0.140.71:51496 - -
```
I failed to access productpage using the gateway after setting the global rate limit according to the document.(I'm not using local rate limit)
here is the configuration I used
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
  namespace: sun-system
data:
  config.yaml: |
    domain: productpage-ratelimit
    descriptors:
      - key: PATH
        value: "/productpage"
        rate_limit:
          unit: minute
          requests_per_unit: 1
      - key: PATH
        rate_limit:
          unit: minute
          requests_per_unit: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-ratelimit
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        # Adds the Envoy Rate Limit Filter in HTTP filter chain.
        value:
          name: envoy.filters.http.ratelimit
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
            domain: productpage-ratelimit
            failure_mode_deny: true
            timeout: 10s
            rate_limit_service:
              grpc_service:
                envoy_grpc:
                  cluster_name: rate_limit_cluster
              transport_api_version: V3
    - applyTo: CLUSTER
      match:
        cluster:
          service: ratelimit.default.svc.cluster.local
      patch:
        operation: ADD
        value:
          name: rate_limit_cluster
          type: STRICT_DNS
          connect_timeout: 10s
          lb_policy: ROUND_ROBIN
          http2_protocol_options: {}
          load_assignment:
            cluster_name: rate_limit_cluster
            endpoints:
            - lb_endpoints:
              - endpoint:
                  address:
                     socket_address:
                      address: ratelimit.default.svc.cluster.local
                      port_value: 8081
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-ratelimit-svc
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: VIRTUAL_HOST
      match:
        context: GATEWAY
        routeConfiguration:
          vhost:
            name: ""
            route:
              action: ANY
      patch:
        operation: MERGE
        # Applies the rate limit rules.
        value:
          rate_limits:
            - actions:
              - request_headers:
                  header_name: ":path"
                  descriptor_key: "PATH"
```

**Affected product area (please put an X in all that apply)**

[x] Docs

**Affected features (please put an X in all that apply)**

[x] Virtual Machine

**Steps to reproduce the bug**
1: install bookinfo system
2: apply the yaml above

**Version**
```
client version: 1.11.0
control plane version: 1.11.0
data plane version: 1.11.0 (9 proxies)
```

**How was Istio installed?**
istio operator init，profile is default

**Environment where the bug was observed (cloud vendor, OS, etc)**
centos7.4
