### ISSUE TITLE
Use gateway injection for east-west gatewat

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#34835]
We should update the `samples/multicluster/gen-eastwest-gateway.sh` to follow the gateway injection mechanism, as done in https://istio.io/latest/docs/setup/additional-setup/gateway/
cc @stevenctl

**Comment by nicole-lihui** [comment]
I want to try it, but i have no experience. so i need to sure the issue's change scope.
try to analyze it, i should need to modify three points:

1. like ingress/egress gateways, to create templates, the path is manifests/charts/gateways/istio-eastwest/templates
2. change samples/multicluster/gen-eastwest-gateway.sh
3. to confirm istio opreator if support the settings(modify istio-ingressgateway to istio-eastwestgateway), and to change it

@howardjohn the above are just personal thoughts, i need your help and advice

**Comment by stevenctl** [comment]
To add another first-class gateway type I think the IstioOperator API would also change. 

https://github.com/istio/api/blob/0ee0abf2a92d477d8b0ed54b02c418929c3dd5cb/operator/v1alpha1/operator.proto#L174-L175


The simplest version of this is just to set the template name:

https://github.com/istio/istio/blob/fa911b97449b5f793deabd964f9bfa89e48b9ad1/samples/multicluster/gen-eastwest-gateway.sh#L128-L136

Although I wonder if we can get rid of a lot of the script by adding not another full template, but instead using a specialized injection template like [/manifests/charts/istio-control/istio-discovery/files/gateway-injection-template.yaml](https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/files/gateway-injection-template.yaml)

**Comment by howardjohn** [comment]
oh we are already setting the injection template? so injection is used,
right? I had missed that

**Comment by stevenctl** [comment]
Yep, in the most basic way. But if possible I want to get rid of the script entirely.

**Comment by howardjohn** [comment]
so is the only thing we need `topology.istio.io/network` and
REQUESTED_NETWORK_VIEW? The rest is injected?

**Comment by stevenctl** [comment]
Yeah we can update the docs to have users apply the following:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: eastwest
spec:
  revision: "${REVISION}"
  profile: empty
  components:
    ingressGateways:
      - name: istio-eastwestgateway
        label:
          istio: eastwestgateway
          app: istio-eastwestgateway
          topology.istio.io/network: $NETWORK
  values:
    gateways:
      istio-ingressgateway:
        injectionTemplate: gateway
```

It's a little different when doing single-network with VMs, but ideally we start to recommend _always_ having some value for network. Need to solve upgrading from that case to the new case though. I'm pretty sure it should _just work_ if you don't already have a network-gateway though.
