### ISSUE TITLE
Add resource limit and request to CNI DaemonSet

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#34833]
Istio CNI lacks resource limit and request, which does not follow the best practice. We need to find an appropriate resource limit and requests and add them.

**Comment by Ruoyu-y** [comment]
I would like to try on that. Shall we first use kubectl top to track the current resource consumed?

**Comment by bianpengyuan** [comment]
Yeah CNI resource consumption is minimum. We can start with something small and safe: e.g.

```yaml
limits:
  cpu: 200m
  memory: 128M
requests:
  cpu: 100m
  memory: 64Mi
```
