### ISSUE TITLE
Misnamed ports cause ingress gateway to bypass sidecars

### ISSUE THREAD

**Issue by malcolmrebughini** [istio/istio#34870]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

When a VirtualService attached to a Gateway points to a Service whose the port doesn't follow the naming convention, all traffic bypasses the sidecar completely. This was extremely hard to debug and I can't find no mention in the docs of this misconfiguration causing such an issue.

There are mentions of similar issues [here](https://github.com/istio/istio/issues/34620) and [here](https://discuss.istio.io/t/istio-1-6-0-traffic-seems-to-bypass-sidecar/6973)

Worth noting is it happens only with traffic inside the mesh, we had a TargetGroupBinding from aws-load-balancer-controller pointing directly to a Service and the sidecar was processing and logging the traffic correctly. 

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Ideally communication to the Service should fail and an error should be logged.

**Steps to reproduce the bug**

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-api-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "httpbin-dev.somehost.com"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpbin-api-rules
  namespace: istio-system
spec:
  gateways:
    - httpbin-api-gateway
  hosts:
    - httpbin-dev.somehost.com
  http:
    - name: httpbin-test
      rewrite:
        uri:  /
      match:
        - uri:
            prefix: /httpbin
      route:
        - destination:
            host: httpbin.httpbin.svc.cluster.local
            port:
              number: 8080
---
apiVersion: v1
kind: Namespace
metadata:
  name: httpbin
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
  namespace: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: httpbin
  labels:
    app: httpbin
    service: httpbin
spec:
  ports:
  - name: something-http
    port: 8080
    targetPort: 80
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      serviceAccountName: httpbin
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80
```

Then hit the /httpbin uri, logs appear at the ingressgateway but not at the sidecar of httpbin

**Version** 
Istio 1.8.2

Chart versions:
base-1.1.0
istio-ingress-1.1.0
istio-discovery-1.2.0

**How was Istio installed?**
Helm

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS EKS

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
I could not reproduce this, and this doesn't align with my expectations of how Istio works. The port name is (supposed to be) irrelevant to whether the traffic is capture by iptables. I used ` ~/istio/istio-1.8.6/bin/istioctl install -y --set meshConfig.accessLogFile=/dev/stdout` on GKE, then applied the config above (thanks for the easy repro!) and saw access logs in the sidecar after sending requests to the gateway.

Maybe you can attach an `istioctl bug-report` to give more info

**Comment by malcolmrebughini** [comment]
@howardjohn thanks for the quick response.

That is really interesting, could the issue be with the helm charts?

Our installation was the following:

```
helm upgrade --install -n istio-system istio-base ./istio-${ISTIO_VERSION}/manifests/charts/base
helm upgrade --install -n istio-system istiod ./istio-${ISTIO_VERSION}/manifests/charts/istio-control/istio-discovery --values=./istiod-values.yaml
helm upgrade --install -n istio-system istio-ingress ./istio-${ISTIO_VERSION}/manifests/charts/gateways/istio-ingress --values=./istio-ingress-values.yaml
helm upgrade --install -n istio-system istio-ingress-noauth ./istio-${ISTIO_VERSION}/manifests/charts/gateways/istio-ingress  --values=./istio-ingress-noauth-values.yaml
```
istiod-values.yaml:
```
meshConfig:
  accessLogFile: "/dev/stdout"
  accessLogEncoding: "JSON"

global:
  imagePullPolicy: IfNotPresent
  proxy:
    holdApplicationUntilProxyStarts: true
    lifecycle:
      postStart:
        exec:
          # This hook serves the same purpose as holdApplicationUntilProxyStarts.
          # For some reason both need to be present or restarts will happen when the pod is starting.
          command:
          - pilot-agent
          - wait
      preStop:
        exec:
          # This preStop hook will wait for application connections to be drained before stopping the container.
          command:
            - /bin/sh
            - -c
            - sleep 20; while [ $(netstat -plunt | grep tcp | grep -v envoy | wc -l | xargs) -ne 0 ]; do sleep 1; done


pilot:
  autoscaleMin: 2
```

istio-ingress-values.yaml:
```
gateways:
  istio-ingressgateway:
    autoscaleMin: 4
    autoscaleMax: 20
    ports:
    - name: status-port
      # setting nodeport so that target group in AWS can be configured to point to this port
      nodePort: 31413
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
    - name: tls
      port: 15443
      protocol: TCP
      targetPort: 15443
```
istio-ingress-noauth-values.yaml
```
gateways:
  istio-ingressgateway:
    name: istio-ingressgateway-noauth
    labels:
      app: istio-ingressgateway-noauth
      istio: ingressgateway-noauth
    autoscaleMin: 4
    autoscaleMax: 20
    ports:
    - name: status-port
      nodePort: 30206
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
    - name: tls
      port: 15443
      protocol: TCP
      targetPort: 15443
```


Notice that we have two ingress gateways, the issue occurred with the one that has the suffix -noauth. Didn't test if the issue manifested in the other ingress, but I'll check soon and report back.

Hopefully this allows you to reproduce the issue.
