### ISSUE TITLE
gateway-api gateway listeners tls routeOverride certificate allow,the certificate is not override?

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#34884]
**Bug description**
gateway-api gateway listeners tls routeOverride certificate allow,the certificate is not override?

[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
override the certificate
**Steps to reproduce the bug**
```
cd certs

openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048  -keyout cert.key -out cert.crt  -config  openssl.conf

创建secret

kubectl create -n istio-system secret tls bookinfo-gateway-secret  --key ./cert.key --cert=./cert.crt

cd http-certs

openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048  -keyout cert.key -out cert.crt  -config  openssl.conf

创建secret

kubectl create -n istio-system secret tls bookinfo-gateway-secret-http  --key ./cert.key --cert=./cert.crt





gateway/bookinfo-gateway-listeners-tls-routeOverride-certificate-Allow.yaml

kubectl apply -f bookinfo-gateway-listeners-tls-routeOverride-certificate-Allow.yaml -n istio-system


kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: bookinfo
spec:
  gatewayClassName: istio
  listeners:  
  - hostname: "*"
    port: 443
    protocol: HTTPS
    tls:
      routeOverride: 
        certificate: Allow
      mode: Terminate
      certificateRef:
        name: bookinfo-gateway-secret
        kind: Secret
        group: core 
    routes:
      namespaces:
        from: All
      selector:
        matchLabels:
          gateway: bookinfo
      kind: HTTPRoute


gatewayclass/isito-gc.yaml

kubectl apply -f isito-gc.yaml -n istio-system


apiVersion: networking.x-k8s.io/v1alpha1
kind: GatewayClass
metadata:
  name: istio
spec:
  controller: istio.io/gateway-controller


gateway/productpage-http-route-with-tls.yaml 

kubectl apply -f productpage-http-route-with-tls.yaml -n istio


kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: productpage
  labels:
    gateway: bookinfo
spec:
  gateways:
    allow: All
  hostnames: ["*"]
  tls:
    certificateRef:
      name: bookinfo-gateway-secret-http
      kind: Secret
      group: core  
  rules:
  - matches:
    - path:
        type: Prefix
        value: /productpage
    - path:
        type: Prefix
        value: /static
    forwardTo:
    - serviceName: productpage
      port: 9080



```

![1629954379(1)](https://user-images.githubusercontent.com/31508490/130904050-347e7707-4203-4025-bb65-c4dcc0601402.jpg)

the secret is bookinfo-gateway-secret not bookinfo-gateway-secret-http

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
istio 1.11.0
**How was Istio installed?**
istioctl install --set profile=demo
**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
