### ISSUE TITLE
gateway-api gateway listener routes namespace from Same,got 503

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#34881]
**Bug description**
gateway-api gateway listener routes namespace from Same,got 503

[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
can visite
**Steps to reproduce the bug**
```
gateway/bookinfo-gateway-listeners-routes-namespaces-Sames.yaml

kubectl apply -f bookinfo-gateway-listeners-routes-namespaces-Same.yaml -n istio-system


kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: bookinfo
spec:
  gatewayClassName: istio
  listeners:  
  - hostname: "*"
    port: 80
    protocol: HTTP
    routes:
      namespaces:
        from: Same
      selector:
        matchLabels:
          gateway: bookinfo
      kind: HTTPRoute
      group: networking.x-k8s.io


gatewayclass/isito-gc.yaml

kubectl apply -f isito-gc.yaml -n istio-system

apiVersion: networking.x-k8s.io/v1alpha1
kind: GatewayClass
metadata:
  name: istio
spec:
  controller: istio.io/gateway-controller


gateway/productpage-http-route.yaml

kubectl apply -f productpage-http-route.yaml -n istio-system

kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: productpage
  labels:
    gateway: bookinfo
spec:
  gateways:
    allow: All
  hostnames: ["*"]
  rules:
  - matches:
    - path:
        type: Prefix
        value: /productpage
    - path:
        type: Prefix
        value: /static
    forwardTo:
    - serviceName: productpage.istio.svc.cluster.local
      port: 9080


访问

 HTTP ERROR 503 找不到服务
```

the httproute serviceName is productpage.istio.svc.cluster.local,but in the envoy config,it is outbound|9080||productpage.istio-system.svc.cluster.local

![1629951348(1)](https://user-images.githubusercontent.com/31508490/130899715-48c8036c-cf44-4c82-acca-b76ec27c3fcb.jpg)

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
istio 1.11.0
**How was Istio installed?**
istioctl install --set profile=demo
**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
