### ISSUE TITLE
gateway-api whne httproute hosts is *.demo, can not visit url http://bookinfo.demo:30902/productpage,got 404

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#34886]
**Bug description**
gateway-api whne httproute hosts is *.demo, can not visit url http://bookinfo.demo:30902/productpage,got 404

[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
can visit
**Steps to reproduce the bug**
```
httproute/productpage-httproute-hostnames-semi-star.yaml

kubectl apply -f productpage-httproute-hostnames-semi-star.yaml -n istio


kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: productpage
  labels:
    gateway: bookinfo
spec:
  gateways:
    allow: All
  hostnames: ["*.demo"] 
  rules:
  - matches:
    - path:
        type: Prefix
        value: /productpage
    - path:
        type: Prefix
        value: /static
    forwardTo:
    - serviceName: productpage
      port: 9080


gateway/bookinfo-gateway-listeners-protocol-http.yaml

kubectl apply -f bookinfo-gateway-listeners-protocol-http.yaml -n istio-system


kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: bookinfo
spec:
  gatewayClassName: istio
  listeners:  
  - hostname: "*"
    port: 80
    protocol: HTTP
    routes:
      namespaces:
        from: All
      selector:
        matchLabels:
          gateway: bookinfo
      kind: HTTPRoute


gatewayclass/isito-gc.yaml

kubectl apply -f isito-gc.yaml -n istio-system


apiVersion: networking.x-k8s.io/v1alpha1
kind: GatewayClass
metadata:
  name: istio
spec:
  controller: istio.io/gateway-controller



```
![1629958306(1)](https://user-images.githubusercontent.com/31508490/130910322-68f7467c-f16e-4fe1-853a-09e6a0f3b067.jpg)

only 80 port is effective

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
istio 1.11.0
**How was Istio installed?**
istioctl install --set profile=demo
**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
