### ISSUE TITLE
gateway-api gateway listeners routes selector matchExpressions in,httproute is not effective ,got 404

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#34882]
**Bug description**
gateway-api gateway listeners routes selector matchExpressions in,httproute is not effective ,got 404

[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
httproute is valid,and can visit
**Steps to reproduce the bug**
```
gateway/bookinfo-gateway-listeners-routes-selector-matchExpressions.yaml

kubectl apply -f bookinfo-gateway-listeners-routes-selector-matchExpressions.yaml -n istio-system


kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: bookinfo
spec:
  gatewayClassName: istio
  listeners:  
  - hostname: "*"
    port: 80
    protocol: HTTP
    routes:
      namespaces:
        from: All
      selector:
        matchExpressions:
        - key: gateway
          operator: in
          values:
          - bookinfo
      kind: HTTPRoute
      group: networking.x-k8s.io


gatewayclass/isito-gc.yaml

kubectl apply -f isito-gc.yaml -n istio-system


apiVersion: networking.x-k8s.io/v1alpha1
kind: GatewayClass
metadata:
  name: istio
spec:
  controller: istio.io/gateway-controller


gateway/productpage-http-route.yaml

kubectl apply -f productpage-http-route.yaml -n istio


kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: productpage
  labels:
    gateway: bookinfo
spec:
  gateways:
    allow: All
  hostnames: ["*"]
  rules:
  - matches:
    - path:
        type: Prefix
        value: /productpage
    - path:
        type: Prefix
        value: /static
    forwardTo:
    - serviceName: productpage
      port: 9080
```

```
Status:
  Gateways:
    Conditions:
      Last Transition Time:  2021-08-26T04:05:25Z
      Message:               Route was valid
      Observed Generation:   28
      Reason:                RouteAdmitted
      Status:                True
      Type:                  Admitted
    Gateway Ref:
      Controller:  istio.io/gateway-controller
      Name:        bookinfo
      Namespace:   istio-system
```

![1629952155(1)](https://user-images.githubusercontent.com/31508490/130900771-3c69ac77-71ad-4891-9f6a-64c482ce68d8.jpg)

```
**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
istio 1.11.0
**How was Istio installed?**
istioctl install --set profile=demo
**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
