### ISSUE TITLE
gateway-api tcproute gateways allow: SameNamespace,can not telnet

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#34888]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
gateway-api tcproute gateways allow: SameNamespace,can not telnet
**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
can telnet 
**Steps to reproduce the bug**
```
tcproute/echo-tcproute-gateways-allow-SameNamespace.yaml

kubectl apply -f echo-tcproute-gateways-allow-SameNamespace.yaml  -n istio-system


kind: TCPRoute
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: echo
  labels:
    gateway: echo
spec:
  gateways:
    allow: SameNamespace
  rules:
  - forwardTo:
    - serviceName: tcp-echo.istio.svc.cluster.local
      port: 9000


gateway/bookinfo-gateway-listeners-protocol-TCP.yaml

kubectl apply -f bookinfo-gateway-listeners-protocol-TCP.yaml -n istio-system


kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: echo
spec:
  gatewayClassName: istio
  listeners:
  - protocol: TCP
    port: 15443
    routes:
      namespaces:
        from: All
      kind: TCPRoute
      selector:
        matchLabels:
          gateway: echo


gatewayclass/isito-gc.yaml

kubectl apply -f isito-gc.yaml -n istio-system


apiVersion: networking.x-k8s.io/v1alpha1
kind: GatewayClass
metadata:
  name: istio
spec:
  controller: istio.io/gateway-controller


tcp-echo-services.yaml

kubectl  apply -f tcp-echo-services.yaml -n istio


apiVersion: v1
kind: Service
metadata:
  name: tcp-echo
  labels:
    app: tcp-echo
    service: tcp-echo
spec:
  ports:
  - name: tcp
    port: 9000
  - name: tcp-other
    port: 9001
  # Port 9002 is omitted intentionally for testing the pass through filter chain.
  selector:
    app: tcp-echo

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-echo-v1
  labels:
    app: tcp-echo
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp-echo
      version: v1
  template:
    metadata:
      labels:
        app: tcp-echo
        version: v1
    spec:
      containers:
      - name: tcp-echo
        image: docker.io/istio/tcp-echo-server:1.2
        imagePullPolicy: IfNotPresent
        args: [ "9000,9001,9002", "one" ]
        ports:
        - containerPort: 9000
        - containerPort: 9001

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-echo-v2
  labels:
    app: tcp-echo
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp-echo
      version: v2
  template:
    metadata:
      labels:
        app: tcp-echo
        version: v2
    spec:
      containers:
      - name: tcp-echo
        image: docker.io/istio/tcp-echo-server:1.2
        imagePullPolicy: IfNotPresent
        args: [ "9000,9001,9002", "two" ]
        ports:
        - containerPort: 9000
        - containerPort: 9001



```

![1629964603(1)](https://user-images.githubusercontent.com/31508490/130924572-f67a2c13-e56f-4b9e-ad01-99a581efe98d.jpg)

serviceName: tcp-echo.istio.svc.cluster.local
cluster: "outbound|9000||tcp-echo.istio.svc.cluster.local.istio-system.svc.cluster.local",

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
istio 1.11.0
**How was Istio installed?**
istioctl install --set profile=demo
**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
