### ISSUE TITLE
gateway-api httproute gateways SameNamespace,got 503

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#34885]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
gateway-api httproute gateways SameNamespace,got 503
**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
can visit
**Steps to reproduce the bug**
```
httproute/productpage-httproute-gateways-allow-SameNamespace.yaml

kubectl apply -f productpage-httproute-gateways-allow-SameNamespace.yaml -n istio-system


kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: productpage
  labels:
    gateway: bookinfo
spec:
  gateways:
    allow: SameNamespace
  hostnames: ["*"] 
  rules:
  - matches:
    - path:
        type: Prefix
        value: /productpage
    - path:
        type: Prefix
        value: /static
    forwardTo:
    - serviceName: productpage.istio.svc.cluster.local
      port: 9080


gateway/bookinfo-gateway-listeners-protocol-http.yaml

kubectl apply -f bookinfo-gateway-listeners-protocol-http.yaml -n istio-system


kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: bookinfo
spec:
  gatewayClassName: istio
  listeners:  
  - hostname: "*"
    port: 80
    protocol: HTTP
    routes:
      namespaces:
        from: All
      selector:
        matchLabels:
          gateway: bookinfo
      kind: HTTPRoute


gatewayclass/isito-gc.yaml

kubectl apply -f isito-gc.yaml -n istio-system


apiVersion: networking.x-k8s.io/v1alpha1
kind: GatewayClass
metadata:
  name: istio
spec:
  controller: istio.io/gateway-controller



```
serviceName: productpage.istio.svc.cluster.local  but the envoy config is outbound|9080||productpage.istio-system.svc.cluster.local

![1629957259(1)](https://user-images.githubusercontent.com/31508490/130908511-628e8583-3203-4507-bc6b-b031714b0406.jpg)

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
istio 1.11.0
**How was Istio installed?**
istioctl install --set  profile=demo
**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
