### ISSUE TITLE
gateway-api gateway listeners tls options，what options does istio gateway-api support?

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#34883]
```
kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: bookinfo
spec:
  gatewayClassName: istio
  listeners:  
  - hostname: "*"
    port: 443
    protocol: HTTPS
    tls:
      options: 
        xx: yy
      mode: Terminate
      certificateRef:
        name: bookinfo-gateway-secret
        kind: Secret
        group: core
    routes:
      namespaces:
        from: All
      selector:
        matchLabels:
          gateway: bookinfo
      kind: HTTPRoute
```

gateway-api gateway listeners tls options，what options does istio gateway-api support?
