### ISSUE TITLE
Internal mesh traffic between HTTPS services fails

### ISSUE THREAD

**Issue by domenjesenovec** [istio/istio#34880]
**Bug description**
I am trying to configure Istio to work with HTTPS backend services. Following the suggestion from [#29107](https://github.com/istio/istio/issues/29107) I have disabled mTLS for the namespace which worked (with limited success). Applications are now accessible outside the mesh via Ingress (AWS ALB). But the traffic between the services is failing.

You might ask why do we want encrypted traffic inside the pod (since this traffic never leaves the node and goes on the network). The answer is we are deploying financial applications to public cloud and would like to have end to end encryption where plain text traffic is never ever exposed outside the container. This does mean we are not utilizing one of the three services Istio provides (traffic encryption) but we still want to use the other two (observability & traffic management for blue/green upgrades).

The below sample is simplified, but demonstrates the problem. We have two services (app-backend & app-web). They are both exposed externally. app-backend service exposes a landing info page with basic app information and REST & SOAP endpoint. The app-web exposes a web UI which is backed by a REST api provided by app-backend. The problem with below configuration - both services are accessible externally, but traffic between them fails.

Looks like the TLS between the two applications gets terminated at one of the proxies? If the communication is: app-web <> app-web-istio-proxy <> app-backend-istio-proxy <> app-backend it seems app-web-istio-proxy terminates TLS and sends plain text traffic to app-web?

**Curl analysis:**
```
pod: app-backend container: app-backend:
curl -i -k https://localhost:8443/app-backend/                          -- OK (HTTP 200)
curl -i -k https://app-backend.app.svc.cluster.local:8443/app-backend/  -- (35) SSL received a record that exceeded the maximum permissible length.
curl -i http://app-backend.app.svc.cluster.local:8443/app-backend/      -- OK (HTTP 200)

pod: app-backend container: istio-proxy
curl -i -k https://localhost:8443/app-backend/                          -- OK (HTTP 200)
curl -i -k https://app-backend.app.svc.cluster.local:8443/app-backend/  -- OK (HTTP 200)
curl -i http://app-backend.app.svc.cluster.local:8443/app-backend/      -- Warning: Binary output can mess up your terminal. Use "--output -" to tell, Warning: curl to output it to your terminal anyway, or consider "--output, Warning: <FILE>" to save to a file.

pod: app-web container: app-web:
curl -i -k https://app-backend.app.svc.cluster.local:8443/app-backend/  -- (35) SSL received a record that exceeded the maximum permissible length.
curl -i http://app-backend.app.svc.cluster.local:8443/app-backend/      -- OK (HTTP 200)

pod: app-web container: istio-proxy:
curl -i -k https://app-backend.app.svc.cluster.local:8443/app-backend/  -- OK (HTTP 200)
curl -i http://app-backend.app.svc.cluster.local:8443/app-backend/      -- Warning: Binary output can mess up your terminal. Use "--output -" to tell, Warning: curl to output it to your terminal anyway, or consider "--output, Warning: <FILE>" to save to a file.

pod instio-ingressgateway container: istio-proxy
curl -i -k https://app-backend.app.svc.cluster.local:8443/app-backend/  -- OK (HTTP 200)
curl -i http://app-backend.app.svc.cluster.local:8443/app-backend/      -- Warning: Binary output can mess up your terminal. Use "--output -" to tell, Warning: curl to output it to your terminal anyway, or consider "--output, Warning: <FILE>" to save to a file.
```

**Istio configuration:**
Ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  namespace: istio-system
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:...
    alb.ingress.kubernetes.io/healthcheck-path: /healthz/ready
    alb.ingress.kubernetes.io/healthcheck-port: "15021"
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[ { "HTTP": 80 }, { "HTTPS": 443 } ]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/security-groups: sg-00000000000000001
    alb.ingress.kubernetes.io/shield-advanced-protection: "true"
    kubernetes.io/ingress.class: alb
spec:
  rules:
  - host: some-domain.com
    http:
      paths:
      - backend:
          serviceName: istio-ingressgateway
          servicePort: 443
        path: /app-backend
      - backend:
          serviceName: istio-ingressgateway
          servicePort: 443
        path: /app-backend/*
      - backend:
          serviceName: istio-ingressgateway
          servicePort: 443
        path: /app-web
      - backend:
          serviceName: istio-ingressgateway
          servicePort: 443
        path: /app-web/*
```
Gateway:
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: app-gateway
  namespace: app
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - some-domain.com # external traffic
    - app/*           # internal traffic
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: app-gateway-tls-certs
      mode: SIMPLE
```
Virtual services:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app-backend-ext # route external traffic to backend service
  namespace: app
spec:
  gateways:
  - app-gateway
  hosts:
  - some-domain.com
  http:
  - match:
    - uri:
        prefix: /app-backend
    route:
    - destination:
        host: app-backend.app.svc.cluster.local
        port:
          number: 8443

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app-backend-int # route internal traffic to backend service
  namespace: app
spec:
  gateways:
  - mesh
  hosts:
  - app-backend.app.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: /app-backend
    route:
    - destination:
        host: app-backend.app.svc.cluster.local
        port:
          number: 8443

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app-web-ext # route external traffic to web UI service
  namespace: app
spec:
  gateways:
  - app-gateway
  hosts:
  - some-domain.com
  http:
  - match:
    - uri:
        prefix: /app-web
    route:
    - destination:
        host: app-web.app.svc.cluster.local
        port:
          number: 8443

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app-web-int # route internal traffic to web UI service
  namespace: app
spec:
  gateways:
  - mesh
  hosts:
  - app-web.app.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: /app-web
    route:
    - destination:
        host: app-web.app.svc.cluster.local
        port:
          number: 8443
```
Destination rules:
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-web
  namespace: app
spec:
  host: app-web.app.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: ISTIOID
          path: /app-web
          ttl: 0s
    tls:
      mode: SIMPLE # Let Envoy proxy know application uses HTTPS

apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-backend
  namespace: app
spec:
  host: app-backend.app.svc.cluster.local
  trafficPolicy:
    tls:
      mode: SIMPLE # Let Envoy proxy know application uses HTTPS
```
PeerAuthentication:
```
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  namespace: app
  name: app-pa
spec:
  mtls:
    mode: DISABLE
```

**Expected behavior**
End to end HTTPS encryption of traffic inside the mesh and traffic between the mesh services and client/browser,

**Steps to reproduce the bug**

**Version**
```
$ istioctl version --remote
client version: 1.7.4
control plane version: 1.10.2
data plane version: 1.10.2 (3 proxies)
$ kubectl version --short
Client Version: v1.18.0
Server Version: v1.16.15-eks-e1a842
$ helm version --short
v3.4.0+g7090a89
```

**How was Istio installed?**
Installed using Istio operator Helm chart.

**Environment where the bug was observed (cloud vendor, OS, etc)**
Deployed on AWS EKS. Applications are exposed via Ingress that sets up AWS ALB.
