### ISSUE TITLE
502 not being retried as expected, presented with a URX

### ISSUE THREAD

**Issue by Stono** [istio/istio#34891]
**Bug description**
Hi, 
We've been talking with @howardjohn recently about some issues around DNS on external clusters (https://github.com/istio/api/pull/2084/files#r694568504), our current mitigation to what we're seeing is to add a `gateway-error` to our retry policy.

Whilst on the whole it seems to have helped, we're still seeing some example of failure where it appears the request isn't being retried, and we're getting a 502 `URX`, which according to https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage is "URX: The request was rejected because the upstream retry limit (HTTP) or maximum connect attempts (TCP) was reached.".

NOTE: Unlike the linked issue, in this issue, the IP is _not_ changing when this happens (but that's not to say we don't get a dns failure perhaps?).  

Frustratingly I can't turn on debug logs to try and capture this because it's a high volume service, contains loads of sensitive information in the requests, and is very infrequent in nature.

Our `VirtualService` looks like this:

```
spec:
  hosts:
  - remote-host.whatever.com
  http:
  - name: default
    retries:
      attempts: 3
      perTryTimeout: 595s
      retryOn: connect-failure,refused-stream,unavailable,cancelled,resource-exhausted,gateway-error
    route:
    - destination:
        host: remote-host.whatever.com
        subset: https
      weight: 100
    timeout: 595s
```

And our `DestinationRule`:
```
spec:
  exportTo:
  - engage-proxy
  host: engage-api.autotrader.co.uk
  subsets:
  - name: https
    trafficPolicy:
      connectionPool:
        http:
          idleTimeout: 30m
        tcp:
          connectTimeout: 2s
          tcpKeepalive:
            interval: 30s
            time: 30s
```

So I can't really see any reason why we're getting `URX`.

The other thing I find interesting as you can see from the trace is that the call was `2.92s`, not like, milliseconds (tcp failures being retried).

![image](https://user-images.githubusercontent.com/1486729/130946432-a1da8fb2-296b-4594-bbb6-e4c07c4e2d35.png)

**Expected behavior**

**Steps to reproduce the bug**
It's intermittent and very infrequent, and can't see any correlation on the type of requests that are failing.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.10.2

**How was Istio installed?**
Helm

**Environment where the bug was observed (cloud vendor, OS, etc)**
GKE

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
