### ISSUE TITLE
the rate limit service update ConfigMap does not take effect

### ISSUE THREAD

**Issue by xichengliudui** [istio/istio#34890]
**Bug description**

ref: https://istio.io/latest/docs/tasks/policy-enforcement/rate-limit/#global-rate-limit
the ConfigMap is created to implement rate limit. after the ConfigMap is updated, the new configuration does not take effect
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
data:
  config.yaml: |
    domain: productpage-ratelimit
    descriptors:
      - key: PATH
        value: "/productpage"
        rate_limit:
          unit: minute
          requests_per_unit: 3
```
```
/ $ curl http://ratelimit.default:6070/rlconfig
productpage-ratelimit.PATH_/productpage: unit=MINUTE requests_per_unit=3
```
now update the productpage configuration to allow one request per minute
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
data:
  config.yaml: |
    domain: productpage-ratelimit
    descriptors:
      - key: PATH
        value: "/productpage"
        rate_limit:
          unit: minute
          requests_per_unit: 1
```
get rate limit configuration is still the configuration before the update
```
/ $ curl http://ratelimit.default:6070/rlconfig
productpage-ratelimit.PATH_/productpage: unit=MINUTE requests_per_unit=3
```
it still takes three requests to return `429` http code，the new configuration takes effect only after the rate limit pod is restarted
```shell
$ kubectl delete pod ratelimit-656895b475-cwnk5
```
```shell
/ $ curl http://ratelimit.default:6070/rlconfig
productpage-ratelimit.PATH_/productpage: unit=MINUTE requests_per_unit=1
```

**Comment by xichengliudui** [comment]
@devincd 
can you configure more than one ConfigMap for ratelimit?
if i have two ConfigMaps, how should ratelimit be configure?
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
data:
  config.yaml: |
    domain: productpage-ratelimit
    descriptors:
      - key: PATH
        value: "/productpage"
        rate_limit:
          unit: minute
          requests_per_unit: 1
      - key: PATH
        rate_limit:
          unit: minute
          requests_per_unit: 100
```
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
data:
  config.yaml: |
    domain: httpbin-ratelimit
    descriptors:
      - key: PATH
        rate_limit:
          unit: minute
          requests_per_unit: 5
```
