### ISSUE TITLE
how to set envoyAccessLogService additional_request_headers_to_log?

### ISSUE THREAD

**Issue by zirain** [istio/istio#34911]
hello, I want to used envoy access log service with additional_request_headers_to_log, is there any to set in istio?

![image](https://user-images.githubusercontent.com/4354057/131202963-bb9fd1aa-23ec-41e3-b3ed-283c45abbd9c.png)

https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/access_loggers/grpc/v3/als.proto.html?highlight=additional_request_headers_to_log

can I use EnvoyFilter to patch access_log configuration ?

![image](https://user-images.githubusercontent.com/4354057/131202987-428e44f3-7552-44df-bee6-b6615c85b49b.png)

**Comment by hzxuzhonghu** [comment]
@bianpengyuan

**Comment by bianpengyuan** [comment]
> can I use EnvoyFilter to patch access_log configuration ?

Yeah it should be possible. See https://github.com/istio/istio/wiki/EnvoyFilter-Samples#disable-access-logging-at-sidecars-and-only-enable-it-at-gateways for some example how to patch xds resources.

**Comment by zirain** [comment]
> > can I use EnvoyFilter to patch access_log configuration ?
> 
> Yeah it should be possible. See https://github.com/istio/istio/wiki/EnvoyFilter-Samples#disable-access-logging-at-sidecars-and-only-enable-it-at-gateways for some example how to patch xds resources.

I have try EnvoyFilter, it's work, but not prefect due to EnvoyFilter merge operation can not replace item in access_log array

**Comment by zirain** [comment]
@bianpengyuan 

I have try to use envoy filter like:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: envoy-als-http
  namespace: istio-system
spec:
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: ANY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
            access_log:
            - name: envoy.access_loggers.http_grpc
              typed_config:
                "@type": "type.googleapis.com/envoy.extensions.access_loggers.grpc.v3.HttpGrpcAccessLogConfig"
                common_config: 
                  log_name: "http_envoy_accesslog"
                  grpc_service: 
                    envoy_grpc: 
                      cluster_name: envoy_accesslog_service
                  filter_state_objects_to_log:
                  - wasm.upstream_peer
                  - wasm.upstream_peer_id
                  - wasm.downstream_peer
                  - wasm.downstream_peer_id
                additional_request_headers_to_log:
                - x-request-user
```
the listener config looks like:
```json
"accessLog": [
                                {
                                    "name": "envoy.access_loggers.file",
                                    "typedConfig": {
                                        "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog",
                                        "path": "/dev/stdout",
                                        "logFormat": {
                                            "textFormat": "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% \"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%\n"
                                        }
                                    }
                                },
                                {
                                    "name": "envoy.access_loggers.http_grpc",
                                    "typedConfig": {
                                        "@type": "type.googleapis.com/envoy.extensions.access_loggers.grpc.v3.HttpGrpcAccessLogConfig",
                                        "commonConfig": {
                                            "logName": "http_envoy_accesslog",
                                            "grpcService": {
                                                "envoyGrpc": {
                                                    "clusterName": "envoy_accesslog_service"
                                                }
                                            },
                                            "filterStateObjectsToLog": [
                                                "wasm.upstream_peer",
                                                "wasm.upstream_peer_id",
                                                "wasm.downstream_peer",
                                                "wasm.downstream_peer_id"
                                            ]
                                        }
                                    }
                                },
                                {
                                    "name": "envoy.access_loggers.http_grpc",
                                    "typedConfig": {
                                        "@type": "type.googleapis.com/envoy.extensions.access_loggers.grpc.v3.HttpGrpcAccessLogConfig",
                                        "commonConfig": {
                                            "logName": "http_envoy_accesslog",
                                            "grpcService": {
                                                "envoyGrpc": {
                                                    "clusterName": "envoy_accesslog_service"
                                                }
                                            }
                                        },
                                        "additionalRequestHeadersToLog": [
                                            "x-request-user"
                                        ]
                                    }
                                }
                            ],
```
this will make envoy_accesslog_service receiver two line per request, use envoy filter is work, but far from perfect.

Can we add an global `additionalRequestHeadersToLog` config on [Global Mesh Options](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#RemoteService)

![image](https://user-images.githubusercontent.com/4354057/132786392-7dae2ad3-ca9b-40d0-bfc8-348e0cd5601f.png)
