### ISSUE TITLE
Empty operator spec after apply valid configuration

### ISSUE THREAD

**Issue by alekskar** [istio/istio#34938]
### Bug Description

Hi, we faced with the following behavior during Istio operator configuration, any valid config becomes empty.
istio deployed with operator. For example
```
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-controlplane
  namespace: istio-system
spec:
  components:
    egressGateways:
      - enabled: true
        k8s:
          hpaSpec:
            maxReplicas: 6
            metrics:
              - resource:
                  name: cpu
                  targetAverageUtilization: 70
                type: Resource
            minReplicas: 1
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: istio-egressgateway
          resources:
            limits:
              cpu: 2000m
              memory: 3Gi
            requests:
              cpu: 200m
              memory: 512Mi
        name: istio-egressgateway
    ingressGateways:
      - enabled: true
        k8s:
          hpaSpec:
            maxReplicas: 3
            metrics:
              - resource:
                  name: cpu
                  targetAverageUtilization: 70
                type: Resource
            minReplicas: 1
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: istio-ingressgateway-internal
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
        label:
          app: istio-ingressgateway-internal
          istio: ingressgateway-internal
        name: istio-ingressgateway-internal
      - enabled: true
        k8s:
          hpaSpec:
            maxReplicas: 5
            metrics:
              - resource:
                  name: cpu
                  targetAverageUtilization: 70
                type: Resource
            minReplicas: 1
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: istio-ingressgateway
          resources:
            limits:
              cpu: '2'
              memory: 3Gi
            requests:
              cpu: '1'
              memory: 1Gi
        name: istio-ingressgateway
    pilot:
      k8s:
        hpaSpec:
          maxReplicas: 3
          metrics:
            - resource:
                name: cpu
                targetAverageUtilization: 90
              type: Resource
          minReplicas: 2
        nodeSelector:
          purpose: system
        resources:
          requests:
            cpu: 500m
            memory: 3Gi
        tolerations:
          - effect: NoSchedule
            key: purpose
            operator: Equal
            value: system
  meshConfig:
    outboundTrafficPolicy:
      mode: ALLOW_ANY
  profile: default
  values:
    global:
      defaultNodeSelector:
        purpose: system
      defaultTolerations:
        - effect: NoSchedule
          key: purpose
          operator: Equal
          value: system
```

after apply becomes:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-controlplane
  namespace: istio-system
status: {}
spec: {}
```
other resources and specifying profiles leads to the same result - status and spec are empty.
logs of istiod and istio-operator doesn't have anything specific

### Version

```prose
client version: 1.9.8
control plane version: 1.9.8
data plane version: 1.9.8 (125 proxies)

kubectl version --short
Client Version: v1.21.2
Server Version: v1.20.7-eks-d88609
```
