### ISSUE TITLE
Starting from 1.10 TCP traffic over Node Port doesn't works anymore

### ISSUE THREAD

**Issue by illidan80** [istio/istio#34930]
### Bug Description

This is how were doing remote debugging of our Java microservices:

Adding a Node Port Kubernetes service which pointing to debugging port (5005 in this case):

```
kind: Service
apiVersion: v1
metadata:
  name: my-service-debugging-service
  namespace: my
spec:
  selector:
    app: my-service
  ports:
    - protocol: TCP
      name: tcp
      port: 80
      targetPort: 5005
      nodePort: 32004
  type: NodePort
```

So, from IntelliJ I was able to attach using the following command line arguments:
`-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:32004
`

This approach was working for us for years, since first Istio versions. Last version where it does works is 1.9.8

After that (tested both in 1.10.4 and 1.11.1) connection fails to connect.

Is there any breaking change in this area? Any suggestions for workaround?

### Version

```prose
Istio: works until 1.9.8, fails on all newer versions (1.10.4, 1.11.1)
Kubernetes: 1.21 (Microk8s)
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
