### ISSUE TITLE
SNI routing through Istio gateway with TLS termination

### ISSUE THREAD

**Issue by EronWright** [istio/istio#34972]
**Describe the feature request**
This is a feature request to support SNI routing for non-HTTPS traffic on the gateway in combination with TLS termination (SIMPLE mode).  The gateway today supports SNI routing in PASSTHROUGH mode only.

The scenario is to route TCP gateway traffic to a specific pod in a StatefulSet via a headless service.  Each pod has a corresponding external FQDN that resolves to the gateway IP.  The gateway terminates TLS using a wildcard certificate.  A virtual service and service entry would be defined for each pod, to effectively map from the external FQDN to the pod's hostname.

An example configuration is provided below.  As of 1.10.3, the current behavior is that the 6651 listener is skipped, with the following error message in Pilot log:
```
gateway omitting listener "0.0.0.0_6651" due to: must have more than 0 chains in listener "0.0.0.0_6651"
```

**Describe alternatives you've considered**
One alternative is to use an `EnvoyFilter` to add custom listeners to the gateway.

**Affected product area (please put an X in all that apply)**

[X] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

Code reference: [pilot/pkg/networking/core/v1alpha3/gateway.go#L563-L600](https://github.com/istio/istio/blob/1.10.3/pilot/pkg/networking/core/v1alpha3/gateway.go#L563-L600)

Desired configuration:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: pulsar-gateway
spec:
  selector:
    istio: ingressgateway 
  servers:
    - port:
        number: 6651
        name: tcp-pulsar
        protocol: tls
      hosts:
        - "broker-0.example.dev"
        - "broker-1.example.dev"
      tls:
        mode: SIMPLE
        credentialName: tls-broker
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: pulsar-broker-0-gateway
spec:
  hosts:
    - "broker-0.example.dev"
  gateways:
    - pulsar-gateway
  tls:
    - match:
        - port: 6651
          sniHosts:
            - "broker-0.example.dev"
      route:
        - destination:
            host: "broker-0.pulsar-broker-headless.default.svc.cluster.local"
            port:
              number: 6650
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: pulsar-broker-0
  labels:
    app: pulsar-broker
spec:
  hosts:
    - "broker-0.pulsar-broker-headless.default.svc.cluster.local"
  ports:
    - number: 6650
      name: tcp-pulsar
      protocol: tcp
      targetPort: 6650
  location: MESH_INTERNAL
  resolution: DNS
---
# omitted for brevity: VirtualService and ServiceEntry for broker-1
```
