### ISSUE TITLE
Intermittently lost HTTP/GRPC responses

### ISSUE THREAD

**Issue by leosunmo** [istio/istio#34973]
### Bug Description

This might be linked to a (somewhat) similar issue we're having, https://github.com/envoyproxy/envoy/issues/17722.

We are very occasionally seeing responses being dropped or lost(?) in our clusters. In the below screenshot you can see an HTTP request going from the Ingressgateway to one of our services.
For _complete_ clarity, the headers you can see are the following from https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#command-operators:
`start_time`: `%START_TIME%`
`path`: `%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%`
`duration`: `%DURATION%`
`request_attempts`: `%REQ(X-ENVOY-ATTEMPT-COUNT)%`
`reponse_flag`: `%RESPONSE_FLAGS%`
`reponse_code`: `%RESPONSE_CODE%`

`timestamp` is when the log was emitted, so more or less the end of the request.

![image (1)](https://user-images.githubusercontent.com/13341934/131592711-08e2aeb7-319a-4d13-a292-e3cf1fcd14f9.png)

This is filtered on a particular `request_id`, and as you can see, the Ingressgateway thinks that the first request times out after 9 seconds (which is the configured `per_try_timeout`) and it retires to a different Pod (see `pod_id`). This request is _also_ treated as if it timed out after 9 seconds. It then returns `UT, URX` and 504.

The service is a NodeJS express server. Normal HTTP, and looking at the bytes sent and `response_code` from the Istio-sidecar logs it's sending replies just fine.

We have seen similar things happen with GRPC-Web requests and assumed it was something related to the Envoy plugins or similar. But we are also seeing it happen for good old HTTP now. I am quite stumped as to what to do next.

Please let me know if you want any other information here as I don't really know what to provide and I can't attach the full `istioctl bug-report` as that contains _a lot_ of internal information.

### Version

```prose
Istio:
client version: 1.11.0
control plane version: 1.11.0
data plane version: 1.11.0 (68 proxies)

We are running on **AKS** in Azure.

Kubernetes:
Client Version: v1.20.0
Server Version: v1.19.11
```

### Additional Information

Relevant config snippet from `istioctl pc all -nistio-system istio-ingressgateway -oyaml` this particular service and route:
```
        - decorator:
            operation: serviceA.default.svc.cluster.local:8880/accounts/.*/projects
          match:
            case_sensitive: true
            safe_regex:
              google_re2: {}
              regex: /accounts/.*/projects
          metadata:
            filter_metadata:
              istio:
                config: /apis/networking.istio.io/v1alpha3/namespaces/default/virtual-service/serviceA
          route:
            cluster: outbound|8880||serviceA.default.svc.cluster.local
            cors:
              allow_headers: authorization,content-type,r-p,r-cs,x-user-agent,x-grpc-web
              allow_methods: GET,POST,PUT,DELETE,HEAD,OPTIONS
              allow_origin_string_match:
              - exact: '*'
              expose_headers: grpc-message,grpc-status
              filter_enabled:
                default_value:
                  numerator: 100
              max_age: "7200"
            max_grpc_timeout: 20s
            retry_policy:
              host_selection_retry_max_attempts: "5"
              num_retries: 1
              per_try_timeout: 9s
              retry_host_predicate:
              - name: envoy.retry_host_predicates.previous_hosts
              retry_on: 5xx
            timeout: 20s
```

I'm not sure what config I can provide from the Service's side in regards to it connecting to the Ingressgateway.
