### ISSUE TITLE
Failed to mount certs for new SA

### ISSUE THREAD

**Issue by 1hanymhajna** [istio/istio#34987]
### Bug Description

Recently we upgraded istio from 1.5.10 to 1.6.14,
And we notice that the istio.<service_account> does not have been created as in the old version (expected behavior)
So we tried to mount the secrets using :
`proxy.istio.io/config: |
          proxyMetadata:
            OUTPUT_CERTS: /etc/istio-output-certs
        sidecar.istio.io/userVolumeMount: '[{"name": "istio-certs", "mountPath": "/etc/istio-output-certs"}]'
 `
 And then added the volume, and mounted it to the relevant container, And it just worked perfectly with old service account (that still have istio.<service account> secret)
 
 when tried to create a new service account and tried to use it, the directory was empty
 We are trying to mount the certs into init container, cause in this stage the istio-proxy not ready yet, and we need to call another service into the mesh, so we must mount the certs. to be able to pass the mtls

my full deployment yaml:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
  selfLink: /apis/apps/v1/namespaces/apps/deployments/test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: test-certificate
  template:
    metadata:
      annotations:
        proxy.istio.io/config: |
          proxyMetadata:
            OUTPUT_CERTS: /etc/istio-output-certs
        sidecar.istio.io/userVolumeMount: '[{"name": "istio-certs", "mountPath": "/etc/istio-output-certs"}]'
      labels:
        app: test-certificate
    spec:
      serviceAccount: test123
      serviceAccountName: test123
      containers:
        - image: kennethreitz/httpbin
          imagePullPolicy: Always
          name: certificate
          ports:
            - containerPort: 8080
              name: client
              protocol: TCP
      imagePullSecrets:
        - name: regcred
      initContainers:
        - command:
            - /bin/sh
            - -c
            - |
              echo "starting"
              ls -la /etc/istio-output-certs
          image: kennethreitz/httpbin
          imagePullPolicy: Always
          name: init
          volumeMounts:
          - name: istio-certs
            mountPath: /etc/istio-output-certs
      volumes:
      - emptyDir:
          medium: Memory
        name: istio-certs
      restartPolicy: Always
``` 

BTW: tried the same in the main container and not just in the init container, and got the same behaviour 

### Version

```prose
client version: 1.6.14
internal-ingressgateway version:
pilot version: 1.6.14
pilot version: 1.6.14
data plane version: 1.6.14 (7 proxies)
```
