### ISSUE TITLE
Supporting OPA policy in CRD format

### ISSUE THREAD

**Issue by liminw** [istio/istio#3498]
Istio has integrated Open Policy Agent (http://www.openpolicyagent.org/) as a Mixer adapter. Currently the way to provide OPA policy is in the adapter parameter (see [example](https://github.com/istio/istio/tree/master/mixer/adapter/opa#example-configuration), note that "policy" under "spec" in "opaHandler" is the OPA policy). This is not ideal. The better way is to allow users to provide OPA policy as K8S CRDs. Earlier discussion on this topic can be found in [this doc](https://docs.google.com/document/d/1U2XFmah7tYdmC5lWkk3D43VMAAQ0xkBatKmohf90ICA/).

**Comment by liminw** [comment]
cc @tsandall @timothyhinrichs @mangchiandjjoe

**Comment by tsandall** [comment]
Thanks @liminw. I'd be happy to spec out the CRD for this. Something like...

```
kind: Policy
apiVersion: openpolicyagent.org/v1beta1
policy: <string>  # raw OPA policy
status:
  state: <"enforced" | "error">
  errors:  # if error, then one or more...
    - message: <string>
      location:
        row: <line number>
        column: <column number>
      details: <JSON value>
```

I'd expect the spec (and generated code) for this to live outside Istio proper and then Istio/Mixer would depend on that package. What do you think?
