### ISSUE TITLE
Implement Endpointslice FQDN addresses

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#34995]
### Bug Description

```yaml
addressType: FQDN
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - httpbin.org
  conditions:
    ready: true
    serving: true
    terminating: false
kind: EndpointSlice
metadata:
  labels:
    kubernetes.io/service-name: httpbin
  name: httpbin-manualy
  namespace: default
ports:
- name: http
  port: 80
  protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
```

With `set env deployment/istiod PILOT_USE_ENDPOINT_SLICE=true`

Leads to 
```
2021-09-01T15:30:58.882375Z     warn    ads     ADS:EDS: ACK ERROR istio-ingressgateway-6b48bbf7d6-q4m28.istio-system-1 Internal:malformed IP address: httpbin.org. Consider setting resolver_name or setting cluster type to 'STRICT_DNS' or 'LOGICAL_DNS'
```

This actually works without PILOT_USE_ENDPOINT_SLICE because coredns generates a CNAME but Istiod doesn't see the endpoint at all. So it works just like any other headless. This would NOT work for TCP, since it would expect to know the IPs.

### Version

```prose
master
```
