### ISSUE TITLE
Target specific cluster services in a multi-cluster enviroment

### ISSUE THREAD

**Issue by daniel-pebble** [istio/istio#34992]
I have set up a multi-primary/multi-network system with load-balancing and smart DNS proxying enabled.  
I need to be able to target specific clusters services, and I wonder if there is a way to do that?  

When making requests to a service, Istio load balances the requests, which is fine, but I would also like to explicitly target services in a specific cluster.  
It seems that using an FQDN doesn’t help as both clusters use the same default DNS domain (.cluster.local), there is a kubeadm option to change the service-dns-domain, but as I understand it, this will break the multi-cluster load balancing, is that correct?

Is there any options available to query based on the multiCluster names?  service-name.cluster1 for example?

**Comment by howardjohn** [comment]
In destination rule you can create a subset and match the cluster label (I think it's istio.io/cluster) I believe. Then create subsets per cluster. There is no out of the box way though

**Comment by howardjohn** [comment]
cc @nmittler as we were just discussing this

**Comment by nmittler** [comment]
@daniel-pebble we've seen this request in the past and I'm wondering if you could expand a bit on your use case.

In the meantime, a work-around might be to simply create extra services in each cluster, say with the name `<svc>-<cluster>.<namespace>`.

**Comment by daniel-pebble** [comment]
@nmittler and @howardjohn – thanks for your feedback.  I had considered deploying extra cluster-specific services as a workaround, so I think we can use that solution for now. 

I’ve created this diagram to help illustrate what we are trying to achieve.  We’ll have three clusters all configured under a single mesh in a multi-primary/multi-network setup.  

To simplify things I’ve just shown some of our PODs, we use a VirtualService to pass external traffic to our UI POD and another for internal traffic between backend services.  

We want to enable locality so that requests are served by local services with the ability to failover should a local POD be unavailable.  However, other PODs such as the “Database” shouldn’t be load-balanced even if a local POD isn’t available.  Our plan for this was to deploy cluster-specific services so that each POD can only consume its local “Database”.  

The next requirement links back to my original question, in that we also need the ability to target specific services in specific clusters.  We can, of course, deploy site-specific services, but I was hoping to avoid the new to deploy extra services for each of our services.  If that’s the only option today, then so be it; in a perfect world, if we would be able to query based on something like <service>.<cluster>.<mesh> it would remove the need for deploying these extra services.

![DR Playground](https://user-images.githubusercontent.com/47243318/131910798-92f35bfe-223e-448e-af58-2af823649de7.jpg)

**Comment by nmittler** [comment]
> We want to enable locality so that requests are served by local services with the ability to failover should a local POD be unavailable. However, other PODs such as the “Database” shouldn’t be load-balanced even if a local POD isn’t available. Our plan for this was to deploy cluster-specific services so that each POD can only consume its local “Database”.

If you just need the database to be cluster-local, then you can make it so in [mesh config](https://github.com/istio/api/blob/master/mesh/v1alpha1/config.proto#L372).

> The next requirement links back to my original question, in that we also need the ability to target specific services in specific clusters. We can, of course, deploy site-specific services, but I was hoping to avoid the new to deploy extra services for each of our services. If that’s the only option today, then so be it; in a perfect world, if we would be able to query based on something like .. it would remove the need for deploying these extra services.

You could define a subset for each cluster (using a match on the [cluster label](https://github.com/istio/api/blob/master/label/labels.yaml#L124)) and then use a custom header to route to a particular subset. That means you'll need a `DestinationRule` for your service that identifies all of the subsets.

**Comment by daniel-pebble** [comment]
Is there something special you must do to have the cluster label added to workloads?  I can see the "topology.istio.io/network" label is added but the cluster one isn't.  I did notice that the cluster label is in alpha, must this be enabled somehow?

**Comment by daniel-pebble** [comment]
I found the answer https://github.com/istio/api/pull/2076

**Comment by daniel-pebble** [comment]
@nmittler I have tried to set up the following but requests to cluster-specific subsets don't work, I get "no healthy upstream" when trying to access "http://router/site/1/api/1/deployment/"

```
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: internal
  namespace: default
spec:
  hosts:
    - router.default.svc.cluster.local
  http:
    - match:
        - uri:
            exact: /site/1/api/1/deployment
        - uri:
            prefix: /site/1/api/1/deployment/
      rewrite:
        uri: /api/1/deployment/
      route:
        - destination:
            host: deploymentservice.default.svc.cluster.local
            subset: cluster1
    - match:
        - uri:
            exact: /site/3/api/1/deployment
        - uri:
            prefix: /site/3/api/1/deployment/
      rewrite:
        uri: /api/1/deployment/
      route:
        - destination:
            host: deploymentservice.default.svc.cluster.local
            subset: cluster3
    - match:
        - uri:
            exact: /api/1/deployment
        - uri:
            prefix: /api/1/deployment/
      route:
        - destination:
            host: deploymentservice.default.svc.cluster.local
```

```
kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: deploymentservice-destination
  namespace: default
spec:
  host: deploymentservice.default.svc.cluster.local
  subsets:
    - labels:
        cluster: cluster1
      name: cluster1
    - labels:
        cluster: cluster3
      name: cluster3
```

In Kiali it reports KIA0203 error against the subsets, I'm not sure if this is just a limitation of kiali in a multi-cluster setup, however, I do see the clusters in the mesh overview page. 
https://kiali.io/documentation/latest/validations/#_kia0203_this_subset_s_labels_are_not_found_in_any_matching_host
