### ISSUE TITLE
Mapping istioOperatorSpec fields to istio helm

### ISSUE THREAD

**Issue by shahriak** [istio/istio#35004]
**Describe the feature request**
We are working on adopting the new istio helm deployment. We are currently using a customized design where istioOperator deploys the istio charts on a cluster using helm as the helm deployment feature was not available prior to istio v1.8. As part of adopting the new helm changes, I am looking into mapping the existing istioOperator spec to the newer helm. I was able to find a mapping for all the other fields except for the following, also highlighted in bold. 

Are these mappings currently available? If not, is there a plan to make these fields available in the next releases? 

	• .Values.istio-ingress.gateways.istio-ingressgateway.hpaSpec.minReplicas
	• .Values.istio-ingress.gateways.istio-ingressgateway.hpaSpec.maxReplicas
	• .Values.istio-ingress.gateways.istio-ingressgateway.overlays
        •  .Values.istio-ingress.gateways.istio-pilot.overlays
	• .Values.istio-ingress.gateways.istio-ingressgateway.hpaSpec.scaleTargetRef

```
istioOperatorSpec:
  apiVersion: install.istio.io/v1alpha1
  kind: IstioOperator
  metadata:
    namespace: istio-system
    name: test-istiocontrolplane
  spec:
    profile: "default"
    hub: acr/istio
    tag: 1.9.4
    installPackagePath: /istio/manifests

    meshConfig:
      defaultConfig:
        terminationDrainDuration: 30s
        holdApplicationUntilProxyStarts: true
      trustDomain: aks-cm

    components:
      ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          env:
          - name: ISTIO_META_ROUTER_MODE
            value: "sni-dnat"
          - name: ISTIO_META_IDLE_TIMEOUT
            value: 30s
          service:
            ports:
            -
              name: https
              port: 443
              targetPort: 8443
          **hpaSpec:
            minReplicas: 2
            maxReplicas: 5**
            # values in the parent helm chart.
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: istio-ingressgateway
            metrics:
              - type: Resource
                resource:
                  name: cpu
                  targetAverageUtilization: 60
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 2000m
              memory: 1024Mi
          strategy:
            rollingUpdate:
              maxSurge: "100%"
              maxUnavailable: "25%"
          nodeSelector:
              kubernetes.io/os: linux
          _**overlays:
            - kind: Deployment
              name: istio-ingressgateway
              patches:
                - path: spec.template.spec.dnsConfig
                  value:
                    options:
                      - name: single-request-reopen**_
      pilot:
        enabled: true
        k8s:
          hpaSpec:
            minReplicas: 2
          **overlays:
            - kind: Deployment
              name: istiod
              patches:
                - path: spec.template.spec.dnsConfig
                  value:
                    options:
                      - name: single-request-reopen**
                   
```
istio helm doc: https://istio.io/latest/docs/setup/install/helm/

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[x ] Docs
[x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
Env: AKS
