### ISSUE TITLE
Istio ingress with EKS ACM not working - response:"503 Service Unavailable"

### ISSUE THREAD

**Issue by amalendur** [istio/istio#35015]
### Bug Description

**### _routing is not working._**
**In our environment we are integrating istio on EKS cluster.
Istio deploying through helm[istio-base, Istio-discovery, Istio-egress, istio-ingress]).
Authenticate k8s-dashboard using dex+oauth2-proxy.
Additionally created Rout53 record for "dex.domain.com/oauth2-proxy.domain.com/dashboard.domain.com" by using the loadbalancer created by istio.
Namespaces are enabled with Istio-injection.
Not sure what is wrong here.
Seeking for help to fix this.**

*"domain.com" is valid hosted zone in AWS.

Following are the config files;

#istio-base-values.yaml
```
global:
  istioNamespace: istio-system
  istiod:
    enableAnalysis: false
base:
  enableCRDTemplates: false
  validationURL: ""
  enableIstioConfigCRDs: true

```
#istio-discovery-values.yaml
```
pilot:
  resources:
    requests:
      cpu: 500m
      memory: 2048Mi
  nodeSelector:
    nodetype: utility
global:
  jwtPolicy: "first-party-jwt"
```

#istio-egress-values.yaml
```
gateways:
    istio-egressgateway:
      rollingMaxSurge: 100%
      rollingMaxUnavailable: 25%
      autoscaleEnabled: true
      autoscaleMin: 1
      autoscaleMax: 5
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 2000m
          memory: 1024Mi
      cpu:
        targetAverageUtilization: 80
      type: ClusterIP
global:
  defaultNodeSelector:
    nodetype: utility
  jwtPolicy: "third-party-jwt"
```

#istio-ingressgateway-values.yaml
```
gateways:
  istio-ingressgateway:
    type: LoadBalancer
    serviceAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <acm_certificate_arn>
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: 443
    externalTrafficPolicy: Cluster
    rollingMaxSurge: 100%
    rollingMaxUnavailable: 25%
    autoscaleEnabled: true
    autoscaleMin: 1
    autoscaleMax: 5
    cpu:
      targetAverageUtilization: 80
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 1024Mi
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
global:
  defaultNodeSelector:
    nodetype: utility
  jwtPolicy: "third-party-jwt"
```

#dex-config.yaml
```
config:
  issuer: https://dex.domain.com
  connectors:
  - type: mockCallback
    id: mock
    name: <cluster_name>
  - type: <connector_type>
    id: <connector_id>
    name: <connector_name>
    config:
      issuer: <issuer>
      clientID: <client_id>
      clientSecret: <client_secret>
      redirectURI: https://dex.domain.com/callback
      scopes: ["openid","profile","email","groups","address","phone","full"]
  enablePasswordDB: true
  staticClients:
  - id: '<cluster_name>-oidc-auth-client'
    redirectURIs:
    - 'https://auth.domain.com/oauth2/callback'
    - 'https://auth.domain.com/callback/<cluster_name>'
    name: '<cluster_name>-oidc-auth-client'
    secret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  staticPasswords:
  - email: "admin@domain.com"
    hash: "<hash>"
    username: "admin"
    userID: "xxxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  telemetry:
    http: 0.0.0.0:5558
  frontend:
    theme: coreos
```

#oauth2-proxy-config.yaml
```
config:
  clientID: '<cluster_name>-oidc-auth-client'
  clientSecret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  cookieSecret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
extraArgs:
  provider: oidc
  provider-display-name: dex
  proxy-websockets: true
  redirect-url: https://auth.domain.com/oauth2/callback
  oidc-issuer-url: https://dex.domain.com
  cookie-secure: true
  cookie-name: _oauth2_proxy
  cookie-refresh: 1h
  cookie-httponly: true
  email-domain: "*"
  pass-host-header: true
  ping-path: /ping
  set-authorization-header: true
  skip-provider-button: true
  http-address: 0.0.0.0:4180
  upstream: static://200
  scope: openid profile email offline_access groups
  client-secret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  client-id: '<cluster_name>-oidc-auth-client'
  whitelist-domain: .domain.com
  cookie-domain: .domain.com
```

#dex-gateway.yaml
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: dex
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - dex.domain.com
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - dex.domain.com
      port:
        name: https
        number: 443
        protocol: HTTP
```
        
#dex-virtualservice.yaml
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dex
  namespace: auth
spec:
  gateways:
    - istio-system/dex
  hosts:
  # The full host name of the app.
    - dex.domain.com
  http:
    - route:
        - destination:
            host: dex
            port:
              number: 80
      match:
        - uri:
            prefix: /
      headers:
        request:
          set:
            x-forwarded-proto: https
            x-forwarded-port: "443"
```

#oauth2-proxy-gateway.yaml
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: oauth2-proxy
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - auth.domain.com
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - auth.domain.com
      port:
        name: https
        number: 443
        protocol: HTTP
```

#oauth2-proxy-virtualservice.yaml
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: oauth2-proxy
  namespace: auth
spec:
  gateways:
    - istio-system/oauth2-proxy
  hosts:
  # The full host name of the app.
    - auth.domain.com
  http:
    - route:
        - destination:
            host: oauth2-proxy
            port:
              number: 80
      match:
        - uri:
            prefix: /
      headers:
        request:
          set:
            x-forwarded-proto: https
            x-forwarded-port: "443"
```

#k8s-dashboard-gateway.yaml
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kubernetes-dashboard
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - dashboard.domain.com
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - dashboard.domain.com
      port:
        name: https
        number: 443
        protocol: HTTP
```

#k8s-dashboard-virtualservice.yaml
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
spec:
  gateways:
    - istio-system/kubernetes-dashboard
  hosts:
  # The full host name of the app.
    - dashboard.domain.com
  http:
    - route:
        - destination:
            host: kubernetes-dashboard
            port:
              number: 80
      match:
        - uri:
            prefix: /
      headers:
        request:
          set:
            x-forwarded-proto: https
            x-forwarded-port: "443"
```

#dex-service.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: dex
  labels:
    app: dex
    service: dex
spec:
  type: ClusterIP
  ports:
  - port: 5556
     name: http
  selector:
    app: dex
```

#oauth2-proxy-service.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
  labels:
    app: oauth2-proxy
    service: oauth2-proxy
spec:
  type: ClusterIP
  ports:
  - port: 4180
     name: http
  selector:
    app: oauth2-proxy
```
#k8s-dashboard-service.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-dashboard
  labels:
    app: kubernetes-dashboard
    service: kubernetes-dashboard
spec:
  type: ClusterIP
  ports:
  - port: 80
     name: http
  selector:
    app: kubernetes-dashboard
```

#envoyfilter.yaml
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  labels:
    app.kubernetes.io/name: <cluster_name>
  name: cluster-authn-filter
  namespace: istio-system
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              name: istio.metadata_exchange
          sni: "*"
    patch:
      operation: INSERT_AFTER
      value:
        name: envoy.filters.http.ext_authz
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
          http_service:
            authorizationRequest:
              allowedHeaders:
                patterns:
                - exact: accept
                - exact: authorization
                - exact: cookie
                - exact: from
                - exact: proxy-authorization
                - exact: user-agent
                - exact: x-forwarded-access-token
                - exact: x-forwarded-email
                - exact: x-forwarded-for
                - exact: x-forwarded-host
                - exact: x-forwarded-proto
                - exact: x-forwarded-user
                - prefix: x-auth-request
                - prefix: x-forwarded
            authorizationResponse:
              allowedClientHeaders:
                patterns:
                - exact: authorization
                - exact: location
                - exact: proxy-authenticate
                - exact: set-cookie
                - exact: www-authenticate
                - prefix: x-auth-request
                - prefix: x-forwarded
              allowedUpstreamHeaders:
                patterns:
                - exact: authorization
                - exact: location
                - exact: proxy-authenticate
                - exact: set-cookie
                - exact: www-authenticate
                - prefix: x-auth-request
                - prefix: x-forwarded
            server_uri:
              cluster: outbound|4180||oauth2-proxy.auth.svc.cluster.local
              timeout: 1.5s
              uri: http://oauth2-proxy.auth.svc.cluster.local
```

### Version

```prose
EKS Version : 1.20
Helm Version: 3.5.3
Kubectl Version: 1.21.0(client)/1.20.7(server)
Istio Version: 1.11.1
```

### Additional Information

It shows the listeners & routing are working as expected.

```
$ istioctl proxy-config listeners -n istio-system <ingress-gateway-pod>
ADDRESS PORT  MATCH DESTINATION
0.0.0.0 8080  ALL   Route: http.8080
0.0.0.0 8443  ALL   Route: http.8443
0.0.0.0 15021 ALL   Inline Route: /healthz/ready*
0.0.0.0 15090 ALL   Inline Route: /stats/prometheus*

$ istioctl proxy-config routes -n istio-system <ingress-gateway-pod>
NOTE: This output only contains routes loaded via RDS.
NAME          DOMAINS                        MATCH             VIRTUAL SERVICE
http.8080     dex.domain.com                                     dex-cluster-domain-com-ingress-istio-autogenerated-k8s-ingress.istio-system
http.8080     oauth2-proxy.domain.com                    oauth2-proxy-cluster-domain-com-ingress-istio-autogenerated-k8s-ingress.istio-system
http.8080     kubernetes-dashboard.domain.com    kubernetes-dashboard-cluster-domain-com-ingress-istio-autogenerated-k8s-ingress.istio-system
http.8080     dex.domain.com           /*                       dex.auth
http.8080     oauth2-proxy.domain.com           /*       oauth2-proxy.auth
http.8080     kubernetes-dashboard.domain.com           /*       kubernetes-dashboard. kubernetes-dashboard
http.8443     dex.domain.com           /*                       dex.auth
http.8443     oauth2-proxy.domain.com           /*                       oauth2-proxy.auth
http.8443     kubernetes-dashboard.domain.com           /*       kubernetes-dashboard.kubernetes-dashboard
              *                                              /healthz/ready*        
              *                                              /stats/prometheus*     
```

Getting 503:

```
$ curl -iL https://dex.domain.com
HTTP/1.1 503 Service Unavailable
date: Fri, 03 Sep 2021 15:23:26 GMT
server: istio-envoy
content-length: 0

$ curl -I https://dex.domain.com -vvv
*   Trying x.xx.xx.xxx...
* TCP_NODELAY set
* Connected to dex.domain.com (x.xx.xx.xxx) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.domain.com
*  start date: Sep  3 00:00:00 2021 GMT
*  expire date: Oct  2 23:59:59 2022 GMT
*  subjectAltName: host "dex.domain.com" matched cert's "*.domain.com"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
> HEAD / HTTP/1.1
> Host: dex.domain.com
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 503 Service Unavailable
HTTP/1.1 503 Service Unavailable
< date: Fri, 03 Sep 2021 15:24:06 GMT
date: Fri, 03 Sep 2021 15:24:06 GMT
< server: istio-envoy
server: istio-envoy
< transfer-encoding: chunked
transfer-encoding: chunked

< 
* Connection #0 to host dex.domain.com left intact
* Closing connection 0
```

**Comment by amalendur** [comment]
There is no DestinationRule in place in the cluster.

**Comment by amalendur** [comment]
I have changed 
ingress-gateway as following;
```
gateways:
  istio-ingressgateway:
    type: LoadBalancer
    serviceAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: < acm_certificate_arn >
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: 443
    externalTrafficPolicy: "Local"
```
gateway for the app as following;
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cluster-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - "*"
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - app.domain.com
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        mode: PASSTHROUGH

```

virtualService as following;
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app
  namespace: app
spec:
  gateways:
    - istio-system/cluster-gateway
  hosts:
  # The full host name of the app.
    - app.domain.com
  tls:
  - match:
    - sniHosts: ["app.domain.com"]
      port: 443
    route:
    - destination:
        host: app
```

Now I'm getting 
```
$ curl -iL https://app.domain.com -v
*   Trying x.xxx.xxx.xx...
* TCP_NODELAY set
* Connected to app.domain.com (x.xxx.xxx.xx) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.domain.com
*  start date: Sep  5 00:00:00 2021 GMT
*  expire date: Oct  4 23:59:59 2022 GMT
*  subjectAltName: host "app.domain.com" matched cert's "*.domain.com"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: app.domain.com
> User-Agent: curl/7.64.1
> Accept: */*
> 
* TLSv1.2 (IN), TLS alert, close notify (256):
* Empty reply from server
* Connection #0 to host app.domain.com left intact
curl: (52) Empty reply from server
* Closing connection 0
```

From Istiod log
```

2021-09-05T19:57:19.034977Z	debug	istio-ingressgateway.istio-system omitting routes for virtual service app/app due to error: no routes matched
```

**Comment by amalendur** [comment]
After read the Istio documentation from somewhere "Istio Ingress has been replaced by Gateway object and VirtualService , from  Istio 0.8. I have removed the ingress object from my configuration(ingress.yaml).
But still getting the same error as following;
```
* TLSv1.2 (IN), TLS alert, close notify (256):
* Empty reply from server
* Connection #0 to host app.domain.com left intact
curl: (52) Empty reply from server
* Closing connection 0
```

**Comment by amalendur** [comment]
any update/suggestion on this issue?

**Comment by amalendur** [comment]
I did some additional test, and here is the response;

```
$ curl -s -I -HHost:dashboard.domain.com "http://<loadbalancer_host_name>:80/status/200" -v
*   Trying xx.xxx.xxx.xxx...
* TCP_NODELAY set
* Connected to <loadbalancer_host_name> (xx.xxx.xxx.xxx) port 80 (#0)
> HEAD /status/200 HTTP/1.1
> Host:dashboard.domain.com
> User-Agent: curl/7.64.1
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host <loadbalancer_host_name> left intact
* Closing connection 0

$ curl -s -I -HHost:dashboard.domain.com "http://<loadbalancer_host_name>:443/status/200" -v
*   Trying xx.xxx.xxx.xxx...
* TCP_NODELAY set
* Connected to <loadbalancer_host_name> (xx.xxx.xxx.xxx) port 443 (#0)
> HEAD /status/200 HTTP/1.1
> Host:dashboard.domain.com
> User-Agent: curl/7.64.1
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host <loadbalancer_host_name> left intact
* Closing connection 0
```

**Comment by amalendur** [comment]
With respect to https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRetry, I have add the following block in all the virtualServices
```
route:
    retries:
      attempts: 3
      perTryTimeout: 5s
      retryOn: gateway-error,connect-failure,refused-stream
```

additionally increases the "livenessProbe:timeoutSecond".
```
livenessProbe:
  enabled: true
  periodSeconds: 10
  timeoutSeconds: 30
```

and getting the following;
```
$ curl -s -I -HHost:dashboard.domain.com "http://<loadbalancer_host_name>:80/status/200" -v
*   Trying x.xxx.xxx.xxx...
* TCP_NODELAY set
* Connected to <loadbalancer_host_name> (x.xxx.xxx.xxx) port 80 (#0)
> HEAD /status/200 HTTP/1.1
> Host:dashboard.domain.com
> User-Agent: curl/7.64.1
> Accept: */*
> 
* Recv failure: Connection reset by peer
* Closing connection 0

$ curl -s -I -HHost:dashboard.domain.com "http://<loadbalancer_host_name>:443/status/200" -v
*   Trying x.xxx.xxx.xxx...
* TCP_NODELAY set
* Connected to <loadbalancer_host_name> (x.xxx.xxx.xxx) port 443 (#0)
> HEAD /status/200 HTTP/1.1
> Host:dashboard.domain.com
> User-Agent: curl/7.64.1
> Accept: */*
> 
* Closing connection 0

```
****note# there is no PeerAuthentication policies...
```
$ kubectl get peerauthentication --all-namespaces
No resources found
```
