### ISSUE TITLE
the domain name cannot be resolved after sidecar is injected using smart DNS

### ISSUE THREAD

**Issue by xichengliudui** [istio/istio#35038]
### Bug Description

It is normal to access the `httpbin service` before sidecar injection
```shell
[root@test mesh_test]# kubectl get pod -n sleep-sys
NAME                       READY   STATUS    RESTARTS   AGE
httpbin-66595f694c-kgpzp   1/1     Running   0          94m
sleep-6596b5c47f-f4546     1/1     Running   0          55s
```
```shell
/ # curl http://httpbin.sleep-sys:8000/ip
{
  "origin": "10.0.0.243"
}
```
failed to resolve domain name when accessing `httpbin service` after sidecar injection
```shell
[root@test mesh_test]# kubectl get pod -n sleep-sys
NAME                       READY   STATUS    RESTARTS   AGE
httpbin-66595f694c-kgpzp   1/1     Running   0          101m
sleep-5c49bc4489-lq2gk     2/2     Running   0          3m58s
```
```shell
/ # curl http://httpbin.sleep-sys:8000/ip
curl: (6) Could not resolve host: httpbin.sleep-sys
/ # curl http://httpbin.sleep-sys:8000/headers
curl: (6) Could not resolve host: httpbin.sleep-sy
```

### Version

```prose
[root@test ~]# ./istioctl version
client version: 1.8.1
control plane version: 1.8.4-97e10d79b8b5b32be0f92175586a4e11c466e640
data plane version: 1.8.4 (9 proxies)
```

### Additional Information
```shell
[root@test mesh_test]# kubectl get pod -n istio-system
NAME                                    READY   STATUS    RESTARTS   AGE
istio-egressgateway-8cf6878-zjjxn       1/1     Running   0          77m
istio-ingressgateway-587bbcc8dc-z9p7v   1/1     Running   0          77m
istiod-iop-1-8-4-5d64f455f9-tm7zv       1/1     Running   0          6h45m
prometheus-6876fcc89f-27278             2/2     Running   0          6h45m
```
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: iop-panel-26-1-8-4
  namespace: istio-system
spec:
  components:
    egressGateways:
    - enabled: true
      k8s:
        env:
        - name: ISTIO_META_ROUTER_MODE
          value: sni-dnat
        - name: TZ
          value: CST-8
        replicaCount: 1
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 50Mi
        service:
          ports:
          - name: http2
            port: 80
            protocol: TCP
            targetPort: 8080
          - name: https
            port: 443
            protocol: TCP
            targetPort: 8443
          - name: tls
            port: 15443
            protocol: TCP
            targetPort: 15443
          type: NodePort
        strategy:
          rollingUpdate:
            maxSurge: 100%
            maxUnavailable: 25%
      name: istio-egressgateway
    ingressGateways:
    - enabled: true
      k8s:
        env:
        - name: ISTIO_META_ROUTER_MODE
          value: sni-dnat
        - name: TZ
          value: CST-8
        replicaCount: 1
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 50Mi
        service:
          ports:
          - name: tls
            nodePort: 32003
            port: 15443
            protocol: TCP
            targetPort: 15443
          - name: http2
            nodePort: 32004
            port: 80
            protocol: TCP
            targetPort: 8080
          - name: https
            nodePort: 32005
            port: 443
            protocol: TCP
            targetPort: 8443
          type: NodePort
        strategy:
          rollingUpdate:
            maxSurge: 100%
            maxUnavailable: 25%
      name: istio-ingressgateway
    pilot:
      enabled: true
      k8s:
        env:
        - name: TZ
          value: CST-8
        - name: PILOT_ENABLE_WORKLOAD_ENTRY_AUTOREGISTRATION
          value: "true"
        replicaCount: 1
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 50Mi
        strategy:
          rollingUpdate:
            maxSurge: 100%
            maxUnavailable: 25%
  meshConfig:
    defaultConfig:
      concurrency: 2
      proxyMetadata:
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
        ISTIO_META_DNS_CAPTURE: "true"
      tracing:
        custom_tags:
          mesh:
            header:
              defaultValue: mesh
              name: mesh
          tag_clustername:
            literal:
              value: panel-26
        sampling: 100
    enableAutoMtls: true
    enableTracing: true
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
  revision: iop-1-8-4
  tag: 1.8.4
  values:
    global:
      imagePullPolicy: IfNotPresent
      istioNamespace: istio-system
      jwtPolicy: first-party-jwt
      meshExpansion:
        enabled: true
        useILB: false
      multiCluster:
        clusterName: panel-26
        enabled: true
        globalDomainSuffix: global
        includeEnvoyFilter: true
      podDNSSearchNamespaces:
      - global
      proxy:
        holdApplicationUntilProxyStarts: false
        image: proxyv2
        logLevel: warning
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 50Mi
      tracer:
        zipkin:
          address: 10.20.21.11:30411
```
