### ISSUE TITLE
How to make access log stored into a custom file.

### ISSUE THREAD

**Issue by ningyougang** [istio/istio#35055]
Refer to this article: https://istio.io/latest/docs/tasks/observability/logs/access-log/ ,e.g.
```
$ kubectl logs -l app=sleep -c istio-proxy
[2020-11-25T21:26:18.409Z] "GET /status/418 HTTP/1.1" 418 - via_upstream - "-" 0 135 4 4 "-" "curl/7.73.0-DEV" "84961386-6d84-929d-98bd-c5aee93b5c88" "httpbin:8000" "10.44.1.27:80" outbound|8000||httpbin.foo.svc.cluster.local 10.44.1.23:37652 10.0.45.184:8000 10.44.1.23:46520 - default
```
We can get the access log easily, but it printed to the standard output by default (And can be found at /var/log/pods/$pod/.....json file)

Can we configure the access log to a custom file of the istio-proxy container while support standard output as well?

**Comment by ningyougang** [comment]
I added some changes(add --log-path to envoy) to istio/proxyv2 image
So i added  `--log-path /var/lib/istio/data/envoy.log` to the envoy process, but the access log didn't print to envoy.log.

btw, have any method of `add blow configuration to all dynamic_resources and static_resources`?
```
  custom-envoy.yaml: |-
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          access_log:
          - name: envoy.access_loggers.file
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: /var/lib/istio/data/access_log.log
```
