### ISSUE TITLE
JWT claim to HTTP header

### ISSUE THREAD

**Issue by vmasyagin** [istio/istio#35108]
Good afternoon.

I am asking you to help me figure out how to add headers to a request based on information from the jwt token. At the moment, we have the following configuration installed: the istio project is installed in the istio-system namespace, version 1.11.1 with the demo profile. The foo namespace contains the app microservice of 2 versions. It is necessary, based on the information received from the token, to send a request to a particular version of the app service. At the moment, the following entities have been created in the foo namespace:
```
-----
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: foo-ingressgateway
  namespace: foo
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - foo-ingressgateway.mycompany.com
-----
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: app
  namespace: foo
spec:
  host: app.foo.svc.cluster.local
  subsets:
    - labels:
        version: prod
      name: prod
      trafficPolicy:
        connectionPool:
          http: {}
          tcp: {}
        loadBalancer:
          simple: ROUND_ROBIN
        outlierDetection:
          baseEjectionTime: 30s
          consecutiveErrors: 1
          interval: 5s
          maxEjectionPercent: 100
    - labels:
        version: canary
      name: canary
      trafficPolicy:
        connectionPool:
          http: {}
          tcp: {}
        loadBalancer:
          simple: ROUND_ROBIN
        outlierDetection:
          baseEjectionTime: 30s
          consecutiveErrors: 1
          interval: 5s
          maxEjectionPercent: 100
  trafficPolicy:
    portLevelSettings:
      - loadBalancer:
          simple: LEAST_CONN
        port:
          number: 80
      - loadBalancer:
          simple: ROUND_ROBIN
        port:
          number: 8080
-----
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: foo-virtual-service
  namespace: foo
spec:
  gateways:
    - foo / foo-ingressgateway
  hosts:
    - '*'
  http:
    - match:
        - headers:
            x-istio-jwt-group:
              exact: canary
          uri:
            prefix: / app
      rewrite:
        uri: / app
      route:
        - destination:
            host: app
            port:
              number: 8080
            subset: canary
          weight: 100
    - match:
        - uri:
            prefix: / app
      rewrite:
        uri: / app
      route:
        - destination:
            host: app
            port:
              number: 8080
            subset: prod
          weight: 100
-----
```
When I pass the header directly in the request, everything works fine.
```
curl http://foo-ingressgateway.mycompany.com/app/info -H "x-istio-jwt-group: canary"
{
  "name": "app",
  "version": "canary"
}
curl http://foo-ingressgateway.mycompany.com/app/info -H "x-istio-jwt-group: prod"
{
  "name": "app",
  "version": "prod"
}
```

Now I'm trying to pull this trick, but adding the x-istio-jwt-group header by parsing the jwt token. I add entities:
```
-----
apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: "jwt-request-authentication"
  namespace: foo
spec:
  selector:
    matchLabels:
      app: app
  jwtRules:
  - issuer: myissuer
    jwks: |
       {"keys": [{"e": "AQAB", "kty": "RSA", "n": "<correct>"}]}
-----
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: require-jwt
spec:
  selector:
    matchLabels:
      app: app
  action: ALLOW
  rules:
  - from:
    - source:
        requestPrincipals: ["myissuer / myuser"]
-----
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: jwt-to-header-filter
  namespace: foo
spec:
  workloadSelector:
    labels:
      app: app
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.lua
        config:
          inlineCode: |
            function envoy_on_request (request_handle)
              local meta = request_handle: streamInfo (): dynamicMetadata (): get ("envoy.filters.http.jwt_authn")
              local claims = meta ["myissuer"]
              local group = claims.group
              request_handle: logInfo ("group" .. group)
              request_handle: headers (): add ("x-istio-jwt-group", group)
            end
```
Now I am constantly routed to the prod version of the app:
```
curl http://foo-ingressgateway.mycompany.com/app/info -H "Authorization: Bearer $ TOKEN"
{
  "name": "app",
  "version": "prod"
}
```
After that I tried to apply other Lua filters without success, also saw the following document (https://docs.google.com/document/d/1eJ4sPt5-fbXytSwov7senndMsrq4Et6qNYQKicLGHDs/edit#) and tried to apply the techniques described there, but it seems to be still under development. Please, tell me, what am I doing wrong and how can I achieve the desired result?
