### ISSUE TITLE
istio-ingressgateway throw a lot of route_not_found prometheus /metrics logs

### ISSUE THREAD

**Issue by xichengliudui** [istio/istio#35122]
### Bug Description

kubectl logs -f istio-ingressgateway-5bc68d4cd7-bhrmb  -n istio-system
```
[2021-09-10T02:31:12.093Z] "GET /metrics HTTP/1.1" 404 NR route_not_found - "-" 0 0 0 - "10.0.54.168" "Prometheus/2.21.0" "74215fc5-3c7c-9601-967a-d0eb982bf6fe" "10.0.54.180:8080" "-" - - 10.0.54.180:8080 10.0.54.168:59378 - -
[2021-09-10T02:31:27.093Z] "GET /metrics HTTP/1.1" 404 NR route_not_found - "-" 0 0 0 - "10.0.54.168" "Prometheus/2.21.0" "b0b6009c-c7fa-9807-8dd7-b0ae8d789622" "10.0.54.180:8080" "-" - - 10.0.54.180:8080 10.0.54.168:59378 - -
[2021-09-10T02:31:42.093Z] "GET /metrics HTTP/1.1" 404 NR route_not_found - "-" 0 0 0 - "10.0.54.168" "Prometheus/2.21.0" "a305ae6b-b946-9936-a5d8-0df043e4c782" "10.0.54.180:8080" "-" - - 10.0.54.180:8080 10.0.54.168:59378 - -
[2021-09-10T02:31:57.093Z] "GET /metrics HTTP/1.1" 404 NR route_not_found - "-" 0 0 0 - "10.0.54.168" "Prometheus/2.21.0" "b7dcfa71-922d-91e5-a07e-be7609892d7a" "10.0.54.180:8080" "-" - - 10.0.54.180:8080 10.0.54.168:59378 - -
[2021-09-10T02:32:12.093Z] "GET /metrics HTTP/1.1" 404 NR route_not_found - "-" 0 0 0 - "10.0.54.168" "Prometheus/2.21.0" "bb3339c9-d441-98a4-8934-fb89360b99f4" "10.0.54.180:8080" "-" - - 10.0.54.180:8080 10.0.54.168:59378 - -
[2021-09-10T02:32:27.093Z] "GET /metrics HTTP/1.1" 404 NR route_not_found - "-" 0 0 0 - "10.0.54.168" "Prometheus/2.21.0" "b0235757-e0ed-9dbb-bb16-b7668db74e13" "10.0.54.180:8080" "-" - - 10.0.54.180:8080 10.0.54.168:59378 - -
[2021-09-10T02:32:42.093Z] "GET /metrics HTTP/1.1" 404 NR route_not_found - "-" 0 0 0 - "10.0.54.168" "Prometheus/2.21.0" "9a85b819-d598-9ba4-a333-7deafea6ab8c" "10.0.54.180:8080" "-" - - 10.0.54.180:8080 10.0.54.168:59378 - -
[2021-09-10T02:32:57.093Z] "GET /metrics HTTP/1.1" 404 NR route_not_found - "-" 0 0 0 - "10.0.54.168" "Prometheus/2.21.0" "db8c9cfe-96d2-9a8c-a711-8859739d20b6" "10.0.54.180:8080" "-" - - 10.0.54.180:8080 10.0.54.168:59378 - -
[2021-09-10T02:33:12.093Z] "GET /metrics HTTP/1.1" 404 NR route_not_found - "-" 0 0 0 - "10.0.54.168" "Prometheus/2.21.0" "3c9f04ab-200a-93a7-89e0-7399e1f8c95f" "10.0.54.180:8080" "-" - - 10.0.54.180:8080 10.0.54.168:59378 - -
[2021-09-10T02:33:27.093Z] "GET /metrics HTTP/1.1" 404 NR route_not_found - "-" 0 0 0 - "10.0.54.168" "Prometheus/2.21.0" "c167ae07-2c08-9468-b789-ce8b1df204bb" "10.0.54.180:8080" "-" - - 10.0.54.180:8080 10.0.54.168:59378 - -
[2021-09-10T02:33:42.093Z] "GET /metrics HTTP/1.1" 404 NR route_not_found - "-" 0 0 0 - "10.0.54.168" "Prometheus/2.21.0" "19871b04-6573-9a3d-a90b-8d1709b6dead" "10.0.54.180:8080" "-" - - 10.0.54.180:8080 10.0.54.168:59378 - -
[2021-09-10T02:33:57.093Z] "GET /metrics HTTP/1.1" 404 NR route_not_found - "-" 0 0 0 - "10.0.54.168" "Prometheus/2.21.0" "01e84c7e-60d3-921a-bba7-287359c7bf67" "10.0.54.180:8080" "-" - - 10.0.54.180:8080 10.0.54.168:59378 - -
[2021-09-10T02:34:12.093Z] "GET /metrics HTTP/1.1" 404 NR route_not_found - "-" 0 0 0 - "10.0.54.168" "Prometheus/2.21.0" "9b36894e-7cf5-9a37-9407-40c2751a728e" "10.0.54.180:8080" "-" - - 10.0.54.180:8080 10.0.54.168:59378 - -
[2021-09-10T02:34:27.093Z] "GET /metrics HTTP/1.1" 404 NR route_not_found - "-" 0 0 0 - "10.0.54.168" "Prometheus/2.21.0" "50775227-64a7-9511-9311-0e5d9f37fc66" "10.0.54.180:8080" "-" - - 10.0.54.180:8080 10.0.54.168:59378 - -
```
the response to the curl command is correct, podip:port or serviceip:port
```
istio-proxy@istio-ingressgateway-5bc68d4cd7-bhrmb:/$ curl 10.0.54.168:9090/metrics
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 7.3619e-05
go_gc_duration_seconds{quantile="0.25"} 0.000120826
go_gc_duration_seconds{quantile="0.5"} 0.000155356
......
# HELP promhttp_metric_handler_requests_total Total number of scrapes by HTTP status code.
# TYPE promhttp_metric_handler_requests_total counter
promhttp_metric_handler_requests_total{code="200"} 186
promhttp_metric_handler_requests_total{code="500"} 0
promhttp_metric_handler_requests_total{code="503"} 0
```
```
istio-proxy@istio-ingressgateway-5bc68d4cd7-bhrmb:/$ curl http://prometheus.istio-system:9090/metrics
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 7.3619e-05
go_gc_duration_seconds{quantile="0.25"} 0.000120826
go_gc_duration_seconds{quantile="0.5"} 0.000152459
......
# HELP promhttp_metric_handler_requests_total Total number of scrapes by HTTP status code.
# TYPE promhttp_metric_handler_requests_total counter
promhttp_metric_handler_requests_total{code="200"} 218
promhttp_metric_handler_requests_total{code="500"} 0
promhttp_metric_handler_requests_total{code="503"} 0
```

### Version

```prose
client version: 1.8.1
control plane version: 1.10.0
data plane version: 1.10.0 (8 proxies)
```

### Additional Information

NONE

**Comment by xichengliudui** [comment]
Is this due to istio or k8s?

**Comment by howardjohn** [comment]
It sounds like you have configured Prometheus to scrape port 8080 on the ingressgateway - which doesn't serve metrics. Maybe you wanted 15090,the metrics port

**Comment by xichengliudui** [comment]
> It sounds like you have configured Prometheus to scrape port 8080 on the ingressgateway - which doesn't serve metrics. Maybe you wanted 15090,the metrics port

thank you for your reply
but my Prometheus was installed by default, and I didn't change any configuration，are there any other configurations that need to be verified?
```yaml
apiVersion: v1
data:
  alerting_rules.yml: |
    {}
  alerts: |
    {}
  prometheus.yml: |
    global:
      evaluation_interval: 1m
      scrape_interval: 15s
      scrape_timeout: 10s
    rule_files:
    - /etc/config/recording_rules.yml
    - /etc/config/alerting_rules.yml
    - /etc/config/rules
    - /etc/config/alerts
    scrape_configs:
    - job_name: 'pilot'
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - istio-system
    - job_name: 'envoy-stats'
      metrics_path: /stats/prometheus
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_container_port_name]
        action: keep
        regex: '.*-envoy-prom'
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:15090
        target_label: __address__
      - action: labeldrop
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: pod_name
    - job_name: prometheus
      static_configs:
      - targets:
        - localhost:9090
    - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      job_name: kubernetes-apiservers
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - action: keep
        regex: default;kubernetes;https
        source_labels:
        - __meta_kubernetes_namespace
        - __meta_kubernetes_service_name
        - __meta_kubernetes_endpoint_port_name
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
    - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      job_name: kubernetes-nodes
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - replacement: kubernetes.default.svc:443
        target_label: __address__
      - regex: (.+)
        replacement: /api/v1/nodes/$1/proxy/metrics
        source_labels:
        - __meta_kubernetes_node_name
        target_label: __metrics_path__
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
    - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      job_name: kubernetes-nodes-cadvisor
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - replacement: kubernetes.default.svc:443
        target_label: __address__
      - regex: (.+)
        replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
        source_labels:
        - __meta_kubernetes_node_name
        target_label: __metrics_path__
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
    - job_name: kubernetes-service-endpoints
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - action: keep
        regex: true
        source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_scrape
      - action: replace
        regex: (https?)
        source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_scheme
        target_label: __scheme__
      - action: replace
        regex: (.+)
        source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_path
        target_label: __metrics_path__
      - action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        source_labels:
        - __address__
        - __meta_kubernetes_service_annotation_prometheus_io_port
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: kubernetes_namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_service_name
        target_label: kubernetes_name
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: kubernetes_node
    - job_name: kubernetes-service-endpoints-slow
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - action: keep
        regex: true
        source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_scrape_slow
      - action: replace
        regex: (https?)
        source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_scheme
        target_label: __scheme__
      - action: replace
        regex: (.+)
        source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_path
        target_label: __metrics_path__
      - action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        source_labels:
        - __address__
        - __meta_kubernetes_service_annotation_prometheus_io_port
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: kubernetes_namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_service_name
        target_label: kubernetes_name
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: kubernetes_node
      scrape_interval: 5m
      scrape_timeout: 30s
    - honor_labels: true
      job_name: prometheus-pushgateway
      kubernetes_sd_configs:
      - role: service
      relabel_configs:
      - action: keep
        regex: pushgateway
        source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_probe
    - job_name: kubernetes-services
      kubernetes_sd_configs:
      - role: service
      metrics_path: /probe
      params:
        module:
        - http_2xx
      relabel_configs:
      - action: keep
        regex: true
        source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_probe
      - source_labels:
        - __address__
        target_label: __param_target
      - replacement: blackbox
        target_label: __address__
      - source_labels:
        - __param_target
        target_label: instance
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - source_labels:
        - __meta_kubernetes_namespace
        target_label: kubernetes_namespace
      - source_labels:
        - __meta_kubernetes_service_name
        target_label: kubernetes_name
    - job_name: kubernetes-pods
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: keep
        regex: true
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_scrape
      - action: replace
        regex: (.+)
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_path
        target_label: __metrics_path__
      - action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        source_labels:
        - __address__
        - __meta_kubernetes_pod_annotation_prometheus_io_port
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: kubernetes_namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: kubernetes_pod_name
      - action: drop
        regex: Pending|Succeeded|Failed
        source_labels:
        - __meta_kubernetes_pod_phase
    - job_name: kubernetes-pods-slow
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: keep
        regex: true
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_scrape_slow
      - action: replace
        regex: (.+)
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_path
        target_label: __metrics_path__
      - action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        source_labels:
        - __address__
        - __meta_kubernetes_pod_annotation_prometheus_io_port
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: kubernetes_namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: kubernetes_pod_name
      - action: drop
        regex: Pending|Succeeded|Failed
        source_labels:
        - __meta_kubernetes_pod_phase
      scrape_interval: 5m
      scrape_timeout: 30s
  recording_rules.yml: |
    {}
  rules: |
    {}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-10T03:31:12Z"
  labels:
    app: prometheus
    beyondmesh.io/addons: prometheus
    release: prometheus
  name: prometheus
  namespace: istio-system
```
