### ISSUE TITLE
Accessing remote cluster VirtualService

### ISSUE THREAD

**Issue by daniel-pebble** [istio/istio#35142]
Hi, 

I've setup two clusters in a multi-primary/multi-network configuration.  The system has two uniquely named VirtualService deployed in each cluster however it isn't possible to access the VirtualService.  
I've enabled Smart DNS proxying and I can resolve the IP address of the remote VirtualService however when I connect I just get a 503 error. 

The k8s service doesn't have a selector as the VirtualService is used to route to different backend services however if I set a selector I can connect to said service remotely.   Also, I've deployed the multi-cluster sample app and this performs as expected.

Does Istio support connecting to a remote VirtualService that don't have a duplicate VirtualService in the local cluster?

**Example** 
API request in cluster 1 which returns 503, the same call in cluster 2 is successful
GET http://site-2.default.svc.cluster.local/api/1/service
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: site-2
  namespace: default
spec:
  hosts:
  - site-2.default.svc.cluster.local
  http:
  - match:
    - uri:
        exact: /api/1/servicetwo
    - uri:
        prefix: /api/1/servicetwo
    route:
    - destination:
        host: servicetwo.default.svc.cluster.local
  http:
  - match:
    - uri:
        exact: /api/1/servicethree
    - uri:
        prefix: /api/1/servicethree
    route:
    - destination:
        host: servicethree.default.svc.cluster.local
```
I do see the remote service (site-1) in the "proxy-config cluster" but not under endpoints
![image](https://user-images.githubusercontent.com/47243318/132914943-0516f1e9-5943-42ab-bc28-799e527963e6.png)

![DR Playground (12)](https://user-images.githubusercontent.com/47243318/132914597-05dcdc18-1a05-4faf-b3e3-89fd507406eb.jpg)
