### ISSUE TITLE
ServcieEntry with baked any domen not work as expected

### ISSUE THREAD

**Issue by kdv611** [istio/istio#35163]
### Bug Description

In docs example https://istio.io/latest/docs/reference/config/networking/service-entry/#ServiceEntry:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-dns
spec:
  hosts:
  - my.host.com #is non-existent external service
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
  endpoints:
  - address:  my.real1.com
    ports:
      http: 80
  - address: my.real2.com
    ports:
      http: 80
  - address: my.real1.com
    ports:
      http: 80
```
where host my.host.com is non-existent external service.
Next, it is created DestinationRule for load balancing on host my.host.com with ROUND_ROBIN
When trying to direct traffic from any pod with curl "curl my.host.com:80" an error occurs "could not resolve host".
Next, it is created Service with name my-virtual-svc and create VirtualService, where 
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: my-virtual-service
spec:
  exportTo:
    - .
  gateways:
    - mesh
  hosts:
    - my-virtual-svc
  http:
    - match:
        - gateways:
            - mesh
          port: 80
      route:
        - destination:
            host: my.host.com
            port:
              number: 80
```

```
After when use "curl my-virtual-svc:80/simple-forward/actuator/health" i see log envoy
GET /simple-forward/actuator/health HTTP/1.1" 503 URX "-" "-" 0 3265 28 27 "-" "curl/7.29.0" "85de2571-7c52-45ff-b49a-30cfb3b11a48" "my-virtual-svc:80" "XXX.XXX.XXX.157:80" outbound|80||my.host.com - 172.30.54.73:80 29.64.174.82:50434
GET /simple-forward/actuator/health HTTP/1.1" 503 URX "-" "-" 0 3265 28 27 "-" "curl/7.29.0" "85de2571-7c52-45ff-b49a-30cfb3b11a48" "my-virtual-svc:80" "XXX.XXX.XXX.158:80" outbound|80||my.host.com - 172.30.54.73:80 29.64.174.82:50434
GET /simple-forward/actuator/health HTTP/1.1" 503 URX "-" "-" 0 3265 28 27 "-" "curl/7.29.0" "85de2571-7c52-45ff-b49a-30cfb3b11a48" "my-virtual-svc:80" "XXX.XXX.XXX.159:80" outbound|80||my.host.com - 172.30.54.73:80 29.64.174.82:50434
```
My question: how to manage Authority header so that the header is equals name of endpoint address, to which the traffic was sent?

### Version

```prose
istioctl version 1.4.3
```
