### ISSUE TITLE
Will be Extension Providers available as a CRD

### ISSUE THREAD

**Issue by juancgalvis** [istio/istio#35165]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

The extensionProviders configuration will be available through a CRD?, which is available only through the configmap

**Describe alternatives you've considered**

Currently the configuration of extensionProviders is available only through a configmap in the istio-system namespace, if it were available through a CRD it would be very simple to give autonomy to applications in different namespaces using their own extension configuration.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

[external-authz](https://istio.io/latest/blog/2021/better-external-authz/)

```yaml
extensionProviders:
# The name "my-ext-authz-service" is referred to by the authorization policy in its provider field.
- name: "my-ext-authz-service"
  # The "envoyExtAuthzGrpc" field specifies the type of the external authorization service is implemented by the Envoy
  # ext-authz filter gRPC API. The other supported type is the Envoy ext-authz filter HTTP API.
  # See more in https://www.envoyproxy.io/docs/envoy/v1.16.2/intro/arch_overview/security/ext_authz_filter.
  envoyExtAuthzGrpc:
    # The service and port specifies the address of the external auth service, "ext-authz.istio-system.svc.cluster.local"
    # means the service is deployed in the mesh. It can also be defined out of the mesh or even inside the pod as a separate
    # container.
    service: "ext-authz.istio-system.svc.cluster.local"
    port: 9000

```

For exmple with CRD

```yaml
apiVersion: security.istio.io/v1beta1
kind: ExtensionProvider
metadata:
  namespace: my-app-namespace
  name: my-ext-authz-service
spec:
  envoyExtAuthzGrpc:
    service: "ext-authz.my-app-namespace.svc.cluster.local"
    port: 9000
```

Policy usage will be the same

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  namespace: my-app-namespace
  name: my-ext-authz-service
spec:
  selector:
    matchLabels:
      app: httpbin-custom
  action: CUSTOM
  provider:
    name: my-ext-authz-service
  rules:
    - {}
```

**Comment by thesuperzapper** [comment]
@howardjohn @stevenctl what are your thoughts on this?

I think it's a very good idea to decouple `MeshConfig.ExtensionProvider` from the global MeshConfig, otherwise, application owners need to update configs in `istio-system` (under `ConfigMap/istio`) just to specify their `ExtensionProvider` to be used in their `AuthorizationPolicy`.

This will also let us put limits on which `AuthorizationPolicy` can use each `ExtensionProvider` rather than the free-for-all it is right now (for example, by namespace).

**Comment by psandhu79** [comment]
+1

**Comment by yehudacohen** [comment]
Have a similar need to the one expressed by @thesuperzapper above. Would be a great addition.

**Comment by psandhu79** [comment]
@douglas-reid are you thinking of describing the extension provider as a label/annotation.

My use case is an ops team control the Istio installation and myself as a app team can only control resources within my app namespace

**Comment by douglas-reid** [comment]
@psandhu79 there were a number of ideas, including label/annotation. it sounds like in your use case, that would be a non-starter (due to access concerns) ?  Is that correct?

I've been focused purely on Telemetry API-related extension stuff. Are you more interested in Authz?

**Comment by dabing1986** [comment]
Sorry to jump in here. Our case looks similar but I am not sure the fix of this request will meet our requirement. 
we introduce out own extension provider and follow the guide 'manually' adding the extensionProvider in the istion configmap. My op colleagues ask if there is any command to replace this mannual step. take authorization policy for example 
I can always use 
`apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ext-authz
  namespace: istio-system`
to apply the authorization policy in the cluster. but for extensionProvider . we can not .. 
another issue we are facing is we don't know which command is used for injecting the configmap in istio meaning we want to add a part and don't update the whole config map .. any thought ..

**Comment by psandhu79** [comment]
Is this not a similar issue #37764 

Is this possible to do this as part of the envoyfilter instead , i am interested in replicating this 

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: external-public-api
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app:external-public-api
  action: CUSTOM
  provider:
    name: "external-auth-provider"
  rules:
  - to:
    - operation:
        paths: ["/api/endpoint*"]
```

Or do we need to write a mutating webhook, or operator to inject into the istio configmap?

**Comment by psandhu79** [comment]
Managed to get it working with EnvoyFilters here is an example
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: external-public-api
  namespace: {{ .Release.Namespace }}
spec:
  workloadSelector:
    labels:
      app: app:external-public-api
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: INSERT_FIRST
      value: # cluster specification
        name: my.envoy.filters.http.ext_authz
        typedConfig:
          '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
          failureModeAllow: false
          httpService:
            authorizationRequest:
              allowedHeaders:
                patterns:
                - exact: user-id
                  ignore_case: true
            authorizationResponse:
              allowedUpstreamHeaders:
                patterns:
                - exact: auth
                  ignore_case: true
            serverUri:
              cluster: outbound|80||auth-service.{{ .Release.Namespace }}.svc.cluster.local
              timeout: 600s
              uri: http://auth-service.{{ .Release.Namespace }}.svc.cluster.local
          transport_api_version: "V3"
          filter_enabled_metadata:
            filter: "envoy.filters.http.rbac"
            path:
              - key: "istio_ext_authz_shadow_effective_policy_id"
            value:
              string_match:
                prefix: "istio-ext-authz"
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: INSERT_FIRST
      value: 
       name: my.envoy.filters.http.rbac
       typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC"
          shadow_rules:
            action: DENY
            policies:
              "istio-ext-authz-ns[{{ .Release.Namespace }}]-policy[external-public-api]-rule[0]":
                permissions:
                  - and_rules:
                      rules:
                        - or_rules:
                            rules:
                            - url_path:
                                path: { prefix: "/api/endpoints/" }

                principals:
                  - and_ids:
                     ids:
                      - any: true
          shadow_rules_stat_prefix: "istio_ext_authz_"
```

**Comment by tculp** [comment]
I think this should be reopened, the original need is still present. I would like to make authorizationProviders at a separate stage or with different permissions than the Istio install itself

**Comment by yogeshgadge** [comment]
Per namespace at the least proxy confix annotation should support extensionProvider. Something like this:-

```
        annotations:
        proxy.istio.io/config: |
            holdApplicationUntilProxyStarts: true
            extensionProviders:
            - name: "oauth2-proxy"
              envoyExtAuthzHttp:
                service: "oauth2-proxy.foo.svc.cluster.local"
                port: "4180" # The default port used by oauth2-proxy.
                includeRequestHeadersInCheck: ["authorization", "cookie"] # headers sent to the oauth2-proxy in the check request.
                headersToUpstreamOnAllow: ["authorization", "path", "x-auth-request-user", "x-auth-request-email", "x-auth-request-access-token"] # headers sent to backend application when request is allowed.
                headersToDownstreamOnAllow: ["set-cookie"] # headers sent back to the client when request is allowed.
                headersToDownstreamOnDeny: ["content-type", "set-cookie"] # headers sent back to the client when request is denied.
           
```
