### ISSUE TITLE
istio-cni fails to update when using the IstioOperator and going from 1.9 to 1.11

### ISSUE THREAD

**Issue by jbilliau-rcd** [istio/istio#35162]
We use the Istio Operator to deploy Istio to all of our clusters via Gitops/Flux. Upon updating our `IstioOperator` object from 1.9.6 to 1.11.2, everything seemed to go smoothly until we realized the cni didn't update. Inspecting the istio-operator logs, we see this:

```
2021-09-10T18:45:09.744221Z	info	installer	The following objects differ between generated manifest and cache:
 - DaemonSet:kube-system:istio-cni-node
2021-09-10T18:45:09.744438Z	info	installer	using server side apply to update obj: DaemonSet/kube-system/istio-cni-node
- Pruning removed resources
2021-09-10T18:45:09.823705Z	error	installer	failed to update resource with server-side apply for obj DaemonSet/kube-system/istio-cni-node: DaemonSet.apps "istio-cni-node" is invalid: spec.template.spec.containers[1].image: Required value
2021-09-10T18:45:09.824877Z	info	installer	Generated manifest objects are the same as cached for component IngressGateways.
✘ CNI encountered an error: failed to update resource with server-side apply for obj DaemonSet/kube-system/istio-cni-node: DaemonSet.apps "istio-cni-node" is invalid: spec.template.spec.containers[1].image: Required value
```

This is our `IstioOperator` YAML:

```YAML
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-controlplane
spec:
  hub: gcr.io/istio-release
  tag: 1.11.2
  meshConfig:
    accessLogFile: /dev/stdout
    rootNamespace: istio-config
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
    enableAutoMtls: true
    defaultConfig:
      extraStatTags:
      - jwt_client_name
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
  components:
    base:
      enabled: true
    cni:
      enabled: true
      namespace: kube-system
    pilot:
      enabled: true
      k8s:
        hpaSpec:
          minReplicas: 3
          maxReplicas: 12
          metrics:
          - resource:
              name: cpu
              targetAverageUtilization: 80
            type: Resource
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: istiod
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
        podDisruptionBudget:
          minAvailable: 2
        strategy:
          rollingUpdate:
            maxSurge: 100%
            maxUnavailable: 25%
    ingressGateways:
    - enabled: true
      k8s:
        env:
        - name: ISTIO_META_ROUTER_MODE
          value: standard
        hpaSpec:
          minReplicas: 3
          maxReplicas: 12
          metrics:
          - resource:
              name: cpu
              targetAverageUtilization: 80
            type: Resource
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: istio-ingressgateway
        service:
          type: NodePort
          ports:
          - name: status-port
            port: 15021
            targetPort: 15021
            nodePort: 31370
          - name: http2
            port: 80
            targetPort: 8080
            nodePort: 31380
          - name: https
            port: 443
            targetPort: 8443
          - name: tls
            port: 15443
            targetPort: 15443
        strategy:
          rollingUpdate:
            maxSurge: 100%
            maxUnavailable: 25%
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 250m
            memory: 128Mi
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - istio-ingressgateway
                topologyKey: kubernetes.io/hostname
              weight: 100
      name: istio-ingressgateway
  values:
    global:
      configRootNamespace: istio-config
      proxy_init:
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 10Mi
      proxy:
        holdApplicationUntilProxyStarts: true
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi
    sidecarInjectorWebhook:
      enableNamespacesByDefault: false
      objectSelector:
        autoInject: true
        enabled: false
      rewriteAppHTTPProbe: true
 ```

I found this issue which describes the same thing and a workaround; delete the istio-cni daemonset and redeploy the operator. That being said, we have hundreds of clusters and doing that in production seems scary :)

https://www.gitmemory.com/issue/istio/istio/34795/903325505

Anyone see this before?
