### ISSUE TITLE
istio operator does not delete service annotations 

### ISSUE THREAD

**Issue by tareqhs** [istio/istio#35213]
### Bug Description

Removing a service annotation from IstioOperator does not remove it from the corresponding Service resource. For example:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  ...
spec:
  components:
    ingressGateways:
    - k8s:
        ...
        serviceAnnotations:
          myannotation: abc
```
The creates the LB service `istio-ingerssgateway` with annotation `myannotation=abc`, as expected. If I later delete the annotation (or even the whole `serviceAnnotations` block) from IstioOperatio spec, the annotation is left as-is in the service resource. After several tries I acknowledged that istio-operator only creates/updates annotations but does not delete them.

We need a method to remove annotations via IstioOperator spec without breaking out to manual resource modifications.

Maybe istio-operator should simply replace the whole annotations block with what's written in IstioOperator spec?

thank you

### Version

```prose
$ istioctl version
client version: 1.9.5
control plane version: 1.9.5

(also reproduced in 1.10.4)
```
