### ISSUE TITLE
Workloads using a PeerAuthentication tls mode of PERMISSIVE only work when the client connects with ISTIO_MUTUAL

### ISSUE THREAD

**Issue by jacob-delgado** [istio/istio#35232]
### Bug Description

Edit: I've noticed this is for a server that is specified as using tcp. Will try with http when I get the opportunity.

Steps to reproduce

1. Apply the following yaml

```yaml
kind: Namespace
apiVersion: v1
metadata:
  name: mysql-server-sidecar-permissive
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql
  namespace: mysql-server-sidecar-permissive
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql-server-sidecar-permissive
  labels:
    app: mysql
spec:
  ports:
  - name: tcp
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mysql-server-sidecar-permissive
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      serviceAccountName: mysql
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: mysql
  namespace: mysql-server-sidecar-permissive
spec:
  selector:
    matchLabels:
      app: mysql
  mtls:
    mode: PERMISSIVE
---
kind: Namespace
apiVersion: v1
metadata:
  name: mysql-client-without-sidecar
  labels:
    istio-injection: disabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql
  namespace: mysql-client-without-sidecar
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql-client-without-sidecar
  labels:
    app: mysql
spec:
  ports:
  - name: tcp
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mysql-client-without-sidecar
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      serviceAccountName: mysql
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
---
kind: Namespace
apiVersion: v1
metadata:
  name: mysql-client-sidecar-dr-disable
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql
  namespace: mysql-client-sidecar-dr-disable
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql-client-sidecar-dr-disable
  labels:
    app: mysql
spec:
  ports:
  - name: tcp
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mysql-client-sidecar-dr-disable
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      serviceAccountName: mysql
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: mysql
  namespace: mysql-client-sidecar-dr-disable
spec:
  host: mysql.mysql-server-sidecar-permissive.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
---
kind: Namespace
apiVersion: v1
metadata:
  name: mysql-client-sidecar-no-dr
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql
  namespace: mysql-client-sidecar-no-dr
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql-client-sidecar-no-dr
  labels:
    app: mysql
spec:
  ports:
  - name: tcp
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mysql-client-sidecar-no-dr
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      serviceAccountName: mysql
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
---
kind: Namespace
apiVersion: v1
metadata:
  name: mysql-client-sidecar-dr-istio-mutual
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql
  namespace: mysql-client-sidecar-dr-istio-mutual
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql-client-sidecar-dr-istio-mutual
  labels:
    app: mysql
spec:
  ports:
  - name: tcp
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mysql-client-sidecar-dr-istio-mutual
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      serviceAccountName: mysql
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: mysql
  namespace: mysql-client-sidecar-dr-istio-mutual
spec:
  host: mysql.mysql-server-sidecar-permissive.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```
1. Attempt to connect a mysql client that does not have a sidecar to a mysql server running with a sidecar with a `PeerAuthentication` TLS mode set to `PERMISSIVE`. This should succeed, but fails.
```bash
$ kubectl exec -it -n mysql-client-without-sidecar $(kubectl get pods -n mysql-client-without-sidecar -l app=mysql -o jsonpath='{.items[0].metadata.name}') -- mysql --host mysql.mysql-server-sidecar-permissive.svc.cluster.local -ppassword
```
1. Attempt to connect a mysql client that has a sidecar, but with a `DestinationRule` set to `DISABLE` TLS, to a mysql server running with a sidecar with a `PeerAuthentication` TLS mode set to `PERMISSIVE` should pass, but fails.
```bash
$ kubectl exec -it -n mysql-client-sidecar-dr-disable $(kubectl get pods -n mysql-client-sidecar-dr-disable -l app=mysql -o jsonpath='{.items[0].metadata.name}') -- mysql --host mysql.mysql-server-sidecar-permissive.svc.cluster.local -ppassword
```

When Istio is installed with the following profile there is also an additional test case where the default profile works, but various settings fail:
1. Install with the following profile
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    enableAutoMtls: false
  values:
    pilot:
      enableProtocolSniffingForInbound: false
      enableProtocolSniffingForOutbound: false
```
1. Attempt to connect a mysql client that has a sidecar, without a `DestinationRule`, to a mysql server running with a sidecar with a `PeerAuthentication` TLS mode set to `PERMISSIVE` should pass, but fails. (Note: this works when using the `default` profile).
```bash
$ kubectl exec -it -n mysql-client-sidecar-no-dr $(kubectl get pods -n mysql-client-sidecar-no-dr -l app=mysql -o jsonpath='{.items[0].metadata.name}') -- mysql --host mysql.mysql-server-sidecar-permissive.svc.cluster.local -ppassword
```

In cases when a mysql client with a sidecar attempts to talk to a mysql server with a sidecar with a `PeerAuthentication` of `PERMISSIVE` and a `DestinationRule` of `ISTIO_MUTUAL` the client is able to connect.
```bash
$ kubectl exec -it -n mysql-client-sidecar-dr-istio-mutual $(kubectl get pods -n mysql-client-sidecar-dr-istio-mutual -l app=mysql -o jsonpath='{.items[0].metadata.name}') -- mysql --host mysql.mysql-server-sidecar-permissive.svc.cluster.local -ppassword
```

### Version

```prose
$ istiocl version
client version: 1.11.2
control plane version: 1.11.2
data plane version: 1.11.2 (5 proxies)

$ kubectl version --short
Client Version: v1.22.1
Server Version: v1.20.7
```

### Additional Information

The above `kubectl` commands were executed on both a default and with the provided profile. I've attached both of the bug reports for each configuration.

[default-profile-bug-report.tar.gz](https://github.com/istio/istio/files/7181319/default-profile-bug-report.tar.gz)
[provided-profile-bug-report.tar.gz](https://github.com/istio/istio/files/7181320/provided-profile-bug-report.tar.gz)
