### ISSUE TITLE
envoy.extensions.filters guide

### ISSUE THREAD

**Issue by yankunsam** [istio/istio#35246]
I want to use postgres proxy by creating a envoyfilter cr, but always falied

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: pg
spec:
  workloadSelector:
    labels:
      app: pg-demo
  configPatches:
  - applyTo: EXTENSION_CONFIG
    match:
      context: ANY
      listener:
        # portNumber: 5432
        name: "10.109.13.116_5432"
    patch:
      operation: ADD
      value:
        name: "envoy.filters.network.postgres_proxy"
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.postgres_proxy.v3alpha.PostgresProxy"
          stat_prefix: postgres
  - applyTo: NETWORK_FILTER
    match:
      context: ANY
      listener:
        filterChain:
          # sni: app.example.com
          filter:
            name: "envoy.filters.network.tcp_proxy"
    patch:
      operation: INSERT_BEFORE
      value:
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: tcp
          cluster: postgres.pg
```

Does Istio support postgres proxy now?

the filter "envoy.filters.network.postgres_proxy" not exist from envoy's config_dump.

And apply to NETWORK_FILTER, the same.
