### ISSUE TITLE
Listeners are not always created when ServiceEntries use TCP protocol and conflict with Services using HTTP protocol

### ISSUE THREAD

**Issue by jacob-delgado** [istio/istio#35242]
### Bug Description

1. Apply samples/sleep/sleep.yaml
2. Apply the following yaml
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-https
spec:
  hosts:
  - istio.io
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http
    protocol: TCP
    targetPort: 80
  resolution: DNS
```
3. From your sleep pod try to curl to istio.io
```bash
$ kubectl exec -it $(kubectl get pods -l app=sleep -o jsonpath='{.items[0].metadata.name}') -- curl istio.io -vvvv
...
< HTTP/1.1 502 Bad Gateway
< date: Fri, 17 Sep 2021 06:12:53 GMT
< server: envoy
< content-length: 0
```
This fails to create a listener for the outbound server.
4. Now apply the following yaml
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-https
spec:
  hosts:
  - istio.io
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
```
5. Curl against istio.io
```bash
$ kubectl exec -it $(kubectl get pods -l app=sleep -o jsonpath='{.items[0].metadata.name}') -- curl istio.io -vvvv
...
< HTTP/1.1 301 Moved Permanently
...
Redirecting to https://istio.io/
```

The issue seems to arise when there is a conflicting service that has already been defined on that port for HTTP protocol.
For instance, if you apply samples/httpbin/httpbin.yaml and use the following yaml it will not work
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-https
spec:
  hosts:
  - istio.io
  location: MESH_EXTERNAL
  ports:
  - number: 8000
    name: http
    protocol: TCP
    targetPort: 80
  resolution: DNS
```
where as
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-https
spec:
  hosts:
  - istio.io
  location: MESH_EXTERNAL
  ports:
  - number: 8000
    name: http
    protocol: HTTP
    targetPort: 80
  resolution: DNS
```
works when using

```bash
$ kubectl exec -it $(kubectl get pods -l app=sleep -o jsonpath='{.items[0].metadata.name}') -- curl istio.io:8000 -vvvv
```

A similar thing happens when the ServiceEntry is declared first and then the httpbin service is created, only this time the httpbin service cannot be reached.

### Version

```prose
$ istioctl version
client version: 1.11.2
control plane version: 1.11.2
data plane version: 1.11.2 (2 proxies)

$ kubectl version --short
Client Version: v1.22.1
Server Version: v1.21.1
```

### Additional Information

[bug-report.tar.gz](https://github.com/istio/istio/files/7183117/bug-report.tar.gz)
