### ISSUE TITLE
istio https use sds error

### ISSUE THREAD

**Issue by liyin37** [istio/istio#35265]
### Bug Description

the same namesapce create two gateway https,but one of it dont visit ,the yaml is below:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: geoscene-micro-service0243-gateway-https
  namespace: gisns-gisuni
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: gisuni-credential
    hosts:
    - geoscene-micro-service0243.gisuni.top


---
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: geoscene-micro-service0243-virtualservice-https
  namespace: gisns-gisuni
spec:
  hosts:
    - geoscene-micro-service0243.gisuni.top
  gateways:
    - geoscene-micro-service0243-gateway-https
  http:
    - route:
        - destination:
            host: geoscene-micro-service0243
            port:
              number: 6080
--- 
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: geoscene-micro-service0244-gateway-https
  namespace: gisns-gisuni
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: gisuni-credential
    hosts:
    - geoscene-micro-service0244.gisuni.top
---
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: geoscene-micro-service0244-virtualservice-https
  namespace: gisns-gisuni
spec:
  hosts:
    - geoscene-micro-service0244.gisuni.top
  gateways:
    - geoscene-micro-service0244-gateway-https
  http:
    - route:
        - destination:
            host: geoscene-micro-service0244
            port:
              number: 6080
```

https://geoscene-micro-service0244.gisuni.top/  error，
![image](https://user-images.githubusercontent.com/42507175/133871183-e8cd6d15-a2ca-4855-8efa-b52e7912ec3f.png)

### Version

```prose
1.10.1
```

### Additional Information

error

**Comment by howardjohn** [comment]
Seems to work for me, can you show `istioctl pc all svc/istio-ingressgateway.istio-system -oyaml`

**Comment by liyin37** [comment]
@howardjohn  the yaml is too long, you can visit here to see 
http://47.109.28.133/istio.yaml

**Comment by howardjohn** [comment]
config looks fine to me, maybe your app returns 404. Would be good to check access logs from envoy

**Comment by liyin37** [comment]
[2021-09-24T09:46:33.978Z] "GET /geoscene/ HTTP/2" 404 NR route_not_found - "-" 0 0 0 - "10.42.5.1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36" "53803c3b-6903-9478-90f8-7f111c88ca0e" "geoscene-micro-service0243.gisuni.top" "-" - - 10.42.5.135:8443 10.42.5.1:22493 geoscene-micro-service0244.gisuni.top -
[2021-09-24T09:46:35.785Z] "GET /geoscene/ HTTP/2" 404 NR route_not_found - "-" 0 0 0 - "10.42.5.1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36" "89e5a22b-3338-9067-b456-fe21ff01438b" "geoscene-micro-service0243.gisuni.top" "-" - - 10.42.5.135:8443 10.42.5.1:22493 geoscene-micro-service0244.gisuni.top -
[2021-09-24T09:46:35.943Z] "GET /geoscene/ HTTP/2" 404 NR route_not_found - "-" 0 0 0 - "10.42.5.1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36" "7845873b-5ad0-9a87-83cb-dff757e81912" "geoscene-micro-service0243.gisuni.top" "-" - - 10.42.5.135:8443 10.42.5.1:22493 geoscene-micro-service0244.gisuni.top -
[2021-09-24T09:46:37.858Z] "GET /geoscene/ HTTP/2" 404 NR route_not_found - "-" 0 0 0 - "10.42.5.1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36" "43be3aef-c30d-977c-b190-04ad2245877d" "geoscene-micro-service0243.gisuni.top" "-" - - 10.42.5.135:8443 10.42.5.1:22493 geoscene-micro-service0244.gisuni.top -
[2021-09-24T09:46:38.019Z] "GET /geoscene/ HTTP/2" 404 NR route_not_found - "-" 0 0 0 - "10.42.5.1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36" "b730484a-2a88-9d48-87f1-5df383b7857a" "geoscene-micro-service0243.gisuni.top" "-" - - 10.42.5.135:8443 10.42.5.1:22493 geoscene-micro-service0244.gisuni.top -
[2021-09-24T09:46:38.173Z] "GET /geoscene/ HTTP/2" 404 NR route_not_found - "-" 0 0 0 - "10.42.5.1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36" "2477827a-80c3-9e8d-8520-adf7148320ed" "geoscene-micro-service0243.gisuni.top" "-" - - 10.42.5.135:8443 10.42.5.1:22493 geoscene-micro-service0244.gisuni.top -

![image](https://user-images.githubusercontent.com/42507175/134654994-4b620b93-9ea2-4862-8272-cecedde958c7.png)
![image](https://user-images.githubusercontent.com/42507175/134655125-770ced9f-c26f-4078-b69b-8c332abf489d.png)

**Comment by howardjohn** [comment]
You have hostname = geoscene-micro-service0243.gisuni.top, SNI
= geoscene-micro-service0244.gisuni.top... maybe
https://istio.io/latest/docs/ops/common-problems/network-issues/#404-errors-occur-when-multiple-gateways-configured-with-same-tls-certificate
?

**Comment by liyin37** [comment]
@howardjohn solved it use below yaml :
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: geoscene-micro-service-gateway-https
  namespace: gisns-gisuni
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: gisuni-credential
    hosts:
    - '*.gisuni.top'


---
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: geoscene-micro-service0243-virtualservice-https
  namespace: gisns-gisuni
spec:
  hosts:
    - geoscene-micro-service0243.gisuni.top
  gateways:
    - geoscene-micro-service-gateway-https
  http:
    - route:
        - destination:
            host: geoscene-micro-service0243
            port:
              number: 6080
---
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: geoscene-micro-service0244-virtualservice-https
  namespace: gisns-gisuni
spec:
  hosts:
    - geoscene-micro-service0244.gisuni.top
  gateways:
    - geoscene-micro-service-gateway-https
  http:
    - route:
        - destination:
            host: geoscene-micro-service0244
            port:
              number: 6080
```
