### ISSUE TITLE
Istio sidecar injection running despite having annotation not to

### ISSUE THREAD

**Issue by Stono** [istio/istio#35271]
### Bug Description

Hi, 
We had a situation today where by change istiod _and_ one on our own mutatingwebhook controllers went down at the same time.  This landed us in a situation where neither could start because both had a failedPolicy: Fail.

This never used to be an issue, because the pods in our workload have the `sidecar.istio.io/inject=false` annotation (eg they should not be blocked on startup by istio)

```
13m         Warning   FailedCreate                   replicaset/kubitzer-698b79c87f                Error creating: Internal error occurred: failed calling webhook "auto.sidecar-injector.istio.io": Post "https://istiod.istio-system.svc:443/inject?timeout=10s": EOF
13m         Warning   FailedCreate                   replicaset/kubitzer-698b79c87f                Error creating: Internal error occurred: failed calling webhook "auto.sidecar-injector.istio.io": Post "https://istiod.istio-system.svc:443/inject?timeout=10s": context deadline exceeded
7m34s       Warning   FailedCreate                   replicaset/kubitzer-698b79c87f                Error creating: Internal error occurred: failed calling webhook "auto.sidecar-injector.istio.io": Post "https://istiod.istio-system.svc:443/inject?timeout=10s": no endpoints available for service "istiod"
```

Looking at the configuration for that particular handler (`auto.sidecar-injector.istio.io`), I see:
```
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: auto.sidecar-injector.istio.io
  namespaceSelector:
    matchExpressions:
    - key: istio-injection
      operator: DoesNotExist
    - key: istio.io/rev
      operator: DoesNotExist
  objectSelector:
    matchExpressions:
    - key: sidecar.istio.io/inject
      operator: DoesNotExist
    - key: istio.io/rev
      operator: DoesNotExist
```

But shouldn't that objectSelector be:
```
  objectSelector:
    matchExpressions:
    - key: sidecar.istio.io/inject
      operator: NotIn
      values:
      - "false"
```

like all of the others?

### Version

```prose
control plane version: 1.10.2
```

**Comment by howardjohn** [comment]
Object selectors only apply to labels, not annotation. So if you have that as a label it should work. We are trying to push for users to use the label since it's strictly better.

**Comment by Stono** [comment]
OK so just to be clear we shouldn't be using `metadata.annotations.sidecar.istio.io/inject: "false"` any more and instead use a label?  When did that change happen?

It's still not clear to me how that selector works though...

```
  objectSelector:
    matchExpressions:
    - key: sidecar.istio.io/inject
      operator: DoesNotExist
```

It doesn't have any true/false assertion, just the presence of the label?  So shouldn't it be:

```
  objectSelector:
    matchExpressions:
    - key: sidecar.istio.io/inject
      operator: NotIn
      values:
      - "false"
```
