### ISSUE TITLE
Concern over leaking sensitive information in headers X-Envoy-Peer-Metadata and X-Envoy-Peer-Metadata-Id

### ISSUE THREAD

**Issue by lei-tang** [istio/istio#35283]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
https://discuss.istio.io/t/istio-leaks-sensitive-information-in-http-headers/11263 describes a concern over leaking sensitive information in http headers X-Envoy-Peer-Metadata and X-Envoy-Peer-Metadata-Id. This issue is created to discuss such concern.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[X ] Extensions and Telemetry
[X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by lei-tang** [comment]
https://github.com/istio/proxy/blob/e02cbbe2e3f390afd9711c5d5e9f4bb5462059ea/test/envoye2e/http_metadata_exchange/exchange_test.go#L77 refers to x-envoy-peer-metadata and x-envoy-peer-metadata-id. 

@kyessenov Can you take a look of this issue?

**Comment by bianpengyuan** [comment]
Better consolidate discussion at https://github.com/istio/istio/issues/17635 which has bunch of history and work arounds.

**Comment by lei-tang** [comment]
Thanks! Based on the comment, this issue was consolidated at #17635.

**Comment by mandarjog** [comment]
@bianpengyuan I suggest that we use this issue to decide on MX, and the other issue to decide on non-mx.

Since we encode and send all labels it can contain information that was unexpected by the app owner. 
Ex: @bianpengyuan can you confirm that it is `all labels`, and not labels from an allow list?

```yaml
        ISTIO_VERSION: 1.9.8-asm.1
        LABELS:
          app: customers
          app.kubernetes.io/managed-by: skaffold
          istio.io/rev: asm-198-1
          managed-by: spinnaker
          pod-template-hash: 59b964bb56
          security.istio.io/tlsMode: istio
          service.istio.io/canonical-name: customers
          service.istio.io/canonical-revision: v1
          skaffold.dev/run-id: f79d8d2e-7dac-404a-8d94-6fd57ce28369
          topology.istio.io/network: customer-serverless-default
          version: v1
        MESH_ID: proj-xxxxxxxx
        NAME: customers-XXXX-ffgc4
```
@douglas-reid 
@bianpengyuan @kyessenov @lambdai by default, we should write out MX-headers if the established connection is mtls. We do need to give an option to always write to preserve the existing behaviour for non-mtls cases.
