### ISSUE TITLE
Unable to forward to external service via captureMode:NONE in v1.11

### ISSUE THREAD

**Issue by jbotelho2-bb** [istio/istio#35314]
### Bug Description

I'm attempting to setup forwarding of TCP traffic from a local port (e.g. 127.0.0.1:8080) to an external service using a Sidecar config with an egress rule, setup with `captureMode: NONE`, along with a ServiceEntry for the service. This is basically following the 4th example on the [Sidecar docs](https://istio.io/latest/docs/reference/config/networking/sidecar/), where `127.0.0.1:3306` is forwarded to an external MySQL server.

In an attempt to make this as easy to reproduce as possible, I setup a fresh kind cluster, installed istio with the "demo" configuration, and deployed the "helloworld" service to start. I then found a service exposed online on a high port to test with, and used that for this example:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
    service: helloworld
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: helloworld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-v1
  labels:
    app: helloworld
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      version: v1
  template:
    metadata:
      labels:
        app: helloworld
        version: v1
    spec:
      containers:
      - name: helloworld
        image: docker.io/istio/examples-helloworld-v1
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
---
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: default
  namespace: default
spec:
  egress:
  - bind: 127.0.0.1
    captureMode: NONE
    port:
      number: 8080
      protocol: TCP
      name: web
    hosts:
    - "./www.asnt.org"
  - captureMode: IPTABLES
    hosts:
    - "*/*"
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-svc
  namespace: default
spec:
  resolution: DNS
  hosts:
  - www.asnt.org
  addresses:
  - 127.0.0.1
  exportTo: [.]
  location: MESH_EXTERNAL
  ports:
  - number: 8080
    name: web
    protocol: TCP
```

On Istio v1.11.2, attempting to contact this service results in "Empty reply" error from curl:
```
$ kubectl exec helloworld-v1-776f57d5f6-dc4l5 -- curl http://127.0.0.1:8080
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (52) Empty reply from server
command terminated with exit code 52
```

However, after uninstalling Istio v1.11.2, then reinstalling with Istio v1.10.4 and replacing the pod, it works fine:
```
$ kubectl exec helloworld-v1-776f57d5f6-6d62j -- curl http://127.0.0.1:8080
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   300  100   300    0     0   4541      0 --:--:-- --:--:-- --:--:--  4615
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
<title>ASNT</title>
<meta http-equiv="REFRESH" content="0;url=http://www.asnt.org"></HEAD>
<BODY>
<p>ASNT Has re-arranged, we're re-directing you, hopefully, to the page you were looking for.</p>
</BODY>
</HTML>
```

I double-checked that reinstalling back to v1.11.2 breaks things with no change in config. It appears this is a regression of some sort, or maybe a breaking change that wasn't documented.

Digging a little deeper, the main difference on Istio v1.11.2 seems to be that it does not create a cluster for this service. This results in a "Cluster not found" error in the istio-proxy logs when attempting to hit 127.0.0.1:8080:

```
2021-09-22T14:37:19.567965Z	debug	envoy filter	[C1201] new tcp proxy session
2021-09-22T14:37:19.568008Z	debug	envoy filter	[C1201] Cluster not found outbound|8080||www.asnt.org
2021-09-22T14:37:19.568021Z	debug	envoy connection	[C1201] closing data_to_write=0 type=1
2021-09-22T14:37:19.568034Z	debug	envoy connection	[C1201] closing socket: 1
```

### Version

```prose
$ istioctl version
client version: 1.11.2
control plane version: 1.11.2
data plane version: 1.11.2 (3 proxies)

$ kubectl version --short
Client Version: v1.21.3
Server Version: v1.21.1
```

### Additional Information

Target cluster context: kind-kind

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-system, kube-public, kube-node-lease, local-path-storage } AND { Namespaces: kube-system, kube-public, kube-node-lease, local-path-storage }
end-time: 2021-09-22 09:49:47.301017 -0400 EDT

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.11.2", GitRevision:"96710172e1e47cee227e7e8dd591a318fdfe0326", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.11.2"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.11.2}

Fetching proxy logs for the following containers:

default/helloworld-v1/helloworld-v1-776f57d5f6-b4djm/helloworld
default/helloworld-v1/helloworld-v1-776f57d5f6-b4djm/istio-proxy
istio-system/istio-egressgateway/istio-egressgateway-6cb7bdc7fb-bzbj5/istio-proxy
istio-system/istio-ingressgateway/istio-ingressgateway-694d8d7656-rdf9g/istio-proxy
istio-system/istiod/istiod-6c68579c55-qwlw4/discovery

Fetching Istio control plane information from cluster.

The following fetches are still running: 
  kubectl get --all-namespaces all,jobs,ingresses,endpoints,customresourcedefinitions,configmaps,events -o yaml
  kubectl get --all-namespaces authorizationpolicies.security.istio.io,destinationrules.networking.istio.io,envoyfilters.networking.istio.io,gateways.networking.istio.io,istiooperators.install.istio.io,peerauthentications.security.istio.io,requestauthentications.security.istio.io,serviceentries.networking.istio.io,sidecars.networking.istio.io,telemetries.telemetry.istio.io,virtualservices.networking.istio.io,workloadentries.networking.istio.io,workloadgroups.networking.istio.io -o yaml

The following fetches are still running: 
  kubectl get --all-namespaces all,jobs,ingresses,endpoints,customresourcedefinitions,configmaps,events -o yaml
  kubectl get --all-namespaces authorizationpolicies.security.istio.io,destinationrules.networking.istio.io,envoyfilters.networking.istio.io,gateways.networking.istio.io,istiooperators.install.istio.io,peerauthentications.security.istio.io,requestauthentications.security.istio.io,serviceentries.networking.istio.io,sidecars.networking.istio.io,telemetries.telemetry.istio.io,virtualservices.networking.istio.io,workloadentries.networking.istio.io,workloadgroups.networking.istio.io -o yaml

The following fetches are still running: 
  kubectl get --all-namespaces all,jobs,ingresses,endpoints,customresourcedefinitions,configmaps,events -o yaml
  kubectl get --all-namespaces authorizationpolicies.security.istio.io,destinationrules.networking.istio.io,envoyfilters.networking.istio.io,gateways.networking.istio.io,istiooperators.install.istio.io,peerauthentications.security.istio.io,requestauthentications.security.istio.io,serviceentries.networking.istio.io,sidecars.networking.istio.io,telemetries.telemetry.istio.io,virtualservices.networking.istio.io,workloadentries.networking.istio.io,workloadgroups.networking.istio.io -o yaml

The following fetches are still running: 
  kubectl get --all-namespaces authorizationpolicies.security.istio.io,destinationrules.networking.istio.io,envoyfilters.networking.istio.io,gateways.networking.istio.io,istiooperators.install.istio.io,peerauthentications.security.istio.io,requestauthentications.security.istio.io,serviceentries.networking.istio.io,sidecars.networking.istio.io,telemetries.telemetry.istio.io,virtualservices.networking.istio.io,workloadentries.networking.istio.io,workloadgroups.networking.istio.io -o yaml
  kubectl get --all-namespaces all,jobs,ingresses,endpoints,customresourcedefinitions,configmaps,events -o yaml

The following fetches are still running: 
  kubectl get --all-namespaces authorizationpolicies.security.istio.io,destinationrules.networking.istio.io,envoyfilters.networking.istio.io,gateways.networking.istio.io,istiooperators.install.istio.io,peerauthentications.security.istio.io,requestauthentications.security.istio.io,serviceentries.networking.istio.io,sidecars.networking.istio.io,telemetries.telemetry.istio.io,virtualservices.networking.istio.io,workloadentries.networking.istio.io,workloadgroups.networking.istio.io -o yaml
  kubectl get --all-namespaces all,jobs,ingresses,endpoints,customresourcedefinitions,configmaps,events -o yaml

The following fetches are still running: 
  kubectl get --all-namespaces authorizationpolicies.security.istio.io,destinationrules.networking.istio.io,envoyfilters.networking.istio.io,gateways.networking.istio.io,istiooperators.install.istio.io,peerauthentications.security.istio.io,requestauthentications.security.istio.io,serviceentries.networking.istio.io,sidecars.networking.istio.io,telemetries.telemetry.istio.io,virtualservices.networking.istio.io,workloadentries.networking.istio.io,workloadgroups.networking.istio.io -o yaml
  kubectl get --all-namespaces all,jobs,ingresses,endpoints,customresourcedefinitions,configmaps,events -o yaml

The following fetches are still running: 
  kubectl get --all-namespaces authorizationpolicies.security.istio.io,destinationrules.networking.istio.io,envoyfilters.networking.istio.io,gateways.networking.istio.io,istiooperators.install.istio.io,peerauthentications.security.istio.io,requestauthentications.security.istio.io,serviceentries.networking.istio.io,sidecars.networking.istio.io,telemetries.telemetry.istio.io,virtualservices.networking.istio.io,workloadentries.networking.istio.io,workloadgroups.networking.istio.io -o yaml

The following fetches are still running: 
  kubectl get --all-namespaces authorizationpolicies.security.istio.io,destinationrules.networking.istio.io,envoyfilters.networking.istio.io,gateways.networking.istio.io,istiooperators.install.istio.io,peerauthentications.security.istio.io,requestauthentications.security.istio.io,serviceentries.networking.istio.io,sidecars.networking.istio.io,telemetries.telemetry.istio.io,virtualservices.networking.istio.io,workloadentries.networking.istio.io,workloadgroups.networking.istio.io -o yaml

The following fetches are still running: 
  kubectl get --all-namespaces authorizationpolicies.security.istio.io,destinationrules.networking.istio.io,envoyfilters.networking.istio.io,gateways.networking.istio.io,istiooperators.install.istio.io,peerauthentications.security.istio.io,requestauthentications.security.istio.io,serviceentries.networking.istio.io,sidecars.networking.istio.io,telemetries.telemetry.istio.io,virtualservices.networking.istio.io,workloadentries.networking.istio.io,workloadgroups.networking.istio.io -o yaml

The following fetches are still running: 
  kubectl get --all-namespaces authorizationpolicies.security.istio.io,destinationrules.networking.istio.io,envoyfilters.networking.istio.io,gateways.networking.istio.io,istiooperators.install.istio.io,peerauthentications.security.istio.io,requestauthentications.security.istio.io,serviceentries.networking.istio.io,sidecars.networking.istio.io,telemetries.telemetry.istio.io,virtualservices.networking.istio.io,workloadentries.networking.istio.io,workloadgroups.networking.istio.io -o yaml

Running istio analyze on all namespaces and report as below:
Analysis Report:
Warning [IST0134] (ServiceEntry external-svc.default) ServiceEntry addresses are required for this protocol.
Info [IST0102] (Namespace istio-system) The namespace is not enabled for Istio injection. Run 'kubectl label namespace istio-system istio-injection=enabled' to enable it, or 'kubectl label namespace istio-system istio-injection=disabled' to explicitly mark it as not needing injection.
Creating an archive at /Users/jbotelho2/src/istio-stacker/bug-report.tar.gz.
Cleaning up temporary files in /var/folders/km/pm4z02s96qv3jjypt2gnc5v40000gr/T/bug-report.
Done.

[bug-report.tar.gz](https://github.com/istio/istio/files/7211665/bug-report.tar.gz)
