### ISSUE TITLE
istio cannot attach static public ip to existing load balancer

### ISSUE THREAD

**Issue by KursLabIgor** [istio/istio#35328]
### Bug Description

istio cannot consume static ip provisioned in another resource group.  

I followed instruction here https://docs.microsoft.com/en-us/azure/aks/static-ip#use-a-static-ip-address-outside-of-the-node-resource-group
ingress-gateway.yaml
```
serviceAnnotations:
      service.beta.kubernetes.io/azure-dns-label-name: myDns
      service.beta.kubernetes.io/azure-load-balancer-resource-group: ResourceGroupOfIp
    loadBalancerIP: ExactIP
```

Motivation : We need to preserve static ip for loadbalancer created by kubernetes outside kubernetes resource group. If we re-deploy cluster we need to have same ip.

### Version

```prose
istio 1.10.2 helm chart used

kubectl version --short
Client Version: v1.20.8
Server Version: v1.20.9

helm version --short
v3.5.4+g1b5edb6
```

### Additional Information

Helm instal failed by timeout with error 

Error syncing load balancer: failed to ensure load balancer: instance not found
