### ISSUE TITLE
How to assign Multiple label to vm?

### ISSUE THREAD

**Issue by cfanbo** [istio/istio#35323]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
assign multiple label to vm

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[x] Virtual Machine
[ ] Multi Control Plane

**Additional context**

docs: https://istio.io/latest/docs/setup/install/virtual-machine/

Automatic generation configure file

cluster.env
```
CANONICAL_REVISION='latest'
CANONICAL_SERVICE='vm1app1'
ISTIO_INBOUND_PORTS='*'
ISTIO_LOCAL_EXCLUDE_PORTS='15090,15021,15020'
ISTIO_METAJSON_LABELS='{"app":"vm1app1","service.istio.io/canonical-name":"vm1app1","service.istio.io/canonical-version":"latest"}'
ISTIO_META_AUTO_REGISTER_GROUP='vm1app1'
ISTIO_META_CLUSTER_ID='Kubernetes'
ISTIO_META_DNS_CAPTURE='true'
ISTIO_META_MESH_ID=''
ISTIO_META_NETWORK=''
ISTIO_META_WORKLOAD_NAME='vm1app1'
ISTIO_NAMESPACE='vm1'
ISTIO_SERVICE='vm1app1.vm1'
ISTIO_SERVICE_CIDR='*'
POD_NAMESPACE='vm1'
SERVICE_ACCOUNT='vm1-sa'
TRUST_DOMAIN='cluster.local'
```

mesh.yaml
```
defaultConfig:
  discoveryAddress: istiod.istio-system.svc:15012
  envoyAccessLogService:
    address: skywalking-oap.istio-system:11800
  proxyMetadata:
    CANONICAL_REVISION: latest
    CANONICAL_SERVICE: vm1app1
    ISTIO_META_AUTO_REGISTER_GROUP: vm1app1
    ISTIO_META_CLUSTER_ID: Kubernetes
    ISTIO_META_DNS_CAPTURE: "true"
    ISTIO_META_MESH_ID: ""
    ISTIO_META_NETWORK: ""
    ISTIO_META_WORKLOAD_NAME: vm1app1
    ISTIO_METAJSON_LABELS: '{"app":"vm1app1","service.istio.io/canonical-name":"vm1app1","service.istio.io/canonical-version":"latest"}'
    POD_NAMESPACE: vm1
    SERVICE_ACCOUNT: vm1-sa
    TRUST_DOMAIN: cluster.local
  tracing:
    zipkin:
      address: zipkin.istio-system:9411

```
