### ISSUE TITLE
Q&A: How to achieve mtls with pods outside of the mesh

### ISSUE THREAD

**Issue by DekelMalul** [istio/istio#35324]
Hey, 

I have setup which includes my application (with istio sidecars) and Strimzi Kafka (not effected by istio at all).

My issue is regards achieving mtls between pods that reside outside of the mesh. 

What is the correct steps inorder to achieve mtls between the pods inside the mesh and outside of the mesh that leverage istio self sign certificate?

I used the follow serviceEntry in order to add the the kafka cluster into the mesh. 

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: kafka-bootstrap-tls
spec:
  hosts:
  - ptc-kafka-bootstrap.dev.svc.cluster.local
  - ptc-kafka-bootstrap
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
  location: MESH_INTERNAL
  ```
