### ISSUE TITLE
Lua EnvoyFilter `httpCall()` seemingly ignores client cert forwarding config

### ISSUE THREAD

**Issue by bleggett** [istio/istio#35338]
### Bug Description

In Pod A

- Lua EnvoyFilter that intercepts Pod A outbound requests, and makes a `httpCall()` to a cluster pointing to a K8S service Service B

Service B
- Has a NETWORK_FILTER EnvoyFilter set up that enables client cert forwarding:
```
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: ANY
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager"
          forward_client_cert_details: SANITIZE_SET
          set_current_client_cert_details:
            subject: true
            cert: true
            uri: true
```

This works great when I make a HTTP request to Service B from a regular container in Pod A - in Service B, I get the `X-Forwarded-Client-Cert` header, with Pod A's client cert, as I expect.

However, if I call Service B from the _Lua EnvoyFilter_ in Pod A - the requests comes to Service B _with no `X-Forwarded-Client-Cert` header_ - the only difference seems to be that I'm making a request from a different container in the same Pod (my workload container vs the Istio proxy container).

This doesn't make a lot of sense to me - I might be missing something, and my understanding of Envoy is incomplete - but why would a Lua filter `httpCall()` to another mesh endpoint lack this header, but a call made from another container in the same pod would have it?

My first thought was that the Lua filter outgoing HTTP request is bypassing the connection manager somehow - but that doesn't make a lot of sense to me, as the client-cert-forwarding config is a listener on the target service, not the source service, and presumably the Lua `httpCall()` request is being routed to that endpoint in the same way as any other request.

### Version

```prose
client version: 1.9.7
control plane version: 1.9.7
data plane version: 1.9.7 (15 proxies)
```
