### ISSUE TITLE
IngressGateway with duplicate targetPorts gives the error 'Duplicate entries for key'

### ISSUE THREAD

**Issue by samirmajen** [istio/istio#35349]
### Bug Description

I am trying to implement an ingressgateway in EKS with 2 ports, 80 and 443 where TLS termination occurs at the AWS load balancer. Both ports should forward traffic to the pod on the same port (8080). Given the following (truncated)  ingressGateway definition:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
spec:
  components:
    ingressGateways:
      - name: ingressgateway
        k8s:
          service:
            ports:
              - port: 80
                targetPort: 8080
                name: http2
              - port: 443
                name: https
                targetPort: 8080
```

I get the error:

`
- Processing resources for Ingress gateways.
✘ Ingress gateways encountered an error: failed to update resource with server-side apply for obj Deployment/istio-system/istio-ingressgateway: failed to create typed patch object: errors:
.spec.template.spec.containers[name="istio-proxy"].ports: duplicate entries for key [containerPort=8080,protocol="TCP"]
`

This has been raised and fixed before https://github.com/kubernetes/kubernetes/issues/53526 

### Version

```prose
istioctl version

client version: 1.9.1
control plane version: 1.9.1
data plane version: 1.9.1

kubectl version --short
Client Version: v1.18.0
Server Version: v1.18.20-eks-8c579e
```
