### ISSUE TITLE
AWS NLB's health check fails if nodeports are updated

### ISSUE THREAD

**Issue by psibi** [istio/istio#35348]
### Bug Description

As the issue title explains, if I update the ingress gateway's node
port, then it results in my network load balancer health check failure.

Steps to reproduce:

1. Install istio using the istio operator
2. Apply this manifest and wait till the ingress is up

<details>
<summary>
Click to Expand manifest
 </summary>
 
 ```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiocontrolplane
  namespace: istio-system
spec:
  components:
    egressGateways:
    - enabled: true
      k8s:
        hpaSpec:
          maxReplicas: 5
          minReplicas: 2
      name: istio-egressgateway
    ingressGateways:
    - enabled: true
      k8s:
        hpaSpec:
          maxReplicas: 5
          minReplicas: 2
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
          service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "600"
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
      name: istio-ingressgateway
    pilot:
      enabled: true
  hub: gcr.io/istio-release
  meshConfig:
    defaultConfig:
      tracing:
        zipkin: null
    enablePrometheusMerge: true
  profile: default
  values:
    global:
      proxy:
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
```
</details>

3. Wait till the network load balancer and the pods are up. Now update
   the above manifest like this to change the node port:

<details>
<summary>Click to expand manifest </summary>

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiocontrolplane
  namespace: istio-system
spec:
  components:
    egressGateways:
    - enabled: true
      k8s:
        hpaSpec:
          maxReplicas: 5
          minReplicas: 2
      name: istio-egressgateway
    ingressGateways:
    - enabled: true
      k8s:
        hpaSpec:
          maxReplicas: 5
          minReplicas: 2
        service:
          ports:
          - name: status-port
            nodePort: 30644
            port: 15021
          - name: http2
            nodePort: 32085
            port: 80
          - name: https
            nodePort: 32082
            port: 443
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
          service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "600"
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
      name: istio-ingressgateway
    pilot:
      enabled: true
  hub: gcr.io/istio-release
  meshConfig:
    defaultConfig:
      tracing:
        zipkin: null
    enablePrometheusMerge: true
  profile: default
  values:
    global:
      proxy:
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
```
</details>

4. Now go and observe the health of your NLB load balancer  and it will fail for both the https and http port. Snapshot:

![unhealth_snap](https://user-images.githubusercontent.com/737477/134649736-81394b98-b65f-440d-9c0f-0b7e0b89c376.png)

Surprisingly for the `status-port`, the health checks are fine.

Note that if I change the node port of my Nginx controllers (backed by NLB) - they do work fine.

There is also a similar looking issue opened previously but which has been closed stating that it should be fixed in 1.8+ : https://github.com/istio/istio/issues/28856

### Version

```prose
❯ istioctl version
client version: 1.10.3
control plane version: 1.10.3
data plane version: 1.10.3 (7 proxies)
❯ kubectl version --short
Client Version: v1.19.0
Server Version: v1.19.13-eks-8df270
```
