### ISSUE TITLE
configuring rate limit for the API does not take effect

### ISSUE THREAD

**Issue by xichengliudui** [istio/istio#35345]
### Bug Description

multiple access to the `/ip` will not return 429
i did not deploy the redis and  ratelimit

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-local-ratelimit-svc-httpbin
  namespace: boook
spec:
  workloadSelector:
    labels:
      app: httpbin
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter
              token_bucket:
                max_tokens: 10
                tokens_per_fill: 10
                fill_interval: 60s
              descriptors:
                - entries:
                  - key: "PATH"
                    value: "/ip"
                  token_bucket:
                    max_tokens: 1
                    tokens_per_fill: 1
                    fill_interval: 120s
              filter_enabled:
                runtime_key: local_rate_limit_enabled
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              filter_enforced:
                runtime_key: local_rate_limit_enforced
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              response_headers_to_add:
                - append: false
                  header:
                    key: cbcccbbb
                    value: 'true'
```
```text
/ $ curl -I http://httpbin.boook:8000/ip
HTTP/1.1 200 OK
server: envoy
date: Sun, 26 Sep 2021 09:24:07 GMT
content-type: application/json
content-length: 28
access-control-allow-origin: *
access-control-allow-credentials: true
x-envoy-upstream-service-time: 3

/ $ curl -I http://httpbin.boook:8000/ip
HTTP/1.1 200 OK
server: envoy
date: Sun, 26 Sep 2021 09:24:07 GMT
content-type: application/json
content-length: 28
access-control-allow-origin: *
access-control-allow-credentials: true
x-envoy-upstream-service-time: 9
```
ratelimit image: `envoyproxy/ratelimit:40393342`

### Version

```prose
# ~/istio-1.11.1/bin/istioctl version
client version: 1.11.1
control plane version: 1.10.0
data plane version: 1.10.0 (9 proxies)
```

### Additional Information

NONE

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by xichengliudui** [comment]
the details of the configuration
```yaml
    filters:
    - name: envoy.filters.network.http_connection_manager
      typedConfig:
        '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
        accessLog:
        - name: envoy.access_loggers.file
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
            logFormat:
              textFormat: |
                [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% "%UPSTREAM_TRANSPORT_FAILURE_REASON%" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%
            path: /dev/stdout
        httpFilters:
        - name: envoy.filters.http.ratelimit
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
            domain: productpage-ratelimit
            failureModeDeny: true
            rateLimitService:
              grpcService:
                envoyGrpc:
                  clusterName: rate_limit_cluster
                timeout: 10s
              transportApiVersion: V3
        - name: envoy.filters.http.router
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
```

**Comment by pangsq** [comment]
do you config the `rate limit actions` according to https://istio.io/latest/docs/tasks/policy-enforcement/rate-limit/ ?

**Comment by xichengliudui** [comment]
> do you config the `rate limit actions` according to https://istio.io/latest/docs/tasks/policy-enforcement/rate-limit/ ?

thank you for your reply. 
i updated the description of the issue. please have a look again

**Comment by xichengliudui** [comment]
more than ten requests can return http code 429
```text
/ $ curl -I http://httpbin.boook:8000/ip
HTTP/1.1 429 Too Many Requests
cbcccbbb: true
content-length: 18
content-type: text/plain
date: Sun, 26 Sep 2021 09:27:45 GMT
server: envoy
x-envoy-upstream-service-time: 1
``` 
proxy config listener
```yaml
[root@10-20-11-81 bookinfo]# istioctl pc listener httpbin-66cdbdb6c5-zjfwq.boook -oyaml | grep -5 /ip
            typeUrl: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              descriptors:
              - entries:
                - key: PATH
                  value: /ip
                token_bucket:
                  fill_interval: 120s
                  max_tokens: 1
                  tokens_per_fill: 1
```
i don't know what went wrong, and I want to fix it.

**Comment by pangsq** [comment]
@xichengliudui The `rateLimits.actions` is also needed to define the descriptors so that envoy can understand what `PATH` means. You can add a configPatch in that EnvoyFilter.

```yml
  - applyTo: HTTP_ROUTE
    match:
      context: SIDECAR_INBOUND
      routeConfiguration:
        vhost:
          route:
            action: ROUTE
    patch:
      operation: MERGE
      value:
        route:
          rateLimits:
          - actions:
            - requestHeaders:
                descriptorKey: PATH
                headerName: :path
```

**Comment by xichengliudui** [comment]
@pangsq thanks, i'm going to try it now.

**Comment by xichengliudui** [comment]
Thank you very much. Now Ratelimit is working fine

**Comment by xichengliudui** [comment]
The `requestHeaders` name felt a bit strange and made me ignore it...
Why not `requesPath`

**Comment by pangsq** [comment]
> The `requestHeaders` name felt a bit strange and made me ignore it...
> Why not `requesPath`

Besides `:path`, there are some other special headers that can be used in `requestHeaders`, like `:method`,`:authority`,`:scheme`,`host`. All the attributes can be represented as headers, so maybe no need to add a `requestPath` or other configs.

**Comment by xichengliudui** [comment]
@pangsq do you know how to configure rateLimits.actions `source_cluster`?

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-local-ratelimit-svc-details
  namespace: boook
spec:
  workloadSelector:
    labels:
      app: details
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter
              status:
                code: 431
              token_bucket:
                max_tokens: 15
                tokens_per_fill: 15
                fill_interval: 60s
              descriptors:
                - entries:
                  - key: "source_cluster"
                    value: "sleep.boook.svc.cluster.local"
                  token_bucket:
                    max_tokens: 5
                    tokens_per_fill: 5
                    fill_interval: 120s
              filter_enabled:
                runtime_key: local_rate_limit_enabled
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              filter_enforced:
                runtime_key: local_rate_limit_enforced
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              response_headers_to_add:
                - append: false
                  header:
                    key: cbcccbbb
                    value: 'true'
  - applyTo: HTTP_ROUTE
    match:
      context: SIDECAR_INBOUND
      routeConfiguration:
        vhost:
          route:
            action: ROUTE
    patch:
      operation: MERGE
      value:
        route:
          rateLimits:
          - actions:
            - sourceCluster:
                descriptorKey: source_cluster
```

**Comment by pangsq** [comment]
@xichengliudui  As i know, the `source_cluster` does not mean where the request is from, but represents what `service-cluster` the server instance is.
For example, if you have a deployment called `client`, and a deployment called `server` in namespace `default`, then you config a ratelimit descriptor: `source_cluster: server.default`.   You will find the requests from `client` to `server` is limited. I think the `source_cluster` is not designed for limiting requests from some `origin` cluster. 

Code in `go-control-plane`:
```
// The following descriptor entry is appended to the descriptor:
//
// .. code-block:: cpp
//
//   ("source_cluster", "<local service cluster>")
//
// <local service cluster> is derived from the :option:`--service-cluster` option.
type RateLimit_Action_SourceCluster struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}
```

Code in [envoy](https://github.com/envoyproxy/envoy/blob/v1.19.1/source/common/router/router_ratelimit.cc#L68): ( it is clearly that `source_cluster` is `local_service_cluster`)
```
bool SourceClusterAction::populateDescriptor(RateLimit::DescriptorEntry& descriptor_entry,
                                             const std::string& local_service_cluster,
                                             const Http::RequestHeaderMap&,
                                             const StreamInfo::StreamInfo&) const {
  descriptor_entry = {"source_cluster", local_service_cluster};
  return true;
}
```

**Comment by xichengliudui** [comment]
thank you for your answer.
does rate limit currently have the ability to limit source services?
e.g
```
service A -> service C    // 60 requests per minute
service B -> service C    // 100 requests per minute
```

**Comment by pangsq** [comment]
[user-agent](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#user-agent) or `x-envoy-downstream-service-cluster` can be used to represent which cluster the request is from. 
But istio does not enable `AddUserAgent` in `HttpConnectionManager` , you may config EnvoyFilters for "service A" and "service B" (or one EnvoyFilter in `istio-system` for all workloads).

**Comment by xichengliudui** [comment]
> [user-agent](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#user-agent) or `x-envoy-downstream-service-cluster` can be used to represent which cluster the request is from. But istio does not enable `AddUserAgent` in `HttpConnectionManager` , you may config EnvoyFilters for "service A" and "service B" (or one EnvoyFilter in `istio-system` for all workloads).

@pangsq  我很少接触 envoy，谢谢解答

**Comment by xichengliudui** [comment]
@pangsq 
i used `x-envoy-downstream-service-cluster` to set the rate limit, but the actual effect was different from what I predicted
after I added `x-envoy-downstream-service-cluster`, it not only didn't take effect, but also affected the API rate limit set before
Is there any method to debug?
```yaml
spec:
  workloadSelector:
    labels:
      app_mesh: httpbin
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: SIDECAR_INBOUND
      routeConfiguration:
        vhost:
          route:
            action: ROUTE
    patch:
      operation: MERGE
      value:
        route:
          rateLimits:
          - actions:
            - requestHeaders:
                descriptorKey: CLIENTCLUSTER
                headerName: "x-envoy-downstream-service-cluster"
            - requestHeaders:
                descriptorKey: PATH
                headerName: ":path"
```
```yaml
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.local_ratelimit
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
          value:
            descriptors:
            - entries:
              - key: PATH
                value: /ip
              token_bucket:
                fill_interval: 120s
                max_tokens: 5
                tokens_per_fill: 5
            - entries:
              - key: CLIENTCLUSTER
                value: sleep.test
              token_bucket:
                fill_interval: 120s
                max_tokens: 5
                tokens_per_fill: 5
            ......
            stat_prefix: http_local_rate_limiter
            token_bucket:
              fill_interval: 60s
              max_tokens: 10
              tokens_per_fill: 10
```
