### ISSUE TITLE
remotePilotAddress using host

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#35363]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
```
cat <<EOF > cluster2.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: demo
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: cluster2
      network: network1
      remotePilotAddress: 192.168.229.100
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
  components:
    egressGateways:
    - name: istio-egressgateway
      enabled: true
EOF
```
can not use remotePilotAddress as host name.
I installed skupper in two k8s cluster,can not using ip to connect between clusters

**Describe alternatives you've considered**
can not use remotePilotAddress as host name.
I installed skupper in two k8s cluster,can not using ip to connect between clusters
**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[x ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
