### ISSUE TITLE
Volumes not work for egressGateways in IstioOperator

### ISSUE THREAD

**Issue by zhaoli2333** [istio/istio#35371]
### Bug Description

Add volumes and volumeMounts for egress in IstioOperator:
```
components:
    egressGateways:
      - name: istio-egressgateway
        enabled: true
        label:
          app: istio-egressgateway
        k8s:
          volumes:
            - name: custom-bootstrap-volume
              volumeSource:
                configMap:
                  localObjectReference:
                    name: custom-bootstrap-configmap
          volumeMounts:
            - mountPath: /etc/istio/custom-bootstrap
              name: custom-bootstrap-volume
```

But the Deployment generated by IstioOperator didn't changed.

### Version

```prose
client version: 1.10.2
control plane version: 1.10.2
data plane version: 65536.65536.65536 (1 proxies),  (7 proxies), 1.10.1 (3 proxies), 1.10.2 (12 proxies)
```
