### ISSUE TITLE
Telemetry V2 - cannot override standard istio metrics

### ISSUE THREAD

**Issue by samirmajen** [istio/istio#35395]
### Bug Description

I am trying to overwrite the "source_workload" metric in "request_bytes_bucket" using the following definition (very hard to find clear examples or documentation for this):

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
spec:
  values:
    telemetry:
      v2:
        prometheus:
          configOverride:
            inboundSidecar:
              stat_prefix: istio
              metrics:
                - name: request_bytes_bucket
                  dimensions:
                    source_workload: "test"
```

The envoy filter appears to be applied to the config:

```
{
	"name": "istio.stats",
	"typedConfig": {
		"@type": "type.googleapis.com/udpa.type.v1.TypedStruct",
		"typeUrl": "type.googleapis.com/envoy.extensions.filters.network.wasm.v3.Wasm",
		"value": {
			"config": {
				"configuration": {
					"@type": "type.googleapis.com/google.protobuf.StringValue",
					"value": "{\"metrics\":[{\"dimensions\":{\"source_workload\":\"test\"},\"name\":\"request_bytes_bucket\"}],\"stat_prefix\":\"istio\"}\n"
				},
				"root_id": "stats_inbound",
				"vm_config": {
					"code": {
						"local": {
							"inline_string": "envoy.wasm.stats"
						}
					},
					"runtime": "envoy.wasm.runtime.null",
					"vm_id": "tcp_stats_inbound"
				}
			}
		}
	}
}
```

but no metrrics are affected and there are no errors in the proxy logs.

How do I override the source_workload metric, and better still can i use conditionals or regex in the value to only modify based on certain source_app's ?

### Version

```prose
λ istioctl version
client version: 1.9.1
control plane version: 1.9.1
data plane version: 1.9.1

λ kubectl version --short
Client Version: v1.18.0
Server Version: v1.18.20-eks-8c579e
```

**Comment by bianpengyuan** [comment]
I think you need to drop the `bucket` suffix.

**Comment by samirmajen** [comment]
Is that document somewhere? Haven't eeen any examples where _bucket is defined as a suffix

**Comment by bianpengyuan** [comment]
https://istio.io/latest/docs/reference/config/metrics/ has document about the metric name. The metric name is `request_bytes`. bucket is the suffix added by prometheus.

**Comment by samirmajen** [comment]
Thanks, I'll give that a try. Is there any way of debugging the filter or adding logging to see whether the rule is matching or not? Also do you know if I can use a regex .matches(), conditionals etc?

**Comment by samirmajen** [comment]
unfortunately dropping the bucket suffix had no effect

**Comment by bianpengyuan** [comment]
Should be "'test'". You can turn on proxy debug log to get error messages on why expr evaluation fails.

**Comment by samirmajen** [comment]
thanks @bianpengyuan adding single quotes did indeed work along with dropping the suffix and prefix, here's the final working example for anyone else trying to do something similar:

```
values:
   telemetry:
     enabled: true
     v2:
       enabled: true
       prometheus:
         configOverride:
           inboundSidecar:
             stat_prefix: istio
             metrics:
               - name: request_bytes
                 dimensions:
                  source_workload: "'test'"
```

Now I want to put in a conditional to only override source_workload based on the 'app' label or any other identifying label or attribute that is available, I've tried things like:

`source_workload: "has(labels['app'].value) ? labels['app'].value : 'unknown'"`
`source_workload: "has(downstream_peer.labels['app'].value) ? downstream_peer.labels['app'].value : 'unknown'"`

all result in errors similar to:

`debug envoy wasm expr_evaluate value error: No value with name "labels" found in Activation`
