### ISSUE TITLE
Using ingress Gateway per subdomain with TLS termination doesn't route to correct Service

### ISSUE THREAD

**Issue by TheAsteroid** [istio/istio#35394]
### Bug Description

We're trying to set up subdomain-to-service ingress routing on our cluster, where incoming requests to `a.example.com` route to service `a`, and requests to `b.example.com` route to service `b` in the same namespace. TLS is terminated by the `Gateway`. We're using real domains, I've just replaced them with example.com for privacy reasons.

We can get this working when using a single `Gateway` with a wildcard on `*.example.com`. However we want to handle only specific subdomains in this way, so we've been trying to get this to work with a `Gateway` per subdomain. In both cases we use the default Istio `ingressgateway`.

**Here's the problem when trying this approach:**
- It appears both requests to https://a.example.com and https://b.example.com are being routed to the `Gateway` for `a.exampe.com` when using any browser. This obviously fails for https://b.example.com because that `Gateway` isn't configured to handle that subdomain, and results in a 404.
- Surprisingly HTTPS requests done with `cURL` work just fine (e.g. `curl https://b.example.com -v`).
- Both browser and `cURL` requests use HTTP/2.
- Browser requests done to http://b.example.com correctly redirect to https://b.example.com and then find their way to service `b`.

HTTPS requests from a browser to `b.example.com` are logged as `NR`. I can see that for `b.example.com` the property `%REQ(:AUTHORITY)%` is set correctly, but `%UPSTREAM_HOST%` is empty, and `%REQUESTED_SERVER_NAME%` is set to `a.example.svc.cluster.local` instead of `b.example.svc.cluster.local`. I'm unsure why this is happening. I suspect it has something to do with the TLS termination and SNI hosts.

I'm reporting it as a bug here rather than a question on discuss.istio.io because of the inconsistent behavior between `cURL` and browser requests, which I can't explain. Of course it's possible that I'm just doing something wrong in the configuration.

The simplified example below is the approach with a Gateway per subdomain, which doesn't work properly.
```
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ingress-a-example-com
  namespace: istio-system
spec:
  gateways:
  - ingressgateway-a-example-com
  hosts:
  - a.example.com
  http:
  - match:
    - uri:
        prefix: /
    name: default-routes
    route:
    - destination:
        host: a.example.svc.cluster.local
        port:
          number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ingress-b-example-com
  namespace: istio-system
spec:
  gateways:
  - ingressgateway-b-example-com
  hosts:
  - b.example.com
  http:
  - match:
    - uri:
        prefix: /
    name: default-routes
    route:
    - destination:
        host: b.example.svc.cluster.local
        port:
          number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: ingressgateway-a-example-com
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - a.example.com
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - a.example.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: my-cert
      minProtocolVersion: TLSV1_2
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: ingressgateway-b-example-com
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - b.example.com
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - b.example.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: my-cert
      minProtocolVersion: TLSV1_2
      mode: SIMPLE
```

The example below uses a single Gateway with a subdomain wildcard. This approach works just fine.
```
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ingress-a-example-com
  namespace: istio-system
spec:
  gateways:
  - ingressgateway-example-com
  hosts:
  - a.example.com
  http:
  - match:
    - uri:
        prefix: /
    name: default-routes
    route:
    - destination:
        host: a.example.svc.cluster.local
        port:
          number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ingress-example-com
  namespace: istio-system
spec:
  gateways:
  - ingressgateway-example-com
  hosts:
  - b.example.com
  http:
  - match:
    - uri:
        prefix: /
    name: default-routes
    route:
    - destination:
        host: b.example.svc.cluster.local
        port:
          number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: ingressgateway-example-com
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - *.example.com
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - *.example.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: my-cert
      minProtocolVersion: TLSV1_2
      mode: SIMPLE
```

### Version

```prose
istioctl version
client version: 1.11.2
control plane version: 1.9.2
data plane version: 1.9.2 (10 proxies)

kubectl version --short
Client Version: v1.21.2
Server Version: v1.20.7

helm version --short
v3.6.3+gd506314
```
