### ISSUE TITLE
Global rate limit Failed and filter_chain_not_found ERROR after enable istio-injection and MTLS

### ISSUE THREAD

**Issue by shingshing222** [istio/istio#35398]
### Bug Description

Steps to reproduce the error:

1. Follow the steps of installation of istio and sample application (Bookinfo) https://istio.io/latest/docs/setup/getting-started/

2. Follow the steps of enabling Rate Limits https://istio.io/latest/docs/tasks/policy-enforcement/rate-limit/

3. Access the bookinfo application (/productpage), it returns 200 OK response and check sidecar log of Rate Limits:
istio-proxy [2021-09-28T14:55:10.730Z] "POST /envoy.service.ratelimit.v3.RateLimitService/ShouldRateLimit HTTP/2" 200 - via_upstream - "-" 52 23 2 1 "172.17.0.9" "-" "c67ff961-6386-9e13-86a0-583996663589"

4. Enable MTLS by applying https://istio.io/latest/docs/reference/config/security/peer_authentication/:
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
name: default
namespace: istio-system
spec:
mtls:
mode: STRICT

5. Access the bookinfo application (/productpage) again and it returns 500 error and also filter_chain_not_found error is found in the sidecar log of Rate Limits:
istio-proxy [2021-09-28T14:55:12.134Z] "- - -" 0 NR filter_chain_not_found - "-" 0 0 0 - "-" "-" "-" "-" "-" - - 172.17.0.8:8081 172.17.0.1:38748 - -

### Version

```prose
istioctl version
Client version: 1.10.2
control plane version: 1.10.2
data plane version: 1.10.2 (10 proxies)

kubectl version --short
Client Version: v1.21.2
Server Version: v1.20.7
```

**Comment by bianpengyuan** [comment]
How do you send request to bookinfo service?

**Comment by shingshing222** [comment]
I sent the request by using the browser visiting http://127.0.0.1/productpage
I think it is nothing to do with bookinfo service. It is just a sample application to allow the request received from istio ingress. 
I guess there should be an issue that envoyfilter sending traffic to another sidecar or receiving traffic from another sidecar when MTLS is enabled at mesh level

**Comment by bianpengyuan** [comment]
Does the request go through an ingress? I think you get `filter_chain_not_found` because all filter chains expects istio mTLS, but request coming in is not encrypted (i.e. not going through an ingressgateway in your case)

**Comment by hschanhkjc** [comment]
Yes, it goes through ingress. One of steps in https://istio.io/latest/docs/setup/getting-started/ is to setup istio ingress gateway and expose the sample application to it.

**Comment by shingshing222** [comment]
Yes, it goes through ingress. One of steps in https://istio.io/latest/docs/setup/getting-started/ is to setup istio ingress gateway and expose the sample application to it.

**Comment by bianpengyuan** [comment]
Oh the log is from rate limit sidecar.. Sorry I misread and thought it was from the bookinfo sidecar. You will need to configure rate limit cluster to use mTLS

**Comment by shingshing222** [comment]
Sorry, I did't understand. Do you mean the envoyfilter mTLS context or rate limit mTLS? and May I know that how to do it?

**Comment by bianpengyuan** [comment]
If you follow the guide, the rate limit cluster added does not have upstream_tls_context, which means it will send plain text to the upstream rate limit service. You can find some examples on what mTLS context look like by `istioctl proxy-config clusters <some-in-mesh-pod> --fqdn <some-mTLS encrypted-service-fqdn> -ojson`.

**Comment by shingshing222** [comment]
Let me try it out. Thanks a lot

**Comment by shingshing222** [comment]
For upstream_tls_context configuration in the caller sidecar (EnvoyFilter), I m able to see some example configuration, but it seems that it may also need downstream_tls_context configuration in the provider sidecar (ratelimit), which I cannot find any example. Could you please help?

**Comment by bianpengyuan** [comment]
It should be configured automatically by istio at rate limit service sidecar.

**Comment by shingshing222** [comment]
With MTLS enabled by Istio and then I added the upstream_tls_context into envoy filter like this

apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-ratelimit
  namespace: istio-system
spec:
  workloadSelector:
    # select by label in the same namespace
    labels:
      istio: ingressgateway
  configPatches:
    # The Envoy config you want to modify
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        # Adds the Envoy Rate Limit Filter in HTTP filter chain.
        value:
          name: envoy.filters.http.ratelimit
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
            # domain can be anything! Match it to the ratelimter service config
            domain: productpage-ratelimit
            failure_mode_deny: true
            timeout: 10s
            rate_limit_service:
              grpc_service:
                envoy_grpc:
                  cluster_name: rate_limit_cluster
              transport_api_version: V3
    - applyTo: CLUSTER
      match:
        cluster:
          service: ratelimit.default.svc.cluster.local
      patch:
        operation: ADD
        # Adds the rate limit service cluster for rate limit service defined in step 1.
        value:
          name: rate_limit_cluster
          type: STRICT_DNS
          connect_timeout: 10s
          lb_policy: ROUND_ROBIN
          http2_protocol_options: {}
          load_assignment:
            cluster_name: rate_limit_cluster
            endpoints:
            - lb_endpoints:
              - endpoint:
                  address:
                     socket_address:
                      address: ratelimit.default.svc.cluster.local
                      port_value: 8081			  
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext


and then access the sample application /productpage, error found in the sidecar log of ratelimit as below
 [2021-10-05T23:04:30.039Z] "- - HTTP/1.1" 400 DPE http1.codec_error - "-" 0 11 0 - "-" "-" "-" "-" "-" - - 172.17.0.12:8081 172.17.0.1:20672 - -  

Could you please advise? Thanks

**Comment by shingshing222** [comment]
@bianpengyuan it seems that the mTLS connection cannot be created with rate limit sidecar and envoyfilter with upstreamtlscontext configuration. Could you please help?

**Comment by sachinsaju** [comment]
@shingshing222 Were you able to successfully ratelimit the service? I also face same errors when mtls is enabled.

**Comment by shingshing222** [comment]
@sachinsaju Actually No, it seems that the sidecar is expected to talk to sidecar only if MTLS is enabled

**Comment by shingshing222** [comment]
@bianpengyuan Can you please help to suggest?

**Comment by sachinsaju** [comment]
@shingshing222 

In case you donot want to enable strict tls with ratelimiting service,You can add following PeerAuthentication in addition to strict authentication.

```
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "ratelimit"
  namespace: "default"
spec:
  selector:
    matchLabels:
      app: ratelimit
  portLevelMtls:
    8081:
      mode: PERMISSIVE

```

You can apply this as a workaround. If you want mtls with rate-limiting-service too, I believe we have to add upstream tlscontext as @bianpengyuan  mentioned.

**Comment by sachinsaju** [comment]
@bianpengyuan Can you please share sample envoy filter config to make mTLS communication with istio ingress gateway and rate-limiting service?

I receive 500 errors in ingressgateway logs since communication between ingress and ratelimiting pod is not successful.(It is only successful when when I make mtls permissive).

**Comment by sachinsaju** [comment]
cc @zirain I tried in different versions of istio and faced this issue. So Is this a limitation of istio? Can you please share what needs to be added in the envoy filter config? I tried adding the upstreamTLSContext config to envoy config but was not successful.

**Comment by zirain** [comment]
@sachinsaju can you try with this demo https://github.com/zirain/limiter/blob/main/pkg/envoyfilter/testdata/global/basic.yaml

**Comment by sachinsaju** [comment]
@zirain  I will try and let you know.

**Comment by sachinsaju** [comment]
@zirain  Have you committed the ratelimit config file? I could not find one.

**Comment by sachinsaju** [comment]
@zirain at https://github.com/zirain/limiter/blob/14bd0a5392160e80c47448f60ac44ce138f6718d/config/rls/rls.yaml

You are specifying sidecar.istio.io/inject: "false" as a label.This means istio sidecar wont be injected to ratelimit pod.
In that case, will mtls work?

**Comment by sachinsaju** [comment]
@zirain It seems to be working even after the istio sidecar was injected to rate limit pod. If my understanding is correct, the specified rate limit envoy filter is applied to httpbin service. In the global rate limit task provided at https://istio.io/latest/docs/tasks/policy-enforcement/rate-limit/  , the envoy filter configuration is applied at ingress gateway. 
Why is the demo configuration not working when mtls is enabled?

If I need to rate limit multiple services, shouldn't I apply a single envoyfilter configuration at Gateway and not create envoy filters for each service?

Thanks

**Comment by zirain** [comment]
> @zirain at https://github.com/zirain/limiter/blob/14bd0a5392160e80c47448f60ac44ce138f6718d/config/rls/rls.yaml
> 
> You are specifying sidecar.istio.io/inject: "false" as a label.This means istio sidecar wont be injected to ratelimit pod. In that case, will mtls work?

actually, in my env, it's still working when ratelimit pod is injected.

> https://istio.io/latest/docs/tasks/policy-enforcement/rate-limit/ , the envoy filter configuration is applied at ingress gateway.
Why is the demo configuration not working when mtls is enabled?

> the envoy filter configuration is applied at ingress gateway. Why is the demo configuration not working when mtls is enabled?

it should be working on ingressgateway, just need a little changes on `Context` and `WorkloadSelector`

> If I need to rate limit multiple services, shouldn't I apply a single envoyfilter configuration at Gateway and not create envoy filters for each service?

both are ok, depends on which request you are trying to enforce the policy.

**Comment by sachinsaju** [comment]
> it should be working on ingressgateway, just need a little changes on Context and WorkloadSelector

@zirain Actually this was what I expected to happen. But it only works when there is no mtls.
For instance, Add the following envoy filters to your cluster.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-ratelimit
  namespace: istio-ingress
spec:
  workloadSelector:
    # select by label in the same namespace
    labels:
      istio: ingress
  configPatches:
    # The Envoy config you want to modify
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        # Adds the Envoy Rate Limit Filter in HTTP filter chain.
        value:
          name: envoy.filters.http.ratelimit
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
            # domain can be anything! Match it to the ratelimter service config
            domain: productpage-ratelimit
            failure_mode_deny: true
            timeout: 10s
            rate_limit_service:
              grpc_service:
                envoy_grpc:
                  cluster_name: rate_limit_cluster
              transport_api_version: V3
    - applyTo: CLUSTER
      match:
        cluster:
          service: ratelimit.default.svc.cluster.local
      patch:
        operation: ADD
        # Adds the rate limit service cluster for rate limit service defined in step 1.
        value:
          name: rate_limit_cluster
          type: STRICT_DNS
          connect_timeout: 10s
          lb_policy: ROUND_ROBIN
          http2_protocol_options: {}
          load_assignment:
            cluster_name: rate_limit_cluster
            endpoints:
            - lb_endpoints:
              - endpoint:
                  address:
                     socket_address:
                      address: ratelimit.default.svc.cluster.local
                      port_value: 8081
                  
---

apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-ratelimit-svc
  namespace: istio-ingress
spec:
  workloadSelector:
    labels:
      istio: ingress
  configPatches:
    - applyTo: VIRTUAL_HOST
      match:
        context: GATEWAY
        routeConfiguration:
          vhost:
            name: ""
            route:
              action: ANY
      patch:
        operation: MERGE
        # Applies the rate limit rules.
        value:
          rate_limits:
            - actions: # any actions in here
              - headerValueMatch:
                  descriptorValue: URL|Prefix|/ip
                  headers:
                    - name: :path
                      stringMatch:
                        prefix: /ip
                        ignoreCase: true
```
This config would work for you if mtls is disabled. But when I turn on mtls STRICT, I get 500 error response.(Make sure to have sidecar injected in ratelimit).
Can you please try above filters and see the behaviour?

Thanks a lot for your previous comments and clarifications.
