### ISSUE TITLE
ServiceEntry has stale endpoints

### ISSUE THREAD

**Issue by yingzhuivy** [istio/istio#35404]
### Bug Description

We have a ServiceEntry in an external Istiod cluster that selects k8s pods in a remote cluster, when the pods are restarted, sometimes there will be stale endpoints in the cluster corresponding to the ServiceEntry. Looking at Istiod's `debug/endpointz`, all of the istiod pods have the same stale states, restarting the Istiod pods fix the problem.

To more easily reproduce, I just scale the deployment to 100 replicas, and then scale down to 1, sometimes some endpoints are not correctly deleted and there will be more than 1 endpoint under the cluster corresponding to the ServiceEntry. It do appear that it's easier to reproduce in more heavy loaded k8s clusters.

Here is the code for reproduction:
In the external Istiod cluster:
```---
apiVersion: v1
kind: Namespace
metadata:
  name: airmesh-test-ying
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: fortioserver
  namespace: airmesh-test-ying
spec:
  addresses:
  - 100.124.99.206
  hosts:
  - fortioserver.airmesh-test-ying.svc.ea1.us.a
  location: MESH_INTERNAL
  ports:
    - name: http-port
      number: 8080
      protocol: HTTP
  resolution: STATIC
  workloadSelector:
    labels:
      app: fortioserver
```

In the remote cluster:
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: airmesh-test-ying
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fortioclient
  name: fortioclient
  namespace: airmesh-test-ying
spec:
  selector:
    matchLabels:
      app: fortioclient
  template:
    metadata:
      labels:
        app: fortioclient
    spec:
      containers:
        - name: fortioclient
          image: docker-artifactory:443/airmesh-fortio:1.9.1-airbnb1
          args:
            - report
          volumeMounts:
            - name: shared-data
              mountPath: /var/lib/fortio
      volumes:
        - name: shared-data
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fortioserver
  name: fortioserver
  namespace: airmesh-test-ying
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortioserver
  template:
    metadata:
      labels:
        app: fortioserver
    spec:
      containers:
        - name: fortioserver
          image: docker-artifactory:443/airmesh-fortio:1.9.1-airbnb1
          volumeMounts:
            - name: shared-data
              mountPath: /var/lib/fortio
      volumes:
        - name: shared-data
          emptyDir: {}
```

### Version

```prose
istio version: 1.10.3
k8s version: 1.17.14
```

### Additional Information

If I turn on debug logging, for the stale endpoints, I didn't see these lines:

```2021-09-28T18:02:19.160451Z	debug	Handle event delete for service instance (from 100.117.83.50) in namespace airmesh-test-ying```

The log comes from here: https://github.com/istio/istio/blob/master/pilot/pkg/serviceregistry/serviceentry/servicediscovery.go#L444

So looks like it's either the delete event is missing or redundantEventForPod is true (which probably is not) ?

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [X] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
