### ISSUE TITLE
Istio Gateway helm chart can't render externalTrafficPolicy

### ISSUE THREAD

**Issue by dm3ch** [istio/istio#35407]
### Bug Description

When `helm template istio-ingress istio/gateway -n istio-system --version 1.12.0-alpha.1 --set service.externalTrafficPolicy="Local"` command is ran, rendering is broken.

Part of output:
```
# Source: gateway/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: istio-ingress
  namespace: istio-system
  labels:
    helm.sh/chart: gateway-1.12.0-alpha.1
    app: istio-ingress
    istio: ingress
    app.kubernetes.io/version: "1.12.0-alpha.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istio-ingress
  annotations:
    {}
spec:
  externalTrafficPolicy: "map[Capabilities:0x366afa0 Chart:0xc0000d2ea0 Files:map[README.md:[35 32 73 115 116 105 111 32 71 97 116 101 119 97 121 32 72 101 108 109 32 67 104 97 114 116 10 10 84 104 105 115 32 99 104 97 114 116 32 105 110 115 116 97 108 108 115 32 97 110 32 73 115 116 105 111 32 103 97 116 101 119 97 121 32 100 101 112 108 111 121 109 101 110 116 46 10 10 35 35 32 83 101 116 117 112 32 82 101 112 111 32 73 110 102 111 10 10 96 96 96 99 111 110 115 111 108 101 10 104 101 108 109 32 114 101 112 111 32 97 100 100 32 105 115 116 105 111 32 104 116 116 112 115 58 47 47 105 115 116 105 111 45 114 101 108 101 97 115 101 46 115 116 111 114 97 103 101 46 103 111 111 103 108 101 97 112 105 115 46 99 111 109 47 99 104 97 114 116 115 10 104 101 108 109 32 114 101 112 111 32 117 112 100 97 116 101 10 96 96 96 10 10 95 83 101 101 32 91 104 101 108 109 32 114 101 112 111 93 40 104 116 116 112 115 58 47 47 104 101 108 109 46 115 104 47 100 111 99 115 47 104 101 108 109 47 104 101 108 109 95 114 101 112 111 47 41 32 102 111 114 32 99 111 109 109 97 110 100 32 100 111 99 117 109 101 110 116 97 116 105 111 110 46 95 10 10 35 35 32 73 110 115 116 97 108 108 105 110 103 32 116 104 101 32 67 104 97 114 116 10 10 84 111 32 105 110 115 116 97 108 108 32 116 104 101 32 99 104 97 114 116 32 119 105 116 104 32 116 104 101 32 114 101 108 101 97 115 101 32 110 97 109 101 32 96 105 115 116 105 111 45 105 110 103 114 101 115 115 103 97 116 101 119 97 121 96 58 10 10 96 96 96 99 111 110 115 111 108 101 10 104 101 108 109 32 105 110 115 116 97 108 108 32 105 115 116 105 111 45 105 110 103 114 101 115 115 103 97 116 101 119 97 121 32 105 115 116 105 111 47 103 97 116 101 119 97 121 10 96 96 96 10 10 35 35 32 85 110 105 110 115 116 97 108 108 105 110 103 32 116 104 101 32 67 104 97 114 116 10 10 84 111 32 117 110 105 110 115 116 97 108 108 47 100 101 108 101 116 101 32 116 104 101 32 96 105 115 116 105 111 45 105 110 103 114 101 115 115 103 97 116 101 119 97 121 96 32 100 101 112 108 111 121 109 101 110 116 58 10 10 96 96 96 99 111 110 115 111 108 101 10 104 101 108 109 32 100 101 108 101 116 101 32 105 115 116 105 111 45 105 110 103 114 101 115 115 103 97 116 101 119 97 121 10 96 96 96 10 10 35 35 32 67 111 110 102 105 103 117 114 97 116 105 111 110 10 10 84 111 32 118 105 101 119 32 115 117 112 112 111 114 116 32 99 111 110 102 105 103 117 114 97 116 105 111 110 32 111 112 116 105 111 110 115 32 97 110 100 32 100 111 99 117 109 101 110 116 97 116 105 111 110 44 32 114 117 110 58 10 10 96 96 96 99 111 110 115 111 108 101 10 104 101 108 109 32 115 104 111 119 32 118 97 108 117 101 115 32 105 115 116 105 111 47 103 97 116 101 119 97 121 10 96 96 96 10 10 35 35 35 32 69 120 97 109 112 108 101 115 10 10 35 35 35 35 32 69 103 114 101 115 115 32 71 97 116 101 119 97 121 10 10 68 101 112 108 111 121 105 110 103 32 97 32 71 97 116 101 119 97 121 32 116 111 32 98 101 32 117 115 101 100 32 97 115 32 97 110 32 91 69 103 114 101 115 115 32 71 97 116 101 119 97 121 93 40 104 116 116 112 115 58 47 47 105 115 116 105 111 46 105 111 47 108 97 116 101 115 116 47 100 111 99 115 47 116 97 115 107 115 47 116 114 97 102 102 105 99 45 109 97 110 97 103 101 109 101 110 116 47 101 103 114 101 115 115 47 101 103 114 101 115 115 45 103 97 116 101 119 97 121 47 41 58 10 10 96 96 96 121 97 109 108 10 115 101 114 118 105 99 101 58 10 32 32 35 32 69 103 114 101 115 115 32 103 97 116 101 119 97 121 115 32 100 111 32 110 111 116 32 110 101 101 100 32 97 110 32 101 120 116 101 114 110 97 108 32 76 111 97 100 66 97 108 97 110 99 101 114 32 73 80 10 32 32 116 121 112 101 58 32 67 108 117 115 116 101 114 73 80 10 96 96 96 10 10 35 35 35 35 32 77 117 108 116 105 45 110 101 116 119 111 114 107 47 86 77 32 71 97 116 101 119 97 121 10 10 68 101 112 108 111 121 105 110 103 32 97 32 71 97 116 101 119 97 121 32 116 111 32 98 101 32 117 115 101 100 32 97 115 32 97 32 91 77 117 108 116 105 45 110 101 116 119 111 114 107 32 71 97 116 101 119 97 121 93 40 104 116 116 112 115 58 47 47 105 115 116 105 111 46 105 111 47 108 97 116 101 115 116 47 100 111 99 115 47 115 101 116 117 112 47 105 110 115 116 97 108 108 47 109 117 108 116 105 99 108 117 115 116 101 114 47 41 32 102 111 114 32 110 101 116 119 111 114 107 32 96 110 101 116 119 111 114 107 45 49 96 58 10 10 96 96 96 121 97 109 108 10 110 101 116 119 111 114 107 71 97 116 101 119 97 121 58 32 110 101 116 119 111 114 107 45 49 10 96 96 96 10 10 35 35 35 32 77 105 103 114 97 116 105 110 103 32 102 114 111 109 32 111 116 104 101 114 32 105 110 115 116 97 108 108 97 116 105 111 110 32 109 101 116 104 111 100 115 10 10 73 110 115 116 97 108 108 97 116 105 111 110 115 32 102 114 111 109 32 111 116 104 101 114 32 105 110 115 116 97 108 108 97 116 105 111 110 32 109 101 116 104 111 100 115 32 40 115 117 99 104 32 97 115 32 105 115 116 105 111 99 116 108 44 32 73 115 116 105 111 32 79 112 101 114 97 116 111 114 44 32 111 116 104 101 114 32 104 101 108 109 32 99 104 97 114 116 115 44 32 101 116 99 41 32 99 97 110 32 98 101 32 109 105 103 114 97 116 101 100 32 116 111 32 117 115 101 32 116 104 101 32 110 101 119 32 72 101 108 109 32 99 104 97 114 116 115 10 102 111 108 108 111 119 105 110 103 32 116 104 101 32 103 117 105 100 97 110 99 101 32 98 101 108 111 119 46 10 73 102 32 121 111 117 32 97 114 101 32 97 98 108 101 32 116 111 44 32 97 32 99 108 101 97 110 32 105 110 115 116 97 108 108 97 116 105 111 110 32 105 115 32 115 105 109 112 108 101 114 46 32 72 111 119 101 118 101 114 44 32 116 104 105 115 32 111 102 116 101 110 32 114 101 113 117 105 114 101 115 32 97 110 32 101 120 116 101 114 110 97 108 32 73 80 32 109 105 103 114 97 116 105 111 110 32 119 104 105 99 104 32 99 97 110 32 98 101 32 99 104 97 108 108 101 110 103 105 110 103 46 10 10 87 65 82 78 73 78 71 58 32 119 104 101 110 32 105 110 115 116 97 108 108 105 110 103 32 111 118 101 114 32 97 110 32 101 120 105 115 116 105 110 103 32 100 101 112 108 111 121 109 101 110 116 44 32 116 104 101 32 116 119 111 32 100 101 112 108 111 121 109 101 110 116 115 32 119 105 108 108 32 98 101 32 109 101 114 103 101 100 32 116 111 103 101 116 104 101 114 32 98 121 32 72 101 108 109 44 32 119 104 105 99 104 32 109 97 121 32 108 101 97 100 32 116 111 32 117 110 101 120 112 101 99 116 101 100 32 114 101 115 117 108 116 115 46 10 10 35 35 35 35 32 71 101 110 101 114 97 108 32 99 111 110 99 101 114 110 115 10 10 70 111 114 32 97 32 115 109 111 111 116 104 32 109 105 103 114 97 116 105 111 110 44 32 116 104 101 32 114 101 115 111 117 114 99 101 32 110 97 109 101 115 32 97 110 100 32 96 68 101 112 108 111 121 109 101 110 116 46 115 112 101 99 46 115 101 108 101 99 116 111 114 96 32 108 97 98 101 108 115 32 109 117 115 116 32 109 97 116 99 104 46 10 10 73 102 32 121 111 117 32 105 110 115 116 97 108 108 32 119 105 116 104 32 96 104 101 108 109 32 105 110 115 116 97 108 108 32 105 115 116 105 111 45 103 97 116 101 119 97 121 32 105 115 116 105 111 47 103 97 116 101 119 97 121 96 44 32 114 101 115 111 117 114 99 101 115 32 119 105 108 108 32 98 101 32 110 97 109 101 100 32 96 105 115 116 105 111 45 103 97 116 101 119 97 121 96 32 97 110 100 32 116 104 101 32 96 115 101 108 101 99 116 111 114 96 32 108 97 98 101 108 115 32 115 101 116 32 116 111 58 10 10 96 96 96 121 97 109 108 10 97 112 112 58 32 105 115 116 105 111 45 103 97 116 101 119 97 121 10 105 115 116 105 111 58 32 103 97 116 101 119 97 121 32 35 32 116 104 101 32 114 101 108 101 97 115 101 32 110 97 109 101 32 119 105 116 104 32 108 101 97 100 105 110 103 32 105 115 116 105 111 45 32 112 114 101 102 105 120 32 115 116 114 105 112 112 101 100 10 96 96 96 10 10 73 102 32 121 111 117 114 32 101 120 105 115 116 105 110 103 32 105 110 115 116 97 108 108 97 116 105 111 110 32 100 111 101 115 110 39 116 32 102 111 108 108 111 119 32 116 104 101 115 101 32 110 97 109 101 115 44 32 121 111 117 32 99 97 110 32 111 118 101 114 114 105 100 101 32 116 104 101 109 46 32 70 111 114 32 101 120 97 109 112 108 101 44 32 105 102 32 121 111 117 32 104 97 118 101 32 114 101 115 111 117 114 99 101 115 32 110 97 109 101 100 32 96 109 121 45 99 117 115 116 111 109 45 103 97 116 101 119 97 121 96 32 119 105 116 104 32 96 115 101 108 101 99 116 111 114 96 32 108 97 98 101 108 115 10 96 102 111 111 61 98 97 114 44 105 115 116 105 111 61 105 110 103 114 101 115 115 103 97 116 101 119 97 121 96 58 10 10 96 96 96 121 97 109 108 10 110 97 109 101 58 32 109 121 45 99 117 115 116 111 109 45 103 97 116 101 119 97 121 32 35 32 79 118 101 114 114 105 100 101 32 116 104 101 32 110 97 109 101 32 116 111 32 109 97 116 99 104 32 101 120 105 115 116 105 110 103 32 114 101 115 111 117 114 99 101 115 10 108 97 98 101 108 115 58 10 32 32 97 112 112 58 32 34 34 32 35 32 85 110 115 101 116 32 100 101 102 97 117 108 116 32 97 112 112 32 115 101 108 101 99 116 111 114 32 108 97 98 101 108 10 32 32 105 115 116 105 111 58 32 105 110 103 114 101 115 115 103 97 116 101 119 97 121 32 35 32 111 118 101 114 114 105 100 101 32 100 101 102 97 117 108 116 32 105 115 116 105 111 32 115 101 108 101 99 116 111 114 32 108 97 98 101 108 10 32 32 102 111 111 58 32 98 97 114 32 35 32 65 100 100 32 116 104 101 32 101 120 105 115 116 105 110 103 32 99 117 115 116 111 109 32 115 101 108 101 99 116 111 114 32 108 97 98 101 108 10 96 96 96 10 10 35 35 35 35 32 77 105 103 114 97 116 105 110 103 32 97 110 32 101 120 105 115 116 105 110 103 32 72 101 108 109 32 114 101 108 101 97 115 101 10 10 65 110 32 101 120 105 115 116 105 110 103 32 104 101 108 109 32 114 101 108 101 97 115 101 32 99 97 110 32 98 101 32 96 104 101 108 109 32 117 112 103 114 97 100 101 96 100 32 116 111 32 116 104 105 115 32 99 104 97 114 116 32 98 121 32 117 115 105 110 103 32 116 104 101 32 115 97 109 101 32 114 101 108 101 97 115 101 32 110 97 109 101 46 32 70 111 114 32 101 120 97 109 112 108 101 44 32 105 102 32 97 32 112 114 101 118 105 111 117 115 10 105 110 115 116 97 108 108 97 116 105 111 110 32 119 97 115 32 100 111 110 101 32 108 105 107 101 58 10 10 96 96 96 99 111 110 115 111 108 101 10 104 101 108 109 32 105 110 115 116 97 108 108 32 105 115 116 105 111 45 105 110 103 114 101 115 115 32 109 97 110 105 102 101 115 116 115 47 99 104 97 114 116 115 47 103 97 116 101 119 97 121 115 47 105 115 116 105 111 45 105 110 103 114 101 115 115 32 45 110 32 105 115 116 105 111 45 115 121 115 116 101 109 10 96 96 96 10 10 73 116 32 99 111 117 108 100 32 98 101 32 117 112 103 114 97 100 101 100 32 119 105 116 104 10 10 96 96 96 99 111 110 115 111 108 101 10 104 101 108 109 32 117 112 103 114 97 100 101 32 105 115 116 105 111 45 105 110 103 114 101 115 115 32 109 97 110 105 102 101 115 116 115 47 99 104 97 114 116 115 47 103 97 116 101 119 97 121 32 45 110 32 105 115 116 105 111 45 115 121 115 116 101 109 32 45 45 115 101 116 32 110 97 109 101 61 105 115 116 105 111 45 105 110 103 114 101 115 115 103 97 116 101 119 97 121 32 45 45 115 101 116 32 108 97 98 101 108 115 46 97 112 112 61 105 115 116 105 111 45 105 110 103 114 101 115 115 103 97 116 101 119 97 121 32 45 45 115 101 116 32 108 97 98 101 108 115 46 105 115 116 105 111 61 105 110 103 114 101 115 115 103 97 116 101 119 97 121 10 96 96 96 10 10 78 111 116 101 32 116 104 101 32 110 97 109 101 32 97 110 100 32 108 97 98 101 108 115 32 97 114 101 32 111 118 101 114 114 105 100 100 101 110 32 116 111 32 109 97 116 99 104 32 116 104 101 32 110 97 109 101 115 32 111 102 32 116 104 101 32 101 120 105 115 116 105 110 103 32 105 110 115 116 97 108 108 97 116 105 111 110 10 10 35 35 35 35 32 79 116 104 101 114 32 109 105 103 114 97 116 105 111 110 115 10 10 73 102 32 121 111 117 32 115 101 101 32 101 114 114 111 114 115 32 108 105 107 101 32 96 114 101 110 100 101 114 101 100 32 109 97 110 105 102 101 115 116 115 32 99 111 110 116 97 105 110 32 97 32 114 101 115 111 117 114 99 101 32 116 104 97 116 32 97 108 114 101 97 100 121 32 101 120 105 115 116 115 96 32 100 117 114 105 110 103 32 105 110 115 116 97 108 108 97 116 105 111 110 44 32 121 111 117 32 109 97 121 32 110 101 101 100 32 116 111 32 102 111 114 99 105 98 108 121 32 116 97 107 101 32 111 119 110 101 114 115 104 105 112 46 10 10 84 104 101 32 115 99 114 105 112 116 32 98 101 108 111 119 32 99 97 110 32 104 97 110 100 108 101 32 116 104 105 115 32 102 111 114 32 121 111 117 46 32 82 101 112 108 97 99 101 32 96 82 69 76 69 65 83 69 96 32 97 110 100 32 96 78 65 77 69 83 80 65 67 69 96 32 119 105 116 104 32 116 104 101 32 110 97 109 101 32 97 110 100 32 110 97 109 101 115 112 97 99 101 32 111 102 32 116 104 101 32 114 101 108 101 97 115 101 58 10 10 96 96 96 99 111 110 115 111 108 101 10 75 73 78 68 83 61 40 115 101 114 118 105 99 101 32 100 101 112 108 111 121 109 101 110 116 41 10 82 69 76 69 65 83 69 61 105 115 116 105 111 45 105 110 103 114 101 115 115 103 97 116 101 119 97 121 10 78 65 77 69 83 80 65 67 69 61 105 115 116 105 111 45 115 121 115 116 101 109 10 102 111 114 32 75 73 78 68 32 105 110 32 34 36 123 75 73 78 68 83 91 64 93 125 34 59 32 100 111 10 32 32 32 32 107 117 98 101 99 116 108 32 45 45 110 97 109 101 115 112 97 99 101 32 36 78 65 77 69 83 80 65 67 69 32 45 45 111 118 101 114 119 114 105 116 101 61 116 114 117 101 32 97 110 110 111 116 97 116 101 32 36 75 73 78 68 32 36 82 69 76 69 65 83 69 32 109 101 116 97 46 104 101 108 109 46 115 104 47 114 101 108 101 97 115 101 45 110 97 109 101 61 36 82 69 76 69 65 83 69 10 32 32 32 32 107 117 98 101 99 116 108 32 45 45 110 97 109 101 115 112 97 99 101 32 36 78 65 77 69 83 80 65 67 69 32 45 45 111 118 101 114 119 114 105 116 101 61 116 114 117 101 32 97 110 110 111 116 97 116 101 32 36 75 73 78 68 32 36 82 69 76 69 65 83 69 32 109 101 116 97 46 104 101 108 109 46 115 104 47 114 101 108 101 97 115 101 45 110 97 109 101 115 112 97 99 101 61 36 78 65 77 69 83 80 65 67 69 10 32 32 32 32 107 117 98 101 99 116 108 32 45 45 110 97 109 101 115 112 97 99 101 32 36 78 65 77 69 83 80 65 67 69 32 45 45 111 118 101 114 119 114 105 116 101 61 116 114 117 101 32 108 97 98 101 108 32 36 75 73 78 68 32 36 82 69 76 69 65 83 69 32 97 112 112 46 107 117 98 101 114 110 101 116 101 115 46 105 111 47 109 97 110 97 103 101 100 45 98 121 61 72 101 108 109 10 100 111 110 101 10 96 96 96 10 10 89 111 117 32 109 97 121 32 105 103 110 111 114 101 32 101 114 114 111 114 115 32 97 98 111 117 116 32 114 101 115 111 117 114 99 101 115 32 110 111 116 32 98 101 105 110 103 32 102 111 117 110 100 46 10]] Release:map[IsInstall:true IsUpgrade:false Name:istio-ingress Namespace:istio-system Revision:1 Service:Helm] Template:map[BasePath:gateway/templates Name:gateway/templates/service.yaml] Values:map[affinity:map[] annotations:map[] autoscaling:map[enabled:true maxReplicas:5 minReplicas:1 targetCPUUtilizationPercentage:80] env:[] labels:map[] name: networkGateway: nodeSelector:map[] podAnnotations:map[inject.istio.io/templates:gateway prometheus.io/path:/stats/prometheus prometheus.io/port:15020 prometheus.io/scrape:true sidecar.istio.io/inject:true] rbac:map[enabled:true] replicaCount:1 resources:map[limits:map[cpu:2000m memory:1024Mi] requests:map[cpu:100m memory:128Mi]] revision: runAsRoot:false service:map[annotations:map[] externalTrafficPolicy:Local loadBalancerIP: loadBalancerSourceRanges:[] ports:[map[name:status-port port:15021 protocol:TCP targetPort:15021] map[name:http2 port:80 protocol:TCP targetPort:8080] map[name:https port:443 protocol:TCP targetPort:8443]] type:LoadBalancer] serviceAccount:map[annotations:map[] create:true name:] tolerations:[]]]"
  type: LoadBalancer
  ports:
    - name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: istio-ingress
    istio: ingress
```

### Version

```prose
IstioCtl not used

$ helm version --short
v3.2.1+gfe51cd1

$ kubectl version --short
Client Version: v1.21.4
Server Version: v1.19.13-gke.701
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1
```
