### ISSUE TITLE
Istio causes Prometheus memory leak caused by OOMKilled

### ISSUE THREAD

**Issue by openstack-test** [istio/istio#35414]
### Bug Description

Increased memory from 6GB to more than 70GB using Prometheus Operator to monitor Istio.

As shown in the figure below
![image](https://user-images.githubusercontent.com/12166405/135249401-4d60359e-a05d-44e8-b543-48ac06e8ee8f.png)

### Version

```prose
prometheus version
v2.11.0

# istioctl version
client version: 1.10.4
control plane version: 1.10.4
data plane version: 1.10.4 (9 proxies)

# kubectl version --short
Client Version: v1.16.1
Server Version: v1.16.1

# helm version --short
v3.5.3+g041ce5a
```

### Additional Information

Prometheus istio dataplane monitoring configuration
```
# cat prometheus-oper-istio-dataplane.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-oper-istio-dataplane
  namespace: monitoring
  labels:
    monitoring: istio-dataplane
spec:
  selector:
    matchExpressions:
      - {key: istio-prometheus-ignore, operator: DoesNotExist}
  namespaceSelector:
    any: true
  jobLabel: envoy-stats
  endpoints:
  - path: /stats/prometheus
    targetPort: http-envoy-prom
    interval: 15s
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_container_port_name]
      action: keep
      regex: '.*-envoy-prom'
    - action: labelmap
      regex: "__meta_kubernetes_pod_label_(.+)"
    - sourceLabels: [__meta_kubernetes_namespace]
      action: replace
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_pod_name]
      action: replace
      targetLabel: pod_name
```

Prometheus istio controlplane monitoring configuration
```
# cat prometheus-oper-istio-controlplane.yaml 
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-oper-istio-controlplane
  namespace: monitoring
spec:
  jobLabel: istio
  selector:
    matchExpressions:
      - {key: istio, operator: In, values: [pilot,galley,citadel,sidecar-injector]}
  namespaceSelector:
    any: true
  endpoints:
  - port: http-monitoring
    interval: 15s
  - port: http-policy-monitoring
    interval: 15s
```

I see I have the same problem [Prometheus Operator - OOM killed when enabling Istio monitoring](https://stackoverflow.com/questions/66552742/prometheus-operator-oom-killed-when-enabling-istio-monitoring), but I don't know how to deal with it. I need help, thanks.
