### ISSUE TITLE
meshConfig. defaultConfig.serviceCluster istio-proxy startup parameter --service-cluster is missing

### ISSUE THREAD

**Issue by xichengliudui** [istio/istio#35411]
### Bug Description

Configure `serviceCluster` in IstioOperator，the startup parameter `--serviceCluster` is missing after istio-proxy injection
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: example-istiocontrolplane
  namespace: istio-system
spec:
  meshConfig:
    defaultConfig:
      serviceCluster: "true"
  profile: demo
```

### Version

```prose
[root@testhost http]# ~/istio-1.11.1/bin/istioctl version
client version: 1.11.1
control plane version: 1.11.1
data plane version: 1.11.1 (10 proxies)
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
