### ISSUE TITLE
ServiceEntry without Locality missing Endpoints in Gateways when using localityLbSetting

### ISSUE THREAD

**Issue by maxbischoff** [istio/istio#35410]
### Bug Description

After configuring localityLbSetting.distribute in our meshConfig, it is not possible anymore to route to external services configured in ServiceEntry via the Ingressgateway without further configuration. Instead, the Ingressgateway shows `no healthy upstream` errors and `istioctl pc clusters` shows that no endpoints exist.
For sidecars of istio-injected pods this behavior is not replicated. Normal sidecars still have the endpoints and are able to route traffic properly (unless failover to an endpoint of a different locality than given in the `distribute` policy is an unintended bug).

### Version

```prose
istioctl version
client version: 1.11.0
control plane version: 1.11.0
data plane version: 1.11.0 (7 proxies)

(was also tested with control plane version 1.11.3)
```

### Additional Information

I deployed my istio ControlPlane into an AKS cluster in `germanywestcentral` zone `0` with following Custom Resource:

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-controlplane
spec:
  profile: default
  tag: 1.11.0-distroless
  components:
    cni:
      enabled: true
  meshConfig:
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
    localityLbSetting:
      enabled: true
      distribute:
      - from: germanywestcentral/0/*
        to:
          "germanywestcentral/0/*": 100
      - from: germanywestcentral/1/*
        to:
          "germanywestcentral/1/*": 100
  values:
    cni:
      excludeNamespaces:
       - kube-system
    global:
      meshID: aks-mesh
      multiCluster:
        clusterName: cluster1
      network: cluster1-net
```

When creating following ServiceEntry, DestinationRule and VirtualService for configuring Routing to example.com via the Ingressgateway with TLS origination:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: test
  namespace: default
spec:
  location: MESH_EXTERNAL
  hosts:
  - test.default.svc.cluster.local
  ports:
  - number: 80
    name: http
    protocol: HTTP
    targetPort: 443
  resolution: DNS
  endpoints:
  - address: example.com
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: test-tls-orig
  namespace: default
spec:
  host: test
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 80
      tls:
        mode: SIMPLE
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: test
  namespace: default
spec:
  hosts:
    - "test.cluster1.example.com"
  gateways:
    - "istio-system/default-gateway"
    - "mesh"
  http:
    - route:
      - destination:
          host: test.default.svc.cluster.local
          port:
            number: 80
```

My ingressgateway proxy shows no endpoints in the cluster (retrieved with `istioctl pc clusters $(kubectl -n istio-system get po -l istio=ingressgateway -o jsonpath='{.items[0].metadata.name}').istio-system -o json | jq '.[] | select(.name | index("test")) | .loadAssignment'`):

```json
{
  "clusterName": "outbound|80||test.default.svc.cluster.local",
  "endpoints": [
    {
      "locality": {},
      "loadBalancingWeight": 1
    }
  ]
}
```

When adding the correct locality to our ServiceEntry endpoint:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: test
  namespace: default
spec:
# ... (same as above, only add locality to below endpoint)
  endpoints:
  - address: example.com
    locality: germanywestcentral/0 # < this is the fix
```

the endpoints in our ingressgateway proxy change to include the desired endpoint:

```json
{
  "clusterName": "outbound|80||test.default.svc.cluster.local",
  "endpoints": [
    {
      "locality": {
        "region": "germanywestcentral",
        "zone": "0"
      },
      "lbEndpoints": [
        {
          "endpoint": {
            "address": {
              "socketAddress": {
                "address": "example.com",
                "portValue": 443
              }
            }
          },
          "metadata": {
            "filterMetadata": {
              "istio": {
                "workload": ";;;;"
              }
            }
          },
          "loadBalancingWeight": 1
        }
      ],
      "loadBalancingWeight": 100
    }
  ]
}
```

When changing the zone part of the locality from 0 to 1, the endpoint vanishes again. A normal sidecar proxy such as 

<details> <summary>this example deployment with sidecar</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: default
spec:
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80
```

</details>

will still show the endpoint, with the locality that we set in the ServiceEntry endpoint:

```json
{
  "clusterName": "outbound|80||test.default.svc.cluster.local",
  "endpoints": [
    {
      "locality": {
        "region": "germanywestcentral",
        "zone": "1"
      },
      "lbEndpoints": [
        {
          "endpoint": {
            "address": {
              "socketAddress": {
                "address": "example.com",
                "portValue": 443
              }
            }
          },
          "metadata": {
            "filterMetadata": {
              "istio": {
                "workload": ";;;;"
              }
            }
          },
          "loadBalancingWeight": 1
        }
      ],
      "loadBalancingWeight": 1
    }
  ]
}
```

The problem also appears when removing the `distribute` policy from the meshConfig and instead creating a `DestinationRule` with the same policy. This is the simpler setup for testing, that I also used for above output since changes appear instantaneously. The behavior is the same as far as I can tell.

<details> <summary> Node labels for reference </summary>

```sh
$ kubectl get node --show-labels
NAME                              STATUS   ROLES   AGE   VERSION   LABELS
aks-default-86974662-vmss000000   Ready    agent   23h   v1.20.9   agentpool=default,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_D2_v2,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=germanywestcentral,failure-domain.beta.kubernetes.io/zone=0,kubernetes.azure.com/agentpool=default,kubernetes.azure.com/cluster=MC_pj_1und1_MaximilianBischoff_cluster1_germanywestcentral,kubernetes.azure.com/mode=system,kubernetes.azure.com/node-image-version=AKSUbuntu-1804containerd-2021.09.19,kubernetes.azure.com/os-sku=Ubuntu,kubernetes.azure.com/role=agent,kubernetes.azure.com/storageprofile=managed,kubernetes.azure.com/storagetier=Standard_LRS,kubernetes.io/arch=amd64,kubernetes.io/hostname=aks-default-86974662-vmss000000,kubernetes.io/os=linux,kubernetes.io/role=agent,node-role.kubernetes.io/agent=,node.kubernetes.io/instance-type=Standard_D2_v2,storageprofile=managed,storagetier=Standard_LRS,topology.kubernetes.io/region=germanywestcentral,topology.kubernetes.io/zone=0
aks-default-86974662-vmss000001   Ready    agent   23h   v1.20.9   agentpool=default,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_D2_v2,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=germanywestcentral,failure-domain.beta.kubernetes.io/zone=0,kubernetes.azure.com/agentpool=default,kubernetes.azure.com/cluster=MC_pj_1und1_MaximilianBischoff_cluster1_germanywestcentral,kubernetes.azure.com/mode=system,kubernetes.azure.com/node-image-version=AKSUbuntu-1804containerd-2021.09.19,kubernetes.azure.com/os-sku=Ubuntu,kubernetes.azure.com/role=agent,kubernetes.azure.com/storageprofile=managed,kubernetes.azure.com/storagetier=Standard_LRS,kubernetes.io/arch=amd64,kubernetes.io/hostname=aks-default-86974662-vmss000001,kubernetes.io/os=linux,kubernetes.io/role=agent,node-role.kubernetes.io/agent=,node.kubernetes.io/instance-type=Standard_D2_v2,storageprofile=managed,storagetier=Standard_LRS,topology.kubernetes.io/region=germanywestcentral,topology.kubernetes.io/zone=0
```
</details>

<details> <summary>Complete test setup</summary>
  
Working setup (no `distribute` policy anywhere):

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-controlplane
  namespace: istio-system
spec:
  components:
    cni:
      enabled: true
  meshConfig:
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
        ISTIO_META_DNS_CAPTURE: "true"
  profile: default
  tag: 1.11.0-distroless
  values:
    cni:
      excludeNamespaces:
      - kube-system
    global:
      meshID: aks-mesh
      multiCluster:
        clusterName: cluster1
      network: cluster1-net
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: default-gateway
  namespace: istio-system
spec:
  selector:
    app: istio-ingressgateway
  servers:
  - hosts:
    - '*.cluster1.example.com'
    port:
      name: http
      number: 80
      protocol: HTTP
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: test
  namespace: default
spec:
  location: MESH_EXTERNAL
  hosts:
  - test.default.svc.cluster.local
  ports:
  - number: 80
    name: http
    protocol: HTTP
    targetPort: 443
  resolution: DNS
  endpoints:
  - address: example.com
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: test-tls-orig
  namespace: default
spec:
  host: test
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 80
      tls:
        mode: SIMPLE
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: test
  namespace: default
spec:
  hosts:
    - "test.cluster1.example.com"
  gateways:
    - "istio-system/default-gateway"
    - "mesh"
  http:
    - route:
      - destination:
          host: test.default.svc.cluster.local
          port:
            number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: default
spec:
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80
```

breaking the setup with a `distribute` policy:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: test-tls-orig
  namespace: default
spec:
  host: test
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 80
      tls:
        mode: SIMPLE
      loadBalancer:
        localityLbSetting:
          enabled: true
          distribute:
          - from: germanywestcentral/0/*
            to:
              "germanywestcentral/0/*": 100
          - from: germanywestcentral/1/*
            to:
              "germanywestcentral/1/*": 100
```

and the complete ServiceEntry with the locality that fixes the endpoints:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: test
  namespace: default
spec:
  location: MESH_EXTERNAL
  hosts:
  - test.default.svc.cluster.local
  ports:
  - number: 80
    name: http
    protocol: HTTP
    targetPort: 443
  resolution: DNS
  endpoints:
  - address: example.com
    locality: germanywestcentral/0 # < this is the fix
```

and the zone that doesn't appear in the endpoints:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: test
  namespace: default
spec:
  location: MESH_EXTERNAL
  hosts:
  - test.default.svc.cluster.local
  ports:
  - number: 80
    name: http
    protocol: HTTP
    targetPort: 443
  resolution: DNS
  endpoints:
  - address: example.com
    locality: germanywestcentral/1
```

</details>

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
