### ISSUE TITLE
ServiceEntry gives "Connection reset by peer"

### ISSUE THREAD

**Issue by lukaszpy** [istio/istio#35419]
### Bug Description

Im using Istio with REGISTER_ONLY:
```
kubectl get istiooperator installed-state -n istio-system -o jsonpath='{.spec.meshConfig.outboundTrafficPolicy.mode}'
REGISTRY_ONL
```

I also try example SE for google:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: googletest
  namespace: testnamespace
spec:
  hosts:
    - www.google.com
  exportTo:
    - "*"
  ports:
    - number: 443
      name: https
      protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
```

but when I try to do `curl` from app container, I'm getting:

```
curl -I https://www.google.com
curl: (56) Recv failure: Connection reset by peer
``` 

what is odd on Kiali graph I see that app traffic form curl is going to different SE:
this one:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: company-net
  namespace: testnamespace
spec:
  hosts:
    - shipjobmp.company.net
    - wrapi-tls.company.net
  ports:
  - number: 80
    name: http
    protocol: HTTP
    targetPort: 443
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: shipjobmp
  namespace: testnamespace
spec:
  host: shipjobmp.company.net
  trafficPolicy:
    tls:
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: wrapi
  namespace: testnamespace
spec:
  host: wrapi-tls.company.net
  trafficPolicy:
    tls:
      mode: SIMPLE
```

### Version

```prose
istioctl version
client version: 1.11.2
control plane version: 1.11.2
data plane version: 1.11.2 (67 proxies)

kubectl version --short
Client Version: v1.19.9
Server Version: v1.19.9
```
