### ISSUE TITLE
service with externalname overrides istio-proxy 443 rules

### ISSUE THREAD

**Issue by ricosega** [istio/istio#35429]
### Bug Description

I have some services without selector pointing to endpoints for external services to the cluster in order to monitor them.
At the moment I create the following object:

```
apiVersion: v1
kind: Service
metadata:
  name: nexus-metrics-monitoring
  namespace: external-monitoring
  labels:
    app: nexus-metrics-monitoring
spec:
  externalName: nexus.internal
  ports:
  - name: nexus
    port: 4443
    protocol: TCP
    targetPort: 443
  - name: node
    port: 9100
    protocol: TCP
    targetPort: 9100   
  - name: containers
    port: 8080
    protocol: TCP
    targetPort: 8080       
  type: ExternalName
```
The TLS connections originated from inside the cluster in a pod with the istio-proxy sidecar starts to fail returning me 404 errors.
This is the ```istioctl proxy-config listeners toolkit-68754d4d6b-d7hm5 | grep 443 ``` output:
```
0.0.0.0        443   Trans: raw_buffer; App: HTTP                                             Route: 443
0.0.0.0        443   ALL                                                                      Cluster: outbound|443||nexus-metrics-monitoring.external-monitoring.svc.cluster.local
10.100.107.185 443   ALL                                                                      Cluster: outbound|443||istiod.istio-system.svc.cluster.local
10.107.150.172 443   ALL                                                                      Cluster: outbound|443||istio-ingressgateway.istio-system.svc.cluster.local
10.107.212.31  443   ALL                                                                      Cluster: outbound|443||keycloak.keycloak.svc.cluster.local
10.108.30.165  443   ALL                                                                      Cluster: outbound|443||istio-egressgateway.istio-system.svc.cluster.local
10.96.0.1      443   ALL                                                                      Cluster: outbound|443||kubernetes.default.svc.cluster.local
10.97.216.209  443   ALL                                                                      Cluster: outbound|443||step-certificates.step-certificates.svc.cluster.local
10.97.92.163   443   ALL                                                                      Cluster: outbound|443||monitoring-operator.monitoring.svc.cluster.local
```

And this is the output of the same command when the service is deleted and all works fine:
```
0.0.0.0        443   ALL                                                                      PassthroughCluster
10.100.107.185 443   ALL                                                                      Cluster: outbound|443||istiod.istio-system.svc.cluster.local
10.107.150.172 443   ALL                                                                      Cluster: outbound|443||istio-ingressgateway.istio-system.svc.cluster.local
10.107.212.31  443   ALL                                                                      Cluster: outbound|443||keycloak.keycloak.svc.cluster.local
10.108.30.165  443   ALL                                                                      Cluster: outbound|443||istio-egressgateway.istio-system.svc.cluster.local
10.96.0.1      443   ALL                                                                      Cluster: outbound|443||kubernetes.default.svc.cluster.local
10.97.216.209  443   ALL                                                                      Cluster: outbound|443||step-certificates.step-certificates.svc.cluster.local
10.97.92.163   443   ALL                                                                      Cluster: outbound|443||monitoring-operator.monitoring.svc.cluster.local
```

### Version

```prose
istioctl version --remote
client version: 1.10.0
control plane version: 1.10.0
data plane version: 1.10.0 (47 proxies)

kubectl version --short
Client Version: v1.22.1
Server Version: v1.22.1

helm version --short
v3.4.1+gc4e7485
```
