### ISSUE TITLE
mTLS origination on egress: selecting client certificates based on traffic source

### ISSUE THREAD

**Issue by rohank2002** [istio/istio#35430]
### Bug Description

Trying to setup mutual TLS origination with an egress gateway and can get it working following the docs.The issue is with trying to use unique client key/cert per namespace.  When I deploy all the resources to another namespace, mTLS will work however it will use the same key.cert that was configured in another namespace.  It appears as if the VirtualService and DestinationRule are being shared.  Attached are the two sets of resources for my config. 

### Version

```prose
Istio v1.11.3
```

### Additional Information

1st Configuration sample:

``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: curl-test
        image: governmentpaas/curl-ssl
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: IfNotPresent
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: certauth
  namespace: default
spec:
  hosts:
  - certauth.idrix.fr
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: external-certauth-22609
  namespace: default
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - certauth.idrix.fr
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-22609
  namespace: default
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: certauth-gateway-22609
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: ISTIO_MUTUAL
          sni: certauth.idrix.fr
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: certauth-22609
  namespace: default
spec:
  hosts:
  - certauth.idrix.fr
  gateways:
  - external-certauth-22609
  - mesh
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: certauth-gateway-22609
        port:
          number: 443
      weight: 100
  - match:
    - gateways:
      - external-certauth-22609
      port: 443
    route:
    - destination:
        host: certauth.idrix.fr
        subset: certauth-22609
        port:
          number: 443
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-mtls-22609
  namespace: default
spec:
  host: certauth.idrix.fr
  subsets:
  - name: certauth-22609
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: MUTUAL
          clientCertificate: /etc/istio/mtls-certs/client-cert1.crt
          privateKey: /etc/istio/mtls-certs/client-key1.key
          caCertificates: /etc/istio/mtls-certs/ca-cert1.crt
          sni: certauth.idrix.fr
```

2nd Configuration sample:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: curl-test
        image: governmentpaas/curl-ssl
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: IfNotPresent
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: certauth
  namespace: test
spec:
  hosts:
  - certauth.idrix.fr
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: external-certauth-23950
  namespace: test
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - certauth.idrix.fr
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-23950
  namespace: test
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: certauth-gateway-23950
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: ISTIO_MUTUAL
          sni: certauth.idrix.fr
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: certauth-23950
  namespace: test
spec:
  hosts:
  - certauth.idrix.fr
  gateways:
  - external-certauth-23950
  - mesh
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: certauth-gateway-23950
        port:
          number: 443
      weight: 100
  - match:
    - gateways:
      - external-certauth-23950
      port: 443
    route:
    - destination:
        host: certauth.idrix.fr
        subset: certauth-23950
        port:
          number: 443
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-mtls-23950
  namespace: test
spec:
  host: certauth.idrix.fr
  subsets:
  - name: certauth-23950
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: MUTUAL
          clientCertificate: /etc/istio/mtls-certs/client-cert.crt
          privateKey: /etc/istio/mtls-certs/client-key.key
          caCertificates: /etc/istio/mtls-certs/ca-cert.crt
          sni: certauth.idrix.fr
```
