### ISSUE TITLE
SAN is not checked unless supplied in a DR

### ISSUE THREAD

**Issue by Kmoneal** [istio/istio#35436]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
For `SIMPLE` and `MUTUAL` TLS mode, the host name is never checked in the presented certificate unless SAN is specified. SAN should be automatically filled to properly check the host certificate.

**Describe alternatives you've considered**
SAN being required by default.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
Below are SEs, DRs, and VSs that will illustrate the problem. `wrong.host.badssl.com` communication should be rejected because the certificate is issued to `*.badssl.com` rather than `*.host.badssl.com`. If no SAN is presented, even with a CA certificate specified, the TLS connection is accepted. 

`wrong.host.badssl.com` communication accepted. This is insecure behavior.
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: wrong-host-badssl-service-entry
  namespace: demo
spec:
  hosts:
  - wrong.host.badssl.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: wrong-host-badssl-destination-rule
  namespace: demo
spec:
  host: wrong.host.badssl.com
  trafficPolicy:
    tls:
      caCertificates: /etc/ssl/certs/ca-certificates.crt
      mode: SIMPLE
      sni: wrong.host.badssl.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: wrong-host-badssl-virtual-service
  namespace: demo
spec:
  hosts:
  - wrong.host.badssl.com
  http:
  - route:
    - destination:
        host: wrong.host.badssl.com
        port:
          number: 443
```

`wrong.host.badssl.com` communication refused.
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: wrong-host-badssl-service-entry
  namespace: demo
spec:
  hosts:
  - wrong.host.badssl.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: wrong-host-badssl-destination-rule
  namespace: demo
spec:
  host: wrong.host.badssl.com
  trafficPolicy:
    tls:
      caCertificates: /etc/ssl/certs/ca-certificates.crt
      mode: SIMPLE
      sni: wrong.host.badssl.com
      subjectAltNames:
      - "wrong.host.badssl.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: wrong-host-badssl-virtual-service
  namespace: demo
spec:
  hosts:
  - wrong.host.badssl.com
  http:
  - route:
    - destination:
        host: wrong.host.badssl.com
        port:
          number: 443
```
