### ISSUE TITLE
the envoy document show there is string_match,but i set string_match show error?

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#35459]
### Bug Description

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: httpconnectionmanager
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        portNumber: 8080
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
              name: envoy.filters.network.http_connection_manager
              typedConfig:
                '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                route_config:
                  name: test
                  virtual_hosts:
                  - name: test
                    domains:
                    - "*"
                    routes:
                    - name: testroute
                      match: 
                        path: /tEst
                        case_sensitive: false
                        headers:
                        - name: "host"
                          string_match:
                            exact: "test.test:32688"
                      direct_response:
                        status: 200
                        body: 
                          inline_string: "runtime_fraction"
```

[root@node01 httpconnectionmanager]# kubectl apply -f ef-route_config-virtual_hosts-routes-match-headers-string_match-exact.yaml -n istio-system
Warning: Envoy filter: can't unmarshal Any nested proto type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager: unknown field "string_match" in envoy.config.route.v3.HeaderMatcher

the envoy document show there is string_match,but i set string_match show error?

### Version

```prose
[root@node01 httpconnectionmanager]# istioctl version
client version: 1.11.2
control plane version: 1.11.2
data plane version: 1.11.2 (12 proxies)

[root@node01 httpconnectionmanager]# kubectl version --short
Client Version: v1.21.0
Server Version: v1.21.0
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
