### ISSUE TITLE
service entry request engress  url encounter: OpenSSL SSL_connect: SSL_ERROR_SYSCALL

### ISSUE THREAD

**Issue by spursy** [istio/istio#35454]
### Bug Description

1. I use minikube in my mac os
2. I have set outboundTrafficPolicy to REGISTRY_ONLY
```
 outboundTrafficPolicy:
        mode: REGISTRY_ONLY
```
3. I can connect to http protocal webside through http service entry, for example: httpbin.org
4. I cannot connect to https protocal webside through https service entry, encounter: **OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to googleapis.com:443**
command terminated with exit code 35

**Below is my config:**
https service entry
```
......
spec:
  addresses:
  - 198.18.0.47
  - 198.18.0.15
  hosts:
  - api.dropboxapi.com
  - www.googleapis.com
  - api.facebook.com
  - baidu.com
  location: MESH_EXTERNAL
  ports:
  - name: https
    number: 443
    protocol: TLS
  resolution: DNS
```

### Version

```prose
**istio versin:**
client version: 1.11.3
control plane version: 1.11.3
data plane version: 1.11.3 (9 proxies)


**k8s version**
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:23:04Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
