### ISSUE TITLE
VirtualService: HeaderMatch fails with prefix=""

### ISSUE THREAD

**Issue by philipsparrow** [istio/istio#35489]
Hi folks,

Using Anthos Service Mesh 198-1 (Istio 1.9.8)

Tried deploying a VirtualService with header matching.

According to docs (https://istio.io/v1.9/docs/reference/config/networking/virtual-service/#HTTPMatchRequest):
> If the value is empty and only the name of header is specfied, presence of the header is checked.

e.g.
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api
spec:
  hosts:
    - "*"
  gateways:
    - gw
  http:
    - match:
        - uri:
            exact: /health
          headers:
            x-my-header:
              prefix: "" # Empty value means only the presence of the header is checked
      route:
        - destination:
            host: echo-service.default.svc.cluster.local
            port:
              number: 80
```

This doesn't work because I used `prefix: ""` rather than `exact: ""`.

Perhaps this is simply a documentation issue?

The error in my ingress gateway:

```
2021-10-05T23:41:28.472641Z	warning	envoy config	gRPC config for type.googleapis.com/envoy.config.route.v3.RouteConfiguration rejected: Proto constraint validation failed (RouteConfigurationValidationError.VirtualHosts[i]: ["embedded message failed validation"] | caused by VirtualHostValidationError.Routes[i]: ["embedded message failed validation"] | caused by RouteValidationError.Match: ["embedded message failed validation"] | caused by RouteMatchValidationError.Headers[i]: ["embedded message failed validation"] | caused by HeaderMatcherValidationError.PrefixMatch: ["value length must be at least " '\x01' " runes"]): name: "http.80"
virtual_hosts {
  name: "*:80"
  domains: "*"
  routes {
    match {
      path: "/health"
      case_sensitive {
        value: true
      }
      headers {
        name: "x-my-header"
        prefix_match: ""
      }
    }
    route {
      cluster: "outbound|80||echo-service.default.svc.cluster.local"
      timeout {
      }
      retry_policy {
        retry_on: "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes"
        num_retries {
          value: 2
        }
...
```

Thanks, I'm loving Istio!

**Comment by howardjohn** [comment]
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api
spec:
  hosts:
    - "echo"
  gateways:
    - mesh
  http:
    - match:
        - uri:
            exact: /health
          headers:
            x-my-header: {}
      route:
        - destination:
            host: echo-service.default.svc.cluster.local
            port:
              number: 80
```

is the expected
