### ISSUE TITLE
[IST0109] Istioctl Analyze Falsely Flags When Using exportTo

### ISSUE THREAD

**Issue by Evesy** [istio/istio#35493]
### Bug Description

`istioctl analyze` falsely reports `[IST0109]` when there is more than one `VirtualService` specifying the same host even if both resources are scoped using `exportTo`

VS 1:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: foo
  namespace: dealer-finance-service
spec:
  exportTo:
  - dealer-finance-service
  hosts:
  - foo.net
  http:
  - name: default
    retries:
      attempts: 3
      perTryTimeout: 15s
      retryOn: connect-failure,refused-stream,unavailable,cancelled,resource-exhausted,gateway-error
    route:
    - destination:
        host: foo.net
        subset: https
      headers:
        request:
          set:
            host: foo.net
      weight: 100
    timeout: 15s
```

VS 2:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: foo
  namespace: finance-calculator-service
spec:
  exportTo:
  - finance-calculator-service
  hosts:
  - foo.net
  http:
  - name: default
    retries:
      attempts: 3
      perTryTimeout: 15s
      retryOn: connect-failure,refused-stream,unavailable,cancelled,resource-exhausted,gateway-error
    route:
    - destination:
        host: foo.net
        subset: https
      headers:
        request:
          set:
            host: foo.net
      weight: 100
    timeout: 15s
```

`istioctl validate` returns the below:
```
Error [IST0109] (VirtualService codeweavers.dealer-finance-service) The VirtualServices dealer-finance-service/codeweavers,finance-calculator-service/codeweavers,finance-search-index-service/codeweavers associated with mesh gateway define the same host */services.codeweavers.net which can lead to undefined behavior. This can be fixed by merging the conflicting VirtualServices into a single resource.
Error [IST0109] (VirtualService codeweavers.finance-calculator-service) The VirtualServices dealer-finance-service/codeweavers,finance-calculator-service/codeweavers,finance-search-index-service/codeweavers associated with mesh gateway define the same host */services.codeweavers.net which can lead to undefined behavior. This can be fixed by merging the conflicting VirtualServices into a single resource.
```

As per the [docs](https://istio.io/latest/docs/reference/config/analysis/ist0109/) , `Scope the resource to a specific namespace by setting the exportTo field.` should be a valid solution.

### Version

```prose
client version: 1.11.3
control plane version: 1.10.2
data plane version: 1.10.2 (1157 proxies)
```

```
client version: 1.11.3
control plane version: 1.10.2
data plane version: 1.10.2 (1157 proxies)
```
```


### Additional Information

_No response_
