### ISSUE TITLE
Confirm understanding of circuit breaker

### ISSUE THREAD

**Issue by guodonglai** [istio/istio#35530]
### Bug Description

Hi team,
We have configured istio (v1.8) as traffic management control plane based on kubernetes (v1.18) cluster. However, it is not clear to me regarding the circuit breaker setup in our cluster. 

### Version

```prose
istioctl version
client version: 1.11.2
control plane version: 1.8.0
data plane version: 1.8.0 (27 proxies)
kubectl version --short                                    
Client Version: v1.18.9-eks-d1db3c
Server Version: v1.18.20-eks-8c579e
```

### Additional Information

Specifically it is not the same as I expected because:
We have a destination rule between ingress-gateway and server as follows.
```
spec:
  host: my-service
  subsets:
  - labels:
      version: v1
    name: v1
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 16
      tcp:
        connectTimeout: 0.100s
        maxConnections: 32
    loadBalancer:
      simple: LEAST_CONN
    tls:
      mode: ISTIO_MUTUAL
```
However, when I dump the data from envoy it seems the max_connection and max_pending_requests configuration from server-side and client-side istio-proxies are different. 
server-side istio-proxy
```
inbound|8080||::default_priority::max_pending_requests::4294967295
inbound|8080||::high_priority::max_pending_requests::1024
```
client-side (ingress-gateway)
```
outbound|8080|v1|my-service.default.svc.cluster.local::default_priority::max_connections::32
outbound|8080|v1|my-service.default.svc.cluster.local::default_priority::max_pending_requests::16
```
From my understanding based on the post in https://tech.olx.com/demystifying-istio-circuit-breaking-27a69cac2ce4 and https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/cluster_builder.go/#L774, the same circuit-breaker configuration should be applied to both server (inbound) and client istio-proxy (outbound) where we should see something like this 

server-side istio-proxy
```
inbound|8080||::default_priority::max_pending_requests::16
inbound|8080||::high_priority::max_pending_requests::32
```
Is that correct understanding? Or am I missing something?
Could you please help me with my understanding? Thanks in advance.
