### ISSUE TITLE
Retries not working

### ISSUE THREAD

**Issue by stephaneey** [istio/istio#35545]
Hello,

I have this very simple config:
Istio version

```
client version: 1.11.2
control plane version: 1.11.2
data plane version: 1.11.2 (4 proxies)
```

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: myapp
  namespace: myapp
spec:
  hosts:
  - myapp.myapp.svc.cluster.local 
  http:      
  - name: "api"    
    route:
    - destination:       
        port: 
          number: 80
        host: myapp.myapp.svc.cluster.local
    retries:
      attempts: 10
      perTryTimeout: 5s
      retryOn: "500"
    timeout: 20s
```
where I have configured a retry policy (purposely offensive) but it does not work, although the following is returned by istioctl when inspecting routes:

```
"routes": [
                    {
                        "name": "api",
                        "match": {
                            "prefix": "/"
                        },
                        "route": {
                            "cluster": "outbound|80||myblazorapp.myblazorapp.svc.cluster.local",
                            "timeout": "0s",
                            "retryPolicy": {
                                "numRetries": 10,
                                "perTryTimeout": "5s",
                                "retryHostPredicate": [
                                    {
                                        "name": "envoy.retry_host_predicates.previous_hosts"
                                    }
                                ],
                                "hostSelectionRetryMaxAttempts": "5",
                                "retriableStatusCodes": [
                                    500
                                ]
                            },
                            "maxGrpcTimeout": "20s"
                        },
                        "metadata": {
                            "filterMetadata": {
                                "istio": {
                                    "config": "/apis/networking.istio.io/v1alpha3/namespaces/myblazorapp/virtual-service/myblazorappinternal"
                                }
                            }
                        },
                        "decorator": {
                            "operation": "myblazorapp.myblazorapp.svc.cluster.local:80/*"
                        }
                    }
                ],
```

However, no matter how I call this service (from a busybox or from another webapp), it doesn't retry on 500 return codes. My API throws exceptions randomly, which should cause istio to retry but it doesn't...There is nothing in the logs, you just see the 500 return codes but no mention of any retry. 

Thanks
