### ISSUE TITLE
Confirm understanding of circuit breaker

### ISSUE THREAD

**Issue by guodonglai** [istio/istio#35546]
Hi team,
We have configured istio  (v1.8) as traffic management control plane based on kubernetes (v1.18) cluster. However, it is not clear to me regarding the circuit breaker setup in our cluster. Specifically it is not the same as I expected because:
We have a destination rule between ingress-gateway and server as follows.
```
spec:
  host: my-service
  subsets:
  - labels:
      version: v1
    name: v1
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 16
      tcp:
        connectTimeout: 0.100s
        maxConnections: 32
    loadBalancer:
      simple: LEAST_CONN
    tls:
      mode: ISTIO_MUTUAL
```
However, when I dump the data from envoy it seems the max_connection and max_pending_requests configuration from server-side and client-side istio-proxies are different. 
server-side istio-proxy
```
inbound|8080||::default_priority::max_pending_requests::4294967295
inbound|8080||::high_priority::max_pending_requests::1024
```
client-side (ingress-gateway)
```
outbound|8080|v1|my-service.default.svc.cluster.local::default_priority::max_connections::32
outbound|8080|v1|my-service.default.svc.cluster.local::default_priority::max_pending_requests::16
```
From my understanding based on the post in https://tech.olx.com/demystifying-istio-circuit-breaking-27a69cac2ce4, the same circuit-breaker configuration should be applied to both server and client istio-proxy where we should see something like this 

server-side istio-proxy
```
inbound|8080||::default_priority::max_pending_requests::16
inbound|8080||::high_priority::max_pending_requests::32
```
Is that correct understanding? Or am I missing something?
Could you please help me with my understanding? Thanks in advance.
