### ISSUE TITLE
How do we remove resources limit/request of sidecar proxy

### ISSUE THREAD

**Issue by janamtote** [istio/istio#35556]
Hello, how do we completely remove k8s resource limit/request of sidecar proxy? We're currently using istio v1.11.3. Thank you.

**Comment by xichengliudui** [comment]
IstioOperator
```yaml
  values:
    global:
      proxy:
        image: proxyv2
        logLevel: warning
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 50Mi
```
