### ISSUE TITLE
local rate limit set `x-envoy-downstream-service-cluster` does not work

### ISSUE THREAD

**Issue by xichengliudui** [istio/istio#35568]
### Bug Description

i used `x-envoy-downstream-service-cluster` to set the rate limit, but the actual effect was different from what I predicted

after I added `x-envoy-downstream-service-cluster`, it not only didn't take effect, but also affected the API rate limit set before，is there any method to debug?

sidecar args
```yaml
  - args:
    - proxy
    - sidecar
    - --domain
    - $(POD_NAMESPACE).svc.cluster.local
    - --serviceCluster
    - sleep.ratelimit-test
    - --proxyLogLevel=warning
    - --proxyComponentLogLevel=misc:error
    - --log_output_level=default:info
    - --concurrency
    - "2"
```

```yaml
spec:
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: SIDECAR_INBOUND
      routeConfiguration:
        vhost:
          route:
            action: ROUTE
    patch:
      operation: MERGE
      value:
        route:
          rateLimits:
          - actions:
            - requestHeaders:
                descriptorKey: CLIENTCLUSTER
                headerName: "x-envoy-downstream-service-cluster"
            - requestHeaders:
                descriptorKey: PATH
                headerName: ":path"
```
```yaml
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.local_ratelimit
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
          value:
            descriptors:
            - entries:
              - key: PATH
                value: /ip
              token_bucket:
                fill_interval: 120s
                max_tokens: 5
                tokens_per_fill: 5
            - entries:
              - key: CLIENTCLUSTER
                value: sleep.test
              token_bucket:
                fill_interval: 120s
                max_tokens: 5
                tokens_per_fill: 5
            ......
            stat_prefix: http_local_rate_limiter
            token_bucket:
              fill_interval: 60s
              max_tokens: 10
              tokens_per_fill: 10
```

### Version

```prose
client version: 1.8.1
control plane version: 1.10.0
data plane version: 1.10.0 (5 proxies)
```

### Additional Information

NONE

### Affected product area

- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
