### ISSUE TITLE
incorrect traffic access

### ISSUE THREAD

**Issue by iPenx** [istio/istio#35562]
### Bug Description

there two services, A and B.  (A accesses B)
B has two deployments(different version "B1" and "B2").

the virtualservice of B only set a default route. like:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: b-vs
  namespace: b-ns
spec:
  hosts:
  - b-svc.b-ns.svc.cluster.local
  http:
  - route:
    - destination:
        host: b-svc.b-ns.svc.cluster.local
        subset: B2
```

it is normal at ordinary times, but sometimes A accesses incorrectly. (A accesses B1, it's wrong.)

What causes this problem？

### Version

```prose
$ bin/istioctl version
client version: 1.6.5
control plane version: 1.6.5
data plane version: 1.6.5 (460 proxies)
$ kubectl version --short
Client Version: v1.18.5
Server Version: v1.16.9-aliyun.1
$
```
