### ISSUE TITLE
TCP probes not working

### ISSUE THREAD

**Issue by tahirali-endurance** [istio/istio#35578]
### Bug Description

We are using readiness with tcp probes. TCP probes works fine without istio proxy but not working with istio proxy.
Kubelet assumes that port is ready even though port is not opened yet. We tried both options with ```sidecar.istio.io/rewriteAppHTTPProbers``` with ```true``` and ```false``` and still got the same behavior. Below is the deployment snippet:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-probes
  namespace: test-probes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-probes
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      labels:
        app: test-probes
    spec:
      containers:
      - env:
        - name: NEWRELIC_LICENSE_KEY
          value: "fooo"
        - name: JWKS_URLS
          value: foo.com
        image: artifactory.roving.com/docker-v2/augment-svc:0.0.50
        imagePullPolicy: IfNotPresent
        name: test-probes-augment-svc
        ports:
        - containerPort: 9001
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 9001
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 3000
        runAsUser: 1000
```

### Version

```prose
kubectl version --short
Client Version: v1.20.1
Server Version: v1.21.2-eks-0389ca3

Istio Operator version
operator:1.10.4-distroless
```
