### ISSUE TITLE
Custom path dimensions allows breaking prometheus scraping

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#35575]
### Bug Description

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    pathNormalization:
      normalization: NONE
    defaultConfig:
      extraStatTags:
      - destination_port
      - request_path
  values:
    telemetry:
      v2:
        prometheus:
          configOverride:
            inboundSidecar:
              metrics:
                - name: requests_total
                  dimensions:
                    destination_port: string(destination.port)
                    request_path: request.path
            outboundSidecar:
              metrics:
                - name: requests_total
                  dimensions:
                    destination_port: string(destination.port)
                    request_path: request.path
            gateway:
              metrics:
                - name: requests_total
                  dimensions:
                    destination_port: string(destination.port)
                    request_path: request.path
```

Then:
`client echo/foo\"bar` (with our echo app client)

Prometheus metrics look like `request_path="/foo"bar"}`. This is invalid format. Prometheus fails to scrape.

It should be impossible to break prometheus scraping, whether this is done by injecting some `escape()` function at the control plane, making envoy auto-escape quotes, or dropping metrics with quotes. Its much better to lose a single metric then to have *all* metrics dropped for an app, which can lead to a production outage due to lack of visibility

### Version

```prose
Master
```
