### ISSUE TITLE
Cannot install ingressgateway in dedicated namespace when using revisions

### ISSUE THREAD

**Issue by iliyan-velichkov** [istio/istio#35609]
### Bug Description

Hi,

I would like to install istio using revision and I want to use a dedicated /not istio-system/ namespace for my integressgateway.
Unfortunately, this is not possible because the ingressgateway is trying to connect to istiod using `istiod.istio-system.svc` service.
Steps to reproduce:
```
istioctl install -f "1.11.3-istio-operator.yaml" -y --set revision=1-11-3
    ✔ Istio core installed                                                                                                                                                                     
    ✔ Istiod installed                                                                                                                                                                         
    ✘ Ingress gateways encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the condition                                                  
    Deployment/istio-ingressgateway/istio-ingressgateway (containers with unready status: [istio-proxy])
    - Pruning removed resources                                                                                                                                                                Error: failed to install manifests: errors occurred during operation
```
Gateway logs:
```
...
2021-10-14T12:57:05.607873Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 14, connection error: desc = "transport: Error while dialing dial tcp: lookup istiod.istio-system.svc on 100.64.0.10:53: no such host"
2021-10-14T12:57:16.254717Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 14, connection error: desc = "transport: Error while dialing dial tcp: lookup istiod.istio-system.svc on 100.64.0.10:53: no such host"
2021-10-14T12:57:25.766591Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 14, connection error: desc = "transport: Error while dialing dial tcp: lookup istiod.istio-system.svc on 100.64.0.10:53: no such host"
```

Here is my `1.11.3-istio-operator.yaml` file
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  components:
    egressGateways:
    - enabled: false
      namespace: istio-egressgateway
      name: istio-egressgateway
      k8s:
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 120Mi
        securityContext:
          runAsGroup: 65534
          runAsNonRoot: true
          runAsUser: 65534
      
    ingressGateways:
    - enabled: true
      namespace: istio-ingressgateway
      name: istio-ingressgateway
      k8s:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - istio-ingressgateway
                topologyKey: "kubernetes.io/hostname"
        hpaSpec:
          maxReplicas: 10
          minReplicas: 3
          metrics:
          - resource:
              name: cpu
              targetAverageUtilization: 80
            type: Resource
          - resource:
              name: memory
              targetAverageUtilization: 80
            type: Resource
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        service:
          ports:
          - name: status-port
            port: 15021
            targetPort: 15021
          - name: http2
            port: 80
            targetPort: 8080
          - name: https
            port: 443
            targetPort: 8443
          - name: tcp
            port: 31400
            targetPort: 31400
        strategy:
          rollingUpdate:
            maxSurge: 100%
            maxUnavailable: 0
        securityContext:
          runAsGroup: 65534
          runAsNonRoot: true
          runAsUser: 65534
    pilot:
      enabled: true
      namespace: istio-system
      k8s:
        env:
        - name: PILOT_HTTP10
          value: "1"
        hpaSpec:
          maxReplicas: 5
          minReplicas: 2
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 250m
            memory: 512Mi
        securityContext:
          runAsGroup: 65534
          runAsNonRoot: true
          runAsUser: 65534
  meshConfig:
    accessLogFile: "/dev/stdout"
    trustDomain: cluster.local
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      terminationDrainDuration: 30s
      proxyMetadata: {}
      tracing:
        zipkin:
          address: "zipkin.istio-system:9411"
    enablePrometheusMerge: false
    enableTracing: false
  values:
    gateways:
      istio-ingressgateway:
        name: istio-ingressgateway
    global:
      imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - istio-reg
      logging:
        level: all:warn
      priorityClassName: ""
      proxy:
        readinessFailureThreshold: 40
        readinessInitialDelaySeconds: 5
        readinessPeriodSeconds: 5
        resources:
          requests:
            cpu: 150m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 1024Mi
      proxy_init:
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 10Mi
    pilot:
      autoscaleMax: 5
      autoscaleMin: 2
    sidecarInjectorWebhook:
      enableNamespacesByDefault: false
      objectSelector:
        autoInject: true
        enabled: false
      rewriteAppHTTPProbe: true
```
Is there a way to install the gateway in a dedicated namespace while using revisions?

### Version

```prose
k version --short
Client Version: v1.21.0
Server Version: v1.21.5

istioctl version
client version: 1.11.3
control plane version: 1.11.3
data plane version: 1.11.3
```

### Affected product area

- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [X] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
