### ISSUE TITLE
when i close PILOT_ENABLE_STATUS the old vs、dr、gateway always had status field 

### ISSUE THREAD

**Issue by cobb-tx** [istio/istio#35624]
### Bug Description

Installed Istio using

```
 --set values.pilot.env.PILOT_ENABLE_STATUS=true \ 
 --set values.global.istiod.enableAnalysis=true \
```

Everything is normal，I can see that status field。
eg：
```
status:
  conditions:
  - lastProbeTime: "2021-09-08T14:23:34.366912777Z"
    lastTransitionTime: "2021-09-08T14:23:34.366913018Z"
    message: 948/948 proxies up to date.
    status: "True"
    type: Reconciled
  observedGeneration: "1"
```

but  when  close these settings

```
 --set values.pilot.env.PILOT_ENABLE_STATUS=false\ 
 --set values.global.istiod.enableAnalysis=false\
```

the status field still exist

I expect to delete the status field

### Version

```prose
$ istioctl version
client version: 1.10.0
control plane version: 1.10.0
data plane version: 1.10.0 (233 proxies)
$ kubectl version --short
Client Version: v1.20.0
Server Version: v1.20.6
```
```


### Additional Information

_No response_
