### ISSUE TITLE
default `allow-nothing` AuthorizationPolicy has highest precedence

### ISSUE THREAD

**Issue by iliyan-velichkov** [istio/istio#35626]
### Bug Description

I'm trying to apply `allow-nothing` AuthorizationPolicy policy in the `istio-system` namespace which is supposed to be applied for all namespaces and block all requests which are not explicitly allowed with AuthorizationPolicy.
Or at least this is my understanding according to these docs:
- https://istio.io/latest/docs/concepts/security/#allow-nothing-deny-all-and-allow-all-policy
  ```
  The following example shows an ALLOW policy that matches nothing. If there are no other ALLOW policies, requests will always be denied because of the “deny by default” behavior.

  Note the “deny by default” behavior applies only if the workload has at least one authorization policy with the ALLOW action.
  ```
- https://istio.io/latest/docs/concepts/security/#policy-target
  ```
  A policy applies to the namespace in the metadata/namespace field. If set its value to the root namespace, the policy applies to all namespaces in a mesh. The value of the root namespace is configurable, and the default is istio-system.
  ```
When I try to access my app which is exposed using gateway and virtual service I get `RBAC: access denied` which tells me that the namespaces AuthorizationPolicy is not working or it has has lower priority.

Steps to reproduce:
- install istio 1.11.3
- apply `allow-nothing` policy to `istio-system` namespace
  ```
  apiVersion: security.istio.io/v1beta1
  kind: AuthorizationPolicy
  metadata:
    name: allow-nothing
  spec:
    action: ALLOW
  ```
- apply allow AuthorizationPolicy for some deployment in different namespace
  ```
  apiVersion: security.istio.io/v1beta1
  kind: AuthorizationPolicy
  metadata:
    name: enable-access
    namespace: test-app
  spec:
    action: ALLOW
    rules:
    - to:
      - operation:
          methods: ["GET"]
  ```
Is this a bug or I'm missing something?

### Version

```prose
k version --short
Client Version: v1.21.0
Server Version: v1.21.5

istioctl version
client version: 1.11.3
control plane version: 1.11.3
data plane version: 1.11.3 (4 proxies)
```
