### ISSUE TITLE
bandth_limit filter not effective,bandth 165,121 surplus the config value?

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#35639]
### Bug Description

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: bandth 
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        portNumber: 8080
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value: 
        name: envoy.filters.http.bandwidth_limit
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.bandwidth_limit.v3alpha.BandwidthLimit
          stat_prefix:  bandthlimit
          enable_mode: REQUEST_AND_RESPONSE
          limit_kbps: 1
          fill_interval: 1s
```

```
[root@node01 ~]# go-stress-testing -c 1000 -n 100000 -u http://192.168.229.134:32406/productpage

 开始启动  并发数:1000 请求数:100000 请求参数: 
request:
 form:http 
 url:http://192.168.229.134:32406/productpage 
 method:GET 
 headers:map[] 
 data: 
 verify:statusCode 
 timeout:30s 
 debug:false 



─────┬───────┬───────┬───────┬────────┬────────┬────────┬────────┬────────┬────────┬────────
 耗时│ 并发数│ 成功数│ 失败数│   qps  │最长耗时│最短耗时│平均耗时│下载字节│字节每秒│ 错误码
─────┼───────┼───────┼───────┼────────┼────────┼────────┼────────┼────────┼────────┼────────
   1s│     34│     34│      0│ 1351.34│  964.88│  391.64│  740.01│ 165,174│ 165,121│200:34
   2s│    103│    103│      0│  792.10│ 1996.51│  391.64│ 1262.46│ 498,709│ 249,261│200:103
   3s│    180│    180│      0│  558.88│ 2997.19│  391.64│ 1789.28│ 872,696│ 290,870│200:180
   4s│    253│    256│      0│  439.36│ 3923.77│  391.64│ 2276.03│1,240,504│ 310,111│200:256
   5s│    309│    332│      0│  374.15│ 4975.55│  391.64│ 2672.70│1,609,312│ 321,846│200:332
   6s│    344│    401│      0│  336.16│ 5921.87│  391.64│ 2974.78│1,943,847│ 323,959│200:401
   7s│    364│    470│      0│  309.65│ 6948.84│  391.64│ 3229.45│2,278,382│ 325,472│200:470
   8s│    365│    542│      0│  300.74│ 6996.55│  391.64│ 3325.12│2,628,458│ 328,550│200:542
   9s│    365│    619│      0│  291.81│ 6996.55│  391.64│ 3426.94│3,001,449│ 333,489│200:619
```

### Version

```prose
[root@node01 ~]# istioctl version
client version: 1.11.2
control plane version: 1.11.2
data plane version: 1.12.0-alpha.1 (5 proxies), 1.11.2 (3 proxies)

[root@node01 ~]# kubectl version --short
Client Version: v1.21.0
Server Version: v1.21.0
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
