### ISSUE TITLE
operator not cleaning up resources

### ISSUE THREAD

**Issue by strantalis** [istio/istio#35657]
### Bug Description

When using the istio operator as an installation method it doesn't clean up the underlying resources (e.g. services, deployments) when the `IstioOperator ` for ingress is deleted as an example. This was also experienced when testing a canary upgrade from 1.9.7 to 1.10.3. The old 1.9.7 ingress and control plane resources were left around but the custom resource were cleaned up so its difficult to understand why the resources were not cleaned up. 

### CNI
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: cni
  namespace: istio-system
spec:
  profile: empty
  revision: 1-10-3
  components:
    cni:
      enabled: true
  values:
    cni:
      excludeNamespaces:
        - istio-system
        - kube-system
```

### Control Plane
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: controlplane-1-10-3
spec:
  profile: minimal
  revision: 1-10-3
  values:
    istio_cni:
      enabled: true
  components:
    pilot:
      k8s:
        replicaCount: 2
        resources:
          requests:
            cpu: 100m 
            memory: 512Mi
```

### IngressGateway

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: ingressgateway-1-10-3
spec:
  profile: empty
  revision: 1-10-3
  components:
    ingressGateways:
      - enabled: true
        name: ingressgateway-1-10-3
        k8s:
          replicaCount: 3
          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
            service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
            service.beta.kubernetes.io/aws-load-balancer-type: external
```

### Version

```prose
istioctl 1.10.3

kubectl
Client Version: v1.22.2
Server Version: v1.21.2-eks-0389ca3
```

### Additional Information

More info can be found in the comments on this issue #35016.
