### ISSUE TITLE
Setting up TLS origination for GRPC connection raises OpenSSL errors

### ISSUE THREAD

**Issue by ribaptista** [istio/istio#35661]
### Bug Description

After reading the docs I tried to enable TLS origination for a GRPC connection using the code below.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-grpc
spec:
  hosts:
    - ${{ .Values.Host }}
  ports:
    - number: 80
      name: grpc
      protocol: GRPC
  resolution: DNS
  location: MESH_EXTERNAL

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: external-grpc
spec:
  host: ${{ .Values.Host }}
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE
```

My golang app is connecting to the GRPC server on port `80`, using the `WithInsecure` option:

```golang
grpc.Dial(address, grpc.WithInsecure())
```

I expected Istio to originate TLS for this connection, but instead a get the following error in istio-proxy logs:

```
[2021-10-19T04:50:50.749Z] "POST /**********/Ping HTTP/2" 200 UF,DI,URX upstream_reset_before_response_started{connection_failure,TLS_error:_268435703:SSL_routines:OPENSSL_internal:WRONG_VERSION_NUMBER} - "TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER"
```

Am I missing something?
I've already checked the GRPC server is accepting (secure) connections on port 443.

Thanks!

### Version

```prose
$ istioctl version
client version: 1.11.2
control plane version: 1.11.2
data plane version: 1.11.2 (4 proxies)
$ kubectl version --short
Client Version: v1.21.1
Server Version: v1.21.1
```

### Additional Information

Target cluster context: kind-test

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-system, kube-public, kube-node-lease, local-path-storage } AND { Namespaces: kube-system, kube-public, kube-node-lease, local-path-storage }
end-time: 2021-10-19 01:52:57.146539837 -0300 -03

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.11.2", GitRevision:"96710172e1e47cee227e7e8dd591a318fdfe0326", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.11.2"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.11.2}

Fetching proxy logs for the following containers:

default/sleep/sleep-557747455f-fxh8v/istio-proxy
default/sleep/sleep-557747455f-fxh8v/sleep
istio-operator/istio-operator/istio-operator-6547bf56c-2zfl2/istio-operator
istio-system/istio-ingressgateway-grpc/istio-ingressgateway-grpc-69fdb59c96-56mrl/istio-proxy
istio-system/istio-ingressgateway/istio-ingressgateway-5d76fcbfc9-zxvw9/istio-proxy
istio-system/istiod/istiod-76b8fdb7d8-cjxvc/discovery
order-dispatcher/order-dispatcher/order-dispatcher-55855dc8b8-k627j/istio-proxy
order-dispatcher/order-dispatcher/order-dispatcher-55855dc8b8-k627j/order-dispatcher

Fetching Istio control plane information from cluster.

Running istio analyze on all namespaces and report as below:
Analysis Report:
Warning [IST0123] (Namespace istio-operator) The namespace has both new and legacy injection labels. Run 'kubectl label namespace istio-operator istio.io/rev-' or 'kubectl label namespace istio-operator istio-injection-'
Warning [IST0129] (DestinationRule external-grpc.default) DestinationRule default/external-grpc in namespace default has TLS mode set to SIMPLE but no caCertificates are set to validate server identity for host: test.grpc.external at port number:80 
Info [IST0102] (Namespace istio-system) The namespace is not enabled for Istio injection. Run 'kubectl label namespace istio-system istio-injection=enabled' to enable it, or 'kubectl label namespace istio-system istio-injection=disabled' to explicitly mark it as not needing injection.
Creating an archive at /opt/istio-1.11.1/bug-report.tar.gz.
Cleaning up temporary files in /tmp/bug-report.
Done.
