### ISSUE TITLE
delete tracing config in cm istio ,but proxy config still remain the same?

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#35684]
### Bug Description

```
apiVersion: v1
data:
  mesh: |-
    accessLogFile: /dev/stdout
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      proxyMetadata: {}
    enablePrometheusMerge: true
    rootNamespace: istio-system
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
kind: ConfigMap
```

![image](https://user-images.githubusercontent.com/31508490/138046755-04eeab35-e861-43a6-ad40-d810e2f1a3dd.png)
![image](https://user-images.githubusercontent.com/31508490/138046783-00d5ed63-9982-453e-a014-e43d35dca14f.png)

### Version

```prose
^C[root@node01 ~]# istioctl version
client version: 1.12.0-alpha.5
control plane version: 1.12.0-alpha.5
data plane version: 1.12.0-alpha.5 (10 proxies)

[root@node01 ~]# kubectl version --short
Client Version: v1.21.0
Server Version: v1.21.0
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
