### ISSUE TITLE
can not modify tracing config using envoyfilter

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#35686]
### Bug Description

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: tracing
  namespace: istio-system
spec:
  configPatches:
  - applyTo: BOOTSTRAP
    patch:
      operation: MERGE
      value:
        node:
          metadata:
            PROXY_CONFIG:
              tracing:
                zipkin:
                  address: zipkin.zipkin:9411
```

![image](https://user-images.githubusercontent.com/31508490/138051768-4814b551-24c7-4a51-bdd8-8d6c266a3bcd.png)

### Version

```prose
[root@node01 tracing]# istioctl version
client version: 1.11.2
control plane version: 1.12.0-alpha.5
data plane version: 1.12.0-alpha.5 (10 proxies)

[root@node01 tracing]# kubectl version --short
Client Version: v1.21.0
Server Version: v1.21.0
```
