### ISSUE TITLE
VirtualService HTTPMatch is different for gateway and mesh 

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#35695]
If we define vs's http match port, it must be different for gateway and mesh.

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "httpbin.example.com"
  ---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - "httpbin.example.com"
  gateways:
  - httpbin-gateway
  http:
  - match:
    port: 80 # this port must be equal to gateway server if exists
    - uri:
        prefix: /status
    - uri:
        prefix: /delay
    route:
    - destination:
        port:
          number: 8000
        host: httpbin
```

For mesh gateway, the vs should be like

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - "httpbin.example.com"
  gateways:
  - mesh
  http:
  - match:
    port: 8000 # this port must be equal to service's port number if exists
    - uri:
        prefix: /status
    - uri:
        prefix: /delay
    route:
    - destination:
        port:
          number: 8000
        host: httpbin
```

So with the difference, i can not declare one vs for both gateway and mesh.
