### ISSUE TITLE
Cannot Access Remote 

### ISSUE THREAD

**Issue by NullOranje** [istio/istio#35703]
### Bug Description

On a single network, multi-cluster installation, applicaitons cannot access remote IPs through the local ServiceIP address.  Pods are directly accessible, as well as the remote ServiceIP.  

Neither the `istiod` pod nor `istio-proxy` indicate any errors or warning, so I'm not sure where else to look for information.  The only indication of a problem when accessing the serviceip/service name.  For example, there is a lengthy delay (5-10s) when accessing the `helloworld` service via curl before it returns the local response.

```bash
$ istioctl proxy-config ep helloworld-v2-767647d97b-kh8pv.sample | grep hello
10.128.4.13:5000                 HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
10.134.2.65:5000                 HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
```

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  profile: openshift
  hub: gcr.io/istio-release
  meshConfig:
    accessLogFile: /dev/stdout
  values:
    global:
      caAddress: cert-manager-istio-csr.cert-manager.svc:443
      meshID: cyber
      multiCluster:
        clusterName: beta
      network: cyber
    cni:
      cniBinDir: /var/lib/cni/bin
      cniConfDir: /etc/cni/multus/net.d
      chained: false
      cniConfFileName: "istio-cni.conf"
      excludeNamespaces:
      - istio-system
      - kube-system
      logLevel: info
    sidecarInjectorWebhook:
      injectedAnnotations:
        k8s.v1.cni.cncf.io/networks: istio-cni
  components:
    cni:
      enabled: true
      namespace: kube-system
    pilot:
      k8s:
        env:
          # Disable istiod CA Sever functionality
        - name: ENABLE_CA_SERVER
          value: "false"
        overlays:
        - apiVersion: apps/v1
          kind: Deployment
          name: istiod
          patches:
            # Mount istiod serving and webhook certificate from Secret mount
          - path: spec.template.spec.containers.[name:discovery].args[-1]
            value: "--tlsCertFile=/etc/cert-manager/tls/tls.crt"
          - path: spec.template.spec.containers.[name:discovery].args[-1]
            value: "--tlsKeyFile=/etc/cert-manager/tls/tls.key"
          - path: spec.template.spec.containers.[name:discovery].args[-1]
            value: "--caCertFile=/etc/cert-manager/ca/root-cert.pem"
          - path: spec.template.spec.containers.[name:discovery].volumeMounts[-1]
            value:
              name: cert-manager
              mountPath: "/etc/cert-manager/tls"
              readOnly: true
          - path: spec.template.spec.containers.[name:discovery].volumeMounts[-1]
            value:
              name: ca-root-cert
              mountPath: "/etc/cert-manager/ca"
              readOnly: true
          - path: spec.template.spec.volumes[-1]
            value:
              name: cert-manager
              secret:
                secretName: istiod-tls
          - path: spec.template.spec.volumes[-1]
            value:
              name: ca-root-cert
              configMap:
                defaultMode: 420
                name: istio-ca-root-cert
```

### Version

```prose
$ istioctl version
client version: 1.11.4
control plane version: 1.11.4
data plane version: 1.11.4 (4 proxies)
$ oc version
Client Version: 4.8.0-0.okd-2021-10-01-221835
Server Version: 4.8.0-0.okd-2021-10-10-030117
Kubernetes Version: v1.21.2-1503+a620f506e95653-dirty
```
