### ISSUE TITLE
The `medium` of an injected volume `istio-data` set to `Memory`.

### ISSUE THREAD

**Issue by BobVanB** [istio/istio#35735]
**Describe the feature request**

Feature request: The `medium` of the injected volume `istio-data` set to `Memory`.

**Describe alternatives you've considered**

We can overwrite it with a `sidecarInjectorWebhook`.

```yaml
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiocontrolplane-1.11.3-bob
spec:
  values:
    sidecarInjectorWebhook:
      defaultTemplates: ["sidecar", "custom"]
      templates:
        custom: |
          spec:
            volumes:
            - name: istio-data
              emptyDir:
                medium: Memory
```

**Affected product area**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features**

[ ] Multi Cluster
[ ] Virtual Machine
[X] Multi Control Plane

**Additional context**

The location of the volume `istio-data`:
https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/files/injection-template.yaml#L434-L435

We have a few use cases where need to enforce `emptyDir` to `Memory`.
When we enforce this with a policy, we came across `istio-data`.
We are thinking of two possible solutions, and we have to decide which is best.

* Update `istio-data` to the `medium` of type `Memory`.
* Exclude `istio-data` from our policy.

My questions with this feature request:

* For what reason is `istio-data` not in memory, just like `istio-envoy`?
* What kind of data is stored in `istio-data` and to what proportions can in grow?
* Is it possible to add a config switch to set the type to in memory:
  In the lines of `.Values.global.sidecarInjectorWebhook.defaultMedium: Memory`

With kind regards,

Bob
