### ISSUE TITLE
Default HPA minReplicas 2 in 'default' profile

### ISSUE THREAD

**Issue by sjmiller609** [istio/istio#35743]
### Bug Description

Hi Istio team! Thank you for an excellent piece of software.

Our team just configured our IstioOperator like this in order to achieve HA.

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-default
spec:
  profile: default
  components:
    ingressGateways:
    - name: istio-public-ingressgateway
      enabled: true
      k8s:
        hpaSpec:
          minReplicas: 3
          maxReplicas: 15
    - name: istio-ingressgateway
      enabled: false
```

However, I would like to note that the "default" profile is described as "This profile is recommended for production deployments".

Perhaps ingress gateways should by default have minReplicas as 2 in this profile?

### Version

```prose
istio

client version: 1.10.3
control plane version: 1.11.3
data plane version: 1.11.3 (16 proxies)


kube

Client Version: v1.21.3
Server Version: v1.21.1
```

### Additional Information

This is not strictly a bug, but more like an FYI
