### ISSUE TITLE
Implement routing in Inbound traffic in sidecar

### ISSUE THREAD

**Issue by zufardhiyaulhaq** [istio/istio#35756]
**Describe the feature request**
currently, as far as my understanding, there is no way to configure route (similar to virtual service) in Inbound traffic in the sidecar.

for example, I have this inbound listener
```
    {
        "name": "0.0.0.0_8080",
        "active_state": {
            "version_info": "2021-10-27T10:54:47Z/51",
            "listener": {
                "@type": "type.googleapis.com/envoy.config.listener.v3.Listener",
                "name": "0.0.0.0_8080",
                "address": {
                    "socket_address": {
                        "address": "0.0.0.0",
                        "port_value": 8080
                    }
                },
                "filter_chains": [{
                    "filter_chain_match": {
                        "destination_port": 8080,
                        "transport_protocol": "raw_buffer"
                    },
                    "filters": [
                        {
                            "name": "envoy.filters.network.http_connection_manager",
                            "typed_config": {
                                "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
                                "stat_prefix": "inbound_0.0.0.0_8080",
                                "route_config": {
                                    "name": "inbound|8080||",
                                    "virtual_hosts": [{
                                        "name": "inbound|http|8080",
                                        "domains": [
                                            "*"
                                        ],
                                        "routes": [{
                                            "match": {
                                                "prefix": "/"
                                            },
                                            "route": {
                                                "cluster": "inbound|8080||",
                                                "timeout": "0s",
                                                "max_stream_duration": {
                                                    "max_stream_duration": "0s"
                                                }
                                            },
                                            "decorator": {
                                                "operation": "echo-postgresql.default.svc.cluster.local:8080/*"
                                            },
                                            "name": "default"
                                        }]
                                    }]
                                }
                            }
                        }
                    ]
                }],
                "traffic_direction": "INBOUND"
            }
        }
    }
```

It will be awesome if we can implement custom routing instead of only providing the default routes in `inbound|http|8080` VirtualHost. For example:
```
{
    "routes": [{
            "match": {
                "prefix": "/api"
            },
            "route": {
                "cluster": "inbound|8080||",
                "timeout": "0s",
                "max_stream_duration": {
                    "max_stream_duration": "0s"
                }
            },
            "decorator": {
                "operation": "echo-postgresql.default.svc.cluster.local:8080/*"
            },
            "name": "api-route"
        },
        {
            "match": {
                "prefix": "/"
            },
            "route": {
                "cluster": "inbound|8080||",
                "timeout": "0s",
                "max_stream_duration": {
                    "max_stream_duration": "0s"
                }
            },
            "decorator": {
                "operation": "echo-postgresql.default.svc.cluster.local:8080/*"
            },
            "name": "default"
        }
    ]
}
```

I am trying to implement Envoy Local Rate Limit but blocked on this since I cannot specify which path that I want to rate limit. For example:

```
    - applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_INBOUND
        routeConfiguration:
          vhost:
            name: "inbound|http|8080"
            route:
              name: "api-route"
```

**Describe alternatives you've considered**
- for rate limit, implement routing inside the rate limit plugin, but it's hard to understand and the filtering is not that good.
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/local_rate_limit_filter#using-rate-limit-descriptors-for-local-rate-limiting

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by asayah** [comment]
A workaround here is to create a new Route, for example of I want to rate limit everything but `/get`on the httpbin service, I can use this Envoy Filter: 
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-local-ratelimit-svc
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: httpbin
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter
    - applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_INBOUND
        routeConfiguration:
          vhost:
            name: inbound|http|8000
      patch:
        operation: INSERT_FIRST       
        value:
          decorator:
            operation: httpbin.default.svc.cluster.local:8000/*
          match:
            prefix: /get
          name: get
          route:
            cluster: inbound|80||
            max_stream_duration:
              grpc_timeout_header_max: 0s
              max_stream_duration: 0s
            timeout: 0s
    - applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_INBOUND
        routeConfiguration:
          vhost:
            name: inbound|http|8000
            route:
              name: default
      patch:
        operation: MERGE
        value:
          typed_per_filter_config:
            envoy.filters.http.local_ratelimit:
              "@type": type.googleapis.com/udpa.type.v1.TypedStruct
              type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
              value:
                stat_prefix: http_local_rate_limiter
                token_bucket:
                  max_tokens: 3
                  tokens_per_fill: 3
                  fill_interval: 60s
                filter_enabled:
                  runtime_key: local_rate_limit_enabled
                  default_value:
                    numerator: 100
                    denominator: HUNDRED
                filter_enforced:
                  runtime_key: local_rate_limit_enforced
                  default_value:
                    numerator: 100
                    denominator: HUNDRED
                response_headers_to_add:
                  - append: false
                    header:
                      key: x-local-rate-limit
                      value: 'true'
                      

```
