### ISSUE TITLE
Telemetry API not reporting proxy traces

### ISSUE THREAD

**Issue by guiguan** [istio/istio#35750]
### Bug Description

I was following the [Telemetry API guide](https://istio.io/latest/docs/tasks/observability/distributed-tracing/configurability/telemetry-api/#configuring-mesh-wide-tracing-behavior) to migrate my old jaeger sampling configuration.

This old config worked:

```yaml
  meshConfig:                                                                                                                                                                                                                                                                                                                      
    defaultConfig:                                                                                                                                                               
      tracing:                                                                                                                                                                   
        sampling: 100                                                                                                                                                            
        zipkin:                                                                                                                                                                  
          address: zipkin.istio-system.svc.cluster.local:9411
    enableTracing: true                                                                                                                    
```

After the migration, none of the following options worked. However, it did seem that the new config could control application-level reporting by the passed in `x-b3-sampled` header from envoy proxy, which has correct value (1 or 0) based on the configured sampling percentage, but **no traces** were received from envoy proxies

## option 1: purely new config

```yaml
  meshConfig:                                                                                                                                                                                                                                                                                                                                                                                                                                    
    defaultProviders:                                                                                                                                                            
      tracing:                                                                                                                                                                   
      - cluster-jaeger                                                                                                                                                                                                                                                                                                                     
    extensionProviders:                                                                                                                                                          
    - name: cluster-jaeger                                                                                                                                                       
      zipkin:                                                                                                                                                                    
        maxTagLength: 56                                                                                                                                                         
        port: 9411                                                                                                                                                               
        service: zipkin.istio-system.svc.cluster.loca
    enableTracing: true # false didn't work either
```

```yaml
apiVersion: telemetry.istio.io/v1alpha1                                                                                                                                          
kind: Telemetry                                                                                                                                                                  
metadata:                                                                                                                                                                                                                                                                                                 
  name: mesh-default                                                                                                                                                             
  namespace: istio-system                                                                                                                                                                                                                                                                                              
spec:                                                                                                                                                                            
  tracing:                                                                                                                                                                       
  - providers:                                                                                                                                                                   
    - name: cluster-jaeger                                                                                                                                                       
    randomSamplingPercentage: 100 
```

## option 2: new and old config together

```yaml
  meshConfig:                                                                                                                                                                                                                                                                                                                                                                                                                                    
    defaultProviders:                                                                                                                                                            
      tracing:                                                                                                                                                                   
      - cluster-jaeger                                                                                                                                                                                                                                                                                                                     
    extensionProviders:                                                                                                                                                          
    - name: cluster-jaeger                                                                                                                                                       
      zipkin:                                                                                                                                                                    
        maxTagLength: 56                                                                                                                                                         
        port: 9411                                                                                                                                                               
        service: zipkin.istio-system.svc.cluster.loca
    defaultConfig:                                                                                                                                                               
      tracing:                                                                                                                                                                   
        sampling: 100                                                                                                                                                            
        zipkin:                                                                                                                                                                  
          address: zipkin.istio-system.svc.cluster.local:9411
    enableTracing: true 
```

```yaml
apiVersion: telemetry.istio.io/v1alpha1                                                                                                                                          
kind: Telemetry                                                                                                                                                                  
metadata:                                                                                                                                                                                                                                                                                                 
  name: mesh-default                                                                                                                                                             
  namespace: istio-system                                                                                                                                                                                                                                                                                              
spec:                                                                                                                                                                            
  tracing:                                                                                                                                                                       
  - providers:                                                                                                                                                                   
    - name: cluster-jaeger                                                                                                                                                       
    randomSamplingPercentage: 100 
```

### Version

```prose
client version: 1.11.3
control plane version: 1.11.3
data plane version: 1.11.3 (14 proxies)
Client Version: v1.21.5
Server Version: v1.21.2-eks-0389ca3
```


### Additional Information

_No response_

### Affected product area

- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by machine3** [comment]
I also ran into the same problem..

**Comment by magware-dev** [comment]
I have the same problem (Istio 1.11.2). It's even worse: once you use the Telemetry API, you can not rollback to the MeshConfig method. I had to completely wipe Istio and reinstall it to get the root traces from the ingress gateway

**Comment by Phil1602** [comment]
We are currently facing the same issue.

However even after re-deploying the istio control plane (and the k8s cluster itself), we were not able to get the Ingress Gateways in any other namespace than "istio-system" configured to push traces to jaeger.

Neither the "legacy" defaultConfig within meshConfig nor the new configuration using extensionProvider & Telemetry CR worked. However the Ingress- & East-West Gateways within "istio-systems" got the correct configuration.

The only way to set the correct tracing address was to pass it via overlay `PROXY_CONFIG` env variable:
```
name: PROXY_CONFIG
value: |
  {"tracing":{"zipkin":{"address":"<jaeger-address>:9411"}}}
```
In this case we were able to see the correct address in the proxy-config, but we were still not able to "enable" tracing, hence no spans were pushed to jaeger.

I would really appreciate hints if there is another way of configuring tracing for non istio-system IngressGateways. 

We are using the istio-operator to deploy the control plane and the different Gateways using a distinct IstioOperator CR for each IngressGateway.

```
istioctl version
client version: 1.11.0
control plane version: 1.11.3
data plane version: 1.11.3 (136 proxies)
kubectl version --short
Server Version: v1.20.11
```

Kindest regards

**Comment by lcc3108** [comment]
This problem is that the host header is malform.
Details can be found at #36277.
Currently, how to use telemetry api before the merged version of the pr comes out is to build the istiod yourself or proxy through nginx to send a request, and you can change the hostheader at this time.
```
upstream jaeger {
   server {YOUR_JAEGER_SVC};{YOUR_JAEGER_PORT}
}
server {
  listen ;
  location / {
    proxy_pass http://jaeger/;
    proxy_set_header Host {YOUR_JAEGER_SVC};
    proxy_set_header X-Forwarded-For $remote_addr;
  }
}
```
I tried this as an evoy filter, but the host header change failed.

**Comment by rauanmayemir** [comment]
We're facing a similar issue.

At one point, I thought telemetry api is not functional and it still seems like it. The only thing that helped was `enableTracing: true`, but now istio stopped reporting traces altogether.

**Comment by funlake** [comment]
so does version 1.12 worked with telemetry api?i just got the same problem on 1.12

**Comment by zirain** [comment]
what's the minor version you're using?

**Comment by funlake** [comment]
@zirain it's 1.12.1

**Comment by zirain** [comment]
> @zirain it's 1.12.1

can you verify this on the latest version of v1.12 or v1.13?

**Comment by funlake** [comment]
> > @zirain it's 1.12.1
> 
> can you verify this on the latest version of v1.12 or v1.13?

Sure,will do later

**Comment by funlake** [comment]
@zirain 1.12.5 worked,:-),thank you

**Comment by zhaoli2333** [comment]
I just got the same problem on 1.13.2

**Comment by Kampe** [comment]
This is still an issue, and should not be closed. @howardjohn

**Comment by ebeninca** [comment]
I have been testing the examples of observability from documentation, specially the "randomSamplingPercentage" and none of them that uses the TemeletryAPI works, it's very frustating. 

https://istio.io/latest/docs/tasks/observability/telemetry/

I still doing things with IstioOperator.

```
$ istioctl version
client version: 1.13.4
control plane version: 1.13.4
data plane version: 1.13.4 (13 proxies)
```

**Comment by guiguan** [comment]
We are on 1.14 (tried both 1.14.0 and 1.14.1) now with the IstioOperator. I can confirm that the Telemetry API is working properly. We have removed the old `defaultConfig` in mesh config. Now, with the Telemetry API, it can dynamically adjust the sampling rate. We upgraded from 1.12 to 1.14 directly, so I am not sure whether the 1.13 is working or not.

**Comment by ebeninca** [comment]
Thank you @guiguan, I found the problem, it wasn't on the version, but on the meshConfig, your hint helped me... 

I lost more than a week on this because the thing is poorly documented, unbelievable... you guys needs to improve this.

I going to put my the entire file here, so others don't suffer from the same problem... the commented part is the one that I had to remove to make it work.

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    #accessLogFile: /dev/stdout
    #defaultConfig:
    #  discoveryAddress: istiod.istio-system.svc:15012
    #  proxyMetadata: {}
    #  tracing:
    #    zipkin:
    #      address: zipkin.istio-system:9411
    defaultProviders:                                                           
      tracing:                                      
      - localtrace
    enablePrometheusMerge: true
    enableTracing: true
    extensionProviders:
    - name: "localtrace"
      zipkin:
        service: "zipkin.istio-system.svc.cluster.local"
        port: 9411
        maxTagLength: 56
    - envoyOtelAls:
        port: 4317
        service: otel-collector.istio-system.svc.cluster.local
      name: otel
    rootNamespace: istio-system
    trustDomain: **cluster.local**
```

Use this file on Istio installation:

```sh
istioctl install --set profile=demo -f mesh.yaml 
```
