### ISSUE TITLE
Support for multiple CUSTOM AuthorizationPolicies

### ISSUE THREAD

**Issue by redondos** [istio/istio#35758]
**Describe the feature request**

We would like a `CUSTOM` policy that allows access through an ingress gateway:
- to all services from a specific subnet
- to specific services from any IP address

Because Auth Policy rules are OR’ed together, this CUSTOM policy with two rules will always trigger because one of the conditions will always be true (unless connecting from this subnet to the public-service) and the request will be denied.

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ext_authz
  namespace: istio-admin
spec:
  action: CUSTOM
  provider:
    name: ext_authz
    rules:
      - from:
          - source:
              notRemoteIpBlocks:
                - 10.0.0.0/8

      - to:
        - operation:
            notHosts:
              public-service.cluster.example.com
```

Because of the [order of rule evaluation](https://istio.io/latest/docs/concepts/security/#implicit-enablement) I believe there is no way to add an `ALLOW` rule that will e.g. match the private subnet; the CUSTOM rule will be evaluated first, and if the hostname is != `public-service.cluster.example.com` ext_authz will deny the request.

I don't believe there is currently a supported way to do this, but please correct me if I'm wrong. Having multiple `CUSTOM` policies as per #34041 might help our use case.

**Describe alternatives you've considered**

Using an EnvoyFilter instead of ext_authz would be more flexible, but we would prefer to leverage the supported mechanism for authenticating requests with an external provider.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
