### ISSUE TITLE
failed to install istio using operator and did not time out

### ISSUE THREAD

**Issue by xichengliudui** [istio/istio#35775]
### Bug Description

when you install istio using operator, throughout the installation process, you are stuck installing the gateway and revision is empty，istio-operator did not time out during installation, and I see no useful logs
```shell
# kubectl get iop -n istio-system
NAME          REVISION   STATUS   AGE
cni-install                       30m
```
```shell
# kubectl get pod -n istio-system
NAME                                    READY   STATUS    RESTARTS   AGE
istio-ingressgateway-77dcd595c8-2hfcn   1/1     Running   0          28m
istiod-785c7b9746-bxwsr                 1/1     Running   0          32m
```
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: cni-install
  namespace: istio-system
spec:
  components:
    cni:
      enabled: true
    egressGateways:
    - enabled: true
      k8s:
        env:
        - name: ISTIO_META_ROUTER_MODE
          value: sni-dnat
        - name: TZ
          value: CST-8
        replicaCount: 1
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 50Mi
        service:
          ports:
          - name: http2
            port: 80
            protocol: TCP
            targetPort: 8080
          - name: https
            port: 443
            protocol: TCP
            targetPort: 8443
          - name: tls
            port: 15443
            protocol: TCP
            targetPort: 15443
          type: NodePort
        strategy:
          rollingUpdate:
            maxSurge: 100%
            maxUnavailable: 25%
      name: istio-egressgateway
    ingressGateways:
    - enabled: true
      k8s:
        env:
        - name: ISTIO_META_ROUTER_MODE
          value: sni-dnat
        - name: TZ
          value: CST-8
        replicaCount: 1
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 50Mi
        service:
          ports:
          - name: tls
            nodePort: 32003
            port: 15443
            protocol: TCP
            targetPort: 15443
          - name: http2
            nodePort: 32004
            port: 80
            protocol: TCP
            targetPort: 8080
          - name: https
            nodePort: 32005
            port: 443
            protocol: TCP
            targetPort: 8443
          type: NodePort
        strategy:
          rollingUpdate:
            maxSurge: 100%
            maxUnavailable: 25%
      name: istio-ingressgateway
    pilot:
      enabled: true
      k8s:
        env:
        - name: TZ
          value: CST-8
        - name: PILOT_ENABLE_WORKLOAD_ENTRY_AUTOREGISTRATION
          value: "true"
        replicaCount: 1
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 50Mi
        strategy:
          rollingUpdate:
            maxSurge: 100%
            maxUnavailable: 25%
  meshConfig:
    accessLogEncoding: TEXT
    accessLogFile: /dev/stdout
    defaultConfig:
      concurrency: 2
      proxyMetadata:
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
      tracing:
        custom_tags:
          mesh:
            header:
              defaultValue: mesh
              name: mesh
          tag_clustername:
            literal:
              value: cluster70
        sampling: 100
    enableAutoMtls: true
    enableTracing: true
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
  revision: 1-8-4
  tag: 1.8.4
  values:
    gateways:
      istio-ingressgateway:
        meshExpansionPorts:
        - name: tcp-istiod
          nodePort: 31261
          port: 15012
          protocol: TCP
          targetPort: 15012
    global:
      imagePullPolicy: IfNotPresent
      istioNamespace: istio-system
      jwtPolicy: first-party-jwt
      meshExpansion:
        enabled: true
        useILB: false
      multiCluster:
        clusterName: cluster70
        enabled: true
        globalDomainSuffix: global
        includeEnvoyFilter: true
      podDNSSearchNamespaces:
      - global
      proxy:
        holdApplicationUntilProxyStarts: false
        image: proxyv2
        logLevel: warning
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 80m
            memory: 50Mi
```

### Version

```prose
client version: 1.8.4
control plane version: 1.8.4
data plane version: 1.8.4 (1 proxies)
```
