### ISSUE TITLE
`image: auto` in istio-ingress/templates/injected-deployment.yaml

### ISSUE THREAD

**Issue by tokiwong** [istio/istio#35789]
### Bug Description

https://github.com/istio/istio/blob/243d3b6c966262f9ed3b944c3144a45f2e02120c/manifests/charts/gateways/istio-ingress/templates/injected-deployment.yaml#L71

Injected istio-ingressgateway Image attempts to pull from `docker.io/library/auto:latest` which doesn't seem to exist

This in contrast to the image defined in [`istio-ingress/template/deployment.yaml`](https://github.com/istio/istio/blob/243d3b6c966262f9ed3b944c3144a45f2e02120c/manifests/charts/gateways/istio-ingress/templates/deployment.yaml#L91-L99)

### Version

```prose
➜ istioctl version 
client version: 1.10.1
istiod version: 1.10.2-fips
istiod version: 1.11.4-fips
data plane version: 1.10.2-fips (35 proxies), 1.11.4-fips (1 proxies)
```

### Additional Information

```
➜ docker pull docker.io/library/auto:latest
Error response from daemon: pull access denied for auto, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by howardjohn** [comment]
No, you should not make that change. You should configure global.proxy.image in the control plane installation. 

https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#customizing-injection describes this a bit but I think we can make the doc more explicit

**Comment by tokiwong** [comment]
thanks for the docs 👍  this clarifies things better.

is there a recommended way to set our own placeholder that isn't `auto`? (for internal compliance reasons)

**Comment by howardjohn** [comment]
```
pkg/kube/inject/webhook.go
652:    AutoImage = "auto"
```

Currently hardcoded

**Comment by aishwaryaa021296** [comment]
what is the solution of this issue

**Comment by chrissng** [comment]
@tokiwong a little late here, but if you haven't figured it out, it is defined in `.Values.global.hub`

**Comment by DPS0340** [comment]
In my case (Istio Helm Chart & Argo CD), `istio-proxy` container (has image `auto`) in `Istio-gateway` Deployment not injected because `istio-sidecar-injector` in `Istiod` was not provisioned properly.
I think that Istio-base CRD was not loaded this time: when charts are synced.
So I have to sync both charts, `istio-gateway` after `istiod`.

**Comment by DPS0340** [comment]
In my case (Istio Helm Chart & Argo CD), `istio-proxy` container (has image `auto`) in `Istio-gateway` Deployment not injected because `istio-sidecar-injector`configmap in Istiod was not provisioned properly.

I think that `Istio-base` CRD was not loaded this time: when charts are synced.

So I have to sync both charts, `istio-gateway` after `istiod`.

**Comment by blue-hope** [comment]
in my case, istio-proxy container is not sidecar injected even though the `istio-injection=enabled` exists.
so I clean up istiod in my istio-system namespace, and re-install it and I got this error:

`Error: INSTALLATION FAILED: Internal error occurred: failed calling webhook "validation.istio.io": failed to call webhook: Post "https://istiod.istio-system.svc:443/validate?timeout=10s": no endpoints available for service "istiod"`

It seems that it is a version issue of validating webhook, so I removed it like:

`kubectl delete validatingwebhookconfiguration istiod-default-validator`

and re-install istiod with helm, and injection works!

**Comment by s7an-it** [comment]
@DPS0340, great this one saved me but how can it be approached in automated matter, I guess sync waves is the answer but need to shuffle through for helm example idea.

**Comment by danielsiwiec** [comment]
My team has had the same issue, which forced us to use sync waves (effectively multiple charts, installed in a particular order). After some deliberation, we went down a different path - creating a Job, that will delete the istio proxy pod, which immediately gets reprovisioned with the right image injected into it. Below is what it looks like. It would have been fantastic to have this somehow handled by istio...

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-proxy-restarter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: istio-proxy-restarter
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["delete", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-proxy-restarter
subjects:
  - kind: ServiceAccount
    name: istio-proxy-restarter
roleRef:
  kind: Role
  name: istio-proxy-restarter
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: restart-istio-proxy
spec:
  template:
    spec:
      serviceAccountName: istio-proxy-restarter
      containers:
        - name: kill-pod
          image: bitnami/kubectl:latest
          command:
            - kubectl
          args:
            - delete
            - pod
            - -l app={{ .Values.gateway.name }}
      initContainers:
        - name: wait-for-istio
          image: bitnami/kubectl:latest
          command: ["sh", "-c", "kubectl wait pods -l app=istiod --for condition=Ready"]
      restartPolicy: OnFailure

```

**Comment by julian-perge** [comment]
For anyone else having this issue but using terraform to deploy the charts. you HAVE to have the `gateway` chart for `istio-ingress` depend on the `base` and `istiod` charts to finish deploying before the `gateway` chart starts, or else you will get have to find a really goofy workaround to get it work.

**Comment by phuntsberger** [comment]
Not sure this should be added to this discussion or not, but using the comment from: https://github.com/istio/istio/issues/35789#issuecomment-1608520667

Led me in the right direction for using GCPs config sync and their annotations for dependencies. Adding this:

```config.kubernetes.io/depends-on: istio-system/deployments/[istiod-deployment-name]```

To:

```
podAnnotations:
  prometheus.io/port: '15020'
  prometheus.io/scrape: 'true'
  prometheus.io/path: '/stats/prometheus'
  inject.istio.io/templates: 'gateway'
  sidecar.istio.io/inject: 'true'
  # @REMARK - Do not remove this annotation, istio discovery needs to be running before this starts.
  # https://github.com/istio/istio/issues/35789#issuecomment-1608520667
  config.kubernetes.io/depends-on: istio-system/deployments/istiod-1-20-0
  ```
  
  In the latest helm chart allows us to use the configuration sync without errors. Not sure that folks can use the same in their deployment methodology, but it is noteworthy to add here. Please feel free to direct me to a discussion!

**Comment by younsl** [comment]
The root cause was a "network configuration error," which often leads to a timeout in MutatingWebhook API calls.

The `kube-apiserver`, one of the control plane components of EKS, must be able to communicate with the Istio control plane (`istiod`) through port 15017, which is forwarded from https-webhook port 443. 

```yaml
# istiod service
spec:
  ports:
  # ... omitted for brevity ...
  - name: https-webhook
    port: 443
    protocol: TCP
    targetPort: 15017
```

For clusters created with the official terraform EKS module, you need to manually add an inbound rule to the worker node's security group to allow the `kube-apiserver` to access port 15017 of `istiod`.

Once this connection is established, istiod will automatically replace the placeholder `auto` in the image tag of the istio ingress gateway with an appropriate tag like `docker.io/istio/proxyv2:1.24.2-distroless` that matches the control plane environment.

## Ambient Mesh

Even when installing Istio using the [Ambient mesh](https://istio.io/latest/docs/ambient/install/) pattern, which is sidecar-less, the Istio Ingress Gateway component still requires sidecar injection by istiod for installation. For this to happen, the control plane's kube-apiserver must be able to connect to istiod's HTTPS webhook port, 15017. This is forwarded from port 443 on istiod.

**Comment by emreberber** [comment]
Is there another solution besides the method suggested by @thequailman? This job doesn't cover everything; the Istio Ingress Gateway pods are running before being fully created, and there are still pods that can fail. They don't recommend using the directory with gateways, so why are you still directing there? Can't action be taken here? Deploying as an umbrella chart shouldn't be this difficult.

**Comment by Tomasz-Marciniak** [comment]
@thequailman - thank you for inspiration.

Here even more generic... adjust namespaces to your needs and you can implement custom health checks as well:

Argo annotations are to prevent reloading if ttl specified.

Bonus: **No any extra image**, no cluster polution.

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: istio-ingress

  name: istio-ingressgateway-restarter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: istio-ingress
  name: istio-ingressgateway-restarter
rules:
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "patch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-ingressgateway-restarter
  namespace: istio-ingress
subjects:
  - kind: ServiceAccount
    name: istio-ingressgateway-restarter
roleRef:
  kind: Role
  name: istio-ingressgateway-restarter
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: retry-istio-ingressgateway-injection
  namespace: istio-ingress
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 5
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: istio-ingressgateway-restarter
      automountServiceAccountToken: true
      restartPolicy: OnFailure
      containers:
        - name: check-and-restart
          image: istio/pilot:1.26.2
          command:
            - /bin/sh
            - -c
            - |
              TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
              CACERT=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
     
              echo "Waiting for istiod to be ready..."
              
              until curl -s -f http://istiod.istio-system.svc.cluster.local:8080/ready > /dev/null; do
                echo "istiod not ready yet, retrying in 5 seconds..."
                sleep 5
              done

              echo "istiod is ready. Patching istio-ingressgateway deployment..."
              
              TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
              
              curl -s -X PATCH --cacert "$CACERT" \
                -H "Authorization: Bearer $TOKEN" \
                -H "Content-Type: application/strategic-merge-patch+json" \
                -d "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"kubernetes.io/restartedAt\":\"$TIMESTAMP\"}}}}}" \
                "https://kubernetes.default.svc/apis/apps/v1/namespaces/istio-ingress/deployments/istio-ingressgateway"
              
              exit 0
```
