### ISSUE TITLE
Pilot - error translating object &crd.RouteRule - v1aplha2

### ISSUE THREAD

**Issue by nmnellis** [istio/istio#3580]
When applying the below routeRule i am seeing the following error in pilot
```
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: app-dev
spec:
  hosts:
  - app-dev
  gateways:
  - mesh
  http:
  - match:
    - uri:
        prefix: "/"
    rewrite:
      uri: "/health"
```

ERROR:
```
2018-02-17T12:47:42.863582Z	warn	error translating object &crd.RouteRule{
	TypeMeta: v1.TypeMeta {
		Kind: "",
		APIVersion: ""
	},
	ObjectMeta: v1.ObjectMeta {
		Name: "app-dev",
		GenerateName: "",
		Namespace: "istio-system",
		SelfLink: "/apis/config.istio.io/v1alpha2/namespaces/istio-system/routerules/app-dev",
		UID: "bebdb36b-13e0-11e8-ba86-0282f2e270dc",
		ResourceVersion: "808923",
		Generation: 0,
		CreationTimestamp: v1.Time {
			Time: time.Time {
				wall: 0x0,
				ext: 63654468462,
				loc: ( * time.Location)(0x1efae20)
			}
		},
		DeletionTimestamp: ( * v1.Time)(nil),
		DeletionGracePeriodSeconds: ( * int64)(nil),
		Labels: map[string] string(nil),
		Annotations: map[string] string(nil),
		OwnerReferences: [] v1.OwnerReference(nil),
		Initializers: ( * v1.Initializers)(nil),
		Finalizers: [] string(nil),
		ClusterName: ""
	},
	Spec: map[string] interface {} {
		"gateways": [] interface {} {
			"mesh"
		}, "hosts": [] interface {} {
			"app-dev"
		}, "http": [] interface {} {
			map[string] interface {} {
				"match": [] interface {} {
					map[string] interface {} {
						"uri": map[string] interface {} {
							"prefix": "/"
						}
					}
				}, "rewrite": map[string] interface {} {
					"uri": "/health"
				}
			}
		}
	}
}
```
