### ISSUE TITLE
JWT claim based routing

### ISSUE THREAD

**Issue by ffais** [istio/istio#35801]
### Bug Description

Hello to all,
I wanted to test the new "JWT claim based routing" feature.
I am following the instructions of the guide present at this address [guide](https://preliminary.istio.io/latest/docs/tasks/security/authentication/jwt-route/).

I used this command to install istio:
`istioctl install --set profile=demo --set tag=1.12.0-alpha.5-distroless`

Using this VirtualService everything works properly:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - "*"
  gateways:
  - httpbin-gateway
  http:
  - route:
    - destination:
        host: httpbin
        port:
          number: 8000
```

**Curl output**
```
$ curl "http://$INGRESS_HOST:$INGRESS_PORT/headers" -H "Authorization: Bearer $TOKEN_GROUP"
{
  "headers": {
    "Accept": "*/*", 
    "Host": "*", 
    "User-Agent": "curl/7.70.0", 
    "X-B3-Parentspanid": "b07cca4736f68714", 
    "X-B3-Sampled": "1", 
    "X-B3-Spanid": "a210726efcf221ca", 
    "X-B3-Traceid": "73033a2f044e09f7b07cca4736f68714", 
    "X-Envoy-Attempt-Count": "1", 
    "X-Envoy-Internal": "true", 
    "X-Forwarded-Client-Cert": "By=spiffe://cluster.local/ns/foo/sa/httpbin;Hash=a257af2c8125c3578f04123d28622b120037addd327198490b2911a3f1cbf21d;Subject=\"\";URI=spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"
  }
}
```

**istio-ingressgateway log:**
`[2021-10-29T14:03:49.487Z] "HEAD /headers HTTP/1.1" 200 - via_upstream - "-" 0 0 3 3 "10.240.0.4" "curl/7.70.0" "a8867c31-848b-9d10-9c4f-48a87473d31a" "20.50.53.62" "10.240.2.210:80" outbound|8000||httpbin.foo.svc.cluster.local 10.240.2.147:40150 10.240.2.147:8080 10.240.0.4:65522 - -
`

But as soon as I apply this virtualservice everything stops working.
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
  namespace: foo
spec:
  hosts:
  - "*"
  gateways:
  - httpbin-gateway
  http:
  - match:
    - uri:
        prefix: /headers
      headers:
        x-jwt-claim.groups: # "x-jwt-claim" is a reserved header for matching JWT claims only.
          exact: group1
    route:
    - destination:
        port:
          number: 8000
        host: httpbin
```
Curl output:
```
$ curl "http://$INGRESS_HOST:$INGRESS_PORT/headers" -H "Authorization: Bearer $TOKEN_GROUP" -v
*   Trying *:80...
* Connected to 20.50.53.62 (20.50.53.62) port 80 (#0)
> GET /headers HTTP/1.1
> Host: *
> User-Agent: curl/7.70.0
> Accept: */*
> Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkRIRmJwb0lVcXJZOHQyenBBMnFYZkNtcjVWTzVaRXI0UnpIVV8tZW52dlEiLCJ0eXAiOiJKV1QifQ.eyJleHAiOjM1MzczOTExMDQsImdyb3VwcyI6WyJncm91cDEiLCJncm91cDIiXSwiaWF0IjoxNTM3MzkxMTA0LCJpc3MiOiJ0ZXN0aW5nQHNlY3VyZS5pc3Rpby5pbyIsInNjb3BlIjpbInNjb3BlMSIsInNjb3BlMiJdLCJzdWIiOiJ0ZXN0aW5nQHNlY3VyZS5pc3Rpby5pbyJ9.EdJnEZSH6X8hcyEii7c8H5lnhgjB5dwo07M5oheC8Xz8mOllyg--AHCFWHybM48reunF--oGaG6IXVngCEpVF0_P5DwsUoBgpPmK1JOaKN6_pe9sh0ZwTtdgK_RP01PuI7kUdbOTlkuUi2AO-qUyOm7Art2POzo36DLQlUXv8Ad7NBOqfQaKjE9ndaPWT7aexUsBHxmgiGbz1SyLH879f7uHYPbPKlpHU6P9S-DaKnGLaEchnoKnov7ajhrEhGXAQRukhDPKUHO9L30oPIr5IJllEQfHYtt6IZvlNUGeLUcif3wpry1R5tBXRicx2sXMQ7LyuDremDbcNy_iE76Upg
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< date: Fri, 29 Oct 2021 14:51:34 GMT
< server: istio-envoy
< content-length: 0
< 
```

**istio-ingressgateway log:**
`[2021-10-29T14:02:54.689Z] "HEAD /headers HTTP/1.1" 404 NR route_not_found - "-" 0 0 0 - "10.240.0.255" "curl/7.70.0" "71457b0a-98c7-99b8-a5d2-4e67c355e199" "20.50.53.62" "-" - - 10.240.2.147:8080 10.240.0.255:27159 - -`

### Version

```prose
$ ./istioctl version
client version: 1.12.0-alpha.5
control plane version: 1.12.0-alpha.5
data plane version: 1.12.0-alpha.5 (3 proxies)
$ kubectl version --short 
Client Version: v1.22.3
Server Version: v1.20.7
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1
```

### Additional Information

```
Target cluster context: istio-test

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-system, kube-public, kube-node-lease, local-path-storage } AND { Namespaces: kube-system, kube-public, kube-node-lease, local-path-storage }
end-time: 2021-10-29 15:58:58.610518826 +0200 CEST


CLI version: version.BuildInfo{Version:"1.12.0-alpha.5", GitRevision:"6aa1f8a2748c87c76ffde6b89bcea31ba8e85e54", GolangVersion:"go1.17.1", BuildStatus:"Clean", GitTag:"1.12.0-alpha.5"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.12.0-alpha.5", GitRevision:"6aa1f8a2748c87c76ffde6b89bcea31ba8e85e54", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.12.0-alpha.5"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.12.0-alpha.5}


Fetching proxy logs for the following containers:

calico-system//calico-node-87bhw/calico-node
calico-system//calico-node-stsfn/calico-node
calico-system//calico-node-xddvx/calico-node
calico-system/calico-kube-controllers/calico-kube-controllers-7846d4d66-5smmg/calico-kube-controllers
calico-system/calico-typha/calico-typha-866b6b9bcb-2db98/calico-typha
calico-system/calico-typha/calico-typha-866b6b9bcb-j4hc5/calico-typha
calico-system/calico-typha/calico-typha-866b6b9bcb-j92gr/calico-typha
foo/httpbin/httpbin-77d765bcfb-zlrs2/httpbin
foo/httpbin/httpbin-77d765bcfb-zlrs2/istio-proxy
istio-system/istio-egressgateway/istio-egressgateway-68d95f6f8f-9tnfh/istio-proxy
istio-system/istio-ingressgateway/istio-ingressgateway-7f5f8b5757-xfwrh/istio-proxy
istio-system/istiod/istiod-7b576cfccc-ct6pp/discovery
tigera-operator/tigera-operator/tigera-operator-855dff4984-4pzxk/tigera-operator

Fetching Istio control plane information from cluster.

Running istio analyze on all namespaces and report as below:
Analysis Report:
Info [IST0102] (Namespace calico-system) The namespace is not enabled for Istio injection. Run 'kubectl label namespace calico-system istio-injection=enabled' to enable it, or 'kubectl label namespace calico-system istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace default) The namespace is not enabled for Istio injection. Run 'kubectl label namespace default istio-injection=enabled' to enable it, or 'kubectl label namespace default istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace foo) The namespace is not enabled for Istio injection. Run 'kubectl label namespace foo istio-injection=enabled' to enable it, or 'kubectl label namespace foo istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace tigera-operator) The namespace is not enabled for Istio injection. Run 'kubectl label namespace tigera-operator istio-injection=enabled' to enable it, or 'kubectl label namespace tigera-operator istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0118] (Service calico-kube-controllers-metrics.calico-system) Port name metrics-port (port: 9094, targetPort: 9094) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service calico-typha.calico-system) Port name calico-typha (port: 5473, targetPort: calico-typha) doesn't follow the naming convention of Istio port.
Creating an archive at /home/ffais/istio-1.12.0-alpha.5/bin/bug-report.tar.gz.
Cleaning up temporary files in /tmp/bug-report.
Done.
```

**Comment by howardjohn** [comment]
I think you need a Request authentication as well?

**Comment by ffais** [comment]
Yes I confirm that I have entered a request authentication as shown in the guide.

**Comment by yangminzhu** [comment]
note we are updating the syntax so the current doc is not final for 1.12. For this specific issue, could you include the request authentication policy? It must be applied on the gateway pod to make this work.

**Comment by ffais** [comment]
I'm using this one:
```
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: ingress-jwt
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: httpbin
  jwtRules:
  - issuer: "testing@secure.istio.io"
    jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.12/security/tools/jwt/samples/jwks.json"
```
I'm actually applying it to the app pod as you can see, probably that's the problem. 

If i applying it to the gateway pod then authentication is required on all apps behind that gateway, right?
