### ISSUE TITLE
Pilot - error translating object &crd.ExternalService - v1alpha2

### ISSUE THREAD

**Issue by nmnellis** [istio/istio#3581]
When applying the below ExternalService i am seeing the following error in pilot
```
apiVersion: config.istio.io/v1alpha2
kind: ExternalService
metadata:
  name: app-dev
  namespace: istio-system
spec:
  hosts:
  - app-dev.example.com
  ports:
  - number: 80
    name: app-http
    protocol: http
  discovery: dns
```

ERROR:
```
2018-02-17T12:53:33.288436Z	warn	error translating object &crd.ExternalService
{
	TypeMeta: v1.TypeMeta {
		Kind: "",
		APIVersion: ""
	},
	ObjectMeta: v1.ObjectMeta {
		Name: "app-dev",
		GenerateName: "",
		Namespace: "istio-system",
		SelfLink: "/apis/config.istio.io/v1alpha2/namespaces/istio-system/externalservices/app-dev",
		UID: "8f9c9887-13e1-11e8-88d6-0a63dce50dbe",
		ResourceVersion: "809807",
		Generation: 0,
		CreationTimestamp: v1.Time {
			Time: time.Time {
				wall: 0x0,
				ext: 63654468813,
				loc: ( * time.Location)(0x1efae20)
			}
		},
		DeletionTimestamp: ( * v1.Time)(nil),
		DeletionGracePeriodSeconds: ( * int64)(nil),
		Labels: map[string] string(nil),
		Annotations: map[string] string(nil),
		OwnerReferences: [] v1.OwnerReference(nil),
		Initializers: ( * v1.Initializers)(nil),
		Finalizers: [] string(nil),
		ClusterName: ""
	},
	Spec: map[string] interface {} {
		"discovery": "dns", "hosts": [] interface {} {
			"app-dev.example.com"
		}, "ports": [] interface {} {
			map[string] interface {} {
				"name": "app-http", "number": 0x50, "protocol": "http"
			}
		}
	}
}
```

**Comment by nmnellis** [comment]
actual error
```
YAML decoding error: gateways:
- mesh
hosts:
- app-dev
http:
- match:
  - uri:
      prefix: /
  rewrite:
    uri: /health
 unknown field "gateways" in v1alpha1.RouteRule
```
