### ISSUE TITLE
VirtualServices with `hosts = ["*"]` cause incorrect envoy `virtualHosts` ordering

### ISSUE THREAD

**Issue by thesuperzapper** [istio/istio#35826]
### Bug Description

Currently, VirtualServices that specify `hosts = ["*"]` can cause istio to incorrectly order the envoy `virtualHosts` for generated Gateways.

This happens for Gateways which expose subdomains like `*.example.com`.

----

Here is a very basic example that causes this behavior.

### `Gateway/my-gateway`
```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: my-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - "default/*.example.com"
      port:
        name: http
        number: 80
        protocol: HTTP
```

### `VirtualService/app1`
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app1
  namespace: default
spec:
  gateways:
    - default/my-gateway
  hosts:
    - app1.example.com
  http:
    - route:
        ## NOTE: I have not included the `Service/app1` YAML in my example
        - destination:
            host: app1.default.svc.cluster.local
            port:
              number: 80
```

### `VirtualService/app2`
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app2
  namespace: default
spec:
  gateways:
    - default/my-gateway
  hosts:
    - "*"
  http:
    - route:
        ## NOTE: I have not included the `Service/app2` YAML in my example
        - destination:
            host: app2.default.svc.cluster.local
            port:
              number: 80
```

----

The generated EnvoyProxy `virtualHosts` have been created in the wrong order, with the most generic `*.example.com` domain at the top, making the more specific `app1.example.com` domain inaccessible.

```bash
istioctl proxy-config route istio-ingressgateway-XXXXXXXX-XXXXX.istio-system -o yaml
```

```yaml
- name: http.80
  validateClusters: false
  virtualHosts:
  - domains:
    - '*.example.com'
    - '*.example.com:80'
    includeRequestAttemptCount: true
    name: '*.example.com:80'
    routes:
    - decorator:
        operation: app2.default.svc.cluster.local:80/*
      match:
        prefix: /
      metadata:
        filterMetadata:
          istio:
            config: /apis/networking.istio.io/v1alpha3/namespaces/default/virtual-service/app2
      route:
        cluster: outbound|80||app2.default.svc.cluster.local
        maxGrpcTimeout: 0s
        retryPolicy:
          hostSelectionRetryMaxAttempts: "5"
          numRetries: 2
          retriableStatusCodes:
          - 503
          retryHostPredicate:
          - name: envoy.retry_host_predicates.previous_hosts
          retryOn: connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes
        timeout: 0s
  - domains:
    - app1.example.com
    - app1.example.com:*
    includeRequestAttemptCount: true
    name: app1.example.com:80
    routes:
    - decorator:
        operation: app1.default.svc.cluster.local:80/*
      match:
        prefix: /
      metadata:
        filterMetadata:
          istio:
            config: /apis/networking.istio.io/v1alpha3/namespaces/default/virtual-service/app1
      route:
        cluster: outbound|80||app1.default.svc.cluster.local
        maxGrpcTimeout: 0s
        retryPolicy:
          hostSelectionRetryMaxAttempts: "5"
          numRetries: 2
          retriableStatusCodes:
          - 503
          retryHostPredicate:
          - name: envoy.retry_host_predicates.previous_hosts
          retryOn: connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes
        timeout: 0s
- virtualHosts:
  - domains:
    - '*'
    name: backend
    routes:
    - match:
        prefix: /healthz/ready
      route:
        cluster: agent
- virtualHosts:
  - domains:
    - '*'
    name: backend
    routes:
    - match:
        prefix: /stats/prometheus
      route:
        cluster: prometheus_stats
```

### Version

```prose
client version: 1.11.4
control plane version: 1.10.3
data plane version: 1.10.3 (16 proxies)

---

Client Version: v1.21.5
Server Version: v1.21.1
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
