### ISSUE TITLE
Istio PeerAuthentication portLevelMtls at namespace level

### ISSUE THREAD

**Issue by pratapagiri** [istio/istio#35871]
We have a requirement to allow PeerAuthentication on Port 9090 (for prometheus). 

I have looked at https://github.com/istio/istio/issues/30457 [](https://github.com/istio/istio/issues/30457) and tried the following, but it didn't work:

```
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "prom-metrics"
  namespace: "mynamespace"
spec:
  selector:
    matchLabels:
      host: "*.mynamespace.svc.cluster.local"
  portLevelMtls:
    9090:
      mode: PERMISSIVE
```
I got the below error:

`Error: admission webhook "validation.istio.io" denied the request: configuration is invalid: wildcard is not supported in selector: "host=*.mynamespace.svc.cluster.local"`

We have around 50 services and we would like to create one policy for the namespace to allow Prometheus.

Can someone suggest me how to do this?

**Comment by howardjohn** [comment]
matchLabels is matching labels on pods, not hostnames. I would just add a common label to everything you want to select (like `app=prometheus`).

**Comment by pratapagiri** [comment]
@howardjohn Thanks for your reply.  We have pods with different labels (ex: service-app1, service-app2, service-app3 etc).
One solution is to repeat the below block for all pods. 
```
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "prom-metrics"
  namespace: "mynamespace"
spec:
  selector:
    matchLabels:
      app: "service-app1"
  portLevelMtls:
    9090:
      mode: PERMISSIVE
```
However, we have 50+ services in the namespace. So I'm looking for some elegant solution.
whether  _matchExpressions_  can be used here?
```
spec:
  selector:
    matchExpressions:
         - {key: app, operator: In, values: [service-app1, service-app2, service-app3..]}    
```

**Comment by hzxuzhonghu** [comment]
You can leave selector unset, which means the rules will be applied to all workloads in the same namespace

**Comment by pratapagiri** [comment]
@howardjohn , @hzxuzhonghu Thanks for your suggestions. 

I have tried with the following and it didn't work:

```
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "prom-metrics"
  namespace: "mynamespace"
spec:
  selector: {}
  portLevelMtls:
    9090:
      mode: PERMISSIVE
```

It gave the below error:

`failed to create resource: admission webhook "validation.istio.io" denied the request: configuration is invalid: mesh/namespace peer authentication cannot have port level mTLS`

As per the code https://github.com/istio/istio/blob/master/pkg/config/validation/validation.go#L1912 we cannot have empty selector 

Could you please let me know some possible solution?
