### ISSUE TITLE
Support PodSecurity

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#35894]
https://github.com/kubernetes/enhancements/issues/2579

Figure out what, if anything, we need to do to 'support' this. Docs, tweaking the pod specs to meet some requirements , etc

**Comment by howardjohn** [comment]
Need to follow https://github.com/kubernetes/pod-security-admission/tree/master/webhook to get started

```
forbidden: violates PodSecurity "restricted:latest": non-default capabilities (container "istio-init" must not include "NET_ADMIN", "NET_RAW" in securityContext.capabilities.add), unrestricted capabilities (container "istio-init" must not include "NET_ADMIN", "NET_RAW" in securityContext.capabilities.add), runAsNonRoot != true (container "istio-init" must not set securityContext.runAsNonRoot=false), runAsUser=0 (container "istio-init" must not set runAsUser=0), seccompProfile (pod or containers "istio-init", "isti
```

From standard istio pod with restricted.


```
is forbidden: violates PodSecurity "baseline:latest": non-default capabilities (container "istio-init" must not include "NET_ADMIN", "NET_RAW" in securityContext.capabilities.add)
```

From baseline
---
With CNI

Baseline is :+1: 

restricted needs `seccompProfile` set. But `RuntimeDefault` seems pretty dangerous given it can be literally anything depending on the platform??

---

Control plane:

* CNI obviously fails even baseline
* Discovery fails but I think we can lock it down

**Comment by howardjohn** [comment]
@ksubrmnn is looking into it

**Comment by oxr463** [comment]
@howardjohn any updates on this one?

**Comment by howardjohn** [comment]
afaik https://github.com/istio/istio/pull/40115 is the latest

**Comment by mhson281** [comment]
We already have that configured but still getting an error that replica set violate the PodSecurity baseline:latest due to Istio container must not have NET_ADMIN & NET_RAW capabilities.

**Comment by howardjohn** [comment]
You need to use https://istio.io/latest/docs/setup/additional-setup/cni/

**Comment by ksubrmnn** [comment]
I'm picking this issue up off my backlog again. I'll start by deprecating any PSP related code before moving on to PSA compat

**Comment by ksubrmnn** [comment]
Findings are that we just need to provide docs for customers to use cni because podsecurity baseline does not allow for net admin/raw capabilities, apply the privileged pod security standard to istio-system namespace to allow for cni daemonset to configure networking, and how to run demo with psa baseline for data-plane namespaces in the mesh

**Comment by ksubrmnn** [comment]
Findings can be confirmed with following steps:

# See pods fail with init container injection
1. Follow steps 1-6 https://kubernetes.io/docs/tutorials/security/cluster-level-pss/#set-modes-versions-and-standards
1. Install istio https://kubernetes.io/docs/tutorials/security/cluster-level-pss/#set-modes-versions-and-standards
1. Run demo steps 1 https://kubernetes.io/docs/tutorials/security/cluster-level-pss/#set-modes-versions-and-standards
kubectl get po -n default -> See that no pods are scheduled
1. Pods fail baseline because injection uses NET_ADMIN
1. Clean up istio and cluster

# See pods succeed with CNI
1. Install istio w/ cni : istioctl install --set components.cni.enabled=true --set profile=demo
1. See failure
1. Label ns istio-system to have privilege enforced
1. See install succeed
1. Remove  injection label on default ns: kubectl label namespaces default istio-injection-
1. Run demo steps 1 https://kubernetes.io/docs/tutorials/security/cluster-level-pss/#set-modes-versions-and-standards
1. See pods running

**Comment by fb314159265** [comment]
The automatic sidecar injection doesn't work on a namespace with PSS restricted... even with the Istio CNI plugin enabled. The sidecar doesn't comply to PSS restricted because seccompProfile.type is empty in the sidecar definition, while PSS restricted requires a seccompProfile to be setted.

`Warning  FailedCreate  4m43s               replicaset-controller  Error creating: pods "productpage-v1-756c7b69c9-hng2t" is forbidden: violates PodSecurity "restricted:latest": seccompProfile (pod or containers "istio-validation", "istio-proxy" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")`

More details here : https://github.com/istio/istio/pull/42717#issuecomment-1494963202

**Comment by ksubrmnn** [comment]
> The automatic sidecar injection doesn't work on a namespace with PSS restricted... even with the Istio CNI plugin enabled. PSS restricted requires a seccompProfile to be setted to "RuntimeDefault" or "Localhost". The sidecar doesn't comply to PSS restricted because seccompProfile.type is empty in the sidecar (istio-validation + istio-proxy) specs.
> 
> `Warning FailedCreate 4m43s replicaset-controller Error creating: pods "productpage-v1-756c7b69c9-hng2t" is forbidden: violates PodSecurity "restricted:latest": seccompProfile (pod or containers "istio-validation", "istio-proxy" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost") `
> 
> More details here : [#42717 (comment)](https://github.com/istio/istio/pull/42717#issuecomment-1494963202) Related to : #41275

Have you tried  setting the securityContext at the pod level and not the container level?

**Comment by fb314159265** [comment]
> Have you tried setting the securityContext at the pod level and not the container level?

Thank you very much @ksubrmnn for your help. You're right. 

I got the error when seccompProfile was defined at the container level on my Deployment. 
By setting seccompProfile at the Pod level (instead of at container level), it works now.

Some securityContext fields needs to be defined at pod level, some others fields need to be defined at container level.

If it can help others to make Istio work with PSS restricted and Istio CNI, this is an example of securityContext fields you can define on your Deployments to make it the istio injection work with PSS restricted. 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-v1
  labels:
    app: ratings
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
      version: v1

  template:
    metadata:
      labels:
        app: ratings
        version: v1
    spec:
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        seccompProfile:
          type: "RuntimeDefault"
      serviceAccountName: bookinfo-ratings
      containers:
      - name: ratings
        image: docker.io/istio/examples-bookinfo-ratings-v1:1.17.0
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: 
            drop: ["ALL"]
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
```
