### ISSUE TITLE
EnvoyFilter validation does not allow google.protobuf.Any types in struct

### ISSUE THREAD

**Issue by nareddyt** [istio/istio#35924]
### Bug Description

I am using Istio's [EnvoyFilter](https://istio.io/latest/docs/reference/config/networking/envoy-filter) to `MERGE` metadata into the [listener config](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener.proto). Sample:

```yaml
//file path: envoyfilter.yaml

{
  "apiVersion": "networking.istio.io/v1alpha3",
  "kind": "EnvoyFilter",
  "metadata": {
    "creationTimestamp": null,
    "name": "my-api-envoy-filter",
    "namespace": "istio-system"
  },
  "spec": {
    "configPatches": [
      {
        "applyTo": "LISTENER",
        "match": {
          "context": "GATEWAY",
          "listener": {
            "portNumber": 8080
          }
        },
        "patch": {
          "operation": "MERGE",
          "value": {
            "metadata": {
              "typedFilterMetadata": {
                "com.google.cloudesf.service_config": {
                  "@type": "type.googleapis.com/google.api.Service",
                  "name": "bookstore.endpoints.project123.cloud.goog",
                  // Fields in this message omitted for brevity
                }
              }
            }
          }
        }
      }
    ]
  },
  "status": {}
}
```

But this fails [configuration validation](https://istio.io/latest/docs/ops/common-problems/validation/) because I filled in the `google.protobuf.Any` with a type that is unknown to Istio. In the example above, the proto is published by Google and not part of the xDS API. https://github.com/googleapis/googleapis/blob/f9acb378c691a7ac449fd9fb32aa25aee14814d8/google/api/service.proto#L71

```
istioctl validate -f envoyfilter.yaml

Error: 1 error occurred:
	* EnvoyFilter/istio-system/my-api-envoy-filter: Envoy filter: could not resolve Any message type: type.googleapis.com/google.api.Service
```

I assume the error is coming from here

https://github.com/istio/istio/blob/57b27bfceb507d56fa59b46917a44eb60524c3ae/pkg/config/validation/validation.go#L835

https://github.com/istio/istio/blob/57b27bfceb507d56fa59b46917a44eb60524c3ae/pkg/config/xds/xds.go#L74

Is there any good solution to this? The validation prevents applying the config with `kubectl` as well. Some workarounds I can think of:
1) Disable istio's configuration validation via the overlay (not recommended)
2) Link in some of these types into Istio's validator, similar to https://github.com/istio/istio/blob/master/pkg/config/xds/filter_types.gen.go

If I do 2, I assume I need to re-build istio myself?

### Version

```prose
client version: 1.11.2-asm.17
control plane version: 1.11.2-asm.17
data plane version: none
```
