### ISSUE TITLE
istiod in remote cluster lacks env ISTIO_CUSTOM_HOST to add its self host to altNames

### ISSUE THREAD

**Issue by YonkaFang** [istio/istio#35939]
### Bug Description

As the title. This will cause the ingress gateway in the remote cluster to report an error when initiating a CSR request to istiod-1-11-4 in its own cluster with the following message.

```
failed to warm certificate: failed to generate workload certificate: create certificate: rpc error: code = Unavailble desc = connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for istiod-remote.istio-system.svc, istiod.istio-system.svc, istio-pilot.istio-system.svc, not istiod-1-11-4.istio-system.svc"
```

**It can be fixed by adding below env to the remote istiod**, 

```yaml
        env:
        - name: ISTIOD_CUSTOM_HOST
          value: istiod-1-11-4.istio-system.svc
```

I've tried to propose a PR to fix it. But maybe it's because I'm not familiar with the manifest part, I couldn't get expected result when I apply the change to `manifests/charts/istio-control/istio-discovery/templates/deployment.yaml` as below:

```yaml
{{- if not (eq $.Values.global.remotePilotAddress "") }}
          - name: ISTIOD_CUSTOM_HOST
            value: istiod{{- if not (eq .Values.revision "") }}-{{ .Values.revision }}{{- end }}
{{- end }}
```

I even found that no changes to this deployment template had any effect from the output of `./bin/istioctl manifest generate  --context="${CTX_CLUSTER2}" --revision=1-11-4 -f op_cluster2.yaml`.

### Version

```prose
./bin/istioctl version
client version: 1.11.4
istiod version: 1.11.4
istiod version: 1.9.9
data plane version: 1.11.4 (3 proxies)

istio-1.11.4 kubectl version --short
Client Version: v1.20.4
Server Version: v1.20.4
```

### Affected product area

- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
