### ISSUE TITLE
Customized Prometheus scraping configuration does not work

### ISSUE THREAD

**Issue by JWT95** [istio/istio#35942]
### Bug Description

Configuring Prometheus with the configuration from https://istio.io/latest/docs/ops/integrations/prometheus/#option-2-customized-scraping-configurations leads to Prometheus only scraping it's own istio-proxy.

Why? Because Istio has installed a listener in Envoy on 0.0.0.0:15090 that redirects all traffic to path /stats/prometheus to 127.0.0.1:15000/stats/prometheus.

This in essence means that:
- All scrapes to the envoy-stats targets are redirected to 127.0.0.1:15000/stats/prometheus
- Prometheus scraping for port 15090 does not work

### Version

```prose
$ helm list -n istio-system
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
base                    istio-system    1               2021-11-08 10:43:10.495659909 +0000 UTC deployed        base-1.11.4
istio-discovery         istio-system    1               2021-11-08 10:43:12.296518288 +0000 UTC deployed        istio-discovery-1.11.4

$ kubectl version --short
Client Version: v1.21.1
Server Version: v1.20.9

$ helm version --short
v3.6.0+g7f2df64
```

### Additional Information

Prometheus config for envoy-stats:
```yaml
- job_name: envoy-stats
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /stats/prometheus
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_container_port_name]
    separator: ;
    regex: .*-envoy-prom
    replacement: $1
    action: keep
  kubernetes_sd_configs:
  - role: pod
    follow_redirects: true
```

Istio Helm chart config:
```
$ helm get values istio-discovery -n istio-system
USER-SUPPLIED VALUES:
global:
  tag: 1.11.4
meshConfig:
  enablePrometheusMerge: false
pilot:
  autoscaleMin: 2
  replicaCount: 2
```

We can see that Prometheus thinks it is happily scraping it's targets:
![image](https://user-images.githubusercontent.com/33938988/140731218-b0fa61ca-3a43-423e-be31-ee70a947517f.png)

But we can see that the metrics it gets are only reported by the source - i.e. for the metrics scrapes as reported by the Istio Proxy in the Prometheus pod:

![image](https://user-images.githubusercontent.com/33938988/140732157-fd92ee49-c268-4a5d-b7d5-613df48e93d2.png)

This behaviour appears to be because of the following parts of the Envoy config (in the Prometheus pod):
```yaml
      static_resources:
        listeners:
          - address:
              socket_address:
                address: 0.0.0.0
                port_value: 15090
            filter_chains:
              - filters:
                  - name: envoy.filters.network.http_connection_manager
                    typed_config:
                      '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                      stat_prefix: stats
                      route_config:
                        virtual_hosts:
                          - name: backend
                            domains:
                              - '*'
                            routes:
                              - match:
                                  prefix: /stats/prometheus
                                route:
                                  cluster: prometheus_stats
                      http_filters:
                        - name: envoy.filters.http.router

...
        clusters:
          - name: prometheus_stats
            type: STATIC
            connect_timeout: 0.250s
            load_assignment:
              cluster_name: prometheus_stats
              endpoints:
                - lb_endpoints:
                    - endpoint:
                        address:
                          socket_address:
                            address: 127.0.0.1
                            port_value: 15000
```

This config redirects all metrics scrapes to the targets back to the local istio-proxy
