### ISSUE TITLE
custom metrics dimensions are appended in metric name rather than as a label

### ISSUE THREAD

**Issue by sedflix** [istio/istio#35943]
### Bug Description

I tried this telementary v2 config values using Isito operator.

```
meshConfig:
  defaultConfig:
      extraStatTags:
       - request_host
       - request_url
telemetry:
      v2:
        prometheus:
          configOverride:
            inboundSidecar:
              metrics:
                - name: requests_total
                  dimensions:
                    request_host: request.host
                    request_url: request.url_path
            outboundSidecar:
              metrics:
                - name:
                  dimensions:
                    request_host: request.host
                    request_url: request.url_path
```

But I get metrics in this format like this:
```
envoy_request_url_<some-url>_istio_requests_total
```

Complete Example:
```
 TYPE envoy_request_url_____<url>___istio_requests_total counter
envoy_request_url_____<url>___istio_requests_total{response_code="500",reporter="destination",source_workload="##",source_workload_namespace="##",source_principal="##",source_app="unknown",source_version="unknown",source_cluster="Kubernetes",destination_workload="##",destination_workload_namespace="##",destination_principal="##",destination_app="unknown",destination_version="unknown",destination_service="##",destination_service_name="##",destination_service_namespace="##,destination_cluster="Kubernetes",request_protocol="http",request_host="proteus",response_flags="-",grpc_response_status="",connection_security_policy="mutual_tls",source_canonical_service="###",destination_canonical_service="###",source_canonical_revision="##",destination_canonical_revision="##"} 1

```

### Version

```prose
$ istioctl version
client version: 1.10.0
control plane version: 1.11.3
data plane version: 1.11.3 (786 proxies)
$ kubectl version --short
Client Version: v1.22.3
Server Version: v1.21.2-eks-0389ca3
$ helm version --short
v3.2.0+ge11b7ce
```

### Additional Information

```
Running with the following config:
istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-system, kube-public, kube-node-lease, local-path-storage } AND { Namespaces: kube-system, kube-public, kube-node-lease, local-path-storage }
end-time: 2021-11-08 17:11:43.253473 +0530 IST
```
---
Istio Operator config
```
 profile: minimal
  hub: ####
  tag: 1.11.3
  meshConfig:
    rootNamespace: elenchos
    enableTracing: true
    defaultServiceExportTo:
    ###
    defaultVirtualServiceExportTo:
    ###
    defaultDestinationRuleExportTo:
    ####
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      extraStatTags:
       - request_host
       - request_url
  components:
    base:
      enabled: true
 
    pilot:
      enabled:  true
      namespace: istio-system
      k8s:
        resources:
          limits:
            cpu: 2000m
            ephemeral-storage: 350Mi
            memory: 2096Mi
          requests:
            cpu: 1000m
            ephemeral-storage: 350Mi
            memory: 2096Mi
        hpaSpec:
          maxReplicas: 9
          minReplicas: 3
        overlays:
        - kind: Deployment
          name: istiod # DEPLOYMENT
          patches:
          - path: spec.template.spec.hostNetwork
            value: true # OVERRIDDEN
  values:
    istio_cni:
      enabled: true
    telemetry:
      v2:
        prometheus:
          configOverride:
            inboundSidecar:
              metrics:
                - name: requests_total
                  dimensions:
                    request_host: request.host
                    request_url: request.url_path
            outboundSidecar:
              metrics:
                - name:
                  dimensions:
                    request_host: request.host
                    request_url: request.url_path
```
