### ISSUE TITLE
AWS NLB sometimes experiences connection errors to istio ingressgateway when pods are migrating to another nodegroup

### ISSUE THREAD

**Issue by erickimek1** [istio/istio#35964]
### Bug Description

Hello, I am currently using AWS NLB which registers istio ingressgateway pods as ip targets and it works well in normal situation.
However, AWS NLB experiences connection errors to the ingressgateway pods while migrating them from one nodegroup to another one for changing node ami and this seems due to the characteristics of AWS NLB that it can send traffic to drained targets up to 180 seconds even after completely drained.

So, I made ingressgateways pods shutdown gracefully to handle the traffic from AWS NLB after drained by using below configuration.

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  profile: default
  components:
    ingressGateways:
    - enabled: true
      k8s:
        overlays:
        - kind: Deployment
          name: istio-ingressgateway
          patches:
          - path: spec.template.spec.terminationGracePeriodSeconds
            value: 310
        podAnnotations:
          proxy.istio.io/config: '{ "drainDuration": 301s, "parentShutdownDuration":
            302s, "terminationDrainDuration": 303s }'
        replicaCount: 2
        service:
          ports:
          - name: https
            port: 443
            protocol: TCP
            targetPort: 8443
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "10"
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /healthz/ready
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "15021"
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: HTTP
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "6"
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
          service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
      name: istio-ingressgateway
```

After this change, I noticed AWS NLB still sometimes experiences connection errors to ingressgateway pods during node ami change as shown below from the access logs of AWS NLB.

```
172.16.104.101:38212 172.16.18.60:443 5006 5 0 0
172.16.188.206:50211 172.16.63.10:443 5019 18 0 0
172.16.188.206:36194 172.16.63.10:443 5012 11 0 0
172.16.188.206:52399 172.16.63.10:443 5023 23 0 0
172.16.102.194:28176 172.16.32.79:443 5003 3 0 0
...
```

It would be great if someone helps me fix this issue so that I can safely change node ami without worrying about service interruption.

FYI, I'm using below envoy filer for keeping tcp connections.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ingress-gateway-socket-options
  namespace: istio-system
spec:
  configPatches:
  - applyTo: LISTENER
    match:
      context: GATEWAY
    patch:
      operation: MERGE
      value:
        socket_options:
        - int_value: 1
          level: 1
          name: 9
          state: STATE_BOUND
        - int_value: 9
          level: 6
          name: 6
          state: STATE_BOUND
        - int_value: 120
          level: 6
          name: 4
          state: STATE_BOUND
        - int_value: 30
          level: 6
          name: 5
          state: STATE_BOUND
```

Thank you,
Eric
 

### Version

```prose
$ istioctl version
client version: 1.10.3
control plane version: 1.10.3
data plane version: 1.10.3 (16 proxies)
$ kubectl version --short
Client Version: v1.21.0
Server Version: v1.20.7-eks-d88609
```
