### ISSUE TITLE
The accessToken of skywalking cannot be sent to the sidecar

### ISSUE THREAD

**Issue by machine3** [istio/istio#35968]
### Bug Description

configmap: istio
```
apiVersion: v1
data:
  mesh: |-
    extensionProviders:
    - name: envoy.tracers.skywalking
      skywalking:
        port: 11800
        service: xxxx
        accessToken: xxxxx        # <--- Here!  When I dump config from Envoy, I can not find it.
    rootNamespace: istio-system
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
kind: ConfigMap
```

### Version

```prose
$ istioctl version
client version: 1.11.2
control plane version: 1.11.2
data plane version: 1.11.2 (15 proxies)
```
