### ISSUE TITLE
Expose autoHostRewrite in HTTPRewrite for a virtual service

### ISSUE THREAD

**Issue by christian-posta** [istio/istio#35999]
For gateway use cases, we should be able to route correctly to traffic that may not be in the mesh. We would need `autoHostRewrite` exposed for VirtualServices https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-auto-host-rewrite

**Comment by rafadesu** [comment]
Auto host rewrite in virtual service would be nice indeed. Although, it seems like rewrite: authority options would do the trick with a bit of repetition. However, I wonder if it would solve the problem I'm having.

I want to use locality failover for an external service mesh like described in this example: https://istio.io/latest/blog/2021/external-locality-failover/

However, it won't work in my case because I require the request to rewrite the host header when trying to reach each of the different endpoints to the FQDN used when describing the endpoint.
So in the blog example, I would need dynamodb.us-east-1.amazonaws.com to be used in the Host header instead of mydb.com when accessing dynamodb.us-east-1.amazonaws.com or dynamodb.us-west-1.amazonaws.com depending on he endpoint used.

I wonder if autoHostRewrite envoy option would do that automatically...

**Comment by rafadesu** [comment]
I tried adding auto_host_rewrite option using EnvoyFilters and seems to fix my issue. This is an example in case anyone is searching on how to do this:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: auto-host-rewrite
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: istio-ingressgateway
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          use_remote_address: true
  - applyTo: HTTP_ROUTE
    match:
      context: GATEWAY
      routeConfiguration:
        vhost:
          name: "mydb.com:443".  # This is the host used in the gateway entry
          route:
            action: ROUTE
    patch:
      operation: MERGE
      value:
        route:
          auto_host_rewrite: true
```
