### ISSUE TITLE
Add extra mounts to istio using operator

### ISSUE THREAD

**Issue by hairongGao** [istio/istio#35995]
### Bug Description

Not sure if I'm doing this right but I tried to add extra mounts to istio , but no errors and no volumes .

### Version

```prose
ray: ~ $ istioctl version
client version: 1.11.4
control plane version: 1.11.4
data plane version: 1.11.4 (2 proxies)
```

### Additional Information

```
ingressGateways:
    - enabled: true
      k8s:
        resources:
          requests:
            cpu: 1000m
            memory: 1Gi
        volumes:
        - name: config
          volumeSource:
            secret:
              secretName: config
        volumeMounts:
        - name:  config
          mountPath: /root/.config
```
