### ISSUE TITLE
permission denied while accessing mounts in sidecar proxies

### ISSUE THREAD

**Issue by rahulanand16nov** [istio/istio#36045]
I am using a minikube cluster with istio deployed on it. I mounted a host machine directory onto the sidecar proxy but was unable to access it due to a permissions issue. Is there a way to allow that access? maybe change sidecar config?

```
minikube start --driver=virtualbox

minikube mount $HOME:/host

istioctl install -y

kubectl label namespace default istio-injection=enabled

kubectl apply -f - <<EOF
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toystore
  labels:
    app: toystore
spec:
  selector:
    matchLabels:
      app: toystore
  template:
    metadata:
      annotations:
        sidecar.istio.io/userVolume: '[{"name": "wasm-vol", "hostPath": {"path":"/host"}}]'
        sidecar.istio.io/userVolumeMount: '[{"name": "wasm-vol", "mountPath": "/host"}]'
      labels:
        app: toystore
    spec:
      containers:
        - name: toystore
          image: quay.io/3scale/authorino:echo-api
          env:
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000
              name: http
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: toystore
spec:
  selector:
    app: toystore
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
EOF

```
```
[rahul@fedora ~]$ k exec -it deployment/toystore -c istio-proxy -- /bin/bash
istio-proxy@toystore-84d9db4fd8-2278b:/$ cd /host/
bash: cd: /host/: Permission denied
```

```
ls -l /
drwx------   1 1000 1000  466 Nov 12 06:51 host
```
