### ISSUE TITLE
Invalid IST0101 Referenced Host not Found when used with exportTo annotation

### ISSUE THREAD

**Issue by Stono** [istio/istio#36048]
### Bug Description

I think we're getting an invalid error on istioctl.  It is claiming that the service doesn't exist - but it does.  It seems to be due to the `networking.istio.io/exportTo` annotation as when i remove that, it is fine.

Given a `VirtualService` like this:

```
spec:
  hosts:
  - admin.elastic-heartbeat.testing.k8.atcloud.io
  http:
  - route:
    - destination:
        host: admin.elastic-heartbeat.svc.cluster.local
      weight: 100
    timeout: 30s
```

And a service like this:
```
metadata:
  name: admin
  annotations:
    networking.istio.io/exportTo: some-other-namespace
```

Istioctl validate gives an error:
```
Error [IST0101] (VirtualService elastic-heartbeat/elastic-heartbeat-admin) Referenced host not found: "admin.elastic-heartbeat.svc.cluster.local"
```

### Version

```prose
1.12-beta2
```
