### ISSUE TITLE
Verifying AWS Load Balancer OIDC Keys with Istio/Envoy

### ISSUE THREAD

**Issue by diranged** [istio/istio#36067]
### Bug Description

First off, I am not sure that this is a bug, or perhaps a lack of documentation, or perhaps a missing feature. That said, I believe this is a widely desired use case, and I've spent a few days trying to figure this out without much luck.

**Scenario**

We use AWS Load Balancers with native [OIDC integration to authenticate employees through Okta](https://docs.aws.amazon.com/en_en/elasticloadbalancing/latest/application/listener-authenticate-users.html)  before passing them to the backend Istio IngressGateways. This works, but we want to also pass user information through to Istio so that we can make use of `AuthorizationPolicies` to grant narrower scopes of access to individual applications.

**Problem**

Amazon provides two headers back - `x-amzn-oidc-data` and `x-amzn-oidc-accesstoken`. These are in the form of JWTs and are signed and populated differently.

**`x-amzn-oidc-data`**: This token is signed by AWS directly and they provide the Key at a downloadable URL (`https://public-keys.auth.elb.region.amazonaws.com/key-id`), but unfortunately they do not publish the key in JWKS format, but instead they publish it in raw PEM format. The thing about this token is that this is the token that AWS fully populates with any of your claims - like `groups`, `email`, etc. Any data returned by the `userinfo` endpoint 

```
$ curl https://public-keys.auth.elb.us-west-2.amazonaws.com/004cb65f-3ef7-4efa-a149-4f19b4c754c8
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEGzBU1b4vFhEmqNIRydHDGh1Pqv5e
YDCjrENOdlNKzZZCLNbx3Xb9M+Z8a0HsV0Ph9brVTtOjK7yO4jpQNCxskQ==
-----END PUBLIC KEY-----
```

Example decoding of the payload:
```json
{
  "sub": "00u6797q09CIFHAKIOML",
  "name": "Matt",
  "locale": "en-US",
  "email": "matt@example.com",
  "preferred_username": "matt@example.com",
  "given_name": "Matt",
  "family_name": "...",
  "zoneinfo": "America/Los_Angeles",
  "updated_at": 1633361545,
  "email_verified": true,
  "groups": [
    "group-a",
    "users",
    "employees",
    "...",
  ],
  "exp": 1636768363,
  "iss": "https://example.okta.com/oauth2/default"
}
```

Unfortunately, there seems to be no way to construct a `RequestAuthentication` resource that understands the Public Key above:

```yaml
kind: RequestAuthentication
metadata:
  name: oidc-jwt-authentication
  namespace: istio-system
spec:
  jwtRules:
  - issuer: https://example.okta.com/oauth2/default
    jwks: |-
       .... there is no way to just put  a Public Key in here ....
    forwardOriginalToken: true
    fromHeaders:
    - name: x-amzn-oidc-data
```

**`x-amzn-oidc-accesstoken`**: This header includes the Key and Payload and Signature for the original request to the backend OIDC server. If you decode the Key you get a KeyId that refers to a key signed by the original request to Okta (in our case). The _problem_ with this is that it's the initial claim request to Okta without any of the scopes that we want (profile, groups, etc). That means that we can use it to verify that the request was indeed signed by Okta - but we cannot gleam any further information about the user.

Decoding the first part of the JWT, you get a KeyId that refers to a Key served up by Okta:

```bash
$ echo 'eyJraWQiOiI2SXE1QkpTYVpOSjRURllFRUY1UVEtWktLaEFkTEpjT3lnR21jcWJxeVlJIiwiYWxnIjoiUlMyNTYifQ' | base64 -d 
{"kid":"6Iq5BJSaZNJ4TFYEEF5QQ-ZKKhAdLJcOygGmcqbqyYI","alg":"RS256"...
$ curl -s https://example.okta.com/oauth2/default/v1/keys | jq . 
{
  "keys": [
    {
      "kty": "RSA",
      "alg": "RS256",
      "kid": "6Iq5BJSaZNJ4TFYEEF5QQ-ZKKhAdLJcOygGmcqbqyYI",
      "use": "sig",
      "e": "AQAB",
      "n": "..."
    },
```

Decoding the payload, we get a very tiny payload:
```json
{
  "ver": 1,
  "jti": "AT.UcGDT2S0ixRDQk5o6xbmwiJZjMvf7_Wb5zvQEYnpMXs",
  "iss": "https://example.okta.com/oauth2/default",
  "aud": "api://k8s",
  "iat": 1636769436,
  "exp": 1636812636,
  "cid": "0oa1jrl1ag1GTea351d8",
  "uid": "...",
  "scp": [
    "groups",
    "openid",
    "profile",
    "email"
  ],
  "sub": "matt@example.com"
}
```

So with the above data, we can construct a "working" but incomplete system where we can validate the issuer and the user email address, but thats it:
```yaml
kind: RequestAuthentication
metadata:
  name: oidc-jwt-authentication
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: private-ingressgateway
  jwtRules:
  - issuer: https://example.okta.com/oauth2/default
    jwksUri: https://example.okta.com/oauth2/default/v1/keys
    forwardOriginalToken: true
    fromHeaders:
    - name: x-amzn-oidc-accesstoken
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: oidc-jwt-authorization
  namespace: istio-system
spec:
  action: ALLOW
  rules:
    - from:
      - source:
          requestPrincipals:
            - https://example.okta.com/oauth2/default/*
      when:
        - key: request.auth.claims[iss]
          values: ["https://example.okta.com/oauth2/default"]
```

**Things I have tried/Read Up On**

_Getting a JWKS blob_:
I have engaged AWS support looking for a JWKS-style data blob we can use, but they have informed me that one is not available.

_Converting the PEM to a JWKS blob_:
I am out of my element here, but AWS tells me it is impossible to convert the public key contents that they do expose into a working JWKS blob.

_Looking for a custom Envoy config_:
I thought perhaps that Envoy would support directly passing in the Public Key and we could generate our own EnvoyFilter.. but my read up on https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto and I do not see that as an available option.

_Previous Issues_:
I read https://github.com/istio/istio/issues/17300 - where someone describes almost exactly the same problem as me, but it is an old thread and their answer refers to a previous mixin strategy that is no longer functional. We are using the latest Istio version.

**The surprisingly broken Blog post**

I found this (https://zdenek-papez.medium.com/istio-authorization-using-okta-user-groups-in-jwt-claims-behind-aws-application-load-balancer-191f26779cad) blog - and I thought *bingo, I've got it!*... But after hours of trying, I cannot replicate their success. I was able to deal with authenticating the user, but there  seemed to be no way to get the userinfo into the session.

In particular, I am confused by the fact that they use the `x-amzn-oidc-accesstoken` header. Given that the value has no user group info in it, it seems almost like the poster was able to get Istio to go and make its own subsequent call to the `userinfo` endpoint to populate the data. Do you think that is possible? If it is not, then how did the author make this work?

**Help Me :)**

So basically, I have a few questions..

_1. Is there some way to use the public key and the fully populated `x-amzn-oidc-data` header?_ If there is some way where we can write an EnvoyFilter that is able to go download the Public Key perhaps and validate the signature for us (like overriding the validate-signature function somewhere?) that would work and would be in-line with the instructions supplied by AWS at https://docs.aws.amazon.com/en_en/elasticloadbalancing/latest/application/listener-authenticate-users.html#user-claims-encoding.

_2. Can we parse the email/groups ourself and then set them in the request context?_ Less ideal, but could we write an `EnvoyFilter` that parses out the email/group information ourselves and then is able to populate the `request.auth` object? [This guy's Lua script](https://gist.github.com/inaiat/02bf5d11732d8e4d7b7546399a3a49af) actually works to do the JWT parsing and validation, and then sets a header... but I don't know what headers we would set (or other functions to call) to control the `request.auth` context.

_3. Is there some way to make Istio do a secondary call to the `userinfo` endpoint?_ Could AWS do the initial auth, and then we configure Istio to make a secondary call to Okta to get the userinfo?

### Version

```prose
$ istioctl version
client version: 1.11.4
control plane version: 1.11.1
data plane version: 1.11.1 (14 proxies)

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```
```


### Additional Information

_No response_
