### ISSUE TITLE
Istio Operator Doesn't Honor Volumes and Volume Mounts Directives

### ISSUE THREAD

**Issue by hi-artem** [istio/istio#36066]
### Bug Description

As the title describes, Istio Operator doesn't honor some of the directives from IstioOperatorSpec. We tested it with Ingress Gateway, so cannot comment on other components. 

How to replicate?

1. Create configmap

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-custom-bootstrap-config
  namespace: istio-system
data:
  custom_bootstrap.json: |
    {
      "layered_runtime": {
        "layers": [
         {"name": "static_layer_0",
          "static_layer": {
             "overload": {
               "global_downstream_max_connections": 250000
             }
          }}
        ]
      }
    }
```

2. Create config for IstioOperator

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: ingressgateway
spec:
  profile: empty
  revision: 1-10-3
  components:
    ingressGateways:
      - enabled: true
        k8s:
          env:
          - name: ISTIO_BOOTSTRAP_OVERRIDE
            value: /etc/istio/custom-bootstrap/custom_bootstrap.json
          volumeMounts:
          - mountPath: /etc/istio/custom-bootstrap
            name: custom-bootstrap-volume
            readOnly: true
          volumes:
          - volumeSource:
              configMap:
                localObjectReference:
                  name: istio-custom-bootstrap-config
                defaultMode: 420
                optional: false
```

Apply both, and verify that created Istio Gateway deployment don't have volumes nor volumemounts.

There are no visible errors in the operator logs and new resources are created as they should, except for missing volumes and volume mounts.

### Version

```prose
$ operator version
version.BuildInfo{Version:"1.10.3-tetratefips-v0", GitRevision:"7e5abe0f6bef3c121aca686eb48ab46ec4dc966e", GolangVersion:"go1.16.4b7", BuildStatus:"Clean", GitTag:"1.10.3-tetratefips-v0"}
```
