### ISSUE TITLE
RBAC: Access denied between istio and non-istio namespaces when adding Authorization Policy 

### ISSUE THREAD

**Issue by MrVentzi** [istio/istio#36119]
I have a weird scenario with Istio Authorization Policy. 

We use Istio inside our clusters, but some of our workloads don't have the sidecars. 

The problem is this. Imagine `namespaceA` doesn't have istio injection and `namespaceB` has istio injection. 

When we have NO Authorization Policies defined in `namespaceB` , we can cURL (for testing purposes) from a pod in namespaceA. 

However, when we add Authorization Policies in namespaceB , we cannot reach it from namespaceA and we get `RBAC: access denied`

E.g. adding the following
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-nothing
  namespace: namespaceB
spec: {}
```
and
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: myapp-access-allow
  namespace: namespaceB
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/namespaceA/sa/default
        - cluster.local/ns/istio-system/sa/istio-level4-internal-ingressgateway-service-account
  selector:
    matchLabels:
      appType: myapp
```

Note: the `matchLabels` is correct.

Now that we get `RBAC: Access denied` we check the logs on the side car and can see this:
```
[2021-11-17T17:24:26.655Z] "GET /myapp/test/ HTTP/1.1" 403 - rbac_access_denied_matched_policy[none] - "-" 0 19 0 - "-" "curl/7.61.1" "1750c690-ace0-424f-a815-889f683f94eb" "myapp.namespaceB.svc.cluster.local:8080" "-" inbound|8080|| - 10.32.64.14:8080 10.32.64.22:50846 - -
```

If we enable istio (add `istio-injection=enabled` label) on `namespaceA` and just restart the pods, everything seems to start working as expected.

If we get rid of the istio inside `namespaceA` then it stops again.
If we then get rid of the `AuthorizationPolicy` inside `namespaceB` then it starts working again (while keeping `namespaceA` without istio)

So the question is, is this expected behavior, and if it is, how do we overcome it?

Considering the principals are kubernetes service accounts, it sounds like it should work?

We are on Istio 1.9.3 but I assume it will be the same on later versions.
