### ISSUE TITLE
error `virtual_hosts` name in inbound `route_config`

### ISSUE THREAD

**Issue by dozer47528** [istio/istio#36112]
### Bug Description

since 1.8.0 (from this pr https://github.com/istio/istio/pull/30979 ), istio will use Service TargetPort to generate inbound listener, but the `virtual_hosts` name is still using Service Port. It's a bug or not?

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: http
    targetPort: 80
  selector:
    app: nginx
```
```json
{
    "route_config": {
        "name": "inbound|80||",
        "virtual_hosts": [
            {
                "name": "inbound|http|8080",
                "domains": [
                    "*"
                ],
                "routes": [
                    {
                        "match": {
                            "prefix": "/"
                        },
                        "route": {
                            "cluster": "inbound|80||",
                            "timeout": "0s",
                            "max_stream_duration": {
                                "max_stream_duration": "0s",
                                "grpc_timeout_header_max": "0s"
                            }
                        },
                        "decorator": {
                            "operation": "nginx.default.svc.cluster.local:8080/*"
                        },
                        "name": "default"
                    }
                ]
            }
        ],
        "validate_clusters": false
    }
}
```

`virtual_hosts[0].name` is `inbound|http|8080`, I think it should be `inbound|http|80`

### Version

```prose
$ istioctl version
client version: 1.10.4
control plane version: 1.10.4
data plane version: 1.10.4 (1 proxies)

$ kubectl version --short
Client Version: v1.21.5
Server Version: v1.21.5
```

**Comment by howardjohn** [comment]
Probably. Does it impact anything though?

**Comment by dozer47528** [comment]
@howardjohn 
It's a long story, we are using Istio `EnvoyFilter` for replace thie `virtual_host` by name matching.

This is our use case. In order to split inbound envoy metrics by path, we replaced the default `virtual_host` and route requests into different cluster by `path`.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: "some-envoyfilter"
spec:
  configPatches:
  - applyTo: VIRTUAL_HOST
    match:
      context: SIDECAR_INBOUND
      routeConfiguration:
        portNumber: 80
        vhost:
          name: inbound|http|80
    patch:
      operation: REMOVE
  - applyTo: VIRTUAL_HOST
    match:
      context: SIDECAR_INBOUND
      routeConfiguration:
        portNumber: 80
    patch:
      operation: ADD
      value:
        domains:
        - '*'
        name: inbound|http|80
        routes:
        - match:
            prefix: /path1
          name: cluster-1
          route:
            cluster: inbound|80|http|cluster-1
            timeout: 0s
        - match:
            prefix: /path2
          name: cluster-2
          route:
            cluster: inbound|80|http|cluster-2
            timeout: 0s
  workloadSelector:
    labels:
      app: "some-app"
```

But when the Service Port and Target Port is different, this `EnvoyFilter` can not match the default `virtual_host`.
