### ISSUE TITLE
Envoy is modifying encrypted traffic

### ISSUE THREAD

**Issue by Arsen-Uulu** [istio/istio#36149]
### Bug Description

I have Service A and Service B both on mTLS. (not ISTIO_MUTUAL)

I have following PeerAuthentication Policy

```
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
spec:
  mtls:
    mode: DISABLE
```

when my Service A is making outbound call to Service B, traffic is already encrypted, I expect sidecar A to just forward the traffic to originalDst, but instead on Sidecar B I see  
```
400 DPE http 1.codec error
```

### Version

```prose
client version: 1.11.0
control plane version: 1.11.0
data plane version: 1.11.0 (4 proxies)

kubernetes version 1.19
```

**Comment by bianpengyuan** [comment]
Do you name your service port with http prefix?

**Comment by Arsen-Uulu** [comment]
@bianpengyuan do you mean the K8s Service? 
If so, then yes, my ports have names with http prefix .

```
  - name: https-primary
    port: 443
    protocol: TCP
    targetPort: 8000
```

**Comment by Arsen-Uulu** [comment]
@bianpengyuan Looks like pilot-agent bootstraps envoy depending how you name your Service port. 
I removed https and http, and left just primary, and I see that envoy listener 0.0.0.0_15006 was bootstrap properly. 
and this was added 

```
                            "forwardClientCertDetails": "APPEND_FORWARD",
                            "setCurrentClientCertDetails": {
                                "subject": true,
                                "dns": true,
                                "uri": true
                            },
```

**Comment by Arsen-Uulu** [comment]
@bianpengyuan Do you know if it's possible to decrypt the outbound traffic ? 
Mount Server certs on envoy pod and configure DownStreamTls context with EnvoyFilter API?

**Comment by bianpengyuan** [comment]
> do you mean the K8s Service?

I mean the port name of service B that you are sending traffic to. Do you intend to terminate TLS at service B application workload or Service B sidecar proxy?  `https` makes sense and envoy should just pass through the traffic through and do not try to decode it as http.

Removing the name prefixes will enable auto detection of traffic protocol, which will make the virtual inbound listener (15006) contain with two chains (one for passthrough tcp traffic, and one for http).

**Comment by Arsen-Uulu** [comment]
@bianpengyuan  I intend to terminate TLS at Service A sidecar proxy

Service A --> TLS --> Envoy Proxy of Service A --> mTLS --> Envoy Proxy of Service B --> TLS --> Service B

https://github.com/istio/istio/issues/21368 similar to this issue, but in my case is mTLS.

**Comment by bianpengyuan** [comment]
How do you configure that? I don't think istio support this use case right now.

**Comment by bianpengyuan** [comment]
AFAIK Some work is going on to support this. https://github.com/istio/istio/issues/35111

**Comment by Arsen-Uulu** [comment]
@bianpengyuan 
Like how gateway has this feature but not sidecar? 
Gateway is an instance of Envoy anyway. 

I was thinking to implement that with use of EnvoyFilter API to configure the outbound listener(15001) with DownStreamTls context. When traffic is intercepted on IPTABLES and forwarded to envoy outbound listener, since true client is still my app right? so it becomes downstream to Envoy, could this work?

**Comment by bianpengyuan** [comment]
I mean the feature is not supported by Istio API. You can probably come up something that is working with EnvoyFilter, but there will be no guarantee on stability or support on the solution because EnvoyFilter is a breaking glass API.

**Comment by Arsen-Uulu** [comment]
@bianpengyuan Understood, but this could work right? 

I understand that I won't open any issue because it's not natively supported via Istio api and I need to do this at my own risk.

**Comment by bianpengyuan** [comment]
Yes it should be able to work.

**Comment by Arsen-Uulu** [comment]
@bianpengyuan 

For this to work, should I configure the 0.0.0.0_15001 listener or 0.0.0.0_443 listener?

As far as I understood that envoy will hand of the traffic to the best matching virtualListener correct? 

so my app makes outbound call to another app on port 443 and what I expect is envoy handing over  the request to 0.0.0.0:443 listener correct?

I'll be honest configuring the 15001 with downStreamTls context didn't work.

**Comment by bianpengyuan** [comment]
Yeah I think downstreamTLSContext should be added to 443 listener.

**Comment by Arsen-Uulu** [comment]
When I create my `VirtualService` for my app, by default Istio adding it to RouteName `80`, how do I enforce it to add to routeName 443?

**Comment by bianpengyuan** [comment]
Please refer to the official guide for this: https://istio.io/latest/docs/reference/config/networking/virtual-service/#Destination

**Comment by Arsen-Uulu** [comment]
Hi @bianpengyuan , I hope you had a great holiday weekend. 

I added downstreamTlsContext to 443 listener and I still see encrypted traffic. 

for some reason is not terminating the TLS.

I shared my EnvoyFilter code bellow, but do you think I need to add a new FilterChainMatch ?


```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: test
spec:
  configPatches:
    - applyTo: FILTER_CHAIN
      match:
        context: SIDECAR_OUTBOUND
        listener:
          name: 0.0.0.0_443
          filterChain:
            transportProtocol: "raw_buffer"
      patch:
        operation: MERGE
        value:
          transport_socket:
            name: tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              common_tls_context:
                tls_certificates:
                  - certificate_chain:
                      filename: /etc/certs/server/cert.pem
                    private_key:
                      filename: /etc/certs/server/key.pem
                validation_context:
                  trusted_ca:
                    filename: /etc/certs/server/ca-chain.cert.pem
```
