### ISSUE TITLE
Local rate limits per route/path

### ISSUE THREAD

**Issue by macpak** [istio/istio#36153]
Hi,

I've a an application that exposes some API (asp.net core). I'd like to apply local rate limit per path, for example:
- x requests for route **/product/list**
- y requests for route **/product/{id}**
So basically all those routes are exposed by the same API (thus one k8s service + one virtualservice) . 
I've tried to follow documentation available [here](https://istio.io/latest/docs/tasks/policy-enforcement/rate-limit/) , however there's no example of how to achieve (if possible) the scenario I've described.

**Comment by zirain** [comment]
@macpak here's more detail [Using rate limit descriptors for local rate limiting](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/local_rate_limit_filter#using-rate-limit-descriptors-for-local-rate-limiting)

**Comment by macpak** [comment]
Thanks @zirain .
One thing that still doesn't work for me is how to ignore query string parameters, so for example /path and /path?a=b should have the same rate limit. I've tried to follow [this](https://dev.to/tresmonauten/setup-an-ingress-rate-limiter-with-envoy-and-istio-1i9g) article, but cannot make it work. 
Do you maybe have an example of that ?

**Comment by zirain** [comment]
> Thanks @zirain . One thing that still doesn't work for me is how to ignore query string parameters, so for example /path and /path?a=b should have the same rate limit. I've tried to follow [this](https://dev.to/tresmonauten/setup-an-ingress-rate-limiter-with-envoy-and-istio-1i9g) article, but cannot make it work. Do you maybe have an example of that ?

try something as follow:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-local-ratelimit-svc
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: productpage
  configPatches:
    - applyTo: HTTP_FILTER
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter
              token_bucket:
                max_tokens: 10
                tokens_per_fill: 10
                fill_interval: 60s
              filter_enabled:
                runtime_key: local_rate_limit_enabled
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              filter_enforced:
                runtime_key: local_rate_limit_enforced
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              response_headers_to_add:
                - append: false
                  header:
                    key: x-local-rate-limit
                    value: 'true'
              descriptors:
                - entries:
                  - key: path
                    value: /productpage
                  token_bucket:
                    max_tokens: 10
                    tokens_per_fill: 10
                    fill_interval: 60s
```

**Comment by BrianEFox** [comment]
What does **NOT** appear to be supported by Istio (though is in the Envoy spec) is the ability to support **/product/{id}**. ALL of the examples of local rate limiting use the `request_headers` / static `path` value approach. However, `entries:` `value:` strings do not support wildcards. The prescribed way to support regex paths (**and the way that works for global rate limiting**) is via `header_value_match` as follows:
```
            - actions:
              - header_value_match:
                  descriptor_value: user_uuid_per_org
                  headers:
                  - name: ":path"
                    safe_regex_match:
                      google_re2: {}
                      regex: "/org/[A-Za-z0-9_\\-]+/user/[A-Za-z0-9_\\-]+"
                ...
                descriptors:
                - entries:
                  - key: header_match
                    value: user_uuid_per_org
                  token_bucket:
                    max_tokens: 10
                    tokens_per_fill: 10
                    fill_interval: 60s
```
Unfortunately, this does NOT work: no rate limiting is applied to the `/org/{id}/user/{id}` path. In addition to `safe_regex_match`, I have also tried both `string_match` and `prefix_match`, neither of which applied any rate limiting. The only `header_value_match` option that seems to be supported is `exact_match`, which offers no advantage over the `request_headers` approach mentioned above.

As near as I can tell, **Istio does not currently support local rate limiting for paths which contain an ID**. If true, this makes local rate limiting basically unusable for most API implementations. If regex paths are supported somehow, please include an example in the documentation, as currently none exist.
