### ISSUE TITLE
Issue about overlapping match

### ISSUE THREAD

**Issue by chenhy97** [istio/istio#36156]
I want to route the requests according to their url and I wrote the `VirtualService` configuration shown as below.
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grpc-cart-1
spec:
  hosts:
    - cartservice
  http:
    - match:
      - port: 7070
      - uri:
           exact: /EmptyCart
      route:
      - destination:
          host: cartservice
          subset: v2
        weight: 100
    - match:
      - port: 7070
      - uri:
           exact: /GetCart
      route:
      - destination:
          host: cartservice
          subset: v1
        weight: 100
    - match:
      - port: 7070
      - uri:
           exact: /AddItem
      route:
      - destination:
          host: cartservice
          subset: v2
        weight: 100
```
However, it do not work. And I get the error:
```
Warning: virtualService rule #1 match #0 is not used (duplicate/overlapping match in rule #0)
Warning: virtualService rule #2 match #0 is not used (duplicate/overlapping match in rule #0)
virtualservice.networking.istio.io/grpc-cart-1 configured
```
I want to know why.
