### ISSUE TITLE
EnvoyFilter stops working after upgrade from Istio 1.3.5 to 1.11.1

### ISSUE THREAD

**Issue by zvazquez** [istio/istio#36172]
### Bug Description

Hi,

We are using EnvoyFilter to enable SAML2 authentication with Oauth2Proxy and Dex, looking to redirect the calls coming through the instio-ingressgatey to be check by Oauth2Proxy if the SAML2 authentication was establish, if not redirect to Dex to start the SAML2 authentication process with our IdP and the request just going straight to the service, in this case Kiali.

The old EnvoyFilter configuration was as follow:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: admin-envoy-filter
  namespace: istio-system
  labels:
    cxm.iac: admin
spec:
  workloadLabels:
    istio: ingressgateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          portNumber: 443
      patch:
        operation: INSERT_BEFORE
        value:
          name: "envoy.ext_authz"
          config:
            http_service:
              server_uri:
                uri: http://oauthproxy-service.admin.svc.cluster.local:4180
                cluster: outbound|4180||oauthproxy-service.admin.svc.cluster.local
                timeout: 1.5s
              allowed_authorization_headers: ["content-type"]
              authorizationRequest:
                allowedHeaders:
                  patterns:
                  - exact: "cookie"
                  - exact: "x-forwarded-access-token"
                  - exact: "x-forwarded-user"
                  - exact: "x-forwarded-email"
                  - exact: "authorization"
                  - exact: "x-forwarded-proto"
                  - exact: "proxy-authorization"
                  - exact: "user-agent"
                  - exact: "x-forwarded-host"
                  - exact: "user-agent"
                  - exact: "x-forwarded-host"
                  - exact: "from"
                  - exact: "x-forwarded-for"
                  - exact: "authorization"
                  - exact: "accept"
                  - exact: "content-type"
                  - prefix: "x-forwarded"
                  - prefix: "x-auth-request"
              authorizationResponse:
                allowedClientHeaders:
                  patterns:
                  - exact: location
                  - exact: proxy-authenticate
                  - exact: set-cookie
                  - exact: "content-type"
                  - exact: "authorization"
                  - exact: "www-authenticate"
                  - prefix: "x-forwarded"
                  - prefix: "x-auth-request"
                allowedUpstreamHeaders:
                  patterns:
                  - exact: "location"
                  - exact: "proxy-authenticate"
                  - exact: "set-cookie"
                  - exact: "authorization"
                  - exact: "www-authenticate"
                  - prefix: "x-forwarded"
                  - prefix: "x-auth-request"
    - applyTo: HTTP_ROUTE
      match:
        context: GATEWAY
        routeConfiguration:
          portNumber: 443
          vhost:
            name: "kiali.domain.com:443"
      patch:
        operation: MERGE
        value:
          typed_per_filter_config:
            envoy.ext_authz:
              "@type": type.googleapis.com/google.protobuf.Struct
              value:
                disabled: true
```

The new EnvoyFilter configuration is as follow:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: kiali-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              # In Istio 1.6.4 this is the first filter. The examples showing insertion
              # after some other authorization filter or not showing where to insert
              # the filter at all didn't work for me. Istio just failed to insert the
              # filter (silently) and moved on.
              name: istio.metadata_exchange
          # The filter should catch traffic to the service/application.
          sni: kiali.domain.com
    patch:
      operation: INSERT_AFTER
      value:
        name: envoy.filters.http.ext_authz
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
          http_service:
            authorizationRequest:
              allowedHeaders:
                patterns:
                - exact: accept
                - exact: authorization
                - exact: cookie
                - exact: from
                - exact: proxy-authorization
                - exact: user-agent
                - exact: x-forwarded-access-token
                - exact: x-forwarded-email
                - exact: x-forwarded-for
                - exact: x-forwarded-host
                - exact: x-forwarded-proto
                - exact: x-forwarded-user
                - prefix: x-auth-request
                - prefix: x-forwarded
            authorizationResponse:
              allowedClientHeaders:
                patterns:
                - exact: authorization
                - exact: location
                - exact: proxy-authenticate
                - exact: set-cookie
                - exact: www-authenticate
                - prefix: x-auth-request
                - prefix: x-forwarded
              allowedUpstreamHeaders:
                patterns:
                - exact: authorization
                - exact: location
                - exact: proxy-authenticate
                - exact: set-cookie
                - exact: www-authenticate
                - prefix: x-auth-request
                - prefix: x-forwarded
              server_uri:
                cluster: outbound|4180||oauthproxy-service.admin.svc.cluster.local
                timeout: 1.5s
                uri: 'https://oauthproxy-service.admin.svc.cluster.local:4180'
```

We used this [blog ](https://www.paraesthesia.com/archive/2020/09/03/setting-up-oauth2-proxy-with-istio/)from Travis Ilig to get into this configuration.

Here is the configuration of the gateway, virtual service and destination rule:

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: kiali-gt
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - 'kiali.domain.com'
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - 'kiali.domain.com'
      port:
        name: https
        number: 443
        protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: kiali-dr
  namespace: istio-system
spec:
  host: kiali.istio-system.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali-vs
  namespace: istio-system
spec:
  gateways:
  - kiali-gt
  hosts:
    - 'kiali.domain.com'
  http:
    - route:
        - destination:
            host: kiali
            port:
              number: 20001
```
Following some of the recommendations from [this ](https://github.com/istio/istio/issues/24480) issue, I executed the command ```istioctl pc```, but it seems the gateway configuration is not created properly, sinze I do not see the "envoy.filters.http.ext_authz".

```
istioctl pc listener istio-ingressgateway-bb55498d6-2mn5q.istio-system -o json | Select-String -Pattern auth

                                        "tag": "istio.authorization.dry_run.allow_policy.name",
                                        "tag": "istio.authorization.dry_run.allow_policy.result",
                                        "tag": "istio.authorization.dry_run.deny_policy.name",
                                        "tag": "istio.authorization.dry_run.deny_policy.result",
                                                "authority": "%REQ(:AUTHORITY)%",
                                        "tag": "istio.authorization.dry_run.allow_policy.name",
                                        "tag": "istio.authorization.dry_run.allow_policy.result",
                                        "tag": "istio.authorization.dry_run.deny_policy.name",
                                                "authority": "%REQ(:AUTHORITY)%",
                            "authority": "%REQ(:AUTHORITY)%",


istioctl pc listener istio-ingressgateway-bb55498d6-m84wf.istio-system -o json | Select-String -Pattern auth

                                        "tag": "istio.authorization.dry_run.allow_policy.name",
                                        "tag": "istio.authorization.dry_run.allow_policy.result",
                                        "tag": "istio.authorization.dry_run.deny_policy.name",
                                        "tag": "istio.authorization.dry_run.deny_policy.result",
                                                "authority": "%REQ(:AUTHORITY)%",
                            "authority": "%REQ(:AUTHORITY)%",
                                        "tag": "istio.authorization.dry_run.allow_policy.name",
                                        "tag": "istio.authorization.dry_run.allow_policy.result",
                                        "tag": "istio.authorization.dry_run.deny_policy.name",
                                        "tag": "istio.authorization.dry_run.deny_policy.result",
                                                "authority": "%REQ(:AUTHORITY)%",
                            "authority": "%REQ(:AUTHORITY)%",
```

Could you help us to understand what could be wrong and the reason why the EnvoyFilter is not being pickup, at the end the intention is to expose services in the Kubernetes cluster, by example Kiali or any other service to be protected by SAML2 
authentication.

We started reading about the external authorization using "AuthorizationPolicy" mentioned [here](https://istio.io/latest/docs/tasks/security/authorization/authz-custom/), but seems to be experimental.

Thanks in advance for your help,

Zareh

### Version

```prose
istioctl version     
client version: 1.11.1
control plane version: 1.11.1
data plane version: 1.11.1 (17 proxies)

kubectl version --short
Client Version: v1.19.12
Server Version: v1.19.13
```
