### ISSUE TITLE
Issue with http2

### ISSUE THREAD

**Issue by illidan80** [istio/istio#36185]
### Bug Description

I have a web application, which needs to accept both regular REST requests and Websockets connections. For RESTs, I want to enable HTTP2. For WS, since it cannot operate over HTTP2 (correct?), I had to support HTTP 1.1. So, for single container I need to support both HTTP2 and HTTP 1.1 side by side. Web server itself does supports both of the protocols.

In order to accomplish what I need, I created two Kubernetes services:

One for WS support (HTTP 1.1):

```
kind: Service
apiVersion: v1
metadata:
  name: tenant-portal-ws
  namespace: digi
spec:
  selector:
    app: tenant-portal
  ports:
    - protocol: TCP
      name: tcp
      port: 80
      targetPort: 8080
```

And other one for REST calls (HTTP2):

```
kind: Service
apiVersion: v1
metadata:
  name: tenant-portal
  namespace: digi
spec:
  selector:
    app: tenant-portal
  ports:
    - protocol: TCP
      appProtocol: http2
      name: tcp
      port: 80
      targetPort: 8080
```

Also, I configured my VirtualService to send all requests starting with "/ws" to service for Websockets, all the rest to the second one:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tenant-portal-ingress
  namespace: digi
spec:
  hosts:
    - "portal.digi.service"
  gateways:
    - digigateway
  http:
    - name: "ws-routing"
      match:
        - uri:
            prefix: "/ws"
      route:
      - destination:
          port:
            number: 80
          host: tenant-portal-ws.digi.svc.cluster.local
    - name: "actual-routing"
      route:
      - destination:
          port:
            number: 80
          host: tenant-portal.digi.svc.cluster.local
```

**Expected**: WS calls will be handled over HTTP 1.1, REST calls will be handled over HTTP2
**Actual**: REST calls handled as desired over HTTP2, but WS calls fail with code 503

I enabled Envoy logs and here are what I get:

Successful request for REST:

`[2021-11-21T13:47:58.648Z] "POST /api/common/authentication/token HTTP/2" 200 - via_upstream - "-" 189 492 32 31 "10.1.98.1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36" "0a0f8391-5f20-4dd6-b898-4a8a1357ca6e" "portal.digi.service" "127.0.0.1:8080" inbound|8080|| 127.0.0.1:54224 10.1.98.179:8080 10.1.98.1:0 outbound_.80_._.tenant-portal.digi.svc.cluster.local default`

Failed request for WS:

`[2021-11-21T13:47:58.693Z] "GET /ws/ws2 HTTP/1.1" 503 UR upstream_reset_before_response_started{remote_reset} - "-" 0 85 1 - "10.1.98.1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36" "4a0965f5-bf89-492a-9a42-baad9db6f220" "portal.digi.service" "127.0.0.1:8080" inbound|8080|| 127.0.0.1:54228 10.1.98.179:8080 10.1.98.1:0 outbound_.80_._.tenant-portal-ws.digi.svc.cluster.local default`

**Interesting**, that if I changing appProtocol of "tenant-portal" service to "http" value - everything works fine (all requests served over HTTP 1.1)

Is it a bug or I doing something wrong?

### Version

```prose
Istio 1.9
Client Version: v1.21.6-3+dd57cd4fdc581a
Server Version: v1.21.6-3+dd57cd4fdc581a
```
