### ISSUE TITLE
Create convenience tool to convert v1alpha1 configs to v1alpha3

### ISSUE THREAD

**Issue by ijsnellf** [istio/istio#3621]
Create a tool to convert v1alpha1 configs to v1alpha2 configs to make v1alpha1 deprecation less painful. 

Considerations:
1. For convenience only. Should be able to handle the majority of configs, but not all edge cases. The tool should warn the user in these cases ideally.
1. Not all sets of v1alpha1 config can be converted perfectly. Warn when this happens.
1. Output should just be a _starting point_ for the v1alpha3 configs. Users will probably want to clean up and rename generated names etc.

Part of https://github.com/istio/istio/issues/1925

**Comment by ijsnellf** [comment]
cc @rshriram

**Comment by ldemailly** [comment]
that'd be awesome ! and tbh required for just before whenever we stop supporting alpha1

**Comment by esnible** [comment]
I tried to convert https://github.com/retroryan/istio-workshop/blob/master/guestbook/route-rule-80-20.yaml using `istioctl experimental convert-networking-config` and ran into two problems.

First the output RouteRule is incorrect because the subset name is invalid because it contains a period:

```
Error: 2 errors occurred:

* output config(s) are invalid: subnet name is invalid: version-1.0
* output config(s) are invalid: subnet name is invalid: version-2.0
```

Even if that is fixed a VirtualService cannot represent the old RouteRule because it refers to an undefined subset.  To make it work we need something like the following to be generated in addition to the VirtualService.

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews-destination
spec:
  host: reviews
  subsets:
  - name: version-v1
    labels:
      version: v1
  - name: version-v2
    labels:
      version: v2
```
