### ISSUE TITLE
Apply VirtualService  and destination  in multicluster problem

### ISSUE THREAD

**Issue by JasperWey** [istio/istio#36241]
### Bug Description

I'm not sure it a bug. Just post for helping.
1. Install multi-primary in multi network according the [doc](https://istio.io/v1.10/docs/setup/install/multicluster/multi-primary_multi-network/) (use v1.10.3 as the k8s version v.18.7)
2. something different with the doc: I setup the env in servers not on cloud, so no LB offer to use. I just put the externalIP with the node ip for the istio-east-westgateway service and change istio-ingressgateway service as nodePort(I have just one nic )
3. the service in istio-system:
```bash
NAME                    TYPE           CLUSTER-IP       EXTERNAL-IP    PORT(S)                                                           AGE
istio-eastwestgateway   LoadBalancer   10.101.91.71     172.25.4.111   15021:30696/TCP,15443:30370/TCP,15012:32082/TCP,15017:31988/TCP   2d
istio-ingressgateway    NodePort       10.103.122.150   <none>         15021:31093/TCP,80:30165/TCP,443:32370/TCP                        2d
istiod                  ClusterIP      10.104.191.124   <none>         15010/TCP,15012/TCP,443/TCP,15014/TCP                             2d

```
4.  [verify the installation](https://istio.io/v1.10/docs/setup/install/multicluster/verify) and it works
```bash
root@vm-demo-12-111:/home/istio# kubectl exec -n sample  sleep-64d7d56698-nlg6k  -c sleep -- curl -sS helloworld.sample:5000/hello
Hello version: v2, instance: helloworld-v2-7855866d4f-wv9wb
root@vm-demo-12-111:/home/istio# kubectl exec -n sample  sleep-64d7d56698-nlg6k  -c sleep -- curl -sS helloworld.sample:5000/hello
Hello version: v1, instance: helloworld-v1-5b75657f75-v7qks
```
5. Apply the virutal service and destination as follow:
```yaml
  apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: helloworld
spec:
  host: helloworld
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helloworld
spec:
  hosts:
  - helloworld
  http:
  - route:
    - destination:
        host: helloworld
        subset: v2
```
6. curl as failed:
```bash
  kubectl exec -n sample  sleep-64d7d56698-nlg6k  -c sleep -- curl -sS helloworld.sample:5000/hello
upstream connect error or disconnect/reset before headers. reset reason: connection failure
```

7. Something wrong when cross the cluster when apply vs and ds. but it works fine without it. Does it related for my LB setting or istio-ingressgateway setting?

### Version

```prose
# istioctl version
client version: 1.10.3
control plane version: 1.10.3
data plane version: 1.10.3 (4 proxies)

# kubectl version --short
Client Version: v1.18.7
Server Version: v1.18.7
```
