### ISSUE TITLE
Is there a way to disable access (or disable DNS resolve) to a specific service in a specific cluster using multicluster setup?

### ISSUE THREAD

**Issue by Noksa** [istio/istio#36243]
Hello!

Thank you for Istio. It is really cool thing!

I've tried to install multicluster setup (2 clusters run in the same network). 

Everything works fine except one thing.

It looks like all services can be accessed from any cluster by default.
How can I disable this behavior?

For example I want that a service with name `service1` will be visible only for `cluster1` and not to `cluster2` because I don't want to share it to all clusters. It should be used only in `cluster1`.
Case is that in my clusters can be services with the same name. But they should be used only in cluster where they exist without any balancing across all clusters in the mesh.

My config as follows:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: cluster1
      network: network1
  meshConfig:
    defaultConfig:
      proxyMetadata:
        # Enable basic DNS proxying
        ISTIO_META_DNS_CAPTURE: "true"
        # Enable automatic address allocation, optional
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
```
The same for cluster2 except name `cluster2`
