### ISSUE TITLE
Omitted setting sidecarInjectorWebhook.enableNamespacesByDefault in istio-revision-tag-default mutating webhook.

### ISSUE THREAD

**Issue by cnvergence** [istio/istio#36258]
### Bug Description

In the Istio 1.12.0 installed by istioctl with default profile, there are two mutating webhooks. 
[mutatingwebhook.yaml](https://github.com/istio/istio/blob/1.12.0/manifests/charts/default/templates/mutatingwebhook.yaml) is missing the part of injector's logic when neither label is set:
```
{{- if .Values.sidecarInjectorWebhook.enableNamespacesByDefault }}
{{- /* Special case 3: no labels at all */}}
{{- include "core" (mergeOverwrite (deepCopy .) (dict "Prefix" "auto.") ) }}
  namespaceSelector:
    matchExpressions:
    - key: istio-injection
      operator: DoesNotExist
    - key: istio.io/rev
      operator: DoesNotExist
  objectSelector:
    matchExpressions:
    - key: sidecar.istio.io/inject
      operator: DoesNotExist
    - key: istio.io/rev
      operator: DoesNotExist
{{- end }}
```
Neither the latest [docs](https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#controlling-the-injection-policy) nor the upgrade notes did not state changes to this logic.

### Version

```prose
istioctl version
client version: 1.12.0
control plane version: 1.12.0
data plane version: 1.12.0 (3 proxies)
```

### Additional Information

Installed the Istio default profile with`istioctl install --set values.sidecarInjectorWebhook.enableNamespacesByDefault=true` using istioctl-1.12.0.
Then deployed workload without pod and namespace annotations.
