### ISSUE TITLE
istioctl analyze invalid memory address

### ISSUE THREAD

**Issue by ludydoo** [istio/istio#36272]
### Bug Description

Trying to run `istioctl analyze -n ...`

Getting a `invalid memory address or nil pointer dereference`

```
istioctl analyze -n thanos
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x2266a84]

goroutine 503 [running]:
istio.io/istio/galley/pkg/config/analysis/analyzers/authz.(*AuthorizationPoliciesAnalyzer).analyzeNamespaceNotFound(0x50000c000c70fc8, 0xc0029ff3b0, {0x3400eb8, 0xc0032dbaa0})
        istio.io/istio/galley/pkg/config/analysis/analyzers/authz/authorizationpolicies.go:146 +0x124
istio.io/istio/galley/pkg/config/analysis/analyzers/authz.(*AuthorizationPoliciesAnalyzer).Analyze.func1(0xc003289c98)
        istio.io/istio/galley/pkg/config/analysis/analyzers/authz/authorizationpolicies.go:60 +0x5e
istio.io/istio/galley/pkg/config/collection.(*Instance).ForEach(0x2800940, 0xc0032dbe90)
        istio.io/istio/galley/pkg/config/collection/instance.go:77 +0xf7
istio.io/istio/galley/pkg/config/processing/snapshotter.(*Snapshot).ForEach(...)
        istio.io/istio/galley/pkg/config/processing/snapshotter/snapshot.go:100
istio.io/istio/galley/pkg/config/processing/snapshotter.(*context).ForEach(0xc0032dbaa0, {0x2dd8cb1, 0x2c}, 0xc003289d88)
        istio.io/istio/galley/pkg/config/processing/snapshotter/analyzingdistributor.go:268 +0x6f
istio.io/istio/galley/pkg/config/analysis/analyzers/authz.(*AuthorizationPoliciesAnalyzer).Analyze(0x525ac50, {0x3400eb8, 0xc0032dbaa0})
        istio.io/istio/galley/pkg/config/analysis/analyzers/authz/authorizationpolicies.go:58 +0xed
istio.io/istio/galley/pkg/config/analysis.(*CombinedAnalyzer).Analyze(0xc000f73080, {0x3400eb8, 0xc0032dbaa0})
        istio.io/istio/galley/pkg/config/analysis/analyzer.go:60 +0x1cd
istio.io/istio/galley/pkg/config/processing/snapshotter.(*AnalyzingDistributor).analyzeAndDistribute(0xc0009fed80, 0xc002c995c0, {0xc00153ee70, 0xd}, 0xc0009e46c0, 0x0)
        istio.io/istio/galley/pkg/config/processing/snapshotter/analyzingdistributor.go:161 +0x125
created by istio.io/istio/galley/pkg/config/processing/snapshotter.(*AnalyzingDistributor).Distribute
        istio.io/istio/galley/pkg/config/processing/snapshotter/analyzingdistributor.go:139 +0x32f

```

### Version

```prose
client version: 1.12.0
control plane version: 1.12.0
data plane version: 1.12.0 (23 proxies), 1.11.4 (19 proxies)
```

### Additional Information

It only happens when any of these 3 authorization policies are present.
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  labels:
    app: loki-distributor
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki-distributor
  name: loki-distributor
  namespace: loki
spec:
  rules:
    - from:
        - {}
    - from:
        - source:
            principals:
              - cluster.local/ns/promtail/sa/promtail
  selector:
    matchLabels:
      app: loki-distributor
      app.kubernetes.io/instance: loki
      app.kubernetes.io/name: loki-distributor
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  labels:
    app: loki-ingester
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki-ingester
  name: loki-ingester
  namespace: loki
spec:
  rules:
    - from:
        - {}
  selector:
    matchLabels:
      app: loki-ingester
      app.kubernetes.io/instance: loki
      app.kubernetes.io/name: loki-ingester
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  labels:
    app: loki-querier
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki-querier
  name: loki-querier
  namespace: loki
spec:
  rules:
    - from:
        - {}
  selector:
    matchLabels:
      app: loki-querier
      app.kubernetes.io/instance: loki
      app.kubernetes.io/name: loki-querier

```

setting the `rules` to `[]` fixes it

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  labels:
    app: loki-distributor
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki-distributor
  name: loki-distributor
  namespace: loki
spec:
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/promtail/sa/promtail
  selector:
    matchLabels:
      app: loki-distributor
      app.kubernetes.io/instance: loki
      app.kubernetes.io/name: loki-distributor
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  labels:
    app: loki-ingester
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki-ingester
  name: loki-ingester
  namespace: loki
spec:
  rules: []
  selector:
    matchLabels:
      app: loki-ingester
      app.kubernetes.io/instance: loki
      app.kubernetes.io/name: loki-ingester
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  labels:
    app: loki-querier
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki-querier
  name: loki-querier
  namespace: loki
spec:
  rules: []
  selector:
    matchLabels:
      app: loki-querier
      app.kubernetes.io/instance: loki
      app.kubernetes.io/name: loki-querier


```
