### ISSUE TITLE
On TCP connection, service only seems to get connection after client sends packages

### ISSUE THREAD

**Issue by daniel-anova** [istio/istio#36283]
### Bug Description

We configured a TCP port 4767 "dev" in our IstioOperator kind, our service needs to reply when recieving a connection.

IstioOperator
```yaml
 spec:
    components:
      cni:
        enabled: false
      egressGateways:
      - enabled: false
        k8s:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: agentpool
                    operator: In
                    values:
                    - system
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    istio: ingressgateway
                topologyKey: kubernetes.io/hostname
          hpaSpec:
            minReplicas: 2
          tolerations:
          - effect: NoSchedule
            key: CriticalAddonsOnly
            operator: Exists
        name: istio-egressgateway
      ingressGateways:
      - enabled: true
        k8s:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: agentpool
                    operator: In
                    values:
                    - system
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    istio: ingressgateway
                topologyKey: kubernetes.io/hostname
          hpaSpec:
            minReplicas: 2
          service:
            loadBalancerIP: <redacted>
            ports:
            - name: https
              port: 443
              targetPort: 8443
            - name: http2
              port: 80
              targetPort: 8080
            - name: a415
              port: 4767
            type: LoadBalancer
          serviceAnnotations:
            service.beta.kubernetes.io/azure-load-balancer-resource-group: <redacted>
            service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: "20"
          tolerations:
          - effect: NoSchedule
            key: CriticalAddonsOnly
            operator: Exists
        name: istio-ingressgateway
```

Gateway
```yaml
  spec:
    selector:
      app: istio-ingressgateway
      istio: ingressgateway
    servers:
    - hosts:
      - <redacted
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        credentialName: istio-certs
        mode: SIMPLE
    - hosts:
      - <redacted>
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
      - <redacted>
      port:
        name: tcp
        number: 4767
        protocol: TCP
```

We're able to connect to the port, however it seems the service only receive a connection after the client sends something (example: garbage characters).

So to summarize:
* connection through istio-ingressgateway (no reply)
* connection through istio-ingressgateway followed by sending an 0 character ~5 times (reply after the 5th send)
* connection through istio-ingressgateway with TCP port 4767 excluded from proxy (reply)
* connection through kubectl port-forward to service (reply)

### Version

```prose
❯ istioctl version
client version: 1.12.0
control plane version: 1.10.2
data plane version: 1.10.2 (199 proxies)
❯ istioctl version --short
client version: 1.12.0
control plane version: 1.10.2
data plane version: 1.10.2 (198 proxies)
❯ helm version --short
v3.7.1+g1d11fcb
```

**Comment by daniel-anova** [comment]
Internal investigation as determined it was our chart which corrected the target for a `DestinationRule` which was setting:
```yaml
spec:
  trafficPolicy:
    tls:
      mode: DISABLE
```

The `tls mode` to `DISABLE` seems to break comunication when forwarding this service traffic.

We apologize for the incorrect reporting.
