### ISSUE TITLE
fault filter: default does not match doc

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#36303]
Filter works:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: default
spec:
  hosts:
  - b
  http:
  - route:
    - destination:
        host: b
    fault:
      abort:
        httpStatus: 418
        percentage:
          value: 100
```

Filter never triggers:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: default
spec:
  hosts:
  - b
  http:
  - route:
    - destination:
        host: b
    fault:
      abort:
        httpStatus: 418
```

Docs ' The optional percentage field can be used to only abort a certain percentage of requests. If not specified, all requests are aborted.'

https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPFaultInjection-Abort

We need to either change the implementation or the behavior

@ramaraochavali @hzxuzhonghu
