### ISSUE TITLE
OpenTelemetryAccessLogConfig not working on istio 1.12

### ISSUE THREAD

**Issue by zirain** [istio/istio#36319]
### Bug Description

try apply this  EnvoyFilter on istio 1.12
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: envoy-als-otel
  namespace: istio-system
spec:
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: ANY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
            access_log:
            - name: envoy.access_loggers.open_telemetry
              typed_config:
                "@type": "type.googleapis.com/envoy.extensions.access_loggers.open_telemetry.v3.OpenTelemetryAccessLogConfig"
                common_config: 
                  log_name: "otel_envoy_accesslog"
                  grpc_service: 
                    envoy_grpc: 
                      cluster_name: envoy_accesslog_service
                  transport_api_version: "V3"
                body: 
                  string_value: "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% \"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%\n"
                attributes: 
                  values:
                  - key: "user_agent"
                    value: 
                      string_value: "%REQ(USER-AGENT)%"
                
``` 
with error:

![image](https://user-images.githubusercontent.com/4354057/144159334-5dae9384-c84f-401c-a2db-061dd23dda8a.png)

after change `type.googleapis.com/envoy.extensions.access_loggers.open_telemetry.v3.OpenTelemetryAccessLogConfig` to 
`type.googleapis.com/envoy.extensions.access_loggers.open_telemetry.v3alpha.OpenTelemetryAccessLogConfig`

sidecar will report error 
![image](https://user-images.githubusercontent.com/4354057/144159571-cd7e7b28-d204-4315-984f-42a69ab19eb2.png)

seems we should upgrade `go-control-plane` to `0.10.0`

### Version

```prose
$ istioctl version
client version: 1.12.0
control plane version: 1.12.0
data plane version: 1.12.0 (9 proxies)

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:54Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```
