### ISSUE TITLE
Unable to resolve DNS in a multi-cluster setup for headless service

### ISSUE THREAD

**Issue by nc-ruth** [istio/istio#36349]
### Bug Description

I have installed Istio 1.12 in two different AKS clusters.

Both AKS clusters is within the same mesh and network. (vnet peered)

I have followed the following guide: https://istio.io/latest/docs/setup/install/multicluster/multi-primary/ 

I have two different Kafka clusters in each of the AKS clusters. 

The setup looks like this:
![image](https://user-images.githubusercontent.com/41048990/144510272-5d58e19a-f02a-4c24-8c89-9fde9434a7a1.png)

I have the following services in cluster1:
```
NAME                                  TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                      AGE
kafka-northeurope                     ClusterIP   10.0.142.171   <none>        9092/TCP                     77m
kafka-northeurope-headless            ClusterIP   None           <none>        9092/TCP,9093/TCP            32m
kafka-westeurope                      ClusterIP   10.0.23.54     <none>        9092/TCP                     32d
kafka-westeurope-headless             ClusterIP   None           <none>        9092/TCP,9093/TCP            32d
kafka-westeurope-kowl-service         ClusterIP   10.0.160.105   <none>        8080/TCP                     32d
kafka-westeurope-metrics              ClusterIP   10.0.18.34     <none>        9308/TCP                     32d
kafka-westeurope-zookeeper            ClusterIP   10.0.243.21    <none>        2181/TCP,2888/TCP,3888/TCP   32d
kafka-westeurope-zookeeper-headless   ClusterIP   None           <none>        2181/TCP,2888/TCP,3888/TCP   32d
kafka-westeurope-zookeeper-metrics    ClusterIP   10.0.244.99    <none>        9141/TCP                     32d
```

I have the following pods in cluster1:
```
NAME                                                READY   STATUS             RESTARTS   AGE
kafka-westeurope-0                                  3/3     Running            0          43m
kafka-westeurope-1                                  3/3     Running            0          44m
kafka-westeurope-2                                  3/3     Running            0          46m
kafka-westeurope-exporter-5c66cd997-7pdqm           2/2     Running            5          47m
kafka-westeurope-kowl-7fc8c68b74-s5k97              2/2     Running            4          47m
kafka-westeurope-mirrormaker-557769cc7f-vbgqt       1/2     CrashLoopBackOff   6          14m
kafka-westeurope-zookeeper-0                        2/2     Running            0          46m
kafka-westeurope-zookeeper-1                        2/2     Running            0          46m
kafka-westeurope-zookeeper-2                        2/2     Running            0          46m
```

I have the following services in cluster2:
```
NAME                                   TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                      AGE
kafka-northeurope                      ClusterIP   10.0.165.97    <none>        9092/TCP                     3h10m
kafka-northeurope-headless             ClusterIP   None           <none>        9092/TCP,9093/TCP            3h10m
kafka-northeurope-kowl-service         ClusterIP   10.0.102.224   <none>        8080/TCP                     3h10m
kafka-northeurope-metrics              ClusterIP   10.0.190.149   <none>        9308/TCP                     3h10m
kafka-northeurope-zookeeper            ClusterIP   10.0.253.82    <none>        2181/TCP,2888/TCP,3888/TCP   3h10m
kafka-northeurope-zookeeper-headless   ClusterIP   None           <none>        2181/TCP,2888/TCP,3888/TCP   3h10m
kafka-northeurope-zookeeper-metrics    ClusterIP   10.0.64.243    <none>        9141/TCP                     3h10m
```

I have the following pods in cluster2:
```
NAME                                                 READY   STATUS    RESTARTS   AGE
kafka-northeurope-0                                  3/3     Running   0          42m
kafka-northeurope-1                                  3/3     Running   0          44m
kafka-northeurope-2                                  3/3     Running   0          47m
kafka-northeurope-exporter-76cb5d8ddc-4fgsb          2/2     Running   5          47m
kafka-northeurope-kowl-5549895cfb-4d97s              2/2     Running   5          47m
kafka-northeurope-zookeeper-0                        2/2     Running   0          45m
kafka-northeurope-zookeeper-1                        2/2     Running   0          46m
kafka-northeurope-zookeeper-2                        2/2     Running   0          47m
```

I am unable to reach following headless service names from cluster1:
```
java.net.UnknownHostException: kafka-northeurope-0.kafka-northeurope-headless.preprod.svc.cluster.local: Name or service not known
java.net.UnknownHostException: kafka-northeurope-1.kafka-northeurope-headless.preprod.svc.cluster.local: Name or service not known
java.net.UnknownHostException: kafka-northeurope-2.kafka-northeurope-headless.preprod.svc.cluster.local: Name or service not known
``` 

All pods are running with a Istio sidecar, and resolving non-headless services works fine. 

The headless service (which resides both in cluster1 and cluster2 looks like this): 
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: kafka-northeurope
    meta.helm.sh/release-namespace: preprod
  labels:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/instance: kafka-northeurope
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
    helm.sh/chart: kafka-14.4.1
  name: kafka-northeurope-headless
  namespace: preprod
spec:
  clusterIP: None
  clusterIPs:
  - None
  ports:
  - name: tcp-client
    port: 9092
    protocol: TCP
    targetPort: kafka-client
  - name: tcp-internal
    port: 9093
    protocol: TCP
    targetPort: kafka-internal
  selector:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/instance: kafka-northeurope
    app.kubernetes.io/name: kafka
  sessionAffinity: None
  type: ClusterIP
```

Do you have any ideas of what I am doing wrong? 
I feel there is a lack of documentation on the area, and I hope I can contribute to the docs with whatever answer which will solve my issue. 

### Version

```prose
$ istioctl version
client version: 1.12.0
control plane version: 1.12.0
data plane version: 1.12.0 (10 proxies)

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVers
ion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"454b5b515582f8ac8419435dc9c230fc97fb844b", GitTreeState:"clean", BuildDate:"2021-11-01T19:59:05Z", GoVers
ion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by nc-ruth** [comment]
Hi @stevenctl, I am sorry to ping you directly, but I have seen that you have done great and significant work in regards of MCS and headless services. Do you have an idea of why it does not work for me?

**Comment by stevenctl** [comment]
Do you have `ENABLE_MULTICLUSTER_HEADLESS` enabled in pilot with in-agent DNS enabled?

**Comment by nc-ruth** [comment]
Hi @stevenctl is ENABLE_MULTICLUSTER_HEADLESS not enabled per default in Istio 1.12? 

I am a bit unsure about the in-agent DNS enablement, how do I enable that?

**Comment by linsun** [comment]
`ENABLE_MULTICLUSTER_HEADLESS` is false by default, you have to manually enable it.

@stevenctl this is only for single network, correct?

**Comment by stevenctl** [comment]
Actually, `ENABLE_MULTICLUSTER_HEADLESS` _is_ enabled by default in 1.12+

For the in-agent DNS, see https://istio.io/latest/docs/ops/configuration/traffic-management/dns-proxy/. 

And yes, as @linsun points out, this won't work if the headless endpoint is in another network from the client.

**Comment by nc-ruth** [comment]
Thank you so much @linsun and @stevenctl :) 

It got solved with the following configuration:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values: # Inspired from:  https://istio.io/latest/docs/setup/install/multicluster/multi-primary/#configure-cluster1-as-a-primary
    global:
      meshID: mesh1
      multiCluster:
        clusterName: cluster1 # is set as cluster2 in the north-europe cluster
      network: network1
  meshConfig: # Inspired from: https://istio.io/latest/docs/ops/configuration/traffic-management/dns-proxy/#getting-started
    defaultConfig:
      proxyMetadata:
        # Enable basic DNS proxying
        ISTIO_META_DNS_CAPTURE: "true"
        # Enable automatic address allocation, optional
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
```
