### ISSUE TITLE
file cluster.env is incorrect when create configure files for virtual machine

### ISSUE THREAD

**Issue by cfanbo** [istio/istio#36358]
### Bug Description

`cluster.env` body is incorrect when create files for virtual machine. 
installl virtualMachine document: https://istio.io/latest/docs/setup/install/virtual-machine/#create-files-to-transfer-to-the-virtual-machine
```
ISTIO_META_POD_PORTS='"[{\"name\":\"mysql\",\"containerPort\":3306,\"protocol\":\"\"},{\"name\":\"redis\",\"containerPort\":6379,\"protocol\":\"\"}]"
```
when execute command 'systemctl start istio` always faild.

```
$ cat /var/log/istio/istio.err.log
2021-12-03T09:55:10.030044Z	error	failed to start envoy agent: failed to generate bootstrap metadata: json: cannot unmarshal string into Go struct field BootstrapNodeMetadata2.POD_PORTS of type []model.PodPort
```

if change `cluster.env` body services is ok
```
ISTIO_META_POD_PORTS='[{"name":"mysql","containerPort":3306,"protocol":""},{"name":"redis","containerPort":6379,"protocol":""}]'
```

1. workloadgroup.yaml
```
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadGroup
metadata:
  name: "approot"
  namespace: "vm"
spec: 
  metadata: 
    labels: 
      app: "approot" 
  template:
    ports:
      mysql: 3306
      redis: 6379
    serviceAccount: "default"
    network: ""
```
2. cerate configure files
```
istioctl x workload entry configure -f workloadgroup.yaml -o "${WORK_DIR}" --clusterID "${CLUSTER}" --autoregister
```
3. cluster.env 
```
CANONICAL_REVISION='latest'
CANONICAL_SERVICE='approot'
ISTIO_INBOUND_PORTS='3306,6379'
ISTIO_LOCAL_EXCLUDE_PORTS='15090,15021,15020'
ISTIO_METAJSON_LABELS='{"app":"approot","service.istio.io/canonical-name":"approot","service.istio.io/canonical-version":"latest"}'
ISTIO_META_AUTO_REGISTER_GROUP='approot'
ISTIO_META_CLUSTER_ID='Kubernetes'
ISTIO_META_DNS_CAPTURE='true'
ISTIO_META_MESH_ID='mesh1'
ISTIO_META_NETWORK=''
ISTIO_META_POD_PORTS='"[{\"name\":\"mysql\",\"containerPort\":3306,\"protocol\":\"\"},{\"name\":\"redis\",\"containerPort\":6379,\"protocol\":\"\"}]"'
ISTIO_META_WORKLOAD_NAME='approot'
ISTIO_NAMESPACE='vm'
ISTIO_SERVICE='approot.vm'
ISTIO_SERVICE_CIDR='*'
POD_NAMESPACE='vm'
SERVICE_ACCOUNT='default'
TRUST_DOMAIN='cluster.local'
```

### Version

```prose
# istioctl version
kuclient version: 1.11.1
control plane version: 1.11.1
data plane version: 1.11.1 (2 proxies), 1.11.0 (3 proxies)
# kubectl version --short
Client Version: v1.21.2
Server Version: v1.21.3
```
