### ISSUE TITLE
Probe rewrite does not rewrite probe for all additionally injected containers in pod

### ISSUE THREAD

**Issue by adriankostrubiak-tomtom** [istio/istio#36353]
### Bug Description

When another operator injects a container into a pod that has already been mutated by the istio operator, the injected container's probe will not be re-written. This is an unexpected (abeit understandable) behavior, and breaks probes with strict mtls enabled.

---

Given the following webhooks installed in a cluster,

```bash
=> kubectl get mutatingwebhookconfiguration                             
NAME                                                     WEBHOOKS   AGE
istio-sidecar-injector                                   4          463d
opa-istio-admission-controller                           1          10d
opentelemetry-operator-mutating-webhook-configuration    3          213d
```

And a workload such as:
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
 selector:
    matchLabels:
      app: my-app
  template:
    spec:
      containers:
        - name: my-prometheus-exporter
          image: my-prometheus-exporter:master-1001658
          livenessProbe:
            httpGet:
              path: /
              port: http-prom
          readinessProbe:
            httpGet:
              path: /
              port: http-prom
        - name: my-app
          image: my-app:staging-1085589
          livenessProbe:
            httpGet:
              path: /health
              port: http-9090
          readinessProbe:
            httpGet:
              path: /health
              port: http-9090
```

The created pod looks like the below. Note that the probes on the two defined containers in the above workload have been appropriately rewritten, as expected. However, the probes on the additional injected containers (those being `otc-container`, `opa-istio`) are not rewritten.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-app-8fb47955f-x2gpd
spec:
  containers:
  - image: my-prometheus-exporter:master-1001658
    livenessProbe:
      httpGet:
        path: /app-health/my-prometheus-exporter/livez
        port: 15020
        scheme: HTTP
    name: my-prometheus-exporter
    ports:
    - containerPort: 9113
      name: http-prom
      protocol: TCP
    readinessProbe:
      httpGet:
        path: /app-health/my-prometheus-exporter/readyz
        port: 15020
        scheme: HTTP
  - image: my-app:staging-1085589
    livenessProbe:
      httpGet:
        path: /app-health/my-app/livez
        port: 15020
        scheme: HTTP
    name: my-app
    readinessProbe:
      httpGet:
        path: /app-health/my-app/readyz
        port: 15020
        scheme: HTTP
  - args:
    - proxy
    - sidecar
    - --domain
    - $(POD_NAMESPACE).svc.cluster.local
    - --proxyLogLevel=warning
    - --proxyComponentLogLevel=misc:error
    - --log_output_level=default:info
    - --concurrency
    - "2"
    env:
    - name: JWT_POLICY
      value: third-party-jwt
    - name: PILOT_CERT_PROVIDER
      value: istiod
    - name: CA_ADDR
      value: istiod.istio-system.svc:15012
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: INSTANCE_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.serviceAccountName
    - name: HOST_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: PROXY_CONFIG
      value: |
        {"tracing":{"zipkin":{"address":"0.0.0.0:9411"},"sampling":100},"proxyMetadata":{"ISTIO_META_DNS_CAPTURE":"true","PROXY_XDS_DEBUG_VIA_AGENT":"false"},"gatewayTopology":{"forwardClientCertDetails":"SANITIZE"}}
    - name: ISTIO_META_POD_PORTS
      value: |-
        [
            {"name":"http-prom","containerPort":9113,"protocol":"TCP"}
            ,{"name":"http-8080","containerPort":8080,"protocol":"TCP"}
            ,{"name":"http-9090","containerPort":9090,"protocol":"TCP"}
        ]
    - name: ISTIO_META_APP_CONTAINERS
      value: my-prometheus-exporter,my-app
    - name: ISTIO_META_CLUSTER_ID
      value: Kubernetes
    - name: ISTIO_META_INTERCEPTION_MODE
      value: REDIRECT
    - name: ISTIO_META_WORKLOAD_NAME
      value: my-app
    - name: ISTIO_META_OWNER
      value: kubernetes://apis/apps/v1/namespaces/my-namespace/deployments/my-app
    - name: ISTIO_META_MESH_ID
      value: cluster.local
    - name: TRUST_DOMAIN
      value: cluster.local
    - name: ISTIO_META_DNS_CAPTURE
      value: "true"
    - name: PROXY_XDS_DEBUG_VIA_AGENT
      value: "false"
    - name: ISTIO_PROMETHEUS_ANNOTATIONS
      value: '{"scrape":"true","path":"/metrics","port":"9113"}'
    - name: ISTIO_KUBE_APP_PROBERS
      value: '{"/app-health/my-prometheus-exporter/livez":{"httpGet":{"path":"/","port":9113,"scheme":"HTTP"},"timeoutSeconds":1},"/app-health/my-prometheus-exporter/readyz":{"httpGet":{"path":"/","port":9113,"scheme":"HTTP"},"timeoutSeconds":1},"/app-health/my-app/livez":{"httpGet":{"path":"/health","port":9090,"scheme":"HTTP"},"timeoutSeconds":1},"/app-health/my-app/readyz":{"httpGet":{"path":"/health","port":9090,"scheme":"HTTP"},"timeoutSeconds":1}}'
    image: gcr.io/istio-release/proxyv2:1.11.4
    imagePullPolicy: IfNotPresent
    name: istio-proxy
    ports:
    - containerPort: 15090
      name: http-envoy-prom
      protocol: TCP
    readinessProbe:
      failureThreshold: 30
      httpGet:
        path: /healthz/ready
        port: 15021
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 2
      successThreshold: 1
      timeoutSeconds: 3
  - image: opa:0.34.1-istio-1-rootless
    livenessProbe:
      httpGet:
        path: /health?plugins
        port: 8282
        scheme: HTTP
    name: opa-istio
    readinessProbe:
      httpGet:
        path: /health?plugins
        port: 8282
        scheme: HTTP
  - image: otel/opentelemetry-collector:0.40.0
    livenessProbe:
      httpGet:
        path: /health
        port: 13133
        scheme: HTTP
    name: otc-container
```

If we adjust the cluster's configuration to duplicate the `MutatingWebhookConfiguration` of `opentelemetry-operator-mutating-webhook-configuration`, simply renaming it to `aopentelemetry-operator-mutating-webhook-configuration` (note that this is intentionally alphabetically before "i"):

```bash
 => kubectl get mutatingwebhookconfiguration                             
NAME                                                     WEBHOOKS   AGE
aopentelemetry-operator-mutating-webhook-configuration   3          11m
istio-sidecar-injector                                   4          463d
opa-istio-admission-controller                           1          10d
opentelemetry-operator-mutating-webhook-configuration    3          213d
```

And restart the workload, to trigger a re-injection, we end up with a pod like the below.

Again, as expected, the probes on the two defined containers in the above workload have been appropriately rewritten. Additionally, the probe on the `otc-container` has now been rewritten.  I believe this to be due to the fact that the controller mutating the pod to add the `otc-container` is now running before istio's mutation process, based on the naming of the MutatingWebhookConfiguration.  Unfortunately, the probe on the `opa-istio` container remains not rewritten.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-app-c45fb45c6-fclrw
  namespace: ak-otel-managed
spec:
  containers:
  - image: my-prometheus-exporter:master-1001658
    livenessProbe:
      httpGet:
        path: /app-health/my-prometheus-exporter/livez
        port: 15020
        scheme: HTTP
    name: my-prometheus-exporter
    ports:
    - containerPort: 9113
      name: http-prom
      protocol: TCP
    readinessProbe:
      httpGet:
        path: /app-health/my-prometheus-exporter/readyz
        port: 15020
        scheme: HTTP
  - image: my-app:staging-1085589
    livenessProbe:
      httpGet:
        path: /app-health/my-app/livez
        port: 15020
        scheme: HTTP
    name: my-app
    readinessProbe:
      httpGet:
        path: /app-health/my-app/readyz
        port: 15020
        scheme: HTTP
  - image: otel/opentelemetry-collector:0.40.0
    livenessProbe:
      httpGet:
        path: /app-health/otc-container/livez
        port: 15020
        scheme: HTTP
    name: otc-container
  - args:
    - proxy
    - sidecar
    - --domain
    - $(POD_NAMESPACE).svc.cluster.local
    - --proxyLogLevel=warning
    - --proxyComponentLogLevel=misc:error
    - --log_output_level=default:info
    - --concurrency
    - "2"
    env:
    - name: JWT_POLICY
      value: third-party-jwt
    - name: PILOT_CERT_PROVIDER
      value: istiod
    - name: CA_ADDR
      value: istiod.istio-system.svc:15012
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: INSTANCE_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.serviceAccountName
    - name: HOST_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: PROXY_CONFIG
      value: |
        {"tracing":{"zipkin":{"address":"0.0.0.0:9411"},"sampling":100},"proxyMetadata":{"EXIT_ON_ZERO_ACTIVE_CONNECTIONS":"true","ISTIO_META_DNS_CAPTURE":"true","PROXY_XDS_DEBUG_VIA_AGENT":"false"},"gatewayTopology":{"forwardClientCertDetails":"SANITIZE"}}
    - name: ISTIO_META_POD_PORTS
      value: |-
        [
            {"name":"http-prom","containerPort":9113,"protocol":"TCP"}
            ,{"name":"http-8080","containerPort":8080,"protocol":"TCP"}
            ,{"name":"http-9090","containerPort":9090,"protocol":"TCP"}
        ]
    - name: ISTIO_META_APP_CONTAINERS
      value: my-prometheus-exporter,my-app,otc-container
    - name: ISTIO_META_CLUSTER_ID
      value: Kubernetes
    - name: ISTIO_META_INTERCEPTION_MODE
      value: REDIRECT
    - name: ISTIO_META_WORKLOAD_NAME
      value: my-app
    - name: ISTIO_META_OWNER
      value: kubernetes://apis/apps/v1/namespaces/my-namespace/deployments/my-app
    - name: ISTIO_META_MESH_ID
      value: cluster.local
    - name: TRUST_DOMAIN
      value: cluster.local
    - name: EXIT_ON_ZERO_ACTIVE_CONNECTIONS
      value: "true"
    - name: ISTIO_META_DNS_CAPTURE
      value: "true"
    - name: PROXY_XDS_DEBUG_VIA_AGENT
      value: "false"
    - name: ISTIO_PROMETHEUS_ANNOTATIONS
      value: '{"scrape":"true","path":"/metrics","port":"9113"}'
    - name: ISTIO_KUBE_APP_PROBERS
      value: '{"/app-health/my-prometheus-exporter/livez":{"httpGet":{"path":"/","port":9113,"scheme":"HTTP"},"timeoutSeconds":1},"/app-health/my-prometheus-exporter/readyz":{"httpGet":{"path":"/","port":9113,"scheme":"HTTP"},"timeoutSeconds":1},"/app-health/otc-container/livez":{"httpGet":{"path":"/health","port":13133,"scheme":"HTTP"},"timeoutSeconds":1},"/app-health/my-app/livez":{"httpGet":{"path":"/health","port":9090,"scheme":"HTTP"},"timeoutSeconds":1},"/app-health/my-app/readyz":{"httpGet":{"path":"/health","port":9090,"scheme":"HTTP"},"timeoutSeconds":1}}'
    image: gcr.io/istio-release/proxyv2:1.12.0
    imagePullPolicy: Always
    name: istio-proxy
    ports:
    - containerPort: 15090
      name: http-envoy-prom
      protocol: TCP
    readinessProbe:
      failureThreshold: 30
      httpGet:
        path: /healthz/ready
        port: 15021
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 2
      successThreshold: 1
      timeoutSeconds: 3
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 40Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 1337
      runAsNonRoot: true
      runAsUser: 1337
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/istio
      name: istiod-ca-cert
    - mountPath: /var/lib/istio/data
      name: istio-data
    - mountPath: /etc/istio/proxy
      name: istio-envoy
    - mountPath: /var/run/secrets/tokens
      name: istio-token
    - mountPath: /etc/istio/pod
      name: istio-podinfo
  - image: openpolicyagent/opa:0.34.1-istio-1-rootless
    livenessProbe:
      httpGet:
        path: /health?plugins
        port: 8282
        scheme: HTTP
    name: opa-istio
    readinessProbe:
      httpGet:
        path: /health?plugins
        port: 8282
        scheme: HTTP
```

Based on how this seems to be working, I can understand how the istio injection is not occurring on containers that are injected after istio has run it's injection. However, I think this is not desirable behavior, and prevents the use of strict mtls due to failing probes.

Checking the k8s documentation on admission control, it seems that this could be rectified by adjusting the `istio-sidecar-injector`'s  [reinvocation policy](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#reinvocation-policy)  to `IfNeeded`.

>A single ordering of mutating admissions plugins (including webhooks) does not work for all cases (see https://issue.k8s.io/64333 as an example). A mutating webhook can add a new sub-structure to the object (like adding a container to a pod), and other mutating plugins which have already run may have opinions on those new structures (like setting an imagePullPolicy on all containers).
> ...
>IfNeeded: the webhook may be called again as part of the admission evaluation if the object being admitted is modified by other admission plugins after the initial webhook call.

I could see that being a more heavy weight solution than desired (maybe a toggle to turn this on for those that want? ...?), as well, but it would be really great if istio would rewrite all of the probes, regardless of when the container is added to a pod.

I'd be happy to lend a hand in figuring out a resolution to this issue. :) 

### Version

```prose
=> istioctl version         
client version: 1.11.4
control plane version: 1.12.0
data plane version: 1.11.4 (176 proxies), 1.12.0 (30 proxies)

=> kubectl version --short
Client Version: v1.21.1
Server Version: v1.21.2
```
