### ISSUE TITLE
WasmPlugin: Confusing configuration

### ISSUE THREAD

**Issue by leyao-daily** [istio/istio#36378]
Suppose I build a `my.wasm` and build it as a docker image using the example Dockerfile in this repo.
And then I create a CR:
```
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: mywasm
  namespace: sc
spec:
  selector:
    matchLabels:
      app: httpbin
  url: oci://docker.io/leyao/mywasm:v4
```
Is that avaliable?

And if I want to deliver some configuration value to my filter, what should I define the following `http_filters.typed_config.config.configuration.value" in the WasmPlugin CR.
```
 http_filters:
          - name: envoy.filters.http.wasm
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
              config:
                name: "my_plugin"
                root_id: "my_root_id"
                # if your wasm filter requires custom configuration you can add
                # as follows
                configuration:
                  "@type": "type.googleapis.com/google.protobuf.StringValue"
                  value: |
                    SecRuleEngine On
                    SecRule ARGS:param1 "test" "id:1,phase:1,pass,status:200,msg:'Test rule'"
                    SecRule ARGS:param1 "attack" "id:2,phase:1,deny,status:400,msg:'Test rule'"
                vm_config:
                  runtime: "envoy.wasm.runtime.v8"
                  vm_id: "my_vm_id"
                  configuration:
                    "@type": "type.googleapis.com/google.protobuf.StringValue"
                    value: |
                     {}
                  code:
                    local:
                      filename: "xxx.wasm"
```
