### ISSUE TITLE
Removing an Envoy Filter fails because the name is set to empty string

### ISSUE THREAD

**Issue by awu** [istio/istio#36398]
### Bug Description

When attempting to remove an Envoy network filter using the `REMOVE` operation, Istio sets the name to an empty string 
https://github.com/istio/istio/blob/51fb00e0400381cdf84f639dc48e674c34ddd08a/pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go#L355

https://github.com/istio/istio/blob/51fb00e0400381cdf84f639dc48e674c34ddd08a/pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go#L539

However this violates the proto validation
 
https://github.com/envoyproxy/envoy/blob/77fdadf4aad468a0a9701afecb253ac67a64ebbd/api/envoy/config/listener/v3/listener_components.proto#L38

and the proxy fails to start with error 

```
gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Proto constraint validation failed (ListenerValidationError.FilterChains[0]: embedded message failed validation | caused by FilterChainValidationError.Filters[0]: embedded message failed validation | caused by FilterValidationError.Name: value length must be at least 1 characters)
```

### Version

```prose
client version: 1.12.0
control plane version: 1.11.4
data plane version: 1.11.4 (1 proxies)
```

**Comment by hzxuzhonghu** [comment]
How to reproduce?

**Comment by awu** [comment]
It happens for me when applying a filter in the root namespace then removing it in another namespace.

Global filter:
```
kind: EnvoyFilter
metadata:
  name: block-rule
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: SIDECAR_OUTBOUND 
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.tcp_proxy"
    patch:
      operation: INSERT_BEFORE
      value:
        name: "envoy.filters.network.rbac"
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.rbac.v3.RBAC"
          rules:
            action: DENY
            policies:
             "block-rule":
                permissions:
                  - or_rules:
                      rules:
                        - destination_ip: 
                            address_prefix: "10.247.224.1"
                            prefix_len: 32
                        - destination_ip: 
                            address_prefix: "10.246.192.192"
                            prefix_len: 32
                principals:
                  - any: true
          stat_prefix: "block-rule"
```

Remove filter
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: lift-rule
  namespace: test-ns
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: SIDECAR_OUTBOUND 
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.rbac"
    patch:
      operation: REMOVE
```

**Comment by awu** [comment]
okay after doing so more digging, I think my issue is actually #27826 because the offending filter is the `tcp_proxy` in `virtualOutbound-blackhole`. I somehow got into some weird state where the filter had its name deleted
```
-                "listener": {
-                    "@type": "type.googleapis.com/envoy.config.listener.v3.Listener",
-                    "name": "virtualOutbound",
-                    "address": {
-                        "socketAddress": {
-                            "address": "0.0.0.0",
-                            "portValue": 15001
-                        }
-                    },
-                    "filterChains": [
-                        {
-                            "filterChainMatch": {
-                                "destinationPort": 15001
-                            },
-                            "filters": [
-                                {
-                                    "typedConfig": {
-                                        "@type": "type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy",
-                                        "statPrefix": "BlackHoleCluster",
-                                        "cluster": "BlackHoleCluster"
-                                    }
-                                }
-                            ],
-                            "name": "virtualOutbound-blackhole"
-                        },
```

**Comment by awu** [comment]
ok removing and adding the filter chain back worked, still unsure how exactly I got in this state
```
  - applyTo: FILTER_CHAIN
    match:
      context: ANY
      listener:
        filterChain:
          name: virtualOutbound-blackhole
        name: virtualOutbound
    patch:
      operation: REMOVE
  - applyTo: FILTER_CHAIN
    match:
      context: ANY
      listener:
        filterChain:
          name: virtualOutbound-blackhole
        name: virtualOutbound
    patch:
      operation: ADD
      value:
        filter_chain_match:
          destination_port: 15001
        filters:
          - name: envoy.filters.network.tcp_proxy 
            typed_config: 
              '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              cluster: BlackHoleCluster
              stat_prefix: BlackHoleCluster
```
