### ISSUE TITLE
Tracing: Istio HTTP->gRPC span doesn't appear in trace. 

### ISSUE THREAD

**Issue by movergan** [istio/istio#36419]
Inspired by investigations done in https://github.com/istio/istio/issues/11696
Environment:

IstioGateway->Service-A(http)->Service-B(gRPC)
Ports in services are named properly. 

Service A Takes headers from incoming HTTP request and adds them to the outdoing gRPC requests to Service B:
```
		XRequestID:      requestID,
		XB3TraceID:      getHeader(xB3TraceID),
		XB3SpanID:       getHeader(xB3SpanID),
		XB3ParentSpanID: getHeader(xB3ParentSpanID),
		XB3Sampled:      getHeader(xB3Sampled),
		XB3Flag:         getHeader(xB3Flags),
		B3:              getHeader(b3),
```
In Jaeger, I only see the trace from IstioGateway to Service A but no span for ServiceA to ServiceB. 

Proxy log format is:
```
accessLogFormat: "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% \"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-B3-SAMPLED)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(X-B3-TRACEID)%\" \"%REQ(X-B3-SPANID)%\" \"%REQ(X-B3-PARENTSPANID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%\n"

```
The logs from the proxies: 

InressGateway:
```
[2021-12-07T21:26:50.090Z] "POST /init HTTP/1.1" 200 - via_upstream - "-" 828 755 47 47 "78.133.70.82, 34.102.217.248,35.191.10.246" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36" "1" "303cef67-e3cb-9ff9-80aa-614c19d502b3" "b8b2896792ea92498a84596ac59bb845" "8a84596ac59bb845" "-" "gs1-gs-x.domain.tld" "10.100.32.24:8005" outbound|80||gs1-api-game-server.d01.svc.cluster.local 10.100.37.6:46938 10.100.37.6:80 35.191.10.246:49843 - play-for-real
```
ServiceA Incoming
```
[2021-12-07T21:26:50.091Z] "POST /init HTTP/1.1" 200 - via_upstream - "-" 828 755 46 45 "78.133.70.82, 34.102.217.248,35.191.10.246" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36" "1" "303cef67-e3cb-9ff9-80aa-614c19d502b3" "b8b2896792ea92498a84596ac59bb845" "7845ffbbf6266607" "8a84596ac59bb845" "gs1-gs-x.domain.tld" "10.100.32.24:8005" inbound|8005|| 127.0.0.6:52327 10.100.32.24:8005 35.191.10.246:0 outbound_.80_._.gs1-api-game-server.d01.svc.cluster.local default
```
ServiceA Outgoing
```
[2021-12-07T21:26:50.095Z] "POST /core_service_v1.CoreService/GetBalance HTTP/2" 200 - via_upstream - "-" 55 17 18 18 "-" "grpc-go/1.36.1" "1" "303cef67-e3cb-9ff9-80aa-614c19d502b3" "b8b2896792ea92498a84596ac59bb845" "7845ffbbf6266607" "8a84596ac59bb845" "gs1-api-core:50101" "10.100.37.2:8007" outbound|50101||gs1-api-core.d01.svc.cluster.local 10.100.32.24:49578 10.100.66.69:50101 10.100.32.24:45616 - default
```
ServiceB Incoming
```
[2021-12-07T21:26:50.096Z] "POST /core_service_v1.CoreService/GetBalance HTTP/2" 200 - via_upstream - "-" 55 17 15 14 "-" "grpc-go/1.36.1" "1" "303cef67-e3cb-9ff9-80aa-614c19d502b3" "b8b2896792ea92498a84596ac59bb845" "7845ffbbf6266607" "8a84596ac59bb845" "gs1-api-core:50101" "10.100.37.2:8007" inbound|8007|| 127.0.0.6:53567 10.100.37.2:8007 10.100.32.24:49578 outbound_.50101_._.gs1-api-core.d01.svc.cluster.local default
```
Based on that proxy logs it seems that spainId and parrentSpanId are not replaced by the envoy and propagated "as is" down to the ServiceB.

As an alternative experiment I called Service B via grpcCurl from the pod of ServiceA:
`
./grpcurl -rpc-header 'x-b3-sampled: 1' -rpc-header 'x-b3-traceid: ebf7561051ac6433952010cd9cac40d3' -rpc-header 'x-b3-parentspanid: 297e3236182ca725' -rpc-header 'x-b3-spanid: 952010cd9cacdddd' -rpc-header 'x-request-id: a48ace99-0d2f-9fa9-9aad-83d5fe03c579' -plaintext -proto core_service_v1.proto gs1-api-core:50101 core_service_v1.CoreService/GetBalance
`

ServiceA outgoing:
```
[2021-12-07T21:37:57.691Z] "POST /core_service_v1.CoreService/GetBalance HTTP/2" 200 - via_upstream - "-" 63 17 29 29 "-" "grpcurl/v1.8.5 grpc-go/1.37.0" "1" "a48ace99-0d2f-9fa9-9aad-83d5fe03c579" "ebf7561051ac6433952010cd9cac40d3" "7fc4a980a41d3edf" "952010cd9cacdddd" "gs1-api-core:50101" "10.100.37.2:8007" outbound|50101||gs1-api-core.d01.svc.cluster.local 10.100.32.24:54452 10.100.66.69:50101 10.100.32.24:38614 - default
```
ServiceB Incoming:
```
[2021-12-07T21:37:57.692Z] "POST /core_service_v1.CoreService/GetBalance HTTP/2" 200 - via_upstream - "-" 63 17 28 27 "-" "grpcurl/v1.8.5 grpc-go/1.37.0" "1" "a48ace99-0d2f-9fa9-9aad-83d5fe03c579" "ebf7561051ac6433952010cd9cac40d3" "cbc05a179e71686a" "7fc4a980a41d3edf" "gs1-api-core:50101" "10.100.37.2:8007" inbound|8007|| 127.0.0.6:42243 10.100.37.2:8007 10.100.32.24:54452 outbound_.50101_._.gs1-api-core.d01.svc.cluster.local default
```
As you can see, in this case, spans were replaced properly.

Debug log with grpc metadata from the application ServiceB when called by ServiceA:
```
2021/12/07 21:57:25 gRPC server metadata x-b3-flags:[];x-forwarded-proto:[http];:authority:[gs1-api-core:50101];user-agent:[grpc-go/1.36.1];x-b3-traceid:[3ffc9fb9cb04232b3a0ec68e6cc286ff];x-b3-spanid:[ffa5bc3f75abc782];x-b3-parentspanid:[3a0ec68e6cc286ff];x-forwarded-client-cert:[By=spiffe://cluster.local/ns/d01/sa/gs1-api-core;Hash=c0306f7205d9ac84e9e5b312c942b9a3465da206292ff0c7c6a4f635ce15ae91;Subject="";URI=spiffe://cluster.local/ns/d01/sa/gs1-api-game-server];content-type:[application/grpc];x-request-id:[d9d13ed6-bb8b-9123-a75a-fe0e456a350c];x-b3-sampled:[1];b3:[];x-envoy-attempt-count:[1];
```
Debug log with grpc metadata from the application ServiceB when called by GRPCcurl:
```
2021/12/07 21:58:40 gRPC server metadata content-type:[application/grpc];x-envoy-attempt-count:[1];x-b3-traceid:[ebf7561051ac6433952010cd9cac40d3];x-b3-parentspanid:[c846478c2b88b686];x-b3-sampled:[1];:authority:[gs1-api-core:50101];user-agent:[grpcurl/v1.8.5 grpc-go/1.37.0];x-request-id:[a48ace99-0d2f-9fa9-9aad-83d5fe03c579];x-forwarded-proto:[http];x-forwarded-client-cert:[By=spiffe://cluster.local/ns/d01/sa/gs1-api-core;Hash=c0306f7205d9ac84e9e5b312c942b9a3465da206292ff0c7c6a4f635ce15ae91;Subject="";URI=spiffe://cluster.local/ns/d01/sa/gs1-api-game-server];x-b3-spanid:[817e1c7f84e7f9ec];
```

Istio installed via helm version 1.12.0 with the following settings:
```
global:
  tracer:
    zipkin:
      address: jaeger-collector.istio-system:9411
meshConfig:
  accessLogFile: /dev/stdout
  accessLogFormat: |
    [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% "%UPSTREAM_TRANSPORT_FAILURE_REASON%" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-B3-SAMPLED)%" "%REQ(X-REQUEST-ID)%" "%REQ(X-B3-TRACEID)%" "%REQ(X-B3-SPANID)%" "%REQ(X-B3-PARENTSPANID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%
pilot:
  traceSampling: 100
```

docker.io/istio/proxyv2:1.12.0
docker.io/istio/pilot:1.12.0
jaegertracing/all-in-one:1.28.0

At this point, I am lost and I am not sure why istio is not taking care of gRPC part of the trace and don't replace headers.
