### ISSUE TITLE
Http1.DPE error for tcp incoming traffic occassionally

### ISSUE THREAD

**Issue by arunpmohan** [istio/istio#36434]
Istio version : 1.9.5

k8s : 1.20 & 1.19

Our service definition is  as follows and the port of interest is 10101 which is a tcp port. 

```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-12-05T04:01:07Z"
  labels:
    app: centralmanagement` 
  name: smcentralmanagement-service
  namespace: sm
spec:
  ports:
  - name: tcp-ltm
    port: 10101
    protocol: TCP
    targetPort: tcp-ltm
  - name: grpc-ltm
    port: 10102
    protocol: TCP
    targetPort: tcp-ltm
  - name: tcp-rollbackmgr
    port: 10103
    protocol: TCP
    targetPort: tcp-rollbackmgr
  selector:
    app: smcentralmanagement
    haActive: "true"
  sessionAffinity: None
  type: ClusterIP
 
```
 

  Our outbound policy is REGISTRY_ONLY and this is an internal service in the same namespace.
 
  Now when other pods tries to connect to this centralmanagement service , we get this http1.dpe error in the istio proxy
  logs of this centralmanagement pods.
 
```
[2021-11-22T21:54:57.850Z] "- - HTTP/1.1" 400 DPE http1.codec_error - "-" 0 11 0 - "-" "-" "-" "-" "-" - - 192.168.162.154:10101 192.168.162.191:36656 outbound_.10101_._.smcentralmanagement-service.sm.svc.cluster.local -
[2021-11-22T21:54:57.949Z] "- - HTTP/1.1" 400 DPE http1.codec_error - "-" 0 11 0 - "-" "-" "-" "-" "-" - - 192.168.162.154:10101 192.168.162
```
 
 
Any help is appreciated. This goes away sometimes on pod restarts or istiod restarts. It doesnt happen always as well.
