### ISSUE TITLE
Support more custom Retry Policy, specifically for Retry-After Header

### ISSUE THREAD

**Issue by grantpaulson6** [istio/istio#36479]
**Describe the feature request**
From a high level, I would like it if Istio would support a http retry policy that honors the http header `Retry-After` in responses. 

The reason is, our application will intentionally return a 503 if a downstream service is unavailable, along with a header of `Retry-After`.  This however will cause istio's retry policy to kick in (we are just using the default policy right now), even though we don't want to retry.  And we do want to maintain the retry on a 503, just not when its an intentional 503 with a `Retry-After` from our application code.

On a lower level, this configuration would be unlocked if Istio supported more custom HTTPRetry fields for envoy. Specifically, if you could pass a [retriableHeaders field](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-retrypolicy-retriable-headers) that would allow us to tell envoy to not retry. (I think a [HeaderMatcher](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-headermatcher) of present_match set to false would work).

**Describe alternatives you've considered**
Not returning a 503 http code intentionally from our application code.  This is undesirable though, since we would have to start using a non-standard http code in its place.
Live with the undesired retries.  This is what we are currently doing.  The drawback is a proliferation of requests. We had a recent incident that triggered this, and we ended up flooding the downstream service with requests

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**
Not sure about this

[ ] Multi Cluster
[] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by ramaraochavali** [comment]
I think this seems a very specific use case. Can you please try with a custom envoy filter that patches the retry policy with the retriable headers?

**Comment by grantpaulson6** [comment]
ok we will look into that, thank you.

**Comment by Chehai** [comment]
+1 for this feature request.

The built-in retry interval is 25ms to 250ms, which is too short for some of our services. Retry-After header would be very nice!

**Comment by Kyslik** [comment]
This EnvoyFilter may be of help to people needing `retry-after` support:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: retry-after-test
  namespace: some-service
spec:
  exportTo:
  - .
  workloadSelector:
    labels:
      app: some-service
  configPatches:
    - applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_OUTBOUND
        routeConfiguration:
          portNumber: 80
          vhost:
            name: "example.com:80"
      patch:
        operation: MERGE
        value:
          route:
            retry_policy:
              rate_limited_retry_back_off:
                reset_headers:
                - name: retry-after
                max_interval: "3s"
```

This is used in tandem with TLS origination (traffic management does not work on HTTPS).

More resources:
- https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter.html#x-envoy-max-retries
- https://github.com/envoyproxy/envoy/blob/fb2d0a059d25d96937b7efcd9ad4d5e3a415eaab/api/envoy/config/route/v3/route_components.proto#L1399-L1412
- https://httpwg.org/specs/rfc7231.html#header.retry-after
