### ISSUE TITLE
External auth `AuthorizationPolicy` prevents `httpsRedirect` in `Gateway`

### ISSUE THREAD

**Issue by akirillov** [istio/istio#36498]
### Bug Description

I'm using a dedicated Istio ingress gateway with `httpsRedirect`. However, when I enable `AuthorizationPolicy` with external authorization, the initial HTTPS redirect is not happening and it looks like the `AuthorizationPolicy` takes precedence over the redirect. Is it expected behavior? Would appreciate it if somebody can point me to the issue.

Manifests:
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: ingress-gateway
  namespace: ingress
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*"
    tls:
      mode: SIMPLE
      credentialName: gateway-cert

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: dex
  namespace: ingress
spec:
  hosts:
  - "*"
  gateways:
  - ingress/ingress-gateway
  http:
  - name: "dex"
    match:
    - uri:
        prefix: "/dex"
    route:
    - destination:
        host: dex.auth.svc.cluster.local
        port:
          number: 5556
  - name: "auth"
    match:
    - uri:
        prefix: "/oauth2"
    route:
    - destination:
        host: oauth2-proxy.auth.svc.cluster.local
        port:
          number: 80
   - name: "httpbin"
     match:
     - uri:
         prefix: "/httpbin"
     rewrite:
       uri: "/"
     route:
     - destination:
         host: httpbin.default.svc.cluster.local
         port:
           number: 8000

---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: external-auth
  namespace: ingress
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
  action: CUSTOM
  provider:
    name: oauth2-proxy
  rules:
    - to:
        - operation:
            hosts: ["*"]
            notPaths: ["/dex/*"]
```

Before applying the `AuthorizationPolicy` curl output looks as expected:
```
$> curl -i -k -L "http://$INGRESS_HOST/httpbin/uuid"

HTTP/1.1 301 Moved Permanently
location: https://192.168.50.150/httpbin/uuid
date: Mon, 13 Dec 2021 21:25:01 GMT
server: istio-envoy
content-length: 0

HTTP/2 200
server: istio-envoy
date: Mon, 13 Dec 2021 21:25:01 GMT
content-type: application/json
content-length: 53
access-control-allow-origin: *
access-control-allow-credentials: true
x-envoy-upstream-service-time: 3

{
  "uuid": "a8c684da-bbf4-4ab1-91c3-b4b138192998"
}
```
Ingress Gateway log:
```
{"path":"/httpbin/uuid","authority":"192.168.50.150","upstream_local_address":null,"bytes_received":0,"route_name":null,"response_flags":"-","request_id":"6041674e-63d1-40cb-a9d8-e3359a073539","bytes_sent":0,"duration":0,"start_time":"2021-12-13T21:47:54.433Z","downstream_remote_address":"192.168.78.0:46131","connection_termination_details":null,"downstream_local_address":"192.168.75.20:80","upstream_service_time":null,"method":"GET","upstream_host":null,"upstream_cluster":null,"response_code":301,"requested_server_name":null,"x_forwarded_for":"192.168.78.0","protocol":"HTTP/1.1","user_agent":"curl/7.64.1","upstream_transport_failure_reason":null,"response_code_details":"direct_response"}
{"route_name":"httpbin","bytes_sent":53,"upstream_cluster":"outbound|8000||httpbin.default.svc.cluster.local","request_id":"44abc819-67a4-4d30-99a5-aaf3e01cda21","downstream_local_address":"192.168.75.20:443","duration":3,"response_code":200,"user_agent":"curl/7.64.1","upstream_local_address":"192.168.75.20:33728","response_flags":"-","start_time":"2021-12-13T21:47:54.465Z","upstream_host":"192.168.72.247:80","x_forwarded_for":"192.168.78.0","authority":"192.168.50.150","upstream_service_time":"2","upstream_transport_failure_reason":null,"path":"/httpbin/uuid","protocol":"HTTP/2","response_code_details":"via_upstream","connection_termination_details":null,"bytes_received":0,"requested_server_name":null,"method":"GET","downstream_remote_address":"192.168.78.0:37711"}
```

After the policy is applied, the initial HTTPS redirect is not happening anymore and the request is redirected to the authorizer app:
```
$> curl -i -k -L "http://$INGRESS_HOST/httpbin/uuid"

HTTP/1.1 302 Found
content-type: text/html; charset=utf-8
location: https://192.168.50.150/dex/auth?<omitted>
set-cookie: _oauth2_proxy_csrf=<omitted>
content-length: 296
date: Mon, 13 Dec 2021 21:26:14 GMT
server: istio-envoy

HTTP/2 302
content-type: text/html; charset=utf-8
location: /dex/auth/local?<omitted>
date: Mon, 13 Dec 2021 21:26:14 GMT
content-length: 1594
x-envoy-upstream-service-time: 8
server: istio-envoy

HTTP/2 400
date: Mon, 13 Dec 2021 21:26:14 GMT
content-length: 816
content-type: text/html; charset=utf-8
x-envoy-upstream-service-time: 2
server: istio-envoy

<!DOCTYPE html>
<html>
   <DEX LOGIN SCREEN HTML>
</html>
```
Ingress Gateway log:
```
{"upstream_local_address":null,"connection_termination_details":null,"x_forwarded_for":"192.168.78.0","path":"/httpbin/uuid","start_time":"2021-12-13T21:40:23.200Z","protocol":"HTTP/1.1","method":"GET","authority":"192.168.50.150","requested_server_name":null,"bytes_received":0,"user_agent":"curl/7.64.1","response_code":302,"duration":3,"response_code_details":"ext_authz_denied","downstream_local_address":"192.168.75.20:80","upstream_host":null,"upstream_transport_failure_reason":null,"request_id":"1b359bd4-5d89-49a0-9456-68e516f1a791","upstream_cluster":null,"bytes_sent":296,"upstream_service_time":null,"route_name":null,"response_flags":"-","downstream_remote_address":"192.168.78.0:39640"}
{"user_agent":"curl/7.64.1","method":"GET","upstream_host":"192.168.72.253:5556","authority":"192.168.50.150","upstream_local_address":"192.168.75.20:51102","requested_server_name":null,"route_name":"dex","response_flags":"-","x_forwarded_for":"192.168.78.0","downstream_remote_address":"192.168.78.0:49174","upstream_transport_failure_reason":null,"downstream_local_address":"192.168.75.20:443","path":"/dex/auth?<omitted>","duration":8,"protocol":"HTTP/2","start_time":"2021-12-13T21:40:23.245Z","response_code":302,"response_code_details":"via_upstream","bytes_received":0,"upstream_cluster":"outbound|5556||dex.auth.svc.cluster.local","bytes_sent":1594,"request_id":"fe4d5732-6261-4949-baec-59e4120fbdc0","upstream_service_time":"7","connection_termination_details":null}
{"x_forwarded_for":"192.168.78.0","connection_termination_details":null,"route_name":"dex","upstream_host":"192.168.72.253:5556","upstream_service_time":"1","protocol":"HTTP/2","path":"/dex/auth/local?<omitted>","requested_server_name":null,"upstream_cluster":"outbound|5556||dex.auth.svc.cluster.local","response_flags":"-","user_agent":"curl/7.64.1","bytes_sent":816,"downstream_local_address":"192.168.75.20:443","upstream_local_address":"192.168.75.20:51102","response_code":400,"authority":"192.168.50.150","request_id":"7e169f8b-78ac-496f-a164-671bcc5371ba","duration":1,"bytes_received":0,"start_time":"2021-12-13T21:40:23.256Z","response_code_details":"via_upstream","downstream_remote_address":"192.168.78.0:49174","method":"GET","upstream_transport_failure_reason":null}
```

### Version

```prose
$ istioctl version
client version: 1.11.4
control plane version: 1.12.1
data plane version: 1.12.1 (4 proxies)

$ kubectl version
Client version: v1.22.2
Server version: v1.21.6
```

**Comment by akirillov** [comment]
Thanks, @howardjohn. My confusion was related to the separation of concerns between the `Gateway` and the rest of the traffic management resources. I'd have expected the `Gateway` redirect to be applied prior to the rest of the configuration takes the effect (including `AuthorizationPolicies`).

Following your advice, I've excluded port `80` from the `AuthorizationPolicy` and now the redirect works:
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: external-auth
  namespace: ingress
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
  action: CUSTOM
  provider:
    name: oauth2-proxy
  rules:
    - to:
        - operation:
            hosts: ["*"]
            notPaths: ["/dex/*"]
            notPorts: ["80"]
```

Not sure how elegant this solution is compared to just disabling HTTP at the `Gateway`.
