### ISSUE TITLE
changes in delegate virtual service do not take effect

### ISSUE THREAD

**Issue by sschepens** [istio/istio#36525]
### Bug Description

Similar to #29123 seems to be happening with Istio 1.12.

Suppose we have following setup:

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: foo
  namespace: foo
spec:
  hosts:
  - bar.bar
  http:
  - match:
    - uri:
        prefix: "/prefix"
    delegate:
      name: bar
      namespace: bar
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: bar
  namespace: bar
spec:
  http:
  - route:
    - destination:
        host: bar.bar
        subset: stable
      weight: 90
    - destination:
        host: bar.bar
        subset: canary
      weight: 10
```

When we change the `bar` virtual service, for example, change the weight from 90,10 to 80,20, routes are not updated on the foo sidecar proxy. Restarting the pod does not get the routes updated either. Triggering some sort of update over the `foo` virtual service does update the routes.

### Version

```prose
$ istioctl version
client version: 1.12.1
control plane version: 1.12.1
data plane version: 1.12.1

$ kubectl version --short
Client Version: v1.21.1
Server Version: v1.21.2-eks-0389ca3
```

### Additional Information

From Istiod logs I can see that VirtualServices are indeed being merged, and an update pushed, but if I check a config dump of the proxy, the weights are not updated.

**Comment by dddddai** [comment]
The root cause is that the rds cache is not refreshed after delegate virtual service updates, I will submit a patch to fix it

For quick fix, you can disable rds cache by setting the env var of istiod:
```yaml
env:
- name: PILOT_ENABLE_RDS_CACHE
  value: "false"
```

Hope this helps :)

/assign
