### ISSUE TITLE
IngressClass Istio not working with Kubernetes Ingress Resources

### ISSUE THREAD

**Issue by raklev20** [istio/istio#36527]
### Bug Description

Using this link https://istio.io/latest/docs/tasks/traffic-management/ingress/kubernetes-ingress/ I want to integrate my Kubernetes Ingress ( v1.1.0 ) with Istio. Take into the consideration that I'm using Kubernetes 1.22 the apiVersion is: networking.k8s.io/v1 for both IngressClass and Ingress. With all of these I cannot run my tests . Here are the logs from Ingress-Nginx-Controller POD:

`I1215 18:57:45.320087       7 store.go:420] "Ignoring ingress because of error while validating ingress class" ingress="de   fault/example-ingress" error="no object matching key \"istio\" in local store"
I1215 19:14:21.653475       7 store.go:502] "ignoring ingressclass as the spec.controller is not the same of this ingress"    ingressclass="istio"`

My config file:
```
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: istio
spec:
  controller: istio.io/ingress-controller
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
spec:
  ingressClassName: istio
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: coffee-svc
            port:
              number: 80
```

### Version

```prose
istioctl version:
client version: 1.12.1
control plane version: 1.12.1
data plane version: 1.12.1 (3 proxies)


kubectl version:
Client Version: v1.22.0
Server Version: v1.22.4

Ingress Version: 
k8s.gcr.io/ingress-nginx/controller:v1.1.0@sha256:f766669fdcf3dc26347ed273a55e754b427eb4411ee075a53f30718b4499076a
```
