### ISSUE TITLE
Unexpected behaviour using netcat to test connectivity to services

### ISSUE THREAD

**Issue by mikmatko** [istio/istio#36540]
### Bug Description

Using netcat to test connectivity to services gives unexpected result when sidecar is enabled.

Given the following target Service:
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: app2
  name: app2
spec:
  ports:
  - name: http-5000
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app.kubernetes.io/name: app2
  type: ClusterIP
```

Testing connectivity from a pod with sidecar disabled:
```
example@app1-d9f66b468-vz67j:/app$ nc -vz app2.mynamespace.svc.cluster.local 5000
app2.mynamespace.svc.cluster.local [10.232.18.135] 5000 (?) open

example@app1-d9f66b468-vz67j:/app$ nc -vz app2.mynamespace.svc.cluster.local 1234
app2.mynamespace.svc.cluster.local [10.232.18.135] 1234 (?) : Connection timed out
```

Testing connectivity from a pod with sidecar enabled:
```
example@app1-6596487fc4-54tvn:/app$ nc -vz app2.mynamespace.svc.cluster.local 5000
app2.mynamespace.svc.cluster.local [10.232.18.135] 5000 (?) open

example@app1-6596487fc4-54tvn:/app$ nc -vz app2.mynamespace.svc.cluster.local 1234
app2.mynamespace.svc.cluster.local [10.232.18.135] 1234 (?) open
```

As can be seen from the sidecar-enabled example, netcat implies that port 1234 can be connected to. The result is the same if I switch from port 1234 to anything else.

What explains this behaviour? My assumption would be that I can use netcat to test if I have connectivity to a service, but now it returns the exact same result for _any_ given port.

### Version

```prose
client version: 1.10.4
control plane version: 1.10.4
data plane version: 1.10.4 (93 proxies), 1.10.0 (6 proxies)
```
