### ISSUE TITLE
Add notHosts in Sidecar resource

### ISSUE THREAD

**Issue by fatedier** [istio/istio#36552]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Now we can allow egress traffic only to a specified namespace by [sidecar](https://istio.io/latest/docs/reference/config/networking/sidecar/#IstioEgressListener), but we can't just exclude some namespaces.

In my scenario, I want to exclude kube-system and monitoring namespace(Services in these namespaces generated too many unnecessary envoy configs). Now I must list all other namespaces in my Sidecar config.

We can do this thing simple with `notHosts` config:

```
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
  namespace: istio-system
spec:
  egress:
  - notHosts:
    - "kube-system/*"
    - "monitoring/*"
```

**Describe alternatives you've considered**
I'm not sure if there are already other solutions.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
