### ISSUE TITLE
gateway-api: Gateway for TLS does not become NotReady when tls.mode is missing

### ISSUE THREAD

**Issue by nak3** [istio/istio#36562]
### Bug Description

- TLSRoute does not become `Ready` when Gateway misses `tls.mode`. If TLSRoute requires Gateway's `tls.mode: Passthrough`, gateway should show the status.
- Please refer to the following reproduce steps.

#### 1. create the following Gateway and TLS Route

```yaml
cat <<EOF | kubectl apply -f -
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: gateway
  namespace: istio-ingress
spec:
  gatewayClassName: istio
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    hostname: "*.example.com"
    name: tls
    port: 443
    protocol: TLS
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: tls
  namespace: default
spec:
  parentRefs:
  - name: gateway
    namespace: istio-ingress
  rules:
  - backendRefs:
    - name: https
      port: 443
EOF
```

#### 2. Gateway is Ready but TLSRoute is `InvalidParentReference`

```
$ kubectl get gateway -n istio-ingress  gateway  -o yaml
 ...
  - lastTransitionTime: "2021-12-19T07:39:26Z"
    message: Gateway valid, assigned to service(s) gateway.istio-ingress.svc.cluster.local:443
    observedGeneration: 17
    reason: ListenersValid
    status: "True"
    type: Ready
```

```yaml
$ kubectl get tlsroutes.gateway.networking.k8s.io -o yaml tls
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
  ...
status:
  parents:
  - conditions:
    - lastTransitionTime: "2021-12-19T07:39:27Z"
      message: kind gateway.networking.k8s.io/v1alpha2/TLSRoute is not allowed
      observedGeneration: 9
      reason: InvalidParentReference
      status: "False"
      type: Accepted
    controllerName: istio.io/gateway-controller
    parentRef:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway
      namespace: istio-ingress
```

#### 3. The problem could be fixed by adding `tls.mode: Passthrough` in Gateway.

```
$ kubectl edit gateway -n istio-ingress  gateway  -o yaml
  ...
    tls:
      mode: Passthrough
```

So the problem is in Gateway not TLSRoute. The Gateway should give us a hint what was wrong.

### Version

```prose
$ istioctl version
client version: 1.13-alpha.90282c9ff5c1c7dfae2c9f15d2a38bcd15b9aa2a
control plane version: 1.13
data plane version: 1.13-alpha.90282c9ff5c1c7dfae2c9f15d2a38bcd15b9aa2a (2 proxies)
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
