### ISSUE TITLE
Mark some clusters use only service discovery

### ISSUE THREAD

**Issue by LawlietLi** [istio/istio#36588]
**Describe the feature request**

We have built a multi-region, multi-cluster system. Each region has one istiod to manage the clusters in that region. The istiod in each region need discovers clusters in all regions. (ensure that cross-region network disconnects can run independently for each region)

However, I found that if multiple istiods discover the same cluster,  each istiod injects a certificate into the cluster. This makes it infeasible if we want each region to issue a separate certificate via the root certificate.

Can we add an annotation in the cluster's secret that mark this cluster for service discovery only, without cluster management operations such as certificate injection.

**Describe alternatives you've considered**

We can add an annotation like this:
```yaml
apiVersion: v1
kind: Secret
metadata:
  annotations:
    istio.io/clusterContext: {{cluster_name}}
  name: istio-cluster-context
  namespace: istio-system
  labels:
    istio/multiCluster: "true"
    istio/discoveryOnly: "true"
```
If a cluster is marked as `istio/discoveryOnly: "true"`, operations such as certificate injection are not performed.
if it is make sense, I can work on it. 

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
