### ISSUE TITLE
Ability to send traces to AWS X-ray

### ISSUE THREAD

**Issue by saaish** [istio/istio#36599]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
It would be good to have the istio envoy out of the box send traces to X-ray. We can run a X-ray agent daemon set / Distro for OpenTelemetry to collect the traces and send it to X-ray.

The current version of envoy used by Istio doesn't have support for X-ray is what I read. Correct me if I'm wrong.
**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
@saaish PTAL https://aws-otel.github.io/docs/getting-started/x-ray

gernerally envoy support to send trace to OTEL in zipkin protocol

**Comment by zirain** [comment]
> @zirain should we own a write-up of OTel tracing integrations via the collector and Telemetry API?

a simple example can be found [here](https://github.com/istio/istio/tree/master/samples/open-telemetry), plan to add a doc in istio.io, but I'm poor with writing in English.

**Comment by douglas-reid** [comment]
> a simple example can be found [here](https://github.com/istio/istio/tree/master/samples/open-telemetry), plan to add a doc in istio.io, but I'm poor with writing in English.

No worries on the English side. I'm happy to help get it into shape.

**Comment by zirain** [comment]
linked to https://github.com/istio/istio.io/pull/10977

**Comment by matcasx** [comment]
I would like to use Istio to send traces to X-ray. I tried to follow the comments in this thread, but I couldn't get the results I wanted.
There are a few things I don't understand:
- Can I use Telemetry CR to configure Istio if I used Helm for the installation?
- If I enable Istio to send accesslog to the OTel collector is it the same as sending traces? 
- Is there any way to send traces from istio-proxy and have the "Service Map" and "traces" section populated on x-ray?

**Comment by muthuct** [comment]
Hi @matcasx did you make any progress on the Istio to AWS X-Ray integration via ADOT? Right now there seems to be very limited info on sending Istio traces via OpenTelemetry to AWS X-Ray with ADOT. Is there a recommended approach suggested by Istio team for this?

**Comment by dallasanta** [comment]
I see two ways of integrating with X-Ray, but none of them is ideal.

1. Using Istio/Envoy's native support of zipkin and otel-tracing with Otel Collector

AWS X-Ray trace id is looks like "1-63441c4a-abcdef012345678912345678". The first token is the version (always 1), the second one is the current timestamp and the final one is a random string. By removing the hyphens and version it becomes a 32-alphanumeric id that could match up with both otel-tracing and zipkin. The problem is that X-Ray validates the timestamp part, which should be within the last 30 days and, really, it should be the current timestamp to properly use the search tools in AWS X-Ray.

So for it to work the tracing headers must be generated externally to istio, so istio can propagate it. Additionally, envoy's spans do not conform with otel semantic conventions so it requires additional transformation.

A configuration for that looks like that:
Istio Config
```
    extensionProviders:
    # either
      - name: zipkin
        zipkin:
          service: amazon-xray-otel-collector.amazon-xray.svc.cluster.local
          port: 9411
      - name: otel-tracing
        opentelemetry:
          port: 4317
          service: amazon-xray-otel-collector.amazon-xray.svc.cluster.local
```
And it requires an otel collector pipeline that receives otlp/zipkin and exports to x-ray.
```
 processors:
    attributes/fix_status_code_type:
      actions:
        - key: http.status_code
          action: convert
          converted_type: int

    span/set_status_ok:
      include:
        match_type: regexp
        attributes:
          - key: http.status_code
            value: "^(2|3).*"
      status:
        code: "Ok"

    span/set_status_error:
      exclude:
        match_type: regexp
        attributes:
          - key: http.status_code
            value: "^(2|3).*"
      status:
        code: "Error"
services:
    pipelines:
      traces:
        receivers:
          - otlp
        processors:
          - span/set_status_ok
          - span/set_status_error
          - attributes/fix_status_code_type
          - batch
        exporters:
          - awsxray

```

2. Using Envoy Filter to setup Envoy's native X-Ray support

Envoy's X-Ray extension provides a better way to integrate with X-Ray, but it can currently only be configured via Envoy Filter in Istio. It creates a problem that the node name cannot be configured per workload, so it is a hardcoded value and all the traces appear under a single node in X-Ray console. Presumably Aws App Mesh configures this extension with the correct value of "segment_name".

The filter looks like:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: add-xray-tracing
spec:
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: ANY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
            tracing:
              http:
                name: envoy.tracers.xray
              provider:
                name: "envoy.tracers.xray"
                typed_config:
                  "@type": type.googleapis.com/envoy.config.trace.v3.XRayConfig
                  segment_name: "Mesh" # This should be statically set and can't be configured per workload!
                  "@type": "type.googleapis.com/envoy.config.trace.v3.XRayConfig"
                  segment_name: Envoy
                  daemon_endpoint:
                    protocol: UDP
                    address: 172.20.0.66
                    port_value: 2000
```

It would be great if we could have this Envoy's X-Ray extension to be configured via Istio!
