### ISSUE TITLE
istio proxy hostNetwork cann't change hostPort to 80

### ISSUE THREAD

**Issue by jingslunt** [istio/istio#36590]
##### Bug Description

                - path: spec.template.spec.containers.[name:istio-proxy].ports.[containerPort:8080].hostPort
                  value: 80
                - path: spec.template.spec.containers.[name:istio-proxy].ports.[containerPort:8443].hostPort
                  value: 443
```
=======================================
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio
spec:
  profile: default
  components:
    egressGateways:
    - name: istio-egressgateway
      enabled: true
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          service:
            type: ClusterIP #change to NodePort, ClusterIP or LoadBalancer if need be
          replicaCount: 1
          tolerations:
            - key: node-role.kubernetes.io/master
              operator: Exists
              effect: NoSchedule
          nodeSelector:
            istio-gateway-ingress: enable
          resources:
            limits:
              cpu: 2000m
              memory: 2Gi
          strategy:
            type: RollingUpdate
            rollingUpdate:
              maxSurge: 0%
              maxUnavailable: 100%
          overlays:
            - apiVersion: apps/v1
              kind: Deployment
              name: istio-ingressgateway
              patches:
                - path: spec.template.spec.hostNetwork
                  value: true
                - path: spec.template.spec.dnsPolicy
                  value: ClusterFirstWithHostNet
%               - path: spec.template.spec.containers.[name:istio-proxy].ports.[containerPort:8080].hostPort
%                  value: 80
%                - path: spec.template.spec.containers.[name:istio-proxy].ports.[containerPort:8443].hostPort
%                  value: 443
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - istio-ingressgateway
                  topologyKey: kubernetes.io/hostname
```
##### Version

```prose
newer 12.1
```

##### Additional Information
```
not product 
internal test env
```
