### ISSUE TITLE
Istio Gateway Helm Chart 1.12 and Above can not be added as a Subchart

### ISSUE THREAD

**Issue by mohammadsrahman** [istio/istio#36595]
### Bug Description

When trying to create a Helm Chart and adding gateway as a subchart helm lint throws errors and installation or upgrade fails with the following message

gateway:
- (root): Additional property global is not allowed

e.g My Chart.yaml looks like

```
name: istio-helm
...
dependencies:
  - name: base
    version: 1.12.1
    repository: https://istio-release.storage.googleapis.com/charts
  - name: istiod
    version: 1.12.1
    repository: https://istio-release.storage.googleapis.com/charts
  - name: gateway
    version: 1.12.1
    repository: https://istio-release.storage.googleapis.com/charts
```

### Version

```prose
client version: 1.12.0 and Above
control plane version: 1.12.0 and Above
```

### Additional Information

A hack or quick fix for this is by Downloading the Chart and using a local version with the following value set in values.schema.json

```
...
  "additionalProperties": true,
...
```

This maybe the fix or to add the global object to the schema.
