### ISSUE TITLE
X-Forwarded-Proto header set to `http` instead of `https` on subsequent request

### ISSUE THREAD

**Issue by marcbachmann** [istio/istio#36612]
### Bug Description

I'm experiencing an issue where only the first request on a server contains the `X-Forwarded-Proto: https` header.
All the requests after the first one contain `X-Forwarded-Proto: http`.

I've recently set up a QUIC listener. Maybe that's the source of the problem? 
```
  values:
    pilot:
      autoscaleEnabled: false
      traceSampling: 100
      env:
        PILOT_ENABLE_QUIC_LISTENERS: "true"
```

### Version

```prose
$ istioctl version
client version: 1.12.1
control plane version: 1.12.1
data plane version: 1.12.1 (4 proxies)

$ kubectl version --short
Client Version: v1.22.4
Server Version: v1.22.4+k3s1
```

### Additional Information

Example deployment that outputs the headers:

<details>
  <summary>deployment.yaml</summary>
  
  ```yaml
  ---
  apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  metadata:
    name: echo
  spec:
    hosts:
    - domain.example.com
    gateways:
    - istio-system/default
    http:
    - match:
      - uri:
          prefix: /
      route:
      - destination:
          host: echo
          port:
            number: 8080
  
  ---
  apiVersion: v1
  kind: Service
  metadata:
    name: echo
  spec:
    selector:
      app: echo
    ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  
  ---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: echo
  spec:
    replicas: 1
    strategy:
      type: RollingUpdate
    selector:
      matchLabels:
        app: echo
    template:
      metadata:
        labels:
          app: echo
      spec:
        enableServiceLinks: false
        containers:
        - name: echo-server
          image: jmalloc/echo-server:0.3.1
          resources:
            limits: {cpu: "0.5", memory: 200Mi}
            requests: {cpu: "0", memory: 5Mi}
          ports:
          - containerPort: 8080
            name: http
  ```
</details>

Overriding the `X-Forwarded-Proto` header of the `VirtualHost` will work as workaround:
```yaml
  - route:
    - destination:
        host: echo
      headers:
        request:
          set:
            X-Forwarded-Proto: https

```
