### ISSUE TITLE
Unable to do Gateway Auto Injection with Istio Revisions

### ISSUE THREAD

**Issue by kameshsampath** [istio/istio#36615]
### Bug Description

With a scenario of I am installing Istio Revisioned Control Plane and Gateways on separate namespace like `istio-system` and `istio-gateways`. using a Operators based install I see the Istio Gateways does not come up with `/inject` failing with certificate with misssing SANs `istiod-<istio-revision>.istio-system.svc` 

```
LAST SEEN   TYPE      REASON                         OBJECT                                   MESSAGE
42s         Warning   FailedCreate                   replicaset/ingressgateway-7d59f6cd7      Error creating: Internal error occurred: failed calling webhook "rev.object.sidecar-injector.istio.io": Post "https://istiod-1-11-5.istio-system.svc:443/inject?timeout=10s": x509: certificate is valid for istiod.istio-system.svc, istiod-remote.istio-system.svc, istio-pilot.istio-system.svc, not istiod-1-11-5.istio-system.svc
3m26s       Normal    ScalingReplicaSet              deployment/ingressgateway                Scaled up replica set ingressgateway-7d59f6cd7 to 1
3m26s       Normal    NoPods                         poddisruptionbudget/ingressgateway       No matching pods found
3m26s       Normal    IPAllocated                    service/ingressgateway                   Assigned IP "192.168.64.100"
11s         Warning   FailedGetResourceMetric        horizontalpodautoscaler/ingressgateway   failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io)
26s         Warning   FailedComputeMetricsReplicas   horizontalpodautoscaler/ingressgateway   invalid metrics (1 invalid out of 1), first error is: failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io)
```

This seem to be regression of https://github.com/istio/istio/issues/27501 ?

CC: @linsun  @nmnellis 

[manifests.zip](https://github.com/istio/istio/files/7764094/manifests.zip)

### Version

```prose
istioctl version
client version: 1.11.5
control plane version: 1.11.5
data plane version: 1.11.5 (3 proxies), 1.11.0 (3 proxies)

kubectl version --short
Client Version: v1.21.6
Server Version: v1.21.6
```

**Comment by kameshsampath** [comment]
Did further debug and analysis,  I see this behaviour happens when I set the `vm-network` value in the Control Plane CR  like

```yaml
values:
    # https://istio.io/v1.5/docs/reference/config/installation-options/#global-options
    global:
      meshID: mesh1
      # needed for connecting VirtualMachines to the mesh
      network: bgc-network1
      # needed for annotating istio metrics with cluster (should match trust domain and GLOO_MESH_CLUSTER_NAME)
      multiCluster:
        clusterName: cluster1
      meshNetworks:
        "bgc-network1":
          endpoints:
          - fromRegistry: "cluster1"
          gateways:
          - registryServiceName: ingressgateway.istio-gateways.svc.cluster.local
            port: 443
        #  gateway pod fails when I set this :(
        vm-network:  "bgc-vm-network"  
```

I am not sure why setting vm-network has effect on the istiod certs ???

@ pseudonator
