### ISSUE TITLE
Trying to download istio on Mac M1

### ISSUE THREAD

**Issue by ahmad1508** [istio/istio#36614]
### Bug Description

I've been trying to install istio on my mac M1 for couple of days it's just getting to this point and then giving me an error.
Is that related to the macbook or is there a solution to fix it ?

### Version

```prose
ahmad@MacBook-Pro-de-Ahmad istio-1.11.4 % istioctl install --set profile=demo -y 
✔ Istio core installed                                                                                                                                                                                                                      
✔ Istiod installed                                                                                                                                                                                                                          
✘ Egress gateways encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the conditionsystem/istio-ingressgateway                                                                         
                                                                                                    
✘ Ingress gateways encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the condition                                                                                                   
                                                                                                   
- Pruning removed resources                                                                                                                                                                                                                   Removed HorizontalPodAutoscaler:istio-system:istio-ingressgateway.
  Removed HorizontalPodAutoscaler:istio-system:istiod.
Error: failed to install manifests: errors occurred during operation
```


### Additional Information

_No response_

**Comment by bianpengyuan** [comment]
Check your ingress gateway pod and deployment status. that should give you some hint about what's wrong.

**Comment by monsteredc** [comment]
Istio currently doesn't support arm. You may try this https://github.com/querycap/istio.

**Comment by bianpengyuan** [comment]
> Istio currently doesn't support arm. You may try this https://github.com/querycap/istio.

@monsteredc I might be wrong, but I think the issue is not really arm support, but rather their proxy cannot become ready?

**Comment by zirain** [comment]
@ahmad1508 can you check the istiod an ingressgateway logs after istioctl exited.
```
kubectl logs <POD_NAME> -nistio-system
```

**Comment by monsteredc** [comment]
@bianpengyuan It could. I encountered the issue at the same progress, and it worked after setting:
```
spec:
  components:
    pilot:
      k8s: # each components have to set this
        affinity: &affinity
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/arch
                      operator: In
                      values:
                        - arm64
                        - amd64
    egressGateways:
      - name: "istio-egressgateway"
        k8s:
          affinity: *affinity
    ingressGateways:
      - name: "istio-ingressgateway"
        k8s:
          affinity: *affinity
```

It might be the platform issue, and I'm not pretty sure. Needs more info to determine the problem.
