### ISSUE TITLE
Eds is not correctly when in service entry addresses not has svc port

### ISSUE THREAD

**Issue by Patrick0308** [istio/istio#36645]
### Bug Description

service entry:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-ip-port-test
spec:
  hosts:
  - foo.bar.com
  location: MESH_EXTERNAL
  ports:
  - number: 8080
    name: http-8080
    protocol: HTTP
  - number: 9080
    name: http-9080
    protocol: HTTP
  - number: 7080
    name: http-7080
    protocol: HTTP
  resolution: STATIC
  endpoints:
  - address: 1.1.1.1
    ports:
      http-8080: 8080
  - address: 2.2.2.2
    ports:
      http-9080: 9080
  - address: 3.3.3.3
    ports:
      http-7080: 7080
```
See eds is 
``` bash
$ .istioctl/bin/istioctl pc endpoints helloworld-v2-755b5c9b6b-t2vqf.sample | grep foo.bar.com
1.1.1.1:7080                     HEALTHY     OK                outbound|7080||foo.bar.com
1.1.1.1:8080                     HEALTHY     OK                outbound|8080||foo.bar.com
1.1.1.1:9080                     HEALTHY     OK                outbound|9080||foo.bar.com
2.2.2.2:7080                     HEALTHY     OK                outbound|7080||foo.bar.com
2.2.2.2:8080                     HEALTHY     OK                outbound|8080||foo.bar.com
2.2.2.2:9080                     HEALTHY     OK                outbound|9080||foo.bar.com
3.3.3.3:7080                     HEALTHY     OK                outbound|7080||foo.bar.com
3.3.3.3:8080                     HEALTHY     OK                outbound|8080||foo.bar.com
3.3.3.3:9080                     HEALTHY     OK                outbound|9080||foo.bar.com
```
1.1.1.1:7080 and 2.2.2.2:8080 and so no is not really exist endpoint.
An optional correct result is
``` bash
$ .istioctl/bin/istioctl pc endpoints helloworld-v2-755b5c9b6b-t2vqf.sample | grep foo.bar.com
1.1.1.1:8080                     HEALTHY     OK                outbound|7080||foo.bar.com
2.2.2.2:9080                     HEALTHY     OK                outbound|7080||foo.bar.com
3.3.3.3:7080                     HEALTHY     OK                outbound|7080||foo.bar.com
1.1.1.1:8080                     HEALTHY     OK                outbound|8080||foo.bar.com
2.2.2.2:9080                     HEALTHY     OK                outbound|8080||foo.bar.com
3.3.3.3:7080                     HEALTHY     OK                outbound|8080||foo.bar.com
1.1.1.1:8080                     HEALTHY     OK                outbound|9080||foo.bar.com
2.2.2.2:9080                     HEALTHY     OK                outbound|9080||foo.bar.com
3.3.3.3:7080                     HEALTHY     OK                outbound|9080||foo.bar.com
```
The second correct result is 
``` bash
$ .istioctl/bin/istioctl pc endpoints helloworld-v2-755b5c9b6b-t2vqf.sample | grep foo.bar.com
1.1.1.1:8080                     HEALTHY     OK                outbound|8080||foo.bar.com
2.2.2.2:9080                     HEALTHY     OK                outbound|9080||foo.bar.com
3.3.3.3:7080                     HEALTHY     OK                outbound|7080||foo.bar.com
```

### Version

```prose
$ istioctl version
client version: 1.11.5
istiod version: 1.11-dev
data plane version: 1.11.5
```

**Comment by bianpengyuan** [comment]
You will need to set endpoints ports explicitly for all service ports if you don't want to fail back to service ports:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-ip-port-test
spec:
  hosts:
  - foo.bar.com
  location: MESH_EXTERNAL
  ports:
  - number: 8080
    name: http-8080
    protocol: HTTP
  - number: 9080
    name: http-9080
    protocol: HTTP
  - number: 7080
    name: http-7080
    protocol: HTTP
  resolution: STATIC
  endpoints:
  - address: 1.1.1.1
    ports:
      http-8080: 8080
      http-9080: 8080
      http-7080: 8080
  - address: 2.2.2.2
    ports:
      http-9080: 9080
      http-8080: 9080
      http-7080: 9080
  - address: 3.3.3.3
    ports:
      http-9080: 7080
      http-8080: 7080
      http-7080: 7080
```
