### ISSUE TITLE
Sidecar Settings will not be respected for Kubelet Probes

### ISSUE THREAD

**Issue by sass1997** [istio/istio#36649]
### Bug Description

I do have service which does have at the moment a authentication setting on it's liveness and readiness endpoints which required either a role or hasIpAddress 127.0.0.1. Due to the change https://istio.io/latest/blog/2021/upcoming-networking-changes/ I'm forced to change this authenication schema. However I wanted to upgrade istio earlier than patching my application. I've tried to add as suggested the Sidecar definition. This works properly if I do access the service from another service but the probes on startup from kubelet will not be transferred to localhost as it should.

Sidecar Definition:
```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: test-app
spec:
  workloadSelector:
    labels:
      app: test-app
  ingress:
    - port:
        number: 8082
        protocol: HTTP
        name: http-metrics
      defaultEndpoint: 127.0.0.1:8082
```
Logs from istio-proxy
```
2021-12-28T09:41:17.268217Z    error    Request to probe app failed: Get "http://11.32.8.22:8082/actuator/health/liveness": dial tcp 127.0.0.6:0->11.32.8.22:8082: connect: connection refused, original URL path = /app-health/test-app/startupz
```

### Version

```prose
❯ istioctl version                                                                                                             
client version: 1.12.1
control plane version: 1.12.1
data plane version: 1.12.1 (48 proxies), 1.9.1 (3 proxies)
❯ kubectl version --short                                                                                                     
Client Version: v1.23.1
Server Version: v1.20.6+vmware.1
❯ helm version --short                                                                                                         
v3.7.0+geeac838
```
