### ISSUE TITLE
tls passthrough not working with k8s ingress .

### ISSUE THREAD

**Issue by Mangaal** [istio/istio#36646]
### Bug Description

I have tried to use tls passthrough with istio controller and k8s ingress but it does not work but with Gateway and VirtualServce it works.  here is the ingress  YAML . 

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: sample-ingress
  namespace: istio-system
spec:
  tls:
  - hosts:
      - example.com
  rules:
  - host: example.com
    http:
      paths:
      - path: /hello
        backend:
          serviceName: sample-service
          servicePort: 443
```
when I try to curl the host I got a message port 443 refused to connect.

### Version

```prose
istioctl version
 client version :1.9.4
 control plane version :1.9.4
kubectl version --short
 client version :1.20.0
 control plane version :1.20.0
```
istioctl proxy-config listeners istio-ingressgateway-795n9.istio-system
ADDRESS PORT MATCH DESTINATION
0.0.0.0 80 ALL Route: http.80
0.0.0.0 15021 ALL Inline Route: /healthz/ready*
0.0.0.0 15090 ALL Inline Route: /stats/prometheus*

### Additional Information

Error I got
on creation of the Ingress, istio is not opening listeners on port 443, so I am getting connection refused

**Comment by howardjohn** [comment]
Is `servicePort: 433` a typo in the issue or in your actual config? tht could cause it to not work

**Comment by Mangaal** [comment]
> typo
Hi @howardjohn  
there is no typo, it works when I terminate the tls traffic at ingress. here is my ingress YAML with tls termination at the ingress 

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: sample-ingress
  namespace: istio-system
spec:
  tls:
  - hosts:
      - example.com
    secretName: ca-issuer-example-com
  rules:
  - host: example.com
    http:
      paths:
      - path: /hello
        backend:
          serviceName: sample-service
          servicePort: 443

 
```

there I am passing tls.secretName to terminate tls
