### ISSUE TITLE
Helm chart for gateway does not contain image name nor tag (Istio 1.12.1 and Istio 1.12.0)

### ISSUE THREAD

**Issue by nc-ruth** [istio/istio#36650]
### Bug Description

In the Istio gateway helm chart, the "auto" image name is not replaced with appropriate image name and tag for istio-proxy. 

```
helm repo add istio https://istio-release.storage.googleapis.com/charts
helm template istio-gateway istio/gateway --version 1.12.1
````

Results in the following deployment manifest:
```
# Source: gateway/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-gateway
  namespace: default
  labels:
    helm.sh/chart: gateway-1.12.1
    app: istio-gateway
    istio: gateway
    app.kubernetes.io/version: "1.12.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istio-gateway
  annotations:
    {}
spec:
  selector:
    matchLabels:
      app: istio-gateway
      istio: gateway
  template:
    metadata:
      annotations:
        inject.istio.io/templates: gateway
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "15020"
        prometheus.io/scrape: "true"
        sidecar.istio.io/inject: "true"
      labels:
        sidecar.istio.io/inject: "true"
        app: istio-gateway
        istio: gateway
    spec:
      serviceAccountName: istio-gateway
      securityContext:
      containers:
        - name: istio-proxy
          image: auto
          securityContext:
            capabilities:
              drop:
              - ALL
              add:
              - NET_BIND_SERVICE
            runAsUser: 0
            runAsGroup: 1337
            runAsNonRoot: false
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: true
          env:
          ports:
          - containerPort: 15090
            protocol: TCP
            name: http-envoy-prom
          resources:
            limits:
              cpu: 2000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 128Mi
```
![image](https://user-images.githubusercontent.com/41048990/147570903-1ff91282-1d34-425e-a81a-8f5b2bddfcb7.png)

Same result when using 1.12.0 as version (`helm template istio-gateway istio/gateway --version 1.12.0`)

### Version

```prose
Istio 1.12.0 and Istio 1.12.1
```
