### ISSUE TITLE
Istio ingress gateway not forwarding TCP keep-alive packets to downstream (client)

### ISSUE THREAD

**Issue by RobertLucian** [istio/istio#36669]
### Bug Description

Got a cluster that uses Istio for its routing functionalities provided in the `VirtualService` services. I'm not using any of the mesh functionalities at all. It's pretty basic. Can show the config at request.

For a given `VirtualService`/`Service`, assume I only have one pod to which the service points to (for the argument's sake) and this pod has a server that processes some stuff when requests land in. The problem I have is that if for some reason there's no transfer for some time between the client and the server, keep-alives will start being sent by server downstream. That's good, but then, the ingress gateway, instead of passing that on to the next hop (to find out if the client is truly alive or not), it just automatically gives back an ACK on that keep-alive, thus holding that request alive indefinitely. And this is particularly bad if the client drops the connection due to some networking issue (bad internet connection for instance).

This is what the chain looks like: _client <-> AWS NLB <-> Istio Ingress <-> Pod (server)_.
I also tried to rule out a misconfiguration with the AWS NLB, so I did: _client <-> AWS NLB <-> Pod (server)_ and this way it worked.

Tried applying the envoy filters (all of them) suggested here https://github.com/istio/istio/issues/28879, and they made a difference in the sense that instead of the ingress gateway reporting DUP ACKs (for the keep-alive header), it would recognize the packets as keep-alives and would immediately respond with ACKs, but didn't see them getting forwarded to the next hop (the AWS NLB).

It would appear that these `EnvoyFilters` hold the key to fixing this. Does anyone have an idea as to what the necessary `EnvoyFilter` needs to look like? This should have worked out-of-the-box, but it doesn't.

I can also attach Wireshark captures here at request.

### Version

```prose
client version: 1.12.1
control plane version: 1.11.4
data plane version: 1.11.4 (2 proxies)

Client Version: v1.20.5
Server Version: v1.21.2-eks-06eac09
```

**Comment by rhyswilliamsza** [comment]
@RobertLucian - did you perhaps find a solution to this?

**Comment by samene** [comment]
@RobertLucian Any luck with resolving this? I may be facing similar issue with a istio multicluster setup on EKS using NLB

- - - - - - - - -                     - - - -                    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|  | client |  - - |  - - - - - ->|  NLB |  - - - - - > |  | eastwest gateway |  - - - - - > |    server   |    |
|   - pod -       |                   - - - -                   |      - - - pod - - - - -                     - - pod - -     |
- - - - - - - - -                                                 - - - - - - - - - - - - -  - - - - - - - - - - - - - - - -  
  cluster 1                                                                                 cluster 2

The client is making a long lived TCP connection to the server. Server is configured to send keepalives every 15 seconds, but they don't seem to be reaching the client, and client disconnects.

**Comment by samene** [comment]
@RobertLucian Any luck with resolving this? I may be facing similar issue with a istio multicluster setup on EKS using NLB

![image](https://user-images.githubusercontent.com/46681492/199655547-b3597d67-cd68-4a07-b5b4-5800c905457a.png)


The client is making a long lived TCP connection to the server. Server is configured to send keepalives every 15 seconds, but they don't seem to be reaching the client, and client disconnects.

**Comment by rhyswilliamsza** [comment]
Hey @samene 

We had some success by implementing TCP Keep-Alives as part of an envoy filter. The below worked for us (originally from https://github.com/istio/istio/issues/28879) 

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: tcp-keep-alives
  namespace: istio-system
spec:
  configPatches:
  - applyTo: LISTENER
    match:
      context: GATEWAY
    patch:
      operation: MERGE
      value:
        socket_options:
        - int_value: 1
          level: 1
          name: 9
          state: STATE_PREBIND
        - int_value: 30
          level: 6
          name: 4
          state: STATE_PREBIND
        - int_value: 30
          level: 6
          name: 5
          state: STATE_PREBIND
```

**Comment by rhyswilliamsza** [comment]
Hey @samene 

We had some success by implementing TCP Keep-Alives as part of an envoy filter. The below worked for us (originally from https://github.com/istio/istio/issues/28879). Make sure you don't scope which context to match, it should be applied to all gateways. Also remember to restart the ingress gateway!

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: tcp-keep-alives
  namespace: istio-system
spec:
  configPatches:
  - applyTo: LISTENER
    match:
      context: GATEWAY
    patch:
      operation: MERGE
      value:
        socket_options:
        - int_value: 1
          level: 1
          name: 9
          state: STATE_PREBIND
        - int_value: 30
          level: 6
          name: 4
          state: STATE_PREBIND
        - int_value: 30
          level: 6
          name: 5
          state: STATE_PREBIND
```

**Comment by dkrzyszczyk** [comment]
@samene @RobertLucian @rhyswilliamsza does any of you figure out the configuration to preserve the long connection between client and server? 

as described above (in the issue itself as well as in the diagram) we also experienced issue that TCP proxy `idle_timeout` cuts off / dropped connection after 1 hour and instead of setting `idle_timeout` to 0s (so disabling it), we tried to configure `socket_options` in `EnvoyFilter` for **keep-alive** but it doesn't reach the client (so of course connection is dropped after 1 hour). that means **keep-alive** doesn't fulfil its own function. additionally, we're trying to avoid situation when we will be forced to disable `idle_timeout` because of the connection leak and of course, we are aware that client should be responsible to disconnect the connection but we don't want to depend on client side. 

setting `EnvoyFilter` with keep-alive:
```apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ingress-gateway-socket-options
  namespace: istio-system
spec:
  configPatches:
  - applyTo: LISTENER
    match:
      context: ANY
    patch:
      operation: MERGE
      value:
        socket_options:
        - description: enable keep-alive
          int_value: 1
          level: 1
          name: 9
          state: STATE_PREBIND
        - description: idle time before first keep-alive probe is sent
          int_value: 45
          level: 6
          name: 4
          state: STATE_PREBIND
        - description: keep-alive interval
          int_value: 9
          level: 6
          name: 5
          state: STATE_PREBIND
        - description: keep-alive probes count
          int_value: 9
          level: 6
          name: 6
          state: STATE_PREBIND
``` 
dropped connction after 1 hour. having `EnvoyFilter` for long `idle_timeout`: 
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: listener-timeout-tcp
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.tcp_proxy
    patch:
      operation: MERGE
      value:
        name: envoy.filters.network.tcp_proxy
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          idle_timeout: 24h
```
is keeping connection but still.. sometimes client needs to established connection for 2-3 days. so having `24h` is not enough and setting to `0s` is not an option. keep-alive should be able to reach the client side.
