### ISSUE TITLE
Second more specific destination rule fails to override first general one

### ISSUE THREAD

**Issue by dan-dragan** [istio/istio#36672]
For learning purposes, I am creating 4 containers, two (curl + web host) meshed and in the mtls namespace, two (curl+web host) non-meshed and in the nomtls namespace. 

Like so:

```

for n in mtls nomtls; do kubectl create namespace $n; done
kubectl label namespace mtls istio-injection=enabled
for n in mtls nomtls; do kubectl create -f curl.yaml -f hostname.yaml -n $n; done
```

With mtls disabled all combinations curl->host work, as expected. 
```
nomtls->nomtls HTTP 200
nomtls->mtls  HTTP 200
mtls->nomtls  HTTP 200
mtls->mtls  HTTP 200

```
Adding a default destination rule  like below will cause curl mtls to host nomtls to fail as an establishment of TLS channel cannot be achieved : 
```
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "default"
  namespace: "mtls"
spec:
  host: "*"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```

Result : 
```
curl.nomtls to hostname.nomtls: 200
curl.nomtls to hostname.mtls: 200
curl.mtls to hostname.nomtls: 503
curl.mtls to hostname.mtls: 200
```
Adding an exception to destination rules to allow meshed mtls clients to connect out of mesh to the nomtls host is supposed to fix that: 
```

apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "to-nomtls"
spec:
  host: 'hostname.nomtls.svc.cluster.local'
  trafficPolicy:
    tls:
      mode: DISABLE
```
but it doesn't : 

```
HTTP/1.1 503 Service Unavailable
content-length: 190
content-type: text/plain
date: Thu, 30 Dec 2021 21:39:46 GMT
server: envoy

curl.mtls to hostname.nomtls.svc.cluster.local/healthz/: 503

```
Thoughts?

**Comment by bianpengyuan** [comment]
Which namespace do you applied `to-nomtls`?

**Comment by dan-dragan** [comment]
Hmm good point. I did not specify a namespace, and not that you point it out, I see that my second policy is missing the namespace. Good catch. Let me try adding and see what goes.

**Comment by dan-dragan** [comment]
That was it. The second policy was missing namespace and presumably getting applied to default., Updated policy works, many thanks!

```
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "to-nomtls" 
  namespace: "mtls"
spec:
  host: 'hostname.nomtls.svc.cluster.local'
  trafficPolicy:
    tls:
      mode: DISABLE
```
