### ISSUE TITLE
holdApplicationUntilProxyStarts isn't being honored 1.10.6

### ISSUE THREAD

**Issue by chris-sanders** [istio/istio#36681]
### Bug Description

I am deploying the Concourse helm chart and the web agent has an init container that has to connect to the postgresql container that's installed for it. Once istio is injected this migration init container is never able to start and the pod never comes up.

I've tried using `holdapplicationUntilProxyStarts` both as a global config and as an annotation on the pod's template. In both cases the istio init container is still being inserted after the migration init container, and I expected it to be inserted before it with this setting enabled.

I started on 1.10.3 and after applying the above settings upgraded to 1.10.6 to check for any issues that have been resolved already. I've also rebooted the entire cluster (full shutdown and power up) with no change.

### Version

```prose
kubectl version --short
Client Version: v1.23.1
Server Version: v1.22.2

client version: 1.12.1
control plane version: 1.10.6
data plane version: 1.10.6 (5 proxies), 1.10.3 (12 proxies)
```

### Additional Information

The failing Concourse pod, you can see the istio init container is after the concourse one, and you can see the annotation applied.

```yaml
k describe -n concourse pod/concourse-web-d48c77568-mz96l
Name:         concourse-web-d48c77568-mz96l
Namespace:    concourse
Priority:     0
Node:         todoroki/192.168.0.8
Start Time:   Fri, 31 Dec 2021 15:56:17 -0600
Labels:       app=concourse-web
              istio.io/rev=default
              pod-template-hash=d48c77568
              release=concourse
              security.istio.io/tlsMode=istio
              service.istio.io/canonical-name=concourse-web
              service.istio.io/canonical-revision=latest
Annotations:  checksum/config: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
              checksum/secrets: 3b4ca2bf36760de99ad336c56f9a0949d3c45a3327046035ef1383a4b857d547
              cni.projectcalico.org/containerID: 92b26d410166581825bd7a4eb44930051ee73ab503baa3d9a556b53d531f71f8
              cni.projectcalico.org/podIP: 10.90.3.76/32
              cni.projectcalico.org/podIPs: 10.90.3.76/32
              kubectl.kubernetes.io/default-container: concourse-web
              kubectl.kubernetes.io/default-logs-container: concourse-web
              kubectl.kubernetes.io/restartedAt: 2021-12-30T17:22:52-06:00
              prometheus.io/path: /stats/prometheus
              prometheus.io/port: 15020
              prometheus.io/scrape: true
              proxy.istio.io/config: { "holdApplicationUntilProxyStarts": true }
              sidecar.istio.io/status:
                {"initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["istio-envoy","istio-data","istio-podinfo","istio-token","istiod-...
Status:       Pending
IP:           10.90.3.76
IPs:
  IP:           10.90.3.76
Controlled By:  ReplicaSet/concourse-web-d48c77568
Init Containers:
  concourse-migration:
    Container ID:  containerd://9158c6c246cf8b30ab8e3716ef34cc9b5010b3dd853b36919f974c35a596babf
    Image:         concourse/concourse:7.6.0
    Image ID:      docker.io/concourse/concourse@sha256:582a9a8ce1de952a6ed329665fde316eaba1f15592ed460d41f533374c10c289
    Port:          <none>
    Host Port:     <none>
    Args:
      migrate
      --migrate-to-latest-version
    State:          Running
      Started:      Fri, 31 Dec 2021 15:56:18 -0600
    Ready:          False
    Restart Count:  0
    Environment:
      CONCOURSE_POSTGRES_HOST:      concourse-postgresql
      CONCOURSE_POSTGRES_USER:      concourse
      CONCOURSE_POSTGRES_PASSWORD:  <set to the key 'postgresql-password' in secret 'concourse-postgresql'>  Optional: false
      CONCOURSE_POSTGRES_DATABASE:  concourse
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-fvz6d (ro)
  istio-init:
    Container ID:
    Image:         docker.io/istio/proxyv2:1.10.6
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Args:
      istio-iptables
      -p
      15001
      -z
      15006
      -u
      1337
      -m
      REDIRECT
      -i
      *
      -x

      -b
      *
      -d
      15090,15021,15020
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:        100m
      memory:     128Mi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-fvz6d (ro)
Containers:
  istio-proxy:
    Container ID:
    Image:         docker.io/istio/proxyv2:1.10.6
    Image ID:
    Port:          15090/TCP
    Host Port:     0/TCP
    Args:
      proxy
      sidecar
      --domain
      $(POD_NAMESPACE).svc.cluster.local
      --serviceCluster
      concourse-web.$(POD_NAMESPACE)
      --proxyLogLevel=warning
      --proxyComponentLogLevel=misc:error
      --log_output_level=default:info
      --concurrency
      2
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:      100m
      memory:   128Mi
    Readiness:  http-get http://:15021/healthz/ready delay=1s timeout=3s period=2s #success=1 #failure=30
    Environment:
      JWT_POLICY:                    third-party-jwt
      PILOT_CERT_PROVIDER:           istiod
      CA_ADDR:                       istiod.istio-system.svc:15012
      POD_NAME:                      concourse-web-d48c77568-mz96l (v1:metadata.name)
      POD_NAMESPACE:                 concourse (v1:metadata.namespace)
      INSTANCE_IP:                    (v1:status.podIP)
      SERVICE_ACCOUNT:                (v1:spec.serviceAccountName)
      HOST_IP:                        (v1:status.hostIP)
      CANONICAL_SERVICE:              (v1:metadata.labels['service.istio.io/canonical-name'])
      CANONICAL_REVISION:             (v1:metadata.labels['service.istio.io/canonical-revision'])
      PROXY_CONFIG:                  {"holdApplicationUntilProxyStarts":true}

      ISTIO_META_POD_PORTS:          [
                                         {"name":"atc","containerPort":8080,"protocol":"TCP"}
                                         ,{"name":"tsa","containerPort":2222,"protocol":"TCP"}
                                         ,{"name":"atc-debug","containerPort":8079,"protocol":"TCP"}
                                     ]
      ISTIO_META_APP_CONTAINERS:     concourse-web
      ISTIO_META_CLUSTER_ID:         Kubernetes
      ISTIO_META_INTERCEPTION_MODE:  REDIRECT
      ISTIO_METAJSON_ANNOTATIONS:    {"checksum/config":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","checksum/secrets":"3b4ca2bf36760de99ad336c56f9a0949d3c45a3327046035ef1383a4b857d547","kubectl.kubernetes.io/restartedAt":"2021-12-30T17:22:52-06:00","proxy.istio.io/config":"{ \"holdApplicationUntilProxyStarts\": true }"}

      ISTIO_META_WORKLOAD_NAME:      concourse-web
      ISTIO_META_OWNER:              kubernetes://apis/apps/v1/namespaces/concourse/deployments/concourse-web
      ISTIO_META_MESH_ID:            cluster.local
      TRUST_DOMAIN:                  cluster.local
      ISTIO_KUBE_APP_PROBERS:        {"/app-health/concourse-web/livez":{"httpGet":{"path":"/api/v1/info","port":8080,"scheme":"HTTP"},"timeoutSeconds":3},"/app-health/concourse-web/readyz":{"httpGet":{"path":"/api/v1/info","port":8080,"scheme":"HTTP"},"timeoutSeconds":1}}
    Mounts:
      /etc/istio/pod from istio-podinfo (rw)
      /etc/istio/proxy from istio-envoy (rw)
      /var/lib/istio/data from istio-data (rw)
      /var/run/secrets/istio from istiod-ca-cert (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-fvz6d (ro)
      /var/run/secrets/tokens from istio-token (rw)
  concourse-web:
    Container ID:
    Image:         concourse/concourse:7.6.0
    Image ID:
    Ports:         8080/TCP, 2222/TCP, 8079/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP
    Args:
      web
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:      100m
      memory:   128Mi
    Liveness:   http-get http://:15020/app-health/concourse-web/livez delay=10s timeout=3s period=15s #success=1 #failure=5
    Readiness:  http-get http://:15020/app-health/concourse-web/readyz delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      CONCOURSE_CLUSTER_NAME:  
      CONCOURSE_ENABLE_GLOBAL_RESOURCES:                  true
      CONCOURSE_SECRET_RETRY_ATTEMPTS:                    5
      CONCOURSE_SECRET_RETRY_INTERVAL:                    1s
      CONCOURSE_LOG_LEVEL:                                info
      CONCOURSE_BIND_PORT:                                8080
      CONCOURSE_BIND_IP:                                  0.0.0.0
      CONCOURSE_ADD_LOCAL_USER:                           <set to the key 'local-users' in secret 'concourse-web'>  Optional: false
      CONCOURSE_EXTERNAL_URL:   
      CONCOURSE_DEBUG_BIND_IP:                            127.0.0.1
      CONCOURSE_DEBUG_BIND_PORT:                          8079
      CONCOURSE_INTERCEPT_IDLE_TIMEOUT:                   0m
      CONCOURSE_GLOBAL_RESOURCE_CHECK_TIMEOUT:            1h
      CONCOURSE_RESOURCE_CHECKING_INTERVAL:               1m
      CONCOURSE_RESOURCE_WITH_WEBHOOK_CHECKING_INTERVAL:  1m
      CONCOURSE_CONTAINER_PLACEMENT_STRATEGY:             volume-locality
      CONCOURSE_BAGGAGECLAIM_RESPONSE_HEADER_TIMEOUT:     1m
      CONCOURSE_BUILD_TRACKER_INTERVAL:                   10s
      CONCOURSE_POSTGRES_HOST:                            concourse-postgresql
      CONCOURSE_POSTGRES_USER:                            concourse
      CONCOURSE_POSTGRES_PASSWORD:                        <set to the key 'postgresql-password' in secret 'concourse-postgresql'>  Optional: false
      CONCOURSE_POSTGRES_DATABASE:                        concourse
      CONCOURSE_KUBERNETES_IN_CLUSTER:                    true
      CONCOURSE_KUBERNETES_NAMESPACE_PREFIX:              concourse-
      CONCOURSE_GC_INTERVAL:                              30s
      CONCOURSE_GC_ONE_OFF_GRACE_PERIOD:                  5m
      CONCOURSE_GC_MISSING_GRACE_PERIOD:                  5m
      CONCOURSE_COOKIE_SECURE:                            true
      CONCOURSE_AUTH_DURATION:                            24h
      CONCOURSE_SESSION_SIGNING_KEY:                      /concourse-keys/session_signing_key
      CONCOURSE_MAIN_TEAM_OIDC_USER: 
      CONCOURSE_OIDC_DISPLAY_NAME:   
      CONCOURSE_OIDC_ISSUER: 
      CONCOURSE_OIDC_CLIENT_ID:                           <set to the key 'oidc-client-id' in secret 'concourse-web'>      Optional: false
      CONCOURSE_OIDC_CLIENT_SECRET:                       <set to the key 'oidc-client-secret' in secret 'concourse-web'>  Optional: false
      CONCOURSE_OIDC_USER_NAME_KEY:                       preferred_username
      POD_IP:                                              (v1:status.podIP)
      CONCOURSE_PEER_ADDRESS:                             $(POD_IP)
      CONCOURSE_TSA_LOG_LEVEL:                            info
      CONCOURSE_TSA_BIND_IP:                              0.0.0.0
      CONCOURSE_TSA_BIND_PORT:                            2222
      CONCOURSE_TSA_DEBUG_BIND_IP:                        127.0.0.1
      CONCOURSE_TSA_DEBUG_BIND_PORT:                      2221
      CONCOURSE_TSA_HOST_KEY:                             /concourse-keys/host_key
      CONCOURSE_TSA_AUTHORIZED_KEYS:                      /concourse-keys/worker_key.pub
      CONCOURSE_TSA_HEARTBEAT_INTERVAL:                   30s
    Mounts:
      /concourse-auth from auth-keys (ro)
      /concourse-keys from concourse-keys (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-fvz6d (ro)
Conditions:
  Type              Status
  Initialized       False
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  istio-envoy:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  istio-data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  istio-podinfo:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      metadata.labels -> labels
      metadata.annotations -> annotations
      limits.cpu -> cpu-limit
      requests.cpu -> cpu-request
  istio-token:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  43200
  istiod-ca-cert:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      istio-ca-root-cert
    Optional:  false
  concourse-keys:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  concourse-web
    Optional:    false
  auth-keys:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  concourse-web
    Optional:    false
  kube-api-access-fvz6d:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  29s   default-scheduler  Successfully assigned concourse/concourse-web-d48c77568-mz96l to todoroki
  Normal  Pulled     28s   kubelet            Container image "concourse/concourse:7.6.0" already present on machine
  Normal  Created    28s   kubelet            Created container concourse-migration
  Normal  Started    28s   kubelet            Started container concourse-migration

```

The istio cm showing the global proxy setting can be seen here.

```yaml
apiVersion: v1
data:
  mesh: |-
    accessLogFile: /dev/stdout
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      holdApplicationUntilProxyStarts: true
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
    enablePrometheusMerge: true
...
```
