### ISSUE TITLE
withoutHeaders can't match the condition: Request does NOT have header X

### ISSUE THREAD

**Issue by penghuazhou** [istio/istio#36698]
**Describe the feature request**
VirtualService match the head that not equal "content-type:application/grpc" or not exists. 

**Describe alternatives you've considered**
I want to match http request not grpc request, but it can not support. It can't match the condition:
Request does NOT have header X.
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
  namespace: istio-ryanzhou
spec:
  hosts:
  - "*"
  gateways:
  - bookinfo-gateway
  http:
  - match:
    - uri:
        exact: /productpage
      withoutHeaders:
        content-type:
          prefix: application/grpc
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: 9080
```
![image](https://user-images.githubusercontent.com/13001038/148059854-a47acffc-98a7-4291-8e09-371b66e20914.png)

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by penghuazhou** [comment]
> Is `refix: application/grpc` the real config or a typo in the issue? It's missing a `p`

use `prefix: application/grpc ` also have the problem.

**Comment by bianpengyuan** [comment]
The semantic of withoutHeaders is that "the header presents AND header does not match xxx", so the browser probably does not send request with content-type and no route matched.

You will need to add the following match rule after prefix match to allow missing content-type if that is desired:

```yaml
    - uri:
         exact: /productpage
      withoutHeaders:
        content-type:
          regex: '*'
```

**Comment by penghuazhou** [comment]
How can I want match       the header presents AND header does not match xxx       or        the header not presents

**Comment by bianpengyuan** [comment]
As said at https://github.com/istio/istio/issues/36698#issuecomment-1006050561:

```yaml
  - match:
    - uri:
        exact: /productpage
      withoutHeaders:
        content-type:
          prefix: application/grpc
     - uri:
         exact: /productpage
      withoutHeaders:
        content-type:
          regex: '*'
```

**Comment by penghuazhou** [comment]
thanks

**Comment by bianpengyuan** [comment]
I cannot think of a way.

**Comment by penghuazhou** [comment]
thanks

**Comment by dlemfh** [comment]
> As said at [#36698 (comment)](https://github.com/istio/istio/issues/36698#issuecomment-1006050561):
> 
> ```yaml
>   - match:
>     - uri:
>         exact: /productpage
>       withoutHeaders:
>         content-type:
>           prefix: application/grpc
>      - uri:
>          exact: /productpage
>       withoutHeaders:
>         content-type:
>           regex: '*'
> ```

This used to be the workaround.

Since v1.22.0 I think https://github.com/istio/istio/pull/49540 (https://github.com/istio/istio/issues/49537) improved the implementation so that using just a single `withoutHeaders`:

```yaml
  - match:
    - uri:
        exact: /productpage
      withoutHeaders:
        content-type:
          prefix: application/grpc
```

gives the same result..!

I've tested locally. Is anyone else willing to also confirm?
