### ISSUE TITLE
istio ingress cors unavailable,nginx ingress available

### ISSUE THREAD

**Issue by jingslunt** [istio/istio#36695]
### Bug Description

- ISTIO-INGRESS

nothing

```
$ curl -X OPTIONS https://proc-some-pre.proc-un.com -IL
HTTP/1.1 405 Method Not Allowed
server: istio-envoy
date: Tue, 04 Jan 2022 08:30:22 GMT
content-type: text/html; charset=utf-8
content-length: 150
x-envoy-upstream-service-time: 19
```

- INGRESS-NGINX

 some Allow-Origin info

```
$ curl -X OPTIONS proc-some-pre.proc-un.com -IL
HTTP/1.1 204 No Content
Date: Tue, 04 Jan 2022 08:26:31 GMT
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, PUT, POST, DELETE, PATCH, OPTIONS
Access-Control-Allow-Headers: DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization
Access-Control-Max-Age: 1728000
Content-Length: 0
```

THIS:
VirtualService cors

```
$ kubectl get vs  fme -n proc-un -o yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  annotations:
    meta.helm.sh/release-name: proc
    meta.helm.sh/release-namespace: proc-un
  creationTimestamp: "2022-01-04T07:22:19Z"
  generation: 2
  labels:
    app.kubernetes.io/managed-by: Helm
  name: fme
  namespace: proc-un
spec:
  gateways:
  - fme
  hosts:
  - proc-some-pre.proc-un.com
  http:
  - corsPolicy:
      allowCredentials: true
      allowHeaders:
      - '*'
      allowMethods:
      - GET
      - POST
      - PATCH
      - PUT
      - DELETE
      - OPTIONS
      allowOrigins:
      - exact: '*'
      maxAge: 24h
    match:
    - uri:
        prefix: /
    route:
    - destination:
        host: fme
        port:
          number: 80
```

ingress cors

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: proc
    meta.helm.sh/release-namespace: proc-hk
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization
    nginx.ingress.kubernetes.io/cors-allow-methods: GET, PUT, POST, DELETE, PATCH,
      OPTIONS
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/enable-cors: "true"
  generation: 1
  labels:
    app: fme
    app.kubernetes.io/instance: proc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fme
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: fme-0.1.0
    status: dev
    tag: green
  name: proc-fme
  namespace: proc-hk
spec:
  ingressClassName: nginx
  rules:
  - host: proc-some-pre.proc-un.com
    http:
      paths:
      - backend:
          service:
            name: fme
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - proc-some-pre.proc-un.com
    secretName: secret-tls

```

### Version

```prose
client version: 1.12.1
control plane version: 1.12.1
data plane version: 1.12.1 (63 proxies)
```
