### ISSUE TITLE
HTTP 1.0 and protocol sniffing

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#36707]
Currently, Istio doesn't enable http/1.0 by default (env var can turn it on). However, we match http/1.0 in the protocol sniffing, only to reject it.

We would be better off just passing it through as TCP

**Comment by hzxuzhonghu** [comment]
sounds good, but the env should also function on the protocol sniffing

**Comment by howardjohn** [comment]
Yeah I agree

**Comment by Sabyasachi2k** [comment]
HI @howardjohn 
We were facing this issue in 1.12.2 and then we upgraded to 1.13.1 and yet we see the same
```
2022-03-03 15:04:37.559 EST[2022-03-03T20:04:37.300Z] "POST /retail/<redacted>/eligibility HTTP/1.0" 426 - low_version - "-" 0 0 0 - "-" "-" "-" "internal-sit2.digital-subscription-qa.com" "-" - - 100.65.136.108:8443 10.158.196.195:47457 internal-sit2.digital-subscription-qa.com -
```

**Comment by Sabyasachi2k** [comment]
Nah,
Plain VS and dr and nothing else. So we have a IBM Datapower calling the service and for some reason it is calling in http 1.0.  They are hitting the DNS "internal-sit2.digital-subscription-qa.com" that is the istio-ingress and then the traffic goes to the pods via VS and DR. I could post the VS and dr if needed but there is nothing special about it. Heck here is the VS and DR
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: digital-subscription-vs-internal
  namespace: sit2
  annotations:
    argocd.argoproj.io/sync-wave: '6'
spec:
  hosts:
  - 'internal-sit2.digital-subscription-qa.com'

  gateways:
    - default/internal-ingress-gateway
  http:

  - name: route-digital-subscription-1
    match:
    - uri:
        prefix: "/retail/<redacted>/"

    route:
    - destination:
        host: "digital-subscription.sit2.svc.cluster.local"
        port:
          number: 21117
        subset: v1
      weight: 100
  
```

here is the DR

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: digital-subscription-dr
  namespace: sit2
  annotations:
    argocd.argoproj.io/sync-wave: '5'
spec:
  host: digital-subscription.sit2.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
 

```

**Comment by howardjohn** [comment]
This fix only applies to mesh. If its gateway there is no protocol sniffing

**Comment by Sabyasachi2k** [comment]
Oh Wait
I have the service defined as and it is defined as http. so that disable this? Now what do I do? 
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: digital-subscription
    version: v1
    part-of: digital-subscription
  name: digital-subscription
  namespace: sit2
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  ports:
  - name: http-digital-subscription
    port: 21117
    targetPort: 21117
  selector:
    app: digital-subscription
  type: ClusterIP
```
