### ISSUE TITLE
istio v1.11.5 ServiceEntry exportTo field ignored

### ISSUE THREAD

**Issue by taitelman** [istio/istio#36712]
It seems the ServiceEntry  (SE) `namespace` overrides the `exportTo` field. that is a behavior change.

when you write a SE the default behavior is expose to all namespaces in the mesh: https://istio.io/latest/docs/reference/config/networking/service-entry/  . you simply don't write `exportTo`.

```
The ‘exportTo’ field allows for control over the visibility of a service declaration to other namespaces in the mesh. By default, a service is exported to all namespaces
```

my SE:

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: hpc
  namespace: A
spec:
  hosts:
  - api.b.com
  ports:
  - name: https-13205
    number: 13205
    protocol: HTTPS
  resolution: DNS
```

then I enable the egress policy to be `REGISTRY_ONLY`
no egress gateway in my mesh.
if I am trying to curl https://api.b.com:13205/aaa from a POD inside namespace A:
I get HTTP 404 - expected.
however if the POD is in different namespace : I get `curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api..`
curl error 35 means that this call was blocked by the egress rule.
 
If I add explicit `exportTo` : 

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: hpc
  namespace: A
spec:
  exportTo:
  - "*"
  hosts:
  - api.b.com
  ports:
  - name: https-13205
    number: 13205
    protocol: HTTPS
  resolution: DNS
```

I still get refuse connection in namespace B.
if I add a duplicate SE to namespace B   

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: hpc
  namespace: B
spec:
  hosts:
  - api.b.com
  ports:
  - name: https-13205
    number: 13205
    protocol: HTTPS
  resolution: DNS
```

then namespace A,B can get to the external host but namespace C can not.

was there any change in SE behavior ?
I also tried exportTo  combinations
```
spec:
  exportTo:
  - A
  - B 
```
all those were ignored by istio. the only scope is in effect is the one inside metadata: namespace field.

```
$ istioctl version
client version: 1.9.0
control plane version: 1.11.5
data plane version: 1.11.5 (166 proxies)

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1-5-g76a04fc", GitCommit:"8b4b09487463415374368af3bbc4ff2e6366477b", GitTreeState:"clean", BuildDate:"2021-06-25T21:59:28Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.13+IKS", GitCommit:"14da388eea4bf735ee4b16dc2306e05b4a4a8d86", GitTreeState:"clean", BuildDate:"2021-11-18T20:34:33Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

```
