### ISSUE TITLE
`forward_client_cert_details` cannot be given the value `SANITIZE` 

### ISSUE THREAD

**Issue by hottea773** [istio/istio#36717]
### Bug Description

The following `EnvoyFilter` doesn't change Envoy's `forward_client_cert_details`:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: forward-client-cert
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager"
          forward_client_cert_details: SANITIZE
          max_request_headers_kb: 86
```
See an inspection of Envoy's config dump:
```bash
$ curl -s 127.0.0.1:15000/config_dump | grep -E "max_request_headers_kb|forward_client_cert_details"
            "max_request_headers_kb": 86,
            "max_request_headers_kb": 86,
            "max_request_headers_kb": 86,
            "max_request_headers_kb": 86,
            "forward_client_cert_details": "APPEND_FORWARD",
            "max_request_headers_kb": 86,
            "forward_client_cert_details": "APPEND_FORWARD",
            "max_request_headers_kb": 86,
            "forward_client_cert_details": "APPEND_FORWARD",
            "max_request_headers_kb": 86,
            "forward_client_cert_details": "APPEND_FORWARD",
            "max_request_headers_kb": 86,
            "forward_client_cert_details": "APPEND_FORWARD",
            "max_request_headers_kb": 86,
            "forward_client_cert_details": "APPEND_FORWARD",
            "max_request_headers_kb": 86,
            "max_request_headers_kb": 86,
```
Other values of `forward_client_cert_details` do though; for example the following EnvoyFilter:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: forward-client-cert-details
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER # http connection manager is a filter in Envoy
    match:
      # context omitted so that this applies to both sidecars and gateways
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
        name: "envoy.filters.network.http_connection_manager"
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          forward_client_cert_details: FORWARD_ONLY
          max_request_headers_kb: 87
```
does:
```bash
$ curl -s 127.0.0.1:15000/config_dump | grep -E "max_request_headers_kb|forward_client_cert_details"
            "forward_client_cert_details": "FORWARD_ONLY",
            "max_request_headers_kb": 87,
            "forward_client_cert_details": "FORWARD_ONLY",
            "max_request_headers_kb": 87,
            "forward_client_cert_details": "FORWARD_ONLY",
            "max_request_headers_kb": 87,
            "forward_client_cert_details": "FORWARD_ONLY",
            "max_request_headers_kb": 87,
            "forward_client_cert_details": "FORWARD_ONLY",
            "max_request_headers_kb": 87,
            "forward_client_cert_details": "FORWARD_ONLY",
            "max_request_headers_kb": 87,
            "forward_client_cert_details": "FORWARD_ONLY",
            "max_request_headers_kb": 87,
            "forward_client_cert_details": "FORWARD_ONLY",
            "max_request_headers_kb": 87,
            "forward_client_cert_details": "FORWARD_ONLY",
            "max_request_headers_kb": 87,
            "forward_client_cert_details": "FORWARD_ONLY",
            "max_request_headers_kb": 87,
            "forward_client_cert_details": "FORWARD_ONLY",
            "max_request_headers_kb": 87,
```
I would expect to be able to set the value `SANITIZE` for the `forward_client_cert_details`.

### Version

```prose
$ helm version --short
v3.6.1+g61d8e8c
$ k0 version --short
Client Version: v1.23.0
Server Version: v1.20.9

istiod & base helm charts at versions `1.12.1`
```
