### ISSUE TITLE
gateway-api: correct route precedence logic

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#36719]
See https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.HTTPRouteRule

We match in ordered list, they have more defined rules.

We should also be merging `mesh` routes, IMO, using the same logic in these cases. We can collapse multiple HTTPRoute down into 1 VS that has a big ordered list (if they have the same hostname).

**Comment by dddddai** [comment]
> We should also be merging mesh routes, IMO, using the same logic in these cases. We can collapse multiple HTTPRoute down into 1 VS that has a big ordered list (if they have the same hostname).

So should we build a VS per host?
 
Let's say there are 2 HTTPRoutes:
```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: route1
spec:
  hostnames:
    - a
    - b
  rules:
    - rule1
```

```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: route2
spec:
  hostnames:
    - a
  rules:
    - rule2
```

After conversion:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
spec:
  hosts:
  - a
  http:
  - rule1
  - rule2 (sorted)
```

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
spec:
  hosts:
  - b
  http:
  - rule2
```
Is this expected?

**Comment by howardjohn** [comment]
Sounds right to me. HTTPRoute and VS do not need to be 1:1. The usage of VS
is just an internal implementation detail

**Comment by dddddai** [comment]
What if multiple HTTPRoutes with the same host have different `parentRefs`? They can't be merged to one VS since the `VS.spec.gateways` are different

**Comment by howardjohn** [comment]
We could do 1 VS per hostname+parent maybe? I think we might already split
by parent - if not entirely then at least mesh is split out iirc

**Comment by dddddai** [comment]
Got it, Thanks!

I have 2 more questions:
1. Should we only merge `mesh` routes? [The gateway-api doc](https://gateway-api.sigs.k8s.io/v1alpha2/api-types/httproute/#merging) says:
> Multiple HTTPRoutes can be attached to a single Gateway resource
2. [The route precedence](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.HTTPRouteRule) is ambiguous if a rule has multiple matches, for example:
```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
spec:
  rules:
  - matches:      # rule1
    - path:
        value: /xxx
    - path:
        value: /foo/bar/baz
    backendRefs:
    - name: svc1
      port: 8080
  - matches:      # rule2
    - path:
        value: /foo/bar
    backendRefs:
    - name: svc2
      port: 8080
```
I have no idea which one wins
