### ISSUE TITLE
Headless service listener behavior confusion

### ISSUE THREAD

**Issue by yanickxia** [istio/istio#36725]
### Bug Description

as https://istio.io/latest/docs/ops/configuration/traffic-management/traffic-routing/#headless-services say.
if service is headless, listener will build POD_IP:PORT for these pod.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: tunnel-internal-svc
spec:
  clusterIP: None
  clusterIPs:
  - None
  ports:
  - name: default
    port: 9996
    protocol: TCP
    targetPort: 9996
  selector:
    app: tunnel
  sessionAffinity: None
  type: ClusterIP
status:
```
it's works.  build some listener like

```
10.20.2.147_9996
10.20.2.148_9996
```

but i modify name to http

```yaml
apiVersion: v1
kind: Service
metadata:
  name: tunnel-internal-svc
spec:
  clusterIP: None
  clusterIPs:
  - None
  ports:
  - name: http
    port: 9996
    protocol: TCP
    targetPort: 9996
  selector:
    app: tunnel
  sessionAffinity: None
  type: ClusterIP
status:
```

it's not work. listener like

```
0.0.0.0_9996
```

it's behavior make us confusion …… maybe add more doc for this condition

### Version

```prose
$ istioctl version
client version: 1.9.5
control plane version: 1.9.5
data plane version: none
```
