### ISSUE TITLE
circuit_breakers.thresholds cannot be set on cluster using EnvoyFilter

### ISSUE THREAD

**Issue by StefanCenusa** [istio/istio#36731]
### Bug Description

I am unable to set [circuit_breakers.threshold](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/circuit_breaker.proto#envoy-v3-api-msg-config-cluster-v3-circuitbreakers-thresholds) on a specific cluster using **EnvoyFilter**. The problem seems to be similar to this [one](https://github.com/istio/istio/pull/29216).

Istio pilot [only processes **MERGE**](https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go#L46) operations on CLUSTER resource and `proto.Merge` appends to the already existing default thresholds array. 

Thus, an EnvoyFilter that tries to update the thresholds array in order to implement server side circuit-breaking will not work.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: custom-circuit-breaking
  namespace: test
spec:
  workloadSelector:
    labels:
      app: foo
  configPatches:
    - applyTo: CLUSTER
      match:
        cluster:
          name: "inbound|80||"
      patch:
        operation: MERGE
        value:
          circuit_breakers:
            thresholds:
              - max_connections: 100
                max_pending_requests: 1
                max_requests: 4294967295
                max_retries: 4294967295
                track_remaining: true

```
Envoy's docs mentions that 

> If multiple Thresholds are defined with the same RoutingPriority, the first one in the list is used. If no Thresholds is defined for a given RoutingPriority, the default values are used.

 so the array item appended by the aforementioned EnvoyFilter won't be taken into account.

This issue is really concerning since there are **no other ways of configuring server-side circuit breaking** with istio for workloads/services that receive traffic from **clients without istio-proxy.**

### Version

```prose
istio 1.12.1
```

**Comment by bianpengyuan** [comment]
I thought circuit breaker at destination rule should apply to both inbound and outbound, so this envoyfilter should not be needed. Is that not the case?

**Comment by StefanCenusa** [comment]
@bianpengyuan Thanks for your quick reply. 

Indeed, now I notice that DestinationRule also applies some of the config on the `inbound|` cluster as well. Is this a known and intended behaviour? Because the docs make me believe it only refers to outbound connections
> DestinationRule defines policies that apply to traffic intended for a service after routing has occurred.

What I am trying to achieve is a server-side circuit breaking - max N http1.1 connections without in-flight requests. No matter where the traffic originates (within the mesh or from clients that don't have istio-proxy injected).

**Comment by bianpengyuan** [comment]
Yeah that is the intended behavior and it behaves like that from the very early days. The doc probably should hint this better.

**Comment by StefanCenusa** [comment]
Ok, noted. Thanks!

**Comment by attila-tokes** [comment]
We encountered kind of the same issue at @RWS. We would need to override the `circuit_breakers.thresholds` values for some Envoy Inbound clusters.

> Yeah that is the intended behavior and it behaves like that from the very early days. The doc probably should hint this better.

@bianpengyuan, unfortunately this behavior does not really makes sense in some use cases. If there is a heavily used **Server** application, called by many **Client** services, the [circuit breaking](https://istio.io/latest/docs/tasks/traffic-management/circuit-breaking/) functionality from Istio is not particularly useful.

For example, if we have:
- a **Server** micro-service deployed with 4 instances
- about 50 x **Client** micro-services, each with 2 instances

and we to try to apply a `DestinationRule` like:
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
spec:
  host: ...
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 10
      http:
        http1MaxPendingRequests: 10
        http2MaxRequests: 10
```

What we are trying to achieve, is to limit the max number of concurrent connections/requests from each **Client** service to `10`. 

Now, because the connection limit of `10` is applied both on Outbound and Inbound, we end up with a bottleneck on the **Server** side. Namely, the **Server** will be limited to maximum of `40` *(4 instances x 10)* concurrent inbound connections/requests.

A similar issue is described in #28666, with the difference that there the Outbound rules are the ones causing the unintended behaviour.

As a workaround, I was trying to override `circuit_breakers.thresholds` in the Inbound cluster, basically to reset it to the defaults values. But, this does not seems to be possible with the current implementation.
