### ISSUE TITLE
Traces being sampled when sample rate set to 0

### ISSUE THREAD

**Issue by Stono** [istio/istio#36750]
### Bug Description

We have the following config

```
data:
  mesh: |-
    defaultConfig:
      tracing:
        max_path_tag_length: 1024
        sampling: 0
        zipkin:
          address: zipkin.istio-system.svc.cluster.local:9411
```

However we're still seeing some spans being sampled.

Doing a config dump shows:
```
 "tracing": {
             "client_sampling": {
              "value": 100
             },
             "random_sampling": {
              "value": 1
             },
             "overall_sampling": {
              "value": 100
             },
```

So it appears the config isn't working

@howardjohn pointed me at: https://github.com/istio/istio/blame/8b5e6505c28feedea342b0b912741fe9c77bd904/pilot/pkg/networking/core/v1alpha3/tracing.go#L447 which explains it, that 0 effectively can't be used.

For context; we don't want istio to decide what we sample - that's what we do with our opentracing libraries at various points in our infrastructure.  All we want istio to do is report the spans if `x-b3-sampled: 1`. 

This is how we've had istio configured for years and it did used to work, because we only want traces for requests that originate through nginx (subsequently correlated to a client request), and we record 100% of those.  We don't care for internal tracing eg, some kafka consumer calling some other service.  And because that's recording just 1% anyway, it confuses our users when they're stumbling across spans for some, but not all of their apps requests (remember, they're used to it being 100% of client requests).

A somewhat cruddy work around is to set it to 0.1, which reduces the amount of noise we store, but obviously doesn't stop it.

Please can we regain the ability to have istio just report spans based on the tracing headers, but never attempt to create traces or spans (so effectively a sample rate of 0) - eg the ability to set `random_sampling` to 0.

Thanks

### Version

```prose
1.12
```

**Comment by howardjohn** [comment]
cc @douglas-reid . Any easy fix is to use a protobuf wrapper to distinguish null from `0`, but I don't know if we can do that in a backwards compatible way?

**Comment by douglas-reid** [comment]
@Stono @howardjohn that code was lifted from the existing code, so that bit should not have changed. Is the issue that it is defaulting to the pilot value of 1.0?  Can we (as a workaround) set the pilot traceSampling to 0 at install ?

**Comment by Stono** [comment]
> Is the issue that it is defaulting to the pilot value of 1.0

Yeah, so we've had 0 set for years, it's quite possible it's always been defaulting to 1 and i've only recently noticed (because i've been investigating jaeger load on ES).   Either way it's somewhat miss leading

> Can we (as a workaround) set the pilot traceSampling to 0 at install

How would I do that?

**Comment by douglas-reid** [comment]
> How would I do that?

What happens if we apply:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    pilot:
      traceSampling: 0.0 # override from 1.0
```

Does that have the intended effect?

**Comment by Stono** [comment]
Will give it a go and see.... please hold

**Comment by Stono** [comment]
<img width="492" alt="Screenshot 2022-01-07 at 18 29 40" src="https://user-images.githubusercontent.com/1486729/148590059-505f9a41-8107-4824-a710-e85fa8b8fbba.png">

That seems to remove the `PILOT_TRACE_SAMPLING` env variable (which was previously 1), rather than setting it to 0? Also how does this relate to `defaultConfig.tracing.sampling` ?

**Comment by howardjohn** [comment]
`{{- if .Values.pilot.traceSampling }}` strikes again....

But you can set that env var directly. the `defaultConfig.tracing.sampling` takes precedence over env var when its non-zero

**Comment by Stono** [comment]
So to be clear I need to set `defaultConfig.tracing.sampling` = 0, and PILOT_TRACE_SAMPLING = 0 ?

**Comment by howardjohn** [comment]
Yep

**Comment by Stono** [comment]
OK got something working:

```
 "tracing": {
             "client_sampling": {
              "value": 100
             },
             "random_sampling": {},
             "overall_sampling": {
              "value": 100
             },
```

To do this you have to have:

```
spec:
  values:
    pilot:
      traceSampling: 0.0
...
   mesh: |-
    defaultConfig:
      tracing:
        sampling: 0
...
spec:
  components:
    pilot:
      k8s:
        env:
        - name: PILOT_TRACE_SAMPLING
          value: '0.0'
```
