### ISSUE TITLE
Sidecar to application upstream connection stuck and never closed

### ISSUE THREAD

**Issue by shonecyx** [istio/istio#36765]
### Bug Description

In our case, we are using ingressgateway and have sidecar injection to the backend application:
```
client --> ingress gateway(envoy) --> [ (destination envoy) -> application ]
```
And there are some connections between ` [ (destination envoy) -> application ]` stuck and never closed which caused the server resource leak(because there is no idle timeout in server side), even if the client to ingressgateway connection is closed.

Connection status in sidecar/app, application is serving on 9000:
```
netstat  -alnop | grep '127.0.0.1:9000'
tcp        0      0 127.0.0.1:41186         127.0.0.1:9000          ESTABLISHED 34/envoy             off (0.00/0/0)
tcp        0      0 127.0.0.1:33962         127.0.0.1:9000          ESTABLISHED 34/envoy             off (0.00/0/0)
tcp        0 1117451 127.0.0.1:53164         127.0.0.1:9000          ESTABLISHED 34/envoy             on (0.02/0/0)
tcp        0      0 127.0.0.1:42316         127.0.0.1:9000          ESTABLISHED 34/envoy             off (0.00/0/0)
tcp        0      0 127.0.0.1:43270         127.0.0.1:9000          ESTABLISHED 34/envoy             off (0.00/0/0)
tcp        0      0 127.0.0.1:43976         127.0.0.1:9000          ESTABLISHED 34/envoy             off (0.00/0/0)
tcp        0      0 127.0.0.1:41022         127.0.0.1:9000          ESTABLISHED 34/envoy             off (0.00/0/0)
tcp        0      0 127.0.0.1:39676         127.0.0.1:9000          ESTABLISHED 34/envoy             off (0.00/0/0)
tcp        0      0 127.0.0.1:41024         127.0.0.1:9000          ESTABLISHED 34/envoy             off (0.00/0/0)
tcp        0      0 127.0.0.1:59994         127.0.0.1:9000          ESTABLISHED 34/envoy             off (0.00/0/0)
tcp        0      0 127.0.0.1:42876         127.0.0.1:9000          TIME_WAIT   -                    timewait (24.32/0/0)
tcp        0      0 127.0.0.1:43712         127.0.0.1:9000          ESTABLISHED 34/envoy             off (0.00/0/0)
tcp        0      0 127.0.0.1:41016         127.0.0.1:9000          ESTABLISHED 34/envoy             off (0.00/0/0)
tcp        0      0 127.0.0.1:44152         127.0.0.1:9000          ESTABLISHED 34/envoy             off (0.00/0/0)
tcp        0      0 127.0.0.1:34176         127.0.0.1:9000          ESTABLISHED 34/envoy             off (0.00/0/0)
tcp        0      0 127.0.0.1:53366         127.0.0.1:9000          ESTABLISHED 34/envoy             off (0.00/0/0)
```

Based on server side metrics, there are two connections on port `43270` and `59994` stuck and leaked for days:
```
istio-proxy@app:/$ lsof -P -i tcp  | grep 43270
envoy      34 istio-proxy  351u  IPv4 249821297      0t0  TCP localhost:43270->localhost:9000 (ESTABLISHED)

istio-proxy@app:/$ stat /proc/34/fd/351
  File: /proc/34/fd/351 -> socket:[249821297]
  Size: 64        	Blocks: 0          IO Block: 1024   symbolic link
Device: 100069h/1048681d	Inode: 289206562   Links: 1
Access: (0700/lrwx------)  Uid: ( 1337/istio-proxy)   Gid: ( 1337/istio-proxy)
Access: 2022-01-10 02:04:35.356631619 +0000
Modify: 2022-01-07 08:09:44.744859669 +0000
Change: 2022-01-07 08:09:44.744859669 +0000
 Birth: -

istio-proxy@app:/$ lsof -P -i tcp  | grep 59994
envoy      34 istio-proxy  388u  IPv4 250257324      0t0  TCP localhost:59994->localhost:9000 (ESTABLISHED)
istio-proxy@app:/$ stat /proc/34/fd/388
  File: /proc/34/fd/388 -> socket:[250257324]
  Size: 64        	Blocks: 0          IO Block: 1024   symbolic link
Device: 100069h/1048681d	Inode: 289206571   Links: 1
Access: (0700/lrwx------)  Uid: ( 1337/istio-proxy)   Gid: ( 1337/istio-proxy)
Access: 2022-01-10 02:04:35.356631619 +0000
Modify: 2022-01-07 08:09:44.744859669 +0000
Change: 2022-01-07 08:09:44.744859669 +0000
 Birth: -
```

tcpdump shows there is tcp keepalive packet in this connection: 
```
tcpdump -i lo  -nnvvv  | grep 127.0.0.1.43270
tcpdump: listening on lo, link-type EN10MB (Ethernet), capture size 262144 bytes
    127.0.0.1.9000 > 127.0.0.1.43270: Flags [.], cksum 0xfe28 (incorrect -> 0x7415), seq 3708089939, ack 520685276, win 12288, options [nop,nop,TS val 3019902876 ecr 3019872156], length 0
    127.0.0.1.43270 > 127.0.0.1.9000: Flags [.], cksum 0xfe28 (incorrect -> 0x2ea0), seq 1, ack 1, win 12278, options [nop,nop,TS val 3019902876 ecr 2582050611], length 0
    127.0.0.1.9000 > 127.0.0.1.43270: Flags [.], cksum 0xfe28 (incorrect -> 0x8414), seq 0, ack 1, win 12288, options [nop,nop,TS val 3019933596 ecr 3019902876], length 0
    127.0.0.1.43270 > 127.0.0.1.9000: Flags [.], cksum 0xfe28 (incorrect -> 0xb69f), seq 1, ack 1, win 12278, options [nop,nop,TS val 3019933596 ecr 2582050611], length 0
```

We have a global DestinationRule configured for this case:
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: default-traffic-policy
  namespaces: istio-system
spec:
  exportTo:
  - '*'
  host: '*'
  trafficPolicy:
    connectionPool:
      http:
        h2UpgradePolicy: DEFAULT
        http1MaxPendingRequests: 20000
        http2MaxRequests: 20000
        idleTimeout: 60s
        maxRequestsPerConnection: 0
        maxRetries: 20000
      tcp:
        connectTimeout: 1s
        maxConnections: 20000
        tcpKeepalive:
          interval: 10s
          probes: 10
          time: 700s
```

Also tried to create the EnvoyFilter to application namespace:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: cluster-idle-timeout-tcp
  namespace: user-ns
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: ANY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.tcp_proxy
    patch:
      operation: MERGE
      value:
        name: envoy.filters.network.tcp_proxy
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          idle_timeout: 15s
```

None of them is working, there is no way to close those two connections between sidecar to application.

**Expected behavior**
In the application pod, the sidecar to application `[ (destination envoy) -> application ]` connection should be closed with above DestinationRule or EnvoyFilter but seems the http idle connection timeout is not working.

### Version

```prose
istioctl version -i istio-staging
client version: 1.9.0
control plane version: 1.10-dev-3e1cdc98208a4824619469fc09d984315f9aece8
data plane version: 1.10-dev
kubectl version: 1.18.8
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by hzxuzhonghu** [comment]
I recall this is a similar issue reported before, the reason is that the destination rule currently is applied only to outbound cluster, not the inbound.

**Comment by shonecyx** [comment]
@hzxuzhonghu  Thanks for comments. If the DestinationRule is not working, why the EnvoyFilter is also not working? Suppose it will apply to sidecar both INBOUND and OUTBOUND with context ANY? The problem here seems that we can not configure the sidecar upstream connection idle timeout which will cause connection stuck and stacking.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: cluster-idle-timeout-tcp
  namespace: user-ns
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: ANY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.tcp_proxy
    patch:
      operation: MERGE
      value:
        name: envoy.filters.network.tcp_proxy
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          idle_timeout: 15s
```

**Comment by hzxuzhonghu** [comment]
What is the application protocol?

**Comment by shonecyx** [comment]
> What is the application protocol?

It's HTTP, here is the VS and GW spec:
```   
kind: Gateway
  name: my-gateway
spec:
  selector:
    istio: ingressgateway-system
  servers:
  - hosts:
    - www.example.com
    port:
      name: https
      number: 443
      protocol: HTTPS

kind: VirtualService
metadata:
  creationTimestamp: null
  name: my-vs
spec:
  gateways:
  - my-gateway
  hosts:
  - www.example.com
  http:
  - match:
    - port: 443
      uri:
        prefix: /
    route:
    - destination:
        host: example-svc
        port:
          number: 443
```

BTW I also tried below EnvoyFilter and still no luck, there is still no idle timeout in the sidecar upstream connection.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: cluster-idle-timeout-http
  namespace:my-ns
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      context: ANY
      proxy:
        proxyVersion: ^1\.10.*
    patch:
      operation: MERGE
      value:
        typed_extension_protocol_options:
          envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
            '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
            commonHttpProtocolOptions:
              idleTimeout: 30s
            explicit_http_config:
              http_protocol_options: {}
```
