### ISSUE TITLE
 Kubernetes ingress not able to reference a secret that is another different namespace

### ISSUE THREAD

**Issue by Mangaal** [istio/istio#36770]
### Bug Description

I was using ingress which is deployed in some other namespace and I was trying to access the secret which is in the istio-system namespace but it was not possible but with ingress gateway and virtual service is works.
Here is my ingress yaml.
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: sample-ingress
  namespace: test
spec:
  tls:
  - hosts:
      - example.mangaal.com
    secretName: ca-issuer-example-com # secret which is in istio-system namespace
  rules:
  - host: example.mangaal.com
    http:
      paths:
      - path: /hello
        backend:
          serviceName: golang-api-service-web
          servicePort: 8080
```

### Version

```prose
istioctl version
 client version :1.9.4
 control plane version :1.9.4
kubectl version --short
 client version :1.20.0
 control plane version :1.20.0
```

### Additional Information

Error I got when i try to curl was "**ssl_error_syscal**l"
