### ISSUE TITLE
istio-ingress missing #accept: text/html,application/xhtml+xml,application/xml

### ISSUE THREAD

**Issue by jingslunt** [istio/istio#36785]
### Bug Description

```
# curl https://aa.com
{"timestamp":"2022-01-11T04:11:02.510+0000","path":"/","status":404,"error":"Not Found","message":null}
# curl   'https://aa.com'   -H 'accept: text/html,application/xhtml+xml,application/xml;'
<html><body><h1>Whitelabel Error Page</h1><p>This application has no configured error view, so you are seeing this as a fallback.</p><div id='created'>Tue Jan 11 12:11:12 CST 2022</div><div>There was an unexpected error (type=Not Found, status=404).</div></body></html>
```

### Version

```prose
# istioctl version
client version: 1.12.1
control plane version: 1.12.1
data plane version: 1.12.1 (3 proxies)
```

**Comment by howardjohn** [comment]
Can you describe more about what you expect to happen and what is actually happening and what your config is?

**Comment by jingslunt** [comment]
> Can you describe more about what you expect to happen and what is actually happening and what your config is?

### Example:
>   GET web.aa.com -->   POST api.aa.com

- GET 
```
:authority: web.aa.com
:method: GET
:path: /seller/login
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: gzip, deflate, br
accept-language: zh-CN,zh;q=0.9
cache-control: max-age=0
if-modified-since: Thu, 18 Nov 2021 06:28:15 GMT
if-none-match: W/"6195f27f-ac5"
sec-ch-ua: "(Not(A:Brand";v="8", "Chromium";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-site: none
sec-fetch-user: ?1
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4820.0 Safari/537.36
```




- login,accept values loss
```
:authority: api.aa.com
:method: POST
:path: /seller/login?geetest_challenge=&geetest_validate=&geetest_seccode=&geetest_usercode=is@163.com
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: zh-CN
content-length: 80
content-type: application/json;charset=UTF-8
cookie: language=zh-CN; JSESSIONID=40303A3C3550CD88411F14A29093F8C7
origin: https://web.aa.com
referer: https://web.aa.com/
sec-ch-ua: "(Not(A:Brand";v="8", "Chromium";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-site
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4820.0 Safari/537.36
```

**Comment by jingslunt** [comment]
@howardjohn istio ingress need default accept values

**Comment by howardjohn** [comment]
Where is Istio involved in this?

**Comment by jingslunt** [comment]
@howardjohn  I use istio gateway, and try add request-header, found not work, something wrong?


```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: request-header-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value:
       name: envoy.filters.http.lua
       typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
          inlineCode: |
            function envoy_on_request(request_handle)
              request_handle:headers():add("manualheader","custom");
              request_handle:headers():replace("accept","text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9");
              if not response_handle:headers():get("accept") then
                response_handle:headers():add("accept","text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9");
              end
            end
```
