### ISSUE TITLE
TestClusterLocal flakes

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#36791]
Recently i met several failure of TestClusterLocal 

https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/36788/integ-pilot-multicluster-tests_istio/1480827322700402688

**Comment by hzxuzhonghu** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/36908/integ-pilot-multicluster_istio/1484342318780649472

**Comment by howardjohn** [comment]
So the test applies this config:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: mysvc-dr
  namespace: echo
spec:
  host: b.echo.svc.cluster.local
  subsets:
  - name: primary
    labels:
      topology.istio.io/cluster: primary
  - name: remote
    labels:
      topology.istio.io/cluster: remote
  - name: cross-network-primary
    labels:
      topology.istio.io/cluster: cross-network-primary
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: mysvc-vs
  namespace: echo
spec:
  hosts:
  - b.echo.svc.cluster.local
  http:
  - name: "primary-local"
    match:
    - sourceLabels:
        topology.istio.io/cluster: primary
    route:
    - destination:
        host: b.echo.svc.cluster.local
        subset: primary
  - name: "remote-local"
    match:
    - sourceLabels:
        topology.istio.io/cluster: remote
    route:
    - destination:
        host: b.echo.svc.cluster.local
        subset: remote
  - name: "cross-network-primary-local"
    match:
    - sourceLabels:
        topology.istio.io/cluster: cross-network-primary
    route:
    - destination:
        host: b.echo.svc.cluster.local
        subset: cross-network-primary
```

Then later removes it and sends requests. The failures show the `remote-local` route still present. Istiod configz shows it does not know the VS, and you can see Istiod triggers a push. 


XDS logs shows push of v129 then v130. Only the a pod (client in this case, the only one that matters) has v129 and has the `remote-local` route. Others are already on v130. `a` pod starts the push after v129 is started but before v130 has. RDS push is 0/64 cache so unlikely a cache issue. For some reason, once it completes the full XDS push cycle, it never pushes again - so v130 is missing.

Other pods, such as `b`, also start before v130, and were able to push again after completion

**Comment by howardjohn** [comment]
The only things I can think of that would explain this are:
* https://github.com/istio/istio/blob/32d4c998cf1be78472fb9159030f5c934caf618d/pilot/pkg/xds/ads.go#L690 is broken
* PushQueue is broken

Neither seem likely...

**Comment by howardjohn** [comment]
Uni test by the same name failing... https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37116/unit-tests_istio/1489348847569211392

**Comment by hzxuzhonghu** [comment]
The integration test does not have workloadentry

**Comment by howardjohn** [comment]
It may be entirely unrelated then and just has the same name

**Comment by howardjohn** [comment]
Super common still. https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37367/integ-pilot-multicluster_istio/1493959780035727360 for example.

@nmittler I don't want to lose coverage here but worried about the impact this is having. We should look into this

**Comment by nmittler** [comment]
I believe this started when we switched the default LB policy. We can temporarily switch back to RR while we investigate.

**Comment by nmittler** [comment]
@ramaraochavali let's try RR and see how it goes

**Comment by howardjohn** [comment]
OK I figured it out. Its actually two bugs.

1. If we have a subset cluster, but not DR, we will continue to build the EDS response (https://github.com/istio/istio/blob/e3904269b7bd95207fdccd2be6f14276a3ad470a/pilot/pkg/xds/eds.go#L480). This means we can get "impossible" configs like DR with subset "empty" with matching nothing,but it has endpoints. This doesn't really occur in *most* cases but is still an issue
2. Race condition on push logic. Explained below

Say we add a config then later remove it.

* v0 - add config
* v1 - remove config

Consider a proxy with the following order of events:

* Config added
* Push v0 fully
* Config removed
* EDS request comes in
  * We fetch the NEWEST push version: https://github.com/istio/istio/blob/e3904269b7bd95207fdccd2be6f14276a3ad470a/pilot/pkg/xds/ads.go#L213. This v1, not v0
  * Sidecar state is stale, so we update it https://github.com/istio/istio/blob/e3904269b7bd95207fdccd2be6f14276a3ad470a/pilot/pkg/xds/ads.go#L242. This means SidecarScope=v1, PrevSidecarScope=v0. all good so bar
* Now the push for v1 is triggered
  * Again we update the state (https://github.com/istio/istio/blob/e3904269b7bd95207fdccd2be6f14276a3ad470a/pilot/pkg/xds/ads.go#L688). Now SidecarScope=v1, and PrevSidecarScope=v1
  * Later we check ProxyNeedsPush. Neither sidecarscope (v1) or prev sidecarscope (also v1) depend on the DR, so we return false, skipping the push.

End results:
* EDS is at v1, with bizarre EDS info (due to bug 1)
* CDS is stuck at v0

**Comment by hzxuzhonghu** [comment]
Catched up with the second  bug, we are too replying on the state transition. 

But I am not sure what is 1 bug actually

**Comment by howardjohn** [comment]
Bug 1:
* apply some config like
```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: mysvc-dr
spec:
  host: echo.default.svc.cluster.local
  subsets:
  - name: my-subset
    labels:
      topology.istio.io/cluster: remote
```

* We get cluster for " my-subset" with 1 endpoint (only remote cluster)
* Delete DR
* EDS push occurs. For various reasons (the bug above, a push request, etc), we still have the " my-subset" envoy cluster. We lookup DR and find nothing, so we continue anyway
* We push EDS for "subset" cluster with 3 endpoints (1 for each cluster).  This state should be impossible since we never defined a subset `my-subset` that allowd those endpoints

Instead, if we are a subset cluster and we do not find the subset config, we should not send an update to envoy. simple fix
