### ISSUE TITLE
Adding a toleration to manifests/charts/istio-control/istio-discovery

### ISSUE THREAD

**Issue by rmalenko** [istio/istio#36795]
Adding a toleration to manifests/charts/istio-control/istio-discovery to allows the pods to schedule onto nodes with matching taints.

`manifests/charts/istio-control/istio-discovery/values.yaml `
```yaml
after...
  nodeSelector: {}

  # Apply to pods, and allow (but do not require) the pods to schedule
  # onto nodes with matching taints.
  tolerations:
    - key: "k8s-app"
      operator: "Equal"
      value: "istio"
      effect: "NoSchedule"
before...
  podAnnotations: {}

```
`manifests/charts/istio-control/istio-discovery/templates/deployment.yaml `
```yaml
after...
{{ toYaml .Values.pilot.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.pilot.tolerations }}
      tolerations:
{{ toYaml .Values.pilot.tolerations | indent 8 }}
{{- end }}
before...
      serviceAccountName: istiod{{- if not (eq .Values.revision "") }}-{{ .Values.revision }}{{- end }}

```
