### ISSUE TITLE
Duplicated cipher suites configured in Envoy

### ISSUE THREAD

**Issue by shonecyx** [istio/istio#36805]
### Bug Description

In our case we need to create the Gateway with specified cipher suites:
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
  name: my-gw
  namespace: my-ns
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - www.example.com
    port:
      name: http-80
      number: 80
      protocol: HTTP
  - hosts:
    - www.example.com
    port:
      name: my-svc
      number: 443
      protocol: HTTPS
    tls:
      cipherSuites:
      - AES128-GCM-SHA256
      - ECDHE-ECDSA-AES128-GCM-SHA256
      - ECDHE-RSA-AES128-GCM-SHA256
      - AES256-GCM-SHA384
      - ECDHE-RSA-AES128-GCM-SHA256
      - ECDHE-ECDSA-AES256-GCM-SHA384
      - ECDHE-RSA-AES256-GCM-SHA384
      minProtocolVersion: TLSV1_2
      mode: SIMPLE
```

And here is what we got in the Envoy config dump in IngressGateway
```
         "transport_socket": {
          "name": "envoy.transport_sockets.tls",
          "typed_config": {
           "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext",
           "common_tls_context": {
            "tls_params": {
             "tls_minimum_protocol_version": "TLSv1_2",
             "cipher_suites": [
              "AES128-GCM-SHA256",
              "ECDHE-ECDSA-AES128-GCM-SHA256",
              "ECDHE-RSA-AES128-GCM-SHA256",
              "AES256-GCM-SHA384",
              "ECDHE-RSA-AES128-GCM-SHA256",
              "ECDHE-ECDSA-AES256-GCM-SHA384",
              "ECDHE-RSA-AES256-GCM-SHA384"
             ]
            },
            "alpn_protocols": [
             "h2",
             "http/1.1"
            ]
```

Noticed there is duplicated cipher suited configured in the gateway and pushed to the Gateway Envoy `ECDHE-RSA-AES128-GCM-SHA256`

This PR https://github.com/istio/istio/pull/34109 added the validation to filter the invalid ciphers, the duplicated cipher suites should also be removed.

### Version

```prose
istio version: 1.10
kubectl version: 1.18.8
```
