### ISSUE TITLE
VirtualService not used by my k8s service

### ISSUE THREAD

**Issue by politrons** [istio/istio#36839]
Hi I'm very newby in Istio/K8s, and I'm trying to make a service that I have `test-service` to use a new `VirtualService `that I've created.

Here the steps that I did

` kubectl config set-context --current --namespace my-namespace
`
I create my VirtualService

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-service
  namespace: my-namespace
spec:
  hosts:
  - test-service
  http:
  - fault:
      delay:
        fixedDelay: 60s
        percentage:
          value: 100
    route:
    - destination:
        host: test-service
        port:
          number: 9100
```

Then I apply into K8s

`kubectl apply -f test-service.yaml`
But now when I invoke the test-service using gRPC I can reach the service, but the fault with the delay is not happening.

I dont know in which log I can see of this test-service is using the VirtualService that I created or not
