### ISSUE TITLE
virtualservice doesn't work with service which port is no equal to targetPort

### ISSUE THREAD

**Issue by iPapanya** [istio/istio#36845]
### Bug Description

I want to redirect trafic from pods within namespace "default" to services a.back-testing, b.back-testing and c.back-testing to service a.default.
All services are the same - just web server that returns hostname on GET /name

manifest:
**back-testing.yaml**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a
  namespace: back-testing
  labels:
    app: a
    version: a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a
  template:
    metadata:
      labels:
        app: a
        version: a
    spec:
      containers:
      - name: web
        image: cr.yandex/crp77elslen50fvl734b/app/simple-server:0.0.2
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        readinessProbe:
          httpGet:
            path: /
            port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: a
  namespace: back-testing
  labels:
    app: a
    version: a
spec:
  selector:
    app: a
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: http-envoy-prom
      protocol: TCP
      port: 18090
      targetPort: http-envoy-prom
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: b
  namespace: back-testing
  labels:
    app: b
    version: b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: b
  template:
    metadata:
      labels:
        app: b
        version: b
    spec:
      containers:
      - name: web
        image: cr.yandex/crp77elslen50fvl734b/app/simple-server:0.1.0
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        readinessProbe:
          httpGet:
            path: /
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: b
  namespace: back-testing
  labels:
    app: b
    version: b
spec:
  selector:
    app: b
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: http-envoy-prom
      protocol: TCP
      port: 18090
      targetPort: http-envoy-prom
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c
  namespace: back-testing
  labels:
    app: c
    version: c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: c
  template:
    metadata:
      labels:
        app: c
        version: c
    spec:
      containers:
      - name: web
        image: cr.yandex/crp77elslen50fvl734b/app/simple-server:0.1.0
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        readinessProbe:
          httpGet:
            path: /
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: c
  namespace: back-testing
  labels:
    app: c
    version: c
spec:
  selector:
    app: c
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
    - name: http-envoy-prom
      protocol: TCP
      port: 18090
      targetPort: http-envoy-prom
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: a
  namespace: back-testing
spec:
  hosts:
  - a.back-testing.svc.cluster.local
  http:
  - name: back-testing-to-default
    match:
    - sourceNamespace: default
    route:
    - destination:
        host: a.default.svc.cluster.local
        port:
          number: 80
        subset: a
  - name: default
    route:
    - destination:
        host: a.back-testing.svc.cluster.local
        port:
          number: 80
        subset: a
  exportTo:
    - "."
    - default
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: b
  namespace: back-testing
spec:
  hosts:
  - b.back-testing.svc.cluster.local
  http:
  - name: back-testing-to-default
    match:
    - sourceNamespace: default
    route:
    - destination:
        host: a.default.svc.cluster.local
        port:
          number: 80
        subset: a
  - name: default
    route:
    - destination:
        host: b.back-testing.svc.cluster.local
        port:
          number: 8080
        subset: b
  exportTo:
    - "."
    - default
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: c
  namespace: back-testing
spec:
  hosts:
  - c.back-testing.svc.cluster.local
  http:
  - name: back-testing-to-default
    match:
    - sourceNamespace: default
    route:
    - destination:
        host: a.default.svc.cluster.local
        port:
          number: 80
        subset: a
  - name: default
    route:
    - destination:
        host: c.back-testing.svc.cluster.local
        port:
          number: 8080
        subset: c
  exportTo:
    - "."
    - default
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: a
  namespace: back-testing
  labels:
    monitoring: prometheus
    release: prometheus
spec:
  jobLabel: a
  endpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
  namespaceSelector:
    matchNames:
      - back-testing
  selector:
    matchLabels:
      app: a
      version: a
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: b
  namespace: back-testing
  labels:
    monitoring: prometheus
    release: prometheus
spec:
  jobLabel: b
  endpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
  namespaceSelector:
    matchNames:
      - back-testing
  selector:
    matchLabels:
      app: b
      version: b
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: c
  namespace: back-testing
  labels:
    monitoring: prometheus
    release: prometheus
spec:
  jobLabel: c
  endpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
  namespaceSelector:
    matchNames:
      - back-testing
  selector:
    matchLabels:
      app: c
      version: c
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: deny-default
  namespace: back-testing
spec:
  mtls:
    mode: PERMISSIVE
```

**default.yaml**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a
  namespace: default
  labels:
    app: a
    version: a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a
  template:
    metadata:
      labels:
        app: a
        version: a
    spec:
      containers:
      - name: web
        image: cr.yandex/crp77elslen50fvl734b/app/simple-server:0.0.2
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        readinessProbe:
          httpGet:
            path: /
            port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: a
  namespace: default
  labels:
    app: a
    version: a
spec:
  selector:
    app: a
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: http-envoy-prom
      protocol: TCP
      port: 18090
      targetPort: http-envoy-prom
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: a
  namespace: default
spec:
  hosts:
  - a.default.svc.cluster.local
  http:
  - name: default
    route:
    - destination:
        host: a.default.svc.cluster.local
        port:
          number: 80
        subset: a
  exportTo:
    - "."
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: a
  namespace: default
  labels:
    monitoring: prometheus
    release: prometheus
spec:
  jobLabel: a
  endpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: a
      version: a
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: deny-default
  namespace: default
spec:
  mtls:
    mode: PERMISSIVE
```

**dest-rules.yaml**
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: a
  namespace: istio-system
spec:
  host: a.back-testing.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      tcp:
        maxConnections: 100
  subsets:
  - name: a
    labels:
      version: a
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: b
  namespace: istio-system
spec:
  host: b.back-testing.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      tcp:
        maxConnections: 100
  subsets:
  - name: b
    labels:
      version: b
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: c
  namespace: istio-system
spec:
  host: c.back-testing.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      tcp:
        maxConnections: 100
  subsets:
  - name: c
    labels:
      version: c
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: a
  namespace: istio-system
spec:
  host: a.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      tcp:
        maxConnections: 100
  subsets:
  - name: a
    labels:
      version: a
```

I expect that from pod of service a in namespace default returns the same output for commands:
curl a/name
curl a.back-testing/name
curl b.back-testing/name
curl c.back-testing:8080/name

But for curl b.back-testing/name it returns the name of pod of service b in namespace back-testing.

In access log of envoy I see that request goes to PassthroughCluster and in Kiali I see that request goes without mtls.
When I add to istio configuration
 outboundTrafficPolicy:
    mode: REGISTRY_ONLY

I get 502 on curl b.back-testing/name from each pod with envoy (except for pod of service b in namespace back-testing)

It seems like istio does not register the service b.back-testing.

### Version

```prose
client version: 1.12.1
control plane version: 1.12.1
data plane version: 1.12.1 (4 proxies)
Client Version: v1.21.2
Server Version: v1.21.5
```
