### ISSUE TITLE
values.global.imagePullSecrets doesn't work in IstioOperatorSpec components

### ISSUE THREAD

**Issue by Yejing0609** [istio/istio#36852]
e.g. I want to let the ingressGateways pod use the private repo's image. we need to setup the imagePullSecrets in this case. I checked some docs and questions, there seems we have a values.global.imagePullSecrets parameter. however, after I set it as below, it still can't have the imagePullSecrets in deployment. How can I set the imagePullSecrets for components?
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  hub: private.io/istio-testing
  tag: latest
  values:
     global:
       imagePullSecrets:
       - artifactory-prod
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
  components:
    ingressGateways:
    - name: istio-ingressgateway-internal
       namespace: istio-system  
      enabled: true
```

### Version

```prose
v1.11
```

### Affected product area

- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
