### ISSUE TITLE
Istio 1.7 mTLS origination with external IIS service. How to disable HTTP/2? 

### ISSUE THREAD

**Issue by achana** [istio/istio#36850]
### Bug Description

context:  I have a requirement to establish an mTLS connection from the Istio egress gateway to an external IIS service. When I do this, connections always fail with a 503 error.  Further investigation found out that egress sends the request in HTTP/2 but IIS is expecting HTTP1.1 for MTLS connection. Windows IIS falls back to HTTP/1.1 and continues the transaction. This may involve negotiating HTTP/1.1 during the handshake, or sending an error code to the client instructing it to retry over an HTTP/1.1 connection.” https://docs.microsoft.com/en-us/iis/get-started/whats-new-in-iis-10/http2-on-iis 

I added the following EnvoyFilter config but it's not working as expected to force Instio egress GW to originate HTTP1.1 request.  Is this config working in Istio 1.7 version?

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: disable-alpn-h2
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: egressgateway
  configPatches:
    - applyTo: FILTER_CHAIN
      match:
        listener:
          filterChain:
            sni: "*.mygateway.com"
      patch:
        operation: MERGE
        value:
          transportSocket:
            name: envoy.transport_sockets.tls
            typedConfig:
              '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              commonTlsContext:
                alpnProtocols:
                  - "http/1.1"
                tlsCertificateSdsSecretConfigs:
                  - name: kubernetes://wildcard-cert
                    sdsConfig:
                      ads: {}
                      resourceApiVersion: V3

```
 

### Version

```prose
➜  ~ istioctl version
client version: 1.7.8
telemetry version: 1.7.8
telemetry version: 1.7.8
telemetry version: 1.7.8
istiod version: 1.7.8
➜  ~ kubectl version --short
Client Version: v1.22.3
Server Version: v1.19.14-gke.1900
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by howardjohn** [comment]
Upstream protocol should be dictated by ServiceEntry. What protocol did you declare it as?

**Comment by achana** [comment]
It's declared as HTTPS in ServiceEntry

**Comment by achana** [comment]
envoy is originating the TLS. Please find my full configuration as below.

we have Istio 1.7 in all our environments, hence we need to add this using the same version. Can you kindly let us know whether the EnvoyFilter I posted is correct? 

```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: pod-to-gw-onprem-https-gcplb-test
  namespace: egress
  annotations:
    helm-chart: istio-policy/egress
    helm-chart-version: 0.1.0
  labels:
    integration: onprem-https
    endpoint: gcplb-test
spec:
  exportTo: ["*"]
  host: cx-egressgateway.egress.svc.cluster.local
  subsets:
    - name: onprem-https-gcplb-test-service
      trafficPolicy:
        loadBalancer:
          simple: ROUND_ROBIN
        portLevelSettings:
          - port:
              number: 443
            tls:
              mode: ISTIO_MUTUAL
              sni: gcplb-test.mygateway.com
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: gw-to-ext-for-onprem-https-gcplb-test
  namespace: egress
  annotations:
    helm-chart: istio-policy/egress
    helm-chart-version: 0.1.0
  labels:
    integration: onprem-https
    endpoint: gcplb-test
spec:
  exportTo: ["."]
  host: gcplb-test.mygateway.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 443
        loadBalancer:
          simple: ROUND_ROBIN
        tls:
          caCertificates: /etc/certs/csp-np/ca/fullchain.pem
          mode: MUTUAL
          clientCertificate: /etc/certs/onprem/tls/tls.crt
          privateKey: /etc/certs/onprem/tls/tls.key
          sni: gcplb-test.mygateway.com
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: onprem-https
  namespace: egress
  annotations:
    helm-chart: istio-policy/egress
    helm-chart-version: 0.1.0
  labels:
    integration: onprem-https
spec:
  selector:
    istio: cx-egressgateway
  servers:
    - hosts:
        - gcplb-test.mygateway.com
      port:
        name: https-onprem-https-gcplb-test
        protocol: HTTPS
        number: 443
      tls:
        mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: onprem-https-gcplb-test
  namespace: egress
  annotations:
    helm-chart: istio-policy/egress
    helm-chart-version: 0.1.0
  labels:
    integration: onprem-https
    endpoint: gcplb-test
spec:
  hosts:
    - "gcplb-test.mygateway.com"
  resolution: DNS
  ports:
    - name: onprem-https-gcplb-test
      number: 443
      protocol: HTTPS
    - name: onprem-https-gcplb-test-internal
      number: 80
      protocol: HTTP
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: onprem-https-gcplb-test
  namespace: egress
  annotations:
    helm-chart: istio-policy/egress
    helm-chart-version: 0.1.0
  labels:
    integration: onprem-https
    endpoint: gcplb-test
spec:
  hosts:
    - gcplb-test.mygateway.com
  gateways:
    - egress/onprem-https
    - mesh
  http:
    - match:
        - gateways:
            - egress/onprem-https
          port: 443
      route:
        - destination:
            host: gcplb-test.mygateway.com
            port:
              number: 443
          weight: 100
    - match:
        - gateways:
            - mesh
          port: 80
      route:
        - destination:
            host: cx-egressgateway.egress.svc.cluster.local
            subset: onprem-https-gcplb-test-service
            port:
              number: 443
          weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: disable-alpn-h2
  namespace: egress
spec:
  workloadSelector:
    labels:
      istio: cx-egressgateway
  configPatches:
    - applyTo: FILTER_CHAIN
      match:
        listener:
          filterChain:
            sni: "gcplb-test.mygateway.com"
      patch:
        operation: MERGE
        value:
          transportSocket:
            name: envoy.transport_sockets.tls
            typedConfig:
              '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              commonTlsContext:
                alpnProtocols:
                  - "http/1.1"
                tlsCertificateSdsSecretConfigs:
                  - name: kubernetes://wildcard-cert
                    sdsConfig:
                      ads: {}
                      resourceApiVersion: V3
```
