### ISSUE TITLE
X-Envoy-Internal when using short hostname

### ISSUE THREAD

**Issue by jgournet** [istio/istio#36859]
### Bug Description

```
curl -v https://myservice.com.au/actuator/health              <= x-envoy-internal is null: that's expected as the call goes out to the internet before coming back in via ingress gateway
curl -v https://myservice.internal.com.au/actuator/health    <= x-envoy-internal is true: that's the normal behavior
curl -v http://myservice.mynamespace/actuator/health         <= x-envoy-internal is null: this seems wrong
curl -v http://myservice/actuator/health                     <= x-envoy-internal is null: this seems wrong (from a pod from the same namespace as "myservice") 
```
the first 2 curl calls behave as expected.
However, the 3rd and 4th calls are using the short form of the hostname, and we're getting x-envoy-internal as null.
That seems like a bug (unless it's a feature)

Context:
The context is to get this authorizationpolicy to work:
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: myservice
  namespace: mynamespace
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        paths:
        - /actuator/*
    when:
    - key: request.headers[X-Envoy-Internal]
      values:
      - "true"
  selector:
    matchLabels:
      app.kubernetes.io/instance: myservice.mynamespace
      app.kubernetes.io/name: myservice
```
=> because of this bug, this authorizationpolicy does not work (I've re-written it using a match on the source namespace, FYI)

### Version

```prose
istio version: 1.10.4

kubectl version --short
Client Version: v1.22.2
Server Version: v1.21.2-eks-0389ca3
```
