### ISSUE TITLE
Can not route no domain suffix host while there are a serviceentry

### ISSUE THREAD

**Issue by Patrick0308** [istio/istio#36864]
### Bug Description

A serviceentry define a no domain suffix host:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: lb-test
spec:
  addresses:
  - 1.1.1.1
  hosts:
  - "lb-test"
  location: MESH_INTERNAL
  ports:
  - number: 8080
    name: grpc-8080
    protocol: grpc
  resolution: STATIC
```
And try to define a virtual service add route configuration:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: lb-test
spec:
  hosts:
  - "lb-test"
  http:
  - match:
    - port: 8080
    route:
    - destination:
        host: lb-test.core.svc.cluster.local
        port:
          number: 8080
```
It is not work. Because if virtual service's host is shortname, istio will interpret the short name. 
The docs mention this, see the hosts field definition in 
https://istio.io/latest/docs/reference/config/networking/virtual-service/#VirtualService

> Note for Kubernetes users: When short names are used (e.g. “reviews” instead of “reviews.default.svc.cluster.local”), Istio will interpret the short name based on the namespace of the rule, not the service. A rule in the “default” namespace containing a host “reviews” will be interpreted as “reviews.default.svc.cluster.local”, irrespective of the actual namespace associated with the reviews service. To avoid potential misconfigurations, it is recommended to always use fully qualified domain names over short names.

However, when I define a service entry has no suffix domain, virtual service should work.

### Version

```prose
$ .istioctl/bin/istioctl version
client version: 1.11.5
istiod version: 1.11-dev
istiod version: 1.11-dev
pilot version: 1.10-dev
data plane version: 1.11.5 (366 proxies)
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
