### ISSUE TITLE
Ingressgateway TLSmode=SIMPLE doesn't support both token auth and client cert auth since 1.10.0

### ISSUE THREAD

**Issue by sonnyhcl** [istio/istio#36863]
### Bug Description

We are facing unexpected behavior for `tlsmode=SIMPLE` and `tlsmode=MUTUAL` when we upgrade from 1.9.9 to 1.10.0.
Below is our `gateway.yaml`. We are using `tlsmode=SIMPLE` since our gateway will accept both token auth and client cert auth. Also we set `caCertificates` to validate client cert if has.
But when we upgrade from 1.9.9 to 1.10.0, we found our client cert is not honored by gateway from `curl-1.10.0-simple.log`, which is different from `curl-1.9.9-simple.log`.

By dumping ingressgateway proxy-config from ingressgateway using below command, I found 1.9.9 with `tlsmode=simple` has `require_client_certificate=false` and have set `validation_context` from `caCertficates` we set, while 1.10.0 with `tlsmode=simple` only has `require_client_certificate=false` and don't have any `validation_context` config. 
```bash
podname=$(k get pods -l istio=ingressgateway -n istio-system -o jsonpath='{.items[0].metadata.name}')
k exec -ti $podname -n istio-system -- curl http://localhost:15000/config_dump > $podname.proxyconfig.json
```

I think it's related to this commit #31391, which is first released in istio 1.10.0. 
After going through the conversations in #31391 and #31984, I think this should be a **regression**. `tlsmode=SIMPLE` should also have ability to optional check client cert and should set `validation_context` if user specify `caCertificates`, which should be equal to `VerifyClientCertIfGiven` in go TLS handshake options.

```yaml
# gateway.yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingressgateway
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        minProtocolVersion: TLSV1_2
        serverCertificate: /etc/ingressgateway-https-certs/tls.crt
        privateKey: /etc/ingressgateway-https-certs/tls.key
        caCertificates: /etc/ca-certs/ca.pem
```
```log
#curl-1.10.0-simple.log
$ curl --cert-type p12 --cert client-cert.pfx https://xxx -vvv
*   Trying xx...
* TCP_NODELAY set
* Connected to xxx port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Unknown (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Client hello (1):
* TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
```
```
#curl-1.9.9-simple.log
$ curl --cert-type p12 --cert client-cert.pfx https://xxx -vvv
*   Trying xxxxx...
* TCP_NODELAY set
* Connected to xxx port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Unknown (8):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Client hello (1):
* TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, CERT verify (15):
* TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
```

### Version

```prose
istio version: We are upgrading istio from 1.9.9 to 1.10.0

$ k version --short
Client Version: v1.22.2
Server Version: v1.20.9
```

**Comment by howardjohn** [comment]
cc @ramaraochavali 

Not quite sure the best behavior here. SIMPLE is underspecified currently, so there is no clearly defined API behavior expectation.



So if we were to revert This would give behavior;
* simple without ca - 1 way tls
* simple with CA - optional mtls
* mutual - required mtls

One concern is that a user may "accidentally* set caCertificates - because it's derived from a single credentialName secret reference; the person controlling the Gateway may not control the Secret format even. 

One question I have is did the old behavior request a client cert? ie if CA cert is set and access from browser you will get a pop-up asking for cert?

**Comment by ramaraochavali** [comment]
The reason why we did that change is https://github.com/istio/istio/pull/31391#pullrequestreview-610973748 and https://github.com/istio/istio/issues/31984#issuecomment-934535108

I am also of the same understanding  that Envoy does not request a cert unless we set `require_client_cert` to true. Quick read of envoy code confirms the same https://github.com/envoyproxy/envoy/blob/bb95af848c939cfe5b5ee33c5b1770558077e64e/source/extensions/transport_sockets/tls/cert_validator/default_validator.cc#L426

Are you sure client cert is requested and validated for SIMPLE?

**Comment by howardjohn** [comment]
So it looks like go does not provide "do not request but verify if sent" (https://github.com/istio/istio/issues/31984#issuecomment-934535108) mode, but that doesn't necessarily mean it's unreasonable? It is valid, afaik, for tls clients to send the client cert even if it's not requested?

**Comment by ramaraochavali** [comment]
> It is valid, afaik, for tls clients to send the client cert even if it's not requested?

May be. I am not sure about this part. So should we add validatonContext if caCert is present for SIMPLE? If that is reasonable - we can add that part back

**Comment by howardjohn** [comment]
my main concern is if it's implicitly set (in Secret, rather than explicit
in Gateway). Especially since changing the behavior back is a breaking
change (and not reverting recent behavioral really - 1.10 was almost a year
ago).

Perhaps another mode...

**Comment by sonnyhcl** [comment]
> Not quite sure the best behavior here. SIMPLE is underspecified currently, so there is no clearly defined API behavior expectation.
So if we were to revert This would give behavior;
simple without ca - 1 way tls
simple with CA - optional mtls
mutual - required mtls

cc @howardjohn  From a user's perspective, Istio needs a way to support optional mTLS as both token auth and client cert auth, just similiar with mesh PERMISSIVE mode. Otherwise we have to setup two different ingressgateways.

> I am also of the same understanding that Envoy does not request a cert unless we set require_client_cert to true. Quick read of envoy code confirms the same https://github.com/envoyproxy/envoy/blob/bb95af848c939cfe5b5ee33c5b1770558077e64e/source/extensions/transport_sockets/tls/cert_validator/default_validator.cc#L426

You can double check the curl log in bug report. Istio 1.9.9+tlsmode=simple did ask for client cert. I'm not expert on Envoy, maybe you can double check whether set `caCertificate` will ask for client cert.

**Comment by sonnyhcl** [comment]
> One question I have is did the old behavior request a client cert? ie if CA cert is set and access from browser you will get a pop-up asking for cert?

This is the screenshot that open link directly in browser and it will popup asking for cert.
![image](https://user-images.githubusercontent.com/10840522/149883694-14034bb0-d4ab-4cc7-9e78-47453b0ac247.png)

**Comment by garyzjq** [comment]
For optional TLS negotiation contract, here are some searching result to answer above questions

> It is valid, afaik, for tls clients to send the client cert even if it's not requested?

Regarding to TLS RFC (https://www.ietf.org/rfc/rfc5246.txt, section 7.4.4 and 7.4.6 for optional/required mTLS), if server side doesn't send "Certificate Request" message to client, client won't send "Client Certificate" to Server. ( see "7.4.6 Client Certificate")
The expected negotiation steps are :
1. Server side first send "Certificate Request" message to client side with the CA list 
2. client side then send "Client Certificate" message back with the client cert, server side decide whether to fail if no client cert provided (require client cert) or continue (client cert is optional)

Thus **for optional mtls, server side need to send CA list to client.**


> The reason why we did that change is [#31391 (review)](https://github.com/istio/istio/pull/31391#pullrequestreview-610973748) and [#31984 (comment)](https://github.com/istio/istio/issues/31984#issuecomment-934535108)
> 
> I am also of the same understanding that Envoy does not request a cert unless we set `require_client_cert` to true. Quick read of envoy code confirms the same https://github.com/envoyproxy/envoy/blob/bb95af848c939cfe5b5ee33c5b1770558077e64e/source/extensions/transport_sockets/tls/cert_validator/default_validator.cc#L426
> 
> Are you sure client cert is requested and validated for SIMPLE?

For how envoy handle optional mTLS logic, one correctness is
1. **SSL_CTX_set_client_CA_list** maps to the Server send "Certificate Request" message to client
	"SSL_CTX_set_client_CA_list() sets the list of CAs sent to the client when requesting a client certificate for ctx." https://linux.die.net/man/3/ssl_ctx_set_client_ca_list
	 
2. **SSL_CTX_set_verify** is to set local flag in server SSL lib whether require client cert when receiving response from client
	"SSL_CTX_set_verify() sets the verification flags for ctx to be mode and specifies the verify_callback function to be used." (https://linux.die.net/man/3/ssl_ctx_set_verify
	
Thus **in Envoy code, if CA list is specified in server config, it will be always send to client no matter 'require_client_cert' is specified or not.** 
https://github.com/envoyproxy/envoy/blob/bb95af848c939cfe5b5ee33c5b1770558077e64e/source/extensions/transport_sockets/tls/cert_validator/default_validator.cc#L424


---------
If we can agree on the correct SSL contract, back to Istio app model, I somehow agree with @howardjohn this is implicit, we can consider to expose require_client_cert flag in Istio model (to align with Envoy model, actually also similar with Jetty model https://www.programcreek.com/java-api-examples/?class=org.eclipse.jetty.util.ssl.SslContextFactory&method=setTrustStorePath) or even define a new type besides SIMPLE and MTLS.

**Comment by howardjohn** [comment]
> I am also of the same understanding that Envoy does not request a cert unless we set require_client_cert to true. Quick read of envoy code confirms the same https://github.com/envoyproxy/envoy/blob/bb95af848c939cfe5b5ee33c5b1770558077e64e/source/extensions/transport_sockets/tls/cert_validator/default_validator.cc#L426

Not always: https://github.com/envoyproxy/envoy/issues/17224.... although maybe in all our usage

**Comment by Colere-Sys** [comment]
any updates on this?

**Comment by zhangyd2015** [comment]
As a simple workaround, we can always use following `EnvoyFilter` to add `combined_validation_context` or `validation_context` to SIMPLE mode:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: add-validation-context-to-simple-mode
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: FILTER_CHAIN
    match:
      context: GATEWAY
      listener:
        portNumber: 8443
    patch:
      operation: MERGE
      value:
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
            common_tls_context:
              combined_validation_context:
                default_validation_context: {}
                validation_context_sds_secret_config:
                  name: kubernetes://ssl-certificate-cacert
                  sds_config:
                    ads: {}
                    resource_api_version: V3

```
