### ISSUE TITLE
Unable to use port within Sidecar resource when ISTIO_META_DNS_AUTO_ALLOCATE is enabled

### ISSUE THREAD

**Issue by linsun** [istio/istio#36883]
### Bug Description

Upon testing in my local laptop (kind + k8s), I have a simple SE:

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: ratings-se
  namespace: myapp
spec:
  hosts:
    - ratings.myapp.io
  location: MESH_INTERNAL
  ports:
    - name: http
      number: 80
      protocol: http
      targetPort: 8080
  resolution: STATIC
  workloadSelector:
    labels:
      app: ratings
```

No Sidecar resource: when accessing to ratings (from sleep pod running in a different ns) using `ratings.myapp.io`, it works fine.

With simple Sidecar resource (no port):  When accessing to ratings (from sleep pod running in a different ns) using `ratings.myapp.io`, it works fine.

```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: default
spec:
  egress:
  - hosts:
    - "myapp/*"
    - "./*"
    - "istio-system/*"
    - "kube-system/*"
```

With simple Sidecar resource with port:  When accessing to ratings (from sleep pod running in a different ns) using `ratings.myapp.io`, it doesn't work.
```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: default
spec:
  egress:
  - hosts:
    - "myapp/*"
    port:
      # neither 80 or 8080 works
      number: 80
      protocol: HTTP
      name: egresshttp
  - hosts:
    - "./*"
    - "istio-system/*"
    - "kube-system/*"
```

@howardjohn kindly reminded me to enable access log and DNS debug log:

- No info is logged in access log from sleep pod when it doesn't work.
- when DNS debug log is enabled via pod annotation `sidecar.istio.io/agentLogLevel: "dns:debug"` for the sleep pod , the following show up in the log:

```
2022-01-18T21:47:34.199294Z	debug	dns	response for hostname "ratings.myapp.io." not found in dns proxy, querying upstream
```
along with other hostnames:  ratings.myapp.io.cluster.local. + ratings.myapp.io.attlocal.net. + ratings.myapp.io.svc.cluster.local.  all returned not found in dns proxy.  I am using ATT as my home network provider

Also noticed that the routes for sleep deployment isn't correct:

```
 istioctl pc routes deploy/sleep -n web-api-ns
NAME                              DOMAINS                                       MATCH                  VIRTUAL SERVICE
80                                ratings.myapp.io               /*
```

The working one (without Sidecar resource with port) had the resolving IP also on the Domains:

```
istioctl pc routes deploy/sleep -n web-api-ns
NAME                              DOMAINS                                            MATCH                  VIRTUAL SERVICE
80                                ratings.myapp.io, 240.240.0.1       /*
```

It appears the client sidecar pod needs to look up `ratings.myapp.io` to its IP address and that look up is somehow blocked.

### Version

```prose
1.12.1
```
