### ISSUE TITLE
When service entry's host has tailing period, smart dns can not resolve it

### ISSUE THREAD

**Issue by Patrick0308** [istio/istio#36885]
### Bug Description

Enable the smart dns.
```
meshConfig:
   defaultConfig: 
     proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
```
Service entry is :
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: lb-chaojiang-test
  namespace: skopos
spec:
  addresses:
  - 1.1.1.1
  hosts:
  - "lb-test."
  location: MESH_INTERNAL
  ports:
  - number: 8080
    name: grpc-8080
    protocol: grpc
  resolution: STATIC
```
Resolve `lb-test.` in pod.
```
# nslookup lb-test.
Server:		x.x.x.x
Address:	x.x.x.x#53

** server can't find lb-test: NXDOMAIN
```
Looks like we need add a dns record about a no tailing `.` host.

### Version

```prose
$ .istioctl/bin/istioctl version
client version: 1.11.5
istiod version: 1.11-dev
istiod version: 1.11-dev
pilot version: 1.10-dev
data plane version: 1.11.5 (366 proxies)
```
