### ISSUE TITLE
A particular pattern of SE was broken between version upgrade from 1.10.5 to 1.11.2

### ISSUE THREAD

**Issue by sudeeptoroy** [istio/istio#36913]
### Bug Description

While upgrading between Istio version 1.10.5 to 1.11.2 we observed a specific case where a particular service entry config did not work as intended.

SE:
The SE is configured with multiple hosts. The resolved ip addresses of the hosts where configured as IP address in the addresses block of SE.

Before upgrade:
The application was able to reach a external host.
After upgrade:
The application failed to connect to the external host. 

We removed the address block from the SE  as they were not needed and the application was able to connect the external host.

I am raising this issue to learn if there were any changes done around SE which can affect this scenario. Release noted do not mention of any changes around this. 

### Version

```prose
1.10.5 to 1.11.2
```

**Comment by sudeeptoroy** [comment]
As discussed during the n/w meet, here is an example. 
Note the resolution is set to NONE

```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-svc-example
spec:
  hosts:
  - host1.domain.com
  - host2.domain.com
  - <many enties>
  addresses:
  - IP_of_hos1
  - IP_of_host2
  - < many enties>
  ports:
  - number: port1
    name: port1
    protocol: TCP
  - number: port2
    name: port2
    protocol: TCP
  - number: port3
    name: port3
    protocol: TCP
 - <many entries>
  location: MESH_EXTERNAL
  resolution: NONE
```

**Comment by bianpengyuan** [comment]
Are you by any chance using CNI?

**Comment by sudeeptoroy** [comment]
yes

**Comment by bianpengyuan** [comment]
Ok, and I suppose you have DNS proxying enabled? (i.e. you set `ISTIO_META_DNS_CAPTURE` env var). At 1.11, CNI starts to support DNS proxy, which will start to return the ip addresses you listed in the service entry when the app tries to resolve host, and probably the address is not really reachable.

**Comment by sudeeptoroy** [comment]
Hi @bianpengyuan , thank you for your reply and explanation.
In our setup we have *not* enabled DNS proxying yet, so there must be something else affecting the behaviour.

**Comment by bianpengyuan** [comment]
I am not sure what's the difference. the following SE works for me on both 1.11 and 1.10
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-svc-example
spec:
  hosts:
  - www.google.com
  addresses:
  - 1.2.3.4
  ports:
  - number: 443
    name: port1
    protocol: TCP
  location: MESH_EXTERNAL
  resolution: NONE
```

I guess we will need access log and config dump from your 1.10 and 1.11 proxy to tell what's the difference.

**Comment by sudeeptoroy** [comment]
Hi Pengyuan,

Thank you for spending time on this.
I guess an external TCP service and many ips and ports in the configuration
could be the difference.
I am unwell now, However I will work on a similar setup and share the
configuration with you little later.

**Comment by sudeeptoroy** [comment]
Hi @bianpengyuan , 

I spent sometime on this today. what i see is i have "ISTIO_META_DNS_CAPTURE" set to "false" and the behaviour is exactly same as what you mentioned. 
The DNS is returning addresses one by one from the "se" entry. 
For example if configured this

```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-svc-example
spec:
  hosts:
  - external.host.example.com
  addresses:
  - 1.2.3.4
  ports:
  - number: 443
    name: port1
    protocol: TCP
  location: MESH_EXTERNAL
  resolution: NONE
```
I see the curl request is targeted to 1.2.3.4

Is there any log you would like me to share with you?
