### ISSUE TITLE
Efficient routing of QUIC packets to the correct worker is not supported

### ISSUE THREAD

**Issue by marcbachmann** [istio/istio#36945]
### Bug Description

I'm running istio with `PILOT_ENABLE_QUIC_LISTENERS` enabled to use http3.
Quic itself is working properly, but during the start of the ingress, envoy logs a warning because bpf couldn't be used. I suspect it could be the cause for some elevated load I'm having on the system.

```
2022-01-22T03:07:15.347858Z	warning	envoy quic	Efficient routing of QUIC packets to the correct worker is not supported or not implemented by Envoy on this platform. QUIC performance may be degraded.
```

According to the envoy team, the pod needs BPF capabilities, which aren't present at the moment in the istio ingress deployment, so that's definitely something that needs to get updated: https://github.com/envoyproxy/envoy/issues/15845

Therefore I've tried to patch the deployment with the following profile to add the BPF capability, but sadly that still didn't work.

Istio Profile:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  hub: docker.io/istio
  tag: 1.12.2
  components:
    pilot:
      enabled: true
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        overlays:
          - kind: Deployment
            name: istio-ingressgateway
            patches:
              # Enable BPF for QUIC
              - path: spec.template.spec.containers.[name:istio-proxy].securityContext.capabilities.add
                value:
                  - BPF

  values:
    pilot:
      env:
        PILOT_ENABLE_QUIC_LISTENERS: "true"
```

Do you have any idea what could be the issue here? Does anybody have the setup working without the warning?

Somehow that condition fails and it goes into the else case: https://github.com/alyssawilk/envoy/blob/e246aec1d8e84b7c99402c7b15f34e04088347b1/source/common/quic/active_quic_listener.cc#L285-L338

### Version

```prose
$ istioctl version
client version: 1.12.1
control plane version: 1.12.2
data plane version: 1.12.2 (4 proxies)

$ kubectl version --short
Client Version: v1.22.5
Server Version: v1.22.5+k3s1

$ uname -a
Linux kubernetes-lhcf 5.10.0-7-amd64 #1 SMP Debian 5.10.40-1 (2021-05-28) x86_64 GNU/Linux
```

**Comment by marcbachmann** [comment]
I'll try to add the bootstrap config next. This is definitely needed to get it to work.
```yaml
layered_runtime:                                                             
  layers:                                                                    
    - name: static-layer
      static_layer:
        envoy.reloadable_features.prefer_quic_kernel_bpf_packet_routing: true
```

**Comment by marcbachmann** [comment]
I'm guessing the build server uses an older kernel.
The only mention about some version is in https://github.com/istio/proxy/blob/39ebaaf2f85c48dee3256b0f8ab2101286676a13/bazel/extension_config/extensions_build_config.bzl#L361

**Comment by su225** [comment]
I think resolving the following complaint is needed to make this feature more mature (cc: @howardjohn)
```
Efficient routing of QUIC packets to the correct worker is not supported or not implemented by Envoy on this platform. QUIC performance may be degraded.
```
Thanks @marcbachmann for investigation.

**Comment by howardjohn** [comment]
We build on Ubuntu 16.04 to get a build compatible with old GLIBC versions

**Comment by 13567436138** [comment]
```
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ebpf-packet-routing
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: BOOTSTRAP
    patch:
      operation: MERGE
      value:
        layered_runtime:
          layers:
          - name: native bpf packet routing
            static_layer:
              "envoy.reloadable_features.prefer_quic_kernel_bpf_packet_routing": true
```
this is not effictive,I have configed the mesh config.
it is effictive for workload sidecar,but not for ingressageway.
