### ISSUE TITLE
Verify cert-manager 1.5+ compatibility with Istio

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#36947]
I heard there were issues here around not finding IngressClass. Look into it

**Comment by maelvls** [comment]
Hi! You are correct, Istio users may have noticed that their HTTP-01 ACME issuer stopped working when upgrading to 1.5.

The issue, reported in https://github.com/jetstack/cert-manager/issues/4537, is caused by a regression introduced in 1.5. Before 1.5, cert-manager used to create an Ingress with the `kubernetes.io/ingress.class` annotation. With cert-manager 1.5 and 1.6, the annotation is not set anymore; instead, the field `ingressClassName` is set.

The workaround is to create an IngressClass on the cluster:

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
  name: istio
spec:
  controller: istio.io/ingress-controller
```

The regression is present in cert-manager 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.6.0, 1.6.1, 1.6.2, and 1.6.3, when using Kubernetes 1.21+ and when using an Issuer or ClusterIssuer with the ACME HTTP-01 solver configured using a `class: istio` is used.

Note that we will be fixing the regression in cert-manager 1.7 by reverting to the "create using the annotation" behaviour (to be released on 26 January 2022). We will also backport this fix to 1.5.5 and 1.6.4.
