### ISSUE TITLE
istioctl install failed with custom logging level

### ISSUE THREAD

**Issue by zirain** [istio/istio#36943]
### Bug Description

istioctl install failed with following iop:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    defaultConfig:
      proxyMetadata:
        # Enable Istio agent to handle DNS requests for known hosts
        # Unknown hosts will automatically be resolved using upstream dns servers in resolv.conf
        ISTIO_META_DNS_CAPTURE: "true"
        # Enable dynamic bootstrap generation.
        BOOTSTRAP_XDS_AGENT: "true"
        PROXY_CONFIG_XDS_AGENT: "true"
  values:
    global:
      logging:
        level: "default:debug,cache:debug"
    telemetry:
      v2:
        metadataExchange:
          wasmEnabled: true
        prometheus:
          wasmEnabled: true
```

istiod crashed with logs:
```console
Error: unknown scope 'cache' specified
2022-01-22T01:21:01.262305Z	error	unknown scope 'cache' specified
```

actually, `cache` is a valid scope in `pilot-agent` [click here](https://github.com/istio/istio/blob/a83fac0d7cd2fb68a464b55deb2906ad63e134b3/security/pkg/nodeagent/cache/secretcache.go#L42)

### Version

```prose
1.13-dev
```
