### ISSUE TITLE
istio-cni not working with rke hyperkube:v1.19.6-rancher1

### ISSUE THREAD

**Issue by ahiaht** [istio/istio#36958]
### Bug Description

istio 1.12.2 installed with a rke cluster using istio-operator. It's working for non-cni (using init container), however when trying to enable istio-cni. The istio-cni-node daemonset hanging with this in log:
```
2022-01-24T06:23:44.860613Z	info	CNI install configuration: 
CNINetDir: /etc/cni/net.d
MountedCNINetDir: /host/etc/cni/net.d
CNIConfName: istio-cni.conf
ChainedCNIPlugin: true
CNINetworkConfigFile: 
CNINetworkConfig: {
  "cniVersion": "0.3.1",
  "name": "istio-cni",
  "type": "istio-cni",
  "log_level": "info",
  "log_uds_address": "__LOG_UDS_ADDRESS__", 
  "kubernetes": {
      "kubeconfig": "__KUBECONFIG_FILEPATH__",
      "cni_bin_dir": "/opt/cni/bin",
      "exclude_namespaces": [ "istio-system", "kube-system", "istio-operator" ]
  }
}
CNIEnableReinstall: true
LogLevel: warn
KubeconfigFilename: ZZZ-istio-cni-kubeconfig
KubeconfigMode: 0600
KubeCAFile: 
SkipTLSVerify: false
K8sServiceProtocol: 
K8sServiceHost: 10.249.0.1
K8sServicePort: 443
K8sNodeName: istio-cni-node-g2dlv
UpdateCNIBinaries: true
SkipCNIBinaries: [[]]
MonitoringPort: 15014
LogUDSAddress: /var/run/istio-cni/log.sock

2022-01-24T06:23:44.860703Z	info	CNI race repair configuration: 
Enabled: true
RunAsDaemon: true
NodeName: w01-apps-nonprod-blue.hcnet.vn
LabelKey: cni.istio.io/uninitialized
LabelValue: true
DeletePods: true
LabelPods: true
SidecarAnnotation: sidecar.istio.io/status
InitContainerName: istio-validation
InitTerminationMsg: 
InitExitCode: 126
LabelSelectors: 
FieldSelectors: 

2022-01-24T06:23:44.860701Z	info	ControlZ available at 127.0.0.1:9876
2022-01-24T06:23:44.861068Z	info	Start a UDS server for CNI plugin logs
2022-01-24T06:23:44.861247Z	info	repair	Start CNI race condition repair.
2022-01-24T06:23:45.270946Z	info	install	Copied istio-cni to /host/opt/cni/bin.
2022-01-24T06:23:45.271057Z	info	install	Directory /host/secondary-bin-dir is not writable, skipping.
2022-01-24T06:23:45.271288Z	info	install	write kubeconfig file /host/etc/cni/net.d/ZZZ-istio-cni-kubeconfig with: 
# Kubeconfig file for Istio CNI plugin.
apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    server: https://[10.249.0.1]:443
    certificate-authority-data: <CA cert from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt>
users:
- name: istio-cni
  user:
    token: "<redacted>"
contexts:
- name: istio-cni-context
  context:
    cluster: local
    user: istio-cni
current-context: istio-cni-context

2022-01-24T06:23:45.271483Z	info	install	Using CNI config template from CNI_NETWORK_CONFIG environment variable.
2022-01-24T06:23:45.271503Z	info	install	CNI config: {
  "cniVersion": "0.3.1",
  "name": "istio-cni",
  "type": "istio-cni",
  "log_level": "info",
  "log_uds_address": "/var/run/istio-cni/log.sock", 
  "kubernetes": {
      "kubeconfig": "/etc/cni/net.d/ZZZ-istio-cni-kubeconfig",
      "cni_bin_dir": "/opt/cni/bin",
      "exclude_namespaces": [ "istio-system", "kube-system", "istio-operator" ]
  }
}
2022-01-24T06:23:45.271687Z	info	install	CNI config file /host/etc/cni/net.d/istio-cni.conf does not exist. Waiting for file to be written...
```

### Version

```prose
$k version --short
Client Version: v1.20.5
Server Version: v1.19.6
client version: 1.12.2
control plane version: 1.12.2
data plane version: none
```

### Additional Information

- rke version: hyperkube:v1.19.6-rancher1
- kubelet options:
```
"Entrypoint": [
                "/opt/rke-tools/entrypoint.sh",
                "kubelet",
                "--read-only-port=0",
                "--hostname-override=w01-apps-nonprod-blue.hcnet.vn",
                "--resolv-conf=/etc/resolv.conf",
                "--address=0.0.0.0",
                "--authentication-token-webhook=true",
                "--event-qps=0",
                "--client-ca-file=/etc/kubernetes/ssl/kube-ca.pem",
                "--fail-swap-on=true",
                "--cni-bin-dir=/opt/cni/bin",
                "--cni-conf-dir=/etc/cni/net.d",
                "--v=2",
                "--network-plugin=cni",
                "--authorization-mode=Webhook",
                "--cgroups-per-qos=True",
                "--streaming-connection-idle-timeout=30m",
                "--node-status-update-frequency=4s",
                "--make-iptables-util-chains=true",
                "--root-dir=/var/lib/kubelet",
                "--eviction-hard=memory.available<1.6Gi",
                "--tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
                "--pod-manifest-path=/etc/kubernetes/manifests",
                "--pod-infra-container-image=rancher-pause:3.2",
                "--volume-plugin-dir=/usr/libexec/kubernetes/kubelet-plugins/volume/exec",
                "--anonymous-auth=false",
                "--cloud-provider=",
                "--cluster-dns=10.249.0.10",
                "--cluster-domain=cluster.local",
                "--kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-node.yaml"
            ],

```
- istio operator crd:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-controlplane
spec:
  profile: minimal
  components:
    base:
      enabled: true
    cni:
      enabled: true
      namespace: kube-system
      k8s:
        overlays:
        - apiVersion: "apps/v1"
          kind: "DaemonSet"
          name: "istio-cni-node"
          patches:
          - path: spec.template.spec.containers.[name:install-cni].securityContext.privileged
            value: true
    egressGateways:
    - enabled: false
      name: istio-egressgateway
    ingressGateways:
    - enabled: false
      name: istio-ingressgateway
    istiodRemote:
      enabled: false
    pilot:
      enabled: true
      k8s:
        resources:
          requests:
            cpu: 1000m # override from default 500m
            memory: 2048Mi # ... default 2048Mi
          limits:
            cpu: 2000m # override from default 500m
            memory: 4096Mi # ... default 2048Mi
        hpaSpec:
          maxReplicas: 4 # ... default 5
          minReplicas: 2  # ... default 1
        # nodeSelector: {}
        # tolerations: {}
  tag: 1.12.2
  meshConfig:
    defaultConfig:
      tracing:
        zipkin:
          address: zipkin.istio-tracing.svc.cluster.local:9411
    accessLogFile: /dev/stdout
    enablePrometheusMerge: true
  values:
    global:
      imagePullPolicy: IfNotPresent
      proxy:
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      proxy_init:
        image: istio-proxyv2
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
    pilot:
      image: istio-pilot
    cni:
      image: istio-install-cni
      cniBinDir: /opt/cni/bin
      cniConfDir: /etc/cni/net.d
      cniConfFileName: istio-cni.conf
      repair:
        enabled: true
      logLevel: info
      excludeNamespaces:
        - istio-system
        - kube-system
        - istio-operator

```

### Affected product area

- [ ] Docs
- [X] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
