### ISSUE TITLE
Unable to use MTLS with cert-manager and Vault as CA. filter_chain_not_found

### ISSUE THREAD

**Issue by EnriqueLop** [istio/istio#36963]
Hi, I am deploying Vault as CA with cert-manager-istio-csr. I manage to make it work, Vault certificates are deployed in istio-proxy container but when I define MutualTLS in PeerAuthentication I get the following error when asking for request: filter_chain_not_found. 

I am deploying basic bookinfo productpage example. For this example I am trying to comunicate productpage with reviews.

# Steps
### 1. Install vault and configure it
Following this tutorial https://medium.com/everything-full-stack/how-to-integrate-vault-as-external-root-ca-with-cert-manager-istio-csr-and-istio-7684baa369db

### 2. Install Issuer
Using helm:
```
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
spec:
  vault:
    path: pki_int/sign/cluster-dot-local
    server: "http://vault.vault.svc.cluster.local:8200" # insert vault url
    auth:
      appRole:
        path: approle
        secretRef: 
          name: cert-manager-vault-approle
          key: secretId
```
Issuer gets validated

### 3. Install cert-manager-istio-crs
```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager-istio-csr
spec:
  releaseName: cert-manager-istio-csr
  chart:
    repository: https://charts.jetstack.io
    version: v0.3.1
    name: cert-manager-istio-csr
  values:
    app:
      logLevel: 5
      certmanager:
        issuer: 
          name: vault-issuer
      tls:
        trustDomain: "cluster.local"
        rootCAFile: /var/run/secrets/istio-csr/ca.cert.pem
    volumeMounts:
      - name: root-ca
        mountPath: /var/run/secrets/istio-csr
    volumes: 
      - name: root-ca
        secret:
          secretName: istio-root-ca
```

### 4. Install istiod
Istio definition: I use the example defined on istio-csr: https://github.com/cert-manager/istio-csr/blob/main/docs/istio-config-getting-started.yaml

### 5. Deploy bookinfo example.
As defined on samples/bookinfo/platform/kube/bookinfo.yaml

### 6. Enable mutual TLS
```
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: "mtls"
  namespace: mobie
spec:
  mtls:
    mode: STRICT
```

# Expected output
Pods comunicate eachother with mutualTLS

# Real output
I get two logs:
- Origin: 503 UC upstream_reset_before_response_started, PassthroughCluster allow_any-
- Destination:  0 NR 

# Searched solutions:
What I have looked on the internet is that I need a DestinationRule with sni. This is my configuration: 

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: productpage
spec:
  host: productpage.mobie.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: details
spec:
  host: details.mobie.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```

I have seen on some Issues that sni value is mandatory to make it works, but documentation says that when ISTIO_MUTUAL is enabled all fields shoulds be empty. https://istio.io/latest/docs/reference/config/networking/destination-rule/#ClientTLSSettings-TLSmode
