### ISSUE TITLE
Envoyfilter inline Lua code does not run in sidecar

### ISSUE THREAD

**Issue by benjaminxie** [istio/istio#36979]
### Bug Description

I am trying to modify the response headers for my pods so that they contain the pod name of the pod that responded to a request. I tried using the following EnvoyFilter with inline lua code:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: pod-identifier-filter
  namespace: the-app-namespace
spec:
  workloadSelector:
    labels:
      component: the-app
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_OUTBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value:
       name: envoy.lua
       typed_config:
         "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
         inlineCode: |
            function envoy_on_response(response_handle)
              podname = os.getenv("POD_NAME");
              response_handle:headers():add("podname", podname);
            end
```
I know I'm correctly targeting my pod because if I intentionally put a syntax error into the lua code, then I see the error in my app's pod's sidecar container's logs. However, if I fix the syntax error, the code doesn't seem to run because I don't see the response headers getting added.

What I have seen work is the following modified from [kabute/istio-security-by-default-header-filter.yaml](https://gist.github.com/kabute/ef8e7198031c8a99212a629a139ac83f)
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: modified-security-by-default-header-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value:
       name: envoy.lua
       typed_config:
         "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
         inlineCode: |
            function envoy_on_response(response_handle)
              podname = os.getenv("POD_NAME");
              response_handle:headers():add("podname", podname);
            end
```
What this gives me is a header with the istio-ingressgateway pod's name. While the istio-ingressgateway pod also runs istio-proxy, it uses the `router` argument instead of the `sidecar` argument. Don't know if this furthers the case that its a sidecar problem.

### Version

```prose
$ istioctl version                                                                                                                                                              client version: 1.11.0                                                                                                                                                                                 control plane version: 1.11.0                                                                                                                                                                          data plane version: 1.11.0 (2 proxies)
$ kubectl version --short                                                                                                                                                       Client Version: v1.21.5                                                                                                                                                                                Server Version: v1.22.4
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by benjaminxie** [comment]
Thanks for you speedy reply @howardjohn. I tried your suggestion of changing ```SIDECAR_OUTBOUND``` to ```SIDECAR_INBOUND``` (I also tried ```ANY```) and I didn't see any changes. Moreover, I added some log messages to my inline Lua code
```
function envoy_on_response(response_handle)
  response_handle:logCritical("uniqueEasyToFindString1");
  podname = os.getenv("POD_NAME");
  response_handle:headers():add("podname", podname);
  response_handle:logCritical("uniqueEasyToFindString2");
end
```
but I don't see them getting logged even after setting the proxy log level to debug.
>Otherwise its running on the proxy of the pod sending the request

The code is certainly on the pod but isn't this evidence that the code isn't running?

**Comment by chenzhiguo** [comment]
Hi，I have same issue, like this:
```yaml
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_OUTBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.lua
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
          inlineCode: |-
            function envoy_on_request(request_handle)
                request_handle:headers():add("group", "v1");
                request_handle:headers():add("namespace", "demo");
                request_handle:headers():add("service", "demoservice");
                zone = os.getenv("ZONE");
                request_handle:headers():add("zone", zone);
            end
```
I found that ZONE is always do not appear. Is `os.getenv("xxx")` not be executed?
