### ISSUE TITLE
control plane installation removes gateway resources before they get reapplied

### ISSUE THREAD

**Issue by chriskim06** [istio/istio#36982]
### Bug Description

we have a custom ingressgateway that whenever we reapply the control plane operator spec has its resources deleted. here is the controlplane operator spec:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  revision: 1-11-5
  values:
    global:
      proxy:
        autoInject: disabled
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "while [ $(netstat -plnt | grep tcp | grep -v envoy | wc -l) -ne 0 ]; do sleep 1; done"]
        includeIPRanges: "172.20.0.0/16"
    telemetry:
      v2:
        enabled: true
  meshConfig:
    accessLogFile: /dev/stdout
    accessLogFormat: "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% \"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME% %UPSTREAM_REQUEST_ATTEMPT_COUNT% %LOCAL_REPLY_BODY% %FILTER_CHAIN_NAME%"
    accessLogEncoding: TEXT

    protocolDetectionTimeout: 0s
    defaultConfig:
      proxyStatsMatcher:
        inclusionRegexps:
          - .*cluster_manager.*
          - .*listener_manager.*
          - .*cluster.*tcp_stats.*
          - .*cluster.*ssl.*
          - .*tls_inspector.*
          - .*http_inspector.*
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: false
      - name: private-ingressgateway
        namespace: foo
        enabled: false
    pilot:
      k8s:
        overlays:
        - kind: Service
          name: istiod-1-11-5
          patches:
          - path: metadata.annotations
            value:
              # annotations needed found here:
              # https://www.datadoghq.com/blog/how-to-monitor-istiod/#configure-the-datadog-agents-to-track-your-istio-deployment
              ad.datadoghq.com/endpoints.check_names: '["istio"]'
              ad.datadoghq.com/endpoints.init_configs: '[{}]'
              ad.datadoghq.com/endpoints.instances: |
                  [
                    {
                      "istiod_endpoint": "http://%%host%%:15014/metrics",
                      "send_histograms_buckets": true
                    }
                  ]
        env:
        - name: PILOT_SIDECAR_USE_REMOTE_ADDRESS
          value: 'true'
        replicaCount: 2
        hpaSpec:
          minReplicas: 2
```
and here is the gateways operator spec
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-1-11-5-gateways # REQUIRED
spec:
  profile: empty # REQUIRED
  revision: 1-11-5
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
      - name: private-ingressgateway
        namespace: foo
        enabled: true
        k8s:
          podAnnotations:
            proxy.istio.io/config: |
              discoveryAddress: istiod-1-11-5.istio-system.svc:15012
```

when running `istioctl install` we see output like this
```
...
- Processing resources for Istio core.
✔ Istio core installed
- Processing resources for Istiod.
✔ Istiod installed
Removed HorizontalPodAutoscaler:foo:private-ingressgateway.
Removed HorizontalPodAutoscaler:istio-system:istio-ingressgateway.
Removed PodDisruptionBudget:foo:private-ingressgateway.
Removed PodDisruptionBudget:istio-system:istio-ingressgateway.
Removed Deployment:foo:private-ingressgateway.
Removed Deployment:istio-system:istio-ingressgateway.
Removed Service:foo:private-ingressgateway.
Removed Service:istio-system:istio-ingressgateway.
Removed ServiceAccount:foo:private-ingressgateway-service-account.
Removed ServiceAccount:istio-system:istio-ingressgateway-service-account.
Removed RoleBinding:foo:private-ingressgateway-sds.
Removed RoleBinding:istio-system:istio-ingressgateway-sds.
Removed Role:foo:private-ingressgateway-sds.
Removed Role:istio-system:istio-ingressgateway-sds.
- Pruning removed resources
✔ Installation complete
...
```

a new elb is created each time for the `private-ingressgateway` and I was wondering why the service is deleted when the control plane is applied? I've tried this with and without the explicit gateway `enabled: false` in the control plane spec but not really sure what's happening.

### Version

```prose
$ istioctl version
client version: 1.10.6
istiod version: 1.10.6
istiod version: 1.10.6
istiod version: 1.11.5
istiod version: 1.11.5
data plane version: 1.10.6 (6 proxies), 1.11.5 (24 proxies)

$ kubectl version --short
Client Version: v1.20.7
Server Version: v1.20.7-eks-d88609
```
