### ISSUE TITLE
Locality aware load balancing does not work as expected for workloadEntry workloads

### ISSUE THREAD

**Issue by iandyh** [istio/istio#37008]
### Bug Description

A `workloadEntry` defines a remote(jpe2) workload.
```
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: deps-in-another-az
spec:
  address: {someip}
  ports:
    http: 80
  locality: jpe2/jpe2z
  labels:
    app: upgrade-test
```
A `serviceEntry` defines local workloads(jpe1).
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  namespace: caas-sentinel
  name: instantdomain-to-svc
spec:
  hosts:
  - {some domain}
  location: MESH_INTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
    targetPort: 8080
  resolution: STATIC
  workloadSelector:
    labels:
      app: upgrade-test
```
`destinationRule` defines the weight distribution across jpe1, jpe2. 

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: fail-over-test
spec:
  host: sample-app-80-caas-sentinel.jpe2-caas1-beta1.caas.jpe2z.r-local.net
  trafficPolicy:
    connectionPool:
      http:
        maxRequestsPerConnection: 1
    loadBalancer:
      simple: ROUND_ROBIN
      localityLbSetting:
        enabled: true
        distribute:
          - from: jpe1/jpe1b
            to:
              "jpe2/jpe2z": 100
              #"jpe2/*": 0
    outlierDetection:
      consecutive5xxErrors: 1
      interval: 1s
      baseEjectionTime: 1m
```
Expectation: When I am sending the traffic from jpe1, all the traffic should be sent to jpe2. 
Actual: Traffic is being evently split between jpe1 and jpe2.

### Version

```prose
client version: 1.12.0
control plane version: 1.9.9
data plane version: 1.9.5 (123 proxies), 1.9.9 (43 proxies), 1.8.2 (1 proxies)
```
```


### Additional Information

Below is the info from Envoy `/clusters` endpoint.
```
outbound|80||{somedomain}::{someaddr}::weight::1
outbound|80||{somedomain}::{someaddr}::region::jpe1
outbound|80||{somedomain}::{someaddr}::zone::jpe1b

outbound|80||{somedomain}::{someaddr}::weight::1
outbound|80||{somedomain}::{someaddr}::region::jpe2
outbound|80||{somedomain}::{someaddr}::zone::jpe2z
```
From my understanding, the region/zone info is populated correctly but the weighted info is not?

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
