### ISSUE TITLE
oauth2 envoyfilter not working in istio with Keycloak

### ISSUE THREAD

**Issue by ricosega** [istio/istio#37016]
### Bug Description

Hi there,

I am using the stack "Istio - oauth2-proxy - Keycloak" for authentication in my apps and as I have seen the [oauth2 filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/oauth2_filter) I wanted to get rid of oauth2-proxy.

I followed this [post](https://getindata.com/blog/oauth2-based-authentication-on-istio-powered-kubernetes-clusters/) in order to make it work with the only difference I am using Keycloak instead of GoogleOauth.

I applied the following [.yaml](https://gist.github.com/ricosega/a08674756ddbe96cbdbf70e98c063cdc)

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: oauth2-ingress
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.jwt_authn"
    patch:
      operation: INSERT_BEFORE
      value:
       name: envoy.filters.http.oauth2
       typed_config:
         "@type": type.googleapis.com/envoy.extensions.filters.http.oauth2.v3alpha.OAuth2
         config:
          token_endpoint:
            cluster: oauth
            uri: https://keycloak.local/auth/realms/test/protocol/openid-connect/token
            timeout: 3s
          authorization_endpoint: https://keycloak.local/auth/realms/test/protocol/openid-connect/auth
          redirect_uri: "%REQ(x-forwarded-proto)%://%REQ(:authority)%/callback"
          redirect_path_matcher:
            path:
              exact: /callback          
          signout_path:
            path:
              exact: /signout
          credentials:
            client_id: test
            token_secret:
              name: token
              sds_config:
                path: "/etc/istio/config/oauth2/token-secret.yaml"
            hmac_secret:
              name: hmac
              sds_config:
                path: "/etc/istio/config/oauth2/hmac-secret.yaml"
          pass_through_matcher:
            - name: authorization
              prefix_match: Bearer
          auth_scopes:
            - profile
            - openid
            - email
          forward_bearer_token: true                 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-oauth2
  namespace: istio-system
data:
  token-secret.yaml: |-
    resources:
      - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
        name: token
        generic_secret:
          secret:
            inline_string: "NDgxODZjZDQtMTZmYy00NTc5LTkyNDgtZTVmNTcyZGIzYTEwCg=="
  hmac-secret.yaml: |-
    resources:
      - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
        name: hmac
        generic_secret:
          secret:
            inline_bytes: XYJ7ibKwXwmRrO/yL/37ZV+T3Q/WB+xfhmVlio+wmc0=
            # generated using `head -c 32 /dev/urandom | base64`
---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: jwt-authentication
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  jwtRules:
    - issuer: "https://keycloak.local/auth/realms/test"
      jwksUri: "https://keycloak.local/auth/realms/test/protocol/openid-connect/certs"
      forwardOriginalToken: true
      audiences:
        - test
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: known-user
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  rules:
  - when:
    - key: request.headers[Authorization]
      notValues:
      - 'Bearer*'
  - when:
    - key: request.auth.audiences
      values: 
        - 'test'
    - key: request.auth.presenter
      values:
        - test
---
```

And when I try to access any app I am properly redirected to Keycloak, then I input username and password but when I am redirected back to the app I get the following message: "OAuth flow failed".

What is wrong in my config? What I am missing?

### Version

```prose
istioctl version --remote
client version: 1.10.0
control plane version: 1.10.0
data plane version: 1.10.0 (112 proxies)

kubectl version --short
Client Version: v1.22.1
Server Version: v1.22.1

helm version --short
v3.4.1+gc4e7485
```

**Comment by nelson3219** [comment]
Hello @ricosega,

the "OAuth flow failed" error message can mean all kinds of problems.

To debug set the log level of istio-proxy to debug: 

`kubectl exec <pod> -c istio-proxy -- curl -X POST http://localhost:15000/logging?level=debug`

The isiot-proxy logs realy helped me to figure out the issue in my case.

I followed the same tutorial post for my setup and i had to solve two issues:
1. My keycloak setup did not have the scopes "profile" and  "openid". I simply removed them from the envoy filter for testing purpose.
2. I had to make sure the Client-Secret was _**plain text and not base64 encoded**_: 
```
token-secret.yaml: |-
    resources:
      - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
        name: token
        generic_secret:
          secret:
            inline_string: "**XXXXXXXXXXXXXXXXXXXXXXXXX**"
```

Maybe this clould be the solution for you, otherwise you can post the output of the istio-proxy logs on debug level for further investigations.
