### ISSUE TITLE
ServiceEntries targetPort change is not getting updated

### ISSUE THREAD

**Issue by rvennam** [istio/istio#37022]
### Bug Description

```
cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: se-update
spec:
  hosts:
  - reviews.global
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 9080
    protocol: http
    targetPort: 9081 # NOTE! <---
  resolution: STATIC
  workloadSelector:
    labels:
      app: reviews
EOF
```
```
istioctl pc endpoints deploy/productpage-v1 | grep reviews.global
10.44.0.49:9081                  HEALTHY     OK                outbound|9080||reviews.global
10.44.1.55:9081                  HEALTHY     OK                outbound|9080||reviews.global
10.44.1.56:9081                  HEALTHY     OK                outbound|9080||reviews.global
```
Update the targetPort and apply again:
```
cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: se-update
spec:
  hosts:
  - reviews.global
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 9080
    protocol: http
    targetPort: 9080 # CHANGE TO 9080
  resolution: STATIC
  workloadSelector:
    labels:
      app: reviews
EOF
```
```
serviceentry.networking.istio.io/se-update configured
~ 🏎  $ istioctl pc endpoints deploy/productpage-v1 | grep reviews.global
10.44.0.49:9081                  HEALTHY     OK                outbound|9080||reviews.global
10.44.1.55:9081                  HEALTHY     OK                outbound|9080||reviews.global
10.44.1.56:9081                  HEALTHY     OK                outbound|9080||reviews.global
```

Endpoints still have the old 9081 value. `istioctl ps` shows all SYNCED

### Version

```prose
$ istioctl version
client version: 1.11.5
control plane version: 1.11.5
data plane version: 1.11.5 (10 proxies)
```
