### ISSUE TITLE
sidecar.istio.io/componentLogLevel annotation doesn't seem to work

### ISSUE THREAD

**Issue by chriskim06** [istio/istio#37046]
### Bug Description

I have a gateway defined in an istiooperator where I'm trying to use the `sidecar.istio.io/componentLogLevel` annotation to set component log levels for the proxy
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-1-11-5-gateway
spec:
  profile: empty
  revision: 1-11-5
  components:
    ingressGateways:
      - name: private-ingressgateway
        namespace: foo
        enabled: true
        k8s:
          podAnnotations:
            sidecar.istio.io/componentLogLevel: connection:trace,conn_handler:trace,envoy_bug:trace,filter:trace,http:trace,http2:trace,pool:trace,router:trace
            proxy.istio.io/config: |
              discoveryAddress: istiod-1-11-5.istio-system.svc:15012
```

the annotation is properly applied to the pod but when I check the components I notice that they aren't set to trace like I expected
```
$ k exec private-ingressgateway-5495bf98b4-6cc4k -- curl -s -X POST http://localhost:15000/logging
active loggers:
  admin: warning
  aws: warning
  assert: warning
  backtrace: warning
  cache_filter: warning
  client: warning
  config: warning
  connection: warning
  conn_handler: warning
  decompression: warning
  dubbo: warning
  envoy_bug: warning
  ext_authz: warning
  rocketmq: warning
  file: warning
  filter: warning
  forward_proxy: warning
  grpc: warning
  hc: warning
  health_checker: warning
  http: warning
  http2: warning
  hystrix: warning
  init: warning
  io: warning
  jwt: warning
  kafka: warning
  lua: warning
  main: warning
  matcher: warning
  misc: error
  mongo: warning
  quic: warning
  quic_stream: warning
  pool: warning
  rbac: warning
  redis: warning
  router: warning
  runtime: warning
  stats: warning
  secret: warning
  tap: warning
  testing: warning
  thrift: warning
  tracing: warning
  upstream: warning
  udp: warning
  wasm: warning
```

### Version

```prose
$ istioctl version
client version: 1.10.6
istiod version: 1.10.6
istiod version: 1.10.6
istiod version: 1.11.5
istiod version: 1.11.5
data plane version: 1.10.6 (6 proxies), 1.11.5 (24 proxies)

$ kubectl version --short
Client Version: v1.20.7
Server Version: v1.20.7-eks-d88609
```

**Comment by howardjohn** [comment]
This annotation only works on sidecars or gateways installed following the docs on this page: https://istio.io/latest/docs/setup/additional-setup/gateway/

**Comment by chriskim06** [comment]
hmm ok thanks, so we do use `istioctl install -f` with this istiooperator to install it. the only major difference I see in the example in that doc is this section of that gateway istiooperator
```
...
spec:
  ...
  values:
    gateways:
      istio-ingressgateway:
        # Enable gateway injection
        injectionTemplate: gateway
```
is missing that section what's causing this to not work?

**Comment by howardjohn** [comment]
Yes

**Comment by chriskim06** [comment]
thanks that fixed it! im running into a different issue though with a different gateway when setting that. we have a second one configured like this
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-1-11-5-istio-ingressgateway # REQUIRED
spec:
  profile: empty # REQUIRED
  revision: 1-11-5
  values:
    gateways:
      istio-ingressgateway:
        injectionTemplate: gateway
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
          service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
          service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: 'true'
          service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: '30'
          service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '600'
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
```
but the pod that comes up is encountering an imagepullbackoff error. it seems like the `image: auto` isn't being replaced when this istiooperator is `istioctl install`'d. the other gateway didn't have an issue though
