### ISSUE TITLE
Multi Cluster setup in Onprem clusters

### ISSUE THREAD

**Issue by cloudcafetech** [istio/istio#37042]
We have two onprem rancher (RKE1) clusters in onprem and both are same subnet.

All installation done and looks good but cross cluster communation not happening 

During verifications with below command ..

```for i in {1..9}; do kubectl --context=dev -n sample exec sleep-557747455f-jwkd8 -c sleep -- curl -s helloworld:5000/hello; done```

It always showing V1

I installed Metallb and in two cluster I took following IP range in configmap **but no luck**.

```
LB1=172.17.255.225-172.17.255.250
LB2=172.17.255.200-172.17.255.224
```

Please guide me to setup in onproem K8S.

I am able to setup sucessfully including verification in KIND Multiple cluster where I took following IP range .

```
LB1=172.18.255.225-172.18.255.250
LB2=172.18.255.200-172.18.255.224
```

Followed https://istio.io/latest/docs/ops/diagnostic-tools/multicluster/ but did not helped.

**Comment by zirain** [comment]
can you share the istio install steps?

**Comment by cloudcafetech** [comment]
> can you share the istio install steps?

On top of two Rancher clusters (RKE1)

- Melallb

```
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.10.2/manifests/namespace.yaml  --context $CTX_CLUSTER1
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.10.2/manifests/metallb.yaml --context $CTX_CLUSTER1

kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.10.2/manifests/namespace.yaml  --context $CTX_CLUSTER2
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.10.2/manifests/metallb.yaml --context $CTX_CLUSTER2

cat <<EOF > ctx1-metalb-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 172.17.255.225-172.17.255.250
EOF

cat <<EOF > ctx2-metalb-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 172.17.255.200-172.17.255.224
EOF

 kubectl apply -f ctx1-metalb-config.yaml --context $CTX_CLUSTER1
 kubectl apply -f ctx2-metalb-config.yaml --context $CTX_CLUSTER2
```

- Istio

As per my [doc](https://github.com/cloudcafetech/k8s-service-mesh/blob/main/multi-cluster-Istio.md)

**Comment by zirain** [comment]
can you run `istioctl pc ep sleep-557747455f-jwkd8 -n sample` and share the istiod pod logs?

**Comment by cloudcafetech** [comment]
```
istioctl pc ep sleep-557747455f-s6hgm -n sample --context=stage
ENDPOINT                         STATUS      OUTLIER CHECK     CLUSTER
10.42.1.22:80                    HEALTHY     OK                outbound|80||cattle-cluster-agent.cattle-system.svc.cluster.local
10.42.1.22:444                   HEALTHY     OK                outbound|443||cattle-cluster-agent.cattle-system.svc.cluster.local
10.42.2.28:80                    HEALTHY     OK                outbound|80||cattle-cluster-agent.cattle-system.svc.cluster.local
10.42.2.28:444                   HEALTHY     OK                outbound|443||cattle-cluster-agent.cattle-system.svc.cluster.local
10.42.2.29:25227                 HEALTHY     OK                outbound|25227||healthmodel-replicaset-service.kube-system.svc.cluster.local
10.42.3.159:53                   HEALTHY     OK                outbound|53||kube-dns.kube-system.svc.cluster.local
10.42.3.159:9153                 HEALTHY     OK                outbound|9153||kube-dns.kube-system.svc.cluster.local
10.42.3.161:4443                 HEALTHY     OK                outbound|443||metrics-server.kube-system.svc.cluster.local
10.42.3.163:5000                 HEALTHY     OK                outbound|5000||order-svc.default.svc.cluster.local
10.42.3.199:15010                HEALTHY     OK                outbound|15010||istiod.istio-system.svc.cluster.local
10.42.3.199:15012                HEALTHY     OK                outbound|15012||istiod.istio-system.svc.cluster.local
10.42.3.199:15014                HEALTHY     OK                outbound|15014||istiod.istio-system.svc.cluster.local
10.42.3.199:15017                HEALTHY     OK                outbound|443||istiod.istio-system.svc.cluster.local
10.42.3.200:5000                 HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
10.42.4.205:8443                 HEALTHY     OK                outbound|443||kubernetes-dashboard.kubernetes-dashboard.svc.cluster.local
10.42.4.208:8000                 HEALTHY     OK                outbound|8000||dashboard-metrics-scraper.kubernetes-dashboard.svc.cluster.local
10.42.4.225:9090                 HEALTHY     OK                outbound|9090||kubemon-prometheus.monitoring.svc.cluster.local
10.42.4.230:80                   HEALTHY     OK                outbound|80||sleep.sample.svc.cluster.local
10.42.5.134:5000                 HEALTHY     OK                outbound|5000||user-svc.default.svc.cluster.local
10.42.5.135:5000                 HEALTHY     OK                outbound|5000||user-svc.default.svc.cluster.local
10.42.5.137:5000                 HEALTHY     OK                outbound|5000||order-svc.default.svc.cluster.local
10.42.5.209:8080                 HEALTHY     OK                outbound|80||istio-ingressgateway.istio-system.svc.cluster.local
10.42.5.209:8443                 HEALTHY     OK                outbound|443||istio-ingressgateway.istio-system.svc.cluster.local
10.42.5.209:15021                HEALTHY     OK                outbound|15021||istio-ingressgateway.istio-system.svc.cluster.local
10.42.5.210:15012                HEALTHY     OK                outbound|15012||istio-eastwestgateway.istio-system.svc.cluster.local
10.42.5.210:15017                HEALTHY     OK                outbound|15017||istio-eastwestgateway.istio-system.svc.cluster.local
10.42.5.210:15021                HEALTHY     OK                outbound|15021||istio-eastwestgateway.istio-system.svc.cluster.local
10.42.5.210:15443                HEALTHY     OK                outbound|15443||istio-eastwestgateway.istio-system.svc.cluster.local
10.42.5.211:9090                 HEALTHY     OK                outbound|9090||prometheus.istio-system.svc.cluster.local
10.42.6.189:53                   HEALTHY     OK                outbound|53||kube-dns.kube-system.svc.cluster.local
10.42.6.189:9153                 HEALTHY     OK                outbound|9153||kube-dns.kube-system.svc.cluster.local
10.42.6.192:8080                 HEALTHY     OK                outbound|8080||kubemon-kube-state-metrics.monitoring.svc.cluster.local
10.42.6.192:8081                 HEALTHY     OK                outbound|8081||kubemon-kube-state-metrics.monitoring.svc.cluster.local
10.42.6.193:9093                 HEALTHY     OK                outbound|9093||kubemon-alertmanager.monitoring.svc.cluster.local
10.42.6.194:2000                 HEALTHY     OK                outbound|2000||prometheus-msteams.monitoring.svc.cluster.local
10.42.6.195:9093                 HEALTHY     OK                outbound|9093||kubemon-alertmanager.monitoring.svc.cluster.local
10.42.6.196:8081                 HEALTHY     OK                outbound|8081||twistlock-console.twistlock.svc.cluster.local
10.42.6.196:8083                 HEALTHY     OK                outbound|8083||twistlock-console.twistlock.svc.cluster.local
10.42.6.196:8084                 HEALTHY     OK                outbound|8084||twistlock-console.twistlock.svc.cluster.local
10.42.6.198:3000                 HEALTHY     OK                outbound|3000||grafana-service.monitoring.svc.cluster.local
10.42.6.232:9090                 HEALTHY     OK                outbound|9090||kiali.istio-system.svc.cluster.local
10.42.6.232:20001                HEALTHY     OK                outbound|20001||kiali.istio-system.svc.cluster.local
127.0.0.1:15000                  HEALTHY     OK                prometheus_stats
127.0.0.1:15020                  HEALTHY     OK                agent
172.25.80.171:6443               HEALTHY     OK                outbound|443||kubernetes.default.svc.cluster.local
172.25.80.172:6443               HEALTHY     OK                outbound|443||kubernetes.default.svc.cluster.local
172.25.80.173:6443               HEALTHY     OK                outbound|443||kubernetes.default.svc.cluster.local
172.25.80.174:9998               HEALTHY     OK                outbound|443||defender.twistlock.svc.cluster.local
172.25.80.175:9998               HEALTHY     OK                outbound|443||defender.twistlock.svc.cluster.local
172.25.80.177:80                 HEALTHY     OK                outbound|80||ingress-nginx-controller.kube-router.svc.cluster.local
172.25.80.177:443                HEALTHY     OK                outbound|443||ingress-nginx-controller.kube-router.svc.cluster.local
172.25.80.177:9998               HEALTHY     OK                outbound|443||defender.twistlock.svc.cluster.local
172.25.80.177:10254              HEALTHY     OK                outbound|10254||ingress-nginx-controller.kube-router.svc.cluster.local
172.25.80.178:80                 HEALTHY     OK                outbound|80||ingress-nginx-controller.kube-router.svc.cluster.local
172.25.80.178:443                HEALTHY     OK                outbound|443||ingress-nginx-controller.kube-router.svc.cluster.local
172.25.80.178:9998               HEALTHY     OK                outbound|443||defender.twistlock.svc.cluster.local
172.25.80.178:10254              HEALTHY     OK                outbound|10254||ingress-nginx-controller.kube-router.svc.cluster.local
172.25.80.211:15443              HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
172.25.80.211:15443              HEALTHY     OK                outbound|80||sleep.sample.svc.cluster.local
unix://./etc/istio/proxy/SDS     HEALTHY     OK                sds-grpc
unix://./etc/istio/proxy/XDS     HEALTHY     OK                xds-grpc
```

**Comment by zirain** [comment]
> 

seems something error with multi-cluster discovery, please check istiod logs

**Comment by cloudcafetech** [comment]
Issue was in metal lb

**Comment by cloudcafetech** [comment]
The SE,VS & DR are as follows ..

```
export ENV1=dev
export ENV2=stage
export ENV2GW=`kubectl --context=$ENV2 -n istio-system get svc istio-eastwestgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}'`

kubectl apply --context=$ENV1 -f istio-1.10.1/samples/bookinfo/networking/bookinfo-gateway.yaml -n sample
kubectl apply --context=$ENV1 -f gw-ing.yaml

kubectl --context=$ENV1 -n sample apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: reviews-sample
spec:
  hosts:
  - review.sample.global
  location: MESH_INTERNAL
  ports:
  - name: http1
    number: 9080
    protocol: http
  resolution: DNS
  endpoints:
  - address: $ENV2GW
    labels:
      cluster: stage-cluster
    ports:
      http1: 15443 # Do not change this port value
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews-global
spec:
  host: review.sample.global
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v2
    labels:
      cluster: stage-cluster
  - name: v3
    labels:
      cluster: stage-cluster
EOF

kubectl apply --context=$ENV1 -n sample -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews
spec:
  host: reviews.sample.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  - name: v3
    labels:
      version: v3
EOF

kubectl apply --context=$ENV2 -n sample -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews
spec:
  host: reviews.sample.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  - name: v3
    labels:
      version: v3
EOF

kubectl apply --context=$ENV1 -n sample -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
    - reviews.sample.svc.cluster.local
  http:
  - match:
    - headers:
        end-user:
          exact: jason
    route:
    - destination:
        host: review.sample.global
        subset: v2
      weight: 50
    - destination:
        host: review.sample.global
        subset: v3
      weight: 50
  - route:
    - destination:
        host: reviews.sample.svc.cluster.local
        subset: v1
EOF
```

```
[test]$ oc get po,svc -n istio-system --context dev
NAME                                         READY   STATUS    RESTARTS   AGE
pod/istio-eastwestgateway-566cb66947-bzdx8   1/1     Running   0          3h11m
pod/istio-ingressgateway-67d86d456d-nh9wc    1/1     Running   0          3h11m
pod/istiod-8777ff57-mggvf                    1/1     Running   0          3h11m
pod/jaeger-7f78b6fb65-7ngqb                  1/1     Running   0          3h10m
pod/kiali-5ccffdfd97-tf45g                   1/1     Running   0          3h10m

NAME                            TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                                                           AGE
service/istio-eastwestgateway   LoadBalancer   10.43.153.40    172.25.80.211   15021:30146/TCP,15443:30176/TCP,15012:31239/TCP,15017:31993/TCP   3h11m
service/istio-ingressgateway    LoadBalancer   10.43.102.38    172.25.80.210   15021:30183/TCP,80:30746/TCP,443:31112/TCP                        3h11m
service/istiod                  ClusterIP      10.43.250.3     <none>          15010/TCP,15012/TCP,443/TCP,15014/TCP                             3h11m
service/jaeger-collector        ClusterIP      10.43.66.70     <none>          14268/TCP,14250/TCP                                               3h10m
service/kiali                   ClusterIP      10.43.172.25    <none>          20001/TCP,9090/TCP                                                3h10m
service/tracing                 ClusterIP      10.43.173.113   <none>          80/TCP                                                            3h10m
service/zipkin                  ClusterIP      10.43.144.41    <none>          9411/TCP                                                          3h10m
[test]$ oc get po,svc -n istio-system --context stage
NAME                                         READY   STATUS    RESTARTS   AGE
pod/istio-eastwestgateway-766b7c4877-7ms5j   1/1     Running   0          3h10m
pod/istio-ingressgateway-5d9f5d6dc8-9qz4m    1/1     Running   0          3h10m
pod/istiod-f6c8b6844-2zfkn                   1/1     Running   0          3h11m
pod/jaeger-7f78b6fb65-jm52p                  1/1     Running   0          3h10m
pod/kiali-5ccffdfd97-nrmn8                   1/1     Running   0          3h10m

NAME                            TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                                                           AGE
service/istio-eastwestgateway   LoadBalancer   10.43.80.10     172.25.80.213   15021:32079/TCP,15443:32645/TCP,15012:32284/TCP,15017:32051/TCP   3h10m
service/istio-ingressgateway    LoadBalancer   10.43.119.8     172.25.80.212   15021:30046/TCP,80:31077/TCP,443:32582/TCP                        3h10m
service/istiod                  ClusterIP      10.43.123.74    <none>          15010/TCP,15012/TCP,443/TCP,15014/TCP                             3h10m
service/jaeger-collector        ClusterIP      10.43.246.126   <none>          14268/TCP,14250/TCP                                               3h10m
service/kiali                   ClusterIP      10.43.87.165    <none>          20001/TCP,9090/TCP                                                3h10m
service/tracing                 ClusterIP      10.43.194.26    <none>          80/TCP                                                            3h10m
service/zipkin                  ClusterIP      10.43.55.96     <none>          9411/TCP                                                          3h10m
[test]$ oc get po,svc -n sample --context dev
NAME                                  READY   STATUS    RESTARTS   AGE
pod/details-v1-5cdc45f7d6-gprjh       2/2     Running   0          163m
pod/helloworld-v1-776f57d5f6-97h4l    2/2     Running   0          3h9m
pod/productpage-v1-66769bdb68-5q9mc   2/2     Running   0          163m
pod/reviews-v1-7f7997b945-27xp8       2/2     Running   0          163m
pod/sleep-557747455f-wkllp            2/2     Running   0          3h10m

NAME                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/details       ClusterIP   10.43.218.41    <none>        9080/TCP   163m
service/helloworld    ClusterIP   10.43.57.118    <none>        5000/TCP   3h10m
service/productpage   ClusterIP   10.43.207.166   <none>        9080/TCP   163m
service/reviews       ClusterIP   10.43.40.115    <none>        9080/TCP   163m
service/sleep         ClusterIP   10.43.29.32     <none>        80/TCP     3h10m
[test]$ istioctl --context=$ENV1 pc ep sleep-557747455f-wkllp.sample
ENDPOINT                         STATUS      OUTLIER CHECK     CLUSTER
10.42.0.19:4443                  HEALTHY     OK                outbound|443||metrics-server.kube-system.svc.cluster.local
10.42.0.20:80                    HEALTHY     OK                outbound|80||cattle-cluster-agent.cattle-system.svc.cluster.local
10.42.0.20:444                   HEALTHY     OK                outbound|443||cattle-cluster-agent.cattle-system.svc.cluster.local
10.42.0.22:53                    HEALTHY     OK                outbound|53||kube-dns.kube-system.svc.cluster.local
10.42.0.22:9153                  HEALTHY     OK                outbound|9153||kube-dns.kube-system.svc.cluster.local
10.42.1.39:53                    HEALTHY     OK                outbound|53||kube-dns.kube-system.svc.cluster.local
10.42.1.39:9153                  HEALTHY     OK                outbound|9153||kube-dns.kube-system.svc.cluster.local
10.42.1.87:15012                 HEALTHY     OK                outbound|15012||istio-eastwestgateway.istio-system.svc.cluster.local
10.42.1.87:15017                 HEALTHY     OK                outbound|15017||istio-eastwestgateway.istio-system.svc.cluster.local
10.42.1.87:15021                 HEALTHY     OK                outbound|15021||istio-eastwestgateway.istio-system.svc.cluster.local
10.42.1.87:15443                 HEALTHY     OK                outbound|15443||istio-eastwestgateway.istio-system.svc.cluster.local
10.42.1.88:5000                  HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
10.42.1.89:9080                  HEALTHY     OK                outbound|9080||details.sample.svc.cluster.local
10.42.2.124:15010                HEALTHY     OK                outbound|15010||istiod.istio-system.svc.cluster.local
10.42.2.124:15012                HEALTHY     OK                outbound|15012||istiod.istio-system.svc.cluster.local
10.42.2.124:15014                HEALTHY     OK                outbound|15014||istiod.istio-system.svc.cluster.local
10.42.2.124:15017                HEALTHY     OK                outbound|443||istiod.istio-system.svc.cluster.local
10.42.3.37:8080                  HEALTHY     OK                outbound|8080||kubemon-kube-state-metrics.monitoring.svc.cluster.local
10.42.3.37:8081                  HEALTHY     OK                outbound|8081||kubemon-kube-state-metrics.monitoring.svc.cluster.local
10.42.3.38:3000                  HEALTHY     OK                outbound|3000||grafana-service.monitoring.svc.cluster.local
10.42.3.39:9090                  HEALTHY     OK                outbound|9090||kubemon-prometheus.monitoring.svc.cluster.local
10.42.3.40:9093                  HEALTHY     OK                outbound|9093||kubemon-alertmanager.monitoring.svc.cluster.local
10.42.3.41:2000                  HEALTHY     OK                outbound|2000||prometheus-msteams.monitoring.svc.cluster.local
10.42.3.42:9093                  HEALTHY     OK                outbound|9093||kubemon-alertmanager.monitoring.svc.cluster.local
10.42.4.173:8080                 HEALTHY     OK                outbound|80||istio-ingressgateway.istio-system.svc.cluster.local
10.42.4.173:8443                 HEALTHY     OK                outbound|443||istio-ingressgateway.istio-system.svc.cluster.local
10.42.4.173:15021                HEALTHY     OK                outbound|15021||istio-ingressgateway.istio-system.svc.cluster.local
10.42.4.174:9411                 HEALTHY     OK                outbound|9411||zipkin.istio-system.svc.cluster.local
10.42.4.174:14250                HEALTHY     OK                outbound|14250||jaeger-collector.istio-system.svc.cluster.local
10.42.4.174:14268                HEALTHY     OK                outbound|14268||jaeger-collector.istio-system.svc.cluster.local
10.42.4.174:16686                HEALTHY     OK                outbound|80||tracing.istio-system.svc.cluster.local
10.42.4.175:9090                 HEALTHY     OK                outbound|9090||kiali.istio-system.svc.cluster.local
10.42.4.175:20001                HEALTHY     OK                outbound|20001||kiali.istio-system.svc.cluster.local
10.42.4.176:80                   HEALTHY     OK                outbound|80||sleep.sample.svc.cluster.local
10.42.4.177:9080                 HEALTHY     OK                outbound|9080||productpage.sample.svc.cluster.local
10.42.4.178:9080                 HEALTHY     OK                outbound|9080|v1|reviews.sample.svc.cluster.local
10.42.4.178:9080                 HEALTHY     OK                outbound|9080||reviews.sample.svc.cluster.local
10.42.4.3:80                     HEALTHY     OK                outbound|80||cattle-cluster-agent.cattle-system.svc.cluster.local
10.42.4.3:444                    HEALTHY     OK                outbound|443||cattle-cluster-agent.cattle-system.svc.cluster.local
10.43.144.41:9411                HEALTHY     OK                zipkin
127.0.0.1:15000                  HEALTHY     OK                prometheus_stats
127.0.0.1:15020                  HEALTHY     OK                agent
172.25.80.133:6443               HEALTHY     OK                outbound|443||kubernetes.default.svc.cluster.local
172.25.80.134:6443               HEALTHY     OK                outbound|443||kubernetes.default.svc.cluster.local
172.25.80.135:6443               HEALTHY     OK                outbound|443||kubernetes.default.svc.cluster.local
172.25.80.139:80                 HEALTHY     OK                outbound|80||ingress-nginx-controller.kube-router.svc.cluster.local
172.25.80.139:443                HEALTHY     OK                outbound|443||ingress-nginx-controller.kube-router.svc.cluster.local
172.25.80.139:5685               HEALTHY     OK                outbound|5685||ingress-nginx-controller.kube-router.svc.cluster.local
172.25.80.139:10254              HEALTHY     OK                outbound|10254||ingress-nginx-controller.kube-router.svc.cluster.local
172.25.80.213:15443              HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
172.25.80.213:15443              HEALTHY     OK                outbound|80||sleep.sample.svc.cluster.local
172.25.80.213:15443              HEALTHY     OK                outbound|9080|v2|review.sample.global
172.25.80.213:15443              HEALTHY     OK                outbound|9080|v2|reviews.sample.svc.cluster.local
172.25.80.213:15443              HEALTHY     OK                outbound|9080|v3|review.sample.global
172.25.80.213:15443              HEALTHY     OK                outbound|9080|v3|reviews.sample.svc.cluster.local
172.25.80.213:15443              HEALTHY     OK                outbound|9080||ratings.sample.svc.cluster.local
172.25.80.213:15443              HEALTHY     OK                outbound|9080||review.sample.global
172.25.80.213:15443              HEALTHY     OK                outbound|9080||reviews.sample.svc.cluster.local
unix://./etc/istio/proxy/SDS     HEALTHY     OK                sds-grpc
unix://./etc/istio/proxy/XDS     HEALTHY     OK                xds-grpc
```
