### ISSUE TITLE
Unable to remove prometheus

### ISSUE THREAD

**Issue by haani-niyaz** [istio/istio#37059]
### Bug Description

I have instio installed and wish to remove the default Prometheus installation (this was prior to it being an add-on option).

I attempted to remove Prometheus by disabling it in the operator CRD:

```
addonComponents:
    prometheus:
      enabled: false
      k8s:
        replicaCount: 0 
```

Although this disables it in the CRD, it does not change the `replicaCount` nor does it uninstall it.

I also attempted to set it via the helm pass through option but it errors:

`unknown field "prometheus" in v1alpha1.Values`

Set as per:

https://istio.io/v1.5/docs/reference/config/installation-options/#prometheus-options

```
values:
....
    prometheus:
      enabled: false 
```

### Version

```prose
client version: 1.12.1
control plane version: 1.12.1
```

### Additional Information

Similar issue was raised #25231 but it as auto closed.
