### ISSUE TITLE
OutboundTrafficPolicy to REGISTRY_ONLY doesn't appear to work in 1.10.3 version

### ISSUE THREAD

**Issue by praseed44** [istio/istio#37065]
### Bug Description

Hi,

In Istio 1.10.3, setting the **OutboundTrafficPolicy** to **_REGISTRY_ONLY_** doesn't appear to take effect as it is not blocking external traffic. I can still do curl requests to external sites within the cluster succesfully. However, the configmap **istio-1-10-3** is updated in istio-system with this configuration. Please note that, we followed the istio operator installation method.

Please let me know if there are any other configurations that we should consider updating to block all external traffic out of service registry scope.

### Version

```prose
istioctl version
client version: 1.10.3
control plane version: 1.10.3
data plane version: 1.10.3 (9 proxies)
-------------------------------
kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.13", GitCommit:"2444b3347a2c45eb965b182fb836e1f51dc61b70", GitTreeState:"clean", BuildDate:"2021-11-18T00:11:26Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

### Additional Information

[bug-report.tar.gz](https://github.com/istio/istio/files/7957963/bug-report.tar.gz)

**Comment by praseed44** [comment]
[bug-report.tar.gz](https://github.com/istio/istio/files/7957959/bug-report.tar.gz)

**Comment by bianpengyuan** [comment]
Is the workload you are curling from injected with `1-10-3` revision?

**Comment by praseed44** [comment]
> Is the workload you are curling from injected with `1-10-3` revision?

@bianpengyuan Yes, the workload is injected with 1.10.3 envoy proxy. Still it is connecting to external domains.

**Comment by bianpengyuan** [comment]
I am mainly wondering if it is injected with 1-10-3 revision. since that is the configmap name suggests `istio-1-10-3`. It should be reflected in the pod spec.

**Comment by praseed44** [comment]
> I am mainly wondering if it is injected with 1-10-3 revision. since that is the configmap name suggests `istio-1-10-3`. It should be reflected in the pod spec.

@bianpengyuan  I have attached the pod description of the workload from where the curl was tried. It has 1.10.3 sidecar container. Please let me know if you notice any discrepancy.

**Comment by bianpengyuan** [comment]
Ok that looks good to me. Can you collect envoy access log for the curl request? https://istio.io/v1.10/docs/tasks/observability/logs/access-log/

**Comment by bianpengyuan** [comment]
Also have you tried restarting istiod pod? Does that fix the issue?

**Comment by praseed44** [comment]
> Also have you tried restarting istiod pod? Does that fix the issue?

Restarting istiod pods didn't make any difference. Interestingly I am not able to see access logs for my curl requests in the pod. Access log is enabled in the mesh config and the ingress gateway logs are printing access logs in the same cluster. I am checking this further.

**Comment by rhrazdil** [comment]
Hello @bianpengyuan @praseed44 , I'm experiencing the same issue as is described here, but in my case, until istio version 1.11.7 the external traffic is blocked, when Sidecar CR setting outboundTrafficPolicy with REGISTRY_ONLY is present in the namespace.

My scenario is the following:
I have two workloads, server and a client, the server serves simple http service and client requests the service via istio-ingressgateway by using the following command:
```
(10.101.162.196 is IP of istio-ingressgateway service) 
$ curl -sD - -o /dev/null -Hhost:vmi-server.example.com http://10.101.162.196
HTTP/1.1 200 OK
```
The client has istio-proxy sidecar and the server doesn't have istio-proxy sidecar.


```
DestionationRule:
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: vmi-server-dr
spec:
  host: vmi-server
  subsets:
  - labels:
      version: v1
    name: v1
    
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vmi-server-vs
spec:
  gateways:
  - vmi-server-gw
  hosts:
  - vmi-server.example.com
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: vmi-server
        port:
          number: 4200
        subset: v1


apiVersion: networking.istio.io/v1beta1
kind: Gateway
  name: vmi-server-gw
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - vmi-server.example.com
    port:
      name: http
      number: 80
      protocol: HTTP
      
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: registry-only-sidecar
spec:
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY
      
Service for the server:
apiVersion: v1
kind: Service
metadata:
  name: vmi-server
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 4200
    protocol: TCP
    targetPort: 4200
  selector:
    app: vmi-server-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

Service for the client:
apiVersion: v1
kind: Service
metadata:
  name: istio-vmi-app-service
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 1500
    protocol: TCP
    targetPort: 1500
  selector:
    app: istio-vmi-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

```


Istio-proxy logs on the client that runs the request, I see records showing allow_any
```
[2022-03-08T11:36:32.752Z] "GET / HTTP/1.1" 200 - via_upstream - "-" 0 12 1 1 "-" "curl/7.42.1" "05e02332-320d-96bb-b439-c8ed18a3b73b" "vmi-server.example.com" "10.101.162.196:80" PassthroughCluster 10.244.196.162:54674 10.101.162.196:80 10.0.2.2:53628 - allow_any
[2022-03-08T11:36:33.040Z] "GET / HTTP/1.1" 200 - via_upstream - "-" 0 12 1 1 "-" "curl/7.42.1" "249c0f30-b0c6-90ae-b534-4e1f20e0d9b4" "vmi-server.example.com" "10.101.162.196:80" PassthroughCluster 10.244.196.162:54674 10.101.162.196:80 10.0.2.2:53630 - allow_any
```
Which IIUC should not be the case with the Sidecar setting OutboundTrafficPolicy to REGISTRY_ONLY and no explicit ServiceEntry allowing the host.

Thanks in advance for looking over the case, let me know what else I could provide
