### ISSUE TITLE
Several DNS requests are sent even if dnsRefreshRate is set to a high value

### ISSUE THREAD

**Issue by marcozov** [istio/istio#37066]
### Bug Description

According to [Istio / Global Mesh Options](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/?_ga=2.32501118.1324415355.1643368327-1482015949.1628501590), the dnsRefreshRate parameter defines how often envoy clusters (of type STRICT_DNS) are being resolved through DNS requests.

If I run a tcpdump on my dns server, I see a lot of traffic:
```
tcpdump -ni peth1 port 53 | grep www.facebook.com
18:58:59.540100 IP 10.236.146.5.46362 > 10.236.145.7.53: 23926+ [1au] A? www.facebook.com. (45)
18:58:59.540122 IP 10.236.146.5.44876 > 10.236.145.7.53: Flags [P.], seq 2905:2952, ack 24375, win 501, options [nop,nop,TS val 3554228951 ecr 1983605167], length 47 40847+ [1au] A? www.facebook.com. (45)
18:58:59.540187 IP 10.236.146.5.46181 > 10.236.145.7.53: Flags [P.], seq 735:782, ack 5296, win 501, options [nop,nop,TS val 3554228951 ecr 1983604806], length 47 57343+ [1au] A? www.facebook.com. (45)
18:58:59.540226 IP 10.236.146.6.26366 > 10.236.145.7.53: 26016+ [1au] A? www.facebook.com. (45)
18:58:59.540226 IP 10.236.146.6.43796 > 10.236.145.7.53: 23109+ [1au] A? www.facebook.com. (45)
18:58:59.540277 IP 10.236.146.6.19700 > 10.236.145.7.53: Flags [P.], seq 172:219, ack 1096, win 501, options [nop,nop,TS val 2720788871 ecr 1071096917], length 47 32613+ [1au] A? www.facebook.com. (45)
18:58:59.540363 IP 10.236.146.6.7628 > 10.236.145.7.53: 33688+ [1au] A? www.facebook.com. (45)
18:58:59.540564 IP 10.236.146.6.44727 > 10.236.145.7.53: 15602+ [1au] A? www.facebook.com. (45)
18:58:59.540841 IP 10.236.146.5.54333 > 10.236.145.7.53: Flags [P.], seq 1783:1830, ack 12746, win 501, options [nop,nop,TS val 3554228952 ecr 1983601338], length 47 54160+ [1au] A? www.facebook.com. (45)
18:58:59.540951 IP 10.236.146.5.31854 > 10.236.145.7.53: 15062+ [1au] A? www.facebook.com. (45)
...
...
```
I see many blocks like this one (with even more dns packets), and I see them roughly every 30 seconds.
This happened with default dnsRefreshRate, but it also happens after setting this parameter to 60s or 600s.

Now, I would expect some DNS requests like these, because I setup a ServiceEntry for www.facebook.com:
```
kubectl get serviceentry -n istio-system facebook -o yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: facebook
  namespace: istio-system
spec:
  hosts:
  - www.facebook.com
  location: MESH_EXTERNAL
  ports:
  - name: tls-service
    number: 443
    protocol: TLS
  resolution: DNS
```
This is because to reach external domains from my cluster, I want all the traffic to be redirected to an egress gateway (so I have corresponding Gateway / VirtualService / DestinationRule resources. I'm not sure how relevant they are, but I provide the full yaml configurations and the reasoning behind the setup in the `Additional Information` section).
I also saw some recommendation that suggested to use STATIC resolution instad of DNS, but my goal would be to rely on DNS resolution so that I can avoid binding www.facebook.com (or any other domain) to one or more IP addresses.

I’m wondering how I can debug this further: dnsRefreshRate seems to be an envoy configuration, so I tried to look at any pod’s istio sidecar logs, and I see entries like this:
```
2021-09-29T17:21:29.340766Z	debug	envoy upstream	DNS refresh rate reset for www.facebook.com, refresh rate 30000 ms
```
I also see them for other domains that I configure just like www.facebook.com, but the refresh rate seems to change (sometimes it’s 5000ms, sometimes it’s 1000ms).
What is going on here? Are all the pods with istio sidecar deployed trying to resolve www.facebook.com every X seconds? Is this influenced by the dnsRefreshRate parameter? If yes: why don’t I see any difference when I set different dnsRefreshRate values? If no: where is my understanding about this wrong?

Any suggestion would be appreciated, as I’m a bit blind in debugging this. Thank you.

### Version

```prose
istioctl version
client version: 1.10.1
control plane version: 1.12.1
data plane version: 1.12.1 (502 proxies), 1.11.3 (12 proxies)

But the same problem happened with version 1.9.x
```

### Additional Information

Here are more details about the whole setup, including the yaml configurations of all the involved components.

We use the istio operator to configure istio. This is the part relevant for the egress gateway.
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  finalizers:
  - istio-finalizer.install.istio.io
  name: istiocontrolplane
  namespace: istio-system
spec:
  components:
    egressGateways:
...
    - enabled: true
      k8s:
        hpaSpec:
          maxReplicas: 30
          minReplicas: 2
        service:
          ports:
          - name: tls
            port: 443
            targetPort: 8443
          - name: tls-2
            port: 8444
            targetPort: 8444
          - name: tls-3
            port: 8445
            targetPort: 8445
      label:
        app: istio-egressgateway-tls
        istio: istio-egressgateway-tls
      name: istio-egressgateway-tls
...
  meshConfig:
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      tracing:
        sampling: 10
        zipkin:
          address: jaeger-collector-headless.observability:9411
    dnsRefreshRate: 600s
    extensionProviders:
    - envoyExtAuthzHttp:
        headersToDownstreamOnDeny:
        - content-type
        - set-cookie
        headersToUpstreamOnAllow:
        - authorization
        - path
        - x-auth-request-user
        - x-auth-request-email
        - x-auth-request-access-token
        includeHeadersInCheck:
        - authorization
        - cookie
        port: "80"
        service: oauth2-proxy.auth.svc.cluster.local
      name: oauth2-proxy
  profile: default
  values:
    global:
      proxy:
        autoInject: enabled
        privileged: true
```

Then, we a Gateway resource:
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: egress-gw-tls-facebook
  namespace: istio-system
spec:
  selector:
    istio: istio-egressgateway-tls
  servers:
    - hosts:
        - www.facebook.com
      port:
        name: tls
        number: 443
        protocol: TLS
      tls:
        mode: ISTIO_MUTUAL
```

A DestinationRule:
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: facebook
  namespace: istio-system
spec:
  host: istio-egressgateway-tls.istio-system.svc.cluster.local
  subsets:
    - name: facebook-subset
      trafficPolicy:
        loadBalancer:
          simple: ROUND_ROBIN
        tls:
          mode: ISTIO_MUTUAL
          sni: www.facebook.com
```

We have a VirtualService:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: facebook
  namespace: istio-system
spec:
  gateways:
    - mesh
    - istio-system/egress-gw-tls-facebook
  hosts:
    - www.facebook.com
  tcp:
    - match:
        - gateways:
            - istio-system/egress-gw-tls-facebook
          port: 443
      route:
        - destination:
            host: www.facebook.com
            port:
              number: 443
          weight: 100
  tls:
    - match:
        - gateways:
            - mesh
          port: 443
          sniHosts:
            - www.facebook.com
      route:
        - destination:
            host: istio-egressgateway-tls.istio-system.svc.cluster.local
            port:
              number: 443
            subset: facebook-subset
```

And an AuthorizationPolicy to allow all traffic coming from the $(ALLOWED_NAMESPACE) default service account:
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-access-facebook
  namespace: istio-system
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/$(ALLOWED_NAMESPACE)/sa/default
      to:
        - operation:
            ports:
              - '8443'
      when:
        - key: connection.sni
          values:
            - www.facebook.com
  selector:
    matchLabels:
      istio: istio-egressgateway-tls
```

Finally, we have the ServiceEntry shown in the bug report as well:
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: facebook
  namespace: istio-system
spec:
  hosts:
    - www.facebook.com
  location: MESH_EXTERNAL
  ports:
    - name: tls-service
      number: 443
      protocol: TLS
  resolution: DNS
```

The idea behind this setup is to be able to control egress TLS traffic, without doing termination / origination. So, at the end, the TLS traffic is encrypted in mTLS: the goal is to rely on the istio egress in order to decide who can access external domains, without touching the original TLS traffic. This concept works and it's not the scope of this github issue (but I still included it in order to provide more details). The problem relates to the amount of DNS requests that are sent: I see a lot of them for any domain that we reach with this approach and I can't find a way to control them.
