### ISSUE TITLE
Inconsistent VS behavior for unknown hosts

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#37087]
Case 1: 

No SE defined
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: route
  namespace: default
spec:
  hosts:
  - alpine.com
  - alpine2.com
  http:
  - route:
    - destination:
        host: alpine
```

behavior: match alpine.com and alpine2.com on port 80

Case 2:
No SE defined, add port match
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: route
  namespace: default
spec:
  hosts:
  - alpine.com
  - alpine2.com
  http:
  - route:
    - destination:
        host: alpine
    match:
    - port: 7070
```

behavior: never matches

Case 3:
Add SE, keep port match:
```yaml

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: route
  namespace: default
spec:
  hosts:
  - alpine.com
  - alpine2.com
  http:
  - route:
    - destination:
        host: alpine
    match:
    - port: 7070
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: dns
spec:
  hosts:
  - "alpine.com"
  addresses:
  - 1.2.3.4
  resolution: STATIC
  endpoints:
  - address: 1.2.3.5
  ports:
  - number: 7070
    name: http
    protocol: HTTP
```

behavior: match alpine.com, 1.2.3.4, or alpine2.com

Case 4:
Same as above, but split VS
```yaml

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: route
  namespace: default
spec:
  hosts:
  - alpine.com
  http:
  - route:
    - destination:
        host: alpine
    match:
    - port: 7070
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: route2
  namespace: default
spec:
  hosts:
  - alpine2.com
  http:
  - route:
    - destination:
        host: alpine
    match:
    - port: 7070
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: dns
spec:
  hosts:
  - "alpine.com"
  addresses:
  - 1.2.3.4
  resolution: STATIC
  endpoints:
  - address: 1.2.3.5
  ports:
  - number: 7070
    name: http
    protocol: HTTP
```

Behavior: only match alpine.com or 1.2.3.4
---

This is a clear bug to me, IMO. Having multiple hostnames defined in a single VS should be equivalent to having multiple VS with a single hostname
