### ISSUE TITLE
Workloads across clusters which belong to two different trust domain rejects connection

### ISSUE THREAD

**Issue by sudeeptoroy** [istio/istio#37096]
### Bug Description

This issue is similar as #31987, in fact i am receiving a similar OPENSSL error (I have seen PADDING_CHECK_FAILED, TLSV1_ALERT_DECRYPT_ERROR when i run envoy in trace mode).

Here is my setup. 
istio version: 1.11.5

I have followed the instructions as mentioned in the link below to bring multi cluster setup
https://istio.io/latest/docs/setup/install/multicluster/primary-remote_multi-network/
with the below changes:
1. I have created two roots, one for cluster 1 and another for cluster 2. These are installed as "cacerts" to their respective cluster. to create the cert i have used the below command (tools are a part of istio code-base).
make ../tools/certs/Makefile.selfsigned.mk root-ca
make ../tools/certs/Makefile.selfsigned.mk cluster1-cacerts
in another folder
make ../tools/certs/Makefile.selfsigned.mk root-ca
make ../tools/certs/Makefile.selfsigned.mk cluster2-cacerts

2. As i have used helm, so while installing istiod i configured mesh config parameters:
ex:

for Cluster 1:

```yaml
pilot:
  env:
    ISTIO_MULTIROOT_MESH: true
meshConfig:
  trustDomain: "cluster1.example.com"
  trustDomainAliases:
    - "cluster2.example.com"
  caCertificates:
    - pem: |
           < root ca for cluster 2>
```

for cluster 2:

```yaml
pilot:
  env:
    ISTIO_MULTIROOT_MESH: true
meshConfig:
  trustDomain: "cluster2.example.com"
  trustDomainAliases:
    - "cluster1.example.com"
  caCertificates:
    - pem: |
           < root ca for cluster 1>
```

---

I have a front-end service which is calling back-end. Back-end service resides on both the clusters.
From the front-end service when i try to connect the back-end; i receive a success when front-end connects to the back-end belonging to the same cluster. If i delete cluster's local back-end service, i receive SSL error from the back-end service belonging to the other cluster.
Before deleting the back-end service when i exec into the front-end service, i can see envoy has discovered both the back-end endpoints correctly. 
When i exec into the back-end service on the other cluster and take a config_dump i see the identity cert has 4 certificates as below.

 workload cert                       << correct
 intermediate cert                  << correct
 cluster root cert                    << correct
 cluster root cert repeated     <<<<<<< not sure why rootca is repeated. i was expecting to see rootca from the other cluster.

rest of the envoy configuration seems fine. 

do you know if I am missing any configuration here or any clues on how to proceed on this?

### Version

```prose
1.11.5
```
