### ISSUE TITLE
EnvoyFilter for Cluster match is not applied

### ISSUE THREAD

**Issue by SantiMunoz** [istio/istio#37107]
### Bug Description

Hello, I'm trying to implement a TLS termination in the sidecar side for outbound connections to a specific service through an EnvoyFilter but it's not applied.

My idea is to use HTTPS to call another service within the mesh, but still use mTLS between proxies. For example the `ServiceA` will query `https://service-b.service.consul`, this will resolve to `service-b.default` and the request should still use mTLS between sidecars. It would look something like:

ServiceA --(HTTPS)-->(TLS termination)ServiceAproxy(initiates mTLS)--(mTLS)-->ServiceBproxy--(plain text)-->ServiceB

The EnvoyFilter I'm trying to use is the following:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: custom-envoy-filter
spec:
  configPatches:
    - applyTo: CLUSTER
      match:
        cluster:
          name: "outbound|443||service-b.service.consul"
        context: SIDECAR_OUTBOUND
      patch:
        operation: INSERT_FIRST
        value:
          transport_socket:
            name: "envoy.transport_sockets.tls"
            typed_config:
              "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext"
              common_tls_context:
                tls_certificates:
                  - certificate_chain:
                      filename: /etc/certs/consul-external/tls.crt
                    private_key:
                      filename: /etc/certs/consul-external/tls.key
                validation_context:
                  trusted_ca:
                    filename: /etc/certs/ca/ca.crt
```
But I'm getting the following error from the istio proxy logs:
```
warning	envoy config	gRPC config for type.googleapis.com/envoy.config.cluster.v3.Cluster rejected: Proto constraint validation failed (ClusterValidationError.Name: value length must be at least 1 characters): transport_socket {
  name: "envoy.transport_sockets.tls"
  typed_config {
    [type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext] {
      common_tls_context {
        tls_certificates {
          certificate_chain {
            filename: "/etc/certs/consul-external/tls.crt"
          }
          private_key {
            filename: "/etc/certs/consul-external/tls.key"
          }
        }
        validation_context {
          trusted_ca {
            filename: "/etc/certs/ca/ca.crt"
          }
        }
      }
    }
  }
}
```
And I can't see it applied in the clusters config:
```
~ istioctl proxy-config cluster netutils-bd8c7fbd-kjvmb.default --fqdn service-b.service.consul -o json
[
    {
        "name": "outbound|443||service-b.service.consul",
        "type": "STRICT_DNS",
        "connectTimeout": "10s",
        "loadAssignment": {
            "clusterName": "outbound|443||service-b.service.consul",
            "endpoints": [
                {
                    "locality": {},
                    "lbEndpoints": [
                        {
                            "endpoint": {
                                "address": {
                                    "socketAddress": {
                                        "address": "service-b.default",
                                        "portValue": 443
                                    }
                                }
                            },
                            "metadata": {
                                "filterMetadata": {
                                    "istio": {
                                        "workload": ";;;;Kubernetes"
                                    }
                                }
                            },
                            "loadBalancingWeight": 1
                        }
                    ],
                    "loadBalancingWeight": 1
                }
            ]
        },
        "circuitBreakers": {
            "thresholds": [
                {
                    "maxConnections": 4294967295,
                    "maxPendingRequests": 4294967295,
                    "maxRequests": 4294967295,
                    "maxRetries": 4294967295,
                    "trackRemaining": true
                }
            ]
        },
        "dnsRefreshRate": "5s",
        "respectDnsTtl": true,
        "dnsLookupFamily": "V4_ONLY",
        "commonLbConfig": {
            "localityWeightedLbConfig": {}
        },
        "transportSocket": {
            "name": "envoy.transport_sockets.tls",
            "typedConfig": {
                "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext",
                "commonTlsContext": {
                    "tlsCertificateSdsSecretConfigs": [
                        {
                            "name": "default",
                            "sdsConfig": {
                                "apiConfigSource": {
                                    "apiType": "GRPC",
                                    "transportApiVersion": "V3",
                                    "grpcServices": [
                                        {
                                            "envoyGrpc": {
                                                "clusterName": "sds-grpc"
                                            }
                                        }
                                    ],
                                    "setNodeOnFirstMessageOnly": true
                                },
                                "initialFetchTimeout": "0s",
                                "resourceApiVersion": "V3"
                            }
                        }
                    ],
                    "combinedValidationContext": {
                        "defaultValidationContext": {
                            "matchSubjectAltNames": [
                                {
                                    "exact": "spiffe://cluster.local/ns/default/sa/service-b"
                                }
                            ]
                        },
                        "validationContextSdsSecretConfig": {
                            "name": "ROOTCA",
                            "sdsConfig": {
                                "apiConfigSource": {
                                    "apiType": "GRPC",
                                    "transportApiVersion": "V3",
                                    "grpcServices": [
                                        {
                                            "envoyGrpc": {
                                                "clusterName": "sds-grpc"
                                            }
                                        }
                                    ],
                                    "setNodeOnFirstMessageOnly": true
                                },
                                "initialFetchTimeout": "0s",
                                "resourceApiVersion": "V3"
                            }
                        }
                    },
                    "alpnProtocols": [
                        "istio-peer-exchange",
                        "istio"
                    ]
                },
                "sni": "outbound_.443_._.service-b.service.consul"
            }
        },
        "metadata": {
            "filterMetadata": {
                "istio": {
                    "config": "/apis/networking.istio.io/v1alpha3/namespaces/default/destination-rule/service-b",
                    "default_original_port": 443,
                    "services": [
                        {
                            "host": "service-b.service.consul",
                            "name": "service-b.service.consul",
                            "namespace": "default"
                        }
                    ]
                }
            }
        },
        "filters": [
            {
                "name": "istio.metadata_exchange",
                "typedConfig": {
                    "@type": "type.googleapis.com/envoy.tcp.metadataexchange.config.MetadataExchange",
                    "protocol": "istio-peer-exchange"
                }
            }
        ]
    }
]
```

I would also like to point out that the EnvoyFilter [documentation](https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-ClusterMatch) mention `ClusterMatch` but it actually doesn't exists in the EnvoyFilter template in `v1alpha3`.

### Version

```prose
$ istioctl version
client version: 1.12.2
control plane version: 1.12.1

$ kubectl version --short
Client Version: v1.20.1
Server Version: v1.20.14
```

### Affected product area

- [X] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by howardjohn** [comment]
Rejected configs do not show up in the config dump

On the ClusterMatch - the left column (name) is what you want for yaml, the ClusterMatch name is the proto/go type (https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-EnvoyConfigObjectMatch)

**Comment by SantiMunoz** [comment]
Oh my bad regarding the documentation, now makes more sense!

Do you have any insight on the error related to the cluster match  `ClusterValidationError.Name: value length must be at least 1 characters` ?
From the documentation I can't identify any missing field.

**Comment by howardjohn** [comment]
Pretty cryptic error but I think I see what is going on.

You are doing an insertion of a clsuter with spec
```yaml
          transport_socket:
            name: "envoy.transport_sockets.tls"
            typed_config:
              "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext"
              common_tls_context:
                tls_certificates:
                  - certificate_chain:
                      filename: /etc/certs/consul-external/tls.crt
                    private_key:
                      filename: /etc/certs/consul-external/tls.key
                validation_context:
                  trusted_ca:
                    filename: /etc/certs/ca/ca.crt
```

That is not a full cluster config - it only has the transport_socket. So its missing `name` (and I am sure plenty of other fields - that is just the first error).

Maybe you want MERGE instead of INSERT?

**Comment by SantiMunoz** [comment]
Thanks for the reply @howardjohn, 
With the merge we don't see any error or warning when applying it, but the configuration doesn't get applied.
The dump of the cluster config is the same as the original I posted in the first post. 
Is it possible that the `transport_sockets.tls.v3.DownstreamTlsContext` is not compatible with a cluster configuration and we need to implement it in another layer?

We already tried using `FILTER_CHAIN` and it worked if we filtered by the port 443, but did nothing when we added the `sni` filter in it, the change is not applied in the config and we don't see any error in the logs.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: custom-envoy-filter
spec:
  configPatches:
    - applyTo: FILTER_CHAIN
      match:
        context: SIDECAR_OUTBOUND
        listener:
          portNumber: 443
          filterChain:
            sni: "service-b.service.consul"
      patch:
        operation: MERGE
        value:
          transport_socket:
            name: "envoy.transport_sockets.tls"
            typed_config:
              "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext"
              common_tls_context:
                tls_certificates:
                  - certificate_chain:
                      filename: /etc/certs/consul-external/tls.crt
                    private_key:
                      filename: /etc/certs/consul-external/tls.key
                validation_context:
                  trusted_ca:
                    filename: /etc/certs/ca/ca.crt
```

Applying it only with `portNumber: 443` works for any outbound HTTPS request, but the side effect is that terminates any TLS connection and affects any HTTPS connection.

Our goal was to only terminate it for traffic that was internal to the mesh so the proxies could use mTLS.

**Comment by SantiMunoz** [comment]
Hello, 
I've finally found the solution for this setup. 
From one hand the `DownstreamTlsContext` is not compatible with the `CLUSTER` config, so I finally used the `FILTER_CHAIN`.
The SNI filter wasn't working because the listeners didn't have this information, so I had to create a `VirtualService` in order to define the SNI for that host and then I could use it in the `EnvoyFilter` to match the listener I was interested in.

Find the final configuration below

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service-b-test
spec:
  hosts:
  - "service-b.service.consul"
  tls:
    - match:
      - port: 443
        sniHosts:
          - service-b.service.consul
      route:
        - destination:
            host: service-b.default.svc.cluster.local
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: custom-envoy-filter
  namespace: istio-system  # root namespace in order to apply it in all the namespaces
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/component: microservice
  configPatches:
    - applyTo: FILTER_CHAIN
      match:
        context: SIDECAR_OUTBOUND
        listener:
          portNumber: 443
          filterChain:
            sni: "service-b.service.consul"
      patch:
        operation: MERGE
        value:
          transport_socket:
            name: "envoy.transport_sockets.tls"
            typed_config:
              "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext"
              common_tls_context:
                tls_certificates:
                  - certificate_chain:
                      filename: /etc/certs/consul-external/tls.crt
                    private_key:
                      filename: /etc/certs/consul-external/tls.key
                validation_context:
                  trusted_ca:
                    filename: /etc/certs/ca/ca.crt

```
