### ISSUE TITLE
Overload manager bootstrap EnvoyFilter fails due to missing proto

### ISSUE THREAD

**Issue by dobriensq** [istio/istio#37110]
### Bug Description

I'm attempting to enable some overload_manager configuration on an egress gateway by using an `EnvoyFilter` applied to the bootstrap and enabling `BOOTSTRAP_XDS_AGENT`. When I do so, I get the following error in the `istio-proxy` startup:

```
{"level":"error","time":"2022-02-01T23:12:28.986848Z","msg":"failed to write updated envoy bootstrap: failed to marshal bootstrap as JSON: proto: not found"}
```

It appears to be caused by the `resource_monitors` definition because removing it gets past the marshaling but fails due to an invalid configuration since its missing the resource monitors definition. This is the `EnvoyFilter`:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: egress-overload-manager
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: egressgateway
  configPatches:
  - applyTo: BOOTSTRAP
    patch:
      operation: MERGE
      value:
        overload_manager:
          actions:
          - name: envoy.overload_actions.shrink_heap
            triggers:
            - name: envoy.resource_monitors.fixed_heap
              threshold:
                value: 0.7
          - name: envoy.overload_actions.stop_accepting_requests
            triggers:
            - name: envoy.resource_monitors.fixed_heap
              threshold:
                value: 0.85
          - name: envoy.overload_actions.stop_accepting_requests
            triggers:
            - name: envoy.resource_monitors.fixed_heap
              threshold:
                value: 0.9
          - name: envoy.overload_actions.stop_accepting_connections
            triggers:
            - name: envoy.resource_monitors.fixed_heap
              threshold:
                value: 0.9
          refresh_interval: 1s
          resource_monitors:
          - name: envoy.resource_monitors.fixed_heap
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.resource_monitors.fixed_heap.v3.FixedHeapConfig
              max_heap_size_bytes: 1073741824.0
``` 

### Version

```prose
$ istioctl version
client version: 1.11.4
control plane version: 1.12.2
data plane version: 1.11.3 (3 proxies), 1.12.2 (73 proxies), 1.11.4 (62 proxies)
$ kubectl version --short
Client Version: v1.22.4
Server Version: v1.20.11-eks-f17b81
```
