### ISSUE TITLE
[AuthorizationPolicy] Rule not working when path exists. 

### ISSUE THREAD

**Issue by philschmid** [istio/istio#37123]
### Bug Description

Hello, I am trying to use `RequestAuthentication` and `AuthorizationPolicy` to secure my API. 
This works perfectly fine with the following policy.
```yaml
...
  action: ALLOW
  rules:
    - to:
      - operation:
          paths: ["/*"]
      when:
      - key: request.auth.claims[iss]
        values: ["company"]
```
But when i try to add "whitelist" for paths which i don't need JWT validation I encountered an unexpected and wrong behavior. 
When adding an additional rule or replacing the existing rule with 
```yaml
...
  action: ALLOW
  rules:
    - to:
      - operation:
          paths: ["/v1/*"]
```
My Assumption is that every path starting with `/v1/*` will be allowed, which is not the case. I have a virtual service with a path exposed at `/v1/test`, which works without authentication and authorization perfectly fine. 
But when having the policy in place and sending a request i get a `403` Forbidden. 
![Bildschirmfoto 2022-02-02 um 15 28 50](https://user-images.githubusercontent.com/32632186/152174793-9ab4291b-aa9a-42c1-9da7-3a98c398dcc4.png)
In addition to this when i change my request URL from `/v1/test` to `/v1/a` or `/v1/test2` i ll get a `404` Not found error, which means istio successfully authorizes the request but couldn't find a route which makes sense. 

### Version

```prose
$ istioctl version             
client version: 1.12.2
control plane version: 1.12.0
data plane version: 1.12.0 (3 proxies)
$ kubectl version --short
Client Version: v1.23.1
Server Version: v1.21.5-eks-bc4871b
```
