### ISSUE TITLE
[help wanted] REQ_WITHOUT_QUERY got rejected by envoy.config.listener: Not supported filed in StreamInfo: REQ_WITHOUT_QUERY(X-ENVOY-ORIGINAL-PATH?:PATH)

### ISSUE THREAD

**Issue by cnjohnniekwok** [istio/istio#37130]
I have upgraded my Istio to v1.12.2 to use the `%REQ_WITHOUT_QUERY(X?Y):Z%` log operator to replace the `%REQ(X?Y):Z%` in the `accessLogFormat` under `meshConfig` inside `features.yaml`. However, I got the following error from ingress gateway pod:

> 2022-02-01T19:53:47.753500Z warning envoy config gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_8443: Not supported field in StreamInfo: REQ_WITHOUT_QUERY(X-ENVOY-ORIGINAL-PATH?:PATH)

I also tried to create an `EnvoyFilter` to specify the envoy formatter extension for requestWithoutQuery(), but that does no effect at all (I don't even know if this is the right approach). Is there any prerequisite steps I need to do in order to use `REQ_WITHOUT_QUERY` without being reject by the envoy listener?

```
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: access-log-req-without-query
  namespace: istio-system
spec:
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: ANY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
            access_log:
              - name: fileaccesslog
                path: /dev/stdout
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                log_format:
                  textFormat: |
                    [%START_TIME%] "%REQ(:METHOD)% %REQ_WITHOUT_QUERY(X?Y):Z% %PROTOCOL%" 
                  formatters:
                    - name: envoy.formatter.req_without_query
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.formatter.req_without_query.v3.ReqWithoutQuery
```
