### ISSUE TITLE
Cross network egress gateway cannot use SNI for routing

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#37134]
Say we are doing TLS routing through egress gw like:
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-server-sds
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: server
    trafficPolicy:
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: ISTIO_MUTUAL
          sni: external.{{.ServerNamespace}}.svc.cluster.local
```

This works perfectly fine in single network. Once another network is added it breaks since the SNI breaks the eastwest gateway traversal.

This makes sense - mostly opening this issue to link for motivation for skipping a test
