### ISSUE TITLE
Support terminating HTTPS on Sidecar's IstioEgressListener

### ISSUE THREAD

**Issue by l8huang** [istio/istio#37160]
**Describe the feature request**

Currently when a port's protocol is set to `HTTPS` in ServiceEntry, for example:

```
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: httpbin
spec:
  hosts:
  - httpbin.example.com
  location: MESH_INTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: STATIC
  workloadSelector:
    labels:
      app: httpbin

```

Istio generates a outbound listener which does SNI match and passthrough request to outbound cluster:

```
$ istioctl pc l ...
ADDRESS PORT  MATCH                     DESTINATION
0.0.0.0 443   ALL                       PassthroughCluster
0.0.0.0 443   SNI: httpbin.exmpale.com     Cluster: outbound|443||httpbin.example.com
```

We have a use case which requires to terminate HTTPS traffic on sidecar's outbound listener; after that, from sidecar to egress gateway the traffic will be encrypted with Istio Mutual TLS. This is mainly for migrating legacy applications into Istio service mesh -- these legacy applications are using HTTPS, it's not practical to make them switching from HTTPS to HTTP during migration(the long-term target is switching to HTTP). The purpose is making the required HTTP-related capabilities being available on sidecar and egress gateway: metrics, tracing, header manipulation, authn/authz, etc.

Gateway API has ServerTLSSettings for TLS termination, so a basic idea is adding a similar but simplified server TLS setting to Sidecar's IstioEgressListener. Please kindly let me know if I misunderstand  anything.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[X] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
