### ISSUE TITLE
How to disable istio retry

### ISSUE THREAD

**Issue by vivuu1989** [istio/istio#37181]
We are using Istio 1.11.2 and facing some issue with istio retry 

Inorder to disable the automatic retry, we added the following block in object in the http list. However istio still retries requests .

    apiVersion: networking.istio.io/v1beta1
    kind: VirtualService
    metadata:
      name: gateway
      namespace: development
    spec:
      gateways:
      - development/ingressgw
      hosts:
      - gateway.dev.rtm.com
      http:
      - match:
        - uri:
            prefix: /
        retries:
          attempts: 0
        route:
        - destination:
            host: gateway.development.svc.cluster.local
            port:
              number: 443

**Comment by vivuu1989** [comment]
Any suggections please

**Comment by zirain** [comment]
@vivuu1989 this cfg looks good
How do you get this conclusion `However istio still retries requests?`

**Comment by vivuu1989** [comment]
Because from app insight traces we could understand that the retry attempt is again happening after getting the 503 error when it called the backend service

**Comment by zirain** [comment]
> development

your gateway name `ingressgw` with namespace `development`?

**Comment by zirain** [comment]
BTW, you can add `"%REQ(X-ENVOY-ATTEMPT-COUNT)%"` in `MeshConfig.AccessLogFormat` and verify with envoy access log.

**Comment by vivuu1989** [comment]
any solution or workaround for this?

**Comment by zirain** [comment]
seems related to https://github.com/istio/istio/pull/35506, can you verify this with v1.12 or v1.13?

**Comment by vivuu1989** [comment]
We are usi g istio 1.11.2 only. Is there any workaround to disable the retry only for 503 from istio side

**Comment by zirain** [comment]
try to reproduce but failed, everything works as expected.

```
root@ecs-istiodev:~/GoProjects/src/istio.io/istio# /root/istioctl version
client version: 1.11.2
control plane version: 1.11.2
data plane version: 1.11.2 (4 proxies)
```

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpbin
  namespace: default
spec:
  gateways:
  - httpbin-gateway
  hosts:
  - '*'
  http:
  - retries:
      attempts: 0
    route:
    - destination:
        host: httpbin
        port:
          number: 8000
```
```console
root@ecs-istiodev:~/GoProjects/src/istio.io/istio# /root/istioctl pc all istio-ingressgateway-5d76fcbfc9-dt67j -nistio-system  -oyaml | grep num_retries -C 5
root@ecs-istiodev:~/GoProjects/src/istio.io/istio# k edit vs 
# change attempts to 2
virtualservice.networking.istio.io/httpbin edited
root@ecs-istiodev:~/GoProjects/src/istio.io/istio# /root/istioctl pc all istio-ingressgateway-5d76fcbfc9-dt67j -nistio-system  -oyaml | grep num_retries -C 5
          route:
            cluster: outbound|8000||httpbin.default.svc.cluster.local
            max_grpc_timeout: 0s
            retry_policy:
              host_selection_retry_max_attempts: "5"
              num_retries: 2
              retriable_status_codes:
              - 503
              retry_host_predicate:
              - name: envoy.retry_host_predicates.previous_hosts
              retry_on: connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes
```

**Comment by vivuu1989** [comment]
I performed atesting again with the sample againand this time I tried with attempt count 5. but still there is no change is happening to the retries, still showing 2. Is there any way to change the property of status codes or headers to disable, so that istio wont retry ? 

`apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: myservice
  namespace: mynamespace
spec:
  gateways:
  - istio-system/ingress-gateway
  hosts:
  - myservice.mynamespace.svc.cluster.local
  - myservice.mycompany.com
  http:
  - match:
    - uri:
        prefix: /
    retries:
      attempts: 5
    route:
    - destination:
        host: myservice.mynamespace.svc.cluster.local
        port:
          number: 8080
        subset: v1
`

this is the  proxy config routing rule out put which generated from my app. 

```
                "routes": [
                    {
                        "name": "default",
                        "match": {
                            "prefix": "/"
                        },
                        "route": {
                            "cluster": "outbound|8080||myservice.mynamespace.svc.cluster.local",
                            "timeout": "0s",
                            "retryPolicy": {
                                "retryOn": "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes",
                                "numRetries": 2,
                                "retryHostPredicate": [
                                    {
                                        "name": "envoy.retry_host_predicates.previous_hosts"
                                    }
                                ],
                                "hostSelectionRetryMaxAttempts": "5",
                                "retriableStatusCodes": [
                                    503
                                ]
                            },
                            "maxStreamDuration": {
                                "maxStreamDuration": "0s",
                                "grpcTimeoutHeaderMax": "0s"
                            }
                        },
                        "decorator": {
                            "operation": "myservice.mynamespace.svc.cluster.local:8080/*"
                        }
                    }
                ],
                "includeRequestAttemptCount": true
```

**Comment by zirain** [comment]
can you try 
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: appservice-B
  namespace: mynamespace
spec:
  gateways:
  - mesh
  - istio-system/ingress-gateway
  hosts:
  - appservice-B.mynamespace.svc.cluster.local
  - appservice-B.mycompany.com
  http:
  - match:
    - uri:
        prefix: /
    retries:
      attempts: 0
    route:
    - destination:
        host: appservice-B.mynamespace.svc.cluster.local
        port:
          number: 8080
        subset: v1
```

**Comment by zirain** [comment]
https://github.com/istio/api/blob/ab2ad4a576138488d6f95f82e727c97a1b61cc9e/networking/v1alpha3/virtual_service.pb.go#L1565

you can try config like following:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: appservice-B
  namespace: mynamespace
spec:
  gateways:
  - mesh
  - istio-system/ingress-gateway
  hosts:
  - appservice-B.mynamespace.svc.cluster.local
  - appservice-B.mycompany.com
  http:
  - match:
    - uri:
        prefix: /
      gateways: # if this's nil, it will use spec.gateways
      - istio-system/ingress-gateway
    retries:
      attempts: 2 # traffic from ingressgatway will retry
    route:
    - destination:
        host: appservice-B.mynamespace.svc.cluster.local
        port:
          number: 8080
        subset: v1
  - match:
    - uri:
        prefix: /
      gateways:
      - mesh
    retries:
      attempts: 0 # traffic from other pod inside mesh will not retry
    route:
    - destination:
        host: appservice-B.mynamespace.svc.cluster.local
        port:
          number: 8080
        subset: v1
```
