### ISSUE TITLE
RequestAuthentication doesn't get distributed to envoy proxy in namespace

### ISSUE THREAD

**Issue by dan1el-k** [istio/istio#37221]
### Bug Description

RequestAuthentication objects don't get distributed to Envoy proxies in service namespace.
However the same RequestAuthentication definition works, when deployed in the service-mesh namespace and on the ingress-gateway.

So,

**Doesn't work:**
```yaml
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: oauth2-nginx
  namespace: service-a
spec:
  selector:
    matchLabels:
      app: nginx
  jwtRules:
  - issuer: https://dex.apps.my-base-url
    jwksUri: http://dex.dex.svc.cluster.local:5556/keys
```
**works:**
```yaml
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: oauth2-nginx
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
  - issuer: https://dex.apps.my-base-url
    jwksUri: http://dex.dex.svc.cluster.local:5556/keys
```
I checked already the Envoy Proxy trace logs, and see that the "jwt_authn" rules are not filled in the envoy in the service-a namespace. On the ingressgateway, where the things are working its of course filled.

A VirtualService, or AuthorizationPolicy however are working correctly in the "service-a" namespace with selector.
There is no PeerAuthentication, nor any DestinationRule deployed in "service-a" namespace, just a VirtualService, DestinationRule and the AuthenticationRequest object.

In Kiali the whole configuration looks also good.
I am running out of ideas. Istioctl also doesn't support an option to check authentication settings.

Does anybody has an idea or can help here ?

### Version

```prose
client version: 1.11.6
control plane version: OSSM_2.1.1-1.el8
data plane version: 1.9.9 (4 proxies)

installed on 
OKD 4.9
Kubernetes 1.22
with Openshift Service Mesh Operator
```

**Comment by r00ta** [comment]
I had the same issue.

**Comment by r00ta** [comment]
Reopen this?

**Comment by dan1el-k** [comment]
Actually, I found out meanwhile what was the root cause of it.
It was my `service` object, which was not compliant to Istio obviously..

```
kind: Service
apiVersion: v1
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
    - name: http-ui
      port: 8080
      targetPort: 8080
      **appProtocol: http**
  selector:
    app: nginx
```

The problematic, part were 2 params
- `appProtocol` param. I somehow took it over from one example.
- `name`. This needs to be 'http' in order to work. tcp is not supported for requestAuthentication
- 
The requestAuthentication was just working, after removing the `appProtocol` param and renaming the port with pattern `http-<something>`

Very nasty, as there were no info or hint, neither a documentation about this rules somewhere that the `service  object causes` has some specific requirements. Also the istioctl and kiali were silent about this.

So hopefully the error handling could be improved and make istio a bit less sensitive to such problems.
