### ISSUE TITLE
Istio ingress helm chart is missing container ports

### ISSUE THREAD

**Issue by FogDong** [istio/istio#37232]
### Bug Description

Use helm chart to install istio ingress, the deployment's container ports are like:

```yaml
spec:
      containers:
      - image: auto
        imagePullPolicy: Always
        name: istio-proxy
        ports:
        - containerPort: 15090
          name: http-envoy-prom
          protocol: TCP
```

Use istioctl to install istio ingress, the deployment's container ports are like:

```yaml
        name: istio-proxy
        ports:
        - containerPort: 15021
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 31400
          protocol: TCP
        - containerPort: 15443
          protocol: TCP
        - containerPort: 15090
          name: http-envoy-prom
          protocol: TCP
```
Are these charts still under maintenance?

### Version

```prose
$ istioctl version
client version: 1.12.2
control plane version: 1.12.2
data plane version: 1.12.2 (2 proxies)
```
