### ISSUE TITLE
can not access https site

### ISSUE THREAD

**Issue by hillbun** [istio/istio#37289]
### Bug Description

I setup gateway for https website

But when visit, I get errors:

Chrome: ERR_CONNECTION_CLOSED
Firefox: PR_END_OF_FILE_ERROR

I create secret with same crt and key file on ingress nginx, it is ok both with Chrome and Firefox

```
openssl s_client -showcerts -connect xxx.xxxx.com:443
CONNECTED(00000005)
write:errno=104
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 324 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
```

### Version

```prose
istioctl version
client version: 1.11.2
control plane version: 1.11.2
data plane version: 1.11.2 (2 proxies)

kubectl version --short
Client Version: v1.20.7
Server Version: v1.20.7

helm version --short
v3.5.4+g1b5edb6
```

**Comment by hzxuzhonghu** [comment]
What's your config look like?

**Comment by hillbun** [comment]
```
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: istio-system
  name: istio-ingress-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 443
      name: https-xxx-com
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: xxx-tls-credential
    hosts:
    - xxx.xxx.com
```
