### ISSUE TITLE
Istio does not route outgoing HTTP if it is intended for ports 5983 or 5984

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#3729]
@esnible commented on [Fri Feb 23 2018](https://github.com/istio/issues/issues/227)

**Bug:** Y

**What Version of Istio and Kubernetes are you using**
Kubernetes v1.8.3+icp+ee
Kubernetes version 0.5.0
Sidecar version http://<istio-proxy>:15000/server_info reports "envoy 0/1.6.0-dev//DEBUG live 1922 1922 0"

**Is Istio Auth enabled or not ?** Y

**What happened**:
I deployed CouchDB with MutualTLS enabled.  My application containers could not reach Couch.  Eventually I realized that although Pilot knows about my CouchDB the sidecar did not.

**How to reproduce it:**
Let's not bother with installing and exposing CouchDB.  This can be demonstrated with just two Services and _curl_.  First, `kubectl apply` this file:

```
apiVersion: v1
kind: Service
metadata:
  name: ecs-easychair
  labels:
    micro: easychair
spec:
  type: ClusterIP
  ports:
  - port: 5985 # if this is 5984, it does not appear in http://<sidecar>:15000/routes
    targetPort: 5984
    protocol: TCP
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: ecs-couch
  labels:
    micro: couch
spec:
  type: ClusterIP
  ports:
  - port: 5984 # if this is 5984, it does not appear in http://<sidecar>:15000/routes
    targetPort: 5984
    protocol: TCP
    name: http
```

After deploying this, ssh into the istio-proxy of any bookinfo pod, and do `curl istio-pilot.istio-system:8080/v1/routes/5985/foo/sidecar~127.0.0.1~boz~bip` and `curl istio-pilot.istio-system:8080/v1/routes/5984/foo/sidecar~127.0.0.1~boz~bip` to verify that Pilot is aware of the services and they are equivalent.

Then do `curl localhost:15000/routes | grep 5985` and `curl localhost:15000/routes | grep 5984` and see that although the istio-proxy knows about 5985 it does not know about 5984.

I noticed that 5983 has a similar issue.
