### ISSUE TITLE
TLS routes are not matched to TLS gateway listener when ISTIO_MUTUAL mode is set

### ISSUE THREAD

**Issue by jewertow** [istio/istio#37293]
#### Background context
I try to create a TLS listener in the egress gateway with `ISTIO_MUTUAL` tls mode. The use case is to have a TCP proxy that forwards outbound traffic to external services, but still to use mTLS within the service mesh.

I apply the resources shown below, but then Istio logs `info    gateway omitting listener "0.0.0.0_8443" due to: must have more than 0 chains in listner "0.0.0.0_8443"`.

The problem is that TLS matching rules specified in virtual service are not matched to TLS server configured in egress gateway.
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: tls
      protocol: TLS
    hosts:
    - www.example.com
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: example-com-routing
spec:
  hosts:
  - www.example.com
  gateways:
  - istio-egressgateway
  tls:
  - match:
    - gateways:
      - istio-egressgateway
      port: 443
      sniHosts:
      - www.example.com
    route:
    - destination:
        host: www.example.com
        port:
          number: 443
```

#### Details

I looked at the code base and I think that I found a bug. There is a function [buildGatewayTCPBasedFilterChains](https://github.com/istio/istio/blob/3c3905e8e904d1913e0b12e841d6feceb41a19e7/pilot/pkg/networking/core/v1alpha3/gateway.go#L188) responsible for creating gateway listener and its filter chains. Its implementation calls function [createGatewayTCPFilterChainOpts](https://github.com/istio/istio/blob/3c3905e8e904d1913e0b12e841d6feceb41a19e7/pilot/pkg/networking/core/v1alpha3/gateway.go#L678) when server is listening on TLS. But this function [creates filter chain from TCP routes](https://github.com/istio/istio/blob/3c3905e8e904d1913e0b12e841d6feceb41a19e7/pilot/pkg/networking/core/v1alpha3/gateway.go#L700), **so none of TLS routes are matched**.

A workaround is to apply virtual service with TCP matching rules and it works, but it's no longer possible to perform SNI-based routing.
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: example-com-routing
spec:
  hosts:
  - www.example.com
  gateways:
  - istio-egressgateway
  tcp:
  - match:
    - gateways:
      - istio-egressgateway
      port: 443
      # sniHosts:
      # - www.example.com
    route:
    - destination:
        host: www.example.com
        port:
          number: 443
```

#### Suggested solution
Function [createGatewayTCPFilterChainOpts](https://github.com/istio/istio/blob/3c3905e8e904d1913e0b12e841d6feceb41a19e7/pilot/pkg/networking/core/v1alpha3/gateway.go#L678) needs another condition in the existing if-statement for case where a server has TLS port and tls mode is not `PASSTHROUGH`.
If you agree with me, I could fix it.

If this is by design, a proper validation must be added.

### Version

```prose
Istio: 1.12.1
Kubernetes: 1.21.1
```
