### ISSUE TITLE
Certificate Challenges failing with Istio + Istio Gateway when installed via Helm

### ISSUE THREAD

**Issue by ChrisJBurns** [istio/istio#37329]
### Bug Description

I have installed Istio on Azure AKS via Helm and Flux. (base, istiod, gateway)

I am currently trying to migrate to Istio Gateway for exposes our applications to the outside world. Currently we do this via Nginx Ingress Controller (and works fine), but when using Istio Gateway we are getting problems when trying to create Certificates for our sub domains.

My scenario is that I'm currently trying to create a `Certificate` for the a Concourse url e.g. `concourse-istio1.tooling.domain.com`. (`-istio1` is just to test a cert gets created and I can access the URL, I will be switching to a more better named domain when I know this all works)

Without getting into the details of creating Istio Gateways I am following [this guide](https://istio.io/latest/docs/ops/integrations/certmanager) and by the time I even get to the `Gateway` part, I can see that the Challenge created doesn't work due to error.
```
Waiting for HTTP-01 challenge propagation: failed to perform self check GET request 'http://concourse-istio1.tooling.domain.com/.well-known/acme-challenge/gW6Ky1oqRmLvAzUw....
```

Now, I've read a tonne on people having these problems, and they recommended putting general gateways in front of it, which I've done via this

```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: general-gateway
  namespace: istio-system
  labels:
    app: gateway
spec:
  selector:
    istio: gateway
  servers:
    - port:
        number: 80
        protocol: HTTP
        name: http
      hosts:
        - "*"
```

And got to a point where the error I got was `waiting for http-01 challenge propagation: wrong status code '404', expected '200'`

I then read more and people described that I had to add a `VirtualService` that took that `challenge` verification and directed it to the `acme-solver-xxxx` like so:

```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: http-redirect
  namespace: istio-system
spec:
  gateways:
  - general-gateway
  hosts:
  - '*'
  http:
    - match:
        - uri:
            prefix: /.well-known/acme-challenge/ 
      route:
        - destination:
            port:
              number: 8089
            host: cm-acme-http-solver-nvcvc.istio-system.svc.cluster.local
```

Which is a terrible solution for automation as we're expected to know the pod name ahead of time meaning manual intervention (and we want all of this to be done automatically). But the error I get from this is `waiting for http-01 challenge propagation: wrong status code 503 expected '200` which I'm assuming is down to some mTLS setting. But again, I don't understand how and why I'm expected to do all of this routing? Especially when the Istio Guide on Cert-manager doesn't include any of the above. I've also read many many examples of multiple people doing multiple things and I've tried many combinations and just cannot get it to work. Many of which are examples on old versions of Istio where stuff like `global.k8sIngress.enabled` aren't even options anymore as I'm using the newer `istio/gateway` Helm chart. 

Issuer yaml for brevity alongside the certificate.

#### Certificate
```yaml
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: concourse-ingress-cert
  namespace: istio-system
spec:
  secretName: concourse-ingress-cert
  dnsNames:
  - concourse-istio1.domain.com
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
    group: cert-manager.io
```

#### Issuer
```yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: istio-system
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: blah.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      # An empty 'selector' means that this solver matches all domains
      - selector: {}
        http01:
          ingress:
            class: istio
```

And IngressClass because apparently I read somewhere I needed it as the old `ingress.class` annotation is being deprecated.

#### IngressClass
```yaml
---
apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
  name: istio
  namespace: istio-system
spec:
  controller: istio.io/ingress-controller
```

#### Cert-manager HelmRelease
```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: cert-manager
spec:
  interval: 1m
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
  interval: 1m
  values:
    version: v1.7.1
    installCRDs: true
```

Not sure why all of this is getting superfluous, I'm hoping it's a simple thing to do, but at the moment, it seems that there's a lack of documentation on this, (something I'm happy to add - but I need to get it working first) especially in an area that seems to attract so many issues.

#### EDIT:
I will add the Flux config for how I'm installing Istio, in case there is a config variable I am missing.

#### HelmRelease for IstioBase and IstioD
```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: istio-system
  namespace: istio-system
spec:
  interval: 1m
  timeout: 2m0s
  url: https://istio-release.storage.googleapis.com/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  chart:
    spec:
      chart: base
      version: 1.12.2
      sourceRef:
        kind: HelmRepository
        name: istio-system
  interval: 1m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  chart:
    spec:
      chart: istiod
      version: 1.12.2
      sourceRef:
        kind: HelmRepository
        name: istio-system
  interval: 1m
```

#### HelmRelease for Istio Gateway (Ingress)
```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-gateway
  namespace: istio-system
spec:
  chart:
    spec:
      chart: gateway
      version: 1.12.2
      sourceRef:
        kind: HelmRepository
        name: istio-system
  interval: 1m
  values:
    service: 
      loadBalancerIP: [our Azure AKS LB Public IP]
```

### Version

```prose
> istioctl version                              
client version: 1.12.2
control plane version: 1.12.2
data plane version: 1.12.2 (32 proxies)

> kubectl version --short                       
Client Version: v1.21.4
Server Version: v1.21.9
```

**Comment by howardjohn** [comment]
Are you on the latest cert-manager patch release? My understand is this was broken and they reverted the change that made it break.

On the flip side, if Istio implemented https://github.com/istio/istio/issues/36971 this would also just work, even with the "broken" cert-manager versions

**Comment by ChrisJBurns** [comment]
Hi Howard, thanks for the quick response.

I've added my HelmRelease for the `cert-manager` installation. As of yesterday I am using `1.7.1`

**Comment by howardjohn** [comment]
When its initial failing, do you have any other virtual services or Gateways?

They should not be required - but its possible you have created one that conflicts with what cert-manager is doing.

**Comment by ChrisJBurns** [comment]
Nope, no additional Gateways - removed them all. I have also just tried this which I saw you add on #20589 and I get the same `404` error on the challenge that I pasted in the issue description.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: http-redirect
  namespace: concourse
spec:
  gateways:
  - https-redirect
  hosts:
  - 'concourse-istio1.domain.com'
  http:
  - redirect:
      scheme: https
      redirectCode: 302
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: https-redirect
  namespace: istio-system
spec:
  selector:
    istio: gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "concourse-istio1.domain.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: https
  namespace: istio-system
spec:
  selector:
    istio: gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "concourse-istio1.domain.com"
    tls:
      credentialName: concourse-ingress-cert
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: concourse-virtualservice
  namespace: concourse
spec:
  hosts:
  - "concourse-istio1.domain.com"
  gateways:
  - https
  http:
  - route:
    - destination:
        host: concourse-web
        port:
          number: 80
```

**Comment by howardjohn** [comment]
if you can do `istioctl pc all INGRESS_POD_NAME -oyaml` and attach it, during the challenge (when Ingress is still there), it could help figure out why we get 404s. I would remove all the extra VS/GWs before doing this to keep things simply.

The workaround above should only be needed if you had `httpsRedirect: true` on a gateway

**Comment by howardjohn** [comment]
sorry run it on the istio-ingressgateway pod, not the solver

**Comment by ChrisJBurns** [comment]
Also, is it expected to have a istio sidecar injected to the solver pod? I've seen that in a few other threads and just wanted to double check if that was also something that was supposed to be happening? As the solver pod is in the `istio-system` namespace I would assume that would be a no

**Comment by irbekrm** [comment]
> Basically I would expect that from your Issuer, cert-manager creates an Ingress with class: istio. Istio reads that, configures the GW, and everything is happy. No other config needed

Not sure if it's related, but in v1.7 cert-manager is again using the `kubernetes.io/ingress.class` annotation not the `ingressClassName` field (see [cert-manager#4537](https://github.com/cert-manager/cert-manager/issues/4537)).

So the `Ingress` that cert-manager creates to forward traffic to the solver pod will have the annotation and not the field.

I am not very familiar with Istio ingress controller implementation and the associated custom resources, but tried to create an `Issuer` and `Certificate` like in the issue description (without a `Gateway`). With cert-manager v1.7 and Istio v1.12.2 I observed that Istio ingress controller does pick up the cert-manager's created `Ingress` (saw `Ingresse`'s status being updated by `pilot-discovery` and the cert got issued as expected). Also tried with an `IngressClass` resource being deployed (I believe that's no longer needed when we now use the annotation?), that too seemed to work.

> Especially when the Istio Guide on Cert-manager doesn't include any of the above

Could be useful to create a more detailed tutorial on how to use cert-manager with Istio

**Comment by ChrisJBurns** [comment]
@irbekrm  Are you using Nginx ingress controller or the Istio Gateway?

I've also noticed that the solver pod itself doesn't have the annotation `kubernetes.io/ingress.class: istio`, but the solver ingress service does.

**Comment by irbekrm** [comment]
> @irbekrm Are you using Nginx ingress controller or the Istio Gateway?

istio ingress-gateway controller with a `Gateway`

> I've also noticed that the solver pod itself doesn't have the annotation kubernetes.io/ingress.class: istio, but the solver ingress service does.

Yes, it should the `Ingress` that should have the annotation, not the pod as you already noticed. I typed the previous comment too quickly :)

**Comment by ChrisJBurns** [comment]
Yep, so it seems we both have the same setup. My Istio Gateway is being configured with the public IP of the LB that is assignment to my AKS cluster (the same setup that we had with the Nginx Ingress Controller).

So just sitrep then:
- my Istio Gateway is installed created and assigned public IP
- `cert-manager` is installed (successfully as far as I can see) at v1.7.1
- no `Gateway` is created yet here are the route config dumps.
   ```
- virtualHosts:
  - domains:
    - '*'
    name: backend
    routes:
    - match:
        prefix: /healthz/ready
      route:
        cluster: agent
- virtualHosts:
  - domains:
    - '*'
    name: backend
    routes:
    - match:
        prefix: /stats/prometheus
      route:
        cluster: prometheus_stats
```
- I add the issuer in the issue description
- I add the certificate in the issue description
- I see a `certificate`, `certificaterequest`, `order` and `challenge` is created
- the solver ingress service and solver pod are created (svc being annotated with istio ingress class)
- expecting all to be golden but get the `Waiting for HTTP-01 challenge propagation: failed to perform self check GET request ...` error as mentioned in the issue description.

**Comment by ChrisJBurns** [comment]
Have edited issue to include how we are installing Istio incase there are some missing configuration options I am not using that I should be

**Comment by ChrisJBurns** [comment]
Ok, so I think I _may_ have got somewhere. I realised that I didn't annotate the `cert-manager` namespace with `istio-injection: enabled`, so when it was trying to make requests to the solver, it didn't understand where to do. With the `cert-manager` pods all being stood up with a `istio-proxy` sidecar, I now get a different error which is `Waiting for HTTP-01 challenge propagation: wrong status code '503', expected '200'`. I got it above also, but I've currently not got any `Gateway` resources defined. 

Is this correct? Am I now missing something else?

**Comment by irbekrm** [comment]
> Yep, so it seems we both have the same setup. My Istio Gateway is being configured with the public IP of the LB that is assignment to my AKS cluster (the same setup that we had with the Nginx Ingress Controller). It's worth mentioning that we only have the one public IP, I'm assuming this won't be a problem?

I have the same setup, but on GKE and haven't enabled sidecar injection on any of the namespaces.
I don't think there should be a need to enable sidecar injection for cert-manager to solve the challenge, but might be wrong.

In case of self-check the flow of requests could be something like cert-manager-controller-pod -> your-load-balancer -> cert-manager-created-ingress -> cert-manager-created-solver-service -> cert-manager-created-solver-pod (someone who knows Istio ingress better could correct me if the middle part is not correct).
You could check if you can access the challenge URL from outside the cluster?
Also whether the cert-manager created Ingress has been picked up by Istio ingressgateway, in my case I see
```
status:
  loadBalancer:
    ingress:
    - ip: <my-load-balancer-ip>
```
on the ingress.

**Comment by ChrisJBurns** [comment]
I can't access the challenge URL from outside the cluster which kind of makes sense as my `cert-manager` solver ingress has an empty status with no `loadBalancer` config. So the Ingress isn't being assigned the public lb IP.

**Comment by ChrisJBurns** [comment]
Out of curiosity @irbekrm how did you install Istio onto your cluster? Did you do it via Helm or the `istioctl`? I'm wondering if the helm charts aren't doing something right. I've just removed Istio from cluster completely and started again and I still have issues

**Comment by irbekrm** [comment]
> Out of curiosity @irbekrm <https://github.com/irbekrm> how did you
install Istio onto your cluster? Did you do it via Helm or the istioctl?
I'm wondering if the helm charts aren't doing something right. I've just
removed Istio from cluster completely and started again and I still have
issues

I just ran `istioctl install` (with istioctl version `1.12.2`)

**Comment by ChrisJBurns** [comment]
I'll try installing with `istioctl` and see if it makes a difference,

**Comment by ChrisJBurns** [comment]
Ok, so, for test purposes, I've completely stripped down the cluster to nothing so that only `flux` is left.

I've installed Istio with `istioctl` via `istioctl install --set profile=default` instead of using the Flux HelmReleases described above and I can confirm that when adding the `cert-manager` HelmRelease, the `Issuer` resource and the `Certificate` that are in the issue description, it all works and the certificate is created successfully. I did see a brief propagation error in the `challenge`, but that quickly disappeared - which I'm assuming was when Istio picked up the ingress.

I'm going to remove all of the above and go back to barebones cluster again with just Flux. I am then going to attempt it all again, but this time installing via `Helm` (without flux) and using a different domain in the cert as this one has already been created to see if that works. If it doesn't work then I can safely assume there is either something wrong with the `helm` chart installation, or there is a configuration option I am not including that the `istioctl` does with the `default` profile. If it does work, then I can only conclude that Flux is the problem.

**Comment by ChrisJBurns** [comment]
So it seems that there is a problem with the Istio installation with Helm.

When [following the Istio Guides](https://istio.io/latest/docs/setup/install/helm/) on installing Istio and Gateway with Helm

I do the following:
- `kubectl create namespace istio-system`
- ` helm install istio-base istio/base -n istio-system`
- `helm install istiod istio/istiod -n istio-system --wait`
- `helm install istio-ingress istio/gateway -n istio-system --wait --set service.loadBalancerIP=[OUR PUBLIC LB IP]`

I wait for all to be installed.

I then install `cert-manager` the same way as I did in the previous step (through the `cert-manager` HelmRelease), I also add the `Issuer` the same way, as well as the `Certificate` under a new domain (just bumped up the `istio1` -> `istio2` like so: `concourse-istio2.tooling.domain.com`, and I am back to the challenge error as before (`Waiting for HTTP-01 challenge propagation: failed to perform self check GET request ...`).

@howardjohn  What's your thoughts on this? Do you identify something I am not doing correctly with regards to the Helm installation of Istio in comparison to what the `istioctl` does? Or is the above enough for a deeper look at what the Helm installation is doing wrong (or not doing in this case)?

**Comment by howardjohn** [comment]
Ahhh I think I know what is going on.. thanks for digging into this so much.

Basically for Ingress there is just one class ("Istio"). But there may be
multiple deployments of gateway service/deployment in the cluster, so Istio
needs to know which one should serve Ingress traffic. cert-manager uses
Ingress (although they are working on more native support).

How that is configured is
https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig
ingressService
and ingressSelector. The default istioctl gateway install aligns with the
mesh config default settings, but not when installing through helm that way.

**Comment by ChrisJBurns** [comment]
Thanks for that @howardjohn, with regards to the Helm install, is there a meshConfig value I need to add when doing a Helm install? And would it be on the `base`, `istiod` or `gateway` installation?

**Comment by ChrisJBurns** [comment]
Can confirm have got it to work with `Helm` by adding the following `meshConfig` settings in the `istiod` Helm installation:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  chart:
    spec:
      chart: istiod
      version: 1.12.2
      sourceRef:
        kind: HelmRepository
        name: istio-system
  interval: 1m
  values:
    meshConfig:
      ingressService: istio-gateway
      ingressSelector: gateway
```

A bit confusing as when I did a `helm show values` on the `istiod` chart, I couldn't see those values at all available. I had to find https://github.com/istio/istio/issues/36444 in order to know how to update the `meshConfig`.

I will try and connect it up to a running concourse service and will report back if I can access via Chrome.
