### ISSUE TITLE
Simplify TLS configuration on sidecar proxy

### ISSUE THREAD

**Issue by shriramsharma** [istio/istio#37330]
The current implementation of a recent feature of [enabling TLS on sidecar proxy](https://github.com/istio/istio/pull/36210) seems to be a little complicated since we are required to disable `mTLS` on the app's port. See the example below.

If `PeerAuthentication` is not configured and with the default mode `PERMISSIVE`, istiod would create listeners allowing plaintext and istio in-mesh mTLS with spiffe certs. 
When enabling TLS on the sidecar proxy with user-provided certs, the requirement of the feature was to not allow any plaintext traffic. 
One way to fix this would be to remove the plaintext listener but doing so would give an incorrect impression to the mesh client as the mode itself is set to `PERMISSIVE`. 
Plus this gets further convoluted with the mode set to `STRICT`.

I wanted to create this issue so that we can start a discussion on this and come to a conclusion on how we can simplify this configuration. 

```
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
    service: httpbin
spec:
  ports:
  - name: https
    port: 8443
    targetPort: 80
  selector:
    app: httpbin
---

apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: httpbin
  namespace: app1
spec:
  workloadSelector:
    labels:
      app: httpbin
  ingress:
    - port:
        number: 80
        name: http
        protocol: HTTPS
      defaultEndpoint: 127.0.0.1:80
      tls:
        mode: SIMPLE
        privateKey: "/etc/certs/tls.key"
        serverCertificate: "/etc/certs/tls.crt"
---

apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: httpbin-pa
  namespace: app1
spec:
  selector:
    matchLabels:
      app: httpbin
  mtls:
    mode: STRICT
  portLevelMtls:
    80:
      mode: DISABLE

```

**Comment by hzxuzhonghu** [comment]
Ingress tls mode and pa tls mode seems confusing, and have conflict.

PA is to control istio mtls, should not be set at all if ingress tls has been set

**Comment by howardjohn** [comment]
We need to decide if we want mTLS _or_ TLS, or to support mTLS _and_ TLS

**Comment by kfaseela** [comment]
mTLS "or" TLS on the same port, "without" the need of explicit peerAuth disable would be good enough(if that is easier to achieve)

**Comment by hzxuzhonghu** [comment]
Looks we can support mtls and tls simultaneously, one for outsidecar access and one for inner mesh access.

The later filter chain match with

```
             "applicationProtocols": [
                        "istio",
                        "istio-peer-exchange",
                        "istio-http/1.0",
                        "istio-http/1.1",
                        "istio-h2"
                    ]
```

**Comment by hzxuzhonghu** [comment]
Doing this will bring some change to  permissive mode.

**Comment by shriramsharma** [comment]
@kfaseela @howardjohn @hzxuzhonghu  ... Here are some proposals we came up with.

cc: @aattuluri 

### Solution 1:
Honor `PeerAuthentication` only for mTLS auth.
If the sidecar config has TLS mode set to `SIMPLE` , then all we do is we make sure we remove the plaintext listener for that port only even if the `PeerAuthentication` is set to `PERMISSIVE` or `DISABLE`.

If the sidecar config has TLS mode set to `MUTUAL`

 a. and if PA  is set to STRICT, then we allow both user mTLS and istio mTLS. We would use ALPN to find the listener match.
 
 b. and if PA is set to PERMISSIVE, then we allow plaintext, user mTLS and istio mTLS
 
 c. and if PA is set to DISABLE, then we only allow plaintext and the mTLS setting on the sidecar is ignored.

Since PeerAuthentication is supposed to control mTLS communication within the mesh, we should not even consider it when it comes to one-way TLS. With this proposal, we can probably extend it control mTLS communication ingressing from outside the mesh.

#### Pros:
1. We remove the need for `PeerAuthentication` configuration for one-way TLS. Makes the configuration reletaively simple.

#### Cons:
1. We still need to create/update PeerAuth configurations in order to enable this feature for mTLS.


### Solution 2:
Add another mode called `EXTERNAL_TLS`. We use this setting to primarily drive the user provided TLS or mTLS configuration certificate overrides on the Sidecar object.

Example:

```
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: httpbin
  namespace: app1
spec:
  workloadSelector:
    labels:
      app: httpbin
  ingress:
    - port:
        number: 80
        name: http
        protocol: HTTPS
      defaultEndpoint: 127.0.0.1:80
      tls:
        mode: SIMPLE
        privateKey: "/etc/certs/tls.key"
        serverCertificate: "/etc/certs/tls.crt"
---

apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: httpbin-pa
  namespace: app1
spec:
  selector:
    matchLabels:
      app: httpbin
  mtls:
    mode: STRICT
  portLevelMtls:
    80:
      mode: EXTERNAL_TLS
```

#### Pros:
1. This explicit mode (`EXTERNAL_TLS`) is more intuitive than setting to `DISABLED`.

#### Cons:
1. We still need to create/update two separate configurations in order to enable this feature.
2. Will need to add additional validations to make sure both the configurations are set correctly.

### Solution 3:
Move the TLS configuration from the Sidecar IstioIngressListener API to PeerAuthentication. Even though this approach is not backwards compatible, this would eliminate the need for two separate config. 

Example:
```
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: httpbin-pa
  namespace: app1
spec:
  selector:
    matchLabels:
      app: httpbin
  mtls:
    mode: STRICT
  portLevelMtls:
    80:
      tls:
        mode: SIMPLE
        privateKey: "/etc/certs/tls.key"
        serverCertificate: "/etc/certs/tls.crt"
```
