### ISSUE TITLE
Perform TLS origination with an egress gateway get "SSL_routines:OPENSSL_internal:WRONG_VERSION_NUMBER" error?

### ISSUE THREAD

**Issue by song0071000** [istio/istio#37348]
### Bug Description

according to [the official document](https://istio.io/v1.11/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/#perform-tls-origination-with-an-egress-gateway)，i create the follow resource:

1 se

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: n126
  namespace: istio-ryanzhou
spec:
  hosts:
    - www.126.com
  ports:
    - number: 80
      name: http
      protocol: HTTP
    - number: 443
      name: https
      protocol: HTTPS
  resolution: DNS
```

2 gw&dr

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: n126-sidecar-gw
  namespace: istio-ryanzhou
spec:
  selector:
    app.kubernetes.io/name: default-egress
  servers: 
    - port:
        number: 80
        name: https-port-for-tls-origination
        protocol: HTTPS
      hosts:
        - www.126.com
      tls:
        mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: n126-sidecar-dr
  namespace: istio-ryanzhou
spec:
  host: default-egress.default.svc.cluster.local
  subsets:
    - name: n126
      trafficPolicy:
        loadBalancer:
          simple: ROUND_ROBIN
        portLevelSettings: 
          - port:
              number: 80
            tls: 
              mode: ISTIO_MUTUAL
              sni: www.126.com 
```

3、vs&dr

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: n126-egress-vs
  namespace: istio-ryanzhou
spec:
  hosts:
    - www.126.com
  gateways:
    - n126-sidecar-gw
    - mesh
  http:
    - match:
        - gateways: 
            - mesh
          port: 80
      route:
        - destination:
            host: default-egress.default.svc.cluster.local
            subset: n126
            port:
              number: 80
          weight: 100
    - match:
        - gateways:
            - n126-sidecar-gw 
          port: 80
      route:
        - destination:
            host: www.126.com
            port:
              number: 443
          weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: n126-egress-dr
  namespace: istio-ryanzhou
spec:
  host: www.126.com
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
      - port:
          number: 443
        tls:
          mode: SIMPLE
```

when i apply these resource to istio, i use curl to visit host(www.126.com), and get this errors:

{"authority":"www.126.com","bytes_received":"0","bytes_sent":"0","connection_termination_details":"-","downstream_local_address":"240.240.0.13:80","downstream_remote_address":"172.28.210.229:60282","duration":"162","method":"HEAD","path":"/","protocol":"HTTP/1.1","request_id":"eccb3967-96a8-9be1-8c0d-27f62796c35e","requested_server_name":"-","response_code":"503","response_code_details":"upstream_reset_before_response_started{connection_failure,TLS_error:_268435703:SSL_routines:OPENSSL_internal:WRONG_VERSION_NUMBER}","response_flags":"UF,URX","route_name":"-","start_time":"2022-02-15T13:35:56.061Z","upstream_cluster":"outbound|80|n126|default-egress.default.svc.cluster.local","upstream_host":"172.28.210.241:8080","upstream_local_address":"-","upstream_service_time":"-","upstream_transport_failure_reason":"TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER","user_agent":"curl/7.29.0","x_forwarded_for":"172.28.210.229"}

i know  a possible reason is the missing of pa. after i apply pa, the error still occurs。

```
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: istio-ryanzhou
spec:
  mtls:
    mode: PERMISSIVE
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
spec:
  mtls:
    mode: PERMISSIVE
```

is there something incorrect or configure that i have ignored?

thanks!

### Version

```prose
## ~ % istioctl version
client version: 1.11.4
control plane version: 1.11.4
data plane version: 1.11.4 (57 proxies)
## ~ % kubectl version --short
Client Version: v1.22.3
Server Version: v1.20.4-aliyun.1
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1
```

**Comment by song0071000** [comment]
> I think we will need configdump from the sidecar proxy and egressgateway for debugging. https://github.com/istio/istio/wiki/Troubleshooting-Istio#collecting-information-2

thanks for reply! i have dump config.
egressgateway: https://github.com/song0071000/yaml_config/blob/main/config_dump_egress.json
sidecar: https://github.com/song0071000/yaml_config/blob/main/config_dump_sidecar.json

**Comment by bianpengyuan** [comment]
Do you have other gateway also configures egressgateway 80 port or 8080 port?

**Comment by bianpengyuan** [comment]
Also any suspicious log from istiod?

**Comment by song0071000** [comment]
> Do you have other gateway also configures egressgateway 80 port or 8080 port?

yes, there have other gateways which also configure egressgateway. but they have different hosts.
such as
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: baidu-egress-gw
  namespace: rtc
spec:
  selector:
    app.kubernetes.io/name: default-egress
  servers:
    - port:
        number: 80
        name: gs-baidu-port
        protocol: HTTP
      hosts:
        - www.baidu.com
```

i found a message from istiod log:
2022-02-17T02:17:24.713486Z	info	model	skipping server on gateway n126-sidecar-gw port https-port-for-tls-origination.8080.HTTPS: conflict with existing server 8080.HTTPS

looks like port conflict？
