### ISSUE TITLE
VirtualService ignore any ports other than 80

### ISSUE THREAD

**Issue by Titof974** [istio/istio#37357]
I followed the tutorial to do mutual TLS origination for egress traffic, but rather than using an internal service I want to an external one. Everything works well when I tried to access to my external service with the port 80, but when I try to use another port to access to, istio refuse to do the mTLS origination and the request will passthrough the egress.

**_My working configuration for the port 80_**

The ServiceEntry
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: test-00
  namespace: default
spec:
  addresses:
  - 11.245.165.212/32
  endpoints:
  - address: 11.245.165.212
  hosts:
  - test-00.bipbip.us
  location: MESH_EXTERNAL
  ports:
  - name: https
    number: 8000
    protocol: HTTPS
  resolution: STATIC
```

The gateway:
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-egressgateway
  namespace: hey-service-mesh
spec:
  selector:
    istio: egressgateway
  servers:
  - hosts:
    - test-00.bipbip.us
    port:
      name: http
      number: 80
      protocol: HTTP
```

The Destination rule with the TLS secret:
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: mtls-test-00
  namespace: hey-service-mesh
spec:
  host:  test-00.bipbip.us
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 8000
      tls:
        credentialName: tls-bipbip-test-00
        mode: MUTUAL
        sni:  test-00.bipbip.us
```

The other destination rule to add visibility
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: egressgateway-test-00
  namespace: default
spec:
  host: istio-egressgateway.hey-service-mesh.svc.cluster.local
  subsets:
  - name: test-00
```

The virtualservice
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ext-test-00
  namespace: default
spec:
  gateways:
  - hey-service-mesh/istio-egressgateway
  - mesh
  hosts:
  -  test-00.bipbip.us
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: istio-egressgateway.hey-service-mesh.svc.cluster.local
        port:
          number: 80
        subset: test-00
      weight: 100
  - match:
    - gateways:
      - hey-service-mesh/istio-egressgateway
      port: 80
    route:
    - destination:
        host: test-00.bipbip.us
        port:
          number: 8000
      weight: 100
```

The curl request:
```
kubectl exec -it testcurl -- curl -vvv --request GET 'test-00.bipbip.us'
*   Trying 11.245.165.212:80...
* Connected to test-00.bipbip.us (11.245.165.212) port 80 (#0)
> GET / HTTP/1.1
> Host: test-00.bipbip.us
> User-Agent: curl/7.81.0-DEV
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< date: Tue, 15 Feb 2022 18:23:33 GMT
< x-envoy-upstream-service-time: 222
< server: envoy
< transfer-encoding: chunked
<
hello bipbip !
* Connection #0 to test-00.bipbip.us left intact

```

**_Now I tried to change the port to use the port 81 (I also tested with the port 8080)_**

First I edited the service of my egress to add the port 81.
```
  ports:
  - name: http-81
    port: 81
    protocol: TCP
    targetPort: 8081
  - name: http2
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
```

The edited gateway:
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-egressgateway
  namespace: hey-service-mesh
spec:
  selector:
    istio: egressgateway
  servers:
  - hosts:
    - test-00.bipbip.us
    port:
      name: http
      number: 81
      protocol: HTTP
```

The edited virtual service:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ext-test-00
  namespace: default
spec:
  gateways:
  - hey-service-mesh/istio-egressgateway
  - mesh
  hosts:
  -  test-00.bipbip.us
  http:
  - match:
    - gateways:
      - mesh
      port: 81
    route:
    - destination:
        host: istio-egressgateway.hey-service-mesh.svc.cluster.local
        port:
          number: 81
        subset: test-00
      weight: 100
  - match:
    - gateways:
      - hey-service-mesh/istio-egressgateway
      port: 81
    route:
    - destination:
        host: test-00.bipbip.us
        port:
          number: 8000
      weight: 100
```

Now the curl request fail:
```
kubectl exec -it testcurl -- curl -vvv --request GET 'test-00.bipbip.us:81'
*   Trying 11.245.165.212:81...
* Connected to test-00.bipbip.us (11.245.165.212) port 81 (#0)
> GET / HTTP/1.1
> Host: test-00.bipbip.us
> User-Agent: curl/7.81.0-DEV
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 503 Service Unavailable
< content-length: 91
< content-type: text/plain
< date: Tue, 15 Feb 2022 18:31:49 GMT
< server: envoy
<
* Connection #0 to host test-00.bipbip.us left intact
upstream connect error or disconnect/reset before headers. reset reason: connection failure
```

I don't understand why istio is not upgrading the request with mTLS here.

Additional debug logs:

istio proxy (with port 80)
```
"GET / HTTP/1.1" 200 - via_upstream - "-" 0 16 223 222 "-" "curl/7.81.0-DEV" "17971a99-9faa-9204-9bb3-85a46322373a" "test-00.bipbip.us" "192.168.207.5:8080" outbound|80|test-00|istio-egressgateway.hey-service-mesh.svc.cluster.local 192.168.69.223:52116 11.245.165.212:80 192.168.69.223:57932 - -
```

```
istio proxy (with port 81)
"GET / HTTP/1.1" 503 UF upstream_reset_before_response_started{connection_failure} - "-" 0 91 53 - "-" "curl/7.81.0-DEV" "7dcdbb52-21e9-999f-bbc5-3336d2c6d7d2" "test-00.bipbip.u:81" "10.245.165.212:81" PassthroughCluster - 11.245.165.212:81 192.168.69.223:41822 - allow_any
```

Logs from istioctl
```
{
        "name": "http.8181",
        "virtualHosts": [
            {
                "name": "test-00.bipbip.us:81",
                "domains": [
                    "test-00.bipbip.us",
                    "test-00.bipbip.us:*"
                ],
                "routes": [
                    {
                        "match": {
                            "prefix": "/",
                            "caseSensitive": true
                        },
                        "route": {
                            "cluster": "outbound|8000||test-00.bipbip.us",
                            "timeout": "0s",
                            "retryPolicy": {
                                "retryOn": "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes",
                                "numRetries": 2,
                                "retryHostPredicate": [
                                    {
                                        "name": "envoy.retry_host_predicates.previous_hosts"
                                    }
                                ],
                                "hostSelectionRetryMaxAttempts": "5",
                                "retriableStatusCodes": [
                                    503
                                ]
                            },
                            "maxGrpcTimeout": "0s"
                        },
                        "metadata": {
                            "filterMetadata": {
                                "istio": {
                                    "config": "/apis/networking.istio.io/v1alpha3/namespaces/default/virtual-service/ext-test-00"
                                }
                            }
                        },
                        "decorator": {
                            "operation": "test-00.bipbip.us:8000/*"
                        }
                    }
                ],
                "includeRequestAttemptCount": true
            }
        ],
        "validateClusters": false
    },
```

I don't know if it's a bug or if I have some missing configuration.

**Comment by bianpengyuan** [comment]
I think your service (i.e. test-00 ServiceEntry) has to have port defined in order to match VS on. 80 works because of some legacy reason: https://github.com/istio/istio/issues/33760

**Comment by Titof974** [comment]
Thanks @bianpengyuan, now everything works well , the right configuration is:
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: test-00
  namespace: default
spec:
  addresses:
  - 11.245.165.212/32
  endpoints:
  - address: 11.245.165.212
    ports:
      http-81: 8000
  hosts:
  - test-00.bipbip.us
  location: MESH_EXTERNAL
  ports:
  - name: http-81
    number: 81
    protocol: HTTP
  resolution: STATIC
```
