### ISSUE TITLE
Old service IP address present in Istio Proxy route config

### ISSUE THREAD

**Issue by JWT95** [istio/istio#37356]
## Overview

If I delete a service and then recreate it, the deleted IP address for the service is present in the list of domains in the Istio Proxy route config for the service but the new IP address is not present.

This means that requests directly to the service IP (i.e. requests with the service IP in the host header) are not handled correctly. In particular they fail if the mutual tls policy is STRICT as they go via the PassthroughCluster.

#### Services
```
$ kubectl get services -n app
NAME                                   TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                         AGE
alt-http-service                       ClusterIP      10.255.193.97   <none>        7001/TCP                        3s
internal-http                          ClusterIP      10.255.32.53    <none>        7001/TCP,8082/TCP,8083/TCP      52s
```

####  Istio-Proxy route config on a client pod for route "7001"
```yaml
      - version_info: 2022-02-15T15:48:46Z/44
        route_config:
          '@type': type.googleapis.com/envoy.config.route.v3.RouteConfiguration
          name: "7001"
          virtual_hosts:
           - name: allow_any
             ...
           - name: alt-http-service.app.svc.cluster.local:7001
              ...
           - name: internal-http.app.svc.cluster.local:7001
              domains:
                - internal-http.app.svc.cluster.local
                - internal-http.app.svc.cluster.local:7001
                - internal-http
                - internal-http:7001
                - internal-http.app.svc
                - internal-http.app.svc:7001
                - internal-http.app
                - internal-http.app:7001
                - 10.255.32.53
                - 10.255.32.53:7001
```
The Service IP address, `10.255.32.53`, is present in the list of domains

### After deleting the internal-http service

Service deleted by:
```
kl delete service internal-http -n app
```

#### Services
```
$ kubectl get services -n app
alt-http-service                       ClusterIP      10.255.193.97   <none>        7001/TCP                        7m28s
```

#### Istio-Proxy route config on a client pod for route "7001"
```yaml
      - version_info: 2022-02-15T15:55:56Z/45
        route_config:
          '@type': type.googleapis.com/envoy.config.route.v3.RouteConfiguration
          name: "7001"
          virtual_hosts:
            - name: allow_any
             ...
            - name: alt-http-service.app.svc.cluster.local:7001
             ...
```
The service has been removed from the route_config for route "7001"

### After recreating the internal-http service

The service is recreated by doing a Helm upgrade on the Helm release that installed it.

#### Services
```
$ kubectl get services -n app
NAME                                   TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                         AGE
alt-http-service                       ClusterIP      10.255.193.97   <none>        7001/TCP                        8m3s
internal-http                          ClusterIP      10.255.62.193   <none>        7001/TCP,8082/TCP,8083/TCP      5s
```

#### Istio-Proxy route config on a client pod for route "7001"
```
     - version_info: 2022-02-15T15:56:44Z/46
        route_config:
          '@type': type.googleapis.com/envoy.config.route.v3.RouteConfiguration
          name: "7001"
          virtual_hosts:
            - name: allow_any
              ...
            - name: alt-http-service.app.svc.cluster.local:7001
              ...
            - name: internal-http.app.svc.cluster.local:7001
              domains:
                - internal-http.app.svc.cluster.local
                - internal-http.app.svc.cluster.local:7001
                - internal-http
                - internal-http:7001
                - internal-http.app.svc
                - internal-http.app.svc:7001
                - internal-http.app
                - internal-http.app:7001
                - 10.255.32.53
                - 10.255.32.53:7001
```

The old service IP address, `10.255.32.53` is present in the list of domains but the new service IP address, `10.255.62.193`, is not. The version info timestamps show that this route_config has been configured into istio-proxy after the service has been deleted and then recreated.

### Version

```prose
$ kubectl version --short
Client Version: v1.21.1
Server Version: v1.21.7
```

```
$ helm version --short
v3.6.0+g7f2df64
```

Version of Istio Helm chart: 1.12.2
```


### Additional Information

Relevant logs from Istiod:

On service deletion:
```
{"level":"info","time":"2022-02-15T15:55:56.355882Z","scope":"ads","msg":"Incremental push, service internal-http.app.svc.cluster.local has no endpoints"}
{"level":"info","time":"2022-02-15T15:55:56.456505Z","scope":"ads","msg":"Push debounce stable[53] 3 for config ServiceEntry/app/internal-http.app.svc.cluster.local: 100.462629ms since last change, 104.975426ms since last push, full=true"}
```

On service recreation:
```
{"level":"info","time":"2022-02-15T15:56:44.194493Z","scope":"ads","msg":"Full push, new service app/internal-http.app.svc.cluster.local"}
{"level":"info","time":"2022-02-15T15:56:44.194524Z","scope":"ads","msg":"Full push, service accounts changed, internal-http.app.svc.cluster.local"}
{"level":"info","time":"2022-02-15T15:56:44.294977Z","scope":"ads","msg":"Push debounce stable[54] 3 for config ServiceEntry/app/internal-http.app.svc.cluster.local: 100.427613ms since last change, 112.645002ms since last push, full=true"}
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
