### ISSUE TITLE
custom bootstrap configuration is not being updated

### ISSUE THREAD

**Issue by obaranov1** [istio/istio#37373]
### Bug Description

The custom bootstrap configuration is not being updated when applying configuration with histogram buckets.
The applied Envoy Filter is: apiVersion: networking.istio.io/v1alpha3 kind: EnvoyFilter metadata: name: stats namespace: istio-system spec: configPatches: applyTo: BOOTSTRAP patch: operation: MERGE value: stats_config: histogram_bucket_settings: match: contains: "xxx" - buckets: [2,3,4,5,6,7,8,9]

### Version

```prose
$ istioctl version:
client version: 1.12.2
control plane version: 1.13
data plane version: 1.13-dev (2 proxies)
$ kubectl version --short 
Client Version: v1.20.6
Server Version: v1.20.6
```

### Additional Information

istioctl proxy-config bootstrap istio-ingressgateway-677c685bd9-ct858.istio-system | grep histogram
empty result

**Comment by howardjohn** [comment]
You need to restart the pod to apply updates, did you do that?

**Comment by obaranov1** [comment]
> You need to restart the pod to apply updates, did you do that?

Changes were not applied after the restart

**Comment by douglas-reid** [comment]
@howardjohn this is attempting to modify BOOTSTRAP. that still requires a control plane flag, correct?

**Comment by obaranov1** [comment]
@douglas-reid @howardjohn what is the istio-agent (control plane) flag and where should I add it?

**Comment by srikarrao** [comment]
@obaranov1 Did you get to figure out which flag to set for bootstrap changes to reflect?

**Comment by douglas-reid** [comment]
Is it the `BOOTSTRAP_XDS_AGENT` env var?

**Comment by rolpat** [comment]
As far as I see it is the right one ... with `BOOTSTRAP_XDS_AGENT="true"` my setup worked ... Just as an example I added the main manifests I used below. 

Remark:  for completeness I left the reference to my wasm binary filter file `/etc/filter.wasm`. Without adoption the expected error _file not found_ will appear in the logs.

Envoy filter
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: envoyfilter
spec:
  configPatches:
    - applyTo: BOOTSTRAP
      patch:
        operation: MERGE
        value:
          bootstrap_extensions:
            - name: envoy.bootstrap.wasm
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.wasm.v3.WasmService
                singleton: true
                config:
                  vm_config:
                    vm_id: "my-vm-id"
                    runtime: "envoy.wasm.runtime.v8"
                    code:
                      local:
                        filename: "/etc/filter.wasm"
```

Sample app deployment
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  labels:
    app: echoserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      annotations:
        sidecar.istio.io/componentLogLevel: "wasm:debug,filter:debug,config:debug"
      labels:
        app: echoserver
    spec:
      containers:
        - image: gcr.io/google_containers/echoserver:1.0
          imagePullPolicy: Always
          name: echoserver
          ports:
            - containerPort: 8080
        - name: istio-proxy
          image: auto
          env:
            - name: "BOOTSTRAP_XDS_AGENT"
              value: "true" # "true" to enable bootstrap configuration
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  labels:
    app: echoserver
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: echoserver
```
