### ISSUE TITLE
AuthorizationPolicy doesn't work with authorization header

### ISSUE THREAD

**Issue by ittus** [istio/istio#37394]
### Bug Description

I'm trying to use AuthorizationPolicy to restrict access to **KFServing** URL. **KFServing** is deployed along with **kubeflow**.
We create k8s service account in the same namespace, get secret token and put it in the header of API request.

There config doesn't work 
```yaml
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: request-auth-predictor
  namespace: deploy-namespace
spec:
  selector:
    matchLabels:
      component: predictor
  jwtRules:
    - issuer: "<k8s_issuer>"
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allowlist-by-paths
  namespace: deploy-namespace
spec:
  action: ALLOW
  rules:
    - to:
        - operation:
            paths:
              - /metrics
              - /healthz
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: model-deployment-rules-allow-sa
  namespace: deploy-namespace
spec:
  selector:
    matchLabels:
      component: predictor
  action: ALLOW
  rules:
    - to:
        - operation:
            methods: ["GET", "POST"]
      when:
        - key: request.auth.claims[sub]
          values: ["*"]
```

```bash
curl 'https://example.com/v1/models/mnist:predict' \                 
--header "Authorization: Bearer ${AUTH_TOKEN}" \
--header 'Content-Type: application/json' \
-d @mnist.json

RBAC: access denied
```

If I remove the `when` part in `AuthorizationPolicy`, it will work correctly.
```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: model-deployment-rules-allow-sa
  namespace: deploy-namespace
spec:
  selector:
    matchLabels:
      component: predictor
  action: ALLOW
  rules:
    - to:
        - operation:
            methods: ["GET", "POST"]
 #     when:
 #      - key: request.auth.claims[sub]
 #         values: ["*"]
```

## Istio debug

```
2022-02-16T16:11:30.695207Z	debug	envoy rbac	checking request: requestedServerName: , sourceIP: ***:37234, directRemoteIP: ***, remoteIP: ***,localAddress: ***, ssl: none, headers: ':authority', '***:8012'
':path', '/v1/models/mnist:predict'
':method', 'POST'
'user-agent', 'curl/7.78.0'
'content-length', '401'
'accept', '*/*'
'authorization', 'Bearer eyJhb*****'
'content-type', 'application/json'
'k-original-host', 'pytorch-mnist-predictor-default.deploy-namespace.svc.cluster.local'
'k-proxy-request', 'activator'
'x-amzn-trace-id', 'Root=1-620d2232-78eac82e0cd551a568781ad5'
'x-b3-parentspanid', 'f8766f5caa749e22'
'x-b3-sampled', '1'
'x-b3-spanid', '1e8de4f74d496235'
'x-b3-traceid', 'afb17f33f8db63b8f8766f5caa749e22'
'x-envoy-attempt-count', '1'
'x-envoy-external-address', '***'
'x-forwarded-for', '****'
'x-forwarded-host', 'pytorch-mnist.deploy-namespace.serve.example.com'
'x-forwarded-port', '443'
'x-forwarded-proto', 'http'
'x-request-id', '90f02bce-f140-97ed-a6c3-98e71f11ee64'
'accept-encoding', 'gzip'
, dynamicMetadata: filter_metadata {
  key: "istio_authn"
  value {
  }
}

2022-02-16T16:11:30.695254Z	debug	envoy rbac	enforced denied, matched policy none
```

The `'authorization', 'Bearer eyJhb*****'` is passed correctly to the pod.

### Version

```prose
❯ istioctl version
client version: 1.13.0
control plane version: 1.9.0
data plane version: 1.9.0 (24 proxies)


```
❯ kubectl version --short
Client Version: v1.22.2
Server Version: v1.20.11-eks-f17b81
```

```
❯ helm version --short
v3.7.0+geeac838
```
```
