### ISSUE TITLE
egressgateway perform simple tls get routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED error?

### ISSUE THREAD

**Issue by song0071000** [istio/istio#37435]
### Bug Description

here is some configure of DestinationRule.
```
spec:
  host: www.rickiyang.com
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
      - port:
          number: 50052
        tls:
          mode: SIMPLE
          sni: www.rickiyang.com
          credentialName: xxxclient-credential # k8s secret
```

egressgateway will perform tls for host www.rickiyang.com.

additionally, the ca content can be found in egressgateway dump configuration.

but do request to external host, we get CERTIFICATE_VERIFY_FAILED error.
i am sure the cacert is right. so the CERTIFICATE_VERIFY_FAILED confuse me.

when i remove credentialName item from DestinationRule, it works well.

i am confused about credentialName in dr. 
is credentialName  supported in kind DestinationRule (egressgateway) ?
some misconfigure or not?

### Version

```prose
# % istioctl version
client version: 1.11.4
control plane version: 1.11.4
data plane version: 1.11.4 (53 proxies)
# % kubectl version --short
Client Version: v1.22.3
Server Version: v1.20.4-aliyun.1
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1
```

### Additional Information

completion yaml configure files appear as follows:
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: grpctest1-egress-vs-tls-dr11
  namespace: istio-ryanzhou
spec:
  host: www.rickiyang.com
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
      - port:
          number: 50052
        tls:
          mode: SIMPLE
          sni: www.rickiyang.com
          credentialName: xxxclient-credential
```
