### ISSUE TITLE
a 'fake resolution' service for facilitating user migration to mesh

### ISSUE THREAD

**Issue by Patrick0308** [istio/istio#37469]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Our service used service discovery and service invocation capabilities provided by Micro. Now we want to migrate our services to istio. Here's a question that's bothering us. In micro, client use a simple micro-name to call the server.  But on k8s, our services are located in different namespaces. During the migration process，we need to establish the mapping of services to namespace.  For example. a service called `SERVICE-A` are located on `CORE` namespace，micro client which located on multi-namespaces call `SERVICE-A` by name `SERVICE-A`, but istio client call SERVICE-A by `SERVICE-A.CORE` . There are many choose proposals to resolve this problem.

*We think a lot of people are experiencing similar problems to us.*

Here are three proposals are not very satisfactory.

***Proposal 1***
Micro client `SERVICE-A` by name `SERVICE-A`. In others namespaces, we create external services.
```
apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: other
spec:
  ports:
  - name: grpc
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ExternalName
  externalName: service-a.core.svc.cluster.local
```
We don't like this proposal, because we need creating many external services and managing route rules on multi namespaces.

***Proposal 2***
Micro client  call `SERVICE-A` by name `SERVICE-A.CORE` or FQDN.  The client must know which namespace SERVICE-A located. This  proposal is a bit of a client-side change. 

***Proposal 3***
Micro client  calls `SERVICE-A` by name `SERVICE-A`.  It needs creating ServiceEntry.
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: service-a
spec:
  hosts:
  - "service-a"
  location: MESH_INTERNAL
  ports:
  - number: 8080
    name: grpc-8080
    protocol: grpc
  resolution: STATIC
--- 
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service-a
spec:
  hosts:
  - "service-a"
  http:
  - route:
    - destination:
        host: service-a.core.svc.cluster.local
```
The smart dns and auto-allocated ip is be abled. Although this service entry generate an empty cluster on sidecar and seeing #36864 virtual service cannot route the host which not has period, we think this proposal is better than above. 

 
***Better Proposal***
 Micro client calls SERVICE-A by name SERVICE-A. The better proposal is create a 'fake resolution' service. 
 ```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: service-a
spec:
  hosts:
  - "service-a"
  addresses:
  - "1.1.1.1"
  location: MESH_INTERNAL
  ports:
  - number: 8080
    name: grpc-8080
    protocol: grpc
  resolution: FAKE
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service-a
spec:
  hosts:
  - "service-a"
  http:
  - route:
    - destination:
        host: service-a.core.svc.cluster.local
 ```
This service entry will not generate clusters and endpoints. It will add a dns record. So it needs smart dns is be abled and setting address in service entry. 

This final proposal help people migrate their services to mesh easier.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
