### ISSUE TITLE
Sidecar egress port re-use with unique bind IPs

### ISSUE THREAD

**Issue by dmichel1** [istio/istio#37487]
### Bug Description

Hi 👋 ,

I'm attempting to configure a Virtual Machine with a Sidecar configuration for egress traffic that listens on the same port but uses a different loopback IP address.

Sidecar Configuration

```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: lb-dev
  namespace: vm-us-east-1-aws-dev
spec:
  workloadSelector:
    labels:
      workload_group: lb-dev
  egress:
  - bind: 127.0.1.3
    hosts:
    - 'foo-dev/service-a.foo-dev.svc.cluster.local'
    port:
      name: app-port
      number: 8080
      protocol: TCP
    captureMode: NONE
  - port:
      number: 8080
      protocol: TCP
      name: app-port
    captureMode: NONE
    bind: 127.0.0.10
    hosts:
    - "echo-dev/echo.echo-dev.svc.cluster.local"
  ```

When I try to apply the Sidecar configuration, I get the below validation error...

```
Resource: "networking.istio.io/v1beta1, Resource=sidecars", GroupVersionKind: "networking.istio.io/v1beta1, Kind=Sidecar"
Name: "lb-dev", Namespace: "vm-us-east-1-aws-dev"
for: "sidecar.yaml": admission webhook "validation.istio.io" denied the request: configuration is invalid: sidecar: ports on IP bound listeners must be unique
```

The error is coming from this part of the [validation logic][1]. 

Should this validation logic take into consideration the IP + port combo instead of just the port number or am I missing some part of the bigger picture?

As a workaround I'm looking at using a UNIX socket or potentially creating a ServiceEntry which would have a unique port. 

I'm trying to avoid the ServiceEntry indirection so I don't have keep track of all the ports, which in my current setup can be spread across many code repositories.

[1]: https://github.com/istio/istio/blob/908d3fb4768e103e4d949dcc2a2cb2badce9d627/pkg/config/validation/validation.go#L1110

### Version

```prose
client version: 1.11.3
control plane version: 1.11.6
data plane version: 1.11.6
```
