### ISSUE TITLE
ServiceEntry host with endpoints is not resolvable

### ISSUE THREAD

**Issue by Arsen-Uulu** [istio/istio#37502]
### Bug Description

I have the bellow ServiceEntry and when I try to resolve the host on an instance with Istio sidecar proxy, the host cannot be resolved.  DSN capture is enabled ISTIO_META_DNS_CAPTURE: "true".
Somehow, Istio-ingress gateway is able to route the traffic to my workload with VirtualService in place. 
```
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: test
spec:
  hosts:
    - my-app.test.com
  location: MESH_INTERNAL
  ports:
    - number: 443
      name: HTTPS
      protocol: HTTPS
      targetPort: 8567
  resolution: DNS
  endpoints:
  - address: <valid-host>
```

IF I create the same ServiceEntry and instead provide `addresses`, I can resolve the host.
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: test
spec:
  hosts:
    - my-app.test.com
   addresses:
   - < instance-ip>
  location: MESH_INTERNAL
  ports:
    - number: 443
      name: HTTPS
      protocol: HTTPS
      targetPort: 8567
  resolution: NONE
```

Is this a bug? or I am missing something? 

### Version

```prose
client version: 1.11.0
control plane version: 1.11.0
data plane version: 1.11.0 (8 proxies)
```

**Comment by bianpengyuan** [comment]
Did you enable `ISTIO_META_DNS_AUTO_ALLOCATE`?

**Comment by Arsen-Uulu** [comment]
No, Documentation says it's optional

**Comment by bianpengyuan** [comment]
It will be required if you don't specify service address: https://preliminary.istio.io/latest/docs/ops/configuration/traffic-management/dns-proxy/#address-auto-allocation

**Comment by Arsen-Uulu** [comment]
Let me try and report back. Thank you

**Comment by hzxuzhonghu** [comment]
Why you specify  resolution: DNS with endpoints address, i think it is not valid, there will be two address, how istio could not know  which to resolve

**Comment by Arsen-Uulu** [comment]
@hzxuzhonghu I don't think I understand. I specified `resolution: DNS` because
```
endpoints:
- address: <host-that-will-resolve-to-a-single-ip>
```
Is this wrong, you say?

**Comment by Arsen-Uulu** [comment]
This host here is not resolvable 
```
spec:
  hosts:
    - my-app.test.com
```

**Comment by Arsen-Uulu** [comment]
@bianpengyuan I enabled ISTIO_META_DNS_AUTO_ALLOCATE and still no luck

**Comment by Arsen-Uulu** [comment]
With the bellow SE, I can see in the logs of the Istio Ingress gateway that is resolved to correct IP and able to route, but no other proxy can resolve that host.
In the logs of Istiod I see 
```
pilot_dns_cluster_without_endpoints
````

```
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: test
spec:
  hosts:
    - my-app.test.com
  location: MESH_INTERNAL
  ports:
    - number: 443
      name: HTTPS
      protocol: HTTPS
      targetPort: 8567
  resolution: DNS
  endpoints:
  - address: <valid-host>
 ```

**Comment by Arsen-Uulu** [comment]
> Why you specify resolution: DNS with endpoints address, i think it is not valid, there will be two address, how istio could not know which to resolve

If I use FQDN in the endpoint address, and won't set resolution to DNS, I get error that is not valid IP

**Comment by hzxuzhonghu** [comment]
I get to understand your usage. Yes, istio does not resolve the endpoints address now. 

You can remove the endpoints in SE and move the address to SE.Hosts as a workaround.

**Comment by Arsen-Uulu** [comment]
>I get to understand your usage. Yes, istio does not resolve the endpoints address now.

Because it's not supported? Is there a plan to support it? Ingress Gateway can resolve this. FYI

> You can remove the endpoints in SE and move the address to SE.Hosts as a workaround.

So SE.Hosts will be the FQDN address, right? I won't get `my-app.test.com`

**Comment by bianpengyuan** [comment]
What exactly is the error when you apply configuration like you mentioned at https://github.com/istio/istio/issues/37502#issuecomment-1050110502? Is it just that your client is not able to verify server cert? The following works for me if I use `curl -iv --insecure https://a.b.c`:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: test
spec:
  hosts:
    - a.b.c
  location: MESH_INTERNAL
  ports:
    - number: 443
      name: https
      protocol: HTTPS
      targetPort: 443
  resolution: DNS
  endpoints:
  - address: www.httpbin.org
```
