### ISSUE TITLE
Route rules in BookInfo Sample (and docs) claim to be v1alpha2 but look like v1alpha1

### ISSUE THREAD

**Issue by rosenhouse** [istio/istio#3750]
Looking at [this page, for example](https://istio.io/docs/tasks/traffic-management/request-routing.html) I see

```yaml
apiVersion: config.istio.io/v1alpha2
  ...
spec:
  destination:
    name: details
  precedence: 1
  route:
  - labels:
      version: v1
```

which appears to match the the contents of [this file](https://github.com/istio/istio/blob/master/samples/bookinfo/kube/route-rule-all-v1.yaml).

But when I look at [the protofile for v1apha2](https://github.com/istio/api/blob/master/routing/v1alpha2/route_rule.proto) I see a different structure, which doesn't have top-level `destination` or `precedence` fields, but does have top-level `hosts` and `http` fields.

Am I mis-reading things?
