### ISSUE TITLE
Unable to enable redis filter

### ISSUE THREAD

**Issue by keyolk** [istio/istio#37525]
### Bug Description

Following below docs,
- https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/
- https://istio.io/latest/docs/reference/commands/pilot-discovery/#envvars

Unable to enable redis filter.

Some manifests I have tested with

- namespace
```yaml
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2022-01-11T05:39:48Z"
  labels:
    istio-injection: enabled
  name: default
  resourceVersion: "13948976"
  uid: b15c063b-abc8-40b1-bb60-015748dd79bb
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```

- redis
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis
data:
  redis.conf: |
    protected-mode no
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      annotations:
        proxy.istio.io/config: '{"proxyMetadata": {"PILOT_ENABLE_REDIS_FILTER": "true"}}'
      labels:
        version: v1
        app: redis
    spec:
      containers:
        - name: server
          image: redis:6.2.6
          ports:
            - containerPort: 6379
              name: tcp-redis
          command: ["redis-server", "/conf/redis.conf"]
          volumeMounts:
            - name: conf
              mountPath: /conf
              readOnly: false
      volumes:
        - name: conf
          configMap:
            name: redis
            defaultMode: 0755
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - port: 6379
    name: redis
    appProtocol: redis
  selector:
    app: redis
```

- redis client
```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    proxy.istio.io/config: '{"proxyMetadata": {"PILOT_ENABLE_REDIS_FILTER": "true"}}'
  name: cli
spec:
  containers:
  - command:
    - bash
    image: redis:6.2.6
    name: redil-cli
    stdin: true
    tty: true
```

enable client's proxy logs.
```bash
$ istioctl proxy-config log cli --level http:warning,redis:debug,filter:debug
```

check the filter env is set and run a redis command.
```bash
$ kubectl exec -ti cli -c istio-proxy -- env | grep -i redis_filter 
PILOT_ENABLE_REDIS_FILTER=true
(...)
$ kubectl exec -ti redis -c istio-proxy -- env | grep -i redis_filter 
PILOT_ENABLE_REDIS_FILTER=true
(...)
$ kubectl attach -ti cli
root@cli:/data# redis-cli -h redis.default.svc.cluster.local get who
(nil)
```

no redis log from istio-proxy.
```bash
$ kubectl logs -f cli -c istio-proxy 
(...)
2022-02-24T19:05:26.312611Z     debug   envoy filter    original_dst: new connection accepted
2022-02-24T19:05:26.312680Z     debug   envoy filter    [C262] new tcp proxy session
2022-02-24T19:05:26.312703Z     debug   envoy filter    [C262] Creating connection to cluster outbound|6379||redis.default.svc.cluster.local
2022-02-24T19:05:26.315252Z     debug   envoy filter    [C262] TCP:onUpstreamEvent(), requestedServerName:
(...)
```

from istioctl
```bash
$ istioctl pc listener cli --port 6379
ADDRESS        PORT MATCH DESTINATION
172.20.96.28   6379 ALL   Cluster: outbound|6379||redis.default.svc.cluster.local
$ istioctl pc cluster cli --port 6379
SERVICE FQDN                                    PORT     SUBSET     DIRECTION     TYPE           DESTINATION RULE
redis.default.svc.cluster.local                 6379     -          outbound      EDS
```

dump envoy config
```bash
$ istioctl pc listener cli --port 6379 -o yaml
- address:
    socketAddress:
      address: 172.20.96.28
      portValue: 6379
  bindToPort: false
  filterChains:
  - filters:
    - name: istio.stats
      typedConfig:
        '@type': type.googleapis.com/udpa.type.v1.TypedStruct
        typeUrl: type.googleapis.com/envoy.extensions.filters.network.wasm.v3.Wasm
        value:
          config:
            configuration:
              '@type': type.googleapis.com/google.protobuf.StringValue
              value: |
                {
                  "debug": "false",
                  "stat_prefix": "istio"
                }
            root_id: stats_outbound
            vm_config:
              code:
                local:
                  inline_string: envoy.wasm.stats
              runtime: envoy.wasm.runtime.null
              vm_id: tcp_stats_outbound
    - name: envoy.filters.network.tcp_proxy
      typedConfig:
        '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
        cluster: outbound|6379||redis.default.svc.cluster.local
        statPrefix: outbound|6379||redis.default.svc.cluster.local
  name: 172.20.96.28_6379
  trafficDirection: OUTBOUND
```

it has TcpProxy

### Version

```prose
$ istioctl version                                                                                       client version: 1.12.1
control plane version: 1.12.2
data plane version: 1.12.2 (4 proxies)
$ kubectl version --short                                                                             
Client Version: v1.22.4
Server Version: v1.20.11-eks-f17b81
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1
```

### Additional Information

(...)

Running with the following config:

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-system,kube-public,kube-node-lease,local-path-storage }
end-time: 2022-02-25 04:16:38.564552 +0900 KST

(...)

CLI version:
version.BuildInfo{Version:"1.12.1", GitRevision:"88902a51acfb0383809608ccff169319560f768c-dirty", GolangVersion:"go1.17.3", BuildStatus:"Modified", GitTag:"1.12.1"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.12.2", GitRevision:"af0d66fd0aa363e9a7b0164f3a94ba36252fe60f", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.12.2"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.12.2}

Fetching proxy logs for the following containers:

default//cli/istio-proxy
default//cli/redil-cli
default/redis/redis-666df5db54-7sqw2/istio-proxy
default/redis/redis-666df5db54-7sqw2/server
istio-system/istio-ingressgateway/istio-ingressgateway-677c74785d-zcwhj/istio-proxy
istio-system/istiod/istiod-b5ffd9549-5pj87/discovery
istio-system/jaeger/jaeger-5f65fdbf9b-6k27b/jaeger
istio-system/kiali/kiali-585bd7d744-kvj6x/kiali
kiali-operator/kiali-operator/kiali-operator-5894d7d65c-vkfn5/operator
prometheus//prometheus-prom-kube-prometheus-stack-prometheus-0/config-reloader
prometheus//prometheus-prom-kube-prometheus-stack-prometheus-0/prometheus
prometheus/prom-grafana/prom-grafana-844b8f5676-wtpqc/grafana
prometheus/prom-grafana/prom-grafana-844b8f5676-wtpqc/grafana-sc-dashboard
prometheus/prom-kube-prometheus-stack-operator/prom-kube-prometheus-stack-operator-dc48b6f86-7dwwz/kube-prometheus-stack

Fetching Istio control plane information from cluster.

The following fetches are still running:
  kubectl get --all-namespaces alertmanagerconfigs.monitoring.coreos.com,alertmanagers.monitoring.coreos.com,authorizationpolicies.security.istio.io,destinationrules.networking.istio.io,eniconfigs.crd.k8s.amazonaws.com,envoyfilters.networking.istio.io,externalsecrets.kubernetes-client.io,gateways.networking.istio.io,ingressclassparams.elbv2.k8s.aws,istiooperators.install.istio.io,kialis.kiali.io,peerauthentications.security.istio.io,podmonitors.monitoring.coreos.com,probes.monitoring.coreos.com,prometheuses.monitoring.coreos.com,prometheusrules.monitoring.coreos.com,requestauthentications.security.istio.io,securitygrouppolicies.vpcresources.k8s.aws,serviceentries.networking.istio.io,servicemonitors.monitoring.coreos.com,sidecars.networking.istio.io,targetgroupbindings.elbv2.k8s.aws,telemetries.telemetry.istio.io,thanosrulers.monitoring.coreos.com,virtualservices.networking.istio.io,wasmplugins.extensions.istio.io,workloadentries.networking.istio.io,workloadgroups.networking.istio.io -o yaml

Running istio analyze on all namespaces and report as below:

Analysis Report:
Info [IST0102] (Namespace kiali-operator) The namespace is not enabled for Istio injection. Run 'kubectl label namespace kiali-operator istio-injection=enabled' to enable it, or 'kubectl label namespace kiali-operator istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace prometheus) The namespace is not enabled for Istio injection. Run 'kubectl label namespace prometheus istio-injection=enabled' to enable it, or 'kubectl label namespace prometheus istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0118] (Service istio-system/jaeger-collector) Port name jaeger-collector-grpc (port: 14250, targetPort: 14250) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service istio-system/jaeger-collector) Port name jaeger-collector-http (port: 14268, targetPort: 14268) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service prometheus/prom-grafana) Port name service (port: 80, targetPort: 3000) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service prometheus/prom-kube-prometheus-stack-prometheus) Port name web (port: 9090, targetPort: 9090) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service prometheus/prometheus-operated) Port name web (port: 9090, targetPort: web) doesn't follow the naming convention of Istio port.

(...)

Done.
