### ISSUE TITLE
Kubernetes Webhook oddities when upgrading to Istio 1.12.2

### ISSUE THREAD

**Issue by AlexDHoffer** [istio/istio#37545]
### Bug Description

When upgrading from Istio 1.8.2 to Istio 1.12.2 on Azure Kubernetes Service using the ``Operator`` path, I see two strange things:

1. The ``ValidatingWebhookConfiguration`` istio-validator-istio-system is added, but istiod-istio-system remains in place. Is istiod-istio-system able to be removed? Its labels suggest that it hasn't been touched by the upgrade:

````
  labels:
    app: istiod
    install.operator.istio.io/owning-resource: istio-control-default
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: istiod
    istio.io/rev: default
    operator.istio.io/component: Base
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.8.2
    release: istio
````

By contrast, the istio-validator-istio-system's labels report:

````
  labels:
    app: istiod
    install.operator.istio.io/owning-resource: istio-control-default
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: istiod
    istio.io/rev: default
    operator.istio.io/component: Pilot
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.12.2
    release: istio
````

2. The ``MutatingWebhookConfiguration`` istio-sidecar-injector has to be erased manually, lest the Operator logs report:

````
Error [IST0139] (MutatingWebhookConfiguration istio-sidecar-injector) Webhook overlaps with others: [istio-sidecar-injector/namespace.sidecar-injector.istio.io]. This may cause injection to occur twice.
````

Is this expected behavior? When I erase it, the logs disappear and the istio-sidecar-injector webhook is recreated.

Thanks in advance.

### Version

```prose
$ istioctl version
client version: 1.12.2
control plane version: 1.12.2
data plane version: 1.12.2 (18 proxies)

$ kubectl version --short
Client Version: v1.22.1
Server Version: v1.20.9

$ helm version --short
v3.6.3+gd506314
```

### Additional Information

Target cluster context: plat

Running with the following config:

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-system,kube-public,kube-node-lease,local-path-storage }
end-time: 2022-02-25 12:22:09.542518 -0800 PST

Cluster endpoint: [**redacted**]
CLI version:
version.BuildInfo{Version:"1.12.2", GitRevision:"af0d66fd0aa363e9a7b0164f3a94ba36252fe60f", GolangVersion:"go1.17.5", BuildStatus:"Clean", GitTag:"1.12.2"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.12.2", GitRevision:"af0d66fd0aa363e9a7b0164f3a94ba36252fe60f", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.12.2"},
    },
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.12.2", GitRevision:"af0d66fd0aa363e9a7b0164f3a94ba36252fe60f", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.12.2"},
    },
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.12.2", GitRevision:"af0d66fd0aa363e9a7b0164f3a94ba36252fe60f", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.12.2"},
    },
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.12.2", GitRevision:"af0d66fd0aa363e9a7b0164f3a94ba36252fe60f", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.12.2"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.12.2}

Fetching proxy logs for the following containers:

[**redacted - app pods and monitoring pods**]
istio-operator/istio-operator/istio-operator-85db69d58-d4n2k/istio-operator
istio-system/istio-ingressgateway/istio-ingressgateway-574b7c9495-vdpn8/istio-proxy
istio-system/istio-ingressgateway/istio-ingressgateway-574b7c9495-zfvnc/istio-proxy
istio-system/istiod/istiod-7f7f8d7fb7-fxm4h/discovery
istio-system/istiod/istiod-7f7f8d7fb7-p6zfx/discovery
istio-system/istiod/istiod-7f7f8d7fb7-pjzxq/discovery
istio-system/istiod/istiod-7f7f8d7fb7-svnhv/discovery

Fetching Istio control plane information from cluster.

Running istio analyze on all namespaces and report as below:
Analysis Report:

Warning [IST0133] (EnvoyFilter istio-system/metadata-exchange-1.6) Schema validation warning: using deprecated filter name "envoy.http_connection_manager"; use "envoy.filters.network.http_connection_manager" instead
Warning [IST0133] (EnvoyFilter istio-system/metadata-exchange-1.7) Schema validation warning: using deprecated filter name "envoy.http_connection_manager"; use "envoy.filters.network.http_connection_manager" instead
Warning [IST0133] (EnvoyFilter istio-system/metadata-exchange-1.8) Schema validation warning: using deprecated filter name "envoy.http_connection_manager"; use "envoy.filters.network.http_connection_manager" instead
Warning [IST0133] (EnvoyFilter istio-system/stats-filter-1.6) Schema validation warning: using deprecated filter name "envoy.http_connection_manager"; use "envoy.filters.network.http_connection_manager" instead
Warning [IST0133] (EnvoyFilter istio-system/stats-filter-1.6) Schema validation warning: using deprecated filter name "envoy.router"; use "envoy.filters.http.router" instead
Warning [IST0133] (EnvoyFilter istio-system/stats-filter-1.7) Schema validation warning: using deprecated filter name "envoy.http_connection_manager"; use "envoy.filters.network.http_connection_manager" instead
Warning [IST0133] (EnvoyFilter istio-system/stats-filter-1.7) Schema validation warning: using deprecated filter name "envoy.router"; use "envoy.filters.http.router" instead
Warning [IST0133] (EnvoyFilter istio-system/stats-filter-1.8) Schema validation warning: using deprecated filter name "envoy.http_connection_manager"; use "envoy.filters.network.http_connection_manager" instead
Warning [IST0133] (EnvoyFilter istio-system/stats-filter-1.8) Schema validation warning: using deprecated filter name "envoy.router"; use "envoy.filters.http.router" instead
Warning [IST0133] (EnvoyFilter istio-system/tcp-stats-filter-1.6) Schema validation warning: using deprecated filter name "envoy.tcp_proxy"; use "envoy.filters.network.tcp_proxy" instead
Warning [IST0133] (EnvoyFilter istio-system/tcp-stats-filter-1.7) Schema validation warning: using deprecated filter name "envoy.tcp_proxy"; use "envoy.filters.network.tcp_proxy" instead
Warning [IST0133] (EnvoyFilter istio-system/tcp-stats-filter-1.8) Schema validation warning: using deprecated filter name "envoy.tcp_proxy"; use "envoy.filters.network.tcp_proxy" instead

Done.
