### ISSUE TITLE
holdApplicationUntilProxyStarts doesn't work with preStop hook

### ISSUE THREAD

**Issue by jdomag** [istio/istio#37541]
### Bug Description

holdApplicationUntilProxyStarts should add postStart hook command `pilot-agent wait` to istio-proxy container. 
However after adding the `holdApplicationUntilProxyStarts: true` to istio config I can't see postStart hooks being added  (there's only preStop that I use to make sure envoy exits after the app container).

![image](https://user-images.githubusercontent.com/28705876/155680691-c827e8d9-67f1-4115-956a-ff331465005b.png)

Looking at the repository I found those lines:

https://github.com/istio/istio/blob/0faf5136361fa4cea96787872a024882dfc85d9d/operator/cmd/mesh/testdata/manifest-generate/output/sidecar_template.golden.yaml#L369

It doesn't make any sense for me - I used preStop and holdApplicationUntilProxyStarts and ended up with preStop hook only. I understand though that both holdApplicationUntilProxyStarts and .Values.global.proxy.lifecycle.postStart can't be use the same time, but this shouldn't affect preStop hook. 

### Version

```prose
istioctl version                                                                    
client version: 1.12.1
control plane version: 1.12.1
data plane version: 1.12.1 (150 proxies)


kubectl version --short
Client Version: v1.21.1
Server Version: v1.21.8
```

**Comment by zufardhiyaulhaq** [comment]
I believe `holdApplicationUntilProxyStarts` only move the sidecar to the first order of the containers. Kubernetes by default will start from the first container, so it's actually hold the application container before the proxy start.

**Comment by s-shirayama** [comment]
We encountered the same issue.
As a workaround, we are planning to add `postStart` manually to IstioOperator like below.

```
kind: IstioOperator
spec:
  values:
    global:
      proxy:
        lifecycle:
          # Ref: https://github.com/istio/istio/blob/438850766c7706c79de58a315d59a4bd6623dc0f/manifests/charts/istiod-remote/files/injection-template.yaml#L200-L210
          postStart:
            exec:
              command:
                - pilot-agent
                - wait
          preStop:
            exec:
              command:
                - ...
```
