### ISSUE TITLE
When wasm plugin use OCI image, the `sha256` field should be the wasm binary's checksum instead of the image's digest.

### ISSUE THREAD

**Issue by johnlanni** [istio/istio#37565]
Example resource:
```yaml
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: openid-connect
  namespace: istio-ingress
spec:
  selector:
    labels:
      istio: ingressgateway
  url: oci://private-registry:5000/openid-connect/openid:latest
  sha256: 1ef0c9a92b0420cf25f7fe5d481b231464bc88f486ca3b9c83ed5cc21d2f6210
```
 
When [fetching entries](https://github.com/istio/istio/blob/6654a4ab8b56c19ae0eb737652fa6a8876731dff/pkg/wasm/cache.go#L116) from the wasm file cache, the url + sha256 specified in WasmPlguin is used.

When [storing entries](https://github.com/istio/istio/blob/6654a4ab8b56c19ae0eb737652fa6a8876731dff/pkg/wasm/cache.go#L185) to the wasm file cache, the url + binary checksum  used.

Therefore, when specifying the `sha256` field as the  OCI image's digest, the cache here will never be hit.
