### ISSUE TITLE
Helm charts: gateways: provide a daemonset chart

### ISSUE THREAD

**Issue by jgournet** [istio/istio#37610]
**Describe the feature request**
Could you provide a daemonset type for gateways ?
https://github.com/istio/istio/blob/master/manifests/charts/gateways/istio-ingress/templates/deployment.yaml
or:
https://github.com/istio/istio/blob/master/manifests/charts/gateway/templates/deployment.yaml

**Describe alternatives you've considered**
We're migrating from istioctl installation back to helm, where we could "easily" set the ingress to run as daemonset with:
```
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
      namespace: istio-system
      k8s:
        overlays:
          - kind: Deployment
            name: istio-ingressgateway
            patches:
              - path: kind
                value: DaemonSet
              - path: spec.strategy
```
But there's no "daemonset" yet in helm

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
