### ISSUE TITLE
TLS on sidecar proxy implementation always uses http1.1 even when ALPN negotiation during TLS has h2

### ISSUE THREAD

**Issue by shriramsharma** [istio/istio#37611]
The current implementation of `TLS on sidecar proxy` does not support h2 even if the TLS ALPN negotiation happens on h2.
This is because when building the upstream cluster config, the `Http2ProtocolOptions` are included only if the service port is HTTP2/GRPC/GRPCWeb. 
As @howardjohn mentioned [here](https://github.com/istio/istio/pull/36210#discussion_r782528825), we could use [HttpProtocolOptions.AutoHttpConfig](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/upstreams/http/v3/http_protocol_options.proto#extensions-upstreams-http-v3-httpprotocoloptions-autohttpconfig) if the port on the service is set to `https`

cc: @aattuluri

**Comment by shriramsharma** [comment]
It seems [HttpProtocolOptions.AutoHttpConfig](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/upstreams/http/v3/http_protocol_options.proto#extensions-upstreams-http-v3-httpprotocoloptions-autohttpconfig) is probably not the right away to go about fixing this.
As the document mentions, this can only work with transport socker that supports `ALPN`, and in our case, the issue is happening when the proxy negotiates `h2` but forwards `http1.1` to the local workload (`inbound|80||`) and this communication is not over TLS.

@howardjohn suggested trying `HttpProtocolOptions_UseDownstreamProtocolConfig` instead and that did the trick. Using `use_downstream_protocol_config`, envoy will use the protocol that was negotiated with the downstream.
This works as long as the client is aware of the correct protocol to use to send request to the server.

#### Example envoy config
```
typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        use_downstream_protocol_config:
          http2_protocol_options:
            connection_keepalive:
              interval: 30s
              timeout: 5s
```
