### ISSUE TITLE
Got "no upstream host" error with redis proxy

### ISSUE THREAD

**Issue by keyolk** [istio/istio#37630]
### Bug Description

I'm testing istio's redis proxy related functions.
With tcp proxy it works normally.
But after enabling redis-proxy, I got "no upstream host" error with redis-proxy.

My redis deployment for test.
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis
data:
  redis.conf: |
    protected-mode no
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        version: v1
        app: redis
    spec:
      containers:
        - name: server
          image: redis:6.2.6
          ports:
            - containerPort: 6379
              name: redis
          command: ["redis-server", "/conf/redis.conf"]
          volumeMounts:
            - name: conf
              mountPath: /conf
              readOnly: false
      volumes:
        - name: conf
          configMap:
            name: redis
            defaultMode: 0755
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - port: 6379
    name: redis
    appProtocol: redis
  selector:
    app: redis
```

From the pod redis-cli
```bash
$ redis-cli -h redis get who
(error) no upstream host
```

Istio proxy log from both redis-cli and redis.
```bash
2022-03-01T15:56:47.391410Z     debug   envoy filter    original_dst: new connection accepted
2022-03-01T15:56:47.391629Z     debug   envoy redis     splitting '["get", "who"]'
```

```bash
2022-03-01T15:56:47.391932Z     debug   envoy redis     splitting '["get", "who"]'
2022-03-01T15:56:47.391956Z     warning envoy upstream  original_dst_load_balancer: No downstream connection or no original_dst.
2022-03-01T15:56:47.391959Z     debug   envoy redis     host not found: 'who'
```

And there was no connection that uses src IP 127.0.0.6 from the redis pod.
```bash
$ kubectl exec -ti -n redis -c istio-proxy deployment/redis -- bash
istio-proxy@redis-666df5db54-n4thc:/$ ss -tan | grep 127.0.0.6
```

Also, it can't connect to the redis from redis pods network namespace using the redis's service IP
```bash
$ ./redis-cli -h 172.20.148.219 get who
(error) no upstream host
```

Of course it can connect with 127.0.0.1
```bash
$ ./redis-cli get who
(nil)
```

I have tried with disabling/enabling mTLS but no changes.
```yaml
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "disable-mtls"
  namespace: "redis"
spec:
  host: "*.redis.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: DISABLE
```

in the case with mTLS, the log from redis's is changed like the below.
```bash
2022-03-01T16:33:07.857817Z     debug   envoy filter    original_dst: new connection accepted
2022-03-01T16:33:07.857854Z     debug   envoy filter    tls inspector: new connection accepted
2022-03-01T16:33:07.857886Z     debug   envoy filter    tls:onServerName(), requestedServerName: outbound_.6379_._.redis.redis.svc.cluster.local
2022-03-01T16:33:07.858372Z     warning envoy filter    Incorrect istio-peer-exchange ALPN magic. Peer missing TCP MetadataExchange filter.
2022-03-01T16:33:07.858405Z     debug   envoy redis     splitting '["get", "who"]'
2022-03-01T16:33:07.858414Z     warning envoy upstream  original_dst_load_balancer: No downstream connection or no original_dst.
2022-03-01T16:33:07.858417Z     debug   envoy redis     host not found: 'who'
```

Any clue to solve this?

### Version

```prose
$ istioctl version                                                                                       client version: 1.12.1
control plane version: 1.12.2
data plane version: 1.12.2 (4 proxies)
$ kubectl version --short                                                                             
Client Version: v1.22.4
Server Version: v1.20.11-eks-f17b81
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1
```

### Additional Information

```bash

Target cluster context: (...)

Running with the following config:

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-system,kube-public,kube-node-lease,local-path-storage }
end-time: 2022-03-02 01:35:04.986044 +0900 KST



Cluster endpoint: (...)
CLI version:
version.BuildInfo{Version:"1.12.1", GitRevision:"88902a51acfb0383809608ccff169319560f768c-dirty", GolangVersion:"go1.17.3", BuildStatus:"Modified", GitTag:"1.12.1"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.12.2", GitRevision:"af0d66fd0aa363e9a7b0164f3a94ba36252fe60f", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.12.2"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.12.2}


Fetching proxy logs for the following containers:

default/details-v1/details-v1-79f774bdb9-vjkq7/details
default/details-v1/details-v1-79f774bdb9-vjkq7/istio-proxy
default/productpage-v1/productpage-v1-6b746f74dc-qv4ls/istio-proxy
default/productpage-v1/productpage-v1-6b746f74dc-qv4ls/productpage
default/ratings-v1/ratings-v1-b6994bb9-4sf7s/istio-proxy
default/ratings-v1/ratings-v1-b6994bb9-4sf7s/ratings
default/reviews-v1/reviews-v1-545db77b95-rbcfb/istio-proxy
default/reviews-v1/reviews-v1-545db77b95-rbcfb/reviews
default/reviews-v2/reviews-v2-7bf8c9648f-mqnmj/istio-proxy
default/reviews-v2/reviews-v2-7bf8c9648f-mqnmj/reviews
default/reviews-v3/reviews-v3-84779c7bbc-nwhlx/istio-proxy
default/reviews-v3/reviews-v3-84779c7bbc-nwhlx/reviews
external/redis/redis-666df5db54-mq8q9/server
istio-system/istio-ingressgateway/istio-ingressgateway-677c74785d-zqqfc/istio-proxy
istio-system/istiod/istiod-5d9d68d9c5-lxclf/discovery
istio-system/jaeger/jaeger-5f65fdbf9b-6k27b/jaeger
istio-system/kiali/kiali-585bd7d744-kvj6x/kiali
kiali-operator/kiali-operator/kiali-operator-5894d7d65c-vkfn5/operator
prometheus//prometheus-prom-kube-prometheus-stack-prometheus-0/config-reloader
prometheus//prometheus-prom-kube-prometheus-stack-prometheus-0/prometheus
prometheus/prom-grafana/prom-grafana-844b8f5676-wtpqc/grafana
prometheus/prom-grafana/prom-grafana-844b8f5676-wtpqc/grafana-sc-dashboard
prometheus/prom-kube-prometheus-stack-operator/prom-kube-prometheus-stack-operator-dc48b6f86-7dwwz/kube-prometheus-stack
redis//cli/istio-proxy
redis//cli/redil-cli
redis/redis/redis-666df5db54-n4thc/istio-proxy
redis/redis/redis-666df5db54-n4thc/server

Fetching Istio control plane information from cluster.

The following fetches are still running:
  kubectl get --all-namespaces alertmanagerconfigs.monitoring.coreos.com,alertmanagers.monitoring.coreos.com,authorizationpolicies.security.istio.io,destinationrules.networking.istio.io,eniconfigs.crd.k8s.amazonaws.com,envoyfilters.networking.istio.io,externalsecrets.kubernetes-client.io,gateways.networking.istio.io,ingressclassparams.elbv2.k8s.aws,istiooperators.install.istio.io,kialis.kiali.io,peerauthentications.security.istio.io,podmonitors.monitoring.coreos.com,probes.monitoring.coreos.com,prometheuses.monitoring.coreos.com,prometheusrules.monitoring.coreos.com,requestauthentications.security.istio.io,securitygrouppolicies.vpcresources.k8s.aws,serviceentries.networking.istio.io,servicemonitors.monitoring.coreos.com,sidecars.networking.istio.io,targetgroupbindings.elbv2.k8s.aws,telemetries.telemetry.istio.io,thanosrulers.monitoring.coreos.com,virtualservices.networking.istio.io,wasmplugins.extensions.istio.io,workloadentries.networking.istio.io,workloadgroups.networking.istio.io -o yaml
  kubectl get --all-namespaces all,namespaces,jobs,ingresses,endpoints,customresourcedefinitions,configmaps,events,mutatingwebhookconfigurations,validatingwebhookconfigurations -o yaml

Running istio analyze on all namespaces and report as below:
Analysis Report:
Info [IST0102] (Namespace external) The namespace is not enabled for Istio injection. Run 'kubectl label namespace external istio-injection=enabled' to enable it, or 'kubectl label namespace external istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace kiali-operator) The namespace is not enabled for Istio injection. Run 'kubectl label namespace kiali-operator istio-injection=enabled' to enable it, or 'kubectl label namespace kiali-operator istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace prometheus) The namespace is not enabled for Istio injection. Run 'kubectl label namespace prometheus istio-injection=enabled' to enable it, or 'kubectl label namespace prometheus istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0118] (Service istio-system/jaeger-collector) Port name jaeger-collector-grpc (port: 14250, targetPort: 14250) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service istio-system/jaeger-collector) Port name jaeger-collector-http (port: 14268, targetPort: 14268) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service prometheus/prom-grafana) Port name service (port: 80, targetPort: 3000) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service prometheus/prom-kube-prometheus-stack-prometheus) Port name web (port: 9090, targetPort: 9090) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service prometheus/prometheus-operated) Port name web (port: 9090, targetPort: web) doesn't follow the naming convention of Istio port.
Creating an archive at (...)
Cleaning up temporary files in /var/folders/7g/1dw9yqgj4mzcrfgcsqj9vs6w0000gq/T/bug-report.
Done.

```
