### ISSUE TITLE
CNI ignoring traffic annotations

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#37637]
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloserver
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/includeInboundPorts: "*"
        traffic.sidecar.istio.io/includeOutboundPorts: "4140"
        istio.io/rev: asm-managed
      labels:
        app: helloserver
    spec:
      containers:
      - image: gcr.io/google-samples/whereami:v1.2.4
        imagePullPolicy: Always
        name: main
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
```
includeOutboundPorts is ignored
