### ISSUE TITLE
Stackdriver logging seems to become enabled when enabling stackdriver metrics

### ISSUE THREAD

**Issue by rolandkool** [istio/istio#37667]
### Bug Description

When enabling Stackdriver metrics through the Telemetry API, it seems that it also enables stackdriver logging.
With a Non-ASM deployment of Istio, the istio-proxy does not have any stackdriver permissions by default, which causes log messages like this to show up in the envoy logs to stdout:
```
wasm log stackdriver_inbound stackdriver_inbound: [extensions/stackdriver/log/exporter.cc:64]::operator()() Stackdriver logging api call error: 7The caller does not have permission
```

The telemetry API config that triggers this:
```
  - overrides:
    - disabled: false
      match:
        metric: ALL_METRICS
        mode: CLIENT_AND_SERVER
    providers:
    - name: stackdriver
 ```

### Version

```prose
Istio 1.13.1 (OSS)
```

### Additional Information

This gist contains a config_dump of the pod that logged the warning: https://gist.github.com/rolandkool/dd4f7f772974288a73e0df8f2dd8dc38
