### ISSUE TITLE
MeshConfig.ExtensionProvider requires name property but installation doesn't fail when not set

### ISSUE THREAD

**Issue by rolandkool** [istio/istio#37666]
### Bug Description

When configuring custom logformat through the new MeshConfig.ExtensionProvider config block, it is possible to omit the `name` property even though it is required. The installer will not fail with a validation error.

The following configuration is accepted while it doesn't work / have any effect:
```
        extensionProviders:
        - envoyFileAccessLog:
            path: "/dev/stdout"
            logFormat:
              labels:
                source_host: "%HOSTNAME%"
```

### Version

```prose
Istio 1.13.1
```
