### ISSUE TITLE
Istio egress connections via service entry always show response code 0

### ISSUE THREAD

**Issue by bnutt** [istio/istio#37687]
### Bug Description

Egress telemetry is missing information even in successful requests made to external endpoints.

Given the following service entry that is being applied to all proxies in the mesh:
```
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: amazonaws.com
spec:
  hosts:
    - "sts.amazonaws.com"
  ports:
    - number: 443
      name: tls
      protocol: tls
  location: MESH_EXTERNAL
```

Egress logs made to `sts.amazonaws.com` show up like so:
```
{"bytes_sent":5707,"request_id":null,"user_agent":null,"response_code_details":null,"downstream_local_address":"209.54.180.124:443","authority":null,"upstream_local_address":"10.5.28.96:36452","response_flags":"-","duration":687,"upstream_service_time":null,"downstream_remote_address":"10.5.28.96:36436","upstream_transport_failure_reason":null,"path":null,"bytes_received":784,"connection_termination_details":null,"response_code":0,"x_forwarded_for":null,"requested_server_name":"sts.amazonaws.com","protocol":null,"start_time":"2022-03-03T04:52:21.898Z","upstream_host":"209.54.180.124:443","route_name":null,"method":null,"upstream_cluster":"outbound|443||sts.amazonaws.com"}
```

I can verify that the pod is able to connect to `sts.amazonaws.com`.  but it is difficult for users to know what the response of that endpoint is without doing some manual testing. Is this the expected behavior for egress requests to hosts outside of the mesh? If not, is there a specific way to enable the response code being available? Having this information would be really helpful in debugging application issues, monitoring in dashboards, etc. 

Thanks!

### Version

```prose
Control Plane Version: 1.11.1
kubectl version: v1.20.11-eks-f17b81
```
