### ISSUE TITLE
Enable accessLogEncoding and accessLogFile for Ingressgateway via Helm

### ISSUE THREAD

**Issue by rameshar16** [istio/istio#37682]
Hi All,
I am trying to enable the below options for Instio Ingressgateway and installed the ingress gateway via Istio. But, II have noticed that the changes are not applied to the ingress gateway. Is it the right way to the these to helm values.yml?

`meshConfig:
  enablePrometheusMerge: true
  accessLogEncoding: JSON
  accessLogFile: "/dev/stdout"
  accessLogFormat: |
     {
        "accessLogFormat": "{
                            \"cfray\": \"%REQ(CF-RAY)%\",
                            \"authority\": \"%REQ(:AUTHORITY)%\",
                            \"start_time\": \"%START_TIME%\",
                            \"bytes_received\": \"%BYTES_RECEIVED%\",
                            \"bytes_sent\": \"%BYTES_SENT%\",
                            \"downstream_local_address\": \"%DOWNSTREAM_LOCAL_ADDRESS%\",
                            \"downstream_remote_address\": \"%DOWNSTREAM_REMOTE_ADDRESS%\",
                            \"duration\": \"%DURATION%\",                                    \"istio_policy_status\": \"%DYNAMIC_METADATA(istio.mixer:status)%\",
                            \"method\": \"%REQ(:METHOD)%\",
                            \"path\": \"%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%\",
                            \"protocol\": \"%PROTOCOL%\",
                            \"request_id\": \"%REQ(X-REQUEST-ID)%\",
                            \"requested_server_name\": \"%REQUESTED_SERVER_NAME%\",
                            \"response_code\": \"%RESPONSE_CODE%\",
                            \"response_flags\": \"%RESPONSE_FLAGS%\",
                            \"route_name\": \"%ROUTE_NAME%\",
                            \"start_time\": \"%START_TIME%\",
                            \"upstream_cluster\": \"%UPSTREAM_CLUSTER%\",
                            \"upstream_host\": \"%UPSTREAM_HOST%\",
                            \"upstream_local_address\": \"%UPSTREAM_LOCAL_ADDRESS%\",
                            \"upstream_service_time\": \"%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%\",
                            \"upstream_transport_failure_reason\": \"%UPSTREAM_TRANSPORT_FAILURE_REASON%\",
                            \"user_agent\": \"%REQ(USER-AGENT)%\",
                            \"x_forwarded_for\": \"%REQ(X-FORWARDED-FOR)%\",
                            \"my_custom_header\": \"%REQ(MY_CUSTOM_HEADER)%\"
                           }"
            }`

Thanks and Regards,
Ramesh

**Comment by howardjohn** [comment]
Those values should be configured when installing Istiod then they apply to the ingress gw. check the `istio` configmap - it it's not there then you likely set these when installing the gateway chart which does not take effect

**Comment by rameshar16** [comment]
Hi @howardjohn,
Thank you for your input.
I see the Istio config map is not having the mesconfig details. Do I need to reinstall the Istiod? I have added the gateways chart values.yml. Will the Istiod take these values from the gateway values.yml? Please suggest me on this.

Thanks and Regards,
Ramesh

**Comment by howardjohn** [comment]
No you need to set then on Istiod chart. It's not really a "reinstall"
since it's declarative, will just update the configmap

**Comment by rameshar16** [comment]
Thank you @howardjohn 
Now, I can see the logs in JSON format.

But, somehow the logs are still printing with the default logformat instead of the custom format which I mentioned above.
Thanks and Regards,
Ramesh

**Comment by douglas-reid** [comment]
This might be a case for recommending Telemetry API usage for updating workload-specific logging options.

**Comment by rameshar16** [comment]
Thank you @howardjohn @douglas-reid.
Now, I see the custom logformat is working fine after I removed the Pipeline (|).

Thanks and Regards,
Ramesh

**Comment by emalihin** [comment]
@rameshar16 how did you manage to configure it in helm? 1.13.2 istiod chart doesn't appear to support `meshConfig.accessLogEncoding` ?

**Comment by howardjohn** [comment]
`--set meshConfig.accessLogEncoding=JSON` should work in helm.

**Comment by emalihin** [comment]
thanks @howardjohn , I've noticed that `accessLogEncoding=JSON` gets injected into `istio` configMap with this set, and istiod picks it up as well. However this doesn't seem to have any effect on the ingressgateway logging format. Should `istio-proxy` container/Envoy pick up this configuration from `istiod`?

I'm also noticing that istio-proxy/Envoy starts with `info	FLAG: --log_as_json="false"` - a parameter that is present in `charts/gateways/ingress-gateway`, but not in `charts/gateway` which I'm using.

**Comment by howardjohn** [comment]
Yes, its dynamically configured in XDS. Access log files are a different
log than `log_as_json` which is just the main logs; access logs are treated
separately

**Comment by emalihin** [comment]
When I add `accessLogEncoding: JSON` to `istio` configmap I see `istiod` log:

```
2022-03-18T17:52:56.002091Z	info	mesh configuration updated to: {
...
    "accessLogEncoding": "JSON",
...
}
```

and i also observe istio-ingressgateway envoy process log `info	envoy main	shutting down parent after drain` a few seconds later. But then it just continues access logging as non-json text.

Could Telemetry API (which enabled access logging in my setup) be incompatible with this meshConfig?

**Comment by emalihin** [comment]
managed to configure access log via `meshConfig.extensionProviders`. Working example:

```
  values:
    meshConfig:
      extensionProviders:
      - name: envoy
        envoyFileAccessLog:
          path: "/dev/stdout"
          logFormat:
            labels:
              start_time: "%START_TIME%"
              source_host: "%HOSTNAME%"
              upstream_host: "%UPSTREAM_HOST%"
              remote_address: "%DOWNSTREAM_DIRECT_REMOTE_ADDRESS%"
              user_agent: "%REQ(USER-AGENT)%"
              host: "%REQ(:AUTHORITY)%"
              protocol: "%PROTOCOL%"
              bytes_rcvd: "%BYTES_RECEIVED%"
              request:
                request_method: "%REQ(:METHOD)%"
                request_path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
                request_time: "%DURATION%"
                request_xff: "%REQ(X-FORWARDED-FOR)%"
                request_id: "%REQ(X-REQUEST-ID)%"
              response:
                response_code: "%RESPONSE_CODE%"
                response_code_details: "%RESPONSE_CODE_DETAILS%"
                response_bytes_sent: "%BYTES_SENT%"
                response_flags: "%RESPONSE_FLAGS%"
                response_time: "%RESPONSE_DURATION%"
                response_upstream_time: "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%"
```
