### ISSUE TITLE
Disabling access logging through Telemetry API does not disable logging for TCP calls

### ISSUE THREAD

**Issue by rolandkool** [istio/istio#37723]
### Bug Description

When disabling the access logging through the Telemetry API, all HTTP calls stop being logged (as expected), but TCP calls are not.
For example, one of out workloads still logs outgoing calls to Google APIs (on port 443), Graphite (port 2003) and Consul (port 8300). All non-HTTP traffic.

The telemetry config to disable the logs looks like:
```
  accessLogging:
  - disabled: true
    providers:
    - name: envoy
```
Access logging has been configured with a custom format and encoding (JSON)

### Version

```prose
Istio ASM 1.12.4
```
