### ISSUE TITLE
Istio HTTP Automatic Protocol Selection Issue

### ISSUE THREAD

**Issue by Champ-Goblem** [istio/istio#37728]
### Bug Description

I seem to be experiencing an issue with HTTP/1 (H1) and HTTP/2 (H2) automatic protocol selection when externally exposing a service with Istio. Ideally what I would like to have is a service that can use H1 and H2 interchangeably depending on what the client supports in the initial request. So far all I have managed to get working is explicitly either H2 or H1 support through the appProtocol field of the service.

My test setup looks like so:

- I have a simple nodejs service with two open ports deployed as a pod in kubernetes
    - 8000 has a H2 listener
    - 8001 has a H1 listener
    
    ```
    const http2 = require('http2');
    const http = require('http');
    
    const serverHTTP2 = http2.createServer();
    
    serverHTTP2.on('stream', (stream, headers) => {
      console.log(`New request with: ${stream.httpVersion}`);
      stream.respond({
        'content-type': 'text/html; charset=utf-8',
        ':status': 200
      });
      stream.end('<h1>Hello World</h1>');
    });
    
    serverHTTP2.listen(8000);
    console.log(`HTTP2 listener on 8000`);
    
    const serverHTTP1 = http.createServer((req, res) => {
      console.log(`New request with: ${req.httpVersion}`);
      res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
      res.end('<h1>Hello World</h1>');
    });
    
    serverHTTP1.listen(8001);
    console.log(`HTTP1 listener on 8001`);
    ```
    
- There is a service pointing to this deployment, with two ports defined:

```
	ports:
  - name: p02
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: p03
    port: 8001
    protocol: TCP
    targetPort: 8001
```

- Two virtual services:

```
http:
  - headers:
      request:
        remove:
        - X-Envoy-Peer-Metadata
        - X-Envoy-External-Address
        - X-Envoy-Peer-Metadata-Id
      response:
        remove:
        - X-Envoy-Peer-Metadata
        - X-Envoy-External-Address
        - X-Envoy-Peer-Metadata-Id
    retries:
      attempts: 3
      retryOn: reset
    route:
    - destination:
        host: nodejs-http2
        port:
          number: 8000
```

and

```
http:
  - headers:
      request:
        remove:
        - X-Envoy-Peer-Metadata
        - X-Envoy-External-Address
        - X-Envoy-Peer-Metadata-Id
      response:
        remove:
        - X-Envoy-Peer-Metadata
        - X-Envoy-External-Address
        - X-Envoy-Peer-Metadata-Id
    retries:
      attempts: 3
      retryOn: reset
    route:
    - destination:
        host: nodejs-http2
        port:
          number: 8001
```

- A gateway that the virtual services point to:

```
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - *.domain.com
    port:
      name: tls
      number: 443
      protocol: HTTPS
    tls:
      credentialName: tls
      mode: SIMPLE
  - hosts:
    - *.domain.com
    port:
      name: redirect
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
```

- MTLS is enabled between services in the mesh

From my understanding, not defining the `appProtocol` field or a port name with the form `<proto>-<name>` should mean istio-proxy will detect the protocol automatically out of TCP/H1/H2. In this instance, it does not seem to be detecting the protocol correctly and downgrades it to H1 from the istio gateway:

```
❯ curl --http2 https://<H2-port-endpoint>
upstream connect error or disconnect/reset before headers. reset reason: protocol error
```

logs from ingressgateway:

```
GET / HTTP/2" 502 - via_upstream - "-" 0 87 9 9 "<ip>" "curl/7.81.0" "a48b0965-ffa1-49c5-9885-07e4e54a7918" "<domain>" "10.48.4.127:8000" outbound|8000||nodejs-http2.default.svc.cluster.local 10.48.2.41:47448 10.48.2.41:8443 <ip> <domain> -
```

logs from istio sidecar:

```
"- - -" 0 - - - "-" 2196 1871 5 - "-" "-" "-" "-" "10.48.4.127:8000" inbound|8000|| 127.0.0.6:49131 10.48.4.127:8000 10.48.2.41:47456 outbound_.8000_._.nodejs-http2.default.svc.cluster.local -
```

In the above case the sidecar does not seem to detect the protocol being used, it only starts showing the protocol when MTLS is disabled:

```
"GET / HTTP/1.1" 502 UPE upstream_reset_before_response_started{protocol_error} - "-" 0 87 2 - "<ip>" "curl/7.81.0" "e1d949ab-fa21-4c12-981d-defe0c50e486" "<domain>" "10.48.4.127:8000" inbound|8000|| 127.0.0.6:42295 10.48.4.127:8000 <ip> - default
```

So from the ingress gateway the protocol seems to have been downgraded from H2 to H1.

Setting the appProtocol field to H2 solves this issue:

```
❯ curl --http2 https://<H2-port-endpoint>
<h1>Hello World</h1>
```

but then this forces all connections to be H2 even if the clients are using H1, for example:

```
❯ curl --http1.1 https://<H1-port-endpoint>
upstream connect error or disconnect/reset before headers. reset reason: protocol error
```

Ingress gateway logs:

```
"GET / HTTP/1.1" 502 - via_upstream - "-" 0 87 10 9 "<ip>" "curl/7.81.0" "cfab6fe3-4284-4db5-9618-bf79b23797f6" "<domain>" "10.48.4.127:8001" outbound|8001||nodejs-http2.default.svc.cluster.local 10.48.3.250:40456 10.48.3.250:8443 <ip> <domain> -
```

Sidecar logs:

```
GET / HTTP/2" 502 UPE upstream_reset_before_response_started{protocol_error} - "-" 0 87 5 - "<ip>" "curl/7.81.0" "819715ed-d6c9-4c55-b3a8-0a6d73e52654" "<domain>" "10.48.4.127:8001" inbound|8001|| 127.0.0.6:49329 10.48.4.127:8001 <domain> - default
```

As the above demonstrates, it works when setting the appProtocol field of the service to the desired HTTP version, but is there a way to get this working without needing to set that? Perhaps I am missing something that is causing the HTTP/2 to be downgraded automatically to HTTP/1 inside of the mesh? We would also like to avoid setting `h2UpgradePolicy` to `UPGRADE` as this will break connections for other services deployed on our clusters.

### Version

```prose
Istio version: 1.12.4

Kubernetes version: 1.21.9-gke.300
```

### Additional Information

<details>
<summary>Istio Operator</summary>
<p>

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
      - name: "istio-ingressgateway"
        enabled: true
        k8s:
          hpaSpec:
            minReplicas: 3
            maxReplicas: 10
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: istio
                          operator: In
                          values:
                            - ingressgateway
                    topologyKey: kubernetes.io/hostname
          service:
            externalTrafficPolicy: Local
          tolerations:
          - effect: NoSchedule
            key: sandbox.gke.io/runtime
            operator: Equal
            value: gvisor

    pilot:
      enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2
          maxReplicas: 5
        tolerations:
        - effect: NoSchedule
          key: sandbox.gke.io/runtime
          operator: Equal
          value: gvisor

  # addonComponents:
  #   grafana:
  #     enabled: false
  #   prometheus:
  #     enabled: false

  values:
    global:
      # meshExpansion:
      #   enabled: true
      proxy:
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 64Mi
    telemetry:
      v2:
        prometheus:
          configOverride:
            inboundSidecar:
              metrics:
                - tags_to_remove:
                  - destination_app
                  - destination_cluster
                  - destination_principal
                  - destination_service_name
                  - destination_service_namespace
                  - source_app
                  - source_cluster
                  - source_principal
            outboundSidecar:
              metrics:
                - tags_to_remove:
                  - destination_app
                  - destination_cluster
                  - destination_principal
                  - destination_service_name
                  - destination_service_namespace
                  - source_app
                  - source_cluster
                  - source_principal
            gateway:
              metrics:
                - tags_to_remove:
                  - destination_app
                  - destination_cluster
                  - destination_principal
                  - destination_service_name
                  - destination_service_namespace
                  - source_app
                  - source_cluster
                  - source_principal


  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      holdApplicationUntilProxyStarts: true
    tcpKeepalive:
      time: 300s
```

</p>
</details>
