### ISSUE TITLE
Reduce Envoy CPU usage when disabling all metrics

### ISSUE THREAD

**Issue by rolandkool** [istio/istio#37724]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
As part of investigating envoys CPU overhead, I performed some loadtests with various Istio features turned on/off. One of the features I disabled was metrics collection.

Our Istio setup has been configured to disable the telemetry (Envoyfilters for stats collection) component:
```
    values
      telemetry:
        v2:
          prometheus:
            enabled: false
          stackdriver:
            enabled: false
```

To disable metrics through the Telemetry API, there are two options:
1. Don't configure anything for metrics (omitting the `metrics` parameter)
2. Configure metrics and explicitly disable everything:
```
  metrics:
  - overrides:
    - disabled: true
      match:
        metric: ALL_METRICS
        mode: CLIENT_AND_SERVER
    providers:
    - name: prometheus
```

If you have, like we do, a default metrics configuration in the `istio-system` namespace that sets a proper default for all workloads, option 1 is no longer an option if you want to disable metrics for a particular workload. Option 2 is the only way to do that.

However, option 1 actually does reduce the CPU overhead of Envoy significantly compared to option 2. My guess is that this is because option 2 still configures some envoyfilter to generate the metrics only to then drop all of them, while option 1 does not configure the proxy to have any envoyfilter for generating metrics.

An improvement could be that when all metrics are explicitly disabled using option 2, that it actually removes all configuration from Envoy so no CPU cycles are wasted on generating metrics that are to be dropped anyway.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
