### ISSUE TITLE
Service returning "503 upstream connect error or disconnect/reset before headers. reset reason: remote reset" after upgrading to 1.10.2

### ISSUE THREAD

**Issue by shahriak** [istio/istio#37739]
### Bug Description

We have upgraded istio to 1.10.2 from 1.9.4 and after upgrading, curling our service is returning 503 upstream connect error or disconnect/reset before headers. reset reason: remote reset. Our service is using http2

### Version

```prose
kubection version --short:
Client Version: v1.21.7
Server Version: v1.21.7

helm version --short
v3.3.4+ga61ce56

client version: 1.9.4
control plane version: 1.10.2-25c4362d87b9946d6b59d39bf21c6c8a192d060f
data plane version: 1.10.2 (132 proxies)
```

### Additional Information

I have verified that after downgrading back to istio 1.9.4, the service is giving expected response.

Our istio-operator spec:

```
  spec:
    hub: acr.azurecr.io/istio

    meshConfig:
      defaultConfig:
        terminationDrainDuration: "30s"
        # See details here https://github.com/istio/istio/issues/26923
        holdApplicationUntilProxyStarts: true
      h2UpgradePolicy: UPGRADE
      trustDomain: aks-ppe-wus2
    components:
      ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          env:
          - name: ISTIO_META_ROUTER_MODE
            value: "sni-dnat"
          - name: ISTIO_META_IDLE_TIMEOUT
            value: "15s"
          service:

          hpaSpec:
            minReplicas: 64
            maxReplicas: 200
            # NOTE: do not remove the parameters below. these are the defaults for this istio component. these were added because configmerge will 
            # turn hpaSpec into null if the optional parameters aren't set without it. if hpaSec becomes null, then it blows away all of these
            # values in the parent helm chart.
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: istio-ingressgateway
            metrics:
              - type: Resource
                resource:
                  name: cpu
                  targetAverageUtilization: 60
          resources:
            requests:
              cpu: "2"
              memory: 1Gi
            limits:
              cpu: "4"
              memory: 2Gi
          strategy:
            rollingUpdate:
              maxSurge: 100%
              maxUnavailable: 25%
          nodeSelector: { "ourapp.microsoft.com/role": "istio" }

          overlays:
            - kind: Deployment
              name: istio-ingressgateway
              patches:
                - path: spec.template.spec.dnsConfig
                  value:
                    options:
                      - name: single-request-reopen
                - path: spec.template.spec.topologySpreadConstraints
                  value:
                    - maxSkew: 1
                      topologyKey: kubernetes.io/hostname
                      whenUnsatisfiable: ScheduleAnyway 
                      labelSelector:
                        matchLabels:
                          app: istio-ingressgateway
            - kind: PodDisruptionBudget
              name: istio-ingressgateway
              patches:
                - path: spec.minAvailable
                  value: 50%

      pilot:
        enabled: true
        k8s:
          env:
          - name: PILOT_ENABLE_INBOUND_PASSTHROUGH
            value: "false"
          hpaSpec:
            minReplicas: 2
            maxReplicas: 10
          overlays:
            - kind: Deployment
              name: istiod
              patches:
                - path: spec.template.spec.dnsConfig
                  value:
                    options:
                      - name: single-request-reopen
      cni:

    values:
      global:
        multiCluster:
          enabled: true
          clusterName: aks-ppe-wus2
          globalDomainSuffix: "global"
          includeEnvoyFilter: true
        defaultNodeSelector:
          kubernetes.io/os: linux
        proxy:
          resources:
            requests:
              cpu: "1"
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 2Gi

      pilot:
        env:
          # pilot is replaced by istiod
          # Istio 1.3 added trust domain validation by default, but this breaks multi-trust domain scenarios, so we disable it
          PILOT_SKIP_VALIDATE_TRUST_DOMAIN: true

      # security:   # security field is deprecated in 1.6
        # By default Istio creates a self signed root certificate authority. If you are creating a multi-cluster mesh
        # (see Section 6), you should set this to false. This will tell Istio to look for your custom Root CA
        # certificate. If your mesh is single-cluster, feel free to omit this flag or set it to true.
        # selfSigned: false

      telemetry:
        v2:
          # if using mixer, we don't need new telemetry data flows
          enabled: true
      gateways:
        istio-ingressgateway:
          # preserve original client source IP, https://istio.io/latest/docs/tasks/security/authorization/authz-ingress/
          externalTrafficPolicy: Local
          ports:
          # We could enable this port if mtls is enabled on the all exposed ports but upstream load balancer requires an endpoint for health check
          # Istio/Envoy provides this port for default health check
          # - port: 15020
          #   targetPort: 15020
          #   name: status-port
          - port: 443
            targetPort: 32443
            name: https
          # This is to create 2 ingress gateway pods at minium if not speficied in "PlatformConfig.Deployment.IstioChartValues.Gateway.MinIngressReplicas" 
          # According to https://github.com/istio/operator, this is a pass-through API to helm values that we should avoid using in future. Validated "autoscaleMin" would be overwritten by hpaSpec -> minReplicas
          autoscaleMin: 2
          podAntiAffinityTermLabelSelector:
          - key: app
            operator: In
            values: istio-ingressgateway
            topologyKey: "kubernetes.io/os"
      cni:
        excludeNamespaces:
        - istio-system
        - kube-system
        logLevel: info

```

My service definition:

```
apiVersion: v1
kind: Service
metadata:
  name: mysvc
  labels:
    app: mysvc
  namespace: mysvc-ns
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      appProtocol: http2
      protocol: tcp
      name: http2
  selector:
    app: mysvc
```

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.gatewayName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: ingressgateway # use Istio's default ingress gateway
  servers:
  - port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: "{{ .Values.credentialName }}"
      minProtocolVersion: TLSV1_2
      cipherSuites:
        - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
    hosts:
    - "*"

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.virtualServiceName }}
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.gatewayName }}
  http:
  - match:
      - uri:
          prefix: /
    mirror:
        host: {{ template "mysvc.fullname" . }}.{{ .Values.namespace }}.svc.cluster.local
        subset: v2
    mirrorPercentage:
      value: {{ .Values.trafficShadow.percentage | default 1 }}
    route:
    - destination:
        # this should be either "service-name" (if it is in the current namespace)
        # or "service-name.namespace" if it is in a different namespace
        host: {{ template "mysvc.fullname" . }}.{{ .Values.namespace }}.svc.cluster.local
        subset: v1
        port: 
          number: 80
      weight: 100
	  
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mysvc-destination
  namespace: {{ .Values.namespace }}
spec:
  host: {{ template "mysvc.fullname" . }}
  subsets:
  - labels:
      version: v1
    name: v1
  - labels:
      version: v2
    name: v2
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
    connectionPool:
      http:
        h2UpgradePolicy: UPGRADE
```

**Comment by bianpengyuan** [comment]
Probably https://istio.io/latest/blog/2021/upcoming-networking-changes/

**Comment by shahriak** [comment]
@bianpengyuan I have set the env variable to false as one of the mitigation steps. Therefore, this change should not have any impact on the service..

```
          - name: PILOT_ENABLE_INBOUND_PASSTHROUGH
            value: "false"

```

**Comment by shahriak** [comment]
FYI, our service is configured to bind to all interfaces:
```

        public static IWebHostBuilder CreateWebHostBuilder(string[] args)
        {
            return WebHost.CreateDefaultBuilder(args)
	            .UseUnityServiceProvider(_container)
                .UseShutdownTimeout(TimeSpan.FromSeconds(30))
                .ConfigureKestrel(options =>
                {
                    // For k8s probe only, which doesn't support http2
                    **options.Listen(IPAddress.Any, 81,** 
                        listenOptions => listenOptions.Protocols = Microsoft.AspNetCore.Server.Kestrel.Core.HttpProtocols.Http1AndHttp2);

                    // Service port,
                    // according to https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-6.0#listenoptionsprotocols
                    // We have to use Http2 enum as TLS is terminated at istio gateway
                    **options.Listen(IPAddress.Any, 80,**
                        listenOptions => listenOptions.Protocols = Microsoft.AspNetCore.Server.Kestrel.Core.HttpProtocols.Http2);
                    options.Limits.MaxConcurrentConnections = 4000;
                    options.AllowSynchronousIO = true;
                    options.ConfigureHttpsDefaults(opt =>
                        opt.ClientCertificateMode =
                            ClientCertificateMode.AllowCertificate);
                })
```

**Comment by shahriak** [comment]
Here's our Gateway,VirtualService and DestinationRule resources for the service:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.gatewayName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: ingressgateway # use Istio's default ingress gateway
  servers:
  - port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: "{{ .Values.credentialName }}"
      minProtocolVersion: TLSV1_2
      cipherSuites:
        - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
    hosts:
    - "*"

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.virtualServiceName }}
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.gatewayName }}
  http:
  - match:
      - uri:
          prefix: /
    mirror:
        host: {{ template "mysvc.fullname" . }}.{{ .Values.namespace }}.svc.cluster.local
        subset: v2
    mirrorPercentage:
      value: {{ .Values.trafficShadow.percentage | default 1 }}
    route:
    - destination:
        # this should be either "service-name" (if it is in the current namespace)
        # or "service-name.namespace" if it is in a different namespace
        host: {{ template "mysvc.fullname" . }}.{{ .Values.namespace }}.svc.cluster.local
        subset: v1
        port: 
          number: 80
      weight: 100
	  
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mysvc-destination
  namespace: {{ .Values.namespace }}
spec:
  host: {{ template "mysvc.fullname" . }}
  subsets:
  - labels:
      version: v1
    name: v1
  - labels:
      version: v2
    name: v2
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
    connectionPool:
      http:
        h2UpgradePolicy: UPGRADE
```

**Comment by shahriak** [comment]
Can someone help with this issue? I also wanted to point out that we use statefulset deployment resource for our service:

```
{{ if .Values.statefulsetEnabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "mysvc.fullname" . }}
  labels:
    app: {{ template "mysvc.name" . }}
    chart: {{ template "mysvc.chart" . }}
    draft: {{ .Values.draft | default "draft-app" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  namespace: {{ .Values.namespace }}
spec:
  serviceName: {{ template "mysvc.name" . }}
  podManagementPolicy: Parallel
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "mysvc.name" . }}
      release: mysvc
  template:
    metadata:
      labels:
        app: {{ template "mysvc.name" . }}
        draft: {{ .Values.draft | default "draft-app" }}
        podRole: {{ .Values.podRole }}
        release: mysvc
        aadpodidbinding: scc
        version: v1
      annotations:
        buildID: {{ .Values.buildID | default "" | quote }}
        traffic.sidecar.istio.io/excludeInboundPorts: 52323,52325,52326
        traffic.sidecar.istio.io/includeOutboundIPRanges: 10.244.0.0/16,10.240.0.0/16,10.0.0.0/16
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: {{ template "mysvc.name" . }}  
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: mysvccommerce.microsoft.com/role
                operator: In
                values:
                - mysvc
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: http-probe
              containerPort: 81
              protocol: TCP
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /mysvc/health
              port: 81
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /mysvc/readiness
              port: 81
              scheme: HTTP
            periodSeconds: 8
            timeoutSeconds: 10
            successThreshold: 3
          startupProbe:
            failureThreshold: 100
            httpGet:
              path: /mysvc/readiness
              port: 81
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          env:
            - name: POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: XPanderVolume
              value: {{ .Values.xpandervolume }}
            - name: XPanderLogsVolume
              value: {{ .Values.xpanderLogsVolume }}
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.aspNetCoreEnvironment }}
            - name: XPanderCacheFileUrl
              value: {{ .Values.xpanderCacheFileUrl }}
            - name: XPanderMinCacheFiles
              value: {{ .Values.xpanderMinCacheFiles | quote }}
            {{- $root := . }}
            {{- range $ref, $values := .Values.secrets }}
            {{- range $key, $value := $values }}
            - name: {{ $ref }}_{{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "mysvc.fullname" $root }}-{{ $ref | lower }}
                  key: {{ $key }}
            {{- end }}
            {{- end }}
            - name: ROLE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['podRole']
            - name: CLUSTER
              value: {{ .Values.cluster }}
            - name: CLUSTER_REGION
              value: {{ .Values.clusterRegion }}
            - name: DOTNET_DiagnosticPorts
              value: /diag/port
            {{ if .Values.deployConfigmap }}
            - name: TargetDbFlipTimePath
              value: {{ .Values.configmapPath }}/{{ .Values.flipTimePath }}
            {{ end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          - mountPath: {{ .Values.xpandervolume }}
            name: xpandervolume
          - mountPath: {{ .Values.xpanderLogsVolume }}
            name: xpanderlogsvolume
          {{ if .Values.deployConfigmap }}
          - mountPath: {{ .Values.configmapPath }}
            name: config-volume
          {{ end }}
          - mountPath: /tmp
            name: tmp
          - mountPath: /diag
            name: diagnostics
        - args:
          - collect
          - --no-auth
          - --diagnostic-port
          - /diag/port
          - -u
          - http://*:52326
          command:
          - dotnet-monitor
          env:
          - name: Metrics__Providers__0__ProviderName
            value: Microsoft-AspNetCore-Server-Kestrel
          - name: Metrics__Providers__1__ProviderName
            value: Microsoft-AspNetCore-Http-Connections
          - name: Metrics__Providers__2__ProviderName
            value: System-Net-Security
          - name: Metrics__Providers__3__ProviderName
            value: System-Net-Http
          - name: Metrics__AllowInsecureChannelForCustomMetrics
            value: "true"
          - name: DotnetMonitor_DefaultProcess__Filters__0__Key
            value: ProcessName
          - name: DotnetMonitor_DefaultProcess__Filters__0__Value
            value: dotnet
          image: mcr.microsoft.com/dotnet/nightly/monitor:5.0.0-preview.8
          imagePullPolicy: Always
          name: dotnetmonitor
          ports:
          - containerPort: 52325
            protocol: TCP
          - containerPort: 52326
            protocol: TCP
          resources:
            limits:
              cpu: "2"
              memory: 1Gi
            requests:
              cpu: "1"
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /diag
            name: diagnostics
      volumes: 
      - name: xpanderlogsvolume
        persistentVolumeClaim:
          claimName: azure-managed-file
      {{ if .Values.deployConfigmap }}
      - name: config-volume
        configMap:
          name: targetdbflip
          items:
          - key: TargetDbFlipTime
            path: {{ .Values.flipTimePath }}
      {{ end }}
      - name: tmp
      - name: diagnostics
     {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
    {{- end }}
      dnsConfig:
        options:
        - name: single-request-reopen
      dnsPolicy: ClusterFirst
      nodeSelector:
        mysvccommerce.microsoft.com/role: mysvc
      shareProcessNamespace: true
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
  volumeClaimTemplates:
  - metadata: 
      name: xpandervolume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: managed-premium
      resources:
        requests:
          storage: {{ .Values.xpandervolumeSize }}
{{ end }}
```

**Comment by k-mckinney** [comment]
We encountered this issue after an upgrade to 1.10 with some .net core 3.1 applications using an EnvoyFilter for JSON<->gRPC transcoding.

This was what we did to fix it - added a ConfigMap and then annotated our pods like so:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-custom-bootstrap-config
data:
  custom_bootstrap.json: |
    {
      "layered_runtime": {
        "layers": [{
           "name": "static_layer_custom",
            "static_layer": {
              "envoy.reloadable_features.preserve_downstream_scheme": false
            }   
          }]
      }
    }
```

And the annotation we added to the pod was 
```yaml
sidecar.istio.io/bootstrapOverride: istio-custom-bootstrap-config
```
