### ISSUE TITLE
envoy -router: fetch failure: key 'hosts' missing or not an array from lines 82-88

### ISSUE THREAD

**Issue by nmnellis** [istio/istio#3773]
When running envoy in `router` configuration there is an error calling pilot cds
I believe the issue is with the following line below which is from and ExternalService

Envoy Router Error
```
[2018-02-26 02:19:15.999][15][warning][upstream] external/envoy/source/common/upstream/cds_subscription.cc:67] cds: fetch failure: key 'hosts' missing or not an array from lines 82-88

```

lines 82-88 from pilot `curl http://istio-pilot:8080/v1/clusters/istio-router/router~....`
```json
   {
    "name": "out.weather.com|external-HTTP-80",
    "service_name": "weather.com|external-HTTP-80",
    "connect_timeout_ms": 1000,
    "type": "strict_dns",
    "lb_type": "round_robin"
   },
```
External Service declaration
```yaml
apiVersion: config.istio.io/v1alpha2
kind: ExternalService
metadata:
  name: weather
  namespace: istio-system
spec:
  hosts:
  - weather.com
  ports:
  - number: 80
    name: http
    protocol: http
  discovery: "DNS"
```

Envoy args
```yaml
      - name: istio-router
        image: gcr.io/istio-testing/proxy:e905f919144177e6258b09588636782e4d55d582
        args:
        - proxy
        - router
        -...
```

**Comment by ijsnellf** [comment]
@nmnellis: There may be a bug in the external service implementation where we are not handling discovery DNS + no endpoints correctly. You might try explicitly adding an endpoint:
```yaml
...
   discovery: "DNS"
   endpoints:
     - address: "weather.com"
```
