### ISSUE TITLE
Kube-inject ignoring ignore annotation

### ISSUE THREAD

**Issue by costinm** [istio/istio#3774]
Maybe I'm too tired: but I ran 'istioctl kube-inject -f ... ' on the 'app t' from the 
integration tests ( converted to proper yaml ), as well as fortio-noistio - and I still
get it injected. 

Did the annotation change ? I tested against master - but if 0.6 is affected it would be a 
blocker. 

 ```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: t
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: t
        version: unversioned
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
```
