### ISSUE TITLE
mTLS egress from sidecar to wildcard domains

### ISSUE THREAD

**Issue by aopopov90** [istio/istio#37757]
Hello,

I am trying to configure the mesh (Istio 1.13.0) to originate mutual TLS with custom keys from an application sidecar to arbitrary domains.
I am using https://certauth.idrix.fr for testing as it displays details about the certificate presented by the client.

When I connect to this server from a laptop with keys specified explicitly it shows me the expected details, such as CN:
```
$ curl certauth.idrix.fr --key ./client.example.com.key --cert ./client.example.com.crt
{output omitted}
HTTP_USER_AGENT] => curl/7.64.1
[HTTP_HOST] => certauth.idrix.fr
[SSL_CLIENT_I_DN] => CN=example.com,O=example Inc.
[SSL_CLIENT_S_DN] => O=client organization,CN=client.example.com
[SSL_CLIENT_VERIFY] => FAILED:unable to verify the first certificate
[SSL_CLIENT_V_END] => Feb 25 08:14:46 2023 GMT
[SSL_CLIENT_V_START] => Feb 25 08:14:46 2022 GMT
{output omitted}
```

I have configured the following ServiceEntry and DestinationRule:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: certauth
spec:
  hosts:
  - "*.fr"
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http-port
    protocol: HTTP
    targetPort: 443
  - number: 443
    name: https-port
    protocol: HTTPS
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: certauth
spec:
  host: "*.fr"
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 80
      tls:
        mode: MUTUAL
        clientCertificate: /etc/istio/egress-app-credential/tls.crt 
        privateKey: /etc/istio/egress-app-credential/tls.key
```

Keys are discovered by Istio as expected:
```
$ istioctl proxy-config secret nginx-54d7c7dc6c-wbp46
RESOURCE NAME                                                                                   TYPE           STATUS     VALID CERT     SERIAL NUMBER                               NOT AFTER                NOT BEFORE
file-cert:/etc/istio/egress-app-credential/tls.crt~/etc/istio/egress-app-credential/tls.key     Cert Chain     ACTIVE     true           1                                           2023-02-25T08:14:46Z     2022-02-25T08:14:46Z
default                                                                                         Cert Chain     ACTIVE     true           186478327003397999897182656701792851598     2022-03-06T09:10:04Z     2022-03-05T09:08:04Z
ROOTCA                                                                                          CA             ACTIVE     true           175219670712651552893899012344499696062     2032-03-02T09:08:17Z     2022-03-05T09:08:17Z
```

However, when I call the destination from an application container I get an error:
```
$ kubectl exec nginx-54d7c7dc6c-wbp46 -c nginx -- curl -v http://certauth.idrix.fr
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 54.36.191.227:80...
* Connected to certauth.idrix.fr (54.36.191.227) port 80 (#0)
> GET / HTTP/1.1
> Host: certauth.idrix.fr
> User-Agent: curl/7.74.0
> Accept: */*
> 
upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER* Mark bundle as not supporting multiuse
< HTTP/1.1 503 Service Unavailable
< content-length: 190
< content-type: text/plain
< date: Sat, 05 Mar 2022 10:35:11 GMT
< server: envoy
< 
{ [190 bytes data]
100   190  100   190    0     0    646      0 --:--:-- --:--:-- --:--:--   646
* Connection #0 to host certauth.idrix.fr left intact
```

istio-proxy container shows a matching error:
```
$ kubectl logs nginx-54d7c7dc6c-wbp46 -c istio-proxy | tail -1
[2022-03-05T10:35:41.634Z] "GET / HTTP/1.1" 503 UF,URX upstream_reset_before_response_started{connection_failure,TLS_error:_268435703:SSL_routines:OPENSSL_internal:WRONG_VERSION_NUMBER} - "-" 0 190 248 - "-" "curl/7.74.0" "ebf2a1bf-a395-9dd0-9b6a-91653db46dcf" "certauth.idrix.fr" "54.36.191.227:80" outbound|80||*.fr - 54.36.191.227:80 172.17.0.4:42898 - default
```

Please, could you confirm if what I am trying to do (i.e. originate mTLS from a sidecar with custom certificates to a wildcard domain) is possible at all? If so I would highly appreciate suggestions on what I am missing.

Thank you.

Regards,
Anton
