### ISSUE TITLE
Chrome ERR_HTTP2_INADEQUATE_TRANSPORT_SECURITY error due to gateway TLS configuration

### ISSUE THREAD

**Issue by shonecyx** [istio/istio#37765]
### Bug Description

Access the gateway FQDN from chrome will get error `ERR_HTTP2_INADEQUATE_TRANSPORT_SECURITY` while curl and Safari work.

**Way to reproduce.**
1. Create the gateway and configure both maxProtocolVersion and minProtocolVersion to be TLSV1_2.
2. Configure the TLS 1.3 ciphers into cipherSuites and they are ahead of TLS 1.2 ciphers.
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: my-gw
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - www.example.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      cipherSuites:
      - AES128-GCM-SHA256
      - AES256-GCM-SHA384
      - ECDHE-ECDSA-AES128-GCM-SHA256
      - ECDHE-RSA-AES128-GCM-SHA256
      - ECDHE-ECDSA-AES256-GCM-SHA384
      - ECDHE-RSA-AES256-GCM-SHA384
      maxProtocolVersion: TLSV1_2
      minProtocolVersion: TLSV1_2
```
3. Access the FQDN through https and will get error as below:
![Screen Shot 2022-03-07 at 1 14 07 PM](https://user-images.githubusercontent.com/12857255/156972202-89453db0-2f2d-40a2-8e38-3ef210ec0596.png)

**Way to restore:**
Option 1: Delete the maxProtocolVersion or change it to TLSV1_3
Option 2: Delete the  tls1.2 ciphers or move them to the bottom of the list.

**Expected behavior:**
Should we remove the tls1.3 ciphers with error log if the maxProtocolVersion is TLSV1_2?

### Version

```prose
istio version: 1.10
kubectl version: 1.18.8
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
