### ISSUE TITLE
Improve WorkloadEntry label handling

### ISSUE THREAD

**Issue by boeboe** [istio/istio#37772]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

Today, there are two ways to integrate a VM into the mesh
1. WorkloadGroup + WorkloadEntry + ServiceEntry
2. WorkloadGroup + WorkloadEntry + Service (K8s Service)

Consider exposure of 1 application `vm-app-1`, which is deployed on two different VM's `vm-app-1-a` and `vm-app-1-b`. ServiceEntry has a dedicated field in its spec to define labels associated with that particular WorkloadEntry.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: vm-app-1-vm-app-1-a
  namespace: vm-namespace
spec:
  address: 10.132.0.54
  labels:
    app: vm-app-1
    instance-id: vm-app-1-a
  serviceAccount: vm-service-account-1
---
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: vm-app-1-vm-app-1-b
  namespace: vm-namespace
spec:
  address: 10.132.0.53
  labels:
    app: vm-app-1
    instance-id: vm-app-1-b
  serviceAccount: vm-service-account-1
```

**Method 1 : using ServiceEntry [working as expected]**

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: vm-app-1
  namespace: vm-namespace
spec:
  hosts:
    - vm-app-1.example.com
    - vm-app-1.vm-namespace.example.com
  location: MESH_INTERNAL
  ports:
    - name: http
      number: 8080
      protocol: HTTP
      targetPort: 8080
  resolution: STATIC
  workloadSelector:
    labels:
      app: vm-app-1
```

When we send traffic to `vm-app-1.example.com` or `vm-app-1.vm-namespace.example.com` , the traffic is correctly load balanced across both VMs `vm-app-1-a` and `vm-app-1-b`.

**Method 2 : using Service [not working as expected]**

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vm-app-1
  name: vm-app-1
  namespace: vm-namespace
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: vm-app-1
```

When we send traffic to `vm-app-1.vm-namespace` or `vm-app-1.vm-namespace.svc.cluster.local`, traffic is not load balanced and will only chose 1 VM destination.

We can solve this issue by adding extra labels on the original WorkloadEntry's as below.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: vm-app-1-vm-app-1-a
  namespace: vm-namespace
  labels:
    app: vm-app-1
    instance-id: vm-app-1-a
spec:
  address: 10.132.0.54
  labels:
    app: vm-app-1
    instance-id: vm-app-1-a
  serviceAccount: vm-service-account-1
---
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: vm-app-1-vm-app-1-b
  namespace: vm-namespace
  labels:
    app: vm-app-1
    instance-id: vm-app-1-b
spec:
  address: 10.132.0.53
  labels:
    app: vm-app-1
    instance-id: vm-app-1-b
  serviceAccount: vm-service-account-1
```

When we now send traffic to `vm-app-1.vm-namespace.svc.cluster.local` or `vm-app-1.vm-namespace.svc.cluster.local` , the traffic is correctly load balanced across both VMs `vm-app-1-a` and `vm-app-1-b`, because the labels are picked up correctly by the Service.

**Remark**

The fact that a WorkloadEntry defines its own set of extra labels under `spec.labels` and does not use the `metadata.labels` field directly, is confusing and error prone. As a kubernetes user, I would expect the WorkloadEntry to be an equivalent to a Pod and have the same label matching logic done by a Service.

**Affected product area (please put an X in all that apply)**

[x ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ x] Virtual Machine
[ ] Multi Control Plane

**Additional context**
