### ISSUE TITLE
Deployment cannot be created again with the same name in IstioOperator

### ISSUE THREAD

**Issue by tuhao1020** [istio/istio#37828]
### Bug Description

sample yaml (iop-test.yaml):
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: ingressgw-test
  namespace: istio-system
spec:
  components:
    ingressGateways:
    - enabled: true
      k8s:
        replicaCount: 1
        resources:
          limits:
            cpu: "0.2"
            memory: 200Mi
          requests:
            cpu: "0.2"
            memory: 200Mi
      label:
        app: ingressgw-test
        istio: tuhao-test-ingressgw-test
      name: ingressgw-test
      namespace: tuhao-test
  profile: empty
  revision: 1-10
  values:
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: false
        injectionTemplate: gateway
        replicaCount: 1
```

Reproduce steps:
1. `kubuectl apply -f iop-test.yaml`
2. wait for deployment and pod to be created
3. delete the deployment
4. repeat the first step

Expect:
deployment will be created again

Actual:
no deployment created.(you must change `ingressgw-test` to another name in iop-test.yaml) 

### Version

```prose
$ istioctl version
client version: 1.10.5
control plane version: 1.10.5-v3.7.5
data plane version: 1.10.5-v3.7.5 (10 proxies)
$ kubectl version --short
Client Version: v1.21.4
Server Version: v1.21.4
```
