### ISSUE TITLE
Resilient session affinity to rolling updates and pod scaling events

### ISSUE THREAD

**Issue by adriABC** [istio/istio#37910]
**Current situation**

As per the [documentation](https://istio.io/latest/docs/reference/config/networking/destination-rule/#LoadBalancerSettings-ConsistentHashLB):
The affinity to a particular destination host will be lost when one or more hosts are added/removed from the destination service.

This means that during a rolling update where a pod is created or after an autoscaling event (pod added or removed), all sticky sessions to existing pods will be lost.

Usually when you require sticky sessions is because once you perform an operation on a specific pod, later operations should be done in the same pod so the flow is not broken.

**Describe the feature request**

It would be nice to maintain the sticky session while the pod is alive, regardless if other pods are deleted or created.  

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
Envoy just recently added support for this. Note its very new and not exposed in core Istio APIs, and is not extensively validated by Istio. 

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: stateful
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.stateful_session
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.stateful_session.v3.StatefulSession
          session_state:
            name: envoy.http.stateful_session.cookie
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.http.stateful_session.cookie.v3.CookieBasedSessionState
              cookie:
                # Name of the cookie
                name: global-session-cookie
                # Path to set. Exercise caution here, as https://github.com/envoyproxy/envoy/issues/19655 may break persistence
                path: /
                # TTL of cookie. Can be set to 0 for session based
                ttl: 120s
```

can configure it though.

This uses an approach similar to nginx-ingress, using a HTTP cookie
