### ISSUE TITLE
Authz ALLOW with mix of http/TCP operations denies TCP 

### ISSUE THREAD

**Issue by nmittler** [istio/istio#37920]
### Bug Description

This was discovered while working on https://github.com/istio/istio/pull/37914

This policy will allow HTTP and GRPC, but deny TCP:

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ .to.Config.Service }}
spec:
  selector:
    matchLabels:
      "app": "{{ .to.Config.Service }}"
  action: ALLOW
  rules:
    - to:
        - operation: # HTTP
            ports: [ "18080", "18085" ]
            paths: [ "/allow" ]
            methods: [ "GET" ]
        - operation: # GRPC
            ports: [ "17070" ]
            paths: [ "/proto.EchoTestService/Echo" ]
            methods: [ "POST" ]
        - operation: # TCP
            ports: [ "19090" ]
      from:
        - source:
            principals: [ "cluster.local/ns/{{ .from.Config.Namespace.Name }}/sa/{{ .from.Config.Service }}" ]
```

This policy will properly allow all protocols:

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ .to.Config.Service }}
spec:
  selector:
    matchLabels:
      "app": "{{ .to.Config.Service }}"
  action: ALLOW
  rules:
    - to:
        - operation: # HTTP
            ports: [ "18080", "18085" ]
            paths: [ "/allow" ]
            methods: [ "GET" ]
      from:
        - source:
            principals: [ "cluster.local/ns/{{ .from.Config.Namespace.Name }}/sa/{{ .from.Config.Service }}" ]
    - to:
        - operation: # GRPC
            ports: [ "17070" ]
            paths: [ "/proto.EchoTestService/Echo" ]
            methods: [ "POST" ]
      from:
        - source:
            principals: [ "cluster.local/ns/{{ .from.Config.Namespace.Name }}/sa/{{ .from.Config.Service }}" ]
    - to:
        - operation: # TCP
            ports: [ "19090" ]
      from:
        - source:
            principals: [ "cluster.local/ns/{{ .from.Config.Namespace.Name }}/sa/{{ .from.Config.Service }}" ]
```

@howardjohn investigated and discovered this log line:

```
skipped rule ns[echo-1-80867]-policy[c]-rule[0] on TCP filter chain: ":method" is HTTP only
```

This implies that when a TCP operation is within the same `to` as an HTTP operation, it will be ignored.

I don't believe this is a vulnerability, since it will end up denying more than it should.

### Version

```prose
head
```

**Comment by howardjohn** [comment]
If we look at an indivual chunk:
```
        - operation: # GRPC
            ports: [ "17070" ]
            paths: [ "/proto.EchoTestService/Echo" ]
            methods: [ "POST" ]
```

I think that should clearly be included or not included. Just dropping the HTTP parts would make it too broad

But if we look at two chunks:
```
    - to:
        - operation: # GRPC
            ports: [ "17070" ]
            paths: [ "/proto.EchoTestService/Echo" ]
            methods: [ "POST" ]
    - to:
        - operation: # TCP
            ports: [ "19090" ]
```

we current take them ALL or NONE. I would think we can just take the chunks that do work (eg the 19090 rule).

Mostly just rephrasing the original issue
