### ISSUE TITLE
Is External authorization able to monitor internal traffic ?  

### ISSUE THREAD

**Issue by dabing1986** [istio/istio#37966]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Hi Recently we are trying to build a external authorization model followed by this link 
https://istio.io/latest/docs/tasks/security/authorization/authz-custom/
We notice that by config the authorization on the app istio-ingressgateway it will make sure all the request outside of the cluster will be redirected to external auth server. but we also want to control the A&A within the cluster.
meaning service A will consume service B . this request will also redirect to external auth server. 

How can we do that ? 

We thought the by changing the name space and matchLabels we can apply the auth internally 
for example 

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ext-authz-internal-01
  namespace: our own namespace 
spec:
  selector:
    matchLabels:
      auth: authz
  action: CUSTOM
  provider:
    name: "ext-authz-http"
  rules:
  - to:
    - operation:
    - 
```
but using label doesn't work and by changing the name space all internal request become 403 and didn't even handled by authz . 

Do you know where is the problem is ? 

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
