### ISSUE TITLE
Standalone istio gateway 503 errors

### ISSUE THREAD

**Issue by nmnellis** [istio/istio#3798]
I have a standalone gateway deployed but it is unable to route to internal or external services despite all configuration looking correct. Each call returns `503 Service Unavailable`. the below example should route `my-subdomain.weather.com` to `dog.ceo`(a public api http://dog.ceo/api/breeds/list/all)

Gateway deployment
```yaml
      - name: istio-ingress
        image: gcr.io/istio-testing/proxy:e905f919144177e6258b09588636782e4d55d582
        args:
        - proxy
        - router
        - -v
        - "8"
        ....
        - --serviceCluster
        - istio-ingress
        ....
```

External Service for public api - http://dog.ceo/api/breeds/list/all
```yaml
apiVersion: config.istio.io/v1alpha2
kind: ExternalService
metadata:
  name: dogs
  namespace: istio-system
spec:
  hosts:
  - dog.ceo
  endpoints:
  - address: dog.ceo
  ports:
  - number: 80
    name: http
    protocol: http
  discovery: "DNS"
```

RouteRule 
```yaml
apiVersion: config.istio.io/v1alpha2
kind: V1alpha2RouteRule
metadata:
  name: dogs
  namespace: istio-system
spec:
  hosts:
  - my-subdomain.weather.com
  gateways:
  - istio-ingress
  http:
  - route:
    - destination:
        name: dog.ceo
```

Gateway Config
```yaml
apiVersion: config.istio.io/v1alpha2
kind: Gateway
metadata:
  name: istio-ingress
  namespace: istio-system
spec:
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - my-subdomain.weather.com
```
** Envoy Debugging **
Routes
```
root@istio-ingress-5f46f7d5dd-vs4ff:/# curl localhost:15000/routes
[
{
"version_info": "hash_8ea159153040a222",
"route_config_name": "80",
"config_source": {
 "api_config_source": {
  "cluster_names": [
   "rds"
  ],
  "refresh_delay": "10s"
 }
}
,
"route_table_dump": {
 "name": "80",
 "virtual_hosts": [
  {
   "name": "istio-ingress|80|my-subdomain.weather.com",
   "domains": [
    "my-subdomain.weather.com:80",
    "my-subdomain.weather.com"
   ],
   "routes": [
    {
     "match": {
      "prefix": "/"
     },
     "route": {
      "cluster": "out.dog.ceo|http",
      "timeout": "0s"
     },
     "decorator": {
      "operation": "dogs"
     }
    }
   ]
  }
 ]
}

}
]
```
Clusters
```sh
root@istio-ingress-5f46f7d5dd-vs4ff:/# curl localhost:15000/clusters | grep out.dog.ceo
out.dog.ceo|external-HTTP-80::default_priority::max_connections::1024
out.dog.ceo|external-HTTP-80::default_priority::max_pending_requests::1024
out.dog.ceo|external-HTTP-80::default_priority::max_requests::1024
out.dog.ceo|external-HTTP-80::default_priority::max_retries::3
out.dog.ceo|external-HTTP-80::high_priority::max_connections::1024
out.dog.ceo|external-HTTP-80::high_priority::max_pending_requests::1024
out.dog.ceo|external-HTTP-80::high_priority::max_requests::1024
out.dog.ceo|external-HTTP-80::high_priority::max_retries::3
out.dog.ceo|external-HTTP-80::added_via_api::true
out.dog.ceo|external-HTTP-80::217.70.180.131:80::cx_active::0
out.dog.ceo|external-HTTP-80::217.70.180.131:80::cx_connect_fail::0
out.dog.ceo|external-HTTP-80::217.70.180.131:80::cx_total::0
out.dog.ceo|external-HTTP-80::217.70.180.131:80::rq_active::0
out.dog.ceo|external-HTTP-80::217.70.180.131:80::rq_error::0
out.dog.ceo|external-HTTP-80::217.70.180.131:80::rq_success::0
out.dog.ceo|external-HTTP-80::217.70.180.131:80::rq_timeout::0
out.dog.ceo|external-HTTP-80::217.70.180.131:80::rq_total::0
out.dog.ceo|external-HTTP-80::217.70.180.131:80::health_flags::healthy
out.dog.ceo|external-HTTP-80::217.70.180.131:80::weight::1
out.dog.ceo|external-HTTP-80::217.70.180.131:80::region::
out.dog.ceo|external-HTTP-80::217.70.180.131:80::zone::
out.dog.ceo|external-HTTP-80::217.70.180.131:80::sub_zone::
out.dog.ceo|external-HTTP-80::217.70.180.131:80::canary::false
out.dog.ceo|external-HTTP-80::217.70.180.131:80::success_rate::-1
```

Access log
```
[2018-02-27T01:50:16.619Z] "GET /api/breeds/list/all HTTP/1.1" 503 NR 0 0 0 - "174.82.221.133, 172.28.98.210" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36" "ed149258-e06b-980c-a0d5-269587263600" "my-subdomain.weather.com" "-"

```
