### ISSUE TITLE
missing cluster when enable `PILOT_FILTER_GATEWAY_CLUSTER_CONFIG`

### ISSUE THREAD

**Issue by zirain** [istio/istio#37997]
### Bug Description

- install istio with istioctl and following iop:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    pilot:
      k8s:
        env:
          - name: PILOT_FILTER_GATEWAY_CLUSTER_CONFIG
            value: "true"
  meshConfig:
    accessLogFile: /dev/stdout
    extensionProviders:
    - name: otel
      envoyOtelAls:
        service: otel-collector.istio-system.svc.cluster.local
        port: 4317
    defaultProviders:
      accessLogging:
      - otel
```
- create `httpbin` and expose with gateway
```shell
kubectl apply -f samples/httpbin/httpbin.yaml
kubectl apply -f samples/httpbin/httpbin-gateway.yaml
```
- access from ingressgateway receive warn log from pod

```console
2022-03-18T06:43:55.848204Z	warn	validation	found invalid extension provider (can be ignored if the given extension provider is not used): invalid extension provider otel: unsupported provider: &{service:"otel-collector.istio-system.svc.cluster.local" port:4317 } of type *v1alpha1.MeshConfig_ExtensionProvider_EnvoyOtelAls

```

### Version

```prose
client version: 1.14-dev
control plane version: 1.14
data plane version: 1.14-dev (4 proxies)
```
