### ISSUE TITLE
ArgoCD fails to connect to Redis when setting Istio with mTLS STRICT mode

### ISSUE THREAD

**Issue by sdargutev** [istio/istio#38019]
Hello, 
I am trying to get ArgoCD to run with Istio with mTLS mode STRICT. I installed both Istio and ArgoCD using their respective Helm charts.
This is my setup:
All ArgoCD related stuff is running on the namespace `argocd`, including the Redis instance that comes with it. 
All pods have Istio proxies present in them.

It works fine as long as the mTLS mode is not STRICT.  When I set it to STRICT the argocd servers cannot connect to Redis anymore. I get the following error in the `wait-for-redis` container: 
![image](https://user-images.githubusercontent.com/21322759/159121430-f7cfa35d-582c-4ddc-b49f-59fc8b2206a1.png)

Here are the setups that I tried with to solve the issue:

I added the following port entry in the Istio Gateway Helm chart values. This is the Redis service port and protocol for Redis as defined in its service. 
```
  - name: tcp-redis
    port: 6379
    protocol: TCP
    targetPort: 6379
```

Here are my ingressgateway, virtual service, and destination rule setups.
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingress-gateway-configuration
  namespace: argocd
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      number: 6379
      name: tcp-redis
      protocol: TCP
    hosts:
    - "*"
   ```
```
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: argo-cd-virtual-service
  namespace: argocd
spec:
  hosts:    
    - "*" 
  gateways:
    - ingress-gateway-configuration
  tcp:
  - match:
    - port: 6379
    route:
    - destination:
        host: argo-cd-redis-master.argocd.svc.cluster.local
        port:
          number: 6379
```
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  namespace: argocd
  name: argo-cd-destination-rule
spec:
  host: argo-cd-redis-master.argocd.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL # also tried with SIMPLE, but yielded the same result
```

Here is a screenshot of all the services:

![image](https://user-images.githubusercontent.com/21322759/159121309-bd8fe90c-4a88-476f-9527-b41a57177a7d.png)

Is there something I am missing? 

Any help would be greatly appreciated! Thank you!
