### ISSUE TITLE
withoutHeaders can't match the condition: Request does NOT have authority X 

### ISSUE THREAD

**Issue by penghuazhou** [istio/istio#38059]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
VirtualService match the head that not equal "authority:prefix: stable".
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
  namespace: istio-ryanzhou
spec:
  hosts:
  - "*"
  gateways:
  - bookinfo-gateway
  http:
  - match:
    - authority:
        prefix: stable
      withoutHeaders:
        content-type:
          prefix: application/grpc
    route:
    - destination:
        host: productpage
        port:
          number: 9080
```

**Describe alternatives you've considered**
I want to match http request that authority not euqal 'stable', but it can not support. 

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
