### ISSUE TITLE
Sidecars hammering coreDNS for ServiceEntries with the same address

### ISSUE THREAD

**Issue by jmunozro** [istio/istio#38102]
### Bug Description

We want to create some ServiceEntries that represent workloads located in other clusters, so we must route them through the ingress gateway of those clusters. In AWS we never get an ip for the LoadBalancer external ip, so there is no way to workaround this.

**Steps to reproduce:**

First install istio with meta_dns options, so we couald expect the dns resolution to happen in the istio pilot dns, and not in coredns

```yaml
istioctl install -y -n istio-system -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: control-plane
spec:
  profile: default
  meshConfig:
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
    enablePrometheusMerge: true
EOF
```

Activate logs for coredns editing the configmap coredns in the kube-system namespace:
```yaml
k get cm -n kube-system coredns -oyaml
apiVersion: v1
data:
  Corefile: |
    .:53 {
        log
        ...
```

You can also increase the dns log in any of the sidecars (or in the gateway), to be able to see the increase in dns queries:
```bash
istioctl pc log -n istio-system deploy/istio-ingressgateway --level dns:trace
```

Keep another console monitoring the dns queries:
```bash
watch -n 1 "kubectl logs -n kube-system deploy/coredns |grep amazonaws|wc -l"
```

Now create some ServiceEntries that are workloads located in other clusters:
```yaml
for i in {1..50};
do
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: reviews${i}.default.svc.cluster2.global
  namespace: istio-system
spec:
  endpoints:
  - address: acbdf5f73d1c2433194c28ea19d2a84a-d2d8d061a683f970.elb.eu-west-1.amazonaws.com
    labels:
      app: reviews
      version: v3
    ports:
      http: 15443
  - address: acbdf5f73d1c2433194c28ea19d2a84a-d2d8d061a683f970.elb.eu-west-1.amazonaws.com
    labels:
      app: reviews
      version: v1
    ports:
      http: 15443
  - address: acbdf5f73d1c2433194c28ea19d2a84a-d2d8d061a683f970.elb.eu-west-1.amazonaws.com
    labels:
      app: reviews
      version: v2
    ports:
      http: 15443
  hosts:
  - reviews${i}.default.svc.cluster2.global
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 9080
    protocol: HTTP
  resolution: DNS
EOF
done
```

You can see now that the number of dns request is `3x50` every `60s`. 60s is TTL of AWS records that can't be changed. All dns queries are identical, and executed all at once every 60s.

The real issue comes when you try to scale, adding some workloads to the mesh. Every new sidecar will contribute with `3x50 dns queries every 60s`, so eventually the coredns becomes the bottleneck:

```bash
kubectl create ns team1
kubectl label ns team1 istio-injection=enabled
kubectl create -n team1 -f https://github.com/istio/istio/raw/master/samples/httpbin/httpbin.yaml
kubectl scale -n team1 --replicas=15 deploy/httpbin 
```

It would be nice to have the pilot dns resolving these queries, so they never reach the coredns of the cluster.
As an alternative, it would be nice if we can remove the repetitions from the envoy cluster in the generated snapshot:
```yaml
load_assignment:
  cluster_name: reviews12.default.svc.cluster2.global
  endpoints:
  - lb_endpoints:
    - endpoint:
        address:
          socket_address:
            address: acbdf5f73d1c2433194c28ea19d2a84a-d2d8d061a683f970.elb.eu-west-1.amazonaws.com
            port_value: 15443
    - endpoint:
        address:
          socket_address:
            address: acbdf5f73d1c2433194c28ea19d2a84a-d2d8d061a683f970.elb.eu-west-1.amazonaws.com
            port_value: 15443
    - endpoint:
        address:
          socket_address:
            address: acbdf5f73d1c2433194c28ea19d2a84a-d2d8d061a683f970.elb.eu-west-1.amazonaws.com
            port_value: 15443
```
This would at least reduce the impact, an envoy does a different dns query for every endpoint

### Version

```prose
$ istioctl version
client version: 1.13.2
control plane version: 1.13.2
data plane version: 1.13.2 (23 proxies)
$ kubectl version --short
Client Version: v1.23.4+k3s1
Server Version: v1.23.4+k3s1
```

**Comment by ramaraochavali** [comment]
ServiceEntries of type DNS are resolved by Envoy proxy - not by Istio because those are typically non mesh dns endpoints (that is the reason you are creating it as SE)

**Comment by howardjohn** [comment]
https://preliminary.istio.io/latest/docs/ops/configuration/traffic-management/dns/ explains some of this

**Comment by jmunozro** [comment]
Thanks you both for your responses. I get your point and I will try this workaround:
_Switch to resolution: NONE to avoid proxy DNS lookups entirely. This is suitable for many use cases._

However, I don't fully understand why a ServiceEntry like this is considered _non mesh dns endpoint_
```
kind: ServiceEntry
metadata:
  name: reviews.default.svc.cluster2.global
  namespace: istio-system
spec:
  hosts:
  - reviews.default.svc.cluster2.global
  location: MESH_INTERNAL
  resolution: DNS
```

I would expect `ISTIO_META_DNS_CAPTURE` to cover this case.

**Comment by rinormaloku** [comment]
Can we add the following option for a service entry:

```
 resolution: LOCAL_DNS_PPROXY
 ```
 
 And then have the ability to configure envoyproxy to resolve said endpoint through the local Proxy?

**Comment by howardjohn** [comment]
The DNS proxy would cache just as often as Envoy does (based on TTL) even if we did that, so it's not clear what benefits it would bring

**Comment by rinormaloku** [comment]
@howardjohn imagine if I want to route a query to another API Gateway, that routes based on the SNI. I would create sth like:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: typicode
  namespace: istio-system
spec:
  hosts:
  - app1.typicode.com
  - app2.typicode.com
  endpoints:
  - address: jsonplaceholder.typicode.com
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL
```

This would generate the following envoy config:

```
  - cluster:
      '@type': type.googleapis.com/envoy.config.cluster.v3.Cluster
      load_assignment:
        cluster_name: outbound|80||app1.typicode.com
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: jsonplaceholder.typicode.com
                  port_value: 80
  - cluster:
      '@type': type.googleapis.com/envoy.config.cluster.v3.Cluster
      load_assignment:
        cluster_name: outbound|80||app2.typicode.com
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: jsonplaceholder.typicode.com
                  port_value: 80
```

This will cause envoy to resolve DNS for the same address `jsonplaceholder.typicode.com`, twice. The more hosts that point to the same address the more DNS queries.

However, when redirecting this to the local DNS proxy, subsequent resoutions would be served from the local DNS proxy cache.
