### ISSUE TITLE
Support default cluster in VirtualService

### ISSUE THREAD

**Issue by shonecyx** [istio/istio#38105]
**Describe the feature request**

This feature is regarding VirtualService routing default cluster. Assume we configured several paths to forward traffic to different upstream clusters:

www.example.com/a to service-a, /a will forward traffic to upstream cluster svc-a
www.example.com/b to service-n, /b will forward traffic to upstream cluster svc-b

When there is no healthy endpoint in upstream cluster svc-a or svc-b, the request should be forwarded to the default cluster, for example svc-homepage.

Here is the sample spec:

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: example-vs
spec:
  gateways:
  - example
  hosts:
  - www.example.com
  http:
  - match:
    - port: 443
      uri:
        prefix: /a
    name: forward-to-svc-a
    route:
    - destination:
        host: svc-a
        port:
          number: 443
  - match:
    - port: 443
      uri:
        prefix: /b
    name: forward-to-svc-b
    route:
    - destination:
        host: svc-b
        port:
          number: 443       
  defaultCluster: svc-homepage

```
This feature is very helpful for the L7 public traffic, instead of responding user with `503 no healthy upstream`, redirect to the default cluster(i.e. home page) is more user friendly.

**Describe alternatives you've considered**

The propose solution is that we can add a new filed `defaultCluster` in the VirtualService spec and leverage Envoy endpoint priority level to implement: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/priority.html

We can introduce a `defaultCluster` in the VirtualService, the `defaultCluster` will be used for setting the fallback endpoints, if it's not empty, the route destination will have 2 sets of endpoints, one is the configured destination in the route, another one is the fallback endpoints in the `defaultCluster`.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
Same effect can be achieved by adding a wildcard match. 

```
    route:
    - destination:
        host: svc-homepage
        port:
          number: xxx
```

**Comment by shonecyx** [comment]
@hzxuzhonghu 
I tried the wildcard match but no luck
```
spec:
  gateways:
  - sample-gw
  hosts:
  - www.example.com
  http:
  - match:
    - port: 443
      uri:
        prefix: /a
    name: test-a
    route:
    - destination:
        host: svc-a
        port:
          number: 8082
  - name: test-default
    route:
    - destination:
        host: svc-default
        port:
          number: 8082
```
If there is no healthy endpoint in `svc-a`; access https://www.example.com/a will get `503 no healthy upstream` instead of redirect to `svc-default`

**Comment by hzxuzhonghu** [comment]
Oh, it is expected.  the example means those not matched requests are routed to svc-default

**Comment by shonecyx** [comment]
@hzxuzhonghu 
What we expect is that, if endpoints in svc-a all goes down, then it should fallback to the svc-default, like the homepage for better user experience. User would be redirected to the homepage instead of the `503 no healthy upstream`.

And this is doable by leveraging https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/priority.html, we can specify the default cluster either through VirtualService annotation i.e. `traffic.istio.io/defaultCluster` or specify it in the VirtualService spec.

**Comment by hzxuzhonghu** [comment]
Not exactly, currently locality load balancing implementation is based on Priority levels, different priority level endpoints are within a cluster. 
Also the fail over happened not when p0 endpoints all down, as you see there is a Overprovisioning Factor[¶](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/overprovisioning#overprovisioning-factor)

**Comment by shonecyx** [comment]
@hzxuzhonghu 
It's similar mechanism with locality load balancing. For each VirtualService route destination, we can append another set of endpoints which are from the fallback service, the default/fallback cluster(P1). So the P0 endpoints are from the original service and if they goes down, then traffic will be forwarded to the default cluster(P1).

The default Overprovisioning factor is 140 which means only if less than 71% of the P0 endpoints are healthy, will the default cluster(P1) start taking traffic. We can make the Overprovisioning factor configurable through annotation, i.e. set it 2000, then the default cluster(P1) will be used when the P0 cluster's healthy member count is less than 5%.

**Comment by hzxuzhonghu** [comment]
I guess the requirement is from spring cloud users, once I heard such one too. Personally, I'd like to see such a feature.

**Comment by shonecyx** [comment]
@hzxuzhonghu  
It's actually from the hardware loadbalancer to Istio migration. This is the default behavior in the hardware loadbalancer which is more user friendly especially for the public traffic.

And I think we have two options to do that:
1. By adding an annotation `traffic.istio.io/defaultCluster` in VirtualService, so we don't need Istio api change.
2. Update the VirtualService spec to add the `defaultCluster` filed.

I would like to make this a generic feature and happy to contribute.

**Comment by hzxuzhonghu** [comment]
Seems we need aggregate cluster to satisfy this feature. Kind of remember some one proposed aggregate cluster before.

**Comment by hzxuzhonghu** [comment]
We have two incentives: one from spring cloud, one from hardware loadbalancer. 
So i think we can extend our capabilities. 
A coarse thought is to add a fall back destination to `HTTPRouteDestination` like

```golang
type HTTPRouteDestination struct {

	// Destination uniquely identifies the instances of a service
	// to which the request/connection should be forwarded to.
	Destination *Destination `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`

        FallBackDestination *Destination

	Weight int32 `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`

	Headers *Headers `protobuf:"bytes,7,opt,name=headers,proto3" json:"headers,omitempty"`
}
```

**Comment by hzxuzhonghu** [comment]
cc @howardjohn @ramaraochavali

**Comment by ramaraochavali** [comment]
Yeah. It is more of an aggregated cluster and we can control over provisioning factor internally

**Comment by howardjohn** [comment]
Can we reuse the existing failover in Destination Rule instead of creating a new mechanism?

**Comment by shonecyx** [comment]
@howardjohn 
The existing failover in Destination Rule doesn't fit for this case very well and there are some downsides:
1. Need to configure the Destination Rule for each route destination. For Ingress Gateway case there might be hundreds of routes and will need to create hundreds of DRs.
2. It has dependency on Outlier detection
3. This is actually not region failover but failover to same region different workloads/services, the failover is similar as:
```
failover:
  - from: region1.svc-a
    to: region1.svc-homepage
```
So ideally the default cluster should be at VirtualService level, for example we can still leverage the wildcard mach(default route) but we can introduce another flag to enable this fallback mechanism.
```
    route:
    - destination:
        host: svc-homepage
        port:
          number: xxx
```

**Comment by howardjohn** [comment]
Sorry I wasn't clear, I wasn't suggesting that the current API can
implement this use case exactly as-is. But mixing backend selection and
routing is not the right API choice, IMO.

**Comment by shonecyx** [comment]
@howardjohn 
Essentially it's the failover capability by leveraging Envoy priority level. Difference is that, one is for locality failover within same service across different regions and another is the specified fallback service and failover to different service.
What is your suggestion to support this case?

**Comment by shonecyx** [comment]
@howardjohn  Is it possible to introduce an annotation `traffic.istio.io/defaultCluster` in VirtualService to support this feature? Thus we don't need api change and it can be backward compatible.

**Comment by howardjohn** [comment]
I am fundamentally against exposing this mechanism as part of virtual service. It belongs as part of the backend configuration - Service, DestinationRule, etc. VirtualService is just about picking which service to connect to; endpoint selection should be independent.

**Comment by shonecyx** [comment]
> We have two incentives: one from spring cloud, one from hardware loadbalancer. So i think we can extend our capabilities. A coarse thought is to add a fall back destination to `HTTPRouteDestination` like
> 
> ```go
> type HTTPRouteDestination struct {
> 
> 	// Destination uniquely identifies the instances of a service
> 	// to which the request/connection should be forwarded to.
> 	Destination *Destination `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
> 
>         FallBackDestination *Destination
> 
> 	Weight int32 `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
> 
> 	Headers *Headers `protobuf:"bytes,7,opt,name=headers,proto3" json:"headers,omitempty"`
> }
> ```

@howardjohn  would this proposal address your concern? Then we can configure at DR level. But the cons is that, if we have thousands of routes to different upstream cluster, we'll need to configure thousands of DRs and fallback to the same default cluster.

**Comment by shonecyx** [comment]
> That proposal seems to put it in Virtual service?

Yes, it's still in VirutalService.  Actually we have similar requirement in Contour and what we did was adding the default_cluster into IngressRoute directly.
```
  route_configuration:
    default_cluster: foo-svc
    default_cluster_port: "80"
```
It's kind of like weighted base routing, we can specify different clusters for traffic steering in VirtualService.

**Comment by howardjohn** [comment]
As mentioned in https://github.com/istio/istio/issues/38105#issuecomment-1095651333, I don't believe VirtualService is the right place for this.

**Comment by shonecyx** [comment]
> As mentioned in [#38105 (comment)](https://github.com/istio/istio/issues/38105#issuecomment-1095651333), I don't believe VirtualService is the right place for this.

@howardjohn 

What about DestinationRule? There is already failover mechanism in DestinationRule but just for locality, is it possible to extend it for default cluster? For example just add `defaultService` in the `failover` field.
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: helloworld
spec:
  host: helloworld.sample.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
      localityLbSetting:
        enabled: true
        failover:
          - defaultService: homepage.sample.svc.cluster.local
```

**Comment by l8huang** [comment]
Not sure if `fallback` is the expected behavior, because the feature request mentioned that:
> **When there is no healthy endpoint** in upstream cluster svc-a or svc-b, the request should be forwarded to the default cluster.

Using Envoy Aggregate Cluster with a large enough overprovisioning_factor value can archive the fallback effect.

Looks like defining the failover destination in DestinationRule's [LoadBalancerSettings](https://istio.io/latest/docs/reference/config/networking/destination-rule/#LoadBalancerSettings) could be a better choice:

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: helloworld
spec:
  host: helloworld.sample.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
      failover:
        failoverFactor: 5 #  when healthy endpoint lower than this percentage, start to failover;
                                     # this is used to calculate Aggregate Cluster's primary cluster's overprovisioning_factor
        destination:
          host: homepage.sample.svc.cluster.local
          subset: v2
          port:
            number: 8080
```

When `failover` is defined, the outbound cluster can be generated as an Envoy Aggregate Cluster, with native destination as primary cluster, and the failover destination as Secondary cluster.
