### ISSUE TITLE
Failed to convert protobuf message to JSON string: INTERNAL:Invalid type URL, unknown type: envoy.extensions.filters.network.rocketmq_proxy.v3.RocketmqProxy

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#38147]
### Bug Description

applied a envoyfilter about rocketmq_proxy,I got
Failed to convert protobuf message to JSON string: INTERNAL:Invalid type URL, unknown type: envoy.extensions.filters.network.rocketmq_proxy.v3.RocketmqProxy

my envoyfilter is:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: rocketmq
spec:
  workloadSelector:
    labels:
      name: rocketmq
  configPatches:
  - applyTo: LISTENER
    match:
      context: SIDECAR_OUTBOUND
    patch:
      operation: ADD
      value:
        name: rocketmq
        address:
          socket_address:
            protocol: TCP
            address: 0.0.0.0
            port_value: 10911
        traffic_direction: "OUTBOUND"
        bind_to_port: false
        filter_chains:
        - filters:
          - name: envoy.filters.network.rocketmq_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.rocketmq_proxy.v3.RocketmqProxy
              stat_prefix: rocketmq
              route_config:
                name: rocketmq
                routes:
                - match:
                    topic:
                      exact: topic1
                  route:
                    cluster: outbound|10911||broker-0.default.svc.cluster.local
```
does latest istio do not support type.googleapis.com/envoy.extensions.filters.network.rocketmq_proxy.v3.RocketmqProxy

### Version

```prose
[root@node01 rocketmq_proxy]# istioctl version
client version: 1.13.2
control plane version: 1.13.2
data plane version: 1.13.2 (18 proxies)

[root@node01 rocketmq_proxy]# kubectl version --short
Client Version: v1.21.0
Server Version: v1.21.0
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
