### ISSUE TITLE
[Istio-Gateway] unable to get local issuer certificate

### ISSUE THREAD

**Issue by ichasco-heytrade** [istio/istio#38152]
### Bug Description

I have added the cert and the key in the gateway:

```
kubectl create -n istio-system secret tls istio-ingressgateway-certs --key=wildcard.xxxxx.com.key --cert=wildcard.xxxx.com.crt 
```

```
tls:
        mode: SIMPLE
        serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
        privateKey: /etc/istio/ingressgateway-certs/tls.key
        minProtocolVersion: TLSV1_2
        maxProtocolVersion: TLSV1_3
      hosts:
        - "api-dev.xxxx.com"
```

The cert is signed by comod (so its valid) and uses SNI

In the browser it works without any warnings, but with curl:

```
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

With verbose:
```
* Connected to api-dev.xxxxxx.com (X.X.X.X) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

### Version

```prose
client version: 1.12.0
control plane version: 1.12.0
data plane version: 1.12.0 (40 proxies)
```
```


### Additional Information

All the certificates have been add okay (I can see them in /etc/istio/ingressgateway-certs/)
