### ISSUE TITLE
EnvoyFilter setting maxRequestBytes breaks ingressgateway

### ISSUE THREAD

**Issue by JonasJasas** [istio/istio#38166]
### Bug Description

This filter is used to work with the 1.11 version:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: size-limit
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.buffer
          typed_config:
            '@type': type.googleapis.com/udpa.type.v1.TypedStruct
            value:
              maxRequestBytes: 1073741824
```
After creating this filter and restarting `ingressgateway` instances `ingressgateway` is always unhealthy and outputs:
```
...
2022-03-29T09:45:04.182440Z    warn    Envoy proxy is NOT ready: config received from XDS server, but was rejected: cds updates: 3 successful, 0 rejected; lds updates: 0 successful, 3 rejected
...
```

### Version

```prose
istioctl version
client version: 1.13.2
control plane version: 1.13.2
data plane version: 1.13.2 (7 proxies)

kubectl version --short
Client Version: v1.23.5
Server Version: v1.23.5
```

### Additional Information

istioctl bug-report

Target cluster context: kubernetes-admin@kubernetes

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2022-03-29 09:58:33.621778134 +0000 UTC

Cluster endpoint: https://10.194.127.210:6443
CLI version:
version.BuildInfo{Version:"1.13.2", GitRevision:"91533d04e894ff86b80acd6d7a4517b144f9e19a", GolangVersion:"go1.17.8", BuildStatus:"Clean", GitTag:"1.13.2"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.13.2", GitRevision:"91533d04e894ff86b80acd6d7a4517b144f9e19a", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.13.2"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.13.2}

Fetching proxy logs for the following containers:

istio-operator/istio-operator/istio-operator-67b876d65f-d8dlm/istio-operator
istio-system/istio-ingressgateway/istio-ingressgateway-6dc5bf864d-7pr4c/istio-proxy
istio-system/istio-ingressgateway/istio-ingressgateway-6dc5bf864d-9hk6g/istio-proxy
istio-system/istio-ingressgateway/istio-ingressgateway-6dc5bf864d-9wrwc/istio-proxy
istio-system/istiod/istiod-59c5cfc9db-j6vbs/discovery

Fetching Istio control plane information from cluster.

Running istio analyze on all namespaces and report as below:
Analysis Report:
Info [IST0102] (Namespace istio-operator) The namespace is not enabled for Istio injection. Run 'kubectl label namespace istio-operator istio-injection=enabled' to enable it, or 'kubectl label namespace istio-operator istio-injection=disabled' to explicitly mark it as not needing injection.
Creating an archive at /root/bug-report.tar.gz.
Cleaning up temporary files in /tmp/bug-report.
Done.
