### ISSUE TITLE
Prometheus-Istio pods crashing with OOM

### ISSUE THREAD

**Issue by thennetirajesh** [istio/istio#38176]
Hi Colleagues,

We are noticing that Prometheus-istio pods keep on restarting with OOM (Out of memory) for the past few weeks.
Even we have increased the resource for the pod even though it's looking for a higher value. currently we have allocated 8G for the istio pod. 
We are unable to figure it out the issue, can someone suggest what may cause the issue also is there any finetune is required kindly suggest us.

Kubernetes version:  1.20.11
Istio version: 1.10.4  & 1.11.8  ( Both versions we are facing the same issue)

**Comment by howardjohn** [comment]
The Prometheus deployments in samples/ are just that - samples. They are not intended as production ready deployments if Prometheus (which is not a trivial thing to do at scale). So you may want to look into more production ready deployments

**Comment by litong01** [comment]
@howardjohn @thennetirajesh the default addon prometheus configuration uses emptyDir for data which may use memory depends on your cloud implementation of emptyDir. Also based on k8s document, emptyDir volume is persistent over pod crashes, I wonder if you can change the storage configuration a bit to use a disk volume instead to see if the error goes away.

```
    volumes:
        - name: config-volume
          configMap:
            name: prometheus
        - name: storage-volume
          emptyDir:
            {}
```
