### ISSUE TITLE
The custom resource sidecar not work as expect

### ISSUE THREAD

**Issue by terryyrliang** [istio/istio#38190]
### Bug Description

In my case, we want some of my request pass through istio-proxy sidecar and some not. So we configure the sidecar like below.
However, the host my-namespace/endpoint1.my-namespace.svc.cluster.local still captured by the istio-proxy sidecar as the result of http://localhsot:15000/listeners.
Another case is if I keep the first rule only, then all the request to any other hosts including the one my-namespace/endpoint1.my-namespace.svc.cluster.local got passthrough by the istio-proxy sidecar.
```
spec:
  egress:
    - captureMode: NONE
      hosts:
        - my-namespace/endpoint1.my-namespace.svc.cluster.local
      port:
        name: egressiam
        number: 8443
        protocol: HTTPS
    - hosts:
        - */*
```

### Version

```prose
$ istioctl -i apigm-off-non-function1-697 version
client version: 1.10.3
control plane version: 1.11-dev

$ kubectl version --short
Client Version: v1.21.1
Server Version: v1.21.1
```
