### ISSUE TITLE
add kafka_mesh envoyfilter,the config has no error,but the config is not effictive

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#38194]
### Bug Description

apply the flowing config:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: kafka-mesh
  namespace: istio
spec:
  workloadSelector:
    labels:
      app: kafka-producter
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: SIDECAR_OUTBOUND
      listener:
        portNumber: 29092 
        filterChain:
          filter:
            name: "envoy.filters.network.tcp_proxy"
    patch:
      operation: INSERT_BEFORE
      value:
          name: envoy.filters.network.kafka_mesh
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.kafka_mesh.v3alpha.KafkaMesh
            advertised_host: "127.0.0.1"
            advertised_port: 29092
            upstream_clusters:
            - cluster_name: kafka-c1
              bootstrap_servers: kafka-all-broker.istio:29092
              partition_count: 3
            - cluster_name: kafka-c2
              bootstrap_servers: kafka-c2-all-broker.istio:29092
              partition_count: 3
              producer_config:
                acks: "1"
                linger.ms: "500"
            forwarding_rules:
            - target_cluster: kafka-c1
              topic_prefix: my-topic
            - target_cluster: kafka-c2
              topic_prefix: my-topic2
```

![1648716411(1)](https://user-images.githubusercontent.com/31508490/161015484-86500f42-3ec1-4d2e-b6ac-ed168bc7496c.jpg)

kafka producer was lautched by：
```
kubectl -n istio run kafka-producer -it  --image=strimzi/kafka:0.12.2-kafka-2.2.1 --labels="app=kafka-producter" --rm --restart=Never -- bin/kafka-console-producer.sh --broker-list 127.0.0.1:29092 --topic my-topic
```

![image](https://user-images.githubusercontent.com/31508490/161015783-299f7189-001a-42da-950f-833b3efcf8e5.png)

### Version

```prose
[root@node01 ~]# istioctl version
client version: 1.11.2
control plane version: 1.11.2
data plane version: 1.11.2 (22 proxies)

[root@node01 ~]# kubectl version --short
Client Version: v1.21.0
Server Version: v1.21.0
```

**Comment by zirain** [comment]
please your config_dump file, image is hard to debug.

**Comment by 13567436138** [comment]
how to dump

**Comment by 13567436138** [comment]
[config_dump.TXT](https://github.com/istio/istio/files/8394887/config_dump.TXT)

**Comment by zirain** [comment]
Is this correct?

![image](https://user-images.githubusercontent.com/4354057/161211302-804f0a88-035f-4f6b-95c5-56ab04a9e5d9.png)


![image](https://user-images.githubusercontent.com/4354057/161211243-37e05c3b-34ce-472d-a263-3dc376864211.png)

**Comment by 13567436138** [comment]
yes，I have changed，it is correct。
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: kafka-mesh
  namespace: istio
spec:
  workloadSelector:
    labels:
      app: kafka-producer
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: SIDECAR_OUTBOUND
      listener:
        portNumber: 29092 
        filterChain:
          filter:
            name: "envoy.filters.network.tcp_proxy"
    patch:
      operation: INSERT_BEFORE
      value:
          name: envoy.filters.network.kafka_mesh
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.kafka_mesh.v3alpha.KafkaMesh
            advertised_host: "127.0.0.1"
            advertised_port: 29092
            upstream_clusters:
            - cluster_name: kafka-c1
              bootstrap_servers: kafka-all-broker.istio:29092
              partition_count: 3
            - cluster_name: kafka-c2
              bootstrap_servers: kafka-c2-all-broker.istio:29092
              partition_count: 3
              producer_config:
                acks: "1"
                linger.ms: "500"
            forwarding_rules:
            - target_cluster: kafka-c1
              topic_prefix: my-topic
            - target_cluster: kafka-c2
              topic_prefix: my-topic2
```
