### ISSUE TITLE
telemetry: consider environment-specific selection / automation

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#38271]
**Describe the feature request**

In a discussion of access logging on VMs, an issue with systemd-based logging was raised regarding access to `/dev/stdout`. It appears that in various environments, a blanket configuration to log to `/dev/stdout` could cause access logging to fail.

At the moment, it should be possible to use the Telemetry API to select different providers per namespace or per workload. However, if VMs are distributed across multiple namespaces, etc., it could be cumbersome to define Telemetry resources in each namespace that select on a given VM-specific label and to label each VM with that consistent label to enable overriding of provider selection.

We should determine if it makes sense, at some level, to allow configuration at the provider level for environment-specific customizations. Alternatively, should we make it easier to provide mesh-wide defaults per environment? Another option would be to automatically detect `/dev/stdout` in certain environments and automatically redirect to a well-known path (something like: `/var/log/istio/proxy.log`).

**Describe alternatives you've considered**

Define two providers in MeshConfig. Label all VMs in all namespaces with something like "istio-env: vm". Create Telemetry resources in all namespaces with a WorkloadSelector with something like `matchLabels: istio-env: vm`.

**Affected product area (please put an X in all that apply)**

[ X ] Extensions and Telemetry
[ X ] User Experience

**Affected features (please put an X in all that apply)**

[ X ] Virtual Machine

**Additional context**

/cc: @GregHanson @linsun @zirain @costinm

**Comment by zirain** [comment]
> Define two providers in MeshConfig. Label all VMs in all namespaces with something like "istio-env: vm". Create Telemetry resources in all namespaces with a WorkloadSelector with something like matchLabels: istio-env: vm.

do you means some like `discoverySelectors`, but for Telemetry?

if we decide to add something, I prefer to use annotation.

**Comment by zirain** [comment]
link to https://github.com/istio/istio/issues/30598

**Comment by douglas-reid** [comment]
> if we decide to add something, I prefer to use annotation.

In that particular example, I was suggesting using the existing label-based `WorkloadSelector` implementation. If we want to pursue an annotation-based approach, we would need to ensure selection could happen.

Having some environment aware behavior _might_ be better for users?

This came out of a discussion in one of the community meetings re: VM issues.

**Comment by costinm** [comment]
For security (and other cases), agent detects the environment and adds some
node metadata automatically. There is no reason for user to have to
configure things that we can auto-configure or detect.

The current API is probably wrong - it should not explicitly specify a
file, just 'enable', and let the implementation pick.

**Comment by zirain** [comment]
> For security (and other cases), agent detects the environment and adds some
node metadata automatically. There

@costinm do you means `OWNER: kubernetes://apis/apps/v1/namespaces/default/deployments/httpbin`?
```
metadata:
        ANNOTATIONS:
          kubectl.kubernetes.io/default-container: httpbin
          kubectl.kubernetes.io/default-logs-container: httpbin
          kubernetes.io/config.seen: "2022-04-07T08:30:03.148168045Z"
          kubernetes.io/config.source: api
          prometheus.io/path: /stats/prometheus
          prometheus.io/port: "15020"
          prometheus.io/scrape: "true"
          proxy.istio.io/config: |-
            proxyStatsMatcher:
              inclusionPrefixs:
              - 'http'
          sidecar.istio.io/status: '{"initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["istio-envoy","istio-data","istio-podinfo","istio-token","istiod-ca-cert"],"imagePullSecrets":null,"revision":"default"}'
        APP_CONTAINERS: httpbin
        CLUSTER_ID: Kubernetes
        DNS_CAPTURE: "true"
        ENVOY_PROMETHEUS_PORT: 15090
        ENVOY_STATUS_PORT: 15021
        INSTANCE_IPS: 10.244.0.79,fe80::6c8f:bbff:fec7:2297
        INTERCEPTION_MODE: REDIRECT
        ISTIO_PROXY_SHA: istio-proxy:ff44db02db5a99a7f06c31441c3a5a0f7ce9e2b4
        ISTIO_VERSION: 1.12.0
        LABELS:
          app: httpbin
          pod-template-hash: 65b46bcd4f
          security.istio.io/tlsMode: istio
          service.istio.io/canonical-name: httpbin
          service.istio.io/canonical-revision: v1
          version: v1
        MESH_ID: mesh1
        NAME: httpbin-65b46bcd4f-t9sr7
        NAMESPACE: default
        OWNER: kubernetes://apis/apps/v1/namespaces/default/deployments/httpbin
        PILOT_SAN:
        - istiod.istio-system.svc
        POD_PORTS: '[{"containerPort":80,"protocol":"TCP"}]'
        PROV_CERT: var/run/secrets/istio/root-cert.pem
        PROXY_CONFIG:
          binaryPath: /usr/local/bin/envoy
          concurrency: 2
          configPath: ./etc/istio/proxy
          controlPlaneAuthPolicy: MUTUAL_TLS
          discoveryAddress: istiod.istio-system.svc:15012
          drainDuration: 45s
          extraStatTags:
          - url_path
          - response_status
          meshId: mesh1
          parentShutdownDuration: 60s
          proxyAdminPort: 15000
          proxyMetadata:
            BOOTSTRAP_XDS_AGENT: "true"
            ISTIO_META_DNS_CAPTURE: "true"
          proxyStatsMatcher: {}
          serviceCluster: httpbin.default
          statNameLength: 189
          statusPort: 15020
          terminationDrainDuration: 5s
          tracing:
            zipkin:
              address: zipkin.istio-system:9411
        SERVICE_ACCOUNT: httpbin
        WORKLOAD_NAME: httpbin
```
