### ISSUE TITLE
Customizing Istio Metrics with unexpected metrics 

### ISSUE THREAD

**Issue by YaHuiSong** [istio/istio#38277]
### Bug Description

situation: 
 I configured the customize COUNTER metric **posta_total** and  HISTOGRAM metrics **istio_posta_duration_millionseconds** with dimensions **url_path** and **response_status** in istioOperator yaml file. Then I got some strange issue
 1.  got extra wired metric with names like following 
 ```
 response_status___200___url_path____app___istio_posta_total
 response_status___200___url_path____app___istio_posta_duration_milliseconds_buckets
 response_status___200___url_path____app___istio_posta_duration_milliseconds_sum
 response_status___200___url_path____app___istio_posta_duration_milliseconds_total
 ```
 2. for HOSTGRAM metric, the buckets distribution is not correct
 
 use the PromQL with 
 `sum(istio_request_duration_milliseconds_bucket{pod="xxxxxxxx"}) by (le)`
 
result: 2 values
<img width="1449" alt="image" src="https://user-images.githubusercontent.com/24310039/162144597-e24d925b-b920-42d1-b9bc-e633d29f0827.png">
 
Use istio standard metric with the same pod 
 `sum(istio_request_duration_milliseconds_bucket{pod="xxxxx"}) by (le)`
 
result: 3 values
<img width="1363" alt="image" src="https://user-images.githubusercontent.com/24310039/162145286-aee30a56-f8ee-45a9-8b1e-f6ac8ca250e9.png">

3. another question, not a bug
Is it possible If I want to override the existing HOSTGRAM metric dimensions **le** . 
I know the telemetry V2 does not support customizing buckets for histogram type metrics from fqa https://istio.io/latest/about/faq/metrics-and-logs/#telemetry-v1-vs-v2.

But I am not sure if  telemetry V2  support customizing buckets right now. While as the le default value is **[0.5, 1, 5, 10, 25, 50, 100, 250, 500, 1000, 2500, 5000, 10000, 30000, 60000, 300000, 600000, 1800000, 3600000]**
For reality service, the values almost locate less than 5000, the most of default le values is not used actually.
So do istio team has any plan to support customizing buckets for  histogram type metrics to make it work better if it does not support now.

I am freshman in istio metric, correct me if I made any mistake. Thanks in advance 
 
 What I did:
 1. configure the istioOperator with 
 ```
 apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
  namespace: istio-system
spec:
  components:
    ingressGateways:
    - enabled: true
      k8s:
        env:
          ....
      name: istio-ingressgateway
  hub: gcr.io/istio-release
  profile: default
  meshConfig:
    defaultConfig:
      proxyStatsMatcher:
        inclusionPrefixes:
          - istio_posta_total
          - istio_posta_duration_milliseconds_buckets
          - istio_posta_duration_milliseconds_sum
          - istio_posta_duration_milliseconds_total
      extraStatTags:
        - url_path
        - response_status
  values:
    gateways:
      istio-ingressgateway:
        type: NodePort
    pilot:
      env:
        PILOT_ENABLE_VIRTUAL_SERVICE_DELEGATE: "true"
    telemetry:
      v2:
        prometheus:
          configOverride:
            inboundSidecar:
              definitions:
              - name: posta_total
                type: "COUNTER"
                value: "1"
              - name: posta_duration_milliseconds
                type: "HISTOGRAM"
                value: "1"
              metrics:
                - name: posta_total
                  dimensions:
                    url_path: request.url_path
                    response_status: string(response.code)
                - name: posta_duration_milliseconds
                  dimensions:
                    url_path: request.url_path
                    response_status: string(response.code)

```
2. check the envoyFilter
3.  restart the application pod
4. check the metrics with istio prometheus dashboard

### Version

```prose
➜  ✗ istioctl version
client version: 1.11.0
control plane version: 1.12.4
data plane version: 1.12.4 (1103 proxies)
➜  ✗ kubectl version --short
Client Version: v1.22.1
Server Version: v1.21.5-eks-bc4871b
➜  ✗ helm version --short
v3.6.3+gd506314
```

### Additional Information

Running with the following config:

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-system, kube-public, kube-node-lease, local-path-storage } AND { Namespaces: kube-system, kube-public, kube-node-lease, local-path-storage }
end-time: 2022-04-07 15:07:07.306058 +0800 CST

The following Istio control plane revisions/versions were found in the cluster:

```
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.12.4", GitRevision:"d60cc270251c6fed857dd5ec0546207e0a7dec1f", GolangVersion:"go1.17.7", BuildStatus:"Clean", GitTag:"1.12.4"},
    },
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.12.4", GitRevision:"d60cc270251c6fed857dd5ec0546207e0a7dec1f", GolangVersion:"go1.17.7", BuildStatus:"Clean", GitTag:"1.12.4"},
    },
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.12.4", GitRevision:"d60cc270251c6fed857dd5ec0546207e0a7dec1f", GolangVersion:"go1.17.7", BuildStatus:"Clean", GitTag:"1.12.4"},
    },
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.12.4", GitRevision:"d60cc270251c6fed857dd5ec0546207e0a7dec1f", GolangVersion:"go1.17.7", BuildStatus:"Clean", GitTag:"1.12.4"},
    },
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.12.4", GitRevision:"d60cc270251c6fed857dd5ec0546207e0a7dec1f", GolangVersion:"go1.17.7", BuildStatus:"Clean", GitTag:"1.12.4"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.12.4}

xxxxxx
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
