### ISSUE TITLE
buildGatewayListeners: skipping privileged gateway port 587

### ISSUE THREAD

**Issue by ronyrv13** [istio/istio#38295]
### Bug Description

Hello Team,

We are getting below error post istio 1.6.11 versions.

Error Message -
warn    buildGatewayListeners: skipping privileged gateway port 587 for node internal-istio-ingressgateway-84cbdf4ffc-d4gz2.istio-system as it is an unprivileged pod

![image](https://user-images.githubusercontent.com/34336227/162466046-f38cc3b0-4c81-427d-8439-cf4a4d145e36.png)

This issue is Blocking our mail-services.

Can anyone please suggest the solution for this?..

We use Istio-Operator for Istio Deployment and we use below config for ingressGateways

```yaml
  components:
    ingressGateways:
    - name: internal-istio-ingressgateway
      namespace: istio-system
      enabled: true
      label:
        istio: internal-ingressgateway
        app: internal-istio-ingressgateway
      k8s:
        securityContext:
           privileged: true
        serviceAnnotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
        hpaSpec:
          minReplicas: 2
        service:
          ports:
            - name: status-port
              port: 15021
              targetPort: 15021
            - name: http2
              port: 80
              targetPort: 8080
            - name: https
              port: 443
              targetPort: 8443
            - name: https-lmis
              port: 9888
              targetPort: 9888
            - name: tls
              port: 15443
              targetPort: 15443
            - name: tcp
              port: 31400
              targetPort: 31400
            - name: smtpd
              port: 587
              targetPort: 587
        overlays:
          - kind: Deployment
            name: internal-istio-ingressgateway
            patches:
              - path: spec.template.spec.containers[0].ports
                value:
                  - containerPort: 15021
                  - containerPort: 8080
                  - containerPort: 8443
                  - containerPort: 15443
                  - containerPort: 31400
                  - containerPort: 15011
                  - containerPort: 15012
                  - containerPort: 8060
                  - containerPort: 853
                  - containerPort: 15090
              - path: spec.template.spec.containers[0].readinessProbe.initialDelaySeconds
                value: 25
```

### Version

```prose
Istio-

client version: 1.12.6
control plane version: 1.12.6
data plane version: 1.12.6 (3 proxies)

kubectl -

Client Version: v1.22.0
Server Version: v1.21.9
```

**Comment by litong01** [comment]
@ronyrv13 I think that since you are using port 853, you will have to make the ingress gateway runAsRoot. something like this.

```
spec:
  values:
    gateways:
      istio-ingressgateway:
        injectionTemplate: gateway
        runAsRoot: true
```

**Comment by litong01** [comment]
@ronyrv13 also noticed that your service is 587 but your container port has 853. not sure if that is really what you want.

**Comment by ronyrv13** [comment]
Hey Tong, Thanks for quick reply.\
So our workflow is like -
IstioLB - > Gateway -> VS -> SMTP-Service (at port 587) -> SMTP POD  (listening at 587)
So, in above config 587 is configured as GatewayListener.

As i mentioned, we are using istio-operator for Istio Deployment where your suggested implementation will be completely different.
Will try to add `runAsRoot: true` in operator config and will update soon

**Comment by litong01** [comment]
@ronyrv13 using operator should be similar, you should be able to create your ingress gateway using operator. Let me know if it works. Thanks.

**Comment by ronyrv13** [comment]
Hello @litong01 

I got the issue resolved for 587 port, but with different approach.
Sharing the same, so that it can help others in future-

Actually the issue is with istio source code itself.

By default the ISTIO_META_UNPRIVILEGED_POD env is set to `true` which automatically resembles that making it false will make it privileged pod.

But if you check Istio source code, you will find a conditional statement [here](https://github.com/istio/istio/blob/30fd2f0c9149ab8dc6410ea4de129634110ac6e1/pilot/pkg/networking/core/v1alpha3/gateway.go#:~:text=if%20builder.node.Metadata.UnprivilegedPod%20!%3D%20%22%22%20%26%26%20port.Number%20%3C%201024%20%7B) where the condition is checking builder.node.Metadata.UnprivilegedPod is null or not and whenever we use ISTIO_META_UNPRIVILEGED_POD: "false" the condition gets true (not null) it get inside the conditional statement and istiod blocks the gateway.


Added following patch resolved the Issue -

```yaml
  values:
    gateways:
      istio-ingressgateway:
        runAsRoot: true
        env:
          ISTIO_META_UNPRIVILEGED_POD: ""
```
<img width="960" alt="WindowsTerminal_YlMtZaqC7t" src="https://user-images.githubusercontent.com/34336227/163937015-12d38753-3fd7-4fa3-8e9e-7bfb2ce08980.png">

The code needs to be updated to check the boolean expression for envVar ISTIO_META_UNPRIVILEGED_POD
