### ISSUE TITLE
Istio-1.13.2 not support K8S 1.21 dualStack ReadinessProbe failed

### ISSUE THREAD

**Issue by wangyj-tc** [istio/istio#38314]
### Bug Description

When I installed istio version 1.13.2 in kubernetes version 1.21, the health check of istio ingress gateway failed all the time. Because the health check through IPv6 + port failed all the time, I looked at the IPv4 address of pod and it was successful

### Version

```prose
[root@wxjd-csy-vm-os01-bcapp-master01 ~]#  istioctl version
client version: 1.13.2
control plane version: 1.13.2
data plane version: 1.13.2 (1 proxies)


[root@wxjd-csy-vm-os01-bcapp-master01 ~]#  kubectl version --short
Client Version: v1.21.5-eki.0
Server Version: v1.21.5-eki.0
```

### Additional Information

![image](https://user-images.githubusercontent.com/33716429/162627610-afefdb67-0274-44b0-baa8-b963ab37bc18.png)

![image](https://user-images.githubusercontent.com/33716429/162627646-b2b5f4f5-6a16-4bb5-afc8-1232dacc71e1.png)

![image](https://user-images.githubusercontent.com/33716429/162627664-11b9f3b0-dee6-485f-91de-cef73f4e2bb3.png)

**Comment by wangyj-tc** [comment]
i used install command
istioctl install  --set hub=nexus.cmss.com:8086/paas-pcb2/service-mesh/istio  --set profile=default
![image](https://user-images.githubusercontent.com/33716429/162627841-5dbdee3a-1b9f-4a2d-b957-970f4d6d913b.png)

**Comment by wangyj-tc** [comment]
![image](https://user-images.githubusercontent.com/33716429/162627900-4f175e74-2f82-442a-9950-bc8a0f71835c.png)

**Comment by wangyj-tc** [comment]
English is very poor. It's the first time to post a question on GitHub. I hope the powerful person can give a reply. Thank you

**Comment by litong01** [comment]
@wangyj-tc did a bit more testing on IPv4 only cluster as well, I still see the readines probe failed error and I think that is really the timing issue.

**Comment by howardjohn** [comment]
Dual stack is not yet supported, see https://github.com/istio/istio/issues/37533

**Comment by litong01** [comment]
@wangyj-tc @howardjohn I did some more testing with dual stack and ipv6 only clusters, with a bit increased initial delay on the ingressgateway and a bit change to helloworld test app (which for some reason does not bind to both ipv4 and ipv6 address, with a bit change to the app itself, it does bind to both ipv4 and ipv6 addresses), from what I can see everything is working. This is based on istio 1.13.2.

**Comment by wangyj-tc** [comment]
> s, with a bit increased initial delay on the ingressgateway and a bi

Is there a plan for when it will be supported?

**Comment by wangyj-tc** [comment]
> @wangyj-tc @howardjohn I did some more testing with dual stack and ipv6 only clusters, with a bit increased initial delay on the ingressgateway and a bit change to helloworld test app (which for some reason does not bind to both ipv4 and ipv6 address, with a bit change to the app itself, it does bind to both ipv4 and ipv6 addresses), from what I can see everything is working. This is based on istio 1.13.2.

Can you briefly describe the place where it was remodeled? Or some screenshots would be better

**Comment by litong01** [comment]
@wangyj-tc you can use the following yaml to increase the initial delay of readiness probe.

```
istioctl install -y -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        overlays:
        - kind: Deployment
          name: istio-ingressgateway
          patches:
          - path: spec.template.spec.containers[0].readinessProbe.initialDelaySeconds
            value: 15
EOF

```

in terms of the verification, I used the istio hello world deployment, but there were some issues due to the python app behaves differently with using default port vs explicitly specified port. Fortunately by using some env variables and reconfiguring the entrypoint, one can force the app to bind to both ipv4 and ipv6 addresses so that the app will work on dual stack. here is what I have. I will include the entire deployment for completeness. The key is to use env and change the container entry point so that the port is explicitly specified.

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-v1
  labels:
    app: helloworld
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      version: v1
  template:
    metadata:
      labels:
        app: helloworld
        version: v1
    spec:
      containers:
      - name: helloworld
        image: docker.io/istio/examples-helloworld-v1
        resources:
          requests:
            cpu: "100m"
        env:
        - name: FLASK_RUN_PORT
          value: "5000"
        - name: FLASK_RUN_HOST
          value: "::"
        - name: FLASK_ENV
          value: "development"
        - name: FLASK_APP
          value: "/opt/microservices/app.py"
        command: ["flask", "run"]
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
```
