### ISSUE TITLE
HTTP  500 errors occurred during the creation of the `wasmplugin`

### ISSUE THREAD

**Issue by johnlanni** [istio/istio#38313]
**Describe the feature request**

The `wasmplugin` resource triggers both ECDS and LDS updates, and when envoy receives the  LDS first, a new listener will start serving requests even if no wasm filter is found. Then all http requests fail with 500 status until the wasm filter loaded through ECDS.

**Describe alternatives you've considered**

Maybe we can add `default_config` and `apply_default_config_without_warming` to ECDS like this:

```json
             {
              "name": "wasm-test",
              "config_discovery": {
               "config_source": {
                "ads": {},
                "initial_fetch_timeout": "0s",
                "resource_api_version": "V3"
               },
               "default_config": {
                "@type": "type.googleapis.com/envoy.extensions.filters.http.composite.v3.Composite"
               },
               "apply_default_config_without_warming": true,
               "type_urls": [
                "type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm",
                "type.googleapis.com/envoy.extensions.filters.http.composite.v3.Composite"
               ]
              }
             }
```
The `default_config` here is  a empty composite filter config used to pass the requests without any processing.
I tested this configuration and no http 500 errors occurred during the creation of the `wasmplugin` resource.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
The listener won't be ready before ecds loaded

**Comment by johnlanni** [comment]
> The listener won't be ready before ecds loaded

@hzxuzhonghu You can test the configuration below and the listener will be ready even if the `wasmtest` filter configuration is not found in ecds.

**envoy.yaml:*
```yaml
node:
  cluster: test-cluster
  id: test-idn
admin:
  address:
    socket_address: { address: 127.0.0.1, port_value: 9901 }
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 127.0.0.1, port_value: 10000 }
    listener_filters:
    - name: "envoy.filters.listener.tls_inspector"
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                direct_response:
                  status: 200
                  body:
                    inline_string: "hello world"
          http_filters:
          - name: wasmtest
            config_discovery:
              config_source:
                path: ./ecds.yml
                resource_api_version: V3
              type_urls:
              - type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
```

**ecds.yaml:**
```yaml
resources: {}
```
```

**Comment by hzxuzhonghu** [comment]
maybe static listener and dynamic listener behave differently.  

cc @ramaraochavali may know this

**Comment by johnlanni** [comment]
@hzxuzhonghu  Dynamic listeners have the same problem. I tested with the official demo, and there is always a problem when loading the wasm code for the first time through this configuration (envoy has wasm code cache, so only the first time):
```yaml
kind: WasmPlugin
metadata:
  name: wasmtest
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  url: oci://xxxxx
```

Start a  wrk like this:

```bash
wrk -c10 -t10 -d60s http://127.0.0.1/productpage
```

Then you can see these errors in the ingressgateway's log:

![image](https://user-images.githubusercontent.com/6763318/162668220-8a899595-8ebe-4ed0-ad28-d758224f1076.png)

**Comment by hzxuzhonghu** [comment]
I am not sure how you get this result, in pilot-agent, pilot-agent will convert the wasm filter before sending to envoy

**Comment by johnlanni** [comment]
> I am not sure how you get this result, in pilot-agent, pilot-agent will convert the wasm filter before sending to envoy

I know, this covertion is avoid to load wasm code from remote, however this way not solve the problem that ECDS is not ready when LDS is acked.

**Comment by hzxuzhonghu** [comment]
If you do config dump, you can see the listener is warming rather than ready. So I could not understand how it can take effect. Inb other word, envoy is still using old warmed listener.

**Comment by hzxuzhonghu** [comment]
```
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: openid-connect
  namespace: default
spec:
  selector:
    matchLabels:
      app: httpbin 
  url: oci://private-registry:5000/openid-connect/openid:latest
  imagePullPolicy: IfNotPresent
  pluginConfig:
    openid_server: authn
    openid_realm: ingress

```

I applied the above config, unfortunately, I see complete different scenario as I described before. Not sure why
