### ISSUE TITLE
Incorrect Service entry stops all proxy communication within cluster and containers starting

### ISSUE THREAD

**Issue by zanven42** [istio/istio#38343]
### Bug Description

implementing a service entry with partial wildcards stops all traffic communication within the cluster.

example service entry file that broke everything.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: azure
  annotations:
    url: "https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops&tabs=IP-V4"
spec:
  hosts:
    - "*.dev.azure.com"
    - "*.vsassets.io"
    - "*gallerycdn.vsassets.io"
    - "*vstmrblob.vsassets.io"
    - aadcdn.msauth.net
    - aadcdn.msftauth.net
    - aex.dev.azure.com
    - aexprodea1.vsaex.visualstudio.com
    - amcdn.msftauth.net
    - amp.azure.net
    - app.vssps.dev.azure.com
    - app.vssps.visualstudio.com
    - "*.vsblob.visualstudio.com"
    - "*.vssps.visualstudio.com"
```

the following lines caused the fault when used, it can be repeatable with removing and adding those lines.
```yaml
    - "*gallerycdn.vsassets.io"
    - "*vstmrblob.vsassets.io"
```

we observed no more workloads could start within the cluster and that any communication within the cluster stopped working as well due to the envoy proxy. The workloads could not start because the envoy proxy could not start, the bug report is limited in scope to an example use case of a dummy workload not starting.

### Version

```prose
❯ istioctl version
client version: 1.13.2
control plane version: 1.11.4
data plane version: 1.11.4 (29 proxies)
❯ istioctl version --short
client version: 1.13.2
control plane version: 1.11.4
data plane version: 1.11.4 (29 proxies)
```

### Additional Information

[bug-report.tar.gz](https://github.com/istio/istio/files/8470890/bug-report.tar.gz)
