### ISSUE TITLE
ServiceEntry MESH_EXTERNAL routed to the local VirtualService

### ISSUE THREAD

**Issue by JonasJasas** [istio/istio#38345]
### Bug Description

In the `ServiceEntry` is set `location: MESH_EXTERNAL` so I expect that my request from the inside of the mesh to `othercluster.mydomain.com` should be bypassed and not handled by the `VirtualService` `vs`.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gw
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
    - hosts:
        - '*'
      port:
        number: 8000
        name: http
        protocol: HTTP
```

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs
spec:
  hosts:
    - my.default.svc.cluster.local
    - '*.mydomain.com'
  gateways:
    - gw
    - mesh # This must be here for the local requests
  http:
    - name: myroute
      match:
        - uri:
            prefix: /  
      route:
        - destination:
            host: handler.default.svc.cluster.local
            port:
              number: 8000
```

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: other-cluster
spec:
  resolution: DNS
  location: MESH_EXTERNAL
  hosts:
    - othercluster.mydomain.com
  ports:
    - number: 80
      name: http-port
      protocol: HTTP
```

### Version

```prose
istioctl version
client version: 1.13.2
control plane version: 1.13.2
data plane version: 1.13.2 (25 proxies)

kubectl version --short
Client Version: v1.23.5
Server Version: v1.23.5
```
