### ISSUE TITLE
Istio envoy ratel limiting doesn't work with Ingress gateway

### ISSUE THREAD

**Issue by vnhirenko** [istio/istio#38358]
### Bug Description

We have Istio ingressgateway and nginx ingress controller installed on the same cluster. Currently we are in the migration process from nginx to istio.
Trying to implement rate limiting for our service using EnvoyFilter, current config is:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  annotations:
  name: httpbin-inbound-8080
  namespace: httpbin
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.local_ratelimit
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
          value:
            stat_prefix: http_local_rate_limiter
  - applyTo: HTTP_ROUTE
    match:
      context: SIDECAR_INBOUND
      routeConfiguration:
        vhost:
          name: inbound|http|8080
          route:
            action: ANY
    patch:
      operation: MERGE
      value:
        typed_per_filter_config:
          envoy.filters.http.local_ratelimit:
            '@type': type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              filter_enabled:
                default_value:
                  denominator: HUNDRED
                  numerator: 100
                runtime_key: local_rate_limit_enabled
              filter_enforced:
                default_value:
                  denominator: HUNDRED
                  numerator: 100
                runtime_key: local_rate_limit_enforced
              response_headers_to_add:
              - append: false
                header:
                  key: x-local-rate-limit
                  value: "true"
              stat_prefix: http_local_rate_limiter
              token_bucket:
                fill_interval: 60s
                max_tokens: 1
                tokens_per_fill: 1
  workloadSelector:
    labels:
      app.kubernetes.io/name: httpbin

```
It works perfectly fine with nginx ingress or even if we are trying to access the service using internal cluster communication but it doesn't work with gateway.

 In our setup we have One gateway for all microservices and virtualservice per service. Istio sidecar injection enabled for all namespaces. 

Operator config:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
spec:
  values:
  values:
    gateways:
      istio-ingressgateway:
        injectionTemplate: gateway
    telemetry:
      v2:
        prometheus:
          configOverride:
            inboundSidecar:
              disable_host_header_fallback: true
            outboundSidecar:
              disable_host_header_fallback: true
            gateway:
              disable_host_header_fallback: true
  meshConfig:
    enableAutoMtls: true
    accessLogFile: /dev/stdout
    defaultConfig:
      holdApplicationUntilProxyStarts: true
  components:
    base:
      enabled: true
    pilot:
      enabled: true
      k8s:
        hpaSpec:
          minReplicas: 3
    egressGateways:
      - name: istio-ingressgateway
        enabled: false
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        label:
          istio: ingressgateway-internal
        k8s:
          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-internal: "true"
            service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
            service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
            service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
            service.beta.kubernetes.io/aws-load-balancer-alpn-policy: HTTP2Optional
            service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ${ISTIO_INTERNAL_ACM_ARN}
          service:
            ports:
            - name: https
              port: 443
              targetPort: 8443
              protocol: TCP
``` 

Are we missing something? Probably, someone has suggestion why rate limiting doesn't work wit gateway. 
 

### Version

```prose
$ istioctl version
client version: 1.13.2
control plane version: 1.13.2
data plane version: 1.12.4 (20 proxies), 1.11.5 (10 proxies), 1.13.2 (100 proxies)

$ kubectl version --short
Client Version: v1.21.0
Server Version: v1.21.5-eks-bc4871b
```

**Comment by zirain** [comment]
there's no inbound on gateway, please try with outbount or [GlobalRatelimit](https://istio.io/latest/docs/tasks/policy-enforcement/rate-limit/#global-rate-limit)

**Comment by vnhirenko** [comment]
hi, @zirain , thanks for your suggestion. 
I was able to implement rate limiting with this

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: httpbin-inbound
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.local_ratelimit
        typed_config:
          "@type": type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
          value:
            stat_prefix: http_local_rate_limiter
            token_bucket:
              max_tokens: 10
              tokens_per_fill: 10
              fill_interval: 60s
            filter_enabled:
              runtime_key: local_rate_limit_enabled
              default_value:
                numerator: 100
                denominator: HUNDRED
            filter_enforced:
              runtime_key: local_rate_limit_enforced
              default_value:
                numerator: 100
                denominator: HUNDRED
            response_headers_to_add:
              - append: false
                header:
                  key: x-local-rate-limit
                  value: 'true'
  ```
  And it works for all traffic that comes through gateway. But when I set `worloadselector`  to particular app
  ```
    workloadSelector:
    labels:
      app.kubernetes.io/name: httpbin
      ```
     
  Also I've noticed that with ` max_tokens: 10` I have ratelimit 20 per minute. I believe because I have 2 ingress gateway pods. Probably someone knows how to set this value per deployment (or service) but not per pod.
