### ISSUE TITLE
Sidecar tls egressListener w/multiple hosts uses one random cert for all of them

### ISSUE THREAD

**Issue by morkod** [istio/istio#38370]
### Bug Description

Hello team
Sidecar tls egressListener with multiple hosts attached to it seems to be using one cert for all of the host, breaking SSL connections for all hosts but that lucky one chosen somewhat randomly. 

We're trying to use Istio Sidecars to reduce proxies load, and ServiceEntries with REGISTRY_ONLY approach to control external connections. So we have SEs for every external connection, including HTTPS services. Those SEs are configured pretty much as the below example:
```
[~] > kubectl get se -n ext-res-dev cnnql -o yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  <...>
  name: cnnql
  namespace: ext-res-dev 
spec:
  hosts:
  - edition.cnn.com
  location: MESH_EXTERNAL
  ports:
  - name: cnnql
    number: 443
    protocol: TLS
  resolution: DNS
```
Now, an app may of course need to connect to multiple services, including multiple external HTTPS services, so we need to specify them all in Istio Sidecar configuration. As mentioned in the discussion of #37487 you can only have one listener per port. The comment there also mentions that as long as you are trying to connect to actual DNS names (which is what we need) rather than to binded IPs (which is not what we need), then you shall use a single listener for all the hosts. Which is also in line with  [egressListener hosts documentation](https://istio.io/latest/docs/reference/config/networking/sidecar/#IstioEgressListener):

> hosts string[] One or more service hosts exposed by the listener in namespace/dnsName format. 

...so by the end of the day we have Sidecar egress configuration similar to the below example:
```
[~] > kubectl get sidecar k8sdemo-dev-stan2-api -o yaml
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
<...>
spec:
  egress:
  - hosts:
    - ext-res-dev/bandcamp.com
    - ext-res-dev/edition.cnn.com
    - ext-res-dev/facebook.com
    port:
      name: tls-443
      number: 443
      protocol: tls
  - hosts:
    - ./*
    - default/*
    - istio-system/*
    - elk/*
  ingress:
<...>
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY
  workloadSelector:
<...>
```
In general this makes perfect sense and seems to be working for HTTP. This breaks however for HTTPS... well, for (N-1) of the services.
In the above synthetic example, if I exec into pod matching Sidecar workloadSelector and try to reach those services, I get the following picture:
One of those services works:
```
~/app $ curl -i https://edition.cnn.com
<valid data output>
~/app
```
The other two don't:
```
~/app $ curl -i https://bandcamp.com
curl: (60) SSL: no alternative certificate subject name matches target host name 'bandcamp.com'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
~/app $ curl -i https://facebook.com
curl: (60) SSL: no alternative certificate subject name matches target host name 'facebook.com'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
~/app $ 
```

The exact error is:
```
~/app $ curl -i -vvv https://bandcamp.com
*   Trying 240.240.0.9:443...
* Connected to bandcamp.com (240.240.0.9) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=cnn.com
*  start date: Feb 11 17:10:46 2022 GMT
*  expire date: Mar 15 17:10:45 2023 GMT
*  subjectAltName does not match bandcamp.com
* SSL: no alternative certificate subject name matches target host name 'bandcamp.com'
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, close notify (256):
curl: (60) SSL: no alternative certificate subject name matches target host name 'bandcamp.com'
```

So it keeps using CN=cnn.com for other services. Not exactly sure why CNN is chosen out of three though...

Now, if I `kubectl edit sidecar` and remove `- ext-res-dev/edition.cnn.com` service, the certificate switches to one of the two services left, So i can connect to one of the two, but cannot connect to the other one:
```
~/app $ curl -i https://bandcamp.com
<valid data output here now>
~/app $ curl -i https://facebook.com
<same SSL error>
```
I might be missing on how this can be worked around with some extra configuration. If so, please let me know. However in general this seems to be a bug to me. Please assist

### Version

```prose
[~] > istioctl version
client version: 1.13.2
control plane version: 1.13.2
data plane version: 1.13.2 (57 proxies), 1.11.0 (10 proxies)
[~] > kubectl version --short
Client Version: v1.23.5
Server Version: v1.21.3
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
[~] > helm version --short
v3.8.1+g5cb9af4
```
