### ISSUE TITLE
ServiceEntries don't match traffic to FQDNs

### ISSUE THREAD

**Issue by treyhyde** [istio/istio#38377]
### Bug Description

ServiceEntries don't match FQDNs.

I have a SE defined as

```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: jaeger-collector
  namespace: something
spec:
  hosts:
  - fulcrum-jaeger-collector.monitoring
  - fulcrum-jaeger-collector.monitoring.svc.cluster.local
  - fulcrum-jaeger-collector.monitoring.svc.cluster.local.
  - fulcrum-jaeger-collector-headless.monitoring
  - fulcrum-jaeger-collector-headless.monitoring.svc.cluster.local
  - fulcrum-jaeger-collector-headless.monitoring.svc.cluster.local.
  location: MESH_EXTERNAL
  ports:
  - number: 9411
    name: zipkin
    protocol: TCP
  - number: 14250
    name: proto
    protocol: TCP
  - number: 14267
    name: agent
    protocol: TCP
  - number: 14268
    name: thrift
    protocol: TCP
  resolution: NONE
```

If I send traffic to `fulcrum-jaeger-collector-headless.monitoring.svc.cluster.local.` the upstream_cluster gets recorded as `PassthroughCluster`
If I send traffic to `fulcrum-jaeger-collector-headless.monitoring.svc.cluster.local` (and suffer the 5+ DNS NX DOMAINs as a result), It gets recorded as expected as `"outbound|14268||fulcrum-jaeger-collector-headless.monitoring.svc.cluster.local"`

### Version

```prose
istioctl version
client version: 1.13.2
control plane version: 1.13.2
data plane version: 1.13.2 (490 proxies)

kubectl version
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by GregHanson** [comment]
```
  - number: 9411
    name: zipkin
    protocol: TCP
```
`protocol: TCP` means traffic will only be matched by port - hostname should not impact traffic at all.  If IP's or CIDR blocks were specified in `addresses`, those would get used for matching traffic but not `hosts` 

Is the trailing `.` in `fulcrum-jaeger-collector-headless.monitoring.svc.cluster.local.` a valid hostname?

**Comment by treyhyde** [comment]
> Is the trailing . in fulcrum-jaeger-collector-headless.monitoring.svc.cluster.local. a valid hostname?

Yes, the trailing `.` means, don't use search_paths in the resolver.  Without it in most places you'll get rate limited by upstream AWS DNS as it will try to resolve to public domains before falling back to cluster.local. and dns in the cluster.   

a more detailed reasonably ok explanation:
- https://pracucci.com/kubernetes-dns-resolution-ndots-options-and-why-it-may-affect-application-performances.html

changing the ndots value in kubernetes is generally pretty risky.

**Comment by hzxuzhonghu** [comment]
All traffic to 9411, capturred by one listener  0.0.0.0_9411.  This only contains one filterchain, with one network filter `envoy.filters.network.tcp_proxy`

```
    - name: envoy.filters.network.tcp_proxy
      typedConfig:
        '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
        cluster: outbound|9411||fulcrum-jaeger-collector-headless.monitoring   // This cluster may differ, according to sortting
        statPrefix: outbound|9411||fulcrum-jaeger-collector-headless.monitoring
```

The cluster does not matter, because all the clusters should be of `ORIGINAL_DST` type
