### ISSUE TITLE
Undesired dedupe of StatefulSet pods across multiple clusters 

### ISSUE THREAD

**Issue by weibohe** [istio/istio#38381]
### Bug Description

We deploy the same StatefulSet across 3 different clusters (each cluster runs in a different AZ). All 3 clusters are connected to a remote Istio control plane. Each StatefulSet pods are labeled with `app=foo`. We define a **ServiceEntry** that select `app=foo`. The clients of this ServiceEntry would like to load balance across pods across 3 clusters. 

Let's say there's 3 pods in each cluster:
- Cluster 1 foo ns: foo-1, foo-2, foo-3
- Cluster 2 foo ns: foo-1, foo-2, foo-3
- Cluster 3 foo ns: foo-1, foo-2, foo-3

Clients now only see 3 endpoints for foo service, instead of 9 endpoints.

Unlike deployments, StatefulSet pods can share the same pod name across clusters. Caching WorkloadInstances by  `namespace/podName` resulted in at any time, only 1 foo-X pod can exist in the istio control plane.  See https://github.com/istio/istio/blob/bb7b5d93cfd0bc6f80c815a25176809e9fcc79aa/pilot/pkg/serviceregistry/serviceentry/servicediscovery.go#L401-L417

The StatefulSet is managed by kafka/TiDB operator. The same StatefulSet is deployed across 3 clusters and is of the same logical cluster. it's very difficult to assign a different StatefulSet name per cluster. 

One potential fix is to append a pod's `ResourceVersion` as suffix to the cache key in addition to `namespace/podName`, but not sure if how it will affect the original problem in https://github.com/istio/istio/issues/20676 (should be okay, but cc @howardjohn to confirm).

### Version

```prose
istio version: 1.12.6
k8s version: 1.18.20
```

**Comment by zirain** [comment]
> One potential fix is to append a pod's ResourceVersion as suffix to the cache key in addition to `namespace/podName`

How about change this `cluster/namespace/podName` ?

**Comment by howardjohn** [comment]
Isn't the pod cache already per cluster?

**Comment by weibohe** [comment]
@howardjohn you are right, pod cache should already be per cluster. Hmm, then is eds deduping then?

**Comment by hzxuzhonghu** [comment]
>Clients now only see 3 endpoints for foo service, instead of 9 endpoints.

What is the ServiceEntry look like?

**Comment by weibohe** [comment]
@hzxuzhonghu 

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: kafka-k8s-multi-az-test-kafka-bootstrap
  namespace: kafka-k8s-multi-az-test
spec:
  addresses:
  - 100.124.67.80
  hosts:
  - kafka-k8s-multi-az-test-kafka-bootstrap.kafka-k8s-multi-az-test.svc.ea1.us.a
  location: MESH_INTERNAL
  ports:
  - name: tcp-10002
    number: 10002
    protocol: tcp
  resolution: STATIC
  workloadSelector:
    labels:
      app: kafka-k8s-multi-az-test-kafka-bootstrap
```

all the stateful sets pods have `app: kafka-k8s-multi-az-test-kafka-bootstrap` label
