### ISSUE TITLE
Envoy connection buffer limits don't take effect

### ISSUE THREAD

**Issue by arangamani** [istio/istio#38411]
### Bug Description

I have a gRPC server and I'm using both the sidecar istio-proxy as well as ingressgateway. I'm simulating a slow consumer by sleeping periodically in the gRPC streams. I see that Istio buffer limit goes up to the default of 256 MB. I'm trying to use the following EnvoyFilter configuration:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: envoy-filter-grpc-streaming
  namespace: istio-system
spec:
  configPatches:
    - applyTo: CLUSTER
      match:
        context: ANY
        cluster:
          portNumber: 8000
      patch:
        operation: MERGE
        value:
          typed_extension_protocol_options:
            envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
              "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
              explicit_http_config:
                http2_protocol_options:
                  initial_stream_window_size: 65536 # 64 KiB
                  initial_connection_window_size: 1048576 # 1 MiB
          http2_protocol_options:
            initial_stream_window_size: 65536 # 64 KiB
            initial_connection_window_size: 1048576 # 1 MiB
    - applyTo: CLUSTER
      match:
        context: ANY
        cluster:
          ## This has to be the port exposed by the pod for the service that we want to affect
          portNumber: 443
      patch:
        operation: MERGE
        value:
          typed_extension_protocol_options:
            envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
              "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
              explicit_http_config:
                http2_protocol_options:
                  initial_stream_window_size: 65536 # 64 KiB
                  initial_connection_window_size: 1048576 # 1 MiB
          http2_protocol_options:
            initial_stream_window_size: 65536 # 64 KiB
            initial_connection_window_size: 1048576 # 1 MiB
    - applyTo: CLUSTER
      match:
        context: ANY
        cluster:
          ## This has to be the port exposed by the pod for the service that we want to affect
          portNumber: 15021 # ingress gateway
      patch:
        operation: MERGE
        value:
          typed_extension_protocol_options:
            envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
              "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
              explicit_http_config:
                http2_protocol_options:
                  initial_stream_window_size: 65536 # 64 KiB
                  initial_connection_window_size: 1048576 # 1 MiB
          http2_protocol_options:
            initial_stream_window_size: 65536 # 64 KiB
            initial_connection_window_size: 1048576 # 1 MiB
    - applyTo: CLUSTER
      patch:
        operation: MERGE
        value:
          per_connection_buffer_limit_bytes: 32768 # 32 KiB
    - applyTo: NETWORK_FILTER
      match:
        context: ANY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
            http2_protocol_options:
              initial_stream_window_size: 65536 # 64 KiB
              initial_connection_window_size: 1048576 # 1 MiB
    - applyTo: LISTENER
      patch:
        operation: MERGE
        value:
          per_connection_buffer_limit_bytes: 32768 # 32 KiB
```
I applied the filter on all possible ports and I can see that the filter is applied if I try to do a config_dump on the sidecars but I still see the buffer going up more than the defined limit of 1 MB. This is the metric I see:
```bash
bash-5.1$ curl http://localhost:15000/stats 2>/dev/null | grep http2.pending
cluster.inbound|8080||.http2.pending_send_bytes: 0
cluster.outbound|8000||mrsdb-manager-service.default.svc.cluster.local.http2.pending_send_bytes: 0
cluster.outbound|8000||mrsdb-reader-service.default.svc.cluster.local.http2.pending_send_bytes: 0
cluster.sds-grpc.http2.pending_send_bytes: 0
cluster.xds-grpc.http2.pending_send_bytes: 0
http2.pending_send_bytes: 263591166
```
It is the `http2.pending_send_bytes`. The value comes down eventually as the client consumes the data and this also causes new clients to wait before the buffer is emptied. If the client consumes the data fast enough, I don't see the buffer growing that much but even in this case, I'd expect the buffer to be within the configured limits. 

If there is something I'm doing wrong, I'd be happy to know that as well. I know applying the EnvoyFilter is making an impact because without the filter applied, I get `http2.outbound_frames_flood` error code after a while.

### Version

```prose
$ istioctl version
client version: 1.11.3
control plane version: 1.11.3
data plane version: 1.11.3 (10 proxies)

$ kubectl version --short
Client Version: v1.22.2
Server Version: v1.19.16-eks-25803e
```

**Comment by silencev** [comment]
I'm having this issue too. It was working well in `istio 1.8.6` but failed in `istio 1.10.4`
here is the **EnvoyFilter** I applied and the sidecar got OOM killed because of the receiver with gRPC API.
and all the data are queued in sidecar and OOM eventually.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  labels:
    app: demo-server
  name: demo-server-h2-window-size
  namespace: demo
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      cluster:
        portNumber: 50051
        service: demo-server.demo.svc.cluster.local
      context: SIDECAR_INBOUND
    patch:
      operation: MERGE
      value:
        http2_protocol_options:
          initial_stream_window_size: 65536
          initial_connection_window_size: 65536
  - applyTo: NETWORK_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
        portNumber: 50051
    patch:
      operation: MERGE
      value:
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          http2_protocol_options:
            initial_stream_window_size: 65536
            initial_connection_window_size: 65536
  workloadSelector:
    labels:
      app: demo-server
```

## Version

$ istioctl version
client version: 1.10.0
control plane version: 1.10.4
data plane version: 1.10.4 (234 proxies)

**Comment by silencev** [comment]
After checking envoy document [here](https://www.envoyproxy.io/docs/envoy/v1.17.4/api-v3/extensions/upstreams/http/v3/http_protocol_options.proto), I found HTTP2 related options is now under `typed_extension_protocol_options`.

it works after I applied the new one with `typed_extension_protocol_options`
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  labels:
    app: demo-server
  name: demo-server-h2-window-size
  namespace: demo
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      cluster:
        portNumber: 50051
        service: demo-server.demo.svc.cluster.local
      context: SIDECAR_INBOUND
    patch:
      operation: MERGE
      value:
# deprecated
#        http2_protocol_options:
#          initial_stream_window_size: 65536
#          initial_connection_window_size: 65536
        typed_extension_protocol_options:
          envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
            '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
            explicit_http_config:
              http2_protocol_options:
                initial_stream_window_size: 65535
                initial_connection_window_size: 65536
  - applyTo: NETWORK_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
        portNumber: 50051
    patch:
      operation: MERGE
      value:
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          http2_protocol_options:
            initial_stream_window_size: 65536
            initial_connection_window_size: 65536
  workloadSelector:
    labels:
      app: demo-server
```
