### ISSUE TITLE
Unable to create Sidecar socket listener that points to a remote service

### ISSUE THREAD

**Issue by diranged** [istio/istio#38428]
### Bug Description

In our non-Istio environment, we use an Envoy sidecar container to provide unix-socket paths to point to remote services... eg, `/var/run/httpbin.sock` -> `https://httpbin.org`). We are trying to replicate this behavior in Istio with the `Sidecar` and `ServiceEntry` resources.

The issue we seem to have is that we cannot set the `egress[].port.number` value to any value other than `0` when `egress[].bind` is set to a socket path. This then is a problem when you try to map it to a `ServiceEntry` where we've defined port 443 or 80.

Take this example:

```yaml
# Sidecar spec...
spec:
  egress:
  - bind: unix:///var/run/sockets/httpbin.sock
    hosts:
    - ./httpbin.org
    port:
      name: https
      number: 0
      protocol: HTTPS
  - captureMode: IPTABLES
    hosts:
    - ./*
```

```
# serviceentry spec...
  spec:
    endpoints:
    - address: httpbin.org
    hosts:
    - httpbin.org
    location: MESH_EXTERNAL
    ports:
    - name: http
      number: 80
      protocol: HTTP
      targetPort: 443
    - name: https
      number: 443
      protocol: HTTPS
    resolution: DNS
```

We end up with the following envoy config:
```
ADDRESS                       PORT  MATCH                                                                    DESTINATION
/var/run/sockets/httpbin.sock 0     ALL                                                                      Cluster: outbound|0||httpbin.org
```

The issue is that there is no `outbound|0` service, there is an `outbound|443...` service.

This seems like a bug? Unless the documentation is just unclear to me on how we are supposed to configure the sidecar for this use case.

**Notes on Socket Paths**

Yes, I am aware and have already configured the sidecar to share a volume between the primary container and the `istio-proxy` container. Also, I am aware that there may not be much of a performance reason to do what we are asking ... we are working to migrate a large application from ECS to K8S and into the mesh ... and we are trying to maintain as much that is "the same" during the migration process, just to reduce the number of variables.

### Version

```prose
$ istioctl version
client version: 1.11.0
control plane version: 1.13.2
data plane version: 1.13.2 (18 proxies)
```

```
$ kubectl version --short
Client Version: v1.22.2
Server Version: v1.21.5-eks-bc4871b
```
```


### Additional Information

_No response_

**Comment by hzxuzhonghu** [comment]
Assume you expect taffic to unix:///var/run/sockets/httpbin.sock, will be routed based on port number. But port concept not work with UDS. So Istio sidecar egress do not allow setting port number for uds. Now It can work only for service with one port.

**Comment by diranged** [comment]
@hzxuzhonghu Thanks for the response.. So we just want one socket to point to one port on one service. Eg, `/var/run/sockets/httpbin.sock` -> `https://httpbin.org:443`.

**Comment by diranged** [comment]
@hzxuzhonghu Ok, after reading your message more closely - I tried removing  the extra port (443) from the service entry and suddenly things changed a little bit.

**Here is my updated test configuration**

```yaml
# Source: envoy/templates/test-sts.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: envoy-test-pod
spec:
  serviceName: envoy-test-pod
  replicas: 1
  selector:
    matchLabels:
      monolith.app.com/envoy: default
      envoy.app.com/kind: test-pod
  template:
    metadata:
      annotations:
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
        sidecar.istio.io/userVolumeMount: '[{ "name": "sockets", "mountPath": "/var/run/sockets" }]'
      labels:
        monolith.app.com/envoy: default
        envoy.app.com/kind: test-pod
        sidecar.istio.io/inject: "true"
    spec:
      terminationGracePeriodSeconds: 1
      #securityContext:
      #  runAsUser: 1337
      #  runAsGroup: 1337
      #  fsGroup: 1337

      volumes:
        - name: sockets
      containers:
        - name: test
          image: curlimages/curl:latest
          command: [sh, -c, 'while true; do sleep 5; done']
          volumeMounts:
            - name: sockets
              mountPath: /var/run/sockets
---
# Source: envoy/templates/serviceentries.yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: envoy-httpbin
spec:
  host: httpbin.monolith-test.svc.cluster.local
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE
          sni: httpbin.org
          insecureSkipVerify: true
---
# Source: envoy/templates/envoyfilter.yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: envoy-app-fault-injection
spec:
  workloadSelector:
    labels:
      monolith.app.com/envoy: default
  configPatches:
    - applyTo: HTTP_ROUTE
      match:
        context: ANY
        routeConfiguration:
          vhost:
            route:
              name: inject-delay-route
      patch:
        operation: MERGE
        value:
          typed_per_filter_config:
            envoy.filters.http.fault:
              '@type': type.googleapis.com/envoy.extensions.filters.http.fault.v3.HTTPFault
              delay:
                header_delay: {}
                percentage:
                  numerator: 1000000
                  denominator: MILLION
              headers:
                - name: app-inject-delay
---
# Source: envoy/templates/serviceentries.yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: envoy-httpbin
spec:
  location: MESH_EXTERNAL
  resolution: DNS
  hosts:
    - httpbin.monolith-test.svc.cluster.local
  endpoints:
    - address: httpbin.org
  exportTo:
    - .
  ports:
    - name: http
      protocol: HTTP
      number: 80
      targetPort: 443
---
# Source: envoy/templates/sidecar.yaml
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: envoy
spec:
  workloadSelector:
    labels:
      monolith.app.com/envoy: default
  egress:
    - port:
        protocol: HTTP
        name: http
      bind: unix:///var/run/sockets/httpbin.sock
      captureMode: NONE
      hosts:
        - ./httpbin.monolith-test.svc.cluster.local

    - captureMode: IPTABLES
      hosts:
        - ./*
---
# Source: envoy/templates/serviceentries.yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: envoy-httpbin
spec:
  hosts:
    - httpbin.monolith-test.svc.cluster.local
  exportTo:
    - .
  http:
    - name: inject-fault-route
      route:
        - destination:
            host: httpbin.monolith-test.svc.cluster.local
      match:
        - headers:
            app-inject-fault: {}
      fault:
        abort:
          httpStatus: 500
          percentage:
            value: 100
    - name: inject-delay-route
      route:
        - destination:
            host: httpbin.monolith-test.svc.cluster.local
      match:
        - headers:
            app-inject-delay: {}
      fault:
        delay:
          fixedDelay: 1s
          percentage:
            value: 100
    - route:
      - destination:
          host: httpbin.monolith-test.svc.cluster.local
      retries:
        attempts: 3
        retryOn: connect-failure
```

 I can see now that the `/var/run/sockets/httpbin.sock` points to the httpbin service:
```
$ istioctl proxy-config all envoy-test-pod-0
SERVICE FQDN                                PORT     SUBSET     DIRECTION     TYPE             DESTINATION RULE
BlackHoleCluster                            -        -          -             STATIC           
InboundPassthroughClusterIpv4               -        -          -             ORIGINAL_DST     
InboundPassthroughClusterIpv6               -        -          -             ORIGINAL_DST     
PassthroughCluster                          -        -          -             ORIGINAL_DST     
agent                                       -        -          -             STATIC           
datadog_agent                               -        -          -             STRICT_DNS       
httpbin.monolith-test.svc.cluster.local     80       -          outbound      STRICT_DNS       envoy-httpbin.monolith-test
prometheus_stats                            -        -          -             STATIC           
sds-grpc                                    -        -          -             STATIC           
xds-grpc                                    -        -          -             STATIC           

ADDRESS                       PORT  MATCH                                                                    DESTINATION
/var/run/sockets/httpbin.sock 0     ALL                                                                      Route: unix:///var/run/sockets/httpbin.sock
0.0.0.0                       80    Trans: raw_buffer; App: http/1.1,h2c                                     Route: 80
0.0.0.0                       80    ALL                                                                      PassthroughCluster
0.0.0.0                       15001 ALL                                                                      PassthroughCluster
0.0.0.0                       15001 Addr: *:15001                                                            Non-HTTP/Non-TCP
0.0.0.0                       15006 Addr: *:15006                                                            Non-HTTP/Non-TCP
0.0.0.0                       15006 Trans: tls; App: istio-http/1.0,istio-http/1.1,istio-h2; Addr: ::0/0     InboundPassthroughClusterIpv6
0.0.0.0                       15006 Trans: tls; Addr: ::0/0                                                  InboundPassthroughClusterIpv6
0.0.0.0                       15006 Trans: tls; App: istio-http/1.0,istio-http/1.1,istio-h2; Addr: 0.0.0.0/0 InboundPassthroughClusterIpv4
0.0.0.0                       15006 Trans: tls; Addr: 0.0.0.0/0                                              InboundPassthroughClusterIpv4
0.0.0.0                       15021 ALL                                                                      Inline Route: /healthz/ready*
0.0.0.0                       15090 ALL                                                                      Inline Route: /stats/prometheus*

NAME                                     DOMAINS                                        MATCH                  VIRTUAL SERVICE
80                                       httpbin, httpbin.monolith-test + 1 more...     /*                     envoy-httpbin.monolith-test
80                                       httpbin, httpbin.monolith-test + 1 more...     /*                     envoy-httpbin.monolith-test
80                                       httpbin, httpbin.monolith-test + 1 more...     /*                     envoy-httpbin.monolith-test
unix:///var/run/sockets/httpbin.sock     httpbin, httpbin.monolith-test + 1 more...     /*                     envoy-httpbin.monolith-test
unix:///var/run/sockets/httpbin.sock     httpbin, httpbin.monolith-test + 1 more...     /*                     envoy-httpbin.monolith-test
unix:///var/run/sockets/httpbin.sock     httpbin, httpbin.monolith-test + 1 more...     /*                     envoy-httpbin.monolith-test
                                         *                                              /stats/prometheus*     
                                         *                                              /healthz/ready*        
InboundPassthroughClusterIpv6            *                                              /*                     
InboundPassthroughClusterIpv4            *                                              /*                     

RESOURCE NAME     TYPE           STATUS     VALID CERT     SERIAL NUMBER                               NOT AFTER                NOT BEFORE
default           Cert Chain     ACTIVE     true           279697261862367762381531680801606763517     2022-04-20T13:49:55Z     2022-04-19T13:49:55Z
ROOTCA            CA             ACTIVE     true           111713164068303522463567436186497476554     2031-12-01T20:28:59Z     2021-12-01T19:28:59Z
```

From within the Pod, we can see that `http://httpbin` works, but we are now getting a permissions issue on the unix socket:
```
/run/sockets $ curl http://httpbin/headers 
{
  "headers": {
    "Accept": "*/*", 
    "Host": "httpbin", 
    "User-Agent": "curl/7.82.0-DEV", 
    "X-Amzn-Trace-Id": "Root=1-625ec04d-35460fba4508835e4599a1f0", 
    "X-Datadog-Parent-Id": "4383566898817317965", 
    "X-Datadog-Sampling-Priority": "1", 
    "X-Datadog-Trace-Id": "4383566898817317965", 
    "X-Envoy-Attempt-Count": "1", 
    "X-Envoy-Decorator-Operation": "httpbin.monolith-test.svc.cluster.local:80/*", 
    "X-Envoy-External-Address": "100.64.42.196", 
...
    "X-Envoy-Peer-Metadata-Id": "sidecar~100.64.42.196~envoy-test-pod-0.monolith-test~monolith-test.svc.cluster.local"
  }
}
/run/sockets $ curl --unix-socket /var/run/sockets/httpbin.sock http:/headers -v -k
*   Trying /var/run/sockets/httpbin.sock:0...
* Immediate connect fail for /var/run/sockets/httpbin.sock: Permission denied
* Closing connection 0
curl: (7) Couldn't connect to server
/run/sockets $ 
```

We can see that the unix socket is owned by `1337` and has `755` permissions:
```
/run $ cd /var/run/sockets/
/run/sockets $ ls -la
total 12
drwxrwsrwx    2 root     1337          4096 Apr 19 13:52 .
drwxr-xr-x    1 root     root          4096 Apr 19 13:49 ..
srwxr-xr-x    1 1337     1337             0 Apr 19 13:52 httpbin.sock
/run/sockets $ 
```

So just for the sake of testing the socket, I relaunched the Pod with the security context set:
```yaml
       securityContext:
         runAsUser: 1337
         runAsGroup: 1337
         fsGroup: 1337
```

This breaks the DNS resolution of `http://httpbin` (I think that is intentional), but allows us to hit the socket for now:
```
$ k exec -ti envoy-test-pod-0 -- sh
/ $ id
uid=1337 gid=1337 groups=1337
/ $ ls -la /var/run/sockets
total 12
drwxrwsrwx    2 root     1337          4096 Apr 19 14:02 .
drwxr-xr-x    1 root     root          4096 Apr 19 14:02 ..
srwxr-xr-x    1 1337     1337             0 Apr 19 14:02 httpbin.sock
/ $ curl --unix-socket /var/run/sockets/httpbin.sock http:/headers -v -k
*   Trying /var/run/sockets/httpbin.sock:0...
* Connected to headers (/var/run/sockets/httpbin.sock) port 80 (#0)
> GET / HTTP/1.1
> Host: headers
> User-Agent: curl/7.82.0-DEV
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 503 Service Unavailable
< content-length: 19
< content-type: text/plain
< date: Tue, 19 Apr 2022 14:02:33 GMT
< server: envoy
< 
* Connection #0 to host headers left intact
no healthy upstream/ $ 
```

The istio-proxy logs for that failed request:
```
{"level":"warning","time":"2022-04-19T14:02:34.120221Z","scope":"envoy upstream","msg":"original_dst_load_balancer: No downstream connection or no original_dst."}
{"response_code":503,"bytes_received":0,"downstream_local_address":"/var/run/sockets/httpbin.sock","upstream_transport_failure_reason":null,"request_id":"c8064687-dcb3-917a-874a-47a458208f11","response_flags":"UH","requested_server_name":null,"authorization":null,"connection_termination_details":null,"x_forwarded_for":null,"upstream_cluster":"PassthroughCluster","downstream_remote_address":"/var/run/sockets/httpbin.sock","duration":0,"upstream_local_address":null,"authority":"headers","upstream_service_time":null,"path":"/","bytes_sent":19,"method":"GET","start_time":"2022-04-19T14:02:34.120Z","protocol":"HTTP/1.1","user_agent":"curl/7.82.0-DEV","upstream_host":null,"grpc_status":"Unavailable","response_code_details":"no_healthy_upstream","route_name":"allow_any"}
```

So I guess I have two questions at this point..

1. How can we control the permissions of the socket that is created by Envoy so that it's `777`?
2. Why are we getting the no healthy upstream error?
