### ISSUE TITLE
Circuit breaker does not seem to work on gRPC

### ISSUE THREAD

**Issue by aidanbae** [istio/istio#38425]
### Bug Description

One connection provides manyConcurrentStream in http2, so it doesn’t work properly even if hundreds of requests are slow. I thought `http2MaxRequests` would be the solution to this, but it is not working properly. Could you tell me a solution to this? (istio v1.12.4)

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: example-service-dr
spec:
  host: example-service
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 5
        http2MaxRequests: 5
      tcp:
        maxConnections: 3
```

in this case , i send 100 slow response grpc and all 100 request will be successful.
and how can i get fail-fast strategy on grpc with istio DestinationRule ?

i tried `maxRequestsPerConnection` option too, but it didn't work as expected.

### Version

```prose
istio version 1.12.4
kubernetes version 1.21
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
