### ISSUE TITLE
WasmPlugin does not work

### ISSUE THREAD

**Issue by alolage-devrev** [istio/istio#38433]
### Bug Description

I am installing a WasmPlugin with following configuration. Sidecar of test-service-1 has /var/local/lib/wasm-filters/hello.wasm loaded. Although I don't see wasm plugin working. how can I even confirm if wasm plugin was successfully installed? 
```yaml
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: wasm-example
spec:
  selector:
    matchLabels:
      app: test-service-1
  phase: STATS
  url: file:///var/local/lib/wasm-filters/hello.wasm
```
Service deployment.yaml

```yaml
apiVersion: v1
kind: Service
metadata:
  name: test-service-1
  labels:
    app: test-service-1
    service: test-service-1
spec:
  ports:
  - port: 8001
    name: http
  selector:
    app: test-service-1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-service-1
  labels:
    account: test-service-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-service-1
  labels:
    app: test-service-1-deployment
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-service-1
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/userVolume: '[{"name":"wasmfilters-dir","configMap": {"name": "wasm-filter"}}]'
        sidecar.istio.io/userVolumeMount: '[{"mountPath":"/var/local/lib/wasm-filters","name":"wasmfilters-dir"}]'
      labels:
        app: test-service-1
        version: v1
    spec:
      serviceAccountName: test-service-1
      containers:
      - name: test-service-1
        image: <image location>
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
---
```

### Version

```prose
istioctl version
client version: 1.13.1
control plane version: 1.13.1
data plane version: 1.13.1 (5 proxies)


kubectl version --short
Client Version: v1.23.4
Server Version: v1.20.11-eks-f17b81
WARNING: version difference between client (1.23) and server (1.20) exceeds the supported minor version skew of +/-1
```
