### ISSUE TITLE
External Authz fails when server in a separate namespace

### ISSUE THREAD

**Issue by nmittler** [istio/istio#38451]
### Bug Description

This was discovered while working on https://github.com/istio/istio/pull/37914. Specifically while porting the `TestAuthorization_Custom` to the new framework.

If the external authz server is created in the same namespace as the echo apps, then it works properly (this is the way the test works today). However, if you try to move the authz server to its own namespace, I see:

```
    authz_test.go:1298: failed calling a (cluster=cluster-0)->'http://b.echo1.svc.cluster.local:80/custom': call failed from a (cluster=cluster-0) to http://b.echo1.svc.cluster.local:80/custom (using http): 5 errors occurred:
        	* response[0]: expected response code `200`, got "403". Response: RawContent:       [0] Url=http://b.echo1.svc.cluster.local:80/custom
        [0] StatusCode=403
        [0] ResponseHeader=Content-Length:0
        [0] ResponseHeader=Date:Tue, 19 Apr 2022 16:53:45 GMT
        [0] ResponseHeader=Server:envoy
        [0] ResponseHeader=X-Envoy-Upstream-Service-Time:1
        
        ID:               
        Method:           
        Protocol:         
        Alpn:             
        URL:              
        Version:          
        Port:             
        Code:             403
        Host:             
        Hostname:         
        Cluster:          
        IstioVersion:     
        IP:               
        Request Headers:  map[]
        Response Headers: map[Content-Length:[0] Date:[Tue, 19 Apr 2022 16:53:45 GMT] Server:[envoy] X-Envoy-Upstream-Service-Time:[1]]
```

### Version

```prose
master (head)
```

**Comment by howardjohn** [comment]
Do we have a Sidecar restricting visibility of it maybe

**Comment by nmittler** [comment]
> Do we have a Sidecar restricting visibility of it maybe

No, the test is pretty simple. All there is to the deployment is: https://github.com/istio/istio/blob/master/samples/extauthz/ext-authz.yaml

**Comment by yangminzhu** [comment]
Could you get the logs of the external authz server?

**Comment by nmittler** [comment]
Just to follow-up, the logs were provided off-line. You indicated that the issue is that the authz server always allows requests from app `a`: https://github.com/istio/istio/blob/6da7a3193970e46ebe6cf748f6411f1de1d286ec/samples/extauthz/src/main.go#L82

**Comment by yangminzhu** [comment]
@nmittler I think this is a different issue (deploying authz server in a separate namespace) and not related to my answer off-line.

I couldn't reproduce this by following https://istio.io/latest/docs/tasks/security/authorization/authz-custom/ (but deploy the authz server in namespace `bar` and sleep/httpbin in ns `foo`), so I suspect it's something wrong in the test code changes.

**Comment by nmittler** [comment]
@yangminzhu were you testing with the "local" provider on "127.0.0.1", or the regular provider?

I'm testing with the regular provider. The authz server is in the `ext-authz` namespace, while the echo apps are in the `echo1` namespace.  My patched mesh config looks like this:

```yaml
accessLogFile: /dev/stdout
defaultConfig:
  discoveryAddress: istiod.istio-system.svc:15012
  gatewayTopology:
    numTrustedProxies: 1
  proxyMetadata:
    ISTIO_META_DNS_CAPTURE: "true"
  tracing:
    zipkin:
      address: zipkin.istio-system:9411
defaultHttpRetryPolicy: {}
enablePrometheusMerge: true
extensionProviders:
- envoyExtAuthzHttp:
    headersToDownstreamOnDeny:
    - x-ext-authz-*
    headersToUpstreamOnAllow:
    - x-ext-authz-*
    includeAdditionalHeadersInCheck:
      x-ext-authz-additional-header-new: additional-header-new-value
      x-ext-authz-additional-header-override: additional-header-override-value
    includeRequestHeadersInCheck:
    - x-ext-authz
    pathPrefix: /check
    port: 8000
    service: ext-authz.ext-authz.svc.cluster.local
  name: ext-authz-http
- envoyExtAuthzGrpc:
    port: 9000
    service: ext-authz.ext-authz.svc.cluster.local
  name: ext-authz-grpc
rootNamespace: istio-system
trustDomain: cluster.local
```

Here is example of an authz policy for HTTP requests to one of the echo apps:

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: custom-b
  namespace: echo1
spec:
  action: CUSTOM
  provider:
    name: ext-authz-http
  rules:
  - to:
    - operation:
        methods:
        - GET
        paths:
        - /custom
        ports:
        - "18080"
        - "18085"
  - to:
    - operation:
        methods:
        - POST
        paths:
        - /proto.EchoTestService/Echo
        ports:
        - "17070"
  - to:
    - operation:
        ports:
        - "19090"
  selector:
    matchLabels:
      app: b
```

For which the response appears to be forbidden before it even reaches the authz server:

```
failed calling a (cluster=cluster-0)->'http://b.echo1.svc.cluster.local:80/custom': call failed from a (cluster=cluster-0) to http://b.echo1.svc.cluster.local:80/custom (using http): 5 errors occurred:
        	* response[0]: expected response code `200`, got "403". Response: RawContent:
        [0] Url=http://b.echo1.svc.cluster.local:80/custom
        [0] StatusCode=403
        [0] ResponseHeader=Content-Length:0
        [0] ResponseHeader=Date:Thu, 21 Apr 2022 15:00:51 GMT
        [0] ResponseHeader=Server:envoy
        [0] ResponseHeader=X-Envoy-Upstream-Service-Time:4
```

**Comment by yangminzhu** [comment]
I'm testing with regular provider as well. Can you include the both Envoy (enabled with debug logging) and the authz server?

**Comment by yangminzhu** [comment]
By the way, I just noticed you have `pathPrefix: /check` in the mesh config, are you using your own authz server? The example authz server does not use this path, see the example config in https://istio.io/latest/docs/tasks/security/authorization/authz-custom/#define-the-external-authorizer:

```
data:
  mesh: |-
    # Add the following content to define the external authorizers.
    extensionProviders:
    - name: "sample-ext-authz-grpc"
      envoyExtAuthzGrpc:
        service: "ext-authz.foo.svc.cluster.local"
        port: "9000"
    - name: "sample-ext-authz-http"
      envoyExtAuthzHttp:
        service: "ext-authz.foo.svc.cluster.local"
        port: "8000"
        includeRequestHeadersInCheck: ["x-ext-authz"]
```
