### ISSUE TITLE
Can delegate virtual service support two ports? Thanks.

### ISSUE THREAD

**Issue by johnzheng1975** [istio/istio#38474]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
I am using delegate service to integrate public virtual service and mesh virtual service, to implement canary testing.
However, when my container has two ports (like one restful, and one grpc)
It fail.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

I create a delegate virtual service.
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: mytwoports
  namespace: test
  ownerReferences:
  - apiVersion: flagger.app/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: Canary
    name: backend-twoports-http
    uid: 0a664c21-d2c6-4293-81ea-6e5049710ec2
spec:
  hosts: []
  http:
  - route:
    - destination:
        host: mytwoports-primary
      weight: 100
    - destination:
        host: mytwoports-canary
      weight: 0

```

Then I create two public virtual service to integrate with this delegate virtual service, since there are two ports in this container.
- For restful path (hello), should go to port 80
- For grpc path (world), should go to port 8082

virtualservice for restful is like
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-mytwoports-http
  namespace: test
spec:
  gateways:
    - istio-system/public-gateway1 
    - mesh
  hosts:
    - a3b8d47ae72f840b69819f885da58f8d-1226767540.us-west-2.elb.amazonaws.com 
    - mytwoports
    - mytwoports.test
    - mytwoports.test.svc.cluster.local
  http:
  - match:
    - port: 80  # want go to port 80, for prefix is /hello
    - uri:
        prefix: /hello  
    delegate:
      name: mytwoports
      namespace: test
```

virtualservice for restful is like
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-mytwoports-http-2nd
  namespace: test
spec:
  gateways:
    - istio-system/public-gateway1 
    - mesh
  hosts:
    - a3b8d47ae72f840b69819f885da58f8d-1226767540.us-west-2.elb.amazonaws.com 
    - mytwoports
    - mytwoports.test
    - mytwoports.test.svc.cluster.local
  http:
  - match:
    - port: 8082
    - uri:
        prefix: /world
    delegate:
      name: mytwoports
      namespace: test
```

After deploy, 8081 can work, but 8082 does not work.

I think the port: xx in virtual service may diff with port in routes. 
Is there any way to implement my requirement: 
Combine with delegate vs, we can implement canary for two ports on the single service, Thanks a lot.

**Comment by howardjohn** [comment]
```
  - match:
    - port: 80  # want go to port 80, for prefix is /hello
    - uri:
        prefix: /hello  
```

This means port 80 OR /hello, not AND. Since its coming from the gateway probbly the port is always 80 so it always uses that
