### ISSUE TITLE
Using separate virtual service,  canary cannot be implemented for one service has two ports (like: one http, another grpc)

### ISSUE THREAD

**Issue by johnzheng1975** [istio/istio#38479]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
That is say, there is one service has two ports (like: one http, another grpc)
- For grpc request (based on its path) go to port 3000 
- For restful request  (based on its path) go to port 80

**Why need use separate service?**
Because canary project like flagger will create its own virtual service in mesh.
It is better for user to create another virtual service connect to gateway.
This is more flexible.

**Can delegate virtual service works?**
- For one port service, using delegate virtual service works.
- For two ports service, using delegate virtual service seems not work  
see https://github.com/istio/istio/issues/38474

So I want to use normal separate virtual service without delegate. 
Finally, when I do canary testing with the load from alb, the load cannot enter canary pod at all.

create two deploy with two ports.
```
apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: mytwoports
    name: mytwoports
    namespace: test
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: mytwoports
    template:
      metadata:
        labels:
          app: mytwoports
      spec:
        containers:
        - image: johnzheng/mytwoports:1.0
          name: mytwoportsd
          ports:
          - containerPort: 8081
            name: http-n1
            protocol: TCP
          - containerPort: 8082
            name: http-n2
            protocol: TCP

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: mytwoports-primary
    namespace: test
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: mytwoports-primary
    template:
      metadata:
        labels:
          app: mytwoports-primary
      spec:
        containers:
        - image: johnzheng/mytwoports:1.0
          imagePullPolicy: Always
          name: mytwoportsd
          ports:
          - containerPort: 8081
            name: http-n1
            protocol: TCP
          - containerPort: 8082
            name: http-n2
            protocol: TCP
          
```

Create virtual service in mesh
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: mytwoports
  namespace: test
spec:
  gateways:
  - mesh
  hosts:
  - mytwoports
  http:
  - route:
    - destination:
        host: mytwoports-primary
      weight: 50
    - destination:
        host: mytwoports-canary
      weight: 50
```
Create two destination rule
```
# kubectl  get dr -A 
NAMESPACE   NAME                 HOST                 AGE
test        mytwoports-canary    mytwoports-canary    61m
test        mytwoports-primary   mytwoports-primary   61m
```

Create virtual service for grpc load from aws alb
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: normal-mytwoports-http-2nd
  namespace: test
spec:
  gateways:
    - istio-system/public-gateway1 
  hosts:
    - a3b8d47ae72f840b69819f885da58f8d-1226767540.us-west-2.elb.amazonaws.com 
  http:
  - match:
    - uri:
        prefix: /world
    route:
    - destination:
        host: mytwoports
        port:
          number: 8082
```

Create virtual service for http load from aws alb
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: normal-mytwoports-http-1st
  namespace: test
spec:
  gateways:
    - istio-system/public-gateway1 
  hosts:
    - a3b8d47ae72f840b69819f885da58f8d-1226767540.us-west-2.elb.amazonaws.com 
  http:
  - match:
    - uri:
        prefix: /hello
    route:
    - destination:
        host: mytwoports
        port:
          number: 80
```

Create three service for canary
```
# kubectl  get svc -n test 
NAME                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)           AGE
mytwoports           ClusterIP   10.100.111.186   <none>        80/TCP,8082/TCP   64m
mytwoports-canary    ClusterIP   10.100.2.216     <none>        80/TCP,8082/TCP   65m
mytwoports-primary   ClusterIP   10.100.161.83    <none>        80/TCP,8082/TCP   65m
```

Testing from outside cluster  -- **fail**
```
 curl a3b8d47ae72f840b69819f885da58f8d-1226767540.us-west-2.elb.amazonaws.com/world;e
```
Actual result: all load enter mytwoports-primary pod, none of them enter mytwoports pod.
Expect result: should 50% enter mytwoports-primary, 50% enter mytwoports 

Testing from inside cluster  -- **pass**
```
root@nginx:/# curl mytwoports.test/hello
root@nginx:/# curl mytwoports.test:8082/world
```
Actual result is correct: 50% enter mytwoports-primary, 50% enter mytwoports 
 

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
