### ISSUE TITLE
httpCookie Session affinity doesn't work with HTTPS virtual service (tls terminated)

### ISSUE THREAD

**Issue by xudesheng** [istio/istio#38507]
### Bug Description

This is a migration from Nginx ingress:
```
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "SERVER"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    kubernetes.io/ingress.class: nginx
```
I understand that the TLS must [be terminated](https://preliminary.istio.io/latest/docs/ops/configuration/traffic-management/tls-configuration/). 
**The gateway**:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: hagateway
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: httpbin-credential-system
    hosts:
    - istio.mydemo.io
```
**The Virtual Service**:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ha-myapp-svc
spec:
  hosts:
  - "istio.mydemo.io"
  gateways:
  - hagateway
  http:
  - match:
    - uri:
        prefix: /Myapp
    route:
    - destination:
        port:
          number: 8443
        host: ha-myapp
```
**The Destination rule**:
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ha-myapp
spec:
  host: ha-myapp
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: SERVER
          ttl: 0s
    portLevelSettings:
    - port:
        number: 8443
      tls:
        mode: SIMPLE
```
The cookie generated with Nginx: 
`
JSESSIONID=5F77541E722232C900432CFC3E455E01; SERVER=1649775315.885.177.52566|525dde1cac1116066211e6139d80202f
`
The cookie generated with Istio:
`
JSESSIONID=D3F5F576D03472CDB0E869EC9A61E62B
`

### Version

```prose
istioctl version:
client version: 1.13.2
control plane version: 1.13.2
data plane version: 1.13.2 (2 proxies)

kubectl version --short:
Client Version: v1.22.0
Server Version: v1.21.9

helm version --short:
v3.7.0+geeac838
```

### Additional Information

AKS 1.21.9 and No sidecar installed since I want to migrate the ingress first.
