### ISSUE TITLE
AuthorizationPolicy different behavior for workloads.

### ISSUE THREAD

**Issue by DaviSoares454** [istio/istio#38537]
### Bug Description

Hello, all!
I have a monitoring stack (kiali, jeager, grafana, prometheus), and the idea was to restrict access to each app by using AuthorizationPolicies and filtering based on user roles from a JWT. 

There is a manifests used to that.
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: prometheus-app-require-jwt-auth
  namespace: monitoring
spec:
  action: DENY
  rules:
    - from:
        - source:
            principals: ["*"]
      when:
        - key: request.auth.claims[roles]
          notValues: 
            - "app__monitoring__*"
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
``` 

Applying the same manifest model worked to every workloads, but one: Grafana. When accessing the Grafana's URL, the following was returned:
``` upstream connect error or disconnect/reset before headers. reset reason: connection termination  ``` 

### Then, I created a new cluster to test only isolated Grafana Operator deploy.

I created a local development cluster to test grafana operator with Istio and AuthorizationPolicies, using K3D.

Using curl from outside the cluster through kubernetes ingress, **with no authpolicy**, all works fine. When connecting to main Grafana URL, it redirects to /login. But when accessing this way, from outside the cluster, these requests made to Grafana aren't shown in its istio-proxy logs.

When using curl from a container inside the cluster, also without authpolicies, it redirects the same way as the other case, regardless of namespaces. But, this time, the requests are shown in grafana's istio-proxy container.

After creating a authpolicy to DENY all requests to Grafana, accessing from inside the cluster returns "RBAC: access denied", just **the way it is supposed to**. But by accessing through ingress, it returns "upstream connect error or disconnect/reset before headers. reset reason: connection termination".

The real problem with this is that, even that the user has the right role (validated by other workloads policies), it just gets this `upstream connect error or disconnect/reset before headers. reset reason: connection termination` message.

I would appreciate any help.
Thanks!!

### Version

```prose
$ istioctl version
client version: 1.11.0
control plane version: 1.11.0
data plane version: 1.11.0 (5 proxies)
$ kubectl version --short
Client Version: v1.23.3
Server Version: v1.21.5+k3s1
$ helm version --short
v3.7.1+g1d11fcb

bitnami/grafana-operator
Chart Version: 2.3.7
App Version: 4.2.0
```

### Additional Information

[bug-report.tar.gz](https://github.com/istio/istio/files/8544161/bug-report.tar.gz)
