### ISSUE TITLE
Question about Istio Standard Metrics missing in application pod 

### ISSUE THREAD

**Issue by Jackson-Stard** [istio/istio#38539]
### Bug Description

I am new hand for Istio, and I found that I cannot get Istio Standard Metrics in my own application pod, but it works well if I deploy bookinfo in my cluster. 
I spent more time to figure it out, but failed, I think it should be something wrong with my application pod, maybe missing some configuration, could anyone happen to know how to fix it?

my test application is webtest, it is quite simple just one api call, istio injection is enabled.
![image](https://user-images.githubusercontent.com/104239579/164861603-dd706f2f-04e8-4619-b14a-bc8a2df5e9b0.png)

I can see the istio_requests_total metric from istio ingress gateway through localhost:15000/stats/prometheus, same as bookinfo, but I cannot see it in my webtest pod.

The log for istio-proxy in my webtest pod is like below: the request id is null, and it is quite different with bookinfo
![image](https://user-images.githubusercontent.com/104239579/164861840-71056a7e-6a5a-4cb1-9eb9-f7d11496a835.png)

Thanks for you help!

### Version

```prose
$ istioctl version
client version: 1.13.1
control plane version: 1.13.1
data plane version: 1.13.1 (11 proxies)

$ kubectl version --short
Client Version: v1.23.4
Server Version: v1.21.10
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1

$ helm version --short
v3.8.0+gd141386
```

**Comment by zirain** [comment]
can you share the config_dump of the `webtest` pod?

**Comment by Jackson-Stard** [comment]
this 

> can you share the config_dump of the `webtest` pod?

the file is quite big, what do you want to see

![image](https://user-images.githubusercontent.com/104239579/164874691-fa73d952-7863-421b-9f2d-e70f4a183c32.png)

**Comment by Jackson-Stard** [comment]
> can you share the config_dump of the `webtest` pod?
[config_dump.txt](https://github.com/istio/istio/files/8546115/config_dump.txt)
I attached the config_dump file, thanks.

**Comment by Jackson-Stard** [comment]
> can you share the config_dump of the `webtest` pod?

I checked the config_dump, I did not find inbound  router for webtest.promtest.svc.cluster.local:80/*, but I find inbound route for productpage.bookinfo.svc.cluster.local:9080/*.

I am wondering why there is no inbound route for webtest.

**Comment by zirain** [comment]
do you follow [this](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#explicit-protocol-selection)?

**Comment by Jackson-Stard** [comment]
> do you follow [this](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#explicit-protocol-selection)?

My service definition like this, oh, I should use http, right?
---
apiVersion: v1
kind: Service
metadata:
  namespace: promtest
  name: webtest
spec:
  selector:
    app: webtest
  ports:
    - protocol: TCP
      port: 9876
      name: tcp-webtest
      targetPort: 80

**Comment by Jackson-Stard** [comment]
it looks it works if I change it to http

**Comment by zirain** [comment]
@Jackson-Stard can we close this?

**Comment by Jackson-Stard** [comment]
> @Jackson-Stard can we close this?

sure, thanks for your help

**Comment by harsh4870** [comment]
@zirain  i am facing same issue but changing the service type not helping much. 

this is my service 

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: test-service
  name: test-svc
spec:
  ports:
  - name: sai-tomcat-port
    port: 4430
    protocol: TCP
    targetPort: 4430
  - name: om-port
    port: 2322
    protocol: TCP
    targetPort: 2322
  selector:
    app.kubernetes.io/instance: test-components
    app.kubernetes.io/name: test-components
    app.siebel.tier: test
  sessionAffinity: None
  type: ClusterIP
```

what I am trying is from another POD just sending **curl** to this service. 

`curl telnet://servicename.namespace:port` but i am not able to get standard metrics only. 

If you could please help.
