### ISSUE TITLE
Pilot - /v1/routes not generating route clusters correctly

### ISSUE THREAD

**Issue by nmnellis** [istio/istio#3855]
When running envoy in `- router` configuration i was seeing 503 NR errors when trying to route dns hosts to my backend. 
I was seeing this error in the logs
```
[2018-03-01T02:16:41.974Z] "GET /health HTTP/1.1" 503 NR 0 0 0 - "174.82.221.133, 172.28.53.0" "curl/7.54.0" "7ab14c4c-332c-9205-bbc7-95fc512d08ef" "my-app.weather.com" "-"
[2018-03-01 02:16:52.882][28][debug][router] external/envoy/source/common/router/router.cc:235] [C260][S13978584865141312896] unknown cluster 'out.my-app.istio-system.svc.cluster.local|http'

```

I determined that whatever suffix you add to the `/v1/routes` call to pilot is what is added to the cluster service as well 

Example 1 "http://istio-pilot:15003/v1/routes/80/istio-ingress/router~~istio-ingress-85cfcfc7b6-c5fh5.istio-system~istio-system.svc.cluster.local"
Routes Cluster response       `"cluster": "out.my-app.istio-system.svc.cluster.local|http"`

Example 2 "http://istio-pilot:15003/v1/routes/80/istio-ingress/router~~istio-ingress-85cfcfc7b6-c5fh5.istio-system~FAKEVALUE.svc.cluster.local"
Routes Cluster response       `"cluster": "out.my-app.FAKEVALUE.svc.cluster.local|http"`

Example route rule not in istio-system namespace
```yaml
---
apiVersion: config.istio.io/v1alpha2
kind: V1alpha2RouteRule
metadata:
  name: my-app
  namespace: rc-dev
spec:
  hosts:
  - my-app.weather.com
  gateways:
  - istio-ingress
  http:
  - route:
    - destination:
        name: my-app
```

Pilot /v1/routes call 
```
 root@istio-ingress-85cfcfc7b6-c5fh5:/# curl "http://istio-pilot:15003/v1/routes/80/istio-ingress/router~~istio-ingress-85cfcfc7b6-c5fh5.istio-system~istio-system.svc.cluster.local"
{
  "virtual_hosts": [
   {
    "name": "istio-ingress|80|my-app.weather.com",
    "domains": [
     "my-app.weather.com:80",
     "my-app.weather.com"
    ],
    "routes": [
     {
      "prefix": "/",
      "cluster": "out.my-app.istio-system.svc.cluster.local|http",
      "timeout_ms": 0,
      "decorator": {
       "operation": "my-app"
      }
     }
    ]
   },
```
