### ISSUE TITLE
EnvoyFilter cannot guarantee idempotency for route configuration

### ISSUE THREAD

**Issue by cywang1905** [istio/istio#38553]
### Bug Description

EnvoyFilter supports removing and adding VIRTUAL_HOST. But if you remove and then add the same VIRTUAL_HOST in the same EnvoyFilter, the result is removing. This violates the idempotency.

For example, the initial RDS configuration is as follows, contains the VIRTUAL_HOST "allow_any"
```json
[
    {
        "name": "9090",
        "virtualHosts": [
            {
                "name": "allow_any",
                "domains": [
                    "*"
                ],
                "routes": [
                    {
                        "name": "allow_any",
                        "match": {
                            "prefix": "/"
                        },
                        "route": {
                            "cluster": "PassthroughCluster",
                            "timeout": "0s",
                            "maxGrpcTimeout": "0s"
                        }
                    }
                ],
                "includeRequestAttemptCount": true
            },
            {
                "name": "prometheus.istio-system.svc.cluster.local:9090",
                "domains": [
                    "prometheus.istio-system.svc.cluster.local",
		     // ...
                ],
                "routes": [
                    {
 			// ...
                    }
                ],
                "includeRequestAttemptCount": true
            }
        ],
        "validateClusters": false
    }
]
```
The following EnvoyFilter will cause the VIRTUAL_HOST "allow_any" to be removed. But actually, I hope it doesn't change.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: remove-add-test
  namespace: default
spec:
  configPatches:
  - applyTo: VIRTUAL_HOST
    match:
      context: SIDECAR_OUTBOUND
      routeConfiguration:
        name: "9090"
        vhost:
          name: allow_any
    patch:
      operation: REMOVE
  - applyTo: ROUTE_CONFIGURATION
    match:
      context: SIDECAR_OUTBOUND
      routeConfiguration:
        name: "9090"
    patch:
      operation: MERGE
      value:
        virtual_hosts:
        - domains:
          - '*'
          name: allow_any
          routes:
          - match:
              prefix: /
            route:
              cluster: PassthroughCluster
```

I've looked at the source code and I think the problem is in the processing logic of rc_patch.go. 
https://github.com/istio/istio/blob/b55bf1a7debc0ce0081e91ad25694e839737512b/pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch.go#L51-L64
In function `ApplyRouteConfigurationPatches`, merge was executed first, followed by the remove contained in function `patchVirtualHosts`. This is inconsistent with the order of patch in the above EnvoyFilter.
I think maybe we should execute remove before merge.

### Version

```prose
hazard@hazard-VirtualBox:~$ istioctl version
client version: 1.13.2
control plane version: 1.13.3
data plane version: 1.13.3 (8 proxies)
hazard@hazard-VirtualBox:~$ kubectl version --short
Client Version: v1.23.6
Server Version: v1.20.7
```
