### ISSUE TITLE
Adding a New Hostname to Sidecar Egress hosts causes imported Service Entry to break 

### ISSUE THREAD

**Issue by crhuber** [istio/istio#38556]
### Bug Description

If you:
1)  create `serviceB` 
2) create `serviceEntryB` (a  wildcard exported `ServiceEntry`  in  namespace  `b`)
3) and add both the service FQDN of `serviceB` and the serviceEntry  `serviceEntryB` to the  `egress.hosts` of the `Sidecar` resource of a `workloadA` in namespace `a`  
4) will cause all the `serviceEntryB` config  to be removed from istio-proxy on `workloadA` 

To reproduce:
1) Create a Facebook `ServiceEntry`  in `platform` namespace

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: apiv2-facebook-external
  namespace: platform
spec:
  exportTo:
  - '*'
  hosts:
  - www.facebook.com
  - graph.facebook.com
  location: MESH_EXTERNAL
  ports:
  - name: https
    number: 443
    protocol: HTTPS
  resolution: NONE
```

2) Add  Facebook `ServiceEntry` to the default sidecar of `istio-demo` namespace 

```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: default
  namespace: istio-demo
spec:
  egress:
  - hosts:
    - '*/*.facebook.com'
```

3) Everything looks good. The proxy-config clusters show the facebook.com hosts

```
istioctl1132 proxy-config clusters curl-dbb8894fc-5pktf
SERVICE FQDN                                                PORT      SUBSET     DIRECTION     TYPE             DESTINATION RULE
BlackHoleCluster                                            -         -          -             STATIC
InboundPassthroughClusterIpv4                               -         -          -             ORIGINAL_DST
InboundPassthroughClusterIpv6                               -         -          -             ORIGINAL_DST
PassthroughCluster                                          -         -          -             ORIGINAL_DST
agent                                                       -         -          -             STATIC
graph.facebook.com                                          443       -          outbound      ORIGINAL_DST
prometheus_stats                                            -         -          -             STATIC
sds-grpc                                                    -         -          -             STATIC
www.facebook.com                                            443       -          outbound      ORIGINAL_DST
xds-grpc                                                    -         -          -             STATIC
zipkin                                                      -         -          -             STRICT_DNS
```

4)  Add  ServiceB  in the `platform` namespace to the default sidecar of `istio-demo` namespace .

```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: default
  namespace: istio-demo
spec:
  egress:
  - hosts:
    - '*/*.facebook.com'
    - platform/serviceB.platform.svc.cluster.local
```

5) All `ServiceEntry`s will be removed from cluster config

```
istioctl1132 proxy-config clusters curl-dbb8894fc-5pktf
SERVICE FQDN                                                 PORT      SUBSET     DIRECTION     TYPE             DESTINATION RULE
BlackHoleCluster                                             -         -          -             STATIC
InboundPassthroughClusterIpv4                                -         -          -             ORIGINAL_DST
InboundPassthroughClusterIpv6                                -         -          -             ORIGINAL_DST
PassthroughCluster                                           -         -          -             ORIGINAL_DST
agent                                                        -         -          -             STATIC
prometheus_stats                                             -         -          -             STATIC
serviceB.platform.svc.cluster.local                              80        -          outbound      EDS              serviceB.platform
sds-grpc                                                     -         -          -             STATIC
xds-grpc                                                     -         -          -             STATIC
zipkin                                                       -         -          -             STRICT_DNS
```

ServiceB does have a DR & VS associated but removing the DR didn't make any difference 

### Version

```prose
client version: 1.13.2
control plane version: 1.13.2
data plane version: 1.13.2 (2064 proxies), 1.12.1 (1 proxies)

Client Version: v1.22.2
Server Version: v1.21.5-eks-bc4871b
```
