### ISSUE TITLE
Authorization Policy rule values from request headers

### ISSUE THREAD

**Issue by krishnakumar797** [istio/istio#38589]
**Currently Authorization policy rules condition values are only supported with static string values, what I need is to verify the request header value with JWT claims. Is there any way I can check the same per http route**

Looking for something like this

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: detail-auth
  namespace: bookinfo
spec:
  action: ALLOW
  selector:
    matchLabels:
      app: details
  rules:
  - to:
    - operation:
        methods: ["GET"]
        paths: ["/details/*"]
    when:
    - key: request.auth.claims[permissions]
      values: request.headers[x-customer-id] -> is it possible to do like this?
    - key: request.auth.claims[permissions]
      values: [PAYMENTS_READ]
```

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ X] Docs
[ X] Installation
[ ] Networking
[ ] Performance and Scalability
[ X] Extensions and Telemetry
[ X] Security
[ X] Test and Release
[ X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
