### ISSUE TITLE
DestinationRule. trafficPolicy don't work for ServiceEntry with VIPs

### ISSUE THREAD

**Issue by zhj-hx** [istio/istio#38614]
### Bug Description

I also encountered the same problem,,When I created ServiceEntry and DestinationRule for host "svc", trafficPolicy is not applied. However, it works, for hosts "svc.se", "svc.something" "svc.whatever"
[https://github.com/istio/istio/issues/29572](url)

### Version

```prose
istio version 1.11
meshconfig
outboundTrafficPolicy.mode=REGISTRY_ONLY
proxyMetadata:
ISTIO_META_DNS_AUTO_ALLOCATE: "true"
ISTIO_META_DNS_CAPTURE: "true"
```

### Additional Information

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: test
  labels:
    app: test
spec:
  hosts:
  - test
  exportTo:
    - "."
  ports:
    - number: 22
      name: ssh
      protocol: TCP
  resolution: STATIC
  location: MESH_EXTERNAL
  endpoints:
    - address: 1.1.1.1
      ports:
        ssh: 22
      labels:
        node: cns0
    - address: 1.1.1.2
      ports:
        ssh: 22
      labels:
        node: cns1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: test
spec:
  host: test
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      mode: DISABLE
    connectionPool:
      tcp:
        maxConnections: 1
        connectTimeout: 3ms
        tcpKeepalive:
          time: 10s
          interval: 2s
          probes: 2
    outlierDetection:
      consecutiveGatewayErrors: 3
      consecutive5xxErrors: 3
      interval: 5s
      baseEjectionTime: 30s
```

```json
{
	"version_info": "2022-04-27T06:27:18Z/81",
	"cluster": {
		"@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
		"name": "outbound|22||test",
		"type": "EDS",
		"eds_cluster_config": {
			"eds_config": {
				"ads": {},
				"initial_fetch_timeout": "0s",
				"resource_api_version": "V3"
			},
			"service_name": "outbound|22||test"
		},
		"connect_timeout": "10s",
		"circuit_breakers": {
			"thresholds": [{
				"max_connections": 4294967295,
				"max_pending_requests": 4294967295,
				"max_requests": 4294967295,
				"max_retries": 4294967295,
				"track_remaining": true
			}]
		},
		"metadata": {
			"filter_metadata": {
				"istio": {
					"default_original_port": 22,
					"services": [{
						"name": "test",
						"namespace": "cloud",
						"host": "test"
					}]
				}
			}
		},
		"filters": [{
			"name": "istio.metadata_exchange",
			"typed_config": {
				"@type": "type.googleapis.com/udpa.type.v1.TypedStruct",
				"type_url": "type.googleapis.com/envoy.tcp.metadataexchange.config.MetadataExchange ",
				"value": {
					"protocol": "istio-peer-exchange"
				}
			}
		}]
	},
	"last_updated": "2022-04-27T06:27:19.362Z"
}
```
