### ISSUE TITLE
Allow RequestAuthentication to pass for invalid tokens

### ISSUE THREAD

**Issue by 0ff** [istio/istio#38615]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
We are using Istio with JWT by setting up a RequestAuthentication per namespace + one AuthorizationPolicy per service.
In the AuthorizationPolicy we require a certain set of claims from the JWT, such as a certain role or other values.

JWTs are saved into cookies and sent by the user automatically.

All our JWTs are set to expire at some point (exp) and the Envoy Filter `envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication` correctly checks for the token to still be valid.
Unfortunately, in the case of an expired token, we only get the default "Jwt token is expired" message and there's no way to clear, for example, a token saved in a cookie (or communicate with the customer at all).
Now in order to solve that, we'd like to set the `requirements` for this filter to `allowMissingOrFailed` as per the envoy docs: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto#envoy-v3-api-field-extensions-filters-http-jwt-authn-v3-jwtrequirement-allow-missing-or-failed

We understand that this means we will have to take care to filter invalid requests in the AuthorizationPolicy because now it might happen that a request with an invalid token is passed to the service. Note however, that all JWT claims on the request are, as expected, empty in case of invalid or expired tokens.

So the change is: instead of a 401, the service is passed the request and all relevant AuthorizationPolicies are applied.
What needs to be done in istio is: we need a way to configure the policy-applier ([code](https://github.com/istio/istio/blob/8909a25c99e34e98039ad233b0afb4140490a682/pilot/pkg/security/authn/v1beta1/policy_applier.go#L290)) to set the requirement to `allowMissingOrFailed` instead.

**Describe alternatives you've considered**

Our current workaround is to replace the filter that is generated and that works as expected:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: allow-invalid-jwt
spec:
  configPatches:
    # make sure to allow ALL requests even if jwt is invalid. Filtering needs to be done later in the chain
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: "envoy.filters.http.jwt_authn"
      patch:
        operation: REPLACE
        value:
          name: envoy.filters.http.jwt_authn
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
            providers:
              {
                "origins-0":
                  {
                    "issuer": "our-jwt-issuer",
                    "localJwks":
                      {
                        "inlineString": "{\n  \"keys\":[ \n    {\n      \"e\":\"AQAB\",\n      \"kid\":\"DHFbpoIUqrY8t2zpA2qXfCmr5VO5ZEr4RzHU_-envvQ\",\n      \"kty\":\"RSA\",\n      \"n\":\"xAE7eB6qugXyCAG3yhh7pkDkT65pHymX-P7KfIupjf59vsdo91bSP9C8H07pSAGQO1MV_xFj9VswgsCg4R6otmg5PV2He95lZdHtOcU5DXIg_pbhLdKXbi66GlVeK6ABZOUW3WYtnNHD-91gVuoeJT_DwtGGcp4ignkgXfkiEm4sw-4sfb4qdt5oLbyVpmW6x9cfa7vs2WTfURiCrBoUqgBo_-4WTiULmmHSGZHOjzwa8WtrtOQGsAFjIbno85jp6MnGGGZPYZbDAa_b3y5u-YpW7ypZrvD8BgtKVjgtQgZhLAGezMt0ua3DRrWnKqTZ0BJ_EyxOGuHJrLsn00fnMQ\"\n    }\n  ]\n}",
                      },
                    "forward": true,
                    "forwardPayloadHeader": "X-ORIGINAL-JWT",
                    "payloadInMetadata": "our-jwt-issuer",
                  },
              }
            rules:
              [
                {
                  "match": { "prefix": "/" },
                  "requires":
                    {
                      "requiresAny":
                        {
                          "requirements":
                            [
                              { "providerName": "origins-0" },
                              { "allowMissingOrFailed": {} }{{/* this is why we do this all. 
                                  istio sets this to "allowMissing" and explicitly disallows any invalid JWT.
                                  However, we need to be able to handle invalid tokens inside the frontend and other services.
                                  Make sure to set an AuthorizationPolicy that checks for claims if you want your service to be safe.
                              */}},
                            ],
                        },
                    },
                },
              ]
```

We understand that this is against your idea stated here https://github.com/istio/istio/issues/24371#issuecomment-641481054 and we don't want to impose a different idea on everyone.
Instead, we want to ask if you were open to taking a pull request that would make this requirement configurable or if you'd reject this from the get-go.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

This would allow to actually resolve the following issue:
* https://github.com/istio/istio/issues/24371
