### ISSUE TITLE
Need to remove unnecessary AuthorizationPolicies from gateway listener's TLS/HTTPS filter chain 

### ISSUE THREAD

**Issue by l8huang** [istio/istio#38610]
**Describe the feature request**

Currently AuthorizationPolicy has a workload selector, which can be used to apply the authorization policy to a specific workload. But istiod translates all AuthorizationPolicies applied to the workload into Envoy RBAC config and adds them to every FilterChains. This could cause scalability issue while AuthorizationPolicy number increasing, the size of LDS config will increase dramatically.
 
As an example, with below 2 AuthorizationPolicies:

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: policy-allow-egress-to-vip-1
spec:
  selector:
    matchLabels:
      istio: egressgateway-test
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - "test.com/ns/app-1/sa/default"
    when:
    - key: connection.sni
      values: 
      - "vip-1.test.com"
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: policy-allow-egress-to-vip-2
spec:
  selector:
    matchLabels:
      istio: egressgateway-test
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - "test.com/ns/app-1/sa/default"
    when:
    - key: connection.sni
      values: 
      - "vip-2.test.com"
```

and below 2 Gateways:
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  namespace: istio-test
  name: egress-gw-1
spec:
  selector:
    istio: egressgateway-test
  servers:
  - hosts:
    - "vip-1.test.com"
    port:
      number: 443
      name: https
      protocol: HTTPS  
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  namespace: istio-test
  name: egress-gw-2
spec:
  selector:
    istio: egressgateway-test
  servers:
  - hosts:
    - "vip-2.test.com"
    port:
      number: 443
      name: https
      protocol: HTTPS  
    tls:
      mode: ISTIO_MUTUAL
```

The generated listener config will be:
```
- address:
    socketAddress:
      address: 0.0.0.0
      portValue: 8443
  filterChains:
  - filterChainMatch:
      serverNames:
      - vip-1.test.com
    filters:
    - name: envoy.filters.network.http_connection_manager
      typedConfig:
        '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
...
        httpFilters:
...
        - name: envoy.filters.http.rbac
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC
            rules:
              policies:
                ns[istio-test]-policy[policy-allow-egress-to-vip-1]-rule[0]:
                  permissions:
                  - andRules:
                      rules:
                      - orRules:
                          rules:
                          - requestedServerName:
                              exact: vip-1.test.com
                  principals:
                  - andIds:
                      ids:
                      - orIds:
                          ids:
                          - metadata:
                              filter: istio_authn
                              path:
                              - key: source.principal
                              value:
                                stringMatch:
                                  exact: test.com/ns/app-1/sa/default
                ns[istio-test]-policy[policy-allow-egress-to-vip-2]-rule[0]:
                  permissions:
                  - andRules:
                      rules:
                      - orRules:
                          rules:
                          - requestedServerName:
                              exact: vip-2.test.com
                  principals:
                  - andIds:
                      ids:
                      - orIds:
                          ids:
                          - metadata:
                              filter: istio_authn
                              path:
                              - key: source.principal
                              value:
                                stringMatch:
                                  exact: test.com/ns/app-1/sa/default
...
```
For a request targeting vip-1.test.com, it will be matched by above filter chain, so it not necessary to have `ns[istio-test]-policy[policy-allow-egress-to-vip-2]-rule[0]` in the http rbac config. And, the same http rbac config is repeated for all Filter Chains.

For resolving this issue, should a relationship being created between Gateway object and AuthorizationPolicy object? Just like VirtualService has `gateways` field which can link a VirtualService to several Gateway objects, e.g.

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: policy-allow-egress-to-vip-1
spec:
  selector:
    matchLabels:
      istio: egressgateway-test
  gateways:
  - egress-gw-1   # <- only apply this AuthorizationPolicy to the FilterChains generated from Gateway egress-gw-1
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - "test.com/ns/app-1/sa/default"
    when:
    - key: connection.sni
      values: 
      - "vip-1.test.com"

```

**Describe alternatives you've considered**
N/A

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
