### ISSUE TITLE
adjust weight for TCP service,the TCP connection will be interrupted.

### ISSUE THREAD

**Issue by zhj-hx** [istio/istio#38616]
### Bug Description

Adjust the traffic proportion of different versions of the TCP protocol service through virtualservice. After the adjustment, the TCP connection will be interrupted.

### Version

```prose
istio verison 1.11
TCP protocol : ssh
```

### Additional Information

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ssh-test-ingress
spec:
  hosts:
    - "*"
  gateways:
    - ssh-test
  tcp:
    - route:
        - destination:
            host: ssh-test
            subset: v1
            port:
              number: 2222
          weight: 100
        - destination:
            host: ssh-test
            subset: v2
            port:
              number: 2222
          weight: 0
```

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ssh-test-ingress
spec:
  hosts:
    - "*"
  gateways:
    - ssh-test
  tcp:
    - route:
        - destination:
            host: ssh-test
            subset: v1
            port:
              number: 2222
          weight: 50
        - destination:
            host: ssh-test
            subset: v2
            port:
              number: 2222
          weight: 50
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [X] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
