### ISSUE TITLE
Encounter "Connection refused: connect" when access application pod via Istio ingress gateway in AKS

### ISSUE THREAD

**Issue by manmaujin2** [istio/istio#38649]
### Bug Description

We deploy Istio ingress gateway on AKS and integrate with Azure Load balancer 

And the Inbound traffic path as below:
Azure LB -> istio ingress Gateway -> pod 

When trigger 3000 requests with 10 thread in Jmeter to call target application, around 1 -3 % request will encounter Connection refused:connect error message. I wonder Istio ingress gateway has compatibility issue with AKS or Azure load balancer...  

Here is the istio configmap config
```
 k get configmap istio -n istio-system -o yaml
apiVersion: v1
data:
  mesh: |-
    accessLogEncoding: JSON
    accessLogFile: /dev/stdout
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      proxyMetadata: {}
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
    enableAutoMtls: true
    enablePrometheusMerge: true
    enableTracing: false
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
    rootNamespace: istio-system
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
kind: ConfigMap
.....
```

Ingress gateway service config:
```
spec:
  clusterIP: 10.0.125.159
  clusterIPs:
  - 10.0.125.159
  externalTrafficPolicy: Cluster
  loadBalancerIP: 10.224.201.140
  loadBalancerSourceRanges:
  - 10.224.201.128/26
  ports:
  - name: status-port
    nodePort: 32442
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: http2
    nodePort: 31380
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 31390
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: tcp
    nodePort: 31400
    port: 31400
    protocol: TCP
    targetPort: 31400
  - name: tls
    nodePort: 31240
    port: 15443
    protocol: TCP
    targetPort: 15443
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.224.201.140
```

Below is the Error message:
```
[Thread Name:Thread Group 1-15
Sample Start:2022-04-20 22:08:57 CST
Load time:19180
Connect Time:19180
Latency:0
Size in bytes:2985
Sent bytes:0
Headers size in bytes:0
Body size in bytes:2985
Sample Count:1
Error Count:1
Data type ("text"|"bin"|""):text
Response code:Non HTTP response code: org.apache.http.conn.HttpHostConnectException
Response message:Non HTTP response message: Connect to demo.home.abc.com:443 [demo.home.abc.com/10.224.201.140] failed: Connection refused: connect

HTTPSampleResult fields:
ContentType: 
DataEncoding: null]([url](url))
```

In Azure Load Balancer, set idle timeout 4 mins and enabled TCP reset also. In addition, we also scale out the istio ingress gateway and application pod and the result also is same. Please kindly to help us and we are facing this issue a long time.

### Version

```prose
Istio version
control plane version: 1.9.5
data plane version: 1.9.5 (133 proxies)

k8s version
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9",
```
