### ISSUE TITLE
Wrong endpoint when the WorkloadEntry is created before the ServiceEntry

### ISSUE THREAD

**Issue by djannot** [istio/istio#38642]
### Bug Description

Here are the 2 Istio objects I have created to reproduce the issue:

```
apiVersion: networking.istio.io/v1beta1
kind: WorkloadEntry
metadata:
  name: test
  namespace: default
spec:
  address: 1.2.3.4
  labels:
    foo: bar
  ports:
    http-1234: 5678
```

and

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: test
  namespace: default
spec:
  addresses:
  - 254.154.115.171
  exportTo:
  - istio-gateways
  hosts:
  - test.global
  location: MESH_INTERNAL
  ports:
  - name: http-1234
    number: 1234
    protocol: HTTP
    targetPort: 1234
  resolution: STATIC
  workloadSelector:
    labels:
      foo: bar
```

If I create the WorkloadEntry before the ServiceEntry, I get the following endpoint when running `./istio-*/bin/istioctl --context cluster1 pc endpoints -n istio-gateways deploy/istio-ingressgateway | grep global`:

```
1.2.3.4:1234                     HEALTHY     OK                outbound|1234||test.global
```

This is wrong.

Now, if I create the ServiceEntry before the WorkloadEntry, I get the following endpoint:

```
1.2.3.4:5678                     HEALTHY     OK                outbound|1234||test.global
```

This one is right.

Obviously, the order shouldn't matter, that's why I create this issue.

From my test, it looks like this bug has been introduced in Istio 1.13.

```


### Version

```prose
Istio:
client version: 1.13.3
control plane version: 1.13.3
data plane version: 1.13.3-solo (11 proxies)
Kubernetes
Client Version: v1.21.1
Server Version: v1.21.1
```
