### ISSUE TITLE
Traffic Management features for TLS configurations in the VirtualService

### ISSUE THREAD

**Issue by SantiMunoz** [istio/istio#38663]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Currently the in the VirtualService you can define Traffic Management features like timeouts and retries, but they are only available for HTTP traffic and not for HTTPS.

In our current implementation we use HTTPS to call services within the mesh, therefore we have a VirtualService with the `tls` configuration, and we can't use the timeouts or retries configs.

Pulling the envoy config from the sidecar we can see the HTTPS Envoy route has the timeout and retry configurations, but from the VirtualService you can't update them.

`istioctl proxy-config route kubium-mesh-mesh-76bdbb87d7-wlwtv -n kubium -o json`
```json
{
                "name": "kubium-mesh-mesh.kubium.svc.cluster.local:443",
                "domains": [
                    "kubium-mesh-mesh.kubium.svc.cluster.local",
                    "kubium-mesh-mesh.kubium.svc.cluster.local:443",
                    "kubium-mesh-mesh",
                    "kubium-mesh-mesh:443",
                    "kubium-mesh-mesh.kubium.svc",
                    "kubium-mesh-mesh.kubium.svc:443",
                    "kubium-mesh-mesh.kubium",
                    "kubium-mesh-mesh.kubium:443",
                    "100.66.206.46",
                    "100.66.206.46:443"
                ],
                "routes": [
                    {
                        "name": "default",
                        "match": {
                            "prefix": "/"
                        },
                        "route": {
                            "cluster": "outbound|443||kubium-mesh-mesh.kubium.svc.cluster.local",
                            "timeout": "0s",
                            "retryPolicy": {
                                "retryOn": "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes",
                                "numRetries": 2,
                                "retryHostPredicate": [
                                    {
                                        "name": "envoy.retry_host_predicates.previous_hosts"
                                    }
                                ],
                                "hostSelectionRetryMaxAttempts": "5",
                                "retriableStatusCodes": [
                                    503
                                ]
                            },
                            "maxStreamDuration": {
                                "maxStreamDuration": "0s",
                                "grpcTimeoutHeaderMax": "0s"
                            }
                        },
                        "decorator": {
                            "operation": "kubium-mesh-mesh.kubium.svc.cluster.local:443/*"
                        }
                    }
                ],
                "includeRequestAttemptCount": true
            }
```

If we configure the `http` section in the VirtualService it creates a new route for port 80 with the specified timeout and retry policy defined from the VirtualService, but it's never used because we are using HTTPS between services.

We use the following VirtualService:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kubium-mesh
  namespace: kubium
spec:
  gateways:
    - kubium-mesh
    - mesh
  hosts:
    - kubium-mesh.service.consul
  http:
    - match:
        - port: 443
      retries:
        attempts: 3
        retryOn: connect-failure,refused-stream
      route:
        - destination:
            host: kubium-mesh-mesh.kubium.svc.cluster.local
            port:
              number: 443
      timeout: 6s
  tls:
    - match:
        - port: 443
          sniHosts:
            - kubium-mesh.service.consul
      route:
        - destination:
            host: kubium-mesh-mesh.kubium.svc.cluster.local
```
In the above configuration the `http` section is only used in the `kubium-mesh` Ingress, therefore for traffic coming from outside the mesh, and the `tls` section is used for the intra-mesh traffic.

**Describe alternatives you've considered**
We will try to use EnvoyFilters to update these routes, but the ideal solution would be to allow updating these fields from the VirtualService
**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by SantiMunoz** [comment]
I've tried to use an Envoy filter to update the Route, it applies correctly to the Envoy config but doesn't seem to work with intra-mesh traffic.

The envoy filter:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: test-route
  namespace: istio-system
spec:
  configPatches:
    - applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_OUTBOUND
        routeConfiguration:
          portNumber: 443
          vhost:
            name: kubium-mesh-mesh.kubium.svc.cluster.local:443
      patch:
        operation: MERGE
        value:
          route:
            retryPolicy:
              retryOn: connect-failure,refused-stream
            timeout: 5s
  workloadSelector:
    labels:
      app.kubernetes.io/component: microservice
      serviceMeshResource: 'true'
```

and in the output of the envoy routes I see it applied:
```json
{
                "name": "kubium-mesh-mesh.kubium.svc.cluster.local:443",
                "domains": [
                    "kubium-mesh-mesh.kubium.svc.cluster.local",
                    "kubium-mesh-mesh.kubium.svc.cluster.local:443",
                    "kubium-mesh-mesh",
                    "kubium-mesh-mesh:443",
                    "kubium-mesh-mesh.kubium.svc",
                    "kubium-mesh-mesh.kubium.svc:443",
                    "kubium-mesh-mesh.kubium",
                    "kubium-mesh-mesh.kubium:443",
                    "100.66.206.46",
                    "100.66.206.46:443"
                ],
                "routes": [
                    {
                        "name": "default",
                        "match": {
                            "prefix": "/"
                        },
                        "route": {
                            "cluster": "outbound|443||kubium-mesh-mesh.kubium.svc.cluster.local",
                            "timeout": "5s",
                            "retryPolicy": {
                                "retryOn": "connect-failure,refused-stream",
                                "numRetries": 2,
                                "retryHostPredicate": [
                                    {
                                        "name": "envoy.retry_host_predicates.previous_hosts"
                                    }
                                ],
                                "hostSelectionRetryMaxAttempts": "5",
                                "retriableStatusCodes": [
                                    503
                                ]
                            },
                            "maxStreamDuration": {
                                "maxStreamDuration": "0s",
                                "grpcTimeoutHeaderMax": "0s"
                            }
                        },
                        "decorator": {
                            "operation": "kubium-mesh-mesh.kubium.svc.cluster.local:443/*"
                        }
                    }
                ],
                "includeRequestAttemptCount": true
            }
```

But when I call the `kubium-mesh` service from another service inside the mesh the request doesn't timeout, and I've tried with delay on the server side of 10, 20 and 30 seconds.

The logs from the client application is the following (for a 30s call):
`[2022-04-29T15:46:37.140Z] "- - -" 0 - - - "-" 106 292 30028 - "-" "-" "-" "-" "100.101.183.234:8080" outbound|443||kubium-mesh-mesh.kubium.svc.cluster.local 100.101.177.252:51586 240.240.0.1:443 100.101.177.252:40944 kubium-mesh.service.consul -`
