### ISSUE TITLE
Istio ingress behind Aws NLB

### ISSUE THREAD

**Issue by jsenon** [istio/istio#3867]
Hi,

I m trying to implement istio ingress behind AWS NLB. It needs to have healthcheck TCP or HTTP to works. I ve tried with `externalTrafficPolicy: Local` or  `externalTrafficPolicy: Cluster`

```
apiVersion: v1
kind: Service
metadata:
  name: istio-ingress
  namespace: istio-system
  labels:
    istio: ingress
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
  - port: 443
    name: https
    protocol: TCP
    targetPort: 443
  selector:
    istio: ingress
```

If we use `externalTrafficPolicy: Local` HTTP endpoint needs to be available on ingress POD, but I think that we don't have one.
If we use `externalTrafficPolicy: Cluster`, TCP endpoint needs to be available.

Does istio is compatible with AWS NLB?

Thanks

**Comment by douglas-reid** [comment]
@andraxylia for triage.

**Comment by jsenon** [comment]
Do you have any update please ?

**Comment by c-knowles** [comment]
Trying to configure this also. I found https://preliminary.istio.io/blog/2018/aws-nlb.html

**Comment by andraxylia** [comment]
Can you please try with 0.8 and Gateway?

**Comment by jsenon** [comment]
Hello @andraxylia I confirm that is working fine for 0.8

**Comment by andraxylia** [comment]
thanks for the confirmation @jsenon , closing this issue.

**Comment by abhinavkorpal** [comment]
This issues still exits.

**Comment by abhinavkorpal** [comment]
> Hello @andraxylia I confirm that is working fine for 0.8. How did you do .. Istio ingress behind Aws NLB ? Can you please lit bit explain me ?

**Comment by towens** [comment]
Hi. We upgraded to Istio 1.4.2. Using a file overlay to spec an AWS NLB results in a network load balancer with only two listeners `TCP:80 and TCP:15020`. I didn't see another issue to track this.

```
client version: 1.4.2
control plane version: 1.4-alpha.10f63ffc12a557209341a7289e5716cf8021578c
data plane version: 1.4-alpha.10f63ffc12a557209341a7289e5716cf8021578c (1 proxies)
```

Deployed like so...
```
GATEWAY_MAX=6
NLB_OVERRIDE="override.yaml"
ISTIO_DEPLOYMENT="istio.yaml"

kubectl create namespace istio-system
helm template install/kubernetes/helm/istio-init --name istio-init --namespace istio-system | kubectl apply -f -
kubectl -n istio-system wait --for=condition=complete job --all
helm template install/kubernetes/helm/istio \
    --name istio --namespace istio-system \
    --set prometheus.enabled=false \
    --set kiali.enabled=true \
    --set gateways.istio-ingressgateway.autoscaleMax="${GATEWAY_MAX}" \
    --set istio_cni.enabled=true \
    -f "${NLB_OVERRIDE}" > "${ISTIO_DEPLOYMENT}"

kubectl apply -f "${ISTIO_DEPLOYMENT}"
```

Just the ingress-gateway.
```
# Source: istio/charts/gateways/templates/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:somecert"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  labels:
    chart: gateways
    heritage: Tiller
    release: istio
    app: istio-ingressgateway
    istio: ingressgateway
spec:
  type: LoadBalancer
  selector:
    release: istio
    app: istio-ingressgateway
    istio: ingressgateway
  ports:
    -
      name: status-port
      port: 15020
      targetPort: 15020
    -
      name: http2
      nodePort: 31380
      port: 80
      targetPort: 80
    -
      name: https
      nodePort: 31390
      port: 443
    -
      name: tcp
      nodePort: 31400
      port: 31400
    -
      name: https-kiali
      port: 15029
      targetPort: 15029
    -
      name: https-prometheus
      port: 15030
      targetPort: 15030
    -
      name: https-grafana
      port: 15031
      targetPort: 15031
    -
      name: https-tracing
      port: 15032
      targetPort: 15032
    -
      name: tls
      port: 15443
      targetPort: 15443
---
```
Can provide other info if it would help. Thanks!
