### ISSUE TITLE
Certs missing from istio-proxy

### ISSUE THREAD

**Issue by kevinlmadison** [istio/istio#38683]
### Bug Description

My certs aren't showing up in istio-proxy , I'm expecting a cert called admin-wildcard
```
> istioctl proxy-config secret -n admin kibana-5975d5b559-t77jx
RESOURCE NAME     TYPE           STATUS     VALID CERT     SERIAL NUMBER                                        NOT AFTER                NOT BEFORE
default           Cert Chain     ACTIVE     true           124054721434298699473753221536725989696005212565     2022-04-29T22:49:34Z     2022-04-29T21:49:04Z
ROOTCA            CA             ACTIVE     true           109131827152280446784907185616920678491184485432     2032-03-29T15:41:13Z     2022-04-01T15:40:43Z
```
and so any traffic going to this pod is resulting in a 404 on port 443, (port 80 works just fine).
The cert does show up if I check the proxy-config against the ingressgatewaywhich seems strange.
```
> istioctl proxy-config secret -n istio-system istio-ingressgateway-9bd56d975-gk8gj
RESOURCE NAME                   TYPE           STATUS     VALID CERT     SERIAL NUMBER                                        NOT AFTER                NOT BEFORE
default                         Cert Chain     ACTIVE     true           574012982311621098570890658624213983814657072370     2022-04-29T20:39:26Z     2022-04-29T19:38:56Z
kubernetes://admin-wildcard     Cert Chain     ACTIVE     true           144753945834875348337526805412397582795              2022-07-21T23:59:59Z     2022-04-22T00:00:00Z
ROOTCA                          CA             ACTIVE     true           109131827152280446784907185616920678491184485432     2032-03-29T15:41:13Z     2022-04-01T15:40:43Z
```

### Version

```prose
> istioctl version
client version: 1.13.2
control plane version: 1.13.2
data plane version: 1.13.2 (31 proxies)
> kubectl version --short
Client Version: v1.19.2
Server Version: v1.22.6+rke2r1
```

**Comment by zirain** [comment]
why did you expect that? how do you config virtualservice and gateway?

**Comment by kevinlmadison** [comment]
Hello @zirain,
I was expecting to find the cert in the istio-proxy because of some documentation on the istio website telling me to check for certs, it didn't explicitly tell me which certs to check for but given my issue I thought that my cert is probably supposed to be there. The virtual service and gateway are configured as follows:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: harbor-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-harbor
      protocol: HTTP
    hosts:
    - "*.dev.mywebsite.com"
  - port:
      number: 443
      name: https-harbor
      protocol: HTTPS
    hosts:
    - "*.dev.mywebsite.com"
    tls:
      mode: SIMPLE
      credentialName: admin-wildcard
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: harbor-http-virtual-service
  namespace: admin
spec:
  hosts:
  - registry.dev.mywebsite.com
  gateways:
  - istio-system/harbor-gateway
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: kibana.admin.svc.cluster.local
        port:
          number: 5601
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: harbor-https-virtual-service
  namespace: admin
spec:
  hosts:
  - registry.dev.mywebsite.com
  gateways:
  - istio-system/harbor-gateway
  tls:
  - match:
    - port: 443
      sniHosts:
      - registry.dev.mywebsite.com
    route:
    - destination:
        host: kibana.admin.svc.cluster.local
        port:
          number: 5601
```

With this configuration I am able to access my app through a browser on port 80, but not 443.

**Comment by zirain** [comment]
if you want tls passthrough in port 443, you should follow this doc: https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/

**Comment by kevinlmadison** [comment]
@zirain Passthrough is not what I want as my application is using HTTP, I want istio to handle the TLS termination.

**Comment by zirain** [comment]
> @zirain Passthrough is not what I want as my application is using HTTP, I want istio to handle the TLS termination.

if you want istio handle the TLS termination, I think you should replace `TlsRoute` with `HttpRoute` like [this doc](https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/).

**Comment by kevinlmadison** [comment]
@zirain thank you, this solved my issue. For anyone else that comes across this I've found 3 common setups for doing TLS with Istio. I've worked through all 3 use cases and have example manifests for each setup below. I'm somewhat new to Istio and I'm not a networking expert so if any part of my explanation is incorrect please feel free to correct it. 
All of my examples work behind an AWS LB that was created by Istio as an `IngressGateway`, for the examples it has an externally available address of: `dev.mysite.com`
I have created a wildcard certificate called `admin-wildcard` in the `istio-system` namespace using cert-manager for: `*.dev.mysite.com`
The application I was setting up was harbor, using Helm. https://github.com/goharbor/harbor-helm

**The 3 Setups**
1. Istio TLS Termination + HTTP Application
2. Istio TLS Passthrough + HTTPS Application (Application terminates TLS)
3. Istio TLS Termination + HTTPS Application (Self Signed Cert / Application internal TLS)

**1. Istio TLS termination + HTTP Application**
This is _probably_ the most common setup. I disabled all TLS in the helm install of Harbor and then deployed the following Istio resources:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: harbor-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-harbor
      protocol: HTTP
    hosts:
    - "*.dev.mysite.com"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https-harbor
      protocol: HTTPS
    hosts:
    - "*.dev.mysite.com"
    tls:
      mode: SIMPLE
      credentialName: admin-wildcard
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: harbor-https-virtual-service
  namespace: admin
spec:
  hosts:
  - registry.dev.mysite.com
  gateways:
  - istio-system/harbor-gateway
  http:
  - match:
    - port: 443
    route:
    - destination:
        host: harbor-portal.admin.svc.cluster.local
        port:
          number: 80
```

**2. Istio TLS Passthrough + HTTPS Application (Application Terminates TLS)**
I enabled external TLS in the helm install of Harbor and then copied the secret containing my wildcard cert from `istio-system` into the `admin` namespace using Kubed https://appscode.com/products/kubed/v0.12.0/setup/install/, this allows you to label namespaces and secrets and then any secret with your label gets copied to all namespaces with your label. The hardest part of this was getting Harbor configured correctly to actually do the termination, i.e. making sure it was actually grabbing my wildcard cert. I then deployed the following Istio resources:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: harbor-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https-harbor
      protocol: HTTPS
    hosts:
    - "*.dev.mysite.com"
    tls:
      mode: PASSTHROUGH
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: harbor-https-virtual-service
  namespace: admin
spec:
  hosts:
  - registry.dev.mysite.com
  gateways:
  - istio-system/harbor-gateway
  tls: 
  - match:
    - port: 443
      sniHosts:
      - registry.dev.mysite.com
    route:
    - destination:
        host: harbor-portal.admin.svc.cluster.local
        port:
          number: 443
```
Note we're using `tls` here instead of `http` in the VirtualService `spec`.

**3. Istio TLS Termination + HTTPS Application (Self Signed Cert / Application internal TLS)**
For this setup I enabled Internal TLS in the helm install of Harbor. This creates an internal certificate for Harbor and so when you connect to it it will be expecting HTTPS traffic, but the Gateway is handling TLS termination so you're no longer using TLS. The solution here is to use Upstream TLS which is also called TLS Origination, essentially we're re-encrypting the traffic as it leaves the envoy proxy and heads to the application. This is accomplished with a simple `DestinationRule`. For a better explanation of this check out this doc https://istio.io/latest/docs/ops/configuration/traffic-management/tls-configuration/. Also note for this setup my wildcard cert, `admin-wildcard`, only needs to be in the `istio-system` namespace.
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: harbor-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-harbor
      protocol: HTTP
    hosts:
    - "*.dev.mysite.com"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https-harbor
      protocol: HTTPS
    hosts:
    - "*.dev.mysite.com"
    tls:
      mode: SIMPLE
      credentialName: admin-wildcard
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: harbor-https-virtual-service
  namespace: admin
spec:
  hosts:
  - registry.dev.mysite.com
  gateways:
  - istio-system/harbor-gateway
  http:
  - match:
    - port: 443
    route:
    - destination:
        host: harbor-portal.admin.svc.cluster.local
        port:
          number: 443
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: harbor-destination-rule
  namespace: admin
spec:
  host: harbor-portal.admin.svc.cluster.local
  trafficPolicy:
    tls:
      mode: SIMPLE
```

Some references that I used to get all these working.
Setup 1: https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/
Setup 2: https://ruzickap.github.io/k8s-knative-gitlab-harbor/part-04/
Setup 3: https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/ + https://istio.io/latest/docs/ops/configuration/traffic-management/tls-configuration/
