### ISSUE TITLE
Handle targetPort set to a name

### ISSUE THREAD

**Issue by linsun** [istio/istio#3870]
The simple example (btw it is a popular guestbook k8s example in official k8s repo) I'm moving from k8s to Istio has the following in the service yaml:

  type: LoadBalancer
    ports:
   - port: 3000
     targetPort: "http-server"

I had to change that to the targetPort... Would be nice to support this to simplify user's onboard experience onto Istio.

**Comment by ymesika** [comment]
@linsun I just tried this configuration (with targetPort) and it's functioning correctly:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: productpage
  labels:
    app: productpage
spec:
  ports:
  - port: 9082
    targetPort: httpport
    name: http
  selector:
    app: productpage
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: productpage-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: productpage
        version: v1
    spec:
      containers:
      - name: productpage
        image: istio/examples-bookinfo-productpage-v1:1.5.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: httpport
          containerPort: 9080
```

with:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - "*"
  gateways:
  - bookinfo-gateway
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: 9082
```

Is it the scenario you referred to?
