### ISSUE TITLE
serviceentry addresses config won't be domains ,preview version can?

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#38719]
### Bug Description

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: details-se
spec:
  hosts:
  - details.bookinfo.com
  addresses:
  - 192.168.229.179
  - 192.168.229.178
  location: MESH_INTERNAL
  ports:
  - number: 9080
    name: http
    protocol: HTTP
  resolution: STATIC
  workloadSelector:
    labels:
      app: details
      version: v2
```
![image](https://user-images.githubusercontent.com/31508490/166667159-c7d60f84-2d21-4645-b136-8f1c6470192e.png)

below is version 1.11.2
![image](https://user-images.githubusercontent.com/31508490/166667272-1cc71a10-92d2-4793-98d9-7b6598d9e4ba.png)

### Version

```prose
[root@node01 serviceentries]# istioctl version
client version: 1.12.0-alpha.5
control plane version: 1.12.0-alpha.5
data plane version: 1.12.0-alpha.5 (14 proxies)

[root@node01 serviceentries]# kubectl version --short
Client Version: v1.21.0
Server Version: v1.21.0
```
