### ISSUE TITLE
use destination port when inferring destinations from vs for sidecar

### ISSUE THREAD

**Issue by yingzhuivy** [istio/istio#38725]
### Bug Description

Suppose there is a client, a vs and a service.
vs has port 8080 but routes to service on port 8081.

When the client defines a sidecar with egress listener depending on vs:8080, the service with port 8081 is not included in the sidecar scope, resulting in client proxy can not get the service configs. If client depends on vs:8081, it works. But I don't think it makes sense since vs does not have port 8081.

I think if client specify vs:8080, istio should be smart enough to pull in service on port 8081. 
I believe the code to change is [here](https://github.com/istio/istio/blob/1.12.6/pilot/pkg/model/sidecar.go#L363), if it makes sense, happy to submit a fix.

### Version

```prose
istio 1.12
```

**Comment by ryan-smick** [comment]
Adding on to this:

Our current setup is as Ying described above, but with the minor difference that the sidecar does not specify a port on the egress listener; it only specifies the vs host. What we're seeing is that istio will create a cluster on the client proxy for every port on the service, even if the virtual service only specifies a single port in the destinations.

It seems to me that if the virtual service will only route to one port (or a subset of ports) on the service, we can skip the cluster creation on the client for the remainder of the service ports.

**Comment by hzxuzhonghu** [comment]
Kind of understanding, can you provide an example

**Comment by yingzhuivy** [comment]
in our case, we have a ServiceEntry defined external service `a` with port 3306, and an egress gateway 'b'. That egress gateway has a bunch of ports, and our service `a` is using port `80`. We use the following virtual service to route A traffic to B:

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vs-a
  namespace: ns-a
spec:
  hosts:
  - a.ns-a....
  tcp:
  - match:
    - port: 3306
    route:
    - destination:
        host: b.ns-b
        port:
          number: 80
      weight: 100
```

For our client `c`, we have the following sidecar:
```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: sidecar-c
  namespace: ns-c
spec:
  egress:
    - hosts:
      - ns-a/a.ns-a....
  workloadSelector:
    labels:
      app: app-c
```

The sidecar depends on `ns-a/a.ns-a....` which pulls in `b.ns-b` through the virtual service. However, currently it pulls in all the ports on b, even though the virtual service is only routing to port 80.
This is problematic for us because we have hundreds of ports on our gateway b, so istio creates a cluster on the client proxy for every port, which causes crashlooping on the client pods.

I think istio should be smart enough to only pull in port 80 through when the port number is defined on the vs destination. what do you think?
