### ISSUE TITLE
Prometheus in Istio Mesh cannot scrape metrics when PeerAuthentication MTLS mode is Permissive

### ISSUE THREAD

**Issue by anders-swanson** [istio/istio#38720]
### Bug Description

Let me start by saying I am not sure if it is more appropriate to file this issue with Prometheus, or with Istio. If this is better suited for Prometheus, please close the issue.

Given a Prometheus instance inside the mesh,
When the Prometheus scrape target is also inside the mesh,
And the default mesh PeerAuthentication MTLS mode is set to PERMISSIVE,
The Prometheus client cannot scrape metrics from endpoints, and receives generic SSL errors (EOF).
 
I believe this is because MTLS PERMISSIVE mode adds an ALPN filter to the Envoy config, and Istio expects to see ALPN info in the TLS request.  ALPN info is automatically set when using normal MTLS with Istio sidecars, but the Prometheus client doesn’t do that - it bypasses Envoy and uses TLS directly.

I can work around this by setting the default mesh MTLS mode to STRICT, and creating workload specific PeerAuthentication policies, but the desired outcome would be to set PERMISSIVE cluster wide and not worry about individual applications.

### Version

```prose
istioctl/istio: 
1.11.4
kubectl/k8s: 1.22
```

**Comment by anders-swanson** [comment]
As a workaround I have Prometheus configured to use STRICT MTLS mode according to the TLS settings defined in the integrations doc you linked. Apps that are required to be outside the mesh, but still need communicate with in-mesh services have workload-specific PeerAuthentication policies configured that sets the MTLS mode to PERMISSIVE for those in-mesh services.

Where it breaks down is if I change the cluster-wide mesh MTLS mode to PERMISSIVE - then Prometheus (which should still be using MTLS) fails and starts getting EOF messages when trying to complete TLS handshakes.

**Comment by lironrisk** [comment]
issue is still relevant.
a service that gets traffic in permissive mode, cannot be scraped by job with tls_config

**Comment by andehpants** [comment]
same here, when I have `STRICT` mode on with my `ServiceMonitor` configured with the below, it scrapes fine.
```
scheme: https
tls_config:
  ca_file: /etc/prom-certs/root-cert.pem
  cert_file: /etc/prom-certs/cert-chain.pem
  key_file: /etc/prom-certs/key.pem
  insecure_skip_verify: true  # Prometheus does not support Istio security naming, thus skip verifying target pod certificate
```
However, if I remove my `PeerAuthentication` CR to change it back to `PERMISSIVE` mode, I get this error
`Get "https://XXXXXX/metrics": read tcp XXXXXX->XXXXXX: read: connection reset by peer`
