### ISSUE TITLE
Istio Operator chart overlapping labels (when running side by side)

### ISSUE THREAD

**Issue by palmobar** [istio/istio#38747]
### Bug Description

In order to run a canary upgrade I want to run **two** istio operators in the `istio-operator` namespace. I've noticed that the pod's labels have no version information like so:

deployment.yaml (excerpt):
```
[...]
kind: Deployment
[...]
spec:
  replicas: 1
  selector:
    matchLabels:
      name: istio-operator
  template:
    metadata:
      labels:
        name: istio-operator
```

so the `matchLabels` is only for `istio-operator` . This poses a problem for example with the endpoints:

```
$ kubectl -n istio-operator get endpoints
NAME                    ENDPOINTS                             AGE
istio-operator-1-11-2   10.1.2.3:8383,10.2.3.4:8383   13d
istio-operator-1-13-3   10.1.2.3:8383,10.2.3.4:8383   2h
```

### Version

```prose
latest chart
1.13.3
```
