### ISSUE TITLE
Use original dest for unknown services

### ISSUE THREAD

**Issue by rosenhouse** [istio/istio#3876]
This can address issues with https outcalls being broken in existing applications.

cc @louiscryan @costinm

**Comment by loewenstein** [comment]
I might be able to spend some cycles on this one. I am anyway looking for some concrete work in the Istio codebase.

**Comment by ldemailly** [comment]
would fix/address #1422

**Comment by andraxylia** [comment]
thanks @loewenstein , I assigned this to you.

**Comment by mandarjog** [comment]
This can be done by adding a single `origin_dst` cluster for outbound listener port 443.

Also also using `origin_dst` cluster as the last virtual host in `:80` route.

**Comment by loewenstein** [comment]
Given that the following egress rule whitelists all http traffic on port 80, should we really apply any original_dst cluster magic to http?
```
apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: external-http
spec:
  destination:
    service: "*"
  ports:
      - port: 80
        protocol: http
```
cc @mandarjog (as you brought it up in your comment)

Same applies to where to put the https flag for original_dst clusters for https. If the following egress works (and I suppose it will as soon as SNI sniffing for such egress traffic is in place), would we want to keep a global mesh setting?
```
apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: external-https
spec:
  destination:
    service: "*"
  ports:
      - port: 443
        protocol: https
```

Where else would I put any temporary flag for https original_dst?
