### ISSUE TITLE
Pilot - /v1/routes not generating external service clusters correctly

### ISSUE THREAD

**Issue by nmnellis** [istio/istio#3878]
When running envoy in `-router` configuration I am seeing 503 NR for external service routings. This is due to the cluster names being wrong in `/v1/routes`

Example  `"cluster": "out.dog.ceo|http"` should be `"cluster": "out.dog.ceo|external-HTTP-80"`
```
 root@istio-ingress-85cfcfc7b6-gvtkp:/# curl "istio-pilot:15003/v1/routes/80/istio-ingress/router~fake~fake~fake"
{
  "virtual_hosts": [
   {
    "name": "istio-ingress|80|dogs.weather.com",
    "domains": [
     "dogs.sun.weather.com:80",
     "dogs.weather.com"
    ],
    "routes": [
   {
    "name": "istio-ingress|80|dogs.weather.com",
    "domains": [
     "dogs.weather.com:80",
     "dogs.weather.com"
    ],
    "routes": [
     {
      "prefix": "/",
      "cluster": "out.dog.ceo|http",
      "timeout_ms": 0,
      "decorator": {
       "operation": "dogs"
      }
     }
    ]
   }
  ]
```
External service
```yaml
apiVersion: config.istio.io/v1alpha2
kind: ExternalService
metadata:
  name: dogs
  namespace: istio-system
spec:
  hosts:
  - dog.ceo
  endpoints:
  - address: dog.ceo
  ports:
  - number: 80
    name: http
    protocol: http
  discovery: "DNS"
```
