### ISSUE TITLE
Helm installation of ingressgateway is inconsistent in the docs

### ISSUE THREAD

**Issue by GiuseppeRaso** [istio/istio#38792]
**Problem**

If you try to install istio gateway with helm, as described in [the docs](https://istio.io/latest/docs/setup/additional-setup/gateway/), you will get an error saying that the referenced selector was not found

**Steps to reproduce the issue**

1.  Install istio with istio gateway using helm as described in the docs
```shell
helm repo add istio https://istio-release.storage.googleapis.com/charts
helm repo update
kubectl create namespace istio-system
kubectl create namespace istio-ingress
kubectl label namespace istio-ingress istio-injection=enabled --overwrite
helm install istio-base istio/base -n istio-system
helm install istiod istio/istiod -n istio-system --wait
helm install istio-ingress istio/gateway -n istio-ingress --wait
```

2. Create a gateway:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istiogateway
  namespace: my-namespace
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
```

Then, if you launch istioctl analyze, you will get this error
```
Error [IST0101] (Gateway my-namespace/istiogateway) Referenced selector not found: "istio=ingressgateway"
```

**Solution**

Just replace istio-ingress with istio-ingressgateway

```shell
# ... install everything else
helm install istio-ingressgateway istio/gateway -n istio-ingress --wait
```

**Request**
Update the docs regarding the helm installation in order to be consistent.

**2nd Request**
The default istioctl installation installs everything in istio-system. Would it be better for consistency to also update the docs regarding the helm installation to do the same?

### Version

```prose
1.13.3
```
