### ISSUE TITLE
Working of       holdApplicationUntilProxyStarts

### ISSUE THREAD

**Issue by mukundjalan** [istio/istio#38800]
I am trying to utilise the feature `holdApplicationUntilProxyStarts: true` so as to ensure the availability of proxy sidecar.
I have a running istio mesh in which I tried updating the IstioOperator config, but couldn't see any changes to the mesh.

**config used**
```yaml
spec:
  ...
  meshConfig:
    defaultConfig:
      gatewayTopology:
        numTrustedProxies: 3
      holdApplicationUntilProxyStarts: true
      proxyMetadata: {}
  values:
    ...
    global:
      proxy:
        holdApplicationUntilProxyStarts: true
  ...
```
Trying under meshConfig as well as global values.

**verifying changes**
I understand that if the above setting is updated, the istio-proxy container would have the `PROXY_CONFIG` environment variable updated with this value. I tried checking environment variables of existing as well as new pods, but none of them have the property updated.

**concern**
As this config does not directly impact the pods in all the scenarios, I am unable to verify the application of this config. I believe that I am either setting the property wrongly or my method of verification is incorrect. Any advise to understand the issue would be appreciated.

Thanks.
