### ISSUE TITLE
request incorrectly routed through service mesh

### ISSUE THREAD

**Issue by thiema** [istio/istio#38813]
### Bug Description

I've created the following setup:
2 Applications: App1 and App2 with Istio Service Plane each (ns: app1, app2, app1-istio-system, app2-istio-system)
Gateway and Virtualservice configurations:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: app-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - app1.example.com
    - app1-admin.example.com
    tls:
      mode: SIMPLE
      credentialName: istio-ingressgateway-certs
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app
spec:
  hosts:
    - app1.example.com
  gateways:
  - app-gateway # must match gateway
  http:
  - name: app
    match:
    - uri:
        prefix: /app
    route:
    - destination:
        host: app # must match app service
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app-admin
spec:
  hosts:
    - app1-admin.example.com
  gateways:
  - app-gateway # must match gateway
  http:
  - name: app-admin
    match:
    - uri:
        prefix: /app-admin
    route:
    - destination:
        host: app-admin # must match admin service
        port:
          number: 80
```

Gateway and Virtualservice for App2 is confgured exactly the same way. (Just the hosts are accordingly defined)
E.g.
```
spec:
  hosts:
    - app2-admin.example.com
```

I have defined multi-domain certificates. So both istio ingress proxies are using the samce key and cert.

Now after trying to access the app using URLs:

https://app1-admin.example.com/app-admin/
https://app2-admin.example.com/app-admin/
https://app1.example.com/app/
https://app2.example.com/app/

I find that around 50% of traffic is routed incorrectly. Seems like requests for app1 are routed to app2 and vice verse.
Ist this behaviour obvious/expected ? What I am doing wrong ?

### Version

```prose
Istio:
1.9 (based on maistra 2.2)
Kubectl:
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", 
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5"}
go1.16.6
```
