### ISSUE TITLE
Metrics support for non sidecar injected destinations

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#3883]
As of 0.6 metrics are collected at the server side, when Mixer client makes a report call to Mixer.
This assumes existence of an injected sidecar on the server.
For services in the cluster that do not have a sidecar, Istio cannot provide any metrics.

Workarounds available in 0.6:
If server is not sidecar injected, it is possible to create an istio `EgessRule` or `ExternalSevice` to point to the service. Client side metrics are collected for a service that matches an `EgressName`.
It is possible to monitor traffic from the mesh to these services.

This still leaves out the use-case of collecting metrics for non-sidecard injected services that are exposed through istio ingress.

As an example, the following configuration can be used to collect metrics about grafana itself.
```yaml
apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: grafana-egress-rule
  namespace: istio-system
spec:
  destination:
    service: grafana.istio-system.svc.cluster.local
  ports:
  - port: 3000
    protocol: http
```
