### ISSUE TITLE
Validation not enabled when installing Istio with istioctl manifest generate

### ISSUE THREAD

**Issue by frankbu** [istio/istio#38834]
### Bug Description

When you install istio using the following command:
```
istioctl manifest generate | kubectl apply -f -
```
the `istiod-default-validator` webhook is not created, and therefore no default resource validation is enabled.

You can verify by applying the following invalid configuration:
```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: invalid-virtual-service
spec:
  http:
EOF
```

and notice that instead of generating the expected error message, the virtual service is applied:
```
kubectl get virtualservice
NAME                      GATEWAYS   HOSTS   AGE
invalid-virtual-service                      3s
```

### Version

```prose
1.13
```
