### ISSUE TITLE
ValidatingWebhookConfiguration stopped working in 1.12 release

### ISSUE THREAD

**Issue by ghisguth** [istio/istio#38839]
### Bug Description

Virtual service validation stopped working in 1.12 and 1.13 versions. 

Here is 1.11.7

```shell
[alexander.fedora:~/Code/istio$ istioctl ps
NAME                                                                    CLUSTER     CDS        LDS        EDS        RDS          ISTIOD                      VERSION
istio-egressgateway-f49cddb54-74s8s.istio-system                                    SYNCED     SYNCED     SYNCED     NOT SENT     istiod-7c6f58bd4d-pgmc2     1.11.7
istio-ingressgateway-5d5fdf9c87-f5h6c.istio-system                                  SYNCED     SYNCED     SYNCED     SYNCED       istiod-7c6f58bd4d-pgmc2     1.11.7
istio-ingressgateway-internal-577d556f57-h679g.istio-system                         SYNCED     SYNCED     SYNCED     SYNCED       istiod-7c6f58bd4d-pgmc2     1.11.7
istio-ingressgateway-internal-with-pip-77d79f44b-7fhr5.istio-system                 SYNCED     SYNCED     SYNCED     SYNCED       istiod-7c6f58bd4d-pgmc2     1.11.7
alexander.fedora:~/Code/istio$ kubectl apply -f ./pkg/test/datasets/validation/dataset/networking-v1beta-VirtualService-invalid.yaml
Error from server: error when creating "./pkg/test/datasets/validation/dataset/networking-v1beta-VirtualService-invalid.yaml": admission webhook "validation.istio.io" denied the request: configuration is invalid: total destination weight 90 != 100
```

And after upgrade to 1.12.6:

```shell
$ istioctl ps
NAME                                                                    CLUSTER     CDS        LDS        EDS        RDS          ISTIOD                    VERSION
istio-egressgateway-d6fdc7768-zdvzg.istio-system                                    SYNCED     SYNCED     SYNCED     NOT SENT     istiod-df74756c-9mcsl     1.12.6
istio-ingressgateway-6799757fd7-4hb2m.istio-system                                  SYNCED     SYNCED     SYNCED     SYNCED       istiod-df74756c-9mcsl     1.12.6
istio-ingressgateway-internal-7755d96749-x7knb.istio-system                         SYNCED     SYNCED     SYNCED     SYNCED       istiod-df74756c-9mcsl     1.12.6
istio-ingressgateway-internal-with-pip-bfbc9c4db-k6qzw.istio-system                 SYNCED     SYNCED     SYNCED     SYNCED       istiod-df74756c-9mcsl     1.12.6
$ kubectl apply -f ./pkg/test/datasets/validation/dataset/networking-v1beta-VirtualService-invalid.yaml
virtualservice.networking.istio.io/invalid-virtual-service created
$ kubectl delete -f ./pkg/test/datasets/validation/dataset/networking-v1beta-VirtualService-invalid.yaml
virtualservice.networking.istio.io "invalid-virtual-service" deleted
```

And the same for 1.13.3:

```shell
$ istioctl ps
NAME                                                                     CLUSTER        CDS        LDS        EDS        RDS          ISTIOD                      VERSION
istio-egressgateway-5c6f6fd5b4-wk4tc.istio-system                        Kubernetes     SYNCED     SYNCED     SYNCED     NOT SENT     istiod-7788d875b6-brntz     1.13.3
istio-ingressgateway-5bdd664585-hzhh4.istio-system                       Kubernetes     SYNCED     SYNCED     SYNCED     SYNCED       istiod-7788d875b6-brntz     1.13.3
istio-ingressgateway-internal-587d64d687-2xzlp.istio-system              Kubernetes     SYNCED     SYNCED     SYNCED     SYNCED       istiod-7788d875b6-brntz     1.13.3
istio-ingressgateway-internal-with-pip-7fb54cdd68-pt26c.istio-system     Kubernetes     SYNCED     SYNCED     SYNCED     SYNCED       istiod-7788d875b6-brntz     1.13.3
$ kubectl apply -f ./pkg/test/datasets/validation/dataset/networking-v1beta-VirtualService-invalid.yaml
virtualservice.networking.istio.io/invalid-virtual-service created
$ kubectl delete -f ./pkg/test/datasets/validation/dataset/networking-v1beta-VirtualService-invalid.yaml
virtualservice.networking.istio.io "invalid-virtual-service" deleted
```

### Version

```prose
$ istioctl version
client version: 1.13.3
control plane version: 1.12.6
data plane version: 1.12.6 (4 proxies)
$ kubectl version --short
Client Version: v1.23.6
Server Version: v1.21.7
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
$ helm version --short
v3.8.2+g6e3701e

and

$ istioctl version
client version: 1.13.3
control plane version: 1.13.3
data plane version: 1.13.3 (4 proxies)
$ kubectl version --short
Client Version: v1.23.6
Server Version: v1.21.7
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
$ helm version --short
v3.8.2+g6e3701e
```

### Additional Information

This is the diff of ValidatingWebhookConfiguration. If I apply older ValidatingWebhookConfiguration on top of 1.13.3, validation starts working again. 

![image](https://user-images.githubusercontent.com/88046/167742173-e0b33426-13f2-4b33-a158-b12437676f5d.png)

Seems like this is missing:

```
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    caBundle: xxx
    service:
      name: istiod
      namespace: istio-system
      path: /validate
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.istio.io
  namespaceSelector: {}
  objectSelector:
    matchExpressions:
    - key: istio.io/rev
      operator: DoesNotExist
  rules:
  - apiGroups:
    - security.istio.io
    - networking.istio.io
    - telemetry.istio.io
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - '*'
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
```

$ istioctl bug-report

Target cluster context: docker-desktop

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2022-05-10 16:44:15.326241 -0700 PDT

Cluster endpoint: https://127.0.0.1:52496
CLI version:
version.BuildInfo{Version:"1.13.3", GitRevision:"b28579cb30c12c428ea58279b7c06f3302abe924-dirty", GolangVersion:"go1.18.1", BuildStatus:"Clean", GitTag:"1.13.3"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.13.3", GitRevision:"b28579cb30c12c428ea58279b7c06f3302abe924", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.13.3"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.13.3}

Fetching proxy logs for the following containers:

argo-rollouts/argo-rollouts/argo-rollouts-7bb88f6f5f-gh85j/argo-rollouts
argo-rollouts/argo-rollouts/argo-rollouts-7bb88f6f5f-tm6jh/argo-rollouts
cert-manager/cert-manager-cainjector/cert-manager-cainjector-5dd88cf989-rxcfj/cert-manager
cert-manager/cert-manager-webhook/cert-manager-webhook-546978644d-m9qxc/cert-manager
cert-manager/cert-manager/cert-manager-668fc8b7cb-zgrlc/cert-manager
istio-operator/istio-operator/istio-operator-fbb6dbfb4-n98k9/istio-operator
istio-system/istio-egressgateway/istio-egressgateway-5c6f6fd5b4-wk4tc/istio-proxy
istio-system/istio-egressgateway/istio-egressgateway-5c6f6fd5b4-wk4tc/microservice-collector
istio-system/istio-ingressgateway-internal-with-pip/istio-ingressgateway-internal-with-pip-7fb54cdd68-pt26c/istio-proxy
istio-system/istio-ingressgateway-internal-with-pip/istio-ingressgateway-internal-with-pip-7fb54cdd68-pt26c/microservice-collector
istio-system/istio-ingressgateway-internal/istio-ingressgateway-internal-587d64d687-2xzlp/istio-proxy
istio-system/istio-ingressgateway-internal/istio-ingressgateway-internal-587d64d687-2xzlp/microservice-collector
istio-system/istio-ingressgateway/istio-ingressgateway-5bdd664585-hzhh4/istio-proxy
istio-system/istio-ingressgateway/istio-ingressgateway-5bdd664585-hzhh4/microservice-collector
istio-system/istiod/istiod-7788d875b6-brntz/discovery
monitoring-system//monitoring-agent-wxmm9/fluentd
monitoring-system//monitoring-agent-wxmm9/monitoring-agent
monitoring-system//monitoring-agent-wxmm9/prometheus-node-exporter

Fetching Istio control plane information from cluster.

Running istio analyze on all namespaces and report as below:
Analysis Report:
Info [IST0102] (Namespace argo-rollouts) The namespace is not enabled for Istio injection. Run 'kubectl label namespace argo-rollouts istio-injection=enabled' to enable it, or 'kubectl label namespace argo-rollouts istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace cert-manager) The namespace is not enabled for Istio injection. Run 'kubectl label namespace cert-manager istio-injection=enabled' to enable it, or 'kubectl label namespace cert-manager istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace istio-operator) The namespace is not enabled for Istio injection. Run 'kubectl label namespace istio-operator istio-injection=enabled' to enable it, or 'kubectl label namespace istio-operator istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace istio-resources) The namespace is not enabled for Istio injection. Run 'kubectl label namespace istio-resources istio-injection=enabled' to enable it, or 'kubectl label namespace istio-resources istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace monitoring-system) The namespace is not enabled for Istio injection. Run 'kubectl label namespace monitoring-system istio-injection=enabled' to enable it, or 'kubectl label namespace monitoring-system istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0135] (Pod istio-system/istio-egressgateway-5c6f6fd5b4-wk4tc) Annotation "sidecar.istio.io/statsInclusionSuffixes" has been deprecated and may not work in future Istio versions.
Creating an archive at /Users/alexander.fedora/Code/istio/bug-report.tar.gz.
Cleaning up temporary files in /var/folders/z4/lt6v5n797cj2gydg6hk6_fk40000gq/T/bug-report.
Done.

**Comment by howardjohn** [comment]
maybe https://github.com/istio/istio/issues/38834

**Comment by ghisguth** [comment]
> there should be 2 validating webhooks (2 objects, not 2 entries in the list) in newer versions. Do you not have 2? how did you install?

@howardjohn we are installing istio operator as separate helm chart, and then creating instio operator resource as separate helm deployment. 

I was able to repro using clean installation using istiooperator, but I also tried installing using istioctl and I can't repro the problem:

```
$ istioctl install
This will install the Istio 1.13.3 default profile with ["Istio core" "Istiod" "Ingress gateways"] components into the cluster. Proceed? (y/N) y
✔ Istio core installed                                                                                                                                                                                                                                                                                                        
✔ Istiod installed                                                                                                                                                                                                                                                                                                            
✔ Ingress gateways installed                                                                                                                                                                                                                                                                                                  
✔ Installation complete                                                                                                                                                                                                                                                                                                       Making this installation the default for injection and validation.

Thank you for installing Istio 1.13.  Please take a few minutes to tell us about your install/upgrade experience!  https://forms.gle/pzWZpAvMVBecaQ9h9

alexander.fedora:~/Code/istio$ kubectl apply -f ./pkg/test/datasets/validation/dataset/networking-v1beta-VirtualService-invalid.yaml
Error from server: error when creating "./pkg/test/datasets/validation/dataset/networking-v1beta-VirtualService-invalid.yaml": admission webhook "validation.istio.io" denied the request: configuration is invalid: total destination weight 90 != 100
```

I will try to compare istio operator generated by istioctl with the one we manually create and will report back.

**Comment by ghisguth** [comment]
I've captured istio operator resource generated by istioctl install. And then applied it manually. I had to remove `install.istio.io/ignoreReconcile: 'true'` annotation, so it kicked in. And was able to repro the issue. 

So it seems like yes, this is exactly the same problem as https://github.com/istio/istio/issues/38834.

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
#  annotations:
#    install.istio.io/ignoreReconcile: 'true'
  creationTimestamp:
  name: istio-system
  namespace: istio-system
spec:
  components:
    base:
      enabled: true
    cni:
      enabled: false
    egressGateways:
    - enabled: false
      name: istio-egressgateway
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
    istiodRemote:
      enabled: false
    pilot:
      enabled: true
  hub: docker.io/istio
  meshConfig:
    defaultConfig:
      proxyMetadata: {}
    enablePrometheusMerge: true
  profile: default
  tag: 1.13.3
  values:
    base:
      enableCRDTemplates: false
      validationURL: ''
    defaultRevision: ''
    gateways:
      istio-egressgateway:
        autoscaleEnabled: true
        env: {}
        name: istio-egressgateway
        secretVolumes:
        - mountPath: "/etc/istio/egressgateway-certs"
          name: egressgateway-certs
          secretName: istio-egressgateway-certs
        - mountPath: "/etc/istio/egressgateway-ca-certs"
          name: egressgateway-ca-certs
          secretName: istio-egressgateway-ca-certs
        type: ClusterIP
      istio-ingressgateway:
        autoscaleEnabled: true
        env: {}
        name: istio-ingressgateway
        secretVolumes:
        - mountPath: "/etc/istio/ingressgateway-certs"
          name: ingressgateway-certs
          secretName: istio-ingressgateway-certs
        - mountPath: "/etc/istio/ingressgateway-ca-certs"
          name: ingressgateway-ca-certs
          secretName: istio-ingressgateway-ca-certs
        type: LoadBalancer
    global:
      configValidation: true
      defaultNodeSelector: {}
      defaultPodDisruptionBudget:
        enabled: true
      defaultResources:
        requests:
          cpu: 10m
      imagePullPolicy: ''
      imagePullSecrets: []
      istioNamespace: istio-system
      istiod:
        enableAnalysis: false
      jwtPolicy: third-party-jwt
      logAsJson: false
      logging:
        level: default:info
      meshNetworks: {}
      mountMtlsCerts: false
      multiCluster:
        clusterName: ''
        enabled: false
      network: ''
      omitSidecarInjectorConfigMap: false
      oneNamespace: false
      operatorManageWebhooks: false
      pilotCertProvider: istiod
      priorityClassName: ''
      proxy:
        autoInject: enabled
        clusterDomain: cluster.local
        componentLogLevel: misc:error
        enableCoreDump: false
        excludeIPRanges: ''
        excludeInboundPorts: ''
        excludeOutboundPorts: ''
        image: proxyv2
        includeIPRanges: "*"
        logLevel: warning
        privileged: false
        readinessFailureThreshold: 30
        readinessInitialDelaySeconds: 1
        readinessPeriodSeconds: 2
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        statusPort: 15020
        tracer: zipkin
      proxy_init:
        image: proxyv2
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 10m
            memory: 10Mi
      sds:
        token:
          aud: istio-ca
      sts:
        servicePort: 0
      tracer:
        datadog: {}
        lightstep: {}
        stackdriver: {}
        zipkin: {}
      useMCP: false
    istiodRemote:
      injectionURL: ''
    pilot:
      autoscaleEnabled: true
      autoscaleMax: 5
      autoscaleMin: 1
      configMap: true
      cpu:
        targetAverageUtilization: 80
      deploymentLabels:
      enableProtocolSniffingForInbound: true
      enableProtocolSniffingForOutbound: true
      env:
        ENABLE_LEGACY_FSGROUP_INJECTION: false
      image: pilot
      keepaliveMaxServerConnectionAge: 30m
      nodeSelector: {}
      podLabels: {}
      replicaCount: 1
      traceSampling: 1
    telemetry:
      enabled: true
      v2:
        enabled: true
        metadataExchange:
          wasmEnabled: false
        prometheus:
          enabled: true
          wasmEnabled: false
        stackdriver:
          configOverride: {}
          enabled: false
          logging: false
          monitoring: false
          topology: false

```
