### ISSUE TITLE
reserved delivery client origin ip  failed  for TCP protocol

### ISSUE THREAD

**Issue by zhj-hx** [istio/istio#38844]
### Bug Description

istioOperator config :
```yaml
spec:
  components:
    ingressGateways:
    - k8s:
        overlays:
        - apiVersion: apps/v1
          kind: Deployment
          name: istio-ingressgateway
          patches:
          - path: kind
            value: DaemonSet
          - path: spec.strategy
          - path: spec.updateStrategy
            value:
              rollingUpdate:
                maxUnavailable: 33%
              type: RollingUpdate
          - path: spec.template.spec.containers.[name:istio-proxy].ports.[containerPort:8080].hostPort
            value: 80
          - path: spec.template.spec.containers.[name:istio-proxy].ports.[containerPort:8443].hostPort
            value: 443
          - path: spec.template.spec.containers.[name:istio-proxy].ports.[containerPort:15021].hostPort
            value: 15021
        service:
          externalTrafficPolicy: Local
      name: istio-ingressgateway
    pilot:
      k8s:
        env:
        - name: PILOT_HTTP10
          value: "1"
        resources:
          limits:
            memory: 1024Mi
          requests:
            cpu: 500m
            memory: 1024Mi
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
        ISTIO_META_DNS_CAPTURE: "true"
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
  profile: default
  values:
    global:
      proxy:
        holdApplicationUntilProxyStarts: true
        resources:
          limits:
            memory: 150Mi
          requests:
            cpu: 50m
            memory: 150Mi
```
I don't add any other configuration for istio-ingressgateway and istio-proxy , I still can get client src IP for the application of 
 the HTTP protocol, but I can't get the original IP for the application of the TCP protocol

Basic configuration reference： https://github.com/hzxuzhonghu/istio-demo/tree/main/istiocon-2021/tcp

1. do not do any settings
  Access httpbin from outside the cluster or inside sleep
```json
{
  "origin": "127.0.0.6"
}
```
2. add config for deployment
```yaml
metadata:
  annotations:
    sidecar.istio.io/interceptionMode: TPROXY
```
Access httpbin from  sleep
reutrn: curl: (56) Recv failure: Connection reset by peer
3. again config for istio-ingressgateway 
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: proxy-protocol
  namespace: istio-system
spec:
  configPatches:
  - applyTo: LISTENER
    patch:
      operation: MERGE
      value:
        listener_filters:
        - name: envoy.listener.proxy_protocol
        - name: envoy.listener.tls_inspector
  workloadSelector:
    labels:
      istio: ingressgateway
```
Access httpbin from  outside the cluster
reutrn: curl: (56) Recv failure: Connection reset by peer

### Version

```prose
➜  ~ istioctl version
client version: 1.13.2
control plane version: 1.11.0
data plane version: 1.11.0 (11 proxies)
➜  ~ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T17:57:25Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```
