### ISSUE TITLE
Using Telemetry api to REMOVE prometheus metrics label causes metrics data double

### ISSUE THREAD

**Issue by suninuni** [istio/istio#38841]
### Bug Description

**If istio-proxy can't reset the previous metrics when loading the telemetry config, I would expect it to apply this config when re-injection.**

When I use the following telemetry to remove useless labels in order to reduce the load about metrics, it doubles my load !!!

```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: prometheus
  namespace: sre
spec:
  metrics:
  - providers:
    - name: prometheus
    overrides:
    - tagOverrides:
        source_app:
          operation: REMOVE
        ...
```

### Version

```prose
$ istioctl version
client version: 1.13.1
control plane version: 1.13.1
data plane version: 1.13.1 (117 proxies)
```
