### ISSUE TITLE
telemetry crd is not available

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#38920]
### Bug Description

```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: default
  namespace: istio-system
spec:
  tracing:
  - randomSamplingPercentage: 10.00
```

I configured the randomSamplingPercentage ,but not change is real value?

![image](https://user-images.githubusercontent.com/31508490/168411724-2b30b12f-a416-4999-b0a6-3594b9c92d04.png)

### Version

```prose
[root@node01 telemetry]# istioctl version
client version: 1.13.3
control plane version: 1.13.3
data plane version: 1.13.3 (11 proxies)

[root@node01 telemetry]# kubectl version --short
Client Version: v1.21.0
Server Version: v1.21.0
```

**Comment by zirain** [comment]
@douglas-reid can telemetry work without provider name? something miss in validating?

**Comment by douglas-reid** [comment]
what does the MeshConfig look like for this mesh?

**Comment by zirain** [comment]
> what does the MeshConfig look like for this mesh?

I can reproduce this with no extension-providers, maybe this [doc](https://istio.io/latest/docs/reference/config/telemetry/) is wrong?

**Comment by 13567436138** [comment]
when I config providers,the tracing config will disappeared

**Comment by 13567436138** [comment]
```
[root@node01 ~]# kubectl get cm istio -n istio-system  -o yaml
apiVersion: v1
data:
  mesh: |-
    accessLogFile: /dev/stdout
    enableTracing: true
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      proxyMetadata: {}
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
    enablePrometheusMerge: true
    extensionProviders:
    - envoyOtelAls:
        port: 4317
        service: otel-collector.istio-system.svc.cluster.local
      name: otel
    rootNamespace: istio-system
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
```

**Comment by zirain** [comment]
here's a full demo:
first, install istio via a istio-operator
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    accessLogFile: /dev/stdout
    extensionProviders:
    - name: zipkin
      zipkin:
        service: zipkin.istio-system.svc.cluster.local
        port: 9411
```
then, apply the telemetry config
```yaml
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  tracing:
  - providers:
    - name: "zipkin"
    randomSamplingPercentage: 100.00
```
