### ISSUE TITLE
proxyConfig crd is not effictive？

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#38959]
### Bug Description

I config the istio with：
```
apiVersion: networking.istio.io/v1beta1
kind: ProxyConfig
metadata:
  name: productpage
spec:
  selector:
    matchLabels:
      app: productpage
  concurrency: 0
  image:
    imageType: debug
```

set image type to debug ,and restarted the productpage-v1 deployment,but the image is not right?
![1652765275(1)](https://user-images.githubusercontent.com/31508490/168735654-6e04c637-f184-4d76-a337-46d0faf3cd63.jpg)

istiod has no warn and error log

### Version

```prose
[root@node01 ~]# istioctl version
client version: 1.13.3
control plane version: 1.13.3
data plane version: 1.13.3 (10 proxies)

[root@node01 ~]# kubectl version --short
Client Version: v1.21.0
Server Version: v1.21.0
```

**Comment by xichengliudui** [comment]
https://istio.io/latest/docs/reference/config/networking/proxy-config/#ProxyImage
example: docker.io/istio/proxyv2:1.11.1 or docker.io/istio/proxyv2:1.11.1-distroless
can you try this config? `docker.io/istio/proxyv2:1.11.1-debug`

**Comment by 13567436138** [comment]
```
apiVersion: networking.istio.io/v1beta1
kind: ProxyConfig
metadata:
  name: productpage
spec:
  selector:
    matchLabels:
      app: productpage
  concurrency: 0
  image:
    imageType: docker.io/istio/proxyv2:1.13.3-debug
```
the same not change the image
supported values: default, debug, distroless.

**Comment by xichengliudui** [comment]
after i tested it, I had the same problem

**Comment by xichengliudui** [comment]
```
apiVersion: networking.istio.io/v1beta1
kind: ProxyConfig
metadata:
  name: pconfig
spec:
  image:
    imageType: debug
```
