### ISSUE TITLE
wasmplugin when sha256 is wrong,the config is still effective?

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#38989]
### Bug Description

```
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: productpage
  namespace: istio
spec:
  selector:
    matchLabels:
      app: productpage
  url: oci://registry.cn-qingdao.aliyuncs.com/hxpdocker/wasm-rate-limiting:v1
  phase: STATS	
  sha256: d3f2d1b3c0ae26100e36a6ddb901ca55732aeea79329e43a14686c1338a1ed03
```

this is right:

follow is wrong:
```
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: productpage
  namespace: istio
spec:
  selector:
    matchLabels:
      app: productpage
  url: oci://registry.cn-qingdao.aliyuncs.com/hxpdocker/wasm-rate-limiting:v1
  phase: STATS	
  sha256: d3f2d1b3c0ae26100e36a6ddb901ca55732aeea79329e43a14686c1338a1ed04
```
but the config is still effective???

### Version

```prose
[root@node01 wasmplugin]# istioctl version
client version: 1.13.3
control plane version: 1.13.3
data plane version: 1.13.3 (10 proxies)

[root@node01 wasmplugin]# kubectl version --short
Client Version: v1.21.0
Server Version: v1.21.0
```
