### ISSUE TITLE
[release 1.13] CORS are handled differently

### ISSUE THREAD

**Issue by Alan-pad** [istio/istio#38993]
### Bug Description

Before 1.13.X version our Preflight Requests were handled directly by the ingress-gateway (OPTIONS method) and were not forwarded to our upstreams (Our apps).

Once we upgraded to 1.13.3 and then 1.13.4 we observed that our upstreams were now receiving those requests. On our side it resulted in 403 errors on all our Preflight requests which led to our app not being usable anymore since no xhr calls from our frontends could pass.

Don't hesitate to ask any snippet of configuration we have on our side if that can help.

### Version

```prose
`istioctl version`
client version: 1.6.7
control plane version: 1.12.7
data plane version: 1.13.3 (69 proxies), 1.12.7 (4 proxies)

`kubectl version --short`
Client Version: v1.17.1
Server Version: v1.23.5-gke.1500
```

### Additional Information

**Istio-operator based-install**

We're not using `istioctl` based install, we were using the istio-operator setup and are still using it today as we don't find any other installation method suitable for our current usage. I don't think it has an impact for this issue to occur but if that's the case at least you have the information.

**CORS setup**

- Our CORS setup is using the `corsPolicy` field of `VirtualService` CRD
- We use an EnvoyFilter to reorder `jwt_authn` filter after `cors` filter so we don't hide an authorization issue behind a cors issue
- We use a global `AuthorizationPolicy` applied to our main ingress-gateway to authorize all OPTIONS request on all hosts and paths

**Comment by bobalong79** [comment]
I have also observed this issue with 1.13.2 with the same type of EnvoyFilter. I had to downgrade to 1.12.x to fix it.

**Comment by jleonar** [comment]
We came from 1.11.x to 1.13.4 and seeing the same issue.

**Comment by Alan-pad** [comment]
@jleonar I'll try your policy but ours looks like that :

```yaml
spec:
  action: ALLOW
  rules:
    - to:
        - operation:
            hosts:
              - '*'
            methods:
              - OPTIONS
            paths:
              - '*'
  selector:
    matchLabels:
      app: istio-ingressgateway
```

**Comment by rayterrill** [comment]
We're running into this issue as well after upgrading from 1.12 to 1.13. I did dig through the release notes and changes, and I was unable to find anything that indicated this kind of change, so this caught us by surprise as it's appeared to have caught others.

It does look like 1.14 potentially handles this differently, https://github.com/istio/istio/pull/36981/files.

I did also confirm that adjusting the AuthorizationPolicy on our Gateway does allow these requests to pass down to our services, but now we're getting 405s because these requests weren't configured to support OPTIONS requests.
```
spec:
  action: ALLOW
  rules:
    - to:
        - operation:
            methods:
              - OPTIONS
            paths:
              - '*'
```

We're looking at reverting in the meantime.
