### ISSUE TITLE
istioctl x uninstall not removing istio-sidecar-injector webhook on istiodless remotes

### ISSUE THREAD

**Issue by frankbu** [istio/istio#39007]
### Bug Description

When the external profile is installed using `istioctl install`, a subsequent `istioctl x uninstall` is not removing the istio-sidecar-injector mutatingwebhookconfiguration. It seems to clean up correctly if Istio is instead installed using the default profile.

To reproduce:
```
cat <<EOF > cluster2.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: external
  values:
    istiodRemote:
      injectionPath: /inject/cluster/cluster2/net/network2
    global:
      remotePilotAddress: ${DISCOVERY_ADDRESS}
EOF
istioctl install --context="${CTX_CLUSTER2}" -f cluster2.yaml
```

If you now run `kubectl get mutatingwebhookconfiguration --context="${CTX_CLUSTER2}"` you'll see that the `istio-sidecar-injector` webhook is still there.

### Version

```prose
latest in master
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [X] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
