### ISSUE TITLE
Authz policy on origin workload breaks outbound TCP requests

### ISSUE THREAD

**Issue by nmittler** [istio/istio#39000]
### Bug Description

This was discovered while working on https://github.com/istio/istio/pull/37914.

Steps to reproduce:

- 2 echo pods: `a` and `b`.
- mTLS on both pods (template config below)
- Authz policy applied to a that allows requests only from itself (policy below)
- Exec onto the `a` pod and send a TCP request to `b` using the echo client `client tcp://b.echo1.svc.cluster.local:9090`.
- Result is this seemingly incomplete response:
```
I have no name!@a-v1-6994d48868-h2225:/$ client tcp://b.echo1.svc.cluster.local:9090
2022-05-18T15:22:24.547272Z	fatal	Error 1/1 requests had errors; first error: expect to recv message with StatusCode=200, got [0] Url=tcp://b.echo1.svc.cluster.local:9090
[0] Echo=HelloWorld
. Return EOF
```

Steps to fix:

- Delete the authz policy on `a`
- Re-run the same request from `a`: `client tcp://b.echo1.svc.cluster.local:9090`
- Response is successful:
```
[0] Url=tcp://b.echo1.svc.cluster.local:9090
[0] Echo=HelloWorld
[0 body] IP=127.0.0.6
[0 body] Hostname=b-v1-d6d8db5d7-bs964
[0 body] Proto=TCP
[0 body] StatusCode=200
[0 body] Cluster=cluster-0
[0 body] IstioVersion=
[0 body] ServiceVersion=v1
[0 body] ServicePort=19090
[0 body] HelloWorld
```

Template for mTLS:

```yaml
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ .To.ServiceName }}
spec:
  selector:
    matchLabels:
      app: "{{ .To.ServiceName }}"
  mtls:
    mode: STRICT
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .To.ServiceName }}
spec:
  host: "{{ .To.ClusterLocalFQDN }}"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```

Authz policy for `a`:

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: a
spec:
  selector:
    matchLabels:
      "app": "a"
  action: ALLOW
  rules:
    - to:
        - operation: # HTTP
            ports: [ "18080", "18085" ]
            paths: [ "/allow" ]
            methods: [ "GET" ]
      from:
        - source:
            principals: [ "cluster.local/ns/echo1/sa/a" ]
    - to:
        - operation: # GRPC
            ports: [ "17070" ]
            paths: [ "/proto.EchoTestService/Echo" ]
            methods: [ "POST" ]
      from:
        - source:
            principals: [ "cluster.local/ns/echo1/sa/a" ]
    - to:
        - operation: # TCP
            ports: [ "19090" ]
      from:
        - source:
            principals: [ "cluster.local/ns/echo1/sa/a" ]
```

### Version

```prose
master
```
