### ISSUE TITLE
External service cluster generation is broken in V1

### ISSUE THREAD

**Issue by ijsnellf** [istio/istio#3901]
Currently V1 generates clusters based on the type of the host of the rule, not the host it is being redirected to. Given:
```yaml
hosts:
  - internal.service
http:
  - route:
    - destination:
        name: internal.service
      weight: 75
    - destination:
        name: external.service.com
      weight: 25
```
where `external.service.com` is an external service,
```yaml
hosts:
  - "external.service.com"
ports:
  - number: 80
    name: http-number
    protocol: http
discovery: NONE
```
the cluster for `external.service.com` will be constructed as if the destination was an internal service (I.E., not an Original DST cluster).

This breaks any realistic configuration scenario, like https://github.com/istio/istio/issues/3878.
