### ISSUE TITLE
V1 host selection only works for existing services in alpha2

### ISSUE THREAD

**Issue by ijsnellf** [istio/istio#3902]
Given:
```yaml
hosts:
  - world.fancy.name
http:
  - route:
    - destination:
        name: world
        subset: v1
      weight: 100
```
Requests to `world.fancy.name` will only be re-routed to `world:v1` if a service with a hostname `world.fancy.name` exists.
