### ISSUE TITLE
V1 alpha2 route destination should be required

### ISSUE THREAD

**Issue by ijsnellf** [istio/istio#3904]
v1alpha2 route rules must have a destination. There can be no default route. This is invalid:
```yaml
hosts:
  - world
http:
  - timeout: 30s
    retries:
      attempts: 1
      perTryTimeout: 5s
```
Currently the V1 tries to create a default route in this scenario.
