### ISSUE TITLE
set env CLOUD_PLATFORM in Istio operator manifest

### ISSUE THREAD

**Issue by AndrzejOlender** [istio/istio#39056]
I need on clusters in GCP, set env CLOUD_PLATFORM to the value none (added to istio from version 1.12.x)
I tried adding CLOUD_PLATFORM to the Istio operator manifest in various ways. Only manually adding to configmap istio-sidecar-injector this variable works, but I would prefer it to be added as a code to our operator configuration. Is it possible to get this?

[x ] Installation

**Comment by howardjohn** [comment]
https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig proxyMetadata field

**Comment by AndrzejOlender** [comment]
```
  meshConfig:
    defaultConfig:
      proxyMetadata:
        CLOUD_PLATFORM: NONE
```

works perfectly, thx
