### ISSUE TITLE
Egress mTLS 1.13.3  TLS error 33554536 OPENSSL_internal Connection reset by peer

### ISSUE THREAD

**Issue by esinhalilov** [istio/istio#39077]
### Bug Description

Istio 1.13.3 mTLS upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 33554536:system library:OPENSSL_internal:Connection reset by peers

Nginx server deployed in kubernetes as out of mesh with mTLS configuraiton as exaplained in the below link example  is working.
https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/#perform-mutual-tls-origination-with-an-egress-gateway  

Similar configuration for 3rd party API is not working. 

Below is config:
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: my-service-egressgateway
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - my.service.com
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: egressgateway-for-my-service
spec:
  exportTo:
  - .
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: my-service
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
        sni: my.service.com
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: originate-mtls-for-cogapi-service-ia
spec:
  exportTo:
  - '*'
  host: my.service.com
  subsets:
  - name: my-service-mtls
    trafficPolicy:
      tls:
        mode: MUTUAL
        credentialName: client-credential-example
        sni: my.service.com
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: my-service-external
spec:
  exportTo:
  - '*'
  hosts:
  - my.service.com
  location: MESH_EXTERNAL
  ports:
  - name: https
    number: 443
    protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: my-service-internal
spec:
  exportTo:
  - .
  hosts:
  - my.service.com
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 80
    protocol: HTTP
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: my-service-internal
spec:
  exportTo:
  - .
  gateways:
  - mesh
  hosts:
  - my.service.com
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    retries:
      attempts: 3
      perTryTimeout: 10s
      retryOn: 5xx
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        port:
          number: 443
        subset: my-service
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: my-service-external
spec:
  exportTo:
  - '*'
  gateways:
  - my-service-egressgateway
  hosts:
  - cogapi.service.ia.test.group
  http:
  - match:
    - gateways:
      - my-service-egressgateway
      port: 443
    retries:
      attempts: 3
      perTryTimeout: 10s
      retryOn: 5xx
    route:
    - destination:
        host: my.service.com
        port:
          number: 443
        subset: my-service-mtls
```

### Version

```prose
>istioctl version
client version: 1.13.3
control plane version: 1.13.3
data plane version: 1.13.3 (7 proxies)

>kubectl version --short
Client Version: v1.23.1
Server Version: v1.21.9
```

### Additional Information

[bug-report.tar.gz](https://github.com/istio/istio/files/8747279/bug-report.tar.gz)
[installed-state-1-13-3.yaml.zip](https://github.com/istio/istio/files/8747283/installed-state-1-13-3.yaml.zip)

Please find attached bug report and IstioOperator yaml file
