### ISSUE TITLE
HTTP request failed after ISTIO_META_DNS_AUTO_ALLOCATE enabled

### ISSUE THREAD

**Issue by fatedier** [istio/istio#39080]
### Bug Description

There is a ServiceEntry for `example.com`, port 9444 as TCP protocol.

HTTP requests to `example.com:80` will also succeed.

```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-auto
spec:
  hosts:
  - example.com
  ports:
  - name: tcp
    number: 9444
    protocol: TCP
  resolution: DNS
```

After I enable `ISTIO_META_DNS_AUTO_ALLOCATE`, HTTP requests to `example.com:80` always failed. Got 503 connection failure

Istio allocs a new IP for `example.com`. Destination of connections to this host will be changed to this IP and passthrough cluster will use ORIGIN DST to connect and fail.

### Version

```prose
client version: 1.12.6
control plane version: 1.12.6
data plane version: 1.12.6
```

**Comment by hzxuzhonghu** [comment]
same as https://github.com/istio/istio/issues/29224

**Comment by fatedier** [comment]
@hzxuzhonghu Hi，there maybe a little different with #29224.

```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-auto
spec:
  hosts:
  - example.com
  ports:
  - name: tcp
    number: 9444
    protocol: TCP
  resolution: DNS
```

I define a TCP port in this ServiceEntry. Resolve `example.com` to an IP auto alloced by istio is expected since I will add VirtualService to this host and port. It needs to dstinguish the different host by IP.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: auto-tls
spec:
  hosts:
  - "example.com"
  gateways:
  - mesh
  tcp:
  - match:
    - port: 9444
    route:
    - destination:
        host: sni-proxy
        subset: example-com-9444
        port:
          number: 443
```

It works well.

But `curl example.com:80` failed. I'm not sure if we can route traffics to the alloced IP and ports except 9444 to a `STRICT_DNS` type cluster.
