### ISSUE TITLE
EnvoyFilter for bootstrap_extensions not working

### ISSUE THREAD

**Issue by freegroup** [istio/istio#39115]
### Bug Description

We want to use an WASM filter of kind "Service" to update some cached data for all EnvoyFilter. The filters are working fine, but we are unable to get the Service to run. Neither we see some logg information in istiod , nor we get some logging info in our istio ingress. It seems, that the EnvoyFilter is ignored.

We saw an issue from 2017 (very old) which describes the very same behaviour of our problem - but without any solution.
https://discuss.istio.io/t/istio-envoy-filter-bootstrap-extension-is-not-executing-the-wasm/12345

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: wasm-fetcher
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      filter: wasm
      app: istio-ingressgateway
  configPatches:
    - applyTo: BOOTSTRAP
      patch:
        operation: ADD
        value:
          bootstrap_extensions:
          - name: envoy.bootstrap.wasm
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.wasm.v3.WasmService
              singleton: true
              config:
                vm_config:
                  runtime: "envoy.wasm.runtime.v8"
                  vm_id: my-wasm-vm-id
                  code:
                    local:
                      filename: "/var/local/lib/wasm-fetcher/fetcher.wasm"
                configuration:
                  "@type": "type.googleapis.com/google.protobuf.StringValue"
                  value: |
                    { "ANY": 500 }

```

We have mounted the `/var/local/lib/wasm-fetcher/fetcher.wasm` with an ConfigMap and Volume mount and the file exists.

...Normal filters are working fine - Services of kind bootstrap_extenson not.

Any idea how to fix this?

### Version

```prose
Istio version:
client version: 1.13.2
control plane version: 1.13.3
data plane version: 1.13.3 (4 proxies)

k8s version:
Client Version: v1.23.4
Server Version: v1.23.4
```
