### ISSUE TITLE
Can support route by authority prefix?

### ISSUE THREAD

**Issue by penghuazhou** [istio/istio#39129]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
VirtualService support  truncate(authority,0,3) to set request headers. for example，authority is 123231312-mesh.google.com，than truncate(authority,0,9)=123231312
zego-micro-global-traffic-label: truncate(authority,0,3) will be zego-micro-global-traffic-label: 123231312
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
  namespace: istio-ryanzhou
spec:
  hosts:
  - "*"
  gateways:
  - bookinfo-gateway
  http:
  - match:
    - withoutHeaders:
        content-type:
          prefix: application/grpc
    route:
    - destination:
        host: productpage
        port:
          number: 9080
      headers:
        request:
          set:
            zego-micro-global-traffic-label: truncate(authority,0,3)
```
**Describe alternatives you've considered**
can support route by authority prefix.
**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
