### ISSUE TITLE
gateway-api httproute backendRefs filters not support?

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#39136]
### Bug Description

```
Status:
  Parents:
    Conditions:
      Last Transition Time:  2022-05-26T03:49:21Z
      Message:               unsupported filter type "RequestMirror"
      Observed Generation:   1
      Reason:                InvalidFilter
      Status:                False
      Type:                  Accepted
    Controller Name:         istio.io/gateway-controller
    Parent Ref:
      Group:      gateway.networking.k8s.io
      Kind:       Gateway
      Name:       bookinfo
      Namespace:  istio-system
Events:           <none>
```

```
httproute/bookinfo-httproute-system-rules-backendRefs-filters-requestMirror.yaml

kubectl apply -f bookinfo-httproute-system-rules-backendRefs-filters-requestMirror.yaml -n istio

apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: bookinfo
spec:
  parentRefs:
  - name: bookinfo
    namespace: istio-system
    group: gateway.networking.k8s.io
    kind: Gateway
  rules:
  - matches:
    - path: 
        type: PathPrefix
        value: /
    backendRefs:
    - name: productpage
      port: 9080
      filters:
      - requestMirror:
          backendRef:
            name: productpage-v2
            port: 9080
        type: RequestMirror


deploy-productpage-v2.yaml

kubectl apply -f deploy-productpage-v2.yaml -n istio


apiVersion: v1
kind: Service
metadata:
  name: productpage-v2
  labels:
    app: productpage-v2
    service: productpage-v2
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: productpage-v2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage-v2
  labels:
    app: productpage-v2
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage-v2
      version: v2
  template:
    metadata:
      labels:
        app: productpage-v2
        version: v2
    spec:
      serviceAccountName: bookinfo-productpage
      containers:
      - name: productpage
        image: docker.io/istio/examples-bookinfo-productpage-v1:1.16.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        securityContext:
          runAsUser: 1000
      volumes:
      - name: tmp
        emptyDir: {}
---

httproute/gw-bookinfo.yaml

kubectl apply -f gw-bookinfo.yaml -n istio-system


apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: bookinfo
spec:
  addresses:
  - value: istio-ingressgateway.istio-system.svc.cluster.local
    type: Hostname
  gatewayClassName: istio
  listeners:  
  - protocol: HTTP
    port: 80
    name: bookinfo-gw
    allowedRoutes:
      namespaces:
        from: All


gatewayclass/istio-gc.yaml

kubectl apply -f istio-gc.yaml -n istio-system


apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GatewayClass
metadata:
  name: istio
spec:
  controllerName: istio.io/gateway-controller



```

### Version

```prose
[root@node01 httproute]# istioctl version
client version: 1.13.3
control plane version: 1.13.3
data plane version: 1.13.3 (14 proxies)

[root@node01 httproute]# kubectl version --short
Client Version: v1.21.0
Server Version: v1.21.0
```
