### ISSUE TITLE
gateway-api gateway can not get secret in other namespace caused timeout?

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#39142]
### Bug Description

gateway-api gateway can not get secret in other namespace caused timeout?
I created ReferencePolicy??? 

openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048  -keyout cert.key -out cert.crt  -config  openssl.conf

secret

kubectl create -n istio secret tls bookinfo-gateway-secret  --key ./cert.key --cert=./cert.crt

referencepolicies/gw-listeners-tls-certificateRefs-namespace.yaml

kubectl apply -f gw-listeners-tls-certificateRefs-namespace.yaml -n istio-system

```
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1alpha2
metadata:
  name: bookinfo
spec:
  addresses:
  - value: istio-ingressgateway.istio-system.svc.cluster.local
    type: Hostname
  gatewayClassName: istio
  listeners:  
  - hostname: "bookinfo.com"
    port: 443
    name: bookinfo-gw
    protocol: HTTPS
    tls:
      options: {}
      certificateRefs:
      - name: bookinfo-gateway-secret
        namespace: istio
        kind: Secret
    allowedRoutes:
      namespaces:
        from: All
```

rp-secret.yaml

kubectl apply -f rp-secret.yaml -n istio

```
kind: ReferencePolicy
apiVersion: gateway.networking.k8s.io/v1alpha2
metadata:
  name: rp-secret
  namespace: istio
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: Gateway
    namespace: istio-system
  to:
  - group: ""
    kind: Secret
    name: bookinfo-gateway-secret
```

gatewayclass/istio-gc.yaml

kubectl apply -f istio-gc.yaml -n istio-system

```
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GatewayClass
metadata:
  name: istio
spec:
  controllerName: istio.io/gateway-controller
```

referencepolicies/bookinfo-httproute-system.yaml

kubectl apply -f bookinfo-httproute-system.yaml -n istio

```
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: bookinfo
spec:
  parentRefs:
  - name: bookinfo
    namespace: istio-system
    kind: Gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: productpage
      port: 9080
```

![image](https://user-images.githubusercontent.com/31508490/170451329-5ca27c80-8806-4804-9f83-0e620b8b1000.png)

### Version

```prose
[root@node01 referencepolicies]# istioctl version
client version: 1.13.3
control plane version: 1.13.3
data plane version: 1.13.3 (17 proxies)

[root@node01 referencepolicies]# kubectl version --short
Client Version: v1.21.0
Server Version: v1.21.0
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
