### ISSUE TITLE
AuthorizationPolicy unexpectedly added to envoy outbound listener filter chain

### ISSUE THREAD

**Issue by dallasanta** [istio/istio#39148]
### Bug Description

We are using istio 1.14.0-beta.1 with outboundTrafficPolicy mode equals to "REGISTRY_ONLY" and therefore we create ServiceEntries to whitelist the external calls.

e.g.
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: standard-port-external-services
  namespace: external
spec:
  hosts:
    - "example.net"
  exportTo:
    - "*"
  location: MESH_EXTERNAL
  ports:
    - number: 443
      name: https
      protocol: TLS
    - number: 80
      name: http
      protocol: HTTP
  resolution: NONE
```

And we also have an AuthorizationPolicy defined for the namespace where our pods are running:
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: some-policy
spec:
  rules:
    - from:
        - source:
            namespaces: ["some-namespace"]
```

After upgrading from istio 1.12.0 to istio 1.14.0-beta1, all the whitelisted external calls were blocked by envoy rbac.

e.g.  (destination has been redacted)
```
debug	envoy rbac	checking connection: requestedServerName: *******, sourceIP: **********/51076, directRemoteIP: 1**********/:51076,remoteIP: **********/:51076, localAddress: **********/:443, ssl: none, dynamicMetadata: 
debug	envoy rbac	enforced denied, matched policy none
```

Envoy config dump shows an unexpected network rbac EnvoyFilter for the listeners related to the whitelisted ServiceEntries.

```
{
     "name": "0.0.0.0_443",
     "active_state": {
      "version_info": "2022-05-26T09:15:32Z/2",
      "listener": {
       "@type": "type.googleapis.com/envoy.config.listener.v3.Listener",
       "name": "0.0.0.0_443",
       "address": {
        "socket_address": {
         "address": "0.0.0.0",
         "port_value": 443
        }
       },
       "filter_chains": [
        {
         "filter_chain_match": {
          "server_names": [
           "example.net"
          ]
         },
         "filters": [
          ...
          {
           "name": "envoy.filters.network.rbac",
           "typed_config": {
            "@type": "type.googleapis.com/envoy.extensions.filters.network.rbac.v3.RBAC",
            "rules": {
             "policies": {
              "ns[some-namespace]-policy[some-policy]-rule[0]": {
                
                **** This is the unexpected AuthorizatioPolicy ****
```

This could be related to https://github.com/istio/istio/pull/38595. Does BuildTCP needs a check for `class == networking.ListenerClassSidecarOutbound` just like BuildHTTP?

Is there any other flag to control this behaviour?

### Version

```prose
# istio
control plane version: 1.14.0-beta.1
data plane version: 1.14.0-beta.1 (10 proxies)

# kubernetes
Client Version: v1.22.0
Server Version: v1.21.9-eks-14c7a48
```
