### ISSUE TITLE
gateway-api udp port port not found

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#39141]
### Bug Description

failed to assign to any requested addresses: port 15449 not found for hostname "istio-ingressgateway.istio-system.svc.cluster.local"

```
[root@node01 ~]#  kubectl get svc -n istio-system
NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                                                                                      AGE
flagger-loadtester     ClusterIP   10.68.71.23     <none>        80/TCP                                                                                       33d
grafana                ClusterIP   10.68.143.246   <none>        3000/TCP                                                                                     254d
istio-egressgateway    ClusterIP   10.68.76.130    <none>        80/TCP,443/TCP                                                                               2d
istio-ingressgateway   NodePort    10.68.183.138   <none>        15021:30534/TCP,80:32542/TCP,443:32388/TCP,31400:30265/TCP,15443:31390/TCP,15449:31220/UDP   2d
istiod                 ClusterIP   10.68.119.201   <none>        15010/TCP,15012/TCP,443/TCP,15014/TCP                                                        2d
jaeger-collector       ClusterIP   10.68.8.190     <none>        14268/TCP,14250/TCP                                                                          255d
kiali                  ClusterIP   10.68.135.199   <none>        20001/TCP,9090/TCP                                                                           254d
prometheus             NodePort    10.68.194.218   <none>        9090:31008/TCP                                                                               256d
tracing                ClusterIP   10.68.45.127    <none>        80/TCP                                                                                       255d
zipkin                 ClusterIP   10.68.135.204   <none>        9411/TCP                                                                                     255d
```

gateway

```
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1alpha2
metadata:
  name: udp
spec:
  addresses:
  - value: istio-ingressgateway.istio-system.svc.cluster.local
    type: Hostname
  gatewayClassName: istio
  listeners:
  - protocol: UDP
    port: 15449
    name: gw-udp
    allowedRoutes:
      namespaces:
        from: All
```

### Version

```prose
[root@node01 ~]# istioctl version
client version: 1.13.3
control plane version: 1.13.3
data plane version: 1.13.3 (17 proxies)

[root@node01 ~]# kubectl version --short
Client Version: v1.21.0
Server Version: v1.21.0
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
