### ISSUE TITLE
proxy-level metrics incomplete cluster_name label

### ISSUE THREAD

**Issue by zufardhiyaulhaq** [istio/istio#39143]
### Bug Description

 we are extending proxy-level metrics since Istio enables only a small subset of the metrics. This is archived via istio operator manifests
 ```
  meshConfig:
    defaultConfig:
      proxyStatsMatcher:
        inclusionRegexps:
        - "^cluster.*"
```

we are using service entry to make sure our external service outside of the mesh get better visibility. if we are not adding any service entry, we can see this kind of traffic is exposed via PassthroughCluster, here is the access log from one of the sidecar.
```
{
  "bytes_received": 847,
  "upstream_transport_failure_reason": null,
  "bytes_sent": 16103,
  "protocol": null,
  "response_code": 0,
  "upstream_cluster": "PassthroughCluster",
  "user_agent": null,
  "upstream_service_time": null,
  "duration": 16,
  "start_time": "2022-05-26T09:11:15.766Z",
  "route_name": null,
  "upstream_host": "185.199.110.153:443",
  "upstream_local_address": "10.122.199.135:45442",
  "requested_server_name": null,
  "path": null,
  "request_id": null,
  "authority": null,
  "connection_termination_details": null,
  "response_code_details": null,
  "method": null,
  "x_forwarded_for": null,
  "downstream_remote_address": "10.122.199.135:45440",
  "downstream_local_address": "185.199.110.153:443",
  "response_flags": "-"
}
```

we try to apply service entry to make this better, 
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: test-se
  namespace: istio-system
spec:
  hosts:
    - zufardhiyaulhaq.com
  location: MESH_EXTERNAL
  ports:
    - name: https-443
      number: 443
      protocol: HTTPS
  resolution: DNS
```
now we can see the upstream cluster
```
{
  "upstream_transport_failure_reason": null,
  "path": null,
  "requested_server_name": "zufardhiyaulhaq.com",
  "start_time": "2022-05-26T09:12:45.069Z",
  "protocol": null,
  "request_id": null,
  "route_name": null,
  "upstream_host": "185.199.110.153:443",
  "user_agent": null,
  "connection_termination_details": null,
  "downstream_remote_address": "10.122.199.135:48138",
  "response_code_details": null,
  "method": null,
  "bytes_received": 847,
  "downstream_local_address": "185.199.110.153:443",
  "response_flags": "-",
  "upstream_local_address": "10.122.199.135:48140",
  "duration": 17,
  "upstream_service_time": null,
  "upstream_cluster": "outbound|443||zufardhiyaulhaq.com",
  "response_code": 0,
  "x_forwarded_for": null,
  "authority": null,
  "bytes_sent": 16104
}
```

we try to check the envoy dashboard, and the envoy stats works fine
```
cluster.outbound|443||zufardhiyaulhaq.com.upstream_rq_retry: 0
cluster.outbound|5000||helloworld.sample.svc.cluster.local.upstream_rq_retry: 0
```

but when we check prometheus stats, we see weird metrics
```
# TYPE envoy_cluster_com_upstream_rq_retry counter
envoy_cluster_com_upstream_rq_retry{cluster_name="outbound|443||zufardhiyaulhaq"} 0

envoy_cluster_upstream_rq_retry{cluster_name="outbound|5000||helloworld.sample.svc.cluster.local"} 0
envoy_cluster_upstream_rq_retry{cluster_name="outbound|5050||onboard-test.default.svc.cluster.local"} 0
```

the metrics name is different! I am not sure why there is `com` inside the metric for any external services that we apply with the service entry object.

This blocks us to create a detailed dashboard for every upstream connection since the metrics name is different.

### Version

```prose
kubectl version --short
Client Version: v1.21.7
Server Version: v1.22.8-gke.200
istioctl version
client version: 1.9.9
control plane version: 1.12.3
data plane version: 1.12.3 (68 proxies)
```

### Additional Information

N/A
