### ISSUE TITLE
HTTPRoute in default namespace svc in istio namespace.I configured  backendRefs namespace ,do not configured ReferencePolicy,It's ok?

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#39159]
### Bug Description

HTTPRoute in default namespace svc in istio namespace.I configured  backendRefs namespace ,do not configured ReferencePolicy,It's ok?

because it's cross namespaces ,it should not ok,but it's ok??? is this a problem???

httproute/bookinfo-httproute-system-rules-backendRefs-namespace.yaml

kubectl apply -f bookinfo-httproute-system-rules-backendRefs-namespace.yaml -n default

```
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: bookinfo
spec:
  parentRefs:
  - name: bookinfo
    namespace: istio-system
    group: gateway.networking.k8s.io
    kind: Gateway
  rules:
  - matches:
    - path: 
        type: PathPrefix
        value: /
    backendRefs:
    - name: productpage
      group: ""
      kind: Service
      port: 9080
      namespace: istio
```

httproute/gw-bookinfo.yaml

kubectl apply -f gw-bookinfo.yaml -n istio-system

```
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: bookinfo
spec:
  addresses:
  - value: istio-ingressgateway.istio-system.svc.cluster.local
    type: Hostname
  gatewayClassName: istio
  listeners:  
  - protocol: HTTP
    port: 80
    name: bookinfo-gw
    allowedRoutes:
      namespaces:
        from: All
```

gatewayclass/istio-gc.yaml

kubectl apply -f istio-gc.yaml -n istio-system

```
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GatewayClass
metadata:
  name: istio
spec:
  controllerName: istio.io/gateway-controller
```

### Version

```prose
[root@node01 httproute]# istioctl version
client version: 1.13.3
control plane version: 1.13.3
data plane version: 1.13.3 (16 proxies)

[root@node01 httproute]# kubectl version --short
Client Version: v1.21.0
Server Version: v1.21.0
```
