### ISSUE TITLE
Originate MTLS with egress gateway not working when client and server are signed by different CAs

### ISSUE THREAD

**Issue by petermollerud** [istio/istio#39166]
### Bug Description

The example desribed at https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/#perform-mutual-tls-origination-with-an-egress-gateway uses the _same CA_ for the authenticating client and the server.

The documented example works fine as long as the client certificate and the server to which one connects to, has the same CA. But in real life that will seldom be the case.  If i try the setup with a client certificate that is not signed by the same CA as the server SSL certificate, the egress gateway logs

`"TLS_error:_268435581:SSL_routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED}"`

In the latter case, I've used the the CA certificate belonging to the client certificate as the ca.crt in the secret provided to the destination rule ("originate-mtls-for-b2b-t") . 

If I instead put in the CA certificate that belongs to the remote server, egress gateway logs 

`"TLS error:268436504:SSL routines:OPENSSL_internal:TLSV1_ALERT_UNKNOWN_CA".`

So obviously, the secret "client-credential" in the example is meant to hold the CA certificate of the client, and not the server (?)
I also tried to concatenate both CA-certificates (CA certificates for server _and_ client)  and put into the ca.crt in the "client-credential" secret, with no luck.

The setup is similar to the example in the Istio doc:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: b2b-t.storebrand.no
  namespace: platform
spec:
  hosts:
  - b2b-t.storebrand.no
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
  namespace: platform
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - b2b-t.storebrand.no
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-b2b-t
  namespace: platform
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: b2b-t
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: ISTIO_MUTUAL
          sni: b2b-t.storebrand.no
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-b2b-t-through-egress-gateway
  namespace: platform
spec:
  hosts:
  - b2b-t.storebrand.no
  gateways:
  - istio-egressgateway
  - mesh
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: b2b-t
        port:
          number: 443
      weight: 100
  - match:
    - gateways:
      - istio-egressgateway
      port: 443
    route:
    - destination:
        host: b2b-t.storebrand.no
        port:
          number: 443
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-mtls-for-b2b-t
  namespace: platform
spec:
  host: b2b-t.storebrand.no
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: MUTUAL
        credentialName: client-credential  
        sni: b2b-t.storebrand.no
        subjectAltNames:
        - b2b-t.storebrand.no
```
Where client-credential is created like:
`kubectl create secret -n istio-system generic client-credential --from-file=tls.key=server.key.pem --from-file=tls.crt=chain.pem  --from-file=ca.crt=ca.cert.pem`

Where:
server.key.pem is the private key of the client
chain.pem is the client certificate and its intermediate certificate
ca.cert.pem is the ca/root certificate corresponding to the intermediate certificate (of the client) 

Thought maybe it was necessary to set "caCertificates" in the DestinationRule to validate the server side, but when credentilaName is set, "caCertificates" directive is not allowed. 

### Version

```prose
Istio version 1.13.2
```
