### ISSUE TITLE
gateway-api httproute can not use backendRefs's  kind httproute?

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#39160]
### Bug Description

gateway-api httproute can not use backendRefs's  kind httproute?

like:

```
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: bookinfo
spec:
  parentRefs:
  - name: bookinfo
    namespace: istio-system
    group: gateway.networking.k8s.io
    kind: Gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: productpage
      kind: HTTPRoute
      group: gateway.networking.k8s.io
```

according to explain :

   kind <string>
     Kind is kind of the referent. For example "HTTPRoute" or "Service".
     Defaults to "Service" when not specified.

### Version

```prose
[root@node01 httproute]# istioctl version
client version: 1.13.3
control plane version: 1.13.3
data plane version: 1.13.3 (16 proxies)

[root@node01 httproute]# kubectl version --short
Client Version: v1.21.0
Server Version: v1.21.0
```
