### ISSUE TITLE
Istio ingress gateway with aws alb can't handle the k8s ingress resource

### ISSUE THREAD

**Issue by shu-ming** [istio/istio#39181]
### Bug Description

I installed the istio on EKS and expose the istio with alb ingress like below.
```
 $k get ingress -n istio-ingress
NAME                       CLASS   HOSTS   ADDRESS                                                                  PORTS   AGE
istio-ingressgateway-alb   alb     *       k8s-istioing-istioing-b9d05c8132-645276771.us-east-1.elb.amazonaws.com   80      3d1h
```
```
  spec:
    ingressClassName: alb
    rules:
    - http:
        paths:
        - backend:
            service:
              name: istio-ingressgateway
              port:
                name: https
          path: /
          pathType: Prefix
  status:
    loadBalancer:
      ingress:
      - hostname: k8s-istioing-istioing-b9d05c8132-645276771.us-east-1.elb.amazonaws.com
   ```
And a dns record is created in route 53 that is linked to the above load balancer.
```
*.mytest.com | A | Simple | - | dualstack.k8s-istioing-istioing-b9d05c8132-645276771.us-east-1.elb.amazonaws.com.
```
`Gateway` and `VirtualService` are created to verify the networking. It works as what we expect. 
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:  
  name: istio-ingressgateway
  namespace: istio-ingress
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - '*'
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        credentialName: istio-tls
        mode: SIMPLE
```
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helloworld
  namespace: istio-sample
spec:
  gateways:
    - istio-ingress/istio-ingressgateway
  hosts:
    - myweb.mytest.com
  http:
    - route:
        - destination:
            host: myweb.dev.svc.cluster.local
```

Then I create another k8s ingress with the` ingressClassName: istio`. 
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld2
  namespace: istio-sample
spec:
  ingressClassName: istio
  rules:
    - host: helloworld2.mytest.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: httpbin
                port:
                  number: 80
```
When trying to do curl this url, it always returns 404
```
> GET /headers HTTP/2
> Host: helloworld2.mytest.com
> user-agent: curl/7.79.1
> accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 404
< date: Sat, 28 May 2022 08:43:20 GMT
< content-length: 0
< server: istio-envoy
<
```
I also tried to update the `istio` configmap with following settings, but it doesn't work either. Looks like this k8s ingress resource is not handled by istio.
```
ingressControllerMode: STRICT
ingressClass: istio
ingressService: istio-ingressgateway
```

### Version

```prose
$istioctl version
client version: 1.13.1
control plane version: 1.13.3
data plane version: 1.13.3 (13 proxies)

$kubectl version --short
Client Version: v1.21.5
Server Version: v1.21.9-eks-14c7a48
```

### Additional Information
Routing configuration can be found from  the dumped config of Istio-ingress-gateway.
```
{
        "name": "helloworld2.mytest.com:80",
        "domains": [
         "helloworld2.mytest.com",
         "helloworld2.mytest.com:*"
        ],
        "routes": [
         {
          "match": {
           "prefix": "/",
           "case_sensitive": true
          },
          "route": {
           "cluster": "outbound|80||helloworld2.istio-sample.svc.cluster.local",
           "timeout": "0s",
           "retry_policy": {
            "retry_on": "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes",
            "num_retries": 2,
            "retry_host_predicate": [
             {
              "name": "envoy.retry_host_predicates.previous_hosts"
             }
            ],
            "host_selection_retry_max_attempts": "5",
            "retriable_status_codes": [
             503
            ]
           },
           "max_grpc_timeout": "0s"
          },
          "metadata": {
           "filter_metadata": {
            "istio": {
             "config": "/apis/networking.istio.io/v1alpha3/namespaces/istio-sample/virtual-service/helloworld2-test-fed-deploy-rnd-mendix-com-helloworld2-istio-autogenerated-k8s-ingress"
            }
           }
          },
          "decorator": {
           "operation": "helloworld2.istio-sample.svc.cluster.local:80/*"
          }
         }
        ],
        "include_request_attempt_count": true
       },
```
_No response_

**Comment by shu-ming** [comment]
@[howardjohn](https://github.com/howardjohn) Explain a little bit background.  The istio gateway and virtual service were created for networking verification. Make sure the aws alb ingress + istio ingress gateway does work. The k8s ingress with ingressClassName=istio is what I want to use in my project. In my project, the k8s ingress would be automatically created by a customized operator. I expect that Istio can pick up these k8s ingresses, then I can get access to my application service via the istio-ingressgateway. Regarding the 80 port, I am able to get access to the application when creating a virtual service like this with `curl -v http:// httptest.mytest.com`
```
spec:
  gateways:
    - istio-ingress/istio-ingressgateway
  hosts:
    - httptest.mytest.com
  http:
    - route:
        - destination:
            host: httpbin.httpbin.svc.cluster.local
```
My observation is that the autogenerated gw and vs from k8s ingress doesn't work. But from the dumped config, looks like istio has created routing for this k8s ingress. How come it doesn't work?
```"dynamic_route_configs": [
    {
     "version_info": "2022-05-31T10:24:51Z/59",
     "route_config": {
      "@type": "type.googleapis.com/envoy.config.route.v3.RouteConfiguration",
      "name": "http.80",
      "virtual_hosts": [
       {
        "name": "helloworld2.mytest.com:80",
        "domains": [
         "helloworld2.mytest.com",
         "helloworld2.mytest.com:*"
        ],
        "routes": [
         {
          "match": {
           "path": "/",
           "case_sensitive": true
          },
          "route": {
           "cluster": "outbound|80||httpbin.httpbin.svc.cluster.local",
```
