### ISSUE TITLE
Tunnel client TLS to gateway using mTLS issue

### ISSUE THREAD

**Issue by andysworkshop** [istio/istio#39210]
### Bug Description

[ Istio 1.13.4 ]

I'm trying to get a client-originated TLS connection to tunnel to an egress gateway using Istio mTLS so that `AuthorizationPolicy` can be applied in the gateway to permit authorized workloads to connect to the hosts managed by the gateway. Istio-originated TLS at the gateway works fine but in this use-case I need client-originated to work.

The flow I'd like to achieve is this:

```
client ->(TLS)-> envoy ->(mTLS-over-TLS)-> gateway ->(TLS)-> external host
```

Firstly, passthrough TLS (without mTLS) is working fine and I can see from the client and gateway logs that the call is correctly routed but obviously there is no mTLS so no possibility to authorize the calling workload at the gateway. For reference, here's my starting passthrough configuration that works:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-egress-int-https
  namespace: istio-egress-int-https
spec:
  selector:
    istio: egressgateway
  servers:
    - hosts:
      - andybrown.me.uk
      port:
        number: 443
        name: tls-passthrough
        protocol: TLS
      tls:
        mode: PASSTHROUGH
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: andy-gateway
  namespace: istio-egress-int-https
spec:
  host: istio-egress-int-https.istio-egress-int-https.svc.cluster.local
  subsets:
  - name: andy
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: andy
  namespace: istio-egress-int-https
spec:
  location: MESH_EXTERNAL
  hosts: [ "andybrown.me.uk" ]
  ports:
  - number: 443
    name: tls-andy
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: andy
  namespace: istio-egress-int-https
spec:
  hosts:
    - andybrown.me.uk
  gateways:
    - mesh
    - istio-egress-int-https
  tls:

    - match:
        - gateways:
            - mesh
          port: 443
          sniHosts:
            - andybrown.me.uk

      route:
        - destination:
            host: istio-egress-int-https.istio-egress-int-https.svc.cluster.local
            subset: andy
            port:
              number: 443

    - match:
        - gateways:
            - istio-egress-int-https
          port: 443
          sniHosts:
            - andybrown.me.uk

      route:
        - destination:
            host: andybrown.me.uk
            port:
              number: 443
          weight: 100
```

To upgrade to mTLS between the client and the gateway I tried to change the gateway server to `ISTIO_MUTUAL` and again for the port in the gateway's `DestinationRule` like this:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-egress-int-https
  namespace: istio-egress-int-https
spec:
  selector:
    istio: egressgateway
  servers:
    - hosts:
      - andybrown.me.uk
      port:
        number: 443
        name: tls-passthrough
        protocol: TLS
      tls:
        mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: andy-gateway
  namespace: istio-egress-int-https
spec:
  host: istio-egress-int-https.istio-egress-int-https.svc.cluster.local
  subsets:
  - name: andy
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      tls:
        mode: ISTIO_MUTUAL
        sni: andybrown.me.uk
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: andy
  namespace: istio-egress-int-https
spec:
  location: MESH_EXTERNAL
  hosts: [ "andybrown.me.uk" ]
  ports:
  - number: 443
    name: tls-andy
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: andy
  namespace: istio-egress-int-https
spec:
  hosts:
    - andybrown.me.uk
  gateways:
    - mesh
    - istio-egress-int-https
  tls:

    - match:
        - gateways:
            - mesh
          port: 443
          sniHosts:
            - andybrown.me.uk

      route:
        - destination:
            host: istio-egress-int-https.istio-egress-int-https.svc.cluster.local
            subset: andy
            port:
              number: 443

    - match:
        - gateways:
            - istio-egress-int-https
          port: 443
          sniHosts:
            - andybrown.me.uk

      route:
        - destination:
            host: andybrown.me.uk
            port:
              number: 443
          weight: 100
```
Now I get an error in the client pod when I test it with `curl`:
```
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to andybrown.me.uk:443
```
A log entry appears in the client envoy container:
```
[2022-05-31T17:57:36.941Z] "- - -" 0 UF,URX - - "-" 0 0 11 - "-" "-" "-" "-" "10.0.201.112:8443" outbound|443|andy|istio-egress-int-https.istio-egress-int-https.svc.cluster.local - 240.240.0.2:443 10.0.148.235:52822 andybrown.me.uk -
```
Nothing appears in the gateway logs so I increased the client envoy logs to `debug` and saw this when a connection attempt is made by the client:
```
envoy filter    tls inspector: new connection accepted
envoy filter    tls:onServerName(), requestedServerName: andybrown.me.uk
envoy filter    [C12783] new tcp proxy session
envoy filter    [C12783] Creating connection to cluster outbound|443|andy|istio-egress-int-https.istio-egress-int-https.svc.cluster.local
envoy misc      Allocating TCP conn pool
envoy pool      trying to create new connection
envoy pool      creating a new connection
envoy connection        [C12784] connecting to 10.0.201.112:8443
envoy connection        [C12784] connection in progress
envoy conn_handler      [C12783] new connection from 10.0.148.235:52872
envoy connection        [C12784] delayed connect error: 111
envoy connection        [C12784] closing socket: 0
envoy connection        [C12784] TLS error: 268435588:SSL routines:OPENSSL_internal:CLIENTHELLO_TLSEXT 268435646:SSL routines:OPENSSL_internal:PARSE_TLSEXT
envoy pool      [C12784] client disconnected, failure reason: delayed connect error: 111
envoy filter    [C12783] Creating connection to cluster outbound|443|andy|istio-egress-int-https.istio-egress-int-https.svc.cluster.local
envoy connection        [C12783] closing data_to_write=0 type=1
envoy connection        [C12783] closing socket: 1
```
I have verified that `10.0.201.112` is the pod IP of the egress gateway. This is where I'm stuck. Can anyone advise on what I need to configure to make this work? I've shown just one target host here but the solution needs to be extendable for multiple external hosts through this gateway.

### Version

```prose
$ istioctl version
client version: 1.13.4
control plane version: 1.13.4
data plane version: 1.13.4 (10 proxies)

$ kubectl version --short
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.24.0
```
