### ISSUE TITLE
Primary Remote Multicluster In Same Network, SmartDNS not work

### ISSUE THREAD

**Issue by yanickxia** [istio/istio#39222]
### Bug Description

i create two cluster in same network (underlay k8s network)

```
cluster 1 (as primary):
     namespace: test
           service: echo-web
                pod:  echo-web-pod
```

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: cluster1
      network: network1
  meshConfig:
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
```

```
cluster 2 (as remote):
     namespace: test
           service: netshoot
                pod:  netshoot-pod
```
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: cluster2
      network: network1
      remotePilotAddress: 192.168.2.161 
  meshConfig:
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
```

try from cluster2 call cluster1
```bash
k exec --context <Cluster2> -n test netshoot-8569d8b47c-zf89r -- curl echo-web                     
Could not resolve host: echo-web
```
seem smartDNS not working..

### Version

```prose
$ istioctl version
client version: 1.13.4
control plane version: 1.13.4
data plane version: 1.13.4 (6 proxies)

$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.20.15-2+c72627d827c130
```
