### ISSUE TITLE
Access logs do not work with REQ_WITHOUT_QUERY when encoding is JSON

### ISSUE THREAD

**Issue by lavoiedn** [istio/istio#39271]
### Bug Description

When using JSON formatting to define access log format, an error is thrown when attempting to use `%REQ_WITHOUT_QUERY(X?:Y):Z%`, as it appears a formatter is missing. This does not appear to be an issue when `logFormat` is `text` or when `accessLogEncoding` is `TEXT`, but happens when `logFormat` is `labels: ...` or `accessLogEncoding` is `JSON`.

This is the error:

```
2022-06-03T14:11:26.165342Z     info    ads     RDS: PUSH for node:istio-ingress-7b64c49dd5-8q94p.istio-ingress resources:1 size:814B cached:0/0
2022-06-03T14:11:26.167903Z     warn    ads     ADS:LDS: ACK ERROR istio-ingress-7b64c49dd5-8q94p.istio-ingress-1 Internal:Error adding/updating listener(s) 0.0.0.0_80: Not supported field in StreamInfo: REQ_WITHOUT_QUERY(:PATH)
```

This error can be reproduced by deploying istio with the `helm` method, adding `samples/httpbin/httpbin.yaml` and using one of these two `meshConfig`:

Legacy config:
```yaml
apiVersion: v1
data:
  mesh: |-
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
    accessLogFile: "/dev/stdout"
    accessLogFormat: '{"path": "%REQ_WITHOUT_QUERY(:PATH)%"}'
    accessLogEncoding: JSON
    enablePrometheusMerge: true
    rootNamespace: null
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: istiod
    meta.helm.sh/release-namespace: istio-system
  labels:
    app.kubernetes.io/managed-by: Helm
    install.operator.istio.io/owning-resource: unknown
    istio.io/rev: default
    operator.istio.io/component: Pilot
    release: istiod
  name: istio
  namespace: istio-system
```

Extension providers config:

```yaml
apiVersion: v1
data:
  mesh: |-
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
    enablePrometheusMerge: true
    rootNamespace: null
    trustDomain: cluster.local
    extensionProviders:
    - name: envoy-custom-format
      envoyFileAccessLog:
        logFormat:
          labels:
            path: "%REQ_WITHOUT_QUERY(:PATH)%"
    defaultProviders:
      accessLogging:
      - envoy-custom-format
  meshNetworks: 'networks: {}'
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: istiod
    meta.helm.sh/release-namespace: istio-system
  labels:
    app.kubernetes.io/managed-by: Helm
    install.operator.istio.io/owning-resource: unknown
    istio.io/rev: default
    operator.istio.io/component: Pilot
    release: istiod
  name: istio
  namespace: istio-system
```

The same config works with text encoding.

```yaml
accessLogFile: "/dev/stdout"
accessLogFormat: "path=%REQ_WITHOUT_QUERY(:PATH)%\n"
accessLogEncoding: TEXT
```

The source seems to be that the log format is [not properly flagged as requiring a formatter](https://github.com/istio/istio/blob/32afc27ea91ef68e4e5f0ee3dd47d0aedfba35f1/pilot/pkg/networking/core/v1alpha3/accesslog.go#L379-L382) in the accesslog logic. It could be user error, however?

I will link a PR with what I think may fix it (I was running into issues building the docker image locally).

### Version

```prose
$ istioctl version
client version: 1.14.0
control plane version: 1.13.4
data plane version: 1.13.4 (1 proxies)

$ kubectl version --short
Client Version: v1.23.3
Server Version: v1.23.1
```
