### ISSUE TITLE
Incomplete localityLbSetting.distribute configuration leads to strange behaviour

### ISSUE THREAD

**Issue by Stono** [istio/istio#39289]
### Bug Description

I was curious if I could use `localityLbSetting.distribute` to effectively disable traffic going to a certain locality.

So take the following example (config **A**):

```
      localityLbSetting:
        distribute:
        - from: '*'
          to:
            europe-west4/europe-west4-a/*: 0
            europe-west4/europe-west4-b/*: 50
            europe-west4/europe-west4-c/*: 50
        enabled: true
```

This works as expected, however I wondered if I could simply do this (config **B**):

```
      localityLbSetting:
        distribute:
        - from: '*'
          to:
            europe-west4/europe-west4-a/*: 0
        enabled: true
```

(thinking about how people operating our platform might just want to relocate traffic from a certain zone for any reason).

This actually has totally the inverse effect and instead sends **all** traffic to `europe-west4-a`, instead of none.

![image](https://user-images.githubusercontent.com/1486729/172047085-57ab53eb-464d-4362-b12d-66a13401b402.png)

I am assuming under the hood the `to` list is just treated as an exclusive list of zones and other zones are simply ignored.  Then subsequently saying there's just one zone, and 0% should go there means there would have been no available endpoints, so subsequently its just failed-open and sent to them all.    

From a technical angle that's probably "working as intended" but from a UX perspective I think it could be improved to help prevent accidental miss-configuration.

### Version

```prose
1.13 on GKE
```
