### ISSUE TITLE
AuthorizationPolicy not working as expected

### ISSUE THREAD

**Issue by stephaneey** [istio/istio#39297]
### Bug Description

The AuthoriztionPolicy is not working

### Version

```prose
client version: 1.12.6
control plane version: 1.12.6
data plane version: 1.12.6 (18 proxies)

Client Version: v1.21.5
Server Version: v1.22.6
```

### Additional Information

Hello,

I'm trying to achieve something that should be straightforward but it is not working. Let us consider 3 namespaces:

- participant1
- participant2
- gatewayns 

The gateway namespace hosts an API gateway which has the following routes:

- /particpiant1/*
- /participant2/*

The goal is simply to say that each participant can only call its all set of APIs (so participant1 can call /particpant1/ but not /participant2/. 

In the gateway namespace, I simply crafted those two policies:

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-nonp1top1
spec:  
  selector:
    matchLabels:
      app: t1t2
  action: DENY 
  rules:  
  - from:
    - source:
        notNamespaces: ["participant1-t1"]
  - to:
    - operation:
        methods: ["GET"]
        paths: ["*/participant1/*"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-nonp2top2
spec:  
  selector:
    matchLabels:
      app: t1t2
  action: DENY 
  rules:  
  - from:
    - source:
        notNamespaces: ["participant2-t2"]
  - to:
    - operation:
        methods: ["GET"]
        paths: ["*/participant2/*"]
---
```
The result is that all requests from my participant1 client are blocked whatever path is targeted. It seems that the "to" part of the rules is just ignored.

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [X] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
