### ISSUE TITLE
sidecar.istio.io/userVolume  not work

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#39312]
### Bug Description

config:
````
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice-v1
spec:
  selector:
    matchLabels:
      app: emailservice
      version: v1
  template:
    metadata:
      labels:
        app: emailservice
        version: v1
      annotations:
        sidecar.istio.io/userVolumeMount: '[{"name":"request-header", "mountPath":"/var/local/lib/wasm-filters", "readonly":true}]'
        sidecar.istio.io/userVolume: '[{"name":"request-header", "comfigMap":{"name":"request-header"}}]'
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: alexshu/emailservice:v0.2.1
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        # - name: DISABLE_TRACING
        #   value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        livenessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
```

error message:
```
2022-06-07T05:16:01.183940Z     warning envoy config    gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_7070: Invalid path: /var/local/lib/wasm-filters/request_header.wasm
10.68.249.207_8000: Invalid path: /var/local/lib/wasm-filters/request_header.wasm
10.68.229.129_443: Invalid path: /var/local/lib/wasm-filters/request_header.wasm
0.0.0.0_24231: Invalid path: /var/local/lib/wasm-filters/request_header.wasm
0.0.0.0_15010: Invalid path: /var/local/lib/wasm-filters/request_header.wasm
0.0.0.0_5000: Invalid path: /var/local/lib/wasm-filters/request_header.wasm
10.68.0.2_9153: Invalid path: /var/local/lib/wasm-filters/request_header.wasm
0.0.0.0_8080: Invalid path: /var/local/lib/wasm-filters/request_header.wasm
0.0.0.0_7000: Invalid path: /var/local/lib/wasm-filters/request_header.wasm
0.0.0.0_3550: Invalid path: /var/local/lib/wasm-filters/request_header.wasm
10.68.114.252_443: Invalid path: /var/local/lib/wasm-filters/request_header.wasm
0.0.0.0_9080: Invalid path: /var/local/lib/wasm-filters/request_header.wasm
0.0.0.0_80: Invalid path: /var/local/lib/wasm-filters/request_header.wasm
0.0.0.0_15014: Invalid path: /var/local/lib/wasm-filters/request_header.wasm
10.68.13.45_15021: Invalid path: /var/local/lib/wasm-filters/request_header.wasm
0.0.0.0_5050: Invalid path: /var/local/lib/wasm-filters/request_header.wasm
0.0.0.0_50051: Invalid path: /var/local/lib/wasm-filters/request_header.wasm
0.0.0.0_9555: Invalid path: /var/local/lib/wasm-filters/request_header.wasm
```
[root@node01 wholecase]# kubectl get cm -n demo-01 
NAME                 DATA   AGE
istio-ca-root-cert   1      42h
kube-root-ca.crt     1      42h
request-header       1      134m
wasm                 1      52m

the cm was created by   kubectl create cm request-header --from-file=request_header.wasm -n demo-01

the folder was empty::

```
[root@node01 wholecase]#  kubectl exec emailservice-v1-8dd85bfc4-wjqkp  -n demo-01 -c istio-proxy -- ls /var/local/lib/wasm-filters/
[root@node01 wholecase]# 
```




### Version

```prose
[root@node01 wholecase]# kubectl version --short
Client Version: v1.21.0
Server Version: v1.21.0

[root@node01 wholecase]# istioctl version
client version: 1.13.3
control plane version: 1.13.3
data plane version: 1.13.3 (21 proxies)
```


### Additional Information

_No response_
