### ISSUE TITLE
Istio Helm Chart 1.14.0 Not Setting Image Tag On deployment.apps/tetrate-istio

### ISSUE THREAD

**Issue by ptravishill** [istio/istio#39323]
### Bug Description

I am installing istio via helm 1.14.0. All works fine except the gateway chart. It is not setting the image tag on the [deployment.yaml](https://github.com/istio/istio/blob/master/manifests/charts/gateway/templates/deployment.yaml#L47)

I reviewed the documentation. Specifically [this](https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#customizing-injection) document. But, I cannot get it to work. 

If I manually set [this](https://github.com/istio/istio/blob/master/manifests/charts/gateway/templates/deployment.yaml#L47) to `istio/proxyv2:1.14.0`, it works. But, I want this working via helm and ArgoCD.

Here is my values.yaml:
```
global:
  hub: docker.io/istio
  tag: 1.14.0

base: {}

cni: {}

istiod:
  istio_cni:
    enabled: true

gateway:
  service:
    type: NodePort
```

Chart.yaml:
```
apiVersion: v2
name: istio
description: A Helm chart for Tetrate Istio Distribution (TID)

# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
type: application

# The chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.0.1

# Version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: "1.14.0"

dependencies:
  - name: base
    version: 1.14.0
    repository: https://istio-release.storage.googleapis.com/charts
  - name: cni
    version: 1.14.0
    repository: https://istio-release.storage.googleapis.com/charts
  - name: istiod
    version: 1.14.0
    repository: https://istio-release.storage.googleapis.com/charts
  - name: gateway
    version: 1.14.0
    repository: https://istio-release.storage.googleapis.com/charts
```

Default namespace has injection labeled:
`k describe namespace default`
```
Name:         default
Labels:       istio-injection=enabled
              kubernetes.io/metadata.name=default
Annotations:  <none>
Status:       Active
```

I also tried enabling injection on the istio-system namespace and redeploying. That did not work:
`k describe namespace istio-system`
```
Name:         istio-system
Labels:       argocd.argoproj.io/instance=tetrate-istio
              istio-injection=enabled
              kubernetes.io/metadata.name=istio-system
Annotations:  argocd.argoproj.io/sync-wave: -1
Status:       Active
```

### Version

```prose
istioctl version:

client version: 1.14.0
control plane version: 1.14.0
data plane version: 1.14.0 (4 proxies)


kubectl version --short:

Client Version: v1.24.1
Kustomize Version: v4.5.4
Server Version: v1.22.6-eks-14c7a48


helm version --short:

v3.8.1+g5cb9af4
```

### Additional Information

How do I fix this?

**Comment by howardjohn** [comment]
Its not set on the deployment, its added to the Pod at runtime

**Comment by ptravishill** [comment]
> 

Okay. With that being said, why isn't it being injected into the pod at runtime?

**Comment by ptravishill** [comment]
> Its not set on the deployment, its added to the Pod at runtime

@howardjohn I have tried many different things. Including

```
global:
  hub: gcr.io/istio-testing
  tag: latest
``` 
Along with:

```
istiod:
  istio_cni:
    enabled: true
  sidecarInjectorWebhook:
    enableNamespacesByDefault: true
```

And, tetrate-istio is still not getting injected at runtime.

```


```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    inject.istio.io/templates: gateway
    kubernetes.io/psp: eks.privileged
    prometheus.io/path: /stats/prometheus
    prometheus.io/port: "15020"
    prometheus.io/scrape: "true"
    sidecar.istio.io/inject: "true"
  creationTimestamp: "2022-06-09T15:41:05Z"
  generateName: tetrate-istio-8d6655986-
  labels:
    app: tetrate-istio
    istio: tetrate-istio
    pod-template-hash: 8d6655986
    sidecar.istio.io/inject: "true"
```

The pod has `sidecar.istio.io/inject: "true"`.

The namespace where it is deployed has it set as well:

```
  labels:
    argocd.argoproj.io/instance: tetrate-istio
    istio-injection: enabled
    kubernetes.io/metadata.name: istio-system
  name: istio-system
```
  
Any help is greatly appreciated.

**Comment by ptravishill** [comment]
Even after the new 1.14.1 helm release, I am still getting the same thing. 

I also tried manually setting the image in `.global.proxy.image` and received the same result.

Strangely, if I install it manually via [this](https://github.com/istio/istio/tree/master/manifests/charts/gateways/istio-ingress), it works even without injection enabled in the namespace.

**Comment by ptravishill** [comment]
@yckbilly1929 @howardjohn any update?

**Comment by yckbilly1929** [comment]
> @yckbilly1929 @howardjohn any update?

currently i got it working by directly cloning and modifying from https://github.com/istio/istio/tree/master/manifests/charts

and then install like

```
$ helm install istio-base -n istio-system -f istio/setup/charts/base/values.yaml ./istio/setup/charts/base

$ helm install istiod -f istio/setup/charts/istio-control/istio-discovery/values.yaml -n istio-system ./istio/setup/charts/istio-control/istio-discovery --wait

$ istioctl tag set prod-stable --revision 1-14-1 --overwrite
$ k label namespaces istio-ingress istio.io/rev=prod-stable --overwrite
$ k label namespaces istio-public istio.io/rev=prod-stable --overwrite

$ helm install istio-ingressgateway -f istio/setup/charts/gateway/ingress-values.yaml -n istio-ingress ./istio/setup/charts/gateway --wait

$ helm install istio-ingressgateway-public -f istio/setup/charts/gateway/public-values.yaml -n istio-public ./istio/setup/charts/gateway --wait
```

if I remember right, the gateway chart used by https://istio-release.storage.googleapis.com/charts is the legacy one <https://github.com/istio/istio/blob/master/manifests/charts/gateways/istio-ingress/templates/deployment.yaml>, where sidecar injection is hardcoded to be false
to make ingressgateway working on namespaces other than istio-system (as suggested <https://istio.io/latest/docs/setup/additional-setup/gateway/>), we have to use the new gateway chart from  <https://github.com/istio/istio/blob/master/manifests/charts/gateway/templates/deployment.yaml>

**Comment by howardjohn** [comment]
https://istio-release.storage.googleapis.com/charts has the newer one

**Comment by RafalSkolasinski** [comment]
I am observing the same. It if all 
```
dependencies:
- name: base
  version: 1.14.2
  repository: https://istio-release.storage.googleapis.com/charts
- name: istiod
  version: 1.14.2
  repository: https://istio-release.storage.googleapis.com/charts
- name: gateway
  version: 1.14.2
  repository: https://istio-release.storage.googleapis.com/charts
```
are present on first sync. If `gateway` is added later it does seem to work properly.
