### ISSUE TITLE
Recent change for east-west GW broke authz tests

### ISSUE THREAD

**Issue by nmittler** [istio/istio#39330]
### Bug Description

https://github.com/istio/istio/pull/38762 seems to have broken [TestAuthz_EgressGateway](https://github.com/istio/istio/blob/master/tests/integration/security/authz/authz_test.go#L1117), leading to the flakes related to that test in https://github.com/istio/istio/issues/39255.

Specifically, calls will fail when they follow the path `source->eastwest->egress->target`. They fail in the east-west gateway, because there are no endpoints for the SNI route for the egress-gateway.

I tried forcibly adding a DR to the `istio-system` namespace:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: test-egress
  namespace: istio-system
spec:
  host: "istio-egressgateway.istio-system.svc.cluster.local"
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 443
        tls:
          mode: ISTIO_MUTUAL
```

... but it had no effect (still no endpoints for the egress gateway SNI route).

I locally rolled back this change and it works fine.

### Version

```prose
master
```
