### ISSUE TITLE
Jwt issuer is not configured

### ISSUE THREAD

**Issue by foreachlife** [istio/istio#39427]
### Bug Description

When only JWT is configured without authorizationpolicy. When the header is "authorization", I keep getting "JWT issuer is not configuration". When the header is any other name is OK,I was use “jwt. io” has verified that JWT and jwks are OK。

Because I need to use JWT with authorization, and the authorization policy uses "authorization" to verify JWT, the name "authorization" must be used here.

I want to know why this. Can anyone answer my question?
Would really appreciate

This is my profile

```
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata: 
  name: authentication-jwt-token
  namespace: aaa
spec: 
  jwtRules: 
    - 
      forwardOriginalToken: true
      fromHeaders: 
        - 
          name: x-jwt-assertion  
          prefix: "Bearer "
      issuer:  test
      jwksUri: "http://test/jwks"
  selector: 
    matchLabels: 
      gateways: test-service
```

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata: 
  name: authorization-peer
  namespace: test
spec: 
  action: DENY
  rules: 
    - 
      from: 
        - 
          source: 
            notRequestPrincipals: 
              - "*"
        - 
          source: 
            namespaces: 
              - test
      to: 
        - 
          operation: 
            methods: 
              - GET
              - POST
              - PUT
              - DELETE
            notPaths: 
              - /admin/login
            paths: 
              - /admin
  selector: 
    matchLabels: 
      app: test-service

```

### Version

```prose
client version: 1.13.3
control plane version:1.13.3
data plane version: 1.13.3
Client Version: v1.19.10
Server Version: v1.19.10-r0-CCE22.3.1.B012
```

**Comment by foreachlife** [comment]
In addition to the authorizationpolicy, any header configured can be verified successfully

**Comment by foreachlife** [comment]
I solved this problem because JWT is not configured on the ingressgateway .
must configure JWT in both the ingressGateway and the service

Correct configuration:

```
--- 
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata: 
  name: authentication-jwt-token
  namespace: spaceA
spec: 
  jwtRules: 
    - 
      forwardOriginalToken: true
      fromHeaders: 
        - 
          name: Authorization
          prefix: "Bearer "
      issuer: test@test.com
      jwksUri: "http://test/jwks"  
	  selector: 
    matchLabels: 
      app: serviceA
--- 
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata: 
  name: authentication-jwt-token
  namespace: istio-system
spec: 
  jwtRules: 
    - 
      issuer: test@test.com
      jwksUri: "http://test/jwks"
      forwardOriginalToken: true
  selector:
    matchLabels:
      istio: ingressgateway
```
