### ISSUE TITLE
istio ingress does not honour secret set in tls field

### ISSUE THREAD

**Issue by qiujian16** [istio/istio#3942]
I set tls field in ingress resources when using istio ingress. 

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: productpage
          servicePort: 9080
        path: /productpage
      - backend:
          serviceName: productpage
          servicePort: 9080
        path: /login
      - backend:
          serviceName: productpage
          servicePort: 9080
        path: /logout
      - backend:
          serviceName: productpage
          servicePort: 9080
        path: /api/v1/products.*
  tls:
  - secretName: test
```

However, the tls certificate in tls is not used. Istio ingress still use the tls secret originally mounted in istio ingress deployment. Ingress controller should have a secret lister, and save the cert/key which is set in tls field into the container.
