### ISSUE TITLE
Configure warmupDurationSecs for slow start , config not take effect

### ISSUE THREAD

**Issue by bboshiZ** [istio/istio#39430]
### Bug Description

1. kubectl apply -f sleep.yaml -n default
2. kubectl apply -f helloworld.yaml -n default
3. kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: helloworld-test
  namespace: default
spec:
  host: helloworld.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      warmupDurationSecs: 123s
EOF

4. kubectl exec -it sleep-xxxx -- bash  && curl 0.0.0.0:15000/config_dump
5. there is no "slow_start_window" in config_dump

### Version

```prose
$istioctl version
client version: 1.14.0
control plane version: 1.14.0
data plane version: 1.14.0 (3 proxies)
```

### Additional Information

when add "simple: LEAST_REQUEST" or "simple: ROUND_ROBIN" , the "warmupDurationSecs" config take effect
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: helloworld-test
  namespace: default
spec:
  host: helloworld.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: LEAST_REQUEST
      warmupDurationSecs: 123s
```
![image](https://user-images.githubusercontent.com/12391320/173299976-398c3368-2ef6-47ce-be77-0f18ef4e8221.png)

by looking up the code, The cause of the problem may be here
```
https://github.com/istio/istio/blob/release-1.14/pilot/pkg/networking/core/v1alpha3/cluster.go#L757
	switch lb.GetSimple() {
	// nolint: staticcheck
	case networking.LoadBalancerSettings_LEAST_CONN, networking.LoadBalancerSettings_LEAST_REQUEST:
		ApplyLeastRequestLoadBalancer(c, lb)
	case networking.LoadBalancerSettings_RANDOM:
		c.LbPolicy = cluster.Cluster_RANDOM
	case networking.LoadBalancerSettings_ROUND_ROBIN:
		ApplyRoundRobinLoadBalancer(c, lb)
	case networking.LoadBalancerSettings_PASSTHROUGH:
		c.LbPolicy = cluster.Cluster_CLUSTER_PROVIDED
		c.ClusterDiscoveryType = &cluster.Cluster_Type{Type: cluster.Cluster_ORIGINAL_DST}
	default:
		c.LbPolicy = defaultLBAlgorithm()
                 **There should be a function here ApplyRoundRobinLoadBalancer or ApplyLeastRequestLoadBalancer or xxx**
	}
```
when  DestinationRule config not set loadBalancer.simple,  lb.GetSimple()  return LoadBalancerSettings_UNSPECIFIED
code run to default, warmupDurationSecs lost!

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by dddddai** [comment]
Currently slow start is only supported in `ROUND_ROBIN` and `LEAST_REQUEST` load balancer types.
https://istio.io/latest/docs/reference/config/networking/destination-rule/#LoadBalancerSettings
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/slow_start

**Comment by bboshiZ** [comment]
> Currently slow start is only supported in `ROUND_ROBIN` and `LEAST_REQUEST` load balancer types. https://istio.io/latest/docs/reference/config/networking/destination-rule/#LoadBalancerSettings https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/slow_start

in istio-1.14.0, the default lb is LEAST_REQUEST,   I think the following configuration should take effect

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: helloworld-test
  namespace: default
spec:
  host: helloworld.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      warmupDurationSecs: 123s
```
the configDump has `"lb_policy": "LEAST_REQUEST"` but no `"slow_start_config"`

![image](https://user-images.githubusercontent.com/12391320/173310716-d42fd2e5-48f5-47af-bfc4-b2ef4f5e0e81.png)
