### ISSUE TITLE
MTLS port override doesn't appear to work for headless services

### ISSUE THREAD

**Issue by nmittler** [istio/istio#39439]
### Bug Description

This was found while working on porting `security/reachability_test.go` to use the `echotest` framework.

PeerAuthn:

```yaml
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ .To.ServiceName }}
spec:
  selector:
    matchLabels:
      app: {{ .To.ServiceName }}
  mtls:
    mode: STRICT
  portLevelMtls:
    {{ (.To.PortForName `http`).WorkloadPort }}:
      mode: DISABLE
```

Where `To` is a target echo instance. This seems to work fine when sending to non-headless workloads. When sent to a headless service, the client gets 503s.

### Version

```prose
master
```
