### ISSUE TITLE
locality load balancing for multi region clusters does not not work when portLevelSettings is specified

### ISSUE THREAD

**Issue by aurelienpedron-efx** [istio/istio#39444]
### Bug Description

locality load balancing does not support portLevelSettings configured in the destinationrule 
For instance, the below would not work, the request would be balanced between the clusters in different regions/zones instead of remaining in the same cluster/region as specified by the localityLBSetting
```
trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
    loadBalancer:
      localityLbSetting:
        enabled: true
        failover:
        - from: australia-southeast1
          to: australia-southeast2
        - from: australia-southeast2
          to: australia-southeast1
      simple: ROUND_ROBIN
    outlierDetection:
      baseEjectionTime: 1m
      consecutive5xxErrors: 1
      interval: 1s
    portLevelSettings:
    - port:
        number: 80
      tls:
        mode: ISTIO_MUTUAL
```

while this one would work
```
trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
    loadBalancer:
      localityLbSetting:
        enabled: true
        failover:
        - from: australia-southeast1
          to: australia-southeast2
        - from: australia-southeast2
          to: australia-southeast1
      simple: ROUND_ROBIN
    outlierDetection:
      baseEjectionTime: 1m
      consecutive5xxErrors: 1
      interval: 1s
```

### Version

```prose
client version: 1.13.3
control plane version: 1.12.5
data plane version: 1.12.5-asm.0 (8 proxies)
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [X] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
