### ISSUE TITLE
Support failover cluster in DestinationRule

### ISSUE THREAD

**Issue by shonecyx** [istio/istio#39445]
This is related with https://github.com/istio/istio/issues/38105 for the failover feature.
Currently we only support locality based failover but we would like to extend this feature to support failover to a specified cluster for a given route. This is very helpful if the destination upstream cluster is down and we can failover to a default service, for example the homepage service.

Since VirtualService is not the right place, I would re-propose DestinationRule.

**Option 1:Add defaultService in the failover field.**
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: helloworld
spec:
  host: helloworld.sample.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
      localityLbSetting:
        enabled: true
        failover:
          - defaultService: homepage.sample.svc.cluster.local
 ```

**Option 2: Using Envoy Aggregate Cluster with a large enough overprovisioning_factor value can archive the fallback effect.**

Looks like defining the failover destination in DestinationRule's [LoadBalancerSettings](https://istio.io/latest/docs/reference/config/networking/destination-rule/#LoadBalancerSettings) could be a better choice:
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: helloworld
spec:
  host: helloworld.sample.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
      failover:
        failoverFactor: 5 # when healthy endpoint lower than this percentage, start to failover;
                          # this is used to calculate Aggregate Cluster's primary cluster's overprovisioning_factor
        destination:
          host: homepage.sample.svc.cluster.local
          subset: v2
          port:
            number: 8080
```
When failover is defined, the outbound cluster can be generated as an Envoy Aggregate Cluster, with native destination as primary cluster, and the failover destination as Secondary cluster.

Actually both options leverage the envoy priority level but implemented through different spec.

[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by shonecyx** [comment]
@howardjohn  any comment?

**Comment by shonecyx** [comment]
@howardjohn  @hzxuzhonghu  We plan to implement this function in Istio to support failover to a specified cluster. It makes sense to specify the failover cluster in the DestinationRule but would result to api change. Another option is that we can add two annotations in DestinationRule to avoid the api change:
```
    traffic.istio.io/defaultCluster: "homepage-svc"
    traffic.istio.io/failoverFactor: "5" ​​# when healthy endpoint lower than this percentage, start to failover;
```

**Comment by zengyuxing007** [comment]
Failover with conditions/context  may also need to be considered, such as:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: example-app
  namespace: default
spec:
  hosts:
    - example
  http:
  - match:
    - uri:
       prefix: /a
    route:
    - destination:
         host: example
         subset: v2
      fallback:
         target:
           host: example
           subset: base
  - route:
    - destination:
        host: example
        subset: v2
      fallback:
        case: noinstances|noavailabled
        target:
          host: example
          subset: v1
```
