### ISSUE TITLE
pilot-discovery periodically reads server disk data, resulting in high IO

### ISSUE THREAD

**Issue by dotbalo** [istio/istio#39459]
### Bug Description

I deployed istio on the k8s cluster, using istiooperator.
Istiooperator is configured as follows:
````
spec:
  components:
    ingressGateways:
    - enabled: true
      k8s:
        env:
        - name: ISTIO_META_OWNER
          value: kubernetes://apis/apps/v1/namespaces/istio-system/daemonsets/istio-ingressgateway
        nodeSelector:
          istio-ingressgateway: "true"
        overlays:
        - kind: Deployment
          name: istio-ingressgateway
          patches:
          - path: kind
            value: DaemonSet
          - path: spec.template.spec.hostNetwork
            value: true
          - path: spec.template.spec.dnsPolicy
            value: ClusterFirstWithHostNet
          - path: spec.strategy
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "2"
            memory: 2Gi
      name: istio-ingressgateway
    pilot:
      k8s:
        nodeSelector:
          istio-ingressgateway: "true"
  meshConfig:
    accessLogEncoding: JSON
    accessLogFile: /dev/stdout
    defaultConfig:
      tracing:
        sampling: 1
    discoverySelectors:
    - matchLabels:
        istio-discovery: "true"
    enableTracing: true
  profile: default
````
The status of the deployment is as follows:
````
# kubectl get po -n istio-system -owide
NAME                         READY   STATUS    RESTARTS       AGE    IP               NODE                         NOMINATED NODE   READINESS GATES
istio-ingressgateway-27gcd   1/1     Running   1 (2d4h ago)   2d5h   10.0.0.24      k8snode24   <none>           <none>
istio-ingressgateway-42q59   1/1     Running   0              2d5h   10.0.0.25      k8snode25   <none>           <none>
istio-ingressgateway-kfs7n   1/1     Running   0              2d5h   10.0.0.28      k8snode28   <none>           <none>
istio-ingressgateway-kj4k6   1/1     Running   0              2d5h   10.0.0.27      k8snode27   <none>           <none>
istio-ingressgateway-qnzbn   1/1     Running   0              2d5h   10.0.0.26      k8snode26   <none>           <none>
istiod-7695b997c9-q2vbp      1/1     Running   0              4d5h   172.20.183.237   k8snode27   <none>           <none>
istiod-7695b997c9-tbbwm      1/1     Running   0              8d     172.30.170.130   k8snode26   <none>           <none>
istiod-7695b997c9-wtjrb      1/1     Running   1 (8d ago)     8d     172.27.201.144   k8snode25   <none>           <none>
````
But the pilot-discovery on the k8snode26 node is often very high iowait.This node only deploys istio-ingressgateway, calico, kube-proxy, containerd, kubelet.

### Version

```prose
$ istioctl version
client version: 1.12.3
control plane version: 1.12.3
data plane version: 1.12.3 (58 proxies)

#  kubectl version --short
Client Version: v1.22.6
Server Version: v1.22.6

# containerd --version
containerd containerd.io 1.6.6

# calico version  v3.23.1 

# iptables --version
iptables v1.4.21

# uname -a
Linux k8snode26 4.20.13-1.el7.elrepo.x86_64 #1 SMP Wed Feb 27 10:02:05 EST 2019 x86_64 x86_64 x86_64 GNU/Linux
```

### Additional Information

I used some tools and found the following information, but I don't know what happened.

When using the top command, you can see that wa is very large:
![top](https://user-images.githubusercontent.com/25141522/173768472-18652554-a05a-41de-b254-e5ae612ede85.png)

At this time, using iotop, you can see that the disk read speed of pilot is 140M/s:
![iotop](https://user-images.githubusercontent.com/25141522/173768808-01e2001a-b5bf-4b1d-8693-7a5ba22f455e.png)

Then use the `pidstat -dt -p 17544 1` command to see which child thread frequently operates io:
![pidstat](https://user-images.githubusercontent.com/25141522/173785357-4821406d-a01d-426a-9e7b-3918a82a2f3c.png)

Finally, through `perf trace -t 17558`, the 17558 thread was found and the following information was printed:
![rt_sigre](https://user-images.githubusercontent.com/25141522/173785689-33d59a33-2590-4b6e-b8b7-3a29834614eb.png)

After the server IO is raised, the information of `rt_sigreturn `will be printed, but I don't know what the error is.
