### ISSUE TITLE
access logging: multiple providers doesn't work

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#39468]
```
  accessLogging:
  - providers:
      - name: envoy
  - providers:
      - name: envoy-json
```

only last one is used due to https://github.com/istio/istio/blob/6a1c1c887bfd7c802f564b15ba10ae9cfc0e0889/pilot/pkg/model/telemetry.go#L467.

cc @zirain
