### ISSUE TITLE
Istio Egress Gateway for TCP connection, hijacking traffic for other namespaces 

### ISSUE THREAD

**Issue by viveksuhanda** [istio/istio#39463]
Hello Team,

We have Istio v1.10.2 deployed on Azure Kubernetes Service using Istio Operator, which connects with Azure MySQL DB via Private Endpoint. While configuring egress traffic for this connection, we followed the below mentioned link,

https://istio.io/latest/blog/2018/egress-mongo/?&_ga=2.89514971.1904130223.1653286465-1348875568.1628146652#direct-tcp-egress-traffic-through-an-egress-gateway

So, this will be normal TCP traffic flow between the Istio Egress Gateway & Azure MySQL DB. Hence, for this purpose we expose additional TCP port in the in the Istio Egress Configuration. Now the issue is when we define "mesh" gateway in the virtual service the applications in other namespace also route their egress traffic via this route. We have defined the namespace parameter in the Service Entry, Destination Rules, Gateway & Virtual Service configuration.

These are the configuration files for your reference,

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: mysql
  namespace: app
spec:
  hosts:
  - mysqldb.mysql.database.azure.com
  ports:
  - number: 3306
    name: tcp
    protocol: TCP
  location: MESH_EXTERNAL
  resolution: DNS
  exportTo:
    - "."
```

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
  namespace: app
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 7777
      name: tcp
      protocol: TCP
    hosts:
    - mysqldb.mysql.database.azure.com
```
	
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-mysql
  namespace: app
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: mysql

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mysql
  namespace: app
spec:
  host: mysqldb.mysql.database.azure.com
```

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-mysql-through-egress-gateway
  namespace: app
spec:
  hosts:
  - mysqldb.mysql.database.azure.com
  gateways:
  - mesh
  - istio-egressgateway
  tcp:
  - match:
    - gateways:
      - mesh
      port: 3306
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: mysql
        port:
          number: 7777
  - match:
    - gateways:
      - istio-egressgateway
      port: 7777
    route:
    - destination:
        host: mysqldb.mysql.database.azure.com
        port:
          number: 3306
      weight: 100
```
