### ISSUE TITLE
pod in different zone get no request when set  outlierDetection

### ISSUE THREAD

**Issue by bboshiZ** [istio/istio#39477]
### Bug Description

1. istioctl install --set profile=default
2. kubectl apply -f sleep.yaml  &&  kubectl apply -f openresy.yaml
3. sleep pod is located in  ”topology.kubernetes.io/zone=ap-southeast-3a“ node
4. openresy pod-1 located in ”topology.kubernetes.io/zone=ap-southeast-3a“
5. openresy pod-2 located in ”topology.kubernetes.io/zone=ap-southeast-3b“
6. kubectl apply -f dstrule.yaml
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: openresty
spec:
  host: openresty.default.svc.cluster.local
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 7
      interval: 5m
      baseEjectionTime: 15m
```

7. pod-2 in ap-southeast-3b get no request from sleep

Because global localityLbSetting is enabled
https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer.go#L36

In our environment, cross-zone traffic is free. Therefore, i need to configure localityLbSetting to false 

No explanation of the interaction between outboundDetection and localityLbSetting can be found on the official website（istio.io）
can someone add a note here？

### Version

```prose
$istioctl version
client version: 1.14.0
control plane version: 1.14.0
data plane version: 1.14.0 (3 proxies)
```
