### ISSUE TITLE
Request allowing Istio Sidecar object has multiple egress listeners with same port 

### ISSUE THREAD

**Issue by l8huang** [istio/istio#39490]
**Describe the feature request**

Currently Sidecar doesn't allow multiple egress listeners have same port number(see [ValidateSidecar()](https://github.com/istio/istio/blob/master/pkg/config/validation/validation.go#L1095-L1097). 

When an application accesses hundreds of external services(each could have several DNS names) through egress gateway, the egress listener's hosts will be a super long list.

Considering HTTP/HTTPS/TLS can do multiplexing with host/SNI, Sidecar should be able to have multiple IstioEgressListeners with same port number, then below can be achieved:
- for an external service with multiple DNS names(which resolve to difference IP address), they can be grouped in one IstioEgressListener. This makes Sidecar object more maintainable and readable.
- we are also looking for terminating HTTPS on sidecar outbound listener(related issue https://github.com/istio/istio/issues/37160), which also relies on this feature request -- different hosts need different TLS certificates.

Basically, with this request below Sidecar:
```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: app
spec:
  egress:
  - hosts:
    - "./foo.com"
    - "./bar.com"
    port:
      number: 80
      protocol: HTTP 
````
can be defined as:
```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: app
spec:
  egress:
  - hosts:
    - "./foo.com"
    port:
      number: 80
      protocol: HTTP 
  - hosts:
    - "./bar.com"
    port:
      number: 80
      protocol: HTTP 
````
And for HTTP termination, it should be:
```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: app
spec:
  egress:
  - hosts:
    - "./foo.com"
    port:
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /path/to/foo.com.crt
      privateKey: path/to/foo.com.key
  - hosts:
    - "./bar.com"
    port:
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /path/to/bar.com.crt
      privateKey: path/to/bar.com.key
```

Changes required for this feature:
- Make validation web hook allows create Sidecar in this way
- Modify sidecar outbound HTTP route config generator
- Changes related to HTTPS termination on sidecar outbound listener(this will be covered in separate feature request)

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

For terminating HTTPS on sidecar's outbound listener, [ServerTLSSettings](https://istio.io/latest/docs/reference/config/networking/gateway/#ServerTLSSettings) need to be added to [IstioEgressListener](https://istio.io/latest/docs/reference/config/networking/sidecar/#IstioEgressListener).
