### ISSUE TITLE
Setting SNI on egress TLS connection doesn't work

### ISSUE THREAD

**Issue by andysworkshop** [istio/istio#39501]
### Bug Description

Minimal test configuration using the Wordpress internet site as a test target.
```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: bar-svc
  namespace: bar
spec:
  addresses:
  - 192.0.78.17/32
  endpoints:
  - address: 192.0.78.17
  hosts:
  - bar.svc
  location: MESH_EXTERNAL
  ports:
  - name: https-bar-svc
    number: 443
    protocol: HTTPS
  resolution: STATIC
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: bar-svc
  namespace: bar
spec:
  host: bar.svc
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE
        sni: wordpress.com
```
This sets up an entry for `http://bar.svc:443` that is upgraded to TLS by the `DestinationRule`. The `sni` attribute should set the SNI to `wordpress.com`. However it is ignored.

Test output from an in-mesh pod shell. Note the `subdomain=bar` in the output. This is where this particular internet site (wordpress) will log the subdomain that it received. If the test had worked then the response is a large amount of HTML from the wordpress home page.
```
bash-5.0# curl -i http://bar.svc:443
HTTP/1.1 302 Found
Server: nginx
Date: Fri, 17 Jun 2022 09:35:46 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Cookie
Location: https://wordpress.com/typo/?subdomain=bar
X-ac: 2.lhr _dfw
```

### Version

```prose
$ ic version
client version: 1.14.1
control plane version: 1.14.1
data plane version: 1.14.1 (17 proxies)

$ kc version --short
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.24.0
```

### Additional Information

`istioctl analyze` for the namespace:
```
Warning [IST0129] (DestinationRule bar/bar-svc) DestinationRule bar/bar-svc in namespace bar has TLS mode set to SIMPLE but no caCertificates are set to validate server identity for host: bar.svc at port number:443
```

Output from `istioctl bug-report` stripped out irrelevant namespaces:
```
$ ic bug-report

Target cluster context: kubernetes-admin@kubernetes

Running with the following config:

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2022-06-17 09:46:47.544163148 +0000 UTC



Cluster endpoint: https://192.168.198.129:6443
CLI version:
version.BuildInfo{Version:"1.14.1", GitRevision:"f59ce19ec6b63bbb70a65c43ac423845f1129464", GolangVersion:"go1.18.2", BuildStatus:"Clean", GitTag:"1.14.1"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.14.1", GitRevision:"f59ce19ec6b63bbb70a65c43ac423845f1129464", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.14.1"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.14.1}
```

**Comment by andysworkshop** [comment]
Yes the cluster config for `bar.svc` looks to be the same on my client pod as yours:
```
$ ic pc c testssl --fqdn bar.svc -o yaml
- circuitBreakers:
    thresholds:
    - maxConnections: 4294967295
      maxPendingRequests: 4294967295
      maxRequests: 4294967295
      maxRetries: 4294967295
      trackRemaining: true
  commonLbConfig:
    localityWeightedLbConfig: {}
  connectTimeout: 10s
  edsClusterConfig:
    edsConfig:
      ads: {}
      initialFetchTimeout: 0s
      resourceApiVersion: V3
    serviceName: outbound|443||bar.svc
  filters:
  - name: istio.metadata_exchange
    typedConfig:
      '@type': type.googleapis.com/envoy.tcp.metadataexchange.config.MetadataExchange
      protocol: istio-peer-exchange
  lbPolicy: LEAST_REQUEST
  metadata:
    filterMetadata:
      istio:
        config: /apis/networking.istio.io/v1alpha3/namespaces/bar/destination-rule/bar-svc
        default_original_port: 443
        services:
        - host: bar.svc
          name: bar.svc
          namespace: bar
  name: outbound|443||bar.svc
  transportSocket:
    name: envoy.transport_sockets.tls
    typedConfig:
      '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
      commonTlsContext:
        tlsParams:
          tlsMaximumProtocolVersion: TLSv1_3
          tlsMinimumProtocolVersion: TLSv1_2
        validationContext: {}
      sni: wordpress.com
  type: EDS
```
I'll get the access log and config dump shortly. I don't know if makes any difference but I'm using the DNS proxying feature in my mesh:
```
    defaultConfig:
      proxyMetadata:
        # Enable basic DNS proxying
        ISTIO_META_DNS_CAPTURE: "true"
        # Enable automatic address allocation, optional
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
```

**Comment by andysworkshop** [comment]
[bug-report.tar.gz](https://github.com/istio/istio/files/8939300/bug-report.tar.gz)

Output from `istioctl bug-report` attached as requested.

**Comment by howardjohn** [comment]
Hmm, the logs show it is matching the `bar.svc` cluster as well, which does have the SNI there!

I don't suppose there is any chance your app is not actually reading SNI? 

Here was how I tested it:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mitmproxy
spec:
  selector:
    matchLabels:
      app: mitmproxy
  template:
    metadata:
      labels:
        app: mitmproxy
        # Disable injector
        sidecar.istio.io/inject: "false"
        # But enable auto mtls to this destination
        security.istio.io/tlsMode: istio
    spec:
      containers:
      - name: mitmproxy
        image: mitmproxy/mitmproxy
        imagePullPolicy: IfNotPresent
        command:
        - sleep
        - "1000000"
        # mitmproxy -p 8081 --mode reverse:echo -v --set block_global=false
```

(exec in and run the mitmproxy command).
