### ISSUE TITLE
Wrong port used for prometheus metric endpoint in gateway chart

### ISSUE THREAD

**Issue by ajatprabha** [istio/istio#39535]
### Bug Description

The port exposed in deployment is `15090` but the one used in annotations is different (`15020`).

https://github.com/istio/istio/blob/9a33da1c5527988b6a78f1277730e56c62fcf8c5/manifests/charts/gateway/templates/deployment.yaml#L83-L86
https://github.com/istio/istio/blob/9a33da1c5527988b6a78f1277730e56c62fcf8c5/manifests/charts/gateway/values.yaml#L25

I also tried manually overriding this value with `values.yaml` but the pod still has annotation `prometheus.io/port=15020`, interestingly the `Deployment` and the `ReplicaSet` has correct annotation in podTemplate. I'm not sure what is overriding this value before pod creation.

```yaml
podAnnotations:
  prometheus.io/port: "15090"
```

### Version

```prose
Client Version: v1.22.9
Server Version: v1.22.8-gke.201
```

**Comment by ajatprabha** [comment]
I'm trying to expose metrics which are documented [here](https://istio.io/latest/docs/reference/config/metrics/). The doc mentioned metric like `istio_requests_total`, but I was not able to find those in my prometheus instance. I checked by port-forwarding to gateway(port: 15090) at `/stats/prometheus` and the counter is there. However, I suspect that because of wrong port prom server is not scraping it.

I want to use [this dashboard](7630).

**Comment by zirain** [comment]
you can try setup a prometheus like [this](https://github.com/istio/istio/blob/master/samples/addons/prometheus.yaml) do, I just test it a few days ago, it works fine.

BTW, `istio_requests_total` metric will generate once there're real requests.

**Comment by controlers** [comment]
@ajatprabha
Hi, I am having the same problem, as you discussed, istio_requests_total is generated whenever there is a request, but I directly requested
 kubectl exec -it -n istio-system istio-ingressgateway-xxx -- curl 127.0.0.1: 15020/stats/prometheus and did not get it, 
I would like to know how you finally solved it.  thanks

**Comment by tehlers320** [comment]
I think something is up with a port change on the metrics between versions. 1.13 seems to work but 1.15 doesnt for me on port 15090.

The reason why 15090 is a must is because prom-operator can only use port 15090 and im fairly certain ive set it correclty on 1.15 of istio-operator for this merge flag. 

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
  namespace: istio-system
spec:
  profile: default
  meshConfig:
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON.
    enablePrometheusMerge: true
    defaultConfig:
      proxyMetadata:
        # Enable basic DNS proxying
        ISTIO_META_DNS_CAPTURE: "true"
        # Enable automatic address allocation, optional
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
```

The problem for prom-operator is that 15020 is not a defined port and will not use it at all.

**Comment by pre** [comment]
@ajatprabha did you find the reason? I'm trying to figure out the same problem,
* Pod annotations have `prometheus.io/port: "15020"`
* Envoy stats answer from both `service-name:15090/stats/prometheus` and `service-name:15090/stats/prometheus` 
* However `localhost:15020/stats/prometheus` works but externally `service-name:15020/stats/prometheus` does not work outside from the Pod's localhost (which is how Prometheus would query it).

I'm trying to understand why the (default) annotation has the port 15020 which doesn't work for scraping.

**Comment by MemoAlfa** [comment]
Here is a work around, it works for me.

```
      - name: my-monitor
        podMetricsEndpoints:
          - interval: 30s
            path: /stats/prometheus
            relabelings:
              - action: replace
                regex: ([^:]+)(?::\d+)?;(\d+)
                replacement: $1:$2
                sourceLabels:
                  - __address__
                  - __meta_kubernetes_pod_annotation_prometheus_io_port
                targetLabel: __address__
```

**Comment by novotnej** [comment]
@MemoAlfa well I'll be damned. 

For anyone who stumbles upon this and wants to use Prometheus PodMonitor and ServiceMonitor to scrape the istio metrics endpoints, here is an example that currently works for me:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-proxy
  namespace: istio-system
  labels:
    istio: proxy
spec:
  jobLabel: component
  selector:
    matchLabels:
      security.istio.io/tlsMode: "istio"
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - interval: 15s
      path: /stats/prometheus
      relabelings:
        - action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          sourceLabels:
            - __address__
            - __meta_kubernetes_pod_annotation_prometheus_io_port
          targetLabel: __address__
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-eastwestgateway
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: eastwestgateway
  namespaceSelector:
    matchNames:
      - istio-system
  endpoints:
    - targetPort: http-envoy-prom
      path: /stats/prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  namespaceSelector:
    matchNames:
      - istio-system
  endpoints:
    - targetPort: http-envoy-prom
      path: /stats/prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istiod
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: pilot
  namespaceSelector:
    matchNames:
      - istio-system
  endpoints:
    - port: http-monitoring
      interval: 15s
```
