### ISSUE TITLE
Unable to use oauth2 proxy via EnvoyFilter; secret load issue

### ISSUE THREAD

**Issue by Stono** [istio/istio#39545]
### Bug Description

I've been battling for a few days now trying to use `EnvoyFilter` to inject `type.googleapis.com/envoy.extensions.filters.http.oauth2.v3.OAuth2`.

I got something working last night (yay), but when I came in this morning, it was failing.

TCP dumping the requests; the `client_secret` was missing from the `POST`:

<img width="449" alt="Screenshot 2022-06-22 at 08 04 14" src="https://user-images.githubusercontent.com/1486729/174967557-47b2b0a1-c037-4193-989b-8e6418f84e29.png">

This led me down the path of investigating why that would be the case (as obviously nothing had changed, i'd gone to bed).

When looking at `config_dump` of the `istio-proxy` I saw the following:
```
"dynamic_warming_secrets": [
    {
     "name": "token",
     "version_info": "uninitialized",
     "last_updated": "2022-06-22T07:11:21.039Z",
     "secret": {
      "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret",
      "name": "token"
     }
    }
```

Which i found odd, the secret configuration is:
```
              credentials:
                token_secret:
                  name: token
                  sds_config:
                    path: '/etc/istio/config/oauth2/..data/token-secret.yaml'
```

And that file is certainly there:
```
istio-proxy@platform-testing-d54956cc9-wvwqk:/$ cat /etc/istio/config/oauth2/..data/token-secret.yaml
resources:
  - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
    name: token
    generic_secret:
      secret:
        inline_string: "omitted"
```

I did then also try the symlinked path `/etc/istio/config/oauth2/token-secret.yaml` for the mounted secret, that didn't work either and interesting i ended up with 4 things in `dynamic_warming_secret`, with duplicated names, which doesn't feel right?:

<img width="423" alt="Screenshot 2022-06-22 at 08 22 06" src="https://user-images.githubusercontent.com/1486729/174968680-668694dd-e74b-4ae1-99be-7b80170ce44f.png">

Doubly interestingly if i delete the `EnvoyFilter` entirely, i'm still left with two secrets in `dynamic_warming_secrets` in an `unintialized` state.  

I can't see anything in the `istio-proxy` debug logs that gives any sort of clue what's going wrong 🤷 And as I say, this was working when I closed my laptop last night!

### Version

```prose
`1.13.5` on GKE
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [X] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
