### ISSUE TITLE
the pod of istio-ingressgateway is running, but the status of the pod's pod doesn't run.

### ISSUE THREAD

**Issue by suwliang3** [istio/istio#39572]
In https://istio.io/latest/docs/setup/install/external-controlplane/ ,
after run `istioctl install -f controlplane-gateway.yaml --context="${CTX_EXTERNAL_CLUSTER}"`,
the status of the pod:
```
[root@vm1 istio-1.12.6]# kubectl get po -n istio-system 
NAME                                    READY   STATUS    RESTARTS   AGE
istio-ingressgateway-698dc57b5d-44d4f   1/1     Running   0          81s
istiod-b578d9bb-k82p4                   1/1     Running   0          88s
```
the service:
```
[root@vm1 istio-1.12.6]# kubectl get svc  -n istio-system 
NAME                   TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                                           AGE
istio-ingressgateway   LoadBalancer   10.233.12.88   <pending>     15021:30361/TCP,15012:31404/TCP,15017:31771/TCP   19m
istiod                 ClusterIP      10.233.20.67   <none>        15010/TCP,15012/TCP,443/TCP,15014/TCP             19m
```
but the port of the ingressgateway 15017 and 15012 doesn't run.
```
[root@vm1 istio-1.12.6]# kubectl exec -it istio-ingressgateway-698dc57b5d-44d4f -n istio-system sh
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
$ netstat -lntp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:15090           0.0.0.0:*               LISTEN      16/envoy            
tcp        0      0 0.0.0.0:15090           0.0.0.0:*               LISTEN      16/envoy            
tcp        0      0 0.0.0.0:15090           0.0.0.0:*               LISTEN      16/envoy            
tcp        0      0 0.0.0.0:15090           0.0.0.0:*               LISTEN      16/envoy            
tcp        0      0 127.0.0.1:15000         0.0.0.0:*               LISTEN      16/envoy            
tcp        0      0 127.0.0.1:15004         0.0.0.0:*               LISTEN      1/pilot-agent       
tcp        0      0 0.0.0.0:15021           0.0.0.0:*               LISTEN      16/envoy            
tcp        0      0 0.0.0.0:15021           0.0.0.0:*               LISTEN      16/envoy            
tcp        0      0 0.0.0.0:15021           0.0.0.0:*               LISTEN      16/envoy            
tcp        0      0 0.0.0.0:15021           0.0.0.0:*               LISTEN      16/envoy            
tcp6       0      0 :::15020                :::*                    LISTEN      1/pilot-agent     
```

**Comment by zirain** [comment]
do you finish step 5 of https://istio.io/latest/docs/setup/install/external-controlplane/#set-up-the-control-plane-in-the-external-cluster ?

**Comment by suwliang3** [comment]
> do you finish step 5 of https://istio.io/latest/docs/setup/install/external-controlplane/#set-up-the-control-plane-in-the-external-cluster ?

@zirain Not yet. I only runned the first step `istioctl install -f controlplane-gateway.yaml --context="${CTX_EXTERNAL_CLUSTER}"`. Can you tell me why the status of the ingress-gateway's pod related to the `step 5 of https://istio.io/latest/docs/setup/install/external-controlplane/#set-up-the-control-plane-in-the-external-cluster` please?

**Comment by zirain** [comment]
after the following istio resources in step 5 created, you will see new listener in ingressgateway pod.
```
cat <<EOF > external-istiod-gw.yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: external-istiod-gw
  namespace: external-istiod
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 15012
        protocol: https
        name: https-XDS
      tls:
        mode: SIMPLE
        credentialName: $SSL_SECRET_NAME
      hosts:
      - $EXTERNAL_ISTIOD_ADDR
    - port:
        number: 15017
        protocol: https
        name: https-WEBHOOK
      tls:
        mode: SIMPLE
        credentialName: $SSL_SECRET_NAME
      hosts:
      - $EXTERNAL_ISTIOD_ADDR
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
   name: external-istiod-vs
   namespace: external-istiod
spec:
    hosts:
    - $EXTERNAL_ISTIOD_ADDR
    gateways:
    - external-istiod-gw
    http:
    - match:
      - port: 15012
      route:
      - destination:
          host: istiod.external-istiod.svc.cluster.local
          port:
            number: 15012
    - match:
      - port: 15017
      route:
      - destination:
          host: istiod.external-istiod.svc.cluster.local
          port:
            number: 443
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: external-istiod-dr
  namespace: external-istiod
spec:
  host: istiod.external-istiod.svc.cluster.local
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 15012
      tls:
        mode: SIMPLE
      connectionPool:
        http:
          h2UpgradePolicy: UPGRADE
    - port:
        number: 443
      tls:
        mode: SIMPLE
EOF

```
