### ISSUE TITLE
local ratelimit descriptor config not work

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#39596]
### Bug Description

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-ratelimit-svc-actions
spec:
  workloadSelector:
    labels:
      app: productpage
  configPatches:
    - applyTo: VIRTUAL_HOST
      match:
        context: SIDECAR_INBOUND
        routeConfiguration:
          vhost:
            name: "inbound|http|9080"
            route:
              action: ANY
      patch:
        operation: MERGE
        value:
          rate_limits:
          - actions:
            - request_headers:
                header_name: ":path"
                descriptor_key: PATH
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-local-ratelimit-svc
spec:
  workloadSelector:
    labels:
      app: productpage
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter
              token_bucket:
                max_tokens: 10
                tokens_per_fill: 10
                fill_interval: 60s
              filter_enabled:
                runtime_key: local_rate_limit_enabled
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              filter_enforced:
                runtime_key: local_rate_limit_enforced
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              response_headers_to_add:
                - append: false
                  header:
                    key: x-local-rate-limit
                    value: 'true'
              descriptors:
              - entries:
                - key: PATH
                  value: /productpage
                token_bucket:
                  max_tokens: 100
                  tokens_per_fill: 100
                  fill_interval: 60s
```

```
─────┬───────┬───────┬───────┬────────┬────────┬────────┬────────┬────────┬────────┬────────
 耗时│ 并发数│ 成功数│ 失败数│   qps  │最长耗时│最短耗时│平均耗时│下载字节│字节每秒│ 错误码
─────┼───────┼───────┼───────┼────────┼────────┼────────┼────────┼────────┼────────┼────────
   1s│     10│     10│   1131│   10.21│  147.91│    2.32│  979.05│  61,766│  61,748│200:10;429:1131
   2s│     10│     10│   2590│    5.13│  147.91│    2.32│ 1947.89│  88,028│  44,008│200:10;429:2590
   3s│     10│     10│   3909│    3.41│  147.91│    2.32│ 2930.98│ 111,770│  37,256│200:10;429:3909
   4s│     10│     10│   5210│    2.56│  147.91│    2.32│ 3903.93│ 135,188│  33,796│200:10;429:5210
   5s│     10│     10│   6647│    2.05│  147.91│    2.32│ 4877.10│ 161,054│  32,209│200:10;429:6647
   6s│     10│     10│   8150│    1.71│  147.91│    2.32│ 5857.40│ 188,108│  31,351│200:10;429:8150


```
it should be limit 100 request ,actually it is 10

![1656031368](https://user-images.githubusercontent.com/31508490/175438035-fca58b0e-513b-43f0-8719-c80208317c48.jpg)

![image](https://user-images.githubusercontent.com/31508490/175438060-1f06e140-d1e0-47b1-88cc-9780a216f6c2.png)

### Version

```prose
[root@node01 ~]# istioctl version
client version: 1.14.1
control plane version: 1.14.1
data plane version: 1.14.1 (9 proxies)

[root@node01 ~]# kubectl version --short
Client Version: v1.21.0
Server Version: v1.21.0
```
