### ISSUE TITLE
enableNamespacesByDefault doesn't work when revision tag is there and previous configuration has enableNamespacesByDefault disabled

### ISSUE THREAD

**Issue by sachin-ks** [istio/istio#39604]
### Bug Description

enableNamespacesByDefault doesn't work when revision tag is there and the previous configuration had enableNamespacesByDefault disabled.

### Version

```prose
$ istioctl version
client version: 1.14.1
control plane version: 1.14.1
data plane version: none

$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.1
Kustomize Version: v4.5.4
Server Version: v1.22.9-eks-a64ea69
```

### Steps to reproduce
save this as disabledByDefault.yaml :
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  profile: minimal
  revision: 1-14-1
```

save this as enabledByDefault.yaml :

```apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  profile: minimal
  revision: 1-14-1
  values:
    sidecarInjectorWebhook:
      enableNamespacesByDefault: true
```
      
Do:
`$ istioctl install -f disabledByDefault.yaml`
Then do:
`$ istioctl install -f enabledByDefault.yaml`

The configmap istio-sidecar-injector-1-14-1 shows `"enableNamespacesByDefault": true,`
But sidecar injection does not work when a pod is created.

**Comment by litong01** [comment]
@sachin-ks followed your steps, and added the step to create a pod like the following:

```
kubectl create namespace sample

cat << EOF | kubectl apply -n sample -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-v1
  labels:
    app: helloworld
    istio.io/rev: 1-14-1
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      version: v1
  template:
    metadata:
      labels:
        app: helloworld
        version: v1
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: helloworld
        image: docker.io/istio/examples-helloworld-v1
        resources:
          requests:
            cpu: "100m"
        env:
        - name: FLASK_RUN_PORT
          value: "5000"
        - name: FLASK_RUN_HOST
          value: "::"
        - name: FLASK_ENV
          value: "development"
        - name: FLASK_APP
          value: "/opt/microservices/app.py"
        command: ["flask", "run"]
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
EOF
```

notice that you will need to specify the revision label to match the istio revision. Injection worked fine.

**Comment by sachin-ks** [comment]
@litong01 Actually, the injection should happen without labeling the namespace or pod because enableNamespacesByDefault is true.

**Comment by sachin-ks** [comment]
@litong01  To confirm the expected behaviour, you can do:
1. Uninstall Istio
2. Install Istio using this file:
```
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  profile: minimal
  revision: 1-14-1
  values:
    sidecarInjectorWebhook:
      enableNamespacesByDefault: true
 ```
 3. Create a new pod (notice that I have removed the labels from the yaml):
 ```
 kubectl create namespace sample
 
cat << EOF | kubectl apply -n sample -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-v1
  labels:
    app: helloworld
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      version: v1
  template:
    metadata:
      labels:
        app: helloworld
        version: v1
    spec:
      containers:
      - name: helloworld
        image: docker.io/istio/examples-helloworld-v1
        resources:
          requests:
            cpu: "100m"
        env:
        - name: FLASK_RUN_PORT
          value: "5000"
        - name: FLASK_RUN_HOST
          value: "::"
        - name: FLASK_ENV
          value: "development"
        - name: FLASK_APP
          value: "/opt/microservices/app.py"
        command: ["flask", "run"]
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
EOF
 ```
 
 The sidecar injection will happen, which is expected. 
 But if you follow my steps from the original issue and try to create a pod, the sidecar injection will not happen, which is not expected.

**Comment by litong01** [comment]
That is right. You need the revision label, not the injection label. Please look at the example I posted. The behavior is correct, you need the revision label since you are using revisioned Istio. That is not the same thing as injection label.

Sent from my iPhone

On Jun 24, 2022, at 3:56 PM, Sachin Kumar ***@***.***> wrote:

﻿
@litong01 To confirm the expected behaviour, you can do: Uninstall Istio Install Istio using this file: kind: IstioOperator metadata: namespace: istio-system name: istiocontrolplane spec: profile: minimal revision: 1-14-1 values: sidecarInjectorWebhook:
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.

ZjQcmQRYFpfptBannerEnd

@litong01<https://github.com/litong01> To confirm the expected behaviour, you can do:

  1.  Uninstall Istio
  2.  Install Istio using this file:

kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  profile: minimal
  revision: 1-14-1
  values:
    sidecarInjectorWebhook:
      enableNamespacesByDefault: true


  1.  Create a new pod (notice that I have removed the labels from the yaml):

kubectl create namespace sample

cat << EOF | kubectl apply -n sample -f -
apiVersion: apps/v1
kind: Deployment
metadata:
 name: helloworld-v1
 labels:
   app: helloworld
   version: v1
spec:
 replicas: 1
 selector:
   matchLabels:
     app: helloworld
     version: v1
 template:
   metadata:
     labels:
       app: helloworld
       version: v1
   spec:
     containers:
     - name: helloworld
       image: docker.io/istio/examples-helloworld-v1
       resources:
         requests:
           cpu: "100m"
       env:
       - name: FLASK_RUN_PORT
         value: "5000"
       - name: FLASK_RUN_HOST
         value: "::"
       - name: FLASK_ENV
         value: "development"
       - name: FLASK_APP
         value: "/opt/microservices/app.py"
       command: ["flask", "run"]
       imagePullPolicy: IfNotPresent #Always
       ports:
       - containerPort: 5000
EOF


The sidecar injection will happen, which is expected.
But if you follow my steps from the original issue and try to create a pod, the sidecar injection will not happen, which is not expected.

**Comment by sachin-ks** [comment]
@litong01 I am using your example only. But please notice that in my previous comment, in 3rd step, I have removed the revision label but still sidecar injection will work.

**Comment by litong01** [comment]
You removed the revision label and injection still happens? Hmmm, if that is the case we are seriously broken. My tests showed if revision label is not there, injection won’t happen which is expected.

Sent from my iPhone

On Jun 24, 2022, at 4:09 PM, Sachin Kumar ***@***.***> wrote:

﻿
@litong01 I am using your example only. But please notice that in my previous comment, in 3rd step, I have removed the revision label but still sidecar injection will work. — Reply to this email directly, view it on GitHub, or ‍ ‍ ‍ ‍ ‍ ‍
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.

ZjQcmQRYFpfptBannerEnd

@litong01<https://github.com/litong01> I am using your example only. But please notice that in my previous comment, in 3rd step, I have removed the revision label but still sidecar injection will work.

**Comment by sachin-ks** [comment]
@litong01 Yes, injection still happens because enableNamespacesByDefault is true. There was a similar issue but it was fixed. Just for your reference: https://github.com/istio/istio/issues/36261

**Comment by litong01** [comment]
@sachin-ks with 1.14.1, with revision label in a work load spec, things will work as expected, if you do not use revision label, injection will not work which is also expected since your istio installed as revisioned istio, to make it work you will need the revision label, notice that enableNamespaceByDefault and revision are two different things. as far as I can see, things work as expected, please close this issue.

**Comment by sachin-ks** [comment]
@litong01 as I have explained earlier, I was able to make injection work with revisioned Istio without the label in the workload spec. There is only one case where injection doesn't seem to work when enableNamespaceByDefault is enabled (which is explained in my original issue). Can you please point me to the documentation where it says that enableNamespaceByDefault will not work if Istio is revisioned?

**Comment by sachin-ks** [comment]
Expected behavior from the documentation: https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#deploying-an-app

If the istio-injection label and the istio.io/rev label are both present on the same namespace, the istio-injection label will take precedence.

The injector is configured with the following logic:

1. If either label is disabled, the pod is not injected
2. If either label is enabled, the pod is injected
3. If neither label is set, the pod is injected if .values.sidecarInjectorWebhook.enableNamespacesByDefault is enabled. This is not enabled by default, so generally this means the pod is not injected.

**Comment by litong01** [comment]
@howardjohn my understanding is when revision tag is used, then all workload which wanting to be controlled by that revisioned control plane should bear the same revision tag, only under that condition, enabledNamespace config should control if injection should happen or not happen per namespace. Otherwise, we are mixed up revision with non revision.

**Comment by howardjohn** [comment]
that is why only one revision can use enableNamespacesByDefault

**Comment by sachin-ks** [comment]
@howardjohn yes, it works if I do `istioctl install -f enabledByDefault.yaml` first, instead of first "disable" then "enable".

**Comment by howardjohn** [comment]
because enableNamespacesByDefault means "if there is no injection, use this revision"

**Comment by cnvergence** [comment]
I have created a draft PR, but need to test it a bit more
- https://github.com/istio/istio/pull/39674

**Comment by litong01** [comment]
@howardjohn @cnvergence I am not so sure about this any more. I am seeing some rather weird behaviors now. Would like to do a bit more testing to figure out the behaviors, seems to me when the configmap istio-sidecar-injector policy is enabled (which is default), any other labels do not matter, injection will happen anyway regardless the value of enableNamespacesByDefault. Have you all seen something like that?

**Comment by litong01** [comment]
@cnvergence since you provided the fixes for the issue, would you like to take over this issue?

**Comment by litong01** [comment]
@sachin-ks @howardjohn @cnvergence if it is set to true, then change to false, the injection will still happen. This behavior confirms the conclusion by @cnvergence that the manifest generation uses old value instead of the latest.

**Comment by cnvergence** [comment]
> @cnvergence since you provided the fixes for the issue, would you like to take over this issue?

@litong01  Alright, I will proceed with my Pull Request

**Comment by cnvergence** [comment]
Hey @sachin-ks, my changes were reverted, because of the wrong assumptions on how the default tag should work
Thanks, @Monkeyanator for the clarification on [this](https://github.com/istio/istio/pull/40050)

So if you install Istio with revision, using this file
`istioctl install -f disabledByDefault.yaml`

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  profile: minimal
  revision: 1-14-1
```
Then to change the default sidecar injection behaviour, you should overwrite the installed default tag with setting `--auto-inject-namespaces` flag:
`istioctl tag set default --revision 1-14-1 --auto-inject-namespaces --overwrite`

Still, I would believe it is needed to provide an option to overwrite the default tag, if it exists, when `enableNamespacesByDefault: true` is passed in the Helm values, WDYT?
