### ISSUE TITLE
source_cluster unset in TCP telemetry

### ISSUE THREAD

**Issue by jshaughn** [istio/istio#39614]
### Bug Description

At times `source_cluster="unknown"` is found in TCP destination-reported metrics.   I'm not exactly sure what the exact conditions are but the problem seems fairly easy to reproduce given the steps below.   Here is an example of the problem telemetry:

`istio_tcp_sent_bytes_total{reporter="destination",source_workload="debugbox"}`

```
istio_tcp_sent_bytes_total{app="tcpserver", connection_security_policy="mutual_tls", destination_app="tcpserver", destination_canonical_revision="latest", destination_canonical_service="tcpserver", destination_cluster="Kubernetes", destination_principal="spiffe://cluster.local/ns/test/sa/default", destination_service="tcpserver.test.svc.cluster.local", destination_service_name="tcpserver", destination_service_namespace="test", destination_version="unknown", destination_workload="tcpserver", destination_workload_namespace="test", instance="10.244.0.84:15020", job="kubernetes-pods", namespace="test", pod="tcpserver-59db975c4-hcvhw", pod_template_hash="59db975c4", reporter="destination", request_protocol="tcp", response_flags="-", security_istio_io_tlsMode="istio", service_istio_io_canonical_name="tcpserver", service_istio_io_canonical_revision="latest", source_app="debugbox", source_canonical_revision="latest", source_canonical_service="debugbox", source_cluster="Kubernetes", source_principal="spiffe://cluster.local/ns/test/sa/default", source_version="unknown", source_workload="debugbox", source_workload_namespace="test"}
0
istio_tcp_sent_bytes_total{app="tcpserver", connection_security_policy="mutual_tls", destination_app="tcpserver", destination_canonical_revision="latest", destination_canonical_service="tcpserver", destination_cluster="Kubernetes", destination_principal="spiffe://cluster.local/ns/test/sa/default", destination_service="tcpserver.test.svc.cluster.local", destination_service_name="tcpserver", destination_service_namespace="test", destination_version="unknown", destination_workload="tcpserver", destination_workload_namespace="test", instance="10.244.0.84:15020", job="kubernetes-pods", namespace="test", pod="tcpserver-59db975c4-hcvhw", pod_template_hash="59db975c4", reporter="destination", request_protocol="tcp", response_flags="-", security_istio_io_tlsMode="istio", service_istio_io_canonical_name="tcpserver", service_istio_io_canonical_revision="latest", source_app="debugbox", source_canonical_revision="latest", source_canonical_service="debugbox", source_cluster="unknown", source_principal="spiffe://cluster.local/ns/test/sa/default", source_version="unknown", source_workload="debugbox", source_workload_namespace="test"}
228
```

Note that the only differing field in the two time-series is `source_cluster` .  Also not that although the count is 0 for the problem time-series, that is not always true in my testing, the count may increase.

Here are the reproduction steps (the same as presented in https://github.com/kiali/kiali/issues/5240, where the problem was reported as a Kiali issue, but the root cause seems to be in the telemetry.

## How to reproduce it

This example is based on the following github issue: https://github.com/istio/istio/issues/22082
We will create 3 apps:
- Debugbox: An image meant for debugging.
- Tcpserver: An istio tcp echo server written in Go. 
- Httpserver: A http server. 

### Prerrequisites
mTLS should be enabled. It can be mesh-wide enabled: 

```
kubectl apply -n istio-system -f - <<EOF
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: "default"
spec:
  mtls:
    mode: STRICT
EOF
```

### Steps

```
kubectl create ns test
kubectl label namespace test istio-injection=enabled
kubectl create -f test.yaml
```

test.yaml
```

apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpserver
  namespace: test
---
apiVersion: v1
kind: Service
metadata:
  name: httpserver
  namespace: test
  labels:
    app: httpserver
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: httpserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpserver
      version: v1
  template:
    metadata:
      labels:
        app: httpserver
        version: v1
    spec:
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpserver
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: debugbox
  namespace: test
---
apiVersion: v1
kind: Service
metadata:
  name: debugbox
  namespace: test
  labels:
    app: debugbox
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: debugbox
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debugbox
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debugbox
  template:
    metadata:
      labels:
        app: debugbox
    spec:
      containers:
      - name: debugbox
        image: markeijsermans/debug
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: tcpserver
  namespace: test
  labels:
    app: tcpserver
spec:
  ports:
  - port: 9000
    name: tcp
  selector:
    app: tcpserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcpserver
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcpserver
  template:
    metadata:
      labels:
        app: tcpserver
    spec:
      containers:
      - name: tcpserver
        image: istio/tcp-echo-server:1.1
        imagePullPolicy: IfNotPresent
        args: [ "9000", "hello" ]
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tcpserver
  namespace: test


```

## Generate requests from debugbox:
Http

`kubectl exec $(kubectl get pod -l app=debugbox -n test -o jsonpath={.items..metadata.name}) -c debugbox -n test -- curl http://httpserver:8000/ip -s -o /dev/null -w "debugbox.test to httpserver: %{http_code}\n"`

Telnet

Install first:
`kubectl exec $(kubectl get pod -l app=debugbox -n test -o jsonpath={.items..metadata.name}) -c debugbox -n test -- apt install telnet -y`

Open session:
`kubectl exec -it $(kubectl get pod -l app=debugbox -n test -o jsonpath={.items..metadata.name}) -c debugbox -n test -- telnet tcpserver 9000`

### Version

```prose
$ kind --version
kind version 0.14.0

$ istioctl version
client version: 1.14.1
control plane version: 1.14.1
data plane version: 1.14.1 (35 proxies)

$ kubectl version --short
Client Version: v1.20.5
Server Version: v1.24.0
```

### Additional Information

I did not see this problem when the source workload sent only TCP requests, so maybe it has something to do with the fact that in the recreation steps `debugbox` sends both TCP and HTTP requests, totally not sure, that fact may be irrlelevant.
