### ISSUE TITLE
I configured vm sidecar workloadgroup locality but actually it not effect？

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#39631]
### Bug Description

```
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadGroup
metadata:
  name: httpd-147
  namespace: vm-httpd
spec:
  metadata:
    labels:
      app: httpd
      type: vm
      region: us-central2
    annotations:
      test: test
  probe:
    periodSeconds: 5
    initialDelaySeconds: 5
    successThreshold: 1
    failureThreshold: 3
    timeoutSeconds: 2
    tcpSocket:
      port: 80
  template:
    serviceAccount: sa-httpd
    network: network2
    locality: "us-central2/z2/sz02"
```

![image](https://user-images.githubusercontent.com/31508490/175798293-545fc2cd-f7b4-4f08-8749-4de2d2e1059e.png)

locality is enpty:
when I using locality distribute loadblance there have not any endpoint？

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: httpd
spec:
  host: httpd.vm.demo
  trafficPolicy:
    loadBalancer:
      localityLbSetting:
        enabled: true
        distribute:
        - from: "us-central3/z3/*"
          to:
            "us-central2/z2/*": 100
    outlierDetection:
      consecutive5xxErrors: 1
      interval: 5m
      baseEjectionTime: 15m
```

[root@node01 ~]# istioctl pc endpoint -n istio ratings-v1-77b9bfdd59-bpnqk|grep vm
172.20.1.130:9080                                       HEALTHY     OK                outbound|9080|v2-mysql-vm|ratings.istio.svc.cluster.local

if the dr is deleted:then
```
[root@node01 ~]# istioctl pc endpoint -n istio ratings-v1-77b9bfdd59-bpnqk|grep vm
172.20.1.130:9080                                       HEALTHY     OK                outbound|9080|v2-mysql-vm|ratings.istio.svc.cluster.local
192.168.229.146:80                                      HEALTHY     OK                outbound|80||httpd.vm.demo
192.168.229.147:80                                      HEALTHY     OK                outbound|80||httpd.vm.demo
[root@node01 ~]# 
```

### Version

```prose
[root@node01 ~]# istioctl version
client version: 1.14.1
control plane version: 1.14.1
data plane version: 1.14.1 (14 proxies), 1.13.0 (2 proxies)

[root@node01 ~]# kubectl version --short
Client Version: v1.21.0
Server Version: v1.21.0
```
