### ISSUE TITLE
Virtual Services not merging

### ISSUE THREAD

**Issue by bradenwright** [istio/istio#39632]
### Bug Description

According to the docs, [Split large virtual services and destination rules into multiple resources](https://istio.io/latest/docs/ops/best-practices/traffic-management/#split-virtual-services) I should be able to use more than 1 virtual service with the same host name, yet for some reason I can't get this to work when split up:

```
# Source: echo-grpc-web-demo/templates/frontend/virtual_service.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: echo-web
  namespace: api
spec:
  hosts:
  - "app.stage.example.com"
  gateways:
  - istio-system/mci-ingressgateway
  http:
  - match:
    - uri:
        prefix: /dist
    - uri:
        exact: /
    route:
    - destination:
        host:  echo-web
        port:
          number: 8090
---
# Source: echo-grpc-web-demo/templates/backend/virtual_service.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: echo-grpc
  namespace: api
spec:
  hosts:
  - "app.stage.example.com"
  gateways:
  - istio-system/mci-ingressgateway
  http:
  - match:
    - uri:
        prefix: /proto.EchoService
    rewrite:
      authority: "server-grpc.stage.example.com"
    route:
    - destination:
        host: server-grpc
        port:
          number: 80
    corsPolicy:
      allowOrigin:
        - "*"
      allowMethods:
        - POST
        - GET
        - OPTIONS
        - PUT
        - DELETE
      allowHeaders:
        - grpc-timeout
        - content-type
        - keep-alive
        - user-agent
        - cache-control
        - content-type
        - content-transfer-encoding
        - custom-header-1
        - x-accept-content-transfer-encoding
        - x-accept-response-streaming
        - x-user-agent
        - x-grpc-web
      maxAge: 1728s
      exposeHeaders:
        - custom-header-1
        - grpc-status
        - grpc-message
```

However it works fine if I combine them into a single virtual service:

```
# Source: echo-grpc-web-demo/templates/virtual_service.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: echo-grpc
  namespace: api
spec:
  hosts:
  - "app.stage.example.com"
  gateways:
  - istio-system/mci-ingressgateway
  http:
  - match:
    - uri:
        prefix: /dist
    - uri:
        exact: /
    route:
    - destination:
        host:  echo-web
        port:
          number: 8090
  - match:
    - uri:
        prefix: /proto.EchoService
    rewrite:
      authority: "server-grpc.stage.example.com"
    route:
    - destination:
        host: server-grpc
        port:
          number: 80
    corsPolicy:
      allowOrigin:
        - "*"
      allowMethods:
        - POST
        - GET
        - OPTIONS
        - PUT
        - DELETE
      allowHeaders:
        - grpc-timeout
        - content-type
        - keep-alive
        - user-agent
        - cache-control
        - content-type
        - content-transfer-encoding
        - custom-header-1
        - x-accept-content-transfer-encoding
        - x-accept-response-streaming
        - x-user-agent
        - x-grpc-web
      maxAge: 1728s
      exposeHeaders:
        - custom-header-1
        - grpc-status
        - grpc-message
```

### Version

```prose
bash-5.1# ./istioctl version
client version: 1.12.7-asm.2
control plane version: 1.12.7
data plane version: 1.12.7-asm.2 (6 proxies)

bash-5.1# kubectl version --short
Client Version: v1.23.5
Server Version: v1.21.12-gke.2200
```

**Comment by howardjohn** [comment]
When you say it doesn't work, what does that mean? Does it always go to echo-web?

**Comment by bradenwright** [comment]
Yeah I really have no clue why.  The web portion works fine, but it doesn't seem to make it to the grpc-web backend.  I'm getting this rpc error, which I get if the route / host for grpc-web is not setup.  More than happy to provide more debug details if someone can give me details on what to run / provide

**Comment by bradenwright** [comment]
Any advice on something to try or info I could relay to help track down the issue?

**Comment by bradenwright** [comment]
@howardjohn I didn't think I had any overlapping rules at all.  I am specifiy:

```
    - uri:
        prefix: /dist
    - uri:
        exact: /
```
and
```
    - uri:
        prefix: /proto.EchoService
```
