### ISSUE TITLE
DOES ISTIO SSL TERMINATION REQUIRE ADDITIONAL CONFIGURATION TO SUPPORT CONNECTIONS TO LDAP PORTS THROUGH GATEWAY

### ISSUE THREAD

**Issue by gnanirahulnutakki** [istio/istio#39664]
Hi, I work with a LDAP application that uses 2636/2389 as LDAPS/LDAP ports, I was setting up SSL termination for the same application to reach to the main UI and other parts.

1. Created Certificate (letsencrypt) put that in secret
2. Created Gateway and VIrtual Service with Desination rules to access the application

I am able to reach the application with https://<host>:7171/main/login
And  I am also able to reach to other pages as mentioned in the Gateway and Virtual Service files

But when I try to reach the ldaps part of the application either though " curl -v ldaps://<host>:636" or using "ldapsearch "
It does not connect and my intuition is that the handshake is failing.

The idea is to terminate the SSL (ldaps) connection at the gateway and then route the query to the backend (application)

**Gateway and Virtual Service Configuration**
```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: fid-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port: 
      number: 636
      name: tls 
      protocol: TLS
    tls:
      mode: SIMPLE
      credentialName: tr-istio-ltbdx 
      maxProtocolVersion: TLSV1_3
      minProtocolVersion: TLSV1_2
    hosts:
    - host
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: tr-istio-ltbdx 
    hosts:
    - host
  - port:
      number: 8090
      name: https-api
      protocol: HTTPS
      # maxProtocolVersion: TLSV1_3
      # minProtocolVersion: TLSV1_2    
    tls:
      mode: SIMPLE
      credentialName: tr-istio-ltbdx 
    hosts: 
    - host
  - port:
      number: 7171
      name: https-cp
      protocol: HTTPS
      # maxProtocolVersion: TLSV1_3
      # minProtocolVersion: TLSV1_2
    tls:
      mode: SIMPLE
      credentialName: tr-istio-ltbdx 
    hosts:
    - host
  - port:
      number: 9101
      name: https-admin
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: tr-istio-ltbdx
      # maxProtocolVersion: TLSV1_3
      # minProtocolVersion: TLSV1_2
    hosts:
    - host
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: fid
spec:
  hosts:
    - host
  gateways:
  - fid-gateway 
  tcp:
  - match:
    - port: 636
    route:
    - destination:
        host: fid
        port:
          number: 2389
  http:
  - match:
    - port: 443
    route:
    - destination:
        host: fid
        port: 
          number: 8089

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: fid-cp
spec:
  hosts:
    - host
  gateways:
  - fid-gateway
  http:
  - match:
    - port: 7171
    route:
    - destination:
        host: fid-cp
        port:
          number: 7171
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: fid-api
spec:
  hosts:
    - fid.opcl.net
  gateways:
  - fid-gateway
  http:
  - match:
    - port: 8090
    route:
    - destination:
        host: fid-cp
        port:
          number: 8090

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: fid-admin
spec:
  hosts:
    - fid.opcl.net
  gateways:
  - fid-gateway
  http:
  - match:
    - port: 9101
    route:
    - destination:
        host: fid
        port:
          number: 9100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: fid-dest-rule
spec: 
  host: fid-cp
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 7171
      tls: 
        mode: SIMPLE
    - port:
        number: 8090
      tls:
        mode: SIMPLE
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: fid-dest-rule-2
spec: 
  host: fid-cp
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 2636
      tls: 
        mode: SIMPLE
    tls:
      mode: SIMPLE

---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: fid
  namespace: istio-ssl-termination
spec:
  selector: 
    matchLabels: 
      app.kubernetes.io/core-name: fid
  mtls: 
    mode: PERMISSIVE
  portLevelMtls: 
    2636:
      mode: PERMISSIVE
```

I have also opened ports on the ingress loadbalancer

**The below is the application yaml**

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: fidrootcreds
type: Opaque
data:
  username: Y249RGlyZWN0b3J5IE1hbmFnZXI= 
  password: c2VjcmV0MTIzNA==
---
apiVersion: v1
data:
  ZK: "external"
  ZK_CONN_STR: "zookeeper.istio-ssl-termination.svc.cluster.local:2181" # this should match the service name from zk deployment
  ZK_CLUSTER: "fid"
  LICENSE: ""
kind: ConfigMap
metadata:
  labels:
    role: fid
  name: fid-environment-variables
---
apiVersion: v1
kind: Service
metadata:
  name: fid
  labels:
    app: fid
spec:
  ports:
    - port: 9100
      name: admin-http
    - port: 2389
      name: ldap
    - port: 2636
      name: ldaps
  selector:
    app: fid
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: fid-cp
  labels:
    app: fid-cp
spec:
  ports:
    - port: 7070
      name: cp-http
    - port: 7171
      name: cp-https
    - port: 8089
      name: http
    - port: 8090
      name: https
  selector:
    statefulset.kubernetes.io/pod-name: fid-0
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fid
  labels:
    kubernetes.io/os: linux
spec:
  selector:
    matchLabels:
      app: fid # has to match .spec.template.metadata.labels
  serviceName: "fid"
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fid # has to match .spec.selector.matchLabels
      annotations:
        traffic.sidecar.istio.io/excludeOutboundPorts: 443,8090,7171
        traffic.sidecar.istio.io/excludeInboundPorts: 7171,8090,2636
    spec:
      terminationGracePeriodSeconds: 120
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: sysctl
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
            [
              "/bin/sh",
              "-c",
              "sysctl -w vm.max_map_count=262144 && set -e && ulimit -n 65536",
            ]
          securityContext:
            privileged: true
      containers:
        - name: fid
          image: image
          imagePullPolicy: Always
          lifecycle:
            postStart:
              exec:
                command:
                  [
                    "/bin/sh",
                    "-c",
                    "echo Hello from the fid postStart handler > /opt/radiantone/vds/lifecycle.txt",
                  ]
            preStop:
              exec:
                #              command: ["/opt/radiantone/vds/bin/advanced/cluster.sh","detach"]
                command: ["/opt/radiantone/vds/bin/stopVDSServer.sh"]
          ports:
            - containerPort: 2181
              name: zk-client
            - containerPort: 7070
              name: cp-http
            - containerPort: 7171
              name: cp-https
            - containerPort: 9100
              name: admin-http
            - containerPort: 9101
              name: admin-https
            - containerPort: 2389
              name: ldap
            - containerPort: 2636
              name: ldaps
            - containerPort: 8089
              name: http
            - containerPort: 8090
              name: https
          readinessProbe:
            tcpSocket:
              port: 2389
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 5
            successThreshold: 1
          livenessProbe:
            tcpSocket:
              port: 9100
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 5
            successThreshold: 1
          envFrom:
            - configMapRef:
                name: fid-environment-variables
          env:
            - name: ZK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fidrootcreds
                  key: password
          volumeMounts:
            - name: r1-pvc
              mountPath: /opt/radiantone/vds
          resources:
            limits:
              cpu: "4"
              memory: 8Gi
            requests:
              cpu: "2"
              memory: 4Gi
          command: ["/bin/sh", "-c"]
          args:
            [
              "if [ $HOSTNAME != fid-0 ]; then export CLUSTER=join; fi;./run.sh fg",
            ]
      nodeSelector:
        kubernetes.io/os: linux        
      volumes:
      - name: r1-pvc
        emptyDir: {}

```

The curl returns the following 
```
curl -v -k ldaps://<host>:636
*   Trying 34.218.138.57:636...
* Connected to fid.opcl.net (34.218.138.57) port 636 (#0)
* LDAP local: LDAP Vendor = Microsoft Corporation. ; LDAP Version = 510
* LDAP local: ldaps://fid.opcl.net:636/
* LDAP local: trying to establish encrypted connection
* LDAP local: bind via ldap_win_bind Server Down
* Closing connection 0
curl: (38) LDAP local: bind via ldap_win_bind Server Down

```

Am I missing anything? Any help is appreciated
