### ISSUE TITLE
the pod doesn't run in remote cluster when using 'Install Istio with an External Control Plane' plan

### ISSUE THREAD

**Issue by suwliang3** [istio/istio#39691]
Pre-instructions:My K8s cluster doesn't support LoadBalancer

```
istioctl version 1.12.6

kubectl version 1.21.5

```

1、Set up a gateway in the external cluster
```
cat <<EOF > controlplane-gateway.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          service:
            ports:
              - port: 15021
                targetPort: 15021
                name: status-port
              - port: 15012
                targetPort: 15012
                name: tls-xds
              - port: 15017
                targetPort: 15017
                name: tls-webhook
EOF
```

the `istio-ingressgateway` in external cluster :
```
[root@vm1-su-001 istio-1.12.6]# kubectl get svc -n istio-system 
NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                                           AGE
istio-ingressgateway   NodePort    10.233.44.128   <none>        15021:31222/TCP,15012:30956/TCP,15017:31263/TCP   142m
istiod                 ClusterIP   10.233.25.55    <none>        15010/TCP,15012/TCP,443/TCP,15014/TCP             142m
```
2、`export EXTERNAL_ISTIOD_ADDR=external.sample.com`  configure `external.sample.com  100.76.x.x ` in /etc/hosts,100.76.x.x is node's IP.
3、`export SSL_SECRET_NAME=external-credential`   `external-credential` is configured by `kubectl create -n istio-system secret tls external-credential --key=external.sample.com.key --cert=external.sample.com.crt` like [https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/](url)
4、Set up the remote config cluster
```
cat <<EOF > remote-config-cluster.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: external-istiod
spec:
  profile: external
  values:
    global:
      istioNamespace: external-istiod
      configCluster: true
    pilot:
      configMap: true
    istiodRemote:
      injectionURL: https://external.sample.com:31263/inject/:ENV:cluster=cluster1:ENV:net=network1
    base:
      validationURL: https://external.sample.com:31263/validate
EOF

```
the port '31263' is nodePort of istio-ingressgateway
5、Set up the control plane in the external cluster
```
cat <<EOF > external-istiod.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: external-istiod
spec:
  profile: empty
  meshConfig:
    rootNamespace: external-istiod
    defaultConfig:
      discoveryAddress: external.sample.com:30956
      proxyMetadata:
        XDS_ROOT_CA: /etc/ssl/certs/ca-certificates.crt
        CA_ROOT_CA: /etc/ssl/certs/ca-certificates.crt
  components:
    pilot:
      enabled: true
      k8s:
        overlays:
        - kind: Deployment
          name: istiod
          patches:
          - path: spec.template.spec.volumes[100]
            value: |-
              name: config-volume
              configMap:
                name: istio
          - path: spec.template.spec.volumes[100]
            value: |-
              name: inject-volume
              configMap:
                name: istio-sidecar-injector
          - path: spec.template.spec.containers[0].volumeMounts[100]
            value: |-
              name: config-volume
              mountPath: /etc/istio/config
          - path: spec.template.spec.containers[0].volumeMounts[100]
            value: |-
              name: inject-volume
              mountPath: /var/lib/istio/inject
        env:
        - name: INJECTION_WEBHOOK_CONFIG_NAME
          value: ""
        - name: VALIDATION_WEBHOOK_CONFIG_NAME
          value: ""
        - name: EXTERNAL_ISTIOD
          value: "true"
        - name: CLUSTER_ID
          value: cluster1
        - name: SHARED_MESH_CONFIG
          value: istio
  values:
    global:
      caAddress: external.sample.com:30956
      istioNamespace: external-istiod
      operatorManageWebhooks: true
      configValidation: false
      meshID: mesh1
EOF
```
6、Create the Istio Gateway, VirtualService, and DestinationRule configuration

```
cat <<EOF > external-istiod-gw.yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: external-istiod-gw
  namespace: external-istiod
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 15012
        protocol: https
        name: https-XDS
      tls:
        mode: SIMPLE
        credentialName: external-credential
      hosts:
      - external.sample.com
    - port:
        number: 15017
        protocol: https
        name: https-WEBHOOK
      tls:
        mode: SIMPLE
        credentialName: external-credential
      hosts:
      - external.sample.com
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
   name: external-istiod-vs
   namespace: external-istiod
spec:
    hosts:
    - external.sample.com
    gateways:
    - external-istiod-gw
    http:
    - match:
      - port: 15012
      route:
      - destination:
          host: istiod.external-istiod.svc.cluster.local
          port:
            number: 15012
    - match:
      - port: 15017
      route:
      - destination:
          host: istiod.external-istiod.svc.cluster.local
          port:
            number: 443
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: external-istiod-dr
  namespace: external-istiod
spec:
  host: istiod.external-istiod.svc.cluster.local
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 15012
      tls:
        mode: SIMPLE
      connectionPool:
        http:
          h2UpgradePolicy: UPGRADE
    - port:
        number: 443
      tls:
        mode: SIMPLE
EOF

```
Finally，deploy sleep application in remote cluster 
```
kubectl create  namespace sample
kubectl label  namespace sample istio-injection=enabled
kubectl apply -f [samples/sleep/sleep.yaml](https://raw.githubusercontent.com/istio/istio/release-1.14/samples/sleep/sleep.yaml) -n sample
```
but, the pod is not running:
```
[root@vm1-su-001 istio-1.12.6]# kubectl get po -n sample
No resources found in sample namespace.
```
```
[root@vm1-su-001 istio-1.12.6]# kubectl get event -n sample
LAST SEEN   TYPE      REASON              OBJECT                        MESSAGE
5s          Warning   FailedCreate        replicaset/sleep-557747455f   Error creating: Internal error occurred: failed calling webhook "namespace.sidecar-injector.istio.io": Post "https://external.sample.com:31263/inject/:ENV:cluster=cluster1:ENV:net=network1?timeout=10s": context deadline exceeded
15s         Normal    ScalingReplicaSet   deployment/sleep              Scaled up replica set sleep-557747455f to 1
```
