### ISSUE TITLE
Implement stateful session affinity to a backend

### ISSUE THREAD

**Issue by sanjaypujare** [istio/istio#39740]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
In stateful services, once a particular "session" is assigned by a load-balancer to a particular service backend, all future activity on that session must be routed to the same service backend. 

Envoy has recently added stateful session affinity extension through the use of cookies that store the “mapping state” and enables the extension to override the load-balancing decision if such state information is available. The way this would work is the application (client) would send the first request in a session without the cookie. Proxyless gRPC or client side Envoy would include a Cookie in the response and the client would use that Cookie value in all the subsequent requests in that session. Proxyless gRPC or Envoy will use the Cookie to route the request as described above.

The Envoy feature is enabled through the use of a custom HttpFilter. It seems Istio will not send this filter to proxyless gRPC because of its internal logic. So we will need 

- to fix the above limitation so one is able to use that custom filter for proxyless gRPC workloads as well
- come up with a "first-class" API or configuration to support stateful session affinity (most likely using the Cookie based mechanism described above) 

**Describe alternatives you've considered**
Consistent hash based load balancing has the issue that any time the set of backend servers changes (hosts are removed or added), the hash mapping of 1/N client sessions gets affected which would lead to dropped requests in case of stateful services.

**Affected product area (please put an X in all that apply)**

[X] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[X] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[X] Virtual Machine
[X] Multi Control Plane

**Additional context**
This issue https://github.com/istio/istio/issues/38822  is about cluster affinity but we need host affinity.

gRPC issue about the same feature: https://github.com/grpc/grpc/issues/30171

Envoy implementation related refs:
https://github.com/envoyproxy/envoy/issues/16698
https://github.com/envoyproxy/envoy/pull/17848
https://github.com/envoyproxy/envoy/pull/18207

Protos:
https://github.com/envoyproxy/envoy/blob/main/api/envoy/extensions/filters/http/stateful_session/v3/stateful_session.proto
https://github.com/envoyproxy/envoy/blob/main/api/envoy/extensions/http/stateful_session/cookie/v3/cookie.proto

Doc:
https://docs.google.com/document/d/1IU4b76AgOXijNa4sew1gfBfSiOMbZNiEt5Dhis8QpYg/edit#

**Comment by sanjaypujare** [comment]
CC @louiscryan @costinm

**Comment by sanjaypujare** [comment]
@louiscryan @costinm gentle reminder about this issue: how soon can this be done?

**Comment by costinm** [comment]
https://github.com/istio/api/pull/2434 is a good example for adding a new load balancing option. 

@sanjaypujare - if you can start a PR following the same pattern with the options we need, it would be the best way to jumpstart the process.

**Comment by ramaraochavali** [comment]
I think so. @sanjaypujare WDYT?

**Comment by sanjaypujare** [comment]
> I think so. @sanjaypujare WDYT?

Hmmm, I don't think this request has been addressed unless I am missing something.

- https://github.com/istio/istio/pull/42840 only adds header based support
- https://github.com/istio/istio/pull/40660 adds cookie based stateful session affinity but only for proxyless gRPC and is probably an annotation/label based support instead of a proper API

So I think it is still not possible to add cookie based support for Envoy yet. Wasn't https://github.com/istio/api/pull/2469 going to do that?

**Comment by ramaraochavali** [comment]
@sanjaypujare https://github.com/istio/istio/pull/42592 added support for Envoy at both Gateway and Sidecars for cookies.

That api is not needed in near future. But we will have to document these labels

**Comment by sanjaypujare** [comment]
Okay, I took a brief look at https://github.com/istio/istio/pull/42592 and it does look like there is support for Envoy (i.e. regular Listeners and not just ApiListeners).

This issue talks about 'coming up with a "first-class" API or configuration to support stateful session affinity' and I believe we still don't have that but I am okay to close this

**Comment by va7ish** [comment]
I agree with @sanjaypujare. This issue was opened to add native support for stateful session affinity configuration. AFAIK right-now this is only possible through a set of annotations on a service.

**Comment by sanjaypujare** [comment]
@ramaraochavali wouldn't https://github.com/istio/api/pull/2469 properly resolve this issue? Is it possible to push to get that one merged?

**Comment by ramaraochavali** [comment]
> Okay, I took a brief look at https://github.com/istio/istio/pull/42592 and it does look like there is support for Envoy (i.e. regular Listeners and not just ApiListeners).

It is supported for regular listeners also

> @ramaraochavali wouldn't https://github.com/istio/api/pull/2469 properly resolve this issue? Is it possible to push to get that one merged?

Yes. I am happy to get that merged. But there is no consensus on API. That is why we landed with these label based approach.

cc: @costinm 

I am fine to keep this open till we have a stable API.

**Comment by sanjaypujare** [comment]
> > Okay, I took a brief look at #42592 and it does look like there is support for Envoy (i.e. regular Listeners and not just ApiListeners).
> 
> It is supported for regular listeners also

Yes that's what I said too.

> 
> > @ramaraochavali wouldn't [istio/api#2469](https://github.com/istio/api/pull/2469) properly resolve this issue? Is it possible to push to get that one merged?
> 
> Yes. I am happy to get that merged. But there is no consensus on API.

Can we try to achieve consensus? May be address the concerns raised there so we can get that merged?


> 
> cc: @costinm
> 
> I am fine to keep this open till we have a stable API.

Yes, but we should have someone working on resolving this issue.

**Comment by arhamGH** [comment]
I am also looking for a fix for this 😞

**Comment by ramaraochavali** [comment]
@arhamGH Can you please try with service labels https://github.com/istio/istio/pull/42592 and https://github.com/istio/istio/pull/42840 and see if it helps? I understand API is important but we can try without that

**Comment by costinm** [comment]
The API is discussed in the K8S Gateway API WG - we will adopt any CRD or
config that is agreed upon with other vendors.

Meanwhile - for 1.18 we should discuss if we can turn the label on by
default for envoy ( it is on by default for proxyless ).
The main reason (besides 'new feature') was that the users with EnvoyFilter
may be impacted - if we can add some checks to
avoid duplication I think we could have it on by default, and be prepared
for the proper API from K8S.

The other still pending issue is draining - I think there are some concerns
on how it works and if it properly detects the state,
as well as tight coupling with K8S ( VMs or other environments acting as
servers will have problems ). I am looking for a more
flexible solution that will also work for other gateway implementations and
in other environments.

**Comment by gabrielsadaka** [comment]
@ramaraochavali thanks for your work on this. Did these changes make it into the 1.17 release? Could you please provide a quick example of how to implement this feature using the service labels?

I am new to Istio and am not sure how to implement this after reading the PR.

**Comment by ramaraochavali** [comment]
Yes those changes are available in 1.17

if you want a cookie based session stickiness you need to set `istio.io/persistent-session` label on the service with value as name of the cookie you want
if you want a header based session stickiness you need to set `istio.io/persistent-session-header` label on the service with the header name as the teh value.

**Comment by arjun-beathi** [comment]
> Yes those changes are available in 1.17
> 
> if you want a cookie based session stickiness you need to set `istio.io/persistent-session` label on the service with value as name of the cookie you want if you want a header based session stickiness you need to set `istio.io/persistent-session-header` label on the service with the header name as the teh value.

When you say service, do you mean k8s service or in pod definition?

**Comment by va7ish** [comment]
@arjun-beathi these labels need to be set on the actual K8s Service object.

**Comment by keithmattix** [comment]
Can we get some documentation on the existing label approach? I'm not even seeing the annotations above listed on the annotations [page](https://istio.io/latest/docs/reference/config/annotations/)

**Comment by pbusko** [comment]
@ramaraochavali  do I need to make some changes in advance? Setting the `istio.io/persistent-session` label on K8s service did nothing in my case :(

**Comment by ramaraochavali** [comment]
Did you enable `PILOT_ENABLE_PERSISTENT_SESSION_FILTER` in pilot?

**Comment by pbusko** [comment]
> Did you enable `PILOT_ENABLE_PERSISTENT_SESSION_FILTER` in pilot?

@ramaraochavali Here's a piece of the `IstioOperator` config I am using:

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: installed-state-default-operator
  namespace: istio-system
spec:
  components:
...
    ingressGateways:
      - enabled: true
        name: istio-ingressgateway
    pilot:
      enabled: true
      k8s:
        env:
        - name: PILOT_ENABLE_PERSISTENT_SESSION_FILTER
          value: "1"
...
```

Gateway:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-gateway
  namespace: istio-system
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  servers:
  - hosts:
    - '*.example.com'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      cipherSuites:
      - ECDHE-RSA-CHACHA20-POLY1305
      - ECDHE-RSA-AES256-GCM-SHA384
      - ECDHE-RSA-AES256-SHA
      - ECDHE-RSA-AES128-GCM-SHA256
      - ECDHE-RSA-AES128-SHA
      credentialName: gateway-certs
      minProtocolVersion: TLSV1_2
      mode: SIMPLE
  - hosts:
    - '*.example.com'
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
```
Service:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: sticky-app
  labels:
    istio.io/persistent-session: somecookie
  namespace: sticky-sessions
spec:
  selector:
    app: sticky-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http
      appProtocol: http
```

The cookie is set only when a request is initiated internally using the service name (like `curl http://sticky-app.sticky-sessions:3000`):
However, when I have a `VirtualService` with the Gateways configuration, the cookie is not set when the request is coming from the outside through the Istio Ingress Gateway. Is this the expected behaviour or did I misconfigured anything?
