### ISSUE TITLE
istio b3 tracing headers are not being generated

### ISSUE THREAD

**Issue by vamsidvk09** [istio/istio#39779]
### Bug Description

Installed istio 1.13.2 on GKE v1.22.8-gke.202 using istioctl and operator manifest in order to override the default profile configuration.

We're observing that b3-* headers are not getting generated for single hop communication for ex: client (curl) --> GCP Load balancer --> ingress-gateway--> Service A  ---> (response) curl 

where as if there is any service involved in between then  b3-* headers are part of response headers. 
Ex: client (curl) --> GCP Load balancer --> ingress-gateway--> Service A  ---> Service B ---> (response) curl 

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-operator
spec:
  profile: default
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 100
        max_path_tag_length: 256
        datadog:
           address: $(HOST_IP):8126
        zipkin:
          address: zipkin.istio-system:9411
  components:
    ingressGateways:
  addonComponents:
    prometheus:
      enabled: false
    kiali:
      enabled: false
    grafana:
      enabled: false
    tracing:
      enabled: false
    istiocoredns:
      enabled: false
  values:
    sidecarInjectorWebhook:
      injectedAnnotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    global:
      proxy:
        image: proxyv2
        clusterDomain: "cluster.local"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
        logLevel: warning
        componentLogLevel: "misc:error"
        privileged: false
        enableCoreDump: false
        statusPort: 15020
        readinessInitialDelaySeconds: 1
        readinessPeriodSeconds: 2
        readinessFailureThreshold: 30
        includeIPRanges: "*"
        excludeIPRanges: ""
        excludeOutboundPorts: ""
        excludeInboundPorts: ""
        autoInject: enabled
        tracer: "zipkin"
        holdApplicationUntilProxyStarts: true
```

### Version

```prose
$ istioctl version
client version: 1.13.2
control plane version: 1.13.2
data plane version: 1.13.2 (8 proxies)

kubectl version --short
Client Version: v1.21.4
Server Version: v1.22.8-gke.202
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
