### ISSUE TITLE
Istio issues with cert-manager, vault and cert-manager-istio-csr

### ISSUE THREAD

**Issue by SoulKyu** [istio/istio#39808]
### Bug Description

Hello, 

I'v setting up an istio configuration with those parameters : 

Created self-signed ROOT-CA on Vault.
CN=istio.internal
Created 1 intermediate CA on Vault. 
CN=istio.internal
allowed_domains=["istio.internal"]

Created cert-manager and configured vault as an issuer.
Everything is working on this side : 
k get issuers.cert-manager.io -o wide
NAME                       READY   STATUS           AGE
vault-istio-admin-issuer   True    Vault verified   5h41m

Installing cert-manager-istio-csr : 
cert-manager-istio-csr-c8ccdf96d-26mft     1/1     Running   0          41m

k get certificate
NAME     READY   SECRET       AGE
istiod   True    istiod-tls   5h41m

Trying to starting an istio with istioctl : 
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: "demo"
  values:
    global:
      meshID: mesh-admin
      multiCluster:
        clusterName: cluster-admin
      network: network-admin
      caAddress: cert-manager-istio-csr.cert-manager.svc:443
  components:
    pilot:
      k8s:
        env:
          # Disable istiod CA Sever functionality
        - name: ENABLE_CA_SERVER
          value: "false"
        overlays:
        - apiVersion: apps/v1
          kind: Deployment
          name: istiod
          patches:

            # Mount istiod serving and webhook certificate from Secret mount
          - path: spec.template.spec.containers.[name:discovery].args[7]
            value: "--tlsCertFile=/etc/cert-manager/tls/tls.crt"
          - path: spec.template.spec.containers.[name:discovery].args[8]
            value: "--tlsKeyFile=/etc/cert-manager/tls/tls.key"
          - path: spec.template.spec.containers.[name:discovery].args[9]
            value: "--caCertFile=/etc/cert-manager/tls/ca.crt"

          - path: spec.template.spec.containers.[name:discovery].volumeMounts[6]
            value:
              name: cert-manager
              mountPath: "/etc/cert-manager/tls"
              readOnly: true
          - path: spec.template.spec.containers.[name:discovery].volumeMounts[7]
            value:
              name: ca-root-cert
              mountPath: "/etc/cert-manager/ca"
              readOnly: true

          - path: spec.template.spec.volumes[6]
            value:
              name: cert-manager
              secret:
                secretName: istiod-tls
          - path: spec.template.spec.volumes[7]
            value:
              name: ca-root-cert
              configMap:
                defaultMode: 420
                name: istio-ca-root-cert
```

istioctl install -f cluster-admin.yaml --set meshConfig.trustDomain=istio.internal
This will install the Istio 1.14.1 default profile with ["Istio core" "Istiod" "Ingress gateways"] components into the cluster. Proceed? (y/N) y
✔ Istio core installed
✔ Istiod installed
✘ Ingress gateways encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the condition
  Deployment/istio-system/istio-ingressgateway (containers with unready status: [istio-proxy])
- Pruning removed resources
Error: failed to install manifests: errors occurred during operation

The istiod pod start well, but i got issue with istio-proxy : 
```
2022-07-06T15:01:33.925544Z     warn    ca      ca request failed, starting attempt 1 in 101.943628ms
2022-07-06T15:01:34.027967Z     warn    ca      ca request failed, starting attempt 2 in 205.704512ms
2022-07-06T15:01:34.234417Z     warn    ca      ca request failed, starting attempt 3 in 417.770519ms
2022-07-06T15:01:34.653351Z     warn    ca      ca request failed, starting attempt 4 in 759.414808ms
2022-07-06T15:01:35.413444Z     warn    sds     failed to warm certificate: failed to generate workload certificate: create certificate: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"istio.internal\")"
2022-07-06T15:01:43.394960Z     warning envoy config    StreamAggregatedResources gRPC config stream closed since 740s ago: 14, connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"istio.internal\")"
2022-07-06T15:02:02.019782Z     warning envoy config    StreamAggregatedResources gRPC config stream closed since 759s ago: 14, connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"istio.internal\")"
2022-07-06T15:02:19.711247Z     warning envoy config    StreamAggregatedResources gRPC config stream closed since 776s ago: 14, connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"istio.internal\")"
```

I have checked my certs with : https://istio.io/latest/docs/ops/common-problems/injection/#x509-certificate-related-errors but they both give the same MD5SUM.

Did you know what i miss or if its a bug ?

### Version

```prose
istioctl version
client version: 1.14.1
control plane version: 1.14.1
data plane version: none
kubectl version --short
Client Version: v1.22.0
Server Version: v1.22.9-eks-a64ea69
helm version --short
v3.9.0+g7ceeda6
```

### Additional Information
```
k get secrets
NAME                                               TYPE                                  DATA   AGE
default-token-kdqrc                                kubernetes.io/service-account-token   3      26h
istio-egressgateway-service-account-token-hbkxd    kubernetes.io/service-account-token   3      15m
istio-ingressgateway-service-account-token-k6kb9   kubernetes.io/service-account-token   3      15m
istio-reader-service-account-token-tgbct           kubernetes.io/service-account-token   3      15m
istiod-ca-pem                                      Opaque                                3      178m
istiod-service-account-token-l957d                 kubernetes.io/service-account-token   3      15m
istiod-tls                                         kubernetes.io/tls                     3      6h
istiod-token-h7k7g                                 kubernetes.io/service-account-token   3      15m
vault-issuer                                       kubernetes.io/service-account-token   3      26h
vault-issuer-approle                               Opaque                                1      23h
vault-issuer-token-dhnrn                           kubernetes.io/service-account-token   3      26h
```
```
k get cm
NAME                              DATA   AGE
istio                             2      15m
istio-ca-root-cert                1      69m
istio-csr                         0      23h
istio-gateway-deployment-leader   0      3h16m
istio-gateway-status-leader       0      3h16m
istio-leader                      0      3h16m
istio-sidecar-injector            2      15m
kube-root-ca.crt                  1      26h
```
```
k get validatingwebhookconfigurations.admissionregistration.k8s.io
NAME                                               WEBHOOKS   AGE
admin-admission                                    1          167d
aws-load-balancer-webhook                          2          167d
istio-validator-istio-system                       1          15m
nginx-ingress-controller-ingress-nginx-admission   1          167d
validation.webhook.config.karpenter.sh             1          84d
validation.webhook.provisioners.karpenter.sh       1          84d
vpc-resource-validating-webhook                    2          168d
```
```
k get mutatingwebhookconfigurations.admissionregistration.k8s.io
NAME                                           WEBHOOKS   AGE
admin-admission                                1          167d
aws-load-balancer-webhook                      2          167d
defaulting.webhook.provisioners.karpenter.sh   1          84d
istio-sidecar-injector                         4          15m
pod-identity-webhook                           1          168d
vpc-resource-mutating-webhook                  1          168d
```
