### ISSUE TITLE
Bug: Host Match Policies

### ISSUE THREAD

**Issue by ade90036** [istio/istio#39810]
### Bug Description

I was testing some host name policies. 

We are trying to match a number of environments based on what we currently have:

- dev
- dev2
- test

We have a ingress-gateway that would then filter certain request from the host name

- dev.example.int
- dev2.example.int
- test.example.int

The following works, SUCCESS

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: core-allow-policy
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  action: ALLOW
  rules:
     - to:
        - operation:
            hosts: [
              "*.example.int",
            ]

```
But if we also want add hosts which use a port, for example in microk8s and minikube can't bind ports to 443, or 80, therefore we need to specify a port. 

- dev.example.int:39954
- dev2.example.int:38567
- test.example.int:35467

then if we create a policy to capture both scenarios like this

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: core-allow-policy
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  action: ALLOW
  rules:
     - to:
        - operation:
            hosts: [
              "*.example.int",
              "*.example.int:*",
            ]

```

Lets say we are testing this URL: http://dev.example.int:39954 
This policy fails to evaluate correctly... 

if i change the policy to this:
```
     - to:
        - operation:
            hosts: [
              "*.example.int",
              "dev.example.int:*",
            ]
```

It works!!

So the issue seems when you have a wild-characted at the beginnign and one at the end. 

### Version

```prose
client version: 1.13.3
control plane version: 1.13.3
data plane version: 1.13.3 (5 proxies)
```
