### ISSUE TITLE
Issue with tcp traffic to "widcard" hosts. Traffic sent only to first host in list

### ISSUE THREAD

**Issue by iocn-2-3-4** [istio/istio#39811]
### Bug Description

We have Gateway:
```apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  annotations:
    meta.helm.sh/release-name: tidal-infra
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
  name: ingressgateway
  namespace: istio-system
spec:
  selector:
    app: istio-ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - '*'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: ingress-cert
      mode: SIMPLE
  - hosts:
    - '*'
    port:
      name: tcp
      number: 5591
      protocol: TCP
```
and 3 virtualservices:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  annotations:
    meta.helm.sh/release-name: release
    meta.helm.sh/release-namespace: ns1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: ingress
  namespace: ns1
spec:
  gateways:
  - istio-system/ingressgateway
  hosts:
  - ns1.example.com
  http:
  - match:
    - uri:
        exact: /connect-server
    name: tcs
    route:
    - destination:
        host: app1
        port:
          number: 4444
  - match:
    - uri:
        prefix: /
    name: cm
    route:
    - destination:
        host: app2
        port:
          number: 8080
  tcp:
  - match:
    - port: 5591
    route:
    - destination:
        host: app1
        port:
          number: 5591
```
______
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  annotations:
    meta.helm.sh/release-name: release
    meta.helm.sh/release-namespace: ns2
  labels:
    app.kubernetes.io/managed-by: Helm
  name: ingress
  namespace: ns2
spec:
  gateways:
  - istio-system/ingressgateway
  hosts:
  - ns2.example.com
  http:
  - match:
    - uri:
        exact: /connect-server
    name: tcs
    route:
    - destination:
        host: app1
        port:
          number: 4444
  - match:
    - uri:
        prefix: /
    name: cm
    route:
    - destination:
        host: app2
        port:
          number: 8080
  tcp:
  - match:
    - port: 5591
    route:
    - destination:
        host: app1
        port:
          number: 5591
```
________
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  annotations:
    meta.helm.sh/release-name: release
    meta.helm.sh/release-namespace: ns3
  labels:
    app.kubernetes.io/managed-by: Helm
  name: ingress
  namespace: ns3
spec:
  gateways:
  - istio-system/ingressgateway
  hosts:
  - ns3.example.com
  http:
  - match:
    - uri:
        exact: /connect-server
    name: tcs
    route:
    - destination:
        host: app1
        port:
          number: 4444
  - match:
    - uri:
        prefix: /
    name: cm
    route:
    - destination:
        host: app2
        port:
          number: 8080
  tcp:
  - match:
    - port: 5591
    route:
    - destination:
        host: app1
        port:
          number: 5591
```
But TCP connection only establishes with virtual service in ns1
if we set list of hosts directly in gateway
```

  - hosts:
    - ns1.example.com
    - ns2.example.com
    - ns3.example.com
    port:
      name: tcp
      number: 5591
      protocol: TCP
```
we get same result, connection can be established only with - ns1.example.com on TCP port 5591
if remove - ns1.example.com from list, connection can be established only with - ns2.example.com on TCP port 5591
So, seems it takes first host from list in any case: wildcard or list of hosts
Even not first host in list, but first alphabetically
Also works fine, if we change port in virtualservices for TCP connection:
```
  tcp:
  - match:
    - port: 5591
    route:
    - destination:
        host: app1
        port:
          number: 5591
```
For example if we want to test ns3.example com, we remain in it's virtualservice port 5591 and change it for ns2 and ns1
Than connection succesfully establishes with ns3 port 5591
Is this expected behaviour?

### Version

```prose
istioctl version
client version: 1.14.1
control plane version: 1.13.3
data plane version: 1.13.3 (1 proxies)
___________________________
 kubectl version --short
Client Version: v1.21.6+2.el8
Server Version: v1.22.5
___________________________
helm version --short
v3.6.3+g809dabc
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
