### ISSUE TITLE
excludeOutboundIPRanges can't able to establish communication between init container and application on a pod

### ISSUE THREAD

**Issue by mohammadsuha** [istio/istio#39826]
I have an application-A deployed in a pod and ISTIO strict mode is ON on that pod.

now i have main application which connect to application-A from the init-container of main application on which ISTIO strict mode is also ON ,but it cant able to connect to application-A using curl command from init-container.
 
I was able to connect to the application-A from init-container of main application when ISTIO strict mode is OFF.

i have explored on google and found 3 ways to enable communication in following documentation

https://istio.io/latest/docs/setup/additional-setup/cni/#compatibility-with-application-init-containers

according to that i have added "excludeOutboundIPRanges : 0.0.0.0/0" in my deployment yaml file.
as below
````
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeOutboundIPRanges: 0.0.0.0/0
````
im accesing the application-A running in a pod using <service-name>:80.

by adding excludeOutboundIPRanges also i cant able to access the application-A using curl command in init-container of main application.

can i know what im doing wrong and how should i connect to other application using curl command from init container?

note: im using istio-init and not using istio-cni.
