### ISSUE TITLE
IstioOperator overlays are broken when using revisions

### ISSUE THREAD

**Issue by zioproto** [istio/istio#39835]
### Bug Description

I want to use a `istioOperator` overlay to patch the `istiod` Deployment, because I want to read the `cacerts` using a csi driver instead of using Kubernetes secrets. I am also using revisioned control plane.
I found this issue where the overlay fails to apply because of the revision. Here is my install command:

```
istioctl install \
  --context=westeurope-aks \
  --set profile=minimal \
  --revision=1-14-1 \
  --set tag=1.14.1 \
   -f overlay.yaml
```

This is the content of overlay.yaml

```
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
 components:
   pilot:
     enabled: true
     k8s:
       overlays:
         - kind: Deployment
           name: istiod
           patches:
             - path: spec.template.spec.volumes[name:cacerts]
               value:
                 name: cacerts
                 csi:
                   driver: secrets-store.csi.k8s.io
                   readOnly: true
                   volumeAttributes:
                     secretProviderClass: "istio-tls"
```

This will fail with the following error:

```
Error: failed to install manifests: errors occurred during operation: overlay for Deployment:istiod does not match any object in output manifest. Available objects are:
HorizontalPodAutoscaler:istio-system:istiod-1-14-1
ClusterRole::istiod-clusterrole-1-14-1-istio-system
ClusterRole::istiod-gateway-controller-1-14-1-istio-system
ClusterRoleBinding::istiod-clusterrole-1-14-1-istio-system
ClusterRoleBinding::istiod-gateway-controller-1-14-1-istio-system
ConfigMap:istio-system:istio-1-14-1
Deployment:istio-system:istiod-1-14-1
ConfigMap:istio-system:istio-sidecar-injector-1-14-1
MutatingWebhookConfiguration::istio-sidecar-injector-1-14-1
PodDisruptionBudget:istio-system:istiod-1-14-1
ClusterRole::istio-reader-clusterrole-1-14-1-istio-system
ClusterRoleBinding::istio-reader-clusterrole-1-14-1-istio-system
Role:istio-system:istiod-1-14-1
RoleBinding:istio-system:istiod-1-14-1
Service:istio-system:istiod-1-14-1
ServiceAccount:istio-system:istiod-1-14-1
EnvoyFilter:istio-system:stats-filter-1.11-1-14-1
EnvoyFilter:istio-system:tcp-stats-filter-1.11-1-14-1
EnvoyFilter:istio-system:stats-filter-1.12-1-14-1
EnvoyFilter:istio-system:tcp-stats-filter-1.12-1-14-1
EnvoyFilter:istio-system:stats-filter-1.13-1-14-1
EnvoyFilter:istio-system:tcp-stats-filter-1.13-1-14-1
EnvoyFilter:istio-system:stats-filter-1.14-1-14-1
EnvoyFilter:istio-system:tcp-stats-filter-1.14-1-14-1
EnvoyFilter:istio-system:stats-filter-1.15-1-14-1
EnvoyFilter:istio-system:tcp-stats-filter-1.15-1-14-1
ValidatingWebhookConfiguration::istio-validator-1-14-1-istio-system
```

If I add manually the revision string to the deployment name everything works.
Here is the working overlay file:

```
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
 components:
   pilot:
     enabled: true
     k8s:
       overlays:
         - kind: Deployment
           name: istiod-1-14-1 
           patches:
             - path: spec.template.spec.volumes[name:cacerts]
               value:
                 name: cacerts
                 csi:
                   driver: secrets-store.csi.k8s.io
                   readOnly: true
                   volumeAttributes:
                     secretProviderClass: "istio-tls"
```

This is clearly a bug because the overlay file should not include the revision string, that is passed as an argument in the istioctl command line: `--revision=1-14-1`.

### Version

```prose
% istioctl version
client version: 1.14.1
control plane version: 1.14.1
data plane version: 1.14.1 (1 proxies)

% kubectl version --short
Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.23.5
```

### Additional Information

This should be the same issue as https://github.com/istio/istio/issues/31076

**Comment by radekg** [comment]
This isn't a bug, your `IstioOperator` manifest is not configured correctly. You need to change `spec.components.pilot.k8s.overlays[0].name`, which you already found out about.

Don't you do need that revision in the overlay deployment because if you proceed with an upgrade with canary, you'll essentially have a deployment per revision?

**Comment by zioproto** [comment]
I am lost. I am passing the revision already in the istioctl command with --revision

Please would it be possible to have a full example of the correct IstioOperator yaml file ?

Thanks

**Comment by radekg** [comment]
It’s what you’ve done here:

```yaml
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
 components:
   pilot:
     enabled: true
     k8s:
       overlays:
         - kind: Deployment
           name: istiod-1-14-1 
           patches:
             - path: spec.template.spec.volumes[name:cacerts]
               value:
                 name: cacerts
                 csi:
                   driver: secrets-store.csi.k8s.io
                   readOnly: true
                   volumeAttributes:
                     secretProviderClass: "istio-tls"
```

with the `istioctl manifest generate -f …` you’re telling istioctl: here’s my `IstioOperator`, go and merge that into generated msnifests.

So, if you generate for revision `1-14-1`, just make sure you reference `istiod-1-14-1` under `spec.components.pilot.k8s.overlays[0].name`. If you were to generate for `1-13-5`, you’d set that value to `istiod-1-13-5`.

My istio operator manifest looks like this:

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
  namespace: istio-system
spec:
  profile: "demo"
  revision: 1-13-5
  tag: 1.13.5
  components:
    pilot:
      k8s:
        overlays:
        - apiVersion: apps/v1
          kind: Deployment
          name: istiod-1-13-5
```

and I generate manifests like this: `istioctl-1.13.5 manifest generate -f istio-operator-1.13.5.yaml`.

Here’s a full example: https://gruchalski.com/posts/2022-06-19-istio-canary-upgrades/.
