### ISSUE TITLE
skywalking tracing not available with istio

### ISSUE THREAD

**Issue by stevenlii** [istio/istio#39838]
I have configed the same configuration follow 
But there is not trace disappeared

```
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      envoyAccessLogService:
        address: skywalking-oap.skywalking.svc.cluster.local:11800
      envoyMetricsService:
        address: skywalking-oap.skywalking.svc.cluster.local:11800
      proxyMetadata: {}
      proxyStatsMatcher:
        inclusionRegexps:
        - .*
    enableEnvoyAccessLogService: true
    enablePrometheusMerge: true
    extensionProviders:
    - skywalking:
        service: skywalking-oap.skywalking.svc.cluster.local
        port: 11800
      name: envoy.tracers.skywalking
  profile: demo
  tag: 1.11.5
```
`kubectl apply -f installed-state.yaml
`
then add Telemetry cr
```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: test
spec:
  tracing:
  - customTags:
      my_new_foo_tag:
        literal:
          value: foo
    providers:
    - name: envoy.tracers.skywalking
    randomSamplingPercentage: 100
```
and `kubectl create -f telemetry.yaml`

and I visit bookinfo via http://ip:port/productpage
but no trace data show at skywalking ui. Even through no only one span
my trace: 
![image](https://user-images.githubusercontent.com/8954758/177983469-a37a0220-54ae-4aee-9b3d-87f5c3069140.png)

Did I miss something?
```
istioctl version
client version: 1.11.5
control plane version: 1.11.5
data plane version: 1.11.5 (33 proxies)
```
k8s version: v1.21.8
skywalking:

```
  helm install skywalking skywalking/skywalking -n skywalking \
  --set oap.image.tag=9.1.0 \
  --set oap.storageType=elasticsearch \
  --set ui.image.tag=9.1.0 \
  --set elasticsearch.imageTag=7.5.1 \
  --set oap.replicas=1 \
  --set oap.env.SW_ENVOY_METRIC_ALS_HTTP_ANALYSIS=mx-mesh \
  --set oap.env.SW_ENVOY_METRIC_ALS_TCP_ANALYSIS=mx-mesh \
  --set values.telemetry.v2.enabled=true
  --set oap.envoy.als.enabled=true
```
Here are some deployments
![image](https://user-images.githubusercontent.com/8954758/177984298-c478a8d3-18ff-49d4-819d-1f2f116c2b10.png)
