### ISSUE TITLE
statsds-to-prometheus bridge does not extract dimensions from metrics 

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#3984]
statsds-to-prometheus bridge does not extract dimensions from envoy metrics 
Having dimensioned metrics is easier to view in prometheus.

Example mapping:
```yaml
apiVersion: v1
data:
  mapping.conf: |
    mappings:
    - match: envoy\.cluster\.(.*)\.upstream_rq_time$
      match_type: regex
      name: "rq_time"
      labels:
        cluster: "$1"
    - match: envoy\.cluster\.(.*)\.upstream_rq_(\d{3}|total)$
      match_type: regex
      name: "rq_count"
      labels:
        cluster: "$1"
        status: "$2"
kind: ConfigMap
metadata:
  name: istio-mixer
  namespace: istio-system
```
