### ISSUE TITLE
Virtual service retries doesn't work if client is envoy lua filter in same K8S cluster.

### ISSUE THREAD

**Issue by sumitaneja** [istio/istio#39851]
### Bug Description

Deployment:  OKE+istio-proxy enabled for pods..

We have EnvoyFilter defined in Istio,  From this filter, Http call is made µService deployed in OKE container,

Query: how can i configure retries here.   I observed virtual service retry not kicking if call is from Envoyfilter http client.
As part of envoyfilter definition a cluster was defined to create route to µService deployment within OKE from Envoy

Here is Cluster definition as part envoyfilter

```
- applyTo: CLUSTER
      match:
        context: SIDECAR_OUTBOUND
      patch:
        operation: ADD
        value: # cluster specification
          name: "lua_cluster"
          type: STRICT_DNS
          connect_timeout: 0.5s
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: lua_cluster
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          protocol: TCP
                          address: "xxxx.svc.cluster.local"
                          port_value: 8080
```

### Version

```prose
istioctl version
client version: 1.6.0
control plane version: 1.12.1
data plane version: 1.12.1 


bash-4.2$ kubectl version --short
Client Version: v1.17.0
Server Version: v1.20.8
bash-4.2$
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
