### ISSUE TITLE
Traffic mirror does not work for external https service

### ISSUE THREAD

**Issue by DimitarPetrov** [istio/istio#39858]
### Bug Description

I have two clusters - stage and prod. I want some calls from prod to be mirrored to stage as well in order to do some validations.

# Prod Cluster

First in prod cluster I created a service entry pointing to the stage cluster's host:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: stage-cluster
  namespace: compass-system
spec:
  hosts:
  - <stage-host>
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  location: MESH_EXTERNAL
  resolution: DNS
```

Then I added the mirror field to the virtual service of the prod cluster:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app: gateway
  name: compass-gateway
  namespace: compass-system
spec:
  gateways:
  - kyma-system/kyma-gateway
  hosts:
  - <prod-host>
  http:
  - match:
    - uri:
        prefix: /tenants
    mirror:
      host: <stage-host>
      port:
        number: 443
    mirror_percent: 100
    route:
    - destination:
        host: <in-cluster-destination-fqdn>
        port:
          number: 4455
```

# Stage Cluster

First, add the shadow host to the gateway:

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: kyma-gateway
  namespace: kyma-system
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  servers:
  - hosts:
    - <stage-host>
    - <prod-host>-shadow
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      cipherSuites:
      - ECDHE-RSA-CHACHA20-POLY1305
      - ECDHE-RSA-AES256-GCM-SHA384
      - ECDHE-RSA-AES256-SHA
      - ECDHE-RSA-AES128-GCM-SHA256
      - ECDHE-RSA-AES128-SHA
      credentialName: kyma-gateway-certs
      minProtocolVersion: TLSV1_2
      mode: SIMPLE
  - hosts:
    - <stage-host>
    - <prod-host>-shadow
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
```

Then add the shadow host to the Virtual Service:

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app: gateway
  name: compass-gateway
  namespace: compass-system
spec:
  gateways:
  - kyma-system/kyma-gateway
  hosts:
  - <stage-host>
  - <prod-host>-shadow
  http:
  - match:
    - uri:
        prefix: /tenants
    route:
    - destination:
        host: <in-cluster-destination-fqdn>
        port:
          number: 4455
```

# Results and troubleshooting information

The flow as described above does not work as expected. While troubleshooting I increased the log level of the istio ingressgateway to debug and the following information was found there:

### Prod cluster
```
2022-07-05T12:29:50.222639Z	debug	envoy router	[C0][S4644820561454574531] cluster 'outbound|443||<stage-host>' match for URL '/tenants/<rest-of-the-path>'

2022-07-05T12:29:50.222684Z	debug	envoy router	[C0][S4644820561454574531] router decoding headers:
':authority', '<prod-host>-shadow'
':path', '/tenants/<rest-of-the-path>'
... <more headers>

2022-07-05T12:29:50.227465Z	debug	envoy router	[C0][S4644820561454574531] upstream reset: reset reason: connection termination, transport failure reason:

2022-07-05T12:29:50.227591Z	debug	envoy http	async http request response headers (end_stream=false):
':status', '503'
'content-length', '95'
'content-type', 'text/plain'
```

It looks like the configuration on the prod side is okay as the envoy is trying to create the shadow request.

### Stage cluster
Nothing is received on stage end

---

Another thing that I have tried is to do the configuration with http (and therefore match the second part of the stage's gateway where it is 301 redirected to https) and in this case it successfully landed in stage's ingress and logs for 301 response were present. Which I think indicates that there are some problems with mirroring https traffic.

---

I tried doing the same thing with envoy filter and the issue is exactly the same:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: mirror-prod-to-stage
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: istio-ingressgateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.lua
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
            inlineCode: |
              function startswith(str, start)
                return str:sub(1, #start) == start
              end

              function dump(o)
                if type(o) == 'table' then
                    local s = '{ '
                    for k,v in pairs(o) do
                      if type(k) ~= 'number' then k = '"'..k..'"' end
                      s = s .. '['..k..'] = ' .. dump(v) .. ','
                    end
                    return s .. '} '
                else
                    return tostring(o)
                end
              end

              function envoy_on_request(request_handle)
                local headers = request_handle:headers()
                local path = headers:get(":path")
                local method = headers:get(":method")
                local authorization = headers:get("authorization")
                local buffered = request_handle:body(true)
                local bodyString = tostring(buffered:getBytes(0, buffered:length()))

                if startswith(path, "/tenants") then
                  local headers, body = request_handle:httpCall(
                   "dev-main-cluster",
                   {
                    [":method"] = method,
                    [":path"] = path,
                    [":authority"] = "<stage-host>",
                    [":scheme"] = "https",
                    ["authorization"] = authorization,
                    ["content-type"] = "application/json",
                    ["content-length"] = bodyString:len(),
                    ["x-forwarded-proto"] = "https"
                   },
                   bodyString, 120000, false)
                   request_handle:logInfo(dump(headers))
                   request_handle:logInfo(dump(body))
                end
              end
    # The second patch adds the cluster that is referenced by the lua code
    # cds match is omitted as a new cluster is being added
    - applyTo: CLUSTER
      match:
        context: GATEWAY
      patch:
        operation: ADD
        value: # cluster specification
          name: "stage-cluster"
          type: STRICT_DNS
          connect_timeout: 0.5s
          lb_policy: ROUND_ROBIN
          http2_protocol_options:
            initial_connection_window_size: 1048576
            initial_stream_window_size: 65536
          transport_socket:
            name: envoy.transport_sockets.tls
          load_assignment:
            cluster_name: "stage-cluster"
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          protocol: TCP
                          address: <stage-host>
                          port_value: 443
```

Tried without http2 config above and it is still the same.

### Version

```prose
▶ istioctl version                                                             
client version: 1.12.2
control plane version: 1.11.4
data plane version: 1.11.4 (56 proxies)

▶ kubectl version --short
Client Version: v1.23.1
Server Version: v1.21.11-gke.1900
```

**Comment by howardjohn** [comment]
Do you have a Destinationrule originated TLS? If not, I think that is what is missing

**Comment by DimitarPetrov** [comment]
Hello @howardjohn

I added the following destination rule to the prod cluster:
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: stage-cluster
  namespace: compass-system
spec:
  host: <stage-host>
  trafficPolicy:
    tls:
      mode: SIMPLE
```

But the error is exactly the same. 

Correct me if I am wrong but as far as I understand destination rule originated TLS is needed when workloads initiate an http call and we want istio to initiate https to the external service. 

In our case calls to prod are already https and we want to mirror them to another https external service (stage cluster). Actually, this part seems to work based on the prod's ingress logs:

```
2022-07-05T12:29:50.222639Z	debug	envoy router	[C0][S4644820561454574531] cluster 'outbound|443||<stage-host>' match for URL '/tenants/<rest-of-the-path>'

2022-07-05T12:29:50.222684Z	debug	envoy router	[C0][S4644820561454574531] router decoding headers:
':authority', '<prod-host>-shadow'
':scheme', 'https'
':path', '/tenants/<rest-of-the-path>'
... <more headers>
```

Which tells me that ingress has an outbound envoy cluster for port 443 and later the scheme used is https.
