### ISSUE TITLE
Unable to route outgoing traffic through the egress gateway

### ISSUE THREAD

**Issue by ArjonBu** [istio/istio#39885]
### Bug Description

I have an external service running in 3 ports. I am trying to force all outgoing traffic to this external service to go through the egress gateway but it's not working. The traffic leaves the cluster from the sidecar. 

### Version

```prose
❯ istioctl version
client version: 1.14.1
control plane version: 1.14.1
data plane version: 1.14.1 (72 proxies)

❯ oc version
Client Version: v4.2.0-alpha.0-1420-gf1f09a3
Server Version: 4.9.15
Kubernetes Version: v1.22.3+e790d7f
```

### Additional Information

I have the following egress gateway:

```
    gateways:
      istio-egressgateway:
        env: {}
        autoscaleEnabled: true
        autoscaleMin: 1
        autoscaleMax: 1
        type: ClusterIP
        name: istio-egressgateway
        secretVolumes:
          - name: egressgateway-certs
            secretName: istio-egressgateway-certs
            mountPath: /etc/istio/egressgateway-certs
          - name: egressgateway-ca-certs
            secretName: istio-egressgateway-ca-certs
            mountPath: /etc/istio/egressgateway-ca-certs
        podAntiAffinityTermLabelSelector:
          - key: app
            operator: In
            values: istio-egressgateway
            topologyKey: kubernetes.io/hostname
            weight: 100
        ports:
          - port: 80
            targetPort: 8080
            name: http2
            protocol: TCP
          - port: 443
            name: https
            targetPort: 8443
            protocol: TCP
          - port: 1521
            name: tcp-oracle
            targetPort: 1521
            protocol: TCP
          - port: 28014
            name: mytool-1
            targetPort: 28014
            protocol: TCP
          - port: 28015
            name: mytool-2
            targetPort: 28015
            protocol: TCP
          - port: 28023
            name: mytool-3
            targetPort: 28023
            protocol: TCP

```

I have the following objects:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: mytool
  namespace: istiotst
spec:
  hosts:
  - mytool.internal
  addresses:
  - X.X.X.X/32
  ports:
  - number: 28014
    name: mytool-1
    protocol: TCP
  - number: 28015
    name: mytool-2
    protocol: TCP
  - number: 28023
    name: mytool-3
    protocol: TCP
  resolution: STATIC
  location: MESH_EXTERNAL
  endpoints:
    - address: X.X.X.X
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mytool-egressgateway
  namespace: istiotst
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 28014
      name: mytool-1
      protocol: TCP
    hosts:
      - "*"
  - port:
      number: 28015
      name: mytool-2
      protocol: TCP
    hosts:
      - "*"
  - port:
      number: 28023
      name: mytool-3
      protocol: TCP
    hosts:
      - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-mytool
  namespace: istiotst
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: mytool
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-mytool-through-egress-gateway
  namespace: istiotst
spec:
  hosts:
  - X.X.X.X
  gateways:
  - mytool-egressgateway
  - mesh
  tcp:
  - match:
    - gateways:
      - mesh
      port: 28014
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: mytool
        port:
          number: 28014
      weight: 100
  - match:
    - gateways:
      - mesh
      port: 28015
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: mytool
        port:
          number: 28015
      weight: 100
  - match:
    - gateways:
      - mesh
      port: 28023
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: mytool
        port:
          number: 28023
      weight: 100
  - match:
    - gateways:
      - mytool-egressgateway
      port: 28014
    route:
    - destination:
        host: mytool.internal
        port:
          number: 28014
      weight: 100
  - match:
    - gateways:
      - mytool-egressgateway
      port: 28015
    route:
    - destination:
        host: mytool.internal
        port:
          number: 28015
      weight: 100
  - match:
    - gateways:
      - mytool-egressgateway
      port: 28023
    route:
    - destination:
        host: mytool.internal
        port:
          number: 28023
      weight: 100
```

the istio-proxy sidecar logs:
```
[2022-07-12T16:04:33.666Z] "- - -" 0 - - - "-" 494 879 37 - "-" "-" "-" "-" "172.31.8.113:28015" outbound|28015||mytool.internal 10.128.39.83:42384 x.x.x.x:28015 10.128.39.83:42382 - -
[2022-07-12T16:04:33.704Z] "- - -" 0 - - - "-" 530 906 8 - "-" "-" "-" "-" "172.31.8.113:28015" outbound|28015||mytool.internal 10.128.39.83:42388 x.x.x.x:28015 10.128.39.83:42386 - -
[2022-07-12T16:04:33.712Z] "- - -" 0 - - - "-" 268 268 48 - "-" "-" "-" "-" "172.31.8.113:28023" outbound|28023||mytool.internal 10.128.39.83:35596 x.x.x.x:28023 10.128.39.83:35594 - -
[2022-07-12T16:04:33.758Z] "- - -" 0 - - - "-" 0 0 13 - "-" "-" "-" "-" "172.31.8.113:28014" outbound|28014||mytool.internal 10.128.39.83:41946 1x.x.x.x:28014 10.128.39.83:41944 - -
```

```
❯ istioctl pc listener -n istiotst service-86454bhn2hd --port 28014
ADDRESS       PORT  MATCH                                DESTINATION
10.138.175.60 28014 Trans: raw_buffer; App: http/1.1,h2c Route: istio-egressgateway.istio-system.svc.cluster.local:28014
10.138.175.60 28014 ALL                                  Cluster: outbound|28014||istio-egressgateway.istio-system.svc.cluster.local
X.X.X.X  28014 ALL                                  Cluster: outbound|28014||mytool.internal
```

The output of `istioctl pc route -n istiotst podname` doesn't show X.X.X.X or mytool.internal. 

The traffic leaves the sidecar but it doesn't go through the egress-gateway. 

`istioctl analyze -A` doesn't return any errors or warnings.

Any idea what I might be doing wrong?
