### ISSUE TITLE
Add support for route percent match

### ISSUE THREAD

**Issue by sschepens** [istio/istio#39880]
**Describe the feature request**
Add support for route percent matching [aka runtime_fraction](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routematch-runtime-fraction)

We have several use cases where we would want to specify different routes with percentages to further customize routing, here are a few examples:
- Direct a percentage of traffic to a new service, we might have a new service replacing an older one and this way we could direct a precentage of traffic to it. This is not doable today using route subsets and weights unless both are subsets of the same service.

- Further extend fault injection, imagine we want to create multiple fault injection rules: abort 30% of requests that match X header, then abort 50% of requests that match Y header, and so on. This is not currently doable today, we could specify several routes each with a fault configuration, but the result would not be the same, for example if we put a route match on header X and fault 50% of requests, then the rest of the traffic would flow correctly, even if it had header Y, because it matched the first route.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by sschepens** [comment]
@howardjohn wdyt? i could have a go at implementing this.

**Comment by sschepens** [comment]
Yeah, I think i got the first one wrong, but the second case is totally valid.

> In this specific example you could add 4 matches (none, x match, y match, x and y match). Although I can see how that could quickly get out of hand

I don't think this would actually work, because I would have to calculate cumulative percentages of X and Y, and that is sort of impossible.

match x - drop 30%
match y - drop 50%
match x and y - drop ?%

As you noted, this also gets more complicated the more matches you add.

**Comment by hzxuzhonghu** [comment]
Not sully understand, what do you expect? Istio HTTPRoute allows you set any matching conditions

```
match x - drop 30%
match y - drop 50%
match x and y - drop ?%
```

**Comment by sschepens** [comment]
An example:
- Drop 30% of traffic that has header X
- Drop 50% of traffic that has header Y

How would I achieve that? Currently what I can do is:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test
spec:
  hosts:
  - host
  http:
  - match:
    - headers:
        X:
          exact: X
      uri:
        prefix: "/"
    route:
    - destination:
        host: host
    fault:
      abort:
        percentage:
          value: 30
        httpStatus: 503
  - match:
    - headers:
        Y:
          exact: Y
      uri:
        prefix: "/"
    route:
    - destination:
        host: host
    fault:
      abort:
        percentage:
          value: 50
        httpStatus: 503
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: host
```

But what happens if we get requests which have both X and Y? they would end up matching over the first route and not the second one, this also gets trickier the more matches you want to make.

What I propose is to add a percent o fraction matcher, then we could do:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test
spec:
  hosts:
  - host
  http:
  - match:
    - headers:
        X:
          exact: X
      uri:
        prefix: "/"
      percent: 30
    route:
    - destination:
        host: host
    fault:
      abort:
        percentage:
          value: 100
        httpStatus: 503
  - match:
    - headers:
        Y:
          exact: Y
      uri:
        prefix: "/"
      percent: 50
    route:
    - destination:
        host: host
    fault:
      abort:
        percentage:
          value: 100
        httpStatus: 503
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: host
```

I could even choose to add custom headers when traffic would be faulted, which is not something we can do right now:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test
spec:
  hosts:
  - host
  http:
  - match:
    - headers:
        X:
          exact: X
      uri:
        prefix: "/"
      percent: 30
    headers:
      response:
        set:
          x-request-faulted: "true"
    route:
    - destination:
        host: host
    fault:
      abort:
        percentage:
          value: 100
        httpStatus: 503
  - match:
    - headers:
        Y:
          exact: Y
      uri:
        prefix: "/"
      percent: 50
    headers:
      response:
        set:
          x-request-faulted: "true"
    route:
    - destination:
        host: host
    fault:
      abort:
        percentage:
          value: 100
        httpStatus: 503
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: host
```
