### ISSUE TITLE
Multi-Cluster/Multi-Network -  the control plane cannot read eastwestgateway endpoints from the remote cluster

### ISSUE THREAD

**Issue by jjluUp** [istio/istio#39930]
### Bug Description

Following the guide [Install Multi-Primary on different networks](https://istio.io/latest/docs/setup/install/multicluster/multi-primary_multi-network), everything seems to install as expected without errors, but the control plane cannot read eastwestgateway endpoints from the remote cluster, only helloworld ip + port
```
$  istioctl pc endpoint sleep-557747455f-szwnt.istio-sample |grep helloworld
10.233.82.135:5000               HEALTHY     OK                outbound|5000||helloworld.istio-sample.svc.cluster.local
10.241.70.74:5000                HEALTHY     OK                outbound|5000||helloworld.istio-sample.svc.cluster.local

cluster1  10.241.70.74:5000
cluster2  10.233.82.135:5000
```
```
$  kubectl -n istio-system get service -l "istio=eastwestgateway"
NAME                    TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)                                                           AGE
istio-eastwestgateway   NodePort   10.241.14.131   <none>        15021:31104/TCP,15443:31636/TCP,15012:31167/TCP,15017:32396/TCP   5h26m
```
```
$  kubectl exec -n istio-sample -c sleep "$(kubectl get pod -n istio-sample -l app=sleep -o jsonpath='{.items[0].metadata.name}')" -- sh -c "while true; do curl -s helloworld.istio-sample:5000/hello; done"
Hello version: v1, instance: helloworld-v1-776f57d5f6-srrzh
Hello version: v1, instance: helloworld-v1-776f57d5f6-srrzh
Hello version: v1, instance: helloworld-v1-776f57d5f6-srrzh
Hello version: v1, instance: helloworld-v1-776f57d5f6-srrzh
Hello version: v1, instance: helloworld-v1-776f57d5f6-srrzh
Hello version: v1, instance: helloworld-v1-776f57d5f6-srrzh
Hello version: v1, instance: helloworld-v1-776f57d5f6-srrzh
```
the eastwest gateway service of type ：NodePort, 
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  annotations:
    install.istio.io/ignoreReconcile: 'true'
  name: installed-state-eastwest
  namespace: istio-system
spec:
  components:
    base:
      enabled: false
    cni:
      enabled: false
    egressGateways:
      - enabled: false
        name: istio-egressgateway
    ingressGateways:
      - enabled: true
        k8s:
          env:
            - name: ISTIO_META_REQUESTED_NETWORK_VIEW
              value: network2
          service:
            externalTrafficPolicy: Local
            ports:
              - name: status-port
                port: 15021
                protocol: TCP
                targetPort: 15021
              - name: tls
                port: 15443
                protocol: TCP
                targetPort: 15443
              - name: tls-istiod
                port: 15012
                protocol: TCP
                targetPort: 15012
              - name: tls-webhook
                port: 15017
                protocol: TCP
                targetPort: 15017
            type: NodePort
          serviceAnnotations:
            traffic.istio.io/nodeSelector: '{}'
        label:
          app: istio-eastwestgateway
          istio: eastwestgateway
          topology.istio.io/network: network2
        name: istio-eastwestgateway
      - enabled: false
        name: istio-ingressgateway
    istiodRemote:
      enabled: false
    pilot:
      enabled: false
  hub: docker.io/istio
  meshConfig:
    defaultConfig:
      proxyMetadata: {}
    enablePrometheusMerge: true
  profile: empty
  tag: 1.13.5
  values:
    base:
      enableCRDTemplates: false
      validationURL: ''
    defaultRevision: ''
    gateways:
      istio-egressgateway:
        autoscaleEnabled: true
        env: {}
        name: istio-egressgateway
        secretVolumes:
          - mountPath: /etc/istio/egressgateway-certs
            name: egressgateway-certs
            secretName: istio-egressgateway-certs
          - mountPath: /etc/istio/egressgateway-ca-certs
            name: egressgateway-ca-certs
            secretName: istio-egressgateway-ca-certs
        type: ClusterIP
      istio-ingressgateway:
        autoscaleEnabled: true
        env: {}
        injectionTemplate: gateway
        name: istio-ingressgateway
        secretVolumes:
          - mountPath: /etc/istio/ingressgateway-certs
            name: ingressgateway-certs
            secretName: istio-ingressgateway-certs
          - mountPath: /etc/istio/ingressgateway-ca-certs
            name: ingressgateway-ca-certs
            secretName: istio-ingressgateway-ca-certs
        type: LoadBalancer
    global:
      configValidation: true
      defaultNodeSelector: {}
      defaultPodDisruptionBudget:
        enabled: true
      defaultResources:
        requests:
          cpu: 10m
      imagePullPolicy: ''
      imagePullSecrets: []
      istioNamespace: istio-system
      istiod:
        enableAnalysis: false
      jwtPolicy: third-party-jwt
      logAsJson: false
      logging:
        level: 'default:info'
      meshNetworks: {}
      mountMtlsCerts: false
      multiCluster:
        clusterName: cluster2
        enabled: true
      network: network2
      omitSidecarInjectorConfigMap: false
      oneNamespace: false
      operatorManageWebhooks: false
      pilotCertProvider: istiod
      priorityClassName: ''
      proxy:
        autoInject: enabled
        clusterDomain: cluster.local
        componentLogLevel: 'misc:error'
        enableCoreDump: false
        excludeIPRanges: ''
        excludeInboundPorts: ''
        excludeOutboundPorts: ''
        image: proxyv2
        includeIPRanges: '*'
        logLevel: warning
        privileged: false
        readinessFailureThreshold: 30
        readinessInitialDelaySeconds: 1
        readinessPeriodSeconds: 2
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        statusPort: 15020
        tracer: zipkin
      proxy_init:
        image: proxyv2
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 10m
            memory: 10Mi
      sds:
        token:
          aud: istio-ca
      sts:
        servicePort: 0
      tracer:
        datadog: {}
        lightstep: {}
        stackdriver: {}
        zipkin: {}
      useMCP: false
    istiodRemote:
      injectionURL: ''
    pilot:
      autoscaleEnabled: true
      autoscaleMax: 5
      autoscaleMin: 1
      configMap: true
      cpu:
        targetAverageUtilization: 80
      deploymentLabels: null
      enableProtocolSniffingForInbound: true
      enableProtocolSniffingForOutbound: true
      env:
        ENABLE_LEGACY_FSGROUP_INJECTION: false
      image: pilot
      keepaliveMaxServerConnectionAge: 30m
      nodeSelector: {}
      podLabels: {}
      replicaCount: 1
      traceSampling: 1
    telemetry:
      enabled: true
      v2:
        enabled: true
        metadataExchange:
          wasmEnabled: false
        prometheus:
          enabled: true
          wasmEnabled: false
        stackdriver:
          configOverride: {}
          enabled: false
          logging: false
          monitoring: false
          topology: false

```
Expose services in cluster1
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cross-network-gateway
  namespace: istio-system
spec:
  selector:
    istio: eastwestgateway
  servers:
    - hosts:
        - '*.local'
      port:
        name: tls
        number: 15443
        protocol: TLS
      tls:
        mode: AUTO_PASSTHROUGH
```

### Version

```prose
istioctl version
client version: 1.13.5
control plane version: 1.13.5
data plane version: 1.13.5 (4 proxies)

kubectl version --short
Client Version: v1.20.10
Server Version: v1.20.10
```
