### ISSUE TITLE
Support space separated groups claim on AuthorizationPolicy Conditions

### ISSUE THREAD

**Issue by gabrielgiussi** [istio/istio#39946]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

[When conditions](https://istio.io/latest/docs/reference/config/security/authorization-policy/#Condition) on AuthorizationPolicy rules only allow for exact string matches, e.g.
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: require-jwt
  namespace: foo
spec:
  selector:
    matchLabels:
      app: httpbin
  action: ALLOW
  rules:
  - from:
    - source:
       requestPrincipals: ["testing@secure.istio.io/testing@secure.istio.io"]
    when:
    - key: request.auth.claims[groups]
      values: ["group1"]
```

The [example](https://istio.io/latest/docs/tasks/security/authorization/authz-jwt/) in this case is a jwt containing a claim `"groups":["group1","group2"]` but I want to apply the condition over the scope claim which is defined in the [RFC 8693 - OAuth 2.0 Token Exchange](https://datatracker.ietf.org/doc/html/rfc8693#section-4.2) as a `string containing a space-separated list of scopes`.

**Describe alternatives you've considered**

The alternative is to insert an Envoy RBAC filter with the EnvoyFilter CDR, this allows to use regex for matching jwt claims but it is much more low level than AuthorizationPolicy.
Example
```yml
- name: envoy.filters.http.rbac
  typed_config:
    "@type": "type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC"
    rules:
      action: ALLOW
      policies:
        example
          permissions:
            - and_rules:
                rules:
                  - url_path:
                      path:
                        exact: /some/api
                  - header:
                      name: :method
                      exact_match: POST
          principals:
            - metadata:
                filter: envoy.filters.http.jwt_authn
                path:
                  - key: jwt_payload
                  - key: scope
                value:
                  string_match:
                    safe_regex:
                      google_re2: {}
                      regex: ((group1|group9)(\s.*|$))|([^\s]+\s(group1|group9)(\s.*|$))
```
The regex matches a claim `scope` containing `group1` or `group9`, where `scope` is a string of elements separated with a whitespace, e.g. `"groups":"group1 group5".

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by liminw** [comment]
We currently support groups as "comma separated" strings. If Oauth 2.0 standard is "space separated" strings, we can support "space separated" strings in addition. 

Shall we rename it to "support space separated groups claim" instead? This will have smaller scope than full regex match support. 

cc. @liwenhao0810 @aryan16

**Comment by gabrielgiussi** [comment]
Just to double check, when we configure the policy like this
```
  rules:
  - from:
    - source:
       requestPrincipals: ["testing@secure.istio.io/testing@secure.istio.io"]
    when:
    - key: request.auth.claims[groups]
      values: ["group1","group2"]
```

It means the claim must contain `group1` **OR** `group2`, so all of these cases will pass
- `{"groups":["group1"]}`
- `{"groups":["group2"]}`
- `{"groups":["group1", "group2"]}`
