### ISSUE TITLE
Sidecar is slow to startup when GCP is not accessible

### ISSUE THREAD

**Issue by rinormaloku** [istio/istio#39950]
The below method is querying metadata from GCP. However, when GCP is not accessible (e.g. firewall rules), this will delay the agent to start up for about 90 seconds. 

https://github.com/istio/istio/blob/6450eccc71f01448d2ff740d1011c2358dbe0a28/pkg/bootstrap/platform/gcp.go#L137

We discovered this when `holdApplicationUntilProxyStarts` is set to  `true`. It caused the pod to be in a infinite crash loop, as the pilot-wait health checks were constantly failed (the health check timeouts in 60 seconds).

How to reproduce:

1. In GKE (with Kubernetes Network Policies enbaled) install istio
2. Create test ns and network policy to block traffic to GCP:
```
kubectl create ns test                                      
kubectl label namespace test istio-injection=enabled 

kubectl -n test apply -f- <<EOF
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: test
spec:
  podSelector:
    matchLabels: 
      app: demo
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except: 
            - 169.254.169.254/32
        - ipBlock:
            cidr: 10.0.0.0/8
EOF
```

3. Create the following workload
```
kubectl -n test apply -f- <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  netshoot
  labels:
    app: demo
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/agentLogLevel: "all:debug"
      labels:
        app: demo
    spec:
      containers:
      - name:  netshoot
        image:  nicolaka/netshoot
        imagePullPolicy: IfNotPresent
        args: ['tail', '-f', '/dev/null']
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
EOF
```

The sidecar will take about 2 minutes to start up. If you would annotate it to hold until app starts it would fail. 
To do so add `proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'` to the above annotations.

> NOTE: Errors are being hidden, I created a second container with some logs prefixed with a series of = signs. You might want to use that to see all the errors: `sidecar.istio.io/proxyImage: 'rinormaloku/proxyv2:wd8'`

I can make a PR to fix this issue but wanted to pick up your mind, what you'd recommend.

**Question:** Should we error out on failure? Shall we make the requests concurrently? Shall we skip all subsequent requests when we discover that GCP is not accessible? Or shall we simply increase the pilot-agent wait timeout?

**Comment by zirain** [comment]
@rinormaloku I do not have a real GCP cluster, would you try https://github.com/istio/istio/issues/39950, feel free to take over it.

**Comment by zirain** [comment]
https://github.com/istio/istio/pull/39953#discussion_r922647875

maybe you'd better request upstream to fix this.

**Comment by rinormaloku** [comment]
I think it is entirely our codebase that can be improved. Though I'd appreciate some input on what would be a suggested solution?

Shall we return false when we call IsGCP when the endpoints are not available?

**Comment by rinormaloku** [comment]
This method is returning true, which tries if the internal DNS resolution can resolve the IP. If it does, then it means that it is running on GCP. 

https://github.com/googleapis/google-cloud-go/blob/compute/v1.7.0/compute/metadata/metadata.go#L146-L154

We need to check if the TCP connection to the endpoint is possible.

**Comment by zirain** [comment]
> This method is returning true, which tries if the internal DNS resolution can resolve the IP. If it does, then it means that it is running on GCP.
> 
> https://github.com/googleapis/google-cloud-go/blob/compute/v1.7.0/compute/metadata/metadata.go#L146-L154
> 
> We need to check if the TCP connection to the endpoint is possible.

so this will happen when user block `169.254.169.254` on GCP for security reason like `https://github.com/istio/istio/issues/40010` but internal DNS resolution still working, istio auto detected platform as GCP, then the following requests send to  `169.254.169.254` will be blocked.

**Comment by rinormaloku** [comment]
Yes, that's how I was able to reproduce it, and the reported issue is the same I am describing here (these two issues are the same)

The PR that I opened, fixes this. I tested it in an GCP environment.

**Comment by rinormaloku** [comment]
Closing this issue as the fix is merged #40105

**Comment by PrayagS** [comment]
> Or shall we simply increase the pilot-agent wait timeout?

We're currently facing this issue intermittently and looking for a way to increase the timeout. Do you know how can we do the same? I couldn't find anything on the docs.

**Comment by rinormaloku** [comment]
You can disable the GCP platform by setting the CLOUD_PLATFORM to none: https://istio.io/latest/docs/reference/commands/pilot-discovery/

Or you can customize the deployment and increase the timeout as shown below:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  #...
spec:
  template:
   #...
    spec:
      containers:
      - # your app
      - name: istio-proxy
        image: auto
        lifecycle:
          postStart:
            exec:
              command:
              - pilot-agent
              - wait
              - --timeoutSeconds
              - '120'
              - --url
              - 'http://0.0.0.0:15021/healthz/ready'
```

**Comment by rinormaloku** [comment]
You can update the injection template to contain those changes, thus it will be added to every pod via sidecar injection

**Comment by PrayagS** [comment]
> You can update the injection template to contain those changes, thus it will be added to every pod via sidecar injection

Thanks again for getting back. I didn't know about the custom templates.

I also stumbled upon another way to configure the hook independently by configuring the `IstioOperator` resource as shown below,
```
...
values:
  global:
    proxy:
      lifecycle:
        postStart:
          exec:
            command:
            - pilot-agent
            - wait
            - --timeoutSeconds
            - '120'
```

As per the YAML templates used to generate the proxy container, the `holdApplicationUntilProxyStarts` flag only adds the default wait command with no way to configure args.
