### ISSUE TITLE
HTTPFaultInjection in VS does not work if percentage is omitted

### ISSUE THREAD

**Issue by shriramsharma** [istio/istio#39969]
## Description
I was trying to configure HTTPFaultInjection in my VirtualService and as per [documentation](https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPFaultInjection-Abort), the `percentage` field is optional. Omitting it should `abort` all the requests meeting the criteria. 

But when I omit it, the `abort` faultInjection stops working and all the requests pass through to the upstream cluster successfully. I'm unsure if this is a bug in the implementation or if I'm using it incorrectly?

## Steps to reproduce
1. Install the httpbin app in a mesh enabled NS
2. Install the sleep app in a mesh enabled NS
3. Create a VS as shown below
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sleep-vs
spec:
  hosts:
  - httpbin.default.svc.cluster.local
  http:
  - fault:
      abort:
        httpStatus: 403
    route:
    - destination:
        host: httpbin.default.svc.cluster.local
        port: 
          number: 8000
    match:
      - uri:
          prefix: "/get"
```
4. Try to make a request from the sleep pod
```
k exec <SLEEP_POD> -it -- curl -vso /dev/null http://httpbin.default.svc.cluster.local:8000/get
``` 

## Expectation
The expectation was that all the requests to the `/get` endpoint should result in `403`. 

## What was observed?
All the requests returned `200`.

Please do let me know if I'm missing something

### Version

```prose
$ istioctl version
client version: 1.13.2
control plane version: 1.13.2
data plane version: 1.13.2 (4 proxies)

$  k version --short
Client Version: v1.21.2
Server Version: v1.22.1
```

### Additional Information

Here is the corresponding envoy config snippet
```json
"name": "httpbin.default.svc.cluster.local:8000",
"domains": [
	"httpbin.default.svc.cluster.local",
	"httpbin.default.svc.cluster.local:8000",
	"httpbin",
	"httpbin:8000",
	"httpbin.default.svc",
	"httpbin.default.svc:8000",
	"httpbin.default",
	"httpbin.default:8000",
],
"routes": [{
		"match": {
			"prefix": "/get",
			"case_sensitive": true
		},
		"route": {
			"cluster": "outbound|8000||httpbin.default.svc.cluster.local",
			"timeout": "0s",
			"retry_policy": {
				"retry_on": "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes",
				"num_retries": 2,
				"retry_host_predicate": [{
					"name": "envoy.retry_host_predicates.previous_hosts"
				}],
				"host_selection_retry_max_attempts": "5",
				"retriable_status_codes": [
					503
				]
			},
			"max_grpc_timeout": "0s"
		},
		"metadata": {
			"filter_metadata": {
				"istio": {
					"config": "/apis/networking.istio.io/v1alpha3/namespaces/default/virtual-service/sleep-vs"
				}
			}
		},
		"decorator": {
			"operation": "httpbin.default.svc.cluster.local:8000/get*"
		},
		"typed_per_filter_config": {
			"envoy.filters.http.fault": {
				"@type": "type.googleapis.com/envoy.extensions.filters.http.fault.v3.HTTPFault",
				"abort": {
					"http_status": 403
				}
			}
		}
	}
```
