### ISSUE TITLE
Install Multi-Primary on different networks  with Helm on EKS problem

### ISSUE THREAD

**Issue by dimitarshenkov** [istio/istio#39987]
### Bug Description

Hi , we have  installed Multi-Primary on different networks  with Helm on EKS following : 
https://istio.io/latest/docs/setup/install/multicluster/multi-primary_multi-network/
Also all steps from here are working fine for us https://istio.io/latest/docs/ops/diagnostic-tools/multicluster/ 
But when we tried  verifying the Cross-Cluster Traffic like https://istio.io/latest/docs/setup/install/multicluster/verify/
The version did NOT toggle between v1 and v2.  

### Version

```prose
istioctl version
client version: 1.12.0
control plane version: 1.14.1
data plane version: 1.14.1 (17 proxies), 1.13.3 (1 proxies)
kubectl version --short
Client Version: v1.23.6
Server Version: v1.22.9-eks-a64ea69
helm version --short
v3.4.0+g7090a89
```

### Additional Information

```
##################################frontend cluster######################################
helm -n istio-system get values istio-eastwestgateway
USER-SUPPLIED VALUES:
env:
  value: ew1-uat-frontend11
global:
  network: ew1-uat-frontend11
labels:
  app: istio-eastwestgateway
  istio: eastwestgateway
  topology.istio.io/network: ew1-uat-frontend11
name: istio-eastwestgateway
networkGateway: ew1-uat-frontend11
service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  ports:
  - name: status-port
    port: 15021
    targetPort: 15021
  - name: tls
    port: 15443
    targetPort: 15443
  - name: tls-istiod
    port: 15012
    targetPort: 15012
  - name: tls-webhook
    port: 15017
    targetPort: 15017
	
helm -n istio-system get values istio
USER-SUPPLIED VALUES:
global:
  istiod:
    enableAnalysis: true
  logAsJson: true
  meshID: mesh2
  meshNetworks:
    ew1-uat-backend11:
      endpoints:
      - fromRegistry: ew1-uat-backend11
      gateways:
      - port: 15443
        registryServiceName: istio-eastwestgateway.istio-system.svc.cluster.local
  multiCluster:
    clusterName: ew1-uat-frontend11
    enabled: true
  network: ew1-uat-frontend11
  tracer:
    zipkin:
      address: zipkin.istio-system.svc.cluster.local:9411
meshConfig:
  enableTracing: true
  outboundTrafficPolicy:
    mode: ALLOW_ANY
pilot:
  autoscaleMin: 2
tracing:
  enabled: true	
```

```
############################backend cluster###############################  
helm -n istio-system get values istio  
USER-SUPPLIED VALUES:
global:
  istiod:
    enableAnalysis: true
  logAsJson: true
  meshID: mesh2
  meshNetworks:
    ew1-uat-frontend11:
      endpoints:
      - fromRegistry: ew1-uat-frontend11
      gateways:
      - port: 15443
        registryServiceName: istio-eastwestgateway.istio-system.svc.cluster.local
  multiCluster:
    clusterName: ew1-uat-backend11
    enabled: true
  network: ew1-uat-backend11
  tracer:
    zipkin:
      address: zipkin.istio-system.svc.cluster.local:9411
meshConfig:
  enableTracing: true
  outboundTrafficPolicy:
    mode: ALLOW_ANY
pilot:
  autoscaleMin: 1
tracing:
  enabled: true

helm -n istio-system get values istio-eastwestgateway 
USER-SUPPLIED VALUES:
env:
  value: ew1-uat-backend11
global:
  network: ew1-uat-backend11
labels:
  app: istio-eastwestgateway
  istio: eastwestgateway
  topology.istio.io/network: ew1-uat-backend11
name: istio-eastwestgateway
networkGateway: ew1-uat-backend11
service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  ports:
  - name: status-port
    port: 15021
    targetPort: 15021
  - name: tls
    port: 15443
    targetPort: 15443
  - name: tls-istiod
    port: 15012
    targetPort: 15012
  - name: tls-webhook
    port: 15017
    targetPort: 15017 
```

### Affected product area

- [X] Docs
- [X] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [X] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
