### ISSUE TITLE
Default targetPort is the same use helm and istioctl to install Istio Gateway

### ISSUE THREAD

**Issue by scydas** [istio/istio#39992]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Default targetPort is the same use helm and istioctl to install Istio Gateway
http2: targetPort 80 -> 8080
https: targetPort 443 -> 8443
https://github.com/istio/istio/blob/master/manifests/charts/gateway/values.yaml
```
service:
  # Type of service. Set to "None" to disable the service entirely
  type: LoadBalancer
  ports:
  - name: status-port
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: http2
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  annotations: {}
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  externalTrafficPolicy: ""
  externalIPs: []
```

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
They are intentionally different. One is made 2 years after the former and learns from the mistakes we have made. If you don't want defaults you can change them

**Comment by panpan0000** [comment]
Meet the same problem.When istio-ingress process listens on 80 port , it requires root privilege. 
But typically, it will listen ports other than 80. So people will usually modify the `spec.ports[?(@.name=="http2")].targetPort `in the helm chart by `--set` during their `helm install`.
However the customization is not an easy way as below:

 Below makes no luck, it will fail with error "- service.ports.0: Invalid type. Expected: object, given: null", complains the ports[0] not set.
```
helm upgrade --install istio-ingress istio/gateway   ... --set service.ports[1].targetPort=8080
```


currently, the render in `gateway/templates/service.yaml` is easy as below
```
{{ .Values.service.ports | toYaml | indent 4 }}
```
But the syntax in `values.yaml` and schema makes it hard to `--set` very easily.

I think the better way is to polish the charts to make this customization easier during `--set`.

**Comment by howardjohn** [comment]
It doesn't require root on recent versions of Kubernetes

**Comment by panpan0000** [comment]
unfortunately, my kubernetes version `v1.23.7`, with UID=0 still not working with 80 port, my reproducing steps as below.

1. install istio-gateway: `helm upgrade --install istio-ingress istio/gateway -n istio-system  --version=1.13.5  --set securityContext.runAsUser=0  --set service.type=NodePort`

2. create a gateway CR to listen on 80 port:
 ```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: my-gateway
  namespace: xxxx
spec:
  selector:
    istio: ingress
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
```

3. Error appears:
```
kubectl -n istio-system logs -f istio-ingress-7fc696cdcb-4dz22
....
2022-07-20T02:18:21.161967Z	error	envoy config	listener '0.0.0.0_80' failed to bind or apply socket options: cannot bind '0.0.0.0:80': Permission denied
2022-07-20T02:18:21.162125Z	warning	envoy config	gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_80: cannot bind '0.0.0.0:80': Permission denied
```
