### ISSUE TITLE
failed to write updated envoy bootstrap: failed to marshal bootstrap as JSON: proto: not found

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#40005]
### Bug Description

ef-rm-fixed_heap.yaml

kubectl apply -f ef-rm-fixed_heap.yaml -n istio

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: rm
spec:
  workloadSelector:
    labels:
      app: productpage
  configPatches:
  - applyTo: BOOTSTRAP
    patch:
      operation: MERGE
      value:
        overload_manager:
          actions:
          - name: envoy.overload_actions.shrink_heap
            triggers:
            - name: envoy.resource_monitors.fixed_heap
              threshold:
                value: 0.9
          - name: envoy.overload_actions.stop_accepting_requests
            triggers:
            - name: envoy.resource_monitors.fixed_heap
              threshold:
                value: 0.95
          refresh_interval: 0.25s
          resource_monitors:
          - name: envoy.resource_monitors.fixed_heap
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.resource_monitors.fixed_heap.v3.FixedHeapConfig
              max_heap_size_bytes: 70741824.0
```

### Version

```prose
[root@node01 resource_monitor]# istioctl version
client version: 1.14.1
control plane version: 1.14.1
data plane version: 1.14.1 (21 proxies)

[root@node01 resource_monitor]# kubectl version --short
Client Version: v1.21.0
Server Version: v1.21.0
```
