### ISSUE TITLE
When using external profile install or generate manifest duplicate services and endpoints created.

### ISSUE THREAD

**Issue by litong01** [istio/istio#40022]
### Bug Description

When use the following command to generate manifest file, duplicate istiod service and endpoint will be produced.

```
cat <<EOF | istioctl manifest generate -f -
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: external
  values:
    global:
      remotePilotAddress: 1.2.3.4
    istiodRemote:
      injectionPath: /inject/cluster/cluster2/net/network1
  components:
    base:
      enabled: true
EOF
```

The following services will be duplicated in the output.

```
apiVersion: v1
kind: Endpoints
metadata:
  name: istiod
  namespace: istio-system
subsets:
- addresses:
  - ip: 1.2.3.4
  ports:
  - port: 15012
    name: tcp-istiod
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: istiod
  namespace: istio-system
spec:
  ports:
  - port: 15012
    name: tcp-istiod
    protocol: TCP
  # if the remotePilotAddress is IP addr, we use clusterIP: None.
  # else, we use externalName
  clusterIP: None
```

using k8s overlay can only modify one instance.

### Version

```prose
This error exists in the following releases tested.
1.13.x
1.14.x
1.15 (master local build)
```
