### ISSUE TITLE
In case, istio unable to route traffic to destination using FQDN due to unavailability of destination, Istio unable to retry another IP address which is configured for the same FQDN

### ISSUE THREAD

**Issue by Asisranjan** [istio/istio#40038]
### Bug Description

We have configured multiple IP address for a FQDN. We are routing the request using FQDN. We are also expecing when one of the IP address goes down and then Istio will retry to another IP address which is not happening. The envoy filter which uses is given below. 
----
[root@asisvm ~]# nslookup nwsim.test.asis.org
Server:         10.75.196.177
Address:        10.75.196.177#53

Name:   nwsim.test.asis.org
Address: 10.75.145.7
Name:   nwsim.test.asis.org
Address: 10.143.118.244
;; Got recursion not available from 10.75.196.177, trying next server
** server can't find nwsim.test.asis.org: NXDOMAIN
-----------
envoy filter
---------------
````
spec:
  configPatches:
  - applyTo: LISTENER
    match:
      context: SIDECAR_OUTBOUND
    patch:
      operation: ADD
      value:
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 10000
            protocol: TCP
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              http_filters:
              - name: envoy.filters.http.dynamic_forward_proxy
                typed_config:
                  '@type': type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
                  dns_cache_config:
                    dns_lookup_family: V4_ONLY
                    name: dynamic_forward_proxy_cache_config
              - name: envoy.filters.http.lua
                typed_config:
                  '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
                  inline_code: |
                    function envoy_on_request(request_handle)
                      request_handle:logInfo("Hello World.")
                    end
              - name: envoy.router
                typed_config:
                  '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              route_config:
                name: local_route
                request_headers_to_remove:
                - x-envoy-peer-metadata
                - x-envoy-peer-metadata-id
                virtual_hosts:
                - domains:
                  - https.traffic.domain
                  name: https_service
                  retry_policy:
                    host_selection_retry_max_attempts: 3
                    num_retries: 2
                    per_try_timeout: 3s
                    retry_host_predicate:
                    - name: envoy.retry_host_predicates.previous_hosts
                    retry_on: connect-failure,refused-stream,503
                  routes:
                  - match:
                      prefix: /
                    route:
                      cluster: https_dynamic_forward_proxy_cluster
                - domains:
                  - nwsim.*
                  - http.traffic.domain
                  name: http_service
                  retry_policy:
                    host_selection_retry_max_attempts: 3
                    num_retries: 2
                    per_try_timeout: 3s
                    retry_host_predicate:
                    - name: envoy.retry_host_predicates.previous_hosts
                    retry_on: connect-failure,refused-stream,503
                  routes:
                  - match:
                      prefix: /
                    route:
                      cluster: http_dynamic_forward_proxy_cluster
              stat_prefix: ingress_http
        name: proxy
  - applyTo: CLUSTER
    match:
      context: SIDECAR_OUTBOUND
    patch:
      operation: ADD
      value:
        cluster_type:
          name: envoy.clusters.dynamic_forward_proxy
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
            dns_cache_config:
              dns_lookup_family: V4_ONLY
              name: dynamic_forward_proxy_cache_config
        connect_timeout: 1s
        http2_protocol_options:
          max_concurrent_streams: 1073741824
        lb_policy: CLUSTER_PROVIDED
        name: https_dynamic_forward_proxy_cluster
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
            common_tls_context:
              alpn_protocols:
              - h2
              tls_certificates:
              - {}
              validation_context:
                match_typed_subject_alt_names:
                - san_type: DNS
  - applyTo: CLUSTER
    match:
      context: SIDECAR_OUTBOUND
    patch:
      operation: ADD
      value:
        cluster_type:
          name: envoy.clusters.dynamic_forward_proxy
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
            dns_cache_config:
              dns_lookup_family: V4_ONLY
              name: dynamic_forward_proxy_cache_config
        connect_timeout: 1s
        http2_protocol_options:
          max_concurrent_streams: 1073741824
        lb_policy: CLUSTER_PROVIDED
        name: http_dynamic_forward_proxy_cluster
  workloadSelector:
    labels:
      app: test
```
-------------
Observation
------------------
1. Istio tries to send one IP address which is resolved and if that IP address goes down, in this case retry happen to same IP address (expectation is retry to other IP address),
2. Istio tries to send one IP address which is resolved and if that IP address goes down, after multipe fail attempt nearly 15-20 secs approximately, Istio send the request to another IP address (expectation is retry to alternate IP address in case route/connect to other IP address is failed)

### Version

```prose
Istio 1.7.6
$kubectl version --short
Client Version: v1.14.3
Server Version: v1.19.7
$helm3 version --short
v3.2.4+g0ad800e
```


### Additional Information

_No response_

### Affected product area

- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
