### ISSUE TITLE
argo-rollouts pod can't match virtualservice sourceLabels

### ISSUE THREAD

**Issue by labaq** [istio/istio#40034]
### Bug Description

my virtualservice spec is
```
spec:
  hosts:
    - example-demo02-stable
  http:
    - match:
        - sourceLabels:
            role: canary
      route:
        - destination:
            host: example-demo02-canary
            port:
              number: 8080
    - route:
        - destination:
            host: example-demo02-stable
            port:
              number: 8080
```
and my rollout have set labels to stable pod and canary pod like this
```
    canary:
      canaryMetadata:
        labels:
          role: canary
      stableMetadata:
        labels:
          role: stable
```
on first canary the pod have the wright labels so the rule is match
but when canary done, the canary pod will become stable pod and the label is change to stable, but it still match the canary rule, i think istio have already record this pod have canary label but not update to stable label.
can i have update the record for the right labels?

### Version

```prose
client version: 1.13.5
control plane version: 1.15
data plane version: 1.13.5 (8 proxies)

Client Version: v1.24.1
Server Version: v1.22.8+k3s1
```
