### ISSUE TITLE
How can I use httpRoute via mTLS gateway ? 

### ISSUE THREAD

**Issue by dearboll23** [istio/istio#40064]
Hi guys. I have two clusters. clusterA calls clusterB by sevice entry pointing to clusterA's ingress. But the gateway is using the mTLS and tls mode is AUTOPASSTHROUGH, I can't find any log matching the httpRoute behind the gateway. 
The virtual serive is below: 
``` yaml 
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: pa-vs
  namespace: dev
spec:
  gateways:
  - mesh
  - wildcard-gateway
  - istio-system/istio-ingressgateway
  hosts:
  - pagateway.dev.svc.cluster.local
  http:
  - match:
    - headers:
        baggage:
          regex: .*(,|^)version=feature-apaq-165(,|$).*
    name: feature-apaq-165
    route:
    - destination:
        host: pa.dev.svc.cluster.local
        port:
          number: 80
        subset: feature-apaq-165
  - name: stable
    route:
    - destination:
        host: pa.dev.dev.svc.cluster.local
        port:
          number: 80
        subset: stable
  tls:
  - match:
    - sniHosts:
      - pa.dev.svc.cluster.local
    route:
    - destination:
        host: pa.dev.svc.cluster.local
        port:
          number: 80
``` 
 and the gateway is below 
``` yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*.global'
    port:
      name: tls
      number: 15443
      protocol: TLS
    tls:
      mode: AUTO_PASSTHROUGH

```
We  call  _pa.global_ from clusterA, and the service entry will change it to _pa.sg.dev.sg.global_ . And gateway in ClusterB has an envoyfilter that will do tcp_cluster_rewrite to change the host from _pa.sg.dev.sg.global_  to _pa.svc.cluster.local_.  I can see the access log from the pod like below. 

``` 
{"path":"/api/v1/pa/payment_intents/create111","start_time":"2022-07-22T15:53:59.925Z","duration":"7","downstream_remote_address":"10.63.5.9:52352","requested_server_name":"outbound_.80_._.pa.dev.sg.global","response_flags":"-","bytes_sent":"109","upstream_service_time":"7","protocol":"HTTP/1.1","route_name":"default","istio_policy_status":"-","upstream_transport_failure_reason":"-","downstream_local_address":"IPIP:8080","upstream_host":"127.0.0.1:8080","bytes_received":"346","method":"POST","authority":"pa.global","request_id":"ac28e414-3ba6-4cd0-9e3e-f75977c26db4","upstream_local_address":"127.0.0.1:38244","user_agent":"curl/7.79.1","x_forwarded_for":"-","upstream_cluster":"inbound|8080||","response_code":"404"}
```
I don't know whether the traffic from mTLS gateway can be routed by http header? Any help is great appreciated.

**Comment by howardjohn** [comment]
You can't. `AUTO_PASSTHROUGH` strictly just passes through and offers NO customization of routing, etc.

From a technical standpoint its also impossible to operator on HTTP when we only see encrypted traffic.

if you want to do this, use ISTIO_MUTUAL tls mode and terminate the TLS

**Comment by dearboll23** [comment]
Hi [howardjohn](https://github.com/howardjohn), I use ISTIO_MUTUAL tls mode in clusterB now, but the client-side in clusterA receives 'upstream connect error or disconnect/reset before headers. reset reason: connection failure'.
the gw yaml in clusterB and the se yaml in clusterA are below. 
``` yaml
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*.global'
    port:
      name: tls-port
      number: 15443
      protocol: TLS
    tls:
      mode: ISTIO_MUTUAL
```
``` yaml 
spec:
  addresses:
  - xxx
  endpoints:
  - address: {GATEWAY_IP}
    ports:
      http1: 15443
  hosts:
  - pa.global
  location: MESH_INTERNAL
  ports:
  - name: http1
    number: 80
    protocol: http
  resolution: DNS
```
