### ISSUE TITLE
Compressor filter not found

### ISSUE THREAD

**Issue by craigb-zencore** [istio/istio#40071]
### Bug Description

We have GZIP compressor filter configured via Istio EnvoyFilter resource. This was working until our latest upgrade of Istio version. Working state was Istio version 1.12.7 with Envoy version 1.20.1. After the upgrade we are on Istio version 1.13.4 with Envoy version 1.21.0. We receive the following error in our istio-proxy logs:

`[libprotobuf WARNING external/com_google_protobuf/src/google/protobuf/text_format.cc:2139] Can't print proto content: proto type type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor not found

[libprotobuf WARNING external/com_google_protobuf/src/google/protobuf/text_format.cc:2139] Can't print proto content: proto type type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor not found

2022-07-22T13:19:36.035841Z warning envoy config gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_8080: Didn't find a registered implementation for name: 'envoy.filters.http.compressor'

0.0.0.0_8443: Didn't find a registered implementation for name: 'envoy.filters.http.compressor'`

### Version

```prose
Istio version 1.13.4
```

### Additional Information

EnvoyFilter config

````
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  namespace: my-namespace
  name: ingressgateway-public-gzip
spec:
  workloadSelector:
    labels:
      app: ingressgateway-public
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.compressor
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor
            response_direction_config:
              common_config:
                min_content_length: 100
                content_type:
                  - application/javascript
                  - application/json
                  - application/xhtml+xml
                  - image/svg+xml
                  - text/css
                  - text/html
                  - text/plain
                  - text/xml
            compressor_library:
              name: text_optimized
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.compression.gzip.compressor.v3.Gzip
                memory_level: 6
                window_bits: 10
                compression_level: BEST_COMPRESSION
                compression_strategy: DEFAULT_STRATEGY
````
