### ISSUE TITLE
can not change bootstrap in envoy gateway using envoyfilter

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#40080]
### Bug Description

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ef-bootstrap
spec:
  workloadSelector:
    labels:
      istio: ingressgateway 
  configPatches:
  - applyTo: BOOTSTRAP
    patch:
      operation: MERGE
      value:
        static_resources:
          listeners:
          - address:
              socket_address:
                address: 0.0.0.0
                port_value: 12111
            traffic_direction: INBOUND
            filter_chains:
            - filters:
              -   name: envoy.filters.network.http_connection_manager
                  typedConfig:
                    '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    stat_prefix: "bookinfo"
                    route_config:
                      name: test
                      virtual_hosts:
                      - name: test
                        domains:
                        - "*"
                        routes:
                        - name: testroute
                          match: 
                            prefix: /
                          direct_response:
                            status: 200
                            body: 
                              inline_string: "prefix" 
                    http_filters:
                    - name: "envoy.filters.http.router"
                      typed_config:
                        "@type": "type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"
```

above config can not change bootstrap config in gateway

### Version

```prose
[root@node01 ~]# istioctl version
client version: 1.14.1
control plane version: 1.14.1
data plane version: 1.14.1 (20 proxies)
[root@node01 ~]# kubectl version --short
Client Version: v1.21.0
Server Version: v1.21.0
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
