### ISSUE TITLE
Provided name for static registration lookup was empty.

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#40081]
### Bug Description

2022-07-23T08:18:21.198346Z     error   envoy envoy_bug envoy bug failure: false. Details: Using a removed guard envoy.reloadable_features.experimental_matching_api. In future version of Enovy this will be treated as invalid configuration
2022-07-23T08:18:21.247794Z     critical        envoy main      error initializing configuration 'etc/istio/proxy/envoy-rev0.json': Provided name for static registration lookup was empty.
Provided name for static registration lookup was empty.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ef-bootstrap
spec:
  workloadSelector:
    labels:
      app: productpage
  configPatches:
  - applyTo: BOOTSTRAP
    patch:
      operation: MERGE
      value:
          watchdogs:
            main_thread_watchdog:
              actions:
              - event: KILL
              - event: MULTIKILL
              - event: MEGAMISS
              - event: MISS
              miss_timeout: 30s
              megamiss_timeout: 20s
              kill_timeout: 10s
              max_kill_timeout_jitter: 20s
              multikill_timeout: 20s
              multikill_threshold: 
                value: 70
            worker_watchdog:
              actions:
              - event: KILL
              - event: MULTIKILL
              - event: MEGAMISS
              - event: MISS
              miss_timeout: 30s
              megamiss_timeout: 20s
              kill_timeout: 10s
              max_kill_timeout_jitter: 20s
              multikill_timeout: 20s
              multikill_threshold: 
                value: 70
```

### Version

```prose
[root@node01 ~]# istioctl version
client version: 1.14.1
control plane version: 1.14.1
data plane version: 1.14.1 (20 proxies)

[root@node01 ~]# kubectl version --short
Client Version: v1.21.0
Server Version: v1.21.0
```
