### ISSUE TITLE
Virtual service retry not getting set to 0 or any other value

### ISSUE THREAD

**Issue by anand-bidwalkar** [istio/istio#40091]
### Bug Description

Hi Team,

We see an unexpected behavior with one of our Go-based services, it is calling another service 2x times without any retry logic in the application. On further debugging, we found ISTIO has default retried 2 times on Virtual Service. We tried to disable it by adding retries: attempts: 0 to virtual service but this value is not set to 0. Could you please advice on what could be wrong here. Below is the virtual service being used. Thanks

```
apiVersion: networking.istio.io/v1alpha3                                                                                                            
kind: VirtualService                                                                                                                                
metadata:                                                                                                                                           
  name: betaservice                                                                                                                               
  namespace: testing                                                                                                                               
  labels:                                                                                                                                           
    app: betaservice                                                                                                                              
spec:                                                                                                                                               
  hosts:                                                                                                                                            
  - betaservice-testing.gcpnp.anz                                                                                                                 
  gateways:                                                                                                                                         
  - ingress/global-gateway                                                                                                                          
  http:                                                                                                                                             
  - route:                                                                                                                                          
    - destination:                                                                                                                                  
        host: betaservice-blue.testing.svc.cluster.local                                                                                          
        port:                                                                                                                                       
          number: 8080                                                                                                                              
    retries:  
        attempts: 0  
```

Envoy proxy config from POD
```
{
        "name": "betaservice-blue.testing.svc.cluster.local:8080",
        "domains": [
         "betaservice-blue.testing.svc.cluster.local",
         "betaservice-blue.testing.svc.cluster.local:8080",
         "betaservice-blue",
         "betaservice-blue:8080",
         "betaservice-blue.testing.svc.cluster",
         "betaservice-blue.testing.svc.cluster:8080",
         "betaservice-blue.testing.svc",
         "betaservice-blue.testing.svc:8080",
         "betaservice-blue.testing",
         "betaservice-blue.testing:8080",
        ],
        "routes": [
         {
          "match": {
           "prefix": "/"
          },
          "route": {
           "cluster": "outbound|8080||betaservice-blue.testing.svc.cluster.local",
           "timeout": "0s",
           "retry_policy": {
            "retry_on": "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes",
            "num_retries": 2,
            "retry_host_predicate": [
             {
              "name": "envoy.retry_host_predicates.previous_hosts"
             }
            ],
            "host_selection_retry_max_attempts": "5",
            "retriable_status_codes": [
             503
            ]
           },
           "max_grpc_timeout": "0s"
          },
          "decorator": {
           "operation": "betaservice-blue.testing.svc.cluster.local:8080/*"
          },
          "name": "default"
         }
        ],
        "include_request_attempt_count": true
       },    
```
### Version

```prose
istioctl version
client version: 1.13.3
control plane version: 1.13.3
data plane version: 1.13.3 (20 proxies)

k version --short
Client Version: v1.21.13
Server Version: v1.21.12-gke.1500
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by hzxuzhonghu** [comment]
The vs applied only to the gateway. Did you dump from a workload pod?

**Comment by anand-bidwalkar** [comment]
@hzxuzhonghu Yes, this dump is from the workload pod. I did try the suggestion listed in this issue to add mesh in the gateway list but that didn't help. https://github.com/istio/istio/issues/37181#issuecomment-1085900928

**Comment by zirain** [comment]
where did you dump the configs, the ingressgateway pod?

**Comment by zirain** [comment]
if you want disable retries for mesh inside traffic, try the following yaml:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: betaservice
  namespace: testing
  labels:
    app: betaservice
spec:
  hosts:
    - betaservice-testing.gcpnp.anz
  gateways:
    - mesh # add this
    - ingress/global-gateway
  http:
    - route:
        - destination:
            host: betaservice-blue.testing.svc.cluster.local
            port:
              number: 8080
      retries:
        attempts: 0
```

**Comment by anand-bidwalkar** [comment]
Thank you @zirain . I tried this configuration by adding mesh to the gateway list, but the retry behavior remains the same. 

The above dump was from the service workload. Our application team is seeing this behavior for 503 error on UI,
UI (1 Outbound Call) ---> Service A (3 Outbound Call) ---> Service B (9 Outbound Call) ---> Service C (outside mesh)

Ideally, Service C should receive only 1 inbound call, but it receives 9 inbound calls. There is no retry mechanism in the application. We disabled the retries on UI, Service A, and Service B virtual services with mesh as the gateway, but the workload config dump route still shows num_retries=2. How could we disable / set value of num_retries=0? We want to understand why requests are getting multiplied on GKE for 503 error.

I would highly appreciate it if you could point us in the right direction.

**Comment by anand-bidwalkar** [comment]
@zirain / @hzxuzhonghu  - We also tried to set num_retries to 0 with below Envoy Filter, but the minimum value it set to is 1. If we pass num_retries it is set to 2. could you please suggest what's wrong here.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: retry-basic-node
  namespace: staging
spec:
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: ANY
      routeConfiguration:
        vhost:
          name: 'basic-node-green.staging.svc.cluster.local:8080'
          route:
            name: 'default'
       
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": type.googleapis.com/envoy.config.route.v3.RouteAction
        route:
          retry_policy:
            num_retries: 0
```
