### ISSUE TITLE
basic auth wasm extension fails to load

### ISSUE THREAD

**Issue by alpatil** [istio/istio#40103]
### Bug Description

We have a kubernetes application with nginx ingress controller 1.1.1 in default namespace that has [basic auth enabled](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/) and services a backend service in same namespace. 

Basic auth stops working as soon as we set peerauthentication to STRICT. curl to the endpoint with basic auth creds work, but browser times out (in STRICT mode). If we set peerauthentication to PERMISSIVE, both curl and browser can access endpoint using basic auth. (We don't use istio ingress gateway in our environment)

After looking at [this](https://github.com/istio/istio/issues/4693) issue, It seems basic auth with Istio is not supported OOTB. If I understand correctly, we need to install [basic auth wasm extension](https://istio.io/latest/docs/tasks/extensibility/wasm-module-distribution/) to make it work.  I am not able to install this extension . It fails to load with below error.

### Version

```prose
$ istioctl version
client version: 1.13.2
control plane version: 1.13.2
data plane version: 1.13.2 (23 proxies)

$ istioctl version --short
client version: 1.13.2
control plane version: 1.13.2
data plane version: 1.13.2 (23 proxies)
```

### Additional Information

Tried to add basic auth wasm extension:
```
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: basic-auth
  namespace: default 
spec:
  selector:
    matchLabels:
      k8s-app: ingress-controller
  url: oci://ghcr.io/istio-ecosystem/wasm-extensions/basic_auth:1.12.0
  phase: AUTHN
  pluginConfig:
    basic_auth_rules:
      - credentials:
          - "YWRtaW46Y2hhbmdlbWU="
  ```

Seeing below error in ingress controller sidecar proxy
```
istio-proxy 2022-07-25T19:21:44.568851Z	debug	envoy filter	Updating filter config default.basic-auth
istio-proxy 2022-07-25T19:21:44.569789Z	critical	envoy wasm	Plugin configured to fail closed failed to load
istio-proxy 2022-07-25T19:21:44.569799Z	critical	envoy wasm	Plugin configured to fail closed failed to load
istio-proxy 2022-07-25T19:21:44.569808Z	critical	envoy wasm	Plugin configured to fail closed failed to load
istio-proxy 2022-07-25T19:21:44.569895Z	warning	envoy config	gRPC config for type.googleapis.com/envoy.config.core.v3.TypedExtensionConfig rejected: Unable to create Wasm HTTP filter default.basic-auth
istio-proxy 2022-07-25T19:21:44.569905Z	debug	envoy filter	Updating filter config default.basic-auth failed due to 2
```

peerauthentication is set to strict

```
$ k get peerauthentication -A
NAMESPACE   NAME      MODE     AGE
default     default   STRICT   43m
```

Backend service Ingress annotation:
```
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/upstream-vhost: [service-name].default.svc.cluster.local
```

nginx deployment annotation:
```
        traffic.sidecar.istio.io/excludeInboundPorts: "443"
        traffic.sidecar.istio.io/includeInboundPorts: ""
```

pods:
```
$ k get pods
NAME                                                 READY   STATUS    RESTARTS   AGE
default-http-backend-default-74d4bf74ff-bzs7z        2/2     Running   0          4d23h
default-http-backend-default-74d4bf74ff-pghts        2/2     Running   0          4d23h
default-http-backend-default-74d4bf74ff-vhshl        2/2     Running   0          4d23h
ingress-controller-default-747b75644b-zc99q   2/2     Running   0          4d3h
manager-console-7c8cf9d86-r9v7l               2/2     Running   0          4d23h
```

**Comment by zirain** [comment]
I can reproduce this with a invalid config, according to the [demo](https://istio.io/latest/docs/tasks/extensibility/wasm-module-distribution/) and [source code](https://github.com/istio-ecosystem/wasm-extensions/tree/master/extensions/basic_auth), looks like you parse a invalid config for that wasm filter?

```console
2022-07-27T03:58:09.571482Z	warning	envoy wasm	wasm log: [extensions/basic_auth/plugin.cc:306]::configure() cannot parse plugin configuration JSON string: {"basic_auth_rules":{"credentials":["ok:test","YWRtaW4zOmFkbWluMw=="]}}
2022-07-27T03:58:09.571528Z	warning	envoy wasm	wasm log: [extensions/basic_auth/plugin.cc:282]::onConfigure() configuration has errors initialization will not continue.
2022-07-27T03:58:09.571531Z	error	envoy wasm	Wasm VM failed Failed to configure base Wasm plugin
2022-07-27T03:58:09.571956Z	critical	envoy wasm	Plugin configured to fail closed failed to load

```

**Comment by alpatil** [comment]
Thanks @zirain - I fixed config. Here's correct config:

```
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: basic-auth
  namespace: default
spec:
  selector:
    matchLabels:
      k8s-app: ingress-controller
  url: oci://ghcr.io/istio-ecosystem/wasm-extensions/basic_auth:1.12.0
  phase: AUTHN
  pluginConfig:
    basic_auth_rules:
      - prefix: "/"
        request_methods:
          - "GET"
          - "POST"
        credentials:
          - "YWRtaW46Y2hhbmdlbWU="
```

and I see basic-auth filter getting initialized:
```
istio-proxy 2022-07-27T17:28:17.279406Z	debug	envoy init	init manager Listener-local-init-manager virtualInbound 5271443287616388656 initializing shared target FilterConfigSubscription init default.basic-auth
```

But when I try to access the url from browser, it does not prompt me for any credentials (same behavior with curl) . The request just goes through without any authentication. Am I missing some configuration?

```
istio-proxy ':status', '200'
istio-proxy 'x-powered-by', 'Express'
istio-proxy 'access-control-allow-origin', '*'
istio-proxy 'accept-ranges', 'bytes'
istio-proxy 'cache-control', 'public, max-age=0'
istio-proxy 'etag', 'W/"29566-181f39ca3d0"'
istio-proxy 'content-type', 'text/html; charset=UTF-8'
istio-proxy 'x-envoy-upstream-service-time', '2'
istio-proxy 'server', 'envoy'
```

**Comment by alpatil** [comment]
After doing some more research, it seems basic auth wasm extension works only with istio ingress gateway. It's not designed to work with nginx ingress controller. Can someone confirm this statement is correct?

**Comment by zirain** [comment]
cc @kyessenov can you confirm that?

**Comment by alpatil** [comment]
Hi @kyessenov - can we confirm basic auth wasm extension works only with istio ingress gateway and not with nginx ingress controller?

**Comment by kyessenov** [comment]
Yes, I wouldn't expect nginx to be able to run Wasm, but I don't follow nginx development. Istio relies on Envoy Wasm support.

**Comment by 0width** [comment]
this is working
`apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sleep
spec:
  hosts:
  - sleep.local.k8s
  gateways:
    - sleep
  http:
  - match:
    - uri:
        prefix: /sleep
      headers:
        Authorization:
          exact: "Basic YWRtaW46MTIzNDU2"
    route:
      - destination:
          host: sleep
          port:
            number: 5000
    timeout: 3s
  - match:
    - uri:
        prefix: /sleep
    directResponse:
      status: 401
    headers:
      response:
        set:
          Www-Authenticate: 'Basic realm="Authentication Required"'`

**Comment by 0width** [comment]
This is working
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sleep
spec:
  hosts:
  - sleep.local.k8s
  gateways:
    - sleep
  http:
  - match:
    - uri:
        exact: /sleep
      headers:
        Authorization:
          exact: "Basic YWRtaW46MTIzNDU2"
    route:
      - destination:
          host: sleep
          port:
            number: 5000
    timeout: 3s
  - match:
    - uri:
        exact: /sleep
    directResponse:
      status: 401
    headers:
      response:
        set:
          Www-Authenticate: 'Basic realm="Authentication Required"'
```
