### ISSUE TITLE
Fetching routes via RDS (route_configuration_name) is not supported with inline scoped routes.

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#40111]
### Bug Description

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: httpconnectionmanager
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        portNumber: 8080
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
              name: envoy.filters.network.http_connection_manager
              typedConfig:
                '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                scoped_routes:
                  name: test
                  scope_key_builder:
                    fragments:
                    - header_value_extractor:
                        name: X-Header
                        element_separator: ";"
                        index: 0
                        element:
                          separator: "="
                          key: test
                  rds_config_source:
                    ads: {}
                    initialFetchTimeout: 10s
                    resourceApiVersion: V3
                  scoped_route_configurations_list:
                    scoped_route_configurations:
                    - on_demand: true
                      name: test1
                      route_configuration_name: "http.8080"
                      key:
                        fragments:
                        - string_key: test1
                    - on_demand: true
                      name: test2
                      route_configuration_name: "http.8081"
                      key:
                        fragments:
                        - string_key: test2
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        portNumber: 8080
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value: 
        name: envoy.filters.http.on_demand
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.on_demand.v3.OnDemand
```

this config has follow errors:
Fetching routes via RDS (route_configuration_name) is not supported with inline scoped routes.

### Version

```prose
[root@node01 on_demand]# istioctl version
client version: 1.14.1
control plane version: 1.14.1
data plane version: 1.14.1 (18 proxies)

[root@node01 on_demand]# kubectl version --short
Client Version: v1.21.0
Server Version: v1.21.0
```
