### ISSUE TITLE
support CIDR range Istio Authorization policy for request header 

### ISSUE THREAD

**Issue by chiranjeevivarma3** [istio/istio#40131]
I am using istio authorization policy for IP whitelisting. I have an issue with the existing environment where the x-forwarded-for header has a complete hop of IPs
example:
x-forwarded-for:  client ip, front door IP ,service ip

I am unable to complete my requirement with ipBlock and remoteIpBlock. so I am using request. header rule. I have created a manifest shown below

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ingress-policy
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  action: ALLOW
  rules:
  - when:
     - key: request.headers[x-azure-socket]
       values: 
       -  x.x.x.x
       -  x.x.x.x
```

It's works for external traffic. But i have issue with internal traffic which is cluster-to-cluster communication. so have to use a multiply istio authorization policy with a different header. if any internal traffic passes the istio ingress gateway the x-forwarded-for has a single IP. I don't see x-azure-socket for internal traffic.

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ingress-policy
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  action: ALLOW
  rules:
  - when:
     - key: request.headers[x-forwarded-for]
       values: 
       -  x.x.x.x
       -  x.x.x.x
```
I have tried creating a custom header with envoyfilter. I am not sure anything wrong I did on envoyfilter which is shown below
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ingressgateway-user-ip
  namespace: ingress
spec:
  workloadLabels:
    app: istio-ingressgateway
  filters:
    - listenerMatch:
        portNumber: 443
        listenerType: ANY
      filterName: envoy.lua
      filterType: HTTP
      filterConfig:
        inlineCode: |
          function envoy_on_request(request_handle)
            local xff_header = request_handle:headers():get("X-Forwarded-For")
            local client_ip = string.gmatch(xff_header, "(%d+.%d+.%d+.%d+)")();
            request_handle:headers():add("X-Custom-User-IP", first_ip);
          end
```
It's creating a custom header as expected after adding custom access logs. but when i try to create istio authorization policy with my custom header. It's not working and in logs shows - (null)

So I have decided to use a multiple istio authorization policy for internal and external traffic. But now I see the request. header rule doesn't support CIDR and as well as TCP protocol.
