### ISSUE TITLE
thrift_proxy route match servicename not effective 

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#40133]
### Bug Description

ef-match-service_name.yaml

kubectl apply -f  ef-match-service_name.yaml -n istio-system

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: thrift-sample-server
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        name: 10.68.153.249_9090    # sed -i .bak "s/\${thrift-sample-server-vip}/`kubectl get svc thrift-sample-server -n thrift -o=jsonpath='{.spec.clusterIP}'`/" istio/envoyfilter-thrift-proxy.yaml
        filterChain:
          filter:
            name: "envoy.filters.network.tcp_proxy"
    patch:
      operation: REPLACE
      value:
        name: envoy.filters.network.thrift_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.thrift_proxy.v3.ThriftProxy
          stat_prefix: "outbound|9090||thrift-sample-server.thrift.svc.cluster.local"
          transport: AUTO_TRANSPORT
          protocol: AUTO_PROTOCOL
          thrift_filters:
          - name: envoy.filters.thrift.router
          route_config:
            routes:
            - match:
                method_name: ""
                service_name: "org.aeraki.HelloService"
              route:
                cluster: "outbound|9090|v2|thrift-sample-server.istio.svc.cluster.local"
  - applyTo: NETWORK_FILTER
    match:
      listener:
        name: virtualInbound
        filterChain:
          destinationPort: 9090
          filter:
            name: "envoy.filters.network.tcp_proxy"
    patch:
      operation: REPLACE
      value:
        name: envoy.filters.network.thrift_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.thrift_proxy.v3.ThriftProxy
          stat_prefix: inbound|9090||
          transport: AUTO_TRANSPORT
          protocol: AUTO_PROTOCOL
          thrift_filters:
          - name: envoy.filters.thrift.router
          route_config:
            routes:
            - match:
                method_name: ""
                service_name: "org.aeraki.HelloService"
              route:
                cluster: inbound|9090||
```

when servicename is empty ,it is ok,but if I configured a servciename:
Connected to thrift-sample-server
org.apache.thrift.TApplicationException: no route for method 'sayHello'
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:79)
        at org.aeraki.HelloService$Client.recv_sayHello(HelloService.java:85)
        at org.aeraki.HelloService$Client.sayHello(HelloService.java:72)
        at org.aeraki.HelloClient.main(HelloClient.java:44)

### Version

```prose
[root@node01 thrift]# istioctl version
client version: 1.14.1
control plane version: 1.14.1
data plane version: 1.14.1 (25 proxies)

[root@node01 thrift]# kubectl version --short
\Client Version: v1.21.0
Server Version: v1.21.0
```
