### ISSUE TITLE
  failed to marshal bootstrap as JSON: proto: not found

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#40139]
### Bug Description

ef-wasm-stats_sink.yaml

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: wasm
spec:
  workloadSelector:
    labels:
      app: productpage
  configPatches:
  - applyTo: BOOTSTRAP
    patch:
      operation: MERGE
      value:
          stats_sinks:
          - name: envoy.stat_sinks.wasm
            typed_config:
                "@type": type.googleapis.com/envoy.extensions.stat_sinks.wasm.v3.Wasm
                config:
                  name: my_plugin
                  configuration:
                    "@type": type.googleapis.com/google.protobuf.StringValue
                    value: |
                      {}
                  vm_config:
                    runtime: "envoy.wasm.runtime.v8"
                    code:
                      local:
                        filename: /var/local/lib/wasm-filters/main.wasm
```

 failed to marshal bootstrap as JSON: proto: not found

### Version

```prose
[root@node01 wasm]# istioctl version
client version: 1.14.1
control plane version: 1.14.1
data plane version: 1.14.1 (21 proxies)
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
