### ISSUE TITLE
Istio JWT validation happens even if RequestAuthentication is not applied to the workload

### ISSUE THREAD

**Issue by romanwozniak** [istio/istio#40141]
### Context:
I have two `httpbin` deployments under `foo` namespace:
1. `httpbin` – deployed with the sidecar proxy
2. `httpbin-no-auth` – deployed without sidecar proxy

I also configured `RequestAuthentication` to be applied to the `httpbin` workload:
```yaml
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:  
  name: jwt-example
  namespace: foo  
spec:
  selector:
    matchLabels:
      app: httpbin
  jwtRules:
  - issuer: https://accounts.google.com
```

Now, I want to create a `VirtualService`, which will route requests to `httpbin` if the `x-use-auth: true` header is present, or otherwise, route requests to `httpbin-no-auth`:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:  
  name: httpbin
  namespace: foo  
spec:  
  gateways:
  - httpbin
  - mesh
  hosts:
  - httpbin.foo.svc.cluster.local
  http:
  - match:
    - headers:
        x-use-auth:
          exact: 'true'
    route:
    - destination:
        host: httpbin.foo.svc.cluster.local
        port:
          number: 8000
  - route:
    - destination:
        host: httpbin-no-auth.foo.svc.cluster.local
        port:
          number: 8000
```

I also have a `Gateway` to pass the ingress traffic to the mesh:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: httpbin
  namespace: foo
spec:  
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - '*'
```

### Expected Behaviour:
```shell
~ curl -H 'Host: httpbin.foo.svc.cluster.local' -H "x-use-auth: true" -H "Authorization: Bearer invalid.token" http://${INGRESS_IP}/ip -v
<redacted>
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< www-authenticate: Bearer realm="http://httpbin.foo.svc.cluster.local/ip", error="invalid_token"
<
Jwt is not in the form of Header.Payload.Signature with two dots and 3 sections%
```

```shell
~ curl -H 'Host: httpbin.foo.svc.cluster.local' -H "Authorization: Bearer invalid.token" http://${INGRESS_IP}/ip -v
<redacted>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
<
{
  "origin": "<ip_address>"
}
```

### Actual Behaviour:
```shell
~ curl -H 'Host: httpbin.foo.svc.cluster.local' -H "Authorization: Bearer invalid.token" http://${INGRESS_IP}/ip -v
<redacted>
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< www-authenticate: Bearer realm="http://httpbin.foo.svc.cluster.local/ip", error="invalid_token"
<
Jwt is not in the form of Header.Payload.Signature with two dots and 3 sections%
```

### Details:
The reason I'm trying to achieve described behaviour is because I have a legacy version of an API service, which is using OAuth2 `access_token` for authentication. Now, I want to migrate this service to OIDC with JWT, without changing hostname/path under which this API is accessible.

### Version

```prose
➜  ~ istioctl version
client version: 1.14.1
control plane version: 1.13.3
data plane version: 1.13.3 (2 proxies)

➜  ~ k version --short
Client Version: v1.23.3
Server Version: v1.22.8-gke.202
```

**Comment by ramaraochavali** [comment]
I suspect the `httpbin-no-auth.foo.svc.cluster.local` is selecting the same set of pods as `httpbin.foo.svc.cluster.local`

**Comment by romanwozniak** [comment]
> I suspect the `httpbin-no-auth.foo.svc.cluster.local` is selecting the same set of pods as `httpbin.foo.svc.cluster.local`

Thanks @ramaraochavali, but this is definitely not the case:
```shell
➜  ~ k get pods -l app=httpbin -n foo
NAMESPACE   NAME                      READY   STATUS    RESTARTS   AGE
foo         httpbin-bbcc89bd6-4z9pq   2/2     Running   0          9d

➜  ~ k get pods -l app=httpbin-no-auth -n foo
NAMESPACE   NAME                               READY   STATUS    RESTARTS   AGE
foo         httpbin-no-auth-5bb8b68879-ch76c   1/1     Running   0          5h9m
```

**Comment by romanwozniak** [comment]
Hi @howardjohn, thanks for looking into this. As I mentioned, `httpbin` is deployed with the sidecar proxy, which I can't see in your posted manifests. If the sidecar is not ingected, then there is no workload matching label `app: httpbin`, hence there will be no JWT validation at all, but this is not I'm looking for.

Here is the manifest of `httpbin` deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: foo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: httpbin
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: httpbin
        kubectl.kubernetes.io/default-logs-container: httpbin
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "15020"
        prometheus.io/scrape: "true"
        sidecar.istio.io/status: '{"initContainers":["istio-init"[],"containers":["istio-proxy"[],"volumes":["istio-envoy","istio-data","istio-podinfo","istio-token","istiod-ca-cert"[],"imagePullSecrets":null,"revision":"default"}'
      creationTimestamp: null
      labels:
        app: httpbin
        security.istio.io/tlsMode: istio
        service.istio.io/canonical-name: httpbin
        service.istio.io/canonical-revision: v1
        version: v1
    spec:
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - proxy
        - sidecar
        - --domain
        - $(POD_NAMESPACE).svc.cluster.local
        - --proxyLogLevel=warning
        - --proxyComponentLogLevel=misc:error
        - --log_output_level=default:info
        - --concurrency
        - "2"
        env:
        - name: JWT_POLICY
          value: third-party-jwt
        - name: PILOT_CERT_PROVIDER
          value: istiod
        - name: CA_ADDR
          value: istiod.istio-system.svc:15012
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.serviceAccountName
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: PROXY_CONFIG
          value: |
            {}
        - name: ISTIO_META_POD_PORTS
          value: |-
            [
                {"containerPort":80}
            ]
        - name: ISTIO_META_APP_CONTAINERS
          value: httpbin
        - name: ISTIO_META_CLUSTER_ID
          value: Kubernetes
        - name: ISTIO_META_INTERCEPTION_MODE
          value: REDIRECT
        - name: ISTIO_META_MESH_ID
          value: cluster.local
        - name: TRUST_DOMAIN
          value: cluster.local
        image: docker.io/istio/proxyv2:1.13.3
        imagePullPolicy: IfNotPresent
        name: istio-proxy
        ports:
        - containerPort: 15090
          name: http-envoy-prom
          protocol: TCP
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /healthz/ready
            port: 15021
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            cpu: "2"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 1337
          runAsNonRoot: true
          runAsUser: 1337
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/secrets/istio
          name: istiod-ca-cert
        - mountPath: /var/lib/istio/data
          name: istio-data
        - mountPath: /etc/istio/proxy
          name: istio-envoy
        - mountPath: /var/run/secrets/tokens
          name: istio-token
        - mountPath: /etc/istio/pod
          name: istio-podinfo
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - istio-iptables
        - -p
        - "15001"
        - -z
        - "15006"
        - -u
        - "1337"
        - -m
        - REDIRECT
        - -i
        - '*'
        - -x
        - ""
        - -b
        - '*'
        - -d
        - 15090,15021,15020
        image: docker.io/istio/proxyv2:1.13.3
        imagePullPolicy: IfNotPresent
        name: istio-init
        resources:
          limits:
            cpu: "2"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsGroup: 0
          runAsNonRoot: false
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1337
      serviceAccount: httpbin
      serviceAccountName: httpbin
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          medium: Memory
        name: istio-envoy
      - emptyDir: {}
        name: istio-data
      - downwardAPI:
          defaultMode: 420
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels
            path: labels
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations
            path: annotations
        name: istio-podinfo
      - name: istio-token
        projected:
          defaultMode: 420
          sources:
          - serviceAccountToken:
              audience: istio-ca
              expirationSeconds: 43200
              path: istio-token
      - configMap:
          defaultMode: 420
          name: istio-ca-root-cert
        name: istiod-ca-cert
```
