### ISSUE TITLE
When DNS_CAPTURE and DNS_AUTO_ALLOCATION are both set, MESH_EXTERNAL ServiceEntries not behaving as expected.

### ISSUE THREAD

**Issue by yannuil** [istio/istio#40166]
### Bug Description

With `ISTIO_META_DNS_CAPTURE` and `ISTIO_META_DNS_AUTO_ALLOCATION` set and  `meshConfig.outboundTrafficPolicy.mode` option is set to ALLOW_ANY, I applied two `MESH_EXTERNAL` ServiceEntries with the identical host `istio.io` but each is with port 80 and 443 respectively. The TLS request failed to route to outside world.  

I tried to add an [integration test](https://github.com/istio/istio/pull/40165/files#diff-91d3a4d4b1dbb152f3252fdf141f1e0841c6517647d0af66115a8b5d87d58fba) in this [PR](https://github.com/istio/istio/pull/40165) to illustrate the problem. 

### Version

```prose
$ kubectl version --short
Client Version: v1.24.3
Kustomize Version: v4.5.4
Server Version: v1.24.0
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by yannuil** [comment]
When defining same service entry as existing one, a new is created instead of acknowledging that it exists.
In addition this breaks use on the service entry.

How to reproduce
1. If I create a ServiceEntry with the host "istio.io" and port number, protocol, name : 443, HTTPS, https. An Envoy Listener with the following VIP is created : 240.240.0.1. I can curl the following URL: "https://istio.io", the VIP used to establish the connection is 240.240.0.1.

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-https
spec:
  hosts:
  - istio.io
  location: MESH_EXTERNAL
  ports:
  - number: 443 
    name: https
    protocol: HTTPS
  resolution: DNS
```

2. If I create another ServiceEntry with the host "istio.io" and port number, protocol, name : 80, HTTP, http. An Envoy Listener with the following VIP is created : 240.240.0.2. I can curl the following URL : http://istio.io/", the VIP used to establish the connection is 240.240.0.2. I can not curl the following URL : "https://istio.io" anymore.  The VIP used to establish the connection is 240.240.0.2. It seems to be the one associated with the HTTP protocol.

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-http
  namespace: istio-dp
spec:
  hosts:
  - istio.io
  location: MESH_EXTERNAL
  ports:
  - number: 80 
    name: http
    protocol: HTTP
  resolution: DNS
```


Expected behavior:

When defining two service entry in the same namespace, both should be reachable under [`ALLOW_ANY`](https://istio.io/latest/docs/tasks/traffic-management/egress/egress-control/#envoy-passthrough-to-external-services).
