### ISSUE TITLE
serviceEntry max cluster count capped at ~300

### ISSUE THREAD

**Issue by taitelman** [istio/istio#40167]
### Bug Description

using istio v1.13+
I notice that if I create many similar SE (different names ,same url), the code will "choke" and refuse to create new SE after ~300 instances. (sometimes 250, sometime 350). Deleting the 300 SE will allow to create new ones.

```
for counter in {0..400}; do
 
cat << EOF > se.yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: rule-${counter}
  namespace: myNS
spec:
  hosts:
  - api.a.b.com
  ports:
  - name: https-9341
    number: 9341
    protocol: HTTPS
  resolution: DNS
EOF
kubectl apply -f se.yaml

done
```

OK, I get it. there is some undocumented limit but here comes the bug:
not only you can’t create new SE , the port in question (this example is port 9341) will get blocked if using REGISTRY_ONLY egress policy. outgoing traffic is blocked until you free some old “9341” SE’s.
we need some clear error log in the istiod logs or somewhere...
I know that many of the istio users will not even get near that SE count. 
and I changed the way I create SE to aggregate ports and check duplicates BEFORE creating new SE. but still ... a low prio bug.
maybe even just an `istioctl analyze` warning ?

### Version

```prose
$ kubectl  version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.21.14+IKS


$ istioctl version
client version: 1.13.3
control plane version: 1.13.5
data plane version: 1.13.5 (1391 proxies)
```
```


### Additional Information

_No response_
