### ISSUE TITLE
WasmPlugin: my wasm file does not shown in Envoy config dump output

### ISSUE THREAD

**Issue by masquee** [istio/istio#40172]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

I tried a WasmPlugin demo

```
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: httpbin-rate-limiting
  namespace: demo
spec:
  selector:
    matchLabels:
      app: httpbin
  url: oci://ghcr.io/tetratelabs/wasm-rate-limiting:v1
```

and **it works**. But I cannot found where is the configuration in Envoy config dump corresponding to the istio wasmplugin shown above. I only found the config 

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/8470824/181753063-f1621b23-e201-4cc0-ac0b-7c324ccb6492.png">
 

I wonder how Envoy known where is my .wasm？The config dump output seems have no information about this.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
