### ISSUE TITLE
Service Entry not working

### ISSUE THREAD

**Issue by Arclight3** [istio/istio#40190]
### Bug Description

I am trying to achieve this scenario:

- From an application within the mesh I connect to this host: "external-mq" and port: 1414
- "external-mq" is a Service Entry that should register in the mesh the service located here: "dev-mq.mycompany.corp"

This is my solution, but it's not working:
```yml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-mq
  labels:
    app: external-mq
spec:
  hosts:
    - dev-mq.mycompany.corp
  location: MESH_EXTERNAL
  ports:
  - number: 1414
    name: tcp-mq
    protocol: TCP
  resolution: DNS
---
# I am using a Virtual Service to redirect traffic from the host "external-mq" to host "dev-mq.mycompany.corp"
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: external-mq-service
spec:
  hosts:
  - external-mq
  http:
  - match:
    - port: 1414
    route:
    - destination:
        host: dev-mq.mycompany.corp
        port:
          number: 1414
```
The external service that I am trying to use is an IBM MQ instance.
It's exposed at this DNS: dev-mq.mycompany.corp and port: 1414.

If inside my application (that runs inside the mesh) I use the DNS, it works to connect to the service, but as I said I want to use the host: "external-mq" not the DNS.
My end goal is to setup network resilience features (reties, timeouts, etc) on top of the Service Entry "external-mq".

I tried to follow Istio's documentation to setup a ServiceEntry but either the documentation is poor, either I am a muggle.. Maybe both..

### Version

```prose
# istioctl version:
client version: 1.14.1
control plane version: 1.14.1
data plane version: 1.14.1 (3 proxies)

# kubectl version:
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.24.0
```

**Comment by hzxuzhonghu** [comment]
external-mq is not the hostname defined by you, it is `dev-mq.mycompany.corp`

**Comment by Arclight3** [comment]
But I have that virtual service that is supposed to redirect traffic from "external-mq" to "dev-mq.mycompany.corp".
So if I connect to "external-mq" from an application inside the mesh, I expect the traffic to reach "dev-mq.mycompany.corp".

Please let me know what part of this design I misunderstood.

Also, in case its not possible to achieve this setup using Istio, what the recommened approach? How should my service entry look like, what host should I call in my application, and how should the virtual service look like to add fault handling for the external service ( retry, timeout, etc).

Thanks!

**Comment by aryan16** [comment]
`external-mq` host name is not defined/exposed anywhere. You need a ingress gateway which exposes this hostname (try changing it to `external-mq.com`, it requires FQDN). Setup the Ingress host, port from here - https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-control/#determining-the-ingress-ip-and-ports

eg ingress - 
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "external-mq.com"
```

eg VS - 
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - "external-mq.com"
  gateways:
  - httpbin-gateway
  http:
  - match:
    - port: 1414
    route:
    - destination:
        host: dev-mq.mycompany.corp
EOF
```

After this when you make a curl like `curl -s -I -HHost:external-mq.com "http://$INGRESS_HOST:$INGRESS_PORT/200"`, it should pass.

**Comment by Arclight3** [comment]
@aryan16 I don't want to define this host in an ingress gateway.
I don't want to expose it externally for other external apps to call it through my mesh.

The host "external-mq" is supposed to be called only by apps that are inside the mesh.
This host "external-mq" is supposed to be just an alias for an external application.

if this application would have been part of the mesh, I would only have to create a Service to expose it to other applications inside the mesh:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: internal-mq
spec:
  selector:
    app.kubernetes.io/name: MyMQ
  ports:
    - protocol: TCP
      port: 1414
      targetPort: 9376
```
and now I can use the host: "internal-mq" to call this service from other apps in the mesh.

I want to achieve exactly the same thing for my external service!
How can I do it?

The only difference from the example above is that the application behind the "external-mq" host is outside the mesh.
That's where I thought ServiceEntry and Virtual Service comes into play and makes the connection.
