### ISSUE TITLE
Support set based label selector in Destinationrules

### ISSUE THREAD

**Issue by zijianz** [istio/istio#40238]
**Describe the feature request**
Destinationrules supports only Equality-based label selector. Can we have Set Based label selector as well? 
This would be useful when we want to exclude some workloads temporarily or to provide an OR(||) relationship among multiple criteria.    

**Affected product area (please put an X in all that apply)**
Say I have 3 regions in a multi-primary setup. One region has experience some hardware failure which gives us unstable network connections.

We wish to be able to quarantine some workloads in the degraded cluster by removing them from being discovered. We also wish to apply this operation in the healthy clusters not in the degraded cluster(We have considered applying `istio-discovery=disabled` in the degraded cluster). 

The best solution is to have a destinationrule subset with all the regions, then remove the degraded region from the subset during the outage. 

Alternative would be creating one subset per region then re-implement round robin ourselves in virtual services. 

**Describe alternatives you've considered**
[X] Networking
**Affected features (please put an X in all that apply)**
[X] Multi Cluster

**Additional context**

**Comment by hzxuzhonghu** [comment]
Destinationrule subset allows setting labels, i think it satisfies your requirement.

**Comment by zijianz** [comment]
> Destinationrule subset allows setting labels, i think it satisfies your requirement.

`labels` is a `map<string, string>` which perform an AND(&&) operation among all labels. Can we use set-based selector to have an OR(||) based label matcher?

**Comment by hzxuzhonghu** [comment]
I donot think this semantics comply with k8s labels selector


I think currently, you can include/exclude endpoints by updating its labels, which seems very easy

**Comment by zijianz** [comment]
> I donot think this semantics comply with k8s labels selector
> 
> I think currently, you can include/exclude endpoints by updating its labels, which seems very easy

K8s has a [set based label selector](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#set-based-requirement) which can do OR operation.

Our use case is that during network partition(hardware failures), we have possibility not be able to control the degraded cluster. So that we need to apply something in healthy clusters to exclude the workloads in the failed cluster. 

Excluding workloads is not easy since we want to exclude those workloads while we may have trouble accessing the api server of their cluster.

One way we were thinking is that the destination rule covers workloads in all 3 regions, and during an outage we will remove the troubled region and leave the 2 healthy regions in the destination rule. This is not possible since label selector performs AND, we can't add all region labels in one subset.

We have to manually quarantine those workloads since the symptom varies case by case during partition, hard to get a circuit breaker rule to cover them all.

**Comment by hzxuzhonghu** [comment]
> K8s has a [set based label selector](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#set-based-requirement) which can do OR operation.

This can be expressed as key in ["a", "b"], I can not tell if it can satisfy your request

I cannot understand how `OR` solve your requirement since all pods have same labels.

Implicitly istio add ``topology.istio.io/cluster` ` label to each endpoint, I think you can make use of it.

**Comment by zijianz** [comment]
> set based label selector

Really appreciate your help! Can you give me more details? Say I wish to have something like this
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: bookinfo-ratings
spec:
  host: ratings.prod.svc.cluster.local
  subsets:
  - name: round-robin
    labels:
      topology.istio.io/cluster in (cluster1, cluster2, cluster3)
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
```
While an outage happens in cluster2,  on healthy clusters we can change it to `topology.istio.io/cluster in (cluster1, cluster3)` 

Can we do it in the current destination rule since `label` is a `map<string, string>`? 

Thanks!!

**Comment by hzxuzhonghu** [comment]
One way You can define some thing like this 
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: bookinfo-ratings
spec:
  host: ratings.prod.svc.cluster.local
  subsets:
  - name: cluster1
    weight: xxx
    labels:
      topology.istio.io/cluster: cluster1
  - name: cluster2
    labels:
      topology.istio.io/cluster: cluster2
    weight: xxx
  - name: cluster3
    labels:
      topology.istio.io/cluster: cluster3
    weight: xxxx
```
