### ISSUE TITLE
components.pilot.k8s.replicaCount should not be set when values.pilot.autoscaleEnabled is true

### ISSUE THREAD

**Issue by martinstenhoff** [istio/istio#40246]
### Bug Description

The default profile provided in 1.14.3 (istio-1.14.3/manifests/profiles/default.yaml) generates a warning message about "incompatible" config settings when used.
```
$ ./istio-1.14.3/bin/istioctl install -f ./istio-1.14.3/manifests/profiles/default.yaml
components.pilot.k8s.replicaCount should not be set when values.pilot.autoscaleEnabled is true
This will install the Istio 1.14.3 default profile with ["Istio core" "Istiod" "Ingress gateways"] components into the cluster. Proceed? (y/N)
```

The default for components.pilot  (using istioctl profile dump command) seems to be:
```
pilot:
      enabled: true
      k8s:
        hpaSpec:
          maxReplicas: 5
          metrics:
          - resource:
              name: cpu
              target:
                averageUtilization: 80
                type: Utilization
            type: Resource
          minReplicas: 1
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: istiod
        replicaCount: 1
```

### Version

```prose
istioctl version
no running Istio pods in "istio-system"
1.14.3

kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.3
Kustomize Version: v4.5.4
Server Version: v1.24.0
```

### Additional Information

Perhaps the profile defaults should've been updated as part of this PR #36928
