### ISSUE TITLE
CNI race condition alternative design

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#40303]
The CNI startup race condition (https://docs.google.com/document/d/1SQzrFxtcn3o_79OtJYbSHMPuqZNhR3EaEhbkpBVMXAw/edit#) is an issue that has plagued Istio for quite some time.

We currently have 2 solutions:

* init container on sidecar injected which tests rules are applied; if they aren't we hang an a controller kills the pod. This is slow, gives high priv to controller, inefficient to kill pods, and confusing to users
* Taint controller; users need to configure their k8s to apply a taint by default to nodes and then we remove it. This works great but requires changes to the k8s cluster that we cannot do (no API)

The alternative I am thinking of is essentially the inverse of the taint controller. We inject a `nodeSelector: cni.istio.io/ready=true` onto all injected pods. Then, when the cni is ready we run the equivilent of `kubectl label node cni.istio.io/ready=true`. With this done, we can remove the istio-validation container entirely.

cc @stewartbutler @jwendell for opinions

**Comment by zirain** [comment]
will (2) fix https://github.com/istio/istio/issues/40008?

**Comment by howardjohn** [comment]
Both (2) taint controller and my proposed new change would

**Comment by howardjohn** [comment]
One other thing is this would allow adding a node selector to  the CNI daemonset to deploy it on a subset of nodes. Then the injected pod selector ensures we only schedule injected pods on those nodes, limiting the mesh to only some nodes. Today, CNI always goes on all (linux) nodes

**Comment by ahmadsayed** [comment]
> will (2) fix #40008?

@zirain I tried to simulate this, via using a daemonset that un-taint the node which seems to be working, but with big catch that render it not useful at least in our case

As this situation happens when a Cluster Node Autoscaler kick-in, by Pending Pod that require node with specific taint and label,  In order to delay the scheduling of a pod this pod must not tolerate this taint, so it can wait for controller to remove the taint, which  led to the the auto-scaler will not kick-in at all, so the Pod will stuck on Pending, and Autoscaler will not kick-in.

**Comment by ahmadsayed** [comment]
> The alternative I am thinking of is essentially the inverse of the taint controller. We inject a `nodeSelector: cni.istio.io/ready=true` onto all injected pods. Then, when the cni is ready we run the equivilent of `kubectl label node cni.istio.io/ready=true`. With this done, we can remove the istio-validation container entirely.

@howardjohn I also tried similar approach but using NodeAffinity,  as in my case we use the nodeSelector, but again in case of [autoscaler](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-does-scale-up-work)  situation, this seems to be not working 

> CA will automatically identify node groups with the same instance type and the same set of labels (except for automatically added zone label) and try to keep the sizes of those node groups balanced. 

and it is even explicitly mention as not [Best Practice] (https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-are-the-key-best-practices-for-running-cluster-autoscaler)
>Do not modify the nodes belonging to autoscaled node groups directly. All nodes within the same node group should have the same capacity, labels and system pods running on them.

**Comment by ahmadsayed** [comment]
One more things I tried is to use Inter-Pod Affinity, but it still k8s bring up the pod prematurely to the node, as soon as istio-cni-node pod scheduled in this node.

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx5
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            k8sapp: istio-cni-node
        namespaces:
        - namespace
        topologyKey: kubernetes.io/hostname
  containers:
  - image: nginx
    name: nginx
    resources:
      requests:
        memory: 11Gi
  nodeSelector:
    resourcePlanId: basic
  restartPolicy: Never
```
