### ISSUE TITLE
add Secret CRD to support passing secrets over MCP

### ISSUE THREAD

**Issue by doujiang24** [istio/istio#40325]
**Describe the feature request**
Add Secret CRD to describe secrets, so that we could pass secrets over MCP.

**Describe alternatives you've considered**

```
apiVersion: networking.istio.io/v1alpha3
kind: Secret
metadata:
  name: mygateway
spec:
  workloadSelector:
    matchLabels:
      app: ratings
  serverCertificate: # string value of server certificate
  privateKey: # string value of private key
  caCertificates: # string value of ca cert
```

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[X] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[X] Virtual Machine
[ ] Multi Control Plane

**Additional context**

Now the secrets only come from k8s, with fixed namespace take effects for a single secret resource.
After having the secret CRD, we could pass secrets over MCP from an alternative MCP server.
Also, having a flexible scope to take effect, with workloadSelector in the CRD.

So that, we could control the secrets in an upper-level control plane/dashboard, even without k8s.
(with MCP & the existing CRD, we could have almost control in the upper-level control plane, except secrets now.)

Any feedbacks are welcome, thanks!
