### ISSUE TITLE
Can a pod not injected with sidecar use istio smart routing?

### ISSUE THREAD

**Issue by mark8s** [istio/istio#40375]
Enable smart routing ：

```yaml
proxyMetadata:
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
        ISTIO_META_DNS_CAPTURE: "true"
```
