### ISSUE TITLE
Istio proxy not reading 443

### ISSUE THREAD

**Issue by strin** [istio/istio#4037]
I am trying to enable AWS ELB in `istio.yaml` installation file:

```
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:786838678978:certificate/d3e33be2-543d-4163-b65e-60496e253ef7
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'
    dns.alpha.kubernetes.io/external: "beta.cresta.ai"
```

All requests to HTTP 80 worked great. But HTTPS requests to 443 are not working.
