### ISSUE TITLE
Support multiple addresses per listener to generate LDS configuration in Istio

### ISSUE THREAD

**Issue by zhlsunshine** [istio/istio#40394]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
As feature [issue#11184](https://github.com/envoyproxy/envoy/issues/11184) in envoy has been completed. According to current implementation, the field of `AdditionalAddresses` has been added into the `Listener` struct. It means that one listener can be used for multiple addresses in envoy. 
This feature can be used by Istio which is deployed in dual-stack k8s cluster. The services in the same cluster can have 2 cluster IP addresses in this scenario, the one is IPv4 and the other is IPv6.
In general, Isito can implement dual stack based on this envoy feature, moreover, it also can help to eliminate duplicated configuration for current dual stack solution which is implemented in extra branch `experimental-dual-stack` of Istio.

**Describe alternatives you've considered**
There is an implementation for dual stack support in extra branch `experimental-dual-stack` of Istio. But it imports duplicated configuration and inflexible.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
One case useful i can think of for now is for tcp headless service, we build one listener per pod instance. With the new version,  we can build only one listener.

**Comment by zhlsunshine** [comment]
> One case useful i can think of for now is for tcp headless service, we build one listener per pod instance. With the new version, we can build only one listener.

Hi @hzxuzhonghu, yeah, that's a good use case. However, we have to consider how to implement traffic route if the network session is stateful.

**Comment by kyessenov** [comment]
@hzxuzhonghu Are you sure the listener update is in-place? Otherwise, you're draining connections any time another endpoint stands up for a headless service.

**Comment by hzxuzhonghu** [comment]
I am not sure, i donot have a chance to look at that yet

**Comment by kyessenov** [comment]
It'd be strictly worse without support for delta updates for additional addresses. I haven't checked either.

**Comment by costinm** [comment]
For dual stack - clearly good idea. 

I think for stateful sets it is also strictly better than what we have today.

**Comment by howardjohn** [comment]
For headless the XDS size is strictly better but there would be draining anytime any endpoint changes. Ive tested in https://github.com/istio/istio/pull/40409 (didn't test the drain though, just assumed)

**Comment by howardjohn** [comment]
Maybe Envoy can be optimized to not drain on multiple addresses if the only thing changing is removing/adding an address?

**Comment by costinm** [comment]
This should also be used for service VIPs for multi-cluster, to allow use of external dns servers. Right now we rely on DNS interception and there are limitations. Instead we should send the VIPs from all clusters.

**Comment by jacob-delgado** [comment]
Maybe I'm lost, but I think he's referring to https://github.com/istio/istio/blob/a2a370e3469c5b51cdcf1e7897bdeb509438cd17/pilot/pkg/model/service.go#L79
and subsequently https://github.com/istio/istio/blob/a2a370e3469c5b51cdcf1e7897bdeb509438cd17/pilot/pkg/model/service.go#L755

with the idea that dual stack Kubernetes clusters have 2 VIPs, one for IPv4 and IPv6 if a Service has both ipFamilies defined.

Thoughts @costinm and @howardjohn ?

**Comment by kyessenov** [comment]
In-place listener update could handle multiple addresses, but the problem is that these listeners are using a poorly supported (and previously deprecated) option for non-binding addresses. It might be better to switch to using matchers for headless services, which will avoid any drain.

**Comment by howardjohn** [comment]
I generally agree, the only issue is we cannot just migrate headless services, we need to migrate everything, I think. Which we should/will do, just not a small effort

**Comment by zhlsunshine** [comment]
Hi all, thank you for all your comments, and thanks for @howardjohn's [PR#40409](https://github.com/istio/istio/pull/40409), I think it's a great example of using multi-addresses per listener for headless service. I understand that all these changes are not a small effort, however, let's brainstorm to make it happen. BTW, I drafted an initialized [PR#40539](https://github.com/istio/istio/pull/40539), any idea?

**Comment by john-a-joyce** [comment]
@zhlsunshine - I was doing some IPv6 testing on Kind with Metallb with Istio v1.16 and I was hitting a number of issues.   One issue was lack of Ipv6 listeners (https://github.com/istio/istio/issues/24099) and another issue was likely due iptables misconfiguration.   When checking for possible matching issues I came across your issue.   Which might address the issues I am seeing. Do you think I should retry my test based on builds of master or should I wait until the remaining PRs get merged?

**Comment by zhlsunshine** [comment]
Hi @john-a-joyce,  I think you may need to wait the PR: https://github.com/istio/istio/pull/41618 got merged before you do the test. BTW, @howardjohn could you please make some higher priority to help review the PR? Thanks so much! ^_^

**Comment by john-a-joyce** [comment]
@zhlsunshine - I pulled the PR: https://github.com/istio/istio/pull/41618, built the images and installed with the Dual Stack params in your design spec but when testing there were still no IPv6 listeners on the istio-ingress.   If there are other steps to follow let me know or if you want more details on the setup I can provide them.

**Comment by zhlsunshine** [comment]
@john-a-joyce how do you install the Istio?

**Comment by john-a-joyce** [comment]
@zhlsunshine - I can put complete details in a gist if it helps,  but I will provide some high level stuff here.  If you want more just let me know anything you might want.   This was on a kind cluster using:  KIND_IMAGE:-kindest/node:v1.21.1 and config
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: A.B.C.D  
  ipFamily: dual
```
It was using metallb VERSION=v0.11.0

Here is what I used to add your configs (the joycej tag was to pull in your PR on top of master).
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  hub: joycej
  profile: minimal
  tag: joycej
  meshConfig:
    defaultConfig:
      proxyMetadata:
        ISTIO_AGENT_DUAL_STACK: "true"
  values:
    global:
      imagePullPolicy: IfNotPresent
    pilot:
      env:
        ISTIO_DUAL_STACK: true
```
Here is the service:  
```
apiVersion: v1 
kind: Service 
metadata:
  name: istio-ingressgateway 
  namespace: istio-ingress
spec:
  type: LoadBalancer 
  selector: 
    istio: ingressgateway
  ports:
  - port: 80 
    name: http2
  - port: 443 
    name: https
  ipFamilyPolicy: PreferDualStack 
  ipFamilies:
  - IPv6
  - IPv4
```
Note I also tried IPv6 only - but I did not try "RequireDualStack" I will repeat with that setting shortly.
