### ISSUE TITLE
Support DSCP Marking on external interfaces for QoS purposes

### ISSUE THREAD

**Issue by kfaseela** [istio/istio#40397]
**Describe the feature request**

Network Functions shall support both server side (ingress gateway) and client side (egress sidecar/gateway) DCSP marking for interfaces including provisioning. Customers who use 5G Core solutions need a mechanism to set DSCP marking on all external facing interfaces. So this becomes an important requirement for telco deployments. Similar request can be seen already on [Contour](https://github.com/projectcontour/contour/issues/4605) which is being worked upon. Other socket options like [TCP KeepAlive](https://github.com/projectcontour/contour/pull/2638) seems to be already supported in Contour.

**Background**

[Differentiated services or DiffServ](https://en.wikipedia.org/wiki/Differentiated_services) is a computer networking architecture that specifies a simple and scalable mechanism for classifying and managing network traffic. DiffServ uses a 6-bit differentiated services code point (DSCP) in the 8-bit differentiated services field (DS field) in the IP header for packet classification purposes.

**EnvoyFilter based solution**

Envoy proxy has already exposed [socket option](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/socket_option.proto.html?highlight=socket_options) through its XDS API (for both listener and cluster). The envoy proxy listener socket option DSCP configuration can work for Istio ingress gateway scenario, as well as Istio egress sidecar/gateway scenario. However, EnvoyFilters are always complex to manage and maintain.

A sample EnvoyFilter for DSCP socket option modification for IPv4 and IPv6 are given below:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ingress-dscp-socketoptions
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: istio-ingressgateway
  configPatches:
  - applyTo: LISTENER
    match:
      context: GATEWAY
      listener:
        portNumber: 8443
    patch:
      operation: MERGE
      value:
        socket_options:   #  this values need to be double checked!
        - level: 0        #  0 for IPPROTO_IP
          name: 1         #  1 for IP_TOS
          int_value: 64   #0x10 IPTOS_LOWDELAY  ==> 10000(00)=2^6=64  0x08 IPTOS_THROUGHPUT ==> 1000(00)=2^5=32
          state: STATE_PREBIND  #STATE_PREBIND is default, other 2 values are STATE_BOUND, STATE_LISTENING
```

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ingress-dscp-socketoptions
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: istio-ingressgateway
  configPatches:
  - applyTo: LISTENER
    match:
      context: GATEWAY
      listener:
        portNumber: 8443
    patch:
      operation: MERGE
      value:
        socket_options:   #  this values need to be double checked!
        - level: 41        #  41 for IPPROTO_IPv6
          name: 67         #  67 for IPV6_TCLASS
          int_value: 32    ##IPV6_TCLASS is 32, and DSCP is 0x20, 0x10 IPTOS_LOWDELAY  ==> 10000(00)=2^6=64  0x08 IPTOS_THROUGHPUT ==> 1000(00)=2^5=32
          state: STATE_PREBIND  #STATE_PREBIND is default, other 2 values are STATE_BOUND, STATE_LISTENING
```

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: egress-dscp-socketoptions
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      cluster:
        name: "outbound|443||traffic.foo.com"
    patch:
      operation: MERGE
      value:
        upstream_bind_config:
          source_address:
            address: "0.0.0.0"
            port_value: 0
          socket_options:
          - level: 0        #  0 for IPPROTO_IP
            name: 1         #  1 for IP_TOS
            int_value: 32  #IP_TOS is 72, and DSCP is 0x48
            state: STATE_PREBIND  #STATE_PREBIND is default, other 2 values are STATE_BOUND, STATE_LISTENING
```
**Solution Proposal**

It would be nice if DSCP socket options configuration is supported via standard istio APIs.
For gateways, https://istio.io/latest/docs/reference/config/networking/gateway/#Port seems to be the right place for adding the same. For egress sidecar, https://istio.io/latest/docs/reference/config/networking/destination-rule/#TrafficPolicy-PortTrafficPolicy can be enhanced to add DSCP marking.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
