### ISSUE TITLE
Egress Traffic - Multiple Client Certificates Auth over one Endpoint

### ISSUE THREAD

**Issue by Crazyigor1987** [istio/istio#40403]
Hello all,

I am facing the puzzle of how to get multiple client certificate authorizations via an egress endpoint.

Example:

Service A uses Clientcert A to invoke domain "endpoint.io".
Service B uses Clientcert B to invoke domain "endpoint.io".

My setting is identical to the one described here: https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/#configure-mutual-tls-origination-for-egress-traffic

No matter how much I define the routes back and forth internally, in the end I always have only one destination rule that loads ONE endpoint and ONE certificate.

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-mtls-for-endpoint-io
spec:
  host: endpoint.io
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: MUTUAL
        credentialName: client-credential # this must match the secret created earlier to hold client certs
        sni: client-service-a.endpoint.io

```
Am I missing something here?
