### ISSUE TITLE
report segment info to skywalking failed

### ISSUE THREAD

**Issue by LL1024LL** [istio/istio#40421]
### Bug Description

We found our istio report trace info to skywalking-oap occasionally failed.However it works normally most of the time.

Skywalking web-ui message showed :
![image](https://user-images.githubusercontent.com/34938683/184295270-ec724ae4-a782-49ab-986d-83db981fcec0.png)

Skywalking-oap log:
![image](https://user-images.githubusercontent.com/34938683/184295802-8c22e52f-a851-4522-aef7-3fdc88c6637c.png)

Isito-proxy log:
![image](https://user-images.githubusercontent.com/34938683/184295482-7b54fa6b-52bb-403c-9a07-635a9bc40ee4.png)

Our istio config:
```
accessLogFile: /dev/stdout
defaultConfig:
  discoveryAddress: istiod.istio-system.svc:15012
  envoyAccessLogService:
    address: skywalking-oap-external.istio-system.svc.cluster.local:8169
  holdApplicationUntilProxyStarts: true
  proxyMetadata: {}
  tracing:
    zipkin:
      address: zipkin.istio-system:9411
defaultProviders:
  tracing:
  - envoy.tracers.skywalking
enableEnvoyAccessLogService: true
enablePrometheusMerge: true
extensionProviders:
- name: envoy.tracers.skywalking
  skywalking:
    port: 8169
    service: skywalking-oap-external.istio-system.svc.cluster.local
- envoyOtelAls:
    port: 4317
    service: otel-collector.istio-system.svc.cluster.local
  name: otel
rootNamespace: istio-system
trustDomain: cluster.local
```

Since our Skywalking server is an External system ， We create ServiceEntry like 
```
spec:
  hosts:
  - skywalking-oap-external.istio-system.svc.cluster.local
  location: MESH_INTERNAL
  ports:
  - name: grpc-skywalking
    number: 8169
    protocol: TCP
  resolution: DNS
```

How to fix this problem？We appreciate for help

### Version

```prose
istioctl version
client version: 1.12.0
control plane version: 1.14.1
data plane version: 1.13.2 (10 proxies), 1.14.1 (27 proxies)

kubectl version --short
Client Version: v1.22.1
Server Version: v1.22.2
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [X] Networking
- [X] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
