### ISSUE TITLE
Istio corrupts some of x-request-id header

### ISSUE THREAD

**Issue by dimitriusx** [istio/istio#40431]
### Bug Description

I founded a bug in Istio. In my project I have to preserve client incoming x-request-id http header. I  enabled an option **preserve_external_request_id** in EnvoyFilter. Istio corrupted this header in some cases (2 from 10 requests). E.g.: I send request to the service with header "x-request-id: ad037f57-3136-e723-ed7d-ed723f0e5718", but istio writes message to logs with corrupted header ad037f57-3136-**9**723-ed7d-ed723f0e5718

More examples of ids:

| Expected | Corrupted |
|--- |---|
| ad037f57-3136-e723-ed7d-ed723f0e5718| ad037f57-3136-9723-ed7d-ed723f0e5718 |
| a0255c06-abd2-7ded-39c9-c15ecb034229| a0255c06-abd2-9ded-39c9-c15ecb034229 |
| 502fba57-6ac5-1516-4ca1-ed0b52b470ad| 502fba57-6ac5-9516-4ca1-ed0b52b470ad |
| 01dc4b9c-a41c-fa82-cb53-78426d02c3d7| 01dc4b9c-a41c-9a82-cb53-78426d02c3d7 |
| b8c35637-c823-534a-95d3-de51d07b2556| b8c35637-c823-934a-95d3-de51d07b2556 |
| 650ff87e-33d3-c8cd-e779-94f37753aafd| 650ff87e-33d3-98cd-e779-94f37753aafd |
| 472b29dc-1775-da63-642d-2e0f381adf19| 472b29dc-1775-9a63-642d-2e0f381adf19 |
| cd0b9e2f-bcde-2f5b-9cb3-ef0dad5010a8| cd0b9e2f-bcde-9f5b-9cb3-ef0dad5010a8 |
| a0fb7d42-1cfd-496b-72fb-5a992de512bf| a0fb7d42-1cfd-996b-72fb-5a992de512bf |
| bfdee500-a381-e72f-caca-026428a98cd7| bfdee500-a381-972f-caca-026428a98cd7 |

My EnvoyFilter manifest
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: istio-tweaks
  name: normalize-headers
  namespace: istio-system
spec:
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: MERGE
        value:
          typed_config:
            '@type': >-
              type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            http_protocol_options:
              header_key_format:
                proper_case_words: {}
            preserve_external_request_id: true
  workloadSelector:
    labels:
      istio: ingressgateway
```

### Version

```prose
kubectl
Client Version: v1.22.6
Server Version: v1.22.10-eks-84b4fe6

istioctl
client version: 1.14.3
control plane version: 1.14.1
data plane version: 1.14.1 (52 proxies)
```
