### ISSUE TITLE
Istio ingress helm chart doesn't allow to modify values

### ISSUE THREAD

**Issue by IvanovOleg** [istio/istio#40436]
### Bug Description

I am trying to install istio ingress gateway helm chart as a dependency and it doesn't allow me to override it's values from a parent values.yaml file.

values.yaml:
```
istio-ingress:
  test: test
```
chart.yaml:
```
apiVersion: v2
name: istio-parent
description: Istio parent chart
type: application
version: 0.0.2
appVersion: 0.0.2
dependencies:
  - name: base
    version: ~1.14.3
    repository: https://istio-release.storage.googleapis.com/charts
    condition: istio.enabled
    alias: istio-base
  - name: istiod
    version: ~1.14.3
    repository: https://istio-release.storage.googleapis.com/charts
    condition: istio.enabled
    alias: istio-discovery
  - name: gateway
    version: ~1.14.3
    repository: https://istio-release.storage.googleapis.com/charts
    condition: istio.enabled
    alias: istio-ingress
```

```
Error: INSTALLATION FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
istio-ingress:
- (root): Additional property test is not allowed
```
I believe schema forbids any modifications.

### Version

```prose
1.14.3
```
