### ISSUE TITLE
Mount cacerts via CSI for Helm chart

### ISSUE THREAD

**Issue by ElkRom** [istio/istio#40490]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Currently, by default we can mount **cacerts** only via [k8s secret in a Helm](https://github.com/istio/istio/blob/e1f63e8ce82e3bad28c2bb0a87f4bc7ffefac1b9/manifests/charts/istio-control/istio-discovery/templates/deployment.yaml#L217).
It is beneficial to extend this possibility and add an option to use [CSI](https://kubernetes.io/blog/2019/01/15/container-storage-interface-ga/), it will be great security enhancement for Helm setup.

**Describe alternatives you've considered**
Yeah, as alternative can be deployed via IstioOperator, which does patching - but it is not our case, as we are using Helm

`
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
 components:
   pilot:
     enabled: true
     k8s:
       overlays:
         - kind: Deployment
           name: istiod # https://github.com/istio/istio/issues/31076
           patches:
             - path: spec.template.spec.volumes[name:cacerts]
               value:
                 name: cacerts
                 csi:
                   driver: secrets-store.csi.k8s.io
                   readOnly: true
                   volumeAttributes:
                     secretProviderClass: "istio-tls"
```
`

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[X] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
It can be done by helm as well https://preliminary.istio.io/latest/docs/setup/additional-setup/customize-installation-helm/

**Comment by ElkRom** [comment]
@howardjohn  thanks for help.  
But still would be nice to have CSI in Istio Helm.

**Comment by ElkRom** [comment]
Hi @howardjohn, could you please help?) 
I will be so grateful if you can share an example of automating customize istio installation (link above) via Terraform

**Comment by zirain** [comment]
An simple demo can be found [here](https://github.com/zirain/playground/tree/master/istio/tf), which I used to debug https://github.com/istio/istio/issues/38831.

**Comment by ElkRom** [comment]
Short update,
I have tried to use [this solution](https://preliminary.istio.io/latest/docs/setup/additional-setup/customize-installation-helm/) for putching Istiod deployment, but it coudln't putch field which already presented in defenition
Error
`│ Error: release istiod failed, and has been rolled back due to atomic being set: cannot patch "istiod" with kind Deployment: Deployment.apps "istiod" is invalid: [spec.template.spec.volumes[0].csi: Forbidden: may not specify more than 1 volume type, spec.template.spec.containers[0].volumeMounts[2].name: Not found: "cacerts"]`

Customization

> apiVersion: apps/v1
kind: Deployment
metadata:
  name: istiod
  namespace: istio-system
spec:
  template:
    spec:
      volumes:
      - name: cacerts
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "istio-mtls"

**Comment by zioproto** [comment]
I tested the approach suggested in https://github.com/istio/istio/issues/40490#issuecomment-1216627201 and I believe it does not work because of the `patchesStrategicMerge` approach.

I created a file `csipatch.yaml`

```
% cat csipatch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istiod
  namespace: istio-system
spec:
  template:
    spec:
      volumes:
      - name: cacerts
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "istio-mtls"
```

I created the kustomize.sh file as described [here](https://preliminary.istio.io/latest/docs/setup/additional-setup/customize-installation-helm/#create-the-kustomization):
```
cat > kustomize.sh <<EOF
#!/bin/sh
cat > base.yaml
exec kubectl kustomize # you can also use "kustomize build ." if you have it installed.
EOF
chmod +x ./kustomize.sh
```

I created my `kustomization.yaml` file:

```
% cat kustomization.yaml
resources:
- base.yaml
patchesStrategicMerge:
- csipatch.yaml
```
Now I can test if the template renders correctly:
```
helm template istiod istio/istiod -n istio-system --post-renderer ./kustomize.sh
```

I see this:
```
      volumes:
      - csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: istio-mtls
        name: cacerts
        secret:
          optional: true
          secretName: cacerts
```

this is not working because the `secret` block should be dropped.


Following instructions here:
https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#customizing

You need to use a `patchesJson6902` patch.

Do the following, change the `kustomization.yaml`:

```
% cat kustomization.yaml
resources:
- base.yaml
patchesJson6902:
- target:
    kind: Deployment
    name: istiod
  path: patch.yaml
```
create a `patch.yaml` file:
```
% cat patch.yaml
- op: replace
  path: /spec/template/spec/volumes[name:cacerts]
  value:
    name: cacerts
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "istio-tls"
```
Now it renders correctly for me with:
```
helm template istiod istio/istiod -n istio-system --post-renderer ./kustomize.sh
```

**Comment by zioproto** [comment]
In comment https://github.com/istio/istio/issues/40490#issuecomment-1239365163 I just explain how to patch the helm template, I did not provide an example how to integrate this in Terraform.

In comment https://github.com/istio/istio/issues/40490#issuecomment-1223637685 it was suggested to look at [istiod.tf](https://github.com/zirain/playground/blob/master/istio/tf/istiod.tf) but in this example it does not use the `--post-renderer` feature.

I believe it is necessary to use the `postrender` block documented in the Terraform resource:
https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#postrender

@ElkRom if you manage to come up with the full example can you please post it here ? thanks

**Comment by ElkRom** [comment]
@zioproto  thanks for help, appreciated
What is working in my case:

patch.yaml
```
- op: replace
  path: /spec/template/spec/volumes/2
  value:
    name: cacerts
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "istio-tls"
```
When compering with @zioproto  example, the path a bit different 

kustomization.yaml is the same:
```
% cat kustomization.yaml
resources:
- base.yaml
patchesJson6902:
- target:
    kind: Deployment
    name: istiod
  path: patch.yaml
```
For kustomiz.sh I have added one input argument, which accepts Terraform ${path.module} value
```
% cat kustomiz.sh
#!/bin/sh
cd $1
cat > base.yaml
exec kubectl kustomize # you can also use "kustomize build ." if you have it installed.
EOF
```

Terraform file for deploying Istio via Helm
```
resource "helm_release" "istiod" {
  name              = "istiod"
  namespace         = var.istio_ns_name
  dependency_update = true
  repository        = local.istio_chart_repo
  chart             = "istiod"
  version           = var.istio_version
  atomic            = true
  values            = local.helm_values_istio
  lint              = true
   
  #For automating csi putch
  postrender {
    binary_path = "${path.module}/kustomize.sh"
    args = ["${path.module}"]
     }
  depends_on = []
   }
  ```

**Comment by zioproto** [comment]
@ElkRom you are right, this patch file does not render correctly:

```
% cat patch.yaml
- op: replace
  path: /spec/template/spec/volumes[name:cacerts]
  value:
    name: cacerts
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "istio-tls"
```

the correct solution is the one you found, changing the `path` to:
```
  path: /spec/template/spec/volumes/2
```
it seems this is a limit of JSON:
https://stackoverflow.com/questions/27439986/what-is-the-json-patch-format-to-remove-an-element-from-an-array
