### ISSUE TITLE
TLS passthrough gateway not working with tcp route

### ISSUE THREAD

**Issue by shonecyx** [istio/istio#40511]
### Bug Description

By default TLS gateway mode is PASSTHROUGH and if the virtualservice is tcp match, then the listener will not be configured, SDS will also not work.

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: foo-gw
  namespace: foo-ns
spec:
  selector:
    istio: ingressgateway-system
  servers:
  - hosts:
    - foo.example.com
    port:
      name: https-443
      number: 443
      protocol: TLS
    tls:
      credentialName: secretname
      minProtocolVersion: TLSV1_2

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: foo-vs
  namespace: foo-ns
spec:
  gateways:
  - foo-gw
  hosts:
  - foo.example.com
  tcp:
  - match:
    - port: 443
    route:
    - destination:
        host: ap-tls-sample-svc
        port:
          number: 8080
```

This can be easily reproduced by below test case:
```
{
			"gateway with TLS passthrough and TCP match virtualservice",
			&pilot_model.Proxy{},
			[]config.Config{
				{
					Meta: config.Meta{Name: "gateway1", Namespace: "testns", GroupVersionKind: gvk.Gateway},
					Spec: &networking.Gateway{
						Servers: []*networking.Server{
							{
								Port:  &networking.Port{Name: "tls", Number: 1118, Protocol: "TLS"},
								Hosts: []string{"bar.example.com"},
								Tls:   &networking.ServerTLSSettings{CredentialName: "test", Mode: networking.ServerTLSSettings_PASSTHROUGH},
							},
						},
					},
				},
			},
			[]config.Config{
				{
					Meta: config.Meta{Name: uuid.NewString(), Namespace: uuid.NewString(), GroupVersionKind: gvk.VirtualService},
					Spec: &networking.VirtualService{
						Gateways: []string{"testns/gateway1"},
						Hosts:    []string{"bar.example.com"},
						Tcp: []*networking.TCPRoute{
							{
								Match: []*networking.L4MatchAttributes{
									{
										Port: 1118,
									},
								},
								Route: []*networking.RouteDestination{
									{
										Destination: &networking.Destination{
											Host: "foo.com",
										},
									},
								},
							},
						},
					},
				},
			},
			[]string{"0.0.0.0_1118"},
		}
```
Error:
```
2022-08-17T11:13:41.313867Z info  gateway omitting listener "0.0.0.0_1118" due to: must have more than 0 chains in listener "0.0.0.0_1118"
    gateway_test.go:1905: Expected listeners: [0.0.0.0_1118], got: []
        map[{1118 TLS }:0xc0011d37d0]
```

**Expected behavior**
If TLS PASSTHROUGH plus `TCPRoute` is invalid, we should have validation in Istio to avoid this spec error or at least have some error logs. 
BTW seems this is a validation of Gateway and VirtualService combination.

### Version

```prose
istio version: 1.10
kubectl version: 1.18.8
```
