### ISSUE TITLE
istio-operator does not re-reconcile when errors occur in helm reconciler

### ISSUE THREAD

**Issue by CathalC2011** [istio/istio#40522]
### Bug Description

When an error occurs within the HelmReconciler subsystem of the IstioOperator reconciliation loop, the operator will not schedule the object for another reconciliation attempt at a later time.

This means that temporary problems external to the operator (like a broken webhook) which become resolved, can leave the IstioOperator resource in error state indefinitely.

### Version

```prose
istioctl version
client version: 1.13.4
control plane version: 1.13
data plane version: 1.13.7 (345 proxies), 1.13.5 (209 proxies)

kc version --short
Client Version: v1.24.1
Kustomize Version: v4.5.4
Server Version: v1.21.9
```

### Additional Information

The [final section of the IstioOperator reconcile function](https://github.com/istio/istio/blob/master/operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go#L372) does two things;

```
	status, err := reconciler.Reconcile()
	if err != nil {
		scope.Errorf("Error during reconcile: %s", err)
	}
	if err := reconciler.SetStatusComplete(status); err != nil {
		return reconcile.Result{}, err
	}

	return reconcile.Result{}, err
```

1. It attempts to reconcile the helm manifests using the HelmReconciler
2. It attempts to update the IstioOperator status

If any error occurs in the HelmReconciler subsystem, the error is thrown away and the IstioOperator never attempts to re-reconcile. 

The following is a closer look at how this hit us, but the details don't really matter.

* [ApplyManifest](https://github.com/istio/istio/blob/master/operator/pkg/helmreconciler/reconciler.go#L211) returns an error
  * If `err` is not nil, we return an [InstallStatus{Status: v1alpha1.InstallStatus_ERROR}](https://github.com/istio/istio/blob/master/operator/pkg/helmreconciler/reconciler.go#L234)
* We store that result in the `status` var in the [calling function](https://github.com/istio/istio/blob/master/operator/pkg/helmreconciler/reconciler.go#L162), **but we do not return it as an err**. Instead, our second return value is [pruneErr](https://github.com/istio/istio/blob/master/operator/pkg/helmreconciler/reconciler.go#L170)
* We store *that* status once again in another `status` var in the [calling function](https://github.com/istio/istio/blob/master/operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go#L372)
* We then *log* that error, but ultimately do nothing with it. 
* The `err` var is then reused to update the IstioOperator status, but we have already lost the chance to return the original error to the Reconcile function, triggering another reconciliation..

### Minimal Reproduction

Create empty Kind cluster:
```
kind create cluster --name kind
Creating cluster "kind" ...
⢄⡱ Ensuring node image (kindest/node:v1.24.0) 🖼
...
```

Install the operator using istioctl:
```
istioctl operator init
Installing operator controller in namespace: istio-operator using image: docker.io/istio/operator:1.13.4
Operator controller will watch namespaces: istio-system
✔ Istio operator installed
✔ Installation complete                                                                                                                                    
...
```

Apply a ValidatingWebhookConfiguration which forces deployment creations to fail:
```
cat <<EOF | kubectl apply -f -
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: idontexist
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: aWRvbnRleGlzdAo=
    service:
      name: idontexist
      namespace: idontexist
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: i.dont.exist
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - deployments
    scope: '*'
  sideEffects: None
  timeoutSeconds: 30
EOF
```

T1 -  Tail the logs:
```
kubectl -n istio-operator logs -l name=istio-operator -f
```

T2 - Apply an IstioOperator resource which requires a deployment:
```
cat <<EOF | kubectl apply -f -
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: base-operator-profile
  namespace: istio-system
spec:
  profile: empty
  components:
    base:
      enabled: true
    egressGateways:
      - name: istio-egressgateway
        enabled: true
EOF
```

Observe that the operator attempts to create the resources once, fails, and never tries again.
```
- Processing resources for Egress gateways.
✘ Egress gateways encountered an error: failed to update resource with server-side apply for obj Deployment/istio-system/istio-egressgateway: Internal error occurred: failed calling webhook "i.dont.exist": could not get REST client: unable to load root certificates: unable to parse bytes as PEM block
```
