### ISSUE TITLE
Add ignoreUriCase to AuthorizationPolicy

### ISSUE THREAD

**Issue by dozer75** [istio/istio#40541]
**Describe the feature request**

The `VirtualService` has the `ignoreUriCase` that can be used to allow uri with any casing to be routed. However the `AuthorizationPolicy` uses the inbound uri to match against the rules which causes problems (and even security issues if `AuthorizationPolicy` is configured wrong). My main issue is that since we're having `ignoreUriCase` set in the `VirtualService` those requests are rejected since the `AuthorizationPolicy` has the URI rules case sensitive.

So, the request is that the `AuthorizationPolicy` should do the same. Having `ignoreUriCase` allowing the configuration to indicate if the Uri casing should be ignored or not when matching the rules.

**Describe alternatives you've considered**

After searching a bit there is a [security advisory around DNS](https://github.com/istio/istio/security/advisories/GHSA-7774-7vr3-cc8j) that suggests to add a Lua filter to the ISTIO config handling DNS casings, but this will then apply normalization globally to the ISTIO ingress level which isn't always something you want when it comes to the Uri.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

Example:

Having a `VirtualService` with the following URI will route like these `https://host/Api/v1/Customer`, `https://host/API/v1/customer`, `https://host/API/V1/CUSTOMER`

```
  - name: "Route API requests"
    match:
    - uri:
        prefix: /api/v1/*
      ignoreUriCase: true
    rewrite:
      uri: /api/v1
    route:
    - destination:
        host: customer-service
        port:
          number: 80

```

But, they will be rejected since there is an `AuthorizationPolicy` match rule like

```
  - to:
       paths: ["/api/v1/customer"]
``` 

on ALLOW and the Authorization policy have a strict Uri casing, to support all various there would need to be 144 variations of to path for that path.
