### ISSUE TITLE
istio-proxy/istiod able to validate jwksuri with STRICT mTLS

### ISSUE THREAD

**Issue by maxres-ch** [istio/istio#40553]
Hi there. I believe this is NOT a feature that's been implemented, I've done my best to make sure I can't find it in the docs.

**Describe the feature request**
We'd like to be able to  to run istio with peerauthentication in STRICT mode and having a RequestAuthentication that uses `jwksUri` that is a service address within the cluster. This would require the istiod and or the proxy to be able to communication with the jwksuri that has mTLS enforced. 

Currently it doesn't seem that this is possible, eg. this doesn't work in the proxy
```
k exec1 -it example-service-xxxx -n example-pipeline-service -c istio-proxy -- bash
istio-proxy@example-service-xxx/$ curl http://myauthservice.mynamespace.svc.cluster.local/jwks
curl: (56) Recv failure: Connection reset by peer
istio-proxy@example-service-xxxxx:/$
```

```
❯ k exec1 -it example-service-xxxx -n example-pipeline-service -- bash
/home/node $ curl http://authentication-service.authentication-service.svc.cluster.local
{
  "timestamp" : "2022-08-18T23:49:43.913+00:00",
  "status" : 404,
  "error" : "Not Found",
  "path" : "/"
}/home/node $
```
Example configuration (I didn't post the authorizationpolicy, not sure it's important),

```yaml
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  generation: 1
  name: strict-tls-policy
  namespace: istio-system
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  annotations:
    meta.helm.sh/release-name: release
    meta.helm.sh/release-namespace: mynamespace
  labels:
    app.kubernetes.io/managed-by: Helm
  name: janus-jwt-required
  namespace: mynamespace
spec:
  jwtRules:
  - audiences:
    - my
    - example
    - audiences
    forwardOriginalToken: true
    fromHeaders:
    - name: authorization
      prefix: 'Bearer '
    issuer: myauthservice
    jwksUri: http://myauthservice.svc.cluster.local/jwks
  selector:
    matchLabels:
      istio: gaea-istio-ingress-poc
```

**Describe alternatives you've considered**

Special conditions in auth policies for just this call, but there's many other services making this call as well besides istio.
We could use a public domain or non internal routing to the jwkuri.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
