### ISSUE TITLE
B3 tracing header cannot be modified in VirtualService

### ISSUE THREAD

**Issue by danhngo-lx** [istio/istio#40613]
### Bug Description

I have enabled tracing for Istio, sampling rate 100%. But I want to disable tracing for some endpoints, and one way I could think of is setting the B3 header `X-B3-Sampled` to "0" for related destinations in a VirtualService, for example:

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpbin-test
  namespace: httpbin-test
spec:
  gateways:
  - default/default-gateway
  hosts:
  - subdomain.example.com
  http:
  - headers:
      request:
        set:
          X-B3-Sampled: "0"
    match:
    - uri:
        prefix: /httpbin-test
    rewrite:
      uri: /
    route:
    - destination:
        host: httpbin-svc
        port:
          number: 80
```

*Expected behavior*: `X-B3-Sampled` value is set to "0" for every HTTP request to httpbin service.

*Actual behavior*: Any request to subdomain.example.com/httpbin-test/ always have `X-B3-Sampled` set to "1":
```
curl -H "accept: application/json" https://subdomain.example.com/httpbin-test/headers
{
  "headers": {
    "Accept": "application/json",
    "Host": "subdomain.example.com",
    "User-Agent": "curl/7.77.0",
    "X-B3-Sampled": "1",
    "X-B3-Spanid": "aade27661ab6379f",
    "X-B3-Traceid": "5c81dd76c996679faade27661ab6379f",
    "X-Envoy-Attempt-Count": "1",
    "X-Envoy-Decorator-Operation": "httpbin-svc.httpbin-test.svc.cluster.local:80/httpbin-test*",
    "X-Envoy-Original-Path": "/httpbin-test/headers",
    "X-Envoy-Peer-Metadata": "<redacted>",
  }
}
```

I'm not sure if this is a bug or expected behavior, given that the sampling rate is 100%, and `X-B3-Sampled` is among the headers used to propagate to downstream service.

### Version

```prose
istioctl version
client version: 1.14.1
control plane version: 1.14.3
data plane version: 1.14.3 (64 proxies), 1.13.2 (4 proxies)
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4", GitCommit:"95ee5ab382d64cfe6c28967f36b53970b8374491", GitTreeState:"clean", BuildDate:"2022-08-17T18:46:11Z", GoVersion:"go1.19", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8-gke.1900", GitCommit:"79209257257c051b27df67c567755783eda93353", GitTreeState:"clean", BuildDate:"2022-07-15T09:23:51Z", GoVersion:"go1.17.11b7", Compiler:"gc", Platform:"linux/amd64"}
```
