### ISSUE TITLE
mTLS through eastwestgateway "NR filter_chain_not_found"

### ISSUE THREAD

**Issue by HenryXie1** [istio/istio#40624]
### Bug Description

We try to access TLS traffic on remote cluster via eastwestgateway, the logs of the gateway has:
```
[2022-08-24T04:40:42.145Z] "- - -" 0 NR filter_chain_not_found - "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.244.1.60:32022 10.244.1.1:58260 reviews.bookinfo-backends.svc.cluster2.global -
```

The `envoyfilter` applied to gateway in cluster2 seems not working.
We expect the filter can replace `cluster2.global` with `cluster.local` in eastwest gateway of cluster2

### Version

```prose
❯ istioctl version
client version: 1.13.4
control plane version: 1.13.4
data plane version: 1.13.4 (8 proxies)

❯ kubectl version --short
Client Version: v1.23.0
Server Version: v1.21.1
```

#### Expected behavior
route TLS traffic to other clusters using mTLS via gateways

#### Steps to reproduce the bug
deploy istio and bookinfo service to cluster1 (bookinfo review has version 1 and version 2). 
deploy eastwestgateway and bookinfo to cluster 2((bookinfo review has version 1, version 2 and version 3)

In cluster 1 bookinfo review service, it tries to access bookinfo review version 3 on cluster2 via eastwest gateway

#### Cluster 1 configs:
```
global:
  meshID: mesh1
  multiCluster:
    clusterName: cluster1
    enabled: true
  network: network1
  hub: docker.io/istio
  tag: 1.13.4
meshConfig:
  accessLogFile: /dev/stdout
  enableAutoMtls: true
  defaultConfig:
    proxyMetadata:
      ISTIO_META_DNS_CAPTURE: "true"
      ISTIO_META_DNS_AUTO_ALLOCATE: "true"
pilot:
  autoscaleEnabled: false
  env:
    PILOT_SKIP_VALIDATE_TRUST_DOMAIN: "true"
```
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: reviews-orange
  namespace: istio-system
spec:
  hosts:
  - reviews.bookinfo-backends.svc.cluster2.global
  ports:
  - name: http-orange
    number: 9080
    protocol: TCP
  addresses:
  - 240.0.0.1
  endpoints:
  - address: 172.21.0.5
    network: network2
    labels:
      cluster: cluster2
    ports:
      http-orange: 32022
  location: MESH_INTERNAL
  exportTo:
    - "*"
  resolution: STATIC
```
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews-orange
  namespace: istio-system
spec:
  host: reviews.bookinfo-backends.svc.cluster2.global
  subsets:
  - name: version-v3
    labels:
      cluster: cluster2
  - name: version-v2
    labels:
      cluster: cluster2
  - name: version-v1
    labels:
      cluster: cluster2
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
      sni: reviews.bookinfo-backends.svc.cluster2.global
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews
  namespace: bookinfo-backends
spec:
  host: reviews.bookinfo-backends.svc.cluster.local
  subsets:
  - name: version-v2
    labels:
      version: v2
  - name: version-v1
    labels:
      version: v1
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
  namespace: bookinfo-backends
spec:
  hosts:
    - reviews.bookinfo-backends.svc.cluster2.global
    - reviews.bookinfo-backends.svc.cluster.local
  http:
    - route:
      - destination:
          host: reviews.bookinfo-backends.svc.cluster2.global
          subset: version-v3
        weight: 80
      - destination:
          host: reviews.bookinfo-backends.svc.cluster.local
          subset: version-v1
        weight: 20
```

#### Cluster2 config
```
global:
  meshID: mesh1
  multiCluster:
    clusterName: cluster2
    enabled: true
  network: network2
  hub: docker.io/istio
  tag: 1.13.4
meshConfig:
  accessLogFile: /dev/stdout
  enableAutoMtls: true
  defaultConfig:
    proxyMetadata:
      ISTIO_META_DNS_CAPTURE: "true"
      ISTIO_META_DNS_AUTO_ALLOCATE: "true"
pilot:
  autoscaleEnabled: false
  env:
    PILOT_SKIP_VALIDATE_TRUST_DOMAIN: "true"
```
```
gateways:
  istio-ingressgateway:
    name: istio-eastwestgateway
    namespace: istio-gateways
    labels:
      istio: eastwestgateway
      app: istio-eastwestgateway
      topology.istio.io/network: network2
    autoscaleEnabled: false
    injectionTemplate: gateway
    ports:
    - name: tcp-status-port
      port: 15021
      targetPort: 15021
    - name: tls
      port: 32022
      targetPort: 32022
      nodePort: 32022
    - name: tcp-istiod
      port: 15012
      targetPort: 15012
    - name: tcp-webhook
      port: 15017
      targetPort: 15017
global:
      meshID: mesh1
      network: network2
      multiCluster:
        enabled: true
        clusterName: cluster2
```
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: orange-multicluster-eastwestgateway
  namespace: istio-system
  labels:
    istio: eastwestgateway
spec:
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.sni_cluster
          portNumber: 32022
      patch:
        operation: INSERT_AFTER
        value:
          name: envoy.filters.network.tcp_cluster_rewrite
          typed_config:
            "@type": "type.googleapis.com/istio.envoy.config.filter.network.tcp_cluster_rewrite.v2alpha1.TcpClusterRewrite"
            cluster_pattern: \.cluster2.global$
            cluster_replacement: .cluster.local
  workloadSelector:
    labels:
      istio: eastwestgateway
```
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: multicluster-eastwest
  namespace: istio-system
spec:
  selector:
    istio: eastwestgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 32022
      name: tls
      protocol: TLS
    tls:
      mode: AUTO_PASSTHROUGH
    hosts:
    - "*.global"
    - "*.local"
---
```
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews
  namespace: bookinfo-backends
spec:
  host: reviews.bookinfo-backends.svc.cluster.local
  subsets:
  - name: version-v3
    labels:
      version: v3
  - name: version-v2
    labels:
      version: v2
  - name: version-v1
    labels:
      version: v1
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
```
