### ISSUE TITLE
Visibility of Sidecar, DestinationRule, ServiceEntry and VirtualServices

### ISSUE THREAD

**Issue by sschepens** [istio/istio#40620]
### Bug Description

Take the following scenario:

We have two services with destinationrules each in it's own namespace and we expose those services vía a VirtualService in another namespace.
We then have a workload attempting to consume that VirtualService and using Sidecar resourse to allow that VirtualService.

Service Foo:
```yaml
name: foo
namespace ns1
```

DestinationRule Foo:
```yaml
name: foo
namespace ns1
```

Service Bar:
```yaml
name: bar
namespace: ns2
```

DestinationRule Bar:
```yaml
name: bar
namespace ns2
```

VirtualService:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: foo-bar.example.com
  namespace: ns3
spec:
  hosts:
  - foo-bar.example.com
  http:
  - route:
    - destination:
        host: foo
    match:
    - uri:
        prefix: /foo
  - route:
    - destination:
        host: bar
    match:
    - uri:
        prefix: /bar
```

Sidecar:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: baz
  namespace: ns4
spec:
  egress:
  - hosts:
    - istio-system/*
    - ns3/foo-bar.example.com
```

Given this scenario, our logic tells us that, by allowing `baz` to consume `ns3/foo-bar.example.com` communication would work.
What apparently seems to happen is that Istio [allows the VirtualService](https://github.com/istio/istio/blob/master/pilot/pkg/model/sidecar.go#L467), but [does not allow the Services](https://github.com/istio/istio/blob/master/pilot/pkg/model/sidecar.go#L469), because no Service matches the configured egress hosts.
This behaviour seems a bit weird in our case, since we would have to expose all the VirtualServices we need and also all the Services that are exposed in this VirtualServices as well, this could get very cumbersome in large deployments, which would be our case. It would seem that Istio could do this automatically since the information is already available.

### Version

```prose
Istio 1.14.1
```
