### ISSUE TITLE
Easier way to route to individual StatefulSet pods?

### ISSUE THREAD

**Issue by zarenner** [istio/istio#40664]
We're exploring using Istio with `StatefulSet`, and even though StatefulSets were supposedly [made easier](https://istio.io/v1.10/blog/2021/statefulsets-made-easier), we were surprised at a couple things.

Our hope was that Istio would make it easy to set up an ingress gateway that allowed routing to specific pods in a `StatefulSet`. 

However, we found a couple disappointments:
1. **Need to manually create `ServiceEntry` host for each pod.**
    Without creating a `ServiceEntry`, no envoy clusters are created / `istioctl analyze` gives "Referenced host not found"
    Works fine once manually adding ServiceEntry hosts, e.g: 
    ```
    apiVersion: networking.istio.io/v1alpha3
    kind: ServiceEntry
    metadata:
      name: server-serviceentry
    spec:
      hosts:
      - server-0.server.default.svc.cluster.local
      - server-1.server.default.svc.cluster.local
    ```
   This means though that each time you scale up the `StatefulSet` and add a pod, you have to (manually?) update the `ServiceEntry`.
2. Having to manually create `ServiceEntries` isn't a huge deal, because `VirtualService` also provides no way to address individual pods without creating individual routes, e.g.
    ```
    - match:
      - { uri: { prefix: /0 } }
      route:
      - destination: { host: server-0.server.default.svc.cluster.local }
    - match:
      - { uri: { prefix: /1 } }
      route:
      - destination: { host: server-1.server.default.svc.cluster.local }
    ```
    That is, there's no way to automatically set up a single route that allows addressing each pod individually.

Example at https://github.com/zarenner/istio-statefulset

Besides writing something to automatically update `ServiceEntry` and `VirtualService` resources every time a statefulset changes replica count, is there a better solution here?

**Comment by howardjohn** [comment]
Step 1 should not be needed. can you give a more explicit example of what goes wrong?

Here is my example:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: headless
spec:
  selector:
    matchLabels:
      app: headless
  serviceName: headless
  replicas: 3
  template:
    metadata:
      labels:
        app: headless
    spec:
      containers:
      - name: echo
        image: gcr.io/istio-testing/app:latest
        args:
        - --tcp=7070
        - --tcp=7071
        - --port=8080
        - --grpc=9090
        - --port=8443
        - --tls=8443
        - --server-first=7071
        - --crt=/cert.crt
        - --key=/cert.key
---
apiVersion: v1
kind: Service
metadata:
  name: headless
spec:
  selector:
    app: headless
  clusterIP: None
  ports:
  - name: http
    port: 8080
  - name: https
    port: 8443
  - name: tcp
    port: 7070
  - name: tcp-sf
    port: 7071
  - name: grpc
    port: 9090
```

then
```
$ curl headless-0.headless:8080 headless:8080 headless-1.headless:8080 -s | grep Hostname=
Hostname=headless-0
Hostname=headless-1
Hostname=headless-1
```

**Comment by zarenner** [comment]
I have a complete example repro at:
* k8s manifests: https://github.com/zarenner/istio-statefulset/tree/main/deploy
* Repro script: https://github.com/zarenner/istio-statefulset/blob/main/script/deploy.sh
* Repro test run: https://github.com/zarenner/istio-statefulset/runs/8028112387

If I understand correctly, your `curl` example shows it working within the mesh (that is, on an arbitrary sidecar-enabled pod, DNS correctly resolves for e.g. `headless-0.headless` and traffic routes fine). That also works fine for me in all cases. 

What doesn't work without `ServiceEntry` is `VirtualService` routes applied to a gateway with a destination of e.g. `headless-0.headless` (or `headless-0.headless.default.svc.cluster.local`) and accessed from outside the cluster via ingress gateway. e.g. https://github.com/zarenner/istio-statefulset/blob/main/deploy/minimal/virtualservice.yaml#L19-L26

That is, `curl $(minikube ip)/any` through ingress gateway with a virtualservice destination of `headless` works fine, but `curl $(minikube ip)/0` with a destination of `headless-0.headless` does not without manually added `ServiceEntry`.

**Comment by howardjohn** [comment]
Ah yes that is working as intended. There is no "correct" way to do that. In theory we could have a feature to encode some pattern (in your case /0 -> app-0, etc), but istio does not have that.

Are there any Ingress providers that offer this?

**Comment by zarenner** [comment]
Not especially - someone appears to have gotten this sort of thing working in `ingress-nginx` via snippets, but it's a total hack: https://stackoverflow.com/questions/69410426/when-using-ingress-nginx-in-kubernetes-is-is-possible-to-configure-backends-wit 

There's also a few other requests / questions around ingress-nginx / k8s ingress, but that's about all I've found:
https://github.com/kubernetes/ingress-nginx/issues/7739
https://stackoverflow.com/questions/60753327/nginx-ingress-controller-for-multiple-service-for-branch-wise-deployment
https://stackoverflow.com/questions/66770459/kubernetes-ingress-with-dynamic-routing

Totally expected the "pattern-based backend routing" part of this to be a feature request (it is an uncommon use case), but you're saying it's also expected that `ServiceEntry` needs to be manually created as well to target an individual StatefulSet pod via a VirtualService? I think our confusion there came from the blog text at https://istio.io/v1.10/blog/2021/statefulsets-made-easier:
> The Istio community has been making gradual progress towards zero-configuration support for StatefulSets; from automatic mTLS, to eliminating the need to create DestinationRule or ServiceEntry resources. . .

Assuming everything is working as intended and any improvements here are unlikely to be prioritized soon, feel free to close this issue. We'll likely implement some mechanism (e.g. k8s controller) to automatically create new `VirtualService` and `ServiceEntry` resources during scaling.

Thanks!

**Comment by howardjohn** [comment]
I see where the confusion is - the blog (and my assumption until reading this) was purely focused on mesh use cases. Previously what I showed in my example didn't work properly. I think its a valid feature request, although there isn't any obvious mechanism that comes to mind to implement it.

Curious, do you need the pattern to be in the url or could header, etc also serve the same purpose?

**Comment by zarenner** [comment]
For our use case, subdomain (e.g. `headless-0.foo.com` -> `headless-0.headless.default.svc.cluster.local`) is probably preferable or at least equal to path. Arbitrary header (`headless.foo.com` w/ `X-Specific-Pod: headless-0`) technically could work as we have full control over our clients, but isn't ideal IMO as it would complicate logging and such.

**Comment by littlehorse-eng** [comment]
Plus 1 to this issue. I have a statefulset that contains partitioned data, and the clients are aware of which server/pod owns which partition key.

The application is offered as a cloud service, which means that it will be exposed over ingress. (Interestingly, it is a grpc api that also utilizes Istio's mtls authentication, which is another weird case cf: https://github.com/istio/istio/issues/25437).

My Gateway looks like: 

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: lh-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 5000
      name: lhall
      protocol: TLS
    tls:
      mode: MUTUAL
      credentialName: lh-server-credential
    hosts:
    - "*.demo.littlehorse.cloud"
```

And I have a statefulset named "lh-server"

And my VirtualServices look like:

```
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: lh-server-0
  namespace: default
spec:
  hosts:
  - "lh-0.demo.littlehorse.cloud"
  gateways:
  - lh-gateway
  tcp:
  - match:
    - port: 5000
    route:
    - destination:
        port:
          number: 5000
        host: lh-server-0.default

```
And so on for all of the various entries. (I am working on a K8s Operator to create/delete the supporting VirtualServices as I scale up and down).

There was some EXTREMELY confusing behavior. When I send requests to `lh-0.demo.littlehorse.cloud`, they are round-robin loadbalanced across all of my statefulset instances.

I will try a workaround with the ServiceEntry as described above and report whether it works or not.

**Comment by howardjohn** [comment]
With https://kubernetes.io/docs/reference/labels-annotations-taints/#apps-kubernetes.io-pod-index this is a bit easier:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: statefulset
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: statefulset
spec:
  hosts:
  - "*"
  gateways:
  - statefulset
  http:
  - match:
    - { uri: { prefix: /0 } }
    route:
    - destination: { host: echo-statefulset, subset: pod-0 }
  - match:
    - { uri: { prefix: /1 } }
    route:
    - destination: { host: echo-statefulset, subset: pod-1 }
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: statefulset
spec:
  host: echo-statefulset
  subsets:
  - name: pod-0
    labels:
      apps.kubernetes.io/pod-index: "0"
  - name: pod-1
    labels:
      apps.kubernetes.io/pod-index: "1"
```

Note no ServiceEntry needed. This means no DNS lookups needed
