### ISSUE TITLE
Set GOMEMLIMIT

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#40676]
New feature in 1.19, should be useful for us

https://github.com/KimMachineGun/automemlimit _might_ allow auto-detect in k8s, but needs  testing. We can also do it via helm/downward api/etc, but may be more complex

**Comment by hzxuzhonghu** [comment]
This pkg looks very early stage, we should use a mature one

**Comment by afirth** [comment]
i think downward API is pretty straightforward too. haven't tried it with `divisor`
```yaml
spec:
  template:
    spec:
      containers:
      - name: <container-name>
        env:
        - name: GOMEMLIMIT
          valueFrom:
            resourceFieldRef:
              containerName: <container-name>
              resource: limits.memory #or requests
```
(untested)
