### ISSUE TITLE
Broken Version Routing in a Multicluster Service Mesh

### ISSUE THREAD

**Issue by seanmcguigan** [istio/istio#40673]
### Bug Description

Hi, Following Multi-Primary on different networks documentation:
https://istio.io/latest/docs/setup/install/multicluster/multi-primary_multi-network/

Before you begin followed:
https://istio.io/latest/docs/setup/install/multicluster/before-you-begin/
Plug in CA Certificates followed:
https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/

The version toggle between v1 and v2 is as expected. :smile: 
```
Hello version: v2, instance: helloworld-v2-79bf565586-5ffrz
Hello version: v1, instance: helloworld-v1-77cb56d4b4-kl6lr
```
However, if I want to only route to `v1` of helloworld via a destination rule and a virtualservice, failure occurs. :cry: 
```
HTTP/1.1 503 Service Unavailable
...
upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: TLS error: 33554536:system library:OPENSSL_internal:Connection reset by peer
```
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: hello
  namespace: sample
spec:
  hosts:
  - helloworld.example.com
  gateways:
  - default-gateway
  http:
  - name: default
    route:
    - destination:
        host: helloworld.sample.svc.cluster.local
        subset: eu
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: hello
  namespace: sample
spec:
  host: helloworld.sample.svc.cluster.local
  subsets:
  - name: eu
    labels:
      version: v1
  - name: au
    labels:
      version: v2
```

### Version

```prose
istio version
client version: 1.14.3
control plane version: 1.14.3
data plane version: 1.14.3 (4 proxies)

k8s version
Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.24.3
```

### Additional Information

```
istioctl --context au proxy-config endpoint sleep-69cfb4968f-8xs4j.sample | grep helloworld
172.17.0.6:5000                                         HEALTHY     OK                outbound|5000|au|helloworld.sample.svc.cluster.local
172.17.0.6:5000                                         HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
192.168.59.201:15443                                    HEALTHY     OK                outbound|5000|eu|helloworld.sample.svc.cluster.local
192.168.59.201:15443                                    HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
```
![image](https://user-images.githubusercontent.com/5500767/186919505-8cbf8aee-9fea-4d73-a90a-f09421ade3bf.png)

I found this documentation https://istio.io/latest/blog/2019/multicluster-version-routing/ which mentions `.global` and seem a little out of date.
