### ISSUE TITLE
Jwt issuer is not configured

### ISSUE THREAD

**Issue by drduker** [istio/istio#40718]
### Bug Description

I have these rules defined in for my ingress gateway:
When my app , which is in it's own namespace, is loading it gets block on the gateway with this error "Jwt issuer is not configured".  I clearly have issuer's defined so I'm confused.  Please help.
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: jwt-rule
  namespace: istio-system
spec:
  rules:
  - from:
    - source:
        requestPrincipals:
        - '*'
  selector:
    matchLabels:
      protect: authservice
---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: jwt-rule
  namespace: istio-system
spec:
  jwtRules:
  - forwardOriginalToken: true
    issuer: https://keycloak.example.com/auth/realms/test
    jwks: '..removed..'
  - forwardOriginalToken: true
    issuer: https://app.example.com
    jwksUri: https://app.example.com/v1/.well-known/jwks.json
  selector:
    matchLabels:
      protect: authservice
```

### Version

```prose
client version: 1.14.3
control plane version: 1.13.5
data plane version: 1.13.4 (1 proxies), 1.13.5 (40 proxies), 1.13.2 (1 proxies)
Client Version: v1.24.3
Kustomize Version: v4.5.4
Server Version: v1.22.10-eks-84b4fe6
```

### Affected product area

- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [X] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by drduker** [comment]
I need a known working example of two jwt's in use.

**Comment by aryan16** [comment]
The selector you have used ‘protect:authservice’, is the same selector present in the ingress gateway ? And please share the istiod logs and envoy config dump

**Comment by aryan16** [comment]
And please check if your issue is because of the 1st reason mentioned  here  https://istio.io/latest/docs/ops/common-problems/security-issues/#end-user-authentication-fails

**Comment by drduker** [comment]
Also, I'm not cycling the gateway's pods because of this error:
```Envoy proxy is NOT ready: config received from XDS server, but was rejected: cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 1 rejected```
I will post logs and configs shortly.

**Comment by foreachlife** [comment]
The authorization name is not fixed and is defined by your request header。
but the prefix must be "Bearer "。 

`
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata: 
  name: authentication-jwt-token
  namespace:  test
spec: 
  jwtRules: 
    - 
      forwardOriginalToken: true
      fromHeaders: 
        - 
          name: Authorization
          prefix: "Bearer "
`

https://istio.io/latest/docs/reference/config/security/jwt/

**Comment by foreachlife** [comment]
The authorization name is not fixed and is defined by your request header。
but the prefix must be "Bearer "。

```
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata: 
  name: authentication-jwt-token
  namespace: test
spec: 
  jwtRules: 
    - 
      forwardOriginalToken: true
      fromHeaders: 
        - 
          name: Authorization
          prefix: "Bearer "
```

https://istio.io/latest/docs/reference/config/security/jwt/
