### ISSUE TITLE
directResponse functionality doesn't work

### ISSUE THREAD

**Issue by bananaappletw** [istio/istio#40754]
### Bug Description

When I follow the tutorial from official website, I found `directResponse` functionality doesn't work as expected.

https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPDirectResponse

Manifest I applied:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ratings-route
spec:
  hosts:
  - ratings.prod.svc.cluster.local
  http:
  - match:
    - uri:
        exact: /v1/getProductRatings
    directResponse:
      status: 503
      body:
        string: "unknown error"
```

Error log:

```
error: error validating "demo": error validating data: ValidationError(VirtualService.spec.http[0]): unknown field "directResponse" in io.istio.networking.v1alpha3.VirtualService.spec.http; if you choose to ignore these errors, turn validation off with --validate=false
```

### Version

```prose
$ istioctl version
client version: 1.14.3
control plane version: 1.14.1
data plane version: 1.14.1 (2 proxies)
$ kubectl version --short
Client Version: v1.21.5
Server Version: v1.22.11-gke.400
```
