### ISSUE TITLE
Support `regex` on the `Sidecar::IstioEgressListener::hosts`

### ISSUE THREAD

**Issue by qudongfang** [istio/istio#40767]
**Describe the feature request**

Support `regex` on the [`Sidecar::IstioEgressListener::hosts`](https://istio.io/latest/docs/reference/config/networking/sidecar/#IstioEgressListener).

Current state:
> One or more service hosts exposed by the listener in namespace/dnsName format.

> The dnsName should be specified using FQDN format, optionally including a wildcard character in the left-most component (e.g., prod/*.example.com). Set the dnsName to * to select all services from the specified namespace (e.g., prod/*).

Use case: Our ServiceEntry host format is something like `${serviceName}-${protocol}.${namespace}.${region}.${provider}.kube`(Multi provider & Multi Region), and we want to setup `Sidecar` per `Service/Deployment` to let `istio-proxy` setup the listeners of required `Service`s only.

It would be great to have the following `Sidecar` config working.

```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: echo-sidecar
  namespace: echo-dev
spec:
  egress:
  - hosts:
    - 'hello-namespace/hello-*.gcp.kube'
  workloadSelector:
    labels:
      app.kubernetes.io/instance: echo
      app.kubernetes.io/name: echo
```

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
