### ISSUE TITLE
Outlier detection based on percentage for clients with diverse TPS, hence outlier detection requirements. 

### ISSUE THREAD

**Issue by nirvanagit** [istio/istio#40785]
**Describe the feature request**
Services with a diverse set of clients, which have different TPS requirements, need different outlier detection policies for automatic failover to take effect.

Today, destination rules provides the following configurations for defining outlier detection ([list](https://istio.io/latest/docs/reference/config/networking/destination-rule/#OutlierDetection)):

1. consecutive5xxErrors
2. consecutiveLocalOriginFailures
3. consecutiveGatewayErrors

If we consider using consecutive5xxErrros, then a high TPS client might need the value to be: 100, but for a low TPS client, the value could be 10.

In order to have a single configuration for catering to both types of clients, it would be easy to define outlier detection based on a percentage. For e.g. have a value of 5 (percent) for both the clients, so that if 5 % of the requests fail for either of the client, the outlier detection should kick in.

Envoy provides an option to detect an outlier based on percentage, as documented here - https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/outlier#failure-percentage 

I have the following questions:
Is it possible to enable this rule without using DestinationRule, as we are currently limited by what is exposed by Istio
Can this configuration be exposed via DestinationRules?

**Describe alternatives you've considered**
Continue using the numerical values, and maintain different DestinationRules for each client which differs significantly in TPS. But this is not a scalable solution, and adds a lot of maintenance overhead. 

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Comment by ramaraochavali** [comment]
you can create an [Envoy filter](https://github.com/istio/api/blob/master/networking/v1alpha3/envoy_filter.proto) to set failure percentage

Other option is to have specific Destination rule for each client using [work load selector](https://github.com/istio/api/blob/master/networking/v1alpha3/destination_rule.proto#L302)

**Comment by nirvanagit** [comment]
@ramaraochavali - but DRs do not have support for failure percentage? Reference: https://istio.io/latest/docs/reference/config/networking/destination-rule/#OutlierDetection

**Comment by ramaraochavali** [comment]
> If we consider using consecutive5xxErrros, then a high TPS client might need the value to be: 100, but for a low TPS client, the value could be 10.

I am saying set this via DR for each client

**Comment by nirvanagit** [comment]
> 

Sorry if I misunderstood, but I don't see percentage based outlier detection in the configuration supported by DestinationRule - https://istio.io/latest/docs/reference/config/networking/destination-rule/#OutlierDetection

**Comment by nirvanagit** [comment]
> > If we consider using consecutive5xxErrros, then a high TPS client might need the value to be: 100, but for a low TPS client, the value could be 10.
> 
> I am saying set this via DR for each client

That is one approach, but then it becomes difficult to maintain DRs per client.

**Comment by nirvanagit** [comment]
@ramaraochavali Is there an example you can provide for enabling this via Envoyfilter?

**Comment by ramaraochavali** [comment]
I do not have an example envoy filter - but should be easy to write one.

**Comment by nirvanagit** [comment]
Thanks Rama for the example:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: outlier-on-percentage 
  namespace: default
spec:
  configPatches:
  - applyTo: CLUSTER
    patch:
      operation: MERGE
      value:
        outlier_detection:
          failure_percentage_threshold: 84
  workloadSelector:
    labels:
      app: productpage
```

While testing on vanilla envoy, I realized there are other important configurations for outlier detection to kick in based on percentages. Specifically, `failure_percentage_request_volume`, which is an absolute value.

I have the following envoy configuration for testing outlier based on failure percentage:
```yaml
    outlier_detection:
      failure_percentage_threshold: "100"
      enforcing_failure_percentage: "100"
      enforcing_failure_percentage_local_origin: 100
      failure_percentage_minimum_hosts: 0
      failure_percentage_request_volume: 2
      
     # ejection configuration not related to failure percentage
     # based ejection
      consecutive_5xx: 100
      consecutive_local_origin_failure: 100
      consecutive_gateway_failure: 100
      enforcing_consecutive_gateway_failure: 100

      base_ejection_time: "30s"
```

In the configuration above, I had to set `failure_percentage_request_volume` to `2` to see the percentage based outlier detection to kick in. Initially I thought that I would just have to set a percentage, which will kick in ejection based on a period of time, and calculate the volume based on the total number of requests over that period of time. But here, envoy asks us to specify the volume over which the percentage will be calculated on. 

Is there any other way I can achieve pure percentage based (over a time) ejections, considering clients with varying TPS ?
