### ISSUE TITLE
Egress workload credential usecase not working since 1.15.0

### ISSUE THREAD

**Issue by LithiumSR** [istio/istio#40801]
### Bug Description

Hello everyone.
I have noticed from my testing that an egress scenario that uses the workload credential is not working anymore since 1.15.0 release (1.14.3 was tested to work fine).
The issue itself lead to the curl request targeting the out-of-mesh svc to return 
```
"upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED".
```
The scenario is also described in the istio doc: https://istio.io/latest/docs/tasks/traffic-management/egress/egress-tls-origination/#mutual-tls-origination-for-egress-traffic
I have verified that the issue has started showing up since #39133 (@howardjohn).

In order to reproduce the issue I have prepared the following steps (resources: [repro.tar.gz](https://github.com/istio/istio/files/9488746/repro.tar.gz)):
- Deploy a KinD cluster or have a cluster already ready
- Install a Istio 1.15.0 instance
- Execute the script that creates: certificates, sleep, sleep-role, sleep-rolebinding, nginx, nginx conf.
`sh script.sh`
- Run a curl request `kubectl -n test exec "$(kubectl -n test get pod -l app=sleep -o jsonpath={.items..metadata.name})" -c sleep -- curl -s http://my-nginx.mesh-external.svc.cluster.local:31443`
- Check that the curl request failed as mentioned.

Is the change in intentional consequence of the PR or is that a bug?

### Version

```prose
client version: 1.15.0
control plane version: 1.15.0
data plane version: 1.15.0 (3 proxies)
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"1f86634ff08f37e54e8bfcd86bc90b61c98f84d4", GitTreeState:"clean", BuildDate:"2021-11-17T14:35:38Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

### Additional Information

[bug-report.tar.gz](https://github.com/istio/istio/files/9488783/bug-report.tar.gz)

**Comment by kfaseela** [comment]
@LithiumSR As discussed offline, this use case is the one described in Istio egress doc at: https://istio.io/latest/docs/tasks/traffic-management/egress/egress-tls-origination/#mutual-tls-origination-for-egress-traffic

And the doc tests seem to be passing for the same. Let us check what is different in the current script.

**Comment by LithiumSR** [comment]
@kfaseela 
The difference between the two scripts is that the one I attached is also using a ServiceEntry
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: first-service-entry
spec:
  exportTo:
  - .
  hosts:
  - my-nginx.mesh-external.svc.cluster.local
  location: MESH_EXTERNAL
  ports:
  - name: http-port-for-tls-origination
    number: 443
    protocol: HTTP
  resolution: NONE
```
The script for the egress doc page is also failing once you add the SE

**Comment by howardjohn** [comment]
il try to reproduce it but would be helpful if you could include your script

**Comment by howardjohn** [comment]
Ok thanks - I missed the script before. I can reproduce thanks

**Comment by howardjohn** [comment]
After looking into it, I am not 100% sure what the _expected_ behavior is, but the old behavior is definitely broken. The new behavior is also broken for different reasons.

1.14 behavior:
* initServiceAccounts loops over all services; SE comes last
* First svc is k8s one (always), set SAs. Next is ServiceEntry, overwrite it with empty list

1.15 behavior (with NONE):
* initServiceAccounts loops over all services; SE comes last
* First svc is k8s one (always), set SAs. SE isn't in EDS index, so no SA found to overwrite
* We build two clusters, SE first then K8s; first one wins. 
* SE one gets SAN set to the k8s one from PushContext AND from a bug of TLS mutating the DestinationRules in store (mentioned below)
* `subjectAltNames` does nothing since its not part of the EDS index

1.15 behavior (with explicit SA):
* initServiceAccounts loops over all services; SE comes last
* First svc is k8s one (always), set SAs. SE overwrites with it's SA
* We build two clusters, SE first then K8s; first one wins
* However, depending on order of events, the Destinationrule may already be mutated to have `subjectAltNames` set, which is broken

Shards are by namespace, so we store the two differently. Behavior would be different if we were in the same namespace?

There seem to be some ordering bugs, especially around changing SE from NONE to STATIC. Seems one bug is we are mutating the DestinationRule stored in memory

**Comment by howardjohn** [comment]
Overall we have a big mess of using one service in some places, and the other in other places, and endless confusion from those.

One thing I would recommend is not having a ServiceEntry and Service for the same host in general.

However, even without the mismatch between those, this is still broken:

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  generation: 6
  name: first-service-entry2
  namespace: test
spec:
  exportTo:
  - .
  hosts:
  - my-nginx2.mesh-external.svc.cluster.local
  location: MESH_EXTERNAL
  ports:
  - name: http-port-for-tls-origination
    number: 31443
    protocol: HTTP
  resolution: NONE
  subjectAltNames: [spiffe://foo]
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: first-destination-rule
  namespace: test
spec:
  exportTo:
  - .
  host: my-nginx2.mesh-external.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 31443
      tls:
        credentialName: sleep-certs
        mode: MUTUAL
        sni: my-nginx.mesh-external.svc.cluster.local
  workloadSelector:
    matchLabels:
      app: sleep
```

`subjectAltNames` is ignored
