### ISSUE TITLE
Configure Access Log Format with Telemetry API

### ISSUE THREAD

**Issue by sabz90** [istio/istio#40823]
I have enabled access logging (Envoy) using the yaml with Telemetry API:

```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: gw-access-log
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  accessLogging:
    - providers:
      - name: envoy
```

I did not find a way to configure access log format via the telemetry API, so I configured it via the IstioOperator resource:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  ...
spec:
  meshConfig:
     accessLogFormat : <my-new-access-log-format>
```

In spite of doing that, The logs are still coming in the default format. I did a config_dump from the istio_ingressgateway and I still see the default format :

```

"typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog",
               "path": "/dev/stdout",
               "log_format": {
                "text_format_source": {
                 "inline_string": "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% \"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%\n"
                }
               }
              }
```

Is there a way to configure the format via the telemetry API for istio/Envoy?

**Comment by zirain** [comment]
we change the behavior in https://github.com/istio/istio/pull/39606
for now, you should add `ExtensionProvider` without name `envoy`, and reference it in `Telemetry` api.

**Comment by sabz90** [comment]
@zirain Thanks for taking a look. 
Unfortunately, I won't be able to upgrade istio in our system now and I'm stuck with 1.14

I didn't quite catch your statement here:
`for now, you should add ExtensionProvider without name envoy, and reference it in Telemetry api.`

Can you please elaborate? Pointers to any documentation would be great.

**Comment by zirain** [comment]
no need for upgrade istio

1. update you IstioOperator spec with following:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
   # add new ExtensionProvider name `file-log`
    extensionProviders:
      - name: file-log
        envoyFileAccessLog:
          path: /dev/stdout
          logFormat:
            text: "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% \"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%\n"
```
2. create an `Telemetry` spec to apply `file-log` mesh wide
```yaml
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  accessLogging:
    - providers:
        - name: file-log
```

**Comment by zirain** [comment]
@sabz90 can we close this?

**Comment by zirain** [comment]
closed as fixed, feel free to reopen.

**Comment by l-rossetti** [comment]
I don't have istio-operator since istio documentation suggests to go with other installation methods. How can I configure the logFormat in that case?

**Comment by l-rossetti** [comment]
For completeness, for those who do not run the operator, it is true that you can add the operator's CRD, but I have found an alternative approach that does not require this.

By installing `istiod` via the Helm chart, logging can be configured using the following values:


``` yaml
meshConfig: # https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/
  accessLogFile: /dev/stdout
  accessLogEncoding: JSON # TEXT or JSON
  accessLogFormat: |
    {"traceID": "%REQ(x-b3-traceid)%","protocol": "%PROTOCOL%","upstream_service_time": "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%","upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%","duration": "%DURATION%","upstream_transport_failure_reason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%","route_name": "%ROUTE_NAME%","downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%","user_agent": "%REQ(USER-AGENT)%","response_code": "%RESPONSE_CODE%","response_flags": "%RESPONSE_FLAGS%","start_time": "%START_TIME%","method": "%REQ(:METHOD)%","request_id": "%REQ(X-REQUEST-ID)%","upstream_host": "%UPSTREAM_HOST%","x_forwarded_for": "%REQ(X-FORWARDED-FOR)%","requested_server_name": "%REQUESTED_SERVER_NAME%","bytes_received": "%BYTES_RECEIVED%","istio_policy_status": "-","bytes_sent": "%BYTES_SENT%","upstream_cluster": "%UPSTREAM_CLUSTER%","downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%","authority": "%REQ(:AUTHORITY)%","path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"}
```

This allows providing a default logging configuration for gateway components (e.g., `ingressGateway`, `waypoint`, etc.).

Another alternative is to define, within the `istiod` Helm chart values, an extension provider with its own logging format. This provider can then be referenced by a `Telemetry` object that enables logging for a specific namespace or workload:

``` yaml
extensionProviders: # value in istiod helm chart
    - name: access-logs
      envoyFileAccessLog:
        path: /dev/stdout
        logFormat:
          text: "test-log" # https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#config-access-log-format-dictionaries
```

Then, in the `Telemetry` object:

``` yaml
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: access-logs
  namespace: istio-system
spec:
  accessLogging:
  - providers:
    - name: access-logs
```

This method allows more flexibility by defining custom logging formats through an extension provider and then applying it selectively using `Telemetry`.

@zirain the provided examples work only for gateway components, not for `ztunnel` (I'm running Istio in `ambient` mode). Is it possibile to customise the logging format also for `ztunnels`?

**Comment by zirain** [comment]
> Is it possibile to customise the logging format also for ztunnels?

not for now

**Comment by Sridharpage** [comment]
@zirain , could you please clarify how to achieve this as you suggested earlier? I tried a few approaches but couldn’t get it to work. I’m currently using Istio 1.28.0 in Ambient mode.

> you can still use istiooperator crd with istioctl.

**Comment by zirain** [comment]
Clarify what? Ztunnel support of Telemetry API?

**Comment by Sridharpage** [comment]
Considering the IstioOperator spec below, I attempted to apply it to an existing Istio installation on the cluster using `istioctl install` and `istioctl upgrade`. However, both commands seem to trigger a full Istio reinstall. Based on your previous comment (https://github.com/istio/istio/issues/40823#issuecomment-2656480197), I’d like to understand the correct way to apply this configuration. I’m currently using Istio 1.28.0 in Ambient mode.

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
   # add new ExtensionProvider name `file-log`
    extensionProviders:
      - name: file-log
        envoyFileAccessLog:
          path: /dev/stdout
          logFormat:
            text: "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% \"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%\n"
```
