### ISSUE TITLE
"authenticationpolicy.yaml": Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod-asm-1118-4.istio-system.svc:443/validate?timeout=10s": service "istiod-asm-1118-4" not found. 

### ISSUE THREAD

**Issue by pablofiumara** [istio/istio#40868]
### Bug Description

I am getting that error when I try to execute

`kubectl apply -f file.yaml`

file.yaml is
```

apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  annotations:
    role: edit
    user: oneEmail.com # replace with the email of the user from your Active Directory case sensitive
  name: user-one-Email-com-clusterrole-edit
  namespace: kubeflow # replace with the namespace/profile name that you are adding contributors to
spec:
  action: ALLOW
  rules:
  - when:
    - key: request.headers[x-goog-authenticated-user-email] # for GCP, use x-goog-authenticated-user-email instead of kubeflow-userid for authentication purpose
      values:
      - accounts.google.com:oneEmail.com # replace with the email of the user from your Active Directory case sensitive
```
If I execute
`kubectl get validatingwebhookconfiguration`

I get  one configuration related to the old Istio version. It happens on an upgraded cluster. 

My question is: What should I change to fix it?  I could delete the old configuration. Problem is I installed Istio again and I am not able to replicate it (first I would like to replicate the error, then I would like to fix it)

### Version

```prose
client version: 1.14.3-asm.0
control plane version: 1.14.3
data plane version: 1.14.3-asm.0 (29 proxies)


Client Version: v1.24.3
Kustomize Version: v4.5.4
Server Version: v1.21.14-gke.700
```
