### ISSUE TITLE
Istioctl Analyze reports invalid error for gateway file

### ISSUE THREAD

**Issue by therealmitchconnors** [istio/istio#40861]
### Bug Description

In 1.14.3 and prior, running istioctl analyze against the following file would not report any error.  After merging #37581, it reports `Error [IST0101] (Gateway istio-system/public-gateway public-gateway.yaml:8) Referenced selector not found: "istio=gateway"`

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: public-gateway
  namespace: istio-system
spec:
  selector:
    istio: gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
```

When running analyze against files, we should not be checking for pods, which should never exist as files, but rather for higher level abstractions such as deployments.

### Version

```prose
1.15.0
```
