### ISSUE TITLE
ingress gateway not routing the request to service

### ISSUE THREAD

**Issue by pnateri** [istio/istio#40923]
### Bug Description

Hi Support,

i have a service called admin-portal and i am putting a VS and GW to pass through the istio ingressgateway and the DNS i am using is "portal.dev.expressplay.com". However, i am getting the below error

GET / HTTP/1.1" 503 NC cluster_not_found

**Full error:**
[2022-09-12T07:55:37.414Z] "GET / HTTP/1.1" 503 NC cluster_not_found - "-" 0 0 0 - "49.204.214.237,192.168.45.102" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36" "feca4e51-4480-9aa0-8f2d-8170f6d4c1c3" "[portal.dev.expressplay.com](http://portal.dev.expressplay.com/)" "-" - - 192.168.43.155:8443 192.168.45.102:52941 - -

Below are my config Files:

GW yaml:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: admin-portal
  namespace: intr-dev
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - portal.dev.expressplay.com
    - portal.xpressplay.net
    - portaltest.dev.expressplay.com
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTP
    hosts:
    - portal.dev.expressplay.com
    - portal.xpressplay.net
    - portaltest.dev.expressplay.com
``` 

VS yaml:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: admin-portal
  namespace: intr-dev
spec:
  hosts:
  - "portal.dev.expressplay.com"
  - "portal.xpressplay.net"
  - "portaltest.dev.expressplay.com"
  gateways:
  - admin-portal
  http:
  - route:
    - destination:
        host: admin-portal.intr-dev.svc.cluster.local
        port:
          number: 8080
```
**Service yaml**
```
kind: Service
apiVersion: v1
metadata:
  name: admin-portal
  namespace: intr-dev
  labels:
    app: admin-portal
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: admin-portal
```

Can you please help resolve this issue?

Regards,
Pranav

### Version

```prose
pnateri@C02G70NAMD6M ~ % istioctl version
client version: 1.14.0
control plane version: 1.14.0
data plane version: 1.14.0 (16 proxies)


pnateri@C02G70NAMD6M ~ % kubectl version --short
Client Version: v1.21.2-13+d2965f0db10712
Server Version: v1.21.14-eks-6d3986b
```

### Additional Information

[bug-report.tar.gz](https://github.com/istio/istio/files/9547200/bug-report.tar.gz)

please find the attached bug report
