### ISSUE TITLE
VirtualService Routing Feature for HTTPS Traffic

### ISSUE THREAD

**Issue by JJRdec** [istio/istio#40955]
**Describe the feature request**
It would be great if we could use VirtualService traffic routing for encrypted traffic using path matching as is done with non-encrypted traffic. 

An ideal situation would be to use a config as below for encrypted traffic. 

Example:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: reviews-route
spec:
  hosts:
  - reviews.prod.svc.cluster.local
  https:
  - name: "reviews-v2-routes"
    match:
    - uri:
        prefix: "/wpcatalog"
    - uri:
        prefix: "/consumercatalog"
    route:
    - destination:
        host: reviews.prod.svc.cluster.local
```

**Describe alternatives you've considered**
1. Using TLS Passthrough on gateway with virtual service SNI matching. But this does not suit our use case as we want to use path matching.
2. Use non-encrypt traffic on application with TLS termination on the gateway with virtual service path matching. However, we require traffic to be encrypted when it reaches the application.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
If there is a valid argument to why this feature is not required or even why it is not possible I'd love to hear. 

Many thanks!
