### ISSUE TITLE
DestinationRule merging not working after upgrading from v. 1.13.2 to 1.14.3

### ISSUE THREAD

**Issue by JesperBerggren** [istio/istio#40952]
### Bug Description

We've just upgraded from version 1.13.2 to 1.14.3.

Up until now we've had merging of DestinationRules working flawlessly.

Our scenario for this is that we're using the Istio ingress gateway as an integration layer to ensure security, logging etc. for backend systems (outside Kubernetes) to call an external API.
Depending on what endpoint is called on the Istio gateway we're using different subsets to call the external API with different client certificates.

E.g. (simplified for readability):
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: solution-ingress-gateway-mtls
  namespace: solution
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https-443
      protocol: HTTPS
    tls:
      mode: MUTUAL
      minProtocolVersion: TLSV1_2
      credentialName: solution-certs-ingress-mtls
    hosts:
    - solution.servicemesh.dev.company.local
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: digitalpost-digst
  namespace: digitalpost-afu
spec:
  exportTo:
  - "istio-system"
  hosts:
  - api.test.solution.dk
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: tls-443
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: digitalpost-digst
  namespace: digitalpost-udk
spec:
  exportTo:
  - "istio-system"
  hosts:
  - api.test.solution.dk
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: tls-443
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: solution-ingress-virtualservice-mtls
  namespace: solution-afu
spec:
  exportTo:
  - "istio-system"
  hosts:
  - solution.servicemesh.dev.company.local
  gateways:
  - solution/solution-ingress-gateway-mtls
  http:
  - match:
    - uri:
        prefix: "/afu/apis/"
    rewrite:
      uri: "/apis/"
      authority: api.test.solution.dk
    route:
    - destination:
        host: api.test.solution.dk
        subset: solution-digst-afu
        port:
          number: 443
      headers:
        request:
          set: 
            Authorization: XXX
      weight: 100
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: solution-ingress-virtualservice-mtls
  namespace: solution-udk
spec:
  exportTo:
  - "istio-system"
  hosts:
  - solution.servicemesh.dev.company.local
  gateways:
  - solution/solution-ingress-gateway-mtls
  http:
  - match:
    - uri:
        prefix: "/udk/apis/"
    rewrite:
      uri: "/apis/"
      authority: api.test.solution.dk
    route:
    - destination:
        host: api.test.solution.dk
        subset: solution-digst-udk
        port:
          number: 443
      headers:
        request:
          set: 
            Authorization: XXX
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-mtls-for-solution-digst
  namespace: solution-afu
spec:
  exportTo:
  - "istio-system"
  host: api.test.solution.dk
  subsets:
  - name: solution-digst-afu
    trafficPolicy:
      loadBalancer:
        simple: LEAST_REQUEST
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: MUTUAL
          credentialName: solution-afu-certs-egress-digst-mtls
          sni: api.test.solution.dk
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-mtls-for-solution-digst
  namespace: solution-udk
spec:
  exportTo:
  - "istio-system"
  host: api.test.solution.dk
  subsets:
  - name: solution-digst-udk
    trafficPolicy:
      loadBalancer:
        simple: LEAST_REQUEST
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: MUTUAL
          credentialName: solution-udk-certs-egress-digst-mtls
          sni: api.test.solution.dk
---
```
As you can see there are two different subsets defined in two separate namespaces but exported to the istio-system namespace.

In Istio v. 1.13.2 the configuration was interpreted like this:
```
$ istioctl proxy-config cluster -n istio-system istio-ingressgateway-6779c46896-655qc
SERVICE FQDN                                                                           PORT      SUBSET                          DIRECTION     TYPE           DESTINATION RULE
BlackHoleCluster                                                                       -         -                               -             STATIC         
agent                                                                                  -         -                               -             STATIC         
api.test.solution.dk                                                                   443       -                               outbound      STRICT_DNS     originate-mtls-for-solution-digst.solution-udk
api.test.solution.dk                                                                   443       solution-digst-aes              outbound      STRICT_DNS     originate-mtls-for-solution-digst.solution-aes
api.test.solution.dk                                                                   443       solution-digst-udk              outbound      STRICT_DNS     originate-mtls-for-solution-digst.solution-udk
```
In Istion v. 1.14.3 the configuration is like this:
```
$ istioctl proxy-config cluster -n istio-system istio-ingressgateway-79f6886b46-8xmtm
SERVICE FQDN                                                                           PORT      SUBSET                          DIRECTION     TYPE           DESTINATION RULE
BlackHoleCluster                                                                       -         -                               -             STATIC         
agent                                                                                  -         -                               -             STATIC         
api.test.solution.dk                                                                   443       -                               outbound      STRICT_DNS     originate-mtls-for-solution-digst.solution-udk
api.test.solution.dk                                                                   443       solution-digst-aes              outbound      STRICT_DNS     originate-mtls-for-solution-digst.solution-aes
```
Notice that it now only knows the first subset!?

I found this issue: https://github.com/istio/istio/issues/22997 but switching to the Kubernetes gateway-api seems like a huge step. 
I also found this in the release notes for v. 1.14: 

> Fixed the problem that xDS may not be updated if multiple destinationRules for a service are merged. In this case the merged rule only records one name/namespace pair of all the destinationRules. However, this meta is used to record config dependencies of a sidecar.

> In this fix, we introduce a new struct consolidatedDestRule and record all the destinationrules’ meta to avoid missing any destinationRule dependencies. ([Issue #38082](https://github.com/istio/istio/issues/38082))

Can anybody give some insights on why the merging no longer works?

Best regards
Jesper Berggren

### Version

```prose
$ istioctl version
client version: 1.14.3
control plane version: 1.14.3
data plane version: 1.14.3 (31 proxies)
```

**Comment by howardjohn** [comment]
cc @hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
I will take a look

**Comment by hzxuzhonghu** [comment]
In both 1.13 and 1.16, i only get the 
```
root@opensrc:~# istioctl pc cluster istio-ingressgateway-57dd48786c-dwmj9 -n istio-system |grep api.test.solution.dk
api.test.solution.dk                                                  443       -          outbound      STRICT_DNS 
```

**Comment by hzxuzhonghu** [comment]
Added tests for this in https://github.com/istio/istio/pull/40980

**Comment by JesperBerggren** [comment]
I wonder if I simplified the yaml too much. I'll try to redeploy it in a clean cluster.
I'll get back later.
//Jesper

**Comment by JesperBerggren** [comment]
Hey again,

I've made the yaml configuration complete and easily deployable on both Istio v. 1.13.2 and 1.14.3.
This is it:
```
kind: Namespace
apiVersion: v1
metadata:
  name: solution-afu
  labels:
    name: solution-afu
    istio-injection: enabled
---
kind: Namespace
apiVersion: v1
metadata:
  name: solution-udk
  labels:
    name: solution-udk
    istio-injection: enabled
---
kind: Namespace
apiVersion: v1
metadata:
  name: solution
  labels:
    name: solution
    istio-injection: enabled
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: solution-ingress-gateway-mtls
  namespace: solution
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https-443
      protocol: HTTPS
    tls:
      mode: MUTUAL
      minProtocolVersion: TLSV1_2
      credentialName: solution-certs-ingress-mtls
    hosts:
    - solution.servicemesh.dev.company.local
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: solution-digst
  namespace: solution-afu
spec:
  exportTo:
  - "istio-system"
  hosts:
  - api.test.solution.dk
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: tls-443
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: solution-digst
  namespace: solution-udk
spec:
  exportTo:
  - "istio-system"
  hosts:
  - api.test.solution.dk
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: tls-443
    protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: solution-ingress-virtualservice-mtls
  namespace: solution-afu
spec:
  exportTo:
  - "istio-system"
  hosts:
  - solution.servicemesh.dev.company.local
  gateways:
  - solution/solution-ingress-gateway-mtls
  http:
  - match:
    - uri:
        prefix: "/afu/apis/"
    rewrite:
      uri: "/apis/"
      authority: api.test.solution.dk
    route:
    - destination:
        host: api.test.solution.dk
        subset: solution-digst-afu
        port:
          number: 443
      headers:
        request:
          set: 
            Authorization: XXX
      weight: 100
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: solution-ingress-virtualservice-mtls
  namespace: solution-udk
spec:
  exportTo:
  - "istio-system"
  hosts:
  - solution.servicemesh.dev.company.local
  gateways:
  - solution/solution-ingress-gateway-mtls
  http:
  - match:
    - uri:
        prefix: "/udk/apis/"
    rewrite:
      uri: "/apis/"
      authority: api.test.solution.dk
    route:
    - destination:
        host: api.test.solution.dk
        subset: solution-digst-udk
        port:
          number: 443
      headers:
        request:
          set: 
            Authorization: XXX
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-mtls-for-solution-digst
  namespace: solution-afu
spec:
  exportTo:
  - "istio-system"
  host: api.test.solution.dk
  subsets:
  - name: solution-digst-afu
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: MUTUAL
          credentialName: solution-afu-certs-egress-digst-mtls
          sni: api.test.solution.dk
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-mtls-for-solution-digst
  namespace: solution-udk
spec:
  exportTo:
  - "istio-system"
  host: api.test.solution.dk
  subsets:
  - name: solution-digst-udk
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: MUTUAL
          credentialName: solution-udk-certs-egress-digst-mtls
          sni: api.test.solution.dk
---
```

On v. 1.13.2 it gives me this configuration of the ingressgateway:
```
$ istioctl proxy-config cluster -n istio-system istio-ingressgateway-f589d66b6-q8k7f
SERVICE FQDN                                                      PORT      SUBSET                          DIRECTION     TYPE           DESTINATION RULE
BlackHoleCluster                                                  -         -                               -             STATIC         
agent                                                             -         -                               -             STATIC         
api.test.solution.dk                                              443       -                               outbound      STRICT_DNS     originate-mtls-for-solution-digst.solution-afu
api.test.solution.dk                                              443       solution-digst-afu              outbound      STRICT_DNS     originate-mtls-for-solution-digst.solution-afu
api.test.solution.dk                                              443       solution-digst-udk              outbound      STRICT_DNS     originate-mtls-for-solution-digst.solution-udk
```

On v. 1.14.3 it gives me this configuration of the ingressgateway:
```
$ istioctl proxy-config cluster -n istio-system istio-ingressgateway-7b4969b798-7qd5d
SERVICE FQDN                                                      PORT      SUBSET                          DIRECTION     TYPE           DESTINATION RULE
BlackHoleCluster                                                  -         -                               -             STATIC         
agent                                                             -         -                               -             STATIC         
api.test.solution.dk                                              443       -                               outbound      STRICT_DNS     originate-mtls-for-solution-digst.solution-afu
api.test.solution.dk                                              443       solution-digst-afu              outbound      STRICT_DNS     originate-mtls-for-solution-digst.solution-afu
```

I does indeed work on 1.13.2 but no longer on 1.14.3.

I should mention that I deploy the yaml file on 1.13.2 and afterwards _upgrades_ Istio after which it no longer works.

Furthermore I've installed Istio with the following options (among many other but these seem relevant to mention):
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  meshConfig:
    enableAutoMtls: true
    defaultServiceExportTo: ["."]
    defaultVirtualServiceExportTo: ["."]
    defaultDestinationRuleExportTo: ["."]
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
```

Best regards
Jesper Berggren
