### ISSUE TITLE
Can't use header from AuthorizationPolicy in VirtualService match

### ISSUE THREAD

**Issue by ethanchowell** [istio/istio#40954]
### Bug Description

I have a VirtualService, which defines a route match that must have a header present. This header is injected from the output of an AuthorizationPolicy with a `CUSTOM` action pointing at an internal plugin which does some stuff with PKI from `x-forwarded-client-cert`. I never match on this route, and see the following logs in my ingress gateway.

```shell
GET /headers HTTP/2" 404 NR route_not_found - ... 
```

Instead, I've tried using an EnvoyFilter to counter this, but it doesn't appear that I'm able to inject an ext.authz filter before the http connection manager.

See below for examples.

### Version

```prose
client version: 1.15.0
control plane version: 1.15.0
data plane version: 1.15.0 (20 proxies)
```

### Additional Information

For the sake of example, lets say my auth plugin talks over grpc with envoyproxy v3 and injects the header `X-TEST-HEADER: SUCCESS`. I'm using the [httpbin example](https://github.com/istio/istio/tree/master/samples/httpbin), with the following mesh config.

```yaml
extensionProviders:
  - name: "ext-authz-plugin"
    envoyExtAuthzGrpc:
      service: "my-plugin-svc.istio-system.svc.cluster.local"
      port: "50051"
```

With the Gateway

```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: my-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: istio-ingress-credential
      mode: MUTUAL
```

The AuthorizationPolicy

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ext-authz
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: CUSTOM
  provider:
    name: ext-authz-plugin
  rules:
  - {}
```

and finally the VirtualService

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpbin
  namespace: default
spec:
  gateways:
  - istio-system/my-gateway
  hosts:
  - '*'
  http:
  - match:
    - headers:
        X-TEST-HEADER:
          regex: (?:.*?\bSUCCESS\b).*
      uri:
        prefix: /headers
    route:
    - destination:
        host: httpbin
        port:
          number: 8000
```

I’ve also tried applying that policy on a namespace basis, and workload basis for my deployment, but my logs never show an auth request being received. Instead what I see in the ingress gateway logs are

```shell
"GET /headers HTTP/2" 404 NR route_not_found - ... "
```

That makes sense if the plugin isn’t being called, and based on [this](https://discuss.istio.io/t/evaluation-order-between-virtualservice-and-authorizationpolicy-features/10763) it appears that routing happens before auth. So then I tried to remove the AuthorizationPolicy, and instead use an EnvoyFilter to inject the authz before the routing filter. This was built based on [istio docs](https://istio.io/latest/docs/reference/config/networking/envoy-filter/) and [envoy docs](https://www.envoyproxy.io/docs/envoy/v1.16.2/configuration/http/http_filters/ext_authz_filter).

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: authz-envoyfilter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: INSERT_FIRST
      value:
        name: envoy.filters.http.ext_authz
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
          grpc_service:
            envoy_grpc:
              cluster_name: ext-authz-plugin-filter
            timeout: 0.5s
          transport_api_version: V3
          include_peer_certificate: true
  - applyTo: CLUSTER
    patch:
      operation: ADD
      value: # cluster specification
        name: ext-authz-plugin-filter
        connect_timeout: 0.25s
        typed_extension_protocol_options:
          envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
            "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
            explicit_http_config:
              http2_protocol_options: {}
        type: LOGICAL_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: ext-authz-plugin-filter
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    protocol: TCP
                    address: my-plugin-svc.istio-system.svc.cluster.local
                    port_value: 50051
```

But still, authz fires after routing with the gateway showing the same logs as above (also note that I’ve tried adding match contexts with no luck). The only way I’ve gotten this working is either converting the above EnvoyFilter to a NETWORK_FILTER, or replacing my `typed_config` with some Lua that makes an http request to my plugin instead. I’ve also had luck with WASM plugins, but that’s not a desirable choice based on some custom auditing and monitoring.

I’d rather not use the NETWORK_FILTER, because there isn’t as much metadata (ex. x-forwarded-client-cert) and I’ll have to do a lot of refactoring. I’d rather not use the Lua filter, because I’ve run into issues with things like the content-length header being overriden and it’s just more difficult/inconvenient to manage/debug.
