### ISSUE TITLE
How to reduce the mesh configuration size of e/w-gateway?

### ISSUE THREAD

**Issue by benyahman** [istio/istio#40981]
Describe the question
I have now deployed two primary control plane on different networks cluster which follows the official doc ([multi-primary_multi-network/](https://istio.io/latest/docs/setup/install/multicluster/multi-primary_multi-network/).)
But I found the mesh configuration of the e/w-gateway belongs to the cluster-wide level. ([expose-services](https://raw.githubusercontent.com/istio/istio/release-1.15/samples/multicluster/expose-services.yaml) )
How to reduce the configuration size and limited scope referenced in e/w-gateway. Just like to be putting on istio-ingressgateway by enabling the pilot parameter, as follows : ([commands-pilot-agent/](https://istio.io/latest/docs/reference/commands/pilot-agent/))

>  PILOT_FILTER_GATEWAY_CLUSTER_CONFIG=true

Version
> 1.13.5

Describe alternatives you've considered
N/A

Affected product area (please put an X in all that apply)

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

Affected features (please put an X in all that apply)

[X ] Multi Cluster
[ ] Virtual Machine
[ X] Multi Control Plane

Additional context

thanks.

**Comment by howardjohn** [comment]
What do you want to reduce? The gateway needs to know about all destinations otherwise it cannot reach them all. If you know only a subset will be used `hosts` can be more restrictive than `*.local`

**Comment by benyahman** [comment]
> I hope the e/w gateway can be able to create by namespace and not only the root namespace ```istio-system```.

For this purpose, so don't want all that is cluster-wide mesh configuration and should be namespace-wide if created by namespace. 
I was trying to modify the ```hosts``` value like you mentioned and expose the service to a specific one and not the original setting ```(*.local. )```.  But, the results seem to be the same.

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cross-network-gateway
spec:
  selector:
    istio: eastwestgateway
  servers:
    - port:
        number: 15443
        name: tls
        protocol: TLS
      tls:
        mode: AUTO_PASSTHROUGH
      hosts:
        - "<svc>.<ns>.cluster.local"
```
