### ISSUE TITLE
Istio installation using IOP failed when hpaSpec for cpu utilization configured  for components

### ISSUE THREAD

**Issue by muraliinformal** [istio/istio#41011]
Installing istio with IOP(default profile) failed when hpaSpec for cpu utilization configured.

Error message - 
```
- Processing resources for Istio core.
   ✔ Istio core installed
   - Processing resources for Istiod.2022-08-30T23:43:32.119129Z        error   installer       failed to update resource with server-side apply for obj HorizontalPodAutoscaler/istio-system/istiod: failed to create typed patch object (istio-system/istiod; autoscaling/v2beta1, Kind=HorizontalPodAutoscaler): .spec.metrics[0].resource.target: field not declared in schema
   
   ✘ Istiod encountered an error: failed to update resource with server-side apply for obj HorizontalPodAutoscaler/istio-system/istiod: failed to create typed patch object (istio-system/istiod; autoscaling/v2beta1, Kind=HorizontalPodAutoscaler): .spec.metrics[0].resource.target: field not declared in schema
```

**Istio version** - 1.14.3
**Kubernetes version** - 1.24.3

**Attachments**: Istio IOP file generated using `istioctl profile dump`
[istio_1.14.3_default_profile.txt](https://github.com/istio/istio/files/9577498/istio_1.14.3_default_profile.txt)

**Comment by howardjohn** [comment]
Minimal reproducer:

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
    - enabled: true
      k8s:
        hpaSpec:
          metrics:
          - resource:
              name: cpu
              targetAverageUtilization: 80
            type: Resource
      name: istio-ingressgateway
  values:
    pilot:
      cpu:
        targetAverageUtilization: 80


```

**Comment by zirain** [comment]
this should be some bug in manifest generate and server side apply, you can template workaround by running:
```
istioctl manifest generate -f istio/iop/hpa-not-working.yaml | k apply -f -
```

**Comment by zirain** [comment]
you can workaround by using:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    pilot:
      k8s:
        hpaSpec:
          metrics:
          - resource:
              name: cpu
              targetAverageUtilization: 80
            type: Resource
    ingressGateways:
    - enabled: true
      k8s:
        hpaSpec:
          metrics:
          - resource:
              name: cpu
              targetAverageUtilization: 80
            type: Resource
      name: istio-ingressgateway
  # values:
  #   pilot:
  #     cpu:
  #       targetAverageUtilization: 80
```
