### ISSUE TITLE
Incorrect ordering of mysql_proxy filter relative to rbac filter in generated filterchain prevents authpolicy from functioning

### ISSUE THREAD

**Issue by eitansuez** [istio/istio#41013]
### Bug Description

Deploying mysql to to an istio-enabled namespace with [PILOT_ENABLE_MYSQL_FILTER](https://istio.io/latest/docs/reference/commands/pilot-discovery/#envvars) enabled, and following the convention for [protocol selection](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#explicit-protocol-selection).

The basic scenario functions as advertised: I see the mysql filter installed on the envoy proxy.  So far so good.

When I define an authorization policy using a when condition matching the name [experimental.envoy.filters.network.mysql_proxy](https://istio.io/latest/docs/reference/config/security/conditions/), Istio will configure the filter chain such that the rbac filter comes before the mysql_proxy filter.

Consequently the rbac filter does not function because it runs too early.  The mysql_proxy filter must be configured in the filterchain ordering so that it comes before the rbac fitler so it has a chance to build the metadata that the rbac filter relies upon to match the when condition.

The following [failing test](https://github.com/istio/istio/commit/83a74bb3f5a82619db3ede201e9dfd14396df623) shows that the ordering of the rbac filter relative to the msyql_proxy is backwards.

Example:

The following authorization policy will not match the specified condition because the mysql_proxy metadata has not been collected by the mysql_proxy filter at the time that the rbac filter condition is evaluated by envoy (because the mysql_proxy is specified after the rbac filter in the filter chain):

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: mysql-policy
  namespace: default
spec:
  selector:
    matchLabels:
        app.kubernetes.io/name: mysql
  action: DENY
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/sqltest/sa/default"]
    when:
    - key: experimental.envoy.filters.network.mysql_proxy[abc.peterdb]
      values: ["select"]
```

### Version

```prose
client version: 1.15.0
control plane version: 1.15.0
data plane version: 1.15.0 (1 proxies)

Client Version: v1.23.8
Server Version: v1.24.4+k3s1
```
