### ISSUE TITLE
ztunnel generates bad envoy config if there are multiple hostNetwork: true pods

### ISSUE THREAD

**Issue by dhawton** [istio/istio#41097]
### Bug Description

The Envoy config being generated if there are multiple `hostNetwork: true` pods on a node will contain filter chains that have the same matching rules

```
2022-09-21T17:49:52.688853Z	warning	envoy config	gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) ztunnel_inbound: error adding listener '0.0.0.0:15008': filter chain 'inbound_192.168.1.3' has the same matching rules defined as 'inbound_192.168.1.3'
```

Replication steps:
1. Deploy any clusters (ie, kind)
2. Deploy a number of containers that are in the hostNetwork, for example:
```
for i in $(seq 8001 8005); do
  cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-$i
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-$i
      version: v$i
  template:
    metadata:
      labels:
        app: http-$i
        version: v$i
    spec:
      hostNetwork: true
      containers:
      - image: ealen/echo-server
        imagePullPolicy: Always
        name: http
        env:
        - name: PORT
          value: "$i"
        ports:
        - containerPort: $i
EOF
done
```
3. Install Ambient via `istioctl install --set profile=ambient -y`
4. ztunnel on nodes with multiple hostNetwork pods will fail to become ready with the above error message

### Version

```prose
❯ i version
client version: 0.0.0-ambient.191fe680b52c1754ee72a06b3e0d3f9d116f2e82
control plane version: 0.0.0
data plane version: 0.0.0-ambient.191fe680b52c1754ee72a06b3e0d3f9d116f2e82 (3 proxies)
```

### Additional Information

Config dump from one of the ztunnels: https://i.hwtn.me/ambient/ztunnel.dump
Logs from the same ztunnel: https://i.hwtn.me/ambient/ztunnel.log
