### ISSUE TITLE
GRPC + TLS: all requests rejected with code = Unavailable desc = upstream connect error or disconnect/reset before headers. reset reason: remote reset

### ISSUE THREAD

**Issue by CooperWolfe** [istio/istio#41102]
### Bug Description

Using the Istio Gateway and Virtual service, I have both HTTP and GRPC endpoints being hit through the same gateway. This has been working without TLS and still works with HTTPS, but GRPC + TLS does not seem to want to comply.  My Istio files are below. I also included my golang GRPC client code.

## Gateway
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: {{ .Values.gateway.httpPort }}
      name: http
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: {{ .Values.gateway.httpsPort }}
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: ingress-cert
    hosts:
    - "*"
```
## Virtual Services
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "app.name" . }}
spec:
  hosts:
  - "*"
  gateways:
  - gateway
  http:
  - match:
    - uri:
        prefix: /svc/media
    rewrite:
      uri: /media
    route:
    - destination:
        host: svc-http
        port:
          number: {{ .Values.svc.http.port }}
  - match:
    - uri:
        prefix: /svc
    route:
    - destination:
        host: svc-grpc
        port:
          number: {{ .Values.svc.grpc.port }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: diff
spec:
  hosts:
  - {{ .Values.gateway.diffDomain | quote }}
  gateways:
  - gateway
  http:
  - match:
    - uri:
        prefix: {{ printf "%s/" .Values.diff.basePath | quote }}
    - uri:
        prefix: {{ .Values.diff.basePath | quote }}
    rewrite:
      uri: "/"
    route:
    - destination:
        host: diff
        port:
          number: {{ .Values.diff.port }}
  - route:
    - destination:
        host: diff
        port:
          number: {{ .Values.diff.publicPort }}
```
## GRPC Service
```
apiVersion: v1
kind: Service
metadata:
  name: svc-grpc
spec:
  ports:
  - name: grpc
    port: {{ .Values.svc.grpc.port }}
    protocol: TCP
    targetPort: {{ .Values.svc.grpc.port }}
  selector:
    app: {{ include "app.name" . }}
    service: svc
```
## HTTP Service
```
apiVersion: v1
kind: Service
metadata:
  name: svc-http
spec:
  ports:
  - name: http
    port: {{ .Values.svc.http.port }}
    protocol: TCP
    targetPort: {{ .Values.svc.http.port }}
  selector:
    app: {{ include "app.name" . }}
    service: svc
```
## Golang client
```
package main

import (
	"context"
	"fmt"
	pb "temp/pb"

	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"
)

func main() {
	creds, err := credentials.NewClientTLSFromFile("lets-encrypt.pem", "") // The Root CA cert of my LetsEncrypt-signed server cert
	if err != nil {
		panic(err)
	}
	conn, err := grpc.Dial("mydomain.com:443", grpc.WithTransportCredentials(creds))
	if err != nil {
		panic(err)
	}

	ctx := context.Background()

	fmt.Println("Executing")
	client := pb.NewSvcClient(conn)
	reply, err := client.Execute()
	if err != nil {
		panic(err)
	}

	fmt.Println(reply.message)
}
```

### Version

```prose
$ istioctl version
client version: 1.12.1
control plane version: 1.12.1
data plane version: 1.12.1 (25 proxies)
$ kubectl version --short
Client Version: v1.23.1
Server Version: v1.22.11-gke.400
$ helm version --short
v3.8.0-rc.1+g0c8320b
```

### Additional Information

Target cluster context: **REDACTED**

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-system,kube-public,kube-node-lease,local-path-storage }
end-time: 2022-09-21 18:45:24.548379 -0400 EDT

Cluster endpoint: https://35.239.37.93
CLI version:
version.BuildInfo{Version:"1.12.1", GitRevision:"88902a51acfb0383809608ccff169319560f768c", GolangVersion:"go1.17.3", BuildStatus:"Clean", GitTag:"1.12.1"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.12.1", GitRevision:"88902a51acfb0383809608ccff169319560f768c", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.12.1"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.12.1}

Fetching proxy logs for the following containers:

**REDACTED**

Fetching Istio control plane information from cluster.

The following fetches are still running: 
  ProxyGet **REDACTED**
  ProxyGet **REDACTED**
  ProxyGet **REDACTED**
  ProxyGet **REDACTED**
  ProxyGet **REDACTED**

Running istio analyze on all namespaces and report as below:
Analysis Report:
**REDACTED**
Done.
