### ISSUE TITLE
proxy-init resources parameter passed to the IstioOperator is not use by the injector 

### ISSUE THREAD

**Issue by x3rus** [istio/istio#41167]
### Bug Description

Hi folks, 

I try to reduce the memory footprint of the istio-proxy sidecar, I'm using a small cluster and based on the perf documentation I should be able to reduce the memory limit. My end goal is to be able to set a namespace quota without having to add 2Gig memory per pod. 

With the Istio Operator, I'm able to redefine the proxy resources and the proxy-init. It's working properly for `proxy` but `proxy-init` is not managed by the injector. 

```
  cat <<EOF | istioctl install --set profile=minimal -y -f -
    apiVersion: install.istio.io/v1alpha1
    kind: IstioOperator
    spec:
      values:
        global:
          proxy:
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 256Mi
                cpu: 500m
          proxy_init:
            resources:
              limits:
                cpu: 1000m
                memory: 2000Mi
              requests:
                cpu: 10m
                memory: 10Mi
        pilot:
          env:
            ENABLE_LEGACY_FSGROUP_INJECTION: false
        sidecarInjectorWebhook:
          rewriteAppHTTPProbe: false
          neverInjectSelector:
            - matchExpressions:
              - key: kpack.io/build
                operator: Exists
            - matchExpressions:
              - key: job-name
                operator: Exists
EOF
```

when I checked in the configmap `istio-sidecar-injector` there are no references to proxy-init.

I did a PR with a suggested fix, I hope it will help.

### Version

```prose
$ istioctl version
client version: 1.15.0
control plane version: 1.14.3
data plane version: 1.14.3 (308 proxies)

$ kubectl version --short
Client Version: v1.24.4
Kustomize Version: v4.5.4
Server Version: v1.21.14-gke.700
```

### Additional Information

[bug-report.tar.gz](https://github.com/istio/istio/files/9647133/bug-report.tar.gz)
