### ISSUE TITLE
Istio and access log filtering

### ISSUE THREAD

**Issue by marcin-kasinski** [istio/istio#41170]
### Bug Description

I've installed istio:

```
helm install istio-base istio/base --version 1.15.0 --namespace istio-system 
helm install istiod istio/istiod --version 1.15.0 --namespace istio-system
helm install istio-ingressgateway istio/gateway --version 1.15.0 --namespace istio-system

```

Then I wanted to turn access logs on with filtering:

```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: xyz-dev
spec:
  accessLogging:
    - providers:
      - name: envoy
    - filter:
        expression: "response.code >= 400"
```

Problem is that expression above doesnt work.

In logs I can see all requests not only with response code higher than 400

Did I miss something?

### Version

```prose
kubectl version --short
Client Version: v1.18.3
Server Version: v1.22.11-eks-18ef993
helm version --short
v3.8.2+g6e3701e
```

### Additional Information

istioctl version

**Comment by zirain** [comment]
if you want a mesh wide config, you should create telemetry on root namespace(`istio-system` in most case).

**Comment by marcin-kasinski** [comment]
```
istioctl bug-report

Target cluster context: arn:aws:eks:eu-west-1:xxxxxxxxxxxx:cluster/a-sto-dev-eks-main

Running with the following config:

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2022-09-26 16:04:51.927432089 +0000 UTC



Cluster endpoint: https://xxxxxxxxxxxxxxxxxxxxxxxx.gr7.eu-west-1.eks.amazonaws.com

```


and hangs


Then after a while:

```

CLI version:
version.BuildInfo{Version:"1.15.0", GitRevision:"e3364ab424b70ca8ee1ca76cb0b3afb73476aaac", GolangVersion:"go1.19", BuildStatus:"Clean", GitTag:"1.15.0"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.15.0", GitRevision:"e3364ab424b70ca8ee1ca76cb0b3afb73476aaac", GolangVersion:"go1.19", BuildStatus:"Clean", GitTag:"1.15.0"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.15.0}


Fetching proxy logs for the following containers:

...


Fetching Istio control plane information from cluster.

The following fetches are still running:
  kubectl version
  PodExec ...
  kubectl get --all-namespaces all,namespaces,jobs,ingresses,endpoints,customresourcedefinitions,configmaps,events,mutatingwebhookconfigurations,validatingwebhookconfigurations -o yaml
  ProxyGet ...
  kubectl get secrets --all-namespaces
  PodExec istio-system/istio-ingressgateway-8584fcc547-bh4tx/istio-proxy:netstat -natpw
  PodExec ...
  kubectl get customresourcedefinitions --no-headers
  kubectl describe nodes
  PodExec istio-system/istiod-d97cbc5f-79pxx/discovery:pilot-discovery request GET debug/adsz
  PodLogs istio-system/istio-ingressgateway-8584fcc547-bh4tx/istio-proxy
  ProxyGet istio-system/istio-ingressgateway-8584fcc547-bh4tx:certs
  ProxyGet ...
  PodExec istio-system/istio-ingressgateway-8584fcc547-bh4tx/istio-proxy:find /var/lib/istio -name core.*
  kubectl get events --all-namespaces -o wide
  kubectl describe pods -n istio-system


Running istio analyze on all namespaces and report as below:
Analysis Report:
Warning [IST0127] (AuthorizationPolicy ...) No matching workloads for this resource with the following labels: kubernetes.io/app=...
...

Creating an archive at /root/bug-report.tar.gz.
Cleaning up temporary files in /tmp/bug-report.
Done.
```

**Comment by howardjohn** [comment]
```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  accessLogging:
    - providers:
      - name: envoy
      filter:
        expression: "response.code >= 400"
```

Shouldn't it be like this? you are creating 2 different log configs, not one with a filter
