### ISSUE TITLE
Mirror traffic by prefix

### ISSUE THREAD

**Issue by dnguyenzd** [istio/istio#41214]
I have 2 deployments `v1` and `v2`: v2 is newer api and only supports a subset of endpoints from `v1`. Let's say `v1` has 2 routes:
- `/route/1`
- `/route/2`
and only `/route/1` is supported by `v2` at the moment. I want all traffic go to `v1` and for those requests that match `/route/1`, also mirror them to `v2`

What I have so far:

`DestinationRule`:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: my-destination-rule
spec:
  host: my-service.svc.cluster.local
  subsets:
  - labels:
      version: v1
    name: v1
  - labels:
      version: v2
    name: v2
```

`VirtualService`:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: my-service
spec:
  gateways:
  - my-service-gateway
  hosts:
  - my-service.test
  http:
  - match:
    - uri:
        prefix: /route/1
    mirror:
      host: my-service.svc.cluster.local
      port:
        number: 80
      subset: v2
    route:
    - destination:
        host: my-service.svc.cluster.local
        port:
          number: 80
        subset: v1
      weight: 100
  - route:
    - destination:
        host: my-service.svc.cluster.local
        port:
          number: 80
        subset: v1
      weight: 100
```

I find that this doesn't work as I expect: requests seem to randomly go to either `v1` or `v2` for `/route/1`. If a request goes to `v1`, it doesn't appear in `v2` log and vice versa. This looks more like traffic splitting to me

Is there any way to do mirroring for a subset of traffic?
