### ISSUE TITLE
HTTP port on 15021 leads to NACK

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#41239]
```
apiVersion: v1
kind: Service
metadata:
  name: shell
spec:
  ports:
  - port: 15021
    name: http
  selector:
    app: shell
```

Causes all pods to NACK. Issue is we try to create a dynamic 0.0.0.0:15021 listener, but we already have a static one
