### ISSUE TITLE
RequestAuthenticaion rules can only be obtained by sending an ADS request if the namespace is istio-system

### ISSUE THREAD

**Issue by 123liuziming** [istio/istio#41247]
I use grpc-java to send a Ads(Lds) request, but can not get any envoy.filters.http.jwt_authn filters when I set the RequestAuthentication's namespace 'foo'. 
```
kubectl apply -f - <<EOF
apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: "jwt-example"
  namespace: foo
spec:
  jwtRules:
  - issuer: "testing@secure.istio.io"
    jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.5/security/tools/jwt/samples/jwks.json"
EOF
```
I can only get the envoy.filters.http.jwt_authn filters when the RequestAuthentication's namespace is istio-system
```
kubectl apply -f - <<EOF
apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: "jwt-example"
  namespace: foo
spec:
  jwtRules:
  - issuer: "testing@secure.istio.io"
    jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.5/security/tools/jwt/samples/jwks.json"
EOF
```

When I apply AuthorizationPolicy,  there is no problem. When I set the AuthorizationPolicy's namespace 'foo', I can get the rules by sending Lds request.
