### ISSUE TITLE
Default Sidecar Object Not Being Applied

### ISSUE THREAD

**Issue by pseymournutanix** [istio/istio#41243]
### Bug Description

Applying a default `sidecar` object into the root configuration namespace doesn't block traffic.

Applying a default `sidecar` object:-
```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: default
  namespace: istio-system
spec:
  egress:
  - hosts:
    - "./*"
    - "istio-system/*"
    - "kube-system/*"
```

This restricts the list of `outbound` connections in the `istioctl pc endpoints` for the pod and the other services in the cluster in other namespaces are removed from that list. 

However I am still able to connect to those services from the pods in another namespace via `curl` etc.

### Version

```prose
client version: 1.15.1
control plane version: 1.15.1
data plane version: 1.15.1 (11 proxies)
```

### Additional Information

The envoy logs show no issues
```
[2022-10-02T11:16:11.288Z] "GET / HTTP/1.1" 200 - via_upstream - "-" 0 153 1 0 "-" "curl/7.83.1" "f75132e4-f17e-4aa2-b29a-766755984ef8" "docker-proxy.docker-proxy.svc.cluster.local" "172.20.4.11:80" inbound|80|| 127.0.0.6:58246 172.20.4.11:80 172.20.6.33:38764 - default
```
