### ISSUE TITLE
port level consistent hash setting not working when vs destination does not have port

### ISSUE THREAD

**Issue by yingzhuivy** [istio/istio#41257]
### Bug Description

The `httpHeaderName: X-HEADER` setting won't be applied to the http route with the following settings:

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: svc-a
  namespace: ns-a
spec:
  host: svc-a.ns-a.svc.cluster.local
  trafficPolicy:
    portLevelSettings:
      - loadBalancer:
          consistentHash:
            httpHeaderName: X-HEADER
            minimumRingSize: 2000
        port:
          number: 8080
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: svc-a
  namespace: ns-a
spec:
  hosts:
  - svc-a.ns-a.svc.cluster.local
  http:
  - match:
      - port: 8080
    retries:
      attempts: 1
      retryOn: gateway-error,connect-failure
    route:
    - destination:
        host: svc-a.ns-a.svc.cluster.local
      weight: 100
    timeout: 10s
```

probably some bugs in this function:
https://github.com/istio/istio/blob/1.14.4/pilot/pkg/networking/core/v1alpha3/route/route.go#L1150
which returns nil if destination has no port specified.

### Version

```prose
1.13 & 1.14
```
