### ISSUE TITLE
istioctl upgrade using `apiVersion: autoscaling/v2beta1`

### ISSUE THREAD

**Issue by jzck** [istio/istio#41262]
### Bug Description

Hello, since we upgraded to kubernetes `1.25` our hpa are in the `autoscaling/v2` apiVersion. Since then the istio upgrade gives the following error:

```
$ istioctl upgrade --skip-confirmation -f /var/folders/fd/0gxnr5l11gsgqj33n6cbpnyh0000gp/T/tmp.1WHmN9FV --readiness-timeout=30m --verify
✔ Istio core installed
- Processing resources for Istiod.                                                                                                                            2022-10-04T08:31:51.050122Z	error	installer	failed to update resource with server-side apply for obj HorizontalPodAutoscaler/istio-system/istiod: no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"
✘ Istiod encountered an error: failed to update resource with server-side apply for obj HorizontalPodAutoscaler/istio-system/istiod: no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"
- Processing resources for Ingress gateways.                                                                                                                  2022-10-04T08:31:53.532954Z	error	installer	failed to update resource with server-side apply for obj HorizontalPodAutoscaler/istio-system/istio-ingressgateway: no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"
✘ Ingress gateways encountered an error: failed to update resource with server-side apply for obj HorizontalPodAutoscaler/istio-system/istio-ingressgateway: no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"
- Pruning removed resources
```

We have tried editing our istio operator to use
```
hpaSpec:
  scaleTargetRef:
    apiVersion: autoscaling/v2
```

but that doesn't change anything, istioctl still uses `v2beta1`

### Version

```prose
$ istioctl version
client version: 1.15.0
control plane version: 1.15.0
data plane version: 1.15.1 (8 proxies), 1.15.0 (3 proxies)

$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.2
Kustomize Version: v4.5.7
Server Version: v1.25.0-gke.1100
```

**Comment by theonlydoo** [comment]
Since [1.25](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v125)
> The autoscaling/v2beta1 API version of HorizontalPodAutoscaler will no longer be served in v1.25.
> 
> Migrate manifests and API clients to use the autoscaling/v2 API version, available since v1.23.
All existing persisted objects are accessible via the new API 
there has been some removal

**Comment by howardjohn** [comment]
this is supposed to be fixed, can you try the latest 1.15 patch? Might need an unreleased version unfortunately, not sure when we fixed it precisely

**Comment by theonlydoo** [comment]
Hey It has been tried with 1.15 & 1.15.1 tagged releases. Do you want to test another one?

**Comment by howardjohn** [comment]
cc @zirain @richardwxn

**Comment by zirain** [comment]
will take a look after national holidays

**Comment by zirain** [comment]
https://github.com/istio/istio/pull/41079 is not included in `1.15.1`, it should be `1.15.2`

![image](https://user-images.githubusercontent.com/4354057/194678696-36704873-de82-4a38-9412-4b3e10a4397b.png)

**Comment by theonlydoo** [comment]
it went through and is working thanks

**Comment by zirain** [comment]
can we close this ticket?

**Comment by theonlydoo** [comment]
looks good to me!

**Comment by theonlydoo** [comment]
maybe we should re-open, sorry for the mishap:
```
- Processing resources for Istio core.
✔ Istio core installed
- Processing resources for Istiod.2022-10-19T08:02:17.280428Z	error	installer	failed to update resource with server-side apply for obj HorizontalPodAutoscaler/istio-system/istiod: no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"

✘ Istiod encountered an error: failed to update resource with server-side apply for obj HorizontalPodAutoscaler/istio-system/istiod: no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"
- Processing resources for Ingress gateways.2022-10-19T08:02:19.759935Z	error	installer	failed to update resource with server-side apply for obj HorizontalPodAutoscaler/istio-system/istio-ingressgateway: no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"

✘ Ingress gateways encountered an error: failed to update resource with server-side apply for obj HorizontalPodAutoscaler/istio-system/istio-ingressgateway: no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"
- Pruning removed resourcesError: failed to install manifests: errors occurred during operation
Error: Process completed with exit code 1.
```

I was under the impression that the release went through but I was wrong!

**Comment by zirain** [comment]
can you share your iop configuration? and output of `istioctl version`

**Comment by theonlydoo** [comment]
[Here you go](https://gist.github.com/theonlydoo/8207ac5b486afe7d5698ee82e032fd63). Here is the output of `istioctl version`

```
client version: 1.15.2
control plane version: 1.15.2
data plane version: 1.15.0 (2 proxies), 1.15.2 (60 proxies)
```

**Comment by zirain** [comment]
I cannot reproduce with your iop and istioctl v1.15.2

**Comment by xvzf** [comment]
@zirain it could be linked to the k8s version; so far it only happens on a 1.25 upgrade

**Comment by xvzf** [comment]
@zirain so, it's linked to the `Values.global.autoscalingv2API` option, which when not set always uses the `autoscaling/v2beta1` which is not available on Kubernetes 1.25

**Comment by zirain** [comment]
I try with your iop, but got `autoscaling/v2`

**Comment by xvzf** [comment]
Hi @zirain @howardjohn, is there any plan to fix this upstream (we're happy to help!)

The proposed solution works but leaves a blurry situation, IMHO the autoscaling/v2 API should be used in Kubernetes >1.24 automatically as the default option is deprecated and results in errors. Wdyt?

**Comment by zirain** [comment]
https://github.com/istio/api/pull/2515 should be merged

**Comment by richardwxn** [comment]
It is actually by design now, since you defined a hpaspec with k8s v2beta1 API so istioctl detect that and apply the v2beta1 templates correspondingly.  We do not have an auto translation logic implemented in istioctl to convert the v2beta1 fields to v2/v2beta2 fields since not all of them have 1:1 match. 

Two possible improvements:
1. issue a warning in istioctl if users still apply IOP with v2beta1 hpaspec on kubernetes 1.25+ clusters, so they can update their IOP, but this may break some CI/CD pipelines OR
2.use v2 always for 1.25+ clusters, but risk losing some intended overlay they previously applied with v2beta1

**Comment by richardwxn** [comment]
@zirain WDYT? Can you own this if we agree on one of the approaches mentioned above

**Comment by zirain** [comment]
ok, I will take a look

**Comment by lam-man** [comment]
Some information regarding this issue. We see this issue in Kubernetes 1.24 while upgrading Istio from 1.4.6 to 1.15.3. We also tried the suggestion provided by @zirain to use the following format. However, the problem still persists. 
```
          - resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 80
```

**Comment by lam-man** [comment]
> Hi @zirain @howardjohn, is there any plan to fix this upstream (we're happy to help!)
> 
> The proposed solution works but leaves a blurry situation, IMHO the autoscaling/v2 API should be used in Kubernetes >1.24 automatically as the default option is deprecated and results in errors. Wdyt?

Hi Matthias @xvzf , I am wondering how you change your iop according to the suggestion provided by @zirain . Would you mind sharing more? I think the suggestion missed one line: `type: Resource` in the `metrics` block. However, I found istio upgrade (1.14.6 -> 1.15.3) failed in k8s 1.24.6 even with the `- type: Resource`.
```
k8s:
  hpaSpec:
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
```

**Comment by anattapol** [comment]
This issue is reproducible in istio version 1.16.2

**Comment by dgershman** [comment]
Yes also happens on Istio 1.16.1 on K8S v1.25

**Comment by lam-man** [comment]
> Yes also happens on Istio 1.16.1 on K8S v1.25

Would you mind sharing how you install Istio Operator? With changes in the customized Helm chart, we were able to resolve the issue. I am not sure the method is applicable to your situation. Would like to learn more before sharing. Thanks

**Comment by anattapol** [comment]
I tested on my AKS cluster 1.25.4 , istio 1.16.2.

`istioctl upgrade -y -f istio-profile.yaml`

I have to specify this config in my istiooperator. 
```yaml
  values:
    global:
      autoscalingv2API: true
```
otherwise, this error message complain.
```log
2023-02-17T13:21:58.350914Z     error   installer       failed to update resource with server-side apply for obj HorizontalPodAutoscaler/my-istio-system/istiod: no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"
✘ Istiod encountered an error: failed to update resource with server-side apply for obj HorizontalPodAutoscaler/my-istio-system/istiod: no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"
```
below is my istio-profile.yaml
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: my-istio-system
  name: my-istio-iop-default
spec:
  hub: myprivate.azurecr.io/istio
  profile: default
  namespace: my-istio-system
  meshConfig:
    rootNamespace: my-istio-system
    defaultConfig:
      holdApplicationUntilProxyStarts: true
    accessLogFile: /dev/stdout
    accessLogFormat: |
      [ %START_TIME% ] %REQ(:METHOD)% %PROTOCOL% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%
      %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION%
      %REQ(X-FORWARDED-FOR)% %REQ(X-REQUEST-ID)% %REQ(:AUTHORITY)%
      %UPSTREAM_HOST% %UPSTREAM_TRANSPORT_FAILURE_REASON% %DOWNSTREAM_TLS_VERSION%
      %DOWNSTREAM_PEER_URI_SAN% ==> %DOWNSTREAM_LOCAL_URI_SAN%
  components:
    cni:
      enabled: true
      k8s:
        nodeSelector:
          kubernetes.io/os: linux
    pilot:
      enabled: true
      k8s:
        priorityClassName: "system-cluster-critical"
        hpaSpec:
          minReplicas: 2
          maxReplicas: 8
          metrics:
            - type: Resource
              resource:
                name: cpu
                target:
                  type: Utilization
                  averageUtilization: 80
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 1Gi
        nodeSelector:
          kubernetes.io/os: linux
    egressGateways: []
    ingressGateways:
      - name: istio-ingressgateway
        k8s:
          priorityClassName: "system-cluster-critical"
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 200m
              memory: 512Mi
          serviceAnnotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
            service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "SUBNET_PLACEHOLDER"
          hpaSpec:
            minReplicas: 2
            maxReplicas: 8
            metrics:
              - type: Resource
                resource:
                  name: cpu
                  target:
                    type: Utilization
                    averageUtilization: 80
          nodeSelector:
            kubernetes.io/os: linux
  values:
    global:
      autoscalingv2API: true
      istioNamespace: adp-istio-system
      proxy:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
  ```
