### ISSUE TITLE
Horizontal Pod Auto Scaler Behavior 

### ISSUE THREAD

**Issue by trick392** [istio/istio#41309]
### Bug Description

**Overview of issue**

There is a buggy implementation of HPA behaviour in Istio. 

Setting quantities in the IstioOperator HpaSpec behaviour causes unmarshalling errors.
```Setting quantities in the IstioOperator CR causes unmarshalling errors.
k8s.io/client-go@v0.24.1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.IstioOperator: failed to list *v1alpha1.IstioOperator: json: cannot unmarshal array into Go struct field IstioOperator.items.spec of type map[string]json.RawMessage
```
There has been a previous thread on this issue: https://github.com/istio/istio/issues/24839 but given that behaviour is a new field this issue may not have been fixed. 

**Expected behavior**

To be able to install when setting quantities in the HPA spec

**Steps to reproduce the bug**

```apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  values:
    pilot:
      autoscaleEnabled: true
  profile: demo
  components:
    pilot:
      k8s:
        hpaSpec:
          scaleTargetRef:
            apiVersion: extensions/v1beta1
            kind: Deployment
            name: istiod
          minReplicas: 1
          maxReplicas: 5
          behavior:
            scaleDown:
              policies:
              - periodSeconds: 30
                type: Pods
                value: 1
              stabilizationWindowSeconds: 300
          metrics:
          - type: Resource
            resource:
              name: cpu
              targetAverageValue: 1000
```

### Version

```prose
control plane version: 1.15.1
Client Version: v1.21.3
Server Version: v1.22.13-eks-15b7512
```

**Comment by zirain** [comment]
@trick392 you should change your configuration as following:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  values:
    pilot:
      autoscaleEnabled: true
  profile: demo
  components:
    pilot:
      k8s:
        hpaSpec:
          scaleTargetRef:
            apiVersion: extensions/v1beta1
            kind: Deployment
            name: istiod
          minReplicas: 1
          maxReplicas: 5
          behavior:
            scaleDown:
              policies: # follow v2beta2 spec
                periodSeconds: 30
                type: Pods
                value: 1
              stabilizationWindowSeconds: 300
          metrics:
          - type: Resource
            resource:
              name: cpu
              target: # follow v2beta2 spec
                 averageUtilization: 1000
                 type: Utilization
```
