### ISSUE TITLE
TLS Min Protocol Version and Max Protocol Version doesn't have any effect

### ISSUE THREAD

**Issue by momiecloudoneguys** [istio/istio#41305]
### Bug Description

In istio 1.15.0, if i change the TLS Protocol Version into the gateway, the parameters doesn't change and only TLS 1.2 and 1.3 work. We don't have the problem with Istio 1.13.3. 
Gateway:
![image](https://user-images.githubusercontent.com/92149621/194509582-0321ed5e-a1f8-4d23-a570-ba7cff6177ea.png)
With Istio 1.15.0:
![image](https://user-images.githubusercontent.com/92149621/194509776-ab36e861-293d-41e0-8bc6-7522940d75ba.png)
With Istio 1.13:
![image](https://user-images.githubusercontent.com/92149621/194510054-b766c6d1-fe53-4b45-b415-846f333a6d73.png)

### Version

```prose
--- istioctl version
client version: 1.15.0
control plane version: 1.15.0
data plane version: 1.15.0
--- kubectl version --short
Client Version: v1.23.4
Server Version: v1.22.9
```

**Comment by hzxuzhonghu** [comment]
What is the gateway tls mode?

**Comment by momiecloudoneguys** [comment]
The gateway is in simple mode  

------------
 - hosts:
    - test.test
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: cert
      maxProtocolVersion: TLSV1_3
      minProtocolVersion: TLSV1_0
      mode: SIMPLE

**Comment by hzxuzhonghu** [comment]
Can you also dump the ingress gateway listener configuration to see if the version set correctly

**Comment by momiecloudoneguys** [comment]
The file is attached. I can see this in the config: 
"tls_params": {
            "tls_minimum_protocol_version": "TLSv1_0",
            "tls_maximum_protocol_version": "TLSv1_3"
 },
[listener.txt](https://github.com/istio/istio/files/9745162/listener.txt)

**Comment by hzxuzhonghu** [comment]
I can see there are many filterChains for "test.test", however the DownstreamTlsContext set is different, not sure how this is generated?
Do you have multi gateways defined for this service

**Comment by momiecloudoneguys** [comment]
test.test isn't the true link, each gateway have differents name and URL, but we have replace in the file for privacy

**Comment by momiecloudoneguys** [comment]
I've found some issue and pull request in the Envoy GitHub like this: https://github.com/envoyproxy/envoy/pull/23297
With the good cipher, TLS below 1.2 work.

**Comment by hzxuzhonghu** [comment]
Good catch, we can note it on istio api as well

**Comment by PeteMac88** [comment]
@momiecloudoneguys Hey, I think I have the same problem. I use 1.15.2 and cannot find a way to support TLSV1_1. I added following config to my gateway:
```
        mode: SIMPLE
        minProtocolVersion: TLSV1_1
        cipherSuites:
          - TLS_AES_128_GCM_SHA256
          - TLS_AES_256_GCM_SHA384
          - TLS_CHACHA20_POLY1305_SHA256
          - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256vv
          - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
          - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
          - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
          - TLS_RSA_WITH_AES_128_CBC_SHA
          - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
          - TLS_RSA_WITH_AES_256_CBC_SHA
```

Did you also configure the istio operator in any way to allow TLS 1.1? I see there is an option to set the TLS version in the mesh config (https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-TLSConfig). Can you provide me with your example? Thanks in advance
