### ISSUE TITLE
Sidecar outbound TCP listener doesn't bind to auto allocated address when port is specified in Sidecar.egress

### ISSUE THREAD

**Issue by l8huang** [istio/istio#41312]
### Bug Description

With below proxy metadata:
```
        proxyMetadata:
          ISTIO_META_DNS_AUTO_ALLOCATE: "true"
          ISTIO_META_DNS_CAPTURE: "true"
```

When a TCP service is configured in Sidecar.egress without `port` setting, the generated sidecar outbound listener will bind to `240.240.x.x`; but if a `port` setting presents, the outbound listener will bind to `0.0.0.0`. 

For example, with below ServiceEntry:
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: fortio
spec:
  hosts:
  - fortio.com
  location: MESH_INTERNAL
  ports:
  - number: 7070
    name: tcp
    protocol: TCP
    targetPort: 7070
  resolution: DNS 
```

If `Sidecar.egress` is configured as:
```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: test
spec:
  egress:
  - hosts:
    - ./fortio.com
    - ~/*
```

Sidecar's outbound listener binds to auto allocated address as expected:
```
$ istioctl  pc l [proxy-id]  
ADDRESS       PORT  MATCH          DESTINATION
240.240.1.175 7070  ALL                Cluster: outbound|7070||fortio.com
```

But, if Sidecar.egress` is configured as:
```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: test
spec:
  egress:
  - hosts:
    - ./fortio.com
    port:
      number: 7070
      protocol: TCP
```
Sidecar's outbound listener binds to `0.0.0.0`:
```
$ istioctl  pc l [proxy-id]  
ADDRESS       PORT  MATCH          DESTINATION
0.0.0.0           7070  ALL                   Cluster: outbound|7070||fortio.com
```

It should bind to `240.240.1.175`.

This issue can be reproduced by UT https://github.com/istio/istio/pull/41311/commits/a17d6454681efe97e171285b666d7ee48bc35790

A fix is PR https://github.com/istio/istio/pull/41311 .

### Version

```prose
$ istioctl  n version
client version: 1.13.0
control plane version: 1.10.3
data plane version: 1.10.3 (3 proxies)

$ kubectl version --short
Client Version: v1.22.2
Server Version: v1.18.8-393
```
