### ISSUE TITLE
Is there a way to set default http IdleTimeout for sidecar inbound cluster

### ISSUE THREAD

**Issue by fatedier** [istio/istio#41328]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
In our env, some service got a few 503 requests.

I found the reason is that user's app set http server idle timeout to 150s, and envoy has no specified idle timeout for inbound cluster, default value is 1h from envoy [docs](https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/timeouts#connection-timeouts).

If the interval of two requests to this pod is 150s, user's http server will close this idle connection. And there is a very small chance that envoy is sending the second request to user's server and got connection termination error.

I want to set a global default http idle timeout(maybe 60s)  for sidecar inbound cluster to avoid this mistakes.

**Describe alternatives you've considered**
Create DestinationRule for each service and set idle timeout.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zirain** [comment]
cc @ramaraochavali @hzxuzhonghu

**Comment by alt-dima** [comment]
I'm also trying to solve 503 errors with nodejs (express) applications where default keepAlive timeout is 5 seconds
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: fix-for-nodejs
  namespace: "${kubernetes_namespace_v1.istio_namespace.metadata[0].name}"
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      cluster:
      context: SIDECAR_OUTBOUND
    patch:
      operation: MERGE
      value:
        typed_extension_protocol_options:
          envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
            '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
            common_http_protocol_options:
              idle_timeout: 4s
            use_downstream_protocol_config: 
              http2_protocol_options: {}
              http_protocol_options: {}
  - applyTo: CLUSTER
    match:
      cluster:
      context: SIDECAR_INBOUND
    patch:
      operation: MERGE
      value:
        typed_extension_protocol_options:
          envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
            '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
            common_http_protocol_options:
              idle_timeout: 4s
            use_downstream_protocol_config: 
              http2_protocol_options: {}
              http_protocol_options: {}
```

**Comment by fatedier** [comment]
@alt-dima Can you verify the envoyfilter config whether it will override the idletimeout in a DestinationRule?

**Comment by alt-dima** [comment]
@fatedier I will try to check now.
But! DestinationRule manages HttpProtocolOptions in the HTTP_FILTER and not in CLUSTER.

This is the first question I'm trying to understand, what the difference common_http_protocol_options in CLUSTER and in HTTP_FILTER

**Comment by fatedier** [comment]
> But! DestinationRule manages HttpProtocolOptions in the HTTP_FILTER and not in CLUSTER.
@alt-dima From my test, DestinationRule will manage idletimeout in CLUSTER for mesh-internal service.

```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: eample
spec:
  host: example
  trafficPolicy:
    connectionPool:
      http:
        idleTimeout: 14s
```
