### ISSUE TITLE
Istio-cni 1.15 not working with SELinux enabled

### ISSUE THREAD

**Issue by xpivarc** [istio/istio#41363]
### Bug Description

Deploying istio-cni 1.15 on a node that has SELinux enabled is failing. 

It is caused by  
```
- hostPath:
   path: /var/run/istio-cni
   type: ""
   name: cni-log-dir
```
the path `/var/run/istio-cni` is going to be created on the node with label `system_u:object_r:container_var_run_t:s0 istio-cni`. This causes istio to fail as `container_t` cannot write to this directory.

### Version

```prose
1.15
```
