### ISSUE TITLE
httpFault RouteRule matching on uri prefix matches everything

### ISSUE THREAD

**Issue by SeriyBg** [istio/istio#4139]
I have two services: `ui-service` and `city-service`. When accessing `ui-service` it makes a call to `city-service` in form of `/city/{cityName}`. I'm trying to add a `httpFault` `RouteRule` for accessing `city-service` based on the uri. Here is my `RouteRule`:
```
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: city-service-fault
spec:
  destination:
    name: city-service
  match:
    request:
      headers:
        uri:
          prefix: "/city/London"
  httpFault:
    abort:
      percent: 100
      httpStatus: 400
```
I'm expecting to get `httpFault` only for a request to `/city/London` but in fact, I'm getting HTTP status `400` to for any city.
I have tried to change the prefix to the following: `prefix: "/aaaaaa"` and the result is the same - I'm getting the HTTP status `400` for all the requests.
