### ISSUE TITLE
httpFault RouteRule matching on uri regex doesn't match anything

### ISSUE THREAD

**Issue by SeriyBg** [istio/istio#4140]
The configuration I have is the same as for #4139 but this time I'm trying to match on `uri: regex:`. And the behavior is completely different I don't get `httpFault` at all.
Here is the `yaml` configuration:
```
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: city-service-fault
spec:
  destination:
    name: city-service
  match:
    request:
      headers:
        uri:
          regex: ".*"
  httpFault:
    abort:
      percent: 100
      httpStatus: 400
```
Here I'm trying to match any request from any `uri`, however all the requests passes.

I'm using `istio v0.6`
Running on `minikube v0.25.0` on MacOS
