### ISSUE TITLE
Need help on finding the wildcard hosts configuration for Gateway

### ISSUE THREAD

**Issue by kamaraj-muthupandian** [istio/istio#41427]
HI Team,
I need to configure path based routing through ISTIO. For some reasons, I cant give  "*" which will enable gateway for all the hosts, so I need a config for path based routing 

for example hosts: "**dev-cluster-istio-ingress.abcd.com/***" ( This is not working, I need to route the traffic according to path defined in virtual service)

Below are my configuration of Gateway and Virtual service. 

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: default-gateway
  namespace: istio-ingress
spec:
  selector:
      istio: ingress
      app: istio-ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - "*"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https-443
      protocol: HTTP
    hosts:
      - "*"
      
```
    ==============

Virtual Service configuration

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx1-vs
  namespace: nginx1 
spec:
  hosts:
  - dev-cluster-istio-ingress.abcd.com
  gateways:
  - istio-ingress/default-gateway
  http:
  - match:
    - uri:
        prefix: /v2/nginx
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 80
        host: nginx1.nginx1.svc.cluster.local
```

**Comment by zirain** [comment]
according to you gateway

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx1-vs
  namespace: nginx1 
spec:
  hosts:
  - dev-cluster-istio-ingress.abcd.com
  gateways:
  - istio-ingress-ext/default-gateway # this should be istio-ingress/default-gateway?
  http:
  - match:
    - uri:
        prefix: /v2/nginx
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 80
        host: nginx1.nginx1.svc.cluster.local
```
