### ISSUE TITLE
Insert listener filters before or after other filters

### ISSUE THREAD

**Issue by luk3thomas** [istio/istio#41445]
**Describe the feature request**
I want to insert a LISTENER filter at a specific index in `listener_filters`, specifically I want to add `envoy.filters.listener.proxy_protocol` as the first entry of `listener_filters`.

The `EnvoyFilter` custom resource allows you to insert filters BEFORE or AFTER other network or HTTP filters. However, I haven't seen anything in the documentation that would give me precise control of `listener_filter` placement though.

**Describe alternatives you've considered**

It is possible to add the `envoy.filters.listener.proxy_protocol` to `listener_filters` by merging into a listener.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: proxy-protocol
  namespace: istio-system
spec:
  configPatches:
  - applyTo: LISTENER
    patch:
      operation: MERGE
      value:
        listener_filters:
        - name: envoy.filters.listener.proxy_protocol
```

However, any new filters added are appended to the end when a listener contains a non-empty `listener_filters` list. For example, given a listener:

```yaml
name: 10.0.83.114_6514
trafficDirection: OUTBOUND
address:
  socketAddress:
    address: 10.0.83.114
    portValue: 6514
listenerFilters:
- name: envoy.filters.listener.tls_inspector
- name: envoy.filters.listener.http_inspector
``` 

Once we merge the attributes defined in `EnvoyFilter` we end up with something like this:
```diff
  name: 10.0.83.114_6514
  trafficDirection: OUTBOUND
  address:
    socketAddress:
      address: 10.0.83.114
      portValue: 6514
  listenerFilters:
  - name: envoy.filters.listener.tls_inspector
  - name: envoy.filters.listener.http_inspector
+ - name: envoy.filters.listener.proxy_protocol
```

In the case of PROXY protocol is it crucial that it is defined as the first entry of `listener_filters`, otherwise it does not work.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

Thank you!
