### ISSUE TITLE
why splite virtualhost when virtualservice havs multi hosts not in service?

### ISSUE THREAD

**Issue by pyrl247** [istio/istio#41458]
When we have a virtualsvc like below:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: test
spec:
  exportTo:
  - .
  hosts:
  - "aaa.com"
  - "bbb.com"
  http:
  - match:
    - uri:
        prefix: /
    name: aaa-route
    route:
    - destination:
        host: aaa.com
      weight: 100
```
And only have svc with host aaa.com.
When build rds ,it will split aaa.com and bbb.com in different virtualhost(https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/httproute.go#L451).
I'm a little confused as to what the purpose of this is.
