### ISSUE TITLE
Istio cannot be deployed on IPv6-first DS clusters

### ISSUE THREAD

**Issue by LithiumSR** [istio/istio#41462]
### Bug Description

Hello everyone,
I have noticed that if I deploy Istio on a DS clusters which has IPv6 as default family it will never go ready.
In particular, the controller will be ready, but the gateways (and sidecars) will not.
This is caused by the readiness probe that will never succeed as shown from kubectl describe:

> Readiness probe failed: Get "http://[2001:db8:42::15]:15021/healthz/ready": dial tcp [2001:db8:42::15]:15021: connect: connection refused

This behavior does not show up in DS clusters that have IPv4 as default family.
I was able to reproduce the behavior with both Istio 1.15.2 and Istio 1.14.4.

Here are some steps to easily reproduce the issue:

0. Download and Install Kind 0.16.0. It is better to have the latest KinD version as previous older versions may not support IPv6-first DS clusters deployment.
1.  Create a yaml file with the following KinD configuration:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: dual
  podSubnet: "2001:db8:42:0::/56,10.244.0.0/16"
  serviceSubnet: "2001:db8:42:1::/112,10.96.0.0/12"
```
N.B: The fact that the IPv6 CIDR comes before the IPv4 one will determine the IPv6-first nature of the cluster.

2. Create the cluster via `kind create cluster --config path_to_yaml`
3. Verify that the DS cluster has IPv6 as the default IPFamily
```
$ kubectl create deployment nginx --image=nginx
$ kubectl get pod nginx_pod_name -o jsonpath='{.status.podIP}'
<You should see an IPv6 address>
```
4. Install Istio (master branch) via `istioctl install --set profile=demo` and the following operator
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
   components:
      pilot:
         k8s:
            env:
               - name: ISTIO_DUAL_STACK
                 value: "true"
   meshConfig:
      defaultConfig:
         proxyMetadata:
            ISTIO_AGENT_DUAL_STACK: "true"
```
5. Check that the gateways are not going ready due to the probes failing after waiting for a while.
```
NAMESPACE            NAME                                         READY   STATUS    RESTARTS   AGE
istio-system         istio-egressgateway-5c7dbb79bf-6kqms         0/1     Running   0          8m45s
istio-system         istio-ingressgateway-577d6c976f-g594v        0/1     Running   0          8m45s
istio-system         istiod-749dd8f9c4-qdcjc                      1/1     Running   0          8m53s
```
I also tried to manually contact the stats endpoint of the proxies and I also found similar connectivity issues.
Let me know if more information is needed

### Version

```prose
$ istioctl version
client version: 1.15.2
control plane version: 1.15.2
data plane version: 1.15.2 (2 proxies)
```

### Additional Information

[ds_ipv6.tar.gz](https://github.com/istio/istio/files/9801796/ds_ipv6.tar.gz)

**Comment by LithiumSR** [comment]
Thank you @zhlsunshine 
I will keep this open so that you can link your DS PR once that is open 👍

**Comment by zhlsunshine** [comment]
Hi @LithiumSR, I think you can have a try on both master and experimental-dual-stack branch for your issue. And hope you can leave the message here for your test result. Thanks in advance!

**Comment by LithiumSR** [comment]
Hello @zhlsunshine
Thank you for fixing it!
Do I need to use any special DS flag for the deployment or are the default values good enough?

**Comment by zhlsunshine** [comment]
> Hello @zhlsunshine Thank you for fixing it! Do I need to use any special DS flag for the deployment or are the default values enough?

Hi @LithiumSR, this issue should be fixed by [PR#43099](https://github.com/istio/istio/pull/43099)

**Comment by LithiumSR** [comment]
I see the commit got merged, I will close the issue.
Thank you Steve 👍

**Comment by LithiumSR** [comment]
Hello Steve,
I tried the dev build that includes the fix (https://gcsweb.istio.io/gcs/istio-build/dev/1.18-alpha.b5df9a51c0290df8fd2692e7578bbef62a315d42) and it seems that I can't deploy it even after setting ISTIO_DUAL_STACK and the proxy ISTIO_AGENT_DUAL_STACK var to true. I hope it is just me that messed up the conf.
Can you try to reproduce the issue by deploying it on a KinD DS IPv6-first cluster (see the initial post for the KinD config file)?

**Comment by LithiumSR** [comment]
Hey Steve.
While testing on DS (IPv4 first this time) I noticed that probes to http://IPV6_PODIP:15021/healthz/ready may not be working either.
Both issues likely share the same root-cause.
I will double check tomorrow my findings

**Comment by zhlsunshine** [comment]
Hi @LithiumSR, how do you install the istio with dual stack enabled?

**Comment by LithiumSR** [comment]
Hello Steve,
I used the following operator to reproduce the issue.
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
   components:
      pilot:
         k8s:
            env:
               - name: ISTIO_DUAL_STACK
                 value: "true"
   meshConfig:
      defaultConfig:
         proxyMetadata:
            ISTIO_AGENT_DUAL_STACK: "true"
```

**Comment by zhlsunshine** [comment]
Hi @LithiumSR, which release did you try it? 1.17 or master branch?

**Comment by LithiumSR** [comment]
Hello Steve, 
I have tried with master (head at b5df9a51c0290df8fd2692e7578bbef62a315d42).

**Comment by zhlsunshine** [comment]
Hi @LithiumSR, I have 2 suggestions for your case:
1. Change the setting from `cluster.Cluster_ALL` into ·cluster.V4_PREFERRED` at L#381 in `[pilot/pkg/networking/core/v1alpha3/cluster_builder.go](https://github.com/istio/istio/commit/b5df9a51c0290df8fd2692e7578bbef62a315d42#diff-9776eb0b58b61447b128d0f2992e56e3f17f9427d53f07365195856045865bda)`
2. Change the setting from `cluster.Cluster_ALL` into ·cluster.Cluster_AUTO` at L#381 in `[pilot/pkg/networking/core/v1alpha3/cluster_builder.go](https://github.com/istio/istio/commit/b5df9a51c0290df8fd2692e7578bbef62a315d42#diff-9776eb0b58b61447b128d0f2992e56e3f17f9427d53f07365195856045865bda)`
And I will try your case asap.

**Comment by LithiumSR** [comment]
Hello Steve,
Sorry for the delay I was on vacation.
I tried changing to V4_preferred and auto but the problem persists

**Comment by zhlsunshine** [comment]
Hi @LithiumSR and @kfaseela, please have a try the PR: https://github.com/istio/istio/pull/43892

**Comment by LithiumSR** [comment]
Hello @zhlsunshine
I have verified the probes behavior on DS and it seems that there is still something that is not working properly:
- DS IPv4-first clusters: probe to IPV6_POD_IP/healthz/ready of istio-proxy fails
- DS IPv6-first clusters: probe to IPV4_POD_IP/healthz/ready of istio-proxy fails

Do you want me to raise a new ticket for that?

**Comment by zhlsunshine** [comment]
Hi @LithiumSR, I understand there are some cross errors, do they occur randomly or regularly?

**Comment by LithiumSR** [comment]
Hello Steve,
As far as I know they are always there. The request to the proxy health endpoint fails due to "connection refused" like if the proxy does not listen on the IP family that is not the default one of the cluster.

**Comment by zhlsunshine** [comment]
Could you please provide more detail? No error message from my environment no matter which one is the first, I mean I have tried both IPv4-first and IPv6-first DS cluster in my environment.

**Comment by zhlsunshine** [comment]
> Hello Steve, As far as I know they are always there. The request to the proxy health endpoint fails due to "connection refused" like if the proxy does not listen on the IP family that is not the default one of the cluster.


Hi @LithiumSR, could you please provide more detail? No error message from my environment no matter which one is the first, I mean I have tried both IPv4-first and IPv6-first DS cluster in my environment.

**Comment by LithiumSR** [comment]
Hello Steve,
Sure, I will reproduce and write down the steps.

**Comment by LithiumSR** [comment]
Hello Steve,
Here are some steps:

0. Obtain a DS cluster using Kind (the default Ip-family is not important for the verification). I used a DS Kind cluster with IPv4 as default.
1. Deploy Istio SM (commit used: Head of https://github.com/zhlsunshine/istio/tree/dnsFamilyWithIPv6First) with DS enabled.
I used the images and the istioctl I built from your branch.
Istioctl command "./out/linux_amd64/istioctl install --set profile=demo -f DS_operator.yaml"
DS_operator.yaml is as follows:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
   components:
      pilot:
         k8s:
            env:
               - name: ISTIO_DUAL_STACK
                 value: "true"
   meshConfig:
      defaultConfig:
         proxyMetadata:
            ISTIO_AGENT_DUAL_STACK: "true"
```
2. Deploy sleep by using kubectl apply -f https://github.com/istio/istio/blob/master/samples/sleep/sleep.yaml -n istio-system
3. Obtain the two pod ips of ingress gw
kubectl get pods $ingress_gw_pod -n istio-system -o yaml
Example:
```
  podIP: 10.244.0.13
  podIPs:
  - ip: 10.244.0.13
  - ip: fd00:10:244::d
```
4. Contact the healthz readiness endpoints of the ingress gw
The request using the pod ip matching the default family of your cluster will work, the other will fail.
```
kubectl exec $sleep_pod -n istio-system -it -- curl ingressgw_pod_ip_ipv4:15021/healthz/ready -v
...
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< date: Fri, 17 Mar 2023 13:18:05 GMT
< content-length: 0
< x-envoy-upstream-service-time: 0
< server: envoy
< 
* Connection #0 to host 10.244.0.13 left intact
kubectl exec $sleep_pod -n istio-system -it -- curl [ingressgw_pod_ip_ipv6]:15021/healthz/ready -v
*   Trying fd00:10:244::d:15021...
* TCP_NODELAY set
* connect to fd00:10:244::d port 15021 failed: Connection refused
* Failed to connect to fd00:10:244::d port 15021: Connection refused
* Closing connection 0
curl: (7) Failed to connect to fd00:10:244::d port 15021: Connection refused
command terminated with exit code 7
```

Let me know in case of difficulties in reproducing
