### ISSUE TITLE
propagated tracing context header values are wrong

### ISSUE THREAD

**Issue by pratapgowda007** [istio/istio#41460]
### Bug Description

How to avoid header value rewrite while routing the request via Istio proxy?

Tracing context propagation header values are not correct while routing the requests via Istio proxy. I'm using Jaeger in my application for distributed tracing and set context propagation to w3c. So each service propagates a transparent header.

If I make direct requests to my applications without using the Istio proxy, end-to-end tracing is working as expected and propagated header values are correct. If I make a request via istio proxy, then the propagated header values are not correct.

**Example:**
I'm having 3 services named application-a, application-b and application-c
`application-a --> application-b --> application-c`

When a request is received at application-a, it generates a new traceid and propagates a transparent header to application-b. application-b uses the same trace-id and generates its span as a child of the span-id received via transparent header. While making a call to application-c, application-b updates the transparent header with its last span and propagates it to application-c. But it looks like Istio's Envoy Proxy is rewriting the header to its older value.

application-a to application-b
`traceparent 00-0000000000000000a496af84d80e8285-7e9730dcae98385c-01`

application-b to application-c
`traceparent 00-0000000000000000a496af84d80e8285-7e9730dcae98385c-01`

As we can see, Istio's Envoy proxy has rewritten the SpanId in the transparent header back to its older value.

May I know how to disable header value rewrite? I disabled tracing in istioOperator as I don't want Istio to initiate tracing.

**IstioOperator:**
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:  
  name: my-istio-control-plane
  namespace: istio-system
spec:
  components:
    cni:
      enabled: true
      namespace: kube-system
    egressGateways:
    - enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2
      name: istio-egressgateway
    ingressGateways:
    - enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2
      name: istio-ingressgateway
    - enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2
        service:
          ports:
          - name: status-port
            port: 15020
            targetPort: 15021
          - name: http2
            port: 80
            targetPort: 8080
          - name: https
            port: 443
            targetPort: 8443
          type: ClusterIP
      label:
        app: cluster-local-gateway
        istio: cluster-local-gateway
      name: cluster-local-gateway
    pilot:
      enabled: true
      k8s:
        env:
        - name: PILOT_TRACE_SAMPLING
          value: "100.0"
        hpaSpec:
          minReplicas: 2
  hub: iad.ocir.io/cxcomms/istio
  meshConfig:
    defaultConfig:
      tracing:
        sampling: 100
    enableTracing: false
  profile: minimal
  values:
    global:
      enableAutoMtls: true
      imagePullSecrets:
      - mysecret
      outboundTrafficPolicy:
        mode: ALLOW_ANY
      useMCP: false
```

### Version

```prose
client version: 1.13.2
control plane version: 1.13
data plane version: 1.13-dev (37 proxies)

Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.22.5
```
