### ISSUE TITLE
503 SERVICE_UNAVAILABLE and body upstream connect error or disconnect/reset before headers. reset reason: connection termination

### ISSUE THREAD

**Issue by dawo0od** [istio/istio#41512]
### Bug Description

We are facing the below issue intermittently when we call an external service outside our cluster
**status code 503 SERVICE_UNAVAILABLE and body upstream connect error or disconnect/reset before headers. reset reason: connection termination**

We have investigated a lot and we found that we are getting above error in our caller Microservice logs , and the request is not reaching the external service we are trying to call. We tried disabling the side car from our internal Microservice ,after that the service started working successfully and the issue did not happen again.

Is there any configuration we need to do with ISTIO instead of disabling the sidecar as actually this is a workaround not an actual fix.

**NOTE: This issue happens only in case we are calling an external service.**

### Version

```prose
$ istioctl version
client version: 1.12.0
control plane version: 1.12.0
data plane version: 1.12.0 (271 proxies)

$ kubectl version --short
Client Version: v1.21.2
Server Version: v1.21.14-eks-6d3986b
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by DSP-doublehappy111** [comment]
Is the phenomenon you are talking about similar to the description below?
I also confused that.

http://gateway.echo-2-93760.svc.cluster.local:80 (using http): response[0]: exp
ected response code `200`, got "503". Response: RawContent:       [0] Url=http://gateway.echo-2-93760.svc.cluster.local:80
        [0] Latency=1.00497493s
        [0] ActiveRequests=1
        [0] StatusCode=503
        [0] ResponseHeader=Content-Length:145
        [0] ResponseHeader=Content-Type:text/plain
        [0] ResponseHeader=Date:Sun, 09 Oct 2022 01:19:57 GMT
        [0] ResponseHeader=Server:envoy
        [0 body] upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 111

        ID:
        Method:
        Protocol:
        Alpn:
        URL:
        Version:
        Port:
        Code:             503
        Host:
        Hostname:
        Cluster:
        IstioVersion:
        IP:
        Request Headers:  map[]
        Response Headers: map[Content-Length:[145] Content-Type:[text/plain] Date:[Sun, 09 Oct 2022 01:19:57 GMT] Server:[envoy]]

**Comment by jd-codelink** [comment]
I'm having the same problem with one of my services. Did you figure out how to solve this problem?

**Comment by DSP-doublehappy111** [comment]
It seems that the cluster has a bad  network.

**Comment by DSP-doublehappy111** [comment]
Such as the workload can not visit the istiod , ingress or egress's service .And custom CNI may cause this.
Maybe some service does not effect.

**Comment by DSP-doublehappy111** [comment]
Of course, we meet the same problem under the different status.

**Comment by jd-codelink** [comment]
I see. Did you resolve the issue by configuring istio-proxy or make change within your services?

**Comment by DSP-doublehappy111** [comment]
No. I only change and check the CNI.

**Comment by jd-codelink** [comment]
Can you elaborate?

**Comment by alt-dima** [comment]
Try this! Please provide feedback. I'm trying to find a solution for istio/envoy and nodejs apps (with 5sec default keepAlive)
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: fix-for-nodejs
  namespace: "${kubernetes_namespace_v1.istio_namespace.metadata[0].name}"
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      cluster:
      context: SIDECAR_OUTBOUND
    patch:
      operation: MERGE
      value:
        typed_extension_protocol_options:
          envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
            '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
            common_http_protocol_options:
              idle_timeout: 4s
            use_downstream_protocol_config: 
              http2_protocol_options: {}
              http_protocol_options: {}
  - applyTo: CLUSTER
    match:
      cluster:
      context: SIDECAR_INBOUND
    patch:
      operation: MERGE
      value:
        typed_extension_protocol_options:
          envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
            '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
            common_http_protocol_options:
              idle_timeout: 4s
            use_downstream_protocol_config: 
              http2_protocol_options: {}
              http_protocol_options: {}
```
