### ISSUE TITLE
EnvoyFilter not matching on other EnvoyFilter with lower priority

### ISSUE THREAD

**Issue by breuerfelix** [istio/istio#41536]
### Bug Description

We have a TCP Listener `0.0.0.0_8443` with a simple TCP Proxy as the default filter_chain.  
The following EnvoyFilter creates a new filter_chain on the Listener that matches a certain address_prefix and proxies to a different location:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: define-filter-chain
  namespace: istio-ingress
spec:
  configPatches:
  - applyTo: FILTER_CHAIN
    match:
      context: ANY
      listener:
        name: 0.0.0.0_8443
        portNumber: 8443
    patch:
      operation: ADD
      value:
        filter_chain_match:
          destination_port: 443
          prefix_ranges:
          - address_prefix: 10.10.10.10
            prefix_len: 32
        filters:
        - name: envoy.filters.network.tcp_proxy
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
            cluster: outbound|443||kube-apiserver.shoot.svc.cluster.local
            stat_prefix: outbound|443||kube-apiserver.shoot.svc.cluster.local
        name: foobar
  priority: -10
  workloadSelector:
    labels:
      app: istio-ingressgateway
      istio: ingressgateway
```

We add another EnvoyFilter that has a higher priority and should add an rbac rule into the filter_chain created by the first EnvoyFilter.  
However, the second EnvoyFilter is never applied in the resulting Envoy config.  
We tried matching by destinationPort, filterchain name and also by specifying the networkfilter name (envoy.filters.network.tcp_proxy) without success.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: authorization-policies
  namespace: istio-ingress
spec:
  workloadSelector:
    labels:
      app: istio-ingressgateway
      istio: ingressgateway
  priority: 10
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: ANY
      listener:
        filterChain:
          name: foobar
    patch:
      operation: INSERT_FIRST
      value:
        name: authorization-policies
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.rbac.v3.RBAC
          stat_prefix: envoyrbac
          rules:
            action: DENY
            policies:
              authorization-policies:
                permissions:
                - any: true
                principals:
                - any: true
```
See the resulting envoy config in the additional informations.

### Version

```prose
istioctl version:
client version: 1.15.0
control plane version: 1.14.1
data plane version: 1.14.1 (2 proxies)

kubectl version:
Client Version: v1.24.0
Server Version: v1.21.11
```

### Additional Information

This is the resulting filter_chain from the envoy config_dump:
```json
{
 "filter_chain_match": {
  "prefix_ranges": [
   {
    "address_prefix": "10.10.10.10",
    "prefix_len": 32
   }
  ],
  "destination_port": 443
 },
 "filters": [
  {
   "name": "envoy.filters.network.tcp_proxy",
   "typed_config": {
    "@type": "type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy",
    "stat_prefix": "outbound|443||kube-apiserver.shoot.svc.cluster.local",
    "cluster": "outbound|443||kube-apiserver.shoot.svc.cluster.local"
   }
  }
 ],
 "name": "foobar"
},
```

This setup is inside the gardener/gardener environment.  
The first EnvoyFilter is created by another part of the system which we do not have control over.  
Our current workaround is to write a mutating Webhook which mutates the first Envoyfilter in order to add the rbac rules. The ability to just add the second EnvoyFilter which mutates the filter_chain would simplify our setup a lot.
