### ISSUE TITLE
Istio VirtualService HeaderOperations do not override certain headers

### ISSUE THREAD

**Issue by cinglese** [istio/istio#41589]
When using a [RequestAuthentication](https://istio.io/latest/docs/reference/config/security/request_authentication/) resource with a [JWTRule](https://istio.io/latest/docs/reference/config/security/jwt/#JWTRule) with the parameter `forwardOriginalToken: true`, the VirtualService will not remove the `authorization` request header if specified.

```
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
spec:
  jwtRules:
  - forwardOriginalToken: true
    issuer: https://adfs.contoso.com/adfs/services/trust
    jwksUri: https://adfs.contoso.com/adfs/discovery/keys
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
spec:
  gateways:
  - istio-system/public
  hosts:
  - endpoint.example.foo
  http:
  - name: endpoint-example-foo
  route:
  - destination:
       host: foo.namespace.svc.cluster.local
       port:
         number: 80
     headers:
       request:
         remove:
         - authorization
```

Istio v1.15.0
