### ISSUE TITLE
AuhorizationPolicy with non `istio-system` workload selector doesn't support `paths`

### ISSUE THREAD

**Issue by brightsparc** [istio/istio#41602]
### Bug Description

I would like to build an application such that the `/api` path is secured with JWT by `RequestAuthentication` and `AuthorizationPolicy` that are matching the `app: nginx` deployment like so:

```
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
spec:
  selector:
    app: httpbin
  ports:
  - name: http
    port: 8000
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: api-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - api.example.com
      # tls:
      #   httpsRedirect: true # need to disable until cert is issued
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: api-example-com-tls
      hosts:
        - api.example.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-vs
spec:
  hosts:
    - example.com
  gateways:
    - api-gateway
  http:
    - match:
      - uri:
          exact: /api/jwks # This will override general /api/* endpoints
      rewrite:
        uri: /headers
      route:   
      - destination:
          host: httpbin.istio-weekly.svc.cluster.local
          port:
            number: 8000  
    - match:
      - uri:
          prefix: /api
      rewrite:
        uri: /status # test rewrite to status page
      route:   
      - destination:
          host: httpbin.istio-weekly.svc.cluster.local
          port:
            number: 8000
---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: api-ra
spec:
  selector:
    matchLabels:
      app: httpbin
  jwtRules:
  - issuer: "me"
    jwks: "my_jwks_json"
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: api-ap
spec:
  selector:
    matchLabels:
      app: httpbin
  action: ALLOW 
  rules:
  - from:
    - source:
        requestPrincipals:
        - example/*
    to:
    - operation:
        hosts:
        - example.com
        methods:
        - GET
        - POST
        paths:
        - "/api/*" # api requires jwt token
  - to:
    - operation:
        hosts:
        - example.com
        methods:
        - GET
        paths:
        - "/api/jwks" # want to make this publicly accessible
 ```

When I attempt to define these in the `istio-weekly` namespace, I find that the the `paths` values do not get applied.  When I create these in the `istio-system` namespace these DO work.  

However, I require having a different `CUSTOM` authorization policy that uses an OAuth2 proxy configured in mesh `extensionProviders` for other paths on the same domain, and when these co-exist in the `istio-system` namespace they clash.

It seems that this is a bug that the `AuthorizationPolicy` can not be applied at the application workload level as the docs have an example for this: https://istio.io/latest/docs/reference/config/security/request_authentication/

When I make a `curl` request the endpoint with the path filter, I get back the following which includes a `X-Envoy-Original-Path` parameter, nto sure if this is somehow obfuscating the real path for the `AuthorizationPolicy` check.

```
curl https://api.example.com/api/jwks                                   
{
  "headers": {
    "Accept": "*/*", 
    "Host": "api.example.com", 
    "User-Agent": "curl/7.79.1", 
    "X-B3-Parentspanid": "3b36a8ad2a2fb46b", 
    "X-B3-Sampled": "0", 
    "X-B3-Spanid": "a80a318321f77dde", 
    "X-B3-Traceid": "2142e66b0e5048bb3b36a8ad2a2fb46b", 
    "X-Envoy-Attempt-Count": "1", 
    "X-Envoy-Internal": "true", 
    "X-Envoy-Original-Path": "/api/jwks", 
    "X-Forwarded-Client-Cert": "By=spiffe://cluster.local/ns/istio-weekly/sa/default;Hash=78d36b3112029c2405b5b7509a0244eaa0cd234d48eee078e7733c6cc093d22a;Subject=\"\";URI=spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"
  }
}
```

But when I added the path filter I get the following:

```
curl https://api.example.com/api/jwks
RBAC: access denied 
```

### Version

```prose
$ istioctl version
client version: 1.15.0
control plane version: 1.15.0
data plane version: 1.15.0 (4 proxies)
$ kubectl version --short                                                
Client Version: v1.24.1
Kustomize Version: v4.5.4
Server Version: v1.22.13-eks-15b7512
```

### Additional Information

```
$istioctl bug-report 

Target cluster context: arn:aws:eks:us-east-1:474375891613:cluster/xxxxxxxx

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2022-10-24 14:44:28.290588 +1100 AEDT



Cluster endpoint: https://00931F6A192C87C80B6CFB840D1C3608.gr7.us-east-1.eks.amazonaws.com
CLI version:
version.BuildInfo{Version:"1.15.0", GitRevision:"e3364ab424b70ca8ee1ca76cb0b3afb73476aaac-dirty", GolangVersion:"go1.18.5", BuildStatus:"Clean", GitTag:"1.15.0"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.15.0", GitRevision:"e3364ab424b70ca8ee1ca76cb0b3afb73476aaac", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.15.0"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.15.0}


Fetching proxy logs for the following containers:

cert-manager/cert-manager-cainjector/cert-manager-cainjector-6cd8d7f84b-8t78f/cert-manager
cert-manager/cert-manager-webhook/cert-manager-webhook-64d76db6c-2qlgn/cert-manager
cert-manager/cert-manager/cert-manager-7b8d75c477-pw8dh/cert-manager
istio-system/istio-ingressgateway/istio-ingressgateway-57486bb7b-6rc8h/istio-proxy
istio-system/istiod/istiod-795dbdd8d6-z4xw2/discovery
istio-weekly/httpbin/httpbin-7c5f796f9c-6g9ph/httpbin
istio-weekly/httpbin/httpbin-7c5f796f9c-6g9ph/istio-proxy
istio-weekly/nginx/nginx-7848d4b86f-trr6x/istio-proxy
istio-weekly/nginx/nginx-7848d4b86f-trr6x/nginx
oauth2-proxy/oauth2-proxy/oauth2-proxy-6867987d4d-jbqzh/istio-proxy
oauth2-proxy/oauth2-proxy/oauth2-proxy-6867987d4d-jbqzh/oauth2-proxy

Fetching Istio control plane information from cluster.


The following fetches are still running: 
  kubectl get --all-namespaces authorizationpolicies.security.istio.io,certificaterequests.cert-manager.io,certificates.cert-manager.io,challenges.acme.cert-manager.io,clusterissuers.cert-manager.io,destinationrules.networking.istio.io,eniconfigs.crd.k8s.amazonaws.com,envoyfilters.networking.istio.io,gateways.networking.istio.io,grafanaagents.monitoring.grafana.com,issuers.cert-manager.io,istiooperators.install.istio.io,logsinstances.monitoring.grafana.com,metricsinstances.monitoring.grafana.com,orders.acme.cert-manager.io,peerauthentications.security.istio.io,podlogs.monitoring.grafana.com,podmonitors.monitoring.coreos.com,probes.monitoring.coreos.com,proxyconfigs.networking.istio.io,rayclusters.ray.io,rayservices.ray.io,requestauthentications.security.istio.io,securitygrouppolicies.vpcresources.k8s.aws,serviceentries.networking.istio.io,servicemonitors.monitoring.coreos.com,sidecars.networking.istio.io,telemetries.telemetry.istio.io,virtualservices.networking.istio.io,wasmplugins.extensions.istio.io,workloadentries.networking.istio.io,workloadgroups.networking.istio.io -o yaml
  PodExec istio-system/istiod-795dbdd8d6-z4xw2/discovery:pilot-discovery request GET debug/networkz
  ProxyGet istio-system/istio-ingressgateway-57486bb7b-6rc8h:runtime
  ProxyGet oauth2-proxy/oauth2-proxy-6867987d4d-jbqzh:runtime

Running istio analyze on all namespaces and report as below:
Analysis Report:
Info [IST0102] (Namespace cert-manager) The namespace is not enabled for Istio injection. Run 'kubectl label namespace cert-manager istio-injection=enabled' to enable it, or 'kubectl label namespace cert-manager istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace default) The namespace is not enabled for Istio injection. Run 'kubectl label namespace default istio-injection=enabled' to enable it, or 'kubectl label namespace default istio-injection=disabled' to explicitly mark it as not needing injection.
```
