### ISSUE TITLE
IngressGateway service annotation ignored by IstioOperator

### ISSUE THREAD

**Issue by samuelgautier** [istio/istio#41608]
### Bug Description

**Introduction**
"service.beta.kubernetes.io/azure-load-balancer-internal-subnet" service annotation is ignored by Istio Operator, and then it complains about the Load Balancer IP address that is not in the range of the AKS POD subnet.

**Context**
Implementing ISTIO Ingress Gateway on AKS behind a private Azure Load Balancer that will be used as the backend pool of an Azure Application Gateway.

**Here is my custom install yaml file :** 

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: minimal #or demo
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          serviceAnnotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: true
            service.beta.kubernetes.io/azure-load-balancer-internal-subnet: snet-front-sandbox
          service:
            loadBalancerIP: 172.29.123.249
```

**Issue**
The Azure Load Balancer fails to create because the IP address (loadBalancerIP) is not in the same IP range than the AKS pods. And that's normal because i want the Azure Load Balancer to be created in another subnet, that's the reason why i provide an other service annotation (service.beta.kubernetes.io/azure-load-balancer-internal-subnet)

**Workaround**
Override manually the service annotations and then the Azure Load Balancer is successfully created.

### Version

```prose
$ istioctl version
client version: 1.15.2
control plane version: 1.15.2
data plane version: 1.15.2 (17 proxies)

$ kubectl version --short
Client Version: v1.25.3
Kustomize Version: v4.5.7
Server Version: v1.24.3
```

**Comment by samuelgautier** [comment]
sorry the indentation in my custom installation yaml file has been removed !!!

**Comment by zirain** [comment]
maybe related to https://github.com/istio/istio/issues/40903#issuecomment-1244832911

**Comment by zirain** [comment]
should the IOP configuration be like:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: minimal #or demo
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          serviceAnnotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
            service.beta.kubernetes.io/azure-load-balancer-internal-subnet: snet-front-sandbox
          service:
            loadBalancerIP: 172.29.123.249
```

```console
k get svc -nistio-system istio-ingressgateway -oyaml  | grep service.beta.kubernetes.io
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: snet-front-sandbox

```

**Comment by keithmattix** [comment]
Hi @samuelgautier - are you still experiencing this issue?

**Comment by samuelgautier** [comment]
Hello @keithmattix ,
No more issue, because I have deployed new instances with Istio version 1.16.1 and the following custom install file:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: minimal #or demo
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          serviceAnnotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
            service.beta.kubernetes.io/azure-load-balancer-internal-subnet: snet-front-horec
          service:
            loadBalancerIP: 172.29.75.249
```
@zirain In my previous tests, I'm pretty sure I did tests with quotes around "true" and that it didn't work any better...but I couldn't swear ;p

Thx.
