### ISSUE TITLE
Gateway installation via `IstioOperator` render failed when k8s version >=v1.23.0

### ISSUE THREAD

**Issue by cbl315** [istio/istio#41623]
### Bug Description

Install istio gateway via `IstioOperator` when k8s version >= v1.23.0 (The version that `autoscaling/v2beta1` been deprecated) failed, below are description of iop:

```yaml
k -n istio-system describe iop istio-ingressgateway
Name:         istio-ingressgateway
Namespace:    istio-system
Labels:       <none>
Annotations:  <none>
API Version:  install.istio.io/v1alpha1
Kind:         IstioOperator
Spec:
  Components:
    Ingress Gateways:
      Enabled:  true
      k8s:
        Hpa Spec:
          Max Replicas:  10
          Metrics:
            Resource:
              Name:                        cpu
              Target Average Utilization:  80
            Type:                          Resource
          Min Replicas:                    2
          Scale Target Ref:
            API Version:  apps/v1
            Kind:         Deployment
            Name:         istio-ingressgateway
      Name:               istio-ingressgateway-1
      Namespace:          istio-ingress
Status:
  Component Status:
    Base:
      Status:  HEALTHY
    Ingress Gateways:
      Error:   failed to update resource with server-side apply for obj HorizontalPodAutoscaler/istio-ingress/istio-ingressgateway-1: failed to create typed patch object (istio-ingress/istio-ingressgateway-1; autoscaling/v2, Kind=HorizontalPodAutoscaler): .spec.metrics[0].resource.targetAverageUtilization: field not declared in schema
      Status:  ERROR
    Pilot:
      Status:  HEALTHY
  Status:      ERROR
Events:        <none>
```

Minimual yaml to reproduce:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  components:
    ingressGateways:
    - enabled: true
      k8s:
        hpaSpec:
          maxReplicas: 10
          metrics:
          - resource:
              name: cpu
              # target:
              #   type: Utilization
              #   averageUtilization: 80
              targetAverageUtilization: 80
            type: Resource
          minReplicas: 2
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: istio-ingressgateway
      name: istio-ingressgateway-1
      namespace: istio-ingress
```

### Version

```prose
> k version --short
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.24.6

> istioctl-1.15.2 version
client version: 1.15.2
control plane version: 1.14.5
data plane version: 1.14.5 (4 proxies)
(the issue is exist for control plane v1.15.2)
```

### Additional Information

We define the `hpaSpec` in pilot iop, it works.

**Comment by cbl315** [comment]
And if I adopt the `metrics` definition to `autoscaling/v2`, it works:

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  components:
    ingressGateways:
    - enabled: true
      k8s:
        hpaSpec:
          maxReplicas: 10
          metrics:
          - resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 80
              # targetAverageUtilization: 80
            type: Resource
          minReplicas: 2
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: istio-ingressgateway
      name: istio-ingressgateway-1
      namespace: istio-ingress
```
