### ISSUE TITLE
how to return x-request-id to client or web?

### ISSUE THREAD

**Issue by ggjjlldd** [istio/istio#41638]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
how to return x-request-id to client or web?
**Describe alternatives you've considered**
return istio add header x-request-id to client, so i can search logs.
**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ x] Networking
[ x] Performance and Scalability
[x ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[x ] Multi Cluster
[x ] Virtual Machine
[ x] Multi Control Plane

**Additional context**

**Comment by zengyuxing007** [comment]
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: responsed-x-request-id-always
  namespace: istio-system
spec:
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: ANY
        listener:
          filterChain:
            filter:
              name: envoy.http_connection_manager
      patch:
        operation: MERGE
        value:
          typed_config:
            '@type': >-
              type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            always_set_request_id_in_response: true
            generate_request_id: true
            preserve_external_request_id: true
  priority: 0

```

You can refer to this one.
