### ISSUE TITLE
feat: Istiod helm chart volume mount support

### ISSUE THREAD

**Issue by Pacobart** [istio/istio#41682]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

There is a use case to use cert-manager with istio to generate mTLS certificates. This requires us to add 2 mounts to the istiod deployment. Currently, tutorials online suggest using IstioOperator, which is now discouraged. We'd like have a parameter on the helm chart to pass the required volumes.

Usage:
```
spec:
  template:
    spec:
      containers:
      - name: discovery
        args:
        - --tlsCertFile=/etc/cert-manager/tls/tls.crt
        - --tlsKeyFile=/etc/cert-manager/tls/tls.key
        - --caCertFile=/etc/cert-manager/ca/root-cert.pem
        env:
        - name: ENABLE_CA_SERVER
          value: "false"
        volumeMounts:
        - mountPath: "/etc/cert-manager/tls"
          name: cert-manager
          readOnly: true
        - mountPath: "/etc/cert-manager/ca"
          name: ca-root-cert
          readOnly: true
      volumes:
      - name: cert-manager
        secret:
          secretName: istiod-tls
      - name: ca-root-cert
        configMap:
          defaultMode: 420
          name: istio-ca-root-cert
```

**Describe alternatives you've considered**

Currently I'm using kubectl patch to add the above configuration. This is sketchy and not recommended for production environments.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

https://github.com/istio/istio/tree/1.15.0/manifests/charts/istio-control/istio-discovery
