### ISSUE TITLE
AuthorizationPolicy problem

### ISSUE THREAD

**Issue by mark8s** [istio/istio#41690]
Hi everyone, I have a question about requesting authentication.

That's it, I now have a requirement like this: I have two services, let's call them A and B first. A needs to use gateway to access B, and I want to restrict only A service to access B service? what should I do? Both A and B services have sidecar injected.

In the beginning, I wanted to set the AuthorizationPolicy from.source.principals for the B service using something like this:

```shell
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: b
spec:
 selector:
   matchLabels:
     app: b
 action: ALLOW
 rules:
 - from:
   - source:
       principals: ["cluster.local/ns/default/sa/a"]
```

But I found that it doesn't seem to take effect, and an error will be reported:

```shell
rpc error: code = PermissionDenied desc = RBAC: access denied
````

I guess it is because A goes through the istio ingress-gateway when accessing B, which seems to cause the B service to not recognize source.principals.

I don't know what to do now? Can you guys help me?

**Comment by ymesika** [comment]
If I understand you correctly in your case the traffic to B is coming from the ingress gateway.
So my guess is that you need to allow the A principal on the ingress gateway and ingress gateway prinicipal (something like `principals: ["cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"]` on B.
This is assuming that you want strict policies that only allows this path.

**Comment by mark8s** [comment]
@ymesika   Thanks for your reply~

Is that what you said?

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: b
spec:
 selector:
   matchLabels:
     app: b
 action: ALLOW
 rules:
 - from:
   - source:
       principals: ["cluster.local/ns/default/sa/a"]
  - source:
       principals: ["cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"]
```
