### ISSUE TITLE
after nginx reset Host Header, the VirtualService rule will be failure

### ISSUE THREAD

**Issue by wang-xiaowu** [istio/istio#41709]
### Bug Description

```nginx
server {
    listen       80;
    listen  [::]:80;
    server_name  _;
    proxy_set_header Host $http_host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Scheme $scheme;
    proxy_set_header X-Forwarded-Host $server_name;
    proxy_http_version 1.1;
    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        #root   /usr/share/nginx/html;
        #index  index.html index.htm;
        proxy_pass http://testaaa:31000;
    }
    location /baidu {
        #root   /usr/share/nginx/html;
        #index  index.html index.htm;
        proxy_pass http://www.baidu.com/;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
```
this is my nginx config

and when i try to curl nginx with header-a, i wish it can be routing to testaaa's header-a version

but it did not work

when i delete this row `proxy_set_header Host $http_host;`, it worked, i think It's chaotic with the VirtualService's hosts column, but i need this row, so how can i figure this out

### Version

```prose
istio version: 1.14.1

Client Version: v1.24.4+k3s1
Kustomize Version: v4.5.4
Server Version: v1.24.4+k3s1
```

**Comment by escoffier** [comment]
What's the problem with virtualservice?

**Comment by wang-xiaowu** [comment]
> What's the problem with virtualservice?

i did `proxy_set_header Host $http_host;` in my nginx, it effect the virtualservice router

this is my virtual service
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: api-open-service
  namespace: sopei-biz
spec:
  hosts:
  - api-open-service.sopei-biz.svc.cluster.local
  http:
  - match:
    - headers:
        project-version:
          exact: master
    route:
    - destination:
        host: api-open-service.sopei-biz.svc.cluster.local
        subset: master
  - route:
    - destination:
        host: api-open-service.sopei-biz.svc.cluster.local
        subset: master
```

so my question is, what can i do if i dont want to change my Host header
