### ISSUE TITLE
Make a distinction between the feature of transparent interception and the interception method of iptables TPROXY

### ISSUE THREAD

**Issue by chrysan55** [istio/istio#41731]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

**Describe alternatives you've considered**

From the [doc of MeshConfig.ProxyConfig.InboundInterceptionMode](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig-InboundInterceptionMode) it says

> The REDIRECT mode uses iptables REDIRECT to NAT and redirect to Envoy. This mode loses source IP addresses during redirection.

> The TPROXY mode uses iptables TPROXY to redirect to Envoy. This mode preserves both the source and destination IP addresses and ports, so that they can be used for advanced filtering and manipulation. 

But I think iptables TPROXY target is not a necessary condition of transparent interception which is implemented by socket option SO_ORIGINAL_DST and IP_FREEBIND in Envoy. In another word, transparent interception is possible when we use iptables REDIRECT target.

My proposal is adding an individual configuration item such as `bool InboundTransparentInterception` to tell Envoy whether or not enable original_src feature. If `InboundTransparentInterception` is true, no matter interception mode is TPROXY or REDIRECT, upstream replying packets should be rerouted as what we do now for TPROXY mode.

Since it's a little destructive that the underlying meaning of current TPROXY InterceptionMode would be lost, I'm seeking for opinions on this idea. If we could reach an agreement, I will work on this.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
Can you show how to do it? My understanding is it isn't possible. Happy to be proven wrong

**Comment by chrysan55** [comment]
@howardjohn  Thanks for your comment !

I'm trying to build a example setup. Hopefully it helps to explain this idea.

Here is the docker compose configuration
```yaml
version: "3.8"
services:
  upstream-server:
    image: nginx:latest
    privileged: true
    volumes:
      - ./nginx-echo-client.conf:/etc/nginx/conf.d/echo-client.conf
    ports:
      - "54321:8080"
      - "9901:9901"
  envoy:
    image: envoyproxy/envoy-dev:latest
    privileged: true
    user: root:envoy
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./transparent-envoy.yaml:/etc/transparent-envoy.yaml
    network_mode: service:upstream-server
    environment:
      ENVOY_UID: 0
    command: ["-c", "/etc/transparent-envoy.yaml", "--service-cluster", "echo", "--log-level", "debug"]
  init:
    image: linuxkit/ip:6cc44dd4e18ddb02de01bc4b34b5799971b6a7bf
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./redirect.rules:/redirect.rules
    command: bash -c "iptables-legacy-restore < /redirect.rules && ip route add local 0.0.0.0/0 dev lo table 100 && ip rule add fwmark 1337 lookup 100"
    network_mode: service:upstream-server
  tcpdump:
    image: corfr/tcpdump:latest
    network_mode: service:upstream-server
```

Basiclly it's a inbound redirect scenario including only a upstream and a virtual inbound listener.

There is a simple nginx server which echoes request's source address, destination address and x-forward-to header, with conf as nginx-echo-client.conf
```
server {
        listen       8080;
        server_name  localhost;
        location = /echo {
          default_type text/plain;
          return 200 'FROM $remote_addr
TO $server_addr
X-FORWARD-FOR: $http_x_forwarded_for
';
        }
}
```

There is a simple virtual inbound listener with an additional original_src filter, conf as transparent-envoy.yaml
```yaml
static_resources:
  clusters:
  - name: upstream
    connect_timeout: 10s
    lb_policy: CLUSTER_PROVIDED
    type: ORIGINAL_DST
  listeners:
  - address:
      socketAddress:
        address: 0.0.0.0
        portValue: 15006
    filterChains:
    name: virtualInbound
    trafficDirection: INBOUND
    filterChains:
    - filterChainMatch:
        destinationPort: 8080
        transportProtocol: raw_buffer
      filters:
        #- name: istio.metadata_exchange
        #typedConfig:
        #  '@type': type.googleapis.com/envoy.tcp.metadataexchange.config.MetadataExchange
        #  protocol: istio-peer-exchange
      - name: envoy.filters.network.http_connection_manager
        typedConfig:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          use_remote_address: true
          skip_xff_append: false
          httpFilters:
          - name: envoy.filters.http.router
            typedConfig:
              '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          routeConfig:
            name: local-upstream
            validateClusters: false
            virtualHosts:
            - domains:
              - '*'
              name: local-upstream
              routes:
              - match:
                  prefix: /
                route:
                  cluster: upstream
          statPrefix: upstream_inbound
    listenerFilters:
    - name: envoy.filters.listener.original_dst
      typedConfig:
        '@type': type.googleapis.com/envoy.extensions.filters.listener.original_dst.v3.OriginalDst
    - name: envoy.filters.listener.original_src
      typedConfig:
        '@type': type.googleapis.com/envoy.extensions.filters.listener.original_src.v3.OriginalSrc
        mark: 1337
admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901
```

Finally set the REDIRECT iptables rules, coupled with necessary transparent routes (from [envoy doc](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/listener_filters/original_src_filter#extra-setup)) as redirect.rules
```
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:ISTIO_INBOUND - [0:0]
:ISTIO_IN_REDIRECT - [0:0]
:ISTIO_OUTPUT - [0:0]
:ISTIO_REDIRECT - [0:0]

-A PREROUTING -p tcp -j ISTIO_INBOUND
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp -m tcp --dport 15008 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A ISTIO_OUTPUT -s 127.0.0.6/32 -o lo -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 0 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 101 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
COMMIT

*mangle
# envoy -> upstream packets, save mark for reply packets
-A PREROUTING -i lo -p tcp -m mark --mark 1337 -j CONNMARK --save-mark
# upstream -> envoy packets, set mark for rerouting to loopback
-A OUTPUT -m connmark --mark 1337 -j CONNMARK --restore-mark
COMMIT
```

Then I docker-compose up and curl the exposed service port. The upstream returns the real client address (docker NATed gateway) instead of the local address (192.168.0.2). 
```bash
~/repo/istio/origsrc-example# docker-compose up -d
[+] Running 5/5
 ⠿ Network origsrc-example_default              Created                                                                                                                           0.1s
 ⠿ Container origsrc-example-upstream-server-1  Started                                                                                                                           0.5s
 ⠿ Container origsrc-example-envoy-1            Started                                                                                                                           0.6s
 ⠿ Container origsrc-example-init-1             Started                                                                                                                           0.6s
 ⠿ Container origsrc-example-tcpdump-1          Started                                                                                                                           0.9s
~/repo/istio/origsrc-example# curl http://localhost:54321/echo
FROM 192.168.0.1
TO 192.168.0.2
X-FORWARD-FOR: 192.168.0.1
```

There is nothing to do with iptables TPROXY target, but we still get the real client IP.
