### ISSUE TITLE
ExtAuthzPerRoute disable doesn't work on 1.15.2

### ISSUE THREAD

**Issue by Titof974** [istio/istio#41741]
### Bug Description

I decided to upgrade my istio 1.11.4 to 1.15.2 and now it doesn't take into account my ExtAuthzPerRoute filter.

I'm using an external auth with an envoy filter and I'm using the ExtAuthzPerRoute filter to exclude some virtualservices. It works without any problems on istio 1.11.4 but not in 1.15.2. 
External authentication still works but I can't exclude virtual services anymore.

My istio is not running in istio-system it's installed in another namespace leaf-service-mesh.

There are not errors in istio log.
```
2022-11-02T17:09:16.114655Z     info    ads     Push debounce stable[239] 1 for config EnvoyFilter/leaf-service-mesh/knight-bypass-auth: 100.801194ms since last change, 100.800994ms since last push, full=true
```

External Auth Filter:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: knight-auth-filter
  namespace: leaf-service-mesh
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.ext_authz
          typed_config:
            '@type': >-
              type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
            http_service:
              authorizationRequest:
                allowedHeaders:
                  patterns:
                    - exact: accept
                    - exact: authorization
                    - exact: cookie
                    - exact: from
                    - exact: proxy-authorization
                    - exact: user-agent
                    - exact: x-forwarded-access-token
                    - exact: x-forwarded-email
                    - exact: x-forwarded-for
                    - exact: x-forwarded-client-cert
                    - exact: x-forwarded-host
                    - exact: x-forwarded-proto
                    - exact: x-forwarded-user
                    - prefix: x-auth-request
                    - prefix: x-forwarded
                headersToAdd:
                  - key: x-knight-path
                    value: '%REQ(:PATH)%'
                  - key: x-knight-cert
                    value: '%DOWNSTREAM_PEER_CERT%'
              authorizationResponse:
                allowedClientHeaders:
                  patterns:
                    - exact: authorization
                    - exact: location
                    - exact: proxy-authenticate
                    - exact: set-cookie
                    - exact: www-authenticate
                    - prefix: x-auth-request
                    - prefix: x-forwarded
                allowedUpstreamHeaders:
                  patterns:
                    - exact: authorization
                    - exact: location
                    - exact: proxy-authenticate
                    - exact: set-cookie
                    - exact: www-authenticate
                    - prefix: x-auth-request
                    - prefix: x-forwarded
              server_uri:
                cluster: >-
                  outbound|3001||knight.leaf-authentication.svc.cluster.local
                timeout: 1.5s
                uri: http://knight.leaf-authentication.svc.cluster.local:3001/
            include_peer_certificate: true
  workloadSelector:
    labels:
      istio: ingressgateway
```

The ExtAuthzPerRoute filter:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: knight-bypass-auth
  namespace: leaf-service-mesh
spec:
  configPatches:
    - applyTo: HTTP_ROUTE
      match:
        routeConfiguration:
          vhost:
            route:
              name: leaf-keycloak-route
      patch:
        operation: MERGE
        value:
          name: envoy.ext_authz_disabled
          typed_per_filter_config:
            envoy.ext_authz:
              '@type': >-
                type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute
              disabled: true
  workloadSelector:
    labels:
      istio: ingressgateway
```

My virtualservice:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: leaf-gw-keycloak-vs
  namespace: leaf-authentication
spec:
  gateways:
    - leaf-service-mesh/leaf-gateway
  hosts:
    - '*'
  http:
    - match:
        - uri:
            exact: /security
        - uri:
            exact: /security/
      name: leaf-keycloak-route-redirect
      redirect:
        uri: /security/auth
    - headers:
        response:
          add:
            content-security-policy: >-
              frame-src self https://10.247.32.128; frame-ancestors self
              https://10.247.32.128; object-src none;
          remove:
            - content-security-policy
      match:
        - uri:
            prefix: /security
      name: leaf-keycloak-route
      route:
        - destination:
            host: leaf-keycloak-http.leaf-authentication.svc.cluster.local
            port:
              number: 80
```

Has the filter changed or is it a bug?

### Version

```prose
$istioctl version --istioNamespace leaf-service-mesh
client version: 1.15.2
control plane version: 1.15.2
data plane version: 1.15.2 (15 proxies)

$kubectl version --short
Client Version: v1.22.3
Server Version: v1.20.5
```
