### ISSUE TITLE
upstream connect error or disconnect/reset before headers. reset reason: connection termination

### ISSUE THREAD

**Issue by wang-xiaowu** [istio/istio#41826]
### Bug Description

i did not use istio gateway
our server request link is: client -> server gateway(istio proxy) -> api server(istioproxy)
and this is my server gateway's service yaml

```yaml
apiVersion: v1
kind: Service
metadata:
  name: orange-gateway-a
spec:
  ports:
  - appProtocol: HTTP
    name: http-web
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80
  - appProtocol: HTTP
    name: http-api
    nodePort: 30077
    port: 7777
    protocol: TCP
    targetPort: 7777
  - appProtocol: HTTP
    name: http-admin
    nodePort: 30099
    port: 9999
    protocol: TCP
    targetPort: 9999
  selector:
    app: orange-gateway-a
  type: NodePort
```

this is api server's DR yaml
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: api-wechat
  namespace: sopei-biz
spec:
  hosts:
  - api-wechat.sopei-biz.svc.cluster.local
  http:
  - route:
    - destination:
        host: api-wechat.sopei-biz.svc.cluster.local
        subset: master
```

this is api server's VS yaml
```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: api-wechat
  namespace: sopei-biz
spec:
  host: api-wechat.sopei-biz.svc.cluster.local
  subsets:
  - labels:
      version: master
    name: master
```

WHEN i visit the api server, it shows `upstream connect error or disconnect/reset before headers. reset reason: connection termination`

### Version

```prose
istio
client version: 1.16.0
control plane version: 1.14.1
data plane version: 1.14.1 (124 proxies)

k8s
Client Version: v1.24.4+k3s1
Kustomize Version: v4.5.4
Server Version: v1.24.4+k3s1
```
