### ISSUE TITLE
Datadog tracing bad host header

### ISSUE THREAD

**Issue by melchiormoulin** [istio/istio#41829]
### Bug Description

Hello we are using the telemetry CRD with the extensionProvider Datadog. 
From mesh config : 
```
    extensionProviders:
    - name: datadog
      datadog:
        service: datadog-agent.sre.svc.cluster.local
        port: 8126
```
When istio proxy is sending traces to datadog agent : 
The host header is set to  the cluster name `outbound|8126||datadog-agent.sre.svc.cluster.local`
The datadog agent respond a `400` Http response code with ` Bad Request: malformed Host heade`r

### Version

```prose
istioctl version
client version: 1.15.3
control plane version: 1.15.3
data plane version: 1.15.3 (123 proxies)

kubectl version --short
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.24.3-gke.2100

helm version --short 
v3.2.4+g0ad800e
```
