### ISSUE TITLE
[Documentation] TUNNEL 

### ISSUE THREAD

**Issue by sedflix** [istio/istio#41854]
**Describe the feature request**

This is a request for user/usage documentation for the new TUNNEL feature introduced in the istio.  

**Describe alternatives you've considered**
I've tried going through https://docs.google.com/document/d/1QbjsBwM0QyQxJIs2LJBUvITap2QeqOKmsHQrGFK9lWQ/edit?usp=sharing and https://github.com/istio/istio/blob/1aca7a67afd7b3e1d24fafb2fbfbeaf1e41534c0/tests/integration/pilot/testdata/tunneling/ but as noob it's really hard to understand how things are working or make it work. 

We can maybe add a section in https://istio.io/latest/docs/tasks/traffic-management/egress/http-proxy/

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by sedflix** [comment]
Thanks a ton, @jewertow for adding this feature. 
(Tagging him for more visibility)

**Comment by jewertow** [comment]
Hey, this documentation is on my todo list and I was going to do it, but this solution has some limitations and flaws. I was working recently on an [RFC](https://docs.google.com/document/d/1y_mYuB9dUoErhUjJD2EaQauDjfevIA8N) that addresses all these issues, so I was not sure whether it's worth to document it now or later.
But on the other hand, it may take long time until the RFC will be implemented, so it makes sense to not wait for it. I will submit a PR next week.

**Comment by shibin-george** [comment]
Hi @jewertow, I have a query about the feature which I haven't yet figured out an answer to:
My use-case is:
- applications should not be aware of the forward-proxy's IP/port and should continue to send HTTP/HTTPS requests business as usual
  - However, they can choose to force a request through a proxy using a header (say: `X-PROXY-THIS`)
- The istio sidecar, intercepts all outbound requests
  - If `X-PROXY-THIS` exists, there should be HTTP CONNECT to the forward-proxy, and the rest of HTTP/S payload should be tunneled to the destination, via the proxy.
  - If `X-PROXY-THIS` doesn't exist, egress should use the default way of egress (PassthroughCluster I guess)
- The other thing is there's no known list of destination server-names (like *.cnn.com, *.google.com, etc). The application, based on some business logic, can choose to proxy requests to any random server, or not proxy.

Is it feasible to implement this solution using the TUNNEL feature in istio?

PS: It has been great learning experience reading through your Github issues, samples, and RFCs, especially: [this ](https://github.com/envoyproxy/envoy/issues/19612), [this](https://docs.google.com/document/d/1QbjsBwM0QyQxJIs2LJBUvITap2QeqOKmsHQrGFK9lWQ/edit) and [this](https://github.com/jewertow/istio-playground/tree/samples-for-rfc)!

**Comment by jewertow** [comment]
Hi @shibin-george!

I'm sorry for the late reply. I'm glad to see that my issues and notes were helpful.

I think that you should be able to force tunneling when a particular header is sent, however it will be only possible with an egress gateway. Why? To make a header-based routing, you need a VirtualService with an HTTP route, but DestinationRule with tunnel settings can be only applied to TCP or TLS services. To avoid this limitation, you need an egress gateway that will expose TCP/TLS port and tunnel received traffic. A quick prototype (I didn't test it):
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: tls
      protocol: TLS
    hosts:
    - www.google.com
    tls:
      mode: PASSTHROUGH
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: force-tunneling-mesh
spec:
  hosts:
  - www.google.com
  gateways:
  - mesh
  http:
  - match:
    - header:
        exact: "X-PROXY-THIS"
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: originate-tls-to-google-com
        port:
          number: 443
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-tls-to-google-com
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: originate-tls-to-google-com
    trafficPolicy:
      tls:
        mode: SIMPLE
        sni: www.google.com
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: force-tunneling-mesh
spec:
  hosts:
  - www.google.com
  gateways:
  - istio-egressgateway
  tls:
  - match:
    - sniHosts:
      - www.google.com
    route:
    - destination:
        host: connect-proxy.net
        subset: tunnel-traffic-to-google-com
        port:
          number: 3128
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-tls-to-connect-proxy-and-tunnel-traffic-to-google-com
spec:
  host: connect-proxy.net
  trafficPolicy:
    tls:
      mode: SIMPLE
      sni: connect-proxy.net
  subsets:
  - name: tunnel-traffic-to-google-com
    trafficPolicy:
      tunnel:
        targetHost: www.google.com
        targetPort: 443
```

If it comes to the last question - it's not possible. If Istio supported command operator `%REQUESTED_SERVER_NAME%`, then your case could probably work. I filed an [issue](https://github.com/istio/istio/issues/41342) to support this option, but first I have to change implementation of tunneling to use an internal listener or implement my RFC that I mentioned in the previous comment. Currently to enable tunneling, you have to define a destination rule with subsets for every target host. You could achieve all your goals with EnvoyFilter, but it's inconvenient to use and difficult to maintain.
