### ISSUE TITLE
istiod push a http2 inbound cluster to http service

### ISSUE THREAD

**Issue by holooooo** [istio/istio#41909]
### Bug Description

Sometime we can find 502 UPE in cluster.And we find inbound cluster has a little bit wrong with what we expect.
What we expect:
```
  - cluster:
      '@type': type.googleapis.com/envoy.config.cluster.v3.Cluster
      metadata:
        filter_metadata:
          istio:
            services:
            - host: a.a
              name: a
              namespace: a
      name: inbound|9999||
      type: ORIGINAL_DST
```
What we got:
```
  - cluster:
      '@type': type.googleapis.com/envoy.config.cluster.v3.Cluster
      metadata:
        filter_metadata:
          istio:
            services:
            - host: b.b
              name: b
              namespace: b
      name: inbound|9999||
      type: ORIGINAL_DST
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http2_protocol_options:
              max_concurrent_streams: 1073741824
```
It looks like it use a same port but different protocol instance for cluster build.
https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/cluster.go#L551

### Version

```prose
istio 1.11.8
```
