### ISSUE TITLE
TLS termination not working in 443 port kubernetes application

### ISSUE THREAD

**Issue by shakunt1202** [istio/istio#41913]
### Bug Description

I am working on Istio gateways and I am facing an issue.
The issue is when we are exposing the Kubernetes application on the 443 port, it is running fine on the node port as well as the traditional ingress but when we switched to Istio gateways, only the passthrough TLS mode was allowing the traffic and other modes like SIMPLE, MUTUAL, ISTIO_MUTUAL throwing errors like:- 
![thumbnail_image](https://user-images.githubusercontent.com/67914403/201013681-f5565fb7-9366-4103-84be-b80429f9af89.png)
and sometimes it is throwing 
![image](https://user-images.githubusercontent.com/67914403/201013776-4f79b858-4180-437e-a924-f064ceabd4b7.png)
while trying different ways.
I am sharing the gateway and virtual service files I have used.
Gateways:-
![image](https://user-images.githubusercontent.com/67914403/201014279-b0c384d6-9730-40bd-9331-97d948442059.png)

Virtual Service:- 
![image](https://user-images.githubusercontent.com/67914403/201019187-33d3bea8-d251-469e-967e-1a76b76ab346.png)

### Version

```prose
$ istioctl version
client version: 1.14.1
control plane version: 1.14.1
data plane version: 1.15.0 (2 proxies), 1.14.1 (8 proxies)
$ kubectl version --short
Client Version: v1.22.6
Server Version: v1.20.11
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1
```

**Comment by eigokor** [comment]
If you test-app listens on TLS you have to add DestinationRule that will instruct mesh to initiate TLS connection to your app

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: originate-tls-for-test-app
  namespace: test
spec:
  host: test-app.test.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE
```
