### ISSUE TITLE
Connections not recreated when a custom certificate is renewed

### ISSUE THREAD

**Issue by SantiMunoz** [istio/istio#41924]
### Bug Description

Hello,

**TL.TR**
We use a custom certificate that we load to the istio-proxy through a volume. The problem we are facing is that when this certificate gets renewed, the istio-proxy correctly updates it in its container, and new connexions from the app is correctly using it, but the problem is with the open old HTTP connections from the app, that are using the old certificate and start failing when the certificate expires. 

What we would like to know if the istio-proxy can update the cert used by these old-open connections of the services, similar on what it does for the certificate used in the mTLS between proxies.

**Full context**
We currently have the applications initiating the traffic using HTTPS instead of HTTP, and in order to make that work with Istio we created an EnvoyFilter that adds a listener in the istio-proxy for egress traffic on port 443 to terminate the TLS, so then the istio-proxy can start the mTLS between the services.

appA--https://appB.default-->EnvoyFilter in the istio-proxy terminates tls | istio-proxy of appA initiates mTLS --> istio-proxy off appB-->appB

This is the EnvoyFilter we use:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: appB-envoy-filter
  namespace: istio-system # root namesapce, this will be accessible from all namespaces
spec:
  workloadSelector:
    labels:
      serviceMeshResource: "true"
      app.kubernetes.io/component: microservice
  configPatches:
    - applyTo: FILTER_CHAIN
      match:
        context: SIDECAR_OUTBOUND
        listener:
          portNumber: 443
          filterChain:
            sni: appB.default
      patch:
        operation: MERGE
        value:
          transport_socket:
            name: "envoy.transport_sockets.tls"
            typed_config:
              "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext"
              common_tls_context:
                tls_certificates:
                  - certificate_chain:
                      filename: /etc/certs/custom-cert/tls.crt
                    private_key:
                      filename: /etc/certs/custom-cert/tls.key
                validation_context:
                  trusted_ca:
                    filename: /etc/certs/ca/ca.crt
```

And they way we inject this cert to the istio-proxy is through the following annotations:
```
sidecar.istio.io/userVolumeMount: '[{"name":"custom-cert", "mountPath":"/etc/certs/custom-cert", "readonly":true},{"name":"root-ca", "mountPath":"/etc/certs/ca", "readonly":true}]'
sidecar.istio.io/userVolume: '[{"name":"custom-cert", "secret":{"secretName":"custom-cert"}},{"name":"root-ca", "secret":{"secretName":"{{ include "microservice.caSecretName" . }}"}}]'
```

We thought it was related to this https://github.com/istio/istio/pull/40137, but after testing the release v1.16.0-rc.0 was able to reproduce the issue again.
Is there a way to make the istio-proxy force the recreation of the service connections when this custom certificate is renewed? 

Thnaks!

### Version

```prose
✗ istioctl version
client version: 1.14.1
control plane version: 1.14.1

and 

✗ istioctl version
client version: 1.14.1
control plane version: 1.16.0
```
