### ISSUE TITLE
istio config map looks weird but seems to work...

### ISSUE THREAD

**Issue by ceastman-r7** [istio/istio#41933]
### Bug Description

here is a snippet of the values.yaml that is used to do a helm install of istiod:
```
meshConfig:
  enableAutoMtls: true
  extensionProviders:
  - name: locallog
    envoyFileAccessLog:
      logFormat:
        labels:
          authority: '%REQ(:AUTHORITY)%'
          bytes_received: '%BYTES_RECEIVED%'
          bytes_sent: '%BYTES_SENT%'
          connection_termination_details: '%CONNECTION_TERMINATION_DETAILS%'
          downstream_local_address: '%DOWNSTREAM_LOCAL_ADDRESS%'
          downstream_remote_address: '%DOWNSTREAM_REMOTE_ADDRESS%'
          duration: '%DURATION%'
          method: '%REQ(:METHOD)%'
          path: '%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%'
          protocol: '%PROTOCOL%'
          request_duration: '%REQUEST_DURATION%'
          request_id: '%REQ(X-REQUEST-ID)%'
          requested_server_name: '%REQUESTED_SERVER_NAME%'
          response_code: '%RESPONSE_CODE%'
          response_code_details: '%RESPONSE_CODE_DETAILS%'
          response_duration: '%RESPONSE_DURATION%'
          response_flags: '%RESPONSE_FLAGS%'
          response_tx_duration: '%RESPONSE_TX_DURATION%'
          start_time: '%START_TIME%'
          upstream_cluster: '%UPSTREAM_CLUSTER%'
          upstream_host: '%UPSTREAM_HOST%'
          upstream_local_address: '%UPSTREAM_LOCAL_ADDRESS%'
          upstream_transport_failure_reason: '%UPSTREAM_TRANSPORT_FAILURE_REASON%'
          user_agent: '%REQ(USER-AGENT)%'
          x_forwarded_for: '%REQ(X-FORWARDED-FOR)%'
  - name: localtrace
    zipkin:
      maxTagLength: 256
      port: 9411
      service: istio-jaeger-collector.istio-addons.svc.cluster.local
```

but the config map looks weird
kubectl get cm istio -n istio-system -o yaml

```
apiVersion: v1
data:
  mesh: |-
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
    enableAutoMtls: true
    enablePrometheusMerge: true
    extensionProviders:
    - envoyFileAccessLog:
        logFormat:
          labels:
            authority: '%REQ(:AUTHORITY)%'
            bytes_received: '%BYTES_RECEIVED%'
            bytes_sent: '%BYTES_SENT%'
            connection_termination_details: '%CONNECTION_TERMINATION_DETAILS%'
            downstream_local_address: '%DOWNSTREAM_LOCAL_ADDRESS%'
            downstream_remote_address: '%DOWNSTREAM_REMOTE_ADDRESS%'
            duration: '%DURATION%'
            method: '%REQ(:METHOD)%'
            path: '%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%'
            protocol: '%PROTOCOL%'
            request_duration: '%REQUEST_DURATION%'
            request_id: '%REQ(X-REQUEST-ID)%'
            requested_server_name: '%REQUESTED_SERVER_NAME%'
            response_code: '%RESPONSE_CODE%'
            response_code_details: '%RESPONSE_CODE_DETAILS%'
            response_duration: '%RESPONSE_DURATION%'
            response_flags: '%RESPONSE_FLAGS%'
            response_tx_duration: '%RESPONSE_TX_DURATION%'
            start_time: '%START_TIME%'
            upstream_cluster: '%UPSTREAM_CLUSTER%'
            upstream_host: '%UPSTREAM_HOST%'
            upstream_local_address: '%UPSTREAM_LOCAL_ADDRESS%'
            upstream_transport_failure_reason: '%UPSTREAM_TRANSPORT_FAILURE_REASON%'
            user_agent: '%REQ(USER-AGENT)%'
            x_forwarded_for: '%REQ(X-FORWARDED-FOR)%'
      name: locallog
    - name: localtrace
      zipkin:
        maxTagLength: 256
        port: 9411
        service: istio-jaeger-collector.istio-addons.svc.cluster.local
```

### Version

```prose
istioctl version
client version: 1.14.1
control plane version: 1.14.4
data plane version: 1.14.5 (107 proxies), 1.14.4 (2 proxies)

kubectl version --short
Client Version: v1.22.15
Server Version: v1.22.15-eks-fb459a0

helm version --short
v3.10.0+gce66412
```
