### ISSUE TITLE
Traffic forwarded to only one backend service inspite of having different hosts and targets in virtual services

### ISSUE THREAD

**Issue by rishabhgargg** [istio/istio#41943]
Issue : 

I have two k8s services"neo4j-standalone.namespace1.svc.cluster.local" and "headless-neo4j.namespace2.svc.cluster.local".
I am using istio-ingress gateway to access the UI on https and logging inside that on tcp, based on two different hostnames "subDomain1-neo4j.domain.com" and "subDomain2-neo4j.domain.com" respectively.

While trying to hit from gateway, TCP traffic is forwarded to only one k8s service (whichever is applied first).

Expectation: Based on hostname, while trying to login, my TCP should also get forwarded to respective destination host based on rules written in virtual services.

Gateway YAML
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: istio-ingress-credential
    hosts:
    - subDomain1-neo4j.domain.com
    - subDomain2-neo4j.domain.com
  - port:
      number: 7474
      name: neo4j
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: istio-ingress-credential
    hosts:
    - subDomain1-neo4j.domain.com
    - subDomain2-neo4j.domain.com
  - port:
      number: 7687
      name: bolt
      protocol: tcp
    hosts:
    - subDomain1-neo4j.domain.com
    - subDomain2-neo4j.domain.com
```

VirtualService 1 YAML
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: neo4j-namespace1
spec:
  gateways:
  - istio-gateway
  hosts:
  - "subDomain1-neo4j.domain.com"
  http:
  - match:
    - port: 7474
    route:
    - destination:
        host: neo4j-standalone.namespace1.svc.cluster.local
        port:
          number: 7474
  tcp:
  - match:
    - port: 7687
    route:
    - destination:
        host: neo4j-standalone.namespace1.svc.cluster.local
        port:
          number: 7687
```

VirtualService 2 YAML
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: neo4j-namespace2
spec:
  hosts:
  - "subDomain2-neo4j.domain.com"
  gateways:
  - istio-gateway
  http:
  - match:
    - port: 7474
    route:
    - destination:
        host: headless-neo4j.namespace2.svc.cluster.local
        port:
          number: 7474
  tcp:
  - match:
    - port: 7687
    route:
    - destination:
        host: headless-neo4j.namespace2.svc.cluster.local
        port:
          number: 7687
```

@howardjohn Would appreciate your help on this one. Thanks.
