### ISSUE TITLE
gateway-api: httproute without backendRefs generates invalid virtualservice

### ISSUE THREAD

**Issue by frankbu** [istio/istio#41965]
### Bug Description

The gateway-api conversion code adds an abort fault when an httproute has no backendRefs:

https://github.com/istio/istio/blob/8538a957dc3d86f985f57434bf69b8d7afecb0bd/pilot/pkg/config/kube/gateway/conversion.go#L352

The result is a virtualservice with no routes, which is invalid.

For example, this httproute:
```
kubectl apply -f - <<EOF
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: httpbin
spec:
  parentRefs:
  - kind: Service
    name: httpbin
    port: 8000
  rules:
  - filters:
    - type: RequestMirror
      requestMirror:
        backendRef:
          name: httpbin-v2
          port: 80
EOF
```

generates this vs:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-0-istio-autogenerated-k8s-gateway
  namespace: default
  creationTimestamp: '2022-11-11T20:34:45Z'
  annotations:
    internal.istio.io/parents: HTTPRoute/httpbin.default
    internal.istio.io/route-semantics: gateway
spec:
  gateways:
  - mesh
  hosts:
  - httpbin.default.svc.cluster.local
  http:
  - fault:
      abort:
        httpStatus: 503
        percentage:
          value: 100
    match:
      - uri:
          prefix: /
    mirror:
      host: httpbin-v2.default.svc.cluster.local
      port:
        number: 80
```

The httproute's status field does not indicate any errors, but the underlying virtualservice causes bad envoy config and produces errors in the istio-proxy logs.

Manually applying the bad virtual service produces the following error:
```
$ k apply -f /tmp/badvs.yaml
Error from server: error when creating "/tmp/junk.yaml": admission webhook "validation.istio.io" denied the request: configuration is invalid: HTTP route, redirect or direct_response is required
```

### Version

```prose
latest
```

**Comment by frankbu** [comment]
Maybe instead of adding abort fault, should be adding directResponse?
```
spec:
  gateways:
  - mesh
  hosts:
  - httpbin.default.svc.cluster.local
  http:
  - directResponse:
      status: 503
    match:
      - uri:
          prefix: /
    mirror:
      host: httpbin-v2.default.svc.cluster.local
      port:
        number: 80
```
