### ISSUE TITLE
Help requested - Telemetry logging filters

### ISSUE THREAD

**Issue by ceastman-r7** [istio/istio#41964]
### Bug Description

Need help creating an expression for the telemetry access log filter to accomplish the following:

response_code >= 400
or
upstream_cluster = BlackHoleCluster
or
upstream_cluster = PassthroughCluster

### Version

```prose
istioctl version       
client version: 1.14.1
control plane version: 1.14.4

kubectl version --short
Client Version: v1.22.15
Server Version: v1.22.15-eks-fb459a0
```

**Comment by zirain** [comment]
```yaml
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: response-code
  namespace: istio-system
spec:
  accessLogging:
  - providers:
    - name: envoy
    filter: 
      expression: response.code >= 400
```
