### ISSUE TITLE
Validate route for every match defined in VirtualService

### ISSUE THREAD

**Issue by reddymh** [istio/istio#41980]
### Bug Description

Currently virtual service without route for match is getting created without any validation error but in the istiod log we are seeing validation error and getting all virtual services 404 not found error.

**vs.yaml:**

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-vs
spec:
  hosts:
    - "*.hello.test.com"
    - searchapi.search.svc.cluster.local
  gateways:
    - istio-gateway.default.svc.cluster.local
    - mesh
  http:
    - match:
      - uri:
           prefix: /m1
    - match:
      - uri:
          prefix: /m2
      route:
      - destination:
          host: nginx
          port:
            number: 80
```

**Validation Error in Logs:**

2022-11-14T13:20:36.030943Z	info	ads	RDS: PUSH for node:fluentbit-fluent-bit-5vkv8.telemetry-ns resources:49 size:54.1kB cached:2/49
2022-11-14T13:20:36.031329Z	info	ads	RDS: PUSH for node:loggingfrontdoor-5d4b8bcb76-psbtv.telemetry-ns resources:49 size:54.1kB cached:0/49
2022-11-14T13:20:36.031422Z	info	ads	RDS: PUSH for node:fluentbit-fluent-bit-vgs4p.telemetry-ns resources:49 size:54.1kB cached:22/49
2022-11-14T13:20:36.056958Z	warn	ads	ADS:RDS: ACK ERROR fluentbit-fluent-bit-5vkv8.telemetry-ns-54 Internal:Proto **constraint validation failed (RouteConfigurationValidationError.VirtualHosts[5]: embedded message failed validation | caused by VirtualHostValidationError.Routes[0]: embedded message failed validation | caused by RouteValidationError.Route: embedded message failed validation | caused by RouteActionValidationError.WeightedClusters: embedded message failed validation | caused by WeightedClusterValidationError.Clusters: value must contain at least 1 item(s)): name: "80"**
virtual_hosts {

### Version

```prose
istio version: 1.14.1
GKE Version: 1.22
```

**Comment by reddymh** [comment]
virtual service with match but no route is defined causing all the virtual services throwing 404 error and there os no validatio for this

**Comment by dddddai** [comment]
I can't reproduce this, the validation is here
https://github.com/istio/istio/blob/1.14.1/pkg/config/validation/virtualservice.go#L254

**Comment by reddymh** [comment]
@dddddai  I am able to create the below virtual service without any validatio error but in the log file I am seeing the validation errors.
istio ValidatingWebhookConfiguration should not allow to create the virtual service object ad throw the validation error which is not happening and able to the validation error log after creation which is blocking all the virtualservice with 404 error.

**Contents of test-vs.yaml**

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: search-api-virtualservice-test
  namespace: search
spec:
  hosts:
    - "*.carbon.lowes.com"
    - searchapi.search.svc.cluster.local
  gateways:
    - istio-gateway.default.svc.cluster.local
    - mesh
  http:
    - match:
      - uri:
           prefix: /m1
    - match:
      - uri:
          prefix: /m2
      route:
      - destination:
          host: nginx
          port:
            number: 80
```

**Execution:**

kubectl create -f test-vs.yaml 
virtualservice.networking.istio.io/search-api-virtualservice-test created

**Istiod Error Log:**

        retry_host_predicate {
          name: "envoy.retry_host_p...(truncated)
2022-11-15T09:13:59.745930Z	warn	ads	ADS:RDS: ACK ERROR loggingfrontdoor-5d4b8bcb76-psbtv.telemetry-ns-3 Internal:Proto constraint validation failed (RouteConfigurationValidationError.VirtualHosts[5]: embedded message failed validation | caused by VirtualHostValidationError.Routes[0]: embedded message failed validation | caused by RouteValidationError.Route: embedded message failed validation | caused by RouteActionValidationError.WeightedClusters: embedded message failed validation | caused by WeightedClusterValidationError.Clusters: value must contain at least 1 item(s)): name: "80"
virtual_hosts {

**Comment by dddddai** [comment]
I did try creating [the vs](https://github.com/istio/istio/issues/41980#issue-1448129061) but I got a validation error correctly
```bash
Error from server: error when creating "vs.yaml": admission webhook "validation.istio.io" denied the request: configuration is invalid: HTTP route, redirect or direct_response is required
```
Could you please check if your validation webhook is working?

**Comment by chaunceyjiang** [comment]
> Error from server: error when creating "vs.yaml": admission webhook "validation.istio.io" denied the request: configuration is invalid: HTTP route, redirect or direct_response is required

From your error message, it seems that your version of istio is not 1.14.1.

https://github.com/istio/istio/blob/1.14.1/pkg/config/validation/virtualservice.go#L255

**Comment by chaunceyjiang** [comment]
I can't reproduce this issue,my version of isio is 1.14.1.
![image](https://user-images.githubusercontent.com/17962021/201887818-fcc76e05-89cd-43a0-a19e-be98c5c6d3b4.png)

**Comment by reddymh** [comment]
@dddddai @chaunceyjiang we are using the below docker version of istiod and istio gateway 
istio-gateway: docker.io/istio/proxyv2:1.14.1 
istiod: docker.io/istio/pilot:1.14.1

**Comment by tangmengqiu** [comment]
> low virtual service without any validatio error but in the log file I am seeing the validation errors.

I got it. In your ValidatingWebhookConfiguration, the 
```
  objectSelector:
    matchExpressions:
    - key: istio.io/rev
      operator: In
      values:
      - default
```
and your virtual service does not contain the label `istio.io/rev=default`. I'm also curious about how to solve this. There is  a workaround that patch this webhook, set its objectSelector to `{}`. But I can understand the purpose to set the matchExpression with the revision on this. Can you explain? @howardjohn. Users do not need to set this label so that their CRDs can get validated, right?
