### ISSUE TITLE
Virtual service no route match when simple host is used

### ISSUE THREAD

**Issue by PedroAlbamonte** [istio/istio#42032]
### Bug Description

Hi,

I defined a simple dns name(foo) and it's resolved only internaly in my network / dns server. It resolves to istio-ingressgateway IP.

When I call `http://foo/bar/v1/health`  it should redirect to the bar service inside my k8s, but I receive the no route match message in ingress gateway log.

Defined Gateway:
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: foo
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
```

Defined VistualService:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: bar
spec:
  gateways:
  - istio-system/foo
  hosts:
  - 'foo'
  http:
  - match:
      gateways:
      - istio-system/foo
      uri:
        prefix: /bar/
    rewrite:
      uri: /
    route:
    - destination:
        host: bar.default.svc.cluster.local
        port:
          number: 80
      weight: 100
```

If I change the host in the VirtualService to '*' it works

### Version

```prose
❯ istioctl version
client version: 1.14.1
control plane version: 1.14.5
data plane version: 1.14.5 (210 proxies), 1.14.3 (184 proxies), 1.14.1 (48 proxies), 1.14.4 (73 proxies), 1.15.3 (5 proxies)

~
❯ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.15+IKS", GitCommit:"e982eaaac65ba290ce43154f935e895ee21640c1", GitTreeState:"clean", BuildDate:"2022-09-21T19:55:23Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```
