### ISSUE TITLE
Header field missing in bookinfo

### ISSUE THREAD

**Issue by rshiva777** [istio/istio#42067]
I have gone through the istio documentation and found that we can add the headers to filter the traffic. Tried using the example provided by istio

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: reviews
  namespace: default
spec:
  hosts:
  - reviews
  http:
  - match:
    - headers:
        end-user:
          exact: jason
    route:
    - destination:
        host: reviews
        subset: v2
  - route:
    - destination:
        host: reviews
        subset: v1
```

My question is where can we find the header field on the webpage. Here we have used the **end-user** as the header and matching with jason user to route to subsetv2 which is working as expected. But, i am unable to find the **end-user** header filed in the inspect page or anywhere else in bookinfo page.

FYI,
![image](https://user-images.githubusercontent.com/42074614/202709593-db456116-57ca-4328-8247-e6c6875e32c1.png)

Can anyone help me where can i find the header "end-user" in the page

**Comment by howardjohn** [comment]
That isn't adding a header, its matching on them. https://istio.io/latest/docs/reference/config/networking/virtual-service/#Headers shows examples of mutating request qand response headers

**Comment by rshiva777** [comment]
@howardjohn  Thanks for the quick response.

Yes i got it, we are adding the header with match condition in virtual service to filter bookinfo page based on the user.

```
  - match:
    - headers:
        end-user:
          exact: jason
```


It was absolutely working fine, but my question is where can i see the end-user header field, i am unable to see it from developer tools or any.
