### ISSUE TITLE
Removing numTrustedProxies is not reflected in IstioOperator spec

### ISSUE THREAD

**Issue by cnvergence** [istio/istio#42068]
### Bug Description

I have encountered confusing behavior during some Istio updates with `istioctl`.
Changing `.values.meshConfig.gatewayTopology.numTrustedProxies` and then removing it is not appropriately reflected in the IstioOperator on the cluster.
However, it is changed in the istio ConfigMap, so it is working as it should.

### Steps to reproduce
- install the latest Istio with the default profile and prepared meshConfig values
```
cat example1.yaml

apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    defaultConfig:
      holdApplicationUntilProxyStarts: false
      gatewayTopology:
        numTrustedProxies: 1
      
istioctl install -f example1.yaml
```
- check applied IstioOperator and istio ConfigMap
```
 k get istiooperators.install.istio.io -o yaml -n istio-system
 
 ...
    meshConfig:
      defaultConfig:
        gatewayTopology:
          numTrustedProxies: 1
        holdApplicationUntilProxyStarts: false
        proxyMetadata: {}
      enablePrometheusMerge: true
 ...
 k get cm istio -n istio-system -o yaml
 ...
data:
  mesh: |-
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      gatewayTopology:
        numTrustedProxies: 1
      holdApplicationUntilProxyStarts: false
      proxyMetadata: {}
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
    enablePrometheusMerge: true
    rootNamespace: istio-system
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
  ...
```
- run the update with changes to meshConfig values
```
cat example2.yaml

apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      
istioctl install -f example2.yaml
```
- check applied IstioOperator and istio ConfigMap
```
 k get istiooperators.install.istio.io -o yaml -n istio-system
 
 ...
    meshConfig:
      defaultConfig:
        gatewayTopology:
          numTrustedProxies: 1
        holdApplicationUntilProxyStarts: true
        proxyMetadata: {}
      enablePrometheusMerge: true
 ...
 k get cm istio -n istio-system -o yaml
 ...
data:
  mesh: |-
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      holdApplicationUntilProxyStarts: true
      proxyMetadata: {}
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
    enablePrometheusMerge: true
    rootNamespace: istio-system
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
  ...
```

### Version

```prose
istioctl version                                                                                                                                                                                                                                                
client version: 1.16.0
control plane version: 1.16.0
```


### Additional Information

_No response_
