### ISSUE TITLE
Istio should probably default to Envoy DnsLookupFamily AUTO or allow configuration via an env variable

### ISSUE THREAD

**Issue by dmorina** [istio/istio#42097]
### Bug Description

We have an IPv6 EKS cluster which is capable of talking to IPv6 and IPv4 destinations without DNS64/NAT64. If we enable Istio in a namespace and the destination domain returns an A record only then Istio is unable to talk to it. This seems to be due to the fact that Istio uses DnsLookupFamily V4_ONLY or V6_ONLY (https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/cluster_builder.go#L369) and doesn't support DNS queries for both. 

Envoy seems to default to AUTO which in most cases would be desirable I think https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-enum-config-cluster-v3-cluster-dnslookupfamily so it would be great to keep the same defaults (maybe there's a reason why it is the way it is). or at the very least allow us to configure the DNS lookup family. 

We managed to apply an EnvoyFilter to the outbound sidecar like so which does the right thing in this namespace but we'd prefer AUTO in most cases (that doesn't seem to be allowed in an EnvoyFilter, seems to revert to V6_ONLY).

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: dns-all
  namespace: test-ns
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      context: SIDECAR_OUTBOUND
    patch:
      operation: MERGE
      value:
        dns_lookup_family: ALL

```

### Version

```prose
$ istioctl version
client version: 1.15.2
control plane version: 1.15.3
data plane version: 1.14.4 (41 proxies), 1.15.3 (7 proxies)
$ kubectl version --short
Client Version: v1.25.3
Server Version: v1.22.15-eks-fb459a0
```
