### ISSUE TITLE
Why is the value of destination_cluster in istio metrics fetched by node.metadata['CLUSTER_ID'] ?

### ISSUE THREAD

**Issue by mark8s** [istio/istio#42105]
Hi everyone, I have some questions. I've been messing around with istio custom metrics recently and I've run into some confusion.

First, when I looked at the envoyfilter named stats-filter-1.10 under istio-system, I found some configurations that I didn't quite understand.

```yaml
patch:
      operation: INSERT_BEFORE
      value:
        name: istio.stats
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          value:
            config:
              configuration:
                '@type': type.googleapis.com/google.protobuf.StringValue
                value: |
                  {
                    "debug": "false",
                    "stat_prefix": "istio",
                    "disable_host_header_fallback": true,
                    "metrics": [
                      {
                        "dimensions": {
                          "destination_cluster": "node. metadata['CLUSTER_ID']",
                          "source_cluster": "downstream_peer.cluster_id"
                        }
                      }
                    ]
                  }
              root_id: stats_inbound
              vm_config:
                code:
                  local:
                    inline_string: envoy.wasm.stats
                runtime: envoy.wasm.runtime.null
                vm_id: stats_inbound
```

1. Why source_cluster: downstream_peer.cluster_id , why "destination_cluster": "node.metadata['CLUSTER_ID']", what is its principle? I checked the official documentation of istio, but I couldn't find the principle.

2. The official document describes a Peer metadata, I don't understand what it means, can someone explain it for me?
original:
> Peer metadata is available as attributes upstream_peer for outbound and downstream_peer for inbound

![image](https://user-images.githubusercontent.com/47961301/203243821-a8c12288-47f0-45a0-b78b-47f4bf3f3f82.png)
