### ISSUE TITLE
How to create new istio metrics, and use default DefaultStatTags?

### ISSUE THREAD

**Issue by mark8s** [istio/istio#42106]
Hello everyone, I have a question. I have a requirement, I want to create custom istio metrics, similar to istio_request_total.

Specifically, I want to create a metric similar to istio_request_total, which contains some tags, such as request_path, reporter, source_app, etc. I implemented it based on envoyfilter, and the implemented yaml content is roughly as follows:

```
- applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: istio.stats
      proxy:
        proxyVersion: ^1\.11.*
    patch:
      operation: REPLACE
      value:
        name: istio.stats
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          value:
            config:
              configuration:
                '@type': type.googleapis.com/google.protobuf.StringValue
                value: |
                 {
                    "debug": "false",
                    "stat_prefix": "test",
                    "metrics": [
                      {
                        "name": "requests_total",
                        "dimensions": {
                          "destination_cluster": "node. metadata['CLUSTER_ID']",
                          "source_cluster": "downstream_peer.cluster_id",
                          "reporter": "reporter",
                          "request_path": "request.path",
                          "source_app": "source_app"
                        }
                      }
                    ]
                  }
              root_id: stats_inbound
              vm_config:
                code:
                  local:
                    inline_string: envoy.wasm.stats
                runtime: envoy.wasm.runtime.null
                vm_id: stats_inbound
```

My idea is that reporter and source_app use the default DefaultStatTags list, and then request_path I use `sidecar.istio.io/extraStatTags: request.path` to declare in the workload. The declaration of my new indicator (test_requests_total) is also through envoyfilter, and its configuration is roughly as follows:

```yaml
- applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
      proxy:
        proxyVersion: ^1\.11.*
    patch:
      operation: INSERT_BEFORE
      value:
        name: istio.stats
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          value:
            config:
              configuration:
                '@type': type.googleapis.com/google.protobuf.StringValue
                value: |
                  {
                    "debug": "false",
                    "stat_prefix": "test",
                    "definitions": [
                      {
                        "name": "request_total",
                        "type": "COUNTER",
                        "value": "1"
                      }
                    ]
                  }
              root_id: stats_inbound
              vm_config:
                code:
                  local:
                    inline_string: envoy.wasm.stats
                runtime: envoy.wasm.runtime.null
                vm_id: stats_inbound
```

Its declaration in the workload is: sidecar.istio.io/statsInclusionPrefixes: test_request_total

But I found that the indicator test_solarmesh_total was not generated after such a configuration. I guess it is caused by reporter and source_app not taking effect, but I don't know how to solve it.

Does anyone know how to fix it? Is there something wrong with my train of thought?
