### ISSUE TITLE
Jwks is an invalid JSON

### ISSUE THREAD

**Issue by 2456868764** [istio/istio#42108]
### Bug Description

1. I apply request authentication policy using demo jwks as bellow:
```
kubectl apply -f - <<EOF
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: "jwt-example"
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
  - issuer: "testing@secure.istio.io"
    jwksUri: "https://gitcode.net/wuswoo/mytest/-/raw/master/doc/istio/security/tools/jwt/samples/jwks.json"
EOF
```

the demo jwks is absolutely same as content from https://raw.githubusercontent.com/istio/istio/release-1.16/security/tools/jwt/samples/jwks.json.

2. kubectl logs -f istio-ingressgateway-57bcb89bf9-hplr4 -n istio-system

2022-11-22T07:46:47.730788Z     warning envoy config    gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_8080: Provider 'origins-0' in jwt_authn config has invalid local jwks: Jwks is an invalid JSON
0.0.0.0_8443: Provider 'origins-0' in jwt_authn config has invalid local jwks: Jwks is an invalid JSON

 

### Version

```prose
$ istioctl version
client version: 1.15.3
control plane version: 1.15.3
data plane version: 1.15.3 (20 proxies)
```
