### ISSUE TITLE
Use envoyfilter to create istio new metrics invalid

### ISSUE THREAD

**Issue by mark8s** [istio/istio#42112]
I used envoyfilter to create an istio_test_requests metrics and set a dimension, but after I applied it to the workload, it didn't take effect. Does anyone know why? My so configuration is as follows:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: test
  namespace: bookinfo
spec:
  workloadSelector:
    labels:
      app: reviews
      version: v2
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_OUTBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
      proxy:
        proxyVersion: ^1\.11.*
    patch:
      operation: INSERT_BEFORE
      value:
        name: istio.stats
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          value:
            config:
              configuration:
                '@type': type.googleapis.com/google.protobuf.StringValue
                value: |
                  {
                    "debug": "false",
                    "stat_prefix": "istio",
                    "definitions": [
                      {
                        "name": "test_requests",
                        "type": "COUNTER",
                        "value": "1"                      
                      }
                    ],
                    "metrics": [
                      { 
                        "name": "test_requests",
                        "dimensions": {
                          "request_path": "upstream_peer.istio_version"
                        }
                      }                    
                    ]
                  }
              root_id: stats_outbound
              vm_config:
                code:
                  local:
                    inline_string: envoy.wasm.stats
                runtime: envoy.wasm.runtime.null
                vm_id: stats_outbound


```

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 4
  labels:
    app: reviews
    version: v2
  name: reviews-v2
  namespace: bookinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v2
  template:
    metadata:
      annotations:
        sidecar.istio.io/extraStatTags: request.path
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/statsInclusionPrefixes: istio_test_metric,istio_test_requests
      creationTimestamp: null
      labels:
        app: reviews
        version: v2
    spec:
      containers:
      - env:
        - name: LOG_DIR
          value: /tmp/logs
        image: registry.cn-shenzhen.aliyuncs.com/solar-mesh/examples-bookinfo-reviews-v2:1.15.0
        imagePullPolicy: IfNotPresent
        name: reviews
        ports:
        - containerPort: 9080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /opt/ibm/wlp/output
          name: wlp-output
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: bookinfo-reviews
      serviceAccountName: bookinfo-reviews
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: wlp-output
      - emptyDir: {}
        name: tmp

```
