### ISSUE TITLE
Telemetry API: implement `MetricDefinition`

### ISSUE THREAD

**Issue by zirain** [istio/istio#42128]
after https://github.com/istio/istio/pull/41991, we're moving to use native stats in v1.17.
before https://github.com/istio/istio/issues/37645, we should support `MetricDefinition` in Telemetry API.

cc @kyessenov @lei-tang 

following IOP will not working on master branch:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: custom-metrics
  namespace: istio-system
spec:
  values:
    global:
      meshID: mesh1
    telemetry:
      enabled: true
      v2:
        enabled: true
        prometheus:
          configOverride:
            inboundSidecar:
              definitions:
                - name: posta_total
                  type: "COUNTER"
                  value: "1"
                - name: posta_duration_milliseconds
                  type: "HISTOGRAM"
                  value: request.duration 
              metrics:
                - name: posta_total
                  dimensions:
                    url_path: request.url_path
                    response_status: string(response.code)
                - name: posta_duration_milliseconds
                  dimensions:
                    url_path: request.url_path
                    response_status: string(response.code)
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      proxyStatsMatcher:
        inclusionPrefixes:
          - istio_posta_total
          - istio_posta_duration_milliseconds_buckets
          - istio_posta_duration_milliseconds_sum
          - istio_posta_duration_milliseconds_total
      extraStatTags:
        - url_path
        - response_status
```
