### ISSUE TITLE
Routing error when using two gateways with the same port and different host

### ISSUE THREAD

**Issue by gtolarc** [istio/istio#42130]
### Bug Description

I want to put the same two environments on the same cluster (for convenience of development)
I set gateway/vs as follows to make access to services in other namespaces through domain division.

It seemed to work fine at first, but only one side works fine. (If the gw gateway works, the gw-dev gateway doesn't work, sometimes it works the other way around) Is it a bug? Or am I setting it up wrong?

```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: gw
  namespace: ns
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - sv.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: sv-credential
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sv1
  namespace: ns
spec:
  gateways:
  - gw
  hosts:
  - sv.com
  http:
  - match:
    - uri:
        prefix: /sv1
    route:
    - destination:
        host: sv1
        port:
          number: 5000




apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: gw-dev
  namespace: ns-dev
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - dev.sv.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: sv-credential
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sv1
  namespace: ns-dev
spec:
  gateways:
  - gw-dev
  hosts:
  - dev.sv.com
  http:
  - match:
    - uri:
        prefix: /sv1
    route:
    - destination:
        host: sv1
        port:
          number: 5000
```

### Version

```prose
## istioctl version
client version: 1.16.0
control plane version: 1.16.0
data plane version: 1.16.0 (9 proxies)

## kubectl version
Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.24.7-eks-fb459a0
```
