### ISSUE TITLE
Envoy filter: unknown field "typed_config" in envoy.config.route.v3.Route

### ISSUE THREAD

**Issue by gmeher** [istio/istio#42148]
### Bug Description

A sample Istio virtual service. It retries 5 times without backoff or Jitter.
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: playlists-api
spec:
  hosts:
  -  playlists-api
  http:
  - name: playlists-api
    route:
    - destination:
        host: playlists-api
    retries:
      attempts: 5
      perTryTimeout: 2s
```

I want to apply Jitter and exponential backoffs to the retries, so adding an envoy Filter

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: retry-interval
spec:
  workloadSelector:
    labels:
      app: playlists-api
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: SIDECAR_OUTBOUND
    patch:
      operation: MERGE
      value:
        name: envoy.filter.retry
        typed_config: 
          '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
        route:
          retry_policy:
            retry_back_off:
              base_interval: 4s
              max_interval: 40s

```

getting output:
```
Warning: Envoy filter: unknown field "typed_config" in envoy.config.route.v3.Route
envoyfilter.networking.istio.io/retry-interval created
```

As expected the retries are not with exponential backoff. 

1. envoy [says exponential backoff is by default](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#x-envoy-max-retries). But istio does not provide the backoff retries as default.
2. Getting warning when trying to add envoy proxy filter to support exponential backoff.

### Version

```prose
client version: 1.16.0
control plane version: 1.16.0
data plane version: 1.16.0 (8 proxies)

Client Version: v1.21.5
Server Version: v1.21.1
```

**Comment by j2gg0s** [comment]
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: retry-interval
spec:
  workloadSelector:
    labels:
      app: playlists-api
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: SIDECAR_OUTBOUND
    patch:
      operation: MERGE
      value:
        name: envoy.filter.retry
        route:
          retry_policy:
            retry_back_off:
              base_interval: 4s
              max_interval: 40s
```

- typed_config is not necessary and istio warn for unknown field.
- maybe we should check Envoy's route, like `istioctl proxy-config route xxx --name xxx | jq '.[].virtualHosts[].routes[].route'`

**Comment by j2gg0s** [comment]
Default Retry policy maybe controlled by this: https://github.com/istio/istio/blob/f8baff38c9b4129c0a6a1b24e31881f90a2c11e6/pilot/pkg/networking/core/v1alpha3/route/retry/retry.go#L33

**Comment by gmeher** [comment]
Hi @j2gg0s , 
I can see the envoyFilter reflecting in the side car.
```
            {
                "name": "playlists-api.default.svc.cluster.local:80",
                "domains": [
                    "playlists-api.default.svc.cluster.local",
                    "playlists-api",
                    "playlists-api.default.svc",
                    "playlists-api.default",
                    "10.96.108.156"
                ],
                "routes": [
                    {
                        "name": "playlists-api",
                        "match": {
                            "prefix": "/"
                        },
                        "route": {
                            "cluster": "outbound|80||playlists-api.default.svc.cluster.local",
                            "timeout": "0s",
                            "retryPolicy": {
                                "retryOn": "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes",
                                "numRetries": 5,
                                "perTryTimeout": "2s",
                                "retryHostPredicate": [
                                    {
                                        "name": "envoy.retry_host_predicates.previous_hosts",
                                        "typedConfig": {
                                            "@type": "type.googleapis.com/envoy.extensions.retry.host.previous_hosts.v3.PreviousHostsPredicate"
                                        }
                                    }
                                ],
                                "hostSelectionRetryMaxAttempts": "5",
                                "retriableStatusCodes": [
                                    503
                                ],
                                "retryBackOff": {
                                    "baseInterval": "2s",
                                    "maxInterval": "8s"
                                }
                            },
                            "maxStreamDuration": {
                                "maxStreamDuration": "0s",
                                "grpcTimeoutHeaderMax": "0s"
                            }
                        },
                        "metadata": {
                            "filterMetadata": {
                                "istio": {
                                    "config": "/apis/networking.istio.io/v1alpha3/namespaces/default/virtual-service/playlists-api"
                                }
                            }
                        },
                        "decorator": {
                            "operation": "playlists-api.default.svc.cluster.local:80/*"
                        }
                    }
                ],
                "includeRequestAttemptCount": true
            }
```

When I make a API request all retries happen at once instead of back_off ? Am I missing something. Or is this a bug ?

**Comment by j2gg0s** [comment]
@gmeher Sorry, i'm not familiar with retry policy.

Maybe because perTryTimeout is same as baseInterval?

**Comment by gmeher** [comment]
Do you know, any one who can figure out what is happening here ?
@j2gg0s

**Comment by GregHanson** [comment]
@gmeher is the `istioctl proxy-config route xxx` output you shared above from the client or server pod?  The retry logic should be applied to the client sidecar.

if `playlists-api.default.svc.cluster.local` is the host you want to patch the retry logic for, you should modify the `workloadSelector` to select the client workload instead of the server `app: playlists-api` workload
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: retry-interval
spec:
  workloadSelector:
    labels:
      app: playlists-api. ## app: client-pod
```

Also, the default retryPolicy Istio uses is the following:
```
        "retryOn": "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes",
```
if that does not apply to your retry scenario, you need to modify the default settings using the global MeshConfig retryPolicy or define a new retryPolicy via VirtualService for host `playlists-api.default.svc.cluster.local`
