### ISSUE TITLE
multi-ingressgateway installation by Istio operator will create a default ingressgateway? 

### ISSUE THREAD

**Issue by dearboll23** [istio/istio#42143]
Hi guys, I'm creating multi ingress gateways for staging and demo env in the same cluster by Istio operator, the operator yaml is as below. I named the two ingress gateway as ` istio-ingressgateway-staging` and ` istio-ingressgateway-demo`, but I found that the operator create a default ingress gateway named `istio-ingressgateway`. How can I disable the default name ingress gateway, or is this a feature of istio operator (to create a default name ingressgateway when the component is enabled)?

``` yaml
  components:
    base:
      enabled: true
    cni:
      enabled: false
    egressGateways:
    - enabled: false
      name: istio-egressgateway
    ingressGateways:
    - enabled: true
      k8s:
        env:
        - name: ISTIO_META_REQUESTED_NETWORK_VIEW
          value: network1
        service:
          ports:
          - name: status-port
            port: 15021
            targetPort: 15021
          - name: tls
            port: 15443
            targetPort: 15443
          - name: tls-istiod
            port: 15012
            targetPort: 15012
          - name: tls-webhook
            port: 15017
            targetPort: 15017
      label:
        app: istio-ingressgateway-staging
        istio: ingressgateway-staging
        topology.istio.io/network: network1
      name: istio-ingressgateway-staging
    - enabled: true
      k8s:
        env:
        - name: ISTIO_META_REQUESTED_NETWORK_VIEW
          value: network1
        service:
          ports:
          - name: status-port
            port: 15021
            targetPort: 15021
          - name: tls
            port: 15443
            targetPort: 15443
          - name: tls-istiod
            port: 15012
            targetPort: 15012
          - name: tls-webhook
            port: 15017
            targetPort: 15017
      label:
        app: istio-ingressgateway-demo
        istio: ingressgateway-demo
        topology.istio.io/network: network1
      name: istio-ingressgateway-demo
```
Thanks for your time!
