### ISSUE TITLE
Why can't I add dimensions to custom metrics?

### ISSUE THREAD

**Issue by mark8s** [istio/istio#42145]
Hello everyone, I would like to ask you about customizing metrics again, and I hope someone can help me out.

I created an envoyfilter and I want to create a custom metrics. I named it istio_solarmesh_requests_total.

Below is my configuration:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: solarmesh-request-total
  namespace: istio-system
  labels:
    istio.io/rev: default
spec:
  priority: -1
  configPatches:
  ## Sidecar Inbound 
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_OUTBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
      proxy:
        proxyVersion: ^1\.11.*
    patch:
      operation: INSERT_BEFORE
      value:
        name: istio.stats
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          value:
            config:
              configuration:
                '@type': type.googleapis.com/google.protobuf.StringValue
                value: |
                  {
                    "debug": "false",
                    "stat_prefix": "istio",
                    "definitions": [
                      {
                        "name": "solarmesh_requests_total",
                        "type": "COUNTER",
                        "value": "1"                      
                      }
                    ],
                    "metrics": [
                      { 
                        "name": "solarmesh_requests_total",
                        "dimensions": {
                          "request_path": "upstream_peer.istio_version"
                        }
                      }                    
                    ]
                  }
              root_id: stats_outbound
              vm_config:
                code:
                  local:
                    inline_string: envoy.wasm.stats
                runtime: envoy.wasm.runtime.null
                vm_id: stats_outbound
```

However, when I applied it, the metrics did not produce any data.

So I removed the dimension definition in metrics, and the data appeared immediately, but this is data without dimension, which is not what I want.

After I removed it, the configuration is as follows:

```
value:
        name: istio.stats
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          value:
            config:
              configuration:
                '@type': type.googleapis.com/google.protobuf.StringValue
                value: |
                  {
                    "debug": "false",
                    "stat_prefix": "istio",
                    "definitions": [
                      {
                        "name": "solarmesh_requests_total",
                        "type": "COUNTER",
                        "value": "1"                      
                      }
                    ]
                  }
              root_id: stats_outbound
              vm_config:
                code:
                  local:
                    inline_string: envoy.wasm.stats
                runtime: envoy.wasm.runtime.null
                vm_id: stats_outbound
```
My Prometheus output:

![image](https://user-images.githubusercontent.com/47961301/203790325-fafc9096-ce72-4b30-a274-7f04a50a27c3.png)

container output： 

```shell
kubectl exec -it -n bookinfo deploy/productpage-v1 -c istio-proxy -- curl localhost:15000/stats/prometheus | grep istio_solarmesh_requests_
# TYPE istio_solarmesh_requests_total counter
istio_solarmesh_requests_total{} 72
```

Why? Weird, I've been confused for days. . .
