### ISSUE TITLE
static files of jaeger not loading

### ISSUE THREAD

**Issue by pallintipremkumar** [istio/istio#42169]
### Bug Description

The static files of jaeger not loading getting 404 error for all static content files. 

I am using below configuration
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tracing-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-tracing
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tracing-vs
  namespace: istio-system
spec:
  hosts:
  - "*"
  gateways:
  - tracing-gateway
  http:
  - match:
    - uri:
        prefix: "/tracing"    
    route:
    - destination:
        port:
          number: 80 # Backend service port
        host: tracing # Backend service name
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: tracing
  namespace: istio-system
spec:
  host: tracing
  trafficPolicy:
    tls:
      mode: DISABLE
---
```

### Version

```prose
client version: 1.15.1
control plane version: 1.15.1
data plane version: 1.15.1 (2 proxies)
[premkumar@fedora bin]$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.1
Kustomize Version: v4.5.4
Server Version: v1.23.3
```

### Additional Information

![Screenshot from 2022-11-27 09-27-15](https://user-images.githubusercontent.com/39269050/204118592-ae159253-6d88-4b74-8d81-f16fccf22abe.png)

**Comment by zirain** [comment]
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tracing-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-tracing
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tracing-vs
  namespace: istio-system
spec:
  hosts:
  - "*"
  gateways:
  - tracing-gateway
  http:
  - match:
    - uri:
        prefix: "/tracing"
    - uri:
        prefix: "/jaeger"    
    route:
    - destination:
        port:
          number: 80 # Backend service port
        host: tracing # Backend service name
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: tracing
  namespace: istio-system
spec:
  host: tracing
  trafficPolicy:
    tls:
      mode: DISABLE
---
```
