### ISSUE TITLE
AuthorizationPolicy validation contradicts actual behavior (CUSTOM with notPrincipals rule)

### ISSUE THREAD

**Issue by F7502** [istio/istio#42162]
### Bug Description

We have implemented an external authorization provider and use it in `AuthorizationPolicy` resources with `action: CUSTOM`. One of our policies looks like this:

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: my-policy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: some-service
  action: CUSTOM
  provider:
    name: "my-ext-authz-provider"
  rules:
  - to:
    # no authz for health check calls
    - operation:
        notPaths: ["/healthz"]
    from:
    # no authz for calls from some-other-service
    - source:
        notPrincipals: ["cluster.local/ns/some-namespace/sa/some-other-service"]

```

When we run `istioctl analyze -A` we get the following error:

```
Error [IST0106] (AuthorizationPolicy my-policy) Schema validation error: invalid policy my-policy: From.NotPrincipals is currently not supported with CUSTOM action
```

However, when we are sending traffic to our service the policy seems to be active, i.e. request coming from the Gateway are processed by our ext-authz provider but requests coming from `some-other-service` skip the ext-authz. When we remove the `from` rule from our policy then requests coming from `some-other-service` are forwarded to the ext-authz provider. So all we see on the cluster tells us that the `AuthorizationPolicy` works as we configured it but the validation tells us it should not.

### Version

```prose
$ istioctl version
client version: 1.16.0
control plane version: 1.15.3
data plane version: 1.13.4 (1219 proxies), 1.15.3 (226 proxies)

$ kubectl version --short
Client Version: v1.24.1
Kustomize Version: v4.5.4
Server Version: v1.23.9
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [X] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
