### ISSUE TITLE
Cannot use DNS_ROUND_ROBIN in ServiceEntry without an endpoint specified

### ISSUE THREAD

**Issue by jacob-delgado** [istio/istio#42184]
### Bug Description

The following does not work in 1.16.0, but works in 1.14.5

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc2
spec:
  exportTo:
  - .
  hosts:
  - example.com
  location: MESH_EXTERNAL
  ports:
  - name: http2-1
    number: 1234
    protocol: HTTP2
  resolution: DNS_ROUND_ROBIN
```

This returns the following:
> Error from server: error when creating "se-1.yaml": admission webhook "validation.istio.io" denied the request: configuration is invalid: there must only endpoint for resolution mode DNS_ROUND_ROBIN

If I add
```yaml
  endpoints:
  - address: 2.2.2.2
```
it works but having
```yaml
  endpoints:
  - address: 2.2.2.2
  - address: 3.3.3.3
```
reports the same issue.

I tracked this to https://github.com/istio/istio/pull/41901

### Version

```prose
client version: 1.16.0
control plane version: 1.16.0
data plane version: 1.16.0 (1 proxies)

Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.25.3
```
