### ISSUE TITLE
Question: isito send info other than header from the external auth.

### ISSUE THREAD

**Issue by lokeshjain2008** [istio/istio#42195]
We have istio gateway with the following configuration

```
envoyExtAuthzHttp:
      service: "<user-service>"
      pathPrefix: "/api/verify-user"
      port: "80"
      includeRequestHeadersInCheck: [ "authorization" ]
      headersToUpstreamOnAllow: [ "authorization", "x-auth-authtype", "x-auth-connection", "x-auth-user" ]

```
Note: the response from the `userService` is being added to the header as 

```     
  response.header('x-auth-user', userObject);
   return response.status(200).send();
```
Now the size of `userObject` has increase with new feature and we getting `header size` error.

Please help me with an alternate approach other than increasing the allowed header size.

thanks,
