### ISSUE TITLE
Question: How to add DefaultStatTags to not standard Envoy metrics.

### ISSUE THREAD

**Issue by davidggz** [istio/istio#42200]
Hello! I've been trying to get more metrics from Envoy using `IstioOperator` configuration because the Standard Istio Metrics are not enough for our use cases. For instance, it would be pretty good having the number of active connections in all our `istio-proxy` containers. Following the documentation [in here](https://istio.io/latest/docs/ops/configuration/telemetry/envoy-stats/) I added the following lines to the `IstioOperator` configuration:

````yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    accessLogFile: /dev/stdout 
    defaultConfig:
      proxyStatsMatcher:
        inclusionSuffixes:
          - "upstream_cx_active"
````

This produces the following output in the `localhost:15000/stats/prometheus` endpoint (many more similar lines appear with different `cluster_name` values):

````yaml
# TYPE envoy_cluster_upstream_cx_active gauge
envoy_cluster_upstream_cx_active{cluster_name="BlackHoleCluster"} 0
envoy_cluster_upstream_cx_active{cluster_name="agent"} 16
envoy_cluster_upstream_cx_active{cluster_name="outbound|15010||istiod.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_active{cluster_name="outbound|15012||istiod.istio-system.svc.cluster.local"} 0
envoy_cluster_upstream_cx_active{cluster_name="outbound|15014||istiod.istio-system.svc.cluster.local"} 0
...
````

This is ok, but I would be interested on adding some other tags to this metric, such as `destination_service_name`. I thought this would be automatically done by Istio. Since I saw that this wasn't happening automatically, I tried to add the tags by myself and added the following configuration to the `IstioOperator` following [the documentation](https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/), but I did get the same result.

````yaml
  values:
    telemetry:
      v2:
        prometheus:
          configOverride:
            gateway:
              metrics:
                - name: upstream_cx_active
                  dimensions:
                    destination_service_name: destination.service.name
````

Am I missing anything?

## Version

````
❯ istioctl --context eip-dev version
client version: 1.14.1
control plane version: 1.14.1
data plane version: 1.14.1
````
