### ISSUE TITLE
ServiceEntry's from other revisions are not being ignored

### ISSUE THREAD

**Issue by morepork** [istio/istio#42212]
### Bug Description

ServiceEntry's with other revision labels are not getting skipped when they should be.

Repro steps in a local kind cluster with bookinfo:

```
kind create cluster --image=kindest/node:v1.22.15

istioctl install --set profile=demo -y

# Install bookinfo
kubectl create namespace bookinfo
k label namespace bookinfo istio-injection=enabled
kubens bookinfo
kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.15/samples/bookinfo/platform/kube/bookinfo.yaml

# Create a SE with a revision label and a DR based on the examples from:
# https://istio.io/latest/docs/reference/config/networking/service-entry/

cat <<EOF | k apply -f -
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: mtls-mongocluster
spec:
  host: mymongodb.somedomain
  trafficPolicy:
    tls:
      mode: MUTUAL
      clientCertificate: /etc/certs/myclientcert.pem
      privateKey: /etc/certs/client_private_key.pem
      caCertificates: /etc/certs/rootcacerts.pem
EOF

cat <<EOF | k apply -f -
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-svc-mongocluster
  labels:
    istio.io/rev: something # <-- revision label
spec:
  hosts:
  - mymongodb.somedomain # not used
  addresses:
  - 192.192.192.192/24 # VIPs
  ports:
  - number: 27018
    name: mongodb
    protocol: MONGO
  location: MESH_INTERNAL
  resolution: STATIC
  endpoints:
  - address: 2.2.2.2
  - address: 3.3.3.3
EOF
```

Now when I query the endpoints of one of the pods, I see the "mongodb" IPs, i.e.

```
% istioctl pc endpoints productpage-v1-797d845774-94p75.bookinfo
...
2.2.2.2:27018                                           HEALTHY     OK                outbound|27018||mymongodb.somedomain
3.3.3.3:27018                                           HEALTHY     OK                outbound|27018||mymongodb.somedomain
unix://./etc/istio/proxy/XDS                            HEALTHY     OK                xds-grpc
unix://./var/run/secrets/workload-spiffe-uds/socket     HEALTHY     OK                sds-grpc
```

I expect these not to be present as the SE has a different revision label to the istio version installed. The installed version has the default revision of `""`.

### Version

```prose
% istioctl version
client version: 1.15.3
control plane version: 1.15
data plane version: 1.15.3 (8 proxies)

% k version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.22.15
WARNING: version difference between client (1.24) and server (1.22) exceeds the supported minor version skew of +/-1
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [X] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
