### ISSUE TITLE
Is there a way to get the inbound or outbound in the access log %UPSTREAM_CLUSTER% separately?

### ISSUE THREAD

**Issue by mark8s** [istio/istio#42218]
Below is my istio-proxy access log：

{
    "start_time":"2022-11-30T12:11:42.183Z",
    "protocol":"HTTP/1.1",
    "upstream_cluster":"inbound|9080||",
    "response_code":200,
    "downstream_local_address":"10.40.0.8:9080",
    "upstream_local_address":"127.0.0.6:58783",
    "user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36",
    "response_flags":"-",
    "downstream_remote_address":"10.46.0.13:41250",
    "upstream_transport_failure_reason":null,
    "bytes_received":0,
    "authority":"reviews:9080",
    "method":"GET",
    "connection_termination_details":null,
    "bytes_sent":295,
    "path":"/reviews/0",
    "duration":14,
    "route_name":"default",
    "upstream_service_time":"13",
    "requested_server_name":"outbound_.9080_._.reviews.bookinfo.svc.cluster.local",
    "response_code_details":"via_upstream",
    "x_forwarded_for":null,
    "upstream_host":"10.40.0.8:9080",
    "request_id":"5ee694cf-f93b-4064-a677-4e6abf8a82be"
}

I want to get the data flow indicator: Inbound/Outbound, what should I do. It seems that the data is stored in the parameter upstream_host: "%UPSTREAM_HOST%", I want to take it out separately and store it in a new field. Can it be done?

For example, the original data is:
```shell
   "upstream_cluster": "inbound|9080||"
```
I want to get a new field,
```shell
   "flow_direction": "inbound"
```

Can this be done? If so, how should it be done?

**Comment by zirain** [comment]
maybe you can try https://istio.io/latest/docs/reference/config/telemetry/

**Comment by mark8s** [comment]
@zirain The telemetry APi requires the istio version, I don't really want to use this. I want to use the most original way.

**Comment by zirain** [comment]
Telemetry is be first class API istio support.

**Comment by pxpnetworks** [comment]
I'm not an Istio user but i do similar things in vanilla Envoy with access log DYNAMIC_METADATA.
The medatada key value comes either from any of the http filters header_to_metadata or rbac filter's shadow_policy_id.
Not sure how original is this though :D

**Comment by zirain** [comment]
maybe envoy should support `%TRAFFIC_DIRECTION%`, but I'm not 100% understand the user case.
you can parse the direction form upstream cluster (it's well formed), and the cost is less.

**Comment by mark8s** [comment]
@zirain Thanks for the reply, %TRAFFIC_DIRECTION% doesn't seem to work, after adding it, istio-proxy can't get up.

**Comment by zirain** [comment]
> @zirain Thanks for the reply, %TRAFFIC_DIRECTION% doesn't seem to work, after adding it, istio-proxy can't get up.

it's not supported for now.

**Comment by zirain** [comment]
here is a workaround:

1. add following to your iop file and reinstall your istio:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    extensionProviders:
      - name: client
        envoyFileAccessLog:
          path: /dev/stdout
          logFormat:
            logFormat:
            labels:
              "direction": "outbound"
              "startTime": "[%START_TIME%]"
              "method": "%REQ(:METHOD)%"
              "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
              "protocol": "%PROTOCOL%"
              "reponseCode": "%RESPONSE_CODE%"
              "reponseFlags": "%RESPONSE_FLAGS%"
              "failureRease": "%UPSTREAM_TRANSPORT_FAILURE_REASON%"
              "bytesReceived": "%BYTES_RECEIVED% %BYTES_SENT%"
              "duration": "%DURATION%"
              "envoyUpstreamServiceTime": "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%"
              "forwardedFor": "%REQ(X-FORWARDED-FOR)%"
              "userAgent": "%REQ(USER-AGENT)%"
              "requestID": "%REQ(X-REQUEST-ID)%"
              "authority": "%REQ(:AUTHORITY)%"
              "host": "%UPSTREAM_HOST%"
              "upstreamCluster": "%UPSTREAM_CLUSTER%"
              "upstreamLocalAdress": "%UPSTREAM_LOCAL_ADDRESS%"
              "downstreamLocalAddress": "%DOWNSTREAM_LOCAL_ADDRESS%"
              "downstreamRemoteAddress": "%DOWNSTREAM_REMOTE_ADDRESS%"
              "requestedServerName": "%REQUESTED_SERVER_NAME%"
              "routeName": "%ROUTE_NAME%"
      - name: server
        envoyFileAccessLog:
          path: /dev/stdout
          logFormat:
            labels:
              "direction": "inbound"
              "startTime": "[%START_TIME%]"
              "method": "%REQ(:METHOD)%"
              "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
              "protocol": "%PROTOCOL%"
              "reponseCode": "%RESPONSE_CODE%"
              "reponseFlags": "%RESPONSE_FLAGS%"
              "failureRease": "%UPSTREAM_TRANSPORT_FAILURE_REASON%"
              "bytesReceived": "%BYTES_RECEIVED% %BYTES_SENT%"
              "duration": "%DURATION%"
              "envoyUpstreamServiceTime": "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%"
              "forwardedFor": "%REQ(X-FORWARDED-FOR)%"
              "userAgent": "%REQ(USER-AGENT)%"
              "requestID": "%REQ(X-REQUEST-ID)%"
              "authority": "%REQ(:AUTHORITY)%"
              "host": "%UPSTREAM_HOST%"
              "upstreamCluster": "%UPSTREAM_CLUSTER%"
              "upstreamLocalAdress": "%UPSTREAM_LOCAL_ADDRESS%"
              "downstreamLocalAddress": "%DOWNSTREAM_LOCAL_ADDRESS%"
              "downstreamRemoteAddress": "%DOWNSTREAM_REMOTE_ADDRESS%"
              "requestedServerName": "%REQUESTED_SERVER_NAME%"
              "routeName": "%ROUTE_NAME%"
```

2. apply following Telemetry API:

```console
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  accessLogging:
    - match:
        mode: SERVER
      providers:
        - name: inbound
    - match:
        mode: CLIENT
      providers:
        - name: outbound
```
