### ISSUE TITLE
Backoff_retries not working After right configuration.

### ISSUE THREAD

**Issue by gmeher** [istio/istio#42246]
### Bug Description

I created a sample app with following Virtual service and envoyFilter
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: playlists-api
spec:
  hosts:
  -  playlists-api
  http:
  - name: playlists-api
    route:
    - destination:
        host: playlists-api
    retries:
      attempts: 5
      perTryTimeout: 2s
```

envoyFilter:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: retry-interval
spec:
  workloadSelector:
    labels:
      app: playlists-api
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: SIDECAR_OUTBOUND
    patch:
      operation: MERGE
      value:
        name: envoy.filter.retry
        typed_config: 
          '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
        route:
          retry_policy:
            retry_back_off:
              base_interval: 4s
              max_interval: 40s
```

I can see the applied config to side using istioctl
```
            {
                "name": "playlists-api.default.svc.cluster.local:80",
                "domains": [
                    "playlists-api.default.svc.cluster.local",
                    "playlists-api",
                    "playlists-api.default.svc",
                    "playlists-api.default",
                    "10.96.108.156"
                ],
                "routes": [
                    {
                        "name": "playlists-api",
                        "match": {
                            "prefix": "/"
                        },
                        "route": {
                            "cluster": "outbound|80||playlists-api.default.svc.cluster.local",
                            "timeout": "0s",
                            "retryPolicy": {
                                "retryOn": "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes",
                                "numRetries": 5,
                                "perTryTimeout": "2s",
                                "retryHostPredicate": [
                                    {
                                        "name": "envoy.retry_host_predicates.previous_hosts",
                                        "typedConfig": {
                                            "@type": "type.googleapis.com/envoy.extensions.retry.host.previous_hosts.v3.PreviousHostsPredicate"
                                        }
                                    }
                                ],
                                "hostSelectionRetryMaxAttempts": "5",
                                "retriableStatusCodes": [
                                    503
                                ],
                                "retryBackOff": {
                                    "baseInterval": "4s",
                                    "maxInterval": "40s"
                                }
                            },
                            "maxStreamDuration": {
                                "maxStreamDuration": "0s",
                                "grpcTimeoutHeaderMax": "0s"
                            }
                        },
                        "metadata": {
                            "filterMetadata": {
                                "istio": {
                                    "config": "/apis/networking.istio.io/v1alpha3/namespaces/default/virtual-service/playlists-api"
                                }
                            }
                        },
                        "decorator": {
                            "operation": "playlists-api.default.svc.cluster.local:80/*"
                        }
                    }
                ],
                "includeRequestAttemptCount": true
            }
```

When I ping the service from another pod. using
```
curl http://playlists-api/
```
I see it retries for 5 times but without back_off or Jitter.

### Version

```prose
istioctl version
client version: 1.16.0
control plane version: 1.16.0
data plane version: 1.16.0 (5 proxies)

kubectl version --short
Client Version: v1.25.2
Kustomize Version: v4.5.7
Server Version: v1.25.2
```
