### ISSUE TITLE
EnvoyFilter for CLUSTER / transport_socket won't override the existing transport socket making it impossible to talk proxy_protocol to upstream

### ISSUE THREAD

**Issue by farcaller** [istio/istio#42257]
### Bug Description

I want to patch the ingress cluster configuration to use `envoy.transport_sockets.upstream_proxy_protocol`.

Supposedly, that would be achieved by replacing the `tlsMode-disabled` configuration in `transport_socket_matches` (the destination doesn't have a sidecar)

original:
```yaml
- name: tlsMode-istio
  ...
- name: tlsMode-disabled
  match: {}
  transport_socket:
    name: envoy.transport_sockets.raw_buffer
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.transport_sockets.raw_buffer.v3.RawBuffer
```

with:
```yaml
- name: tlsMode-istio
  ...
- name: tlsMode-disabled
  match: {}
  transport_socket:
    name: envoy.transport_sockets.upstream_proxy_protocol
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.transport_sockets.proxy_protocol.v3.ProxyProtocolUpstreamTransport
      config:
        version: V2
      transport_socket:
        name: "envoy.transport_sockets.raw_buffer"
```

The problem is that the cluster merger doesn't handle that use case properly.

First, it will only support a [MERGE operation](https://sourcegraph.com/github.com/istio/istio@1.16.0/-/blob/pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go?L48).

Second, it has a [special case handling](https://sourcegraph.com/github.com/istio/istio@1.16.0/-/blob/pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go?L87) for the transport_socket, but it tries to match on the transport socket name, not the transport_socket_matches. This only allows to modify the existing configuration for `envoy.transport_sockets.raw_buffer`.

Failing to handle that logic by supplying a `transport_socket`, the only alternative is to supply `transport_socket_matches` instead. Unfortunately, the default merge algorithm (and the only one used) will append the configuration, meaning there will be two `tlsMode-disabled` and the first one will always match.

While there are other mechanisms to pass the source IP, proxy protocol is the only option if istio doesn't terminate tls.

Expected behavior:

If the patch contains `transport_socket_matches` it should be special-cased as well and perform the merging based on the name (that might as well be the REPLACE operation at that point).

### Version

This is a source issue first noticed in 1.16.0. [It was known to work](https://discuss.istio.io/t/enable-proxy-protocol-from-istio-to-upstreams/10321) around istio 1.8.5.

### Additional Information

N/A

**Comment by klarose** [comment]
I am also running in to this. I'm sni routing a TLS session to a pod, and want to use proxy-protocol so it can see the original IP address. Unfortunately I cannot figure out how to get this to work.

**Comment by klarose** [comment]
I was able to get this to work by adding an entirely new static cluster. E.g.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: proxy-protocol-v1
  namespace: istio-system
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      context: GATEWAY
    patch:
        operation: ADD
        value:
              circuitBreakers:
                thresholds:
                - maxConnections: 4294967295
                  maxPendingRequests: 4294967295
                  maxRequests: 4294967295
                  maxRetries: 4294967295
                  trackRemaining: true
              commonLbConfig:
                healthyPanicThreshold: {}
                localityWeightedLbConfig: {}
              connectTimeout: 1.500s
              edsClusterConfig:
                edsConfig:
                  ads: {}
                  initialFetchTimeout: 0s
                  resourceApiVersion: V3
                serviceName: outbound|5002||my-service.namespace.svc.cluster.local
              filters:
              - name: istio.metadata_exchange
                typedConfig:
                  '@type': type.googleapis.com/envoy.tcp.metadataexchange.config.MetadataExchange
                  protocol: istio-peer-exchange
              lbPolicy: LEAST_REQUEST
              metadata:
                filterMetadata:
                  istio:
                    config: /apis/networking.istio.io/v1alpha3/namespaces/namespace/destination-rule/my-service-dr
                    default_original_port: 5002
                    services:
                    - host: my-service-pp.namespace.svc.cluster.local
                      name: my-service-pp
                      namespace: namespace
              name: outbound|5002||my-service-pp.namespace.svc.cluster.local
              outlierDetection:
                baseEjectionTime: 2s
                consecutiveGatewayFailure: 3
                enforcingConsecutiveGatewayFailure: 100
                enforcingSuccessRate: 0
                interval: 5s
                maxEjectionPercent: 50
              transportSocketMatches:
              - match: {}
                name: tlsMode-disabled
                transportSocket:
                  name: envoy.transport_sockets.upstream_proxy_protocol
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.transport_sockets.proxy_protocol.v3.ProxyProtocolUpstreamTransport
                    config:
                      version: V1
                    transport_socket:
                      name: "envoy.transport_sockets.raw_buffer"
              type: EDS
  workloadSelector:
    labels:
      app: istio-ingressgateway

```

This is not really a log-term solution though. It's extremely fragile, and basically breaks the istio config model. I'd really like to see this properly implemented/the existing filter approaches fixed. I think ideally we would have two options: 
 - give the ability to set the base transportSocket, overriding the transportSocketMatches, which works well when there's no sidecar,
 -  or when there is a sidecar, enhance the source ip detection to extract the IP address from the mtls source.ip attribute, and have the sidecar inject the proxy protocol. This would be nice since then we could continue to use mtls authz policy and so on.
