### ISSUE TITLE
Not able to install istio with this serviceAnnotation

### ISSUE THREAD

**Issue by ms8527** [istio/istio#42251]
### Bug Description

I am trying to generate Istio 1.16.0  manifest using demo profile and by setting the following serviceAnnotation. 

`istioctl manifest generate --set profile=demo --set values.gateways.istio-ingressgateway.serviceAnnotations.service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags='Application=istio-eks, ApplicationGroup=istio-eks' `

But getting the following error 
`Error: set flag values.gateways.istio-ingressgateway.serviceAnnotations.service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags=Application=istio-eks has incorrect format, must be path=value``

It looks like Istio is splitting the value on the basis of = , as a result the value containing = is causing the problem.
I can update the demo.yaml config manually and can add this serviceAnnotation patch but I need to do this using istioctl for my automation

### Version

```prose
istioctl version          
client version: 1.16.0
control plane version: 1.16.0
data plane version: 1.16.0 (24 proxies)

kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.3
Kustomize Version: v4.5.4
Server Version: v1.21.14-eks-fb459a0
```

**Comment by howardjohn** [comment]
I think there's a way to escape it but save yourself the headache and use `-f` to pass in a yaml file input.. much simpler

**Comment by ms8527** [comment]
@howardjohn I can use -f . But I am writing an automation script in which I am trying  to install Istio with having those ServiceAnnotations be already there. I tried to escape `=` but thats not working

**Comment by j2gg0s** [comment]
> istioctl manifest generate --set profile=demo --set values.gateways.istio-ingressgateway.serviceAnnotations.service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags='Application=istio-eks, ApplicationGroup=istio-eks'

helm's --set is diffecult to used in shell script, istioctl also

**Comment by ms8527** [comment]
@howardjohn @j2gg0s 
Can I use Kustomize to modify the demo , default profile yaml file (like I want to patch serviceAnnotations before installiong istio) and then once its modified I can then install istio with those updated profiles?

**Comment by j2gg0s** [comment]
Istio allow you add service annotations to gateway when installed, like this. We use helm template to manage different profile for different environment. Kustomize should can do this too, but im not familiar with it.
```
# Source: istio-control/templates/istio.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: example
  namespace: istio-system
spec:
  ingressGateways:
  - name: istio-ingressgateway
    enabled: true
    k8s:
      serviceAnnotations:
        service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: 'Application=istio-eks, ApplicationGroup=istio-eks'
```
