### ISSUE TITLE
istio ingress-gateway with port 25

### ISSUE THREAD

**Issue by Rez0k** [istio/istio#42303]
Hi,

I am working with istio for a while with aws eks.
Now i have been asked to support port 25 on our application.
I created an ingress-gateway and modified the helm chart service to work with nlb and with port 25.
Everything I tried didn't work. it seems envoy doesn't listen to this port no matter what I do.

config files:
```
kind: Gateway
apiVersion: networking.istio.io/v1beta1
metadata:
  name: tcp-gateway
spec:
  servers:
    - port:
        number: 25
        protocol: TCP
        name: tcp
      hosts:
        - '*'
  selector:
    istio: tcp-ingressgateway
``` 

```
kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: example-service
spec:
  hosts:
    - example-service
  gateways:
    - tcp-gateway
  http:
    - route:
        - destination:
            host: example-service
            port:
              number: 25
```

![image](https://user-images.githubusercontent.com/23296337/205901270-ea43c338-836c-4ed8-ad7b-d6d507433bf5.png)

in the image you can see that there is no listener for port 25 but if I create other custom ports like: 8090 it will be created.
any insight?

Thanks!

**Comment by Rez0k** [comment]
fixed my issue by changing
```
kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: example-service
spec:
  hosts:
    - example-service
  gateways:
    - tcp-gateway
  http:
    - route:
        - destination:
            host: example-service
            port:
              number: 25
```

to:
```
kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: example-service
spec:
  hosts:
    - example-service
  gateways:
    - tcp-gateway
  tcp:
    - match
      - port: 25
    - route:
        - destination:
            host: example-service
            port:
              number: 25
```
