### ISSUE TITLE
AuthorizationPolicy field not work because of principal not found

### ISSUE THREAD

**Issue by hanxiaop** [istio/istio#42332]
### Bug Description

Tried the spec below:
```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: service
  namespace: ns1
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces:
        - ns1
    to:
    - operation:
        ports:
        - "8080"
  - to:
    - operation:
        paths:
        - /metrics
        ports:
        - "8080"
```
however it does not work. 
The same configuration works on version 1.15.3.

Suspect that there's some impacts after https://github.com/istio/istio/pull/42031 get merged, and the configuration becomes different which causes the bug.

### Version

```prose
master branch
```
