### ISSUE TITLE
Ambient support for redhat openshift

### ISSUE THREAD

**Issue by linsun** [istio/istio#42341]
Would be nice for IBM/Redhat team to step in and contribute an ambient openshift profile when ambient is merged to upstream, similar like the openshift profile today.

**Comment by jewertow** [comment]
The tricky part of ambient mode on OpenShift is installation of ztunnel, which requires NET_ADMIN capabilities, so `privileged` SCC must be added to istio-system (`oc adm policy add-scc-to-group privileged system:serviceaccounts:istio-system`).

I wonder if we could install ztunnel in kube-system namespace, where we can install privileged workload out of the box?
Then the only missing part would be creating `istio-ca-root-cert` config map in that namespace, which is required by ztunnel.

What do you think @howardjohn @jwendell @morvencao?

PoC:
```
cat <<EOF >> control-plane.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: control-plane
spec:
  hub: quay.io/jewertow
  tag: 1.18-latest
  profile: ambient
  components:
    cni:
      enabled: true
      namespace: kube-system
    ztunnel:
      enabled: true
      namespace: kube-system
  values:
    cni:
      cniBinDir: /var/lib/cni/bin
      cniConfDir: /etc/cni/multus/net.d
      chained: false
      cniConfFileName: "istio-cni.conf"
      excludeNamespaces:
       - istio-system
       - kube-system
      logLevel: info
      privileged: true
    sidecarInjectorWebhook:
      injectedAnnotations:
        k8s.v1.cni.cncf.io/networks: istio-cni
EOF
oc adm policy add-scc-to-group anyuid system:serviceaccounts:istio-system
istioctl install -y -n istio-system -f control-plane.yaml
// ztunnel will fail to start, so create missing config map manually
oc get cm istio-ca-root-cert -n istio-system -o json | jq -r '.data."root-cert.pem"' > root-cert.pem
oc create cm istio-ca-root-cert -n kube-system --from-file=root-cert.pem
```
