### ISSUE TITLE
Support hostname for TCP egress rules

### ISSUE THREAD

**Issue by dtzar** [istio/istio#4236]
[Per the documentation](https://istio.io/docs/tasks/traffic-management/egress-tcp.html#using-istio-egress-rules-for-external-tcp-traffic), it is required to specify CIDR IP address blocks to allow containers in the pod to bypass the sidecar for tcp-based egress traffic.  It is common for these requests to be directed at a URL where the IP address of that URL might change.  There is no reasonable automated way to check for the IP address changes in the URL and update / add egress rules.  This makes users be forced to [bypass the egress rules entirely](https://istio.io/docs/tasks/traffic-management/egress.html#calling-external-services-directly), losing the advantages of tracing/metrics and potentially making it less secure.  

Feature request would be to support url for tcp egress rules.

**Comment by ldemailly** [comment]
you mean dns resolution or name based  egress ?

if you want http (‘url’) it works with http egress as long as you don’t use https

**Comment by dtzar** [comment]
So are you saying that something like this would be supported?

```
kind: EgressRule
metadata:
  name: wikipedia-range2
spec:
  destination:
      service: mydatabaseconnection.cloudprovider.net
  ports:
      - port: 443
        protocol: tcp
```

**Comment by ldemailly** [comment]
I meant for "URL"s there is
https://istio.io/docs/tasks/traffic-management/egress.html#configuring-the-external-services

**Comment by vadimeisenbergibm** [comment]
Allowing external traffic to a DNS name via TCP can be achieved today with Kubernetes ExternalName Services - https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors.

@ijsnellf @frankbu @ldemailly we should decide what we do with the Egress Rules - do we continue to evolve them? Or do we recommend to switch to alpha 3 external services after 0.7?

**Comment by vadimeisenbergibm** [comment]
^ Note that you have to specify the port and the protocol (TCP) for the Kubernetes ExternalName Services to be addressable from Istio.

**Comment by dtzar** [comment]
@vadimeisenbergibm so are you saying that if we used the K8s `ExternalName` service, Istio would support an egress rule like the following?

```
kind: EgressRule
metadata:
  name: allow-db-service
spec:
  destination:
      service: myDatabaseExternalService.default.svc.cluster
  ports:
      - port: 443
        protocol: tcp
```
