### ISSUE TITLE
exact_balance specified in proxy metadata does not get applied to listeners

### ISSUE THREAD

**Issue by jacob-delgado** [istio/istio#42374]
### Bug Description

Possible regression for https://github.com/istio/istio/issues/18152

When using the following annotation on a deployment pod spec:

```yaml
      annotations:
        proxy.istio.io/config: |
          proxyMetadata:
            INBOUND_LISTENER_EXACT_BALANCE: "true"
            OUTBOUND_LISTENER_EXACT_BALANCE: "true"
```

I do not see the listener config being applied

```
connection_balance_config:
  exact_balance: {}
```

### Version

```prose
1.14+
```
