### ISSUE TITLE
Istio Low throughput with a single pod

### ISSUE THREAD

**Issue by acemaster** [istio/istio#42373]
### Bug Description

Setup:
We are running a few experiments on an Openshift cluster with 96 CPUs and 384 GB of memory. 
We are deploying 2 application
1. A hello-world Go application with one rest endpoint.
2. A workgenerator client that does load test on the application. (wrk2 [https://github.com/giltene/wrk2](https://github.com/giltene/wrk2))
YAML files for these are below.
Without Istio, the application was able to handle **182698** requests per second
After adding Istio, the throughput dropped significantly to **12383** requests per second. That is a throughput decline of over 10 times. 
I tried changing sidecar configuration, adding more CPU and memory to it, but it didn't help. 

Hello world yaml:
```
apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod-2
  labels:                  # You'll use labels A LOT w/ kube
    death-star-project: hotel-res
    app: hello-world       # They are useful for organizing and identifying attributes of an object
  namespace: hotel-res
#  annotations:
#    sidecar.istio.io/proxyCPU: 4000m
#    sidecar.istio.io/proxyCPULimit: 8000m
#    sidecar.istio.io/proxyMemory: 4Gi
#    sidecar.istio.io/proxyMemoryLimit: 8Gi
spec:
  containers:              # This spec has multiple containers, how fancy!
  - name: "k8s-hello-node"
    image: "rogertinsley/hello-world:v1"
    resources:
      requests:
        cpu: 16
        memory: 20Gi
---
kind: Service              # Services can expose pods to the public
apiVersion: v1
metadata:
  name: hello-world-svc
  labels:
    death-star-project: hotel-res
  namespace: hotel-res
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  selector:
    app: hello-world
  type: "ClusterIP"
```

Load Generator
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-client
  labels:
    death-star-project: hotel-res
    app: ubuntu-client
  namespace: hotel-res
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: hotel-res
      app: ubuntu-client
  template:
    metadata:
      labels: 
        death-star-project: hotel-res
        app: ubuntu-client
      name: ubuntu-client
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: hr-client
        image: ubuntu
        resources:
          requests:
            cpu: 2
            memory: 2Gi
        command:  ["/bin/sh", "-c"]
        args:
          - apt-get -y update &&
            apt-get -y upgrade &&
            apt-get -y install dnsutils git vim python3 python3-aiohttp libssl-dev libz-dev luarocks iputils-ping lynx build-essential gcc bash curl &&
            luarocks install luasocket &&
            sleep 365d
        imagePullPolicy: Always
        restartPolicy: Always
      imagePullSecrets:
        - name: regcred
```

Istio YAML file:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    base:
      enabled: true
    cni:
      enabled: true
      namespace: kube-system
    egressGateways:
    - enabled: false
      name: istio-egressgateway
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
    istiodRemote:
      enabled: false
    pilot:
      enabled: true
  hub: docker.io/istio
  meshConfig:
    defaultConfig:
      proxyMetadata: {}
    enablePrometheusMerge: true
  profile: openshift
  tag: 1.15.0
  values:
    base:
      enableCRDTemplates: false
      validationURL: ""
    cni:
      chained: false
      cniBinDir: /var/lib/cni/bin
      cniConfDir: /etc/cni/multus/net.d
      cniConfFileName: istio-cni.conf
      excludeNamespaces:
      - istio-system
      - kube-system
      logLevel: info
      privileged: true
    defaultRevision: ""
    gateways:
      istio-egressgateway:
        autoscaleEnabled: true
        env: {}
        name: istio-egressgateway
        secretVolumes:
        - mountPath: /etc/istio/egressgateway-certs
          name: egressgateway-certs
          secretName: istio-egressgateway-certs
        - mountPath: /etc/istio/egressgateway-ca-certs
          name: egressgateway-ca-certs
          secretName: istio-egressgateway-ca-certs
        type: ClusterIP
      istio-ingressgateway:
        autoscaleEnabled: true
        env: {}
        name: istio-ingressgateway
        secretVolumes:
        - mountPath: /etc/istio/ingressgateway-certs
          name: ingressgateway-certs
          secretName: istio-ingressgateway-certs
        - mountPath: /etc/istio/ingressgateway-ca-certs
          name: ingressgateway-ca-certs
          secretName: istio-ingressgateway-ca-certs
        type: LoadBalancer
    global:
      configValidation: true
      defaultNodeSelector: {}
      defaultPodDisruptionBudget:
        enabled: true
      defaultResources:
        requests:
          cpu: 10000m
      imagePullPolicy: "IfNotPresent"
      imagePullSecrets: []
      istioNamespace: istio-system
      istiod:
        enableAnalysis: false
      jwtPolicy: third-party-jwt
      logAsJson: false
      logging:
        level: default:info
      meshNetworks: {}
      mountMtlsCerts: false
      multiCluster:
        clusterName: ""
        enabled: false
      network: ""
      omitSidecarInjectorConfigMap: false
      oneNamespace: false
      operatorManageWebhooks: false
      pilotCertProvider: istiod
      priorityClassName: ""
      proxy:
        autoInject: enabled
        clusterDomain: cluster.local
        componentLogLevel: misc:error
        enableCoreDump: false
        excludeIPRanges: ""
        excludeInboundPorts: ""
        excludeOutboundPorts: ""
        image: proxyv2
        includeIPRanges: '*'
        logLevel: warning
        privileged: false
        readinessFailureThreshold: 30
        readinessInitialDelaySeconds: 1
        readinessPeriodSeconds: 2
        resources:
          limits:
            cpu: 12000m
            memory: 5Gi
          requests:
            cpu: 10000m
            memory: 2Gi
        statusPort: 15020
        tracer: zipkin
      proxy_init:
        image: proxyv2
        resources:
          limits:
            cpu: 12000m
            memory: 5Gi
          requests:
            cpu: 10000m
            memory: 2Gi
      sds:
        token:
          aud: istio-ca
      sts:
        servicePort: 0
      tracer:
        datadog: {}
        lightstep: {}
        stackdriver: {}
        zipkin: {}
      useMCP: false
    istiodRemote:
      injectionURL: ""
    pilot:
      autoscaleEnabled: true
      autoscaleMax: 5
      autoscaleMin: 1
      configMap: true
      cpu:
        targetAverageUtilization: 80
      enableProtocolSniffingForInbound: true
      enableProtocolSniffingForOutbound: true
      env: {}
      image: pilot
      keepaliveMaxServerConnectionAge: 30m
      nodeSelector: {}
      podLabels: {}
      replicaCount: 1
      traceSampling: 1
    sidecarInjectorWebhook:
      injectedAnnotations:
        k8s.v1.cni.cncf.io/networks: istio-cni
    telemetry:
      enabled: false
      v2:
        enabled: false
        metadataExchange:
          wasmEnabled: false
        prometheus:
          enabled: false
          wasmEnabled: false
        stackdriver:
          configOverride: {}
          enabled: false
          logging: false
          monitoring: false
          topology: false

### Version

```prose
client version: 1.15.0
control plane version: 1.15.0
data plane version: 1.15.0 (2 proxies)
```
