### ISSUE TITLE
Setting Envoy SocketAddress ipv4_compat breaks Service Entries

### ISSUE THREAD

**Issue by dmorina** [istio/istio#42376]
### Bug Description

We have an IPv6 only Kubernetes cluster which is capable of talking to IPv4 endpoints, we attempted to make Envoy listen for IPv4 traffic as well by adding a filter like so (docs https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/address.proto): 

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ipv4-compat
  namespace: istio-system
spec:
  configPatches:
    - applyTo: LISTENER
      match:
        context: SIDECAR_OUTBOUND
        listener:
          name: virtualOutbound
          portNumber: 15001
      patch:
        operation: MERGE
        value:
          address:
            socket_address:
              ipv4_compat: true
```

We also configured dns64 via CoreDNS as follows 
```
dns64 0:0:0:0:0:ffff::/96 {
  translate_all
}
```

Now with that in place Istio is treating TLS ServiceEntries in a very strange way, if you have more than one host for the same port (e.g. 443) then Istio will pick a random host (or first one that it finds) and it will only add a filter for that and all other endpoints will break.

Proxy config for the listeners on port 443 looks like this:
```
{
        "name": "0.0.0.0_443",
        "address": {
            "socketAddress": {
                "address": "0.0.0.0",
                "portValue": 443
            }
        },
        "filterChains": [
            {
                "filters": [
                    {
                        "name": "istio.stats",
                        "typedConfig": {
                            "@type": "type.googleapis.com/udpa.type.v1.TypedStruct",
                            "typeUrl": "type.googleapis.com/envoy.extensions.filters.network.wasm.v3.Wasm",
                            "value": {
                                "config": {
                                    "configuration": {
                                        "@type": "type.googleapis.com/google.protobuf.StringValue",
                                        "value": "{\"disable_host_header_fallback\":true}\n"
                                    },
                                    "root_id": "stats_outbound",
                                    "vm_config": {
                                        "code": {
                                            "local": {
                                                "inline_string": "envoy.wasm.stats"
                                            }
                                        },
                                        "runtime": "envoy.wasm.runtime.null",
                                        "vm_id": "tcp_stats_outbound"
                                    }
                                }
                            }
                        }
                    },
                    {
                        "name": "envoy.filters.network.tcp_proxy",
                        "typedConfig": {
                            "@type": "type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy",
                            "statPrefix": "outbound|443||autoscaling.us-east-1.amazonaws.com",
                            "cluster": "outbound|443||autoscaling.us-east-1.amazonaws.com",
                            "accessLog": [
                                {
                                    "name": "envoy.access_loggers.file",
                                    "typedConfig": {
                                        "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog",
                                        "path": "/dev/stdout",
                                        "logFormat": {
                                            "jsonFormat": {
                                                // omitted
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                ]
            }
        ],
        "trafficDirection": "OUTBOUND",
        "accessLog": [
            {
                "name": "envoy.access_loggers.file",
                "filter": {
                    "responseFlagFilter": {
                        "flags": [
                            "NR"
                        ]
                    }
                },
                "typedConfig": {
                    "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog",
                    "path": "/dev/stdout",
                    "logFormat": {
                        "jsonFormat": {
                            // omitted 
                        }
                    }
                }
            }
        ],
        "bindToPort": false
    }
```

Sample ServiceEntries 

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: aws-services
  namespace: istio-system
spec:
  hosts:
  - ecr.us-east-1.amazonaws.com
  - ecr.us-west-1.amazonaws.com
  - ecr.us-west-2.amazonaws.com
  - api.ecr.us-east-1.amazonaws.com
  - api.ecr.us-west-1.amazonaws.com
  - api.ecr.us-west-2.amazonaws.com
  - sts.us-east-1.amazonaws.com
  - sts.us-west-1.amazonaws.com
  - sts.us-west-2.amazonaws.com
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
  location: MESH_EXTERNAL
```

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: autoscaling.us-east-1.amazonaws.com
  namespace: test-namespace
spec:
  hosts:
    - autoscaling.us-east-1.amazonaws.com
  location: MESH_EXTERNAL
  ports:
    - number: 443
      name: https
      protocol: HTTPS
  resolution: DNS
```

Logs from the proxy when attempting to connect to `sts.us-east-1.amazonaws.com` for example:
```
SSL validation failed for https://sts.us-east-1.amazonaws.com/ ("hostname 'sts.us-east-1.amazonaws.com' doesn't match either of 'autoscaling.us-east-1.amazonaws.com', 'us-east-1.autoscaling.amazonaws.com', 'autoscaling.amazonaws.com', 'application-autoscaling.us-east-1.amazonaws.com', 'autoscaling-plans.us-east-1.amazonaws.com', '*.autoscaling.us-east-1.vpce.amazonaws.com', '*.application-autoscaling.us-east-1.vpce.amazonaws.com', '*.autoscaling-plans.us-east-1.vpce.amazonaws.com'",)
```

Any idea why Istio is behaving like this?

### Version

```prose
Kubernetes 1.22
Istio 1.15.3 and 1.16.0
```
