### ISSUE TITLE
Register postgres proxy filter API in Istio

### ISSUE THREAD

**Issue by caoyukun0430** [istio/istio#42380]
**Describe the feature request**
We are using istio 1.15 and envoy 1.24.
Months ago istio started [add support for start tls mode](https://github.com/istio/istio/pull/37290#top) #37290  BUT it's closed due to envoy is still developing postgres filter. 

Now postgres filter is developed in envoy https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/postgres_proxy_filter.html But we believe the Postgres proxy filter API is not yet registered inside Isito. So when we trying to apply postgres proxy filter in istio using envoyfilter, we saw the error complaining that **Didn't find a registered implementation for name: 'envoy.extensions.filters.network.postgres_proxy'**

Here is the envoyfilter we tried to add:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: starttlsnew-cm
spec:
  workloadSelector:
   labels:
     app: client-manager
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: SIDECAR_OUTBOUND
      listener:
        portNumber: 5432
        filterChain:
          filter:
            name: "envoy.filters.network.tcp_proxy"
    patch:
      operation: INSERT_BEFORE
      value:
        name: "envoy.extensions.filters.network.postgres_proxy"
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.postgres_proxy.v3alpha.PostgresProxy"
```

Here is the error we see from istiod and proxy sidecar:
```
###istiod log
2022-12-09T13:50:12.728164Z	warn	ads	ADS:LDS: ACK ERROR client-manager-5c8d7c6c89-xflsg.istio-system-1 Internal:Error adding/updating listener(s) 0.0.0.0_5432: Didn't find a registered implementation for name: 'envoy.extensions.filters.network.postgres_proxy'
10.109.114.229_5432: Didn't find a registered implementation for name: 'envoy.extensions.filters.network.postgres_proxy'
10.108.154.164_5432: Didn't find a registered implementation for name: 'envoy.extensions.filters.network.postgres_proxy'

###proxy log
[libprotobuf WARNING external/com_google_protobuf/src/google/protobuf/text_format.cc:2139] Can't print proto content: proto type type.googleapis.com/envoy.extensions.filters.network.postgres_proxy.v3alpha.PostgresProxy not found
[libprotobuf WARNING external/com_google_protobuf/src/google/protobuf/text_format.cc:2139] Can't print proto content: proto type type.googleapis.com/envoy.extensions.filters.network.postgres_proxy.v3alpha.PostgresProxy not found
[libprotobuf WARNING external/com_google_protobuf/src/google/protobuf/text_format.cc:2139] Can't print proto content: proto type type.googleapis.com/envoy.extensions.filters.network.postgres_proxy.v3alpha.PostgresProxy not found
[libprotobuf WARNING external/com_google_protobuf/src/google/protobuf/text_format.cc:2139] Can't print proto content: proto type type.googleapis.com/envoy.extensions.filters.network.postgres_proxy.v3alpha.PostgresProxy not found
[libprotobuf WARNING external/com_google_protobuf/src/google/protobuf/text_format.cc:2139] Can't print proto content: proto type type.googleapis.com/envoy.extensions.filters.network.postgres_proxy.v3alpha.PostgresProxy not found
[libprotobuf WARNING external/com_google_protobuf/src/google/protobuf/text_format.cc:2139] Can't print proto content: proto type type.googleapis.com/envoy.extensions.filters.network.postgres_proxy.v3alpha.PostgresProxy not found
2022-12-09T13:50:12.727676Z	warning	envoy config	gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_5432: Didn't find a registered implementation for name: 'envoy.extensions.filters.network.postgres_proxy'
10.109.114.229_5432: Didn't find a registered implementation for name: 'envoy.extensions.filters.network.postgres_proxy'
10.108.154.164_5432: Didn't find a registered implementation for name: 'envoy.extensions.filters.network.postgres_proxy'
```

Please help to register  Postgres proxy filter API in istio so that we can at least use it in Istio.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
