### ISSUE TITLE
Connection failure when initiating from pod running on the same host as istio ingress gateway

### ISSUE THREAD

**Issue by Ruckus0143** [istio/istio#42392]
### Bug Description

This was observed consistently on EKS and Istio providing ingress service, deployed with default profile and NLB set as internal. Application pods that are running on the same host as istio-ingressgateway pod cannot complete successful connection through NLB:

```
istio-proxy@istio-ingressgateway-7867fdc898-9ndz7:/$ INGRESS=a8aaa72d56ee9460bb89928f3f08afe7-af6797483135fb2c.elb.us-east-1.amazonaws.com
istio-proxy@istio-ingressgateway-7867fdc898-9ndz7:/$ while true; do curl -k https://$INGRESS/productpage > /dev/null; done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:09 --:--:--     0
curl: (28) Failed to connect to a8aaa72d56ee9460bb89928f3f08afe7-af6797483135fb2c.elb.us-east-1.amazonaws.com port 443: Connection timed out
```

Same test succeeds if connection attempt is initiated from any other pod that resides on nodes without ingress pod:

```
I have no name!@reviews-v2-68b8bc8647-jdcrf:/$ INGRESS=a8aaa72d56ee9460bb89928f3f08afe7-af6797483135fb2c.elb.us-east-1.amazonaws.com
I have no name!@reviews-v2-68b8bc8647-jdcrf:/$ while true; do curl -k https://$INGRESS/productpage > /dev/null; done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5290  100  5290    0     0   103k      0 --:--:-- --:--:-- --:--:--  105k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4293  100  4293    0     0  81000      0 --:--:-- --:--:-- --:--:-- 81000
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5294  100  5294    0     0    99k      0 --:--:-- --:--:-- --:--:--   99k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
.
.
.
```

Relevant Istio install options:
```
istioctl install --set profile=default \
  --set 'values.gateways.istio-ingressgateway.serviceAnnotations.service\.beta\.kubernetes\.io/aws-load-balancer-type=nlb' \
  --set 'values.gateways.istio-ingressgateway.serviceAnnotations.service\.beta\.kubernetes\.io/aws-load-balancer-internal="true"'
```

Test application

```
kubectl apply -f https://raw.githubusercontent.com/istio/istio/master/samples/bookinfo/platform/kube/bookinfo.yaml -n default
```

Gateway/VirtualService

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: mygateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - a8aaa72d56ee9460bb89928f3f08afe7-af6797483135fb2c.elb.us-east-1.amazonaws.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: httpbin-credential
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: bookinfo
  namespace: default
spec:
  gateways:
  - istio-system/mygateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: 9080
```

[bug-report.tar.gz](https://github.com/istio/istio/files/10201333/bug-report.tar.gz)

### Version

```prose
istioctl version
client version: 1.14.5
control plane version: 1.14.5
data plane version: 1.14.5 (1 proxies)

kubectl version --short
Client Version: v1.23.7-eks-4721010
Server Version: v1.24.7-eks-fb459a0
```
