### ISSUE TITLE
k8s service exportTo annotation not working on gateways

### ISSUE THREAD

**Issue by nmnellis** [istio/istio#42400]
### Bug Description

in previous versions of istio you could add `exportTo` annotation to a Kubernetes service and it would be removed from service discovery on gateways.  Not it appears the annotation does not work in gateways in 1.16

Example
```yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    service: frontend
  annotations:
    networking.istio.io/exportTo: "."
spec:
  ports:
  - port: 8080
    name: http
  - port: 9080
    name: http2-grpc
  selector:
    app: frontend
    version: v1
```

```sh
▶ istioctl pc cluster deploy/istio-ingressgateway.istio-system
SERVICE FQDN                                            PORT      SUBSET     DIRECTION     TYPE           DESTINATION RULE
BlackHoleCluster                                        -         -          -             STATIC         
agent                                                   -         -          -             STATIC         
frontend.app.svc.cluster.local                          8080      -          outbound      EDS            
frontend.app.svc.cluster.local                          9080      -          outbound      EDS            
istio-egressgateway.istio-system.svc.cluster.local      80        -          outbound      EDS            
istio-egressgateway.istio-system.svc.cluster.local      443       -          outbound      EDS            
istio-ingressgateway.istio-system.svc.cluster.local     80        -          outbound      EDS            
istio-ingressgateway.istio-system.svc.cluster.local     443       -          outbound      EDS            
istio-ingressgateway.istio-system.svc.cluster.local     15021     -          outbound      EDS            
istio-ingressgateway.istio-system.svc.cluster.local     15443     -          outbound      EDS            
istio-ingressgateway.istio-system.svc.cluster.local     31400     -          outbound      EDS            
istiod.istio-system.svc.cluster.local                   443       -          outbound      EDS            
istiod.istio-system.svc.cluster.local                   15010     -          outbound      EDS            
istiod.istio-system.svc.cluster.local                   15012     -          outbound      EDS            
istiod.istio-system.svc.cluster.local                   15014     -          outbound      EDS            
kube-dns.kube-system.svc.cluster.local                  53        -          outbound      EDS            
kube-dns.kube-system.svc.cluster.local                  9153      -          outbound      EDS            
kubernetes.default.svc.cluster.local                    443       -          outbound      EDS            
metrics-server.kube-system.svc.cluster.local            443       -          outbound      EDS            
prometheus_stats                                        -         -          -             STATIC         
sds-grpc                                                -         -          -             STATIC         
xds-grpc                                                -         -          -             STATIC         
zipkin                                                  -         -          -             STRICT_DNS     
```

Steps to reproduce
```sh
istioctl install -y --set profile=demo

kubectl create ns app

kubectl label ns app istio-injection=enabled

kubectl apply -f app.yaml -n app

istioctl pc cluster deploy/istio-ingressgateway.istio-system | grep frontend

kubectl apply -n app -f - <<EOF
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    service: frontend
  annotations:
    networking.istio.io/exportTo: "."
spec:
  ports:
  - port: 8080
    name: http
  - port: 9080
    name: http2-grpc
  selector:
    app: frontend
    version: v1
EOF


istioctl pc cluster deploy/istio-ingressgateway.istio-system
```

app.yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    service: frontend
spec:
  ports:
  - port: 8080
    name: http
  - port: 9080
    name: http2-grpc
  selector:
    app: frontend
    version: v1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  labels:
    account: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-v1
  labels:
    app: frontend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: v1
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      serviceAccountName: frontend
      containers:
      - name: frontend
        image: ghcr.io/nmnellis/istio-echo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        args:
          - --name
          - frontend-v1
          - --port
          - "8080"
          - grpc
          - "9080"
          - --version
          - v1
          - --cluster
          - cluster-1
```

### Version

```prose
▶ istioctl version
client version: 1.16.0
control plane version: 1.16.0
data plane version: 1.16.0 (3 proxies)
```

### Additional Information

[bug-report.tar.gz](https://github.com/istio/istio/files/10210372/bug-report.tar.gz)
