### ISSUE TITLE
Trace outgoing http calls from a WASM plugin 

### ISSUE THREAD

**Issue by Hoferl** [istio/istio#42426]
Hi, I am trying to setup distributed tracing, but I am struggling with the setup for my WASM plugins.

Outgoing HTTP calls from the WASM plugins (via _DispatchHttpCall_) in the Istio Ingress Gateway are not traced correctly.
It seems like while these calls do get tracing information, they are not correlated to the original request. They get a new trace id and because of that there are now multiple traces for one request.

I thought about propagating the trace information manually in the WASM plugin to prevent the creation of a new trace id and hoped some generated B3 header (or similar) would have been added to the request at that point and I can just append them to the outgoing call. But there is no trace information whatsoever available during plugin runtime. The only related header I get is the `x-request-id` header and propagating it doesn´t help.

I wonder if I am missing something, how do I get the WASM calls to be part of the original request´s trace?

My Istio version is **1.14.5**.
My Global Mesh options:
```
defaultConfig:
  proxyMetadata:
    ISTIO_META_DNS_CAPTURE: "true"
  tracing:
    sampling: 100
    openCensusAgent:
      address: "grafana-agent.grafana-agent.svc.cluster.local:55678"
enableTracing: true
```
