### ISSUE TITLE
customize metrics for istio_requests_total does not work.

### ISSUE THREAD

**Issue by johnzheng1975** [istio/istio#42429]
### Bug Description

Per https://events.istio.io/istiocon-2022/sessions/understanding-the-new-istio-telemetry-api/, istio should support customize istio_requests_total, like adding request_method in metrics. However, not work in my try.

Step 1: Install Istio 1.15.3
Step 2: Prepare test app
```
  k apply -f samples/httpbin/httpbin-gateway.yaml
  k apply -f samples/httpbin/httpbin.yaml
  k apply -f samples/sleep/sleep.yaml
```
Step 3: Prepare the telemetry
```
$ k get telemetries.telemetry.istio.io -A -oyaml
apiVersion: v1
items:
- apiVersion: telemetry.istio.io/v1alpha1
  kind: Telemetry
  metadata:
    name: namespace-metrics
    namespace: default
  spec:
    metrics:
    - overrides:
      - tagOverrides:
          response_method:
            value: request.method
      providers:
      - name: prometheus
```
Step 4: Delete all existed envoy-filter
```
k delete envoyfilter -n istio-system --all
```
Step 5: Edit http bin, add annotations of extratag.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: default
spec:
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/extraStatTags: request_method
      labels:
        app: httpbin
        version: v1
    spec:
      containers:
      - image: docker.io/kennethreitz/httpbin
        name: httpbin
        ports:
        - containerPort: 80
          protocol: TCP
      serviceAccount: httpbin
      serviceAccountName: httpbin
```
Step 6: Test as below:
```
  k port-forward deploy/httpbin 15000:15000
  k exec -ti deploy/sleep  -- curl httpbin:8000/put  -XPUT
```

Expect result: should like:
istio_requests_total{response_code="200",request_method="PUT" ... ..}

Actual result:  response_method___PUT___istio_requests_total
```
response_method___PUT___istio_requests_total{response_code="200",reporter="destination",source_workload="sleep",source_workload_namespace="default",source_principal="spiffe://cluster.local/ns/default/sa/sleep",source_app="sleep",source_version="unknown",source_cluster="Kubernetes",destination_workload="httpbin",destination_workload_namespace="default",destination_principal="spiffe://cluster.local/ns/default/sa/httpbin",destination_app="httpbin",destination_version="v1",destination_service="httpbin.default.svc.cluster.local",destination_service_name="httpbin",destination_service_namespace="default",destination_cluster="Kubernetes",request_protocol="http",response_flags="-",grpc_response_status="",connection_security_policy="mutual_tls",source_canonical_service="sleep",destination_canonical_service="httpbin",source_canonical_revision="latest",destination_canonical_revision="v1"} 1
```

### Version

```prose
$ ./istioctl version
client version: 1.15.3
control plane version: 1.15.3
data plane version: 1.15.3 (3 proxies)

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.13-eks-fb459a0", GitCommit:"55bd5d5cb7d32bc35e4e050f536181196fb8c6f7", GitTreeState:"clean", BuildDate:"2022-10-24T20:35:40Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by zirain** [comment]
https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/#enable-custom-metrics

**Comment by johnzheng1975** [comment]
Yes,, please view step 5:    
    metadata:
      annotations:
        sidecar.istio.io/extraStatTags: request_method

**Comment by johnzheng1975** [comment]
Others, FYI
```
$ k get cm -n istio-system  istio -oyaml
apiVersion: v1
data:
  mesh: |-
    accessLogFile: /dev/stdout
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      proxyMetadata: {}
      tracing:
        max_path_tag_length: 99999
        sampling: 100
        zipkin:
          address: $(HOST_IP):9411
    enablePrometheusMerge: true
    enableTracing: true
    rootNamespace: istio-system
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
kind: ConfigMap

$ k get envoyfilter -A
No resources found

```

**Comment by johnzheng1975** [comment]
[istioctl_pc_listener_httpbin.yaml.log](https://github.com/istio/istio/files/10223984/istioctl_pc_listener_httpbin.yaml.log)

**Comment by zirain** [comment]
istioctl pc all would be helpful

**Comment by zirain** [comment]
be careful of your input:

```
    - overrides:
      - tagOverrides:
          response_method:
            value: request.method

sidecar.istio.io/extraStatTags: request_method
```

**Comment by johnzheng1975** [comment]
Thanks @zirain  so much. 
It is caused by my typo, not a defect. Sorry. 
After change, it works perfectly.
Now, I can change metrics add request_host/request_path/request_method. And alert based on this also. (Currently, I alert based on access_log ~_~)

**Comment by johnzheng1975** [comment]
With that, test result is perfect:
```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: namespace-metrics
  namespace: default
spec:
  metrics:
  - providers:
    - name: prometheus
    overrides:
    - tagOverrides:
        request_host:
          value: request.host
        request_method:
          value: request.method
        request_path:
          value: request.path
```

Change httpbin deploy, add extraStatTags annotations
  ```
  spec:
    template:
      metadata:
        annotations:
  ```
 $ curl localhost:15000/stats/prometheus  | grep "istio_requests_total"
```
istio_requests_total{response_code="200",reporter="destination",source_workload="sleep",source_workload_namespace="default",source_principal="spiffe://cluster.local/ns/default/sa/sleep",source_app="sleep",source_version="unknown",source_cluster="Kubernetes",destination_workload="httpbin",destination_workload_namespace="default",destination_principal="spiffe://cluster.local/ns/default/sa/httpbin",destination_app="httpbin",destination_version="v1",destination_service="httpbin.default.svc.cluster.local",destination_service_name="httpbin",destination_service_namespace="default",destination_cluster="Kubernetes",request_protocol="http",request_host="httpbin:8000",response_flags="-",grpc_response_status="",connection_security_policy="mutual_tls",source_canonical_service="sleep",destination_canonical_service="httpbin",source_canonical_revision="latest",destination_canonical_revision="v1",request_method="GET",request_path="/status/200"} 1
istio_requests_total{response_code="200",reporter="destination",source_workload="sleep",source_workload_namespace="default",source_principal="spiffe://cluster.local/ns/default/sa/sleep",source_app="sleep",source_version="unknown",source_cluster="Kubernetes",destination_workload="httpbin",destination_workload_namespace="default",destination_principal="spiffe://cluster.local/ns/default/sa/httpbin",destination_app="httpbin",destination_version="v1",destination_service="httpbin.default.svc.cluster.local",destination_service_name="httpbin",destination_service_namespace="default",destination_cluster="Kubernetes",request_protocol="http",request_host="httpbin:8000",response_flags="-",grpc_response_status="",connection_security_policy="mutual_tls",source_canonical_service="sleep",destination_canonical_service="httpbin",source_canonical_revision="latest",destination_canonical_revision="v1",request_method="PUT",request_path="/put"} 1
```
