### ISSUE TITLE
Configure Envoy access logs on a per-pod basis

### ISSUE THREAD

**Issue by jacob-delgado** [istio/istio#42453]
**Describe the feature request**

Be able to configure access logging `meshConfig` controls on a per-pod basis. We have some use cases where customers would like modify the [default Envoy access log format](https://istio.io/latest/docs/tasks/observability/logs/access-log/#default-access-log-format).

Currently, we are able to configure the following, but only in a mesh-wide context:
* accessLogFile
* accessLogFormat
* accessLogEncoding

This is similar to https://github.com/istio/istio/issues/42138

**Describe alternatives you've considered**

This can be implemented in ProxyConfig or in the Telemetry API. I would vote for the Telemetry API as that already has some [AccessLogging](https://istio.io/latest/docs/reference/config/telemetry/#AccessLogging) controls. But the codebase may be easier to implement if done in [ProxyConfig](https://istio.io/latest/docs/reference/config/networking/proxy-config/)

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by jacob-delgado** [comment]
cc @howardjohn @costinm @zirain @kyessenov @douglas-reid  thoughts on what api should be changed?

**Comment by howardjohn** [comment]
Telemetry can already do this?

**Comment by jacob-delgado** [comment]
Maybe I'm just running into usability issues.

I'd like to change the access logging format from

```
[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS%
\"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\"
\"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%\n
```

to something like 

```
[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %ROUTE_NAME%\n
```

but only for a few pods.

Looking at https://github.com/istio/api/blob/bcd542ae5e1c21a2afdddc45d92506be405f5e30/telemetry/v1alpha1/telemetry.proto#L613

it doesn't appear you can configure the `accessLogFormat` only somethings, like the conditions for it to log.

**Comment by jacob-delgado** [comment]
Looking at this I think I could possibly setup multiple providers with envoy to get this functionality. Let me try and get back to you. It's not very intuitive.

**Comment by zirain** [comment]
> Looking at this I think I could possibly setup multiple providers with envoy to get this functionality. Let me try and get back to you. It's not very intuitive.

yes, that should be worked.

there's discussion in https://github.com/istio/api/pull/2170 and https://github.com/istio/api/pull/2171

**Comment by jacob-delgado** [comment]
I was able to do this using the api.

Here's my yamls used

istioctl-install.yaml
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    extensionProviders: # The following content defines two example tracing providers.
    - name: "envoy1"
      envoyFileAccessLog:
        path: /dev/stdout
    - name: "envoy2"
      envoyFileAccessLog:
        path: /dev/stdout
        logFormat:
          text: "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %ROUTE_NAME%\n"
```

and the telemetry api

logging-envoy1.yaml
```yaml
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: default
spec:
  accessLogging:
  - providers:
    - name: envoy1
 ```

logging-envoy2.yaml
```yaml
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: default
spec:
  accessLogging:
  - providers:
    - name: envoy2
```
