### ISSUE TITLE
Example on header to metadata grpc needed

### ISSUE THREAD

**Issue by balebomm** [istio/istio#42479]
I'm currently setting up grpc transcoding with header to metadata, i can set transcoding successfully without header to metadata. Please give me an example that i can follow. Appreciate for replies.
This is what i got:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: cict-auth-transcoder
spec:
  workloadSelector:
    labels:
      app: cict-auth
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
        portNumber: 50051
    patch:
      operation: INSERT_FIRST
      value:
        name: envoy.filters.http.header_to_metadata
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.header_to_metadata.v3.Config
          request_rules:
            - header: cookie
              on_header_present:
                metadata_namespace: envoy.lb
                key: session_id
                type: STRING
              remove: false
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
        portNumber: 50051
    patch:
      operation: INSERT_FIRST
      value:
        name: envoy.filters.http.grpc_json_transcoder
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
          services:
          - cict.service_auth.v1.UserService
          proto_descriptor: "/etc/envoy/cict.descriptor"
          print_options:
            add_whitespace: true
            always_print_primitive_fields: true
            always_print_enums_as_ints: false
            preserve_proto_field_names: false
  - applyTo: CLUSTER
    patch:
      operation: MERGE
      value:
        lb_subset_config:
          fallback_policy: ANY_ENDPOINT
          subset_selectors:
            - keys:
                - session_id
```
