### ISSUE TITLE
Unable to use captureMode: NONE when the application binds the same port as the target service

### ISSUE THREAD

**Issue by hintofbasil** [istio/istio#42487]
### Bug Description

When adding `captureMode: NONE` to a Sidecar egress spec it causes the `istio-proxy` container to bind to the same ports as the service's included in the egress block.  If the application container also tries to bind to this port then one of them will fail.

To recreate

1. Install Istio

```
kubectl create namespace istio-system
helm install istio-base istio/base -n istio-system
helm install istiod istio/istiod --namespace istio-system
```

2. Deploy the following resources

```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: infrabin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infrabin
  namespace: infrabin
spec:
  selector:
    matchLabels:
      app: infrabin
  template:
    metadata:
      labels:
        app: infrabin
    spec:
      containers:
      - image: maruina/infrabin
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        name: infrabin
---
apiVersion: v1
kind: Service
metadata:
  name: infrabin
  namespace: infrabin
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: infrabin
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: shell
---
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: shell
  namespace: shell
spec:
  egress:
  - captureMode: NONE
    hosts:
    - infrabin/*
  workloadSelector:
    labels:
      app: shell
---
apiVersion: v1
kind: Pod
metadata:
  name: shell
  namespace: shell
  labels:
    app: shell
spec:
  containers:
  - image: alpine
    command:
    - sh
    - "-c"
    - "apk add python3; python -m http.server 8080"
    name: shell
```

The `alpine` container in the `shell` pod will fail to bind to port 8080 and will continuously crash.

Changing the port that the `alpine` container listens on will allow the pod to come up successfully.

### Version

```prose
❯ istioctl version
client version: 1.16.1
control plane version: 1.15.2
data plane version: 1.15.2 (2 proxies)
```

```
❯ kubectl version --short
Client Version: v1.22.3
Server Version: v1.21.1
```

```
❯ helm version --short
WARNING: "kubernetes-charts.storage.googleapis.com" is deprecated for "stable" and will be deleted Nov. 13, 2020.
WARNING: You should switch to "https://charts.helm.sh/stable" via:
WARNING: helm repo add "stable" "https://charts.helm.sh/stable" --force-update
v3.7.1+g1d11fcb
```
```


### Additional Information

```
❯ istioctl bug-report

Target cluster context: kind-kind

Running with the following config:

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2022-12-16 11:35:52.83147 +0000 UTC

Cluster endpoint: https://127.0.0.1:52349
CLI version:
version.BuildInfo{Version:"1.16.1", GitRevision:"f6d7bf648e571a6a523210d97bde8b489250354b-dirty", GolangVersion:"go1.19.4", BuildStatus:"Clean", GitTag:"1.16.1"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.15.2", GitRevision:"b542583af7f8240ad0c9cab56eb9f8d55e1357ab", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.15.2"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.15.2}

Fetching proxy logs for the following containers:

infrabin/infrabin/infrabin-58fc45cdfb-lpplm/infrabin
infrabin/infrabin/infrabin-58fc45cdfb-lpplm/istio-proxy
istio-system/istiod/istiod-799d6d98f7-9mq24/discovery
shell//shell/istio-proxy
shell//shell/shell

Fetching Istio control plane information from cluster.

Running istio analyze on all namespaces and report as below:
Analysis Report:
Info [IST0102] (Namespace default) The namespace is not enabled for Istio injection. Run 'kubectl label namespace default istio-injection=enabled' to enable it, or 'kubectl label namespace default istio-injection=disabled' to explicitly mark it as not needing injection.
Creating an archive at REDACTED/tmp/istio-1.13-bind-bug/bug-report.tar.gz.
Cleaning up temporary files in /var/folders/4t/fmgqx6gj3fb1k05xyfvwq1xr0000gp/T/bug-report.
Done.
```
