### ISSUE TITLE
Support to configure the listener reuse_port default value

### ISSUE THREAD

**Issue by shonecyx** [istio/istio#42488]
**Describe the feature request**
There is use case that we need to enable bind in the gateway spec:
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: mygw
  namespace: gw-ns
spec:
  selector:
    istio: ingressgateway
  servers:
  - bind: 10.0.0.1
    hosts:
    - '*'
    port:
      name: https-443
      number: 443
      protocol: HTTPS
```
And since there is also gateway on same port without bind, so Istio will build the wildcard listener `0.0.0.0_8443` and to avoid conflicting with the bind VIP gateway, we introduce the EnvoyFilter to enable the reuse port on 8443. 
```
  configPatches:
  - applyTo: LISTENER
    match:
      context: GATEWAY
      listener:
        portNumber: 8443
      proxy:
        proxyVersion: ^1\.10.*
    patch:
      operation: MERGE
      value:
        reuse_port: true
```
However there would be race condition that the wildcard listener created before the EnvoyFilter takes effect since the LDS doesn't honor the EnvoyFilter. And what's more important is that the listener **reuse_port option can't be dynamically changed since it's socket level option**. As of now we need to delete the ingressgateway and recreate to avoid the conflict.

`2022-12-15T04:41:43.295951Z error envoy main  failed to add listener on worker: cannot bind '10.0.0.1:8443': Address already in use`

And the gap here is that LDS doesn't have reuse_port config as below:
https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/listener.go#L1230-L1239

Meanwhile latest envoy changed the default behavior to enable the reuse_port by default:
https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.20/v1.20.0.html?highlight=enable_reuse_port
**Describe alternatives you've considered**

Propose to introduce a global configure like `ISTIO_META_REUSE_PORT` to allow user to configure the default behavior of the LDS reuse_port option. Thus we can avoid the race condition and make sure we have consistent behavior.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
