### ISSUE TITLE
CircuitBreaker-  max connection in connectionPool limit servicelevel or podlevel

### ISSUE THREAD

**Issue by ankitdiscovery** [istio/istio#42490]
itle: maxConnection configured under connectionpool is service level or pod level

Description:

i have istio service mesh with envoy running as sidecar, a destination service with below configuration in destination rule is deployed.
mainly i was trying to check ciruitbreaker beaviour of envoy/istio.
```
 trafficPolicy:
   connectionPool:
     http:
       http1MaxPendingRequests: 1
     tcp:
       maxConnections: 5
```

my client is sending request to this i see a same connection limit getting applied to client side also. if a scale destination replicas to 4, would be my destination service work with total 20 connections (5 connections each pod ) ? or 5 strict connections would be shared between all 4 pods ? And how client side connection would be affected based on that ?

context:- i see after increasing the destination replicas i get less 503 with reponse flag UO.
