### ISSUE TITLE
Allow ServiceEntry to have multiple hosts for same TCP port 

### ISSUE THREAD

**Issue by l8huang** [istio/istio#42522]
**Describe the feature request**

When a ServiceEntry has two hosts on a TCP port:
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: sample
spec:
  hosts:
  - foo.com
  - bar.com
  ports:
  - number: 7070
    targetPort: 7070
    name: tcp
    protocol: TCP
  resolution: DNS
```
It will be denied:
> admission webhook "validation.istio.io" denied the request: configuration is invalid: multiple hosts provided with non-HTTP, non-TLS ports

According to doc string, the reason is:
>		// however, for plain TCP there is no way to differentiate between the
>		// hosts so we consider it invalid, unless the resolution type is NONE
>		// (because the hosts are ignored).

But when `DNS_AUTO_ALLOCATE` is enabled, they can actually be differentiated by allocated IP `240.240.x.x`.

Our use case is mainly related to sidecar's egress TCP traffic through egress gateway, we are looking for removing this restriction from validation webhook. 

**Describe alternatives you've considered**

This issue can be worked around by creating multiple ServiceEntry objects, each only has one host:
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: sample-bar
spec:
  hosts:
  - bar.com
  ports:
  - number: 7070
    targetPort: 7070
    name: tcp
    protocol: TCP
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: sample-foo
spec:
  hosts:
  - foo.com
  ports:
  - number: 7070
    targetPort: 7070
    name: tcp
    protocol: TCP
  resolution: DNS
```

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by hzxuzhonghu** [comment]
DNS_AUTO_ALLOCATE  is not always enabled, user can optionally turn on or off

**Comment by l8huang** [comment]
Yes, it can be turn on/off per workload. But currently multiple ServiceEntrys can be created to archive same effect, the validation is quite weak. 

When DNS_AUTO_ALLOCATE is enabled, validation webhook should allow to leverage related functionalities conveniently.
How about adding a feature flag to loose the validation with the prior knowledge of DNS_AUTO_ALLOCATE has to be enabled?

**Comment by howardjohn** [comment]
Just create 2 service entries is preferred IMO

**Comment by hzxuzhonghu** [comment]
>the validation is quite weak.

This is the fault of declarative API, validator can not prevent this.

>When DNS_AUTO_ALLOCATE is enabled, validation webhook should allow to leverage related functionalities conveniently.
How about adding a feature flag to loose the validation with the prior knowledge of DNS_AUTO_ALLOCATE has to be enabled?

This is also not perfect, as you say DNS_AUTO_ALLOCATE  is per proxy

**Comment by hzxuzhonghu** [comment]
If `DNS_AUTO_ALLOCATE` is disabled, istio will ignore a host

**Comment by l8huang** [comment]
> Just create 2 service entries is preferred IMO

Unfortunately We could have more than 10 services and each of them may have multiple(way more than 2) DNS host names.

We are not looking for a perfect solution at this moment, just want to reduce the number of ServiceEntry required, given that `DNS_AUTO_ALLOCATE`  will be enabled for sure.

**Comment by hzxuzhonghu** [comment]
IMO i am ok with loosen the validation to make validations consistent.  It is no harm  then both ways have same problem when DNS_AUTO_ALLOCATE = false

**Comment by howardjohn** [comment]
Its not great practice to have validation tied to environment variables, because if you change the setting you have persisted invalid configs, and you may have multiple revisions.

**Comment by l8huang** [comment]
> Its not great practice to have validation tied to environment variables, ...

Agree. For this case, the ides of adding a feature environment is purely for preserving the old validation behavior by default, it doesn't make real difference once ServiceEntry being created. If preserving validation behavior is not that important, below validation code can be removed directly:

```
		// multiple hosts and TCP is invalid unless the resolution type is NONE.
		// depending on the protocol, we can differentiate between hosts when proxying:
		// - with HTTP, the authority header can be used
		// - with HTTPS/TLS with SNI, the ServerName can be used
		// however, for plain TCP there is no way to differentiate between the
		// hosts so we consider it invalid, unless the resolution type is NONE
		// (because the hosts are ignored).
		if serviceEntry.Resolution != networking.ServiceEntry_NONE && len(serviceEntry.Hosts) > 1 {
			for _, port := range serviceEntry.Ports {
				p := protocol.Parse(port.Protocol)
				if !p.IsHTTP() && !p.IsTLS() {
					errs = appendValidation(errs, fmt.Errorf("multiple hosts provided with non-HTTP, non-TLS ports"))
					break
				}
			}
		}
``` 
Then no need to work around by creating ServiceEntry for each of hosts.

**Comment by howardjohn** [comment]
Ok but then users not using AUTO_ALLOC (off by default, so most users) will be broken, right? So we definitely cannot remove that.

**Comment by l8huang** [comment]
If users unintentionally create two ServiceEntry on same TCP port when DNS_AUTO_ALLOCATE is false, they still run into the problem.

Any better options for providing convenience to ServiceEntry creation when DNS_AUTO_ALLOCATE is true?

**Comment by l8huang** [comment]
> users not using AUTO_ALLOC (off by default, so most users) will be broken, right? 

For users not using AUTO_ALLOC, they will encounter the same problem if they create multiple ServiceEntry objects with same TCP port.

**Comment by howardjohn** [comment]
Sure, and we can and should provide warnings for those. Just because the
validation isn't perfect doesn't mean we should make it worse?

**Comment by taitelman** [comment]
Its a shame Redis is not supported. 
anyho... 
I added it the ugly way

values.yaml:
```
consumption_redis:
  environment1:
    - a.redis.com:1148
    - b.redis.com:1873
```

service entry:
```
{{- range $urls:=  index .Values.consumption_redis .Values.global.env }}       {{ $parts := split ":" $urls }}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: redis-consumption-{{ $parts._1 }}
  namespace: istio-system
spec:
  location: MESH_EXTERNAL
  exportTo:
    - "*"
  hosts:
    - {{ $parts._0 }}
  ports:
    - number: {{ $parts._1 }}
      name: redis-{{ $parts._1 }}
      protocol: REDIS
  resolution: DNS
---
{{- end}}

```
