### ISSUE TITLE
Unable to route TCP through egress gateway for two hosts on same port

### ISSUE THREAD

**Issue by fluzzykitten** [istio/istio#42520]
### Bug Description

We have a requirement to send all outbound TCP 22 (SSH) traffic through the istio egress gateway from an AWX/Ansible application running in Kubernetes, to hundreds of hosts that are being managed remotely. 

Ideally, we'd like to send all traffic destined to *.example.com through the egress gateway like is documented here, but that can't work because TCP traffic doesn’t have headers, and the ability to send all requests to a single server with different hosts in the headers. All SSH traffic meant for desperate hosts can’t be routed to a single host like in the case of HTTP/HTTPS REST calls. https://istio.io/latest/docs/tasks/traffic-management/egress/wildcard-egress-hosts/

Thus we settled on what we thought was the only option – define a service entry and virtual service for host that we want to have access to from AWX in Kubernetes through the isto-egress gateway. This works for a single host, following these docs - https://github.com/istio/istio/issues/28777

The problem is that this only works for a single host per port. When you add a second service entry and virtual service for a second host, the egress traffic from the egress gateway all goes to one host. I believe the root of the problem is that when you change the “host” from “agent-1” to “istio-egress”, the request no longer has information on where the original request was headed, and thus the istio-egress gateway matches the egress rule for both virtual services, and thus will always fire on the first one. In this case, both agent-1 and agent-2 go to the egress gateway, and then all egress from the egress gateway always goes to the agent-2 on port 22. 

We cannot find a way around this, and so it looks like Istio is unable to route more than one host through the egress gateway on port 22. 

Here is the config we’re using:
```
istioctl install -y -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-operator
  namespace: kube-system
spec:
  meshConfig:
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
    accessLogFile: /dev/stdout #enable envoy access logging
  components:
    cni:
      enabled: true
      namespace: kube-system
    egressGateways:
      - name: istio-egressgateway
        enabled: true
        k8s:
          service:
            ports:
              - port: 80
                targetPort: 8080
                name: http2
              - port: 443
                name: https
                targetPort: 8443
              - port: 15443
                targetPort: 15443
                name: tls
              - port: 22
                targetPort: 3022
                name: ssh
  values:
    cni:
      privileged: true
EOF
```

We’re using the sleep sample app for testing, no changes:
```
kubectl apply -f  - <<EOF
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sleep
---
apiVersion: v1
kind: Service
metadata:
  name: sleep
  labels:
    app: sleep
    service: sleep
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: sleep
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      terminationGracePeriodSeconds: 0
      serviceAccountName: sleep
      containers:
        - name: sleep
          image: curlimages/curl
          command: ["/bin/sleep", "infinity"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /etc/sleep/tls
              name: secret-volume
      volumes:
        - name: secret-volume
          secret:
            secretName: sleep-secret
            optional: true

EOF
```

And here are the Istio CRDs:
```
kubectl apply -f  - <<EOF
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
spec:
  selector:
    istio: egressgateway
  servers:
    - port:
        number: 22
        name: ssh
        protocol: TCP
      hosts:
        - "*.example.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-example
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
    - name: example
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: agent-2
spec:
  hosts:
    - "agent-2.example.com"
  gateways:
    - mesh
    - istio-egressgateway
  tcp:
    - match:
        - gateways:
            - mesh
          port: 22
      route:
        - destination:
            host: istio-egressgateway.istio-system.svc.cluster.local
            subset: example
            port:
              number: 22
          weight: 100
    - match:
        - gateways:
            - istio-egressgateway
          port: 22
      route:
        - destination:
            host: agent-2.example.com
            port:
              number: 22
          weight: 100

---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: agent-2
spec:
  hosts:
    - agent-2.example.com
  ports:
    - number: 22
      name: ssh
      protocol: TCP
  resolution: DNS

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: agent-1
spec:
  hosts:
    - "agent-1.example.com"
  gateways:
    - mesh
    - istio-egressgateway
  tcp:
    - match:
        - gateways:
            - mesh
          port: 22
      route:
        - destination:
            host: istio-egressgateway.istio-system.svc.cluster.local
            subset: example
            port:
              number: 22
          weight: 100
    - match:
        - gateways:
            - istio-egressgateway
          port: 22
      route:
        - destination:
            host: agent-1.example.com
            port:
              number: 22
          weight: 100

---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: agent-1
spec:
  hosts:
    - agent-1.example.com
  ports:
    - number: 22
      name: ssh
      protocol: TCP
  resolution: DNS
EOF
```

To test, I just did a jank curl on port 22, just as a POC. Don’t judge me too harshly =) Here I make two requests, to the two agents
```
kubectl exec "$(kubectl get pod -l app=sleep -o jsonpath={.items..metadata.name})" -c sleep -- curl -k -sS -o /dev/null -w "%{http_code}\n" [https://agent-1.example.com:22](https://rke2-kmgt-test-agent-1.heb.com:22/)
kubectl exec "$(kubectl get pod -l app=sleep -o jsonpath={.items..metadata.name})" -c sleep -- curl -k -sS -o /dev/null -w "%{http_code}\n" [https://agent-2.example.com:22](https://rke2-kmgt-test-agent-2.heb.com:22/)
```

Then looking at the logs from the side car on the pod, we see both requests go out:
```
kubectl logs "$(kubectl get pod -l app=sleep -o jsonpath={.items..metadata.name})" -c istio-proxy –follow
…
[2022-12-19T22:41:33.442Z] "- - -" 0 - - - "-" 517 21 7 - "-" "-" "-" "-" "10.42.5.45:3022" outbound|22|example|istio-egressgateway.istio-system.svc.cluster.local 10.42.3.58:59440 172.16.226.191:22 10.42.3.58:59914 - -
[2022-12-19T22:41:46.113Z] "- - -" 0 - - - "-" 517 57 7 - "-" "-" "-" "-" "10.42.5.45:3022" outbound|22|example|istio-egressgateway.istio-system.svc.cluster.local 10.42.3.58:56858 172.16.226.236:22 10.42.3.58:43784 - -
```

Then we see from the side care on the egress gateway that both go to the same server, agent-2
```
kubectl logs -l istio=egressgateway -c istio-proxy -n istio-system –follow
…
[2022-12-19T22:41:43.546Z] "- - -" 0 - - - "-" 517 57 8 - "-" "-" "-" "-" "172.16.226.236:22" outbound|22||agent-2.example.com 10.42.5.45:42398 10.42.5.45:3022 10.42.3.58:59440 - -
[2022-12-19T22:41:56.218Z] "- - -" 0 - - - "-" 517 57 6 - "-" "-" "-" "-" "172.16.226.236:22" outbound|22||agent-2.example.com 10.42.5.45:42898 10.42.5.45:3022 10.42.3.58:56858 - -
```

Thanks again, any help is greatly appreciated!

### Version

```prose
$ kubectl version --short
Client Version: v1.23.13
Server Version: v1.23.14+rke2r1
$ istioctl version
client version: 1.16.0
control plane version: 1.16.0
data plane version: 1.16.0 (9 proxies)
```

**Comment by l8huang** [comment]
We have similar use case, we do:
- From sidecar to egress gateway, MTLS is enabled, and DestinationRules are used to set SNI to `agent-1.example.com` or `agent-1.example.com` for different TCP traffic.
- On egress gateway, create 2 Gateway objects on same port(22 in your case) for matching `agent-1.example.com` or `agent-1.example.com`.

The basic idea is Istio MTLS itself doesn't use SNI, so SNI can be used to multiplexing TCP traffic on same port.

**Comment by zufardhiyaulhaq** [comment]
Is it possible to tunnel the TCP via another transport protocol in the mesh? so the egress gateway can select the destination based on DNS? never try through https://istio.io/latest/docs/reference/config/networking/destination-rule/#TrafficPolicy-TunnelSettings

**Comment by fluzzykitten** [comment]
@l8huang Thanks for the quick reply, that sounds like it would solve our problem, but I'm not sure I fully understand how you guys implemented this solution. My understanding of mTLS just ensures that the comms between the worker pod and the egress pod is encrypted with mTLS, it doesn't actually change the route of a request to agent-1 on port 22 from the worker pod to route through the egress gateway. Could you include some of your configuration yamls to help me better understand your implementation? 

@zufardhiyaulhaq Thanks for the quick reply. Yes, tunneling sounds fantastic! When we first found these docs for tunneling, we'd hoped it would fix our problem, but we were unable to get it to work. We created two destination rule subsets with different tunnel settings to the different hosts, but nothing changed. All outbound comms all went to only one host. If this should work, then we must've not done it right. When we implemented this, I couldn't find any specific examples of how to implement the tunnelSettings. Do you have a link to any examples that implement tunnels in destination rules? Could you forward them to me, so I can check to see if we wrote the code up for tunneling correctly? Hopefully it was just user error, but as far as we can tell, everything looks correctly configured

**Comment by l8huang** [comment]
Egress gateway listener on port 22 can use `SNI` to multiplexing TLS traffic, 2 Gateway objects are required to define the FilterChainMatch with SNI, and 2 DestinationRules are used to enable Istio MTSL and set SNI for egress TCP traffic forwarded by different subset of egress gateway outbound cluster on client-side Istio sidecar.

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: agent-1
spec:
  hosts:
    - agent-1.example.com
  ports:
    - number: 22
      name: ssh
      protocol: TCP
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: agent-2
spec:
  hosts:
    - agent-2.example.com
  ports:
    - number: 22
      name: ssh
      protocol: TCP
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway-agent-1
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 22
      name: ssh
      protocol: TLS
    hosts:
    - "agent-1.example.com"
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway-agent-2
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 22
      name: ssh
      protocol: TLS
    hosts:
    - "agent-2.example.com"
    tls:
      mode: ISTIO_MUTUAL
---

apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: egressgateway-for-agent-1
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: agent-1
    trafficPolicy:
      portLevelSettings:
      - port:
          number: 22
        tls:
          mode: ISTIO_MUTUAL
          sni: agent-1.example.com
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: egressgateway-for-agent-2
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: agent-2
    trafficPolicy:
      portLevelSettings:
      - port:
          number: 22
        tls:
          mode: ISTIO_MUTUAL
          sni: agent-2.example.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: agent-1
spec:
  hosts:
    - "agent-1.example.com"
  gateways:
    - mesh
    - istio-egressgateway-agent-1
  tcp:
    - match:
        - gateways:
            - mesh
          port: 22
      route:
        - destination:
            host: istio-egressgateway.istio-system.svc.cluster.local
            subset: agent-1
            port:
              number: 22
          weight: 100
    - match:
        - gateways:
            - istio-egressgateway-agent-1
          port: 22
      route:
        - destination:
            host: agent-1.example.com
            port:
              number: 22
          weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: agent-2
spec:
  hosts:
    - "agent-2.example.com"
  gateways:
    - mesh
    - istio-egressgateway-agent-2
  tcp:
    - match:
        - gateways:
            - mesh
          port: 22
      route:
        - destination:
            host: istio-egressgateway.istio-system.svc.cluster.local
            subset: agent-2
            port:
              number: 22
          weight: 100
    - match:
        - gateways:
            - istio-egressgateway
          port: 22
      route:
        - destination:
            host: agent-2.example.com
            port:
              number: 22
          weight: 100
```

**Comment by l8huang** [comment]
Also, don't forget to enable below in operator.yaml:
```
  values:
    meshConfig:
      defaultConfig:
        proxyMetadata:
          ISTIO_META_DNS_AUTO_ALLOCATE: "true"
          ISTIO_META_DNS_CAPTURE: "true"
```
