### ISSUE TITLE
Cannot merge authn rules using envoyfilter

### ISSUE THREAD

**Issue by kebe7jun** [istio/istio#42533]
### Bug Description

When using the following envoyfilter:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: envoy-jwt-cookie
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: istio-ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        portNumber: 8080
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.jwt_authn"
    patch:
      operation: MERGE
      value:
        name: envoy.filters.http.jwt_authn
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
          providers:
            origins-0:
              from_cookies: 
              - jwt
            origins-1:
              from_cookies: 
              - jwt
            origins-2:
              from_cookies: 
              - jwt

```

Istiod shows the following errors:
```
2022-12-20T07:51:15.033276Z	warn	ads	ADS:LDS: ACK ERROR istio-ingressgateway-9b8c76bfc-jx7hl.istio-system-8721 Internal:Error adding/updating listener(s) 0.0.0.0_8080: Proto constraint validation failed (JwtAuthenticationValidationError.Providers[origins-0]: embedded message failed validation | caused by field: "jwks_source_specifier", reason: is required): providers {
  key: "origins-0"
  value {
    from_cookies: "jwt"
  }
}
```

### Version

```prose
latest
```
