### ISSUE TITLE
Istio SNI is giving validation error when I use it in virtual service as SNI host

### ISSUE THREAD

**Issue by shivanshu1333** [istio/istio#42537]
### Bug Description

I want to use SNI generated from istio in my virtual service but it gives me validation error in `networking.istio.io/v1beta1`, no error if I use `networking.istio.io/v1alpha3`

Validation error with `v1beta1`
```
Error from server: error when creating "vs.yaml": admission webhook "rev.validation.istio.io" denied the request: configuration is invalid: domain name "outbound_.5000_._.helloworld.echo-7-25457.svc.cluster.local" invalid (label "outbound_" invalid)
```

My VS:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    istio.io/rev: stable
  name: vs-test
  namespace: echo-7-25457
spec:
  exportTo:
  - .
  gateways:
  - echo-7-25457/ew-gw
  hosts:
  - helloworld.echo-7-25457.svc.cluster.local
  tls:
  - match:
    - port: 15443
      sniHosts:
      - outbound_.5000_._.helloworld.echo-7-25457.svc.cluster.local
    route:
    - destination:
        host: helloworld.echo-7-25457.svc.cluster.local
        port:
          number: 5000
      weight: 100
 ```
Relevant code https://github.com/istio/istio/blame/master/pkg/config/validation/validation.go#L2689-L2706

### Version

```prose
v15.2
```
