### ISSUE TITLE
Unable to enable telemetry with remote profile

### ISSUE THREAD

**Issue by vardhaman22** [istio/istio#42569]
### Bug Description

When trying to install istio with remote profile i tried enabling telemetry which resulted in following error

```

✘ Istiod remote encountered an error: failed to update resource with server-side apply for obj EnvoyFilter/istio-system/stats-filter-1.13: no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3"
--



```

### Version

```prose
version: 1.15.3
```

### Additional Information

the following config was used when trying to install istio.

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    base:
      enabled: false
    pilot:
      enabled: false
    ingressGateways:
    - name: istio-ingressgateway
      enabled: false
    istiodRemote:
      enabled: true
  values:
    global:
      externalIstiod: true
      omitSidecarInjectorConfigMap: true
      configCluster: false
    pilot:
      configMap: false
    telemetry:
      enabled: true
      v2:
        enabled: true
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
