### ISSUE TITLE
Configuration profile support for istio-proxy. Sidecar in root namespace with labelSelector?

### ISSUE THREAD

**Issue by Pawan-Bishnoi** [istio/istio#42593]
**Describe the feature request**
Currently, there is no support for configuration profiles at root namespace level. 
All proxies get the entire config on startup. 

Can we enhance the Sidecar CRD to have a meshWorkloadSelector which when defined in root namespace will consider all workloads in the mesh.

```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: minimal-config-profile
  namespace: mesh-root
spec:
  egress:
  - hosts:
    - 'mesh-root/metrics-service.svc.cluster.local'
    - '*/httpproxy.svc.cluster.local'
    - '*/logs-service.svc.cluster.local'
  meshWorkloadSelector:
    labels:
      mesh-proxy-bootstrap-profile: minimal
```

**Describe alternatives you've considered**
Sidecar CRD supports a workload selector already but it is applied on a namespace level only.
Every namespace must define the Sidecar CRD and there is risk of Sidecar config being not ready when Deployment & Sidecar are applied together (for eg. a fresh namespace creation)
In case of updates to the configuration profile, multiple copies of the same resource needs to be updated.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[x] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
This is to improve the startup time of istio-proxy when running in large mesh installations having thousands of clusters.
Onboarding to a configuration profile is a label away for existing customers of a mesh offering.
