### ISSUE TITLE
Can't evaluate field ProxyImage in type *inject.SidecarTemplateData

### ISSUE THREAD

**Issue by pzhx521** [istio/istio#42601]
### Bug Description

When I use the **IstioOperator** yaml file to install the isio, I find that the proxy container cannot be injected normally, and an error message is prompted: `Admission webhook "[namespace.sidecar-injector.istio.io](http://namespace.sidecar-injector.istio.io/)" denied the request: failed to run injection template: template: inject:77:15: executing "inject" at <.ProxyImage>: can't evaluate field ProxyImage in type *inject.SidecarTemplateData:Deployment does not have minimum availability.`

### Version

```prose
istio version: 1.6.1
```

### Additional Information

I don't know how to set `ProxyImage`. I can't find the description of relevant documents.

![20221229-184259](https://user-images.githubusercontent.com/46491088/209940173-58420a0a-9d9d-43d4-ac02-ec6525f9fe3b.jpeg)

I failed to use the following methods.
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  ...
  profile: default
  ProxyImage: xxxx
  values:
     ....
```
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  ...
  profile: default
  values:
     ....
     ProxyImage: xxxx
```

The error message is as follow:
`Error: generate config: error unmarshaling JSON: while decoding JSON: unknown field "ProxyImage" in istio.operator.v1alpha1.IstioOperatorSpec:`

I did not find this field in `IstioOperatorSpec`, so I think there is a problem with the template file.

https://github.com/istio/istio/blob/1.16.1/manifests/charts/istiod-remote/files/injection-template.yaml
https://github.com/istio/api/blob/1.16.1/operator/v1alpha1/operator.proto
