### ISSUE TITLE
VirtualService delegate doesn't work with defaultVirtualServiceExportTo: ["."]

### ISSUE THREAD

**Issue by rajatsharma94** [istio/istio#42602]
### Bug Description

Merging of VirtualServices based on the `delegate` doesn't happen when VirtualServices are set to be exported to their own namespace (setting `defaultVirtualServiceExportTo: ["."]`) and the `exportTo` in VirtualService is not set. 

#### VirtualService
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dummy-svc-1
  namespace: ns-1
spec:
  hosts:
  - "dummy-svc-1.service"
  http:
  - match:
    - uri:
        prefix: "/"
    delegate:
       name: dummy-svc-1-dlg
```
#### Delegate VirtualService
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dummy-svc-1-dlg
  namespace: ns-1
spec:
  http:
  - route:
    - destination:
        host: dummy-svc-1.ns-1.svc.cluster.local
```
In the Mesh config we have VirtualServices being exported to their own namespace.
```
defaultVirtualServiceExportTo: ["."]
```

### Expected Behaviour

Since both VirtualServices are in the same namespace and are exported to their own namespace by default, the VirtualServices routes should be merged and the istio-proxy sidecar should receive a routing rule that matches `dummy-svc-1.service` and forwards it to `dummy-svc-1.ns-1.svc.cluster.local`

### Actual Behaviour

The istio-proxy sidecar doesn't receive any routing logic for this VirtualService at all.

On further investigation, found the following error in Istiod logs
```
debug	model	delegate virtual ns-1/dummy-svc-1-dlg of ns-1/dummy-svc-1 is not exported to ns-1
```

### Version

```prose
client version: 1.13.1
control plane version: 1.15.0
data plane version: 1.15.0 (9 proxies)
```

### Additional Information

This issue doesn't show up if the VirtualServices are exported to all namespaces by default (`defaultVirtualServiceExportTo:["*"]`), or if we explicitly define `exportTo:["."]` in the delegate VirtualService.
