### ISSUE TITLE
enabling v2 telemetry with wasm results in `Unable to create Wasm HTTP filter`

### ISSUE THREAD

**Issue by ajohnstone** [istio/istio#42614]
### Bug Description

enabling v2 telemetry results in `Unable to create Wasm HTTP filter`

```
k -n istio-system logs -f deploy/istiod
2022-12-29T20:09:21.059758Z	warn	ads	ADS:LDS: ACK ERROR reviews-v3-c9c4fb987-whpm9.bookinfo-4 Internal:Error adding/updating listener(s) 10.96.70.143_443: Unable to create Wasm network filter
10.96.0.1_443: Unable to create Wasm network filter
10.96.188.98_443: Unable to create Wasm network filter
10.96.148.152_9402: Unable to create Wasm network filter
10.96.44.96_15012: Unable to create Wasm network filter
10.96.0.10_53: Unable to create Wasm network filter
10.96.44.96_443: Unable to create Wasm network filter
0.0.0.0_15014: Unable to create Wasm HTTP filter
10.96.70.143_15021: Unable to create Wasm HTTP filter
0.0.0.0_80: Unable to create Wasm HTTP filter
10.96.0.10_9153: Unable to create Wasm HTTP filter
0.0.0.0_15010: Unable to create Wasm HTTP filter
0.0.0.0_9080: Unable to create Wasm HTTP filter
virtualOutbound: Unable to create Wasm network filter
virtualInbound: Unable to create Wasm network filter

2022-12-29T20:09:22.024450Z	info	klog	successfully acquired lease istio-system/istio-leader
2022-12-29T20:09:22.024851Z	info	leader election lock obtained: istio-leader
2022-12-29T20:09:22.025233Z	info	Starting ingress controller
```

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  values:
...
    telemetry:
      enabled: true
      v2:
        enabled: true
        prometheus:
          wasmEnabled: true
        metadataExchange:
          wasmEnabled: true
...
```

### Version

```prose
istioctl version
client version: 1.16.1
control plane version: 1.16.1
data plane version: 1.16.1 (6 proxies)
```

```
kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.2
Kustomize Version: v4.5.7
Server Version: v1.25.3
```
```


### Additional Information

_No response_
