### ISSUE TITLE
【holdApplicationUntilProxyStarts=true】 affects istio support spire feature

### ISSUE THREAD

**Issue by tanjunchen** [istio/istio#42656]
### Bug Description

According to doc https://istio.io/latest/docs/ops/integrations/spire/#verifying-that-identities-were-created-for-workloads, We add holdApplicationUntilProxyStarts=true into iop,it will result in pod failed.
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  profile: default
  meshConfig:
    trustDomain: example.org
    defaultConfig:
      # the holdApplicationUntilProxyStarts parameter added
      holdApplicationUntilProxyStarts: true
  values:
    # This is used to customize the sidecar template, to allow mounting the Workload API socket.
    sidecarInjectorWebhook:
      templates:
        spire: |
          spec:
            containers:
            - name: istio-proxy
              volumeMounts:
              - name: workload-socket
                mountPath: /run/secrets/workload-spiffe-uds
                readOnly: true
            volumes:
              - name: workload-socket
                csi:
                  driver: "csi.spiffe.io"
                  readOnly: true
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        label:
          istio: ingressgateway
        k8s:
          overlays:
            - apiVersion: apps/v1
              kind: Deployment
              name: istio-ingressgateway
              patches:
                - path: spec.template.spec.volumes.[name:workload-socket]
                  value:
                    name: workload-socket
                    csi:
                      driver: "csi.spiffe.io"
                      readOnly: true
                - path: spec.template.spec.containers.[name:istio-proxy].volumeMounts.[name:workload-socket]
                  value:
                    name: workload-socket
                    mountPath: "/run/secrets/workload-spiffe-uds"
                    readOnly: true
```
related issues: 
https://github.com/spiffe/spire/issues/3092 
https://github.com/spiffe/spire/pull/3460

### Version

```prose
istioctl version

spire git:(master) ✗ istioctl version
client version: 1.15.0
control plane version: 1.15.0
data plane version: 1.15.0 (4 proxies)
```

spire git:(master) ✗ kubectl version --short
```
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.2
Kustomize Version: v4.5.7
Server Version: v1.20.8
WARNING: version difference between client (1.25) and server (1.20) exceeds the supported minor version skew of +/-1
```
```


### Additional Information

_No response_
