### ISSUE TITLE
Istio Local Rate Limit not working by route

### ISSUE THREAD

**Issue by rss04** [istio/istio#42664]
### Bug Description

I have tried to use rate limit by route but it is rate limiting the whole application not limiting it by  a single path. 
I am using the following example. Can anyone please advise ?

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-local-ratelimit-payment
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: payment-dgs
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter            
    - applyTo: HTTP_ROUTE
      match: 
        context: SIDECAR_INBOUND
        routeConfiguration:
          vhost:
            name: "inbound|http|80"
            route:
              action: ANY
      patch:
        operation: MERGE
        value:
          route:
            rate_limits:
              - actions: 
                  - remote_address: {}
              - actions: 
                  - header_value_match:
                      descriptor_value: "echo"
                      expect_match: true
                      headers:
                        - name: :path
                          string_match:
                            prefix: /paymentdgs/webhooks/echo
                            ignore_case: true
              - actions: 
                  - header_value_match:
                      descriptor_value: "status"
                      expect_match: true
                      headers:
                        - name: :path
                          string_match:
                            prefix: /graphql/paymentdgs/status
                            ignore_case: true                            
              # - actions: 
              #     - header_value_match:
              #         descriptor_value: "echo"
              #         expect_match: true
              #         headers:
              #           - name: :path
              #             string_match:
              #               prefix: /paymentdgs
              #               ignore_case: true
              # - actions: 
              #     - header_value_match:
              #         descriptor_value: "status"
              #         expect_match: true
              #         headers:
              #           - name: :path
              #             string_match:
              #               safe_regex:
              #                 google_re2: {}
              #                 regex: "status"
          typed_per_filter_config:
            envoy.filters.http.local_ratelimit:
              "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
              stat_prefix: test_enabled
              token_bucket:
                max_tokens: 2
                tokens_per_fill: 2
                fill_interval: 60s
              filter_enabled:
                runtime_key: test_enabled
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              filter_enforced:
                runtime_key: test_enabled
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              response_headers_to_add:
                - append: false
                  header:
                    key: x-local-rate-limit
                    value: "true"
              descriptors:
                - entries:
                    - key: header_match
                      value: echo
                  token_bucket:
                    max_tokens: 10
                    tokens_per_fill: 10
                    fill_interval: 60s
                - entries:
                    - key: header_match
                      value: status
                  token_bucket:
                    max_tokens: 2
                    tokens_per_fill: 2
                    fill_interval: 60s      
                                  
```

### Version

```prose
istioctl version
client version: 1.16.1
control plane version: 1.14.1
data plane version: 1.14.1 (23 proxies)
kubectl version --short
Client Version: v1.25.2
Kustomize Version: v4.5.7
Server Version: v1.21.14-eks-fb459a0
```

**Comment by zirain** [comment]
I think the root cause is https://github.com/envoyproxy/envoy/issues/24682

can you increase the default token bucket then retry again?

**Comment by rss04** [comment]
@zirain thanks for responding. Yes, I have increased the default bucket to 100 something like this but still it is not rate limiting by path but the whole app. 
It is is also rate limiting all paths (I guess the whole App) even if we apply limit to a single path. 
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-local-ratelimit-payment
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: payment-dgs
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter            
    - applyTo: HTTP_ROUTE
      match: 
        context: SIDECAR_INBOUND
        routeConfiguration:
          vhost:
            name: "inbound|http|80"
            route:
              action: ANY
      patch:
        operation: MERGE
        value:
          route:
            rate_limits:
              - actions: 
                  - remote_address: {}
              - actions: 
                  - header_value_match:
                      descriptor_value: "echo"
                      expect_match: true
                      headers:
                        - name: :path
                          string_match:
                            prefix: /paymentdgs/webhooks/echo
                            ignore_case: true
              - actions: 
                  - header_value_match:
                      descriptor_value: "status"
                      expect_match: true
                      headers:
                        - name: :path
                          string_match:
                            prefix: /graphql/paymentdgs/status
                            ignore_case: true                            
              # - actions: 
              #     - header_value_match:
              #         descriptor_value: "echo"
              #         expect_match: true
              #         headers:
              #           - name: :path
              #             string_match:
              #               prefix: /paymentdgs
              #               ignore_case: true
              # - actions: 
              #     - header_value_match:
              #         descriptor_value: "status"
              #         expect_match: true
              #         headers:
              #           - name: :path
              #             string_match:
              #               safe_regex:
              #                 google_re2: {}
              #                 regex: "status"
          typed_per_filter_config:
            envoy.filters.http.local_ratelimit:
              "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
              stat_prefix: test_enabled
              token_bucket:
                max_tokens: 100
                tokens_per_fill: 100
                fill_interval: 60s
              filter_enabled:
                runtime_key: test_enabled
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              filter_enforced:
                runtime_key: test_enabled
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              response_headers_to_add:
                - append: false
                  header:
                    key: x-local-rate-limit
                    value: "true"
              descriptors:
                - entries:
                    - key: header_match
                      value: echo
                  token_bucket:
                    max_tokens: 10
                    tokens_per_fill: 10
                    fill_interval: 60s
                - entries:
                    - key: header_match
                      value: status
                  token_bucket:
                    max_tokens: 2
                    tokens_per_fill: 2
                    fill_interval: 60s 
```

**Comment by rss04** [comment]
Does it matter if it is a graphql ?

**Comment by zirain** [comment]
if you want bypass in default bucket, change it to 
```
              tokenBucket:
                maxTokens: 2147483647
                tokensPerFill: 2147483647
                fillInterval: 60s
```
