### ISSUE TITLE
VirtualService not working with ExternalService with TLS1.3 + SNI?

### ISSUE THREAD

**Issue by kehao95** [istio/istio#42695]
### Bug Description

I have an existing cluster A  (`cluster-a.dev`) with `istio` installed & configured 
And an httpbin service setup on `httpbin.cluster-b.dev`.

I want to create a virtual service for `httpbin.cluster-a.dev` to route it to `httpbin.cluster-b.dev`

So I created `ServiceEntry/DestinationRule/VirtualService` according to doc, but it didn't work. 
But when I change the hostname from `httpbin.cluster-b.dev` to `httpbin.org`, it works.

So the same config works for `https://httpbin.org` but not for `https://httpbin.cluster-b.dev`. Even though they are all valid httpbin endpoints. 
So I think the only difference between these two endpoints, **SNI or TLS1.3**, is causing the problem. 

**Config I'm using**
```yaml
# and exact same ServiceEntry for httpbin.org 
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: httpbin.cluster-b.dev
  namespace: dev-ns
spec:
  hosts:
  - httpbin.cluster-b.dev
  location: MESH_EXTERNAL
  ports:
  - name: HTTPS
    number: 443
    protocol: TLS
  resolution: DNS

# and exact same DestinationRule for httpbin.org 
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: httpbin.cluster-b.dev
  namespace: dev-ns
spec:
  host: httpbin.cluster-b.dev
  trafficPolicy:
    tls:
      mode: SIMPLE
      sni: httpbin.cluster-b.dev

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: auryc-app-message-tracker
  namespace: dev-ns
spec:
  gateways:
  - istio-system/cluster-gateway
  - mesh
  hosts:
  - httpbin.cluster-a.dev
  http:
  - name: heap-only
    route:
    - destination:
        host: httpbin.cluster-b.dev  # This won't works
        # host: httpbin.org   # This works
        port:
          number: 443
```

**Results for the config:**
```bash
# when VS destination set to httpbin.cluster-b.dev 
$ http get https://httpbin.cluster-a.dev/get
HTTP/1.1 404 Not Found
Content-Length: 0
Date: Fri, 06 Jan 2023 08:01:14 GMT
Server: istio-envoy
X-Envoy-Upstream-Service-Time: 29

# when VS destination set to httpbin.org 
$ http get https://httpbin.cluster-a.dev/get
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Content-Length: 2797
Content-Type: application/json
Date: Fri, 06 Jan 2023 08:02:39 GMT
Server: istio-envoy
X-Envoy-Upstream-Service-Time: 56

{
    "args": {},
    "headers": {...}
}
```

**Difference Between `httpbin.cluster-b.dev` and `httpbin.org`**
The only thing I can tell is that curl did SSL connection 
using TLSv1.3 with `httpbin.cluster-b.dev` 
but using TLSv1.2 with `httpbin.org`
which should be server's preferred TLS version. 
And I know `httpbin.cluster-b.dev` is using SNI which was matching `*.cluster-b.dev`.

```bash
curl -v https://httpbin.cluster-b.dev/ip
* Connected to httpbin.cluster-b.dev (44.206.84.35) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=httpbin.cluster-b.dev
*  start date: Jan  5 04:17:24 2023 GMT
*  expire date: Apr  5 04:17:23 2023 GMT
*  subjectAltName: host "httpbin.cluster-b.dev" matched cert's "httpbin.cluster-b.dev"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* h2h3 [:method: GET]
* h2h3 [:path: /ip]
* h2h3 [:scheme: https]
* h2h3 [:authority: httpbin.cluster-b.dev]
* h2h3 [user-agent: curl/7.84.0]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x121812400)
> GET /ip HTTP/2
> Host: httpbin.cluster-b.dev
> user-agent: curl/7.84.0
> accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 2147483647)!
< HTTP/2 200
< server: istio-envoy
< date: Fri, 06 Jan 2023 08:06:28 GMT
< content-type: application/json
< content-length: 33
< access-control-allow-origin: *
< access-control-allow-credentials: true
< x-envoy-upstream-service-time: 1
<
{
  "origin": ".xxxx.xx.xx"
}
```
```bash
curl -v https://httpbin.org/ip
* Connected to httpbin.org (3.220.55.57) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=httpbin.org
*  start date: Oct 21 00:00:00 2022 GMT
*  expire date: Nov 19 23:59:59 2023 GMT
*  subjectAltName: host "httpbin.org" matched cert's "httpbin.org"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* h2h3 [:method: GET]
* h2h3 [:path: /ip]
* h2h3 [:scheme: https]
* h2h3 [:authority: httpbin.org]
* h2h3 [user-agent: curl/7.84.0]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x13e810000)
> GET /ip HTTP/2
> Host: httpbin.org
> user-agent: curl/7.84.0
> accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200
< date: Fri, 06 Jan 2023 08:08:10 GMT
< content-type: application/json
< content-length: 33
< server: gunicorn/19.9.0
< access-control-allow-origin: *
< access-control-allow-credentials: true
<
{
  "origin": "73.102.130.221"
}
* Connection #0 to host httpbin.org left intact
```

### Version

```prose
$ istioctl version
client version: 1.16.1
control plane version: 1.16.1
data plane version: 1.11.1 (93 proxies), 1.16.1 (31 proxies)
$ kubectl version 
Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.21.14-gke.4300
```
```


### Additional Information

_No response_

**Comment by escoffier** [comment]
404 error code indicated that TLS handshake successfully.   Could you dump envoy configuration using istioctl?

**Comment by kehao95** [comment]
Hi @escoffier, 
My cluster was messy with a lot more irrelevant workloads.
So I created a minimal reproduction of the problem here https://github.com/kehao95/istio-istio-42695

You can just reproduce the problem with the repo within a few mins. 
Or I've also uploaded `istioctl bug-report` generated files as well.

Hope this helps

**Comment by kehao95** [comment]
Hi, I got some new findings here. https://github.com/istio/istio/issues/41869 
Maybe this is the root cause. That for Cluster B, I was configuring a wildcard listener with multiple certs like this:
```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: cluster-gateway
  namespace: gateway-system
spec:
  gatewayClassName: istio
  listeners:
  - name: http-wildcard
    hostname: '*.cluster-b.dev'
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  
  - name: https-wildcard
    hostname: '*.cluster-b.dev'
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: cluster-b-dev-cert
        kind: Secret

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-b-dev-cert
  namespace: gateway-system
spec:
  dnsNames:
  - httpbin.cluster-b.dev
  - podinfo.cluster-b.dev
  - demo.cluster-b.dev
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cluster-issuer
  secretName: cluster-b-dev-cert
  usages:
  - digital signature
  - key encipherment
```
