### ISSUE TITLE
Istio 1.15 breaks Wildcard configuration for arbitrary domains

### ISSUE THREAD

**Issue by PatrickDuncan** [istio/istio#42709]
### Bug Description

Hey, is [Wildcard configuration for arbitrary domains](https://istio.io/v1.13/docs/tasks/traffic-management/egress/wildcard-egress-hosts/#wildcard-configuration-for-arbitrary-domains) supported in Istio 1.15.4? We have some HTTPS endpoints using the standard [Egress Gateways](https://istio.io/v1.13/docs/tasks/traffic-management/egress/egress-gateway/) approach and they work fine with 1.14 and 1.15. But our endpoints that use the wildcard approach with the sni-proxy container work with 1.14, but fail with 1.15.

We use the canary process when upgrading. The wildcard traffic works when the 1.15 canary is installed and when the egress gateway is using 1.15. But the second I apply istiod 1.15 image, the wildcard communication breaks. The error the client sees is EOF.

I do not see any warnings/errors that were not already there with 1.14. The nginx sni-proxy logs look the same with success/failure.

I've fixed a couple `istioctl analyze` errors/warnings, but the problem persists. Current warnings:
```
Warning [IST0133] (EnvoyFilter istio-system/istio-egressgateway-sni-verifier) Schema validation warning: Envoy filter: unknown field "config" in envoy.config.listener.v3.Filter
Warning [IST0133] (EnvoyFilter istio-system/forward-downstream-sni) Schema validation warning: Envoy filter: unknown field "config" in envoy.config.listener.v3.Filter
Warning [IST0133] (ServiceEntry application/sni-proxy) Schema validation warning: addresses are required for ports serving TCP (or unset) protocol
Warning [IST0134] (ServiceEntry application/sni-proxy) ServiceEntry addresses are required for this protocol.
```

We're sending to a Kafka offering, here's the Gateway. The rest of the YAML is the same as the documentation except our port is 9093 instead of 443.
```yaml
- apiVersion: networking.istio.io/v1alpha3
  kind: Gateway
  metadata:
    name: istio-egressgateway
    namespace: application
  spec:
    selector:
      istio: egressgateway
    servers:
    - hosts:
      - '*.eventstreams.cloud.ibm.com'
      - '*.containers.appdomain.cloud'
      - '*.messagehub.appdomain.cloud'
      port:
        name: tls-kafka
        number: 9093
        protocol: TLS
      tls:
        mode: ISTIO_MUTUAL
```

### Version

```prose
$ istioctl version

client version: 1.15.4
istiod version: 1.15.4
istiod version: 1.15.4
istiod version: 1.15.4
istiod version: 1.15.4
pilot version: 1.14.5
pilot version: 1.14.5
pilot version: 1.14.5
pilot version: 1.14.5
data plane version: 1.14.5 (30 proxies), 1.15.4 (66 proxies)

$ kubectl version --short

Client Version: v1.23.5
Server Version: v1.24.9+IKS
```
