### ISSUE TITLE
egress gateway replicaCount not being honored

### ISSUE THREAD

**Issue by fluzzykitten** [istio/istio#42769]
### Bug Description

We wanted to have two egress pods for redundancy, but setting the replicaCount as per the docs doesn't appear to affect the deployed egressGateway. Per the docs:
https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#KubernetesResourcesSpec

We set the istio config:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-operator
  namespace: kube-system
spec:
  components:
    egressGateways:
      - name: istio-egressgateway
        enabled: true
        k8s:
          replicaCount: 2
```
But the resulting deployment still only has a replica count set to 1
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-egressgateway
...
spec:
  replicas: 1
...
```
Temporary work around is to increase the HPA policy to have 2, which works and reflects in the configs and gives us two deployments with two pods
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-operator
  namespace: kube-system
spec:
  components:
    egressGateways:
      - name: istio-egressgateway
        enabled: true
        k8s:
          replicaCount: 2
          hpaSpec:
            minReplicas: 2
```
Which correctly reflects in the configuration:
```
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: istio-egressgateway
spec:
  minReplicas: 2
...
```
But setting replicaCount and not seeing it reflected in the deployment appears to be a bug. KkThnxBai.

### Version

```prose
$ istioctl version
client version: 1.16.0
control plane version: 1.16.0
data plane version: 1.16.0 (18 proxies)
$ kubectl version --short
Client Version: v1.23.13
Server Version: v1.23.14+rke2r1
```
