### ISSUE TITLE
VirtualService - mesh gateway not working

### ISSUE THREAD

**Issue by holotrack** [istio/istio#42773]
I installed istio on my test cluster configured gateway and few VirtualServices pined to this gateway and it is working. But when im trying to create VirtualService for sidecars (injection is enabled on namespace) im still getting:

```
/# mysql -h mysql-vs
ERROR 2005 (HY000): Unknown MySQL server host 'mysql-vs' (-2)
```

Here is my VirtualService and Service yaml:

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: mysql-vs
spec:
  gateways:
  - mesh
  hosts:
  - mysql-vs
  tcp:
  - match:
    - port: 3306
    route:
    - destination:
        host: mysql-service
        port:
          number: 3306
          
```

```
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  annotations:
    cloud.google.com/backend-config: '{"default": "backendconfig"}'
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 3306
      targetPort: 3306
```

Am I missing something? I still can reach mysql-service, but not mysql-vs.

**Comment by xichengliudui** [comment]
Try using FQDN

**Comment by xichengliudui** [comment]
update mysql-vs to mysql-service.namespace.svc.cluster.local

**Comment by zirain** [comment]
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: mysql-vs
spec:
  gateways:
  - mesh
  hosts:
  - mysql-service
  tcp:
  - match:
    - port: 3306
    route:
    - destination:
        host: mysql-service
        port:
          number: 3306
```

FYI, mysql is [server first protocol](https://istio.io/latest/docs/ops/deployment/requirements/#server-first-protocols)

**Comment by holotrack** [comment]
I changed it to FQDN but still that same, I'm sure when I first try it on different cluster it was working without FQDN

**Comment by GregHanson** [comment]
do you need to specify a port on the request?
```
  hosts:
  - mysql-vs
  tcp:
  - match:
    - port: 3306
```
your VS is defining TCP traffic capture.  The `hosts` field is ignored for TCP based traffic.  The istio sidecar only knows to capture traffic on port 3306 and forward to `mysql-service`, regardless of the hostname

> I'm sure when I first try it on different cluster it was working without FQDN

there may be a port conflict for 3306 if you have more than one K8S Service, ServiceEntry, or TCP based VirtualService defined for port 3306 - which would explain why you are seeing different behavior in different clusters.  Does `istioctl ps` show LDS as STALE for any of the client pods?  or any errors from `istioctl analyze`?
