### ISSUE TITLE
seems that Istio does not validate wrong virtural host

### ISSUE THREAD

**Issue by tackish** [istio/istio#42798]
Hi, team.
I've found some points that It's really serious problem.

When it comes to injection virtual service with yaml, seems that istio does not validate the yaml struct.
for example, 

```
  http:
    - mirror:
        host: abc.local
      mirrorPercentage:
        value: 10
      - name: default
         route:
           - destination:
              host: abc.local
```

above yaml struct is wrong. cause "mirror" and "name" are needed to be same line without "-"
but above configuration can be injected to istio virtual service.

after that istio will occur validation error for the all of the exist virtual service and all of the new pod will be logged with "No Route 404 error" for all virtual service not only "abc.local" from envoy proxy.

Isn't that really dangerous? 
only one changing virtual service could be really deadly whole service issue. 

I think this need to be added to known issues. and need to validate the virtualhost when yaml or json is injected to not be injected to the istio mesh.

Thanks
