### ISSUE TITLE
difference between istioctl manifest generate and istioctl install in mutatingwebhook

### ISSUE THREAD

**Issue by juliantaylor** [istio/istio#42826]
### Bug Description

If a tagged mutatingwebook (e.g. istio-revision-tag-default) exists `istioctl install/upgrade` and istio manifest generate different manifests.
install/upgrade first applies the same manifests as generate, but then changes the selectors to this:

```
  namespaceSelector:
    matchLabels:
      istio.io/deactivated: never-match
  objectSelector:
    matchLabels:
      istio.io/deactivated: never-match
```

While istio manifest generate generates the normal selectors
```
  namespaceSelector:
    matchExpressions:
    - key: istio.io/rev
      operator: In
      values:
      - default
    - key: istio-injection
      operator: DoesNotExist
  objectSelector:
    matchExpressions:
    - key: sidecar.istio.io/inject
      operator: NotIn
      values:
      - "false"
```

This only happens if a tagged mutating hook already exists, the code that does it is here: https://github.com/istio/istio/blob/master/istioctl/pkg/tag/util.go#L154

Imo the generated manifests should be the same as applied in install/upgrade but it also creates problems when you deploy istio with install/upgrade and then apply generated manifests on top to e.g. label and properly prune stuff. This then fails due to a difference in manifests:

```
 Error: failed to install manifests: errors occurred during operation: creating default tag would conflict:
Jan 13 13:25:06 Error [IST0139] (MutatingWebhookConfiguration istio-sidecar-injector) Webhook overlaps with others: [istio-revision-tag-default/namespace.sidecar-injector.istio.io]. This may cause injection to occur twice.
```

### Version

```prose
client version: 1.16.1
control plane version: 1.16.1
data plane version: 1.16.1 (19 proxies)
```
