### ISSUE TITLE
Creating a global Istio Rate limit based on a regex

### ISSUE THREAD

**Issue by sergiosanche** [istio/istio#42829]
Hello,

I have tried to implement the global Istio Rate limit based on a regex following the doc in https://dev.to/tresmonauten/setup-an-ingress-rate-limiter-with-envoy-and-istio-1i9g.

I am using Istio 1.16.

The problem is that it doesn't work and it also complains with the following message in the ingress gateway:

```
2023-01-16T13:58:30.720009Z     warning envoy config    gRPC config for type.googleapis.com/envoy.config.route.v3.RouteConfiguration rejected: type envoy.config.route.v3.RateLimit.Action Using deprecated option 'envoy.config.route.v3.RateLimit.Action.dynamic_metadata' from file route_components.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history for details. If continued use of this field is absolutely necessary, see https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/runtime#using-runtime-overrides-for-deprecated-features for how to apply a temporary and highly discouraged override.
```

I am using the regex ^\/(\w+)\/.*$ that fits requests like:

- /CLIENT1/endpoint1
- /CLIENT2/endpoint1
- /CLIENT2/endpoint2

So that the key *uri* will have the values CLIENT1 or CLIENT2.

The rate limit is not working at all, it does not limit the requests.

The code I am using is:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
data:
  config.yaml: |
    domain: productpage-ratelimit
    descriptors:
      - key: BAR
        value: "CLIENT1"
        rate_limit:
          unit: minute
          requests_per_unit: 1
      - key: BAR
        value: "CLIENT2"
        rate_limit:
          unit: minute
          requests_per_unit: 1
      - key: BAR
        value: "CLIENT3"
        rate_limit:
          unit: minute
          requests_per_unit: 1
      # Any other client will have 100 req/min
      - key: BAR
        rate_limit:
          unit: minute
          requests_per_unit: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-ratelimit
  namespace: istio-system
spec:
  workloadSelector:
    # select by label in the same namespace
    labels:
      istio: ingressgateway
  configPatches:

    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        proxy:
          proxyVersion: ^1\.16.*        
        listener:
          filterChain:
            filter:
              name: 'envoy.filters.network.http_connection_manager'
              subFilter:
                name: 'envoy.filters.http.router'
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.header_to_metadata
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.header_to_metadata.v3.Config
            request_rules:
            - header: ':path'
              on_header_present:
                # use an arbitary name for the namespace
                # will be used later to extract descriptor value
                metadata_namespace: example
                # use an arbitary key for the metadata
                # will be used later to extract descriptor value
                key: uri
                regex_value_rewrite:
                  pattern:
                    # regex matcher
                    google_re2: {}
                    # truncates parameters from path
                    regex: '^\/(\w+)\/.*$'
                  substitution: '\1'
    # The Envoy config you want to modify
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        proxy:
          proxyVersion: ^1\.16.*        
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.header_to_metadata"
      patch:
        operation: INSERT_BEFORE
        # Adds the Envoy Rate Limit Filter in HTTP filter chain.
        value:
          name: envoy.filters.http.ratelimit
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
            # domain can be anything! Match it to the ratelimter service config
            domain: productpage-ratelimit
            failure_mode_deny: true
            timeout: 10s
            rate_limit_service:
              grpc_service:
                envoy_grpc:
                  cluster_name: outbound|8081||ratelimit.default.svc.cluster.local
                  authority: ratelimit.default.svc.cluster.local
              transport_api_version: V3
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-ratelimit-svc
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: VIRTUAL_HOST
    match:
      context: GATEWAY
      routeConfiguration:
        vhost:
          name: ""
          route:
            action: ANY
    patch:
      operation: MERGE
      value:
        rate_limits:
        - actions:
          - dynamic_metadata:
              descriptor_key: BAR
              metadata_key:
                key: example
                path:
                - key: uri
```

Can you help me solving this problem?

Regards!

**Comment by zirain** [comment]
that warning message came from `This field has been deprecated in favor of the [metadata](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto.html?highlight=ratelimit%20action#envoy-v3-api-field-config-route-v3-ratelimit-action-metadata) field`

you should check logs from both envoy and RLS.

**Comment by ashutosh2539** [comment]
Change dynamic_metadata to metadata
`- actions:
          - metadata:
              descriptor_key: BAR
              metadata_key:
                key: example
                path:
                - key: uri
 `

**Comment by blaivs** [comment]
Hey @sergiosanche did you manage to solve the issue? I'm experiencing the same, i tried using `dynamic_metadata` and `metadata` and rate_limit action never gets registered.. so it nevers trigger rate limiting check. 

When I dump the config I get it empty (I also have rate limiting by host which works):

```
    ...
   rate_limits {                                                                                                                                                                                                                                                            
     actions {                                                                                                                                                                                                                                                              
     }                                                                                                                                                                                                                                                                      
   }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
   rate_limits {                                                                                                                                                                                                                                                            
     actions {                                                                                                                                                                                                                                                              
       request_headers {                                                                                                                                                                                                                                                    
         header_name: "host"                                                                                                                                                                                                                                                
         descriptor_key: "HOST"                                                                                                                                                                                                                                             
       }                                                                                                                                                                                                                                                                    
     }                                                                                                                                                                                                                                                                      
   }    
```
My conf patch: 
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
data:
  config.yaml: |
    domain: global-ratelimit
    descriptors:
      - key: HOST
        rate_limit:
          unit: minute
          requests_per_unit: 20
      - key: PATH
        value: "/config" 
        rate_limit:  
          unit: minute
          requests_per_unit: 1
      - key: PATH
        rate_limit:        
          unit: minute
          requests_per_unit: 10
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-ratelimit-svc
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: VIRTUAL_HOST
      match:
        context: GATEWAY
        routeConfiguration:
          gateway: istio-system/main
          portNumber: 443
          portName: https
      patch:
        operation: MERGE
        value:
          rate_limits:
            - actions:
                - metadata:
                    descriptor_key: "PATH"
                    metadata_key:
                      key: "enclave.filter"
                      path:
                        - key: "uri"
            - actions:
                - request_headers:
                    header_name: "host"
                    descriptor_key: "HOST"
```

There's my filter chain config where I also tried to log if the dynamic_metadata value is added to the request, but it errors saying `script log: [string "function envoy_on_request(request_handle)..."]:3: attempt to index a nil value ` .So maybe this is another issue...
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-ratelimit
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        proxy:
          proxyVersion: ^1\.16.*
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.header_to_metadata
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.header_to_metadata.v3.Config
            request_rules:
              - header: ":path"
                on_header_present:
                  metadata_namespace: enclave.filter
                  key: uri
                  type: STRING
                  regex_value_rewrite:
                    pattern:
                      # regex matcher
                      regex: '^(\/[\/\d\w-]+)\??.*$'
                    substitution: "\\1"
    - applyTo: HTTP_FILTER
      match:
        proxy:
          proxyVersion: ^1\.16.*
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.header_to_metadata"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.log_metadata
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
            inline_code: |
              function envoy_on_request(request_handle)

              local info = request_handle:streamInfo():dynamicMetadata():get("envoy.filters.http.header_to_metadata")["enclave.filter"]
              -- FAILS: 
              request_handle:logInfo("uri.h: "..info.uri)
              end
    - applyTo: HTTP_FILTER
      match:
        proxy:
          proxyVersion: ^1\.16.*
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.log_metadata"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.ratelimit
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
            # ensure the domain matches with the domain used in the ratelimit service config
            domain: global-ratelimit
            failure_mode_deny: true
            rate_limit_service:
              grpc_service:
                envoy_grpc:
                  cluster_name: outbound|8081||ratelimit.istio-system.svc.cluster.local
                  authority: ratelimit.istio-system.svc.cluster.local
                timeout: 10s
              transport_api_version: V3

```

**Comment by parmarnikunj** [comment]
I got it solved by just putting header_to_metadata befor ratelimit filter.

**Comment by seun9su** [comment]
> 속도 제한 필터 앞에 header_to_metadata를 넣어 해결했습니다.

Can you give me some example code?

**Comment by pisces-period** [comment]
> I got it solved by just putting header_to_metadata before rate-limit filter.

Hi, could you please elaborate or paste a complete sample snippet?

**Comment by pisces-period** [comment]
@seun9su, in case this is still relevant to you, I was able to finally get it working. I just had to literally put the `header_to_metadata` filter before the `rate-limit` filter, like so:

```yaml
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.header_to_metadata
          typed_config:
            '@type': >-
              type.googleapis.com/envoy.extensions.filters.http.header_to_metadata.v3.Config
            request_rules:
              - header: ':path'
                on_header_present:
                  key: uri
                  metadata_namespace: custom_metadata
                  regex_value_rewrite:
                    pattern:
                      google_re2: {}
                      regex: '^(\/[\/\d\w-]+)\??.*$'
                    substitution: \1
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.ratelimit
          typed_config:
            '@type': >-
              type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
            domain: foobarlis
            failure_mode_deny: false
            rate_limit_service:
              grpc_service:
                envoy_grpc:
                  authority: istio-rate-limit.istio-ingress.svc.cluster.local
                  cluster_name: >-
                    outbound|8081||istio-rate-limit.istio-ingress.svc.cluster.local
              transport_api_version: V3
            timeout: 1s
```
