### ISSUE TITLE
Cluster connect to VM requests did not go through vm-sidecar

### ISSUE THREAD

**Issue by WellyHong** [istio/istio#42822]
### Bug Description

followed the [VM-installation](https://istio.io/latest/docs/setup/install/virtual-machine/) guidance, install & configure istio in virtual machine, connection from vm to cluster is as expect and I can see log in `/var/log/istio/istio.log`

connection from cluster to vm is also success, but the request did not go through vm-sidecar,  I cannot see any inbound request in  `/var/log/istio/istio.log`.  is this a right behavior?

any comments and suggestion will be appreciated.

### Version

```prose
$ istioctl version
control plane version: 1.13.1
data plane version: 1.13.1 (16 proxies), 1.13.0 (1 proxies)

$ kubectl version --short
Client Version: v1.23.3
Server Version: v1.22.11

Istio virtual machine integration runtime:
https://storage.googleapis.com/istio-release/releases/1.13.9/deb/istio-sidecar.deb
```

### Additional Information

configure workload entry command as below:

`istioctl x workload entry configure -f workloadgroup.yaml -o $WORK_DIR --clusterID $CLUSTER --autoregister --externalIP my_vm_public_ip`

**Comment by hzxuzhonghu** [comment]
To ensure iptables are setup correctly https://istio.io/latest/docs/ops/diagnostic-tools/virtual-machines/#iptables

**Comment by WellyHong** [comment]
hi @hzxuzhonghu,

I'm not familiar with network, from my understanding, I think that envoy proxy will highjack all inbounds and redirect to **15006** port, is it right?

below is iptable, workloadentry and service setting
any suggestion will be appreciated.

```
*nat
:PREROUTING ACCEPT [9:646]
:INPUT ACCEPT [9:540]
:OUTPUT ACCEPT [27:1996]
:POSTROUTING ACCEPT [11:1096]
:DOCKER - [0:0]
:ISTIO_INBOUND - [0:0]
:ISTIO_IN_REDIRECT - [0:0]
:ISTIO_OUTPUT - [0:0]
:ISTIO_REDIRECT - [0:0]
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A OUTPUT -p udp -m udp --dport 53 -m owner --uid-owner 997 -j RETURN
-A OUTPUT -p udp -m udp --dport 53 -m owner --gid-owner 997 -j RETURN
-A OUTPUT -d 127.0.0.53/32 -p udp -m udp --dport 53 -j REDIRECT --to-ports 15053
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A POSTROUTING -s 172.17.0.2/32 -d 172.17.0.2/32 -p tcp -m tcp --dport 8080 -j MASQUERADE
-A DOCKER -i docker0 -j RETURN
-A DOCKER ! -i docker0 -p tcp -m tcp --dport 80 -j DNAT --to-destination 172.17.0.2:8080
-A ISTIO_INBOUND -p tcp -m tcp --dport 15008 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A ISTIO_OUTPUT -s 127.0.0.6/32 -o lo -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -p tcp -m tcp ! --dport 53 -m owner --uid-owner 997 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -p tcp -m tcp ! --dport 53 -m owner ! --uid-owner 997 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 997 -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --gid-owner 997 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -p tcp -m tcp ! --dport 53 -m owner ! --gid-owner 997 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 997 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.53/32 -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 15053
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
```

```yaml
apiVersion: networking.istio.io/v1beta1
kind: WorkloadEntry
metadata:
  annotations:
    istio.io/autoRegistrationGroup: vm-app
  generation: 1
  labels:
    app: vm-app
    service.istio.io/canonical-name: vm-app
    service.istio.io/canonical-revision: latest
  name: vm-app-public.ip-vm-network
  namespace: vm
  ownerReferences:
  - apiVersion: networking.istio.io/v1alpha3
    controller: true
    kind: WorkloadGroup
    name: vm-app
spec:
  address: vm_public_ip
  labels:
    app: vm-app
    service.istio.io/canonical-name: vm-app
    service.istio.io/canonical-revision: latest
  network: vm-network
  serviceAccount: vm-app
```

```yaml
apiVersion: v1
kind: Service
metadata:
  name: vm-svc
  namespace: vm
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: vm-app
```
