### ISSUE TITLE
Multi Primary cluster - service discovery from istio proxy sidecar

### ISSUE THREAD

**Issue by cheevs** [istio/istio#42849]
**Describe the feature request**
Service discovery, dns resolution, for multi primary cluster setup does not work from the Istio proxy sidecar in a remote cluster.

Unsure if this should be a feature request to the Istio project or envoy.

Example of a jaeger configuration that only works configured on a local cluster.

Tested on Istio version 1.11.2
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator 
spec:
  values:
    global:
      tracer:
        zipkin:
          address: jaeger-jaeger-operator-jaeger-collector.jaeger.svc.cluster.local:9411
```
logs from the istio proxy in a remote cluster
```
2023-01-17T17:48:35.658091Z     debug   envoy router    [C0][S10049687786385441187] cluster 'zipkin' match for URL '/api/v2/spans'
2023-01-17T17:48:35.658142Z     debug   envoy upstream  no healthy host for HTTP connection pool
2023-01-17T17:48:35.658288Z     debug   envoy http      async http request response headers (end_stream=false):
':status', '503'
'content-length', '19'
'content-type', 'text/plain'
```

**Describe alternatives you've considered**
* run the same workload in all the clusters
* use the internal ingress gateway instead of the east west gateway

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
