### ISSUE TITLE
gateway label not found in case of istio helm install

### ISSUE THREAD

**Issue by ar-bella-jeong** [istio/istio#42911]
### Bug Description

I installed istio using helm charts such as base, istio-discovery and gateway.
and then, I deployed the sample application to test as below the link.
https://istio.io/latest/docs/setup/getting-started/#bookinfo

It works well, but when I checked istioctl analyze, It showed the error as the following log.
```
Error [IST0101] (Gateway sandbox/bookinfo-gateway) Referenced selector not found: "istio=gateway"
```

I checked gateway pod's label, I'm pretty sure the label of gateway pod is 'istio=gateway'
and the proxy_config of ingress gateway is also set all I want. so I could access bookinfo page.

Nevertheless anyone knows is there any reason istioctl shows the error log?

### Version

```prose
# istio
client version: 1.16.1
control plane version: 1.16.1
data plane version: 1.16.1 (7 proxies)

# kubectl
Client Version: v1.22.6
Server Version: v1.22.15

# helm
use flux 0.38.2
helm 3.10.3
```

**Comment by GregHanson** [comment]
checking the sample provided in the 1.16 download: [link](https://raw.githubusercontent.com/istio/istio/release-1.16/samples/bookinfo/networking/bookinfo-gateway.yaml)
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bookinfo-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
```
the selector should be `istio: ingressgateway`, have you modified the examples?
