### ISSUE TITLE
workloadSelector result in ServiceEntry is wrong after change the labels in Pods

### ISSUE THREAD

**Issue by rajatsharma94** [istio/istio#42921]
### Bug description

Similar to https://github.com/istio/istio/issues/25678, currently if a K8s pod changes labels, the workload instance in a ServiceEntry using workloadSelector are not updated.

### Setup
Service Entry
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: test-se
  namespace: default
spec:
  hosts:
  - www.test.com
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 80
    protocol: HTTP
  resolution: STATIC
  workloadSelector:
    labels:
      ready: "true"
      app: "test"
 ```
Initial Pod Value
 ```
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: default
  labels:
    ready: "true"
    app: "test"
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
```
Changed Pod Value
 ```
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: default
  labels:
    ready: "false"
    app: "test"
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
```

### Expected Behaviour

The pod should appear as the SE workload instance when the label is `ready: "true"` and should be removed from the list of workload instances when the label is changed to `ready: "false"`

### Actual Behaviour

The pod is not removed from the list of SE workload instances. Moreover since the labels don't match anymore, if the pod is even deleted, the SE workload instance is not removed.

### Version

```prose
client version: 1.13.1
control plane version: 1.15.0
data plane version: 1.15.0 (9 proxies)
```

### Additional Information

The bug can be mitigated by changing the workloadSelector in ServiceEntry. This recreates the list of workload instances again and removes the broken workload instance from Service Entry.
