### ISSUE TITLE
Authz Port Matching when HBONE enabled on sidecar results in RBAC denied

### ISSUE THREAD

**Issue by dhawton** [istio/istio#42929]
### Bug Description

Sidecars when HBONE enabled do not have Destination Port rules apply correctly.

Steps to reproduce:
1. Install 1.16.x with `ambient` profile
2. Create two namespaces (other, test) with `istio-injection=enabled` labelled
3. Deploy sleep to `other`, httpbin to `test`
4. Apply the following Authz policy:
```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: httpbin
  namespace: test
spec:
  selector:
    matchLabels:
      app: httpbin
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/other/sa/sleep"]
    to:
    - operation:
        paths:
        - /get
        methods: ["GET"]
        ports: ["80"]
```
5. Make a curl request from sleep to httpbin's /get endpoint

Expected result:

200 response

Actual result:

403: `RBAC: access denied`

May need similar work to https://github.com/istio/istio/issues/41204

### Version

```prose
> i version
client version: 1.16.1
control plane version: 1.16.1
data plane version: 1.16.1 (4 proxies)
> k version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.25.3
```

Also affects the `experimental-ambient` branch
