### ISSUE TITLE
Evaluation order with VirtualService and EnvoyFilter

### ISSUE THREAD

**Issue by kiich** [istio/istio#42944]
### Bug Description

I have a setup in my environment where I utilise Istio resources to do auth between apps and one of the things it does is to inject wasm filters which injects a token depending on the endpoint the client app is trying to reach out to.

When using the FQDN for the endpoint, this all works great. However, I now have a need to use "pod.namespace" convention to achieve the same thing and one way we are proposing to do this using `VirtualService` like so:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: foo
spec:
  gateways:
  - mesh
  hosts:
  - foo.bar.svc.cluster.local
  http:
  - route:
    - destination:
        host: my_FQDN.com
      headers:
        request:
          set:
            host: my_FQDN.com
```
so the idea is if my app calls out to `foo.bar`, VirtualService will send it to `my_FQDN.com` by also setting the `host` header so in the wasm, i can carry on using the `my_FQDN.com`.

This does not seem to work and it seems the host header set logic is NOT happening before like we anticipated.
According to the docs, it did seem like the above should work but wondering if we read it wrong.

Apologies for the not-so-clear example above - hope it is enough to illustrate our issue!

### Version

```prose
istioctl version
client version: 1.13.1
control plane version: 1.16.0
data plane version: 1.16.0
```
```

**Comment by ymesika** [comment]
Can you check whether adding the request header to all destinations (for you it doesn't matter) works?
I.e.
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: foo
spec:
  gateways:
  - mesh
  hosts:
  - foo.bar.svc.cluster.local
  http:
  - headers:
      request:
        set:
          host: my_FQDN.com
    route:
    - destination:
        host: my_FQDN.com      
```

**Comment by kiich** [comment]
Thanks for the suggestion @ymesika - I've realised I only pasted snippet of my actual `VirtualService` which I should have done in the original post - it actually looks like:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: foo
spec:
  gateways:
  - mesh
  hosts:
  - foo.bar.svc.cluster.local
  http:
  - route:
    - destination:
        host: my_FQDN.com
      headers:
        request:
          set:
            host: my_FQDN.com
      weight: 50
    - destination:
        host: my_other_FQDN.com
      headers:
        request:
          set:
            host: my_other_FQDN.com
      weight: 50
```

So with that, i think i can not set the `host` header for all outbound right?
Thanks for the suggestion anyways - I apologise for not being as detailed I should have been!
