### ISSUE TITLE
Custom CA Integration with K8s CSR fails with cert-manager self-signed CA

### ISSUE THREAD

**Issue by jaellio** [istio/istio#42977]
### Bug Description
**Bug report**: [bug-report.tar.gz](https://github.com/istio/istio/files/10494770/bug-report.tar.gz)

When working through the [Custum CA Integration with k8s CSR demo](https://istio.io/latest/docs/tasks/security/cert-management/custom-ca-k8s/), istiod failed to provide a certificate to istio-ingressgateway resulting in istiod and istio-ingressgateway failures. This issue occurred after [deploying istio with the default cert signer information](https://istio.io/latest/docs/tasks/security/cert-management/custom-ca-k8s/#deploy-istio-with-default-cert-signer-info) as specified in the demo. 

**Demo environment**:
- AKS cluster

**Errors in Istiod**:
```bash
2023-01-24T20:41:14.904656Z     error   serverca        CSR signing error (failed to find root cert from signed cert-chain (found root cert is not a ca type cert: &{[...]} spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account))
```
**Errors in istio-ingressgateway**:
```bash
2023-01-24T22:44:47.922416Z     info    ads     ADS: new connection for node:istio-ingressgateway-7c946df4ff-4pjkt.istio-system-902
2023-01-24T22:44:47.956442Z     warn    sds     failed to warm certificate: failed to generate workload certificate: create certificate: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.0.215.14:15012: connect: connection refused"
2023-01-24T22:44:48.196471Z     warn    ca      ca request failed, starting attempt 1 in 107.722649ms
2023-01-24T22:44:48.305036Z     warn    ca      ca request failed, starting attempt 2 in 210.596616ms
2023-01-24T22:44:48.516831Z     warn    ca      ca request failed, starting attempt 3 in 379.315277ms
2023-01-24T22:44:48.897101Z     warn    ca      ca request failed, starting attempt 4 in 755.246519ms
```

**Verifications**:
I verified the specifications for the demo were successfully applied. istiod recieved the correct environment variables:
```yaml
 env:
    - name: CERT_SIGNER_DOMAIN
      value: clusterissuers.cert-manager.io
    - name: EXTERNAL_CA
      value: ISTIOD_RA_KUBERNETES_API
    - name: REVISION
      value: default
    - name: JWT_POLICY
      value: third-party-jwt
    - name: PILOT_CERT_PROVIDER
      value: k8s.io/clusterissuers.cert-manager.io/istio-system
```
istiod successfully picked up on the environement variables and correctly used the istio-system cert-manager issuer to issue its own certificate:
```bash
2023-01-24T22:51:11.045175Z     info    Generating K8S-signed cert for [istiod.istio-system.svc istiod-remote.istio-system.svc istio-pilot.istio-system.svc] using signer clusterissuers.cert-manager.io/istio-system
2023-01-24T22:51:11.337886Z     info    x509 cert - Issuer: "CN=istio-system", Subject: "O=", SN: 368c7ba0d9aaa81e09060977f266bd09, NotBefore: "2023-01-24T22:51:11Z", NotAfter: "2033-01-21T22:51:11Z"
```
Cert-manager was also install using the correct feature gate:
```bash
helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.11.0 --set featureGates=ExperimentalCertificateSigningRequestControllers=true
```
```yaml
Containers:
  cert-manager-controller:
    Container ID:  containerd://48338bbf7cf9d056d0cfc373da42665c66b985b8d5e9d1ae8e34401d34d23a06
    Image:         quay.io/jetstack/cert-manager-controller:v1.11.0
    Image ID:      quay.io/jetstack/cert-manager-controller@sha256:d429b6d696e0ef47cff1d15241c6ffaac351e38ac22664b82fafa771d615b89a
    Port:          9402/TCP
    Host Port:     0/TCP
    Args:
      --v=2
      --cluster-resource-namespace=$(POD_NAMESPACE)
      --leader-election-namespace=kube-system
      --acme-http01-solver-image=quay.io/jetstack/cert-manager-acmesolver:v1.11.0
      --feature-gates=ExperimentalCertificateSigningRequestControllers=true
      --max-concurrent-challenges=60
```

**Findings**:
The error log in istiod (`failed to find root cert from signed cert-chain`) was generated by `[SignWithCertChain()](https://github.com/istio/istio/blob/4f3e28b2c580ce83c8a9a6d0c8cb20738d9c6a32/security/pkg/pki/ra/k8s_ra.go#L115)` in `k8s_ra.go`. The method is described as follows:
```go
// SignWithCertChain is similar to Sign but returns the leaf cert and the entire cert chain.
// root cert comes from two sources, order matters:
// 1. Specified in mesh config
// 2. Extract from the cert-chain signed by the CSR signer.
```
However, the ordering of the checks to find the cert chain in the code did not match the description:
```go
rootCertFromCertChain, err = util.FindRootCertFromCertificateChainBytes(cert)
if err != nil {
	return nil, raerror.NewError(raerror.CSRError, fmt.Errorf("failed to find root cert from signed cert-chain (%v)", err.Error()))
}
rootCertFromMeshConfig, err = r.GetRootCertFromMeshConfig(certSigner)
if err != nil {
	pkiRaLog.Infof("failed to find root cert from mesh config (%v)", err.Error())
}
```
To obtain the root cert, the cert chain is checked first before checking the MeshConfig. Additionally, if the root is not found in the cert chain, an error is returned rather than also checking if the root is in the MeshConfig.

**Current Hypothesis**:
When calling [`Sign` on the `csrPem`](https://github.com/istio/istio/blob/4f3e28b2c580ce83c8a9a6d0c8cb20738d9c6a32/security/pkg/pki/ra/k8s_ra.go#L116) cert-manager creates a certificate using the `istio-system` Issuer (created in the demo) created from a self-signed Issuer. Istio expects that the returned cert contains the certificate chain. In this case, the certificate does not contain the certificate chain and therefore does not contain the root certificate. The subsequent call to `FindRootCertFromCertificateChainBytes(cert)` will return an error and [`SignWithCertChain` will return `failed to find root cert from signed cert-chain`](https://github.com/istio/istio/blob/4f3e28b2c580ce83c8a9a6d0c8cb20738d9c6a32/security/pkg/pki/ra/k8s_ra.go#L130).

**Proposal**:
- Update the ordering of `FindRootCertFromCertificateChainBytes` and `GetRootCertificateFromMeshConfig`
- Do not return an error in `SignWithCertChain` when `FindRootCertificateFromCertificateChainBytes` returns an error
- Write unit or e2e tests to verify this functionality

### Version

```prose
$ istioctl version
client version: 1.16.0
control plane version: 1.16.0

$ kubectl version --short
Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.24.6
```
