### ISSUE TITLE
Istio routing to same postgres db even when separate gateway and virtual service exist for separate DBs

### ISSUE THREAD

**Issue by utkarsh079** [istio/istio#42984]
### Bug Description

I am running two postgres DBs in pods and trying to access the pods via Istio ingressgateway (with Network Load Balancer).
i have created 2 separate gateways and Virtual services for each DB (pg3.example.com and pg4.example.com). For some reason, when I am trying to connect with hostname, it connects to same host every time.

Gateways:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: postgres-gateway
  namespace: istio-test
spec:
  selector:
    istio: ingressgateway 
  servers:
  - hosts:
    - 'pg3.example.com'
    port:
      number: 5432
      name: tcp-postgres
      protocol: TCP
```

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: postgres-gateway-2
  namespace: istio-test
spec:
  selector:
    istio: ingressgateway 
  servers:
  - hosts:
    - 'pg4.example.com'
    port:
      number: 5432
      name: tcp-postgres
      protocol: TCP
```

VirtualServices:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: postgres-vs
  namespace: istio-test
spec:
  hosts:
  - 'pg3.example.com'
  gateways:
  - postgres-gateway
  tcp:
  - match:
    - port: 5432
    route:
    - destination:
        host: postgresql-dev
        port:
          number: 5432
        subset: postgres-0
```

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: postgres-vs-2
  namespace: istio-test
spec:
  hosts:
  - 'pg4.example.com'
  gateways:
  - postgres-gateway-2
  tcp:
  - match:
    - port: 5432
    route:
    - destination:
        host: postgresql-new-dev-istio
        port:
          number: 5432
        subset: postgres-1
```

Destination rules;

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: postgres-0
  namespace: istio-test
spec:
  host: postgresql-dev.istio-test.svc.cluster.local
  subsets:
  - labels:
      app.kubernetes.io/instance: postgresql-dev
    name: postgres-0
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
      sni: postgresql-dev.istio-test.svc.cluster.local
```

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: postgres-1
  namespace: istio-test
spec:
  host: postgresql-new-dev-istio.istio-test.svc.cluster.local
  subsets:
  - labels:
      app.kubernetes.io/instance: postgresql-new-dev-istio
    name: postgres-1
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
      sni: postgresql-new-dev-istio.istio-test.svc.cluster.local
```

### Version

```prose
istioctl version                                                                                                                  
client version: 1.16.1
control plane version: 1.16.1
data plane version: 1.16.1 (4 proxies)

kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.21.14-eks-ffeb93d

helm version --short
v3.10.1+g9f88ccb
```

### Additional Information

Expected behavior
psql should connect to respective db

Actual behavior
psql is connecting to only pg3.example.com even when trying with host pg4.example.db

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by GregHanson** [comment]
```
    port:
      number: 5432
      name: tcp-postgres
      protocol: TCP
```
`protocol: TCP` means traffic can only be matched against port, protocol, IP addresses, and CIDR blocks.  I would expect  `istioctl proxy-status` to show some STALE LDS for your gateway  or `istioctl analyze -A` to report some conflicts since you cannot define 2 separate TCP services on the same port without providing an IP or CIDR block to distinguish.
