### ISSUE TITLE
(Question) Should destination host for virtual service always be service??

### ISSUE THREAD

**Issue by kimkihoon0515** [istio/istio#43034]
Hi I'm trying to fix infinite loop on logout in kubeflow while using keycloak. (Which is already issued here https://github.com/kubeflow/kubeflow/issues/5704)
Here's what I'm trying to do.
I'm trying to make virtual serivce in kubeflow namespace.
When i press logout, it redirects to `http://whateverdomain/logout` and this causes infinite loop.
So I'm trying to make virtual service and change it to right redirect destination.
Here's my yaml file
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: oauth2-proxy-logout
  namespace: kubeflow
spec:
  gateways:
  - kubeflow/kubeflow-gateway
  hosts:
  - "*"
  http:
  - match:
    - uri:
        exact: /logout
    route:
    - destination:
        **host: http://localhost:8080/auth/realms/<my_realm>/protocol/openid-connect/logout** -> Is it possible??
```
I'm not sure host of destination should always be service.namespace.svc.cluster.local or not.
