### ISSUE TITLE
istioctl proxyconfig not working with custom proxyAdminPort

### ISSUE THREAD

**Issue by zirain** [istio/istio#43063]
### Bug Description

install istio with follwing iop:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    accessLogFile: /dev/stdout  
    defaultConfig:
      proxyAdminPort: 19000
```

`istioctl pc all details-v1-7d4d9d5fcb-l2jhm` will fail with following error message:
```
2023-01-31T11:18:44.134020Z     error   klog    an error occurred forwarding 43441 -> 15000: error forwarding port 15000 to pod 98f316bbf8c802dd36fbbdc22f64debca01a8ff19742f834b1c72b46565e818b, uid : failed to execute portforward in network namespace "/var/run/netns/cni-e55db30e-592f-bd2e-9238-4c0206e92781": failed to connect to localhost:15000 inside namespace "98f316bbf8c802dd36fbbdc22f64debca01a8ff19742f834b1c72b46565e818b", IPv4: dial tcp4 127.0.0.1:15000: connect: connection refused IPv6 dial tcp6 [::1]:15000: connect: connection refused 
```

### Version

```prose
client version: 1.16.1
control plane version: 1.17
data plane version: 1.17-dev (9 proxies)
```
