### ISSUE TITLE
Socket disconnecting on each hour

### ISSUE THREAD

**Issue by Rez0k** [istio/istio#43066]
Hi,

One of my micro services usually connect to a Redis server with web-socket (the connection should be alive for a long time), and in each hour, I am getting: `Socket closed unexpectedly`, and then my service reconnecting.

I tried setting keepaliveMaxServerConnectionAge to 24h or even more, 
I also tried to set:
```
trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
        connectTimeout: 30ms
        tcpKeepalive:
          time: 7200s
          interval: 75s
```
in the service DestinationRule
I even tried: `excludeOutboundPorts: "6379"` to skip all redis connections from passing through envoy.

Nothing works except removing the envoy sidecar container completely from the service, only without the envoy container the redis doesn't get disconnected.

Any advice?
I am pretty sure it's some configuration that I need to update in the envoy sidecar.

Thanks!

**Comment by ramaraochavali** [comment]
Is this happening even though there is traffic during that period ?

**Comment by Rez0k** [comment]
> Is this happening even though there is traffic during that period ?

in this service, there is no traffic (I am testing istio in test env)

**Comment by ramaraochavali** [comment]
Ok. Then you may be hitting idle_time_out https://github.com/istio/api/blob/master/networking/v1alpha3/destination_rule.proto#L777

**Comment by Rez0k** [comment]
> Ok. Then you may be hitting idle_time_out https://github.com/istio/api/blob/master/networking/v1alpha3/destination_rule.proto#L777

don't mind the last comment, I changed my service destionation-rule to be like:
```
host: <service-name>
trafficPolicy:
    connectionPool:
      http:
        idleTimeout: 360000000s
```

still, after an hour I am still getting `Socket closed unexpectedly`.
Other ideas?
