### ISSUE TITLE
VERIFY_CERTIFICATE_AT_CLIENT does not apply to mutual tls

### ISSUE THREAD

**Issue by irregular-ferret** [istio/istio#43078]
### Bug Description

When enabling VERIFY_CERTIFICATE_AT_CLIENT and providing MTLS configuration (without a CA), Istio still looks for a defined CA certificate as part of the MTLS configuration. i.e

VERIFY_CERTIFICATE_AT_CLIENT = true 

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: server-com-mtls
spec:
  host: server.com
  trafficPolicy:
    tls:
      mode: MUTUAL
      credentialName: certificate-credentials
```

```
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: certificate-credentials
data:
  cert: CERTIFICATE
  key: KEY
  # Do not include CACert
```

When using 'SIMPLE' tls  VERIFY_CERTIFICATE_AT_CLIENT works as expected.

### Version

```prose
client version: 1.14.3
control plane version: 1.14.3
data plane version: 1.14.3

Client Version: v1.21.8
Server Version: v1.21.8
```
