### ISSUE TITLE
wasm: providing platform-native authentication for downloading wasm OCI images on private registry

### ISSUE THREAD

**Issue by ingwonsong** [istio/istio#43080]
Currently, Wasm API provides `ImagePullSecret` for accessing a private registry.
Basically, `ImagePullSecret` means long-lived secret, which is generally not recommended.

But, if the OCI image is on a private registry of a cloud platform (e.g., ECR/ACR/GCR) and the cluster is in the cloud platform,
we can provide safer way to access the private registry.

Moreover, in case of ECR on AWS, there is no notion of long-lived secret. Therefore, managing `ImagePullSecret` in manual way is a pain point.

This is the issue for tracking this topic.

** Previous Efforts **

There were some approaches, but, due to the issue of splitting _platform-specific_ code from istio code base,  they were halt.
* Previous PR
  - https://github.com/istio/istio/pull/39487
  - https://github.com/istio/istio/pull/41970

To explore the alternative approaches, the document below was discussed, but there was no clear conclusion.
* Design doc
  - https://tinyurl.com/2b9byunv

As an alternative approach, [docker-credential-magic-proxy](https://github.com/ingwonsong/docker-credential-magic-proxy) - a kind of downloading proxy/cache which does the authentication on behalf of the istio agent - was implemented, but it has an limitation that it requires additional workloads in the cluster.
 
**Affected product area (please put an X in all that apply)**

[X] Extensions and Telemetry

**Comment by ingwonsong** [comment]
cc @ramaraochavali

**Comment by ramaraochavali** [comment]
Thank you so much for creating this issue @ingwonsong

**Comment by johnkeates** [comment]
Would the platform-specific split-off also work for other fetcher methods? We tried OCI first as well, but like others wrote, if you are using ECR that doesn't seem viable right now, so we then went for S3 HTTP next, which does allow pre-signed URLs for up to 7 days, or subnet based access control, but this makes me wonder if HTTP authentication could be extended for things like sigv4 which is also used when making requests to an AWS API like ECR.

**Comment by JPumpkin** [comment]
Has there been any further progress on this issue?

**Comment by sarasensible** [comment]
We worked around this issue by leveraging External Secrets Operator which we were already using in our cluster.  ESO is capable of using an IRSA enabled service account to populate a secret with the token via ECRAuthorizationToken.  We used a ClusterGenerator since our external secrets helm install is in a different namespace than our wasm plugin.

https://external-secrets.io/latest/api/generator/ecr/

We created a role with the AmazonEC2ContainerRegistryReadOnly policy attached, then annotated our service account to reference this role.  We had to create a trust policy that allowed the service account to connect via OIDC.

Note that I used the `${my_variable}` format for certain variables since we are using Terraform to provision everything so these resources all begin their lifecycle as Terraform templates (.tftpl).  Use your own template interpolator or just hard code wherever you see `${my_variable}`.

Trust Relationship on the role
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::${aws_account}:oidc-provider/oidc.eks.${cluster_region}.amazonaws.com/id/${cluster_OIDC_identifier}"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringLike": {
                    "oidc.eks.us-east-2.amazonaws.com/id/${cluster_OIDC_identifier}:sub": "system:serviceaccount:*:ecr-pull-images-service-account",
                    "oidc.eks.us-east-2.amazonaws.com/id/${cluster_OIDC_identifier}:aud": "sts.amazonaws.com"
                }
            }
        }
    ]
}
```

Service account
```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${aws_account}:role/ecr-pull-images-role
  name: ecr-pull-images-service-account
  namespace: wasm-plugin-namespace
```

ESO ECR Token Cluster Generator
```
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: ecr-wasm-token
spec:
  kind: ECRAuthorizationToken
  generator: 
    ecrAuthorizationTokenSpec:
      region: ${private_registry_region}
      auth:
        jwt:
          serviceAccountRef:
            name:  ecr-pull-images-service-account
            namespace: wasm-plugin-namespace

```

External Secret that generates the secret for imagepullsecrets to reference
```
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ecr-wasm-pull-secret
  namespace: wasm-plugin-namespace
spec:
  refreshInterval: 6h
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ClusterGenerator
        name: ecr-wasm-token
  target:
    name: ecr-wasm-pull-secret # Secret name
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: '{"auths":{"${aws_account}.dkr.ecr.${private_registry_region}.amazonaws.com":{"username":"{{ .username }}","password":"{{ .password }}","auth":"{{ printf "%s:%s" .username .password | b64enc }}"}}}'
```

Wasm Plugin
```
apiVersion: extensions.higress.io/v1alpha1
kind: WasmPlugin
metadata:
  name: my-waf
  namespace: wasm-plugin-namespace
spec:
  url: ${private_registry_waf_image}
  imagePullSecret: ecr-wasm-pull-secret
```

Of course, this is a lot of work when the plugin should really just support this.  Since it has been three years with no movement though I'm not going to wait around for it to happen.
