### ISSUE TITLE
Sidecar protocol detection fails when WS and HTTP APIs are exposed on the same port.

### ISSUE THREAD

**Issue by monoxane** [istio/istio#43154]
### Bug Description

I have a Golang/GinGonic service that provides both HTTP/REST and Websocket APIs on the same port through HTTP upgrades on specific paths. When this is exposed with the following service (port name the same on the pod template too):
```
apiVersion: v1
kind: Service
metadata:
  name: the-usvc
spec:
  ports:
    -
      name: http-0
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: the-usvc
  type: ClusterIP
```
All WS requests succeed, but all REST/HTTP requests fail with `HTTP 426 Upgrade Required`.

When exposed as: 
```
apiVersion: v1
kind: Service
metadata:
  name: the-usvc
spec:
  ports:
    -
      name: port-0
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: the-usvc
  type: ClusterIP
```
Everything works absolutely perfectly.

The reason this was hard to troubleshoot is the debugging output shows a lot more information about the request as `http`, and not a whole lot as `port`, along with dozens of GitHub issues and forum posts saying this is the expected result when using HTTP/1.0, leading me to think that another reverse proxy or loadbalancer along the way might be force downgrading the HTTP requests, which is definitely not the case.

### Version

```prose
Not using istioctl, installed with the helm chart
Helm: v3.7.2+g663a896
Charts: 
- istio-base: 1.16.2
- istiod: 1.16.2
Images:
- docker.io/istio/proxyv2:1.16.2
- docker.io/istio/pilot:1.16.2

Clusters:
$ kubectl version --short # Cluster 1
Client Version: v1.24.8
Kustomize Version: v4.5.4
Server Version: v1.24.8-gke.2000

$ kubectl version --short # Cluster 2
Client Version: v1.25.2
Kustomize Version: v4.5.7
Server Version: v1.25.2
```
