### ISSUE TITLE
Telemetry: ALL_METRICS doesn't seem to work

### ISSUE THREAD

**Issue by Stono** [istio/istio#43155]
### Bug Description

I have the following telemetry v2 configuration:

```
spec:
  metrics:
  - providers:
    - name: prometheus
    overrides:
    - disabled: true
      match:
        metric: ALL_METRICS
        mode: SERVER
    - tagOverrides:
        destination_canonical_service:
          operation: REMOVE
        source_canonical_service:
          operation: REMOVE
        destination_principal:
          operation: REMOVE
        source_principal:
          operation: REMOVE
        connection_security_policy:
          operation: REMOVE
        grpc_response_status:
          operation: REMOVE
        source_version:
          operation: REMOVE
        destination_version:
          operation: REMOVE
        request_protocol:
          operation: REMOVE
        source_canonical_revision:
          operation: REMOVE
        destination_canonical_revision:
          operation: REMOVE
        source_cluster:
          operation: REMOVE
        destination_cluster:
          operation: REMOVE
        destination_app:
          operation: REMOVE

    - match:
        metric: REQUEST_DURATION
      tagOverrides:
        response_code:
          operation: REMOVE
        response_flags:
          operation: REMOVE
        source_cluster:
          operation: REMOVE
        destination_cluster:
          operation: REMOVE

    - match:
        metric: REQUEST_SIZE
      tagOverrides:
        response_code:
          operation: REMOVE
        response_flags:
          operation: REMOVE
        source_cluster:
          operation: REMOVE
        destination_cluster:
          operation: REMOVE

    - match:
        metric: RESPONSE_SIZE
      tagOverrides:
        response_code:
          operation: REMOVE
        response_flags:
          operation: REMOVE
        source_cluster:
          operation: REMOVE
        destination_cluster:
          operation: REMOVE
```

However with this configuration, I am still seeing `reporter=destination` metrics, despite the `SERVER` disabled.

If I change that first part to:

```
spec:
  metrics:
  - providers:
    - name: prometheus
    overrides:
    - disabled: true
      match:
        metric: REQUEST_COUNT
        mode: SERVER
    - disabled: true
      match:
        metric: REQUEST_DURATION
        mode: SERVER
    - disabled: true
      match:
        metric: REQUEST_SIZE
        mode: SERVER
    - disabled: true
      match:
        metric: RESPONSE_SIZE
        mode: SERVER
```

eg, explicitly disabling the `SERVER` for each of the metrics (instead of using `ALL_METRICS`), it works.

### Version

```prose
1.16.2
```

**Comment by kyessenov** [comment]
CC @lei-tang @zirain

**Comment by zirain** [comment]
will take a look later

**Comment by zirain** [comment]
@Stono can you share the output of running `istioctl bug-report`

**Comment by Stono** [comment]
@zirain will ping you on slack

**Comment by Stono** [comment]
Just checking, was this fixed by https://github.com/istio/istio/issues/43178 ?

**Comment by zirain** [comment]
please try with following configuration:

```yaml
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: disable-server-metrics
  namespace: istio-system
spec:
  metrics:
    - providers:
        - name: prometheus
      overrides:
        - disabled: true
          match:
            metric: ALL_METRICS
            mode: SERVER
        - match:
            mode: CLIENT
          tagOverrides:
            destination_canonical_service:
              operation: REMOVE
            source_canonical_service:
              operation: REMOVE
            destination_principal:
              operation: REMOVE
            source_principal:
              operation: REMOVE
            connection_security_policy:
              operation: REMOVE
            grpc_response_status:
              operation: REMOVE
            source_version:
              operation: REMOVE
            destination_version:
              operation: REMOVE
            request_protocol:
              operation: REMOVE
            source_canonical_revision:
              operation: REMOVE
            destination_canonical_revision:
              operation: REMOVE
            source_cluster:
              operation: REMOVE
            destination_cluster:
              operation: REMOVE
            destination_app:
              operation: REMOVE
        - match:
            mode: CLIENT
            metric: REQUEST_DURATION
          tagOverrides:
            response_code:
              operation: REMOVE
            response_flags:
              operation: REMOVE
            source_cluster:
              operation: REMOVE
            destination_cluster:
              operation: REMOVE
        - match:
            mode: CLIENT
            metric: REQUEST_SIZE
          tagOverrides:
            response_code:
              operation: REMOVE
            response_flags:
              operation: REMOVE
            source_cluster:
              operation: REMOVE
            destination_cluster:
              operation: REMOVE
        - match:
            mode: CLIENT
            metric: RESPONSE_SIZE
          tagOverrides:
            response_code:
              operation: REMOVE
            response_flags:
              operation: REMOVE
            source_cluster:
              operation: REMOVE
            destination_cluster:
              operation: REMOVE
```
