### ISSUE TITLE
Telemetry: disabling ALL_METERS does not work as expected

### ISSUE THREAD

**Issue by zirain** [istio/istio#43178]
the following configuration will disable all metrics from both server and client side:

```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: disable-metrics
  namespace: istio-system
spec:
  metrics:
    - overrides:
        - disabled: true
          match:
            metric: ALL_METRICS
            mode: CLIENT
      providers:
        - name: prometheus
```
