### ISSUE TITLE
authority of route rule rewrite not work 

### ISSUE THREAD

**Issue by aimuke** [istio/istio#4320]
version：istio: 0.6.0 +  Ubuntu 16.04.2 LTS

Hi, 

I run bookinfo example in kube by the guide. I did some changes of the example to test the authority of routerule rewrite. But I found it did not work. Can someone give me a hint? Below are what I did:

1. I changed the detail  request url from 'http://details:9080/details/0' to 'http://ratings:9080/v1/details/0' in productpage service,and restart the service.
2. add a rewrite rule(**detail-rewrite**) of detail to rewrite "/v1/details" to '/details'
3. add a redirect rule(**rate2detail**) of ratings to redirect 'ratings' to 'details'
4. refresh the demo page. the demo is ok, it can get the detail info. **(redirect success)**
5. then I replace **rate2detail** to **rate2detail rewrite**.
6. refresh the demo page and now the the detail request fails. **(rewrite not work)**

Below are the rules:

**detail-rewrite**
````
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: detail-rewrite
spec:
  ## Used by services inside the Kubernetes cluster
  destination:
    name: details
  match:
    request:
      headers:
        uri:
          prefix: /v1/details
  rewrite:
    uri: /details
````

**rate2detail**
````
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: rate2detail
spec:
  ## Used by services inside the Kubernetes cluster
  destination:
    name: ratings
  redirect:
    authority: details:9080
````

**rate2detail rewrite**
````
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: rate2detail
spec:
  ## Used by services inside the Kubernetes cluster
  destination:
    name: ratings
  rewrite:
    authority: details:9080
````

**Comment by GregHanson** [comment]
@aimuke can you try your `rate2detail rewrite` rule without the port in the rewrite?

```
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: rate2detail
spec:
  ## Used by services inside the Kubernetes cluster
  destination:
    name: ratings
  rewrite:
    authority: details
```

**Comment by aimuke** [comment]
Thx, @GregHanson 

I tried to update rate2detail rule without port, but this didnot work.  It still returns:

>  Sorry, product details are currently unavailable for this book.http://details/v1/details/0[]

**Comment by aimuke** [comment]
@GregHanson , I tried to change rate2detail  redirect to detail without port. By this way,  the request fails too.

````
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: rate2detail
spec:
  ## Used by services inside the Kubernetes cluster
  destination:
    name: ratings
  redirect:
    authority: details
````

**Comment by aimuke** [comment]
This issue is solved.
https://groups.google.com/forum/#!topic/istio-users/4hAjdIOFIQA

The reason is that a rewrite doesn't change the destination of a request, it only updates the header value in the request. So this place I should use route to change the destination, like below:

````
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: rate2detail
spec:
  
# send traffic who's destination is "ratings" to the destination "details"
  destination:
    name: ratings
  route:
  - destination:
      name: details
````
