### ISSUE TITLE
Wasmplugin does not support network filters

### ISSUE THREAD

**Issue by hanxiaop** [istio/istio#43229]
### Bug Description

When applied network WASM plugin with the WasmPlugin resource, for example:
```yaml
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: network
spec:
  imagePullPolicy: Always
  pluginName: network_plugin
  url: oci://xxxxxx 
```
The plugin is actually not attached, and will cause panic and cause the request to fail.

### Version

```prose
main branch
```
