### ISSUE TITLE
Istio Mirroring on more than one subset 

### ISSUE THREAD

**Issue by sqsous** [istio/istio#43228]
### Bug Description

Istio mirroring works fine, when only defining one subset 

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: web-mirror-vs
spec:
  hosts:
    - web-service.default.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: "/index.html"
    route:
    - destination:
        host: web-service.default.svc.cluster.local
  - match:
    - uri:
        prefix: /index2.html
    route:
    - destination:
        host: web-service.default.svc.cluster.local
        subset: v1
      weight: 100
    mirror:
      host: web-service.default.svc.cluster.local
      subset: v2
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: web-destinationrule
spec:
  host: web-service.default.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  - name: v3
    labels:
      version: v3
```

but it will not with second or third subset, the things I tried:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: web-mirror-vs
spec:
  hosts:
    - web-service.default.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: "/index.html"
    route:
    - destination:
        host: web-service.default.svc.cluster.local
  - match:
    - uri:
        prefix: /index2.html
    route:
    - destination:
        host: web-service.default.svc.cluster.local
        subset: v1
      weight: 100
    mirror:
      host: web-service.default.svc.cluster.local
      subset: v2
    mirror:
      host: web-service.default.svc.cluster.local
      subset: v3
```
I tried to add multiple labels in destination rule 
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: web-destinationrule
spec:
  host: web-service.default.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
      versions: v3
```
and just using one subset also didn't work 

### Version

```prose
eks_cluster_version = "1.22"
Istio = version: 1.14.4
```
