### ISSUE TITLE
ambient: consider allowing hostname `:authority` header

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#43241]
Currently we only allow IP. We _may_ want to also allow hostnames.

Note this will add complexity to the system, we need to measure the cost vs reward before committing.

**Comment by Hronom** [comment]
Hello, I'm setting this:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: argocd
  namespace: argocd
spec:
  selector:
    istio: ingressgateway-internal
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: gw-cert
      hosts:
        - "staging-argocd.internal.bla.com"

```
but seems like gateway fails to process request when host header actually goes in `:authority`:
```
2023-02-17T00:12:12.009357Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:972	[C19265][S10669755378619845445] request headers complete (end_stream=true):
':authority', 'staging-argocd.internal.bla.com'
':path', '/'
':method', 'GET'
'x-forwarded-for', '11.111.11.111'
'x-forwarded-proto', 'https'
'x-forwarded-port', '443'
'x-amzn-trace-id', 'Root=1-63eec65c-2ba6b49865b7c6b53ac9fbca'
'user-agent', 'curl/7.81.0'
'accept', '*/*'
```
