### ISSUE TITLE
ambient: Waypoint does not support passhthrough (orig_dst) upstreams

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#43242]
Currently if you define

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: passthrough
  annotations:
    test-suite: automtls-passthrough
spec:
  host: "*"
  trafficPolicy:
    loadBalancer:
      simple: PASSTHROUGH

```

We do not get expected behavior. I think envoy supports this, we just need control plane changes.

---

Note: this is copied from old repo, this may no longer be true but the test covering it is currently skipped.
