### ISSUE TITLE
It's not possible to disable tracing for istio-proxy

### ISSUE THREAD

**Issue by andreyreshetnikov-zh** [istio/istio#43253]
### Bug Description

I found several existing issues:
https://github.com/istio/istio/issues/35935
https://github.com/istio/istio/issues/31658
https://github.com/istio/istio/issues/29898
https://github.com/istio/istio/issues/33968

However, none of the described methods helped to disable tracing, istio-proxy container starts with `tracing:\n  zipkin:\n    address: zipkin.istio-system:9411\n"` setting.

istio-proxy container log:
```
{"level":"info","time":"2023-02-09T19:03:05.292121Z","msg":"Effective config: binaryPath: /usr/local/bin/envoy\nconcurrency: 2\nconfigPath: ./etc/istio/proxy\ncontrolPlaneAuthPolicy: MUTUAL_TLS\ndiscoveryAddress: istiod.istio-system.svc:15012\ndrainDuration: 45s\nparentShutdownDuration: 60s\nproxyAdminPort: 15000\nserviceCluster: istio-proxy\nstatNameLength: 189\nstatusPort: 15020\nterminationDrainDuration: 5s\ntracing:\n  zipkin:\n    address: zipkin.istio-system:9411\n"}
```

istio-sidecar-injector configmap(proxy parameters):
```
apiVersion: v1
data:
  config: |-
        "proxy": {
          "autoInject": "enabled",
          "clusterDomain": "cluster.local",
          "componentLogLevel": "misc:error",
          "enableCoreDump": false,
          "excludeIPRanges": "",
          "excludeInboundPorts": "",
          "excludeOutboundPorts": "",
          "holdApplicationUntilProxyStarts": true,
          "image": "proxyv2",
          "includeIPRanges": "*",
          "includeInboundPorts": "*",
          "includeOutboundPorts": "",
          "logLevel": "warning",
          "privileged": false,
          "readinessFailureThreshold": 30,
          "readinessInitialDelaySeconds": 1,
          "readinessPeriodSeconds": 2,
          "resources": {
            "limits": {
              "cpu": "2000m",
              "memory": "2048Mi"
            },
            "requests": {
              "cpu": "500m",
              "memory": "512Mi"
            }
          },
          "statusPort": 15020,
          "tracer": "none"
        },
        "tag": "1.15.3",
        "tracer": {
          "datadog": {
            "address": "$(HOST_IP):8126"
          },
          "lightstep": {
            "accessToken": "",
            "address": ""
          },
          "stackdriver": {
            "debug": false,
            "maxNumberOfAnnotations": 200,
            "maxNumberOfAttributes": 200,
            "maxNumberOfMessageEvents": 200
          },
          "zipkin": {
            "address": ""
          }
        },
        "useMCP": false
      },
      "revision": "",
    }
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: istio-istiod
    meta.helm.sh/release-namespace: istio-system
  labels:
    app.kubernetes.io/managed-by: Helm
    operator.istio.io/component: Pilot
    release: istio-istiod
  name: istio-sidecar-injector
```

istio configmap:
```
apiVersion: v1
data:
  mesh: |-
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      tracing: {}
    enablePrometheusMerge: true
    rootNamespace: null
    trustDomain: cluster.local
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: istio-istiod
    meta.helm.sh/release-namespace: istio-system
  labels:
    app.kubernetes.io/managed-by: Helm
    operator.istio.io/component: Pilot
    release: istio-istiod
  name: istio
```

values.yaml:
```
global:
  tracer: {}
  proxy:
    tracer: none
```
I also tried:
```
global:
  tracer: {}
  proxy:
    tracer: none

meshConfig:
  enableTracing: false
  defaultConfig:
    tracing: {}
```

The problem is that requests to the zipkin.istio-system domain create a huge load on coredns. How can we disable tracing or what workaround is possible?

### Version

```prose
istio helm chart: 1.15.3
istio-proxy: istio/proxyv2:1.15.3
istiod: istio/pilot:1.15.3
eks: 1.22
```

**Comment by andreyreshetnikov-zh** [comment]
Hello @howardjohn, as I understand it, you have the greatest expertise in this matter. I would be very grateful if you have the opportunity to take a look at this situation

**Comment by rlex** [comment]
I would also like to add that it's impossible to configure tracing in proxy in general, or so it seems.

proxy: block misses tracing: block. Here is my values:

```
      - global:
          proxy:
            enableTracing: true
            tracer: "zipkin"
          tracer:
            zipkin:
              address: ${HOST_IP}:9411
```

It seems like global.tracer settings is only applied to pilot (i can see proper values on start of pilot)

But proxy still reports default config: 

```
2023-02-09T12:57:59.651182Z	info	Effective config: binaryPath: /usr/local/bin/envoy
concurrency: 2
configPath: ./etc/istio/proxy
controlPlaneAuthPolicy: MUTUAL_TLS
discoveryAddress: istiod.istio-system.svc:15012
drainDuration: 45s
parentShutdownDuration: 60s
proxyAdminPort: 15000
serviceCluster: istio-proxy
statNameLength: 189
statusPort: 15020
terminationDrainDuration: 5s
tracing:
  zipkin:
    address: zipkin.istio-system:9411
```

My wild guess is that it should either inherit global.tracer config for proxy, or have separate tracer in global.proxy (unless proxies should pull that data from pilot)

Additionally, istio pilot misses HOST_IP env variable, so setting ${HOST_IP} in pilot's config will not work (proxy have that env variable)
