### ISSUE TITLE
ISTIO TELEMETRY - Create metric with dimensions

### ISSUE THREAD

**Issue by sergiosanche** [istio/istio#43308]
Hello,

I want to create a custom metric representing the rate limit per descriptor. It would be something like this:

# GAUGE
istio_irl_limit{}

istio_irl_limit{tenant="SRETENANT"} 20
istio_irl_limit{tenant="BBAND"} 10

What I want is to represent in Prometheus the configmap associated with the rate limit service:

```
apiVersion: v1
data:
  config.yaml: |
    domain: productpage-ratelimit
    descriptors:
      - key: TENANT
        value: "SRETENANT"
        rate_limit:
          unit: second
          requests_per_unit: 20
      - key: TENANT
        value: "BBAND"
        rate_limit:
          unit: second
          requests_per_unit: 10
kind: ConfigMap
metadata:
  name: ratelimit-config
  namespace: public-istio-ingress
```

How can I do this?

Regards.
