### ISSUE TITLE
istio operator stuck after adding new label

### ISSUE THREAD

**Issue by arnoldyahad** [istio/istio#43312]
### Bug Description

Hey folks,
when adding a new label to the istio operator it got stuck and caused our gateway pods to not work, this is the change i've made: 
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-ingress-gateway
  namespace: istio-system
spec:
  namespace: istio-system
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: false
    - name: test-lb
      enabled: true
      namespace: istio-ingress
      label:
        app: test-lb
        istio: test-lb
        co.elastic.logs/enabled: "true" # New label
        {{- end }}
```
this caused an error:
```
status:
  componentStatus:
    IngressGateways:
      error: >-
        failed to update resource with server-side apply for obj
        Deployment/istio-ingress/test-lb: Deployment.apps "test-lb" is invalid:
        spec.selector: Invalid value:
        v1.LabelSelector{MatchLabels:map[string]string{"app":"test-lb",
        "co.elastic.logs/enabled":"true", "istio":"test-lb",
        "type":"ingressgateway"},
        MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
      status: ERROR
  status: ERROR
```

and also when reading the logs of the operator it got stuck entierly on that error and doesnt print anymore messages:
```
2023-02-13T15:39:45.637227Z	info	installer	using server side apply to update obj: PodDisruptionBudget/istio-ingress/test-lb
2023-02-13T15:39:45.688361Z	info	installer	using server side apply to update obj: Service/istio-ingress/test-lb
- Processing resources for Ingress gateways.
✘ Ingress gateways encountered an error: failed to update resource with server-side apply for obj Deployment/istio-ingress/test-lb: Deployment.apps "test-lb" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"test-lb", "co.elastic.logs/enabled":"true", "istio":"test-lb", "type":"ingressgateway"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

new test-lb pods are not passing their readiness gate:
```
kubectl get pods -n istio-ingress -o wide
NAME                            READY   STATUS    RESTARTS   AGE     IP               NODE                             NOMINATED NODE   READINESS GATES
test-lb-59f9fb69b6-lqlgn        1/1     Running   0          22m     10.191.193.234   ip-10-191-207-7.ec2.internal     <none>           <none>
test-lb-59f9fb69b6-m8vqf        1/1     Running   0          22m     10.191.202.109   ip-10-191-197-112.ec2.internal   <none>           <none>
```

is this an intended behavior? because this means that if someone adds a label the istio-ingress pods will stop working.
is there any fix or other way to add labels to existing istio-ingress pods?

### Version

```prose
istioctl version --remote
client version: 1.15.0
control plane version: 1.16.1
data plane version: 1.16.1 (43 proxies), 1.13.5 (5 proxies)

kubectl version --short
Client Version: v1.22.15-eks-fb459a0
Server Version: v1.23.14-eks-ffeb93d
```
