### ISSUE TITLE
Use envoyfilter to create istio new metrics invalid

### ISSUE THREAD

**Issue by jokerYan-today** [istio/istio#43349]
I created an istio_test_requests metric with envoyfilter and set a dimension to count x-envoy-upstream-service-time data, but after I applied it to the workload, it didn't take effect. Does anyone know why? My configuration looks like this.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: fengyu-http-1-stats-filter
  namespace: default
spec:
  workloadSelector:
    labels:
      app: "fengyu-http-1"
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
      proxy:
        proxyVersion: ^1\.13.*
    patch:
      operation: INSERT_BEFORE
      value:
        name: istio.test.stats
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          value:
            config:
              configuration:
                '@type': type.googleapis.com/google.protobuf.StringValue
                value: |
                  {
                    "debug": "false",
                    "stat_prefix": "istio",
                    "definitions": [
                      {
                        "name": "test_requests",
                        "type": "COUNTER",
                        "value": "response.code"
                      }
                    ],
                    "metrics": [
                      {
                        "name": "test_requests",
                        "dimensions": {
                          "request_path": "request.path"
                        }
                      }
                    ]
                  }
              root_id: stats_inbound
              vm_config:
                code:
                  local:
                    inline_string: envoy.wasm.stats
                runtime: envoy.wasm.runtime.null
                vm_id: stats_inbound
```
deployment yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fengyu-http-1
  name: fengyu-http-1-34700012
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      service-id: cer4a037qe4s77387ksg
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.istio.io/merge-metrics: "false"
        sidecar.istio.io/extraStatTags: request_path
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/interceptionMode: TPROXY
        sidecar.istio.io/logLevel: info
        sidecar.istio.io/proxyCPU: 500m
        sidecar.istio.io/proxyCPULimit: 500m
        sidecar.istio.io/proxyMemory: 1024Mi
        sidecar.istio.io/proxyMemoryLimit: 1024Mi
        sidecar.istio.io/statsInclusionPrefixes: istio_test_requests
```
Requesting the service, I can get the following metrics
```
curl 10.105.68.49:15020/stats/prometheus | grep test_
# TYPE istio_test_requests counter
istio_test_requests{request_path="/"} 200
```
Modify the envoyfilter file with the value field changed to response.headers['x-envoy-upstream-service-time']
```
                value: |
                  {
                    "debug": "false",
                    "stat_prefix": "istio",
                    "definitions": [
                      {
                        "name": "test_requests",
                        "type": "COUNTER",
                        "value": "response.headers['x-envoy-upstream-service-time']"
                      }
                    ],
```
Requesting the service, I can get the following metrics, 
The correct value for metrics should be 10, but it shows 0.
```
 yufeng@P6LQGR4TX0  ~/code/yaml  curl -v 10.105.66.83
*   Trying 10.105.66.83:80...
* Connected to 10.105.66.83 (10.105.66.83) port 80 (#0)
> GET / HTTP/1.1
> Host: 10.105.66.83
> User-Agent: curl/7.85.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-type: text/plain; charset=utf-8
< date: Wed, 15 Feb 2023 03:22:31 GMT
< content-length: 15
< x-envoy-upstream-service-time: 10
< server: istio-envoy
< x-envoy-decorator-operation: svc-fengyu-http-1.aip-svc-nonlive-1.svc.cluster.local:80/*
<
* Connection #0 to host 10.105.66.83 left intact
Hello, Gin demo%
 yufeng@P6LQGR4TX0  ~/code/yaml  curl 10.105.66.83:15020/stats/prometheus | grep test_
# TYPE istio_test_requests counter
istio_test_requests{request_path="/"} 0
```

I want to create metrics for x-envoy-upstream-service-time data, what should I do?
