### ISSUE TITLE
Bug for istioctl installation when setting a boolean environment variable in meshConfig.defaultConfig.proxyMetadata

### ISSUE THREAD

**Issue by zhlsunshine** [istio/istio#43355]
### Bug Description

There is error output when setting a boolean environment variable in `meshConfig.defaultConfig.proxyMetadata` to install Istio, 
Installation:
```
$ istioctl install --set values.pilot.env.ISTIO_DUAL_STACK=true --set meshConfig.defaultConfig.proxyMetadata.ISTIO_AGENT_DUAL_STACK=true -y
```

Output:
```
Run the command with the --force flag if you want to ignore the validation error and proceed.
Error: generate config: failed to unmarshall mesh config: json: cannot unmarshal bool into Go value of type string
```

It's okay if the value is put into an istio installation yaml file

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
spec:
  profile: default
  meshConfig:
    defaultConfig:
      proxyMetadata:
        ISTIO_AGENT_DUAL_STACK: "true"
  values:
    pilot:
      env:
        ISTIO_DUAL_STACK: true
```

### Version

```prose
client version: 1.17-dev
```
