### ISSUE TITLE
Add ability to override sample decision in Telemetry resource

### ISSUE THREAD

**Issue by Stono** [istio/istio#43356]
**Describe the feature request**

As per the documentation at https://istio.io/latest/docs/reference/config/telemetry/#Tracing, it says (for `randomSamplePercentage`):

```
Controls the rate at which traffic will be selected for tracing if no prior sampling decision has been made. If a prior sampling decision has been made, that decision will be respected. However, if no sampling decision has been made (example: no x-b3-sampled tracing header was present in the requests), the traffic will be selected for telemetry generation at the percentage specified.
```

It'd be nice to be able to override this.  

For context; imagine you have a large microservice architecture.  You make a decision at the top of your request tree to sample the request, but for whatever reason there's a service in that tree you're not interested in recording spans for - you can't currently stop spans being recorded for it.

It would be nice to be able to add the `Telemetry` resource to the namespace of that service, and disable reporting from that point down.

**Describe alternatives you've considered**

I have tried using `HeaderOperations` to remove the `x-b3-sampled` header, but it had no effect, presumably due to where the filters apply.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by Stono** [comment]
Equally the inverse btw, a trace that wasn't sampled, but we might want to force all calls for a particular service to be recorded.

**Comment by zirain** [comment]
with Telemetry API you can change tracing setting for specifics workloads by [WorkloadSelector](https://istio.io/latest/docs/reference/config/type/workload-selector/#WorkloadSelector), is that works for you?

**Comment by Stono** [comment]
It doesn't work if a sample decision has already been made by an upstream service, eg `x-b3-sampled` is set.

**Comment by zirain** [comment]
> Service2 could have a telemetry selector which sets a rate of 0, but it won't matter, as the sample decision was already made in the upstream.

IIRC, you can disable tracing for `service2`?

**Comment by Stono** [comment]
No, you can't. And the docs say you can't too. 
Give it a go and see for yourself :)

**Comment by zirain** [comment]
can you try with following configuration:
```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  tracing:
    - providers:
        - name: "zipkin"
      randomSamplingPercentage: 100.00
---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: disable-details
  namespace: default
spec:
  selector:
    matchLabels:
      app: details
  tracing:
    - providers:
        - name: "zipkin"
      disableSpanReporting: true
```
