### ISSUE TITLE
DestinationRule's consecutiveGatewayErrors takes into account 500 errors

### ISSUE THREAD

**Issue by elavrom** [istio/istio#43357]
### Bug Description

The consecutiveGatewayErrors traffic policy behaves the same as consecutive5xxErrors since it takes into account the 500 status code.

Yaml to reproduce : 

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes  3;
    error_log  /var/log/nginx/error.log;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       80;
          server_name  _;
          location / {
              return 500;
          }
      }
    }
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx
          readOnly: true
          name: nginx-conf
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: default-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - nginx.exemple.com
      port:
        name: http
        number: 80
        protocol: HTTP2
      tls:
        httpsRedirect: false
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx
spec:
  gateways:
    - default-gateway
  hosts:
    - nginx.exemple.com
  http:
    - route:
        - destination:
            host: nginx.default.svc.cluster.local
            port:
              number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: nginx
spec:
  host: nginx.default.svc.cluster.local
  trafficPolicy:
    outlierDetection:
      consecutiveGatewayErrors: 3
      interval: 5m
      baseEjectionTime: 15m
```

### Version

```prose
$ istioctl version
client version: 1.16.0
control plane version: 1.15.0
data plane version: 1.14.4 (2 proxies), 1.15.0 (3 proxies)

$ kubectl version --short                                                                                                                                                                     
Client Version: v1.24.8
Server Version: v1.24.8
```
