### ISSUE TITLE
Add topologySpreadConstraints to values.yaml for Istiod Helm chart

### ISSUE THREAD

**Issue by youwalther65** [istio/istio#43360]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
In order to deploy multiple replicas of Istiod in different cloud availability zones (AZ) usage of topologySpreadConstraints is the best option. Currently there is no such option in istiod Helm chart
Having an istiod in every AZ and using a service annotation of
`service.kubernetes.io/topology-aware-hints: auto`
one can reduce the cross-AZ traffic by making use of K8s Topology Aware Hints .
So Envoy sidecar configuration is most probably loaded from local istiod.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[x ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[x ] Multi Cluster
[x] Virtual Machine
[x ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
You can do this and arbitrary other things you need with https://istio.io/latest/docs/setup/additional-setup/customize-installation-helm/. Also `.Values.pilot.serviceAnnotations`. We will not add a dedicated field for this. Thanks!

**Comment by youwalther65** [comment]
@howardjohn  Thank you for the fast response. This was useful! I use Fluxv2 and was able to utilize HelmeRelase postRenderes approach for that. As a reference for other folks see here:
```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  chart:
    spec:
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 5m0s
  releaseName: istiod
  targetNamespace: istio-system
  postRenderers:
    # Instruct helm-controller to use built-in "kustomize" post renderer.
    - kustomize:
        # Array of inline strategic merge patch definitions as YAML object.
        # Note, this is a YAML object and not a string, to avoid syntax
        # indention errors.
        patchesStrategicMerge:
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: istiod
              namespace: istio-system
            spec:
              template:
                spec:
                  topologySpreadConstraints:
                  - maxSkew: 1
                    topologyKey: topology.kubernetes.io/zone
                    whenUnsatisfiable: ScheduleAnyway
                    labelSelector:
                      matchLabels:
                        app: istiod
          - kind: Service
            apiVersion: v1
            metadata:
              annotations:
                service.kubernetes.io/topology-aware-hints: auto
              name: istiod
              namespace: istio-system
  valuesFrom:
    - kind: ConfigMap
      name: istiod-values
  dependsOn:
    - name: istio-base
      namespace: istio-system
```
