### ISSUE TITLE
istioctl experimental describe does not display all weights for weighted routes

### ISSUE THREAD

**Issue by rsalmond** [istio/istio#43368]
### Bug Description

I created a virtualservice with multiple weighted routes and found that `istioctl x describe service ...` only prints out the weights for the first route.

foo.yaml

``` yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: prism
spec:
  hosts:
  - lab20.classroom.superorbital.io
  gateways:
  - prism-gateway
  http:
  - match:
    - uri:
        prefix: /red
    rewrite:
      uri: "/"
    route:
    - destination:
        host: red
      weight: 5
    - destination:
        host: red-v2
      weight: 5
    - destination:
        host: red-v1
      weight: 90
```

``` console
$ istioctl x describe svc red
Service: red
   Port: http 80/HTTP targets pod port 80


Exposed on Ingress Gateway http://34.168.223.18
VirtualService: prism
   Weight 5%
   /red*

$ istioctl x describe svc red-v1
Service: red-v1
   Port: http 80/HTTP targets pod port 80

$ istioctl x describe svc red-v2
Service: red-v2
   Port: http 80/HTTP targets pod port 80
```

Sanity check, the envoy config on my ingress gateway seems right, and manual testing seems to distribute the load correctly.

``` json
"virtual_hosts": [
              {
                "name": "lab20.classroom.superorbital.io:80",
                "domains": [
                  "lab20.classroom.superorbital.io"
                ],
                "routes": [
                  {
                    "match": {
                      "prefix": "/red",
                      "case_sensitive": true
                    },
                    "route": {
                      "weighted_clusters": {
                        "clusters": [
                          {
                            "name": "outbound|80||red.default.svc.cluster.local",
                            "weight": 5
                          },
                          {
                            "name": "outbound|80||red-v2.default.svc.cluster.local",
                            "weight": 5
                          },
                          {
                            "name": "outbound|80||red-v1.default.svc.cluster.local",
                            "weight": 90
                          }
                        ],
                        "total_weight": 100
                      },
```

### Version

```prose
istioctl version
client version: 1.17.0
control plane version: 1.17.0
data plane version: 1.17.0 (5 proxies)

kubectl version --short
Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.23.16-gke.200
```
