### ISSUE TITLE
Redirect on button click

### ISSUE THREAD

**Issue by Rez0k** [istio/istio#43367]
Hi,

I am trying to implement istio on an exist product.
In my product there is a button that when you click on it, it will redirect to an auth provider and then redirect back to the app if you have the proper permissions.

Everything is working great without istio but with istio, on the button click I am being redirected to auth provider page and then being redirected back to my app, but I can't get in.

I am not getting any errors, from the logs of the auth provider I am able to login from their side.

Probably envoy doesn't know how to handle with the response headers or the redirect, any ideas how to fix this issue?

If more data from my side is required please let me know.

**Comment by Rez0k** [comment]
More info after debugging:
istio is striping 
`set-cookie: sessionId=*******; Path=/; Expires=Thu, 16 Feb 2023 ...; HttpOnly; Secure`
from the response headers.
how can I prevent this?

**Comment by hanxiaop** [comment]
You may look at examples about ext authz at https://istio.io/latest/docs/tasks/security/authorization/authz-custom/, to send back the `set-cookie` header if the request is allowed/denied

**Comment by hanxiaop** [comment]
If your auth service is out of mesh, you should define a serviceentry

**Comment by Rez0k** [comment]
> If your auth service is out of mesh, you should define a serviceentry

```apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: microsoft-sso
spec:
  hosts:
  - <external-host-url>
    location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
  ```
  
  and then changed istio configmap to:
  ```
extensionProviders:
    - name: "custom-auth"
      envoyExtAuthzHttp:
        service: "<external-host-url"
        port: "443"
        includeRequestHeadersInCheck: ["authorization", "cookie", "set-cookie"] 
        headersToUpstreamOnAllow: ["authorization", "path", "x-auth-request-user", "x-auth-request-email", "x-auth-request-access-token", "set-cookie"]
        headersToDownstreamOnDeny: ["content-type", "set-cookie"]
```

and still it's not seems to work
