### ISSUE TITLE
TelemetryAPI: unexpected behavior of multi accesslogging filters

### ISSUE THREAD

**Issue by fatedier** [istio/istio#43371]
### Bug Description

Two cases:
1. Only set accessloging filter for workload mode `SERVER`.
2. Set different accessloging filters for `CLIENT` and `SERVER`.

Example, case 1: this filter takes effect for inbound but it will disable accessloging for outbound. 

```yaml
- match:
    mode: SERVER
  providers:
  - name: envoy
  disabled: false
  filter:
    expression: response.code >= 500
``` 

case 2:  both inbound and outbound listeners will apply the last filter `response.code >= 500`

```yaml
- match:
    mode: CLIENT
  providers:
  - name: envoy
  disabled: false
  filter:
    expression: response.code >= 400
- match:
    mode: SERVER
  providers:
  - name: envoy
  disabled: false
  filter:
    expression: response.code >= 500
```

### Version

```prose
1.17.0
```
