### ISSUE TITLE
Error: Internal:Proto constraint validation failed when applying envoyfilter

### ISSUE THREAD

**Issue by AlfredoFausto** [istio/istio#43383]
### Bug Description

I tried many version since 1.14.3 up to 1.16.2
When applying the following envoyfilter:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: custom-timeout
  namespace: bookinfo
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      context: ANY
      cluster:
        name: PassthroughCluster
    patch:
      operation: MERGE
      value:
        connect_timeout: 5s
```

Pilot returns the following messages:

```
2023-02-15T21:45:49.863854Z	warn	ads	ADS:CDS: ACK ERROR reviews-v3-75596dfd78-j5zg9.bookinfo-13 Internal:Proto constraint validation failed (ClusterValidationError.ConnectTimeout: value must be greater than 0s): name: "PassthroughCluster"
type: ORIGINAL_DST
connect_timeout {
  6: 6
}
circuit_breakers {
  thresholds {
    max_connections {
      value: 4294967295
    }
    max_pending_requests {
      value: 4294967295
    }
    max_requests {
      value: 4294967295
    }
    max_retries {
      value: 4294967295
    }
    track_remaining: true
  }
}
typed_extension_protocol_options {
  key: "envoy.extensions.upstreams.http.v3.HttpProtocolOptions"
  value {
    [type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions] {
      common_http_protocol_options {
        idle_timeout {
          seconds: 300
        }
      }
      use_downstream_protocol_config {
        http_protocol_options {
        }
        http2_protocol_options {
        }
      }
    }
  }
}
filters {
  name: "istio.metadata_exchange"
  typed_config {
    [type.googleapis.com/envoy.tcp.metadataexchange.config.MetadataExchange] {
      protocol: "istio-peer-exchange"
    }
  }
}
```

Sometimes, pods are unable to start due the same error because it didn't receive an update from CDS
Besides that, it seems that the filter is applied to all the cluster when I'm specifically select the PassthroughCluster

Attaching the istiod log and the ouput of istioctl pc clusters 

[istiod-logs.txt](https://github.com/istio/istio/files/10748173/istiod-logs.txt)
[clusters-reviews-v3.txt](https://github.com/istio/istio/files/10748178/clusters-reviews-v3.txt)

### Version

```prose
istioctl version
client version: 1.16.0
control plane version: 1.16.0
data plane version: 1.16.0 (8 proxies)

kubectl version
Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.22.17-gke.3100
```
