### ISSUE TITLE
TPR "IstioConfig" is not ready in Tectonic install

### ISSUE THREAD

**Issue by ingshtrom** [istio/istio#434]
This issue is exactly like #355, but I opted to create a new issue because I am using Tectonic and have different output from the commands that were needed to debug. I also didn't fully understand what was done to fix the issue.

I've installed a fresh k8s cluster with Tectonic on AWS. 

Kubernetes: v1.6
Istio: v0.1.6

I installed istio and addons via the following commands:
```
kubectl apply -f install/kubernetes/istio-rbac-beta.yaml
kubectl apply -f install/kubernetes/addons/prometheus.yaml
kubectl apply -f install/kubernetes/addons/grafana.yaml
kubectl apply -f install/kubernetes/addons/servicegraph.yaml
kubectl apply -f install/kubernetes/addons/zipkin.yaml

# I also installed the bookinfo sample
kubectl apply -f <(istioctl kube-inject -f samples/apps/bookinfo/bookinfo.yaml)
```

Here are my api-versions:
![image](https://user-images.githubusercontent.com/571756/27587836-ee3441c6-5b13-11e7-9c52-63b5b5bad54e.png)

> Can you please check if the rbac file you applied contains "istioconfigs.istio.io"?

I applied the beta file, and yes it has this string in it for the resources.

### Output of commands requested in #355 

**kubectl get clusterrole istio-manager -oyaml**
```
Error from server (NotFound): clusterroles.rbac.authorization.k8s.io "istio-manager" not found
```

**kubectl get rolebinding istio-ingress-admin-role-binding -oyaml**
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1beta1","kind":"RoleBinding","metadata":{"annotations":{},"name":"istio-ingress-admin-role-binding","namespace":"default"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"istio-pilot"},"subjects":[{"kind":"ServiceAccount","name":"istio-ingress-service-account"}]}
  creationTimestamp: 2017-06-27T12:26:53Z
  name: istio-ingress-admin-role-binding
  namespace: default
  resourceVersion: "205922"
  selfLink: /apis/rbac.authorization.k8s.io/v1beta1/namespaces/default/rolebindings/istio-ingress-admin-role-binding
  uid: e71b3545-5b33-11e7-9aa3-02158d3208e5
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-pilot
subjects:
- kind: ServiceAccount
  name: istio-ingress-service-account
```

**kubectl get clusterrolebinding istio-ingress-admin-role-binding -oyaml**
```
Error from server (NotFound): clusterrolebindings.rbac.authorization.k8s.io "istio-ingress-admin-role-binding" not found
```

Thank you for all of your work!

**Comment by ingshtrom** [comment]
Looks like my problem was actually that it was a namespace role binding, not a cluster role binding. After replicating the namespace role binding as a cluster role binding, I got errors that the resources didn't exist. I then restarted all `istio-ingress` pods so that they created the TPCs as expected.

I am having these same problems with the `istio-egress`, so I will need to do the same thing for that.

**Comment by ingshtrom** [comment]
I found that I had to modify `install/kubernetes/istio-rbac-beta.yaml` in order to get `istio-pilot`, `istio-ingress`, and `istio-egress` working properly. Here is the full file after modifications.
```
# Permissions and roles for istio
# To debug: start the cluster with -vmodule=rbac,3 to enable verbose logging on RBAC DENY
# Also helps to enable logging on apiserver 'wrap' to see the URLs.
# Each RBAC deny needs to be mapped into a rule for the role.
# If using minikube, start with '--extra-config=apiserver.Authorization.Mode=RBAC'
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: istio-pilot
rules:
- apiGroups: ["istio.io"]
  resources: ["istioconfigs", "istioconfigs.istio.io"]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["thirdpartyresources", "thirdpartyresources.extensions", "ingresses", "ingresses/status"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["configmaps", "endpoints", "pods", "services"]
  verbs: ["*"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: istio-ca
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "watch", "list"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["watch", "list"]
---
# Permissions for the sidecar proxy.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: istio-sidecar
rules:
- apiGroups: ["istio.io"]
  resources: ["istioconfigs"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["extensions"]
  resources: ["thirdpartyresources", "ingresses"]
  verbs: ["get", "watch", "list", "update"]
- apiGroups: [""]
  resources: ["configmaps", "pods", "endpoints", "services"]
  verbs: ["get", "watch", "list"]
---
# Grant permissions to the Pilot/discovery.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: istio-pilot-admin-role-binding
subjects:
- kind: ServiceAccount
  name: istio-pilot-service-account
roleRef:
  kind: ClusterRole
  name: istio-pilot
  apiGroup: rbac.authorization.k8s.io
---
# Grant permissions to the Pilot/discovery.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: istio-ca-role-binding
subjects:
- kind: ServiceAccount
  name: istio-ca-service-account
roleRef:
  kind: ClusterRole
  name: istio-ca
  apiGroup: rbac.authorization.k8s.io
---
# Grant permissions to the Ingress controller.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: istio-ingress-admin-role-binding
subjects:
- kind: ServiceAccount
  name: istio-ingress-service-account
roleRef:
  kind: ClusterRole
  name: istio-pilot
  apiGroup: rbac.authorization.k8s.io
---
# Grant permissions to the sidecar.
# TEMPORARY: the istioctl should generate a separate service account for the proxy, and permission
# granted only to that account !
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: istio-sidecar-role-binding
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: ClusterRole
  name: istio-sidecar
  apiGroup: rbac.authorization.k8s.io
---
# CUSTOM START
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: istio-egress-admin-role-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: istio-pilot
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: istio-ingress-admin-role-binding
subjects:
- kind: ServiceAccount
  name: istio-ingress-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: istio-pilot
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: istio-pilot-admin-role-binding
subjects:
- kind: ServiceAccount
  name: istio-pilot-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: istio-pilot
  apiGroup: rbac.authorization.k8s.io
```

Notice that I added everything after `# STARTING CUSTOM` and I also changed the `istio-pilot` ClusterRole to include `ingresses/status` for `extensions` api types.
