### ISSUE TITLE
Istio service entry causing http: server gave HTTP response to HTTPS client

### ISSUE THREAD

**Issue by psandhu79** [istio/istio#43415]
### Bug Description

I have implemented the following on my kube cluster

https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/

i have all http traffic redirected to my egress gateway everything works fine.

However i have one service which needs to make a api call on https to a host which is defined as a service entry, the service entry is needed because its needs for other  service to making http calls through the egress gateway

using the example on the web

apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cnn
spec:
  hosts:
  - edition.cnn.com
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS

the service that needs to call http://edition.cnn.com is sent to my egressgateway and fowarded on as https request.

The service that makes a call to https://edition.cnn.com directly fails with  server gave HTTP response to HTTPS client

If i remove the entry the service that makes the http call starts failing but the service which makes the https call works.

i have even tried to add workload selector to the service entry to the egress gateway that ended with neither working.

I tried to remove the http declaration but still no success

### Version

```prose
client version: 1.9.1
control plane version: 1.16.1
data plane version: 1.16.1 (197 proxies)

Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.24.8-gke.2000
```

**Comment by dddddai** [comment]
I suspect it's because of double encryption
Could you try adding
```yaml
workloadSelector:
  matchLabels:
    app: istio-egressgateway
``` 
in the `originate-tls-for-edition-cnn-com` DR?

**Comment by GregHanson** [comment]
What is the use case for the HTTPS client?  The HTTP client wants calls sent through egress gateway - but does the HTTPS client want calls also going through egress gateway?  You will probably have to modify the VirutalService for the `mesh` gateway to define how you want the HTTPS traffic handled by the client's sidecar.  It currently only defines traffic HTTP traffic capture for the edition host:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-cnn-through-egress-gateway
spec:
  hosts:
  - edition.cnn.com
  gateways:
  - istio-egressgateway
  - mesh
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: cnn
        port:
          number: 80
      weight: 100
  - match:
    - gateways:
      - istio-egressgateway
      port: 80
    route:
    - destination:
        host: edition.cnn.com
        port:
          number: 443
      weight: 100
```
And if you do want to send HTTPS traffic for edition, you will also need to modify the Gateway resource since it is expecting only ISTIO_MUTUAL on its inbound port
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 80
      name: https-port-for-tls-origination
      protocol: HTTPS
    hosts:
    - edition.cnn.com
    tls:
      mode: ISTIO_MUTUAL
```
You can also check the access logs on the client sidecar to see who and where it is sending the HTTPS traffic

**Comment by psandhu79** [comment]
> > The service that makes a call to https://edition.cnn.com/ directly fails with server gave HTTP response to HTTPS client
> 
> Are you sure the client gets HTTP?
> 
> In my env I think it's because of double encryption Could you try adding
> 
> ```yaml
> workloadSelector:
>   matchLabels:
>     app: istio-egressgateway
> ```
> 
> in the `originate-tls-for-edition-cnn-com` DR?

This worked thank you, is this because i had mtls turned on within my mesh ?

**Comment by GregHanson** [comment]
The DestinationRule was telling all traffic to edition.cnn.com on port 443 to wrap all traffic in a new TLS session:
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-tls-for-edition-cnn-com
spec:
  host: edition.cnn.com
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE # initiates HTTPS for connections to edition.cnn.com
```
DestinationRule's apply to client envoy proxies, so by adding the `workloadSelector`, it ensures only the egress gateway configures traffic with TLS context, and that the client sidecar will not perform any additional TLS operations
