### ISSUE TITLE
EnvoyFilter: patch of `Cluster.ConnectTime` gets applied to arbitrary `Clusters` rather then `Cluster` specified by the `match`

### ISSUE THREAD

**Issue by yskopets** [istio/istio#43435]
### Bug Description

Create `EnvoyFilter` to patch `ConnectTime` of the `PassthroughCluster`:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: custom-timeout
  namespace: bookinfo
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      context: SIDECAR_OUTBOUND
      cluster:
        name: PassthroughCluster
    patch:
      operation: MERGE
      value:
        connect_timeout: 123s
```

Once this `EnvoyFilter` is applied, `connect_timeout: 123s` will appear in the configuration of arbitrary `Clusters`, rather than just `PassthroughCluster`, e.g. in
* `BlackHoleCluster`
* `outbound|15012||istiod.istio-system.svc.cluster.local`
* `outbound|443||bookinfo-ingressgateway.bookinfo.svc.cluster.local`
* `outbound|443||istiod.istio-system.svc.cluster.local`
* `outbound|80||bookinfo-ingressgateway.bookinfo.svc.cluster.local`
* `outbound|9080||details.bookinfo.svc.cluster.local`

Even if `EnvoyFilter` is removed later on, `Clusters` preserve `connect_timeout: 123s` value.

### Version

* `master`
* `1.17.x`
* `1.16.x`
* `1.15.x`
* `1.14.x`
* (not tested on earlier versions)

### Additional Information

It looks like the issue is caused by `copy-by-pointer` semantics when creating a `Cluster` object:

* https://github.com/istio/istio/blob/cff05d9ed3d3778e7c5e2452cb1c588804ad5185/pilot/pkg/networking/core/v1alpha3/cluster_builder.go#L667
* https://github.com/istio/istio/blob/cff05d9ed3d3778e7c5e2452cb1c588804ad5185/pilot/pkg/networking/core/v1alpha3/cluster_builder.go#L679
* https://github.com/istio/istio/blob/cff05d9ed3d3778e7c5e2452cb1c588804ad5185/pilot/pkg/networking/core/v1alpha3/cluster_builder.go#L1389
* https://github.com/istio/istio/blob/cff05d9ed3d3778e7c5e2452cb1c588804ad5185/pilot/pkg/networking/core/v1alpha3/cluster.go#L1064

When `EnvoyFilter` is applied, it mutates global `Push.Mesh.ConnectTimeout` value rather than `ConnectTimeout` value of a single `Cluster`.
