### ISSUE TITLE
Istio 1.17.0 regression with Knative DomainMappings

### ISSUE THREAD

**Issue by dprotaso** [istio/istio#43440]
### Bug Description

Downstream issue: https://github.com/knative/serving/issues/13712

Upgrading to Istio v1.17.0 has caused our DomainMapping feature to break - Istio now returns 503 `no health upstream`

The diff in our deployment is here - https://github.com/knative-sandbox/net-istio/pull/1061/files#diff-d30c8c1936a00c0ef1c073c949441ea6cec0aa9d66d9a6da585ed998f642056b

Virtual Services and K8s Services are in this gist - https://gist.github.com/dprotaso/64c53787a85b7e7cd1ec9f2b0c427bbe

I think the notable thing is one of our services uses `ExternalName`

### Version

```prose
$ istioctl version
client version: 1.17.0
control plane version: 1.17.0
data plane version: 1.17.0 (3 proxies)
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by dprotaso** [comment]
It's possible to reproduce this in [kind+metallb](https://kind.sigs.k8s.io/docs/user/loadbalancer/)

### Setup

```bash
$ kind create cluster
$ kubectl apply -f https://github.com/knative/serving/releases/download/knative-v1.9.0/serving-core.yaml
$ kubectl apply -f https://raw.githubusercontent.com/knative-sandbox/net-istio/ef720f6/third_party/istio-latest/istio-ci-no-mesh/istio.yaml
$ kubectl apply -f https://github.com/knative-sandbox/net-istio/releases/download/knative-v1.9.0/net-istio.yaml

$ kubectl patch configmap/config-domain --namespace knative-serving --type merge --patch '{"data":{"example.com":""}}'
$ kubectl patch configmap/config-network --namespace knative-serving --type merge --patch '{"data":{"autocreate-cluster-domain-claims":"true"}}'
```

### Fixtures

```bash
$ kubectl apply -f - <<EOF
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-samples/helloworld-go
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "World"
EOF
$ kubectl apply -f - <<EOF
apiVersion: serving.knative.dev/v1alpha1
kind: DomainMapping
metadata:
  name: blah.com
  namespace: default
spec:
  ref:
    name: hello
    kind: Service
    apiVersion: serving.knative.dev/v1
EOF
```
### Run the Test

First one succeeds - second one fails

```sh
$ docker run --network kind -it --rm cgr.dev/chainguard/curl -v -H 'Host: hello.default.example.com' 172.18.255.20 # Istio Ingress LB
$ docker run --network kind -it --rm cgr.dev/chainguard/curl -v -H 'Host: blah.com' 172.18.255.20 # Istio Ingress LB
```

**Comment by dprotaso** [comment]
Here's another bug where it returns 404. This setup is simpler as it doesn't require Knative

### Setup

Setup Kind with MetalLB and install istio with `istioctl install`

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving  
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: knative-ingress-gateway
  namespace: knative-serving
  labels:
    app.kubernetes.io/component: net-istio
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: devel
    networking.knative.dev/ingress-provider: istio
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: knative-local-gateway
  namespace: knative-serving
  labels:
    app.kubernetes.io/component: net-istio
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: devel
    networking.knative.dev/ingress-provider: istio
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 8081
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: v1
kind: Service
metadata:
  name: knative-local-gateway
  namespace: istio-system
  labels:
    app.kubernetes.io/component: net-istio
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: devel
    networking.knative.dev/ingress-provider: istio
    experimental.istio.io/disable-gateway-port-translation: "true"
spec:
  type: ClusterIP
  selector:
    istio: ingressgateway
  ports:
    - name: http2
      port: 80
      targetPort: 8081
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
      - containerPort: 80
        name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http-web-svc
---
apiVersion: v1
kind: Service
metadata:  
  name: nginx-internal
  namespace: default  
spec:
  externalName: knative-local-gateway.istio-system.svc.cluster.local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: ExternalName
status:
  loadBalancer: {}    
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nginx-ingress
  namespace: default  
spec:
  gateways:
  - knative-serving/knative-ingress-gateway
  - knative-serving/knative-local-gateway
  hosts:
  - nginx.default.example.com  
  http:
  - headers:
      request:
        set:
          K-Network-Hash: 0878975ddb3e11427b140f810d15eb3cc2993d744e2f689514280dd8e43b24c5
    match:
    - authority:
        prefix: nginx.default
      gateways:
      - knative-serving/knative-local-gateway
      headers:
        K-Network-Hash:
          exact: override
    retries: {}
    route:
    - destination:
        host: nginx.default.svc.cluster.local
        port:
          number: 80
      headers:
        request:
          set:
            Knative-Serving-Namespace: default
            Knative-Serving-Revision: hello-00001
      weight: 100
  - match:
    - authority:
        prefix: nginx.default
      gateways:
      - knative-serving/knative-local-gateway
    retries: {}
    route:
    - destination:
        host: nginx.default.svc.cluster.local
        port:
          number: 80
      weight: 100
  - headers:
      request:
        set:
          K-Network-Hash: 0878975ddb3e11427b140f810d15eb3cc2993d744e2f689514280dd8e43b24c5
    match:
    - authority:
        prefix: nginx.default.example.com
      gateways:
      - knative-serving/knative-ingress-gateway
      headers:
        K-Network-Hash:
          exact: override
    retries: {}
    route:
    - destination:
        host: nginx.default.svc.cluster.local
        port:
          number: 80
      headers:
        request:
          set:
            Knative-Serving-Namespace: default
            Knative-Serving-Revision: hello-00001
      weight: 100
  - match:
    - authority:
        prefix: nginx.default.example.com
      gateways:
      - knative-serving/knative-ingress-gateway
    retries: {}
    route:
    - destination:
        host: nginx.default.svc.cluster.local
        port:
          number: 80
      headers:
        request:
          set:
            Knative-Serving-Namespace: default
            Knative-Serving-Revision: hello-00001
      weight: 100
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:  
  name: foo.com-ingress
  namespace: default  
spec:
  gateways:
  - knative-serving/knative-ingress-gateway
  hosts:
  - foo.com
  http:
  - match:
    - authority:
        prefix: foo.com
      gateways:
      - knative-serving/knative-ingress-gateway
    retries: {}
    rewrite:
      authority: nginx-internal.default.svc.cluster.local
    route:
    - destination:
        host: nginx-internal.default.svc.cluster.local
        port:
          number: 80
      headers:
        request:
          set:
            K-Original-Host: foo.com
      weight: 100
```


### Run the test
Fix one succeeds - second one does not
```sh
$ docker run --network kind -it --rm cgr.dev/chainguard/curl -v -H 'Host: nginx.default.example.com' 172.18.255.200
$ docker run --network kind -it --rm cgr.dev/chainguard/curl -v -H 'Host: foo.com' 172.18.255.200
```
