### ISSUE TITLE
requestAuthentication doesn't return 401 even if token is invalid

### ISSUE THREAD

**Issue by Mathis-Deconchat** [istio/istio#43466]
### Bug Description

Hi everyone, thanks for the good work with istio !
I have an issue with the authN/authZ flow and I don't find the appropriate documentation about it.
I don't know if it's really an issue or if the documentation is unclear about this.

### Expected behavior : 

RequestAuthentication : 
```yaml 
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: ingressgateway-back-front
  namespace: default
spec:
  selector: 
    matchLabels:
      auth: "true"
  jwtRules:  
  - issuer: "https://example/realms/realm-example"
    jwksUri: "https:/example/realms/realm-example/protocol/openid-connect/certs"
    forwardOriginalToken: true
    outputPayloadToHeader: x-id-token
    fromHeaders:
    - name: authorization
      prefix: "Bearer "
``` 
AuhtorizationPolicy : 
```yaml 
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: auth-policy-front
  namespace: default
spec:
  selector:
    matchLabels:
      auth "true"
  action: CUSTOM
  provider:
    name: oauth2-proxy
  rules:
    - {}
```
(The authorizationPolicy used a custom Provider referencing to oauth2-proxy and using Keycloak as an IAM)

From what I understand from the documentation, this is what should happen with the requestAuthentication : 
```mermaid 
graph TD
B[Client]-- Acces protected service by requestAuth --> C{requestAuthentication}
C -.->|Request without token| D[return True but without any authentication headers]
C -.->|Request with invalid token| E[Return False and http 401]
C -.->|Requête with valid token| F[Return true and add authz token]
``` 

So what I was expecting was : 
If the request doesn't have any authorization headers, the request goes by the authPolicy without any authentication Headers, and the custom authPolicy could return the login page to the user.

If the request had an invalid authorization header, the requestAuthentication should return an 401 error and not go through the authorizationPolicy

### Actual behavior : 
If I make a request to the service protected with the requestAuth and auhtPol, event if my token is invalid (random strings, expired etc...) I still get redirected to the login page, so it is still going through the authorizationPolicy.

It's not a problem about the name of the header, if the token is valid we do get an x-id-token as specified in the requestAuthentication

 

### Version

```prose
$ istioctl version
1.14.1 

$ kubectl version --short
Client Version: v1.22.12

Not using Helm
```
