### ISSUE TITLE
K8s service, virtual-service and gateway are set-up, but unable to configure istio ingress.

### ISSUE THREAD

**Issue by geolney** [istio/istio#43473]
### Bug Description

When pointing the virtualService and gateway to the service correctly (as have successfully done in multiple other apps) I am getting errors when accessing the URL: `upstream connect error or disconnect/reset before headers. reset reason: connection termination`.

VirtualService, Gateway, Service manifests:
```
kubectl get vs -n threatmapper -oyaml
apiVersion: v1
items:
- apiVersion: networking.istio.io/v1beta1
  kind: VirtualService
  metadata:
...
  spec:
    gateways:
    - deepfence-router
    hosts:
    - threatmapper-console.<our domain>.com
    http:
    - match:
      - uri:
          prefix: /
      route:
      - destination:
          host: deepfence-router.threatmapper.svc.cluster.local
          port:
            number: 443
        weight: 100
kind: List


kubectl get gateway -n threatmapper -oyaml
apiVersion: v1
items:
- apiVersion: networking.istio.io/v1beta1
  kind: Gateway
  metadata:
...
  spec:
    selector:
      gateway: external
    servers:
    - hosts:
      - threatmapper-console.<our domain>.com
      port:
        name: http-port
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
      - threatmapper-console.<our domain>.com
      port:
        name: https-port
        number: 443
        protocol: HTTP
kind: List


kubectl get svc deepfence-router -n threatmapper -oyaml
apiVersion: v1
kind: Service
metadata:
...
spec:
  clusterIP: 172.20.118.167
  clusterIPs:
  - 172.20.118.167
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    name: deepfence-router
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

When looking at `istioctl proxy-config listeners deepfence-router-766bf467c5-gslxk -n threatmapper`, I am expecting to see a `Route: deepfence-router.threatmapper.svc.cluster.local:443` however this is not the case. Is this the reason for the lack of connection? 

NOTE: out of all services outputted in the bug-report below, all of them are able to be configured successfully through VS/gateway apart from `deepfence-router` and `deepfence-internal-router`, either of which are the service that I actually want to serve. 

TO REPRODUCE:
I have installed the helm-charts with my own values from this link - https://github.com/deepfence/ThreatMapper/tree/master/deployment-scripts/helm-charts 
deployed `deepfence-console` and `deepfence-router`.

### Version

```prose
istioctl version
client version: 1.17.0
control plane version: 1.15-alpha.9cb7b428fe38654f3e0d462720f4f19347cbe728
data plane version: 1.15-alpha.9cb7b428fe38654f3e0d462720f4f19347cbe728 (10 proxies), 1.18-alpha.1258e3fdad4421078dbd0962c3df09b8e9bc752b (41 proxies), 1.18-alpha.ed3c31ba5be34a2ee9e137f30918c0a83a8c473b (21 proxies)

kubectl version --short
Client Version: v1.25.4
Server Version: v1.22.16-eks-ffeb93d
```

### Additional Information

```
istioctl bug-report

Target cluster context: sandbox

Running with the following config:

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2023-02-20 19:02:51.646686 +0000 UTC



Cluster endpoint: https://<url>.gr7.eu-west-2.eks.amazonaws.com
CLI version:
version.BuildInfo{Version:"1.17.0", GitRevision:"c8c901a56861021dc25412f2e557b72a235b554c-dirty", GolangVersion:"go1.19.6", BuildStatus:"Clean", GitTag:"1.17.0"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.15-alpha.9cb7b428fe38654f3e0d462720f4f19347cbe728", GitRevision:"9cb7b428fe38654f3e0d462720f4f19347cbe728", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.15-alpha.9cb7b428fe38654f3e0d462720f4f19347cbe728"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.15-alpha.9cb7b428fe38654f3e0d462720f4f19347cbe728, 1.18-alpha.ed3c31ba5be34a2ee9e137f30918c0a83a8c473b, 1.18-alpha.1258e3fdad4421078dbd0962c3df09b8e9bc752b}


Fetching proxy logs for the following containers:

...
istio-system/dsp-istio-ingressgateway-spare1/dsp-istio-ingressgateway-spare1-5bc8c4db44-9lzlv/istio-proxy
istio-system/dsp-istio-ingressgateway-spare2/dsp-istio-ingressgateway-spare2-8649d65f89-m6x48/istio-proxy
istio-system/dsp-istio-ingressgateway-whitelisted-spare1/dsp-istio-ingressgateway-whitelisted-spare1-649f7dddc9-xxbpd/istio-proxy
istio-system/dsp-istio-ingressgateway-whitelisted-spare2/dsp-istio-ingressgateway-whitelisted-spare2-5df9db87b9-9pvbm/istio-proxy
istio-system/dsp-istio-ingressgateway-whitelisted/dsp-istio-ingressgateway-whitelisted-5bb76d7cbf-msv6j/istio-proxy
istio-system/istio-ingressgateway/istio-ingressgateway-6567bc886f-mqh4w/istio-proxy
istio-system/istio-internal-ingressgateway/istio-internal-ingressgateway-c8f4c79b7-ptn96/istio-proxy
istio-system/istio-mtls-ingressgateway/istio-mtls-ingressgateway-f8f649474-xmjtx/istio-proxy
istio-system/istio-mtls-ingressgateway/istio-mtls-ingressgateway-f8f649474-z99gd/istio-proxy
istio-system/istio-operator/istio-operator-7468fdd974-6489p/istio-operator
istio-system/istio-operator/istio-operator-7468fdd974-6489p/istio-proxy
istio-system/istiod/istiod-74547f9f6b-4jt54/discovery
...
threatmapper-agent//deepfence-agent-4pw9t/deepfence-agent
threatmapper-agent//deepfence-agent-549dk/deepfence-agent
threatmapper-agent//deepfence-agent-5tfnp/deepfence-agent
threatmapper-agent//deepfence-agent-c7p6g/deepfence-agent
threatmapper-agent//deepfence-agent-h6p6c/deepfence-agent
threatmapper-agent//deepfence-agent-kmvgg/deepfence-agent
threatmapper-agent//deepfence-agent-qrq9q/deepfence-agent
threatmapper-agent//deepfence-agent-tcx8c/deepfence-agent
threatmapper-agent//deepfence-agent-x5jkk/deepfence-agent
threatmapper-agent/deepfence-cluster-agent/deepfence-cluster-agent-56cbb54955-hgkq7/deepfence-cluster-agent
threatmapper-agent/deepfence-cluster-agent/deepfence-cluster-agent-755df7bc8d-ctxx4/deepfence-cluster-agent
threatmapper//deepfence-discovery-2qjwc/deepfence-discovery
threatmapper//deepfence-discovery-5flk2/deepfence-discovery
threatmapper//deepfence-discovery-6bgsc/deepfence-discovery
threatmapper//deepfence-discovery-7rb6n/deepfence-discovery
threatmapper//deepfence-discovery-8xgwh/deepfence-discovery
threatmapper//deepfence-discovery-9kzrp/deepfence-discovery
threatmapper//deepfence-discovery-bwzcr/deepfence-discovery
threatmapper//deepfence-discovery-pzsp8/deepfence-discovery
threatmapper//deepfence-discovery-vnfjc/deepfence-discovery
threatmapper//deepfence-es-0/deepfence-es
threatmapper//deepfence-es-0/istio-proxy
threatmapper//deepfence-es-1/deepfence-es
threatmapper//deepfence-es-1/istio-proxy
threatmapper//deepfence-es-2/deepfence-es
threatmapper//deepfence-es-2/istio-proxy
threatmapper//deepfence-postgres-0/deepfence-postgresql
threatmapper//deepfence-postgres-0/istio-proxy
threatmapper/deepfence-api/deepfence-api-5df48f4f49-wrp7b/deepfence-api
threatmapper/deepfence-api/deepfence-api-5df48f4f49-wrp7b/istio-proxy
threatmapper/deepfence-backend/deepfence-backend-6ddfbc7757-wcflh/deepfence-backend
threatmapper/deepfence-backend/deepfence-backend-6ddfbc7757-wcflh/istio-proxy
threatmapper/deepfence-celery/deepfence-celery-68785b847-zkcn2/deepfence-celery
threatmapper/deepfence-celery/deepfence-celery-68785b847-zkcn2/istio-proxy
threatmapper/deepfence-diagnosis/deepfence-diagnosis-56f9f6b77f-qqvkr/deepfence-diagnosis
threatmapper/deepfence-diagnosis/deepfence-diagnosis-56f9f6b77f-qqvkr/istio-proxy
threatmapper/deepfence-fetcher/deepfence-fetcher-74d8c48c87-mlhkr/deepfence-fetcher
threatmapper/deepfence-fetcher/deepfence-fetcher-74d8c48c87-mlhkr/istio-proxy
threatmapper/deepfence-internal-router/deepfence-internal-router-b58c65c57-89wpw/deepfence-internal-router
threatmapper/deepfence-internal-router/deepfence-internal-router-b58c65c57-89wpw/istio-proxy
threatmapper/deepfence-package-scanner/deepfence-package-scanner-586b67678d-dhzt2/deepfence-package-scanner
threatmapper/deepfence-package-scanner/deepfence-package-scanner-586b67678d-dhzt2/istio-proxy
threatmapper/deepfence-redis/deepfence-redis-94546cfb4-fxpxv/deepfence-redis
threatmapper/deepfence-redis/deepfence-redis-94546cfb4-fxpxv/istio-proxy
threatmapper/deepfence-router/deepfence-router-766bf467c5-gslxk/deepfence-router
threatmapper/deepfence-router/deepfence-router-766bf467c5-gslxk/istio-proxy
threatmapper/deepfence-secret-scaner/deepfence-secret-scaner-bdfbf997b-kp5d6/deepfence-secret-scanner
threatmapper/deepfence-secret-scaner/deepfence-secret-scaner-bdfbf997b-kp5d6/istio-proxy
threatmapper/deepfence-topology/deepfence-topology-94b886c45-zrvvl/deepfence-topology
threatmapper/deepfence-topology/deepfence-topology-94b886c45-zrvvl/istio-proxy
threatmapper/deepfence-ui/deepfence-ui-db4df9678-q6mxl/deepfence-ui
threatmapper/deepfence-ui/deepfence-ui-db4df9678-q6mxl/istio-proxy
threatmapper/deepfence-vulnerability-mapper/deepfence-vulnerability-mapper-5f6777877b-8grgf/deepfence-vulnerability-mapper
threatmapper/deepfence-vulnerability-mapper/deepfence-vulnerability-mapper-5f6777877b-8grgf/istio-proxy
...

Fetching Istio control plane information from cluster.

The following fetches are still running:
  PodExec threatmapper/deepfence-ui-db4df9678-q6mxl/istio-proxy:netstat -natpw
  ProxyGet threatmapper/deepfence-topology-94b886c45-zrvvl:certs
  PodLogs threatmapper/deepfence-secret-scaner-bdfbf997b-kp5d6/istio-proxy


Running istio analyze on all namespaces and report as below:
Analysis Report:

Warning [IST0105] (Pod threatmapper/deepfence-api-5df48f4f49-wrp7b) The image of the Istio proxy running on the pod does not match the image defined in the injection configuration (pod image: gcr.io/istio-testing/proxyv2:1.18-alpha.1258e3fdad4421078dbd0962c3df09b8e9bc752b; injection configuration image: gcr.io/istio-testing/proxyv2:1.15-alpha.9cb7b428fe38654f3e0d462720f4f19347cbe728). This often happens after upgrading the Istio control-plane and can be fixed by redeploying the pod.
Warning [IST0105] (Pod threatmapper/deepfence-backend-6ddfbc7757-wcflh) The image of the Istio proxy running on the pod does not match the image defined in the injection configuration (pod image: gcr.io/istio-testing/proxyv2:1.18-alpha.1258e3fdad4421078dbd0962c3df09b8e9bc752b; injection configuration image: gcr.io/istio-testing/proxyv2:1.15-alpha.9cb7b428fe38654f3e0d462720f4f19347cbe728). This often happens after upgrading the Istio control-plane and can be fixed by redeploying the pod.
Warning [IST0105] (Pod threatmapper/deepfence-celery-68785b847-zkcn2) The image of the Istio proxy running on the pod does not match the image defined in the injection configuration (pod image: gcr.io/istio-testing/proxyv2:1.18-alpha.1258e3fdad4421078dbd0962c3df09b8e9bc752b; injection configuration image: gcr.io/istio-testing/proxyv2:1.15-alpha.9cb7b428fe38654f3e0d462720f4f19347cbe728). This often happens after upgrading the Istio control-plane and can be fixed by redeploying the pod.
Warning [IST0105] (Pod threatmapper/deepfence-diagnosis-56f9f6b77f-qqvkr) The image of the Istio proxy running on the pod does not match the image defined in the injection configuration (pod image: gcr.io/istio-testing/proxyv2:1.18-alpha.1258e3fdad4421078dbd0962c3df09b8e9bc752b; injection configuration image: gcr.io/istio-testing/proxyv2:1.15-alpha.9cb7b428fe38654f3e0d462720f4f19347cbe728). This often happens after upgrading the Istio control-plane and can be fixed by redeploying the pod.
Warning [IST0105] (Pod threatmapper/deepfence-es-0) The image of the Istio proxy running on the pod does not match the image defined in the injection configuration (pod image: gcr.io/istio-testing/proxyv2:1.18-alpha.1258e3fdad4421078dbd0962c3df09b8e9bc752b; injection configuration image: gcr.io/istio-testing/proxyv2:1.15-alpha.9cb7b428fe38654f3e0d462720f4f19347cbe728). This often happens after upgrading the Istio control-plane and can be fixed by redeploying the pod.
Warning [IST0105] (Pod threatmapper/deepfence-es-1) The image of the Istio proxy running on the pod does not match the image defined in the injection configuration (pod image: gcr.io/istio-testing/proxyv2:1.18-alpha.1258e3fdad4421078dbd0962c3df09b8e9bc752b; injection configuration image: gcr.io/istio-testing/proxyv2:1.15-alpha.9cb7b428fe38654f3e0d462720f4f19347cbe728). This often happens after upgrading the Istio control-plane and can be fixed by redeploying the pod.
Warning [IST0105] (Pod threatmapper/deepfence-es-2) The image of the Istio proxy running on the pod does not match the image defined in the injection configuration (pod image: gcr.io/istio-testing/proxyv2:1.18-alpha.1258e3fdad4421078dbd0962c3df09b8e9bc752b; injection configuration image: gcr.io/istio-testing/proxyv2:1.15-alpha.9cb7b428fe38654f3e0d462720f4f19347cbe728). This often happens after upgrading the Istio control-plane and can be fixed by redeploying the pod.
Warning [IST0105] (Pod threatmapper/deepfence-fetcher-74d8c48c87-mlhkr) The image of the Istio proxy running on the pod does not match the image defined in the injection configuration (pod image: gcr.io/istio-testing/proxyv2:1.18-alpha.1258e3fdad4421078dbd0962c3df09b8e9bc752b; injection configuration image: gcr.io/istio-testing/proxyv2:1.15-alpha.9cb7b428fe38654f3e0d462720f4f19347cbe728). This often happens after upgrading the Istio control-plane and can be fixed by redeploying the pod.
Warning [IST0105] (Pod threatmapper/deepfence-internal-router-b58c65c57-89wpw) The image of the Istio proxy running on the pod does not match the image defined in the injection configuration (pod image: gcr.io/istio-testing/proxyv2:1.18-alpha.1258e3fdad4421078dbd0962c3df09b8e9bc752b; injection configuration image: gcr.io/istio-testing/proxyv2:1.15-alpha.9cb7b428fe38654f3e0d462720f4f19347cbe728). This often happens after upgrading the Istio control-plane and can be fixed by redeploying the pod.
Warning [IST0105] (Pod threatmapper/deepfence-package-scanner-586b67678d-dhzt2) The image of the Istio proxy running on the pod does not match the image defined in the injection configuration (pod image: gcr.io/istio-testing/proxyv2:1.18-alpha.1258e3fdad4421078dbd0962c3df09b8e9bc752b; injection configuration image: gcr.io/istio-testing/proxyv2:1.15-alpha.9cb7b428fe38654f3e0d462720f4f19347cbe728). This often happens after upgrading the Istio control-plane and can be fixed by redeploying the pod.
Warning [IST0105] (Pod threatmapper/deepfence-postgres-0) The image of the Istio proxy running on the pod does not match the image defined in the injection configuration (pod image: gcr.io/istio-testing/proxyv2:1.18-alpha.1258e3fdad4421078dbd0962c3df09b8e9bc752b; injection configuration image: gcr.io/istio-testing/proxyv2:1.15-alpha.9cb7b428fe38654f3e0d462720f4f19347cbe728). This often happens after upgrading the Istio control-plane and can be fixed by redeploying the pod.
Warning [IST0105] (Pod threatmapper/deepfence-redis-94546cfb4-fxpxv) The image of the Istio proxy running on the pod does not match the image defined in the injection configuration (pod image: gcr.io/istio-testing/proxyv2:1.18-alpha.1258e3fdad4421078dbd0962c3df09b8e9bc752b; injection configuration image: gcr.io/istio-testing/proxyv2:1.15-alpha.9cb7b428fe38654f3e0d462720f4f19347cbe728). This often happens after upgrading the Istio control-plane and can be fixed by redeploying the pod.
Warning [IST0105] (Pod threatmapper/deepfence-router-766bf467c5-gslxk) The image of the Istio proxy running on the pod does not match the image defined in the injection configuration (pod image: gcr.io/istio-testing/proxyv2:1.18-alpha.1258e3fdad4421078dbd0962c3df09b8e9bc752b; injection configuration image: gcr.io/istio-testing/proxyv2:1.15-alpha.9cb7b428fe38654f3e0d462720f4f19347cbe728). This often happens after upgrading the Istio control-plane and can be fixed by redeploying the pod.
Warning [IST0105] (Pod threatmapper/deepfence-secret-scaner-bdfbf997b-kp5d6) The image of the Istio proxy running on the pod does not match the image defined in the injection configuration (pod image: gcr.io/istio-testing/proxyv2:1.18-alpha.1258e3fdad4421078dbd0962c3df09b8e9bc752b; injection configuration image: gcr.io/istio-testing/proxyv2:1.15-alpha.9cb7b428fe38654f3e0d462720f4f19347cbe728). This often happens after upgrading the Istio control-plane and can be fixed by redeploying the pod.
Warning [IST0105] (Pod threatmapper/deepfence-topology-94b886c45-zrvvl) The image of the Istio proxy running on the pod does not match the image defined in the injection configuration (pod image: gcr.io/istio-testing/proxyv2:1.18-alpha.1258e3fdad4421078dbd0962c3df09b8e9bc752b; injection configuration image: gcr.io/istio-testing/proxyv2:1.15-alpha.9cb7b428fe38654f3e0d462720f4f19347cbe728). This often happens after upgrading the Istio control-plane and can be fixed by redeploying the pod.
Warning [IST0105] (Pod threatmapper/deepfence-ui-db4df9678-q6mxl) The image of the Istio proxy running on the pod does not match the image defined in the injection configuration (pod image: gcr.io/istio-testing/proxyv2:1.18-alpha.1258e3fdad4421078dbd0962c3df09b8e9bc752b; injection configuration image: gcr.io/istio-testing/proxyv2:1.15-alpha.9cb7b428fe38654f3e0d462720f4f19347cbe728). This often happens after upgrading the Istio control-plane and can be fixed by redeploying the pod.
Warning [IST0105] (Pod threatmapper/deepfence-vulnerability-mapper-5f6777877b-8grgf) The image of the Istio proxy running on the pod does not match the image defined in the injection configuration (pod image: gcr.io/istio-testing/proxyv2:1.18-alpha.1258e3fdad4421078dbd0962c3df09b8e9bc752b; injection configuration image: gcr.io/istio-testing/proxyv2:1.15-alpha.9cb7b428fe38654f3e0d462720f4f19347cbe728). This often happens after upgrading the Istio control-plane and can be fixed by redeploying the pod.
...
...
Info [IST0118] (Service threatmapper/deepfence-api) Port name deepfence-api-port (port: 9998, targetPort: 9998) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service threatmapper/deepfence-api) Port name deepfence-internal-api-port (port: 9997, targetPort: 9997) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service threatmapper/deepfence-backend) Port name deepfence-backend-port (port: 4041, targetPort: 4041) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service threatmapper/deepfence-diagnosis) Port name deepfence-diagnosis-port (port: 8009, targetPort: 8009) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service threatmapper/deepfence-es) Port name deepfence-es-port-1 (port: 9200, targetPort: 9200) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service threatmapper/deepfence-es) Port name deepfence-es-port-2 (port: 9300, targetPort: 9300) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service threatmapper/deepfence-fetcher) Port name deepfence-fetcher-port-1 (port: 8001, targetPort: 8001) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service threatmapper/deepfence-fetcher) Port name deepfence-fetcher-port-2 (port: 8002, targetPort: 8002) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service threatmapper/deepfence-fetcher) Port name deepfence-fetcher-port-3 (port: 8006, targetPort: 8006) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service threatmapper/deepfence-package-scanner) Port name deepfence-package-scanner-port (port: 8005, targetPort: 8005) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service threatmapper/deepfence-postgres) Port name deepfence-postgres-port (port: 5432, targetPort: 5432) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service threatmapper/deepfence-redis) Port name deepfence-redis-port (port: 6379, targetPort: 6379) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service threatmapper/deepfence-secret-scanner) Port name deepfence-secret-scanner-port (port: 8011, targetPort: 8011) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service threatmapper/deepfence-topology) Port name deepfence-topology-port (port: 8004, targetPort: 8004) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service threatmapper/deepfence-ui) Port name deepfence-ui-port (port: 4042, targetPort: 4042) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service threatmapper/deepfence-vulnerability-mapper) Port name deepfence-vulnerability-mapper-port (port: 8001, targetPort: 8001) doesn't follow the naming convention of Istio port.
...
Creating an archive at /Users/georgeolney/bug-report.tar.gz.
Cleaning up temporary files in /var/folders/fp/nxtmm7fd5ldc3vd3qlskcm6w0000gq/T/bug-report.
Done.
```

**Comment by howardjohn** [comment]
Looks like you are sending to an https backend but send HTTP. Youll either want to use passthrough TLS or originate TLS with a SIMPLE mode destination TLS rule

**Comment by geolney** [comment]
Hello @howardjohn, thank you for your reply! I was away on leave shortly after posting this and have just been able to add the `tls.mode PASSTHROUGH` to the gateway. This hadn't worked previously and is still showing the error:

`upstream connect error or disconnect/reset before headers. reset reason: connection termination` when I try to access the URL. 

The same happens if I add SIMPLE to the gateway. 

example
```
    - port:
        number: 443
        name: https-port
        protocol: HTTP
      hosts:
        - "threatmapper-console.dsp-test.bt.com"
      tls:
        mode: SIMPLE    
```

**Comment by geolney** [comment]
Hello @howardjohn, thank you for your reply! I was away on leave shortly after posting this and have just been able to add the tls.mode PASSTHROUGH to the gateway. This hadn't worked previously and is still showing the error:

upstream connect error or disconnect/reset before headers. reset reason: connection termination when I try to access the URL.

The same happens if I add SIMPLE to the gateway.

example

    - port:
        number: 443
        name: https-port
        protocol: HTTP
      hosts:
        - "threatmapper-console.<my-domain>.com"
      tls:
        mode: SIMPLE

**Comment by lambohamp** [comment]
Hi. I am getting the same error (`upstream connect error or disconnect/reset before headers. reset reason: connection termination`), would appreciate any help. Here is my config:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
  namespace: app-ns
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: true
    hosts:
    - domain.com
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: secret # secret name in the istio-system namespace
    hosts:
    - domain.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-virtual-service
  namespace: app-ns
spec:
  hosts:
  - domain.com
  gateways:
  - my-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: app-svc.app-ns.svc.cluster.local
        port:
          number: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: app-ns
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
```

The application has a self-signed TLS certificate. If I set `tls.mode: PASSTHROUGH`, it works fine (i.e. `curl -k https://domain.com` serves a correct response). If I remove the self-signed certificate from the app, it also works fine.

But I need to make it work with `tls.mode: SIMPLE` and with the self-signed cert inside the container.
