### ISSUE TITLE
Waypoint authz rules not generated unless auth policy targets waypoint proxy pod

### ISSUE THREAD

**Issue by dhawton** [istio/istio#43476]
### Bug Description

Waypoint proxy authz rules don't seem to be applied any longer. Against HEAD, building a gateway with

```shell
istioctl x waypoint apply -n test --service-account httpbin
```

And then applying the Authz Policy of:

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: httpbin-deny-sleep
 namespace: test
spec:
 selector:
   matchLabels:
     app: httpbin
 action: DENY
 rules:
 - from:
   - source:
       principals: ["cluster.local/ns/test/sa/sleep"]
   to:
   - operation:
       methods: ["GET"]
```

I expect a 403 response or some kind of rejection when I run a curl from sleep, but I get a success response.  I can see in the access logs of the Waypoint that the request was received and forwarded:

[2023-02-20T21:20:54Z] "GET /get HTTP/1.1" 200 - via_upstream - "-" 0 0 2 2 "-" "curl/7.87.0-DEV" "1e7261ac-72a1-46e1-84b3-b620a45f9abe" "httpbin.test:8000" "envoy://connect_originate/10.244.2.4:80" inbound-vip|8000|http|httpbin.test.svc.cluster.local envoy://internal_client_address/ 10.96.34.189:8000 envoy://internal_client_address/ - default

In the config_dump, I am not seeing the rule even being generated to be checked by Envoy.

cc: @shashankram 

### Version

```prose
❯ id version
client version: 1.18-dev
control plane version: 1.18-dev
data plane version:  (3 proxies), 1.18-dev (2 proxies)

kind:
❯ k version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.25.3
```
