### ISSUE TITLE
Anomalies in request routing based on header match using VirtualService

### ISSUE THREAD

**Issue by RaiAnandKr** [istio/istio#43490]
### Bug Description

Here are the basic destination rule and virtual service I have set up:

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: xyz
spec:
  host: xyz
  subsets:
  - name: alpha
    labels:
      version: "30071875"
  - name: prod
    labels:
      version: "29917846"
```

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: xyz
spec:
 hosts:
 - xyz
 http:
 - match:
   - headers:
      USER-AGENT:
        exact: grpc-go/1.45.0
   route:
    - destination:
        host: xyz
        subset: alpha
 - route:
     - destination:
         host: xyz
         subset: prod
```

This works fine for the most part where requests with `USER-AGENT` header set to `grpc-go/1.45.0` are served by the `alpha` subset of pods (i.e. pod with `version: "30071875"`) and all other requests are served by `prod` subset of pods.

But every now and then, I see anomalies in the request routing. For e.g. a request with `"user_agent":"grpc-python/1.41.1 grpc-c/19.0.0 (linux; chttp2)"` goes to alpha pods while it should go to prod pods. Again, to be clear, the same request routes fine to prod pods most of the times but 3 out of 10 times (a rough estimate) it goes to alpha pods. Is this behaviour expected i.e. the routing isn't guaranteed to be 100% accurate ? What could be causing this? What can I look at to debug such issues?

I fear that in one of our large scale apps, these anomalies could still have a considerable impact.

### Version

```prose
istioctl version
client version: 1.16.1
control plane version: 1.16.1
data plane version: 1.16.1 (13 proxies)

kubectl version --short
Client Version: v1.21.1
Server Version: v1.22.17
```
