### ISSUE TITLE
SSL broken after istio upgrade

### ISSUE THREAD

**Issue by Yeroha** [istio/istio#43527]
### Bug Description

Hi everyone. After upgrade istio to 1.16.2 we get broken SSL. Gateway doesn't accept https traffic, http normal
```
curl -v https://keycloak.example.com
*   Trying 178.154.227.142:443...
* Connected to keycloak.example.com (<IP ADDR>) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: Connection reset by peer in connection to keycloak.example.com:443 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to keycloak.example.com:443
```

Manifests:
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: gw-test
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*.example.com"
    tls:
      httpsRedirect: true
  - hosts:
      - "*.example.com"
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: cert-from-digicert
      mode: SIMPLE
```
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: keycloak-stage-vs
  namespace: keycloak
spec:
  hosts:
  - "keycloak.example.com"
  gateways:
  - istio-system/gw-test
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: keycloak-http
        port:
          number: 80
```

### Version

```prose
$ istioctl version
client version: 1.16.2
control plane version: 1.16.2
data plane version: 1.16.2 (2 proxies)
$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.1
Kustomize Version: v4.5.4
Server Version: v1.22.6
WARNING: version difference between client (1.24) and server (1.22) exceeds the supported minor version skew of +/-1
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
