### ISSUE TITLE
Allow all cookies

### ISSUE THREAD

**Issue by Rez0k** [istio/istio#43533]
Hi,

I am using istio with envoy as a sidecar.
I am using external auth provider which set session-id cookie in the response headers if the auth succeeded.

Before istio everything worked fine, but after applying istio with the envoy sidecar the session-id cookie is not reaching as a response header.

I tried creating envoy filter to allow the cookie in the response header to pass, but it does not seems to work.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: secure-session-cookie-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.lua
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
            inlineCode: |
              function envoy_on_request(request_handle)
                local headers = request_handle:headers()
                request_handle:streamInfo():dynamicMetadata():set("envoy.filters.http.lua", "cookies", headers:get("set-cookie"))
              end

              function envoy_on_response(response_handle)
                local cookies = response_handle:streamInfo():dynamicMetadata():get("envoy.filters.http.lua")["cookies"]
                response_handle:headers():add("set-cookie", cookies)
              end
```

I tried applying this yaml to allow set-cookie but it does not work.
Can you please help me set the envoy filter to work with istio?

**Comment by hanxiaop** [comment]
Have you tried ext authz feature? You may look at https://istio.io/latest/docs/tasks/security/authorization/authz-custom/

**Comment by Rez0k** [comment]
> Have you tried ext authz feature? You may look at https://istio.io/latest/docs/tasks/security/authorization/authz-custom/

Yea, I did try the following:

```apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: custom-sso
spec:
  hosts:
  - <external-host-url>
    location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
  ```
  
  and then changed istio configmap to:
  ```
extensionProviders:
    - name: "custom-auth"
      envoyExtAuthzHttp:
        service: "<external-host-url"
        port: "443"
        includeRequestHeadersInCheck: ["authorization", "cookie", "set-cookie"] 
        headersToUpstreamOnAllow: ["authorization", "path", "x-auth-request-user", "x-auth-request-email", "x-auth-request-access-token", "set-cookie"]
        headersToDownstreamOnDeny: ["content-type", "set-cookie"]
```

and still, it does not seem to work.
What did I miss?

But honestly, I don't want this feature 
I am implementing Istio on existing working app that use auth provider.

All I want it to work. Are you telling me that I have to do it the way you mentioned?

I really need a workaround. I feel very stuck.

**Comment by hanxiaop** [comment]
I think maybe you need `HeadersToDownstreamOnAllow` to set the header for the client?

**Comment by Rez0k** [comment]
> I think maybe you need `HeadersToDownstreamOnAllow` to set the header for the client?

I update istio configmap in istio-system as the following:
```
extensionProviders:
  - name: "custom-auth"
    envoyExtAuthzHttp:
      service: "<external-host-url>"
      port: "443"
      includeRequestHeadersInCheck: ["authorization", "cookie", "set-cookie"] 
      headersToUpstreamOnAllow: ["authorization", "path", "x-auth-request-user", "x-auth-request-email", "x-auth-request-access-token", "set-cookie"]
      headersToDownstreamOnAllow: ["content-type", "set-cookie"]
      headersToDownstreamOnDeny: ["content-type", "set-cookie"]
```

I tried applying with my external auth provider but it did not work.
Can I use something like '*' in the envoyExtAuthzHttp.service?

**Comment by Rez0k** [comment]
Any help?

I am stuck with issue for too long.

I believed that implementing istio will be almost transparent, I don't want to create oauth2 service or anything like this,
I just want my app to work like it worked before.

Right now my app is disabled because I cant log in with sso.

Please help me figure this out.

Can I use just use the service that is making the sso request without any oauth service? 
```
extensionProviders:
  - name: "custom-auth"
    envoyExtAuthzHttp:
      service: "<internal-service-that-ask-for-sessionId-cookie>"
      port: "80"
      includeRequestHeadersInCheck: ["authorization", "cookie", "set-cookie"] 
      headersToUpstreamOnAllow: ["authorization", "path", "x-auth-request-user", "x-auth-request-email", "x-auth-request-access-token", "set-cookie"]
      headersToDownstreamOnAllow: ["content-type", "set-cookie"]
      headersToDownstreamOnDeny: ["content-type", "set-cookie"]

```
