### ISSUE TITLE
Istio ingress controller does not respect k8s default back end

### ISSUE THREAD

**Issue by ratulb** [istio/istio#43566]
### Bug Description

I defined a ClusterIP service and defined a k8s ingress with the cluster ip service as the default backend and faced 404 error while accessing the service via ingress controller.

Resource definitions:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocket-app-deployment
spec:
  selector:
    matchLabels:
      pod_name: rocket-app
  replicas: 1 
  template:
    metadata:
      labels:
        pod_name: rocket-app
    spec:
      containers:
      - name: rocket-app
        image: ratulb/rocket-app_v3:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rocket-app-service
spec:
  selector:
    pod_name: rocket-app
  type: ClusterIP
  ports:
  - name: rocket-app-service-port
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    #kubernetes.io/ingress.class: istio
  name: default-rocket-ingress
spec:
  defaultBackend:
    service:
      name: rocket-app-service
      port: 
        number: 8080
  ingressClassName: istio
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: istio
spec:
  controller: istio.io/ingress-controller

```
The same thing works if I try with nginx controller.

### Version

```prose
istioctl version
client version: 1.17.0
control plane version: 1.17.0
data plane version: 1.17.0 (3 proxies)

====================================
kubectl version -o yaml
clientVersion:
  buildDate: "2023-01-18T15:58:16Z"
  compiler: gc
  gitCommit: 8f94681cd294aa8cfd3407b8191f6c70214973a4
  gitTreeState: clean
  gitVersion: v1.26.1
  goVersion: go1.19.5
  major: "1"
  minor: "26"
  platform: linux/amd64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2023-01-18T15:51:25Z"
  compiler: gc
  gitCommit: 8f94681cd294aa8cfd3407b8191f6c70214973a4
  gitTreeState: clean
  gitVersion: v1.26.1
  goVersion: go1.19.5
  major: "1"
  minor: "26"
  platform: linux/amd64
```

**Comment by howardjohn** [comment]
This is explicitly not supported: https://github.com/istio/istio/blob/ff2bbfdd42997f7a4a05251565d5a64ca02907a1/pilot/pkg/config/kube/ingress/conversion.go#L238

**Comment by ratulb** [comment]
The only catch all backend for missing resources that seem to be working is:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: ingress
spec:
  #ingressClassName: istio
  rules:
  - http:
      paths:
      - path: /.*
        pathType: ImplementationSpecific #Prefix
        backend:
          service:
            name: rocket-app-service
            port:
              number: 8080
```
For pathType: Prefix - I get a 404

Is this a viable alternative to k8s' default ingress backend?
