### ISSUE TITLE
Istio internal DNS resolution intermittent failures

### ISSUE THREAD

**Issue by allen-bmf** [istio/istio#43579]
### Bug Description

I am accessing redis and mysql using aws route53 private record.
When accessing an external service
Is the service item mesh_external required?

Apps using istio intermittently fail dns lookup.
(Non istio apps have no problem)

my cluster container about 1000

### Version

```prose
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: installed-state
spec:
  tag: 1.14.1
  meshConfig:
    accessLogFile: ""
    enablePrometheusMerge: true
    localityLbSetting:
      enabled: false
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
  components:
    ingressGateways:
      - name: istio-ingressgateway
        namespace: istio-system
        enabled: true
        k8s:
          service:
            type: NodePort
            ports:
              - name: status-port
                protocol: TCP
                port: 15021
                targetPort: 15021
                nodePort: 30420
              - name: http2
                protocol: TCP
                port: 80
                targetPort: 8080
                nodePort: 30421
              - name: https
                protocol: TCP
                port: 443
                targetPort: 8443
                nodePort: 30422
          hpaSpec:
            minReplicas: 3
            maxReplicas: 3
          strategy:
            rollingUpdate:
              maxSurge: 100%
              maxUnavailable: 0
          podDisruptionBudget:
            minAvailable: 25%
          overlays:
            - kind: Deployment
              name: istio-ingressgateway
              patches:
                - path: spec.template.spec.containers[name:istio-proxy].lifecycle.preStop.exec.command
                  value:
                    - "/bin/sh"
                    - "-c"
                    - "sleep 180"
                - path: spec.template.spec.topologySpreadConstraints
                  value:
                    - maxSkew: 1
                      topologyKey: topology.kubernetes.io/zone
                      whenUnsatisfiable: ScheduleAnyway
                      labelSelector:
                        matchLabels:
                          istio: ingressgateway
                - path: spec.template.spec.terminationGracePeriodSeconds
                  value: 200
```

### Additional Information

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: redis
  namespace: istio-system
spec:
  hosts:
    - 'xxx-redis.xxxx.internal' // aws route53 private record
    - 'xxxx-redis.xxxx.internal'
    - 'xxxxx-redis.xxxx.internal'
    - 'xxxx-queue-redis.xxxx.internal'
  location: MESH_EXTERNAL
  ports:
    - name: redis
      number: 7777
      protocol: TCP
  resolution: NONE
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: mysql-aurora
  namespace: istio-system
spec:
  hosts:
    - 'xxxxx-mysql.xxxxx.internal'
    - 'xxxxx-mysql-ro.xxxxx.internal'
  location: MESH_EXTERNAL
  ports:
    - name: mysql
      number: 4477
      protocol: TCP
  resolution: NONE
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: mongo
  namespace: istio-system
spec:
  hosts:
    - '*.mongodb.net'  // using atlas mongodb (vpc peering)
  location: MESH_EXTERNAL
  ports:
    - name: mongo
      number: 27017
      protocol: TCP
  resolution: NONE
```
