### ISSUE TITLE
Does envoyOtelAls service support localhost or $(HOST_IP), thanks.

### ISSUE THREAD

**Issue by johnzheng1975** [istio/istio#43575]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Does envoyOtelAls service support  $(HOST_IP)? Currently it have to input service name like: splunk-otel.infra.svc.cluster.local
```
$kubectl edit cm -n istio-system istio
... ...
  mesh: |-
    accessLogEncoding: JSON
    ... ...
    extensionProviders:
    - envoyOtelAls:
        port: 4317
        service: splunk-otel.infra.svc.cluster.local
      name: otel
```

You know, below zipkin address support  $(HOST_IP) well
```
  mesh: |-
    defaultConfig:
      tracing:
        zipkin:
          address:  $(HOST_IP):9411
```

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
