### ISSUE TITLE
Authz policy not enforced with waypoint

### ISSUE THREAD

**Issue by linsun** [istio/istio#43576]
### Bug Description

Following our get started guide for ambient - https://docs.google.com/document/d/1gnnYg8LMTsANc85RHtp4t_4EMWKsv-Ev-Eu0glNLqEo/edit?usp=sharing, the authz policy for L4 works, but not L7.

```
$ # this should fail with an RBAC error because it is not a GET operation
$ kubectl exec deploy/sleep -- curl -s http://productpage:9080/ -X DELETE
$ # this should fail with an RBAC error because the identity is not allowed
$ kubectl exec deploy/notsleep -- curl -s http://productpage:9080/  | head -n1
$ # this should continue to work
$ kubectl exec deploy/sleep -- curl -s http://productpage:9080/ | head -n1
```

Specifically, it didn't fail with RBAC error when calling from notsleep.

```
kubectl exec deploy/notsleep -- curl -s http://productpage:9080/
<!DOCTYPE html>
<html>
  <head>
    <title>Simple Bookstore App</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
```

Waypoint proxy log didn't indicate any rbac error, I would expect to fail here.

```
[2023-02-24T03:32:28.882Z] "GET / HTTP/1.1" 200 - via_upstream - "-" 0 1683 3 2 "-" "curl/7.88.1-DEV" "5ea5eb0a-f4b9-4d6e-8a39-717d6da78f7c" "productpage:9080" "envoy://connect_originate/10.244.1.15:9080" inbound-vip|9080|http|productpage.default.svc.cluster.local envoy://internal_client_address/ 10.96.199.135:9080 envoy://internal_client_address/ - default
```

Did get a 405 on the DELETE method req earlier:

```
[2023-02-24T03:30:38.329Z] "DELETE / HTTP/1.1" 405 - via_upstream - "-" 0 178 3 3 "-" "curl/7.88.1-DEV" "366984cc-c8b9-424e-b560-15c37b8a52d8" "productpage:9080" "envoy://connect_originate/10.244.1.15:9080" inbound-vip|9080|http|productpage.default.svc.cluster.local envoy://internal_client_address/ 10.96.199.135:9080 envoy://internal_client_address/ - default
```

Ztunnel log (where productpage runs) has no error as it checks if waypoint's identity is allowed:

```
2023-02-24T03:33:14.995728Z  INFO inbound{id=3fb2521ec04a3616356aaf30a482ff50 peer_ip=10.244.1.16 peer_id=spiffe://cluster.local/ns/default/sa/bookinfo-productpage-istio-waypoint}: ztunnel::proxy::inbound: got CONNECT request to 10.244.1.15:9080
2023-02-24T03:33:29.973473Z  INFO inbound{id=406891f726b2e91568731f8a0b258d63 peer_ip=10.244.1.16 peer_id=spiffe://cluster.local/ns/default/sa/bookinfo-productpage-istio-waypoint}: ztunnel::proxy::inbound: got CONNECT request to 10.244.1.15:9080
```

### Version

```prose
1.8-dev
```

**Comment by linsun** [comment]
cc @howardjohn @kyessenov

**Comment by kyessenov** [comment]
Can you dump the envoy config for the waypoint?

**Comment by linsun** [comment]
@kyessenov this?

```
 istioctl pc l gtw/bookinfo-productpage -o yaml
- address:
    socketAddress:
      address: 0.0.0.0
      portValue: 15008
  filterChains:
  - filters:
    - name: istio_authn
      typedConfig:
        '@type': type.googleapis.com/udpa.type.v1.TypedStruct
        typeUrl: type.googleapis.com/io.istio.network.authn.Config
        value:
          shared: true
    - name: envoy.filters.network.http_connection_manager
      typedConfig:
        '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
        forwardClientCertDetails: APPEND_FORWARD
        http2ProtocolOptions:
          allowConnect: true
        httpFilters:
        - name: connect_baggage
          typedConfig:
            '@type': type.googleapis.com/udpa.type.v1.TypedStruct
            typeUrl: type.googleapis.com/io.istio.http.connect_baggage.Config
        - name: connect_authority
          typedConfig:
            '@type': type.googleapis.com/udpa.type.v1.TypedStruct
            typeUrl: type.googleapis.com/io.istio.http.connect_authority.Config
        - name: envoy.filters.http.router
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
        routeConfig:
          name: default
          virtualHosts:
          - domains:
            - '*'
            name: default
            routes:
            - match:
                connectMatcher: {}
              route:
                cluster: internal
                upgradeConfigs:
                - connectConfig: {}
                  upgradeType: CONNECT
              typedPerFilterConfig:
                connect_authority:
                  '@type': type.googleapis.com/udpa.type.v1.TypedStruct
                  typeUrl: type.googleapis.com/io.istio.http.connect_authority.Config
                  value:
                    enabled: true
                    port: 15008
        serverName: istio-envoy
        setCurrentClientCertDetails:
          dns: true
          subject: true
          uri: true
        statPrefix: connect_terminate
        streamIdleTimeout: 0s
        upgradeConfigs:
        - upgradeType: CONNECT
        useRemoteAddress: false
    name: default
    transportSocket:
      name: tls
      typedConfig:
        '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
        commonTlsContext:
          alpnProtocols:
          - h2
          combinedValidationContext:
            defaultValidationContext:
              matchSubjectAltNames:
              - prefix: spiffe://cluster.local/
            validationContextSdsSecretConfig:
              name: ROOTCA
              sdsConfig:
                apiConfigSource:
                  apiType: GRPC
                  grpcServices:
                  - envoyGrpc:
                      clusterName: sds-grpc
                  setNodeOnFirstMessageOnly: true
                  transportApiVersion: V3
                initialFetchTimeout: 0s
                resourceApiVersion: V3
          tlsCertificateSdsSecretConfigs:
          - name: default
            sdsConfig:
              apiConfigSource:
                apiType: GRPC
                grpcServices:
                - envoyGrpc:
                    clusterName: sds-grpc
                setNodeOnFirstMessageOnly: true
                transportApiVersion: V3
              initialFetchTimeout: 0s
              resourceApiVersion: V3
          tlsParams:
            tlsMaximumProtocolVersion: TLSv1_3
            tlsMinimumProtocolVersion: TLSv1_3
  name: connect_terminate
- filterChainMatcher:
    matcherTree:
      customMatch:
        name: ip
        typedConfig:
          '@type': type.googleapis.com/xds.type.matcher.v3.IPMatcher
          rangeMatchers:
          - onMatch:
              matcher:
                matcherTree:
                  exactMatchMap:
                    map:
                      "443":
                        action:
                          name: inbound-vip|443||kubernetes.default.svc.cluster.local-tcp
                          typedConfig:
                            '@type': type.googleapis.com/google.protobuf.StringValue
                            value: inbound-vip|443||kubernetes.default.svc.cluster.local-tcp
                  input:
                    name: port
                    typedConfig:
                      '@type': type.googleapis.com/envoy.extensions.matching.common_inputs.network.v3.DestinationPortInput
            ranges:
            - addressPrefix: 10.96.0.1
              prefixLen: 32
          - onMatch:
              matcher:
                matcherTree:
                  exactMatchMap:
                    map:
                      "9080":
                        action:
                          name: inbound-vip|9080||productpage.default.svc.cluster.local-http
                          typedConfig:
                            '@type': type.googleapis.com/google.protobuf.StringValue
                            value: inbound-vip|9080||productpage.default.svc.cluster.local-http
                  input:
                    name: port
                    typedConfig:
                      '@type': type.googleapis.com/envoy.extensions.matching.common_inputs.network.v3.DestinationPortInput
            ranges:
            - addressPrefix: 10.96.175.50
              prefixLen: 32
          - onMatch:
              matcher:
                matcherTree:
                  exactMatchMap:
                    map:
                      '''h2c''':
                        action:
                          name: direct-http
                          typedConfig:
                            '@type': type.googleapis.com/google.protobuf.StringValue
                            value: direct-http
                      '''http/1.1''':
                        action:
                          name: direct-http
                          typedConfig:
                            '@type': type.googleapis.com/google.protobuf.StringValue
                            value: direct-http
                  input:
                    name: application-protocol
                    typedConfig:
                      '@type': type.googleapis.com/envoy.extensions.matching.common_inputs.network.v3.ApplicationProtocolInput
                onNoMatch:
                  action:
                    name: direct-tcp
                    typedConfig:
                      '@type': type.googleapis.com/google.protobuf.StringValue
                      value: direct-tcp
            ranges:
            - addressPrefix: 10.244.1.9
              prefixLen: 32
      input:
        name: ip
        typedConfig:
          '@type': type.googleapis.com/envoy.extensions.matching.common_inputs.network.v3.DestinationIPInput
  filterChains:
  - filters:
    - name: istio.stats
      typedConfig:
        '@type': type.googleapis.com/udpa.type.v1.TypedStruct
        typeUrl: type.googleapis.com/stats.PluginConfig
        value:
          reporter: SERVER_GATEWAY
    - name: envoy.filters.network.tcp_proxy
      typedConfig:
        '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
        accessLog:
        - name: envoy.access_loggers.file
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
            logFormat:
              textFormatSource:
                inlineString: |
                  [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% "%UPSTREAM_TRANSPORT_FAILURE_REASON%" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%
            path: /dev/stdout
        cluster: inbound-vip|443|tcp|kubernetes.default.svc.cluster.local
        statPrefix: inbound-vip|443|tcp|kubernetes.default.svc.cluster.local
    name: inbound-vip|443||kubernetes.default.svc.cluster.local-tcp
  - filters:
    - name: envoy.filters.network.http_connection_manager
      typedConfig:
        '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
        accessLog:
        - name: envoy.access_loggers.file
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
            logFormat:
              textFormatSource:
                inlineString: |
                  [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% "%UPSTREAM_TRANSPORT_FAILURE_REASON%" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%
            path: /dev/stdout
        forwardClientCertDetails: APPEND_FORWARD
        httpFilters:
        - name: envoy.filters.http.fault
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.http.fault.v3.HTTPFault
        - name: envoy.filters.http.cors
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
        - name: istio.stats
          typedConfig:
            '@type': type.googleapis.com/udpa.type.v1.TypedStruct
            typeUrl: type.googleapis.com/stats.PluginConfig
            value:
              reporter: SERVER_GATEWAY
        - name: envoy.filters.http.router
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
        normalizePath: true
        pathWithEscapedSlashesAction: KEEP_UNCHANGED
        requestIdExtension:
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.request_id.uuid.v3.UuidRequestIdConfig
            useRequestIdForTraceSampling: true
        routeConfig:
          name: inbound-vip|9080|http|productpage.default.svc.cluster.local
          validateClusters: false
          virtualHosts:
          - domains:
            - '*'
            name: inbound|http|9080
            routes:
            - decorator:
                operation: :9080/*
              match:
                prefix: /
              name: default
              route:
                cluster: inbound-vip|9080|http|productpage.default.svc.cluster.local
                maxStreamDuration:
                  grpcTimeoutHeaderMax: 0s
                  maxStreamDuration: 0s
                timeout: 0s
        serverName: istio-envoy
        setCurrentClientCertDetails:
          dns: true
          subject: true
          uri: true
        statPrefix: inbound_0.0.0.0_9080
        streamIdleTimeout: 0s
        tracing:
          clientSampling:
            value: 100
          customTags:
          - metadata:
              kind:
                request: {}
              metadataKey:
                key: envoy.filters.http.rbac
                path:
                - key: istio_dry_run_allow_shadow_effective_policy_id
            tag: istio.authorization.dry_run.allow_policy.name
          - metadata:
              kind:
                request: {}
              metadataKey:
                key: envoy.filters.http.rbac
                path:
                - key: istio_dry_run_allow_shadow_engine_result
            tag: istio.authorization.dry_run.allow_policy.result
          - metadata:
              kind:
                request: {}
              metadataKey:
                key: envoy.filters.http.rbac
                path:
                - key: istio_dry_run_deny_shadow_effective_policy_id
            tag: istio.authorization.dry_run.deny_policy.name
          - metadata:
              kind:
                request: {}
              metadataKey:
                key: envoy.filters.http.rbac
                path:
                - key: istio_dry_run_deny_shadow_engine_result
            tag: istio.authorization.dry_run.deny_policy.result
          - literal:
              value: latest
            tag: istio.canonical_revision
          - literal:
              value: bookinfo-productpage-istio-waypoint
            tag: istio.canonical_service
          - literal:
              value: cluster.local
            tag: istio.mesh_id
          - literal:
              value: default
            tag: istio.namespace
          overallSampling:
            value: 100
          randomSampling:
            value: 1
        upgradeConfigs:
        - upgradeType: websocket
        useRemoteAddress: false
    name: inbound-vip|9080||productpage.default.svc.cluster.local-http
  - filters:
    - name: connect_authority
      typedConfig:
        '@type': type.googleapis.com/udpa.type.v1.TypedStruct
        typeUrl: type.googleapis.com/io.istio.http.connect_authority.Config
    - name: istio.stats
      typedConfig:
        '@type': type.googleapis.com/udpa.type.v1.TypedStruct
        typeUrl: type.googleapis.com/stats.PluginConfig
        value:
          reporter: SERVER_GATEWAY
    - name: envoy.filters.network.tcp_proxy
      typedConfig:
        '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
        accessLog:
        - name: envoy.access_loggers.file
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
            logFormat:
              textFormatSource:
                inlineString: |
                  [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% "%UPSTREAM_TRANSPORT_FAILURE_REASON%" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%
            path: /dev/stdout
        cluster: encap
        statPrefix: encap
    name: direct-tcp
  - filters:
    - name: connect_authority
      typedConfig:
        '@type': type.googleapis.com/udpa.type.v1.TypedStruct
        typeUrl: type.googleapis.com/io.istio.http.connect_authority.Config
    - name: envoy.filters.network.http_connection_manager
      typedConfig:
        '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
        accessLog:
        - name: envoy.access_loggers.file
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
            logFormat:
              textFormatSource:
                inlineString: |
                  [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% "%UPSTREAM_TRANSPORT_FAILURE_REASON%" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%
            path: /dev/stdout
        forwardClientCertDetails: APPEND_FORWARD
        httpFilters:
        - name: envoy.filters.http.fault
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.http.fault.v3.HTTPFault
        - name: envoy.filters.http.cors
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
        - name: istio.stats
          typedConfig:
            '@type': type.googleapis.com/udpa.type.v1.TypedStruct
            typeUrl: type.googleapis.com/stats.PluginConfig
            value:
              reporter: SERVER_GATEWAY
        - name: envoy.filters.http.router
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
        normalizePath: true
        pathWithEscapedSlashesAction: KEEP_UNCHANGED
        requestIdExtension:
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.request_id.uuid.v3.UuidRequestIdConfig
            useRequestIdForTraceSampling: true
        routeConfig:
          name: encap
          validateClusters: false
          virtualHosts:
          - domains:
            - '*'
            name: inbound|http|0
            routes:
            - decorator:
                operation: :0/*
              match:
                prefix: /
              name: default
              route:
                cluster: encap
                maxStreamDuration:
                  grpcTimeoutHeaderMax: 0s
                  maxStreamDuration: 0s
                timeout: 0s
        serverName: istio-envoy
        setCurrentClientCertDetails:
          dns: true
          subject: true
          uri: true
        statPrefix: inbound_0.0.0.0_0
        streamIdleTimeout: 0s
        tracing:
          clientSampling:
            value: 100
          customTags:
          - metadata:
              kind:
                request: {}
              metadataKey:
                key: envoy.filters.http.rbac
                path:
                - key: istio_dry_run_allow_shadow_effective_policy_id
            tag: istio.authorization.dry_run.allow_policy.name
          - metadata:
              kind:
                request: {}
              metadataKey:
                key: envoy.filters.http.rbac
                path:
                - key: istio_dry_run_allow_shadow_engine_result
            tag: istio.authorization.dry_run.allow_policy.result
          - metadata:
              kind:
                request: {}
              metadataKey:
                key: envoy.filters.http.rbac
                path:
                - key: istio_dry_run_deny_shadow_effective_policy_id
            tag: istio.authorization.dry_run.deny_policy.name
          - metadata:
              kind:
                request: {}
              metadataKey:
                key: envoy.filters.http.rbac
                path:
                - key: istio_dry_run_deny_shadow_engine_result
            tag: istio.authorization.dry_run.deny_policy.result
          - literal:
              value: latest
            tag: istio.canonical_revision
          - literal:
              value: bookinfo-productpage-istio-waypoint
            tag: istio.canonical_service
          - literal:
              value: cluster.local
            tag: istio.mesh_id
          - literal:
              value: default
            tag: istio.namespace
          overallSampling:
            value: 100
          randomSampling:
            value: 1
        upgradeConfigs:
        - upgradeType: websocket
        useRemoteAddress: false
    name: direct-http
  internalListener: {}
  listenerFilters:
  - name: set_dst_address
    typedConfig:
      '@type': type.googleapis.com/xds.type.v3.TypedStruct
      typeUrl: type.googleapis.com/istio.set_internal_dst_address.v1.Config
      value: {}
  - name: envoy.filters.listener.http_inspector
    typedConfig:
      '@type': type.googleapis.com/envoy.extensions.filters.listener.http_inspector.v3.HttpInspector
  name: internal
  trafficDirection: INBOUND
- filterChains:
  - filters:
    - name: envoy.filters.network.tcp_proxy
      typedConfig:
        '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
        cluster: connect_originate
        statPrefix: connect_originate
        tunnelingConfig:
          hostname: '%DOWNSTREAM_LOCAL_ADDRESS%'
  internalListener: {}
  listenerFilters:
  - name: set_dst_address
    typedConfig:
      '@type': type.googleapis.com/xds.type.v3.TypedStruct
      typeUrl: type.googleapis.com/istio.set_internal_dst_address.v1.Config
      value: {}
  name: connect_originate
  useOriginalDst: false
- accessLog:
  - filter:
      responseFlagFilter:
        flags:
        - NR
    name: envoy.access_loggers.file
    typedConfig:
      '@type': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
      logFormat:
        textFormatSource:
          inlineString: |
            [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% "%UPSTREAM_TRANSPORT_FAILURE_REASON%" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%
      path: /dev/stdout
  filterChains:
  - filters:
    - name: envoy.filters.network.tcp_proxy
      typedConfig:
        '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
        accessLog:
        - name: envoy.access_loggers.file
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
            logFormat:
              textFormatSource:
                inlineString: |
                  [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% "%UPSTREAM_TRANSPORT_FAILURE_REASON%" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%
            path: /dev/stdout
        cluster: outbound-tunnel
        statPrefix: outbound-tunnel
        tunnelingConfig:
          hostname: '%DOWNSTREAM_LOCAL_ADDRESS%'
  internalListener: {}
  listenerFilters:
  - name: set_dst_address
    typedConfig:
      '@type': type.googleapis.com/xds.type.v3.TypedStruct
      typeUrl: type.googleapis.com/istio.set_internal_dst_address.v1.Config
      value: {}
  name: outbound-tunnel
  useOriginalDst: false
- address:
    socketAddress:
      address: 0.0.0.0
      portValue: 15090
  filterChains:
  - filters:
    - name: envoy.filters.network.http_connection_manager
      typedConfig:
        '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
        httpFilters:
        - name: envoy.filters.http.router
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
        routeConfig:
          virtualHosts:
          - domains:
            - '*'
            name: backend
            routes:
            - match:
                prefix: /stats/prometheus
              route:
                cluster: prometheus_stats
        statPrefix: stats
- address:
    socketAddress:
      address: 0.0.0.0
      portValue: 15021
  filterChains:
  - filters:
    - name: envoy.filters.network.http_connection_manager
      typedConfig:
        '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
        httpFilters:
        - name: envoy.filters.http.router
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
        routeConfig:
          virtualHosts:
          - domains:
            - '*'
            name: backend
            routes:
            - match:
                prefix: /healthz/ready
              route:
                cluster: agent
        statPrefix: agent
```
