### ISSUE TITLE
pod Injection failure

### ISSUE THREAD

**Issue by zzguang520** [istio/istio#43593]
Hi team,
   I have use istio v 1.17.0 by helm: 
and I have set the enable to sidecar Injection for namespace
but, now have error when I deploy my app:
```
Error creating: Internal error occurred: failed calling webhook "[namespace.sidecar-injector.istio.io](http://namespace.sidecar-injector.istio.io/)": failed to call webhook: Post "[https://istiod.istio-system.svc:443/inject?timeout=10s](https://istiod.istio-system.svc/inject?timeout=10s)": context deadline exceeded
```
install istio 
```
kubectl create namespace istio-system
helm install istio-base istio/base -n istio-system
helm install istiod istio/istiod -n istio-system

helm list -n istio-system
NAME      	NAMESPACE   	REVISION	UPDATED                                	STATUS  	CHART        	APP VERSION
istio-base	istio-system	2       	2023-02-21 22:08:24.297146855 -0500 EST	deployed	base-1.17.0  	1.17.0
istiod    	istio-system	2       	2023-02-21 22:09:02.292086364 -0500 EST	deployed	istiod-1.17.0	1.17.0
```
k8s info
```
kubectl version --output=yaml
clientVersion:
  buildDate: "2022-11-09T13:38:19Z"
  compiler: gc
  gitCommit: fdc77503e954d1ee641c0e350481f7528e8d068b
  gitTreeState: clean
  gitVersion: v1.24.8
  goVersion: go1.18.8
  major: "1"
  minor: "24"
  platform: linux/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-11-09T13:31:40Z"
  compiler: gc
  gitCommit: fdc77503e954d1ee641c0e350481f7528e8d068b
  gitTreeState: clean
  gitVersion: v1.24.8
  goVersion: go1.18.8
  major: "1"
  minor: "24"
  platform: linux/amd64
```
I have troubleshooting with this pages: https://github.com/istio/istio/wiki/Troubleshooting-Istio#sidecar-injection
```
kubectl get --raw /api/v1/namespaces/istio-system/services/https:istiod:https-webhook/proxy/inject -v4
I0224 11:26:14.950601  158025 helpers.go:246] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "the server rejected our request for an unknown reason",
  "reason": "BadRequest",
  "details": {
    "causes": [
      {
        "reason": "UnexpectedServerResponse",
        "message": "no body found"
      }
    ]
  },
  "code": 400
}]
Error from server (BadRequest): the server rejected our request for an unknown reason
[root@master1 ~]# kubectl exec istiod-58bd97fff4-kgctl -n istio-system -- curl https://localhost:15017/inject -k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0    668      0 no body found-:-- --:--:--     0
--:--:-- --:--:-- --:--:--   700
[root@master1 ~]
```
all is no body found,

I have disable the firewalld on the servers(include master and node )， what‘s issue?

**Comment by vyom-soft** [comment]
Hi,
I am also seeing the same behaviour after injecting the side car. The pod is not coming up. In the replica set of the app (in argocd) [sidecar-injector.istio.io: failed to call webhook](`https://github.com/istio/istio/issues/43882`)

```
status:
  conditions:
    - lastTransitionTime: '2023-03-15T07:53:56Z'
      message: >-
        Internal error occurred: failed calling webhook
        "namespace.sidecar-injector.istio.io": failed to call webhook: Post
        "https://istiod.istio-system.svc:443/inject?timeout=10s": context
        deadline exceeded
      reason: FailedCreate
      status: 'True'
      type: ReplicaFailure
  observedGeneration: 1
  replicas: 0
```
