### ISSUE TITLE
Helm Chart do not apply tag and variant on injected sidecars

### ISSUE THREAD

**Issue by HSoulat** [istio/istio#43629]
### Bug Description

Current helm chart do not apply tag & variant options to injected sidecars. Options are also not available on proxy & proxy_init sections.

```
global:
  istioNamespace: istio-system
  hub: sample.io/library
  tag: 1.16.2
  variant: "distroless"
  proxy:
    image: proxyv2
    autoInject: enabled
  proxy_init:
    image: proxyv2
```

The "latest" tag is applied to injected sidecars. However, hub is correctly configured 
```
  istio-proxy:
    Container ID:
    Image:         sample.io/library/proxyv2:latest
```

### Version

```prose
kubectl version : v1.23.8
```

**Comment by howardjohn** [comment]
what does your `istio` configmap look like?

Should be:

```
$ helm template manifests/charts/istio-control/istio-discovery -f /tmp/v.yaml | k grep ConfigMap/istio
---
# Source: istiod/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio
  namespace: default
  labels:
    istio.io/rev: default
    install.operator.istio.io/owning-resource: unknown
    operator.istio.io/component: "Pilot"
    release: release-name
data:

  # Configuration file for the mesh networks to be used by the Split Horizon EDS.
  meshNetworks: |-
    networks: {}

  mesh: |-
    defaultConfig:
      discoveryAddress: istiod.default.svc:15012
      image:
        imageType: distroless
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
    enablePrometheusMerge: true
    rootNamespace: istio-system
    trustDomain: cluster.local
```

Note the `distroless` part

What version?

**Comment by HSoulat** [comment]
Here the istio configmap applied, 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio
  namespace: istio-system
  labels:
    install.operator.istio.io/owning-resource: unknown
    istio.io/rev: default
    operator.istio.io/component: Pilot
    release: istio
data:
  meshNetworks: |-
    networks: {}
  mesh: |-
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
    enablePrometheusMerge: true
    rootNamespace: istio-system
    trustDomain: cluster.local
```

We are currently using 1.16.2-distroless version.
