### ISSUE TITLE
How to disable some istio standard metrics ?

### ISSUE THREAD

**Issue by zhangbo1882** [istio/istio#43627]
The istio standard metrics will have huge metrics, especailly  istio_request_bytes and istio_response_bytes.
How can I disable the metrics besides modify the code ?

**Comment by zirain** [comment]
try configuration like following:
```
# export mesh_id cluster_id in metrics
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: custom-metrics
  namespace: istio-system
spec:
  values:
    global:
      meshID: mesh1
    telemetry:
      enabled: true
      v2:
        enabled: true
        prometheus:
          configOverride:
            outboundSidecar:
              metrics:
                - name: requests_total
                  drop: true
            inboundSidecar:
              metrics:
                - name: requests_total
                  drop: true
```
