### ISSUE TITLE
pilot: default passthrough listener/cluster

### ISSUE THREAD

**Issue by rshriram** [istio/istio#4363]
I created this issue 5 months ago, somewhere. I can't find it. So recreating it again.

Until Pilot is ready, the envoys in the cluster will not be able to route anything. This results in a general availability problem, as the pods can't complete their health checks, and thus become visible for a given service. 

One problem snowballs into another, leading to overall poor experience.

One simple way to solve this is to ship a default cluster as part of the initial original dst listener in static config, such that envoy simply acts as a pass through L4 proxy until it gets all the xDS data.
something like this:

```yaml
staticResources:
- listener: 15001
     type: originalDstListener
     filters:
        tcpProxy:
            cluster: passthroughCluster
  cluster:
   - passthroughCluster:
         type: originalDstCluster # passes traffic to original destination
dynamicResources:
- listeners/clusters from LDS/CDS
```

We need to test this logic in Envoy, to see if it allows this.. The listeners from LDS/CDS could be for specific ports/protocols, such that if Envoy sees a listener with a better match, it picks that one. If such a listener does not exist, then it *fallsback* to the default cluster associated with the original_dst listener, which ends up passing traffic through.
