### ISSUE TITLE
 code = Unauthenticated desc = authentication failure integerate istio with karmada muliticluster install error

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#43681]
### Bug Description

2023-03-01T05:55:11.023341Z	info	xdsproxy	connected to upstream XDS server: istiod-remote.istio-system.svc:15012
2023-03-01T05:55:11.036832Z	warn	xdsproxy	upstream [8] terminated with unexpected error rpc error: code = Unauthenticated desc = authentication failure
2023-03-01T05:55:11.038030Z	warning	envoy config external/envoy/source/common/config/grpc_stream.h:163	StreamAggregatedResources gRPC config stream to xds-grpc closed: 16, authentication failure	thread=13

install primary remote in karmada

### 准备

```
 cluster1:
 mkdir -p certs
 make -f ../tools/certs/Makefile.selfsigned.mk root-ca
 make -f ../tools/certs/Makefile.selfsigned.mk primary-cacerts
 make -f ../tools/certs/Makefile.selfsigned.mk cluster1-cacerts
 make -f ../tools/certs/Makefile.selfsigned.mk cluster2-cacerts
 
root@cluster1-144:~/istio-1.17.1/certs# tree
.
├── cluster1
│   ├── ca-cert.pem
│   ├── ca-key.pem
│   ├── cert-chain.pem
│   └── root-cert.pem
├── cluster2
│   ├── ca-cert.pem
│   ├── ca-key.pem
│   ├── cert-chain.pem
│   └── root-cert.pem
├── primary
│   ├── ca-cert.pem
│   ├── ca-key.pem
│   ├── cert-chain.pem
│   └── root-cert.pem
├── root-ca.conf
├── root-cert.csr
├── root-cert.pem
├── root-cert.srl
└── root-key.pem



```

### 安装

```
kubectl create secret generic cacerts  --kubeconfig ~/.kube/147config -n istio-system \
    --from-file=certs/cluster1/ca-cert.pem \
    --from-file=certs/cluster1/ca-key.pem \
    --from-file=certs/cluster1/root-cert.pem \
    --from-file=certs/cluster1/cert-chain.pem

kubectl create secret generic cacerts  --kubeconfig ~/.kube/159config -n istio-system \
    --from-file=certs/cluster2/ca-cert.pem \
    --from-file=certs/cluster2/ca-key.pem \
    --from-file=certs/cluster2/root-cert.pem \
    --from-file=certs/cluster2/cert-chain.pem
```

Run the following command to install istio CRDs on karmada apiserver:

**image: registry.cn-hangzhou.aliyuncs.com/hxpdocker/pilot**

```
cat <<EOF | istioctl install --kubeconfig ~/kube-karmada -y --set profile=minimal -f -
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    accessLogFile: /dev/stdout
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: primary
      network: network1
EOF
```

Karmada apiserver will not deploy a real istiod pod, you should press `ctrl+c` to exit installation when `Processing resources for Istiod`.

```bash
✔ Istio core installed                                                                                                                                                         
- Processing resources for Istiod.
```

**Install Istio on karmada host**

```
kubectl create namespace istio-system
kubectl create secret generic cacerts -n istio-system \
    --from-file=certs/primary/ca-cert.pem \
    --from-file=certs/primary/ca-key.pem \
    --from-file=certs/primary/root-cert.pem \
    --from-file=certs/primary/cert-chain.pem
```

Create istio-kubeconfig on karmada-host

```
kubectl create secret generic istio-kubeconfig --from-file=config=/root/kube-karmada -nistio-system
```

Install istio control plane

```
cat <<EOF | istioctl install -y --set profile=minimal -f -
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    accessLogFile: /dev/stdout
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: primary
      network: network1
EOF
```

Expose istiod service

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: istiod-elb
  namespace: istio-system
spec:
  ports:
  - name: https-dns
    port: 15012
    protocol: TCP
    targetPort: 15012
  selector:
    app: istiod
    istio: pilot
  sessionAffinity: None
  type: LoadBalancer
EOF
```

Export DISCOVERY_ADDRESS:

```bash
export DISCOVERY_ADDRESS=$(kubectl get svc istiod-elb -nistio-system -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
# verify
echo $DISCOVERY_ADDRESS
```

Prepare member cluster secret

```
istioctl x create-remote-secret --name=cluster1 --kubeconfig ~/.kube/147config > istio-remote-secret-cluster1.yaml

istioctl x create-remote-secret --name=cluster2 --kubeconfig ~/.kube/159config  > istio-remote-secret-cluster2.yaml

```

Apply istio remote secret

```
kubectl apply -f istio-remote-secret-cluster1.yaml --kubeconfig ~/kube-karmada

kubectl apply -f istio-remote-secret-cluster2.yaml --kubeconfig ~/kube-karmada
```

Install istio remote cluster1

image: registry.cn-hangzhou.aliyuncs.com/hxpdocker/proxyv2

**需要注意的是 ctr 是 containerd 自带的工具，有命名空间的概念。Kubernetes 下使用的 containerd 默认命名空间是 k8s.io。所以在导入镜像时需要指定命令空间为 k8s.io，否则使用 crictl images 无法查询到。**

```
cat <<EOF | istioctl install --kubeconfig ~/.kube/147config -y -f -
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
    egressGateways:
    - name: istio-egressgateway
      enabled: true
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: cluster1
      network: network1
      remotePilotAddress: ${DISCOVERY_ADDRESS}
EOF
```

Install istio remote cluster2

```
cat <<EOF | istioctl install  --kubeconfig ~/.kube/159config -y -f -
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
    egressGateways:
    - name: istio-egressgateway
      enabled: true
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: cluster2
      network: network1
      remotePilotAddress: ${DISCOVERY_ADDRESS}
EOF
```

### Version

```prose
root@cluster1-144:~/karmada-teaching/serviceGovernance/istio-host-primary-remote-single-network# istioctl version
client version: 1.17.1
control plane version: 1.17.1
data plane version: none

root@cluster1-144:~/karmada-teaching/serviceGovernance/istio-host-primary-remote-single-network# kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.26.1
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [X] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
