### ISSUE TITLE
fix gateway bind with same port and different protocol

### ISSUE THREAD

**Issue by shonecyx** [istio/istio#43688]
### Bug Description

If there are two gateways with same port and different protocol, one GRPC and one HTTPS but bind to different IP, the GRPC one will fail with below error and no listener gets created for the GRPC gateway, only the HTTPS gateway listener is there:
```
2023-02-28T09:30:28.203738Z	warn	model	TLS server without TLS options gw-ns/gw port:<number:8000 protocol:"GRPC" name:"grpc-8000" > bind:"10.0.0.2" hosts:"*"
```

Reproduce with below spec, omitted the vs/svc spec.

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: gateway-test-1
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - bind: 10.0.0.1
    hosts:
    - '*'
    port:
      name: https-port
      number: 8000
      protocol: HTTPS
    tls:
      mode: SIMPLE
```
---
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: gateway-test-2
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - bind: 10.0.0.2
    hosts:
    - '*'
    port:
      name: grpc-port
      number: 8000
      protocol: GRPC
```
```


### Version

```
istio master branch
```


### Additional Information

_No response_
