### ISSUE TITLE
ERROR: After approving csr istio-sidecar-injector.istio-system, the signed certificate did not appear on the resource

### ISSUE THREAD

**Issue by cmoulliard** [istio/istio#4368]
Script to `/webhook-create-signed-cert.sh` fails when it is executed against openshift 3.9 = kubernetes 1.9

```
cd ~/.istio/istio-0.6.0
 ./install/kubernetes/webhook-create-signed-cert.sh \
    --service istio-sidecar-injector \
    --namespace istio-system \
    --secret sidecar-injector-certs
creating certs in tmpdir /var/folders/56/dtp67r4n1hv79q2hrh_dbwcc0000gn/T/tmp.OMMuwlf2
Generating RSA private key, 2048 bit long modulus
....................................+++
.........................................................................+++
e is 65537 (0x10001)
certificatesigningrequest "istio-sidecar-injector.istio-system" created
NAME                                  AGE       REQUESTOR   CONDITION
istio-sidecar-injector.istio-system   0s        admin       Pending
certificatesigningrequest "istio-sidecar-injector.istio-system" approved
ERROR: After approving csr istio-sidecar-injector.istio-system, the signed certificate did not appear on the resource. Giving up after 10 attempts.
See https://istio.io/docs/setup/kubernetes/sidecar-injection.html for more details on troubleshooting.
```

**Comment by metacosm** [comment]
Yes, I have the same issue.

**Comment by metacosm** [comment]
Per James Falkner:

> you have to enable the kube certificate server api through some changes to your master config:
> So in master-config.yaml you need (near the top):

```yaml
admissionConfig:
  pluginConfig:
    MutatingAdmissionWebhook:
      configuration:
        apiVersion: v1
        disable: false
        kind: DefaultAdmissionConfig
```

> and (somewhere in the middle):

```yaml
kubernetesMasterConfig:
  controllerArguments:
    cluster-signing-cert-file: [ ca.crt ]
    cluster-signing-key-file: [ ca.key ]
```
> Then reboot OpenShift, and it should work...

**Comment by metacosm** [comment]
With minishift, this could be done using:
`minishift openshift config set --patch '<valid json of the wanted changes>'`

**Comment by geoand** [comment]
@metacosm Seems like `minishift openshift config set --patch` is currently broken for Openshift 3.9 running inside Minishift. See [this](https://github.com/minishift/minishift/issues/2156) issue

**Comment by geoand** [comment]
FYI, this should be fixed in `minishift v1.15.0`

**Comment by cmoulliard** [comment]
@geoand Can you submit a PR to mention such requirement within the doc please ?

**Comment by geoand** [comment]
@cmoulliard Yes, I will do that later on in the day

**Comment by joesonw** [comment]
Got the same issue with rke installed k8s cluster.
```
 kube-api:
    image: rancher/hyperkube:v1.10.1
    extra_args:
      admission-control: NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,NodeRestriction,Priority
    extra_binds: []
    service_cluster_ip_range: 10.43.0.0/16
    pod_security_policy: false
```
I believe above configuration would turn on the necessary admission control plugins?
