### ISSUE TITLE
recommended to add telemetry analyzer

### ISSUE THREAD

**Issue by zengyuxing007** [istio/istio#43705]
**Describe the feature request**

The [Telemetry documentation](https://istio.io/latest/docs/reference/config/telemetry/) describes how to use telemetry, but in practice, if you don't read the documentation carefully, it's easy to fall into the pit and users will obsess about what went wrong because they didn't achieve the expected results.

The following two points are easily overlooked by users
- For any namespace, including the root configuration namespace, it is only valid to have a single workload selector-less Telemetry resource.
- For resources with a workload selector, it is only valid to have one resource selecting any given workload.

It is recommended to add a diagnosis

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by zengyuxing007** [comment]
If you want to configure a global Trace and Metrics, you must write them under a Telemetry CR. Instead of
write them under two separate Telemetry CRs like below.

```yaml
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: global-metrics
  namespace: istio-system
spec:
  metrics:
  - providers:
    - name: prometheus
    overrides:
    - match:
        metric: ALL_METRICS
        mode: CLIENT_AND_SERVER
      disabled: false

```

```yaml
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: global-trace
  namespace: istio-system
spec:
  tracing:
  - randomSamplingPercentage: 10.00
    customTags:
      my_new_foo_tag:
        literal:
          value: "foo"
```
If you write them separately, the result is undefined. (The one configured at the earliest time will take effect)
