### ISSUE TITLE
downstream_peer metrics unknown in custom TCP metrics dimension

### ISSUE THREAD

**Issue by dwj300** [istio/istio#43735]
### Bug Description

Following https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/#use-expressions-for-values, we have defined the following extra dimensions for our server-side TCP metrics:
```
"metrics":[
  {
    "dimensions":{
      "dir":"'in'",
      "src_app":"downstream_peer.workload_name"
    },
```
However `src_app` is always "unknown". After increasing the verbosity, we continue to see this error:
```
{"level":"debug","time":"2023-03-03T01:18:56.031961Z","scope":"envoy wasm","msg":"expr_evaluate value error: No value with name \"downstream_peer\" found in Activation"}
{"level":"trace","time":"2023-03-03T01:18:56.032003Z","scope":"envoy wasm","msg":"wasm log stats_inbound tcp_stats_inbound: [external/istio_proxy/extensions/stats/plugin.cc:633]::report() Failed to evaluate expression: <downstream_peer.workload_name>"}
```

What is strange however, is that the "standard" `source_workload` label is set correctly:
```
# TYPE istio_tcp_connections_closed_total counter
istio_tcp_connections_closed_total{reporter="destination",source_workload="mesh-e2e-tcp-client-a-ea1t-us",destination_service="mesh-e2e-server-a-ea1t-us.mesh-e2e-a-ea1t-us.svc.ea1t.us.a",dir="in",src_app="unknown"} 0
# TYPE istio_tcp_connections_opened_total counter
istio_tcp_connections_opened_total{reporter="destination",source_workload="mesh-e2e-tcp-client-a-ea1t-us",destination_service="mesh-e2e-server-a-ea1t-us.mesh-e2e-a-ea1t-us.svc.ea1t.us.a",dir="in",src_app="unknown"} 10
# TYPE istio_tcp_received_bytes_total counter
istio_tcp_received_bytes_total{reporter="destination",source_workload="mesh-e2e-tcp-client-a-ea1t-us",destination_service="mesh-e2e-server-a-ea1t-us.mesh-e2e-a-ea1t-us.svc.ea1t.us.a",dir="in",src_app="unknown"} 11900
# TYPE istio_tcp_sent_bytes_total counter
istio_tcp_sent_bytes_total{reporter="destination",source_workload="mesh-e2e-tcp-client-a-ea1t-us",destination_service="mesh-e2e-server-a-ea1t-us.mesh-e2e-a-ea1t-us.svc.ea1t.us.a",dir="in",src_app="unknown"} 11900
```

### Version

```prose
istio 1.15.5 (though this issue has persisted at least since 1.10).
```

### Additional Information

Seems similar to https://github.com/istio/istio/issues/39614.

**Comment by zirain** [comment]
I test with following IOP, works as expected.
```yaml
# export mesh_id cluster_id in metrics
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: custom-tags
  namespace: istio-system
spec:
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      extraStatTags:
        - src_app
  values:
    global:
      meshID: mesh1
    telemetry:
      enabled: true
      v2:
        enabled: true
        prometheus:
          configOverride:
            outboundSidecar:
              metrics:
                - name: requests_total
                  dimensions:
                    src_app: downstream_peer.workload_name
            inboundSidecar:
              metrics:
                - name: requests_total
                  dimensions:
                    src_app: downstream_peer.workload_name

```
