### ISSUE TITLE
fix gateway with TCP and different bind listeners are not generated correctly 

### ISSUE THREAD

**Issue by shonecyx** [istio/istio#43775]
### Bug Description

If there are two gateways with same TCP and different bind, only one listener will be generated.

2023-03-06T03:00:10.613297Z    info    model    skipping server on gateway tcpgw1 port tcp.8100.TCP: conflict with existing server 8100.TCP
2023-03-06T03:00:10.613324Z    info    model    skipping server on gateway tcpgw2 port tcp.8100.TCP: conflict with existing server 8100.TCP

Reproduce with below spec, omitted the vs/svc spec.

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: gateway-test-1
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - bind: 10.0.0.1
    hosts:
    - '*'
    port:
      name: tcp
      number: 8000
      protocol: TCP

apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: gateway-test-2
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - bind: 10.0.0.2
    hosts:
    - '*'
    port:
      name: tcp
      number: 8000
      protocol: TCP
```

Expected two listeners should be generated: 10.0.0.1_8000 and 10.0.0.2_8000

### Version

```prose
master branch
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
