### ISSUE TITLE
Istio 1.16.1 to 1.17.1 upgrade - Error adding/updating listener(s) virtualInbound - caused by field: "identifier", reason: is required): rules

### ISSUE THREAD

**Issue by chlunde** [istio/istio#43785]
### Bug Description

When upgrading from Istio 1.16 to 1.17.1, we see istiod errors when push authorizationpolicies to sidecars:

```
ADS:LDS: ACK ERROR X.Y Internal:Error adding/updating listener(s) virtualInbound: Proto constraint validation failed (RBACValidationError.Rules: embedded message fail
ed validation | caused by RBACValidationError.Policies[ns[X]-policy[allow-ingress-service]-rule[0]]: embedded message failed validation | caused by PolicyValidationError.Principals[0]: embedded mes
sage failed validation | caused by PrincipalValidationError.AndIds: embedded message failed validation | caused by SetValidationError.Ids[0]: embedded message failed validation | caused by PrincipalValidationError
.OrIds: embedded message failed validation | caused by SetValidationError.Ids[0]: embedded message failed validation | caused by field: "identifier", reason: is required): rules
```

We have noticed that the genereted config is slightly different:

1.16:
```yaml
    - authenticated:              
        principal_name:           
```

1.17:
```yaml
  - filter_state:                   
      key: io.istio.peer_principal  
      string_match:                 
```

This seems to be related to this PR: https://github.com/istio/istio/issues/41585
However, it seems this PR at least attempts to discover the version on the proxy side: https://github.com/istio/istio/pull/42031/files#diff-c11033941b9345c9e0ad343849688d1b60dcfe60b859a8c7414f960914888c5d

Example AuthorizationPolicy:

```yaml
# Deny by default, so open relevant HTTP methods from the ingress gateway
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-ingress-service
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces: ["istio-system"]
            principals:
              - cluster.local/ns/istio-system/sa/service-ingressgateway-service-account
```

Is this a known issue? Does it mean sidecars will not get any new config until updated? Or just no new auth policies? Does this affect all upgrades?

### Version

```prose
$ istioctl version
client version: 1.16.1
control plane version: 1.17.1
data plane version: 1.16.1 (244 proxies), 1.17.1 (94 proxies)
$ kubectl version
Client Version: v1.24.7
Kustomize Version: v4.5.4
Server Version: v1.24.8-eks-ffeb93d
```

**Comment by keeliu07** [comment]
Facing same problem while upgrading from v1.13.4 to v1.16.2...

**Comment by Kyslik** [comment]
@dddddai adding more information from @keeliu07's case:

AP:

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: a-service-blocking
  namespace: istio-system
spec:
  action: DENY
  rules:
  - from:
    - source:
        namespaces:
        - a-namespace
    to:
    - operation:
        notHosts:
        - except-this.except-this.svc.cluster.local
        ports:
        - "8080"
```

And full error/warning:

```
gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_8080: Proto constraint validation failed (RBACValidationError.Rules: embedded message failed validation | caused by RBACValidationError.Policies[ns[istio-system]-policy[a-service-blocking]-rule[0]]: embedded message failed validation | caused by PolicyValidationError.Principals[0]: embedded message failed validation | caused by PrincipalValidationError.AndIds: embedded message failed validation | caused by SetValidationError.Ids[0]: embedded message failed validation | caused by PrincipalValidationError.OrIds: embedded message failed validation | caused by SetValidationError.Ids[0]: embedded message failed validation | caused by field: "identifier", reason: is required): rules {
  action: DENY
  policies {
    key: "ns[istio-system]-policy[a-service-blocking]-rule[0]"
    value {
      permissions {
        and_rules {
          rules {
            not_rule {
              or_rules {
                rules {
                  header {
                    name: ":authority"
                    string_match {
                      exact: "except-this.except-this.svc.cluster.local"
                      ignore_case: true
                    }
                  }
                }
              }
            }
          }
          rules {
            or_rules {
              rules {
                destination_port: 8080
              }
            }
          }
        }
      }
      principals {
        and_ids {
          ids {
            or_ids {
              ids {
                12 {
                  1: "io.istio.peer_principal"
                  2 {
                    5 {
                      2: ".*/ns/a-namespace/.*"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
shadow_rules_stat_prefix: "istio_dry_run_allow_"

0.0.0.0_8443: Proto constraint validation failed (RBACValidationError.Rules: embedded message failed validation | caused by RBACValidationError.Policies[ns[istio-system]-policy[a-service-blocking]-rule[0]]: embedded message failed validation | caused by PolicyValidationError.Principals[0]: embedded message failed validation | caused by PrincipalValidationError.AndIds: embedded message failed validation | caused by SetValidationError.Ids[0]: embedded message failed validation | caused by PrincipalValidationError.OrIds: embedded message failed validation | caused by SetValidationError.Ids[0]: embedded message failed validation | caused by field: "identifier", reason: is required): rules {
  action: DENY
  policies {
    key: "ns[istio-system]-policy[a-service-blocking]-rule[0]"
    value {
      permissions {
        and_rules {
          rules {
            not_rule {
              or_rules {
                rules {
                  header {
                    name: ":authority"
                    string_match {
                      exact: "except-this.except-this.svc.cluster.local"
                      ignore_case: true
                    }
                  }
                }
              }
            }
          }
          rules {
            or_rules {
              rules {
                destination_port: 8080
              }
            }
          }
        }
      }
      principals {
        and_ids {
          ids {
            or_ids {
              ids {
                12 {
                  1: "io.istio.peer_principal"
                  2 {
                    5 {
                      2: ".*/ns/a-namespace/.*"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
shadow_rules_stat_prefix: "istio_dry_run_allow_"
```

And this WARN:

```
Unknown field: type envoy.config.rbac.v3.Principal(envoy.extensions.filters.http.rbac.v3.RBAC::envoy.config.rbac.v3.RBAC::::envoy.config.rbac.v3.Policy::envoy.config.rbac.v3.Principal::envoy.config.rbac.v3.Principal.Set::envoy.config.rbac.v3.Principal::envoy.config.rbac.v3.Principal.Set) with unknown field set {12}
```
