### ISSUE TITLE
listener tag for local rate limit filter

### ISSUE THREAD

**Issue by yingzhuivy** [istio/istio#43792]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
We use envoy filter to add the local rate limit filter to our egress gateway, the metrics generated is in the form of
```
# TYPE envoy_local_rate_limit_air_rate_limited counter
envoy_local_rate_limit_air_rate_limited{} 0
```
without any info on which listener is rate limited, which makes it hard to debug. Is there a way to add the listener info?

the envoy filter looks like:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: rate-limit
  namespace: ns
spec:
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.rbac"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.network.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.network.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: air
              token_bucket:
                max_tokens: 500
                tokens_per_fill: 10
                fill_interval: 1s
```
**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
