### ISSUE TITLE
HTTP 503s when targeting a newly created ready backends

### ISSUE THREAD

**Issue by dprotaso** [istio/istio#43816]
### Bug Description

Knative has a networking conformance test were we probe an ingress endpoint while we mutate a Virtual Service (indirectly through Knative's internal type).

The type of mutations that occur include adding header responses and changing the backend destination. The backend destinations are static and always available.

This test has been flakey in earlier versions (https://github.com/knative-sandbox/net-istio/issues/938) but trying to bump to Istio 1.17.1 seems to consistently fail (https://github.com/knative-sandbox/net-istio/pull/1068)

### Version

```prose
Istio 1.14+ - more flakey with 1.16/1.17
```

**Comment by dprotaso** [comment]
Currently we have Istio 1.17.0 in CI - and you can see the flakey behaviour - https://testgrid.k8s.io/r/knative-own-testgrid/net-istio#continuous&width=20

**Comment by dprotaso** [comment]
Besides access logs are there ways to capture data or debug this further?

This might be similar to a bug we've seen in Contour - https://github.com/projectcontour/contour/issues/2151

**Comment by howardjohn** [comment]
Do we have access logs? That would eb the most useful to figure out what type of error we are talking about. Knowing what type of mutation would help as well. I couldn't reproduce just movbing a VS from backend1 to backend2

**Comment by dprotaso** [comment]
Test is here

https://github.com/knative/networking/blob/c692e9e6afe17fdd870e19fd04a869585296e315/test/conformance/ingress/update.go#L35

We actually stress it by running it 10x in parallel

https://github.com/knative-sandbox/net-istio/blob/11ffd8009173b43a2401a37245dc281806b6273c/test/conformance/ingress_test.go#L32

**Comment by howardjohn** [comment]
I tried to reproduce but it just hanged forever, this is after installing istio + knative and running `go test -count=1 -p 1 -tags=e2e ./test/conformance -run TestIngressConformance -v`.

**Comment by dprotaso** [comment]
> I tried to reproduce but it just hanged forever, this is after installing istio + knative and running go test -count=1 -p 1 -tags=e2e ./test/conformance -run TestIngressConformance -v.

There are some prereqs - install `ko` then

```sh
# Upload test images
$ ./test/upload-test-images.sh

# install our Istio setup
$ kubectl apply -f third_party/istio-latest/istio-ci-no-mesh/istio.yaml

# Install test resources
$ ko apply -f test/config 

# Install knative net-istio plugin
$ ko apply -f config/

# Run tests
$ gotestsum -f testname --  -tags e2e -timeout 30m --parallel 12 -run TestIngressConformance ./test/conformance --enable-beta --enable-alpha
```

### Failed run with Telemetry

I have a failed run. You can access [prow logs](https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative-sandbox_net-istio/1080/integration-tests_net-istio_main/1634252237339365376). Or it might be easier to access [Cluster Logs via GCP LogViewer](https://console.cloud.google.com/logs/query;query=resource.labels.cluster_name%3D%22e2e-cls-zpyvoajp%22;timeRange=2023-03-10T17:48:00.000Z%2F2023-03-10T18:39:00.000Z;cursorTimestamp=2023-03-10T18:28:55.470682659Z?referrer=search&project=knative-boskos-90)

You can access those logs by being a member of the google group https://groups.google.com/g/knative-dev


Here's a [query](https://console.cloud.google.com/logs/query;query=resource.labels.cluster_name%3D%22e2e-cls-zpyvoajp%22%0A-resource.labels.container_name%3D%22foo%22%0A%22ingress-conformance-0-update-tnemuddb%22%0A;timeRange=2023-03-10T18:06:30.000Z%2F2023-03-10T18:13:30.000Z;cursorTimestamp=2023-03-10T18:11:19.730387Z;resultsSearch=503?referrer=search&project=knative-boskos-90) that shows a pod becoming ready and then Istio serving 503s

You can see the Endpoint is ready around 2023-03-10 13:11:20.742 EST, insert ID(f53228af-5116-4f45-852a-13eaa9d68320)

> [2023-03-10T18:11:20.516Z] "GET / HTTP/1.1" 503 UH no_healthy_upstream - "-" 0 19 0 - "10.120.2.1" "knative.dev/TestIngressConformance/0/update/ingress-conformance-0-update-lmjbdirz" "31e6033c-8ad8-4989-9996-544bc574738f" "ingress-conformance-0-update-yaljemdf.example.com" "-" outbound|81||ingress-conformance-0-update-tnemuddb.serving-tests.svc.cluster.local - 10.120.2.9:8080 10.120.2.1:55564 - -

**Comment by dprotaso** [comment]
Here's a summary of the customizations we do

from: https://github.com/knative-sandbox/net-istio/blob/main/third_party/istio-latest/istio-ci-no-mesh.yaml

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    pilot:
      autoscaleMin: 3
      autoscaleMax: 10
      cpu:
        targetAverageUtilization: 60
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: false

  meshConfig:
    defaultConfig:
      terminationDrainDuration: "20s"

  components:
    ingressGateways:
      - name: istio-ingressgateway
        k8s:
          replicaCount: 3
          resources:
            limits:
              cpu: 3000m
              memory: 2048Mi
            requests:
              cpu: 1000m
              memory: 1024Mi
```
