### ISSUE TITLE
Prometheus is unable to fire alerts using istio: HTTP status 503

### ISSUE THREAD

**Issue by kirankh7** [istio/istio#43829]
### Bug Description

We are using Istio mesh to connect Prometheus to Alertmanager. Whenever an Alertmanager pod gets restarted, we get the following error(up on firing new alerts to alertmanager). If we restart the Prometheus server error goes away, and able to establish a new connection to Alertmanager. Is this a way we can fix this issue using istio? 

```
ts=2023-03-07T21:34:40.312Z caller=scrape.go:1351 level=debug component="scrape manager" scrape_pool=alertmanager target=http://am-0.monitoring.svc.cluster.local:9093/metrics msg="Scrape failed" err="server returned HTTP status 503 Service Unavailable"
```

### Version

```prose
Prometheus Version: 2.42.0
Alertmanager Version: 0.25.0
Istio Version: v1.17
```

### Additional Information

**port config alertmanager**(headless service)
```
spec:
  clusterIP: None
  ports:
    - name: tcp-client # we changed this from http- to tcp- because of this issue 
      port: 9093
      protocol: TCP
      targetPort: 9093
    - name: tcp-client-meshpeer
      port: 6783
      protocol: TCP
      targetPort: 6783
    - name: udp-client-meshpeer
      port: 6783
      protocol: UDP
      targetPort: 6783
```

**alerting configuration:**
```
    alerting:
      alert_relabel_configs:
      - action: labeldrop
        regex: replica
        replacement: $1
        separator: ;
      alertmanagers:
        - static_configs:
          - targets:
            - am-0.monitoring.svc.cluster.local:9093
            - am-1.monitoring.svc.cluster.local:9093
            - am-2.monitoring.svc.cluster.local:9093
```
