### ISSUE TITLE
Host header created by a custom AuthorizationPolicy is incorrect

### ISSUE THREAD

**Issue by spadger** [istio/istio#43836]
### Bug Description

Context:
* An ingressgateway exists at `ingress.com`
* An authorization endpoint exists at `auther.com`, with DNS 1.2.3.4

```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  namespace: istio-system
  name: inbound-secret-auth
spec:
  selector:
    matchLabels:
      istio: ingress-gw
  action: CUSTOM
  provider:
    name: some-authz
  rules:
    - to:
        - operation:
            paths:
              - "/secret/*"
```

The relevant part of istio's values file:

```yaml
extensionProviders:
  - name: "some-authz"
    envoyExtAuthzHttp:
      service: "auther.com"
      port: "8080"
      pathPrefix: "/check?url="
      includeRequestHeadersInCheck:
        - "x-*"
        ...
      headersToUpstreamOnAllow:
        - "sapi-*"
        ....
      includeRequestBodyInCheck:
        maxRequestBytes: 1048576
        allowPartialMessage: true
        packAsBytes: true
```

When I make a call to `ingress.com/secret/stuff`, the IngressGateway does create an HTTP call to the correct destination IP (1.2.3.4), but the `host` header is for `ingress.com` rather than `auther.com`, which would not play well with any intermediate nginx instances...

### Solution (maybe)
Envoy specifically disallows host-header mutation, but it does allow this check to be [disabled](https://github.com/envoyproxy/envoy/blob/1816b675dbd3e6ae10ac01778f5b9aca6e54f71d/api/envoy/config/common/mutation_rules/v3/mutation_rules.proto#L48-L51). I guess Istio could surface this fact, at least in the docs so that people could create an `EnvoyFilter`

### Version

```prose
$ istioctl version
client version: 1.17.1
control plane version: 1.17.1
data plane version: 1.17.0 (5 proxies)

$ kubectl version --short
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.26.1

$ helm version --short
v3.11.1+g293b50c
```
