### ISSUE TITLE
sidecar-injector.istio.io: failed to call webhook

### ISSUE THREAD

**Issue by vyom-soft** [istio/istio#43882]
### Bug Description

Pods fails to deploy on node restart with istio side-car injector
After Installing Istio via Helm chart. And enabling the istio sidecar injection on the namespace .
I am seeing the following error in the pod
```
status:
  conditions:
    - lastTransitionTime: '2023-03-15T07:53:56Z'
      message: >-
        Internal error occurred: failed calling webhook
        "namespace.sidecar-injector.istio.io": failed to call webhook: Post
        "https://istiod.istio-system.svc:443/inject?timeout=10s": context
        deadline exceeded
      reason: FailedCreate
      status: 'True'
      type: ReplicaFailure
  observedGeneration: 1
  replicas: 0
```

### Version

```prose
Istio version 1.17.1
Kubernetes 1.24.6 with Kubespray
with MetalLB
No Firewall in the N/W.
hostNetwork=false  (also mentioned in istio document the it should not be set)
```

### Additional Information

In validatingwebhookconfigurations istiod-default-validator -n kube-system
The faiulrePolicy=Ignore
