### ISSUE TITLE
Istio metrics override doesn't work for overlapping tag names

### ISSUE THREAD

**Issue by wiegandf** [istio/istio#43949]
### Bug Description

We are using the custom metrics feature in Istio and configure it via the Telemetry resource. It works fine for 

```yaml
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
spec:
  metrics:
    - overrides:
        - tagOverrides:
            tenant:
              operation: UPSERT
              value: request.headers["test-tenant"]
      providers:
        - name: prometheus
```

It doesn't work (meaning istio_requests_total doesn't hold the custom metrics) for 

```yaml
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
spec:
  metrics:
    - overrides:
        - tagOverrides:
            cc_tenant:
              operation: UPSERT
              value: request.headers["test-cloud-tenant"]
            tenant:
              operation: UPSERT
              value: request.headers["test-tenant"]
      providers:
        - name: prometheus
```

Interestingly, it works for (pay attention to the first tagOverride name (tenant_cc instead of cc_tenant).

```yaml
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
spec:
  metrics:
    - overrides:
        - tagOverrides:
            tenant_cc:
              operation: UPSERT
              value: request.headers["test-cloud-tenant"]
            tenant:
              operation: UPSERT
              value: request.headers["test-tenant"]
      providers:
        - name: prometheus
```

The extraStatTags are configured via IstioOperator: 
```yaml
  meshConfig:
    defaultConfig:
      extraStatTags:
        - tenant
        - cc_tenant
```

### Version

```prose
$ istioctl version
client version: 1.16.1
control plane version: 1.16.1
data plane version: 1.16.1 (16 proxies)

$ kubectl version --short
Client Version: v1.25.5
Kustomize Version: v4.5.7
Server Version: v1.24.10
```

### Additional Information

Curling some istio pods that would produce those metrics shows an interesting thing:

```plain
curl -v <istio_host> -H "test-tenant: test123" -H "test-cloud-tenant: helloworld"
```
produces
```plain
tenant___test123___istio_requests_total{response_code="200",...,tenant="helloworld",cc_tenant="helloworld"} 1
```

So tenant gets the value of cc_tenant and furthermore the problem occurs that no istio_requests_total metric is produced.
