### ISSUE TITLE
istioctl analyze fails with runtime error for EnvoyFilter for ISTIO 1.15.0 onwards

### ISSUE THREAD

**Issue by anand-bidwalkar** [istio/istio#43957]
### Bug Description

Hi Team,

While upgrading our ISTIO version from 1.14.5 to 1.16.3 version we found a bug/issue on running istioctl analyze command for an EnvoyFilter. The below error is only coming from ISTIO 1.15.0 onwards, 1.14.6 doesn't show this error. On further investigating we found adding a FilterMatch to FilterChainMatch resolves the issue. But as per the documentation on ISTIO website FilterMatch is not a required field. Below is the envoy filter and error for reference. Could you please help us understand the issue? 

https://istio.io/v1.14/docs/reference/config/networking/envoy-filter/#EnvoyFilter-ListenerMatch-FilterChainMatch

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: disable-alpn-h2
  namespace: egress
spec:
  configPatches:
  - applyTo: FILTER_CHAIN
    match:
      listener:
        filterChain:
          sni: gcp-macro.ops.service.dev
    patch:
      operation: MERGE
      value:
        transportSocket:
          name: envoy.transport_sockets.tls
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
            commonTlsContext:
              alpnProtocols:
              - http/1.1
              tlsCertificateSdsSecretConfigs:
              - name: kubernetes://wildcard-cert
                sdsConfig:
                  ads: {}
                  resourceApiVersion: V3
  workloadSelector:
    labels:
      istio: egressgateway
```

Error
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x3447503]

goroutine 1 [running]:
istio.io/istio/pkg/config/analysis/analyzers/envoyfilter.(*EnvoyPatchAnalyzer).analyzeEnvoyFilterPatch(0xc0002e5830, 0xc003771ef0, {0x461fd20, 0xc0013dc8c0?}, {0x668c350?, 0xc00052cfe0?, 0x0?})
	istio.io/istio/pkg/config/analysis/analyzers/envoyfilter/envoyfilter.go:108 +0x223
istio.io/istio/pkg/config/analysis/analyzers/envoyfilter.(*EnvoyPatchAnalyzer).Analyze.func1(0x3fcc7cd?)
	istio.io/istio/pkg/config/analysis/analyzers/envoyfilter/envoyfilter.go:51 +0x3f
istio.io/istio/pkg/config/analysis/local.(*istiodContext).ForEach(0xc0013dc8c0, {0x400a151, 0x26}, 0xc002e5cb10)
	istio.io/istio/pkg/config/analysis/local/context.go:146 +0x694
istio.io/istio/pkg/config/analysis/analyzers/envoyfilter.(*EnvoyPatchAnalyzer).Analyze(0x668c350, {0x461fd20?, 0xc0013dc8c0})
	istio.io/istio/pkg/config/analysis/analyzers/envoyfilter/envoyfilter.go:50 +0x11d
istio.io/istio/pkg/config/analysis.(*CombinedAnalyzer).Analyze(0xc000f07b30, {0x461fd20, 0xc0013dc8c0})
	istio.io/istio/pkg/config/analysis/analyzer.go:60 +0x1b4
istio.io/istio/pkg/config/analysis/local.(*IstiodAnalyzer).ReAnalyze(0xc000f172b0, 0xc000117140)
	istio.io/istio/pkg/config/analysis/local/istiod_analyze.go:136 +0x2fd
istio.io/istio/pkg/config/analysis/local.(*IstiodAnalyzer).Analyze(0x1?, 0x3fab919?)
	istio.io/istio/pkg/config/analysis/local/istiod_analyze.go:155 +0xdb
istio.io/istio/istioctl/cmd.Analyze.func1(0xc000dd1b80?, {0xc000d18e30, 0x1, 0x1})
	istio.io/istio/istioctl/cmd/analyze.go:222 +0x795
github.com/spf13/cobra.(*Command).execute(0xc000dd1b80, {0xc000d18e00, 0x1, 0x1})
	github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc000d5c780)
	github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
	istio.io/istio/istioctl/cmd/istioctl/main.go:39 +0xdc
```

### Version

```prose
client version: 1.16.3
control plane version: 1.16.3
data plane version: 1.16.3

kubectl version --short
Client Version: v1.23.9
Server Version: v1.23.14-gke.1800
```
