### ISSUE TITLE
Istio envoy local rate limiting doesn't work

### ISSUE THREAD

**Issue by rlleshi** [istio/istio#43953]
I am applying a local rate limit like so:

``` 
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: detection-ratelimit
  namespace: istio-system
spec:
  workloadSelector:
  # select the workload to which the EnvoyFilter will be applied
    labels:
      app: detection-pose
      version: v1
      namespace: seldon-system
  configPatches:
    - applyTo: HTTP_FILTER  # apply the patch to the HTTP filter chain
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: 'envoy.filters.network.http_connection_manager'
      patch:
      # the actual configuration changes go here
        operation: INSERT_BEFORE  # insert rate limit at the top of the HTTP filter list
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            '@type': type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter
              enable_x_ratelimit_headers: DRAFT_VERSION_03
              token_bucket:
                max_tokens: 10
                tokens_per_fill: 8
                fill_interval: 60s
              filter_enabled:
                runtime_key: local_rate_limit_enabled
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              filter_enforced:
                runtime_key: local_rate_limit_enforced
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              response_headers_to_add:
                - append_action: APPEND_IF_EXISTS_OR_ADD
                  header:
                    key: x-rate-limited
                    value: TOO_MANY_REQUESTS
              status:
                code: BadRequest
```

The filter is not working. Meaning that I can do > 10 requests per minute. Istio injection for the namespace is enabled. Version:

```
client version: 1.13.4
control plane version: 1.17.0
data plane version: 1.17.0 (5 proxies)
```

I am not so familiar with istio. Any pointers would be highly appreciated!
