### ISSUE TITLE
Http Header based consistentHash load balancing is not working with Grpc

### ISSUE THREAD

**Issue by QiyuanHU** [istio/istio#43974]
Hello I was follwing:
https://istio.io/latest/docs/reference/config/networking/destination-rule/#LoadBalancerSettings

For my service to service call, I noticed the call with same header did not get routed into the same pod always. 

Here is my destination rule:
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: "math-resource-service"
  labels:
    app.kubernetes.io/name: "math-resource-service"
    app.kubernetes.io/part-of: "math-resource"
    app.kubernetes.io/managed-by: "Tiller"
  namespace: "default"
spec:
  host: "math-resource-service.default.svc.cluster.local"
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: "profile-id-header"
    outlierDetection:
      consecutiveErrors: 5
  subsets:
    - name: "v1"
      labels:
        version: "1"
```

my virtual service:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "math-resource-service-internal"
  labels:
    app.kubernetes.io/name: "math-resource-service"
    app.kubernetes.io/part-of: "math-resource"
    app.kubernetes.io/managed-by: "Tiller"
  namespace: "default"
spec:
  gateways:
    - "default/gateway"
  hosts:
    - "*"
  http:
    - match:
      - uri:
          prefix: "/com.math"
      route:
        - destination:
            host: "math-resource-service.default.svc.cluster.local"
            subset: "v1"
            port:
              number: 7020
```

I can see the istio proxy log that my grpc call do have the header **header-routing:1335278963**:
`accessLogFormat: "{\"header-routing\":\"%REQ(profile-id-header)%\"`

`[istio-proxy] {"upstream_local_address":"127.0.0.1:50702","response_flags":"-","downstream_local_address":"172.17.0.15:7020","method":"POST","duration":979,"bytes_sent":73,"connection_id":266,"protocol":"HTTP/2","response_code_details":"via_upstream","start_time":"2023-03-16T01:42:38.538Z","route_name":"default","downstream_remote_address":"172.17.0.14:59010","upstream_service_time":"784","request_id":"53f9e49b-478e-4675-8663-b12c7536010f","x_forwarded_for":null,"path":"/com.math.v2.MathService/PushEvent","connection_termination_details":null,"upstream_cluster":"inbound|7020||","bytes_received":52,"user_agent":"grpc-java-netty/1.35.1","header-trace":"6bab0fed528295d89f8a7c8a57dbd8ab","authority":"math-resource-service:7020","trace_id":"6bab0fed528295d89f8a7c8a57dbd8ab","response_code":200,"header-routing":"1335278963","upstream_host":"127.0.0.1:7020","upstream_transport_failure_reason":null,"requested_server_name":null}` 

I checked the envoy config dump and it indeed has the header based routing config:

`{
        "name": "math-resource-service.default.svc.cluster.local:7020",
        "domains": [
         "math-resource-service.default.svc.cluster.local",
         "math-resource-service.default.svc.cluster.local:7020",
         "math-resource-service",
         "math-resource-service:7020",
         "math-resource-service.default.svc",
         "math-resource-service.default.svc:7020",
         "math-resource-service.default",
         "math-resource-service.default:7020",
         "10.103.97.7",
         "10.103.97.7:7020"
        ],
        "routes": [
         {
          "match": {
           "prefix": "/"
          },
          "route": {
           "cluster": "outbound|7020||math-resource-service.default.svc.cluster.local",
           "timeout": "0s",
           "retry_policy": {
            "retry_on": "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes",
            "num_retries": 2,
            "retry_host_predicate": [
             {
              "name": "envoy.retry_host_predicates.previous_hosts",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.retry.host.previous_hosts.v3.PreviousHostsPredicate"
              }
             }
            ],
            "host_selection_retry_max_attempts": "5",
            "retriable_status_codes": [
             503
            ]
           },
           "hash_policy": [
            {
             "header": {
              "header_name": "profile-id-header"
             }
            }
           ],
           "max_stream_duration": {
            "max_stream_duration": "0s",
            "grpc_timeout_header_max": "0s"
           }
          },
          "decorator": {
           "operation": "math-resource-service.default.svc.cluster.local:7020/*"
          },
          "name": "default"
         }
        ],
        "include_request_attempt_count": true
       }
      ],
      "validate_clusters": false
     },
     "last_updated": "2023-03-16T01:34:38.764Z"
    }`

Can you help me? Anything I am missing? Thanks for your help!
