### ISSUE TITLE
Connections drop when using TCP proxying because of ephemeral ports exhaustion

### ISSUE THREAD

**Issue by johnbuluba** [istio/istio#44008]
### Bug Description

We have a service that uses raw TCP protocol and accepts a lot of short-lived connections.
While scaling up the service consumers caused an increase in the number of connections and, at some point, connections started dropping without reason.

Further inspecting the sidecar we saw that: 
1. The `upstream_cx_connect_fail` and `upstream_cx_connect_attempts_exceeded` stats for the inbound cluster increased over time.
1. Enabled the debug logs for the sidecar and saw entries like the following: 
     ```
     debug   envoy pool  creating a new connection                        
     debug   envoy misc  failed to bind to 127.0.0.6:0: Address already in use 
     ```

This hinted that envoy could not bind to `127.0.0.6` because the ephemeral ports were exhausted. We further verified that this was indeed the issue with the following command:
```
istio-proxy@pod-name:/$ netstat -an | grep -o -E '127.0.0.6:[0-9]+' | sort | uniq | wc -l
28232
```
This showed us that 28232 ports were in use, which is the default Linux ephemeral port limit. Also, note that most of the ports were in the `TIME_WAIT` state.

### Reproduce

You can reproduce the above issue with the following example: 

<details>
  <summary>Example </summary>

  ```yaml
          
  apiVersion: v1
  kind: Service
  metadata:
    name: helloworld
    labels:
      app: helloworld
      service: helloworld
  spec:
    ports:
    - port: 80
      name: tcp
    selector:
      app: helloworld
  ---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: helloworld
    labels:
      app: helloworld
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: helloworld
    template:
      metadata:
        labels:
          app: helloworld
          sidecar.istio.io/inject: "true"
        annotations:
          sidecar.istio.io/interceptionMode: "REDIRECT"
          proxy.istio.io/config: |-
            proxyStatsMatcher:
              inclusionRegexps:
              - ".*upstream_cx_.*"
              inclusionSuffixes:
              - "upstream_rq_timeout"
      spec:
        containers:
        - name: helloworld
          image: nginxdemos/hello:latest
          resources:
            requests:
              cpu: "1000m"
          imagePullPolicy: IfNotPresent #Always
          ports:
          - containerPort: 80
  
  ---
  apiVersion: security.istio.io/v1beta1
  kind: AuthorizationPolicy
  metadata:
    name: helloworld
  spec:
    action: ALLOW
    rules:
    - {}
    selector:
      matchLabels:
        app: helloworld
  ---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: stress-script
  data:
    test.sh: |
      #! /bin/bash -e
      
      apt-get update && apt install -y curl
      curl -o /usr/local/bin/hey https://hey-release.s3.us-east-2.amazonaws.com/hey_linux_amd64
      chmod +x /usr/local/bin/hey
                  
      while true
      do
        hey -n 200 -c 100 -q 2 http://helloworld.default.svc
        sleep 1
      done  
  
  ---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: stress
  spec:
    replicas: 28
    selector:
      matchLabels:
        app: stress
    template:
      metadata:
        annotations:
          proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true}'
        labels:
          app: stress
          sidecar.istio.io/inject: "true"
      spec:
        volumes:
        - configMap:
            defaultMode: 420
            name: stress-script
          name: scripts
        containers:
        - name: main
          image: ubuntu:jammy
          command:
          - bash
          - /scripts/test.sh
          resources:
            requests:
              cpu: 1m
          volumeMounts:
            - mountPath: /scripts
              name: scripts


  ```
</details>

Note that even though we are using HTTP in this example, the port name is TCP which forces Istio to use raw TCP proxying.
As a side note when using HTTP proxying this issue doesn't come up.

### Workaround

While searching for a solution, we bumped into the `TPROXY` interception mode. When using `TPROXY` we noticed that no connections were dropping and everything worked as expected.

So adding the following annotation fixes the issue: 
```
sidecar.istio.io/interceptionMode: "TPROXY"
```

### Questions

1. Are there any other alternatives to solve this issue without using `TPROXY`?
1. Are there any drawbacks to using the `TPROXY` interception mode? If not, why is this not the default interception mode?

### Version

```prose
$ istioctl version
client version: 1.14.1
control plane version: 1.14
data plane version: 1.14.3 (61 proxies)
$ kubectl version --short
Client Version: v1.26.3
Kustomize Version: v4.5.7
Server Version: v1.23.16-eks-48e63af
```
