### ISSUE TITLE
Preventing traffic drop during revisioned upgrade

### ISSUE THREAD

**Issue by chauhanshubham** [istio/istio#44047]
**Preventing traffic drop during revisioned upgrades**

I have a traditional revisioned setup with two revisioned control planes provisioned, with `stable` and `canary`.
I intend to upgrade my bookinfo application from revision `stable` to newer revision `canary`.

I have the following GW and VS in place (spec truncated for brevity)
```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  labels:
    istio.io/rev: stable
  name: bookinfo-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
```

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    istio.io/rev: stable
  name: bookinfo
  namespace: default
spec:
  gateways:
  - bookinfo-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        exact: /productpage
...
    route:
    - destination:
        host: productpage
        port:
          number: 9080
```

When setting up the `canary` revision via the following command
```
istioctl install  --set revision=canary
```

the gateway proxies are upgraded in-place automatically to the `canary` revision as expected, and the gateway proxy connects to `istiod-canary`.

Since the GW and VS are still pointing to the previous revision `stable`, `istiod-canary` cannot provide details about these configs to the gateway proxy. This leads to traffic drop
```bash
root@http-client:/# curl -s -I -HHost:httpbin.example.com "http://172.18.254.100:80/productpage"
HTTP/1.1 503 Service Unavailable
content-length: 145
content-type: text/plain
date: Tue, 21 Mar 2023 14:00:53 GMT
server: envoy
```

The only workaround would be to 
Duplicate all istio configs and point that to the intended upgraded revision `canary`, in this case the GW and VS.
This would mean double the number of istio configs.

**Describe alternatives you've considered**
As mentioned earlier the only workaround is to have a copy of the istio configurations for all revisions in the setup. This leads to duplicates and IMHO is not a great UX.

Could we consider watching for and filter out istio configs, that not just matches the istiod revision, but matches multiple revisions at once?
i.e. in the scenario above, the pilot crd-client watcher in `istiod-canary` is able to watch for and process istio configs with revision `stable` and `canary` both.
If `istiod-canary` propagates the `stable` information to `canary` proxies, the traffic would still work. Users can then update the existing GW and VS objects to point to revision `canary`. This should not lead to any traffic drop. The rollback should also be seamless.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
