### ISSUE TITLE
Istio AuthorizationPolicy allow requires defining a port number if HTTP Host header includes a port number

### ISSUE THREAD

**Issue by pre** [istio/istio#44080]
### Bug Description

We have a third party service whose source code we have no control over. Some HTTP requests made by this service to our cluster with Istio worked and some were denied with RBAC "policy matched none". The service is using mTLS and has some heavy Istio configuration. Maybe this is not relevant but gives some context about the pain on trying to find the problem.

We now have a cluster wide `AuthorizationPolicy` for allow with two entries for each host:

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow
  namespace: istio-system
spec:
  action: ALLOW
  rules:
    - to:
      - operation:
          hosts:
          - "*.ourdomain.com"     # <-- Earlier we had only this one, a host without a port
          - "*.ourdomain.com:443" # <-- This issue is about having to also define the host with the port number
  selector:
    matchLabels:
      istio: istio-ingressgateway
```

When a HTTP request is made and the `Host:` header of this request includes the port number, Istio will fail the request. We are able to replicate this issue with Postman. Issue cannot be reproduced by `curl` because curl removes the port number from the HTTP request's `Host` header. 

For example: `Host: lolcat.ourdomain.com:443` where normally the HTTP request would have `Host: lolcat.ourdomain.com`. 

It seems each hostname needs to be duplicated in the allow list with one including the port number. 
Which is surprising and it is not really documented anywhere. 

Is it expected behaviour from Istio that one needs to consider port numbers in the `hosts` field of an `AuthorizationPolicy`? 

* If yes, let's document the behaviour. 
* If not, let's fix this.
* If we're not going to anything about this - here's at least a Github issue for fellow developers in the future.

### Version

```prose
$ istioctl version
client version: 1.16.2
control plane version: 1.16.2
data plane version: 1.16.2 (66 proxies)
```

### Additional Information

```
Target cluster context: redacted

Running with the following config:

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2023-03-23 18:04:22.388775 +0200 EET



Cluster endpoint: https://redacted
CLI version:
version.BuildInfo{Version:"1.16.2", GitRevision:"3e5fd5a1d70ea535ad5d18fb66a76c5cce905876-dirty", GolangVersion:"go1.19.5", BuildStatus:"Clean", GitTag:"1.16.2"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.16.2", GitRevision:"3e5fd5a1d70ea535ad5d18fb66a76c5cce905876", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.16.2"},
    },
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.16.2", GitRevision:"3e5fd5a1d70ea535ad5d18fb66a76c5cce905876", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.16.2"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.16.2}


Fetching proxy logs for the following containers:
[.. redacted .. ]
```

**Comment by SpecialYang** [comment]
Maybe you can use the env `ISTIO_GATEWAY_STRIP_HOST_PORT` to force data plane to remove port from host before authz filter processing.

The env `ISTIO_GATEWAY_STRIP_HOST_PORT` cannot effect the sidecar proxy. But your case is only gateway and I think you can use it.

**Comment by hzxuzhonghu** [comment]
https://istio.io/latest/docs/ops/best-practices/security/#writing-host-match-policies
You can specify a wildcard suffix
```
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: ingress-host
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  action: DENY
  rules:
  - to:
    - operation:
        hosts: ["example.com", "example.com:*"]

```
