### ISSUE TITLE
Gateway adding mixed content elements (http and https)

### ISSUE THREAD

**Issue by u0000000021** [istio/istio#44119]
### Bug Description

The browser is getting a `mixed-content` warning which means that there are both `secured` and `unsecured` elements being served up on a page that should be completely encrypted where any page using an HTTPS address must have all of the content within coming from a secured source.

The project uses a custom built Docker image and was tested on a single container/VM, loaded to a kubernetes cluster. The same image was tested on the pod level (using port-forward HTTP and HTTPS), at the service level (using port-forward HTTP and HTTPS) and at browser level (through istio Gateway/VirtualService level). 
HTTP is displaying the page correctly and HTTPS is not - adding the mixed content warning - which prevents the page to be displayed correctly (jQuery not loaded for example)

![image](https://user-images.githubusercontent.com/78825665/227802145-4a44d413-cf1e-4272-b476-3a18438f4e2e.png)

The below are the debug steps taken before submitting a bug report:
- [ ] Built an image from a Dockerfile, pushed the image to `ghcr.io` registry
- [ ] Tested the image using `docker-compose` on a VM, both using `HTTP` and `HTTPS` :heavy_check_mark: No mixed content issue
- [ ] Loaded the project in a kube cluster, tested at pod level (HTTPS through port-forward)  :heavy_check_mark: No mixed content issue
- [ ] tested at service level (HTTPS through port-forward)  :heavy_check_mark: No mixed content issue
- [ ] tested at browser level (through istio gateway/virtual service) :x: Mixed content issue

I also tried various hacks, like using the Apache Rewrite Engine (mod_rewrite) to force all `http` scheme to `https`, another attempt with the  `EnvoyFilter` using `LUA` scripts, ...

:bulb: The cluster is hosted on AWS, through the `KOPS` open source kube orchestration and is already hosting a 'Moodle' service without `mixed-content` issues.

:scroll: istio manifests used

* Gateway
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: qa-mahara-ufo-ca-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - qa.mahara.ufo.ca
    tls:
      httpsRedirect: true # Remove when issuing certificate
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: qa-mahara-ufo-ca-tls
    hosts:
    - qa.mahara.ufo.ca
```    
* VirtualService
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mahara-service
spec:
  hosts:
  - qa.mahara.ufo.ca
  gateways:
  - qa-mahara-ufo-ca-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: mahara-service.qa.svc.cluster.local
        port:
          number: 80
  tls:
  - match:
    - port: 443
      sniHosts:
      - qa.mahara.ufo.ca
    route:
    - destination:
        host: mahara-service.qa.svc.cluster.local
        port:
          number: 443
```
Any leads will be greatly appreciated

### Version

```prose
$ istioctl version
client version: 1.15.0
control plane version: 1.15.0
data plane version: 1.15.0 (6 proxies)
```

### Additional Information

- [ ] IstioCTL bug-report

```
istioctl bug-report
```
> Outputs :
<pre>
Target cluster context: cluster.mywebsite.ca

Running with the following config: 

istio-namespace: istio-system
full-secrets: false
timeout (mins): 30
include: {  }
exclude: { Namespaces: kube-node-lease,kube-public,kube-system,local-path-storage }
end-time: 2023-03-26 15:50:46.721423 -0400 EDT

Cluster endpoint: https://api.cluster.mywebsite.ca
CLI version:
version.BuildInfo{Version:"1.15.0", GitRevision:"e3364ab424b70ca8ee1ca76cb0b3afb73476aaac-dirty", GolangVersion:"go1.18.5", BuildStatus:"Clean", GitTag:"1.15.0"}

The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
    {
        Component: "pilot",
        Info:      version.BuildInfo{Version:"1.15.0", GitRevision:"e3364ab424b70ca8ee1ca76cb0b3afb73476aaac", GolangVersion:"", BuildStatus:"Clean", GitTag:"1.15.0"},
    },
}

The following proxy revisions/versions were found in the cluster:
Revision default: Versions {1.15.0}

Fetching proxy logs for the following containers:

cert-manager/cert-manager-cainjector/cert-manager-cainjector-84f755b45c-2579m/cert-manager
cert-manager/cert-manager-webhook/cert-manager-webhook-6ff87f58f8-f7prv/cert-manager
cert-manager/cert-manager/cert-manager-896979b44-mmvsj/cert-manager
default//dev-moodle-cron-27997668-zctv4/dev-moodle-cron
default//dev-moodle-cron-27997669-l4ftr/dev-moodle-cron
default//dev-moodle-cron-27997670-pqpdz/dev-moodle-cron
dev//moodle-mariadb-0/mariadb
dev/moodle/moodle-5d6d5fb7bd-xjl7b/moodle
istio-system/istio-ingressgateway/istio-ingressgateway-69857d7dc4-2pwzw/istio-proxy
istio-system/istiod/istiod-5559b6cb99-zwq4b/discovery
qa//mahara-elastic-0/istio-proxy
qa//mahara-elastic-0/mahara-elastic
qa//mahara-postgres-0/istio-proxy
qa//mahara-postgres-0/mahara-postgres
qa//mahara-redis-master-0/istio-proxy
qa//mahara-redis-master-0/redis
qa/mahara-admin/mahara-admin-549d76b7c9-jm4rs/istio-proxy
qa/mahara-admin/mahara-admin-549d76b7c9-jm4rs/mahara-admin
qa/mahara/mahara-d897cc898-jf28m/istio-proxy
qa/mahara/mahara-d897cc898-jf28m/mahara

Fetching Istio control plane information from cluster.

Running istio analyze on all namespaces and report as below:
Analysis Report:
Warning [IST0117] (Deployment qa/mahara-admin) No service associated with this deployment. Service mesh deployments must be associated with a service.
Info [IST0102] (Namespace cert-manager) The namespace is not enabled for Istio injection. Run 'kubectl label namespace cert-manager istio-injection=enabled' to enable it, or 'kubectl label namespace cert-manager istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace default) The namespace is not enabled for Istio injection. Run 'kubectl label namespace default istio-injection=enabled' to enable it, or 'kubectl label namespace default istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace dev) The namespace is not enabled for Istio injection. Run 'kubectl label namespace dev istio-injection=enabled' to enable it, or 'kubectl label namespace dev istio-injection=disabled' to explicitly mark it as not needing injection.
Creating an archive at /Users/u0000000021/Developer/config-grappe-superieure/preprod/qa/mahara/install/bug-report.tar.gz.
Cleaning up temporary files in /var/folders/1_/n9m1dkg927702xp081fg7zsc0000gn/T/bug-report.
Done.
</pre>
