### ISSUE TITLE
headless service couldn't select endpoints from other primary clusters after upgrading to 1.15

### ISSUE THREAD

**Issue by qudongfang** [istio/istio#44141]
### Bug Description

The setting is Primary-Primary and different networks:

- `cluster-dev-1`, `dev-network`
- `cluster-qa-1`,   `qa-network`
- `cluster-prod-1,   `prod-network`
- `cluster-mgmt-1`, `mgmt-network`

All the clusters are remote clusters of `cluster-mgmt-1` so that `cluster-mgmt-1` could talk to them.

The endpoints of non-mgmt clusters are imported to the `cluster-mgmt-1` cluster with the following config:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: mgmt-1-control-plane
spec:
  values:
    global:
      meshNetworks:
        dev-network:
          endpoints:
            - fromRegistry: cluster-dev-1
        qa-network:
          endpoints:
            - fromRegistry: cluster-qa-1
        prod-network:
          endpoints:
            - fromRegistry: cluster-prod-1
```

Running `nslookup -type=A echo-headless.echo.svc.cluster.local` on the `cluster-mgmt-1` used to show up all the `echo` pods running across all the clusters. 

After upgrading to `1.15`,  `nslookup -type=A echo-headless.echo.svc.cluster.local` on the `cluster-mgmt-1` only shows the `echo` pods running on the `cluster-mgmt-1`.

After changing the network of  `cluter-mgmt-1` from `mgmt-network` to `prod-network`, the prod pods show up.

It shouldn't be related to the [topology.istio.io/controlPlaneClusters annotation](https://istio.io/latest/news/releases/1.15.x/announcing-1.15/upgrade-notes/#remote-cluster-management)  because it's not primary-remote mode.

### Version

```prose
$ istioctl version
client version: 1.16.0
control plane version: 1.14.6
data plane version: 1.14.6 (545 proxies)
```

```
$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.23.16-eks-48e63af
```

```
$ helm version --short
v3.10.2+g50f003e
```
```


### Additional Information

N/A
