### ISSUE TITLE
Use mirror to access external services

### ISSUE THREAD

**Issue by mark8s** [istio/istio#44146]
I would like to ask a question, in the mirror of VS, can the address of hosts be specified as an external service?

Do I need to configure serviceentry?

Why can't I visit. My vs configuration is like this:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
   name: helloworld
   namespace: helloworld
spec:
   hosts:
     - helloworld
   http:
     -mirror:
         host: 8080-helloworld-demo.test.cn
         port:
           number: 80
       mirror_percent: 100
       route:
         -destination:
             host: helloworld
             port:
               number: 5000
           weight: 100

```

``` 8080-helloworld-demo.test.cn``` is an external service address, which is exposed through 80. I can curl it directly in the pod, but I use mirror and there is no response.

Do you know?
