### ISSUE TITLE
Low Throughput on Online Boutique Benchmark

### ISSUE THREAD

**Issue by yizhengx** [istio/istio#44185]
### Bug Description

Setup:
We are running Online Boutique benchmark (https://github.com/GoogleCloudPlatform/microservices-demo) on chameleon open cloud with three worker nodes (raw k8s, 48 threads and 192G for each). (We also tried on openshift with three 5.8xlarge compute nodes and get very similar results)
- Resource allocation: for each server container, we assign 3 vCPUs and 1 Gi Memory, for each sidecar container, we assign 4 vCPUs and 1Gi Memory 
- Workload generator: we used wrk2 to generate user requests visiting homepage of online boutique web. We used two threads, 320 connections and 2000 input rate to saturate the mircoservices and get the throughput.
- Results: 
  - Without istio, we can achieve ~850 req/s.
  - With istio default settings, we can only achieve ~320 req/s
- Tuning:
  - Concurrency: we changed the concurrency to 0 to allow envoy use 4 worker threads but it didn't help. It makes sense since even the throughput without istio is not high.
  - Max request per connection (envoy cluster): Online-boutique uses grpc communication which use one HTTP/2 connection. For HTTP/2 connections, envoy connection pooling will use a single connection if there is no limit. So we also tried tuning max_request_per_connection for envoy cluster which reached ~650 req/s with max_request_per_connection=40.
  - Buffer limit per connection: since frontend will return a whole web page, we also tried increasing buffer limit but it didn't help much.
  
 Now we still have spaces for further tuning. One possible bottleneck would be the outbound listener. For example, frontend service will send requests to port 7000 of currency service. If I check the `top` output in frontend sidecar container, the one with very high cpu usage is always the one handling connection to port 7000. Also the ratio of user request to requests to currency service is 1:10, which means there should be ~6500 req/s to port 7000 of currency service.
<img src="https://i.imgur.com/XZ5Or8g.png"  width="70%" height="40%">
<img src="https://i.imgur.com/0to0eus.png"  width="50%" height="20%">
If this is the bottleneck, we are wondering if there is any tuning we can do. If not, what could be the bottleneck and how we can tune it? Thanks!

istio-operator.yaml
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    base:
      enabled: true
    cni:
      enabled: false
    egressGateways:
    - enabled: false
      name: istio-egressgateway
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
    istiodRemote:
      enabled: false
    pilot:
      enabled: true
  hub: docker.io/istio
  meshConfig:
    defaultConfig:
      proxyMetadata: {}
      proxyStatsMatcher:
        inclusionRegexps:
        - ".*_cx_.*"
      concurrency: 0
    enablePrometheusMerge: true
  profile: default
  tag: 1.17.1
  values:
    base:
      enableCRDTemplates: false
      validationURL: ""
    defaultRevision: ""
    gateways:
      istio-egressgateway:
        autoscaleEnabled: true
        env: {}
        name: istio-egressgateway
        secretVolumes:
        - mountPath: /etc/istio/egressgateway-certs
          name: egressgateway-certs
          secretName: istio-egressgateway-certs
        - mountPath: /etc/istio/egressgateway-ca-certs
          name: egressgateway-ca-certs
          secretName: istio-egressgateway-ca-certs
        type: ClusterIP
      istio-ingressgateway:
        autoscaleEnabled: true
        env: {}
        name: istio-ingressgateway
        secretVolumes:
        - mountPath: /etc/istio/ingressgateway-certs
          name: ingressgateway-certs
          secretName: istio-ingressgateway-certs
        - mountPath: /etc/istio/ingressgateway-ca-certs
          name: ingressgateway-ca-certs
          secretName: istio-ingressgateway-ca-certs
        type: LoadBalancer
    global:
      configValidation: true
      defaultNodeSelector: {}
      defaultPodDisruptionBudget:
        enabled: true
      defaultResources:
        requests:
          cpu: 4000m
      imagePullPolicy: ""
      imagePullSecrets: []
      istioNamespace: istio-system
      istiod:
        enableAnalysis: false
      jwtPolicy: third-party-jwt
      logAsJson: false
      logging:
        level: default:info
      meshNetworks: {}
      mountMtlsCerts: false
      multiCluster:
        clusterName: ""
        enabled: false
      network: ""
      omitSidecarInjectorConfigMap: false
      oneNamespace: false
      operatorManageWebhooks: false
      pilotCertProvider: istiod
      priorityClassName: ""
      proxy:
        autoInject: enabled
        clusterDomain: cluster.local
        componentLogLevel: misc:error
        enableCoreDump: false
        excludeIPRanges: ""
        excludeInboundPorts: ""
        excludeOutboundPorts: ""
        image: proxyv2
        includeIPRanges: '*'
        logLevel: warning
        privileged: false
        readinessFailureThreshold: 30
        readinessInitialDelaySeconds: 1
        readinessPeriodSeconds: 2
        resources:
          limits:
            cpu: 4000m
            memory: 1Gi
          requests:
            cpu: 4000m
            memory: 1Gi
        statusPort: 15020
        tracer: zipkin
      proxy_init:
        image: proxyv2
        resources:
          limits:
            cpu: 4000m
            memory: 1Gi
          requests:
            cpu: 4000m
            memory: 1Gi
      sds:
        token:
          aud: istio-ca
      sts:
        servicePort: 0
      tracer:
        datadog: {}
        lightstep: {}
        stackdriver: {}
        zipkin: {}
      useMCP: false
    istiodRemote:
      injectionURL: ""
    pilot:
      autoscaleEnabled: true
      autoscaleMax: 5
      autoscaleMin: 1
      configMap: true
      cpu:
        targetAverageUtilization: 80
      enableProtocolSniffingForInbound: true
      enableProtocolSniffingForOutbound: true
      env: {}
      image: pilot
      keepaliveMaxServerConnectionAge: 30m
      nodeSelector: {}
      podLabels: {}
      replicaCount: 1
      traceSampling: 1
    telemetry:
      enabled: true
      v2:
        enabled: true
        metadataExchange:
          wasmEnabled: false
        prometheus:
          enabled: true
          wasmEnabled: false
        stackdriver:
          configOverride: {}
          enabled: false
          logging: false
          monitoring: false
          topology: false
```

EnvoyFilter for tuning
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: envoy-filter-for-buffer-increase
  namespace: online-boutique
spec:
  configPatches:
    - applyTo: CLUSTER
      patch:
        operation: MERGE
        value:
          max_requests_per_connection: 40
```

### Version

```prose
$ istioctl version
client version: 1.17.1
control plane version: 1.17.1
data plane version: 1.17.1 (12 proxies)
$ kubectl version --short
Client Version: v1.26.2
Kustomize Version: v4.5.7
Server Version: v1.26.2
```

**Comment by kyessenov** [comment]
I think your analysis that it's caused by h2 is correct - connections are sticky in h2 so all concurrent streams are handled by a single worker which limits the throughput. For large streams, the suggestion is to limit concurrent streams per TCP connection. Try reducing server side "max_concurrent_streams" (see https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#config-core-v3-http2protocoloptions). This should cause more connections and more even worker distribution.

**Comment by yizhengx** [comment]
Thank you for your response. I tried the following yaml for max_concurrent_streams which didn't help much. And I see the same cpu usage and downstream connections.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: h2-control
  namespace: online-boutique
spec:
  configPatches:
    - applyTo: NETWORK_FILTER
      patch:
        operation: MERGE
        value:
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            http2_protocol_options:
              max_concurrent_streams: 50
```
Could you please provide more insights about the config? I'm a bit confused how setting max_concurrent_streams would help if the application itself uses one h2 connection for all grpc calls. Thanks!
