### ISSUE TITLE
Configure AuthorizationPolicy and/or behavior

### ISSUE THREAD

**Issue by ethanchowell** [istio/istio#44184]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

I'm using an AuthorizationPolicy/RequestAuthentication combo to control access to resources based on JWT claims. For example

```yaml
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: httpbin
  namespace: foo
spec:
  selector:
    matchLabels:
      app: httpbin
  jwtRules:
  - issuer: "issuer-foo"
    jwksUri: https://example.com/.well-known/jwks.json
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: httpbin
  namespace: foo
spec:
  selector:
    matchLabels:
      app: httpbin
  rules:
  - to:
    - operation:
        paths:
        - /headers
    when:
    - key: request.auth.claims[groups]
      values:
      - group-a
      - group-b
```

By default, it looks like if a user has `group-a` but not `group-b`, they can still access the `/headers` endpoint. It makes sense that this is the default, considering other ways to use the AuthorizationPolicy for filtering IPs, browser-like headers, etc. But it would be nice to be able to optionally enforce that _all_ of the `values` are present like

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: httpbin
  namespace: foo
spec:
  selector:
    matchLabels:
      app: httpbin
  rules:
  - to:
    - operation:
        paths:
        - /headers
    when:
    - key: request.auth.claims[groups]
      operator: And
      values:
      - group-a
      - group-b
```

**Describe alternatives you've considered**

I think I could push multiple AuthorizationPolicies, each checking the same claim with a single value in each but this becomes a pain point when the number of services starts to increase.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hanxiaop** [comment]
Although the values are using the `OR` logic, you can specify multiple when rules, which should be AND i think.

**Comment by hanxiaop** [comment]
For example:

```
  when:
    - key: request.auth.claims[groups]
      values:
      - group-a
    - key: request.auth.claims[groups]
      values:
      - group-b
```
