### ISSUE TITLE
Cert error when configuring the Ingress Gateway to send traffic to an external service in Ambient mode

### ISSUE THREAD

**Issue by djannot** [istio/istio#44197]
### Bug Description

Here are the Istio resources:

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: httpbin-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpbin
  namespace: default
spec:
  gateways:
  - istio-system/httpbin-gateway
  hosts:
  - '*'
  http:
  - route:
    - destination:
        host: httpbin.org
        port:
          number: 443
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: httpbin
  namespace: istio-system
spec:
  exportTo:
  - .
  hosts:
  - httpbin.org
  ports:
  - name: http
    number: 80
    protocol: HTTP
    targetPort: 80
  - name: https
    number: 443
    protocol: HTTPS
    targetPort: 443
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: httpbin
  namespace: istio-system
spec:
  host: httpbin.org
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE
        sni: httpbin.org
```

If I try to execute a curl on `/get` I get the following error:

```
upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
```

And this in the logs of the Ingress Gateway:

```
[2023-03-31T14:36:54.484Z] "GET /get HTTP/1.1" 503 UF,URX upstream_reset_before_response_started{connection_failure,TLS_error:_268435581:SSL_routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED} - "TLS_error:_268435581:SSL_routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED" 0 218 533 - "172.18.0.4" "curl/7.68.0" "f248a5e8-bc31-43d4-8c0e-22e1e84eb4c9" "172.18.101.1" "52.20.27.92:443" outbound|443||httpbin.org - 10.101.1.2:8080 172.18.0.4:17255 - -
```

### Version

```prose
istioctl version
client version: 1.18.0-alpha.0
control plane version: 1.18.0-alpha.0
data plane version: 1.18.0-alpha.0 (5 proxies)
```
