### ISSUE TITLE
Envoy proxy does not emit HTTP-related metrics until sibling container in pod is ready

### ISSUE THREAD

**Issue by m90** [istio/istio#44247]
### Bug Description

We are having Istio inject sidecar proxies into the pods of our 3-node ElasticSearch cluster. Proxying and intra-cluster traffic work as intended, however we are facing one issue when collecting metrics from the proxies:

When re-created, an ElasticSearch node can take quite a while before it passes its readiness probe (say ~5 mins). During this period, we can observe that:

a. the sidecar proxy is up
b. the sidecar proxy is already seeing traffic that is properly relayed to the ElasticSearch node
c. the sidecar proxy is being successfully scraped by our Prometheus instance

The problem we are having is that __during this recovery time, no HTTP-level metrics (e.g. `istio_requests_total`) will be present in the `/stats` response of the proxy__, and thus will not show up in our monitoring. Other metrics, e.g. `istio_build gauge` will always be served. Once the node has recovered and Kubernetes marks the pod as ready, metrics like `istio_requests_total` will be included again.

This seems unintended as the proxy is being scraped while serving traffic, but no metrics about the traffic are included.

Is this expected behavior or somethings that can be configured to work differently?

### Version

```prose
$ kubectl version --short
Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.24.9-gke.3200
```

```
$ helm version --short
v3.10.3+g835b733
```

`istiod` Helm chart is at 1.17.1, `base` is at `1.17.1` as well.
```


### Additional Information

`istioctl` is not in use.

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
This seems unexpected and I cannot reproduce it.

What I did:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  name: httpbin
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: httpbin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: httpbin
    spec:
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: Always
        name: httpbin
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /get
            port: 800
            scheme: HTTP
          initialDelaySeconds: 4
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
```

This pod is never ready

Then from another pod `curl HTTPBIN_POD_IP/get`

Then  in httpbin
```
$ curl localhost:15090/stats/prometheus -s | grep istio_requests
# TYPE istio_requests_total counter
istio_requests_total{reporter="destination",source_workload="unknown",source_canonical_service="unknown",source_canonical_revision="latest",source_workload_namespace="unknown",source_principal="unknown",source_app="unknown",source_version="unknown",source_cluster="unknown",destination_workload="httpbin",destination_workload_namespace="default",destination_principal="unknown",destination_app="httpbin",destination_version="",destination_service="httpbin.default.svc.cluster.local",destination_canonical_service="httpbin",destination_canonical_revision="latest",destination_service_name="httpbin",destination_service_namespace="default",destination_cluster="Kubernetes",request_protocol="http",response_code="200",grpc_response_status="",response_flags="-",connection_security_policy="none"} 9
```
