### ISSUE TITLE
Issues with Istio upgrade from 1.13.0 to 1.17.1

### ISSUE THREAD

**Issue by yasithab-pf** [istio/istio#44245]
### Bug Description

I upgraded Istio from version 1.13.0 to 1.17.1, going through the intermediate versions **1.13.9, 1.14.6, 1.15.6, 1.16.3, and finally 1.17.1**. However, after completing the upgrade, I noticed that some of the **istio-ingressgateway** pods were still running the old version **(1.13.0)**, even though all the pods were rotated automatically during the upgrade process. Is this a common issue, or did I make a mistake?

### Version

```prose
istioctl version

client version: 1.17.1
control plane version: 1.17.1
data plane version: 1.17.1 (184 proxies)

kubectl version --short

Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.23.16-eks-48e63af
WARNING: version difference between client (1.25) and server (1.23) exceeds the supported minor version skew of +/-1
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [X] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by howardjohn** [comment]
It depends how you installed and upgraded. There are unfortunately quite a few paths, and different ways involve different steps to upgrade the GW.

**Comment by yasithab-pf** [comment]
Hello @howardjohn, Thank you for reaching out :)

Our approach involves IstioOperator and upgrading it using the following command.

`istioctl install --readiness-timeout 10m0s -y -f my-config.yaml`

Please let me know if you want any additional information.

**Comment by westwind-sc** [comment]
Any revision labels on the namespace?

**Comment by yasithab-pf** [comment]
Hello @westwind-sc

Thank you for the reply. These are the labels/annotations we have right now. Please let me know if you need any additional Information. 

The **istio-system** namespace

```
Name:         istio-system
Labels:       istio-injection=disabled
              istio-operator-managed=Reconcile
              kubernetes.io/metadata.name=istio-system
              name=istio-system
              operator.istio.io/component=Base
              operator.istio.io/managed=Reconcile
              operator.istio.io/version=1.5.4
Annotations:  <none>
Status:       Active

No resource quota.

No LimitRange resource.
```

The **istiod** pod

```
Name:                istiod-86997f8bf5-9vv9f
Namespace:      istio-system
Priority:             100000
Priority Class Name:  istio
Labels:          app=istiod
                      install.operator.istio.io/owning-resource=unknown
                      istio=pilot
                      istio.io/rev=default
                      operator.istio.io/component=Pilot
                      pod-template-hash=86997f8bf5
                      sidecar.istio.io/inject=false
Annotations: kubernetes.io/psp: eks.privileged
                      prometheus.io/port: 15014
                      prometheus.io/scrape: true
                      sidecar.istio.io/inject: false
```

The **istio-ingressgateway** pod

```
Name:                 istio-ingressgateway-59876b4f48-26gsn
Namespace:       istio-system
Priority:             100000
Priority Class Name:  istio
Labels:          app=istio-ingressgateway
                      chart=gateways
                      heritage=Tiller
                      install.operator.istio.io/owning-resource=unknown
                      istio=ingressgateway
                      istio.io/rev=default
                      operator.istio.io/component=IngressGateways
                      pod-template-hash=59876b4f48
                      release=istio
                      service.istio.io/canonical-name=istio-ingressgateway
                      service.istio.io/canonical-revision=latest
                      sidecar.istio.io/inject=false
Annotations: kubernetes.io/psp: eks.privileged
                      prometheus.io/path: /stats/prometheus
                      prometheus.io/port: 15020
                      prometheus.io/scrape: true
                      sidecar.istio.io/inject: false
```

**Comment by howardjohn** [comment]
Whats in my-config.yaml? Probably something there is telling it not to overwrite the gateway. if nothing obvious then logs from the install will help

**Comment by yasithab-pf** [comment]
Hello @howardjohn 

Thanks for the reply :) Please find the my-config.yaml content below.

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  components:
    ingressGateways:
    - enabled: true
      k8s:
        nodeSelector:
          nodegroup: app
        env:
        - name: ISTIO_META_ROUTER_MODE
          value: sni-dnat
        hpaSpec:
          maxReplicas: ${try(gateway_resources.max_replicas, "30")}
          metrics:
          - resource:
              name: cpu
              targetAverageUtilization: 80
            type: Resource
          minReplicas: 3
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: istio-ingressgateway
        resources:
          limits:
            cpu: ${try(gateway_resources.limits.cpu, "2000m")}
            memory: ${try(gateway_resources.limits.memory, "1024Mi")}
          requests:
            cpu: ${try(gateway_resources.requests.cpu, "100m")}
            memory: ${try(gateway_resources.requests.memory, "256Mi")}
        service:
          ports:
          - name: status-port
            port: 15021
            targetPort: 15021
            nodePort: 30710
          - name: http2
            port: 80
            targetPort: 8080
            nodePort: 31380
          - name: https
            port: 443
            targetPort: 8443
            nodePort: 31390
          - name: tls
            port: 15443
            targetPort: 15443
            nodePort: 31181
        strategy:
          rollingUpdate:
            maxSurge: 100%
            maxUnavailable: 25%
      name: istio-ingressgateway
    pilot:
      k8s:
        nodeSelector:
          nodegroup: app
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - istiod
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 100
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - istiod
              topologyKey: kubernetes.io/hostname

  meshConfig:
    accessLogFile: "/dev/stdout"
    accessLogEncoding: JSON
    enableAutoMtls: false
    defaultConfig:
      holdApplicationUntilProxyStarts: true
  values:
    global:
      proxy:
        resources: ${jsonencode(proxy_resources)}
        %{~ if istio_tracing_proxy_to_datadog_enabled ~}
        tracer: datadog
        %{~ endif ~}
      priorityClassName: ${priority_class}
    gateways:
      istio-ingressgateway:
        type: NodePort
        podAntiAffinityLabelSelector:
        - key: app
          operator: In
          values: istio-ingressgateway
          topologyKey: kubernetes.io/hostname
        podAntiAffinityTermLabelSelector:
        - key: app
          operator: In
          values: istio-ingressgateway
          topologyKey: failure-domain.beta.kubernetes.io/zone

    pilot:
      autoscaleMin: 3
      traceSampling: ${istio_tracing_sampling_rate}

```

By the way, this morning I downgraded istio to version 1.13.0 and completely uninstalled it with the `istioctl x uninstall --purge` command. Then, I incrementally upgraded it back to version 1.17.1, checking that all `istio-ingressgateway` and `istiod` pod image tags were updated accordingly. 

However, when I attempted to test a couple of websites, I received a 502 error. Upon checking, I found that the istio sidecar image tags for these website pods were correct, but most of the `VirtualServices` were missing, requiring me to redeploy all the applications to enable the VirtualServices again. 

I suspect that the `istioctl x uninstall --purge` command removes all istio components, which may be the intended behavior, but I am still uncertain whether the initial issue is a bug in istio or related to the deployment process.
