### ISSUE TITLE
Telemetry CRD drop metrics not work

### ISSUE THREAD

**Issue by vaxilicaihouxian** [istio/istio#44266]
### Bug Description

I create a crd.
```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: metrics-optimize
  namespace: my-space
spec:
  accessLogging:
  - disabled: true
  metrics:
  - overrides:
    - match:
        metric: REQUEST_DURATION
        mode: CLIENT_AND_SERVER
      disabled: true
    providers:
      - name: prometheus
      - name: stackdriver
```
I use config_dump api to get config info: config.txt

Run command `fgrep request_duration_milliseconds config.txt` and output is:
```
...
"value": "{\"metrics\":[{\"name\":\"request_duration_milliseconds\",\"drop\":true}]}"
...
```

After a while,I fetch xxx:15090/stats/prometheus api.It still has so many  request_duration_milliseconds metrics.

### Version

```prose
istioctl version
1.13.9
kubectl version --short
Client Version: v1.21.2
Server Version: v1.20.8
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
