### ISSUE TITLE
Why is the default failurePolicy of ValidatingWebhookConfiguration set through helm chart template?

### ISSUE THREAD

**Issue by gitanuj** [istio/istio#44285]
The official Helm chart for istiod sets [failurePolicy of ValidatingWebhookConfiguration as Ignore](https://github.com/istio/istio/blob/cbb162618b16b4a887b33f73382631f46f442148/manifests/charts/istio-control/istio-discovery/templates/validatingwebhookconfiguration.yaml#L44). There is a comment saying that webhook controller will make it `Fail` when endpoint is ready.

This causes almost immediate update of this property right after the helm chart is installed and makes it difficult to rely on diff'ing tools like [tk diff](https://tanka.dev/diff-strategy) to track changes that have been deployed (because this always shows up in diffs).

Can the default failurePolicy be `Fail`? If not, can this ValidatingWebhookConfiguration be deployed by istiod during runtime when it is actually ready to be used?

**Comment by zirain** [comment]
IIRC, istiod will modify it after it's running.

**Comment by hanxiaop** [comment]
> If not, can this ValidatingWebhookConfiguration be deployed by istiod during runtime when it is actually ready to be used?

IMO this adds too much complexity to the installation process and Istiod.

**Comment by howardjohn** [comment]
If its Fail the problem is that any Istio config is rejected, until istiod comes up. But we create config during install: https://github.com/istio/istio/issues/22095.

We _just_ (1 week ago) got to the point that the default install doesn't create Istio config, but there are still cases it does.

**Comment by howardjohn** [comment]
Expecting deployed resources to not change isn't feasible, its extremely common for resources to be modified (annotations added, etc)

**Comment by batazor** [comment]
It's made problem when we use gitops (as ArgoCD)

**Comment by murzart** [comment]
> It's made problem when we use gitops (as ArgoCD)

I just added it to `ignoreDifferences`

for the base chart:
```
    spec:
      ignoreDifferences:
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          name: istiod-default-validator
          jqPathExpressions:
            - .webhooks[] | select(.name == "validation.istio.io") | .failurePolicy
```

for istiod:
```
    spec:
      ignoreDifferences:
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          name: istio-validator-istio-system
          jqPathExpressions:
            - .webhooks[] | select(.name == "rev.validation.istio.io") | .failurePolicy
```

see: https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/

**Comment by oliverpark999** [comment]
> > gitops(ArgoCD로)를 사용할 때 문제가 발생합니다.
> 
> 방금 추가했어요 `ignoreDifferences`
> 
> 기본 차트의 경우:
> 
> ```
>     spec:
>       ignoreDifferences:
>         - group: admissionregistration.k8s.io
>           kind: ValidatingWebhookConfiguration
>           name: istiod-default-validator
>           jqPathExpressions:
>             - .webhooks[] | select(.name == "validation.istio.io") | .failurePolicy
> ```
> 
> istiod의 경우:
> 
> ```
>     spec:
>       ignoreDifferences:
>         - group: admissionregistration.k8s.io
>           kind: ValidatingWebhookConfiguration
>           name: istio-validator-istio-system
>           jqPathExpressions:
>             - .webhooks[] | select(.name == "rev.validation.istio.io") | .failurePolicy
> ```
> 
> 참조: [ https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/ ](https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/)

Where do I add this?

**Comment by oliverpark999** [comment]
> > It's made problem when we use gitops (as ArgoCD)
> 
> I just added it to `ignoreDifferences`
> 
> for the base chart:
> 
> ```
>     spec:
>       ignoreDifferences:
>         - group: admissionregistration.k8s.io
>           kind: ValidatingWebhookConfiguration
>           name: istiod-default-validator
>           jqPathExpressions:
>             - .webhooks[] | select(.name == "validation.istio.io") | .failurePolicy
> ```
> 
> for istiod:
> 
> ```
>     spec:
>       ignoreDifferences:
>         - group: admissionregistration.k8s.io
>           kind: ValidatingWebhookConfiguration
>           name: istio-validator-istio-system
>           jqPathExpressions:
>             - .webhooks[] | select(.name == "rev.validation.istio.io") | .failurePolicy
> ```
> 
> see: https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/

Where do I add this?

**Comment by Cr0n1c** [comment]
> > > It's made problem when we use gitops (as ArgoCD)
> > 
> > 
> > I just added it to `ignoreDifferences`
> > for the base chart:
> > ```
> >     spec:
> >       ignoreDifferences:
> >         - group: admissionregistration.k8s.io
> >           kind: ValidatingWebhookConfiguration
> >           name: istiod-default-validator
> >           jqPathExpressions:
> >             - .webhooks[] | select(.name == "validation.istio.io") | .failurePolicy
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > for istiod:
> > ```
> >     spec:
> >       ignoreDifferences:
> >         - group: admissionregistration.k8s.io
> >           kind: ValidatingWebhookConfiguration
> >           name: istio-validator-istio-system
> >           jqPathExpressions:
> >             - .webhooks[] | select(.name == "rev.validation.istio.io") | .failurePolicy
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > see: https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/
> 
> Where do I add this?

Add this to the Application manifest... Example
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations: {}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    argocd.argoproj.io/instance: app-of-apps-xxxxxxx
  name: istiod
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      jqPathExpressions:
        - >-
          .webhooks[] | select(.name == "rev.validation.istio.io") |
          .failurePolicy
      kind: ValidatingWebhookConfiguration
      name: istio-validator-istio-system
  project: default
  source:
    helm:
      ignoreMissingValueFiles: true
      valueFiles:
        - values.yaml
    path: xxxxxxxx/istiod
    repoURL: 'git@github.com:xxxxxxxxxx/xxxxxxxxx.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
```
