### ISSUE TITLE
localhost HOST header gives 400 bad Request for the health check

### ISSUE THREAD

**Issue by jinn-k** [istio/istio#44291]
### Bug Description

Our system use Django framework, so for the allowed_hosts we need localhost host header for the health check from the kubelet. To achieve it we use httpHeaders for the livenessProbe and readinessProbe.
```
        readinessProbe:
          failureThreshold: 10
          httpGet:
            httpHeaders:
            - name: HOST
              value: localhost
            path: /status/
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
```

As I checked, if I use `httpHeaders` to push localhost host header, I found out that the istio-proxy gives 400 bad request like below.
```
00:08:14.181896 IP 10.119.26.76.37666 > 10.119.28.178.15020: Flags [P.], seq 1:155, ack 1, win 491, options [nop,nop,TS val 3656328203 ecr 791935060], length 154
E...JN@.....
w.L
w...":.'..+..;.....L......
..$./3.TGET /app-health/service-name/readyz HTTP/1.1
Host: 10.119.28.178:15020
User-Agent: kube-probe/1.22+
Accept: */*
HOST: localhost
Connection: close


00:08:14.181909 IP 10.119.28.178.15020 > 10.119.26.76.37666: Flags [.], ack 155, win 489, options [nop,nop,TS val 791935060 ecr 3656328203], length 0
E..4.m@....j
w..
w.L:.."..;.'.......L......
/3.T..$.
00:08:14.182009 IP 10.119.28.178.15020 > 10.119.26.76.37666: Flags [P.], seq 1:104, ack 155, win 489, options [nop,nop,TS val 791935060 ecr 3656328203], length 103
E....n@.....
w..
w.L:.."..;.'.......Ly.....
/3.T..$.HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Connection: close
```

If I remove httpHeaders, it works fine. (also I put allow all from the allowed_hosts in Django)
```
00:10:20.636776 IP 10.119.26.76.35548 > 10.119.24.149.15020: Flags [P.], seq 1:138, ack 1, win 491, options [nop,nop,TS val 2930496383 ecr 2308459026], length 137
E.....@...1.
w.L
w....:.ag0dn.......H~.....
......J.GET /app-health/service-name/readyz HTTP/1.1
Host: 10.119.24.149:15020
User-Agent: kube-probe/1.22+
Accept: */*
Connection: close


00:10:20.636796 IP 10.119.24.149.15020 > 10.119.26.76.35548: Flags [.], ack 138, win 489, options [nop,nop,TS val 2308459026 ecr 2930496383], length 0
E..4t.@....P
w..
w.L:...n...ag0.....G......
..J.....
00:10:20.641938 IP 10.119.24.149.15020 > 10.119.26.76.35548: Flags [P.], seq 1:95, ack 138, win 489, options [nop,nop,TS val 2308459031 ecr 2930496383], length 94
E...t.@.....
w..
w.L:...n...ag0.....HS.....
..J.....HTTP/1.1 200 OK
Date: Fri, 07 Apr 2023 00:10:20 GMT
Content-Length: 0
Connection: close
```

Can I know the principle of the health check of the istio-proxy through `ISTIO_KUBE_APP_PROBERS` to troubleshoot together and why localhost host header influence to the health check?

Many thanks for your help in advance !!!

### Version

```prose
❯ istioctl version
client version: 1.16.3
control plane version: 1.16.3
data plane version: 1.16.3 (183 proxies)
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
