### ISSUE TITLE
[IstioOperator] Unable to apply k8s patch to ztunnel

### ISSUE THREAD

**Issue by andriilahuta** [istio/istio#44311]
### Bug Description

Trying to apply a manifest like this:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-operator
spec:
  profile: ambient
  components:
    ztunnel:
      enabled: true
      k8s:
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
```
results in the following error:
`Error:   failed to update resource with server-side apply for obj DaemonSet/istio-system/ztunnel: failed to create typed patch object (istio-system/ztunnel; apps/v1, Kind=DaemonSet): .spec.template.spec.containers: expected list, got &{map[[name:]:map[resources:map[limits:map[cpu:200m memory:200Mi] requests:map[cpu:100m memory:100Mi]]]]}`.

### Version

```prose
client version: 1.18.0-alpha.0
control plane version: 1.18.0-alpha.0
data plane version: 1.18.0-alpha.0 (5 proxies)

Client Version: v1.26.3
Kustomize Version: v4.5.7
Server Version: v1.26.3
```

### Affected product area

- [X] Ambient
- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
