### ISSUE TITLE
Upstream TCP with proxy protocol

### ISSUE THREAD

**Issue by JuniorJPDJ** [istio/istio#44342]
**Describe the feature request**
Making connection to upstreams services (envoy clusters) encapsulated in PROXY protocol.
Feature was requested at forums at least 2 times and I saw some stackoverflow posts about it too:
- https://discuss.istio.io/t/enable-proxy-protocol-from-istio-to-upstreams/10321
- https://discuss.istio.io/t/config-istio-proxy-protocol/14911

**Describe alternatives you've considered**
EnvoyFilter, but now it's impossible to do using filters due to `transport_socket_matches` being an array - MERGE is adding `transport_socket` at the end and it's never matched as 
```
      {
        "name": "tlsMode-disabled",
        "match": {},
        "transport_socket": {
         "name": "envoy.transport_sockets.raw_buffer",
         "typed_config": {
          "@type": "type.googleapis.com/envoy.extensions.transport_sockets.raw_buffer.v3.RawBuffer"
         }
        }
       }
```
is before and is matching all the traffic.
The only way I figured out it very much dirty and is recreating whole cluster. This AFAIK makes it impossible to apply other `EnvoyFilter.ClusterMatch` filters based on service names later.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[x] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Comment by hzxuzhonghu** [comment]
cc

**Comment by klarose** [comment]
Thanks for posting this issue. It was previously tracked here as well: https://github.com/istio/istio/issues/42257#issuecomment-1476399995

**Comment by JuniorJPDJ** [comment]
Thank you very much for your previous issue link!
I've not found it myself.
It looks like more people needs this feature too ;)

**Comment by rsalmond** [comment]
Can this be closed now that #48237 has shipped?

**Comment by JuniorJPDJ** [comment]
Probably yes, I haven't checked if it works tho.

**Comment by JuniorJPDJ** [comment]
There's no way to enable proxy protocol on only one of ports - it's only specified in `TrafficPolicy` and not in `TrafficPolicy.PortTrafficPolicy`.

**Comment by hzxuzhonghu** [comment]
This is like tunnel, making it per port is viable too

**Comment by JuniorJPDJ** [comment]
Also it looks like it's working only for cluster-internal services.
When trying to forward traffic to service with EndpointSlice targeted at IP beyond the cluster it doesn't send proxy headers.
It works for service with pod inside the cluster.

**Comment by hzxuzhonghu** [comment]
DR must be bound with a service, so you can define a SE for external service

**Comment by JuniorJPDJ** [comment]
It shouldn't be neccessary as I've native Service defined for those, just with `ClusterIP: None` and with EndpointSlice pointing to the IP.

**Comment by howardjohn** [comment]
Can you provide the Service and DR config?

**Comment by JuniorJPDJ** [comment]
I don't have DR config, the `Service` looks like that:

```
apiVersion: v1
kind: Service
metadata:
  labels:
    argocd.argoproj.io/instance: cluster-config
  name: big-boy
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  - IPv6
  ipFamilyPolicy: RequireDualStack
  ports:
  - appProtocol: ssh 
    name: ssh-main
    port: 22
    protocol: TCP 
    targetPort: 22
  - appProtocol: tls
    name: tls-haproxy
    port: 8443
    protocol: TCP 
    targetPort: 8443
  - appProtocol: http
    name: http-haproxy
    port: 880 
    protocol: TCP 
    targetPort: 880 
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

With `EndpointSlice` like this:
```
addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 192.168.64.41
  conditions: {}
kind: EndpointSlice
metadata:
  labels:
    argocd.argoproj.io/instance: cluster-config
    kubernetes.io/service-name: big-boy
  name: big-boy
ports:
- appProtocol: ssh 
  name: ssh-main
  port: 22
  protocol: TCP 
- appProtocol: tls 
  name: tls-haproxy
  port: 8443
  protocol: TCP 
- appProtocol: http
  name: http-haproxy
  port: 880 
  protocol: TCP 
```

**Comment by howardjohn** [comment]
Istio configures PROXY with aDestinationrule, so not sure I understand . If you don't set that, you must do the PROXY yourself and Istio insn't involved here at all?

**Comment by JuniorJPDJ** [comment]
Nvm, yes, sorry. I had one. Wait a second, I need to find it in git history as I already migrated to envoy-gateway.

**Comment by JuniorJPDJ** [comment]
So full pack from commit when I was using the istio:

```
# Source: config/templates/external-services.yaml                                                                                                                                                                                                         
apiVersion: discovery.k8s.io/v1                                                                                                                                                                                                                           
kind: EndpointSlice                                                                                                                                                                                                                                       
metadata:                                                                                                                                                                                                                                                 
  name: "big-boy"                                                                                                                                                                                                                                         
  namespace: "istio-system"                                                                                                                                                                                                                               
  labels:                                                                                                                                                                                                                                                 
    kubernetes.io/service-name: "big-boy"                                                                                                                                                                                                                 
addressType: "IPv4"                                                                                                                                                                                                                                       
ports:                                                                                                                                                                                                                                                    
    - appProtocol: ssh                                                                                                                                                                                                                                    
      name: ssh-main                                                                                                                                                                                                                                      
      port: 22                                                                                                                                                                                                                                            
      protocol: TCP                                                                                                                                                                                                                                       
    - appProtocol: tls                                                                                                                                                                                                                                    
      name: tls-haproxy                                                                                                                                                                                                                                   
      port: 8443                                                                                                                                                                                                                                          
      protocol: TCP                                                                                                                                                                                                                                       
    - appProtocol: http                                                                                                                                                                                                                                   
      name: http-haproxy                                                                                                                                                                                                                                  
      port: 880                                                                                                                                                                                                                                           
      protocol: TCP                                                                                                                                                                                                                                       
endpoints:                                                                                                                                                                                                                                                
  - addresses:                                                                                                                                                                                                                                            
      - "192.168.64.41"                                                                                                                                                                                                                                   
    conditions: {}                                                                                                                                                                                                                                        
---
# Source: config/templates/external-services.yaml
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: "big-boy"
  namespace: "istio-system"
  labels:
    kubernetes.io/service-name: "big-boy"
addressType: "IPv4"
ports:
    - appProtocol: ssh
      name: ssh-main
      port: 22
      protocol: TCP
    - appProtocol: tls
      name: tls-haproxy
      port: 8443
      protocol: TCP
    - appProtocol: http
      name: http-haproxy
      port: 880
      protocol: TCP
endpoints:
  - addresses:
      - "192.168.64.41"
    conditions: {}
---
# Source: config/templates/istio-destinationrules-proxyproto.yaml                                                                                                                                                                                         
apiVersion: networking.istio.io/v1beta1                                                                                                                                                                                                                   
kind: DestinationRule                                                                                                                                                                                                                                     
metadata:                                                                                                                                                                                                                                                 
  name: proxy-protocol-route-big-boy-tls-haproxy                                                                                                                                                                                                          
  namespace: istio-system                                                                                                                                                                                                                                 
spec:                                                                                                                                                                                                                                                                                                                                                                                                                                                            
  host: "big-boy.istio-system.svc.cluster.local"                                                                                                                                                                                                          
  # TODO: 8443 when https://github.com/istio/istio/issues/44342#issuecomment-1998896077 is fixed                                                                                                                                                          
  trafficPolicy:                                                                                                                                                                                                                                          
    proxyProtocol:                                                                                                                                                                                                                                        
      version: V2   
```

When used almost the same DR with service pointing to my `ingress-nginx` inside the same cluster - it worked like a charm.

This is directly from `helm template` after checking out the commit before migration to Envoy Gateway.
