### ISSUE TITLE
Istio-init container not honoring logAsJson flag

### ISSUE THREAD

**Issue by iress-ac** [istio/istio#44352]
### Bug Description

With the global mesh option `logAsJson` set to true, I was expecting logs from `istio-init` init containers to be logged as json. Instead it logs about 200 lines of unformatted logs, starting with:

```
2023-04-12T11:38:49.067419Z     info    Istio iptables environment:
ENVOY_PORT=
INBOUND_CAPTURE_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_OUTBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_EXCLUDE_INTERFACES=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=
ISTIO_META_DNS_CAPTURE=true
INVALID_DROP=
```

`istio-init` has `log_as_json` passed to it as a flag:

```
initContainers:
    - name: istio-init
      image: >-
        <snip>/gloo-mesh/istio-a7d0a87b8a81/proxyv2:1.17.1-solo-fips
      args:
        - istio-iptables
        - '-p'
        - '15001'
        - '-z'
        - '15006'
        - '-u'
        - '1337'
        - '-m'
        - REDIRECT
        - '-i'
        - '*'
        - '-x'
        - ''
        - '-b'
        - '*'
        - '-d'
        - 15090,15021,15020
        - '--log_output_level=default:warn'
        - '--log_as_json'
```

### Version

```prose
$istioctl version
client version: 1.17.1
control plane version: 1.17.1-solo-fips
data plane version: 1.17.1-solo-fips (9 proxies)
$kubectl version --short
Client Version: v1.24.12
Kustomize Version: v4.5.4
Server Version: v1.24.12-eks-ec5523e
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
