### ISSUE TITLE
A ServiceEntry duplicating existing Service ruins ingressgateway

### ISSUE THREAD

**Issue by apolovov** [istio/istio#44356]
### Bug Description

Steps to reproduce:
* Deploy ingressgateway.
* Create a Gateway:

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  labels:
    app: ingressgateway
  name: ingressgateway
  namespace: d8-istio
spec:
  selector:
    app: ingressgateway
  servers:
  - hosts:
    - '*.ice.local'
    port:
      name: tls
      number: 15443
      protocol: TLS
    tls:
      mode: AUTO_PASSTHROUGH
```

* Create a Service:

```
apiVersion: v1
kind: Service
metadata:
  name: hello-breaker
  namespace: c1
spec:
  ports:
  - name: http
    port: 8888
    protocol: TCP
    targetPort: 5000
  selector:
    app: hello
  type: ClusterIP
```

* Create a ServiceEntry:

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: hello-breaker-svc
  namespace: c1
spec:
  hosts:
  - hello-breaker.c1.svc.ice.local
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 8888
    protocol: TCP
  resolution: DNS
  workloadSelector:
    labels:
      app: hello
```

* Restart ingressgateway pod and see the error:

```
2023-04-12T18:02:25.187207Z	warning	envoy config	gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_15443: error adding listener '0.0.0.0:15443': filter chain '' has the same matching rules defined as ''
```

💡  I suspect, it is because control-plane generates two filterChains with the same filterChainMatch for a single listener:
```
# ./istioctl -n d8-istio proxy-status ingressgateway-44c4x | sed -e 's/^-//' -e 's/^+//' -e 's/^Routes Match//' -e '1,4d' > status.json
# cat status.json | jq '.dynamicListeners[].activeState.listener.filterChains[] | select(.filterChainMatch.serverNames[0] == "outbound_.8888_._.hello-breaker.c1.svc.ice.local") | .filterChainMatch'
{
  "serverNames": [
    "outbound_.8888_._.hello-breaker.c1.svc.ice.local"
  ],
  "applicationProtocols": [
    "istio",
    "istio-peer-exchange",
    "istio-http/1.0",
    "istio-http/1.1",
    "istio-h2"
  ]
}
{
  "serverNames": [
    "outbound_.8888_._.hello-breaker.c1.svc.ice.local"
  ],
  "applicationProtocols": [
    "istio",
    "istio-peer-exchange",
    "istio-http/1.0",
    "istio-http/1.1",
    "istio-h2"
  ]
}
```

### Version

```prose
./istioctl version
client version: 1.16.1
istiod version: 1.16.2
data plane version: 1.16.2 (11 proxies)

kubectl version --short
Client Version: v1.22.17
Server Version: v1.22.17
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
