### ISSUE TITLE
DestinationRule exportTo does not work when there are multiple destination rules with different subsets and exportTo

### ISSUE THREAD

**Issue by TommyTu** [istio/istio#44366]
### Bug Description

Configuration is defined as follow:
Basically there are two destinationRules with identical namespace(default) and host,
with different `exportTo`, one is `foo` and another is `bar`, and different subset:  `v1` and `v2`.

```
 apiVersion: networking.istio.io/v1alpha3
 kind: DestinationRule
 metadata:
   name: d1
   namespace: default
 spec:
   host: "helloworld.default.svc.cluster.local"
   exportTo: ["foo"]
   subsets:
   - name: v1
     labels:
       version: v1
       app: helloworld
 ---
 apiVersion: networking.istio.io/v1alpha3
 kind: DestinationRule
 metadata:
   name: d2
   namespace: default
 spec:
   host: "helloworld.default.svc.cluster.local"
   exportTo: ["bar"]
   subsets:
   - name: v2
     labels:
       version: v2
       app: `helloworld`
 ---
 apiVersion: v1
 kind: Service
 metadata:
   name: helloworld
   labels:
     app: helloworld
     service: helloworld
 spec:
   ports:
   - port: 5000
     name: http
   selector:
     app: helloworld
```

Ideally, the proxy on namespace `foo` should only see subset `v1` for cluster `helloworld`, however it seems like proxy on namespace `foo` is able to see both subset `v1` and `v2`:

```
helloworld git:(main) ✗ istioctl proxy-config clusters helloworld-v1-77489ccb5f-t7r7d  -n foo
SERVICE FQDN                                            PORT      SUBSET     DIRECTION     TYPE             DESTINATION RULE
                                                        5000      -          inbound       ORIGINAL_DST     
BlackHoleCluster                                        -         -          -             STATIC           
InboundPassthroughClusterIpv4                           -         -          -             ORIGINAL_DST     
PassthroughCluster                                      -         -          -             ORIGINAL_DST     
agent                                                   -         -          -             STATIC           
helloworld.default.svc.cluster.local                    5000      -          outbound      EDS              d1.default
helloworld.default.svc.cluster.local                    5000      v1         outbound      EDS              d1.default
helloworld.default.svc.cluster.local                    5000      v2         outbound      EDS              d1.default
```

I did some investigation on the code base and here is the root cause:
https://github.com/istio/istio/blob/master/pilot/pkg/model/push_context.go#L1766
in this function, we will merge subsets from multiple destination rules with same namespace and same host, while for exportTo, we always take the oldest DR from the merged DR list.

Not sure if it is expected behavior?

### Version

```prose
$istioctl version                                                     
client version: 1.15.0
control plane version: 1.15.0
data plane version: 1.15.0 (5 proxies)
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
