### ISSUE TITLE
istioctl analyze is reporting missing addresses field in ServiceEntry for resolution: DNS

### ISSUE THREAD

**Issue by lulukas86** [istio/istio#44369]
### Bug Description

When running `istioctl analyze`, it reports that the field `addresses` is missing in the ServiceEntry. However, I believe this is not needed as the resolution is set to DNS.

> Warning [IST0134] (ServiceEntry egress-gateway-database/database-app-backend) ServiceEntry addresses are required for this protocol.

ServiceEntry:
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: database-app-backend
  namespace: egress-gateway-database
spec:
  hosts:
  - app-backend-db.domain.com
  location: MESH_EXTERNAL
  ports:
  - name: database-3306
    number: 3306
    protocol: TCP
  resolution: DNS
```
Can someone explain what are the reasons to define the IP/CIDRs as addresses in the ServiceEntry when the resolution is anyway done by the DNS?

### Version

```prose
$ istioctl version
client version: 1.14.3
control plane version: 1.13.2
data plane version: 1.13.2 (161 proxies)

$ kubectl version --short
Client Version: v1.24.1
Kustomize Version: v4.5.4
Server Version: v1.22.12+vmware.1
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
