### ISSUE TITLE
VirtualService with empty header prefix match casues envoy validation error 

### ISSUE THREAD

**Issue by larhauga** [istio/istio#44424]
### Bug Description

When a VirtualService tries to use `prefix: ""` for header matching (eg. does the header exist), it validates OK, but on configuration push from istio to envoy it will fail envoy configuration validation. 

Given the following example, where it tries to match for a `prefix: ""` on the header `appkey` it cases the following error message.
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nexus
spec:
  gateways:
  - istio-system/devns
  hosts:
  - example
  http:
  - match:
    - headers:
        appkey:
          prefix: ""
    route:
    - destination:
        host: nexus.nexus.svc.cluster.local
        port:
          number: 8080

```

```
gRPC config for type.googleapis.com/envoy.config.route.v3.RouteConfiguration rejected: Proto constraint validation failed (RouteConfigurationValidationError.VirtualHosts[3]: embedded message failed validation | caused by VirtualHostValidationError.Routes[0]: embedded message failed validation | caused by RouteValidationError.Match: embedded message failed validation | caused by RouteMatchValidationError.Headers[0]: embedded message failed validation | caused by HeaderMatcherValidationError.StringMatch: embedded message failed validation | caused by StringMatcherValidationError.Prefix: value length must be at least 1 characters): name: "https.443.https.devns.istio-system"
...
virtual_hosts {
  name: "x:443"
  domains: "x"
  routes {
    match {
      prefix: "/"
      case_sensitive {
        value: true
      }
      headers {
        name: "appkey"
        string_match {
          prefix: ""
        }
      }
    }
    route {
      cluster: "outbound|8080||nexus.nexus.svc.cluster.local"
      timeout {
      }
...
```

Based on the feedback I have gathered, this was implemented partly due to the VirtualService spec documentation, which I think leads in this direction. Could there be something missing when testing for present headers?:
> The header keys must be lowercase and use hyphen as the separator, e.g. x-request-id.
> 
> Header values are case-sensitive and formatted as follows:
> - exact: "value" for exact string match
> - prefix: "value" for prefix-based match
> - regex: "value" for RE2 style regex-based match (https://github.com/google/re2/wiki/Syntax).
> 
> If the value is empty and only the name of header is specified, presence of the header is checked. Note: The keys uri, scheme, method, and authority will be ignored.

This got a lot bigger of an issue for us, since a ingress gateway scaled up and started without configuration, which cased a whole lot of 404's/service outage.
This is not the only issue we have seen where the admission webhook allows virtualservice configuration that cases a broken envoy configuration. A good example of this (which we now validate on our own in our ci pipeline) is where a regex match is present that is not valid re2.

### Version

```prose
$ istioctl version
client version: 1.17.1
control plane version: 1.17.2
data plane version: 1.17.2 (13 proxies)

$ kubectl version --short
Client Version: v1.24.7
Kustomize Version: v4.5.4
Server Version: v1.25.6-eks-48e63af
```

### Affected product area

- [ ] Ambient
- [X] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by peterj** [comment]
The way to check for presence is like this:

```yaml
  - match:
    - headers:
        appkey:
          prefix: {}
```

This should be clarified in the docs.
