### ISSUE TITLE
Upgrade to 1.16.4 (from 1.15.7) results in missing clusters in gateway proxies.

### ISSUE THREAD

**Issue by janzantinge** [istio/istio#44439]
### Bug Description

Upgrading the control plane in our cluster to 1.16.4 has resulted in the gateway proxies missing cluster configuration. The listener and route configuration is all there though. This causes the proxies to respond with `503` `NC` for every request they receive.

Every version of Istio 1.15 seems to be fine and every version after 1.16 seems to be affected. The gateway proxy version doesn't seem to matter, only that of the control plane. Downgrading the control plane to some version prior to 1.16 will always resolve the issue. The networking configuration (ie VirtualServices, ServiceEntries, Gateways) did not change during upgrades (nor downgrades).

The `PILOT_FILTER_GATEWAY_CLUSTER_CONFIG` is set to `true`. Setting it to `false` does result in the affected gateway proxies receiving _all_ clusters.

The affected gateways have VirtualServices bound to them, some of which exist in namespaces other than the gateway proxy deployment's namespace. These VirtualServices use delegates and explicitly export to `*` (as seen below):
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: moe-mesh
  namespace: moe
spec:
  exportTo:
  - '*'
  gateways:
  - mesh
  - moe-ingressgateway
  - trogdor-ingress/trogdor-ingress
  hosts:
  - moe.mesh.example.com
  http:
  - delegate:
      name: moe-base
      namespace: moe
```
If the `exportTo` field is removed, the Istio control plane will send the cluster configuration to the gateway proxies fixing the issue. The default visibility is public which makes sense. Exporting to the gateway's namespace also fixes the problem. The docs say the `*` value should also result in public visibility still though.

Below is the delegate VirtualService:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: moe-base
  namespace: moe
spec:
  exportTo:
  - '*'
  http:
  - route:
    - destination:
        host: moe.us-east-1.mesh.example.com
      weight: 0
    - destination:
        host: moe-mesh.moe.svc.cluster.local
      weight: 100
```

And this is the Istio Gateway resource:
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: trogdor-ingress
  namespace: trogdor-ingress
spec:
  selector:
    app: trogdor-ingress
  servers:
  - hosts:
    - '*'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      caCertificates: /etc/secrets/ssl/certificate_authority.pem
      maxProtocolVersion: TLSV1_2
      minProtocolVersion: TLSV1_2
      mode: MUTUAL
      privateKey: /etc/secrets/ssl/tls.key
      serverCertificate: /etc/secrets/certs/tls.crt
```

### Version

```prose
$ istioctl version
client version: 1.16.4
control plane version: 1.16.4
data plane version: 1.14.1 (3 proxies), 1.15.4 (35 proxies), 1.16.4 (43 proxies)
$ kubectl version --short
Client Version: v1.23.3
Server Version: v1.24.10-eks-48e63af
```

### Additional Information

Cluster configuration output from an affected gateway proxy pod:
```
❯ istioctl pc cluster -n trogdor-ingress trogdor-ingress-6f689969fb-sblbk
SERVICE FQDN         PORT     SUBSET     DIRECTION     TYPE           DESTINATION RULE
BlackHoleCluster     -        -          -             STATIC
agent                -        -          -             STATIC
datadog_agent        -        -          -             STRICT_DNS
prometheus_stats     -        -          -             STATIC
sds-grpc             -        -          -             STATIC
xds-grpc             -        -          -             STATIC
```

Route configuration from the same affected pod:
```
❯ istioctl pc route -n trogdor-ingress trogdor-ingress-6f689969fb-sblbk
NAME                                                DOMAINS                                                                                                                                                 MATCH                  VIRTUAL SERVICE
https.443.https.trogdor-ingress.trogdor-ingress     curly-joe.mesh.example.com.global, curly-joe.mesh.example.com + 3 more...                                 /*                     curly-joe-mesh.curly-joe
https.443.https.trogdor-ingress.trogdor-ingress     istio-tester.mesh.example.com.global, istio-tester.mesh.example.com + 3 more...                           /*                     istio-tester-mesh.istio-tester
...
https.443.https.trogdor-ingress.trogdor-ingress     larry.mesh.example.com.global, larry.mesh.example.com + 3 more...                                         /*                     larry-mesh.larry
...
https.443.https.trogdor-ingress.trogdor-ingress     moe.mesh.example.com.global, moe.mesh.example.com + 3 more...                                             /*                     moe-mesh.moe
...
/healthz/ready*                                     *
/stats/prometheus*                                  * 
```

Cluster configuration when the `exportTo` is removed:
```
❯ istioctl pc cluster -n trogdor-ingress trogdor-ingress-6f689969fb-sblbk
SERVICE FQDN                                                     PORT     SUBSET     DIRECTION     TYPE           DESTINATION RULE
BlackHoleCluster                                                 -        -          -             STATIC
agent                                                            -        -          -             STATIC
datadog_agent                                                    -        -          -             STRICT_DNS
moe-canary.moe.svc.cluster.local                                 80       -          outbound      EDS
moe-mesh.moe.svc.cluster.local                                   80       -          outbound      EDS            moe.moe
moe.us-east-1.mesh.example.com                                   80       -          outbound      STRICT_DNS     istio-multicluster-ingressgateway.istio-system
prometheus_stats                                                 -        -          -             STATIC
sds-grpc                                                         -        -          -             STATIC
xds-grpc                                                         -        -          -             STATIC
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [X] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
