### ISSUE TITLE
Gateway API relies on version-specific backend service definitions for the route targets, the configuration model is inconsistent with istio's multi version model which use subsets select different instances of same service

### ISSUE THREAD

**Issue by idouba** [istio/istio#44446]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
AS[ gateway-api](https://istio.io/latest/blog/2022/getting-started-gtwapi/#configure-weight-based-version-routing) case described，User need build 2 service helloworld-v1 and helloworld-v2 for each version as route targets of helloworld.

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: helloworld
spec:
  parentRefs:
  - name: sample-gateway
    namespace: sample-ingress
  hostnames: ["helloworld.sample.com"]
  rules:
  - matches:
    - path:
        type: Exact
        value: /hello
    backendRefs:
    - name: helloworld-v1
      port: 5000
      weight: 90
    - name: helloworld-v2
      port: 5000
      weight: 10
```
Compared with Istio [multi-version case](https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRouteDestination), each routing rule of VS is associated with one or more service versions,which is defined by subsets in DR

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews-route
spec:
  hosts:
  - reviews.prod.svc.cluster.local
  http:
  - route:
    - destination:
        host: reviews.prod.svc.cluster.local
        subset: v2
      weight: 25
    - destination:
        host: reviews.prod.svc.cluster.local
        subset: v1
      weight: 75


apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews-destination
spec:
  host: reviews.prod.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
 ```
And make ingress route rule incompatible with which within mesh, and is incompatible with Service and workload & instances model, especially for the service accessed from both gateway and other service within mesh, one service or several version-specific service.

[backendRefs in gateway API ](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.HTTPRouteRule)shows several different HTTPBackendRef

- Support: Core for Kubernetes Service
- Support: Extended for Kubernetes ServiceImport
- Support: Implementation-specific for any other resource
- Support for weight: Core

Does Istio provide one implementation to support subset like backend?

The  current gateway-api to istio resource [conversion ](https://github.com/istio/istio/blob/dd90c85346965f13aa83ff41a1e34a14f1d31480/pilot/pkg/config/kube/gateway/conversion.go#L881)only convert HTTPBackendRef to Destination{host, port} ，and subset Not included.

**Describe alternatives you've considered**
Istio provide one subset like backend HTTPBackendRef implementation, and support route to multi-version backend of same service, make ingress traffic rules share the same semantics and model. Since Istio users are used to one service multi-version model instead of multi-service model. 

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
