### ISSUE TITLE
Layering AuthorizationPolicies with waypoint proxies in ambient

### ISSUE THREAD

**Issue by peterj** [istio/istio#44458]
### Bug Description

How does the layering work (or should work) when there are AuthorizationPolicies applied at multiple levels (global, namespace, workload) using a namespace-scoped waypoint proxy?

I tried three different scenarios, all using the namespace-scoped waypoint proxy. When using global and namespace-scoped AuthorizationPolicies together, the waypoint proxy correctly enforced them. However, when a workload-scoped policy gets added to the mix, it's not being enforced (the previous two policies are still enforced, but not the workload-scoped one).  

Even if I deploy a service account based waypoint proxy, the last policy is not enforced. My expectation would be that the policy gets enforce (either at the namespace waypoint or at the more specific service account waypoint).

**Repo steps**

1. Deploy httpbin-1 and httpbin-2 workloads to `default` namespace, deploy sleep to `second` namespace (attached workloads.yaml file)
2. Deploy the namespace scoped waypoint proxy:
```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: namespace
  namespace: default
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - name: mesh
    port: 15008
    protocol: ALL
``` 
3. Apply the global & namespace scoped policy:

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: global-policy
 namespace: istio-system
spec:
 action: DENY
 rules:
 - from:
   - source:
       principals: ["cluster.local/ns/second/sa/sleep"]
   to:
   - operation:
         methods: ["GET"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: ns-policy
 namespace: default
spec:
 action: DENY
 rules:
 - from:
   - source:
       principals: ["cluster.local/ns/second/sa/sleep"]
   to:
   - operation:
         methods: ["POST"]
```

4. At this point, GET and POST requests from the `sleep` workload will be denied. DELETE request will work for example.
5. Deploy the workload policy:

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: httpbin-2-policy
 namespace: default 
spec:
 action: DENY
 selector:
    matchLabels:
        app: httpbin-2
 rules:
 - from:
   - source:
       principals: ["cluster.local/ns/second/sa/sleep"]
   to:
   - operation:
         methods: ["DELETE"]
```

At this point, I would expect that DELETE request to httpbin-2 would be denied, but it isn't. Similarly, if you deploy a waypoint proxy for the httpbin-2 service account, it's the same behavior - the request is not denied. Note that the previous two policies are still being enforced; ztunnel has all three policies in its config, however the service account waypoint only has the first two policies (global and namespace).  

### Version

```prose
❯  ./istioctl version
client version: 1.18.0-alpha.0
control plane version: 1.18.0-alpha.0
data plane version: 1.18.0-alpha.0 (5 proxies)
```

### Affected product area

- [X] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [X] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
