### ISSUE TITLE
Local rate limit with descriptors not working as expected.

### ISSUE THREAD

**Issue by mosakashaka** [istio/istio#44496]
### Bug Description

I deployed a test web server which just offer two endpoints: `/mesh/foo` and `/mesh/bar`.
I want to use `local ratelimit` to limit `/mesh/bar` to 1 per 40s with descriptors. 
And I also configure a route scope rate limit as 10 per 40s.

I read ralated issues and realize that if a descriptor matches, not only its bucket will be consumed, the route bucket will also be consumed. 

**expeted behaviour**
Within 40 seconds, only 1 request to `/mesh/bar` will succeed, others will be rate limited.
9 requests to `/mesh/foo` will succeed, others will be rate limited.

**observed behaviour**
 1 request to `/mesh/bar` succeed, others are rate limited. (This is correct)
Only 5 requests to `/mesh/foo`  success, others are rate limited.

I also tried observe the stats `envoy_http_local_rate_limiter_route_http_local_rate_limit_ok` emitted on  `Prometheus` dashboard.
Every 40 seconds, it's increaed by 6 rather than 10.

Here is my `EnvoyFilter` config:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-local-ratelimit-svc
  namespace: default
spec:
  workloadSelector:
    labels:
      app: restdemo
      version: v2
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          portNumber: 8080
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter
    - applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_INBOUND
        routeConfiguration:
          portNumber: 8080
          vhost:
            name: "inbound|http|8080"         
      patch:
        operation: MERGE
        value:
          route:
            rate_limits:
            - actions:
              - request_headers:
                  header_name: :path
                  descriptor_key: path
          typed_per_filter_config:
            envoy.filters.http.local_ratelimit:
              "@type": type.googleapis.com/udpa.type.v1.TypedStruct
              type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
              value:
                stat_prefix: http_local_rate_limiter_route
                token_bucket:
                  max_tokens: 10
                  tokens_per_fill: 10
                  fill_interval: 40s
                filter_enabled:
                  runtime_key: local_rate_limit_enabled
                  default_value:
                    numerator: 100
                    denominator: HUNDRED
                filter_enforced:
                  runtime_key: local_rate_limit_enforced
                  default_value:
                    numerator: 100
                    denominator: HUNDRED
                descriptors:
                - entries:
                  - key: path
                    value: /mesh/bar
                  token_bucket:
                    max_tokens: 1
                    tokens_per_fill: 1
                    fill_interval: 40s   
```

Here is my deployment config.

```yaml
##################################################################################################
# restdemo service
##################################################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: restdemo
---
apiVersion: v1
kind: Service
metadata:
  name: restdemo
  labels:
    app: restdemo
    service: restdemo
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: restdemo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restdemo
      version: v2
  template:
    metadata:
      labels:
        app: restdemo
        version: v2
      annotations:
        proxy.istio.io/config: |-
          proxyStatsMatcher:
            inclusionRegexps:
            - ".*http_local_rate_limit.*"
            - "cluster.*.outlier_detection.*"
    spec:
      serviceAccountName: restdemo
      containers:
      - image: demo:v2
        imagePullPolicy: IfNotPresent
        name: restdemo
        ports:
        - containerPort: 8080

```

### Version

```Text
# istioctl version
client version: 1.17.2
control plane version: 1.17.2
data plane version: 1.17.2 (9 proxies)

# kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.8+k3s1
Kustomize Version: v4.5.7
Server Version: v1.25.8+k3s1
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
