### ISSUE TITLE
Consider replacing distroless fork with apko

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#44510]
```yaml
contents:
  repositories:
    - https://packages.wolfi.dev/os
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
    - ca-certificates-bundle
    - glibc
    - iptables
    - wolfi-baselayout
archs:
  - x86_64
  - aarch64
paths:
- path: /run
  type: directory
  permissions: 0o755
accounts:
  users:
    - username: nobody
      uid: 65532
    - username: nobody
      uid: 65534
  run-as: 65532
work-dir: /home/nonroot
```

I think we need a few extra libraries to get it to work, but its a *lot* simpler than the distroless bazel mess
