### ISSUE TITLE
Support  dynamic destination under a single route

### ISSUE THREAD

**Issue by zengyuxing007** [istio/istio#44518]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

There are some cases that I tried to illustrate with some yaml examples.

Example1 :  subset is a variable,  and the subset may be different for different requests.

```yaml

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: example-app
  namespace: default
spec:
  hosts:
    - example
  http:
  - route:
    - destination:
        host: example
        subset: $userdefine_label1

```

Example2 :    when the v1  group does not exist or  all instances under this group are not available, the request will be fallback to the base group

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: example-app
  namespace: default
spec:
  hosts:
    - example
  http:
  - route:
    - destination:
        host: example
        subset: v1
      fallback:
        host: example
        subset: base
```

If it makes sense, I would be glad to submit a proposal and implementation.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

- [ ] Ambient
- [X] Docs
- [X] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
