### ISSUE TITLE
gateway-api: add timeouts and retries support

### ISSUE THREAD

**Issue by frankbu** [istio/istio#44571]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

Given that Istio plans to make Gateway API the default API for traffic management in the future, there are several missing Istio features that need to be supported in the Gateway API implementation. Currently, the only way to support them is by providing Istio implementation-specific extensions to Gateway API.

Timeouts and retries are two examples, so we can start by supporting them with a new Istio ExtensionRef kind something like this:

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: reviews
spec:
  parentRefs:
  - kind: Service
    name: reviews
    port: 9080
  rules:
  - filters:
    - type: ExtensionRef
      extensionRef:
        group: networking.istio.io/v1beta1
        kind: K8sRouteExtension
        name: reviews
    backendRefs:
    - name: reviews-v1
      port: 9080
---
apiVersion: networking.istio.io/v1beta1
kind: K8sRouteExtension
metadata:
  name: reviews
spec:
  timeout: 10s
  retries:
    attempts: 3
    perTryTimeout: 2s
    retryOn: connect-failure,refused-stream,503
```

**Describe alternatives you've considered**

Work with the `kubernetes.sigs/gateway-api` community to add first class support for these features, although that would probably be better as a followup, after we've successfully implemented them as extensions first.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[x] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
