### ISSUE TITLE
error handling istio-ca-root-cert when Install multiple Istio

### ISSUE THREAD

**Issue by ZLBer** [istio/istio#44600]
### Bug Description

I deploy multiple isitods in the same k8s cluster, refer to the following document
https://istio.io/latest/docs/setup/install/multiple-controlplanes/  

When I installed two, everything was fine. but when I install to three, some errors appear in the log

```
2023-04-27T06:11:08.033331Z     error   controllers     error handling istio-system-03/istio-ca-root-cert, and retry budget exceeded: error when updating configmap istio-ca-root-cert: Operation cannot be fulfilled on configmaps "istio-ca-root-cert": the object has been modified; please apply your changes to the latest version and try again controller=namespace controller
2023-04-27T06:11:08.135477Z     error   controllers     error handling istio-system-02/istio-ca-root-cert, and retry budget exceeded: error when updating configmap istio-ca-root-cert: Operation cannot be fulfilled on configmaps "istio-ca-root-cert": the object has been modified; please apply your changes to the latest version and try again controller=namespace controller
```
is it a bug for v1.14? how to resolve this problem？

### Version

```Text
$ istioctl version 
client version: 1.14.0
control plane version: 1.14.0
data plane version: none
$ kubectl version --short
Client Version: v1.24.3
Kustomize Version: v4.5.4
Server Version: v1.23.0
```

### Additional Information

the installation files are as follows，same like istio-system-01, istio-system-02, istio-system-03
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system-03
spec:
  profile: minimal
  revision: istio-system-03
  meshConfig:
    discoverySelectors:
      - matchLabels:
          usergroup: istio-system-03
    accessLogFile: "/dev/stdout"
    defaultConfig:
      controlPlaneAuthPolicy: NONE
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
  values:
    global:
      istioNamespace: istio-system-03
    pilot:
      env:
        XDS_AUTH: false
        ENABLE_ENHANCED_RESOURCE_SCOPING: true
        PILOT_ENABLE_XDS_IDENTITY_CHECK: false
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [X] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio
