### ISSUE TITLE
Grpc with sidecar will Received unexpected EOS on DATA frame from server

### ISSUE THREAD

**Issue by id-id-id** [istio/istio#44606]
### Bug Description

we have a server(have sidecar) in k8s and expose grpc ports through the istio-ingressgateway. A client in another k8s with sidecar send a grpc request to the server. Grpc request accesses the server through istio-ingressgateway but client error log show  Received unexpected EOS on DATA frame from server。

when we use server.namespace.svc.local to send grpc request, it will work normal.

server istio.yaml
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: server-gw
  namespace: server
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 21885  # aps1 gRPC internal: aws internal network access
        name: grpc-aps1
        protocol: GRPC
      hosts:
        - server.xxx.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: server-vs
  namespace: server
spec:
  gateways:
    - server-gw
  hosts:
    - server.xxx.com
  http:
    - match:
        - uri:
            prefix: /
          port: 21885
      route:
        - destination:
            host: server
            port:
              number: 8850 # {service.port.gRPC}
``` 
istio-ingressgateway yaml
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    region: aps1
    release: istio
  name: internal-ingressgateway
  namespace: istio-system
spec:
  ports:
  - name: grpc
    nodePort: 31255
    port: 8850
    protocol: TCP
    targetPort: 21885
  selector:
    app: istio-ingressgateway
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: xxx.com
``` 
server service.yaml
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: server
  name: server
  namespace: server
spec:
  ports:
  - name: grpc
    port: 8850
    protocol: TCP
    targetPort: grpc
  selector:
    app.kubernetes.io/name: server
  sessionAffinity: None
  type: ClusterIP
``` 

We find that in istio ingress gateway log, request show protocol is HTTP/1.1 but we find in proxy, request protocol is HTTP/2.
Server can receiver request and deal with it correctlly, but response client get missing a peace of data.
left is server, right is package client receive
![image](https://user-images.githubusercontent.com/49929614/236396858-985256c4-361b-4aa3-8ac0-09de1f758e10.png)

### Version

```Text
istioctl version:
client version: 1.16.2
control plane version: 1.16.2
data plane version: 1.16.2 (163 proxies), 999.0.0 (1 proxies)

kubectl version --short:
Client Version: v1.23.0
Server Version: v1.24.10-eks-48e63af
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
