### ISSUE TITLE
Ingress route mapping coupled with other HTTP match conditions，brings duplication and redundancy in gateway-api

### ISSUE THREAD

**Issue by idouba** [istio/istio#44621]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Similar to scenario described in https://github.com/istio/istio/issues/6070 ，
```
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: svc1-v1
spec:
  parentRefs:
  - kind: Gateway
    name: internal-http
  hostnames:
  - "app.demo.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /p1   //duplicated url mappings coupling with canary condition.
    - headers:
      - type: Exact
        name: env
        value: canary
    backendRefs:
    - kind: Service
      name: svc1-v1
      port: 8080


kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: svc1-v2
spec:
  parentRefs:
  - kind: Gateway
    name: internal-http
  hostnames:
  - "app.demo.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /p1   //duplicated url mappings
    backendRefs:
    - kind: Service
      name: svc1-v2
      port: 8080
      
      
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: svc2
spec:
  parentRefs:
  - kind: Gateway
    name: internal-http
  hostnames:
  - "app.demo.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /p2
    backendRefs:
    - kind: Service
      name: svc2
      port: 8080
```
Svc1 and svc2 are both published in gateway by the same domain name "app.demo.com", and accessed by different path mappings, /p1 to svc1, and /p2 to svc2. 

url mappings are mixed with other match conditions in svc1’s HTTP route. In svcs’s canary cases, the same url mappings should be included in every svc1 route. Make it hard to modify both the url mappings and canary conditions.

It is better to decouple ingress url mapping and other http match conditions.

**Describe alternatives you've considered**

Consider introduce another HTTPRoute  implementation for backendRefs. The following root HTTP route is responsible for ingress. and the  backendRefsed delegate HTTP describe the traffic route of service own.   and gateway controller merge the route like  [VS delegate ](https://github.com/istio/istio.io/pull/7383)

```
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: app-ingress
spec:
  parentRefs:
  - kind: Gateway
    name: internal-http
  hostnames:
  - "app.demo.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /p1
    backendRefs:
    - kind: HTTPRoute   //delegate to another httproute
      name: svc1-route
  - matches:
    - path:
        type: PathPrefix
        value: /p2
    backendRefs:
    - kind: HTTPRoute  //delegate to another httproute
      name: svc2-route
 ```
     
```
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: svc1-route
spec:
  parentRefs:
  - kind: Gateway
    name: internal-http
  hostnames:
  - "app.demo.com"
  rules:
  - matches:
    - headers:
      - type: Exact
        name: env
        value: canary
    backendRefs:
    - kind: Service
      name: svc1-v1
      port: 8080
  - backendRefs:
    - kind: Service
      name: svc1-v2
      port: 8080

kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: svc2-route
spec:
  parentRefs:
  - kind: Gateway
    name: internal-http
  hostnames:
  - "app.demo.com"
  rules:
  - backendRefs:
    - kind: Service
      name: svc2
      port: 8080
```

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
