### ISSUE TITLE
L4 authorization policy not applied if waypoint is present

### ISSUE THREAD

**Issue by npolshakova** [istio/istio#44671]
### Bug Description

**Scenario:**
When a waypoint is created and an L4 policy exists, the policy is no longer enforced correctly until the waypoint is removed or the selector labels on the policy are changed to select the waypoint. 

**How to reproduce:**

Create an L4 policy: 

```
kubectl apply -f - <<EOF
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: ratings-access
 namespace: bookinfo
spec:
 selector:
   matchLabels:
     app: ratings
 action: ALLOW
 rules:
 - from:
   - source:
       principals:
       - cluster.local/ns/bookinfo/sa/bookinfo-productpage
EOF
```

Everything works as expected:

```
curl ratings:9080/ratings/1
curl: (56) Recv failure: Connection reset by peer
```

Create a waypoint:

```
kubectl apply -f - <<EOF
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: ratings
  namespace: bookinfo
  annotations:
    istio.io/for-service-account: bookinfo-ratings
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - allowedRoutes:
      namespaces:
        from: Same
    name: mesh
    port: 15008
    protocol: HBONE
EOF
```

Now the traffic is not blocked:

```
$ curl ratings:9080/ratings/1
{"id":1,"ratings":{"Reviewer1":5,"Reviewer2":4}}/
```

But the policy is present on the ztunnel: 

```
    "policies":{
       "bookinfo/ratings-access":{
          "name":"ratings-access",
          "namespace":"bookinfo",
          "scope":"WorkloadSelector",
          "action":"Allow",
          "groups":[
             [
                [
                   {
                      "principals":[
                         {
                            "Exact":"cluster.local/ns/bookinfo/sa/bookinfo-productpage"
                         }
                      ]
                   }
                ]
             ]
          ]
       }
    },
```

After deleting the Gateway, the waypoint is cleaned up and the L4 authorization policy is applied correctly again: 

```
$ curl ratings:9080/ratings/1
curl: (56) Recv failure: Connection reset by peer
```

### Version

```Text
❯ istioctl version
client version: 1.18.0-alpha.0
control plane version: 1.18.0-alpha.0
data plane version: 1.18.0-alpha.0 (4 proxies)
```

### Affected product area

- [X] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
