### ISSUE TITLE
VirtualService with regex match casues envoy validation error

### ISSUE THREAD

**Issue by maya-aravot** [istio/istio#44693]
### Bug Description

When a VirtualService tries to use regex for route matching, it gets a validation error:
```
2023-05-01T08:26:29.862785Z	warn	ads	ADS:RDS: ACK ERROR kafdrop-main-istio-ingressgateway-57d76c9c46-s2nzg.data-1975 Internal:Proto constraint validation failed (RouteConfigurationValidationError.VirtualHosts[0]: embedded message failed validation | caused by VirtualHostValidationError.Routes[0]: embedded message failed validation | caused by RouteValidationError.Match: embedded message failed validation | caused by RouteMatchValidationError.SafeRegex: embedded message failed validation | caused by field: "engine_type", reason: is required): name: "http.8080"
virtual_hosts {
  name: "kafdrop-main.playground.domain.com:80"
  domains: "kafdrop-main.playground.domain.com"
  domains: "kafdrop-main.playground.domain.com:*"
  routes {
    match {
      case_sensitive {
        value: true
      }
      safe_regex {
        regex: "/topic/.*/delete"
      }
    }
    route {
      cluster: "outbound|80||noservice.data.svc.cluster.local"
      timeout {
      }
      retry_policy {
        retry_on: "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes"
        num_retries {
          value: 2
        }
        retry_host_predicate {
          name: "envoy.retry_host_predicates.previous_hosts"
          typed_config {
            [type.googleapis.com/envoy.extensions.retry.host.previous_hosts.v3.PreviousHostsPredicate] {
            }
          }
        }
        host_selection_retry_max_attempts: 5
        retriable_status_codes: 503
      }
      max_grpc_timeout {
      }
    }
    metadata {
      filter_metadata {
        key: "istio"
        value {
          fields {
            key: "config"
            value {
              string_value: "/apis/networking.istio.io/v1alpha3/namespaces/data/virtual-service/kafdrop-main-istio-ingressgateway-vs"
            }
          }
        }
      }
    }
    decorator {
      operation: "noservice.data.svc.cluster.local:80/topic/.*/delete"
    }
    request_headers_to_add {
      header {
        key: "X-FORWARDED-PROTO"
        value: "https"
      }
      append {
      }
    }
    request_headers_to_add {
      header {
        key: "x-request-start"
        value: "t=%START_TIME(%s.%3f)%"
      }
      append {
        value: true
      }
    }
    response_headers_to_remove: "x-envoy-upstream-healthchecked-cluster"
    response_headers_to_remove: "x-envoy-upstream-service-time"
  }
  routes {
    match {
      prefix: "/topic/create"
      case_sensitive {
        value: true
      }
    }
    route {
      cluster: "outbound|80||noservice.data.svc.cluster.local"
      timeout {
      }
      retry_policy {
        retry_on: "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes"
        num_retries {
          value: 2
        }
        retry_host_predicate {
          name: "envoy.retry_host_predicates.previous_hosts"
          typed_config {
            [type.googleapis.com/envoy.extensions.retry.host.previous_hosts.v3.PreviousHostsPredicate] {
            }
          }
        }
        host_selection_retry_max_attempts: 5
        retriable_status_codes: 503
      }
      max_grpc_timeout {
      }
    }
    metadata {
      filter_metadata {
        key: "istio"
        value {
          fields {
            key: "config"
            value {
              string_value: "/apis/networking.istio.io/v1alpha3/namespaces/data/virtual-service/kafdrop-main-istio-ingressgateway-vs"
            }
          }
        }
      }
    }
    decorator {
      operation: "noservice.data.svc.cluster.local:80/topic/create*"
    }
    request_headers_to_add {
      header {
        key: "X-FORWARDED-PROTO"
        value: "https"
      }
      append {
      }
    }
    request_headers_to_add {
      header {
        key: "x-request-start"
        value: "t=%START_TIME(%s.%3f)%"
      }
      append {
        value: true
      }
    }
    response_headers_to_remove: "x-envoy-upstream-healthchecked-cluster"
    response_headers_to_remove: "x-envoy-upstream-service-time"
  }
  routes {
    match {
      prefix: "/"
      case_sensitive {
        value: true
      }
    }
    route {
      cluster: "outbound|9000||kafdrop-...(truncated)
```
VirtualService yaml:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kafdrop-main-istio-ingressgateway-vs
  namespace: data
spec:
  gateways:
    - kafdrop-main-istio-ingressgateway
  hosts:
    - kafdrop-main.playground.domain.com
  http:
    - headers:
        request:
          add:
            x-request-start: t=%START_TIME(%s.%3f)%
          set:
            X-FORWARDED-PROTO: https
        response:
          remove:
            - x-envoy-upstream-healthchecked-cluster
            - x-envoy-upstream-service-time
      match:
        - uri:
            regex: /topic/.*/delete
      route:
        - destination:
            host: noservice.data.svc.cluster.local
            port:
              number: 80
    - headers:
        request:
          add:
            x-request-start: t=%START_TIME(%s.%3f)%
          set:
            X-FORWARDED-PROTO: https
        response:
          remove:
            - x-envoy-upstream-healthchecked-cluster
            - x-envoy-upstream-service-time
      match:
        - uri:
            prefix: /topic/create
      route:
        - destination:
            host: noservice.data.svc.cluster.local
            port:
              number: 80
    - headers:
        request:
          add:
            x-request-start: t=%START_TIME(%s.%3f)%
          set:
            X-FORWARDED-PROTO: https
        response:
          remove:
            - x-envoy-upstream-healthchecked-cluster
            - x-envoy-upstream-service-time
      match:
        - uri:
            prefix: /
      route:
        - destination:
            host: kafdrop-main.data.svc.cluster.local
            port:
              number: 9000
```

After changing the regex to be prefix it worked, but it needs to be regex..
```
prefix: /topic
```

### Version

```Text
istioctl version
client version: 1.17.1
control plane version: 1.17.1
data plane version: 1.17.1 (22 proxies)

kubectl version 
Client Version: v1.24.8
Kustomize Version: v4.5.4
Server Version: v1.25.8-eks-ec5523e
```

### Affected product area

- [ ] Ambient
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [X] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
