### ISSUE TITLE
To run EnvoyProxy as Edge Proxy on VM with the help of Istio Control Plane

### ISSUE THREAD

**Issue by xyphanajay** [istio/istio#44700]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
We are trying to run Envoy Proxy as edge proxy on dedicated VMs for inbound traffic. We want to run it as main process not as sidecar/proxy approach. A control plane running inside kubernetes cluster can push the desired configuration to the envoy proxy running as dedicated Load Balancer and populate upstream cluster endpoints as per the config requirement.

**Describe alternatives you've considered**
We tried existing Istio VM setup but that is tweaking IP table routes and routing all port traffic to envoy proxy (acting as a proxy for any application running on the VM). Our infra is latency centric and running envoy proxy as VM mode is adding unnecessary latency.

We are explore Gloo Edge but that doesn't support the features of envoy proxy which we are trying to configure and use.

At presenting, we are trying to create our own control plane to populate envoy proxy configuration running on the VM via ADS. 

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[x] Docs
[x] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[*] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by xyphanajay** [comment]
I had a discussion at Istio booth during EU Kubecon '23 and got to know that Istio does support this with a configurable flag but it is not documented.

**Comment by howardjohn** [comment]
https://blog.howardjohn.info/posts/local-gateway/ shows doing this. I think I was the one who talked with you at KubeCon and I still strongly recommend not running it in a VM

**Comment by xyphanajay** [comment]
Yes, we discussed this. I'll test it and get back to you. Thanks.

**Comment by xyphanajay** [comment]
@howardjohn I want to deploy istio ingress gateway in VMs while using istiod (running in the cluster) and doing all the discovery of backends.  VM as part of istio's official documentation assumes that there is some application running which needs to be part of the mesh. And the blog you share is deploying both istiod and gateway in the vm. 
Is it possible to make the envoy sidecar deployed in vm to act as reverse proxy of the traffic to cluster pods/services?

**Comment by howardjohn** [comment]
Just do half of the blog post and point it at Istiod running in cluster.

A gateway on VM vs sidecar on VM is really not very different. Just no iptables and `proxy router` as the args instead of `proxy sidecar`.

**Comment by anuragagarwal561994** [comment]
@howardjohn thanks for your help and blogpost, @xyphanajay and I worked together on your provided blogpost and was able to successfully link envoy on VM as a gateway to istod control plane sitting inside the kubernetes cluster.

May be this can be added as a documentation on the main istio website

**Comment by xyphanajay** [comment]
1. added the following variables in cluster.env to run proxy as router and for no iptable changes.
ISTIO_AGENT_FLAGS='router'
ISTIO_CUSTOM_IP_TABLES='true'

2. Now when I am writing a listener envoyfilter for http ports, envoyproxy is unable to bind these ports as it's not running as sudo. How can I enable envoy to bind http ports?

3. Also, when I'm registering multiple vms with same istioctl generated config files, I am getting the following error:
`
2023-09-05T09:17:39.043500Z     info    Pilot SAN: [istiod-1-16-1.istio-system.svc]
2023-09-05T09:17:39.044269Z     info    Starting proxy agent
2023-09-05T09:17:39.044292Z     info    starting
2023-09-05T09:17:39.044306Z     info    Envoy command: [-c etc/istio/proxy/envoy-rev.json --drain-time-s 45 --drain-strategy immediate --local-address-ip-version v4 --file-flush-interval-msec 1000 --disable-hot-restart --allow-unknown-static-fields --log
-format %Y-%m-%dT%T.%fZ %l      envoy %n %g:%#  %v      thread=%t -l warning --component-log-level misc:error]
2023-09-05T09:17:39.141264Z     error   citadelclient   Failed to load key pair open etc/certs/cert-chain.pem: no such file or directory
`

4. To avoid manual entry in /etc/hosts for resolving istiod, I want to use `istiod.srv.abc.com` which our internal DNS will resolve. But I saw that root-cert.pem is for cluster.local . Is it feasible what I'm trying to achieve here?

**Comment by howardjohn** [comment]
Either give it permissions (setcap, sudo, etc) or don't bind to ports <1024.

Istiod flag can set `ISTIOD_CUSTOM_HOST=istiod.srv.abc.com`

**Comment by xyphanajay** [comment]
On a different note, I am not able to see metrics for the listener or the cluster I am using to route the traffic to.
I checked both ports 15020/stats/prometheus and 15090/stats/prometheus for istio/envoy request metric.
I have applied the following filter to handle https requests and route them to the cluster which got registered after creating destination rule associated with it.
I am serving ~100 QPS with this listener but don't see any envoy/istio metrics.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: listener-https
  namespace: envoy
  labels:
    app: envoy
spec:
  workloadSelector:
    labels:
      app: envoy
  configPatches:
  - applyTo: LISTENER
    match:
      context: GATEWAY
    patch:
      operation: ADD
      value:
        name: "https_listener"
        address:
          socket_address:
            address: "0.0.0.0"
            port_value: 443
        filter_chains:
        - filters:
          - name: "envoy.filters.network.http_connection_manager"
            typed_config:
              "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
              codec_type: AUTO
              stat_prefix: envoy_https_ingress
              use_remote_address: true
              normalize_path: true
              merge_slashes: true
              path_with_escaped_slashes_action: UNESCAPE_AND_REDIRECT
              common_http_protocol_options:
                idle_timeout: 300s
                headers_with_underscores_action: REJECT_REQUEST
              http2_protocol_options:
                max_concurrent_streams: 100
                initial_stream_window_size: 65536
                initial_connection_window_size: 1048576
              stream_idle_timeout: 300s
              request_timeout: 300s
              generate_request_id: false # enable with tracing
              ## access log config
              access_log:
              - name: envoy.access_loggers.file
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                  path: "/var/log/istio/envoy-https.log"
              route_config:
                name: cluster_route
                request_headers_to_add:
                  - header:
                      key: X-Client-IP
                      value: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
                  - header: 
                      key: X-Request-Start
                      value: "%START_TIME(%s.%3f)%"
                virtual_hosts:
                - name: "local_hosts"
                  domains: 
                    - xyz.abc.com
                  routes:
                  - match:
                      prefix: "/xyz/"
                    route:
                      cluster: "outbound|7017|abc-envoy|abc-envoy.abc.svc.cluster.local"
                      timeout: 0.4s
                      max_stream_duration:
                        max_stream_duration: 0s
                  - match:
                      prefix: "/"
                    direct_response:
                      status: 204
              http_filters:
              # Decompressor filter
              - name: envoy.filters.http.decompressor
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.decompressor.v3.Decompressor
                  decompressor_library:
                    name: envoy.compression.gzip.decompressor
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.compression.gzip.decompressor.v3.Gzip
                  request_direction_config:
                    common_config:
                      enabled:
                        default_value: true
                        runtime_key: request_decompressor_enabled
              - name: envoy.filters.http.lua
                typed_config:
                  "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
                  default_source_code:
                    inline_string: |
                      function envoy_on_request(request_handle)
                        print("some lua logic")
                      end
              - name: "envoy.filters.http.router"
              ## for default response;
              local_reply_config:
                mappers:
                - filter:
                    status_code_filter:
                      comparison:
                        op: GE
                        value:
                          default_value: 300
                          runtime_key: "non_2xx_status_code"
                  status_code: 204
          transport_socket:
            name: "envoy.transport_sockets.tls"
            typed_config:
              "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext"
              common_tls_context:
                tls_certificates:
                  - certificate_chain: { filename: "/etc/certs/star.abc.com.crt" }
                    private_key: { filename: "/etc/certs/star.abc.com.key" }


```

**Comment by xyphanajay** [comment]
- After adding the following into /etc/istio/config/mesh I am able to get desired envoy metrics. I guess telemetry kind resources also do the same thing.
```
proxyStatsMatcher:
    inclusionRegexps:
      - "cluster.*.upstream_cx_total"
      - "cluster.*.upstream_cx_active"
      - "listener.*.downstream_cx_total"
      - "listener.*.downstream_cx_active"
    inclusionSuffixes:
      - "downstream_rq_total"
      - "downstream_rq_completed"
```

- cluster.local cert-chain generated by istio agent/pilot has expired and getting the following error. Is it expected to be auto renewed by the agents? Need help over here.
```
2023-09-06T13:29:58.605909Z     warn    xdsproxy        upstream [437] terminated with unexpected error rpc error: code = Unauthenticated desc = authentication failure
2023-09-06T13:30:02.933798Z     warn    cert expired, using token instead
```

**Comment by xyphanajay** [comment]
- Now suddenly envoy is dropping traffic with the following error
```
2023-09-07T16:23:25.434950Z     critical        envoy assert external/envoy/source/common/network/socket_interface_impl.cc:72   assert failure: SOCKET_VALID(result.return_value_). Details: socket(2) failed, got error: Too many open files   thread=20181
2023-09-07T16:23:25.435015Z     critical        envoy backtrace external/envoy/source/server/backtrace.h:104    Caught Aborted, suspect faulting address 0x3e500004ec2  thread=20181
2023-09-07T16:23:25.435023Z     critical        envoy backtrace external/envoy/source/server/backtrace.h:91     Backtrace (use tools/stack_decode.py to get line numbers):      thread=20181
2023-09-07T16:23:25.435025Z     critical        envoy backtrace external/envoy/source/server/backtrace.h:92     Envoy version: 3c27a1b0cf381ca854ccc3a2034e88c206928da2/1.26.4-dev/Clean/RELEASE/BoringSSL      thread=20181
[symbolize_elf.inc : 1000] RAW: /proc/self/task/20162/maps: errno=24
2023-09-07T16:23:25.435076Z     critical        envoy backtrace external/envoy/source/server/backtrace.h:98     #0: [0x7ff1d1c1f140]    thread=20181
```

**Comment by xyphanajay** [comment]
The above

> * Now suddenly envoy is dropping traffic with the following error
> 
> ```
> 2023-09-07T16:23:25.434950Z     critical        envoy assert external/envoy/source/common/network/socket_interface_impl.cc:72   assert failure: SOCKET_VALID(result.return_value_). Details: socket(2) failed, got error: Too many open files   thread=20181
> 2023-09-07T16:23:25.435015Z     critical        envoy backtrace external/envoy/source/server/backtrace.h:104    Caught Aborted, suspect faulting address 0x3e500004ec2  thread=20181
> 2023-09-07T16:23:25.435023Z     critical        envoy backtrace external/envoy/source/server/backtrace.h:91     Backtrace (use tools/stack_decode.py to get line numbers):      thread=20181
> 2023-09-07T16:23:25.435025Z     critical        envoy backtrace external/envoy/source/server/backtrace.h:92     Envoy version: 3c27a1b0cf381ca854ccc3a2034e88c206928da2/1.26.4-dev/Clean/RELEASE/BoringSSL      thread=20181
> [symbolize_elf.inc : 1000] RAW: /proc/self/task/20162/maps: errno=24
> 2023-09-07T16:23:25.435076Z     critical        envoy backtrace external/envoy/source/server/backtrace.h:98     #0: [0x7ff1d1c1f140]    thread=20181
> ```

This is happening due to socket exhaustion as we have high QPS served by this VM. We are optimizing by setting up TCP keepalive time and Http connections.

Thank you for helping out for setting up Istio VM as router.

**Comment by apsega** [comment]
@xyphanajay would you mind sharing Istio confings for running as a separate gateway on VM?

**Comment by xyphanajay** [comment]
You will need `workloadgroup.yaml` , `serviceaccount.yaml` present in the respective namespace. Post that I am using `kind: envoyfilter` for applying all the listener configuration. Envoy doesn't have permission to bind port 80, 443 so I run `sudo setcap cap_net_bind_service=+ep /usr/local/bin/envoy;` to allow it. I create Destination Rules for registering my services as cluster for istio.

EnvoyFilter-http.yaml
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: prod-listener-http
  namespace: envoy
  labels:
    app: istio
spec:
  workloadSelector:
    labels:
      app: istio
  configPatches:
  - applyTo: LISTENER
    match:
      context: GATEWAY
    patch:
      operation: ADD
      value:
        name: "http_listener"
        address:
          socket_address:
            address: "0.0.0.0"
            port_value: 80
        filter_chains:
        - filters:
          - name: "envoy.filters.network.http_connection_manager"
            typed_config:
              "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
              codec_type: AUTO
              stat_prefix: ingress             # gets appended to the metric name
              use_remote_address: true
              normalize_path: true
              merge_slashes: true
              path_with_escaped_slashes_action: UNESCAPE_AND_REDIRECT
              common_http_protocol_options:
                idle_timeout: 1s
                headers_with_underscores_action: REJECT_REQUEST
              http2_protocol_options:
                max_concurrent_streams: 100
                initial_stream_window_size: 65536
                initial_connection_window_size: 1048576
              stream_idle_timeout: 1s
              request_timeout: 2s
              delayed_close_timeout: 1s
              generate_request_id: false # enable with tracing
              ## access log config
              route_config:
                name: cluster_route
                request_headers_to_add:
                  - header:
                      key: X-Client-IP
                      value: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
                  - header: 
                      key: X-Proxy
                      value: "envoy"
                  - header: 
                      key: X-Request-Start
                      value: "%START_TIME(%s.%3f)%"
                virtual_hosts:
                - name: "dummy_hosts"
                  routes:
                  - match:
                      prefix: "/abc/"
                    route:
                      cluster: "outbound|7017|abc-common|common.abc.svc.cluster.local" # this is destination rule name followed by kubernetes service name
                      # timeout: 1s
                  - match:
                      prefix: "/"
                    direct_response:
                      status: 204
              http_filters:
              # Decompressor filter
              - name: envoy.filters.http.decompressor
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.decompressor.v3.Decompressor
                  decompressor_library:
                    name: small
                    typed_config:
                      "@type": "type.googleapis.com/envoy.extensions.compression.gzip.decompressor.v3.Gzip"
                      window_bits: 9
                      chunk_size: 8192
                  response_direction_config:
                    common_config:
                      enabled:
                        default_value: false
                        runtime_key: response_decompressor_enabled
              - name: envoy.filters.http.compressor
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor
                  request_direction_config:
                    common_config:
                      enabled:
                        default_value: false
                        runtime_key: request_compressor_enabled
                  compressor_library:
                    name: for_response
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.compression.gzip.compressor.v3.Gzip
                      memory_level: 3
                      window_bits: 10
                      compression_level: BEST_COMPRESSION
              - name: envoy.filters.http.lua
                typed_config:
                  "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
                  default_source_code:
                    inline_string: |
                      function envoy_on_request(request_handle)
                        -- some lua logic
                      end
              - name: "envoy.filters.http.router"
              ## for 204 response; but does not work for some reason
              local_reply_config:
                mappers:
                - filter:
                    status_code_filter:
                      comparison:
                        op: GE
                        value:
                          default_value: 300
                          runtime_key: "non_2xx_status_code"
                  status_code: 204
                - filter:
                    status_code_filter:
                      comparison:
                        op: EQ
                        value:
                          default_value: 0
                          runtime_key: "zero_status_code"

```

**Comment by xyphanajay** [comment]
I am in process of using `kind: gateway` with `kind: VirtualService` for configuring listeners in Istio VM as router. But TLS is not working for some reason. 
You workloadgroup app label matters while applying any configuration for Istio VM as router.
`app=envoy` is my workloadgroup selector/identifier.

Gateway.yaml
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-tls-gateway
  namespace: envoy
spec:
  selector:
    app: envoy
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - example.com
    tls:
      mode: SIMPLE
      credentialName: star-exmaple # this must match the secret name
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - abc.com
    tls:
      mode: SIMPLE
      credentialName: star-abc # this must match the secret name
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - abc.com
```

Virtual service.yaml
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: abc-common-vs
  namespace: envoy
spec:
  hosts:
  - "abc.com"
  - "example.com"
  gateways:
  - my-tls-gateway
  http:
  - match:
    - uri:
        prefix: /abc/
    route:
    - destination:
        host: common.abc.svc.cluster.local
        subset: abc-common
```
The above configuration works for non TLS. While it was not working for me when secret is present in envoy NS or in istio-system NS.
