### ISSUE TITLE
Add new field to access_log is not friendly

### ISSUE THREAD

**Issue by johnzheng1975** [istio/istio#44721]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Current there is no GRPC_STATUS_NUMBER in access_log.
I need add it  friendly, thanks.

[Happy Case]
1. Change istio config map, add GRPC_STATUS_NUMBE
```
# k edit cm -n istio-system istio
# Change accessLogFormat
  mesh: |-
    accessLogFile: /dev/stdout
    accessLogFormat: "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% \"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME% %GRPC_STATUS_NUMBER%\n"
    defaultConfig:
```
2. View the log, the GRPC_STATUS_NUMBER  is added successfully.
```
### [2023-05-03T07:22:39.390Z] "POST /helloworld.Greeter/SayHello HTTP/2" 200 - via_upstream - "-" 12 18 22 21 "-" "grpc-go/1.37.1" "23a8cd6c-8eb8-43f6-ab4a-738a91fb15d5" "test:3000" "192.168.14.9:50051" outbound|3000||test.default.svc.cluster.local 192.168.24.83:57980 10.100.90.238:3000 192.168.24.83:51712 - default 0
### [2023-05-03T07:23:35.722Z] "POST /helloworld.Greeter/SayHello HTTP/2" 200 URX via_upstream - "-" 12 0 100 100 "-" "grpc-go/1.37.1" "f84b7c11-4233-41ec-9817-882453ccfc8c" "test:3000" "192.168.24.83:50051" outbound|3000||test.default.svc.cluster.local 192.168.24.83:53696 10.100.90.238:3000 192.168.24.83:52208 - default 14
```
However, there are two issue.
1. It is difficult to successful when accessLogEncoding: JSON, I added as below, not work.
```
apiVersion: v1
data:
  mesh: |-
    accessLogEncoding: JSON
    accessLogFile: /dev/stdout
    accessLogFormat: |
       {               
       "accessLogFormat": "{ 
            \"authority\": \"%REQ(:AUTHORITY)\%",
            \"bytes_received\": \"%BYTES_RECEIVED\%",
            \"bytes_sent\": \"%BYTES_SENT\%",
            \"connection_termination_details\": \"%CONNECTION_TERMINATION_DETAILS\%",
            \"downstream_local_address\": \"%DOWNSTREAM_LOCAL_ADDRESS\%",
            \"downstream_remote_address\": \"%DOWNSTREAM_REMOTE_ADDRESS\%",
            \"duration\": \"%DURATION\%",
            \"method\": \"%REQ(:METHOD)\%",
            \"path\": \"%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)\%",
            \"protocol\": \"%PROTOCOL\%",
            \"request_id\": \"%REQ(X-REQUEST-ID)\%",
            \"requested_server_name\": \"%REQUESTED_SERVER_NAME\%",
            \"response_code\": \"%RESPONSE_CODE\%",
            \"response_code_details\": \"%RESPONSE_CODE_DETAILS\%",
            \"response_flags\": \"%RESPONSE_FLAGS\%",
            \"route_name\": \"%ROUTE_NAME\%",
            \"start_time\": \"%START_TIME\%",
            \"upstream_cluster\": \"%UPSTREAM_CLUSTER\%",
            \"upstream_host\": \"%UPSTREAM_HOST\%",
            \"upstream_local_address\": \"%UPSTREAM_LOCAL_ADDRESS\%",
            \"upstream_service_time\": \"%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)\%",
            \"upstream_transport_failure_reason\": \"%UPSTREAM_TRANSPORT_FAILURE_REASON\%",
            \"user_agent\": \"%REQ(USER-AGENT)\%",
            \"x_forwarded_for\": \"%REQ(X-FORWARDED-FOR)%\",
            \"x_grpc_status\": \"%GRPC_STATUS_NUMBER%\"
            }"
        }
    defaultConfig:
...
```
2. No matter accessLogEncoding  is json or txt, it still need write **ALL FIELDS in accessLogFormat**, instead of **just add field you want**, this is really not friendly, and very easy to error configure.  Also, when istio upgrade and default format changed, you need change again.
 

**Describe alternatives you've considered**
No

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

Can you please
1. Suggest the correct json format accessLogFormat in my example
2. Let us know whether plan to add one field instead of list all in accessLogFormat ?

Thanks a lot!
