### ISSUE TITLE
Support configuring ALPN on Gateway listener.

### ISSUE THREAD

**Issue by albertlockett** [istio/istio#44729]
**Describe the feature request**
I would like there to be the ability to configure the ALPN protocols that the Gateway's the listener exposes. 

This capability would, for example, allow users to configure which of the downstream client's supported http versions the server will select.

This is configured in on the envoy [listener's filter chain's](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener_components.proto) `transport_socket`'s (type = [DownstreamTlsContext](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/tls.proto#envoy-v3-api-msg-extensions-transport-sockets-tls-v3-downstreamtlscontext)) `common_tls_context.alpn_protocols` field (see [here](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/tls.proto#envoy-v3-api-field-extensions-transport-sockets-tls-v3-commontlscontext-alpn-protocols)).

Currently the ALPN protocols are set to the default values`"h2", "http/1.1"`, unless either 
 - a) the transport protocol is QUIC or 
 - b) the TLS Settings Mode is ISTIO_MUTUAL.
https://github.com/istio/istio/blob/965788550c9a2582cdb91c1839501fba824e5006/pilot/pkg/networking/core/v1alpha3/listener.go#L122-L138

I think a reasonable API for this could be the one proposed here where the additional field `alpnProtocols` is added to the Gateway's Server's TLS settings:
https://github.com/istio/api/pull/2131

The logic in the listener builder could be that, if the listener is not being configured for QUIC/ISTIO_MUTUAL (the cases a/b listed above), then we'll use the values provided by the Gateway configuration, otherwise we'll use the current defaults.

**Describe alternatives you've considered**

It's not feasible to patch these values using an envoy filter. Because the `alpn_protocols` field on `commonTlsContext` is a list and the MERGE semantics for proto arrays cause the values to be appended.

i.e. simple envoy filter like this:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: disable-ingress-h2
  namespace: istio-gateway-ns
  labels:
    istio: ingressgateway
spec:
  configPatches: 
  - applyTo: FILTER_CHAIN
    match:
      listener:
        portNumber: 8443
    patch:
      operation: MERGE
      value:
        transportSocket:
          name: envoy.transport_sockets.tls
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
            commonTlsContext:
              alpnProtocols:
              - http/1.1
```

would result in a configuration like this...
```yaml
$ istioctl -n istio-gateway-ns proxy-config listeners deploy/istio-ingressgateway -oyaml
    ...
    transportSocket:
      name: envoy.transport_sockets.tls
      typedConfig:
        '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
        commonTlsContext:
          alpnProtocols:
          - h2
          - http/1.1
          - http/1.1
```
which is not what we want .. the intention would be to have this:
```yaml
# ...
          alpnProtocols:
          - http/1.1
```

If we could somehow fix the EnvoyFilter patch semantics for arrays to support replacing the value, that would solve the issue as well.

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

Similar Issue: https://github.com/istio/istio/issues/25081

**Comment by zengyuxing007** [comment]
Until this PR (https://github.com/istio/api/pull/2131) is merged in, there is really no good way to do it.

Perhaps we can make [EnvoyFilter's REPLACE](https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-Patch-Operation) support FILTER_CHAIN.  In this way, we can use EnvoyFilter to implement the requirement

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: disable-ingress-h2
  namespace: istio-gateway-ns
  labels:
    istio: ingressgateway
spec:
  configPatches: 
  - applyTo: FILTER_CHAIN
    match:
      listener:
        portNumber: 8443
    patch:
      operation: REPLACE
      value:
        transportSocket:
          name: envoy.transport_sockets.tls
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
            commonTlsContext:
              alpnProtocols:
              - http/1.1
```
