### ISSUE TITLE
Allow customize header in http response 

### ISSUE THREAD

**Issue by hsiaand** [istio/istio#44720]
I have use case to include a customized header in the machine-to-machine requests to distinguish the request from the user/browser.
e.g. 
curl -v http://httpbin.foo:8000/headers -H 'machine2machine: 1'

The purpose of this header is to include in response header so the envoyfilter/lua can decide if 401/403 should be change to 302 and redirect to a login URL if it is not machine-to-machine request.

The output of the request headers are been sanitized as shown below.  Is there a way to add customized header to it that will be available in the response header?

```
/ $ curl -v http://httpbin.foo:8000/headers -H 'Myheader: 123'
*   Trying 192.168.73.226:8000...
* Connected to httpbin.foo (192.168.73.226) port 8000 (#0)
> GET /headers HTTP/1.1
> Host: httpbin.foo:8000
> User-Agent: curl/7.80.0
> Accept: */*
> Myheader: 123
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< server: envoy
< date: Wed, 03 May 2023 07:36:00 GMT
< content-type: application/json
< content-length: 545
< access-control-allow-origin: *
< access-control-allow-credentials: true
< x-envoy-upstream-service-time: 5
<
{
  "headers": {
    "Accept": "*/*",
    "Host": "httpbin.foo:8000",
    "Myheader": "123",
    "User-Agent": "curl/7.80.0",
    "X-B3-Parentspanid": "7df50e10715ff866",
    "X-B3-Sampled": "0",
    "X-B3-Spanid": "af3683a81254bfdb",
    "X-B3-Traceid": "42aa95502e4c0fcc7df50e10715ff866",
    "X-Envoy-Attempt-Count": "1",
    "X-Forwarded-Client-Cert": "By=spiffe://cluster.local/ns/foo/sa/httpbin;Hash=1c05b351dd3965e1b07d5367e5541917c3a3c796e392e40eef6e4bc125c43ede;Subject=\"\";URI=spiffe://cluster.local/ns/bar/sa/default"
  }
}
* Connection #0 to host httpbin.foo left intact
/ $
```

**Comment by howardjohn** [comment]
You can set destination headers with virtual service: https://istio.io/latest/docs/reference/config/networking/virtual-service/#Headers

**Comment by hsiaand** [comment]
@howardjohn Looking at the reference provided, unless I overlooked it, it is injecting a static header regardless if the request is coming from a user or another external service.

**Comment by howardjohn** [comment]
You can match the incoming header to selectively set it though

**Comment by hsiaand** [comment]
@howardjohn I see there is `HeaderOperations` that supports add/remove/set operations.  But I don't see an example of how to conditionally inject the header.  Can you provide an example?

**Comment by howardjohn** [comment]
Under `match`

**Comment by hsiaand** [comment]
@howardjohn Thank you for pointing me to the answer.  
I am able to generate a custom header "m2m" in the response header based on user-agent.

in VirtualService, following is my definition 
```
  http:
  - match:
    - headers:
        user-agent:
          regex: .*Chrome.*
      uri:
        prefix: /status
    - headers:
        user-agent:
          regex: .*Chrome.*
      uri:
        prefix: /delay
    - headers:
        user-agent:
          regex: .*Chrome.*
      uri:
        prefix: /headers
    route:
    - destination:
        host: httpbin
        port:
          number: 8000
      headers:
        response:
          add:
            m2m: "1"
  - match:
    - uri:
        prefix: /status
    - uri:
        prefix: /delay
    - uri:
        prefix: /headers
    route:
    - destination:
        host: httpbin
        port:
          number: 8000
      headers:
        response:
          add:
            m2m: "0"
```

testing indicate if the header contains the `Chrome` keyword, it will return `m2m: 1` 
```
% curl -v https://access-control.dev.mycompany.com/headers -H "Authorization: Bearer $TOKEN" -H 'User-Agent: This is Chrome' 2>&1|egrep '^<'
< HTTP/2 200
< server: istio-envoy
< date: Wed, 03 May 2023 16:26:02 GMT
< content-type: application/json
< content-length: 612
< access-control-allow-origin: *
< access-control-allow-credentials: true
< x-envoy-upstream-service-time: 4
< m2m: 1
<
% curl -v https://access-control.dev.mycompany.com/headers -H "Authorization: Bearer $TOKEN" -H 'User-Agent: This is curl' 2>&1|egrep '^<'
< HTTP/2 200
< server: istio-envoy
< date: Wed, 03 May 2023 16:26:14 GMT
< content-type: application/json
< content-length: 610
< access-control-allow-origin: *
< access-control-allow-credentials: true
< x-envoy-upstream-service-time: 3
< m2m: 0
<
```
