### ISSUE TITLE
How to create bootstrap_extensions in WasmPlugins?

### ISSUE THREAD

**Issue by HZHgagaga** [istio/istio#44818]
I have used EnvoyFilter to complete my requirements:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: httpbin-wasm
  namespace: default
spec:
  workloadSelector:
    labels:
      app: httpbin
  configPatches:
  - applyTo: BOOTSTRAP
    patch:
      operation: MERGE
      value:
        bootstrap_extensions:
        - name: envoy.bootstrap.wasm
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.wasm.v3.WasmService
            singleton: true
            config:
              name: my_plugin
              configuration:
                "@type": type.googleapis.com/google.protobuf.StringValue
                value: "main"
              vm_config:
                vm_id: main_thread
                runtime: "envoy.wasm.runtime.v8"
                code:
                  local:
                    filename: "/var/local/lib/wasm-filters/main/main_thread.wasm"
  - applyTo: HTTP_FILTER
    match:
        context: SIDECAR_INBOUND
        listener:
          portNumber: 80
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
    patch:
      operation: INSERT_FIRST
      value:
        name: envoy.filters.http.wasm
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm"
          config:
            vm_config:
              vm_id: work_thread
              runtime: envoy.wasm.runtime.v8
              code:
                local:
                  filename: "/var/local/lib/wasm-filters/work/work_thread.wasm"
            configuration:
              "@type": "type.googleapis.com/google.protobuf.StringValue"
              value: "work"
```

Now I want to use OCI to update my wasm file, so I want to use WasmPlugin: [https://istio.io/v1.12/docs/reference/config/proxy_extensions/wasm-plugin/](url)

My requirement requires applying wasm in bootstrap_extensions, but I didn't see a description of bootstrap_extensions in the document.

How should I use wasm in bootstrap_extensions?
