### ISSUE TITLE
Unable to use wasm EnvoyFilter

### ISSUE THREAD

**Issue by HZHgagaga** [istio/istio#44810]
I have a requirement to use the wasm plugin to enable data communication between Envoy's main thread and work thread.

Similar to Envoy's wasm plugin: [https://github.com/tetratelabs/proxy-wasm-go-sdk/tree/main/examples/shared_queue](url)

I use Envoy's  main thread continue to send data to work thread through shared queue during the tick.

In the Envoy's wasm plugin, the main thread needs to be configured in bootstrap_extensions.

So I have written the following configuration:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: httpbin-wasm
  namespace: default
spec:
  workloadSelector:
    labels:
      app: httpbin
  configPatches:
  - applyTo: BOOTSTRAP
    patch:
      operation: MERGE
      value:
        bootstrap_extensions:
        - name: envoy.bootstrap.wasm
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.wasm.v3.WasmService
            singleton: true
            config:
              name: my_plugin
              configuration:
                "@type": type.googleapis.com/google.protobuf.StringValue
                value: "main"
              vm_config:
                vm_id: main_thread
                runtime: "envoy.wasm.runtime.v8"
                code:
                  local:
                    filename: "/var/local/lib/wasm-filters/main/main_thread.wasm"
  - applyTo: HTTP_FILTER
    match:
        context: SIDECAR_INBOUND
        listener:
          portNumber: 80
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
    patch:
      operation: INSERT_FIRST
      value:
        name: envoy.filters.http.wasm
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm"
          config:
            vm_config:
              vm_id: work_thread
              runtime: envoy.wasm.runtime.v8
              code:
                local:
                  filename: "/var/local/lib/wasm-filters/work/work_thread.wasm"
            configuration:
              "@type": "type.googleapis.com/google.protobuf.StringValue"
              value: "work"
```

As a result, Envoy's work thread successfully ran and output the correct log, but the main thread did not run and did not output any logs.

istio version:
```
client version: 1.12.5
control plane version: 1.12.5
data plane version: 1.12.5 (10 proxies)
```

Please help me, I would be very grateful.
