### ISSUE TITLE
patch the route of a specific virtualhost, affecting other virtualhosts

### ISSUE THREAD

**Issue by believening** [istio/istio#44820]
### Bug Description

different virtualHosts may share same routes pointer(which is a slice) as: 
https://github.com/istio/istio/blob/80bf81b2937dfb1a506a88150204bfbee53aaadf/pilot/pkg/networking/core/v1alpha3/httproute.go#L447

but patch the http route inplace:
https://github.com/istio/istio/blob/80bf81b2937dfb1a506a88150204bfbee53aaadf/pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch.go#L257-L258

reproduce:
1. create virtual service with more then one hosts:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: helloworld
  namespace: default
spec:
  hosts:
  - helloworld
  - hellofoo
  http:
  - match:
    - name: exact
      uri:
        exact: /hello
    route:
    - destination:
        host: helloworld
        port:
          number: 5000
        subset: v1
      weight: 10
    - destination:
        host: helloworld
        port:
          number: 5000
        subset: v2
      weight: 90
```

  got routeconfiguration like：

```
# before apply envoyfilter
$ istioctl proxy-config route xxx.demo -ojson | jq '.[] | select(.name =="5000")'
{
  "name": "5000",
  "virtualHosts": [
    {
// ....
    },
    {
      "name": "hellofoo.default.svc.cluster.local:5000",
      "domains": [...],
      "routes": [
        {
          "name": ".exact",
          "match": {...},
          "route": {...},
          "metadata": {...},
          "decorator": {...}
        }
      ],
      "includeRequestAttemptCount": true
    },
    {
      "name": "helloworld.default.svc.cluster.local:5000",
      "domains": [
        "helloworld.default.svc.cluster.local",
        "helloworld.default",
        "helloworld.default.svc",
        "10.96.214.152"
      ],
      "routes": [
        {
          "name": ".exact",
          "match": {...},
          "route": {...},
          "metadata": {...},
          "decorator": {...}
        }
      ],
      "includeRequestAttemptCount": true
    }
  ],
  "validateClusters": false,
  "ignorePortInHostMatching": true
}
```

2.  use envoyfilter to modify the route of vh `helloworld.default.svc.cluster.local:5000` like:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  labels:
    istio.io/rev: default
  namespace: demo
  name: patch-helloworld
spec:
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: SIDECAR_OUTBOUND
      routeConfiguration:
        vhost:
          name: helloworld.default.svc.cluster.local:5000
          route:
            name: .exact
    patch:
      operation: MERGE
      value:
        name: modified-route-name
```

  got routeconfiguration like：

```
# before apply envoyfilter
$ istioctl proxy-config route xxx.demo -ojson | jq '.[] | select(.name =="5000")'
{
  "name": "5000",
  "virtualHosts": [
    {
// ....
    },
    {
      "name": "hellofoo.default.svc.cluster.local:5000",
      "domains": [...],
      "routes": [
        {
          "name": "modified-route-name",
          "match": {...},
          "route": {...},
          "metadata": {...},
          "decorator": {...}
        }
      ],
      "includeRequestAttemptCount": true
    },
    {
      "name": "helloworld.default.svc.cluster.local:5000",
      "domains": [
        "helloworld.default.svc.cluster.local",
        "helloworld.default",
        "helloworld.default.svc",
        "10.96.214.152"
      ],
      "routes": [
        {
          "name": "modified-route-name",
          "match": {...},
          "route": {...},
          "metadata": {...},
          "decorator": {...}
        }
      ],
      "includeRequestAttemptCount": true
    }
  ],
  "validateClusters": false,
  "ignorePortInHostMatching": true
}
```

### Version

```Text
$ istioctl version
client version: 1.16.1
control plane version: 1.16.1
data plane version: 1.16.1 (4 proxies)
$ kubectl version --short  
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.25.0
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
