### ISSUE TITLE
HTTP2 Gateway + H2C enabled Application

### ISSUE THREAD

**Issue by JJRdec** [istio/istio#44847]
### Bug Description

I expected:
1. Forward HTTP2 upgrade headers to my application (with protocol selection i.e. name: http2-blah).
2. Hit the gateway on port 80 over HTTP2 (h2c plaintext) connection.

**Setup**:
1. Gateway (HTTPS and HTTP2)
4. Service (HTTP2)

## Behaviour 
**Running App locally**:
```
curl -v -k --http2 http://localhost:8080/boilerplate/hello
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /boilerplate/hello HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.68.0
> Accept: */*
> Connection: Upgrade, HTTP2-Settings
> Upgrade: h2c
> HTTP2-Settings: AAMAAABkAARAAAAAAAIAAAAA
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 101 Switching Protocols
< Connection: Upgrade
< Upgrade: h2c
< Date: Wed, 10 May 2023 11:57:42 GMT
* Received 101
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Connection state changed (MAX_CONCURRENT_STREAMS == 4294967295)!
< HTTP/2 200
< expires: 0
< cache-control: no-cache, no-store, max-age=0, must-revalidate
< x-xss-protection: 1; mode=block
< pragma: no-cache
< x-frame-options: DENY
< date: Wed, 10 May 2023 11:57:42 GMT
< x-content-type-options: nosniff
< content-type: text/plain;charset=ISO-8859-1
< content-length: 32
<
* Connection #0 to host localhost left intact
Hello from Boilerplate!
```

**App Logs Http2 upgrade headers**:
```
2023-05-10 11:57:42.624  INFO 1 --- [  XNIO-1 task-1] c.d.b.security.Http2HeaderFilter         : HTTP2-Settings=AAMAAABkAARAAAAAAAIAAAAA
2023-05-10 11:57:42.624  INFO 1 --- [  XNIO-1 task-1] c.d.b.security.Http2HeaderFilter         : Upgrade=h2c
```

---

**Gateway (HTTP2 port)**:
```
curl -v -k --http2 http://local.api.blah.com/boilerplate/hello
*   Trying 127.0.0.1:80...
* TCP_NODELAY set
* Connected to local.api.blah.com (127.0.0.1) port 80 (#0)
> GET /boilerplate/hello HTTP/1.1
> Host: local.api.blah.com
> User-Agent: curl/7.68.0
> Accept: */*
> Connection: Upgrade, HTTP2-Settings
> Upgrade: h2c
> HTTP2-Settings: AAMAAABkAARAAAAAAAIAAAAA
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< expires: 0
< cache-control: no-cache, no-store, max-age=0, must-revalidate
< x-xss-protection: 1; mode=block
< pragma: no-cache
< x-frame-options: DENY
< date: Wed, 10 May 2023 12:34:03 GMT
< x-content-type-options: nosniff
< content-type: text/plain;charset=ISO-8859-1
< content-length: 32
< x-envoy-upstream-service-time: 5
< server: istio-envoy
<
* Connection #0 to host local.api.blah.com left intact
Hello from Boilerplate!
```

**App Logs Http2 upgrade headers**:
```
2023-05-10 11:59:37.540  INFO 1 --- [  XNIO-1 task-1] c.d.b.security.Http2HeaderFilter         : no http2 headers
```

---

**Gateway (HTTPS port)**:
```
curl -v -k --http2 https://local.api.blah.com/boilerplate/hello
*   Trying 127.0.0.1:443...
.
.
.
> GET /boilerplate/hello HTTP/2
> Host: local.api.blah.com
> user-agent: curl/7.68.0
> accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 2147483647)!
< HTTP/2 200
< expires: 0
< cache-control: no-cache, no-store, max-age=0, must-revalidate
< x-xss-protection: 1; mode=block
< pragma: no-cache
< x-frame-options: DENY
< date: Wed, 10 May 2023 12:35:40 GMT
< x-content-type-options: nosniff
< strict-transport-security: max-age=31536000 ; includeSubDomains
< content-type: text/plain;charset=ISO-8859-1
< content-length: 32
< x-envoy-upstream-service-time: 12
< server: istio-envoy
<
* Connection #0 to host local.api.blah.com left intact
Hello from Boilerplate!
```

**App Logs Http2 upgrade headers:**
```
2023-05-10 11:59:37.540  INFO 1 --- [  XNIO-1 task-1] c.d.b.security.Http2HeaderFilter         : no http2 headers
```

## Cluster 
**Mesh config (configmap/istio)**:
h2UpgradePolicy: UPGRADE

**Gateway**:

```
# Source: gateway/templates/ingress-gateway.yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: protected-gateway
  labels:
    helm.sh/chart: gateway-0.1.0
    app.kubernetes.io/managed-by: "Helm"
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: ingress-cert
      hosts:
        - "local.api.blah.com"
    - port:
        number: 80
        name: http2-backend
        protocol: HTTP2
      hosts:
        - "local.api.blah.com"
---
# Source: gateway/templates/mtls-peer-authentication.yaml
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  # apply to root namespace to apply to the entire mesh
  namespace: istio-system
  labels:
    helm.sh/chart: gateway-0.1.0
    app.kubernetes.io/managed-by: "Helm"
spec:
  mtls:
    mode: STRICT
---
# Source: gateway/templates/protected-routing.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: private-gateway-virtual-service
  labels:
    helm.sh/chart: gateway-0.1.0
    app.kubernetes.io/managed-by: "Helm"
spec:
  hosts:
    - "*.api.blah.com"
  gateways:
    - protected-gateway
  http:
	- match:
	  - uri:
		  prefix: /boilerplate
	  route:
	  - destination:
		  host: boilerplate-service.backend.svc.cluster.local
```

**App**: 
```
# Source: boilerplate/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: boilerplate-service-account
  labels:
    helm.sh/chart: boilerplate-0.1.0
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/version: 1.0.0
---
# Source: boilerplate/templates/dr.yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: boilerplate-dr
  labels:
    helm.sh/chart: boilerplate-0.1.0
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/version: 1.0.0
spec:
  host: "boilerplate-service.backend.svc.cluster.local"
  trafficPolicy:
    connectionPool:
      http:
        useClientProtocol: true
---
# Source: boilerplate/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: boilerplate-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: boilerplate-0.1.0
    service: boilerplate-service
    skaffold.dev/run-id: bbcb20b6-ee66-4cac-83c4-fcf8015d8cc4
  name: boilerplate-service
  namespace: backend
spec:
  clusterIP: None
  ports:
  - name: http2
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: boilerplate-app
---
# Source: boilerplate/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: boilerplate-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: boilerplate-0.1.0
    skaffold.dev/run-id: e7065b54-7f14-435d-89ad-9b08fa37e8d8
  name: boilerplate-app
  namespace: backend
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: boilerplate-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: boilerplate-app
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: boilerplate-secret
        image: boilerplate:3e145095052d4ccdecf161ad563a45bbbc1350b6208be7a4a78993be83e00f38
        imagePullPolicy: IfNotPresent
        name: boilerplate-app
        ports:
        - containerPort: 8080
          name: http2
          protocol: TCP
        resources: {}

```

### Version

```Text
client version: 1.15.1
control plane version: 1.15.1
data plane version: 1.15.1 (4 proxies)
---
Client Version: v1.22.15
Server Version: v1.25.3
```

### Affected product area

- [ ] Ambient
- [X] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
So the broken case is

Gateway (HTTP2 port):

right? And it does http2 to the backend, just not from client-gateway?

**Comment by JJRdec** [comment]
> 

Well, yes - on the gateway for the HTTP2 port I expected to able to establish a http2 connection (h2c)  between the client and gateway.

Also, after setting http2 as a prefix to the port name in the service resource I taught I would see http2 upgrade headers logged within my app, or is protocol selection doing something else in this case that I'm missing?  

I can see from envoy logs we using http2 between my proxies thanks to "h2UpgradePolicy: UPGRADE" set via the configmap.

**Comment by howardjohn** [comment]
> Also, after setting http2 as a prefix to the port name in the service resource I taught I would see http2 upgrade headers logged within my app, or is protocol selection doing something else in this case that I'm missing?

This port naming should mean that any requests are doing h2c (prior knowledge). So gateway --> backend should always be http2 regardless of what the client does. Even without `"h2UpgradePolicy: UPGRADE"`

**Comment by JJRdec** [comment]
@howardjohn so I'm not a seeing http2 connection to the backend. Do we think there is a is a bug here? Why is envoy not forwarding the appropriate headers to my backend service?

**Comment by howardjohn** [comment]
No http2 connection or not upgrade request?

If there is no http2 connection and port is "http2" it's a bug or misconfiguration. Can you get a config_dump from the gateway?

**Comment by JJRdec** [comment]
Yes, no http2 connection. 

[config_dump.zip](https://github.com/istio/istio/files/11453039/config_dump.zip)

**Comment by howardjohn** [comment]
thansk

Looking at `outbound|8080||boilerplate-service.dcx.svc.cluster.local`

```
      "typed_extension_protocol_options": {
       "envoy.extensions.upstreams.http.v3.HttpProtocolOptions": {
        "@type": "type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions",
        "use_downstream_protocol_config": {
         "http_protocol_options": {},
         "http2_protocol_options": {}
        }
       }
```

So its using the downstream protocol.

I totally missed this in your example:
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: boilerplate-dr
  labels:
    helm.sh/chart: boilerplate-0.1.0
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/version: 1.0.0
spec:
  host: "boilerplate-service.backend.svc.cluster.local"
  trafficPolicy:
    connectionPool:
      http:
        useClientProtocol: true
```

Which would cause this. I think if you remove that it will always do http2 to `boilerplate-service`. Right now, you are saying "whatever client->gateway protocol was, use it for gateway->boilerplate".

That would still leave client->gateway as HTTP/1.1 though as the upgrade isn't happening. Need more investigation into that -- the lack for http2 from gateway->boilerplate was the low-hanging fruit
