### ISSUE TITLE
defaultRevision boolean does not appear to function in istioOperatorSpec

### ISSUE THREAD

**Issue by jaymiracola** [istio/istio#44851]
### Bug Description

When generating manifests via `istioctl manifest generate -f istio-operator.yaml` the `defaultRevision: true` does not appear to create the necessary validation webhook configurations to properly function as default. 
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  hub: gcr.io/istio-release
  tag: 1.16.3
  revision: 1-16
  profile: minimal
  defaultRevision: true

  meshConfig:
    defaultConfig:
```

### Version

```Text
istioctl version
client version: 1.16.3
control plane version: 1.6.3
data plane version: 1.16.3 (7 proxies)

k version --short
Client Version: v1.27.1
Kustomize Version: v5.0.1
Server Version: v1.26.3
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [X] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [X] Control Plane Revisions
