### ISSUE TITLE
expose envoy internal redirect fields

### ISSUE THREAD

**Issue by yingzhuivy** [istio/istio#44881]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
We have a setup where client <-> egress gateway is istio mtls, and egress gateway terminates the mtls and initiates tls with the upstream. This requires that client application send plaintext request.
In case when the external site respond with a 302, currently the egress gateway will pass the redirect request back to the downstream, which won't work in some case when the redirect URL is HTTPS in which case client will send HTTPS instead of plaintext.

The current workaround is to use EnvoyFilter to add the internal_redirect_policy supported by Envoy. I think it's a useful feature and if istio can expose the setting it would be great.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: redirect
  namespace: egress
spec:
  workloadSelector:
    labels:
      app: egress
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: ANY
    patch:
      operation: MERGE
      value:
        route:
          internal_redirect_policy:
            max_internal_redirects: 5
            redirect_response_codes: ["302"]
```

**Describe alternatives you've considered**
EnvoyFilter
**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
