### ISSUE TITLE
cni: logic to determine "should add iptables" is flawed

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#44938]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-ingressgateway
  namespace: istio-ingress
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  template:
    metadata:
      annotations:
        # Select the gateway injection template (rather than the default sidecar template)
        inject.istio.io/templates: gateway
      labels:
        # Set a unique label for the gateway. This is required to ensure Gateways can select this workload
        istio: ingressgateway
        # Enable gateway injection. If connecting to a revisioned control plane, replace with "istio.io/rev: revision-name"
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: istio-proxy
        image: auto # The image will automatically update each time the pod starts.
      - name: other
        image: alpine
```

This will install iptables. The logic currently is just "has istio-proxy and >1 container".

I am assigning to myself as I am working on a wider change that will overlap with the fix
