### ISSUE TITLE
ambient: VirtualService with multiple Waypoint destinations fails

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#44948]
Repro steps:

1. Install with ambient enabled
2. Deploy 2 services `a` and `b` (in a namespace with redirection enabled)
3. Deploy waypoints for them
4. Create a third deployment in the same namespace to be the client
5. Apply the following VirtualService
6. Try sending HTTP traffic to `a`. 

Half of it will fail

```
upstream connect error or disconnect/reset before headers. reset reason: connection termination
```

Envoy log from `a` waypoint:

```
[2023-05-16T22:14:00.041Z] "GET / HTTP/1.1" 503 UC upstream_reset_before_response_started{connection_termination} - "-" 0 95 1 - "-" "curl/7.81.0" "7b3c62e0-47f0-4b0d-a455-db8c975ff0cb" "a" "envoy://connect_originate/10.244.1.12:18080" outbound|80||b.echo-2-13188.svc.cluster.local envoy://internal_client_address/ 10.96.107.97:80 envoy://internal_client_address/ - -
```

(10.96.107.97 is the `b` svc vip, 10.244.1.12 is the `b` backing Pod)

zTunnel on `b`'s node:

```
2023-05-16T22:29:25.086112Z  INFO inbound{id=a1ebe994c68fdfa633dcd0481b5f47a2 peer_ip=10.244.2.9 peer_id=spiffe://cluster.local/ns/echo-2-13188/sa/a-istio-waypoint}: ztunnel::proxy::inbound: bypassed waypoint conn=10.244.2.9(spiffe://cluster.local/ns/echo-2-13188/sa/a-istio-waypoint)->10.244.1.12:18080
```

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: traffic-split
spec:
  hosts:
  - a
  http:
  - route:
    - destination:
        host: a
      weight: 50
    - destination:
          host: b
      weight: 50
```
