### ISSUE TITLE
DNS traffic not intercepted when using kubevirtInterfaces and ISTIO_META_DNS_CAPTURE

### ISSUE THREAD

**Issue by larhauga** [istio/istio#44996]
### Bug Description

We are running github actions controller in kubernetes with docker in docker and istio sidecars.
Istio is configured with `ISTIO_META_DNS_CAPTURE=true` and should intercept DNS and we would expect to see ip addresses in the range `240.240.0.0/16`.

However when running a dind container, we do not see the DNS meta addresses when trying to connect to remote addresses from the docker container. The pods have been annotated with the `"traffic.sidecar.istio.io/kubevirtInterfaces": "docker0"`  annotation, and we can see that the traffic is correctly passed through istio.

```
annotations:
  "traffic.sidecar.istio.io/kubevirtInterfaces": "docker0"
```

```
$ istioctl proxy-config all <pod> |grep public.ecr.aws
public.ecr.aws                                            443       -          outbound      STRICT_DNS
240.240.15.240  443   ALL                                                                      Cluster: outbound|443||public.ecr.aws
```

In the runner itself things work fine:
```
kubectl exec -it .runner -- sh
curl https://public.ecr.aws/ -v
*   Trying 240.240.15.240...
* TCP_NODELAY set
* Connected to public.ecr.aws (240.240.15.240) port 443 (#0)
```

But when trying to connect to the external service the IP is not resolved correctly.
```
sh-4.4# docker run --rm -it public.ecr.aws/amazonlinux/amazonlinux:2
bash-4.2# curl https://public.ecr.aws/ -v
*   Trying 99.83.145.10:443...
* Connected to public.ecr.aws (99.83.145.10) port 443 (#0)
...
* Recv failure: Connection reset by peer
* OpenSSL SSL_connect: Connection reset by peer in connection to public.ecr.aws:443 
* Closing connection 0
curl: (35) Recv failure: Connection reset by peer

```

It does not look like the `240.240.0.0/16` traffic is routed correctly even though the `kubeVirtInterfaces` is configured for the docker bridge.
The following command is not logged in the istio proxy
```
curl -H "Host: public.ecr.aws" https://240.240.15.240 -v
*   Trying 240.240.15.240:443...
* Connected to 240.240.15.240 (240.240.15.240) port 443 (#0)

```
curl https://public.ecr.aws/amazonlinux/amazonlinux -v
*   Trying 75.2.101.78:443...
* Connected to public.ecr.aws (75.2.101.78) port 443 (#0)
curl: (35) Recv failure: Connection reset by peer
```
{"response_flags":"UH","upstream_service_time":null,"connection_termination_details":null,"protocol":null,"downstream_remote_address":"172.17.0.2:36988","authority":null,"upstream_local_address":null,"requested_server_name":"public.ecr.aws","path":null,"route_name":null,"response_code":0,"bytes_sent":0,"user_agent":null,"method":null,"response_code_details":null,"x_forwarded_for":null,"bytes_received":0,"upstream_host":null,"start_time":"2023-05-19T05:33:18.951Z","request_id":null,"upstream_transport_failure_reason":null,"upstream_cluster":"BlackHoleCluster","duration":0,"downstream_local_address":"75.2.101.78:443"}
```

From what I can gather it looks like there is a bug in the istio iptables configuration that results in:
1. DNS requests not correctly passed through istio-proxy dns resolver
2. Traffic with META IP addresses not correctly passed through istio-proxy.

### Version

```Text
$ istioctl version
client version: 1.17.1
control plane version: 1.17.2
data plane version: 1.17.2 (16 proxies)
$ kubectl version --short
Client Version: v1.25.9
Kustomize Version: v4.5.7
Server Version: v1.25.6-eks-48e63af
```

### Additional Information

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: play
spec:
  exportTo:
    - "."
  hosts:
    - public.ecr.aws
    - d2glxqk2uabbnd.cloudfront.net    
  ports:
    - name: https
      number: 443
      protocol: TLS
  resolution: DNS
  location: MESH_EXTERNAL
```

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: gh-ci-runner
  namespace: ci-runner
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/kubevirtInterfaces: docker0
    spec:
      dockerEnabled: true
      dockerVolumeMounts:
      - mountPath: /var/lib/docker
        name: var-lib-docker
      dockerdContainerResources: {}
      dockerdWithinRunnerContainer: false
      env:
      - name: RUNNER_FEATURE_FLAG_EPHEMERAL
        value: "true"
      - name: RUNNER_GRACEFUL_STOP_TIMEOUT
        value: "110"
      repository: xxx
      serviceAccountName: build
      terminationGracePeriodSeconds: 120
      volumes:
      - emptyDir: {}
        name: var-lib-docker

```
istio-init log:
```istio-init
2023-05-15T13:40:14.352904Z	info	Istio iptables environment:
ENVOY_PORT=
INBOUND_CAPTURE_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_OUTBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_EXCLUDE_INTERFACES=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=
ISTIO_META_DNS_CAPTURE=true
INVALID_DROP=

2023-05-15T13:40:14.352943Z	info	Istio iptables variables:
PROXY_PORT=15001
PROXY_INBOUND_CAPTURE_PORT=15006
PROXY_TUNNEL_PORT=15008
PROXY_UID=1337
PROXY_GID=1337
INBOUND_INTERCEPTION_MODE=REDIRECT
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=*
INBOUND_PORTS_EXCLUDE=15090,15021,15020
OUTBOUND_OWNER_GROUPS_INCLUDE=*
OUTBOUND_OWNER_GROUPS_EXCLUDE=
OUTBOUND_IP_RANGES_INCLUDE=*
OUTBOUND_IP_RANGES_EXCLUDE=10.199.1.0/24
OUTBOUND_PORTS_INCLUDE=
OUTBOUND_PORTS_EXCLUDE=
KUBE_VIRT_INTERFACES=docker0
ENABLE_INBOUND_IPV6=false
DNS_CAPTURE=true
DROP_INVALID=false
CAPTURE_ALL_DNS=false
DNS_SERVERS=[172.20.0.10],[]
OUTPUT_PATH=
NETWORK_NAMESPACE=
CNI_MODE=false
HOST_NSENTER_EXEC=false
EXCLUDE_INTERFACES=
...
2023-05-15T13:40:14.358391Z	info	Running command: iptables-save 
2023-05-15T13:40:14.360776Z	info	Command output: 
# Generated by iptables-save v1.8.7 on Mon May 15 13:40:14 2023
*raw
:PREROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A PREROUTING -d 172.20.0.10/32 -p udp -m udp --sport 53 -j CT --zone 1
-A OUTPUT -p udp -m udp --dport 53 -m owner --uid-owner 1337 -j CT --zone 1
-A OUTPUT -p udp -m udp --sport 15053 -m owner --uid-owner 1337 -j CT --zone 2
-A OUTPUT -p udp -m udp --dport 53 -m owner --gid-owner 1337 -j CT --zone 1
-A OUTPUT -p udp -m udp --sport 15053 -m owner --gid-owner 1337 -j CT --zone 2
-A OUTPUT -d 172.20.0.10/32 -p udp -m udp --dport 53 -j CT --zone 2
COMMIT
# Completed on Mon May 15 13:40:14 2023
# Generated by iptables-save v1.8.7 on Mon May 15 13:40:14 2023
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:ISTIO_INBOUND - [0:0]
:ISTIO_IN_REDIRECT - [0:0]
:ISTIO_OUTPUT - [0:0]
:ISTIO_REDIRECT - [0:0]
-A PREROUTING -i docker0 -j ISTIO_REDIRECT
-A PREROUTING -i docker0 -j RETURN
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A OUTPUT -p udp -m udp --dport 53 -m owner --uid-owner 1337 -j RETURN
-A OUTPUT -p udp -m udp --dport 53 -m owner --gid-owner 1337 -j RETURN
-A OUTPUT -d 172.20.0.10/32 -p udp -m udp --dport 53 -j REDIRECT --to-ports 15053
-A ISTIO_INBOUND -p tcp -m tcp --dport 15008 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A ISTIO_OUTPUT -s 127.0.0.6/32 -o lo -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -p tcp -m tcp ! --dport 53 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -p tcp -m tcp ! --dport 53 -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -p tcp -m tcp ! --dport 53 -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 172.20.0.10/32 -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 15053
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -d 10.109.14.0/24 -j RETURN
-A ISTIO_OUTPUT -d 10.109.15.0/24 -j RETURN
-A ISTIO_OUTPUT -d 10.109.255.0/24 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
COMMIT
# Completed on Mon May 15 13:40:14 2023

```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
