### ISSUE TITLE
Istio Ingress and Redirects

### ISSUE THREAD

**Issue by gitoverflow** [istio/istio#450]
As far as I understood istio is not only a service to service mesh, but can also handle ingress traffic via it's ingress controller.

So, should we use istio for ingress traffic routing?  (And if the answer ist yes:)

How are we supposed to redirect all http traffic to https traffic, given the following example:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: secured-ingress
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  tls:
    - secretName: ingress-secret
  rules:
  - http:
      paths:
      - path: /ip
        backend:
          serviceName: httpbin
          servicePort: 8000
      - path: /headers
        backend:
          serviceName: httpbin
          servicePort: 8000
      - path: /delay/.*
        backend:
          serviceName: httpbin
          servicePort: 8000
```
