### ISSUE TITLE
Istio Authorization policy fails to validate elements in header values as Array

### ISSUE THREAD

**Issue by krishnakumar797** [istio/istio#45051]
### Bug Description

Authorization policy wasnt able to successfully validate elements in an Array which is coming as header with the request. Used the following yaml.

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: user-service-auth
  namespace: order
spec:
  action: ALLOW
  selector:
    matchLabels:
      name: user-service-pod
  rules:
  - to:
    - operation:
        methods: ["GET"]
        paths: ["/*"]
    when:
    - key: request.headers[permissions]
      values: ["ORDER_READ"]
```

the value of reqest.headers[permission] is as follows

[ORDER_READ,ORDER_DELETE]

this always returns RBAC Access denied error

### Version

```Text
istio version : 1.17.1
Kubectl version:
   Client Version: v1.14.0
   Server Version: v1.25.6

used helm to deploy istio
  helm version: v3.5.2+g167aac7
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
