### ISSUE TITLE
Gateway-based data plane extensions

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#45068]
Gateway APIs allow open-ended extensions as part of the CRDs. This functionality can provide the same capability as what EnvoyFilter is used today for, but in a supportable way. For example, [zip support](https://github.com/istio/istio/issues/18443) could be done as follows:

```yaml
apiVersion: envoyfilter.istio.io/v1alpha1
kind: CompressionFilter
metadata:
  name: compression-example
spec:
  compressor_library:
    name: text_optimized
    typed_config:
      '@type': type.googleapis.com/envoy.extensions.compression.brotli.compressor.v3.Brotli
      quality: 5
      encoder_mode: DEFAULT
      window_bits: 18
      input_block_bits: 24
      chunk_size: 4096
  response_direction_config:
    remove_accept_encoding_header: true
    common_config:
      enabled:
        default_value: true
        runtime_key: response_direction_config_enabled
      content_type:
        - application/json
        - text/css
        - text/html
        - text/plain
        - text/xml
      min_content_length: 800
  request_direction_config:
    common_config:
      enabled:
        default_value: false
        runtime_key: request_direction_config_enabled
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: mesh
spec:
  parentRefs:
  - kind: Service # or Gateway
    name: example
  rules:
  - filters:
    - extensionRef:
        group: envoyfilter.istio.io/v1alpha1
        kind: CompressionFilter
        name: compression-example
      type: ExtensionRef
  - backendRefs:
    - name: example
      port: 80
```

The explicit trade-off taken here is:
- GAMMA-based binding
- allow-listed Envoy filters via the kind
- schema based on Envoy xDS

Long term, this would be a preferred option via a [popular EnvoyFilter method](https://karlstoney.com/2023/01/31/enabling-gzip-compression-with-envoyfilter/).

**Comment by keithmattix** [comment]
This is really intriguing to me. A couple of thoughts:

- Where does the line get drawn for community supported functionality vs roll your own?

- How will istiod know about every  CRD out there?

- This UX is already vastly more accessible than EnvoyFilter

**Comment by kyessenov** [comment]
> * Where does the line get drawn for community supported functionality vs roll your own?
The line is drawn at the filter type. We will have a set of filters from upstream Envoy registered with their schema definitions. Others can extend with vendor-specific or 3rd party definitions (for custom builds of Envoy, for example) and re-use much of the machinery.

> * How will istiod know about every  CRD out there?

The list of filters should be defined in code I think. It's not worth pursuing meshconfig-type provider definitions IMHO.
I don't know whether we should have a CRD per EnvoyFilter or a container CRD, e.g.:

```
apiVersion: envoyfilter.istio.io/v1alpha1
kind EnvoyFilter
metadata:
  name: compression-example
spec:
  name: envoy.extensions.filters.http.compressor.v3.Compressor
  typed_config:
    compressor_library:
```

We have tried both ways in the past - too many CRDs are also difficult to manage.

**Comment by keithmattix** [comment]
> The line is drawn at the filter type. We will have a set of filters from upstream Envoy registered with their schema definitions. Others can extend with vendor-specific or 3rd party definitions (for custom builds of Envoy, for example) and re-use much of the machinery.

That would still require an istiod fork, no? I would love if we took this opportunity to make the vendor/extension experience less painful (e.g. the maintenance burden of a long-term fork). Dynamic CRD registration would be the ideal

>  I don't know whether we should have a CRD per EnvoyFilter or a container CRD, e.g.:
The long-term maintainability of a container CRD would be rough IMO. That's a lot of fields to version and evolve

**Comment by kyessenov** [comment]
> That would still require an istiod fork, no? I would love if we took this opportunity to make the vendor/extension experience less painful (e.g. the maintenance burden of a long-term fork). Dynamic CRD registration would be the ideal

I don't mind it being done dynamically via CEL and loading protobuf descriptors. Golang was not strong in dealing with protos that are not compiled-in last time I checked.

> The long-term maintainability of a container CRD would be rough IMO. That's a lot of fields to version and evolve

I think it's about the same cost to maintain a set of 10 CRDs vs 1 CRD with 10 enum options. If k8s can handle many CRDs operationally (in the management, install, etc), I don't think it's that different. Last time we added 40 CRDs we got a lot of beef for that.

**Comment by costinm** [comment]
Few comments - while noting that I agree with the approach and very happy to see it.

I think the fundamental decision is if want to add a 'allow users to set compression API', or we just want a way to apply a subset of envoy filters in a safe manner, which is not possible with EnvoyFilter. Both are valuable, and we should consider them in parallel. 

1. I generally ask for 'prior art' - to avoid NIH and because a good API should have more than one implementation. I think it should be a requirement for any API review. How is Nginx/HAProxy/Apache/??? configuring compression ? Is envoy the only proxy that has compression support
2.  Surface - do we need ALL of the functionality ? Looking at what others provide is useful, it is much easier to add features later. Also easier to test a narrower surface. 
3. Scope - setting the filter on each HttpRoute is a lot of work for users - current use with EnvoyFilter seems to be to set it for the entire workload.  We can do this in a few different ways - but taking into account Waypoints and Gateways, we should be able to apply it to a list of hosts. 
4. HttpRoute filters have one big future problem - if we are to have any interop or migration with other mesh implementations, filters don't work well because routes will be rejected by non-istio meshes. 
5. HttpRoutes tend to be included with the app helm - adding vendor-specific filters is difficult, since an istio filter would be rejected by non-istio implementations. Resulting in complex helm charts with 'if istio' ...

My proposal is to ALSO provide a mechanism to attach this extension to workloads ( for sidecars) or hosts or gateway listeners with a parentRef. I think it is useful to keep the route filter for advanced users with only istio, but shouldn't be the only option.

And to start with a smaller CRD than the full envoy filter - based on what other vendors support and what users need, so we have a narrower test surface ( to get this API to beta we'll need to add tests and docs ).

The comments are not specific to compression - we should do this for other envoy filters if they are considered stable and 
they have broad use in Istio.

**Comment by kyessenov** [comment]
Thanks for the responses. I generally agree that we need to keep the "supportable EnvoyFilter" track separate from the first-class Gateway extension discussion. I'm interested in the former right now. I haven't seen GEP for compression proposed anywhere yet. I think all the criticism of GAMMA attachment is valid - but is this really the right place to design a solution for it? I'd imagine parentRef over HTTPRoute and first-class compression need to be discussed in the wider context, and we should try to avoid a custom Istio-only solution until there's a common proposal for it. 

HTTPRoute attachment is not going away so we have to support that regardless - and it's certainly useful to cover more EnvoyFilter use cases. A common request is to apply it per-route which VS/EF make it hard.

**Comment by costinm** [comment]
I think the critical issue we need to address in Gateway is adding 'sections' to HttpRoute, so the policy attachment can work. Or alternatively to define a mechanism to have optional (ignored) route filters. Right place is in the Gateway WG, but we need to start the discussion and make sure it's moving forward.

My concern is that even 'supportable EnvoyFilter' is not as supportable as an API as it sounds. It is certainly better than current EnvoyFilter, but still too broad API and dependent on having an envoy - any use on sidecars will create problems as we move to ambient/ztunnel and may or may not be ok in Waypoints. We should do the work - it is a clear improvement, but we really need to do the proper API in parallel, so users are not stuck with envoy filter ( even the slightly more supportable variant ).

I don't think we disagree on much - compression is a good start, and if needed I think we could add few fields to VirtualService ( it is backwards compatible ) so we are not blocked on Gateway. 

BTW: we should avoid using 'GAMMA' term, it is not an API, just a WG where Gateway API use in mesh is discussed. Compression for example is far more in scope for a gateway ( and waypoint ).

**Comment by kyessenov** [comment]
The fact that it's Envoy specific is intentional - there's always going to be a need to break-through Istio limitations and access Envoy capabilities directly, since realistically all Istios are Envoy based. Related to this work, I think it's worth carving out a subset of EnvoyFilter that can be ported across versions and Gateway representation. I started #45223 with the goal of making internal tests stop using EnvoyFilter excessively.

**Comment by keithmattix** [comment]
Not stale

**Comment by spacewander** [comment]
Envoy gateway has added an extension CRD called SecurityPolicy:
https://github.com/envoyproxy/gateway/blob/main/site/content/en/latest/design/security-policy.md#features--api-fields

This policy combines multiple features into one single policy, so the number of CRDs can be reduced.

Would you consider using such a meta policy to define the extensions? For example, we can define a policy called HTTPFilterPolicy, and the CompressionFilter above can be written as:

```
apiVersion: envoyfilter.istio.io/v1alpha1
kind: HTTPFilterPolicy
metadata:
  name: compression-example
spec:
  filters:
    compress:
        compressor_library:
```
