### ISSUE TITLE
Waypoint and ztunnel are not exposing their ports properly

### ISSUE THREAD

**Issue by krisztianfekete** [istio/istio#45093]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I'd like to create scrape_configs for ambient components, but their ports are not exposed and named properly, so I cannot do that.

This is the scrape_config I'd like to use to be aligned with the existing scrape configs recommended [here](https://istio.io/latest/docs/ops/integrations/prometheus/#option-2-customized-scraping-configurations): 

```yaml
- job_name: 'waypoint-stats'
  metrics_path: /stats/prometheus
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_annotation_istio_io_for_service_account]
    action: keep
    regex: (.+)
  - source_labels: [__meta_kubernetes_pod_container_port_name]
    action: keep
    regex: 'waypoint-stats'
- job_name: ztunnel-stats
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_label_app]
    action: keep
    regex: ztunnel
```

### Version

```Text
master branch
```

### Affected product area

- [X] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
