### ISSUE TITLE
Blackholed metrics and logs don't correlate.

### ISSUE THREAD

**Issue by mikhail-khodorovskiy** [istio/istio#45117]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

The tcp connection metrics collected by the envoy show a non-zero a count for   istio_tcp_connections_closed_total and istio_tcp_connections_closed_total "BlackHoleCluster" cluster metrics:

```
istio-proxy@benefits-routing-service-54754bfd87-shc89:/$ curl http://localhost:15000/stats/prometheus | grep -i black | more
istio_tcp_connections_closed_total{reporter="destination",source_workload="unknown",source_workload_namespace="unknown",source_principal="unknown",source_app="unknown",source_version="unknown",sour
ce_cluster="unknown",destination_workload="benefits-routing-service",destination_workload_namespace="benefits-routing-service",destination_principal="unknown",destination_app="benefits-routing-serv
ice",destination_version="20230522_162905",destination_service="benefits-routing-service",destination_service_name="BlackHoleCluster",destination_service_namespace="benefits-routing-service",destin
ation_cluster="Kubernetes",request_protocol="tcp",response_flags="UH",connection_security_policy="none",source_canonical_service="unknown",destination_canonical_service="benefits-routing-service",s
ource_canonical_revision="latest",destination_canonical_revision="20230522_162905"} 2
istio_tcp_connections_closed_total{reporter="source",source_workload="benefits-routing-service",source_workload_namespace="benefits-routing-service",source_principal="unknown",source_app="benefits-
routing-service",source_version="20230522_162905",source_cluster="Kubernetes",destination_workload="unknown",destination_workload_namespace="unknown",destination_principal="unknown",destination_app
="unknown",destination_version="unknown",destination_service="unknown",destination_service_name="BlackHoleCluster",destination_service_namespace="unknown",destination_cluster="unknown",request_prot
ocol="tcp",response_flags="UH",connection_security_policy="unknown",source_canonical_service="benefits-routing-service",destination_canonical_service="unknown",source_canonical_revision="20230522_1
62905",destination_canonical_revision="latest"} 1
istio_tcp_connections_opened_total{reporter="destination",source_workload="unknown",source_workload_namespace="unknown",source_principal="unknown",source_app="unknown",source_version="unknown",sour
ce_cluster="unknown",destination_workload="benefits-routing-service",destination_workload_namespace="benefits-routing-service",destination_principal="unknown",destination_app="benefits-routing-serv
ice",destination_version="20230522_162905",destination_service="benefits-routing-service",destination_service_name="BlackHoleCluster",destination_service_namespace="benefits-routing-service",destin
ation_cluster="Kubernetes",request_protocol="tcp",response_flags="UH",connection_security_policy="none",source_canonical_service="unknown",destination_canonical_service="benefits-routing-service",s
ource_canonical_revision="latest",destination_canonical_revision="20230522_162905"} 2
istio_tcp_connections_opened_total{reporter="source",source_workload="benefits-routing-service",source_workload_namespace="benefits-routing-service",source_principal="unknown",source_app="benefits-
routing-service",source_version="20230522_162905",source_cluster="Kubernetes",destination_workload="unknown",destination_workload_namespace="unknown",destination_principal="unknown",destination_app
="unknown",destination_version="unknown",destination_service="unknown",destination_service_name="BlackHoleCluster",destination_service_namespace="unknown",destination_cluster="unknown",request_prot
ocol="tcp",response_flags="UH",connection_security_policy="unknown",source_canonical_service="benefits-routing-service",destination_canonical_service="unknown",source_canonical_revision="20230522_1
62905",destination_canonical_revision="latest"} 1
```
The logs for the same envoy instance, does not have the corresponding logs:
```
kubectl logs benefits-routing-service-54754bfd87-shc89 -n benefits-routing-service -c istio-proxy | grep -i black
$
```
even though the access log typically contain the BlackHoleCluster access logs but not for this pod. Example access log from another pod for the BlackHoleCluster scenario:

```
[2023-05-24T18:09:52.038Z] "- - -" 0 UH - - "-" 0 0 2 - "-" "-" "-" "-" "-" BlackHoleCluster - 78.45.22.13:443 10.52.48.104:46806 api-dev.google.com -
```

### Version

```Text
istioctl version
client version: 1.16.4
control plane version: 1.16.4
data plane version: 1.16.4 (90 proxies)
```
```
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.13-eks-0a21954", GitCommit:"6305d65c340554ad8b4d7a5f21391c9fa34932cb", GitTreeState:"clean", BuildDate:"2023-04-15T00:33:45Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}
```
```


### Additional Information

_No response_

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
Hmm, `destination_version="20230522_162905"` is weird too. There is no destination version for Blackhole. Looks like it may be copying source to destination.

do you know a way to reproduce this?

**Comment by mikhail-khodorovskiy** [comment]
I am not exactly sure, but it seems to happen for the pods on restart/redeploy is when out monitors wrongfully fire without anything in the logs indicating blocked requests.

Istio is installed using HELM charts and here is the resulting configmap:
```
  mesh: |-
    defaultConfig:
      discoveryAddress: istiod-1-16-4.istio-system.svc:15012
      tracing:
        datadog:
          address: $(HOST_IP):8126
    enablePrometheusMerge: true
    extensionProviders:
    - envoyExtAuthzHttp:
        headersToUpstreamOnAllow:
        - x-ext-authz
        - x-current-user
        - authorization
        - x-ext-authz-check-result
        includeRequestHeadersInCheck:
        - x-ext-authz
        - Authorization
        - authorization
        port: "80"
        service: external-authorization-service.external-authorization-service.svc.cluster.local
      name: ext-authz-http
    - envoyExtAuthzGrpc:
        port: "9000"
        service: ext-authz.extauth-test.svc.cluster.local
      name: ext-authz-grpc
    - envoyExtAuthzGrpc:
        includeRequestBodyInCheck:
          maxRequestBytes: 1000000
        port: "9191"
        service: local-opa-grpc.local
      name: opa-local
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
    rootNamespace: null
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
``` 

Each service we deploy uses in-house HELM chart and here are the VS and DR examples:
```
 apiVersion: networking.istio.io/v1beta1
  kind: VirtualService
  metadata:
    annotations:
      meta.helm.sh/release-name: example-pipeline-service
      meta.helm.sh/release-namespace: example-pipeline-service
    creationTimestamp: "2022-10-04T16:56:06Z"
    generation: 2
    labels:
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: example-pipeline-service
      app.kubernetes.io/part-of: janus-platform-continuous-integration
      janusplatform.io/TechOwnerName: platform-infrastructure
    name: example-pipeline-service
    namespace: example-pipeline-service
    resourceVersion: "123109666"
    uid: c71f0257-972d-462b-894e-458fad7b8ee8
  spec:
    gateways:
    - internal-istio-ingressgateway/gateway
    hosts:
    - example-pipeline-service-k8s.dev.platform.io
    - example-pipeline-service.dev.platform.io
    http:
    - match:
      - uri:
          prefix: /
      route:
      - destination:
          host: example-pipeline-service.example-pipeline-service.svc.cluster.local
``` 

```
apiVersion: networking.istio.io/v1beta1
  kind: DestinationRule
  metadata:
    annotations:
      meta.helm.sh/release-name: example-pipeline-service
      meta.helm.sh/release-namespace: example-pipeline-service
    creationTimestamp: "2022-10-04T16:56:06Z"
    generation: 2
    labels:
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: example-pipeline-service
      app.kubernetes.io/part-of: janus-platform-continuous-integration
      janusplatform.io/TechOwnerName: platform-infrastructure
    name: example-pipeline-service
    namespace: example-pipeline-service
    resourceVersion: "123109661"
    uid: e43170fb-cfee-418a-add4-5c2f92e00eff
  spec:
    host: example-pipeline-service.example-pipeline-service.svc.cluster.local
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
```

with each service being deployed into its own namespace.

We use Datadog for monitoring and which runs host agents setup to scan each envoy's stats endpoint and send the metrics to their APIs.

The attachment shows the spikes in the count of blackhole'd closed connections but there is nothing in the logs corresponding the egress being blocked.
 
![Screen Shot 2023-05-30 at 10 59 19 AM](https://github.com/istio/istio/assets/44823822/36bef6e0-c146-43c1-8dac-b09fc92053b2)


What else would you need to reproduce it?
