### ISSUE TITLE
Support custom NodePorts in native k8s Gateway

### ISSUE THREAD

**Issue by terabyte128** [istio/istio#45113]
When creating an Istio Ingress Gateway resource of type NodePort, I can define custom `nodePort`s in the IstioOperator, e.g.,

```yaml
components:
  ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      namespace: cluster-ingress
      k8s:
        service:
          type: NodePort
          ports:
            - name: status-port
              protocol: TCP
              port: 15021
              targetPort: 15021
              nodePort: 31021
            - name: http2
              protocol: TCP
              port: 80
              targetPort: 8080
              nodePort: 31080
            - name: https
              protocol: TCP
              port: 443
              targetPort: 8443
              nodePort: 31443
```

However, when creating a NodePort service via the [native Gateway API](https://gateway-api.sigs.k8s.io/), there doesn't appear to be a way to do this:

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: httpbin-gateway
  namespace: cluster-ingress
  annotations:
    networking.istio.io/service-type: "NodePort" # how do I define which ports to use?
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    hostname: "httpbin.example.com"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same
```

We need to be able to define custom `NodePort`s to ensure that they remain consistent between environments and when services are restarted. As far as I can tell, Istio doesn't currently provide any way to do this.

Is this possible? Or could it be added?

**Comment by terabyte128** [comment]
Bump, would still be helpful

**Comment by mitchellmann** [comment]
[](https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/#manual-deployment)

This says here you can manually create a service and deployment, then link them.

**Comment by networkhermit** [comment]
How can we get this issue reopened? I think this usage is fairly common and it's overkill to manually deploy the gateway.

**Comment by danielloader** [comment]
> How can we get this issue reopened? I think this usage is fairly common and it's overkill to manually deploy the gateway.

Agreed if only for use with Kind and other local developer setups.

**Comment by gerassimos** [comment]
Yes how to reopen this?
I would suggest to add an annotation such as `networking.istio.io/service-nodePort` to be able to define the actual NodePort number
So for example should be able to have a `Gateway` as follow:


```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: httpbin-gateway
  namespace: cluster-ingress
  annotations:
    networking.istio.io/service-type: "NodePort" 
    networking.istio.io/service-nodePort: 30080 
```

**Comment by danielloader** [comment]
The issue here is you're fighting against the design rationale for the gateway API in the first place, which was to get rid of the annotations as configuration by convention. So whole I agree it'd be nice to have, the chances of custom annotations configuring the gateway is approximately zero.

**Comment by terabyte128** [comment]
While there is precedent for custom annotations (for instance, `networking.istio.io/service-type`), the probably-more-canonical solution (and the one that I ended up going with) is to deploy all the Gateway resources [as a Helm chart](https://artifacthub.io/packages/helm/istio-official/gateway/1.17.1) if more extensive customization is desired.

**Comment by gerassimos** [comment]
An other workaround could be to just create the `service` object upfront.
So before actually creating the `gateway` object you could create `service` object as follow:
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    networking.istio.io/service-type: NodePort
  labels:
    gateway.istio.io/managed: istio.io-gateway-controller
    gateway.networking.k8s.io/gateway-name: httpbin-gateway
    istio.io/gateway-name: httpbin-gateway
  name: httpbin-gateway-istio
  namespace: cluster-ingress
spec:
  selector:
    gateway.networking.k8s.io/gateway-name: httpbin-gateway
  type: NodePort
  ports:
  - appProtocol: tcp
    name: status-port
    nodePort: 32751
    port: 15021
    protocol: TCP
    targetPort: 15021
  - appProtocol: http
    name: http
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80
```
This way the `deployment` object is created automatically and the service object is updated but we have control over the nodePort used, in this example `30080`

**Comment by paulwitt** [comment]
For anyone finding this through a google search you can accomplish this by deploying the gateway through the helm chart, setting it to run as a nodeport service and defining the port there.  Then you create your gateways using the manual deployment steps mentioned above by @mitchellmann.  This allows you to terraform the load balancer type of your choice, use a limited number of load balancers, and have all traffic routed into your cluster through the nodeport service.

**Comment by mehyedes** [comment]
For anyone else who ends up here looking for an answer, I can confirm that this is possible using the method described in the Istio docs under [Automated deployment](https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/#automated-deployment) which relies on a `ConfigMap`.
You will have to manage an extra `ConfigMap`, but this is way better than having to manage the `Gateway` related resources manually with a helm chart.
Istio will also reconcile any changes to the configmap and apply them to the gateway, even after the gateway is created. 

IMHO, this approach is much cleaner than creating the service manually, as it doesn't differ much from the manual deployment approach.

I was able to make it work using the manifests below:
- **Cluster:**  Kind 
- **Istio version:** v1.29.1
- **Gateway API version:** v1.4.1 experimental

**gw-options.yaml:**
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: gw-options
  namespace: ingress-gateway
data:
  horizontalPodAutoscaler: |
    spec:
      minReplicas: 2
      maxReplicas: 2

  deployment: |
    metadata:
      annotations:
        additional-annotation: some-value
    spec:
      replicas: 2

# Set the nodePort in this section
  service: |
    spec:
      ports:
      - port: 30080
        nodePort: 31234
```

**gateway.yaml:**
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: custom-gateway
  namespace: ingress-gateway
  annotations:
    networking.istio.io/service-type: "NodePort"
spec:
  infrastructure:
    parametersRef:
      group: ""
      kind: ConfigMap
      name: gw-options
  gatewayClassName: istio
  listeners:
  - name: httpbin
    port: 30080
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
```

The service that was created has the correct node port `31234` configured:
```
$ kubectl -n ingress-gateway get svc custom-gateway-istio
NAME                   TYPE       CLUSTER-IP   EXTERNAL-IP   PORT(S)                           AGE
custom-gateway-istio   NodePort   10.96.10.4   <none>        15021:31440/TCP,30080:31234/TCP   15m

$ kubectl -n ingress-gateway describe svc custom-gateway-istio
Name:                     custom-gateway-istio
Namespace:                ingress-gateway
Labels:                   gateway.istio.io/managed=istio.io-gateway-controller
                          gateway.networking.k8s.io/gateway-class-name=istio
                          gateway.networking.k8s.io/gateway-name=custom-gateway
                          istio.io/dataplane-mode=none
Annotations:              networking.istio.io/service-type: NodePort
Selector:                 gateway.networking.k8s.io/gateway-name=custom-gateway
Type:                     NodePort
IP Family Policy:         PreferDualStack
IP Families:              IPv4
IP:                       10.96.10.4
IPs:                      10.96.10.4
Port:                     status-port  15021/TCP
TargetPort:               15021/TCP
NodePort:                 status-port  31440/TCP
Endpoints:                10.244.0.13:15021,10.244.0.12:15021
Port:                     httpbin  30080/TCP
TargetPort:               30080/TCP
NodePort:                 httpbin  31234/TCP
Endpoints:                10.244.0.13:30080,10.244.0.12:30080
Session Affinity:         None
External Traffic Policy:  Cluster
Internal Traffic Policy:  Cluster
Events:                   <none>
```
