### ISSUE TITLE
Jwks_remote_fetch_is_failed with Auth0

### ISSUE THREAD

**Issue by trenslow** [istio/istio#45138]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Recently the remote fetch of from the JWKS URI stopped working on my IngressGateway, halting all secured traffic into my cluster. It started responding with `Jwks remote fetch is failed`. If I look at the envoy logs, I see that the fetch of the JWKS from the Remote Uri shows the following log `debug    envoy filter    onSuccess: fetch pubkey [uri = https://{AUTH0_TENANT}.eu.auth0.com/.well-known/jwks.json]: response status code {code}` where {code} is either 400 or 503. I would expect that the remote fetch would work as it always had up until this issue. As far as I can tell, nothing changed in my configurations when this issue started occurring on 11 April.

For context, I'm running Google's Anthos Service Mesh with managed Istio Control Plane. I have an IngressGateway in front of a few backend services. I also have strict mTLS enabled mesh-wide, which, as I understand, requires me to create ServiceEntry resources for all the external APIs my backend services call. I've configured RequestAuthentication on the gateway to check for valid JWT tokens issued by Auth0. 

So far I've found two workarounds:

1. Use the physical JWKS copied from Auth0's endpoint directly into the RequestAuthentication. This works without issue, but I would prefer something more dynamic in case I have to rotate the signing keys on my Auth0 tenant.
2. I can keep the `jwksUri` set and I can remove the host "{AUTH0_TENANT}.eu.auth0.com" from my ServiceEntry. This won't work in a strict mTLS setting, as the sidecars in the backend services will treat the connections to that host as part of the mesh.

Something I've noticed for the (now) broken configuration: If I set the `jwksUri` and the host in the ServiceEntry the response to the remote JWKS endpoint is 400 if I set `resolution: DNS`. If I remove this setting, the response is 503. I'm not sure if that's useful.

I hope it's ok to file the issue here, because I think it's related to Istio/Envoy configuration and not Anthos. I'm also sure that the problem isn't on the Auth0 side, as I can curl the JWKS endpoint directly in the IngressGateway's envoy container and get a successful response.

### Version

```Text
$ istioctl version
no running Istio pods in "istio-system" (this is due to the managed control plane being "hidden" by Google -> managed control plane is running 1.15.7-asm.8)
1.17.2
$ kubectl version --short
Client Version: v1.25.9
Kustomize Version: v4.5.7
Server Version: v1.26.2-gke.1000
```

### Additional Information

I'm attaching the parts of the bug-report related to the gateway:

```
Error [IST0101] (Gateway gateway/asm-ingressgateway) Referenced selector not found: "asm=ingressgateway"
Warning [IST0127] (AuthorizationPolicy gateway/require-hc-claim) No matching workloads for this resource with the following labels: asm=ingressgateway
Warning [IST0127] (AuthorizationPolicy gateway/require-jwt) No matching workloads for this resource with the following labels: asm=ingressgateway
Warning [IST0133] (AuthorizationPolicy gateway/require-hc-claim) Schema validation warning: configured AuthorizationPolicy will deny all traffic to TCP ports under its scope due to the use of only HTTP attributes in a DENY rule; it is recommended to explicitly specify the port
Warning [IST0133] (AuthorizationPolicy gateway/require-jwt) Schema validation warning: configured AuthorizationPolicy will deny all traffic to TCP ports under its scope due to the use of only HTTP attributes in a DENY rule; it is recommended to explicitly specify the port
Warning [IST0144] (Deployment gateway/asm-ingressgateway) User ID (UID) 1337 is reserved for the sidecar proxy.
Warning [IST0146] (Deployment gateway/asm-ingressgateway) Deployment asm-ingressgateway contains `image: auto` but does not match any Istio injection webhook selectors.
Info [IST0118] (Service gateway/asm-ingressgateway) Port name status-port (port: 15021, targetPort: 15021) doesn't follow the naming convention of Istio port.
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
Why it broke was a change moving from resolving JWKS in Istiod to doing it in Envoy. This was not supposed to cause issues but does in some cases which is being looked into.

> I can keep the jwksUri set and I can remove the host ".eu.auth0.com" from my ServiceEntry. This won't work in a strict mTLS setting, as the sidecars in the backend services will treat the connections to that host as part of the mesh.

I am not sure what this has to do with strict mTLS. to make sure we are on the same page, https://istio.io/latest/docs/ops/configuration/traffic-management/tls-configuration/ may help. Strict mTLS is a server-side enforcement, but I would imagine eu.auth0.com is outside the mesh? 

So I would expect the desired flow to be `envoy --- TLS ---> eu.auth0.com`. Note the "TLS" here would not be Istio mTLS, just standard TLS as if I did `curl https://eu.auth0.com`.

If you remove the SE, ASM should automatically configure things correctly, so that does seem like one viable path. The other is to setup the SE to meet this usage.

Typically, you could setup a SE like this:

```yaml
kind: ServiceEntry
spec:
  hosts:
  - auth0.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: NONE
```

Then inyour app do `curl https://auth0.com`. Envoy proxy passes the TLS through and we are good-to-go. The issue with JWKS resolution is Envoy is originating the request. So `resolution: NONE` doesn't work, since there is no original destination (I suspect this is the 503 you mentioned).

Moving it to DNS gets us a bit further - you should see 400. This is because now its not sending TLS. In the curl case, the app was doing the TLS and envoy passes it through. Now it does the same, but there is no TLS to pass through (arguably, it should just do this automatically, but... it is what it is...). So we need to add a DR config to tell it to also add TLS.

So overall you should have:

```yaml
kind: ServiceEntry
spec:
  hosts:
  - auth0.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
---
kind: DestinationRule
spec:
  host: auth0.com
  trafficPolicy:
    tls:
      mode: SIMPLE
      sni: auth0.com
```

**Comment by trenslow** [comment]
Thanks for the quick response on this one @howardjohn.

> I am not sure what this has to do with strict mTLS. to make sure we are on the same page, https://istio.io/latest/docs/ops/configuration/traffic-management/tls-configuration/ may help. Strict mTLS is a server-side enforcement, but I would imagine eu.auth0.com is outside the mesh?

Auth0 is indeed outside the mesh. I'm not able to find it anymore, but I remember at some point reading that when strict mTLS is enabled, ServiceEntries with `location: MESH_EXTERNAL` need to be created in order to not interfere with the TLS between internal services and external services. I not only have the gateway validating tokens at the Auth0 host, but an internal service also communicating with the same host. Sorry about not providing that context before; I didn't realize it was related until now.

Since the internal service is communicating with Auth0, keeping the ServiceEntries seems to be the preferable path, since, from what I understand, configuring ServiceEntries enables telemetry for internal-external service communication, as well as the ability to further lock down the mesh to have REGISTRY_ONLY communication.

> Now it does the same, but there is no TLS to pass through (arguably, it should just do this automatically, but... it is what it is...). So we need to add a DR config to tell it to also add TLS.

Based on your proposed solution, do I understand correctly that even though the `jwksUri` is configured with an https:// URL and a ServiceEntry exists for the host which explicitly specifies the HTTPS protocol, envoy is still sending a plain-text request to the `jwksUri`? Shouldn't that somehow be picked up by the Protocol Selection feature? That's a little confusing, but I can live with that. 

However, if I add the destination rule, does that mean that traffic to the Auth0 host from the internal service will somehow be double encrypted, i.e. TLS requests originated in the internal service will also be wrapped in another layer of TLS by the proxy? 

Maybe there's a cleaner solution to cover both the gateway JWT validation as well as the unlocking the functionality that comes with creating a ServiceEntry for the internal service to Auth0 communication?

**Comment by howardjohn** [comment]
> However, if I add the destination rule, does that mean that traffic to the Auth0 host from the internal service will somehow be double encrypted, i.e. TLS requests originated in the internal service will also be wrapped in another layer of TLS by the proxy?

Yes, good point. I suppose you could do

```yaml
kind: ServiceEntry
spec:
  hosts:
  - definitely-not-auth0.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
  endpoints:
  - address: auth0.com
```

then set jwksURI to `definitely-not-auth0.com` (don't actually use that domain name, though). The `host` is just a lookup key more of less.

Let me look into if there are some better options

**Comment by trenslow** [comment]
@howardjohn just dropping in to see how this topic has developed on your side and if my assessment in the last comment was correct

**Comment by vitalii-buchyn-exa** [comment]
just a notice, if you set something like `definitely-not-someextauth.com` instead of `someextauth.com` in ServiceEntry and in jwksUri, envoy will send that host in requestUrl, so if a remote side cannot proceed it you will get 404, thus doesn't work for us

**Comment by trenslow** [comment]
If anyone ever comes across this issue, I fixed it by creating a DestinationRule for each host listed in the ServiceEntry and I was able to achieve both goals of mine: 1) validating JWTs in RequestAuthentication using the jwksUri field instead of hardcoding the JWKS and 2) still using the same hosts in the ServiceEntry as the hosts defined in the jwksUri field, allowing me to avoid PassthroughCluster traffic from internal services. E.g.:

```
---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: api-authn
spec:
  selector:
    matchLabels:
      asm: ingressgateway
  jwtRules:
  - issuer: https://{AUTH0_TENANT}.eu.auth0.com/
    jwksUri: https://{AUTH0_TENANT}.eu.auth0.com/.well-known/jwks.json
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: auth0-ext
spec:
  hosts:
    - {AUTH0_TENANT}.eu.auth0.com
  location: MESH_EXTERNAL
  ports:
    - number: 443
      name: https
      protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: originate-tls-to-jwks-uri
spec:
  host: {AUTH0_TENANT}.eu.auth0.com
  trafficPolicy:
    tls:
      mode: SIMPLE
      sni: {AUTH0_TENANT}.eu.auth0.com
```
