### ISSUE TITLE
VS: HTTPRewrite doesn't work without HTTPMatchRequest

### ISSUE THREAD

**Issue by jdloft** [istio/istio#45148]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Suppose we want a fake Kubernetes service to forward all connections to an external resource on a sub path. Using a VirtualService with a rewrite on the default route like the following doesn't work.
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: example-vs
spec:
  hosts:
  - service.namespace.svc.cluster.local
  http:
  - rewrite:
      uri: /path
    route:
    - destination:
        host: site.example.com
        port:
          number: 80
    headers:
      request:
        set:
          Host: site.example.com
```

Instead an HTTP match with an empty prefix is required.
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: example-vs
spec:
  hosts:
  - service.namespace.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: ""
    rewrite:
      uri: /path
    route:
    - destination:
        host: site.example.com
        port:
          number: 80
    headers:
      request:
        set:
          Host: site.example.com
```
This is either a bug or a documentation problem since the docs for HTTPRewrite only say the following:
> rewrite the path (or the prefix) portion of the URI with this value. If the original URI was matched based on prefix, the value provided in this field will replace the corresponding matched prefix.

This suggests that a match based on prefix is optional.

### Version

```Text
client version: 1.17.1
control plane version: 1.16.4
data plane version: 1.16.4 (142 proxies)
```

### Affected product area

- [ ] Ambient
- [X] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
