### ISSUE TITLE
Authorization policy not being applied to Gateway

### ISSUE THREAD

**Issue by brunooliveiramac** [istio/istio#45140]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

What happened:
authorization policy not being applied to Gateway

What you expected to happen:
authorization policy is applied to Gateway and traffic denied

How to reproduce it (as minimally and precisely as possible):

I have this gateway configured in GKE with a static regional IP.

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: my-gateway
  namespace: istio-ingress
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
  addresses:
    - value: "x.x.x.x"
      type: IPAddress
      
```
the service:

```
apiVersion: v1
kind: Service
metadata:
  name: my-gateway-istio
  namespace: istio-ingress
  labels:
    gateway.istio.io/managed: istio.io-gateway-controller
spec:
  externalTrafficPolicy: Local
  ports:
    - appProtocol: tcp
      name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    - appProtocol: http
      name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    istio.io/gateway-name: my-gateway
  type: LoadBalancer
```
HTTPRoute:

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: my-gateway-http-route
spec:
  parentRefs:
    - name:  my-gateway
      namespace: istio-ingress
  rules:
    - matches:
        - path:
            type: Exact
            value: "/test"
      backendRefs:
        - name: my-service
          port: 8080
```
          
and the authorization policy:

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: my-gateway-authorization-policy
  namespace: istio-ingress
spec:
  selector:
    matchLabels:
      istio.io/gateway-name: my-gateway
  action: ALLOW
  rules:
    - from:
        - source:
            ipBlocks:
              - x.x.x.x # Test IP
```

### Version

```Text
$istioctl version
client version: 1.11.0
control plane version: 1.17.1
data plane version: 1.17.1 (20 proxies)

$kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.24.11-gke.1000
```

### Additional Information

The policy is not working. I've gone through some troubleshooting, changing some configs, reinstalling everything, and also trying to check the istio pod logs:

`kubectl patch deployment my-gateway -n istio-ingress -p'{"spec":{"template":{"spec":{"containers":[{"name":"istio-proxy","args":["proxy", "sidecar", "--proxyLogLevel=debug"]}]}}}}' `

I'm using kubernetes gateway API: https://gateway-api.sigs.k8s.io/guides/

### Affected product area

- [ ] Ambient
- [X] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [X] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
