### ISSUE TITLE
Cannot create Ingress Gateways with Istio v1.17.2 and EKS v1.26

### ISSUE THREAD

**Issue by geoffo-dev** [istio/istio#45178]
Hello, 

I have been having quite a bit of trouble installing istio on a brand new EKS cluster. 

I am trying to automate the deployment and have been using helm charts through argocd for the deployment. In essence this follows the documentation of:

```
helm repo add istio https://istio-release.storage.googleapis.com/charts
helm repo update
kubectl create namespace istio-system
helm install istio-base istio/base -n istio-system
helm install istiod istio/istiod -n istio-system
kubectl create namespace istio-ingress
helm install istio-ingress istio/gateway -n istio-ingress
```

Initially I was receiving the error (which is not the exact one, but I know very similar as I copied from another site after fixing it): 

```
Error creating: Internal error occurred: failed calling webhook “http://sidecar-injector.istio.io/”: Post https://istio-sidecar-injector.istio-system.svc/inject?timeout=10s: context deadline exceeded
```

Which appeared to be due to a rule needing to be added port `15017` between the primary cluster security group and the node security group. 

Once this was fixed (and the sidecar injected in the istio namespace). I then attempted to deploy the following for a ingress gateway.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: keycloak-gateway
spec:
  selector:
    istio: ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "keycloak.{{ .Values.domain }}"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: keycloak-crt
    hosts:
    - "keycloak.{{ .Values.domain }}"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: keycloak-virtual-service
spec:
  hosts:
  - "keycloak.{{ .Values.domain }}"
  gateways:
  - keycloak-gateway
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: keycloak.keycloak.svc.cluster.local
        port:
          number: 80
```

I have ensured there is also the cert available in the `istio-ingress` namespace.

I used istioctl analyze to confirm that this configuration is correct, but no matter what I do, the Gateway source does not seem to be detected and created by the ingress operator - there is no status or anything.

I have tried to create the resources in different istio namespaces and have tried to move the ingress operator into the ingress-system namespace but have had no success.

Am I missing something?
