### ISSUE TITLE
Gateways configured in ISTIO_MUTUAL require clients to overwrite SNI in DestinationRule

### ISSUE THREAD

**Issue by jacob-delgado** [istio/istio#45173]
**Describe the feature request**

Given the following for a server

```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: httpbin-example-ingressgateway
  namespace: httpbin
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - httpbin.example.com
    port:
      name: https-8443
      number: 8443
      protocol: HTTPS
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpbin-example-igw-vs
  namespace: httpbin
spec:
  gateways:
  - httpbin-example-ingressgateway
  hosts:
    - httpbin.example.com
  http:
  - match:
    route:
    - destination:
        host: httpbin.httpbin.svc.cluster.local
        port:
          number: 8000
```

and a client that has the following config

```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: httbin-example-se
  namespace: sleep
spec:
  hosts:
    - httpbin.example.com
  ports:
  - name: http2-8443
    number: 8443
    protocol: HTTP2
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: httpbin-example-dr
  namespace: sleep
spec:
  host: httpbin.example.com
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```
configures the client's cluster definition to use an SNI of `outbound_.8443_._.httpbin.example.com`

This requires additional user configuration for the `DestinationRule`. Wildcards can introduce more complexity for users if they wish to have a `DestinationRule` with `sni: *.example.com`.

Proposal: For HTTP connections we can build the client's cluster definition to use Envoy's `auto_sni` feature for `location: MESH_EXTERNAL` services. This would auto-populate the SNI based on the host authority header making the UX much better for users doing this. We would not alter this for TCP-only connections.

**Describe alternatives you've considered**

N/A

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
