### ISSUE TITLE
Why set DEFAULT_WORKLOAD_CERT_TTL not work?

### ISSUE THREAD

**Issue by HZHgagaga** [istio/istio#45190]
I want to modify the expiration time of the certificate, so I used the following configuration:
```yaml
# istio-operator-config.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-operator-config
spec:
  components:
    pilot:
      k8s:
        env:
        - name: DEFAULT_WORKLOAD_CERT_TTL
          value: "720h"
          
  meshConfig:
    defaultConfig:
      proxyMetadata:
        DEFAULT_WORKLOAD_CERT_TTL: "720h"
```

```shell
$ istioctl install -f istio-operator-config.yaml

$ kubectl get deployment istiod -n istio-system -o jsonpath='{.spec.template.spec.containers[0].env[?(@.name=="DEFAULT_WORKLOAD_CERT_TTL")]}'
{"name":"DEFAULT_WORKLOAD_CERT_TTL","value":"720h"}

$ kubectl delete deployment unit
deployment.apps "unit" deleted

$ kubectl apply -f example/unit/istio-unit.yaml serviceaccount/unit unchanged
service/unit unchanged
deployment.apps/unit created

$ kubectl exec unit-74894bc94d-x752v -c istio-proxy -- curl 127.0.0.1:15000/certs
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16475    0 16475    0     0  15.7M      0 --:--:-- --:--:-- --:--:-- 15.7M
{
 "certificates": [
  {
   "ca_cert": [
    {
     "path": "\u003cinline\u003e",
     "serial_number": "853eebb8baed8aa60d83e8b91204fb8d",
     "subject_alt_names": [],
     "days_until_expiration": "3649",
     "valid_from": "2023-05-29T07:08:26Z",
     "expiration_time": "2033-05-26T07:08:26Z"
    }
   ],
   "cert_chain": [
    {
     "path": "\u003cinline\u003e",
     "serial_number": "9661fe9b23d76ef8211102595f16a391",
     "subject_alt_names": [
      {
       "uri": "spiffe://cluster.local/ns/default/sa/unit"
      }
     ],
     "days_until_expiration": "0",
     "valid_from": "2023-05-29T08:38:59Z",
     "expiration_time": "2023-05-30T08:40:59Z"
    }
   ]
  },
```
I find the  "days_until_expiration"  value is zero, DEFAULT_WORKLOAD_CERT_TTL seems to have not taken effect.
But when I used the following configuration, I successfully modified the expiration time of the certificate:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-operator-config
spec:
  meshConfig:
    defaultConfig:
      proxyMetadata:
        SECRET_TTL: "720h"
```
```shell
$ kubectl exec unit-864d7d6c6b-wp46f  -c istio-proxy -- curl 127.0.0.1:15000/certs
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16500    0 16500    0     0  15.7M      0 --:--:-- --:--:-- --:--:-- 15.7M
{
 "certificates": [
  {
   "ca_cert": [
    {
     "path": "\u003cinline\u003e",
     "serial_number": "853eebb8baed8aa60d83e8b91204fb8d",
     "subject_alt_names": [],
     "days_until_expiration": "3649",
     "valid_from": "2023-05-29T07:08:26Z",
     "expiration_time": "2033-05-26T07:08:26Z"
    }
   ],
   "cert_chain": [
    {
     "path": "\u003cinline\u003e",
     "serial_number": "07b9208fee3c7338c9d93b7a8d36a71f",
     "subject_alt_names": [
      {
       "uri": "spiffe://cluster.local/ns/default/sa/unit"
      }
     ],
     "days_until_expiration": "29",
     "valid_from": "2023-05-30T02:45:56Z",
     "expiration_time": "2023-06-29T02:47:56Z"
    }
   ]
  },
```
I see "days_until_expiration" value is 29, It's working.
What is the difference between DEFAULT_WORKLOAD_CERT_TTL and SECRET_TTL?
Why set DEFAULT_WORKLOAD_CERT_TTL not work? Is it related to minikube? I used istio v1.12.5 and minikube in this test.
Which value should I use in the production environment?

istio version:
```shell
$ istioctl version
client version: 1.12.5
control plane version: 1.12.5
data plane version: 1.12.5 (14 proxies)

$ minikube version
minikube version: v1.30.1
commit: 08896fd1dc362c097c925146c4a0d0dac715ace0
```
