### ISSUE TITLE
authorization policy not working properly

### ISSUE THREAD

**Issue by brunooliveiramac** [istio/istio#45217]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Rules in the authorization policy are being ignored.

I have this policy. The IpBlock does works, but the namespace one is not working.
I have a pod with a sidecar trying to access my gateway, and it's getting access denied.

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: bitbucket-webhook-authorization-policy
  namespace: istio-ingress
  labels:
    app.kubernetes.io/version: 1.17.1
    app: istio-ingressgateway
spec:
  selector:
    matchLabels:
      istio.io/gateway-name: ci-webhooks
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces: ["*"]
        - source: # see https://support.atlassian.com/organization-administration/docs/ip-addresses-and-domains-for-atlassian-cloud-products/#AtlassiancloudIPrangesanddomains-OutgoingConnections
            ipBlocks:
              - 13.52.5.96/28
```

I don't have mTls enabled.

### Version

```Text
istioctl version:

client version: 1.17.1
control plane version: 1.17.1
data plane version: 1.17.1 

kubectl version:
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.24.11-gke.1000
```

### Affected product area

- [X] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
