### ISSUE TITLE
SSL Error Between Sidecar Service and Kafka

### ISSUE THREAD

**Issue by tommyJimmy87** [istio/istio#4524]
This is my scenario : 

Aws
Kubernetes 1.7.2
Istio 0.6
Kafka Stream Application
Kafka Cluster (with SSL and SASL Enabled)

I installed Istio Auth in istio-system namespace and so far is ok.
I Deployed a Kafka Cluster (3 brokers) in another namespace (test) with the configuration for SSL and SASL without a sidecar.
I Deployed a Kafka Stream Application with a Sidecar in the same kafka's namespace (test) with istio kube-inject, the installation is ok, the sidecar is attached correctly but when the kafka producer trying to connect with Kafka Cluster got this error : 

> [kafka-admin-client-thread | adminclient-1] WARN org.apache.kafka.clients.NetworkClient - [AdminClient clientId=adminclient-1] Connection to node 0 terminated during authentication. This may indicate that authentication failed due to invalid credentials.
[kafka-admin-client-thread | adminclient-1] WARN org.apache.kafka.common.network.SslTransportLayer - Failed to send SSL Close message 
java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.apache.kafka.common.network.SslTransportLayer.flush(SslTransportLayer.java:212)
	at org.apache.kafka.common.network.SslTransportLayer.close(SslTransportLayer.java:170)
	at org.apache.kafka.common.utils.Utils.closeAll(Utils.java:703)
	at org.apache.kafka.common.network.KafkaChannel.close(KafkaChannel.java:61)
	at org.apache.kafka.common.network.Selector.doClose(Selector.java:717)
	at org.apache.kafka.common.network.Selector.close(Selector.java:708)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:500)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:398)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:460)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1006)

I tryed to exclude kafka service in the istio config-map : 

`# Edit this list to avoid using mTLS to connect to these services.
    # Typically, these are control services (e.g kubernetes API server) that don't have Istio sidecar
    # to transparently terminate mTLS authentication.
    mtlsExcludedServices: ["kubernetes.default.svc.cluster.local","kafka-csvc.dev.svc.cluster.local"]`

Without Sidecar it work well.
I would like to exclude kafka cluster from the envoy proxy or something like that. 
Any help is appreciated.
Thanks

**Comment by tommyJimmy87** [comment]
UPDATE : I tried to annotate with "auth.istio.io/9094: NONE" my kafka borkers as well. But I still got the same problem. 
Any Idea ?

**Comment by andraxylia** [comment]
cc @diemtvu for help.

**Comment by diemtvu** [comment]
By kafka service, do you mean the one in Kafka cluster (i.e receiving side)?
Basically, you use annotation on the receiving service (even when it doesn't has sidecar). Also, you don't need to set mtlsExcludedServices.

**Comment by tommyJimmy87** [comment]
Yes, i mean the Kafka Private Service (Kubernetes Service) which is the one to which my other pods connect.
Kafka doesn't have the sidecar but i annotated as documentation > "auth.istio.io/9094: NONE". 
But i still have the problem above when i try to connect from another application in another pod to the Kafka Pod. 
Kafka has SSL and SASL configured, it seems that the sidecar  (envoy proxy) when find a service with the annotation changes the request somehow and the result is that the SSL authentication in my Kafka doesn't work.

**Comment by diemtvu** [comment]
Can you deploy another client pod without sidecar to see if it can connect to kafka service?

**Comment by tommyJimmy87** [comment]
I have already applications without sidecar that work well with our Kafka Cluster. 
I've also tried to disable the Mutual TLS and the problem persists.
The problem is only in this use case because i've also tried with other services (which don't have SSL) and the annotation work well.

**Comment by diemtvu** [comment]
That's strange. Every thing sounds correct to me. Can you send me snippet of your deployment script (for both client and server) to double check.

**Comment by tommyJimmy87** [comment]
Again, without sidecar it works well, I would like to figure out the envoy proxy behaviour when MTLS is active but disabled on one service. 
What i think is that somehow the request change after the Envoy Proxy.
And what i would like to do is completely exclude one service of the cluster from the mesh and go forward the request without passing from the Sidecar Proxy.

Anyway this is the Application which try to connect to Kafka (Kafka Stream Application) : 

```
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{.component}}
  namespace: {{.namespace}}
  labels:
    release: {{.release}}
    component:  {{.component}}
    version: {{.version}}
spec:
  updateStrategy:
    type: "RollingUpdate"
  replicas: {{.replicas}}
  serviceName: {{.component}}-psvc
  template:
    metadata:
      name: {{.component}}
      labels:
        component: {{.component}}
    spec:
      imagePullSecrets:
        - name: {{.artifactoryStore}}
      containers:
      - image: {{.image}}
        imagePullPolicy: Always
        name: {{.name}}
        env:
        envFrom:
          - configMapRef:
               name: {{.component}}-kafka-config-{{.version}}
        command:
        - bash
        - -c
        - " {{if .ssl}}
            export SSL_TRUSTSTORE_PASSWORD=$(cat /etc/kafka/secrets/jks/clientTrustStorePass) && \
            export SSL_KEYSTORE_PASSWORD=$(cat /etc/kafka/secrets/jks/clientKeyStorePass) && \
            export SSL_KEY_PASSWORD=$(cat /etc/kafka/secrets/jks/clientKeyPass) && \
            {{if .auth}}
            export BOOTSTRAP_SERVERS=SASL_SSL://$KAFKA_CSVC_SERVICE_HOST:$KAFKA_CSVC_SERVICE_PORT && \
            {{else}}
            export BOOTSTRAP_SERVERS=SSL://$KAFKA_CSVC_SERVICE_HOST:$KAFKA_CSVC_SERVICE_PORT && \
            {{end}}
            {{else}}
            export BOOTSTRAP_SERVERS=INTERNAL://$KAFKA_CSVC_SERVICE_HOST:$KAFKA_CSVC_SERVICE_PORT && \
            {{end}}
            export SCHEMA_REGISTRY_URL=http://$SCHEMA_REGISTRY_SERVICE_PRIVATE_SERVICE_HOST:$SCHEMA_REGISTRY_SERVICE_PRIVATE_SERVICE_PORT && \
            export ZOOKEEPER_CONNECT=$ZK_CSVC_SERVICE_HOST:$ZK_CSVC_SERVICE_PORT && \
            export ZOOKEEPER_CONNECT=$ZK_CSVC_SERVICE_HOST:$ZK_CSVC_SERVICE_PORT/{{.kafkaZNode}}  && \
            printenv && \
            /docker/run"
        livenessProbe:
          httpGet:
            path: /v1/groups
            port: 7001
          initialDelaySeconds: 5
          periodSeconds: 360
        readinessProbe:
          httpGet:
            path: /v1/groups
            port: 7001
          initialDelaySeconds: 5
          periodSeconds: 360
        ports:
        - containerPort: 7001
        resources:
          requests:
             {{ range $key, $value := .requests }}
             {{ $key }}: {{ $value }}
             {{ end }}
          limits:
             {{ range $key, $value := .limits }}
             {{ $key }}: {{ $value }}
             {{ end }}
        volumeMounts:
          {{if .ssl}}
          - name: kafka-stores-jks
            mountPath: /etc/kafka/secrets/jks
          {{end}}
          {{if .auth}}
          - name: kafka-stores-jaas
            mountPath: /etc/kafka/secrets/jaas
          {{end}}
          - name: config-volume
            mountPath:  /etc/{{.component}}/config
          - name: {{.component}}-storage-dir
            mountPath: {{.stateDir}}
      volumes:
      - name: config-volume-jmx
        configMap:
          name:   {{.component}}-jmx-config-{{.version}}
          items:
          - key:  config.yaml
            path: config.yaml
      {{if .ssl}}
      - name: kafka-stores-jks
        secret:
             secretName: {{.kafkaStores}}-client
      {{end}}
      {{if .auth}}
      - name: kafka-stores-jaas
        secret:
             secretName: {{.kafkaStores}}-kafka-client-privileged
      {{end}}
      - name: config-volume
        configMap:
          name:   {{.component}}-app-config-{{.version}}
          items:
          - key:  app.yml
            path: app.yml
          - key:  server.yml
            path: server.yml
  volumeClaimTemplates:
    - metadata:
        name: {{.component}}-storage-dir
        annotations:
            volume.beta.kubernetes.io/storage-class: gp2
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{.diskSize}}
```

And here the command for run it : 

``` 
kubectl apply -f <(istioctl kube-inject --injectConfigFile <(kubectl create -f components/sidecar/0_istio-sidecar-injector-configmap-debug.yaml --dry-run -o=jsonpath='{.data.config}') -f <(kontemplate template environments/dev.yaml  -i application/test))

```
