### ISSUE TITLE
Bug with Envoy Filter and specification of internal_redirect_policy

### ISSUE THREAD

**Issue by witold-gren** [istio/istio#45254]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When I defined `EnvoyFilter` and we try to set `internal_redirect_policy` the envoy sidecar stop working. Below is an example of a filter: 
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: allow-cross-scheme-redirect
spec:
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: MERGE
        value:
          name: "envoy.filters.network.http_connection_manager"
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
            route_config:
              name: allow-cross-scheme-redirect
              virtual_hosts:
                - name: allow-cross-scheme-redirect
                  domains:
                    - "environment.data.gov.uk"
                  routes:
                    - name: allow-cross-scheme-redirect
                      match:
                        prefix: /
                      route:
                        internal_redirect_policy:
                          max_internal_redirects: 5
                          allow_cross_scheme_redirect: true
```
After I checked logs from sidecar I see this information:
```
0.0.0.0_15010: Proto constraint validation failed (HttpConnectionManagerValidationError.RouteConfig: embedded message failed validation | caused by RouteConfigurationValidationError.VirtualHosts[0]: embedded message failed validation | caused by VirtualHostValidationError.Routes[0]: embedded message failed validation | caused by RouteValidationError.Route: embedded message failed validation | caused by field: "cluster_specifier", reason: is required): stat_prefix: "outbound_0.0.0.0_15010"
route_config {
  name: "allow-cross-scheme-redirect"
  virtual_hosts {
    name: "allow-cross-scheme-redirect"
    domains: "environment.data.gov.uk"
    routes {
      match {
        prefix: "/"
      }
      route {
        internal_redirect_policy {
          max_internal_redirects {
            value: 10
          }
          allow_cross_scheme_redirect: true
        }
      }
      name: "allow-cross-scheme-redirect"
    }
  }
}
...
2023-06-02T09:31:52.168157Z	warn	Envoy proxy is NOT ready: config received from XDS server, but was rejected: cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 1 rejected
2023-06-02T09:31:52.670100Z	warn	Envoy proxy is NOT ready: config received from XDS server, but was rejected: cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 1 rejected
```
I checked my envoy version:
```
$ envoy --version
envoy  version: d799381810ae54f1cccb2a9ae79d9c6191ca2c83/1.25.4-dev/Clean/RELEASE/BoringSSL
```
When we go to documentation https://www.envoyproxy.io/docs/envoy/v1.25.6/api-v3/config/route/v3/route_components.proto.html#config-route-v3-routeaction we will not find anything about configuration of `cluster_specifier`. 

When I try to add such an empty field to my config: 
```
...
                      route:
                        cluster_specifier: ""
                        internal_redirect_policy:
                          max_internal_redirects: 5
                          allow_cross_scheme_redirect: true
```
then I have information that is a wrong configuration:
```
Warning: Envoy filter: can't unmarshal Any nested proto type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager: unknown field "cluster_specifier" in envoy.config.route.v3.RouteAction
envoyfilter.networking.istio.io/allow-cross-scheme-redirect configured
```

### Version

```Text
$ istioctl version
client version: 1.17.2
control plane version: 1.17.2
data plane version: 1.17.0 (3 proxies), 1.17.2 (273 proxies)
$ kubectl version --short
Client Version: v1.25.9
Kustomize Version: v4.5.7
Server Version: v1.23.17-eks-0a21954
$ helm version --short
v3.10.2+g50f003e
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
