### ISSUE TITLE
tests integration pilot can not use node port for service

### ISSUE THREAD

**Issue by vaxilicaihouxian** [istio/istio#45262]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

The manifests yaml files use constant port.Then when we use kind with script `./prow/integ-suite-kind.sh --topology MULTICLUSTER` build k8s clusters and run tests,the service use constant port (15012,15017...).The istio eastwest service use node port that can not be these constant ports.
Example:
```
{{- if .Values.global.remotePilotAddress }}
  {{- if .Values.pilot.enabled }}
apiVersion: v1
kind: Endpoints
metadata:
  name: istiod-remote
  namespace: {{ .Release.Namespace }}
subsets:
- addresses:
  - ip: {{ .Values.global.remotePilotAddress }}
  ports:
  - port: 15012
    name: tcp-istiod
    protocol: TCP
  {{- else if regexMatch "^([0-9]*\\.){3}[0-9]*$" .Values.global.remotePilotAddress }}
apiVersion: v1
kind: Endpoints
metadata:
  name: istiod
  namespace: {{ .Release.Namespace }}
subsets:
- addresses:
  - ip: {{ .Values.global.remotePilotAddress }}
  ports:
  - port: 15012
    name: tcp-istiod
    protocol: TCP
  {{- end }}
---
{{- end }}
```

### Version

```Text
1.13.2
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
