### ISSUE TITLE
UNAVAILABLE: upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 111

### ISSUE THREAD

**Issue by anup1384** [istio/istio#45261]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When attempting to bring down the Spring Boot pods(more than 10 pods at same time), I encountered the error message at client end "UNAVAILABLE: upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 111." This error occurred while the traffic was being routed through Istio, which serves as the service mesh for the Spring Boot application.
Client have URL for GRPC-
http://app-service.test.svc.cluster.local:9090
and for rest
http://abc.com/app-service

Container spec
```
    spec:
      containers:
      - command:
        - java
        - -Dspring.profiles.active=dev
        - -Dserver.shutdown=graceful
        - -jar
        - /app/app.jar
        envFrom:
        - configMapRef:
            name: app-config
        image: app-spring:v1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        name: app-service
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
```
Services yaml
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-service
  name: app-service
  namespace: test
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  - name: grpc
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
      app: app-service
  type: ClusterIP
 ---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-service
  name: app-service-canary
  namespace: test
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  - name: grpc
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
      app: app-service
  type: ClusterIP
```
virtual services for rest and grpc
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app: app-service
  name: app-service
  namespace: test
spec:
  gateways:
  - gateway-new
  hosts:
  - abc.com
  http:
  - match:
    - uri:
        prefix: /app-service
    name: primary
    route:
    - destination:
        host: app-service
        port:
          number: 8080
      weight: 100
    - destination:
        host: app-service-canary
        port:
          number: 8080
      weight: 0
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app: app-service
spec:
  gateways:
  - mesh
  hosts:
  - app-service.test.svc.cluster.local
  http:
  - name: internal
    route:
    - destination:
        host: app-service
        port:
          number: 9090
      weight: 100
    - destination:
        host: app-service-canary
        port:
          number: 9090
      weight: 0
```

### Version

```Text
$ istioctl version                                                                                                                       
client version: 1.15.7
istiod version: 1.15.7
data plane version:1.15.7 (1890 proxies)
$ kubectl version --short   
Client Version: v1.23.4
Server Version: v1.22.17-eks-0a21954
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
