### ISSUE TITLE
Improve VirtualService CRD to increase security

### ISSUE THREAD

**Issue by etifontaine** [istio/istio#45279]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

CustomResourceDefinition defines the schema of Istio ressources. CRD can be used on a CI/CD pipeline to validate the ressources and make sure the YAML is valid. 
However, if some fields are missing but the YAML is still valid, the ressource can be pushed to the cluster and actually break the Service Mesh.

For example:
````
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: my-service
  namespace: default
spec:
  hosts:
    - "my-service.default.svc.cluster.local"
  http:
    - name: my-service-status-update
      match:
        - uri:
            regex: "/v1/status"
          method:
            exact: "GET"
````
Is valid on the current VirtualService CRD, istiod will push the config to the proxies and they will break because a destination is missing.

We should improve CRD to handle such use cases, and in the future also handle it on istiod directly.

### Version

```Text
Istio: 1.17.1
Kubernetes: 1.26.3
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [X] Test and Release
- [X] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
