### ISSUE TITLE
Cannot disable prometheus metrics on default profile

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#45292]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Installing 1.18 RC I see that prometheus metrics are now emitted without any config.
This is because "defaultProviders" was set to "prometheus".
However, that means to disable prometheus, I need this config:

```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  metrics:
  - providers:
    - name: prometheus
    overrides:
    - disabled: true
```

However, this is not doing what I want it to do - to stop making metrics and save on CPU. See xDS:

```
"name": "istio.stats",
           "typed_config": {
            "@type": "[type.googleapis.com/stats.PluginConfig](http://type.googleapis.com/stats.PluginConfig)",
            "metrics": [
             {
              "name": "request_messages_total",
              "drop": true
             },
             {
              "name": "response_messages_total",
              "drop": true
             },
             {
              "name": "requests_total",
              "drop": true
             },
             {
              "name": "request_duration_milliseconds",
              "drop": true
             },
             {
              "name": "request_bytes",
              "drop": true
             },
             {
              "name": "response_bytes",
              "drop": true
             },
             {
              "name": "tcp_connections_closed_total",
              "drop": true
             },
             {
              "name": "tcp_connections_opened_total",
              "drop": true
             },
             {
              "name": "tcp_received_bytes_total",
              "drop": true
             },
             {
              "name": "tcp_sent_bytes_total",
              "drop": true
             }
            ]
```

This xDS actually does the worst thing - it makes the metrics and then deletes them.

### Version

```Text
1.18
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [x] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by kyessenov** [comment]
cc @howardjohn @zirain @lei-tang

**Comment by howardjohn** [comment]
```yaml
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  metrics:
  - providers:
    - name: prometheus
    overrides:
    - disabled: true
      match:
        metric: ALL_METRICS
```

works around it. I will send a PR
