### ISSUE TITLE
istioctl analyze for gateway TLS parse problem

### ISSUE THREAD

**Issue by taitelman** [istio/istio#45324]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)
**Describe the feature request**
I badly rotated my istio gateway HTTPS cert secret. The certificate was corrupted .
istio ingress gateway pod reported (v1.16.4) a tiny warning:
```
Jun 6 18:03:21 xxx-ingressgateway-7c5c96bbc-8cf7t istio-proxy warning envoy config	gRPC config for type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret rejected: Failed to load certificate chain from <inline> 
```
 
any request sent to that such badly configured mesh got an SSL handshake error:
```
*  CAfile: /etc/pki/tls/certs/ca-bundle.crt
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.0 (OUT), TLS header, Unknown (21):
* TLSv1.3 (OUT), TLS alert, decode error (562):
```

if you want to reproduce simply take two pem files 
and connect them badly to one file that will look like:
```
-----BEGIN CERTIFICATE-----
MIIBGDCBvgIJAM43mDwwTa1vMAoGCCqGSM49BAMCMBQxEjAQBgNVBAMMCWlzdGlv
LmNvbTAeFw0yMzA2MDkwOTE1MDlaFw0yNDA2MDgwOTE1MDlaMBQxEjAQBgNVBAMM
CWlzdGlvLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABGB97ZHTF5Kf7br1
2h+Ee6OQR+FA5ZabWnCrMlrXWw5yz8thn38l8p1PkEvTj5zGo5L3LHxtT5tkQ6sX
z66Q51MwCgYIKoZIzj0EAwIDSQAwRgIhAJCUNFmFD9pQ8aib7xtMCSxZU7pFf9TF
239+n1YyVrROAiEArr8VreiAWx3Q/04BvZBig7fLbAJT2CVl6eFia9lSnBk=
-----END CERTIFICATE----------BEGIN CERTIFICATE-----
MIIBMjCB2AIJAN7bbihOl29BMAoGCCqGSM49BAMCMBQxEjAQBgNVBAMMCWlzdGlv
LmNvbTAeFw0yMzA2MDkwOTE3MTdaFw0yNDA2MDgwOTE3MTdaMC4xEjAQBgNVBAoM
CWlzdGlvLmNvbTEYMBYGCSqGSIb3DQEJARYJYS5iQGMuY29tMFkwEwYHKoZIzj0C
AQYIKoZIzj0DAQcDQgAEQ0NVrAOBQNXdN0u6OVhbmpHuicum/XnnCX2GUcjan++h
OHhlQQ+iKer1PNwiP656ENkdTJoMQUGjJefkSWWj5TAKBggqhkjOPQQDAgNJADBG
AiEAoGvxpfcIEjv8wYySmkQECw8JgRUGafHcA7L18IWtd4QCIQCGGMOTPnZhdMHx
KJeYSapMc81N4dd5VKZvCBF6H1TB8Q==
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
MIIBMjCB2AIJAN7bbihOl29BMAoGCCqGSM49BAMCMBQxEjAQBgNVBAMMCWlzdGlv
LmNvbTAeFw0yMzA2MDkwOTE3MTdaFw0yNDA2MDgwOTE3MTdaMC4xEjAQBgNVBAoM
CWlzdGlvLmNvbTEYMBYGCSqGSIb3DQEJARYJYS5iQGMuY29tMFkwEwYHKoZIzj0C
AQYIKoZIzj0DAQcDQgAEQ0NVrAOBQNXdN0u6OVhbmpHuicum/XnnCX2GUcjan++h
OHhlQQ+iKer1PNwiP656ENkdTJoMQUGjJefkSWWj5TAKBggqhkjOPQQDAgNJADBG
AiEAoGvxpfcIEjv8wYySmkQECw8JgRUGafHcA7L18IWtd4QCIQCGGMOTPnZhdMHx
KJeYSapMc81N4dd5VKZvCBF6H1TB8Q==
-----END CERTIFICATE-----
```

and save it as your K8s secret : `my-private-tls`

```
  apiVersion: networking.istio.io/v1beta1
  kind: Gateway
  metadata:
    name: private-istio-gateway
    namespace: custom-gateways
  spec:
    selector:
      istio: custom-ingressgateway
    servers:
    - hosts:
      - '*.private.mydomain.com'
      port:
        name: https-custom
        number: 443
        protocol: HTTPS
      tls:
        credentialName: my-private-tls
        mode: SIMPLE
    - hosts:
      - '*.private.mydomain.com'
      port:
        name: http-custom
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
```

**Describe alternatives you've considered**
I want to raise the log level to an `error` . current warning is not very descriptive. may want to add "future SSL handshakes will fail."

**Affected product area (please put an X in all that apply)**

[ ] Ambient
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[x] Multi Cluster
[x] Virtual Machine
[x] Multi Control Plane

**Additional context**
