### ISSUE TITLE
Istio virtual service multiple services with the same host

### ISSUE THREAD

**Issue by Rez0k** [istio/istio#45332]
Hi,

I have multiple services that listen to the same host by different urls, for example:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vsc-A
spec:
  hosts:
    - "www.example.com"
  gateways:
  - example-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: service-A
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vsc-B
spec:
  hosts:
    - "www.example.com"
  gateways:
  - example-gateway
  http:
  - match:
    - uri:
        prefix: /api
    route:
    - destination:
        port:
          number: 80
        host: service-B
```
I want a virtual service for each service because I manage my services with helm and I don't want to create one big virtual service with multiple rules and a catch all rule at the end out of any service chart.
It will become difficult for me to manage those services http rules with helm.

I read the discussion at https://github.com/istio/istio/issues/10464 and wanted to ask, waht are my options.

Thanks!
