### ISSUE TITLE
TLS key logging via envoy filter is not applied

### ISSUE THREAD

**Issue by Anonymous-Coward** [istio/istio#45392]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I am trying to enable TLS key logging for use with wireshark traffic capturing, using the element `key_log` in [CommonTlsContext](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/tls.proto.html#extensions-transport-sockets-tls-v3-commontlscontext), using the following **steps**.

I created an envoy filter like so:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: keylog-envoy-filter
  namespace: istio-system
spec:
  configPatches:
    - applyTo: FILTER_CHAIN
      match:
        context: GATEWAY
        listener:
          portNumber: 443
      patch:
        operation: MERGE
        value:
          transport_socket:
            name: "envoy.transport_sockets.tls"
            typed_config:
              "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext"
              common_tls_context:
                key_log:
                  path: /tmp/session_keys.log
```
applied it using `kubectl apply`, and received no errors:

```
$ k -n istio-system apply -f envoyfilter.yaml 
envoyfilter.networking.istio.io/keylog-envoy-filter created
```
Then I used `istioctl dashboard envoy` to look at the listener configuration. The element `key_log` was not added:
![image](https://github.com/istio/istio/assets/2550856/99b36424-08c8-43e6-9fe6-fce8dcfae1c6)

If I open a shell into one of the istio ingress gateway pods, I don't see any file created in `/tmp` either. The newly added configuration doesn't appear anywhere in the configuration dump.

I would have **expected** either an error, or at least a warning, when trying to apply the filter or the new configuration element to appear _somewhere_ in the configuration. 

**Actually**, the new configuration element is accepted but ignored silently, and not added anywhere into the configuration.

### Version

```Text
$ istioctl version
client version: 1.17.1
control plane version: 1.16.0
data plane version: 1.16.0 (2 proxies)
$ k version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.10
Kustomize Version: v4.5.7
Server Version: v1.25.5
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by hexiaodai** [comment]
```yaml
...
spec:
  configPatches:
    - applyTo: FILTER_CHAIN
      match:
        context: GATEWAY
        listener:
          portNumber: 443
...
```
Is your gateway listening on port 443?

<img width="454" alt="image" src="https://github.com/istio/istio/assets/40925990/4f3faa94-e597-4611-8b71-768aef567d3a">
