### ISSUE TITLE
 Issue with AuthorizationPolicy configuration for JWT authentication in Istio

### ISSUE THREAD

**Issue by SammyFidato** [istio/istio#45408]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We are currently facing an issue with the configuration of the Istio AuthorizationPolicy for JWT authentication. Our objective is to implement JWT authentication for traffic originating from outside the namespace while allowing requests within the namespace to proceed without authentication.

Here is the current configuration we have:

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  annotations:
  name: auth-policy
  namespace: istio-system
spec:
  rules:
  - from:
    - source:
        requestPrincipals:
          - '*'
    - source:
        notNamespaces:
          - <namespace>
  selector:
    matchLabels:
      <key>: <value>
```

```
apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: jwt
  namespace: istio-system
spec:
  selector:
    matchLabels:
      <key>: <value>
  jwtRules:
  - issuer: "<issuer>"
    jwksUri: "<jwksUri>"
    fromHeaders:
    - name: x-jwt-assertion
      prefix: "Bearer "
```

The problem we are encountering is that requests within the namespace are also requiring authentication when we use the notNamespaces field instead of namespaces in the AuthorizationPolicy configuration. We expected that requests within the specified namespace would be exempt from authentication.

We kindly request assistance in resolving this issue. Any suggestions or guidance on the correct configuration to achieve the desired behavior would be greatly appreciated.

Thank you in advance for your help!

### Version

```Text
client version: 1.15.2
control plane version: 1.15.2
data plane version: 1.15.2 (104 proxies)
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [X] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [X] Control Plane Revisions

**Comment by howardjohn** [comment]
```
    - source:
        requestPrincipals:
        - '*'
	- source:
        notNamespaces:
        - <namespace>
```

Indent on second 'source' is broken?

should be

```
    - source:
        requestPrincipals:
        - '*'
    - source:
        notNamespaces:
        - <namespace>
```

Not sure if that is just the github issue though or in your actual cluster?

**Comment by SammyFidato** [comment]
Sorry that was just in the github while posting the question

I have updated the intend in the post

**Comment by hexiaodai** [comment]
```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: auth-policy
  namespace: istio-system
spec:
  rules:
  - from:
    - source:
        requestPrincipals:
          - '*'
    - source:
        notNamespaces:
          - test-namespace
  selector:
    matchLabels:
      app: istio-ingressgateway
```

Use kubectl to access the pods deployed under test-namespace.
```base
# Note, do not add x-jwt-assertion to the http header

curl -k https://istio-ingressgateway.istio-system.svc.cluster.local/apis
{"msg": "ok"}

# If you add the wrong x-jwt-assertion to the http header
curl -k -H 'add x-jwt-assertion: Bearer faketoken' https://istio-ingressgateway.istio-system.svc.cluster.local/apis
Jwks doesn't have key to match kid or alg from Jwt
```
