### ISSUE TITLE
How to update histogram metrics?

### ISSUE THREAD

**Issue by unitrade** [istio/istio#45405]
I am newer at istio. Can you help me please

For high cardinality metrics I need to update histogram metrics, so I remove some buckets

For test at local envoy config:
```
stats_config:
  histogram_bucket_settings:
    - match:
        contains: "envoy_cluster_upstream_cx_connect_ms"
      buckets: [1,5,50,500,5000,10000]
    - match:
        contains: "envoy_cluster_upstream_cx_length_ms"
      buckets: [1000,10000,60000,600000]
```
Local its work fine

But in k8s cluster for istio I write EnvoyFilter and its not work for me
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: envoy-filter-1.1
  namespace: istio-system
spec:
  configPatches:
    - applyTo: NETWORK_FILTER # patch at the network filter level
      match:
        context: ANY # for both gateway and sidecar
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: MERGE # operation to perform (MERGE, ADD, REMOVE)
        value:
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
            stats_config:
              histogram_bucket_settings:
                - match:
                    contains: "envoy_cluster_upstream_cx_connect_ms"
                  buckets: [1,5,50,500,5000,10000]
                - match:
                    contains: "envoy_cluster_upstream_cx_length_ms"
                  buckets: [1000,10000,60000,600000]

```
version
```
envoy --version
envoy  version: 2b6009118109b480e1d5abf3188fd7d9c0c0acf0/1.22.1-dev/Clean/RELEASE/BoringSSL
```

**Comment by zirain** [comment]
IIRC, the `stats_config` should be part of bootstrap not listener.

can you take a look at https://github.com/istio/istio/pull/45368?

**Comment by unitrade** [comment]
@zirain not sure
I try this also
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: envoy-stats-1
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: BOOTSTRAP
    patch:
      operation: MERGE
      value:
        stats_config:
          histogram_bucket_settings:
            - match:
                contains: "connect"
              buckets: [1,5,50,500,5000,10000]
            - match:
                contains: "length"
              buckets: [1000,10000,60000,600000]
```

**Comment by unitrade** [comment]
May be this help:
```
istioctl proxy-config listeners istio-ilbgateway-5b6fbc4564-v469f -n istio-system --port 15090 -o json
[
    {
        "address": {
            "socketAddress": {
                "address": "0.0.0.0",
                "portValue": 15090
            }
        },
        "filterChains": [
            {
                "filters": [
                    {
                        "name": "envoy.filters.network.http_connection_manager",
                        "typedConfig": {
                            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
                            "statPrefix": "stats",
                            "routeConfig": {
                                "virtualHosts": [
                                    {
                                        "name": "backend",
                                        "domains": [
                                            "*"
                                        ],
                                        "routes": [
                                            {
                                                "match": {
                                                    "prefix": "/stats/prometheus"
                                                },
                                                "route": {
                                                    "cluster": "prometheus_stats"
                                                }
                                            }
                                        ]
                                    }
                                ]
                            },
                            "httpFilters": [
                                {
                                    "name": "envoy.filters.http.router",
                                    "typedConfig": {
                                        "@type": "type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"
                                    }
                                }
                            ]
                        }
                    }
                ]
            }
        ]
    }
]
```
and this
```
istioctl proxy-config bootstrap -n istio-system istio-ilbgateway-5b6fbc4564-v469f 
"staticResources": {
            "listeners": [
                {
                    "address": {
                        "socketAddress": {
                            "address": "0.0.0.0",
                            "portValue": 15090
                        }
                    },
                    "filterChains": [
                        {
                            "filters": [
                                {
                                    "name": "envoy.filters.network.http_connection_manager",
                                    "typedConfig": {
                                        "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
                                        "statPrefix": "stats",
                                        "routeConfig": {
                                            "virtualHosts": [
                                                {
                                                    "name": "backend",
                                                    "domains": [
                                                        "*"
                                                    ],
                                                    "routes": [
                                                        {
                                                            "match": {
                                                                "prefix": "/stats/prometheus"
                                                            },
                                                            "route": {
                                                                "cluster": "prometheus_stats"
                                                            }
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        "httpFilters": [
                                            {
                                                "name": "envoy.filters.http.router",
                                                "typedConfig": {
                                                    "@type": "type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"
                                                }
                                            }
                                        ]
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    "address": {
                        "socketAddress": {
                            "address": "0.0.0.0",
                            "portValue": 15021
                        }
                    },
                    "filterChains": [
                        {
                            "filters": [
                                {
                                    "name": "envoy.filters.network.http_connection_manager",
                                    "typedConfig": {
                                        "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
                                        "statPrefix": "agent",
                                        "routeConfig": {
                                            "virtualHosts": [
                                                {
                                                    "name": "backend",
                                                    "domains": [
                                                        "*"
                                                    ],
                                                    "routes": [
                                                        {
                                                            "match": {
                                                                "prefix": "/healthz/ready"
                                                            },
                                                            "route": {
                                                                "cluster": "agent"
                                                            }
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        "httpFilters": [
                                            {
                                                "name": "envoy.filters.http.router",
                                                "typedConfig": {
                                                    "@type": "type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"
                                                }
                                            }
                                        ]
                                    }
                                }
                            ]
                        }
                    ]
                }
            ],
```

**Comment by unitrade** [comment]
@zirain thank you
I just enable Bootstrap for EnvoyFilter and use this:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: envoy-stats-1
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: BOOTSTRAP
    patch:
      operation: MERGE
      value:
        stats_config:
          histogram_bucket_settings:
            - match:
                contains: "connect"
              buckets: [1,5,50,500,5000,10000]
            - match:
                contains: "length"
              buckets: [1000,10000,60000,600000]
```
![image](https://github.com/istio/istio/assets/28563126/6feb36af-7f3a-4044-8771-768bd829d7c2)

**Comment by zirain** [comment]
@unitrade can we close this ticket?

**Comment by unitrade** [comment]
@zirain yes

**Comment by iPapanya** [comment]
> enable Bootstrap for EnvoyFilter

could you tell me exactly how you turned on Bootstrap for EnvoyFilter

**Comment by unitrade** [comment]
@iPapanya 
You must set env 
`BOOTSTRAP_XDS_AGENT: "true"`
Here [example](https://github.com/istio/istio/issues/40903#issuecomment-1242693063)

**Comment by zirain** [comment]
For people who are interesting, there's a new way to do this (will be avaliable in v1.19): https://github.com/istio/istio.io/pull/13360

**Comment by iPapanya** [comment]
> @iPapanya You must set env `BOOTSTRAP_XDS_AGENT: "true"` Here [example](https://github.com/istio/istio/issues/40903#issuecomment-1242693063) And then do not forget rollout

@unitrade 
I try to enable by using ProxyConfig (https://istio.io/latest/docs/reference/config/networking/proxy-config/)

`# Source: app-base/templates/proxyconfig.yaml
apiVersion: networking.istio.io/v1beta1
kind: ProxyConfig
metadata:
  name: debug-service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: debug-service
      app.kubernetes.io/instance: debug-service
  environmentVariables:
    BOOTSTRAP_XDS_AGENT: "true"
`

and after rollout see that it applied 

istio-proxy@debug-service-5f7d85b48b-qrrfn:/$ printenv | grep BOOTSTRAP_XDS_AGENT
BOOTSTRAP_XDS_AGENT=true

But EnvoyFilter does not work
`apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: debug-service-histogram-bucket-settings
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/name: debug-service
      app.kubernetes.io/instance: debug-service
  configPatches:
    - applyTo: BOOTSTRAP
      patch:
        operation: MERGE
        value:
          stats_config:
            histogram_bucket_settings:
              - match:
                  prefix: istio
                buckets:
                   - 9
                   - 99
                   - 999
                   - 9999
                   - 99999
`

`istio-proxy@debug-service-5f7d85b48b-qrrfn:/$ curl localhost:15020/stats/prometheus | grep istio | grep "le=" | grep 9999
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  113k    0  113k istio_agent_go_gc_heap_allocs_by_size_bytes_total_bucket{le="8.999999999999998"} 7506
   istio_agent_go_gc_heap_allocs_by_size_bytes_total_bucket{le="24.999999999999996"} 62566
0  istio_agent_go_gc_heap_allocs_by_size_bytes_total_bucket{le="64.99999999999999"} 133791
   istio_agent_go_gc_heap_allocs_by_size_bytes_total_bucket{le="144.99999999999997"} 206877
0  istio_agent_go_gc_heap_allocs_by_size_bytes_total_bucket{le="320.99999999999994"} 223744
22.istio_agent_go_gc_heap_allocs_by_size_bytes_total_bucket{le="704.9999999999999"} 229411
1M istio_agent_go_gc_heap_allocs_by_size_bytes_total_bucket{le="1536.9999999999998"} 237539
  istio_agent_go_gc_heap_allocs_by_size_bytes_total_bucket{le="3200.9999999999995"} 238196
   istio_agent_go_gc_heap_allocs_by_size_bytes_total_bucket{le="6528.999999999999"} 239191
0 istio_agent_go_gc_heap_allocs_by_size_bytes_total_bucket{le="13568.999999999998"} 239436
--:istio_agent_go_gc_heap_allocs_by_size_bytes_total_bucket{le="27264.999999999996"} 239614
--:istio_agent_go_gc_heap_frees_by_size_bytes_total_bucket{le="8.999999999999998"} 1362
-- istio_agent_go_gc_heap_frees_by_size_bytes_total_bucket{le="24.999999999999996"} 33896
--:istio_agent_go_gc_heap_frees_by_size_bytes_total_bucket{le="64.99999999999999"} 83304
--:istio_agent_go_gc_heap_frees_by_size_bytes_total_bucket{le="144.99999999999997"} 140135
-- istio_agent_go_gc_heap_frees_by_size_bytes_total_bucket{le="320.99999999999994"} 152179
--:istio_agent_go_gc_heap_frees_by_size_bytes_total_bucket{le="704.9999999999999"} 155424
--:istio_agent_go_gc_heap_frees_by_size_bytes_total_bucket{le="1536.9999999999998"} 162790
-- istio_agent_go_gc_heap_frees_by_size_bytes_total_bucket{le="3200.9999999999995"} 163065
22.istio_agent_go_gc_heap_frees_by_size_bytes_total_bucket{le="6528.999999999999"} 163775
1Mistio_agent_go_gc_heap_frees_by_size_bytes_total_bucket{le="13568.999999999998"} 163847

istio_agent_go_gc_heap_frees_by_size_bytes_total_bucket{le="27264.999999999996"} 163927
istio_agent_go_gc_pauses_seconds_total_bucket{le="9.999999999999999e-10"} 0
istio_agent_go_gc_pauses_seconds_total_bucket{le="9.999999999999999e-09"} 0
istio_agent_go_gc_pauses_seconds_total_bucket{le="9.999999999999998e-08"} 0
istio_agent_go_gc_pauses_seconds_total_bucket{le="1.0239999999999999e-06"} 0
istio_agent_go_gc_pauses_seconds_total_bucket{le="1.0239999999999999e-05"} 2
istio_agent_go_gc_pauses_seconds_total_bucket{le="0.00010239999999999998"} 15
istio_agent_go_gc_pauses_seconds_total_bucket{le="0.0010485759999999998"} 21
istio_agent_go_gc_pauses_seconds_total_bucket{le="0.010485759999999998"} 21
istio_agent_go_gc_pauses_seconds_total_bucket{le="0.10485759999999998"} 22
istio_agent_go_sched_latencies_seconds_bucket{le="9.999999999999999e-10"} 917
istio_agent_go_sched_latencies_seconds_bucket{le="9.999999999999999e-09"} 917
istio_agent_go_sched_latencies_seconds_bucket{le="9.999999999999998e-08"} 1462
istio_agent_go_sched_latencies_seconds_bucket{le="1.0239999999999999e-06"} 2365
istio_agent_go_sched_latencies_seconds_bucket{le="1.0239999999999999e-05"} 2448
istio_agent_go_sched_latencies_seconds_bucket{le="0.00010239999999999998"} 2610
istio_agent_go_sched_latencies_seconds_bucket{le="0.0010485759999999998"} 2625
istio_agent_go_sched_latencies_seconds_bucket{le="0.010485759999999998"} 2625
istio_agent_go_sched_latencies_seconds_bucket{le="0.10485759999999998"} 2626`

**Comment by unitrade** [comment]
1. Do you check that env BOOTSTRAP_XDS_AGENT  was set for debug-service?
2. Try change prefix to contains, should be work
```
histogram_bucket_settings:
  - match:
       contains: istio
     buckets:
```
