### ISSUE TITLE
VirtualService traffic shifting not respected by traffic originating from ServiceEntry

### ISSUE THREAD

**Issue by roee-landesman** [istio/istio#45401]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have a k8s cluster with the following setup:

Traffic originating from app A, heading towards a hostname (`service-B-alias.local`) defined in a ServiceEntry configured as such:

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
spec:
  endpoints:
    - address: serviceB.namespace-B.svc.cluster.local
  hosts:
    - service-B-alias.local
  location: MESH_INTERNAL
  ports:
    - name: http
      number: 80
      protocol: TCP
  resolution: DNS
```

Traffic does in fact make it from app A to app B, (DNS resolution works fine in the sidecar proxy), however when trying to apply a virtualservice (See below) for traffic shifting behavior, the `.local` hostname is not being matched and the traffic is split round-robin 50/50.

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
spec:
  hosts:
    - service-B-alias.local
  http:
    - match:
        - uri:
            prefix: /
      name: primary
      route:
        - destination:
            host: serviceB.namespace-B.svc.cluster.local
            subset: stable
          weight: 99
        - destination:
            host: serviceB.namespace-B.svc.cluster.local
            subset: canary
          weight: 1
```

I'm not sure where this is going wrong, any debugging help would be greatly appreciated. Thanks!

### Version

```Text
client version: 1.17.2
control plane version: 1.16.4
data plane version: 1.16.4 (245 proxies)

Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.23.17-eks-0a21954

v3.12.0+gc9f554d
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
