### ISSUE TITLE
External authorization fails when using an HTTPS ServiceEntry to a service outside the mesh

### ISSUE THREAD

**Issue by ajpauwels** [istio/istio#45414]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When attempting to use an authorization service external to the mesh, the authorization request fails with a 503 error and the following error in the sidecar debug logs:

```
2023-06-12T11:26:29.615719Z    debug    envoy router external/envoy/source/common/router/router.cc:1274    [C0][S481425681128483792] upstream reset: reset reason: connection termination, transport failure reason:     thread=24
```

The external authorization provider plugin looks like this:

```
      extensionProviders:
      - name: oauth2-proxy
        envoyExtAuthzHttp:
          service: "auth.mydomain.com"
          port: "443"
          includeRequestHeadersInCheck:
          - "authorization"
          - "cookie"
          - "x-forwarded-for"
          headersToUpstreamOnAllow:
          - "authorization"
          - "cookie"
          - "path"
          - "x-forwarded-id-token"
          - "x-forwarded-access-token"
          - "x-forwarded-refresh-token"
          - "x-forwarded-for"
          - "x-forwarded-user"
          - "x-forwarded-groups"
          - "x-forwarded-email"
          - "x-forwarded-preferred-username"
          headersToDownstreamOnDeny:
          - "content-type"
          - "set-cookie"
          headersToDownstreamOnAllow:
          - "x-forwarded-id-token"
          - "x-forwarded-access-token"
          - "x-forwarded-refresh-token"
          - "x-forwarded-for"
          - "x-forwarded-user"
          - "x-forwarded-groups"
          - "x-forwarded-email"
          - "x-forwarded-preferred-username"
          includeAdditionalHeadersInCheck:
            x-auth-request-redirect: "https://%REQ(:authority)%%REQ(x-envoy-original-path?:path)%"
```

And the ServiceEntry for the external service looks like this:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-authz-https
  namespace: i-istio-system
spec:
  hosts:
  - "auth.mydomain.com"
  location: MESH_EXTERNAL
  ports:
  - name: https
    number: 443
    protocol: HTTPS
  resolution: DNS
```

The cluster is definitely recognized and the request is directed to it as evidenced by these logs:

```
2023-06-12T11:26:29.613114Z    debug    envoy rbac external/envoy/source/extensions/filters/http/rbac/rbac_filter.cc:130    shadow denied, matched policy istio-ext-authz-ns[t-tenant-main]-policy[nodejs-example-dev]-rule[0]    thread=2
2023-06-12T11:26:29.613125Z    debug    envoy rbac external/envoy/source/extensions/filters/http/rbac/rbac_filter.cc:167    no engine, allowed by default    thread=24
2023-06-12T11:26:29.613232Z    debug    envoy router external/envoy/source/common/router/router.cc:478    [C0][S481425681128483792] cluster 'outbound|443||auth.mydomain.com' match for URL '/secure'    thread=24
```

IMPORTANT NOTE: This is a single-stack IPv6 cluster. I went down a debug path where I discovered that ServiceEntries in single-stack IPv6 have a listener generated that listens on `0.0.0.0` instead of `::`. I wrote an EnvoyFilter that updates the listener to `::` which allowed proper resolution of the addresses inside of pods, but the auth continues to fail.

### Version

```Text
$ istioctl version
client version: 1.16.1
control plane version: 1.17-dev
data plane version:  (36 proxies)

$ kubectl version --short
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.27.1-eks-2f008fe
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
