### ISSUE TITLE
mTLS ingress gateway with Cert manager doesn't offer CA override to verify client

### ISSUE THREAD

**Issue by fouadsemaan** [istio/istio#45449]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Currently a single secret containing the cert, key and CA can be specified. Cert manager allows for automated generated cert as secret with CA being the one used to sign the Cert as such:

```
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: MUTUAL
      credentialName: httpbin-credential # must be the same as secret
    hosts:
    - httpbin.example.com
```

How does one specify a CA to verify client if we're taking the secret/CM route?

Would love to be able to do something as  follows:

```
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: MUTUAL
      credentialName: httpbin-credential # must be the same as secret
      caName: clientCA
    hosts:
    - httpbin.example.com
```
The [docs](https://istio.io/latest/docs/reference/config/networking/gateway/#ServerTLSSettings) seems to suggest that if you specify secret "httpbin-credential" it will look for secret "httpbin-credential-cacert" if it exists and use that to verify client cert.

```
credentialName --> For gateways running on Kubernetes, the name of the secret that holds the TLS certs including the CA certificates. Applicable only on Kubernetes. An Opaque secret should contain the following keys and values: key: <privateKey> and cert: <serverCert>. For mutual TLS, cacert: <CACertificate> can be provided in the same secret or a separate secret named <secret>-cacert. A TLS secret for server certificates with an additional ca.crt key for CA certificates is also supported. Only one of server certificates and CA certificate or credentialName can be specified.
```

[ ] Ambient
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**
mTLS ingress gateway
[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
