### ISSUE TITLE
Could not assign priorityClass

### ISSUE THREAD

**Issue by akheel5544** [istio/istio#45443]
I am trying to assign priorityclass to the release name internal-ingressgateway in an aks cluster, no matter where I assign the priorityclassname it is not working.

Below is my helm release and helm repository for your reference:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gateway
  namespace: istio-system
spec:
  dependsOn:
  - name: istiod
    namespace: istio-system
  releaseName: internal-ingressgateway
  targetNamespace: istio-system
  timeout: "10m"
  chart:
    spec:
      chart: gateway
      version: '1.16.1'
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  interval: 24h
  serviceAccountName: "ns-sa-op-istio-system"
  values:
    imagePullSecrets:
      - name: image-pull-secret
    priorityClassName: deployment-priority-high
    replicaCount: 3
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80
    service:
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
        service.beta.kubernetes.io/alicloud-loadbalancer-address-type: "intranet"
      ports:
      - name: status-port
        port: <>
        protocol: <>
        targetPort: <>
```
