### ISSUE TITLE
Istio-operator add component labels caused significant impact

### ISSUE THREAD

**Issue by Patrick0308** [istio/istio#45457]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When adding a label on exist eastwest gateway by modify istio-operator. 
```yaml
  components:
    ingressGateways:
    - enabled: false
      name: istio-ingressgateway
    - enabled: true
      label:
        app: istio-eastwestgateway
        istio: eastwestgateway
        topology.istio.io/network: network-staging-eks-1
        vector.dev/scrape: "true"
        test: test ## add test label
      name: istio-eastwestgateway
```
Then gateway become error status:
```yaml
status:
  componentStatus:
    Base:
      status: HEALTHY
    IngressGateways:
      error: 'failed to update resource with server-side apply for obj Deployment/istio-system/istio-eastwestgateway:
        Deployment.apps "istio-eastwestgateway" is invalid: spec.selector: Invalid
        value: v1.LabelSelector{MatchLabels:map[string]string{"app":"istio-eastwestgateway",
        "istio":"eastwestgateway", "test":"test", "topology.istio.io/network":"network-staging-eks-1",
        "vector.dev/scrape":"true"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}:
        field is immutable'
      status: ERROR
    Pilot:
      status: HEALTHY
  status: ERROR
```
It seems we can't modify running deployment pod selector.

However, the eastwest gateway svc's selector is modified. 
```
apiVersion: v1
kind: Service
metadata:
  name: istio-eastwestgateway
  namespace: istio-system
spec:
  selector:
    app: istio-eastwestgateway
    istio: eastwestgateway
    test: test
    topology.istio.io/network: network-staging-eks-1
    vector.dev/scrape: "true"
```
**So the eastwest gateway svc has zero endpoints.**

```
$ k get endpoints -n istio-system istio-eastwestgateway
NAME                    ENDPOINTS   AGE
istio-eastwestgateway   <none>      341d
```

### Version

```Text
$ istioctl version
client version: 1.11.5
control plane version: 1.11-dev
data plane version: 1.11-dev (413 proxies)
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
