### ISSUE TITLE
After upgrade to 1.18.0 Request to probe app failed

### ISSUE THREAD

**Issue by AurimasNav** [istio/istio#45482]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Pods do not become ready after upgrading istio to 1.18.0

2023-06-15T12:15:15.006134Z	error	Request to probe app failed: Get "http://10.255.37.140:9090/health": dial tcp 127.0.0.6:0->10.255.37.140:9090: connect: connection refused, original URL path = /app-health/marketplace/readyzapp URL path = /health

### Version

```Text
istioctl version
client version: 1.17.2
control plane version: 1.18.0
data plane version: 1.17.2 (32 proxies), 1.18.0 (5 proxies)

kubectl version --short
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.26.3
```

### Additional Information

only the workloads running 1.18.0 proxies are failing

helm chart values for istiod:

```yaml
global:
  proxy:
    holdApplicationUntilProxyStarts: true
    resources:
      requests:
        cpu: 1m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 1Gi
# meshConfig:
#   outboundTrafficPolicy:
#     mode: REGISTRY_ONLY
pilot:
  autoscaleEnabled: false
  replicaCount: 2
```

downgrading istio to 1.17.3 resovles the issue

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by howardjohn** [comment]
So `10.255.37.140:9090` should be your pod ip and probe. if you execinto the proxy and do `curl 10.255.37.140:9090` does it work?

We did make a few changes in this area: 
* https://github.com/istio/istio/pull/43021/files#diff-f4a8d4cea1f2df10aac7cba701184f7af5f7a5e78b19c41b0c44b8204093b523R35
* https://github.com/istio/istio/pull/44297

Can you give us a bit more info on your environment? Node OS and version, k8s platform, etc?

Does this happen for this one app or all of them? If just one, can you give us more info about it?

**Comment by AurimasNav** [comment]
> So `10.255.37.140:9090` should be your pod ip and probe. if you execinto the proxy and do `curl 10.255.37.140:9090` does it work?
I will post the result once I am able to test it, for now I have tried to port-forward to the pod 9090 and verify that /health endpoint was working.
> 
> We did make a few changes in this area:
> 
> * https://github.com/istio/istio/pull/43021/files#diff-f4a8d4cea1f2df10aac7cba701184f7af5f7a5e78b19c41b0c44b8204093b523R35
> * [kube-probe: avoid duplicate probe headers #44297](https://github.com/istio/istio/pull/44297)
> 
> Can you give us a bit more info on your environment? Node OS and version, k8s platform, etc?
> 
> Does this happen for this one app or all of them? If just one, can you give us more info about it?
I've tested with couple of pods in different namespaces, both exhibited this behavior.
K8s platform is AKS, I will add the rest of the info later on.

**Comment by howardjohn** [comment]
Thanks. More details on the AKS aspect may help. I talked with someone who has run 1.18 on AKS without issues but could be a certain configuration, etc. Given its happening on different pods it seems likely an environmental issue

**Comment by resnikb** [comment]
I am having a similar issue of probes failing. The application is configured to have the probes on a different port:

```yaml
          ports:
            - name: http2
              containerPort: 8080
              protocol: TCP
            - name: http-diag
              containerPort: 3434
              protocol: TCP
              
          livenessProbe:
            httpGet:
              path: /healthz
              port: http-diag
              scheme: HTTP
```

With Istio 1.17.2, application logs this for health checks:
```
Request finished HTTP/1.1 GET http://10.255.1.27:3434/healthz - - - 200 - text/plain 0.3456ms
```

With Istio 1.18, this is logged (note that the port is not the expected one):
```
Request finished HTTP/1.1 GET http://10.255.1.150:15020/healthz - - - 404 0 - 0.2376ms
```

It's an ASP.NET Core application, with health checks configured as:
```csharp
app.MapHealthChecks("/healthz").RequireHost("*:3434");
```

This check is failing after the upgrade as it looks at the request URL.

**Comment by AurimasNav** [comment]
> So `10.255.37.140:9090` should be your pod ip and probe. if you execinto the proxy and do `curl 10.255.37.140:9090` does it work?

It did work:
> istio-proxy@marketplace-66c6c5bf84-mdqqc:/$ curl http://10.255.37.184:9090/health
{"status":"Healthy","totalDuration":"00:00:00.0008780","entries":{}}

corresponding logs:
![image](https://github.com/istio/istio/assets/7810047/81245248-d381-4d76-8d35-7c1e2a1470af)

> Can you give us a bit more info on your environment? Node OS and version, k8s platform, etc?

AKS 1.26.3, 
Node OS:
>PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/44297 probably changes the host processing. Before we override the port and now we don't?

To verify can you try `curl 10.255.37.140:9090 -H "Host: 10.255.37.140:15020`?

I think for https://github.com/istio/istio/issues/45482#issuecomment-1598143650 case this is almost certainly the cause but would be good to double check these are the same issue

**Comment by AurimasNav** [comment]
> To verify can you try `curl 10.255.37.140:9090 -H "Host: 10.255.37.140:15020`?

```bash
istio-proxy@marketplace-66c6c5bf84-8r8ms:/$ curl http://10.255.37.170:9090/health
{"status":"Healthy","totalDuration":"00:00:00.0000071","entries":{}}
istio-proxy@marketplace-66c6c5bf84-8r8ms:/$ curl -I http://10.255.37.170:9090/health -H "Host: 10.255.37.170:15020"
HTTP/1.1 404 Not Found
date: Wed, 21 Jun 2023 05:19:21 GMT
server: istio-envoy
x-envoy-upstream-service-time: 0
x-envoy-decorator-operation: :0/*
transfer-encoding: chunked
```

**Comment by jaellio** [comment]
> #44297 probably changes the host processing. Before we override the port and now we don't?
> 
> To verify can you try `curl 10.255.37.140:9090 -H "Host: 10.255.37.140:15020`?
> 
> I think for [#45482 (comment)](https://github.com/istio/istio/issues/45482#issuecomment-1598143650) case this is almost certainly the cause but would be good to double check these are the same issue

Would you have expected this command to succeed prior to the changes in https://github.com/istio/istio/pull/44297? Trying to understand the thought process here.

I am trying to make the fix [here]( https://github.com/istio/istio/pull/45632) and I want to make sure I understand what makes the scenario captured in this issue unique and why it wasn't caught in the unit tests.

**Comment by howardjohn** [comment]
I think before the app got 9090 as the Host header port, and now it gets
15020. I could be mistaken though

**Comment by jaellio** [comment]
Gotcha, that makes sense. I think we're currently overriding the host of the new app request with the host of Kubelet's request to the istio-agent status server https://github.com/istio/istio/pull/44297/files#diff-8a331529c387b787b4d84fab3273afb6ce52355c663f4dee58aad15a1e832c18R710. In this case, the host of Kubelet's request would be the <pod ip>: 15020, and the host of the app request would be set to the same. If the host header is set on either request (which it isn't in this issue) I would expect this to override the host. 

I am not sure why the application in the unit test accepts the requests at port 15020.

**Comment by hzxuzhonghu** [comment]
>I think before the app got 9090 as the Host header port, and now it gets 15020. I could be mistaken though

If the app does not care about the `host`, then consued why there is connection refused error met


> 2023-06-15T12:15:15.006134Z error Request to probe app failed: Get "http://10.255.37.140:9090/health": dial tcp 127.0.0.6:0->10.255.37.140:9090: connect: connection refused, original URL path = /app-health/marketplace/readyzapp URL path = /health

**Comment by howardjohn** [comment]
The issue is the app DOES care about the Host

**Comment by howardjohn** [comment]
Not sure why "connection refused" though

**Comment by jaellio** [comment]
I have not been able to reproduce this error on a kind cluster. I have tried testing on a fresh v1.18.0 installation and a v1.17.2 installation that I upgrade to v1.18.0. I modified the `pilot/cmd/pilot-agent/status/server.go` to add more logging and the host value for the request is overwritten to port 15020 and the url remains the same as prior to the changes in https://github.com/istio/istio/pull/44297, but the host value does not take precedence over the host in the URL. Does the app explicitly have to care about the host over the url or is this dependent on the protocol?

Next, I will test in an AKS cluster.

**Comment by howardjohn** [comment]
To reproduce you can run something like this:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - args:
        - --tcp=9090
        - --tcp=9091
        - --server-first=9091
        - --port=80
        - --grpc=7070
        - --port=443
        - --tls=443
        - --crt=/cert.crt
        - --key=/cert.key
        env:
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: gcr.io/istio-testing/app:latest
        imagePullPolicy: IfNotPresent
        name: echo
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
```

It won't actually fail but you can see it log the host header so it should
be close enough.

 I used that to test your PR and it looks correct now
