### ISSUE TITLE
One istio-egressgateway pod is getting all traffic (or almost)

### ISSUE THREAD

**Issue by kurkop** [istio/istio#45486]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

We are using a destination rule to route traffic between an app and redis in different GKE clusters:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: redisgateway-destination-rule
  namespace: istio-egress
spec:
  host: istio-egressgateway.istio-egress.svc.cluster.local
  subsets:
  - name: platform-services-glb-anthos-permanent-redis-db
    trafficPolicy:
      loadBalancer:
        simple: RANDOM
      portLevelSettings:
      - port:
          number: 6379
        tls:
          mode: ISTIO_MUTUAL
          sni: platform-services-glb-anthos-permanent-redis-db.istio-egress.svc.cluster.local
```

While those pods don't have traffic they use low cpu:

```
% k top pods 
NAME                                   CPU(cores)   MEMORY(bytes)   
istio-egressgateway-7df5b4bcf9-9mrsk   7m           58Mi            
istio-egressgateway-7df5b4bcf9-r2676   7m           57Mi
```

After a Jmeter test with 900 users:
```
% k top pods
NAME                                   CPU(cores)   MEMORY(bytes)   
istio-egressgateway-7df5b4bcf9-9mrsk   7m           58Mi            
istio-egressgateway-7df5b4bcf9-r2676   51m          57Mi
```

Also, I have tested with RANDOM, ROUND ROBIN and LEAST_CONN

### Version

```Text
% istioctl version
client version: 1.15.3
control plane version: 1.16.4
data plane version: 1.16.4-asm.2 (20 proxies)
% kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.3
Kustomize Version: v4.5.7
Server Version: v1.25.9-gke.400
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [X] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [X] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
