### ISSUE TITLE
multi-network filters are not applied to non-EDS clusters

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#45506]
By "non-EDS" I more specifically mean DNS clusters. It's possible to mix IPs with hostnames in a DNS cluster. A ServiceEntry with the following endpoints should route the IPs on remote networks to the gateways. 

```yaml
...
  endpoints:
  - address: 1.2.3.4 # stays as is in load assignment
    network: local-net
  - address: foo.bar.com
    network: remote-net # for sidecars, this stays as is. HBONE would let us ask the gateway to resolve? 
  - address: 4.5.6.7 # replaced with gateway IP
    network: remote-net

```
