### ISSUE TITLE
Request Authentication ignored when using Ambient

### ISSUE THREAD

**Issue by myshkin5** [istio/istio#45502]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Note this issue was originally reported as a security vulnerability but I was instructed by @howardjohn to open an issue here:
> Hi,
> 
> Thanks for the report. Since Ambient is alpha I think this can just be opened publicly. Can you include if you have a waypoint proxy deployed in the issue?
> 
> Thanks!

I’m doing some preliminary testing with Ambient using Istio 1.18.0 and believe I’ve found a vulnerability when using a Request Authentication and an Authorization Policy. The behavior is different when compared to using the sidecar model. I’m deploying an HTTP client and server pod, then verifying they can communicate using curl. I then deploy the following Authorization Policy and Request Authentication:
 
```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: http-server
  namespace: http-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: http-server
  action: ALLOW
  rules:
  - from:
    - source:
        requestPrincipals: ["*"]
---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: http-server
  namespace: http-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: http-server
  jwtRules:
  - issuer: [testing@secure.istio.io](mailto:testing@secure.istio.io)
    jwksUri: https://raw.githubusercontent.com/istio/istio/master/security/tools/jwt/samples/jwks.json
```

At this point I would expect any requests that don’t contain a JWT, contain an invalid JWT or JWT from another issuer to be rejected. As a sanity check, I verified that using the same configuration with sidecars produces a 401/403 response.

This behavior was seen after I had a waypoint deployed. Without a waypoint, I saw `Connection reset by peer` as soon as the Authorization Policy was deployed.

### Version

```Text
$ istioctl version
client version: 1.18.0
control plane version: 1.18.0
data plane version: 1.18.0 (8 proxies)
$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.27.1
```

### Affected product area

- [X] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [X] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by keithmattix** [comment]
I think I know what the problem is; we don't add the authn filter for waypoints : https://github.com/istio/istio/blob/master/pilot/pkg/networking/plugin/authn/authentication.go#L106

The JWT filter apparently doesn't block requests if no token is present. According to the [Ambient APIs doc](https://docs.google.com/document/d/1Lk1I1qB-XwVWFP0sVcIN5JMJZHjuF3j8lGWtUeDK6pY/edit#heading=h.xw1gqgyqs5b), the plan seems to be to modify RequestAuthentication to take a parentRef; is that still the case?

/cc @linsun

**Comment by keithmattix** [comment]
RequestAuthentication is L7 policy though; it wouldn't apply to the ztunnel regardless...If an RA exists in an Ambient context, we know that the waypoint should process it right?

**Comment by howardjohn** [comment]
but the authorization policy part should right? that's what was denying
before the waypoint was added

**Comment by howardjohn** [comment]
The waypoint doesn't process it since it isn't selecting the waypoint
(which will be parent ref in the future but we have a short term hack to
label select the waypoint)

**Comment by keithmattix** [comment]
> but the authorization policy part should right? that's what was denying before the waypoint was added

I'm not sure that's the case; there's only a single rule that has L7 policy attached to it (requestPrincipals). When we send AuthorizationPolicy to ztunnel we ignore any rule with an L7 policy such as requestPrincipals. So the AP in the description would, from my understanding, translate to an "allow all" Authorization in ztunnel. I'm actually not sure what's doing blocking in the non-waypoint case

**Comment by howardjohn** [comment]
I don't think we ignore, we send them as always matching (deny) or never
matching (allow)

**Comment by keithmattix** [comment]
I'm not saying we ignore the entire policy; I'm saying we ignore the rule itself (at least that's my understanding based on the code I linked above). Since there's only one rule in the described AuthorizationPolicy, istiod would send an Authorization to ztunnel that has no rules which I _think_ effectively means match anything

**Comment by keithmattix** [comment]
Spoke with @howardjohn offline; he's right: the AuthorizationPolicy was blocking the traffic. @myshkin5, can you try adding the following label selector to your AuthorizationPolicy: `istio.io/gateway-name: bookinfo-productpage` (from this [doc](https://istio.io/latest/docs/ops/ambient/getting-started/#l7-authorization-policy)). I think that should make the AuthorizationPolicy apply at the waypoint

**Comment by myshkin5** [comment]
@keithmattix I changed the match label from `app.kubernetes.io/name: http-server` to `istio.io/gateway-name: http-server` (`http-server` is the app label and the service account name). With a waypoint deployed, I saw 403s as expected (without a waypoint, traffic was not blocked). I think this means that a user would need to update their auth policy when they switched a workload from sidecar injected to Ambient to use the right match label (no way to do an "or" on workload selectors AFAICT).

Thanks for the clarification!

**Comment by keithmattix** [comment]
@myshkin5 i thought you said

> Without a waypoint, I saw Connection reset by peer as soon as the Authorization Policy was deployed.

**Comment by myshkin5** [comment]
@keithmattix You are right, I did say that. Looking back at my notes, I think (not 100% sure) I was using a deny everything auth policy. Just tried recreating that original scenario and this was the only auth policy that causes a connection reset as described above:
```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: http-server
  namespace: http-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: http-server
  action: DENY
  rules:
  - from:
    - source:
        requestPrincipals: ["*"]
  - to:
    - operation:
        ports: ["8000"]
```

Sorry for the confusion

**Comment by keithmattix** [comment]
Thanks for clearing this up! Closing the issue

**Comment by danielloader** [comment]
@myshkin5 Sorry to chase this up but I can't seemingly get RequestAuthentication checks to work in ambient for me, no matter what I do they give me a 200 response - no header, invalid jwt, valid jwt. All pass through to the pod and responses are completed.

I appreciate it's been a year, but if anyone has a full reproducible example I can deploy to a namespace to inspect the configuration and adapt it, I'd appreciate!

**Comment by myshkin5** [comment]
@danielloader Sorry I don't have anything to add here. I was working on a PoC using Ambient and haven't used it since. Guessing from John Howard's responses above, there were major UX changes on the horizon and I have no idea if they got implemented in the meantime. Good luck!

**Comment by nvcnvn** [comment]
Hi, so now (v1.25.2), basically if I want to use use JWT authentication, the AuthorizationPolicy and RequestAuthentication need to select the waypoint's label?
And that should be something like:
```
      gateway.networking.k8s.io/gateway-name: waypoint
```

**Comment by nvcnvn** [comment]
I do this with `targetRefs` and still don't think it work
```
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: "zitadel-jwt-req-auth"
spec:
  targetRefs:
  - name: waypoint
    kind: Service
  - name: transformar-service
    kind: Service
  jwtRules:
  - issuer: "http://zitadel.example.com"
    jwksUri: "http://zitadel.example.com/oauth/v2/keys"
    fromHeaders:
    - name: "Authorization"
      prefix: "Bearer "
    outputClaimToHeaders:
    - header: X-User-Roles
      claim: "urn:zitadel:iam:org:project:roles"
    - header: X-User-Id
      claim: "sub"
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: require-jwt
spec:
  targetRefs:
  - name: waypoint
    kind: Service
  - name: transformar-service
    kind: Service
  action: ALLOW
  rules:
  - from:
    - source:
       namespaces: ["istio-system"]
    to:
    - operation:
        methods: ["GET"]
        paths: ["/"]
    - operation:
```
