### ISSUE TITLE
Istiod does not get ready if ISTIO_WATCH_NAMESPACE env is set

### ISSUE THREAD

**Issue by LithiumSR** [istio/istio#45512]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hello everyone,
I was testing the new ISTIO_WATCH_NAMESPACE feature that was recently added (#43935) and I noticed that if I deploy Istio in istio-system with that env set to "istio-system" then the controller never goes ready.
My objective was to have an istio deployment whose informers only watch in "istio-system".
The issue also shows up if the "watch namespace" is different than the one the controller is deployed to.

I tested it using a build **based on current master** with the following IstioOperator:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
   components:
      pilot:
         k8s:
            env:
               - name: ISTIO_WATCH_NAMESPACE
                 value: "istio-system"
```

From what I see in the logs it seems that the webhook patching is not performed
```
2023-06-16T11:57:36.936717Z     info    validationController    Not ready to switch validation to fail-closed: dummy invalid config not rejected
2023-06-16T11:57:36.936780Z     info    validationController    validatingwebhookconfiguration istio-validator-istio-system (failurePolicy=Ignore, resourceVersion=3547346) is up-to-date. No change required.
2023-06-16T11:57:36.936802Z     error   controllers     error handling /istio-validator-istio-system, retrying (retry count: 12): webhook is not ready, retry   controller=validation
2023-06-16T11:57:37.717319Z     warn    discovery is not ready
```
If I remove the flag, then the deployment works as intended.

### Version

```Text
1.19-alpha.8f7d578ce031dba8394104a90e5cfe31a9c417d8
data plane version: none

kubectl version --short
Client Version: v1.21.7
Server Version: v1.24.7
```

### Additional Information

[bug-report.tar.gz](https://github.com/istio/istio/files/11769941/bug-report.tar.gz)

### Affected product area

- [ ] Ambient
- [ ] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
