### ISSUE TITLE
Ordering of WasmPlugin and AuthorizationPolicy

### ISSUE THREAD

**Issue by amar1104** [istio/istio#45511]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi folks,
I have an AuthorizationPolicy with custom action which connects to external authz. I’m trying to add a WasmPlugin before AuthorizationPolicy but seems like it is always coming next to external AuthorizationPolicy. I have tried with AUTHN and AUTHZ phase in WasmPlugin and with high priority but still no luck.

SampleCode
```
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: auth-wasm
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  url: http://host.minikube.internal:9000/main.wasm
  phase: AUTHN
  priority: 100
```
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: auth-policy
  namespace: default #Change
spec:
  selector:
    matchLabels:
      app: nginx  #Change
  action: CUSTOM
  provider:
    name: test-ext-authz-http
  rules: 
    - {}
```
Expecting WasmPlugin to come after AuthPolicy but not working.

### Version

```Text
istioctl version: 1.17.2
kubectl version: 1.27.2
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by hzxuzhonghu** [comment]
Can you share your listener configuration, from https://github.com/istio/istio/blob/8652668835700c4e278dac4437a9e736602bc559/pilot/pkg/networking/core/v1alpha3/listener_builder.go#L363-L383, we do order them as documented

**Comment by amar1104** [comment]
@hzxuzhonghu sharing the listeners config here 
[envoy-config.txt](https://github.com/istio/istio/files/11788466/envoy-config.txt)

In the above code snippet I see this
`// TODO: how to deal with ext-authz? It will be in the ordering twice`
`filters = append(filters, lb.authzCustomBuilder.BuildHTTP(httpOpts.class)...) `
`filters = extension.PopAppend(filters, wasm, extensions.PluginPhase_AUTHN) `
Does it mean that ext-authz(custom AuthzPolicy) is added before PluginPhase_AUTHN?

**Comment by hzxuzhonghu** [comment]
IC, you are using custom authz, it is inserted in front of all others.

@howardjohn Do you remember why you put it like this in #38595

**Comment by howardjohn** [comment]
I think that PR was just retaining the existing ordering which was probably accidental

**Comment by hzxuzhonghu** [comment]
@yangminzhu Tracked custom authz filter was put in front by you, do you remember the ctx?

**Comment by amar1104** [comment]
Hi @yangminzhu, any update on this?

**Comment by howardjohn** [comment]
Yangmin is no longer working on the project so I wouldn't expect a response

**Comment by hzxuzhonghu** [comment]
Just not sure if there was some more considerations

**Comment by boeboe** [comment]
How about we define a new PluginPhase_AUTHZ_CUSTOM (as this is reflecting current reality) and modify protobuf accordingly, so customers can also inject custom WASM plugins before this new stage (which is now not possible).


https://github.com/istio/istio/blob/7c506844cf3f58b504c97a1a2e5a41ca0a37d25d/pilot/pkg/networking/core/v1alpha3/listener_builder.go#L396

```golang
		// TODO: how to deal with ext-authz? It will be in the ordering twice
		filters = extension.PopAppendHTTP(filters, wasm, extensions.PluginPhase_AUTHZ_CUSTOM)
		filters = append(filters, lb.authzCustomBuilder.BuildHTTP(httpOpts.class)...)
		filters = extension.PopAppendHTTP(filters, wasm, extensions.PluginPhase_AUTHN)
		filters = append(filters, lb.authnBuilder.BuildHTTP(httpOpts.class)...)
		filters = extension.PopAppendHTTP(filters, wasm, extensions.PluginPhase_AUTHZ)
		filters = append(filters, lb.authzBuilder.BuildHTTP(httpOpts.class)...)
		// TODO: these feel like the wrong place to insert, but this retains backwards compatibility with the original implementation
		filters = extension.PopAppendHTTP(filters, wasm, extensions.PluginPhase_STATS)
		filters = extension.PopAppendHTTP(filters, wasm, extensions.PluginPhase_UNSPECIFIED_PHASE)
```

https://github.com/istio/api/blob/master/extensions/v1alpha1/wasm.pb.go#L291

```
// The phase in the filter chain where the plugin will be injected.
type PluginPhase int32

const (
	// Control plane decides where to insert the plugin. This will generally
	// be at the end of the filter chain, right before the Router.
	// Do not specify `PluginPhase` if the plugin is independent of others.
	PluginPhase_UNSPECIFIED_PHASE PluginPhase = 0
	// Insert plugin before Istio authentication filters.
	PluginPhase_AUTHZ_CUSTOM PluginPhase = 1
	// Insert plugin before Istio authentication filters.
	PluginPhase_AUTHN PluginPhase = 2
	// Insert plugin before Istio authorization filters and after Istio authentication filters.
	PluginPhase_AUTHZ PluginPhase = 3
	// Insert plugin before Istio stats filters and after Istio authorization filters.
	PluginPhase_STATS PluginPhase = 4
)

// Enum value maps for PluginPhase.
var (
	PluginPhase_name = map[int32]string{
		0: "UNSPECIFIED_PHASE",
		1: "AUTHZ_CUSTOM",
		2: "AUTHN",
		3: "AUTHZ",
		4: "STATS",
	}
	PluginPhase_value = map[string]int32{
		"UNSPECIFIED_PHASE": 0,
		"AUTHZ_CUSTOM":      1,
		"AUTHN":             2,
		"AUTHZ":             3,
		"STATS":             4,
	}
)

```

This would require a change in the protobuf API definition, so I do not know what other impact his has. 

Original sample code of this issue adjusted:

```yaml
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: auth-wasm
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  url: http://host.minikube.internal:9000/main.wasm
  phase: AUTHZ_CUSTOM
  priority: 100
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: auth-policy
  namespace: default #Change
spec:
  selector:
    matchLabels:
      app: nginx  #Change
  action: CUSTOM
  provider:
    name: test-ext-authz-http
  rules: 
    - {}
```
