### ISSUE TITLE
Unavailable to sync multi-cluster using east/west gateway over NodePort

### ISSUE THREAD

**Issue by betonetotbo** [istio/istio#45516]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I have 3 clusters (`cluster-main`, `cluster-1`, `cluster-2`) on different networks. I installed istio multi-cluster in different networks mode.

In 2 of that clusters I'm using the default Service definition of Istio eastwest-gateway, letting it create a Service of type LoadBalancer.

But in one of them clusters, I needed to change the default Service type to NodePort. After that, I configure my nginx to proxy all requests to the ports 15012, 15017, 15021 and 15443 to a main node private IP of the `cluster-1`. This was necessary because I'm not have the possibility to use a Service of type LoadBalancer in that cluster.

Here is the manifest of the eastwest gateway of `cluster-1`:

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: eastwest
spec:
  revision: ""
  profile: empty
  components:
    ingressGateways:
      - name: istio-eastwestgateway
        label:
          istio: eastwestgateway
          app: istio-eastwestgateway
          topology.istio.io/network: cluster-1-network
        enabled: true
        k8s:
          env:
            # traffic through this gateway should be routed inside the network
            - name: ISTIO_META_REQUESTED_NETWORK_VIEW
              value: cluster-1-network
          service:
            type: NodePort
            ports:
              - name: status-port
                port: 15021
                targetPort: 15021
                nodePort: 30200
              - name: tls
                port: 15443
                targetPort: 15443
                nodePort: 30201
              - name: tls-istiod
                port: 15012
                targetPort: 15012
                nodePort: 30202
              - name: tls-webhook
                port: 15017
                targetPort: 15017
                nodePort: 30203
  values:
    gateways:
      istio-ingressgateway:
        injectionTemplate: gateway
    global:
      network: cluster-1-network
```

This is working, I was able to connect to it (via nginx proxy ports) and validate the connection successful.

But problem I'm facing is about the multi-cluster syncronization.

I added this `meshNetworks` definition to my istio installation manifest of `cluster-2`:

```yaml
      meshNetworks:
        cluster-1-network:
          endpoints:
          - fromRegistry: cluster-1
          gateways:
          - registryServiceName: istio-eastwestgateway.istio-system.svc.cluster.local
            port: 15443
            address: 172.40.0.201
```

This `cluster-1-network` is that cluster previously quoted, that is behind the nginx proxying.

When I try to request to a service running in that `cluster-1` from `cluster-2` I'm getting this:

```
[HTTP 503]
upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: TLS error: 33554536:system library:OPENSSL_internal:Connection reset by peer
```
The request to services that are running on `cluster-main` are working as expected.

So, when I retrive some information via istioctl, I'm getting this:

```yaml
$ istioctl x internal-debug networkz
[
  {
    "Network": "cluster-1-network",
    "Cluster": "",  // <<< I'm suspecting this is the problem
    "Addr": "172.40.0.201",
    "Port": 15443
  },
  {
    "Network": "cluster-main-network",
    "Cluster": "cluster-main",
    "Addr": "x.x.x.x",
    "Port": 15443
  }
]
# I have a nginx-2 deployment running on cluster-2, and also a nginx-1 in cluster-1
# Here i'm query the endpoint of nginx-1 in cluster-1 from cluster-2
# Note that the IP of nginx-1 is correct!
$ istioctl pc ep nginx-2-7b799fbf97-h7hg2.default | grep nginx
10.244.0.151:80                                         HEALTHY     OK                outbound|80||nginx-2.default.svc.cluster.local
172.40.0.201:15443                                      HEALTHY     OK                outbound|80||nginx-1.default.svc.cluster.local

```

Note that the `Cluster` field in the network infos of the `cluster-1` is empty. I'm suspecting what that is the root of my problem.

Is something that I can do to solve it? Or this is realy a BUG?

Another question here is, why this IP/DNS of the `cluster-1` eastwest gateway is not defined inside the `cluster-1` configuration? Why istio cannot synchronize/discovery this DNS querying it to the remote cluster `cluster-1` (e.g.: inside the `cluster-1` IstioOperator CRD) instead of setting this on each cluster that need to sync with that one (this question is based on the behavior of istio when the service is of type LoadBalancer, it resolves itself)?

### Version

```Text
$ istioctl version
client version: 1.14.5
control plane version: 1.14.5
data plane version: 1.14.5 (2 proxies)
$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.13
Kustomize Version: v4.5.4
Server Version: v1.24.14
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [X] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
