### ISSUE TITLE
Failed to pull image "gcr.io/istio-release/pilot:1.17.0"

### ISSUE THREAD

**Issue by rondy-cg** [istio/istio#45536]
# Background
I was trying to install istio 1.17.0 via helmCharts below via ArgoCD but got error which says "Failed to pull image", details below.

```
helmCharts:
- name: istiod
  repo: https://istio-release.storage.googleapis.com/charts
  version: v1.17.0
  releaseName: istiod
  namespace: istio-system
  valuesFile: values.yaml
```

```
Failed to pull image "gcr.io/istio-release/pilot:1.17.0": rpc error: code = Unknown desc = Error response from daemon: manifest for gcr.io/istio-release/pilot:1.17.0 not found: manifest unknown: Failed to fetch "1.17.0" from request "/v2/istio-release/pilot/manifests/1.17.0".
```

# Initial Checks
As per https://console.cloud.google.com/gcr/images/istio-release, looks like the pilot image of 1.17.1〜1.17.3 were there but couldn't find 1.17.0, any special reason or I was referencing the wrong place?
![image](https://github.com/istio/istio/assets/102935179/794c9fea-4830-4f56-8234-9213a8a1d20c)

On the other hand, when I checked istiod 1.17.0 separately, I found the tag as below, do I have to specify the image tag explicitly via  kustomize patch or something else?

https://console.cloud.google.com/gcr/images/istio-release/global/charts/istiod
![image](https://github.com/istio/istio/assets/102935179/9bafe3e8-29ba-4385-840f-15e127f47e94)
