### ISSUE TITLE
Wrong service in 'destination_service' label of the sidecar metrics

### ISSUE THREAD

**Issue by SrDayne** [istio/istio#45555]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hello.

I played with Argo Rollouts, especially with Analysis and Canary deployments and noticed that  destination_service metrics is wrong. It keep old name all the time, no matter what you do: set weight to 0, comment piece of code related to this service, change destination port. Only removing of the previous service helps.

Could be related issues:
https://github.com/istio/istio/issues/44189
https://github.com/istio/istio/issues/45117
https://github.com/istio/istio/issues/45401

### Version

```Text
$ istioctl version
client version: 1.17.1
control plane version: 1.17.1
data plane version: 1.17.1 (9 proxies)

$ kubectl version --short
Client Version: v1.23.6
Server Version: v1.25.9-eks-0a21954
WARNING: version difference between client (1.23) and server (1.25) exceeds the supported minor version skew of +/-1
```

### Additional Information

Steps to reproduce:
1. Deploy services, gateway, virtual service and deployment.

**Deployment**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollouts-demo
  labels:
    istio-injection: enabled
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: deployment-rollouts-demo
  template:
    metadata:
      labels:
        app: deployment-rollouts-demo
        istio-injection: enabled
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: istio-metrics
          containerPort: 15020
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
```
**Services**
```
apiVersion: v1
kind: Service
metadata:
  name: deployment-rollouts-demo-canary
  labels:
    release: prometheus
    service-app: app-fluentd-metrics
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  - port: 15020
    targetPort: istio-metrics
    protocol: TCP
    name: istio-metrics
  selector:
    app: deployment-rollouts-demo

---
apiVersion: v1
kind: Service
metadata:
  name: deployment-rollouts-demo-stable
  labels:
    release: prometheus
    service-app: app-fluentd-metrics
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  - port: 15020
    targetPort: istio-metrics
    protocol: TCP
    name: istio-metrics
  selector:
    app: deployment-rollouts-demo
```
**Virtual Service**
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rollouts-deployment
spec:
  gateways:
  - istio-system/gateway
  hosts:
  - reviews.example.com
  http:
  - name: primary
    route:
    - destination:
        host: deployment-rollouts-demo-stable
        port:
          number: 80
      weight: 100
  tls:
  - match:
    - port: 3000
      sniHosts:
      - reviews.example.com
    route:
    - destination:
        host: deployment-rollouts-demo-stable
      weight: 100
```
3. Get metrics from sidecar on port `15020`, path `/stats/prometheus`
4. Value of the  `destination_service` is `deployment-rollouts-demo-stable`

```
istio_requests_total{
cluster="cluster-dev",
connection_security_policy="mutual_tls",
container="rollouts-demo",
destination_app="deployment-rollouts-demo",
destination_canonical_revision="latest",
destination_canonical_service="deployment-rollouts-demo",
destination_cluster="Kubernetes",
destination_principal="spiffe://cluster.local/ns/demo/sa/default",
destination_service="deployment-rollouts-demo-stage.demo.svc.cluster.local",
destination_service_name="deployment-rollouts-demo-stable",
destination_service_namespace="demo",
destination_workload="rollouts-demo",
destination_workload_namespace="demo",
endpoint="istio-metrics",
instance="10.1.12.187:15020",
job="deployment-rollouts-demo-stable",
namespace="demo",
pod="rollouts-demo-6b5f955b78-kw9lj",
prometheus="monitoring/prometheus-kube-prometheus-prometheus",
prometheus_replica="prometheus-prometheus-kube-prometheus-prometheus-0",
reporter="destination",
request_protocol="http",
response_code="200",
response_flags="-",
service="deployment-rollouts-demo-stable",
source_app="istio-ingressgateway",
source_canonical_revision="latest",
source_canonical_service="istio-ingressgateway",
source_cluster="Kubernetes",
source_principal="spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account",
source_version="unknown",
source_workload="istio-ingressgateway",
source_workload_namespace="istio-system"}
```

5. Disable this service in VirtualService and connect `deployment-rollouts-demo-canary`. Check metrics, `destination_service` stay same as previous service.
6. Remove service `deployment-rollouts-demo-stable` form cluster. Check metrics again, now it changed to new service name.

I checked routing, I disabled ports on old service, traffic is going on new service, however metric labels contain old service names.

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
