### ISSUE TITLE
Istio sidecar has dozens of wasm vms

### ISSUE THREAD

**Issue by Xemuel** [istio/istio#45573]
I implemented two wasm http filters for worker thread and deploy them by Istio EnvoyFilter as following

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: foo-filter
  namespace: istio-system
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
        context: SIDECAR_INBOUND
      patch:
        operation: INSERT_BEFORE
        value:
          config_discovery:
            apply_default_config_without_warming: true
            config_source:
              api_config_source:
                api_type: GRPC
                grpc_services:
                  - envoy_grpc:
                      cluster_name: ecds_cluster
                transport_api_version: V3
            default_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
              config:
                configuration:
                  "@type": type.googleapis.com/google.protobuf.StringValue
                  value: '{"enabled":true}'
                fail_open: true
                name: foo
                root_id: foo
                vm_config:
                  code:
                    local:
                      filename: /var/local/wasm/prod/foo.wasm
                  runtime: envoy.wasm.runtime.v8
                  vm_id: "001"
            type_urls:
              - type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          name: test.foo
```

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: bar-envoy-filter
  namespace: istio-system
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
        context: SIDECAR_OUTBOUND
      patch:
        operation: INSERT_BEFORE
        value:
          config_discovery:
            apply_default_config_without_warming: true
            config_source:
              api_config_source:
                api_type: GRPC
                grpc_services:
                  - envoy_grpc:
                      cluster_name: ecds_cluster
                transport_api_version: V3
            default_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
              config:
                configuration:
                  "@type": type.googleapis.com/google.protobuf.StringValue
                  value: '{"enabled":false}'
                fail_open: true
                name: rfcp
                root_id: rfcp
                vm_config:
                  code:
                    local:
                      filename: /var/local/wasm/prod/bar.wasm
                  runtime: envoy.wasm.runtime.v8
                  vm_id: "001"
            type_urls:
              - type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          name: test.bar
```

The sidecar has concurrency set to 2.

In Prometheus, I saw there are 28 active v8 wasm vms active for a pod:
![](https://blog-static.fintopia.tech/84d4809d9efb0d51d46a028d36ddd852.png)

For my understanding, stats filters are null rumtime so they are not counted in the 28 active v8 vms.
Why there are that much vms? It doesn't seem to have that much for a local naked envoy with two filters loaded, even count for the base vm and the created thread local vm in the non-worker thread.
