### ISSUE TITLE
AuthorizationPolicy exclude hosts/services from oauth redirection (open them to world)

### ISSUE THREAD

**Issue by holotrack** [istio/istio#45581]
I have such  AuthorizationPolicy config:

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: known-user
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: sandbox-istio
  action: ALLOW
  rules:
    - when: # Lack of Authorization header will push user to oauth2 filter
        - key: request.headers[Authorization]
          notValues:
            - "Bearer*"
    - to:
        - operation:
            hosts:
               - "www.example.com"
```

But it doesn't work like I'm expecting. I need to make authorization only on few services/domains, not on all. How to exclude them from OAuth redirection?

EDIT:

Im using native oauth2 EnvoyFilter
