### ISSUE TITLE
Envoy proxy is remained NOT ready status.

### ISSUE THREAD

**Issue by KoJJang** [istio/istio#45616]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

When I upgraded istio v1.13.2 to v1.17.2, some pods(actually only one gateway pod) are remaining readiness probe failed status. 

I've set `revision` for the mesh, and set `discoverySelector` field for v1.17.2.

The below logs have been generated for NOT ready status istio-proxy container. 
```shell
...
...
2023-06-23T07:51:38.098164Z     info    ads     XDS: Incremental Pushing:0 ConnectedEndpoints:0 Version:
2023-06-23T07:51:38.098229Z     info    cache   returned workload trust anchor from cache       ttl=23h59m59.901773755s
2023-06-23T07:51:57.299224Z     error   failed scraping envoy metrics: error scraping http://localhost:15090/stats/prometheus: Get "http://localhost:15090/stats/prometheus": dial tcp [::1]:15090: connect: connection refused
...
2023-06-23T07:52:49.615390Z     error   failed scraping envoy metrics: error scraping http://localhost:15090/stats/prometheus: Get "http://localhost:15090/stats/prometheus": context deadline exceeded
...
```

And successfully deployed pod(except above one pod) have logs like below
```shell
...
2023-06-23T06:26:00.114785Z     info    ads     XDS: Incremental Pushing:0 ConnectedEndpoints:0 Version:
2023-06-23T06:26:00.114827Z     info    cache   returned workload trust anchor from cache       ttl=23h59m59.885174746s
2023-06-23T06:26:02.097777Z     info    Readiness succeeded in 2.466196107s
2023-06-23T06:26:02.098197Z     info    Envoy proxy is ready
```

Furthermore, if I send a request to `http://localhost:15090/stats/prometheus` from each pod, I will get a different response as shown below.

- ready status pod
```shell
$ curl http://localhost:15090/stats/prometheus -I
HTTP/1.1 200 OK
content-type: text/plain; charset=UTF-8
cache-control: no-cache, max-age=0
x-content-type-options: nosniff
date: Fri, 23 Jun 2023 08:52:06 GMT
server: envoy
x-envoy-upstream-service-time: 3
transfer-encoding: chunked
```
- NOT ready status pod
```shell
$ curl http://localhost:15090/stats/prometheus -I
HTTP/1.1 504 Gateway Timeout
content-length: 24
content-type: text/plain
date: Fri, 23 Jun 2023 08:51:56 GMT
server: envoy
```

Since they are istio-ingressgateways operating in different namespaces, there are a few different names, but almost all of the settings are the same. The response time from the **NOT ready status pod** is also quite long (almost 5 seconds), what should I check?

### Version

```Text
$ istioctl version -i {revision}
client version: 1.17.2
control plane version: 1.17.2
data plane version: 1.17.2 (237 proxies)
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by GregHanson** [comment]
@KoJJang can you check the logs in the not ready istio-proxy pod for the first error in the logs?  I'm guessing the prometheus query is not succeeding because it has no config, and the actual error is hidden at the start of the failing prometheus query logs. Anything `STALE` for gateway in question?
```
istioctl proxy-status
```

**Comment by KoJJang** [comment]
@GregHanson 
The **NOT READY status pod** doesn't listed for `prorxy-status`. All other ready status pods are listed with **SYNCED status**. 
```shell
### There is no result of NOT ready status pod
$ istioctl ps -i {revision}
NAME                                                                                          CLUSTER        CDS        LDS        EDS          RDS          ISTIOD                      VERSION
...
istio-ingressgateway-mygateway-6d74bf449b-xwcvg.namespace1                             Kubernetes     SYNCED     SYNCED     NOT SENT     SYNCED       istiod-elb-5bcbd88d7b-whfn5     1.17.2
```

**Comment by hzxuzhonghu** [comment]
You can check why the pod is not ready, basically why the gateway is not ready yet

**Comment by KoJJang** [comment]
@hzxuzhonghu 
What should I check? Below are what I checked.
- describe pod resulted `readiness probe failed events`.
- configMap(`istio-ca-root-cert`) is same with other Namespaces.
- There is no `error` logs before `failed scraping envoy metrics: error scraping http://localhost:15090/stats/prometheus` error occurred. 
- Even after I restarted NOT ready pod, same problem keep occurring only same deployment(in the specific Namespace).
- After I rollbacked to istio v1.13.2, all pods are running well after restarting gateway pods.

Could you suggest anything else to check?

**Comment by hzxuzhonghu** [comment]
what `discoverySelector ` do you set, does it select the namespace where the gateway deployed

**Comment by hzxuzhonghu** [comment]
And you can check whether there is some indication from istiod log

**Comment by hzxuzhonghu** [comment]
can you enable debug in istiod, i donot see related RDS and EDS push logs

**Comment by KoJJang** [comment]
@hzxuzhonghu 

I found the reason of NOT ready status pod.
There is an envoyfilter to use [coraza](https://github.com/corazawaf/coraza-proxy-wasm/tree/main/wasmplugin) wasm for WAF, and we are manually generated istio-proxyv2 v1.13.2 with coraza wasm file. 
However, in the proxy image I used for v1.17.2, the pod did not run properly because there is no wasm file in the specified path.

After delete that envoyfilter, gateway pod is running well. Sorry for making it seem like there's a version issue due to personalization. I'll close this issue


<details>

<summary> applied envoyfilter </summary>

```yaml
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.wasm
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          config:
            configuration:
              '@type': type.googleapis.com/google.protobuf.StringValue
              value: |
                {
                  "rules": [
                    "SecDebugLogLevel 9",
                    "SecRuleEngine On",
                    "SecRule REQUEST_URI \"@streq /admin\" \"id:101,phase:1,t:lowercase,deny\""
                  ]
                }
            name: coraza-filter
            root_id: ""
            vm_config:
              code:
                local:
                  filename: build/main.wasm ### this path
              runtime: envoy.wasm.runtime.v8
              vm_id: coraza-filter_vm_id
```

</details>
