### ISSUE TITLE
`holdApplicationUntilProxyStarts` and `restartPolicy: OnFailure` results in permanent breakage if the wait fails

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#45627]
With this combination, if the hook fails (timeout after 30s), Kubelet will send a SIGTERM to the agent. The agent will then exit with an exit code of 0. Due to  `restartPolicy: OnFailure`, it will not be retried since it has exit code 0. 

I suppose the same applies to `restartPolicy: Never`, but there is no fix there even if we hack around the exit code.

In particular, jobs *cannot* use `restartPolicy: Always`, which is really the only safe option.

`holdApplicationUntilProxyStarts` make things worse, since it provides an obvious avenue for the proxy to exit: simply taking >60s.

Aside from that, proxy doesn't crash often, really only if it cannot startup which is likely only from port conflicts or misconfigs, not likely ephemeral things that can happen intermittently.

I am not sure a good fix for this. Not using `holdApplicationUntilProxyStarts` is of course an option... The sidecar KEP likely helps quite a bit here, eventually.

simplified non-istio config you can use to test:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: shell2
  labels:
    app: shell
    sidecar.istio.io/inject: "false"
spec:
  restartPolicy: OnFailure
  containers:
  - name: istio-proxy
    lifecycle:
      postStart:
        exec:
          command:
          - sh
          - -c
          - |
            echo "starting hook ..."
            sleep 1
            echo "exiting hook ..."
            exit 1
    image: howardjohn/shell
    imagePullPolicy: IfNotPresent
    args:
      - sh
      - -c
      - |
        function term() {
          echo "got term..."
          sleep 5
          exit 1
        }

        trap "echo I was SIGINT terminated; exit" SIGINT
        trap "echo I was SIGQUIT terminated; exit" SIGQUIT
        trap "echo I was SIGTERM terminated; exit" SIGTERM
        echo "starting..."
        counter=0

        while true
        do 
          echo "Loop number:" $((++counter))
          sleep 1
        done
  - name: shell
    image: howardjohn/shell
    imagePullPolicy: IfNotPresent
    args:
      - /bin/sleep
      - infinity
```
