### ISSUE TITLE
DestinationRule traffic policy disables retryRemoteLocalities

### ISSUE THREAD

**Issue by davegustafson** [istio/istio#45668]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I believe this is a bug. It's possible I just don't fully understand how these two features are related or conflict with one another, but the behavior I'm seeing is not what I would expect.

I have a service deployed across two clusters in a multi-primary configuration. For the purpose of this test, each cluster consists of a single node. The service consists of 5 replicas in each cluster.

I have a VirtualService that routes ingress traffic from a gateway to the service. The VirtualService is configured to retry on 5xx status, up to 3 times, and to retry remote localities.

The destination service in this case returns a 503 error by design. When I make a test request, I see the first request reach the service in the target cluster, then I see 3 new requests against the service in the alternate cluster, exactly like I would expect.

However, when I add a DestinationRule with a traffic policy to control the distribution of traffic across the clusters, this seems to override the retryRemoteLocalities setting and essentially disables it.

This is a problem for us because we want to control active/pilot load-balancing under normal operating conditions, but we want to fail-over to the other cluster immediately if any replica of the destination service returns a 5xx error code.

I would expect that retryRemoteLocalities would continue to operate as expected even with a DestinationRule traffic policy in place, but this doesn't seem to be the case.

Below are the VirtualService and DestinationRule from my tests:

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: demo
  namespace: local-istio-system
spec:
  gateways:
  - ingressgateway-internal
  hosts:
  - istio-ingressgateway-internal.local-istio-system
  http:
  - match:
    - uri:
        prefix: "/playground/"
    - uri:
        prefix: "/playground"
    rewrite:
      uri: /
    route:
    - destination:
        host: demo.local-playground.svc.cluster.local
    retries:
      attempts: 3
      retryOn: 5xx
      retryRemoteLocalities: true
```

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: demo
spec:
  host: "demo.local-playground.svc.cluster.local"
  trafficPolicy:
    loadBalancer:
      simple: LEAST_REQUEST
      localityLbSetting:
        enabled: true
        distribute:
        - from: us-east-1/*
          to:
            "us-east-1/*": 99
            "us-east-2/*": 1
        - from: us-east-2/*
          to:
            "us-east-2/*": 99
            "us-east-1/*": 1
```

Thank you for taking a look at this, and I'm happy to share any other information that might be relevant.

### Version

```Text
$ istioctl --istioNamespace local-istio-system version
client version: 1.14.3
control plane version: 1.18.0
data plane version: 1.18.0 (12 proxies)

$ kubectl version --short
Client Version: v1.21.12
Server Version: v1.23.17

$ helm version --short
v3.10.3+g835b733
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [X] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
