### ISSUE TITLE
stats collisions after upgrade to 1.18

### ISSUE THREAD

**Issue by pintonunes** [istio/istio#45673]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Before 1.18 when istio metrics were generated by the wasm filter, metric tags were separated by `;.;` and values by `=.=`
This would make a metric look like:

`wasmcustom.reporter=.=source;.;source_workload=.=istio-ingressgateway;.;source_workload_namespace=.=tenant-1;.;source_principal=.=spiffe://cluster.local/ns/tenant-1/sa/default;.;source_app=.=unknown;.;source_version=.=unknown;.;source_canonical_service=.=istio-ingressgateway;.;source_canonical_revision=.=latest;.;source_cluster=.=Kubernetes;.;destination_workload=.=app-1;.;destination_workload_namespace=.=tenant-1;.;destination_principal=.=spiffe://cluster.local/ns/tenant-1/sa/default;.;destination_app=.=app-1;.;destination_version=.=unknown;.;destination_service=.=app-1.tenant-1.svc.cluster.local;.;destination_service_name=.=app-1;.;destination_service_namespace=.=tenant-1;.;destination_canonical_service=.=app-1;.;destination_canonical_revision=.=latest;.;destination_cluster=.=Kubernetes;.;request_protocol=.=http;.;response_flags=.=-;.;connection_security_policy=.=unknown;.;response_code=.=200;.;grpc_response_status=.=;.;istio_response_bytes`

Also the tag separator could be configured in the wasm filter.
So we could easily parse and extract tag names and values. 

With the move to 1.18 metrics are now generated by an envoy filter and tags are separated by dots. 

`istiocustom.istio_requests_total.reporter.source.source_workload.istio-ingressgateway.source_canonical_service.istio-ingressgateway.source_canonical_revision.latest.source_workload_namespace.tenant-1.source_principal.unknown.source_app.source_version.source_cluster.Kubernetes.destination_workload.unknown.destination_workload_namespace.unknown.destination_principal.unknown.destination_app.unknown.destination_version.unknown.destination_service.app-1.tenant-1.svc.cluster.local.destination_canonical_service.unknown.destination_canonical_revision.latest.destination_service_name.app-1.destination_service_namespace.unknown.destination_cluster.unknown.request_protocol.http.response_code.503.grpc_response_status.response_flags.UH.connection_security_policy.unknown`

With tags separated by dots its pretty impossible to parse due to service names always have dots. Like:
`destination_service.app-1.tenant-1.svc.cluster.local.destination_canonical_service`

So my question is:
- Is there a way to configure tags separator after 1.18? 
If we cant configure or change this behavior stats sinks are pretty un-useful 

### Version

```Text
client version: 1.18.0
control plane version: 1.18.0
data plane version: 1.18.0 (2 proxies)
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by zirain** [comment]
cc @kyessenov

**Comment by pintonunes** [comment]
The only workaround I found so far was to enable the emit_tags_as_labels = true. This way I can get tags in the grpc message already separated:

```
    - applyTo: BOOTSTRAP 
      patch:
        operation: MERGE
        value:
          stats_sinks:
          - name: "envoy.stat_sinks.metrics_service"
            typed_config:
              '@type': type.googleapis.com/envoy.config.metrics.v3.MetricsServiceConfig
              emit_tags_as_labels: true
              transport_api_version: V3
              grpc_service:
                envoy_grpc:
                  cluster_name: envoy_metrics_service
```

               
![image](https://github.com/istio/istio/assets/37883272/25698daa-9293-4d38-8213-63809e5d6ffb)

The side effect is that the proxy will emit istio metrics twice. With and without labels.

**Comment by howardjohn** [comment]
Just wondering, is there a reason you are not using /stats/prometheus which is prometheus format instead of statsd?

**Comment by zirain** [comment]
PULL vs PUSH mode?

**Comment by howardjohn** [comment]
Ooops, didn't realize the sink

**Comment by kyessenov** [comment]
There are really two issues here:
* statsd sink should probably escape dots in the tag value;
* metrics_sink should probably strip tags from the metric name when the emit tags as labels is set.

Would those address your concern?

Neither statsd nor metrics_service are truly supported by Istio. We're committing to OTLP metric sinks though which is fairly similar to metrics_service.

**Comment by kyessenov** [comment]
Re: item 2 - otel doesn't have this problem since it has an option to use tag extract name that is set by default:

```
metrics:<name:"istiocustom.istio_requests_total" sum:<data_points:<attributes:<key:"reporter" value:<string_value:"destination" > > attributes:<key:"source_workload" value:<string_value:"productpage-v1" > > attributes:<key:"source_canonical_service" value:<string_value:"productpage-v1" > > attributes:<key:"source_canonical_revision" value:<string_value:"version-1" > > attributes:<key:"source_workload_namespace" value:<string_value:"default" > > attributes:<key:"source_principal" value:<string_value:"unknown" > > attributes:<key:"source_app" value:<string_value:"productpage" > > attributes:<key:"source_version" value:<string_value:"v1" > > attributes:<key:"source_cluster" value:<string_value:"client-cluster" > > attributes:<key:"destination_workload" value:<string_value:"ratings-v1" > > attributes:<key:"destination_workload_namespace" value:<string_value:"default" > > attributes:<key:"destination_principal" value:<string_value:"unknown" > > attributes:<key:"destination_app" value:<string_value:"ratings" > > attributes:<key:"destination_version" value:<string_value:"v1" > > attributes:<key:"destination_service" value:<string_value:"server.default.svc.cluster.local" > > attributes:<key:"destination_canonical_service" value:<string_value:"ratings" > > attributes:<key:"destination_canonical_revision" value:<string_value:"version-1" > > attributes:<key:"destination_service_name" value:<string_value:"server" > > attributes:<key:"destination_service_namespace" value:<string_value:"default" > > attributes:<key:"destination_cluster" value:<string_value:"server-cluster" > > attributes:<key:"request_protocol" value:<string_value:"http" > > attributes:<key:"response_code" value:<string_value:"200" > > attributes:<key:"grpc_response_status" value:<string_value:"" > > attributes:<key:"response_flags" value:<string_value:"-" > > attributes:<key:"connection_security_policy" value:<string_value:"none" > > time_unix_nano:1687904866071008000 as_int:10 > aggregation_temporality:AGGREGATION_TEMPORALITY_CUMULATIVE is_monotonic:true > >
```

**Comment by pintonunes** [comment]
Ok, let me give you the full context. 
We built an external-push KEDA scaler for istio. All proxies are configured to push/stream metrics to the external scaler (thats why we need to push metrics) and then the scaler collects metrics and inform KEDA about the counter rate values. So far so good.
We've been using this since istio 1.14 (if im not wrong). 
Everything works great besides the fact that we have a couple of namespaces that runs tests and creates lots of short lived pods. Since telemetry v2, istio does not expire metrics. So we have gateways being OOM killed on those namespaces from time to time.
Now we have 1.18 that finally expire metrics again (awesome feature guys) but the metrics format was changed. 

In the scaler we are splitting metric names by  `;.;`  and by `=.=`. This way we can extract all labels and values.
Now with 1.18 we cant cause everything is dot separated. 

@kyessenov:
"metrics_sink should probably strip tags from the metric name when emit_tags_as_labels is set." - True. But generates metrics twice (in both formats). Meaning, all istio_* metrics are duplicated. We have metrics with labels extracted from the name with labels on the grpc message and metrics without the labels extracted from the name. So basically we have a metrics like:
`istiocustom.istio_requests_total` and the same metric like `istiocustom.istio_requests_total.reported.source..........etc etc`

statsd I didnt test it yet since everything was working fine with grpc and metrics_service.

But something catch my attention on your message.  statsd and metrics_service are not fully supported by istio but OTLP is. So im glad to change the scaler to a supported sink. Can you pin point some documentation about the metrics OTLP sink? Cause I couldn't find any on istio or envoy.

**Comment by zirain** [comment]
OTLP sink will release in envoy's next major version, see https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.27/v1.27.0

**Comment by pintonunes** [comment]
We can close this one. For now I found a workaround using regex.

**Comment by kyessenov** [comment]
@pintonunes 

Otel metrics should work with the next version, here is some preliminary testing https://github.com/istio/proxy/pull/4782.
I don't think it generates duplicate methods with tags and without tags. These labels are generated as labels at the source, so combining them back into the statsd name has to be intentional somewhere in Envoy.

**Comment by akashjain971** [comment]
I am trying to get the open telemetry sink to work with EnvoyFilter not able to in both Istio 1.20 and 1.23.
With 1.20, istio-proxy is stuck in PodInitializing state and eventually killed by PostStartHook.
With 1.23, istio-proxy is coming up but it does not reflect in the BOOTSTRAP config.
Is there anything wrong with this envoy filter?

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: stats-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: istio-gateway
  configPatches:
    - applyTo: BOOTSTRAP
      match:
        context: GATEWAY
      patch:
        operation: MERGE
        value:
          static_resources:
            clusters:
            - name: grpc-cluster
              connect_timeout: 1.25s
              type: LOGICAL_DNS
              lb_policy: ROUND_ROBIN
              dns_lookup_family: V4_ONLY
              typed_extension_protocol_options:
                envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
                  "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
                  explicit_http_config:
                    http2_protocol_options: {}
              load_assignment:
                cluster_name: grpc-cluster
                endpoints:
                - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: telegraf-service.istio-system.svc.cluster.local
                          port_value: 6999
          stats_sinks:
          - name: envoy.stat_sinks.open_telemetry
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.stat_sinks.open_telemetry.v3.SinkConfig
              grpc_service:
                envoy_grpc:
                  cluster_name: grpc-cluster

```
