### ISSUE TITLE
AuthorizationPolicy rules not working as expected

### ISSUE THREAD

**Issue by naimadswdn** [istio/istio#45703]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi, 

I am trying to implement JWT token validation using Istio. 
I am running Kubernetes on AKS, Istio and k8s version below. I installed Istio using Helm. 

What I am trying to do, is to enforce JWT token validation on all patches, that are starting with `/api/*`. 
Anyway, what Istio is actually doing, it is enforcing JWT token validation on ALL patches. 
I tried many combinations and it simply doesn't work as per documentation: 
https://istio.io/latest/docs/reference/config/security/authorization-policy/#Operation

My code: 
```
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: validate-jwt-token
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingress
  jwtRules:
  - issuer: MY_ISSUER
    jwksUri: MY_JKWS_URI
    forwardOriginalToken: true

---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: validate-jwt-token
  namespace: istio-system
spec:
  action: ALLOW
  selector:
    matchLabels:
      istio: ingress
  rules:
  - to:
    - operation:
        hosts:
        - 'MY_HOST'
        paths:
        - /api/*
    when: 
    - key: request.auth.audiences
      values:
      - MY_AUDIENCE
```

I am using Istio gateway to expose outbound traffic from the cluster. 
I have a VirtualService configured as well. 

When I try to run: 
`https://MY_HOST/api/something`

I am getting 403, because JWT token is missing - **that is expected**. 

But when I try to run: 
`https://MY_HOST/not-api/something`

I am also getting 403 error, despite this path should **not** be protected with JWT token validation. 

I tried different combination, like replacing `when` with `from` -> it is always returning the same result. 

I am able to achieve my goal with the following manifest for the AuthorizationPolicy:
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: validate-jwt-token
  namespace: istio-system
spec:
  action: ALLOW
  selector:
    matchLabels:
      istio: ingress
  rules:
  - to:
    - operation:
        hosts:
        - 'MY_HOST'
        paths:
        - /api/*
    when: 
    - key: request.auth.audiences
      values:
      - MY_AUDIENCE
  - to:
    - operation:
        methods:
        - GET
        paths:
        - "not-api/*"
```

But I believe it should not works like that. I am saying: *Please validate JWT on all endpoints with prefix `/api/*`*, but Istio is doing: *I am requiring JWT token on ALL endpoints*.

Could you please help me to understand why it is happening like that? 

### Version

```Text
~ istioctl version
client version: 1.17.3
control plane version: 1.18.0
data plane version: 1.17.2 (3 proxies), 1.18.0 (13 proxies)

~ kubectl version --short
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.24.10

~ helm version --short
v3.12.0+gc9f554d
```

### Additional Information

I have mTLS enabled for whole service mesh traffic.

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [X] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by keithmattix** [comment]
Your last AuthorizationPolicy is correct; if at least 1 ALLOW policy exists and an inbound connection/request doesn't match it, that request is denied

**Comment by naimadswdn** [comment]
Hmm, that is interesting. That means there is no difference between setting path `/api/*` or `'*'`, because both will be handled the same way? 

I would expect, that when a request did not match an ALLOW policy rule, it will follow the default behavior which in case of AuthorizationPolicy is ALLOW.

**Comment by keithmattix** [comment]
From the docs here: https://istio.io/latest/docs/reference/config/security/authorization-policy/

    1. If there are any CUSTOM policies that match the request, evaluate and deny the request if the evaluation result is deny.
    2. If there are any DENY policies that match the request, deny the request.
    3. If there are no ALLOW policies for the workload, allow the request.
    4. If any of the ALLOW policies match the request, allow the request.
    5. Deny the request.
    
 The simplest way to accomplish what you're describing would be to provide a second rule that's the inverse of your first (i.e. notPaths) that doesn't have the JWT requirement:
 
 ```yaml
rules:
- to:
    - operation:
        hosts:
        - 'MY_HOST'
        paths:
        - /api/*
    when: 
    - key: request.auth.audiences
      values:
      - MY_AUDIENCE
- to:
    - operation:
        hosts:
        - 'MY_HOST'
        notPaths:
        - /api/*
 ```

**Comment by naimadswdn** [comment]
Ok, got it now. Points 4 and 5 from the referenced docs are the key part for my case. 

So that is definitely not an issue, I will close the report. 

Thank you very much for the explanation @keithmattix. Really appreciated! 

For the community, I will add that if you want to **not** enforce JWT token validation on subpath of the `/api/*`, you need to define a third rule. Example: 

```
rules:
# actual token validation rule
- to:
   - operation:
       hosts:
       - 'MY_HOST'
       paths:
       - /api/*
   when: 
   - key: request.auth.audiences
     values:
     - MY_AUDIENCE
# do not validate token for /api subpath
- to:
   - operation:
       hosts:
       - 'MY_HOST'
       paths:
       - /api/v3/api-docs/*
       - /api/swagger
# all that is not related to /api endpoint
- to:
   - operation:
       hosts:
       - 'MY_HOST'
       notPaths:
       - /api/*
```
