### ISSUE TITLE
Duplicate domain with different case resulting in all new istio-proxy containers in a cluster to crash

### ISSUE THREAD

**Issue by nirvanagit** [istio/istio#45719]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

If there are 2 virtual services with the same host string, which differ in case, then istiod pushes those configurations to envoy, resulting in new envoy proxy's to crash, and existing envoyproxy to create an error state (but limits from the existing proxy's to get any RDS updates)

VS1
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews-route
spec:
  hosts:
  - reviews.prod.svc.cluster.local
  http:
  - name: "reviews-v1-route"
    route:
    - destination:
        host: reviews.prod.svc.cluster.local
```

VS2
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews-route
spec:
  hosts:
  - Reviews.prod.svc.cluster.local ## NOTICE THE CAPITAL R
  http:
  - name: "reviews-v1-route"
    route:
    - destination:
        host: reviews.prod.svc.cluster.local
```

This results in istiod sending these configurations to envoyproxy, which results in crashloop backoff of proxy containers.
The error envoy throws is:
```sh
warning	envoy config	gRPC config for type.googleapis.com/envoy.config.route.v3.RouteConfiguration rejected: Only unique values for domains are permitted. Duplicate entry of domain rtb.intuit.platform.servicesfabric.serviceregistry.mesh in route 80
```

### Version

```Text
1.13.5
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
