### ISSUE TITLE
Unable to create http cache EnvoyFilter

### ISSUE THREAD

**Issue by Andy-Dufresne1994** [istio/istio#45748]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

I tried to apply the following EnvoyFilter config to make a http cache filter;
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: http-cache-filter
  namespace: default
spec:
  workloadSelector:
    labels:
      app: user-app
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: ANY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: ADD
        value:
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.cache.v3.CacheConfig"
            "allowed_vary_headers": ["User"]
```
but ended up with the error below (formatted for readability):
```
Error from server: error when creating "cache-filter.yaml": 
admission webhook "validation.istio.io" denied the request: configuration is invalid: 
Envoy filter: can't unmarshal Any nested proto type.googleapis.com/envoy.extensions.filters.http.cache.v3.CacheConfig: json: cannot unmarshal string into Go value of type map[string]json.RawMessage
```

### Version

```Text
$ /root/istio-1.15.1/bin/istioctl version
client version: 1.15.1
control plane version: 1.15
data plane version: 1.15-dev (16 proxies)

$ kubectl version --short
Client Version: v1.22.9
Server Version: v1.22.9

$ helm version --short
v3.8.0+gd141386
```

### Additional Information

$ /root/istio-1.15.1/bin/istioctl bug-report
[bug-report.tar.gz](https://github.com/istio/istio/files/11913257/bug-report.tar.gz)

FYI, I have found the same issue on [stackoverflow](https://stackoverflow.com/questions/75601837/how-to-implement-caching-in-istio-service-mesh-using-envoy-proxy) 

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [X] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions

**Comment by wulianglongrd** [comment]
Note that the element of the `allowed_vary_headers` array is an object, see[ here](https://www.envoyproxy.io/docs/envoy/v1.24.1/api-v3/extensions/filters/http/cache/v3/cache.proto.html).  Below is a correct example:

```
patch:
  operation: ADD
  value:
    typed_config:
      "@type": "type.googleapis.com/envoy.extensions.filters.http.cache.v3.CacheConfig"
      "allowed_vary_headers":
        - exact: User
```

**Comment by eduardosanzb** [comment]
@Andy-Dufresne1994 could you share your whole configuration?

**Comment by eduardosanzb** [comment]
This is the configuration I'm using:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: cache-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingress
      app: cache
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_FIRST
        value:
          typed_config:
              "@type": "type.googleapis.com/envoy.extensions.filters.http.cache.v3.CacheConfig"
              "allowed_vary_headers":
                - exact: "cache-key"
```

Sadly I'm not being get any request cached.

**Comment by wulianglongrd** [comment]
Just to clarify, I have not used this filter, the "correct" example I gave above just means that it can be accepted by istio normally, does not mean that it can achieve your needs, maybe you need to take another look at envoy's documentation. Thanks.

**Comment by zirain** [comment]
this's not a real issue. feel free to reopen.

**Comment by Andy-Dufresne1994** [comment]
> Note that the element of the `allowed_vary_headers` array is an object, see[ here](https://www.envoyproxy.io/docs/envoy/v1.24.1/api-v3/extensions/filters/http/cache/v3/cache.proto.html). Below is a correct example:
> 
> ```
> patch:
>   operation: ADD
>   value:
>     typed_config:
>       "@type": "type.googleapis.com/envoy.extensions.filters.http.cache.v3.CacheConfig"
>       "allowed_vary_headers":
>         - exact: User
> ```

@wulianglongrd Thank you for your help, now it's accepted. However, just like @eduardosanzb said, no request has been cached.

here is my experiment:
1. a simple python user server, respond to different user with different content based on user's request, notice that response has a Vary header to notify intermediate cache or proxies(here is envoy) to cache different  response content according to User header.
```python
from flask import Flask, request, make_response
import datetime

app = Flask(__name__)

@app.route('/user')
def get():
    # Retrieve the username from the User header
    username = request.headers.get('User')

    if username:
        # Generate the response body
        response_body = f"Hello, {username}!\n"
    else:
        response_body = "Oops, no User header found!\n"

    response_body += f"Response generated at: {datetime.datetime.utcnow().strftime('%a, %d %b %Y %H:%M:%S GMT')}\n"

    # Create the response with the body and headers
    response = make_response(response_body)
    response.headers['Vary'] = 'User'

    return response

if __name__ == "__main__":
    app.run(host='0.0.0.0', port=8000)
```
2. deploy it to k8s and expose it with an service:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
        - name: user-app
          image: simple-user-server:latest
          ports:
            - containerPort: 8000
            - apiVersion: apps/v1
---
apiVersion: v1
kind: Service
metadata:
  name: user-server-service
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: user-app

```
3. use postman to send different request with different  User header


### expected:
once requested made for first time, the subsequent request with same header should be responded with an cache content.
I should got a  http code 304 response, and  Date header should not have same value with response content.


### actual got:
every time I got an  new response with http code 200:
```
Hello, Alice!
Response generated at: Fri, 30 Jun 2023 23:38:40 GMT
```
with response Date header has same value with response content:
```
Date: Fri, 30 Jun 2023 23:38:40 GMT
```

any advice would be appreciated! Thanks!
