### ISSUE TITLE
Errors with NLB OpenSSL SSL_connect: SSL_ERROR_SYSCALL. With ELB is working

### ISSUE THREAD

**Issue by ichasco-heytrade** [istio/istio#45751]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi, we are currently using both internal and public ELBs to publish our EKS services. Now, due to a need to publish a websocket, we need to have a NLB, but when deploying this one (in theory it is deployed correctly and has access to the EKS nodes and traffic arrives to it) we can't get it to work.
The error we get is:
```
curl https://XXXXXXXXXX -vvv                                                                                                                                                                                                         35 err 
*   Trying XX.XX.XX.XX:443...
* Connected to XXXXXXXXXX (XX.XX.XX.XX) port 443 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to XXXXXXXXXX:443 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to XXXXXXXXXX:443 
```
This works perfectly with the ELB. I have deployed a parallel NLB and changed only the gateway to go through the new load balancer. But this is not working.

The certificates are created in the same NS with cert-manager (are the same that are used in the ELBs)

Ingressgateway config:

```
istio-internal-nlb-ingressgateway:
  name: "istio-internal-nlb-ingressgateway"
  revision: ""
  replicaCount: 1
  kind: Deployment
  rbac:
    enabled: true
  serviceAccount:
    create: true
    annotations: {}
    name: ""
  podAnnotations:
    prometheus.io/port: "15020"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/stats/prometheus"
    inject.istio.io/templates: "gateway"
    sidecar.istio.io/inject: "true"
  securityContext: ~
  containerSecurityContext: ~
  service:
    type: LoadBalancer
    ports:
    - name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    - name: tls
      port: 15443
      protocol: TCP
      targetPort: 15443
    annotations:
      external-dns.alpha.kubernetes.io/hostname: internal-nlb.dev.XXXX
      service.beta.kubernetes.io/aws-load-balancer-name: "Istio Private NLB"
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
      service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "ManagedBy=Istio"
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    externalIPs: []
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 2000m
      memory: 1024Mi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
  env:
    ISTIO_META_ROUTER_MODE: standard
  labels:
    app: istio-internal-nlb-ingressgateway
    istio: internal-nlb-ingressgateway
  annotations:
    fluentbit.io/exclude: "true"
  tolerations: []
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: service.istio.io/canonical-name
              operator: In
              values:
                - istio-internal-nlb-ingressgateway
          topologyKey: "kubernetes.io/hostname"
  networkGateway: ""
  imagePullSecrets: []
```

Gatway:

```
 - name: private
      selector: internal-nlb-ingressgateway
      servers:
        - port:
            number: 80
            name: http-private-nlb
            protocol: HTTP2
          hosts:
            - "*.XXXXXXXX"
          # tls:
          #   httpsRedirect: true
        - port:
            number: 443
            name: https-private-nlb
            protocol: HTTPS
          tls:
            mode: SIMPLE
            credentialName: wildcard.XXXXXXXXXXX
            minProtocolVersion: TLSV1_2
            maxProtocolVersion: TLSV1_3
          hosts:
            - "*.XXXXXXX"
```

Envoy filters:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: proxy-protocol-internal-nlb
  namespace: istio-ingress
spec:
  workloadSelector:
    labels:
      istio: internal-nlb-ingressgateway
  configPatches:
  - applyTo: LISTENER
    patch:
      operation: MERGE
      value:
        listener_filters:
        - name: envoy.listener.proxy_protocol
        - name: envoy.listener.tls_inspector
```

### Version

```Text
istioctl version                                                                                                                                                                                                                              
client version: 1.18.0
control plane version: 1.18.0
data plane version: 1.17.0 (32 proxies), 1.18.0 (3 proxies)

Client Version: v1.25.6-eks-48e63af
Kustomize Version: v4.5.7
Server Version: v1.25.10-eks-c12679a

We are using Gateway Helm Chart 1.18.0
```


### Additional Information

_No response_

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
