### ISSUE TITLE
API server removed from endpoints in multi-cluster mesh with istio 1.17

### ISSUE THREAD

**Issue by MM53** [istio/istio#45756]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hello,

we are using an istio mesh across two clusters and want to keep the traffic inside the local cluster if not explicitly configured otherwise. These clusters are hosted on-premise and divided into two zones, therefore each cluster has a unique zone. Currently, we are using the `localityLbSetting` of `meshConfig` with the following config to achieve this:

```yaml
    localityLbSetting:
      enabled: true
      distribute:
      - from: region1/zone1/*
        to:
          "region1/zone1/*": 100
      - from: region1/zone2/*
        to:
          "region1/zone2/*": 100
```

Before updating istio to 1.17 from version 1.16.4 there were no issues with this configuration. After the update all endpoints for `kubernetes.default.svc.cluster.local` were removed from the sidecar proxies. All connections to the api-server now fail with an SSL error. For example a call with curl results in the following error:

```bash
$ curl "https://kubernetes.default.svc.cluster.local"
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to kubernetes.default.svc.cluster.local:443
```

Inspired by this older issue https://github.com/istio/istio/issues/31340 we deployed the following `DestinationRule` as a workaround:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: kubernetes
  namespace: default
spec:
  host: kubernetes.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      localityLbSetting: {}
```

We would expect that this extra DestinationRule is not required, since older versions worked flawless without this change. Additionally, there should be a default `serviceSetting` which marks `kubernetes.default.svc` and all services in `kube-system` as cluster local. For `kube-system` services this works without any problem. Therefore, we assume something broke in the 1.17 release. Also updating to 1.17.3 did not fix the unexpected behavior.

### Version

```Text
$ istioctl version
client version: 1.17.3
control plane version: 1.17.3
data plane version: 1.17.3 (2 proxies)

$ kubectl version --short
Client Version: v1.24.12
Kustomize Version: v4.5.4
Server Version: v1.24.13
```

### Affected product area

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [X] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
