### ISSUE TITLE
Kubernetes Ingress Resource does not work

### ISSUE THREAD

**Issue by dvob** [istio/istio#45752]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Following the documentation under https://istio.io/latest/docs/tasks/traffic-management/ingress/kubernetes-ingress/ I'm not able to create an routing using Kubernetes Ingress resource. Maybe there is a missing required configuration which is not documented?

I set up a cluster and Istio as follows:
```
kind create cluster
```

Point DNS `*.mycluster.local` to `docker inspect kind-control-plane | jq -r '.[0].NetworkSettings.Networks.kind.IPAddress'`

`istiooperator.yaml`:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: default
spec:
  meshConfig:
    accessLogFile: "/dev/stdout"
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        overlays:
        - apiVersion: v1
          kind: Service
          name: istio-ingressgateway
          patches:
          - path: spec.type
            value: ClusterIP
        - apiVersion: apps/v1
          kind: Deployment
          name: istio-ingressgateway
          patches:
          - path: kind
            value: DaemonSet
          - path: spec.strategy
          - path: spec.updateStrategy
            value:
              rollingUpdate:
                maxUnavailable: 33%
              type: RollingUpdate
          - path: spec.template.spec.containers.[name:istio-proxy].ports.[containerPort:8080].hostPort
            value: 80
          - path: spec.template.spec.containers.[name:istio-proxy].ports.[containerPort:8443].hostPort
            value: 443
          - path: spec.template.spec.containers.[name:istio-proxy].ports.[containerPort:15021].hostPort
            value: 15021
  values:
    telemetry:
      v2:
        prometheus:
          enabled: false
    pilot:
      autoscaleEnabled: false
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: false
```

`ingressclass.yaml`:
```
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: istio
spec:
  controller: istio.io/ingress-controller
```

Setup Istio:
```
curl -fSsL https://github.com/istio/istio/releases/download/1.18.0/istioctl-1.18.0-linux-amd64.tar.gz | tar xzvf -
./istioctl install -f istiooperator.yaml
kubectl apply -f ingressclass.yaml
```

Install Test App:
```
kubectl create deployment web --image kennethreitz/httpbin
kubectl expose deployment web --port 80
kubectl create ingress web --class=istio --rule="web.mycluster.local/*=web:80"
```

At this point I don't see listeners. The documentation does not state that a Gateway is required but i guess this is the case?

Then I created a Gateway:
```
openssl req -x509 -newkey rsa:2048 -keyout tls.key -out tls.crt -sha256 -nodes -subj "/CN=*.mycluster.local" -addext "subjectAltName = DNS:*.mycluster.local"
kubectl create secret -n istio-system tls default-cert --key=tls.key --cert=tls.crt
```
`gateway.yaml`:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: default-ingress
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443 
      name: default-https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: default-cert
    hosts:
    - "*"
  - port:
      number: 80
      name: default-http
      protocol: HTTP
    tls:
      httpsRedirect: true
    hosts:
    - "*"
```
```
kubectl apply -f gateway.yaml
```

After this I see listeners for 8080 and 8443 but still no route for the ingress:
```
$ ./istioctl proxy-config route istio-ingressgateway-tk29r.istio-system
NAME                                                     VHOST NAME        DOMAINS     MATCH                  VIRTUAL SERVICE
https.443.default-https.default-ingress.istio-system     blackhole:443     *           /*                     404
http.8080                                                *:80              *           /*                     404
                                                         backend           *           /healthz/ready*        
                                                         backend           *           /stats/prometheus*    
```
Hence I get a 404 if I try to reach example app:
```
curl -k -v https://web.mycluster.local
```

### Version

```Text
client version: 1.18.0
control plane version: 1.18.0
data plane version: 1.18.0 (1 proxies)

Client Version: v1.27.1
Kustomize Version: v5.0.1
Server Version: v1.27.3
```

### Affected product area

- [ ] Ambient
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [ ] Control Plane Revisions
